### ISSUE TITLE
Clicking on build status on Github force to re-authorize almost everyday

### ISSUE THREAD

**Issue by rockerhieu** [Shippable/support#1000]
Clicking on a build status link on Github, i.e https://app.shippable.com/builds/54c618528748150e0083586d force me to re-authorize almost everyday. Is it because of the oauth token is expired? It's kinda annoy to me.

**Comment by pmoust** [comment]
Also affected, please extend the expiration date on token.

**Comment by manishas** [comment]
This should be fixed now. Please comment or re-open if you're still running into this problem.
