### ISSUE TITLE
dedicated host: enabled queue?

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1001]
![screenshot 2015-01-26 14 24 21](https://cloud.githubusercontent.com/assets/2493339/5899628/ea86ad58-a566-11e4-81b6-0041735f42b5.png)

Did you guys just enable queueing on dedicated hosts?
If so how to lift/increase the queue limit?

**Comment by manishas** [comment]
@pmoust dedicated hosts do not queue builds, except in rare circumstances. We'll take a look at what's going on with your hosts. Did you see this multiple times or is it happening often?

**Comment by pmoust** [comment]
@manishas as soon as our dev team starts shipping today I will let you know.

**Comment by pmoust** [comment]
@manishas hasn't reoccured, at least it hasn't come to our attention.

**Comment by manishas** [comment]
Thanks for confirming. Closing this since it was an aberration.
