### ISSUE TITLE
Shippable build fails due to "File name too long"

### ISSUE THREAD

**Issue by codeviking** [Shippable/support#1008]
Here's the related build:
https://app.shippable.com/builds/54c9303a27b7640f00c2a4d1

The build fails at compilation, simply due to the error: "File name too long"

It builds locally, just not in shippable's environment.

It may be related to this?
https://github.com/sbt/sbt-assembly/issues/69

**Comment by codeviking** [comment]
@schmmd @jkinkead

**Comment by manishas** [comment]
Thanks for reporting this. We'll work on this fix soon and let you know when it's available.

**Comment by codeviking** [comment]
@manishas Any idea of when a fix will be rolled out for this?  Our build is perpetually broken atm.

**Comment by codeviking** [comment]
(or, alternatively, any pointers as to how we could resolve this on our side)

**Comment by manishas** [comment]
@codeviking I'll give you an ETA in a couple of hours.

**Comment by manishas** [comment]
@codeviking we are having trouble reproducing this at our end. Can you send me your shippable.yml at manisha@shippable.com?

**Comment by manishas** [comment]
@codeviking I am closing this issue for now. If it happens when you re-introduce the code, let us know and we'll take a look. Thanks!
