### ISSUE TITLE
Customize how PostgreSQL starts

### ISSUE THREAD

**Issue by godfat** [Shippable/support#1013]
We want to turn fsync off in order to speed up the tests, is there anyway to configure PostgreSQL? A few options:

* Edit `postgresql.conf`
* Does setting `$PGOPTIONS` work?
* A custom `$SHIPPABLE_POSTGRES_CMD`

I've tried a few hacks to stop and start postgres manually, but none of them worked.

**Comment by ric03uec** [comment]
hi @godfat , you should be able to specify a custom postgres command file by exporting following env variable
```
export SHIPPABLE_POSTGRES_CMD="sudo -u postgres $SHIPPABLE_POSTGRES_BINARY -c \"config_file=$SHIPPABLE_REPO_DIR/my_pg.conf\""
```  
shippable then runs postgres using this command instead of default one.
hope this helps

**Comment by godfat** [comment]
Last time I tried it didn't work. Or can't I use the `env` in `shippable.yml`?

**Comment by ric03uec** [comment]
you need to put in the `env` section in `shippable.yml` only. Sorry I didn't mention that earlier. If you put this in any other section, it wont effect pg because by that time postgres has already started. Inserting this into `env` section makes sure that the export is at the top of the build script and hence correct postgres command is executed. So now your yml should have a section like following

```
env:
 - SHIPPABLE_POSTGRES_CMD="sudo -u postgres $SHIPPABLE_POSTGRES_BINARY -c \"config_file=$SHIPPABLE_REPO_DIR/my_pg.conf\""
```

**Comment by godfat** [comment]
Just tried again, and I don't think this does work?
It's still showing the old command.
This is our current `shippable.yml`:

``` yaml
env:
  - RACK_ENV=test RAILS_ENV=test DEPLOY=1 DATABASE_URL=postgres://postgres:@127.0.0.1/codementor-test DISPLAY=:99.0 SHIPPABLE_POSTGRES_CMD='sudo -u postgres $SHIPPABLE_POSTGRES_BINARY -c config_file=/etc/postgresql/$SHIPPABLE_POSTGRES_VERSION/main/postgresql.conf -c fsync=off'
```

**Comment by ric03uec** [comment]
I just ran a sample build with the following env value
```
env:
  - FOO=fooval SHIPPABLE_POSTGRES_CMD='sudo -u postgres $SHIPPABLE_POSTGRES_BINARY -c config_file=/etc/postgresql/$SHIPPABLE_POSTGRES_VERSION/main/postgresql.conf -c fsync=off'
```
which gives the following console output

![screenshot - 02032015 - 07 02 51 pm](https://cloud.githubusercontent.com/assets/1110988/6034431/4a116e90-abd7-11e4-9d5f-6da32d49ab68.png)

can you verify if you're getting the same console logs or not. 
Also, if you have set `cache=true` can you disable that and then run the build again.

**Comment by godfat** [comment]
No, it didn't show that. I noticed that you're using postgres 9.2, which we're using 9.3. That might be the reason? You might not make postgres 9.3 respect `SHIPPABLE_POSTGRES_CMD`? Also, it would be great if you could provide postgres 9.4.

![screen shot 2015-02-04 at 2 43 34 pm](https://cloud.githubusercontent.com/assets/10416/6036194/4b5d4b7a-ac7c-11e4-9e1b-19f627cdc546.png)

``` yaml
addons:
  postgresql: 9.3
```

**Comment by ric03uec** [comment]
@godfat yes, you're right. The addon that is causing the issue in this case. I'll open an issue internally to track this.
Thanks for the feedback
@manishas can you please remove the `resolved` tag from the issue

**Comment by rageshkrishna** [comment]
@godfat This should be working correctly now. Please try it out and let us know if you're still running in to issues.

**Comment by godfat** [comment]
Looks good now, thank you!

**Comment by lucasmpb** [comment]
Hello guys, Not sure if I should open a new issue, but I'm having the same problem trying to setup the `SHIPPABLE_POSTGRES_CMD` env variable.

```
env:
  global:
    - SHIPPABLE_POSTGRES_CMD="sudo -u postgres $SHIPPABLE_POSTGRES_BINARY -c \"config_file=/etc/postgresql/$SHIPPABLE_POSTGRES_VERSION/main/postgresql.conf\" -c \"fsync=off\" -c \"synchronous_commit=off\""
```
I'm using the postgresql 9.3 addon
```
addons:
  postgresql: '9.3'
```
But it's still using the default cmd 
```
postgres_start 5s
  sudo su -c "sudo -u postgres /usr/lib/postgresql/9.3/bin/postgres -c config_file=/etc/postgresql/9.3/main/postgresql.conf > /dev/null 2>&1 &"
```

Same thing if I echo the env var
```
echo $SHIPPABLE_POSTGRES_CMD 0s  
sudo -u postgres /usr/lib/postgresql/9.3/bin/postgres -c config_file=/etc/postgresql/9.3/main/postgresql.conf
```

I'm using my own host to build (BYOH feature)
