### ISSUE TITLE
Support of Google Container Registry

### ISSUE THREAD

**Issue by JeffMerlet** [Shippable/support#1015]
Do you have on your roadmap (and for when approximatively) to add support for Google Container Registry (https://cloud.google.com/tools/container-registry/)?

**Comment by manishas** [comment]
@JeffMerlet Absolutely. I cannot give you a firm date right now, but watch for upcoming announcements.

**Comment by smvv** [comment]
I'm interested in this feature as well.  Any updates for support on the roadmap?

**Comment by mavarazy** [comment]
+1

**Comment by manishas** [comment]
This is available now. Please check out http://docs.shippable.com/docker_registries/

We also have a demo video at https://www.youtube.com/watch?v=VKedeesHirE 
The video was captured before the GCR UI redesign but should still help with setting everything up.

Please let me know if you have any questions. Thanks!
