### ISSUE TITLE
how to config to use dedicated host

### ISSUE THREAD

**Issue by adamyao** [Shippable/support#1017]
I created an instance on AWS, and added it as dedicated host to shippable, and initialization is successful . But I count not find any docs to tell how to config so that my project will build on this dedicated host. Thanks.

**Comment by manishas** [comment]
Once you set up a dedicated host and initialize successfully, builds will automatically be executed on your host.

**Comment by austinsmorris** [comment]
How long does it take to initialize a dedicated host?  Mine has been queued forever (10 min :)

**Comment by adamyao** [comment]
I could not verify that the build is run on the dedicate host. I have a simple test run which does this:
cd /home/shippable
touch myfirstfile

Then I ssh into my dedicate host, and  cd to /home/shippable, but the file is not there
(my build is https://app.shippable.com/projects/54cbd21e5ab6cc13528a56e6 build#5)

Also does that mean all my other projects will also run on the dedicate host (which is not actually my original intention)?
Thanks a lot

**Comment by manishas** [comment]
@adamyao the build is running on your host. And yes, all projects in the org will run on that host. We are working on some features that will let you configure this a bit more and we will announce these in the next few weeks. Thanks!
