### ISSUE TITLE
Multiple java/maven projects in same repository

### ISSUE THREAD

**Issue by jnath8** [Shippable/support#1018]
I have 4 projects in a single bitbucket repository. One project builds to a war file and has dependency on 3 others which builds to jar libraries. How to configure this in shippable, if possible.

pom.xml exists in each of these projects, but not in the repository root.

**Comment by rageshkrishna** [comment]
@jnath8 You should be able to run your build in any manner you want by defining a `script` tag in your YML file with the commands you need. For example,

````
script:
 # First build all the dependencies
 - cd dependency1 && mvn build
 - cd ../dependency2 && mvn build
 - cd ../dependency3 && mvn build
 # Now build the main project
 - cd ../ && mvn build
````
Would this work for you?

**Comment by bahenc** [comment]
works, thanks

**Comment by manishas** [comment]
Thanks for confirming. Closing this issue.
