### ISSUE TITLE
Install conditional on runtime

### ISSUE THREAD

**Issue by pwalsh** [Shippable/support#1021]
I'm using shippable to run tests on multiple Python runtimes.

For Python 2.x runtimes, I need to install some additional dependencies that *can't* install on Python 3.x runtimes.

How can I conditionally control the install stanza to achieve this?

**Comment by rageshkrishna** [comment]
For Python projects, the `VIRTUALENV_PYTHON` env var should give you the Python version that's being used. You can potentially check the value of that variable in your `install` section and decide to run additional commands.

**Comment by pwalsh** [comment]
How would I check that in the `install` section? Are there docs for this?

Let's say my `install` is:

```
install:
  - pip install -r requirements/test.txt --use-mirrors
```

How would I add such a conditional statement like:

```
install:
  # if py2.7
  - pip install -r requirements/test.txt --use-mirrors && pip install -r requirements/py2.txt --use-mirrors
  # else, do the default install
```

Additionally, in my local env at least (Mac OS X), `$VIRTUALENV_PYTHON` has no value (checked with a range of 2.7 and 3.3 venvs I have here). Searching for documentation on `VIRTUALENV_PYTHON `

**Comment by rageshkrishna** [comment]
$VIRTUALENV_PYTHON is something we're injecting in to the build scripts ourselves.

I think you should be able to do something like this:
````
install:
 - if [ "$VIRTUALENV_PYTHON" == "2.7" ]; then pip install -r py2.txt; else pip install -r py3.txt; fi
````
You can take a look at the "Script" tab on a build if you'd like to see how we're setting up all the environment variables.

**Comment by pwalsh** [comment]
Ok, that makes sense. I still seem to have an error with the `VIRTUALENV_PYTHON` thing though while building. 

Here is my shippable.yaml:
https://github.com/okfn/tabular-validator/blob/master/shippable.yaml

And, here is the build:
https://app.shippable.com/builds/54d085eb33d2890e0001d6e6

The first line of the install sequence for the 2.7 runtime shows:

```
/home/shippable/build/build.sh: line 87: [2.7: command not found
```

**Comment by rageshkrishna** [comment]
Can you try adding spaces after/before the `[` and `]`? I think bash may be getting confused without it.

So, instead of 
````
if ["$VIRTUALENV_PYTHON" == "2.7"]; then pip install -r requirements/test-py27.txt --use-mirrors; else pip install -r requirements/test.txt --use-mirrors; fi
````

do this:

````
if [ "$VIRTUALENV_PYTHON" == "2.7" ]; then pip install -r requirements/test-py27.txt --use-mirrors; else pip install -r requirements/test.txt --use-mirrors; fi
````

**Comment by pwalsh** [comment]
that does it: thanks
