### ISSUE TITLE
shippable ran old version of "script:  " portion

### ISSUE THREAD

**Issue by adamyao** [Shippable/support#1023]
I made changes on the "script:  " portion in the shippable.yaml file, but the shippable kept running the "script:  " portion of an old version of shippable.yaml.  But shippable indeed run the new version of other portions of the shippable.yaml.

**Comment by manishas** [comment]
@adamyao can you point me to 2 builds - one with the old script section, and one with the changed script ?

**Comment by adamyao** [comment]
Thanks Manishas.
The old version build: https://app.shippable.com/builds/54cfe1568320dc0e00957b01
The newer build (with new "script: " portion, but shippable still run the old "script: " portion):   https://app.shippable.com/builds/54d014fac2b2af0e00735b41

**Comment by manishas** [comment]
@adamyao also, can you either paste the old shippable.yml and new shippable.yml here? if you prefer you can also email to manisha@shippable.com

**Comment by adamyao** [comment]
OK, I send you email

**Comment by adamyao** [comment]
Hi Manisha,  Thanks for your help. After I pasted the two files, I found I had an error on my new .yaml file: it has two sections for "script: ", the second is left over from the old file. That's the reason. My apology. You may close the ticket.
Adam

 

     On Monday, February 2, 2015 9:00 PM, Manisha <notifications@github.com> wrote:
   

 @adamyao also, can you either paste the old shippable.yml and new shippable.yml here? if you prefer you can also email to manisha@shippable.com—

**Comment by manishas** [comment]
Thanks! Closing this issue.
