### ISSUE TITLE
How to trigger  project-B build from project-A

### ISSUE THREAD

**Issue by adamyao** [Shippable/support#1024]
I can only find one sentence in the docs about how to trigger  project-B build from project-A:

For example, in order to trigger build for project B, add the following line in any script section of project A’s shippable.yml.
curl -XPOST https://api.shippable.com/projects/<project_B_project_id>/build?token=$SHIPPABLE_API_TOKEN

I can not make it work. What is this $SHIPPABLE_API_TOKEN, how to get it, is it from a build of project_B?

Thanks.

**Comment by rageshkrishna** [comment]
@adamyao Sorry about the bad documentation on this. That feature has been deprecated and we're no longer exposing the $SHIPPABLE_API_TOKEN during the build.

We will be enabling full access to our API with managed tokens. You might want to follow https://github.com/Shippable/support/issues/768 for updates on that.

**Comment by manishas** [comment]
@adamyao how important is this scenario for you?

**Comment by adamyao** [comment]
Thanks, Rageshrishna and Manishas for quick response.
The scenario is very import to us: it is a link in our continuous deployment circle, after successful build of the unit/functional test project, we want it to trigger the integration test project build.

**Comment by manishas** [comment]
@adamyao we will work on making this available in the next couple of weeks. Hope that works for you.

**Comment by chriskinsman** [comment]
Need this also and just waiting...

**Comment by avinci** [comment]
this is coming in a few days @chriskinsman. we are prepping docs etc for this. stay tuned.

**Comment by adamyao** [comment]
Hi avinci, any update on this one?  Thanks.

**Comment by manishas** [comment]
being tested as we speak...

**Comment by adamyao** [comment]
Thanks!

**Comment by manishas** [comment]
Sorry for the delay in updating these issues. Now available - http://blog.shippable.com/daisychaining-builds-with-our-new-public-api
