### ISSUE TITLE
Build doesn't start

### ISSUE THREAD

**Issue by evgeny-goldin** [Shippable/support#1025]
Hi,

Could you have a look at https://app.shippable.com/builds/54d0a39233d2890e0001d9d9.
It just doesn't start. Thanks!

**Comment by rageshkrishna** [comment]
@evgeny-goldin Did you delete that build? I was hoping to take a look at this but I can't seem to find it anymore.

**Comment by evgeny-goldin** [comment]
Hi, no, I deleted nothing. Here's another one, which I just triggered:
https://app.shippable.com/builds/54d0be1133d2890e0001dc97
https://www.dropbox.com/s/4g5a6iapni0fd2v/Screenshot%202015-02-03%2013.23.43.png?dl=0

**Comment by evgeny-goldin** [comment]
The first one (https://app.shippable.com/builds/54d0a39233d2890e0001d9d9) is also still in "Waiting for build information..."

https://www.dropbox.com/s/iy5mu6p9gu6sryw/Screenshot%202015-02-03%2013.30.17.png?dl=0

**Comment by rageshkrishna** [comment]
I see the issue now: "Custom images may only be used with dedicated hosts. No initialized dedicated host was found for subscription evgeny-goldin.". 

Do you have a `build_image` defined in your YML file and no dedicated hosts?

We'll be completely reworking how we surface these errors in the UI. I agree that this is completely buggy at the moment.

**Comment by evgeny-goldin** [comment]
Yes, I have a custom image but no dedicated host, I assumed that was an old requirement that was later lifted off and one can use custom build images on Shippable infrastructure. 

Ok, I see the problem now. Thanks!

**Comment by evgeny-goldin** [comment]
Will try to set up one on AWS.

**Comment by manishas** [comment]
@evgeny-goldin I am going to close this issue since your question is addressed. Please open up a feature request if you want to bring the AWS dedicated host up and down...
