### ISSUE TITLE
Shippable is always shown as default on status

### ISSUE THREAD

**Issue by velo** [Shippable/support#1026]
![image](https://cloud.githubusercontent.com/assets/136590/6026117/e8a95e82-abbe-11e4-9071-cf0367b7b860.png)

Other CI services put their name on pull request status... shippable just writes default ....

**Comment by manishas** [comment]
@velo thanks for reporting this! we'll take a look at why this is happening...

**Comment by manishas** [comment]
@velo do you see this every time? we have not been able to repro this at our end. we'll take a deeper look but was wondering if this happens for all repos or just under certain conditions.

**Comment by velo** [comment]
yes, all the time.

I'm talking about the status message....  take a look Shippable reports as 'default', Travis reports as 'continuous-integration/travis-ci' which is way more meaningful then 'default'

**Comment by rageshkrishna** [comment]
@velo Can you try now? It should be showing `Shippable` instead of `default`.

**Comment by velo** [comment]
![image](https://cloud.githubusercontent.com/assets/136590/6059839/5ce57df8-ad1d-11e4-930d-dc500fff29f0.png)

Nice =D
Awesome, I did not expected to see that this soon, thanks!
