### ISSUE TITLE
Recently toggled Third-party application access policy in GitHub and now cannot see org in shippable dashboard

### ISSUE THREAD

**Issue by bobeagan** [Shippable/support#1028]
I tried turning on the 3rd party application security for our org (https://github.com/blog/1941-organization-approved-applications) and was no longer able to access our org from the shippable dashboard.  I then approved access in GitHub for shippable to access private data for my org.  Still no access to the dashboard.  Then I tried disabling the security policy to revert back to the previously working state but still the dashboard does not allow me to access my org in shippable.  Is there some kind of cache for how frequently it checks for allowed orgs? I tried logging out and then back in but that didn't help.  Any suggestions would be appreciated as we're not able to check any of our builds until this is resolved.

**Comment by bobeagan** [comment]
This seems to be working now.

**Comment by manishas** [comment]
@bobeagan we sync every 60 minutes, so that's why it started working after a while. That said, we're improving this experience in the next couple of days and you'll be able to force a sync.
