### ISSUE TITLE
Anonymous browser can't see my test results

### ISSUE THREAD

**Issue by alexaltair** [Shippable/support#1029]
I've got a Shippable badge on my repo. When click on it and open the [link](https://app.shippable.com/projects/54d275965ab6cc13528ad353/builds/latest) in an incognito window,  I can see the general build results. But when I click on the "Tests" tab, it says "No test results found.". If I open the same link while logged in, I see the individual numbers of how many tests passed, etc.

Is this an intentional obscuring of information for privacy reasons, or a bug? I'd like the general public to be able to see the test results in the same spirit as having the badge on my repo.

**Comment by alexaltair** [comment]
Similarly, in [this pull request](https://github.com/alexaltair/calico/pull/1), there's a link under "Show all checks" > ["Details"](https://app.shippable.com/builds/54d2a1753a8ff910008b7f59). When I open this in an incognito window, I get dropped on the Shippable homepage.

**Comment by manishas** [comment]
This is now available... you can view your build results through an anonymous browser :)
