### ISSUE TITLE
after_success build container

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1030]
We are using a fleet of dedicated hosts for Shippable.

After a successful build on master I would like to create a plain data container that will hold what is in the Shippable workdir (i.e. checked-out code, fetched dependencies and what not).

Using `commit_container` is not an option as the private docker image we use to run tests with is rather large and contains a toolchain that allows the application to self-bootstrap as well as running extra services to perform unit/acceptance tests against.

Would it be possible to allow accessing the docker daemon on host to build a container based on a Dockerfile in the git repo?

@rageshkrishna @manishas I would love to get in a hangout with you guys to explain our situation. I believe a lot of DevOps teams are or will be facing the same issues.

**Comment by pmoust** [comment]
If you implement the feature request on #987 might also solve this as we could `commit_container:` a plain bootstrapped data container and having all other services (node, php, mongo, solr etc) in linked containers.

But I do believe a quicker work-around is adding a section in `shippable.yml` (like `build_container: organization/name` that will seed from a Dockerfile in the tested git repo codebase) or a param on `after_success` to interact with Host

**Comment by manishas** [comment]
@pmoust I'll send you a hangout request in a bit... need to check availability of some folks on our side. I'm targeting Monday morning PST, which will be evening for you.

**Comment by pmoust** [comment]
@manishas sounds fine.

**Comment by manishas** [comment]
@pmoust I sent you a hangout invite for Thursday at 9am PST. Does that work for you?

**Comment by pmoust** [comment]
@manishas thanks, i just RSVPed.

**Comment by pmoust** [comment]
Needs some expanding with the newly released feature.

**Comment by pmoust** [comment]
This has been implemented, thanks
