### ISSUE TITLE
Builds stuck processing when completed

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#1032]
The builds complete, but stay stuck in the processing state. I have to cancel to get the next to run.

Builds that stuck so far: 
- 54d379c308ac4d0e00c88893 (cancelled)
- 54d37cab08ac4d0e00c88939 (cancelled)
- 54d381ed08ac4d0e00c88a39 (still processing)

**Comment by pmoust** [comment]
Same.

**Comment by rageshkrishna** [comment]
Thanks for reporting. I'm looking in to this.

**Comment by rageshkrishna** [comment]
One of our queues backed up. We've reset the queue processor and it has completed processing all of the pending updates. Your builds should be running normally now.

Please let me know if you're still seeing issues.

**Comment by tomsterritt** [comment]
Looks fine now, thanks!

**Comment by tomsterritt** [comment]
It's stopped running altogether now - not triggered by Github and won't do anything when I try to run manually?

**Comment by ybroze** [comment]
Yes, we're having similar difficulties -- no builds are being triggered whatsoever.

**Comment by ybroze** [comment]
@rageshkrishna, for reference, here's our project id, if it helps. 546e0896d46935d5fbbe2131

**Comment by ybroze** [comment]
All is working again. Incidentally -- it may be a good feature to deduplicate multiple rapid-fire requests, as we inevitably kicked off! :goat:

**Comment by tomsterritt** [comment]
^ Yes please, just been through and cancelled all the manual requests I didn't think were going through - so many email :scream:

**Comment by manishas** [comment]
Closing this issue since the original problem is no longer an issue.
