### ISSUE TITLE
Maven central proxy...

### ISSUE THREAD

**Issue by velo** [Shippable/support#1033]
Hi guys,

You probably spend a good ammount of money on internet to contact repo1.maven.org/maven2 and repo.maven.apache.org/maven2/

You probably can save a lot by setting up you own "central" using nexus or artifactory.... 

For me, as user, it would save tons of time downloading maven artifacts.

**Comment by manishas** [comment]
This is not on our near term roadmap, especially with all the build system upgrades that were recently announced. Downloads are super fast and we're also adding folder level caching.

Closing as deferred.
