### ISSUE TITLE
Failling to download artifacts from maven central

### ISSUE THREAD

**Issue by velo** [Shippable/support#1034]
My build always fail to download some artifact.
https://app.shippable.com/builds/54d3abef08ac4d0e00c897b7

The problem is the artifacts are available at maven central repository.

I removed everything here and tried all fresh, it works, just fine.

Is there and internet connectivity problems?

**Comment by manishas** [comment]
@velo for your latest builds, I see an error complaining about No plugins found for prefix coveralls...

can you try the workaround here - https://vzurczak.wordpress.com/2014/04/04/no-plugin-found-for-prefix/

**Comment by velo** [comment]
Seems the central download issue is now fixed. Thanks

**Comment by manishas** [comment]
Thanks! I am closing this issue but please let me know if you need help with anything else.

**Comment by velo** [comment]
The problem happened again
https://app.shippable.com/builds/54e37274d551ba0f0082fea1

And the artifact is on central...
http://repo1.maven.org/maven2/org/apache/geronimo/specs/geronimo-stax-api_1.0_spec/1.0/
