### ISSUE TITLE
I need to add additional repositories for maven into settings.xml

### ISSUE THREAD

**Issue by venkateshamurthy** [Shippable/support#1036]
Is it possible add custom repository urls some where (basically settings.xml customized) during maven build?

Today i am failing in https://app.shippable.com/builds/54d4db5421e8ee0e00db520a.

Please help

**Comment by manishas** [comment]
@venkateshamurthy apologies for dropping the ball on this. Do you still need help with this?

**Comment by venkateshamurthy** [comment]
thanks for reaching out on this.
Well, the build history is wiped out and am not able to recollect which project it was.
So in general if there are third party repositories that i need to add say as part of settings.xml(usually such dependencies are not to be added in maven pom.xml and hence my question) . does shippable allow that? if so what is the way.
If there is clear example on this it might help many. 
once i get a response from you on this; i will try set up and then get back to u with more details. 


     On Thursday, 2 July 2015 10:27 PM, Manisha <notifications@github.com> wrote:
   

 @venkateshamurthy apologies for dropping the ball on this. Do you still need help with this?—

**Comment by manishas** [comment]
This is an old issue and we've revamped our build system since. Closing.
