### ISSUE TITLE
Enable repo gives Internal Server Error

### ISSUE THREAD

**Issue by MarneeDear** [Shippable/support#1037]
Github username:  MarneeDear

I can see my repos from my organization but when I click Enable I get "Internal Server Error".

![marnee_shippabe_error](https://cloud.githubusercontent.com/assets/5660628/6089836/53670d5a-ae26-11e4-99c2-c6b94b08cc1a.png)

**Comment by manishas** [comment]
@MarneeDear we're looking into this. Does the same thing happen if you try to enable a repo under MarneeDear?

**Comment by MarneeDear** [comment]
Enabling a repo under MarneeDear does seem to work.

**Comment by manishas** [comment]
@MarneeDear one more thing - on your org page on Shippable, can you click on 'sync repos' at the top and then try enabling the repo you want?

**Comment by MarneeDear** [comment]
I have tried that a few times now.  I tried again just now and I get the same error.

**Comment by manishas** [comment]
@marneedear sorry about this. We have fixed this issue, so can you please try again? It should work now.

**Comment by MarneeDear** [comment]
Yep.  That worked.  Thank you!
