### ISSUE TITLE
PhantomJS crashes on ubuntu14/node_js image

### ISSUE THREAD

**Issue by iislucas** [Shippable/support#1039]
See: https://app.shippable.com/builds/54d58eef5e46b00e000f833c

Looks like phantomjs needs to be installed locally?

**Comment by rageshkrishna** [comment]
@iislucas These images only come with the base language tools. You'll need to install phantomjs by scripting it in to your YML file. Only shippable/minv2 has the complete set of tools pre-installed.

**Comment by iislucas** [comment]
@rageshkrishna : Thanks! Do you know where I can find out more about the shippable/minv2 image - seems a little hard to find out what it is exactly - although I did notice it was the default image chosen on shippable.

**Comment by manishas** [comment]
@iislucas minv2 has all the main language versions and services deployed. 
Look at this for - http://docs.shippable.com/en/latest/index.html

**Comment by iislucas** [comment]
@manishas : thanks! But it doesn't say much about what's actually in shippable/minv2 ... but I'll just use that for now. Thanks.

**Comment by manishas** [comment]
Absolutely understand. We'll improve documentation to make it more clear. Let me know if the image works for you.

**Comment by iislucas** [comment]
It works. Thanks!

**Comment by manishas** [comment]
Closing.
