### ISSUE TITLE
passes when i pasu but when I have a pull request it fails are away

### ISSUE THREAD

**Issue by senbay** [Shippable/support#1040]
onmer85 / Tinville

Build History
Pull Requests
Notifications *
 Build History

Build Group	Status	Triggered	Duration	Changeset	Branch	Committer	Actions
1178	  failed  	Today at 5:39 PM	a minute	4db7bda (PR#480)	Sprint8	senay	 
Build Item	Status	Runtime Env.	Triggered	Duration	Test Count	Passed	Failed	Branch Cov.	Line Cov.
1178.1	  failed  	python 2.7  	10 minutes ago	a minute	0	0	0	0.00%	0.00%
1177	  processing  	Today at 5:39 PM

**Comment by manishas** [comment]
@senbay can you send me a link to the failed builds?

**Comment by senbay** [comment]
This can be closed. Thank you

**Comment by manishas** [comment]
Thanks for the update!
