### ISSUE TITLE
Different tests for Server side & Client side

### ISSUE THREAD

**Issue by podoler** [Shippable/support#1041]
Hi,
We have two different tests & coverage,
one for server side and the other for client side,
Is there any way to see both different reports for tests & coverage for both of them?

Thank you,
Yarin Podoler
StartApp Team

**Comment by rageshkrishna** [comment]
@podoler How about kicking off a matrix build by using the `env` tag in your YML like so:
````
env:
 - TESTS=server
 - TESTS=client
````
With this configuration, for every commit we'll trigger two builds (one with `TESTS=server` and the other with `TESTS=client`). You can use this to tell your test runner what to do. Each build will get its own tests and coverage tab.

Would this work for you?

**Comment by podoler** [comment]
This could work for the tests but would create other issues with the way we work today,
after a successful build we will automatically upload the artifacts to s3 and send a webhook to deploy them, this process will get messier if we need both of the builds to pass in order to continue...

**Comment by manishas** [comment]
This has open for a long time and we haven't received any +1s for it, so at this point, we don't think this is going to be implemented in the near future. Closing as deferred.
