### ISSUE TITLE
Is there a way to only build pushes to a specific branch?

### ISSUE THREAD

**Issue by agius** [Shippable/support#1044]
We are trying out Shippable, but don't want it to build all branches for our repo. 

When trying other CI systems, there are usually specific tweaks we have to make, and we don't want to put those into master until we are ready to leave our current solution. At the very least, there's no point in including `shippable.yml` until we're sure we're going to use it long-term.

Don't see anything in the documentation or config sections about how to do this.

**Comment by manishas** [comment]
@agius you can put the shippable.yml only in the branch you want to build. In the yml, you should specify - 
branches:
     only:
         - branch_name

You can look at http://docs.shippable.com/en/latest/config.html#include-exclude-branches for this config.

**Comment by naveensky** [comment]
@manishas - I have been trying to include only master branch in my shippable but build seems to trigger for all branches. I have read the doc mentioned above, any help here ?

Relevant section of shippable.yml

# include
branches:
  only:
    - master

**Comment by manishas** [comment]
@naveensky can you point me to a build that was triggered for a branch other than master?

**Comment by naveensky** [comment]
@manishas - The build url is https://app.shippable.com/builds/54dbb2e21182c511006438cc

**Comment by manishas** [comment]
can you send me your shippable.yml? Do you have a yml file in every branch?

**Comment by naveensky** [comment]
You can look at the complete file at
https://gist.github.com/naveensky/0bc6ca555925753edc99

Cheers,
Naveen Gupta
+91.989-141-0701
+91.114-576-8419

Green Apple Solutions Pvt. Ltd.
http://www.greenapplesolutions.com

Disclaimer:
The information contained in this e-mail is confidential, and is intended
for the named person's use only. It may contain proprietary or legally
privileged information. If you have received this email in error, please
notify the sender and delete it immediately. You must not, directly or
indirectly, use, disclose, distribute, print, or copy any part of this
message if you are not the intended recipient

Internet communications are not secure. You should scan this message and
any attachments for viruses. Green Apple Solutions does not accept any
liability for loss or damage which may result from receipt of this message
or any attachments.

**Comment by manishas** [comment]
@naveensky one more question - is the only tag only specified in the master branch or does the shippable.yml in the develop branch also have this tag? I suspect you added it to master branch only.

If you have a branch you want to exclude, you will either need to delete shippable.yml from that branch, or have it there with the keywords
branches:
    only:
       - <branchname>

**Comment by manishas** [comment]
@naveensky i will definitely update documentation since this is a bit confusing.... to explain further, when a webhook for an enabled repo comes in, we check if the branch has shippable.yml and if it does, we follow the config. Now if the shippable.yml in develop branch does not include these keywords, we will build the branch regardless of what's in the shippable.yml in master branch.

**Comment by naveensky** [comment]
great, got it working. Thanks for the tip about updating shippable in every branch. Yeah, I guess you should update the documentation, its slightly confusing.

On other note, is there a better way of pushing artifacts to github than the hackish way I have done in my shippable ? Do I open a separate ticket for this query?

**Comment by manishas** [comment]
@naveensky can you open up a new issue? i will tag with 'question' and ask someone from our team to look at this. 

I am closing this issue since the original qs is answered.
