### ISSUE TITLE
Pushes to Bitbucket does not trigger build

### ISSUE THREAD

**Issue by HenrikOssipoff** [Shippable/support#1045]
It seems that pushes to our Bitbucket repositories does not trigger any build in Shippable today. Syncing the repository in Shippable does not yield anything either.

Repository ID is 548968ddd46935d5fbbfe71b

**Comment by rageshkrishna** [comment]
Hi @HenrikOssipoff, would you mind triggering a webhook build right now? I'm monitoring the logs to figure out what's going on. Thanks!

**Comment by HenrikOssipoff** [comment]
Just triggered one that also did not start a new build.

**Comment by HenrikOssipoff** [comment]
Hello, anything new on this? Thanks.

**Comment by rageshkrishna** [comment]
@HenrikOssipoff I haven't been able to get to the exact cause just yet. There's something unusual happening when we're trying to parse the webhook payload for your project. I have added a few more traces to capture more details about the problem.

Can you please trigger a webhook build once again?

**Comment by HenrikOssipoff** [comment]
I just did another push that triggered a webhook, and this webhook actually caused a build to happen (54db2e391182c511006424c6).

Still a little worried that it didn't work at all yesterday though -- something at odds with Bitbucket perhaps?

**Comment by rageshkrishna** [comment]
I think you're right -- something probably went wrong at BitBucket. We were unable to reproduce the issue with any of our repos on BitBucket. In addition, we haven't changed anything to make it work today!

In any case, I have added more logging today to help debug this if it ever happens again.

**Comment by HenrikOssipoff** [comment]
Sweet, thank you for your time. I'll open a new issue in case we ever see this again. Thank you for a continued awesome service!
