### ISSUE TITLE
Builds Will Not Start

### ISSUE THREAD

**Issue by darylrobbins** [Shippable/support#1046]
Just trying out shippable and I can't get a build to start. When I try to start one on any project, it goes into an endless loop saying "Waiting for build information...". I'm attempting to build from a bitbucket repository.

**Comment by lekhabhargavi** [comment]
Hi @darylrobbins, this is fixed now. Can you please try building a project again and let me know if that works?

**Comment by darylrobbins** [comment]
No, still seems to be broken. I even tried deleting and re-creating the project.

This is what I see after starting a build:
![screenshot 2015-02-10 16 58 29](https://cloud.githubusercontent.com/assets/2270905/6137342/160742f4-b146-11e4-8896-0a77821cdd9c.png)

**Comment by manishas** [comment]
@darylrobbins sorry about this. The fix was reverted due to an unrelated issue and will be redeployed soon. Thanks for your patience and we will let you know as soon as it's available again.

**Comment by darylrobbins** [comment]
Working great now. Thanks!

**Comment by manishas** [comment]
Thanks for confirming. Let us know if we can help with anything else.
