### ISSUE TITLE
Deployment key rejected by Heroku

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#1049]
I downloaded the deployment key from my Shippable dashboard to add to Heroku through the toolbelt.  The result was the key was rejected because it was not deemed strong enough:

```bash
heroku keys:add shippable.pub
Uploading SSH public key shippable.pub... failed
 !    Contents Your public key has been rejected because it was generated by a weak random number generator.
 !    See http://www.ubuntu.com/usn/usn-612-2 for more information.
```

That Ubuntu page references a vulnerability from 2008.

**Comment by manishas** [comment]
we'll look into this and get back to you. thanks for reporting it!

**Comment by manishas** [comment]
@jeffkole did you look at our blog post about deploying to heroku - http://blog.shippable.com/using-the-heroku-toolbelt-in-your-shippable-minions

**Comment by jeffkole** [comment]
I followed those instructions, and using the toolkit with a newly generated key works just fine.  Thank you for your help.

I would suggest removing the "deployment key" that is on the dashboard if it is not meant to be used for this purpose.  The description ("You can use the following key to enable continuous deployment to any provider that supports git-based deployments") implies that I should be able to use that key to do git pushes to Heroku.
