### ISSUE TITLE
put build badges at the top

### ISSUE THREAD

**Issue by tristanwietsma** [Shippable/support#1051]
You've got this awkward infinite scroll on the repo page. I was trying to get a build badge (located at the bottom) and kept scrolling to the bottom, only to get hammered by the build history. It was almost funny.

Result: I gave up.

You should consider moving the build badge to the top of the page, above the infinite scroll.

**Comment by manishas** [comment]
@tristanwietsma can you be more specific? We do have the badge at the top - 
![screen shot 2015-02-11 at 2 58 22 pm](https://cloud.githubusercontent.com/assets/2983749/6158373/7ebdb1ee-b1fe-11e4-97d2-444844c0c0be.png)

Are you looking at it on a different form factor or with the window being narrow?

**Comment by tristanwietsma** [comment]
ah, so the issue i had was when viewing the page at less than full width that badge panel shows up below the build history. so problem solved by going full width.

i'm not a ux expert, so i'll defer.

**Comment by manishas** [comment]
We have a responsive UI so it changes according to window width/device. Thanks for reporting this and we'll re-evaluate this if more people have a problem finding the badge.
