### ISSUE TITLE
Email notification not sent

### ISSUE THREAD

**Issue by mhaligowski** [Shippable/support#1055]
https://app.shippable.com/builds/54dc3a741182c511006449c4

Part of shippable.yml file:

    notifications:
      email:
        - mhaligowski+shippable.success@memoryalbums.co

Build is successful, I don't receive any email.

**Comment by manishas** [comment]
@mhaligowski Did you specify the following in your yml - 
 on_success: always
 on_failure: always

Please check out http://docs.shippable.com/en/latest/config.html#email-notification

**Comment by manishas** [comment]
shippable.yml should be file:

    notifications:
      email:
        - mhaligowski+shippable.success@memoryalbums.co
      on_success: always
      on_failure: always

Let me know if that works.

**Comment by mhaligowski** [comment]
> You can also specify when you want to get notified using change|always|never. Change means you want to be notified only when the build status changes on the given branch. Always and never mean you want to be notified always or never respectively.

From: http://docs.shippable.com/en/latest/config.html#email-notification

I thought that was the default settings, will check that in a moment.

**Comment by manishas** [comment]
we definitely need better documentation here :(

I will update it in a bit but let me know if the yml works for you.

**Comment by manishas** [comment]
updated docs and closing issue. please re-open if it doesn't work for you. thanks!
