### ISSUE TITLE
Email notifications for specific Branches

### ISSUE THREAD

**Issue by willscott** [Shippable/support#1056]
Per http://docs.shippable.com/en/latest/config.html#notifications notifications can be configured for failure and success changes.

It would be great to have emails sent for changes only to the `master` branch, since the team may want to know about failures there, but not about the status of in-progress pull requests.

**Comment by manishas** [comment]
@willscott The shippable.yml file is per branch so you can configure it differently for each branch.

**Comment by Sahloul** [comment]
@manishas What if I want to build for ALL branches and receive a notification (email, slack, ..etc) on specific branches?
