### ISSUE TITLE
Slow bundle install but then cache: true causes error

### ISSUE THREAD

**Issue by braindeaf** [Shippable/support#1057]
Hi there,

We're running into problems with our build in that our bundle install for our Rails project comes in at 6 minutes, obviously we'd like to try and speed this up. However, when we set the cache: true option in our shippable.yml we get the following error. Can you assist at all?

500 Server Error: Internal Server Error ("Cannot start container d077adc66416b7d3ef75bf5a8420142fa0894683b49e107612f7d8e3a7e5ee3a: finalize namespace setup user get supplementary groups Unable to find user shippable"): Traceback (most recent call last): File "/home/shippable/dpd/step_listener.py", line 98, in handle_message_callback self.execute_step(build_plan, current_step, False) File "/home/shippable/dpd/step_listener.py", line 164, in execute_step raise e APIError: 500 Server Error: Internal Server Error ("Cannot start container d077adc66416b7d3ef75bf5a8420142fa0894683b49e107612f7d8e3a7e5ee3a: finalize namespace setup user get supplementary groups Unable to find user shippable")

Here's the copy of our shippable.yml

language: ruby
rvm:
  - 2.1.2
cache: true
env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage CODECLIMATE_REPO_TOKEN=codeclimatetoken

services:
  - mysql
  - redis

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libtag1-dev ffmpeg libavcodec-extra-53 lame libmp3lame0 sox libsox-fmt-mp3 libsox-fmt-all jpegoptim

install:
  - bundle install --gemfile="Gemfile"

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - cp config/database.yml.shippable config/database.yml
  - rake db:create --trace
  - rake db:schema:load --trace
  - rake db:migrate
  - rake db:seed --trace

script:
  - rspec --tag ~acceptance --tag ~skip -f RspecJunitFormatter -o shippable/testresults/results.xml spec/suite.rb

notifications:
  email:
    recipients:
      - ouremailaddress@ourdomain.com
    on_success: change
    on_failure: always

**Comment by pledgemusic** [comment]
Hi Manisha,

We're aching to switch over to a paid account, but builds are still much slower than our existing CI: (about 36mins vs 18mins) so can't make the switch yet:

Fixing the caching above (8mins on 'install' step) is part of that, but it also looks like the tests run slower in general. Could you confirm whether the CPU allocation is larger on paid accounts?

Zach

**Comment by pledgemusic** [comment]
Caching issue seems to have resolved itself.

**Comment by manishas** [comment]
@braindeaf do you still run into this error? We deployed several fixes over the last couple of weeks and you shouldn't see this any more.

**Comment by manishas** [comment]
Closing.
