### ISSUE TITLE
Got charged twice

### ISSUE THREAD

**Issue by thesynapses** [Shippable/support#1058]
Hi Support,
I opened shippable.com in Chrome and went to account and changed it to a paid plan and it charged me $12. After few minutes I checked again and the account was still set at free. I selected paid plan again and got charged $12 again. 

Please check for email sureel@thesynapses.com and refund the extra charge.

regards,
Sureel
(312)380-1857

**Comment by manishas** [comment]
@thesynapses sorry about this! We will add a warning dialog if anyone tries to delete credit card info.

Which org was this upgrade for? I will enter a request for a refund and will let you know as soon as it's processed.

**Comment by thesynapses** [comment]
Synapse LLC.


Regards,
Sureel

On Feb 13, 2015, at 7:29 PM, Manisha <notifications@github.com<mailto:notifications@github.com>> wrote:


@thesynapses<https://github.com/thesynapses> sorry about this! We will add a warning dialog if anyone tries to delete credit card info.

Which org was this upgrade for? I will enter a request for a refund and will let you know as soon as it's processed.

**Comment by manishas** [comment]
@thesynapses this charge has been refunded. please re-open this issue if you don't see it within the next 3-4 days. Thanks!
