### ISSUE TITLE
Customized docker image on EC2 box runs out of space

### ISSUE THREAD

**Issue by adamwgoldberg** [Shippable/support#1059]
It looks like Shippable is keeping failed builds on the system because I've filled up my 100GB of quota. Is there a way to delete the directories /home/shippable/{dpd,_sh_swap} automatically from the GUI rather than sshing to the machine and removing them? Thanks.

**Comment by manishas** [comment]
@adamwgoldberg we're looking into this.

I'll check if resetting the host will delete the directories, but this is not an ideal solution obviously.

**Comment by adamwgoldberg** [comment]
Even when I use a non-custom image my builds still randomly freeze up until I manually remove everything, stop and reset the dedicated host and restart the build. Any update on your end? It's making my builds randomly hang. 

e.g.: https://app.shippable.com/builds/54e53f85b0802f100019ca1d

**Comment by crania** [comment]
Having the same issue.

**Comment by manishas** [comment]
@adamwgoldberg are you still running into this issue? Sorry for the long delay on this.

**Comment by manishas** [comment]
Closing. Please re-open if you still run into this.
