### ISSUE TITLE
include & exclude branches documentation is unclear

### ISSUE THREAD

**Issue by ffagerho** [Shippable/support#1060]
The documentation in chapter "A bit deeper", section include & exclude branches is a bit unclear. Maybe it could be written more clearly? Thanks! :-)

**Comment by manishas** [comment]
@ffagerho I have changed the documentation to be clearer :)

I'm closing the issue but let me know if you think it's still unclear. Also, our docs are open source so a contribution is super welcome as well :)

**Comment by manishas** [comment]
http://docs.shippable.com/en/latest/config.html#include-exclude-branches
