### ISSUE TITLE
Can not add payment method

### ISSUE THREAD

**Issue by andruby** [Shippable/support#1063]
I filled in my credit card details on the "Add payment method" form. I have a valid Visa card, yet the system shows a Error: "Internal Server Error" when I click on submit. I have a screenshot, but I'm uncomfortable adding it here even with blurred out CC details.

**Comment by rageshkrishna** [comment]
@andruby Can you please get in touch with me at ragesh@shippable.com? Thanks!

**Comment by gayanhewa** [comment]
The payment option is not available anywhere in my dashboard.

**Comment by rageshkrishna** [comment]
@gayanhewa Can you please tell me if you are an owner on the github/bitbucket organization that you are trying to upgrade? At the moment we only allow owners to change billing information on a subscription.

**Comment by gayanhewa** [comment]
I am not the one who is trying to upgrade. I am only an Admin for the repo.  But the owner tried to upgrade.

**Comment by fabiocarneiro** [comment]
I had a similar problem some days ago, and i resolved it using a different card. Although my previous card was perfectly valid and had limit, it wont let me add it, neither upgrade the plan. I talked to @manishas and shippable support were not able to discover why that was happening.

**Comment by manishas** [comment]
@andruby I see your org is upgraded now. Do you need any additional help with this?

We use a third party payment processing provider and the declines are coming from them. We'll follow up with them for more clarity. Thanks!

**Comment by andruby** [comment]
Hi @manishas. I borrowed a friends credit card to upgrade our account. Could the fact that my credit card is due to expire in two months have been an issue for your third party provider?

My problem was solved so I'm ok if you close this issue

**Comment by manishas** [comment]
Thanks! Closing.
