### ISSUE TITLE
Build hangs on npm install

### ISSUE THREAD

**Issue by andruby** [Shippable/support#1064]
Is there a maximum build size? Or maximum number of files?

Our application consists of a rails application and two embedded 2 ember-cli apps. The build just hangs when running npm install for the 2nd ember app. There is no output what-so-ever, it just hangs..

Build url: https://app.shippable.com/builds/54e1becfc44f060e0073aa1b

On a local build the npm and bower dependencies are 460MB large (not counting the rails gems) and contain 68700 files.

Cheers,
Andrew

**Comment by rageshkrishna** [comment]
I've never played around with ember much, but a quick search turned up [this twitter conversation](https://twitter.com/noelrap/status/506821510791573504) which seems to suggest that bower is running in interactive mode by default and it prompts you to share usage statistics or something like that, which led me to the [actual github issue on bower](https://github.com/bower/bower/issues/1162) that documents this.

Here are a couple of things you could try:

1. `yes "Y" | ember install` so it enters "Y" for any question that ember or bower asks, or
1. Update .bowerrc with this flag:
````
{
  "interactive": false
}
````

Please give this a shot and let me know if it works.

**Comment by rageshkrishna** [comment]
https://github.com/bower/bower/pull/1163 seems to suggest that bower will default to non-interactive mode if it finds the environment variable `CI=true`. What's strange is that we do set that in the builds, so it _should_ work. Can you try running ember in verbose mode to see if we can get more information?

**Comment by andruby** [comment]
It's actually this call that hangs: `cd web/venture/ && npm install && cd -` not ember or bower.
When running it locally it does not ask for anything.

I've run the build (https://app.shippable.com/builds/54e1d33dc44f060e0073ac3f) with npm install --verbose which shows more info. The last console line is `npm verb lock ember-export-application-global@1.0.2 /home/shippable/.npm/abe13c66--export-application-global-1-0-2.lock`.

I'll try to run the shippable docker container locally and see if I can run the npm install there.

**Comment by rageshkrishna** [comment]
Oh, sorry about that. I think I got confused between the build script and the actual output.

We don't enforce any limits on number of files or disk space so this is indeed quite odd. Can you please share the package.json files from both projects? I'd like to try and repro this so I can debug it further. You can mail them to ragesh@shippable.com.

**Comment by rageshkrishna** [comment]
We've seen issues with npm locking up before, but it usually throws an error message instead of just freezing. Can you try a build that upgrades npm with `npm install -g npm` as the first step in `before_install`?

**Comment by andruby** [comment]
The issue was related to a dependency in our package.json to a private repository. We solved it by using a Github oauth token in the url.
`git+https://<github_token>:x-oauth-basic@github.com/<user>/<repo>.git` ( [more info here](http://rzrsharp.net/2013/07/02/private-github-repos-with-npm-and-heroku.html) )

It's a pity that we didn't see any useful output from npm pointing us in the right direction.
