### ISSUE TITLE
Limit builds when using dedicated hosts

### ISSUE THREAD

**Issue by velo** [Shippable/support#1065]
My build is really greedy.  And I wanna limit how many builds I run per machine.

If I don't linux will start killing processes.

How can I do so?

**Comment by rogierslag** [comment]
duplicate of https://github.com/Shippable/support/issues/1200

**Comment by manishas** [comment]
this is now available. Dedicated hosts are available as part of your subscription and are priced according to number of parallel builds. More at http://docs.shippable.com/ci_byoh/
