### ISSUE TITLE
Minify & Combine JS on shippable app

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1066]
Hi, 

I am using shippable in India for last 2-3 weeks. I find shippable app to load really slow (15+ secs) on my 16Mbps connection. I guess thats because shippable prod app is not combining js/css, 

- total of 115 unminified scripts, amount to 2.2 MB which can reduce by 75% and we could definitely use CDN for angular, socket and other third party libs
- total of 12 css which could be combine
- We could definitely use CDN to host js/css/images

I am sure shippable team would be knowing about these issues but if they could prioritise in their grand scheme of things (no pun intended, u guys are doing awesome stuff!) it would make my life easier

I am more than willing to help if required, 

Thanks,

**Comment by velo** [comment]
it would help me as well

**Comment by avinci** [comment]
this has been minified at this point. Let me know if you still see issues.
