### ISSUE TITLE
Unable to see bitbucket private repositories

### ISSUE THREAD

**Issue by jagmal** [Shippable/support#1067]
I have linked my github account to shippable but am not able to see the repositories in the list of repositories on the right side. I only see two organizations there.

Can you help?

**Comment by rageshkrishna** [comment]
On the dashboard you'll see a few icons on the right side of the screen. If it says Private Repos Off, please click on the icon so we can get the necessary Github permissions to work with your private projects:

![repos](https://cloud.githubusercontent.com/assets/1134972/6267475/6bace382-b86a-11e4-8da2-bac859017aa7.png)

**Comment by jagmal** [comment]
Sorry, my bad. I am using bitbucket account for this purpose.

**Comment by rageshkrishna** [comment]
OK, the "All Repos Off" button you see there is for bitbucket repos. Clicking on that will let you link your bitbucket identity to the same Shippable account.

**Comment by jagmal** [comment]
I have already linked the bitbucket identity (in fact I used the same to login).  Please see attached. And I can see two organizations on the left side but not the repositories that I own.

![screenshot from 2015-02-19 19 13 23](https://cloud.githubusercontent.com/assets/6551179/6267602/6a882d08-b86b-11e4-916d-0f3c45b128a9.png)

**Comment by jagmal** [comment]
In case you need it, my email id is jagmal [at] gmail [.] com

**Comment by rageshkrishna** [comment]
Can you try the "Sync Account" button? It should refresh all your account permissions.

**Comment by jagmal** [comment]
Yes, I did.

Is it so that you don't support mercurial repositories? Because I can see a few git repositories I have access to (via others) but not my mercurial repositories.

**Comment by rageshkrishna** [comment]
Ahh yes, that would be it. We don't support mercurial yet. You can only use git repositories.

**Comment by jagmal** [comment]
Thanks for the support, Ragesh.

Will surely use shippable for git repository in future.

**Comment by manishas** [comment]
Closing this issue.
