### ISSUE TITLE
Illegal tag name (30 character limit?)

### ISSUE THREAD

**Issue by ahmadia** [Shippable/support#1069]
This is related to https://github.com/docker/docker/issues/8445

I think restricting my Git branch names to less than 30 characters is silly.  I'm not sure what a good workaround would be, aside from resorting to just cropping the branch name when shipping to Docker.

```
500 Server Error: Internal Server Error ("Illegal tag name (ahmadia/adjustable_gauge_duplication_tolerance.181.1): only [A-Za-z0-9_.-] are allowed, minimum 2, maximum 30 in length"): Traceback (most recent call last):
```

**Comment by manishas** [comment]
@ahmadia are your builds failing? If yes, can you point me to a failed build?

**Comment by ahmadia** [comment]
Hi @manishas - here is an example: https://app.shippable.com/builds/54e8b30af084cf0e00e5faba

**Comment by ahmadia** [comment]
(I know the build is failing for another reason, don't worry about that, the Docker push step is also failing).

**Comment by manishas** [comment]
@ahmadia sorry for the delay on this. I don't think there is much we can do (except for cropping branch name) and that isn't an elegant fix. I am closing this issue, but please let me know if you need assistance again.
