### ISSUE TITLE
Question: How to install ruby_worker_ng gem on default minion image

### ISSUE THREAD

**Issue by pcullin-ratio** [Shippable/support#1070]
I'm trying to install Iron.io's iron_worker_ng Ruby gem in order to automate deployment of IronWorker packages from Shippable. This depends on Ruby version 1.9.2 or above, but it appears the default Ruby version on the minion is 1.8.1 and I have not been able to successfully update it and set the default version to use anything above 1.8.1.

**Comment by rageshkrishna** [comment]
@pcullin-ratio Your YML specifies `node_js` as the language. We don't initialize `rvm` automatically in this case. You should be able to get it to work by sourcing rvm before using it like so:
````
before_install:
 - source ~/.rvm/scripts/rvm
 - rvm use 1.9.2 || rvm install 1.9.2
````
I hope this helps!

**Comment by pcullin-ratio** [comment]
That does help, thanks! I was using sudo in my gem install command, so once I added these before_install commands and removed sudo it worked.
