### ISSUE TITLE
Pull always fails

### ISSUE THREAD

**Issue by Delors** [Shippable/support#1072]
When I create a new project everything works fine. However, as soon as I update the repository and shippable tries to rebuild the project it fails:

The message ist always similar:
 git reset --hard 663ee6d3691c3afb79e44a5569b1d9218feca645
 fatal: Could not parse object '663ee6d3691c3afb79e44a5569b1d9218feca645'.
 
(As said: after deleting the project and reactivating the project (bitbucket/delors/opal) it works fine until I update the project again.) Nobody else in the project team has any git issues.

**Comment by manishas** [comment]
Closing this issue. We believe this is a bitbucket issue.
