### ISSUE TITLE
Build hanging at various random steps

### ISSUE THREAD

**Issue by pastawoua** [Shippable/support#1074]
For the last 6 hours, all our builds have been hanging at various random steps in the build process. They usually take 2/5 minutes.

**Comment by manishas** [comment]
@pastawoua Can you paste a link to a hanging build? Thanks!

**Comment by pastawoua** [comment]
@manishas https://app.shippable.com/builds/54ebcfe59b80f20d00c394d4

**Comment by pastawoua** [comment]
@manishas any update please?

**Comment by lekhab** [comment]
![screen shot 2015-03-12 at 12 07 32 pm](https://cloud.githubusercontent.com/assets/9526532/6625916/6ab7dbfc-c8b0-11e4-8f0e-15bbbdc5cc04.png)

**Comment by manishas** [comment]
@pastawoua can we do a hangout? We cannot reproduce this at our end.

**Comment by manishas** [comment]
Closing due to lack of response. 

@pastawoua Please let me know if we can set up a hangout and debug real time. Thanks!
