### ISSUE TITLE
Build with custom image just hangs...

### ISSUE THREAD

**Issue by velo** [Shippable/support#1077]
I made a pull request with 
````build_image: shippableimages/ubuntu1404_java````

But build just hangs:
https://app.shippable.com/builds/54eb309ff774120e0020eb1c

Any idea?

**Comment by rageshkrishna** [comment]
@velo Docker is experiencing an outage at the moment which might be causing the `docker pull` to hang: https://status.docker.com/

**Comment by velo** [comment]
I'm experiencing this for the past 4 days, since I open my pull request.

**Comment by rageshkrishna** [comment]
@velo Is this happening on the foundation project? You should be seeing messages about YML merge failures in the notifications tab for this project.

We now attempt to merge the YML file from the PR's head and base branches before attempting the build. In this case, the `patch` utility is unable to complete the merge. I can tell from the logs on our server that it's reporting 2 failed hunks. This can happen if the YML file has changed in both the head and base branches of the PR. Rebasing your PR on the base branch should help.

We could tell `patch` to ignore contexts in the diff but that increases the possibility of a bad merge so we decided to play it safe.

**Comment by velo** [comment]
Nice, that was it.  Would be nice a visual clue on what happened though.

Thank you Ragesh!

**Comment by manishas** [comment]
Closing.
