### ISSUE TITLE
Dedicated hosts server

### ISSUE THREAD

**Issue by velo** [Shippable/support#1078]
Would be nice to have a visual clue showing witch dedicated hosts is being used for a given build.

My build stuck for some reason and I had to connect to all servers and reboot to get things back to normal

**Comment by manishas** [comment]
thanks! we're improving the dedicated hosts feature and I'll put this as an enhancement.

**Comment by DavidGDragon** [comment]
Active nodes will now show a link to the run/job that is being processed on it.
![screenshot from 2016-03-08 13 48 50](https://cloud.githubusercontent.com/assets/6647936/13617640/9eb273d0-e534-11e5-9c59-98e709fbbc2e.png)
---

beta verified www 5436

**Comment by DavidGDragon** [comment]
@velo could please verify that this feature is working for you?

**Comment by manishas** [comment]
This is done, so closing the issue.
