### ISSUE TITLE
Failed build step time

### ISSUE THREAD

**Issue by velo** [Shippable/support#1079]
Would be nice to have the time the step took to fail.

![image](https://cloud.githubusercontent.com/assets/136590/6332369/974c42de-bb63-11e4-8c6e-ed398321bdb6.png)

**Comment by ankul-shippable** [comment]
We have added this feature. It will be available soon.

**Comment by ankul-shippable** [comment]
This is feature is live now. Feel free to reopen this if there is any problem around this. Closing this.
