### ISSUE TITLE
Builds are hanging indefinitely

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1082]
Docker appears to be up but kicking off a build manually from the shippable site never gets past the "Waiting for build information..." state.

**Comment by vincentpaca** [comment]
Experiencing the same thing. No issues on docker status pages aside from the post on the issues page readme here.

**Comment by abhi1010** [comment]
I am also having the same thing - My only project from bitbucket is not building anymore. I have tried deleting and adding the project on shippable - no joy.

**Comment by rageshkrishna** [comment]
We've had an issue with one of our message processors for the past hour. This has been corrected now and builds have started running. Please give it a few minutes. As the queue drains out you should see your builds starting to run.

**Comment by vincentpaca** [comment]
Yup. Just saw a few of my builds just now. Thanks @rageshkrishna

**Comment by abhi1010** [comment]
Nope, mine is still saying "Waiting for build information..."

**Comment by rageshkrishna** [comment]
@abhi1010 Can you give me your project id? Thanks.

**Comment by abhi1010** [comment]
It is working now, the page wasn't refreshing for some reason. When I went back and started from the home page of the project, it worked. Thanks

**Comment by chriskinsman** [comment]
Running here now...
