### ISSUE TITLE
Don't use a virtualenv for boot.sh on dedicated

### ISSUE THREAD

**Issue by pcsforeducation** [Shippable/support#1084]
My base container has all the requirements already installed, so tests take like 30 seconds when I also install the requirements.txt in /home/shippable/wrk/requirements.txt and throw a "deactivate" into boot.sh. Otherwise they take quite a bit longer, and I see little benefit over using Travis. It would be much simpler to ship the requirements preinstalled (there's only like 3 of them) in the directory you mount into the container. The dependencies are pinned anyway, so when you want to change them, you can reship them. 

Also, you seem to overwrite the files in /home/shippable/wrk occasionally, so I can't just edit the file and have my tests always work :)

**Comment by manishas** [comment]
This is an old issue and we've revamped our build system since. Closing.
