### ISSUE TITLE
Is there a way to deploy containers to Azure?

### ISSUE THREAD

**Issue by munjalpatel** [Shippable/support#1086]
Hello,

Is there a way to deploy containers to Azure CoreOS machine?

**Comment by manishas** [comment]
@munjalpatel we're working on enabling this as we speak. Give us a few days and I'll give you an update.

**Comment by sibex** [comment]
:+1: :smiley_cat: I'm looking forward to this upcoming feature.

**Comment by tmcgannon** [comment]
Is this feature available yet?

**Comment by westlakem** [comment]
It's been over a year since the initial request that you were "working" on it.  Any updates?

**Comment by abhijitkini** [comment]
@westlakem We're sorry that it has taken us so long. Since our newly released platform in March, we have been rapidly adding support from various providers. Azure/mesos support is coming up in the near future, so follow us on twitter ([@BeShippable](https://twitter.com/BeShippable)) or [subscribe to our blog updates](http://blog.shippable.com) so you don't miss the announcement.

Also, are you looking for support on Azure DC/OS or Docker Swarm?
If you are interested in previewing a demo of the support, send me an email (abhijit@shippable.com)

**Comment by westlakem** [comment]
How near future are we talking?  We're proofing solutions for our
enterprise applications in July, and it looks like you've got the closest
product to what we're looking at.

**Comment by abhijitkini** [comment]
@westlakem we can schedule a demo for you and talk about your requirements this Friday or next Tuesday PST. Send me an email with your available times and I'll set up the demo.

**Comment by westlakem** [comment]
I don't have the time for a live demo any time in the foreseeable future.
We are a java shop with many applications. For the evaluation, we have to
use azure. The goal is to run unit tests (junit and Jasmine) and if those
pass, deploy to a test server where we can run selenium tests against the
site. When those pass, we want to be able to have a manual verification
step.  Finally,  when the approver signs off on the code, build a docker
container, spin up and deploy it to Azure servers. After the servers are
fully running, swap them with the live production servers behind the load
balancers.

Let me know if you think that's something you can do

**Comment by manishas** [comment]
@westlakem We launched our new Pipelines last week that support your scenario. Documentation is at:

Overview: http://docs.shippable.com/pipelines/overview/
Getting started: http://docs.shippable.com/pipelines/gettingStarted/
Sample pipeline: http://docs.shippable.com/tutorials/pipelines/samplePipeline/

**Comment by manishas** [comment]
I would love to show you a demo if you have some time in the next few days. Let me know.

**Comment by Kirtap** [comment]
Hi, I see that this was closed a while ago but i do not see any Azure deployment support in the documentation. Am I missing something here?
