### ISSUE TITLE
mounting volumes on dedicated host

### ISSUE THREAD

**Issue by bassamtabbara** [Shippable/support#1087]
I see that I can set --privileged and --net on the docker instance running on a dedicated host through the shippable.yml file. What about other docker options like mounting volumes with -v and setting more LXC privileges through cap-add and cap-drop? 

One idea would be to support DOCKER_OPTS environment variable that you pass directly to docker run.

**Comment by rageshkrishna** [comment]
@bassamtabbara We have some updates coming up that will allow you to configure more Docker options for the build. I can confirm that mount points will be configurable once this update is released. We'll announce these new features very soon, so please stay tuned!

**Comment by bassamtabbara** [comment]
@rageshkrishna thanks. is there a workaround I can use now? I'm unable to build one of our libraries without volume support.

**Comment by bassamtabbara** [comment]
hi was volume support added in the release you just shipped? If not when do you anticipate this support being added?

**Comment by bassamtabbara** [comment]
Hi, any update on this?

**Comment by bassamtabbara** [comment]
shippable team, would love an update on this. Its hard to plan on whether we should rely on this support or not in our roadmap.

**Comment by Finomnis** [comment]
Same here.

**Comment by manishas** [comment]
We do not support privileged mode on dedicated hosts, so docker in docker scenarios are unsupported.

If you want to run multi container environments, you should take a look at Formations https://app.shippable.com/mktg/#formations

Let me know if you have any questions. Thanks!
