### ISSUE TITLE
Parallel tests have little effect on build time

### ISSUE THREAD

**Issue by vincentpaca** [Shippable/support#1088]
Running multiple minions to run parallel tests are really really slow for me and we're only running our rspec tests.

We have around 1000 spec files, around 7000 tests in total, divided over 50 minions. A build takes around 20 minutes to complete. My benchmark for this is our current CI with a concurrency of 24 instances.

Would the slowness be solved by having our own dedicated hosts? If it would, is there a benchmark I can follow to choose the right size of dedicated hosts?

**Comment by manishas** [comment]
@vincentpaca let's discuss this over email. I believe you've reached out to @CADBOT and we'll get back to you shortly.
