### ISSUE TITLE
When clicking build get "Waiting for build information..." never completes

### ISSUE THREAD

**Issue by jasonriddell** [Shippable/support#1089]
When clicking build of a repository the build gets stuck on "Waiting for build information...", this was working last night and we haven't commited any changes to bitbucket (and bitbucket appears to be operating correctly/fully functional). Also when trying to cancel the build that is stuck in "Waiting for build information..." I get an error in the bottom right hand corner saying "The requested resource was not found" (screenshot attached).

Build is https://app.shippable.com/builds/54eda56832f6c81400a5a53b

Thanks,
Jason.

![screenshot from 2015-02-25 10 37 36](https://cloud.githubusercontent.com/assets/2424202/6369086/de4171e6-bcda-11e4-9b51-b40d4b6c0a01.png)

**Comment by jasonriddell** [comment]
This appears to have been addressed, looks like a service outage.

**Comment by pniederw** [comment]
Still having the same problem (since yesterday).

**Comment by pniederw** [comment]
Still not working.

**Comment by pniederw** [comment]
Found the cause for my problems (see #1110).
