### ISSUE TITLE
<Urgent> Project is not responding to any request

### ISSUE THREAD

**Issue by bldoron** [Shippable/support#1090]
Our project:  "startappdev / portal" is not responding.
Trying to stop the current stuck build or to restart or to delete it, does nothing.

Trying to push a new build also doesn't trigger any webhook.

Please advise quickly.

**Comment by rageshkrishna** [comment]
@bldoron Builds should be running normally now. Can you please check and confirm? One of our message processors has been having issues over the past few days. This is causing build processing to be delayed for a while, but you should see all the queued builds running to completion now.

**Comment by bldoron** [comment]
This is indeed what happened.
The problem was that during that time, we got no response from the servers.
The buttons didn't respond, and pushing new content created no visible builds waiting to be executed.

We felt like there was nothing we could have done.
I hope this doesn't happen again.
