### ISSUE TITLE
Debian minion image

### ISSUE THREAD

**Issue by DanLipsitt** [Shippable/support#1091]
Issue #72 requested Debian 7 (wheezy) minions, as well as Ubuntu. The issue was closed when the Ubuntu image was completed, but there is still no Wheezy image.

**Comment by manishas** [comment]
+ @fommil requested Debian Jessie.

**Comment by fommil** [comment]
I was running Shippable fine on Debian Wheezy. There were a few tickets I raised around this, so check my history if you're interested.

The problem is Debian Jessie, which doesn't work. I needed it for kernel support that wasn't available in Wheezy.

**Comment by manishas** [comment]
This is an old issue, not sure if still relevant. We have launched a bunch of new images and platforms since then, such as CentOS, RHEL7, Windows, MacOS, and also Arm machines.

Closing as deferred.
