### ISSUE TITLE
postgres 9.4

### ISSUE THREAD

**Issue by thecaddy** [Shippable/support#1092]
Would appreciate if you'd add an the updated postgres.

**Comment by pmarti** [comment]
:+1: 9.4 is 4 months old, please add it

**Comment by grue** [comment]
+1

**Comment by bilalaslam** [comment]
:+1: please add this.

**Comment by bulv1ne** [comment]
+1

**Comment by smvv** [comment]
+1

**Comment by HenrikOssipoff** [comment]
+1

**Comment by pmarti** [comment]
@manishas any eta on when will this land? Thanks

**Comment by ALenfant** [comment]
I use Postgres 9.4-exclusive features and this is preventing me from relying on Shippable to do my CI. Your silence on this issue is concerning since this version was released last December and is starting to be widely used.
Is it possible to know when this will be available? Thanks, I can't wait to use it!

**Comment by pschrammel** [comment]
same here. need 9.4 for testing (+1)

**Comment by adnan-panalytics** [comment]
+1

**Comment by ryanbaldwin** [comment]
Amazing. This issue is nearly 7 months old and no response? Brutal. 9.4 has been out for a while, kinda silly it's still not supported. 

+1 for 9.4

**Comment by thecaddy** [comment]
Ya, our entire stack was on shippable for a while but this forced us to look for another vendor.  We ended up switching to CircleCI.  Additionally they allow testing of docker containers and connecting to external db's from inside the container.

**Comment by manishas** [comment]
We're in the process of revamping all our images and adding new versions of languages and tools. I will have an update on this in the next couple of days. 

In addition our free plans let customers use their custom docker containers for builds.

**Comment by manishas** [comment]
@thecaddy we allow testing of docker containers as well. In fact you can bring up your entire multi-container application and automate functional testing against the live application. You can set it up to autoupdate with each push so you're not just automating unit testing but actual functional testing for each push. 

Thanks.

**Comment by HenrikOssipoff** [comment]
@manishas within the next few days you say?

**Comment by bigardone** [comment]
+1

**Comment by javiercr** [comment]
+1

**Comment by bbay** [comment]
+1

**Comment by achru** [comment]
:+1:

**Comment by jamescgibson** [comment]
:+1:

**Comment by robertcsakany** [comment]
+1

**Comment by flemse** [comment]
any status on this?

**Comment by pschrammel** [comment]
After more than two months of waiting I'll start to switch to one of your competitors. We're using AWS and work with Postgresql 9.4 on RDS. 9.4 has cool features (jsonb) I need and I base my work on. I think I was patient long enough. Bye and thanks for the fish.

**Comment by jamescgibson** [comment]
@flemse @pschrammel FWIW (not associated with Shippable), this has worked for us in our .shippable.yml:

```
 - sudo service postgresql stop
 - sudo apt-get remove --purge postgresql-9.1 postgresql-9.2 postgresql-9.3
 - shippable_retry sudo apt-get update -y -q
 - shippable_retry sudo apt-get install -y -q postgresql-9.4-postgis-2.1 postgresql-client-9.4 postgresql-contrib-9.4 postgresql-plperl-9.4 --fix-missing
 - echo 'host all all localhost trust' | sudo tee /etc/postgresql/9.4/main/pg_hba.conf > /dev/null
 - echo 'local all all trust' | sudo tee --append /etc/postgresql/9.4/main/pg_hba.conf > /dev/null
 - sudo service postgresql start
```

**Comment by davidthewatson** [comment]
@jamescgibson Thanks for your solution. I copied it verbatim into my shippable.yml but when this line runs:

    - psql -c 'create database blah;' -U postgres

I get:

    Specified cluster does not exist locally and does not specify a remote cluster

I'm not sure why this is happening on my container and not yours. 

It makes me sad that shippable doesn't support a modern postgresql since my app depends on JSONB support.

**Comment by jamescgibson** [comment]
@davidthewatson Can you share where that line is in your .shippable.yml? We actually create the database in `before_script`, not in `before_install`, and use rake (rails), so I'm not sure how much help I can be. Try moving `- psql -c 'create...` to `before_script`?

**Comment by davidthewatson** [comment]
@jamescgibson Yep, mine's in before_script too. Thanks for the tip. I've been running on shippable for a couple years now so pretty familiar. Only other diff I can think of would be python 3.5, but I can't imagine why that would be a factor here, though I have seen shippable.yml's execution revert to python 2.7 for no apparent reason while the script was executing (from the stacktraces).

**Comment by jamescgibson** [comment]
@davidthewatson Any odd log input from the `before_install` we've been using? `Specified cluster does not exist` sounds to me like the installation failed.

We're caching our containers, so I'd bet my left shoe we're going to run into this issue as soon as our cache expires, haha.

**Comment by davidthewatson** [comment]
@jamescgibson Oh man, that's scary.

I looked and all the postgresql 9.4 install stuff in before_install completes successfully with a green arrow and no errors. That's why I'm baffled.

**Comment by davidthewatson** [comment]
It's dying here:

https://github.com/jbq/postgresql-common/blob/master/pg_wrapper#L65

**Comment by avinci** [comment]
@davidthewatson we have completely revamped our images from ground up. This is going to launch on Feb 29. We have revamped our build system too and hence testing it end to end. Hope that helps. 

Reason for our not updating is we thought folks will use their own images using Docker and we realized late November that it was not the case. We decided to revisit our decision and update all the versions and also create a system for updating images on a monthly basis. 

Hope this helps and thanks for your patience.

**Comment by davidthewatson** [comment]
@avinci Thanks for your response. This is very frustrating given that the other vendors in my toolchain all support postgresql 9.5. Unfortunately, I can't wait that long. 

Can I just use:

https://github.com/docker-library/postgres/blob/916a840510b481e7d3f0f74fa04fde3edfdfbd04/9.5/Dockerfile

If so, can you point me to a piece of documentation showing how to include this?

**Comment by davidthewatson** [comment]
@avinci Alternatively, could I use heroku postgres and just point a secure environment variable to the DB URL there?

**Comment by avinci** [comment]
Sorry, In a different timezone. Yes, that should technically work. Let me play with this and get back to you .

**Comment by manishas** [comment]
This is available now. The `pls` and `all` versions of our standard images in the [drydock repo](https://hub.docker.com/u/drydock/) have Postgres 9.4 installed.

please note that we have a new yml format, so now would be a good time to convert to new yml as well :)

let us know if you need help with this.

**Comment by manishas** [comment]
closing since postgres 9.4 is now available.

**Comment by catskul** [comment]
@manishas can you link to the yml conversion doc? I tried a few obvious links and didn't find any clear indication of what changed and how old yml should be adjusted.

**Comment by manishas** [comment]
@catskul here are a few links that will help:

New yml config: http://docs.shippable.com/ci_configure/
Migration guide: http://blog.shippable.com/migrating-to-the-new-build-platform
5 migration tips: http://blog.shippable.com/5-tips-for-a-successful-migration

Also, our new official images are in the [drydock repo on Docker Hub](https://hub.docker.com/u/drydock/) and naming convention for images is [in our docs](http://docs.shippable.com/ci_configure/#setting-your-build-image). A list of supported languages and services is here - http://docs.shippable.com/gs_supported/

Let me know if you need help with the config.

**Comment by diwu1989** [comment]
@manishas the documentation for postgres doesn't work
![image](https://cloud.githubusercontent.com/assets/380950/14076911/eafcf556-f49a-11e5-84d3-21db3c1cf5e8.png)

```
# Postgres binds to 127.0.0.1 by default. 
# Create a user and DB as part of the ci section before using it

services:
    - postgres

build:
  ci:
    - psql -c 'createuser -s --username=postgres shippable'
    - psql -c 'create database myapp_test;' -U postgres
```
please fix the documentation
