### ISSUE TITLE
Clearer "Success" iconography

### ISSUE THREAD

**Issue by phptek** [Shippable/support#1094]
On the https://app.shippable.com/ domain - I have a hard time seeing at-a-glance if my build passed or not. The reason: I'm colourblind - so reds, browns and greens don't have as much contrast for me ans they do for those who aren't colourblind.

My suggestion: Use the standard "isshippable", "notshippable" icon instead of the Green / Red build number to the left of each build.

Other than that, awesome, easy-to-use and configurable service - THANKS!

**Comment by manishas** [comment]
@phptek did you take a look at our new UI? Do you still have the same problem with it?

Feedback greatly appreciated!

**Comment by phptek** [comment]
A quick look on my iPhone appears to yield a mobile friendly view, good work! I'll need to bust out my lappy to see it in all it's glory :-)

**Comment by manishas** [comment]
Closing. @phptek please let us know any feedback and we'll follow up :)
