### ISSUE TITLE
Timeout when trying to push/deploy to CloudControl using cloudcontrol tools

### ISSUE THREAD

**Issue by resurge** [Shippable/support#1095]
Related build: https://app.shippable.com/builds/54ea59f7f774120e0020dc48

When trying to push or deploy to CloudControl I get a timeout.
(`cctrlapp <appname>/<branchname> push` & `cctrlapp <appname>/<branchname> deploy`)
More info about the tools can be found here: https://www.cloudcontrol.com/dev-center/Platform%20Documentation

(I could circumvent the push command by using git straightaway to push but the deplot command I can't find an easy alternative to)
In my case, when trying to execute `cctrlapp shippablecloudcontrolexample/default deploy` I get a timeout.
I think it's weird that it completely freezes.
Is it possible that the cctrlapp command is prompting for input and that that line doesn't get logged in the shippable output?

**Comment by manishas** [comment]
@resurge this is certainly possible. We've run into this with other scenarios. We'll investigate on our end, but if there something you can do so your command doesn't prompt for user input?

**Comment by resurge** [comment]
If everything runs fine no prompt should be shown.
So the reason I would need to know what the prompt is showing is for debugging purposes.  

I suspect I'm being asked to enter my password, which shouldn't happen since authentication should work by using my shippable deploy key. (is this only sent when doing git push maybe?)

**Comment by manishas** [comment]
We have redone our console with a buffering logic of 10 lines or 30 seconds, whichever happens first. This should ensure that you see the prompt in the console .

closing.
