### ISSUE TITLE
aufs diff layers keep stacking up on dedicated hosts

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1096]
`/data/aufs/diff/` is getting filled rapidly.

```sh
root@shippable00:/data# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       32G   31G     0 100% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            996M   12K  996M   1% /dev
tmpfs           201M  344K  200M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none           1001M  1.3M  999M   1% /run/shm
none            100M     0  100M   0% /run/user
root@shippable00:/data# du -sh aufs/diff/
25G     aufs/diff/
root@shippable00:/data# ls -lah aufs/diff/ | wc -l
307
root@shippable00:/data# docker images -a | wc -l
295
root@shippable00:/data# docker ps -aq | wc -l
5
```

**Comment by vkuusk** [comment]
We have the same problem. is there a manual way to clean up this directory. 

Something like delete everything in /data directory and "reset" the dedicated host? 

We do not need to preserve any test results or anything like that. we just need to continue to run tests.

Thanks.

**Comment by pmoust** [comment]
using BTRFS mitigates the effect.

**Comment by vkuusk** [comment]
@manishas we ran out of disk space in /data again. 
ubuntu@ip-10-253-138-155:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       24G  8.7G   14G  39% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            3.7G   12K  3.7G   1% /dev
tmpfs           748M  520K  748M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            3.7G  2.4M  3.7G   1% /run/shm
none            100M     0  100M   0% /run/user
/dev/xvdb        30G   29G     0 100% /data

Is there somewhere step by step instruction on manual procedure to cleanup the disk space?

Is it possible to cleanup without switching to the BTRFS. (I'm not sure how to set it up on the dedicated host without breaking the shippable control)

I'm fine with running manual cleanup for now.

**Comment by pmoust** [comment]
Closing as dedicated nodes are deprecated.
