### ISSUE TITLE
unable to remove dedicated hosts

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1097]
Due to #1096 I decided it was quicker to bring up a new fleet of shippable dedicated hosts over rectifying the issue manually.

New hosts have been added in Shippable UI and are initializing, but I cannot remove the aforementioned dead Shippable hosts.

![screenshot 2015-02-27 11 07 04](https://cloud.githubusercontent.com/assets/2493339/6409796/b7f43d4c-be70-11e4-8740-5a9d1dd34e61.png)

**Comment by adamyao** [comment]
hey, I have exactly the same problem and plus extra. I have one dedicate node which has the red "failed" sign, but I can not reset it or delete it (but I find it is still working though). I can not add a second node either. My error message is: you do not have the access right to exercise the request.

**Comment by manishas** [comment]
We'll look at both these issues asap.

**Comment by manishas** [comment]
this will be fixed in a few hours... we're testing a fix internally. sorry for the disruption!

**Comment by manishas** [comment]
This is available in production. Let me know if you can delete hosts now

**Comment by adamyao** [comment]
I can not add new dedicate host, still get the error message: you don't have sufficient permissions to perform this operation

**Comment by adamyao** [comment]
I can not remove the old dedicate node either, same error message.

**Comment by pmoust** [comment]
@manishas thanks, this one is fixed.
