### ISSUE TITLE
Dedicated host running out of disk space

### ISSUE THREAD

**Issue by apeiniger** [Shippable/support#1099]
We have a problem with our dedicated host running out of disk space. I checked the folders and most of it is used by /data and /home/shippable. Do you know why this is happening and how this can be resolved? Thought about deleting something but wasn't sure if I would destroy the setup.

If you want to check, here is a build id that fails because of this: 54f0327e6e35fd0e00f1fd67

**Comment by adamyao** [comment]
I just have the same problem on my dedicate host: disk is full and build aborts. I checked diskspace 100% full out of 24G, but /home/shippable uses up only 4.8G.

**Comment by apeiniger** [comment]
Is there any news on this? We now have three days without testing, which is really bad.

**Comment by manishas** [comment]
@apeiniger sorry about this. some of the space issues are docker related, and we're finding ways to work around them. For example, see #1096 .

I'm documenting the reasons why this can happen and workarounds and we will have this soon.

**Comment by apeiniger** [comment]
Ok, thanks. For now we just deleted the old instance and created a new one, but of course thats a bad workaround. Are you also planning on supporting custom docker images without the dedicated hosts?

**Comment by lekhab** [comment]
closing this - since we now support custom docker images without dedicated hosts.
