### ISSUE TITLE
Can't reach most recent build from badge

### ISSUE THREAD

**Issue by issue-reporter** [Shippable/support#1100]
Markdown link for project looks like: 

```
[![Build Status](https://api.shippable.com/projects/2398523895project29352/badge?branchName=master)](https://app.shippable.com/projects/2398523895project29352/builds/latest)
```

When you click on the badge, it goes to the link `https://app.shippable.com/projects/2398523895project29352/builds/latest`,
which tells you that the "The build you're looking for wasn't found." even when correctly logged in.

**Comment by manishas** [comment]
@issue-reporter this should work now. can you please confirm?

**Comment by manishas** [comment]
@issue-reporter is this still happening?

**Comment by manishas** [comment]
Closing. Please re-open if this is still a problem.
