### ISSUE TITLE
Can't access after conversion to organization.

### ISSUE THREAD

**Issue by thedracle** [Shippable/support#1101]
I changed my github account serviewcare to an organization, and now I can't access it from the organizations panel via my personal account.

I also had my shippable account/payment set up on that account.

Any help would be greatly appreciated.

**Comment by manishas** [comment]
@thedracle can you click on the 'sync accounts' button on your dashboard and see if the org shows up? Thanks.

**Comment by thedracle** [comment]
I managed to solve this by going to Applications in my github account, and selecting to give permissions to my organization to Shippable, all works now.

Thanks :)
