### ISSUE TITLE
Angular.js errors in your Dashboard

### ISSUE THREAD

**Issue by rorito** [Shippable/support#1102]
The Dashboard seems to be broken for me, is anyone else seeing this?

![screenshot 2015-02-27 14 36 49](https://cloud.githubusercontent.com/assets/930780/6419780/33460094-be8e-11e4-956d-4e4d3cf69ac6.png)

**Comment by manishas** [comment]
we're on it...

**Comment by manishas** [comment]
is this a 100% reprofor you?

**Comment by rorito** [comment]
Do you mean reproducible?

I just tested on Chrome, Firefox Nightly and my iPhone (iOS 8) and I'm
getting the dashboard errors on all of them.

**Comment by manishas** [comment]
@rorito is this still happening for you?

**Comment by rorito** [comment]
Nope, looks good, thanks for the help.

**Comment by manishas** [comment]
Thanks! Closing this issue.
