### ISSUE TITLE
How to tell if the current branch is master?

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1103]
I know, we have the `$BRANCH` environment variable, but, when building a PR to, let's say, `master`, the variable shows `master`.

In my point of view, this is wrong. I am not building the master branch, but a bunch of changes that I want to apply to it.

Is there a way to get the actual current branch being built?

**Comment by velo** [comment]
Use ````HEAD_BRANCH```` instead

**Comment by caarlos0** [comment]
indeed.

thanks
