### ISSUE TITLE
Failed to reset/delete a dedicate node, failed to add a new dedicate host

### ISSUE THREAD

**Issue by adamyao** [Shippable/support#1105]
I posted this inside  the issue#1097. #1097 has been closed, so I have to issue a new.
When I try to reset/delete an existing dedicate node, or try to add a new dedicate node, I got the following error message:

![screen shot 2015-02-27 at 1 59 39 pm](https://cloud.githubusercontent.com/assets/10078683/6422121/ad061842-be89-11e4-9904-4d0767fd0b4a.png)

**Comment by manishas** [comment]
@adamyao only subscription owners can add dedicated hosts. You're seeing these errors because you are a collaborator.

**Comment by adamyao** [comment]
I added the existing dedicate node back a month ago.
.

**Comment by manishas** [comment]
@adamyao we recently added some checks to make our permissions model align more closely with GitHub's. Is it possible to have an owner of the subscription add the host?
