### ISSUE TITLE
An owner must login before you can enable this repo

### ISSUE THREAD

**Issue by DanLipsitt** [Shippable/support#1106]
I'm unable to get both github and bitbucket connections working at the same time. I've tried various combinations of deleting shippable logins and deleting and re-authorizing OAuth connections. I'm currently getting the following error for my bitbucket account:

```
An owner must login before you can enable this repo
```

**Comment by manishas** [comment]
@DanLipsitt are you seeing this error when you try to connect your BitBucket account?

**Comment by DanLipsitt** [comment]
The icons say "repos on" for both github and bitbucket, but I got the error when I tried to enable a repo. The error persisted when I deleted and re-created my accounts. It's working now. Did you change something or did it fix itself?

**Comment by manishas** [comment]
We did a rather major update last night and deployed a couple of fixes today so that might be it. 

Is everything working as expected now?

**Comment by DanLipsitt** [comment]
So far so good. Thanks.

**Comment by Manc** [comment]
I'm getting the same error message. First I connected with Bitbucket, then added GitHub. The GitHub repositories are listed, but when I try to enable one of them, I get "An owner must login before you can enable this repo".

**Comment by djindjic** [comment]
Sorry for posting new issue for this theme, but I also still have same error reported here: https://github.com/Shippable/support/issues/1161
