### ISSUE TITLE
Option to remove old builds

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1108]
Is there an option to remove old builds for a project? One of my projects has over 100 build as of now and I would like to keep last 20 of them only

**Comment by manishas** [comment]
You can delete each build by clicking the X action. There's no bulk delete as of now.

**Comment by naveensky** [comment]
@manishas - I do that. Would love if we have a bulk delete option, probably via shippable.yml, as well. I will close this ticket, but if you make any update on this, please ping me

**Comment by avinci** [comment]
@naveensky we are implementing that feature. So that its rolling builds...
