### ISSUE TITLE
Unparsable shippable.yaml causes manually triggered builds to hang forever

### ISSUE THREAD

**Issue by pniederw** [Shippable/support#1110]
UI hangs forever at "Waiting for build information...". No feedback about the parse error.

**Comment by manishas** [comment]
@pniederw you will see a notification in the notifications tab for the project. We're improving the experience around notifications soon so it will be more prominent.

**Comment by pniederw** [comment]
If I'm not mistaken, there is no such notification in case of a manually triggered build. Anyway, feedback needs to be improved, and having the UI hang at " "Waiting for build information..." is a clear bug.

**Comment by manishas** [comment]
We'll fix the notifications. And yes, he build should not hang. I'll file an internal bug to track this.

**Comment by lekhab** [comment]
the build hanging issue has been fixed. Notifications are shown in case of manually triggered builds.  closing this bug.  We are continuing to work on improving the notifications flow in general.
