### ISSUE TITLE
How to exclude specific build from matrix

### ISSUE THREAD

**Issue by pniederw** [Shippable/support#1112]
Let's say I have

```
jdk:
  - openjdk6
  - openjdk7

env:
  -FOO=bar1
  -FOO=bar2
```

How do I exclude the build with openjdk7 and FOO=bar2? The docs only have an exclude with a single value (e.g. `matrix: exclude: - jdk: openjdk7`), but I don't understand what that gives over not including that value in the first place (in the `jdk:` section). I've tried:

```
matrix:
  exclude:
    - jdk: openjdk7
      env: FOO=bar2
```

That's analogous to the `matrix: include:` syntax given in the docs, but it doesn't seem to parse (builds never start, no feedback).

I've also tried to exclusively use `matrix: include: ...` instead, but then my secure env variables don't work anymore, no matter how I add them (`env: global: ...`, repeated for every `matrix: include:`, etc.).

**Comment by pniederw** [comment]
Actually this might be a consequence of #1113.

**Comment by manishas** [comment]
Closing since this was a side effect of a service interruption.

**Comment by asanchezgiraldo** [comment]
@manishas are you able to exclude multiple variables from your matrix.

so if I have 

```ymal
env: 
 - FOO=prod
 - FOO=dev
 - FOO=test

matrix:
 exclude:
  - env: FOO=prod
  - env: FOO=dev
```

**Comment by ambarish2012** [comment]
@asanchezgiraldo Yes that is possible.

**Comment by asanchezgiraldo** [comment]
@manishas thanks, I was having issues as i had multiple `env: ` in my matrix like below but I figure out how to exclude them

```ymal
env: 
 - FOO=prod VOO=true
 - FOO=dev VOO=true
 - FOO=test VOO=false

matrix:
 exclude:
  - env: FOO=prod VOO=true
  - env: FOO=dev VOO=true
```
