### ISSUE TITLE
sudo apt-get install libmagic-dev fail

### ISSUE THREAD

**Issue by zedtux** [Shippable/support#1114]
Since the 7th of February I have the following issue at the before_install step:

    Reading package lists...
    Building dependency tree...
    Reading state information...
    The following packages were automatically installed and are no longer required:
    libnet-daemon-perl libdbi-perl libterm-readkey-perl libhtml-template-perl
    mysql-client-core-5.5 libdbd-mysql-perl libplrpc-perl mysql-client-5.5
    Use 'apt-get autoremove' to remove them.
    The following NEW packages will be installed:
    libmagic-dev
    0 upgraded, 1 newly installed, 0 to remove and 51 not upgraded.
    Need to get 73.7 kB of archives.
    After this operation, 300 kB of additional disk space will be used.
    Err http://archive.ubuntu.com/ubuntu/ precise-updates/main libmagic-dev amd64 5.09-2ubuntu0.5
    404 Not Found [IP: 91.189.92.201 80]
    Err http://archive.ubuntu.com/ubuntu/ precise-security/main libmagic-dev amd64 5.09-2ubuntu0.5
    404 Not Found [IP: 91.189.92.201 80]
    Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/file/libmagic-dev_5.09-2ubuntu0.5_amd64.deb 404 Not Found [IP: 91.189.92.201 80]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    Reading package lists...
    Building dependency tree...
    Reading state information...
    The following packages were automatically installed and are no longer required:
    libnet-daemon-perl libdbi-perl libterm-readkey-perl libhtml-template-perl
    mysql-client-core-5.5 libdbd-mysql-perl libplrpc-perl mysql-client-5.5
    Use 'apt-get autoremove' to remove them.
    The following NEW packages will be installed:
    libmagic-dev
    0 upgraded, 1 newly installed, 0 to remove and 51 not upgraded.
    Need to get 73.7 kB of archives.
    After this operation, 300 kB of additional disk space will be used.
    Err http://archive.ubuntu.com/ubuntu/ precise-updates/main libmagic-dev amd64 5.09-2ubuntu0.5
    404 Not Found [IP: 91.189.92.200 80]
    Err http://archive.ubuntu.com/ubuntu/ precise-security/main libmagic-dev amd64 5.09-2ubuntu0.5
    404 Not Found [IP: 91.189.92.200 80]
    Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/file/libmagic-dev_5.09-2ubuntu0.5_amd64.deb 404 Not Found [IP: 91.189.92.200 80]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    Reading package lists...
    Building dependency tree...
    Reading state information...
    The following packages were automatically installed and are no longer required:
    libnet-daemon-perl libdbi-perl libterm-readkey-perl libhtml-template-perl
    mysql-client-core-5.5 libdbd-mysql-perl libplrpc-perl mysql-client-5.5
    Use 'apt-get autoremove' to remove them.
    The following NEW packages will be installed:
    libmagic-dev
    0 upgraded, 1 newly installed, 0 to remove and 51 not upgraded.
    Need to get 73.7 kB of archives.
    After this operation, 300 kB of additional disk space will be used.
    Err http://archive.ubuntu.com/ubuntu/ precise-updates/main libmagic-dev amd64 5.09-2ubuntu0.5
    404 Not Found [IP: 91.189.92.200 80]
    Err http://archive.ubuntu.com/ubuntu/ precise-security/main libmagic-dev amd64 5.09-2ubuntu0.5
    404 Not Found [IP: 91.189.92.200 80]
    Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/file/libmagic-dev_5.09-2ubuntu0.5_amd64.deb 404 Not Found [IP: 91.189.92.200 80]
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    Build completed
    Skipping artifact upload
    Build completed

**Comment by zedtux** [comment]
Here is the extract from my `shippable.yml` file:

    before_install:
      - shippable_retry sudo apt-get install libmagic-dev

**Comment by rageshkrishna** [comment]
Please try adding a `sudo apt-get update` before the apt-get install command. This can happen when the apt repositories are updated with newer packages and the cached package lists get out dated.

**Comment by zedtux** [comment]
This solved my issue.
