### ISSUE TITLE
script fails after shippable_retry succeeds

### ISSUE THREAD

**Issue by pelegb** [Shippable/support#1115]
Hi,
I'm using the following shippable.yml in order to build an android project:

language: java

jdk:
    - openjdk7

install:
    - shippable_retry sudo apt-get update -y
    - "sudo apt-get install -y lib32stdc++6 lib32z1"

script:
    - "shippable_retry ./TrivialDrive/gradlew -p ./TrivialDrive/ --stacktrace clean build"

The script line fails though second run outputs Build Successful (I need two runs because of the Android SDK Manager Gradle plugin).

Please assist.

Thanks.

**Comment by manishas** [comment]
@pelegb are you still running into this? If yes, can you paste a link to a build which failed with the issue above?

**Comment by pelegb** [comment]
I made a work-around so I don't know if this still occurs.

**Comment by rogierslag** [comment]
Encountering the same issue :(

**Comment by pelegb** [comment]
My workaround was to perform the retry myself, running the command twice in my script:
- "./failing_command || true"
- "./failing_command || true"

Check if this helps you.

**Comment by rogierslag** [comment]
I opted for `bundle install || bundle install || bundle install`:wink:
