### ISSUE TITLE
Error parsing test reports

### ISSUE THREAD

**Issue by swoertz** [Shippable/support#1116]
I am using a c++ and the boost::unit_test_framework to generate the shippable/testresults/*.xml files.

The build process suceeds and the generated files are found, but I get the following error when shippable is parsing the xml.
> Error parsing test reports.

Is there a way to get more information from the parser? So I could fix the xml files...

**Comment by manishas** [comment]
@swoertz we parse junit format for test reports, so you will need to convert the output to junit format. Hope this helps.

**Comment by manishas** [comment]
Closing. Please let me know if converting to junit format didn't work.
