### ISSUE TITLE
API support to add, initialize, deploy and remove dedicated nodes

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1117]
We want to move our Shippable dedicated nodes to an AWS autoscaling group that will also benefit from spot/price launch configuration for EC2 instances.

Currently there is not way for us to programmatically call an Initialize + Deploy sequence.

The flow would be as follows

1. On instance boot + after our custom provision from cloud-init, allow instance to call your API and register itself as a dedicated node. On success do
2. Call initialise, on success do
3. Deploy Shippable containers and proactively pull our custom images
4. If any steps fail, deregister (remove) dedicated node and kill the EC2 instance

The above covers initial cluster launch and scale up strategy. 

Scale down (due to no load, or spot price too high) triggers an SNS call per destroyed instance, that we 'll handle and call your API to remove killed dedicated node.

Would be a very nice feature to have.

**Comment by manishas** [comment]
This is a great scenario and we're working on some things that will address this. Will update very soon once we announce.

**Comment by velo** [comment]
++

**Comment by pmoust** [comment]
@manishas looking forward to some update on this (or similar feature).
We 've released an API client in Go https://github.com/PeoplePerHour/go-shippable and we 'd like to include said feature :hammer:

**Comment by pmoust** [comment]
Closing since dedicated nodes are deprecated.
