### ISSUE TITLE
High amount (almost 50%) of builds are getting stuck on "Waiting for mongodb to start..."

### ISSUE THREAD

**Issue by DanielLevin** [Shippable/support#1119]
organization: startappdev 
project: portal 

Hi,
We are hitting build timeouts in almost 50% of builds.
Builds are getting stuck on  "Waiting for mongodb to start..."
The workaround is to use [reset_minion] which works in most of the cases, but it leads to a terrible waste of time.
Is there anything that can be done to improve the situation?

Thanks,

Daniel

**Comment by manishas** [comment]
@DanielLevin we'll take a look at this, thanks for reporting!

**Comment by manishas** [comment]
@DanielLevin are you still running into this?

**Comment by DanielLevin** [comment]
Yes, all the time.

**Comment by j1z0** [comment]
We are also hitting it. Seems to have started around Thursday or Friday of last week.

**Comment by manishas** [comment]
@DanielLevin @j1z0 we have a fix for this and we'll push it out soon. I'll update you when it's deployed. Thanks!

**Comment by manishas** [comment]
This was fixed several days ago, so you shouldn't see this any more. Let me know if it is still happening.

**Comment by DanielLevin** [comment]
This is still happening. Should I open a new bug or would you rather reopen this one?
