### ISSUE TITLE
Do not attempt a build if the PR if base<->head have merge conflicts

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1120]
PR contains conflicts with base branch that cannot be automatically resolved.

Expected behavior: no build triggered
Actual behavior: build starts and fails on git merge.

Not that important, but nice to not have a spam to the team members if a PR fails for such reason.

**Comment by manishas** [comment]
Thanks for the suggestion! We'll consider this enhancement when we make improvements to the PR experience.

**Comment by manishas** [comment]
While this is a nice to have, it's not on our current roadmap. Closing this out... will reopen if there are several +1s for this.
