### ISSUE TITLE
Istanbul: No such file or directory

### ISSUE THREAD

**Issue by pcullin-ratio** [Shippable/support#1121]
I'm attempting to implement unit test running and code coverage visualization into my Node.js project using the Node sample projects and documentation provided. However, I'm not using Grunt as a task runner - just straight NPM. And being new to all this, I've had some difficulty.

I was able to get my Mocha tests to run and save xunit output to shippable/testresults/result.xml. That enabled Shippable to see that I had passing tests finally. However, there is an issue with Istanbul that is preventing code coverage from working as well.

I have this block in my shippable.yml:
after_script:
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha
  - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/

This is the error I'm seeing in my build:
./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha
/home/shippable/build/build.sh: line 87: ./node_modules/.bin/istanbul: No such file or directory

Also, I thought the Tests tab was supposed to show the output from the Mocha test runner but it is only showing the number of Passed/Failed/Errors/Skipped tests (albeit properly). I could use some guidance on how to get this all set up for my project specifically.

**Comment by manishas** [comment]
@pcullin-ratio are you still running into this? We'll take a look if this is still happening...

**Comment by pcullin-ratio** [comment]
Yes, but I don’t think it’s an issue with your service. I can’t get Istanbul to work properly locally, so I’ll work to resolve those issues myself.

However, I could use some more detailed direction on getting both unit test results and code coverage set up properly for a Node.js application using NPM. The only examples I’ve been able to find seem to use Grunt, which I’m not using and have no plans to use.

The only way I was able to get the unit test reporter to work properly was to do this in my test NPM script:
"test": "mocha test/ --recursive --reporter xunit > shippable/testresults/result.xml"

It works, but I’m wondering if there’s a more straightforward method…

**Comment by manishas** [comment]
@pcullin-ratio I'm tagging this so that we can get a build sample for this in the next few days. Closing the issue since the original Istanbul problem has no action item for us.
