### ISSUE TITLE
no build after merge to master (bitbucket)

### ISSUE THREAD

**Issue by djindjic** [Shippable/support#1124]
I have just tried to utilize:
```
branches:
  only:
    - master
```
and make an new branch, push it to my bitbucket account and everything works fine (no build for no master branch). When I merge it locally to my master and push that merged master, there is no build started.

**Comment by rageshkrishna** [comment]
@djindjic When you did the merge to master, did git do a fast-forward merge or did it create a merge commit? There is a known bug with BitBucket webhooks for fast-forward commits due to which we cannot trigger builds. Please let me know if this is the case. Thanks!

**Comment by djindjic** [comment]
no it doesn't create merge commit, just merge commits from feature branch. It seems to be that known bitbucket issue. If you have seen this issue documented in their issues tracking tool, could you please give me a link? I want to subscribe on it.
thanks!

**Comment by rageshkrishna** [comment]
Here's the BitBucket issue for this problem: https://bitbucket.org/site/master/issue/7775/post-service-does-not-provide-useful
