### ISSUE TITLE
How to install JCE unlimited strength jars? (on shippable)

### ISSUE THREAD

**Issue by aug70** [Shippable/support#1126]
Has anybody done this before? How do you change the 

* local_policy.jar
* US_export_policy.jar

and install JCE unlimited strength jars?

Duplicate of https://github.com/Shippable/support/issues/892

**Comment by manishas** [comment]
closing as dup of #892. I've entered this into our system and will update when i know more.

**Comment by manishas** [comment]
you can actually do this yourself by add the policy files you want to use in the root of your repo, and the following lines in the yml:

```
before_install:
    - sudo mv -f local_policy.jar /usr/lib/jvm/java-7-oracle/jre/lib/security
    - sudo mv -f US_export_policy.jar /usr/lib/jvm/java-7-oracle/jre/lib/security
```
