### ISSUE TITLE
I don't see any Bitbucket repositories

### ISSUE THREAD

**Issue by girlprogrammer** [Shippable/support#1127]
With Bitbucket username 'girlprogrammer', the Shippable application can't see any repositories, not of my own and not of any organizations I'm in.  They are private repositories, not public.

I was seeing this problem, so then I tried to delete my Shippable account and start over, which may have made it worse.  How can I try this out with a Bitbucket repository?

![image](https://cloud.githubusercontent.com/assets/6608332/6494124/6f7cac68-c28d-11e4-8704-a4ae9b9314d7.png)

My organization's looking for a CI solution and I had met you guys at GlueCon last year.  I was hoping we could see if this would work.

**Comment by manishas** [comment]
@girlprogrammer our logs show you have mercurial repositories in your account. 

We currently support git based repositories, which is why you don't see your repos in Shippable. 

Hope this helps. Thanks!

**Comment by manishas** [comment]
@girlprogrammer i am closing this issue since a feature request for Mercurial support is already on our plate. We will let you know when we add it.
