### ISSUE TITLE
A build was attempted but failed for PR #55 of "ContaAzul/Puppet" because the YML file could not be merged.

### ISSUE THREAD

**Issue by velo** [Shippable/support#1131]
````
 Error merging YML file in "ContaAzul/Puppet"  in a few seconds Low

A build was attempted but failed for PR #55 of "ContaAzul/Puppet" because the YML file could not be merged.
````

I'm getting this error message over and over.  But the PR is mergeable and I did merged with target branch.

https://app.shippable.com/builds/54f9e7bbaf46330e001209af
https://github.com/ContaAzul/Puppet/pull/55

**Comment by manishas** [comment]
@velo was it mergeable automatically? or did you do a manual merge?

**Comment by velo** [comment]
Initially it was not.

But I did a manual merge to get all mergeable again.

**Comment by caarlos0** [comment]
Just have the same issue.

The PR was automatically mergeable: no conflicts with master

I merged master into it but it did not fix the problem. Had to merge the PR without build...

**Comment by rageshkrishna** [comment]
@caarlos0 Was it the same project? If not, can you please give me the project name or id and PR number? Thanks.

**Comment by caarlos0** [comment]
@rageshkrishna nope: https://github.com/ContaAzul/invoice-admin/pull/61

It's a private project, though

**Comment by velo** [comment]
FWIW, it is also happening on another project!
https://app.shippable.com/builds/54ff04ed9b4cf40c00002644
https://github.com/ContaAzul/heimdall/pull/4

This one I just forked master and no one touch master since I did that!

**Comment by rageshkrishna** [comment]
Thanks! I'm looking in to heimdall right now to see what's going on.

**Comment by rageshkrishna** [comment]
@velo This was very helpful. I can see now why it's failing. The YML file in master has no new line at the end of the file, but when you changed it in your PR a new line got introduced. The bug at our end was that we were not telling `patch` to ignore whitespace changes while merging the YML file.

We'll have a fix for this deployed very soon.

**Comment by velo** [comment]
thanks!

lemme know when I can retry!

**Comment by caarlos0** [comment]
@rageshkrishna nice! Thank you very much!

**Comment by rageshkrishna** [comment]
@velo @caarlos0 We've pushed some fixes to the YML merge that should address this particular error. Please give it a shot and let me know how it goes!

**Comment by velo** [comment]
Ok, thanks!

**Comment by velo** [comment]
worked for me!
https://app.shippable.com/builds/54ffbbc340ac2e0c00333250

Thanks!

**Comment by manishas** [comment]
Closing.
