### ISSUE TITLE
Can not delete a project

### ISSUE THREAD

**Issue by murtyk** [Shippable/support#1133]
Getting an Internal Server Error when tried to delete (clicking trash can) a project.

**Comment by avinci** [comment]
are you the owner of the repo on GH? Can you give me your repoID so that I can check it?

**Comment by murtyk** [comment]
It is wtracker on bitbucket

**Comment by murtyk** [comment]
https://bitbucket.org/murtykorada/wtracker.git

**Comment by manishas** [comment]
this is complete, so closing the issue. please re-open if it doesn't work for you.
