### ISSUE TITLE
Builds timing out

### ISSUE THREAD

**Issue by arunask1992** [Shippable/support#1134]

**Comment by manishas** [comment]
@arunask1992 can you please paste your shippable.yml in a comment?

**Comment by arunask1992** [comment]
language: java

jdk:
  - oraclejdk8
env:
  # - NODE_ENV=production

git:
  submodules: false

branches:
  only:
    - dev
    - master

before_install:
  - npm install yo
  - npm install bower
  - npm install grunt-cli

install:
  - bower install
  - npm install

before_script:
  - mkdir -p shippable/test-results
  - mkdir -p shippable/code-coverage
  - psql -c 'create role billingone with LOGIN PASSWORD ‘password’;'
  - psql -c 'create database billingone;'
  - psql -c 'create database billingone_test;'
  - psql -c 'grant create on database billingone to billingone;'
  - psql -c 'grant create on database billingone_test to billingone;'

script:
  - spring_profiles_active=test gradle cleanTest test
  - grunt test

after_success:
  # - git push git@heroku.com:ultimate-seed.git master

after_failure:
  # -

after_script:
  # - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -u tdd
  # - ./node_modules/.bin/istanbul report cobertura --dir  shippable/codecoverage/

**Comment by rageshkrishna** [comment]
@arunask1992 Thanks for the update. I'm going to try and trigger some builds manually to figure out what's going on. I'll update this issue as soon as I know more.

**Comment by rageshkrishna** [comment]
@arunask1992 It looks like we have a bug in our YML parser when you use stylized quotes. Please change the following line:
````
psql -c 'create role billingone with LOGIN PASSWORD ‘password’;'
````
Notice the quotes around `password`? That needs to be changed to use regular single-quotes like so:
````
psql -c 'create role billingone with LOGIN PASSWORD \'password\';'
````
Please update your YML and try running a build. It should start running this time.

I have already created an internal issue to fix our handling of this scenario.

**Comment by manishas** [comment]
@arunask1992 did you get a chance to try out the suggestion above? Please let me know.

**Comment by manishas** [comment]
Closing due to lack of response.

@arunask1992 please re-open if you still run into this.
