### ISSUE TITLE
minion doesn't build archive even though files are in ./shippable

### ISSUE THREAD

**Issue by kornelc** [Shippable/support#1135]
My goal:
I'm trying to set up CI for a Play Framework app which is to be deployed on AWS. In addition I would like to be able to download my artifacts for this app from shippable.com UI, for manual deploy. I got as far as building the artifacts and copying them into ./shippable, in my project root.

The problem:  
The doc says I should do the copy into ./shippable from before_archive. But before_archive is ignored. So I put the cp -R command at the end of my script. This works. ls -R ./shippable shows my artifacts. But they down't get zipped up. The console doesn't show any archival step. 
It's my assumption that first I must get this working before I can even attempt the push to my AWS instance. So I believe I'm stuck.

Can you please help?
-kornel

**Comment by rageshkrishna** [comment]
@kornelc You'll need to turn on archiving in your `shippable.yml` file by adding the following line:
````
archive: true
````
This will prevent `before_archive` from being ignored and your artifacts will be uploaded.

**Comment by manishas** [comment]
@kornelc i am closing this issue. please re-open if the suggestion above doesn't help.
