### ISSUE TITLE
Build hangs at processing stage

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1136]
I have a maven project which I dockerized by following the instructions here --  http://blog.shippable.com/making-deployments-even-easier-with-docker-build 

The build hangs at processing stage forever. Not sure what's going on ... the last step it shows is "boot successful"

**Comment by manishas** [comment]
@hshira can you please try reinitializing and redeploying your dedicated host and try again?

**Comment by hshira** [comment]
I did. Didn't work.
 BTW do you have a private channel where I can create a ticket?

**Comment by manishas** [comment]
@hshira this is our main support site. If you want to send some information that you don't want to include here, feel free to send an email to manisha@shippable.com

Are you still running into this? If yes, can you include a link to a hanging build?

**Comment by manishas** [comment]
@hshira you can now run dockerbuild without dedicated hosts.

Closing this issue but please leave a comment if you have any questions.
