### ISSUE TITLE
Docker HUB organization account: which credentials?

### ISSUE THREAD

**Issue by ringods** [Shippable/support#1137]
Both on Bitbucket and Docker Hub, I have a personal account and an organization account. I login in Shippable with my personal BitBucket account and it detects the BitBucket organization just fine.

On Docker Hub, an organization doesn't have credentials. Which credentials should I enter for Docker Hub support in my organization on BitBucket/Shippable?

**Comment by manishas** [comment]
@ringods you will need to use the docker hub credentials that will let us pull the image from your org account on docker hub.

**Comment by ringods** [comment]
That'll be my personal credentials then. :-/

**Comment by manishas** [comment]
yes. please re-open this issue if it doesn't work for you.
