### ISSUE TITLE
`exit 0` should not fail a build

### ISSUE THREAD

**Issue by winglian** [Shippable/support#1141]
I simply have `exit 0` in the `script` block, but that seems to trigger a failure, which is incorrect.
![screenshot 2015-03-09 18 31 30](https://cloud.githubusercontent.com/assets/381258/6566137/a7597b2c-c68c-11e4-9478-54580a9b960c.png)

**Comment by manishas** [comment]
This will be fixed soon. I'll let you know when its deployed.

**Comment by manishas** [comment]
This has been fixed, so closing. let me know if you run into this ever again.

**Comment by trollixx** [comment]
Same problem occurs in `after_success` command. I have tried the following code there to skip deployment in case a build is triggered from a pull request:

```bash
if ! [ "$PULL_REQUREST" = false ]; then exit 0; fi;
```

And the whole build gets marked as failed.
