### ISSUE TITLE
Grunt + Compass + PNG Error

### ISSUE THREAD

**Issue by egermano** [Shippable/support#1142]
I've got some issues with grunt, compass and png (when generate sprites).

This already worked in past, but now, don't.

[That's my build](https://app.shippable.com/builds/54ff539c50bbf40d00dd6822)

That's the error I've got:

    Warning: ChunkyPNG::SignatureMismatch on line 102 of /var/lib/gems/1.8/gems/chunky_png-1.3.4/lib/chunky_png/datastream.rb: PNG signature not found, found "\211PNG\n\032\n\000" instead of "\211PNG\r\n\032\n"!

**Comment by manishas** [comment]
This is an old issue and we've revamped our build system since. Closing.
