### ISSUE TITLE
Build fails with "syntax error: unexpected end of file"

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#1144]
Given the following valid `script` in our `shippable.yml`:

```yaml
script:
  - composer install --no-progress --no-interaction
  - >
    if [[ "$UNIT_TESTS" == "yes" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
    fi
```

All builds fail with an error like this:

```
if [[ "$UNIT_TESTS" == "yes" ]]; then
  echo;
  echo "Running unit tests";
  ./bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
fi
|1426063856
/home/shippable/build/build.sh: eval: line 85: syntax error: unexpected end of file
```

Not even something like `[[ "$UNIT_TESTS" == "yes" ]] && ./bin/phpunit ...` works since that seems to trigger parsing errors. (*Error parsing shippable.yml in `<project>`*)

Any idea what's wrong? The same setup works fine on Travis.

**Comment by manishas** [comment]
@mbrodala we'll take a look at this. thanks!

**Comment by manishas** [comment]
@mbrodala I see your recent builds are succeeding? Are you still running into this?

**Comment by mbrodala** [comment]
@manishas No, I just haven't triggered a build with such a configuration in the meantime again. I just tried again and it still fails with the same error.

**Comment by rageshkrishna** [comment]
@mbrodala I believe the issue is a missing `;` on the line running phpunit. When you use the `>` token in a YML file, the lines following it will be rendered as a single string without any line breaks. As a result, you'll have a bash command that does not end with a `;` and has a trailing `fi`.

Adding a couple of `;` like so should get rid of the syntax error:

````
script:
  - composer install --no-progress --no-interaction
  - >
    if [[ "$UNIT_TESTS" == "yes" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage;
    fi;
````

I hope this helps!

**Comment by mbrodala** [comment]
Thanks for the hint, that solved the issue. :-)
