### ISSUE TITLE
Use Dockerfile to build custom build image?

### ISSUE THREAD

**Issue by velo** [Shippable/support#1145]
Is it possible to do that?

I wanna change my shippable.yml from something like:
````
build_image: shippable/minv2
````

To something like:
````
build_image: Dockerfile
````

I wanna this Dockerfile just to build my application, won't publish this build container anywhere.

**Comment by manishas** [comment]
You can build from a dockerfile if you have dedicated hosts - http://blog.shippable.com/making-deployments-even-easier-with-docker-build

**Comment by velo** [comment]
even if I don't wanna deploy this container?

**Comment by manishas** [comment]
Yes. For security reasons, we do not let custom containers run on our multi-tenant hosts.

**Comment by velo** [comment]
nice!
