### ISSUE TITLE
How do we give you money?

### ISSUE THREAD

**Issue by pledgemusic** [Shippable/support#1146]
Hi Manisha,

For the life of me, I can't find a link to upgrade to parallel builds plan.

('pledgemusic' account)

Thanks,

Zach

**Comment by kastork** [comment]
Or indeed to make changes of any kind to account settings.  There is mention of a need to upgrade the account for various reasons (tokens, dedicated builds, etc), but no way to do it.  If you go out and try to "sign up" from the pricing page, it just logs you back in.

**Comment by manishas** [comment]
@pledgemusic @kastork our upgrades are per org and you can do this by clicking on 'Plans and Billing' on org page on Shippable. Let me know if you need help with this.

**Comment by pledgemusic** [comment]
@manishas that's giving me an "Internal Server Error" for AMEX. Thanks.

**Comment by fommil** [comment]
:+1: I was interested in getting custom docker images to my account (for FOSS projects, actually... it's not always about being gratis) but couldn't find the link. Had to come here to find out how.

**Comment by fommil** [comment]
OMG OMG OMG, $12/year.... ![shut up and take my money](http://i3.kym-cdn.com/photos/images/newsfeed/000/264/241/9e9.gif)

**Comment by fommil** [comment]
seriously though, I really can't find how to sign up. The www host makes me go to the app host, and there is no link there to sign up.

**Comment by manishas** [comment]
@fommil from the dashboard, you can click on the org you want to upgrade. Click on 'plans and billing' on the top right of the org page. Add your card and then choose Startup plan to upgrade.

**Comment by fommil** [comment]
@manishas you got here before I deleted my comment after finding it :smile: Awesome strategy! Myself and several others have been trying to get Travis to do this for about a year and they are total oil tankers on pricing. Also, custom docker images, wow. I'm telling everybody about this, it is a game changer.

**Comment by manishas** [comment]
@pledgemusic can you please try another card? We use a third party payment processing gateway and hence we do not control this. I am closing this issue, but if you run into further problems upgrading, please send me an email at manisha@shippable.com
