### ISSUE TITLE
Test failed on Shippable, but is successful everywhere else

### ISSUE THREAD

**Issue by angelathewebdev** [Shippable/support#1148]
It's a very strange situation for which I can not fathom.

My tests have passed on both my local machine (node v0.12.0) and on another machine (node v.0.10.33) with flying colours, but when I pushed it to Shippable. It failed. I don't understand why or what could cause such behaviour.

And it's difficult for me to pinpoint the source of the issue as each try requires another code push to the repository. This is my repository on Bitbucket https://bitbucket.org/angelawang/import_playlist, please let me know if anyone need repository access.

**Comment by angelathewebdev** [comment]
I noticed that the test didn't ran its full course. The timeout I've set in the script is 10 minutes. But the execution terminated much earlier than that. The script made quite a few HTTP requests, which can cause it to run quite slowly. Perhaps there is also a limit on how long the script can run?

**Comment by angelathewebdev** [comment]
Hi, I'm wondering if there's any update on this issue?

**Comment by rageshkrishna** [comment]
Hi @angelathewebdev. It looks like your unit tests are indeed failing, but it's impossible for me to say exactly why as your project is private and I can't see the code. You'll need to give me access if you'd like me to debug this further. My bitbucket id is `ragesh`. Thanks!

**Comment by angelathewebdev** [comment]
I've added you to the repo

**Comment by rageshkrishna** [comment]
I'm unable to get the tests to pass locally because the ` 虾米 bot for user home page` test is returning an empty array for data. Here's the output when I try to run your crawler from the command line:
````
{"data":[],"status":200}
````
Unfortunately, I cannot guess why this is happening. Perhaps the API you're hitting is filtering by IP or geographic location.

**Comment by angelathewebdev** [comment]
I see, that makes total sense to me now :)

**Comment by angelathewebdev** [comment]
Is it possible to have Shipping configure a local environment variable so I
can run tests differently on Shippable vs. locally?

**Comment by rageshkrishna** [comment]
Absolutely. We `export SHIPPABLE=true;` on every build. A full list of the environment variables we set is available at http://docs.shippable.com/en/latest/config.html#common-environment-variables

**Comment by manishas** [comment]
Closing this. @angelathewebdev let us know if you need further assistance with anything.
