### ISSUE TITLE
Test environment using multiple docker containers

### ISSUE THREAD

**Issue by jtseatwave** [Shippable/support#1149]
I have a go app that connects to a database running on couchbase server.

I want to run tests in a similar environment to production and I do this by running two containers.  One holds the couchbase server, the other holds the go app built from a git repository and the test files.  I currently do this in jenkins by running a script that starts the couchbase server, gets the IP address of that container and then passes it to the app container.

Does shippable support running multiple containers to setup the build environment?

**Comment by manishas** [comment]
We cannot comment on details, but your scenario will be addressed very soon. Look for an announcement in a few days.

**Comment by leonfs** [comment]
Are there any news about this feature?

**Comment by manishas** [comment]
@jtseatwave @leonfs this scenario is addressed with Shippable Formations - https://app.shippable.com/mktg/#formations

Your scenario is a perfect fit for this... please set up a demo with us at https://shippable.youcanbook.me/ to check out how it works.

**Comment by manishas** [comment]
Closing this this scenario is addressed with Formations. Please set up a demo or shoot me an email at manisha@shippable.com if you have questions.
