### ISSUE TITLE
Test and build docker image workflow

### ISSUE THREAD

**Issue by rvrignaud** [Shippable/support#1150]
Hello,

I was trying to use the new Docker build feature. What I need to achieve is : 
* run tests in a generic image like shippable/minv2
* if tests succeed build the docker image of the project
* push the image to docker hub

If I understand correctly the actual workflow,  right now 
* you first build the docker image of the application
* then use that image to run tests

This workflow doesn't work for me because in my runtime image I don't want to have all files/tests etc related to the tests.

Am I missing something ? Is there any workaround or feature planned in roadmap ?

Thanks in advance

**Comment by manishas** [comment]
Your understanding of our current feature is correct. But we've heard feedback from multiple users who want to achieve your exact workflow and we're working on adding it soon. Watch for an announcement in the next few days and I'll update this issue when it's available.

**Comment by mavarazy** [comment]
+1

**Comment by manishas** [comment]
@rvrignaud we now have post CI docker build where you can have a Dockerfile in your repo, but the Dockerbuild happens only if CI passes on minv2. Check out the docs at http://docs.shippable.com/en/latest/docker_build.html#post-ci-docker-build
and our blog - http://blog.shippable.com/post-ci-dockerbuild

**Comment by manishas** [comment]
Closing this issue. Please re-open if you need more help.
