### ISSUE TITLE
Configure EC2 Instance as Minion

### ISSUE THREAD

**Issue by kastork** [Shippable/support#1151]
Hi,

I'm having trouble getting an Ubuntu 14.04LTS instance in AWS initialized.

Here's what I've done:

- Built the box up, installing ansible dependencies and docker.io
- Provided the instance with a fixed public IP address
- Configured the security group to allow port 22 access from anywhere
- Ran the command you provide in the minion setup.
- Verified the shippable user was created and that the ssh key is there, permissions on .ssh and its contents are correct.
- Restarted the machine

Now when I run the initialization in the shippable interface, the procedure executes, but fails with

```
ssh: connect to host ###.###.###.### port 22: Connection timed out rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
```

So it looks to me like shippable can't get connected to the EC2 instance.

I went back and further added 'AllowUser shippable' to the '/etc/ssh/sshd_config' file and restarted the sshd service...  no joy.

Are there further steps I need to take on the minion machine that I've missed?

**Comment by kastork** [comment]
Follow up

To test the user, I added a new keypair.  I can ssh in to the box as the shippable user with this key pair.

I kicked off another shippable minion initialization in the shippable ui, and watched the logs at `/var/log/auth.log`  That log shows no sign that the shippable service is even attempting to connect.

**Comment by manishas** [comment]
We'll take a look at this and get back to you.

**Comment by kastork** [comment]
This was due to a ACL configuration error on my EC2 VPC.  Sorry for the false report.
