### ISSUE TITLE
Shared local maven repository between projects

### ISSUE THREAD

**Issue by akribopo** [Shippable/support#1152]
Hi, 

I have 5 different java projects. During the build of No.1 project, mvn install is executed in order to install the artifacts of the build to the local maven repository. Cache is also enabled. 

However, when the build for project No.2 (which has a dependency in project No.1)  is executed, it fails because there aren't any artifacts of No.1 project in the local repository. 

Is there any solution to share local maven repositories between projects/minions?

**Comment by reddy6ue** [comment]
I am also trying to solve the same problem. With jenkins it's a flag on the workspace. Shippable adoption by the java community will be boosted if this feature were made available.

**Comment by manishas** [comment]
Our builds platform runs builds in a distributed fashion, so this is not currently possible with this architecture.

You can solve this by pushing your repository to S3 and pulling it when needed.
