### ISSUE TITLE
Docker build workflow

### ISSUE THREAD

**Issue by thephred** [Shippable/support#1154]
I looked at the current docker build workflow and there is a scenario I can't accomplish with it currently.

I have another repo that is built and tested by shippable and when a build succeeds I want to trigger a build of a separate docker image repo that needs to pull in the build artifacts/binaries from the first build.
Up until the recent release of the api and docker build functionality this was a no go.  Now I'm really close.  What is missing is being able to run code before the docker build to pull in the artifacts. That would be sufficient but ideally there would be a way of fetching artifacts/binaries from the other build too.

**Comment by manishas** [comment]
@thephred thanks for the suggestion. We're working on some improvements to the workflow since we have similar feedback from other customers. I will let you know when it's available.

**Comment by manishas** [comment]
@thephred we announced our post CI dockerbuild feature last week and this should address your scenario. Check out the docs - http://docs.shippable.com/en/latest/docker_build.html#post-ci-docker-build - and blog - http://blog.shippable.com/post-ci-dockerbuild

**Comment by manishas** [comment]
Closing this issue. Please re-open if the blogs above don't help you get started.
