### ISSUE TITLE
save_reports fails when no code for coverage analysis 

### ISSUE THREAD

**Issue by nbucic** [Shippable/support#1155]
Right now our code is not well tested but we want to implement code coverage analysis for further bundles that we will create. When I put current Symfony bundles in phpunit.xml <whitelist><exclude> and make phpunit test localy, empty code coverage analysis is generated.
However, when I deploy to github and Shippable automatically runs build, script finally fails with error:

```
save_reports
  parse_coverage_reports
    Error parsing coverage reports.
```

This is what I get when I run phpunit locally with coverage-text:

```
Code Coverage Report:     
  2015-03-13 22:00:40     
                          
 Summary:                 
  Classes: 100.00% (14/14)
  Methods:        (0/0)   
  Lines:          (0/0)   
```

If I enable at least one of current bundles, script succeeds.

**Comment by manishas** [comment]
We parse test results if they're in junit format and code coverage if it's in cobertura format. More here -http://docs.shippable.com/en/latest/config.html#test-and-code-coverage-visualization
Did you follow all instructions there?

**Comment by nbucic** [comment]
@manishas thanks for reply.

I'm using code sample just like it's written here - http://docs.shippable.com/en/latest/samples/php.html.
Here is the exact line from shippable.yml file: phpunit -c app/ --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage

As I already mentioned, currently all code is excluded from code coverage analysis and I suppose that your parser looks in coverage xml for some lines which are not there and throws error on parsing it.
