### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by jiasilu** [Shippable/support#1156]
I got the "File name too long" error when running some of the tests. Those tests are calling geocoder for IP address and I'm using VCR for those rspec tests. 
![screen shot 2015-03-12 at 2 18 12 pm](https://cloud.githubusercontent.com/assets/1372178/6648102/0257aca2-c993-11e4-8139-59cf03b460f8.png)

**Comment by jiasilu** [comment]
@manishas Any feedback on this bug? We can't upgrade to the paid plan until it works for us. Hope you fix it asap. Thanks a lot.

**Comment by manishas** [comment]
@jiasilu can you point me to a build where this happens? And also share shippable.yml?

**Comment by jiasilu** [comment]
@manishas Send you an email with required info. Sorry about the delay.

**Comment by manishas** [comment]
thanks for the file. we're taking a look and will get back to you with an update soon.

**Comment by manishas** [comment]
closing this issue since it was followed up over email.
