### ISSUE TITLE
Can't merge client+server coverage report together

### ISSUE THREAD

**Issue by topikachu** [Shippable/support#1157]
I have a node project which uses mocha for server tests and karma+jasmine for client tests. Both create coverage report, with different file name, under shippable\codecoverage. It's OK if there's only a single coverage report. But if I create two reports together, shippable only displays the server one.

**Comment by antonienko** [comment]
+1, but in my case it's phpunit for server-side tests, and karma for client side.

**Comment by manishas** [comment]
consolidating all code coverage requests in #174
