### ISSUE TITLE
ignoring travis apt_packages

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1159]
With your docker support, I'm certain you have a much better way of doing this, but for the awesome "10 seconds to migrate from travis" claim, you might want to fix this.

My project uses the Travis-CI `sudo: false` with the `apt_packages` addon.

https://github.com/ensime/ensime-server/blob/master/.travis.yml

it would appear that you do not support this, otherwise this would have worked

https://app.shippable.com/builds/550458419b228b0d005bd68c

**Comment by manishas** [comment]
closing this since this is a stale issue. we do not claim 100% Travis compatibility.
