### ISSUE TITLE
An owner must login before you can enable this repo

### ISSUE THREAD

**Issue by djindjic** [Shippable/support#1161]
I have tried to add an private github repo into my shippable projects and get this error.
>An owner must login before you can enable this repo

I have also tried it with owner's github account of this private repo by singing up as new shippable user and have same issue.
This is same project migrated from bitbucket with same conditions (private not mine repo) and all was fine before it.

Thanks

**Comment by manishas** [comment]
@djindjic which repo did you try to enable? We only allow owners to enable projects, this change was made to the permissions model to align it more closely to GitHub's permissions.

**Comment by djindjic** [comment]
It's not my repo, I just have contributor privileges on this private repository of other github user. This was possible with bitbucket projects few days before we migrate to github.  btw, I have tried to enable it as owner's github authenticated user on shippable, and have same error shown.

**Comment by djindjic** [comment]
if it could help, I'm getting this errors logged in my console:

bad request error 400
>https://api.shippable.com/workflow/enableRepoBuild

and internal server error 500
>https://api.shippable.com/byoh/subscriptions/5505fe0c5ab6cc13529b4f4d/migrate

there is same issues no matter am I authenticate as me or repo owners's credentials.

**Comment by manishas** [comment]
Closing this issue. Please leave a comment if you're still blocked on this and we'll take a deeper look.
