### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by ttrahan** [Shippable/support#1162]
Error described by @fommill at https://github.com/ensime/ensime-server/issues/889

I'm trying to use  debian:jessie  but seeing this:

HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=jessie&fromImage=debian (Caused by <class 'socket.error'>: [Errno 111] Connection refused): Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=jessie&fromImage=debian (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

am I asking for the wrong image or is there something wrong with our dedicated host(s)?

**Comment by fommil** [comment]
btw, my dedicated nodes seem to be working if I use the default docker image (although it is rather large and took a long time to download).

**Comment by fommil** [comment]
ok, I figured it out! To download **anything** from docker.io you are requiring the credentials to be entered. Is that really necessary? I thought it was only needed for private docker images.

**Comment by fommil** [comment]
is there any way to see **which** node a job is running on?

**Comment by fommil** [comment]
hmm, it seemed to get only so far and then

```
Warning: Boot step is taking longer than expected
```

and it looks like you killed it... given how many packages were being installed I'm not surprised it was taking a while.

**Comment by manishas** [comment]
@fommil i'm asking someone to take a look at this. 

In the meantime, I see a notification for your project - 
![screen shot 2015-03-14 at 2 46 01 pm](https://cloud.githubusercontent.com/assets/2983749/6653689/e85c046c-ca58-11e4-901f-1425aceb8753.png)

Can you send me your shippable.yml? You can email it to me at manisha@shippable.com if you're not comfortable pasting it in a comment.

**Comment by manishas** [comment]
also, i see you're having different issues with the builds... probably depending on which host the build ran on.

**Comment by fommil** [comment]
@manishas thanks. Ignore the encrypted variables bit... that's the sonatype key/password. That's expected. Although, being able to mark all as read would be nice :wink: 

I think there are two issues here:

1. transient network problem (original report)
2. killing the start too soon. For a stock Debian Jessie image, you seem to have a lot to install.

I'm fine building on top of your stock image for now, but eventually I'd like to be using my own OS because it is relevant for Linux binary builds (libc version, etc).

**Comment by manishas** [comment]
@fommil minv2 is a big image and can cause out of space issues if the build hosts you added aren't big enough. You can also try starting with our language specific images - http://docs.shippable.com/en/latest/custom_images.html but these are barebones with just the OS and language versions and you'll need to install everything else through the yml. Dockerfiles for the language specific images are in the shippableImages repo on github. 

Let's set up a call next week to figure out why your custom image is failing. We can do any time between 10am-4pm PST but can also make other times work if you're in a different time zone. What times work for you?

**Comment by manishas** [comment]
I noticed you're in London. Can you do 5pm on Monday or 4pm on Tuesday London time?

**Comment by fommil** [comment]
@manishas I've not built a custom image yet, it's just the stock Debian Jessie one. I need to build a custom one locally before I can progress that. The only problem I can see here is that your timeout is kicking in and killing the job. I think I can probably work around that by creating a custom image with everything you expect to see on it.

Even the `minv2` image is failing on occasion on my dedicated box, I just don't know how to debug it. I'm happy to give a shippable engineer root access to the box if you think that would help? If so, send me your `id_rsa.pub` and then login as `root@fommil.com` when I set it up.

You've caught me during a particularly sociable week, so I think Monday evening (i.e. 8pm+ GMT) is the only time I can talk. I'm using Shippable for FOSS, not my day job. But I'm happy to continue using the issue tracker.

**Comment by fommil** [comment]
Any ideas when you can help out with this? You should be able to manually ssh into the box to debug, or you can give me another public key to use in ssh.

The shippable debugging logs are not telling me enough about what is going wrong for me to debug. I can't even see which script is failing. I'm assuming it's failing before you even start the docker image. Is there some extra requirement for the environment that you need which is not documented?

`shippable` user should definitely have network access, I just now logged in and started up an image.

**Comment by fommil** [comment]
Please close this ticket as I'm starting a new one, as there was a lot of noise before I worked out what the core problem was #1196

**Comment by manishas** [comment]
Closing...
