### ISSUE TITLE
result is not published to github when `script` stage finishes

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1165]
I have some big `after_success` jobs that are slow and trigger downstream behaviours (e.g. coverage reports from coveralls.io) but Shippable seems to be waiting for **everything** to finish before reporting success, especially back to github (e.g. updating a PR status or badge).

The correct behaviour should be that when the `script` stage finishes, the triggers to update github and badges should be fired.

**Comment by fommil** [comment]
I'm not so sure this is a feature request, it's definitely a regression against Travis CI.

BTW, out of all the tickets I have raised, this is the highest priority for me, as it results in CI times jumping from 20 minutes to 1 hour.

**Comment by manishas** [comment]
@fommil understood. it is tagged as a FR since we intentionally designed the platform to work this way. We had the previous design earlier, but customers complained that they got a build success notification but some steps still failed.

I'll follow up on this and escalate as a higher priority item.

**Comment by fommil** [comment]
ok thanks. There needs to be a way of successing/failing early. The complainers may actually have been incorrect, and should simply have added additional lines to their `script` stage.

**Comment by fommil** [comment]
@manishas any progress on this? It's in my top 2 priority tickets.

Semantically, I don't see what the difference between the stages is if you wait until "after_result" to publish results. Sounds to me like your users who requested this feature should simply move their "after_result" stage into "script".

**Comment by manishas** [comment]
this is an old request and we have changed yml format since then. closing.
