### ISSUE TITLE
`cache` not supported

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1166]
In Travis, I am able to have this section in my YML:

```
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
```

but it is ignored by Shippable.

Having the ability to cache dependencies is absolutely essential for the stability of Java and Scala projects, because the time to populate these directories from Maven central is quite high and it is prone to errors.

Travis waits until the entire build has finished before checking if the cache needs to be updated. I would recommend that actually the correct time to do the caching is after the `install` stage. Results from the `script` really shouldn't influence the cache, IMHO.

**Comment by fommil** [comment]
btw, this is a different cache than the container cache http://blog.shippable.com/faster-builds-with-cached-containers

However, if I can get custom docker images working I should be able to create an image that captures everything of relevance for the cache.

**Comment by naveensky** [comment]
@fommil - were you able to use existing cache to cache your sbt dependencies. I am facing similar issue in my sbt project and though I have cache flag in my shippable, it doenst seem to work

**Comment by fommil** [comment]
I've decided not to use their caches at all. Since I can build custom docker images, I am going to build a "clean" image and a "cached" image with all deps automatically using docker hub.

**Comment by naveensky** [comment]
@fommil - I couldnt find a way to use custom docker images unless using dedicated host? Isn't that correct, else I will go ahead and build my own docker image as well.

**Comment by fommil** [comment]
I'm using dedicated hosts.

**Comment by manishas** [comment]
We do not support caching in the same way that Travis does. Our suggestion is to use custom docker images for builds.

You can now use custom images without dedicated hosts :)
