### ISSUE TITLE
Scala docker images using bad version of sbt

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1167]
The sbt `.deb` files on bintray are absolute rubbish and no Scala devs actually use them, unfortunately they are what you're using in your scala images: http://docs.shippable.com/en/latest/custom_images.html#scala

All Scala developers that I know use this script instead of a `.deb` https://github.com/paulp/sbt-extras/blob/master/sbt You'll have a whole world of pain if you don't use this script. I've never understood why the the `sbt` developers don't just ship this script.

Also, you need to update your docs to say that `sbt` should be called with `sbt ++$TRAVIS_SCALA_VERSION` (or whatever your equivalent is) in order to ensure that the `scala.version` parameter is taken into account.

**Comment by fommil** [comment]
Indeed, my tests fail because this version of `sbt` is so non-standard https://app.shippable.com/builds/5504cdac9b228b0d005bdeb5

Workaround is to bundle my own version of `sbt` with the repo until I can build a custom docker image.

**Comment by manishas** [comment]
We have updated our scala images, so closing. Please re-open if you run into any problems with this.
