### ISSUE TITLE
jdk flag is ignored

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1169]
I changed our builds to use the Ubuntu 14.04 (instead of 12.02) docker images, but now it's clear that the config entry

```
jdk:
  - openjdk6
```

is being ignored because our tests always fail on these two unit tests if the java sources are not installed, and I only installed `openjdk-6-source` https://app.shippable.com/builds/5504c2e29b228b0d005bde28

I can only presume that `JAVA_HOME`, `JDK_HOME` and all the various `java` binaries are not pointing at my selected java.

Workaround is to manually type something like this in `install`, which is what the `jdk` entry should be doing behind the scenes.

```
sudo update-java-alternatives -s java-1.6.0-openjdk-amd64 &&
export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::") &&
export JDK_HOME=$(readlink -f /usr/bin/javac | sed "s:bin/javac::")
```

**Comment by fommil** [comment]
Note the documentation here http://docs.shippable.com/en/latest/custom_images.html#java is wrong wrong wrong! This only updates the `java` binary, not the tooling (including the java compiler!) that is part of the specified JDK. (It's also not compatible with how Travis Java projects work)

**Comment by manishas** [comment]
This should not happen after our build system upgrade. closing.
