### ISSUE TITLE
build_image ignored

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1170]
I added

```
build_image: shippableimages/ubuntu1404_scala
```

to our `shippable.yml`, but it was ignored.

I managed to get it working, but only by changing the docker image in the project's "Settings" page.

I suspect the same is also true for the other settings in here.

**Comment by voanhduy1512** [comment]
I have the same issue too. `build_image: shippableimages/ubuntu1404_base` and it still use `minv2`

**Comment by mikehancock** [comment]
+1 on this - would be nice if you could use both project settings in the website in conjunction with yml, where the yml file takes precendence over those in the website

**Comment by manishas** [comment]
@fommil @voanhduy1512 @mikehancock we are working to improve the experience around this.

Currently, the UI project settings override the yml settings. So if you include build_image in the yml and project settings say something else, then the settings win. 

Please let me know if that is not happening.

**Comment by manishas** [comment]
Closing this issue since the system is working as designed. We will improve the experience around this scenario soon.

**Comment by n0mer** [comment]
@manishas is this 'soon' already arrived? :)
