### ISSUE TITLE
failure in after_success should not influence the results

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1172]
related somewhat to #1165 I just had a build fail because of a failure in `after_success` https://app.shippable.com/builds/5504edc19b228b0d005bdfbe

This shouldn't happen: the build has succeeded at this point and failures in `after_success` should be ignored (perhaps a notification?)

**Comment by fommil** [comment]
FYI http://docs.travis-ci.com/user/build-lifecycle/#Breaking-the-Build

```
before_install
install
before_script
script
after_success or after_failure
after_script


If any of the commands in the first four stages above returns a non-zero exit code, Travis CI considers the build to be broken.

When any of the steps in the before_install, install or before_script stages fails with a non-zero exit code, the build will be marked as errored.
```

**Comment by manishas** [comment]
@fommil thanks for all the issues you opened today! I'm going to take them all to the team and we'll fix them one by one. I'll keep you updated on where we are as we go through them.

**Comment by fommil** [comment]
@manishas thanks! I still prefer it to Travis :smile: at least all these problems have workarounds, and most of these niggles will have easy fixes.

**Comment by manishas** [comment]
From travis docs - 
Currently, neither the after_success nor after_failure have any influence on the build result. We have plans to change this behaviour.

We will revisit our design, but don't want to introduce too many 'statuses' but I do see that differentiating between build failure and failure in after_success is great to have. 

Will keep you posted.

**Comment by manishas** [comment]
this is an old issue and our build system was revamped after this. closing.
