### ISSUE TITLE
RFE: exit build with message to appear on github, etc

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1173]
It would be really great if scripts could be written with some extra information that would appear in PRs if they fail, e.g. instead of the current

```bash
  - sbt ++$SCALA_VERSION clean test:compile it:compile doc &&
    sbt ++$SCALA_VERSION test it:test &&
    sbt ++$SCALA_VERSION publishLocal &&
    ensime-emacs/test/run_emacs_tests.sh &&
```

imagine if we could write

```bash
  - sbt ++$SCALA_VERSION clean test:compile it:compile doc || failed "compilation"
  - sbt ++$SCALA_VERSION test it:test || failed "tests"
  - sbt ++$SCALA_VERSION publishLocal &&
    ensime-emacs/test/run_emacs_tests.sh || failed "integration tests"
```

it would be even better if the PR comment included a link to the relevant part of the log.

Under Travis rules, if a line fails the others will still be evaluated. I'd like a way of just exiting immediately with the message. Anything that speeds up the cycle is good.

**Comment by manishas** [comment]
This isn't on the near term roadmap, so closing as deferred.
