### ISSUE TITLE
Shippable Image for Typesafe Activator pre-insatalled

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1174]
Hi, 

Do we have any shippable image which has scala + typesafe activator pre-installed? I currently have a build that uses it and build spends about 8 mins just to get required dependencies. 

This is not a road blocker, but if we have an image handy, I would like to reduce my build time.

Thanks,
Naveen

**Comment by manishas** [comment]
@naveensky not at the moment. However, we're going to refresh all our language specific images in the next couple of weeks and I'll make sure this gets in if it's a popular platform.

**Comment by manishas** [comment]
@naveensky can you use caching to reduce time? I know you said caching isn;t working for you, but you might be running into the same problem as https://github.com/Shippable/support/issues/1125#issuecomment-77493561

You should do a commit with [reset_minion] so that the existing cache is cleared and then start again.

**Comment by naveensky** [comment]
@manishas - Thanks for the tip, let me try once with [reset_minion] command to check if that reduces build time

**Comment by naveensky** [comment]
@manishas - this doesnt work for me. Somehow my SBT dependencies are not getting cached or my image is not getting cached. 

Can you check if I am doing cache clean correctly ?

**Comment by naveensky** [comment]
@manishas - I just checked and it looks caching is working good now :+1: 

I am closing this, thanks for the useful tip. 

I would still persist for play framework native image :)
