### ISSUE TITLE
PUBLIC API's

### ISSUE THREAD

**Issue by velo** [Shippable/support#1177]
Hi,

I wanna use public api to connect/disconnect.

I can create nodes just fine, but seems the initialize api is changing from time to time.
It was 
POST https://api.shippable.com/nodes/$NODE_ID/initialize
Now it is
POST https://api.shippable.com/workflow/initializeNode 

Is there any documentation on public api?

**Comment by velo** [comment]
@luizm

**Comment by manishas** [comment]
we're building the docs as we speak. goal is to get everything done by EOW.

**Comment by velo** [comment]
Nice, any news for me?

**Comment by manishas** [comment]
most APIs are documented -  http://docs.shippable.com/en/latest/api.html

**Comment by manishas** [comment]
closing this issue. please re-open if you want a specific scenario that is not addressed.
