### ISSUE TITLE
Setting user for custom image

### ISSUE THREAD

**Issue by thephred** [Shippable/support#1179]
I am trying to run a custom docker build image via a dedicated host.  It has a user setup in it for the build and I would like shippable to launch the build with that user similar to how minv2 runs as shippable.  However, it only runs as root.  There was a reference in another ticker to the fact that you could set the user in the shippable.yml but I couldn't find how to do this in the docs and guessing how to do it has failed.  Any clue on this?

**Comment by thephred** [comment]
Any update on this question?

**Comment by thephred** [comment]
We are blocked on this so a response would be great.

**Comment by manishas** [comment]
This is not a recommended approach and even we have moved away from it in our new build images.

Closing this issue but if you still need this, would be happy to look at your scenario and suggest alternatives.
