### ISSUE TITLE
How to copy build output to cloud storage

### ISSUE THREAD

**Issue by affmobapp** [Shippable/support#1181]
How to copy build output to cloud storage like DropBox or google drive

**Comment by manishas** [comment]
@affmobapp sorry for the delay... we recently announced a public API and we're in the middle of documenting it. Once the relevant portions are documented, I'll update you on how to do this.

**Comment by manishas** [comment]
Instructions for copying build artifacts are here - http://docs.shippable.com/ci_configure/#build-artifacts

You can adapt this to push to another cloud storage.
