### ISSUE TITLE
Builds hang at "Waiting for build information..." for one branch in a github repo while working for other branches

### ISSUE THREAD

**Issue by vkuusk** [Shippable/support#1182]
we have a project for a repo in github and shippable was triggered by commits to any branch.
Starting today commits to one particular branch stopped triggering test runs.
(Let me know if you need the names of project and branch in it.)

I can rerun previous builds for this branch many times, 
but manual scheduling of a new build (sync project then build) hangs in "Waiting for build information..."
- and canceling produces error:  "The requested resource was not found"
--- Manual triggering for other branches works.
-----------------------
I do not see any differences between status of branches on github.

Is this something we can fix on our side 
or this is a bug in shippable?

Thx

**Comment by vkuusk** [comment]
Resolved: based on #1110 
---- It was a syntax error in  shippable.yml file

And I agree that it would be nice to have (an error message) or (just fail the build) or (redirecting from the page with "waiting for the build information"). otherwise it's somewhat confusing.

Thanks

**Comment by manishas** [comment]
We're improving UX for this scenario. 

Closing this issue since this isn't a bug.
