### ISSUE TITLE
Bump maven version

### ISSUE THREAD

**Issue by velo** [Shippable/support#1191]
Currently shippable is using  maven 3.2.1.

This version has some bugs to run parallel builds [MNG-5750](http://jira.codehaus.org/browse/MNG-5750) and to download artifacts [MNG-5723](http://jira.codehaus.org/browse/MNG-5723)

I will build a custom image for my project, but would be way better keep using shippable default image!

Thanks!

**Comment by caarlos0** [comment]
+1

I had to build a custom image, but then commands like `services` and `jdk` stopped working... so I put it in `before_install` section... which bump my build time in ~20s.

https://github.com/caarlos0/shipable-minv2-maven32

**Comment by manishas** [comment]
We now have v3.2.5 in our build containers. closing.
