### ISSUE TITLE
Builds Failing with Certificate Expired

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1192]
Get https://index.docker.io/v1/repositories/shippableimages/ubuntu1204_nodejs/images: x509: certificate has expired or is not yet valid: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
Exception: Get https://index.docker.io/v1/repositories/shippableimages/ubuntu1204_nodejs/images: x509: certificate has expired or is not yet valid

**Comment by chriskinsman** [comment]
Looks like the certificate on https://index.docker.io expired...

**Comment by manishas** [comment]
Yes we're escalating this with them.

**Comment by manishas** [comment]
It affects everyone so should be fixed quickly, hopefully.

**Comment by chriskinsman** [comment]
Not so much I guess...

**Comment by chriskinsman** [comment]
Back up

**Comment by manishas** [comment]
thanks! 

time to explore all avenues :-|
