### ISSUE TITLE
Build failing due to - No docker credentials provided

### ISSUE THREAD

**Issue by affmobapp** [Shippable/support#1193]
My build failed due to folllowing error
No docker credentials provided: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
Exception: No docker credentials provided

Build URL - https://app.shippable.com/builds/550d3bfd21d6a90b00366c5b

**Comment by manishas** [comment]
@affmobapp I see all your builds after that passed.... docker hub had some issues over the weekend and  I suspect your build was being processed at that time.

I am closing this issue but please re-open if you run into this again.
