### ISSUE TITLE
no shippable.yml/.travil.yml creates error

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1194]
If I don't have a YML file in a branch, then I don't want it to be built, so I'd rather not receive notifications about missing YML files.

**Comment by manishas** [comment]
This is a design decision we made and it's really a matter of what works for folks. When we failed silently, we got a lot of customer complaints about us not showing a notification or sending them an email notifying them. We chose to show non intrusive notifications to solve this problem.

We will certainly revisit if we get this feedback more frequently, but for now, I will close this. Thanks!!
