### ISSUE TITLE
share dedicated host across accounts

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1195]
I have two paid accounts with you: `fommil` and `ensime`. I would like to use the same dedicated host for both, but it is not clear if this is supported. If you took `username` as a parameter to the dedicated host, then we could set up multiple shippable node accounts on some of the beefier machines that I have in mind (alternatively, recognise when a node is up across accounts, so there is no need to do the initialisation/launcher again).

**Comment by manishas** [comment]
Great feature suggestion... we're thinking along the same lines :)

**Comment by fommil** [comment]
Do you have an ETA for this? I can see you labelling for bug/feature/question but your triage stage is not assigning priorities or timelines/milestones/sprints to anything, so it's hard to tell if I should be putting more effort into workarounds.

I've raised a lot of tickets on this tracker, most of them I can work around, but this ticket, followed by #1173 are by far the biggest problems I'm facing and workarounds would really take up a lot of my time.

Without the ability to share my machines across accounts, I'm effectively burning through cash on the various VPS machines that I'm paying for, and I have to choose github accounts to sacrifice. The only workaround I can see is to move all my projects into one group, which is effectively impossible because I'm not the sole owner of those groups.

I'd be happy with a hack that basically allows me to short-cut adding a node... e.g. an option to "add a dedicated node that is managed by another account". That gets me up and running.

**Comment by fommil** [comment]
@manishas this one is killing me... do you have anything to report on this.

Honestly, if this one isn't on your roadmap I'm going to have to look into setting up Jenkins to manage my OSS builds because it would be a lot cheaper for me to pay somebody to set that up than to have to pay for 2 dedicated hosts per github account.

**Comment by manishas** [comment]
@fommil I do have an update on this but I cannot make a public comment. I will send you an email in the next few hours.

**Comment by manishas** [comment]
Closing this issue. We'll reopen if we get more +1s from customers.
