### ISSUE TITLE
connection error on dedicated node

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1196]
I have two dedicated nodes: both successfully deployed, but one is working and the other is not. Both are hosted by the same provider, but are running different flavours of Linux: the succeeding one is running Ubuntu, the failing one is running Debian.

This is an example of a failure https://app.shippable.com/builds/550d5d8f21d6a90b00366cf4 which is using the normal shippable docker image. It also fails for custom images.

```
 Docker login
Warning: Docker login failed for user fommil with error HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/auth (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
 Docker pull shippable/minv2:latest
HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=latest&fromImage=shippable%2Fminv2 (Caused by <class 'socket.error'>: [Errno 111] Connection refused): Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=latest&fromImage=shippable%2Fminv2 (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
```

If I manually log in to the box as the `shippable` user, I am able to issue this command

```
docker pull shippable/minv2 
```

which works (although, notably, it had to download everything first).

It would help me greatly if you could let me see the script that is running and failing... there is probably some missing unix utility or a python/shell version mismatch.

**Comment by fommil** [comment]
w00t! Got it. You are assuming that the host is running the docker API on port 4243. This is definitely not a universal assumption. The workaround is to enable the service on localhost, e.g. in debian this means adding to `/etc/default/docker` the following

```
DOCKER_OPTS='-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock'
```

However, I would **strongly** recommend that you only use the unix socks mechanism (docker default), because a) it is a lot more secure and b) you already require unix socks support when initialising the node.

**Comment by fommil** [comment]
reopening to get your opinion on the above comment.

**Comment by manishas** [comment]
@fommil We'll look into this... tagging feature request.

**Comment by manishas** [comment]
this has been redone for the new release. closing this issue.
