### ISSUE TITLE
TypeError: on_connection_closed() takes exactly 2 arguments (4 given)

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1197]
While debugging another issue, I found a lot of these errors in the shippable logs:

```
TypeError: on_connection_closed() takes exactly 2 arguments (4 given)
WARNING:pika.connection:Disconnected from RabbitMQ at msg.shippable.com:5671 (0): Not specified
```

You might want to look at http://stackoverflow.com/questions/19255014 to help with this.

**Comment by manishas** [comment]
This has been redone with the new build platform. closing this issue since it is no longer relevant.
