### ISSUE TITLE
support coveralls.io in pull requests

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1198]
to get coveralls.io support in pull requests, I need to put my `COVERALLS_REPO_TOKEN` in the `shippable.yml` file. I think it is correct that the encrypted vars should not be visible in pull requests, but it would also be good if some transient thing were made available to work with coveralls.io. Travis is able to do this by using their `TRAVIS_JOB_ID` but I think they have buy-in from `coveralls.io` to do this.

**Comment by manishas** [comment]
you're right... until we have an official integration with coveralls, i don't know if we can do what Travis does.

**Comment by manishas** [comment]
all coverage requests consolidated in https://github.com/Shippable/support/issues/174

Closing.
