### ISSUE TITLE
cancelling a job does not stop it on the node

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1199]
On my dedicated nodes, if I start up a bunch of jobs and then cancel them, I can still see them running to completion on the nodes, eating up CPU cycles and precious resources.

**Comment by manishas** [comment]
yes, we're aware of this bug. I'll keep you updated when we make some progress.

**Comment by rogierslag** [comment]
Also encountering this bug. Very annoying, especially when someone just pushed, found a comment type, amends the commit and force pushes

**Comment by manishas** [comment]
this has been fixed in our Single Tenant CI plan which has replaced dedicated hosts.

**Comment by manishas** [comment]
Actually, no. We're working on this in our next phase of build fixes.

**Comment by manishas** [comment]
This is fixed with our new release that was deployed today. Everyone will be migrated in the next 24-48  hours so you shouldn't see this after that.
