### ISSUE TITLE
Docker container size is much larger compared to locally build image

### ISSUE THREAD

**Issue by mavarazy** [Shippable/support#1202]
I've created very simple project, to test Google Container Engine with Spring Boot application
https://github.com/clemble/badge

For some reason docker image size exceeds 13 G, and I can't start it (running out of space)
When I build same project locally it's size is 438M

Why is the difference?

**Comment by rageshkrishna** [comment]
@mavarazy It looks like you haven't enabled the Docker Build feature on your project. By default, the build runs on our shippable/minv2 image which contains dependencies for all the build platforms we support.

You can take a look at this blog post which walks you through setting up Docker Builds for your project: http://blog.shippable.com/making-deployments-even-easier-with-docker-build

**Comment by mavarazy** [comment]
What is commit_container for, and what is the difference between custom image & commit_container?
Did I understand right, that now I need to have separate Docker image with all construction tools & services (like Maven, RabbitMQ, MongoDB ...) and shippable.yml in this case does not play any role?
Shippable becomes just a trigger to run my jobs.

For me it was intuitive that after I added Dockerfile, shippable would publish my updated image on successful build?
Is it planned to implement it any future?

**Comment by rageshkrishna** [comment]
So we've got three different things going on:

1. `build_image` in your YML file allows you to use an existing image from Docker Registry to run your build.
2. `commit_container` in your YML file lets you push the container that ran the build back to the Docker Registry.
3. Docker Build, which is a new feature that we announced recently, will build an image from a Dockerfile in your repository and then run your build in that container

However, what I understand from your last comment is that you want to run the build inside our default shippable/minv2 container and, if the build succeeds, you would like to build an image using your Dockerfile and push it to the registry. If my understanding is correct, we already have a feature request open for this here: https://github.com/Shippable/support/issues/1150

You may want to subscribe to that issue for updates on this feature.

Please let me know if this answers your question.

**Comment by mavarazy** [comment]
Thanks I'll close it since #1150 fits my idea
