### ISSUE TITLE
No coverage reports parsed - Codeception

### ISSUE THREAD

**Issue by Ben-Speakman** [Shippable/support#1203]
I have the following output in the results page of my build:
```
cp -v tests/_output/coverage.xml shippable/codecoverage/
    `tests/_output/coverage.xml' -> `shippable/codecoverage/coverage.xml'
```

But then at the end:

```
parse_coverage_reports
    No coverage reports parsed.
```

I am using the [CodeCoverage](http://codeception.com/docs/11-Codecoverage) output from codeception. Am I doing anything wrong?
The build is failing but shouldn't it show the coverage anyway?

**Comment by manishas** [comment]
@Ben-Speakman we need the output to be in cobertura formar for us to parse it.

**Comment by Ben-Speakman** [comment]
It seems Codeception uses the Clover format. Can I request you guys look into supporting this format?

**Comment by manishas** [comment]
I will add this to the list of code coverage related feature requests. Closing as dup of https://github.com/Shippable/support/issues/174
