### ISSUE TITLE
Triggered build on bitbucket branch never starts

### ISSUE THREAD

**Issue by bbradbury** [Shippable/support#1205]
I manually triggered a build for a private bitbucket project by pressing the "play" button on the shippable ui and selecting a branch, but the build never starts. I instead get a "Waiting for build information" spinner. The last try I made was for https://app.shippable.com/builds/551087b621d6a90b00368a0c (a private build, so not sure how useful that is).

**Comment by bbradbury** [comment]
The button works for the main branch, just not for the development branch I had selected.

**Comment by manishas** [comment]
@bbradbury whats your bitbucket username? Can you check if the Notifications tab on your repo page on Shippable shows any errors? This usually happens if the yml is missing or has a problem.

**Comment by bbradbury** [comment]
I'm bbradbury on bitbucket: https://bitbucket.org/bbradbury

The branch name had a slash in it (e.g. feature/new_feature_name) maybe that causes a problem on the UI only? Works fine when committing.

**Comment by bbradbury** [comment]
Also no notifications about it.

**Comment by manishas** [comment]
@bbradbury I do see notifications about a missing yml... https://app.shippable.com/projects/550a25835ab6cc1352a49184 and click on 'Unread notifications'

Do you have a yml in the branch?

**Comment by manishas** [comment]
but if it worked fine while committing then that's not it... can you confirm that the project above is the one for which you're running into this?

**Comment by bbradbury** [comment]
No, different project: https://app.shippable.com/projects/54bf12795ab6cc1352893cab When trying to manually trigger a job on the same branch as job 181.

**Comment by manishas** [comment]
is this still an issue? sorry for the late follow up.

**Comment by bbradbury** [comment]
Yes -- still happens when manually triggering a build for a branch with a / and an _ in the name.

**Comment by manishas** [comment]
we'll take a look at this tomorrow and get back to you with an update. Thanks for your patience!

**Comment by bbradbury** [comment]
Thanks manisha! 

Brent Bradbury

**Comment by manishas** [comment]
@bbradbury we looked into this and this is a bitbucket API issue. We had opened up a bug - https://bitbucket.org/site/master/issue/9969/get-commit-revision-api-does-not-accept - a year ago but they haven't done much to fix it. We'll bug them again.

There is nothing actionable for us to do at this point :(

**Comment by manishas** [comment]
Closing this issue since there is no way for us to handle it. We will continue tracking this with bitbucket.

**Comment by belak** [comment]
This is actually possible to fix, but it involves an additional API request.

https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/refs/branches/%7Bname%7D

This endpoint will allow you to get the hash for any branch, even if it contains a slash. That hash can then be plugged into the commit revision API.
