### ISSUE TITLE
project summary shouldn't show PRs

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1206]
We have some PRs with builds that time out (this may change when you look at it)

  https://app.shippable.com/subscriptions/5504572d5ab6cc13529ad105

and, although our master builds are all green, our summary page is showing up red.

IMHO, it would be more intuitive if the project summary page had the status for each of the branches on the main repos, not including PRs.

**Comment by manishas** [comment]
Thanks for this feedback!

UI has been redesigned and this is addressed with the new design. Closing.
