### ISSUE TITLE
allow user parameters to the `docker run` command (not just privileged/unprivileged)

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1207]
You already give the option to run in privileged mode, but that's a massive security hole. I'd like to run one of my custom images with support for `virtualbox`, and this requires providing just one device mapping, e.g.

```
docker run -i -t --device=/dev/vboxdrv fommil/freeslick:base
```

do you think you could allow us to pass parameters to the `docker run` command? (obviously, only for dedicated nodes)

**Comment by fommil** [comment]
Workaround, place this in `/usr/local/bin/docker` with chmod 755:

```
#!/bin/bash                                                                                                                                                                  

if [ "$1" = "run" ] ; then
  exec /usr/bin/docker run --device=/dev/vboxdrv ${*:2}
else
  exec /usr/bin/docker $*
fi
```

In fact, I need this not just for security but because my container fails to run in a privileged environment (it's doing funky networking stuff that needs to be isolated)

**Comment by fommil** [comment]
damn, you're not using this launch script. I'm going to have to hack `/usr/bin/docker` for this...

**Comment by fommil** [comment]
still not working. You're launching docker in a really weird way.

**Comment by fommil** [comment]
you're not launching docker within docker, are you? That's... weird.

**Comment by fommil** [comment]
yup, you're mounting docker inside docker and then running docker. This is going to make it tricky to workaround.

**Comment by manishas** [comment]
@fommil are you looking for a follow up?

we do not provide a way to customize the docker run comment today.

**Comment by fommil** [comment]
@manishas no need, I've moved on to drone thanks.

**Comment by avinci** [comment]
#3402 has a solution for this scenario for anyone coming to this support issues by searching for mounts.
