### ISSUE TITLE
Rebuild all open pull requests on push to destination branch

### ISSUE THREAD

**Issue by sigvef** [Shippable/support#1208]
Hi,

Is it possible to rebuild all open pull requests on push to the destination branch? By this I mean that when a  branch (say, `master`) is updated, all open pull requests into that branch are rebuilt.

Thanks!

**Comment by manishas** [comment]
This is a great requirement and is now possible with new build platform. Marking implement.

This should be implemented as a setting in the yml.

**Comment by filipegiusti** [comment]
@manishas is this in the queue or was deprioritized?

**Comment by avinci** [comment]
this will be implemented in next weeks release

**Comment by avinci** [comment]
We have implemented most of this feature. We have not enabled this as it might lead to a very nasty problem for some of the large projects where many PRs are open and turning this on will flood the system. If you still need it maybe, we could implement an additional check like build the most recent 10 PRs etc. and this can be set to 0 which means its off. I am closing this as no one else has asked for this. in future, if anyone needs this, please reopen and we can implement this in a week.
