### ISSUE TITLE
npm ERR EEXIST

### ISSUE THREAD

**Issue by ivanoats** [Shippable/support#1211]
I'm not sure why I'm getting this npm error below:

```
npm ERR! EEXIST, open '/home/shippable/.npm/1fccc280-ble-npm-big-js-2-5-1-package-tgz.lock'
File exists: /home/shippable/.npm/1fccc280-ble-npm-big-js-2-5-1-package-tgz.lock
Move it away, and try again. 
```

It seems to happen randomly. Is there a work-around to get a more consistent npm install process?

https://app.shippable.com/builds/5511db565b59870c00c0d6fc

Thanks :smile:

**Comment by manishas** [comment]
we'l look into this and get back to you.

**Comment by lekhab** [comment]
@ivanoats: this seems to be a known npm issue. the thread below outlines a solution as well. Could you please try that?

http://stackoverflow.com/questions/26316933/getting-error-while-scaffolding-angular-app

**Comment by manishas** [comment]
There is a workaround in this thread -
https://github.com/Shippable/support/issues/713

Update your YML file to include the following:
````
before_install:
  - npm install -g npm@next
````

Let me know if this works!

**Comment by manishas** [comment]
Closing. @ivanoats please let us know if the solution above worked for you.
