### ISSUE TITLE
laravel 5 behat 3 Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by damianbatson** [Shippable/support#1212]
hi shippable team

is it possible to increase the xdebug nesting level to 500?
to fix this locally i can add xdebug.max_nesting_level = 500 to my php.ini script in wamp.

can i add something like this to a script in testing?

thanks

**Comment by bbrala** [comment]
Try this, we needed this for Laravel with codeception. 

- echo "xdebug.max_nesting_level = 200" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
