### ISSUE TITLE
Send notifications to last committer as well as custom emails

### ISSUE THREAD

**Issue by smaiyaki** [Shippable/support#1213]
In the current configurations, shippable sends notifications by default to the last committer and we can override this configuration by adding some recipients email in the notification tag. It will be nice if we can keep this default behavior and at same time add some custom recipients.

The common use case is that as a build engineer, I want to get notified of build failures so that we can check if this is an infrastructural issues or changes to build flow

**Comment by manishas** [comment]
good suggestion. i will follow up on this.

**Comment by smaiyaki** [comment]
Thank you

**Comment by manishas** [comment]
Dup of #901.
