### ISSUE TITLE
Access problem

### ISSUE THREAD

**Issue by brankastanic** [Shippable/support#1215]
I have a problem. I can't access to project https://app.shippable.com/projects/540e7b1d3479c5ea8f9ebcdc, althought I have access to repo on github. My github username is branka.stanic@boutsourcing.com.

**Comment by manishas** [comment]
@brankastanic you need to enable access to private repositories in order to see the project on Shippable.  To do this, click on 'Private repos off' at the top right of your dashboard and go through the flow. Once you're done, return to shippable and sync your account and you'll see the repos.

Let me know if this works.

**Comment by brankastanic** [comment]
Thank you, It works now.

On Sun, Mar 29, 2015 at 6:27 AM, Manisha <notifications@github.com> wrote:

> @brankastanic <https://github.com/brankastanic> you need to enable access
> to private repositories in order to see the project on Shippable. To do
> this, click on 'Private repos off' at the top right of your dashboard and
> go through the flow. Once you're done, return to shippable and sync your
> account and you'll see the repos.
>
> Let me know if this works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1215#issuecomment-87355645>.
>



-- 

 Branka Stanic
PHP Developer
Evolution Team

[image: Displaying LogoBosMail.png]

Business Outsourcing Services d.o.o.
Španskih boraca 3, 11070 Belgrade, Serbia
mobile: +381 60 522 5491
email: branka.stanic@boutsourcing.com
web: www.boutsourcing.com


<http://www.boutsourcing.com>

**Comment by manishas** [comment]
Thanks!  Closing this issue.
