### ISSUE TITLE
Permission denied when running psql

### ISSUE THREAD

**Issue by snowballhg** [Shippable/support#1216]
When trying to run `sudo -u postgres psql -U postgres CMD` we are getting the following error:
`could not change directory to "/root/workspace/src/bitbucket.com/snowballhg/projectname": Permission denied`.

We're using the ubuntu1404_python image.  These same commands work perfectly on a AWS Ubuntu 14.04 AMI or a vanilla ubuntu 14.04 installation.

As a last resort I tried modifying the working directory permissions to 777 during the before_install (see below), but that failed as well.

![image](https://cloud.githubusercontent.com/assets/2517127/6829334/140193fa-d2d0-11e4-8652-3e5867ce3e8b.png)

I'd like to let our installation script do the installation of services such as postgresql rather than have special commands in the .yml file to limit code duplication and variation in our installation scripts.

Any ideas would be appreciated.

### YML file

    language: python
    build_image: shippableimages/ubuntu1404_python
    python: "3.4"

    before_install:
     - chmod -R 777 .
     - ls -al .

    install:
     - ./install.py --install dev

**Comment by manishas** [comment]
@snowballhg is this still an issue? can you point me to a failed build?

**Comment by snowballhg** [comment]
Yes, this is still an issue.  It is preventing us from selecting shippable
as our CI system.  I'm not sure how to point you to our build they are for
a private repository.  You can reproduce the issue simply be doing an
apt-get install of postgresql and then invoking the sudo -u command
mentioned in the bug report.  We invoke these from a shell script.

**Comment by manishas** [comment]
@snowballhg can you share your install script? If you're not comfortable pasting it here, you can send it to manisha@shippable.com

**Comment by snowballhg** [comment]
@manishas I've trimmed down the script to help reproduce the problem.

### install.sh
    #! /bin/bash
    sudo apt-get update
    echo "*** START POSTGRESQL"

    sudo apt-get --yes install postgresql
    sudo apt-get --yes install postgresql-contrib
    sudo apt-get --yes install postgresql-client
    
    service postgresql status
    service postgresql start
 
    sudo -u postgres psql --echo-all -U postgres -d postgres --command "create database prod;"
    sudo -u postgres psql --echo-all -U postgres -d postgres --command "alter user postgres with password 'foobar';"

    # restart postgresql service for changes to take effect
    sudo service postgresql restart

    echo "*** DONE"

### yml file
    language: python
    build_image: shippableimages/ubuntu1404_python
    python: "3.4"
    
    install:
     - ./install.sh

**Comment by manishas** [comment]
@snowballhg here is the response from our engineers -

We made a slight change in the postgres commands listed in the scripts:

**From** `sudo -u postgres psql --echo-all -U postgres -d postgres --command "create database prod;"`

**To** `sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"create database prod;\""`

The error `could not change directory to "/root/...` is thrown by psql when its called from a directory that it doesn't have access to.
The above command ensures that the pwd changes to the specified user's home.

We are not sure whether the customer's other environments (aws & vanilla instances) are running with the root user. That can be why they don't face any problems there.

Success build: https://appbeta.shippable.com/builds/551be9755dce0c0d00c3c9b8

Updated script:

```
sudo apt-get update
echo "*** START POSTGRESQL"

sudo apt-get --yes install postgresql
sudo apt-get --yes install postgresql-contrib
sudo apt-get --yes install postgresql-client

service postgresql status
service postgresql start

sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"create database prod;\""
sudo su - postgres -c "psql --echo-all -U postgres -d postgres --command \"alter user postgres with password 'foobar';\""

# restart postgresql service for changes to take effect
sudo service postgresql restart

echo "*** DONE"
```

**Comment by manishas** [comment]
please let me know if changing the script as shown fixes the issue. Thanks!

**Comment by snowballhg** [comment]
@manishas That fixes the issue thanks for the help!
