### ISSUE TITLE
Cannot find forked repo in repo list

### ISSUE THREAD

**Issue by fabioberger** [Shippable/support#1217]
Hi,

I recently forked a repo and wanted to deploy it through shippable but it is not showing up in the repo list. I have tried pressing "sync repo" multiple times to no avail.

I see other forked repo's in the list so I am assuming forks are also being displayed. 

Any ideas?

Thanks!

**Comment by manishas** [comment]
@fabioberger is this still a problem? is the forked repo public or private?

**Comment by fabioberger** [comment]
Hi Manishas, not a problem any more. Didn't know private repos required additional authentication and that you need to enable it in the settings.
