### ISSUE TITLE
dedicated node init needs blowfish-cbc

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1218]
Just a comment, your init script for dedicated nodes is using a non-standard sshd protocol (`blowfish-cbc`) which is no longer used by default on Debian Jessie.

To workaround, I needed to enable it by adding the following to my `/etc/ssh/sshd_config`

```
Ciphers blowfish-cbc,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
```

**Comment by manishas** [comment]
@fommil we do not officially support Debian, so I am going to close this issue as a dup of https://github.com/Shippable/support/issues/1091 since that is a feature request for Debian wheezy. I'll add a comment there saying we also need Debian Jessie.
