### ISSUE TITLE
Launcher does not succeed on Debian Jessie

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1219]
I upgraded by debian wheezy dedicated host from Debian Wheezy to Jessie as I need access to a recent version of `virtualbox` from my docker images.

However, after doing a fresh initialisation/launch of the shippable scripts, my node is no longer usable, failing with the following errors:

```
Command failed : cd /tmp && /tmp/ff6821fa-1bfd-4f81-a367-691a0160a979.sh Exception Script failure tag received
docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
Command completed
docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory
Command completed
Command failed : cd /tmp && /tmp/42f009ac-df8d-4e85-a820-4d87b3c5b5bb.sh Exception Script failure tag received
```

I can't even find these script files in my /tmp so I assume are part of some docker image that you're running within.

It looks like you're not setting up the correct LD_LIBRARY_PATH or something, because docker works fine from the CLI and the "missing library" is in fact available in /usr/lib/x86_64-linux-gnu/

Can I please ask that you look into this as a priority? I am unable to use my dedicated node to do any builds until this is fixed :cry: The machine is `fommil.com` and you should be able to log in using the shippable key and sudo to install anything that is missing .... or just to test out some dev scripts. I don't have anything of value on the server, it's just a worker.

**Comment by manishas** [comment]
we'll look into this as a high priority issue. thanks!

**Comment by fommil** [comment]
:smile:

**Comment by fommil** [comment]
I've noticed that you only officially support ubuntu, not debian. If you can't get this fixed in the next 24 hours or so, I'll look into swapping my OS (which will be a bit of a pain to be honest, so I'd rather get it working on Debian Jessie).

**Comment by manishas** [comment]
yes we officially support ubuntu as of now, but we'll try to take a look at this as soon as one of our engineers has a min and see if there's anything obvious we can do.

**Comment by fommil** [comment]
This is no longer a priority for me, as I reinstalled the OS on my VPS.

It would be good to support Jessie in the future. In particular, it is important to have virtualbox running the same version in the container as the kernel support on the host. Ubuntu stable tends to lag a bit, whereas Debian Jessie is much more up to date, so custom ppas are needed to handle this.

**Comment by manishas** [comment]
Dup of https://github.com/Shippable/support/issues/1091. Added comment saying Debian Jessie is a feature request.
