### ISSUE TITLE
Recent builds stuck on "waiting"

### ISSUE THREAD

**Issue by baihuqian** [Shippable/support#1220]
I'm using shippable for a Node project and it was always fine. However, most recent push gets stuck on "waiting", so I stopped the build and restart it manually, but it is no help. Could you have a look? Below is the link to the repo.
https://app.shippable.com/projects/54dceed25ab6cc13528bbf80

I recently refactored the testing code, but it runs fine locally, so not sure why it is stuck.

**Comment by manishas** [comment]
each org gets one build minion, so you can only run only build at a time. Right now, this build https://app.shippable.com/builds/55134f3f9461c40b00437ad9 is running, so others are waiting to start as previous builds finish.

Our startup plan comes with 5 minions for just $12/yr, so you can run upto 5 parallel builds.

**Comment by manishas** [comment]
maybe the build is stuck because of the tests being restructured?

**Comment by baihuqian** [comment]
There's no output to the console in waiting builds. I don't think it's because the tests are restructured. I tried running a successful build, and it stuck on start as the others. So now I cannot run any tests.

I think a build never finishes somewhere, which prevents me to run any other builds since I'm on the free tier.
