### ISSUE TITLE
[WISHLIST] docker push of build named with sha and don't use number of build

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#1221]
1) Matter:
I have a unique and global private project in docker hub named: dkrhub-user/dkrhub-project
I want to add all builds of all projects in dkrhub-user/dkrhub-project
I don't want to add a private project of docker hub for each github private project, because is hardest of administration and more cost of plan.

I change my travis.yml file to add
```yaml
commit_container: dkrhub-user/dkrhub-project
```
in github-team/github-project1

I change my other travis.yml file to add
```yaml
commit_container: dkrhub-user/dkrhub-project
```
in github-team/github-project2

Create a PR to github-team/github-project1 generate shippable build number # 1 and a saw a docker push dkrhub-user/dkrhub-project:1
Create a PR to github-team/github-project2 generate shippable build number # 1 and a saw a docker push dkrhub-user/dkrhub-project:1

2) I saw:
I have two docker push to same tag:
docker push dkrhub-user/dkrhub-project:1

3) I expected:
My problem is fix it if you use
docker push dkrhub-user/dkrhub-project:SHA
If you use sha version of git to docker push we can see each build by sha and we can have a unique docker project to push all my builds.

**Comment by manishas** [comment]
thanks for the suggestion! i'll tag this as a feature request.

**Comment by moylop260** [comment]
This feature is cool because I use my deployments from sha info.

**Comment by manishas** [comment]
@moylop you can now do this with our new tagging options -

![screen shot 2015-07-02 at 3 54 02 pm](https://cloud.githubusercontent.com/assets/2983749/8489648/d211d904-20d2-11e5-82c8-79d3bfd13754.png)
 
Just choose commitsha and you'll have your images tagged with it.

**Comment by moylop260** [comment]
I love you!
Thanks!
