### ISSUE TITLE
Is it possible to perform multiple builds per project?

### ISSUE THREAD

**Issue by yanivby** [Shippable/support#1222]
We have a project in which there are multiple languages:
1. Scala for the server-side (we use sbt for building JAR files)
2. Node.js in the client-side (we use grunt to build an AngularJS application. The grunt tasks basically does the script minification, CSS compilation from LESS, run client-side unit tests, etc.)
So the question is - what's the best practice with Shippable? How would the shippable.yml file look generally? (e.g., which 'language' should I choose?)

**Comment by manishas** [comment]
@yanivby couple of qs -
- is the server side and client side code in different repositories? If so, you'll have to enable both repositories and write a shippable.yml for each.

If it is just one repo you can choose node as the language and the scala part of your build will still work with our default container since it comes preinstalled with all popular languages and tools.

**Comment by manishas** [comment]
Actually, choosing scala as language should work as well, probably better. npm will work as usual since everything is preinstalled. Can you try that?

**Comment by yanivby** [comment]
Yes, this appears to be working with scala as the language. It didn't work
when node_js was the language, because it automatically attempted to do npm
install in the root direcoty, which doesn't have a package.json in my case
(in my case the node.js project is in a subdirectory).
So Shippable reports that the build succeeds and by looking at the console
output it looks like both the scala and the node.js builds succeeded.
However, I'm still a bit confused about how I get access to the actual
products of the build.
Is it possible to copy the artifacts to some remote machine? If not, what
is the "correct" way to deploy, assuming I don't use PaaS, but rather IaaS
(specifically, SoftLayer).
Thanks,
Yaniv

On Tue, Mar 31, 2015 at 8:58 PM, Manisha <notifications@github.com> wrote:

> Actually, choosing scala as language should work as well, probably better.
> npm will work as usual since everything is preinstalled. Can you try that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1222#issuecomment-88188694>.
>



-- 
Thanks,
Yaniv

**Comment by manishas** [comment]
@yanivby you will need to specify archive: true in your yml and the build artifacts will be available for download. We have a bunch of docs about deploying to various environments - http://docs.shippable.com/en/latest/continuous_deployment.html#continuous-deployment

We haven't specifically addressed SoftLayer but I'm hoping one of these will help?

**Comment by manishas** [comment]
Closing this issue. @yanivby please let us know if you need more help.
