### ISSUE TITLE
Global secure variable not repeated in matrix

### ISSUE THREAD

**Issue by marcogario** [Shippable/support#1223]
In our project we want to define some global secure variable that should be used by all configurations in the matrix. However, we also need to change some other information in the environment for some specific builds. 
[1] Is an example of our shippable.yml file. In line 55-56 we tried to repeat the secure variables, however this also does not work.

What would be the proper way of defining these variables in a global way?

Thanks

[1] https://github.com/pysmt/pysmt/blob/97d93b1df5fed5a52c8ecf46c7d1aac990a1e3a9/shippable.yml

**Comment by manishas** [comment]
@marcogario can you follow the instructions here - http://docs.shippable.com/en/latest/config.html#secure-environment-variables

Let me know if it works. Thanks!

**Comment by manishas** [comment]
@marcogario can you try out the suggestion above? Thanks!

**Comment by marcogario** [comment]
Thanks for the reply. I am not sure on how to apply the instructions you provide for the specific use case. Nevertheless, we worked around the issue by using the 'exclude' command. In this way all configurations have the secure variables by default (using the 'global' command) and we skip the builds for which this does not make sense.

For me it is ok to close this issue. Thanks for your time.

**Comment by manishas** [comment]
Thanks. I will close this issue but let me know if you ever need anything else.
