### ISSUE TITLE
failure in before_script reported as Boot failure

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1224]
I had a (genuine) failure in `before_script` in https://app.shippable.com/builds/5514419f86c05f0c006904e7 but it is showing up as a failure in Boot.

**Comment by manishas** [comment]
@fommil are you still seeing this particular issue? Sorry for some of the build problems last week, things should be smoother now.

**Comment by fommil** [comment]
We've not been using shippable particularly heavily but the few that we did run seemed to be ok, thanks. 

Do you have any timelines for the other tickets I reported when I started? I have two high priority tickets and I'd like to know if you're going to address new or if I should be investigating alternatives.

**Comment by manishas** [comment]
CLosing this issue since it shouldn't be happening any more.
