### ISSUE TITLE
Shippable stuck waiting for dedicated host

### ISSUE THREAD

**Issue by iislucas** [Shippable/support#1229]
Sometime today, our build on our dedicated host stopped happening. Shippable just gets stuck in an infinite waiting state.... 
![image](https://cloud.githubusercontent.com/assets/415450/6878039/0fa14834-d4ae-11e4-84bf-4210792d0e5c.png)

Our dedicated build host seems to be fine (I even re-set it up from scratch): 
![image](https://cloud.githubusercontent.com/assets/415450/6878037/0ab9015e-d4ae-11e4-932b-4e22828c9e8e.png)

Not sure how to debug or understand what is wrong... any ideas?

**Comment by manishas** [comment]
@iislucas I see some notifications for the org and also for the project. Can you please check and see if you can address the errors in the tab?

Additionally, it will help us figure out what's going on if you share your shippable.yml.

**Comment by iislucas** [comment]
The errors in the tab are all old ones before shippable stopped working; and there is one error for the time when I was recreating the dedicated build host. 

The shippable.yml files I tried can be found here: 
https://github.com/uProxy/uproxy-networking/blob/dev/.shippable.yml
https://github.com/uProxy/uproxy-networking/blob/dev-requireify/.shippable.yml

But unfortunately, I can't tell if the build host even got to the point of retrieving the yml files.

**Comment by manishas** [comment]
we're looking into this. I see an error in the notifications tab for uproxy-lib at 9:58am and all the stuck build seem to be after this time stamp... so my hunch is something went wrong at that time. I'll let you know as soon as we know more...

**Comment by ragsden** [comment]
I re-deployed dpd for the host and the builds started running.

**Comment by ragsden** [comment]
The build containers on host machine was not listening to the message queues and hence I had to restart the build containers by redeploying them. We will keep an eye on this to see if this happens again Sorry about the inconvenience.

**Comment by iislucas** [comment]
Thanks!

**Comment by iislucas** [comment]
Just had a look, but now it seems that the uProxy projects have all disappeared :/ Any ideas?

**Comment by lekhab** [comment]
@iislucas: apologies! we just rolled out a fix. can you please refresh or sync account on the shippable dashboard?

**Comment by iislucas** [comment]
looking good now, thanks!

**Comment by manishas** [comment]
Thanks for the confirmation! Closing this issue.
