### ISSUE TITLE
Invoice fiscal number

### ISSUE THREAD

**Issue by melo** [Shippable/support#1231]
Hey,

read through #704, not sure if downloadable invoices are already available, but I didn't find any place to update my billing information (company name, fiscal number, etc).

Do you have that?

**Comment by melo** [comment]
Hey, sorry, found the downloadable invoices :)

But still didn't find where I can put my billing data.

Thanks,

**Comment by manishas** [comment]
The only place we accept billing info is the 'Plans and billing' dialog. You can click on 'add card' to enter your card info and then choose an upgraded plan.

**Comment by melo** [comment]
Yes, that is the *card info*, but there aren't any fields for Company or Address...

**Comment by manishas** [comment]
we use a third party payment processing gateway and it does not require us to ask for this information. Is there a reason why you want to add all these to your shippable account?

**Comment by melo** [comment]
Hi,

Fields that would be useful:

* Company name;
* Company address;
* Company fiscal number (important in EU);

The last one is the important one for us.

Thank you,
