### ISSUE TITLE
don't require sudo

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1233]
Longer term, you should be looking at dedicated host installations that **do not** require `sudo` permissions.

Given that you only:

* install python packages into your home directory
* launch docker

there is no reason for you to `sudo`, if I have given you access to run docker. I realise this means that you would not be able to run docker in privileged mode, but I'm very happy with that.

**Comment by manishas** [comment]
we have completely revamped dedicated hosts and we don't even need SSH access to your nodes at this point. Closing.
