### ISSUE TITLE
Support docker and docker-compose

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#1234]
Our webapp will be based on docker containers and using docker-compose for orchestration. This means you need to make both docker and docker-compose available within your docker containers.
Can this be supported?

**Comment by manishas** [comment]
we're working on a solution to allow multi container environments. Let me know if you want to join our beta program and we can share more details.

I'll follow up on the docker compose qs and get back to you...

**Comment by rarkins** [comment]
I would like to try the beta. Now that we've moved to docker we have no choice but to use it in CI.

**Comment by egoldschmidt** [comment]
I would also be interested in beta support for multi-container environments.

**Comment by manishas** [comment]
@rarkins @egoldschmidt I have put you on the list for beta. I will connect in the next 2-3 weeks to give you more information.

**Comment by rarkins** [comment]
Thanks. This is a high priority for us as we need to use a different CI solution in the meantime

**Comment by johanneswuerbach** [comment]
I would also be interested. Thanks in advance.

**Comment by rarkins** [comment]
Also a heads up, beware of this docker-in-docker problem: https://github.com/docker/docker/issues/9939

**Comment by egoldschmidt** [comment]
@rarkins out of curiosity, what are you using in the meantime?

**Comment by manishas** [comment]
@rarkins Thanks for the warning :) We're battling a strange docker issue right now but we might have it under control now.

I will reach out over email to everyone who's expressed interest in the beta program. Thanks!

**Comment by ianneub** [comment]
@manishas I'd also love to try out the beta version with Docker support. We are currently looking for a CI/CD system that supports bulding/testing/pushing docker images.

**Comment by manishas** [comment]
@ianneub are you looking for multi-container testing/deployment or single container?

**Comment by ianneub** [comment]
Multi-container. We need to both build a container, and then test that container along with a host of other containers. Our test process is as follows:
* docker build -f Dockerfile.prod -t my_container .
* docker-compose up -d db elasticsearch redis memcached
* docker-compose run web rake db:create
* docker-compose run web rake db:migrate
* docker-compose run web rspec

**Comment by rarkins** [comment]
@manishas I think it would be great (and wise) to support docker-compose as natively as possible. This approach to docker orchestration has momentum and would save you a lot of time compared to writing your own orchestration for multi-containers.

**Comment by Shashank123p** [comment]
@manishas  Interested for the multi container beta. Thanks.

**Comment by mathroc** [comment]
Hi @manishas , we're interesting in running multiple containers using docker-compose. thank you

**Comment by jchamberlain** [comment]
@manishas, can I get in on the multi-container beta? (I assume this is related to #987.)

**Comment by tfox-aver** [comment]
We would also like to get in on the multi-container beta.

**Comment by mtoothman** [comment]
I would be very interested in the multi-container beta.

**Comment by gJigsaw** [comment]
As would I.

**Comment by manishas** [comment]
@ everyone who has expressed interest in multi-container environments, can you please send an email to manisha@shippable.com and tom@shippable.com with the following information -

First name, last name
Organization
Website 
Your job title
Email
Brief description of  scenarios you're interested in

We will start to reach out to folks in the next few days to discuss further, so this will be helpful to get started. Thanks!

**Comment by rarkins** [comment]
@manishas I see that docker support has been announced by Avi yesterday, but is there any documentation for how to configure it in shippable.yml?

**Comment by rarkins** [comment]
Ping @manishas! How can docker be installed/used?

**Comment by manishas** [comment]
We've addressed this through Shippable Formations - http://blog.shippable.com/introducing-shippable-formations-devops20-for-dockerized-apps

Please sign up for a demo to see how it works - https://shippable.youcanbook.me/

If you believe Formations does not work for you, please send me an email at manisha@shippable.com and we can set up a call to discuss further.

**Comment by manishas** [comment]
@rarkins we're looking into your scenario and will address it in upcoming weeks.
