### ISSUE TITLE
enable selected branches

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1235]
I have some branches on my repos that I don't want shippable to build or complain about if there is missing `shippable.yml`.

**Comment by manishas** [comment]
@fommil tagging as feature request.

**Comment by mbrodala** [comment]
@fommil what about the `branches` (exclude, include) option?

**Comment by fommil** [comment]
don't use shippable anymore.

**Comment by mbrodala** [comment]
What did you go with and what are the advantages? :-)

**Comment by fommil** [comment]
drone. it actually works, and is free software.

**Comment by mbrodala** [comment]
Ah OK, considered this one while looking for a CI service but decided for Shippable. Thanks.

**Comment by manishas** [comment]
this works with the branches tags:
http://docs.shippable.com/ci_configure/#includingexcluding-branches
 
You still need a shippable.yml in the branch you want to exclude.
