### ISSUE TITLE
organization just dropped off my account

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1236]
I have two paid-for accounts: `fommil` and `ensime`.

The `ensime` is no longer listed under my "Organisations" tab. Please add it back as soon as possible, as I require access to get anything done on it this weekend.

**Comment by manishas** [comment]
@fommil  we tried calling GitHub API directly with your token and it didn't  return repos from ensime. We're looking into it more to figure out why. 

If you want to unblock immediately you can enable private repos on shippable (top right of dashboard). If you are not comfortable doing that, we're investigating the core issue and will provide an update soon.

**Comment by fommil** [comment]
Ok, that works as a workaround!

**Comment by avinci** [comment]
This is a bug on github new API that they added. Supposedly we should be getting all repos a particular user has access by calling /users/:userid/repos. It seems to not do that....unless we have [repo] scope which mean we are asking for private access.

We will look into this more on Monday and get back....

**Comment by manishas** [comment]
this has been fixed now, so closing.
