### ISSUE TITLE
option to make builds of public repos public

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1237]
#1236 taught me that I actually needed to be a member of the organisation to see the results of a build in a public repo: e.g. https://app.shippable.com/builds/5516ee3986c05f0c006929ab

It would be good if it were possible to make builds of public repos, public. Indeed, it should probably be the default, as with Travis CI.

**Comment by manishas** [comment]
@fommil is #1236 still an issue? I see you've pasted a build from that org in this issue. Are you a member of the ensime org?

**Comment by manishas** [comment]
Yes you're a member of ensime on github.

**Comment by fommil** [comment]
@manishas yes, #1236 is a major issue. I can see the link to builds because they show up in the PR but I cannot see the results, nor am I am member of ensime on shippable anymore.

**Comment by manishas** [comment]
we do allow everyone to view individual builds for public repos if they have a link (i.e. through build badge or PR pages), but not the build history as a whole. 

Dup of #53.
