### ISSUE TITLE
Dedicated hosts: enabling layer cache for docker builds

### ISSUE THREAD

**Issue by melo** [Shippable/support#1238]
Hi,

I'm using Docker builds for some node.js projects and I would like the npm install layer to be cached.

But with the current command that Shippable is using this will not happen:

`sudo docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag="XXXXXX" .`

Is there any switch I can use to remove the options `--rm=true --force-rm=true --no-cache=true` from my builds?

Thanks,

**Comment by manishas** [comment]
@melo we do not support caching when we're building a container from the Dockerfile each time the build runs. We do support it if you prebuild an image and pull that image for your builds using the build_image tag in shippable.yml.

**Comment by melo** [comment]
Yeah, not what I looking for… We mostly want to build Docker images, using the Docker Build's functionality with the external hosts, and the difference between a full build and a build with cache is 10 mins vs 1.5 seconds, given that the biggest step is to install all the deps of our node.js project and those rarely change…

I'll work around with it with a docker wrapper script that removes the extra parameters, but I hope that you would consider giving us an option to do this directly.

Thank you
