### ISSUE TITLE
[cosmetic] log output doesn't play well with control sequences

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1240]
The log output is quite horrible when running any scala builds, e.g. this is typical output:

```
[info] Loading project definition from /root/workspace/src/github.com/fommil/freeslick/project
[info] Updating {file:/root/workspace/src/github.com/fommil/freeslick/project/}freeslick-build...
[info] Resolving com.typesafe.sbt#sbt-scalariform;1.3.0 ...
A
2K[info] Resolving org.scalariform#scalariform_2.10;0.1.4 ...
A
2K[info] Resolving org.scala-lang#scala-library;2.10.4 ...
A
2K[info] Resolving org.scoverage#sbt-scoverage;1.0.4 ...
A
2K[info] Resolving org.scoverage#scalac-scoverage-plugin_2.10;1.0.4 ...
A
2K[info] Resolving org.scoverage#sbt-coveralls;1.0.0.BETA1 ...
A
2K[info] Resolving com.fasterxml.jackson.core#jackson-core;2.4.2 ...
A
2K[info] Resolving com.fasterxml.jackson.module#jackson-module-scala_2.10;2.4.2 ...
```

with the

```

A
2K
```

being artefacts that should not be shown. Also, there is a lot of double newline printing happening when there should only be one newline.

**Comment by shrivara** [comment]
@fommil The mentioned artifacts should not appear anymore. You might still see new lines due to an unsupported escape sequence returned by `sbt`. To fix this, you can start `sbt` with the flag `-Dsbt.log.format=false`.

**Comment by fommil** [comment]
I've not used shippable in about a year, I'm happy for you to close all my tickets unless you see them as having wider applicability.
