### ISSUE TITLE
Postgresql gem install is failing 

### ISSUE THREAD

**Issue by bhargavisatpathy** [Shippable/support#1241]
When I am building my Ruby on Rails project it fails because the pg gem install is not finding the pg_cofig. What's the path to this file?

Thanks,
Bhargavi

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /root/.rvm/rubies/ruby-2.1.1/bin/ruby extconf.rb 
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by avinci** [comment]
what image are you using? if its default then all conf files are in the folder depending on your version
/etc/postgresql/[9.1][9.2][9.3]

try installing this package and see if it works before you install gem
`sudo apt-get install libpq-dev`

**Comment by beydogan** [comment]
@avinci I tried adding `sudo apt-get install libpq-dev` to `before_install` but it asks confirmation to continue installing and aborting.

```
sudo apt-get install libpq-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  comerr-dev krb5-multidev libgssrpc4 libkadm5clnt-mit8 libkadm5srv-mit8
  libkdb5-6 libkrb5-dev libpq5
Suggested packages:
  doc-base krb5-doc krb5-user postgresql-doc-9.1
The following NEW packages will be installed:
  comerr-dev krb5-multidev libgssrpc4 libkadm5clnt-mit8 libkadm5srv-mit8
  libkdb5-6 libkrb5-dev libpq-dev libpq5
0 upgraded, 9 newly installed, 0 to remove and 6 not upgraded.
Need to get 673 kB of archives.
After this operation, 2,901 kB of additional disk space will be used.
Do you want to continue [Y/n]? Abort.
```

**Comment by beydogan** [comment]
Solved this by adding following lines to `before_install`
```
 - sudo apt-get -y update
 - sudo apt-get -y install libpq-dev
```

**Comment by avinci** [comment]
yeah, it depends on what image we are doing. minv2, should not matter as we auto accept all user challenges. anything else you might need the `-y` flag. glad you got it working.

**Comment by manishas** [comment]
Closing.
