### ISSUE TITLE
Services section skipped during build using build_image

### ISSUE THREAD

**Issue by mikehancock** [Shippable/support#1243]
I am experiencing various issues, but I will try not to duplicate. 

Firstly, duplicate of https://github.com/Shippable/support/issues/1170:
build_image: shippableimages/ubuntu1404_scala
in my YAML file is ignored and build proceeds to use shippable/minv2:latest instead, unless i specify the build image through the web interface. 

That done, the following:
services:
  - redis

which was running happily with shippable/minv2, no longer produces a "Starting Services" section in the console output. I'm assuming this is because setting build_image means there are some pre-requisites / tools missing  - but I couldn't find anything in the documentation that states that. 

Can you confirm that with a custom image I need to take care of installing everything myself?

**Comment by manishas** [comment]
Yes, with custom images you will need to install the services and tools you need for your build. If you turn cache on, the container with your pre-reqs will be cached and the installs won't take up time for every build. 

Here are the docs - http://docs.shippable.com/en/latest/custom_images.html

**Comment by manishas** [comment]
@mikehancock did the docs help? Please let me know if we can further assist.

**Comment by manishas** [comment]
Closing this issue since the question was answered.

@mikehancock please feel free to re-open if you have any questions.
