### ISSUE TITLE
Incorrect javac version for java project

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#1244]
Added openjdk7 in shippable.yml but javac -version shows 1.6.0_32

Build id - 5519277586c05f0c00693939

**Comment by manishas** [comment]
@phagunbaya did you follow the instructions at http://docs.shippable.com/en/latest/custom_images.html#java

If you're using our Java specific image, you will need to add some lines to before_script as shown.

**Comment by phagunbaya** [comment]
@manishas : That helped. I'm wondered why javac version is 1.6.0_32 when I'm installing openjdk7 ?

**Comment by manishas** [comment]
CLosing. Please re-open if this is still a problem,
