### ISSUE TITLE
Unable to select startup plan

### ISSUE THREAD

**Issue by joaonvfigueiredo** [Shippable/support#1245]
I've successfully added my billing information, but for some reason I'm unable to select the startup plan. All I get is 'Internal Server Error' as the reply to the POST.

My bitbucket organization is yellow-energy .

**Comment by manishas** [comment]
@joaonvfigueiredo can you please try again and if it fails, email ragesh@shippable.com and manisha@shippable.com with the exact time you tried to upgrade? We will need to track this down.

**Comment by joaonvfigueiredo** [comment]
OK, it just failed. I'll e-mail you the info shortly.

**Comment by rageshkrishna** [comment]
@joaonvfigueiredo Thanks for the update. I have a definitive reason for this error -- your bank is refusing to approve the transaction. Here is the exact description from our payment provider:

`This response indicates that the customer's bank is declining the transaction for unspecified reasons. It doesn't necessarily mean that there is an issue with the card, but it does indicate that the bank won't approve this transaction.`

I'm afraid there isn't much we can do at this point. You will have to follow up with your bank to figure out why they are blocking this transaction.

**Comment by joaonvfigueiredo** [comment]
@rageshkrishna Thanks, I've just tried with a different card and everything worked out fine. It would be nice if you could inform the user via the error that there's a billing issue - I would've tried with a different card sooner. But I also understand that for security reasons, it's wiser to return a general error.
Now I can finally use the API ;)

 Best,
Joao

**Comment by rageshkrishna** [comment]
Good to know it worked out, @joaonvfigueiredo. And you're completely right about the vague error message. We do not want to take any chances with payment methods so we only log the errors internally and send a generic error in the response.

I'm going to go ahead and close this issue now that it's all working.
