### ISSUE TITLE
timeouts for dedicated host jobs

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1246]
I currently have a bug in my build that I'm trying to track down, which results in the build hanging and eating up my CPU.

However, Shippable has no timeout on my jobs... so they just happily spin eating up my server's resources.

Can you please add timeouts to jobs?

**Comment by manishas** [comment]
Jobs should timeout in 60 mins. Is this not happening?

**Comment by fommil** [comment]
nope, I had a 12 hour zombie process yesterday.

**Comment by manishas** [comment]
@fommil I see a few timeouts in your build history now, but they seem to be timing out after 2 hours. Are you still seeing these zombie processes?

**Comment by manishas** [comment]
Closing this issue since I don't think you're running into this any more.

If you're still experiencing this, please comment or re-open and we'll take another look.
