### ISSUE TITLE
Shippable for java dependent projects

### ISSUE THREAD

**Issue by reddy6ue** [Shippable/support#1248]
I am trying to solve the following problem. 

I have three projects, a persistence layer library, a service layer library and a web application.

Shippable currently doesn't have a feature to kickoff cascading builds like Jenkins does. So, I decided to use git submodules to setup appropriate dependencies. Does anybody have a sample that makes git submodules work with a bitbucket git repo? 

Or alternately, has anybody solved the cascading dependent jobs problem like the one Jenkins provides?

**Comment by manishas** [comment]
@reddy6ue funny you ask about cascading builds :)

Check out our blog post at http://blog.shippable.com/daisychaining-builds-with-our-new-public-api and let me know if that addresses your scenario. We also have a post on how to work with git submodules coming up later this week.

Thanks!

**Comment by reddy6ue** [comment]
This only solves part of the problem. It solves the chaining of builds, but it does not help with using the output of one build process to be used as an input in the other. 

This is how I configured it in Jenkins. 
1. Job to build model.jar only trigger by code changes to model.jar
2. Job to build service.jar triggered by both code changes to service.jar and code changes to model that uses the output model.jar from Job 1.
3. Job to bulid webapp.war triggered by code changes to webapp.war, service.jar and model.jar uses the output of both model.jar from Job1 and service.jar from Job2. 

At this point, the only way to get it to work is to install artifactory or nexus on a publicly accessible VM and then use the solution you pointed above to kickoff depended build. That's way too much configuration for what Jenkins can do with a single checkbox. I feel this is a serious drawback in shippable for java projects, especially for large enterprises where 100s or projects are going on at the same time and there are regular dependencies between them.

**Comment by manishas** [comment]
This is not on our near term roadmap so closing as deferred. If there are several +1 requests, it will pop back up on the roadmap.
