### ISSUE TITLE
MongoDB version

### ISSUE THREAD

**Issue by malchmih** [Shippable/support#1249]
Hello!

Base docker image has outdated version of Mongo - 2.4.12. Could you update it to 2.6+? My project depends on the features of this new version, so I can't really use Shippable now.

Thank you!

**Comment by manishas** [comment]
@malchmih thanks for bringing this to our notice. 

One way to unblock your scenario is for you to use the build_image tag in our yml and start with a barebones image. This is documented here - http://docs.shippable.com/en/latest/custom_images.html

Then you can install the right version of mongodb in your shippable.yml and use it. Does that work?

**Comment by malchmih** [comment]
Thank you! I'll try and report here.

**Comment by manishas** [comment]
Second way to get this going is -

add this line under `before_install:`
```
- sudo apt-get install mongodb-org
```
this will update mongo on that image, however it will have to update it every time the build runs. You can circumvent the need to update every time by adding the line `cache: true` to the yml, then it will save the image after the build runs.

**Comment by malchmih** [comment]
I've chosen second path and it works so far. But anyway it would be great to have mongo version updated - currently 3.0.1 is their "production" =) I'd like to have this issue open, if it's ok with you. Thanks for help!

**Comment by malchmih** [comment]
I also created pull request for this feature: https://github.com/shippableImages/minBase/pull/1

**Comment by icebob** [comment]
+1

**Comment by manishas** [comment]
Our standard images have been updated with latest version of services.
Images are at [drydock repo](https://hub.docker.com/u/drydock/)

MongoDB 3.0 should be installed on all `pls` and `all` images.

**Comment by manishas** [comment]
closing since this is done.
