### ISSUE TITLE
Build showing success but Boot process marked x.

### ISSUE THREAD

**Issue by yamii** [Shippable/support#1250]
I have a test project it's just pulling an existing image from docker hub. 

I can see that the overall build is marked as success. However, `Boot` section is marked x. What does it imply?

Last entry of my `Boot` section was:
/home/shippable/build/build.sh: line 21: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

Here's the link to the build:
https://app.shippable.com/builds/551a497053beef0c0091b671

**Comment by manishas** [comment]
thanks for reporting! we'll take a look.

**Comment by manishas** [comment]
This has been fixed, so you shouldn't see sections of your yml fail if the build passes. I am closing this issue, please reopen if you still run into it.
