### ISSUE TITLE
Organization does not show in the Repositories List

### ISSUE THREAD

**Issue by MarneeDear** [Shippable/support#1251]
My Github Organization, Elmerly, does not show in the Repositories list.  I want to enable two Repos in that Organization.  I have clicked Sync Account a few times, but no luck.

Thank you.

**Comment by manishas** [comment]
@MarneeDear does your org have any public repos?

You will need to give us access to private repos in order to view orgs with just private repos. You can do this by clicking on the 'private repos' at the top right of your dashboard and following the flow on GitHub. Then click 'sync account' on your dashboard. You should see your org.

**Comment by manishas** [comment]
Actually, is this a new org? Was it created after you authorized shippable?

**Comment by MarneeDear** [comment]
Yes.  This is a new org that I transferred from an existing org that is now
deleted.

On Tue, Mar 31, 2015 at 8:08 AM, Manisha <notifications@github.com> wrote:

> Actually, is this a new org? Was it created after you authorized shippable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1251#issuecomment-88125905>.
>



-- 
Marnee Dearman
Software Engineer
Tucson, Arizona
520.647.6372

**Comment by manishas** [comment]
@MarneeDear There is another potential reason for this. We ask for permissions to github when you first sign in, but those aren't valid for orgs created after that point. If this is the case, you should see this when you go to github settings for the org -
https://cloud.githubusercontent.com/assets/4965752/6409551/4ae82298-be8b-11e4-8aa7-2b6819ad2b82.png

You will need to remove these restrictions from GitHub and then click on account sync on your dashboard. Can you let me know if that works?

**Comment by MarneeDear** [comment]
Yes that worked.  I can see my org and I can enable the repos.

Thank you.


On Tue, Mar 31, 2015 at 9:19 AM, Manisha <notifications@github.com> wrote:

> @MarneeDear <https://github.com/MarneeDear> There is another potential
> reason for this. We ask for permissions to github when you first sign in,
> but those aren't valid for orgs created after that point. If this is the
> case, you should see this when you go to github settings for the org -
>
> https://cloud.githubusercontent.com/assets/4965752/6409551/4ae82298-be8b-11e4-8aa7-2b6819ad2b82.png
>
> You will need to remove these restrictions from GitHub and then click on
> account sync on your dashboard. Can you let me know if that works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1251#issuecomment-88153283>.
>



-- 
Marnee Dearman
Software Engineer
Tucson, Arizona
520.647.6372

**Comment by manishas** [comment]
Thanks! Closing.
