### ISSUE TITLE
Best way to run PHP and node tests in same build?

### ISSUE THREAD

**Issue by nathanmarks** [Shippable/support#1252]
What's the best way to run both in the same build?

I have an app that has the front and back end in the same repository. Front end is AngularJS and back end is PHP.

Can I just use npm like I normally would? I seem to be having issues so far with permissions.... do we need to use sudo? Is there a way to do this that I'm not aware of that doesn't require the use of sudo for npm?

**Comment by manishas** [comment]
@nathanmarks you should specify the language as php in your yml. As long as you use our default image, it comes with everything preinstalled, so npm should still work. Let me know if you run into any problems.

Also, a link to a failed build would be super useful for us to debug, so please include that. Thanks!

**Comment by nathanmarks** [comment]
@manishas 

I got my build working! great.

I was unable to use npm without sudo, is that intended?

**Comment by manishas** [comment]
Closing.
