### ISSUE TITLE
Question: Can a custom Docker image run in a minion?

### ISSUE THREAD

**Issue by pcullin-ratio** [Shippable/support#1254]
I'm using Iron.io's IronWorker service in my application, and they have a new recommended dev workflow that involves running worker code in their custom Docker image(s) - iron/images:node-0.10:
http://blog.iron.io/2015/03/the-new-ironworker-development-workflow.html

It looks like you can't do this with Shippable, unless you use the new Dedicated Hosts feature, but I'm wondering if it is in fact possible and if so if you can provide guidance.

**Comment by manishas** [comment]
@pcullin-ratio just responded to your email. Let me know if that helps... we can jump on a call tomorrow afternoon and I can explain further.

**Comment by manishas** [comment]
Closing this issue since the discussion is happening offline.
