### ISSUE TITLE
Collaborator cannot access private project

### ISSUE THREAD

**Issue by leecrossley** [Shippable/support#1255]
I (the owner) can see my private project, but a collaborator (@ryansroberts) cannot.

Private repos are enabled for both accounts but when the collaborator visits the project url:

"This project is no longer available on Shippable. Go to dashboard"

**Comment by manishas** [comment]
sounds like a bug, we'll take a look and let you know what we find.

**Comment by manishas** [comment]
@leecrossley we synced the repos and he should see it on his dashboard now. Please re-open if it doesn't work.

Thanks!

**Comment by leecrossley** [comment]
Works now, thanks
