### ISSUE TITLE
triggerBuild allows branch selection

### ISSUE THREAD

**Issue by joaonvfigueiredo** [Shippable/support#1256]
I've setup our CI system daisy-chaining builds using the Shippable API as seen [here](http://blog.shippable.com/daisychaining-builds-with-our-new-public-api).

However [reading the docs](http://docs.shippable.com/en/latest/api.html#post-workflow-triggerbuild) for the /workflow/triggerBuild I see all the parameters it takes is the projectId.

Given that Shippable can select the branch which to build when receiving the hook from Bitbucket, is it possible to have an extra parameter branchName in the POST data, such that I can specify which branch I want to trigger build for?

Thanks,
Joao

**Comment by rageshkrishna** [comment]
Hi @joaonvfigueiredo! We also accept `branchName` if you POST it along with the project ID, like so:

````
"branchName": "master"
````

**Comment by rageshkrishna** [comment]
I'll get the documentation updated soon. Sorry about the confusion.

**Comment by joaonvfigueiredo** [comment]
@rageshkrishna thanks! I'll test it in a bit.

**Comment by joaonvfigueiredo** [comment]
@rageshkrishna this worked fine, I used the $BRANCH variable without any issues (this way the shippable.yml is portable across branches)

**Comment by manishas** [comment]
closing.
