### ISSUE TITLE
Node js version and docker image

### ISSUE THREAD

**Issue by leonfs** [Shippable/support#1257]
Hi,

I'm having an issue with the node version. During build phase I set the node version 0.12.0 by doing:
- source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
- node --version (this prints the correct version, 0.12.0)

As per documentation. 
Then npm will install all module dependencies and the image would be published to docker hub. 

Once I pulled the image from docker hub, when I try to execute my app the node version is 0.10.38. Compiled modules (bcrypt for example) would be compiled against 0.12.0 and throws an error:

Unhandled rejection Error: /root/workspace/src/bitbucket.com/{team}/{team_app}/node_modules/bcrypt/build/Release/bcrypt_lib.node: undefined symbol: node_module_register

**Comment by rageshkrishna** [comment]
Hi @leonfs. Because the build uses nvm, you'll need to initialize it before running your app like this:
````
source ~/.nvm/nvm.sh && nvm use 0.12
````
Notice that it says "use" and not "install" here.

Basically, the image comes with multiple versions of node_js preinstalled and you need to activate nvm and tell it which version you're interested in using.

**Comment by leonfs** [comment]
That was my suspicion but I didn't know how to do it. I would have thought that the configuration would have been persisted in the docker image with "nvm install". Would be great to have it in the documentation for node projects.

This leads to other questions:
1. Does nvm install include an implicit nvm use within boot.sh scope? 
2. Is there a way to persist the version to use? maybe using an environment variable?

Thanks for the quick reply.

**Comment by rageshkrishna** [comment]
1. Yes, when you do an `nvm install`, it implicitly `use`s that version
1. I'm not sure about environment variables, but you should be able to say `nvm default 0.12`. From this point on, 0.12 will be selected by default whenever you `source ~/.nvm/nvm.sh`.

**Comment by leonfs** [comment]
Fantastic Ragesh, thank you very much!!
