### ISSUE TITLE
Can not loading teams for my bitbucket code base . (blocking issue)

### ISSUE THREAD

**Issue by XinV** [Shippable/support#126]
Please help me check my repo named "portal", I signed up your service 2 days ago. We have 5 team members within that bitbucket account, but it can not load the team members. Please check. Thanks

**Comment by carlqt** [comment]
Hi! I'm currently facing this issue. I'm not able to see the repository that I have created under bitbucker team.

**Comment by lekhab** [comment]
@carlqt: can you please try force syncing the account?  Click on Account Settings (the gear icon) on the top bar and click the Force Sync button? 

In case that doesn't work, can you please add the link to the subscription here?

**Comment by lekhab** [comment]
@carlqt: Closing this. please open a new issue if you are still having trouble.
