### ISSUE TITLE
Cannot upgrade account

### ISSUE THREAD

**Issue by sophiegeorge** [Shippable/support#1260]
Hey there,

I'm trying to upgrade from a free plan to the Startup package and cannot see anywhere to input card details for this. Can you assist further?

We're looking to use Shippable for our Github repos and I am one of the owners for the organisation.

Many thanks

Soph

**Comment by kkarski** [comment]
I am looking for the same and can't find it. How do I upgade?

**Comment by lc3t35** [comment]
Same for me !

**Comment by lc3t35** [comment]
See #1048
