### ISSUE TITLE
Where to find build artifacts?

### ISSUE THREAD

**Issue by vjmuvva** [Shippable/support#1261]
Hi,

I couldn't find build artifacts on build page. Can someone let me know how can I view and download build artifact? Did I miss anything? Here is my Shippable.yml

language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew build
notifications:
 email:
      recipients:
         - chinna580@gmail.com

**Comment by rageshkrishna** [comment]
@vjmuvva You need to add `archive: true` to the YML file to enable archiving. We don't archive by default.

**Comment by manishas** [comment]
@vjmuvva I am closing this issue since your question was answered. Please re-open if you need anything else.
