### ISSUE TITLE
Keep environment variable after build.sh in docker image

### ISSUE THREAD

**Issue by leonfs** [Shippable/support#1262]
Hi,

I was wondering if it's possible to keep in the docker image environment variables used during the build process. For example, $SHIPPABLE_REPO_DIR.

I was trying to do:
after_scripts:
 - echo WORKING_DIR=$SHIPPABLE_REPO_DIR >> ~/.bashrc

But still the variable wouldn't get loaded when running the docker image. 

I think it would be pretty cool to be able to do this, specially mixing it with encrypted environment variables. 

Any ideas on how can I achieve it?

**Comment by rageshkrishna** [comment]
This can happen if the container is run without setting the `HOME` environment variable. Are you using one of our standard build images? Depending on which one you're using, HOME will need to be set differently.

For minv2 images, try `docker run -it -e HOME=/home/shippable /bin/bash`

For language specific images that run as root, try `docker run -it -e HOME=/root /bin/bash`

This should allow bash to correctly source your .bashrc file.

**Comment by rageshkrishna** [comment]
Oops, I forgot to add the image name in those commands. They should be:

`docker run -it -e HOME=/home/shippable {your-image-name} /bin/bash` and 

`docker run -it -e HOME=/root {your-image-name} /bin/bash`

**Comment by leonfs** [comment]
Hi Ragesh,

Thanks again for the quick response. 

I followed your advice and run those commands. And the environment variable started to show up. 

But, I went further to find out why. And I found out that bash will source the .bashrc file when using the 

`-t` 

parameter even if I remove the HOME environment variable.

Thanks again!! 
Leo.-

**Comment by rageshkrishna** [comment]
Glad it worked! I'm not sure how the `-t` option helps, but I'll read up on it. Thanks for pointing it out.

I'll close this issue as it's working for you now.
