### ISSUE TITLE
Can not see any of my bitbucket repos and orgs

### ISSUE THREAD

**Issue by m00t** [Shippable/support#1264]
I can not run build because I can not see any of my org bitcubket private repos: https://www.dropbox.com/s/e0vt3usw6vhcdwn/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-03-26%2009.45.51.png?dl=0

And support person with email manishas@shippable.com just forgot about me a week ago.

**Comment by manishas** [comment]
@m00t are your repositories mercurial? We support git repos at this time.

**Comment by m00t** [comment]
All my repos are git.

**Comment by manishas** [comment]
@m00t do you have read/write/admin access to the repos in the org?

From our engineer - If the user is an admin on their org(team), but does not belong to any group that has read, write or admin access to the repos - then bitbucket does not return the repos. If this is the case, these specific repos must not show up on their Bitbucket dashboard either.. they will only see it under their team view in BB.

]

**Comment by m00t** [comment]
@manishas I belong to administrators group in this team. Also I have many private git repositories which do not listed too.

**Comment by manishas** [comment]
we're taking a deeper look at this and I'll update you as soon as I know more.

**Comment by m00t** [comment]
Tried to login today: now I can see my repos.

**Comment by manishas** [comment]
@m00t I am sorry this slipped off our radar. We did look into this issue and could not repro it at our end.

Are you available for a hangout today? I can do anytime between 3-5pm PST. Let me know.

**Comment by manishas** [comment]
Seems to be resolved, so closing.

Again, apologize for the lack of follow up.

**Comment by m00t** [comment]
It is ok, I understand ticket can be lost. Will try shippable later maybe, since this issue was resolved. Thank you!
