### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1265]
specifically for example inventid/neo 2704.1

I tried restarting, but it failed again (only one of the two builds though)

![screenshot 2015-04-02 22 40 58](https://cloud.githubusercontent.com/assets/2778689/6973211/7398abea-d989-11e4-8577-7f0492a68346.png)

**Comment by manishas** [comment]
We're taking a look...update soon

**Comment by manishas** [comment]
We isolated this issue to one of our build hosts and we've brought that host down, so you shouldnt see this any more.  Please let us know if it happens again.

**Comment by malchmih** [comment]
Have the same issue for malchmih/rpq 140.1, 142.1

**Comment by rogierslag** [comment]
Still occurring here

**Comment by rogierslag** [comment]
![screenshot 2015-04-04 13 13 54](https://cloud.githubusercontent.com/assets/2778689/6992407/774d6ffc-dacc-11e4-9337-315e334183a7.png)

**Comment by manishas** [comment]
@rogierslag we were running into aufs issues on some build hosts and this has been addressed now. I am closing this issue, but please reopen if this happens again.

Thanks!
