### ISSUE TITLE
Builds kicked of via github webhook failing

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1266]
500 Server Error: Internal Server Error ("Cannot start container 34d2e58a159ac803758d88cbacfab498d5e7154687594a284d14fda8d5d8b920: exec format error"): Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
APIError: 500 Server Error: Internal Server Error ("Cannot start container 34d2e58a159ac803758d88cbacfab498d5e7154687594a284d14fda8d5d8b920: exec format error")

Kicking it off manually right after works...

**Comment by manishas** [comment]
We're taking a look.at this...update soon.

**Comment by manishas** [comment]
We isolated this issue to one of our build hosts and we've brought that host down, so you shouldnt see this any more. Please let us know if it happens again.

**Comment by frenkel** [comment]
I'm seeing this as well:

500 Server Error: Internal Server Error ("Cannot start container e4203e3a1a0e4ec2e81fe41113baa4f065dfccab0082f0506856ba106f5acc42: exec format error"): Traceback (most recent call last):

**Comment by claar** [comment]
We get this as well since yesterday, and again a moment ago:

Server Error: Internal Server Error ("Cannot start container ff4e151aa67ef64f4bf87c3cae425d6e438b7cbef47d895c1974be064d31f720: exec format error")

**Comment by chriskinsman** [comment]
I can confirm this is also still happening for us...

**Comment by manishas** [comment]
yes, we're looking into this... update soon. Thanks!

**Comment by nathgs** [comment]
+1

**Comment by manishas** [comment]
Update on this - we were running into some aufs related issues on our build hosts. We have addressed the problem and this should not be happening any more. I am closing this, but please re-open if you run into this again.
