### ISSUE TITLE
Breadcrumbs linking is inconsistent

### ISSUE THREAD

**Issue by catskul** [Shippable/support#1267]
The bread crumb links in the top left do not follow a simple consistent scheme.

While looking at a project the text is:

    Team / project

If I click on project, I get taken to bitbucket.
If I click on team, I get taken to shippable team page

Once on the shippable team page the text is:
 
     Team

If I click on the team, I end up on the bitbucket page.

I regularly click on links on Shippable, and in Shippable emails and end up on bitbucket without meaning to. It's extremely frustrating, and despite having used Shippable for months now I still find myself ending up on pages I don't mean to be.

IMO virtually all links should link back to places within the shippable app, unless there's a compelling reason not to (links on commit hashes). I see no utility in arbitrarily linking back to revision control site. 

I'll open a separate ticket for the email UX.

**Comment by avinci** [comment]
this has been completely revamped. Let us know if you still see issues
