### ISSUE TITLE
Primary/largest link in emails should be to the build results

### ISSUE THREAD

**Issue by catskul** [Shippable/support#1268]
I've been using Shippable for several months now and have found the email notifications a bit frustrating in their UX.

Virtually any time I want to go somewhere from the email it's going to be the details of a test failure.

However the test failure "details" link is the smallest most non-obvious link on the page, and when I'm in automatic mode, I always end up clicking one of the other links on the page, and end up annoyed.

IMO, the first and most obvious link on the page should be to the test results:
- Not to shippable.com, no one who already uses the service would want to go there from this email
- Not to the repo url, not sure what I would do from there
- The commit hash is potentially useful but certainly not in comparison to why the build failed.

If you agree, please re-think the UX of your email alerts.

The easiest fix IMO would be link to move the results to the top, and the context information to the bottom, and to link the green/red "succeeded"/"failed" marker to the details. And un-link the Shippable icon.

**Comment by manishas** [comment]
We should redesign the email template, so marking implement.

**Comment by deepikasl** [comment]
We have re-designed our build report email.
Hence closing.
