### ISSUE TITLE
"fadeInDown" animations distracting

### ISSUE THREAD

**Issue by catskul** [Shippable/support#1269]
This may just be personal preference, but I find the fadeInDown animation on some of the widgets distracting. Every time a page loads things that move for no reason draw attention without providing any information, and it feels like attentional noise.

I'm not sure if I'm in the minority, but I'd ask that you poll a few users and see if there might be consensus.

**Comment by manishas** [comment]
@catskul we have not heard this feedback from users before. I will tag this as a feature request and leave it open for a couple of weeks. If folks add a +1, we can revisit this experience.

**Comment by catskul** [comment]
Thanks @manishas ! much appreciated.

**Comment by avinci** [comment]
actually I agree with @catskul with this. A build system needs to be snappy and peppy. We are working on a new version of the UI, but in the meantime I will find these and remove it in the next few days as I find it. Thanks for the feedback...

**Comment by avinci** [comment]
+20 just in case

**Comment by manishas** [comment]
The UI has been completely redesigned last month and we've tried to stay away from animations. Thanks for your feedback!

Closing this issue.

**Comment by catskul** [comment]
Thanks : )
