### ISSUE TITLE
Custom Docker build on Dedicated host staled at "Waiting" status

### ISSUE THREAD

**Issue by patelsan** [Shippable/support#1271]
Trying my very first build, and it's stuck at "Waiting" status, I canceled and queued up couple times but no luck so far. There are no notifications or messages, so I don't know even if it's me messing something up here!

**Comment by manishas** [comment]
@patelsan your dedicated host isn't set up correctly. Please click on the deploy button in the dedicated hosts window -
![screen shot 2015-03-27 at 3 56 49 pm](https://cloud.githubusercontent.com/assets/2983749/6995046/23797c6e-dae4-11e4-8738-8eb750c35215.png)

**Comment by patelsan** [comment]
Ahhaa... it wasn't clear from the UI that one more setup step is required. Thank you for catching that.

I deployed the builder, now I am running into  permission error while booting, it appears to be occurring in the shippable sequence before executing the application/ tests, following is the error I am getting now...

Checking Image brainiacapp:master.5
Image exists, starting boot sequence
[Errno 13] Permission denied: '/home/shippable/builds/551c3c1d5ab6cc1352b36e61/5.1': Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
OSError: [Errno 13] Permission denied: '/home/shippable/builds/551c3c1d5ab6cc1352b36e61/5.1'

**Comment by fakewaffle** [comment]
Yeah, the documentation isn't up to date either.

**Comment by fakewaffle** [comment]
I also get a permission denied error:

```
Boot ✗
Checking Image user-service:dev.2.1
[Errno 13] Permission denied: '/home/shippable/builds/55123a955ab6cc1352aa323d/2.1': Traceback (most recent call last):
File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
self.execute_step(build_plan, current_step, False)
File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
raise e
OSError: [Errno 13] Permission denied: '/home/shippable/builds/55123a955ab6cc1352aa323d/2.1'
```

**Comment by patelsan** [comment]
It resolved automagically after waiting for couple days! Now running into permission denied while pushing to Docker Hub - waiting for inputs on that now.

**Comment by manishas** [comment]
Closing this issue since it was resolved.
