### ISSUE TITLE
Issues with running apt-get update on my build instances this morning.

### ISSUE THREAD

**Issue by sbarrus** [Shippable/support#1272]
Fetched 4,386 kB in 3s (1,237 kB/s)
W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B70731143DD9F856
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/main/source/Sources  502  Bad Gateway [IP: 108.168.194.92 80]

W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/main/binary-amd64/Packages  502  Bad Gateway [IP: 108.168.194.92 80]

W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/main/binary-i386/Packages  502  Bad Gateway [IP: 108.168.194.91 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by thedracle** [comment]
It seems to get stuck on this step during apt-get update:

Ign http://www.apache.org 21x Release.gpg


Pretty much all of our builds are broken until this is fixed :(

**Comment by thedracle** [comment]
I've produced a temporary workaround by removing the apache lines from sources.list:

install:
    - sudo sed -i '/apache/d' /etc/apt/sources.list
    - sudo apt-get update

**Comment by manishas** [comment]
@thedracle we will look into this as soon as we can... hope you are temporarily unblocked by the workaround?

**Comment by thedracle** [comment]
Yes, builds are succeeding with the work around.

**Comment by manishas** [comment]
@sbarrus @thedracle debian mirrors are down, so sudo apt-get update will fail until they are up.

**Comment by manishas** [comment]
@sbarrus @thedracle this should be resolved now since I just ran a successful build using apt-get update. Please re-open this issue if you still run into this.
