### ISSUE TITLE
Credit card charged twice

### ISSUE THREAD

**Issue by bj16060** [Shippable/support#1274]
My card was charged twice for a yearly subscription. Please contact me to fix this.

Transaction IDs: 6vhmj56 & b92jt56 

As an aside, Github is a silly place to direct all support issues. I can understand tech related issue but billing issues might be better handled in some other fashion.

**Comment by manishas** [comment]
@bj16060 I will check on this and reverse one of the charges. Sorry about this.

**Comment by manishas** [comment]
We have issued a refund. Please let me know if you don't see it in the next 2-3 days. 

Thanks!
