### ISSUE TITLE
ember-cli tests won't run(PhantomJS)

### ISSUE THREAD

**Issue by mikkergimenez** [Shippable/support#1275]
Hello,

   I'm not sure if there are tools available to debug this, but I'm unable to get my ember-cli tests to run on shippable.  They run fine locally.  The output is below, not sure if I need to do something special to enable phantomjs or what.

Thanks!

OUTPUT:

ember test
Future versions of Ember CLI will not support v0.10.22. Please update to Node 0.12 or io.js.
version: 0.2.2
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Building
Built project successfully. Stored in "/root/workspace/src/bitbucket.com/mikkergp/ember-webroot/tmp/class-tests_dist-mP3dn3nq.tmp".

1..0
# tests 0
# pass  0
# fail  0

# ok
No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.
Build script completed
Build completed
Skipping artifact upload
Build completed

**Comment by manishas** [comment]
@mikkergimenez can you please let me know which github or bitbucket id you're using to run this?

**Comment by mikkergimenez** [comment]
Hello Manisha,

It's bitbucket username mikkergp.

Thanks

Mik

**Comment by manishas** [comment]
@mikkergimenez this should not happen any more. Please let me know if you're still running into this problem, and feel free to re-open the issue.

**Comment by mikkergimenez** [comment]
This is still not working, same error messages.
