### ISSUE TITLE
heroku create app & deploy doesn't working

### ISSUE THREAD

**Issue by jpizarrom** [Shippable/support#1276]
```
heroku apps | grep ^$APP_NAME || heroku create $APP_NAME -n && heroku addons:add heroku-postgresql --app $APP_NAME && heroku addons:add mandrill --app $APP_NAME
```
```
WARNING: Heroku Toolbelt requires Ruby 1.9+
https://github.com/heroku/heroku/pull/1479
/usr/local/heroku/lib/heroku/command/stack.rb:64: warning: already initialized constant IN
/usr/local/heroku/lib/heroku/command/stack.rb:68: warning: already initialized constant OUT
[WARNING] MultiJson is using the default adapter (ok_json).We recommend loading a different JSON library to improve performance.
WARNING: Heroku Toolbelt requires Ruby 1.9+
https://github.com/heroku/heroku/pull/1479
/usr/local/heroku/lib/heroku/command/stack.rb:64: warning: already initialized constant IN
/usr/local/heroku/lib/heroku/command/stack.rb:68: warning: already initialized constant OUT
[WARNING] MultiJson is using the default adapter (ok_json).We recommend loading a different JSON library to improve performance.
Creating a6bf124c-feature-upgrade-loopb... done, stack is cedar-14
WARNING: Incomplete credentials detected, git may not work with Heroku. Run `heroku login` to update your credentials. See documentation for details: https://devcenter.heroku.com/articles/http-git#authentication
Build completed
Skipping artifact upload
Build completed
```

I changed api key, encrypted again, checked localy, still get the same error

**Comment by manishas** [comment]
@jpizarrom does the suggestion in https://github.com/Shippable/support/issues/863 help?

@rageshkrishna suggested -

@stocarul Sorry about the delay. It looks like something changed with the way Heroku deals with Git authentication. Can you please try adding `--ssh-git` to your `heroku git:remote` command? The full command should now look like this:

````
git remote -v | grep ^heroku || heroku git:remote --ssh-git --app $HEROKU_APP_NAME
````

This should get you around the `Incomplete credentials detected, git may not work with Heroku.` error.

**Comment by jpizarrom** [comment]
it doesn't work, because I'm trying to create an heroku app and there isn't a --ssh-git param

heroku apps | grep ^$APP_NAME || heroku create $APP_NAME -n

**Comment by manishas** [comment]
@jpizarrom I think you're running into the same issue as  https://github.com/Shippable/support/issues/1291

If you're specifying a language other than ruby in the language tag, can you add the following to the before_install section of your yml -

```. $HOME/.rvm/scripts/rvm && rvm use ruby-2.0.0-p598 --default && ruby --version```

The heroku push will then use ruby 2.0.0

**Comment by manishas** [comment]
Closing this issue. @jpizarrom please let us know if it worked for you.

**Comment by jpizarrom** [comment]
@manishas It works, thanks
