### ISSUE TITLE
does shippable run builds for each git tag push on bit-bucket?

### ISSUE THREAD

**Issue by geshan** [Shippable/support#1277]
I think it does not run the build/tests for git tags pushed on bit-bucket can this be checked. In my opinion it should run the build on each git tag push only only branch push. thanks.

**Comment by geshan** [comment]
any update?

**Comment by rageshkrishna** [comment]
@geshan I tried this out and it looks like BitBucket's webhook doesn't tell us anything about what really happened on the repository when you push a tag:

````
payload={
  "repository": {
    "website": "",
    "fork": false,
    "name": "Python-buildsample",
    "scm": "git",
    "owner": "ragesh",
    "absolute_url": "/ragesh/python-buildsample/",
    "slug": "python-buildsample",
    "is_private": false
  },
  "truncated": false,
  "commits": [],
  "canon_url": "https://bitbucket.org",
  "user": "ragesh"
}
````

It looks like the same bug at BitBucket's end that's stopping us from building fast-forward merges: https://bitbucket.org/site/master/issue/7775/post-service-does-not-provide-useful#comment-5215915

I'm not sure if there's anything we can do about this except wait for BitBucket to fix their webhooks.

**Comment by kanthchandra** [comment]
Hi @geshan , we have recently added this feature. Can you please try this out and let us know if this works for you?
