### ISSUE TITLE
[WISHLIST] Create a link with project status from shippable

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#1279]
Other CI show a status with a link from ci tool that you can add to readme file to show it ever you open main project page.

Example:
![build status](https://cloud.githubusercontent.com/assets/6644187/7014266/4a2bc510-dc88-11e4-84df-90105134c6d7.png)

Additional to this matter
There is a standard named CC Tray 
[cc example] (https://api.travis-ci.org/repos/Vauxoo/maintainer-quality-tools/cc.xml?branch=master)
This is a cool standard to create our custom dashboard or use a tool with cc tray support for example http://ccmenu.org/

**Comment by manishas** [comment]
@moylop260 we already do the build badge and you can paste it in the readme. Please look at http://docs.shippable.com/en/latest/config.html#build-badge

You will need to go to the project on Shippable, click on 'Badge' on the right side of the page, copy the markdown, and then paste that in the README file of your github repo.

The cctray request is an open issue and we will definitely consider adding support. Thanks!

**Comment by moylop260** [comment]
I got it
Thank you
I will close this issue
