### ISSUE TITLE
shippable deploy keys

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1284]
Hi guys,

Some time ago new keys were required for shippable, but the old ones were not deleted. From a security standpoint, IA is hammering me to reduce the deploy keys per repo. Which can be deleted?

![screenshot 2015-04-07 16 17 47](https://cloud.githubusercontent.com/assets/2778689/7025161/ea9f73b6-dd41-11e4-920e-0ed36e0a229e.png)

**Comment by avinci** [comment]
`shippable-production` is what we use. We should have deleted the other one and this is a miss. Sorry about that.

**Comment by rogierslag** [comment]
No problem, thanks for the quick feedback!
