### ISSUE TITLE
git clone stopped working 

### ISSUE THREAD

**Issue by vkuusk** [Shippable/support#1285]
We were using git clone to get some extra files from a different repo than it is defined for the shippable project.

Shippable had the deployment key setup in that repo too.
and it was working fine all last week,  but 
on monday it stopped working with the message during  command:

git clone git@github.com:myorganization/my-repo-name.git

     Cloning into 'my-repo-name'...
     Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
     ERROR: Repository not found.
     fatal: Could not read from remote repository.

     Please make sure you have the correct access rights
     and the repository exists.

I re-ran the build that was working on Friday and it fails now. 

So it's the problem with github keys, It's most likely on our side, but I would appreciate 
if you cold confirm that it were no events(updates) on shippable side which could reset the private key for the projects?

Thanks

**Comment by manishas** [comment]
@vkuusk I will check with engineering but I am not aware of any change that would cause this on our side. Can you share a link to the failed build? I see all latest builds have passed for your projects.

**Comment by vkuusk** [comment]
Thank you for checking with engineering @manishas 

I commented out the tests which were depending on the  git clone, so the latest build were passing. 
The project: https://app.shippable.com/projects/545284ad44927f89db3e599f
The first failing build was: https://app.shippable.com/builds/55236b7fbd14530c001e8ed1

I'll step through our code tomorrow to see where the key might be changed on our side.
Thx.

**Comment by rageshkrishna** [comment]
Hello @vkuusk. I can confirm that we haven't made any changes to SSH keys over the weekend. Please let me know if there's anything more I can do to help you debug this.

**Comment by vkuusk** [comment]
Thank you, @rageshkrishna 
The problem is on our side: one person added shippable deployment key (public ssh key) to his github account. So everything was working fine, but
when his account was removed from the organization our projects broke.

To troubleshoot the situation it was helpful to include the command:

     ssh -T -ai ~/.ssh/id_rsa git@github.com

into shippable.yml to find whose account has the key.

Just in case, if I can not contact him, will it be possible to reset the deployment key for the organization?

I'll try to contact him today and will let you know the result. Thanks.

**Comment by rageshkrishna** [comment]
Sure thing, @vkuusk. Let me know how it goes.

**Comment by vkuusk** [comment]
@rageshkrishna I recovered the key.
everything is back to normal.
Thanks

**Comment by manishas** [comment]
@vkuusk thanks for confirming! 

Closing this issue.
