### ISSUE TITLE
Is there a way to get the commit message in the build process?

### ISSUE THREAD

**Issue by geshan** [Shippable/support#1287]
The branch, build number, job id even commit ID is available in the build as [environment variable](http://docs.shippable.com/en/latest/config.html#common-environment-variables) , is there anyway to read the commit message during the build process which is not documented? 

If yes please let me know or any other way to get the commit message as it seems it is being read for [skipping builds](http://docs.shippable.com/en/latest/config.html#skipping-a-build).

**Comment by rageshkrishna** [comment]
Hi @geshan, we don't make the commit message available as an environment variable.

However, we do expose the commit sha as $COMMIT. Using a little git on the command line you can get the commit message like this:

````
before_script:
 - export COMMIT_MESSAGE=`git log --format=%s -n 1 $COMMIT`
 - echo $COMMIT_MESSAGE
````

I hope this helps!

**Comment by geshan** [comment]
I think even the $COMMIT will not be required, thanks I should of thought of this.
