### ISSUE TITLE
HTTP 403 while pushing image to private repo on Docker Hub

### ISSUE THREAD

**Issue by patelsan** [Shippable/support#1289]
I am getting following error while pushing image to my Docker Hub's private repo

"Error: Status 403 trying to push repository patelsan/brainiacapp: "Access denied, you don't have access to this repo": Traceback (most recent call last):"

I have 'commit_container' with correct uername/reponame in yml file. I have the docker hub integration turned on for this specific account. Also, I tried deleting and adding the Docker account to make sure the password is correct.

**Comment by patelsan** [comment]
Any inputs on this?

**Comment by manishas** [comment]
@patelsan can you share your shippable.yml?

**Comment by patelsan** [comment]
# language setting
language: node_js

# Running npm test to run your test cases
script:
 - npm test

commit_container: patelsan/brainiacapp

**Comment by manishas** [comment]
@patelsan do you have write access to the docker hub repo you're pushing to?

**Comment by patelsan** [comment]
Yes, I am using the primary and only account which is owner of this private repo.

**Comment by manishas** [comment]
@patelsan we are getting an error from docker hub, and i don't think there is anything we can do to address it :(

**Comment by manishas** [comment]
i know you checked your credentials, but at this point, i can only guess that something about the creds is being rejected by DH.

**Comment by patelsan** [comment]
Is this working for other users?

**Comment by manishas** [comment]
Yes.

**Comment by manishas** [comment]
@patelsan did this ever work for you? I am closing out the issue since this was an issue with Docker Hub rejecting creds. Please let me know if we can help with anything else.
