### ISSUE TITLE
coverage: highlighted source code

### ISSUE THREAD

**Issue by jamestalmage** [Shippable/support#1290]
In Jenkins, the cobertura coverage output includes highlighted version of the source-code that allows you to easily see which lines are not covered. Using basically the same build process in Shippable (i.e. same result.xml file) - I am seeing basic coverage information information for each file, but no highlighted sources.

Is this a feature that Shippable does not support, or am I doing something wrong?

**Comment by manishas** [comment]
We do not support this as of now, so have tagged this a feature request. Thanks!
