### ISSUE TITLE
Continuous Deployment to Heroku not working

### ISSUE THREAD

**Issue by jonmer85** [Shippable/support#1291]
Hello,
My builds have started failing when deploying to Heroku.

The output I see is as follows:

test -f ~/.ssh/id_rsa.heroku || ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.heroku && heroku keys:add ~/.ssh/id_rsa.heroku
Heroku Toolbelt requires Ruby 1.9+.
Build completed
Skipping artifact upload
Build completed

The build is at https://app.shippable.com/builds/5525ed185cb2750c00d89bfc

I see that others have posted similar issues but I am still having the issue when trying their suggestions.

**Comment by manishas** [comment]
@jonmer85 we tried our build sample and it is working fine, so we will need to look into this a bit more.

Can you share your shippable.yml?

**Comment by jonmer85** [comment]
Sure, I have removed the secure sections:

language: python

python:
  - 2.7
addons:
  firefox: "27.0"

env:
  global:
    - secure: <secure stuff>
    - secure: <secure stuff>
    - DISPLAY=:99.0

before_install:
  - which heroku || wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

install:
  - pip install -r requirements.txt

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
#  - mysql -e 'create database test;'
  - /etc/init.d/xvfb start

script:
  - ./initDataNoInput lettuce_tests
  - coverage run --source='Tinville,basket,common,designer_shop,extensions,custom_oscar.apps.catalogue,custom_oscar.apps.checkout,custom_oscar.apps.customer,custom_oscar.apps.order,custom_oscar.apps.dashboard,user' manage.py harvest --with-xunit --xunit-file=shippable/testresults/lettucetests.xml --settings=Tinville.settings.lettuce_tests
  - coverage xml -o shippable/codecoverage/coverage_lettuce.xml
  - coverage run --source='Tinville,basket,common,designer_shop,extensions,custom_oscar.apps.catalogue,custom_oscar.apps.checkout,custom_oscar.apps.customer,custom_oscar.apps.order,custom_oscar.apps.dashboard,user' manage.py test --with-xunit --xunit-file=shippable/testresults/unittests.xml --settings=Tinville.settings.unit_tests
  - coverage xml -o shippable/codecoverage/coverage_unittests.xml

after_script:
  - /etc/init.d/xvfb stop

after_success :
  - echo $BRANCH
  - test -f ~/.ssh/id_rsa.heroku || ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.heroku && heroku keys:add ~/.ssh/id_rsa.heroku
  - ./deploy.sh

**Comment by jonmer85** [comment]
This is the line the seems to fail "test -f ~/.ssh/id_rsa.heroku || ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.heroku && heroku keys:add ~/.ssh/id_rsa.heroku"

**Comment by manishas** [comment]
@jonmer85 we suspect this is happening because the language set in the yml is python, so the right version of Ruby isn't being invoked.

Can you try the following suggestion -
Use rvm to switch to the supported ruby version and then run the commands. So, add the following line to the `before_install` section : 
```. $HOME/.rvm/scripts/rvm && rvm use ruby-2.0.0-p598 --default && ruby --version```

The heroku push will use ruby 2.0 later in the script

**Comment by jonmer85** [comment]
@manishas It seems to work now :) Thanks for your swift assistance!

**Comment by manishas** [comment]
Glad it worked! Closing.
