### ISSUE TITLE
Permission denied with dedicated hosts

### ISSUE THREAD

**Issue by fakewaffle** [Shippable/support#1295]
Using the Docker build on dedicated hosts I get a permission denied error:

```
Boot ✗
Checking Image user-service:dev.2.1
[Errno 13] Permission denied: '/home/shippable/builds/55123a955ab6cc1352aa323d/2.1': Traceback (most recent call last):
File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
self.execute_step(build_plan, current_step, False)
File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
raise e
OSError: [Errno 13] Permission denied: '/home/shippable/builds/55123a955ab6cc1352aa323d/2.1'
```

See also #1271.

**Comment by manishas** [comment]
@fakewaffle can you try running a build again? We had a service disruption for a few minutes and I suspect you might have hit it.

**Comment by fakewaffle** [comment]
Seems like that was it. Thanks.

**Comment by manishas** [comment]
Great! 
Closing this issue.

**Comment by fakewaffle** [comment]
I'm getting it again...

**Comment by manishas** [comment]
we're looking into this...

**Comment by aaronjudd** [comment]
I'm also getting the same error on a new build with a dedicated host:
```
 Checking Image ongoworks/reaction:development.1
[Errno 1] Operation not permitted: '/home/shippable/builds/55233af95ab6cc1352ba19b5/1.1': Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
OSError: [Errno 1] Operation not permitted: '/home/shippable/builds/55233af95ab6cc1352ba19b5/1.1'

  purge
 Container
container UBL_cf070bed-7894-46c1-9471-2fdc9adf7b28 purged
```

**Comment by avinci** [comment]
we found a problem with the docker build. We are working on fixing this ASAP. Please stay tuned and I am sorry for the inconvenience...

**Comment by fakewaffle** [comment]
Any updates on this? Thank you :)

**Comment by manishas** [comment]
@fakewaffle we have a temporary fix in place but we will need to delete your project on our backend and then you can enable it again (just deleting from the UI won't work). A more permanent fix is coming up in the next couple of days, but this intermittent step will unblock you.

Can you send us the repo name and we will delete it from our system?

**Comment by manishas** [comment]
@aaronjudd we can do the same for your project as mentioned in my comment above. Can you share your repo name? Thanks!

**Comment by fakewaffle** [comment]
@manishas you can delete all repos associated with *School-Improvement-Network*. Let me know when I can start testing again. Thanks!

**Comment by aaronjudd** [comment]
@manishas thanks, I've deleted the repo, I will test again later.

**Comment by fakewaffle** [comment]
@manishas Did you delete the repos?

**Comment by manishas** [comment]
@fakewaffle sorry for the delay in responding. Yes, we've deleted all repos on the backend.

**Comment by manishas** [comment]
Closing since there is no action item for us.. @fakewaffle let me know if you need anything else.
