### ISSUE TITLE
Shippable website interface suggestions

### ISSUE THREAD

**Issue by lavalamp** [Shippable/support#1296]
Bug report:

When I click through to a shippable build like (this one)[https://app.shippable.com/builds/55285aba892aba0c00bd6793], it often (50% of the time?) reloads the page after it's about half loaded. This is very annoying because I've often clicked on the second build, and when it reloads, it shows the first build.

Feature request:

If there's two builds and one succeeded and one failed, please just default to showing the failed one. I never care about the succeeded one! :)

**Comment by manishas** [comment]
UI has been redesigned and this should no longer happen. Let us know if you have any other UI suggestions :)
