### ISSUE TITLE
Dedicated intitalises but hangs on deploy set up.

### ISSUE THREAD

**Issue by pmd500** [Shippable/support#1297]
So I would like to set up a dedicated server however it currently hangs once I set up the deployment. 

I see this in the init log:
Script file created: /tmp/3cb1e49c-dc93-4c76-8b3e-cab05564229c.sh
sending incremental file list 3cb1e49c-dc93-4c76-8b3e-cab05564229c.sh sent 1,106 bytes received 35 bytes 456.40 bytes/sec total size is 2,118 speedup is 1.86
executing script file

Deploy log:
Always empty

Thanks in advance
Phil

**Comment by pmd500** [comment]
It no longer initiliazes for me, this is the log now:

Swap space available, not adding
Checking fstab entries
/etc/fstab updated, swap check complete
Swap add script completed
Writing key to file
mode of '/tmp/d55ab352-5978-4aae-8b81-8337a136b8e2.rsa' changed from 0644 (rw-r--r--) to 0600 (rw-------)
KEY file created: /tmp/d55ab352-5978-4aae-8b81-8337a136b8e2.rsa
Writing script to file
Script file created: /tmp/d55ab352-5978-4aae-8b81-8337a136b8e2.sh
sending incremental file list d55ab352-5978-4aae-8b81-8337a136b8e2.sh sent 1,108 bytes received 35 bytes 457.20 bytes/sec total size is 2,118 speedup is 1.85
executing script file
Repository shipimg/ndq already being pulled by another client. Waiting.
Command timed out
Command thread timed out
Command timed out
Command thread timed out

**Comment by manishas** [comment]
@pmd500 are you still running into this?

**Comment by sklose** [comment]
I have a similar issue, when I click on 'Initialize' for a new dedicated host it says 'Node XYZ queued for initialization' but nothing happens. The initialization log remains empty. I followed the same steps a couple of days ago and it was working fine.

The reason I am setting up my dedicated host from scratch is: I installed updates on my Ubuntu machine and restarted it. After the restart none of the shippable docker images were running though and deploying from the shippable website didn't help either. This might be another (unrelated) bug ... I think the docker containers should automatically restart when the machine is rebooted.

**Comment by manishas** [comment]
We have discovered an issue that was introduced in the dedicated hosts initialization. We're working on a fix and will let you know as soon as it's available. Thanks!

**Comment by ragsden** [comment]
@sklose : We have fixed the issue and now you should be able to run builds on your host. Sorry for the inconvenience.
Please let me know if you have questions. Thanks.

**Comment by manishas** [comment]
Closing this issue since it was addressed.
