### ISSUE TITLE
docker pull fails

### ISSUE THREAD

**Issue by kkarski** [Shippable/support#1298]
I just upgraded to paid account and added a dedicated node. The next build I tried to do I got the following error. Not sure if related:

HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=latest&fromImage=shippable%2Fminv2 (Caused by <class 'socket.error'>: [Errno 111] Connection refused): Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=latest&fromImage=shippable%2Fminv2 (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

**Comment by kkarski** [comment]
FYI... This is for account appcrossings.

**Comment by manishas** [comment]
i've reported this to engineering and they will take a look. I will update you as soon as I know what's going on.

**Comment by kkarski** [comment]
Any update on this? I can't do any builds in my account since Friday last week. I'm completely blocked.

**Comment by manishas** [comment]
Sorry for the delay. I will make sure this is prioritized.

**Comment by manishas** [comment]
@kkarski can you look at the workaround mentioned in https://github.com/Shippable/support/issues/1196

Does that work for you?

**Comment by kkarski** [comment]
So, am I forced to have dedicated hosts with a paid account? I removed my
dedicated hosts and attempted to build again and get the same error.
Shouldn't that scenario use your infrastructure? Does a paid account mean I
no longer get to build on your machines?

KK

**Comment by manishas** [comment]
@kkarski A paid account comes with 2 things -
- 5 build minions on our multi-tenant platform. Custom docker images are not supported on this because of security issues. However, you can start with an image from our public repo shippableImages and customize with shippable.yml and then cache the container. You can use this image on our multi-tenant platform.
- Access to dedicated hosts beta. This means you can attach your build host to your org and all builds for that org will run on your own host. Custom images and dockerbuild is supported on this platform.

**Comment by kkarski** [comment]
I have no interest in using custom build images. All I want to do is to
execute a docker build to create and push a production docker image to my
private repo. From the documentation it seemed I can only do docker builds
if I use a dedicated hosts, that's why I hooked up this host.

However, if I can build a docker images and push it to my private docker
hub from your multi tenant infrastructure, then that's all I need.

KK

**Comment by manishas** [comment]
Your scenario of building a docker image and pushing to private docker hub is available today with dedicated hosts.

Docs are here - http://docs.shippable.com/en/latest/docker_build.html#docker-build-support

**Comment by kkarski** [comment]
OK, so I have made the post changes on my host and bounced docker. I just
kicked off another build and I am "Waiting" and 1 minion in use. Why am I
in waiting mode when I have my own dedicated host?

**Comment by kkarski** [comment]
OK....it waited until it timed out. I don't have any error logs or anything
to go on.

KK

On Thu, Apr 16, 2015 at 10:33 AM, Krzysztof Karski <kkarski@conteligence.com

**Comment by manishas** [comment]
we're taking a look and will update soon.

**Comment by kkarski** [comment]
Retried build in the afternoon. Actually started processing this time but got this error:

Error downloading dependent layers, 
Error pulling image (latest) from shippable/minv2, endpoint: https://registry-1.docker.io/v1/, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device, 
Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device, 
Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
Exception: Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device

I checked the space on my host:
Filesystem                   Size  Used Avail Use% Mounted on
/dev/mapper/ubuntu--vg-root  227G   36G  181G  17% /
none                         4.0K     0  4.0K   0% /sys/fs/cgroup
udev                         3.8G   12K  3.8G   1% /dev
tmpfs                        777M  1.3M  775M   1% /run
none                         5.0M     0  5.0M   0% /run/lock
none                         3.8G   14M  3.8G   1% /run/shm
none                         100M   64K  100M   1% /run/user
/dev/sda1                    236M  128M   96M  58% /boot

I should have plenty left.

**Comment by kkarski** [comment]
OK, closing this issue since the above mentioed work-around worked with changing the docker port. Have opened the space issue as a new ticket.
