### ISSUE TITLE
docker build-image vs production-image

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1299]
Docker build-image vs production-image
=============================================

Let me start by saying that I don't really care about  docker build-image as long it creates a build artifact (war file) for me. The shippable/minv2 is doing all I need. 

However, I do greatly care about my production docker image. With the current documentation in shippable-docs, it is hard to figure out difference between the build image vs production image. 

Another confusing thing is source code path, as mentioned in http://blog.shippable.com/making-deployments-even-easier-with-docker-build. Shippable pulls the git code and builds it then why is it asking for src folder. Shouldn't the Dockerfile take care of everything. All Dockerfile cares, should be relative to Dockerfile's location. In my case my  Dockerfile doesn't want to know about java source, it should just take my war file (generated by build at target/blah-blah.war), throw it in tomcat webapps folder(as described in Dockerfile) and generate a named/versioned image.

In essence all I need is the shippable builds my code and post build, run the following commands --
docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
docker build -t hshira/hello-docker:$BUILD_NUM .
docker build -t hshira/hello-docker:latest .
docker push hshira/hello-docker:$BUILD_NUM
docker push hshira/hello-docker:latest

I also have a circle.yml which does this very easily, I want to be able to this using shippable.yml
Here is the hell-docker project that I am trying to build and push to dockerhub --
https://bitbucket.org/hshira/hello-docker/src

Please help me write the shippable.yml to do this.

**Comment by manishas** [comment]
@hshira I can ask our engineers to help with the yml, but let me confirm I understand the scenario.

You want shippable to pull your code for the hell0_docker repo for every commit and build it on minv2.  Then, if CI passes, you want us to create your prod image by running Dockerbuild using the Dockerfile in your repo and push this image to your Docker hub. 

Is my understanding correct?

**Comment by manishas** [comment]
http://docs.shippable.com/en/latest/docker_build.html#docker-build-support

**Comment by hshira** [comment]
Yes, your understanding is right.

**Comment by sklose** [comment]
I agree with hshira, the current Docker build process is very confusing and not well documented. I am trying to do pretty much the same thing, execute these three commands:

- ./build.sh publish
- docker build -t quay.io/xyz/abc .
- docker push quay.io/xyz/abc

The build.sh produces some artifacts which are picked up by the Dockerfile. If you could provide an example for this kind of scenario in the documentation that would be great.

The Dockerfile looks like this:
```
FROM microsoft/aspnet:nightly

ENV DNX_APPBASE_PACKAGE XYZ
ENV DNX_APPBASE_VERSION 1.0.0

ADD ./run.sh /app/run.sh
COPY ./artifacts/publish /app
WORKDIR /app

CMD /app/run.sh
```

**Comment by kkarski** [comment]
I'd also like to upvote this issue. I too only care about my production docker build and use the minv2 image for build. I too find the documentation very confusing. 

I have yet to build a docker image but my hope was that if the dockerfile is at the root of my project, and I build the artifacts into target (using java and maven), then I can just put "ADD /target/artifact-1.0.0-SNAPTSHOT.jar ...etc" in my dockerfile. Once the image is build, I want it pushed to my private hub repo.

**Comment by manishas** [comment]
@hshira @sklose @kkarski sorry for the unclear docs for build artifacts for post CI dockerbuild. we will clean that up.

In the meantime, here is how you can get your artifacts in your prod image -

* In your shippable.yml, add the following to before_script section -
```
  - mkdir -p shippable/buildoutput
```
* Copy whatever you need on your prod image to this directory in the after_script section -
```
- cp <artifacts> ./shippable/buildoutput
```
* You can now access this folder in your Dockerfile and add whatever you need to your prod image using ADD

Please let me know if this helps.

**Comment by manishas** [comment]
@hshira for your scenario, here is what you would do -

- Connect your docker hub account to Shippable by clicking on this button on your org page on Shippable -
![screen shot 2015-04-14 at 1 27 42 pm](https://cloud.githubusercontent.com/assets/2983749/7146665/0f884dca-e2aa-11e4-9cac-aaa6ec9bea3d.png)

- Have the Dockerfile for your prod image at the root of your repo

- Enable the repository on Shippable

- On the repo page in Shippable, go to 'Settings'
    * Choose the following -
    * Build image : Custom Image
    * Custom image action : Build
    * Custom image name : (docker hub username)/(image name)
    * Source code path : (source code path for image you want to build)
    * Docker build when finished : Check
    * Image to pull: Specify image you want to run tests on, default is shippable/minv2
    * Push to Docker Hub : Check

- Run a build. 

At this point, we will run CI on shippable/minv2. When finished, if CI passes, we will do dockerbuild for the Dockerfile in your repo and push to docker hub with the tag (image name).(latest build number)

You can copy artifacts from the CI step to your prod docker image using the steps outlined in the previous comment. 

Please let me know if this works.

**Comment by sklose** [comment]
Thanks for the clarification @manishas. Are there yml equivalents for all the settings I see in the UI (custom image action, custom image name, ...)? I don't like having my configuration in multiple places ...

One other followup question: you said the Dockerfile can access everything in shippable/buildoutput with ADD statements. Do I have to use a path prefix or do they appear as if in the current working directory? Example
```
after_script:
  - cp artifact.xyz ./shippable/buildoutput
```
```
FROM ubuntu
ADD ./artifact.xyz
ADD ./shippable/buildoutput/artifact.xyz
```

Which of the ADD statements is correct?

**Comment by manishas** [comment]
@sklose ```ADD ./shippable/buildoutput/artifact.xyz``` is correct.

**Comment by ragsden** [comment]
@sklose : Sorry about the confusion. Once the artifacts specified in the after_script section of the CI is copied to shippable/buildoutput folder a new docker container is spawned to build the production docker image. This new container will git clone the repo again to get access to the Dockerfile and the buildoutput folder is then copied to the repo source code location. So, all you have to to in you docker file is to add the following

FROM ubuntu
ADD ./buildoutput/artifact.xyz

We spin off a new container because the container has to run in privileged mode to perform docker build.

Please let me know if you have any questions.

**Comment by sklose** [comment]
thanks for the clarification @ragsden, the workflow is much clearer now. I don't like that the directory name is hard coded to ./shippable/buildoutput though. So far all integration with shippable is nicely contained within the shippable.yml file, forcing my Dockerimage to use that directory makes shippable 'leak' into my actual application. Have you guys considered something like this?

```
after_script:
  - cp artifact shippable/buildoutput

before_docker:
  - cp shippable/buildoutput artifact
```

This might also help with the fact that I can't push to my private quay.io repository right now, I could do something like this then:

```
after_script:
  - cp artifact shippable/buildoutput

before_docker:
  - cp shippable/buildoutput artifact
  - cp .dockercfg /home/shippable/.dockercfg
```

**Comment by hshira** [comment]
It is still not working for me.

Here is my [Dockerfile](https://bitbucket.org/hshira/hello-docker/raw/8e4e51edbcad3473ab030d01179216fb3297eb0f/Dockerfile)

Here is my [shippable.yml](https://bitbucket.org/hshira/hello-docker/raw/8e4e51edbcad3473ab030d01179216fb3297eb0f/shippable.yml)

docker build fails while executing Step 2 --

Step 2 : ADD ./shippable/buildoutput/app.war /tomcat/webapps/ROOT.war
time="2015-04-15T03:21:34Z" level="info" msg="shippable/buildoutput/app.war: no such file or directory" 


Not sure why it is not able to find ./shippable/buildoutput/app.war

**Comment by manishas** [comment]
@hshira I am now trying out your scenario and will update you soon.

**Comment by ragsden** [comment]
@hshira You should replace ADD ./shippable/buildoutput/app.war /tomcat/webapps/ROOT.war
with ADD ./buildoutput/app.war /tomcat/webapps/ROOT.war
Let me know if this works. Thanks

**Comment by hshira** [comment]
@ragsden I made the change and it still fails. Just the error message changed to -- "buildoutput/app.war: no such file or directory" 

![screen shot 2015-04-15 at 8 44 49 am](https://cloud.githubusercontent.com/assets/1060991/7160051/49df55a2-e34c-11e4-9115-0c3f7f2e5aa5.png)

The mvn build does copy app.war to shippable/buildoutput as shown in the following screenshot, but the docker build, somehow is not able to find it.

![screen shot 2015-04-15 at 8 45 31 am](https://cloud.githubusercontent.com/assets/1060991/7160069/6c867a04-e34c-11e4-9338-65e52f47c0fd.png)

If I remove the ADD line, docker build and push works fine and pushes the image without my artifact into dockerhub. So, the problem is that the file is unavailable. 
Is the shippable/buildoutput being cleaned up before running docker build?

**Comment by hshira** [comment]
Another observation,  the after_script copies the file to the following location --

    /root/workspace/src/bitbucket.com/hshira/hello-docker/shippable/buildoutput/app.war

git clone again checks out the code at same location, and ovewrites it. 

    rm -rf /root/workspace/src/bitbucket.com/hshira/hello-docker/shippable

I am not sure how docker build can find the artifact.

**Comment by manishas** [comment]
@hshira can you try your builds now? It should work as expected.

**Comment by hshira** [comment]
Works now. Thanks!

**Comment by manishas** [comment]
Thanks for confirming! Closing this issue.

**Comment by dlckl** [comment]
Can you guide me where to place after_script section in the latest yaml build configuration file? The document: http://docs.shippable.com/ci_configure/ doesnt reflect the same. 

Thanks.

**Comment by chetantarale** [comment]
@dlckl In the new yml configuration you have to use `post_ci` section. so any commands you would write in `after_script` section should now be in  `post_ci`. Also depending on weather your `ci` passes or no you can also write your command under `on_success` or `on_failure`.

**Comment by manishas** [comment]
@dickl our yml migration blog will help you understand the relationship between old and new sections - http://blog.shippable.com/migrating-to-the-new-build-platform
