### ISSUE TITLE
[BUG] Docker push show error "Skipping push because commit was not successful or skipped."

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#1300]
```bash
...
docker push:
 -Docker login Docker login successful for user XYZ
 -pushing image:
     Skipping push because commit was not successful or skipped.
...
```
[build_with_error](https://app.shippable.com/builds/5529dbf58f66be0c006409ef)

I saw this error in all our builds

**Comment by manishas** [comment]
@moylop260 are you trying to push the image to docker hub? If no, you can ignore this message. If yes, can you follow instructions at http://docs.shippable.com/en/latest/config.html#docker-hub ? I suspect you might be missing the commit_container tag in your shippable.yml

**Comment by ragsden** [comment]
@moylop260 : We push to docker registry only for git commits and not pull requests to the "main" branch.
The build you have referenced was a pull request build and hence the image was not pushed. The next build which ran was commit build on the destination branch and hence you can see the image was pushed to your docker repository. 
I see that message is not very intuitive and we will take care of that. Let me know if you have any questions.

**Comment by moylop260** [comment]
Ok I got it
Thank for you reply.
Can I activate docker push from pr?

**Comment by ragsden** [comment]
A PR results in two builds, one when the PR is open and the second when the PR is merged which results to a commit build in the destination branch. The commit results in a docker push. Hence merging the PR will eventually result in a docker push. Will this satisfy your requirement?

**Comment by moylop260** [comment]
Hello @ragsden 
Thanks for reply.

I have some errors in a build of PR but I don't have this error in my environment local.
It is very useful have the option of download the environment with error. (We can't merge a pr with errores).
Then I'm without a option of merging and without option of download the environment with error.

**Comment by manishas** [comment]
I am closing this issue since the original qs was answered. Please open a new feature request for the follow up suggestion.
