### ISSUE TITLE
High amount (almost 50%) of builds are getting stuck on "Waiting for mongodb to start..."

### ISSUE THREAD

**Issue by DanielLevin** [Shippable/support#1301]
This is the reopen for issue #1119

**Comment by manishas** [comment]
we'll take a look at this.

**Comment by manishas** [comment]
@DanielLevin do you still see this? We've pushed some changes to our build workflow and it should have helped with your timeouts.

**Comment by lekhab** [comment]
Assuming this is no longer an issue. Closing - please feel free to re-open if you are still facing this.
