### ISSUE TITLE
Apache HBase standalone version for integration tests

### ISSUE THREAD

**Issue by reddy6ue** [Shippable/support#1302]
Shippable already supports Cassandra and Couchbase. Can you please add a local standalone HBase database option too?

I don't think it's currently supported.

**Comment by manishas** [comment]
@reddy6ue you're right, we do not support HBase out of the box. You can always install it in your shippable.yml and it will be available for your build. 

Our default image is pretty bloated so we're cautious about adding more stuff to it unless there are a lot of +1s. I will close this issue for now, but if multiple customers want this, we will definitely reconsider.

Thanks!

**Comment by reddy6ue** [comment]
@manishas I guess I'll have to build my own Dockerfile. Not too much of  a problem. I'll post it here when I am done.
