### ISSUE TITLE
Build failing with no errors

### ISSUE THREAD

**Issue by og3b** [Shippable/support#1303]
I'm getting intermittent build failures (it times out after 2 hours) but there are no errors. We use dedicated hosts with a custom docker image. Every stage in the build has a green tick next to it, but the stages 'docker push' and 'purge' are missing from the failed build.

Here's an example of a failed build:
https://app.shippable.com/builds/552adde88f66be0c00640dce
This is the re-run which succeeded. 
https://app.shippable.com/builds/552b808e6206490c00972768
It looks like the step 'docker push' never runs in the failed build.

Is there any way to see what's going wrong?

thanks

Enabled by github/cage433

.shippable.yml

	language: scala
	jdk:
	  - oraclejdk8
	scala:
	  - 2.11.5
	sudo: false
	cache:
	  directories:
		- $HOME/.ivy2/cache
	script:
	  - sbt -Djline.terminal=jline.UnsupportedTerminal ++$TRAVIS_SCALA_VERSION -J-XX:+CMSClassUnloadingEnabled -J-XX:PermSize=512M -J-XX:MaxPermSize=1024M clean test && ./check.rb

check.rb

	#!/usr/bin/env ruby

	require 'logger'
	require 'date'

	$stdout.sync = true
	$stderr.sync = true

	$logger = Logger.new($stdout)
	$logger.formatter = proc do |severity, datetime, progname, msg|
	  "#{datetime}: #{severity} - #{msg}\n"
	end

	class Checks

	  def Checks.no_new_files_after_tests_have_run
		if `git status --short | wc -l`.to_i > 0
		  $logger.error("Some artifacts left after tests have run: #{`git status`}")
		  return false
		end
		return true
	  end

	  def Checks.check_all
		no_new_files_after_tests_have_run 
	  end
	end

	if Checks.check_all
	  $logger.info("Check completed successfully")
	else
	  exit 1
	end

**Comment by og3b** [comment]
Here is another failed build:
https://app.shippable.com/builds/55361edbb9b42c0b00e2b4b7
We cancelled it after 14 minutes. You can see it has finished running our tests fine and it hanging in the clean up part that belongs to shippable. It looks like it finishes everything, including 'Purge', it just doesn't report back and instead keeps running.

Any ideas on what's happening here? Thanks

**Comment by manishas** [comment]
@og3b we deployed a few fixes for this and you shouldn't run into it any more.... are you still seeing this issue?

**Comment by og3b** [comment]
@manishas We haven't seen it in over a week. Is there anything I need to do to get these fixes you mention? Or is rolled out to our dedicated host automatically? Thanks

**Comment by manishas** [comment]
We rolled these out to all dedicated hosts, so you should have them.

**Comment by manishas** [comment]
Closing this issue. Please re-open if you run into it again.

**Comment by og3b** [comment]
@manishas we're running into it again. see here:
https://app.shippable.com/builds/5565e059d88a130e00216ad4
It seems to have only completed the 'pull' stage. Another build running at the same time completed fine (#214).
Here's another two in case it helps:
https://app.shippable.com/builds/5560b7eed88a130e0021294e
https://app.shippable.com/builds/55587347591ea70b00b5fd48

**Comment by og3b** [comment]
@manishas unfortunately I can't reopen this issue as you have closed it and that means I don't have the permission to open it. Could you please reopen it?
