### ISSUE TITLE
curl: (22) The requested URL returned error: 404

### ISSUE THREAD

**Issue by kaspernj** [Shippable/support#1304]
Please see 35.4 on this build:
https://app.shippable.com/builds/552b9ba96206490c00972945

I am getting those errors randomly very often.

"shippable.yml" and all other files are available from the public repository.

**Comment by kaspernj** [comment]
Got another one here:
https://app.shippable.com/builds/55362780b9b42c0b00e2b59f

**Comment by lekhab** [comment]
@kaspernj: are you still running into this?
