### ISSUE TITLE
Shippable is spamming me when I didn't sign up

### ISSUE THREAD

**Issue by drbrain** [Shippable/support#1306]
Steps to reproduce:

1. ?

Expected results:

No spam

Actual results:

Spam in my inbox:

![rake update readme rdoc on shippable com inbox 2015-04-13 18-01-30](https://cloud.githubusercontent.com/assets/9831/7128513/0d160098-e208-11e4-8c28-17b26f281298.png)

**Comment by manishas** [comment]
@drbrain as we explained on twitter, this was because your email address was hardcoded in the .travis.yml and it wasn't removed in the fork. We have requested for it to be removed so you will not see emails any more. 

Thanks!

**Comment by manishas** [comment]
@drbrain I hope you haven't seen any new notifications today. Thanks!

**Comment by manishas** [comment]
Closing. @drbrain let us know if you see any more notifications.

**Comment by dentarg** [comment]
Seems like you are still doing this. You received "Shippable Newsletter May 18, 2016" out of the blue. I never signed up for anything. I'm baffled.

**Comment by abhijitkini** [comment]
@dentarg we have removed your email address (*****k@st*****t.net) from our system. We have included the "unsubscribe from all future emails" in the newsletter to self-serve.

Let us know if you see any more notification from us.

**Comment by dentarg** [comment]
Thanks, but how did I end up in your system at the first place?

**Comment by manishas** [comment]
We need to investigate this. 

We sent the newsletter to folks on our subscribers list and to current customers.

**Comment by manishas** [comment]
Subscribers list is people who have expressed interest in shippable including people we talk to at conferences etc. anyway we're looking into this.

**Comment by dentarg** [comment]
Great.
