### ISSUE TITLE
Shippable is dead - Internal server error

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1307]
Nobody in here at @ContaAzul can access anything on Shippable anymore...

We keep getting "Internal Server" errors... jobs won't appear nor build...

Can you please fix that?

![screenshot from 2015-04-14 14 04 27](https://cloud.githubusercontent.com/assets/245435/7142478/3626f18e-e2af-11e4-8c0d-4dedf4a86f0e.png)

Cheers

**Comment by manishas** [comment]
@caarlos0 we're taking a look and will update as soon as we bring everything up again.

**Comment by caarlos0** [comment]
It shows that the public and private repos are off, but, when I try to enable them, I got Internel server error too.

**Comment by caarlos0** [comment]
@manishas OK!

**Comment by bittner** [comment]
@caarlos0 Re "Can you please fix that": Sorry in advance if I put my nose into things that are none of my concern, but: I'd love to see if we all would be a little bit more polite.

Shippable is free for most users here, or costs just very little money. I strongly believe the guys behind this great service will stay awesomely motivated if we all stop yelling for every single little hick-up. (I've noticed this kind of communication tone in other threads / issues, too.)

Sorry if I'm too direct. I don't mean to be rude. Thank you for your understanding.

**Comment by caarlos0** [comment]
@bittner Sorry, english is not my native language, I didn't meant to be rude either.

**Comment by manishas** [comment]
@caarlos0 everything should be back up now. MongoDB was running out of space and we have addressed the issue.

@bittner appreciate the kind words :)

**Comment by bbradbury** [comment]
Thanks Shippable team for the quick fix!

**Comment by caarlos0** [comment]
Many thanks Shippable team! Seems to be working now!

Cheers :beers:

**Comment by andersonborges** [comment]
Hi @bittner, I'm sorry but I didn't see anything rude about @caarlos0 communication. ("Can you please fix that?").
There are moments where be "too direct" as you said is necessary.
As a startup leader, I also have clients that are rude but also clients that understand things don't always goes right and they help us a lot when they are direct to the point, showing us their urgency (Sometimes they need to issue a eletronic invoice and depends on our app), as was this case.

Help me understand, what words would be better for such communication? What do you expect?

Thanks!
