### ISSUE TITLE
https://app.shippable.com gives error 500

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1309]
Since this morning I am not able to use shippable because it gives an internal server error (500) after logging in. If I look at the debugger of my browser I see that api.shippable.com/accounts gives this error.

**Comment by hranicka** [comment]
I have the same problem.

When I sign-in with BitBucket, I get `Internal server error` buble in the right bottom corner.

When I try sign-in with GitHub, I get message `Error: Unexpected response from API exchange at _exchangeTokenResponseHandler (/home/shippable/fe/common/githubStrategy.js:79:13) at Request._callback (/home/shippable/fe/views/index/exchangeToken.js:37:21) at self.callback (/home/shippable/fe/node_modules/request/request.js:368:22) at Request.emit (events.js:95:17) at Request.onRequestError (/home/shippable/fe/node_modules/request/request.js:1025:8) at ClientRequest.emit (events.js:95:17) at CleartextStream.socketCloseListener (http.js:1526:9) at CleartextStream.emit (events.js:117:20) at tls.js:693:10 at process._tickCallback (node.js:419:13)`

**Comment by phagunbaya** [comment]
Same problem. Happening since afternoon (PST)

![screen shot 2015-04-15 at 12 09 47 pm](https://cloud.githubusercontent.com/assets/1146297/7153466/9c068086-e369-11e4-81a6-e376924814c6.png)

**Comment by manishas** [comment]
:( sorry about this. We're looking into it.

**Comment by manishas** [comment]
everything is back up now... we'll watch very closely and this will be addressed soon. Thanks for your patience!

**Comment by rvdwijngaard** [comment]
yep it is working; thanks for acting quick since this was blocking our ci pipeline.

**Comment by hranicka** [comment]
:+1: Thank you for quickness!

**Comment by manishas** [comment]
Thanks for the patience! Today has been challenging since we ran into Mongodb space issues, but we have it under control now.

**Comment by phagunbaya** [comment]
@manishas : Thanks ! working for me too.

**Comment by manishas** [comment]
Closing.
