### ISSUE TITLE
Build is not building

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1310]
[This build](https://app.shippable.com/builds/552e57ea9f3b170b0086237a) don't work...

It stops in some "infinite loading" and nothing happens... how can I fix that?

Cheers!

**Comment by rageshkrishna** [comment]
Hi, @caarlos0. We've been seeing some timeouts on calls to the Github API. This caused one of our queues to slow down but it's now back to normal. Your builds should have started running now.

**Comment by caarlos0** [comment]
Hi @rageshkrishna!

It is indeed working now! 


Many thanks! :beers:
