### ISSUE TITLE
Failing on Install part of build

### ISSUE THREAD

**Issue by sojharo** [Shippable/support#1313]
Shippable sometimes fails to pull the libraries during the build process. After this, I go to the shippable website and run the build manually from there and then it gives no error.

![shippable](https://cloud.githubusercontent.com/assets/5811465/7176266/44244592-e436-11e4-8f42-1bb5dc7afb78.PNG)

**Comment by manishas** [comment]
@sojharo how often does this happen? Can you share your shippable.yml?

**Comment by sojharo** [comment]
This did not happen before, now it happens after every other commit.

This is how my .travis.yml file looks like:

language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - bower install
services: mongodb
notifications:
     email:
         recipients:
             - email1@email.com
             - email2@email.com
         on_success: change
         on_failure: always

**Comment by manishas** [comment]
closing this since it's an old issue. please let us know if you still need help with this.
