### ISSUE TITLE
NPM Installs fail

### ISSUE THREAD

**Issue by mustela** [Shippable/support#1314]
This is not the first time it happens, we have this issue at least 2 or 3 times per week 

The problem seems to be when trying to run `npm install grunt grunt-cli karma karma-cli bower`

```
npm ERR! EEXIST, open '/home/shippable/.npm/98196386-ble-npm-lodash-2-4-1-package-tgz.lock'
File exists: /home/shippable/.npm/98196386-ble-npm-lodash-2-4-1-package-tgz.lock
Move it away, and try again. 

npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "grunt" "grunt-cli" "karma" "karma-cli" "bower"
npm ERR! cwd /home/shippable/workspace/src/github.com/packethost/portal
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /home/shippable/.npm/98196386-ble-npm-lodash-2-4-1-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0
```

https://app.shippable.com/builds/552fd3f731d6ed0c0026f791

**Comment by bobeagan** [comment]
Old version of npm that needs to be updated. See https://github.com/npm/npm/issues/6309  
Causing problems for me on several projects, too.

**Comment by manishas** [comment]
There is a workaround for this npm issue in this thread - https://github.com/Shippable/support/issues/713

You will need to update your YML file to include the following:
````
before_install:
  - npm install -g npm@next
````

Let me know if this works!

**Comment by mustela** [comment]
Thanks @manishas! Updated. Will check a few deploys and close the issue if they run ok.

**Comment by mustela** [comment]
@manishas take a look to the results now:


```
 npm install -g npm@next
npm ERR! Error: EACCES, unlink '/usr/bin/npm'
npm ERR!  { [Error: EACCES, unlink '/usr/bin/npm'] errno: 3, code: 'EACCES', path: '/usr/bin/npm' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "npm@next"
npm ERR! cwd /home/shippable/workspace/src/github.com/packethost/portal
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /usr/bin/npm
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/bin/npm'
npm ERR! error rolling back Error: EACCES, unlink '/usr/bin/npm'
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/bin/npm'] errno: 3, code: 'EACCES', path: '/usr/bin/npm' }
npm ERR! not ok code 0
```

**Comment by manishas** [comment]
@mustela I looked your latest builds and looks like everything is working now.

I am closing this issue, but if you post your solution to the issue you were facing, it will help other folks :)

**Comment by mustela** [comment]
I didn't change anything :), so maybe some change in your end?

**Comment by mustela** [comment]
@manishas it is still happening I just got another one https://app.shippable.com/builds/554bae94ff724e0c00e4e752

Any idea?

**Comment by mberrueta** [comment]
I have the same issue, but randomly 
I included the

  - npm install -g npm@next
  - npm install

and sometimes work, and sometime fails

maybe an issue with internet connection?
