### ISSUE TITLE
In triggerBuild request: Passing a parameter from one build to another

### ISSUE THREAD

**Issue by vkuusk** [Shippable/support#1315]
We are doing chaining of several builds and need to pass "a string value" from one build to the next.
Currently we are using external location (private S3 bucket) to store this value (one build puts there, the next one reads from there).

the data we are transferring is just a small string.

Is it currently possible to pass a key:value pair to the triggerBuild request, so it becomes an environmental variable in the "next" build.

If it's not currently possible, will you consider adding this feature at some point in future?

Thanks

**Comment by manishas** [comment]
We are now working on this so watch for an update in the next couple of days.

**Comment by pranaypareek** [comment]
@vkuusk this feature is live now.

While calling the `newBuild` api end point (`POST /projects/:projectId/newBuild`), you can now inject global environment variables into the new build by specifying key-value pairs in the request body of the POST. These key-value pairs have to be set in the `globalEnv` property.

```
{
  "globalEnv": {
    "FOO": "bar",
    "FIZZ": "buzz"
  }
}
```
http://docs.shippable.com/api/#trigger-a-new-run

Do check this out and let us know if you'd like to see anything else added too. We promise to be much quicker this time :)
