### ISSUE TITLE
post docker push operations

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1317]
I want to deploy my newly created docker image to AWS. It seems the only thing that happens after docker push is purge.

Is there anything like after_docker_push or something like that where I can put my AWS CLI scripts for deploying new docker image?

**Comment by manishas** [comment]
@hshira currently, no. but we're working on addressing this soon.

**Comment by alexanderlamb** [comment]
@manishas has this been addressed yet?  Coincidentally, this was a large part of why we ended up running docker in docker on Shippable.

**Comment by marcospedreiro** [comment]
+1 We would like this feature as well. Any updates about this feature would be great.

**Comment by manishas** [comment]
Closing as DUP of #824 where i'm tracking all requests for docker registry pushes and after push operations.
