### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by kkarski** [Shippable/support#1320]
Downloading, [============================>                      ] 342.8 MB/600.6 MB 18s
Error downloading dependent layers, 
Error pulling image (latest) from shippable/minv2, endpoint: https://registry-1.docker.io/v1/, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device, 
Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device, 
Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device: Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
Exception: Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device

Have plenty of space left on my host:

Filesystem Size Used Avail Use% Mounted on
/dev/xvda 48G 18G 30G 38% /
none 4.0K 0 4.0K 0% /sys/fs/cgroup
devtmpfs 2.0G 4.0K 2.0G 1% /dev
none 401M 240K 400M 1% /run
none 5.0M 0 5.0M 0% /run/lock
none 2.0G 0 2.0G 0% /run/shm
none 100M 0 100M 0% /run/user

**Comment by manishas** [comment]
@kkarski are you still having problems with space on custom hosts. I am closing this issue, but please leave a comment if you are still facing this and i'll reopen.
