### ISSUE TITLE
Update PHP composer version

### ISSUE THREAD

**Issue by claar** [Shippable/support#1321]
The composer version in shippable is from November 2014 (1.0.0-alpha10, hash ffffab3).

This old version doesn't understand current composer syntaxes, such as ^5.2, so I've had to add `composer self-update` to my build script, adding an unnecessary delay in build times and processing work/bandwidth for the build host.

**Comment by manishas** [comment]
@claar you can cache the container to avoid installing each time. Have you tried that?

**Comment by manishas** [comment]
we have updated composer version on php images. the images are available in the [drydock repo](https://hub.docker.com/u/drydock/)

If you update to our new yml format, the correct php image will be pulled automatically.
