### ISSUE TITLE
shippable.yml post success line being parsed strangely

### ISSUE THREAD

**Issue by catskul** [Shippable/support#1322]
A line from my `shippable.yml` appears to being parsed into something odd:
```
curl -X POST -d "{ 'uuid': \'$COMMIT\' }" "$DEPLOYSERVER_URL"
```
shows up in the bash script as:
```
exec_cmd $'[object Object]'
ret=$?
```

Resulting in the following log

```bash
python sprintly_notifier.py --email $SPRINTLY_EMAIL --password $SPRINTLY_PASSWORD --    product_id 23448 --test_results "[SUCCEDED](BUILD_URL)"
[object Object]
    /home/shippable/build/build.sh: line 100: [object: command not found
    Build completed
    Skipping artifact upload
    Build completed
```

I'm guessing it has to do with my escaped single quotes. Attempting work around.

**Comment by catskul** [comment]
Worked around by pushing into separate script file.

**Comment by rvrignaud** [comment]
I have exact same problem. Is there any proper solution for that ?

**Comment by catskul** [comment]
I tried several variations without success. It'd be nice if escaping worked well, but IMO pushing to a separate script is probably the better option.
