### ISSUE TITLE
Private/scoped npm modules not accessible in builds

### ISSUE THREAD

**Issue by pcullin-ratio** [Shippable/support#1323]
npm just released their new "private" modules feature, which we've started using.
https://www.npmjs.com/private-modules

As you can see in the documentation, to access your private modules you have to log in with a user account that has access to the module via `npm login`. The problem is, this is an interactive command...so how can I log in with the proper user in a Shippable build?

**Comment by rageshkrishna** [comment]
It looks like `npm login` doesn't offer any way to work in non-interactive mode. There are a couple of workarounds at http://stackoverflow.com/a/24154126 that you can try. You can couple this with secure environment variables and just generate the `.npmrc` file yourself.

I've used this successfully on a project to push to npm on successful builds. You can check out my YML file [here](https://github.com/rageshkrishna/shippable.js/blob/master/.shippable.yml)

**Comment by manishas** [comment]
Closing this issue. @pcullin-ratio please re-open if it doesn't work for you.
