### ISSUE TITLE
Bundle install times out often

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1326]
We often see the following error recently in our build 
`Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Connection timed out - connect(2) for "bb-m.rubygems.org" port 443 (https://rubygems.org/gems/fastercsv-1.5.5.gem)
An error occurred while installing fastercsv (1.5.5), and Bundler cannot
continue.` (package can differ obviously)

If this happens > 3 times, the build will fail since it didnt get the dependencies. Which requires a rerun (even though another build of the build matrix succeeded) etc. 

Now I'm trying to do just one build at the time (which is actually two due to the build matrix), but in the list below, all the failures are due to one of the two failing to proceed with `bundle install`. The cancelled ones are the ones where one failed, so there was little use in continuing with the other

![screenshot 2015-04-18 17 32 15](https://cloud.githubusercontent.com/assets/2778689/7216053/004138dc-e5f1-11e4-8e57-a52460eb29de.png)

**Comment by rogierslag** [comment]
While typing this issue, 3041 also failed both builds on `bundle install`

**Comment by manishas** [comment]
@rogierslag what is 'source' set to in your Gemfile? I found a few folks online running into similar issues...

http://help.rubygems.org/discussions/problems/17672-gems-not-installing-due-to-timeout
http://help.rubygems.org/discussions/problems/19052-bundle-install-connection-timed-out-error

Our sample uses ```source "https://rubygems.org"```, for example.

**Comment by rogierslag** [comment]
Usung the same here actually. But im moving to a dedicated host now with a custom docker image and it now seems ok (plus its blazingly fast!)

**Comment by manishas** [comment]
Closing this issue. Please let us know if we can help with anything else.
