### ISSUE TITLE
No Support to embed build status badge into github.com project (README.md)?

### ISSUE THREAD

**Issue by syang** [Shippable/support#1327]
I understand that the current shippable.com dashboard shows the build's status badge, but I would like to see my project's status page on my github page. i.e., to embedd the markdown into my README.md file like this http://docs.travis-ci.com/user/status-images/

Currently it does not seem to support it. Or maybe I miss anything? (I am using a free account for now to understand Shippable's capability)

**Comment by manishas** [comment]
You can go to the project page on shippable, click on 'badge' at the right of the page, copy the markdown, and put it in your readme.

**Comment by syang** [comment]
Thanks, got it!

Please mark this as resolved.

**Comment by manishas** [comment]
Glad it worked for you! Closing.
