### ISSUE TITLE
Docker enable other registries

### ISSUE THREAD

**Issue by justjico** [Shippable/support#1329]
Hi,

Is there a way to use other docker registries instead of Docker Hub, for instance Google's gcr.io ?

On dedicated_hosts, it seems I would just need to have a proper .dockercfg on the build image.

**Comment by manishas** [comment]
@jico84 today, we support docker hub. I cannot comment in too much detail on our roadmap but this is certainly on our radar.

**Comment by manishas** [comment]
@justjico GCR is now supported -
http://docs.shippable.com/docker_registries/
https://www.youtube.com/watch?v=VKedeesHirE

I am tracking additional registry requests in #800 so if you're looking for quay.io or private registry support, please follow that issue. That is on our roadmap soon as well.

**Comment by manishas** [comment]
This is now available! You can push and pull images from Quay.io as well as private docker registries.

Check out our docs at http://docs.shippable.com/docker_registries/

Let me know if you have any questions.... feedback much appreciated :)
