### ISSUE TITLE
Booth.sh while building centos docker image

### ISSUE THREAD

**Issue by jico84** [Shippable/support#1330]
Hi,

For a project, I'm building a custom docker image which runs centos. All other steps are fine, except for booth, where it tries to install python among other steps.

Is there a way to disable the booth step ?

If not, I found I could get it to work just making the following changes on booth.sh:

```
if [ "$PIP" == "" ] || [ "$GIT" == "" ]; then
YUM=`which yum`
if [ "$YUM" == "" ]; then
  $SUDO apt-get update && $SUDO apt-get install -y python-pip ssh git-core
else
  $SUDO yum update -y && $SUDO yum install -y python-pip git-core
fi
  pip install -I virtualenv==1.11.4
fi;
```

**Comment by manishas** [comment]
@jico84 there is currently no way to disable the boot step.

We officially support ubuntu 12.04 and ubuntu 14.04 images. But other images should work with a few tweaks, so happy to answer further qs.
