### ISSUE TITLE
Are badges capable of automatically determining branch name?

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#1333]
Hi,

are badges URLs capable of automatically determining branch name by parsing referer URL?

In other words, if I put such URL `https://api.shippable.com/projects/55341ccfedd7f2c052c86d5f/badge` to the README (`branchName` parameter was intentionally stripped), and have several branches, would this badge show different build status if user browses to the different branch on GitHub or would it always show status of the last build?

This behaviour is currently undocumented.

**Comment by manishas** [comment]
@mspanc it will show the latest build status.
