### ISSUE TITLE
Latest Python 2.7.x support

### ISSUE THREAD

**Issue by j1fig** [Shippable/support#1336]
Hi,

[This warning](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) yields due to using an older version of Python 2.7 SSL implementation. I'm using Python 2.7.8 which works without this warning.

The module that issues the warning (urllib3) is quite used for python web programming, and used by other modules such as requests. I'd say some more people are getting the warning.

Currently I see that the min/v2 container uses the Python 2.7.3 version, however the shippable.yml only seems to be able to select the major versions.

Is this possible:
@shippable.yml

```
python:
  - 2.7.8
```

?

If not, am I forced to use a different build image that uses an updated version of Python?

**Comment by Nalum** [comment]
I would also like to see this added.

**Comment by joaonvfigueiredo** [comment]
@manishas any news on this?

**Comment by avinci** [comment]
this was already implemented a while ago. We also are going to be launching new 3.x versions next week.
