### ISSUE TITLE
Missing consolidated reference for shippable.yml

### ISSUE THREAD

**Issue by companykitchen-dev** [Shippable/support#1337]
I am having a hard time finding a reference for the shippable.yml file. I have found a lot of great examples and it was easy to get off the ground, but now that I'm getting into details, I would like one place to go to see all the elements available in the file and what they can contain etc. Is there such a reference?

**Comment by manishas** [comment]
docs.shippable.com contains all documentation for the yml. If you have specific questions on a scenario, please open up an issue with your scenario and we'll try to find or build a sample for you.
