### ISSUE TITLE
can't reset settings override of shippable.yml

### ISSUE THREAD

**Issue by DanLipsitt** [Shippable/support#1338]
The settings in the web interface say they override the contents of shippable.yml. The problem is that there is no way to unset that override. This is compounded by the fact that you can't change some settings without changing others. This means you can't set enable-privileged-mode without also setting build-image, which I want to leave at the default value in shippable.yml.

**Comment by manishas** [comment]
@DanLipsitt we can reset the settings on the backend if you want. we're working on this UX and will keep this feedback in mind.

**Comment by manishas** [comment]
this has been completely overridden and the docker config is now completely driven through the yml.

http://docs.shippable.com/ci_configure/#pushing-an-image-to-a-registry
http://docs.shippable.com/ci_configure/#setting-your-build-image
