### ISSUE TITLE
ssh/rsync error during init of dedicated node

### ISSUE THREAD

**Issue by DanLipsitt** [Shippable/support#1339]
I can't init a dedicated node because of this error:

```
Writing key to file
mode of '/tmp/66ce2c15-98b1-4b40-ae8f-1e61c959fe53.rsa' changed from 0644 (rw-r--r--) to 0600 (rw-------)
KEY file created: /tmp/66ce2c15-98b1-4b40-ae8f-1e61c959fe53.rsa
Writing script to file
Script file created: /tmp/66ce2c15-98b1-4b40-ae8f-1e61c959fe53.sh
ssh_exchange_identification: Connection closed by remote host rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
```

**Comment by manishas** [comment]
@DanLipsitt did you run the sudo command on your host before initializing?

**Comment by DanLipsitt** [comment]
Yes, I did. The ssh key is present in `/home/shippable/.ssh/authorized_keys`.

**Comment by leroyjware** [comment]
Was this ever resolved?

**Comment by manishas** [comment]
I am closing this issue, but please feel free to comment/reopen if you're still running into this problem.

@DanLipsitt you can now use custom images without dedicated hosts, so it will be great if you can try your build on our multi-tenant platform if possible. Thanks!
