### ISSUE TITLE
PHP Warning during both successful and failed builds

### ISSUE THREAD

**Issue by pbosko** [Shippable/support#1340]
After PHP unit starts all builds for project 540e7b1d3479c5ea8f9ebcdc contain following message along with stack trace.

PHP Warning:  include_once(/home/shippable/workspace/src/github.com/EvolutionSoftware/gips4/src/xtests/gips/unit): failed to open stream: No such file or directory in phar:///home/shippable/.phpenv/versions/5.4.30/bin/phpunit/phpunit/Util/Fileloader.php on line 93

This doesn't seem to cause us problems but it is annoying. Is there something we can do about it or is it a bug?

**Comment by pbosko** [comment]
Example build: https://app.shippable.com/builds/5538a337d7211f0b0011f86c

**Comment by manishas** [comment]
@pbosko searching on the internet, it seems to be a quirk depending on how php was installed. i am closing this issue since this doesn't seem to be a big pain point, but if we get additional reports of this, we will take a look. Thanks!

**Comment by pbosko** [comment]
We have fixed this one. It was a bug on our side. Sorry for bothering.
