### ISSUE TITLE
Artifacts download URL with Free plan for a private repo

### ISSUE THREAD

**Issue by cchantep** [Shippable/support#1341]
Hi,

Is it possible to get (if yes how) the download URL for the artifacts (the archive) created by a build, using a free Shippable plan with a private Bitbucket repository?

Best regards

**Comment by manishas** [comment]
The Shippable API is only available to paid accounts, so to use the API to download artifacts, you would need a paid account.

However, you can upload your artifacts to S3 as part of your build workflow in the free plan.

**Comment by brianjking** [comment]
@manishas What about uploading artifacts via SCP or FTP? If so, can you point me in the right direction. Thanks!
