### ISSUE TITLE
Using Shippable for publishing releases

### ISSUE THREAD

**Issue by schmmd** [Shippable/support#1342]
We are trying to make Shippable publish our releases instead of publishing them from developer machines.  One advantages is this makes our releases go through code review, another is we don't need to configure every developer machine to be able to make releases.

I'm hitting a problem, however.  I expected that when a pull request is merged into master, each commit would be built.  However, only the last commit in the merge is built.

https://github.com/allenai/test/pull/1

In this case, I need https://github.com/allenai/test/commit/995a18e413bca0a27fbbd5c4cdb8046e1c5af02f to be built by Shippable because this is the commit that is actually tagged by the release process.  Unfortunately Shippable is not building this commit.

I'm copying this strategy from https://github.com/scala/scala-xml which accomplishes this on Travis-CI.  How would you recommend doing this on Shippable?

**Comment by manishas** [comment]
@schmmd the merge is treated as one unit, so there is no way to deploy by commit if a merge contains multiple commits. The entire merge is built when the PR is merged.

I took a look at the .travis.yml in the link you posted, and I don't think they're publishing per commit. Their build is a matrix and they are choosing to publish when running on openjdk6.

**Comment by schmmd** [comment]
Do you have any suggestions on how I could use Shippable to publish my
releases?

**Comment by schmmd** [comment]
I'm using a more complex script now.

https://github.com/allenai/test/blob/master/admin/publish-release.sh

**Comment by manishas** [comment]
Closing this issue. Please re-open or comment if you're still looking for an answer here.
