### ISSUE TITLE
Cannot initialize Dedicated Host

### ISSUE THREAD

**Issue by bmajz** [Shippable/support#1347]
Nodes for Namespace: bitbucket/bmajz

Command failed : ssh -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=0 -p 22 -i /tmp/fd8a1f8a-6f02-49e2-8599-baf70848014d.rsa shippable@52.5.86.252 /tmp/fd8a1f8a-6f02-49e2-8599-baf70848014d.sh Exception Script failure tag received
Checking kernel
sudo: sorry, you must have a tty to run sudo

**Comment by manishas** [comment]
@bmajz did you run the sudo command on the host before initializing the host?

![host_dialog](https://cloud.githubusercontent.com/assets/2983749/7311395/a9eaee48-e9f0-11e4-936e-358b15b3a51c.png)

**Comment by bmajz** [comment]
Yes I did

**Comment by manishas** [comment]
@bmajz is this a machine on AWS or DO? Dedicated hosts has been tested on AWS and DO hosts and minimum requirements are 64 bit OS, Ubuntu 12.04 or 14.04, 30GB HDD, 2GB RAM.

**Comment by bmajz** [comment]
Got it. I was using a standard Amazon AMI rather than Ubuntu.
