### ISSUE TITLE
Build taking 20 minutes

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1349]
One of my project takes 20 minutes to build on Shippable. Locally it takes 12 seconds. The reason why it is so slow is that it downloads all maven dependencies before the build. 

This is really painful. I see the caching button is disabled on my project settings. 
![screen shot 2015-04-23 at 6 53 59 am](https://cloud.githubusercontent.com/assets/1060991/7296483/a4f614b4-e985-11e4-8815-bec4b7e391e9.png)

Why can't Shippable cache my dependencies after 1st run ?

**Comment by manishas** [comment]
@hshira you can specify ```cache: true``` in your yml to cache your container. We're reworking this UI, so this issue will be fixed.

**Comment by manishas** [comment]
Closing this. @hshira please let us know if you still need help with this.
