### ISSUE TITLE
project setting overrides specified build_image

### ISSUE THREAD

**Issue by hackerhasid** [Shippable/support#1351]
i specified a build image in my shippable.yml file

`build_image: shippableimages/ubuntu1404_ruby`

but the build still was using the `shippable/minv2`. i noticed in my project settings the build image was set to `shippable/minv2:latest` so i updated that to `shippableimages/ubuntu1404_ruby` (screenshot below). this surprised me because i would expect my shippable.yml to override this setting. as it stands there doesn't seem to be a way to override the setting on the website!

![screen shot 2015-04-23 at 3 36 27 pm](https://cloud.githubusercontent.com/assets/797379/7305783/8f4b0108-e9ce-11e4-9a81-dc21c06398a7.png)

**Comment by manishas** [comment]
@hackerhasid currently, once you start using project settings, they override the yml. There is a warning on that page informing users of this.
