### ISSUE TITLE
deploy to different opsworks stacks based on branch

### ISSUE THREAD

**Issue by hackerhasid** [Shippable/support#1353]
what's the best way to deploy to different places based on the current branch? i could write a simple script for that but what i'd like to do (which is supported by your competitors) is specify env variables in inside your website for different branches. so i could e.g. specify for the branch development the `STACK_ID` is 123 whereas for the branch production the `STACK_ID` is 456.

**Comment by manishas** [comment]
@hackerhasid we have a BRANCH name env variable and you can also define your secure env variables.

http://docs.shippable.com/en/latest/config.html#common-environment-variables

here are some other support issues about similar questions -
https://github.com/Shippable/support/issues/1247
https://github.com/Shippable/support/issues/1281

Do these help? If not, we can put together a build sample.

**Comment by manishas** [comment]
Closing since the question is answered...
