### ISSUE TITLE
Build stalls after phpunit, and then stops with timeout

### ISSUE THREAD

**Issue by antonienko** [Shippable/support#1354]
I'm trying out shippable, and I want to see how everything works before upgrading the account to a paying one, but I'm getting stuck with one problem:

the build seem to freeze after the phpunit is completed, and finally after so many minutes it gives a timeout.

You can see the build here:
https://app.shippable.com/builds/553a228bbf6d0a0c00523d18

What am I doing wrong?

Thanks in advance.

**Comment by manishas** [comment]
@antonienko can you try without code coverage? There have been other reports of builds being stuck at code coverage step - https://github.com/Shippable/support/issues/349

Suggested workaround from the issue - 
The use code line is: - ```phpunit --log-junit shippable/testresults/junit.xml --coverage-html shippable/html --configuration phpunit.xml app/tests/unit```, maybe it will be useful to others.

**Comment by antonienko** [comment]
Indeed, without code coverage it worked perfectly

**Comment by bretterer** [comment]
+1 for the issue and mine does work without code coverage

**Comment by claar** [comment]
Same issue for us. We use code coverage.

**Comment by daniel-sc** [comment]
+1

**Comment by antonienko** [comment]
When I include a whitelist for code coverage, it works perfectly. Maybe that's the issue for you too guys.

**Comment by manishas** [comment]
php code coverage has been rebuilt from ground up, so this should not be happening any more. please let us know if this works now.
