### ISSUE TITLE
Not seeing any output from the build

### ISSUE THREAD

**Issue by hcarver** [Shippable/support#1356]
E.g. number 553a561782cfa40b00ba5c4c

The console is not showing any content at all, even if I wait. Content is there if I look at a past build, just not for a build that's meant to be running at the moment.

**Comment by bbradbury** [comment]
Same symptom as #1355 I think

**Comment by manishas** [comment]
@hcarver @bbradbury one of our builds hosts had an issue which has caused some builds to be backed up. The build queue is now being processed., but it will take some time to catch up.

**Comment by bbradbury** [comment]
thx @manishas :+1:

**Comment by rbwinslow** [comment]
Waited for build, zero output, for more than an hour before seeing this ticket. Canceled, started a new one, and now at the 35 minute mark with, again, zero output. "Waiting" status.

Is the contents of the "Service Status" section of your README really defensible, at this point?

**Comment by manishas** [comment]
This should be resolved, so closing. Please open a new issue with a build link if you're still seeing issues.

**Comment by rbwinslow** [comment]
Sorry for the lack of action; thought that it was already closed. Many thanks!
