### ISSUE TITLE
getting a lot of "error occurred while removing container" in purge step

### ISSUE THREAD

**Issue by hackerhasid** [Shippable/support#1357]
this happened a few times yesterday including my most recent build (5539bf0ebf6d0a0c005236ed).

should i be concerned?
```
error occurred while removing container gh_hackerhasid_website_51_1_5537f7c1edd7f2c052cd78de: 500 Server Error: Internal Server Error ("Cannot destroy container gh_hackerhasid_website_51_1_5537f7c1edd7f2c052cd78de: Driver aufs failed to remove root filesystem 53fac64dc9b0bcd64d8e2788aefa23a278aaeec961884f802900c5fc182c0061: rename /data/aufs/diff/53fac64dc9b0bcd64d8e2788aefa23a278aaeec961884f802900c5fc182c0061 /data/aufs/diff/53fac64dc9b0bcd64d8e2788aefa23a278aaeec961884f802900c5fc182c0061-removing: device or resource busy"): Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
Exception:  
 error occurred while removing container gh_hackerhasid_website_51_1_5537f7c1edd7f2c052cd78de: 500 Server Error: Internal Server Error ("Cannot destroy container gh_hackerhasid_website_51_1_5537f7c1edd7f2c052cd78de: Driver aufs failed to remove root filesystem 53fac64dc9b0bcd64d8e2788aefa23a278aaeec961884f802900c5fc182c0061: rename /data/aufs/diff/53fac64dc9b0bcd64d8e2788aefa23a278aaeec961884f802900c5fc182c0061 /data/aufs/diff/53fac64dc9b0bcd64d8e2788aefa23a278aaeec961884f802900c5fc182c0061-removing: device or resource busy")
```

**Comment by manishas** [comment]
@hackerhasid i've logged a bug in our internal tracker. the purge step should not fail.

**Comment by manishas** [comment]
@hackerhasid can we do a hangout on monday? i want to understand your build workflow and make sure everything is set up correctly. 

Taking a look at https://github.com/shippableSamples/docker-build-nodejs has helped a couple of folks get started.

**Comment by hackerhasid** [comment]
sure - https://calendly.com/noahb/15min



--
Noah Blumenthal
Founder, BargeApp.com - Load Testing for Developers
@barge

On April 25, 2015 at 2:04:32 PM, Manisha (notifications@github.com) wrote:

@hackerhasid can we do a hangout on monday? i want to understand your build workflow and make sure everything is set up correctly.

Taking a look at https://github.com/shippableSamples/docker-build-nodejs has helped a couple of folks get started.

**Comment by manishas** [comment]
Closing this. We've fixed the purge issue.
