### ISSUE TITLE
[Question] What's the logic of 'cache'

### ISSUE THREAD

**Issue by txchen** [Shippable/support#1358]
When we specify cache = true in shippable.yml, what will actually happen?

Our product is using gradle as build tool, and it will download the dependencies to ~/.gradle. We are using cache=true, but seems it is not caching the .gradle directory, every build is downloading the same jars from maven central again.

So I'd like to know what does 'cache' mean, exactly? And is there a way to cache the .gradle directory?

Thanks a lot!

**Comment by manishas** [comment]
@txchen we wrote a blog about this a few weeks ago - http://blog.shippable.com/container-caching

Let me know if this answers your question.

**Comment by txchen** [comment]
@manishas thanks! It is helpful.

So according to the blog, it is actually caching the before_install steps, right? Then what's your recommendation to cache maven or gradle external dependencies download?

**Comment by manishas** [comment]
@txchen it should cache the entire container, not just the before_install steps.

**Comment by manishas** [comment]
Closing since there is no action item on our plate.
