### ISSUE TITLE
cannot log into shippable.com via github auth

### ISSUE THREAD

**Issue by hackerhasid** [Shippable/support#1359]
i click login with github auth, am redirected back to https://app.shippable.com/auth/github/identify?code=6ee245707b0b750b202f with the following output (to my browser!):

> Error: Unexpected response from API exchange at _exchangeTokenResponseHandler (/home/shippable/fe/common/githubStrategy.js:79:13) at Request._callback (/home/shippable/fe/views/index/exchangeToken.js:38:12) at Request.self.callback (/home/shippable/fe/node_modules/request/request.js:368:22) at Request.emit (events.js:98:17) at Request.<anonymous> (/home/shippable/fe/node_modules/request/request.js:1219:14) at Request.emit (events.js:117:20) at IncomingMessage.<anonymous> (/home/shippable/fe/node_modules/request/request.js:1167:12) at IncomingMessage.emit (events.js:117:20) at _stream_readable.js:944:16 at process._tickCallback (node.js:448:13)

**Comment by manishas** [comment]
@hackerhasid are you still experiencing this?

**Comment by manishas** [comment]
this should be resolved. closing.
