### ISSUE TITLE
Does Shippable support hg projects?

### ISSUE THREAD

**Issue by wyuenho** [Shippable/support#136]
It seems like Shippable is always trying to git clone even if my project on Bitbucket is using Mercurial. Does Shippable support Mercurial?

**Comment by giumas** [comment]
The issue that Mercurial projects are not supported is still not clearly specified! So, after almost 1 year, I share the @schinckel feeling!

**Comment by erichiggins** [comment]
+1

**Comment by qraynaud** [comment]
+1, would like to see bitbucket support

**Comment by manishas** [comment]
Closing as dup of https://github.com/Shippable/support/issues/45 since all requests for additional source control integrations will be tracked there.
