### ISSUE TITLE
GitHub/Bitbucket tag support

### ISSUE THREAD

**Issue by jchamberlain** [Shippable/support#1362]
On Travis, I could push a tag up and a build would start, just like with any other commit. On Shippable, the build tries to start but complains that there's no shippable.yml. Builds work fine for everything else, just not pushed tags. I'm only deploying when a tag is pushed, so right now I have to manually start a build whenever I push a tag.

In some ways, this is the opposite request of #905. I'd like to have the same behavior as Travis.

**Comment by manishas** [comment]
consolidating all tags requests in #905
