### ISSUE TITLE
Cache is very inconsistent

### ISSUE THREAD

**Issue by nathanmarks** [Shippable/support#1363]
I'm having issues with the cache being less than reliable. Sometimes the build is pretty quick, but a lot of times I'm seeing it take **forever** getting the npm and composer dependencies. I'm assuming this is a cache issue...

**Comment by manishas** [comment]
@nathanmarks what github/bitbucket username are you using to sign in to shippable?

**Comment by nathanmarks** [comment]
@manishas poweredbysearch/sme-reporting

**Comment by nathanmarks** [comment]
@manishas And my last build completed but shippable has it marked as processing still.

**Comment by nathanmarks** [comment]
@manishas I think it built the cache again this last run, which is why it took so long to complete. Things should be better now.
