### ISSUE TITLE
Explanation of build times?

### ISSUE THREAD

**Issue by nathanpeck** [Shippable/support#1364]
Shippable always shows times that look phenomenal when you view the build detail page:

![img](http://i.imgur.com/SjBWFWI.png)

It looks like that build took just 12 seconds.... But that is completely untrue, as the overall time was over 3 minutes according to the build list for the project. Additionally if I had started a stop watch the moment the buildimage step began and stopped it the moment it finished it would have been about 1 minute in length. The same goes for the other steps.

Can you explain how the timing works, and why the build details thinks it only took 12 seconds, while the build list clearly shows times of several minutes in length?

**Comment by chriskinsman** [comment]
Noticed this also...

**Comment by rvdwijngaard** [comment]
yep, my build usually takes three minutes to run (mainly because of a docker push) but the total lead time of the build is 9 minutes.

**Comment by manishas** [comment]
we have revamped our build system. we're no longer showing times for individual steps, but we'll add it in soon and make sure the times make sense.
