### ISSUE TITLE
Stuck on "pull"

### ISSUE THREAD

**Issue by chrisdl** [Shippable/support#1365]
It pulls down the cached minv2:latest docker image. says a bunch of hashes already exists and that the
Status: Image is up to date for shippable/minv2:latest

It just never continues to the next step, and i've got a ton of builds lined up...

**Comment by manishas** [comment]
@chrisdl we had to restart docker on our hosts this morning and that caused your build to be stuck. We canceled that build and the next build is running fine now.

Please re-open this issue if you run into this again. Thanks!
