### ISSUE TITLE
Inconsistent cache

### ISSUE THREAD

**Issue by nathanmarks** [Shippable/support#1366]
Followup to the ticket I closed earlier #1363 

See this screenshot: http://i.glui.me/1Ex6iMR

I would expect that the 2nd build there would use the cache and take ~6-7 minutes again. Instead it took much longer.

**Comment by manishas** [comment]
@nathanmarks our caching is at a per host level, so it takes some time for it to catch up on all hosts. Details at http://blog.shippable.com/container-caching

**Comment by manishas** [comment]
Closing this issue @nathanmarks let us know if caching is still broken for you.
