### ISSUE TITLE
Build times out

### ISSUE THREAD

**Issue by markschaake** [Shippable/support#1368]
This build timed out: https://app.shippable.com/builds/553e9904a173611200929bb0

Also, duration is reported as "A few seconds" and it clearly ran for much longer than that.

**Comment by chriskinsman** [comment]
I am seeing this intermittently today also.  Probably 10 or so builds today have done this...

**Comment by HenrikOssipoff** [comment]
Seeing this as well. As far as we can see, this happens when Shippable pulls from Bitbucket?

**Comment by chriskinsman** [comment]
We are on github...

**Comment by chriskinsman** [comment]
Seeing this still even after the other fixes.  @manishas any thoughts?

**Comment by manishas** [comment]
we're actually figuring this out right now and everyone is working on this. will update when i have an ETA.

**Comment by HenrikOssipoff** [comment]
@manishas any update? Still seeing this - recent example is 553ff016070bc40b00c816fb.

**Comment by frenkel** [comment]
We have this problem as well, but using bitbucket.org

**Comment by HenrikOssipoff** [comment]
Things seem to be working on our end now.

**Comment by manishas** [comment]
This should be fixed now, so closing. Please open a new issue if you're still experiencing build issues.
