### ISSUE TITLE
Error after pull step

### ISSUE THREAD

**Issue by pkaminski** [Shippable/support#1369]
Starting this afternoon, I'm seeing errors like this (details vary) between the `pull` and `git_sync` steps:

```
/root/13e170ee-6f59-4c08-82ed-337bb31a3b53.sh: line 73: featurecataloguecache.105.1: syntax error: invalid arithmetic operator (error token is ".105.1")
```

The build continues but later on can't find `~/.nvm/nvm.sh` and proceeds with an old version of node -- not sure if this is related or a separate bug.

My build environment:

```
build_image: shippableimages/ubuntu1404_nodejs
language: node_js
node_js:
  - "0.12"
```

Sample build with error:
https://app.shippable.com/builds/553eb42fa173611200929e54

**Comment by chrisdl** [comment]
I get something similar

`/root/8a560781-7ceb-4fed-a4d9-dXXXXXXa.sh: line 73: refactorreact-revamp.103.1: syntax error: invalid arithmetic operator (error token is ".103.1")`

**Comment by phagunbaya** [comment]
Same here.
/root/db7bd2c0-e314-41f1-a2fe-0317fee38e82.sh: line 73: refactorreact-revamp.103.1: syntax error: invalid arithmetic operator (error token is ".103.1")

**Comment by manishas** [comment]
This issue should be resolved now. We're still working on a fix for some timeouts and dedicated hosts, but this particular issue should not happen any more.

Closing this, but please let us know if you run into this again.
