### ISSUE TITLE
Shorter custom timeout

### ISSUE THREAD

**Issue by winglian** [Shippable/support#1371]
There have been a lot of random timeouts lately. All successful builds take less than 15minutes, and if it runs longer than that, it times out. Is there a setting we can use in shippable.yml that we can use to simply set the timeout to 30 minutes instead of 2 hours so we aren't waiting for these random timeouts?

**Comment by rogierslag** [comment]
Would love this as well!

**Comment by rogierslag** [comment]
For now we just added `timeout 30m` before the build command

**Comment by manishas** [comment]
We should add a project setting to be able to specify custom timeouts, up to a maximum of what we support .

**Comment by shrivara** [comment]
We have added this feature and should be available soon. I'll update here with details once its live.

**Comment by avinci** [comment]
@kanthchandra please update this issue

**Comment by kanthchandra** [comment]
@rogierslag @winglian  You can now go to your project settings page and set the custom timeout. You will need to set the custom timeout in minutes. The maximum that we support at the moment is around 90 minutes. 

Any job in processing state for more than the number of minutes you have mentioned will timeout.
