### ISSUE TITLE
Errors pulling image from docker hub

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1373]
![screen shot 2015-04-28 at 6 43 40 am](https://cloud.githubusercontent.com/assets/1522018/7370881/f86c8fca-ed71-11e4-980e-ee769362cfda.png)

**Comment by nathanmarks** [comment]
Same here

**Comment by chriskinsman** [comment]
It looks like this is now gone.  Still seeing quite a pause post Docker Pull
