### ISSUE TITLE
Syntax error pulling from docker

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1374]
![screen shot 2015-04-28 at 7 01 17 am](https://cloud.githubusercontent.com/assets/1522018/7371258/716eb59a-ed74-11e4-9bff-028fd8b67090.png)

**Comment by chrisdl** [comment]
same as #1369 methinks. ton of people (including me) having this issue.

**Comment by chriskinsman** [comment]
Perhaps.  I didn't see the same error in the initial bug report so decided to open new issue.  At this point Shippable is pretty much down for us.  None of our builds are completing which means our deploy pipeline is dead in the water...

**Comment by chriskinsman** [comment]
It looks like this is now gone.  Still seeing quite a pause post Docker Pull

**Comment by chriskinsman** [comment]
This is back for me now @manishas

**Comment by chriskinsman** [comment]
Appears to be fixed again...
