### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by arun057** [Shippable/support#1375]
I have a gem being referenced from a public github repo and build fails with this error:
```
Fetching git@github.com:achand04/pickadate.js.git
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```

https://app.shippable.com/projects/552c2cd65ab6cc1352c2a250

**Comment by manishas** [comment]
@arun057 did you figure this out? I see all your latest builds are passing....

**Comment by manishas** [comment]
Closing this issue since the problem seems to be resolved.
