### ISSUE TITLE
Build randomly fails at pulling of docker image

### ISSUE THREAD

**Issue by FlorianLoch** [Shippable/support#1376]
Some of my builds are queued, some few run green but most of them fail while pulling the docker image...
Error message: "Error response from daemon: Registration: \"Wrong email format (it has to match \\\"[^@]+@[^@]+\\\\.[^@]+\\\")\"  

![image](https://cloud.githubusercontent.com/assets/5587805/7371730/fd46d31a-edc2-11e4-8b11-7e82ecfbbc35.png)

So my pipeline is dead right now :/

**Comment by antonienko** [comment]
+1, I'm having the same error message on a build that was green before, without any change.

**Comment by chriskinsman** [comment]
Seeing same issue.  Contacted one of the founders and he indicated they are working on a number of issues related to upgrading their docker integration.  Heres to hoping they figure it out soon...

**Comment by manishas** [comment]
@FlorianLoch @antonienko @chriskinsman we're investigating this and will post an update as soon as possible.

**Comment by catskul** [comment]
+1

**Comment by nathanmarks** [comment]
+1

**Comment by prattl** [comment]
+1

**Comment by hasier** [comment]
+1

**Comment by manishas** [comment]
we've found the issue and are working to fix it. update soon.

**Comment by manishas** [comment]
We've pushed a fix and most builds should work now. 

If you're using using custom images on dedicated hosts, you will still see failed builds and we're now working on a fix for that.

**Comment by jwriteclub** [comment]
I'm still seeing what appears to be an instance of the same issue when running using the Shippable supplied images and public instances

` Cache exists, skipping pull

/root/8b15cd4f-dc03-4a1f-9807-c6c21d65b9fc.sh: line 73: refactorreact-revamp.103.1: syntax error: invalid arithmetic operator (error token is ".103.1")`

I've seen this on every recent build.

**Comment by chriskinsman** [comment]
I found once it re-downloads it works just fine...

**Comment by jwriteclub** [comment]
Is there a way to somehow clear the cache and/or force a re-download for a project?

**Comment by manishas** [comment]
@jwriteclub you can do a commit with [reset_minion] in your commit message. this will delete cache.

http://docs.shippable.com/en/latest/config.html#caching-minions

**Comment by FlorianLoch** [comment]
I can confirm it is working again fine (at least for me).

**Comment by chriskinsman** [comment]
Working here...

**Comment by manishas** [comment]
Thanks for confirming! We've pushed several fixes to prod today, so everything should work. 

I will close this issue now and we'll keep a close watch.
