### ISSUE TITLE
Stop building my project! 

### ISSUE THREAD

**Issue by paulhernandez** [Shippable/support#1378]
I have revoked access to shippable but it still tries to build with every PR. How do I turn off shippable? I've already revoked access.

repo
https://github.com/SpanningCloudApps/stab.git

**Comment by manishas** [comment]
@paulhernandez sorry about this. we'll figure out what's going on and get back to you soon.

**Comment by manishas** [comment]
@paulhernandez if you go to the repo settings on github, do you see the shippable webhook still there? It should look like this - https://api.shippable.com/projects/<project id>

If it is there, can you delete the webhook? That should stop everything.

**Comment by manishas** [comment]
@paulhernandez I am closing this issue since we cannot delete the webhook at our end at this point since we do not have access. Let us know if it doesn't work for you.
