### ISSUE TITLE
Max retries exceeded with url: /v1.15/images/create?tag=latest&fromImage=shippable%2Fminv2

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1379]
Job: https://app.shippable.com/builds/553fcac350fb130d009aac4f

Got this error several times...

Full stacktrace:

```
HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=latest&fromImage=shippable%2Fminv2 (Caused by <class 'socket.error'>: [Errno 111] Connection refused): Traceback (most recent call last):
  File "/home/shippable/dpd/step_listener.py", line 99, in handle_message_callback
    self.execute_step(build_plan, current_step, False)
  File "/home/shippable/dpd/step_listener.py", line 165, in execute_step
    raise e
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4243): Max retries exceeded with url: /v1.15/images/create?tag=latest&fromImage=shippable%2Fminv2 (Caused by <class 'socket.error'>: [Errno 111] Connection refused)
```

**Comment by manishas** [comment]
@caarlos0 we're looking into this.

**Comment by caarlos0** [comment]
@manishas thanks! :dancer:

**Comment by manishas** [comment]
@caarlos0 your latest builds seem to have succeeded. We've deployed a bunch of fixed to prod today and I don't think you should see this problem any more.

One qs though - do you have a build host that you have deleted from the Shippable UI recently? We see an old component talking to our service and we're wondering if it's an old build host that is still connecting to our service...

**Comment by caarlos0** [comment]
@manishas not that I'm aware of, no...

Our instances shutdown and turn on again in scheduled times, though, but we don't remove them from the Shippable UI... I will talk to my coworkers and let you know if I discover anything, ok? :dancer: 

I can see that the error indeed stopped occurring, many thanks :beers:

**Comment by caarlos0** [comment]
@manishas the bug started to occur again...

**Comment by manishas** [comment]
@caarlos0 which repo is this happening for? I don't see this issue in the repo from yesterday.

**Comment by caarlos0** [comment]
@manishas ContaAzul/ContaAzul, ContaAzul/Puppet and possibly other too...

**Comment by caarlos0** [comment]
Apparently it went away again...

thanks.
