### ISSUE TITLE
intermittent error when installing docker

### ISSUE THREAD

**Issue by hackerhasid** [Shippable/support#1381]
as part of my build i need to build a docker image. to do so i install docker using the command `wget -qO- https://get.docker.com/ | sh`

this works most of the time but fails intermittently with the error:

> Warning: "docker" or "lxc-docker" command appears to already exist.

i would expect the build container to *always* be the same. so it's very odd that it *sometimes* contains docker and *sometimes* does not!

**Comment by manishas** [comment]
@hackerhasid are you available for a hangout right now?

**Comment by hackerhasid** [comment]
no. but i will be in 30 min. does that work?



--
Noah Blumenthal
Founder, BargeApp.com - Load Testing for Developers
@barge

On April 28, 2015 at 2:41:08 PM, Manisha (notifications@github.com) wrote:

@hackerhasid are you available for a hangout right now?

**Comment by manishas** [comment]
yes. what's your email id? i can send you a mtg request.

**Comment by hackerhasid** [comment]
noah@bargeapp.com



--
Noah Blumenthal
Founder, BargeApp.com - Load Testing for Developers
@barge

On April 28, 2015 at 2:43:03 PM, Manisha (notifications@github.com) wrote:

yes. what's your email id? i can send you a mtg request.

**Comment by manishas** [comment]
Our minions were not designed to support docker in docker scenarios, so closing this out for now.
