### ISSUE TITLE
Builds hanging intermittently

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1382]
![screen shot 2015-04-28 at 11 35 47 am](https://cloud.githubusercontent.com/assets/1522018/7377364/cd556b9e-ed9a-11e4-8fbf-e09bda909988.png)

It just stays on this screen until the build times out.  I have done a git commit -am "reset_minion" on this repo

**Comment by jeffkole** [comment]
I am seeing the same behavior.  My builds have been incredibly slow this morning, most of them hanging, and some of them failing because they are running `npm install` properly.  I am getting *a lot* of false negatives.

**Comment by bdmesh** [comment]
+1

**Comment by chriskinsman** [comment]
I have noticed that builds kicked off via GitHub webhook fail with this timeout.  If I cancel them and kick a build off manually it downloads the ubuntu1404/nodejs image and doesn't hang.  Takes a bit longer but at least I get something out...

**Comment by jeffkole** [comment]
Unfortunately, that work around did not work for me.

**Comment by chriskinsman** [comment]
This appears to be fixed for now.  Crossing my fingers...
