### ISSUE TITLE
My minion is in use... by what?

### ISSUE THREAD

**Issue by bdmesh** [Shippable/support#1383]
We've been hitting some oddities in our builds the past few days, but seemed to be working again last night when it validated my PR.  I checked in this morning and now I'm back to where the first "pull" step succeed in 6 seconds or so, but then nothing else happens.  After 5 minutes, I canceled the build, committed one small fix and watched for it to start again.

All of my repos are in the success/failed/waiting state (none running/pending) and on my main shippable page, it says "1/1 available minions in use".  It's been like that for 15 minutes and my waiting build won't get picked up.  

Is something broken right now?  Is there a way to kick the minion and restart everything?  I have no idea what it's doing.

Thanks!

**Comment by bdmesh** [comment]
OK, after 60 minutes, my "waiting" build timed out... so now my minion is free.  I tried starting a build from the web console and the build gave me a checkmark by the 'pull' step, simply saying "cache exists, skipping pull"... and it hung there.  So I canceled that one.

I just set this repo up last night and haven't changed the shippable.ml file since.  No where do I have 'cache: true' in it.  So not sure where this is coming from.

After killing the previous build, I just now  checked in a change with the comment 'reset_minion' and it.  Now 'pull' succeeds after 5 seconds (says "sudo docker pull shippable/minv2:latest"), but now it hangs there.

I have no idea why it's not moving forward.

**Comment by bdmesh** [comment]
Note, I've confirmed that we're experiencing the same problem (says cache exists) across multiple repos.

**Comment by manishas** [comment]
@bdmesh we're running into some issues today and are working on fixing them. update as soon as we bring everything back to normal.

**Comment by bdmesh** [comment]
Looks like all is working again.  Feel free to close.  Thanks!

**Comment by manishas** [comment]
@bdmesh our service ran into a few issues yesterday and this was probably a side effect. Let us know if you run into any issues again.
