### ISSUE TITLE
Build fails because of missing module that is shown as installed in the log

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#1384]
Our build correctly installs the `Immutable` package from `npm`, as you can see in the logs.  But then, the tests fail with this error:

```
Error: Cannot find module 'Immutable'
```

Any way I can get to that machine and do some diagnosis?

Build is: https://app.shippable.com/builds/553fe5ac50fb130d009aaf54

**Comment by jeffkole** [comment]
FYI: This is my build history today (all of these builds run just fine locally):

![shippable___truly_fastest_ci_in_the_cloud](https://cloud.githubusercontent.com/assets/286588/7393771/87e3a9e0-ee44-11e4-94f5-0720f2019738.png)

**Comment by manishas** [comment]
We'll take a look at this today. We ran into some issues with docker lockups yesterday so could not look at individual issues. Sorry for the delay.

**Comment by manishas** [comment]
https://github.com/BrowserSync/browser-sync/issues/502

Does the above help?

**Comment by jeffkole** [comment]
I've asked a follow up question on that issue, but there is not really a solution there that helps.  The output from the build shows that Immutable is installed in these lines:

```
npm http GET https://registry.npmjs.org/immutable/3.7.1
npm http 200 https://registry.npmjs.org/immutable/3.7.1
npm http GET https://registry.npmjs.org/immutable/-/immutable-3.7.1.tgz
npm http 200 https://registry.npmjs.org/immutable/-/immutable-3.7.1.tgz
immutable@3.7.1 node_modules/immutable
```

I could possibly do some debugging of my own if I could get access to a container after the build has broken.  Is that a feature you have?

**Comment by jeffkole** [comment]
The recommendation from that issue is to reinstall Immutable, so I have sent a `[reset_minion]` command to Shippable to start from scratch.  So far, that build is hanging.  Can you trigger a manual reset for me?

**Comment by jeffkole** [comment]
Finally finished a `[reset_minion]` build, but the results are the same:

https://app.shippable.com/builds/55415ff14dd3670e00327aaf

**Comment by jeffkole** [comment]
Mea culpa!  The module should be loaded as `immutable` with a lower-case "i".  This is the second time in two days that case-sensitivity on your machines (versus on our Macs) has broken our build.  I wish I had spotted the issue more quickly.  Thank you for your help.
