### ISSUE TITLE
Failure when dedicated host pulls docker image

### ISSUE THREAD

**Issue by cymeng** [Shippable/support#1386]
We just started having failures with "Email: EOF" message. It happened a couple times yesterday and consistently today. 

Build is: https://app.shippable.com/builds/55400f92bb4c400b002a9edb

Any idea what the root cause could be?
Thanks!

**Comment by vkuusk** [comment]
Just to add to troubleshooting:

1. the failure happens during the image pulling step (Note: the image was already on the dedicated host from previous runs)

2. message:  "sudo: unable to resolve host ip-10-253-138-155" was always there.

3. The dedicated host disk usage looks OK.
ubuntu@ip-10-253-138-155:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/xvda1       24G  8.7G   14G  39% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            3.7G   12K  3.7G   1% /dev
tmpfs           748M  376K  748M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            3.7G  280K  3.7G   1% /run/shm
none            100M     0  100M   0% /run/user
/dev/xvdb        30G   17G   12G  59% /data

**Comment by manishas** [comment]
@vkuusk @cymeng  can you try running another build? we updated some fixes in prod and your issue should be fixed.

**Comment by cymeng** [comment]
@manishas looks like our latest build had the same issue: https://app.shippable.com/builds/55401e7586638d0d00e2063c

Let us know if anything needs to be done on our side.

**Comment by manishas** [comment]
we're looking into this...

**Comment by manishas** [comment]
@vkuusk @cymeng we pushed a fix for this issue last night, so this shouldn't happen now. Please re-open if you run into this again.

Thanks for your patience!
