### ISSUE TITLE
fatal error response from daemon

### ISSUE THREAD

**Issue by vkuusk** [Shippable/support#1390]
On dedicated host test projects started to fail during the pull phase:

Logged Error message is

pull ✗
sudo: unable to resolve host ip-10-253-138-155
time="2015-04-30T00:04:42Z" level=fatal msg="Error response from daemon: </html>" 

@manishas here is the link to the build: https://app.shippable.com/builds/5541710d4dd3670e00327c30

I rerun and or triggered the build it still fails

Another build (I think it was the first failure) 
https://app.shippable.com/builds/554170944dd3670e00327c27
has error:

  pull ✗
sudo: unable to resolve host ip-10-253-138-155
time="2015-04-30T00:02:41Z" level=fatal msg="Error response from daemon: </html> (Code: 502; Headers: map[Date:[Thu, 30 Apr 2015 00:00:44 GMT] Content-Type:[text/html; charset=utf-8] Content-Length:[11577] Etag:[\"5509bd82-2d39\"] Strict-Transport-Security:[max-age=31536000] Server:[nginx/1.6.2]])" 

Let me or @cymeng  know if we need to do something on the Dedicated Host

Thanks.

**Comment by vkuusk** [comment]
It started to work.

Last triggered build went through OK

Thanks.

**Comment by manishas** [comment]
Thanks for letting us know that your latest build worked!
