### ISSUE TITLE
Only able to run one build at a time

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#1394]
I am on the Startup plan that is supposed to offer me 5 minions to build with at the same time, but currently my builds keep getting backed up in the 'waiting' state.  Right now, I am able to build only one at a time.  Since I am trying to debug why my build is broken on Shippable and working on all local hosts, having only a single thread of builds is quite the drain on my time.

**Comment by manishas** [comment]
@jeffkole is this still an issue?

**Comment by manishas** [comment]
I'm pretty sure this wont happen again, so closing. Please re-open if you run into this again and we'll take a look.
