### ISSUE TITLE
Dedicated host initialization hangs

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#1396]
In an attempt to be able to debug my builds, I am going through the process of setting up dedicated hosts.  I have been waiting for several minutes for the initialization script to complete.  It is hung at:

```
6e5e321b-6b73-4703-a88d-5eebd8b09506.sh sent 1,773 bytes received 35 bytes 328.73 bytes/sec total size is 5,442 speedup is 3.01
executing script file
No NDQ containers found
Container running : beta-ldq-service_shipimg_ldq_06109ae6-1ae4-4527-82a4-e80e7ee5db08_2
Removing any running DPD container
Run script completed
Removing any running NDQ container
Starting container, try count 1
No DPD containers found
/root/.ssh/known_hosts updated. Original contents retained as /root/.ssh/known_hosts.old
```

`ps` on the machine shows

```
root      3190     1  3 12:22 ?        00:00:34 /usr/bin/docker -d -H unix:///var/run/docker.sock -g=/data --storage-driver aufs
root      3694     2  0 12:25 ?        00:00:00 [kworker/1:0]
root      3854  3190  0 12:26 ?        00:00:00 /bin/bash -e /home/shippable/ldq/boot.sh
root      3862  3854  0 12:26 ?        00:00:00 python main.py
```

And yet, there is no `/home/shippable/ldq/boot.sh` file in existence right now.

Suggestions?

**Comment by jeffkole** [comment]
`docker ps` shows only one image, but the only documentation you have on setting up dedicated hosts ([this blog post](http://blog.shippable.com/dedicated-hosts-)] says that two should be started before all is well.

```
CONTAINER ID        IMAGE                COMMAND                CREATED             STATUS              PORTS               NAMES
c097b1f80503        shipimg/ldq:latest   "/home/shippable/ldq   24 minutes ago      Up 24 minutes                           beta-ldq-service_shipimg_ldq_06109ae6-1ae4-4527-82a4-e80e7ee5db08_2   
```

**Comment by manishas** [comment]
@jeffkole sorry about this. we made some changes to the build platform a couple of days ago and we're trying to stabilize that. 

I'll update the docs asap.

**Comment by jeffkole** [comment]
Now that I have a dedicated host, how can I stop Shippable from purging the
container after a failed build so that I can login to it and debug?

**Comment by manishas** [comment]
@jeffkole you mentioned you went back to the multi-tenant minions, so closing this issue. If you do go back to dedicated hosts, please feel free to re-open.
