### ISSUE TITLE
Waiting for mysql start goes on forever

### ISSUE THREAD

**Issue by davidthewatson** [Shippable/support#1397]
I have a build running at 55428c5b93aca60e00aa5226

It gets to the start services phase and then displays the "Waiting for mysql to start..." message several hundred times before it times out:

    echo "Waiting for mysql to start..."
    ...
    Command timed out
    Command thread timed out

Is there anything that I can do to prevent blocking on mysql? This project uses postgres.

Thanks,
David

**Comment by manishas** [comment]
@davidthewatson sorry for the late response! I took a look at your project and looks like builds are working now. Please let me know if you're still running into issues.

We had service disruptions leading to timeouts and slow builds over the last 2 days. We believe we've fixed 90% of the issues and the tail end will be addressed today.

**Comment by manishas** [comment]
I am closing this since it is resolved. Please re-open if you run into this again.
