### ISSUE TITLE
addons for custom docker images

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1398]
Hi, 

I've setup my build configuration to use a custom docker image. My shippable.yaml includes the following lines to set a custom hostname: 

````
addons:
  hosts:
    - dynamodb-local  
````

This does not seem to work but I don't know why. Previously my build config was using the shippable/minv2 image and in the build log the following entries were made: 

````
 Installing addons ✓ 0 seconds
   sudo cp -vr /etc/hosts /tmp/hosts.original > /dev/null 2>&1
   echo "127.0.0.1 dynamodb-local" | sudo tee -a /tmp/hosts.original
   sudo cp -vr /tmp/hosts.original /etc/hosts
````

This does not happen in my changed build configuration. My custom docker image is based on the shippableimages/ubuntu1204_nodejs image. Is it true that the addons are only available for the minv2 base image?

**Comment by manishas** [comment]
@rvdwijngaard yes, services and addons are only available for the minv2 image. If you need anything other than the platform + language, you will need to install it in your yml.
