### ISSUE TITLE
Transparant caching in Shippable

### ISSUE THREAD

**Issue by schmmd** [Shippable/support#1399]
It's great to have caching in Shippable because it speeds our builds by more than 50%.  Shippable must have a slow connection to Maven Central because downloading dependencies is **slow**.  And downloading all dependencies for each build is insane for a complex JVM application.

However, Shippable's caching mechanism is far from perfect.  It's clear you have sacrifice development costs for product quality.  At our company, our caches frequently need to be invalidated because dependencies change and builds start to slow down again because of the new dependencies.  However, it's hard to stay on top of that, and it's yet another thing I need to educate the development team on.  Plus, when we reset our cache, the next ~5 builds are excruciatingly slow.

Transparent caching would be a huge boon to our company and a differentiating feature for Shippable.

On a much smaller scale, it would be great to have a button to invalidate the cache.  Presently, we notice the cache needs to be invalidated on Shippable, and then we switch over to Git, push a commit to a bogus branch with "[reset_minion]" in the title, and then delete the branch.  A button would be much more straightforward ;-)

**Comment by mbrodala** [comment]
There is a button to clear the container cache in the project settings.

**Comment by manishas** [comment]
Yes, there is a button to reset cache. Also, we have revamped caching in the new release and the container is now centrally cached after every build.
