### ISSUE TITLE
Installing specific version of npm doesn't work (today... worked yesterday)

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#1400]
Yesterday, I could specify which version of `npm` I wanted to use.  Today, it blows up:

![shippable___truly_fastest_ci_in_the_cloud](https://cloud.githubusercontent.com/assets/286588/7436837/39ba0822-f006-11e4-9ee1-b2aa52cfd31e.png)

**Comment by manishas** [comment]
@jeffkole can you point me to a specific build where this happened? I clicked through a few and cant find it.... also the latest builds have passed.

**Comment by jeffkole** [comment]
https://app.shippable.com/builds/5543e0de42da970c000ef44d

**Comment by lekhab** [comment]
@jeffkole - I see the builds on your project seem to be doing okay now. Closing this issue. Please re-open if this is still an issue.
