### ISSUE TITLE
Test reports and coverage not visible to public

### ISSUE THREAD

**Issue by schlegel11** [Shippable/support#1401]
I can't see test and code coverage reports unless i'am signed in.
Is this a normal behavior?

**Comment by manishas** [comment]
@schlegel11 yes this is by design as of now with one exception. If someone clicks on the build badge for public projects, they can view results without signing in.

We do have a feature request on our plate to make this public and we'll definitely address this.

**Comment by schlegel11** [comment]
Oh ok.
Thank you for your fast answer :)
