### ISSUE TITLE
Add sample for test visualization support with Scala's specs2 framework

### ISSUE THREAD

**Issue by jedesah** [Shippable/support#1403]
This is just a question of getting the specifics right of how to output the junit xml with specs2 and then where exactly to put those files for them to be picked up by Shippable. I haven't found it mentioned anywhere where exactly to put the xml files in order for them to be picked up.

I am also trying to figure ou the specs2 here: https://github.com/etorreborre/specs2/pull/368

**Comment by manishas** [comment]
Here are docs on where to put the xml - http://docs.shippable.com/en/latest/config.html#test-and-code-coverage-visualization

**Comment by manishas** [comment]
Closing. Please re-open if you still run into issues setting it up.
