### ISSUE TITLE
gulp: ../deps/uv/src/unix/core.c:422: uv__close: Assertion `fd > 2' failed.

### ISSUE THREAD

**Issue by andrewmichaelsmith** [Shippable/support#1404]
A gulp task to SCP some files after a successful load now consistently fails.

For the past 4 months this task has worked perfectly for over 80 builds. Now the past 3 builds have all failed. I have changed nothing on the host machine and the tasks succeeds from other servers.

The task:

```
gulp.task('upload', shell.task([                                                 
    'chmod 0600 id_rsa',                                                         
    'scp -iid_rsa -rpv www/* user@host:/path/'           
]));
```

The error:

```
[13:25:56] Starting 'upload'...
gulp: ../deps/uv/src/unix/core.c:422: uv__close: Assertion `fd > 2' failed.
[13:25:56] 'upload' errored after 228 ms
```

**Comment by manishas** [comment]
@andrewmichaelsmith i cannot find your account - are you using a different username to sign in?

**Comment by andrewmichaelsmith** [comment]
Hi

I'm using my bitbucket account, username me@andrewmichaelsmith.com

Thanks

On 4 May 2015 at 22:18, Manisha <notifications@github.com> wrote:

> @andrewmichaelsmith <https://github.com/andrewmichaelsmith> i cannot find
> your account - are you using a different username to sign in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1404#issuecomment-98852083>.
>



-- 
Andy Smith
http://andrewmichaelsmith.com | @bingleybeep

**Comment by andrewmichaelsmith** [comment]
@manishas did you get a chance to take a look at this? Just tried a build this afternoon and it's giving me the same error

Thanks!

**Comment by manishas** [comment]
@andrewmichaelsmith sorry we dropped the ball on this one with no follow up.... did your build work?

I see green builds for one project, so am closing this. If something is still not working as expected, please reopen and we'll take a look.
