### ISSUE TITLE
Automated deployment to Digital Ocean

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1405]
Hi,

I am looking forward to setup automated deployment to Docker instances on Digital Ocean. Do you have a tutorial/setup guide in regards to the same.

I need to deploy a Java app

Naveen

**Comment by lekhab** [comment]
@naveensky: We do have a guide and a sample for how to deploy a Ruby on Rails app to Digital Ocean in our docs here - http://docs.shippable.com/digitalocean/. We are working on adding one for Java - will keep you posted.

**Comment by jawaid** [comment]
@naveensky  We are building this functionality and you would see this soon.

**Comment by avinci** [comment]
At this time, we are keeping our system out of deploying directly to VMs without the use of some external tools like Chef and Puppet. Hence closing this.
