### ISSUE TITLE
Downgrade and refund

### ISSUE THREAD

**Issue by grepnull** [Shippable/support#1406]
Hello, I've been experimenting with your dedicated hosts and docker support in the past day and we've found that it doesn't support our needs. Could I get a refund? Thanks!

**Comment by manishas** [comment]
@grepnull We would love to get feedback about what you were looking for that was unavailable with our docker support.

Our dedicated hosts feature is in beta and is not the core offering of the $12/year plan. Our Startup plan gives customer 5 minions and is very competitively priced. Our terms and conditions clearly states that no refunds will be granted - http://www.shippable.com/tos.html

**Comment by grepnull** [comment]
How would I have been able to evaluate the dedicated hosts and docker support otherwise?
