### ISSUE TITLE
Can't run 'bower install' because of sudo

### ISSUE THREAD

**Issue by jaurand** [Shippable/support#1413]
I'm trying to run my tests for an ember-cli project, and I get the following error when running `bower install`

bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

If I use the `--allow-root` option, then phantomjs crashes on me:

 ember test
version: 0.2.3
0.2.3

Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Building
Built project successfully. Stored in "/root/workspace/src/github.com/mortgagemapp/members/tmp/class-tests_dist-DugD6Dwh.tmp".
not ok 1 PhantomJS - Browser "/root/workspace/src/github.com/mortgagemapp/members/node_modules/phantomjs/lib/phantom/bin/phantomjs /root/workspace/src/github.com/mortgagemapp/members/node_modules/ember-cli/node_modules/testem/assets/phantom.js http://localhost:7357/6927" exited unexpectedly.

1..1
 tests 1
 pass  0
 fail  1

These are builds 55490e8542da970c000f2a40 and 554909eb42da970c000f29cb

My yml file looks like this:
<pre>
language: node_js

# version numbers
node_js:
  - 0.12

build_image: shippableimages/ubuntu1204_nodejs
archive: true

before_install:
# Activate the required node.js version
  - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
  - node --version

#before_install:
install:
 - npm install -g ember-cli
 - npm install -g bower
 - npm install
 - bower install
before_script:
 - mkdir -p shippable/testresults
 - rm -f shippable/testresults/*

# # write the rspec tests to the output dir
script:
 - ember test
</pre>

**Comment by jaurand** [comment]
I should add that the above phantomjs error is when I have `npm install phantomjs` in my install step.  If I leave that out I get:
<pre>
Building
Built project successfully. Stored in "/root/workspace/src/github.com/mortgagemapp/members/tmp/class-tests_dist-I3XUa1vv.tmp".

1..0
# tests 0
# pass  0
# fail  0

# ok
No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.
</pre>

There are five tests that should run.  If I try to install phantomjs with `npm install -g phantomjs` I get:
<pre>
npm install -g phantomjs
/root/.nvm/versions/v0.12.2/bin/phantomjs -> /root/.nvm/versions/v0.12.2/lib/node_modules/phantomjs/bin/phantomjs

> phantomjs@1.9.16 install /root/.nvm/versions/v0.12.2/lib/node_modules/phantomjs
> node install.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/root/.nvm/versions/v0.12.2/lib/node_modules/phantomjs/install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "/root/.nvm/versions/v0.12.2/bin/node" "/root/.nvm/versions/v0.12.2/bin/npm" "install" "-g" "phantomjs"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/workspace/src/github.com/mortgagemapp/members/npm-debug.log
</pre>

**Comment by nathanmarks** [comment]
@jaurand @manishas I am running bower and phantomjs without a problem.

```
  - npm install -g bower gulp karma-cli
  - npm install
  - bower install --allow-root
```


```
> phantomjs@1.9.16 install /root/workspace/src/bitbucket.com/poweredbysearch/sme-reporting/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /root/workspace/src/bitbucket.com/poweredbysearch/sme-reporting/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Received 12854K total.
Extracting tar contents (via spawned process)
Removing /root/workspace/src/bitbucket.com/poweredbysearch/sme-reporting/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Copying extracted folder /root/workspace/src/bitbucket.com/poweredbysearch/sme-reporting/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1430928533459/phantomjs-1.9.8-linux-x86_64 -> /root/workspace/src/bitbucket.com/poweredbysearch/sme-reporting/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /root/workspace/src/bitbucket.com/poweredbysearch/sme-reporting/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs
```

**Comment by bradenstenning** [comment]
@jaurand I ran into the same problem and was able to run tests using the distribution version of phantomjs.

    ...
    build_image: shippableimages/ubuntu1404_nodejs
    ...
    install:
      - apt-get install phantomjs
      - npm install -g ember-cli
      - npm install -g bower
      - npm install
    ...

Eventually I just went with using a dedicated host and used a custom docker image that had the most recent version of phantomjs already installed. That works nicely, if you have the dedicated host.

**Comment by allebdev** [comment]
Also, phantomjs may crashes due to the lack of some dependencies.
To fix this issue you can install the following packages:
`apt-get install libfreetype6 libfontconfig`

It works with `build_image: shippableimages/ubuntu1404_nodejs`

**Comment by manishas** [comment]
Sorry we haven't actively helped out with this. @jaurand Do the comments solve your issue? Let me know if you have any more questions.

**Comment by manishas** [comment]
Thanks to everyone who helped answer :)

**Comment by manishas** [comment]
Closing this issue. Please re-open if you still run into this.
