### ISSUE TITLE
pg_config executable not found - psycopg2 install

### ISSUE THREAD

**Issue by fkumro** [Shippable/support#1414]
During the install process, pip is ran to install the necessary packages. One of those packages is `psycopg2>=2.6,<=2.6.99` but it fails to install due to missing pg_config (log below). I am using python 3.4 with the shippableimages/ubuntu1404_python build image.

Failed build link: https://app.shippable.com/builds/554922d842da970c000f2c0c

```
# language setting
language: python

# specify the build image
build_image: shippableimages/ubuntu1404_python

# set version numbers
python:
  - "3.4"
```

```
Downloading/unpacking Django==1.8.0 (from -r requirements/base.txt (line 1))
Downloading/unpacking psycopg2==2.6 (from -r requirements/base.txt (line 2))
  Running setup.py (path:/root/ve/build/psycopg2/setup.py) egg_info for package psycopg2
    
    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/psycopg2.egg-info

writing pip-egg-info/psycopg2.egg-info/PKG-INFO

writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt

writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt

writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'

warning: manifest_maker: standard file '-c' not found



Error: pg_config executable not found.



Please add the directory containing pg_config to the PATH

or specify the full executable path with the option:



    python setup.py build_ext --pg-config /path/to/pg_config build ...



or with the pg_config option in 'setup.cfg'.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /root/ve/build/psycopg2
Storing debug log for failure in /root/.pip/pip.log
```

**Comment by fkumro** [comment]
@manishas Any updates available? Stopping all builds on my end from running.

**Comment by geraldroy** [comment]
Getting the same problem. Any updates?

**Comment by manishas** [comment]
We'll look into this and get back to you. Thanks!

**Comment by fkumro** [comment]
Any updates? Leaving us dead in the water...

**Comment by manishas** [comment]
@fkumro sorry for the late response on this. Can you send us your shippable yml? Our language specific images are very barebones and do not come with postgres installed.

**Comment by fkumro** [comment]
@manishas Thanks, would be helpful to add that to the postgres section in the docs to avoid any confusion. (We support PostgreSQL 9.1, 9.2 and 9.3 versions and by default, version 9.2 is installed on our minions. ).

````
# language setting
language: python

# specify the build image
build_image: shippableimages/ubuntu1404_python

# set version numbers
python:
  - "3.4"

# setup test database
before_script:
  - psql -c 'create database test;' -U postgres

# install repds using the shippable requirements file
install: "pip install -r requirements/shippable.txt --use-mirrors"

# what command to execute for tests
script:
  - python manage.py --settings=api.settings.shippable test
````

**Comment by manishas** [comment]
@fkumro our language specific build images like the one you're using do not come with any Postgres versions installed - http://docs.shippable.com/languages/images/

You can install Postgres using the method mentioned in https://github.com/Shippable/support/issues/746 and try your build again. 

Let me know if this works. Again, apologize for the late response.

**Comment by fkumro** [comment]
@manishas Reading fail on my part about no addons with language specific images.

**Comment by manishas** [comment]
@fkumro did your build work?

**Comment by lekhab** [comment]
@fkumro: closing this out. please feel free to re-open if this is still an issue.
