### ISSUE TITLE
Slowness to open project list

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1415]
This [URL](https://api.shippable.com/projects/540e77a63479c5ea8f9e9017/builds?page=0&pageSize=20) takes a lot of time to load while [listing our builds](https://app.shippable.com/projects/540e77a63479c5ea8f9e9017)...

Also, the total data transferred is 44.0Mb (which takes ~2min):

![screenshot from 2015-05-05 19 17 34](https://cloud.githubusercontent.com/assets/245435/7484098/6d92598a-f35b-11e4-957c-9b635df62ce0.png)

The overall client performance is pretty bad today too... 

![screenshot from 2015-05-05 19 26 02](https://cloud.githubusercontent.com/assets/245435/7484235/a59e00e4-f35c-11e4-8233-849c3136c166.png)

Can we improve this on our side in some way?

Thanks!

**Comment by manishas** [comment]
@caarlos0 yes, we deployed some new stuff and the system was a bit slower than normal today. It should be back to normal now.

**Comment by caarlos0** [comment]
@manishas OK, it seems better already =D

Many thanks! :beers:
