### ISSUE TITLE
where is rails test.log ?

### ISSUE THREAD

**Issue by murtyk** [Shippable/support#1416]
I searched the docs and web but not able to find information about test.log file. When I run specs locally, it generates test.log which is quite helpful in debugging. Can you please let me know if shippable build process generates test.log? If yes, how to get it?

**Comment by rageshkrishna** [comment]
Hi @murtyk! If your build generates the file, all you need to do is copy it to the `shippable` directory and set `archive: true` in your YML file. After the build you'll be able to download this file and take a look at the logs.

**Comment by murtyk** [comment]
Hi @rageshkrishna 
 Yes archive: true is there but the archive has only test results, code coverage and capybara screenshots. It does not have test.log which is supposed to have rails server log entries. When I run the rspec locally, we do get test.log. Is there a way to get this?

**Comment by rageshkrishna** [comment]
Setting `archive: true` only creates an archive out of the contents of the `./shippable` folder if it exists at the root of your project. If your `test.log` file is being created somewhere else, you should `cp test.log ./shippable` in the YML (maybe in the `after_script` section) so it gets picked up.

**Comment by lekhab** [comment]
@murtyk - hoping this was resolved by the earlier solution. please re-open if you are still facing issues.
