### ISSUE TITLE
Builds hanging and GitHub Webhooks going unnoticed

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1422]
All of our builds are down again...

If I manually kick them off they get stuck at this screen:

![screen shot 2015-05-07 at 6 37 46 am](https://cloud.githubusercontent.com/assets/1522018/7516348/9cb3a560-f483-11e4-9048-0099ac41dac0.png)

@manishas Is this a known issue you guys are working on?

**Comment by phagunbaya** [comment]
Same here. @manishas Help needed !

**Comment by manishas** [comment]
Yes, we're looking at it.

**Comment by manishas** [comment]
Are your builds running now? Should be back up... Let me know.

**Comment by phagunbaya** [comment]
Seems to be resolved. Thanks !

**Comment by chriskinsman** [comment]
Looks to be resolved...
