### ISSUE TITLE
Help debugging phpunit issue

### ISSUE THREAD

**Issue by eventbase-web** [Shippable/support#1425]
Having an issue where a particular test is failing on the minion but not on our local environment.

What I'd like to do ideally is run the container locally to debug the issue. Is that possible?

**Comment by manishas** [comment]
@eventbase-web you cannot download the container directly from Shippable.

However, you can push the container to Docker Hub and download the container from there to debug.  Pushing to Docker Hub is documented [here](http://docs.shippable.com/en/latest/docker_build.html#push-to-docker-hub) 

Hope this helps.

**Comment by eventbase-web** [comment]
Thanks!
