### ISSUE TITLE
Builds started failing in npm shrinkwrap

### ISSUE THREAD

**Issue by henrjk** [Shippable/support#1426]
I started seeing build failures in npm shrinkwrap  during after_success. This used to work without showing errors in prior builds although nothing has changed as far as I can tell. The error seen in build 192.1 https://app.shippable.com/builds/554dd56dff724e0c00e50750 is this:

```console
npm ERR! Linux 3.13.0-43-generic
npm ERR! argv "node" "/home/shippable/.nvm/v0.10.35/bin/npm" "shrinkwrap"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.5

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: os-shim@0.1.2 /home/shippable/workspace/src/bitbucket.com/henkr/jetza/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync/node_modules/os-shim
npm ERR! extraneous: os-shim@0.1.2 /home/shippable/workspace/src/bitbucket.com/henkr/jetza/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync/node_modules/os-shim
npm ERR! extraneous: os-shim@0.1.2 /home/shippable/workspace/src/bitbucket.com/henkr/jetza/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync/node_modules/os-shim
npm ERR! extraneous: os-shim@0.1.2 /home/shippable/workspace/src/bitbucket.com/henkr/jetza/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/bin-check/node_modules/spawn-sync/node_modules/os-shim
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/shippable/workspace/src/bitbucket.com/henkr/jetza/npm-debug.log
```
Build 192.1 is a repeat build of one which succeeded earlier (both are on commit f4334cb).  The original build for that commit was 176.1
https://app.shippable.com/builds/553a472682cfa40b00ba5afb

Since the failing build I tried:
1. A build 193.1 using `npm install -g npm@next` instead of `npm install -f npm@2.1.5`. 
2. A build 194.1 with `npm@next` and which retries npm shrinkwrap but both these builds fail in the same way.

Do you have a suggestion what could have changed or be wrong?

**Comment by manishas** [comment]
we'll take a look at this

**Comment by henrjk** [comment]
I just happened to start another build to see whether there was any change before you commented, but the build still failed as before. 
Thanks for taking a look!

**Comment by manishas** [comment]
@henrjk looks like this fell off the radar. Sorry!

I checked your build history and looks like builds are working now. Can I close this issue? If you're still facing problems, please let me know and we'll follow up.

**Comment by henrjk** [comment]
This all of a sudden started working again. So I guess there is no point in trying to see what was happening now. Thank you!
