### ISSUE TITLE
wrong CI status displayed due to previous run of same HEAD commit in different branch

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1427]
* Scenario:
branch `master` and branch `develop` with different commit history (thus different codebase) both receive a PR from the same branch 'feature-X`

* Expected behavior:
Two CI builds, one per branch. Reporting separate statuses on each PR

* Actual behavior:
CI build runs on whichever branch's github postback received first by Shippable, and during that time its status is displayed on GH PR.
PR on branch `develop`  CI succeeds
PR on branch `master` (with entirely different history) displays green pointing to `develop` PR. In reality it should have failed.

I am assuming that this is due to you guys caching build statuses based on HEAD hash. This is not desirable though and can lead to trouble.

**Comment by manishas** [comment]
Thanks for reporting this. I'll enter this issue in our internal tracking system.

**Comment by manishas** [comment]
I don't think we can address this cleanly as of now.

Comments from our devs on this - 
GitHub uses the status of the head branch/commit to determine the pull request status: https://developer.github.com/v3/pulls/#link-relations

The only other way I can think of to put a status on a pull request would be to add a comment to the pull request, which wouldn't change the color of the merge button and may be harder for a reviewer to find.

**Comment by pmoust** [comment]
The PR list when two branches (let A, B) from another branch (let C) contains only C-to-A or B-to-A.
I think this is related.
