### ISSUE TITLE
How to increase memory for a build?

### ISSUE THREAD

**Issue by markschaake** [Shippable/support#1429]
We haven't had a successful build in a while: https://app.shippable.com/projects/54612991c6f0803064f40850

We assume it is due to insufficient memory on our build instance. Is there a way to increase memory for a specific project?

**Comment by markschaake** [comment]
Just happened again. https://app.shippable.com/builds/5550f7a8ff724e0c00e521ae

How much memory is available to a build instance?

**Comment by markschaake** [comment]
Here is the jvisualvm heap monitoring during a local build (which succeeds):

![screen shot 2015-05-11 at 1 19 59 pm](https://cloud.githubusercontent.com/assets/181607/7574220/8a7c1cf0-f7e0-11e4-91cc-91f4e03b7d92.png)

**Comment by schmmd** [comment]
+1 on getting an answer to "How much memory is available to a build instance?"

I searched but couldn't find it in the documentation.

**Comment by markschaake** [comment]
Tried setting the SBT_OPTS environment variable to specify a max heap of 8g per http://stackoverflow.com/questions/15280839/how-to-set-heap-size-for-sbt. Didn't make a difference. 

See: https://app.shippable.com/builds/55511ecfff724e0c00e52541

**Comment by schmmd** [comment]
The iteration on this is horrible.  It doesn't cache, since the builds don't fail.  So whenever I make a change, I don't know if it's succeeded for 20 minutes.

**Comment by schmmd** [comment]
Interestingly if I manually set the environment variables:

```
JAVA_OPTS='-Xmx4g'; SCALA_OPTS='-Xmx4g'; SBT_OPTS='-Xmx4g'; sbt formatCheckStrict styleCheckStrict test
```

The build still fails and I get the following message:

> Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

Maybe my settings are being overridden somehow?

**Comment by manishas** [comment]
All our containers now have 2 cores, 4 GB RAM. No way to increase memory for a build as of now, but we will consider bigger containers for paid plans in the future.

Closing this issue.
