### ISSUE TITLE
How to see npm-debug 'additional errors' for a node app?

### ISSUE THREAD

**Issue by rajaraodv** [Shippable/support#1431]
I am hitting some issue on shippable that I can't reproduct on localhost. I see a message from npm that says: See additional information at: "/home/shippable/workspace/src/github.com/rajaraodv/nin/npm-debug.log". How to access that file?

**Comment by rageshkrishna** [comment]
@rajaraodv You can `cat` the file in the `after_failure` section of your YML file like this:

````
after_failure:
 - if [ -f /home/shippable/workspace/src/github.com/rajaraodv/nin/npm-debug.log ]; then cat /home/shippable/workspace/src/github.com/rajaraodv/nin/npm-debug.log; fi
````

This will allow you to see it in the console output for the build.

**Comment by manishas** [comment]
closing this issue.
