### ISSUE TITLE
Secure env vars were lost

### ISSUE THREAD

**Issue by pcullin-ratio** [Shippable/support#1432]
My secure environment variables mysteriously stopped working earlier today, causing build failures. Took me a few minutes to figure out that this was the problem, but there were notices in my account messages indicating the `-secure` env vars section of my Shippable.yml file were not able to be decrypted by the service. I had not made any changes to that section of my Shippable.yml file, nor any other changes (like to the variables themselves) that explain why that happened. To fix, I simply re-hashed them and updated my Shippable.yml with the new values.

**Comment by manishas** [comment]
did it work after rehashing them? I'll chat with the team and find out why this might have happened.

**Comment by pcullin-ratio** [comment]
Yes it worked after rehashing and updating the `-secure` value in my shippable.yml

**Comment by manishas** [comment]
@pcullin-ratio we're not sure what happened here and we cannot repro. I am closing this issue since your issue was worked around. I'll keep an eye on this in the future.
