### ISSUE TITLE
Cannot access my company's repo

### ISSUE THREAD

**Issue by sayanh** [Shippable/support#1433]
Hello administrator,

Although I can access my company's repo in github, I cannot see those repos in shippable. Only the public repos are visible. Can you please check?

Thanks,
Sayan

**Comment by manishas** [comment]
@sayanh please ensure that you've given us access to your private repos... on your dashboard, at the top right, it should say 'Private repos ON'. If it shows off, you will need to click on that control to authorize us to access private repos. 

Please click on 'Sync account' after that and you should see your private repos.

**Comment by sayanh** [comment]
@manishas Thanks a lot. I got this.
