### ISSUE TITLE
Build number format for docker images

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1434]
Hi, 

According to your blog article http://blog.shippable.com/immutable-containers-with-version-tags-on-docker-hub all pushed docker images are provided with a tag which contains the build number. 

My images are tagged with the branchname + build number (without the revision number).

In my yaml I want to update some metadata file in s3 with the docker image version: 
- sed -e "s;%BUILD_NUMBER%;$BUILD_NUMBER;g" ecs/machinelogservice.json > ecs/tmp.json

The build number contains the build number + revision (in my case 60.1). 

Is there any environment variable which contains the tag / version info of my docker image?

**Comment by manishas** [comment]
@rvdwijngaard I will put this on our plate as a feature request.

**Comment by manishas** [comment]
this has been completely redone and you now have complete control over tags. more on this here - http://docs.shippable.com/ci_configure/#pushing-an-image-to-a-registry
