### ISSUE TITLE
Slow bundle install

### ISSUE THREAD

**Issue by Kukunin** [Shippable/support#1435]
My bundle install takes too much time, last time it took 850 seconds. I don't have a lot of gems, my Gemfile contains 69 gems.

It seems, the internet connection is really slow

**Comment by manishas** [comment]
@Kukunin I see you've turned on caching... it will take a few builds for the cache to be on each build host. I'd give it a few more builds and if caching doesn't kick in, we'll take a deeper look.

**Comment by Kukunin** [comment]
When will you increase your prices to buy more servers to provide better speed?

**Comment by Kukunin** [comment]
My all tests takes literally 5 minutes on my local machine, but I have been waiting for a hour already, and they aren't finished yet. I'd love to pay you reasonable money to speed up the process.

**Comment by Kukunin** [comment]
The build has finished a 10-15 minutes ago (after 1.5 hours of processing), and now it says "Duration is 24 minutes).

**Comment by jamesmk** [comment]
+1 

`bundle install` is exceptionally slow in the containers. This build took almost 15 mins to bundle, when it take 4 mins locally. 
https://app.shippable.com/builds/55522a3dff724e0c00e5391f

**Comment by manishas** [comment]
@Kukunin @jamesmk You can now use custom docker images for your builds. If you include everything you need for your builds in the image, you can get around the periodic slowness in bundle installs.

For more information on how to use custom images, please look at http://docs.shippable.com/docker_registries/
