### ISSUE TITLE
Stash (Atlassian) support on dedicated host (question)

### ISSUE THREAD

**Issue by vkuusk** [Shippable/support#1436]
I was wondering if support for Stash is somewhere in the near future on Shippable roadmap.
( Some time ago it was a question about support for other git repos (e.g. stash) -  #45  )

Our use case is that we can not mirror to the github for security reasons and we are running shippable with dedicated host. So both Stash and Dedicated host are on the same network behind firewall.

**Comment by manishas** [comment]
Thanks for the feature request! This is on our radar already, so will leave this open until we have an update.

**Comment by mathieumg** [comment]
+! :+1:

**Comment by manishas** [comment]
Dup of #45 

I am tracking all requests for additional source control providers in that issue.
