### ISSUE TITLE
Take my money, please?

### ISSUE THREAD

**Issue by thockin** [Shippable/support#1437]
I *desperately* want to pay money to make our builds faster and more reliable.  It's basically useless as it is.  And yet I can not figure out how to do this.  I got to pricing, clicked "sign up now" and it just took me to the project dashboard.

How do I upgrade our (OSS) project to some large number of parallel builds on dedicated machines.  Please?  Today, please?  I have money...

**Comment by thockin** [comment]
I found how to add dedicated nodes but it says I do not have permission.  What permission do I need and how do I get it?  I have VMs waiting to be used.

**Comment by vkuusk** [comment]
As far as I understand, you have to be an owner of your github organization. At least it was the case for our org.

**Comment by phagunbaya** [comment]
@thockin : @vkuusk is correct.

**Comment by manishas** [comment]
@thockin I am closing this issue since this is being discussed over email.

**Comment by manishas** [comment]
Actually, leaving it open until we resolve this.

**Comment by manishas** [comment]
Closing this issue. @thockin let's follow up over email and track this further.
