### ISSUE TITLE
"Error parsing shippable.yml in <project>" should indicate which line

### ISSUE THREAD

**Issue by xorgate** [Shippable/support#1442]
As title indicates.

I am now left wondering what's wrong. Yamllint sees no issues with my shippable.yml file.

Also such an error should be more prominent, since it's relatively hidden in 'Unread Notifications'. 
Would be a good idea to show the red error icon in this tab, I think.

**Comment by manishas** [comment]
We have completely redone the UI around this and this should show an error notification on the same page. Closing this issue.
