### ISSUE TITLE
Waiting for build information...

### ISSUE THREAD

**Issue by gegere** [Shippable/support#1443]
Hello, I have a build that does not seem to be building. I have started to troubleshoot the node. There was an issue with the disk space on the node hosted within Digital Ocean, it was full. I deleted the node and created a new one with 2gb RAM and 30gb Disk. The same problem is occurring were the build instance is "Waiting for build information..." several months ago there was a poke need on Shippable's end to get the system building again.

I am trying to get to the bottom of this to learn if I am doing something wrong.

Thanks!

**Comment by manishas** [comment]
can you point us to the build link? thanks!

**Comment by gegere** [comment]
The link: https://app.shippable.com/builds/55536dcd3566980c00a3b90a

**Comment by manishas** [comment]
sorry, also project link please. for some reason, the build link isn't working.

**Comment by gegere** [comment]
Yes, this seems to be the issue. It is like it is starting and then disappearing. Project link: https://app.shippable.com/projects/54cf015b5ab6cc13528a7b6a

**Comment by gegere** [comment]
I think the issue with this instance was a merge conflicted **shippable.yml** file. I have revised and pushed the build is now running here: https://app.shippable.com/builds/555373103566980c00a3b98f

**Comment by gegere** [comment]
**Ok solid progress all day!**

The build is completing and the tests I have created are passing. The Docker image is ready to be pushed to the Docker repo. Here is the [build progress](https://app.shippable.com/builds/5553c47a3566980c00a3c242)

```
 sudo docker push htmlgraphic/apache:master.95 2>/tmp/push-error.txt
 sudo docker push htmlgraphic/apache:master.95 2>/tmp/push-error.txt
 sudo docker push htmlgraphic/apache:master.95 2>/tmp/push-error.txt
 sudo docker push htmlgraphic/apache:master.95 2>/tmp/push-error.txt
 sudo docker push htmlgraphic/apache:master.95 2>/tmp/push-error.txt
 sudo docker push htmlgraphic/apache:master.95 2>/tmp/push-error.txt
 sudo docker push htmlgraphic/apache:master.95 2>/tmp/push-error.txt
 sudo docker push htmlgraphic/apache:master.95 2>/tmp/push-error.txt
 sudo docker push htmlgraphic/apache:master.95 2>/tmp/push-error.txt
Image push is already in progress, trying again after 5 seconds.
Image push is already in progress, trying again after 5 seconds.
Image push is already in progress, trying again after 5 seconds.
Image push is already in progress, trying again after 5 seconds.
Image push is already in progress, trying again after 5 seconds.
Image push is already in progress, trying again after 5 seconds.
Image push is already in progress, trying again after 5 seconds.
Image push is already in progress, trying again after 5 seconds.
Image push is already in progress, trying again after 5 seconds.
Image push is already in progress, trying again after 5 seconds.
```

**Comment by manishas** [comment]
Great news! Closing this issue... I have responded to your email about source location.

**Comment by gegere** [comment]
Everything is good. But... my last comment. 

```
Image push is already in progress, trying again after 5 seconds.
```

Is this an issue I need to understand anything about?
