### ISSUE TITLE
Mock not working in Python

### ISSUE THREAD

**Issue by lfrodrigues** [Shippable/support#1444]
Hi,

I'm using 
```
@mock.patch('storages.backends.s3boto.S3BotoStorage', FileSystemStorage)
```
In my test code.

Locally my test code is working fine but when it is run at Shippable mock doesn't patch correctly and S3BotoStorage gets used. Any idea what could be wrong?

**Comment by manishas** [comment]
@lfrodrigues can you post a link to a failed build?

**Comment by lfrodrigues** [comment]
Here it is:
https://app.shippable.com/builds/55546f0ed81dea0d0039c849

Currently it is working because I went around the problem

**Comment by manishas** [comment]
The build system upgrade should have fixed this issue. Please let us know if this doesn't work.
