### ISSUE TITLE
default workspace environment variable

### ISSUE THREAD

**Issue by Zambonilli** [Shippable/support#1445]
I'm not seeing an environment variable for the root of the repository directory.  I had to manually cd to /home/shippable/workspace/src/github.com/ with my repo name.   It seems like this would be something that is standard environment variable so if the dir convention ever changes it doesn't break a slew of builds.

**Comment by manishas** [comment]
@Zambonilli sorry for the delay. The env variable you're looking for is SHIPPABLE_REPO_DIR

I realized we've missed it in our documentation, so will add it in.

Hope this helps.
