### ISSUE TITLE
Best practices for using Postgres 9.4

### ISSUE THREAD

**Issue by akl32** [Shippable/support#1446]
Hi all,

I know you haven't added 9.4 to the available images yet, but I'm wondering what the best practices are for an app that needs to use Postgres 9.4. Should we be building our own Docker containers with it installed? Is there a way to install 9.4 in the "install" section of shippable.yml then stop the 9.3 instance before running 9.4?

All best,
Alex

**Comment by manishas** [comment]
You can do one of several things -

- Build your own docker image with Postgres 9.4 and use that for your builds. You will need dedicated hosts to do this.
- Start with one of our barebones images from our language specific images which do not come with a default Postgres installed and you can install in your yml. More on this at http://docs.shippable.com/languages/images/
