### ISSUE TITLE
apt-get update permission denied

### ISSUE THREAD

**Issue by pmacosta** [Shippable/support#1447]
As part of my shippable.yml file I do an distro update with "apt-get update" (I need to do this to pick up newer versions of packages that are not in the image). I am getting the error below. This was working before I got hit by the timeout errors which appear to have gone away.

shippable_retry apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

**Comment by manishas** [comment]
@pmacosta I see one enabled repository for you and that doesn't seem to run into this issue. can you point me to a build link?

**Comment by pmacosta** [comment]
The putil repository is failing (the only one that I have enabled). Latest
(as of now) changeset is 7bf28ef
<https://bitbucket.org/pacosta/putil/commits/7bf28ef94d887414ec2f6a8fd120838142470dfe>.
As of this writing the last 5 builds have failed.

Pablo

**Comment by rageshkrishna** [comment]
@pmacosta I noticed your builds are running on the minv2 image. Please try `shippable_retry sudo apt-get update` instead. This should get it working for you.

**Comment by pmacosta** [comment]
That fixed the apt-get update issue, now I am getting time-out errors again 






On Wed, May 13, 2015 at 9:15 PM -0700, "Ragesh Krishna" <notifications@github.com> wrote:












@pmacosta I noticed your builds are running on the minv2 image. Please try shippable_retry sudo apt-get update instead. This should get it working for you.

**Comment by manishas** [comment]
Closing this issue. Please comment or re-open if you're still running into this.
