### ISSUE TITLE
Got "Permission error" when building

### ISSUE THREAD

**Issue by QuantumGhost** [Shippable/support#1448]
I have code below in my shippable.yaml

```yaml
  - sudo echo 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' > /etc/apt/sources.list.d/pgdg.list
```

but I got an error saying `/home/shippable/f5d76c29-ca20-4563-9be9-2c12bdb1232b.sh: line 89: /etc/apt/sources.list.d/pgdg.list: Permission denied` when building. I really don't know why this would happen.

**Comment by rageshkrishna** [comment]
Hello, @QuantumGhost. This fails because sudo is only running echo. The redirection to the file is done by the shell, which is still running as a regular user. You can use `tee` instead like this:

````
before_install:

echo 'deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' | sudo tee --append /etc/apt/sources.list.d/pgdg.list
````

**Comment by QuantumGhost** [comment]
It works.
Thanks for your help.
