### ISSUE TITLE
Builds fail - Timeout when pushing container

### ISSUE THREAD

**Issue by nimshkedy** [Shippable/support#1449]
This started happening very often - see attached image:
![screen shot 2015-05-14 at 9 31 30 am](https://cloud.githubusercontent.com/assets/796461/7627123/12b61840-fa1c-11e4-9bed-63f8cefb2b9d.png)

Details:
- *Link to the failed build*: https://app.shippable.com/builds/5553730d3566980c00a3b98e
- *github account which enabled this repo*: https://github.com/thumzap

Here's the relevant part of shippable.yml
`commit_container: pelegb/thumzap-server-android`

**Comment by manishas** [comment]
@nimshkedy looks like your builds are working now. We did push some fixes to this workflow over the last few days.

Let us know if you run into this again. Thanks!
