### ISSUE TITLE
save_coverage_reports error

### ISSUE THREAD

**Issue by jonmer85** [Shippable/support#1450]
Hi,
I recently changed some of my coverage configuration to include some omissions of files that I don't want to count towards my test coverage. I now see that the save_coverage_reports step is failing and I don't get any errors to help me determine the problem. I confirmed that the changes on my local environment work just fine and the produced coverage files are of similar format.

The build in question is https://app.shippable.com/builds/555413c64240ea0b00c2aad6

Thanks,
Jon

**Comment by manishas** [comment]
@jonmer85 sorry for the delay in responding. are you still running into this?

**Comment by jonmer85** [comment]
I am yes. I was experimenting in that branch I sent you.

**Comment by manishas** [comment]
We have redone our coverage reports handling with the build system upgrade. This should be fixed now. Please let us know if this doesn't work.
