### ISSUE TITLE
Containers still running on cancelling a build though UI

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#1451]
I found a weird issue where on cancelling a build on UI did not stop the running docker containers for that build. It's on dedicated shippable host. Any idea ?

**Comment by manishas** [comment]
This is a known issue and will be addressed in our next update.

**Comment by abhijitkini** [comment]
Canceling a build in UI that stops all running containers for that build is now available. Upon canceling builds now, all customer spun containers will be removed. The images will remain though as it helps with future pulls if the machine is still active.
