### ISSUE TITLE
RethinkDB 2.x

### ISSUE THREAD

**Issue by zedtux** [Shippable/support#1452]
I've migrated my application to RethinkDB version 2.0.1 and the build is no more passing as you're using a version 1.x.

Is there a way to specify the version I want to use in the `shippable.yml` file ? Or does it need to be implemented ?

**Comment by manishas** [comment]
@zedtux instead of specifying rethinkdb in the services tag of your yml, you can install the version you need with apt-get install in the appropriate section of your yml. Let me know if that works for you.

**Comment by zedtux** [comment]
Ubuntu do not have a rethinkdb package to be install simply with `apt-get install` unfortunately.

RethinkDB documentation for Ubuntu is here: http://www.rethinkdb.com/docs/install/ubuntu/.
Can you please tell me how to make it working with Shippable ?

**Comment by manishas** [comment]
@zedtux you can install in your shippable.yml based on the link you have in your comment above - 

```
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb
```
You will also need to start it explicitly in your yml.
Does this work for you?

**Comment by zedtux** [comment]
It's working, thank you @manishas.

**Comment by dunnock** [comment]
Thanks for help, worked for me too with build_image: shippableimages/ubuntu1204_nodejs!
