### ISSUE TITLE
"No tests found.[test(AVD) - 4.4.2]" on android unit testing exampleApp

### ISSUE THREAD

**Issue by mario-naether** [Shippable/support#1453]
Hi,
i has a small issue on Shippable.
I write a Sample Android app and hostet on bitbucket. (https://bitbucket.org/mnaether/sampleapp)
my builds failed in the shippable Project with following error on command:
"gradlew connectedAndroidTest build"

```
com.android.builder.testing.ConnectedDevice > No tests found.[test(AVD) - 4.4.2] FAILED 

No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).

:app:connectedAndroidTestDebug FAILED


FAILURE: Build failed with an exception.


* What went wrong:

Execution failed for task ':app:connectedAndroidTestDebug'.

> There were failing tests. See the report at: file:///home/shippable/workspace/src/bitbucket.com/mnaether/sampleapp/app/build/reports/androidTests/connected/index.html
```

All tests running completely on my Local Android Stuido.
What is wrong on my test or shippable config?

**Comment by mario-naether** [comment]
I have found the wrong configuration. The tests runing after I add the "testApplicationId" in build.gradle...

**Comment by mario-naether** [comment]
ok, the workaround with the "testApplicationId" works only for one build. 
All other builds has the same error "com.android.builder.testing.ConnectedDevice > No tests found.[test(AVD) - 4.4.2] FAILED"

**Comment by mario-naether** [comment]
Hi,

the command "curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator" dosn't download the shell script. I commit the Script to my Repro and all Tests and Emulators works successfully.

**Comment by manishas** [comment]
This issue was opened prior to the build system upgrade. Please let us know if this is still happening.

**Comment by boyue** [comment]
the command "curl http://is.gd/android_wait_for_emulator > android-wait-for-emulator" dosn't download the shell script. I commit the Script to my Repro and all Tests and Emulators works successfully.

Excuse me ， where is your Script?
