### ISSUE TITLE
Unable to Connect to Dedicated Host

### ISSUE THREAD

**Issue by leroyjware** [Shippable/support#1455]
I'm trying to connect to my dedicated host and I'm seeing the error below. I've already run the command that you provide on the host, so shippable user is there and the key has been added to authorized_keys:

Writing key to file
mode of '/tmp/9e5485fe-6113-451e-887b-9b77699069b3.rsa' changed from 0644 (rw-r--r--) to 0600 (rw-------)
KEY file created: /tmp/9e5485fe-6113-451e-887b-9b77699069b3.rsa
Writing script to file
Script file created: /tmp/9e5485fe-6113-451e-887b-9b77699069b3.sh
Permission denied (publickey). rsync: connection unexpectedly closed (0 bytes received so far) [sender] rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]

**Comment by leroyjware** [comment]
Ok. We got past this problem. It was incorrect permissions on the authorized_keys file. We still have a problem, however. The host says ready, but our builds are not running.

**Comment by manishas** [comment]
@leroyjware is this still happening?

**Comment by leroyjware** [comment]
No. We got it figured out. Thanks! :)

---
Leroy Ware
*DeepRapid Design Studio, LLC.*
*Web applications and cloud support.*
leroy@deeprapid.com
408-908-0214
www.deeprapid.com

**Comment by manishas** [comment]
That's great! Let us know if we can help with anything else.
