### ISSUE TITLE
'Cache Container' setting works only if 'Push Build' setting is enabled too.

### ISSUE THREAD

**Issue by allebdev** [Shippable/support#1456]
If both settings are enabled then 2nd and next builds use previous cached build results. If only 'Cache Container' setting is enabled, then cached results are not used. But it seems it should work separately and independent.

**Comment by smvv** [comment]
I'm experiencing the same issue.

**Comment by manishas** [comment]
We haven't been able to repro this, so closing this issue. 

Please let us know if you're still running into this. Thanks!
