### ISSUE TITLE
Build stuck at "waiting" for 7 minutes

### ISSUE THREAD

**Issue by davidthewatson** [Shippable/support#1457]
This build:

https://app.shippable.com/builds/555a198f591ea70b00b611de

Has been stuck at "waiting" for 7 minutes. I'm not sure how to proceed.

**Comment by manishas** [comment]
@davidthewatson build 40 is currently processing, so the build you posted a link to is queued since you have one build minion with your free plan.

**Comment by manishas** [comment]
Closing this issue since this is working as expected. Thanks!
