### ISSUE TITLE
Add better build artifacts handling.

### ISSUE THREAD

**Issue by RX14** [Shippable/support#146]
I would prefer the build artifacts to be handled like Jenkins. You should be able to upload multiple files by where they are instead or simply zipping the shippable folder. There should be an artifacts tab with all the different artifacts you specify and also a download of all of the artifacts (incl. code coverage and test results)
For example:
````yml
#shippable.yml

artifacts:
  - build/libs/Test-*.jar #Import a file
  - build/libs #Zip the libs folder and send it as an artifact
````

This would be a great addition to a service that I have otherwise found faultless (so far...)

**Comment by robertdfrench** [comment]
This would be a very cool feature to have. Is it still in the pipeline?

**Comment by manishas** [comment]
We have moved away from artifacts handling on behalf of the user in our latest release. You will need to push artifacts in your shippable.yml, which is documented here - http://docs.shippable.com/ci_configure/#build-artifacts

Closing as deferred. We will get back to this at a future time if there is enough demand in this area.

**Comment by nealeu** [comment]
@manishas Can you provide a URL to replace the dead one in your last comment?

Are there any good examples of pushing an artifact through a build pipeline (e.g. a Docker image or a file such as a .jar) ?
