### ISSUE TITLE
can't pull custom build_image on dedicated node

### ISSUE THREAD

**Issue by alexanderlamb** [Shippable/support#1460]
Recently, our custom build_image isn't being pulled, only the default shippable/minv2 image is being used when running builds on a dedicated node.

We've made adjustments to our shippable.yml file to see if something had changed, but so far we haven't been able to make any progress.  Previously our configuration was working as expected and pulling a custom image from dockerhub.

Example build: https://app.shippable.com/builds/555a4b7a19c6df0c003e6e3b

**Comment by ragsden** [comment]
@alexanderlamb : The project setting tab had minv2 as the pull image name. I have fixed it to use your  custom  build image.

**Comment by alexanderlamb** [comment]
@ragsden ahh yes, thank you!
