### ISSUE TITLE
image exists, skipping pull

### ISSUE THREAD

**Issue by iancrosser** [Shippable/support#1461]
I'm using a shippable.yml with a custom build image on a dedicated host.  However after updating the image and pushing it to docker hub every build is failing due to the new image not being pulled.  Is there a way to get the image to update without logging into the dedicated host and updating the image manually?

https://app.shippable.com/builds/555c2c4a64b96c0c002e248d

**Comment by manishas** [comment]
Can you try including [reset_minion] in your commit message and try again? 
http://docs.shippable.com/yml_reference/

If that doesn't work, try resetting the host. 

Let me know if these suggestions work.

**Comment by iancrosser** [comment]
putting [reset_minion] did not work and neither did resetting the host.  I removed the docker image manually from the dedicated host and it pulled successfully again. Until we have an update to the image again I won't know if things are resolved so I will revisit this issue when that happens.

**Comment by manishas** [comment]
We pushed a fix for this a few minutes ago. I am closing this issue but please do reopen if it happens again. Thanks!

**Comment by manishas** [comment]
We pushed a fix for this a few minutes ago. I am closing this issue but please do reopen if it happens again. Thanks!

**Comment by n0mer** [comment]
@manishas , so how to manually clear already fetched image?

"Force Synchronize Project" and "Clear Cache" in project settings does not help, still having 'skipping pull' message

**Comment by rageshkrishna** [comment]
@n0mer We had a regression on this in the last couple of days, but it has been fixed now. Please open up another issue if you still see this happening. Thanks!

**Comment by n0mer** [comment]
@rageshkrishna , thanks for follow-up.

i created #2010, that aimed to help us troubleshoot issues like this.

currently it is impossible to tell what image is actually used.
