### ISSUE TITLE
Cannot pull image for dedicated host

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1462]
Since a screenshot says more than a thousand stacktraces

![screenshot 2015-05-20 11 57 04](https://cloud.githubusercontent.com/assets/2778689/7723227/6da8a130-fee7-11e4-863f-953f4fb82860.png)

**Comment by manishas** [comment]
@rogierslag docker hub was down for some time a few hours ago, so push and pull to Docker Hub was failing. Please re-open if you're still running into this.
