### ISSUE TITLE
Can't build with local import paths for Go

### ISSUE THREAD

**Issue by boj** [Shippable/support#1463]
The following import:

    import "myproject/subpath"

Fails with:

    import "myproject/subpath": import path does not begin with hostname

If you try the following:

    import "github.com/boj/myproject/subpath"

The build will fail on a private project because it expects to be able to import it like it was public.

My shippable.yml:

```
language: go

go:
  - 1.4

script:
  - export GOPATH=$SHIPPABLE_GOPATH
  - source $HOME/.gvm/scripts/gvm
  - gvm use go$SHIPPABLE_GO_VERSION
  - go get -d -v ./... && make integration

services:
  - rethinkdb
```

**Comment by manishas** [comment]
Old issue opened before release of the upgraded build platform. Closing.
