### ISSUE TITLE
Build not starting "Missing shippable.yml in "

### ISSUE THREAD

**Issue by gregv12** [Shippable/support#1467]
Hi,

I am trying out shippable with a new bitbucket account and project I created, but with no success. I receive the same error message everytime: Missing shippable.yml in "v12technology/gitflowsample1", which is strange as shippable.yml is in the root of my master and develop branches.

I have created a github account with the same mail but different username, not sure if this is having any effect. Can you help please.

Greg

**Comment by manishas** [comment]
@gregv12 can you send me your bitbucket username you're signing in with?

**Comment by gregv12** [comment]
my username for bitbucket is v12technology

On Wed, May 20, 2015 at 11:38 PM, Manisha <notifications@github.com> wrote:

> @gregv12 <https://github.com/gregv12> can you send me your bitbucket
> username you're signing in with?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1467#issuecomment-104063697>.
>



-- 
Regards,

Greg HIggins
CEO V12 Technology Limited

**Comment by manishas** [comment]
We haven't seen this before.... can you check if your yml is valid at http://www.yamllint.com/

**Comment by manishas** [comment]
If it is valid, can you send me a screenshot of your bitbucket repo showing shippable.yml at the root? i'll ask someone to take a look.

**Comment by gregv12** [comment]
Hi the yaml is valid, I edit it with netbeans which has a yml editor and I
have a tree view that only works if the yml is valid. I have also tested in
YAMLint with no issues

On Wed, May 20, 2015 at 11:45 PM, Manisha <notifications@github.com> wrote:

> We haven't seen this before.... can you check if your yml is valid at
> http://www.yamllint.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1467#issuecomment-104064837>.
>



-- 
Regards,

Greg HIggins
CEO V12 Technology Limited

**Comment by manishas** [comment]
manisha@shippable.com

**Comment by gregv12** [comment]
Hi,

attached two screenshots -

1/ from bitbucket showing file contents on master
2/ Lint validation of the yml file

On Wed, May 20, 2015 at 11:48 PM, Greg Higgins <
greg.higgins@v12technology.com> wrote:

> Hi the yaml is valid, I edit it with netbeans which has a yml editor and I
> have a tree view that only works if the yml is valid. I have also tested in
> YAMLint with no issues
>
> On Wed, May 20, 2015 at 11:45 PM, Manisha <notifications@github.com>
> wrote:
>
>> We haven't seen this before.... can you check if your yml is valid at
>> http://www.yamllint.com/
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Shippable/support/issues/1467#issuecomment-104064837>
>> .
>>
>
>
>
> --
> Regards,
>
> Greg HIggins
> CEO V12 Technology Limited
>



-- 
Regards,

Greg HIggins
CEO V12 Technology Limited

**Comment by gregv12** [comment]
I see a similar issue - https://github.com/Shippable/support/issues/816
could this be related?

On Wed, May 20, 2015 at 11:49 PM, Manisha <notifications@github.com> wrote:

> manisha@shippable.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1467#issuecomment-104065396>.
>



-- 
Regards,

Greg HIggins
CEO V12 Technology Limited

**Comment by gregv12** [comment]
Hi,

I see the problem, I had created an extra nesting in the directory
hierarchy, my fault. Thanks for your help, you can close.

regards

Greg

On Thu, May 21, 2015 at 12:01 AM, Greg Higgins <
greg.higgins@v12technology.com> wrote:

> I see a similar issue - https://github.com/Shippable/support/issues/816
> could this be related?
>
> On Wed, May 20, 2015 at 11:49 PM, Manisha <notifications@github.com>
> wrote:
>
>> manisha@shippable.com
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Shippable/support/issues/1467#issuecomment-104065396>
>> .
>>
>
>
>
> --
> Regards,
>
> Greg HIggins
> CEO V12 Technology Limited
>



-- 
Regards,

Greg HIggins
CEO V12 Technology Limited

**Comment by manishas** [comment]
Thanks for the clarification! Closing
