### ISSUE TITLE
 mvn: command not found

### ISSUE THREAD

**Issue by gregv12** [Shippable/support#1468]
Hi,
build: https://app.shippable.com/builds/555d16f0fba96c0c005d4159
builds are failing with error in script stage:
 mvn clean cobertura:cobertura
/root/54cd4df2-e7d2-43a7-a59b-07196a45b512.sh: line 86: mvn: command not found

shippable.yml:

jdk: 
  - oraclejdk8
language: java
notifications: 
  email: 
    recipients: 
      - greg.higgins@v12technology.com
script: 
  - "mvn clean cobertura:cobertura"
  - "mvn test"
 

Can you help please? 
 
regards

Greg

**Comment by gregv12** [comment]
screenshot of yaml - formatting not preserved in previous post

![shippable-yml-lintvalidation](https://cloud.githubusercontent.com/assets/12534882/7738813/970afbe0-ff50-11e4-8a06-609835d3d133.jpg)

**Comment by manishas** [comment]
@gregv12 our language specific images do not come with services and tools installed. Check out our docs at http://docs.shippable.com/languages/images/
You'll need to install mvn in your shippable.yml before calling mvn clean cobertura:cobertura

**Comment by gregv12** [comment]
Hi,

that has worked, thanks for the reply.
