### ISSUE TITLE
Waiting 40 minutes and counting for build

### ISSUE THREAD

**Issue by coreybutler** [Shippable/support#1469]
https://app.shippable.com/builds/555d104afba96c0c005d40b2

This is my first build, so I have no insight into why this has just been queued up for so long. I triggered it manually.

**Comment by manishas** [comment]
I don't see anything obviously wrong, so I've asked our engineers to take a look.

**Comment by manishas** [comment]
@coreybutler actually, i do think i know whats going on - your Settings indicate that you want to pull a private image from Docker Hub, run tests, then build a prod image from Dockerfile and push to GCR. 
If my understanding is correct, this is an unsupported scenario - http://docs.shippable.com/docker_registries/

We do not support pulling private images from one registry and pushing to another. You can pull an image from GCR and push to GCR for the same project.

**Comment by manishas** [comment]
I'll make sure we handle this scenario more gracefully within the product in the future.

**Comment by coreybutler** [comment]
Understood... and thank you.

Using the same project, I reconfigured it to pull a base image from GCR and push back to GCR. It doesn't even show a "waiting" status anymore.... the site just has the animated loading image. So, it doesn't even show up in my build as queued or waiting... it appears as though it never even gets registered. I am assuming I've missed something again in the configuration, but I have zero insight into what's happening (i.e. can shippable even reach my server?).

Thoughts? If you can access that same project, feel free to initiate a build from it so your engineers can see.... it's just a trivial test project.

**Comment by coreybutler** [comment]
So right after I made this comment, I got 3 emails and the status changed to "timed out". All of the builds were listed (they weren't before), and the console log is completely blank.

https://app.shippable.com/builds/555e4588fba96c0c005d5a9b

**Comment by manishas** [comment]
we're taking a look at this...thanks!

**Comment by manishas** [comment]
@coreybutler you have a dedicated host with  GNU/linux but we only support Ubuntu at this point. Can you please try with an Ubuntu host? 
http://docs.shippable.com/config/#dedicated-hosts outlines minimum requirements for a host.

**Comment by coreybutler** [comment]
Taking me awhile to get this (we're a CentOS/CoreOS shop).

**Comment by manishas** [comment]
Closing this issue. @coreybutler let me know if you have any other questions.
