### ISSUE TITLE
how to  run the the Keytool utility to get the SHA-1 fingerprint of the certificate in the shippable minion?

### ISSUE THREAD

**Issue by cribello** [Shippable/support#147]
I need to get the  SHA-1 fingerprint of the certificate from minion where build is happening to be able to use Google Plus SignIn in my android app.. Steps are mentioned in the following link..
    
    https://developers.google.com/+/quickstart/android#step_1_enable_the_google_api

how to  run the the Keytool utility to get the SHA-1 fingerprint of the certificate in the shippable minion?

**Comment by manishas** [comment]
This is not on our plate for now. I am marking this postponed and we will revisit when we plan our next milestones.
