### ISSUE TITLE
How do I upgrade my account to the Startup plan?

### ISSUE THREAD

**Issue by tonym2105** [Shippable/support#1471]
I would like to upgrade my plan to the startup plan, but I do not see the option when I log in?

**Comment by manishas** [comment]
@tonym2105 you will need to navigate to the Organization you want to upgrade. Click on Plans and Billing on the top right of that page, add your card information, and then choose Startup plan.

Only owners can upgrade plans, so please make sure you have owner permissions to the org on GitHub/Bitbucket.

**Comment by lekhab** [comment]
Our new version went live mid-June. Please check our FAQ here - http://docs.shippable.com/faq/#how-can-i-update-my-shippable-plan  that explains how to upgrade plans in the new version.

Closing the issue.
