### ISSUE TITLE
Cannot start PhantomJS in shippable/minV2

### ISSUE THREAD

**Issue by byndcivilization** [Shippable/support#1472]
Hi I'm getting a testing error in my shippable builds on the minv2 host. 
```
   > rgi-assessment-tool@1.0.0 test /home/shippable/workspace/src/github.com/NRGI/rgi-assessment-tool
   > ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS

   INFO [karma]: Karma v0.12.32 server started at http://localhost:9876/
   INFO [launcher]: Starting browser PhantomJS
   ERROR [launcher]: Cannot start PhantomJS
	
   INFO [launcher]: Trying to start PhantomJS again (1/2).
   ERROR [launcher]: Cannot start PhantomJS
	
   INFO [launcher]: Trying to start PhantomJS again (2/2).
   ERROR [launcher]: Cannot start PhantomJS
	
   ERROR [launcher]: PhantomJS failed 2 times (cannot start). Giving up.
   npm ERR! Test failed.  See above for more details.
   npm ERR! not ok code 0
```

**Comment by byndcivilization** [comment]
I've tried to explicitly install phatomjs but that doesn't seem to work.

**Comment by manishas** [comment]
@byndcivilization your latest builds seems to be failing at the push container step. Did you get past the phantomJS issue? Do you still need help?

**Comment by nathanmarks** [comment]
@manishas PhantomJS is also failing to start on my builds now. It was working perfectly before and I haven't changed anything in my related configurations. Have you guys changed something that would cause this?

**Comment by nadavsinai** [comment]
+1

**Comment by manishas** [comment]
We haven't looked at this in detail, but @zpchavez seems to have found a solution -
https://github.com/synapsestudios/frontend-template/pull/119
https://github.com/karma-runner/karma/issues/1144

Can you try the solution mentioned in a comment in the karma repo issue and see if that works?

**Comment by manishas** [comment]
Closing. @byndcivilization please reopen if the solution in the comment above doesnt work.
