### ISSUE TITLE
Feature request - pre-install Android SDK on minion

### ISSUE THREAD

**Issue by rockerhieu** [Shippable/support#1474]
Right now it take ~7mins for our builds to just download and install the Android SDK and necessary components. It would be cool if we can save these ~7mins by having Android SDK with latest `tools,platform-tools,android,build-tools`. I think it will benefit Shippable too as it will save a lot of bandwidth and CPU for these tasks.

**Comment by manishas** [comment]
Have you tried turning on caching?

We will definitely address this scenario soon, but you should try caching until then. Other option is to use a custom image with dedicated hosts.

**Comment by rockerhieu** [comment]
How can I use the caching feature? The document only say that `cache: true` will enable caching. But I think the issue is different. So that I will have to know whether all the dependencies are installed so that I can skip installing them. Is there a best practice to enable cache for an Android Gradle project?

**Comment by rockerhieu** [comment]
Can you please explain the workflow of `cache: true`?

**Comment by manishas** [comment]
@rockerhieu caching is documented at 
http://docs.shippable.com/yml_reference/#caching
http://blog.shippable.com/container-caching

**Comment by rockerhieu** [comment]
I enabled cache with `cache: true` but `before_install` is always executed no matter what. Do you have a workflow chart where I can understand the lifecycle of Shippable build?

**Comment by rockerhieu** [comment]
And regarding the last comment in this article http://blog.shippable.com/faster-builds-with-cached-containers, it seems that caching isn't enabled unless Docker Hub integration is enabled, is it true? Please clarify because I am not using Docker Hub integration at all.

Please add a more details caching documentation where we can understand how to use it properly. It is very confusing now.

**Comment by manishas** [comment]
@rockerhieu you can now use custom docker images for your builds. So if you have an image with Android SDK installed, you can pull it to use for your builds. More info at http://docs.shippable.com/docker_registries/

Closing this issue. If the suggestion above does not help, please comment and i will re-open. Thanks!
