### ISSUE TITLE
New commits are not being pulled in from github.

### ISSUE THREAD

**Issue by babelian** [Shippable/support#1475]
https://app.shippable.com/projects/5413806af82ab7ebd69c942c

pushed two commits, neither are coming up. latest is:

0566cd1b06a623d6a68c1596c7431a339aec07d8

syncing project spins but does not change it.

its a deploy branch, so i'm stuck.

tried rebuilding old builds on other projects and nothing happens.

**Comment by chaserelock** [comment]
+1 currently experiencing the same issue
Went to rebuild an old commit, looked at the script page:
![screen shot 2015-05-21 at 1 57 37 pm](https://cloud.githubusercontent.com/assets/5704766/7758821/6dbaebd0-ffc1-11e4-89e9-d563abee5418.png)

**Comment by jcahoon-stoneware** [comment]
+1 We are experiencing the same issue

**Comment by tobiasc** [comment]
+1

**Comment by bradenstenning** [comment]
Also happening with Bitbucket.

**Comment by harrisonde** [comment]
+1 Github webhook recent deliveries (and redeliver) report 200 in response header.

**Comment by babelian** [comment]
its back

**Comment by manishas** [comment]
thanks for letting us know, it should be fixed now. Thanks!
