### ISSUE TITLE
Failed to run docker in an image

### ISSUE THREAD

**Issue by jerbia** [Shippable/support#1477]
I am using the dedicated host feature, which allows me to use custom Docker images.
I've prepared a custom image with docker installed (yes, docker in a docker). This is based on the dind project (https://github.com/jpetazzo/dind).

When I run my shippable build and try loading docker inside my image, I get following error:
  mount: block device cgroup is write-protected, mounting read-only 
  mount: cannot mount block device cgroup read-only
  Could not make a tmpfs mount. Did you use --privileged?

Note that if I doing the same command manually (meaning, manually running the container with privileged parameter), all works fine.

In the shippable.yml I've specified "privileged: true: under the "build_image" token.

Anyone experienced similar problem?

**Comment by manishas** [comment]
@jerbia we are deprecating the 'privileged: true' functionality very soon. We do not support docker in docker scenarios today.

**Comment by bassamtabbara** [comment]
@manishas are you saying that containers running on dedicated hosts can no longer be privileged? This seems to go against one of the primary features of dedicated hosts -- full admin access.

**Comment by rarkins** [comment]
@jerbia @bassamtabbara wondering if you two gave up on "docker in docker" with shippable or if you found a way? I was expecting it to be supported on hosted minions as part of the latest announcement, but now in this issue it sounds like it wasn't even supported on dedicated either?

**Comment by jerbia** [comment]
I no longer need the "docker in docker" support.

**Comment by manishas** [comment]
Closing this issue. We currently do not support docker in docker scenarios.

**Comment by moylop260** [comment]
Hello @manishas 
Now, with new releases... Is supported docker-in-docker scenarios?
