### ISSUE TITLE
git submodules false has no effect

### ISSUE THREAD

**Issue by sbalko** [Shippable/support#1478]
Hi,

I have a project hosted on GitHub with several submodules. For the shippable build, I do not want these submodules to be fetched, so I included a

```
git:
   submodules: false
```

clause into ```shippable.yml```. However, that does not seem to have any effect. I continue to see the following build steps:

```
 ssh-agent bash -c 'ssh-add /root/.ssh/project_rsa; git clone git@github.com:sbalko/libav.js.git /root/workspace/src/github.com/sbalko/libav.js'
 git config --get user.name || git config user.name 'Shippable Build'
 git config --get user.email || git config user.email 'build@shippable.com'
 rm -rf /root/workspace/src/github.com/sbalko/libav.js/shippable
 mkdir -p /root/workspace/src/github.com/sbalko/libav.js/shippable/testresults
 mkdir -p /root/workspace/src/github.com/sbalko/libav.js/shippable/codecoverage
 mkdir -p /root/workspace/src/github.com/sbalko/libav.js/shippable/buildoutput
 git checkout -f dev --
 git reset --hard f78c31dbe932080e7811bcb780e4dc73287bd87a
 git submodule init
 git submodule sync
```

Why are the latter two steps happening? Isn't that what is supposed to be suppressed by the "submodules: false" clause?

Any help would be greatly appreciated!
Soeren

**Comment by manishas** [comment]
Closing this issue since this should be fixed with the latest release.
