### ISSUE TITLE
Build fail when resulttest.xml no tests

### ISSUE THREAD

**Issue by Andrewwojownik** [Shippable/support#1479]
I start using shippable for new project. Now i no tests and if I build with no test and file with result have only:
<?xml version="1.0" encoding="UTF-8"?>
<testsuites/>

build fail with error: Error parsing test reports.
If I add one test, all with build success and test results shows ok.

I using codeception with php 5.6 and laravel framework.

Link for build https://app.shippable.com/builds/5561b036d88a130e00212d8b

**Comment by manishas** [comment]
@Andrewwojownik I am closing this issue since your latest builds seem to have passed. Please re-open if you run into this again.
