### ISSUE TITLE
Install fails with 403

### ISSUE THREAD

**Issue by Nalum** [Shippable/support#1480]
The install phase of the build is failing with:
```
package bitbucket.org/[group]/[repo]/[sub-module]: https://api.bitbucket.org/1.0/repositories/[group]/[repo]: 403 FORBIDDEN
```

This is a private repo do I need to do something to allow access?

Here is my `shippable.yml` file:

```
language: go

go:
  - 1.4

env:
  - CI_REPORT=shippable/testresults/junit.xml

before_install:
  - export GOPATH=$SHIPPABLE_GOPATH
  - source $HOME/.gvm/scripts/gvm
  - gvm install go$SHIPPABLE_GO_VERSION
  - gvm use go$SHIPPABLE_GO_VERSION
  - go get github.com/t-yuki/gocover-cobertura
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

# Make folders for the reports
before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - go test -coverprofile=coverage.txt -covermode count ./
  - $GOPATH/bin/gocover-cobertura < coverage.txt > shippable/codecoverage/coverage.xml
```

**Comment by rvdwijngaard** [comment]
Hi, 

is there any update on this? My go build is failing because of this. Is there any workaround for this?

**Comment by rvdwijngaard** [comment]
Hi, any news? I temporarily had to make my repo public just because of the build failures. that is not acceptable. Please advice.

**Comment by lekhab** [comment]
@Nalum, @rvdwijngaard: Can you please point me to a failed build?

**Comment by Nalum** [comment]
@lekhab: Here is one of mine: https://app.shippable.com/builds/55809d2ce352db0d0056730f

I have removed the submodule yesterday, do you have a recommended way to `go get` private repos?

**Comment by rvdwijngaard** [comment]
hi, this is my build which fails: https://app.shippable.com/builds/559e1f204dd79a0b00449452

**Comment by Nalum** [comment]
Is there any update on this? I'm also getting this for packages that are just sub-packages in the same repo.

**Comment by Nalum** [comment]
@lekhab any update on this?

**Comment by Nalum** [comment]
Looks like the docs have been updated.

Setting the GOPATH before doing any `go get/install` to `$HOME/workspace` did the trick for me.

**Comment by rvdwijngaard** [comment]
@lekhab is there any update on this?

**Comment by lekhab** [comment]
@rvdwijngaard: sorry, I thought this was resolved with the last update. Were you able to try the workaround suggested by Nalum above?

**Comment by rvdwijngaard** [comment]
Hi @lekhab the workaround of @Nalum does not solve my issue. I am still getting a 403. Please advice since this is really becoming an issue. 

The build which is failing is https://app.shippable.com/builds/56125233c941e90c00ef92c1

**Comment by rvdwijngaard** [comment]
hi, 

I gave it another try and finally resolved this. It seems 
````
gvm use go$SHIPPABLE_GO_VERSION
````
is changing the GOPATH. I changed my configuration to something like this: 
````
before_install:
  - source $HOME/.gvm/scripts/gvm;
  - gvm use go$SHIPPABLE_GO_VERSION

  - export GOPATH=/root/workspace 
  - go get github.com/t-yuki/gocover-cobertura
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify/assert
  - go get -d -v ./...
````

This solves the issue.

**Comment by manishas** [comment]
Closing this since it's an old issue and we've revamped the build system recently.
