### ISSUE TITLE
PhantomJS not starting anymore. I haven't changed my configuration.

### ISSUE THREAD

**Issue by nathanmarks** [Shippable/support#1482]
Hey guys,

I haven't touched any configuration related to PhantomJS, but it's suddenly not starting in my builds anymore.

```
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (1/2).
WARN [launcher]: PhantomJS have not captured in 60000 ms, killing.
INFO [launcher]: Trying to start PhantomJS again (2/2).
```

Example failed build: https://app.shippable.com/builds/55633688d88a130e00213bbb
Example success build: https://app.shippable.com/builds/555617d5d81dea0d0039ebed

**Comment by manishas** [comment]
@nathanmarks i cannot access either of the builds you've linked to here. I did look at the 2 builds in your reporting-tool repo and those show the error you've pasted above. Googling the error gives me many possible reasons why this might happen -
https://www.google.com/search?q=WARN+%5Blauncher%5D%3A+PhantomJS+have+not+captured+in+60000+ms%2C+killing.&oq=WARN+%5Blauncher%5D%3A+PhantomJS+have+not+captured+in+60000+ms%2C+killing.&aqs=chrome..69i57.425j0j4&sourceid=chrome&es_sm=91&ie=UTF-8#q=ERROR+%5Blauncher%5D:+PhantomJS+failed+2+times+(timeout).+Giving+up.

We will need to take a deeper look at what's going on here.

**Comment by nathanmarks** [comment]
@manishas It started working again... all I did was re-run the same build that had already failed twice. What's going on here? https://app.shippable.com/builds/556707287472310c00b364e1

**Comment by manishas** [comment]
our build system has been revamped for the new release. if this still happens, happy to take a look.
