### ISSUE TITLE
Cannot merge bitbucket account with github account

### ISSUE THREAD

**Issue by Neku** [Shippable/support#1483]
When I try to connect my github I get 
"""
 Error
Unable to link identity since it already belongs to another account. Delete one of the accounts in order to link them."""
Tried to delete the profile a couple of times and still doesn't work.

**Comment by manishas** [comment]
@Neku there is a bug in delete account that we discovered a couple of days ago. It has been fixed, so you should be able to delete one of your accounts, login with the other, and then connect the two.

**Comment by manishas** [comment]
Closing.
