### ISSUE TITLE
Is there any official support for MySQL 5.6?

### ISSUE THREAD

**Issue by QuantumGhost** [Shippable/support#1484]
Our project is using MySQL 5.6 now. I hope that there is a way to specify the version of MySQL used in the build process.

**Comment by manishas** [comment]
@QuantumGhost You can use one of our language specific images and install MySQL in your yml -
http://docs.shippable.com/languages/images/

**Comment by QuantumGhost** [comment]
Ok, thank.
It would be better if it is possible to specify mysql version like this:

```yaml
mysql:
  version:
     5.6.19
```
