### ISSUE TITLE
Managing invites on new projects

### ISSUE THREAD

**Issue by sdlarsen** [Shippable/support#1485]
When creating a new project, invites are sent to everyone who has/had access to the repositories and has been signed in to Shippable (I guess). How can we manage this when people are leaving a team (or a company)?

**Comment by manishas** [comment]
We send invites to everyone who has access to the repository on GitHub, irrespective of whether they have signed into Shippable yet. The idea is to let them know that this repo has been configured on Shippable and they can sign in and view build status if they want.

We sync permissions with GitHub so if someone leaves the team and loses access to the repo, they will not see any invites.

**Comment by sdlarsen** [comment]
Hi. Thank you for your answer. We use BitBucket and have removed a person from the team, but he's still getting invites (to an inactive email account). I'm not sure why this is marked as resolved.

**Comment by lekhab** [comment]
@sdlarsen: is this still an issue? If it is, can you share details about the email that is still getting invites?

**Comment by manishas** [comment]
closing since this is an old issue and this should not happen with our revamped build platform.
