### ISSUE TITLE
AWS Opsworks integration

### ISSUE THREAD

**Issue by thiagonache** [Shippable/support#1486]
Hi there,

I'm integrating shippable with opsworks, but I could not find a way to create deployment after container push. Is that possible?
I deploy the container on opsworks, so if I use after_success I'm not sure if deployment will run before or after the push to dockerhub.

**Comment by thiagonache** [comment]
Something like after_push it would be great

**Comment by thiagonache** [comment]
Something like after_push it would be great

**Comment by manishas** [comment]
@thiagonache we're working on improving our deployment options, and will keep this in mind as we design.

**Comment by thiagonache** [comment]
Cool. Do you have ETA?

**Comment by manishas** [comment]
http://docs.shippable.com/ht_opsworks/
