### ISSUE TITLE
Feature Request: Coverage

### ISSUE THREAD

**Issue by Nalum** [Shippable/support#1488]
On the coverage view can you show the extra data that is provided?

Example: Python coverage goes into detail about which lines are covered, partially and not covered.

It would be nice to see this in the coverage tab and not have to either create the HTML output from coverage or view the console output to get that information.

**Comment by smvv** [comment]
I'm very interested in this feature as well!

**Comment by assisrafael** [comment]
I'm also very interested in this feature.

**Comment by manishas** [comment]
consolidating all coverage related requests in #174
