### ISSUE TITLE
API errors

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1489]
Trying to get  current running builds while testing a new client for shippable API. 
I get an error response, to reproduce:

```
curl -H "Authorization: apiToken $apiToken"  https://api.shippable.com/projects/54e2287a5ab6cc13528c39d2/runningBuilds
```

response:
headers:
```
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept,Content-Type,Authorization,Cookie
Access-Control-Allow-Methods: GET,PUT,POST,DELETE
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Date: Wed, 27 May 2015 16:00:57 GMT
ETag: "1123644452"
X-Powered-By: Express
Content-Length: 155
Connection: keep-alive
```
respBody:
```json
{
  "id": 9999,
  "methodName": "shipError",
  "link": {
    "name": "MongoError",
    "$err": "Can't canonicalize query: BadValue unknown top level operator: $nin",
    "code": 17287
  }
}
```

**Comment by pmoust** [comment]
Issue persists.
Would love some update on the docs as well to explain the `status` part of the response of builds.
Also, the `steps` produced from `build` calls seem to not contain any info.

**Comment by pmoust** [comment]
`workflow/disableBuild` does not return `application/json`, instead it replies with a text on success;
```
Deleted project 556734d0edd7f2c052ff35b4
```
This breaks a generic client expecting json, I find it ugly relying only on status code.

**Comment by pmoust** [comment]
```
curl -H "Authorization: apiToken $apiToken" \
     -H "Content-Type: application/json" \
     -d "{\"username\": \"pmoust\", \"password\": \"dummy\", email: \"yolo@yolo.gr\"}" 

https://api.shippable.com/workflow/validateDockerHubCredentials -sil
```

returns
```
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain; charset=utf-8
Date: Tue, 02 Jun 2015 07:48:23 GMT
X-Powered-By: Express
Content-Length: 21
Connection: keep-alive

Internal Server Error%
```

**Comment by pmoust** [comment]
Hi is there an ETA on API revamp on your end?

**Comment by lekhab** [comment]
@pmoust: we never got back to you on this, apologies! 

The API issues you faced on the runningBuilds API was fixed.  Please let me know if you are still facing issues there.

We are updating the APIs continually as we improve the backend. I don't have an ETA for a complete revamp yet - am following up on the other API issues and docs you mention here.

**Comment by manishas** [comment]
Closing this since we fixed the API in question...
