### ISSUE TITLE
Project won't build

### ISSUE THREAD

**Issue by bdmesh** [Shippable/support#1491]
Hi, i have a project 'concur\concur-test-utils' that I've been successfully building/deploying in the past (last build 5/11/15).  However today, I just checked into my dev branch on github and no build triggered.  So I went into shippable.com... there appeared to be no notification for it.  I tried to manually start the build, but after the dialog pops up asking me which branch, it won't actually action when I click the 'run' button.  So I'm stuck not being able to get it to build.  Additionally, if I click on the individual project, it tries to take me to the specific project view, but just sits there with a spinner and won't load.  Did somehow I foobar my project?  What's the path to recover?

Thanks!
-Brian

**Comment by manishas** [comment]
@bdmesh can I try to run a manual build on your behalf?

**Comment by pkaminski** [comment]
Ditto here on `reviewable/reviewable-client`.  Automatic builds don't trigger, and when trying a manual build nothing happens when hitting the "Run" button.  You can try building the master branch to debug if you want.  Everything was working fine yesterday.

**Comment by manishas** [comment]
@bdmesh @pkaminski we have a partial disruption affecting some builds. ETA for a fix is 30 mins.

https://twitter.com/BeShippable

**Comment by bdmesh** [comment]
Sure, feel free to try to build!
Thx!



On May 27, 2015, at 5:16 PM, Manisha <notifications@github.com<mailto:notifications@github.com>> wrote:


@bdmesh<https://github.com/bdmesh> can I try to run a manual build on your behalf?

—
Reply to this email directly or view it on GitHub<https://github.com/Shippable/support/issues/1491#issuecomment-106118936>.

________________________________

This e-mail message is authorized for use by the intended recipient only and may contain information that is privileged and confidential. If you received this message in error, please call us immediately at (425) 590-5000 and ask to speak to the message sender. Please do not copy, disseminate, or retain this message unless you are the intended recipient. In addition, to ensure the security of your data, please do not send any unencrypted credit card or personally identifiable information to this email address. Thank you.

**Comment by bdmesh** [comment]
it builds great now! Thx!
