### ISSUE TITLE
Unlink github from my account.

### ISSUE THREAD

**Issue by PJnes** [Shippable/support#1492]
I have an account, created through my bitbucket account (http://bitbucket.org/pj). I added my github account, but it's also added all of the organisation repos I have access to, making the repository list a pain to navigate when adding new projects. I've disabled the the shippable access in github, but it hasn't removed the accounts in shippable, and I can't see any way to remove them.

Is there an option I'm missing, or is there something else I need to do to remove by github account?

**Comment by manishas** [comment]
@PJnes can you click on 'sync' on your dashboard after removing access? If you still see the accounts, I will see if we can delete them on the backend.

**Comment by PJnes** [comment]
@manishas It's kind of half removed now.

I'm still seeing github organisations in the org list, but not seeing github repos in my repo list any more. Github public and private repos are showing as 'on' but I get a 'Error connecting to GitHub' notification each time I click 'sync'.

Is there anything you can do to fully remove it?

**Comment by blakeblackshear** [comment]
Somehow I have 2 accounts and I need to move the link to my github to the same account where I have bitbucket linked. How can I do this?

**Comment by lekhab** [comment]
@blakeblackshear: I can only see one account with your id.  Can you please provide the details of the 2 accounts and which one you need removed?

**Comment by blakeblackshear** [comment]
The account id linked to github is: 55819d9d4d96360c000eff55
The account id linked to bitbucket is: 54f9e39a5ab6cc13529428d6

Please remove account id 55819d9d4d96360c000eff55.

**Comment by PJnes** [comment]
@blakeblackshear Any chance you could move this to your own issue? You've kind of jumped in on mine.

@lekhab I'm still waiting for a reply to my latest response (over 2 months fwiw).

**Comment by lekhab** [comment]
@PJnes - apologies. following up on your issue internally.

@blakeblackshear - created a separate support issue to track your case - #1761

**Comment by lekhab** [comment]
@PJnes: Can you please take a look now and let me know if the account is cleaned up on your end? We cleaned up the backend for your Github account on Shippable.

**Comment by PJnes** [comment]
@lekhab All sorted now, thanks!

**Comment by lekhab** [comment]
great - closing this. @blakeblackshear - will update #1761 as soon as your dupe account is deleted.
