### ISSUE TITLE
How to deploy only once, when using build matrix

### ISSUE THREAD

**Issue by frenkel** [Shippable/support#1493]
I would like to deploy only once, but my build matrix results in 4 calls to after_success if all 4 of the matrix finish successfully. I just need to deploy once when the ruby 2.1.6 build with postgresql finished successfully, or only once when all builds finished successfully. How can I achieve one of these?

**Comment by rageshkrishna** [comment]
Hi @frenkel. Can you give me the ID of a recent build I can look at? I'm sure we can figure something out by looking at the environment variables. Thanks!

**Comment by frenkel** [comment]
For example 556811d67472310c00b37be2

**Comment by mbrodala** [comment]
This is the same issue as Travis CI has and so far I got around with tools like [deployasaur.us](http://www.deployasaur.us/). It would be awesome if Shippable could support this natively.

**Comment by frenkel** [comment]
@rageshkrishna Did you find a solution?

**Comment by rageshkrishna** [comment]
@frenkel Unfortunately, we don't have a trigger you can use that is only run when all the matrix builds complete. For your specific scenario, however, I think you might be able to get away with an `after_success` that validates the runtime and DB environment variables like this:

````
after_success:
 - if [ "$SHIPPABLE_RUBY" == "2.1.5" ] && [ "$DB" == "postgres" ]; then ./deploy.sh; fi;
````

I hope this helps.

**Comment by frenkel** [comment]
Of course, it is just a normal shell command that evaluates! Hadn't thought about it. Thanks for the hint.

**Comment by mbrodala** [comment]
@rageshkrishna Could you elaborate on this a bit more? How can I derive that all builds have succeeded within a single one only with environment variables?

**Comment by frenkel** [comment]
@mbrodala That is not what we are trying to achieve. We want to prevent 6 builds generating 6 deploys to the same server. If the 2.2.2 postgresql build succeeds, we want it to be deployed, because that is what the server uses as well.

**Comment by mbrodala** [comment]
@frenkel Ah, so your usecase is different, gotcha. ;-)

**Comment by nigelwinterburn** [comment]
This doesn't really work for me. What if every build fails except 2.1.5? This solution seems to ignore every other build.

**Comment by mbrodala** [comment]
Maybe [travis-after-all](https://github.com/alrra/travis-after-all) is an option for Shippable too.
