### ISSUE TITLE
use iojs

### ISSUE THREAD

**Issue by assisrafael** [Shippable/support#1494]
How do I configure shippable.yml to use iojs instead of nodejs?

**Comment by MarkHerhold** [comment]
You can manually download and install iojs on the container or use a node version manager such as n or nvm.

**Comment by lekhab** [comment]
@assisrafael: please let me know if this is still an open question. Closing the issue for now.

**Comment by assisrafael** [comment]
Yes, I still don't know how to do that. What I need to write into shippable.yml ? The following will work (iojs@2.3.1)?

```
node_js:
  - "2.3.1"
```

**Comment by MarkHerhold** [comment]
@assisrafael try
```
node_js:
    - 0.11.14

before_script:
    - sudo npm i -g n
    - sudo n io 3.0.0

script:
    - n io use 3.0.0 myNodeScript.js
```
