### ISSUE TITLE
Build timing out even after tests pass

### ISSUE THREAD

**Issue by tomek-rej** [Shippable/support#1495]
Hello,
My account name is HealthshareAU.
For the past week all my builds on Shippable have been timing out. Looking at the console output the tests have been passing. The last few lines of the console output are:
```
-----------------------------------------------------------------------------------------------------------
TOTAL                                                                         24215  14305    41%   
----------------------------------------------------------------------
Ran 878 tests in 750.334s
OK
Command timed out
Command thread timed out
```
and in the end the status of the Shippable build is a timeout.

**Comment by lcannon** [comment]
Any updates on this? This is slowing down our development.

**Comment by lcannon** [comment]
It's now been nearly one and a half months since we opened this issue that is still affecting our development, and we don't even have a single reply or update on the status of this issue?

**Comment by manishas** [comment]
@lcannon Sorry it has taken this long! We'll look at it in a few hours and get back to you.

**Comment by manishas** [comment]
@lcannon your builds are no longer timing out, but looks like 3 of your tests are failing.

**Comment by lcannon** [comment]
Thanks!

**Comment by manishas** [comment]
Closing this issue since the build is now green. Sorry about the delay on this!
