### ISSUE TITLE
How to cut down the lead time of shippable build? 

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1496]
Hi, 

We are using dedicated hosts to run our builds. Currently the machine is an t2.medium EC2 instance. This machine does not seem to be very busy. A regular build of a nodejs project takes approx. 9 minutes, including a docker push. The actual build time of the nodejs code is 20 seconds. 

How can we reduce the lead time of the builds? Do you have any recommendations for running dedicated hosts on AWS?

**Comment by manishas** [comment]
@rvdwijngaard you can speed up builds by turning on cache. Please turn on cache in your your project settings tab.

**Comment by rvdwijngaard** [comment]
Thanks for your answer; I don't think this is the solution. The cache option is disabled because I am using the docker-build option for my repo. It seems that the docker build / push options are really taking a lot of time; Besides the lead time of these two actions there is a big amount of (overhead) time which is not traceable.
