### ISSUE TITLE
use custom ec2

### ISSUE THREAD

**Issue by rhmontgomery** [Shippable/support#1498]
I am new to this so thanks in advance for the help.  I have MATLAB installed on an ec2 instance and was hoping to use that instance as my build host for my tests for shippable.  Is that possible or do have to create custom docker file?  I ask this because MATLAB requires licensing and mac address which I don't think I can accomplish with a docker file.  Thanks!

**Comment by manishas** [comment]
You will need to create a custom docker file to use dedicated hosts. We do not support your scenario today, but we'll keep it in mind as we evolve the product. Thanks!
