### ISSUE TITLE
Encrypted env vars not available

### ISSUE THREAD

**Issue by sengenbe** [Shippable/support#1499]
I have a Rails application in which all builds are failing due to the env vars not being available to a gem called Figaro, which throws errors when required variables are not present.  I followed instructions and verified I used the correct organization and my yml file looks fine.  Are the variables not made available at this step?

**Comment by manishas** [comment]
can you point me to a failed build?

**Comment by sengenbe** [comment]
Not hard to find :) 53.1 - a5dc48b

Secure encryption does not work but placing the naked pairs in
shippable.yml made it pass that step (to the next step at least).

**Comment by lekhab** [comment]
@sengenbe: Apologies for the delay in getting back to you.

If this is still an issue, can you please share your yml (minus the unencrypted vars, of course :-) )? Also, can you confirm you generated the secure variables using the encrypt vars functionality in the UI?

**Comment by sengenbe** [comment]
Hi, I did use the UI for the encryption following the examples in the
docs.  I will upload shortly.a

**Comment by manishas** [comment]
This is an old issue and we have upgraded our build platform since then. Please reopen if this is still a problem.
