### ISSUE TITLE
Anything change today?? Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by mbrevoort** [Shippable/support#1500]
We've been building docker containers on our custom build nodes without issue for weeks and then today all of our builds are failing because of this issue:

```
 if [ "$BRANCH" = "master" ]; then sudo docker build -t quay.io/robotsandpencils/api:$COMMIT_SHORT .; fi
Sending build context to Docker daemon 
time="2015-05-30T03:40:34Z" level=fatal msg="Cannot connect to the Docker daemon. Is 'docker -d' running on this host?"
```

Before I dig too deep, I would love to know if you know of a change that happened today that may be the cause of these issues.

**Comment by alexanderlamb** [comment]
We have also been having trouble suddenly with our builds that require docker running inside docker.  Things were fine yesterday.

**Comment by manishas** [comment]
@mbrevoort @alexanderlamb We officially never supported docker-in-docker and some changes were introduced today that affected these scenarios. You will receive an email about this in a few hours.

Dedicated hosts is a beta feature and is undergoing major changes. More communication soon on how we can help you get your builds up and running again.

**Comment by mbrevoort** [comment]
Its really difficult  as a user to know and understand the fine print of what's officially supported and what's not.  We go through this process of trial and error and find something that works and go with that hoping the ground won't shift beneath us. 

This is the second time in a month that a similar unsupported change has broken all of our builds and deployment pipeline.  I really want shippable to work for us but it's beginning to become more of a liability. 

 I completely understand your stance, and you're more right than I am, but as a user it is frustrating.

**Comment by alexanderlamb** [comment]
@manishas I appreciate the response.

Unfortunately we have to begin moving our CI / CD workflow away from Shippable today as a result of this change.  When can we expect this communication to see if these changes will in fact allow us to continue using your service?

**Comment by manishas** [comment]
@alexanderlamb just sent you an email. Let me know if we can jump on a call.

**Comment by rarkins** [comment]
@alexanderlamb @mbrevoort wondering if you gave up on this, or found a way to still make it work? "Docker in docker" is supported by other CI/CD services so really surprised that a "built on docker" company like shippable isn't supporting it.

**Comment by manishas** [comment]
Docker-in-Docker isn't supported on Shippable today. Closing this issue.
Thanks!
