### ISSUE TITLE
Builds running docker inside docker suddenly failing

### ISSUE THREAD

**Issue by alexanderlamb** [Shippable/support#1501]
I'd like to confirm that the shippable.yml configuration seen below is still valid
![image](https://cloud.githubusercontent.com/assets/5480111/7895495/32d28902-0646-11e5-95ca-8ce9f971a46e.png)

Yesterday our builds were completing as normal, but this afternoon they started failing with errors indicating that the above settings are no longer taking effect.

Example of failed build:
https://app.shippable.com/builds/55692afde9aab00d00d502eb

**Comment by manishas** [comment]
closing this issue. docker in docker scenarios are not supported on Shippable.
