### ISSUE TITLE
The build you're looking for wasn't found

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1502]
We have a public github repo and we expect the shippable builds to also be public. However, as reported by a contributor:

https://github.com/ensime/ensime-emacs/pull/133#issuecomment-107002113

non-admins are seeing "The build you're looking for wasn't found." e.g. for this build

https://app.shippable.com/builds/556888f47472310c00b386b8

This is not good, as it means that our community cannot see why their tests are failing.

**Comment by manishas** [comment]
Shippable build results are now public and do not require signing into Shippable. Thanks!
