### ISSUE TITLE
Permission denied when running COPY FROM queries against PostgreSQL

### ISSUE THREAD

**Issue by netj** [Shippable/support#1503]
It seems postgres has no permission to access files under /home/shippable/workspace/src/github.com/.  Our tests include `COPY FROM` queries and they are not being able to pass.  See https://app.shippable.com/builds/5569a020e9aab00d00d504df.

**Comment by manishas** [comment]
Sorry this fell off the radar!

We have completely redone our build system recently, so this should no happen any more.
