### ISSUE TITLE
How do I bind a docker build to a database addon?

### ISSUE THREAD

**Issue by tal-moshayov** [Shippable/support#1504]
I'm using a custom docker image for my build, which requires a db (postgres) to run its tests. So I added:
`addons:  
  postgresql : "9.3"
` to shippable.yml.
Now, assuming shippable kickstarts the database addon in the background, **what is the db host name and port I should bind to?**  
It appears that on a shippable predefined image the addon is automatically bound to localhost, but it doesn't seem to be this way with a custom docker image.

**Comment by manishas** [comment]
@tal-moshayov the yml sections for 'services' 'addons' work only with our default image since we know what's installed on it.

You will have to start the db explicitly through your shippable.yml.

**Comment by filemon** [comment]
? so you guys don't provide addons as docker containers to be linked with my own docker container for the build?  I can't believe that, please prove I'm wrong.

**Comment by manishas** [comment]
@filemon you can use Formations to if you want to define and run a multi-container environment. Would love to show you how easy it is to set up and use... let me know if you have 15-30 mins next week and i can set up a hangout.

**Comment by filemon** [comment]
Thanks @manishas. I played with Formations for a while, but didn't find the way how to attach a build to given environment. I would assume some sort of docker-compose style configuration (even in UI), that would allow me to link the container being built with the rest. Happy to talk to you next weekend - booked the time for Tuesday. :)

**Comment by manishas** [comment]
This should be addressed with our latest release. We now allow docker commands in the yml, so you should be able to spin up containers using docker compose in your yml. More on this here -
[Configuring your build](http://docs.shippable.com/ci_configure/)
[Docker support](http://docs.shippable.com/ci_docker/)
