### ISSUE TITLE
Cannot connect to port on dedicated host & custom image

### ISSUE THREAD

**Issue by RobertHerhold** [Shippable/support#1505]
I bought dedicated host support and created and pushed a public docker image based off of this repo: https://github.com/shippableImages/mongoBase.

I am able to run the container and connect to it just fine on my local machine (port 27017). Is there something special I need to do either on my dedicated host or in my custom image to resolve this issue?

Running `mongo` (Mongo shell) returns 
```
connecting to: test
couldn't connect to server 127.0.0.1:27017...
exception: connect failed
```

I have tried this with a separate database, different port, and different docker images but have never been able to connect.

With this being an issue, dedicated hosts are absolutely useless. Please advise.

**Comment by manishas** [comment]
@RobertHerhold can you send us your shippable.yml? Also a link to a failed build will help.

**Comment by RobertHerhold** [comment]
@manishas I made a separate repo just to test this out.

build #4 (Failed): https://app.shippable.com/builds/556bb2a220addd0f00f5e8c0

build #3 (Success): https://app.shippable.com/builds/556ba805475bca0b00081256

Failing build shippable.yml file: Ignore the node stuff.
```
build_image: robertherhold/shippable_mongo:latest

language: node_js

node_js:
    - 0.11.14

services:
    - mongodb

script:
    - mongo < mongostuff
```

mongostuff file:
```
db.version();
show dbs;
```

**Comment by RobertHerhold** [comment]
Any update?

**Comment by manishas** [comment]
We have completely upgraded dedicated hosts and this should not happen after the upgrade. closing.
