### ISSUE TITLE
docker image user disappeared

### ISSUE THREAD

**Issue by tal-moshayov** [Shippable/support#1506]
I'm building using a custom docker image that has a postgres user pre-created in it. 
When I try to use that image in shippable, that user does not exist (invalid user: 'postgres').
What's going on here? Is shippable changing the target docker? 
Any hint for debug?

**Comment by wigcheng** [comment]
I have the same issue

**Comment by manishas** [comment]
This has been completely redone in our newly released build system and this should not happen any more. Sorry on the long long delay on this.

Closing.
