### ISSUE TITLE
Support html coverage reports (phpunit)

### ISSUE THREAD

**Issue by eventbase-web** [Shippable/support#1507]
Are there any plans to support html coverage reports?

We've been using a local install of Jenkins for our PHP CI builds, but *much* prefer Shippable for a variety of reasons. Right now the XML coverage reports are the only deal breaker between me and moving us wholesale to Shippable.

**Comment by EHLOVader** [comment]
Second this.. I might even suggest that supporting arbitrary HTML reports might help most of the report problems in here. 
In particular #174 which has requests for lots of formats, and if HTML were allowed then it could show anything.

**Comment by mmindenhall** [comment]
+1.  The `go cover` tool is also capable of producing an html report.  I've tried converting the coverage reports to cobertura xml format using two available tools, but in both cases I still get 0% coverage reported for my packages by Shippable.

@eventbase-web, any chance you can change the issue title to "Support html coverage reports" (or similar)?

**Comment by manishas** [comment]
Consolidating all coverage related requests in #174.
