### ISSUE TITLE
build keeps hanging on "pull"

### ISSUE THREAD

**Issue by fommil** [Shippable/support#1508]
I've restarted this build a few times, but it keeps hanging during the docker image pull, can you please have a look?

https://app.shippable.com/builds/556c33ed20addd0f00f614b3

**Comment by fommil** [comment]
and more https://app.shippable.com/builds/556d48617f74c80d007c7720

**Comment by fommil** [comment]
now we're getting timeouts even though the build finished successfully **sigh**

https://app.shippable.com/builds/557087657f74c80d007ee0dc

**Comment by fommil** [comment]
@manishas we've not had any builds working for several weeks now. I'm moving over to drone today. Good luck with your venture.

**Comment by manishas** [comment]
@fommil sorry to hear you're still having a problem with builds. did you try running your builds on the multi-tenant system without dedicated hosts?

**Comment by fommil** [comment]
do I just delete my dedicated nodes? It's worth a try, but I can't see that working. The reason why we moved to shippable from Travis is so that we could use beefy machines to run our intensive jobs. Drone allows us to use our own machines **and** it uses the standard docker APIs... no magic scripts and dockers within dockers. Technically it is a superior solution.

**Comment by manishas** [comment]
Yes if you delete your dedicated nodes builds will automatically run on the multi tenant platform. Let me know if it works. 

We totally understand if another solution fits your needs better :(

**Comment by manishas** [comment]
Also, we've had several customers that complained about Travis not being able to handle their workloads but they've been fine on our platform, especially now that we're guaranteeing 2 cores 4 gb.

**Comment by avinci** [comment]
we have changed our processing quite a bit. Please let us know if you still seeing issues. closing this to make sure we are addressing the valid ones.
