### ISSUE TITLE
Signup now leads to app?

### ISSUE THREAD

**Issue by davidthewatson** [Shippable/support#1509]
I wanted to upgrade my account. I start here:

http://www.shippable.com/pricing.html

clicked sign up now/github auth and wound up here:

https://app.shippable.com/

but still no indication of how to sign up for the $12/year plan. Help!

**Comment by manishas** [comment]
Click on your organization on the right side of your dashboard, then on the org page, click on Plans and Billing on the top right. 

Enter your credit card info and then choose the plan you want. 

Only owners of orgs can upgrade plans.

**Comment by davidthewatson** [comment]
Thanks! UX could be fixed by just making the login's next link proceed to the plans and billing page, since that would be a reasonable expectation given the link.
