### ISSUE TITLE
Frequent issues creating a virtualenv

### ISSUE THREAD

**Issue by prabhuramachandran** [Shippable/support#1510]
Been using shippable for a while now and of late I have found that several of my builds routinely fail with a strange virtualenv error.  Here is an example:

https://app.shippable.com/builds/556cbd0e20addd0f00f67a18

If you notice on this: https://app.shippable.com/projects/540e849c3479c5ea8f9f030e

There are several builds that have failed with a similar error.  My shippable.yml has not changed in any significant way in many months.

**Comment by prabhuramachandran** [comment]
As an update, I reran the build today and it all works fine.  This has been happening on and off though and is a bit frustrating as I am not sure if there is anything I can do to fix it.

**Comment by prabhuramachandran** [comment]
Today the builds are failing again with the same errors as before.  It would be great if this worked reliably.

**Comment by prabhuramachandran** [comment]
Any updates on this?

**Comment by manishas** [comment]
this has been completely redone in the new build system. closing.
