### ISSUE TITLE
Single Build Minion on Paid Account

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1511]
Hi,

I have a paid account on shippable. I received 5 build minion as part of my plan. I recently added a bitbucket team repository under my account and I can only see single minion being available on that repository. I can still see 5 build minions under my github repositories as earlier.

I expected that all 5 minions to be used across all projects under my paid shippable account. Do I need to pay separately for bitbucket repositories or is there some configuration setting which I need to set so that all 5 minions are shared across projects.

Thanks,
Naveen

**Comment by manishas** [comment]
@naveensky yes, subscription is per organization. So you'll need to pay separately for GitHub and Bitbucket orgs.
