### ISSUE TITLE
cannot delete builds.

### ISSUE THREAD

**Issue by richhl** [Shippable/support#1512]
to reproduce:

-click trash bin icon attached to any build.
-select ok as option for confirm deletion dialog.
-i got screen attached.

![cannot_delete_buils](https://cloud.githubusercontent.com/assets/1074446/7932227/f6002d4e-0916-11e5-934d-cd71b4974ecb.png)

**Comment by manishas** [comment]
@richhl sorry for the late response. you can only delete builds if you're an owner for the project on github or bitbucket.
