### ISSUE TITLE
got unexpected error for a mysql sentence when executing before script

### ISSUE THREAD

**Issue by richhl** [Shippable/support#1513]
don't know what happens, mysql sentence is well formed! thx in advance. 

 before_script ✗
 composer install -n
 mysql -e "CREATE USER 'ticketuser'@'localhost' IDENTIFIED BY 'evarV3';"
 mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'ticketuser'@'localhost';"
/home/shippable/862d9511-f5db-407d-a31a-fd6ccd4a2cac.sh: eval: line 85: unexpected EOF while looking for matching `"''

**Comment by manishas** [comment]
We have upgraded our build system since this issue was reported, so closing this.
