### ISSUE TITLE
Where is the Dockerfile for minv2?

### ISSUE THREAD

**Issue by jchamberlain** [Shippable/support#1516]
I need to add a couple things to minv2 for my tests, but I'd also like to remove some things I don't need so that I can use it in a Docker Hub automated build (it's too big right now). If I could see the Dockerfile, I could figure out how to do exactly what I need for my testing with minimal changes, but I can't seem to find it.

**Comment by manishas** [comment]
We haven't published the dockerfile for minv2. Our goal is to deprecate it as soon as we introduce an easier way to create custom Dockerfiles.
