### ISSUE TITLE
Ssh public key ~/.ssh/id_rsa.pub not found

### ISSUE THREAD

**Issue by yellowcap** [Shippable/support#1518]
Hi

I am trying to use the ssh public key on my shippable build, but the key is not there, I get the following error:

    Key '/home/shippable/.ssh/id_rsa.pub' seems to not be a RSA public key or not found!

According to the following blog post it should be available. How can I access the public key on sihppable?

http://rageshkrishna.com/blog/demystifying-shippable-s-deployment-keys

**Comment by manishas** [comment]
@yellowcap i am really sorry this wasn't answered sooner. Are you still running into this issue?

**Comment by lekhab** [comment]
please let us know if you are still running into this and will re-open.

**Comment by samius** [comment]
Hi, 
I am having the same problem right now.
