### ISSUE TITLE
When using custom docker image git checkout fails (easy fix)

### ISSUE THREAD

**Issue by jakirkham** [Shippable/support#1519]
When using the standard docker image the command used for checkout is `git checkout -f <branch> --`, which works fine. However, when using a custom image, the common used for checkout becomes `git checkout -f <branch>` (i.e. `--` is missing). As a consequence, a failure occurs with the message below (unless of course there is a file/directory with the name of the git-branch). It appears there was a typo in one case vs. another.

    error: path spec '<branch>' did not match any file(s) known to git.

To be honest, I'm not sure I understand why this is necessary at all as that `git` command is followed by `git reset --hard <sha1>`, which should have the desired effect regardless.

**Comment by manishas** [comment]
@jakirkham are you still running into an error? Please re-open this issue or leave a comment if so. thanks!
