### ISSUE TITLE
Build timeout and some errors by build Android Project

### ISSUE THREAD

**Issue by mario-naether** [Shippable/support#1521]
Hi , recently I get some errors on build my Andriod Project.

https://app.shippable.com/projects/5551c34aedd7f2c052e982f2

Command "sudo apt-get update" output "W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B70731143DD9F856" 

Command: "echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null" outputed "Error: Ignoring unknown package filter 'platform-tools'"

Command: "echo yes | android update sdk -a -u -t sys-img-armeabi-v7a-android-10" outputed "Error: Ignoring unknown package filter 'sys-img-armeabi-v7a-android-10'  "

ShellScript "android-wait-for-emulator" outputed "
Command timed out
Command thread timed out"

Can anyone tell me what is wrong on my shippable config?

**Comment by manishas** [comment]
Sorry this seemed to have completely fallen off the radar.

We released an upgraded build system last week and since this issue was for the old one, I am going to close this. Let us know if this still fails on the new platform and we will look into it asap.
