### ISSUE TITLE
Any known issues with mocha-junit-reporter over-reporting number of passed tests?

### ISSUE THREAD

**Issue by tinisi** [Shippable/support#1523]
Folks,
Loving your service, getting very close to a useful CI solution.

We have a node app with about 1100 server side mocha tests.

Ever since we have switched to using mocha-junit-reporter with your service, the total number of tests shown in your web report is much inflated, by about a factor of 20.

When I run the tests locally with tap reporter, I see what I would expect.

We have tried a number of different set ups, letting mocha discover all our tests in a folder, and using a shell script and the mocha --grep option to run portions of the tests, but the number of passed tests is always high.

The failures seem to be reported correctly.

Are there any known issues that might cause this?

Thanks!
Tinisi

**Comment by tinisi** [comment]
Bumping...

**Comment by manishas** [comment]
Sorry for the delay here. We have redone our test reports handling, so not sure if this is still an issue.

I am closing this since it's an old issue but if anyone runs into this, please let us know and we will reopen.
