### ISSUE TITLE
Build failing because of error saving reports

### ISSUE THREAD

**Issue by adrianbk** [Shippable/support#1525]
Hi, 

I'm on the startup plan and my build is consistently failing when saving test reports:

![image](https://cloud.githubusercontent.com/assets/1910629/8019950/90dabac8-0caa-11e5-8117-4da59f483a3a.png)

Is there an upper limit on the the size of the test reports or the number of test results that shippable can handle?

Here's my build config: https://github.com/adrianbk/gradle/blob/shippable/shippable.yml

**Comment by manishas** [comment]
This is an old issue and we have upgraded our build platform this week. 

Closing.
