### ISSUE TITLE
Cache builds failing at 'commit for cache' stage

### ISSUE THREAD

**Issue by adrianbk** [Shippable/support#1527]
https://app.shippable.com/builds/55743aeb0d553e0c002eb819

It appears as if the `commit for cache` stage is not being executed and fails the build, despite the build script succeeding. Any idea what's happening here? 

__Failing build__
![image](https://cloud.githubusercontent.com/assets/1910629/8024278/41c8da7e-0d71-11e5-8149-d30b16d736c6.png)

__Successful build__
![image](https://cloud.githubusercontent.com/assets/1910629/8024287/a81b485c-0d71-11e5-80db-3fed83a62227.png)

**Comment by manishas** [comment]
we have completely revamped caching and this will not happen with the new design.

closing this but please let us know if you run into this.
