### ISSUE TITLE
Shippable hangs with no response when running velocity tests with Meteor.js

### ISSUE THREAD

**Issue by imarichardson** [Shippable/support#1530]
I am trying to run shippable against my meteor.js app.
My tests are in cucumber running via meteor's testing architecture, velocity. One of the things core to testing in meteor is that the app will need to run a cloned instance of itself so the tests can actually run. When I run the test my app perpetually runs; I've decided to not stop the latest build to see how long it will run and at this point it appears to be around 35 minutes. The build continues to show processing with no feedback.

Account name: imarichardson
Project: ve-client-meteor
See build 8. 

Here is my config:
https://gist.github.com/eac8b92e37942f9bbfe6

Thanks.

**Comment by imarichardson** [comment]
Just curious to see if any new info was found about this.
Thanks.

**Comment by imarichardson** [comment]
Guess not :(

**Comment by manishas** [comment]
We'll take a look at this in the next 24 hours. Sorry for the delay!

**Comment by imarichardson** [comment]
Thanks very much. 

I appreciate the response. 



—

**Comment by pauljohncleary** [comment]
I have the same issue... any update?

**Comment by manishas** [comment]
This is an old issue and we have upgraded our build system since then. I am closing this but please reopen if this happens again.
