### ISSUE TITLE
Missing shippable.yml 

### ISSUE THREAD

**Issue by jariwiklund** [Shippable/support#1532]
This morning shippable notifies me that shippable.yml is missing. Which I am sure it is not.
I have connected to a bitbucket repository

**Comment by babarinde** [comment]
Hi, just started noticing this issue myself from bitbucket as well

**Comment by rageshkrishna** [comment]
Starting an hour ago, we've been seeing some strange authorization errors from the BitBucket API. We're still trying to figure out a root cause. We haven't changed anything around this code in our service so I'm hoping this is just a temporary glitch at BitBucket.

**Comment by jariwiklund** [comment]
Seems to be working now. Perhaps this issue was the cause:
http://status.bitbucket.org/incidents/tvc55pbkssxn

**Comment by babarinde** [comment]
looks like it works now
