### ISSUE TITLE
Fail to deploy to Amazon Elastic Beanstalk 

### ISSUE THREAD

**Issue by truongces** [Shippable/support#1533]
Here is my shippable.yml

```
language: php

php:
  - 5.6

env:
  global:   
    - AWSAccessKeyId=my-key
    - AWSSecretKey=my-secret

before_install:
  - SUDO=$(which sudo) && $SUDO pip install awsebcli

before_script:
  - mysql -e 'create database if not exists test;'
  - mkdir -p ~/.aws
  - echo '[profile eb-cli]' > ~/.aws/config
  - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
  - echo "aws_secret_access_key = $AWSSecretKey" >> ~/.aws/config

script: true

after_success :
  - export PATH=$PATH:$PWD/aws/eb/linux/python2.7/ && virtualenv ve && source ve/bin/activate && pip install -r aws/requirements.txt && eb init && eb push
```

And I got error at after_success section, here is the errors log
```
ERROR: EOFError :: EOF when reading a line

Select a default region
1) us-east-1 : US East (N. Virginia)
2) us-west-1 : US West (N. California)
3) us-west-2 : US West (Oregon)
4) eu-west-1 : EU (Ireland)
5) eu-central-1 : EU (Frankfurt)
6) ap-southeast-1 : Asia Pacific (Singapore)
7) ap-southeast-2 : Asia Pacific (Sydney)
8) ap-northeast-1 : Asia Pacific (Tokyo)
9) sa-east-1 : South America (Sao Paulo)
(default is 3): 
```

Please help me fix this issue. Thanks so much.

**Comment by truongces** [comment]
I had used your sample https://github.com/shippableSamples/sample-php-mysql-beanstalk/ 
It still met the same issue.

**Comment by jariwiklund** [comment]
Its pretty obvious, the error log indicates in a big way that you need to define the region.
Under your before_script you need something like:
- echo "region=eu-east-1" >> ~/.aws/config

**Comment by truongces** [comment]
Can you share the documentation that help me walk through this issue?
After following your comment, I met the error below:
```
ERROR: EOFError :: EOF when reading a line

Select an application to use
1) cybermentor_dev
2) [ Create new Application ]
(default is 2): 
```
Under before_script, I added 
 - echo "application=cybermentor_dev" >> ~/.aws/config  

But its not work.Thanks for your help

**Comment by jariwiklund** [comment]
Seems like you're missing stuff under script:, in any case that part of your shippable.yml isn't the same as the sample

**Comment by truongces** [comment]
If I use stuff under script in the sample, this is the error that I got
```
mkdir -p .elasticbeanstalk
cp config.yml .elasticbeanstalk/
cp: cannot stat `config.yml': No such file or directory
```

**Comment by jariwiklund** [comment]
You are missing the config.yml file.
I suggest you make you local dev be able to deploy, before attempting to get shippable to deploy

**Comment by truongces** [comment]
Yes, you right. I miss the config.yml file.
Everything is working fine. Thanks for your help.
