### ISSUE TITLE
constantly getting throttled from github

### ISSUE THREAD

**Issue by spyrospph** [Shippable/support#1534]
I am usually getting the below error message when tryign to log in through github.

This usually occurs every GMT morning.

failed to fetch user profile (status: 403 data: {"message":"API rate limit exceeded for spyrospph.","documentation_url":"https://developer.github.com/v3/#rate-limiting"}) at /home/shippable/fe/node_modules/passport-github/lib/passport-github/strategy.js:90:28 at passBackControl (/home/shippable/fe/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:123:9) at IncomingMessage.<anonymous> (/home/shippable/fe/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:142:7) at IncomingMessage.emit (events.js:117:20) at _stream_readable.js:944:16 at process._tickCallback (node.js:448:13)

-S.

**Comment by manishas** [comment]
thanks for reporting this! we'll take a look asap.

**Comment by lekhab** [comment]
This is a known issue that is related to syncing a large number of repos and github rate limits. Unfortunately, we don't have a workaround for this currently. I am going to tag this as a feature request to keep a track on this.

**Comment by avinci** [comment]
we have reduced the calls massively to github. is this still occurring?
