### ISSUE TITLE
~50% Build Failures

### ISSUE THREAD

**Issue by jchamberlain** [Shippable/support#1535]
Hello,

I'm using a dedicated host, and in the last week or so I've been having at least half of builds fail for seemingly random reasons, including:
- Failing to connect to the Docker registry ("tcp: lookup registry-1.docker.io on 69.20.0.164:53: no such host")
- Doing nothing at all. All it ever shows is the "save reports" step. This is probably the most common error.
- Timing out with no message.

Has anything changed?

Update: I just deployed a fresh server for shippable, and nothing's changed.

**Comment by manishas** [comment]
@jchamberlain I will follow up with you over email.

**Comment by jchamberlain** [comment]
Thanks @manishas. I look forward to that.

**Comment by manishas** [comment]
@jchamberlain i am going to close this issue, but please let me know if this is not fixed yet. If you want to run your builds on your own servers, we have a new plan that you can switch to, let me know if you're interested.
