### ISSUE TITLE
Exclude Tag / Branch names with wildcards

### ISSUE THREAD

**Issue by TheEadie** [Shippable/support#1536]
Is it possible to exclude tags for building via wildcards eg. To not build anything beginning "bulid/" or "release/"

I've tried using the travis style regex in the excludes section of the shippable.yml but this doesn't seem to prevent the tag triggering a build.

```
branches:
  except:
    - /^build.*$/
```

**Comment by TheEadie** [comment]
Any thoughts on this guys?

**Comment by mbrodala** [comment]
I'd say this is a duplicate of #693

**Comment by manishas** [comment]
closing since this is a duplicate. i will leave the other one open.
