### ISSUE TITLE
Auto-start amazon dedicated nodes

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1537]
Hi,

We use a custom grid of nodes in Amazon EC2.

Problem is: most of the time, we don't really need all of them.

Is there a way to auto-start them when needed? Some hook, API call, or whatever...

Thanks!

**Comment by manishas** [comment]
@caarlos0 there is no way to do this currently.

Did you get our email about dedicated hosts?

**Comment by caarlos0** [comment]
@manishas Sad to hear that :/

No, I didn't (or missed it)... can you re-send it?

**Comment by lekhab** [comment]
Closing the issue - since the specific question was addressed.
