### ISSUE TITLE
Request for FQN in coverage report

### ISSUE THREAD

**Issue by jariwiklund** [Shippable/support#1540]
I would really like to have FQN (Fully Qualified Name) in coverage reports.
I'm using phpunit as examplified:
phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage --configuration phpunit.xml
But my coverage report only shows the class name and I have a few Classes called Controller(in different namespaces), so from the coverage report, it is impossible to know which of the Controller classes is covered.

**Comment by manishas** [comment]
Consolidating all code coverage requests in #174

**Comment by harryi3t** [comment]
@jariwiklund could you post a link to your build. Thanks.

**Comment by jariwiklund** [comment]
There you go
https://app.shippable.com/builds/55bf5e8385a1520b002615df
But for some reason there's nothing in the console?

**Comment by harryi3t** [comment]
@jariwiklund After our [release][1] in May this year, we have removed the `builds` objects. Instead now we have `runs` and `jobs`.

Seems like you haven't run a build since almost a year.

[1]:http://blog.shippable.com/a-lap-around-whats-new-in-shippable-4

**Comment by jariwiklund** [comment]
That is correct. So you will have to test for FQN in the coverage report yourself

MVH Jari
