### ISSUE TITLE
About ~50% of builds fail

### ISSUE THREAD

**Issue by nZac** [Shippable/support#1542]
I keep on getting an issue with builds failing during setup of the database.  The same build run two different times will fail once and succeed the next.

The lines that seem to fail are:
```yaml
- sudo echo "<REDACTED>" > /etc/postgresql/9.3/main/pg_hba.conf
- sudo echo "<REDACTED>" >> /etc/postgresql/9.3/main/pg_hba.conf
```

**Comment by manishas** [comment]
We have upgraded the build platform and this should not happen after your account is upgraded. 

Closing this issue.
