### ISSUE TITLE
apc support (php 5.6)

### ISSUE THREAD

**Issue by antonienko** [Shippable/support#1544]
I've added this line to my before_script section 
`- echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini`
as stated here:
http://shippable-docs-20.readthedocs.org/en/latest/languages/php.html

But I only obtain this error:
> PHP Warning: PHP Startup: Unable to load dynamic library '/home/shippable/.phpenv/versions/5.6.0/lib/php/extensions/no-debug-non-zts-20131226/apc.so' - /home/shippable/.phpenv/versions/5.6.0/lib/php/extensions/no-debug-non-zts-20131226/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0

Am I doing anything wrong?

**Comment by ThaDafinser** [comment]
Did you do `pecl install <extension>` ?

**Comment by antonienko** [comment]
In the documentation (link that I provided) it says 
> Our minions are pre-installed with the following PHP extensions.
>
>   amqp.so
>    apc.so
>    memcache.so
>    memcached.so
>    mongo.so
>    redis.so
>    xdebug.so
>    zmq.so

So I never tried to install it. But I just tried and:
> /tmp/pear/temp/APC/apc_cache.c: In function ‘_apc_cache_user_update’:
>
> /tmp/pear/temp/APC/apc_cache.c:818:63: error: ‘IS_CONSTANT_INDEX’ undeclared (first use in this function)
>
> /tmp/pear/temp/APC/apc_cache.c:818:63: note: each undeclared identifier is reported only once for each function it appears in
> 
> /tmp/pear/temp/APC/apc_cache.c:820:22: error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function)
>
> make: *** [apc_cache.lo] Error 1
> ERROR: `make' failed

**Comment by ThaDafinser** [comment]
@antonienko because APC is outdated in newer PHP versions. Since PHP 5.5 opcache is the optimizer to go. https://github.com/krakjoe/apcu/issues/73

If you still rely on the "userland cache" try `APCu` (see the U)
https://pecl.php.net/package/APCu

**Comment by antonienko** [comment]
That was it, I installed apcu. I guess the documentation should be updated to include that information. Thanks @ThaDafinser

**Comment by ThaDafinser** [comment]
Ping @manishas ...can u update the doc?
