### ISSUE TITLE
Automated build on each commit should trigger a new build in Dockerhub

### ISSUE THREAD

**Issue by guysyml** [Shippable/support#1545]
Hi Team,

I want to know can shippable be able to do the automated build each and everytime a new commit is triggered in github or bitbucket.
So that each trigger can build a new image and that can be used to for continious delivery.

I have the setup where automated builds happening.
git->docker->nirmata where my applications are running on nirmata. they are maintaing the micro services for us. Is this possible the same way can shippable maintain the micro services.

Regards,
Guy

**Comment by pelegb** [comment]
I've setup build triggers on docker hub and then put a curl cmd in the after_success section:
after_success:
- curl -H "Content-Type:application/json" --data "{\"source_type\":\"Branch\", \"source_name\":\"${BRANCH}\"}" -X POST https://registry.hub.docker.com//YOUR_KEY

Hope this helps

**Comment by manishas** [comment]
@guysyml watch for our announcement on June 17 :)

**Comment by manishas** [comment]
@guysyml I wanted to bring your attention to our announcement regarding Shippable formations. You can run your application environments on Formations, we support microservices as well.

You can sign up for a demo here - https://shippable.youcanbook.me/

For more information, check out -
http://blog.shippable.com/introducing-shippable-formations-devops20-for-dockerized-apps
https://app.shippable.com/mktg/#formations

**Comment by manishas** [comment]
closing this isue. @guysyml let me know if you have any other questions.
