### ISSUE TITLE
[PHP] build in ldap extension? 

### ISSUE THREAD

**Issue by ThaDafinser** [Shippable/support#1546]
There are some php - extensions around and the ones available on pecl can be installed.
http://shippable-docs-20.readthedocs.org/en/latest/languages/php.html

But `ldap` comes with PHP and there is no version on `pecl`...how can i install it?

Just `enable it` does not work: https://app.shippable.com/builds/557ae2297915e70b005988b1

**Comment by manishas** [comment]
@ThaDafinser wouldn't sudo apt-get install php5-ldap work for installing this? That's what I get when I google this issue..

**Comment by manishas** [comment]
closing, please comment or reopen if it foesnt work for you.
