### ISSUE TITLE
Service status right now?

### ISSUE THREAD

**Issue by lukehutton** [Shippable/support#1548]
I'm getting hanging builds on my project for past 15 minutes.

Waiting for build information...

Thanks!

**Comment by manishas** [comment]
@lukehutton can you point me to the build link? I cannot see anything waiting for your account.

**Comment by lukehutton** [comment]
Sure, build link: https://app.shippable.com/builds/557b54567915e70b005993d4
Project link: https://app.shippable.com/projects/554cf64cedd7f2c052e616ad

Cheers

**Comment by lukehutton** [comment]
Up now! thanks.
