### ISSUE TITLE
Can I trigger a build for another repository?

### ISSUE THREAD

**Issue by limikael** [Shippable/support#1549]
Can I set things up so that when I push to a certain repository, this will trigger a checkout and a build of another repository? I would like to use this since I have a main project repository and some dependency projects. I would like a commit to one of the dependency projects to trigger a build on the main project.

Thanks in advance!

**Comment by limikael** [comment]
Yes I can... :)

http://blog.shippable.com/daisychaining-builds-with-our-new-public-api

**Comment by manishas** [comment]
@limikael let me know if you could successfully set up daisy chained builds.

**Comment by limikael** [comment]
Actually, I didn't actually go the whole way of setting it up, since this requires a paied account, and I only have a free one. Is this correct btw? It is not possible to set this up on a free account?

**Comment by lekhab** [comment]
Yes, using our API does require a paid account, I am afraid.

**Comment by limikael** [comment]
I realized however that your cheapest plan was only $1 per month, which is very resonable!

**Comment by lekhab** [comment]
@limikael: We launched our new version and updated our pricing plans only a couple of weeks ago :-) Still very reasonable though - it is $10/month/container for a paid plan.

You can read more about our pricing plans here:
https://app.shippable.com/pricing.html

Please let me know if you have any further questions.
