### ISSUE TITLE
build timeouts

### ISSUE THREAD

**Issue by magwas** [Shippable/support#1550]
I have a build which consists of some python unit tests followed with some selenium tests in python for chrome and firefox. For the selenium tests I run an apache on ports 8888 and 8889, and a fake smtp server on 1025, all on 127.0.0.1. The build runs nicely on travis. When it finishes on shippable, it runs for 13 minutes.
However there are a lot of cases when it just times out.
I suspect that it has something to do with selenium.
Build history:
https://app.shippable.com/projects/55771730edd7f2c0520e8d4c

**Comment by manishas** [comment]
@magwas are you still looking for a response to this? I see your latest builds are not timing out.

**Comment by lekhab** [comment]
closing. please let me know if there are any recent builds facing issues.
