### ISSUE TITLE
Build project button should allow to reset minion

### ISSUE THREAD

**Issue by pelegb** [Shippable/support#1551]
Feature request - web interface build project button should have ability to reset minion.

**Comment by manishas** [comment]
DUP of #829. This is on our radar now and will be available in the next few days.

**Comment by manishas** [comment]
This is now available in the UI through project settings -

![screen shot 2015-07-30 at 9 58 27 am](https://cloud.githubusercontent.com/assets/2983749/8989549/a9c0f162-36a1-11e5-9197-1169aba82f8e.png)

Thanks for your patience!
