### ISSUE TITLE
Not able to install 'curl'

### ISSUE THREAD

**Issue by gamename** [Shippable/support#1552]
Hi,

I'm unable to install curl in this build:
https://app.shippable.com/builds/557dd597781ebc0c00a95b16

**Comment by rageshkrishna** [comment]
It's possible that the apt repositories have been updated. Please try running `sudo apt-get update` before the install.

**Comment by gamename** [comment]
Thanks!  I'll try that.

**Comment by manishas** [comment]
@gamename did the suggestion above work? Please re-open this issue if your build still fails.
