### ISSUE TITLE
Can't view build results anonymously

### ISSUE THREAD

**Issue by zachriggle** [Shippable/support#1553]
I am unable to view build results from an incognito session:

https://app.shippable.com/projects/55687795edd7f2c05200bc0b

However, I *can* view Travis CI resukts:

https://travis-ci.org/binjitsu/binjitsu

What setting to I need to enable to de-restrict the results so that they are viewable?

**Comment by manishas** [comment]
@zachriggle our current design requires you to sign in to view build results, even for public projects. We're working on changing this soon, I'll let you know when it's available.

**Comment by manishas** [comment]
This is now available.... you can view build results of public projects without signing into shippable.
