### ISSUE TITLE
Getting an SSH key?

### ISSUE THREAD

**Issue by tekram** [Shippable/support#1555]
It mentions at the link below that we can grab an SSH key from the 'Deployment Key' tab under 'Settings'. Has this been removed as it does not seem to be present anymore? 

http://docs.shippable.com/deployment/heroku/

**Comment by tekram** [comment]
Location has changes but the docs are a bit outdated...

http://blog.shippable.com/continuous-nodejs-deployment-to-digitalocean

**Comment by manishas** [comment]
@tekram thanks for tracking this down. Let me know if you need help with anything else.
