### ISSUE TITLE
Can't find the re-run button after UI upgrade

### ISSUE THREAD

**Issue by caesarxuchao** [Shippable/support#1560]
I can't find the button to re-run the test after the UI upgrade. Could someone help?

cc @nikhiljindal

**Comment by manishas** [comment]
@caesarxuchao you can go to the Project page and then for the last build, click on the play button to the right. That will rerun the build.

**Comment by caesarxuchao** [comment]
Thank you very much @manishas. I found the button, but I think this UI change makes the re-run operation very inconvenient. I need to: 1. go to the project page, 2. click "PR build", 3. click on "fetch more" multiple times, 4. finally I found my PR and click re-run. Plus, each operation takes 5-10 seconds to load the webpage. The old way is much more smooth.

**Comment by nikhiljindal** [comment]
+1. To clarify, earlier the build page itself (ex: https://app.shippable.com/builds/5581ca373d07800f0005e452) had the rerun button, which was way simpler than going to the project page and finding the specific build there.

**Comment by caesarxuchao** [comment]
Same as the first point in #1562.

**Comment by caarlos0** [comment]
BTW: we use custom nodes... some PR's simply disappeared from the PR list... cannot restart, cannot do anything... :/

**Comment by davidopp** [comment]
+1, it would be really really really great to have the "re-run" button back on each build page as before.

**Comment by manishas** [comment]
Feedback taken :) we'll address this.

**Comment by caarlos0** [comment]
@manishas thanks =)

**Comment by lekhab** [comment]
The UI updates over the last few days included adding back the re-run option to the build pages and a few other enhancments based on feedback. Please take a look and let us know what you think.

**Comment by davidopp** [comment]
I see the re-run link -- thanks!

**Comment by caesarxuchao** [comment]
Thank you, @lekhab.
