### ISSUE TITLE
Can't download console output after UI upgrade

### ISSUE THREAD

**Issue by caesarxuchao** [Shippable/support#1561]
After the UI upgrade, when I try to download the console output, the webpage response with a page saying "unauthorized". Could someone help?

cc @nikhiljindal

**Comment by manishas** [comment]
We'll look into this and get back to you.

**Comment by manishas** [comment]
This should be fixed now. Please let us know if this still doesn't work for you.

**Comment by caesarxuchao** [comment]
Thank you @manishas. It's working now.

I have another question about the log download. I tried to download the logs throught wget, what credentials shall I supply if I linked my GH account with Shippable? The authentication failed when I supplied my GH user name and password. Thanks.

**Comment by lekhab** [comment]
@caesarxuchao: To use our API to download console logs, you need an API token to authenticate. (http://docs.shippable.com/api/#authentication). You can generate an API token by going to your Account Settings page and scroll down to API tokens.

The syntax below worked for me. Please give it a shot and let me know if you have any questions.

wget -qO- -- header "x-api-key:<API_TOKEN>" https://api.shippable.com/builds/<build_id>/1/console/download

**Comment by caesarxuchao** [comment]
Hi @lekhab, thank you for the information. I tried the command you provided but still got an authentication error, but I didn't try hard enough anyway. I'll let you know if I need further help. Thanks again.
