### ISSUE TITLE
New version problems

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1562]
- cannot stop/restart from the build view
- cannot download build log
- log view doesn't auto-update
- seems like the build distribution across custom nodes is broken (feels like it send almost all builds to a single machine)
- cannot see initialization logs on custom nodes view
- some pull requests simply don't appear in the PR list

**Comment by jchamberlain** [comment]
Can I add one?
* Because the height of each build row has increased in the UI so dramatically, I can only see about 1/4th of the information on the project page that I used to be able to see. I would much prefer to see the last 20 or so builds in the same space that I can now see only 5 or so builds.

**Comment by geshan** [comment]
The build sorting in the project page is all messed up, please make it as it was latest first.

**Comment by manishas** [comment]
Thanks for the feedback! We will definitely work on addressing most of these problems in the next few days.

- cannot stop/restart from the build view 
- make re-running a build easier 
- log view doesn't update (should be fixed already)
- some pull requests simply don't appear in the PR list (is being worked on as we speak)
- Alternate views for showing build listing

**Comment by caarlos0** [comment]
@manishas Nice! Many thanks! :)

BTW: besides these problems, the new interface seems faster than the previous one... congrats the team for me :beers:

**Comment by manishas** [comment]
@caarlos0 thanks! :)

**Comment by manishas** [comment]
This has been completely revamped with the new upgrade. Closing.
