### ISSUE TITLE
Python 3.4 failure

### ISSUE THREAD

**Issue by pmacosta** [Shippable/support#1563]
I have a repo with a Python package that is passing all tests with Python 2.7 but it is failing with Python 3.4. The failure is not on the tests, the process does not even get there. As part of the test process I build the package with "python setup.py sdist". With Python 3.4 I get

ImportError: No module named 'setuptools' 

Build information: https://app.shippable.com/builds/5581b5c93d07800f0005bc56

I poked around and there doesn't seem to be a proper Python 3.4 tool chain (pip, py.test, etc.) in the minion. Do I have to activate a virtual environment or something like that? What is the best practice for Python 3.4?

Thanks!

Pablo

**Comment by manishas** [comment]
We have Python 3.5 in our new build images in the [drydock repo on docker hub](https://hub.docker.com/u/drydock/)

This has all the tool chain required in the minion. Closing.
