### ISSUE TITLE
Device out of space

### ISSUE THREAD

**Issue by kkarski** [Shippable/support#1564]
Here is what I see in my logs:

134a5dcb8ebe: Error downloading dependent layers
63655319ed5c: Error pulling image (latest) from shippable/minv2, endpoint: https://registry-1.docker.io/v1/, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device
63655319ed5c: Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device
time="2015-06-17T20:20:01Z" level="fatal" msg="Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device"

**Comment by manishas** [comment]
Looking into this now. Thanks!

**Comment by phagunbaya** [comment]
Happening same on dedicated hosts. Old builds are not getting cleanup automatically.

**Comment by kkarski** [comment]
So... Is this something I need to do something about?

**Comment by kkarski** [comment]
OK...deleted all old builds but one...still get the same error message.

**Comment by kkarski** [comment]
Still happening

https://app.shippable.com/builds/55848d4e88c5380b008e40fd

**Comment by kkarski** [comment]
Any resolution on this?

**Comment by manishas** [comment]
Yes we've tracked down the issue and will fix it in the next 1-2 days. I will update when done. Sorry about this!

**Comment by kkarski** [comment]
Still happening

134a5dcb8ebe: Pulling fs layer
134a5dcb8ebe: Error downloading dependent layers
63655319ed5c: Error pulling image (latest) from shippable/minv2, endpoint: https://registry-1.docker.io/v1/, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device
63655319ed5c: Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device
time="2015-06-29T20:30:21Z" level="fatal" msg="Error pulling image (latest) from shippable/minv2, ApplyLayer exit status 1 write /home/shippable/.gvm/gos/go1.2/src/pkg/go/token/position_test.go: no space left on device"

**Comment by lekhab** [comment]
Adding updates to the issue from the email thread with @kkarski:

- The OS on the machine is an unsupported one, so unable to upgrade docker. We only support these platforms: http://docs.shippable.com/supported_services/#platforms.  Are you able to use one of the supported platforms? 
- Also, shippable/minv2 is a huge image that can potentially cause space issues. We recommend using an image more specific to your needs. Build images for specific languages are available in the public Docker repo shippableimages/*.
