### ISSUE TITLE
Docs: What controls email notifications?

### ISSUE THREAD

**Issue by gohanman** [Shippable/support#1565]
New user, simple question, but I'm not seeing anything obvious in the docs or settings. I have two projects running in shippable. Both run tests automatically when I commit. One sends me email notifications when the build fails; the other does not.

The one that sends me email notifications:
* Is a public github repository
* Is part of a github organization where I am the *owner*
* Is using a .travis.yml 
* Is marked as *watching* on github

The one that does not send me email notifications:
* Is a private github repository
* Is part of a github organization where I am a *member* 
* Is using a .travis.yml (an identical one, actually)
* Is marked as *watching* on github

What setting(s) on shippable and/or github control whether email notifications go out on build failures?

**Comment by manishas** [comment]
@gohanman our notifications are documented here - http://docs.shippable.com/project_settings/#notifications

We'll take a look at what's going on...

**Comment by gohanman** [comment]
Thanks! Perhaps I need to add a proper shippable.yml rather than lazily relying on travis-ci compatibility.

**Comment by manishas** [comment]
Closing this issue. Please let me know if you have any other questions.
