### ISSUE TITLE
Build time

### ISSUE THREAD

**Issue by pelegb** [Shippable/support#1566]
There seems to be a discrepancy between the build time displayed and summing the time all the build steps took. For example in the following build:
https://app.shippable.com/builds/5581e3033d07800f00060ca9

Your UI says the build time is 7 minutes while summing all the steps times you receive 110 + 4  secs = less than 2 minutes.

**Comment by manishas** [comment]
@pelegb this is an area we need to improve in. Currently, each step reports the time it took to execute, but there are things that happen in between that aren't accounted for.

The total build time is correct, though.

**Comment by manishas** [comment]
we have revamped the build platform and now show only the overall build time. Closing this.
