### ISSUE TITLE
No dedicated hosts in the new UI?

### ISSUE THREAD

**Issue by pcsforeducation** [Shippable/support#1567]
I got really excited about the new UI/features, but I don't see support for dedicated hosts anywhere (the main selling point to me) and the docs haven't been updated. Any word on this?

**Comment by kkarski** [comment]
Yeah, my dedicated hosts also diapered. I still have the Shippable containers running on my private hosts? Did this feature get taken out?

KK

**Comment by manishas** [comment]
@kkarski @pcsforeducation we sent out communication about dedicated hosts a couple of weeks ago.

Dedicated Hosts was a beta feature that we added in order to support advanced Docker functionality. Over the last few months, we've added all the functionality to our service, negating the need for this feature. As a result, we plan to deprecate this on July 31,2015.

I'll post the email as a blog on our site so that everyone is aware.

**Comment by pcsforeducation** [comment]
I see you have caching in the new version but couldn't find docs for
exactly what was happening. My pipeline (on a vagrant box currently) is
(Python backend): run unit tests (and functional soon) in a prebuilt
container (don't have to install deps), build production container, run
integration tests, push container, run Ansible to deploy. The testing
portion only takes a couple minutes locally because most of the testing
container is already cached, no dep install, etc. I was hoping to move this
pipeline to shippable, but without dedicated hosts, I fear it will take
much longer.

**Comment by rvdwijngaard** [comment]
One of the reasons we are using dedicated hosts is that we can run them on aws. We use aws security while interacting with other aws services. How can we do this without dedicated hosts? I don't want to store aws keys in my yml files.

**Comment by pmoust** [comment]
Same issue with @rvdwijngaard . Shippable dedicated hosts were used with AWS IAM Roles that allowed certain actions.

**Comment by manishas** [comment]
@rvdwijngaard @pmoust @pcsforeducation can you send me an email at manisha@shippable.com with a broader explanation of your scenario and why dedicated hosts were necessary for those scenarios?

This will help a great deal while we decide on our roadmap with dedicated hosts.

**Comment by pcsforeducation** [comment]
Sorry, I already jumped ship (heh, get it?) to a Jenkins server. Couple
hours of set up and my builds/deploys are faster than ever.
