### ISSUE TITLE
Download Artifacts in New UI ?

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1568]
Hi,

I am unable to find link to download artifacts file in the new UI. Previously there was an icon which allowed us to download artifacts. 

Some help, where to find the artifacts link on new UI now

Naveen

**Comment by manishas** [comment]
@naveensky we missed this during our upgrade :(

Adding it back in today, so you should see it show up tomorrow.

**Comment by naveensky** [comment]
@manishas - I can see the download link now. Thanks for working on it so soon :)
