### ISSUE TITLE
Shippable UI Broken due to unsafe JS files ?

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1569]
Hi,

I need to explicitly enable allow unsafe JS files on UI after which I have UI working properly on my chrome browser. If I do not do that, UI breaks badly for me, but it is usable

Naveen

**Comment by manishas** [comment]
@naveensky at what point do you run into this? As soon as you sign in, or when do you take a specific action? We don't see this at our end, so some repro steps would be super helpful.

Also, a screenshot will help too.

**Comment by naveensky** [comment]
@manishas - I did allow them manually and cant reproduce the broken UI on my machine. I'll close it down this for now, in case I can replicate it, I will open again

**Comment by manishas** [comment]
We've tracked down this issue and it will be addressed soon. Thanks for reporting it!
