### ISSUE TITLE
Create new build for branch failed

### ISSUE THREAD

**Issue by vladdancer** [Shippable/support#1570]
Error that I've got 
```
{"id":3000,"message":"No access or object not found for :id 5582a15f3d07800f0007b8f5","methodName":"chkPermForId|_getBuildById"}
```

**Comment by manishas** [comment]
@vladdancer can you point us to the project and branch?

**Comment by jpanlasi** [comment]
I'm getting the same error message.

{"id":3000,"message":"No access or object not found for :id 55831326152d7e0b0099037c","methodName":"chkPermForId|_getBuildById"}

Project ID: 5582feb6edd7f2c052246507
Branch: master

I am the owner of the project source code and it is a public repo. 
https://github.com/jpanlasi/ics53-lab4

**Comment by kurtiss** [comment]
I'm getting this too.
{"id":3000,"message":"No access or object not found for :id 5584a64588c5380b008e7cea","methodName":"chkPermForId|_getBuildById"}

https://app.shippable.com/projects/5584a5b9edd7f2c052296e85
https://github.com/kurtiss/nsadmin

**Comment by manishas** [comment]
we're looking into this. @kurtiss thanks for the links!

**Comment by manishas** [comment]
@kurtiss does the branch you're trying to build have a shippable.yml in it?

**Comment by kurtiss** [comment]
Yes, you should see it there on GitHub.

**Comment by manishas** [comment]
@kurtiss I checked the yml using a yml validator and there is an error in it 

http://yaml-online-parser.appspot.com

We will improve the experience around this error handling.

@vladdancer @jpanlasi can you validate your yml as well?

**Comment by kurtiss** [comment]
@manishas Thanks, that was it. My fault!

**Comment by jpanlasi** [comment]
AH, @manishas thanks! How embarrassing

**Comment by manishas** [comment]
Thanks for confirming! We'll improve the error handling experience so that it's obvious what's wrong.

**Comment by vladdancer** [comment]
@manishas , thanks for help but my yml is a valid and I still get an error.
Project: 552d00ec5ab6cc1352c377d7
Branch: any (for example:  v1/AL-87)

**Comment by aug70** [comment]
Same problem https://github.com/Shippable/support/issues/1602
