### ISSUE TITLE
How do I remove a user from my account?

### ISSUE THREAD

**Issue by epicserve** [Shippable/support#1573]
I can't figure out how to remove this user.

![shippable hosted continuous integration service 2015-06-18 10-47-56](https://cloud.githubusercontent.com/assets/191620/8235490/e9a108dc-15a7-11e5-84af-831def30fe7e.jpg)

I think he was added because he's a support person with Shippable.

**Comment by manishas** [comment]
@epicserve this isn't a Shippable support person. https://github.com/bkroeze

Do you have access to some repositories in bkroeze's account? Are you a collaborator for any of their repositories?

**Comment by epicserve** [comment]
I have no idea who this person.

**Comment by manishas** [comment]
we'll look into it...

**Comment by epicserve** [comment]
@manishas Any updates?

**Comment by epicserve** [comment]
@manishas Any sort of any ETA on this issue?

**Comment by manishas** [comment]
@epicserve I'll follow up on both your recent issues and get you an update today.

**Comment by manishas** [comment]
You have forked a repository from bitbucket/bkroeze and you're on his list of watchers for the repo, so when we call the bitbucket API it returns this as well. You can delete your fork, sync your account, and see if that resolves this -

![screen shot 2015-06-26 at 6 59 13 pm](https://cloud.githubusercontent.com/assets/2983749/8390006/78c10498-1c35-11e5-8ab0-8c40a0eeab42.png)

![screen shot 2015-06-26 at 7 00 48 pm](https://cloud.githubusercontent.com/assets/2983749/8390013/afcf2122-1c35-11e5-8099-8eb0b25458cf.png)

**Comment by manishas** [comment]
@epicserve I am closing this issue but if you need more help, please don't hesitate to reach out.

**Comment by epicserve** [comment]
Seems like a weird behavior of Shippable to add users to your shippable of repositories you have forked or are watching. It would be nice if Shippable would do that. :) Anyway, I stopped watching the repository and deleted my fork and then re-synced and the user is gone from my shippable CI list.
