### ISSUE TITLE
Current Builds Display Showing (seemingly) Random Unordered List

### ISSUE THREAD

**Issue by markTward** [Shippable/support#1575]
When I link to the Current Builds page from the home page, my most recent build isn't appearing.  Additionally, a refresh of the Current Builds page changes the order/display of the builds.  A descending timestamp order would be helpful.

I like the organization by build and branches.  It would be very useful if one could jump to a build branch set from a link, dropdown, &c.  However for my most recent build, the branch section isn't appearing.

Take One
![screen shot 2015-06-18 at 4 10 40 pm](https://cloud.githubusercontent.com/assets/4840338/8244362/9dab4000-15d4-11e5-8534-1302d8aaea0b.png)

Take Two (after refresh)
![screen shot 2015-06-18 at 4 12 10 pm](https://cloud.githubusercontent.com/assets/4840338/8244380/cc372740-15d4-11e5-87d3-cf52d57b3148.png)

**Comment by manishas** [comment]
@markTward do you still see this?

The Current builds list should show the latest completed build for each branch, sorted by latest first.

**Comment by markTward** [comment]
The sorted list for the branch now appears in descending build order.  Thanks for the quick fix.
