### ISSUE TITLE
Newbie question: Why is the "Run Build" icon not showing up on the Shippable project page?

### ISSUE THREAD

**Issue by mulupuru** [Shippable/support#1577]
Context: I am interested in trying out the new Formations feature. This is the first I am using Shippable CI. So, please bear with my newbie questions, and would appreciate pointing me in the right direction.

In spirit of getting my first Shippable project up and running, I set up a public Github repo (https://github.com/mulupuru/sj.git), that is essentially a copy of the Shippable Java sample https://github.com/shippableSamples/sample_java, without pom.xml (because I stripped out any references to running test scripts).

I followed instructions at http://docs.shippable.com/.

shippable.yml for this public repo is below:

language: java

jdk:
   - openjdk7
   - oraclejdk7
   - openjdk6
   - oraclejdk8

Issue: I was expecting to see a "Run Build" icon on my Shippable subscriptions page for my Shippable account. But, I am not seeing anything there. My account's project status page is: https://app.shippable.com/subscriptions/5581d2adedd7f2c052209b4e/projectsStatus.

Could some one help please? Let me know if there is any additional information that I could provide here.

**Comment by manishas** [comment]
The easiest way to trigger a build is to change something in the readme file. That should auto-trigger a build. 

That being said, I'm not sure why your project doesn't show the run build control. I'll follow up and let you know.

**Comment by winglian** [comment]
Yes, please fix this ASAP!

**Comment by manishas** [comment]
Followed up on this. We do have a run build but we need to improve UX here.

To run a build with latest code in a branch, click on the play button for the branch you want to build under Current builds on the Project page.

![screen shot 2015-06-19 at 8 46 48 am](https://cloud.githubusercontent.com/assets/2983749/8257112/413b3ffa-1660-11e5-9f64-1346bf570a5f.png)

**Comment by manishas** [comment]
@winglian @mulupuru let me know if you need help with anything else. closing this issue since the run build action is available.

**Comment by mulupuru** [comment]
This issue is now addressed for me, thanks for the quick turnaround. You may leave this in resolved state (or close it altogether).

As fyi, when cloning from an existing repo (as I did by cloning the Shippable's Java sample repo), the Play or the Run Build icons don't show up. I am working around this by touching README.md, as you suggested. You may want to consider fixing this. Please find screen shot below.

![1](https://cloud.githubusercontent.com/assets/2811235/8322506/404997b6-19eb-11e5-96b4-1a5edf0ae427.png)
