### ISSUE TITLE
Build failed, but all console actions show success. What failed?

### ISSUE THREAD

**Issue by HeyZiko** [Shippable/support#1579]
When I get into the details of my build, the build shows as failed but every batch executed in the console has a green checkmark.
https://app.shippable.com/builds/5584477888c5380b008d4c22 

I can't seem to dig any deeper to determine what failed. 

Am I missing something?

**Comment by manishas** [comment]
I've logged an issue in the internal system. Will update as soon as I know more.

**Comment by jeffkole** [comment]
Same thing just happened to me.

**Comment by HeyZiko** [comment]
@manishas any word on this?
Thx!

**Comment by manishas** [comment]
Yes we've tracked down the issue and it will be fixed soon. I'll update you when it's deployed.

**Comment by lgfausak** [comment]
I just ran in to the same issue.

**Comment by leonfs** [comment]
I'm also having the same issue. Any updates on the status?

**Comment by lekhab** [comment]
@leonfs: following up on your build. The previous issues were resolved, so I am going to close this and open yours as a new support issue. Please track your issue here: #1816
