### ISSUE TITLE
Build Badges no longer showing in the new UI?

### ISSUE THREAD

**Issue by KFCSpike** [Shippable/support#1580]
Previously, the build status badges would show on the project page (https://github.com/Shippable/support/issues/20).
Clicking on the badges would show how to use them.

It is still possible to use badges for the project by creating the link(s) manually (as per examples below) but having the image and link on the dashboard previously made things a bit easier for anyone new to Shippable.
An alternative option to showing the badges (with instructions) on the project page might be to update the docs to explain how to show badges?

Examples:
Master
`https://api.shippable.com/projects/54d05baa5ab6cc13528a9e64/badge/master`

Will show the status of the master branch:
![Master](https://api.shippable.com/projects/54d05baa5ab6cc13528a9e64/badge/master)

Develop
`https://api.shippable.com/projects/54d05baa5ab6cc13528a9e64/badge/master`

Will show the status of the develop branch:
![Master](https://api.shippable.com/projects/54d05baa5ab6cc13528a9e64/badge/develop)

**Comment by manishas** [comment]
@KFCSpike yes, we will update the docs asap. Thanks for your feedback!

**Comment by KFCSpike** [comment]
Thanks @manishas  I raised it as an issue in the docs repo.
