### ISSUE TITLE
There is no way to rebuild on the build page of the new UI

### ISSUE THREAD

**Issue by mikedanese** [Shippable/support#1581]
I have to go all the way back to the PR list to find the rebuild button.

**Comment by manishas** [comment]
we just deployed a fix for this in the morning. 
![screen shot 2015-06-20 at 10 51 47 am](https://cloud.githubusercontent.com/assets/2983749/8268436/61183d98-173a-11e5-878e-cf97de6ad088.png)

**Comment by mikedanese** [comment]
Thanks!
