### ISSUE TITLE
API support to create and destroy Formations

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1583]
Great release guys, I believe we will be moving to Formations soon.

Your API needs some (or a lot) love first though.

**Comment by manishas** [comment]
@pmoust let's set up a time in a few days to discuss further. We're improving the API and I'd love to understand exactly what you're trying to achieve with it.

Will send you a meeting request soon. Thanks!!

**Comment by manishas** [comment]
Formations have been deprecated and replaced by integrated pipelines. The API for these will be documented next week.

The build system upgrade has complete new APIs.
