### ISSUE TITLE
Bitbucket triggers broken?

### ISSUE THREAD

**Issue by mgladdish** [Shippable/support#1585]
I pushed several changes to my private bitbucket repo on Friday last week and today, none of which triggered a build in Shippable. 
Re-running the build only took the code from the previous build's commit.

I lost patience and deleted the Shippable project in order to re-create it and start again, only this hasn't worked properly. The repo shows up as an available project, I enable it, so it appears on the list of bitbucket projects as "new". I click on that to go to the build screen: https://app.shippable.com/projects/550022db5ab6cc135297e740 and all appears well. So I click on "run a new build for this branch" but then I get the error:
{"id":3000,"message":"No access or object not found for :id 55882999607cdd0b00a15560","methodName":"chkPermForId|_getBuildById"}
and the page says "Build not found".

**Comment by rvdwijngaard** [comment]
Hi, 

I am having the same issue right now; it worked earlier today but I just committed some changes to my repo and no build is triggered; i get similar error message as mentioned above. 

please help, this is blocking my deployment.

**Comment by phagunbaya** [comment]
Same happening with github integration. Also not able to reset a dedicated host. Blocker for our deployment too.

**Comment by jonmer85** [comment]
+1 for Broken GitHub integration. This is blocking my release!

**Comment by AaronBedward** [comment]
Same smell the trigger works for my develop branch but not for master

**Comment by alan-unravel** [comment]
+1

**Comment by manishas** [comment]
These issues should be resolved now, so closing this issue. If you're still running into a specific problem, can you please open up a new support issue? Thanks!
