### ISSUE TITLE
Failure on fetching apahe packages on ubuntu

### ISSUE THREAD

**Issue by cymeng** [Shippable/support#1586]
similar to #1272 we started experiencing following failures today:

```
Err http://www.apache.org 21x/main Sources
404 Not Found [IP: 108.168.194.91 80]
Err http://www.apache.org 21x/main amd64 Packages
401 Unauthorized [IP: 108.168.194.91 80]
Err http://www.apache.org 21x/main i386 Packages
401 Unauthorized [IP: 108.168.194.92 80]
Fetched 4,579 kB in 5s (819 kB/s)
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/main/source/Sources 404 Not Found [IP: 108.168.194.91 80]
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/main/binary-amd64/Packages 401 Unauthorized [IP: 108.168.194.91 80]
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/main/binary-i386/Packages 401 Unauthorized [IP: 108.168.194.92 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by darylng** [comment]
I'm seeing the same problems too 

>Err http://www.apache.org 21x/main Sources
>404 Not Found [IP: 108.168.194.91 80]
>Err http://www.apache.org 21x/main amd64 Packages
>401 Unauthorized [IP: 108.168.194.91 80]
>Err http://www.apache.org 21x/main i386 Packages
>401 Unauthorized [IP: 108.168.194.91 80]
>Fetched 4,573 kB in 4s (1,066 kB/s)
>W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B70731143DD9F856
>W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/main/source/Sources 404 Not Found [IP: 108.168.194.91 80]
>W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/main/binary-amd64/Packages 401 Unauthorized [IP: 108.168.194.91 80]
>W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/21x/main/binary-i386/Packages 401 Unauthorized [IP: 108.168.194.91 80]
>E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by cymeng** [comment]
@darylng just in case you missed it, comments in ticket #1272 mentioned a workaround, which could be used temporarily :)

```
install:
- sudo sed -i '/apache/d' /etc/apt/sources.list
- sudo apt-get update
```

**Comment by darylng** [comment]
@cymeng thanks!

**Comment by manishas** [comment]
debian mirrors were down last time this happened, so it should be resolved now. Please confirm that everything works for you now. Thanks!

**Comment by manishas** [comment]
Closing this issue, please feel free to re-open if you run into this again and debian mirrors are not down.

http://mirror.debian.org/status.html
