### ISSUE TITLE
Build Not Found

### ISSUE THREAD

**Issue by erwindev** [Shippable/support#1589]
I am getting this error when I try to invoke a build.

{"id":3000,"message":"No access or object not found for :id 55886ec947a1ce0b00f01b67","methodName":"chkPermForId|_getBuildById"}

My builds were working up until a few hours ago.

**Comment by phagunbaya** [comment]
#1588

**Comment by manishas** [comment]
We'll look into it

**Comment by manishas** [comment]
@erwindev this should be resolved now. Can you please confirm?

**Comment by manishas** [comment]
Closing. Please re-open if it happens again.
