### ISSUE TITLE
Internal API error : getPermissionByProjectId

### ISSUE THREAD

**Issue by timstclair** [Shippable/support#1590]
I'm unable to view details for a failed shippable run on https://github.com/GoogleCloudPlatform/kubernetes/pull/10077
(https://app.shippable.com/builds/558376f415e8400d00004fe6)

I get the error:
```
{"id":1005,"message":"Internal API error : getPermissionByProjectId","methodName":"chkPermForId|_getSByProjectId"}
```

This looks like a permissions error (because I'm not a collaborator on the project?), but we would like the results to be public for anyone submitting PRs to the project.

@davidopp
@ixdy

**Comment by manishas** [comment]
@timstclair I've escalated this within the team. We'll address this soon.

**Comment by pquentin** [comment]
We get hit by this issue nearly every day too.

**Comment by avinci** [comment]
i think this should be fixed. It happens during Sync and we have cleaned that code up.

**Comment by pquentin** [comment]
@avinci Yes, it got fixed at some point. Thanks for cleaning things up!
