### ISSUE TITLE
Trigger action only if all matrix builds succeeded

### ISSUE THREAD

**Issue by rvrignaud** [Shippable/support#1592]
Hello,

I would like to be able to trigger an action only if all build from a matrix succeed. Is there a way to do that ?

Thanks,

**Comment by rvrignaud** [comment]
Hello,
Is there any news on this one ?

Regards,

**Comment by lekhab** [comment]
@rvrignaud: we don't have a trigger that supports this, unfortunately. There is an open feature request for this here: https://github.com/Shippable/support/issues/1493 (that also describes a few workarounds, but they are very use-case specific).

**Comment by manishas** [comment]
This is not currently possible, since we cannot support any action that would require artifacts from a matrix build since builds run on distributed infrastructure. Without artifacts, the usefulness of this would be very limited.

Closing.
