### ISSUE TITLE
Configure project only with shippable.yml file

### ISSUE THREAD

**Issue by rvrignaud** [Shippable/support#1593]
Hello,

Being able to configure CI in a file (shippable.yml) is a great feature and is one of reason why we choose shippable.
However Docker integration seems to be configurable only with WebUI. Is there any plan to support docker integration configuration directly in shippable.yml ?

Thanks,

**Comment by manishas** [comment]
@rvrignaud thanks for the feedback.

Our strategy right now is to put all the build config like package installs, etc in the yml and everything else in the UI. We will look into this experience again if we get more feedback along the same lines.

**Comment by pquentin** [comment]
Can we at least have an API for all settings that live only in the UI? At 42 projects and growing, it is very painful to update those settings by hand, especially given the very slow page loads.

**Comment by manishas** [comment]
@rvrignaud @pquentin we're actually in the process of revisiting this and working on an update that will return settings to the yml. More on the roadmap soon....

**Comment by rvrignaud** [comment]
Glad to hear that ! This will be a major improvement.
