### ISSUE TITLE
Using issue queue as support platform is not acceptable

### ISSUE THREAD

**Issue by alan-unravel** [Shippable/support#1596]
As a revenue generating product having an issue queue for a support mechanism is not tolerable and should be replaced with a more sustainable and usable tool such as Intercom.

**Comment by manishas** [comment]
@alan-unravel we are looking into alternate forms of support and also hiring in this area. Thanks for your feedback!

**Comment by manishas** [comment]
also, we'll soon set up an irc channel as well where customers will get more immediate help.
