### ISSUE TITLE
Build not found

### ISSUE THREAD

**Issue by JefAlive** [Shippable/support#1597]
I can't open my shippable build (https://app.shippable.com/builds/5589b3e6bd5b2a0c00e0ee3e), I received this message:

*{"id":1005,"message":"Internal API error : getPermissionByProjectId","methodName":"chkPermForId|_getSByProjectId"}*
**Build not found**

I'm receiving this message oftenly.

**Comment by manishas** [comment]
Looking into it...

**Comment by manishas** [comment]
@JefAlive quick question - how did you get the build link? Can you see the project on your org page in Shippable? Do you see build history for the project?

**Comment by JefAlive** [comment]
!(http://i.imgur.com/aUcIgie.png)[]

I got this link at GitHub.

**Comment by manishas** [comment]
Please make sure you have permissions to the repo on GitHub.

**Comment by manishas** [comment]
@JefAlive one more possibility - did you enable private repos on Shippable? By default we only ask for access to public repos... so if you want t see private repos, you'll need to enable access. 

Please check your account settings and make sure github private scopes are turned on.

**Comment by lekhab** [comment]
@JefAlive: Please let me know if the previous suggestion worked. I will close this for now. Please re-ope if you are still facing any issues.

**Comment by JefAlive** [comment]
At [Account Settings → GitHub Identity → Private] I set Private to On and Forced Sync. After a re-login everything got ok.
