### ISSUE TITLE
Route permissions not found error

### ISSUE THREAD

**Issue by dennissugar** [Shippable/support#1598]
I am getting the following error on our project settings page.

https://app.shippable.com/subscriptions/545ebd74c6f0803064f3d9fb/subscriptionsSettings

```json
{"id":9999,"message":"Route permissions not found","methodName":"getRoutePermission|_getRoutePermissions"}
```

**Comment by manishas** [comment]
I've logged an internal bug. thanks for reporting this.

**Comment by kkarski** [comment]
Same here:
{"id":9999,"message":"Route permissions not found","methodName":"getRoutePermission|_getRoutePermissions"}

**Comment by phagunbaya** [comment]
+1 #1607

**Comment by manishas** [comment]
This should now be resolved, so closing. Please do re-open if you run into this again. Thanks for your patience!
