### ISSUE TITLE
Cancelled build = success 

### ISSUE THREAD

**Issue by david-anyvan** [Shippable/support#1600]
At the moment if a build is started and then cancelled it is treated as a success and triggers after_success. It should be treated as an error or neither

**Comment by manishas** [comment]
@david-anyvan this could be a side effect of slow console log updates where you saw the updates late but the build was already successful. We're working on improving performance of console logs and we'll try to repro this at our end.

**Comment by jbowman1107** [comment]
I am seeing this as well. When we cancel a build, after_success is triggered.

**Comment by manishas** [comment]
we have completely redone our build platform and this will not happen any more. Closing.
