### ISSUE TITLE
Guage resource usage on shippable

### ISSUE THREAD

**Issue by bprashanth** [Shippable/support#1601]
There are times when I've observed what looks like high n/w latencies in my test logs (but could also be eg: cpu starvation of a goroutine pulling stuff off of the network). We run tests in parallel and sometimes things might get loaded. How does one figure out where the resource boundry is? 

I don't mean how many cores I'm supposed to get, I mean how much cpu etc my tests are *actually* using. If i was on a linux box I would use top/ps/sar etc to profile it. I suppose the promise of virtualization is that this should not be necessary, but do you export any time-series machine stats? 

I only want a way to increase the confidence that a flake that the logs say is because of high latency, correlates with spikes of machine stats. I've not had much luck reproducing these spikes locally on n1-standard-1 gce machines.

**Comment by manishas** [comment]
Closing.

**Comment by manishas** [comment]
To add on to that, we also show you memory and resource usage if you attach your own build machines. This is available in subscription settings.
