### ISSUE TITLE
getPermissionByProjectId error

### ISSUE THREAD

**Issue by dennissugar** [Shippable/support#1603]
My colleague is unable to access build results, either when linking from github or navigating from the main Shippable page.  He is getting the following error when accessing https://app.shippable.com/builds/558b5ec790e8910c00a12c57:

```json
{"id":1005,"message":"Internal API error : getPermissionByProjectId","methodName":"chkPermForId|_getSByProjectId"}
```
We have the same project permissions in github and I am able to view the build results fine. I verified that I have both private and public repos enabled, though as a side note, it doesn't look like I am able to change any repo settings after the UI change.

**Comment by manishas** [comment]
@dennissugar what is your colleague's github username? Does he have private permissions turned on in Shippable?

He can check that by going to account settings and checking to see that the github private repos icon is green.

**Comment by brymaven** [comment]
Hi @manishas, I was the one having problems with shippable. My private repo icon is green.
![screen shot 2015-06-26 at 11 16 13 am](https://cloud.githubusercontent.com/assets/3811764/8384272/ca25aac8-1bf4-11e5-89d3-9ccef7fe190d.png)

**Comment by manishas** [comment]
@brymaven can you try clicking on 'sync' in the account settings and see if that fixes the issue?

**Comment by brymaven** [comment]
It works now. Thanks @manishas.

**Comment by manishas** [comment]
Closing. Thanks!
