### ISSUE TITLE
Problem with refs after introducing new UI 

### ISSUE THREAD

**Issue by stafot** [Shippable/support#1604]
When i amend  in an existing commit and forcedly pushing it in my remote branch, shippable does not updates the refs. So I am unsure when re-running my build if it runs with the latest refs or not. This strange behavior starting after your UI updates. 

Thanks in advance for any answer.

**Comment by stafot** [comment]
It doesn't only happens on force push but also on new commit push. the PR build remains to the previous refs and does not get the latest.

**Comment by stafot** [comment]
I can ensure that is only UI problem. It takes the proper refs, but it does not updates the UI with the correct reference. So plz fix it cause it is confusing for your users. 

Thanks, again.

**Comment by lekhab** [comment]
@stafot: We believe this was happening due to queues getting backed up when we were upgrading to our new system. Please let me know if you are still seeing this and I will re-open.
