### ISSUE TITLE
timeout builds

### ISSUE THREAD

**Issue by zheiran** [Shippable/support#1605]
when some of my builds are started they keep in `Waiting for logs..` up to 20 minutes until i cancelled.

other 2 builds just keep a long time in `. /home/shippable/.nvm/nvm.sh && nvm install 0.10.31`, around 800.36 seconds, when it finished, the build appear as "timeout" and the changes are not visible, after Re-run the build it happens again, some hours later, the changes are visible but the last build still appearing as timeout

**Comment by manishas** [comment]
@zheiran we're looking into this. We recently had a sudden increase in number of builds and we're adding more build resources to handle this.

**Comment by manishas** [comment]
@zheiran I see all your latest builds haven't timed out. Please let me know if it happens again.
