### ISSUE TITLE
New Repo Not Building

### ISSUE THREAD

**Issue by tekram** [Shippable/support#1606]
If I try a new build on a branch from a repo that has other functioning branch it gives me the below error. 

{"id":3000,"message":"No access or object not found for :id 558cc62dba27100b00ebc303","methodName":"chkPermForId|_getBuildById"}

Reliability of Shippable service is making it challenging to try to actual use it.

**Comment by manishas** [comment]
@tekram are you using bitbucket? can you give me your username? Sorry about the issues you're seeing, we upgraded the service to a new release and there are still some issues we're ironing out.

**Comment by tekram** [comment]
Yes, it is a bitbucket account. User name is tashfeen. 

Thanks.

**Comment by manishas** [comment]
thanks. can you also point me to the project and branch you're trying to build?

**Comment by tekram** [comment]
Here is the link to the project: https://app.shippable.com/projects/558c950aedd7f2c0523cb609

There are three branches and I am unable to build any of them.

**Comment by manishas** [comment]
@tekram this could be due to an error in your yml. Can you please validate it here - http://yaml-online-parser.appspot.com/

Let me know if the yml is valid and we'll take a deeper look.

**Comment by tekram** [comment]
Thanks for that. That seems like the issue. So, if I ever get that similar type of error, yml file is that place to look?

**Comment by manishas** [comment]
yes, for now. we're improving the experience around this error so in a few days you should see a more obvious error.
