### ISSUE TITLE
Cannot access projects/builds on shippable UI

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#1607]
```
{"id":9999,"message":"Route permissions not found","methodName":"getRoutePermission|_getRoutePermissions"}
```

**Comment by manishas** [comment]
@phagunbaya is this still happening? We deployed a few fixes and that should have fixed the problem, so let us know.

**Comment by phagunbaya** [comment]
@manishas Seems to be resolved now. Thanks !

**Comment by buley** [comment]
This was happening to me today for a few hours. It just now cleared up "on it's own."
