### ISSUE TITLE
Build failing with no errors

### ISSUE THREAD

**Issue by lgfausak** [Shippable/support#1611]
All builds for this project are failing, but, the log shows everything worked.

https://app.shippable.com/builds/558d90ded7eacb0c00061098

I am new at this, maybe I have something set up wrong?

**Comment by manishas** [comment]
we're looking into this...

**Comment by lgfausak** [comment]
it looks like i didn't do the 'hub integration'.  I turned that on, and the build started to work.  I can reproduce this error if you want me to.

**Comment by manishas** [comment]
@lgfausak ah, i didn't look at your project settings.

Can you describe the scenario you were trying to achieve so we can repro it?

**Comment by lgfausak** [comment]
i will follow up over the werkend, best, -g

**Comment by lgfausak** [comment]
the scenario i was trying to accomplish:

i stumbled upon shippable, i think google uses it for kubernetes, so i
thought i would take a look.  I have a little project which creates a
google component in an image called tacodata/hyperkube.  I thought I would
use shippable to create that image for me.

It isn't obvious what to do.

Eventually I settled upon a post-ci build, and i tailored my shippable.yml
file to do a make followed by a copy to the shippable/buildoutput directory
which I then would use in my Dockerfile.  That part worked fine.
Everything was coming up green check marked, but, I got a failure
everytime.  That is what I reported to you and you said you would look into
it.

Eventually I tried 'Project Integrations' and selected my Docker Hub
account that I created and that made things work.

That is the confusing part.  In the top part of the form you ask for push
build (yes/no), push image to, push image tag.  I think it would make sense
to put the 'Project Integration' under this same section and call it 'Push
Image to (account)'.  That way the things that relate to each other would
be in the same section of the form.

You also have another 'Pull image name' right under the 3 prompts I listed
above.  But, this image has nothing to do with the 3 prompts!  It should
probably be in a different section.

Anyway, that's my opinion.  I understand it now.  I think you might benefit
from some user interface changes (no offense intended :-) ). For me, I
would like to see the entire spec in the .yml file, or maybe another .yml
file.  The only thing that really needs to be entered via gui on your site
would be credentials for accounts and whatnot.

Thank you very much for your time.  I am really starting to enjoy the
shippable product now that I understand it a little better.

-g


Sent from my iPhone

On Jun 26, 2015, at 9:14 PM, Manisha <notifications@github.com> wrote:

@lgfausak <https://github.com/lgfausak> ah, i didn't look at your project
settings.

Can you describe the scenario you were trying to achieve so we can repro it?

—
Reply to this email directly or view it on GitHub
<https://github.com/Shippable/support/issues/1611#issuecomment-115936817>.
