### ISSUE TITLE
How can I diagnose this build timeout?

### ISSUE THREAD

**Issue by shyela** [Shippable/support#1612]
Hi there,

This build (https://app.shippable.com/builds/558dc1536339ec0d0021ff2e) resulted in a timeout, but I can't figure out exactly why. The console log doesn't give a specific indication: there's no error at the end of the file and searching for "timeout" or "time out" shows nothing. Is it just the elapsed time (about an hour) or is there some other reason?

Are there any files or other details that you need to resolve my question?

Thanks!
Shy

**Comment by gegere** [comment]
+1

**Comment by manishas** [comment]
@shyela yes, builds time out after an hour.
