### ISSUE TITLE
Do any minions support docker now?

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#1614]
Are there any minions that either come with docker pre-installed within, or support the docker install process?

**Comment by manishas** [comment]
@rarkins can you tell us a little about the scenario you're trying to enable with Shippable? You can not pull your custom image from docker hub or google container registry and use that container for your CI. also, we can build your container from a Dockerfile and use that for CI as well. We can push docker images to image registries as well.

**Comment by rarkins** [comment]
@manishas I'm talking about "docker in docker" and using docker compose to provide backing services like Postgres and nginx etc

**Comment by rarkins** [comment]
I'm a little shocked if a company like yours built on docker doesn't see the need for customers to run containers too. Please tell me I've misunderstood!

**Comment by manishas** [comment]
@rarkins I corrected a typo in my previous comment. I wanted to say - 'you can now pull' - but the now was converted to not for some reason. 

As for running a multi- container application on Shippable, please check out Formations. That is our story for running your application in a real environment with backing services. I'd love to set up a call and show you a demo, I'll reach out over email.

**Comment by manishas** [comment]
You can also sign up for our webinar on Formations at https://attendee.gotowebinar.com/rt/8882154363785691649

**Comment by rarkins** [comment]
Thanks @manishas. We already have a cloud+container development environment so Formations is not for us. However we still need a way to test that and were expecting shippable to support customers who use docker for orchestration (not just single container testing). 

When you say:
> You can now pull your custom image from docker hub or google container registry and use that container for your CI. 

Do you mean we can build our own "custom minion" with docker included and test inside that instead? If so, can you point me to the latest/most accurate docs for that?

**Comment by manishas** [comment]
Formations give you orchestrated multi-container environments you can test against. Please let me know if you're interested in a call to discuss further. 

If you're super attached to running docker in docker with docker compose, we do not support that today. As you know, other CI platforms support running docker on their VMs so I can point you to a couple of those.

**Comment by manishas** [comment]
Just to add to the above, I want to stress that Formations exactly addresses your scenario of testing a multi-container application. I am not sure why you're saying 'it's not for us'. What is the difference between you using docker compose to spin up multiple docker containers in a docker container vs using formations to spin up multi container environments?

**Comment by rarkins** [comment]
Hi @manishas 

These are the main reasons why Formations isn't for us:

1. We can define the orchestration rules once and use docker-compose to set up containers in all environments - dev, test (an alternate CI/CD provider obviously), staging and production. Formations can't give us that "write once, use anywhere" approach so it's not something I'd want to use even if it didn't cost us anything more.

2. It's possible to run our 8 containers for dev inside a $5/month Digital Ocean VM (using Vagrant) so Formations @ $56/developer/month would mean an 11x increase in costs. Containers like nginx or logspout really use very few resources - 512MB containers are complete overkill (as is $7/month).
