### ISSUE TITLE
SyntaxError when activating Python 3.4 virtualenv

### ISSUE THREAD

**Issue by textbook** [Shippable/support#1615]
[This build](https://app.shippable.com/builds/558e80ca0db5cc0c00c44c7a) failed because the virtual environment couldn't be activated:

```
source /home/shippable/build_ve/python/3.4/bin/activate
File "<string>", line 1
import uuid; print str(uuid.uuid4())
^
SyntaxError: invalid syntax
File "<string>", line 1
import uuid; print str(uuid.uuid4())
^
SyntaxError: invalid syntax
```

It's not even getting far enough that I can imagine there's a problem in the [`shippable.yml` settings](https://bitbucket.org/jonrsharpe/dj_cv/src/2578c7a3469d9afdda3a8c326cc25ae6faa0c69b/shippable.yml?at=master), Python 3.4 is [listed as supported](http://docs.shippable.com/languages/#python) and re-running it made no difference. Any ideas?

**Comment by manishas** [comment]
I've logged a bug in our system, will provide status as soon as we know more.

**Comment by amcintosh** [comment]
Same issue. Exact same error, running with python 3.4

**Comment by manishas** [comment]
This should be fixed now. Please let me know if it works.

**Comment by amcintosh** [comment]
Looks good! Thanks!

**Comment by manishas** [comment]
Thanks! Closing.

**Comment by textbook** [comment]
All working from here, too; thank you for the prompt response!
