### ISSUE TITLE
Container Caching

### ISSUE THREAD

**Issue by coleca** [Shippable/support#1617]
The container caching switch on the project settings page seems to have disappeared.  I had set it to "On" but after reading this article: http://docs.shippable.com/docker_registries/ I want to turn it "Off" since I'm using Google Container Registry, but the setting is now gone.  Adding a [reset_minion] into every commit message isn't a good solution to this.

**Comment by manishas** [comment]
@coleca container caching is not available if you're using Dockerbuild functionality, which is why you do not see that option. Your container is being built each time.
