### ISSUE TITLE
Any failure in script will not run after_script if the working directory is changed

### ISSUE THREAD

**Issue by tanin47** [Shippable/support#1618]
Please see: https://app.shippable.com/builds/558f4c03e3b3480d00d90d3f

I have this part:

```
script:
  - cd test
  - errgergerherhhr
```

It produces an error `/home/shippable/cab1dd50-c254-4655-99c5-3ef22e6408d5.sh: line 90: errgergerherhhr: command not found`

The `after_script` is never run.

Is this an expected behaviour?

---------

Ok, I have run a small test on this. It is because I change the working directory to somewhere else. I'm not sure why though.

--------

I've found a workaround:

```
script:
  - (cd test/ && exec some_program_that_errors)
```

In this way, the `after_script` is run properly.

The other combination won't run `after_script`, for example, `(cd test/ && some_program_that_errors)`.

Please let me know if you cannot reproduce it.

**Comment by DavidGDragon** [comment]
I was not able to repro this issue, I used the following code in shippable.yml to create a directory, move into it, generate an error, and check if after_script ran. After script ran in all cases.
```
script:
  - echo $PWD
  - mkdir aaa
  - cd aaa
  - echo $PWD
  - qqqqqqqqqqqqqqqqqqqqqqqqqq

after_script:
  - echo "after_script"
```

**Comment by manishas** [comment]
Closing this issue since we couldn't repro it.

Also we have upgraded our build system recently and the yml format has changed.

**Comment by tanin47** [comment]
Cool, thanks!
