### ISSUE TITLE
Inconsistent Starting of MongodDB?

### ISSUE THREAD

**Issue by tekram** [Shippable/support#1619]
There seems to be some inconsistency between builds of the same commit. After I re run it, it will sometimes pass and others fail. It seems to be around starting/connecting to the mongodb service. 

Here is one example:
This one succeeded https://app.shippable.com/builds/558f5d76b0a2d60c00e55150
This one failed https://app.shippable.com/builds/558f5cc726d2a30b00f52c08

Here is another commit the first passed and the later two failed. All are form the same commit just re-run. 
https://app.shippable.com/builds/558f62ad0422360d00fdfa2c
https://app.shippable.com/builds/558f63b4e3b3480d00d96e0d
https://app.shippable.com/builds/558f61beec90ac0c00f62e9e

Thanks.

**Comment by manishas** [comment]
i've logged an internal bug, we'll take a look and let you know what's going on..

**Comment by tekram** [comment]
Thanks for the fast response.

**Comment by avinci** [comment]
@tekram, I see that you are installing redis and mongo. In our internal images, these services could take up to 20 seconds to start. 

Are you checking to see if these services have come up before running the tests? Second, you could just blindly sleep for 20 seconds before executing the test scripts also. 

Can you try that and let me know if that solves your problem..

**Comment by tekram** [comment]
I was not checking to see if the services start. 

I have switched the install order by installing MongoDB first and then Redis. Perhaps, that gives enough time for MongoDB to come up? 

So, far it seems to be doing fine. Do you have any internal images that have these services already installed?

Thanks for your help.

**Comment by manishas** [comment]
I am closing this issue, please re-open if you run into this again.
