### ISSUE TITLE
Push tag to docker hub fails

### ISSUE THREAD

**Issue by jazmit** [Shippable/support#1620]
Using the build number or commit sha as a tag causes the build to fail with 'Tag does not exist':
````
sudo docker push schoolshape/web:master.63 2>/tmp/push-error.txt
The push refers to a repository [schoolshape/web] (len: 1)
sudo: unable to resolve host ip-20-0-100-153
time="2015-06-28T15:21:04Z" level=fatal msg="Error pushing to registry: Tag does not exist: master.63"
````
Reference to a failed build: https://app.shippable.com/builds/55901014cf4aed0c003f8bfe

The push works fine when I specify an existing tag such as 'latest'.

**Comment by manishas** [comment]
This has been fixed with the revamped build platform. closing.
