### ISSUE TITLE
Add a new project with startup plan

### ISSUE THREAD

**Issue by xherriot** [Shippable/support#1621]
Hello,

We are with the old plan (12$ / year).
We currently have 3 projects and we would like to add a new one but on the projects page the "+" doesn't appear.

It seems me the startup plan does not limit the number of projects, am I wrong ?

Thanks.

**Comment by manishas** [comment]
No there's no limit to number of projects in any plan. The button was removed by mistake a few hours ago and we'll add it back in very soon. Sorry about this!

**Comment by xherriot** [comment]
Ok, thanks !
