### ISSUE TITLE
Bower install failing

### ISSUE THREAD

**Issue by lucmig** [Shippable/support#1622]
Hi,
My yml that was working before now fails with "EACCES EACCES, permission denied '/home/shippable/.cache/bower'" when trying to do "bower install".

I have tried "bower --allow-root install", have tried installing "npm install -g bower" with and without sudo, and so far nothing worked.

Need some guidance, please.

**Comment by manishas** [comment]
@lucmig can you point me to a failed build link?

**Comment by lucmig** [comment]
hi manishas,

i unfortunately deleted all the failed builds after downloading the logs, been waiting for one to complete but they seem to have gotten stuck! maybe you would advise me about that too? what info do you need me to provide on a build for you to be able to investigate?

**Comment by lekhab** [comment]
@lucmig: can you please send me your yml?

**Comment by lekhab** [comment]
@lucmig: is this still an issue?

I tried doing this in a sample (https://github.com/shippableSamples/sample-bower/) and I was able to install bower successfully.  Please let me know if this is still an open issue for you.

**Comment by lekhab** [comment]
please let me know if you would like us to look into this further. closing the issue.
