### ISSUE TITLE
SSH key and not reachable repository

### ISSUE THREAD

**Issue by stekycz** [Shippable/support#1623]
Hi,

I have had to revoke access to my account on GitHub recently a reconnect it again. However since that time all build in our organization are failing. For example https://app.shippable.com/builds/559106d45e65d40c00015c32

I have tried to use the SSH key in organization settings (on Shippable) for my GitHub account however the GitHub shows me the message that the key is already in use.

I have also wanted to deny access to private repos and renew it but it is not possible on Shippable.

What can I do to fix it?

Thank you!

**Comment by pilec** [comment]
As a hotfix, please can you regenerate Deployment key for that project? We love to use shippable CI more, but this is really flustrating.

**Comment by pilec** [comment]
Guys? 35 hours without any action? Its blocker issue for us.

**Comment by manishas** [comment]
Sorry we had production service issues yesterday and that took up all our bandwidth. I'm following up on this now.

**Comment by manishas** [comment]
we are adding a way to reset your project and that should address this issue. ETA for a fix is less than 24 hours.

**Comment by pilec** [comment]
Thank you @manishas !

**Comment by manishas** [comment]
This is now available in project settings tab -

![screen shot 2015-07-01 at 10 36 24 am](https://cloud.githubusercontent.com/assets/2983749/8460888/3812ce76-1fdd-11e5-95d8-8e2dfb153eda.png)

**Comment by manishas** [comment]
Please let me know if this works for you.

**Comment by pilec** [comment]
It works! Thanks a lot.

**Comment by manishas** [comment]
Glad it worked! Closing this issue :)
