### ISSUE TITLE
Builds are suddenly breaking due to `dropdb` error

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#1625]
Builds that have been working just fine are all of a sudden breaking because the version of `dropdb` does not recognize an argument that is supported.  Did the postgres version that is on the defaul image change?

![shippable___hosted_continuous_integration_service](https://cloud.githubusercontent.com/assets/286588/8417035/a894fe9c-1e5e-11e5-98be-863577dea0ea.png)

Build: https://app.shippable.com/builds/55919b5cd3efa70c00b15f20

**Comment by manishas** [comment]
@jeffkole is this still happening? I see your recent builds seem fine, but the specific branch for this build was deleted.

**Comment by jeffkole** [comment]
Builds are back to normal.  Any idea what may have caused this?

**Comment by lekhab** [comment]
@jeffkole: We are in the process of migrating over to a new orchestration layer. This error occurred while you were on the new system. We have since reverted back to our old system, while we iron out these  issues. Hope that explains the hiccup and the return back to normalcy.

**Comment by lekhab** [comment]
@jeffkole: can you please send me your yml  to help us debug this issue further? you can either paste it here or send it to me at lekha@shippable.com.

**Comment by manishas** [comment]
I am going to close this issue since builds are back to normal. Thanks!
