### ISSUE TITLE
Maven builds all fail; was working 11 days ago...; seems like timeout issue ?

### ISSUE THREAD

**Issue by aschwabe** [Shippable/support#1626]
I have the startup paid account.  Minimal project code changes since last successful build (11 days ago), but builds now fail every time.  I've tried making several changes to shippable.yml in hopes of resolving the issue.  No success.

When a failed build happened before (11+ days ago), I used to see a red x in the log and could see where the build failed and the appropriate console messages.  Now, I see all green check marks.  Seems to be failing on my maven test or build, unpredictably before the comman completes.  There are no visible error messages, and the logs shows all green check marks, but the build is always marked as failed, and it never gets to my actual package, build, push.

**It looks like a timeout is occurring** because log output just stops mid-process.  Somtimes during mvn test, sometimes during apt-get install maven, but I am not seeing any error messages.

What I have tried so far:

1. removed some "optional" steps and packages in shippable.yml >> still fails
2. switched to a different ubuntu image >> still fails
3. moved some commands around to before_script, before_install, hoping timeouts would be different >> still fails
4. skip tests altogether >> still fails.
5. tried enabling caching on the container >> still fails
6. added shippable_retry ahead of apt-get commands and build commands >> still fails

I'm at a loss.  Of course code isn't committed unless it compiles locally.  No idea why the shippable build is failing, and have no more ideas on what to try based on the log files.

Build logs:
https://app.shippable.com/builds/55919f3e27d2aa0c0089c8ca
https://app.shippable.com/builds/55919cf427d2aa0c0089a6d9
https://app.shippable.com/builds/559195072d7d470b008e6931

It could totally be a problem with my shippable.yml, but that didn't seem logical to me since it was working famously before.

Kind of freaking out now about a deadline.  It worked great before and not much changed, but I can't get a build to pass so I can do 2nd level testing...

Account is andrew_schwabe
my direct email is aschwabe (at) gmail (dot) com

**Comment by manishas** [comment]
@aschwabe can you share your shippable.yml?

**Comment by aschwabe** [comment]
Just emailed it to you, didn't want to publish it online, and wanted you to see it 100% as is

**Comment by aschwabe** [comment]
btw, the maven install line is commented out, obviously that will cause a problem.  just another "thing i tried" in case mvn was already configured (its not!).

all previous build fails used variations of apt-get install maven before trying to mvn test and mvn package.

It usually gets past the apt-get install, and usually fails on mvn test or mvn package

**Comment by aschwabe** [comment]
It appears that this was all caused by yesterday's performance issue with the new container orchestration layer.  Everything seems to be running along fine now.
