### ISSUE TITLE
Builds stuck on "Waiting for logs....."

### ISSUE THREAD

**Issue by soby** [Shippable/support#1627]
I've tried to get a build working by canceling, restarting, closing/opening the PR, etc. Nothing seems to work and it's get's stuck in the "waiting" status with this message.

https://app.shippable.com/builds/5591a81b27d2aa0c008a48ca

**Comment by soby** [comment]
I also get a lot of these messages when interacting with builds, restarting, and trying to get them to run:

{"id":3000,"message":"No access or object not found for :id 5591aa8c2d7d470b008fa1c7","methodName":"chkPermForId|_getBuildById"}

**Comment by davidthewatson** [comment]
I'm having the same problem with this build:

https://app.shippable.com/builds/5591aaad55c27a0d00ef6b7d

Started happening a few hours ago. I've since re-run the build and it gets stuck at "waiting" status still.

**Comment by caarlos0** [comment]
Same problem here...

**Comment by manishas** [comment]
We're working to resolve this... will post an update with an explanation soon.

![screen shot 2015-06-29 at 2 06 25 pm](https://cloud.githubusercontent.com/assets/2983749/8418442/0f452b36-1e68-11e5-9b29-e73f3f0cd05b.png)

**Comment by caarlos0** [comment]
@manishas it would be nice to have a http://status.shippable.com/ like http://status.github.com/ , for example...

**Comment by manishas** [comment]
Builds should be back to normal now.

We moved to a new orchestration layer that held up as we moved some users to it every day but hit scale issues today and we had to revert everyone back to the old system.

Let me know if you're still seeing delays. Sorry for the service interruption today.

**Comment by asgeo1** [comment]
@manishas - I've just started getting "Waiting for logs..." errors today:

https://app.shippable.com/builds/55bee1c38798a00b0099f963

**Comment by makiolo** [comment]
Same here "Waiting for logs...":
https://app.shippable.com/builds/55f749025907ab0b00f8fc93

Thanks.
