### ISSUE TITLE
Timeout and very long build time 

### ISSUE THREAD

**Issue by Gateway85** [Shippable/support#1628]
We are seeing really long build times (1 hour and above) and timeout in shippable for project that build within 15 min a couple of days ago. 

![screen shot 2015-06-30 at 13 14 38](https://cloud.githubusercontent.com/assets/9881114/8424248/305851be-1f2a-11e5-83fc-0ec0f032f179.png)

![screen shot 2015-06-30 at 13 13 49](https://cloud.githubusercontent.com/assets/9881114/8424252/38cea974-1f2a-11e5-9764-a644ac66200b.png)

**Comment by Gateway85** [comment]
it's getting worse to a point where my developers are totally blocked. 
![screen shot 2015-06-30 at 21 22 31](https://cloud.githubusercontent.com/assets/9881114/8431766/3d77645e-1f6e-11e5-840a-e8e7847a8ee8.png)

**Comment by avinci** [comment]
Looking into it....with get back in a bit. Just saw you fired another build. Let me see if this persists..

**Comment by avinci** [comment]
I have upgraded your account for a month, so that it doesn't get locked up. I am monitoring this in the meantime. I apologize very much for your inconvenience and will keep you posted when we find the root cause...

**Comment by Gateway85** [comment]
Thanks for the fast reaction. It is working for now. We will come back, should we encounter issues again. Would be great to get to know the root cause, though.

**Comment by avinci** [comment]
root cause of the issue is that we upgraded our orchestration engine and it doesn't seem to handle the load. as a result our main build watcher is dying and hence we were losing handle of the builds. 

We have reverted aback to old system and stressing the new orchestration before we upgrade again...

Hope this helps...

**Comment by Gateway85** [comment]
thanks for the info 
good luck with the next try :)
