### ISSUE TITLE
Clicking github link for failed build logs me into shippable but not the build in question

### ISSUE THREAD

**Issue by thockin** [Shippable/support#1629]
Clicking the link a second time works better.

**Comment by manishas** [comment]
I cannot seem to repro this. Can you point me to a specific link i.e. Was this a link in a build status email or the 'details' link on pull request page, etc.

**Comment by thockin** [comment]
Any time I have been away from shippable "too long", this happens.

Offer a PR, shippable runs, fails, and status is red.  Clicking that link
on the PR page takes me to a build-specific URL, which gets rewritten to
lose the build number.  Zgoing bsck and clicking that link again takes me
to the right place.  I assume it has something to do with an auth timeout.

**Comment by manishas** [comment]
this should be fixed after our build system upgrade. CLosing.
