### ISSUE TITLE
Deployment works but always shows as Timeout

### ISSUE THREAD

**Issue by dunicaboy** [Shippable/support#1630]
I have a GAE Maven deployment which seems to deploy correctly.
However, the console always shows it as 'Timeout' 

The logs finish with the following;

  Update for module default completed successfully.

    Success.

    Cleaning up temporary files for module default...

    [INFO] ------------------------------------------------------------------------

    [INFO] BUILD SUCCESS

    [INFO] ------------------------------------------------------------------------

    [INFO] Total time: 45:05 min

    [INFO] Finished at: 2015-06-29T07:59:40+00:00

    [INFO] Final Memory: 36M/1621M

    [INFO] ------------------------------------------------------------------------

after_script

copy_archives

exec_echo

  echo 'skipping archive upload...'

    skipping archive upload...

after_archive

**Comment by manishas** [comment]
@dunicaboy this should be fixed now. Sorry about that... we were moving to a new orchestration layer and unearthed many issues at scale so fought with that all day yesterday. We've now reverted back to the original platform and we'll make sure all issues with the new layer are resolved.

**Comment by dunicaboy** [comment]
Thanks that's a great help

**Comment by manishas** [comment]
Closing.

**Comment by dunicaboy** [comment]
Hi Manisha,

I'm getting the same timeout problem with my GAE project deployment on
shippable.
You fixed it via reversion last time.

Thanks
Denis
