### ISSUE TITLE
Timeout Issues and Build Failing

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1631]
Hi,

I am facing timeout issues with my builds which were working pretty good recently. Such builds fail after certain time period.

The url to build is https://app.shippable.com/builds/5592674827d2aa0c00939c8b

Thanks,

**Comment by manishas** [comment]
@naveensky can you please try triggering a new build? This should be fixed now.

**Comment by xherriot** [comment]
I think there still is a issue, more than a hour to build & send to docker my image:
https://app.shippable.com/builds/5592b0c0ae8dc80c009d4975

A re-build is currently running (same commit than before), it blocks a long time at the step "upload artifacts":
https://app.shippable.com/builds/5592e8c627c8c80b00b1031d

**Comment by naveensky** [comment]
@manishas - They are looking good now. Thanks for the help
