### ISSUE TITLE
Different tags per branch

### ISSUE THREAD

**Issue by marcospedreiro** [Shippable/support#1632]
Is it possible to have shippable push an image with a different tag based on the branch, or push an image with two tags, the default and a custom tag?  

For example, I want to have my master branch push with the tag ```devlatest``` and another branch test push with the tag ```testlatest```.

**Comment by manishas** [comment]
This is a good scenario and it's on our radar. I've tagged it as a feature request and will let you know when we have an update.

**Comment by phagunbaya** [comment]
Any estimate for the release date ?

**Comment by rvdwijngaard** [comment]
I really need this too

**Comment by phagunbaya** [comment]
@manishas : Is there any page/docs where we can see the upcoming features in timely manner ? It will be helpful for everyone of your customers/users to plan their dev and expectations.

**Comment by manishas** [comment]
All docker tag requests are being tracked in #824 since that will give us a consolidated view of what customers want to see in this area. 

Closing this issue as a DUP.
