### ISSUE TITLE
No access or object not found for :id

### ISSUE THREAD

**Issue by kkarski** [Shippable/support#1638]
Just added a new project to build from BitBucket and tried building a branch for the first time and got this error:

{"id":3000,"message":"No access or object not found for :id 559578f5c5db3c0c00e68156","methodName":"chkPermForId|_getBuildById"}

**Comment by manishas** [comment]
@kkarski what is the username you sign into shippable with?

**Comment by manishas** [comment]
also can you point me to the org/project name you tried to enable?

**Comment by kkarski** [comment]
Appcrossings.

Just try building any of the empty projects

**Comment by kkarski** [comment]
Still facing this issue:

{"id":3000,"message":"No access or object not found for :id 559d9568c6edff0b008f20d7","methodName":"chkPermForId|_getBuildById"}

**Comment by lekhab** [comment]
@kkarski: can you please share you yml? you can mail me at lekha@shippable.com

**Comment by lekhab** [comment]
build issue resolved via email.

@kkarski: Please let me know if there is anything further I can help you with.

**Comment by lekhab** [comment]
@kkarski - you should now be able to build the correct branch from the subscriptions page. closing this issue.
