### ISSUE TITLE
404 Not Found Fetching deb file in ubuntu Image.

### ISSUE THREAD

**Issue by salazarguille** [Shippable/support#1639]
Hello,

When my project run I get this error:

Get:108 http://archive.ubuntu.com/ubuntu/ trusty/main libsaxon-java all 1:6.5.5-10 [1,075 kB]
Get:109 http://archive.ubuntu.com/ubuntu/ trusty/universe libwagon2-java all 2.5-1 [1,278 kB]
Get:110 http://archive.ubuntu.com/ubuntu/ trusty/main libxom-java all 1.2.10-1 [170 kB]
Get:111 http://archive.ubuntu.com/ubuntu/ trusty/universe maven all 3.0.5-1 [1,303 kB]
Get:112 http://archive.ubuntu.com/ubuntu/ trusty/main rhino all 1.7R4-2 [14.4 kB]
Get:113 http://archive.ubuntu.com/ubuntu/ trusty/universe testng all 6.8.7-2 [767 kB]
Err http://archive.ubuntu.com/ubuntu/ trusty-security/main libservlet3.0-java all 7.0.52-1ubuntu0.1
404 Not Found [IP: 91.189.91.15 80]
Fetched 61.9 MB in 4s (13.0 MB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/t/tomcat7/libservlet3.0-java_7.0.52-1ubuntu0.1_all.deb 404 Not Found [IP: 91.189.91.15 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

The project was building fine, but now I get this error.

**Comment by salazarguille** [comment]
The image used is shipimg/ubuntu1404_java and shipimg/ubuntu1204_java

**Comment by manishas** [comment]
@salazarguille can you share your yml file?

Did you try the suggested fixes like running apt-get update before the install command or trying the install command with --fix--missing?

**Comment by salazarguille** [comment]
Yes, I can share my yml.

It is

language: java

jdk:
  - oraclejdk7

runtime:
  - maven

before_install:
  - apt-get install -y maven

script:
  - cd odra-mms
  - mvn clean compile

after_success:  
   - mvn clean cobertura:cobertura -P test
   - mvn test -P test


I have:
before_install:
  - apt-get install -y maven

I think it is ok (because it always worked fine).

**Comment by salazarguille** [comment]
Hi I fixed it.

I added a apt-get update command in before_install sentence:

before_install:
  - apt-get update
  - apt-get install -y maven

And it worked fine!

I didn't understand why I had to add this sentenc, if it was working fine.

Thank you very much
Regards
Guillermo

**Comment by salazarguille** [comment]
I resolved this issue adding

before_install:
apt-get update
apt-get install -y maven
