### ISSUE TITLE
Some PR Commits are being ignored

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1640]
Examples:

- https://github.com/ContaAzul/ContaAzul/pull/8063
- https://github.com/ContaAzul/ContaAzul/pull/8066

The last commit of each of them is not being built and they don't appear in the "Pull Requests" view...

**Comment by caarlos0** [comment]
One more:

- https://github.com/ContaAzul/ContaAzul/pull/8086 (commit https://github.com/randalmaia/ContaAzul/commit/10c4043ef138ce242108bf81a5793a568b071b05)

**Comment by caarlos0** [comment]
We see this bug very often here, at least one PR/day...

**Comment by Xmio** [comment]
One more:
https://github.com/Xmio/ContaAzul/commit/cec033df9ce553a9ee4228c52acc41a0d158e2e7

**Comment by caarlos0** [comment]
@manishas can you take a look at this one?

**Comment by manishas** [comment]
We'll look into this and get back to you..

**Comment by caarlos0** [comment]
Thanks @manishas... It happens almost every day... let me know if I can help with anything...

**Comment by celinoaraujo** [comment]
@manishas Can you take a look? Commits ignored...

https://github.com/ContaAzul/ContaAzul/pull/8236
https://github.com/ContaAzul/ContaAzul/pull/8237

**Comment by manishas** [comment]
@caarlos0 @celinoaraujo we're tracking this issue at our end and figuring out the best way to fix this. I'll update you soon.

**Comment by caarlos0** [comment]
@manishas one more build not running: https://github.com/ContaAzul/ContaAzul/pull/9806

**Comment by hcarine** [comment]
@manishas Commits ignored: ContaAzul/ContaAzul/pull/9885

**Comment by randalmaia** [comment]
@manishas one more https://github.com/ContaAzul/ContaAzul/pull/9891

**Comment by manishas** [comment]
@randalmaia @hcarine i cannot see the PR page since I'm not a member of ContaAzul... can you send me a screenshot of the PR page at manisha@shippable.com?

**Comment by manishas** [comment]
Actually, I do see a build for PR 9891... build id is 562683b0265d0d0d00ae98dd and for PR 9885 - 56267942031de20d0034e65e

Can you please double check?

**Comment by randalmaia** [comment]
@manishas  562683b0265d0d0d00ae98dd is the previous commit.

Look this
![screenshot from 2015-10-20 17 06 41](https://cloud.githubusercontent.com/assets/2751058/10618162/1c36c870-774d-11e5-9e15-28d6b1eb073b.png)

**Comment by avinci** [comment]
@randalmaia We are starting to surface all the issues where we don't create builds. Is this happening today?

**Comment by hcarine** [comment]
@manishas only the last commit was not ignored

look!
![screenshot from 2015-10-20 17 07 20](https://cloud.githubusercontent.com/assets/10616827/10618230/8e454b8a-774d-11e5-83f2-45f20e9d4522.png)

**Comment by randalmaia** [comment]
@avinci This is happening now!

**Comment by caarlos0** [comment]
@avinci happening again

**Comment by manishas** [comment]
@caarlos0 @randalmaia can someone from ContaAzul please contact us at manisha@shippable.com? We sent some communication about dedicated hosts but haven't been successful in reaching anyone yet.

**Comment by caarlos0** [comment]
@manishas we are aware, I'm traveling right now, probably @luizm will take a look into this. Can you help him?

**Comment by manishas** [comment]
yes, that should be ok. I'll follow up with him.... thanks!!

**Comment by caarlos0** [comment]
@manishas thanks!

**Comment by avinci** [comment]
We have significantly hardened our web hook processing listener. Are you still seeing issues with web hooks being ignored?

**Comment by caarlos0** [comment]
@Xmio @hcarine @randalmaia ?

**Comment by manishas** [comment]
This is an old issue and should not be seen with our revamped build platform. CLosing.
