### ISSUE TITLE
Cannot trigger any manual builds from the web

### ISSUE THREAD

**Issue by JADurham909** [Shippable/support#1642]
I cannot seem to trigger builds for any projects.  I just get a server 500 error back on:

https://api.shippable.com/workflow/triggerBuild

This was working fine for most of the day.

<img width="1440" alt="screen shot 2015-07-02 at 9 01 12 pm" src="https://cloud.githubusercontent.com/assets/574966/8490832/8b9d0504-20fd-11e5-8464-a15038a945fa.png">

**Comment by JADurham909** [comment]
I am using BitBucket.

**Comment by Enalmada** [comment]
+1.   Shippable with BitBucket appears to be down.

**Comment by EHLOVader** [comment]
+1 down for me too. Not just manual builds but also the webhook requests. :-1:

**Comment by manishas** [comment]
Thanks for reporting this. I'm escalating this issue...

**Comment by manishas** [comment]
Should be fixed now. Let us know.

**Comment by EHLOVader** [comment]
Confirmed it is seeing pushes from BitBucket for me. :+1:

**Comment by JADurham909** [comment]
Awesome, it is fine now. :+1:
