### ISSUE TITLE
New BitBucket Web Hooks

### ISSUE THREAD

**Issue by EHLOVader** [Shippable/support#1643]
While looking for causes to #1642 on Bitbuckets end I noticed they recently updated the webhooks.

I know the webhook is added through the API  (at least that is how I remember it happening) but is there anything in the new webhooks which would benefit the process? 

Anyway I thought I would notify in case it helped.

__Documentation for new webhooks__
https://confluence.atlassian.com/display/BITBUCKET/Manage+Webhooks;jsessionid=08DF3E6B619EC3A9815170E2C470BE26.node3
__Blog Post for new webhooks__
https://blog.bitbucket.org/2015/06/24/the-new-bitbucket-webhooks/

**Comment by pquentin** [comment]
Using the new Bitbucket web hooks is the only way to not be affected by https://bitbucket.org/site/master/issues/7775/post-service-does-not-provide-useful. This is a serious bug, as you can see from the 300+ votes and 200+ issues.

Basically, when merging to a branch, the old Bitbucket POST service used by Shippable does not trigger a new build. As many other teams, we use git-flow, and releasing a new version means merging the release branch in develop and master. Those merge commits don't trigger a build, meaning we don't test our releases unless we trigger a build manually.

Allowing us to use the new Bitbucket web hooks would solve the issue. Thanks!

**Comment by Paikan** [comment]
+1

This is actually really annoying and a fix would be greatly appreciated

**Comment by vladdancer** [comment]
I agree with Paikan. This is a critical issue for us to get successful ci flow!
Any news on this?

**Comment by manishas** [comment]
@mbrodala thanks for updating this.... yes, we fixed this over 3 weeks ago. We're now using the new push webhooks.

Apologies for not updating this issue at our end.... our old support process duplicated these issues in an internal repository and we sometimes missed following up and updating the issues in support repo. To fix this process, our developers have started working directly off support issues and providing updates here as we pick up issues and make progress, which ensures full transparency as we work through the backlog. This will be apparent in any new issues created, and we intend to review all prior issues over the next few weeks and update them as required.

Again, thanks for your help!
