### ISSUE TITLE
Updated docker image not pulled

### ISSUE THREAD

**Issue by stekycz** [Shippable/support#1644]
Hi,

I have updated our docker image however it was not updated during following build (https://app.shippable.com/builds/5596b7d5ddb2810c00bf6941). What should I do to make it updated?

Thank you!

**Comment by manishas** [comment]
I've entered this as an issue in our internal system. Update as soon as we know more...

**Comment by manishas** [comment]
this is a bug on our side. we'll fix it soon and let you know.

**Comment by manishas** [comment]
Until this bug is fixed, we can remove your old image from our hosts so that builds pull your new image. Do you want us to do that? We will need your image name.

**Comment by stekycz** [comment]
It is possible however what about another change after that? We always find some new reason why our tests fails.

**Comment by manishas** [comment]
We're fixing the bug so if you change your image again it will be pulled. 

I wanted to unblock you for now by deleting the image from our hosts manually. Let me know if you want us to do that and if so, the image name.

**Comment by stekycz** [comment]
Thank you, the image name is `stekycz/shippable`

**Comment by pilec** [comment]
Can you give me an update pls? This is completely blocker for one of our repo.

**Comment by pilec** [comment]
Can you give me an update pls? This is completely blocker for one of our repo.

**Comment by pilec** [comment]
Can you give me an update pls? This is completely blocker for one of our repo.

**Comment by manishas** [comment]
We've prioritized this super high and we're aiming to get this done in the next 2-3 days. 

In the meantime, we can manually remove your old image from our hosts so the next build can pick up the new images. That should unblock you. Can you send me your repo and image name and we'll remove it manually. You can send me an email at manisha@shippable.com with your image name if you don't feel comfortable sharing it here. 

Thanks!

**Comment by pilec** [comment]
Hi there, image is already in this comment: https://github.com/Shippable/support/issues/1644#issuecomment-119488077 feel free to delete it.

**Comment by pilec** [comment]
Hello, here is still this issue without manually removing, can you please fix this or manually remove dock as soon as possible? Thank you!

**Comment by manishas** [comment]
The image has been manually removed. Please let me know if it works. Thanks!

**Comment by pilec** [comment]
unfortunately it doesn`t work: more information - https://app.shippable.com/builds/55a6848bc85dde0c0069c6d0

**Comment by ragsden** [comment]
@pilec : I looked at the build and I found that you are using caching turned on and hence builds are not pulling the latest image. For you to pull the latest image, you will have to reset your cache and this can be done by adding [reset minion] tag in the commit message. This will invalidate the cache, pull the latest image. You can find more info here http://shippable-docs-20.readthedocs.org/en/latest/config.html

**Comment by lekhab** [comment]
@pilec: please let us know if the resolution does not work for you and we will re-open.

**Comment by pilec** [comment]
Thank you, it works for us.
