### ISSUE TITLE
Internal Server Error in Build (new project) / Rerun Build

### ISSUE THREAD

**Issue by salazarguille** [Shippable/support#1646]
Hello,

I am try to build a old project (it was working ok), and creating a new project and I get an internal server error message.

![shippable_errorjpg](https://cloud.githubusercontent.com/assets/5948309/8512712/22dc92c0-2326-11e5-851c-5a23cd71d1e0.JPG)

**Comment by claar** [comment]
I'm having the same problem with my existing project -- can't rebuild.

**Comment by esenti** [comment]
Same issue here, the request to `https://api.shippable.com/workflow/triggerBuild` returns `500` with `Internal Server Error` in the request body.

**Comment by manishas** [comment]
Can you please try again? It should work now.

**Comment by salazarguille** [comment]
I tried it again two minutes ago, and I got the same error. (I logout/login).

**Comment by manishas** [comment]
Actually, hold on. We're looking into it.

**Comment by manishas** [comment]
It should work now. Can you please let me know? 

Thanks for your patience!!

**Comment by salazarguille** [comment]
Yes, Manishas. It worked for me! Thank you very much!.
do I close this issue?

**Comment by manishas** [comment]
Yes, please close it :)

**Comment by salazarguille** [comment]
It worked for me. I could build/rebuild projects.
