### ISSUE TITLE
unable to locating deployment keys in dashboard

### ISSUE THREAD

**Issue by gaumire** [Shippable/support#1647]
Hi,

The interface seems to be changing so often that I now do not see the 'deployment keys'  panel in settings, also the subscription panel is not readily accessible. I remember creating one and using a project key for a repo in github. But while trying to get the other key for heroku integration I am not being able to locate it again. Followed @rageshkrishna's blog on deployment keys [here](http://www.rageshkrishna.com/blog/demystifying-shippable-s-deployment-keys) but that did not help, seems the interface has moved on from when he wrote the writeup.

Also, when working as a collaborator on a project, would I have to use the owner's deployment keys or should I use my own? 

Thanks

**Comment by armicron** [comment]
hi, maybe it will help #1555
http://blog.shippable.com/continuous-nodejs-deployment-to-digitalocean

**Comment by gaumire** [comment]
@armicron thanks, that seems to be it.
