### ISSUE TITLE
MongoDB configuration?

### ISSUE THREAD

**Issue by RobertHerhold** [Shippable/support#1650]
Hi,

Typically when you run a MongoDB database from the shell, you can specify a configuration file by using [`mongod --config <config file>`](http://docs.mongodb.org/manual/reference/configuration-options/). Is there any way to achieve this in the `shippable.yml` file where you specify mongodb as a service?

**Comment by ric03uec** [comment]
@RobertHerhold can you try doing the following:
- do not put mongodb in the service section
- start mongodb in `before_install` section like `mongod --config <custom_config> &`

The config file can be generated dynamically (echo "some config" >> mongo.config) before booting mongo server or it can be a part of your repo. 

hope this helps

**Comment by RobertHerhold** [comment]
Thanks!
