### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by cemo** [Shippable/support#1652]
1. After permitting to private repositories I had to click refresh button in UI. This is horrible because I lost a couple minutes to figure out why my private repos could not be displayed.

2. The red error message is displayed on main menu. This is pretty bad because I thought that there was a system error. I could not find add project button anywhere in UI.

**Comment by avinci** [comment]
@DavidGDragon can you look into this...

**Comment by manishas** [comment]
this should be fixed after the build system upgrade. closing.
