### ISSUE TITLE
Network issue ?

### ISSUE THREAD

**Issue by xherriot** [Shippable/support#1653]
Hello,

• Since we use Shippable, we have some errors and when we re-launch these builds, it works:
<img width="1150" alt="screen shot 2015-07-07 at 09 34 53" src="https://cloud.githubusercontent.com/assets/5094797/8541063/85283784-248b-11e5-9a90-f569e8be0486.png">
<img width="683" alt="screen shot 2015-07-07 at 09 25 49" src="https://cloud.githubusercontent.com/assets/5094797/8541068/8914f6fc-248b-11e5-8772-1a5d0c06351b.png">
<img width="303" alt="screen shot 2015-07-07 at 09 27 29" src="https://cloud.githubusercontent.com/assets/5094797/8541065/86fa961a-248b-11e5-814f-3e15461f5529.png">

• Your UI takes a while to load (~15 seconds on the project page).

• Until "after script", the process takes ~15/20 minutes, it's ok, but then it takes more an hour to finish the build (pull/build/push docker image).

Daily, it really is annoying :(

**Comment by manishas** [comment]
@xherriot can you give me the username you sign in with? I cannot find any builds for the account you're using to post here.

**Comment by xherriot** [comment]
Yes, this is another acccount: TechnicalBot

**Comment by xherriot** [comment]
It's happening again & again :(

<img width="1231" alt="screen shot 2015-07-15 at 09 04 19" src="https://cloud.githubusercontent.com/assets/5094797/8692701/0dd70100-2ad1-11e5-97f1-6922316fa627.png">

**Comment by lekhab** [comment]
@xherriot: are you still facing this?

**Comment by xherriot** [comment]
I always have an issue with "composer install" command, I don't know if the problem come from shippable or the repository but it always happen in the react/stream library:

<img width="979" alt="screen shot 2015-10-01 at 08 02 38" src="https://cloud.githubusercontent.com/assets/5094797/10214458/cad6e93a-6818-11e5-90b8-ea9b6beb9d90.png">

Sometimes it works, sometime it doesn't.

A bad one: https://app.shippable.com/builds/560cccab354b7c0c00ec1269
A good one: https://app.shippable.com/builds/560c17138bd2640d0068614b

**Comment by avinci** [comment]
can your try `shippable_retry` command so that youdont get affected by network glitches?
