### ISSUE TITLE
docker-compose support from shippable with elastic beanstalk

### ISSUE THREAD

**Issue by mozinrat** [Shippable/support#1654]
Sir, I would like to suggest support for deployment on ELB from a docker-compose.yml

**Comment by manishas** [comment]
@mozinrat have you checked out Formations - https://app.shippable.com/mktg/#formations

Let me know if this is something that would address your requirements. Formations lets you run multi-container environments very easily without the need to manage infrastructure, provisioning, networking, etc.

**Comment by manishas** [comment]
you can now run docker compose in shippable.yml, so your workflow should now be configurable. Check out http://docs.shippable.com/ci_docker/#docker-compose

I am closing this issue since it has been addressed.
