### ISSUE TITLE
Build keep hanging after docker pull

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1655]
inventid/neo build are hanging after docker pull until they timeout, numbers are 4288, 4299, 4290.

Not sure why, the logs show no extra information at all

**Comment by manishas** [comment]
Should be fixed now. Please let us know if it happens again.

**Comment by rogierslag** [comment]
Seems to be happening again to 4293 and 4294.

**Comment by rogierslag** [comment]
And now it seems to be OK again :)

**Comment by rogierslag** [comment]
And now it isnt again. The variableness seems to indicate it is host dependent

**Comment by rogierslag** [comment]
I've updated according to the email that was sent out (about deprecated settings) and we now specify the integrations and the docker images in the new fashion since build _4353_. So far that does not seem to make a difference.

@joostverdoorn this is the reason builds are timing out. If they are still at `docker pull` after three minutes, cancel that build and refire it

**Comment by rageshkrishna** [comment]
@rogierslag I'm looking in to this and I think I know why this is happening. Did you make any recent changes to your image? Would it be possible for you to share your latest Dockerfile with me (ragesh@shippable.com). I think there is something about how your image is set up that our build system isn't expecting. The Dockerfile would help me round this down quickly. Thanks!

**Comment by rogierslag** [comment]
Cool thanks for looking into this! I've sent you an email with our docker build instructions. In case you need any more information, please let me know! :heart:

**Comment by rogierslag** [comment]
Fixed with a supporter, our image was partly to blame
