### ISSUE TITLE
Build stuck in waiting state

### ISSUE THREAD

**Issue by satyasrikantmantha** [Shippable/support#1657]
Hi,

I queued a build and it is stuck in waiting state for more than 10 minutes.

Normally, the builds are in waiting state if the minions are not available. However, the build I am running is the only one in the queue now and it is stuck in waiting state. 

I also tried cancelling the build and running a new one, which is still causing the same issue. 

Any help in this direction would be appreciated.

Kind Regards...

**Comment by jawaid** [comment]
Please check again. This has been fixed.

**Comment by RobertHerhold** [comment]
This has been happening to me for ~2-3 days... Any news concerning this issue?

**Comment by manishas** [comment]
@RobertHerhold can you share your yml file?

**Comment by lekhab** [comment]
@RobertHerhold - following up on your issue in #1686. 

Closing this one. @satyasrikantmantha: please let me know if you are still seeing issues with your builds.
