### ISSUE TITLE
Log not loading

### ISSUE THREAD

**Issue by tekram** [Shippable/support#1658]
It seems like this build failed but I am unable to load the log. 

https://app.shippable.com/builds/559c2ac3f923de0f0056f3ab

**Comment by jeffkole** [comment]
+1.  Having the same issue with https://app.shippable.com/builds/559c43c2c8ded311002a1f2d

**Comment by lekhab** [comment]
This issue was resolved with the new system (newer builds should not have this issue. Note: logs were purged for builds older than Aug 16) Closing this.
