### ISSUE TITLE
All jasmine tests timing out

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#1659]
https://app.shippable.com/builds/559c3fd9c8ded311002a1208

All of these work just fine locally.  Nothing is different in this build from yesterday's successful build of master other than a `[reset_minion]` tag used to debug other builds that are broken for no clear reason.

https://app.shippable.com/builds/559b03f58469020c00c6999e is a successful build from yesterday with the exact same code.

**Comment by RobertHerhold** [comment]
Mine are also timing out:
https://app.shippable.com/builds/559adea8ee07b90e00e3b9fd

And the other ones are currently not running at all ("waiting"), will most likely be timed out in about 2 hrs:

https://app.shippable.com/builds/559c598ec8ded311002a936d

**Comment by jeffkole** [comment]
Looks like it has been resolved for now.

**Comment by RobertHerhold** [comment]
Mine is still waiting...
https://app.shippable.com/builds/559c6adf5f95d00b002cc7c5

**Comment by lekhab** [comment]
Closing this, since the original issue is resolved and another issue is open for @RobertHerhold's specific build (#1686)
