### ISSUE TITLE
100% Test passing, 0 Failures, but Build Fails

### ISSUE THREAD

**Issue by StephenGrider** [Shippable/support#1660]
I'm having an issue with this merge build: https://app.shippable.com/builds/559c634ac8ded311002ab0e5
There are no errors being reported by the UI or the console, yet the build is still being marked as failing.  

In addition, the commit version of the build is getting a `fail to start chrome` error: https://app.shippable.com/builds/559c634bc8ded311002ab0e8

If any other info is required for troubleshooting just let me know :)

Here is my `shippable.yaml`:

```
language: node_js

node_js:
  - 0.12

before_install:
  - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
  - npm install -g karma-cli gulp-cli coffee-script
  - apt-get update
  - apt-get -y install xvfb chromium-browser
  - test -e /tmp/.X99-lock || /usr/bin/Xvfb :99 &
  - export DISPLAY=:99.0
  - export CHROME_BIN=/usr/bin/chromium-browser
  - coffee -c karma.conf.coffee

install:
  - npm install
  - gulp shippable

script:
  - karma start --browsers Chrome --singleRun true --reporters progress,junit
```

**Comment by pschrammel** [comment]
Hi, 
we're having a similar issue with a ruby environment. Everything passes (all tests, all steps) but we get a build fail.

https://app.shippable.com/builds/559d0ebac6edff0b008ec7d4

**Comment by manishas** [comment]
we're looking into this now, thanks!

**Comment by StephenGrider** [comment]
@manishas Thanks for looking into this.  Just to be clear, we are having two separate issues: the build failing with 0 spec failures, and the commit version is failing due to a failure to start chrome.

**Comment by StephenGrider** [comment]
Hi @manishas, I was curious if there was any progress on this issue.

**Comment by manishas** [comment]
we're looking into the build failing with 0 errors problem and but we haven't been able to find the root cause yet. We might need to add more logging to identify the problem.

I'll follow up on the other issue and let you know what we find.

**Comment by manishas** [comment]
This is an old issue and the entire build system has been revamped since then to avoid running into such scenarios. Closing this since this should not happen on the new platform.
