### ISSUE TITLE
Can't save setting if there's no entry in "Pull image from"

### ISSUE THREAD

**Issue by osumampouw** [Shippable/support#1662]
Hi,
I have 3 questions about project settings:
1.) I want to enable save between state in each CI build, does that require a docker container? Because in the project setting, when I enable "Cache Container", it says I have to write something on "Pull image from" field?
2.) If yes, right now I don't have time to setup docker container yet, so I disabled "Cache Container" option, but I still can't remove the the text inside "Pull Image From". So now I can't build anything because everytime I try to build, it will throw this exception:
Pulling repository cermati-test
Error: image library/cermati-test:latest not found

3.) Is there a way to undo my entry in "Pull Image from"? If not, how can I setup docker so I can move on?

**Comment by lekhab** [comment]
@osumampouw:
1. You don't need to do a docker build to enable caching (please let me know if I misunderstood your query here). In the  "Pull Image from" field, enter what was previously specified under `build_image` in your shippable yml. If you are not using a custom build_image and are going with the default, please enter shippable/minv2 in that field. Further details are documented here: http://docs.shippable.com/project_settings/#build-image.

2. Please refer to the answers for (1) and (3) and let me know if that doesn't help.

3. You can undo Project Settings by clicking on the tiny trash icon below the Project Settings. Screen shot below.


![proj_settings](https://cloud.githubusercontent.com/assets/9526532/8582568/7e56c5be-257c-11e5-8449-b35274a65d1f.png)


Does that help?

**Comment by osumampouw** [comment]
oh you're right. Thanks that answers my question :)
