### ISSUE TITLE
Frequent failures from install step running npm install

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1663]
We are seeing frequent build failures that causes our builds to stop at the install step while running npm install.

Looking at the console logs it looks like the minion is unable to connect to npmjs.org.

Typically just rerunning the same build several times will cause it to succeed.  It sometimes takes three or four re-runs before it completes successfully.

**Comment by chriskinsman** [comment]
The odd part is that is gets part way through.  Check out pushspring/ps-jobscripts Build 1016 for a recent example.

**Comment by chriskinsman** [comment]
Just tried adding shippable_retry before it to see if that helps.

**Comment by ragsden** [comment]
@chriskinsman We are looking into this and will get back to you soon. Thanks.

**Comment by ragsden** [comment]
@chriskinsman : NPM install has errors when trying to build postgres related libraries. This is happening for both 1016 and 1017 builds. 
For some reason npm install is ignoring the errors and moving forward in case of build 1017. Ideally 1017 should have failed too. We will have to do some more debugging to understand npm install's behavior.

In the mean time to will have to install postgres to make npm install successful. You can do the following in the before install section
echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" >> /etc/apt/sources.list ;
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
apt-get update;
apt-get install postgresql-9.3 postgresql-contrib-9.3 postgresql-client-9.3;
Please let me know if this works.

**Comment by chriskinsman** [comment]
@ragsden We are actually fine with those native builds failing.  You don't have a build_image with postgres pre-installed and we don't want to take the build perf hit installing it.

When those fail things usually proceed without any issues.  It is just recently that things have started failing right after those steps...

**Comment by chriskinsman** [comment]
@ragsden @manishas Still seeing this quite frequently even after putting in shippable_retry.  We can't see what in the build has failed in the log but it is marked as failed during the npm install phase...

**Comment by manishas** [comment]
@chriskinsman i don't see this happening for your project any more. Can we close this?

**Comment by chriskinsman** [comment]
Sure.  It is quite intermittent we have found.
