### ISSUE TITLE
Internationalized messages not loading properly on shippable.com

### ISSUE THREAD

**Issue by lekhab** [Shippable/support#1664]
Opening an issue on behalf of @kkarski:

When my shippable.com initially loads, and the wheel is spinning with the UI loading, the internationalized messages are not loading properly, instead I always see {{...some message key..}} for all the UI elements.

@kkarski: Please paste a screenshot here when you see this happening again.

**Comment by pquentin** [comment]
We sometimes get hit by this too.

Occasionally, it can be a FOUC:

![screen shot 2015-07-09 at 10 05 09](https://cloud.githubusercontent.com/assets/42327/8590593/448273d2-2622-11e5-8f14-9c7cf4571af1.png)

But usually it's just:

![loading_message](https://cloud.githubusercontent.com/assets/42327/8590598/5034ee62-2622-11e5-93d7-6edf91143225.png)

**Comment by lekhab** [comment]
@pquentin/@kkarski: this was fixed in the deployment last week. Please let me know if you still see this in any part of your workflow.
