### ISSUE TITLE
/subscriptions/... page consistently takes more than 10 seconds to load

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#1665]
Shippable has always been slow since we started using it in December 2014. We had hoped speed would have become a priority, but it does not look like it. Our network is not fast, but Shippable still is the exception. The slowest page on shippable for us it the subscriptions page, that list the status of our 39 shippable projects.

 * On load, Firefox reports 151 requests and 2MB page size, for a page load time between 10.71s and 11.24s for a sample size of 5 pages loads.
 * On reload, Firefox reports 159 requests and 2.5MB page size, for a page load time between 12.10s and 13.30s.

The page load seems to be divided in three main parts:

 1. Calls to app.shippable.com. They're *fast*, between 50ms and 500ms and well distributed, so they end after 1.5s at most.
 2. 30 requests to api.shippable.com. They're also fast, but seem to happen sequentially. They end after 8s.
 3. Many calls to api.shippable.com/projects/.../searchBuilds?status=complete&limit=1&isPR=false. They seem to be distributed, but seem to hit what looks like a concurrent requests Firefox limit. They spend more and more time waiting, and the last requests take 3s.

I'd be happy to share anything else that could help debug the issue. I'll send the organization name by email, but continuing the discussion here would be nice. Thank you for shippable!

**Comment by jchamberlain** [comment]
I second this. The long page loads get pretty tiresome. I have only two projects, but it still takes upwards of 8 seconds before I can see them (Chrome).

**Comment by pquentin** [comment]
Any progress on this? Thanks!

**Comment by manishas** [comment]
This should be fixed with our new release which also addressed perf. please let us know if you think pages still load slowly...
