### ISSUE TITLE
docker image tests after build image / before push container

### ISSUE THREAD

**Issue by trentmswanson** [Shippable/support#1667]
I would like to run tests on the image output that was built before it's pushed to docker hub.

Is there something like "after_buildimage" or "before_pushcontainer" events where I can execute some scripts to run and test?

How are folks doing  this today?  Am I missing something?

**Comment by manishas** [comment]
@trentmswanson I want to understand your scenario a little bit better before I recommend how to achieve this.

We support 2 workflows with Dockerbuild -

build image from Dockerfile -> pull code from github and put it in the container -> run your unit tests in the container -> if tests pass, push container to docker registry
OR
pull image from docker registry -> pull code from github and put it in the container -> run your unit tests in the container -> if unit tests pass, build image from Dockerfile -> push image to docker registry

These scenarios are possible with our CI platform. If this addresses your scenario, let me know and I can point you to the right docs.

**Comment by trentmswanson** [comment]
Thanks @manishas, I am using the second workflow you had listed right now.

pull image from docker registry (build image includes grunt packages) -> pull code from github and put it in the container -> run unit tests in the container -> if unit tests pass, build image from Dockerfile (app runtime image) -> push image to docker registry

Is what I would like to do is just test/validate the image before it's pushed to docker hub.  Actually, a little bit more than that.

pull image from docker registry (build image includes grunt, etc...) -> pull code from github and put it in the container -> run unit tests in the container -> if unit tests pass, build image from Dockerfile (app runtime image) -> run integration, functional, acceptance(maybe) tests on a running container -> push image to docker registry

It may seem trivial, but I would very much like to run most of my tests against container from the image that is built instead of the code before it's pushed to docker hub.  After the image is build I could see this as shippable either calling my script or command from which I call docker run, and then some tests or shippable runs my image with configurable set of parameters and then my scripts to run the tests.  Once successful the container is stopped and the image is pushed.

**Comment by rraheja** [comment]
+1 for the support to test the post-CI build container-would be useful to validate the container before final push.

**Comment by avinci** [comment]
I am not sue why PRE CI Dockerbuild not work for this scenario? This seems awfully similar to what like PRECI build does today

**Comment by trentmswanson** [comment]
It's actually quite different than your PRE CI approach, but no longer matters to me as I have moved on and have it working they way it should.

**Comment by avinci** [comment]
Thanks for getting back. I would love to understand what is different if you don't mind. Maybe it's something we would want to support for other.

**Comment by rraheja** [comment]
PreCI is not the same. We use Post CI since our build and test have a lot of different pre-requisites tools that I don't want to ship in the final delivered container. However I still want to test the image using functional tests before publishing it to the repo. A PreCI build that pushes a postCI Dockerfile could have worked but I guess that would be a different workflow altogether PrePostCI?

**Comment by trentmswanson** [comment]
Like @rraheja we need to be able to run, test, and validate the docker images that are built before they can be pushed to docker hub.

This is the primary reason we moved off shippable.

**Comment by manishas** [comment]
This is now addressed with the new yml format where you can run docker commands as part of your ci workflow through the yml. 

You can spin up containers, run docker compose, etc to run functional tests if needed. 

Documentation for the new format is at http://docs.shippable.com/ci_configure/

Let us know if you need help with configuring this.

**Comment by jasonrichardsmith** [comment]
Since this result comes up in google you may want to update the dead link
