### ISSUE TITLE
ERROR: Database server does not support the InnoDB storage engine. 

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#1668]
build 559ee5bc72c8990c0031cc12

**Comment by rageshkrishna** [comment]
@luckyraul Is it possible you are running in to this Magento issue: http://stackoverflow.com/questions/17284498/innodb-working-still-showing-database-server-does-not-support-innodb-storage-e

I did a `show engines` on mysql inside our container and it definitely lists InnoDB as installed and default:
````
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+
| Engine             | Support | Comment                                                        | Transactions | XA   | Savepoints |
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+
| FEDERATED          | NO      | Federated MySQL storage engine                                 | NULL         | NULL | NULL       |
| CSV                | YES     | CSV storage engine                                             | NO           | NO   | NO         |
| MRG_MYISAM         | YES     | Collection of identical MyISAM tables                          | NO           | NO   | NO         |
| BLACKHOLE          | YES     | /dev/null storage engine (anything you write to it disappears) | NO           | NO   | NO         |
| MEMORY             | YES     | Hash based, stored in memory, useful for temporary tables      | NO           | NO   | NO         |
| MyISAM             | YES     | MyISAM storage engine                                          | NO           | NO   | NO         |
| ARCHIVE            | YES     | Archive storage engine                                         | NO           | NO   | NO         |
| PERFORMANCE_SCHEMA | YES     | Performance Schema                                             | NO           | NO   | NO         |
| InnoDB             | DEFAULT | Supports transactions, row-level locking, and foreign keys     | YES          | YES  | YES        |
+--------------------+---------+----------------------------------------------------------------+--------------+------+------------+

````

**Comment by luckyraul** [comment]
I don't think it is a software problem, because on TRAVIS
https://travis-ci.org/mygento/cdn/jobs/69450507 
it is working normally with the same ENV parameters

**Comment by rageshkrishna** [comment]
It works on Travis because they are running MySQL 5.5 whereas our image is running 5.6. I think this confirms the issue I linked to earlier, because the variable that magento is looking for to determine InnoDB availability was removed in MySQL 5.6.

There is currently no way to change MySQL versions short of doing a manual installation in your YML file. It would be easier to just create a custom Docker image to run the build instead.

**Comment by luckyraul** [comment]
Ok, thanks. Docker is that's I am doing today  and I have the problem  with using docker( already issued). Anyway can you tell me how I can pass ENV variables from matrix for docker building? I know  I can not use them in build command. Maybe you have some events on yml configuration for prebuild scripting?

**Comment by manishas** [comment]
The docker issue is at https://github.com/Shippable/support/issues/1648

**Comment by manishas** [comment]
We have completely redone our yml format and it is now possible to pass options to the docker build or run command since docker workflows and commands can be included in the yml. closing.
