### ISSUE TITLE
Status badges require a none standard font be installed.

### ISSUE THREAD

**Issue by PJnes** [Shippable/support#1673]
The build status badges look terrible unless the user has DejaVuSans installed, as they'll fallback to the browser default.

![screenshot](https://cloud.githubusercontent.com/assets/5631/8663463/141f6d18-29c3-11e5-84d4-5aae0c9c9b38.png)

Any chance of adding some fallbacks alongside DejaVuSans?

**Comment by lukefrake** [comment]
:+1:

**Comment by manishas** [comment]
Our new badges are images, so don't need any fonts installed. closing.
