### ISSUE TITLE
Internal API error

### ISSUE THREAD

**Issue by devmach** [Shippable/support#1675]
When i try to check what's failing with the build, 4 of 5 times I'm getting following error.

```
{"id":1005,"message":"Internal API error : getPermissionByProjectId","methodName":"chkPermForId|_getSByProjectId"}
```

![image](https://cloud.githubusercontent.com/assets/538277/8676625/a017282e-2a18-11e5-8425-4dee7641e672.png)

**Comment by manishas** [comment]
I don't see any projects enabled for your account....what are you clicking on to get to this page?

**Comment by devmach** [comment]
@manishas I'm clicking on "Details" link in a pull request (, which redirects me to https://app.shippable.com/builds/55a53b5d322c9a0b00dc0255 ). It's a private repository but shippable should have an access.

![image](https://cloud.githubusercontent.com/assets/538277/8681215/387e8286-2a34-11e5-8018-3828e70021c3.png)

**Comment by manishas** [comment]
@devmach have you enabled private repos for your Shippable account?

Here is how you can check -
- Go to account settings by clicking on the gear icon in the top menu (second from right)
- Make sure that for your github identity, both private and public repos are set to ON -
![screen shot 2015-07-14 at 11 33 58 am](https://cloud.githubusercontent.com/assets/2983749/8681462/58ea040e-2a1c-11e5-849e-cfd2e785e575.png)

If private repos are not on, please click on the private repos icon to grant permissions. 
- Click on Force Sync in the Account information section in Account settings 
![screen shot 2015-07-14 at 11 35 43 am](https://cloud.githubusercontent.com/assets/2983749/8681488/87e78010-2a1c-11e5-9dd1-d313157e294d.png)

Now try clicking on the build link again.

**Comment by devmach** [comment]
@manishas : It worked, thanks.
