### ISSUE TITLE
Allowing users to report bugs privately

### ISSUE THREAD

**Issue by devmach** [Shippable/support#1676]
While reporting bugs through GitHub issues is developer friendly, it's definitely not a business friendly way. There should be a way to report issues privately which won't cause developers headache with their employers.

**Comment by manishas** [comment]
@devmach another way to report issues privately is to send an email to support@shippable.com

We prefer GitHub issues for a couple of reasons -
- users can help each other out in some cases, so it's a more scalable, community driven way of helping out. This is especially useful when it's a matter of yml configuration for a specific scenario, which can take us some time to figure out but can sometimes get instant help from the community.
- This repository serves as a knowledge base for new users who run into something and then search for similar issues.
- There is an easy way to keep track of the issue. 

Please feel free to send an email to support@shippable.com with your bug. Thanks!
