### ISSUE TITLE
Shippable won't build Centos 7 containers

### ISSUE THREAD

**Issue by buley** [Shippable/support#1681]
I've found the following at the top of a `Dockerfile` will cause my builds to fail on Shippable:

	FROM    centos:latest
	RUN yum -y install epel-release \
	  && yum -y update \
	  && yum -y upgrade
    ...

I've tried a number of different pulled images to build from, but it seems related to (apparently) some usage of AUFS somewhere.  https://github.com/docker/docker/issues/6980 Using the currently-supported `centos6.6` was my fix.

e.g. https://app.shippable.com/builds/55a72e96b617690b00155cd9

The key error:

> 	error: unpacking of archive failed on file /usr/bin/ping: cpio: cap_set_file

	Step 0 : FROM centos:latest
	latest: Pulling from centos
	f1b10cd84249: Already exists
	c852f6d61e65: Already exists
	7322fbe74aa5: Already exists
	7322fbe74aa5: Already exists
	Digest: sha256:57554136c655abb33ecb7bb790b1db0279668d3763c3b81f31bc6c4e60e4a1f3
	Status: Image is up to date for centos:latest
	---> 7322fbe74aa5
	Step 1 : MAINTAINER Taylor Buley (taylor.buley@mcnaughton.media)
	---> Running in edbbac70d137
	---> f00936843cd7
	Removing intermediate container edbbac70d137
	Step 2 : RUN groupadd -g 1855 application && /usr/sbin/useradd --uid 1855 --create-home --home-dir /usr/local/application --shell /bin/bash -g application application && /usr/sbin/usermod -g application root && chown -R application:application /usr/local/ && chown -R application:application /usr/src/ && chown -R application:application /usr/lib/ && chown -R application:application /usr/bin/ && chown -R root:application /var/log && chown -R application:application /srv && chmod 765 /srv && chmod +s /srv
	---> Running in e2cbae8418f3
	---> ee93c72e5f85
	Removing intermediate container e2cbae8418f3
	Step 3 : RUN yum -y install epel-release && yum -y update && yum -y upgrade
	---> Running in f3a7f6ed5f26
	Loaded plugins: fastestmirror
	Determining fastest mirrors
	* base: mirror.umd.edu
	* extras: mirror.vtti.vt.edu
	* updates: mirror.cc.columbia.edu
	Resolving Dependencies
	--> Running transaction check
	---> Package epel-release.noarch 0:7-5 will be installed
	--> Finished Dependency Resolution
	Dependencies Resolved
	================================================================================
	Package Arch Version Repository Size
	================================================================================
	Installing:
	epel-release noarch 7-5 extras 14 k
	Transaction Summary
	================================================================================
	Install 1 Package
	Total download size: 14 k
	Installed size: 24 k
	Downloading packages:
	[91mwarning: /var/cache/yum/x86_64/7/extras/packages/epel-release-7-5.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
	[0mPublic key for epel-release-7-5.noarch.rpm is not installed
	Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
	[91mImporting GPG key 0xF4A80EB5:
	Userid : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
	Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
	Package : centos-release-7-1.1503.el7.centos.2.8.x86_64 (@CentOS)
	From : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
	[0mRunning transaction check
	Running transaction test
	Transaction test succeeded
	Running transaction
	Installing : epel-release-7-5.noarch 1/1
	Verifying : epel-release-7-5.noarch 1/1
	Installed:
	epel-release.noarch 0:7-5
	Complete!
	Loaded plugins: fastestmirror
	[91mhttp://mirror.es.its.nyu.edu/epel/7/x86_64/repodata/177d6316481d72b37adfa268bc016669c6c8092a815b20c3c962ecb258b84cc9-primary.sqlite.xz: [Errno 14] HTTP Error 404 - Not Found
	[0m[91mTrying other mirror.
	[0m[91mhttp://mirror.cc.columbia.edu/pub/linux/epel/7/x86_64/repodata/177d6316481d72b37adfa268bc016669c6c8092a815b20c3c962ecb258b84cc9-primary.sqlite.xz: [Errno 14] HTTP Error 404 - Not Found
	[0m[91mTrying other mirror.
	[0mLoading mirror speeds from cached hostfile
	* base: mirror.umd.edu
	* epel: mirror.symnds.com
	* extras: mirror.vtti.vt.edu
	* updates: mirror.cc.columbia.edu
	Resolving Dependencies
	--> Running transaction check
	---> Package iputils.x86_64 0:20121221-6.el7 will be updated
	---> Package iputils.x86_64 0:20121221-6.el7_1.1 will be an update
	---> Package nss.x86_64 0:3.18.0-2.2.el7_1 will be updated
	---> Package nss.x86_64 0:3.19.1-3.el7_1 will be an update
	---> Package nss-sysinit.x86_64 0:3.18.0-2.2.el7_1 will be updated
	---> Package nss-sysinit.x86_64 0:3.19.1-3.el7_1 will be an update
	---> Package nss-tools.x86_64 0:3.18.0-2.2.el7_1 will be updated
	---> Package nss-tools.x86_64 0:3.19.1-3.el7_1 will be an update
	---> Package nss-util.x86_64 0:3.18.0-1.el7_1 will be updated
	---> Package nss-util.x86_64 0:3.19.1-1.el7_1 will be an update
	---> Package openssl-libs.x86_64 1:1.0.1e-42.el7.8 will be updated
	---> Package openssl-libs.x86_64 1:1.0.1e-42.el7.9 will be an update
	---> Package python.x86_64 0:2.7.5-16.el7 will be updated
	---> Package python.x86_64 0:2.7.5-18.el7_1.1 will be an update
	---> Package python-libs.x86_64 0:2.7.5-16.el7 will be updated
	---> Package python-libs.x86_64 0:2.7.5-18.el7_1.1 will be an update
	---> Package tzdata.noarch 0:2015d-1.el7 will be updated
	---> Package tzdata.noarch 0:2015e-1.el7 will be an update
	--> Finished Dependency Resolution
	Dependencies Resolved
	================================================================================
	Package Arch Version Repository Size
	================================================================================
	Updating:
	iputils x86_64 20121221-6.el7_1.1 updates 152 k
	nss x86_64 3.19.1-3.el7_1 updates 846 k
	nss-sysinit x86_64 3.19.1-3.el7_1 updates 51 k
	nss-tools x86_64 3.19.1-3.el7_1 updates 478 k
	nss-util x86_64 3.19.1-1.el7_1 updates 70 k
	openssl-libs x86_64 1:1.0.1e-42.el7.9 updates 949 k
	python x86_64 2.7.5-18.el7_1.1 updates 86 k
	python-libs x86_64 2.7.5-18.el7_1.1 updates 5.6 M
	tzdata noarch 2015e-1.el7 updates 432 k
	Transaction Summary
	================================================================================
	Upgrade 9 Packages
	Total download size: 8.6 M
	Downloading packages:
	Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
	--------------------------------------------------------------------------------
	Total 3.1 MB/s | 8.6 MB 00:02
	Running transaction check
	Running transaction test
	Transaction test succeeded
	Running transaction
	Updating : nss-util-3.19.1-1.el7_1.x86_64 1/18
	Updating : nss-sysinit-3.19.1-3.el7_1.x86_64 2/18
	Updating : nss-3.19.1-3.el7_1.x86_64 3/18
	Updating : 1:openssl-libs-1.0.1e-42.el7.9.x86_64 4/18
	Updating : python-libs-2.7.5-18.el7_1.1.x86_64 5/18
	Updating : python-2.7.5-18.el7_1.1.x86_64 6/18
	Updating : iputils-20121221-6.el7_1.1.x86_64 7/18[91mError unpacking rpm package iputils-20121221-6.el7_1.1.x86_64
	[0m
	error: unpacking of archive failed on file /usr/bin/ping: cpio: cap_set_file
	Updating : nss-tools-3.19.1-3.el7_1.x86_64 8/18
	error: iputils-20121221-6.el7_1.1.x86_64: install failed
	Updating : tzdata-2015e-1.el7.noarch 9/18
	Cleanup : nss-tools-3.18.0-2.2.el7_1.x86_64 10/18
	Cleanup : nss-sysinit-3.18.0-2.2.el7_1.x86_64 11/18
	Cleanup : nss-3.18.0-2.2.el7_1.x86_64 12/18
	Cleanup : python-2.7.5-16.el7.x86_64 13/18
	error: iputils-20121221-6.el7.x86_64: erase skipped
	Cleanup : tzdata-2015d-1.el7.noarch 14/18
	Cleanup : python-libs-2.7.5-16.el7.x86_64 15/18
	Cleanup : 1:openssl-libs-1.0.1e-42.el7.8.x86_64 16/18
	Cleanup : nss-util-3.18.0-1.el7_1.x86_64 17/18
	Verifying : 1:openssl-libs-1.0.1e-42.el7.9.x86_64 1/18
	Verifying : nss-3.19.1-3.el7_1.x86_64 2/18
	Verifying : python-libs-2.7.5-18.el7_1.1.x86_64 3/18
	Verifying : nss-sysinit-3.19.1-3.el7_1.x86_64 4/18
	Verifying : python-2.7.5-18.el7_1.1.x86_64 5/18
	Verifying : nss-tools-3.19.1-3.el7_1.x86_64 6/18
	Verifying : nss-util-3.19.1-1.el7_1.x86_64 7/18
	Verifying : tzdata-2015e-1.el7.noarch 8/18
	Verifying : python-2.7.5-16.el7.x86_64 9/18
	Verifying : nss-3.18.0-2.2.el7_1.x86_64 10/18
	Verifying : python-libs-2.7.5-16.el7.x86_64 11/18
	Verifying : iputils-20121221-6.el7_1.1.x86_64 12/18
	Verifying : nss-tools-3.18.0-2.2.el7_1.x86_64 13/18
	Verifying : tzdata-2015d-1.el7.noarch 14/18[91miputils-20121221-6.el7.x86_64 was supposed to be removed but is not!
	[0m
	Verifying : iputils-20121221-6.el7.x86_64 15/18
	Verifying : nss-sysinit-3.18.0-2.2.el7_1.x86_64 16/18
	Verifying : 1:openssl-libs-1.0.1e-42.el7.8.x86_64 17/18
	Verifying : nss-util-3.18.0-1.el7_1.x86_64 18/18
	Updated:
	nss.x86_64 0:3.19.1-3.el7_1 nss-sysinit.x86_64 0:3.19.1-3.el7_1
	nss-tools.x86_64 0:3.19.1-3.el7_1 nss-util.x86_64 0:3.19.1-1.el7_1
	openssl-libs.x86_64 1:1.0.1e-42.el7.9 python.x86_64 0:2.7.5-18.el7_1.1
	python-libs.x86_64 0:2.7.5-18.el7_1.1 tzdata.noarch 0:2015e-1.el7
	Failed:
	iputils.x86_64 0:20121221-6.el7 iputils.x86_64 0:20121221-6.el7_1.1
	Complete!
	Removing intermediate container f3a7f6ed5f26
	The command '/bin/sh -c yum -y install epel-release && yum -y update && yum -y upgrade' returned a non-zero code: 1

(Interestingly, if I used `centos:centos7` it said the image was up to date and hung forever. Seems to be OK with `centos6`)

**Comment by ragsden** [comment]
@buley : Unfortunately our CI system does not support centos. Currently we support Ubuntu 12.04 and 14.04. Please let m know if you have any questions.
Raghu

**Comment by ragsden** [comment]
@buley  My bad, I just realized that you are trying to build an image. Ignore my previous comment.

**Comment by manishas** [comment]
this is an old issue and we have completely revamped the build system since then.You can now run docker build yourself in the yml - http://docs.shippable.com/ci_configure/#setting-your-build-image
