### ISSUE TITLE
System is very slow

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1682]
Hi, 

I am experiencing performance issues with the console and the build processes. Are you aware of this? 

Regards,
Ron

**Comment by rvdwijngaard** [comment]
any updates on this: I am not able to run any build at the moment.

**Comment by manishas** [comment]
looking into it...

**Comment by lekhab** [comment]
@rvdwijngaard: There were performance issues yesterday that has since been resolved. We are actively working on addressing the root cause related to the slowness. Thanks for your patience!
