### ISSUE TITLE
Coverage decrease alert

### ISSUE THREAD

**Issue by antonienko** [Shippable/support#1683]
Would it be possible to implement an alert when the code coverage decreases significantly?

I want to be able to know if some developer pushed code without proper test coverage.

**Comment by manishas** [comment]
consolidating all coverage feature requests in #174

**Comment by harryi3t** [comment]
Hey @antonienko, I see that you have moved to travis and scrutinizer-ci.
But still I just wanted you to know that we now support the feature you requested and more!

### 1. coverage badge
![coverage-badge][1]

### 2. Notification alert (slack/hipchat/email/irc) on low coverage. 
### 3. Support to mark build as "UNSTABLE" in low coverage
![lowcoverage-alert][2]

Both of these can be configured/accessed from the project settings page

[1]:https://cloud.githubusercontent.com/assets/5207331/14566885/07cbeb70-034f-11e6-8b54-cbfed13f4202.png
[2]:https://cloud.githubusercontent.com/assets/5207331/14567480/e6842cf4-0351-11e6-8297-d1c6f414cd83.png

If there are any more features that you would like to see in Shippable, feel free to let us know
