### ISSUE TITLE
Deployment works but always shows as Timeout

### ISSUE THREAD

**Issue by dunicaboy** [Shippable/support#1685]
I have a GAE Maven deployment which seems to deploy correctly.
However, the console always shows it as 'Timeout'
This was happening before and was fixed Issue https://github.com/Shippable/support/issues/1630

The logs finish with the following;

Update for module default completed successfully.

Success.

Cleaning up temporary files for module default...

[INFO] ------------------------------------------------------------------------

[INFO] BUILD SUCCESS

[INFO] ------------------------------------------------------------------------

[INFO] Total time: 45:05 min

[INFO] Finished at: 2015-06-29T07:59:40+00:00

[INFO] Final Memory: 36M/1621M

[INFO] ------------------------------------------------------------------------
after_script

copy_archives

exec_echo

echo 'skipping archive upload...'

skipping archive upload...
after_archive

**Comment by lekhab** [comment]
following up

**Comment by dunicaboy** [comment]
Any success with this. My deployments still timeout

**Comment by lekhab** [comment]
@dunicaboy: your builds should work now - I just ran a test build for you and it went through successfully. We are following up on the root cause of why your build is timing out on the new orchestration layer. In the meantime, we have moved you back to the previous version.

**Comment by dunicaboy** [comment]
Thanks for ur help
