### ISSUE TITLE
All builds timing out

### ISSUE THREAD

**Issue by RobertHerhold** [Shippable/support#1686]
Hi,

I've seen a few other issues around like this, but they seem to have been resolved. Additionally, the [Shippable Twitter feed](https://twitter.com/BeShippable/status/621718140498522112) seems to indicate that everything is back up, but my builds still will not run.

https://app.shippable.com/builds/55a88011b891e30b00c3d0cc

**Comment by lekhab** [comment]
@RobertHerhold: can you please share your YML? This seems specific to your project and I am unable to reproduce it with our sample mongo projects. The YML would help us look into this further.

Have you tried running this on a multi-tenant?

**Comment by RobertHerhold** [comment]
@lekhab 

My YML file is:

```
language: java

jdk:
    - openjdk7

# Mongo binds to 127.0.0.1 by default
services:
    # - mongodb
    - rabbitmq

# environment variable
env:
    - XUNIT_FILE=../../shippable/testresults/result.xml

before_install:
    - mongod --config ./config.yml

install:
    - mvn install --batch-mode

# Create directories for test and coverage reports
before_script:
    - mongo < ./logQueries.sh
    #- tail -f /var/log/mongodb/mongodb.log &
    - mkdir -p ./shippable/testresults
    - mkdir -p ./shippable/codecoverage

script:
    - "java -jar target/blocklaunch-api-1.0.jar server config_test.yml &"
    - cd ./test/frisby/
    - sudo npm install
    - ./node_modules/mocha/bin/mocha test --reporter xunit-file
    # - ./node_modules/mocha/bin/mocha **/*.js --reporter xunit-file

after_script:
    - less /var/log/mongodb/mongodb.log
    - pkill java
```

The `config.yml` file referenced in the `before_install` section:
```
systemLog:
   verbosity: 5
```

The `logQueries.sh` file in the `before_script` section:
```
use blocklaunch-test
# db.setLogLevel(5)
db.runCommand( {
   setParameter: 1,
   logComponentVerbosity: {
      verbosity: 5
    #   query: {
        #  verbosity: 2
    #   }
   }
} )
db.getProfilingLevel()
db.setProfilingLevel(2)
db.getProfilingLevel()
db.system.profile.find().pretty()
```

**Comment by RobertHerhold** [comment]
I just tried another repo, and the build still hangs:

https://app.shippable.com/projects/55abbe36edd7f2c05278150d

YML:
```
services:
  - rethinkdb

script:
  - echo "hi"
  - curl -X GET http://localhost:8080/#dashboard -I
```

 I believe its an issue with my account.

**Comment by lekhab** [comment]
@RobertHerhold: do you mind if I remove your dedicated host while I test this out? Or could you see if you are facing the same issue when you don't use a dedicated host?

**Comment by RobertHerhold** [comment]
Feel free to remove it. I actually un-provisioned the VM a few weeks ago.

**Comment by lekhab** [comment]
@RobertHerhold: I removed the dedicated nodes and your builds are no longer timing out.  

Can you try and re-run the build after uncommenting the mongodb lines?

https://app.shippable.com/builds/55aea7ed0740160b00e2bc21

**Comment by RobertHerhold** [comment]
@lekhab It works great, thanks for the help!
