### ISSUE TITLE
Build process is totally hang

### ISSUE THREAD

**Issue by mustela** [Shippable/support#1688]
A built has been triggered an hour ago and I only have: 

`Waiting for logs...` 

https://app.shippable.com/builds/55a9184d2434f00c00d16ab1

**Comment by manishas** [comment]
@mustela I don't see any builds waiting.... one build is in processing state. I see you canceled a few an hour ago, so we'll take a look and see if we find why those builds didn't start.

**Comment by mustela** [comment]
@manishas yes I had to cancel them all and trigger the builds again which btw is taking a lot https://app.shippable.com/builds/55a92ab7ca4deb0c008ea4f6

**Comment by lekhab** [comment]
will close this out as an old issue. If there are any recent builds facing any issues, will open a new issue.
