### ISSUE TITLE
 Error: Invalid version specified with $PGCLUSTER

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#1689]
I have a custom image with postgres installed.
I create a new local container and start postgresql.
Work fine!

Now, I added to my .shippable.yml file my custom-image with postgres and same command to start postgresql.

Shippable create a new build and now I have next error:
`Error: Invalid version specified with $PGCLUSTER`
![error shippable](https://cloud.githubusercontent.com/assets/6644187/8758050/4313b130-2ca5-11e5-9ed9-5156d452fa67.png)

I don't know why shippable set $PGCLUSTER variable to custom images.

**Comment by geekazoid** [comment]
I'm experiencing this issue as well, but in different situation:

part of my `shippable.yml`:

```
  # install and launch postgres
  - apt-get install -y wget
  - apt-get install -y libpq-dev
  - apt-get install -y postgresql postgresql-contrib
  - echo "host all all localhost trust" > /etc/postgresql/9.1/main/pg_hba.conf
  - echo "local all all trust" >> /etc/postgresql/9.1/main/pg_hba.conf
  - service postgresql start
  - createuser -s root -U postgres
  - psql --version
```

the output:

```
  apt-get update
  apt-get install -y wget
  apt-get install -y libpq-dev
  apt-get install -y postgresql postgresql-contrib
  echo "host all all localhost trust" > /etc/postgresql/9.1/main/pg_hba.conf
  echo "local all all trust" >> /etc/postgresql/9.1/main/pg_hba.conf
  service postgresql start
  createuser -s root -U postgres
Error: Invalid version specified with $PGCLUSTER
```

**Comment by mspanc** [comment]
+1

**Comment by lekhab** [comment]
@moylop260, @mspanc - Apologies for the delay in getting this resolved. We have an open bug internally for this. Could you please use the following workaround until we get the bandwidth to resolve this?

In the env section of your YML, unset PGCLUSTER by adding the line below:

```
env:
 - export $PGCLUSTER=""

```

**Comment by lekhab** [comment]
@moylop260, @mspanc, @geekazoid: this has been fixed now. The builds should no longer fail with the PGCluster invalid version error. marking this resolved.  Please let me know if you are facing any further issue.

**Comment by moylop260** [comment]
@lekhab 
Thank you.

==Offtopic==
Now I have a new error:
`createdb: could not connect to database template1: FATAL: the database system is starting up`
Do you know a similar case with this error?
I execute next script to start postgresql:
`sudo su -c "sudo -u postgres /usr/lib/postgresql/9.3/bin/postgres -c "config_file=/etc/postgresql/9.3/main/postgresql.conf" > /tmp/pg.log 2>&1`
