### ISSUE TITLE
Is there any way to check the output data expected from database when the test case is executed? 

### ISSUE THREAD

**Issue by ils-rachna** [Shippable/support#1690]
My issue is, when ever we run test cases by putting some static data in it; the test gets executed and gives out result but it doesn't connects to the database. Then how we will come to know that weather the service is fetching correct data or not.

Thanks

**Comment by lekhab** [comment]
@ils-rachna - sounds like the question is related to the internals of your project and how test cases need to be written. If there is a specific build we can help with, please paste the build link here and we can help you further. You should be able to view the console logs to figure out the progress of the build.
