### ISSUE TITLE
Extract file from container; publish as binary asset to GitHub release

### ISSUE THREAD

**Issue by garthk** [Shippable/support#1692]
I need to run a task in a Docker container and extract the result, e.g.:

```
set -x
docker build -t $TAG .
CID=`docker run -d $TAG`
docker logs -f $CID
docker cp $CID:$OUTPUTFILE .
```

How do I do this with a pre- or post-CI Docker build? The documentation doesn't make it clear whether Shippable can conclude a build by extracting build artifacts and [post it to a GitHub release](https://github.com/quantum/shippable-utils/blob/master/github-release.sh).

**Comment by DavidGDragon** [comment]
We've released a new build system, you can review the revised YML format here http://docs.shippable.com/ci_configure/

**Comment by manishas** [comment]
Closing this since it has been answered.
