### ISSUE TITLE
GO Versions

### ISSUE THREAD

**Issue by Nalum** [Shippable/support#1695]
I'm trying to run tests on a go project and have added the following versions:
```
language: go

go:
  - 1.4
  - release 
  - tip
```

The problem I'm encountering is the following for both `release` and `tip`:

![shippable-error-01](https://cloud.githubusercontent.com/assets/384180/8773753/99119d10-2ece-11e5-814e-9fd0c2d82a5b.png)

**Comment by manishas** [comment]
we support the following versions for go: 

1.1
1.2
1.3
1.4
1.5
