### ISSUE TITLE
Download console logs not allowed

### ISSUE THREAD

**Issue by xherriot** [Shippable/support#1696]
Hello,

I can not download the console logs:
```
{"id":3000,"message":"route permission does not match systemRoles","methodName":"validateCaller|_setSystemRoles"}
```

It seems to be the same for all my builds.
It worked fine few days ago.

Thanks.

**Comment by lekhab** [comment]
@xherriot: can you please point me to a build link with the problem?

**Comment by dennissugar** [comment]
I am having the same problem:

https://app.shippable.com/builds/55ad42d516bc8f0c00664aa0

**Comment by lekhab** [comment]
following up

**Comment by xherriot** [comment]
https://app.shippable.com/builds/55ad2a22b925f20b00601a41

**Comment by pigfoot** [comment]
the same here
https://app.shippable.com/builds/55af7b3885656f0b00925360/1/console/download

**Comment by dennissugar** [comment]
Is there an update on this?

**Comment by lekhab** [comment]
@dennissugar, apologies for the delay - we had to deploy a fix. Can you please try again and let me know if you are running into this now? 

@pigfoot, @xherriot - this should be fixed for you as well. please confirm.

**Comment by dennissugar** [comment]
It's working for me now. Thanks.

**Comment by xherriot** [comment]
Good for me too, thanks !
