### ISSUE TITLE
What could be the reasons why we are not triggering a build for Pull Requests on Bitbucket?

### ISSUE THREAD

**Issue by shamasis** [Shippable/support#1699]
Our shippable integration with Bitbucket is working just fine, except that no build is triggered when Pull requests are sent or updated. What would be a way to debug this? Could it be any issue that we caused during configuring shippable from our end?

**Comment by lekhab** [comment]
@shamasis: PR webhook builds on Bitbucket are not supported currently. There is an open feature request for this here - https://github.com/Shippable/support/issues/237. Please follow updates on that issue. 

Linking this to the feature request and closing.

**Comment by manishas** [comment]
To add some context, bitbucket did not support webhooks for pull requests builds until very recently. 
They recently made some changes to their API and now looks like they've added support. This is high on our priority list and we will address this as soon as we have the bandwidth to work on it.

**Comment by shamasis** [comment]
That makes sense. I guess, until the integration is made, the PR build section on BB repositories could either be disabled or a notice posted so that we don't bother you with support questions. :-)

Looking forward.
