### ISSUE TITLE
Builds taking too long and not working sometimes

### ISSUE THREAD

**Issue by kellyodonovan** [Shippable/support#1700]
This is happening far too often recently.

Builds can take up to an hour or sometimes longer.

Please see recent builds:
![screen shot 2015-07-21 at 11 18 01 am](https://cloud.githubusercontent.com/assets/9378953/8798574/2ab20f94-2f9b-11e5-9dd4-bc7099c4153e.png)

We pay for your service and of late it's not been acceptable.

Could somebody please look into our case?

**Comment by rageshkrishna** [comment]
@kellyodonovan We're looking in to this. I'll update this issue as soon as I have more details.

**Comment by pelegb** [comment]
We're having the same issue. Our build is stuck on "Waiting for mysql to start ..."

**Comment by naveensky** [comment]
My builds are getting failed/stuck. 

https://app.shippable.com/builds/55ae563bdd1c9a0b00f273a8

**Comment by rageshkrishna** [comment]
We're seeing some performance issues on some of our minion hosts. This is manifesting as mysql start errors on builds running on those hosts. We're now taking these hosts out of service. I'll update this issue as we make progress on this.

**Comment by phagunbaya** [comment]
+1 on builds taking more time than before.

**Comment by lekhab** [comment]
this has been resolved now. please let us know if you still facing issues on these builds.

**Comment by phagunbaya** [comment]
Looks better now. Thanks !
