### ISSUE TITLE
Builds hang on "Waiting for mysql to start..."

### ISSUE THREAD

**Issue by sigvef** [Shippable/support#1701]
All builds seem to hang on "Waiting for mysql to start..." during `start_services`. Mysql is not specified as a service in `shippable.yml`, and since [".. services are turned off by default .."](http://docs.shippable.com/yml_reference/#services) it should not try to start in the first place, as far as I can tell.

Here is an example of a build failing: https://app.shippable.com/builds/55ae4dbcbb6b0b0c0060a1ef (login required / non-public).

**Comment by sigvef** [comment]
https://github.com/Shippable/support/issues/564 contains previous discussion about mysql starting without being specified in `shippable.yml`, for reference.

**Comment by rjferguson21** [comment]
We are also experiencing this issue.

**Comment by simensen** [comment]
This is quite problematic for us. If it was just the 10 seconds lost to running MySQL and PostgreSQL that would be one thing, but we are seeing this  "Waiting for mysql to start..." problem several times a day and we're not even using the system super heavily yet. Is there something wrong w/ one of the minion default images that causes this?

**Comment by juanpabloaj** [comment]
I have the same problem

**Comment by lekhab** [comment]
this is now resolved. please let us know if you are still seeing the mysql errors in your builds.

**Comment by rjferguson21** [comment]
Is there any recommendation about ensuring the services are off by default?  There seems to be some confusion around why mysql was being run in the first place.

**Comment by manishas** [comment]
We only start some services automatically if you use our default image. 

If you use your custom docker image or provide a Dockerfile that is built each time, we will not start anything automatically. You can also use our of our barebones language specific images - check out the build image section of the language you're using at http://docs.shippable.com/languages/

**Comment by sigvef** [comment]
> this is now resolved. please let us know if you are still seeing the mysql errors in your builds.

Thanks! The mysql errors are gone.
