### ISSUE TITLE
Unable to disable docker images after initialing enabling

### ISSUE THREAD

**Issue by michaelcho** [Shippable/support#1703]
We tried to enable cache container and docker images using Project Settings. This did not work out too well for us, so I then tried to "undo" this by disabling cache container and docker images.

However it displayed an error message - http://www.piktorious.com/shots/e444a3

And our tests are also unable to run, since it now keeps trying to pull from docker - http://www.piktorious.com/shots/ccdf93

**Comment by manishas** [comment]
To clear all docker related project settings, you can click on the trash icon just under cache container in the project settings section. Let me know if that works for you. Thanks!

**Comment by michaelcho** [comment]
Yes clearing all project settings allows tests to run now, thank you.
