### ISSUE TITLE
Builds are stuck in queue and minions appear full even if no build is actually running

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1706]
https://app.shippable.com/subscriptions/5480429dd46935d5fbbf5213

Minions usage is reported at 4/4. Builds are starting to pile up in queue.
No build is running.

**Comment by rageshkrishna** [comment]
We're looking in to this. I'll update this issue as soon as I have more details.

**Comment by pmoust** [comment]
No longer relevant.
