### ISSUE TITLE
Pushing to GCR causes 403 "Access Denied"

### ISSUE THREAD

**Issue by donmasakayan** [Shippable/support#1708]
In the final step of the build process when we're about to push the container to GCR, I'm getting either this error ([Build] (https://app.shippable.com/builds/55af5ca285656f0b006cf3ca)):
```
Sending image list
Error: Status 403 trying to push repository friendly-neighbors/api: "Access denied."
```

OR this error ([Build] (https://app.shippable.com/builds/55af64ec85656f0b007cbece)):
```
Sending image list
Please login prior to push:
Username: EOF
```

In GCR's documentation, [they do mention something about this here](https://cloud.google.com/tools/container-registry/?hl=en_US&_ga=1.128611918.357180263.1429696607#access_denied). Something about docker 1.7.x breaking the way docker writes credentials.

Other than that, I've set up GCR integration correctly.

Please advise. Thanks.

**Comment by rvrignaud** [comment]
Hello,
It seems I'm getting this behavior if I try to push to another domain that gcr.io (ie eu.gcr.io is failling but gcr.io is OK).

Did you push to gcr.io ?

**Comment by donmasakayan** [comment]
Interesting. I'm indeed pushing to `us.gcr.io`. I'll test out pushing to `gcr.io` tomorrow.

**Comment by donmasakayan** [comment]
Update: Pushing to `gcr.io` worked. So it seems that there's an issue with using the other domains.

**Comment by lekhab** [comment]
following up on why there are intermittent Access Denied issues with using GCR.

@donmasakayan - does using ```gcr.io``` resolve your issue?

**Comment by rvrignaud** [comment]
@lekhab would that be possible to add the feature request to be able to push to other domain (like eu.gcr.io ?). Using different domain implies to use a bucket in a different region.

**Comment by donmasakayan** [comment]
@lekhab Yes, using `gcr.io` worked for me.
