### ISSUE TITLE
CPU leak during archiving step

### ISSUE THREAD

**Issue by xherriot** [Shippable/support#1709]
Hello,

During the build, the console works fine but when arrived to the archiving step, my CPU goes to 100% (and ram x2), (Firefox does not respond) until the end of the step.

Before & after archiving:
<img width="547" alt="screen shot 2015-07-22 at 12 35 00" src="https://cloud.githubusercontent.com/assets/5094797/8823568/2ca0b476-306e-11e5-8db2-151f14325ac3.png">

During archiving:
<img width="555" alt="screen shot 2015-07-22 at 11 24 33" src="https://cloud.githubusercontent.com/assets/5094797/8823459/463f6bb2-306d-11e5-9129-4add6ddab19c.png">

Firefox 39 / Mac 10.9.5

**Comment by manishas** [comment]
We have deprecated archiving as a standard feature and will instead provide a how-to guide explaining how you can set up archiving for your artifacts. closing this issue.
