### ISSUE TITLE
unauthorized access to build route

### ISSUE THREAD

**Issue by nicdex** [Shippable/support#1710]
I keep getting build not found when trying to see the result of a build that failed.

{"id":3000,"message":"Unauthorized access to build route","methodName":"validateCaller|_checkPublicRoute"}

last build id is 55afd9f658c0a30b0086f2a4

**Comment by nicdex** [comment]
Just noticed that it does that error with EVERY BUILD for ALL PROJECTS in our shippable account.

**Comment by lekhab** [comment]
on it..

**Comment by lekhab** [comment]
this is resolved now. are you able to access your builds?

**Comment by nicdex** [comment]
yes thank you.
