### ISSUE TITLE
HHVM Seriously Out of Date

### ISSUE THREAD

**Issue by jwriteclub** [Shippable/support#1713]
Running the following in before_script

`- php --version`

During a run with hhvm selected indicates that the current hhvm version is

```
HipHop VM 3.3.1 (rel)
Compiler: tags/HHVM-3.3.1-0-ge0c98e21167b425dddf1fc9efe78c9f7a36db268
Repo schema: f53e1743f31a2dee70c46aa66fb1b321c3e97c10
Extension API: 20140829
```

Whereas the most recent version of HHVM is 3.8.0. There's been a ton of changes in the meantime, and a number of projects which pass on recentish HHVM (3.6+ tested on an amazon VM) fail with such an old version.

In addition, PHP 5.6 is currently at 5.6.0, while 5.6.11 is available.

What are the chances of getting some updates to these runtimes?

**Comment by RobertHerhold** [comment]
The MongoDB and RethinkDB services are also considerably out of date.

The MongoDB service on Shippable is currently running 2.4, whereas the current version is 3.04

**Comment by cur3n4** [comment]
+1 to upgrade RethinkDB

**Comment by manishas** [comment]
We have new build images with latest versions of services in our [drydock repo on docker hub](https://hub.docker.com/u/drydock/). Explanation of nomenclature [is here](http://docs.shippable.com/ci_configure/#setting-your-build-image)
