### ISSUE TITLE
NPM Git Head error

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1714]
npm ERR! Failed resolving git HEAD (git@github.com:PushSpring/s3-stream-upload.git) fatal: bad object bb6b71e31c43017cfbd3ee964e4c99ab1a97ed0a
npm ERR! Failed resolving git HEAD (git@github.com:PushSpring/s3-stream-upload.git)
npm ERR! Error: Command failed: fatal: bad obj

blowing away node_modules locally and running npm install completes successfully.

My reference in package.json:
"s3-stream-upload": "git+ssh://git@github.com:PushSpring/s3-stream-upload.git#master",

Have turned off caching for project
Have sent reset_minion
Have validated I can pull that repo
Have blown away node_modules and npm installed successfully on local box

It is almost as though shippable has a cached pointer of the commit_sha that represents master

**Comment by rageshkrishna** [comment]
@chriskinsman It looks like our nodejs image is stuck on a really old version of npm. Can you try doing an `npm install npm -g` as the first `before_install` step to see if it helps?

If it doesn't, please send me your full shippable.yml and package.json so I can try to repro this.

Thanks!

**Comment by chriskinsman** [comment]
Still hit with issue.

@rageshkrishna Where should I send the files?  This has all of our deployments blocked right now

**Comment by chriskinsman** [comment]
@rageshkrishna Also just discovered it appears the node version is being ignored in my shippable.yml

In shippable.yml:
node_js: 0.10.21

However running 
node --version 

in before install yields 0.10.37

**Comment by chriskinsman** [comment]
Using nvm to force to 0.10.21 didn't alter the issue at all

**Comment by chriskinsman** [comment]
I think I found the issue.  One of the dependent packages in our package.json had a reference to a commit sha in it's package.json and that referenced a commit sha that no longer existed likely due to a rebase/squash.  I am closing.  Thanks for your help.
