### ISSUE TITLE
Deployment Key / SSH Key for Account not found or is not displayed

### ISSUE THREAD

**Issue by bastianwegge** [Shippable/support#1717]
When I'm going to my user and settings page, the field for deployment key is empty. I'd love to set up continous deployment to heroku, but it's not possible without it. And I don't want to go the dirty way using a token.

**Comment by lekhab** [comment]
following up on the fix.

**Comment by bastianwegge** [comment]
Don't know if it helps, but in the `script` part it's looking for some project_rsa for the ssh-agent. Trying to access it or a public part fails (the public part doesn't seem to exist).

**Comment by bastianwegge** [comment]
Don't know what you did, but now the ssh key seems to be available. Thank you!
