### ISSUE TITLE
Running parallel processes hangs a build

### ISSUE THREAD

**Issue by rudism** [Shippable/support#1718]
The latest build I have seen this in: https://app.shippable.com/builds/55b2b63e432f1f0c00fd0b32

In my build I'm trying to call a shell script that runs several test suites in parallel. I've used a few different methods, including spawning the processes with `&` and using the `wait` command, using GNU Parallel, and using `xargs -P`. In every case, after the command finishes, the build hangs and eventually times out. For example, calling a script that looks something like any of these seems to hang the build:

    #!/bin/sh
    testrunner --class class1 &
    testrunner --class class2 &
    wait
or

    #!/bin/sh
    parallel testrunner --class {} ::: class1 class2
or

    #!/bin/sh
    echo class1 class2 | xargs -n1 -P2 testrunner --class

I see the output from each of the commands in every case up to the completion of the final process, but then all output stops and the build does not seem to progress any farther.

The strange thing is that I have a notifier that runs in the `after_success` and `after_failure` blocks, and the jobs that hang will notify me that they have succeeded (meaning the `after_success` block is being run, even though the job is still listed as processing and eventually times out).

**Comment by lekhab** [comment]
@rudism: are you still running into this? from your description, the build appears to be waiting for some user input. I see some of your recent builds have been succeeding. please let me know if this is still occurring.

**Comment by rudism** [comment]
I don't believe it was related to user input... running the same shell scripts manually outside the context of shippable worked just fine.

I ended up copying the `parallel` and `xargs` calls directly into the `shippable.yml` file instead of calling them from a shell script which seemed to fix the issue.

**Comment by manishas** [comment]
Closing since there is nothing actionable for us to do here.
