### ISSUE TITLE
Can't access my formation service

### ISSUE THREAD

**Issue by magnus-larsson** [Shippable/support#1720]
I can no longer access my service in my formation:
(worked fine a couple of days ago)

<img width="575" alt="screen shot 2015-07-25 at 11 50 13" src="https://cloud.githubusercontent.com/assets/1313727/8888945/9866a268-32c3-11e5-9241-14ba8022e0ec.png">

<img width="819" alt="screen shot 2015-07-25 at 11 50 49" src="https://cloud.githubusercontent.com/assets/1313727/8888942/80a1f9e8-32c3-11e5-8624-d82e7cff4c49.png">

(I don't know if it is related but the console says I have 3 containers up and running, while I only have started one service in my formation?)

I just restarted the service and Tomcat reports no problems to startup:

<img width="812" alt="screen shot 2015-07-25 at 11 53 31" src="https://cloud.githubusercontent.com/assets/1313727/8888955/f3542ff6-32c3-11e5-8d41-087430d4dc94.png">

But when I try to access it with curl or just connect using telnet I get connection refused errors:

    $ telnet mt-fo-lb-168423950.us-east-1.elb.amazonaws.com 30507
    Trying 54.175.216.126...
    telnet: connect to address 54.175.216.126: Connection refused
    Trying 54.152.137.164...
    telnet: connect to address 54.152.137.164: Connection refused
    telnet: Unable to connect to remote host

Hope you can help!

Regards,
Magnus.

**Comment by avinci** [comment]
@magnus-larsson sorry about this. We had a problem with our auto-load balancer config and ended up corrupting some of the proxies. I think your pod has that problem and we must have missed it in out query.

Here is what you need to do to fix it.

* from the formations status page, click on the service which will take you to the service status page
* in the bottom panel where it shows you details of the current version running, there is a `+`  at the top which used to created a new deployment. click on that
* now you should see your image and port opened. toggle Open ON to OFF. Deploy the service with routing being turned off. (this will automatically clean up the routing rules)  
* after 20-30 seconds repeat the process, only this time toggle OPEN to ON. If your need it external, then turn EXTERNAL to ON. Deploy it and you should have routing back up again

Please let me know if you have any questions and I apologize the inconvenience.

**Comment by magnus-larsson** [comment]
Tanks for the help, but I still get "Connection refused".

I can see that the port is changed after following your instruction and I can see that tomcat restarts ok in the logs but I still get "Connection refused".

...and the console still reports: "Container Usage: 3 of 1" (don't understand that message...)

Any other idea?

**Comment by avinci** [comment]
Do you mind sending me the url from the formation status screen. 



—

**Comment by magnus-larsson** [comment]
Here it comes:

<img width="415" alt="screen shot 2015-07-26 at 08 04 34" src="https://cloud.githubusercontent.com/assets/1313727/8892774/1f9542cc-336d-11e5-93b3-635b96eccd56.png">

A curl-request without authentication should result in a 401 like:

    $ AWS_HOST=mt-fo-lb-168423950.us-east-1.elb.amazonaws.com
    $ AWS_POST=10984
    $ curl "https://$AWS_HOST:$AWS_PORT" -ik
    HTTP/1.1 401 Unauthorized

But it currently instead results in a "Connection refused".

Regards,
Magnus.

**Comment by manishas** [comment]
@magnus-larsson apologize for the lack of clarity, what we need is the URL of your Formations status page. 

You can go to your dashboard and select your Formation name from the Formations dropdown -
![screen shot 2015-07-26 at 10 03 09 am](https://cloud.githubusercontent.com/assets/2983749/8894947/914144d8-337d-11e5-93d0-2b05011545b7.png)

You will see your Formations status page. We need the URL for this status page (it looks like this - https://app.shippable.com/subscriptions/55b2629bf6ab630b004e4e5f)

Thanks!

**Comment by avinci** [comment]
@magnus-larsson  Couple of things you might want to change on your script
* typo on AWS_POST. It has to be AWS_PORT i think
* second, you are using https and it should be http

I did not realize those errors or your script and ended up redeploying to test. 

If i deploy `magnuslarsson/az-ip-api-server:latest` then I get the following out put

```
$ AWS_HOST=mt-fo-lb-168423950.us-east-1.elb.amazonaws.com
$ AWS_POST=59406
$ curl "http://$AWS_HOST:$AWS_PORT" -ik

HTTP/1.1 504 GATEWAY_TIMEOUT
Content-Length: 0
Connection: keep-alive

```

If i deploy `magnuslarsson/az-ip-api-server:master.15` then I get the following out put

```
$ AWS_HOST=mt-fo-lb-168423950.us-east-1.elb.amazonaws.com
$ AWS_POST=59406
$ curl "http://$AWS_HOST:$AWS_PORT" -ik

HTTP/1.1 404 Not Found
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Date: Sun, 26 Jul 2015 17:24:58 GMT
Expires: 0
Pragma: no-cache
Server: Apache-Coyote/1.1
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
WWW-Authenticate: Basic realm="Spring"
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
Content-Length: 0
Connection: keep-alive
```

This confirms that routing is working as we are getting different responses for different versions of the container. Is there a route that your API is listening to so that we can get an `OK` message from? 

Let me know if you are still able to hit the container..

**Comment by magnus-larsson** [comment]
Great, thanks!

Sorry for not spelling PORT correctly ;-)

Yes, deploying master.15 now works fine so the routing is working again!

Using https it intentionally, the latest docker image use https.
I was not aware that https is not supported by the infrastructure.

Do you have any link to information how to use https in your infrastructure?
Or should I register a new issue regarding that?

**Comment by avinci** [comment]
We are working on SSL termination and its pretty close to launch. Give me a couple of days and I will get back to you on the exact date of launch

**Comment by magnus-larsson** [comment]
Great, thanks!

**Comment by avinci** [comment]
we have moved away from managing our own formations. We are piggy backing on all the container services out there. let us know if this is of interest to you
