### ISSUE TITLE
Pushing code to bitbucket no longer triggers new builds correctly

### ISSUE THREAD

**Issue by magnus-larsson** [Shippable/support#1721]
While working on resolving issue #1720 I pushed some code changes to the master branch in my BitBucket project:

<img width="1129" alt="screen shot 2015-07-26 at 22 43 04" src="https://cloud.githubusercontent.com/assets/1313727/8895848/9b9c0d12-33e8-11e5-9954-33d8f3faec9b.png">

But no build were triggered so I tried to reset the webhook using the Reset button on the project page, https://app.shippable.com/projects/55a37e50edd7f2c0526982b0 , and then performing a new push to BitBucket.

A build was then triggered but not on the latest commit in my master branch:

<img width="1462" alt="screen shot 2015-07-26 at 22 44 15" src="https://cloud.githubusercontent.com/assets/1313727/8895857/feb48d48-33e8-11e5-8496-315dc447c517.png">

The build is based on commit 47176a8 instead of the latest 9cbe07b.

Can you help me to sort out what is going wrong?

Regards,
Magnus.

**Comment by lekhab** [comment]
@magnus-larsson: Bitbucket did not support webhooks for PR builds until very recently - so we were unable to automate PR builds for Bitbucket. They did launch this support recently and we now have it on our backlog to support this. This feature request is being tracked in #237. Please follow that issue for updates on this feature.

**Comment by magnus-larsson** [comment]
Thanks for helping me out! 

I'm not using PR, just ordinary push to the master branch. It has worked flawless until some day ago when it simply stopped to work...

Hope you can help me to get it working again!

Regards,
Magnus.

**Comment by lekhab** [comment]
my bad! 

so it looks like we are having trouble parsing your YML. The error I see against these builds is "Error parsing shippable.yml". Can you please either send me your YML to lekha@shippable.com or check if your YML is valid at http://www.yamllint.com/ ?

**Comment by magnus-larsson** [comment]
Thanks a lot!

You are right, my shippable.yml is no longer valid :-(

http://www.yamllint.com/ complains about the line (i have it in the after_success section):

      - sed -i.org 's/baseUri: https:\/\/localhost:8080\/api/baseUri: \/api/' src/main/resources/public/raml/az-ip-api.raml

It runs fine when I test it locally, but http://www.yamllint.com/ reports:
 
    (<unknown>): mapping values are not allowed in this context at line 22 column 66

How can I make the `sed` command to work in the shippable.yml - configuration?
(besides placing it in a shell script in my git-repo...)

I also wonder how I can pick up future build that fails on "Error parsing shippable.yml". Since these builds don't show up in my console I can't see them...

**Comment by lekhab** [comment]
Can you try by removing the escape characters and adding quotes to the command? I was able to do a simple sed replace using the format below..

``` "sed -i.org 's/baseUri: https://localhost:8080/api/baseUri: /api/' src/main/resources/public/raml/az-ip-api.raml" ```

**Comment by magnus-larsson** [comment]
Thanks for the help with the `sed`-command!

My final question is regarding how I can pick up future build that fails on "Error parsing shippable.yml". Since these builds don't show up in my console I can't see them...

Is there another way for me to see these failed builds and whatever reason that prevented them to show up in my console (e.g. a broken shipping.yml file)?

**Comment by lekhab** [comment]
@magnus-larsson: Error notifications are currently only visible when you run a manual build.  We do realize this is something that is critical for our users to debug failed webhook builds themselves - there is an internal issue that's open to resolve this.

**Comment by magnus-larsson** [comment]
Ok, great! Thanks for the info, I'll close this issue.
