### ISSUE TITLE
Can't build Docker image with FROM poiting to private GCR image

### ISSUE THREAD

**Issue by rvrignaud** [Shippable/support#1723]
Hello,

We use GCR integration for our Docker builds (post-CI with image push).
For images with a FROM (parent image) that point to a public image (like ubuntu:14.04) it works fine.
Whoever if we try to use a FROM with a private GCR image we get a 403 Access Denied.
(like this build https://app.shippable.com/builds/55b6231f67a1d80b00778f78).

**Comment by lekhab** [comment]
looking into this..

**Comment by rvrignaud** [comment]
Hello @lekhab. Did you manage to reproduce the problem ?

**Comment by ragsden** [comment]
@rvrignaud : We were able to repro the issue and we are debugging the issue. This issue seems to be occurring only with Docker build and works fine when we execute docker pull of the private image. We will keep you posted on the progress. Sorry for the inconvenience.

**Comment by Darune** [comment]
Any news on this?,
It would considerately fasten my build time to have a private base GCR image.

**Comment by rvrignaud** [comment]
Hello @ragsden,
Did you make any progress on this one. This is really annoying for us.

Thanks !

**Comment by manishas** [comment]
This should not happen any more. Please reopen if this is still a problem.
