### ISSUE TITLE
Can't see docker / image options for Project

### ISSUE THREAD

**Issue by david-anyvan** [Shippable/support#1725]
Our account was set up by an employee who has now left the company, and today as he was removed from our github account. Since that point the build appears to be trying to use docker and in doing so does not finding the image. As far as we can tell the manager is the (or a) subscription owner - yet we can't see any container options for our project / dashboard. Would that original account have had options to add extra privileges to the other users?

**Comment by lekhab** [comment]
@david-anyvan: looks like the project you are trying to build does not have a hub integration set up in Shippable anymore - so we are unable to access docker to pull the build image. 

1. Go to Account Settings and link your shippable account to the docker hub account by providing the docker hub login credentials to use.
2. Under your project settings -> project integration, select the docker hub integration you have created in (1)

Documented here: http://docs.shippable.com/docker_registries/#pull-images-from-docker-hub

Please let me know if you have any questions while doing this.

**Comment by lekhab** [comment]
Closing this. please let me know if you have any further questions and I can re-open.
