### ISSUE TITLE
App isn't loading

### ISSUE THREAD

**Issue by mdlampi** [Shippable/support#1727]
Trying to access a build is timing out. The app says "There is an issue loading the app. Please contact support.".

**Comment by manishas** [comment]
@mdlampi are you still running into this?

**Comment by mdlampi** [comment]
Hi Manisha,

 

Thank you for asking. It seems to be working  at this time.

 

Best regards,

 

Michael Lampi, Senior SDET Lead

Inline image 1

1501 4th Avenue, Suite 2900

Seattle, Washington 98101

425.765.3976 Direct

Level11.com
