### ISSUE TITLE
PHP extension installation

### ISSUE THREAD

**Issue by Green-Cat** [Shippable/support#173]
My builds are failing as the php extensions mongo and intl are not available.
Installing them using pecl doesn't work either (I get "No releases available for package "pecl.php.net/mongo" install failed" when running pecl install mongo).
Note, I do have mongodb itself enabled in services.

**Comment by bitgandtter** [comment]
Im trying to enable extensions on my project https://app.shippable.com/builds/560c4100815c980d0064aa86 and im getting the same error messages

PHP Warning:  PHP Startup: Unable to load dynamic library '/root/.phpenv/versions/5.4/lib/php/extensions/no-debug-non-zts-20100525/apc.so' - /root/.phpenv/versions/5.4/lib/php/extensions/no-debug-non-zts-20100525/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0

even for pecl

/root/fecc05b9-5436-4055-92a6-5fe52e83d2b3.sh: line 84: pecl: command not found

What should i do

**Comment by Sebastien-Meiffren** [comment]
+1 I'm having the same issue.

**Comment by mbrodala** [comment]
I have a working solution in #2086 but it's far from optimal.
