### ISSUE TITLE
builds are very slow and hanging

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1730]
Hi, 

I spent several hours in getting my api deployed but without any luck. Initially it seemed my disk was running out of space which I fixed. My builds, however, are failing and very slow. It takes a quarter to build a simple GO api of 2 MB. 

for example: 
https://app.shippable.com/builds/55b798358425e20b00f51f95

Can you please checkout what's wrong here since this is stopping my deployment.

Ron

**Comment by lekhab** [comment]
@rvdwijngaard: pls let me know if this is still an issue after you have updated the node..

**Comment by rvdwijngaard** [comment]
@lekhab: I have suffered this issue for several hours; my builds were failing at the docker push step because the buildoutput folder did not exist. After some time the problem was resolved without changing anything.

**Comment by lekhab** [comment]
closing this, since the perf issues were addressed.
