### ISSUE TITLE
Possibility of providing anaconda as a base package for Python Builds

### ISSUE THREAD

**Issue by sachuin23** [Shippable/support#1733]

**Comment by sachuin23** [comment]
Closing as I found a similar request already triaged and replied to.

**Comment by manishas** [comment]
@sachuin23 one quick update since the earlier issue was responded to - you no longer need dedicated hosts to use custom images. You can use any custom image you want on our platform - more details at http://docs.shippable.com/docker_registries/

**Comment by sachuin23** [comment]
Thank you so much for quick response!
