### ISSUE TITLE
python 3.4 configuration still uses /root/ve/lib/python2.7 to pip install -r requirements.txt

### ISSUE THREAD

**Issue by macolo** [Shippable/support#1734]
I use the following shippable.yml however still python2.7 is used in the virtualenv and this breaks ````pip install -r requirements.txt`````

````
language: python

build_image: shippableimages/ubuntu1204_python

python:
  - "3.4"
````

It apparently fails to install Pillow and errors out with: ````error: command 'gcc' failed with exit status 1````

What is going wrong?

**Comment by lekhab** [comment]
@macolo: Since you are using the custom python image, you will need to activate the appropriate venv in the before_install section, so the build runs against the correct version of python. You can use $SHIPPABLE_PYTHON environment variable for this.

Documentation on how to use the custom image for python is here:
http://docs.shippable.com/languages/#build-image_5

Here's a sample YML from the docs:

```
language: python

python:
  - 3.4

before_install:
#  set up a virtualenv and activate the python version that you want to use
  - mkdir -p $HOME/bldve/
  - virtualenv -p $SHIPPABLE_PYTHON  $HOME/bldve/
  - source $HOME/bldve/bin/activate

install:
#install the required dependencies
  - pip install -r requirements.txt

script:
  - python test.py
```

Please let me know if this doesn't work for you..

**Comment by macolo** [comment]
Hi Lekha,

This is great, thank you very much!

All the best

Mario

On Fri, Jul 31, 2015 at 2:04 AM, Lekha Bhargavi <notifications@github.com>
wrote:

> @macolo <https://github.com/macolo>: Since you are using the custom
> python image, you will need to activate the appropriate venv in the
> before_install section, so the build runs against the correct version of
> python. You can use $SHIPPABLE_PYTHON environment variable for this.
>
> Documentation on how to use the custom image for python is here:
> http://docs.shippable.com/languages/#build-image_5
>
> Here's a sample YML from the docs:
>
> language: python
>
> python:
>   - 3.4
>
> before_install:
> #  set up a virtualenv and activate the python version that you want to use
>   - mkdir -p $HOME/bldve/
>   - virtualenv -p $SHIPPABLE_PYTHON  $HOME/bldve/
>   - source $HOME/bldve/bin/activate
>
> install:
> #install the required dependencies
>   - pip install -r requirements.txt
>
> script:
>   - python test.py
>
> Please let me know if this doesn't work for you..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1734#issuecomment-126524879>.
>



-- 
Mario Colombo
Senior Product Specialist

Webrepublic AG
Phone: +41 44 542 90 68 <+41445429068>
Mobile: +41 78 941 73 34 <+41789417334>

mario.colombo@webrepublic.com

**Comment by lekhab** [comment]
Glad that worked :-)
