### ISSUE TITLE
Builds waiting for too long

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#1735]
Our builds are not getting started, and showing "waiting" status.

**Comment by lekhab** [comment]
can you provide the link to a waiting build, pls?

**Comment by phagunbaya** [comment]
@lekhab https://app.shippable.com/builds/55b94b5000fec00b00e9d38a

**Comment by lekhab** [comment]
looks like the message was stuck in our queue. I canceled the stuck one and re-ran the build and it's now processing successfully. 

will follow up on why this might have happened and keep a look out for any repeat issues of this kind.

**Comment by phagunbaya** [comment]
Appreciate the help.
