### ISSUE TITLE
php Multiple file intregation

### ISSUE THREAD

**Issue by ils-miteshs** [Shippable/support#1736]
There is no steps for how to deal with multiple lib and files. How should I integrate my php lib in test case. So that I do not have to right same code twice. I want test case to check db query also is it required every time I have to use create and drop table commands. How should I include multiple files for test cases.

**Comment by lekhab** [comment]
@ils-miteshs - Apologies if I misunderstood your question.  
If you are asking about how to write php test cases - please use the php reference manual here: https://phpunit.de/getting-started.html & https://phpunit.de/manual/current/en/index.html. 

We do have a sample PHP code to illustrate how you can build and run those tests in Shippable. Details and links to samples are available in our documentation pages here:  http://docs.shippable.com/languages/#php
