### ISSUE TITLE
{"id":2100,"message":"No build found","methodName":"validateCaller|_checkAccessLevel"} 

### ISSUE THREAD

**Issue by sammountford** [Shippable/support#1737]
I'm using a private BitBucket Repo and have added shippable.yml to a feature branch and I'm running the build on that branch and I get the error
{"id":2100,"message":"No build found","methodName":"validateCaller|_checkAccessLevel"}

**Comment by lekhab** [comment]
@sammountford: what's a link to your build or project, please? I can't find it with the github user id you are using..

Also, can you please confirm if your YML is valid here: http://www.yamllint.com/? 

We sometimes see that error when there are YML errors..

**Comment by lekhab** [comment]
Actually, this is a different error.. not to do with YML. 

Did you see the error on Shippable or when you were clicking through an email link? Just confirming if you were logged into Shippable - this is required for us to authenticate you to access a build link.

**Comment by lekhab** [comment]
@sammountford - closing this. please let me know if you are still facing this and I will re-open.

**Comment by mbrodala** [comment]
I can see this error currently when manually triggering builds. All previous builds where just fine.

**Comment by lekhab** [comment]
@mbrodala - this was probably related to the Bitbucket issues earlier today. Are you still facing this? I see one of your recent builds went through completely.

**Comment by mbrodala** [comment]
Yes, the following builds where fine although I had to cancel some of them which where apparently queued due to manual triggering. I'll let you know in case the issue occurs again.

**Comment by rept** [comment]
Getting this error too.  Also I've made 2 commits to Bitbucket that just don't pop up in Shippable.  It seems to be stuck on a certain commit?
