### ISSUE TITLE
Timeout since run start not since enqueue

### ISSUE THREAD

**Issue by stekycz** [Shippable/support#1738]
Sometimes in our projects a build times out. From the data we have collected it looks that the timeout is calculated since the time of enqueue the build. I think the timeout should be calculated since the time the build has started (finished waiting in the queue).

Is it possible or is there some reason why it is not calculated as I described?

**Comment by lekhab** [comment]
@stekycz: Timeout is calculated based on when the build starts to run, not queued. That said, there may be edge cases here that may cause behavior that you are seeing. Do you have examples of builds that have timed out based on queuedTime and not startTime? 

I can take a look to see if there's something specific going on with those builds.

**Comment by lekhab** [comment]
closing this for now. please let me know if there are any specific builds to follow up on and I can re-open.
