### ISSUE TITLE
Force push or fixup does not enqueue a build

### ISSUE THREAD

**Issue by stekycz** [Shippable/support#1739]
I have got a lot of feedback from my developers when they force push to their's branch or create a fixup commit in Git then the build is not enqueued.

Could it be fixed?

**Comment by lekhab** [comment]
@stekycz: can you please add some examples to help us debug? There is no reason why a force push would not queue a build, as far as I know. If you can please provide the link to your project and example commits that did not get queued - I can debug this further.

**Comment by Achse** [comment]
I have found an example this night:

* Here is a failed build: https://app.shippable.com/builds/55b754d9dcc3110c00f6d4b1 (before 4 days)
* Now, I have made rebase the branch 
* I force-pushed the result.
* No build has started.

I have theory: when commit message of the last commit on the tested brach does not change, no test will be started.

**Comment by lekhab** [comment]
@Achse: you are right - we did confirm this. Auto builds relies on Github sending us webhooks. It looks like when there are changes in a rebase, Git gives the latest commit a different commit hash and a webhook is sent. However, if there are no new commits in the rebase, the commit hash remains the same and Github does not send a webhook.  Which kinda makes sense...

Please let me know if there's anything further we can do to help.

**Comment by stekycz** [comment]
Do I understand well that it cannot be fixed on your side because of GitHub? Because GitHub does not send a webhook on force push with the same top commit?

**Comment by lekhab** [comment]
@stekycz - that's correct...

**Comment by stekycz** [comment]
@lekhab Ok, thank you. I will contact GitHub support :-)

**Comment by lekhab** [comment]
will close this for now. Please let me know if you need this to be re-opened for any reason.
