### ISSUE TITLE
[Consolidated] Code coverage enhancements

### ISSUE THREAD

**Issue by epicserve** [Shippable/support#174]
It would be nice if on the coverage tab it showed the source code with hits or misses, when you click on the plus for each file.

Here is a screenshot of the area I'm referring to.

![shippable 2014-05-30 16-10-18 2014-05-30 16-11-38](https://cloud.githubusercontent.com/assets/191620/3136210/01c28838-e83f-11e3-8497-73828d453a66.jpg)

**Comment by manishas** [comment]
I am linking all feature requests related to code coverage enhancements to this issue, so that we can address as much as possible at the same time when we touch this code.

Support to mark build as "UNSTABLE" in low coverage - #198 
code coverage for a pull request only #661
More prominent coverage display #681

**Comment by pwalsh** [comment]
I want to reiterate my original request in #978 : it would be really useful and enables shippable to replace the travis + coveralls combination.

**Comment by fabiocarneiro** [comment]
:+1: ..

coverage badge ASAP please?

**Comment by dennissugar** [comment]
+1

**Comment by velo** [comment]
+1

**Comment by grue** [comment]
+1

**Comment by dandesousa** [comment]
+1 for code coverage badge

**Comment by BenV** [comment]
:+1:

**Comment by caarlos0** [comment]
:+1:

**Comment by rockerhieu** [comment]
+1

**Comment by FlorianLoch** [comment]
Is there any progress with that feature? I would really like to see it implemented as it would save me from using coveralls.io and would really make my ci pipeline slimer.

**Comment by calclavia** [comment]
+1 on this.

**Comment by amondnet** [comment]
+1

**Comment by scottclowe** [comment]
+1

**Comment by clifg** [comment]
+1 on the badge

**Comment by pwalsh** [comment]
@manishas this issue is around 1 year and 9 months old. That is fine, as obviously there are many priorities. I'd just like to ask: is this something you are actually planning to add? If not, it might be better to state that, and then close this issue.

**Comment by harryi3t** [comment]
## We now support
 
### 1. coverage badge
![coverage-badge][1]

### 2. Notification alert (slack/hipchat/email/irc) on low coverage. 
### 3. Support to mark build as "UNSTABLE" in low coverage
![lowcoverage-alert][2]

[1]:https://cloud.githubusercontent.com/assets/5207331/14566885/07cbeb70-034f-11e6-8b54-cbfed13f4202.png
[2]:https://cloud.githubusercontent.com/assets/5207331/14567480/e6842cf4-0351-11e6-8297-d1c6f414cd83.png

Thank you for your patience guyz. Will keep updating this issue about our progress.
Happy Shipping!

**Comment by bensonmiller** [comment]
+1

**Comment by iamed2** [comment]
+1 for line coverage

**Comment by Ryuske** [comment]
As per #1203 is that something you guys have any kind of plan to implement? Currently, code coverage with Shippable is useless for me, which kind of prevents Shippable from being a viable option for me.

Thanks!

**Comment by pacey** [comment]
Any update on the jacoco support?

**Comment by rohitghatol** [comment]
+1 for jacoco

**Comment by jessica-pixvana** [comment]
+1 for jacoco

**Comment by wakingrufus** [comment]
+1 for jacoco

**Comment by manishas** [comment]
Jacoco support was added last week but we're running behind on docs. ETA is early next week. I'll update this thread with a link to docs :)

**Comment by Neal910** [comment]
Hi @manishas , has doc been updated? Thanks.

**Comment by manishas** [comment]
@Neal910 @wakingrufus @jessica-pixvana Well, it look longer than I expected, but we've updated docs for Jacoco:

[Basic Jacoco config](http://docs.shippable.com/ci/languages/java/#advanced-test-reports)
[Jacoco tutorial with sample](http://docs.shippable.com/tutorials/ci/integrations/codeCoverage/usingJacoco/)

Let us know any feedback :)

**Comment by magwas** [comment]
The "Jacoco tutorial with sample" link leads to a page looking awfully, and without relevant information.
There are actually a lot of related pages looks the same...

**Comment by manishas** [comment]
@magwas hmm I think the link was wrong?

Here is the correct link: http://docs.shippable.com/tutorials/ci/code-coverage-jacoco/

Does this still look awful at your end?

**Comment by Neal910** [comment]
Hi @magwas , thanks for your update. Actually, I have implemented code coverage by Jacoco without documentation, but experiment. And the documentation looks good in my side.
