### ISSUE TITLE
Older build for the same pull request does not die on new commit

### ISSUE THREAD

**Issue by stekycz** [Shippable/support#1740]
We have found an issue that creates a lot of builds in the queue which makes a lot of delays. It can be done by forgotten change which should be in the pull request. I know that it can be killed manually but we usually want to kill previous build.

Is it possible to make it? Or is it possible to make it configurable per project?

**Comment by manishas** [comment]
This is not on our roadmap for now, so closing this. If there is enough customer feedback around this, we'll reopen and address it.
