### ISSUE TITLE
npm issue with gulp-imagemin/gifsicle

### ISSUE THREAD

**Issue by maazghani** [Shippable/support#1742]
### npm issue with gulp-imagemin/gifsicle
We have builds that do not fail in our local environments, but are failing on shippable, randomly. The build succeeds and fails in ways that we can not consistently reproduce.

The exact error that we are getting that breaks the build is:
```
events.js:85
throw er; // Unhandled 'error' event
^
Error: spawn /root/workspace/src/github.com/ottemo/karigran/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
at exports._errnoException (util.js:746:11)
at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
at child_process.js:1144:20
at process._tickCallback (node.js:355:11)
```

### What I've tried:
* Adding `npm cache clean` to the shippable.yml
* Clearing the cache from the Project Settings

Issue seems to be specifically with the gulp-imagemin package's gifsicle dependency, but I've updated the version of gulp-imagemin to the latest to no avail.

Again to reiterate, this issue does not happen in our local environments.

The issue could be with [Node 2.13.2 but not with 2.13.1](https://github.com/npm/npm/issues/8982).

Any guidance would be appreciated.

**Comment by djmrr** [comment]
hmmmmmmm

**Comment by Tapefabrik** [comment]
We are struggeling with the exact same error :/ i manually compile images on my local machine to upload them manually afterwards every time. Any hints?

**Comment by DavidGDragon** [comment]
You can try using a different version of npm by adding `sudo npm install -g npm@2.12.1` (or w/e version you want) to `before_install:` section of the shippable.yml and see if that helps the issue.

**Comment by acrontum** [comment]
Worked for us. Thanks @DavidGDragon

**Comment by lekhab** [comment]
closing resolved issues.
