### ISSUE TITLE
Project not automatically building (and showing up as 'empty')

### ISSUE THREAD

**Issue by d3ming** [Shippable/support#1744]
disclaimer: I'm a total noob at shippable, just started trying it out.

One of my projects I'm trying to set up on shippable doesn't automatically build even after I added a shippable.yml file.  It also doesn't show up on my project list, it only shows up if I click 'show empty project'.  My questions are:

1. What makes the project 'empty'?  It's clearly not an empty project - although it is a private repo
2. How do I get my project to build on commit?  Is it something I'm doing wrong or a bug with the system?

I'm also noticing general perf/slowness issues in getting my projects or getting list of branches for my project.  i.e. https://app.shippable.com/subscriptions/55b80b38edd7f2c05289fee9, https://app.shippable.com/projects/55b81febedd7f2c0528a1c54

**Comment by d3ming** [comment]
Never-mind - I see the error was in my shippable.yml.  It's just slow/not obvious to get this to surface since the project was hidden under empty projects.

**Comment by lekhab** [comment]
@d3ming: Thanks for the feedback - we are working on making error notifications more obvious to the users.

To answer your first question, 'empty' projects are those that don't have any builds on our system yet. I have added your question to our documentation FAQ here for now: http://docs.shippable.com/faq/

Please let me know if I can help if any other way and I can re-open the issue.
