### ISSUE TITLE
Initial view after signing up is very unhelpful ...

### ISSUE THREAD

**Issue by grosser** [Shippable/support#1745]
Some inline documentation on how to get started would be nice instead of just a blank page

<img width="1075" alt="screen shot 2015-07-30 at 9 33 47 pm" src="https://cloud.githubusercontent.com/assets/11367/9000831/cb02972a-3702-11e5-9b96-b40d65cbe04a.png">

**Comment by asgeo1** [comment]
I had this same issue. Was quite confusing.

The process to go through to get Shippable to find my private repositories was way too many steps.

**Comment by lekhab** [comment]
@grosser, @asgeo1: Thanks for the feedback! I have added this to our backlog to address.

**Comment by manishas** [comment]
@DavidGDragon we should look into improving this experience. Can you pick this up?

**Comment by DavidGDragon** [comment]
Added a helpful panel that shows up when you have not enabled a project or created a pipeline. 
![screenshot from 2016-03-07 14 57 03](https://cloud.githubusercontent.com/assets/6647936/13586290/e6966654-e474-11e5-84d4-ab98303a30b4.png)
---
beta verified www 5430

**Comment by grosser** [comment]
:heart:
