### ISSUE TITLE
It takes over 30s to load the project page

### ISSUE THREAD

**Issue by d3ming** [Shippable/support#1746]
Repro page: https://app.shippable.com/projects/55b81febedd7f2c0528a1c54

Takes over 30s to load the branches/ jobs for my project, and generally page load is slow.  Are there any performance issues being investigated now or am I a special case?  This is making it nearly impossible to use shippable for me.

**Comment by amondnet** [comment]
It takes 3~5s to load page. (Busan, Korea 100Mbps connection)

**Comment by sebest** [comment]
same thing here (SF California), the UI is really sluggish

**Comment by avinci** [comment]
we have improved quite a bit on this. Can you let us know if this is still happening?

**Comment by manishas** [comment]
closing since this is completely redone and we have greatly improved perf.
