### ISSUE TITLE
Project not syncing

### ISSUE THREAD

**Issue by lukehutton** [Shippable/support#1747]
Hi there,

Builds are not triggering, and branches aren't showing up. Seems like github sync not working on my private repo. URL = https://app.shippable.com/projects/55b170b3edd7f2c05281b1dd

Could you take a quick peek and see if I have any misconfiguration?

Thx

**Comment by lekhab** [comment]
@lukehutton: can you please send me your yml at lekha@shippable.com? Or check if the yml is valid at http://www.yamllint.com/. 

Please confirm the branches you are building are not excluded in your yml..

**Comment by lukehutton** [comment]
Sure, yml is valid, and I'm only building master branches, but PRs aren't being built and when I close a PR and merge it to master, master isn't building. I'll send you the yml via email.

thx

**Comment by lukehutton** [comment]
Awesome, thanks! like you said, i had "master" in yml, but branch was named "Master" in github. I deleted Master and added master branch
