### ISSUE TITLE
Cannot create API token

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1750]
Error:

```json
{
  "id":3000,
  "message":"APIToken creation failed",
  "methodName":"caller:540e7792399939140041ee81|accountPermissions|post|_checkPaidPlans"
}
```

**Comment by kevinhodges** [comment]
Also seeing this error message, are you aware of this problem?

**Comment by notABluesSinger** [comment]
Can also confirm I'm seeing this exact issue.

**Comment by lekhab** [comment]
following up on this.

**Comment by lekhab** [comment]
@caarlos0, @notABluesSinger, @kevinhodges:  We fixed this bug yesterday - a miss when we were making upgrades to our PlanManagement code. 

If you are still facing this, please add the link to the subscription so we can take a look.

**Comment by lekhab** [comment]
closing this, as the issue is resolved.

**Comment by caarlos0** [comment]
Sorry, forgot to do that.

Thanks @lekhab !

**Comment by norbe** [comment]
I've got the same problem at [our subscription](https://app.shippable.com/subscriptions/54e08c3a5ab6cc13528bff48).

**Comment by lekhab** [comment]
@norbe - opened a new support issue to track your case, since this one was already closed.

Issue here: https://github.com/Shippable/support/issues/1797
