### ISSUE TITLE
NPM Error: shasum check failed and networks errors

### ISSUE THREAD

**Issue by Vilsepi** [Shippable/support#1751]
For the past 7 days, our Node 0.12 builds (using the *shippableimages/ubuntu1404_nodejs* image) have been failing randomly. Almost half the time the build fails, and if we rebuild the same commit enough times, it passes.

The build passes locally on our machines without problems, and when downloading the files manually, the checksums are correct. This is slightly irritating, as each Node build takes 20-40 minutes.

## Today

https://app.shippable.com/builds/55bf65f1430ade0b00a1b694

    npm ERR! argv "/root/.nvm/versions/v0.12.7/bin/node" "/root/.nvm/versions/v0.12.7/bin/npm" "update"
    npm ERR! node v0.12.7
    npm ERR! npm v2.11.3
    npm ERR! shasum check failed for /tmp/npm-2218-c0ca66d2/registry.npmjs.org/less/-/less-1.7.5.tgz
    npm ERR! Expected: 4f220cf7288a27eaca739df6e4808a2d4c0d5756
    npm ERR! Actual: 380e4909748a04ce2bffb7aa719610db01418dc8
    npm ERR! From: https://registry.npmjs.org/less/-/less-1.7.5.tgz

https://app.shippable.com/builds/55bf37f3c3487d0b002ff359

    npm ERR! argv "/root/.nvm/versions/v0.12.7/bin/node" "/root/.nvm/versions/v0.12.7/bin/npm" "update"
    npm ERR! node v0.12.7
    npm ERR! npm v2.11.3
    npm ERR! shasum check failed for /tmp/npm-2217-3eef2c52/registry.npmjs.org/less/-/less-1.7.5.tgz
    npm ERR! Expected: 4f220cf7288a27eaca739df6e4808a2d4c0d5756
    npm ERR! Actual: cd9efda378ee90f1fd844bac6454ba9537ca2400
    npm ERR! From: https://registry.npmjs.org/less/-/less-1.7.5.tgz

## 3 days ago

https://app.shippable.com/builds/55bbc44f2ee9d20b0063116a

    npm ERR! argv "/root/.nvm/versions/v0.12.7/bin/node" "/root/.nvm/versions/v0.12.7/bin/npm" "update"
    npm ERR! node v0.12.7
    npm ERR! npm v2.11.3
    npm ERR! shasum check failed for /tmp/npm-2036-01dd1b9b/registry.npmjs.org/selenium/-/selenium-2.20.0.tgz
    npm ERR! Expected: f515b1a162de93c2ccef2fc0ca33f3b5543e38c8
    npm ERR! Actual: 657a16493574af5011e76cad271d73ac64103454
    npm ERR! From: https://registry.npmjs.org/selenium/-/selenium-2.20.0.tgz

https://app.shippable.com/builds/55bb99082c6c780b00d94259

    npm ERR! argv "/root/.nvm/versions/v0.12.7/bin/node" "/root/.nvm/versions/v0.12.7/bin/npm" "update"
    npm ERR! node v0.12.7
    npm ERR! npm v2.11.3
    npm ERR! shasum check failed for /tmp/npm-2124-1e87b123/registry.npmjs.org/selenium/-/selenium-2.20.0.tgz
    npm ERR! Expected: f515b1a162de93c2ccef2fc0ca33f3b5543e38c8
    npm ERR! Actual: 0bc8995702a44b4c554958336b518c3421597ff8
    npm ERR! From: https://registry.npmjs.org/selenium/-/selenium-2.20.0.tgz

## 4 days ago

https://app.shippable.com/builds/55ba3f9fd4c0f10b0029ff9b

    npm ERR! code ECONNRESET
    npm ERR! errno ECONNRESET
    npm ERR! syscall read
    npm ERR! network read ECONNRESET
    npm ERR! network This is most likely not a problem with npm itself
    npm ERR! network and is related to network connectivity.
    npm ERR! network In most cases you are behind a proxy or have bad network settings.

https://app.shippable.com/builds/55ba2e22de719b0b006c6c29

    npm ERR! argv "/root/.nvm/versions/v0.12.7/bin/node" "/root/.nvm/versions/v0.12.7/bin/npm" "update"
    npm ERR! node v0.12.7
    npm ERR! npm v2.11.3
    npm ERR! shasum check failed for /tmp/npm-2192-d0d4e91d/registry.npmjs.org/less/-/less-1.7.5.tgz
    npm ERR! Expected: 4f220cf7288a27eaca739df6e4808a2d4c0d5756
    npm ERR! Actual: 44120e66464cd82512fa7ea26bd5ce0c4231379e
    npm ERR! From: https://registry.npmjs.org/less/-/less-1.7.5.tgz

## 7 days ago

https://app.shippable.com/builds/55b60f32d5d2f60c00033383

    npm ERR! argv "/root/.nvm/versions/v0.12.7/bin/node" "/root/.nvm/versions/v0.12.7/bin/npm" "update"
    npm ERR! node v0.12.7
    npm ERR! npm v2.11.3
    npm ERR! shasum check failed for /tmp/npm-2042-a7cce89c/registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz
    npm ERR! Expected: a567c2af000ad22dc8f2a653d91978ae1f5316f4
    npm ERR! Actual: baaa081767f24dc28ffe71c9d04f69e276dce980
    npm ERR! From: https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz

sudo docker rm -f -v 4b5e47d53aff

    Error response from daemon: Cannot destroy container 42f97fb23cd9: Driver aufs failed to remove root filesystem 42f97fb23cd9b328bf77f31fab47ab63c514ec057013e057454683d8bf8a05cf: rename /data/aufs/diff/42f97fb23cd9b328bf77f31fab47ab63c514ec057013e057454683d8bf8a05cf /data/aufs/diff/42f97fb23cd9b328bf77f31fab47ab63c514ec057013e057454683d8bf8a05cf-removing: device or resource busy
    Error: failed to remove containers: [42f97fb23cd9]

**Comment by mikeblakeuk** [comment]
+1

**Comment by lekhab** [comment]
@Vilsepi,@mikeblakeus: Apologies for the delay in getting back. We weren't able to reproduce this, unfortunately.  But our engineer did some digging and here is what she found. Can you try the suggested workaround below and let me know if that helps?

- The npm shasum errors tend to happen when there's a network connection issue (DaftMonk/generator-angular-fullstack#49), and/or something gets corrupted in your npm cache (npm/npm#7991) - again, possibly as a result of network issues.
- You are using shippable_retry npm install in your yml, which will retry your npm installation in the event of network issues (http://docs.shippable.com/yml_reference/#retrying-npm-install). However, those same network issues could lead to a corrupt npm cache, which would cause shasum errors.
- One solution would be to change your yml to ```shippable_retry npm cache clean && npm install```. This gives the benefit of retrying if there's a network issue, but with a fresh npm cache each time.

**Comment by lekhab** [comment]
closing this. Please let me know if we can help you any further.
