### ISSUE TITLE
files in buildoutput do not exist

### ISSUE THREAD

**Issue by spyrospph** [Shippable/support#1753]
In our after_script code we have the action

cp -r vendor ./shippable/buildoutput 

However suddenly our files are not being copied correctly and this results to our vendor folder not existing in our final docker build.

Please look into this ASAP as our builds are broken on production.

**Comment by pmoust** [comment]
Reference build https://app.shippable.com/projects/54c655025ab6cc135289c9c2

Sequence is 
1. Pull Image A
2. Get dependiences, run CI
4. Pass
5. copy artifacts in shippable/buildoutput dir to be used in
6. Docker build
7. Push

Critical cause some services CD is broken.

**Comment by rageshkrishna** [comment]
We're looking in to this. I'll update here as soon as I have more details.

**Comment by lekhab** [comment]
this is now fixed - a regression during changes pushed to update our build system. Apologies! :-(

**Comment by pmoust** [comment]
Thanks
