### ISSUE TITLE
Shippable does not redirect users to HTTPS

### ISSUE THREAD

**Issue by czardoz** [Shippable/support#1754]
Visiting http://app.shippable.com does not open the app. 

IsUp also shows an error connecting: http://isup.me/app.shippable.com

```
 It's not just you! http://app.shippable.com looks down from here. 
```

**Comment by lekhab** [comment]
@czardoz - Please use http://shippable.com or https://shippable.com - those are the correct URLs for Shippable.  We will eventually stop exposing app.shippable.com
