### ISSUE TITLE
Google App Engine deployments aren't sustainable long-term

### ISSUE THREAD

**Issue by aaronwest** [Shippable/support#1756]
Google App Engine deployments, using the appcfg.py Python toolkit, do not work long-term. I'm using GAE SDK v1.9.24 and following the Shippable documentation listed [here](http://docs.shippable.com/appengine/#deployment-of-a-python-application) and am not able to get GAE deployments to work long-term.

I am able to get deployments to work, under certain conditions, for an hour until the GAE tokens expire. More on this below.

The Shippable documentation linked above outlines two scenarios for GAE deployments: password authentication or OAuth2 authentication. I've tried both and have been partially successful with OAuth2 authentication.
#### Password authentication

The Shippable docs instruct users to global env vars, one for your Google email and one for your Google password. With of course the password being encrypted using the project settings on Shippable. Then, the docs say to use the following command:

> - echo "$GAE_PASSWORD" | $GAE_DIR/google_appengine/appcfg.py -e "$EMAIL" --passin update .

The `--passin` flag is not available in the GAE SDK v1.9.24. I'm not sure when it was removed but it isn't available in the latest version of the SDK and there doesn't appear to be a replacement. Nevertheless, I attempted to get password-based authentication working by searching and seeing how others were doing it. I also consulted the Google docs. I was never able to get it working.
#### OAuth2 authentication

After failing with password-based authentication I tried OAuth2. I followed the Shippable instructions [here](http://docs.shippable.com/appengine/#deployment-of-a-python-application) which ask users to call a method of appcfg.py (`list_versions`) which lists application versions (Google supports up to 10 versions) for the app you have deployed on GAE. A byproduct of the calling this command - or any other command - of appcfg.py is the storage of an app token in the user's home directory. The token is called `.appcfg_oauth2_tokens` and is a basic JSON file which includes several pieces of information. Notable data are the app token string and the token expiry. The token expiry is a date in UTC (more specifically it is stored as zulu time in JSON) and is set to +1 hours from the time the `.appcfg_oauth2_tokens` was written to disk.

NOTE: The token is only written to disk if the user accepts the OAuth2 session in the browser.

The Shippable instructions go on to ask the user to encrypt the access token using a Shippable secure variable. No specific instructions are given which is unfortunate. But, the basic workflow is for the user to copy only the string in the `access_token` portion of the `.appcfg_oauth2_tokens` file. Then, copy that value, plus a corresponding name you make up, into _Encrypt Env Vars_ in your Shippable project settings. This will then give you a value you can define as a secret in your shippable.yml file and use as a `$variable` in the appcfg.py command.

Once I figured all of this out I pushed a feature branch to GitHub and Shippable walked through the build process. And it worked. I was super happy.

An little while later I executed the same process and the Shippable build failed with error message:

> google.appengine.tools.appengine_rpc_httplib2.AuthPermanentFail: Access token is invalid.

So I spent a few hours searching, reading GAE documentation, and trying to get builds to work. I discovered the invalid token was due to GAE expiring ALL OAuth2 tokens after 1 hour. On a local machine such as my Mac this isn't a problem. The `.appcfg_oauth2_tokens` file exists on my machine and when I execute appcfg.py GAE simply updates the `access_token` value and the `token_expiry`. When executing the same command in a Shippable build it fails. This is because the `.appcfg_oauth2_tokens` file doesn't exist in the container AND the token being used as the secret (encrypted env var) is now invalid.

After more searching I tried the `--oauth2_refresh_token` switch in appcfg.py instead of the `--oauth2_access_token` switch in the Shippable documentation. As long as the token I was using as the secret env var was not expired, this command worked.

In summary, there doesn't appear to be a way to get long-term Shippable builds working with GAE. I couldn't get password authentication working and even if I could I don't want the deployment process tied to my Google Apps email. Also, the OAuth2 based authentication, while it can be engineered to work, doesn't work beyond 1 hour.

Here's some documentation pages I read while I was trying to get all this working. Hopefully, someone else can make sense of this process and we can get things working. In the meantime, my team will build and deploy to GAE using appcfg.py locally instead of through Shippable webhooks to GitHub. That's unfortunate but we need a predictable/working solution.

http://docs.shippable.com/appengine/
https://developers.google.com/console/help/new/#serviceaccounts
https://developers.google.com/identity/protocols/OAuth2ServiceAccount
https://cloud.google.com/appengine/docs/python/gettingstartedpython27/uploading

**Comment by lekhab** [comment]
@aaronwest: Thanks again for the work on this and providing the details. The way it is set up currently, your solution is probably one of the more feasible ones. I have tagged this as a feature request to prioritize GAE deployments natively within Shippable.

**Comment by avinci** [comment]
We have launched runCLI which allows you to run any CLI commands you want. The idea here is to get Shippable do enough to help you but at the same time not really get in the way. Sometimes managed tasks can be restrictive and open shell scripting be too cumbersome. Our belief is runCLI is the perfect balance

Docs link :  http://docs.shippable.com/pipelines/jobs/runCLI/
