### ISSUE TITLE
Failed to upload image yet build was not treated as "Failed"

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#1757]
Found an error in shippable output logs during image upload to gcr but build was not treated as failed.
```
fa644e510873: Buffering to disk
Failed to upload layer: Put https://gcr.io/v1/images/fa644e5108734490781c9faf3798cbb8d9230e0767d7a564654de5fc718a1a72/layer: write tcp 
<ip-masked>:443: connection reset by peer
```

Is this behaviour as per design or some bug ? It should have mark build as "Failed" because I cannot deploy this image and it messes up our auto deployment.

**Comment by jawaid** [comment]
We will look into it and get back to you.

**Comment by jawaid** [comment]
This is as per design.
