### ISSUE TITLE
PhpUnit failed, but build marked as SUCCESS

### ISSUE THREAD

**Issue by claar** [Shippable/support#1758]
PhpUnit had a fatal error, but the build was still marked as succeeding -- see https://app.shippable.com/builds/55c4386342d32f0b00aad35e

Possibly related to #1757?

**Comment by lekhab** [comment]
following up on this.

**Comment by claar** [comment]
When you said "following up on this", did you mean that you were checking into this, or that you wanted more information from me?

This is still happening, and is a big problem for us -- another example can be seen at https://app.shippable.com/builds/55ce58ba1557230b007d6109

Thanks!

**Comment by claar** [comment]
I need help with this please -- our builds have been silently failing for too long. Our master branch was broken for 2 days and we didn't know -- we've come to rely on Shippable for this.

https://app.shippable.com/builds/55ce346babe3150b00bfe814

**Comment by lekhab** [comment]
@claar: Sorry abt the delay here. We have been trying to reproduce the error - but have not been successful so far. So far, it appears as though something in your PHPunit configuration is returning a zero exit code which leads the script section to be marked successful. 

I am going to follow up with our leads again on this - but this might require us to know the details of your internal configuration to understand why the script returns a zero exit code, despite the error.

**Comment by claar** [comment]
Thanks @lekhab -- I'm happy to provide any information needed.

**Comment by claar** [comment]
@lekhab I looked into this some more, and found that `phpunit` is returning a zero exit code locally as well.

This is a PHPunit problem, not a Shippable problem -- so I'm closing this. Thanks for the help!
