### ISSUE TITLE
No items in CI menu

### ISSUE THREAD

**Issue by shagabutdinov** [Shippable/support#1759]
The CI menu is empty and I didn't find way to fix it:

![screen_2015-08-07_13 49 30_03 00](https://cloud.githubusercontent.com/assets/1635613/9134375/31bfab1a-3d0c-11e5-8c1d-3dde4040f3ad.png)

I have public repositories on github and I logined with github account "shagabutdinov".

**Comment by jawaid** [comment]
Will look into it and get back to you.

**Comment by kailevy** [comment]
@shagabutdinov Have you tried going into account settings (top right) and clicking 'Force Sync'?

**Comment by shagabutdinov** [comment]
The trick worked for me, thank you!
