### ISSUE TITLE
Reproducible builds using Gitian LXC containers

### ISSUE THREAD

**Issue by indolering** [Shippable/support#176]
I've been following [this issue](https://github.com/devrandom/gitian-builder/issues/53#issuecomment-44742393) on the Gitian Github repo and it looks like someone has figured it out,
>I made progress on this and I successfully built bitcoin using gitian-builder inside a docker container.
>
>Now I am wrapping up the results and going to publish them, thus you might consider integrating them here.
>
>The key steps are:
>...

This is something Travis CI and other just CANNOT accomplish and the time required for reproducible builds is a major barrier to their being used in CI.

**Comment by manishas** [comment]
@gdm85 we allow privileged containers with dedicated hosts - http://docs.shippable.com/en/latest/config.html#dedicated-hosts

The blog post for dedicated hosts describes how to set up and use - http://blog.shippable.com/dedicated-hosts-

These should address your scenario. Plus, watch for some announcements reg multi container environments soon :)
