### ISSUE TITLE
Build fails but no error in console

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1760]
I am not sure why this build is failing. I see no errors in console --
https://app.shippable.com/builds/55c75d2713cd3f0b005e777f
Need help in understanding what is causing this issue.

Thanks,
Harpreet

**Comment by lekhab** [comment]
@hshira: sorry about the delay in getting back to you. We purged the logs older than Aug 16 when we had to deal with a DB out of space issue recently. I see all your recent builds are succeeding. Do you have any recent builds where you have seen this happen again?

**Comment by leonfs** [comment]
I'm experiencing a similar situation. Build fails but all checks are green.

https://app.shippable.com/builds/55ddf4637743f10b002b64ce

**Comment by lekhab** [comment]
@leonfs - opened a new issue for you in #1816. Closing this out.
