### ISSUE TITLE
Delete duplicate account for blakeblackshear

### ISSUE THREAD

**Issue by lekhab** [Shippable/support#1761]
opening for @blakeblackshear - separating the issue from #1492.

Details from @blakeblackshear:
"
Somehow I have 2 accounts and I need to move the link to my github to the same account where I have bitbucket linked. How can I do this?

The account id linked to github is: 55819d9d4d96360c000eff55
The account id linked to bitbucket is: 54f9e39a5ab6cc13529428d6

Please remove account id 55819d9d4d96360c000eff55.
"

**Comment by ragsden** [comment]
deleted account

**Comment by blakeblackshear** [comment]
I was able to link my github account to the same one as my bitbucket account, but all but 1 of my projects disappeared from the bitbucket organization.

**Comment by blakeblackshear** [comment]
They seem to have come back after logging out and back in.

**Comment by lekhab** [comment]
@blakeblackshear - closing as it's resolved. please let us know if we can help you any further.
