### ISSUE TITLE
Can't add repository from github

### ISSUE THREAD

**Issue by bayu41** [Shippable/support#1762]
Hi guys,

I have error while add private project from github.
It say Internal Server Error.
How can I add the repository?

**Comment by kailevy** [comment]
Does the error message say anything else alongside Internal Server Error? Could you post a screenshot of the message?

**Comment by lekhab** [comment]
@bayu41: can you also confirm that under your Account settings -> GitHub identity, the Private Repos button is "ON".

![screen shot 2015-08-11 at 10 55 20 am](https://cloud.githubusercontent.com/assets/9526532/9205507/7e88772a-4017-11e5-89b7-8be13ab5fde1.png)

**Comment by lekhab** [comment]
@bayu41: are you still facing this issue?

**Comment by lekhab** [comment]
please let me know if you are still facing this and I will re-open. Closing for now.
