### ISSUE TITLE
Build stuck in "waiting"

### ISSUE THREAD

**Issue by iqbalnurhakim** [Shippable/support#1763]
Hi there,

Our builds is stuck in "waiting" status. any idea what's going on there?

https://app.shippable.com/subscriptions/5534a859edd7f2c052c8bb44

**Comment by iqbalnurhakim** [comment]
And i found `Waiting for mysql to start... ` in the log.

**Comment by caarlos0** [comment]
Here:

> Waiting for logs...

https://app.shippable.com/builds/55cb8a2d4efad50b00035fdc

Seems like all of our builds are stuck...

**Comment by caarlos0** [comment]
cc/ @lekhab

**Comment by lekhab** [comment]
transient issue with resources being overloaded. the root cause is now fixed. closing.
