### ISSUE TITLE
Stop trimming console logs

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#1764]
When downloading console logs, all spaces are preserved.

However, the console tab of any build page displays console logs without spaces (app.min.js appears to call `trim()` on every `output` in the `console` array). This is destructive and makes full tracebacks very hard to read. Can you please stop trimming those spaces? Thanks!

**Comment by lekhab** [comment]
@pquentin - opened an internal request to follow up on this.

**Comment by pquentin** [comment]
@lekhab The bug appears to be fixed on my end. Thanks!

**Comment by pquentin** [comment]
Really seems fixed, closing.
