### ISSUE TITLE
Build output not pushed to quay.io

### ISSUE THREAD

**Issue by rlcomte** [Shippable/support#1765]
Hi,

We are encountering blocking issues in our CI pipeline, with Shippable not pushing build outputs to Quay.io. For one of our projects the last (and only) successful push happened on August 4. After that the pushes failed, not only for this project, but also for others. We use the minv2 image.

This happens with Golang based projects. Strangely the Nodejs based project did push. This project uses a custom ubuntu image.

**Comment by lekhab** [comment]
@rlcomte: I am unable to pull up builds with your github id. Are you using a different id? Can you paste links to failed builds here, pls?

**Comment by rlcomte** [comment]
Sorry for not providing more information, but normally my colleague takes care of this.
The builds are run under the toincrease account.
Failed build links: https://app.shippable.com/builds/55c9dc6e2f479e0b00fc5210

Note that I got errors in my AWS CodePipeline deployment, because it could not fetch the build image from quay.io. That is not shown in this build log here.

Hope this helps.

**Comment by rlcomte** [comment]
Hi,

I apologize for this issue, as it turned out that a change in our shippable.yml, using encrypted credentials, broke our integration with AWS. I assume that within the Shippable build script the call to AWS failed, and the subsequent post to quay.io did not happen. 
The one thing I would like to see from Shippable is a more detailed build log.

Rine
