### ISSUE TITLE
Unable to login with Bitbucket login

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1766]
![image](https://cloud.githubusercontent.com/assets/1060991/9198091/2b3e1f4c-3fff-11e5-8511-71157ddd41fa.png)

**Comment by kailevy** [comment]
Is this bitbucket account already linked to your github? Are you trying to login to an account linked ONLY to bitbucket?

**Comment by hshira** [comment]
This account is associated with BOTH github and bitbucket. I am able to login via github but not via bitbucket.

**Comment by viz** [comment]
I'm getting the same error. I've just created an account today - initially from a bitbucket account, and then configured my github account as well on the settings page.

I get the rror when trying to log in with either bitbucket or github.

**Comment by manishas** [comment]
@viz our service is down right now. ETA for the fix is 30 mins to an hour at the latest.

**Comment by lekhab** [comment]
@hshira: this has been resolved now. You should be able to login with both GitHub and Bitbucket accounts. Please let me know if you are still facing any issue.
