### ISSUE TITLE
Waiting - even though no minions in use

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1767]
None of the minions are processing any other builds, still stuck:
![image](https://cloud.githubusercontent.com/assets/1060991/9198114/66b7ca00-3fff-11e5-845a-b72461580b0c.png)

https://app.shippable.com/builds/55c9f0b4862ab60b008fa12a

**Comment by hshira** [comment]
Started now. Not sure why it waited for 10 minutes

**Comment by avinci** [comment]
We are experiencing heavy volume and our scheduler is backed up. We are working on getting the log jam eased up. Sorry about the delay.

**Comment by lekhab** [comment]
@hshira: the queues were cleared. I see your builds are succeeding now. marking this resolved. please let me know if you are facing any other issue.

**Comment by hshira** [comment]
It works now thanks!
