### ISSUE TITLE
Multiple tags on docker image push

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1768]
I want to apply 2 tags to my docker image created by build. 
1. default: example, master.57
2. latest

Is it supported by shippable? How can I do that?

**Comment by lekhab** [comment]
@hshira: no, I am afraid we don't support multiple tags to a docker image currently. We do have it on our backlog and there is an open issue where this is being tracked - https://github.com/Shippable/support/issues/824.

Please follow that issue for updates on this feature request. I will close this one as it's a duplicate.
