### ISSUE TITLE
Builds are stuck in queue even if there are unused minions

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#1769]
Builds are stuck in queue even if there are unused minions
Ref. subscription/org https://app.shippable.com/subscriptions/5480429dd46935d5fbbf5213

**Comment by simensen** [comment]
We're seeing this as well.

**Comment by manishas** [comment]
looking into it now...

**Comment by manishas** [comment]
Builds should be running again.... let us know if you're still running into issues. Sorry for the inconvenience!

**Comment by pmoust** [comment]
Thanks
