### ISSUE TITLE
How to use private maven repository?

### ISSUE THREAD

**Issue by dcheckoway** [Shippable/support#177]
Sorry if this is a common one or a duplicate, but I've searched your documentation and I can't figure it out.

I have a java/maven project, and I'm trying to migrate it to Shippable.  I have a private Maven repository (which I currently host myself), and I use ~/.m2/settings.xml and ~/.m2/settings-security.xml to configure access to it.

I can't figure out how to set that up on Shippable...help!

**Comment by manishas** [comment]
Closing this issue since folks have found a way to make this scenario work. Thanks!
