### ISSUE TITLE
Cannot open the app

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1771]
A request to `/accounts/:id/sync?force=true` took 2 min and timed out...

Seems like this is happening to everyone in our organization...

Anything I can do here to help?

**Comment by lekhab** [comment]
@caarlos0: The queues got backed up. This is resolved now. We are working hard to stabilize this - apologies for the bumps during the process.

**Comment by caarlos0** [comment]
Ok! Many thanks @lekhab :+1:

**Comment by caarlos0** [comment]
Hi @lekhab ,

Sorry to reopen this, but seems like builds are not being build too...

**Comment by lekhab** [comment]
@caarlos0: We are taking a look and will keep you posted. Our console logs are still catching up - so the logs will take sometime to update. As long as your hosts are up, the builds should run though, so following up on this. (when do you turn off your hosts typically?)

**Comment by caarlos0** [comment]
@lekhab in ~4 hours from now (19:45 GMT-3)

**Comment by caarlos0** [comment]
@lekhab thanks, BTW

**Comment by lekhab** [comment]
@caarlos0:  Apologies, there was an issue during an upgrade which resulted in SSH keys being reset. So we are unable to contact your hosts. The hosts need to be re-initialized afresh with the new keys, I am afraid. 

I sent you the key on email - can you please run it on all your hosts and then hit the re-initialize button?

Thanks again for your patience!

**Comment by caarlos0** [comment]
@lekhab it's working now!

Thanks :tada:
