### ISSUE TITLE
Organization not showing up.

### ISSUE THREAD

**Issue by mikedanese** [Shippable/support#1772]
Hi, we just move the kubernetes to the new organization https://github.com/kubernetes and while trying to reenable shippable, I noticed that the kubernetes organization is not showing up. Am I looking in the right spot?

![no-kubernetes](https://cloud.githubusercontent.com/assets/1787169/9232157/e39953e0-40e0-11e5-8ef9-534ff04a27b8.png)

**Comment by kailevy** [comment]
Could you ensure that your account is fully synced by going to settings (top right) and clicking 'Force Sync'?

**Comment by ixdy** [comment]
I just tried a force sync on https://app.shippable.com/accountSettings, but it's still not showing the kubernetes org for me, either.

**Comment by mikedanese** [comment]
Yup. Force sink did not work.

**Comment by kailevy** [comment]
Could you try following these instructions? 
http://docs.shippable.com/faq/#why-cant-shippable-see-my-org-on-github

**Comment by manishas** [comment]
we're looking into this...

**Comment by manishas** [comment]
This might be relevant - 

Why can't Shippable see my org on GitHub?

GitHub's default policy when a new org is created is 'access restricted'. In order for Shippable to be able to see the org, you must manually grant access to Shippable. This can be resolved by going to the third-party access section for the org, and clicking 'Remove restrictions' Under the 'Third-party application access policy' section.

**Comment by mikedanese** [comment]
That worked! Thanks @kailevy @manishas . Is there a way to only add shippable as an authorized application? What is the benefit of restricting access?

Side note: we had 8 workers in our old configuration but now we only have one.

**Comment by mikedanese** [comment]
We are still having some issues. Builds aren't starting and it looks like a webhook is not setup.

Is there any documentation on how to re-setup a webhook?

Is there any way we can get our 8 workers for this new location?

**Comment by mikedanese** [comment]
Figured out how to reset the webhook.
