### ISSUE TITLE
Git Clones Failing

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1773]
with Permission denied (publickey).

During npm install of packages that include private repositories.  This is ALL of our packages so no builds are completing...

@manishas Are you having a bunch of known issues right now?  Haven't seen much on twitter but feeling very wobbly today..

**Comment by lekhab** [comment]
@chriskinsman: Real sorry about this - we had issues during an upgrade which resulted in the ssh deploy keys being reset. 

Can you please re-enable access to the Shippable Deployment Key (found under Subscription -> Settings for your repos?

Please let me know if you have any questions about this and I am happy to help.

**Comment by chriskinsman** [comment]
Arrgghhh.  That is several dozen repos...

**Comment by chriskinsman** [comment]
Getting key already in use error once I try to add it to second repo

**Comment by lekhab** [comment]
:(  Didn't realize your settings were at the repo level. You could set this at an account level if you have multiple repos - but I am assuming you didn't want that.

**Comment by lekhab** [comment]
just saw your comment - following up..

**Comment by chriskinsman** [comment]
Shippable added it in the past

**Comment by lekhab** [comment]
@chriskinsman:  This needs to be added at the account level in GitHub for multiple repos, afaik. Are you able to add it to the account?

Just so I understand, are you saying this was working for you at a repo level earlier? Are you able to get on a hangout or a call, so we can get this resolved for you.?

**Comment by chriskinsman** [comment]
I don't want to give shippable write access to all repos.  I can jump on a call or hangout.  Point me at one.

**Comment by chriskinsman** [comment]
Also can't find a place in the org screen to add a deploy key at the org level.  Appears to be repo level only

**Comment by lekhab** [comment]
opened a hangout here: https://plus.google.com/hangouts/_/shippable.com/shippablecall?authuser=1. Please join in when you get a chance.

**Comment by chriskinsman** [comment]
Couldn't join for some reason.

**Comment by chriskinsman** [comment]
Resetting the project let's it pull the root stuff.

However npm install is failing to pull stuff with this:

git fetch -a origin (git@github.com:PushSpring/s3-stream-upload.git) Permission denied (publickey).

**Comment by lekhab** [comment]
it looks like you do have an account level key that it is trying to use and failing.

the hangout should work now - can you please try again?

**Comment by chriskinsman** [comment]
Had to re-add shippable in my ssh keys
