### ISSUE TITLE
Can you have spaces in encrypted environment variables?

### ISSUE THREAD

**Issue by aaronwest** [Shippable/support#1774]
See the two examples I've written below. Based on my testing I don't think it is possible to have spaces in encrypted variables but I wanted to ask.

Example 1:
`var="this is my variable"`

Example 2:
`var1="thisismyvariable" var2="here is another one"`

Notice the use of spaces in the value portion of both examples. Having spaces and then doing something like `echo $var` or `echo ${var}` or even `echo "${var}"` all show truncated results.

**Comment by lekhab** [comment]
@aaronwest: all environment variables can have spaces in them..I created a couple and doing an echo $var did print out the spaces.

I may have misunderstood your question..is there anything that is failing that led you to test this? can you share more details on how this was tested - since it worked for me.

**Comment by aaronwest** [comment]
@lekhab I was trying to store a JSON string in an encrypted var. The start of the string looked something like this:

>{"_module": "oauth2client.client", "token_expiry": "2015-08-12T19:59:00Z"

And after adding the encrypted var and testing it in a Shippable build, an echo statement would always be truncated at the first space (`{"_module":`). Hope this helps.

**Comment by DavidGDragon** [comment]
The combination `: ` (colon followed by a space) is a YAML special indicator http://www.yaml.org/refcard.html

In addition, spaces outside of a quote delimits variable names (ie `VAR1=a VAR2=b` results in 2 variables).

Lastly, the double quotes are removed from the variable during runtime, so you need to escape them if you want to use JSON.parse on the string.

Therefore, to use a JSON string in a YAML, you need to remove spaces after `:`'s, enclose the string using single quotes, and escape double quotes.

Example:
`MY_VAR='{\"_module\":\"oauth2client.client\", \"token_expiry\":\"2015-08-12T19:59:00Z\"}'`
Then you can encrypt that to use the JSON string in your build.

**Comment by lekhab** [comment]
@aaronwest: please let me know if @DavidGDragon's approach works for you.

**Comment by aaronwest** [comment]
@DavidGDragon - thank you so much for the suggestions which all made perfect sense. I was thinking the Shippable back-end was handling everything needed to make complex encrypted variables work. I shouldn't have assumed.

@lekhab @DavidGDragon - I was able to get the build working today after making the suggestions. Here's a quick run through of what I changed:
* escape all double quotes
* wrap the entire string (that which is on the right-side of the encrypted variable's equal sign) in single quotes
* remove all spaces

With all the above done I was able to `echo $VAR_NAME > ~/.token_filename`, `chmod 600 ~/.token_filename` and run `appcfg.py update .` to run a website update via the GAE Python SDK.

@DavidGDragon basically captured all the changes which were necessary except for removing the spaces after the commas.

Thanks everyone. This is resolved until Google creates a better way to accommodate automated builds/deployment in their SDK.

**Comment by lekhab** [comment]
great. thanks, @aaronwest. closing this.

**Comment by pkaminski** [comment]
@DavidGDragon What can I do if I need to pass an encrypted JSON value with spaces?  Specifically, it looks something like this:

```
{
  "private_key_id": "1e272...",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIE...qr+k\u003d\n-----END PRIVATE KEY-----\n",
  "client_email": "18995...@developer.gserviceaccount.com",
  "client_id": "18995....apps.googleusercontent.com",
  "type": "service_account"
}
```

I already removed all the spaces I could, escaped all the double quotes, and wrapped the whole thing in single quotes, but it still doesn't make it trough (the JSON fails to parse).  The spaces in `BEGIN PRIVATE KEY` and `END PRIVATE KEY` need to stay for the key to be properly recognized.  Any ideas?  Thanks.

**Comment by aaronwest** [comment]
@pkaminski - I think you're looking for something like this.

'{\"private_key_id\":\"1e272...\",\"private_key\":\"-----BEGINPRIVATEKEY-----\nMIIE...qr+k\u003d\n-----ENDPRIVATEKEY-----\n\",\"client_email\":\"18995...@developer.gserviceaccount.com\",\"client_id\":\"18995....apps.googleusercontent.com\",\"type\":\"service_account\"}'

* all newlines removed
* all spaces removed
* all double quotes replaced with `\"`
* entire string wrapped in single quotes

**Comment by pkaminski** [comment]
@aaronwest Unfortunately, the spaces in `BEGIN PRIVATE KEY` and `END PRIVATE KEY` are _required_.  Removing them invalidates the key.  Is there really no way to escape spaces in environment values in Shippable?  I can probably kludge around it by using another unique character then replacing with spaces at time of use, but it feels wrong to have to hack around this.

**Comment by aaronwest** [comment]
@pkaminski - Given spaces are required I don't think you'll be able to store the content as an encrypted variable. Perhaps there's another way.

**Comment by pkaminski** [comment]
:disappointed: I'll work around it.  Thanks.
