### ISSUE TITLE
After transfering repositories the number of workers was reduced

### ISSUE THREAD

**Issue by mikedanese** [Shippable/support#1775]
When our repository was at https://github.com/GoogleCloudPlatform/kubernetes we had 8 builders running concurrently. Now that we have transfered to https://github.com/kubernetes/kubernetes we only have around 3 builders running concurrently. How can we increase our number of builders to what we had previously?

**Comment by lekhab** [comment]
@mikedanese - following up on this.

**Comment by mikedanese** [comment]
Thanks much!

**Comment by lekhab** [comment]
@mikedanese - You now have 15 minions for your subscription as before. (you were seeing ~8 builders because each of your build is a matrix of 2 )

will resolve this.

**Comment by mikedanese** [comment]
Thanks @lekhab

**Comment by mikedanese** [comment]
LGTM
