### ISSUE TITLE
While troubleshooting issues today I deleted and re-added a repository

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1776]
How can I set the build number to a larger number to sync up with where it was...

**Comment by lekhab** [comment]
@chriskinsman: this isn't possible by default - since it is technically a new project. however, we can update the backend as a one time thing.  Do you know the build number that it needs to be set to?

**Comment by chriskinsman** [comment]
Please set ps-common to 2000

**Comment by ragsden** [comment]
We have set the build number to 700.
