### ISSUE TITLE
Docker build 

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#1778]
I am facing issues with docker build and deployment to ElasticBeanstalk.

I am using the POST-CI docker build process, where my code is checked out of github shippable compiles code and runs tests.

Once tests are completed shippable uses the docker file in my project to build the new image.
These are the contents of my Dockerfile

FROM sminq/baseimage:v1.0.2
WORKDIR /opt/sminq/api/
ENV APP_VERSION=1.2.1
ADD /home/shippable/.m2/repository/sminq/sminq-api/${APP_VERSION}/target/sminq-api-${APP_VERSION}.jar /opt/sminq/api/
ADD /home/shippable/.m2/repository/sminq/sminq-api/${APP_VERSION}/src/main/resources/build/sminqapi.sh     /opt/sminq/api/
ADD /home/shippable/.m2/repository/sminq/sminq-api/${APP_VERSION}/src/github.com/sminq/api/sminq-api.yml /opt/sminq/api/

RUN \
     mkdir /etc/service/sminqapi && \
     chmod +x  /opt/sminq/api/sminqapi.sh  && \
     cp /opt/sminq/api/sminqapi.sh /etc/service/sminqapi/run

EXPOSE 80 8081

The build fails everytime as docker cannot locate the jar file, where does shippable store the jar file for the project after the build/test process?

**Comment by DavidGDragon** [comment]
Docker build is run in the repository that was pulled so it doesn't know about `/hom/shippabe...`
Try using a path relative to the folder the Dockerfile is in. If the Dockerfile is in `sminq-api` then to add the jar you would use `${APP_VERSION}/target/sminq-api-${APP_VERSION}.jar`

More info: http://kimh.github.io/blog/en/docker/gotchas-in-writing-dockerfile-en/

**Comment by sheldon-sminq** [comment]
Still no luck, I am currently using the POST CI docker build process

1. image is pulled from shippable/minv2
2. My code is checked out from Github
3. Code is compiled and tests are run.

Now after the build is a success the 2nd part of the process begins

My docker image is created from the Dockerfile present in github repo root.

But the build fails as the location of .jar file generated in part 1 cannot
be found.

Regards,
Sheldon

**Comment by manishas** [comment]
Can you follow instructions in the 'Copying artifacts to prod image' section of this page -  http://docs.shippable.com/docker_build/

If you have done this and it doesn't work please send your dockerfile and Shippable.yml to lekha@shippable.com or post it in this issue as a comment. Thanks!

**Comment by sheldon-sminq** [comment]
Hi Manisha,

That worked for me thanks, I just wanted to know the final step of
deploying the Docker image to ElasticBeanstalk.

The image is created successfully after the build, the tag is also pushed
to Docker Hub.

I have included the Dockerrun.aws.json file in the github source root, do i
have to copy this too to the /buildoutput folder ?

Because currently it is not deployed to ElasticBeanstalk

Regards,
Sheldon

**Comment by manishas** [comment]
Did you try the instructions at http://docs.shippable.com/autodeploy-to-ebs/#deploy-via-docker-containers

You'll need the Dockerrun.aws.json at the root of your repo.

**Comment by sheldon-sminq** [comment]
Yes i have this file in root and the contents are

{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "<IMAGE_NAME>:<TAG>",
    "Update": "true"
  },
  "Authentication": {
    "Bucket": "sminq",
    "Key": "<KEY>"
  },
  "Ports": [
    {
      "ContainerPort": "80"
    }
  ]
}

**Comment by manishas** [comment]
Did you set up the integration and other config on Shippable as described in the docs link I pasted in the comment above?

**Comment by sheldon-sminq** [comment]
Yes since i am using Docker container deployment in EBS

I have followed these
steps
1. AWS integration added
2. Docker integration added
3. and in the deployment section have included EBS

**Comment by sheldon-sminq** [comment]
This is the output of the build process, it stops at image push

**Comment by lekhab** [comment]
@sheldon-sminq - we are following up on this. Will keep you posted.

**Comment by manishas** [comment]
@sheldon-sminq can you try your build again and see if the push to beanstalk goes through? Thanks!

**Comment by sheldon-sminq** [comment]
Hi Manisha,

Thanks things are working now.

**Comment by manishas** [comment]
Glad it works! Closing the issue.

**Comment by sheldon-sminq** [comment]
How can i use ebextension with the continuous deployment process? according
to aws documentation i have to package the Dockerrun json file with the
ebextension folder.

Does @Shippable support this?
