### ISSUE TITLE
Golang build is too slow

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1779]
Every build, Shippable downloads and install the Go version using `gvm`... I believe this could be optimized...

**Comment by lekhab** [comment]
@caarlos0 - can you attach some build links, pls?

**Comment by caarlos0** [comment]
@lekhab sure, sorry, forgot to do that somehow

- https://app.shippable.com/builds/55cc97d9195e410c0012f826

204 seconds just for the `gvm install`

**Comment by caarlos0** [comment]
using go tip seems to fix the issue, but still, I'm not always want the last version...
