### ISSUE TITLE
Changed annual plan from 5 minions to 1

### ISSUE THREAD

**Issue by AndriyPt** [Shippable/support#1780]
Hi,

I am employee of the Shadow Robot company (shadow-robot organization name on GitHub).
We have paid for annual subscription for the Startup plan https://web.archive.org/web/20150420071249/https://www.shippable.com/pricing.html with 5 minions about two months ago.

![billing](https://cloud.githubusercontent.com/assets/10820297/9249745/78c68bd2-41d0-11e5-8d39-4bd81c52fe49.png)

Today we have discovered that only one minion is available 
![minions_count](https://cloud.githubusercontent.com/assets/10820297/9249752/82a9fd0a-41d0-11e5-8e3f-3f8b6ee6f34e.png)

Yesterday we had 5 minions working for us.

Could you please advice what we should to get our minions back? :)

Thanks

**Comment by avinci** [comment]
Sorry @AndriyPt, I have updated your plan. There was a bug introduced in our code due a darn `!` bug which ended up messing some plans. 

I apologize for this.
