### ISSUE TITLE
Plan reduced to 1 minion

### ISSUE THREAD

**Issue by blakeblackshear** [Shippable/support#1781]
Our plan was reduced to 1 minion, and our ssh key seems to have been regenerated. Now we have to regenerate our encrypted vars and update keys everywhere.

**Comment by lekhab** [comment]
@blakeblackshear: Many apologies about the inconvenience. Following up on the following subscription: 54ff4f905ab6cc1352974ee1. Please let me know if there are other subscriptions that are having issues as well.

**Comment by lekhab** [comment]
Actually, looks like the subscription: 54f8bef75ab6cc13529374f7 was already updated to 5 minions. I was looking at the github org subscription which was not on the plan. 

Please let me know if that's not the case.  Will mark this resolved for now.

**Comment by blakeblackshear** [comment]
Using shippable is becoming painful enough that it will be worth the extra cost of travisci. We battle it daily.

**Comment by lekhab** [comment]
@blakeblackshear: Very sorry to hear that. I would love to get on a call with you and work through any issues you are facing. Please let me know at lekha@shippable.com if that is a possibility.
