### ISSUE TITLE
Change email addresses

### ISSUE THREAD

**Issue by adityabansod** [Shippable/support#1782]
Is there a way to change what email address my shippable notifications go to?

**Comment by kailevy** [comment]
You can change your primary email on github and then force sync your account-- that should be the one that is getting notifications

**Comment by adityabansod** [comment]
i have ~4 emails associated with my github profile, each linked to a different organization i belong to. i only use shippable w/ one org. can i pick which email to use?

**Comment by lekhab** [comment]
@adityabansod - no,  I am afraid not.  The notifications, by default go to the primary github account.

**Comment by lekhab** [comment]
Also tagging this as a feature request for our backlog..
