### ISSUE TITLE
when we "go get" a binary, it does not seem to be in the $PATH

### ISSUE THREAD

**Issue by sebest** [Shippable/support#1783]
see https://app.shippable.com/builds/55cc5955774b820c00800bb9

the same build is working on travis, so i guess it is just $PATH missing the path to go binaries

**Comment by lekhab** [comment]
@sebest: can you compare your YML to the samples provided in the documentation here? It also describes the PATH variable that needs to be set in the YML.

http://docs.shippable.com/languages/#go

Please let me know if the doc does not answer your questions.

**Comment by sebest** [comment]
@lekhab i think this will work, but IMHO the GOPATH and the PATH with GOPATH/bin should be set automatically by the CI when 'language: go' is set as it is part of a working go development environment.
thought?

**Comment by lekhab** [comment]
@sebest: I agree. I have provided the feedback to the engineering team. will update this to a feature request, so we can add this to our backlog.

**Comment by rageshkrishna** [comment]
@sebest Sorry we lost track of this for so long. A fix for this will be available in the next hour or so.

**Comment by rageshkrishna** [comment]
@sebest This has now been fixed.
