### ISSUE TITLE
Can't get past the "git_sync" stage

### ISSUE THREAD

**Issue by buley** [Shippable/support#1784]
My builds started failing a while back and I've been unable to find a solution.

It seems like it's failing in a part of the Shippable process that is outside of my control. Is there something I can be doing to get past the `git_sync` stage?

![screen shot 2015-08-13 at 3 18 02 pm](https://cloud.githubusercontent.com/assets/86985/9263048/9af0c0d0-41ce-11e5-967e-b6d56d910427.png)

**Comment by kailevy** [comment]
I believe that this issues is a clone of #728. Could you try the solution proposed there?

**Comment by buley** [comment]
I've got a deployment key added on a Github "Machine Account" that is a member of the team that has push/pull access to all organization repos.

This was the only way I could get through earlier issues because I have multiple private submodules and Github only allows you to use a (deployment) ssh-key once.

I also thought this was the issue so I also enabled the repo manually in Shippable. I believe enabling this repo in Shippable added another deploy key to it, so I was hoping to have ruled that out as the problem.

**Comment by lekhab** [comment]
@buley: Can you please add the deployment key from your Subscription -> Settings to the Machine Account one more time? The key was reset due to a bug and hence the issue. 

When you re-enabled the repo, only the project level key was reset - but we need the Account level key to be updated as well.

**Comment by buley** [comment]
I removed and re-added my deployment key to the Machine Account. Same error at the private submodule but, interestingly, now Github says the deployment key has never been used.


![screen shot 2015-08-13 at 4 03 01 pm](https://cloud.githubusercontent.com/assets/86985/9263774/d962fa30-41d4-11e5-9c03-1c49f65c9d99.png)

I rechecked and the machine account to which this was added and it appears to have the correct permissions. 

![screen shot 2015-08-13 at 4 05 35 pm](https://cloud.githubusercontent.com/assets/86985/9263813/31429328-41d5-11e5-9fe9-5eb3df95fe83.png)
![screen shot 2015-08-13 at 4 05 45 pm](https://cloud.githubusercontent.com/assets/86985/9263812/3141b2aa-41d5-11e5-9887-780c1686d978.png)

**Comment by lekhab** [comment]
@buley: Can we do hangout to figure out what's going on? The error I see in your builds should be fixed by updating the subscription deployment key in git@github.com:mcnaughton/legacy-systems.git - looks like you have already done this. 

Please let me know a time that works at lekha@shippable.com and I can set up a hangout session.

**Comment by lekhab** [comment]
@buley: Please let me know if you still need help getting this resolved.

**Comment by lekhab** [comment]
closing this. Please let me know if you are still facing issues and I will re-open.
