### ISSUE TITLE
Slack Notifications not triggering.

### ISSUE THREAD

**Issue by LuisMuniz** [Shippable/support#1785]
I have set up notifications with my slack channel up following the instructions in: http://docs.shippable.com/slack_notifications/

Though I can see in my channel that the integration has been added, and on my project , I have set up the notification in the project integrations section, I can not see any activity in my channel when I trigger builds.

**Comment by lekhab** [comment]
@LuisMuniz: are you able to see no notifications at all in your Slack Channel? Currently, you should get notifications when a build completes on the build status (success, failed..) 

We are in the process of adding additional slack notifications and this should be deployed over the next few days. 

Can you please send me the link to the project if you are still having issues?

**Comment by LuisMuniz** [comment]
Hi Lekha,

Yes, no notification has been shown at all since I created the integration.
This is the link to my project:

https://app.shippable.com/projects/55cdad20edd7f2c052a81eae


Regards,

Luis

Luis Muñiz
IT Director – Research and Development, Architecture | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | M : +34 647 79 34 76
luis.muniz@b2boost.com<mailto:luis.muniz@b2boost.com> | www.b2boost.com<http://www.b2boost.com/>

Please consider the environment before printing.


From: Lekha Bhargavi
Reply-To: Shippable/support
Date: Friday 14 August 2015 18:48
To: Shippable/support
Cc: Luis Muniz
Subject: Re: [support] Slack Notifications not triggering. (#1785)


@LuisMuniz<https://github.com/LuisMuniz>: are you able to see no notifications at all in your Slack Channel? Currently, you should get notifications when a build completes on the build status (success, failed..)

We are in the process of adding additional slack notifications and this should be deployed over the next few days.

Can you please send me the link to the project if you are still having issues?

**Comment by lekhab** [comment]
@LuisMuniz: It doesn't look like any builds have run for this project yet. Can you run a build and see if the integration works for build statuses? We are in the process of adding more notifications this week.

**Comment by LuisMuniz** [comment]
Why are you saying that no builds have run?
There are 11 builds on this project.

Luis Muñiz
IT Director – Research and Development, Architecture | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | M : +34 647 79 34 76
luis.muniz@b2boost.com<mailto:luis.muniz@b2boost.com> | www.b2boost.com<http://www.b2boost.com/>

Please consider the environment before printing.


From: Luis Muniz Fernandez
Date: Friday 14 August 2015 23:18
To: Shippable/support, Shippable/support
Cc: Luis Muniz
Subject: Re: [support] Slack Notifications not triggering. (#1785)

Hi Lekha,

Yes, no notification has been shown at all since I created the integration.
This is the link to my project:

https://app.shippable.com/projects/55cdad20edd7f2c052a81eae


Regards,

Luis

Luis Muñiz
IT Director – Research and Development, Architecture | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | M : +34 647 79 34 76
luis.muniz@b2boost.com<mailto:luis.muniz@b2boost.com> | www.b2boost.com<http://www.b2boost.com/>

Please consider the environment before printing.


From: Lekha Bhargavi
Reply-To: Shippable/support
Date: Friday 14 August 2015 18:48
To: Shippable/support
Cc: Luis Muniz
Subject: Re: [support] Slack Notifications not triggering. (#1785)


@LuisMuniz<https://github.com/LuisMuniz>: are you able to see no notifications at all in your Slack Channel? Currently, you should get notifications when a build completes on the build status (success, failed..)

We are in the process of adding additional slack notifications and this should be deployed over the next few days.

Can you please send me the link to the project if you are still having issues?

**Comment by LuisMuniz** [comment]
Sorry I just realized that I sent you the wrong link.

https://app.shippable.com/projects/55cdad20edd7f2c052a81eb1


Luis Muñiz
IT Director – Research and Development, Architecture | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | M : +34 647 79 34 76
luis.muniz@b2boost.com<mailto:luis.muniz@b2boost.com> | www.b2boost.com<http://www.b2boost.com/>

Please consider the environment before printing.


From: Lekha Bhargavi
Reply-To: Shippable/support
Date: Monday 17 August 2015 19:09
To: Shippable/support
Cc: Luis Muniz
Subject: Re: [support] Slack Notifications not triggering. (#1785)


@LuisMuniz<https://github.com/LuisMuniz>: It doesn't look like any builds have run for this project yet. Can you run a build and see if the integration works for build statuses? We are in the process of adding more notifications this week.

**Comment by manishas** [comment]
Can you trigger a new build and see if notifications work?

If not we will take a closer look... can we trigger a manual build on your behalf to see what's going on?

**Comment by LuisMuniz** [comment]
Yes please do

Luis Muñiz
IT Director – Research and Development, Architecture | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | M : +34 647 79 34 76

luis.muniz@b2boost.com | www.b2boost.com<http:// www.b2boost.com>



Please consider the environment before printing.



On Tue, Aug 18, 2015 at 1:50 AM -0700, "Manisha" <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you trigger a new build and see if notifications work?

If not we will take a closer look... can we trigger a manual build on your behalf to see what's going on?

**Comment by lekhab** [comment]
@LuisMuniz: I triggered this build for you: https://app.shippable.com/builds/55d36798373bda0b0094b4d0

We are not seeing any errors on our end.. could you let me know if you saw any notifications show up on your slack channel?

**Comment by lekhab** [comment]
@LuisMuniz: We realized what the problem is. Looks like you have set the channel name in your integration to `optipost-backend-dev`. It needs to be ` #optipost-backend-dev`. Slack is rather particular about having the  `#`. 

Can you try updating the name and trigger a build again?

**Comment by LuisMuniz** [comment]
Actually I just figured it out, I was writing to you about it as I received your email. It is precisely the reverse. The second integration works.
You see, it is a private channel. Private channels don’t start with #.
When I created a new integration with the name optipost-backend-dev, it works.

Thanks for your assistance. You may close the issue

Regards,

Luis

Luis Muñiz
IT Director – Research and Development, Architecture | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | M : +34 647 79 34 76
luis.muniz@b2boost.com<mailto:luis.muniz@b2boost.com> | www.b2boost.com<http://www.b2boost.com/>

Please consider the environment before printing.


From: Lekha Bhargavi
Reply-To: Shippable/support
Date: Tuesday 18 August 2015 20:06
To: Shippable/support
Cc: Luis Muniz
Subject: Re: [support] Slack Notifications not triggering. (#1785)


@LuisMuniz<https://github.com/LuisMuniz>: We realized what the problem is. Looks like you have set the channel name in your integration to optipost-backend-dev. It needs to be #optipost-backend-dev. Slack is rather particular about having the #.

Can you try updating the name and trigger a build again?
