### ISSUE TITLE
Ruby in NodeJS build

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#1786]
I've seen the following recommended in other issues:

```
language: node_js
node_js:
    - 0.12
before_install:
    - source ~/.rvm/scripts/rvm && rvm use 1.9.3
```

This produces an error:
```
line 90: /root/.rvm/scripts/rvm: No such file or directory
```

Is there an updated way to get ruby enabled in a node build?

**Comment by lekhab** [comment]
@tomsterritt: I ran a build to try this and I was able to get ruby enabled. my yml looks like below. (I was also able to run this without re-installing ruby)

If this doesn't work, can you share your whole yml with me at lekha@shippable.com?

```
# Language setting
language: node_js

# Version number
node_js:
  - 0.11

 before_install:
  - source ~/.rvm/scripts/rvm
  - rvm install 1.9.3 
  - source ~/.bashrc && ~/.rvm/scripts/rvm && rvm use 1.9.3

```

**Comment by lekhab** [comment]
this is working as per @tomsterritt on mail. closing.
