### ISSUE TITLE
Symfony

### ISSUE THREAD

**Issue by Grazulex** [Shippable/support#1789]
Hello,

is it possible to used your servcive with a Symfony application ?
If yes, can you show me a exemple for 
- install & config apache
- start composer install
- start the behat and unit test
thank you

**Comment by lekhab** [comment]
@Grazulex: Yes! We created a sample using the Symfony framework and you can find this in the shippablesamples repo (https://github.com/shippableSamples/sample_php_symfony).

Incidentally, one of our customers wrote this fantastic blog that might be of use to you as well. Please check that out for a step by step instruction on how [using Symfony with Shippable]
(http://ifdattic.com/continuous-integration-php-project-using-shippable/?utm_content=buffer54c83&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)

**Comment by Grazulex** [comment]
Many thanks with you help and this of the blog I have find the perfect config for me :
language: php

php:
    - 5.6
    
cache: true    

archive: true

env:
    global:
        - SYMFONY__ENV__DATABASE_HOST=127.0.0.1
        - SYMFONY__ENV__DATABASE_PORT=~
        - SYMFONY__ENV__DATABASE_NAME=ecom
        - SYMFONY__ENV__DATABASE_USER=ecom
        - SYMFONY__ENV__DATABASE_PASSWORD=

before_install:
    - echo "xdebug.max_nesting_level = 1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo 'variables_order = "EGPCS"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage    
    - composer self-update -n
    - composer install --prefer-dist -n
    - mysql -e "CREATE DATABASE $SYMFONY__ENV__DATABASE_NAME"
    - ./app/console doctrine:schema:create -n
    - ./app/console doctrine:fixtures:load

script:
    - phpunit -c app --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
    - ./app/console server:start -n
    - ./bin/behat --format=progress --out=std --format=junit --out=shippable/testresults -n

after_script:
    - ./app/console server:stop -n
    - cp -r ./app/logs shippable/logs
