### ISSUE TITLE
Cache container is 'on' but the state is not saved

### ISSUE THREAD

**Issue by osumampouw** [Shippable/support#1790]
This is in reference to this project:
https://app.shippable.com/projects/552c7ec75ab6cc1352c300d8
we turned on the cache container option, but we noticed in the past several builds that only the "pull" step is skipped, the rest are not skipped. Is this intentional?
For example:
<img width="1044" alt="screen shot 2015-08-16 at 12 58 29 am" src="https://cloud.githubusercontent.com/assets/2935092/9290143/07219c40-43b2-11e5-8f3b-167b42e782c6.png">
there are:
test_ve (5 secs)
git_sync (4 secs)
install (63 secs)

Can we just skip the steps above if cache container is already on? go straight to before_script, script and after_success?

Thanks
-Oby

**Comment by lekhab** [comment]
@osumampouw: This is by design. Cache only implies the image being pulled. The other steps still need to be updated for each build. git_sync, for instance, is syncing your code and we will need to continue to do this.
