### ISSUE TITLE
Any example with Alpine Linux base image

### ISSUE THREAD

**Issue by geshan** [Shippable/support#1794]
I just found out the default image used for testing is `13 gb` on [imagelayers](https://imagelayers.io/?images=shippable%2Fminv2:latest).

For one of my PHP application I don't even need MySQL (so surely not ruby, java, python, postgres etc). How do I use a very light ~40 mb image that only has PHP and composer built on alpine linux and still run my tests? Is there any guide or blog-post about it?

PS: I tried one with [php and composer](https://github.com/geshan/docker-php-composer-alpine) image but it failed on shippable.

**Comment by lekhab** [comment]
@geshan: You can use our language specific images and see if that works. These are bare-bones images, so you will have to install anything you need additional on top of it. Details in the guide below:

http://docs.shippable.com/languages/#php

You can also use your custom image  in the project settings and have your build use that instead. You can possibly combine the language specific Shippable DockerFile and the one you have and use that as your base image, for instance.

Documentation on how to use images from your Docker Registries is here:

http://docs.shippable.com/docker_registries/

http://docs.shippable.com/project_settings/#build-image

Hope this helps.

**Comment by lekhab** [comment]
@geshan: please let me know if I can help you any further and I will re-open. Closing the issue.

**Comment by geshan** [comment]
If there is any example of an alpine base image running on shippable that would be great to kick start.
