### ISSUE TITLE
Builds failing due to network issues

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1795]
An example: https://app.shippable.com/builds/55d1cd96952ed10b0045ae68

Builds are running in our own machines, but, in the build, we add to /etc/hosts the address of our nexus server. It was working until friday, and today it's not working anymore.

Our nexus is working normally, it's just shippable containers that can't connect to it...

**Comment by caarlos0** [comment]
BTW: we download some maven plugins from repo1.maven in `before_install`, and they too are very slow...

**Comment by caarlos0** [comment]
Just to be clear, what we do related to hosts:

```
before_install:
  - # unrelated stuff
  - echo "X.X.X.X repo.contaazul.ninja" | sudo tee -a /etc/hosts
  - sudo /etc/init.d/networking restart
```

**Comment by caarlos0** [comment]
Basically, seems like Shippable is not using our servers, and we have only 1 minion available... 

@lekhab help us here, please :(

**Comment by caarlos0** [comment]
I've restarted all nodes, reseted all nodes, re-initialized all nodes... nothing seems to work...

**Comment by caarlos0** [comment]
To clarify: the original issue (unable to connect to our nexus server) happens because the build is running in Shippable's infrastructure instead of ours, and our Nexus server is inside our VPC, so, no surprise it doesn't work.

**Comment by manishas** [comment]
looking into this...

**Comment by manishas** [comment]
@caarlos0 can you try again? This should be fixed. Sorry for the inconvenience!

**Comment by caarlos0** [comment]
@manishas seems to be working now, thanks!
