### ISSUE TITLE
All build are failing!!!

### ISSUE THREAD

**Issue by jamesmk** [Shippable/support#1796]
Help!!! All of our builds as of 5 days ago are failing. They are failing on the install so our notification script wasn't setup and we weren't notified.

This is across 4 projects so far that were all building perfectly fine. Looks to be a key issue:

From https://app.shippable.com/builds/55d21ac207b3460c00781b60

```
Cloning into 'shippable-setup'...
Warning: Permanently added the RSA host key for IP address '192.30.252.129' to the list of known hosts.
Permission denied (publickey).
```

From https://app.shippable.com/builds/55d2134207b3460c0077a2d6

```
SSHKit::Runner::ExecuteError: Exception while executing on host [xyz].com: Authentication failed for user [xyz]@[xyz].com
```

https://app.shippable.com/subscriptions/540f392a586ac5d7e36513c3

thanks

**Comment by jamesmk** [comment]
It looks like our deployment key changed here: https://app.shippable.com/subscriptions/540f392a586ac5d7e36513c3/subscriptionsSettings

**Comment by manishas** [comment]
@jamesmk i am really sorry about this! Your deployment key did change, so you'll need to update that.

We'll do better about communicating such changes in the future so nobody is caught off guard.

**Comment by jamesmk** [comment]
Ouch, I have to rush update 20-odd projects now. Why did the key change? Can I expect this key to change in the future?

**Comment by lekhab** [comment]
@jamesmk: this was due to a bug in a recent upgrade. So the key shouldn't change again. Sorry abt this.

Since you have multiple projects, you can also add the subscription key to your Github Account, so it's applied to everything. Under your Github profile -> Settings -> SSH keys

**Comment by jamesmk** [comment]
@manishas Did our encrypted variables get reset too?

```python slack_notifier.py --project $PROJECT --org $SLACK_ORG --token $SLACK_TOKEN
option --token requires argument```

**Comment by lekhab** [comment]
@jamesmk: Yes:-( They use the SSH keys as well for encryption..

On a related note, I see you are using our old way of doing slack notifications. We recently launched our integration with slack for build notifications from within Shippable. Details here: http://blog.shippable.com/how-to-use-slack-integration-for-build-notifications

**Comment by jamesmk** [comment]
Also, just noticing I'm at the free tier with 1 concurrent built. I've been a paying customer for almost a year and there's no grandfathering or even a notification that I'm losing 4 minions?

Wow.

**Comment by manishas** [comment]
@jamesmk i see 5 minions for your org. was there another org that should have 5 minions but does not?

we're looking into why the second build didn't get picked up immediately.

**Comment by jamesmk** [comment]
@manishas I just updated my subscription to 5

**Comment by manishas** [comment]
@jamesmk spoke too soon. i see you bought some minions. let me figure out what's going on.

**Comment by manishas** [comment]
@jamesmk just sent you an email about your account. Thanks!

**Comment by lekhab** [comment]
closing since the credit was applied.
