### ISSUE TITLE
Cannot create API token 

### ISSUE THREAD

**Issue by lekhab** [Shippable/support#1797]
Creating issue for @norbe. Original comment on closed issue: https://github.com/Shippable/support/issues/1750

I've got the same problem at our subscription: https://app.shippable.com/subscriptions/54e08c3a5ab6cc13528bff48

**Comment by lekhab** [comment]
@norbe: I see you are on an individual plan. API access is only available with our paid plans. Details [here](https://app.shippable.com/pricing.html). Please let me know if this was related to some other subscription that did have API access earlier.

**Comment by norbe** [comment]
If I take a look at pricing page and select 1 container, I still see API access, so it should be fixed at pricing page at least...

Also some human-friendly error message will be nice if my subscription has not available api access...

**Comment by lekhab** [comment]
@norbe - thanks a lot for the feedback.  will follow up on these.

**Comment by xdothackerx** [comment]
Should be a relatively easy fix for the pricing page. :) @manishas Let me know if you'd like me to implement a change.

**Comment by lekhab** [comment]
the change was made to the pricing page to make it more obvious..

**Comment by n0mer** [comment]
also please include more user-friendly message when user on a free plan tries to create an API token.

Currently it looks like this, on the top of the screen:


![image](https://cloud.githubusercontent.com/assets/1862997/11010466/51f8773e-84df-11e5-8b13-916ead0ec4f0.png)

**Comment by n0mer** [comment]
ping @norbe )

**Comment by norbe** [comment]
I'm pretty sure that I can't help you as I'm only user, not developer of shippable ;)

**Comment by n0mer** [comment]
then ping @lekhab :)

**Comment by avinci** [comment]
@n0mer , currently we allow API tokens only on paid accounts. Can you confirm that you are trying it with an account that has access to one of the paid subs?

**Comment by n0mer** [comment]
@avinci , i'll repeat my comment: "please include more user-friendly message when user on a free plan tries to create an API token"

**Comment by avinci** [comment]
Yup, will add that ASAP.

**Comment by avinci** [comment]
Thanks for the feedback
