### ISSUE TITLE
Sihppable is unaccessible

### ISSUE THREAD

**Issue by rockerhieu** [Shippable/support#1798]
I got this error message on all pages: `Error syncing account Id: [object Object]`

![screen shot 2015-08-18 at 9 19 41 am](https://cloud.githubusercontent.com/assets/1281889/9320960/5360c782-458a-11e5-9682-af66984be095.png)

**Comment by smaiyaki** [comment]
In addition to that, when you try to login, you get thrown out with the message below:
![shippable](https://cloud.githubusercontent.com/assets/1958503/9321007/3eae414e-4593-11e5-8f35-c725255a4e34.png)

**Comment by manishas** [comment]
we're looking into this...

**Comment by nigelwinterburn** [comment]
Same here

**Comment by miraculixx** [comment]
+1 same here

**Comment by manishas** [comment]
We're working to fix this. ETA is 30 mins to an hour at the latest.

**Comment by smaiyaki** [comment]
Awesome. This is fixed now.  Thanks Manishas

**Comment by manishas** [comment]
Everything should be working as expected now. Sorry for the interruption and we will do better to avoid this situation again with better monitoring.

Thanks for your patience!

**Comment by nigelwinterburn** [comment]
I'm seeing this error again
