### ISSUE TITLE
Is there any plan to integrate with Atlasssian JIRA?

### ISSUE THREAD

**Issue by shamasis** [Shippable/support#1799]
Hello there,

Is there any plan to allow integration with Project Management systems? Especially JIRA?

**Comment by lekhab** [comment]
@shamasis - I have tagged this as a feature request. we will prioritize based on customer votes on the request.

**Comment by iolufemi** [comment]
+1

**Comment by malffred** [comment]
+1

**Comment by tbashor** [comment]
+1

**Comment by sdwarak** [comment]
+1

**Comment by tdutrion** [comment]
+1

**Comment by manishas** [comment]
what kind of integration would you want with JIRA? Some scenarios would be helpful to see if we can do this.

**Comment by avinci** [comment]
We have not heard any feedback about this feature. closing this due to lack of interest. If anyone would like to reopen with some scenarios, we can definitely do it.

**Comment by cdroulers** [comment]
Bamboo has an integration with Jira where builds related to an issue (marked with the Issue code) are shown in the issue itself. So any commit that creates a failing build is reported in Jira for easy tracking of broken issues to prevent them from going further in the process. I'm guessing that might be more of a Jira integration thing though.
