### ISSUE TITLE
Account keeps getting downgraded to individual

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1800]
We have started a startup plan in November 2014, which gave us 5 minions. Recently we suddenly had only 1 (which was resolved after a tweet). However a few days back it happened again. So instead of 5 minions, I'm currently stuck with only one

organization is _inventid_ btw

**Comment by manishas** [comment]
@rogierslag sorry about this! your org should show 5 minions again... I'll make sure it doesn't revert again.
