### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by dustinswisstack** [Shippable/support#1802]
I had to transfer my Github repositories to the Github user I am submitting this from. In the process, I lost my "Startup" status in billing. Can you please reinstate that status for us on my account?

Thanks,
Dustin

**Comment by lekhab** [comment]
@dustinswisstack: Followed up on this. Since this is a brand new subscription/account, it falls under the new pricing plans which replaced the startup plans. 

That said, we have given a credit of $40 for 2 cycles for your new subscription. Hope that works.

**Comment by lekhab** [comment]
Please let me know if there is anything else we can help you with. closing the issue.

**Comment by mbrodala** [comment]
@lekhab I have a hard time finding the announcement for the plan changes, can you give me a pointer? We are also currently using the old startup plan for $12 per year and 5 minions and I'm unsure if we continue on this plan or are automatically moved to a different plan.

**Comment by lekhab** [comment]
@mbrodala: The pricing changes were part of our [3.0 announcement](http://blog.shippable.com/devops-2.0-is-here-announcing-shippable-formations-and-enhanced-ci-capabilities) in Jun. You should have received an email as well.

To answer your specific question: You will remain on your existing plan until your subscription period comes up for renewal, at which time you will need to convert to a new plan.

**Comment by mbrodala** [comment]
@lekhab Thanks for clarification.
