### ISSUE TITLE
Builds failing even when all steps are successful

### ISSUE THREAD

**Issue by nigelwinterburn** [Shippable/support#1804]
I think the screenshot pretty much explains it: all green checkmarks yet a failed build. I checked each command and verified that at least they appeared to run successfully.

![screen shot 2015-08-19 at 1 22 23 pm](https://cloud.githubusercontent.com/assets/12054443/9367958/807619f2-4675-11e5-87a6-bd9cf57f6e6a.png)

**Comment by nigelwinterburn** [comment]
Also, I'm seeing the chat notifications from my `after_success` block and not anything from the `after_failure`

**Comment by lekhab** [comment]
internal issue opened. following up on this.

**Comment by chriskinsman** [comment]
I see something similar.  Build shows completely done, post upload artifacts but it just sticks in running state for 15-20 minutes...

**Comment by nigelwinterburn** [comment]
Mine actually exits quickly and returns a failed state just as quickly as
if it had passed. At first it was intermittent but now it's without
exception.

**Comment by nigelwinterburn** [comment]
5 consecutive green builds on multiple branches. I'd consider this closed.
