### ISSUE TITLE
Builds triggered via api failing

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1806]
If I then re-trigger from console they are successful despite no changes in source control...

**Comment by DavidGDragon** [comment]
How are you triggering them via the API?

**Comment by chriskinsman** [comment]
after_success step in shippable.yml:

  - 'curl -H "Authorization: apiToken $API_TOKEN" -H "Content-Type: application/json" -d "{\"projectId\":\"$psjobscriptsid\"}" https://api.shippable.com/workflow/triggerBuild'

**Comment by DavidGDragon** [comment]
You must also specify a `branchName` in the JSON

**Comment by chriskinsman** [comment]
Not sure how that relates:

1.  It is is kicking of the right branch build on master

2. It is working on projects that have multiple branches as is...

**Comment by DavidGDragon** [comment]
Do you have a link to a build where the trigger failed?

**Comment by chriskinsman** [comment]
https://app.shippable.com/builds/55d615587522cc0c004d4ac9

**Comment by lekhab** [comment]
@chriskinsman: we are still looking into this. should have an update for you by tmrw on next steps.

**Comment by lekhab** [comment]
@chriskinsman: we are making changes to our code to fix this scenario - happens intermittently when a number of builds are kicked off simultaneously as in your case. it should be deployed to prod early next week.

**Comment by chriskinsman** [comment]
Thanks

**Comment by lekhab** [comment]
@chriskinsman: We deployed a fix for this a few hours ago. Please confirm if this is resolved on your end.

**Comment by chriskinsman** [comment]
Looks good.  Ran 4-5 builds and had no issues...
