### ISSUE TITLE
Build hangs after uploading artifacts before commit to cache for almost 20 minutes

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1807]
Almost like the commit to cache is taking quite a long time...

Look at exploratron build 1156 in our account to see an example...

**Comment by lekhab** [comment]
following up

**Comment by lekhab** [comment]
@chriskinsman: we had some heavy builds a couple of hours ago which slowed us down a bit - checking to see if this was around the same time. I see your later builds are back to normal times.. did you see this recurring?

**Comment by chriskinsman** [comment]
We have been seeing it off and one for the last couple days.  I will keep an eye on it today...

**Comment by lekhab** [comment]
thanks, please let me know. It does appear to be linked to the heavy load times, when the logs took longer to load.

**Comment by lekhab** [comment]
@chriskinsman: Are you seeing this lately?

**Comment by chriskinsman** [comment]
nope
