### ISSUE TITLE
Builds not pushing Docker image to private repo on Docker Hub

### ISSUE THREAD

**Issue by ryanbaldwin** [Shippable/support#1810]
Everything was working fine up until recently. Now, every one of my builds finishes with the following:

>The push refers to a repository [ryanbaldwin/bunnyhug] (len: 1)
>af694b7d53c8: Buffering to Disk
>af694b7d53c8: Image push failed
>Please login prior to push:
>Username (ryanbaldwin): EOF

I checked and my project still has my docker credentials, and everything seems right, all things considered. Are there any known issues for pushing images to private docker hub repos? I searched the issues but didn't see anything.

Thanks.

**Comment by manishas** [comment]
not that we are aware of. let me follow up....you haven't changed your password for docker hub recently by any chance?

**Comment by manishas** [comment]
@ryanbaldwin can you try to delete the integration, and then add it again through account settings?

**Comment by ryanbaldwin** [comment]
Nope, I've not changed the password on docker hub. I'll try and delete the integration and re-recreate it. Will post back here with my results.

**Comment by ryanbaldwin** [comment]
Just deleted the integration, recreated it, and re-associated it with my project. Build still failed at the final step when attempting to push to docker hub:

>The push refers to a repository [ryanbaldwin/bunnyhug] (len: 1)
>59180db04411: Buffering to Disk
>59180db04411: Image push failed
>Please login prior to push:
>Username (ryanbaldwin): EOF

**Comment by manishas** [comment]
Thanks! We're taking a look and I will let you know if we need more information.

**Comment by manishas** [comment]
@ryanbaldwin we cannot repro this internally, but by reading around, it might be a permissions related issue.

Can you try pushing your image to and pulling your image from this private repository from your local machine? does that work?

**Comment by ryanbaldwin** [comment]
I'll give that a whirl.

**Comment by ryanbaldwin** [comment]
Strange, even after doing a _docker login_ I can't even pull. I wonder if something screwed up with my private repo after I downgraded my subscription. I'll try deleting the docker repo and recreating it, but yea.... strange...

**Comment by ryanbaldwin** [comment]
So I deleted my private repo on docker hub and re-created it, and I can now access it from the command line. However, in shippable, I'm now experiencing errors during _build image_ and and _hub push_ (not sure if they're related, though first place one would think they're mutually exclusive):

##build image
>...
>Status: Image is up to date for frolvlad/alpine-oraclejdk8:slim
>---> 42692a56a638
>Step 1 : MAINTAINER Ryan Baldwin <ryanbaldwin@gmail.com>
>---> Running in d7f55a0fb85f
>---> d6d207af7673
>Removing intermediate container d7f55a0fb85f
>Step 2 : ADD ./buildoutput/bunnyhug.jar /opt/bunnyhug.jar
>buildoutput/bunnyhug.jar: no such file or directory

Did shippable recently change the build output location?

##hub push
>sudo docker push ryanbaldwin/bunnyhug-web:master.25 2>/tmp/push-error.txt
>The push refers to a repository [ryanbaldwin/bunnyhug-web] (len: 1)
>Repository does not exist: ryanbaldwin/bunnyhug-web
Oddly, it does exist. I'm looking at it right now, however there's nothing in it.

I find this all so very confusing as I literally haven't changed anything in my project in probably a couple months. As far as CI and Docker pushes I've not changed *anything*... I'm very confused as to why it all suddenly stopped working.

Thoughts?

**Comment by ryanbaldwin** [comment]
Quick followup: I am successfully able to build the exact same revision if I remove the Docker credentials (i.e. the _build image_ section builds just fine). Something definitely appears to be unexpected here, at least from a consumer perspective.

**Comment by ragsden** [comment]
@ryanbaldwin : I looked at your timeout build and I see that the after_script section did not execute, hence the artifacts were not copied to buildoutput folder. Can you add your docker hub integration and run a build again?

**Comment by ryanbaldwin** [comment]
will do!

**Comment by ryanbaldwin** [comment]
Cool beans, we are all in the clear now. Thanks!

**Comment by ragsden** [comment]
I'm glad everything is sorted out. I will close the issue.
