### ISSUE TITLE
DockerHub push failing silently

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1811]
Since yesterday evening, I am noticing that new builds are not being pushed on to dockerhub. The build shows NO failure logs. 

https://app.shippable.com/builds/55d724676a40ef0b0043106e
https://app.shippable.com/projects/5544d2f4edd7f2c052ddc8f0

This is happening for all of my projects on Shippable.

**Comment by manishas** [comment]
hello, the logs actually show push succeeded. are you saying that your hub shows no images from these builds?

**Comment by lekhab** [comment]
@hshira: can you do a docker pull for your images from Docker Hub and see if you are able to pull the images? it's working when we do.  It may have been an intermittent docker issue.. 

If you are unable to see the images, please let me know and we can regroup again.

**Comment by hshira** [comment]
Yes, no images were pushed to dockerhub. The same job was pushing the code until tomorrow evening. I have run another build. I am expecting it to push an image with tag master.47 If it doesn't push the image with this tag, then I believe there is a problem.

**Comment by lekhab** [comment]
thanks, @hshira. actually, I was suggesting if you could do a docker pull for the expected image and see if that worked (or did you already do this as well?) 

It could be a Docker Hub UI issue.. wanted to eliminate that as a potential cause - we have seen that it sometimes takes a while for the new tags to show up on the Hub.

**Comment by hshira** [comment]
This time build failed.
Error pushing to registry: Server error: 400 trying to push *****/***:master.47 manifest
The same build was passing until now

**Comment by lekhab** [comment]
looking into this

**Comment by ragsden** [comment]
@hshira : I tried running a new build **.master.48 and docker push worked fine. This looks like docker registry related issue. We will keep a watch on this and open an issue with docker folks if this happens frequently.
Related to your issue on not able to see the image, can you try pulling **master.48 image and let us know if it worked?

**Comment by hshira** [comment]
It is working fine now. Not sure why the tags didn't show up, now everything is showing up. Thanks!

**Comment by ragsden** [comment]
Awesome! Closing the issue
