### ISSUE TITLE
Shippable finds 0 projects for CI integration

### ISSUE THREAD

**Issue by marmida** [Shippable/support#1812]
I have a private BitBucket repository that I'd like to integrate with Shippable. I go to the Status page, and there, I see this: 

> New Project
> No projects available to be enabled.

Clicking "force sync" does not change this; it never finds any projects to create. Clicking "New project" on the right does nothing.

It is hinted in #1745 that there might be some additional steps necessary to enable private repository builds, but those aren't enumerated. What do I need to do?

**Comment by lekhab** [comment]
@marmida: For Bitbucket, all repos are turned on by default, so you should be able to view all repos typically. Before I dig into this further, can you please confirm these are Git repos and not Mercurial? We do not support mercurial repos at this point.

**Comment by marmida** [comment]
@lekhab welp, that's the issue - these are Mercurial repos. Thanks!
