### ISSUE TITLE
Artifacts are not being uploaded sometimes

### ISSUE THREAD

**Issue by RealNobody** [Shippable/support#1813]
When a build succeeds or if ONLY RSpec fails, then artifacts are uploaded.

However, (so far) whenever the Cucumber tests fail, artifacts are not uploaded.

Here is a sample Cucumber failure:  https://app.shippable.com/builds/55d78ac1831cd10b00df2f5b
An RSpec failure (with artifacts): https://app.shippable.com/builds/55d7640032a7bd0c00a467a9
And a success: https://app.shippable.com/builds/55d7a2fd1f61b10c00280272

I can't find anything in the console output that tells me why the artifacts aren't being uploaded.  All I see is:

```
script
  <output of running the script>

uploading artifacts to s3
  echo 'skipping upload'
```

What is interesting is that I do NOT see the after script:
```
script:
 - rspec -r yarjuf -f JUnit -o shippable/testresults/results.xml
 - cd dashboard && node_modules/.bin/ember test ci --silent -c testem-ci.json > ../shippable/testresults/emberresults.xml && cd ..
 - DISPLAY=localhost:1.0 xvfb-run bundle exec cucumber --tags ~@skip-ci --format junit --out shippable/testresults

after_script:
 - cp -r cornucopia_report shippable/testresults
```

What I am wondering is why does the after_script not run if Cucumber fails.  I really need the artifacts because they contain diagnostic information to tell me why Cucumber is failing.

Thanks

**Comment by lekhab** [comment]
opened an internal issue to follow up.

**Comment by lekhab** [comment]
@RealNobody: We deployed a few changes to this flow last week. Can you please let me know if you are still facing this?

**Comment by RealNobody** [comment]
> Can you please let me know if you are still facing this?

I still had this problem as of this morning. (2015-08-31 11:00AM PST)

I hadn't heard anything in a while, so I'm trying some things on a purposefully broken branch to see what I can try to figure out.

**Comment by lekhab** [comment]
Thanks, @RealNobody. We are following up on this.

**Comment by RealNobody** [comment]
So, today I was messing around testing what I can...

I changed my RSpec tests so that no tests would do anything and I added a Before Script for Cucumber that would raise an exception.  (RSpecs take no time and all features fail.)  I then changed the script from:

```
script:
 - rspec -r yarjuf -f JUnit -o shippable/testresults/results.xml
 - cd dashboard && node_modules/.bin/ember test ci --silent -c testem-ci.json > ../shippable/testresults/emberresults.xml && cd ..
 - DISPLAY=localhost:1.0 xvfb-run bundle exec cucumber --tags ~@skip-ci --format junit --out shippable/testresults
```

to:
```
script:
 - rspec -r yarjuf -f JUnit -o shippable/testresults/results.xml
 - cd dashboard && node_modules/.bin/ember test ci --silent -c testem-ci.json > ../shippable/testresults/emberresults.xml && cd ..
 - set +e
 - DISPLAY=localhost:1.0 xvfb-run bundle exec cucumber --tags ~@skip-ci --format junit --out shippable/testresults
 - echo "The last return value was: $!"
 - cp -r cornucopia_report shippable/testresults
 - echo "Script finished"
```

When I did this, the results of the test was that the echo after the Cucumber command (nor anything after that in the script) did NOT get run (as far as I can tell) as it was not in the console.  However, the post script DID run and I did have the artifacts.

I went back to the changed script and ONLY removed the `- set +e` line (leaving the echoes and cp in the script.)

That run behaved as "normal" in that the script stops when Cucumber fails and then the post script is not being run and I don't get the artifacts that I want/need.

I do not know what is going on, but that is what I am seeing from the outside.  As far as I can tell, adding the `- set +e` achieves the goal that I have at least - the post script runs when Cucumber fails.  But it doesn't make sense to me why the script always stops after Cucumber fails no matter what I do, or how the change I made fixes a problem I don't understand in the first place.

I hope that some of this helps at least.

**Comment by RealNobody** [comment]
Additional updates:

We have had more tests fail to upload artifacts when they fail at different points.

Previously we had a regular problem with artifacts uploading after Cucumber tests, but in the last couple of days we had two new similar issues:

* Artifacts did not upload when RSpec failed due to a parsing error (bad file name).  No RSpec tests ran at all, so there wasn't much to lose, but there were some things that would have been nice to have anyway...
* Artifacts did not upload when the ember tests (possibly) failed.  I say possibly as this particular test timed out (which could be related to https://github.com/Shippable/support/issues/1828) so I don't know for sure if the test timed out causing the failure or if the test failed and somehow caused the timeout.

**Comment by RealNobody** [comment]
> I say possibly as this particular test timed out (which could be related to #1828) so I don't know for sure if the test timed out causing the failure or if the test failed and somehow caused the timeout.

I found out that the Ember tests were failing legitimately and not due to a timeout.

I detail how/why I found this out in [this issue](https://github.com/Shippable/support/issues/1838)

I have three issues open currently.  I opened them separately because although they may be related, they may not be.

The three issues are:

* [Artifacts not being uploaded](https://github.com/Shippable/support/issues/1813)
  * I think I *may* have worked around this by moving the test calls out of the YML script and instead into a script file.  So far this seems to work, but having had to do this points to some kind of base issue in the system.
* [Build timeouts](https://github.com/Shippable/support/issues/1828).
  * I have not reliable way to reproduce this one, no diagnostics and only a few guesses.  As you can tell, I am trying to find out as much as I can to help you figure this one out.  I just don't have much yet.)
* [Script sections executing out of order](https://github.com/Shippable/support/issues/1838)
  * I only have one instance of this that I have seen/noticed.  I have high hopes that my new YML changes to work around the upload issue may address that one as well.  Again though, it is very weird, and if it is/was an issue for us, it will be for others.  (Not everybody is willing/able to keep throwing "stuff" at a wall until they find a workaround.)

**Comment by RealNobody** [comment]
New update.

https://app.shippable.com/builds/55e9ce34ebb34c0c00e852bc

This build is going into 2 bug incidents.

Related to this incident is that nothing uploaded.

I see the following:

```
+  after_script 0.66 seconds
  +  cp -r cornucopia_report shippable/artifacts
  +  date > shippable/artifacts/end_date.txt
  -  cat shippable/artifacts/end_date.txt
Fri Sep  4 17:51:24 UTC 2015
-  uploading artifacts to s3 0.09 seconds
  +  echo 'skipping upload'
```

There is nothing to indicate why it is skipping the upload, so I don't have a clue what is happening.

Because it may be pertinent, in this build, there is nothing in these three folders:

* shippable/testresults
* shippable/codecoverage
* shippable/buildoutput

Instead, everything is in `shippable/artifacts` to try to empty the coverage and tests tabs per a request from Shippable Support.

My latest build has changed to move everything into `shippable/buildoutput` on the flat out guess that this will cause the files to get uploaded.

**Comment by manishas** [comment]
@RealNobody our docs for artifacts are here - http://docs.shippable.com/build_case2/#artifacts

**Comment by RealNobody** [comment]
> All files in the ./shippable folder at the root of the project are automatically archived for each run upon completion. You can download a tarball of your build's artifacts by clicking on the download archive button on the build page.

The thing is, this documentation isn't correct (as far as I can tell.)

On of the main points of this issue is that I know for a fact that the shippable folder is not empty and that it has all sorts of useful information in it but in spite of having the `archive: true` attribute in our shippable.yml file the artifacts aren't being uploaded.

I assert that success, failure, timeout or whatever, the artifacts should be uploaded.  They aren't, and it seems like they aren't because of some `if` statement on your side that I have no idea what it is doing, but it ISN"T looking in the shippable folder to see if there is something there.

(The other point is that the `after_script` call is often being skipped or called in the wrong order.  Based on the documentation that says that the `after_script` is to be called after the `after_fail` script, it is reasonable to assume that it should always be called even if there is a script failure or a timeout.  Again, this is clearly not the case.)

**Comment by RealNobody** [comment]
This is becoming a critical issue for us.

Latest build:  https://app.shippable.com/builds/55f04bd7d830d20b0022b478

We have been using a script to isolate the run errors and to try to work around the problem of the artifacts not uploading and for the most part it had been working fairly well.

It had been working fairly well that is up till now, but this script failed and there are no artifacts to download which is just really annoying.

Why in the world are you skipping uploading the artifacts?  It just doesn't make any sense.  The folder exists, it has data in it why is it being skipped!

**Comment by trriplejay** [comment]
Hi @RealNobody,

Thanks for all the detailed information! We just deployed a fix that should correct some of the artifact upload issues you were experiencing.  Let us know if you see a difference.  

We're still investigating the timeouts and hope to have more information on that soon.

**Comment by RealNobody** [comment]
> Thanks for all the detailed information!

No problem.  I'm just trying to send in whatever I think might help and hope it does.

Unfortunately, the issue is intermittent.  I have had it happen, then re-run the build and had the same results in terms of errors and not have it happen.

As such, the fact that it works for us for a while doesn't mean it absolutely is fixed - maybe we're getting lucky?

That said, you will definitely hear if I do have a problem.

Thanks for the update.

**Comment by RealNobody** [comment]
> We're still investigating the timeouts and hope to have more information on that soon.

Since you mentioned this, I'll comment on it too.

I may have uploaded this information already, but it's been a long day and I'm tired, and I don't remember, so just in case...

* I have noticed other tickets in the issues list that indicates that others are seeing similar results.  A successful run and then it times out before the last step shows in the console.  That indicates to me it probably isn't something too peculiar about our project or our tests.
* We had a failing test timeout (so it isn't just successes.)  Not sure if I had any failing examples timeout.  I know I had a bunch after success.
* We had a test timeout with an empty testresults folder (The only way I know of to turn off the Tests tab as requested.)  This indicates to me that it probably isn't the parsing of the tests folder.
* Because of an error on our side, I don't have a good sample set to guess at frequency of timeouts caused by Shippable at this time still.  Sorry.

Finally, not diagnostically important, but important in other ways:

My fellow team members are very frustrated that we don't have the Tests tab when tests fail.  We have a workaround in place, but this request isn't helping the teams overall view of Shippable.  The sooner we can put those back, the better.

**Comment by lekhab** [comment]
@RealNobody - Thanks again for working with us through this. We have resolved the issue with the large messages, so you can turn your test reports back on. Thanks a lot for turning it off while we resolved that.
Please do let us know if the fixes we have already put in place have made a difference. We are making more changes to address the timeouts as well.

**Comment by RealNobody** [comment]
> Please do let us know if the fixes we have already put in place have made a difference.

It is hard to say yet, but this script failed then timed out (meaning the timeout is still there) - but we did get the artifacts which was awesome as it allowed me to diagnose the error.

**Comment by RealNobody** [comment]
We have not had a problem with artifacts all day.  It seems reasonable that could be fixed.

I am therefore closing this.  If I have future issues, I'll open a new ticket.

Thanks.
