### ISSUE TITLE
All steps show success, build failed

### ISSUE THREAD

**Issue by lekhab** [Shippable/support#1816]
Opening issue for @leonfs. Transferred from #1579.

Build: https://app.shippable.com/builds/55ddf1047743f10b0029581d

**Comment by leonfs** [comment]
Hi lekhab, Thanks.

Is really weird as the console doesn't give me a single clue on what's wrong.

<img width="1827" alt="screen shot 2015-08-26 at 19 11 33" src="https://cloud.githubusercontent.com/assets/654615/9501981/7b4a23ea-4c26-11e5-8fb4-5f1bcf84da43.png">

**Comment by ragsden** [comment]
@leonfs : I looked at your project settings and found that you have set "Dockerfile" for "Source location" which is a wrong value. This field should be set to the location where your source code exists in the image built during the prior step. You can find more info here http://docs.shippable.com/project_settings/

We will look into why the logs are not showing up. Thanks!

**Comment by lekhab** [comment]
@leonfs: can you pleas update the source location in your project settings and try again?

We have an internal issue open to show an error when this happens instead of failing silently. Marking this resolved, since the immediate issue is resolved.

**Comment by lekhab** [comment]
@leonfs: This is now resolved. If the source code location is incorrect, the build will now fail. Closing the issue.
