### ISSUE TITLE
Code coverage report not useful with Go projects

### ISSUE THREAD

**Issue by ixdy** [Shippable/support#1817]
I tried adding Shippable code coverage support to the Kubernetes unit tests in kubernetes/kubernetes#13171. Shippable parses the coverage XML file without issue, but it reports 0% branch and sequence coverage across the entire project (e.g. https://app.shippable.com/builds/55de3e23f44cfb0c0015a260).

I'm guessing this is because the Go coverage tools seem to only report statement coverage. As it stands, this means that the coverage utility in Shippable isn't really useful for us, however.

**Comment by lekhab** [comment]
tagging this an an enhancement to follow up on.

**Comment by manishas** [comment]
Code coverage has been redone for the new build platform and this should be addressed now. closing.
