### ISSUE TITLE
Feature request: make it easier to identify skipped tests in test report

### ISSUE THREAD

**Issue by ixdy** [Shippable/support#1818]
I created a PR to use Shippable's test report parsing functionality in kubernetes/kubernetes/pull/13114.

A test report from an example run such as (https://app.shippable.com/builds/55de3d96f44cfb0c00153ccf) shows 1886 Passing and 9 Skipped tests, but there is no easy way to identify which tests were skipped.

Additionally, the GitHub commit status shows "Shippable builds completed. 3772/3790 tests passed", not making it clear that there were skipped tests. (Instead, one might wonder why some tests didn't pass, wondering if there were actually failures.)

**Comment by manishas** [comment]
Closing this in favor of https://github.com/Shippable/support/issues/1818 which will track all Test result improvements.

**Comment by manishas** [comment]
Sorry I meant https://github.com/Shippable/support/issues/1582
