### ISSUE TITLE
Can't trigger new builds

### ISSUE THREAD

**Issue by nigelwinterburn** [Shippable/support#1819]
I can't trigger a new build. At first, I thought maybe the Jira-generated super long branch name caused a problem, but now I can't get any branch to trigger a new build. I have reset the project and verified the new deploy keys were added in bitbucket. 

No new jobs appear after successful pushes.

**Comment by lekhab** [comment]
@nigelwinterburn: We had some queue build up for a few minutes around the time you filed the issue which was resolved. Please let me know if you are still facing this. I just ran a manual build for you and it went through fine.
