### ISSUE TITLE
HTTP api for getting build status.

### ISSUE THREAD

**Issue by RX14** [Shippable/support#182]
This would be useful for external applications such as an IDE where they can show whether the build is failing or not. Requires #53

**Comment by keichi** [comment]
+1 for web hook!

**Comment by bittner** [comment]
[shields.io](http://shields.io/) wants me to tell you you should use them.  :smile: 

Travis-CI uses them. The badge image URL looks like this: (shields.io URL vs. Travis-CI URL)

    https://img.shields.io/travis/bittner/django-organice.svg?style=flat
    https://travis-ci.org/bittner/django-organice.svg?branch=develop

 The badge syntax looks like this: (Markdown vs. reST)

    [![Travis](https://img.shields.io/travis/bittner/django-organice.svg)](http://...)
    .. image:: https://img.shields.io/travis/joyent/node.svg   :target: http://...

Shippable is still missing on http://shields.io/
Would be nice and convenient to see you there! That would solve the badge request issue.

**Comment by RX14** [comment]
I love shields.io because it gives me to option of using ?style=flat which is IMO much more appealing than the other style.

**Comment by bittner** [comment]
Great, Shippable is now available from http://shields.io/

Thank you, guys, for listening!

**Comment by manishas** [comment]
Closing this issue. Getting build status through api is documented at - http://docs.shippable.com/build_dashboard/#build-badges

Or you can use shields.io

**Comment by RX14** [comment]
This is not fixed!
![](http://i.imgur.com/3lLr2xI.png)

**Comment by avinci** [comment]
You can use our API to get this information. We are adding more API docs, but technically if you create an account level token on Shippable, you can make any calls to our API on behalf of the user whose account was used to create the token. 

Does that work?

**Comment by manishas** [comment]
Re-opened issue. my bad for closing it.

**Comment by manishas** [comment]
This should be addressed with the new API - http://docs.shippable.com/api/

GET /runs/:id will give you all information for a run, including status. Closing.

**Comment by abhijitkini** [comment]
You can now customize your build badge status on Shippable using shield.io. Read more about it on [our blog](http://blog.shippable.com/customizing-build-badges-for-a-nodejs-project-status).
