### ISSUE TITLE
Can't see my project/builds anymore

### ISSUE THREAD

**Issue by LuisMuniz** [Shippable/support#1820]
Hi,

I use the BitBucket integration to build my repository with shippable.
Since a couple of hours, I have been unable to see my projects, or my organization's project. The list is empty.

When I go back and click on a link to one of my previous builds, I can see the following error message:

    {"id":1005,"message":"Internal API error : getPermissionByProjectId","methodName":"chkPermForId|_getSByProjectId"}
    Build not found.

When I try to add a new project from my bitbucket account. The list of my repositories does not show up.

I have seen on twitter that there are performance issues with bitbucket, but this is totally different, my full setup has disappeared aand I can't seem to be able to restore it.

**Comment by lekhab** [comment]
@LuisMuniz: This is probably related to the issues at Bitbucket. I am following up on this - in the meantime,  can you please try force syncing your account and let me know if that works? [Account Settings -> Force Sync]

**Comment by LuisMuniz** [comment]
Hi,

Thanks for the workaround!

After force syncing, I can see my projects again.

Thanks


Luis Muñiz
IT Director – Research and Development, Architecture | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | M : +34 647 79 34 76
luis.muniz@b2boost.com<mailto:luis.muniz@b2boost.com> | www.b2boost.com<http://www.b2boost.com/>

Please consider the environment before printing.


From: Lekha Bhargavi
Reply-To: Shippable/support
Date: Thursday 27 August 2015 19:02
To: Shippable/support
Cc: Luis Muniz
Subject: Re: [support] Can't see my project/builds anymore (#1820)


@LuisMuniz<https://github.com/LuisMuniz>: This is probably related to the issues at Bitbucket. I am following up on this - in the meantime, can you please try force syncing your account and let me know if that works? [Account Settings -> Force Sync]

**Comment by lekhab** [comment]
Great. It was a temporary glitch due to the Bitbucket issues. Closing the issue.
