### ISSUE TITLE
[Security] Builds and details still accessible when user is excluded from Bitbucket organization

### ISSUE THREAD

**Issue by bittner** [Shippable/support#1821]
When you're part of an organization and you create a Shippable account by logging in using e.g. Bitbucket you can see all public and private repositories.

When your account is removed from the Bitbucket organization then you can still see the builds, and you can still even inspect the details of all builds.

Is this behavior intended?

**Comment by lekhab** [comment]
@bittner: Apologies for the delay in getting back to you.  This is definitely not intended behavior.  This was probably related to a lag in syncing the account with the updated permissions. Are you still seeing this?

**Comment by bittner** [comment]
Alright, looks okay. What is the sync delay, usually?
