### ISSUE TITLE
Repos moved to new organization on GitHub won't be listed in Projects list

### ISSUE THREAD

**Issue by bittner** [Shippable/support#1822]
I had some public repositories on GitHub and Bitbucket under my personal account last year when I started to integrate them with Shippable.

I've moved the repos into a [new organization](https://github.com/Organice) on [April 7](https://twitter.com/organice_io/status/585499869852409857) this year both on GitHub and Bitbucket. For your Bitbucket integration this was not a problem, I think it continued to work without an intervention (though I'm not 100% sure whether or not I had to reactivate the repos). For GitHub, however this has proven to be a severe problem:

## New ID for repos moved to GitHub organization?

When I go to `Home` > `CI` (dropdown) > `Organice` (my GitHub organization) the [subscription page](https://app.shippable.com/subscriptions/5445fe05b904a4b21567c28e) that loads has an empty Projects list, no big Plus (+) sign to click on top, instead just a "Force sync" icon to click on the top right corner. When I try to force sync still no projects appear.

When I now try to go to `Settings` (tab on the right), and click the `Reset` button in the "Reset Subscription" section the following error message occurs on top of the page in red color:

``` json
{"id":3300,"message":"Owner not found for subscription.","methodName":"resetById|_getSubscriptionOwner"}
```

Looks like you're referring to the repo with an ID, and the ID has changed after the repo was moved to the new organization.

## Any quick fix available?

Apart from this being a bug report for the GitHub integration, how do I fix that problem in my Shippable account? I need builds also for pull requests, I can't have that with Bitbucket at the moment. That's why I need the GitHub integration to work.

**Comment by rageshkrishna** [comment]
@bittner Can you please check if you have enabled third-party access for Shippable on the new organization? You can verify this by visiting https://github.com/organizations/Organice/settings/oauth_application_policy.

If GitHub's access restrictions are enabled for the org and you don't see Shippable listed on that page, you will need to enable it by following the instructions at https://help.github.com/articles/approving-third-party-applications-for-your-organization/

**Comment by bittner** [comment]
That's a good hint, thanks!

Now, the problem is I have no pending requests under the "Third-party access" tab. And it seems that it's not possible to trigger a third-party request for the Shippable UI. When I click on "Force sync" in the Shippable project settings nothing happens on GitHub.

How can I fix that?

**Comment by lekhab** [comment]
@bittner:  just confirming  that you have set the policy for the org as "No restrictions" for third party access before trying out @rageshkrishna's suggestions.

http://docs.shippable.com/faq/#why-cant-shippable-see-my-org-on-github

**Comment by bittner** [comment]
That fixed it: The `Private Repos OFF` button in  the GitHub Identity section showed a dialog to allow access permission. (I didn't have to actually turn private repos on.)

Thanks.
