### ISSUE TITLE
Feature Request: Validate Docker Hub Credentials on save

### ISSUE THREAD

**Issue by behemphi** [Shippable/support#1823]
When I save my Docker hub credentials, I don't know for sure I have them right.  This presents a problem later if I don't get the expected result because I don't necessarily know where the problem lies.  If I do know the problem is the credentials I have to navigate away to the right place to attempt a fix at which time I am still in the same situation: I don't _know_ I have them right.

Thanks for a cool product.

**Comment by avinci** [comment]
we are doing this now. Please let us know if not so.. also invalid creds are also shown in the console now.
