### ISSUE TITLE
UNSTABLE build still calls after_success

### ISSUE THREAD

**Issue by LuisMuniz** [Shippable/support#1825]
Hi,

I read from diverse sources that I should place my deployment instructions in after_success, but I found out today that my unstable build was deployed to my production environment, why is this? Should I put my deployment code somewhere else? Should I check the build status myself?

**Comment by avinci** [comment]
is this still happening? just want to make sure as I remember folks fixing this. If its happening please reopen.

**Comment by LuisMuniz** [comment]
Yes, this still happpened last sunday

https://app.shippable.com/builds/566d926fe9a7dc0c00c7f254

**Comment by LuisMuniz** [comment]
I don't know how to reopen the issue. there is no obvious button in the interface to do that.
