### ISSUE TITLE
Builds timeout after success

### ISSUE THREAD

**Issue by RealNobody** [Shippable/support#1828]
This is not something that happens every time, but it has been happening a reasonable amount recently.

Sometimes when we run a build, it times out.  I have not identified any reliable circumstances under which this happens.

When I look at the timed out builds, I cannot see anything in the console output that indicates why it timed out.  In the console output, I see the same basic output as I do for a successful run except that the last step that is shown is `uploading artifacts` and the `save_reports` step is the only missing step.

If we do get a timeout, running it again often gets a green build.

The test suite on average runs for about 30 minutes, well within the 2 hour or so timeout.

The only diagnostic information I may have is the following:

The time for a script does not seem to be based on how long a test actively runs.  The time starts as of the moment that the test build button is clicked rather than as of the time that the test actually starts doing active work.  I have seen at least one timeout where a test started and couldn't get a worker for the timeout period so it never even pulled the code from git or anything, it just timedout waiting.

I don't know in any of the timeout failures we have if this is a factor or not.  It could be in that if the timeout is 2 hours and the run sits for 1.9 hours before starting to pull and run, the timeout could be a false negative because the total run time was too long.

It seems weird to me though that in 5 or 6 timeouts that I can remember looking at they all failed at the same point - right after uploading artifacts.

From my perspective, it seems like one of the following may be happening:

* The timeout is occurring because shippable is doing some post processing work that is getting into some kind of infinite loop and timing out.
* The timeout is only checked at certain points which would allow the script to start running, run and then fail at the first checkpoint.

It would be nice if the timeout time was based on the run time after it gets a worker rather than from the time that the build is started.  That would make more sense to me.

**Comment by dustinswisstack** [comment]
@lekhab Can we get some attention to this? Shippable is becoming an impediment to our progress and we are considering a move to another system if we cannot resolve our issues within the next week or so.

Thanks!

**Comment by jawaid** [comment]
@RealNobody  & @dustinswisstack 

we would look into this

**Comment by manishas** [comment]
@RealNobody @dustinswisstack we are looking into all your open support issues and will have an update as soon as we know more.

We did have one request - can you please turn off your test and coverage reports temporarily? We realized that the size of your reports is causing some problems on our platform that is affecting performance for other customers. We need to look into this more as well and will let you know when you can turn reports back on.

**Comment by RealNobody** [comment]
> can you please turn off your test and coverage reports temporarily? We realized that the size of your reports is causing some problems on our platform that is affecting performance for other customers.

I will look into how to do this and do it as soon as I can.  I have an alternative that we can use while you resolve this.

**Comment by RealNobody** [comment]
We have one outlier:  https://app.shippable.com/builds/55e960907f23310c00b963cc

<img width="1126" alt="screen shot 2015-09-04 at 10 01 41 am" src="https://cloud.githubusercontent.com/assets/358891/9689678/82bf3a80-52ec-11e5-846c-f5d61d46a8d4.png">

No idea what happened.  I asked the team to leave it for you to look at if you wanted to.

If you don't let me know please so I can kill it.

**Comment by RealNobody** [comment]
Because you asked me to turn off tests, I looked at how they work.

I came in later to the  project and knew little about Shippable.

As such, I made a mistake which I am correcting that probably didn't help.

I put files into the `testresults` folder which weren't test results.

After I realized that this could be a problem - I went looking for documentation about the post_build step and where I could/should put artifacts I want to keep.  It was really hard to find.  It also wasn't very clear from my perspective.

**Comment by RealNobody** [comment]
Here is a fun one for you:

https://app.shippable.com/builds/55e9ce34ebb34c0c00e852bc

This one I know a little about the timeout.

* I know it started almost immediately after it was posted.  (i.e. it didn't sit around in a waiting state for long if at all.)
* I know that the `instal` step started at Fri Sep  4 17:04:27 UTC 2015 - which basically jives with the 10:00 AM start time listed and the time for the steps before this point.
* I know that all tests were completed at: Fri Sep  4 17:51:24 UTC 2015 - well under the timeout period.
* I know that due to a problem in my branch - a TON of tests failed.  (Should be irrelevant to the timeout I think, but just acknowledging our problems.)
* I know that the folder `shippable/artifacts` had to have had lots of useful information in it.
* I know that nothing got uploaded to S3 - All I see is that this was skipped.
* I know that the following folders probably did not exist or should have been completely empty at the end of the `script` phase.
  * `shippable/testresults` - NOTE: as tests run, the results are put here, but are moved afterwards.
  * `shippable/codecoverage`
  * `shippable/buildoutput`
* I know I put all of the stuff I wanted to keep into `shippable/artifacts`.

Maybe it timed out because I moved the `shippable/testresults` and `shippable/codecoverage` folders and that caused your scripts to freak out?

I don't know.  I just know that it took just under an hour to get to the after_script, it didn't upload anything, it didn't save reports (whatever that is), and it timed out.

**Comment by RealNobody** [comment]
We now have a reproducible timeout.  The thing is that the fact that it is so reliably reproducible indicates either that you changed something that makes it way worse, or that we did something to make it worse.  I really don't know which.

The problem we are having now is that our Ember tests are always timing out.  They used to be just fine.

They run locally extremely quickly, but seem to freeze on the test runs.

I'm going to try to pull an old branch and see if it is the environment or code changes.

**Comment by RealNobody** [comment]
> I'm going to try to pull an old branch and see if it is the environment or code changes.

ARGH!

I can't do that.  You do a merge with develop as part of your build process which negates any attempt to run an old branch.

**Comment by RealNobody** [comment]
> I'm going to try to pull an old branch and see if it is the environment or code changes.

There was a bug in the Ember tests that caused them to hang indefinitely.

I have fixed that timeout issue.

**Comment by RealNobody** [comment]
Just so we're clear - we still have unexplained timeouts in the recent past.  I don't know yet if not putting anything into the testresults folder helps or not.

**Comment by RealNobody** [comment]
This happened again today:

https://app.shippable.com/builds/55f0685fc9a9450b00003777

This build does NOT have anything in the `testresults` folder.

So, we turned off the Tests tab for you, and it is still happening.

I noticed today that I'm not the only one having this problem it seems:  https://github.com/Shippable/support/issues/1860

The odd thing here is that it looks like it uploaded the artifacts.  I'm waiting for the build to timeout to see if I can actually get them or not.

(NOTE:  I'd like to be able to get them even if I cancel, but something tells me it is highly unlikely that the download link will exist if I don't wait for the timeout, and I don't have high hopes if I do wait...  I'm crossing my fingers.)

**Comment by RealNobody** [comment]
Another incident:

https://app.shippable.com/builds/55f0cfc7f7cb7d0b0052432b

* I did not start this run, so I do not know how long it might have sat in a waiting state.  I doubt it did though.
* According to the build details - test started at: 2015/09/09 - 5:33 PM (UTC - 7)
* Our code started at: Thu Sep 10 00:35:08 UTC 2015 - 2 minutes later which is reasonable
* Our code ended at: Thu Sep 10 01:22:21 UTC 2015 - Slightly less than 1 hour later
* This run has the `Tests` tab and the `Coverage` tab turned off per previous request.
* Artifacts DID get uploaded properly.
* The run shows as a timeout.

Good news - Artifacts uploaded allowing me to diagnose failures that occurred in the run.
Bad new - It is still getting a false timeout.

NOTE:  I have been told I can turn the Tests tab back on, so we will be doing that.

**Comment by RealNobody** [comment]
Just saw this one too:

https://app.shippable.com/builds/55f0a6230b2b130c00382b7f

* Run time of our code about 50 minutes
* Artifacts did upload
* Tests tab disabled
* Script was successful - only error was the timeout.

I don't know if you care about all of these.  I update you with information on each run so you have more examples to look at for diagnostic purposes.  If you don't want me to keep updating like this, just let me know.

**Comment by RealNobody** [comment]
This one hasn't timed out yet, but it will eventually at this point:

https://app.shippable.com/builds/55f1d35670bb320b008dfb92

**Comment by ragsden** [comment]
@RealNobody : we have rolled out a fix which should fix the timeout issues you are seeing. We will keep an eye on your builds. Sorry about the inconvenience.

**Comment by RealNobody** [comment]
Thanks.
I haven't seen a timeout in a bit today.

Unfortunately, the timeouts weren't reliably reproducible.  I'll leave this open for a day or so.  If I don't see any timeouts, I'll close it.

**Comment by RealNobody** [comment]
We had another incident today:

https://app.shippable.com/builds/55f322ae2663230b002e5928

* Our code ended after about 1hour 30 minutes (approximately)
* start - Fri Sep 11 18:54:32 UTC 2015
* end - Fri Sep 11 20:22:19 UTC 2015
* The console output for the post steps seems to be bad/wrong - Something new.
* The artifacts DID work (a different bug I had been having persistent problems with.  Just saying that one does seem to be fixed.)
* It DID get to the save_reports step this time.  Don't know what that means.

So, I'm keeping this one open for now.

We are having

**Comment by RealNobody** [comment]
This timed out:

https://app.shippable.com/builds/55f86e446910ec0b0083331c

NOTE:  We've had some other tests recently failing on the `npm_install` - not sure why.

I don't know if this is related or not as the post steps didn't run and there aren't any timestamps to know what happened when.

It seems unlikely that whatever happened was us, but I can't rule it out on this one.

**Comment by RealNobody** [comment]
Another unknown timeout:

https://app.shippable.com/builds/55f859ac5821fa0b004c7bcb

**Comment by RealNobody** [comment]
Another timeout:

https://app.shippable.com/builds/55f88373e20ad80d0065fcb7

It took 1:20 to get to the start of the RSpec tests which seems a bit long.  The Rspecs shouldn't have taken long enough to timeout based on past experiences.

Also, this one didn't run the post scripts OR upload the artifacts which were issues that were supposed to have been fixed.

**Comment by RealNobody** [comment]
This build had the same issues:

https://app.shippable.com/builds/55f8858ba62c630d00bd012b

NOTE:  I can verify our code running for about 1:30 minutes till the RSpecs start.

It doesn't look like the RSpecs run at all almost from the console output so this one almost certainly shouldn't have timed out based on what I'm seeing in the console.

But the artifacts didn't upload and it didn't run the after script.

**Comment by RealNobody** [comment]
Again: https://app.shippable.com/builds/55f9cf574eb90d0c009eacfb

This one didn't do anything at all, so there wasn't anything to timeout.

**Comment by RealNobody** [comment]
Again: https://app.shippable.com/builds/560ec3bc013d9a0f002e4d50

RSpec and Cucumber tests appear to have completed successfully, but the system timed out without running Ember tests.

**Comment by jawaid** [comment]
@RealNobody  are you still have this issue?

**Comment by RealNobody** [comment]
Huh.  I've stopped monitoring Shippable failures very closely as the team has come to just sort of expect them and I hadn't heard anything in a while.

So, I looked, yes, we seem to still be having problems:

![image](https://cloud.githubusercontent.com/assets/358891/10594695/8d8c1008-7684-11e5-8dd1-99730362ed61.png)

I particularly love the timeouts that ran for less than 2 hours myself.
