### ISSUE TITLE
scala: console output format is borked

### ISSUE THREAD

**Issue by ahjohannessen** [Shippable/support#1829]
Recently the console output format from build log is borked. We get output like this:

```
[2K[0m[[0minfo[0m] [0mResolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.4 ...[0m
[A
[2K[0m[[0minfo[0m] [0mResolving org.scala-lang.modules#scala-xml_2.11;1.0.4 ...[0m
[A
[2K[0m[[0minfo[0m] [0mResolving com.google.protobuf#protobuf-java;2.6.1 ...[0m
[A
[2K[0m[[0minfo[0m] [0mResolving com.trueaccord.scalapb#scalapb-runtime_2.11;0.4.15 ...[0m
[A
[2K[0m[[0minfo[0m] [0mResolving com.trueaccord.lenses#lenses_2.11;0.3 ...[0m
[A
```
and
```
[0m[[0minfo[0m] [0m[33mNo tests were executed.[0m[0m
[0m[[0minfo[0m] [0m[32mBehaviourTestingSpec:[0m[0m
[0m[[0minfo[0m] [0m[32mBehaviorTesting[0m[0m
[0m[[0minfo[0m] [0m[32m- should provide given-when-then with success[0m[0m
```

**Comment by lekhab** [comment]
@ahjohannessen: can you add the build links here, please? I am not able to reproduce this with any of our scala samples.

**Comment by ahjohannessen** [comment]
One example is here https://app.shippable.com/builds/55e4d3a056d4420b00dc3182

**Comment by lekhab** [comment]
thanks. looks like we are not parsing the color codes correctly. opening an internal issue to track this.

**Comment by ahjohannessen** [comment]
It seems like a regression because it has worked earlier

**Comment by lekhab** [comment]
@ahjohannessen: The color codes are being parsed correctly in the console outputs now. Can you please confirm?

**Comment by ahjohannessen** [comment]
@lekhab Things are back to normal, thanks!
