### ISSUE TITLE
Bitbucket webhook not triggering builds

### ISSUE THREAD

**Issue by deosjr** [Shippable/support#1831]
Hi,

It seems like since today commits to any of our existing bitbucket repositories that were registered to shippable are not triggering new builds anymore.
I think the last automatic build was this morning, any after that we had to trigger by hand in the shippable webapp.

My bitbucket account is "sndost", using the "to-increase" team account.

**Comment by satyasrikantmantha** [comment]
This is rather urgent as our development is stalled. Kindly Prioritize...

**Comment by mbrodala** [comment]
It seems like this is actually a [Bitbucket issue](http://status.bitbucket.org/incidents/8h11jljfd445).

**Comment by lekhab** [comment]
@satyasrikantmantha: @mbrodala is right.This is a Bitbucket issue - please follow the update on their issue link [here](http://status.bitbucket.org/incidents/8h11jljfd445)

**Comment by satyasrikantmantha** [comment]
I am also experiencing issues with the UX, it shows loading the app for long..
![image](https://cloud.githubusercontent.com/assets/9287965/9609579/15bc195e-50f2-11e5-9819-0113bb92108a.png)

**Comment by mbrodala** [comment]
@satyasrikantmantha See #1724

**Comment by lekhab** [comment]
@satyasrikantmantha: the shippable service is back up now. (bitbucket issue is still open)

**Comment by lekhab** [comment]
the bitbucket issue is resolved now.. closing this.
