### ISSUE TITLE
Source location not set to value specified within "Settings"

### ISSUE THREAD

**Issue by leonfs** [Shippable/support#1832]
Hi,

I'm getting failures on the builds due to a problem on the working directory path not being set to the value specified within Settings.

If I run:
```
before_install:
  - pwd
````
I get /root

I had to run in order to have successful builds:
```
before_install:
  - cd $SHIPPABLE_REPO_DIR
```

Link to failed build
https://app.shippable.com/builds/55e63a79fe05460b00f9f989

**Comment by lekhab** [comment]
@leonfs: This was a bug in our nodejs script that is now fixed. You should now be able to run your project without adding the additional line in before_install. Please let me know if you have any further issues.

**Comment by leonfs** [comment]
Hi Lekhab,

I confirm that is fixed. Thanks!!

**Comment by lekhab** [comment]
Great. Closing issue.
