### ISSUE TITLE
Errors when trying to force sync or trigger build by push

### ISSUE THREAD

**Issue by EHLOVader** [Shippable/support#1834]
I have some strange errors showing up on the top of the page, and recent pushes don't appear on shippable. 

```json
{"id":1005,"message":"Internal API error : getProjectById","methodName":"chkPermProjectId|_getProjectById"}
```

Force sync also produces a different error that appears across the top.

```json
{"id":3300,"message":"No Owner for subscriptionId::555d3a2eedd7f2c052f68fb8","methodName":"caller:555d3a6dfba96c0c005d4377|subscriptions|syncById:555d3a2eedd7f2c052f68fb8|_getValidOwner"}
```

**Comment by lekhab** [comment]
@EHLOVader: This should be resolved now. We just deployed a fix. Please let me know if you are still facing issues.

**Comment by EHLOVader** [comment]
Confirmed that it is working. Thank you.
