### ISSUE TITLE
Previous Build History Gone

### ISSUE THREAD

**Issue by hillbilly90** [Shippable/support#1835]
Over the past 2 months we have been using shippable to deploy to our Amazon server. As of today, I can't see any of the previous builds. It even says 'No builds have been triggered yet.'

Any ideas?

**Comment by lekhab** [comment]
@hillbilly90: following up. I don't see any projects that can be enabled on your subscription. Can you confirm the subscription is this: https://app.shippable.com/subscriptions/5524db225ab6cc1352bbd5f0/

**Comment by hillbilly90** [comment]
It was connected to my github account and was a private repo. I believe it was here: https://app.shippable.com/subscriptions/5524da9e5ab6cc1352bbd4e4

**Comment by lekhab** [comment]
@hillbilly90 - this is most likely related to the ongoing bitbucket issue: http://status.bitbucket.org/ - we can't get projects for your subscription from bitbucket.

**Comment by lekhab** [comment]
sorry, we crossed each other. Following up on the GitHub subscription. I can see the build details on our system..

**Comment by hillbilly90** [comment]
![image](https://cloud.githubusercontent.com/assets/5092385/9639739/b7169e64-516a-11e5-9964-ab68df26d9fe.png)

**Comment by lekhab** [comment]
Thanks @hillbilly90. We are investigating as a high priority issue.

**Comment by hillbilly90** [comment]
Thank you

**Comment by lekhab** [comment]
@hillbilly90: We just deployed a fix for this. Please let me know if you are still facing any issues.

**Comment by hillbilly90** [comment]
Will this take a few hours to take affect? I am still not seeing anything. Thanks

**Comment by trriplejay** [comment]
@hillbilly90 Can you try clicking the 'force sync' button on your account settings page? Let me know if that works for you.

**Comment by hillbilly90** [comment]
Ahhh yeah! See I tried that before and it didnt work. It must have been your fixes. 

Thanks a ton! Everything seems to be good.
