### ISSUE TITLE
Error while accessing my build details

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1836]
Hi,

I get an error if I try to access https://app.shippable.com/projects/557f0f35edd7f2c0521800b4

The error I get is: {"id":2100,"message":"No build found","methodName":"validateCaller|_checkAccessLevel"}

**Comment by lekhab** [comment]
@rvdwijngaard: we are investigating this as we speak..

**Comment by lekhab** [comment]
@rvdwijngaard: This should be resolved now. We just deployed a fix for this. Please let me know if you are still facing issues.

**Comment by rvdwijngaard** [comment]
yep it is resolved now; thanks

**Comment by sojharo** [comment]
I am still having this issue whenever I run build manually. Also, when I commit the code, it doesn't start building automatically, in fact, it doesn't even know that commit has been made. I have a private bitbucket repository.

**Comment by taz77** [comment]
Same issue here too.  Seems many people are having this problem and no response on Twitter either.
