### ISSUE TITLE
Feature Request: Docker build and register moved from GUI to YAML

### ISSUE THREAD

**Issue by behemphi** [Shippable/support#1839]
It would be ideal if the description for the docker build & register was done in the YAML instead of the UI where it would be part of the project and, most importantly, under source control.

By docker build/register, I mean essentially this: 

![screen shot 2015-09-02 at 6 48 49 pm](https://cloud.githubusercontent.com/assets/522972/9647517/7084fa5c-51a3-11e5-90ed-7ce95ceae651.png)

**Comment by manishas** [comment]
this is absolutely on our roadmap and we'll get to this soon. Thanks for the feedback!

**Comment by manishas** [comment]
We have moved all docker workflows to the yml with the build system upgrade. You can try the new yml format explained at http://docs.shippable.com/ci_configure/ after your account is upgraded (ETA < 48 hrs).

You'll know you are upgraded when your subscription plan on billing page shows Continuous Delivery.
