### ISSUE TITLE
Ubuntu 14.04 with PHP and Apache to test Drupal websites

### ISSUE THREAD

**Issue by taz77** [Shippable/support#1840]
I have been working with Shippable for a few days. I like the service but so far I cannot get the environment I need for various reasons.

Using the default image which is Ubuntu 12.x you get Apache 2.2 and not 2.4. My production enviornments are 2.4. Reading through the issue queue I found the image `shippableimages/ubuntu1404_php`, so I began to use it.

This image does easily give me Apache 2.4 with an `apt-get -y install apache2` but I have run into other problems. Unlike the standard Ubuntu 12.x image this image clones the repository as `root` instead of user `shippable` and is running as `root`.

Is there an easier option to getting to Apache 2.4/PHP without doing a lot of configuring in the YAML to setup the image `shippableimages/ubuntu1404_php` to be like the Ubuntu 12.x in how it runs?

**Comment by lekhab** [comment]
@taz77: Following up on this internally. The fastest way is probably to take one of the Docker files, customize it to your needs and create a custom Docker image that you can then use for your projects. 

Will let you know what I find.

**Comment by taz77** [comment]
That is partially what I was afraid of having to do. I will keep working on it. 

For you guys I guess you may want to look into having an option in the default docker images. Apache 2.2 is getting old and 2.4 has a lot of performance improvements with how it runs. Getting 2.4 onto Ubuntu 12.x takes a lot of configuration from what I can find on Google searches (I am primarily a RHEL person so I have to google Ubuntu stuff, haha).

**Comment by lekhab** [comment]
@taz77: Custom images are currently the way to go. Making it easier for images to be customized for our users is already on our roadmap. You should hear more as we make progress on this later this year. 

Will change this to a feature request, so it can be tracked.

**Comment by taz77** [comment]
Thanks! I did some work arounds and got what I needed with 12.x

**Comment by manishas** [comment]
Closing this since we have a new set of official images. If you have very specific requirements for what is installed on an image, you should use custom images for your build.
