### ISSUE TITLE
Docker ENV parameter

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#1841]
Hi,

How I can specify ENV parameters from .shippable.yml matrix to docker ? 

I need to run Code in different docker images depending on ENV parameters

**Comment by taz77** [comment]
Like this? 

env:
  global:
    - VARIABLE1=data1 VARIABLE2=data2

**Comment by luckyraul** [comment]
I really need PHP version and custom param
for example
```
php:
  - 5.5
  - 5.6
  - hhvm
env:
  matrix:
    - MAGENTO_VERSION=magento-ce-1.9.1.1
    - MAGENTO_VERSION=magento-ce-1.8.1.0
    - MAGENTO_VERSION=magento-ce-1.7.0.2
```

**Comment by lekhab** [comment]
@luckyraul: I hope I am understanding your use case correctly. You should be able to specify these environment variables as you have done above and use the before_install section to install the right version of Magento for each of the matrix build.

Something like this:

```
before_install:
  - if [[ $MAGENTO_VERSION == "magento-ce-1.9.1.1" ]]; then <insert the right version to use>

```

Let me know if that works for you.

**Comment by luckyraul** [comment]
Without docker now I have this matrix and I need to test my code in every magento version on every php version
```
php:
  - 5.5
  - 5.6
  - hhvm

env:
  matrix:
    - MAGENTO_VERSION=magento-ce-1.9.1.1
    - MAGENTO_VERSION=magento-ce-1.8.1.0
    - MAGENTO_VERSION=magento-ce-1.7.0.2
```

There is a script installing downloading magento by env MAGENTO_VERSION , merge with my repository code and run tests. 

Downloading Magento and Installing takes too long time. 

So I am going to make it with docker

I got in mind two possible ways: 

1) Create docker image with all magento versions installed and all php versions installed and via some file or variable from Matrix copied or added as run parameter to image.

2) Create different docker images(or different tags) with one magento version installed and one php version accordingly and via some configuration on shippable choose which Docker image I need and run inside image

**Comment by lekhab** [comment]
@luckyraul: You should be able to do (1) using environment variables.  The [Java sample](https://github.com/shippableSamples/sample_ubuntu1204_java) we have does do something similar, so take a look at that YML for some pointers.

(2) is not possible - you cannot have different docker images across the same build matrix.

**Comment by DavidGDragon** [comment]
You can create a build with 9 jobs, where is job has a specific version of PHP and magento version.
Your env setup is good, but you'll need to add a script to install the version of megento you want to use.
Note: I only put the version number in the $MAGENTO_VERSION to make it easier for the script later.
```
php:
  - 5.5
  - 5.5
  - hhvm
 
env:
  matrix:
    - MAGENTO_VERSION=1.9.1.1
    - MAGENTO_VERSION=1.8.1.0
    - MAGENTO_VERSION=1.7.0.2

before_install:
  - echo $MAGENTO_VERSION
  - . install_magneto
```
Where  `install_magento` is a script file in the root of your repo with the following:
```
#!/bin/bash 
echo http://www.magentocommerce.com/downloads/assets/$MAGENTO_VERSION/magento-$MAGENTO_VERSION.tar.gz
wget http://www.magentocommerce.com/downloads/assets/$MAGENTO_VERSION/magento-$MAGENTO_VERSION.tar.gz
tar -zxvf magento-$MAGENTO_VERSION.tar.gz
mv magento/* magento/.htaccess .
chmod -R o+w media var
chmod o+w app/etc
```
This downloads and installs the version of megento based on the environment variable you specified.
1: Prints the URL of the download
2: uses WGET to download the file
3: uncompresses the file
4,5,6: moves and gives permissions on the files

I noticed you are using CE edition, so the download link may need to be structured differently to accommodate that.
Additionally, you could include the uninstalled magento versions in your image and install the version you want during runtime to skip downloading it each time.

**Comment by luckyraul** [comment]
All you described is the current scheme which I have. 

It's quite long setup. I want to use docker image. 

Java example is not I want. Both your examples are irrelevant and not have anything close with docker

**Comment by DavidGDragon** [comment]
You can generate a docker image using a dockerfile using the shippable image base and adding Magento on top of it. You can install every version of magento you want, and instead of doing the move command in the script you'd move them to folders with the version name. Then during runtime you move the version you want to use to the correct directory. This way you don't have to download or install, just move the folder. https://docs.docker.com/reference/builder/

If needed I can provide more detail next week.

**Comment by luckyraul** [comment]
This sound interesting, so if shippable base image understand ENV params - I can use it
