### ISSUE TITLE
cannot set to blank project option "Pull Image from:"

### ISSUE THREAD

**Issue by gtnx** [Shippable/support#1843]
If i leave the field blank, i cannot save. I got a message:

    Some errors were detected with your project settings:
    Requires an image name to pull.

**Comment by lekhab** [comment]
@gtnx: There is a trash icon below the settings that you can use to clear your project settings. Please try that and re-try. Screenshot below.

![screen shot 2015-09-03 at 11 44 14 am](https://cloud.githubusercontent.com/assets/9526532/9667578/687af044-5231-11e5-9af6-0ecd5d78057d.png)

**Comment by gtnx** [comment]
Indeed, thanks!
