### ISSUE TITLE
Build timeout in "boot"

### ISSUE THREAD

**Issue by pnpritchard** [Shippable/support#1844]
All of my builds have been failing due to "timeout" since yesterday afternoon. I can't think of any change to my code that would have caused this. From the console view, looks like it is stuck in the "boot" stage. It is also weird that this stage is not at the end of the list, even though it is still running.

![image](https://cloud.githubusercontent.com/assets/5124612/9672176/1999a8aa-524d-11e5-987f-2157fbf4a8f6.png)

**Comment by lekhab** [comment]
@pnpritchard: following up on this.

**Comment by pnpritchard** [comment]
@lekhab seems like this was just affecting one commit. After pushing more commits, it is not happening anymore.
