### ISSUE TITLE
No builds running on my account

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1850]
automated builds are not working for my account. Also if I trigger a manual build, I get an error.

https://app.shippable.com/builds/55e98d0a781a6d0c002e9c73
https://app.shippable.com/builds/55e977b756443b0c00cecdb0

**Comment by manishas** [comment]
@naveensky this should now be fixed. can you please confirm?

**Comment by naveensky** [comment]
Thanks working good now!
