### ISSUE TITLE
Build stuck on processing, it's been an hour. Can't stop it.

### ISSUE THREAD

**Issue by LuisMuniz** [Shippable/support#1851]
Hi,

My build is stuck at processing. If I look at the logs, I see it was downloading some dependency, but it does not move anymore.
When I try to manually stop it, via the stop button, I can see the spinner for a time, but the build is not stopping.
When I try to launch another instance of the build, I see the following error:

    {"id":2100,"message":"No build found","methodName":"validateCaller|_checkAccessLevel"}

**Comment by caarlos0** [comment]
Same issue here.

I can't properly cancel builds also..

**Comment by LuisMuniz** [comment]
I can't launch any new builds as well. Now I'm stuck. If I am not getting a solution quickly, I will have to switch to another service.

**Comment by jawaid** [comment]
Our apology. The issue has been fixed can you please let us know if you are still messing the issue.

**Comment by lekhab** [comment]
@caarlos0, @LuisMuniz: I see your recent builds seem to be doing okay. Please let me know if there is any build we can help you with.

**Comment by caarlos0** [comment]
@lekhab yes, thanks
