### ISSUE TITLE
Bitbucket issues. Build showing no shippable.yml

### ISSUE THREAD

**Issue by taz77** [Shippable/support#1853]
I am having the exact same issue as #1737. I have checked my .yml at http://www.yamllint.com/ and no problems there. These are pulls from Bitbucket private repositories. 

Additionally any push to the repository does not trigger a build.

Build ID: builds/55eb2e27886c130c009bc4b0
Bitbucket user: bowens06

**Comment by taz77** [comment]
Another related issue #1845

**Comment by taz77** [comment]
Forgot to mention. My master branch does not have the shippapble.yml in it yet. I am working in a feature branch right now to get this working before it goes into master.

**Comment by rageshkrishna** [comment]
@taz77 Can you tell me which branch has the YML file? I'd like to try triggering manual builds on your project to figure out exactly what is going on here. Thanks!

**Comment by taz77** [comment]
@rageshkrishna Sure!.  The branch with the shippable.yml is feature/repeatable_testable_installation

Yeah a little crazy. This thing was running like clockwork till Bitbucket had issues last week.

**Comment by taz77** [comment]
I even had to make manual changes to Bitbucket to get our Jira instance working again.

BTW. I noticed that there was a POST push notification setup by Shippable in my Bitbucket account. Do you guys know that Bitbucket is phasing those out in favor of the Webhooks function?

**Comment by rageshkrishna** [comment]
I think the problem is that the BitBucket API we use to get commit details does not work if the branch name has a `/` in it. We raised this issue with BitBucket over a year ago and there hasn't been any progress on it from their end.

It's possible that webhook builds will trigger on this branch correctly because then we use the commit SHA to get the details, but manual builds will always use the branch name because we want to know what commit is at the tip of the branch. 

Unfortunately, at this point there's very little we can do to work around this because the limitation is within the BitBucket API itself. Can you please try using a branch that doesn't contain a `/` in it? I'm pretty sure that will work.

**Comment by rageshkrishna** [comment]
Here's the BitBucket issue tracker link for this problem: https://bitbucket.org/site/master/issues/9969/get-commit-revision-api-does-not-accept

**Comment by taz77** [comment]
I'll give it a shot with another branch. 

Question. Is there a way for me to find my push/webhook URL to use for Shippable inside of Shippable? Or just copy the one that was created in the account?

**Comment by rageshkrishna** [comment]
We have a `/workflow/triggerBuild` API that you can use. The documentation is at http://docs.shippable.com/api/

**Comment by taz77** [comment]
Odd thing was it was running no problem last week. I think they made changed to Bitbucket last week that broke so many things. Even my Jira cloud instance stopped working with Bitbucket.

**Comment by taz77** [comment]
Cool. Thanks!

**Comment by taz77** [comment]
No dice. I just created a root branch /developtest and I still get the same message that there is no builds

<img width="1620" alt="screen shot 2015-09-08 at 09 37 24" src="https://cloud.githubusercontent.com/assets/1389543/9729110/4d311c7a-560d-11e5-89fb-a573256527aa.png">

**Comment by taz77** [comment]
@jawaid @rageshkrishna Here is my Shippable.yml: https://gist.github.com/taz77/e2f91a1879b6ea857228

Over the weekend, attempting to fix this, I deleted the project out of Shippapble and added it back. Could that have caused other problems?

**Comment by taz77** [comment]
The testing branch with the yml is /developtest

**Comment by rageshkrishna** [comment]
@taz77 Please try removing the `- services: postgre` line from your matrix.exclude section of the YML. We currently don't support exclusions based on the services tag. This limitation is causing all of your builds in the matrix to get excluded. Removing this line should get your other builds to trigger successfully.

**Comment by taz77** [comment]
@rageshkrishna Thanks! Crap in my haste of doing so many other things I forgot I had added this to see if it was supported or not. Looks like a build just kicked off from a push. I feel stupid... Thanks so much for the help!
