### ISSUE TITLE
/builds and /workflow routes of API don't work

### ISSUE THREAD

**Issue by LuisMuniz** [Shippable/support#1857]
HI,

I am trying to find out the way to create a script which would trigger downstream builds, but only if they're not yet in the queue. I have an API token and am able to get the subscriptions, the projects, etc.

To get the running builds, I figure I have to get the list of running builds, through the /builds resource.
However, when I GET the /builds resource, I see the following text error message (code 404):

Cannot GET /builds

Same with /workflow

Am I missing something?

I am using the following page as reference.

http://docs.shippable.com/api/

**Comment by LuisMuniz** [comment]
any progress on this?

**Comment by lekhab** [comment]
@LuisMuniz: can you provide more details on how you are doing this? Both the API routes are working as described. The following works for me..

GET /builds:
```curl -H "Authorization: apiToken [token]" https://api.shippable.com/builds/[build_id]```

POST /workflow/triggerBuild:
```curl -H "Authorization: apiToken [token] application/json" -d '{"projectId":"your_project_id"}' https://api.shippable.com/workflow/triggerBuild```

**Comment by LuisMuniz** [comment]
@lekhab 
`GET /builds/55ef5a53cf2baa0b00e6ea07` works but I would like to get the currently running builds, independently of the project. Is that possible?

**Comment by lekhab** [comment]
@LuisMuniz: We added some API routes recently that should help you:

1. You can use the new searchBuilds API and this will give you all the builds for an account, subscription or project across all states (waiting, queued, processing and completed).

GET /projects/:projectId/searchBuilds
/subscriptions/:subscriptionId/searchBuilds
/accounts/:id/searchBuilds

You can use the limit string to limit the number of builds returned on searchBuilds.
/projects/:projectId/searchBuilds/?limit=100

2. To just get runningBuilds for your account, you could use the `/accounts/:accountid/runningBuilds`  route.

Hope this helps.

**Comment by LuisMuniz** [comment]
Yes, thanks this helps!
