### ISSUE TITLE
Build timeouts if boot step appears

### ISSUE THREAD

**Issue by pbosko** [Shippable/support#1859]
Lately we have experienced a lot of build timeouts. Although most of our builds last for around 30 minutes some timeout after 3-4 hours regardless of tests outcome.

I have also noticed that our builds that finish in 30 mins don't have "boot" step in console, while those that timeout have it right after "pulling image from hub".

Those builds that time out display message like:

    WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.
    Installing virtualenv 1.11.4

We are not using any custom docker image.

Here is the example of successful build: https://app.shippable.com/builds/55ed7b4816ce0a0c00cbfbcf
And here is the one that time outed: https://app.shippable.com/builds/55e989d2781a6d0c002d3934

**Comment by jawaid** [comment]
WE are looking into it.

**Comment by lekhab** [comment]
@pbosko: We deployed a fix yesterday that should resolve the timeout issues. I see all your builds since the fix was deployed have been running to completion. Please let me know if you notice any recurrence.

**Comment by pbosko** [comment]
Great. I didn't see the same error happen again.

Now almost all are builds run to completion. Still there is one that didn't: https://app.shippable.com/builds/55fad01ce5b1f60c00a13bd9 but that is probably an unrelated issue. I'll keep looking if this happends again.
