### ISSUE TITLE
Buid is finished but still at processes

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1860]
Happening to a lot of builds right now:

![image](https://cloud.githubusercontent.com/assets/245435/9744124/546bfb30-5640-11e5-8451-868464d915fa.png)

https://app.shippable.com/builds/55ef11e900ed490b003d224f

**Comment by jawaid** [comment]
Looking into it.

**Comment by caarlos0** [comment]
@jawaid It still happening. 18 hours later...

https://app.shippable.com/builds/55f0210aca57e10c001ca7db

**Comment by jawaid** [comment]
@caarlos0  Our apology. We are actively working to resolve your issue.

**Comment by ragsden** [comment]
@caarlos0 : We rolled out a fix today and you should not see this issue happening. Sorry about the inconvenience.
