### ISSUE TITLE
node sass 

### ISSUE THREAD

**Issue by teo721** [Shippable/support#1861]
> node-sass@3.3.2 install /root/workspace/src/bitbucket.org/controljoy/web/node_modules/gulp-sass/node_modules/node-sass

    > node scripts/install.js

    

    sh: 1: node: not found

    npm WARN This failure might be due to the use of legacy binary "node"

    npm WARN For further explanations, please read

    /usr/share/doc/nodejs/README.Debian

     

    npm ERR! node-sass@3.3.2 install: `node scripts/install.js`

    npm ERR! Exit status 127

    npm ERR! 

    npm ERR! Failed at the node-sass@3.3.2 install script.

    npm ERR! This is most likely a problem with the node-sass package,

    npm ERR! not with npm itself.

    npm ERR! Tell the author that this fails on your system:

    npm ERR!     node scripts/install.js

    npm ERR! You can get their info via:

    npm ERR!     npm owner ls node-sass

    npm ERR! There is likely additional logging output above.

    

    npm ERR! System Linux 3.13.0-57-generic

    npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"

    npm ERR! cwd /root/workspace/src/bitbucket.org/controljoy/web

    npm ERR! node -v v0.10.29

    npm ERR! npm -v 1.4.21

    npm ERR! code ELIFECYCLE

    npm ERR! 

    npm ERR! Additional logging details can be found in:

    npm ERR!     /root/workspace/src/bitbucket.org/controljoy/web/npm-debug.log

    npm ERR! not ok code 0

**Comment by teo721** [comment]
And my shippable.yml is 
# Language setting
language: node_js

# Version number
node_js:
  "- 0.12.0"

before_install:
 - npm install -g gulp
 - npm install -g bower

install:
  - npm install

**Comment by lekhab** [comment]
@teo721: I just tried running the shippable yml as you have pasted above and was able to run it successfully..

Also this might be relevant, since you have a line in your log that indicates Debian. We only support Ubuntu and not Debian currently. Are you able to run your builds on Ubuntu?

**Comment by teo721** [comment]
how should transform my .yml to run on Ubuntu not in Debian ?

**Comment by lekhab** [comment]
@teo721: Your app needs to run on Ubuntu. Are your tests working locally on a Ubuntu platform?

**Comment by teo721** [comment]
@lekhab My os is ubuntu 14.04 and the app is working locally. I'm trying to build a nginx docker and i use http://gulpjs.com/ to build my statics.The problem comes when my build attempt's to run npm install because gulp-sass want's to install node-sass but does not find node ( sh: 1: node: not found).

This is my package.json :
{
  "name": "web",
  "version": "0.0.0",
  "description": "",
  "main": "gulpfile.js",
  "scripts": {
    "install": "node ./node_modules/bower/bin/bower install --allow-root",
    "postinstall": "node ./node_modules/gulp/bin/gulp install && node ./node_modules/gulp/bin/gulp compile",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "bower": "^1.4.1",
    "fs": "0.0.2",
    "glob": "^5.0.12",
    "gulp": "^3.9.0",
    "gulp-concat": "^2.6.0",
    "gulp-order": "^1.1.1",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.0.3",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.6",
    "gulp-watch": "^4.2.4",
    "gulp-webserver": "^0.9.1",
    "main-bower-files": "^2.8.2",
    "path": "^0.11.14",
    "require-dir": "^0.3.0"
  }
}

**Comment by teo721** [comment]
@lekhab i modified something and now it's working but i have another problem.If i use https://hub.docker.com/_/nginx/ i need to COPY www/ /usr/share/nginx/html but I don't know where i can find the www.

**Comment by manishas** [comment]
The entire docker workflow can now be driven through shippable.yml so this older issue is out of date.

Please let us know if you are still experiencing issues and we will reopen this.
