### ISSUE TITLE
Unable to remove Formation

### ISSUE THREAD

**Issue by bellhop-admin** [Shippable/support#1862]
All of my services are stopped, but I cannot remove the service configuration due to a "dependency" error of which I cannot determine, which is preventing me from removing the Formation altogether.

My Formation ID is: 55e0c324b20b210c00f5f0c8

**Comment by trriplejay** [comment]
Hi,
You should be able to delete your service now.  Let us know if you have other questions!

**Comment by stuartfenton** [comment]
I have the same issues as well.

**Comment by trriplejay** [comment]
Hi @stuartfenton, is there a specific formation you're having trouble with?  Are you attempting to delete a service or deactivate the formation?

**Comment by grandmore** [comment]
I have added a formation by clicking the formation tab at the top, however I cannot delete it once it's created. Since I was testing different accounts I find that I now have 6 that cannot be deleted.

**Comment by macgyver2028** [comment]
I have a similar situation to @grandmore.  I added a formation for testing, but cannot delete it once it was created.  My formation ID is:  5628616f954d220c005e3252

**Comment by npahucki** [comment]
How the heck to DELETE Formations!? There is no delete button even though the formation has no services in it.

**Comment by trriplejay** [comment]
The delete button should be on the billing tab.  If you can't see it let me know the ID and I'll take a look.

**Comment by manishas** [comment]
@npahucki Please let us know if you need help with deleting your Formation.

On another note, Formations as a standalone offering will be deprecated tomorrow and the functionality will be rolled into one subscription which will offer CI and deployment pipelines. Please let me know if you would like a demo of what we're launching on 2/29 (Monday).

**Comment by npahucki** [comment]
First, thanks for the info, I had expected the option to delete in settings like the CI stuff. @manishas I'd love to see what you're unveiling. Is there a webcast?

**Comment by manishas** [comment]
@npahucki we can set up a google hangout anytime after 4/2. Let me know a couple of times that work for you. We're in PST time zone.

**Comment by manishas** [comment]
Formations functionality has now been rolled into pipelines, so deleting a formation is no longer a valid scenario.
