### ISSUE TITLE
github signup fails

### ISSUE THREAD

**Issue by eviweb** [Shippable/support#1863]
Hi,
I've just tried to signup using my github account and it fails with the error message:
_getUserEmails returned error or empty body:null_
Any idea how to solve this ?

thanks

Eric

**Comment by rageshkrishna** [comment]
@eviweb Thanks for reporting this. I'm looking in to it.

**Comment by rageshkrishna** [comment]
@eviweb This should be working now. Can you please try again? Thanks!

**Comment by eviweb** [comment]
@rageshkrishna,
yes it works like a charm,
thanks for your reactivity
Eric
