### ISSUE TITLE
Node v4.0.0

### ISSUE THREAD

**Issue by RobertHerhold** [Shippable/support#1865]
Feature request for [Node.js v4.0.0](https://nodejs.org/en/blog/release/v4.0.0/)

**Comment by roll** [comment]
:+1:

**Comment by philcraven** [comment]
:+1:

**Comment by winglian** [comment]
try something like (works for me):

```
node_js:
  - "4.1.1"
language: node_js

build_image: shippableimages/ubuntu1404_nodejs

before_install:
  - sudo apt-get install -y --force-yes build-essential
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.27.1/install.sh | bash
  - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
  - node --version

```

**Comment by vinicius0026** [comment]
:+1:

**Comment by philcraven** [comment]
the simple answer is for setup_ve to call
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.27.1/install.sh | bash
before it tried to install node, which would allow you to not need the specific build image

**Comment by manishas** [comment]
This is now available in our official images in the [drydock repo on Docker Hub](https://hub.docker.com/u/drydock/)

Naming convention:

Our standard build images are named as follows:

- The first 3 letters of image name indicate the platform. u14 denotes ubuntu 14.04, u12 denotes ubuntu 12.04
- The next 3 letters indicate the language. nod for node.js, sca for scala, pyt for python, gol for golang, rub for ruby, clo for clojure, jav for java, and php for php.
- The last 3 letters, if present, indicate any additional services that are pre-installed. pls indicates that Cassandra, Elasticsearch, Memcached, MongoDB, MySQL, Neo4j, RabbitMQ, Redis, Selenium, SQLLite are already installed on the build minion. all indicates that in addition to all services available in pls images, CouchDB, Kestrel, RethinkDB, Riak are also installed.

**Comment by manishas** [comment]
closing.
