### ISSUE TITLE
node builds are failing because nvm error

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1866]
Hi, 

SInce this morning my nodejs builds are failing because of an nvm error: 
before_install
  mkdir -p shippable/testresults
  mkdir -p shippable/codecoverage
  npm install -g vows
/usr/bin/vows -> /usr/lib/node_modules/vows/bin/vows
vows@0.8.1 /usr/lib/node_modules/vows
├── diff@1.0.8
├── eyes@0.1.8
└── glob@4.0.6 (inherits@2.0.1, graceful-fs@3.0.8, once@1.3.2, minimatch@1.0.0)
  source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
/root/.nvm/nvm.sh: line 711: manpath: command not found
Version '0.12' not found - try `nvm ls-remote` to browse available versions.

this build was showing green until yesterday. 

Please advice

**Comment by rvdwijngaard** [comment]
hi is there any update on this since it is really blocking my ci pipeline for a bunch of services

**Comment by rageshkrishna** [comment]
@rvdwijngaard We're seeing some issues across the board with node builds today, include errors with nvm as well as strange issues with npm installs. Can you please share your project or build id so I can dig deeper into this?

**Comment by rvdwijngaard** [comment]
@rageshkrishna My project is https://app.shippable.com/projects/552cbd655ab6cc1352c32b68. You will see all builds of today are failing.

**Comment by pkaminski** [comment]
Failing here too, same error: https://app.shippable.com/builds/55f14371d68e150c004e9e15

This is completely blocking my pipeline as well.

**Comment by rageshkrishna** [comment]
I'm not quite sure what caused this to start happening today, but please upgrade nvm to the latest release (0.26.1) with the following command. This should be the first step in your before_install, before you call `source /root/.nvm/nvm.sh`.

````
before_install:
 - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash
````

**Comment by jawaid** [comment]
Please let us know if you are still seeing errors.

**Comment by pkaminski** [comment]
This fix worked for me -- thanks.  I'm not sure where I got the `source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION` line from, but it was likely from Shippable docs somewhere, in which case it would be good to update the instructions with the extra download command.

**Comment by rvdwijngaard** [comment]
yes that solves the problem but its not a very nice solution; it slows down the build quite drastically; do you have any plans to update nvm on your nodejs base images?
