### ISSUE TITLE
Can't login with Bitbucket - getUserEmails returned error or empty body:null

### ISSUE THREAD

**Issue by JADurham909** [Shippable/support#1867]
getUserEmails returned error or empty body:null

**Comment by joelash** [comment]
No idea what your issue is, however just as an FYI I logged in (first time login) with bitbucket just an hour or so after you created this issue and it was fine.

**Comment by JADurham909** [comment]
The issue was there was no email on the bitbucket account.  I am not sure how that is possible, but after adding a confirmed email it was ok.

**Comment by joelash** [comment]
:+1: Good to know

**Comment by jawaid** [comment]
Thanks
