### ISSUE TITLE
Can't login with github

### ISSUE THREAD

**Issue by grue** [Shippable/support#1868]
When attempting to log in with github I receive this error:

`Failed to sync payment provider for account id: <accountid>`

**Comment by georgwaechter** [comment]
the same for me with bitbucket

**Comment by aaronjudd** [comment]
same thing here, preventing me from considering Shippable once again.

**Comment by crania** [comment]
I'm having the same issue

**Comment by lekhab** [comment]
A fix for this issue is in progress and will be deployed to prod over the next couple of days.

**Comment by menome** [comment]
getting same error - any insight as to when a fix might be specifically available, or if there is a work around? I will need this working before tomorrow...

**Comment by kanthchandra** [comment]
A fix has been deployed to production today. Please let us know if this works for you guys.

**Comment by crania** [comment]
Works for me - thank you.

**Comment by menome** [comment]
works for me now as well! Many thanks!

**Comment by grue** [comment]
awesome, thanks!
