### ISSUE TITLE
Clojure tests tab shows "No tests for this build"

### ISSUE THREAD

**Issue by joelash** [Shippable/support#1869]
I have two build that have tests, which pass, when I run with `lein test` locally. I have my `shippable.yml` setup almost identical to the Clojure samples, however I still see "No tests for this build" whenever I run my build. Is there a bug or am I setup incorrectly?

**Comment by joelash** [comment]
Managed to get this working by install [`lein test2junit`](https://github.com/ruedigergad/test2junit) plugin and setting `{:test2junit-output-dir "shippable/testrsults"}` in my `project.clj` file. If this is *the way* to make tests show up in the shippable UI then it should at least say so in the documentation and samples.

**Comment by jawaid** [comment]
@joelash Just to update you. We are working on this and would update you soon.

**Comment by jawaid** [comment]
@joelash all our clojure samples have now been updated with the plugin test2junit.  We are now able to see the Test Reports.

The docs at http://docs.shippable.com/languages/#clojure have been updated (and are live) to inform the usage of test2junit.

**Comment by joelash** [comment]
:+1:
