### ISSUE TITLE
Post CI Docker image is not being pushed

### ISSUE THREAD

**Issue by matthewpflueger** [Shippable/support#1870]
I believe this is related to issue: https://github.com/Shippable/support/issues/1648

Unfortunately, that issue was opened on July 6th and it looks like no movement has been made.  This issue is a huge blocker for me as I would like to setup a continuous deployment in another environment but need the built image to be pushed.

Here is one of many builds that result in no pushed image:  https://app.shippable.com/builds/55f2406a5ae1b20b00ac1cdb

BTW, I really love the service and think you guys have something great here.  However, it does feels very buggy.  I hope that improves soon...

**Comment by matthewpflueger** [comment]
Any movement on this?  Anything I can do to help?

**Comment by lekhab** [comment]
@matthewpflueger: This is very much on our radar. We are working on upgrading the underlying build workflow that should help with this issue. will follow up internally and get back to you with an update later this week.

**Comment by matthewpflueger** [comment]
Awesome.  Thanks for the update.  Please keep me posted!

**Comment by matthewpflueger** [comment]
Any updates for this issue?

**Comment by jawaid** [comment]
@matthewpflueger  We are actively working on this issue. Will keep you updated.

**Comment by avinci** [comment]
@matthewpflueger this should be fixed. Can you let me know if this is working for you?

**Comment by matthewpflueger** [comment]
Sorry Avi but we canceled our account due to needing to move past this.
Perhaps we will explore Shippable in the future. Thanks.
