### ISSUE TITLE
CI list doesn't scroll

### ISSUE THREAD

**Issue by coreybutler** [Shippable/support#1872]
I may be in the extreme minority, but I am a member of bunch of teams/orgs between my Github and BitBucket accounts. When I try to select a CI integration source, the list will not scroll, so I cannot add my repos:

You'll also notice at least one duplicate (some of the dupes are due to similarly named repos on both Github and BitBucket)

![Unscrollable](https://s3.amazonaws.com/uploads.hipchat.com/94386/688041/Md1KeuW2iQgZE9L/upload.png)

**Comment by coreybutler** [comment]
Forgot to mention this is Chrome 45.0.2454.85 (64-bit) on OSX.

**Comment by coreybutler** [comment]
When I click on "more" to show the history of prior runs, I am able to see more of the list.... doing this enough times eventually shows the whole list. Looks like a `z-index` problem with absolute positioning.

![image](https://cloud.githubusercontent.com/assets/770982/9833231/40bad742-5955-11e5-983f-05c8d3f7fa9c.png)

**Comment by coreybutler** [comment]
And while you're updating the menu, it would be really nice to show a small Github/BitBucket icon to indicate whether the repo/group is sourced from one or the other. I'm guessing other users use the same organization name the way we do... we release our open source stuff on Github and use BitBucket for private repos.... yet both systems have orgs with the same name.

**Comment by avinci** [comment]
@DavidGDragon can we look into this while we clean up our UI

**Comment by DavidGDragon** [comment]
This issue should be resolved with new UI
