### ISSUE TITLE
Builds running very slow - stuck for 30 minutes

### ISSUE THREAD

**Issue by hshira** [Shippable/support#1874]
My builds are running way slower than usual. 
I cancelled this build after it failed to finish after 27 minutes https://app.shippable.com/builds/55f6226cd472a90b009a4445 This usually takes atmost 10 minutes

Another build https://app.shippable.com/builds/55f62886d472a90b009c9a76 is stuck for 17 minutes. Usually this doesn't take more than 5 minutes.

**Comment by hshira** [comment]
Now this has been going on for an hour https://app.shippable.com/projects/54336bc97a7fb11eaa6496a6

**Comment by hshira** [comment]
Now this has been going on for 2 hours. Support team ... you need to do something. The whole idea of CICD goes down the drain with this kind of performance.

**Comment by rageshkrishna** [comment]
@hshira I'm very sorry about the time it took to resolve this. One of our API instances was having an issue with queue connectivity, which caused a delay in updating the build status for some of the builds. We've resolved this issue and things are back to normal now. Can you please let me know if you still see this happening?

**Comment by hshira** [comment]
Seems to be working fine now. Thank you for resolving this.
