### ISSUE TITLE
How to add custom configs to MySQL

### ISSUE THREAD

**Issue by 164c** [Shippable/support#1875]
I'm trying to run rails spec with mysql. And I need to add some extra configurations to my.cnf to run my spec so I wrote it in shippable.yml as below.
~~~
before_script:
  - cp config/ci/.my.cnf ~/.my.cnf
  - sudo service mysql restart
~~~

config/ci/.my.cnf
~~~
[mysqld]
collation-server = utf8_general_ci
init-connect='SET NAMES utf8'
character-set-server = utf8

innodb_ft_min_token_size = 2
~~~

The before_script looks done with no trouble but it doesn't take effect.
I searched the docs and web but not able to find information about this.

Any clues?

**Comment by 164c** [comment]
@lekhab 
Is there any way to do this?
We have no time to decide if we can use Shippable for our new project.

**Comment by ric03uec** [comment]
@164c we're not using upstart for managing the services, so `service start/stop/restart mysql` won't work. So you'll have to stop the running instance of mysql and then start another one with your custom config.
- can you try the following and let me know if it works.
```
before_install:
  - pgrep "mysqld" | xargs -I {} sudo kill -9 {}
  - sudo cp config/ci/.my.cnf /etc/mysql/my.cnf  
  - sudo su -c "/usr/bin/mysqld_safe > /dev/null 2>&1 &"
```

**Comment by 164c** [comment]
@ric03uec  Thanks! The script didn't work because parameters of mysql is insufficient.
I think we are almost there with the .my.cnf below.

~~~
[mysqld]
innodb_file_format = Barracuda
innodb_large_prefix

basedir=/opt/mysql/server-5.6
socket=/var/run/mysqld/mysqld.sock
pid-file=/var/run/mysqld/mysqld.pid
plugin-dir=/opt/mysql/server-5.6/lib/plugin
datadir=/var/lib/mysql
log-error=/var/log/mysql/error.log

[client]
socket=/var/run/mysqld/mysqld.sock
~~~

But I could not try the config because before_script stopped to proceed after some trial.
Since then I've not succeeded to run the script. It always stops at on the way of before_script.

I have no idea what is happend.

Could you take a look at?

**Comment by ric03uec** [comment]
@164c 
- can you post the output of `before_script` section. i tried running the one of shippable sample builds using the `my.cnf` you pasted in the previous comment and mysql does come up correctly with it. 
- This is the project I used for testing : https://github.com/ric03uecS/sample_python_mysql/blob/killmysql/shippable.yml
- also, can you add `ps -eaf `statement at the end of `before_script` section so that we know all the processes running during the build
- it would also help if you provided us with your project id
Thanks

**Comment by 164c** [comment]
@ric03uec 

I put a screen shot below which shows what I described as "before_script stopped to proceed" in my previous comment. You'll see it timed out on the way of processing the before_script.

<img width="1092" alt="screen shot 2015-09-18 at 10 40 24 am" src="https://cloud.githubusercontent.com/assets/1281528/9950483/f6717736-5df5-11e5-9878-ccdd92ee13ae.png">


> also, can you add ps -eaf statement at the end of before_script 

I can add ```ps -eaf ``` but ,as you see, it won't show in the console because the script does not reach there.

I need your help.

Project ID     : 55f67e3e1895ca44741511a4
Branch name: shippable_db

Thanks!

**Comment by ric03uec** [comment]
@164c i see that that you're running  mysql in the foreground which is causing the build flow to hang.
- you need to run the following command to spin up mysql so that mysql runs in the background
```
sudo su -c "/usr/bin/mysqld_safe > /dev/null 2>&1 &"
```
- can you give this a shot and try again

**Comment by 164c** [comment]
@ric03uec 
Thanks! 

I made it after I added ```sleep 2``` after ```sudo su -c "/usr/bin/mysqld_safe > /dev/null 2>&1 &"``` to wait the mysql starting.
(sleep 1 does not woke sometime..)

I wonder if there is smarter way to wait mysql starting instead of sleep.
Please tell me if you know the way.

**Comment by ric03uec** [comment]
@164c glad it worked :)
- i'm afraid adding a `sleep` is the easiest way to do this. I would recommend at least 5 seconds
- when you start services by default, shippable build script makes sure they run by using a retry loop. you can add that logic to the build yml(the code is in the `start_services_internal` function of build script)
  - or a different(better) way to do it will be to write a helper script for your project that contains mysql custom boot logic and then invoke it from the build yml.

hope this helps

**Comment by 164c** [comment]
@ric03uec  thanks for your quick reply.

I understand it.
I have no more questions.

Please close this issue if you like.

Thanks!
