### ISSUE TITLE
Nodejs build time is around 20 minutes

### ISSUE THREAD

**Issue by siutsin** [Shippable/support#1876]
Hi,

I am evaluating Shippable and noticed that the [build time](https://app.shippable.com/builds/55f693e087a25c0b004bed48) for node is ~ 20 mins.
The setup for the [sample project](https://bitbucket.org/simonli/test-ci/src/6c0d57f3c347f2d6ac288476df2aa7a46abb0dd0?at=develop) is one test case with gulp and jasmine.

From the build log, setup_ve took 1126.37 seconds:
```
 setup_ve 1126.37 seconds
  . /home/shippable/.nvm/nvm.sh && nvm install 0.12
  nvm use 0.12 && npm config set ca ''
  nvm ls
  node -v
```

shippable.yml
```
language: node_js
node_js:
  - 0.12
```

Is this expected or bug?

Regards,
Simon

**Comment by jawaid** [comment]
We are looking into it and will get back to you.

**Comment by czardoz** [comment]
Possible duplicate: #1881

**Comment by manishas** [comment]
Our new official images have node 0.12 preinstalled on them and you can find them in our [drydock repo on docker hub](https://hub.docker.com/u/drydock/). The pls and all versions of images have services preinstalled on them as well.

Please use these images to avoid building node each time.
