### ISSUE TITLE
Cannot find new bitbucket project, even after force sync

### ISSUE THREAD

**Issue by frenkel** [Shippable/support#1878]
Maybe because we now have 546 repositories in our bitbucket team.

**Comment by jawaid** [comment]
@frenkel We are looking it and get back to you.

**Comment by frenkel** [comment]
I only see about 30 projects and it seems the search functionality looks only in the projects that are visible on the page, instead of all projects.

**Comment by jawaid** [comment]
looking up 'frenkel' all i see is one bitbucket account, which has 0 projects and 0 subscriptions. account was most likely just created as an offline account... what subscription are you refering to (subscription name, or ID)

**Comment by frenkel** [comment]
My `frenkel` account parcitipates in a team called `ivaldi`. That team has only private repo's.

**Comment by frenkel** [comment]
Apparently it works again today. Thanks.

**Comment by jawaid** [comment]
@frenkel  I am glad it is working for you. 

Regards
