### ISSUE TITLE
Artifacts are not being uploaded on timeout

### ISSUE THREAD

**Issue by RealNobody** [Shippable/support#1879]
I had the following issue:  https://github.com/Shippable/support/issues/1813

It had looked like it was fixed until I got this run:

https://app.shippable.com/builds/55f88373e20ad80d0065fcb7

I don't know why it timed out.  A typical successful run only takes a little less than 1 hour.  I will be looking into that.

What bothers me is that it didn't run the post-script and it didn't upload the artifacts that I know existed and that I need.

**Comment by RealNobody** [comment]
This build had the same issues:

https://app.shippable.com/builds/55f8858ba62c630d00bd012b

NOTE:  I can verify our code running for about 1:30 minutes till the RSpecs start.

It doesn't look like the RSpecs run at all almost from the console output so this one almost certainly shouldn't have timed out based on what I'm seeing in the console.

But the artifacts didn't upload and it didn't run the after script.

**Comment by jawaid** [comment]
We are looking into it.

**Comment by RealNobody** [comment]
Again!

No timeout, it just doesn't upload artifacts.

NOTE:  We thought the artifact thing had been fixed, so we switched back to just running the commands rather than using a script like we had been doing to work around this issue.

https://app.shippable.com/builds/5601cd3f767f8812006033f0

**Comment by RealNobody** [comment]
Again: https://app.shippable.com/builds/560ec3bc013d9a0f002e4d50

Still not fixed - Not running post script - not uploading artifacts

**Comment by jawaid** [comment]
This has been fixed.

**Comment by RealNobody** [comment]
> Are you still having this issue?

Absolutely.

**Comment by DavidGDragon** [comment]
We've released a new build system where users set up their own artifacts, you can find more information here http://docs.shippable.com/ci_configure/#build-artifacts
Try the new system and see if you continue to have issues.

**Comment by manishas** [comment]
Closing this since this has been addressed with the new build system.
