### ISSUE TITLE
Click on build badge does not bring up results.

### ISSUE THREAD

**Issue by henrjk** [Shippable/support#1880]
I looked at issue #1401 

Clicking on the build badge on page https://github.com/henrjk/connect/tree/shippable opens the images for me not the build results. Am I doing something wrong? Is this no longer working?

**Comment by jekram** [comment]
@henrjk  Can you please include a screenshot.

**Comment by henrjk** [comment]
Here is relevant part or the build page https://github.com/henrjk/connect/tree/shippable.

![screen shot 2015-09-17 at 10 34 01](https://cloud.githubusercontent.com/assets/7439282/9928653/ebee8a5c-5d27-11e5-8262-7306a231aac2.png)

When I click on either of the *build* badges I see simply the graphic displayed instead of getting to the build results.

![screen shot 2015-09-17 at 10 34 53](https://cloud.githubusercontent.com/assets/7439282/9928660/f53c1ba6-5d27-11e5-9081-16f1e30be35f.png)

**Comment by jawaid** [comment]
@henrjk  We are looking into and get back to you

**Comment by jawaid** [comment]
Comment from our Eng Staff @a-murphy 

"This user has not specified what the image should link to the in markdown, so GitHub thinks that it should be a link to the image. The route that used to be used in the build badges to get the latest build appears to no longer exist (and is not in the documentation). But, the project page might be a reasonable substitution. This will go to the user's project page when clicked (it's a public project):

[![Build Status](https://api.shippable.com/projects/55f995921895ca447415d057/badge/shippable)](https://app.shippable.com/projects/55f995921895ca447415d057)

Also please see:  http://docs.shippable.com/build_badge/

**Comment by henrjk** [comment]
Summarizing: with this markdown  the badge shows the status of the most recent build and I can link to the (public) project page:

```
[![build](https://img.shields.io/shippable/55f995921895ca447415d057/shippable.svg)](https://app.shippable.com/projects/55f995921895ca447415d057)
```

I understand that there is no longer a way to link to the build which status the badge reflects. I think restoring the ability to link to the associated build would be very desirable. 

More problematic is that badge shows 'pending' while a build runs. It seems to me it would be much better if only completed builds would be shown with the badge. I just checked that the Travis build badge does not show pending builds. 

Thank you for the quick turnaround.

**Comment by manishas** [comment]
We have redone the build badge implementation completely for the new build system, so closing this issue.

Badges are described at http://docs.shippable.com/ci_projects/#build-status-badges

Your subscription needs to be on the new build system, i.e. plan name in the Billing tab should be 'Continuous Delivery'. If it is not, you can update the plan and badges should start working from subsequent build.
