### ISSUE TITLE
Shippable shows us "failed" with no errors.

### ISSUE THREAD

**Issue by 164c** [Shippable/support#1883]
Shippable sometimes shows us that a test has failed but it looks no errors have been happened.

<img width="1158" alt="screen shot 2015-09-18 at 7 04 19 pm" src="https://cloud.githubusercontent.com/assets/1281528/9957050/1eada674-5e38-11e5-9fa5-9b5138779241.png">

<img width="1103" alt="screen shot 2015-09-18 at 6 58 23 pm" src="https://cloud.githubusercontent.com/assets/1281528/9956998/cd4c178e-5e37-11e5-9a86-98b9ee1f2e15.png">

Just re-running the test fixes it.

Project ID: 55f67e3e1895ca44741511a4

**Comment by lekhab** [comment]
@164c: opened an issue to figure out why those specific builds seemed to have a problem. I see all your recent builds seem to be doing fine. Have you seen this recur since the time you reported this?

**Comment by 164c** [comment]
@lekhab No. I've not seen it since I reported this issue. And I don't have any farther information about this issue. 

 If you have any ideas about this issue and you think it would not occur again, feel free to close this issue. I'll re-open this issue if it occurred again.

**Comment by jawaid** [comment]
@164c WE will close it for now and please reopen it if it happens again.
