### ISSUE TITLE
Docker build pushing into private repository with different port

### ISSUE THREAD

**Issue by tudvari** [Shippable/support#1885]
Hi guys,

I would like to use your service with the followed setup. I have my own domain name. I have a VPS, which has a Nginx web server on the port 80 and 443. On this machine, I have a docker registry, which has SSL support also, registry runs on port 5000. How can I set up my integration on shippable to use my registry? 

I try on this way:

![image](https://cloud.githubusercontent.com/assets/181417/9960085/c6c9856e-5e18-11e5-9cad-8b19ca2de18b.png)

My Project settings:

![image](https://cloud.githubusercontent.com/assets/181417/9960138/0e6b5528-5e19-11e5-9364-1ea53a68c723.png)

Docker build command, what I can see on the console:

sudo docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag="tudvari/authservice:b0304397a6c94bbc4dbcceeac9dbea1a85fa2066" .;

Docker push command is : 

sudo docker push tudvari/authservice:b0304397a6c94bbc4dbcceeac9dbea1a85fa2066 2>/tmp/push-error.txt

![image](https://cloud.githubusercontent.com/assets/181417/9960308/223269ec-5e1a-11e5-86f8-cda5664b9c7e.png)

Build ID for this run is : 55fc104290f21e0b0008f52d

Thanks in advance,

Regards,
Tibor

**Comment by lekhab** [comment]
@tudvari:

* Under Project settings, can you specify the full URL against the push image to section? ```tudvari.com:5000/tudvari/authservice```

* The account integration looks correct. Please let me know if you face any issue after you try the approach above.

This [blog](http://blog.shippable.com/integrate-with-quay.io-and-private-docker-registry) also walks you through the setup for private docker registry.

**Comment by tudvari** [comment]
Hi, 

I tried your suggestion, unfortunatelly it does not work. Maybe we found an issue in the build image phase in the workflow, the docker daemon tags the new image, and this image tag name doesn't match with the image name, what we would like to push into our registry.

Docker build command is:

  sudo docker build --rm=true --pull=true --force-rm=true --no-cache=true --tag="tudvari.com:b0304397a6c94bbc4dbcceeac9dbea1a85fa2066" .;

Docker image push command is: 

sudo docker push tudvari.com:5000/tudvari/authservice:b0304397a6c94bbc4dbcceeac9dbea1a85fa2066 2>/tmp/push-error.txt

You can see the difference between the tag names. I think, we should use the last position number of the ":" character, instead of the first occurance. 

Here you can see, my project settings:

![image](https://cloud.githubusercontent.com/assets/181417/9988806/f8c7e06e-6053-11e5-8ac8-0823878a3744.png)


Build ID is : 55ffcafb58124d0d00f788ef

Thanks in advance.

BR,
Tibor

**Comment by lekhab** [comment]
will follow up on this.

**Comment by lekhab** [comment]
an internal issue has been opened to take a look at this issue.

**Comment by tudvari** [comment]
Hi,

could you please give me a feedback, what is the current status of this issue? It would be nice, if we can use shippable as a main CI tool. :-)

Thanks in advance.

BR,
Tibor

**Comment by imrefazekas** [comment]
Guys, would you share an update on this ticket? I have the same issue now and would be good to know to initiate the development of an own tool or can wait for a patch.
Thanks!

**Comment by manishas** [comment]
@tudvari @imrefazekas we have actually tested a fix for this internally already and it should be available in production in less than 24 hours.

**Comment by tudvari** [comment]
Great news! Thank you :)

**Comment by tudvari** [comment]
@manishas Could you give me please update about this issue, it seems to not working yet :-(

**Comment by imrefazekas** [comment]
@manishas : I can confirm the statement from @tudvari . It does not work yet. How can I assist your effort on this subject? I am at your disposal. Our project must go on, so we have to initiate a plan B and implement a custom CI, but still can spend some time on this...

**Comment by manishas** [comment]
The fix is ready to be deployed and I'll make sure it is deployed today. I'll update soon...

**Comment by manishas** [comment]
@imrefazekas @tudvari can you try now? We've deployed the fix to prod.

**Comment by tudvari** [comment]
I got the followed error msg:

{"id":1005,"message":"Internal API error : getBuildById","methodName":"caller:556ee9c87f74c80d007db4b3|buildConsoles|chkPermForBuildId:561001fa28b6700c007edf92|_getBuildById"}

**Comment by manishas** [comment]
Can you paste a link to your build?

**Comment by tudvari** [comment]
Sorry I can't because I have been recreate the project, it seems to working at the moment. :-)

**Comment by manishas** [comment]
Oh so it's working now?

**Comment by tudvari** [comment]
Yes, I try the fix for this issue. :)

**Comment by tudvari** [comment]
Thank you for your help, it's working :-)
