### ISSUE TITLE
Build failing mysteriously -- URGENT

### ISSUE THREAD

**Issue by leroyjware** [Shippable/support#1886]
Our builds on one of our repos started failing yesterday:

https://app.shippable.com/builds/55fc519ae600ce0c00774999

Can you please help us. We are exhibiting at TechCrunch on Tuesday of next week and it is critical that our deployments are working.

**Comment by trriplejay** [comment]
@leroyjware It looks like all of the failed builds were run on the same PR.  Was something changed in that PR that could have caused this? The output of before_install looks quite different. Maybe a package.json change?

**Comment by leroyjware** [comment]
It was a simple PR that shouldn't have run any different. No changes to package.json.

**Comment by manishas** [comment]
Can you please send your Dockerfile and shippable.yml to devashish@shippable.com? We're trying to get to the bottom of this.

**Comment by lekhab** [comment]
@leroyjware: Marking this resolved based on the email thread/PR builds are now succeeding. Please let us know if you need any further help.
