### ISSUE TITLE
How to run script after successful docker push?

### ISSUE THREAD

**Issue by paislee** [Shippable/support#1887]
Once my Post-CI image is successfully pushed to Google Container Registry, I want to run a script that authenticates to gcloud and performs a rolling update on GKE. For non-Docker builds, `after_success` is used for deployment purposes, but this appears to run _before_ the image is pushed, at least for Post-CI workflow.

Is it possible to do this for a Docker build?

**Comment by manishas** [comment]
We currently only allow a small number of targeted actions after the container is pushed to google container registry, and adding support for your specific scenario is on our roadmap.  I will let you know when it's available. Thanks!

**Comment by manishas** [comment]
@paislee actually, one way to achieve your scenario with existing functionality is this -

- Create a Shippable Formation and deploy your container there
- We provide a way to trigger a workflow every time the container in a Formation is updated. This can be your GKE deploy script. 

We can show you a demo of how this is possible... Can you set up a time slot at https://shippable.youcanbook.me ?
