### ISSUE TITLE
ElasticBeanstalk private dockerhub repo auth has  the wrong file format

### ISSUE THREAD

**Issue by JADurham909** [Shippable/support#1888]
Amazon expects:

{
		"https://index.docker.io/v1/": {
			"auth": "X",
			"email": "X"
		}
}

But is getting:

{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "X",
			"email": "X"
		}
	}
}

This causes the elastic beanstalk deploy to fail.

**Comment by JADurham909** [comment]
Closed by accident.

**Comment by JADurham909** [comment]
It appears that Shippable is using a newer docker version and Amazon is still expecting an older auth file format.

http://stackoverflow.com/questions/31395904/deploy-image-to-aws-elastic-beanstalk-from-private-docker-repo

**Comment by JADurham909** [comment]
This one is causing me some pain.  I have 11 or so builds I have to manually update the auth file in S3 on each push to master.  Is there another workaround for this?  Maybe a script I can trigger to update the file format as part of a post build?

**Comment by ragsden** [comment]
@JADurham909 : I have deployed a fix which pushes the older format to S3. Can you please let me know if the issue is now resolved? Thanks!

**Comment by JADurham909** [comment]
Just tested and it works as expected.  Thank you for doing this so quickly.  That is going to save me a ton of time ;P

**Comment by jawaid** [comment]
Thanks @JADurham909  & @ragsden
