### ISSUE TITLE
Build times are wrong

### ISSUE THREAD

**Issue by Arcnor** [Shippable/support#1889]
I'm using a webhook to inform one of my services when a build starts & ends. However, although the time for "BUILD STARTED" is correct, the time for "BUILD SUCCEEDED" is between 10 to 20 seconds later (although the build takes ~5-10 minutes, and I get the message at that time, with the wrong time on it)

**Comment by jawaid** [comment]
@Arcnor  We will look at it and get back to you.

**Comment by Arcnor** [comment]
Thanks @jawaid. In case it's useful, our last build went backwards in time (i.e. its finish time was before its starting time :D)

**Comment by manishas** [comment]
This is completely redone with our build system upgrade. closing.
