### ISSUE TITLE
Build with Python doesn't install latest packages from PyPI (reusing image?)

### ISSUE THREAD

**Issue by bittner** [Shippable/support#1890]
I have an Open Source project that builds [successfully on Travis-CI](https://travis-ci.org/Organice/django-organice/builds/81201759), but [fails on Shippable](https://app.shippable.com/builds/55fdd43ad7f42d0b003db088).

The reason for the failure is that one or more outdated package are installed that should be pulled afresh on a clean install. The build log suggests that the (intentionally lax) dependency is already satisfied. So, is the image reused from an earlier build? If yes, was this always the case? If no, when was the default behavior changed?

**Comment by jawaid** [comment]
@bittner  We will look into this and get back to you.

**Comment by manishas** [comment]
@bittner can you share a link to the project so we can test it out at our end? Thanks!

**Comment by bittner** [comment]
https://bitbucket.org/organice/django-organice (triggers Travis-CI)
https://github.org/Organice/django-organice (triggers Shippable)

Source code is identical in boths repositories.

**Comment by manishas** [comment]
@bittner you have the following in your yml -

```
cache:
  directories:
    - $HOME/.pip-cache/
```
This is causing the cached image to be used for your builds. If you want to run a clean build every time, please remove those statements from your yml. 

Let me know if this solves your issue.

**Comment by bittner** [comment]
Okay, thanks for the hint. This instruction is obviously specific to Shippable (and ignored by Travis-CI).

**Comment by bittner** [comment]
Still failing, but differently! Looks like the actual build is now passing. Now Travis-CI passes in the `after_success` section due to `coveralls` (probably) exiting non-zero.

Now, this has been reduced to an issue of the coveralls client. Travis-CI is obviously ignoring the exit code on purpose: Either they circumvent the coveralls issue, or they don't react on non-zero exits after successful completion of the `script` section.

Fine for me for now. (Though still failing.)

**Comment by bittner** [comment]
Oh, as for coveralls, in fact my fault: My coveralls.io account still points at the old repository location. Sorry! :weary:

**Comment by jawaid** [comment]
@bittner Thanks closing the issue.
