### ISSUE TITLE
Using /root/ve as a custom virtualenv causes surprising errors

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#1891]
When using a custom build image, the [Languages docs](http://docs.shippable.com/languages/#build-image_5) recommend using a custom virtual environment with `$SHIPPABLE_PYTHON` as an interpreter. It's already a source of confusion, because it's not clear why Shippable cannot do this for us.

Anyway, in your example you're using `/root/bldve`. It's not clear what bld means, so we naturally used `/root/ve`. However, this virtual environment already exists with Python 2 (Shippable created it?), and virtualenv does not rewrite python or pip when run in an existing virtual environment. So this virtual environment did contain python3.4 and pip3.4, but it also contained python2.7 and pip2.7. Worse, pip and python pointed to the Python 2 versions. This meant that `pip install -r requirement.txt` pointed to Python 2 instead of Python 3, which caused confusing errors.

Is there a way to avoid this issue? The best way seems to use something less obvious than /root/ve to avoid the name clash.

Thanks for Shippable.

**Comment by jawaid** [comment]
@pquentin  We would look into it and we will get back to you

**Comment by avinci** [comment]
@pquentin We have made the change so that we do not use $HOME/ve as a folder. We use python to run out build and hence the conflict. Let me know if you still are facing issues with this.

**Comment by pquentin** [comment]
@avinci Thank you, that's perfect! Closing.
