### ISSUE TITLE
Pull request does not trigger build

### ISSUE THREAD

**Issue by Achse** [Shippable/support#1893]
Hello,

I have my pull request (here: https://github.com/damejidlo/damejidlo/pull/8078) and no build has been triggered after push. Hook for other CI (Scrutinizer) works well.

I have tried to change commit mesaage (to change commit hash) and force-push. It does not help.

Thank you for help.
Petr

**Comment by rageshkrishna** [comment]
Hi @Achse. We had a small hiccup in our build trigger system. Your build should have started running. Please take a look and let me know. Thanks!

**Comment by Achse** [comment]
`Shippable — Builds in progress on Shippable`

Thanks. :)
