### ISSUE TITLE
How to trigger build?

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#1894]
Hi,

I've pushed to our project (55d486cd1895ca44740e2a80) however it hasn't triggered a build - is there any option to manually trigger a build for a branch anymore? I've tried using Force Sync but the commit still hasn't come through.

Thanks

**Comment by rageshkrishna** [comment]
Hi @tomsterritt. Which branch are you trying to build?

When you visit your project page on Shippable, we list the latest build on each branch at the top of the page. By default we hide the branches that haven't run anything so far but there is a checkbox to "Show empty branches". Does that help, or are you not seeing the branch at all?

**Comment by tomsterritt** [comment]
The branch is there ('dev') - we've had builds running from it for a while. This commit just seems to have got lost, and I can't trigger it myself anymore it would seem?

**Comment by rageshkrishna** [comment]
There is a "play" button against each branch that should trigger a build. Is that not doing anything for you?

**Comment by rageshkrishna** [comment]
When you trigger a manual build we run with the tip of the branch.

**Comment by tomsterritt** [comment]
It gave me this error:
```
{"id":2100,"message":"No build found","methodName":"validateCaller|_checkAccessLevel"}
```

**Comment by tomsterritt** [comment]
There also seems to be a lot of these errors, but marked as 'Low':
```
Error parsing shippable.yml in "[redacted]"  Today at 2:46 PM
A build was attempted but failed for branch "dev" of "[redacted]."
```

They've not caused it to fail before though, it seems...

**Comment by rageshkrishna** [comment]
Hmm... did you make any changes recently to your YML file? Can you share it here or send it to me at ragesh@shippable.com so I can take a look?

**Comment by rageshkrishna** [comment]
Closing as this turned out to be an indentation error in the YML file.
