### ISSUE TITLE
Build fails with no explanation

### ISSUE THREAD

**Issue by chaserelock** [Shippable/support#1897]
Hi guys,
We're running into some black box failure here. Our CI steps get all the way to building our dockerfile successfully, after which the build fails quickly.

I'd love some insight or a way to debug this.

Here is what the UI looks like:
![screen shot 2015-09-22 at 12 05 00 pm](https://cloud.githubusercontent.com/assets/5704766/10028624/55c63aee-6122-11e5-851b-56c17c811d79.png)

**Comment by lekhab** [comment]
@chaserelock: have there any other similar failures since this build? I see your recent builds are running okay..

following up on this case.

**Comment by chaserelock** [comment]
Looks good now - you guys should mention that the user needs to be root in the pre-build CI flow
