### ISSUE TITLE
Services in EU?

### ISSUE THREAD

**Issue by alex88** [Shippable/support#1898]
Will it be possible to have services run in europe's aws datacenters?

**Comment by avinci** [comment]
@alex88 we are announcing a couple of Enterprise plans in the next 2 weeks. With this its absolutely possible to do this. Does that work?

**Comment by alex88** [comment]
@avinci Enterprise plans? that sounds pricy, we would run just 10/15 containers, I thought you were going to offer the formations thing with the ability to select Europe as DC

**Comment by avinci** [comment]
We call it Enterprise as it has a lot of other enterprise features like OnPremise Github adapters etc. We do not plan to charge for those adapters but will only enable them for specific plans. One of the features that was asked by enterprises was more control on the host machines. please stay tuned and happy to discuss this offline more details...

I do promise that there will be no sticker shock...
