### ISSUE TITLE
Support for autodeploy from GCR to Cloud compute

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#1899]
You have added support for GCR now, but would love to have an option to autodeploy to cloud compute.

We currently use autodeploy to elastic beanstalk, but gcr does not work well with EBS

**Comment by avinci** [comment]
@sheldon-sminq Can you let me know what you mean by auto deploy to cloud compute? We have done a lot of work in the last few weeks and wanted to know if we have addressed your scenario.

**Comment by sheldon-sminq** [comment]
I meant the similar flow to elastic beanstalk and docker deployment that
shippable supports
When a commit to github happens ci

**Comment by manishas** [comment]
@sheldon-sminq can you explain your scenario in a little more detail?

**Comment by manishas** [comment]
I am closing this issue, but please let us know if you want us to enable a specific scenario and we'll be happy to reopen and investigate. Thanks!
