### ISSUE TITLE
Can the pypy version be updated in the base minions?

### ISSUE THREAD

**Issue by mtimm** [Shippable/support#1900]
We have started to see the following in our pypy builds:

    pip install pyOpenSSL
    Downloading/unpacking pyOpenSSL
    Downloading/unpacking six>=1.5.2 (from pyOpenSSL)
      Downloading six-1.9.0-py2.py3-none-any.whl
    Downloading/unpacking cryptography>=0.7 (from pyOpenSSL)
      Running setup.py (path:/home/shippable/build_ve/python/pypy/build/cryptography/setup.py) egg_info for package cryptography
        Traceback (most recent call last):
          File "app_main.py", line 72, in run_toplevel
          File "app_main.py", line 578, in run_it
          File "", line 17, in 
          File "/home/shippable/build_ve/python/pypy/build/cryptography/setup.py", line 51, in 
            "cryptography 1.0 is not compatible with PyPy < 2.6. Please "
        RuntimeError: cryptography 1.0 is not compatible with PyPy < 2.6. Please upgrade PyPy to use this library.
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
    
      File "app_main.py", line 72, in run_toplevel
    
      File "app_main.py", line 578, in run_it
    
      File "", line 17, in 
    
      File "/home/shippable/build_ve/python/pypy/build/cryptography/setup.py", line 51, in 
    
        "cryptography 1.0 is not compatible with PyPy < 2.6. Please "
    
    RuntimeError: cryptography 1.0 is not compatible with PyPy < 2.6. Please upgrade PyPy to use this library.

Can pypy be updated from 2.2.1 to 2.6.1?

https://github.com/shippableImages/minBase/blob/master/ubu1204/02python/pythonInstaller.sh

Thanks!

**Comment by avinci** [comment]
@mtimm We are planning to sunset this min image as its becoming un-maneagble and move to native images. Is there any other pre-installed service that you use currently? or its just pypy?

**Comment by mtimm** [comment]
python 2.7, python3.4 and pypy are the ones we use.

https://github.com/datacenter/cobra/blob/master/shippable.yml

I'd happily switch to ubuntu1404_python or ubuntu1204_python if they included pypy.  I guess I could switch now and manually install pypy as needed.  Thoughts and suggestions greatly appreciated.

**Comment by avinci** [comment]
perfect. I will update the image and let you know the path. Thanks for your patience...

**Comment by avinci** [comment]
@mtimm, we have fully updated images with python. We will be launching this soon, but in the meantime you can use them with the following tags in your YML

`build_image : drydock/u14pyt:prod` or  `build_image : drydock/u12pyt:prod`

These are the versions installed. 
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4

The docker files are here
https://github.com/dry-dock/u12pyt
https://github.com/dry-dock/u14pyt

**Comment by mtimm** [comment]
Thank you @avinci, I noticed you did not mention pypy in the versions listed.  Was pypy added?

**Comment by avinci** [comment]
I did not add pypy. I will add it and let you know.

**Comment by kepkin** [comment]
Is there a documentation on how I can use ```build_image``` tag? I tried: build_image: python:3.4.4 but build doesn't work :-(

**Comment by mtimm** [comment]
@kepkin there is some info here: http://docs.shippable.com/project_settings/

**Comment by manishas** [comment]
@kepkin the build_image tag is officially unsupported. The right way to set a build image is to follow the instructions at http://docs.shippable.com/project_settings/#build-image. 

If your build image is private, you'll need to add an account integration with your docker registry credentials as explained in http://docs.shippable.com/docker_registries/

**Comment by manishas** [comment]
@mtimm btw, pypy was added to our python image -
docker hub - https://hub.docker.com/r/drydock/u14pyt/
github - https://hub.docker.com/r/drydock/u14pyt/ (you'll see pypy in the version folder)

Additionally, we also have images with python plus some services -
docker hub - https://hub.docker.com/r/drydock/u14pytpls/
github - https://github.com/dry-dock/u14pytpls

(the docker hub description doesnt say pypy - will have that corrected)

Let me know if the images work for you.

**Comment by kepkin** [comment]
Thanks @mtimm and @manishas. But what I'm looking for is a little bit different. If I use ```shippableimages/ubuntu1404_python``` as a build image, it will work. But if I use any other image from docker hub like ```python:3.4```, build will just timeout. What I should install in image in order to make it work on shippable?

**Comment by avinci** [comment]
@kepkin we have updated all our images etc. and also upgraded the build system completely from ground up. 

If you use any custom image, if its ubuntu, we install sudo & git. So if you want to do this on non ubuntu image, you will need some way to get git installed and also make sure your YML commands have root escalation like sudo, when you run docker commands. 

We do not officially support other OSes, but there are quite a few customers who do this debian, GNU etc.

Hope this helps
