### ISSUE TITLE
Make build debugging easy

### ISSUE THREAD

**Issue by megha-n-bodke** [Shippable/support#1902]
Currently build debugging is very hard and time consuming.
As there is no direct access to build environment, it has to be done through echo statements and log analysis.
Direct access will reduce this time drastically.

**Comment by avinci** [comment]
@megha-n-bodke We have been working on this for last 3 weeks and the first phase of this is complete with the second phase to be done by end of this month. I totally hear you wrt to this and we should have done this sooner than later. stay tuned. If you have a subscription ID, we can move you over to the new system if you would like to be on the Beta group.

**Comment by megha-n-bodke** [comment]
Hi Avi,

We are happy to be part of Beta group.
My id is 56068cdb4fcd3a0b00e186c4

Cheers,
Megha
