### ISSUE TITLE
/recentBuilds endpoint removed?

### ISSUE THREAD

**Issue by caarlos0** [Shippable/support#1903]
I was using the `/projects/PROJECT_ID/recentBuilds` endpoint to measure the AVG build time here... seems like it was removed?

Why?

How can I get something like that now?

Thanks

**Comment by lekhab** [comment]
@caarlos0: Sorry about that. We made some recent changes to our APIs (for the better!). You should be able to use  ```/projects/:projectId/searchBuilds``` to get the info you previously got from recentbuilds.

The API documentation on the route is updated here:

http://docs.shippable.com/api/#projects

Hope this helps. Please let me know if you have any further questions.

**Comment by caarlos0** [comment]
@lekhab 

> {"id"=>2000, "message"=>"Database error", "methodName"=>"caller:540e779e399939140041f191|builds|searchByProjectById:540e77a63479c5ea8f9e9017|_searchBuilds", "link"=>{"name"=>"MongoError", "$err"=>"Runner error: Overflow sort stage buffered data usage of 33557538 bytes exceeds internal limit of 33554432 bytes", "code"=>17144}}

What should I pass to get the latest builds?

**Comment by caarlos0** [comment]
@lekhab got it, I was passing 100 as limit, apparently that is too much. 50 worked.

Thanks!
