### ISSUE TITLE
Build "hangs" for about an hour between "after success" and "save reports"

### ISSUE THREAD

**Issue by winglian** [Shippable/support#1904]
The actual timings seem to be about 10minutes total, but takes over an hour to complete, with no output about what is happening. https://app.shippable.com/builds/5609999da4c15d0d007ec9f7

**Comment by jawaid** [comment]
@winglian Sorry to miss this. Are you still having this issue?

**Comment by winglian** [comment]
@jawaid I wouldn't be able to tell you at this point. The unresolved bug became intolerable so we had to switch to another service for our CI. Thanks for following up.

**Comment by avinci** [comment]
@winglian sorry about not being responsive. We have cleaned up quite a bit of our code. Hopefully you will give it a try sometime in the future...
