### ISSUE TITLE
Ability to zip files in shippable.yml

### ISSUE THREAD

**Issue by aschwabe** [Shippable/support#1905]
I have scoured documentation and can't seem to find an answer.

Problem:  Using elastic beanstalk, want to do a custom build of an app and incorporate shippable's build id info.  This requires me to create a local zip file, and then have elastic beanstalk configured to look for that archive to deploy instead of the default git archive.

in my shippable.yml, i've tried the normal apt-get zip variations, which yield a "E: Unable to locate package zip" error.

There has to be a way, yes ?  If not, it would be super helpful to HAVE a way, since some of us may want to do custom zips of build stuff and push it to S3 or elsewhere.

**Comment by pquentin** [comment]
Did you try [unzip](http://packages.ubuntu.com/precise/unzip)?

**Comment by DavidGDragon** [comment]
You should be able to zip a file with the `zip` command
`zip myArchive.zip file1 file2 fileN`

**Comment by avinci** [comment]
You need to make sure you understand the relative path of where the build is running. I would suggest doing `pwd` in your YML and see the current folder. There are also quite a few ENV vars that you can use to get the dynamic build number folder etc. You could add `printenv` to your YML `before_install` section and it will print all the things that are set as part of the build environment. 

We should document this..:-) duh.
