### ISSUE TITLE
cannot delete a project

### ISSUE THREAD

**Issue by richhl** [Shippable/support#1906]
To reproduce:

login with my account
go to project settings https://app.shippable.com/projects/560a75471895ca447418c7c0/settings
click trash can
got  {"id":3000,"message":"Not Authorized to perform this action","methodName":"caller:540f589205bbf06a0205b786|projects|chkPermForId:560a75471895ca447418c7c0|_chkPermForId"} 

thx in advance

**Comment by DavidGDragon** [comment]
Only owners of a project can delete a project, collaborators cannot.
