### ISSUE TITLE
trying to deactivate formation gives error

### ISSUE THREAD

**Issue by RazvanPetruescu** [Shippable/support#1907]
Pressing deactivate formation - I want to remove credit card details.

Error message : 

{"id":1003,"message":"Missing body data :unitType","methodName":"caller:55a37aa351e4f50b00051639|subscriptionPlans|post|_checkInputParams"}

**Comment by rageshkrishna** [comment]
Hi @RazvanPetruescu. We're looking in to this and will have an update soon.

**Comment by rageshkrishna** [comment]
@RazvanPetruescu We've deployed a fix. Please try this out again and let me know how it goes. Thanks!

**Comment by RazvanPetruescu** [comment]
@rageshkrishna seems to be working, thanks!
