### ISSUE TITLE
Run arbitrary service containers

### ISSUE THREAD

**Issue by gtaylor** [Shippable/support#1910]
Hello!

We have the need to be able to run arbitrary service containers for a few daemons that our integration tests require. For example, NSQ, Cassandra, and some other stuff that can be found on public Dockerhub.

Is there any way to run arbitrary containers and link them in with the container being used in the Pre-CI Docker build flow?

**Comment by avinci** [comment]
@gtaylor This is possible with the new enterprise plans coming in the next couple of weeks. On multi tenant SaaS product this is not possible due to port and network security that we have enabled. Would be happy to talk more about the new plans if you would like to beta test it.

**Comment by gtaylor** [comment]
After doing some more research, it sounds like there are some other existing services that a bit further along with this. Given our timeline, I think we'll try one of them out.

Best of luck with the new development. It sounds like you're heading in the right direction!
