### ISSUE TITLE
Yet another case of all build steps succeeding, while marking the build as failed.

### ISSUE THREAD

**Issue by nigelwinterburn** [Shippable/support#1911]
https://app.shippable.com/builds/560cf11d8bd2640d0096e25d

This issue happens very frequently, perhaps every time I update my docker container. I have deleted and re-added the project and I'm still running into issues. 

![screen shot 2015-09-30 at 10 53 07 pm](https://cloud.githubusercontent.com/assets/12054443/10216620/26b54bf0-67c6-11e5-8c62-86789862d4d0.png)
![screen shot 2015-09-30 at 10 53 13 pm](https://cloud.githubusercontent.com/assets/12054443/10216619/26b50e06-67c6-11e5-8f59-14149723eb2f.png)

Previously reported by me in https://github.com/Shippable/support/issues/1804, previously reported by many others many times.

I :heart: shippable, but I'm really getting tired of this. https://twitter.com/ndm/status/649504873306832896

**Comment by avinci** [comment]
@nigelwinterburn we are massively cleaning up this handler. We have had tons of problem with how we handle post build workflows and if there is an error, we are not surfacing that to the user. We should have a fix in the next week and this should not happen or if it does, we will have console which shows why...

Hope that helps.

**Comment by avinci** [comment]
I don't think this should be happening anymore. Please let us know if it is still happening. closing it as we have not seen this on our side anymore
