### ISSUE TITLE
Mulple ssh key

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#1912]
Where is any posibility to add multple ssh keys to agent?
Because Bitbucket not allowing to use the same key twice.

**Comment by avinci** [comment]
@luckyraul Could you elaborate a bit more on what you are trying to achieve here? There might be a way to do it now.

**Comment by luckyraul** [comment]
I need two ssh keys to provide cloning from multiple bitbucket repositories. I can't use your key in them both since Bitbucket not allowing to use the same key twice in different repositories.

**Comment by avinci** [comment]
There are two possible solutions.
* one is to use the subscription key and add that to your account as an external trusted key. Now you have impersonated shippable build account as yourself and as along as you have access to the repos it should work across orgs, repos etc.
* second is if you don't want to shippable to impersonate you. You can create a new bitbucket account and give that account permissions to the necessary repos and then add the shippable subscription deployment key as an approved external key.

Both these scenarios should allow you to achieve what you need. More info on deployment keys http://docs.shippable.com/ci_settings/#deployment-key

Let me know if this helps
