### ISSUE TITLE
Use shippable.yml from result of merge of PR with HEAD of branch

### ISSUE THREAD

**Issue by bgrant0607** [Shippable/support#1914]
Every time we (Kubernetes) need to change shippable.yml to match a corresponding change in the source it breaks hundreds of outstanding github PRs, none of which touch whatever it was we changed. 

I couldn't find clear documentation about it, but it appears that shippable.yml is always taken from the PR rather than from the result of merging the PR with HEAD of the appropriate branch. Unfortunately, because the source is merged, tests will fail due to an inconsistent test matrix configuration.

This behavior prevents our automated merge queue from working adequately, since progress grinds to a halt once a shippable.yml change is merged.

Please consider changing this behavior. It doesn't make sense for shippable.yml to be inconsistent with the source.

**Comment by avinci** [comment]
@bgrant0607 Yes, you are right. We take the shippable.yml from the PR if it is present and then merge it the the branch against which the PR was opened. This behavior is present to allow for the first commit itself to be a PR as well future changes to the YML to be supported through PR.

If the PRs are merged in the order they were created, it should not technically break unless an earlier PR will break the consistency of the current PR, which is what is happening if I am not mistaken.

It just means the state of branch against which the PR was made against has changed and technically if this breaks the tests should it not really fail? 

Do you have a suggestion on how you would expect this work? I think either way we go, we will end up breaking the other side right?

**Comment by bgrant0607** [comment]
Thanks much for the response. If shippable.yml is taken from the result of merging the PR with HEAD, that is the behavior we want. I'll look again into the failures we've seen to see whether something else is going on.

**Comment by bgrant0607** [comment]
FWIW, this is a change that broke even seemingly non-conflicting PRs: https://github.com/kubernetes/kubernetes/pull/14156/files
