### ISSUE TITLE
Python test results and coverage reports are not parsed

### ISSUE THREAD

**Issue by megha-n-bodke** [Shippable/support#1915]
I have following script to generate testresults and coverage. As we can see in ls those files are being generated. 
```
py.test -k 'not functional_tests' --ds=lb.settings.ci_test --junit-xml=/home/shippable/testresults/results.xml
ls /home/shippable/testresults/results.xml
 /home/shippable/testresults/results.xml
coverage run --source='.' manage.py test --settings=lb.settings.ci_test
coverage xml -o /home/shippable/codecoverage/coverage.xml
ls /home/shippable/codecoverage/coverage.xml
 /home/shippable/codecoverage/coverage.xml
```
But save_reports do not parse any reports:
```
save reports 0.00 seconds
  parse coverage reports
No Coverage reports to parse
  parse test reports
No Test reports to parse
```

I am doing something wrong here?

**Comment by avinci** [comment]
@megha-n-bodke are you sure your tests are writing the files to that directory? Is there a projectId that I can look at that you are testing?

**Comment by megha-n-bodke** [comment]
Hi Avi,

Here are the details:
Account Id: ID: 56068cdb4fcd3a0b00e186c4
Link to build: https://app.shippable.com/builds/5613e20074520f0d00a12e3c

Let me know if you need anything else.

Regards,
Megha

**Comment by manishas** [comment]
we have completely redone our test and coverage reports handling, so closing this issue. please let us know if you run into this again.
