### ISSUE TITLE
i registed 2 account by one auth my github and the other auth my bitbrucket.

### ISSUE THREAD

**Issue by zixia** [Shippable/support#1918]
now the system treat me like to identities.

I want to delete one and re-link them together, but the "delete account" feature is not availble now.

could you help me to delete my account manually?

thx.

**Comment by lekhab** [comment]
@zixia: which account would you like deleted? the github one or bitbucket?

**Comment by zixia** [comment]
bitbucket, please. :+1:

**Comment by avinci** [comment]
@zixia Can you give me your bitbucket account login so that I can delete it.

**Comment by zixia** [comment]
the same as my github email: zixia@zixia.net

thanks!

**Comment by avinci** [comment]
this has been deleted.
