### ISSUE TITLE
Build failed after pulling image from dockerhub

### ISSUE THREAD

**Issue by marcogario** [Shippable/support#1919]
The build fails. Usually only one or two of the jobs fail, while the other are successful. Successive runs might have a different set of jobs failing. Looking at the log of the failed jobs, we see only that the (custom) docker image is being pulled from docker hub, with the last line of the log saying:
```
Status: Downloaded newer image for pysmt/pysmt-docker:latest
```

After this, the tests are not executed and the next step is 'save reports'. 

https://app.shippable.com/builds/5616561ebf5f9b0c00cfd1c9

**Comment by marcogario** [comment]
Related: #1920

**Comment by marcogario** [comment]
The problem persists [1]. I also tried changing the docker image we are pulling from. Any hope this can be looked into?

[1] https://app.shippable.com/builds/56168edc61d1110b00cc9bf8

**Comment by manishas** [comment]
We are looking into this and will update you soon..

**Comment by marcogario** [comment]
On my side, you can close the issue. The issue kept occurring, and we were forced to change CI service.
Thanks for looking into it.

Best Regards,
Marco

**Comment by avinci** [comment]
@marcogario thanks for trying this out and letting us know about the problem. We found the issue and have fixed it and it should helps other for sure. Hopefully you will give us a try once again sometime in the near future...
