### ISSUE TITLE
Builds not continued after the testing images is pulled

### ISSUE THREAD

**Issue by chaserelock** [Shippable/support#1920]
You can look at any of our recent builds, the test image is pulled and then there's nothing for a while, followed eventually by "Saving Reports". Essentially skipping...everything

For whatever reason we're no longer seeing the git sync step, which makes me think that there's some issue starting up or running our test container. I can't actually debug it because I don't know how shippable is starting it up and there are no issues running locally. I'd love some insight.

**Comment by avinci** [comment]
@chaserelock TLDR, this should be fixed. In case you want to know what happened or for others who are following the conversation...

We had a weird bug that we could reproduce and was tough to chase down. This happens at scale when docker daemon becomes unresponsive in certain cases. In those, it returns a success but the immediate next command fails as the internal cache is not yet update at the deamon level. This was why builds containers would not come up as we first `docker remove [containerName]` before spinning it up and that causes the daemon to lock up. When we then spin the container, we get an error saying `cannot spin a container thats marked for deletion`. This was not handled by us and hence the issue. We have fixed this and hopefully this should make it a lot more stable.

Thanks for your patience and let me know if you still this issue
