### ISSUE TITLE
Builds stuck for 2 hours

### ISSUE THREAD

**Issue by JADurham909** [Shippable/support#1921]
I do not have any active builds, but my build has been stuck waiting for 2 hours.  I tried to cancel it, but I cannot get another one to run.

**Comment by JADurham909** [comment]
My current build has been waiting for 30 minutes.

**Comment by JADurham909** [comment]
3 hours and its still waiting.

**Comment by manishas** [comment]
We're looking into this...

**Comment by trriplejay** [comment]
@JADurham909 

Hello, would you mind if I trigger a build for your project to help track this down?

**Comment by JADurham909** [comment]
Not at all go for it.

**Comment by trriplejay** [comment]
@JADurham909 looks like your build is running again now. Let me know if you have other problems.
