### ISSUE TITLE
Laravel 5.1 user interaction testing

### ISSUE THREAD

**Issue by Lammmas** [Shippable/support#1926]
Hello,

In Laravel you can test user interaction by visiting URLs and simulate user interactions. However, when I try to do that I keep getting this error:

```A request to [localhost] failed. Received status code [404].```

I've tried sending an email via the contact form, but no reply. What would be the correct URL to use? localhost:80 is not working, so should it be localhost:8080 or localhost:8000 or something else?

Sample build is ```5614ed7114fb560c001935c9```

Thank you,
Renna

**Comment by daylightstudio** [comment]
I'm running into a similar issue and have specified the protected $baseUrl property on my test class to match the testing URL in my environment as well but am still getting the 404 error message.

**Comment by masterbits** [comment]
having the same after i install the new laravel version. please help....

**Comment by avinci** [comment]
I am not too sure about Laravel, but let me play around with this and see if I can make it happen.

**Comment by avinci** [comment]
Based on a quick read, how are you starting your PHP app? Are you using some sort of a web server locally? I can't seem to access your build. Is this a public project? Can you send me the YML you have? avi@shippable.com

**Comment by masterbits** [comment]
I got my issue resolved. i just found out that inside my controllers constructor i did change the header to convert some input into utf8. so what i did was remove any code that changes the header.

**Comment by Lammmas** [comment]
Hello,

Thank you for your response. For me the issue is also resolved, and it seems to have been an issue with the correct configuration of Laravel for your environment and running the Artisan test "server" correctly. For future reference I'm adding this link: https://laracasts.com/discuss/channels/testing/artisan-serve-can-not-open-localhost
