### ISSUE TITLE
Allow notification of pull request owner 

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#1927]
When a build is triggered for a branch or pull request it would be nice to have a way to notify the branch committer or pull request creator the status of that build regardless of success or failure.

No one else on the team is likely interested.

Today you have to put the notification emails directly in the .yml and there is no way to indicate committer/pull request creator dynamically.

**Comment by manishas** [comment]
we have revamped notifications and now it is possible to [specify the committer dynamically](http://docs.shippable.com/ci_configure/#email-notifications). I don't think we plan to support different rules for different roles in the near future unless we hear recurring feedback around this.

Closing this issue.
