### ISSUE TITLE
Fail to deploy to Amazon EBS, EOFError on prompts

### ISSUE THREAD

**Issue by jakemmarsh** [Shippable/support#1928]
I have my build working and all my tests/running passing correctly. In my `after_success`, I'm attempting to deploy to Amazon EBS using the steps provided in your documentation.

When it begins the `eb init && eb deploy` step, I get the following prompt/error:

```
It appears you are using Node.js. Is this correct?
(y/n): ERROR: EOFError :: EOF when reading a line
```

I can't seem to find anyone else having this problem, or any documentation about how to specify platform in `config.yml`. I did recently remove the platform specification from `shippable.yml` in order to only install node via nvm and skip the manual build to decrease deploy time (saw this tip in another issue reported here). Any ideas?

**Comment by jakemmarsh** [comment]
I fixed the first error by adding `default_platform: node.js` to my `config.yml` file.

Now, it's failing on the prompt `Do you want to set up SSH for your instances?`. I'm assuming this can also be defined in `config.yml`, but I've yet to find the correct option. Documentation for possible values in this file is very poor

**Comment by avinci** [comment]
@jakemmarsh I will try to look into docs and see if I can write a sample app. Sorry for the delay in response

**Comment by kanthchandra** [comment]
Hi @jakemmarsh  It looks the you are doing a interactive eb init and the awscli is waiting for a command line input. So can you please send me the config.yml and shippable.yml to chandrakanth@shippable.com so that I can take a deeper look at this?
