### ISSUE TITLE
Bitbucket hooks not triggering builds

### ISSUE THREAD

**Issue by JADurham909** [Shippable/support#1931]
Commits to master branch are no longer kicking builds for any repositories on Bitbucket.

**Comment by JADurham909** [comment]
I can manually kick them.

**Comment by lekhab** [comment]
@JADurham909 - there's a current issue with bitbucket webhooks posted on the Bitbucket status page:
http://status.bitbucket.org/

**Comment by JADurham909** [comment]
thanks, this is working again.
