### ISSUE TITLE
Slack build notification should show the test results for individual builds

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#1932]
A project I am running on Shippable reports weird numbers like `698/702 tests passed` or `788/792 tests passed` upon build notification in Slack. The notification correctly indicates a successful build but the test number is totally off. For an example see build `561781993a54720b00048afd`.

**Comment by rageshkrishna** [comment]
@mbrodala We're reporting the total number of tests across all the builds in the matrix. If you add up all the tests in each build, the numbers should match. But I can totally see how this is confusing. We should probably improve our notification to show test numbers for individual builds.

**Comment by mbrodala** [comment]
Ah, I get it, now it at least makes sense why the build is reported as successful even though not all tests have passed. ;-)

**Comment by rageshkrishna** [comment]
Hmm, that definitely should not be happening. If the tests fail the build should be reported as 'unstable' or 'failed', depending on how your test runner likes to report errors. I will open up an issue internally to track this down.

**Comment by mbrodala** [comment]
Sorry for not being clear here: some of the builds fail but are also allowed to fail, so this is perfectly fine. Thus the unequal number of executed and total tests.

**Comment by mbrodala** [comment]
The current state is fine for me actually since I understand its reason. I don't know how the message could be changed without cluttering it heavily to separate the results of jobs.
