### ISSUE TITLE
Builds failing with internal API error

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#1934]
I have configured a build for a private Java Maven repository hosted on Bitbucket.  One out of every few builds is failing with the following error:

> Error occurred while generating build meta-data: Internal API Error : getPermissionByProjectId

Simply re-running the build usually succeeds.  However, the repeated failures are causing false alarms for the team as non-technical users are habitual of taking a look at the build status page and get surprised on seeing so many failures.

**Comment by rageshkrishna** [comment]
@manish-in-java We're currently seeing some issues with webhook builds. We're looking in to this and will have an update soon.

**Comment by rageshkrishna** [comment]
@manish-in-java We deployed a fix for this a few hours ago. Please let me know if you're still seeing this. Thanks.

**Comment by manish-in-java** [comment]
I triggered a build just now and it succeeded.  If you are certain that the underlying issue has been fixed, please feel free to close this issue.  I will raise another one if I run into a problem later.

**Comment by manishas** [comment]
Yes, we've fixed the underlying issue. Thanks for letting us know it works now!

**Comment by bselva** [comment]
I am having the same problem today. Can you check for us?
`Error occurred while generating build meta-data: Internal API Error : getPermissionByProjectId`
Thanks,

**Comment by manishas** [comment]
looking into it...

**Comment by manishas** [comment]
@bselva this is now fixed and deployed. can you confirm that it works for you?

**Comment by bselva** [comment]
Great! It's working now!
