### ISSUE TITLE
Using multiple projects' build outputs

### ISSUE THREAD

**Issue by cduzan** [Shippable/support#1935]
I have multiple repos that each contain a project. I want to keep these separate so every time something is committed that specific project is built and tested separately in Shippable. Fairly straightforward Shippable functionality, I don't have any problems with this part.

However, these projects are pieces to a whole that needs to be deployed together. Is there a way to store the necessary parts of each of these projects to in a container to be deployed out to Dockerhub?

**Comment by cduzan** [comment]
Just found Docker Compose. This looks like the solution I need.

**Comment by avinci** [comment]
You can use Docker Compose as long as you are ok to hardcode a lot of these. If you would like to keep it more run time options, look into Shippable formations

**Comment by cduzan** [comment]
Thanks @avinci . I'll definitely take a look at this. I'm new to Shippable and Docker so I'm kind of just learning as I go
