### ISSUE TITLE
Go build test randomly failing

### ISSUE THREAD

**Issue by jdextraze** [Shippable/support#1936]
I get a "cannot find package" when my go tests run on shippable. And the missing package folder is in my project repository, not an external package. How can this be possible?

Like I said, this is randomly happening... I re-run the build and it works.

Any idea why?

Example build: 561843a34ebffb0c00ce87d0

**Comment by manishas** [comment]
Just filed an internal bug.... will look into this and get back to you.

**Comment by manishas** [comment]
@jdextraze is this still happening?

**Comment by jdextraze** [comment]
No. Thanx.
