### ISSUE TITLE
Shippable not reacting to commits in some of the projects

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#1938]
Hello,

Shippable stopped to automatically detect new commits in one of my projects.

This is sample build that had to be triggered manually, despite commit being pushed to bitbucket: https://app.shippable.com/builds/5619182fe1819f0d00abf9b6

**Comment by tudvari** [comment]
Hi, 

do you have any restrictions in your shippable.yml file? For example:

branches:
  only:
    - master

This rule allow just the master branch.

**Comment by mspanc** [comment]
No, I don't have any restrictions, the same script was working properly some time ago, it was untouched.

**Comment by avinci** [comment]
@mspanc Currently we don't support PR hooks on bitbucket. We are working on this right now and should be available in the coming week. Let me know if thats the case.

**Comment by mspanc** [comment]
@avinci it's not the case of pull request. It's regular workflow of pull/add something/commit/push.

**Comment by avinci** [comment]
I am going to look into it. Sorry for the delay, I just got back from a business trip. We are starting to surface all the errors which were being silent over into the console logs if we don't see a build fire. 

Let me look into your specific project and do you mind if I fire a couple of test builds?

**Comment by mspanc** [comment]
@avinci sure, this project can be investigated. It's just a project that pushes certan repository to heroku once this repo is updated.

**Comment by avinci** [comment]
What time zone are you in? We might have to test web hooks which means you might need to do some fake test commits to READMe or something....I will get an engineer on my side to look at the logs.

**Comment by mspanc** [comment]
@avinci I am in CEST

**Comment by mspanc** [comment]
@avinci this project also stopped working right now https://app.shippable.com/builds/5626a8cb54d5c20c004885ea

**Comment by avinci** [comment]
It seems like the build lost connection to some server (db or something). Are you trying to connect externally or is it a local server on the build minion?

**Comment by mspanc** [comment]
It's local server.

**Comment by avinci** [comment]
It seems like a hiccup in the build process. Once we start the build process, we do not touch the workflow. Can you put some retry logic into that db script? What type of db is this? Not sure what could cause the local db to stop taking connections.

**Comment by mspanc** [comment]
I am unable to put the retry logic as it can make test suite non-deterministic.

This is regular postgresql.

Recently it started to work without changing anything. Are you sure we don't hit resource limit and there's no out-of-memory killer engaged?

**Comment by avinci** [comment]
We currently set the limit to 2gb and 2 cores and thats guaranteed. We are recently seeing an uptick in usage and we have added more capacity. Please let me know if it happens again...
