### ISSUE TITLE
Psi integration (Pagespeed insights)

### ISSUE THREAD

**Issue by BradleyFord** [Shippable/support#194]
Hi Shippable team,

Whilst we are not yet up an running with Shippable yet (The docs are not clear how to get tests working...)

It would be great if we could include Psi integration in the frontend; so it will automated performance testing as part of the results.
https://github.com/addyosmani/psi

**Comment by manishas** [comment]
You can install psi on your minion through your yml and use it for your builds. Please let us know if this doesn't work.
