### ISSUE TITLE
Error while generating build

### ISSUE THREAD

**Issue by pmacosta** [Shippable/support#1940]
Late Sunday (EST) builds started to error out in the first step, I get:
+ Generating builds
    + Error while generating build for branch develop
        Error saving build meta-data: Database error

Example build 429, commit 1b8a845

**Comment by fabiocarneiro** [comment]
same for me 5621b6fba38bad0e009603a4

**Comment by avinci** [comment]
@fabiocarneiro 5621b6fba38bad0e009603a4 failed cos in the branch develop.95 there is no YML. Can you check again?

@pmacosta can you give me a buildId. Its hard for me to find which build it is without know the projectId or the projectName

**Comment by pmacosta** [comment]
Hi Avi,

Build 9d8ac32
<https://bitbucket.org/pmacosta/putil/commits/9d8ac3210d3d7e8b25f18c73e9e19909e040cd84>,
repo pmacosta/putil.

Thanks for any help you can provide!

Pablo

**Comment by pmacosta** [comment]
No need to investigate this issue any further (if you still are), moving on to Travis.

**Comment by avinci** [comment]
@pmacosta we are cleaning up quite a bit of complexity that was in this part of the code. It should get much much cleaner. I understand your decision and thanks for pushing us to make this change which was a tough one for us. but its the right thing to do to reduce the flakiness

I will close this and please re-open if you still need it.
