### ISSUE TITLE
Building a container with just a go (golang) binary

### ISSUE THREAD

**Issue by geoah** [Shippable/support#1941]
I'm interested if it is possible to build and push a container `FROM scratch` that just contains the binary of a golang application (instead of actually pushing the golang container with the source the the built binary)

Our workflow the following; currently uses travis with `requires sudo` and a makefile that does all the dirty work for us:
1) Create a build container `FROM golang`, test & build the binary from the repo (building is using the same makefile)
2) Copy the binary out of the container
3) Create a production container `from scratch`
4) Push the production container to private repo

Parts 1 and 4 do not have to be done manually but were done so due to travis limitations, shippable might be able to do them differently.
So I'm basically asking if we can perform 2 & 3 with shippable somehow.

Thanks :)

**Comment by avinci** [comment]
Yes. This is definitely possible. We have a way to copy artifacts out from a container and create a prod container and push this out. 

attaching our docs to achieve this. They key is you need to do PostCI build in order to achieve this.

http://docs.shippable.com/docker_build/#copying-artifacts-to-prod-image

Let me know if this helps

**Comment by GameXG** [comment]
Documentation errors, the document above all

-tip
-release

http://docsv2.readthedocs.io/en/latest/languages/go.html
http://docsshippable.readthedocs.io/en/latest/custom_images.html

**Comment by manishas** [comment]
@GameXG that is the older copy of our docs. Here are the latest docs - http://docs.shippable.com/ci_configure/

Can you share your scenario so we can help with the config?
