### ISSUE TITLE
Test results aren't being parsed

### ISSUE THREAD

**Issue by chinthakagodawita** [Shippable/support#1943]
We've got PHP CodeSniffer running under a custom Docker container outputting a JUnit XML report file (to `<build-root>/shippable/testresults/phpcs.xml`).

This used to work but now simply doesn't display any of the test results. Has something changed within shippable? Output from shippable is:

```
save reports 0.00 seconds
  parse coverage reports
    No Coverage reports to parse
  parse test reports
    No Test reports to parse
```

**Comment by sdlarsen** [comment]
I have the same issue. Tests are run, coverage report generated but nothing shows up. My projects are python. Something must have changed as this has been working for quite some time.

**Comment by rageshkrishna** [comment]
We're looking in to this. I'll update this issue as soon as I have more details.

**Comment by rageshkrishna** [comment]
This has been fixed. @chinthakagodawita @sdlarsen Please try another build and let me know if you're still running in to this. Thanks!

**Comment by sdlarsen** [comment]
@rageshkrishna: My builds are fine again. Thank you.

**Comment by rageshkrishna** [comment]
Thanks for the update @sdlarsen 

@chinthakagodawita I'm going to close this issue now as it has been resolved. Please reopen this if you still see this happening on your projects.

**Comment by chinthakagodawita** [comment]
All good for me as well, thanks for the quick response @rageshkrishna!
