### ISSUE TITLE
Error while generating build for branch master

### ISSUE THREAD

**Issue by rkiciak** [Shippable/support#1944]
We are experiencing errors on builds currently:

> Error while generating build for branch master
> Error occurred while generating build meta-data: Internal API Error : getPermissionByProjectId

See build `561cd9f8f44b4610006f18c1` for example.

**Comment by fabiocarneiro** [comment]
same for me 5621b6fba38bad0e009603a4

**Comment by avinci** [comment]
@fabiocarneiro Your issue is a bit different as I commented on the other issue. @rkiciak I see that your projects are running now. I will resolve and close this issue
