### ISSUE TITLE
web hook not working for one of my projects

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#1945]
Hi, 

A build is not triggered if I push a commit to my repository even though there one configured which has been working properly in the past. 

please checkout this project: https://app.shippable.com/projects/552cbd655ab6cc1352c32b68

How can I enable the web hook for this project? 

Kind Regards,
Ron

**Comment by EHLOVader** [comment]
I am actually having the same issue in one of my projects https://app.shippable.com/projects/555d3a2eedd7f2c052f69002

was working but is no longer. Requires manually running the build, and I even tried resetting the project to fix any broken webhooks.

**Comment by kanthchandra** [comment]
@EHLOVader @rvdwijngaard We have deployed a fix for this issue. Can you please confirm if it works?  Thanks
