### ISSUE TITLE
Allow developers/collaborators access to clear cache button

### ISSUE THREAD

**Issue by catskul** [Shippable/support#1950]
As far as I can tell, to uniformly clear the cache, a user has to be the project owner.

This makes it very difficult to debug cache problems, and allow developers on the project to work independently to get related work done.

**Comment by avinci** [comment]
We will get this implemented ASAP.

**Comment by avinci** [comment]
In the meantime, in the commit message of your PR, if you put in the text `[reset_minion]` , it should clean cache. I have an open issue internally to fix the API permissions

**Comment by avinci** [comment]
this has been implemented and deployed to production. Please let me know if it works for you. resolving it.

**Comment by catskul** [comment]
Great! Will do.
