### ISSUE TITLE
Stuck on 0.5 GB of RAM

### ISSUE THREAD

**Issue by camullen** [Shippable/support#1951]
It appears that my subscription is stuck on the following:

Muti-tenant plan for Continuous Integration — 2 cores, 0.5 GB RAM per minion

I'd like to be able to get the full 4GB per minion. Can you fix my config?

**Comment by manishas** [comment]
I've logged an internal error for this. This seems to be a UI issue since all our containers have the same resources on multi-tenant CI.

**Comment by rageshkrishna** [comment]
The value in the plan was wrong. I have updated it in prod.

**Comment by rageshkrishna** [comment]
@camullen Sorry, my previous comment should have been clearer. The underlying issue has been corrected and you should be seeing the right value show up in your subscription now.
