### ISSUE TITLE
Error while generating build for branch develop

### ISSUE THREAD

**Issue by fabiocarneiro** [Shippable/support#1952]
Generating builds
  Error while generating build for branch develop

https://app.shippable.com/builds/56223202bb2a6b0d002a44b8

**Comment by avinci** [comment]
I think this is happening due to some unicode issue. We are looking into it and will have a fix soon.

**Comment by fabiocarneiro** [comment]
@avinci My builds are also not running automatically. This is what happened when I tried to re-run a previous build.

**Comment by fabiocarneiro** [comment]
@avinci Any updates? I need this working so I can convince my boss to buy some minions :dancers:

**Comment by avinci** [comment]
@fabiocarneiro I will get back to you on tomorrow. I can see that your master branch is running, so its something weird with develop branch and will need a couple of devs to debug. I will make sure someone takes a look at this tomorrow.

**Comment by rageshkrishna** [comment]
@fabiocarneiro I'm looking in to this issue now. I hope you don't mind me triggering a few builds on your project to debug this.

**Comment by fabiocarneiro** [comment]
@rageshkrishna have fun

**Comment by fabiocarneiro** [comment]
@avinci nothing yet? :cry:

**Comment by rageshkrishna** [comment]
@fabiocarneiro We're still working on this. There appears to be an issue with PR builds on your project. For some reason we are not able to correctly detect a shippable.yml file for PR webhooks from your project. We are working to resolve this as a top priority right now.

**Comment by fabiocarneiro** [comment]
@rageshkrishna not my project, but my project**s**, its not happening in only one.

**Comment by manishas** [comment]
@fabiocarneiro we have identified the issue for manual reruns of PR builds not working and we'll let you know as soon as it's fixed. 

Is that the only issue you're seeing or are there more? Are your webhook builds working?

**Comment by manishas** [comment]
@fabiocarneiro can we jump on a hangout when it's convenient for you? It will be much faster to debug further. Since you're in Germany, we can either meet at 9am or 5pm your time tomorrow.  Please let me know which works better.

**Comment by manishas** [comment]
@fabiocarneiro we have pushed fixes for this issue. Please re-open if you run into any problems.
