### ISSUE TITLE
CD Docker Image to AWS EBS

### ISSUE THREAD

**Issue by andylibrian** [Shippable/support#1953]
I tried to setup a Continuous Delivery based on this article http://docs.shippable.com/autodeploy-to-ebs/.
It is working, but how do I configure which branch deploy to which env?
Currently any branch deploy to the same ebs env. I want to set it up so that master branch will be deployed to prod env, staging branch to staging env, and so on.

**Comment by avinci** [comment]
@andylibrian exactly what we are working it. Give us a few days and your should see this as a beta feature. Would you like to be part of our Beta program?

**Comment by andylibrian** [comment]
Sure, thanks!

**Comment by rsweetland** [comment]
Any news on when this might be available?

**Comment by avinci** [comment]
We just implemented this allowing a single branch deploy. We cannot make this dynamic at this point as it required tons of metadata to be transferred as EBS deploy of a container has to be done outside the build container. 

The right way to do it is use our deploy functionality that we launched recently. Let me know if that works.
