### ISSUE TITLE
PHP Extensions :: Mongo

### ISSUE THREAD

**Issue by Sebastien-Meiffren** [Shippable/support#1954]
Hello,

I'm trying to run shippable with a PHP project, in 5.6, with the Phalcon Framework. I managed to have the Phalcon framework running but Mongo so file doesn't seems to load itself up.

```
language: php

php:
  - 5.6

services:
  - mongodb
  - memcached

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - DIRECTORY="${PWD##*/}/cphalcon"
  - if [ ! -d "$DIRECTORY" ]; then git clone --depth=1 git://github.com/phalcon/cphalcon.git && cd cphalcon/build && ./install && cd ../.. && echo 'extension="phalcon.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini


before_install:
  - export PATH=$HOME/.phpenv/bin:$HOME/.phpenv/extensions:$PATH && eval "$(phpenv init -)"
  - phpenv global $SHIPPABLE_PHP_VERSION
  - php --version

script:
  - cd myCOL/tests
  - phpunit  --log-junit ../../shippable/testresults/junit.xml --coverage-xml ../../shippable/codecoverage --configuration phpunit.xml

notifications:
   email: false
```

PS 1 : I'm assuming that I don't need to put the so as it is provided in the example since now in the documentation it says that shippable comes with it
PS 2 : I have the same issue with memcache

Thanks :)

**Comment by Sebastien-Meiffren** [comment]
pecl install mongo doesn't work either. It says 
```
pecl: command not found
```

**Comment by mbrodala** [comment]
You could try installing `php5-pear` before.

**Comment by mbrodala** [comment]
Also see #2086 where I had a similar issue with the `intl` extension.

**Comment by Sebastien-Meiffren** [comment]
For futur reference, thanks to @mbrodala, this is what I put in my before_script section
````
  - sudo apt-get update
  - sudo apt-get install --yes php-pear libicu-dev php5-memcached
  - yes '' | pecl upgrade mongo
  - echo "extension=mongo.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension=memcached.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
````

But the fact that the documentation is not up to date (or working) remains ...

**Comment by manishas** [comment]
Thanks @mbrodala!

We're rewriting documentation and this will be available in next couple of weeks. We're adding an FAQ section where these tips and tricks will be aggregated so folks can find them easily. 

With regards to this specific issue, I'll get someone to follow up on Monday and explain what's going on.

**Comment by Sebastien-Meiffren** [comment]
OK I'll wait for the update cause Mongo + mySQL doesn't seems to be working properly as well despite the fact that it seems to have started (can't connect even with the right port / user / pass)

**Comment by manishas** [comment]
@chetantarale can you take a look at this please?

**Comment by chetantarale** [comment]
This should be working on our new build system with new dry-dock images.
@Sebastien-Meiffren Can you please give it a try and let us know if you are still running into this.

**Comment by Sebastien-Meiffren** [comment]
I will try and let you know but I need to reconfigure my project because I no longer use shippable ...
