### ISSUE TITLE
Build can't be deleted

### ISSUE THREAD

**Issue by chinthakagodawita** [Shippable/support#1957]
Hi,

We've got a triggered build that can't be cancelled regardless of what we try - https://app.shippable.com/builds/5626f2d254d5c20c0057af7c

**Comment by manishas** [comment]
We're fixing this as we speak. It will be deployed soon... Will update when it's deployed.

**Comment by manishas** [comment]
@chinthakagodawita can you try now?

**Comment by chinthakagodawita** [comment]
Thanks @manishas, deletion seems to be working now.
