### ISSUE TITLE
Changes to shippable.yml not taking effect

### ISSUE THREAD

**Issue by claar** [Shippable/support#1962]
I've updated my shippable.yml to include `npm install -g npm` to try to fix some npm issues, but this command isn't showing up. Any hints what I'm missing? https://app.shippable.com/builds/5628402fd666e20c0082733a

**Comment by avinci** [comment]
are you sure you are building the right branch? i.e. pushed the change to the shippable.yml in the right branch?

**Comment by claar** [comment]
Yes, I was on the right commit/branch -- odd, it's working fine today. Oh well.
