### ISSUE TITLE
Remove Bitbucket account request 

### ISSUE THREAD

**Issue by sydhenry** [Shippable/support#1963]
I have the same problem as this:
https://github.com/Shippable/support/issues/1918

Github id: 55578322edd7f2c052f125ed
Bitbucket id: 555e79f1edd7f2c052f81889

I would like to have the bitbucket account removed if possible so that I can have both on the same account.

Thanks

**Comment by avinci** [comment]
555e79f1edd7f2c052f81889 has been deleted.

**Comment by sydhenry** [comment]
I'm very sorry. I tested to see if it was and that just made a new account, could you remove this one:

56294b92d666e20c00c5e98c

And I will be sure to sign in with github and link this time.
