### ISSUE TITLE
Carnegie Mellon University github cmusv-fse organizational account build bottlenecks

### ISSUE THREAD

**Issue by erdogmush** [Shippable/support#1964]
Our graduate Software Engineering class at CMU Silicon Valley projects are using shippable for CI. All class repos are stored in the private github organization cmusv-fse (operating under a free academic license from github). There are currently 15 teams, so 15 active projects. It seems like, because all teams belong to this organization, shippable is allowing only one concurrent build under its free sub policy. This is causing serious bottlenecks in the class projects. Is there any way you can grant more concurrent builds to this github organization as an academic/educational institution? We expose about over 80 students each year to shippable. CMU and our ECE graduate programs are very highly ranked in the US. Our grads end up working for Silicon Valley software and high-tech companies, including all the big ones.

My github id is erdogmush, which owns the github cmusv-fse organization. I am an associate professor at CMU, teaching the course 18652, Foundations of Software Engineering.

Thanks in advance for your consideration.

**Comment by erdogmush** [comment]
BTW, my github id is erdogmush, which owns the github cmusv-fse organization. I am an associate professor at CMU, teaching the course 18652, Foundations of Software Engineering

**Comment by manishas** [comment]
@erdogmush thanks for your note and thanks for using Shippable!

We're happy to support educational institutions, so I'll get back to you in bit with a plan to increase your concurrent builds limit.

**Comment by erdogmush** [comment]
Manisha, thank you very much for the fast turnaround. We very much
appreciate that you support our educational goals.

Best - Hakan


Hakan Erdogmus, PhD
Associate Teaching Professor, Software Engineering
Department of Electrical and Computer Engineering
Carnegie Mellon University - Silicon Valley

hakan.erdogmus@sv.cmu.edu
+1 650 335 2883 (office)
+1 408 816 9863 (mobile)
NASA Research Park, Bldg 23
Moffett Field, CA, USA - 94035
http://www.cmu.edu/silicon-valley/

**Comment by avinci** [comment]
This has been added. Please let us know if you don't see this. Closing this for now.
