### ISSUE TITLE
Unable to add AWS integration 

### ISSUE THREAD

**Issue by swleighton** [Shippable/support#1970]
Reciving the following error message when attempting to add my AWS account:

{"id":1003,"message":"Missing body data :url","methodName":"caller:562d325db84b390c007a4aa6|accountIntegrations|post|_postProvider"}

**Comment by rageshkrishna** [comment]
@swleighton Thanks for reporting this. I'm looking in to this right now.

**Comment by rageshkrishna** [comment]
@swleighton This has been fixed. Can you please try again and let me know how it goes? Thanks!

**Comment by swleighton** [comment]
Fixed, thanks for the fast response and great job!
