### ISSUE TITLE
Upgrading from startup to full fledged

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1973]
Got a question: currently we have a startup plan still, which apparently comes with a 0.5GB RAM limit per container. When upgrading to a regular plan, will this start using the full 4 GB? And are there more differences between the two plans (I can't find anything about those old plans on the website)?

**Comment by manishas** [comment]
@rogierslag the UI is incorrect... I have filed a bug internally. All builds get the same size containers - 1 core, 2GB.

We've retired the old plans so they are no longer on the website. We're shortly going to introduce one more option by which you can get bigger containers... our beta for that starts next week if you're interested.

**Comment by rogierslag** [comment]
Cool, thanks for the feedback!
