### ISSUE TITLE
Python 2.7.9 setup fails

### ISSUE THREAD

**Issue by sbalko** [Shippable/support#1975]
Hi Shippable,

as of a few days ago, we are seeing issues with Shippable's Python environment. Specifically, you seem to have upgraded to Python 2.7.9, which does not work the way it should. This is what we see in the build log. Downstream, we have tests failing - I can only assume that that's because of the activate command not completing.

Can you please have a look at this?

Thanks,
Soeren

```
setup_ve

  virtualenv -p /usr/bin/python2.7.9 /home/shippable/build_ve/python/2.7.9

    The executable /usr/bin/python2.7.9 (from --python=/usr/bin/python2.7.9) does not exist

  source /home/shippable/build_ve/python/2.7.9/bin/activate

    /home/shippable/59ec6ed6-08c0-4eeb-8062-69a24a9d85c7.sh: line 89: /home/shippable/build_ve/python/2.7.9/bin/activate: No such file or directory

  python --version

    Python 2.7.3
```

**Comment by pquentin** [comment]
+1 Most of our builds fail for this reason.

**Comment by manishas** [comment]
We've just found that a recent change introduced this problem. We're working on a fix that will be available shortly.

**Comment by pquentin** [comment]
@manishas Thank you. any ETA on this?

**Comment by rageshkrishna** [comment]
Should be just a few more minutes now.

**Comment by rageshkrishna** [comment]
@pquentin @sbalko This has been fixed. Please try it out and let me know how it goes.

**Comment by pquentin** [comment]
It works, thank you!

**Comment by rageshkrishna** [comment]
Thanks for confirming, @pquentin.
