### ISSUE TITLE
Cancel subscription doesn't work

### ISSUE THREAD

**Issue by hajee** [Shippable/support#1976]
I'm trying to cancel my subcription and remove the credit card. But it doesn't seem to work.
![screen shot 2015-10-28 at 13 05 23](https://cloud.githubusercontent.com/assets/20322/10788044/161d7ff0-7d75-11e5-885a-603db0028fd3.jpg)

**Comment by DavidGDragon** [comment]
To cancel your CI subscription go to the subscription listed (hajee) and on the Billing tab set the slider to 1 and click 'Enable Free Plan'. After that you can remove your credit card.
