### ISSUE TITLE
Big number of random timeouts

### ISSUE THREAD

**Issue by pbosko** [Shippable/support#1977]
Hello,

Our builds usually take around 30 mins. Recently we are having a big number of timeouts happening. Sometimes pull request build finishes in 30 mins, then it's merge commit timeouts, then next merge commit again finishes in 30 mins.

Here is an example of regular build that finished in about 30 mins: https://app.shippable.com/builds/562f7281fc37d80d00571158

And here is a list of builds that reached timeout in last couple of days:
https://app.shippable.com/builds/562f902e310f1e0e0063d58f
https://app.shippable.com/builds/562f8f1d8a81b20c000b1cd4
https://app.shippable.com/builds/562f8ec8aed4e40d008a03a0
https://app.shippable.com/builds/562f8e84aed4e40d0089ef78
https://app.shippable.com/builds/562f8e49fc37d80d005fa861
https://app.shippable.com/builds/562f885daed4e40d00884bba
https://app.shippable.com/builds/562f6fedc6ecdf0c00617b76
https://app.shippable.com/builds/562f5ae3aed4e40d007c489d
https://app.shippable.com/builds/562f5838c6ecdf0c005b12a7
https://app.shippable.com/builds/562e386e904ba10c000c717d
https://app.shippable.com/builds/562e07a1c6ecdf0c001534d2
https://app.shippable.com/builds/5628896c8d49770f0057f05c

Can you take a look at them? We would like to be able to rely on all builds taking the same time to finish.

**Comment by manishas** [comment]
we will look into this and get back to you. Thanks for reporting this issue!

**Comment by avinci** [comment]
We have handed quite a few pieces of our code in the last 3 weeks. We have seen timeouts drop by a factor of 10x and I am hoping your issue is resolved too. Please let us know otherwise.
