### ISSUE TITLE
Shippable SQL before_script best practice for bootstrapping database

### ISSUE THREAD

**Issue by molerat619** [Shippable/support#1979]
In https://github.com/shippableSamples/sample_php_mysql they use following for the **shippable.yml** file to set up the database.

    ...
    before_script: 
       ...
       - mysql -e 'create database if not exists tododo;'
    ...

What's the best practice for setting up the database with all tables and a seed-script?

**Comment by avinci** [comment]
sorry for the delay. I would basically create a small db backup and restore it. Its probably faster that way if you have quite a bit of data. if its simple metadata then it should be relatively easy to write inset scripts to prime the DB. you could use some sort of migration package to achieve this too. Not sure if PHP has built in migrations like db:migrations in ruby
