### ISSUE TITLE
Project settings doesn't update

### ISSUE THREAD

**Issue by rmrbest** [Shippable/support#1980]
We want change an image name in pull image from field. 

The error show follow:
{"id":1004,"message":"Invalid namespace name","methodName":"|common|validateDockerImageName"}

The problem is tag name?

We need change version image in pull image from field.

Regards,
Raul.

**Comment by manishas** [comment]
@rmrbest what are you trying to change the tag to?

**Comment by rmrbest** [comment]
Yes, we update new version and we need change name tag in pull image from field, in settings.

**Comment by vidyar** [comment]
Hi @rmrbest : This error usually shows up when there is a space in between the username and image name (For ex: `username  /imagename`)  in **pull image from** field in Project settings. Can you please check and let us know if this is the problem?

**Comment by rmrbest** [comment]
Hi, no there space between username and image name. I need change it. Before, we could do it.

**Comment by kanthchandra** [comment]
Hi @rmrbest. We follow the same validation that dockerhub follows and your namespace must match the regex `/^[a-z0-9-_]+$/` in order to pass the validation.

You can send me the image name that you are trying to add to chandrakanth@shippable.com so that we can take a look and get back to you.

**Comment by rmrbest** [comment]
Hi,

I attached screenshot with error showed.

Please tell us soon.

Thanks.

Regards,
Raul.

2015-11-04 9:40 GMT+01:00 Chandrakanth <notifications@github.com>:

> Hi @rmrbest <https://github.com/rmrbest>. We follow the same validation
> that dockerhub follows and your namespace must match the regex
> /^[a-z0-9-_]+$/ in order to pass the validation.
>
> You can send me the image name that you are trying to add to
> chandrakanth@shippable.com so that we can take a look and get back to you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/1980#issuecomment-153637055>.
>



-- 
Saludos,

Raul Mesa.

**Comment by kanthchandra** [comment]
Hi @rmrbest we have opened an internal issue to track this problem. We will update this thread as soon as we have more information on this. Thanks for reporting this.

**Comment by kanthchandra** [comment]
Hi @rmrbest this has been fixed, can you please try it out and let us know? thanks!
