### ISSUE TITLE
No created job

### ISSUE THREAD

**Issue by ZuluPro** [Shippable/support#1981]
I have a `shippable.yml` with this piece of content:
```
language: python
python: 2.7
```
And no jobs are created.

I tested:
```
language: python
python:
  - 2.7
  - pypy
```
No python 2.7 job are launched.

I also tested:
```
language: python
python:
  - 2.7
```
No job are launched

**Comment by manishas** [comment]
@ZuluPro can you send me a link to the project on shippable?

**Comment by ZuluPro** [comment]
Here's my shippable.yml file:
https://github.com/ZuluPro/myblog/blob/master/shippable.yml

I also tested:
```
language: python
python:
  - "2.7"
```

**Comment by manishas** [comment]
ok, i see the issue now. Will track this down... thanks!

**Comment by ZuluPro** [comment]
Thanks a lot, for this short latency !

**Comment by rageshkrishna** [comment]
@ZuluPro Sorry for the delay on this, but we have a fix for this issue that will be deployed some time today. I will update this issue as soon as it's available.

**Comment by manishas** [comment]
This is now available....
