### ISSUE TITLE
Internal API Error: triggerNewBuild

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#1982]
When using:

    r = requests.post(
        'https://api.shippable.com/workflow/triggerBuild',
        headers={'Authorization': 'apiToken {}'.format(API_TOKEN)},
        data={'projectId': project_id}
    )

I receive:

    {
        "id":1005,
        "message":"Internal API Error: triggerNewBuild",
        "methodName":"caller:54f477fa5ab6cc1352906167|workflow|triggerBuild|_triggerNewBuild"
    }

What's going on? Thanks!

**Comment by rageshkrishna** [comment]
Hi @pquentin. I'm looking in to this now. Can you please give me the ID of a project that you are getting this error on?

**Comment by rageshkrishna** [comment]
Never mind my last comment... I think I have enough information now to dig deeper. I'll update this issue as soon as I know more.

**Comment by rageshkrishna** [comment]
@pquentin A recent change has caused an issue in our trigger build flow. At the moment, the system is unable to pick up the default branch for the project if you don't specify it in the request. We're looking in to fixing this now.

In the mean time, if you pass a branch name in the request body as `branchName` it should start working immediately.

**Comment by pquentin** [comment]
@rageshkrishna This is not the first time using the default branch is [an issue](https://github.com/Shippable/support/issues/1793). We have many projects following git-flow where we want to build develop, and many others where it's only master. I would really prefer not having to fetch this information from Bitbucket myself and can wait for the fix.

Thanks!

**Comment by pquentin** [comment]
Works since about one hour (2015-10-29 08:20 UTC). Thanks again @rageshkrishna.
