### ISSUE TITLE
Build fails while trying to install node version managar n

### ISSUE THREAD

**Issue by pawanrawal** [Shippable/support#1986]
Hi, build fails while trying to execute `sudo npm install n -g`. I am able to build this on my machine. Can't understand why this fails on shippable.

Here is a link of the build
https://app.shippable.com/builds/563711b1a0c8000d00ed2f29

**Comment by manishas** [comment]
I think you're missing some path setting that exists on your local machine but is not being set in the yml... we can dig in deeper if this doesn't help.

**Comment by rageshkrishna** [comment]
Hi @pawanrawal. We haven't been able to repro this issue in our tests. I see that your build is running on a custom image. Would it be possible for you to share your Dockerfile? You can send it to me at ragesh@shippable.com if you'd rather not share it here. Thanks!
