### ISSUE TITLE
SSH into build environment

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#1987]
To deal with issues during builds it would be very useful if one could enter the build environment via SSH. I am aware that [Circle CI offers this as feature](https://circleci.com/docs/ssh-build) and AFAIS they also use Docker for build environments. Maybe this provides some hints how it could be done.

**Comment by avinci** [comment]
Circle is using VMs upon which they run docker containers. So for every build, its a separate VM and hence on the free plan they limit you to 1500 minutes. We run a different architecture and hence can support unlimited builds on the free plan and the limitation is SSH...

We allow bring your own machines to run builds which will allow you do anything. let me know if you need more information on that...

**Comment by mbrodala** [comment]
You're right, I forgot about that option. I'll look into that, thanks.

**Comment by manishas** [comment]
@mbrodala if you want to use your own machines to run builds please let me know. We have a beta for this and we could add you to it.

**Comment by mbrodala** [comment]
@manishas Thanks but first we'd need to find suitable machines which are fast enough to handle all builds without delays. For now we'll stick with the "hosted" builds but will have a look at this again. :-)
