### ISSUE TITLE
Add Team members to Project

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#1989]
Hi,

I need to add team members to my project. Can you help me with that.

Naveen

**Comment by kanthchandra** [comment]
Hi @naveensky, We inherit the same permissions that the project has on github/bitbucket. So after you have added members to the project on github/bitbucket, the team members can login to shippable and then force sync their account in the account settings tab. The permissions will get synced and they should be able to see the project.

**Comment by naveensky** [comment]
@kanthchandra - thanks for the update. I am able to give my team access now :)
