### ISSUE TITLE
Pushing containers to selfhosted registries

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#1991]
Currently we use a docker based docker registry for internal use. However, shippable cannot push to these repositories. Meanwhile Docker Hub is sometimes especially slow when both pushing and pulling images (not only on Shippable, this is a general Hub problem).

Are there any plans to support local registries?

**Comment by rageshkrishna** [comment]
@rogierslag We do have an integration for private docker registries. You should be able to create this account integration from https://app.shippable.com/accountSettings/integrations/new and then add it to your project settings, just like you would do with Docker Hub. The complete docs are at http://docs.shippable.com/docker_registries/. Is this not working for you?

![private_registry](https://cloud.githubusercontent.com/assets/1134972/10907002/691c0452-824c-11e5-8028-bf099ff2a665.png)

**Comment by rogierslag** [comment]
For unknown reasons I completely missed this feature (and im pretty sure the docs said somewhere only docker hub and some google thing were supported)!
