### ISSUE TITLE
Unable to see project logs on dashboard

### ISSUE THREAD

**Issue by hammadalinaqvi** [Shippable/support#1992]
Hey,

I don't see any logs of the builds that are generated/executed for my projects. It has been more than a month that I am using Shippable.

For the team communication, we are using Slack and a webhook is enabled for git commits and shippable builds. Attached are the screenshots of Slack creating the builds and my shippable dashboard for the project.

![shippable](https://cloud.githubusercontent.com/assets/4103334/10907565/00f49d0c-824d-11e5-8540-caaf8facaaed.png)
![logs](https://cloud.githubusercontent.com/assets/4103334/10907564/00f2377e-824d-11e5-84c7-bbdba8d22915.PNG)

**Comment by vidyar** [comment]
Hi @hammadalinaqvi,  Can you please follow the instructions at http://docs.shippable.com/#why-cant-i-see-some-of-my-repositories-in-my-shippable-account and let us know if that helps. If that doesn't work we will take a look at this further.

**Comment by hammadalinaqvi** [comment]
It indeed helped @vidyar :+1:
Thanks a bunch!! :smile:
