### ISSUE TITLE
Can not delete project

### ISSUE THREAD

**Issue by netroby** [Shippable/support#1994]
I do not want shippable run CI for my project, but i have no permission to delete my project on shippable.

**Comment by avinci** [comment]
whats your projectId?

**Comment by netroby** [comment]
https://app.shippable.com/?redirectUrl=/subscriptions/543cc6557a7fb11eaa650180

**Comment by netroby** [comment]
Please deleted all my ip

**Comment by avinci** [comment]
I am not able to find that project or subscription. Can you send me the right information
