### ISSUE TITLE
Builds fail due to inability to download JARs from Maven Central

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#1995]
Builds are failing on multiple occasions due to failure to download JARs from Maven Central.  Some samples below:

> [ERROR] Failed to execute goal on project common: Could not resolve dependencies for project org.example:common:jar:6.3.4.0: Could not transfer artifact org.scalatest:scalatest_2.11:jar:2.2.5 from/to central (http://repo.maven.apache.org/maven2): GET request of: org/scalatest/scalatest_2.11/2.2.5/scalatest_2.11-2.2.5.jar from central failed: Connection reset -> [Help 1]

> [ERROR] Failed to execute goal on project common: Could not resolve dependencies for project org.example:common:jar:6.3.4.0: Could not transfer artifact org.scalatest:scalatest_2.11:jar:2.2.5 from/to central (http://repo.maven.apache.org/maven2): GET request of: org/scalatest/scalatest_2.11/2.2.5/scalatest_2.11-2.2.5.jar from central failed: Connection reset -> [Help 1]
> [ERROR] Failed to execute goal on project common: Could not resolve dependencies for project org.example:common:jar:6.3.4.0: Could not transfer artifact org.scala-lang:scala-library:jar:2.11.7 from/to central (http://repo.maven.apache.org/maven2): GET request of: org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar from central failed: Connection reset -> [Help 1]

Problem is occurring every few builds.  The JARs are perfectly downloadable from Maven Central.

This is annoying and misleading because simply re-running the build works most of the times (but not always).

**Comment by mgladdish** [comment]
I'm getting this, too.

I'd like just a single week where builds were stable in Shippable :(

**Comment by manish-in-java** [comment]
Builds are failing today as well with the following error:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project common: Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources failed: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven.shared:maven-filtering:jar:1.1, org.sonatype.plexus:plexus-build-api:jar:0.0.4: Could not transfer artifact org.apache.maven.shared:maven-filtering:jar:1.1 from/to central (http://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:80 [repo.maven.apache.org/23.235.39.215] failed: Connection timed out -> [Help 1]

@mgladdish is right in that not a single week passes where the builds do not fail for these senseless reasons.

Can we at least get an acknowledgement from the Shippable team that these issues are known and are being worked upon?

**Comment by avinci** [comment]
Folks...this clearly says its a maven issue. We are not able to connect to an external repo of maven. This has nothing to do with Shippable as its a build related issue. 

Please try again as now http://repo.maven.apache.org/maven2 is redirecting to http://repo1.maven.apache.org/maven2.

if this is still not working, let me flush DNS...

**Comment by avinci** [comment]
another thing you could also try is to build some robustness where you are pulling something from the internet using `shippable_retry`. This will prevent any sorts of hiccups in the system especially network problems that could make your build fail right away...

Let me know if that helps

this talks about it for nam, but can be used for anything
http://docs.shippable.com/yml_reference/#retrying-npm-install

**Comment by manish-in-java** [comment]
These same builds work from all other systems (our dev machines, our test environment, etc.) at the same time that the Shippable builds are failing.  `repo.maven.org/maven2` is the default Maven Central URL that is configured on the server, so this IS a Shippable problem.  If it was not a Shippable problem, all builds would be failing at all times, not just a few ones; and they would not succeed on reruns.

We are not doing anything special with our Maven builds so the comment `where you are pulling something from the Internet` is not relevant here.  Pulling JARs from the Internet is the way Maven (and other modern Java build systems) works.

**Comment by avinci** [comment]
I understand. We are running 1000s of builds and if its an internet problem, then every build fail. I am trying to nail down what that is. Did you get a chance to do `shippable_retry`?

**Comment by avinci** [comment]
Also, can I get your projectID?

**Comment by manish-in-java** [comment]
My project ID is 55d549851895ca44740e54d9.   Take a look at builds 78-82.  Build 78 passed and then 79 failed.  Manually retried builds 80-81 did not work.  Then, retried build 82 worked.  You will notice that builds 79-82 are against the same commit in the source repository so nothing in the source code has changed between them to warrant a difference in behaviour.

I have added `shippable_retry` to our build commands to see if it resolves the issue.  Will monitor the build for the next few days and see if the problem goes away.

**Comment by manishas** [comment]
@manish-in-java while digging deeper into this, we did discover a bug in our retry script which we have fixed. This should work more predictably for you now... let us know.

We're focusing on improving stability over the last few and next few weeks, so you will see issues like this disappear soon. Thanks!

**Comment by manishas** [comment]
@manish-in-java i am going to close this issue since the fix for shippable_retry should have fixed the problem. If you see this again, please let us know and we'll follow up.
