### ISSUE TITLE
Build stuck processing

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#1998]
5639cb51cdfca60e009dc6af

Thanks

**Comment by manishas** [comment]
Looks like the build timed out... is this happening frequently or was this a one time thing?

**Comment by tomsterritt** [comment]
@manishas I think it happened a couple of times, but it doesn't seem to have happened since

**Comment by avinci** [comment]
@tomsterritt we have the entire org working on hardening this part of the code and make it more resilient. We have seen timeouts drop by a factor of 10x. I hope your issue is resolved and if now please let us know.
