### ISSUE TITLE
Can't cancel a build using the rest api.

### ISSUE THREAD

**Issue by HelainSchoonjans** [Shippable/support#1999]
I've successfully used the Shippable API to trigger builds and get project information using using curl queries. I couldn't however cancel any incomplete build using rest requests:
`curl -H "Authorization: apiToken $myToken"      -H                                                                                                                                   "Content-Type: application/json"      -d "{\"BuildId\": \"$buildId"}"      https://api.shippable.com/workflow/cancelBuild`
indeed results in an "Invalid Request" response. Wondering if I was using a wrong id, I also tried with a made up buildId  but got the same response.

Wondering if there might be an error in the Shippable API documentation, I tried to use "buildId" as key in the json (most keys in the API indeed begin with a lowercase):
`curl -H "Authorization: apiToken $myToken"      -H                                                                                                                                   "Content-Type: application/json"      -d "{\"buildId\": \"$buildId\"}"      https://api.shippable.com/workflow/cancelBuild`
Getting this time the message "The requested resource was not found".

I tried again with a made up id:
`curl -H "Authorization: apiToken $myToken"      -H                                                                                                                                   "Content-Type: application/json"      -d "{\"buildId\": \"$madeUpId\"}"      https://api.shippable.com/workflow/cancelBuild`
Getting a "Internal Server Error"

From these requests, it seems that the right parameter name in the query should be "buildId" instead of "BuildId", since it only reacts differently to the made up ids in previous case proving that some kind of id validation is happening.

I don't however understand why I'm getting "The requested resource was not found" message. I can get this processing build information with the other methods of the API without problems. Is there something wrong with my query or is it a bug in Shippable?

**Comment by pranaypareek** [comment]
@HelainSchoonjans We have opened up an internal issue and will keep you updated as we make progress. Thanks for reaching out!

**Comment by rageshkrishna** [comment]
@HelainSchoonjans It looks like you're doing a GET, but this call needs to be a POST. This should work:

````
curl -X POST 'https://api.shippable.com/workflow/cancelBuild' \
 -H "Content-Type: application/json" \
 -H "Authorization: apiToken $token" \
 -d "{\"buildId\" : \"$buildId\"}"
````

**Comment by HelainSchoonjans** [comment]
According to the curl docs, the -d option does make the query a POST one. I however did try to add the method explicitly as in your example:
After adding -X POST to my request, I still gets the same responses, either "The requested resource was not found" or "Invalid request" or "Internal server error" when making similar queries as the ones in my first post - plus the "-X POST".

**Comment by rageshkrishna** [comment]
@HelainSchoonjans I'm still unable to reproduce this issue. Can you share the build ID you're using? You can send it to me at ragesh@shippable.com if you'd rather not add it here. Thanks.

**Comment by HelainSchoonjans** [comment]
Done @rageshkrishna.

**Comment by HelainSchoonjans** [comment]
Okay, seems I obtained the id of the build using GET /project/{projectId}/searchBuilds then looked in the json[0]["builds"][0]["id"] while the id that works is uin fact at position json[0]["id"] (this assumes that there is only one build running for this project).

I'm not sure to understand the difference between both "buildIds"...
