### ISSUE TITLE
Build badges

### ISSUE THREAD

**Issue by mplewis** [Shippable/support#20]
Are there plans to implement build badges in Shippable?

P.S. Tried to add a "Feature Request" label but can't. Might be my fault but I can't see a way to edit labels.

**Comment by bittner** [comment]
1) Just for clarification (I searched quite some time for the badge), it's not on the [Dashboard](https://app.shippable.com), it's on the *project* dashboard in the right-hand panel on top.

It says "project's page" correctly in the [documentation](http://docs.shippable.com/en/latest/config.html#build-badge), just @rageshkrishna's comment above suggested it could (also) be on the main dashboard.

2) Do you plan to integrate with [shields.io](http://shields.io/) as suggested above by @thedrow? Adapting their URL scheme would be nice. I've also added a related comment to this in issue #182.

**Comment by dunnock** [comment]
I see it was integrated with shields.io, guys badge is there! just no update in this thread.

**Comment by bittner** [comment]
The crazy thing is: With the new, improved UI I can't find the place where to get the badge from anymore. (Sorry for the sarcasm!)

Where is it? Has the badge feature been removed from the UI? It's not on the project dashboard anymore.

**Comment by dunnock** [comment]
I have found it on shields website, it is all clear there: http://shields.io/

**Comment by stevenschwenke** [comment]
Sorry - searched for it for the last 20 minutes. Could you please specify where I can get the badges? A screenshot in the documentation would be awesome. Thanks!

**Comment by manishas** [comment]
Sorry we need to update docs.

This issue shows you how to include a badge - https://github.com/Shippable/support/issues/1580

We'll update the docs asap...

**Comment by stevenschwenke** [comment]
Thanks for this link, now it's fairly simple: Just use an existing link and copy your own project ID into it.

**Comment by rogierslag** [comment]
The shields.io badges seem to have stopped working though for private projects. Probably since the API does no longer return the response. However we prefered those icons, since theu fit into the flow, and generally look better.

refs https://github.com/badges/shields/issues/355
