### ISSUE TITLE
GitHub Collaborator can't see build

### ISSUE THREAD

**Issue by jamescgibson** [Shippable/support#2000]
My github collaborators can't see my builds. They're in my org, on the repo, and have every permission I can grant them on GitHub.

I tried forcing a sync through the Shippable web interface. 

Advice?

**Comment by kanthchandra** [comment]
Hi @jamescgibson, Can you please try the suggestions given at http://docs.shippable.com/#why-cant-i-see-some-of-my-repositories-in-my-shippable-account and see if any of those work?

I'm guessing that it's a private project and the collaborators haven't enabled private scopes on their account and as a result they are not able to see the projects on Shippable. If this is the case then enabling private scopes and force syncing the collaborator's account should sync all the permissions. 

If none of the above suggestions work, we will take a deeper look at this, thanks.

**Comment by jamescgibson** [comment]
This worked, thanks!
