### ISSUE TITLE
test all pushes, but only build and push to hub for tagged releases

### ISSUE THREAD

**Issue by nlf** [Shippable/support#2001]
how we prefer to work is by pushing code to master and keeping that branch tested and up to date, which works perfectly in shippable.

however, where we differ somewhat is we don't want to necessarily build and push a docker container for every push. we use semantic versioning and tag our releases in git when we want a build to run. is there any support for that in shippable?

bonus points if we can make the tag in the docker image match the tag in git.

**Comment by avinci** [comment]
Just want to make sure I understand the tag you are referring to. Are you referring to release tags? 

@nlf, let answer the bonus point q first. today we push the commitSHA as a tag. I think we can push tags too. It should super simple. 

Now coming the main Q. I want to make sure I understand your workflow. Do you run CI first and upon it passing, you push a tag again to the same commit? I am not sure if we get a web hook commit for tags. But we could actually make this only run docker push only upon tag commit. Would that work?

**Comment by nlf** [comment]
correct. we test a release, then tag it in git and push the tag and we want the docker push to *only* happen for a git tag

**Comment by avinci** [comment]
We will pick this feature up the moment we finish this sprint.

**Comment by chrisrhoden** [comment]
:+1: would love to see this supported

**Comment by cavis** [comment]
To support something like a Github flow, it would also be nice to also build the `master` branch in addition to any tags/releases.  That would allow continuously acceptance testing the bleeding-edge `master` in a test Formation, plus deploying tags/releases to a production Formation in less frequent intervals.

**Comment by manishas** [comment]
consolidating all requests for tags in #1362

**Comment by manishas** [comment]
@nif We have added a project setting so that you can configure whether your project should be built when you push a tag or create a release. 

![image](https://cloud.githubusercontent.com/assets/2983749/15169977/12e71c90-16f6-11e6-855a-e109b5391dc4.png)

This setting only works for GitHub projects as of now.
