### ISSUE TITLE
can't create an aws formation

### ISSUE THREAD

**Issue by drankinn** [Shippable/support#2002]
I'm getting the following error when creating a formation for aws:
{"id":1004,"message":"Adapter call failed for getClusterByName","methodName":"getClusterByName|_getClusterByName","link":{"message":"Missing region in config","code":"ConfigError","time":"2015-11-04T21:12:19.782Z"}}

here's the screenshot: 
![selection_019](https://cloud.githubusercontent.com/assets/1199706/10952105/53674fc4-82fe-11e5-9739-66657f07f58c.png)

**Comment by manishas** [comment]
looking into this.... will update soon.

**Comment by trriplejay** [comment]
@drankinn we're working on the fix for this, targeting end of day, but i'll update the issue to let you know the status.

**Comment by drankinn** [comment]
Nice response time.  Thanks for looking into this

**Comment by trriplejay** [comment]
hi @drankinn, We made some changes to this workflow.  Now you should be able to successfully create a formation using our plan called 'cs-deploy'.  Once created, you will be able to link it to your aws integration.

**Comment by manishas** [comment]
@drankinn can you try this out again and let us know if it works?

**Comment by drankinn** [comment]
I have tried it since the change, and it works as expected.
