### ISSUE TITLE
Builds are getting stuck

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#2003]
Hi,

My builds are getting stuck as I am getting "[error] File name too long" error. The same build was working good for the same project few days back. The build commands runs successfully on my local machine.

For reference the build is https://app.shippable.com/builds/563b60d8f2dc3d0c0074eded

Guide me how to resolve this

Naveen

**Comment by avinci** [comment]
the problem is the path on this one. We add a few folders to clone the repo and thats causing the file name issue. Let me look into what we can do with this. This is typically happens with scala and maven like projects. 

is there something that has very deep folder structure in your repo?

**Comment by naveensky** [comment]
@avinci - nothing which I could tell. Strange thing is that same build was working fine 2-3 days back

**Comment by naveensky** [comment]
@avinci - Any update on this ? Is there a temporary workaround which I can use for now?

**Comment by rageshkrishna** [comment]
@naveensky This is how we set the workspace folder today:

````
export SHIPPABLE_REPO_DIR="$HOME/workspace/src/bitbucket.org/$REPO_NAME";
````

You _might_ be able to temporarily get around this issue by adding an env to your YML file to override it with something like this:

````
env:
 - SHIPPABLE_REPO_DIR=$HOME/src";
````

I hope this helps.

**Comment by rageshkrishna** [comment]
(edited a couple of typos in the previous comment)

**Comment by naveensky** [comment]
@rageshkrishna - Do we have encrypted file system on build images ? Is there a way to make them unencrypted. It seems that can resolve the issue,  More info at https://github.com/scala/pickling/issues/10

**Comment by rageshkrishna** [comment]
@naveensky No, our Scala images are built straight from ubuntu:[12|14].04 and we don't configure any encryption. Did setting `SHIPPABLE_REPO_DIR` to a shorter path not help?

**Comment by naveensky** [comment]
@rageshkrishna, adding the SHIPPABLE_REPO_DIR variable had no effect on folder structure. I solved the issue by adding following clause to my build.sbt

`scalacOptions ++= Seq("-Xmax-classfile-name", "100")`

This resolved the issue with filename path. I am closing this task for now, unless I face any further issue
