### ISSUE TITLE
"last successful build" API alias

### ISSUE THREAD

**Issue by n0mer** [Shippable/support#2006]
Hi,

is there any way to get fixed URL to download artifacts from last successful build?

It is sort of a hassle to pass build_id here and there, so - what is the "official" way to download artefacts from last successful build of a given project? 

This feature exists in Jenkins, by the way: https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API

>  if you want to access information about a particular build, e.g. http://ci.jruby.org/job/jruby-base/lastSuccessfulBuild/, then go to http://ci.jruby.org/job/jruby-base/lastSuccessfulBuild/api/ and you'll see the list of functionalities for that build.

Thanks.

**Comment by DavidGDragon** [comment]
In the new build system, build artifacts are now set up by the user. See more information about build artifacts here http://docs.shippable.com/ci_configure/#build-artifacts

**Comment by manishas** [comment]
I am closing this issue since artifact handling has changed in the new build system.
