### ISSUE TITLE
Unable to find precise build start time

### ISSUE THREAD

**Issue by pkaminski** [Shippable/support#2007]
I want to correlate my deployments with some production issues and can't seem to find the exact time that a build was started.  It just says "10 days ago" or "10/28/2015" in the UI even though the data is clearly there (looking directly at the Angular scope).  Could you please display the day and time that a build started and make the time zone clear?  Thanks.

**Comment by avinci** [comment]
@DavidGDragon while we implement the new build page, we should add this option

**Comment by avinci** [comment]
this has been implemented and pushed to prod
