### ISSUE TITLE
"Pull Image from" container image does not get updated

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2008]
We're using a custom container image for consistency between Shippable and production. Since about two days, we get:

    echo "image gcr.io/[snip]/shippable-ubuntu-1504:latest exists, skipping pull"

Resetting the minion does not help. This was already happening at the end of last week, as reported by [n0mer](https://github.com/Shippable/support/issues/1461#issuecomment-154704304). This is really bad as those are the images that end up in production. Shippable really needs to get this right.

**Comment by manishas** [comment]
@pquentin thanks for pointing this out. We'll look into this... completely agree that custom images should be pulled every time.

**Comment by manishas** [comment]
I've raised a high priority issue on this internally and we'll provide an update soon.

**Comment by rageshkrishna** [comment]
@pquentin This has been fixed. Please give it another shot and let me know how it goes.

**Comment by pquentin** [comment]
Yes, it works. Thank you for the quick fix!
