### ISSUE TITLE
Unable to download build result

### ISSUE THREAD

**Issue by gzsombor** [Shippable/support#2009]
Hi,

 I've tried to setup a simple maven build, but I couldn't find a way to configure what will be the result artifacts of the build, which at the end, I can download. When I specified only the bare minimal:

    language: java
    
    jdk: 
        - oraclejdk8
    
    script:
        - mvn -DskipTests package

Nothing showed up in the UI. From the generated script, I've noticed, that the system treats specially the stuff which ends up in shippable/buildoutput, so I've tried to add 'cp $SHIPPABLE_REPO_DIR/target/*.war $SHIPPABLE_REPO_DIR/shippable/buildoutput/' to the script, but it didn't helped. Is it possible at all to do it?

Any help would be appreciated, 
 Thanks

**Comment by rageshkrishna** [comment]
Hi @gzsombor. You just need to add this to your YML to get downloadable archives:

````
archive: true
````

Quoting from http://docs.shippable.com/build_case2/

> All files in the ./shippable folder at the root of the project are automatically archived for each run upon completion. You can download a tarball of your build's artifacts by clicking on the download archive button on the build page.

I hope this helps.

**Comment by gzsombor** [comment]
thanks, I will try it!

**Comment by manishas** [comment]
closing this issue. please let us know if this didn't work.
