### ISSUE TITLE
Builds unstable

### ISSUE THREAD

**Issue by LuisMuniz** [Shippable/support#2011]
Hi,

I am struggling to get a stable build running on your servers.
The nature of some of my tests is asynchronous, so I need to build in some pauses to wait for the backend to perform its work. This works fine on a reasonably powerful server. I have built in generous pauses (20s, 30s) to give the server time to catch up, and sometimes the tests pass, but sometimes they don't. Now it is getting worse. When I look at the logs on the user interface and follow the build, I sometimes get wait times of more than a minute, in a place where no tests are run! I have a plan for 4 minions, but that is useless to me in this instance, because this needs to run in a single instance. I would gladly exchange a couple of minions for more memory, or a faster server.

**Comment by manishas** [comment]
@LuisMuniz we'll look into this and follow up with some options very soon.

**Comment by rageshkrishna** [comment]
@LuisMuniz Can you give me the ID of the project where you're seeing these issues? Thanks.

**Comment by LuisMuniz** [comment]
Hi Ragesh,

55cdad20edd7f2c052a81e96


Regards,

Luis

Luis Muñiz
IT Director – Research and Development, Architecture | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | M : +34 647 79 34 76
luis.muniz@b2boost.com<mailto:luis.muniz@b2boost.com> | www.b2boost.com<http://www.b2boost.com/>

Please consider the environment before printing.


From: Ragesh Krishna
Reply-To: Shippable/support
Date: Monday 9 November 2015 at 12:40
To: Shippable/support
Cc: Luis Muniz
Subject: Re: [support] Builds unstable (#2011)


@LuisMuniz<https://github.com/LuisMuniz> Can you give me the ID of the project where you're seeing these issues? Thanks.

**Comment by rageshkrishna** [comment]
Thanks, @LuisMuniz. I'm looking in to this.

I haven't confirmed what the problem is yet, but it looks like your YML file requests the elasticsearch service (you can see it starting up in the "start services" section of the build output), but your before_script also tries to launch an instance of elasticsearch. I'm not sure right now if that's an issue but thought I'd just put it out here as it seems unnecessary to do both.

**Comment by LuisMuniz** [comment]
I think that I have read in the documentation the elasticsearch is not started automatically, even if you declafre it in the services. I can't find the place I have read that now, though.

**Comment by LuisMuniz** [comment]
OK, I got confused by this article. Starting it up manually only is necessary when you need your own config file.

http://blog.shippable.com/custom-elasticsearch-configs-and-shippable

However I doubt this is the core issue.

**Comment by LuisMuniz** [comment]
I have removed the command to launch elasticsearch, and the sporadic failures still occur of course.

**Comment by LuisMuniz** [comment]
Any progress?

**Comment by rageshkrishna** [comment]
@LuisMuniz Sorry about the delay on this. It appears that this is indeed a case of needing a fast processor or more RAM. We are making some improvements to resource utilization on our multi-tenant hosts that should make this a little better, but we are also running a beta for single-tenant CI where you can get dedicated processing and RAM just for your subscriptions. Is this something you'd be interested in trying out?

**Comment by LuisMuniz** [comment]
Hi Ragesh,

I would indeed be interested in trying out your beta program.

Is there an additional cost involved?

Thanks.

Luis

Luis Muñiz
IT Director – Research and Development, Architecture | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | M : +34 647 79 34 76
luis.muniz@b2boost.com<mailto:luis.muniz@b2boost.com> | www.b2boost.com<http://www.b2boost.com/>

Please consider the environment before printing.


From: Ragesh Krishna
Reply-To: Shippable/support
Date: Tuesday 17 November 2015 at 12:18
To: Shippable/support
Cc: Luis Muniz
Subject: Re: [support] Builds unstable (#2011)


@LuisMuniz<https://github.com/LuisMuniz> Sorry about the delay on this. It appears that this is indeed a case of needing a fast processor or more RAM. We are making some improvements to resource utilization on our multi-tenant hosts that should make this a little better, but we are also running a beta for single-tenant CI where you can get dedicated processing and RAM just for your subscriptions. Is this something you'd be interested in trying out?

**Comment by ttrahan** [comment]
@LuisMuniz : 

Hi Luis,

I'm jumping in here, as I'm running the beta program for our single-tenant CI option. There's no additional Shippable charge for the single tenant option while we're in beta, though you will cover the cost of the single tenant machines, which you can size to any specification you need. I will send you an email detailing this further and schedule a quick call to discuss the right setup for you.

Thanks,
Tom

Tom Trahan / VP, Business Development
m 425.999.9781
1932 1st Ave, Ste 420, Seattle, WA 98101
tom@shippable.com
http://www.shippable.com
