### ISSUE TITLE
My GHE enterprise projects are missing

### ISSUE THREAD

**Issue by pezra** [Shippable/support#2012]
I added a GHE integration (apparently successfully) but none of the projects on that github show up on my subscriptions dashboard. My GHE username is also missing from the "CI" drop down on the landing page. Did i miss a step in setting up my integration?

**Comment by manishas** [comment]
@pezra can you go to account settings and Force Sync your account? You should see the subs in your CI drop down after that. 

However you will need a couple of more steps to get completely set up. We're in the process of documenting this. In the meantime if you send me an email at manisha@shippable.com I can share some instructions and also we can set up a quick on boarding meeting.

**Comment by pezra** [comment]
The api seems to work ok from the public internet.
```
$ curl -H "Authorization: token $ghe_token" https://github.comverge.com/api/v3/users/pwilliams
{
  "login": "pwilliams",
  "id": 77,
  "avatar_url": "https://github.comverge.com/avatars/u/77?",
  "gravatar_id": "",
  "url": "https://github.comverge.com/api/v3/users/pwilliams",
  "html_url": "https://github.comverge.com/pwilliams",
  "followers_url": "https://github.comverge.com/api/v3/users/pwilliams/followers",
  "following_url": "https://github.comverge.com/api/v3/users/pwilliams/following{/other_user}",
  "gists_url": "https://github.comverge.com/api/v3/users/pwilliams/gists{/gist_id}",
  "starred_url": "https://github.comverge.com/api/v3/users/pwilliams/starred{/owner}{/repo}",
  "subscriptions_url": "https://github.comverge.com/api/v3/users/pwilliams/subscriptions",
  "organizations_url": "https://github.comverge.com/api/v3/users/pwilliams/orgs",
  "repos_url": "https://github.comverge.com/api/v3/users/pwilliams/repos",
  "events_url": "https://github.comverge.com/api/v3/users/pwilliams/events{/privacy}",
  "received_events_url": "https://github.comverge.com/api/v3/users/pwilliams/received_events",
  "type": "User",
  "site_admin": false,
  "public_repos": 0,
  "public_gists": 8,
  "followers": 0,
  "following": 2,
  "created_at": "2013-10-03T21:38:01Z",
  "updated_at": "2015-11-05T05:31:26Z",
  "suspended_at": null,
  "private_gists": 4,
  "total_private_repos": 6,
  "owned_private_repos": 0,
  "disk_usage": 0,
  "collaborators": 0
}
```

**Comment by rageshkrishna** [comment]
@pezra This should be working now.

The underlying issue turned out to be quite simple. At one point in our repository sync code, we were looking for "github.com" in the URL to figure out if we're talking to GitHub or a GitHub Enterprise server. Of course, this triggered a false negative for your server because it also happens to have the term "github.com" in it, but just at the wrong place :)

We've made this check much more reliable now and there shouldn't be any issues. Please force sync your account once again and let me know if you still don't see your repositories.

**Comment by pezra** [comment]
I am able to see my GHE subscriptions now. Thanks.
