### ISSUE TITLE
Cannot connect to mongodb

### ISSUE THREAD

**Issue by copyhawk** [Shippable/support#2014]
I have been stuck on this issue for a while and I do not know what I'm doing wrong. Also, I have not found any related issues. I'm trying a nodejs build and using one of your pre-build images, but mongodb does not seem to startup correctly no matter what I try. Could you please give me any pointers?

build_image: shippableimages/ubuntu1204_nodejs

before_install:
  - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
  - node --version
  - apt-get install -y memcached mongodb
  - memcached -u root &
  - mongod &

install:
  - npm install -g npm@next --loglevel silent
  - npm install
  - npm ls

**Comment by avinci** [comment]
@copyhawk the problem with mongo install is that it does not by default expose the port on which its running. So what you need to do is run this command

`sudo sed -i 's/#port = 27017/port = 27017/' /etc/mongod.conf` and this should allow you to connect.  let me know if this works

**Comment by copyhawk** [comment]
Thanks but I actually got it to connect by doing the following (before starting mongo):

- mkdir -p /data/db/

Now I'm having other issues, and will post as they evolve and I need help.

**Comment by copyhawk** [comment]
I keep getting:

npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "node" "/root/.nvm/versions/v0.12.7/bin/npm" "install" "-g" "npm@next" "--loglevel" "error"
npm ERR! node v0.12.7
npm ERR! npm  v3.4.0
npm ERR! path /root/.nvm/versions/v0.12.7/lib/node_modules/npm
npm ERR! code EXDEV
npm ERR! errno -18

npm ERR! EXDEV, rename '/root/.nvm/versions/v0.12.7/lib/node_modules/npm'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     

npm ERR! Please include the following file with any support request:
npm ERR!     /root/workspace/src/bitbucket.org/jonatanalava/scripter-core/npm-debug.log

No idea why.

**Comment by avinci** [comment]
can you try `build_image: drydock/u14nod` This is the latest version of node image and we will be launching it soon. It should solve your problem, if not let me know

**Comment by avinci** [comment]
sorry try `build_image: drydock/u14nod:prod`

**Comment by copyhawk** [comment]
Will try that. should all other steps remain the same?

**Comment by avinci** [comment]
yup, its the same.

**Comment by copyhawk** [comment]
will try it and let you know of the outcome

**Comment by copyhawk** [comment]
have been unable to run any builds. the process seems frozen, even after cancelling and restarting multiple times

**Comment by copyhawk** [comment]
using the new image I'm back to not being able to connect to mongo

**Comment by avinci** [comment]
can you share your projectId and your yml?

**Comment by copyhawk** [comment]
id: 56417a3a2ce77e0c00085429

# Language setting
language: node_js

# Version number
node_js:
  - 0.12.7

# Cache environment
cache: true

env:
  global:
    - XUNIT_FILE=shippable/testresults/xunit.xml MongoConnectionStringTests=mongodb://127.0.0.1:27017/test MemcachedLocationTest=localhost:11211 LogLevel=error
    - secure: GVfbYWQ6H65vvkehkZLnfwKrFpmFBumlseB1/ZeiCbUjTk2oWrxrw81ZFF0c2G6D0WShLvyK+I9b5OyO32Ln8c34fOD93Vo/DXEtWa74mGezTCuO3hCO2MwDbRldji03qcK/5E4yqwcz5IGIFU6m0Pa5ydvy1vvvQHwfGGEL5A7xF7TQSCw2IcmMVWT+ddBtTUssTr+2RJgpDpiaKbEIFfA14wFI8wl2geIObeHoOZlNBo405v4n/Sw8JLMQWOtkzY9cIKgIIJkbp1upZDvZvf1mnpLpi/vpIIE4eNmdktp3yBgJY9/tKITXzp8sRxGRc3ZdoWwhj2mzhypbK8P7T3Ac7O9hpXwXYmhSxXOj1voK6flJ/YUby2nT+nqtBEgNPmsbVLe7Wsugw/eXxiPpBL4Bmdmp3DbdcL2RMzFkmnEv45UjRIWs+FWRC2rPrwewALln8z0IOVcuryAuEqS0Itek6g4gvDZ5hgyjPo5A6IinqTwJhWHStzkUGqN0DHyOwRSK1yHl7qpAsIKZtMCxw9LMHmeS+6XsDHPmJF8FfC6UyL+OR8R5EDcKM6aMFETz6C7FoRc6AUA5CZ3pyu+zYlshDBUofzj4BMIfIP35OjPM8dvKwKR75N39AwyaInc8I+J8YvL1Qqm0opE1p79qrsrfGo22V1o4//D15VpsjSE=

build_image: drydock/u14nod:prod

before_install:
  - mkdir -p /data/db/
  - source ~/.nvm/nvm.sh && nvm install $SHIPPABLE_NODE_VERSION
  - apt-get install -y memcached mongodb
  - memcached -u root &
  - mongod &
  - sudo sed -i 's/#port = 27017/port = 27017/' /etc/mongod.conf

install:
  - npm install

before_script:
  - mkdir -p shippable/testresults

# Running the tests with grunt
script:
  - npm run-script ci

# Should generate a coverage report
after_script:
  - mongo test --eval "db.dropDatabase()"

**Comment by copyhawk** [comment]
I got build 92 to work, but shippable still shows it as failed. There are no failures in any of the steps.

**Comment by copyhawk** [comment]
build 93 failed and build 94 worked. I never seem to get consistent results

**Comment by avinci** [comment]
here is my script to install as well as a green build. The main problem is amount of storage the container has which causes mongo not to start. I used --smallfiles option and it seems to work consistently. I will check on how to increase the base container storage so that mongo is going to be fine tomorrow morning as its late and my team is not around. 

In the meantime here is where I got to...Let me know if this works

My build (its public and you should be able to access it)
https://app.shippable.com/builds/5641892d2ce77e0c0009b32a

Source code
https://github.com/avinci/sample_node

Hope this helps

**Comment by copyhawk** [comment]
Tried it and seems to be working fine. I will let you know how consistent it is.

**Comment by copyhawk** [comment]
Again, facing an issue of consistency. Builds work around 60% of the time, the rest mongo fails to start up. Is there any way to use your mongo service on a docker image?

**Comment by avinci** [comment]
Yup, we will be making our image public in next 2 weeks. Its not been fully tested and hence I am worried about launching it. 

if its failing during npm install, one thing you can do is this. add `shippable_retry` in front of the command. This reduces the flakiness if downloading things from the internet. 

Does it fail at the exact same place or its random?

**Comment by copyhawk** [comment]
I'll be adding shippable_retry, but it fails in random places, mostly around mongo install or start. Also, I have now added test coverage, but it's parsing the report to 100% coverage even though when I run it offline it is not close to 100%

**Comment by copyhawk** [comment]
now I'm getting a "failed" result, even though the tests were successful. Coverage is still not working as expected.

**Comment by copyhawk** [comment]
Have you been able to see my builds? I'm still getting successful test runs, but ultimately the build status shows as failure.

**Comment by avinci** [comment]
yes. We found the problem. We will be fixing by EOD. Please stay tuned and thanks for helping us find this problem

**Comment by copyhawk** [comment]
Any feedback on this?

**Comment by ric03uec** [comment]
@copyhawk can you try running the builds again and let me know if it works this time. 
thanks

**Comment by copyhawk** [comment]
Will do

**Comment by copyhawk** [comment]
ran and got the exact same results. All tests pass, coverage shows an erroneous 100% and the end result is a failure

**Comment by copyhawk** [comment]
@ric03uec any updates on this bug?

**Comment by ric03uec** [comment]
@copyhawk sorry for delayed response. there was a bug in the scripts that cache the container which was probably causing this issue. we've just deployed the patch to production. can you please try the build again and let me know if it works.
Also, can we trigger a build on your project if further debugging is required?

**Comment by copyhawk** [comment]
I'll try it again now, and yes you can trigger a build to troubleshoot if required.

**Comment by copyhawk** [comment]
I ran it multiple times, got one failure instantiating mongodb, other than that it seems to be working now in terms to reporting successful builds.
One problem that remains is the coverage report, which still displays 100% coverage without displaying any other details.

**Comment by avinci** [comment]
We are hardening report parsing piece in the next couple of weeks. I will look into this, but since this is being re-worked, we might not fix the old code. I hope that works. 

Thanks once again for helping us find these issues and I am very happy that our refactored code is working better for you.

**Comment by avinci** [comment]
the original issue has been resolved. hence closing this.
