### ISSUE TITLE
Stop buffering in the console

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2018]
The build console in the UI buffers the script output. This is one of the major issues that prevent us to be more effective with Shippable: when something is not printed, we cannot assume it did not happen, we also have to assume that the UI just did not print it. (It was even worse when we weren't aware of the issue.)

I've created a [sample repo](https://github.com/pquentin/shippable-bugs) and test it on a free account to help everyone see the issue more directly. After installing pytest, you can run `py.test --verbose` to see:

```
test_sleep.py::test_sleep[1] PASSED
test_sleep.py::test_sleep[2] PASSED
test_sleep.py::test_sleep[3] PASSED
...
test_sleep.py::test_sleep[37] PASSED
test_sleep.py::test_sleep[38] PASSED
test_sleep.py::test_sleep[39] PASSED
test_sleep.py::test_sleep[40]
```

Notice that the last line sleeps longer than the Shippable timeout: I expect to see "test_sleep.py::test_sleep[40]" even if there was no \n yet. But [I do not even see "test_sleep.py::test_sleep[39] PASSED"](https://app.shippable.com/builds/5641b80ddbd2270c00b873b3)! Even worse, [I don't see 39 or 40 even after canceling the build](https://app.shippable.com/builds/5641b7583fedf70c00c8a6eb)!

For what it's worth, Travis does this correctly, even displays progress bars, and does it fast (I could not believe how fast it was the first time I saw it after months of using Shippable.)

**Comment by manishas** [comment]
@DavidGDragon can you look into this?

**Comment by manishas** [comment]
@pquentin Thanks for the feedback! You're right, we do buffer in the console to some degree. 

Our plan is to change this in the next couple of weeks since we're making some changes to the platform that will help us address this problem. I'll update you when we make the change.

**Comment by pquentin** [comment]
@manishas Thank you - I'm glad to see that there are plans to improve this.

**Comment by manishas** [comment]
@pquentin we have redone our console with a buffering logic of 10 lines or 30 seconds, whichever happens first. Hope that works for you. Thanks!
