### ISSUE TITLE
Deploying on Github Tag

### ISSUE THREAD

**Issue by leroyjware** [Shippable/support#2019]
When we used TravisCI, we were able to use "on: tags: true" to deploy Github tagged commits to prod. The builds were triggered automatically when we tagged the commits on Github. Is this something we can do with Shippable?

**Comment by leroyjware** [comment]
We're moving back to Travis for now. The Docker support (for deploying to EC2 Container service) as well as the front-end support for deploying on tag are both there with Travis, and we don't have much more time to experiment.

I appreciate everything.

**Comment by abhijitkini** [comment]
I would like to announce that we have added the feature of triggering a build based on git tag push & git release events (in addition to pull requests & commits). Read more about configuring these settings in [our documentation](http://docs.shippable.com/ci_projects/#configure-webhook-events-for-triggering-builds).

**Comment by tjomk** [comment]
@abhijitkini this is only for GitHub :(

**Comment by mbrodala** [comment]
@abhijitkini That page is empty. :-)

**Comment by Asgoret** [comment]
@abhijitkini your link doesn't work
![image](https://user-images.githubusercontent.com/30697011/56278825-a27cc380-610f-11e9-9d12-c84964bb11cf.png)
