### ISSUE TITLE
Do not build docker container for Post CI workflow for PR builds

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2020]
Shippable currently does not push to Docker Hub for pull request builds.

In this scenario, if post-CI Docker build is configured, we shouldn't build the Docker container at all since we're not going to push it. 

Post CI Dockerbuild should only happen for commit builds.

**Comment by avinci** [comment]
@ric03uec we should absolutely do this...this is a miss on our side.

**Comment by fabiocarneiro** [comment]
Please, high priority on this. I have PR builds taking 30 minutes+ just because of container builds that are 
useless. This is impacting productivity.

**Comment by avinci** [comment]
@fabiocarneiro i just coded, tested and deployed this to production. We will not be doing POST Dockerbuild for a PR build anymore. Please let me know if you face any issues
