### ISSUE TITLE
Support multiple tags for Docker Push

### ISSUE THREAD

**Issue by avinci** [Shippable/support#2022]
We should have the ability to push multiple tags. Currently we only support 1 or the other of the following
* branch + build number 
* commitSHA
* custom

Users need to be able to specify any combinations or the above along with an array of custom tags too. We also need to have a way to push tags from git also as an option

**Comment by avinci** [comment]
linking https://github.com/Shippable/support/issues/824

**Comment by hshira** [comment]
Avi, thanks for creating a new issue. Do you know when you are you planning to implement this feature?

**Comment by koryonik** [comment]
:+1: thanks

**Comment by avinci** [comment]
this feature has been implemented and verified in pre-prod. Will be shipping on Feb 29

**Comment by luckyraul** [comment]
@avinci  Any updates?

**Comment by avinci** [comment]
This was just launched a minute ago. We have completely revamped the product and you should be able to do everything and anything in the YML.

http://docs.shippable.com/ci_docker/#docker-commands-in-yml

We are going to start migrating users to the new plan `Continuous Delivery` but you can go to the subscription and do it yourself too if you don't want to wait for us to move you in the background.

More here...
http://docs.shippable.com/ci_docker/#docker-commands-in-yml

**Comment by manishas** [comment]
Also docs.shippable.com/ci_configure

**Comment by luckyraul** [comment]
Can I use matrix for multiple builds with multiple tags?

**Comment by avinci** [comment]
yes. you can do whatever you want :-)

**Comment by luckyraul** [comment]
An example, please, with matrix for image:tags

**Comment by manishas** [comment]
Can you explain your scenario and I'll send you the yml config.

**Comment by luckyraul** [comment]
docker build --build-arg VAR='xxx'

**Comment by manishas** [comment]
your yml looks good. Closing this issue.
