### ISSUE TITLE
Existing credit card not recognized as used in any subscriptions 

### ISSUE THREAD

**Issue by ttrahan** [Shippable/support#2024]
Existing credit card not recognized as used in any subscriptions, however, it is used in several CI subscriptions (see https://app.shippable.com/subscriptions/54934d03d46935d5fbc099ed)

![image](https://cloud.githubusercontent.com/assets/4467650/11133644/d373ed46-894b-11e5-8873-d37187df86e6.png)

![image](https://cloud.githubusercontent.com/assets/4467650/11133653/f1ac0fc8-894b-11e5-9026-5a20edbda8bd.png)

![image](https://cloud.githubusercontent.com/assets/4467650/11133632/c2afe38e-894b-11e5-9d7d-da1c0ca7e606.png)

I tried deleting the credit card and it allowed me to do so, which it shouldn't have if it recognized the dependency properly:

![image](https://cloud.githubusercontent.com/assets/4467650/11133703/4bc79cf2-894c-11e5-9e59-aec41b526799.png)

**Comment by manishas** [comment]
@DavidGDragon @xdothackerx can you guys look into it?

**Comment by ttrahan** [comment]
note that this subscription is for a single-tenant beta plan at $0, which may be why the card isn't shown as associated with the subscription.

**Comment by manishas** [comment]
I am running into the same thing. sub id is 540efdd13479c5ea8f9f2a5b which is mt-ci and has 5 minions.

Account settings show my amex not linked to anything.

**Comment by manishas** [comment]
Closing this issue since it's not really a problem.
