### ISSUE TITLE
The right credit card is not being selected on billing page of a sub 

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2025]
I have multiple credit cards in my account and am using my Visa in one of my subs (id 540efdd13479c5ea8f9f2a5b).

When I go to my sub billing page, I see my AmEx selected by default in the credit card dropdown. It should show my Visa as selected there.

**Comment by manishas** [comment]
Assigning to @DavidGDragon

**Comment by avinci** [comment]
Did we fix this?

**Comment by manishas** [comment]
We will address this when we redesign the CI Billing page this week.

**Comment by xdothackerx** [comment]
Beta verified 3120.
