### ISSUE TITLE
How does one produce a Java War file and have it included in a docker container?

### ISSUE THREAD

**Issue by asans** [Shippable/support#2026]
In Java Webapps, the process of creating the war is normally different from the docker container that is created to run.  For example, a job is used to create a war file.  This war file is then added into a runtime Tomcat docker container that contains the war file.  In the tomcat runtime container, there is no need to have a development environment used to create the war file.  

In a case like this, I would assume that I would need to create the war file ahead of time and then during the post CI task, I would make use of this war file with a different container.

The question is... how do I get this war file into the docker container?  From what I have tried, it doesn't keep the generated war file during the script stage.  Other than placing this war file into a intermediate storage like S3 or maven repo, is there any other way to just make use of this artifact?

**Comment by manishas** [comment]
@asans can you follow the instructions in this issue comment - https://github.com/Shippable/support/issues/1299#issuecomment-93084101

Let me know if that helps...

**Comment by manishas** [comment]
@asans let us know if the link above helped. I am closing this issue, but please re-open if you need more information.

**Comment by asans** [comment]
This helped.  Thanks.  A bit of a hack since it forces the dockerfile to be dependent on shippable semantics and configuration, but works.
