### ISSUE TITLE
possible bug: getaddrinfo to localhost failed

### ISSUE THREAD

**Issue by osumampouw** [Shippable/support#2027]
This is the error that I got from trying to connect to mongo in localhost:

Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

This problem recently started happening since 10 hours ago. 

Prior to this, all of our builds succeeded. We didn't modify our code that is associated to mongo. Even when we commit a dummy change, the build failed. 

So we were wondering if there's any change in shippable container. Maybe there's a change in a setting related to something like this: http://serverfault.com/questions/527297/dns-server-cant-resolve-localhost-name ?

As a bit of context: We used getaddrinfo to connect to mongo in localhost. We used mongo to setup our test and do full integration test in shippable.  

Reference build that failed:
https://app.shippable.com/builds/5645999d3832510d006d2a92
https://app.shippable.com/builds/56459f2b3832510d006dc4fd
https://app.shippable.com/builds/5645a2d43832510d006e1389
https://app.shippable.com/builds/5645b5246479ca0c00733c27
https://app.shippable.com/builds/5645b62e3832510d0070cda3

**Comment by manishas** [comment]
@osumampouw we will take a look at this today.

**Comment by osumampouw** [comment]
Hi @manishas actually we found the problem. It's on our code. Some of the mongodb connection that we made point to a mongo server outside of localhost. And somehow the database was down yesterday so that's the reason why all the builds started failing. Sorry for the inconvenience. I'll close this bug.
