### ISSUE TITLE
Cannot create slack Integration

### ISSUE THREAD

**Issue by avinci** [Shippable/support#2029]
![screen shot 2015-11-15 at 9 40 13 am](https://cloud.githubusercontent.com/assets/1302035/11170024/00034aea-8b7d-11e5-8a6d-4af61a90b2d6.jpg)

@manishas can we fix this ASAP

**Comment by manishas** [comment]
@rageshkrishna can you look into this?

**Comment by rageshkrishna** [comment]
This works now.
