### ISSUE TITLE
Cached version of the code

### ISSUE THREAD

**Issue by RonXS** [Shippable/support#2030]
I'm running into weird caching-like-issues.

If you check my build 5649b49e3a1ff80d00ad0db7 (account InsightYou)

You will see that it's failing on this step:

TASK: [database | Make sure that MySQL is running] **************************** 
failed: [127.0.0.1] => {"failed": true}
msg: /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

However, i removed this whole step some commits ago and this should not happen anymore.

Any suggestions how to make sure it doesnt try to build old versions of the code?

**Comment by RonXS** [comment]
I've also merged everything back into master, built that one on Shippable and it still runs that step even though its a whole new branch without that database step in place.

**Comment by RonXS** [comment]
I seem to book progress with the [reset_minion] tag, running into new problems, but this might be related to the complete reset, since the container might have been cached for a loooong time. 

However, this still is an issue even after i got this resolved, when i submit a new version of the code, it should NEVER run a old build ofcourse, otherwise Shippable would not be very reliable. It will checkout and test old versions of the code, might or might not fail and strange errors would occur (integrity issues there)

**Comment by RonXS** [comment]
Yes the minion cache was the problem here, so we need to find a way to prevent the minion cache to cause integrity issues by not actually updating the code where it should have.

**Comment by avinci** [comment]
@RonXS cache is triggered only once in the workflow. It was built predominantly for folks who wanted certain dependency packages not to be installed over and over again. 

Unfortunately there are more scenarios that folks need and we need to enhance this feature from ground up. We are currently working on stabilizing other parts and we will get to this the moment those are done. Should be early Jan when you should see this completely re-worked. 

For now you can manually reset the cache through a commit message `[reset-minion]`  and this will clean up all the cache present so that it will recache. 

Hope this helps

**Comment by RonXS** [comment]
Yes i understand what it's ment for, but the code that you checkout, which i add in the docker file, is not updated to the latest version either. It's the whole reason of using Shippable is it not? To unit test the latest version of your code.

So, my container fires up, references to the right commit message, however it doesnt actually get that version of the code, it's running an older version unless i literally reset the minion.

I cannot ask this from my developers to commit everything with [reset_minion]

**Comment by avinci** [comment]
Not sure I understand. If you do DockerBuild we don't cache at all. Can you send me your projectId and YML to avi@shippable.com and I will take a look at it.

**Comment by RonXS** [comment]
Will do!

**Comment by avinci** [comment]
I found your project from the build above. You are doing Pre CI docker build. Hence we don't cache anything. If you have cache turned on and its caching then its a problem. 

We should be getting your code and building it. Are you sure its not getting the latest code?

**Comment by RonXS** [comment]
Yes i am 100% sure if i remove the [reset_minion] tag, inconsistency starts happening.

I had a irrelevant step in my code that was causing errors, i removed it. This was it:

TASK: [database | Make sure that MySQL is running] **************************** 
failed: [127.0.0.1] => {"failed": true}

So, i removed that step. It kept running this step, until i added [reset_minion] to the commit message 5-6 builds later.

**Comment by avinci** [comment]
I see that your issue has been resolved. Thanks for persisting with it. I am going to be making updates to how we should be structuring our docs. Let me know if you hit any more bumps..
