### ISSUE TITLE
Multiple Environments on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by fabiocarneiro** [Shippable/support#2031]
I'm using "Deploy via Docker containers" http://docs.shippable.com/autodeploy-to-ebs/, and I created one deployment. The problem is that it only allows to create one, and what makes it even worse is that it deploys every single branch to this environment. I can't even select to deploy master only. So if I have one feature branch and it passes the tests it will be automatically deployed to my production environment.

There is one solution for that, which is having a single branch and work with forks, but not all my working colleagues like to work with forks, so it makes this solution unusable.

***we should at least be able to select the branch that is going to be deployed in the environment.***

**Comment by avinci** [comment]
Hi @fabiocarneiro, we have a host of env vars that is set automatically in the build. One of it $BRANCH and that should allow you to pivot on that. 

But I get your point. This was half baked and has not been thought through. As you might see, we are taking an overall look at everything and reworking it so that it meets real scenarios and not as a prototype. 

To give more flexibility, we are moving away from UI and to YML based config. It should allow you to pick any deploy based on the $BRANCH and then be able to push to multiple targets. 

This should be available to you early next month as we are starting to clean up from 1 end. I will try and see if we can prioritize this earlier...

**Comment by fabiocarneiro** [comment]
@avinci This is true for the "predefined environments" aproach, since you manually add eb init & eb deploy to "after_success" section.

However, I'm using the "Deployments" on the project settings. It allows you to setup only one deployment, which is weird, but acceptable. The main problem is, ***it deploys every single branch to the same environment***.

**Comment by avinci** [comment]
I can get that fix in. But we are totally moving away from project settings as we have heard that folks don't want to do on UI. Let me check on the branch setting in the deploy. Should be simple.

**Comment by fabiocarneiro** [comment]
@avinci Yes, at least while you don't have this available. I also suppose that you'll keep this ui thing working at least for a while so you don't break the running projects, right? So maybe its still worth to do it.

**Comment by avinci** [comment]
Yup. Also, we are planning to do the same thing with pre-defined deploys. Multiple of them in YML. Not putting the onus on you. I think we will have this working in beta soon. I will circle back with you on that to check whether it meets your needs....

On the UI, I will try and get that added ASAP.

**Comment by fabiocarneiro** [comment]
@avinci Just to clarify. how long you imagine this ASAP will take? Because I'm depending on that to finish my stuff and I need to decide If I can wait or find another solution.

**Comment by avinci** [comment]
I will get back to you by EOD.

**Comment by avinci** [comment]
This should be do-able. We will get this out early next week after our sprint this week is complete. Hope that works

**Comment by fabiocarneiro** [comment]
@avinci Is it supposed to be available already? I tried to delete my deployment and create again and I still can't select the branch.

**Comment by JADurham909** [comment]
I second this, I am trying to stand up a CI formation and I cant because everything is going to elastic automatically.  Its kind of a big roadblock.

**Comment by avinci** [comment]
Sorry for the delay. With long weekend and everything, we had very few resources available. 

I ended up digging through this code and the more I dig, doing a deployment in a CI workflow with Docker build is going to be super complicated. Just selecting branch does not solve the real problem, The immediate next thing that folks would need is different environment settings for different environments as it starts getting very very messy. It gets even more complicated if your beanstalk app consists of more than 1 docker container as the CI process is building only 1 container. 

There are 2 ways of doing this right.
1. you just use after_success script and do a push using awe-cli with the environment variables and you have complete control. You will not be able to do Post Docker Build in multi tenant plan. 
2. we built `shippable deploy` to do exactly this, especially for Docker in a managed way. We currently deploy to ECS and we will need to add Beanstalk to that. Our entire service with ver 40 micro services are running using SHIPPABLE deploy doing CD to ECS. 

@fabiocarneiro do you want to filter by branch still? I have the code already but it will not solve the environment var problem or the Docker build problem.

I think we need to take a step back and do this right. Do you guys mind jumping on a hangout to discuss this and make sure we implement the right thing. @JADurham909 @fabiocarneiro

**Comment by fabiocarneiro** [comment]
@avinci What do you exactly mean with "shippable deploy"? Is it a new feature or service? Can I already have access to it?

And I think you're looking into the big picture there. We have more than one container here but we are running a ci project for each of these containers since they're different projects and different languages and for these container we only need the image to be pushed to hub, we don't actually need a deployment for them. We need only one deployment for the entire application, if there are more than one deployment, it means that they will be different applications and then I can have different deployment configuration.

There are 3 things that would completely solve the problem for now in hi-lo priority order.
1. the ability to select a branch for the deployment
2. the ability to add multiple deployments (one for each branch)
3. the ability to have a generic deployment that would catch and create any other branch not specified in the banch selected ones, but as last step, so we could have "staging on demand" for branches not specified before, or the ability to activate deployment on pull request (always to a new environment)

The first one, is must-have, since nobody wants all branches to be deployed to the same server, and it doesn't make any sense unless you have only one branch.

The second one is highly desired, so you could at least have two environments, with lets say master and development branches and test things on development branch before allowing them to reach master.

The third one is optional, but would be really nice.

**Comment by JADurham909** [comment]
For us, the main thing is also just the ability to "include" a specific branch.  At least in the short-term.  That way I can use Formations off the master without having the images get deployed on the builds.

**Comment by JADurham909** [comment]
I can jump on a hangout if you want.

**Comment by fabiocarneiro** [comment]
@JADurham909 By default, they're all included in the same server. So basically you need my 1 and 2 requests.

**Comment by JADurham909** [comment]
@fabiocarneiro I use formations for CI, so I only need a one branch deploy.

**Comment by avinci** [comment]
I have added branch filtering to EBS deployment. As of now, default will be all branched will be deployed. In the deployment settings, you can pick a branch and once you pick, deployment will fire only for that branch. Let me know if this working for you folks.

**Comment by JADurham909** [comment]
This is not working.  I just had a dev branch deploy to EB after configuring it for master.

**Comment by avinci** [comment]
let me look into it and get back to you.

**Comment by JADurham909** [comment]
branches:
  only:
    - master
    - dev

And in the UI I selected master

**Comment by fabiocarneiro** [comment]
https://github.com/Shippable/support/issues/2108

**Comment by avinci** [comment]
@JADurham909 there was a bug and I have deployed the fix. This is working as expected. Let me know if you have any issues

**Comment by larsjoergensen** [comment]
The feature for "the ability to add multiple deployments (one for each branch)"

is there a timeframe for this?
