### ISSUE TITLE
extra breadcrumb when we navigate back to the subscription page from node details page

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2035]
repro steps -

- For a subscription on Single tenant beta (st-ci-beta), add a build node
- As the node initializes (or even after it initializes) go to the node details page
- Click on the subscription breadcrumb

The breadcrumb is wrong at this point  with 2 entries for subscription -
![screen shot 2015-11-17 at 5 14 32 pm](https://cloud.githubusercontent.com/assets/2983749/11229869/bd35676a-8d4e-11e5-8ff3-ffac049d084f.png)

**Comment by manishas** [comment]
assigning to @DavidGDragon

**Comment by manishas** [comment]
This should be wrapped up today.

**Comment by DavidGDragon** [comment]
beta verified www 3085
