### ISSUE TITLE
Use RESTful URLs for Account Integrations and Cluster Nodes

### ISSUE THREAD

**Issue by DavidGDragon** [Shippable/support#2037]
Account integrations and cluster nodes do not use restful URLs, they should be migrated to
accountIntegrations/:accountIntegrationId
clusterNode/:clusterNodeId

**Comment by manishas** [comment]
This should be wrapped up today.

**Comment by DavidGDragon** [comment]
EOD: PR needs review for clusterNode route.

**Comment by DavidGDragon** [comment]
Today: Goal is to close

**Comment by DavidGDragon** [comment]
Today: Finish clusterNodes, start accountIntegrations

**Comment by DavidGDragon** [comment]
https://github.com/Shippable/www/issues/2532 clusterNodes page beta verified www 3121

**Comment by DavidGDragon** [comment]
EOD: accountIntegrations page on hold until I have time to address it.

**Comment by DavidGDragon** [comment]
beta verified www 3384

**Comment by DavidGDragon** [comment]
production verified www 3387
