### ISSUE TITLE
Handle git clone failures and merge conflicts for pre-ci docker build 

### ISSUE THREAD

**Issue by vidyar** [Shippable/support#2039]
![image](https://cloud.githubusercontent.com/assets/4965752/11208498/87f4b6e4-8d41-11e5-996d-6e8608fbf45e.png)
![image](https://cloud.githubusercontent.com/assets/4965752/11208533/bee490de-8d41-11e5-9f59-adcf11e92f0e.png)

It works correctly for normal builds and post-ci docker builds. But it is not working for pre-ci builds . Build steps are still executing even after `syncing git repo` step failure .
- https://app.shippable.com/builds/564af20734a1910d000157cf
- https://app.shippable.com/builds/564ad76a2299470d00274658

**Comment by manishas** [comment]
This will be closed today.

**Comment by kanthchandra** [comment]
A fix for this is ready and should make it to production in the next deployment.

**Comment by kanthchandra** [comment]
This has been deployed and verified. Closing.
