### ISSUE TITLE
I want to choose which job of a matrix to push to docker registry

### ISSUE THREAD

**Issue by ferrix** [Shippable/support#2041]
I am testing several matrix versions but only one is worthy of production.

Currently all of them get pushed to registry. I would however want to pick one.

**Comment by manishas** [comment]
Do you want to pick the same one each time? You can do it using environment variables and our new yml format which gives you complete control over your workflow.

Your yml would look something like this: 

``
env:
   - FOO = 1
   - FOO = 2

build:
   post_ci:
      -  'if [ "$FOO" == "2" ]; then docker push repo/image:tag ; fi'
```
