### ISSUE TITLE
Build stuck on waiting

### ISSUE THREAD

**Issue by fayazkhan** [Shippable/support#2042]
My build is stuck on waiting. It says "Minion usage: 1 of 1" but the organization does not have any other builds running.

**Comment by manishas** [comment]
@fayazkhan we had an outage today which affected a lot of builds. It is being tracked in https://github.com/Shippable/support/issues/2046.

We believe the issue has been resolved and we're actively monitoring the system. I am closing this issue, but let us know if you're still running into this and we'll take a look.
