### ISSUE TITLE
Move "Clear Cache" to "Cache Container"

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2043]
Within the project settings one can clear the cache of containers in *Clear Cache*. However, this is hard to notice that far away from the actual *Cache Container* setting, so it should be moved upwards to have both of these together.

**Comment by manishas** [comment]
we are moving away from cache container setting in project settings. the new way of caching is documented here - http://docs.shippable.com/ci_configure/#caching-your-container

closing this issue.

**Comment by mbrodala** [comment]
Notice that this issue was not about cache settings but cache actions. With `[reset minion]` this can be done with a commit though.
