### ISSUE TITLE
Builds are stucked and cannot be cancelled.

### ISSUE THREAD

**Issue by Achse** [Shippable/support#2045]
Hi,

for example: https://app.shippable.com/builds/564c8b002ed34f0c00e5de83 is stucked and when I press cancel, nothing happend.

Thanks for help.

Petr

**Comment by Achse** [comment]
This build too: https://app.shippable.com/builds/564c7d61fd15880d0019eae9

**Comment by Achse** [comment]
Also, today is problem with starting a builds. For example this pull: https://github.com/damejidlo/valkfleet-adapter/pull/17 (commit 38e568b466cad0b1b609881fe86053f85f330c9c) hasn't started a build.

**Comment by manishas** [comment]
@Achse We are currently experiencing a service outage. We're looking into it and will have an update soon.

**Comment by hillbilly90** [comment]
This build as well: https://app.shippable.com/projects/5524db225ab6cc1352bbd5e7

**Comment by manishas** [comment]
I am closing this as a dup of https://github.com/Shippable/support/issues/2046 since this was related to the outage we had today.

Please let us know if you are still running into issues and we will take a look. Thanks for your patience!
