### ISSUE TITLE
SERVICE OUTAGE

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2046]
Shippable is currently experiencing a service outage.

The reason behind this is that our internal queue server is down and we're trying to recover by creating a new one and bringing it up.

We will post updates in this issue until the outage is resolved.

**Comment by phagunbaya** [comment]
Any ETA ?

**Comment by manishas** [comment]
We're still investigating it and will provide an ETA in 30 mins.

**Comment by ivancamilov** [comment]
sorry to be a nag, but it's been an hour... any ETA?

**Comment by manishas** [comment]
We should be able to get things back to normal in another 60 minutes. We'll post an update soon.

**Comment by manishas** [comment]
Service is back up and builds should be running normally. Please let us know if you run into any issues. 

Thanks for your patience!

**Comment by phagunbaya** [comment]
Thanks !

**Comment by manishas** [comment]
Everything should be back up now. Thanks!

**Comment by manishas** [comment]
@jessestuart great haiku... I hope devs didn't leave yet :)

**Comment by jessestuart** [comment]
@manishas Haha, nope 😄 Thanks for your hard work guys/gals!

**Comment by chriskinsman** [comment]
We still have a ton of hung builds and no new ones are kicking off...

**Comment by jessestuart** [comment]
@manishas @chriskinsman Yeah, no progress on our end either—hung builds, no new builds being triggered.

**Comment by pastawoua** [comment]
Keep getting this message now:
Error
An error occured, please choose an action.
Missing response

**Comment by avinci** [comment]
We are looking into it. Sorry did not update the issue. I will not close it until we get to steady state

**Comment by manishas** [comment]
The core issue has been resolved and we are now stabilizing the system. Builds have started to run but might be backed up due to the load. We are closely monitoring the situation to make sure everything keeps running.

We will keep this issue open until we are completely sure that everything will stay up and running as expected.

**Comment by manishas** [comment]
closing this since outage is resolved.
