### ISSUE TITLE
Service timeout from github hook

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#2051]
The Shippable webhooks that github is invoking are responding with "Service Timeout" messages, so no automated builds are being registered for me.  Is this related to the queue backup and outage earlier today?

**Comment by avinci** [comment]
yes. All web hooks go into a queue and if queue goes down, we cannot do anything. This was the first time msg went down in the last 14 months and we will update a post mortem on this once we are done with the fix... Right now all hands are on deck to fix this issue

**Comment by jeffkole** [comment]
I see.  #2046 gives the impression that the issue had been resolved.

**Comment by manishas** [comment]
@jeffkole i am closing this since it was related to our outage today. That is being tracked in https://github.com/Shippable/support/issues/2046.

Please let us know if you are still running into this and we will take a look. Thanks for your patience!
