### ISSUE TITLE
Build not triggered on commit and manual building branch doesn't work

### ISSUE THREAD

**Issue by nicdex** [Shippable/support#2052]
My build did not trigger from my bitbucket push. Also I can't trigger it manually.

When inspecting the web app I see that call to https://api.shippable.com/projects/55c4f515edd7f2c05299123d/newBuild returns a 504.

**Comment by manishas** [comment]
@nicdex I am closing this issue as a dup of https://github.com/Shippable/support/issues/2046 since this was related to our outage today.

Please let us know if you are still running into issues. Thanks for your patience!
