### ISSUE TITLE
builds frozen

### ISSUE THREAD

**Issue by jamesmk** [Shippable/support#2053]
Hello,

Our builds are currently frozen. They've been processing for hours and I can't cancel them. This is blocking all other build in queue.

https://app.shippable.com/subscriptions/540f392a586ac5d7e36513c3

thanks

**Comment by manishas** [comment]
@jamesmk closing this as a dup of https://github.com/Shippable/support/issues/2046 since this was related to our outage today.

Please let us know if you still are running into issues and we'll take a look.
