### ISSUE TITLE
Bitbucket integration build status api?

### ISSUE THREAD

**Issue by vladdancer** [Shippable/support#2054]
Hi, bitbucket was released recently a [build status api] (http://blog.bitbucket.org/2015/11/18/introducing-the-build-status-api-for-bitbucket-cloud/). Docs are here https://confluence.atlassian.com/bitbucket/buildstatus-resource-779295267.html Do you plan to support this feature?

**Comment by hranicka** [comment]
+1

**Comment by pquentin** [comment]
This would be great because it would allow us to bypass completely the /subscriptions page (the slowest part of Shippable for us, see #1665) to get directly to the build page. From Reunion island, our /subscriptions page takes 24s to load completely while a build page is "only" 13 seconds.

**Comment by elssar** [comment]
+1

**Comment by windmaomao** [comment]
Does this mean that github works out of box on this ?

**Comment by lafraia** [comment]
+1

**Comment by iivvoo** [comment]
+1

**Comment by melwas** [comment]
+1

**Comment by hranicka** [comment]
Shippable, any progress on the issue?

Until Shippable will support BitBucket Build API, I will use simple proxy service: https://bitbucket.org/hranicka/build-status/overview

**Comment by shamasis** [comment]
+1

**Comment by brettdh** [comment]
Hmm, maybe +1s do make a difference. :-)

I too would love to hear an estimate on when Shippable might roll this out. In the meantime, thanks @hranicka for the workaround!

**Comment by kanthchandra** [comment]
@everyone This feature will be available when the next prod deployment happens. Thanks everyone for your patience.

**Comment by kanthchandra** [comment]
@brettdh This has been deployed to prod. Marking this as resolved and closing the issue.

**Comment by shamasis** [comment]
Cheers.

**Comment by pquentin** [comment]
Thank you @kanthchandra!

**Comment by elssar** [comment]
:+1:
