### ISSUE TITLE
Builds still frozen

### ISSUE THREAD

**Issue by ricardoon** [Shippable/support#2055]
You have announced that the problem was solved, but my builds are still frozen.. I have one from 3 hours ago still waiting and I can't even cancel it.. And its not creating new ones..
Can you help me with that? =)

**Comment by avinci** [comment]
We are aware...sorry, we are looking into it. We are having message bus issues and causing us issues.

**Comment by manishas** [comment]
closing since this is a dup of https://github.com/Shippable/support/issues/2046

Please comment here if your builds are still frozen and we'll take a look. Thanks for your patience!
