### ISSUE TITLE
Hook to execute script after image pushed

### ISSUE THREAD

**Issue by pnpritchard** [Shippable/support#2057]
We are using the "Post-CI Build" workflow (http://blog.shippable.com/post-ci-dockerbuild). To complete our CI/CD workflow, we would like to run a script after the docker image is built and pushed, so that it can be deployed. Please let me know if this is possible currently, or if it could be added to your new feature roadmap. Thanks!

**Comment by manishas** [comment]
This is already on our feature roadmap. We'll mark this in progress when we pick it up and post regular updates.

**Comment by manishas** [comment]
@pnpritchard this is now available with the new build system!
cc @phagunbaya as FYI.

After you migrate to the new yml format, there is a `post_ci` section where you can include your `docker build` and `docker push` commands and then your script. This will execute sequentially, so the script will run after the image is pushed.

Please note that if you're using a custom image for your CI and are pushing to GCR, you will need the gcloud sdk installed in your custom image. More here - http://docs.shippable.com/ci_configure/#pushing-an-image-to-a-registry

**Comment by phagunbaya** [comment]
@manishas : Thanks. We will be initiating the migration next week.

**Comment by manishas** [comment]
cool. let us know if you need help.

closing this issue since this has been addressed.
