### ISSUE TITLE
Failures in pre-CI docker build are not handled correctly

### ISSUE THREAD

**Issue by rageshkrishna** [Shippable/support#2059]
When a pre-CI docker build fails to complete, the build should fail immediately. What is happening today is that the build continues without any complaints _if_ a previous docker build on the same project succeeded at any point in the past.

**Comment by kanthchandra** [comment]
This fix for this issue is ready and should be available when the next prod deployment takes place.

**Comment by kanthchandra** [comment]
This has been deployed and verified.Closing.
