### ISSUE TITLE
Can't connect to MySQL

### ISSUE THREAD

**Issue by fayazkhan** [Shippable/support#2060]
I seem to be having trouble connecting to MySQL.

```E       OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")```

Any ideas?

**Comment by rageshkrishna** [comment]
Hi @fayazkhan. It looks like you're running builds on our shippableimages/ubuntu1404_python image. This image only contains python, so if you need mysql you will need to install it yourself with `sudo apt-get install -y mysql-server` in the `install` section of your YML file and then launch mysql manually with something like `/usr/bin/mysqld_safe &`.

Note that mysql may take a few seconds to start up, so you will need to introduce a few seconds of delay (with `sleep`, maybe?) to give it some time.

Let me know if you have any more questions on this.

**Comment by fayazkhan** [comment]
So, is there a python image which has mysql installed?

**Comment by manishas** [comment]
@fayazkhan our default image minv2 has python and mysql preinstalled. Can you try your build with minv2? We will also add new images with python and several services preinstalled in the next couple of weeks.
