### ISSUE TITLE
Add support for Bitbucket build status API

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2061]
Bitbucket recently announced its [build status API](http://blog.bitbucket.org/2015/11/18/introducing-the-build-status-api-for-bitbucket-cloud/) which allows CI tools to post their build status to Bitbucket and thus conveniently show them within Bitbucket. Shippable should probably support this.

**Comment by manishas** [comment]
Dup of https://github.com/Shippable/support/issues/2054

**Comment by mbrodala** [comment]
Whoops, you're right. ;-)
