### ISSUE TITLE
Slow Builds

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2062]
@manishas Not sure if a hang over from yesterday but builds are very slow still today.  Builds that normally take 5-8 minutes are taking about 21-23 minutes...

**Comment by chriskinsman** [comment]
Weird thing is some are executing quickly.  Others end up taking 20-25 minutes...

**Comment by manishas** [comment]
we're monitoring this... no root cause yet.

**Comment by manishas** [comment]
@chriskinsman do you still see this? we deployed a couple of fixes over the last day that should help with this...
