### ISSUE TITLE
Build stale on authentication required

### ISSUE THREAD

**Issue by adrien-candiotti** [Shippable/support#2063]
Hi!

I built a base image hosted on my tutum registry to share my SSH keys.
The build on shippable reach the FROM, tries to pull the image but the authentication kicks in and makes the build go stale.

Is there any way I could hack this? By login into the tutum registry before the build maybe?

Here is the link to the build:
https://app.shippable.com/builds/564df0a9722fc10d00541e06

Thanks!

**Comment by manishas** [comment]
@adrien-candiotti can you try the instructions at 
http://docs.shippable.com/integrations/#private-registry
http://docs.shippable.com/docker_registries/#pull-images-from-a-private-registry

Let me know if that works.

**Comment by adrien-candiotti** [comment]
Mmh, the thing is that I do want to build an image but based on a private image.
Your solution only propose to build an image or pull it from a private registry.
Not to build an image based on an image in a private registry.

That's ok, i'll just hack around.

**Comment by rageshkrishna** [comment]
@adrien-candiotti If you set up your Tutum Registry credentials as a Private Docker Registry integration in our system, we will do the `docker login` for you with those credentials. Just use the Tutum registry URL and everything should work. Once we do the `docker login`, your docker build will be able to pull your private image and continue with the build.

We call it a "Private Docker Registry" integration, but you can really use it to connect to any arbitrary registry. Let me know if you need any more help with this.
