### ISSUE TITLE
Builds repeating steps until timeout

### ISSUE THREAD

**Issue by JADurham909** [Shippable/support#2064]
I am seeing this behavior on all projects using dockerhub to push containers.  The build steps repeat over and over until finally it times out

Generating Builds
Updating RSA keys
Syncing Git
Login to hub
Build image
Rinse and repeat

This is currently happening on at least 3 builds today.  Its also happening on builds with elastic beanstalk deployments which never trigger.

**Comment by JADurham909** [comment]
Docker + Elastic Deployment steps

![image](https://cloud.githubusercontent.com/assets/574966/11292080/c9056454-8f16-11e5-8c81-c343e9468d90.png)

**Comment by JADurham909** [comment]
Docker without Elastic Deployments

![image](https://cloud.githubusercontent.com/assets/574966/11292087/e6deb1b0-8f16-11e5-8628-b477c749c616.png)

**Comment by JADurham909** [comment]
This started happening this morning, its been fine for weeks.

**Comment by manishas** [comment]
dup of #2023
