### ISSUE TITLE
Builds not completing and getting "Timeout" eventually.

### ISSUE THREAD

**Issue by hammadalinaqvi** [Shippable/support#2065]
@manishas, @vidyar : None of the builds that are initiated are getting completed for the last 2 days. Attached are the screenshots. Would really appreciate if this can be resolved soon.

The latest builds are:
1. https://app.shippable.com/builds/564db5a4722fc10d003d56fe (1eq)
2. https://app.shippable.com/builds/564dd928ac794d0c0085bfcd (one_account)

**Comment by rageshkrishna** [comment]
@hammadalinaqvi It looks like you're using custom nodes. Support for this has been deprecated and we have started a new beta for single-tenant CI. You would have received an email from @manishas communicating the changes and how you can move your dedicated host to the new single-tenant plans. Transitioning should only take 5 minutes of your time.

Please let me know if you need any help with this.

**Comment by manishas** [comment]
@hammadalinaqvi in case you missed the email, instructions were reposted in https://github.com/Shippable/support/issues/2040

Can you follow the instructions there and let us know if everything works?

**Comment by hammadalinaqvi** [comment]
@rageshkrishna Yup we are. Let me try the switching process.

@manishas Can you please send me that email too. I didn't get it. 
Email: hammad.ali08@gmail.com

**Comment by manishas** [comment]
@hammadalinaqvi I just sent it to you. Let me know if you need help with switching over to the single tenant CI plan.

**Comment by manishas** [comment]
i am closing this issue since your latest builds seem to have been successful. Let me know if we can help with anything else.

Our Single Tenant CI Beta is the new reincarnation of dedicated hosts and has many bug fixes and enhancements. Over the next few weeks, we plan to harden it and also get feedback from users like yourself so we can add the right things to it before launch. @ttrahan will reach out to you soon with a follow up. Thanks!

**Comment by hammadalinaqvi** [comment]
@manishas & @rageshkrishna: Thank you for your support, I was able to switch o st-ci (beta) seamlessly.

However for the past 2 hours the builds are getting initiated but not finishing completely.
https://app.shippable.com/builds/5652f52c0b0f290e00f3f5de started 2 hours ago and is still in progress!!

**Comment by hammadalinaqvi** [comment]
@manishas https://app.shippable.com/builds/56531a2a4dc05e0b00bfedf7 is in "processing" state for the last 1 hour.

**Comment by hammadalinaqvi** [comment]
@manishas @rageshkrishna @vidyar 
Guys would you like me to create a new ticket for this (please see above comments after the ticket was closed) or can we open this ticket again and see whats wrong!!

**Comment by manishas** [comment]
@hammadalinaqvi can you kick off a build for the staging branch? we'll take a look at what's going on...

**Comment by hammadalinaqvi** [comment]
@manishas Should I re-deploy one of the cancelled ones, or would you like me to kick off a new build?

**Comment by manishas** [comment]
Either will be fine. Thanks!

**Comment by hammadalinaqvi** [comment]
staging.1031: 
https://app.shippable.com/builds/565374737480340c002f82a6

**Comment by manishas** [comment]
can you do the following -
on your build host, run command -  ```docker ps | grep 552ed126edd7f2c052c3f4bf```

this will give you a container id. then tail the logs with - ```docker logs -f [containerID]`` and let us know what the last few lines of the logs are.

**Comment by manishas** [comment]
@hammadalinaqvi have you added any packages to the build since the last successful run? Our best guess right now is that some package is waiting for user input and this is timing out. Steps in the comment above will help us figure out what happened.

**Comment by hammadalinaqvi** [comment]
@manishas package.json was last updated 5 months ago.

Trying to see the logs for you...

**Comment by hammadalinaqvi** [comment]
@manishas Don't have any containers by the NAME 
However `CDM.build.565374737480340c002f82a6.1` exists. Attached is the log for this container
[474d62b65d20.txt](https://github.com/Shippable/support/files/42075/474d62b65d20.txt)

**Comment by hammadalinaqvi** [comment]
Fixed it. Apparently it was some dependency issue!!

@manishas @rageshkrishna Thanks for the support! Much appreciated.

**Comment by manishas** [comment]
:+1:
