### ISSUE TITLE
Email notification shows negative build duration for some builds

### ISSUE THREAD

**Issue by vidyar** [Shippable/support#2067]
![image](https://cloud.githubusercontent.com/assets/4965752/11297854/21936ae6-8fa1-11e5-9f3f-b2c4e0adec38.png)

![image](https://cloud.githubusercontent.com/assets/4965752/11297909/7b9db33e-8fa1-11e5-8267-337e5ed48f14.png)

**Comment by avinci** [comment]
@kanthchandra this should be part of nf refactor

**Comment by vidyar** [comment]
Closing this issue as it doesn't seem to be happening in prod now.
