### ISSUE TITLE
buildoutput: no such file or directory

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#2068]
Hi, 

Since two hours ago our builds are all failing at the **build image** step with error message 
buildoutput: no such file or directory

Please help us out since this is blocking our delivery process. 

https://app.shippable.com/builds/564ef4c742492c0d00e0d41f

Ron

**Comment by rageshkrishna** [comment]
@rvdwijngaard Can you please try it out now? Things should be back to normal.

**Comment by deosjr** [comment]
Seems to have been fixed, thanks a lot!
