### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#2069]
I keep getting these errors? unable to deploy any builds.

error creating aufs mount to /data/aufs/mnt/23c714bb8f09303bfda08e4342f4550aa11d5ea4ff50b8e31d5032a9833548d6-init: invalid argument

**Comment by manishas** [comment]
@sheldon-sminq can you please share a link for a failed build with this message?

**Comment by sheldon-sminq** [comment]
https://app.shippable.com/builds/564f4f1e3fd5ae0d0087b2e6

**Comment by sheldon-sminq** [comment]
Not sure but after i did a clear cache things worked.

**Comment by sheldon-sminq** [comment]
And another failure

https://app.shippable.com/builds/564ffd6c4dc05e0b008c32a9

**Comment by avinci** [comment]
@sheldon-sminq I see that you are doing a post docker build. I wanted to know if you are extracting artifacts from your preCI container as part of our docker build? Can you send me your YML and DockerFile so that I can debug this further...

my email is avi@shippable.com

**Comment by manishas** [comment]
@avinci @sheldon-sminq is there any progress on this? I took a look and didn't see any failures in that branch for the last couple of days, so not sure where we are with this issue.

**Comment by sheldon-sminq** [comment]
No failures yet i did experience it a couple of times but doing a rebuild
worked.

**Comment by manishas** [comment]
is this still a problem?

**Comment by manishas** [comment]
I am closing this issue. if this is still a problem, please reopen.
