### ISSUE TITLE
Limit concurrent branch builds

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#2071]
For some scenarios, we'd like to do a master build, only for the commit (so not PR), once merged. This then creates an artifact which is ready for deploy. However in order to prevent race conditions, we'd want to limit these builds to just one concurrent build (to prevent a slow build to release an artifact later on, while the later faster build should be the correct one).

Is there any plan to support such a feature?

**Comment by avinci** [comment]
Sorry for the delayed response. I want to understand the scenario a bit more. I understand most it except the last part which was in parenthesis. Can you elaborate that a bit more?

**Comment by avinci** [comment]
I think i got it after spending sometime thinking about it. So what you need to don't finish until the prior one is finished...correct?

**Comment by rogierslag** [comment]
Right. For eg a master branch, which will publish a release: it should queue those builds to perform them in sequence instead of parallel. That way the produced releases are at least deterministic and not influenced by build server loads

**Comment by joostverdoorn** [comment]
:+1: would help me greatly!

**Comment by manishas** [comment]
this is a flavor of the feature described in #983 so linking them together and closing.

**Comment by manishas** [comment]
@rogierslag this is now available as a project setting. If you go to the Settings tab for your project and scroll to the 'Run parallel jobs' section, you'll see a button to Disable parallel builds. Once you disable parallel builds, you'll see a dropdown that lets you select specific branch(es) for which to limit cocurrency.

Docs are updated here - http://docs.shippable.com/ci_projects/#run-parallel-jobs
