### ISSUE TITLE
Rake command not found on a node.js image

### ISSUE THREAD

**Issue by adrien-candiotti** [Shippable/support#2072]
Hi!

The image is now built with my private image without any trouble as far as I know.

The problem is that after the build there is a "script" step, where the test stop saying:

rake:
/root/cb5d5dbb-25ea-47b8-a546-e93e4c6b966b.sh: line 88: rake: command not found

I guess you're injecting a script somewhere (or it's the container that execute the test that fails?) as the script seems named after a hash and i'm not using rake in my node.js project.

Maybe there's a ruby options checked somewhere in my shippable configuration?

Thank you!

**Comment by rageshkrishna** [comment]
If your YML file doesn't specify a `language` setting, we default to Ruby. For Ruby projects, if you don't specify a `script` setting in the YML, we default to `rake`.

You should update your YML file to specify a language, platform version and script commands, like this:

````
language: node_js
node:
 - 0.12
script:
 - echo "This is a script step"
 - echo "This is another script step"
````

**Comment by adrien-candiotti** [comment]
I'm building my own image for the test, I guess the mecanism you describe is used to test in one of your images?
What do I need to avoid this "language specific" step?

**Comment by rageshkrishna** [comment]
Even if you're using your own images, we need to know what commands to run during the build. If you don't specify anything in your YML file, we assume it's Ruby and run `rake`. This choice was made for legacy compatibility.

If you want to customize this, you must change your shippable.yml file.

**Comment by adrien-candiotti** [comment]
Ok i'll try :)

Thank you!
