### ISSUE TITLE
node initialization is broken for st-ci-beta plan

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2073]
https://app.shippable.com/subscriptions/540e75583479c5ea8f9e71e1/nodeDetails?node=563d4f50aba5ac0c00d36a5b

```
sudo apt-get install -y lxc-docker-$DOCKER_VERSION
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package lxc-docker-undefined
```

**Comment by manishas** [comment]
assigning to avinci...

**Comment by avinci** [comment]
this is fixed. There was a missing setting in the initialization micro-service. I have updated it and its fixed
