### ISSUE TITLE
Question: Is it possible to run shippable.yml locally or use a script to parse it into Dockerfile?

### ISSUE THREAD

**Issue by davidthewatson** [Shippable/support#208]
I'd like to use shippable.yml to run my build locally, since shippable was dramatically easier to get working than any other method I've found. Is it possible to run my shippable build on my local machine, or is there a script to convert it to a docker file? I'd really like to use it to spin up new developer machines. I'm not interested in running builds locally beyond that capability.

**Comment by manishas** [comment]
Our Dockerfiles are all in the shippableImages org on github. 
We also provide the build script that was run for your build in the script tab on your build page -

![screen shot 2015-07-01 at 12 32 42 pm](https://cloud.githubusercontent.com/assets/2983749/8463186/633618a0-1fed-11e5-9455-448104d2b4f4.png)

Additionally, you can push your container to docker hub or another docker registry and download and run on your machine.
