### ISSUE TITLE
How to create/set postgres user and password?

### ISSUE THREAD

**Issue by bradcypert** [Shippable/support#2080]
Is there a correct way to create a user for testing and how do I set that for the shippable job?

**Comment by rageshkrishna** [comment]
@bradcypert If you're running builds on our default image (shippable/minv2), postgres is already set up and configured to accept connections from user `postgres` with no password so you can just do this in your shippable.yml to start using it:

````
before_script:
  - psql -c 'create database myapp_test;' -U postgres
````

If you really do need to create a new user, this should work for you:

````
before_script:
  - echo "CREATE ROLE foo WITH LOGIN PASSWORD 'bar'" | psql -U postgres
````
