### ISSUE TITLE
Scala build hangs during compilation phase on shippable, but not locally using the same container

### ISSUE THREAD

**Issue by rchristensen** [Shippable/support#2082]
Hey Shippable!

This [build](https://app.shippable.com/builds/565520aaaf914c0d006ff3fd) hangs during the compilation step of our Scala/Play-Framework app, with no errors. The same container compiles and runs tests fine locally.  Is there anymore information you can provide us to help debug this issue?

[This](https://app.shippable.com/builds/5655d00d4561b70d008be7a3) is another example that I'm re-running now for posterity, if it helps

Our YML:

```
build_image: jaroop/play-test:2.3.9
language: scala
scala:
  - 2.11.7
cache: true
before_install:
- sudo su
- service mysql start
- ln -s /tmp target
- mysql --version
- mysql -uroot -e "SELECT VERSION();"
- export _JAVA_OPTIONS="-Xms1024m -Xmx1024m -Xss256m"
before_script:
- export TZ=UTC
- date
- mysql -uroot -e 'drop database if exists jets_test; create database jets_test;'
- cat conf/application.conf | sed s/db.default.password=\"root\"/db.default.password=\"\"/ > conf/testing.conf
- mv conf/testing.conf conf/application.conf
script: sbt ++$SHIPPABLE_SCALA_VERSION -Ddb.default.user=root -Ddb.default.password="" -Dehcacheplugin=enabled -Dmemcachedplugin=disabled -Demails.enabled=false clean coverage test
after_script:
- mkdir -p shippable/testresults
- cp target/test-reports/*.xml shippable/testresults
- cp target/scala-2.11/coverage-report/cobertura.xml shippable/codecoverage
notifications:
   email: false
```

**Comment by manishas** [comment]
@rchristensen i see your latest builds are green.... do you still have this issue or did you fix it?

Let me know if we need to look into this. thanks!

**Comment by rchristensen** [comment]
@manishas yes, sorry! we figured out that node wasn't installed for some reason and our JS tests were somewhat silently failing.  I'll close this out.
