### ISSUE TITLE
Cannot locate Dockerfile

### ISSUE THREAD

**Issue by gegere** [Shippable/support#2083]
Hello,

Kinda confused... I know I need to tell Shippable where the Dockerfile is but not quite sure how? Is it a must that the Dockerfile be in the root directory?

Within [this repo](https://github.com/htmlgraphic/Mail-Server) I am looking to `cd` into the `Dovecot` directory and execute the Dockerfile to build and test the system build. As I create more tests I will do the same for the other directories and test various other builds. I am missing something simple but after much document reading on shippable.com and searching I have come up empty handed.

Build issue:
https://app.shippable.com/builds/56565bc679c1df0c00f353ab

**Comment by manishas** [comment]
@gegere currently, the dockerfile has to be at the root of your repository and we only support one dockerfile per repo.

However, we're moving all docker options to the yml where you will be able to do the above.

**Comment by cjerdonek** [comment]
I would rename the title of this issue to something like, "Allow path to Dockerfile to be customized."

**Comment by avinci** [comment]
@cjerdonek this has been fixed in our next version. This is launching on Feb 29th and you will get full control of docker daemon on the host. This should solve most of the docker build issues and we have made a deliberate design decision to get out of your docker command and the docker daemon. This was a design choice we made 2 years ago before docker became ubiquitous and we have changed that now... Hope you are going to like the next version....

**Comment by manishas** [comment]
This is now possible with our new yml format, where you can include docker commands. yml configuration is explained here - http://docs.shippable.com/ci_configure/

You will need to be on the new build system to use the new format. You can check by going to the Billing tab of your subscription and making sure plan name is Continuous Delivery. If it is not, you can update the plan.

Your yml will have something like this to cd into a folder and run docker build-

```
build:
   pre_ci: 
       - cd micro-api && docker build -t manishas/micro-api .
```

Example above is from a sample repo - https://github.com/shippableSamples/micro-sample

**Comment by manishas** [comment]
I am closing this issue but please let us know if you need help getting set up.

**Comment by gegere** [comment]
Awesome!

**Comment by cjerdonek** [comment]
Thanks, @avinci and @manishas. Looking forward to trying it out!
