### ISSUE TITLE
project settings do not show hub integration added by someone else or let me change it

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2084]
This is a regression - if someone else adds a hub integration, we are not displaying it and also not letting the user change it.

![screen shot 2015-11-25 at 9 55 54 pm](https://cloud.githubusercontent.com/assets/2983749/11416122/8e7be1ca-93bf-11e5-96e2-a68b3923d110.png)

**Comment by manishas** [comment]
@pranaypareek we need to fix this ASAP.

**Comment by pranaypareek** [comment]
This has been fixed and verified in beta.

Integrations for the project added by other team members are now visible.

Dropdown for choosing another integration is also visible.

![selection_491](https://cloud.githubusercontent.com/assets/6316230/11418400/718e2434-9445-11e5-949e-e7b5477b38d3.png)

**Comment by pranaypareek** [comment]
The fix is now in prod.
