### ISSUE TITLE
"No defaultPlanId found" during AWS integration setup

### ISSUE THREAD

**Issue by Enalmada** [Shippable/support#2085]
I am trying to follow these direction to attach aws integration to my account.
   http://blog.shippable.com/deploying-containers-to-elastic-beanstalk-the-shippable-way

I choose Integrations > AWS, set name to "AWS Integration", add a key/secret with access to beanstalk and this error comes up:

```
{"id":1003,"message":"No defaultPlanId found for MasterIntegration :id55c8d2333399590c007982f8","methodName":"caller:55938e141604df0b00de3341|accountIntegrations|post|_postProvider"}
```

**Comment by manishas** [comment]
this is a bug and looks like we introduced this recently. we'll take a look asap.

**Comment by manishas** [comment]
@himanshu0503 we need to fix this asap!

**Comment by himanshu0503** [comment]
I am looking into it.

**Comment by manishas** [comment]
@Enalmada sorry about this. we're fixing this and ETA is ~ 1 hour. We will update this when we deploy the fix.

**Comment by himanshu0503** [comment]
@Enalmada : A fix has been deployed for this. Can you please verify?

**Comment by Enalmada** [comment]
Yes, I can confirm that it did save my integration.  Thank you for the quick response!
