### ISSUE TITLE
Unable to setup links between containers in service definition

### ISSUE THREAD

**Issue by wandergeek** [Shippable/support#2088]
I need to be able to access services from other containers in the formation, but I can't seem to figure out where the configuration needs to sit.

**Comment by avinci** [comment]
This depends on how your networking in setup. If all your container instances can talk to each other, then by looking at host port and host IP information you can setup routes in the apps. If you run multiple replicas, then you will need a load balancer to accomplish this. If you don't want it public, you can use an internal load balancer to do it. 

If you would like, I can jump on a hangout and then demo this e2e. Would that work?
