### ISSUE TITLE
Unable to set CPU and memory parameters for containers deployed to AWS ECS 

### ISSUE THREAD

**Issue by wandergeek** [Shippable/support#2089]
I am unable to determine how to set both CPU and memory parameters for the containers in my formation. Is this feature available?

**Comment by avinci** [comment]
yup, this going to be added very soon. We are cleaning up this setting and will make this available in the next couple of weeks.

**Comment by avinci** [comment]
We have deployed this into production. We are not going to be supporting CPU in the short term as there is no deterministic way to do this. But memory has been implement. I am happy to discuss more around CPU if you would like to.
