### ISSUE TITLE
Build fails during npm install most of the time

### ISSUE THREAD

**Issue by ashernevins** [Shippable/support#2090]
I recently created a new project that uses an identical Dockerfile to another project of mine. 
This new project almost always (but not always) fails while running npm install with the following error:

npm ERR! System Linux 3.13.0-57-generic
npm ERR! command "/nodejs/bin/node" "/nodejs/bin/npm" "install"
npm ERR! cwd /app
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path /root/.npm/a58c529b-oot-npm-lodash-2-4-2-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47
npm ERR! not ok code 0

I cannot reproduce this error when building the image locally, and I have restarted the build a few times on shippable and it was built successfully after a failure. What about the environment would cause this, and is there anything I can do to prevent it?

**Comment by rageshkrishna** [comment]
Can you try with a newer version of npm? Older versions have been known to have race conditions that cause these intermittent issues.

**Comment by ashernevins** [comment]
I can't easily upgrade to the latest right now because many of the packages I use haven't been updated to deal with the new dependency handling.

Do you have a link to the bug that causes these race conditions?

**Comment by rageshkrishna** [comment]
Here are a few support issues we've seen in the past with similar problems (EEXIST errors):

https://github.com/Shippable/support/issues/691
https://github.com/Shippable/support/issues/712
https://github.com/Shippable/support/issues/713

**Comment by ashernevins** [comment]
Thanks for those references. I'm going to close this since it seems to be solvable by upgrading npm.
