### ISSUE TITLE
Formation service will not start, no error logs

### ISSUE THREAD

**Issue by JADurham909** [Shippable/support#2092]
I am not sure what do with this one, I see a red circle on my formation by no way to see the logs to see why it stopped.

**Comment by JADurham909** [comment]
Getting this error today:

{"id":1004,"message":"No cluster found for :consumerId 565dd07de75ca00d009f04b8","methodName":"caller:56551cd85069e30f0090a740|passthrough|tasks|getSByServiceId:565dd0dd82697a0c00f8cbd6|_getSubscriptionCluster"}

**Comment by avinci** [comment]
@JADurham909 we are completely reworking this piece. I will get back to you once its up and running.
