### ISSUE TITLE
Notifications (via Slack integration) has stopped working

### ISSUE THREAD

**Issue by ashernevins** [Shippable/support#2093]
I have two projects that have notifications via Slack. One of them can be found here: https://app.shippable.com/projects/562f31c81895ca4474213d24

Some time between builds 19 and 20 on that project (between 2 hours ago and 40 mins ago) the slack notifications stopped working. They also stopped working for another project.

I have tested the slack integration API path directly and have confirmed that Slack is working fine.

**Comment by manishas** [comment]
@kanthchandra can we take a look at this?

**Comment by kanthchandra** [comment]
@manishas looking into it.

**Comment by kanthchandra** [comment]
We have identified the issue and we will deploy a fix very soon. I'll update this as we make progress.

**Comment by kanthchandra** [comment]
@ashernevins this is fixed and you should have got all the backed up messages.

**Comment by ashernevins** [comment]
Thanks for the fast response
