### ISSUE TITLE
Error getting file list from provider

### ISSUE THREAD

**Issue by fayazkhan** [Shippable/support#2094]
Building a specific tag seems to be failing at this point:

     Error while generating build for branch v2.15.15
         Error getting file list from provider

**Comment by manishas** [comment]
@fayazkhan we do not support building tags at this time. We're definitely considering adding this since we've had a couple of requests around this feature.

**Comment by manishas** [comment]
in the meantime, you can try running a manual build and that should work fine.

**Comment by manishas** [comment]
DUP of https://github.com/Shippable/support/issues/1362
