### ISSUE TITLE
Where can I find my Deployment Key?

### ISSUE THREAD

**Issue by martijnpolder** [Shippable/support#2095]
We're considering migrating from Codeship to Shippable, but I appear to be running into so issues. 
Our composer.json is setup to retrieve some private repositories from bitbucket, using the snippet

```
    "repositories": [
        {
            "type": "vcs",
            "url":  "git@bitbucket.org:our_company/private_repo.git"
        },
        {
            "type": "vcs",
            "url":  "git@bitbucket.org:our_company/another_private_repo.git"
        }
    ]
```

But the build fails with

```
[RuntimeException]                                                                                                                             
  Failed to execute git clone --mirror 'git@bitbucket.org:our_organization/private_repo.git' '/home/shippable/.composer/cache/vcs/git-bitbucket.org-our_organization-private_repo.git/'  
  Cloning into bare repository '/home/shippable/.composer/cache/vcs/git-bitbucket.org-our_organization-private_repo.git'...                                          
  Permission denied (publickey).                                                                                                                 
  fatal: Could not read from remote repository.                                                                                                  
  Please make sure you have the correct access rights                                                                                            
  and the repository exists.
```

I assume the Shippable public key has to be added to the Bitbucket repositories, but using the information in http://blog.shippable.com/demystifying-shippables-deployment-keys I haven't been able to retrieve the deployment keys generated by Shippable. My settings page looks a bit different than the example though, see attachment:
![shippable_settings](https://cloud.githubusercontent.com/assets/11680755/11527214/d78d0798-98df-11e5-90cf-da8bc27d0120.png)

Where can I find my Deployment Keys?

**Comment by rageshkrishna** [comment]
We've moved things around a little since that blog post. You can now find your deployment key in the "Settings" tab on your subscription's page. This is the page you see when you click on your subscription from the "CI" dropdown on the dashboard. I hope this helps.
