### ISSUE TITLE
Builds not being triggered

### ISSUE THREAD

**Issue by czardoz** [Shippable/support#2096]
Hi,

New commits for project https://app.shippable.com/projects/55882f2cedd7f2c0522e51b1 are not being detected. What could be the issue?

-- Aniket

**Comment by manishas** [comment]
Couple of questions...

- when was the last webhook build triggered for that project? i.e. when was the last commit detected correctly and a build triggered?
- are webhook builds working for your other projects/branches?

You can try force syncing the project or even your account and see if that helps.

**Comment by manishas** [comment]
@czardoz i am closing this issue but if you are still running into this please let us know and we'll take a look.
