### ISSUE TITLE
Cache container not working.

### ISSUE THREAD

**Issue by gaumire** [Shippable/support#2098]
Hi, I have enabled **cache: true** in my shippable.yml file and have enabled **Cache Container** on the project settings page, but still I see the `before_install` step being run on every consecutive builds increasing my build time. Could there be anything else that I can do to get container caching working for me again?

**Comment by manishas** [comment]
Can you clear cache and try again? Here is an explanation of how caching works on shippable - http://blog.shippable.com/container-caching

**Comment by manishas** [comment]
we have now implemented true caching where containers are cached after every build, so this should not happen again. closing.
