### ISSUE TITLE
Failed to POST accountIntegration

### ISSUE THREAD

**Issue by bonesmccoy** [Shippable/support#2099]
Hello,

I've signed up few weeks ago for the free plan with my bitbucket account bonesmccoy and I used shippable for few days.

Suddenly It stopped working.  Now everytime I try to sign in I reached the page https://app.shippable.com/error that displays the following message:
```
Error
An error occured, please choose an action.
Failed to POST accountIntegration
```
Two buttons:  `Logout` and `Back to App` are also displayed and both brings me to the website home.

I've revoked my OAuth integration on my BB account and I've tried to repeat the sign-up process but unfortunately this procedure didn't help.
Everytime I click on 'signup with bit bucket' I have the same error.

Is this something generic or related to my account ?

many thanks

**Comment by manishas** [comment]
@bonesmccoy i will look into this and get back to you.

**Comment by bonesmccoy** [comment]
@manishas many thanks!

**Comment by pranaypareek** [comment]
@bonesmccoy we tried to reproduce this behaviour but haven't observed this happening with other BitBucket accounts. So we think this might be a stand-alone case related to your account. At the moment, it isn't be possible for us to investigate this issue independently.

Would you be able join a Hangout call this week so that we can investigate what's going wrong with your login flow?

**Comment by wmhilton** [comment]
I'm seeing this too now. :-( Logging in with BitBucket fails - worked yesterday but not today.

![screenshot_7](https://cloud.githubusercontent.com/assets/587740/11727361/673c8414-9f51-11e5-92c3-2c866f3a73a1.png)

**Comment by rageshkrishna** [comment]
@wmhilton @bonesmccoy We found a bug with the way integrations were being managed that was causing an issue during the login flow. This has been resolved now. Please try logging in once again and let us know if you see any issues. Thanks!

**Comment by bonesmccoy** [comment]
@rageshkrishna thanks a lot, now it works!
@pranaypareek  sorry I didn't see your message about the hangouts.

thanks to everyone!

**Comment by rageshkrishna** [comment]
@bonesmccoy Happy to help!

@wmhilton This should be resolved now for you, too, so I'm going to go ahead and close the issue. Feel free to open another one if you're still seeing this. Thanks!

**Comment by wmhilton** [comment]
Awesome, works again!
