### ISSUE TITLE
Language: C

### ISSUE THREAD

**Issue by larsbrinkhoff** [Shippable/support#2100]
Hello,

I'm building my project in Travis CI.  The .travis.yml file includes

    language: c

I also want to build my project in Shippable, using .travis.yml.  However that line makes Shippable fail.

**Comment by manishas** [comment]
@larsbrinkhoff we do not support C on Shippable today.

However, some folks have still run builds successfully by 'lying' about the language and saying ```language: python``` More on that [here](https://github.com/Shippable/support/issues/312), though looks like you participated in that thread.

Can you add a shippable.yml and just add the language tag and see if it works? If we find shippable.yml and .travis.yml in a repo, we ignore travis yml and run shippable.

**Comment by larsbrinkhoff** [comment]
@manishas Please consider supporting C.  Your images already have everything installed for compiling and running C programs.

If you just were to ignore `language: c`, it would work just fine.

**Comment by avinci** [comment]
We also added `language : none ` today which removes the lying part. Since C really has no setup required from our side like rvm, nvm, etc. is there anything i am missing?

**Comment by manishas** [comment]
Closing this issue. @larsbrinkhoff let us know if you have any questions.

**Comment by larsbrinkhoff** [comment]
Works great, thanks!
