### ISSUE TITLE
Need to be able to run after_success by branch

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2102]
I have a common project that as part of it's after_success it fires off seven curl calls to trigger builds that depend on it.

The problem is when using git-flow checking in a branch or sending a pull request triggers these downstream builds but they build master for each of those projects which is useless.  

I want to be able to indicate the after_success action should only be triggererd when build_branch = master.

Thanks!

**Comment by manishas** [comment]
@chriskinsman can you use the $BRANCH env variable to do this.... a few solutions are mentioned in https://github.com/Shippable/support/issues/456

Specifically if you don't want to trigger the downstream builds for pull requests as well, look at the last comment -

if [ "$BRANCH" == "master" -a "$PULL_REQUEST" == "false" ] ; then (trigger downstream builds)

**Comment by chriskinsman** [comment]
Thanks!

**Comment by chriskinsman** [comment]
Tried this:

- if [ "$BRANCH" == "master" -a "$PULL_REQUEST" == "false" ]; then curl -H "Authorization: apiToken $API_TOKEN" -H "Content-Type: application/json" -d "{\"projectId\":\"$psjobscriptsid\"}" https://api.shippable.com/workflow/triggerBuild; fi

and getting invalid yaml:

JS-YAML: bad indentation of a sequence entry at line 37, column 131:
     ... ken $API_TOKEN" -H "Content-Type: application/json" -d "{\"proje ... 
                                         ^ Invalid shippable yaml

Also tried:

- if [ "$BRANCH" == "master" -a "$PULL_REQUEST" == "false" ]; then 'curl -H "Authorization: apiToken $API_TOKEN" -H "Content-Type: application/json" -d "{\"projectId\":\"$psjobscriptsid\"}" https://api.shippable.com/workflow/triggerBuild'; fi

**Comment by trriplejay** [comment]
try wrapping your entire first example in single quotes like this:
```
- 'if [ "$BRANCH" == "master" -a "$PULL_REQUEST" == "false" ]; then curl -H "Authorization: apiToken $API_TOKEN" -H "Content-Type: application/json" -d "{\"projectId\":\"$psjobscriptsid\"}" https://api.shippable.com/workflow/triggerBuild; fi'
```

**Comment by chriskinsman** [comment]
That did it.  Thanks!
