### ISSUE TITLE
st-ci initialization scripts do not work on DO droplet

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2103]
Repro - 

- create new droplet on Digital Ocean
- For a subscription on st-ci plan, go to settings and add a node.
- Choose 'I will run initialization scripts myself', check swap, and generate scripts
- copy script to DO machine and run

I ran into multiple issues -
- first issue was that the script failed with /home/shippable not found
- i created that directory, then it failed with docker: unrecognized command

We need to look into this asap. The script needs to work on a fresh DO/EC2 machine and should have the same effect as initializing through Shippable UI.

**Comment by manishas** [comment]
Assigning to @rageshkrishna

**Comment by rageshkrishna** [comment]
This has been fixed and deployed.
