### ISSUE TITLE
cannot queue in any build

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#2105]
Hi, 

I am not able to queue in any new builds since a few minutes. The build has status "triggered" but nothing happens. 

For example: https://app.shippable.com/builds/566178dc6303cf0d00da4ceb

My last build is from 15 minutes ago. 

Please help since this is blocking for me. 

Kind Regards,
Ron

**Comment by rageshkrishna** [comment]
@rvdwijngaard I'm looking in to this right now. I will have a more detailed update in a few minutes.

**Comment by rvdwijngaard** [comment]
right, it seems that the build is running now; the build has been in the queue for quite a long time.

**Comment by rvdwijngaard** [comment]
current build is https://app.shippable.com/builds/566178dc6303cf0d00da4ceb but it seems to be very slow

**Comment by rageshkrishna** [comment]
@rvdwijngaard Things are back to stable now. Please let me know if you're still seeing this.
