### ISSUE TITLE
Build processing more than 2 hours!! Then timeout

### ISSUE THREAD

**Issue by lucidprogrammer** [Shippable/support#2106]
All other parts of the yml file succeeds. However, while running the script (velocity test-packages), it all stays there at the following step for more than 1 hour. (5661661c6303cf0d00d3e891 - project id)

velocity test-packages
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
lucidprogrammer:watson: updating npm dependencies -- watson-developer-cloud...

-------------------------------------------------------------
Finally after 2 hours, I can see the above step worked properly. but I guess it took too long, so I see the build is showing the badge timeout.

[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
lucidprogrammer:watson: updating npm dependencies -- watson-developer-cloud...
=> Started your app.

=> App running at: http://localhost:3000/

**Comment by avinci** [comment]
@ric03uec can you take a look at this

**Comment by manishas** [comment]
this is an older issue and we have upgraded our build system this week. Closing.
