### ISSUE TITLE
What is the process for getting a nodejs 4.2.2 build running?

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2107]
Should I be using the https://github.com/dry-dock/u14nodpls image?

This looks to only have 4.0.0? If I want 4.2.2 should I be submitting a pull request?

Thanks!

**Comment by manishas** [comment]
@chriskinsman we're in the process of refreshing all build images and I'll make sure we include node 4.2.2. I expect this to be available later this week or early next week.

If you need this right away, you can include a Dockerfile at the root of your repo with a FROM statement pulling from drydock/u14nodpls:prod and add install for node 4.2.2 in the Dockerfile. Set up your project to do a pre-CI Docker build. To set the node version in the yml, you can add ```nvm use 4.2.2``` in the ```before_install``` section.

Let me know if it works for you.

**Comment by chriskinsman** [comment]
@manishas  Tried that.

Build: https://app.shippable.com/builds/5667470593c4370d0004916f

As it sits now it finishes my build and then just hangs there.  I never see the image pushed to hub.docker.com nor is there any status in console...

**Comment by chriskinsman** [comment]
Got this working but have found with my image the node_js tag in shippable.yml is being ignored.

I did an nvm alias default 4.2.2 and specified it as part of the node_js: 4.2.2 element.  A node --version still shows 0.10.37 as the default.  Thoughts?

**Comment by chriskinsman** [comment]
@manishas

**Comment by chriskinsman** [comment]
Anyone?

**Comment by manishas** [comment]
sorry for the delay! i'll ask someone to take a look at this asap.

**Comment by manishas** [comment]
can you share your yml file? Did you include this in your yml -

```
before_install:
 nvm use 4.2.2
```

**Comment by chriskinsman** [comment]
Initially now.  I thought:

```
node_js: 4.2.2
```

Would work
