### ISSUE TITLE
EBS fails to deploy to EU

### ISSUE THREAD

**Issue by fabiocarneiro** [Shippable/support#2108]
Upload files to S3

```
aws s3 cp Dockerrun.aws.json.shippable.<organization>.<project>.master.445 s3://<bucket-name>
```

```bash
upload failed: ./Dockerrun.aws.json.shippable.<organization>.<project>.master.445 to s3://<bucket-name>/Dockerrun.aws.json.shippable.<organization>.<project>.master.445 A client error (InvalidRequest) occurred when calling the PutObject operation: You are attempting to operate on a bucket in a region that requires Signature Version 4.  You can fix this issue by explicitly providing the correct region location using the --region argument, the AWS_DEFAULT_REGION environment variable, or the region variable in the AWS CLI configuration file.  You can get the bucket's location by running "aws s3api get-bucket-location --bucket BUCKET".
```

![image](https://cloud.githubusercontent.com/assets/1375034/11593658/bc5825a8-9aa5-11e5-93ba-6ff5a34b1152.png)

This is managed by shippable "deployment", not by `after_success`

https://app.shippable.com/builds/5661b19755968e0d0039a85b

**Comment by avinci** [comment]
@fabiocarneiro I am not sure why this happening to your build. Can you try again with the new fix we did for #2031

**Comment by fabiocarneiro** [comment]
https://app.shippable.com/builds/5666a9f5c7f9be0c0030eaea

@avinci I don't think it is related. I moved the deployment amazon account and also region. It was working on the previous region and maybe you're not supporting eu-central-1.

**Comment by avinci** [comment]
updating issue title. I will write the sample to push to EU and see how it works

**Comment by fabiocarneiro** [comment]
@avinci 2 days already. Please.

**Comment by fabiocarneiro** [comment]
@manishas @avinci. 1 week without deployment. Please investigate it.

**Comment by avinci** [comment]
I have fixed this and tested it. I am going to be deploying this to prod in the next 20 mins and you should be able to test this.

**Comment by avinci** [comment]
production has been updated and you should be able to push to EU now
