### ISSUE TITLE
Remove project from shippable

### ISSUE THREAD

**Issue by andrehofman** [Shippable/support#2110]
Hello,

I can't seem to find how to remove a project from the shippable configuration.
I removed the webhooks from the bitbucket configuration because I wanted it to stop building the project and couldn't find the remove button.

Please help as I have a useless project in the interface now ;-(

Regards, Andre

**Comment by kanthchandra** [comment]
Hi @andrehofman, please navigate to that particular project's page and click on the settings tab (top right corner) and you should find the delete at the end of the settings page.

**Comment by andrehofman** [comment]
Awesome, overlooked that settings page entirely!

Thanks a lot kanthchandra!
