### ISSUE TITLE
Builds not doing anything

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#2111]
Builds for one of our projects seem to have just stopped running anything?

It does the "pulling image from hub" stage and then skips straight to "save reports" and "purging build container" and fails - e.g. 5666b927c7f9be0c00358e3b

**Comment by rageshkrishna** [comment]
@tomsterritt I'm starting to look in to this now.

**Comment by rageshkrishna** [comment]
@tomsterritt Our internal logs seem to indicate some sort of bash syntax error in the build script. Did you make any changes to your environment variables or any of the commands in your YML file that might have triggered this?

**Comment by tomsterritt** [comment]
Ah I put $ on all my secure vars, oops. Thanks.

**Comment by avinci** [comment]
@rageshkrishna why is this going into console? We should push all user related errors into console. Can we get this in as a fix

**Comment by manishas** [comment]
@avinci we have an open issue https://github.com/Shippable/support/issues/2079 and pranay investigated yesterday. Will forward his notes to you.
