### ISSUE TITLE
Unable to change image to pull from in project settings

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2112]
Get this message:

{"id":1004,"message":"Invalid namespace name","methodName":"|common|validateDockerImageName"}

I am attempting to set it to an image on hub.docker.com

Tried:

pushspring/u14nodpls:prod

and

https://hub.docker.com/pushspring/u14nodpls:prod

**Comment by chriskinsman** [comment]
@manishas Any ideas?

**Comment by manishas** [comment]
Looking into this...

**Comment by manishas** [comment]
do you get this while entering the above in project settings and clicking on save?

**Comment by chriskinsman** [comment]
Yes

**Comment by manishas** [comment]
weird. i tried it on a different project and it worked. Can you let me know what project you're seeing this for?

**Comment by chriskinsman** [comment]
https://app.shippable.com/projects/54a34a85d46935d5fbc137b2

**Comment by manishas** [comment]
can i try changing it for your project?

**Comment by manishas** [comment]
one thing i noticed- your image seems to be private in which case you'd need to add a hub integration

**Comment by chriskinsman** [comment]
Please.  We are going to be changing all of our projects to this one.

**Comment by chriskinsman** [comment]
I have a hub integration listed on that settings page.

**Comment by manishas** [comment]
yeah i get the same error. ok, following up....

**Comment by chriskinsman** [comment]
Also the hub.docker.com image is public...

**Comment by manishas** [comment]
i get a page not found even for pushspring...https://hub.docker.com/pushspring/

**Comment by manishas** [comment]
ok we found the issue. you had earlier turned on push build and that image name had invalid characters. When you turned push build off, we didn't clear this image name and this was actually calling the failure while saving. It should work now.

For any other projects with this problem, you can -
- turn push build on
- clear the image name 
- turn push build off again
- specify other settings
- save

one more thing - do you need pre-installed services for your project? we're making small changes to the images and wanted to make sure we have whatever you need covered.

**Comment by manishas** [comment]
@DavidGDragon we should fix this.

When someone has push build turned on and later they turn it off without clearing image name, we should clear the image name while saving settings.
