### ISSUE TITLE
Docker & --privileged --cap-add SYS_ADMIN (because of mount tmpfs)

### ISSUE THREAD

**Issue by Achse** [Shippable/support#2114]
Hi,

I would like to ask you how do you run docker image. I am trying to run tests with MySQL in `tmpfs` and because of it I probabbly need to run it with `--privileged --cap-add SYS_ADMIN`. Is it somehow possible?

Thanks for info,

Have a nice day, 
Petr

**Comment by manishas** [comment]
As of now, docker containers do not run in privileged mode on our platform.

However, your request is on our roadmap for the Single Tenant CI plan and we should have this done fairly soon.

**Comment by Achse** [comment]
Thanks for information. Really looking forward to it, because our build is really slow and with database in `tmpfs` it runs 7.5x faster on my machine.

**Comment by madebysid** [comment]
Any updates on this? We also need a way to run docker in privileged mode somehow

**Comment by manishas** [comment]
all our build container run in privileged mode with the build system upgrade. Your account should be migrated to the new system in the next ~72 hours.

**Comment by manishas** [comment]
This should be available now. Just make sure your organization is on the Continuous Delivery plan by going to the billing tab and looking at the plan name.
