### ISSUE TITLE
PHP 5.6: getenv() not working

### ISSUE THREAD

**Issue by paulgrimes1** [Shippable/support#2115]
I understand this has been opened perhaps a couple of times before; env variables are not being passed to the PHP application that's being loaded into the environment. It's a laravel 5.1 app. I've tried with laravel's env() function (which is just getenv() with a default) and PHP getenv(). Neither work; the application always reverts to defaults.

The attached anonymized YML (as txt) references an nginx setup - this is not the issue, I've done testing in an identical environment and they're picked up fine.

I've made the env vars global - is that the correct way to handle this so that the application recognises them form the env list? The doco is not super clear there.

Please let me know if you'd like me to do any further digging on this - cheers guys.

[shippable.txt](https://github.com/Shippable/support/files/57702/shippable.txt)

**Comment by rageshkrishna** [comment]
@paulgrimes1 Can you send me a project or build id that I can look at? Thanks.

**Comment by paulgrimes1** [comment]
@rageshkrishna Hi - project ID 55d666c41895ca44740ea949, the latest build attempts each try various env var output debugging.

The portion of the console output to look at is for the script item `vendor/bin/behat features/API_html.feature` - there's debug output there that says `{"error":{"code":900,"http_code":401,"message":"Auth param missing. Cannot Authenticate. HMAC is enforced::  - App env: "}}` (don't mind the fact that it's saying auth param missing, this is part of the test suite)

I am using laravel's `env()` function to echo an env var after `HMAC is enforced:: `, and standard PHP `getenv()` to try to echo an env var after `App env:`. Neither output the variable, however using a CLI `echo $APP_ENV` above it, works just fine.

Let me know if you'd like me to try anything else, or require anything extra. Cheers!

**Comment by rageshkrishna** [comment]
I don't know much about PHP, and pretty much nothing about Laravel but here's what I've figured out from some research:

It looks like Laravel's `env` helper gets values from `$_ENV`. http://stackoverflow.com/a/27077452 tells me that `$_ENV` will not be populated unless php.ini allows it. I checked against the defaults and it looks like it will not get anything from the environment. Here's what's in our php.ini:

````
variables_order = "GPCS"
````

The missing "`E`" is probably the problem. If you're using our default shippable/minv2 image to run builds, the file is located at `/home/shippable/.phpenv/versions/5.6/etc/php.ini` (substitute 5.6 with whatever version of PHP you are using).

Can you try running a build by updating php.ini. Adding the following `sed` line in your YML should do the trick:

````
before_install:
 - sed -i '/variables_order = "GPCS"/c\variables_order = "EGPCS"'  /home/shippable/.phpenv/versions/5.6/etc/php.ini
````

**Comment by paulgrimes1** [comment]
Hi @rageshkrishna,

Thanks for looking into this - great advice there on the `GPCS` setting - I was unaware of it to date. No joy unfortunately just yet. After a bit more digging I'm finding that env vars are actually being loaded OK in a different part of the application, which is strange.

I'm thinking this might something to do with the environment variables not being loaded when the PHAR (http://php.net/manual/en/intro.phar.php) script `vendor/bin/behat features/API_html.feature` is called.

In AWS elastic beanstalk (not sure about their container service, I can only speak for EC2 standard), in order to run PHAR-based commands, you need to tell the command to proactively load the env vars before calling the script. 

For example, a cron job calling the laravel-specific 'artisan' phar would be formatted as follows:
`* * * * * . /opt/elasticbeanstalk/support/envvars; /usr/bin/php artisan`

Is there an equivalent file in shippable (/opt/elasticbeanstalk/support/envvars) where I can load the environment variables to go into the phar script?

I could give that a shot and see how I fare..

**Comment by manishas** [comment]
@paulgrimes1 i am closing this issue, but please feel free to comment if you need more help and we'll reopen it.

**Comment by paulgrimes1** [comment]
@manishas Well my last question was "Is there an equivalent file in shippable" that stores the env vars in a file that a script may access when running PHP-CLI processes? If you could let me know on that one that would be great. Cheers.
