### ISSUE TITLE
Big number of random timeouts - again

### ISSUE THREAD

**Issue by pbosko** [Shippable/support#2116]
Hello,

We are experiencing the same thing we had in issue #1977. In last couple of days we had a lot of builds that timeout, although our builds usually take around 30 minutes.

Here is a list of our builds that had timeout in last few days:
https://app.shippable.com/builds/5666cd1793c4370d00e35217
https://app.shippable.com/builds/5666d939c77cdd0d00929a02
https://app.shippable.com/builds/5666d95ac7f9be0c003eac20
https://app.shippable.com/builds/5666d989c77cdd0d0092a63f
https://app.shippable.com/builds/5666e567c7f9be0c0040e2a0
https://app.shippable.com/builds/5666e858c77cdd0d00956aec
https://app.shippable.com/builds/5666eaa5c77cdd0d0095f55e
https://app.shippable.com/builds/5666fb53c77cdd0d009b721e
https://app.shippable.com/builds/5667e2ec786f130c0076585d
https://app.shippable.com/builds/56682a10de06d40d00e39c3e
https://app.shippable.com/builds/56682f5ade06d40d00e59e72
https://app.shippable.com/builds/56683415284d960d00439804
https://app.shippable.com/builds/566834c9284d960d0043d0ac
https://app.shippable.com/builds/56683714f8e64f0c00f4bc98
https://app.shippable.com/builds/56683747de06d40d00e80294
https://app.shippable.com/builds/56683dab622a050d00ea3080
https://app.shippable.com/builds/56685079d4991d0d00abdc74

I hope I won't have to be continuously manually involved in this continuous integration process. Thanks.

**Comment by avinci** [comment]
@ric03uec can you take a look at this.

**Comment by pbosko** [comment]
Here is a list for last three days:
https://app.shippable.com/builds/566ec6b6738e2e0c007e88b3
https://app.shippable.com/builds/56700c1df5d42b0d005a97e6
https://app.shippable.com/builds/56701046f5d42b0d005b3c4a
https://app.shippable.com/builds/56711ee9308acd0c00c133ea
https://app.shippable.com/builds/567156563be21f0b00c08a86

That's 13% of all builds in given period.

**Comment by ric03uec** [comment]
@pbosko i'm looking at the timed out builds now. all the timeouts seem to be happening on the `phpunit ....` command in `script` section. we're trying to figure out if the step is really 'stuck' or the actual processing is taking longer than expected for some reason. i'll post an update once i have more info

**Comment by pbosko** [comment]
We're still experiencing a high level of timeouts for builds that otherwise take 30 minutes to complete. Is there anything we can do to help you diagnose the problem?

**Comment by manishas** [comment]
This should be resolved with the new build system. I do not see timeouts in your recent build history. Please let us know if this is still happening and we will reopen.
