### ISSUE TITLE
Caching after switching to custom docker image

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2119]
We switched to a custom docker image with node 4.2.2.

We turned off caching and set our docker image.

Several builds completed.

We went back in and turned caching back on.

It is now grabbing the cached standard image instead of our standard one. 

Do we have to do the checking with [cache reset] trick?

**Comment by chriskinsman** [comment]
Anyone?

**Comment by manishas** [comment]
yes, you should reset your cache one time by going to project settings and clicking on 'Clear cache'. [reset minion] in a commit message will work as well.

Then try again. As always, it will take a few builds for the cached image to propagate to all build hosts.
