### ISSUE TITLE
Multiple platforms on one account

### ISSUE THREAD

**Issue by jamesmk** [Shippable/support#2121]
We are paying for 5 containers linked to our Bitbucket account (https://app.shippable.com/subscriptions/540f392a586ac5d7e36513c3), but we also have a couple projects on a GitHub account (https://app.shippable.com/subscriptions/546a8c11d46935d5fbbddbed). Is there a way to combine those subscriptions?

thanks

**Comment by abhijitkini** [comment]
@jamesmk Want to make sure we got your question right. You want to combine bitbucket/wearefine & github/wearefine subscriptions?

**Comment by abhijitkini** [comment]
Pricing plans are per subscriptions. The minions you have in the BitBucket subscription can be used for building repositories in that subscription only.

**Comment by jamesmk** [comment]
@abhijitkini ok, thank you
