### ISSUE TITLE
matrix values with pre-ci docker build

### ISSUE THREAD

**Issue by sleverbor** [Shippable/support#2122]
I am trying to use the docker build pre-ci flow.  I have a simple Dockerfile file that creates an image with the os I want.  I have a shippable.yml like this:

language: ruby
rvm:
      - 2.2.2
      - 2.2.3

before_script:
  - bundle install
  - bundle exec rake db:create db:schema:load

script:
  - xvfb-run -a -s "-screen 0 1920x1080x24" bundle exec rake

after_success:
  - bin/slack notify build_success

after_failure:
  - bin/slack notify build_failure

It cant find the Gemfile.

Any ideas?

**Comment by avinci** [comment]
the problem is when you use a preCI docker build, we are not setting any `rvm` settings. if you add this to your before script. it should work. 

`$SHIPPABLE_RUBY` will contain your version when the script runs. 

you add this to before script
```
rvm install $SHIPPABLE_RUBY --verify-downloads 1
. $HOME/.bashrc && . $HOME/.rvm/scripts/rvm && rvm use $SHIPPABLE_RUBY
rvm autolibs disable
rvm ls
ruby -v
gem install bundler --no-ri --no-rdoc
bundle --version
gem --version
``
This should work. let me know if otherwise
