### ISSUE TITLE
Integration API access?

### ISSUE THREAD

**Issue by tudvari** [Shippable/support#2124]
Hi guys,

I would like to ask, have you a API for the Integration configuration? It would be nice, when I can set up my Docker registry settings remotely.

Thanks in advance.

Regards,
Tibor

**Comment by manishas** [comment]
@rageshkrishna can you answer this?

**Comment by tudvari** [comment]
Hi Guys!

Do you have any update about this topic? 

Thanks in advance.

**Comment by tudvari** [comment]
Hi! 

Can you please give me any update about this? 

Thank is advance.

**Comment by DavidGDragon** [comment]
To create a Docker integration via the API, you can send a POST request to `https://api.shippable.com/accountIntegrations` with the below json body.
The only fields that you need to change are:
`"name": "IntegrationName"` to be the name of the integration
Inside `formJSONValues` change these values to your values
`"value": "dockerUserName"`
`"value": "password123"`
`"value": "myemail@company.com"`
```
{
  "masterIntegrationId": "5553a7ac3566980c00a3bf0e",
  "masterDisplayName": "Docker",
  "masterName": "Docker",
  "masterType": "hub",
  "isEnabled": true,
  "formJSONValues": [
    { "label": "username", "type": "inputSmall", "description": "username used to log into Docker Hub", "example": "janedoe", "secure": false, "value": "dockerUserName" },
    { "label": "password", "type": "password", "description": "password used to log into Docker Hub", "example": "*******", "secure": true, "value": "password123" },
    { "label": "email", "type": "inputSmall", "description": "email used in your Docker Hub Account", "example": "janedoe@outlook.com", "secure": false, "value": "myemail@company.com" }
  ],
  "name": "IntegrationName"
}
```

**Comment by manishas** [comment]
closing since this is now available with the recent service update.
