### ISSUE TITLE
Layer already being pulled by another client

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2125]
We frequently see our builds blocked on this message:

prod: Pulling from pushspring/u14nodpls
28502fae2b3c: Pulling fs layer
e463550e184d: Pulling fs layer
d9161c543ba5: Pulling fs layer
ed81929a20cb: Pulling fs layer
0273d588f6b9: Pulling fs layer
0273d588f6b9: Pulling fs layer
0273d588f6b9: Layer already being pulled by another client. Waiting.
e463550e184d: Verifying Checksum
e463550e184d: Download complete
ed81929a20cb: Verifying Checksum

Is there anyway around this?

We tried to turn on caching but we got an old cached image from before our switch to the image above.

Thanks,

**Comment by avinci** [comment]
this is docker doing it. Docker is single threaded in a lot of cases and this is its normal behavior. There is nothing that can be done at this time. 

One thing we do is reduce the layers by flattening if, if your don't need it. This will reduce it but not avoid it
