### ISSUE TITLE
Can't login in with Bitbucket.  And when I was logged in, could not see my company's projects, just my own.

### ISSUE THREAD

**Issue by calasyr** [Shippable/support#2126]
Bitbucket has been displaying this message: "We're changing our IP addresses on 15 December 2015 at 00:00 UTC. Please make sure your firewalls are up to date."

The time mentioned was only an hour ago.

**Comment by manishas** [comment]
thanks for reporting. i also get an error while signing in.... @trriplejay we need to look into this asap.

failed to fetch user profile
   at /home/shippable/www/node_modules/passport-bitbucket/lib/passport-bitbucket/strategy.js:74:28
   at passBackControl (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:409:9)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)

**Comment by calasyr** [comment]
Thanks!

**Comment by calasyr** [comment]
maybe reloading or restarting the DNS server you're using might help.  Maybe run nslookup on bitbucket.org

**Comment by manishas** [comment]
Something has definitely changed on bitbucket's end and several APi calls are failing for us. We're investigating this and in the meantime, we'll deploy a fix soon that should unblock builds.

Please stay tuned for more updates as we get more information.

**Comment by trriplejay** [comment]
We've opened a support ticket with bitbucket.  It seems likely that it's related to the IP address change, however it doesn't seem to be simply a matter of updating our own DNS lookup.  

Basically, there is a specific bitbucket API route that our passport module is using to fetch a user profile, and that particular call is failing when done via oauth. (I can manually make the exact call to the exact endpoint and get my profile back when I use basic authentication)

We're working towards finding a solution.

**Comment by calasyr** [comment]
Thanks.  Hopefully it will be resolved soon.

**Comment by trriplejay** [comment]
Actually it does look like the problem is resolved now.  Let me know if you're still having trouble.

**Comment by calasyr** [comment]
Yeah, looks like I can only see my own builds still and not my company's.

**Comment by trriplejay** [comment]
try doing a 'sync' from the account settings page.

**Comment by calasyr** [comment]
That did it, thanks.  Can see them all now.

I imagine bitbucket users will need to be informed of the need to do that.

**Comment by calasyr** [comment]
The plus icon for adding a new project is missing.

**Comment by manishas** [comment]
Please look for an 'Enable project' button. We are revamping the UI with a new style.

**Comment by pquentin** [comment]
The relevant URL is https://app.shippable.com/accountSettings. Click "Sync" on this page.

@manishas, @trriplejay: thanks for the quick fix, but this sould be done automatically!

**Comment by calasyr** [comment]
Yes, I found it, thanks.

**Comment by calasyr** [comment]
Yes, pquentin.  That makes sense.  Better that most users aren't bothered.

And, most likely, that is Shippable's plan.  They just wanted us to get our issue resolved more quickly.
