### ISSUE TITLE
Force sync button is not displayed when there are no projects in enable project page

### ISSUE THREAD

**Issue by Varsha-Arun** [Shippable/support#2131]
Steps to reproduce:
- Enable all projects under a subscription
- Fork new project from bitbucket/github
- Click on enable projects. It will display ``No projects are available to be enabled``. Search and Force sync buttons are missing. 
![selection_037](https://cloud.githubusercontent.com/assets/15084465/11833005/71dc7d88-a3e4-11e5-9b48-0979b4404cc0.png)

**Comment by manishas** [comment]
@pranaypareek @abhinavashippable can someone pick this up?

**Comment by Varsha-Arun** [comment]
Closing this issue as it is working in prod
