### ISSUE TITLE
Restore Bitbucket webhook in repository

### ISSUE THREAD

**Issue by werdlerk** [Shippable/support#2133]
Hello,

I've accidently removed the Bitbucket webhook in the Bitbucket repository and would like to have it restored. I don't know how to do this.

I've already tried removing the project from Shippable to recreate the webhook but I get the following error when I try to delete the project:
```
{"id":3300,"message":"Owner not found for projectId::563c98391895ca447422c4ef","methodName":"caller:563c9873f245fd0c00b6d686|projects|disableById:563c98391895ca447422c4ef|_getValidOwner"}
```

Can you inform me how to restore the Bitbucket integration and get Shippable running again?

Thanks!

**Comment by rageshkrishna** [comment]
Hi @werdlerk. The permission error should go away if you head over to your [account settings page](https://app.shippable.com/accountSettings) and click on the "Sync" button.

Once that is done you should be able to fix the webhook issue by going to the Settings tab on your project page and clicking on the "Reset" button near the bottom of the page. This will recreate the webhook and generate new deploy keys for your project.

**Comment by werdlerk** [comment]
Hello @rageshkrishna,

Thank you for your answer. 
I've synced my account and then tried to reset the project. Unfortunately the following error was shown after clicking the Reset + Confirm button:
```
{"id":1005,"message":"Internal API error syncProjectById for id: 563c98391895ca447422c4ef","methodName":"caller:563c9873f245fd0c00b6d686|projects|resetById:563c98391895ca447422c4ef|_syncProjectById","link":400}
```

Do you know what's wrong?

Thanks!

**Comment by rageshkrishna** [comment]
Hmm, I'll look in to this a little deeper and get back to you.

**Comment by rageshkrishna** [comment]
I have a couple of questions:

1. Can you give me the bitbucket username you use to log in to Shippable?
1. Are you an owner of the project on Bitbucket?

Thanks!

**Comment by werdlerk** [comment]
Hello @rageshkrishna,

In answer to your questions:

1. Bitbucket username I use is 'werdlerk'
2. The private repository in Bitbucket is owned by the team 'morgenwerk' where I'm an Administrator of.

**Comment by rageshkrishna** [comment]
Hi @werdlerk, did you happen to delete any of your account integrations (from the integrations tab on the account settings page)? I can't seem to find a bitbucket integration on your account, which might be why the account sync isn't correctly repopulating your permissions. All you would need to do to fix this is to logout of Shippable and log back in with your BitBucket account. The integration will get recreated automatically.

Once you do this, please sync your account once again and let me know if it helps. We do sync the account automatically on regular intervals; I'm only asking that you do this manually now to hopefully resolve the issue right away. Thanks!

**Comment by werdlerk** [comment]
Hello @rageshkrishna,
I might have done that. I've logged out and logged in again and I was able to sync the account and reset the project. Everything seems to be working again.

Thanks for your help!
