### ISSUE TITLE
Builds fail - karma throws missing .js files errors -

### ISSUE THREAD

**Issue by dkenzox** [Shippable/support#2134]
Hi guys,
Since Monday one of our projects keep failing in every build and the errors change everytime we rerun the build...the past Friday our builds ran successfully, so maybe something happened on the weekend?
It looks like karma is the problem here, maybe the info below could be of help.
There are 2 errors that seems to persists almost everytime...this one: 
`Pattern "...//libs/bower/angular-ui-utils/ui-utils.min.js" does not match any file.`
and also: 
`PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  SyntaxError: Parse error
  at .../libs/bower/angular-mocks/angular-mocks.js:1901`
Here are a few builds you could take a look: 
https://app.shippable.com/builds/5671528088e8540e001fc410
https://app.shippable.com/builds/56714bc524ad970d003d5a94
https://app.shippable.com/builds/567158e93be21f0b00c15437 (this one has karma logLevel in LOG_DEBUG)
Hopefully you will be able to help me with this.
Bests.

EDIT:
After a few more tests we are listing everything to see if the files are really missing and yes, they are.
Here is that build: https://app.shippable.com/builds/567177cd3be21f0b00c7c01f.

As an example, in the build mentioned we have a few of these errors:
`WARN [watcher]: Pattern ".../libs/bower/angular-resource/angular-resource.min.js" does not match any file.`

And in the directory where the min file should be we have this:

```
./libs/bower/angular-resource:
.
..
angular-resource.js
.bower.json
README.md
```

if I try to run the bower in my local like this 
`bower install angular-resource#~1.3`
After the instalation is completed I get this:
```
/bower-angular-resource/bower_components/angular-resource git:(master) ✗ ls -a
.                           angular-resource.min.js
..                          angular-resource.min.js.map
.bower.json                 bower.json
README.md                   index.js
angular-resource.js         package.json
```

**Comment by manishas** [comment]
I realized this completely fell off the radar. Are you still seeing this?

**Comment by manishas** [comment]
closing.
