### ISSUE TITLE
Basic questions: multiple jobs per repo, caching Maven dependencies

### ISSUE THREAD

**Issue by alain-a** [Shippable/support#2136]
Apologies if this set of basic questions has been answered before: unfortunately I did not manage to find the answers. Feel free to tell me to split the questions into several issues, if this is the way to go.

My questions;

1) I would like to be able to run multiple build jobs, just like in Jenkins where you can define
- a build job that gets triggered upon pushing to the repo
- a code static analysis job that gets  triggered upon successful completion of the build job
- an acceptance test job that gets triggered upon successful completion of the static analysis job
- etc with more complex dependencies.

I'd like also the possibility to manually re-run specific jobs.

How to do that in Shippable? For a given repo, do we have only one monolythic build job as defined by the yml file? Must we then inline and sequence all those jobs as successive operations within the yml file?

2) Right now I have a basic YAML file using Maven to build. the build is very long because dependencies are fetched every time the build is run. Is there a way to cache dependencies?

**Comment by alain-a** [comment]
nobody able to answer this after a fuill week?

**Comment by manishas** [comment]
Sorry for the long delay on this.

Wrt to running different tests on shippable, you would need to include the commands sequentially in the `ci` section of the yml. 

We are adding folder level caching and this will be announced next week.

**Comment by avinci** [comment]
We have deployed the new caching implementation to production. Docs have also been updated - http://docs.shippable.com/ci_configure/#caching-your-container

As mentioned in the docs, simply having a cache: true in the build section of the yml will result in $SHIPPABLE_BUILD_DIR being cached. You can also choose to cache specific folders using the cache_dir_list tag in addition.

'''
build:
  cache: true
  # cache_dir_list is optional. If not present, we will cache $SHIPPABLE_BUILD_DIR.
  cache_dir_list: 
    - dir1
    - dir2
    - dir3
'''
The first build you run with cache turned on might show an error during the upload cache step but the cache should be successfully pushed during the second build and be available thereafter.
