### ISSUE TITLE
Invalid docker pull command

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#2141]
Some images, such as `node` do not use a specific user identifier. The image name is just `node:5.2.0`.

However Shippable places a `/` in front, causing errors when pulling

The message is

```
  pulling image from hub
  sudo docker pull /node:5.2.0
Invalid namespace name (). Cannot be fewer than 2 or more than 255 characters.
```

I've just tested this locally, and indeed it fails this way, but it works fine without the `/`. This bug stops all of our js builds though

**Comment by rogierslag** [comment]
And example build is https://app.shippable.com/builds/5672a7fbd89a0f0c0062c7bf

**Comment by pranaypareek** [comment]
@rogierslag we are fixing this and will keep you posted as we make progress. Thanks for bringing it up!

**Comment by rogierslag** [comment]
A quick workaround seems to be to prefix the docker registry itself, so it becomes `registry.hub.docker.com/node:5.2.0`

**Comment by pranaypareek** [comment]
@rogierslag we have deployed a fix for this. The image `node:5.2.0` does get pulled the correct way now.

Do check it out and let us know if everything is fine on your end!

**Comment by manishas** [comment]
closing this issue.
