### ISSUE TITLE
No redirect to requested URI after github oauth2 login

### ISSUE THREAD

**Issue by mhzajac** [Shippable/support#2142]
Currently, if I follow a link from github pull request to a specific failing build and my session on shippable.com has expired, the browser will follow the OAuth2 login flow (through github), but once I have a session I am not redirected to the URI that was originally requested. Instead, I'm dropped in the home page with a list of all projects, so I have to go back and follow the link from github again to access the build I wanted to see. Considering my session seems to expire after a day, this happens every day. It's not a major issue, but an inconvenience as the expectation is that the server would serve up the originally requested URI, if it can.

**Comment by mbrodala** [comment]
I see the same issue with Bitbucket and there where already reports on this AFAIR.

**Comment by DavidGDragon** [comment]
We've put in a fix that should resolve the issue, please verify that the issue no longer occurs when you have the chance.

---
beta verified www 5482

**Comment by manishas** [comment]
closing.
