### ISSUE TITLE
Branch names with semicolon are not handling properly

### ISSUE THREAD

**Issue by vidyar** [Shippable/support#2143]
https://app.shippable.com/builds/5672d441d89a0f0c006bb104

Build failed without executing all steps and the build scripts shows the following for branch
![image](https://cloud.githubusercontent.com/assets/4965752/11873544/14aa4960-a501-11e5-9f68-32d51c25652c.png)

**Comment by manishas** [comment]
@vidyar please reopen if this is still happening on new build system.
