### ISSUE TITLE
Bitbucket adapter failed POST webhook

### ISSUE THREAD

**Issue by dragon00** [Shippable/support#2144]
Hello,

today I created a new Bitbucket repository and when I would like to "Enable" it on CI interface I got an error message:
```json
{"id":1004,"message":"Bitbucket adapter failed POST webhook.","methodName":"|common|bitbucket|postWebHook|<myreponame>|_postHook","link":{"statusCode":400,"data":"{\"error\": {\"fields\": {\"skip_cert_verification\": [\"This field may not be null.\"]}, \"message\": \"Bad request\"}}"}}
```
What's the problem?

**Comment by manishas** [comment]
what is your bitbucket username?

**Comment by dragon00** [comment]
gaborglazer
This repo is a private repository.

**Comment by manishas** [comment]
Thanks. We're looking into this. We've recently faced some issues with bitbucket integration as their team works through some changes. 

We're following up with them and will keep you posted.

**Comment by dragon00** [comment]
Thank you, I'm waiting for your answer!

**Comment by trriplejay** [comment]
@dragon00 this should be fixed now. Let me know if you still see any errors.

**Comment by dragon00** [comment]
It works, thanks!
