### ISSUE TITLE
BitBucket Pull Request Support

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#2146]
Hi,

Is there any idea on when Bitbucket pull-request might be implemented? They have webhooks which should giv eyou all the information you need to listnen for them.

https://blog.bitbucket.org/2015/06/24/the-new-bitbucket-webhooks/

Documentation: https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html
API resource: https://confluence.atlassian.com/bitbucket/webhooks-resource-735642279.html

Would be nice to have some info on the timeline of implementing this.

Best regards, Bjorn

**Comment by shrivara** [comment]
@bbrala This is now available. Please take a look at the [docs](http://docs.shippable.com/ci_configure/#pull-requests) for more details. Let us know if you have any questions.

**Comment by bbrala** [comment]
That is awesome :) Thanks a lot!

**Comment by mikemhenry** [comment]
Doc link is broken

**Comment by a-murphy** [comment]
The CI pull request documentation is now [here](http://docs.shippable.com/ci/pull-request-builds/).
