### ISSUE TITLE
Support command like `after_success` after hub push

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2147]
Hello,

We build our Docker images in Shippable which pushes them to GCR once they're built. However, we have to manually deploy each image to Kubernetes once Shippable has succesfully pushed it. If we had a command such as `after_push` (or anything else, really) we could:

 1. set up Slack integration to be notified of the successful push
 2. automatically deploy our images in our integration environment

Lighthouse does not seem to be an option: we are doing this to move faster and are worried that the polling-based approach is going to be too slow. And we can't use the Shippable <-> Slack integration because we only care about 1/ successful pushes of a few repositories and 2/ all build failures, not every Shippable event.

Thank you for making Shippable!

**Comment by tudvari** [comment]
I can agree with you pquentin. We also need this feature. It would be a very nic xmas gift for us. :-)

**Comment by avinci** [comment]
@pquentin @tudvari 

this is exactly what we are working on. We have this working for ECS already by mid jan we will be doing this for GKE. 

The idea behind deploy is that, doing after_push means you would need to maintain all the state management information somewhere else. name 
* what branch deploys where.
* what env configs do you want to use
* what load balancers should be routing your service traffic etc.

In addition, we have auto deploy functionality that any change to the image which creates your service you can auto deploy based on a regex. Happy to do a demo if you guys would like as we have this working 100% for AWS ECS.

**Comment by avinci** [comment]
of course, after_push is coming soon too if you don't care about all the config management etc and just want to push

**Comment by tudvari** [comment]
@avinci : Thanks for the good news. :-) In my case the only what I need is a simple webhook or callback request to a specific url. It is possible to configure the notification system to make a custom HTTP request ?

**Comment by avinci** [comment]
web hook notification is already being tested. we are using it internally for deploys. we are making it generic and exposing it to users. there is major update coming early Jan and you should see all these in that release.

**Comment by tudvari** [comment]
@avinci : Thanks for the news. I waiting for Jan. ;-)

**Comment by javiercr** [comment]
Hey @avinci any updates on this? We're in the same scenario described here. Thanks!

**Comment by pquentin** [comment]
Appears to be fixed with the new version indeed even if not fully specified. Closing in favor of #2315.
