### ISSUE TITLE
page stays blank in firefox

### ISSUE THREAD

**Issue by johannbarbie** [Shippable/support#2148]
![screenshot from 2015-12-19 08 08 59](https://cloud.githubusercontent.com/assets/659301/11911940/ee8ebac2-a627-11e5-88cd-b8ef25b9f6fa.png)

**Comment by manishas** [comment]
is this still happening? we haven;t been able to repro this.

**Comment by avinci** [comment]
We have complete redone our UI. Please let us know if this is still happening.

**Comment by manishas** [comment]
Closing this issue. Please let us know if this is still happening and we will reopen.
