### ISSUE TITLE
Node v4.2

### ISSUE THREAD

**Issue by jamesjwarren** [Shippable/support#2149]
Using node v4 in shippable fails at the `setup_ve` stage.
```
node_js:
  - 4
```
Errors:
```
nvm: install v4.2.3 failed!
WARNING: C++ compiler too old, need g++ 4.8 or clang++ 3.4 (CXX=g++)
```

**Comment by jokr** [comment]
Yes, same issue with higher versions as well.

**Comment by carlitux** [comment]
Best way could be create custom container

I did one but adding other services:

https://hub.docker.com/r/lcruzc/ubuntu1404_nodejs/~/dockerfile/

**Comment by carlitux** [comment]
If you can try I have one with just node 4 and ansible

https://hub.docker.com/r/lcruzc/ubuntu1404_node4_ansible

**Comment by manishas** [comment]
@jamesjwarren we are in the process of refreshing our build images. You can try our node image at https://hub.docker.com/r/drydock/u14nodall/. The Dockerfile for the image is at https://github.com/dry-dock/u14nodall

To use node 4.2.3, you'll need the following in your yml - 
before_install:
  - . /root/.nvm/nvm.sh && nvm use 4.2.3

Sample project is here - https://github.com/manishas/sample_node
