### ISSUE TITLE
Allow a way to skip building based on newest updated commit

### ISSUE THREAD

**Issue by asans** [Shippable/support#2150]
Sometimes, only readme or non-code related files are updated, which doesn't really require a build to be triggered for release.  

Is there a way to skip to CI if that's the case?  

Usually from what I've seen, CIs such as Travis will detect a particular phrase in your commit message, like "[skip ci]" to indicate to the CI system not to trigger a build.  

Can you guys do something like this rather than us having to implement this in our own shippable.yml?

**Comment by manishas** [comment]
Please check out our FAQ at http://docs.shippable.com/faq/

You can use 'skip ci' or 'ci skip' in your commit message to skip a build.  For PR builds the skip ci string has to be in the title of the PR title. For PR Builds with multiple commits the string should be in the PR title of the first commit.

**Comment by mbrodala** [comment]
@manishas Since the FAQ states the same: is the string looked for really `ci skip` and `skip ci`? In Travis this must be exactly `[ci skip]` which is safer from my POV. Otherwise a commit message like `Also skip circles since we only like squares` would skip a build. ;-)

**Comment by manishas** [comment]
@mbrodala you're right. we're changing this soon to require the square brackets....
