### ISSUE TITLE
Docker run test script

### ISSUE THREAD

**Issue by jamesjwarren** [Shippable/support#2151]
With the docker build pre-CI workflow, how can one run the test command inside the docker container? Just setting the command in the shippable.yml file seems to hang the build.
```
script:
  - npm test
```
There is nothing in the documentation about this: http://docs.shippable.com/docker_build/

**Comment by avinci** [comment]
@jamesjwarren we have completely revamped our build system. of course docs have been updated too.

Basically, all the stuff thats in the section below is run inside the container. 
```
build:
    ci:
    post_ci:
```

`pre_ci` sections runs outside the container as part of the prep process.
