### ISSUE TITLE
ECS cluster in eu-central not recognized.

### ISSUE THREAD

**Issue by cohenn95** [Shippable/support#2152]
shippable won't recognize my ECS cluster in region eu-central.  It recognizes ones I added in eu-west, just not eu-central.  
<img width="1164" alt="screen shot 2015-12-26 at 3 27 23 pm" src="https://cloud.githubusercontent.com/assets/10636514/12007839/33443bfc-abe5-11e5-9b19-8b820226174c.png">
My account is cohenn95.

<img width="1573" alt="screen shot 2015-12-26 at 3 24 07 pm" src="https://cloud.githubusercontent.com/assets/10636514/12007832/d6080f5e-abe4-11e5-8364-680436481ed3.png">

**Comment by manishas** [comment]
Thanks for reporting. This seems like a bug... i'll ask someone to take a look and get back to you.

**Comment by trriplejay** [comment]
this should be available now.

**Comment by manishas** [comment]
closing.
