### ISSUE TITLE
Custom Docker image

### ISSUE THREAD

**Issue by carlitux** [Shippable/support#2153]
Hi I created a custom docker but I can't connect to arangodb

https://hub.docker.com/r/lcruzc/ubuntu1404_nodejs/

how is running the docker?

**Comment by carlitux** [comment]
Getting this when running tests.

Error: connect ECONNREFUSED 127.0.0.1:8529
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

**Comment by manishas** [comment]
@carlitux did this start working for you? Your latest builds are green so want to confirm.

Thanks!

**Comment by carlitux** [comment]
@manishas yeah... I had to start service on shippable.yml

**Comment by manishas** [comment]
Yes you do need to do that if its not a standard service pre installed on our image. 

Glad it worked and sorry for the delay. It's a bit slow due to the holidays but do let us know if you need anything else.
