### ISSUE TITLE
AWS Elastic Beanstalk deployment ignores .ebextensions folder

### ISSUE THREAD

**Issue by zebehringer** [Shippable/support#2156]
I was trying to get our Elastic Beanstalk environments pulling images from our private AWS ECR repository using these instructions: https://medium.com/learnings-in-and-around-sharetribe/using-aws-ec2-container-registry-to-host-docker-images-for-deployment-with-elastic-beanstalk-b5f21c3c8e21#.b3qzsth78

I added a file named ecr.config to the .ebextensions folder at the root of my git repo and pushed that to trigger a build. The build gets triggered and succeeds, but only the Dockerrun.aws.json file is deployed to Elastic Beanstalk. I would assume that a zip file needs to be created, containing both the Dockerrun.aws.json file and the .ebextensions folder, and that deployed to Elastic Beanstalk (If I manually create a zip file with those two items and manually deploy that the Elastic Beanstalk, all works as I expect).

my bitbucket account used by Shippable is "zbehringer", and the project I just tried this on is named "Reveal_Bumpy"

**Comment by zebehringer** [comment]
my bitbucket account used by Shippable is "zbehringer", and the project I just tried this on is named "Reveal_Bumpy"

**Comment by KnowRe** [comment]
+1 for this issue. We're trying to add extra configuration in .ebextensions directory, but only the information in Dockerrun.aws.json is applied.

**Comment by rsteckler** [comment]
Same here.  The fix would be to zip up the Dockerrun.aws.json file along with the .ebextensions folder and use that to deploy the beanstalk application.
Does anyone know another way to configure the Docker host (apart from a custom AMI)?

**Comment by manishas** [comment]
We're working on a fix for this. I'll update as soon as it is available.

**Comment by KnowRe** [comment]
Is there any schedule for this? This is quite critical and we'll have to consider different deployment structure if this is not working.

**Comment by trriplejay** [comment]
This feature should now be available.  If your source contains a .ebextensions directory, the directory should be appropriately packaged and uploaded to s3, rather than just the Dockerrun by itself.

**Comment by zebehringer** [comment]
I tried it out. It did zip up all the contents of my source, including the .ebextensions folder, and deployed that to EB.
However, I was expecting the Dockerrun.aws.json file to be modified by the build script to use the Docker image built by the job, but it left that line untouched (the committed copy of that file points to the ":latest" tag of the docker image, which we store in AWS ECR). I could have sworn I saw Shippable do that before, but it has been a while, so my memory could be wrong.
Furthermore, I was also expecting the .ebignore file in my source root to be honored, but it wasn't. All I really want in the .zip file is the Dockerrun.aws.json file and the .ebextensions folder, but the zip file had everything. The _eb deploy_ command line tool does just that.
I basically am using a bash script to modify the Dockerrun.aws.json file to use the tag I want, stage that, and then call _eb deploy --staged_ to zip up and push to EB. It works, but obviously isn't automatic.

**Comment by trriplejay** [comment]
currently we're looking for some placeholders in your dockerrun file, like:
```
"name": "<IMAGE_NAME>:<TAG>"
```

as well as `<DOCKER_CONFIG>` if the image is private.

Shippable then replaces those with info from the image created in your build, so if your file had the actual image name with a tag, we wouldn't have modified it.

I'll take a closer look at the .ebignore issue.

**Comment by zebehringer** [comment]
Ah, ok. I remember that now. I'll fix my Dockerrun file. Thanks!
FYI, my .ebignore file is below. It essentially results in just the Dockerrun.aws.json and the .ebextensions folder:
`*`
`!Dockerrun.aws.json`
`!.ebextensions/*`

**Comment by manishas** [comment]
CLosing this since it was fixed.

**Comment by bobbydeveaux** [comment]
This change is broken, created an issue here:
https://github.com/Shippable/support/issues/2632
