### ISSUE TITLE
Send email from shippable images

### ISSUE THREAD

**Issue by beinnova** [Shippable/support#2157]
Hi,
I need to send email from my Node Js test, but actually I can't send. There is any special configuration to send mail from my application?

Thanks.

**Comment by mspanc** [comment]
I guess you have to use external service, such as Mandrill.

**Comment by manishas** [comment]
This isn't a standard feature offered by Shippable, so you will need to figure out if you can configure your CI workflow to do this. 

Closing since there is nothing actionable for us to do here.
