### ISSUE TITLE
CI builds stuck

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#2159]
Facing this issue today none of our github commits are getting built. We are stuck and cant do anything at the moment.

If i run a manual build, its not visible anywhere.

**Comment by rageshkrishna** [comment]
@sheldon-sminq Are you seeing this on a specific branch or is this happening for everything? Please share the project ID and branch and the latest YML file from this branch. This will help me debug further. Thanks.

**Comment by sheldon-sminq** [comment]
yes for to of my projects

Api 1.5.8
https://app.shippable.com/projects/555b31abedd7f2c052f3fcac

Backend 1.3.3
https://app.shippable.com/projects/555b31abedd7f2c052f3fcad

Even a manual build shows the build is queued but i dont see anything in
the progress view.

**Comment by rageshkrishna** [comment]
OK, I think I found the problem -- did you delete the AWS account integration that was linked to your project's EBS deployment? Looks like the validation we do to make sure the integration is not in use is broken and allowed this delete to go ahead.

Please create a new AWS integration if you haven't done it already, then head over to your project settings, delete the configured EBS deployment and create a new one that uses the new AWS integration.

I have already created internal issues to fix the delete validation and to bubble up the appropriate error message to the build console.

**Comment by sheldon-sminq** [comment]
my bad i guess i deleted it by mistake when i was exploring the AWS ECS
option, the build has started now. Thanks.

**Comment by rageshkrishna** [comment]
Glad to help. Have a happy new year! :)

**Comment by manishas** [comment]
closing,
