### ISSUE TITLE
What causes shippable to commit an image to cache?

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2161]
I am finding that if a minion is booted from cache it will not commit the additional changes back to cache.  It appears it is only committed to cache when it is first created not from cache.

Is this correct?

**Comment by DavidGDragon** [comment]
Caches are based on what host it was built on. If you haven't built on a host before, it will not have a cached version until it finishes the first build. Your build is assigned to whatever host is available at the time.

**Comment by chriskinsman** [comment]
That wasn't my question.  

When is a cache committed/updated? 

Only if a build runs on a host with no cached copy?  (This appears to be the case...)
Every time a build is run the cache on that host is updated? (This does not appear to be the case...)

**Comment by DavidGDragon** [comment]
Yes it is only the first build on that machine that is cahced. If you want to update your cache you would need to go the project settings page and clear the cache and run a new build.

**Comment by chriskinsman** [comment]
In my case I want it updated after each build.  I want to cache the results of the previous build because it has to pull down the latest packages, etc.   

I don't want to have to weekly go in and do  cache reset, etc

**Comment by manishas** [comment]
@chriskinsman a little more about caching here - http://blog.shippable.com/container-caching

In short - you're right. We only cache the first time. If you add something and want to cache again reset cache and cache will be built up again. Caching is something we're taking a second look at in the next few weeks as we evolve the platform.

**Comment by chriskinsman** [comment]
It should really update the cache with the results of the build so they are available for the next build.

In our case we want to persist the npm cache across builds to speed up npm install.

I will close now.

Thanks!
