### ISSUE TITLE
Formation - Do not see and option to add an Environment under Service setting

### ISSUE THREAD

**Issue by manish-sangani** [Shippable/support#2162]
Hi 
I purchased a Formation - Multi-tenant subscription and created a formation.
Under the settings page for Service, I don't see an option to add an environment.

According to your documentation, I should get an Environment section under Service settings page.

Is this changed or am I missing anything here?

Please help me resolve the issue.

Thanks
Manish

**Comment by manish-sangani** [comment]
i want to create different dev environment under formation.
Please help me progress further.

Thanks

**Comment by DavidGDragon** [comment]
You can no longer make additional environments, instead you create a new formation (free or paid).

**Comment by manish-sangani** [comment]
Ok, I was going through the online documentation on shippable which mentioned to add an environment.
It seems the documentation is not updated.

Anyways, I have another issue where I cannot Deploy the service.

Is formation same as a web server that my image will be deployed to?

If not, what is it that Formation used for?

Thank you,
Manish Sangani | Technical Lead
P: 212.235.5324
manish.sangani@prideglobal.com<mailto:manish.sangani@prideglobal.com>
[p_logo]
420 Lexington Avenue, Suite 2220
New York, NY 10170

**Comment by manishas** [comment]
We have deprecated Formations and replaced it with Pipelines - http://docs.shippable.com/pipelines_overview/

Please give it a shot and let us know if you run into issues. You get one pipeline free with every subscription, so it's free to try.
