### ISSUE TITLE
Single Tenant CI creation script fails

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2164]
with:

Running git clone https://github.com/Shippable/cds.git /home/shippable/cds
fatal: could not create work tree dir '/home/shippable/cds'.: Permission denied
__SH__SCRIPT_END_FAILURE__

This is on Ubuntu 14.04 LTS using the aws ami: ami-5189a661

**Comment by himanshu0503test** [comment]
@chriskinsman : Can you please try running the command as root user?

**Comment by manishas** [comment]
Closing this since this was pre build system upgrade. please let us know if you still run into this.
