### ISSUE TITLE
Duplicate Billings

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2165]
@avinci 
Each time I switch between multi-tenant and single-tenant I am being billed again for my monthly single tenant fee.  Been hit twice now...

Thanks

**Comment by manishas** [comment]
@chriskinsman I have refunded your first transaction that you canceled after a few minutes. 

You will be charged each time you sign up for multi-tenant right now. In our next release coming up in a few weeks this will no longer be a problem since we're consolidating all CI plans into one.
