### ISSUE TITLE
Status Screen only shows most recent successful build

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2166]
This means that to see a broken build I have to drill into each project.  

The main reason to look at the status screen is to show the status of the latest build and see if any have broken.  Please revert to old behavior...

**Comment by chriskinsman** [comment]
@manishas Any thoughts on this?

**Comment by mbrodala** [comment]
@chriskinsman I cannot confirm this. I always see the latest build for each project on https://app.shippable.com/, no matter if it was successful or has failed. Do you mean something else with "status screen"?

**Comment by manishas** [comment]
@chriskinsman can you send me a screenshot of the status screen where you're seeing a problem? As @mbrodala says above, we do not hide broken builds if that is latest status.

We have the following pages that show status
- Landing page - https://app.shippable.com
This shows status of the latest build for the default branch for each enabled project. If there is no default branch, it will show the status of latest build of branch `master`. If there is no master branch, it will show status of latest build (any branch).

- Subscription page
This shows the same information as landing page but only for enabled projects in the particular subscription.

- Project page
Shows status of latest build for each branch.

Also each of the above has a 'History' tab which will just show chronological list of all builds....

**Comment by chriskinsman** [comment]
It was on the subscriptions page but I am no longer seeing the behavior.  Thanks!
