### ISSUE TITLE
Project settings throw error

### ISSUE THREAD

**Issue by leovin** [Shippable/support#2168]
Navigation to project settings (https://app.shippable.com/projects/XXXXXXXXXXXX/settings) gives
{"id":3000,"message":"route permission does not match systemRoles: /projects/:projectId/settings","methodName":"validateCaller|_setSystemRoles"}.

**Comment by evra** [comment]
I'm having the same issue.

**Comment by manishas** [comment]
we're looking into this....

@evra i do not see any projects enabled in your account. can you share a link to the project page where you're seeing this?

**Comment by leovin** [comment]
I guess it's account, not project specific - error appears on all of my 3 projects, even on newly created one.

**Comment by evra** [comment]
@manishas I'm using bitbucket. Please, check the shippable account linked with ery bitbucket account.

**Comment by leovin** [comment]
https://github.com/leovin/shiptest

3 projects are on Bitbucket and the above one is on git (for test) ...

**Comment by avinci** [comment]
I have found the problem and deploying a fix. We are overhauling security system and this route was missed. I have updated it and should fix the problem. I will let you know once its in prod. should be in the next 15 minutes.

**Comment by leovin** [comment]
Good to know, thank you!

**Comment by avinci** [comment]
I have deployed it to production. Can you verify?

**Comment by leovin** [comment]
It's working, thank you!!!
