### ISSUE TITLE
I am unable to generate encrypted environment variables in shippable

### ISSUE THREAD

**Issue by iolufemi** [Shippable/support#2169]
On clicking the encrypt button, i get no response. So i checked the console and dug this out.

See console log 

```
Request URL:https://api.shippable.com/workflow/encryptString
Request Method:OPTIONS
Status Code:404 Not Found
Remote Address:XXX.XXX.XXX.XXX:443
```

**Comment by avinci** [comment]
@iolufemi I am looking into it. I have identified a bug in our latest deployment where we made some route changes. I am pushing a fix and will update in 10 minutes.

**Comment by avinci** [comment]
fix is in. Can you please check and let me know if it works.

**Comment by avinci** [comment]
verified it working and hence closing

**Comment by iolufemi** [comment]
Works now thanks.
