### ISSUE TITLE
Extend shippable.yml with "Enable Project" and docker settings

### ISSUE THREAD

**Issue by leovin** [Shippable/support#2170]
Looking at the issues, I've noticed "moving away from UI settings" trend and that is great!
Ability to drive build and packaging from configuration is a dream that's almost true with shippable :)

Do you have a plan to pimp shippable.yml with most popular UI settings?

1) "Enable Project" setting

2) Docker settings (found only "build_image" tag, looks like other settings from UI are missing in yml)

**Comment by manishas** [comment]
You're right... we're moving away from UI settings and making everything configurable from the yml.

What do you mean by 'Enable project' setting? We only look at the yml for enabled projects so not sure what you mean by that setting.... can you elaborate the scenario?

Yes to (2)... we're in the process of making our yml very powerful for docker users. You'll be able to everything you can do today and much much more just with the yml. Stay tuned :)

**Comment by leovin** [comment]
Good to know #2 is on track!

Regarding 'Enable project' setting scenario:
Imagine you fork a repo with shippable.yml, would it be nice to get a project automatically? (without going to UI in search of 'Enable Project' button)

**Comment by mbrodala** [comment]
@leovin I understand what you mean but I'd imagine this to be impossible to solve. Shippable would have to iterate over all of your VCS repositories which wheren't enabled on Shippable yet, download the `shippable.yaml` from each of them and check for the flag to enable builds.

At least I am not aware of a webhook or similar fired by VCS hosters like Github or Bitbucket whenever a repository is created which Shippable could listen for.

**Comment by leovin** [comment]
@mbrodala thank you taking time to evaluate
agree, this is not viable for now

only Github and only for organizations has such hook https://developer.github.com/v3/activity/events/types/#repositoryevent.

Asking Github and Bitbucket to extend webhooks would be to much.

Closing, and thank you once again for consideration!
