### ISSUE TITLE
Slack build notifications not triggered

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2171]
We have set up a [Slack integration for build notifications](http://docs.shippable.com/slack_notifications/) which was working well at least until December 30th, 2015. But today we are not seeing any notifications.

The builds are triggered just fine and complete successfully.

Please let me know what additional info safe to post in public you need.

**Comment by kanthchandra** [comment]
Hi @mbrodala , we have just identified an issue with our slack notification service. We're working on a fix as we speak. This should be fixed and deployed in the next couple of hours. I'll keep you posted on this. thanks!

**Comment by kanthchandra** [comment]
@mbrodala This should be fixed now and all the backed up messages must have been delivered. Thanks!

**Comment by mbrodala** [comment]
@kanthchandra Looks good, thanks for fixing. :-)
