### ISSUE TITLE
Delete Project Broken

### ISSUE THREAD

**Issue by gohanman** [Shippable/support#2173]
I'm trying to delete a project via the Delete button at the bottom of its settings tab. I repeatedly get this error message and it fails to delete the project:

```json
{"id":1005,"message":"Internal API error : removeBuilds for projectId:5577a259edd7f2c0520f4f95","methodName":"caller:5577a2a17915e70b0059432b|projects|disableById:5577a259edd7f2c0520f4f95|_removeBuilds","link":{"code":"EMFILE","errno":"EMFILE","syscall":"connect"}} 
```

**Comment by luhn** [comment]
Experiencing the same issue here.

    {"id":1005,"message":"Internal API error : removeBuilds for projectId:540e77433479c5ea8f9e8849","methodName":"caller:540e773e399939140041db94|projects|disableById:540e77433479c5ea8f9e8849|_removeBuilds","link":500}

**Comment by manishas** [comment]
@ric03uec @rageshkrishna can we take a look at this asap?

**Comment by rageshkrishna** [comment]
We've made some improvements to how this is handled. @gohanman @luhn Please give this another shot and let me know if you're still seeing the issue. Thanks, and sorry for the long turnaround time on this.

**Comment by gohanman** [comment]
On Delete, I get a spinning circle for approx. 90-120 seconds, then the page redirects to a /subscriptions/{hex} URL that still lists my project. The subscriptions page links back to a /projects/{hex} URL has the same settings tab and Delete option that I started with.

For me at least this is not terribly pressing. If it's tough to fix I can just set up a mail filter so I don't see the failed-build notifications from shippable any more.

**Comment by luhn** [comment]
I was able to successfully delete.


— Theron

**Comment by abhijitkini** [comment]
@gohanman Can you confirm if you were able to delete the project?

**Comment by gohanman** [comment]
@abhijitkini It does appear to have deleted now; just took the web UI a little while to catch up.

**Comment by abhijitkini** [comment]
Great. Thanks for the update.
