### ISSUE TITLE
How to handle sporadic issues?

### ISSUE THREAD

**Issue by baleyko** [Shippable/support#2175]
Hi guys.

I'm running built-in php server with this command in the "install" section:
`php -S 127.0.0.1:8888 -t web > /dev/null 2>&1 & echo $!`

and in the "script" section when I'm trying to make http request to 127.0.0.1:8888 with curl, I'm getting "couldn't connect to host", it's happening not all the time, but it's a most part of trying.

I've tried to add sleep after running of built-in php server, but it doesn't help.

Suggestion: Would be good to have some debug mode, when the instance is accessible through ssh for some time. What do you think about that?

**Comment by abhijitkini** [comment]
Do you have shippable_retry included in the yml?
If the issue continues, please respond with your BuildID.

**Comment by manishas** [comment]
You can use dedicated hosts with Shippable, i.e. attach your own build machines and you then have SSH access to build minions.
http://docs.shippable.com/ci_byoh/
