### ISSUE TITLE
Option for new build to cancel any running/pending builds

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2176]
We have a situation where a common library triggers builds of a number of dependent libraries.

Since the common library can have quite a few checkins we will occasionally see the number of queued builds for the dependent libraries pile up.  Frequently we will end up going in and canceling those with lower buildGroupNumbers so that we can get the final build version done more quickly.

Would be nice to specify as a build setting for a project that triggering a new build should cancel any pending and/or running builds.

This may be a controversial option since folks may want to see test output from every commit but at least in our case I am good with test output from the final build that I want to get deployed without waiting for all the interim builds to finish.

**Comment by mattclay** [comment]
I'd like to see this specifically for PRs. When a new commit is added to an existing PR, it would be very nice to have the option to cancel any previous build for that PR. This should be configurable for PRs independently of builds for commits.

**Comment by avinci** [comment]
this is getting done in next weeks launch on 5.3.2

**Comment by mattclay** [comment]
This feature was included in the 5.4.3 release: https://github.com/Shippable/support/wiki/5-4-3

**Comment by ambarish2012** [comment]
Thanks @mattclay for beating me to the update :), closing this ticket.
