### ISSUE TITLE
/workflow api returning 404

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2177]
I am trying to use the workflow api as documented here:

http://docs.shippable.com/api/

Even using the curl sample for enableRepoBuild with my own api token and project id is failing.  

Have the endpoints changed?

Seeing this for /workflow/enableRepoBuild and /workflow/disableBuild

**Comment by a-murphy** [comment]
All of the "workflow" routes were recently moved.

```POST /workflow/enableRepoBuild``` has been replaced by ```POST /projects/:projectId/enable```, where ```:projectId``` signifies the ID formerly sent in the body for the workflow route.  Nothing needs to be sent in the body for the new route.

```POST /workflow/disableBuild``` has been replaced by ```POST /projects/:projectId/disable```, where ```:projectId``` is the value previously in the body now in the route parameters instead.

```POST /workflow/cancelBuild``` has been replaced by ```POST /builds/:id/cancel```, where ``:id`` is the build group ID previously sent in the body as ```buildId```.

```POST /workflow/triggerBuild``` has been replaced by ```POST /projects/:projectId/newBuild```, where ```:projectId``` is the ID of the project to be built (formerly in the body as ```projectId```).  The other parameters in the body, such as ```branchName```, remain the same as they were for the previous route when they are used.

```POST /workflow/validateDockerHubCredentials``` was simply removed, but logging into Docker Hub with those credentials will check that they are valid equally well.

**Comment by a-murphy** [comment]
That project is not enabled, so it doesn't have a ```deployKey``` and can't run builds.  You should be able to enable it by clicking "Enable Project" on the subscription page, finding the project in the list, and clicking "Enable" or with ```POST /projects/:projectId/enable```.

**Comment by chriskinsman** [comment]
Figured out the issue.  I was filtering by name instead of full name and getting a fork that wasn't enabled.

Would be nice when calling projects to have a search option and to specify only enabled projects.  Right now a call to /projects returns 100s of items for me due to number of github repos I am connected to...

**Comment by jdextraze** [comment]
Are you guys planning on updating docs soon... http://docs.shippable.com/api/ is still showing /workflow route.
