### ISSUE TITLE
jruby-head has not been installing for some time

### ISSUE THREAD

**Issue by kaspernj** [Shippable/support#2178]
https://app.shippable.com/builds/568d456129e78a1000f41f72

**Comment by himanshu0503** [comment]
@kaspernj : We've upgraded our platform and our `ruby` image has the following ruby versions.
```
  jruby-1.7.19
  jruby-9.0.0
  ree-1.8.7
  1.8.7
  1.9.2
  1.9.3
  2.0.0
  2.1.2
  2.1.3
  2.1.4
  2.1.5
  2.2.0
  2.2.1
```
To use new features you can change your subscription plan to CD (Continuous Delivery) and convert your yml to the new format ([link](http://docs.shippable.com/ci_configure/)).
Alternatively, you can add the `build_image: drydock/u12rub:prod` in your yml to use the latest ruby image.

**Comment by manishas** [comment]
Closing since this is addressed. Please let us know if it doesn't work for you and i will reopen this issue.
