### ISSUE TITLE
site down!!

### ISSUE THREAD

**Issue by rmossuk** [Shippable/support#2182]
goto shippable and i see this error.

failed to obtain access token (status: 400 data: Could not verify OAuth request.)
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:134:36
   at /home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:465:22
   at passBackControl (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:397:13)
   at IncomingMessage.<anonymous> (/home/shippable/www/node_modules/passport-bitbucket/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:409:9)
   at IncomingMessage.emit (events.js:117:20)
   at _stream_readable.js:944:16
   at process._tickCallback (node.js:448:13)

**Comment by rmossuk** [comment]
We can now see the UI but we have no projects!

**Comment by kanthchandra** [comment]
![selection_063](https://cloud.githubusercontent.com/assets/1583444/12167512/8c37eb84-b552-11e5-9aef-bf7882b1b851.png)

It looks like bitbucket's response time for api requests is really high and as a result our connections might be timing out. We are keeping a close watch on this. 

All your projects are safe and we will be able to display them once we are able to sync permissions from Bitbucket.

**Comment by pquentin** [comment]
This has already happened in the past: https://github.com/Shippable/support/issues/1967#issuecomment-150544370

Even though @avinci said it was not Shippable bug, I think there should be something more robust to avoid being locked out every time BitBucket takes time to answer.

**Comment by godfrzero** [comment]
Same thing is happening for me. Tried the force Sync etc. mentioned in #1967, nothing helps.

**Comment by manishas** [comment]
Bitbucket has an outage - http://status.bitbucket.org/

Our issue will be resolved when their API is operational again. We will look at making this more robust but since we do not store anything other than some build information, I am not sure how useful it will be when the bitbucket api is down.

**Comment by godfrzero** [comment]
Everything seems to be stable now.

@manishas I'd probably prefer a page mentioning that the BitBucket API is misbehaving (at least) :D I was seeing 401s in some places, which got me thinking maybe I was doing something wrong as far as permissions/credentials go.

**Comment by manishas** [comment]
closing since this was due to a bitbucket api issue.

**Comment by manishas** [comment]
We have a status page now live at http://status.shippable.com :)

It also monitors some third party integrations including Atlassian Bitbucket, so this should really help detect if there is an outage.
