### ISSUE TITLE
something's wrong

### ISSUE THREAD

**Issue by sachit-singh** [Shippable/support#2183]
![shippable](https://cloud.githubusercontent.com/assets/8382151/12169510/060f8f4e-b561-11e5-8cfe-b16127803ce2.png)

**Comment by kanthchandra** [comment]
Closing this since it's a duplicate of https://github.com/Shippable/support/issues/2182. You can follow the proceedings there.

The reason for this is that Bitbucket API is taking too long to respond and our connections are timing out. We are keeping a watch on this.
