### ISSUE TITLE
Formations ECS deploy: Load Balancer configuration

### ISSUE THREAD

**Issue by cratz** [Shippable/support#2184]
I have an working cluster in ECS now I wanna use Shippable Formations to handle my 2 running services but it looks like it is not possible to configure the Load Balancer in a proper way! 

Currently Shippable sets the port where the Load Balancer is listening to the same as the container port but there is no relation between this and there is no way to configure these settings.

Is it possible to configure the listeners of the Load Balancer?

**Comment by trriplejay** [comment]
At this time we automatically configure the load balancer to listen on the same port as the container port.  

We are planning to allow the load balancer port to be customizable in the near future, but that feature is not available yet.

**Comment by cratz** [comment]
Thank you for the information!
Can you give me a hint what do you mean with "near future" because without this Shippable Formations is useless for us, unfortunately, and I have to investigate other solutions.

**Comment by trriplejay** [comment]
I'd say by early next week.  Most of the functionality is there, but not yet exposed.  I will update this issue when the functionality is available.

**Comment by trriplejay** [comment]
This feature should be available now.  In the routing section of the settings page, there is a new field called 'Exposed Port'.  This becomes the 'Load Balancer Port' on your Amazon load balancer when you deploy.

Let me know if you have any more questions or concerns!

**Comment by cratz** [comment]
Awesome it works like charm :D
Thank you very much for the fast shipment of this feature!

Last issue for us in this topic is SSL configuration for the Load Balancer. Is this already on your roadmap?

**Comment by trriplejay** [comment]
Yes, it's on our roadmap, but I'd estimate more along the lines of 3-4 weeks.  In the meantime, you can get around it by setting up SSL on AWS manually after your initial Shippable deploy (with load balancer configuration).

For example, on Shippable you can pick port 443 as your 'exposed port', and select TCP as the protocol, and click deploy.  Once your deploy is successful, you can go to AWS, switch tcp to ssl for the 'load balancer port', and choose your cert.  Any additional deploys you do from Shippable won't re-write your load balancer config unless you specifically change the settings on Shippable itself, so future deploys after that initial config should just work.

**Comment by cratz** [comment]
Thank you very much I will try it out.
