### ISSUE TITLE
Deleted single-tenant CI node still appears in UI

### ISSUE THREAD

**Issue by ttrahan** [Shippable/support#2185]
On the CI subscriptions setting page where dedicated, single-tenant nodes are managed, I deleted a node, received a horn message indicating success, but the node still appears in the list of available nodes.

See this page for the example:
https://app.shippable.com/subscriptions/563805181895ca4474226578/subscriptionsSettings

**Comment by manishas** [comment]
This shouldn't happen any more. Closing.
