### ISSUE TITLE
404 Cannot POST error when trying to trigger a build from the API

### ISSUE THREAD

**Issue by HelainSchoonjans** [Shippable/support#2188]
I have some projects whose builds were triggered from a script using using the Shippable API. This script worked flawlessly for months but I recently noticed that the builds were no longer triggered, and the POST on resulted in:
`Failed to trigger build for projectId '55cdadxxxxxxxxxxxxxxxxxx'.
Status code: 404
Response message: Cannot POST /workflow/triggerBuild`

I tried to call the API with curl, with the same result:
`$ curl -H "Authorization: apiToken mytoken" -H "Content-Type: application/json" -d '{"projectId":"55cdadxxxxxxxxxxxxxxxxxx"}' https://api.shippable.com/workflow/triggerBuild`
`Cannot POST /workflow/triggerBuild`

Other endpoints works fine however:
`$ curl -H "Authorization: apiToken mytoken"  https://api.shippable.com/projects` for example works.

Has the /workflow/triggerBuild endpoint changed? Is there a new version of the API? Or maybe are my project ids wrong?

**Comment by manishas** [comment]
Can you try the solution in https://github.com/Shippable/support/issues/2172

Sorry we're improving our API and docs are not always up to date right now. Working on fixing this.

**Comment by HelainSchoonjans** [comment]
That fixes it, thanks.

**Comment by manishas** [comment]
Thanks for confirming it worked! Closing.
