### ISSUE TITLE
MySQL client not found

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2189]
The `mysql` CLI client seems missing in the Shippable build image (at least `shippableimages/ubuntu1404_php`):

> mysql: command not found

([Example build](https://app.shippable.com/builds/568fe9514676f20f004eff63))

[The docs](http://docsv2.readthedocs.org/en/latest/config.html#mysql) suggest that the command should be there to e.g. create databases during builds:

```yaml
# MySQL binds to 127.0.0.1 by default and is started on boot. Default username is shippable with no password
# Create a DB as part of before script to use it

before_script:
    - mysql -e 'create database myapp_test;'
```

**Comment by manishas** [comment]
@mbrodala our language images are pretty barebones and do not have any services pre-installed. 

We're working on refreshing our images and php is actually the last language image we're still working on. These new images will come with services preinstalled.

ETA is early next week.

**Comment by manishas** [comment]
closing.

**Comment by mbrodala** [comment]
@manishas Thanks for the pointers, looking forward to it. :-)
