### ISSUE TITLE
Single-tenant node on Azure fails to initialize

### ISSUE THREAD

**Issue by ttrahan** [Shippable/support#2190]
The install section fails to complete when initializing a node on Azure.  Does apt-get, but fails to do install git and docker.  The cloneDNS section then fails, since git isn't installed.

![image](https://cloud.githubusercontent.com/assets/4467650/12208820/0a1d89f8-b604-11e5-8420-def402a70147.png)

**Comment by manishas** [comment]
@abhinavashippable can you take a look at this?

**Comment by abhinavashippable** [comment]
I used Virtual Machine (Classic) from Azure and I am able to successfully initialize the node.
![builds_beta_running](https://cloud.githubusercontent.com/assets/11938017/12259741/bb6c0f90-b93d-11e5-9174-77281ca4f273.png)

**Comment by ttrahan** [comment]
Looks like it was a point-in-time issue.  I was able to re-initialize the node successfully today, which didn't work on Friday.
