### ISSUE TITLE
Example Tutorial

### ISSUE THREAD

**Issue by akamalov** [Shippable/support#2191]
Hello,

I am using an example tutorial - https://github.com/shippabledemo/radar-www2 provided by Shippable. So far, I have created my integration point with AWS EB, and Shippable build completes successfully. However, I do not see any evidence that a container has been pushed out to EB or even build image pushed. What is it am I doing wrong ?

Thanks,

Alex

**Comment by abhijitkini** [comment]
Please use the latest step-wise instructions for the end to end workflow.
http://blog.shippable.com/shippable-continuous-delivery-to-amazon-ec2-container-services-0

**Comment by akamalov** [comment]
Thank you! I will give it a shot!

Alex

**Comment by abhijitkini** [comment]
@akamalov here is an even more relevant one, directly related to deploying containers to Elastic Beanstalk
http://blog.shippable.com/deploying-containers-to-elastic-beanstalk-the-shippable-way.

Let us know if you continue to see an issue.

**Comment by akamalov** [comment]
Thanks a ton!!!

Alex

**Comment by akamalov** [comment]
I think I did follow this guide to deploy sample "radar-www2" app when I
encountered the error. It just wouldn't deploy. Builds it find but when it
comes to deploying, nothing gets pushed out.

**Comment by abhijitkini** [comment]
@akamalov Could you double check the Docker Options settings & compare it to the settings shown in http://blog.shippable.com/deploying-containers-to-elastic-beanstalk-the-shippable-way.

You will also need to complete Step 3: Create Dockerrun.aws.json

**Comment by manishas** [comment]
Closing this issue because there is nothing actionable to do here.
