### ISSUE TITLE
Can't login or enable using my Bitbucket account.

### ISSUE THREAD

**Issue by brampey** [Shippable/support#2192]
I'm not sure what triggered this issue.  I've been using my login for Bitbucket for quite some time.  However, sometime in the last couple days I'm seeing an error while logging in using my Bitbucket account.   I've attached two screen shots.   One is when I choose login from the Shippable home page.   It's the error "Failed to POST accountintegration".   The other one is the error I see when I login with my GitHub account and then click the Bitbucket "Enable" button under my account settings. 
![screen shot 2016-01-10 at 12 11 05 pm](https://cloud.githubusercontent.com/assets/398839/12222769/338b3984-b794-11e5-86b0-44d820230355.png)
![screen shot 2016-01-10 at 12 15 08 pm](https://cloud.githubusercontent.com/assets/398839/12222770/338f1748-b794-11e5-857b-4c6aaf3c0c6f.png)

**Comment by ric03uec** [comment]
@brampey can you please try to login again. There was some issue with the bitbucket integration for your account. the login should work now.

**Comment by brampey** [comment]
Thank you!  Appears to be working now.
