### ISSUE TITLE
How to obtain an api key ? 

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#2193]
Hi, 

I want to use the shippable api to improve my processes. In the documentation I read that you can generate an api key from the profile page. In my case Api Tokens are grayed out because I am not part of an paid account. That's not completely true because we have an paid account for our company but my personal account isn't paid. How does this work? 

Kind Regards,
Ron

**Comment by manishas** [comment]
@ric03uec  can you look into this?

**Comment by ric03uec** [comment]
@rvdwijngaard your account seems to be linked with two subscriptions, one of which is an organization. But the organization is still on the free plan because of which the api token is not available.
Can you please verify if the org subscription is a paid one or not.
thanks

**Comment by manishas** [comment]
closing.
