### ISSUE TITLE
Getting image modified emails after running PR builds

### ISSUE THREAD

**Issue by vidyar** [Shippable/support#2194]
To repro:
- Configure the project with preci-docker build options and turn on lighthouse notifications from project settings
![image](https://cloud.githubusercontent.com/assets/4965752/12235388/7c939ab2-b899-11e5-8b9a-c9b3cf31b64d.png)

-  Watch the same image from Lighthouse page and turn on notifications
-  Run a PR build. You will get an image modified email notification immediately.

**Comment by manishas** [comment]
@pranaypareek can you look into this?

**Comment by pranaypareek** [comment]
Made the fix and tried this out in `beta`. This doesn't seem to be happening anymore.

**Comment by vidyar** [comment]
Not getting  image modified emails after running PR builds in prod now. Hence closing this issue.
