### ISSUE TITLE
Builds not trigger automatically for non-master branches

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#2196]
My shippable.yaml looks like this
```
branches:
  only:
    - master
    - stable
    - release
```

But for `stable` and `release` branches builds are not getting triggered automatically. Is there any change in configuration, I have to sync up with ?

**Comment by phagunbaya** [comment]
Though the builds for pull requests are working fine but not for push commits.

**Comment by manishas** [comment]
do the `stable` and `release` branches have shippable.yml with the same branch config?

**Comment by phagunbaya** [comment]
@manishas Yes

**Comment by pranaypareek** [comment]
@phagunbaya we are investigating this issue right now. We'll keep you posted!

**Comment by pranaypareek** [comment]
@phagunbaya I wasn't able to reproduce the issue you're facing. I tried this out with one of our sample projects (https://github.com/pranaypareek/sample_node_mongo/blob/master/shippable.yml).

* Created 2 more branches (you can find them at the link above) called `b1_for_auto_build` and `b2_for_auto_build`.

* Updated the `shippable.yml` (on the `master` branch) with
```
branches:
  only:
    - master
    - b2_for_auto_build
```

* Updated the `shippable.yml` for the new branches as well.

* Pushed a new commit for all three branches.

* I could see builds getting triggered automatically for `master` and `b2_for_auto_build`  branches.

Do you think something might be different for your project?

Also, if you're okay with it, a look at your `shippable.yml` might give us another lead. You may send it over at `pranay@shippable.com`. Thanks!

**Comment by pranaypareek** [comment]
@phagunbaya please re-open if you're still facing the problem. Thanks for reaching out!
