### ISSUE TITLE
How to build a docker image and push to registry?

### ISSUE THREAD

**Issue by maxfi** [Shippable/support#2197]
I would like to simply build a docker image from the `Dockerfile` in the root of my project and on successful build push it to Docker Hub or ideally to the [Tutum](http://www.tutum.co) registry. At the moment I don't require running any tests.

At present I have the following:

shippable.yml
```
script:
  - true
branches:
  only:
    - develop
```

and project settings
![screen](https://cloud.githubusercontent.com/assets/2127381/12261317/3c7dddd0-b95b-11e5-9979-b1a401a4a7e8.png)

Am I going about this the right way or is there a more streamlined way of doing this?

**Comment by cratz** [comment]
I use exactly this way to build the image and push it to docker hub. Works like charm.

**Comment by maxfi** [comment]
Thanks @cratz. Thought there might be someway to speed it up? Perhaps cacheing the intermediate containers?

**Comment by cratz** [comment]
The build speed depends heavily on your Dockerfile.
And shippable has a very good reason to not cache all intermediate containers check out this:
http://blog.shippable.com/container-caching

**Comment by maxfi** [comment]
Thanks for the link @cratz. It appears to me that the article relates more to the pre-ci build order though? If all I'm doing is building from a Dockerfile (one designed for caching itermediate containers) does this also apply?

**Comment by cratz** [comment]
As far as I understand there is no difference between post/pre-ci build in terms of caching.

If you don't care for script results and you wanna only build after a push to e.g. github you could use docker-hub's own functionality (" Create Automated Build"). I use this as well and in docker hub all itermediate containers are cached.

**Comment by maxfi** [comment]
I've been having issues with Docker Hub's Automated Builds and will likely use Shippable's extra scripting capabilities down the track. I'll try out the cache option on Shippable and see if it works for my needs. Thanks again for your assistance @cratz!
