### ISSUE TITLE
Automate production builds

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#2199]
I have integrated shippable with my development pipeline to deploy docker updates to our staging environment after every commit, this works well with the team members and new features are always ready to test.

I was wondering how to automate the deployment of a production build, since my production Docker files are different i currently do a manual docker build and push. And in AWS elastic beanstalk upload the Dockerrun zip file manually.

**Comment by manishas** [comment]
@sheldon-sminq do you still need help with this?

Our new API is published here - http://docs.shippable.com/api/ There are still some routes that are undocumented, so let us know if you need help figuring out how to configure your scenario.
