### ISSUE TITLE
Console log improvements

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2207]
Within the Shippable build environment apparently `stdout` doesn't seem to be a proper TTY.

Due to this code checking for this to e.g. [determine whether color output is supported](https://github.com/symfony/symfony/issues/17360), fails.

Is it possible for Shippable to expose `stdout` as proper TTY?

**Comment by manishas** [comment]
@kanthchandra can we do this while working on our new console?

**Comment by kanthchandra** [comment]
@manishas I dont think this is a frontend issue. I think it is related to the way we spin up the docker containers which execute the build scripts. So we will need to take a look at this deeper and see if it is actually feasible to do this.

**Comment by mbrodala** [comment]
Small update: we can enforce color output for Symfony console apps via `--ansi` and for PHPUnit with `--colors=always` (or `<colors>always</colors>` in `phpunit.xml`).

**Comment by mbrodala** [comment]
Notice that this does not work anymore after the infrastructure changes yesterday. We are now seeing raw color escape sequences in our [build logs](https://app.shippable.com/runs/56d567673e79a20c00a74cc7).

Are there plans to bring back the color output?

**Comment by mbrodala** [comment]
@manishas Are there any updates here? I know it's not a dealbreaker but all of my colleagues have asked me already where all the pretty colors have gone. ;-)

(Please compare [this old build](https://app.shippable.com/builds/56975facecdf4f0d008bcd3f) before the architecture switch with [this current build](https://app.shippable.com/runs/56e295c456582c0c005abe2c).)

**Comment by manishas** [comment]
@mbrodala we'll look into this... thanks for the build links :)

**Comment by shrivara** [comment]
@mbrodala We've added support for ansi colors. I'll update here once its live.

**Comment by shrivara** [comment]
@mbrodala This is live now. Feel free to reopen if you find any problems with it.

**Comment by mbrodala** [comment]
@shrivara Works wonderful. And it's awesome that this also fixes all existing build logs. Great work.

**Comment by mbrodala** [comment]
@shrivara Is it possible to fix the initial issue and have `stdout` exposed as regular TTY so that ANSI color output works in every CLI tool out of the box?

**Comment by shrivara** [comment]
@mbrodala We're taking a look at this and will get back to you.

**Comment by manishas** [comment]
I'm going to consolidate all console log improvements in this issue so that we can pick it up one time and work through it.

Related issues:

https://github.com/Shippable/support/issues/2574

**Comment by mbrodala** [comment]
We won't be using Shippable anymore.

But thanks so far!
