### ISSUE TITLE
build started failing: ssh-agent command not found

### ISSUE THREAD

**Issue by manish-sangani** [Shippable/support#2208]
Hi,

all of sudden my builds started failing.
It throws an error below when trying git_sync

/root/3a76c3c6-f700-4285-b453-ad300c1ceacb.sh: line 84: ssh-agent: command not found

Please help as we are stuck.

Thanks

**Comment by ric03uec** [comment]
@manish-sangani can you provide us with the build id(or project id) for which this is happening

**Comment by manishas** [comment]
@ric03uec project id is 565cb94c1895ca447424fe77

**Comment by manish-sangani** [comment]
where do i find build id?

**Comment by manish-sangani** [comment]
I found it...
Here is the project id 565cb94b1895ca447424fe75

**Comment by manish-sangani** [comment]
Build id given by manishas is correct.

**Comment by manish-sangani** [comment]
@manishas , @ric03uec 
Latest build failed - 5697eae19188220d00817c5c

**Comment by ric03uecS** [comment]
@manish-sangani can you verify if the image you're running the builds on has `ssh-agent` installed. I didn't find any ssh agent installation logs in docker build.
 Shippable images have it installed by default so the commands work as expected.

**Comment by manish-sangani** [comment]
@ric03uec 
I ran so many builds without adding ssh-agent.
Is there anything changed in shippable?

I do see the Docker configuration section is changed.

**Comment by ric03uec** [comment]
my observations from the build history for the project `565cb94c1895ca447424fe77`
- up till build number 67, the project was using `shippable/minv2` which has ssh-agent installed
- build 69 did a pre-ci docker build which passed. For pre-ci builds, we clone the repo outside the container, use the `Dockerfile` in the repo to build the image and then run the build by mounting the code inside the image, so the code is checked out **outside** the image being built
- build 70 did the same, and passed
- build 74 (the one that fails with `ssh-agent` error) is trying to use a custom image to run the build. This means that the shippable will try to clone the repo **inside** the image for which `ssh-agent` command should be present in that image

**Comment by manish-sangani** [comment]
ok, I used shippable image as a base image and it worked.

Thanks
