### ISSUE TITLE
Formation - does not pickup the latest image from dockerhub

### ISSUE THREAD

**Issue by manish-sangani** [Shippable/support#2209]
Hi
I have configured Formation service to pull a docker image from docker hub but when creating a new image, I don't see the latest image available from Dockerhub.

What could have I done wrong?

Fromation service id - 568fe12c4676f20f004c9057

Please let me know.

Thanks

**Comment by trriplejay** [comment]
Do you build the image from Shippable CI? if so, make sure your "Lighthouse Notifications" section is set to "on".  If not, then you'll need to click the "sync" button in order to fetch the latest tags for that image.

**Comment by manish-sangani** [comment]
@trriplejay - Yes I build the image from shippable CI and Lighthouse Notifications is on.
When I do sync, it still brings up the list of image which is 22 days old and some of them do not even exist.

Thanks

**Comment by manish-sangani** [comment]
Is there anything I am missing here?
Can you assist me to resolve the issue?

Thanks

**Comment by trriplejay** [comment]
It looks like a bug on our end.  We've got an issue opened to resolve it.  In the meantime, I should be able to fix your particular case shortly.  I'll update again when I've resolved your particular case.

**Comment by trriplejay** [comment]
@manish-sangani Your service should be fixed now.

**Comment by trriplejay** [comment]
This bug can still happen if you delete tags from docker hub, but I'll update this issue again when our fix for that bug is released.

**Comment by manish-sangani** [comment]
Thanks, I will check and let you know by tomorrow.

Manish
On Jan 14, 2016, at 5:52 PM, John Stockbauer <notifications@github.com<mailto:notifications@github.com>> wrote:


This bug can still happen if you delete tags from docker hub, but I'll update this issue again when our fix for that bug is released.

**Comment by trriplejay** [comment]
The issue should now be resolved.

**Comment by manish-sangani** [comment]
Thanks
