### ISSUE TITLE
Formation - Service is running using AWS - EC2

### ISSUE THREAD

**Issue by manish-sangani** [Shippable/support#2211]
Hi,

I have created a service in Formation using AWS.  I successfully deployed docker image to a a cluster but when I hit the url it times out.

What could be the issue?

Service id - 568fe12c4676f20f004c9057

**Comment by trriplejay** [comment]
Hello,

Based on your event list (the 'events' tab, next to 'history' on the formationService status page) it looks to me like your EC2 instances are not correctly configured to be associated with your ECS cluster.

I recommend having a look at this page:
[http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html] (http://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html) 
which details how to bring up an EC2 instance specifically for use with ECS.

**Comment by manishas** [comment]
Formations is now deprecated as part of our latest release. Please look into using pipelines instead - http://docs.shippable.com/pipelines_overview/

We're always happy to jump on a hangout and help if needed.
