### ISSUE TITLE
Private Python-based repository consistently fails on pip install

### ISSUE THREAD

**Issue by pwalsh** [Shippable/support#2214]
I have a private GitHub repository that always fails on install with:

```
pip install --upgrade -r requirements/base.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements/base.txt'
Storing debug log for failure in /root/.pip/pip.log
```

The file exists. The shippable.yaml is:

```
language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install --upgrade -r requirements/base.txt
  - pip install --upgrade -r requirements/test.txt

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage

script:
  - PYTHONPATH=. py.test --cov hamigdalor --cov-config .coveragerc --cov-report xml --junitxml=shippable/testresults/tests.xml

notifications:
  email:
   - {EMAIL}
```

I use the exact same setup on another [public repo](https://github.com/okfn/goodtables/blob/master/shippable.yaml) and it works fine.

For shippable support: the project number is: `54b9035d5ab6cc135288d36f `

**Comment by abhijitkini** [comment]
By default, we will only ask for access to public repos. If you want to use Shippable to build your private repos, you will need to authorize us for private repositories. Could you check the account settings for private repos?

Here is a document for your reference: http://docs.shippable.com/account_settings/

**Comment by manishas** [comment]
@pwalsh i think @abhijitkini misunderstood. You do have private repos turned on.

We'll look into this problem and get back to you.

**Comment by pwalsh** [comment]
@manishas yes, please.

**Comment by manishas** [comment]
@pwalsh you're using a custom image for the private repo build. can you send me a screenshot of your project settings for docker options to manisha@shippable.com?

**Comment by manishas** [comment]
@pwalsh also your Dockerfile for the image you're building will be helpful to debug further. 

 We expect that your Dockerfile will copy your source repository into the new image and the ```Source location``` field in Project settings->Docker options should be the directory to which it was copied.

**Comment by pwalsh** [comment]
Ah, so the last point is it: I have no configured a source location via the shippable UI.
