### ISSUE TITLE
Billing page bugs

### ISSUE THREAD

**Issue by manishas** [Shippable/support#2215]
Once I buy a plan, if i go back to the billing page, i only see the following -
![screen shot 2016-01-18 at 3 15 39 am](https://cloud.githubusercontent.com/assets/2983749/12390119/270db2f0-bd92-11e5-8300-05be760ea8a5.png)

-  There is no way to change the card associated with a CI subscription without changing the number of minions.
- There is no way to update billing email without changing number of minions.

We need to address these issues. To do this,

- Show all values, including card and billing email, as read only when a user lands on the billing page. At the bottom, show a button - Update plan
- When the user clicks on update, he can make changes to the plan. This includes changing the slider, changing billing email, or changing the card associated. He sees 2 buttons - Save plan and Cancel. Save plan is greyed out until be makes a change.
- Once he makes any changes, he the Save plan button is enabled and the changes are saved. Changes to billing email or card should not trigger a purchase.
- He can also cancel out of this action at any time and nothing is saved.

**Comment by DavidGDragon** [comment]
I noticed that you can't see you invoices unless you click 'update plan' and thought that was confusing. Was this intended?

**Comment by manishas** [comment]
no, not intended. if a user has invoices they should always see them.

**Comment by amalfra** [comment]
Okay. Would fix it now.

**Comment by amalfra** [comment]
Bug has been fixed. Now invoices and delete subscription in formation billing are always shown.

**Comment by manishas** [comment]
this is complete. closing.
