### ISSUE TITLE
SNI not working with Composer

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2216]
Currently [some](https://app.shippable.com/builds/569cea6011bbb80c00493a5e) of our builds fail with the following error:

```
[RuntimeException]                                                                                                                                          
  The "https://get.typo3.org/json" file could not be downloaded: Peer certificate CN=`ssl340684.cloudflaressl.com' did not match expected CN=`get.typo3.org'  
  Failed to enable crypto                                                                                                                                     
  failed to open stream: operation failed   
```

It seems like the [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) is not working in the Shippable build environment. Can you please check what is necessary here?

**Comment by eyecatchup** [comment]
@mbrodala Are you sure it is related to the Shippable build environment? We experience the exact same issue for all our project builds since yesterday evening. And we are _not_ in a Shippable build environment. Don't you think this issue is rather related to TYPO3?

**Comment by mbrodala** [comment]
@eyecatchup Your suggestion seems correct, I just found [this issue in Composer](https://github.com/composer/composer/issues/4782) which talks about this. They have worked around the problem for `github.com` but it still affects other hosts. (See the [current implementation](https://github.com/composer/composer/blob/546730dcf3da4d2689664116c0639655aa428b6b/src/Composer/Util/RemoteFilesystem.php#L525).)

Closing this one.

**Comment by eyecatchup** [comment]
@mbrodala FYI: We "solved" this for now by rolling back to composer version `2015-03-25_14-32-49-8cfd48c`.

**Comment by mbrodala** [comment]
@eyecatchup Thanks for the info. I don't see a related change in that or its directly following commits. Did you find the commit which broke this?

**Comment by eyecatchup** [comment]
@mbrodala Sorry, we didn't checked the commits. We just rolled back to this specific version since it was the version that was running on our Jenkins before we self-updated yesterday.

**Comment by BenjaminBeck** [comment]
Same here. To execute "php ./composer.phar create-project typo3/cms-base-distribution CmsBaseDistribution62 6.2.x-dev" i used a older composer.phar. The error message with the current release was:
```
[RuntimeException]                                                                                                                                          
  The "https://get.typo3.org/json" file could not be downloaded: Peer certificate CN=`ssl340682.cloudflaressl.com' did not match expected CN=`get.typo3.org'  
  Failed to enable crypto                                                                                                                                     
  failed to open stream: operation failed   
```
