### ISSUE TITLE
Can't see any option at CI's menu

### ISSUE THREAD

**Issue by lmvalenzuela** [Shippable/support#2217]
I've tried using 3 different browsers (Chrome, Firefox and Safari) and can't pick any option from de CI menu.
![captura de pantalla 2016-01-19 a las 11 29 54](https://cloud.githubusercontent.com/assets/15267361/12426615/2e3b1c0c-bea0-11e5-9ed1-efd4418276e4.png)

**Comment by trriplejay** [comment]
Try going to the 'account settings' page and clicking the 'sync' button under 'account information'
https://app.shippable.com/accountSettings

**Comment by trriplejay** [comment]
also, we only sync public repos by default for Github.  If you want to see private repos, you'll have to click 'enable' button for private access on that same account settings page. in the 'Git identities' section.

**Comment by lmvalenzuela** [comment]
Already done it and still don’t see anything. Even I granted access to my organization repos at github.
Regards.

Luis Miguel Valenzuela Arteaga
IT & Infraestructure


T 5250.8088 ext. 812 / M 044.55.6612.5008
Shakespeare #30 Piso 8, Col. Anzures, México D.F.
ktcagency.com <http://www.ktcagency.com/?utm_source=Firma_ktc&utm_medium=Email&utm_campaign=ktcagency>    -    thoughts.ktcagency.com <http://thoughts.ktcagency.com/?utm_source=Firma_ktc&utm_medium=Email&utm_campaign=thoughts>

Ya está disponible la nueva edición de nuestro BLOG: "10 años de transformación digital". <http://thoughts.ktcagency.com/>
Conoce nuestros reconocimientos en FWA <http://www.thefwa.com/shortlist/ktc> y AWWWARDS <http://www.awwwards.com/best-websites/ktc/>

**Comment by trriplejay** [comment]
Your projects should be available now.  I think your account needed to be sync'ed again after you enabled the private scope.  We should probably be doing this automatically, but it looks like we aren't at this time.

**Comment by lmvalenzuela** [comment]
Corrected !
Thanks

Luis Miguel Valenzuela Arteaga
IT & Infraestructure


T 5250.8088 ext. 812 / M 044.55.6612.5008
Shakespeare #30 Piso 8, Col. Anzures, México D.F.
ktcagency.com <http://www.ktcagency.com/?utm_source=Firma_ktc&utm_medium=Email&utm_campaign=ktcagency>    -    thoughts.ktcagency.com <http://thoughts.ktcagency.com/?utm_source=Firma_ktc&utm_medium=Email&utm_campaign=thoughts>

Ya está disponible la nueva edición de nuestro BLOG: "10 años de transformación digital". <http://thoughts.ktcagency.com/>
Conoce nuestros reconocimientos en FWA <http://www.thefwa.com/shortlist/ktc> y AWWWARDS <http://www.awwwards.com/best-websites/ktc/>

**Comment by olegsinyavskiy** [comment]
The same issue. Every new sync in account settings added something. But I had to synchronize 4 times before I saw the project I wanted.

**Comment by manishas** [comment]
@rageshkrishna can we get this fixed asap? Looks like this is affecting new accounts and customers cannot see their subscriptions until they force sync the account.

**Comment by rageshkrishna** [comment]
We're on it. I think we'll have a fix deployed very soon.

**Comment by avinci** [comment]
@spsiddarthan i think this is fixed. Please post a comment when you change labels..so that everyone is updated.

**Comment by spsiddarthan** [comment]
@avinci, Will do. This is fixed and will be available in the next deployment.

**Comment by russel** [comment]
I am not sure if this is the same issue as this one or whether another issue needs to be raised.

I just set up an account and connected to BitBucket, but only my private repository shows when trying to set up CI. The CI I want is on a public repository. Have I just missed a setting?

**Comment by spsiddarthan** [comment]
@russel, Could you please try syncing your account from the account settings page and see if all the repositories you want to see show up?

**Comment by spsiddarthan** [comment]
This should be fixed now, please let us know if you still see a problem.
