### ISSUE TITLE
Builds failing due to IO issues

### ISSUE THREAD

**Issue by robby-phd** [Shippable/support#2218]
Somehow my builds that use a custom Docker image started failing today due to IO issues.
The first failing build is: https://app.shippable.com/builds/569fb0a0bcc57e0d008185f6
It was working fine the day before: https://app.shippable.com/builds/569e659cdbbd510d00c377ec
I tried clearing the container cache and created a new Docker image but to no avail.

**Comment by robby-phd** [comment]
I disabled caching and it seems to be working again: https://app.shippable.com/builds/569fe1ba316dcf0c00212eb6
Not sure it's works now because of that.

**Comment by robby-phd** [comment]
Reopening this issue because caching is not the issue as my builds are failing again (e.g., https://app.shippable.com/builds/56a10ca56110700c00d43e85 and https://app.shippable.com/builds/56a18dba6110700c00edd6ad).

**Comment by rageshkrishna** [comment]
I'm not an sbt expert by any stretch of the imagination, but this might be a problem in sbt itself: https://github.com/sbt/sbt/issues/2156

**Comment by robby-phd** [comment]
Thanks for the response and the pointer. It does look like a problem in Sbt (or a Sbt plugin that the build uses). It's interesting that it never happens in my local build. At any rate, I'm closing this again since this does not seem to be shippable's issue (sorry for the noise).
