### ISSUE TITLE
Build ID 0 stuck in my status page

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#2219]
It's nothing that prevents shippable from using but build with ID 0 (added initially after syncing empty repo) is stuck in my status page.

Subscription ID: 569a6b151895ca44746ffea2

![zrzut ekranu 2016-01-21 o 10 15 59](https://cloud.githubusercontent.com/assets/389651/12476250/4ef26688-c028-11e5-9c0c-01912ccca90a.png)

**Comment by cratz** [comment]
I have the same issue with one of my projects when I visit the CI-page of the organization and the project is not visible at all on the home page within the `Continuous Integration` section.

Subscription ID `56406c941895ca4474230170`

**Comment by cratz** [comment]
@manishas any news on this topic?
Thanks!

btw. Have you ever been thinking about using [Gitter](https://gitter.im/) as a support channel?

**Comment by manishas** [comment]
@harryi3t we need to look into this as well.

**Comment by cratz** [comment]
@manishas 
Looks like this is fixed now at least for us.

**Comment by manishas** [comment]
This should be fixed now on the new build system. Please let us know if it happens again after your subscription is migrated to the new system (i.e. plan name in Billing tab is 'Continuous Delivery').
