### ISSUE TITLE
Unable to initialize a single tenant node because git is not installed

### ISSUE THREAD

**Issue by himanshu0503** [Shippable/support#2220]
![selection_036](https://cloud.githubusercontent.com/assets/2168263/12479733/34211aa8-c063-11e5-8dfc-55818f1cc6d8.png)

**Comment by rageshkrishna** [comment]
Looks like the install didn't complete, similar to what @ttrahan saw a few days ago.

**Comment by manishas** [comment]
@himanshu0503 is this still happening?
