### ISSUE TITLE
Builds timing out

### ISSUE THREAD

**Issue by copyhawk** [Shippable/support#2221]
Most of my builds lately seem to be timing out. Is there any setting I'm forgetting or getting wrong?

Last Build: https://app.shippable.com/builds/569fa6646110700c009af44e

**Comment by realAkhmed** [comment]
If this is a Dockerbuild then I am experiencing a similar issue #2212

**Comment by trriplejay** [comment]
@copyhawk based on your logs for the build you linked, it looks like some error in your test is causing your script to wait.  If you look at the timestamps, the script retries something every 5 minutes or so.  Eventually you hit shippable's timeout limit and we stop the build.

**Comment by copyhawk** [comment]
@trriplejay thanks for the help. Just notices a bug was introduced that was causing this long wait.
