### ISSUE TITLE
Not able to set exposed port on container

### ISSUE THREAD

**Issue by hip911** [Shippable/support#2224]
Hi

I am playing around with the 'Formation' feature. When I select an image within my service, I'm unable to set the 'host port'.
The format expected is strictly a single 'int', not an 'int:int' combination.

When entering a number,it sets the container port,but the host port will be random. How can I set the exposed port to fixed?

**Comment by avinci** [comment]
We currently pick a random port on the host so that when you run multiple containers on the host, there is no conflict. This is displayed in the routing information as to which host we picked. Does that help?

**Comment by trriplejay** [comment]
@hip911 if you want to set your own custom port for accessing your service, one solution is to create a load balancer on AWS and link it to your service in Shippable.  Once you have selected the load balancer in Shippable, you can customize the port number that the load balancer exposes.
