### ISSUE TITLE
Large number of build timeouts since yesterday

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#2226]
https://app.shippable.com/builds/56ab08a829231c0c0057da51
https://app.shippable.com/builds/56ab08a8616ce50c00f223c0
https://app.shippable.com/builds/56aacd30b209670d00185e09
https://app.shippable.com/builds/56aacd2fe2dce70c0088b177
https://app.shippable.com/builds/56aa55c2e2dce70c005e9e17
https://app.shippable.com/builds/56aa2508616ce50c00a1b783
https://app.shippable.com/builds/56aa2508b209670d00d983e8

**Comment by sheldon-sminq** [comment]
Unable to download any of the logs to debug further too

**Comment by sheldon-sminq** [comment]
After disabling the test suite and resetting minion the build succeeded.

**Comment by sheldon-sminq** [comment]
So the issue seems to be with automated unit/integration tests. Can you please get this sorted ASAP!

**Comment by sheldon-sminq** [comment]
Any update on this?

**Comment by manishas** [comment]
I'll ask someone to look into this. Sorry for the delay.

**Comment by sheldon-sminq** [comment]
Its been over 10 days now i am still facing issue with my tests activated
https://app.shippable.com/builds/56b9984ee72c740d006be42e

Need to debug this issue, i cannot run builds with my tests de-activated. I am unable to download the logs files too to check for issues.

**Comment by mbrodala** [comment]
We have started seeing timeouts frequently this week which never occurred for us before. Anything wrong ATM?

**Comment by alvaroc1** [comment]
Same thing for me, all my builds are timing out. What is going on?

**Comment by kpmeen** [comment]
Seing the same...builds have been constantly timing for about 5 days.

**Comment by manishas** [comment]
I am closing this issue since it was opened before the build system upgrade. If you're still seeing timeouts, please open a new issue and provide a build link. Thanks!!
