### ISSUE TITLE
Not able to billing tab to change the plan and change number of containers.

### ISSUE THREAD

**Issue by BeoTCN** [Shippable/support#2227]
Tried to follow the steps below after adding a credit card to my subscription, but I don't see any Billing tab.
-----------------
To purchase additional containers for Shippable CI:
•Click on CI on the Shippable Landing page
•Click on your CI Subscription in the dropdown
•Go to the Billing tab
•Make sure your plan is set to Multi-Tenant CI
•Use the slider to select the number of containers you want for your subscription.
•Enter your payment details and click Buy
•Your CI Plan is now updated
--------------
It is because you have to be the owner of the Team?

**Comment by rageshkrishna** [comment]
@BeoTCN Yes, only team owners can access the billing tab.
