### ISSUE TITLE
PHP: vendor directory missing from deployed zip [question]

### ISSUE THREAD

**Issue by martijnpolder** [Shippable/support#2231]
I would like to build the project on Shippable and then deploy it to AWS EB, without having composer rebuild the dependencies after deployment. I can see in the Shippable build logs that the dependencies are retrieved successfully, but I notice that the ZIP files placed on S3 by Shippable do not contain the vendor directory. 
Are my assumptions about the process incorrect, or did I misconfigure something?

**Comment by mbrodala** [comment]
Did you copy all necessary files to `shippable/buildoutput`? See [docs](http://docs.shippable.com/docker_build/#copying-artifacts-to-prod-image) (the directory is created automatically contrary to what the docs imply.)

**Comment by martijnpolder** [comment]
Thanks for your feedback! 
No, I'm not using Docker for our Laravel apps, currently just the CI + deployment through AWS EB. I don't copy anything myself. It appears that this is not needed, as Shippable does create a ZIP file containing the source code of my application, which is placed on S3, According to the eb-activity.log, the ZIP is succesfully retrieved and extracted on the EC2 instance of the target environment (and does end up in /var/app/current/), but the vendor-directory is missing from the created archive. 
In ZIPs from our current deployment solution (Codeship) the vendor directory is present however. I tried removing /vendor from the .gitignore in the build configuration using shippable.yml

``script:``
``  - mkdir -p .elasticbeanstalk``
``  - cp config.yml .elasticbeanstalk/``
``  - sed '/\/vendor/d' ./.gitignore > ./.gitignore  ``

... but this didn't appear to work.
Could you point me in the right direction? We're looking to replace Codeship as they appear to have trouble reading the correct state after the ``eb init && eb deploy``

**Comment by martijnpolder** [comment]
I found a way by requesting the Elastic Beanstalk to deploy the entire Laravel application directory instead, by changing the eb commands to 

`eb init && eb deploy --staged`

However, this made my ZIPs jump from 100KB to 150MB, because the .git directories of the dependencies were included. Though acceptable, it certainly won't speed up the process... 
To exlude these I added these lines to .ebignore:

`**/.git/`
`.git/`

(probably only the second one does the job, but hey...)

This achieved the desired result: building the project on the default Shippable image, and deploying the (pre-built) artifact to AWS using Elastic Beanstalk.
