### ISSUE TITLE
Failed to POST accountIntegration

### ISSUE THREAD

**Issue by ahueniken** [Shippable/support#2232]
Similar to: https://github.com/Shippable/support/issues/2099

I revoked shippable's oauth token from bitbucket & deleted the ssh key because we were having errors trying to connect / enable a 2nd repository, and I thought starting from scratch may work. 

Now after granting access to bitbucket and trying to login we get this error:

![screen shot 2016-02-02 at 4 20 30 pm](https://cloud.githubusercontent.com/assets/2120721/12764682/3144e85e-c9c9-11e5-8167-d4aa681bf62b.png)

**Comment by trriplejay** [comment]
Can you try once more?  The problem should be corrected now.

**Comment by ahueniken** [comment]
Yep it's working now :)
