### ISSUE TITLE
Why try to start elasticsearch 3 times?

### ISSUE THREAD

**Issue by igayoso** [Shippable/support#2234]
Hi,

I'm debugging your way to provision machine before start the test and I saw that you try to start 3 times elasticsearch with an echo after start telling that was problem during starting but you don't check if the start was correct or not:

```
sudo` su -c "/usr/share/elasticsearch/bin/elasticsearch --cluster.name=56b1e481a674840d00b4e9ae.52.1 > /dev/null 2>&1 &"
  echo 'Service elasticsearch boot error, restarting...'
Service elasticsearch boot error, restarting...
  sudo su -c "/usr/share/elasticsearch/bin/elasticsearch --cluster.name=56b1e481a674840d00b4e9ae.52.1 > /dev/null 2>&1 &"
  echo "elasticsearch started successfully"
elasticsearch started successfully
```

I re-check in your docker image (shippable/minv2:latest) and have same results. Is this ok? Is just a workaround?

Thanks!

**Comment by ric03uec** [comment]
@igayoso we verify whether elasticsearch is running correctly by
  - checking whether a PID file is successfully created or not, and
  - whether easticsearch is successfully listening for connections on its port
If any of these conditions are not satisfied, we try to restart it, which results in the logs you mentioned.
I wouldn't call it a workaround. Its an added safety mechanism to make sure the service **does** boot correctly

**Comment by igayoso** [comment]
Ok, thanks for explanation!
