### ISSUE TITLE
Cache node_modules with shippable build

### ISSUE THREAD

**Issue by drublic** [Shippable/support#2235]
Is it possible to cache `node_modules` (or any other folder) with a Shippable default image?
Currently reinstalling all our modules takes around 5 minutes which is a lot.

It might be interesting to know that we install node in a new version which works without any problem. This seems to be cached. Running `npm install` doesn't seem to add the node modules to some cache.

I would be happy about any suggestions.

**Comment by cratz** [comment]
@drublic We have the same problem and setting `cache: true` in shippable.yml doesn't change anything.
As a workaround you can override default `npm install` [to speed up](https://twitter.com/gavinjoyce/status/691773956144119808) the process at least a bit. We save ~2-3min per build.
```
shippable.yml
install:
  - npm install --quiet --progress=false
```

Btw how was it possible for you to install new node version? I tried to set node version in shippable.yml but this never worked for me.

**Comment by drublic** [comment]
@cratz 

Thanks for the hint regarding npm's progress. Just implemented this and it currently did not improve the build time.

We've a `before_install` hook which does:

```
mkdir -p ~/.nvm/versions
. /home/shippable/.nvm/nvm.sh && nvm install 4.2.6
nvm use 4.2.6 && npm config set ca ''
```

I think the thing that did the trick here was adding the `~/.nvm/versions` folder. We had a problem with this before.

**Comment by cratz** [comment]
@drublic 
Thanks for the hint regarding how to install a newer node version I will try it out.

Regarding npm I forgot to mention that we had to install the latest version of npm because of another issue.
```
shippabel.yml
before_install:
  - npm install -g npm@next
```
But this will be useless in your case since the time you save by disabling progress will be spend by installing latest version of npm except you install node >= 5.x which is shipped with npm >=3.x

**Comment by cratz** [comment]
@drublic 
I just found this and it looks promising to solve the super slow npm install (not only on CI)
https://medium.com/@bestander_nz/my-node-modules-are-in-git-again-4fb18f5671a

**Comment by manishas** [comment]
We are redoing our caching implementation and adding support for folder level caching. This should be available next week.

**Comment by manishas** [comment]
We have deployed the new caching implementation to production. Docs have also been updated - http://docs.shippable.com/ci_configure/#caching-your-container

As mentioned in the docs, simply having a ```cache: true``` in the build section of the yml will result in $SHIPPABLE_BUILD_DIR being cached. You can also choose to cache specific folders using the `cache_dir_list` tag in addition.

```
build:
  cache: true
  # cache_dir_list is optional. If not present, we will cache $SHIPPABLE_BUILD_DIR.
  cache_dir_list: 
    - dir1
    - dir2
    - dir3
```
The first build you run with cache turned on might show an error during the upload cache step but the cache should be successfully pushed during the second build and be available thereafter.

**Comment by drublic** [comment]
Thank you for the update!
Sadly we've moved on from Shippable with my current project. It's great to see the progress now though :)
