### ISSUE TITLE
node EXDEV error

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#2236]
There is an error when installing and deduplicating nodejs package on `npm install`.

The error thrown is `npm ERR! EXDEV: cross-device link not permitted, rename '/root/workspace/src/github.com/inventid/morpheus/node_modules/react-addons-pure-render-mixin' -> '/root/workspace/src/github.com/inventid/morpheus/node_modules/material-ui/node_modules/react-addons-pure-render-mixin'`. According to https://stackoverflow.com/questions/12196163/node-js-fs-rename-doesnt-work (check the last comment) this might have something to do with the `/tmp` being on another virtual device. This used to work before and just started failing for `inventid/morpheus`.

@joostverdoorn

**Comment by rogierslag** [comment]
might be related to https://github.com/npm/npm/issues/9863

**Comment by rogierslag** [comment]
Seems like this was related to a cached container which contained an older version of an npm package. This package could not be properly unlinked through Docker using AUFS. The issue above references this. Can be worked around by adding `[reset minion]` to a commit message

**Comment by frank-dspeed** [comment]
Final workaround code is here:
~~~
FROM node:5.4.1
# workaround for this: https://github.com/npm/npm/issues/9863
RUN rm -rf /usr/local/lib/node_modules/npm \
 && git clone https://github.com/DIREKTSPEED-LTD/npm /usr/local/lib/node_modules/npm \
 && rm -rf /usr/local/lib/node_modules/npm/.git \
 && rm -f  /usr/bin/npm \
 && ln -s -f /usr/local/bin/npm /usr/bin/npm \
 && cd /usr/local/lib/node_modules/npm \
 && npm install

## your normal dockerfile
~~~

we did a npm version that dont has EXDEV Problems inside docker
