### ISSUE TITLE
Ruby project has Java code coverage result on one build

### ISSUE THREAD

**Issue by OddEssay** [Shippable/support#2237]
Normally my builds Ruby code coverage comes from SimpleCov, and I only get Sequence Coverage as expected.

On the last build of a branch, I got Branch Coverage: 22.73% and Sequence Coverage: 15.27% which stood out, upon investigation the coverage relates to a bunch of Java:

```
Coverage Reports
  org.expertojava.jbibrest.modelo Branch: 50.00% / Sequence: 30.99%
  org.expertojava.jbibrest.persistencia Branch: 0.00% / Sequence: 0.00%
  org.expertojava.jbibrest.rest Branch: 0.00% / Sequence: 0.00%
  org.expertojava.jbibrest.rest.dto Branch: 0.00% / Sequence: 0.00%
  org.expertojava.jbibrest.rest.exception Branch: 0.00% / Sequence: 0.00%
  org.expertojava.jbibrest.servicio Branch: 0.00% / Sequence: 0.00%
  org.expertojava.jbibrest.servlets Branch: 0.00% / Sequence: 0.00%
  org.expertojava.jbibrest.utils Branch: 53.13% / Sequence: 57.75%
```
No shippable configuration has change, the only new code between this and the many working branches is some changed erb templates, there isn't any Java in the project at all.

I can provide additional details if you let me know what would be helpful?

**Comment by manishas** [comment]
@OddEssay can you point me to a build where this happened?

**Comment by manishas** [comment]
Closing this. Please point us to a build link so we can investigate this.

**Comment by OddEssay** [comment]
@manishas Sorry about the delay, the build was: https://app.shippable.com/builds/56b49531a674840d0092a022
