### ISSUE TITLE
cannot upgrade CI/Cd plan

### ISSUE THREAD

**Issue by manish-sangani** [Shippable/support#2238]
Hi
I am trying to upgrade plan to 3 containers on CI/CD but after adding the Credit card details, it keeps displaying Loading icon.

https://app.shippable.com/subscriptions/565cb94b1895ca447424fe75

Thanks

**Comment by spsiddarthan** [comment]
@manish-sangani, This should be fixed now. Please go to the billings tab, click on update plan and select the Continuous Delivery plan dropdown. Please let us know if you still have a problem.
