### ISSUE TITLE
Can't enable repository on github, 404 error

### ISSUE THREAD

**Issue by timadamson** [Shippable/support#2240]
I'm getting this error when trying to enable a project on GitHub:

{"logType":"verbose","methodName":"|common|github|postDeployKey|timadamson/ldap_task|_getDeployKeys","id":4005,"message":"getDeployKeys failed for timadamson/ldap_task","link":404}

It's a private repository and I'm using a brand new Shippable account which I only opened today.

**Comment by manishas** [comment]
sorry for the delay on this. I see that you could successfully enable the project, so i am closing this issue. Let me know if you need help with the build failures.
