### ISSUE TITLE
no access to build details

### ISSUE THREAD

**Issue by tcurdt** [Shippable/support#2245]
I should have access to build details https://app.shippable.com/builds/56bf54f0fb50fb0c005c272b
but I am getting

    {  
      "logType":"warn",
      "methodName":"common|validateCaller|/builds/:id|_checkAuthCallersProjectAccess",
      "id":2000,
      "message":"object not found or unauthorized for route: /builds/:id"
    }

instead.

**Comment by trriplejay** [comment]
If the project is private, you may need to go to your account settings page and enable private repos.

**Comment by tcurdt** [comment]
@trriplejay private repos are enabled.

**Comment by tcurdt** [comment]
I am added to that private repo - but I am not the owner.

**Comment by trriplejay** [comment]
can you try again now? I think your account just needed to re-sync your repos after the private scopes were enabled.

**Comment by tcurdt** [comment]
Now it works, thanks!

When do I need to re-sync? manually?

**Comment by trriplejay** [comment]
normally you shouldn't have to. Shippable will do it automatically, but we basically have a bug where enabling private scope doesn't force the sync, so in this case the user has to do it manually (or wait for the next interval)... Hopefully we'll change that soon.

**Comment by tcurdt** [comment]
Thanks for the quick help, @trriplejay
