### ISSUE TITLE
Docker build order

### ISSUE THREAD

**Issue by markhofmann** [Shippable/support#2248]
I'm currently evaluating shippable for my projects using the free account.

Somehow I'm unable build my project with a custom Dockerfile - probably because shippable tries to Dockerize my app before actually building it.

How do I get to the Docker build order switch as described here?
http://docs.shippable.com/docker_build/

All I get are the settings as described on this page:
http://docs.shippable.com/project_settings/#docker-options

**Comment by manishas** [comment]
@markhofmann sorry it took so much time for us to respond. We recently released an upgraded build system which gives you complete control over docker workflows, including running docker commands in your yml. Let me know if we can help get you started. Docs are here - http://docs.shippable.com/ci_configure/#setting-your-build-image
