### ISSUE TITLE
Support for higher /dev/shm size

### ISSUE THREAD

**Issue by madebysid** [Shippable/support#2250]
I have loads of UI tests using Chromedriver, running on Shippable. They all run fine on my local machine, but when I run the same on the CI Platform , the tests fail because Chrome crashes with this error:
``` RuntimeError: unknown error: session deleted because of page crash from tab crashed ```

Research suggests this happens because of a low shared memory size. Is there a way increase the /dev/shm size when starting my CI build? This is extremely necessary for me because unlike other issues, my tests are not just slow, they fail. I don't mind paying as long as I can eliminate random test failure.

**Comment by avinci** [comment]
we have completely revamped our build system. This issue should no longer occur. Please let us know if so...
