### ISSUE TITLE
Angular 2 Gulp Build - Undefined Function

### ISSUE THREAD

**Issue by Grahamcraker** [Shippable/support#2251]
I'm attempting to run some simple gulp tasks on an Angular 2(TypeScript) application. The error occurs when attempting to run the following line
```js
require('../components/cake-baker.component');
```
When I run gulp on my local machine, there are no issues. I've tried modifying my configuration with no success. The associate gulp files and app files can be found here:
https://gist.github.com/Grahamcraker/daeb7a4a7d5ad879afb6
I have a failed build at https://app.shippable.com/builds/56c35466fb50fb0c004a85c4

Thanks for any help!!

**Comment by manishas** [comment]
I cannot get to this build, probably because the project was disabled. Sorry for the delay.

We have revamped our build system and this has resolved a lot of issues. Please let us know if this is still happening and I will reopen this issue.
