### ISSUE TITLE
Sbt, fork in test never end.

### ISSUE THREAD

**Issue by gervaisb** [Shippable/support#2253]
I'm using `shippable\ubuntu1404_scala` image to build a multi module sbt project. 
My build is configured with `fork in Test := true` and run fine localy. However on Shippable it seems to wait indefinitely. 
If I remove the fork instruction it finish successfully.

**Comment by manishas** [comment]
Sorry for the delay on getting to this. I looked up your subscription but did not find any builds or enabled projects.

We recently upgraded our build system and if this is still happening, happy to take a look. Let us know.

**Comment by gervaisb** [comment]
Manisha, In fact I have delete evrything and requested an account deletion
(but not received any response)
