### ISSUE TITLE
Login is broken when connecting with BitBucket account

### ISSUE THREAD

**Issue by smclaughry** [Shippable/support#2254]
From https://app.shippable.com/ I click the "bitbucket" button and am immediately redirected to https://app.shippable.com/error with the following message:
"An error occured, please choose an action. Failed to POST accountIntegration"

My bitbucket profile is here: https://bitbucket.org/smclaughry/

Login with my github account works fine.

**Comment by trriplejay** [comment]
can you try again? it should be fixed now.

**Comment by smclaughry** [comment]
Thanks!
