### ISSUE TITLE
Build issue using gradle

### ISSUE THREAD

**Issue by asheibani** [Shippable/support#2256]
Hi,

My builds are failing due to a docker step that adds some files that are generated during the gradle build but for some reason are missing.

Here is snippet of the logs:
...
Sending build context to Docker daemon 
Step 0 : FROM java:7-jre
7-jre: Pulling from java
1e58eecba27a: Already exists
a0e9fe2f8803: Already exists
9b0523a037ca: Already exists
383137f3df30: Already exists
c597615ac784: Already exists
6aff7fb974d8: Already exists
8c106035506d: Already exists
df58f4016b15: Already exists
cfd77b163a28: Already exists
6f8d4a74ba6d: Already exists
Digest: sha256:afbb74cf8f13f57b71a63ba4f292c70519bac57e0a83087dd496821895c39770
Status: Image is up to date for java:7-jre
 ---> 6f8d4a74ba6d
Step 1 : MAINTAINER 
 ---> Running in 053858560e29
 ---> 4a167d29f18c
Removing intermediate container 053858560e29
Step 2 : ADD build/unpacked/lib/ /app/lib/
build/unpacked/lib/: no such file or directory

During the gradle build process (gradle clean assemble) the above directory is created. Locally I have no issues. 

Thanks,
Amir

**Comment by manishas** [comment]
closing this issue since we have upgraded the build system since this was opened. please let us know if this is still happening.
