### ISSUE TITLE
Builds are not starting

### ISSUE THREAD

**Issue by ashernevins** [Shippable/support#2258]
This issue has been happening on and off all day.

A build will be next in the queue to start (or the only build) and it will just not start. The build will show up in the 'In Progress' tab, and the duration will start counting up and be equal to the queued time. For example, the latest build this is happening on for me is https://app.shippable.com/builds/56cd7b50d527f60c00b6fe2b and it is currently showing 4 minutes for both queued and duration, and they are incrementing together.

**Comment by kjones1876** [comment]
Same issue happening here. It just sits there, does nothing, times out after like 2 hours.

**Comment by pkaminski** [comment]
I'm seeing this too, e.g. in https://app.shippable.com/builds/56cd8386d527f60c00b76a0c.

**Comment by pkaminski** [comment]
My builds eventually went through.

**Comment by kjones1876** [comment]
Same here, just finished. However, i did have ones yesterday that straight up timed out and failed

**Comment by rageshkrishna** [comment]
Hi everyone. I'm very sorry about the delayed update on this. Our build agent decided to die on all of the machines in quick succession and this caused a complete outage. We have initialized completely new hosts and all builds should be running correctly now.

Please let me know if you continue to see any issues.

**Comment by ashernevins** [comment]
Closing as this appears to be resolved.
