### ISSUE TITLE
Shippable perf

### ISSUE THREAD

**Issue by martijnpolder** [Shippable/support#2259]
Hi support,

We've run a trial of Shippable for a while now, as we're considering moving away from our current deployment provider. However, the difference in speed of the two solutions are quite large.
Though Shippable sometimes seems to get stuck in starting (unneeded) mysql-services, which is a nuisance, the major delay is in de step "composer install --prefer-source --no-interaction", which takes shippable 5 for upto 20 minutes. Our current supplier, Codeship, handles this step in 1 to 2 minutes at most consistantly. The instance size Shippable is advertised to use seems to be easily up for the task, bandwith at the dependency-sources is obviously the same for Codeship and Shippable, so what causes this delay? Bandwith at Shippable's end?
Are you aware of any issues?

regards,
M. Polder

**Comment by mbrodala** [comment]
@martijnpolder As for Composer you might want to execute `phpenv config-rm xdebug.ini` before. This will vastly speed up all Composer invocations. Notice that you should copy that file somewhere else if you want to re-add it later for coverage reports. See #2186

**Comment by martijnpolder** [comment]
Seems like a great tip, I'll try it - though if the bandwidth really would be the bottleneck it won't be the magic bullet, I'll keep you posted

**Comment by manishas** [comment]
@martijnpolder sorry for the delayed response! We've been focused on getting our latest release out the door and this should address your problem.

It will be good to disable and enable your project, convert to the new yml format explained in the docs, and try a build. We've made massive perf improvements and we're happy to help you tweak your yml.
