### ISSUE TITLE
Was there a recent change to minion resources?

### ISSUE THREAD

**Issue by pnpritchard** [Shippable/support#2260]
Starting yesterday, a lot of my builds have experienced timeouts. The logs show the build is hanging at various steps of compilation. There isn't any indication in the logs, but my feeling is that it is getting killed for going out of memory.

I saw this comment (https://github.com/Shippable/support/issues/1429#issuecomment-104020337) from a year ago saying that the minion has 2gb memory . Is this still the case?

**Comment by manishas** [comment]
@pnpritchard we've upgraded our platform today and you should not see these timeouts any more.

Please let us know if you run into this again.

**Comment by manishas** [comment]
closing this since this shouldn't happen after the build system upgrade.
