### ISSUE TITLE
Deploy to Meteor Galaxy

### ISSUE THREAD

**Issue by maxfi** [Shippable/support#2262]
I had a few issues when trying to setup deployments to Meteor Galaxy so I put together [a small repo](https://github.com/maxfi/shippable-meteor-galaxy) that might be of help to others. Feedback and contributions are welcome.

**Comment by manishas** [comment]
@maxfi thanks for this sample project! We recently added support for json for encrypted variables, so you should give that a shot.

Can we include this project as part of our sample code so all Shippable users can benefit from it? 

Thanks again.

**Comment by manishas** [comment]
closing this, but please let us know if we can include your repo as a sample project.

**Comment by maxfi** [comment]
@manishas Thanks for the information about the support for json in encrypted variables. I'll check it out and update the project.

Yes, please feel free to include the repo in as a sample project. Hopefully it's useful for others! :-)
