### ISSUE TITLE
Setting the build version/number format?

### ISSUE THREAD

**Issue by adamalesandro** [Shippable/support#2263]
I was just setting up my first CI project and I see that the build number increments by 1 each time I commit- all good.  But can I specify a particular version in the YML or elsewhere i.e. Major and Minor, something like this:
```
version: 0.1.{$BUILD_NUMBER}
```
so that I will see `0.1.165` as the build instead of (currently) `165`

**Comment by manishas** [comment]
@adamalesandro at this time, we do not support custom build numbers. If we hear more feedback on this, we will definitely revisit this. Thanks!
