### ISSUE TITLE
Can't add image to Formation 

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2264]
I am trying to set up a Formation for ECS. I did one yesterday and it worked fine. Today, while the image on my ECR repo shows up...no tags show up at all. I even gave the user Admin permissions to eliminate a permissions problem. The repository exists and there is an image available. See screen shots. 

![screenshot 2016-02-26 17 29 51](https://cloud.githubusercontent.com/assets/823555/13364647/bf45e980-dcae-11e5-92b2-fa7df32ca33e.png)
![screenshot 2016-02-26 17 29 39](https://cloud.githubusercontent.com/assets/823555/13364650/c01e1b02-dcae-11e5-92fa-8e68db382b92.png)
![screenshot 2016-02-26 17 31 53](https://cloud.githubusercontent.com/assets/823555/13364668/dae60544-dcae-11e5-8cfb-8ff01b3a10e1.png)

**Comment by manishas** [comment]
I am closing this issue since we should pick this up with pipelines. I have set up a demo for 3/2 at 10am PST.

**Comment by prabhuinbarajan** [comment]
sorry to chime in late on this thread. i have a similar problem like @npahucki . I am still unable to retrieve my images via pipelines from ECR.  CI seems to be setup correctly and pushing images to ECS through the same integration. But pipelines and lighthouse are not retrieving the images. I suspect it has to do something with the convention of the repo url. is AWS/ECS supported for pipelines?

![image](https://cloud.githubusercontent.com/assets/4031715/15522362/bad34854-21c6-11e6-846f-659d15aa27c2.png)

**Comment by a-murphy** [comment]
Did you create a user for the keys in the account integration?  It looks like it's missing permissions for `ecr:ListImages`.  Could you make sure that `ecr:ListImages` is in the policy for that user?

**Comment by prabhuinbarajan** [comment]
@a-murphy  - Thanks for the quick response. it was missing ecr:ListImages. 
After adding that I tried a quick experiment with light house , and tried adding an image. 
https://app.shippable.com/lighthouse/5745e1ee6d44470b00ffd6b6

It still couldnt list all the tags for the above subscription - can you point out where the problem might be? is there a way to see debug messages behind these?

Thanks
prabhu

**Comment by prabhuinbarajan** [comment]
infact, the user has  "ecr:*" permissions now.

**Comment by trriplejay** [comment]
@prabhuinbarajan I'm seeing this error in the logs now:
```
Failed getTags for repo: micro-api RepositoryNotFoundException: The repository with name 'shippable-aws/micro-api' does not exist in the registry with id '413045187232'
```

Unfortunately we're not currently surfacing these debug logs to the users, but that's definitely a feature that we'll try to add soon.

possible problems: incorrect region? typo in repo name?

**Comment by prabhuinbarajan** [comment]
here is a screenshot from the ECS console.
![image](https://cloud.githubusercontent.com/assets/4031715/15550753/c19969e2-2267-11e6-8c20-9c0a9079f48a.png)

![image](https://cloud.githubusercontent.com/assets/4031715/15550852/2eea0a2e-2268-11e6-888a-3dbb5601033c.png)

and the corresponding lighthouse subscription:
![image](https://cloud.githubusercontent.com/assets/4031715/15550882/4b55d8e6-2268-11e6-84dc-a9c0ebbe1efb.png)

seems like it is in order. the only point to note is that I setup the repository in us-west-2. there is no other indicator than the repository url that hints that. is it sending a region tag somewhere in the call?

**Comment by trriplejay** [comment]
Ah, this looks like a bug on our end. I'll open up an internal issue and update this thread with status. Thanks for pointing this out!

**Comment by prabhuinbarajan** [comment]
sounds good. thanks

**Comment by trriplejay** [comment]
@prabhuinbarajan hey there. The fix for this has been deployed. Let us know if you run into any other problems.
