### ISSUE TITLE
Builds timeout before any of the code executes

### ISSUE THREAD

**Issue by alvaroc1** [Shippable/support#2265]
Builds are timing out for us after these steps:

    Generating builds 0.00 seconds
    hub login 0.46 seconds
    pulling image from hub 2.36 seconds

All of which appear to complete successfully. But nothing else happens after that. What's going on?
 This is happening to all of our builds.

**Comment by ric03uec** [comment]
@alvaroc1 we've migrated the subscription to the new build system. can you please try your builds again and let me know if it works.
also, i would recommend moving to the new yml format(http://docs.shippable.com/ci_configure/) which has added support for handling custom images

**Comment by alvaroc1** [comment]
Ok, I migrated the shippable.yml to the new version... my builds seem to be working now. Thanks.

**Comment by rageshkrishna** [comment]
Closing because this appears to be resolved.
