### ISSUE TITLE
Formation AutoDeploy to ECS just stopped working

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2266]
I had setup a formation to deploy to ECS a few days ago. It worked a [couple of times](https://cloud.githubusercontent.com/assets/823555/13374972/98835624-dd72-11e5-8707-b4dad18f1aa3.png), but now constantly fails (and I can't find any error messages anywhere). This is the formation: https://app.shippable.com/formationServices/56cf0a0d22366a0c005a5da2

<img width="1040" alt="screenshot 2016-02-27 16 49 54" src="https://cloud.githubusercontent.com/assets/823555/13374964/4ec0a5e6-dd72-11e5-9777-5cb1521fe21b.png">

Here is what I have tried/verified: 
1) I already have a role called ecsInstanceRole.
+ It has the attached [TrustRelationship](https://github.com/Shippable/support/files/149526/TrustRelationship.txt)
 document specifying both ECS and EC2.
+ It has the attached [Policies](https://github.com/Shippable/support/files/149527/Policies.txt) - though to eliminate a problem with permissions I even temporarily gave it Admin permissions and it still failed. 
+ I removed the Load Balancer and it still fails - though it fails right away with the load balancer. 
<img width="1029" src="https://cloud.githubusercontent.com/assets/823555/13374965/4ec19960-dd72-11e5-817a-62a7600e1749.png">

2) The AWS keys used for the integration I also gave Admin just to try it - no difference. 

It seems to completely fail to create an ECS task or service. Can you please let me know what is going on here?

**Comment by trriplejay** [comment]
one error I'm seeing in our logs is:
`not authorized to perform: elasticloadbalancing:DeleteLoadBalancerListeners`

If you had a load balancer set up, then removed it, we would attempt to delete any listeners that we may have added in the previous deployment.

We are planning on surfacing these kinds of errors to the user in the near future.

**Comment by manishas** [comment]
Closing this since this functionality has now migrated to pipelines

**Comment by npahucki** [comment]
You have a bug in your initialization script - you don't set the mode for the auth keys files!

May  2 18:35:48 ip-172-31-2-179 sshd[22859]: Authentication refused: bad ownership or modes for file /home/shippable/.ssh/authorized_keys
May  2 18:35:48 ip-172-31-2-179 sshd[22859]: Connection closed by 52.6.173.6 [preauth]
