### ISSUE TITLE
Can't change number of minion in billing form

### ISSUE THREAD

**Issue by rvrignaud** [Shippable/support#2268]
Hello,

I'm trying to increase the number of minion (we were in the annual 12$ plan). I got the following error : 
```
{"logType":"verbose","methodName":"subscriptionPlans|post|callerId:xxxxx_verifySubscriptionCost","id":4003,"message":"Total cost sent 0 does not match calculated cost 40"}
```

Is there anything I can do ?

**Comment by manishas** [comment]
@rvrignaud we're in the middle of an upgrade, I'll let you know when everything is up so you can try again.

**Comment by manishas** [comment]
@rvrignaud you can choose the plan for 'Continuous Delivery' on your billing page to buy more minions. 

This is the new plan everyone will be moved to in the next day or two.

**Comment by rvrignaud** [comment]
Thx that worked.
