### ISSUE TITLE
Formations gone?

### ISSUE THREAD

**Issue by cratz** [Shippable/support#2269]
After we received the email (see below) I answered twice to make sure our formations become migrated 
We never got a reply and now our formations are gone!!! 
May be open an issue here will help, let's see...

> Based on customer feedback, we are making some key changes to the Shippable service on 2/29:
> 
> Shippable 
> 
> Hi Shippable Customer,
> 
> Thank you for using Shippable Formations and providing us with valuable feedback about the service.
> 
> Shippable Formations has evolved significantly over the last few months, including adding support for third-party container services like Amazon ECS. Based on customer feedback, we are making some key changes to the service on 2/29--
> 
> Multi Tenant Deploy plan will be retired.
> 
> We launched the Shippable container service when there weren’t many options available for teams wanting to use containers for their Dev/Test workflows. Multiple container service options are available now, including Amazon ECS, Google Container Engine and others.  As a result, we will no longer run our own container service, but focus on integrating with all container services to provide you with a uniform platform to deploy your containerized applications to any cloud.  If you are on the Multi Tenant Deploy plan, your Formation will be unavailable after 2/29.
> 
> CI and Formations (Container Service Deploy) will be merged into one subscription.
> 
> Based on your feedback, CI and the functionality offered by the Container Service Deploy plan are just pieces of your application delivery pipeline and it doesn’t make sense to offer them as two separate subscriptions. To address this, we’re merging these into a single subscription where you can manage both your continuous integration and deployment workflows in one place.
> 
> As a result, Formations on the Container Service Deploy plan will be unavailable after 2/29, unless you send us an email asking us to migrate your services to an existing CI subscription. Please include the account name and subscription you want us to migrate your Formations to.
> 
> Please note that these changes do NOT affect your current Shippable CI subscription.
> 
> If you have any questions, feel free to email me at manisha@shippable.com (mailto:manisha@shippable.com) .
> 
> Thanks again for using Shippable!
> 
> Manisha Sahasrabudhe
> Vice President of Product

**Comment by manishas** [comment]
@cratz your formation will be migrated today. I will send you an email in a few minutes.

**Comment by cratz** [comment]
Thx!

**Comment by manishas** [comment]
This Formation has been migrated, so closing this issue. Please let us know if you run into any issues.

Thanks!
