### ISSUE TITLE
newBuild API needs to be able to trigger a build for project->branch

### ISSUE THREAD

**Issue by ducky427** [Shippable/support#2270]
Till very recently (as recent as last week), we were using the `searchBuilds` for a project to get the previous results by some paramters. But it seems that that bit of the API doesn't work anymore and furthermore, it seems to have disappeared from the documentation.

It quite disturbing that some parts of the API have gone missing without any warning to the user.

**Comment by manishas** [comment]
@ducky427 I am really sorry about this! We communicated several changes to affected customers over the last couple of weeks but this was a miss. We'll make sure the everything is backwards compatible and versioned if it changes again.

Can you send me a list of APIs you were using at manisha@shippable.com and I can get back to you with suggested updates in a few hours. Let me know if that helps.

Sorry for the inconvenience!

**Comment by shadowfax-chc** [comment]
I was also using the `searchBuilds` endpoint. Is there a new endpoint that provides similar information?

**Comment by manishas** [comment]
we'll look into this and get back to you.

**Comment by manishas** [comment]
@shadowfax-chc you're seeing this because you have not been migrated to the new plan yet. We wanted to migrate customers in chunks to ensure a smooth migration.

GET /builds should work pretty much like GET /runs for retrieving builds from the existing old build system.

**Comment by shadowfax-chc** [comment]
@manishas `/builds` is doing the trick, thanks. Will `/builds` stop returning new results once the migration happens?

**Comment by manishas** [comment]
@shadowfax-chc /builds will still work after migration for builds that were triggered before migration. For builds triggered after migration, you'll need to call the /runs routes.

**Comment by manishas** [comment]
@ducky427 you can do the following to get the latest successful build per project and branch-

GET /runs?status=30&projectIds=[projectId]&branch=[branch]&limit=1&isPullRequest=false

You can also use GET /builds for builds triggered before migration. 

We have a new API to trigger a build - POST /projects/:projectId/newBuild - but this triggers a build for the default branch. We're adding a parameter to this to specify branch and this should be available tomorrow.

**Comment by ducky427** [comment]
@manishas, I tried the `runs` api you suggested and it always returns `[]` no matter whatt the parameters are even when I tried the ones you've mentioned.

Has it been deployed?

**Comment by kanthchandra** [comment]
@ducky427 https://api.shippable.com/runs?status=success&projectIds=[projectId]&branch=[branch]&limit=1&isPullRequest=false
Note: status should be success, projectIds should be an array with one element and branch should be an array with one element

This query will get the latest successful run for a project.

Can you try this and let me know if it works?

Also please let me know what is the exact thing that you want to do so that I can help you with the query?

**Comment by ducky427** [comment]
Hi @kanthchandra, I am getting the following error when I try:

`https://api.shippable.com/runs?status=success&projectIds=[projectId]&branch=[branch]&limit=1&isPullRequest=false`

```
{
  "logType": "verbose",
  "methodName": "common|validateProjs|callerId:<Some Hex Code>|_injectUserProjectPermissions",
  "id": 4005,
  "message": "Failed to obtain public projects"
}```

I've redacted the callerId from the response.

**Comment by kanthchandra** [comment]
I think the mistake with the query that @manishas is that we are sending the projectIds as an array. If you want the runs for more than one projects, it should be comma separated variables like `projectIds=projectId1,projectId2`.

**Comment by ducky427** [comment]
@kanthchandra, as I looking to query only one project, I've tried both

1) `projectIds=projectId1`
2) `projectIds=[projectId1]`

Both don't work. The first returns `[]` and the second returns a response which looks like an error.

**Comment by kanthchandra** [comment]
hmm, let me investigate and come back to you.

**Comment by kanthchandra** [comment]
@ducky427 can you please tell me if the project that you are trying to access is on which plan? If you go the subscriptions billing page you will know the plan. If its not on Continuous Delivery plan then you should replace the `/runs` by `/builds` . Please make sure that you are making the call with a valid apiToken in the headers.

**Comment by ducky427** [comment]
huzzah! `builds` works for me. thanks!

**Comment by kanthchandra** [comment]
@manishas this is working as expected. Can I close this out?

**Comment by ducky427** [comment]
@kanthchandra, I think the only thing outstanding is triggering a build for a specific branch for a project.

**Comment by kanthchandra** [comment]
@ducky you can trigger a build by doing a POST https://api.shippable.com/projects/projectId/newBuild?branch=master or which branch, Please note that the project has to be enabled before you can build it and you can also send the branch as a json body { "branch": "master" } from postman or curl or whichever tool.

Please make sure that you are making the call with a valid apiToken in the headers.

**Comment by ducky427** [comment]
@kanthchandra, great. that works! i'm gonna close this issue now.
