### ISSUE TITLE
My Formations are gone, and Add Pipeline is disabled

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2273]
![screenshot 2016-02-29 11 29 27](https://cloud.githubusercontent.com/assets/823555/13397217/c2bf141c-ded7-11e5-884f-e3cb84ddb886.png)

**Comment by manishas** [comment]
we're looking into this...

**Comment by manishas** [comment]
ah I know why. a free pipeline is offered with the Continuous Delivery plan. Everyone will be migrated to this plan in the next 24-48 hours, but you can do so before that by going to your Billing page and updating the plan to `Continuous Delivery`. 

Your Add pipelines button should show up at that point.

**Comment by manishas** [comment]
closing.
