### ISSUE TITLE
Unable to pay for subscription plan

### ISSUE THREAD

**Issue by boffe** [Shippable/support#2274]
Hi,

Trying to create a subscription with 5 minions, but when I move the slider up the amount doesnt change. When I click "Save changes" I get the following error "Total cost sent 0 does not match calculated cost 40". 
![shippable](https://cloud.githubusercontent.com/assets/7431023/13397697/5a3af112-defb-11e5-9af8-d6c1fc389791.PNG)

Thanks

**Comment by spsiddarthan** [comment]
@boffe, We're in the middle of an upgrade which is why you saw this error - we are fixing it. 

However, you can right away go and choose the plan for 'Continuous Delivery' on your billing page to buy more minions. Everyone will be moved to this new plan in a couple of days.

**Comment by manishas** [comment]
@boffe I am closing this since our upgrade is complete. You can choose the Continuous Delivery plan on your Billing page and then upgrade your minions. Pls let us know if it doesn't work.
