### ISSUE TITLE
$SHIPPABLE_PYTHON has disappeared

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2275]
Hello,

Our build scripts were doing something like:
```
mkdir -p $HOME/sample_ve/ 
virtualenv -p $SHIPPABLE_PYTHON $HOME/sample_ve/
source $HOME/sample_ve/bin/activate
```

It seems $SHIPPABLE_PYTHON no longer exists and http://docs.shippable.com/ci_configure/#using-environment-variables seems to agree.

I see there is a $SHIPPABLE_VE_DIR, can you confirm I should now be doing:
```
source $SHIPPABLE_VE_DIR/bin/activate
```
directly?

Will it stay that way or do you plan to reintroduce $SHIPPABLE_PYTHON? I am asking because I have dozens of build files to fix.

**Comment by pmezard** [comment]
I worked around it by setting SHIPPABLE_IS_OFFICIAL_IMAGE=true in "env" section. Since it used to work, it still works. Would be nice to do it automatically to "old" configurations.

**Comment by mbrodala** [comment]
@pmezard Thanks a lot, this also [fixes an issue](https://github.com/Shippable/support/issues/2279#issuecomment-190611794) we are seeing currently.

We'll add this workaround for now to keep it working.

**Comment by rageshkrishna** [comment]
`SHIPPABLE_PYTHON` will be available only on builds running official images. The reason for this is that the path to the python binary you need to use can change with the image you're using.

We do export a SHIPPABLE_PYTHON_VERSION variable, so if your python binaries are named conventionally (python2.7, python3, etc.), you should be able to do this:

````
mkdir -p $HOME/sample_ve/ 
virtualenv -p /path/to/my/python$SHIPPABLE_PYTHON_VERSION $HOME/sample_ve
$HOME/sample_ve/bin/activate
````

Would this work for you?

Setting SHIPPABLE_IS_OFFICIAL_IMAGE on a custom image can cause problems because our build scripts make certain assumptions about where things are located on the file system when it is set to true.

**Comment by mbrodala** [comment]
@rageshkrishna How are official images detected? And why are `drydock/*` images not official? We are using `drydock/u14php` and have to export `SHIPPABLE_IS_OFFICIAL_IMAGE` in all of our projects, [otherwise `setup_php` fails](https://app.shippable.com/runs/56d6a58fac215a0c00bbccb3).

**Comment by rageshkrishna** [comment]
Hmm, that should not be happening to drydock images.. I'll check right now and get this fixed.

**Comment by pquentin** [comment]
@rageshkrishna Your [suggestion](https://github.com/Shippable/support/issues/2275#issuecomment-191072563) does work, but it's `source $HOME/sample_ve/bin/activate` (you forgot `source`). But in other words, setting python to something else than "2.7" continues to be useless by itself: we need to do the work ourselves in the yml file.

**Comment by rageshkrishna** [comment]
Thanks, @pquentin! I've updated the snippet above.

I see what you're saying about doing the work in the YML file, but I'm not sure what the safe alternative could be when we're running the build on a custom image. For minv2 and all drydock images, this will be handled by us without any effort from your end.

If it makes it easier, this is basically what we do internally on official images:

````
build:
  ci:
    - |
      if [ "$SHIPPABLE_PYTHON_VERSION" == "pypy" ]; then
        virtualenv -p /usr/bin/pypy $HOME/sample_ve;
      elif [ "$SHIPPABLE_PYTHON_VERSION" == "pypy3" ]; then
        virtualenv -p /usr/bin/pypy3 $HOME/sample_ve;
      else
        virtualenv -p /usr/bin/python$SHIPPABLE_PYTHON_VERSION $HOME/sample_ve;
      fi
    - source $HOME/sample_ve
````

**Comment by rageshkrishna** [comment]
@mbrodala I'm unable to repro the problem you're seeing with `drydock/u14php`. I just tried a new build and it is indeed setting `SHIPPABLE_IS_OFFICIAL_IMAGE`. Can you please link me to a build where you've seen this happening.

I can confirm that `shippableImages/*` is not part of the official list.

**Comment by rageshkrishna** [comment]
I will get rid of the problem where setup_php is failing for other images. I can see we made a mistake with the last line where it tries to print the language version.

**Comment by mbrodala** [comment]
@rageshkrishna Thanks, you are right that this workaround is only necessary for the older images, it [works just fine](https://app.shippable.com/runs/56d6c6436b86640c004639a8) for the `drydock/*` images.

**Comment by pmezard** [comment]
The SHIPPABLE_PYTHON_VERSION trick is good enough, but the variable is not documented anywhere. At least not in http://docs.shippable.com/ci_configure/#specifying-language-and-runtime or in the "Languages" page.

**Comment by manishas** [comment]
this env variable has now been added to the docs - http://docs.shippable.com/ci_configure/#standard-variables
