### ISSUE TITLE
ssh-agent: not found using standard image

### ISSUE THREAD

**Issue by rvrignaud** [Shippable/support#2277]
Hello,

Our build https://app.shippable.com/runs/56d45d855009560c004877f6 is broken.
We are using standard shippable image.
However it fails to build due to ```/bin/sh: 1: ssh-agent: not found```  during wait_for_exit phase.

Any clue ?

**Comment by manishas** [comment]
@ric03uec can we take a look at this asap?

**Comment by ric03uec** [comment]
@rvrignaud can you confirm if the custom image you're using has `ssh-agent` installed on it

**Comment by ric03uec** [comment]
@rageshkrishna since we were installing the dependencies for custom images earlier, we should port the same functionality for the new build system. want to double check with you whether this would conflict with our strategy for handling custom images.

**Comment by manishas** [comment]
We should fix this.

**Comment by rvrignaud** [comment]
@ric03uec we are using 'Use default Shippable Image' setting

**Comment by rageshkrishna** [comment]
I'm looking in to this now. Looks like we have a couple of bugs that need to be addressed around this. I'll share more updates as we make progress here.

**Comment by rageshkrishna** [comment]
There was one issue with our component that would error out if ssh agent is not found. This fix will be deployed shortly.

In the mean time, can you please delete your project settings and create them once again. We seem to have gone into an unusual state on your project settings which is causing your build to be executed with the pre-ci docker build workflow instead of the post-ci that you have configured.

Resetting this should let your builds start running correctly on the default Shippable image.

**Comment by JasonSwindle** [comment]
I too am impacted by this as my example does not have ssh-agent at all, nor needs it (nginx:latest)

projects: 56d1f64f1895ca44747c9577

**Comment by manishas** [comment]
@rvrignaud is this still an issue? we pushed a couple of fixes yesterday so wanted to check in and see if this was fixed.

Please delete your project settings and recreate them as suggested by ragesh above. 

We're also happy to jump on a hangout and help debug... just let us know.

**Comment by pmezard** [comment]
The original issue is fixed but at the same time we rewrote the .shippable.yml and switch the CI image, so it is hard to tell what happens in the original conditions.

I will let you or @JasonSwindle close the issue.

**Comment by rageshkrishna** [comment]
We now check for missing dependencies and install them when the container is started. Currently, this takes care of ensuring the following tools are available for the build:

1. sudo
1. git
1. ssh-agent
1. python

I'm closing this issue as @JasonSwindle has another one open for his specific scenario.
