### ISSUE TITLE
New shippable.yml format not evaluated

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2279]
I'm currently testing the new format of the `shipppable.yml` in one of our projects but it seems like it is not picked up at all, [all builds fail](https://app.shippable.com/builds/56d469911954630c00231aec).

Here are a few hints which clearly indicate that my `shippable.yml` configuration is ignored:

```
  pulling image from hub
    echo "image shippable/minv2:latest (id: 63655319ed5c) exists, skipping pull."
      image shippable/minv2:latest (id: 63655319ed5c) exists, skipping pull.
```

This should be `dry-dock/u14php` (`tip`) instead as configured in `build.pre_ci_boot.image_*`.

```
  script
    phpunit
      PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Could not find .../autoload.php, make sure you ran composer.' in /home/shippable/.../tests/bootstrap.php:5
      Stack trace:
      ...
```

This is missing all commands from `build.ci`, including `composer install`.

Is this some bug or am I missing something to switch to the new format?

**Comment by manishas** [comment]
@mbrodala all users have not been migrated to the new plan which supports the format. We wanted to make sure everything in prod was perfect before migrating users :)

If you want to use the new format, please switch to the 'Continuous Delivery' plan on the Billing tab of your subscription. This plan supports both ymls - old and new.

**Comment by mbrodala** [comment]
@manishas Thanks for reopening since there still seem to be some issues here. The build still fails but now with a different error:

```
boot_container
  echo 'No running build container to stop'
  echo 'Using dry-dock/u14php:tip for the build'
  echo 'Booting job image dry-dock/u14php:tip'
  sudo docker run -d --privileged=true --net=bridge -v /home/shippable/cexec:/home/shippable/cexec -v /tmp/cexec:/tmp/cexec -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock --name=c.exec.my-project.1132.1 --entrypoint=/home/shippable/cexec/build.sh -e RUN_MODE=production -e SHIPPABLE_API_URL=https://api.shippable.com -e SHIPPABLE_API_RETRY_INTERVAL=3 -e SHIPPABLE_CONTAINER_NAME=c.exec.my-project.1132.1 -e SHIPPABLE_IS_OFFICIAL_IMAGE=false -e SHIPPABLE_IS_LEGACY_IMAGE=false dry-dock/u14php:tip
```

Although I cannot see an error message, the build just stops at this point and the error indicator shows up at the right.

On that note: a different project still using the old format also fails on a different point:

```
setup_php
  echo PHP environment configuration will be skipped because this job is not running on an official image
    PHP environment configuration will be skipped because this job is not running on an official image

  php --version
    /root/794fd07f-d575-497e-aebc-3f5724e8358f.sh: line 58: php: command not found
```

This (as all our projects) is using `shippableimages/ubuntu1404_php`. Is this related?

**Comment by rageshkrishna** [comment]
@mbrodala The reason for the failure is hidden in the output of the last command in the boot_container step. It looks like you've specified `dry-dock/u14php:tip` as the image name. This should be `drydock/u14php:tip`.

**Comment by mbrodala** [comment]
@rageshkrishna Thanks, I didn't expand that message which indeed gives me a clear error message:

```
Unable to find image 'dry-dock/u14php:tip' locally
Pulling repository docker.io/dry-dock/u14php
Error: image dry-dock/u14php:tip not found
```

It now indeed fetches the image and runs all build steps. There is an error in the `ci` step but I'll open a different issue for that.

Thanks!

**Comment by mbrodala** [comment]
(Issue #2290 added)
