### ISSUE TITLE
Proper status page/updates

### ISSUE THREAD

**Issue by BenRomberg** [Shippable/support#2283]
Hi guys,

we really appreciate your great platform and use it every day.

However, it annoys us that status updates about service outages are only available by following your Twitter account. We streamline all relevant status messages (from all cloud services we're using) into our team's Slack channel, and it regularly gets flooded with status updates from your Twitter account. Most of these aren't even relevant for us, but are responses to specific customers.

If you could please provide a status page like, for example, the one on Bitbucket: http://status.bitbucket.org/ - you can easily subscribe to their feed and only get status updates when they're relevant.

Otherwise we're considering turning off status updates - with the downside of having to manually detect outages and look them up on your Twitter account. Or is there already another way?

**Comment by manishas** [comment]
This will be addressed in an upcoming update. We plan to have a Status page just like Bitbucket or GitHub.

**Comment by mbrodala** [comment]
I'm looking forward to the status page. Just to be sure: please make sure that a feed (Atom/RSS) is available on that page for subscriptions.

**Comment by manishas** [comment]
@BenRomberg @mbrodala we now have a status page live at http://status.shippable.com :)

**Comment by mbrodala** [comment]
Awesome! :-) Now I gotta wait for some issues. ;-)

**Comment by manishas** [comment]
:) 

Never thought I'd see the day when someone wants an outage :-D

**Comment by BenRomberg** [comment]
@manishas: Awesome, just subscribed. Thanks a lot!
