### ISSUE TITLE
Error received on all builds after changing subscription type

### ISSUE THREAD

**Issue by philcraven** [Shippable/support#2286]
Under Alerts:Errors
common2|_cleanRunYml|callerId:546d5db67aac73c60083a409|projectId:546d5ddcd46935d5fbbe1382|_checkInputParams Missing parameter: projectEnabledDate

**Comment by manishas** [comment]
@trriplejay we need to take a look at this asap.

**Comment by manishas** [comment]
@himanshu0503 this might have something to do with the migrations script for enabledDate

**Comment by trriplejay** [comment]
@philcraven Your project should be updated now.  Let us know if you're still seeing this issue.

**Comment by manishas** [comment]
@rageshkrishna can we ensure that other customers who upgrade do not run into this?

**Comment by rageshkrishna** [comment]
This should be fixed now.

**Comment by philcraven** [comment]
Works great!

**Comment by manishas** [comment]
closing.
