### ISSUE TITLE
Missing /root/.ssh/id_rsa

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2294]
The file `/root/.ssh/id_rsa` seems to be gone after the infrastructure change.

Where can we find the private key file associated with the public **Deployment Key** of Shippable? (As seen in the subscription settings.)

**Comment by avinci** [comment]
We are automatically adding all the keys to the ssh-agent. so you should be able to run any ssh command. In case you still need it its in /tmp/ssh on the build container.

**Comment by mbrodala** [comment]
The ssh agent solution is great but we still need the key file since our current deployment tool (Rocketeer) needs a key file.

I'll try copying the file from `/tmp/ssh/id_rsa` (?) to `~/.ssh/id_rsa` since we'd have to change our deployment configuration otherwise which must continue to work in every environment.

**Comment by avinci** [comment]
you need `cp /tmp/ssh/sub to ~/.ssh/id_rsa`

**Comment by mbrodala** [comment]
Thanks, works fine. :-)

**Comment by rageshkrishna** [comment]
@mbrodala Quick update on this... we are seeing some problems in the order in which SSH keys are offered by ssh-agent, so we've pushed a small change that will probably affect your builds.

The key you need is now located at `/tmp/ssh/00_sub`. (we added `00_` to the name)

**Comment by mbrodala** [comment]
@rageshkrishna Thankfully I've started to migrate our deployment configuration to [use the SSH agent if available](https://github.com/rocketeers/rocketeer/pull/226#issuecomment-191202081). I am using the private key for signing a `.phar` in another repository so I'll have to update that one, thanks for the heads up!
