### ISSUE TITLE
Get last run for each project

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2295]
We currently have 96 projects in Shippable, and want to build 78 of them daily. Is there any way to get the latest run for each project? With the old API, I could use `https://api.shippable.com/subscriptions/$SUBSCRIPTION_ID/searchBuilds?limit=500` and check that I had all projects. It was ugly, but it worked. 

You removed that API call without a single warning at around 4AM UTC yesterday, and I don't want to make 100 API calls for such a simple task.

How should I move forward?

**Comment by himanshu0503** [comment]
@pquentin : We have added two new API's
API - Search builds/runs (Gives you all the builds/runs for the given list of subscriptionIds/projectIds.)
For MT-CI plan
`https://api.shippable.com/builds?subscriptionIds=$SUBSCRIPTION_ID_1, $SUBSCRIPTION_ID_2&projectIds=$PROJECT_ID_1, $PROJECT_ID_1`.
For Continuous Delivery plan
`https://api.shippable.com/runs?subscriptionIds=$SUBSCRIPTION_ID_1, $SUBSCRIPTION_ID_2&projectIds=$PROJECT_ID_1, $PROJECT_ID_1`.

API - Run status (Gives you the latest status of all the projects enabled on your account)
For all plans
`https://api.shippable.com/accounts/$ACCOUNT_ID/runStatus`

Can you try using these API's and let us know if it works for you?

**Comment by pquentin** [comment]
Thank you, the undocumented route `/subscriptions/$SUBSCRIPTION_ID/runStatus` in your edit is exactly what I needed!
