### ISSUE TITLE
Syntax error in YML env section

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2296]
The builds of one of our projects currently fail after the Shippable infrastructure switch:

```
echo 'An error occurred while trying to export an environment variable. Please check your YML's env section'
/root/39900a0b-30ae-4794-a21b-86c54403ac00.sh: eval: line 58: unexpected EOF while looking for matching `''
/root/39900a0b-30ae-4794-a21b-86c54403ac00.sh: eval: line 59: syntax error: unexpected end of file
```

This did work perfectly fine before.

**Comment by rageshkrishna** [comment]
@mbrodala It seems like you have some environment variables that are not quoted. Can you please confirm whether this is the case? We no longer inject any quotes ourselves so this may be what you're running in to.

**Comment by mbrodala** [comment]
@rageshkrishna Thanks, that was the issue. One of the environment variables was a line for the `known_hosts` file with spaces and without quotes.

I've now moved this line to a file instead and add the file content to the system file during build.
