### ISSUE TITLE
"Could not open input file" after Shippable upgrade

### ISSUE THREAD

**Issue by pbosko** [Shippable/support#2297]
Hello,

We are experiencing "Could not open input file" with latest builds in build_ci step. So, I dug out a build that passed on 29.3. 15:53 and rerun it, and it too failed with this error.

> php /var/www/wt/webwiz/tools/build/class_cache.php
Could not open input file: /var/www/wt/webwiz/tools/build/class_cache.php

Commit that successfully passed build: https://app.shippable.com/builds/56d45b555009560c004797ce
The same commit fails in another build today: https://app.shippable.com/runs/56d57ceea2dd5e0c00105380

So, since it is the same commit, I guess some change on your side is affecting us.

Can you fix this, or can you tell us what to do to mitigate this problem?

Thanks

**Comment by pbosko** [comment]
First problematic build with this error was today at 12:05 (https://app.shippable.com/runs/56d5778135921e0c005bf314). Previous one happened today at 10:41 and it was successful (https://app.shippable.com/builds/56d563cdf696ab0d00da11bb).

After today at 12:05 all failed with the same error.

**Comment by rageshkrishna** [comment]
@pbosko We've identified the issue. A fix will be in very soon.

**Comment by himanshu0503** [comment]
@pbosko : Investigated your issue and found out that you're probably using the path `/home/shippable/workspace/src/github.com/projectName/` in your yml, the path of the `project` is exported in  `$SHIPPABLE_BUILD_DIR` variable.
Can you try using the `$SHIPPABLE_BUILD_DIR` variable and let us know if you run into the same issue?

**Comment by pbosko** [comment]
Yes, that's it! Thanks.
