### ISSUE TITLE
http://app.shippable.com/ (HTTP, not HTTPS) is down

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2298]
http://shippable.com/ redirects to https://app.shippable.com/, but http://app.shipable.com/ (HTTP, no HTTPS) does not redirect to https://app.shippable.com/.

This is not a theoretical issue, I was really wondering what was going on.

**Comment by avinci** [comment]
we don't support direct access to app through http. Its a redirect from www.shippable.com. I would recommend that you don't directly use that URL as we might want to change it due to routing etc. during upgrades. www.shippable.com is the right bet...
