### ISSUE TITLE
Very slow docker tag & push

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2300]
While builds are in general really fast (congratulations on this one ;-) ) the Docker commands invoked in the `build_on_success` step are extremely slow.

[This build](https://app.shippable.com/runs/56d59e4f797c670c00f6cb01) for example took 10 minutes in total to complete where the actual build was completed in < 1 minute and the remaining time was taken by the Docker commands.

Is there some issue here? Can these Docker commands be disabled or are they necessary for caching?

**Comment by avinci** [comment]
We use docker for caching. They have a layer limit due to AUFS and hence we have to commit the container and then do it. Else, if you cache the who machine, its even more slower. 

That being said, there is feature we are working on where only folders are cached and that doesnt required any docker commands. that will be coming soon.

**Comment by mbrodala** [comment]
@avinci Thanks for the info, looking forward to that. :-)

**Comment by mbrodala** [comment]
@avinci Can I speed up the current state with a manual `shippable_cache_container` call during the build?

**Comment by avinci** [comment]
not really. It does the same thing, and it allows folks to be able to get to cache at a particular stage as opposed to the last step.

**Comment by mbrodala** [comment]
@avinci OK, is there anything else I can do right now?

The delay is not really an issue for the builds itself since all of our commands are ran before the Docker tag/push but all of these long running builds take up minions thus we won't be able to run builds at busy times.

**Comment by avinci** [comment]
How much of time caching is saving you? Since we are doing a lot of optimizations on the machine itself, if you are using our generic images, you might be better off turning off caching.

I need some info wrt to where caching might and might not help you. So if you could send me email if you want to take it offline, happy to do that too. avi@shippable.com

**Comment by mbrodala** [comment]
The caching avoids re-installation of the PHP "intl" extension on every build (see #2086) and the installation of Composer dependencies. But compared to a 10 minute waiting time this is nothing, so we've disabled the cache for now. The build completes after 2 minutes now (and always fails due to #2293) but it looks good. I'll try this in various projects and builds.

**Comment by manishas** [comment]
We are addressing this with a new implementation of caching that is folder based. This will be available next week. Marking this in progress.

**Comment by manishas** [comment]
We have deployed the new caching implementation to production. Docs have also been updated - http://docs.shippable.com/ci_configure/#caching-your-container

As mentioned in the docs, simply having a ```cache: true``` in the build section of the yml will result in $SHIPPABLE_BUILD_DIR being cached. You can also choose to cache specific folders using the `cache_dir_list` tag in addition.

```
build:
  cache: true
  # cache_dir_list is optional. If not present, we will cache $SHIPPABLE_BUILD_DIR.
  cache_dir_list: 
    - dir1
    - dir2
    - dir3
```
The first build you run with cache turned on might show an error during the upload cache step but the cache should be successfully pushed during the second build and be available thereafter.

**Comment by mbrodala** [comment]
@manishas Thanks a lot for adding this, I'll test it ASAP. Am I seeing correct that the `cache_dir_list` is a list of absolute paths? Could this be amended to also support paths relative to `$SHIPPABLE_BUILD_DIR`? Thus if there is no leading slash, automatically prepend it.

This makes a bit more sense from my POV since people should not bother with absolute paths (figuring them out, keeping them updated) in their build configuration. It's also closer to [what Travis does](https://docs.travis-ci.com/user/caching/#Arbitrary-directories). ;-)

**Comment by rageshkrishna** [comment]
@mbrodala You can also use $SHIPPABLE_BUILD_DIR as part of the path, if it helps:

````
build:
  cache: true
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR/foo
    - $SHIPPABLE_BUILD_DIR/bar
````

**Comment by mbrodala** [comment]
@rageshkrishna Sure that helps (actually missed that part), but maybe make this the default prefix as suggested? What happens with a path like `foo` (without leading slash) ATM?

**Comment by rageshkrishna** [comment]
I haven't really tried it out to be honest :) As of now, specifying $SHIPPABLE_BUILD_DIR is the safest bet.

I think your suggestion makes sense. I'll get back to you on this soon.

**Comment by mbrodala** [comment]
@rageshkrishna Thanks for considering. :-)
