### ISSUE TITLE
Add time to build output/log

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2301]
There should be an output for every build step to denote how much time (in seconds) the step took. This will help a lot with identifying issues in the build/infrastructure setup.

As an example have a look at the [current Travis CI output](https://travis-ci.org/Brainsware/puppet-composer/jobs/102302116).

**Comment by avinci** [comment]
we will add this.

**Comment by mbrodala** [comment]
:thumbsup:

**Comment by avinci** [comment]
this has been added and will be deployed today.

**Comment by mbrodala** [comment]
@avinci Thanks, looking forward to this.

**Comment by mbrodala** [comment]
@avinci Thanks, looking forward to this.

**Comment by avinci** [comment]
deployed. You might want to hard refresh shippable page to get latest controller code.

**Comment by mbrodala** [comment]
@avinci I'm not seeing it ATM even after flushing caches and triggering fresh builds but I'll check again tomorrow. How should it look like?

**Comment by ankul-shippable** [comment]
@mbrodala It should look like this.

![beta_verified_step_duration](https://cloud.githubusercontent.com/assets/16793274/13746910/a5070728-ea1b-11e5-9b6b-8f53d1cfbccf.png)

**Comment by mbrodala** [comment]
Now it did show up (even for existing builds), thanks a lot!

Everything besides `build_ci` is close to 0s which reflects the speed we are seeing in our builds. :-)
