### ISSUE TITLE
Cannot open subscription page

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#2302]
When I access our organizations subscription page (https://app.shippable.com/subscriptions/540e780d3479c5ea8f9e95ac), it does not load. Angular throws an error on 
<img width="586" alt="screenshot 2016-03-01 17 22 53" src="https://cloud.githubusercontent.com/assets/2778689/13433460/3d497efc-dfd2-11e5-8416-f8cda926f8e7.png">

Ironically I'd like up upgrade our plan but that is not possible for now (then it throws this)

<img width="587" alt="screenshot 2016-03-01 17 23 23" src="https://cloud.githubusercontent.com/assets/2778689/13433472/52646fd6-dfd2-11e5-913e-975f1d88bf6b.png">

**Comment by rogierslag** [comment]
Probably related btw, but all builds for this organization are also hanging

**Comment by manishas** [comment]
this should be resolved. closing.
