### ISSUE TITLE
Getting errors in console on Subscriptions screen

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2303]
{"logType":"verbose","methodName":"subscriptions|getStateById|callerId:5490c3ac60108e0e00ef1836|subscriptionId:5490c3add46935d5fbc061a8_getSubscriptionById","id":4005,"message":"getSubscriptionById for id: 5490c3add46935d5fbc061a8","link":500}

**Comment by ric03uec** [comment]
@chriskinsman we've deployed a fix for this error. Let me know if you're still seeing this.

**Comment by manishas** [comment]
this should be fixed, so closing.
