### ISSUE TITLE
Project page never loads

### ISSUE THREAD

**Issue by calasyr** [Shippable/support#2307]
Every time we load the project page for particular project (https://app.shippable.com/projects/55c67495edd7f2c0529a0d64), we just get the spinner and a message with this JSON.
    
{"logType":"verbose","methodName":"runs|getBranchRunStatusByProjectId|callerId:55c67500edd7f2c0529a1061|projectId:55c67495edd7f2c0529a0d64|_getBuilds","id":4005,"message":"getBuilds for query: projectIds=55c67495edd7f2c0529a0d64&limit=1&isPullRequest=false&status=complete&branch=ST5S-1012-get_phone_method"}

The history page loads but there's been no build since Sunday at 10:27 pm.

Any idea what's happening with it?

**Comment by manishas** [comment]
we'll look into what's causing the error. The problem with your subscription is that you switched to the single tenant plan and have not added a build node. So your builds have no place to run.

You can switch to the Continuous Delivery plan and your builds should start running. Let me know if it works.

**Comment by calasyr** [comment]
We have the Continuous Delivery plan.

**Comment by manishas** [comment]
Yes you're now on the continuous delivery plan. Did you try to trigger a build? Are you still seeing the json errors?

**Comment by calasyr** [comment]
We've been trying to trigger a build.  Yes, we still see the JSON.

**Comment by manishas** [comment]
@rageshkrishna can we take a look at this?

**Comment by rageshkrishna** [comment]
@calasyr We've identified the root cause behind this issue. A bug in our subscription sync routine is what's triggering this error. We will have this fixed in a few hours.

**Comment by calasyr** [comment]
Awesome, thanks Ragesh.

**Comment by manishas** [comment]
this should be fixed. closing.

**Comment by calasyr** [comment]
Still getting the same behavior

**Comment by rageshkrishna** [comment]
@calasyr This should be gone now (for real!). Please try it again and let me know if you're still seeing this. Thanks! :)

**Comment by calasyr** [comment]
Now we get this error

Errorscommon2|bitbucket|normalizeBranchSha|callerId:55c67500edd7f2c0529a1061|projectId:55c67495edd7f2c0529a0d64|_getCommit Empty repositoryErrors 

https://s3.amazonaws.com/uploads.hipchat.com/184416/1325607/cz4uHBypMsDnfve/upload.png

**Comment by DavidGDragon** [comment]
@calasyr we have a fix on the way. However you may be able to fix this in the meantime. It could be your bitbucket project doesn't have a default branch. You can assign a default branch on bitbucket in the settings and try syncing, you should be able to build then.

**Comment by calasyr** [comment]
Which section of the settings page will I find that?

I don't see a way to set a default  branch, other than in shippable.yml.  And its always been set to the same thing.  

branches:
  only:
    - development

There is a way to specify a branch for the badge, but that just provides the code for the badge and there's no way to save it.

**Comment by DavidGDragon** [comment]
@calasyr you set the default branch on your provider, so bitbucket.org in the repository's settings page, 'main branch' option. Then sync the project on shippable

**Comment by calasyr** [comment]
That's set to master

**Comment by calasyr** [comment]
To answer your other question, I invoked from the build button for the development branch
![shippablehowinvoked](https://cloud.githubusercontent.com/assets/2043511/13508699/ec4c888e-e13c-11e5-8fb2-5db1340ad5df.png)


There is also an automatic web hook, but that hasn't worked since Sunday.

**Comment by DavidGDragon** [comment]
@calasyr does this error happen every time you try to build?

**Comment by calasyr** [comment]
I was asked me how I started the build.  The image is showing you the page from which I kicked it off.

458 is the one presented on the project status page from last Sunday.  Pressing the build button SHOULD be creating a new build and thus a newer build number.

**Comment by calasyr** [comment]
Does this fail every time we build? Yes, I just retried and got this:

common2|bitbucket|normalizeBranchSha|callerId:55c67500edd7f2c0529a1061|projectId:55c67495edd7f2c0529a0d64|_getCommit Empty repository

**Comment by manishas** [comment]
We've identified the problem. We are not handling spaces in project names correctly. We'll have a fix for this today.

**Comment by calasyr** [comment]
Thanks, Manisha.

**Comment by ric03uec** [comment]
@calasyr the fix for this is now deployed. Can you please verify if your builds are working correctly now?
thanks

**Comment by calasyr** [comment]
Yes, the tests are now starting.  Not really finishing, but that's most likely our problem.

Thanks for fixing this.
