### ISSUE TITLE
Yml merge for PR failed

### ISSUE THREAD

**Issue by pbosko** [Shippable/support#2309]
Hello,

Yesterday (Mar 1st 16:26) a commit passed all tests in this build: https://app.shippable.com/runs/56d5b4a601e5670d00aae83d

Now (Mar 2nd 9:13) the same commit fails in another build with message "Yml merge for PR failed", in Alerts section. Build link: https://app.shippable.com/runs/56d6a09fe494ba0c0089ab2d

Since this is first step in build process, I guess there is not much we can do about it.

**Comment by manishas** [comment]
@pbosko is this still an issue?

**Comment by pbosko** [comment]
@manishas New commits are not experiencing this error. Rebuild of given build is still reproducing it, but we can live without it.

**Comment by manishas** [comment]
I am closing this issue but it becomes a problem for multiple customers we will revisit it.

**Comment by brianpmaher** [comment]
I'm seeing this issue as of today.

Issue happens on one PR only and rebuilds throw the same error. Other PRs are building fine.

**Comment by bwaite-jaroop** [comment]
One of our private repositories is breaking with the same error after updating to the new shippable yml spec. Rebasing the branch to be up-to-date with master does nothing, neither does closing the PR and making a new one, or amending commits to force a new hash.

**Comment by manishas** [comment]
@bwaite-jaroop can you open up a new issue and include the your yml?
