### ISSUE TITLE
chown: invalid user: ‘shippable.shippable’

### ISSUE THREAD

**Issue by pbosko** [Shippable/support#2310]
Hello,

On March 1st 16:26 (GMT+1) a commit passed all tests in build: https://app.shippable.com/runs/56d5b4a601e5670d00aae83d

When I merged that commit on March 2nd 08:01 (GMT+1) build for merge commit https://app.shippable.com/runs/56d68fc06c92f40c002b0aa2 failed with message "chown: invalid user: ‘shippable.shippable’"

Any workarounds you might suggest? Will this be a permanent change?

Thanks

**Comment by rageshkrishna** [comment]
Hi @pbosko. Builds only run as `shippable` user on shippable/minv2. Moving forward, every build will run as `root`.

**Comment by pbosko** [comment]
OK. Thanks. That helped me pass that step.
