### ISSUE TITLE
drydock/u14rub:prod missing packages

### ISSUE THREAD

**Issue by cratz** [Shippable/support#2313]
Looks like there are missing packages in `drydock/u14rub:prod` image to run `bundle install` successfully.

```
/usr/local/rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
```

"build_ci" section in this build:
https://app.shippable.com/runs/56d6a965ac215a0c00bddf8e

**Comment by rageshkrishna** [comment]
@chetantarale Let's get this sorted out today.

**Comment by manishas** [comment]
@chetantarale we need daily status on issues in progress. Can you please update status on this ASAP?

**Comment by chetantarale** [comment]
I have built u14rub, u14pls and u14all imges, but the builds are failing for u12 images because i=of missing dependencies. This was happening because in our pls and all images we are installing chrome.and google is no longer supporting chrome32-bit. we have a fix for it and are implementing it.

**Comment by chetantarale** [comment]
Goal for today is to build all ruby images with the missing packages and push to dockerhub.

**Comment by chetantarale** [comment]
we have opened an internal issue for patching the images.Currently working on the design and will post the updates on the progress.

**Comment by chetantarale** [comment]
@cratz We have added missing packages to all the ruby images, can you please try and let us know if you run into the same issue again.

**Comment by cratz** [comment]
@chetantarale 
Thanks I will try it asap.

**Comment by cratz** [comment]
@chetantarale 
I'm still not able to use default ruby image for our build because of missing libraries but I'm not able to reopen this issue.

Build:  https://app.shippable.com/runs/56efd8c3ca1aa60d00fda642
```
Installing pg 0.18.4 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.2.4/bin/ruby -r ./siteconf20160321-2909-smonfa.rb extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

If this image is intended to work similar to the old `shippable/minv2` image you should not be that restrictive with pre-installed libraries.
Of course I can install all needed packages by my self but this will increase build time by factor 2 or 3. I keep using old minv2 image since this is working.

I run into another issue related to the ruby image.  I have the following in my shippable.yml
```
rvm:
  - 2.2.4
```
Everything is working with the `minv2` image. After I switched to the default ruby image (drydock/u14ruball:prod) I have to run `rvm use 2.2.4` from `shippable.yml` otherwise it will use `ruby 2.2.1p85`.
I added some debug output for this issue in this build : https://app.shippable.com/runs/56efd8c3ca1aa60d00fda642

After all this issues I will just use the old image since I have no more time yet to debug your images or build my own CI image.

**Comment by chetantarale** [comment]
@cratz we have identified all the missing packages in our images and here is the list.

```
zlib1g-dev
libssl-dev
libreadline-dev
libyaml-dev
libsqlite3-dev
libxslt1-dev
libcurl4-openssl-dev
libffi-dev
libcurl4-gnutls-dev
libopenssl-ruby
libmysqlclient-dev
libpq-dev
ruby-dev
libxslt-dev
libxml2-dev
libpq5
rake
libncurses5-dev
libxslt-dev
libxml2-dev
libevent-dev
chrpath
libfontconfig1-dev
libqt4-core
libqt4-dev
libqt4-gui
x11-xkb-utils
qt4-dev-tools
```
Can you please help us here and let us know what packages you need so we can incorporate them in our images.

**Comment by cratz** [comment]
@chetantarale 
Of course I can help you but I can't tell you when I will have time for this.
I will try to get back to you until the end of this week.

**Comment by chetantarale** [comment]
@cratz Thank you very much. We will wait for you to get back.

**Comment by manishas** [comment]
@cratz can you let us know which packages you're looking for?

**Comment by manishas** [comment]
@cratz i am closing this issue, but please let us know which packages you need and we can reopen.

**Comment by cratz** [comment]
Hi,
OK thx, I will. 
Sorry for not getting back to you but I have no time currently and since the old image is working this issue is not critical for us.
