### ISSUE TITLE
A commit on one project led to four builds

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2314]
Here are the four builds in question:

- 60: https://app.shippable.com/runs/56d6baa787a3710b0041a362
- 61: https://app.shippable.com/runs/56d6baa76b86640c0041ef6d
- 62: https://app.shippable.com/runs/56d6baa7300cbc0d0096cc71
- 63: https://app.shippable.com/runs/56d6baa787a3710b0041a385

We canceled manually the builds 61, 62 and 63.

**Comment by rageshkrishna** [comment]
@pquentin The only reason I can think of for this to happen is that we received multiple webhooks from BitBucket. Would you mind checking your project's webhook settings page on BitBucket to confirm this? This should be at https://bitbucket.org/{yourOrg}/{yourRepo}/admin/addon/admin/bitbucket-webhooks/bb-webhooks-repo-admin

**Comment by pquentin** [comment]
@rageshkrishna There are four `Shippable_Webhooks` in this project: I'll remove the last three.

**Comment by manishas** [comment]
closing this issue.
