### ISSUE TITLE
Can't connect to [local] MySQL

### ISSUE THREAD

**Issue by pbosko** [Shippable/support#2316]
Hello,

In latest builds a new error started to show up.

In this build https://app.shippable.com/runs/56d6c7306b86640c00466432 we got:
> mysql --force mysql < /home/shippable/tzdata.sql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

I tried to switch MySQL to connect over TCP in build https://app.shippable.com/runs/56d6c9b6d6078c0c006048c4 but got error:
> mysql -h 127.0.0.1 -P 3306 --force mysql < /home/shippable/tzdata.sql
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

It used to work nice. You can check build https://app.shippable.com/runs/56d5b4a601e5670d00aae83d that had the same config and that ran fine.

What can we do?

**Comment by rageshkrishna** [comment]
In the new build system, we no longer start mysql or postgres by default. Please update your YML file to include this:

````
services:
  - mysql
  - postgres             #if you need it
````

**Comment by pbosko** [comment]
OK. Thanks. That helped me pass that step.

**Comment by cratz** [comment]
@rageshkrishna 
sorry but adding `- postgres` to services will not start the postgres server [check this build](https://app.shippable.com/runs/56d6d2c4afeb620c007241ab)
A working solution how to start postgres is described here #2304
