### ISSUE TITLE
New project enabled - but auto deploy to AWS EB is not triggered?

### ISSUE THREAD

**Issue by jlsupport** [Shippable/support#2317]
Hi, I just enabled a new project today, and setup deployment to AWS EB, but when i run a build its not deploying to EB?

**Comment by manishas** [comment]
we're looking into this...

**Comment by manishas** [comment]
@jlsupport can you point us to the new project?

**Comment by jgregors** [comment]
I am having this problem as well... my project is osden/platform (from a bitbucket project).

**Comment by jlsupport** [comment]
@manishas the project name is restudyaps/automatic-platform-restudy

**Comment by ttrahan** [comment]
@jlsupport we're resolving the issue on the backend.  In the meantime, if urgent, I can help you set up a workaround to get deployments into EB working.  Please let me know if you'd be interested in this.

**Comment by jlsupport** [comment]
@ttrahan what is the timeframe? if its not to long it can wait

**Comment by ttrahan** [comment]
@jlsupport : it should be resolved within next 1-2 days.

**Comment by ttrahan** [comment]
@jlsupport: we had hoped to have this resolved by today, but ran into some additional issues.  work is underway, but will take a bit more time.  i'll post an update shortly with a revised estimate.

**Comment by jlsupport** [comment]
Hi @ttrahan any update on this? :)

**Comment by ttrahan** [comment]
Hi @jlsupport : we're halfway through the 2nd of 3 engineering tasks defined for resolving this.  I expect we'll see this finished within the next several days, though I'm not able to say the exact day.  

In the meantime, take a look at these two examples that show how to configure EB deployments directly within your yml.  A similar approach may work for you while we're finishing the changes.

EB source code deployment: https://github.com/ttrahan/node-express-eb
EB Docker deployment: https://github.com/ttrahan/micro-api/tree/amazon-eb-cli-beta

**Comment by ttrahan** [comment]
@jlsupport : good news - the EB source code deployment is now live in production.  Updated docs are still to come, but you can use this now with the following instructions:

1.  On your Project Settings page, add a Deploy Integration to your project.  This will enable authentication into AWS.  Here's a screen shot of my Project Settings page with me adding the Deploy Integration 'AWS - ttrahan' to my project.
  ![image](https://cloud.githubusercontent.com/assets/4467650/13789836/0607460a-eaa3-11e5-81e3-355be6e9f6dc.png)

2.  Update your `shippable.yml` with the new collection for deployments.  Here's the form for doing a source code deployment to EB:

  ```
integrations:
  deploy:
    - integrationName: "AWS - ttrahan"
      type: aws
      target: ebs_paas
      platform: "Node.js"
      application_name: expressapp
      env_name: expressapp-dev
      region: us-east-1
```
You'll replace with your values as follows:
**integrationName**: replace 'AWS - ttrahan' with your Account Integration set up for AWS (keep the double quotes)
**platform**: replace 'Node.js' with your platform (available options can be found [here](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/tutorials.html))
**application_name**: replace with your EB application name
**env_name**: replace with your EB environment name

The sample project for source code deployments above has been updated with this setup:
https://github.com/ttrahan/node-express-eb

**Comment by jlsupport** [comment]
Hi @ttrahan 
thanks a lot, now i migrated my shippable.xml but it looks like the deploy is running from inside my docker image? on the old setup it did run from outside?

**Comment by ttrahan** [comment]
@jlsupport: you're correct that the EB deployment steps are happening from inside your build container at the conclusion of all build steps that occur within the container (ci, post_ci, after_success, after_failure).  Previously, these steps occurred in a sidecar container that Shippable ran alongside your build container.  Keep in mind that your build container does not necessarily match your Docker image that you push to EB.  It will depend upon your specific build steps configured in your yml.

If you need to do the EB deployment from outside the build container, you can do this by leveraging the shippable.yml build sections that run on the host (pre_ci, push).

**Comment by abhijitkini** [comment]
The [documentation on deploying to Elastic Beanstalk](http://docs.shippable.com/ci_configure/#aws-elastic-beanstalk) has been updated.

**Comment by ttrahan** [comment]
@jlsupport : we've completed the updates to our EB deployment integration and updated the documentation.  please re-open this issue if you continue to have issues deploying to EB.
