### ISSUE TITLE
mysql_tzinfo_to_sql dissapeared

### ISSUE THREAD

**Issue by pbosko** [Shippable/support#2318]
Hello,

We're getting error:
> mysql_tzinfo_to_sql /usr/share/zoneinfo > /home/shippable/tzdata.sql
/root/8bedc192-1393-4e33-a617-282c8e1d4ced.sh: line 58: mysql_tzinfo_to_sql: command not found

in build https://app.shippable.com/runs/56d6d142afeb620c0071e298

It used to be available as it was in build https://app.shippable.com/runs/56d5b4a601e5670d00aae83d

Any suggestions how to install it now? It seems that listing mysql in services isn't enough.

**Comment by manishas** [comment]
@pbosko we will take a look at why you're running into this with the new images. Can you share your yml so we can try to reproduce thus problem?

In the meantime, to be unblocked, you can explicitly pull the old build image by addign the following in your yml:

```
pre_ci_boot:
    image_name: shippable/minv2
    image_tag: latest
    pull: true
```

Let me know if that works.

**Comment by manishas** [comment]
@rageshkrishna we need to look into this asap.

**Comment by ric03uec** [comment]
@pbosko 
- can you add following line in the `ci` section 
```
export PATH=$PATH://usr/local/mysql/bin/
```
we missed out adding this by default and will fix the issue shortly. in the meantime, this patch should work

@rageshkrishna  we need to add `/usr/local/mysql/bin/` to the path for all images that have `mysql` on them

**Comment by manishas** [comment]
assigning to chetan.

**Comment by rageshkrishna** [comment]
@pbosko This should be fixed now. Please try a build and let me know how it goes.

**Comment by pbosko** [comment]
I've added MySQL bin dir to $PATH, but it seems that builds are working since you switched us back to shippable/minv2. I get that's the case since user executing build is again shippable, and not root as I have been suggested to update shippable.yml to in #2310.

**Comment by pbosko** [comment]
OK. It again works without path specified. But user executing build is shippable and not root. So I guess I didn't test it on your next image.

**Comment by manishas** [comment]
Closing this issue. @pbosko please let us know if this happens again.
