### ISSUE TITLE
Shippable prefers travis

### ISSUE THREAD

**Issue by taynaud** [Shippable/support#2319]
Hello,

When there are both a .travis.yml and .shippable.yml, shippable use the travis one. 

I do not think it is very intuitive to use another service configuration first.

**Comment by manishas** [comment]
you're right. We did not do this earlier, so must be a recent bug. we'll take a look.

**Comment by manishas** [comment]
tagging @rageshkrishna so this gets picked up today.

**Comment by himanshu0503** [comment]
@taynaud : We've identified the problem, a fix will be available very shortly.

**Comment by himanshu0503** [comment]
@taynaud : This is now in production. Can you please verify?

**Comment by taynaud** [comment]
Seems good, thanks
