### ISSUE TITLE
Incorrect values in Elastic Beanstalk config dropdown

### ISSUE THREAD

**Issue by ttrahan** [Shippable/support#2320]
When configuring a deployment integration in the Project Settings page for Elastic Beanstalk, user is prompted to select a AWS account integration to use.  The list includes account integrations that are not type = AWS.

![image](https://cloud.githubusercontent.com/assets/4467650/13472883/acb6c594-e06b-11e5-8f9a-83938df8e1f8.png)

**Comment by DavidGDragon** [comment]
beta verified www 5371
