### ISSUE TITLE
`/subscriptions/:id/runStatus` API shows deleted but redirected BitBucket projects

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2321]
`/subscriptions/:id/runStatus` shows deleted BitBucket projects that were redirected to another BitBucket project. Interestingly, it does not appear to happen with `/accounts/:id/runStatus`.

**Comment by manishas** [comment]
@pquentin this is fixed and deployed. please let us know if it doesn't work for you.

**Comment by pquentin** [comment]
Thanks, it works perfectly.
