### ISSUE TITLE
PHP code coverage parse error

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2323]
I am seeing the following [error](https://app.shippable.com/runs/56d85bd503f4c90c00fc232d) in the `parse coverage reports` step:

```
reports --destination /shippableci/coverageresults coverage --source /root/src/<host>/<project>/shippable/codecoverage
time="2016-03-03T15:46:16Z" level=error msg="Failed to marshal json result:json: unsupported value: NaN" 
Successfully wrote results to coverageresults.json
```

Thus no coverage reports are available. The coverage was generated by `phpunit/php-code-coverage` version 2.2.4 and `phpunit/phpunit` version 4.8.23.

**Comment by ric03uec** [comment]
@mbrodala the coverage reports should parse correctly now. can you please check and verify if its working for you

**Comment by manishas** [comment]
this is complete. closing.

**Comment by mbrodala** [comment]
@manishas Sorry, I'm [still seeing](https://app.shippable.com/runs/56dd3f4e0877220e002b5bb0) exactly the same error. Can you have a look at this once more?
