### ISSUE TITLE
Permissions for apache2 user (`www-data`) on `/root`

### ISSUE THREAD

**Issue by daniel-sc** [Shippable/support#2324]
Hi,

for some unclear reason the apache2 user (`www-data`) has no read/browse access to `/root`, even though the permissions were correctly set via `sudo chmod a+rx /root`.

The setup is a ubuntu14 image (based on https://github.com/shippableImages/ubuntu1404_base ).
When listing the directory in shippable.yml (as root) everything looks fine:

> total 168
> drwxr-xr-x  14 root root  4096 Mar  3 16:59 .
> drwxr-xr-x 100 root root  4096 Mar  3 16:59 ..
> -rwxr-xr-x   1 root root 31242 Mar  2 12:40 0d6dca18-8cbc-43f8-9043-7b191249745e.sh
> -rwxr-xr-x   1 root root  7099 Mar  2 12:40 3e405a81-9e78-47f2-9697-65410a35ec09.sh
> -rwxr-xr-x   1 root root  7964 Mar  2 12:24 63ffab09-b2f9-4bc9-8ff0-6039db8d2f81.sh
> -rwxr-xr-x   1 root root 31223 Mar  2 12:24 7f0db1d8-3d27-4935-9d0d-cffb199ead29.sh
> -rwxr-xr-x   1 root root  7964 Mar  3 16:59 a3be856f-1ee5-4e88-8a7c-50f284484729.sh
> drwxr-xr-x   4 root root  4096 Mar  2 12:36 .ansible
> -rw-r--r--   1 root root  3106 Feb 20  2014 .bashrc
> -rwxr-xr-x   1 root root 28351 Mar  3 16:59 c45a1435-d8c8-47fe-86a0-bbf2b37de3c3.sh
> drwxr-xr-x   3 root root  4096 Mar  2 12:24 .composer
> drwxr-xr-x   3 root root  4096 Mar  2 12:24 .distlib
> -rw-r--r--   1 root root   179 Mar  2 12:36 .google_libcloud_auth.integral-cell-662
> drwxr-xr-x   2 root root  4096 Mar  3 16:59 logs
> -rw-r--r--   1 root root   140 Feb 20  2014 .profile
> drwxr-xr-x   3 root root  4096 Mar  2 12:36 .qws
> drwxr-xr-x   8 root root  4096 Mar  3 16:59 shippable_ve
> drwxr-xr-x   2 root root  4096 Mar  3 16:59 .ssh
> drwxr-xr-x   4 root root  4096 Mar  3 16:59 workspace

but when executing this as `www-data` using the command `sudo -u www-data -s /bin/bash -c "ls -la /root"` the result is: `ls: cannot open directory /root: Permission denied`

This is a serious problem, as apache needs access to all folders that lead to the document root - which is of course `$SHIPPABLE_REPO_DIR`.

This gave me already big headaches - any suggestions?

**Comment by manishas** [comment]
@daniel-sc can you share a build link please?

**Comment by daniel-sc** [comment]
@manishas sure: e.g. https://app.shippable.com/builds/56d86ab05356400c00f55404

**Comment by a-murphy** [comment]
I haven't been able to list the files in ```/root``` in a shippableImages/ubuntu1404_base image (before or after changing the file permissions) without ```sudo``` either.  It might be because ```/root``` is the root user's home directory since this does not occur when listing files in another user's home directory.

**Comment by daniel-sc** [comment]
Additional note: When running this image locally (Boot2Docker on VirtualBox) this issue does _not_ occur!

**Comment by stephanielingwood** [comment]
Hey, @daniel-sc. I pulled your two latest images (tags ending in v2 and v3) and ran those images using the docker cli. In both of those images, trying to execute
`sudo -u www-data -s /bin/bash -c "ls -la /root"`
fails with
`ls: cannot open directory /root: Permission denied`. It's worth noting that in those images, the permissions on /root are rwx------.

However, I then executed 
`chmod a+rx /root`
in the containers running your images. I could then execute
`sudo -u www-data -s /bin/bash -c "ls -la /root"`
without problem.

I noticed, too, that the build logs don't show that you've executed `chmod a+rx /root` in the build. I would suggest doing either:
- adding `chmod a+rx /root` to your yml, before www-data is trying to access /root, or
- changing the permissions on the root directory in your local version of the image, committing, tagging, and pushing that image, and then updating the image name/tag in the Docker Options section of your project settings on Shippable.

Either of these options will ensure that we're running the container with the correct permissions on the /root directory at build time. If you're still seeing the error after that, then we can investigate further.

**Comment by daniel-sc** [comment]
Hi @stephanielingwood thanks for looking into this!

Before the chmod was a little hidden - I made it more explicit in https://app.shippable.com/builds/56dd5ba6941ca60c00b6ec0f (see the "before script" section).

As I tried to indicate above the same thing does only happen when running the build on shippable.com - I cannot reproduce this via docker cli as well!

Please let me know if you need more information!

**Comment by stephanielingwood** [comment]
Hi @daniel-sc,

Thanks for the clarification. I played around with your images some more today, and here's what I found:

If I run your images in a build just like yours, and with the chmod in the before_script step, they indeed fail on that  `sudo -u www-data -s /bin/bash -c "ls -la /root"`. Boo.

However, we just upgraded our build system. In that new system, we are bringing up the docker containers in a different manner (it allows for docker-in-docker scenarios, amongst other things). I ran your build in that new system, and good news: it worked!

What this means for you: if you're willing, we can change you over to the new build system. To do that, you will need to make a couple changes to your project settings and your yml.  They are:
- New yml format:
  - You'll get the best results if you transition your existing yml to our new format. It's not required, unless you have SSH keys you're currently including in secure env variables. Documentation on the new yml format is here: http://docs.shippable.com/ci_configure/
- SSH keys:
  - If you have any ssh keys you're including in secure env variables, you'll create integrations for them instead. To do this, go to account settings, and then create them on the integrations tab.
  - Next, go to your project's page. Click on the settings tab. Look for the integrations section. There, add your SSH keys. The SSH keys will then be available in your build container.
- Pulling your image:
  - Add your docker credentials as a project integration. This is in the integrations panel on the project settings tab.
  - In the new yml, specify the image and credentials.  Below is a sample of the yml I created to test your image.

Let me know if you want us to switch you to the new build system. If you have questions about the new yml format, we're happy to help. 

Sample yml:
```
language: node_js

node_js:
    - 0.10.33

build:
    pre_ci_boot:
        image_name: yourDockerRepo/yourImageName
        image_tag: yourImageTag
        pull: true
    ci: 
        - whoami
        - ls -la /
        - chmod a+rx /root
        - ls -al /
        - sudo -u www-data -s /bin/bash -c "ls -la /root" 

integrations:
    hub:
      - integrationName: stephanieDocker
        type: docker
```

**Comment by daniel-sc** [comment]
@stephanielingwood thanks for the investigation! Yes please switch this project over to the new build system - I'll change the shippable.yml accordingly.

**Comment by stephanielingwood** [comment]
@daniel-sc Great. We just changed you over to the new plan and build system. Once you get the new yml in place, you shouldn't see that permissions error anymore. 

We'll keep this issue open until you let us know the results of your new builds. In the meantime, if you need help migrating to the new yml, you might find this blog post helpful: http://blog.shippable.com/migrating-to-the-new-build-platform

**Comment by manishas** [comment]
Closing this issue since the problem has been addressed. @daniel-sc please let us know if it doesn't work and we'll reopen.
