### ISSUE TITLE
Builds just stopped working - AWS cli tools not found!?

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2325]
I'm using shippableimages/ubuntu1404_nodejs for the build.

![screenshot 2016-03-03 15 48 49](https://cloud.githubusercontent.com/assets/823555/13505316/72836b56-e157-11e5-939d-dd3817fbe809.png)

**Comment by manishas** [comment]
can you change the image to drydock/u14nod:prod and try again?

**Comment by npahucki** [comment]
Did that, fails with another problem now:
![screenshot 2016-03-03 16 10 32](https://cloud.githubusercontent.com/assets/823555/13505993/8e5cdddc-e15a-11e5-82d8-1276fea97b0a.png)

**Comment by manishas** [comment]
@ric03uec can we look into this?

**Comment by ric03uec** [comment]
@npahucki can you tell me the build id

**Comment by manishas** [comment]
@ric03uec 56d88b835356400c00fc6988

**Comment by manishas** [comment]
@npahucki we have tracked down the problem and are working on a solution.

**Comment by npahucki** [comment]
I have some additional information here. 

A can see a few things going wrong in the build with the drydock/u14nod:prod image and my scripts. 

1) Because Shippable assumes that the source code to build is right in the root of the repo  that it checks out and ours is NOT, I had to hack the YML file a bit and use an ENV var that I had found by looking at the script tab in the build console so that I could cd to the source dir, then get back to the original dir after my ci build ran. That variable $SHIPPABLE_REPO_DIR seems to renamed in the current image to $SHIPPABLE_BUILD_DIR. You might want to revisit the assumption that the CI build stuff is in the root of the repo checked out from git. 
2) However changing this env var to use the new one did not fix the issue as it seems that the 'after_script' section of the YML file is being completely ignored, so my 'cd' statement to go back to the root of the repo does not get run, and therefore the Dockerfile is not found in the next step. 
3) Is the format of the YML file changing? The [current documentation](http://docs.shippable.com/ci_configure/) looks quite a bit more complicated than stuff I set up just two weeks ago. For how long are you planning backward compatibility for the old scripts? I've already spent all the time I had allotted to get CI working last week, I'll be hard pressed to find time to rewrite and test (a VERY slow process!) a completely different version of the shippable.yml. Are you going to provide a migration path, or are we on our own?



I hope this sheds some light on the topic.

**Comment by npahucki** [comment]
Ok, so i decided to try the new format. As I expected it's anything but smooth, and now I am stuck. It refuses to find my integrations names. I even created new ones with no spaces in the name and I still get an error saying that the integrations are not found. 

from my YML : 
```integrations:
    notifications:
      - integrationName: slack_notifications
        type: slack
        recipients: builds
#        branches:
#            only:
#              - master
#              - dev
        on_success: always
        on_failure: always
    hub:
      - integrationName: main_ecr
        type: ecr
#        branches:
#          only:
#            - develop
```

My integrations page clearly showing integrations using those names:
![screenshot 2016-03-04 11 27 58](https://cloud.githubusercontent.com/assets/823555/13529721/57dae572-e1fc-11e5-9f6a-faf295267350.png)

Yet the build fails immediately:
![screenshot 2016-03-04 11 23 41](https://cloud.githubusercontent.com/assets/823555/13529735/6ccb88d8-e1fc-11e5-83e6-827a5dab446b.png)


I starting to get really really frustrated with this whole Shippable system, please help me get this figured out TODAY before I throw my arms up and try an alternative.

**Comment by manishas** [comment]
@npahucki can we jump on a hangout again today? Let me know what time works. 

Regarding the error you are seeing - do you have the integrations in your project settings as well? 

You'll need to go to project settings and select the hub integration from the dropdown and same for notifications.  -

**Comment by manishas** [comment]
![image](https://cloud.githubusercontent.com/assets/2983749/13530594/006779b0-e1d7-11e5-99b2-1486b35b9745.png)

**Comment by npahucki** [comment]
Ok, I had them added already, but they were named with spaces and it would not find them. I recreated with no spaces in the names, but then thought that having them in the account integrations was enough. i added the new ones to the project settings and I am now past this issue, trying to figure the next one.

**Comment by manishas** [comment]
this is resolved. closing.
