### ISSUE TITLE
Error messages EVEN more useless than before!

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2326]
Someone forgot to stringify the JSON error message:

![screenshot 2016-03-04 11 28 25](https://cloud.githubusercontent.com/assets/823555/13529809/d81e7ac8-e1fc-11e5-8b47-8aac45236a5e.png)

**Comment by manishas** [comment]
@DavidGDragon we have to fix this.

**Comment by DavidGDragon** [comment]
beta verified www 5417

**Comment by manishas** [comment]
this is deployed to prod. closing.
