### ISSUE TITLE
JDK version ignored - sometime since March 2nd

### ISSUE THREAD

**Issue by mgladdish** [Shippable/support#2327]
My project uses Java 8. It was building happily as recently as March 2nd.
The next build, on March 4th, failed due to using Java 7.

My shippable.yml (which hasn't changed):
```
language: scala
scala:
    - 2.11.7
jdk:
   - oraclejdk8
```

Output in your console:
```
setup_jdk
  sudo update-alternatives --set java /usr/lib/jvm/java-7-oracle/jre/bin/java
update-alternatives: using /usr/lib/jvm/java-7-oracle/jre/bin/java to provide /usr/bin/java (java) in manual mode.

  sudo update-alternatives --set javac /usr/lib/jvm/java-7-oracle/bin/javac
update-alternatives: using /usr/lib/jvm/java-7-oracle/bin/javac to provide /usr/bin/javac (javac) in manual mode.
```

And 
```
build_ci
  javac -version
javac 1.7.0_72
```

How can I get shippable to use Java 8 to build my project again?

**Comment by manishas** [comment]
@mgladdish we moved your account to the new build system to fix the notifications issue but looks like you're running into this new problem now.

I will move you back to the old system until we can repro your scenario and take a look at why this isn't working. Give me a couple of hours and I will let you know when you're back on the old system.

**Comment by mgladdish** [comment]
And, ironically, I still got email notifications for these broken builds.

I'm rapidly running out of confidence in Shippable. The bugs just keep coming, and really disrupting my development. The open issues list is really grim reading for any system, never mind one whose entire purpose is to support continuous integration and automated testing.

**Comment by manishas** [comment]
Build notifications for broken builds are always turned on by default. You need to turn them off if you don't want to get them.

In the old system that was by specifying:

```
notifications:
    email: false
```

On the new system it is:

```
integrations:
    notifications:
      - integrationName: email
        type: email
        on_success: never
        on_failure: never 
```
Docs for the new config are at http://docs.shippable.com/ci_configure/#email-notifications

When you are transitioned back to the old system, you will run into the notifications issue again but that is better than build failing.

Sorry about the problems you're running into. We're working to fix them.

**Comment by kelebra** [comment]
I face the very same issue. Any suggestion on fix?

**Comment by ric03uec** [comment]
@mgladdish @kelebra this should now be working correctly for you. Can you guys test your builds and confirm.

**Comment by mgladdish** [comment]
@ric03uec Nope.

Build usually takes between 6-12 minutes. It's been running for 25 mins and counting, having only written this to the console:

```
  Provision job node
  Info
Provisioning a node for subscriptionId: 562f3ecd1895ca4474213df2
```

**Comment by mgladdish** [comment]
@ric03uec Tried again.

This time it's been running for an hour(!) with this as the last entry in the `build_on_success` section:
```
  /usr/bin/sudo su -c "docker export c.exec.uxforms-accounts-api.42.1 | docker import - 690089443214.dkr.ecr.us-east-1.amazonaws.com/562f3ecd1895ca4474213df2:561fbd8b1895ca44741dff9d"
```

**Comment by avinci** [comment]
A few questions...and maybe I can help.
do you have cache turned on? Can you try it without cache? What image are you building on? If this is minv2 and if you have cache, we are caching a massive image. I would try and switch to our smaller images that might give you better perf and they have all the latest updates. 

You can set it in `pre_c_boot` section. Here is more help if you would like and it should also have images that we have for each language.  http://docs.shippable.com/ci_configure/

**Comment by mgladdish** [comment]
@avinci  Now this build has apparently moved back to the 'old' system, does the new .yml format work on the old system?

I've not changed the cache or image settings since it used to work semi-reliably.

But yes, cache is turned on (in an attempt to keep build times acceptably short - hint: even the usual 23 mins for a compile and test run is nuts when it takes ~ 2 minutes on my own machine).
Yes, I was using the default image.

I've just tried turning the cache off and using the `u14scapls` image - let's see if that's any better.

To be honest I'm just grateful I hadn't moved my production build pipeline to shippable yet or else I would have been utterly screwed. I'm going to have to take my builds off here and recommend my colleagues and clients don't use this service either. The repeated and regular critical bugs out of nowhere aren't even remotely acceptable, especially on such a critical service.

It's a shame - I really like the idea of the Shippable service, it's let down by a poor implementation.

**Comment by manishas** [comment]
@mgladdish you are still on the new build system. We figured out what was happening with your build, so did not need to move you back to the old one.

**Comment by mgladdish** [comment]
@avinci So it looks like just re-running the build was enough to get it to work again :(

I added this to my shippable.yml:
```
pre_ci_boot:
  image_name: u14scapls
```

But then saw this in the console:
```
pull_job_image
  sudo docker pull shippable/minv2:latest
```

So I evidently either got the syntax wrong for the image or the syntax isn't accepted by your 'old' system,

**Comment by manishas** [comment]
maybe you missed my earlier message - you are on the new build system.

you need the following information in the pre_ci_boot section:

```
pre_ci_boot:
    image_name: drydock/u14scapls
    image_tag: prod
    pull: true
```

**Comment by mgladdish** [comment]
Yeah, I think our messages crossed over the wires somewhere.

I'll try that out. 

Although by now this is just to tide me over until I get all my builds on to my own build infra and off Shippable. This has been one critical bug too many for me.

**Comment by manishas** [comment]
Your builds are working now and the original problem has been addressed. Closing this issue.

Good luck.
