### ISSUE TITLE
Badge isn't showing correct status

### ISSUE THREAD

**Issue by clifg** [Shippable/support#2330]
My project badge just shows "run | none", even though my latest build succeeded. Doesn't matter which branch I use. Here's my current badge url:
https://api.shippable.com/projects/56b6dbab1895ca4474738165/badge?branch=master

**Comment by manishas** [comment]
Build badges will be available as soon as your subscriptions are migrated to our new build system in the next few days. I'll update you when the migration is done.

**Comment by lizrush** [comment]
@manishas any news on this one?

**Comment by manishas** [comment]
@lizrush your subscription hasn't been updated yet. We are migrating most subs this week so it should be soon. If you want to get a jump start, you can switch to the continuous delivery plan in the Billing tab of your Subscription page and from the next build onwards, your badge should start working as expected.

**Comment by lizrush** [comment]
@manishas That's okay, I'll let it resolve by itself. Just hadn't seen any user messaging from within Shippable to know this was happening. Next time would appreciate a note or info about the status from within the app instead of having to search support, but I'm ok waiting for this migration to happen! Thanks.

**Comment by aug70** [comment]
@manishas seems to be working fine now...

**Comment by clifg** [comment]
Not sure why this issue has been closed. My badge is _still_ not working. Just click the link in the original post to see.

**Comment by lizrush** [comment]
Still not working for me either: [![Run Status](https://api.shippable.com/projects/56a12f721895ca447472408e/badge?branch=master)](https://app.shippable.com/projects/56a12f721895ca447472408e)

**Comment by manishas** [comment]
I am going to reopen this and leave it open until both accounts are migrated and the badges are available.

**Comment by clifg** [comment]
Thanks for your help, Manisha!

**Comment by manishas** [comment]
@clifg @lizrush both your subscriptions have been migrated to the new plan. Please let me know if you run into any problems.

**Comment by clifg** [comment]
The badge in my project settings still isn't working:
[![Run Status](https://api.shippable.com/projects/56b6dbab1895ca4474738165/badge?branch=master)](https://app.shippable.com/projects/56b6dbab1895ca4474738165)

Is there anything else I need to do or should the badge uri be different? I copied this directly from the project settings page.

**Comment by manishas** [comment]
Did you run a new build? The badge will light up after you run a build on the new platform.

**Comment by lizrush** [comment]
@manishas I triggered a re-build and mine's working now. Thanks again!

**Comment by clifg** [comment]
Thanks, I'll give it a shot. Just tried a rebuild and now the setup_ve task is failing when it tries to nvm over to node 4.2.6. This used to fail before as well, but I worked around it by installing that version myself in a later script. I'll have to spend some time trying to get this to work again, but from Liz's comment it sounds like the badge should be working for me once that's done. Thanks for the update!

**Comment by clifg** [comment]
Worked for me as well, thanks!
