### ISSUE TITLE
Docker Hub Login Fails / Cannot Delete Hub Integration

### ISSUE THREAD

**Issue by jgregors** [Shippable/support#2332]
My builds starting failing a couple of days ago due to the docker hub: hub_login -> "Docker login failed for username <my_username> and email <my_email>". All projects are failing, look at osden-io/catalogue or osden/platform for details.

I saw [this issue](https://github.com/Shippable/support/issues/2289) but I think my case is different as I am not including any custom commands in my [shippable.yml](https://github.com/osden-io/catalogue/blob/master/shippable.yml).

To try and fix the issue, Ihave tried changing my docker hub passwords in both docker hub and the integration is shippable. I turned off the docker hub push in the project configurations and removed the hub integration (and "synced" the projects"). I then tried to delete the docker hub integration but I have several subscription images that I can't delete. When I try to disable them, I get taken to an old test project "osden_test" (which I must have created briefly a while back) and I get errors which prevent me from removing subscriptions to the docker hub integration:

"(Id: 4005) getPlanById for id: 557cb86ecc51360c001b943b
verbose: subscriptions|getStateById|callerId:56ac79b3a77c0d0b00a819e9|subscriptionId:56bd8123b506740c00b9c3c3_getPlanById
404"

Any help is much appreciated.

**Comment by sheldon-sminq** [comment]
+1 cannot delete or edit a hub integration, have to add a new one every time. And the old one still appear after delete.

**Comment by manishas** [comment]
@rageshkrishna can you look into what's happening here?

**Comment by trriplejay** [comment]
@jgregors We've cleaned up some of the stale data on our end. Can you try again to delete your unused integrations? Let me know if it still doesn't work.

@sheldon-sminq Can you post the specific error you're seeing? When you say you can't edit, do you mean the 'save' action fails or the edit button itself?

**Comment by sheldon-sminq** [comment]
No i mean if I add an integration, cannot edit it the only option is to
delete it. Once deleted, the options still appears in the integrations list.
but havent checked the same after as i was busy with the migration.

**Comment by trriplejay** [comment]
@sheldon-sminq ahh, I think I understand.  What you're actually adding/deleting is the association between your accountIntegration and your project.  If you want to remove the accountIntegration entirely, you can do so on the [accountSettings](https://app.shippable.com/accountSettings) page, under the 'integrations' tab. (make sure you first delete it from your project, so it's not being used)

You can also edit the integration on the accountSettings page.

**Comment by jgregors** [comment]
@trriplejay the integration was able to be deleted - thx.

**Comment by jgregors** [comment]
As for the Docker push not working: it was due to having the formatting of the .yml file being incorrect. I had accidentally added an extra tab space to the "integrations" block. When I removed this, the built image was pushed.

**Comment by manishas** [comment]
@jgregors I am closing this issue since there is nothing to be fixed here. Please let us know if you need help with anything else.
