### ISSUE TITLE
Smoke tests

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2334]
Just curious: in the API documentation e.g. for [getting a job](http://docs.shippable.com/api/#get-a-job) I can see the following:

```javascript
{
    "version": "0.12",
    "infra": {
    },
    "build": {
        "pre_ci": [],
        "pre_ci_boot": {
        },
        "ci": [
        ],
        "post_ci": [],
        "post_ci_boot": {
        },
        "smoke_test": [],
        "on_success": [],
        "on_failure": [],
        "cache": false
    },
    "deploy": {
        "pre_ci": [],
        "pre_start_boot": {
        },
        "start": [],
        "post_start": [],
        "post_start_boot": {
        },
        "smoke_test": [],
        "on_success": [],
        "on_failure": []
    },
}
```

What are these `smoke_test` entries for? Is Shippable able to perform smoke tests or is this a section in the YML one could/should use to add them?

(And what about the whole `deploy` section altogether? Is this also something which could go into the YML?)

**Comment by manishas** [comment]
@mbrodala you're finding features that have not yet been announced :)

These are in the schema for future compatibility and lot of it is still WIP and will be announced in the next few weeks.

**Comment by manishas** [comment]
If you have specific follow up questions please send me an email at manisha@shippable.com

**Comment by mbrodala** [comment]
Thanks for clarifying. :-)
