### ISSUE TITLE
Kubernetes and GKE

### ISSUE THREAD

**Issue by GEverding** [Shippable/support#2336]
Hi,

I'm currently evaluating Shippable for my company. We currently have a manual deploy process running on GKE/Kubernetes and I have a couple questions. 

1. How am I supposed to integrate with Kubernetes/GKE services/ingress if I can't set labels in a deployment pipeline? This wasn't covered in your documentation. 
2. How can I set env variables during the CI phase of my build? Common use case is generating the version tag for my docker images.

Thanks, Garrett

**Comment by ttrahan** [comment]
@GEverding : for #1 above, we currently do not support adding labels.  we've marked that as a feature request and will get it into our backlog process.

For #2 above, if I understand your question properly, there are several ways you can accomplish this that vary depending upon how/when in the CI process you generate your docker image.  You can set env variables from within your Dockerfile or within the shippable.yml.  The timing matters, though, so you'll want to ensure you've injected the variables prior to creating the image to push.

If you upload a copy of your Dockerfile and shippable.yml here, we can help troubleshoot this for you.

**Comment by ttrahan** [comment]
@GEverding : just checking in on 2) above. If you'd like to connect offline, please email me at tom@shippable.com and we'll arrange a Hangout.

**Comment by avinci** [comment]
@ttrahan did you guys connect? I am closing this as there is no action for us. Please re-open if there is any....

**Comment by devillex** [comment]
Hi. Do you have a link to the feature request ticket or your feature backlog?

Being able to use labels with Shippable for deployment to kubernetes is critical for our team.
