### ISSUE TITLE
Golang github repository clone is in incorrect location

### ISSUE THREAD

**Issue by 0xvkrmkpr** [Shippable/support#2337]
Our code is getting checked out at "/root/src/github.com/**reponame**". It needs to be at "/root/src/github.com/**company_name**/**reponame**". 

Because of missing company name, build fails since golang needs paths to match

----------------
ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git clone git@github.com:**company_name/reponame**.git 
/root/src/github.com/**reponame**'
Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
**Cloning into '/root/src/github.com/**reponame**'...**

**Comment by manishas** [comment]
thanks :)

ETA for a fix is tomorrow.

**Comment by ric03uec** [comment]
@0xvkrmkpr the fix for this is deployed now. can you please verify if this now working correctly for you.

**Comment by 0xvkrmkpr** [comment]
It is working great and build passed for us. Really appreciate the quick turnaround.
