### ISSUE TITLE
API: `/subscriptions/:id/runStatus` is not always up-to-date

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2339]
We use a script to ensure all our projects are built every day. We use `/subscriptions/:id/runStatus` every five minutes for this (as recommended in #2295). A few times already, we built the same project twice because the API took more than five minutes to report the first build. A few examples that happened today:

- https://app.shippable.com/runs/56de70d39227720c004aa818 and https://app.shippable.com/runs/56de6fa29227720c004a9e6c
- https://app.shippable.com/runs/56de6c139227720c004a8481 and https://app.shippable.com/runs/56de6d44f264a60c0078a682
- https://app.shippable.com/runs/56de615f9227720c004a398a and https://app.shippable.com/runs/56de629036784b0c006e1f81

**Comment by a-murphy** [comment]
By default, ```GET /subscriptions/:id/runStatus``` will only return builds that have completed.  So, if a build was in progress, it would not have been returned.  You may want to use the optional ```status``` query parameter to include those builds.  Assuming that you want all builds, ```GET /subscriptions/:id/runStatus?status=incomplete,complete``` should work.  Other combinations of statuses may also be given if you want to exclude certain statuses.

**Comment by pquentin** [comment]
Great, thank you!
