### ISSUE TITLE
API: How can we replace `projects/:id/searchBuilds?limit=n`?

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2340]
We're tracking coverage for all our projects by storing coverage data in InfluxDB and displaying it in Grafana. Or at least we were doing it before the API changed completely overnight. The way we were doing this until now was using a script every hour on each project which:

1. looked at the latest build number (now called run number) both in Shippable and in InfluxDB
2. used `projects/:id/searchBuilds?limit=n` to get all the runs that appeared in Shippable but were not in InfluxDB yet.

The 2. does not appear to be possible yet with the new API. The closest contender is `/runs?projectIds=:id` but there's no way to get "only n runs". I think having a `minRunNumber` (and not only a `maxRunNumber`) would solve our issue: we could request all runs between the latest InfluxDB run and the latest Shippable run.

**Comment by DavidGDragon** [comment]
`/runs?limit=n` is the new way. Note that n has a maximum of 100. If you need more than 100 you will need to use pagination and add the parameter `skip=z`

**Comment by manishas** [comment]
Closing since the question is answered.

**Comment by pquentin** [comment]
Thanks @DavidGDragon, that's exactly what I needed.
