### ISSUE TITLE
COMPARE_URL not set

### ISSUE THREAD

**Issue by Gudahtt** [Shippable/support#2341]
The environment variable COMPARE_URL isn't set in any of our new builds. This has been happening since yesterday evening. It's always set to an empty string.

**Comment by Gudahtt** [comment]
Also, in the new [documentation](http://docs.shippable.com/ci_configure/), this environment variable is listed as 'COMPARE_UR'. I assume that's a typo?

**Comment by manishas** [comment]
@a-murphy can you take a look at this?

**Comment by Gudahtt** [comment]
It looks like the 'BUILD_URL' environment variable is missing as well.

BUILD_URL isn't even set to an empty string like COMPARE_URL is - it's completely absent.

**Comment by a-murphy** [comment]
```COMPARE_URL``` has been verified in Beta (it's not in production just yet).

**Comment by a-murphy** [comment]
```BUILD_URL``` is now being set as well in Beta.

**Comment by Gudahtt** [comment]
This appears to be fixed. The environment variables are set correctly in our builds now.

Thanks for your help!

**Comment by manishas** [comment]
closing since this is fixed.
