### ISSUE TITLE
Decryption failed for var

### ISSUE THREAD

**Issue by aug70** [Shippable/support#2342]
This has been working until now, nothing is changed in the variable or configuration. Unless decryption algorithm changed, this must not fail!

Last good build https://app.shippable.com/builds/5626bfbf3f695d0c004b4ec5
Failed build https://app.shippable.com/runs/56def0232732f60d00bc6edc

Please advise, thank you!

**Comment by manishas** [comment]
@aug70 we will test this at our end but looks like your problem was resolved by re-encrypting the env variable. Did someone reset the project? The keys get reset if that happens and you need to re-encrypt - 
http://docs.shippable.com/ci_projects/#resetting-the-project

**Comment by manishas** [comment]
closing this since builds are now working.

**Comment by aug70** [comment]
Thanks for looking into it! Nobody changed or reset the project, I'm the only person working on this. It's weird it stopped working.
