### ISSUE TITLE
Service start failure console entries

### ISSUE THREAD

**Issue by Gudahtt** [Shippable/support#2344]
We don't have services enabled for our build, yet entries continue to appear in the build console about postgres and mysql starting. Also, during the 'setup_ve' step, it complains about nvm configuration.

Here is an example: https://app.shippable.com/runs/56dee3f62732f60d00b7e3be

```
echo nvm configuration will be skipped because this job is not running on an official image
nvm configuration will be skipped because this job is not running on an official image
```

```
postgres_start
  echo postgres will not be started automatically because this job is not running on an official image
```

```
echo mysql will not be started automatically because this job is not running on an official image
mysql will not be started automatically because this job is not running on an official image
```

Is this expected? I'm confused as to why these entries have appeared. Thanks.

**Comment by manishas** [comment]
@Gudahtt this is expected. Your subscription was moved to the new build system and these entries are meant to clarify that behavior that is standard with official images or legacy images (shippable/minv2) will not happen with custom images - i.e. no services are started by default if you're using custom images.

**Comment by Gudahtt** [comment]
Ok, thanks.
