### ISSUE TITLE
Deleting Account Integrations

### ISSUE THREAD

**Issue by emilcara** [Shippable/support#2346]
I'm having a hard time deleting integrations within my account and deleting my account. I keep getting a dependency error when I try. I also no longer see the formations tab in my account.

**Comment by manishas** [comment]
@emilcara do you want to delete your account or just the integrations?

Formations was recently deprecated and replaced with pipelines - http://docs.shippable.com/pipelines_overview/

**Comment by emilcara** [comment]
just the integration.

**Comment by manishas** [comment]
@emilcara can you let us know the integration name you want to delete?

**Comment by manishas** [comment]
Closing this, but please let us know if you still need help with this.
