### ISSUE TITLE
Build gets stuck Intermittently at step 'Job node info'

### ISSUE THREAD

**Issue by Gudahtt** [Shippable/support#2349]
I've noticed that our builds have been getting stuck fairly often during the 'Job node info'.

e.g. https://app.shippable.com/runs/56e02bcb64dd900c00477297 - this build is still running as of this moment, but it's been stuck on this step for >20 minutes. For reference, the build typically takes between 5-10 minutes to run.

Specifically, it seems to get stuck on the command `free -m`. It displays the headers returned by `free`, but no output.

I've been dealing with this by cancelling the build and rebuilding.

**Comment by Gudahtt** [comment]
I'd also like to note that it still hasn't timed out yet either.

> If there has not been any log output or a command hangs for 10 minutes

It's been 30 minutes now with no log output, so it should have timed out 20 minutes ago.

**Comment by Gudahtt** [comment]
The build has now been running for well over an hour (4500 seconds). I've had to cancel it. So it looks like the 1-hour timeout didn't work properly either.

**Comment by himanshu0503** [comment]
@Gudahtt : We're very sorry for the inconvenience caused, can you please let us know if it is still an issue?

**Comment by Gudahtt** [comment]
@himanshu0503 Sure, I'll let you know if it happens again.

I'll give it a couple days - it was happening between 2-4 times a day last week, but we'll likely have fewer builds for the next couple days.

**Comment by manishas** [comment]
@Gudahtt is this still happening? If not, can we close this issue?

**Comment by magwas** [comment]
This is maybe related. Build hangs in "Provision job node" phase:
https://app.shippable.com/runs/56ea51729b8e4e0c009e1542
This is at least the second one I see in a day.

**Comment by Gudahtt** [comment]
I haven't seen this happen so far this week - I'll close this for now. I'll comment here again if it happens again.

@magwas I've never seen that happen to my builds - it was always stuck at 'Job node info'. But yeah, could be related. Not sure.

**Comment by rsinnet** [comment]
I signed up for Shippable today and I've experienced this issue multiple times already. Is this a regular occurrence?

**Comment by a-murphy** [comment]
Builds are not often stuck in the "job node info"  step.  However, the "provision job node" step does occasionally take longer than expected, usually when the first attempt to provision a node fails for some reason.  Provisioning a node can typically take about three minutes.  Once provisioned, a node will be used for subsequent builds in the same subscription that start in the next hour, which reduces the time to run those builds.  The provisioning time can be avoided by [adding your own node](http://docs.shippable.com/getting-started/byon-overview/).

**Comment by rsinnet** [comment]
Thanks for the quick reply. I will try BYON and see how that works.
