### ISSUE TITLE
Make timeout duration configurable

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#2350]
Example build is https://app.shippable.com/runs/56e0406a5088740d0052bd33

You might need to scroll upwards a bit, since we test in parallel and only one of them fails

**Comment by rogierslag** [comment]
Could be, I dont know enough about the ruby internals to assess that. 

It does yield a feature request though: currently such a build will be left around for 2 hours before being considered failed. Could we specify the max time in the `shippable.yml` file in some way?

**Comment by manishas** [comment]
The custom timeout request is a dup of #1371. 

Please track resolution of this feature request in that issue
