### ISSUE TITLE
$PULL_REQUEST no longer set to false for non-pull request

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2355]
We use an on_success step like this:

    - 'if [ "$BRANCH" == "master" -a "$PULL_REQUEST" == "false" ]; then curl -X POST -H "Authorization: apiToken $API_TOKEN" -H "Content-Type: application/json" https://api.shippable.com/projects/$psjobscriptsid/newBuild; fi'

To trigger a new build.  After switching to the new platform we have found $PULL_REQUEST is no longer set to false.  This means our builds aren't triggering.  The docs seem to indicate it still should be set to false when a non-pull request is building.

Thanks,

**Comment by chriskinsman** [comment]
Working around this with:

- 'if [ "$BRANCH" == "master" -a -z "$PULL_REQUEST" ]; then curl -X POST -H "Authorization: apiToken $API_TOKEN" -H "Content-Type: application/json" https://api.shippable.com/projects/$psjobscriptsid/newBuild; fi'

**Comment by pranaypareek** [comment]
@chriskinsman thanks for reaching out. We are looking into this and will keep you posted!

**Comment by pranaypareek** [comment]
Chris, this has been pushed to beta and verified. I'll update you as soon as this is pushed to production, in the next few hours.

**Comment by rogierslag** [comment]
We had the same problem, the variable in the new setup is called `$IS_PULL_REQUEST` (which to be honest is an improvement since the name is clearer)

**Comment by pranaypareek** [comment]
@rogierslag you're right. Our docs were missing the description for the new variable `$IS_PULL_REQUEST`. (We're updating them)

The older variable `PULL_REQUEST` can still be used though as **it will be set to false for a non-PR build** and **with the build number for a PR build**.

Thanks!

**Comment by rogierslag** [comment]
_P.S. (not strictly related, but would be very useful) to see the environment which is used. Currently we just add `env` as the first step in the `ci` block. However that does print everything everytime (not sure about encrypted vars). It would be awesome if you could check the used `env` directly from the web ui or something!_

**Comment by pranaypareek** [comment]
Rogier, as far as I understood your request, we do show the env vars on the UI! (Please correct me if I'm wrong)

This can be done without needing to use the `env` step in the `ci` block.

* You can navigate to the `Script` tab .

![selection_189](https://cloud.githubusercontent.com/assets/6316230/13668681/518272fc-e6e4-11e5-914d-843757aa58ba.jpg)

* Here, you should expand the `boot` step.
![selection_191](https://cloud.githubusercontent.com/assets/6316230/13668778/f50f83a6-e6e4-11e5-807d-b26e9eb80ff3.jpg)

* If you scroll down a bit after expanding this, you will be able to see the list of all env variables in the script:

![selection_190](https://cloud.githubusercontent.com/assets/6316230/13668686/55fe53a0-e6e4-11e5-85b1-fd92aac16c66.jpg)

-------------------------------------

* You can also check out the env variables being used from the shippable.yml

These can be found by navigating to the runs page.

You should click on the `[...]` expansion box adjacent to the `Matrix Values` label.

This will open up a div listing out the environment variables that you're using (as specified in your shippable.yml).

![selection_188](https://cloud.githubusercontent.com/assets/6316230/13668693/5fa19e6c-e6e4-11e5-85f6-0447fdb1f192.jpg)

These are the env variables that I am using:
```
env:
  global:
    - FOO=FUBU
    - FO1=BUBU
    - BOO=GUBU
```

This is from the yml of my sample project here: https://github.com/pranaypareek/sample_node/blob/master/shippable.yml


Please let me know if this solves your query! **:)**

**Comment by pranaypareek** [comment]
@chriskinsman the fixes are now live. Please let us know if this works for you. Thanks!

**Comment by rogierslag** [comment]
Aha the part under the script section is exactly what I was looking for! Awesome :)
