### ISSUE TITLE
ignoring changes to shippable.yml

### ISSUE THREAD

**Issue by tcurdt** [Shippable/support#2357]
We have a PR from a branch off master. New commits will trigger a new build - but according to the logs changes to the `shippable.yml` are being ignored.

https://github.com/VIORAMA/chronos/blob/80af6d76b00ee2cd1507ab778f0b130d3a2723a1/shippable.yml

vs

https://app.shippable.com/builds/56e0fc399c434f0d009c87c3

**Comment by manishas** [comment]
@tcurdt we cannot see the yml since this is a private project. 

Does your branch contain shippable.yml? Also, does master have a shippable.yml at the root of the repo?

**Comment by tcurdt** [comment]
@manishas "yes" is the answer to both questions.

It seems like PR builds are ignoring changes to the `shippable.yml` while the reqular builds are OK.

**Comment by rageshkrishna** [comment]
@tcurdt It looks like your subscription is running on the old build system. This problem should go away once your subscription gets migrated to the newer version, which should happen some time in the coming week.

**Comment by manishas** [comment]
@tcurdt as ragesh mentioned, your subscription is on the old build system. You should have received an email from us indicating that all projects using Docker options in Project settings to customize their docker workflows need to migrate to the new build platform before 3/22.

Please follow instructions in the email to migrate your subscriptions. Let me know if we can help with anything.

**Comment by manishas** [comment]
Closing this issue since there is nothing actionable for us to do here. If this problems recurs on the new build system, please let us know.

Thanks!!
