### ISSUE TITLE
500 error on build

### ISSUE THREAD

**Issue by babelian** [Shippable/support#2360]
Am receiving this error on clicking build for deploy/production branch

https://app.shippable.com/projects/5413806af82ab7ebd69c942c

(Id: 4006) postRun failed for projectId: 5413806af82ab7ebd69c942c
verbose: projects|triggerNewBuildRequest:5413806af82ab7ebd69c942c|_queueRun
500

Thanks.

**Comment by a-murphy** [comment]
This might have had something to do with recent changes to caching, and if so should no longer be a problem.  Could you try triggering the build again?

**Comment by manishas** [comment]
@babelian can you point us to the latest build for your project?

**Comment by manishas** [comment]
@babelian is this still happening?

**Comment by pledgemusic** [comment]
no, there's a build error but i'll follow up with that separately if i can't work it out. Thanks.

**Comment by manishas** [comment]
Closing this issue. Please open another one if you need help with the build error.

**Comment by vastbinderj** [comment]
@manishas we are seeing this issue today.  The only previous build error was on the post-success deploy step.

**Comment by lazebny** [comment]
@manishas, see such error today. Cant build any of repositories: 
(Id: 4006) postRun failed for projectId: 56eef6dc9d043da07bee68cf
verbose: projects|triggerNewBuildRequest:56eef6dc9d043da07bee68cf|_queueRun
500

**Comment by jeppefrandsen** [comment]
+1

**Comment by gg-dh** [comment]
Same thing. When I use caching in the `shippable.yml`:

```
build:
  cache: true
```

then the build is not triggered on git push, and when I click "Build" I get this error:

```
(Id: 4006) postRun failed for projectId: 56f9b7449d043da07b091cd4
verbose: projects|triggerNewBuildRequest:56f9b7449d043da07b091cd4|_queueRun
500
```

Without caching everything is ok.

**Comment by vastbinderj** [comment]
I moved all my yml files to the new format to get around these issues.  I would suggest you do the same.  I began by following this blog post and @manishas pointed me to a translator, but I cannot find it in my history:

http://blog.shippable.com/migrating-to-the-new-build-platform

**Comment by vastbinderj** [comment]
BTW - @manishas did a fantastic job helping with migrating my ymls to the new format.

**Comment by kanthchandra** [comment]
@lazebny @gg-dh @jeppefrandsen We had a small glitch in one of our runs api and we have fixed it. Can you please try now and see? If the problem still persists please feel free open a new issue and we will look into it.

**Comment by gg-dh** [comment]
@kanthchandra No more troubles with caching, everything's ok atm. Thank you!

**Comment by lazebny** [comment]
@kanthchandra, thanks resolved.
