### ISSUE TITLE
git submodule update started failing after I changed to the Continuous Delivery plan

### ISSUE THREAD

**Issue by zebehringer** [Shippable/support#2364]
I was following the steps for migrating to the new YML format: http://blog.shippable.com/migrating-to-the-new-build-platform. The first step is to update your billing plan, so I did that. Between doing that and actually committing an adapted shippable.yml to any of our code repos, we had to build some other changes. So far they are all failing when trying to resolve submodules.
I then tried resetting the subscription to generate a new Deployment Key, copying that to bitbucket and all, but still failing.
I then tried committing an adapted shippable.yml file, thinking that could be the culprit, but still failing. 

One of the failed builds: https://app.shippable.com/runs/56e22815747c3e0d0079f038

bitbucket username: zbehringer@revealmobile.com

**Comment by manishas** [comment]
@rageshkrishna can we look at this?

**Comment by rageshkrishna** [comment]
Hi @zebehringer. I've started looking in to this issue. I'll get back to you in a bit with my findings.

**Comment by rageshkrishna** [comment]
I have figured out why this is happening. One of our components is presenting keys in the wrong order. We have a fix ready for this and it will be deployed in the next hour.

**Comment by rageshkrishna** [comment]
@zebehringer This should be working now. Please give it a shot and let me know how it goes. Thanks!

**Comment by zebehringer** [comment]
Yeah, looks like the builds are now getting past the submodule update line. It is now failing on ecr login, but that is because I haven't adapted the Dockerfile to install the awscli.
