### ISSUE TITLE
Status reporting to github

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#2365]
Currently shippable saves one status to Github when checking a pull request. However two checks are done. 1 for the tip of the branch and one for the proposed merge. However just a single one is shown in Github.

Would it be possible to use two different names for the status checks, such that they both show up (e.g. `Shippable/merge` and `Shippable/branch`)? That way it is easier for developers whether their branch has problems of its own, or just after a merge in master. Plus it would give direct click through access to both builds on Shippable itself :)

**Comment by manishas** [comment]
This will be too complicated to implement especially in cases where the branch has a lot of commits for the PR. Closing as deferred.
