### ISSUE TITLE
ebs_check_deploy_run_json not found in source code

### ISSUE THREAD

**Issue by zebehringer** [Shippable/support#2368]
building an app that deploys to Elastic Beanstalk, using the new YML format and the Continuous Delivery plan, is failing. As far as I can tell, it is on a step called "ebs_check_deploy_run_json". CI and pushing to ECR works.

https://app.shippable.com/runs/56e33d93718a8f0c0003f923

bitbucket username: zbehringer@revealmobile.com

**Comment by ttrahan** [comment]
@zebehringer: we apologize, this is a known issue that we're fixing.

in the meantime, if you'd like to set up the EB deployment steps directly yourself in your shippable.yml, here are two examples for doing so:
* [For source code deployment](https://github.com/ttrahan/node-express-eb/blob/master/shippable.yml)
* [For Docker deployment](https://github.com/ttrahan/micro-api/tree/amazon-eb-cli-beta)

**Comment by abhijitkini** [comment]
The [documentation on deploying to Elastic Beanstalk](http://docs.shippable.com/ci_configure/#aws-elastic-beanstalk) has been updated.

**Comment by manishas** [comment]
@zebehringer the updated docs should provide details on how to set up beanstalk deployment with the new platform. Let us know how it goes :)

**Comment by ttrahan** [comment]
@zebehringer : we've completed the updates to our EB deployment integration and updated the documentation.  I'll close this issue, but please re-open if you continue to have issues deploying to EB.
