### ISSUE TITLE
gcloud version update policy

### ISSUE THREAD

**Issue by pkaminski** [Shippable/support#2369]
Thanks for adding gcloud to the new standard images!  However, I notice that the version of the tool you have installed there is v95, whereas the latest is v100.  What's your policy regarding updating to new versions of gcloud in the drydock images?  What's the best way to update it in our script if we need a more recent one?  I've adapted the Ubuntu script from the gcloud docs but it's probably overkill:

```
sudo apt-get -qq update && sudo apt-get -qq -y install curl
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo apt-get -qq -y install google-cloud-sdk
```

Thanks.

**Comment by manishas** [comment]
@pkaminski we will update our official images every quarter with the latest tools, services, and language versions. Next update will be June 2016.

Your scripts look right, we're actually doing exactly that to install gcloud sdk on our images. You can create a Docker image with a FROM using our standard image and then just install the latest version of the sdk on it which you can then use as a custom image on Shippable. However, official images have some advantages like being able to use `services` tag and runtime tags to switch language versions.

**Comment by pkaminski** [comment]
OK, thanks.  I think I'll keep things as-is -- the additional install isn't slowing things down very much, and I like having the runtime dealt with automatically.  Once `gcloud preview app` settles down perhaps I'll fall back to your quarterly version.  Cheers.

**Comment by moeadham** [comment]
@manishas Gcloud 96 is now pretty much fully deprecated. Can you please update to v116? You can no longer deploy node apps on 96.

Thanks
