### ISSUE TITLE
BitBucket Pull Request Support

### ISSUE THREAD

**Issue by coreybutler** [Shippable/support#237]
Any timeline on pull request support with BitBucket? Every CI service has Github integration... this would be a nice differentiating factor.

**Comment by grue** [comment]
+1 for this

**Comment by bbrala** [comment]
This would be so usefull. Any news?

**Comment by sdlarsen** [comment]
+1

**Comment by caarlos0** [comment]
+1

**Comment by basco-johnkevin** [comment]
+1

**Comment by zanona** [comment]
This would be great to have guys! Fork based PRs FTW :+1:

**Comment by clockwork-coder** [comment]
+1

**Comment by tstangenberg** [comment]
+1

**Comment by shawn9273** [comment]
+1

**Comment by per-nilsson** [comment]
@avinci Thanks for the hard work! My Shippable experience has been really great so far. If you could provide a recipe for integrating with Bitbucket pull requests, that would be really helpful!

**Comment by nathanmarks** [comment]
+1 any updates on this?

**Comment by fabiocarneiro** [comment]
For people asking this feature. I guess this isn't a Shippable problem. This happens because Bitbucket does not support it. I moved my repos to Github and it works perfectly.

**Comment by manishas** [comment]
yes, this is a limitation of Bitbucket - https://bitbucket.org/site/master/issue/6545/pull-request-web-hooks-bb-7736

We will track this and add as soon as bitbucket fixes on their end. Thanks!

**Comment by Nalum** [comment]
Just adding my vote to this.

**Comment by bbrala** [comment]
@manishas I see something new on the relevant ticket. Have these webhooks changed anything?

https://bitbucket.org/site/master/issue/8340/pull-request-post-hook-does-not-include

"In the future, you will not be able to create POST or Pull Request POST services from this screen, 
as Bitbucket's new and improved webhooks will replace these services. Existing POST services 
will continue to function as expected for now. 
To create a new webhook, refer to the documentation for Bitbucket's updated webhooks ."

And the newish documentation on those: https://confluence.atlassian.com/display/BITBUCKET/Manage+Webhooks

**Comment by hranicka** [comment]
BitBucket has created new webhooks: https://bitbucket.org/site/master/issue/6545/pull-request-web-hooks-bb-7736#comment-19264939

Please, is it sufficient for Shippable pull request hooks for BitBucket like on GitHub?

**Comment by manishas** [comment]
we're looking into this, will send an update once we know more.

**Comment by cloudkite** [comment]
+1

**Comment by amondnet** [comment]
+1

**Comment by jdextraze** [comment]
+1

**Comment by jeremysuriel** [comment]
+1

**Comment by bbrala** [comment]
Hi @manishas, any news to report on this?

**Comment by alexyer** [comment]
+1

**Comment by crimsonronin** [comment]
Bump!

**Comment by kepkin** [comment]
Bitbucket had released new API at last!
https://bitbucket.org/site/master/issues/8548/better-ci-integration-add-a-build-status

**Comment by bbrala** [comment]
@manishas Here we are again, 6 months after bitbucket implemented the webhooks for pull request. And still nothing. Can we get any news? Is this even considered? I'm really confused as to why there is so little communication and i guess progress on this issue.

**Comment by fiznool** [comment]
This is the one thing standing in the way of me using shippable. Can anyone suggest a competitor that can offer this functionality?

**Comment by coopy** [comment]
@fiznool CodeShip may offer the features you need. https://blog.codeship.com/codeship-bitbucket-tutorial/

**Comment by avinci** [comment]
@coopy this is not a Shippable limitation. Its bitbucket. Bitbucket today cannot link forks to a parent. Hence the keys don't match and as a result PR builds don't work. We have an open ticket with bitbucket for last 15 months and they don't seem to want to fix it. Hence its infeasible to do PRs just like github on bitbucket. 

If you have ideas, happy to implement it.

**Comment by avinci** [comment]
This is the request on bitbucket that we opened...

https://bitbucket.org/site/master/issues/5814/reify-pull-requests-by-making-them-a-ref

**Comment by coopy** [comment]
@avinci Ah, thank you for the explanation. That is frustrating.

**Comment by fiznool** [comment]
@avinci that issue only affects pull requests coming from a private fork, correct?

In that case, would it be feasible to implement this for pull requests originating from a different branch, in the same repo? This is my use case.

**Comment by manishas** [comment]
This will be tracked in #2146

**Comment by ttrahan** [comment]
This is now available. Please take a look at the [docs](http://docs.shippable.com/ci_configure/#pull-requests) for more details. Let us know if you have any questions.

**Comment by GuyMograbi** [comment]
link is broken. can you please comment with the right link?
