### ISSUE TITLE
Is there a away to add multiple environments?

### ISSUE THREAD

**Issue by pukapukan** [Shippable/support#2370]
I have multiple repos in a github account and want each of them to be deployed their respective ECS cluster.

However it seems like Shippable allows a single environment at the moment.  Is there a way to add multiple environments?

**Comment by pukapukan** [comment]
Found #2354 - closing this.

**Comment by manishas** [comment]
@pukapukan we have now added the ability to create multiple environments within a subscription.

The next phase will address promotion, permissions, etc but the simple case of adding another environment and deploying to it should now work as expected.
