### ISSUE TITLE
Delete my account

### ISSUE THREAD

**Issue by sbalko** [Shippable/support#2372]
Guys,

I told you to cancel my account some time ago after it refused to do so in your Web interface. Now I find an invoice over $10 in my inbox. 

Guys, cancel my subscription IMMEDIATELY. I can neither remove the credit card from my account, nor can I cancel the account altogether.

Regards,
Soeren Balko, PhD
CTO clipchamp.com

**Comment by manishas** [comment]
@sbalko sorry about this oversight. We'll delete your account and also issue a refund within 24 hours. 

While deleting accounts was not available through the site in the past, you should have been able to switch your subscription to the free plan.

**Comment by manishas** [comment]
Refund has been issued and will show up on your card in a couple of days. I will leave this open until your account is deleted.

**Comment by manishas** [comment]
Account has been deleted. Closing.
