### ISSUE TITLE
Deploy with load balance enabled - Could not find required IAM role.

### ISSUE THREAD

**Issue by pukapukan** [Shippable/support#2373]
Hi, when a Docker image is deployed to AWS ECS without load balancer enabled, everything works fine.

But when I try to deploy the same image with a load balancer, the deployment completes with following message: "Could not find required IAM role."

Since the registered ECS service gets removed after the deployment - I bet it has got to do with creating a service with load balancer enabled - but it fails even with Administrator policy.

Can you please provide on steps/requirements for setting up the routing with the load balancing enabled?

Thanks in advance :)

**Comment by manishas** [comment]
@trriplejay can you help with this?

**Comment by trriplejay** [comment]
When creating a service with a load balancer, ECS requires that you provide it with a role that will allow the ECS agent to access everything it needs.

Currently, Shippable is using your provided credentials to find an existing role that suits this purpose.  Our current criteria for the role is that it contains the following trust relationships:

```
"Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    },
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
```

basically, the role needs access to both ECS and EC2.  Even if the user has admin, if we can't find a role with the proper trust relationships, then we won't be able to utilize the load balancer.

That being said, we're working on analyzing what roles and policies are actually needed, at a minimum, to allow Shippable to manage all of the various aspects of your ECS cluster.  I'm hoping we can make that information available soon.

**Comment by pukapukan** [comment]
Thanks @trriplejay!  That was helpful!
