### ISSUE TITLE
Cannot login to shippable, receiving Failed to POST accountIntegration

### ISSUE THREAD

**Issue by hgrubst** [Shippable/support#2374]
Hi,

Since yesterday I cannot login to my shippable account anymore. 
I keep getting a screen saying : 
'Failed to POST accountIntegration'
I normally login through my bitbucket account.

**Comment by rageshkrishna** [comment]
@hgrubst Can you please give me the bitbucket username with which you are trying to log in? Thanks!

**Comment by hgrubst** [comment]
Same as my email : aclement2@gmail.com

Thanks

**Comment by rageshkrishna** [comment]
@hgrubst Can you please try logging in once again? There was an inconsistency in our database that has been corrected. Things should be back to normal now.

**Comment by hgrubst** [comment]
Thanks for the support, back to normal now:)

Arthur
