### ISSUE TITLE
Repository name converted to lower case during git clone operation.

### ISSUE THREAD

**Issue by volcan01010** [Shippable/support#2379]
Since migration to the updated build system, my tests have started failing because the repository name is changed to lower case in the git clone command that is run by Shippable at the git sync stage. e.g.

    git clone git@github.com:someUser/SomeProject.git /root/src/github.com/someUser/someproject'

This means that Python commands similar to the one below fail during testing:

   from SomeProject import my_module

An example failing build is: https://app.shippable.com/runs/56e6de1e90c2830c003a59c9

I found a workaround for now.  Adding

    - ln -s /root/src/github.com/thinkWhere/roadnet /root/src/github.com/thinkWhere/Roadnet

to the `ci` section of shippable.yml fixes the imports in Python.  An example working build is https://app.shippable.com/runs/56e6e7167c4f6b0c00f22880

**Comment by a-murphy** [comment]
This should be corrected soon.  The folder for the cloned repository has been updated to match the GitHub repository name in Beta.  It might require synchronizing the project once it has been deployed production to take effect.

**Comment by a-murphy** [comment]
It's in production now.  If your project is still cloning into a lowercase folder name, either synchronizing the project on the project settings tab or waiting for the next automatic sync will update it.

**Comment by manishas** [comment]
This is fixed, so closing. @volcan01010 let us know if you run into any issues.

**Comment by natcl** [comment]
Does think also fix installing from git ?
My organisation has capital letters in it's name and it fails:
npm install MyOrg/myrepo gets converted to myorg/myrepo

**Comment by manishas** [comment]
@a-murphy can you look into this?

**Comment by a-murphy** [comment]
Sorry, I can't seem to find the problem.  Would you mind letting me know if this is GitHub or Bitbucket?  And, is it in the ```git_sync``` step, another command automatically added to the script, or part of your shippable.yml?

**Comment by natcl** [comment]
@a-murphy This is with Github.  for example, say I have a package located here:
MyOrgName/mypackage

if I do `npm install MyOrgName/mypackage` npm will lower case my organization name and won't be able to clone the repo:

```bash
ubuntu@ip-172-31-16-195:~$ npm install MyOrgName/mypackage
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:myorgname/mypackage.git /home/ubuntu/.npm/_git-remotes/git-github-com-myorgname-mypackage-git-397760d5: undefined
npm ERR! git clone --template=/home/ubuntu/.npm/_git-remotes/_templates --mirror git@github.com:myorgname/mypackage.git /home/ubuntu/.npm/_git-remotes/git-github-com-myorgname-mypackage-git-397760d5: undefined
```

**Comment by natcl** [comment]
Sorry, not sure what happened but I meant to comment about this on the npm repo, not here, sorry about that please ignore.
