### ISSUE TITLE
Turning on cache is causing builds to hang

### ISSUE THREAD

**Issue by jeffkole** [Shippable/support#2380]
Looks like a success, but the build has just been hanging and won't finish.  The logs don't even look like anything else should be going on:

https://app.shippable.com/runs/56e72c8a90c2830c0046bb49

**Comment by manishas** [comment]
@jeffkole we are experiencing issues with our caching implementation so we're working on a new implementation that is folder based rather than caching the whole minion. 

Can you reset cache, turn off caching and try again?

**Comment by manishas** [comment]
The new caching implementation will be available this week.

**Comment by jeffkole** [comment]
Given your documentation states it, I was under the impression caching was disabled:

> Caching is currently disabled for all customers on the Continuous Delivery plan. We discovered some issues that are slowing builds down when caching is turned on and we're working to address this with folder level caching.
> 
> This section will be updated when folder level caching is available. ETA is 3/18

From: http://docs.shippable.com/ci_configure/#caching-your-container

I'll manually disable it to see if that helps.

**Comment by manishas** [comment]
@jeffkole are you still running into builds hanging?

**Comment by jeffkole** [comment]
They are moving much faster with caching turned off now.

**Comment by manishas** [comment]
Thanks. I am going to change the title to 'turning on cache is causing builds to hang'. When our new caching implementation is complete, we will update this issue with a link to how to set it up.

**Comment by manishas** [comment]
We have deployed the new caching implementation to production. Docs have also been updated - http://docs.shippable.com/ci_configure/#caching-your-container

As mentioned in the docs, simply having a ```cache: true``` in the build section of the yml will result in $SHIPPABLE_BUILD_DIR being cached. You can also choose to cache specific folders using the `cache_dir_list` tag in addition.

```
build:
  cache: true
  # cache_dir_list is optional. If not present, we will cache $SHIPPABLE_BUILD_DIR.
  cache_dir_list: 
    - dir1
    - dir2
    - dir3
```
