### ISSUE TITLE
Problem with build badge

### ISSUE THREAD

**Issue by LukasSommerTu** [Shippable/support#2383]
I have a problem with the build badge of my Shippable project
(https://app.shippable.com/projects/55610dc2edd7f2c052f9deb7).

I copied the Markdown badge for branch master from the 'Settings'-tab
and integrated it in my Readme
(https://bitbucket.org/LukasSommerTU/joptimframework).
Unfortunately, the badge is only displaying "run: none" (see second screenshot), though there
have been successful runs of the corresponding master branch on the
Shippable project (see first screenshot).

Did I set up something wrongly or what is the problem here?

Thank you very much in advance!

![build](https://cloud.githubusercontent.com/assets/1321397/13785985/1a6ad066-ead6-11e5-81ba-fd521b22240d.png)
![readme](https://cloud.githubusercontent.com/assets/1321397/13785986/1a6dc6ae-ead6-11e5-82f9-e5141c5cddd2.png)

**Comment by manishas** [comment]
@LukasSommerTu this is because your Subscription wasn't migrated to the new plan. I just migrated it , so the badge should light up from the next build. Let me know if this works.

**Comment by LukasSommerTu** [comment]
Unfortunately, the migration of the plan seems to break my CI, because I cannot run any builds now, error message is " All jobs have been excluded by YML configuration ". Do I need to reconfigure my travis.yml to match the new plan? 

[travis.txt](https://github.com/Shippable/support/files/174407/travis.txt)

**Comment by manishas** [comment]
@LukasSommerTu I was able to repro your scenario. We will rollback your subscription to the old system until we investigate and fix the issue you're running into.

**Comment by manishas** [comment]
@LukasSommerTu actually, we found the problem - can you specify a jdk version in your yml? Something like this:
```
jdk:
  - openjdk7
```

It should work as expected after that.

**Comment by ric03uec** [comment]
- we should set the default jdk to `openjdk7` if its not specified in the yml
- each of the following formats should be supported
```
jdk: openjdk7
```
and 
```
jdk:
  - openjdk7
```

**Comment by a-murphy** [comment]
Verified that a default JDK (```openjdk7```) is being set for Java builds in Beta.

**Comment by LukasSommerTu** [comment]
After setting the JDK in the .yml-file with 
```
jdk:
  - openjdk7
```

the build is now working again and the build badge now also displays the correct status in my README. 
Thank you for your support!

**Comment by manishas** [comment]
:+1:
