### ISSUE TITLE
id:4006 postRun failed for projectId

### ISSUE THREAD

**Issue by vastbinderj** [Shippable/support#2384]
We are not able to rebuild our projects. We are testing a modification in our deploy step, but are hitting this error in Shippable.

See this project and try to rebuild it, a repro step: 

Try rebuilding https://app.shippable.com/builds/56e70bf390c2830c00435a55

**Comment by manishas** [comment]
@vastbinderj your subscription was migrated to the new platform recently, so rebuilding for older builds won't work.

Can you try triggering a build from your project page - https://app.shippable.com/projects/56bba0731895ca447473c526

**Comment by manishas** [comment]
@vastbinderj looks like you started over again with your project are are running to 'Host verification key failed' issue.

I see that your project is using our old image shippableimages/ubuntu1404_nodejs. Can you please remove the custom `buildimage` tag and try the build? This will ensure that the latest official images get picked for your build and should move past the error you're seeing.

**Comment by vastbinderj** [comment]
@manishas - that got us past the issue with the host verification key.

Now the `build_on_success` step seems to take forever to finish when exporting the docker container.  Which, at this time, we don't need or care about...  Is there a setting to skip this part of `build_on_success`?

**Comment by manishas** [comment]
This is a known issue and happens when you have cache turned on. We are working on a new caching implementation that will enable folder level caching and this should be available later this week or early next week. 

Until then can you turn cache off and try a build? I'll leave this open and update you when the new caching is in place.

**Comment by vastbinderj** [comment]
TY @manishas 

We now have passing builds again.
