### ISSUE TITLE
language: none should avoid any language specific default processing for custom images

### ISSUE THREAD

**Issue by magwas** [Shippable/support#2385]
This is a failed build:
https://app.shippable.com/runs/56e84c43c54c770c00f7540d
Here is the matching shippable.yml:
https://github.com/edemo/PDOauth/blob/6d4970c5a280855b608a038a88877c063b555e2c/shippable.yml

Apparently a recent update for some reason thinks that
- it is a ruby project
- I need some bundles to be installed. (why???????????)

As there is no "bundle" command in the docker image I am using, the build fails.

What to do to be able to build my project again?

The same issue from a broader viewpoint:

In another project I was struggling with the fact that shippable apparently added a python interpreter to the image, and set it as default. That interpreter did not have the ubuntu-default python path, hence did not see the modules installed to the image. => build failed

I believe it is a common use case that one
- builds her own docker image
- comes up with a build sequence that works in that image
- trusts shippable to do it automatically and in a reproduceable way.

I also understand that some advanced services you provide need altering the image/build sequence.

Therefore I propose that you provide a way to signal in shippable.yml that "no thanks, I need no alterations"?

**Comment by manishas** [comment]
@ric03uec can we look into this?

**Comment by manishas** [comment]
@magwas our build system defaults to ruby if no language tag is specified in the yml. We will investigate this more to find out what changed for your specific yml parsing between old and new build systems.

To unblock your builds, can you please add a language and runtime tags?

For example -

```
language: python

python:
  - 2.7
```

**Comment by magwas** [comment]
Thank you, adding language to shippable.yml solved the immediate problem.
Working shippable.yml: https://github.com/magwas/PDOauth/blob/8a4a620b7291d6f5a1151acb66b1ef59ff84d78a/shippable.yml
Build:
https://app.shippable.com/runs/56e88356c8cfb20d00a5debc

What if you would add support for
language: none
to signal that there should be no modification to image or build process?

**Comment by manishas** [comment]
Thanks for letting us know. I will retag this as feature request.

**Comment by mspanc** [comment]
I dream about `language: none`, too. I am using shippable mostly because it allowed to easily run totally custom images & builds with previous syntax.

**Comment by manishas** [comment]
This has been bumped up in priority since it will enable users to run custom images with any language. Update soon :)

**Comment by kanthchandra** [comment]
Hi everyone,  This is now available in production. You can use the tag `language: none` in your shippable.yml and we wont be executing any default scripts for the build.

**Comment by mspanc** [comment]
Wonderful!

**Comment by manishas** [comment]
closing since this is now in prod.
