### ISSUE TITLE
git_sync phase leaving out "git clone" command

### ISSUE THREAD

**Issue by cjerdonek** [Shippable/support#2386]
After migrating a private repo to the new YAML format, the project started erroring out at the "git_sync" phase as follows:

    ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; cd /root/src/[path removed] && git clean -f && git fetch'
    Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
    fatal: Not a git repository (or any of the parent directories): .git

As you can see, for some reason Shippable isn't including the "git clone" statement after "ssh-add". This is working fine in a different repo / project. Is this a known issue? I've tried deleting and re-adding the project, and other variations on that.

Thanks for your help.

**Comment by rageshkrishna** [comment]
@cjerdonek I'm looking in to this now. I'll have some updates for you soon.

**Comment by cjerdonek** [comment]
Thanks!

**Comment by rageshkrishna** [comment]
@cjerdonek The fix for this is being tested in beta right now. This will be available in production very soon.

**Comment by f3l1x** [comment]
@rageshkrishna @cjerdonek Same error with me.

**Comment by rageshkrishna** [comment]
@cjerdonek The fix for your issue has been deployed to production. Please let me know how your next few builds look. Thanks!

**Comment by cjerdonek** [comment]
@rageshkrishna It's working now. Thanks for your prompt response and for addressing this so quickly!
