### ISSUE TITLE
Trying to migrate to the new yml configuration but now all my builds are broken

### ISSUE THREAD

**Issue by osumampouw** [Shippable/support#2387]
Hi,

So I followed your instructions to upgrade the build plan to _continuous delivery plan_. After that all my builds started to fail. And I have been trying to fix the .yml file. 

So:
1.) This is the first failure after I upgraded to continuous delivery plan. https://app.shippable.com/runs/56e8c447c8cfb20d00aa8de8
2.) A bit about our project config:
I use the docker configuration for my project only to cache the image. So I use the default docker image. I don't push image to hub nor do I use lighthouse notification. That means I have to upgrade my .yml file right?
3.) Attached is my old .yml file and my new .yml file. Even after the change, now shippable just stops and not doing anything. 
[shippable.zip](https://github.com/Shippable/support/files/175407/shippable.zip)
This is the build where it just stops doing anything after I change yml using the new format
https://app.shippable.com/runs/56e8fbf606121a0c0065a819

Can you take a look at them?

Thanks
-Oby

**Comment by manishas** [comment]
@osumampouw are you still having issues? Your latest builds are green, so checking before we investigate this.

**Comment by osumampouw** [comment]
Hi manishas, the reason why its green is because i reverted the yml and disable the container option just to unblock this problem. Because we have to deploy. But ideally we still would like to have the old option back.

So yeah, can you help see the configuration yml?

**Comment by a-murphy** [comment]
I'm not sure which yml you are trying to use, but here's what I noticed:

If you're using ```new_shippable.yml```, ```pre_ci_boot``` should be in the ```build``` section like ```ci``` and ```on_success```.

The SSH keys have been moved to ```/tmp/ssh``` and renamed, so that will need to be updated for either yml.  It looks like you are trying to use the subscription SSH key, so you might be able to just remove the ```ssh-add``` line.  These resolved issues are related: #2375 and #2395.

**Comment by osumampouw** [comment]
oh ok thanks for the hints. I will give it a try. 
I have a question about the image_name. So I'm using drydock. What's the difference between all the images there? For example u14 vs u12 ?

**Comment by kanthchandra** [comment]
Hi @osumampouw, Here is the guide which gives an idea about the naming conventions used for the images http://docs.shippable.com/ci_configure/#setting-your-build-image

**Comment by osumampouw** [comment]
so for this https://hub.docker.com/r/drydock/u14nodpls/tags/
there are 3 tags. My build has an error because I specify the tag as 'latest'
Now I change it to 'prod'.
What's the difference between 'prod', 'marker' and 'tip'?

**Comment by chetantarale** [comment]
@osumampouw  Every newly build image is first tagged as `tip`.
We then test tip to work with sample projects and test cases and then tag it as `prod` if everything is working fine on that image.
`marker` is something we use internally when patching images.

**Comment by osumampouw** [comment]
oh ok, cool thanks. Mine's working now after I made some changes. I'll use prod for stability then. Thanks
