### ISSUE TITLE
Shippable failed to build a release

### ISSUE THREAD

**Issue by aftabaslam** [Shippable/support#2388]
Hi, 
My builds are getting  failed from yesterday 
Following are the errors in the build log 

W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B70731143DD9F856
W: A error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.opera.com stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 63F7D4AFF6D61D45

W: Failed to fetch http://deb.opera.com/opera/dists/stable/Release  

can you please look into this issue.

**Comment by trriplejay** [comment]
Hello,

Shippable recently moved to a new build system, and I suspect that some of the difference in the new platform are causing this issue with your build.  There are a few ways in which you could fix this.

1. I see that your build is relying on our old default image: shippable/minv2.  Instead, you could try specifying an image in your yml like this: `build_image: drydock/u14phpall:prod`.  A guide to our new images can be found here: http://docs.shippable.com/ci_configure/#setting-your-build-image

2. To fully utilize the new system, you should migrate your yml to the new format. This will also cause Shippable to automatically select one of our new images for your build.  Here is a migration guide that takes you through everything you need to know about updating yml: http://blog.shippable.com/migrating-to-the-new-build-platform

Please let us know if this doesn't work for you, or if you have any further questions.

**Comment by manishas** [comment]
Closing this issue since this was answered. Please let us know if you run into any issues and we'll reopen. thanks!
