### ISSUE TITLE
Issue with Git Sync command 

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#2389]
Hi,

I am getting continuous and errors on my multiple projects. Git Clone command is failing with 

`
ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git clone ssh://git@bitbucket.org/medharbour/web.git //src/bitbucket.org/medharbour/web'
Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
Cloning into '//src/bitbucket.org/medharbour/web'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
`

None of my projects are building correctly.

Can somebody help with this.

**Comment by rageshkrishna** [comment]
Hi @naveensky. It looks like you've been migrated to our new build platform. The issue you're running in to is that we no longer specify a user for the docker containers when we launch them. Unfortunately, the shippableImages containers do not specify USER or HOME variables on their own, either. As a result, SSH is unable to find an appropriate config file (because it's going to look in $HOME/.ssh).

There are a couple of ways you can fix this. If you're still using the old YML format, add the following to your `env`:

````
env:
  global:
    - USER=root
    - HOME=/root
````

The solution above will also work if you are using the updated YML format, but with the new format you can also specify a user and environment as a docker option in the `pre_ci_boot` section of the YML:

````
pre_ci_boot:
  image_name: shippableImages/ubuntu1404_scala
  image_tag: latest
  options: "--user root -e HOME=/root" 
````

This keeps your docker settings cleanly separated from build environment variables.

Let me know if you need any more help with this.

**Comment by f3l1x** [comment]
@rageshkrishna @cjerdonek Same error with me.

-----

Current:

```
ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git clone ssh://git@bitbucket.org/__MY__/__REPO__.git /home/shippable/workspace/src/bitbucket.org/__REPO__'
Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
Cloning into '/home/shippable/workspace/src/bitbucket.org/__REPO__'...
Warning: Permanently added 'bitbucket.org,104.192.143.3' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Previsous build:

```
ssh-agent bash -c 'ssh-add /home/shippable/.ssh/project_rsa; git clone ssh://git@bitbucket.org/__MY__/__REPO__.git /home/shippable/workspace/src/bitbucket.org/econea/__REPO__'
Identity added: /home/shippable/.ssh/project_rsa (/home/shippable/.ssh/project_rsa)
Cloning into '/home/shippable/workspace/src/bitbucket.org/__MY__/__REPO__'...
Warning: Permanently added 'bitbucket.org,104.192.143.3' (RSA) to the list of known hosts.
```

I see difference between `/tmp/ssh/01_deploy` and `/home/shippable/.ssh/project_rsa`. Can you help me?

**Comment by naveensky** [comment]
@rageshkrishna - I am still getting the error even after adding env variable. My current build is https://app.shippable.com/runs/56e9690906121a0c0073497a

**Comment by rageshkrishna** [comment]
@naveensky I just took a deeper look at the issue. It looks like there is an issue with using shippableImages. The ideal way to fix this would be to migrate to the new YML format which will allow you to use docker options as I listed in my previous comment.

Please let me know if you need help with this. If you can share your current YML file with me at ragesh@shippable.com I can show you how to use the new format.

If you'd rather not change the YML right away, you can try changing your build image from `shippableImages/ubuntu1404_scala` to one of the newer drydock scala images. Depending on whether you need any services, you can use either `drydock/u14sca:prod` (which has no services) or `drydock/u14scaall:prod`.

**Comment by naveensky** [comment]
@rageshkrishna I have email the file to you. Also I updated the docker file to drydock/u14scaall:prod but I am still getting same error

**Comment by naveensky** [comment]
@rageshkrishna Its not working with updated shippable file. The build url is https://app.shippable.com/runs/56e986f6ae35a90c007e2034

**Comment by rageshkrishna** [comment]
It looks like your build is moving past the `Host key verification failed.` issue now. The latest builds are failing because authentication is being rejected by BitBucket. I'll figure out what's going on with this and get back to you soon.

**Comment by naveensky** [comment]
@rageshkrishna Any luck with identifying the issue ?

**Comment by rageshkrishna** [comment]
@naveensky For some reason, BitBucket is not accepting the project's SSH key. Can you please try hitting the "Reset" button from the project's settings page? This should generate new keys and push them to BitBucket. If you are using any secure env variables in this project you will need to encrypt them once again after the reset.

**Comment by naveensky** [comment]
@rageshkrishna I did a reset with subscription and tried again. Getting the error https://app.shippable.com/runs/56ea68d0c594df0d009a0fe6

**Comment by rageshkrishna** [comment]
It's not the subscription you need to reset. There's a reset button in the project's settings tab. This is the one that will update your project's keys on BitBucket. Please try that instead.

I also see that this build is still using shippableImage/ubuntu1404_scala. Can you please switch it back to `drydock/u14scaall:prod` after the reset and try a build with that?

**Comment by f3l1x** [comment]
Reset button occurred error.

```
(Id: 2000) No access or object not found for id: 56a66b161895ca447472870e
warn: common|validateProjs|callerId:56a67495e76bb80e001b891b|_checkProjectPermissions
```

**Comment by rageshkrishna** [comment]
@f3l1x We currently only allow project owners to perform the reset operation because it involves changing keys on the source provider. Can you please ask one of the owners to try it?

**Comment by f3l1x** [comment]
@rageshkrishna I'm only owner. Or you mean BitBucket project owner? It owns a company and I have i read/write permission.

**Comment by rageshkrishna** [comment]
@f3l1x Yes, it needs to be a BitBucket project owner.

**Comment by rageshkrishna** [comment]
@naveensky It looks like your builds are running successfully now. Please let me know if you have any more problems.

**Comment by naveensky** [comment]
@rageshkrishna Though builds are working fine, my executable file deploy.sh is not executing. It contains my logic to deploy artifacts to beta/prod servers.

https://app.shippable.com/runs/56ea953d9b8e4e0c00a82d4c

The file with deploy.sh is just not doing anything if you see the output of it. Either it should run or produce an error.

**Comment by naveensky** [comment]
@rageshkrishna Things looking better. The cache container command is taking huge time to cache, unlike previous times. Not sure if its a bug or it really needs 20+ mins to cache container.

**Comment by naveensky** [comment]
@rageshkrishna The build url https://app.shippable.com/runs/56ea9d0317639a0d0094c697

**Comment by manishas** [comment]
The cache issue is a known issue and we are addressing it with a new implementation for caching that is folder based. This will be available in the next couple of days.

**Comment by naveensky** [comment]
@manishas @rageshkrishna I have got my builds running again. Thanks for your support during this entire thing :+1: 

I am just worried about image cache. Is there a quick work around for those. My builds which were previously taking 5 mins have gone to 20 mins. Is there any temporary fix which I can work with for now till the time you guys complete your cache feature ?

**Comment by manishas** [comment]
The new cache implementation will be available tomorrow. We'll update this issue with instructions on how to use it.

**Comment by manishas** [comment]
We have deployed the new caching implementation to production. Docs have also been updated - http://docs.shippable.com/ci_configure/#caching-your-container

As mentioned in the docs, simply having a ```cache: true``` in the build section of the yml will result in $SHIPPABLE_BUILD_DIR being cached. You can also choose to cache specific folders using the `cache_dir_list` tag in addition.

```
build:
  cache: true
  # cache_dir_list is optional. If not present, we will cache $SHIPPABLE_BUILD_DIR.
  cache_dir_list: 
    - dir1
    - dir2
    - dir3
```
The first build you run with cache turned on might show an error during the upload cache step but the cache should be successfully pushed during the second build and be available thereafter.
