### ISSUE TITLE
Control version of the elasticsearch service

### ISSUE THREAD

**Issue by gtnx** [Shippable/support#2390]
I'm using the elasticsearch service in one my continuous integration script and printed the Elasticsearch version:

    Version: 1.1.1, Build: f1585f0/2014-04-16T14:27:12Z, JVM: 1.8.0_25

- The version is very old. Is it possible to upgrade it?
- The best would be to control the version. Is it possible?

**Comment by manishas** [comment]
@gtnx your build is using the legacy image shippable/minv2 which is an outdated image that we plan to deprecate soon.

Our new official images are in the [drydock repository on docker hub](https://hub.docker.com/u/drydock/). Naming convention is explained [in our documentation](http://docs.shippable.com/ci_configure/#setting-your-build-image). The pls and all versions of images have elasticsearch 1.5.1 installed on them. 

To use the new images, you will need to convert your yml to the new syntax, as explained [in this migration guide](http://blog.shippable.com/migrating-to-the-new-build-platform). Once you migrate the correct official build image will be selected for you by default.

Let me know if you need help with this.

**Comment by manishas** [comment]
Also, if you want a specific version, you can always skip specifying elasticsearch in the `services` tag and install a specific version in the yml. you'll need to handle starting/stopping the service in your yml as well if you choose to go this route.

**Comment by manishas** [comment]
I am closing this issue since the question was answered. Please let me know if you have any more questions or run into any issues. Thanks!

**Comment by gtnx** [comment]
Thanks @manishas . do you have any example of handling a specific elasticsearch version in the yml with all the starting/stopping stuff?
