### ISSUE TITLE
git clone failing

### ISSUE THREAD

**Issue by iivvoo** [Shippable/support#2391]
We're using old-style yaml files and suddently our projects no longer build. Earlier build that succeeded are also failing. The builds are currently breaking on cloning the git repo:
```

 ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git clone ssh://git@bitbucket.org/kascooperatie/knipapp.git //src/bitbucket.org/kascooperatie/knipapp'
Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
Cloning into '//src/bitbucket.org/kascooperatie/knipapp'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
See, for example, https://app.shippable.com/runs/56e9577dfbb4d40d003b9ade

Explicitly setting HOME and USER to (resp) /root and root has no effect.

**Comment by rageshkrishna** [comment]
@iivvoo Can you try changing your build image from `shippableimages/ubuntu1404_nodejs:latest` to `drydock/u14nod:prod`?

**Comment by iivvoo** [comment]
That seems to solve the issue. Is this a workaround or can it be considered a permanent fix?

Also I noticed another issue now that tests work again, I will create a new issue for this.

**Comment by rageshkrishna** [comment]
The fix is permanent. Moving forward, the `drydock` images are what we will continue to update and support.

I'm going to close this issue now as it has been resolved.
