### ISSUE TITLE
shippable handles "env:" differently

### ISSUE THREAD

**Issue by iivvoo** [Shippable/support#2393]
We used to have

```
env:
  CI=true

```
in our (old-style) shippable.yaml. This worked for us

```
Matrix Values 
  Runtime: 5.5.0
  Environment Variables:
  CI="true"
```

However, since recent changes shippable handles this differently. It will run a test for each individual character in env. In our case: 'C', 'I', '=', 't', 'r', 'u', 'e'

The fix for us is simple: fix the yaml:

```
env:
 - CI=true
```

However, you might want to check how you want to handle this on your end - spawning many (useless, possibly incorrect) jobs may not be optimal.

**Comment by rageshkrishna** [comment]
Thanks for reporting this. This is definitely a bug at our end and we'll look in to it.

**Comment by a-murphy** [comment]
It's being parsed as one variable now.

**Comment by manishas** [comment]
Closing this since this in production.
