### ISSUE TITLE
Shippable not kicking off builds from github checkins

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2394]
We have found our builds are very slow to trigger right now...

**Comment by manishas** [comment]
@trriplejay  can you look into this?

**Comment by manishas** [comment]
@chriskinsman we're figuring out if GitHub is sending webhooks with a delay or if we're doing something funny. Will have an update soon.

**Comment by manishas** [comment]
@chriskinsman this seems to have resolved itself since we're not seeing it for our projects any more. At this point, not sure if this was a GitHub issue or ours, but we'll keep a watch.

Let me know if your projects are still triggered slowly.

**Comment by manishas** [comment]
Closing this since I don't think this is happening any more. Let us know if this is still a problem for you and we'll reopen and investigate.
