### ISSUE TITLE
Can't find SSH key

### ISSUE THREAD

**Issue by jamesmk** [Shippable/support#2395]
Hello,

After upgrading our plan today, our deploys are failing. We've been accessing the container's key to enable agent forwarding in our Capistrano deploy. This is the command we use:

```
ssh-agent bash -c 'ssh-add /home/shippable/.ssh/id_rsa; ssh -i /home/shippable/.ssh/id_rsa -vT git@bitbucket.org; cap $DEPLOY_BRANCH deploy'
```

This now returns `/home/shippable/.ssh/id_rsa: No such file or directory`. Did this file move in the migration?

Here is an example build: https://app.shippable.com/runs/56e9944a132d570c00d8bf4d

cc @cpitkin

Thanks!

**Comment by a-murphy** [comment]
Yes, the keys were moved to ```/tmp/ssh``` and renamed ```00_sub``` and ```01_deploy```.  It looks like you are using the subscription SSH key, ```00_sub```.

**Comment by jamesmk** [comment]
That did the trick, thanks!
