### ISSUE TITLE
Permission denied during "pip install --upgrade awscli"

### ISSUE THREAD

**Issue by antonbabenko** [Shippable/support#2396]
Suddenly, today I get this error when trying to install awscli:
```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 228, in run
    requirement_set.install(install_options, global_options)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1089, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 476, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1391, in remove
    renames(path, new_path)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 248, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/bin/aws'

Storing complete log in /home/shippable/.pip/pip.log
```

Failed build for investigation - https://app.shippable.com/runs/56e9a9a1132d570c00dc1b6a

**Comment by trriplejay** [comment]
Previously, the container was running as root, however we recently updated our build platform such that this is no longer the case.  There are a few ways that this can be fixed.

1. in your Shippable.yml, specify one of our new drydock images as your build image like this:
`build_image: drydock/u14phpall:prod`.  A guide to our images can be found here: http://docs.shippable.com/ci_configure/#setting-your-build-image

2. Migrate your yml to the new format used by our new build system.  It looks like you're using shippable/minv2 as your build image, which used to be our default.  However, if you update your yml to the new format, Shippable will select one of our newer images to use as the default based on your project's language.  Here is a migration guide that takes you through everything you need to know about updating yml: http://blog.shippable.com/migrating-to-the-new-build-platform

3. It's likely you could also make this work by adding 'sudo' to the command.

please let us know if any of these steps don't work for you.

**Comment by antonbabenko** [comment]
Adding `sudo` was the fastest solution which helped. Thank you!

**Comment by willwillzhang** [comment]
How about the windows?
