### ISSUE TITLE
Pass "--user root" to "docker run" in boot_container phase

### ISSUE THREAD

**Issue by cjerdonek** [Shippable/support#2397]
I noticed that setting `USER` to a non-root user in one's Dockerfile causes the "boot_container" phase to fail with the new YAML format.

This is because Shippable's invocation of `docker run` in the boot_container phase doesn't pass `--user` and so defaults to using the Dockerfile's `USER`. I believe Shippable expects this command to be run as root (which is what is causing the phase to fail in this situation). It seems like Shippable should be passing `--user root` in its `docker run` invocation in the "boot_container" phase:

    $ sudo docker run -d --privileged=true --net=bridge -v ...

**Comment by manishas** [comment]
@cjerdonek we're already working on this and a fix should be available soon.

**Comment by ric03uec** [comment]
@cjerdonek 
- this is a known issue and we're working on it. the fix will be deployed within next day.
- your assessment was correct and we are not passing `--user` argument to docker run. This is resulting in the `ci` step using the Dockerfile's `USER`. Now this dependency will be removed and the Dockerfile can have any value of `USER` set without it affecting the shippable ci scripts. Also, the docker run can have any value of `--user`.

**Comment by cjerdonek** [comment]
Great, @manishas and @ric03uec. Thanks for the update and for working on addressing this so quickly!

**Comment by ric03uec** [comment]
@cjerdonek this is now deployed. can you please verify if its working as expected for you.

**Comment by cjerdonek** [comment]
@ric03uec No, it's still failing at the same point in the boot_container / wait_for_exit phases. Shippable is still not passing `--user root` in its call to `docker run` in the boot_container phase like I suggested that it do above:

    $ sudo docker run -d --privileged=true --net=bridge -v ...

**Comment by ric03uec** [comment]
@cjerdonek the following changes were made in the latest update
- [bug] setting `USER` in dockerfile does not cause the builds to fail now
- [bug] setting `-e USER=foo` in docker run options does not cause the build to fail now
- you are free to provide any value of `USER` in the docker run options. 

So, not setting `--user root` by default is intentional. If you want you can add a section in the yml, that does this. e.g.

```
build:
  pre_ci_boot:
    image_name: drydock/u14pytall
    image_tag: prod
    pull: true
    options: '--privileged=true --net=bridge -e USER=root'  // and/or --user=root

ci:
  - <your ci command(s)>
```

**Comment by cjerdonek** [comment]
Okay, I see now. I added `--user=root` to the "pre_ci_boot" options, and it is working now. Thanks a lot for your help, @ric03uec.

Personally, I think `--user=root` should be included in your default options (along with `--privileged=true` and `--net=bridge`) since root permissions are needed for Shippable's boot to succeed, but I can add it myself manually. Thanks.

**Comment by manishas** [comment]
Closing this issue.
