### ISSUE TITLE
postgresql service not starting on minv2

### ISSUE THREAD

**Issue by ric03uec** [Shippable/support#2398]
![image](https://cloud.githubusercontent.com/assets/1110988/13833160/52e8fc5e-eba0-11e5-9901-55e03f4365d1.png)

- specifying `postgresql` as a service results in the warning and the service is not started when the `ci` container boots

**Comment by rageshkrishna** [comment]
This works in beta now.

**Comment by manishas** [comment]
Closing this issue.
