### ISSUE TITLE
bring in coverage report in custom image?

### ISSUE THREAD

**Issue by magwas** [Shippable/support#2400]
I am running build in a custom docker image. Coverage report fails with

    /root/src/github.com/magwas/PDOauth/shippable/codecoverage
        /root/bf0be5d6-7863-4d6f-8df6-16e5774877b1.sh: line 58: reports: command not found

Please document what should I install to the image to enable coverage/test/etc reports?
(Low priority, as I have worked it around by creating and exporting my own report.)
Build: https://app.shippable.com/runs/56e9e3229af9af0c00da456c

**Comment by henrjk** [comment]
I am interested into this as well.

**Comment by manishas** [comment]
This has not been fixed, so closing. Please let us know if you still don't see test and coverage reports.
