### ISSUE TITLE
Triggering builds on branch with the API fails with 500: Unable to find the specified branch.

### ISSUE THREAD

**Issue by HelainSchoonjans** [Shippable/support#2401]
Dear Shippable supports,

I have frequently used the API to trigger builds on specific branches of projects but after having enabled builds with a new branch I recently had 500 errors while trying to trigger builds of the branch.

Output from my script: (Using _Post_ on /projects/ + project_id + /newBuild with branchName = "shippable_migration" )
> Failed to trigger build for projectId '55cdad20edd7f2c052a81eb0' and branch 'shippable_migration'.
> Status code: 500
> Response message: {"logType":"verbose","methodName":"projects|triggerNewBuildRequest:55cdad20edd7f2c052a81eb0|_getProjectById","id":4005,"message":"Unable to find the specified branch, shippable_migrationPlease sync the project and try again"}

The branch exists and some builds even already have been automatically triggered when some commits were pushed on it. This branch has been created to experiment with the new shippable.yml syntax and contains an yml with runs enabled for this branch. 

I can see its past builds in the project history on the Shippable app, but can't see it in the list of branches in the summary, even when checking the "Show all branches" box.

Triggering builds on my other branches ( "master" and "rc" ) with the same script does work however.

**Comment by kanthchandra** [comment]
Hi,  As the message states this branch might have been pushed recently and the project has not yet been on synced on shippable. So can you please go to project settings page and force sync the project. After the sync the branch should be present and we will be able to trigger the build

**Comment by HelainSchoonjans** [comment]
Thanks! It works!
