### ISSUE TITLE
Using rvm in a node_js yml

### ISSUE THREAD

**Issue by algarpe** [Shippable/support#2402]
Hi,

Before the migration, my builds worked perfectly. But after it, I cannot install ruby as I used to.
My builds worked with:
`- source ~/.rvm/scripts/rvm
- rvm install ruby-2.0.0-p598
- source ~/.bashrc && ~/.rvm/scripts/rvm && rvm  use 2.0.0
- gem install compass`

But now, I'm stuck.

Any suggestion?

Thanks...

**Comment by a-murphy** [comment]
Your builds are now running on the new default NodeJS image, which is smaller and faster, but doesn't have ```rvm``` installed, or other things for languages that aren't JavaScript.  The easiest solution is probably to install ```rvm```.

This is how we are installing ```rvm``` in the new Ruby default image (full install script used in the Dockerfile [here](https://github.com/dry-dock/u14rub/blob/master/install.sh)), which you could add to your shippable.yml:
```
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -sSL https://get.rvm.io | bash -s stable
echo '[[ -s /etc/profile.d/rvm.sh ]] && source /etc/profile.d/rvm.sh' >> $HOME/.bashrc
[[ -s /etc/profile.d/rvm.sh ]] && source /etc/profile.d/rvm.sh
```
Then installing versions like [this](https://github.com/dry-dock/u14rub/blob/master/version/2_0_0.sh):
```
rvm requirements
rvm install 2.0.0
rvm use 2.0.0
gem install bundler
```

If the installation is too slow to run every build, I would suggest creating your own Docker image to use in your builds.  Switching back to the shippable/minv2 image is also an option, but there are some known issues with that on the new build system and it is a rather large image.

**Comment by algarpe** [comment]
Installing ruby with curl, works fine. But next line (echo with brackets) breaks yml format. How should it be?

**Comment by a-murphy** [comment]
Single quotes around the line ```'[[ -s /etc/profile.d/rvm.sh ]] && source /etc/profile.d/rvm.sh'``` seems to make the YML parse and not cause an error in the build if it's directly in shippable.yml.

**Comment by algarpe** [comment]
I've solved it like this:

`- source /etc/profile.d/rvm.sh && rvm install ruby-2.0.0-p598`

Thanks

**Comment by manishas** [comment]
closing this issue.
