### ISSUE TITLE
redis server not starting on minv2

### ISSUE THREAD

**Issue by ric03uec** [Shippable/support#2403]
- if the service name `redis-server` is provided, it does not start redis server
![image](https://cloud.githubusercontent.com/assets/1110988/13854850/bef1b4ec-ec2a-11e5-9ce0-47c15d970744.png)

- the service name should support bot `redis` and `redis-server`

**Comment by manishas** [comment]
@a-murphy can you work on this?

**Comment by a-murphy** [comment]
Beta-verified.  The ```redis_start``` step appears now.

**Comment by manishas** [comment]
this is now in production. closing.
