### ISSUE TITLE
Builds fail after upgrading to new yml format

### ISSUE THREAD

**Issue by mmindenhall** [Shippable/support#2405]
I just completed the process of upgrading our build to the new yml format.  Everything is succeeding in the build, but the `build_on_success` phase shows the red 'X' indicating that something failed.  When I drill down into the commands executed during that phase, everything looks to be completing successfully.

These are the exact same commands that were executing (and succeeding) in the `after_success` phase of the old yml.  Any idea what might be going wrong here?

https://app.shippable.com/runs/56eaf4e89c57b30d00936ab6

**Comment by trriplejay** [comment]
Hello, 

It looks like this this is caused by a change we made to one of our environment variables.  A fix should be available later today.  I'll update again once it's been deployed.

**Comment by trriplejay** [comment]
This fix is deployed now. Let me know if you have any other issues.
