### ISSUE TITLE
git_sync issue

### ISSUE THREAD

**Issue by svo** [Shippable/support#2407]
Hi,

I have been going through the process of updating my shippable.yml as per email regarding changes and am trying to run builds to test the change.

Unfortunately I'm encountering an issue with the `git_sync` stage of the build process as per below:

```
ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git clone git@github.com:<repository details> //src/github.com/<repository details>'
Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
Cloning into '//src/github.com/<repository details>'...
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I've tried:

* reseting deployment keys
* adding subscription deployment key to github ssh keys (have since removed as it didn't seem to help)
* disabling two factor authentication on github (have re-enabled as it didn't seem to help)
* regenerating access token for github

Any assistance with getting the build up and running again would be greatly appreciated.

Many thanks.

**Comment by manishas** [comment]
@svo are you using a build image from shippableimages? Those are our older images and are experiencing issues on the new platform. If you are already using new format, skipping the pre_ci_boot section will choose one of our new official images and this should get you past this problem. 

Let me know if that works.

**Comment by manishas** [comment]
Actually i just checked and you're using a custom image. In that case, check out our blog that calls out this error and how to fix it - http://blog.shippable.com/5-tips-for-a-successful-migration

Tip #5: Fix git_sync error: Host verification key failed

A couple of customers started seeing a "Host verification key failed" errors in their console logs after migration. This might happen if you are using a custom image for your build which does not set the $HOME environment variable. This creates a problem when we try to update your ~/.ssh/config to insert StrictHostKeyChecking no. To fix this error, you can either update your Dockerfile to set the $HOME environment variable, or you can set it in your pre_ci_boot section in the options tag:

```
build:
  pre_ci_boot:
    image_name: your/image
    image_tag: your_tag
    options: "-e HOME=/root"
```

**Comment by svo** [comment]
Hi @manishas,

My CI image was based on one of the older shippableimages images.

I have built it anew using the dry-dock equivalent and now, after some fiddling, have a green build.

Thanks very much for your time... it has been greatly appreciated.

**Comment by manishas** [comment]
:+1:
