### ISSUE TITLE
Unable to add "My Own" onsite-node

### ISSUE THREAD

**Issue by cramblda** [Shippable/support#2408]
I have been attempting to add my own onsite node to our shippable account. I have tried both initialization options: 1) via ssh and 2) via create initialization scripts.

The ssh method adds the node, but then never attempts to connect via ssh to initialize the node. I can see an error occurs in the web browser console, complaining about the body of the message, specifically in regards to the "status".

The create scripts option just spins forever creating scripts and never finishes.

**Comment by manishas** [comment]
@cramblda we will look into this and get back to you with an update.

**Comment by manishas** [comment]
@cramblda does your node satisfy the following minimum requirements [specified in our docs](http://docs.shippable.com/ci_byoh/#minimum-requirements) -
1.8GB RAM
30GB SSD
Ubuntu 14.04 OS
64-bit architecture

If not, it will fail to initialize. We're working on adding better messaging for this scenario.

**Comment by manishas** [comment]
@cramblda can you try again? We discovered an issue and it is now resolved.

**Comment by cramblda** [comment]
Yes its working. Thanks.
