### ISSUE TITLE
Custom docker image not found

### ISSUE THREAD

**Issue by david-anyvan** [Shippable/support#2410]
I am trying to get our builds working with our own private docker image - it was pulling the image earlier, but now after updating the docker image it keeps coming up as not found.

**Comment by manishas** [comment]
@david-anyvan did you upgrade to the new yml format? Can you share your shippable.yml so we can take a look?

**Comment by david-anyvan** [comment]
Yes, I have changed to the new format - file attached
[shippable.yml.zip](https://github.com/Shippable/support/files/181982/shippable.yml.zip)

**Comment by rageshkrishna** [comment]
@david-anyvan, the `integrations` part of the YML needs to be at the same level as `build`, not nested within in. Please take a look at http://docs.shippable.com/ci_configure/ for some examples of this. Moving this should allow your docker hub integration to work correctly and get your image pulled.

**Comment by david-anyvan** [comment]
Thanks - odd that it worked the first time around, and only failed after I updated the image - must have been cached before somehow

**Comment by manishas** [comment]
closing since this is resolved.
