### ISSUE TITLE
How can I use xvfb to run firefox?

### ISSUE THREAD

**Issue by moslemezzati** [Shippable/support#2412]
First of all thanks for your great service, I have issue about running Firefox due to test, here is my yml file
```
# Build Environment
build_environment: Ubuntu 14.04

language: node_js

node_js:
  - 4.3.2
addons:
  firefox: 44.0.2

install:
  - npm install karma karma-cli grunt-cli -g
  - npm install
#  - bower install
# Make folders for the reports, and create the SQL db
before_script:
  # run xvfb
    - export DISPLAY=:99.0
    - etc/init.d/xvfb start

after_script:
  - /etc/init.d/xvfb stop

script:
  - npm test
```

and my console:
![shippable](https://cloud.githubusercontent.com/assets/4618195/13890978/a3aa0af6-ed63-11e5-8f98-eb3c394a131b.png)

my build link is:
https://app.shippable.com/runs/56ec17506b2b030d0077a2b8
How can I fix it?

**Comment by rageshkrishna** [comment]
Hi @moslemezzati. Here's a sample YML you can use: https://github.com/shippableSamples/sample_node_selenium/blob/master/shippable.yml

The key difference is that we no longer allow starting xvfb as a service. Instead, you need to run your test command with `xvfb-run`. I hope this helps.
