### ISSUE TITLE
Builds hangs at provision job node

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#2413]
I still have builds that hangs at provision job node. Especially when doing rebuilds. I have disabled caching but did not help.

**Comment by manishas** [comment]
We deployed a couple of fixes on Friday to address this intermittent issue. Can you please try again and let me know if this is still happening?

**Comment by jeppefrandsen** [comment]
@manishas it seems still to be a problem. You are welcome to trigger some builds on my behalf.

**Comment by manishas** [comment]
@rageshkrishna can you please follow up on this asap?

**Comment by rageshkrishna** [comment]
I'm looking in to this now.

**Comment by jeppefrandsen** [comment]
@rageshkrishna It seems the build now continued after ~15 minutes. Will provision job node always take this long? Thanks

**Comment by jeppefrandsen** [comment]
@rageshkrishna Build 115 still hangs in provision job node after enabling cache again.

**Comment by rageshkrishna** [comment]
Provision node definitely shouldn't take that long. This is one of the things I'm looking in to. Would you mind if I cancel your currently running builds? There are a couple of things I'd like to do to debug this, but I need to first get to a clean slate with no running builds.

**Comment by jeppefrandsen** [comment]
Yes, sure. Just go ahead.

**Comment by rageshkrishna** [comment]
@jeppefrandsen It looks like the builds for one of the projects is pretty CPU intensive. I was just wondering what kind of build times you see locally, and the type of hardware you typically run them on (how much RAM, and how many cores?) . I'm trying to rule out any environment issues that could be causing builds to slow down in the new build system.

**Comment by jeppefrandsen** [comment]
@rageshkrishna I normally build it on a i5-4300 (dual core, 4 threads) with 3 threads and 6 GB RAM assigned to the VM running Linux. The build time is a bit less than 1 hour. Will just do a local build to verify.

**Comment by AndreCimander** [comment]
We are also having 100% stalling builds while provisioning a job node.

**Comment by rageshkrishna** [comment]
@AndreCimander Can you give me the github or bitbucket username you use to sign in to Shippable? Thanks.

**Comment by AndreCimander** [comment]
@rageshkrishna sent the information via mail :mailbox: Feel free to trigger builds.

**Comment by jeppefrandsen** [comment]
@rageshkrishna build time is around 50 minutes on my laptop.

**Comment by rageshkrishna** [comment]
@jeppefrandsen Thanks. I've rounded down the problem to the fact that we now provide only only two cores on the build machines. I could see the CPU load on these machines go over 12, and after that everything locks up. 

I think you may need to attach custom nodes to your subscription to get around this. The alternative is to use fewer threads for your compiles, but this would make the builds run slower which is a bad trade-off.

I also think that this is what is causing the issues with jobs getting stuck at "provisioning node". The system believes the node should be free after the job times out, but the node is so overwhelmed by the CPU load that the runner is unable to terminate the build and pick up any new jobs.

**Comment by rageshkrishna** [comment]
@AndreCimander I'm looking in to your issue now

**Comment by jeppefrandsen** [comment]
@rageshkrishna okay. Thank you very much. Will look into using a custom build node instead.

**Comment by rageshkrishna** [comment]
@jeppefrandsen FWIW, I tested with a custom node from DigitalOcean (4 cores, 8GB) and a build ran in 36 minutes.

**Comment by rageshkrishna** [comment]
@AndreCimander Your issue should be resolved now. Please let me know if you still have trouble triggering builds. Thanks!

**Comment by manishas** [comment]
@jeppefrandsen let me know if you need any help with setting up custom nodes. Couple of links that might help:

[Overview of running builds on your own machines](http://docs.shippable.com/ci_byoh/)
[Instructions showing how to attach build nodes to your subscription](http://docs.shippable.com/ci_subscriptions/#adding-your-own-build-infrastructure-byoh)

**Comment by jeppefrandsen** [comment]
@manishas thank you very much - and thank you for an outstanding support! Currently looking into using Linode servers.
