### ISSUE TITLE
Add user options to define display rules for build status on sub/home page

### ISSUE THREAD

**Issue by cratz** [Shippable/support#2420]
on homepage and on subscription home page in status section (see: #2219)
It still looks like shippable is only checking `master` branch (two working jobs) and it is not working for other branches. 
Is it intended to work like this or should it show the latest build?

![statusstuck](https://cloud.githubusercontent.com/assets/351588/13925752/d5f58a9e-ef89-11e5-996b-898bcc824474.png)

**Comment by manishas** [comment]
@cratz this is the logic:
- Show status of latest build for default branch of project
- If no default branch, show status of latest build of master branch
- If no default and no master branch, show status of latest build (across branches)

Let me know if this is not working according to the logic above.

**Comment by cratz** [comment]
@manishas,
thanks for the explanation!
It is not working according to the logic you described.

> Show status of latest build for default branch of project
works for us

> If no default branch, show status of latest build of master branch
works for us

> If no default and no master branch, show status of latest build (across branches)
not working always shows 0. 
Our default branch is 'master' and has no builds yet but we have ~420 builds in this project on multiple branches.

As @mspanc mentioned in the original issue this is not critical and it's nothing that prevents us from using shippable.

**Comment by manishas** [comment]
> Our default branch is 'master' and has no builds yet but we have ~420 builds in this project on multiple branches.

If your default branch is master and has no builds, that's why it shows 0. The first condition (Show status of latest build for default branch of project) is being called  so its showing latest build for master.

Am I missing something?

**Comment by cratz** [comment]
I think our case should match 3th condition:
> If no default and no master branch, show status of latest build (across branches)

No builds on master (and / or default) branch should show latest build and branch should not matter.

**Comment by manishas** [comment]
So you're suggesting that if a branch has 0 builds, treat it as if the branch doesn't exist.... we'll need to think through the scenarios before making this change. I'll mark this feature request.

**Comment by cratz** [comment]
Yes something like this or may be even simpler by just showing the latest build of the project without any logic of checking branches. Users will be still able to check status of all branches on the project page.
The problem I see with applying any logic at this place is that no matter how sophisticated your algorithm is it will never fit to all of your customers.

**Comment by avinci** [comment]
I think the fundamental question is this. Whats the status of the repo that has multiple branches. We went with the approach that we always show the default branch and if not set, show master status. This is the best we can do as showing the last commit status of any branch as the status will mislead a whole bunch of other folks who use default branch value. 

As @cratz mentioned, there is no way to do this accurately. Our solution of commit status for default branch or master is the best we can do.

@cratz simplest way to avoid this would be to set a default branch on your source control. @manishas we should give another setting to let users pick what they want. We can do this but its lower priority given the number of other key features we have on the roadmap

Project settings
* show latest run (including PRs)
* show latest commit run
* show default branch status
* show a particular branch status

This should resolve this issue

**Comment by abhijitkini** [comment]
Happy to announce that you can now specify the branches & the run types (commit only or commit/pull requests) to be displayed on the Subscription & Landing (Home) pages. Read about it in [our documentation](http://docs.shippable.com/ci_projects/#dashboard-settings).

**Comment by abhijitkini** [comment]
Feedback/questions, let us know. Closing the issue.

**Comment by cratz** [comment]
Awesome works like charm even branches without a build are not displayed anymore when they are selected in dashboard settings.
Thank you for this!!!
