### ISSUE TITLE
build_ci needs a duration for each step

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2424]
Each step in build_ci needs a duration so we can see where the time is being taken without having to add our own timing...

**Comment by avinci** [comment]
We already have this data and should be relatively simple to add. Just need to find someone to do it :-)

**Comment by ankul-shippable** [comment]
@chriskinsman We have added this feature. You should be able to see the duration for each step for old as well as new builds. Thanks.

**Comment by chriskinsman** [comment]
Thanks Guys!
