### ISSUE TITLE
No shippable user for mysql

### ISSUE THREAD

**Issue by allenwei** [Shippable/support#2426]
according the the document

> MySQL binds to 127.0.0.1 by default. Default username is shippable with no password
  Create a DB as part of the ci section before you use it

http://docs.shippable.com/ci_configure/

but there is no shippable user at all 

```
mysql -e 'SELECT User, HOST FROM mysql.user;'
User	HOST
root	127.0.0.1
root	::1
	dfc2eabdf236
root	dfc2eabdf236
	localhost
root	localhost
```

The default ruby image is 
```
sudo docker pull drydock/u14ruball:prod
prod: Pulling from drydock/u14ruball
Digest: sha256:35ca4c3e804b31ef82c09d0bea6c4b3cc8e07afb0cf0b1a6b70515c881932785
Status: Image is up to date for drydock/u14ruball:prod

```

**Comment by manishas** [comment]
Sorry about this, we will update the docs asap.

The new images, including ``` drydock/u14ruball:prod```, do not have a ```shippable``` user in the MySQL database.  Creating a ```shippable``` user when creating the database will solve this problem, as would using the default ```root``` database user.   To create a user with the same privileges as the previous ```shippable``` user add ```mysql -e "GRANT ALL ON *.* TO shippable@localhost IDENTIFIED BY ''; FLUSH PRIVILEGES;"``` to the yml when creating the database.

Let me know if that works.

**Comment by allenwei** [comment]
Thanks for quick response, I'm using `root` user right now.

**Comment by manishas** [comment]
@allenwei thanks for the update!

Docs have been updated - http://docs.shippable.com/ci_configure/#mysql

Closing this issue.
