### ISSUE TITLE
API: How can I get started builds or complete builds but not cancelled builds?

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2428]
I'm using `/subscriptions/:id/runStatus?status=complete,incomplete` as advised in #2339 to get started and finished builds but this also returns cancelled builds. Is there some way to avoid the cancelled builds?

More generally, is it possible to document the actual statuses?

Thanks

**Comment by rageshkrishna** [comment]
@pquentin Here are all the states:

````
// Incomplete states:
waiting
queued
processing

// Complete states:
success
skipped
unstable
timeout
canceled
failed
````

I hope this helps. We'll get this added to our documentation soon.

**Comment by pquentin** [comment]
Thanks! Please mention the meaning of those statuses in the documentation: I don't know what skipped and unstable mean.

**Comment by rageshkrishna** [comment]
@pquentin "Unstable" is for when a job ends successfully (meaning it returned an exit code of 0), but there are one or more failed tests.

If any job in a matrix run fails, the run will be marked as failed.

If at least one job in a matrix is unstable and all the other jobs are successful, the run will be marked as unstable.

I hope this clarifies things. Let me know if you have any more questions.

**Comment by pquentin** [comment]
Great, thank you. Leaving open for the documentation update.

**Comment by manishas** [comment]
@abhijitkini this is another docs issue we need to address.

**Comment by abhijitkini** [comment]
The documentation has been updated to indicate the build status details. 
http://docs.shippable.com/ci_builds/#build-status
