### ISSUE TITLE
Question about SSH deployment

### ISSUE THREAD

**Issue by adamalesandro** [Shippable/support#2431]
Hi shippable,

I am trying to hook up an automated deployment using ssh and I am running into a strange issue.  According to [this post](http://blog.shippable.com/demystifying-shippables-deployment-keys), my deployment keys should be located in the `~/.ssh` directory with a name of id_rsa.

I added a `ls` command in the `after_success` so I could see whats in the folder:
```bash
$ ls ~/.ssh
    config
    known_hosts
``` 

and when it gets to the point where its supposed to connect, unsurprisingly, I get:
```bash
IOError: [Errno 2] No such file or directory: '/home/shippable/.ssh/id_rsa'
```

Am I missing a step?

**Comment by a-murphy** [comment]
That post is a little outdated.  The SSH keys have been moved to ```/tmp/ssh``` and renamed ```00_sub``` (subscription) and ```01_deploy``` (project).  However, you might not need to use the SSH key file directly in your shippable.yml file now.  It should already be set up to use the subscription SSH key (see https://github.com/Shippable/support/issues/2375#issuecomment-196117852 for an explanation of that).

**Comment by adamalesandro** [comment]
@a-murphy thanks!

**Comment by bittner** [comment]
1. Would you please be so kind to add a note on top of [that blog post](http://blog.shippable.com/demystifying-shippables-deployment-keys) directing users where to find up-to-date documentation?
1. Please update the documentation on SSH keys and deployment. I need to connect to a custom host via SSH and there is no related documentation on how to figure out the public key I have to add to my `authorized_keys` for Shippable. (This used to be easier in the past, btw. There was an option in the UI of the builds.)

**Comment by bittner** [comment]
No way to make this work with Shippable documentation and the Integrations > Key option.

However, I managed to **print out the public keys** the following way: (They of course work for SSH access to custom servers.)
``` bash
script:
  # show fingerprints (as listed on https://github.com/<user>/<repo>/settings/keys)
  - ssh-add -l
  # show public keys for private keys used for cloning the repo
  - for FILE in `ls /tmp/ssh/*`; do echo "Public key for $FILE"; ssh-keygen -y -f $FILE; done
```
You should consider adding an option to show the available public keys in the user interface of Shippable projects (e.g. in the project settings) again. This used to be very convenient and intuitive.

**Comment by avinci** [comment]
@bittner you are right. this should be much more easily available. We are doing a How to Series and we will update this very soon. Thanks for the feedback.
