### ISSUE TITLE
Ability to keep a node alive between certain hours

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2432]
We currently pay for 8 minions/nodes.

First folks in the morning pay the wait time for nodes spinning up.  Then if we have a long meeting or lunch we have to wait for things to spin up again.

Sure would be nice if say between the hours of 7 and 4 it wouldn't shut all nodes down but would leave at least one spun up.

Alternatively if you had a pool of nodes that was pre-spun up and used to satisfy provisioning requests, thus shortening the provisioning time so it becomes a non-issue.

I guess I could perversely create this by running a build every 50 minutes but that really defeats the purpose of what you are doing...

**Comment by manishas** [comment]
We will find ways to improve provisioning time over the next few weeks. This is always going to WIP which balances between impact to build times vs cost of operations vs pricing per node and might result in additional plan tiers. 

You can use dedicated hosts if you want your hosts to stay up all the time. However we currently do not support a hybrid of dedicated hosts and shippable hosts, so you'd then have to provision 8 custom nodes for your builds.

**Comment by chriskinsman** [comment]
Yep.  Thats tough. Hybrid would be nice.  To be able to run one build node of my own all the time and then use your auto creating nodes to scale up...
