### ISSUE TITLE
Error on get cache from aws

### ISSUE THREAD

**Issue by Nightw0rk** [Shippable/support#2433]
after enable `cache:true` on shippable.yml get error on boot_container step:

>  aws s3api get-object --bucket 54ffc3ec5ab6cc135297a75f --key cache/5694d6a11895ca4474680ee0.tar.gz /home/shippable/cache/5694d6a11895ca4474680ee0.tar.gz
> 
> A client error (AccessDenied) occurred when calling the GetObject operation: Access Denied
> 
>   echo 'Failed to pull cache from S3 bucket, proceeding without cache'
> Failed to pull cache from S3 bucket, proceeding without cache

on previous build on cache step get message

> tar -czf /home/shippable/cache/5694d6a11895ca4474680ee0.tar.gz /root/src/bitbucket.org/nightw0rk/ksu_server_node/node_modules
> tar: Removing leading `/' from member names

**Comment by kanthchandra** [comment]
Hi @Nightw0rk , we noticed that your builds 1-12 failed for various reasons, no cache was pushed for those builds. Build 13 did not find anything in the cache and hence you see that message. It is an expected message when no cache exists. Cache was successfully pushed at end of build 13 and so build 14 onwards should be able to use the cache. Can you please try running the build again and let us know if it doesn't work?

**Comment by manishas** [comment]
Closing this issue. Please let us know if you have any questions.
