### ISSUE TITLE
Commit as Part of Build Preventing Endless loop of builds

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2434]
I am building a nodejs package.

As part of the build I want to increment the version in package.json, commit the change and push it to the repository.

By doing this I however trigger another build, which then increments the version, etc.

Is there any way to prevent the commit during the build from triggering another build?

An alternative would be to version it based on the build number environment variable in shippable.  Exploring that option now...

**Comment by a-murphy** [comment]
If ```[skip ci]``` or ```[ci skip]```is in the commit message, a build will not be triggered for the commit webhook.  However, for pull request webhooks we check the pull request title instead (it's what we get from GitHub), so it is possible that builds will still be triggered for any pull requests updated by the commit.

**Comment by chriskinsman** [comment]
Seems dangerous.  I think I am going the route of not doing a commit during build...
