### ISSUE TITLE
Documentation search only works from http://docs.shippable.com/

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2435]
When searching for "Shippable" from the /api page, I get redirected to http://docs.shippable.com/api/search.html?q=Shippable but I don't get any results.

**Comment by manishas** [comment]
@xdothackerx we need to fix this asap

**Comment by xdothackerx** [comment]
Hello @pquentin! Sorry for the issue you're having. Do you mind giving me a hand reproducing the problem so I can find out what's wrong? I'd like to know what browser and OS you're viewing http://docs.shippable.com/api/ from, if you don't mind.

**Comment by xdothackerx** [comment]
@pquentin I have an idea of what you might be talking about - by any chance, do results appear while you are typing in the search bar, but disappear when you press enter?

**Comment by pquentin** [comment]
@xdothackerx exactly! I'm using Firefox on OS X.

**Comment by xdothackerx** [comment]
Bug should now be fixed!

**Comment by pquentin** [comment]
Thank you.
