### ISSUE TITLE
[Question] Does migration to the new format reset deployment keys?

### ISSUE THREAD

**Issue by czardoz** [Shippable/support#2436]
Do the keys that shippable generates for our projects change?

**Comment by rageshkrishna** [comment]
@czardoz No, they should not have changed. However, we do store them at a different location in the build container now. Please let me know exactly what you're running in to and I might be able to help you sort it out. Thanks!

**Comment by czardoz** [comment]
Oh, we have not actually migrated yet. Here's the relevant part of my shippable config, 

```

**Comment by rageshkrishna** [comment]
@czardoz Your YML does not seem to have been pasted correctly. Please try it again, or you can email me at ragesh@shippable.com if you need help with something. Thanks.

**Comment by czardoz** [comment]
No worries, things working just fine. Thanks!
