### ISSUE TITLE
My builds started to fail today

### ISSUE THREAD

**Issue by kepkin** [Shippable/support#2437]
My project https://app.shippable.com/projects/56411a971895ca4474230e43 started to fail.

It seems you have changed post docker build to pre-ci build. But I can't change it back in settings.

**Comment by rageshkrishna** [comment]
Hi @kepkin. Your subscription has been migrated to the new build system. I'm looking in to why your docker build is happening at the wrong step.

**Comment by rageshkrishna** [comment]
@kepkin Can you please try triggering a new build on your project now?

**Comment by kepkin** [comment]
@rageshkrishna still fails but with a different error now. Looks like some python package are missing now.

**Comment by kepkin** [comment]
Where can I read about new build system? What have changed?

**Comment by rageshkrishna** [comment]
Our documentation has been updated to describe the new system. Please take a look at https://docs.shippable.com for the details. I'll get back to you soon on the error you're seeing.

**Comment by rageshkrishna** [comment]
@kepkin I've located the bug that's causing this issue. The virtualenv directory is being set incorrectly for builds running on shippable/minv2, which is why it's complaining about missing packages. I'll have a fix deployed for this soon.

**Comment by rageshkrishna** [comment]
The fix for this issue is being tested in beta right now and will make it to production in the next deployment.

**Comment by kanthchandra** [comment]
Hi @kepkin, this has been fixed and deployed to production. Can you please let us know if this works for you. thanks.

**Comment by kepkin** [comment]
Now it fails on building docker image cause can't find file `buildoutput/requirements.txt`

Do you have some kind of changelog? I don't want to go through all https://docs.shippable.com again to understand what have changed. Also, https://docs.shippable.com is not working at all

**Comment by a-murphy** [comment]
The ```post_ci``` step is run in the build container, so a Dockerfile used to build an image there can use any of the files in the container at that time.  We are not requiring the files that you want to use to be moved into a ```buildoutput``` folder in the new build system, and it sounds like there is no ```buildoutput/requirements.txt``` in your container.  It's quite likely that the file you are looking for is in ```shippable/buildoutput``` if the Dockerfile was written for the old build system.
