### ISSUE TITLE
Paused project unpause on next webhook

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2438]
It doesn't appear it is possible to pause a project.

As soon as the next webhook comes in it unpauses itself...

**Comment by a-murphy** [comment]
So, the project appears to have been unpaused as a result of a bug in account synchronization, which is done automatically to keep the list of projects that the account has access to up-to-date (but shouldn't be setting if the projects are paused or not).  This has been corrected in Beta and we'll let you know when it is deployed to production.

**Comment by a-murphy** [comment]
It's been deployed to production, so projects shouldn't unpause themselves now.
