### ISSUE TITLE
Documentation should make clear all supported ENV variables

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#2439]
There are a number of very useful variables set in the ENV, but the documentation only discusses a few. This makes me reluctant to rely on the others. 

Please update the documentation to describe each variable that is 'supported', and specify that other variables may be added or removed without warning.  Perhaps prefixing the unsupported variables would help:

Current list:
==================
NVM_RC_VERSION=
is_success=false
SHIPPABLE_BUILD_NUMBER=71
BUILD_URL=
SSH_AGENT_PID=100
HOSTNAME=
HAS_JOSH_K_SEAL_OF_APPROVAL=true
SHIPPABLE=true
RUN_MODE=production
NVM_PATH=/root/.nvm/versions/node/v5.6.0/lib/node
TRAVIS_COMMIT=
CACHE_DIR=false
BASE_BRANCH=
TRAVIS_OS_NAME=linux
SHIPPABLE_NODE_VERSION=5.6
OLDPWD=/root
SHIPPABLE_CONTAINER_NAME=
SHIPPABLE_DATA_DIR=/root/data
SHIPPABLE_BUILD_DIR=
LC_ALL=en_US.UTF-8
BRANCH=master
NVM_DIR=/root/.nvm
SHIPPABLE_SUBMODULE_ENABLED=true
SUBSCRIPTION_ID=
SHIPPABLE_JOB_NUMBER=1
SSH_AUTH_SOCK=
SHIPPABLE_BUNDLER_ARGS=
JOB_NUMBER=1
TRAVIS=true
PULL_REQUEST_BASE_BRANCH=
TRAVIS_REPO_SLUG=
HAS_ANTARES_THREE_LITTLE_FRONZIES_BADGE=true
TRAVIS_PULL_REQUEST=false
RACK_ENV=test
REPO_FULL_NAME=
SHIPPABLE_OS_NAME=linux
SHIPPABLE_REPO_DIR=
PATH=/root/.nvm/versions/node/v5.6.0/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/usr/local/bin
SHIPPABLE_API_URL=https://api.shippable.com
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
PROJECT_ID=
SHIPPABLE_IS_OFFICIAL_IMAGE=true
PWD=
REGISTRY_ACCESS_KEY=
CONTINUOUS_INTEGRATION=true
SCRIPT_CATEGORY=build
LANG=en_US.UTF-8
SHIPPABLE_ARTIFACTS_DIR=/shippableci
REPO_NAME=
MERB_ENV=test
REGISTRY_ACCOUNT_ID=
SHIPPABLE_COMMIT_RANGE=
REGISTRY_SECRET_KEY=
shippable_group_name=
SHIPPABLE_REPO_SLUG=
TRAVIS_NODE_VERSION=5.6
HEAD_BRANCH=
TRAVIS_JOB_NUMBER=1
SHLVL=3
HOME=/root
COMMIT=
RAILS_ENV=test
CI=true
TRAVIS_BUILD_ID=
JOB_ID=
IS_PULL_REQUEST=false
REGISTRY_REGION=us-east-1
LC_CTYPE=en_US.UTF-8
REPOSITORY_URL=
ARCHIVE_DIR=/tmp/shippable
DEBIAN_FRONTEND=noninteractive
NVM_BIN=/root/.nvm/versions/node/v5.6.0/bin
NVM_IOJS_ORG_MIRROR=https://iojs.org/dist
BUILD_NUMBER=
ORG_NAME=formhero
SHIPPABLE_BUILD_ID
GIT_ASKPASS=echo
TRAVIS_BRANCH=master
SHIPPABLE_JOB_ID=1
PULL_REQUEST=false
COMPARE_URL
TRAVIS_COMMIT_RANGE
SHIPPABLE_IS_LEGACY_IMAGE=false
SHIPPABLE_API_RETRY_INTERVAL=3
TRAVIS_JOB_ID=1
CACHE_CONTAINER=false
TRAVIS_BUILD_NUMBER=71
TRAVIS_BUILD_DIRr
_=/usr/bin/env

**Comment by manishas** [comment]
@abhijitkinican you take care of this?

**Comment by abhijitkini** [comment]
Documentation has been updated at http://docs.shippable.com/ci_configure/#standard-variables. 
Closing issue as resolved.

**Comment by ryan-kimber** [comment]
Great job! Thank you for this.

**Comment by ryan-kimber** [comment]
This is awesome to see and wasn't clear to me before (if I missed it somewhere else, fair enough);

> Custom Variables
> 
> You can also set your own environment variables in the yml. Each statement under the env tag will trigger a separate build with that env variable, so specifying multiple environment variables will give you a build matrix for every commit.

**Comment by manishas** [comment]
:+1:
