### ISSUE TITLE
Keep get alert and abort: shippable Integration with docker registry

### ISSUE THREAD

**Issue by JohnnyNiu** [Shippable/support#2440]
I am new to shippable, When I follow the instruction to deploy my image to my docker registry, I keep getting alert as follow:

![](http://i.stack.imgur.com/mnd71.png)

Build Result in console

![](http://i.stack.imgur.com/VOA6f.png)

But I checked it all over and it's all matched:

Configuration in my account

This is my shippable.yml:

integrations:
  hub:
    - integrationName: ship-docker
      type: docker
Thank you in advance!

shippable-ci

**Comment by kanthchandra** [comment]
Hi @JohnnyNiu ,

Have you added the "ship-docker" hub integration to your project settings page? If not please go to the project settings page and add in the hub integrations drop down please select "ship-docker" and see if it solves the problem.

If it doesn't solve the problem, Can you please post the id of the project that is showing this alert?

You can get more information about configuring your CI here http://docs.shippable.com/ci_configure/

**Comment by JohnnyNiu** [comment]
thank you very much @kanthchandra, After add the setting, it is working now.
