### ISSUE TITLE
[pipeline] Error while adding a new image (Cell Manifest) using GCR integration

### ISSUE THREAD

**Issue by mikaelh** [Shippable/support#2441]
When adding a new image using GCR integration, it always seem to give this error: "The image sync failed, most likely due to invalid account integration, invalid image name, or connection issues"

The GCR integration works fine in the CI-environment and is configured with a service account in Google Cloud. 

Link: https://app.shippable.com/subscriptions/56b4962d1895ca4474736e3a/newPipeline

Tried with <project-id>/<image> as well as full path eu.gcr.io/<project>/<image> without success.

**Comment by a-murphy** [comment]
```eu.gcr.io/<Google project ID>/<image name>``` would be the correct format, but apparently we're only expecting ```gcr.io``` right now.  Thank you for letting us know.  There should be any reason we can't sync ```eu.gcr.io``` as well and we'll let you know when it's fixed.

**Comment by rageshkrishna** [comment]
@mikaelh This should be working now. Please give it a shot and let us know how it goes. Thanks!

**Comment by manishas** [comment]
Closing since this is in prod.
