### ISSUE TITLE
Shippable failed to build a release

### ISSUE THREAD

**Issue by aftabaslam** [Shippable/support#2446]
Hi, 
I am facing issue in shippable builds. We have exit 0 script section of my ymal file that should execute the on_success section of the file, however, the builds goes to failure. 
![fireshot screen capture 003 - 1eq_one_account i develop_308 - shippable - app_shippable_com_runs_56f93d4e52c78c0d00bf8f9c](https://cloud.githubusercontent.com/assets/4181429/14080006/887d552a-f51b-11e5-812c-6b538ed6a71e.png)

**Comment by manishas** [comment]
Assigning to Ragesh since he is already communicating about this issue over email. 

@aftabaslam can you try @rageshkrishna 's suggestion of using `return 0` instead of `exit 0`?

**Comment by aftabaslam** [comment]
Thank you. it works.

On Mon, Mar 28, 2016 at 9:29 PM, Manisha <notifications@github.com> wrote:

> Assigning to Ragesh since he is already communicating about this issue
> over email.
>
> @aftabaslam <https://github.com/aftabaslam> can you try @rageshkrishna
> <https://github.com/rageshkrishna> 's suggestion of using return 0
> instead of exit 0?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Shippable/support/issues/2446#issuecomment-202473285>
>



-- 
Regards,

Aftab Aslam | Sr. Associate Software Engineer | Zigron Inc.
E-mail: aftab.aslam@zigron.com
Website: www.zigron.com

**Comment by rageshkrishna** [comment]
@aftabaslam Thanks for the update!
