### ISSUE TITLE
(Id: 4006) postRun failed for projectId 404

### ISSUE THREAD

**Issue by madshostrup** [Shippable/support#2448]
We are not able to rebuild our project and we havn't changed any settings. Any ideas why this is not working?

https://app.shippable.com/builds/56e2decaf802950b0033edc2

**Comment by rageshkrishna** [comment]
@madshostrup Your subscription was upgraded to the new build platform sometime in the past couple of weeks. Unfortunately, the new build system cannot rebuild anything that was originally run on the old build system. I hope this helps.

Please let us know if you are seeing this issue for anything that was run after the 16th of March.

**Comment by madshostrup** [comment]
Just tested with a new branch and PR and it is building. But we don't see the indicator beside the commits in Github?

**Comment by kanthchandra** [comment]
@madshostrup I just tested out the following scenario on a github PR.

1. Enabled the project shippable/test on github
2. Forked shippable/test into my account (kanthchandra/test)
3. Opened a PR from kanthchandra/test to shippable/test 
4. The PR triggered a Build on Shippable and the commit status on the github PR page got updated to processing.
5. After the build got completed, the commit status on the github PR page got updated to success.
6. I reran the PR build and observed that the commit status was again updated to processing. 

So this is expected flow and it seemed to work me or am I missing something here?

can you please elaborate your use case and also please post the projectId which is causing this problem. I will take a look at this.

**Comment by madshostrup** [comment]
Our (not expected) scenario on project with id 5506810c5ab6cc13529b84bd

1. Had a working repo working with Shippable running RSpec and Rubocop
2. Commits are suddenly not being build without any changes from our side
3. Contacted support and found out we've been moved to the new build platform
4. Made a new branch and PR and now it's building but we don't see commit status

**Comment by kanthchandra** [comment]
Thanks for letting us know about this. I'll investigate this and get back to you once I have more data on this project.

**Comment by kanthchandra** [comment]
@madshostrup can you please try this now and let us know if it works?

**Comment by madshostrup** [comment]
Works again
