### ISSUE TITLE
Problems with aws_eb_docker_deploy

### ISSUE THREAD

**Issue by Paviel** [Shippable/support#2449]
We've been having problems with the CI process since March 25. Some of them were resolved by modifying configuration in shippable.xml. Currently the issue is upload_artifacts fails if the application name contains a whitespace. Do we need to escape those (how?) or can't they be used altogether?

**Comment by avinci** [comment]
Have you tried putting the application name inside `""` double quotes?

**Comment by Paviel** [comment]
Do you mean the name string itself needs to contain " characters?

**Comment by avinci** [comment]
yes

**Comment by Paviel** [comment]
No, the error is only a little different. The path to s3://elasticbeanstalk-... is constructed in a wrong way. When the app name contains whitespaces they break the url as if there's several consequent parameters. Now only the part of the url before the first whitespace is used and create_application_version fails with "A client error (InvalidParameterValue) occurred when calling the CreateApplicationVersion operation: No Application named 'Air' found."

**Comment by avinci** [comment]
Ok, let me get someone internally to test this out end to end. I think we are not encoding s3 url. Will get back to you in a couple of days with a fix.

**Comment by avinci** [comment]
@manishas can we get someone to pick this up. I think we need to do proper encoding of string, especially urls.

**Comment by manishas** [comment]
The fix should be available now. @Paviel can you try again and confirm that it works as expected?

**Comment by Paviel** [comment]
@manishas thanks, that issue is no more, although I have noticed that S3Key and VersionLabel values are constructed now differently than before. We're still having deployment problems because of that.

**Comment by manishas** [comment]
Can you open a new issue for that and we'll take a look asap.
