### ISSUE TITLE
set timeout to a build

### ISSUE THREAD

**Issue by mdespriee** [Shippable/support#2450]
One of my build is stuck since 40mn+ (analysis on going...).
It's blocking the build queue.

I would like to customize the timeout (in the yaml) to make sure it won't block that much if it happens again. Possible ?

**Comment by avinci** [comment]
@mdespriee this is already being worked upon where we can set this at a project level. Should be there by early next week. For now, you can cancel the build and the rest will get picked up...

**Comment by avinci** [comment]
@kanthchandra can you please comment on this. It seems like this is already in production.

**Comment by kanthchandra** [comment]
@mdespriee You can now go to your project settings page and set the custom timeout. You will need to set the custom timeout in minutes. The maximum that we support at the moment is around 90. 

Any job in processing state for more than the number of minutes you have mentioned will timeout.

**Comment by mdespriee** [comment]
Great !
Thanks
