### ISSUE TITLE
Postgres instructions don't work

### ISSUE THREAD

**Issue by diwu1989** [Shippable/support#2452]
the instructions here
http://docs.shippable.com/ci_configure/
don't seem to work, i get this error
![image](https://cloud.githubusercontent.com/assets/380950/14126939/3b2f0468-f5c9-11e5-978f-4a21d529b8c8.png)

can you update the docs?

**Comment by a-murphy** [comment]
The command should have been ```psql -c 'create role shippable with superuser;' -U postgres```.

**Comment by diwu1989** [comment]
great, i hope they update the official docs

**Comment by manishas** [comment]
This has been updated in docs - 

http://docs.shippable.com/ci_configure/#postgres
