### ISSUE TITLE
Security flaw?

### ISSUE THREAD

**Issue by menny** [Shippable/support#2453]
Consider the following case:

Given:
1. My shippable script also does deploy and signing using secret (secure) environment variables
2. My shippable script only deploy and sign if the build is in the _master_ branch.

PRs:
1. When a PR is submitted to my repo (but before merging), shippable will build the PR.
2. Of course, since the script also checks for the branch, it will not deploy or sign the source in the PR.

The (possible) flaw:
A user that wants to deploy a malicious code, or read my secret (secure) environment variables can do the following:
1. Change the shippable script in the PR, so it would print out the secret (secure) variables using `echo` call, or
2. deploy the malicious code by removing the guarded (condition) deploy script that checks for the branch value, and instead deploy from any branch.

**Comment by rageshkrishna** [comment]
@menny We do not decrypt any secure env variables for PR builds on public projects. They are made available for commit builds, which can only be done by collaborators on the project and not by any random github or bitbucket user.

For private projects, we decrypt secure env variables for both PR and commit builds. The reasoning behind this is that only collaborators can actually send PRs on private projects.

I hope this clarifies the scenario. Please let me know if you still have any concerns around this. Feel free to email me at ragesh@shippable.com if you'd like to continue this discussion privately. Thanks!

**Comment by manishas** [comment]
Closing this since there is nothing actionable to be done here.

**Comment by menny** [comment]
Thanks!

Two questions:
1) Can you point me to the documents that describes this behavior?
2) When creating a PR, two jobs are created:
<img width="791" alt="screen shot 2016-03-30 at 12 10 53 pm" src="https://cloud.githubusercontent.com/assets/481272/14149088/7a4ee5da-f670-11e5-9100-d9fa9e0150ee.png">
Why is that?

**Comment by a-murphy** [comment]
1)  There is a note [here](http://docs.shippable.com/ci_configure/#multiple-variables-per-build) in the documentation.
2)  One of the builds is for the commit, and the other for the pull request.  In your screenshot, 376 is for the commit on pre-post-merge.  Then, 377 is for the pull request opened, which is the master branch with the changes in the pull request added.  It's possible to get different results from the two builds if pre-post-merge isn't up-to-date and doesn't have some of the commits in master (the commit build won't have those, but the pull request build will).
