### ISSUE TITLE
Use both node & ruby

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#2457]
Hi,

Trying to migrate to new format & run scripts which rely on having both node and ruby.

Based on docs & a [previous reply](https://github.com/Shippable/support/issues/1896#issuecomment-157073751) this should now be available, so I'm trying `u14nod` as I'm assuming it has ruby from `u14`, however:

```
ruby --version
/root/3ba6d229-469b-4eec-b105-52ce40a63eb2.sh: line 58: ruby: command not found
```

How do I do this please?

Thanks

**Comment by manishas** [comment]
We'll look into this. We do install default version of Ruby in our node images, so not sure what's going on as of yet.

**Comment by stephanielingwood** [comment]
Hi, @tomsterritt. Thanks for the question.

I looked at our images, and rvm is installed in our u14 image (and therefore the u14nod images) by default. However, it's installed in /usr/local - which means it's not in PATH.

To use ruby or rvm, then, you'll need to add 
`source /usr/local/rvm/scripts/rvm`
to your yml. It'll look something like this:
```
build:
  ci:
    - source /usr/local/rvm/scripts/rvm
    - ruby --version
```

FWIW, I just tested this in a build, so you can see what's currently being installed, and where:
![rubyimage](https://cloud.githubusercontent.com/assets/7757711/14152965/9dfa7716-f66a-11e5-92da-f8c10c6c3e19.png)

Hope this helps! Let us know if you have any other questions.

**Comment by manishas** [comment]
@stephanielingwood can you add an FAQ item about this to our docs?

**Comment by stephanielingwood** [comment]
@tomsterritt Added this section to our docs, in case you need it for future reference: http://docs.shippable.com/ci_faq/#how-do-i-use-ruby-in-a-build-with-another-language
Enjoy!

**Comment by manishas** [comment]
Closing this issue.
