### ISSUE TITLE
Cannot see build details

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#2458]
This is what I'm seeing on UI

<img width="905" alt="screen shot 2016-03-30 at 8 12 03 pm" src="https://cloud.githubusercontent.com/assets/1146297/14146020/c30aa12c-f6b3-11e5-9cb4-7628bec72b6a.png">

**Comment by phagunbaya** [comment]
Now it's redirecting me to login page and after login I'm seeing below screen.
<img width="1079" alt="screen shot 2016-03-30 at 8 14 12 pm" src="https://cloud.githubusercontent.com/assets/1146297/14146087/097c0d80-f6b4-11e5-94be-611163ad70a1.png">

**Comment by legendik** [comment]
We have exactly same problem.

**Comment by manishas** [comment]
Looking into this

**Comment by manishas** [comment]
This should now be resolved. Please let us know if it works.

**Comment by legendik** [comment]
It works, thank you!
