### ISSUE TITLE
Custom label / branch in build badge

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2461]
It would be nice if one could influence the label of the [Shippable build status badge](http://docs.shippable.com/ci_projects/#build-status-badges).

Right now it always shows `run | shippable`, it would be useful to include e.g. the specific branch to have `master | shippable`, `staging | shippable` and `production | shippable`.

**Comment by mgeisler** [comment]
Yes, I would like to see this feature too: I don't think anybody know what "run | shippable" means, but "build | passed" is understood universally.

**Comment by manishas** [comment]
Good suggestions. I've put this on our backlog and will let you know when there's an update.

**Comment by mbrodala** [comment]
This has been fixed for me through the shields.io API change.

**Comment by abhijitkini** [comment]
You can now customize your build badge status on Shippable using shield.io. Read more about it on [our blog](http://blog.shippable.com/customizing-build-badges-for-a-nodejs-project-status).
