### ISSUE TITLE
All Builds Down due to AWS us-east-1 auto scale / ec2 runinstance issues

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2465]
I show 4 nodes but none show green in the settings screen.

4 builds are stuck with the longest stuck for > 41 minutes

@manishas @avinci  any ideas?

**Comment by trriplejay** [comment]
This appears to be related to an AWS issue with launching new instances:
![image](https://cloud.githubusercontent.com/assets/6869398/14162559/b8becde0-f6a1-11e5-97ae-a5b1c8e88b32.png)

**Comment by chriskinsman** [comment]
Been dead since 5:06 or so for me.  Some of the instances have now shut down and builds are just stuck

Should I kill them or will they restart once nodes become available?

Might want to update your status if this is what you believe the issue to be...

**Comment by trriplejay** [comment]
The builds should get picked up once these issues are resolved. Here's the latest AWS status:
![image](https://cloud.githubusercontent.com/assets/6869398/14162992/d614b702-f6a5-11e5-8e47-2d6768daab61.png)

**Comment by chriskinsman** [comment]
Thanks for the update.

**Comment by chriskinsman** [comment]
Well I learned builds will timeout after two hours.  Have 8 nodes spun up all red for now...

**Comment by chriskinsman** [comment]
7 stuck minions that have been up for ~ 5 hours now 3.5-4 hours now with no builds.

Pushed a new build and had an 8th spin up and start building. 

No idea how to clear the other 7 stuck ones...

**Comment by manishas** [comment]
@rageshkrishna can you clean up the stuck minions?

**Comment by chriskinsman** [comment]
Even with the stuck minions I am getting new ones spinning up.  Going to leave open till morning but builds are starting to slowly move through...

**Comment by trriplejay** [comment]
looks like AWS is back to normal.  We just need to clean up a few minions that were left in a bad state.

**Comment by rageshkrishna** [comment]
All the stale nodes should be gone now. I'm going to close this issue. Please re-open if the problem persists.
