### ISSUE TITLE
Build stuck after Browserstack tests

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#2469]
Hi,

We're running some tests via browserstack and where it would previously continue after the tests completed it's now stuck just showing the results, not continuing to the next step in our script.

e.g. 56fd237fd1f1f60c002f5735

How can we get it to continue?

Thanks

**Comment by rageshkrishna** [comment]
@tomsterritt Sorry about the delay in getting back to you. Do you mind if I trigger builds on your project to debug this? Thanks!

**Comment by tomsterritt** [comment]
@rageshkrishna of course not, go ahead :smile:

**Comment by rageshkrishna** [comment]
It looks like BrowserStackLocal isn't terminating for some reason, but I'm not really sure why. I'm going to try and reproduce this with one of my own projects so I can debug further.

I'll keep this issue updated as I make progress.

**Comment by rageshkrishna** [comment]
@tomsterritt Can you tell me a little bit about how your tests are structured and how you use BrowserStack? I'm new to BrowserStack and there are a bunch of different ways I can start using it. I want to make sure I set things up so they match your configuration.

You can email me at ragesh@shippable.com if you'd rather not discuss the details here. Thanks!

**Comment by rageshkrishna** [comment]
@tomsterritt Thanks once again for your email. I was able to reproduce the scenario on my dev box. This definitely appears to be a problem with [theintern](https://github.com/theintern) or one of its components. I did nothing special to repro the problem -- I simply followed the [official tutorial](https://github.com/theintern/intern-tutorial) to the letter and the runner just sits there after it completes the tests. I have to hit Ctrl+C to make it stop.

As I was able to repro the problem on my dev box, it does not appear to be an issue that's isolated to the Shippable build environment. I wish I had some ideas on how this could be fixed, but at the moment I don't know enough about theintern to make any suggestions.

**Comment by tomsterritt** [comment]
@rageshkrishna thanks for investigating this. I've just run another build using a version of intern I know to work on my Mac but it's still stuck, so I'm thinking it could be down to a specific platform? Is there anything obviously similar between your dev box and the Shippable build environment? If you wouldn't mind giving me some details about those I will go over and create an issue with them.

Thanks

**Comment by rageshkrishna** [comment]
The only obvious peculiarity is that they are both headless machines (yes, I do all my development in vim on a remote machine). Having said that, I don't know if that in itself is a contributing factor because, if I'm not mistaken, your tests were running successfully on Shippable earlier.

Besides that, they're pretty standard Ubuntu 14.04 machines. I can't really think of anything else that's unusual about these two environments.

**Comment by tomsterritt** [comment]
Thanks for your help - going to close this and take it to Intern/Browserstack.
