### ISSUE TITLE
Cache not working, flag set to true

### ISSUE THREAD

**Issue by naveensky** [Shippable/support#2471]
Hi,

Though I  have cache flag set to true in my shippable files, I suspect cache is not happening correctly. All my builds are taking same time as uncached build. 

For eg https://app.shippable.com/runs/56fe10e31f6f0d0c00bebd74 took about 31 minute just to download all binaries and compile. All binaries ideally should be cached for each next run.

**Comment by rageshkrishna** [comment]
Hi @naveensky. I don't know _anything_ about scala so you'll need to help me understand this a little bit...

1. Where are all of these dependencies downloaded and stored in the filesystem? Are they kept somewhere relative to the current directory, or do they go somewhere else?
1. I see the command `activator clean dist`. Is it possible that the `clean` is deleting something that it shouldn't?

By default, if you just say `cache: true`, we cache only the contents of $SHIPPABLE_BUILD_DIR. If you need other directories to be cached, you need to include the `cache_dir_list` tag to your YML. The details are [here](http://docs.shippable.com/ci_configure/#caching).

**Comment by naveensky** [comment]
@rageshkrishna the default cache directory for scala projects is <home directory of user>/.ivy2

Do I need to include this directory separately in shippable file? If yes, what is path to home directory

**Comment by rageshkrishna** [comment]
You should add `$HOME/.ivy2` to your `cache_dir_list` in the YML file.
