### ISSUE TITLE
Issues with create_application_version

### ISSUE THREAD

**Issue by Paviel** [Shippable/support#2472]
We're having problems with deploying our application to AWS EB Docker. The reason is starting this week some values have been constructed differently.

One of them is ApplicationVersion.S3Key; before is was like `shippable.<company>.<appname lowercase w/o whitespace>.<branch>.<build no>.sourcebundle.zip`, now it's `<full appname>/<name of environment_name>/Dockerrun.aws.json.shippable.<full appname>.<branch>.<build no>`. 

The other is ApplicationVersion.VersionLabel; before like `shippable.<company>.<appname lowercase w/o whitespace>.<branch>.<build no>`, now `shippable.<name of environment_name>.<branch>.<build no>`.

The build on Shippable contains no errors but the deployment doesn't happen. Thanks in advance.

**Comment by avinci** [comment]
@harryi3t can you comment?

**Comment by harryi3t** [comment]
@Paviel can you share some more details if your project is open source.
I would like to see your yml file.

If you can't share it here, feel free to [mail me][harry]

Also for reference your can look our [official sample application for EB Docker Deployment][1]

Also the shippable run for this is passing [here][2]

[harry]: mailto:harendra@shippable.com
[1]:https://github.com/shippablesamples/sample_node_eb_docker/blob/master/shippable.yml
[2]:https://app.shippable.com/runs/56ebd5248dc7220c0090d5b4

**Comment by manishas** [comment]
@harryi3t are you following up on this offline?

**Comment by harryi3t** [comment]
@manishas I have not received any mail from @Paviel yet.
It's true that we have updated the naming convention of the files we store on `s3` but that we are handling in our code. So there should be no problem in that.
I need more information to understand what is going wrong.

**Comment by Paviel** [comment]
We have resolved the issue in out shippable.yml
