### ISSUE TITLE
NodeJS pre-installed

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2473]
Our builds reference NodeJS 4.2.2 this morning I noticed almost 40s of our build time is related to setup_ve doing an nvm install 4.2.2

Any chance of having nodejs version pre-installed in images?  Can I already do this post recent changes?  I don't see a way anymore to specify a base container that I would create from your base container so I wasn't sure.

**Comment by avinci** [comment]
Our policy on images we update the `prod` version on the last month of the quarter. We keep updating the `tip` version with all the latest versions. If you really need to be on edge, `tip` is the right way to go, but then other things that will also get updated might break your build. 

The best way to do this is take `prod` version and build a custom image and push it to docker hub. You can use that image in the `pre_ci_boot` section which will control whats on your ci image. 

As a best practice, we always separate our base image build and the application into separate repos that allow us to do this effectively. Happy to write a blog on this if it helps.
