### ISSUE TITLE
flag provided but not defined: --tmpfs

### ISSUE THREAD

**Issue by VaclavSir** [Shippable/support#2476]
Since docker 1.10.0, there is this flag `--tmpfs`, that mounts given directory in the container as a tmpfs. I tried to add this option to the shippable.yml and the boot_container failed:

```
flag provided but not defined: --tmpfs
See 'docker run --help'.
```

Isn't it possible, that you run some older version of Docker?

It's not a big deal, I can work this around (using `--privileged` option and then mounting the directory manually), yet still it would be cool to use current version of Docker.

**Comment by manishas** [comment]
@VaclavSir Yes, we're using an older version of Docker. We do upgrade Docker versions periodically based on business need, so we'll probably upgrade in the next few months. 

Let me know if you have any more questions or need help with the yml config.
