### ISSUE TITLE
Build stuck in provision job node after setting up own AWS EC2 node

### ISSUE THREAD

**Issue by aouyang1** [Shippable/support#2477]
Current node on AWS is showing green in shippable. I can't figure out a good way to diagnose where I'm having the problem.

**Comment by manishas** [comment]
@rageshkrishna can we look into this asap?

**Comment by rageshkrishna** [comment]
@aouyang1 The most common cause for builds not being picked up from custom hosts is usually a connectivity issue between the build runner and our message queue. I have confirmed from our queues that we have no consumers on your build queue. 

The build components need to be able to make outgoing connections to `msg.shippable.com` (port 5671) and `api.shippable.com` (port 443).

On your host you should be able to find a container with `mexec` in its name. This is our build runner. Can you please do `docker logs --tail=200` on that container and let me know what errors you see?

**Comment by aouyang1** [comment]
@rageshkrishna This did it! had to change the security groups to allow the outbound traffic on 5671 and 443. I'm not sure if I missed this in the documentation or not, but I think it'd be good to also add this is one of the prereqs when others are using their own hosts.

On a side note, I noticed that if we wanted to run more builds in parallel, it requires that we have a separate host for each parallel build. Is it typically bad practice to have multiple containers running builds on the same host? I would imagine that we'd still gain from the container isolation and a better use of resources.

Thanks again for all the help @rageshkrishna and @manishas!
