### ISSUE TITLE
Coverage Badge also reads "Run Status" in generated Mark Down

### ISSUE THREAD

**Issue by devillex** [Shippable/support#2478]
The mark down generated for the Coverage Badge under settings incorrectly refers to '`Run Status`'. This generated mark down should rather relate to coverage.

![screen shot 2016-04-04 at 1 04 08 pm](https://cloud.githubusercontent.com/assets/11049609/14246457/85c0dcde-fa67-11e5-92a9-6f7d63f3a5de.png)

**Comment by harryi3t** [comment]
Nice catch @devillex 
This is fixed now.
