### ISSUE TITLE
Commit status not updated on GitHub

### ISSUE THREAD

**Issue by mgeisler** [Shippable/support#2480]
Hi, thanks for the service! This is excellent for small open source projects :-)

I have pull requests where the commit status isn't updated on GitHub after the build finishes successfully. See this run and the corresponding pull request:

* https://app.shippable.com/runs/5702b7b777ac7a0c000fa4a9
* https://github.com/mgeisler/cram/pull/3

The commit status was updated correctly on the first pull request I made to enable Shippable:

* https://github.com/mgeisler/cram/pull/1

Am I missing something here?

**Comment by manishas** [comment]
@rageshkrishna can you ask someone to look into this asap?

**Comment by rageshkrishna** [comment]
I'm not sure why yet, but we're seeing GitHub return a 422 status code when we try to update the commit status on your project. We'll take a deeper look at this today and see what's really going on.

**Comment by mgeisler** [comment]
Thanks for looking into it!

**Comment by spsiddarthan** [comment]
@mgeisler, We have deployed a fix for this. Could you please try again and let us know the if the problem still exists?

**Comment by mgeisler** [comment]
Thanks for fixing this! I see the commit status being updated on GitHub again.
