### ISSUE TITLE
build failed for syslog driver

### ISSUE THREAD

**Issue by n0mer** [Shippable/support#2483]
https://app.shippable.com/runs/57030d9277ac7a0c001baffc
```
Provision job node
  Job node info 1s
  boot_container 0s
  wait_for_exit 0s
  sudo docker logs -f c.exec.<image>.573.1 0s  
"logs" command is supported only for "json-file" and "journald" logging drivers (got: syslog)

  setup_ve 0s
  git_sync 4s
  build_ci 1m 42s
  build_on_success 3s
  parse test reports 0s
  parse coverage reports 0s
```

Every step except 'wait_for_exit` is green, but overall build failed.

Docker installation on my host is configured to use syslog driver.

**Comment by manishas** [comment]
@n0mer We install docker on the build machines and custom docker configs on the build host is currently unsupported. Our code uses docker logs command and according to [docker docs](https://docs.docker.com/engine/admin/logging/overview/): The docker logs command is available only for the json-file and journald logging drivers.

If we hear frequent feedback around this, we will figure out a way to get around this.

**Comment by n0mer** [comment]
@manishas can you detect this in your 'bootstrap' script?
