### ISSUE TITLE
Sequence Coverage not entirely accurate

### ISSUE THREAD

**Issue by TomK** [Shippable/support#2485]
Hi, i'm using PHPUnit 4.8 to output coverage in xml.
The sequence coverage (which i have read is line coverage), is coming out too low.

Example build: https://app.shippable.com/runs/570370741644e20b002a8854

Many files here are listed as 0% where in fact there are no executable lines in those files, so they are actually 100%.  In many instances this is correct, these are interfaces.
I assume this is because the xml output has a blank percentage.

Example of `IRoute.php` coverage xml file below:

``` xml
<?xml version="1.0"?>
<phpunit xmlns="http://schema.phpunit.de/coverage/1.0">
  <file name="IRoute.php">
    <totals>
      <lines total="26" comments="15" code="11" executable="0" executed="0" percent=""/>
      <methods count="0" tested="0" percent=""/>
      <functions count="0" tested="0" percent=""/>
      <classes count="0" tested="0" percent=""/>
      <traits count="0" tested="0" percent=""/>
    </totals>
  </file>
</phpunit>
```

**Comment by TomK** [comment]
I have opened an issue on PHPUnit suggesting a change to coverage to 100%.
However, it would be nice if shippable could interpret this situation as covered since this exists in historical versions of phpunit.  Specifically where we can see `executable="0"`

**Comment by manishas** [comment]
Looks like the PHPUnit issue was fixed, so I'm assuming we don't require a change to Shippable at this point. Closing this issue.
