### ISSUE TITLE
bundle: command not found while running ruby build

### ISSUE THREAD

**Issue by mspanc** [Shippable/support#2486]
I am getting `bundle: command not found` while running ruby build

https://app.shippable.com/runs/56fd2325d1f1f60c002f4ac5

shippable.yml:

```
language: ruby
rvm:
  - 2.2.3

services:
  - postgres

before_script:
  - psql -c 'create database "radiokit-auth-test";' -U postgres

```

**Comment by chetantarale** [comment]
@mspanc You are using ruby 2.2.3 which is not preinstalled in our official images and when you using any ruby version other than the supported ones you will need to install your own packages.

For now you can install bundle by using `gem install bundler` command in your yml's `before_script` section or in `ci` section when using `new yml` format. 

Also if you are using postgres you may also need to install `libpq-dev` and `libpq5` packages as they are missing in our images.
