### ISSUE TITLE
drydock/u14nod:prod - Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

### ISSUE THREAD

**Issue by iivvoo** [Shippable/support#2487]
When using the drydock/u14nod:prod image an apt-get update/upgrade results in

```
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-updates_restricted_source_Sources.gz is not what the server reported 5217 5219
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

This happens structurally, rebuilding has no effect. Clearing cache makes no difference either.

**Comment by iivvoo** [comment]
sample (failing) build: https://app.shippable.com/runs/5703b5f9018a420c00174153

**Comment by chetantarale** [comment]
@iivvoo You will need to rebuild cache.Running the following commands before  `apt-get update`  should resolve it.
```
    - cd /var/lib/apt
    - sudo mv lists lists.old
    - sudo mkdir -p lists/partial
    - sudo apt-get update
```

**Comment by iivvoo** [comment]
Correct, this fixes it though I don't really understand how I can start my build with a broken image. Also, for future reference if anyone else runs into this make sure you restore your CWD

```
  - OLDWD=`pwd`
  - cd /var/lib/apt
  - sudo mv lists lists.old
  - sudo mkdir -p lists/partial
  - cd $OLDWD
```
