### ISSUE TITLE
NPM Error On Build

### ISSUE THREAD

**Issue by taylortdixon** [Shippable/support#2489]
Build Link: https://app.shippable.com/runs/570421f3c4ea6d0c00c76023

NPM seems to fail on all our builds. This does not happen on our teams local machines. I believe this is a shippable error.

**Comment by rageshkrishna** [comment]
@taylortdixon I noticed your build is running on shippable/minv2 image. This image is no longer supported or maintained. As the first step towards debugging this, can you please try using `drydock/u14nodall:prod` as your build image?

**Comment by abhijitkini** [comment]
@taylortdixon Please let us know if you continue to have the issue after trying out @rageshkrishna's recommendation. Closing the issue as resolved.
