### ISSUE TITLE
Unable to Add Node

### ISSUE THREAD

**Issue by SDETools** [Shippable/support#2493]
After changing our Billing info, our custom nodes disappeared from "Build Infrastructure" and I am unable to use the "Add Node" button. https://app.shippable.com/subscriptions/55f97b061895ca447415cb44 

Tried switching from "My Node" to "Shippable Node" and back, no change.

Please help resolve this.

/Torben

**Comment by kanthchandra** [comment]
@SDETools This fix for this should be available in the next couple of minutes. This was because of a bug in our frontend code which we have fixed and deployed.

**Comment by kanthchandra** [comment]
@SDETools Can you please try it now and let us know if it works? Also please hard refresh the page before trying it out.

**Comment by SDETools** [comment]
@kanthchandra It works now, thank you.
