### ISSUE TITLE
On-Premises build node stopped processing

### ISSUE THREAD

**Issue by dcramble** [Shippable/support#2495]
We setup an on-premises build node a few weeks ago, and it has been working great. However, today it seems Shippable has lost communication with our build node, or some other issue. Although, the Shippable web interface shows a green status for our node, CI builds are just sitting at the _provision job node_ stage of the build process.

We checked to make sure our node is still available from outside our firewall and it is. We also rebooted the node for good measure. Is there any way to get further details about the communication between Shippable and our node?

@oforralmesdk12orus
@tyhand

**Comment by manishas** [comment]
@dcramble we're looking into this.

@trriplejay

**Comment by trriplejay** [comment]
@dcramble Shippable runs a container on your machine that listens for builds.  Could you issue a `docker ps -a` and show us the output? there should be a running container named something like `shippable-mexec-...`

**Comment by dcramble** [comment]
```sh
# docker ps -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS               NAMES
2c5974576d72        shipimg/mexec:master.128   "/home/shippable/mexe"   2 weeks ago         Up 45 minutes                           shippable-mexec-56f1d22880a5180d00b0234f
```

**Comment by trriplejay** [comment]
@dcramble did anyone use the 'reset' button from the subscription settings tab recently?

**Comment by dcramble** [comment]
There is only three of us testing the interface right now and we didn't intentionally push it, so I think "No", but can't say 100%.

**Comment by trriplejay** [comment]
hmm, ok.  Could you do a `docker logs --tail=500 2c5974576d72` and email me the output? john@shippable.com I'll see if I can figure out why our agent can't connect.

In the meantime, the fastest way to get your builds running is probably:
1. delete your node
2. re-add your node and run the scripts again.

Sorry for the inconvenience.  We'll try and get to the bottom of this.

**Comment by dcramble** [comment]
No problem, your support has been outstanding considering we're working with the free tier at this time.

It's kind of hassle to remove and add nodes for us, because of the security restrictions we have - based on our GitHub team configuration. We'll wait it out for a couple of days and then see if we do need to delete the node and re-add it.

**Comment by trriplejay** [comment]
Ok, we'll update here once we have more info.

**Comment by trriplejay** [comment]
@dcramble your node should be fixed now. Let us know if you have more trouble.

**Comment by dcramble** [comment]
Thanks - it's building now.
