### ISSUE TITLE
disable default gradle assemble for a gradle project

### ISSUE THREAD

**Issue by boxheed** [Shippable/support#2496]
I have a gradle project for which I use the gradle wrapper and the default container, however the `build_ci` target runs `gradle assemble` which I don't want it to do. Is there any way to stop shippable doing this?

**Comment by manishas** [comment]
@boxheed if you want Shippable to skip default processing for the `ci` section, just put some command in that section.... even something like `pwd` or `ls`. As long as there is some command in the `ci` section, default processing will be skipped.

**Comment by boxheed** [comment]
thank you

**Comment by manishas** [comment]
Closing
