### ISSUE TITLE
I can not sign in through Github

### ISSUE THREAD

**Issue by CobySeo** [Shippable/support#2497]
The message that is shown up on the page is:

status: 401 data: {"message":"Requires authentication","documentation_url":"https://developer.github.com/v3"

How can I solve this error?

**Comment by manishas** [comment]
Is this still happening? We haven't seen this reported by anyone else so wondering if it was a transient thing.

**Comment by CobySeo** [comment]
Oh I was confused that it was cloud9's page.
I mean I cannot sign in to cloud9 via github

**Comment by CobySeo** [comment]
And it is still unavailable to sign in with same message on it.

**Comment by manishas** [comment]
You mean you still can't sign in to cloud9? That's not our site. 

Do you need any help with Shippable?

**Comment by manishas** [comment]
Closing this issue since it's not a Shippable related problem.

**Comment by CobySeo** [comment]
Oh I see. I thought it may be somehow related to github cause i was trying
to sign in to cloud9 with my github account.

**Comment by manishas** [comment]
This is not a support forum for github or cloud9. 

It's for reporting problems with Shippable - https:://app.shippable.com - a continuous delivery platform.

**Comment by CobySeo** [comment]
Oh i got it.
Sorry
