### ISSUE TITLE
.ebextensions is ignored again

### ISSUE THREAD

**Issue by KnowRe** [Shippable/support#2498]
Looks like it's fixed once but it started to ignore .ebextensions folder again.
https://github.com/Shippable/support/issues/2156

The log is below:
https://app.shippable.com/runs/5705f76ff028a50b0080873f

**Comment by manishas** [comment]
@trriplejay can you take a look at this?

**Comment by trriplejay** [comment]
looks like a bug on our end. We should have something deployed in the next day or two. I'll update when the fix is available.

**Comment by trriplejay** [comment]
Hello, this fix has now been deployed. Please give it a try and let me know if you run into any problems.

**Comment by KnowRe** [comment]
It works well. Thank you very much!
