### ISSUE TITLE
Do gradle builds works with gradle wrapper?

### ISSUE THREAD

**Issue by rahuladeptus** [Shippable/support#2502]
Does it work with gradlew honouring the gradleVersion specified by the project?

If not whats the current default gradle version used?

**Comment by manishas** [comment]
@a-murphy can you answer this? Thanks!

**Comment by a-murphy** [comment]
Yes, tasks run with ```./gradlew```, such as ```./gradlew test```,  as documented [here](https://docs.gradle.org/current/userguide/gradle_wrapper.html) will use the version of Gradle specified in the wrapper.

If you have only specified  ```gradleVersion``` in a wrapper task in ```build.gradle``` and haven't created a ```./gradlew``` file (or the version in that file doesn't match), you may need to run ```gradle wrapper``` in your build script first.

Our current default version of Gradle is 2.3.

**Comment by manishas** [comment]
@rahuladeptus i'm closing this issue but please let us know if you have additional questions.
