### ISSUE TITLE
after moving github projects, building project breaks.

### ISSUE THREAD

**Issue by sboesen** [Shippable/support#2504]
I moved a github project to a different account;as building fails because the git_sync step tries to clone from original repo, which doesn't exist.

When I try to delete my original account I get the following error message:

```
(Id: 2000) No access or object not found for id: 57070fe02a8192902e1bc0fe
warn: common|validateProjs|callerId:570710fe49783a120011cb75|_checkProjectPermissions
```

Thanks for a good product otherwise!

**Comment by manishas** [comment]
@sboesen what was the username for your old account?

**Comment by sboesen** [comment]
Old account was sboesen, new github account is larsbo99.

**Comment by kanthchandra** [comment]
@sboesen can you please try force syncing your account so that all the permissions get updated? You can go to your account settings page and click on the sync button to forcesync your account.

Also I notice that larsbo99 is an organization under sboesen account. Since I couldn't find any account with username `larsbo99` have you logged in to shippable using larsbo99 account?

**Comment by sboesen** [comment]
I signed in for that account now and it works so far as it builds properly and passes on that account!

Unfortunately, I still can't delete that project from my account (or delete my account in an attempt to reset it). I suppose this is fine, I can just add projects, but weird it lingers and can't be deleted.

**Comment by manishas** [comment]
Closing this issue.

**Comment by sboesen** [comment]
Hi, I still can't delete my project (or my account). I suppose it's not the end of the world, but a bit frustrating. Still get the error message reference in the original post.

**Comment by sboesen** [comment]
@manishas could we reopen this ticket?

**Comment by manishas** [comment]
@trriplejay can we delete the account sboesen?

**Comment by trriplejay** [comment]
@sboesen your account has been removed.  If you log in again with that account, it will be treated like a new signup.  Please let me know if there's something else you wanted us to clean up, or if you're still experiencing any problems with your project.

**Comment by sboesen** [comment]
Thanks!
