### ISSUE TITLE
Changed annual plan from 5 minions to 1 again 

### ISSUE THREAD

**Issue by AndriyPt** [Shippable/support#2505]
We have already had the same issue some time ago 
https://github.com/Shippable/support/issues/1780

In the current case we have received email from Manisha Sahasrabudhe about our plan deprecation and I have tried steps from **Migrate your Subscription to the new plan** but after I have changed amount of containers to 5 (the same amount of minions which we have and paid for) I get hint to provide credit card details. But we have already paid for annual subscription and it haven't expired yet.

Could you please advice what we should do to get our minions back? :)

Thank you

**Comment by manishas** [comment]
@AndriyPt We shut down the $12 Startup plan on 2/28. This was communicated through my email, and you will be issued a refund for the $12 paid. We had actually sent out communication in July 2015 about shutting down the plan but it took a few months to be implemented.

You'll need to upgrade your plan at the current price of $10/minion. Let me know if you have any questions. 

Also, please let me know the github/bitbucket username with which you paid for the $12 subscription and I will issue a refund asap.

**Comment by manishas** [comment]
I have issued a refund for the $12 cost of Startup plan. You should see it on your card in the next couple of days.
