### ISSUE TITLE
services binding inconsistent, postgres doesn't bind to * address

### ISSUE THREAD

**Issue by oppianmatt** [Shippable/support#2506]
Trying to connect to postgres from a docker container but postgres is only listening on localhost. This is inconsistent with services like redis which listen on *.

For example:

```
  netstat -ta 0s  
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 *:6379                  *:*                     LISTEN     
tcp        0      0 localhost:postgresql    *:*                     LISTEN     
tcp        0      0 3c48b8537813:44026      github.com:ssh          TIME_WAIT  
tcp        0      0 3c48b8537813:39548      ec2-52-87-95-33.c:https ESTABLISHED
tcp6       0      0 [::]:6379               [::]:*                  LISTEN     
tcp6       0      0 localhost:postgresql    [::]:*                  LISTEN     
tcp6       0      0 localhost:47717         localhost:6379          TIME_WAIT  
tcp6       0      0 localhost:40467         localhost:postgresql    TIME_WAIT  
```

redis is bound to *:6379 and so can be used in docker containers but postgres is bound to 127.0.0.1 so can't be used.

shippable.yml:

```
language: python

python:
  - 2.7

services:
  - postgres
  - redis

build:
  cache: true
  ci:
    - psql -c 'CREATE DATABASE testdb;' -U postgres
    - ifconfig
```

Note tried a work around of setting the environment cmd that starts postgres to include a listen address:

```
SHIPPABLE_POSTGRES_CMD=sudo -u postgres /usr/lib/postgresql/9.4/bin/postgres -c config_file=/etc/postgresql/9.4/main/postgresql.conf -c listen_addresses '*'         
```

but this gives an error:

```
setup_env 0s
  echo 'An error occurred while trying to export an environment variable: SHIPPABLE_POSTGRES_CMD Please check your YML env section'
```

**Comment by trriplejay** [comment]
for your SHIPPABLE_POSTGRES_CMD, you can avoid that error by putting everything in quotes:
```
SHIPPABLE_POSTGRES_CMD="sudo -u postgres /usr/lib/postgresql/9.4/bin/postgres -c config_file=/etc/postgresql/9.4/main/postgresql.conf -c listen_addresses '*'"
```

Typically we just start our services with default settings and let the user override if necessary.  Let us know if that works for you.

**Comment by oppianmatt** [comment]
I ended up trying to use a docker container to start postgres for testing (as that's what I use locally, and I need to do it for solr anyway). But the port bindings have me a little confused:

```
docker ps -a 0s  
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
82a21c098060        pitchup/solr               "/opt/solr/bin/solr -"   20 minutes ago      Up 20 minutes       0.0.0.0:8983->8983/tcp   jovial_hopper
5a36a91cf7ab        pitchup/postgres           "/docker-entrypoint.s"   21 minutes ago      Up 21 minutes       0.0.0.0:5432->5432/tcp   prickly_einstein
d0566a95f8a2        drydock/u14pytall:prod     "/home/shippable/cexe"   24 minutes ago      Up 24 minutes                                c.exec.Pitchup.com.224.1
1553166c44d3        shipimg/mexec:master.128   "/home/shippable/mexe"   25 minutes ago      Up 25 minutes                                shippable-mexec-5708d3c8c179750c000efa64

  netstat -ta 0s  
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 *:6379                  *:*                     LISTEN     
tcp6       0      0 [::]:6379               [::]:*                  LISTEN     
```

As you can see I've started solr and postgres via docker, and the ports are exposed but I can't see them with netstat. I'm guessing that's because I'm a docker in docker container and those ports are really exposed to the outside container and not the one I'm running in.

Had a question but ending up solving it, so leaving the solution here in case it helps anyone else.

Because we are running docker in docker, containers that expose ports aren't accessible via localhost since the localhost is in a docker itself. What one needs to do is to `link` the containers when running the test container. For example with postgres:

```
 - docker run -d --name postgres pitchup/postgres
 - docker run --link postgres:postgres --env-file .env -v $(pwd)/shippable/testresults:/app/shippable/testresults $DOCKER_HUB_PROJECT python -u manage.py test --noinput --with-xunit --xunit-file=/app/shippable/testresults/nosetests.xml
```

Alternatively I might try the solution suggested and not create/run containers for services and try use existing services (Although will still need to do so for solr).

**Comment by manishas** [comment]
closing this issue. @oppianmatt would you consider writing a blog about how to handle this scenario? We'll be happy to post it on our blog site.

Thanks!

**Comment by eddwardo** [comment]
This causes issues for people who want to run containers and connect to them.
Running _another_ container just to link with the new container seems like a workaround, it causes serious discrepancy between local and CI environment.

For example: I run containers with docker-py during the tests, they pass locally just fine. But on shippable I get cryptic errors about ports not being open. Investigating this took me 3hrs and lead me to this issue. Not cool at all.
