### ISSUE TITLE
Nodes not starting and builds not being assigned to existing nodes

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2508]
We have 8 builds pending.

No nodes are spinning up.

1 node that is existing is not building any of the projects...

**Comment by chriskinsman** [comment]
Last running node has now shutdown.  Dead in the water with a fix to deploy...

**Comment by trriplejay** [comment]
looking into it now

**Comment by chriskinsman** [comment]
Thanks!

**Comment by chriskinsman** [comment]
Something just changed.  All projects just went into provisioning node state instead of waiting.

**Comment by chriskinsman** [comment]
No nodes however appear to be provisioning...

**Comment by chriskinsman** [comment]
Nodes just provisioned it looks like...

**Comment by chriskinsman** [comment]
Builds are now building...
