### ISSUE TITLE
PostGIS extension support?

### ISSUE THREAD

**Issue by aguywithanidea** [Shippable/support#251]
We have two databases that need to be created to run our tests.  One requires the [PostGIS extension](http://postgis.net/install/).  Our database create commands execute successfully, the calls to enable the extension appear to succeed (we don't receive errors in the migration), but any subsequent calls that depend upon GIS-based columns will fail with errors saying the columns do not exist.

Let me know what additional information you require on this.

**Comment by aguywithanidea** [comment]
Manisha,

We haven't had a chance to review this.  You can close out this issue for
now.

R

**Comment by manishas** [comment]
Thanks! I will check back with you in a few weeks.
