### ISSUE TITLE
New wait_for_exit part of script makes build timeout

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2514]
Last Thursday at 2:56pm PST, my build was working. All builds after 4:21pm PST fail by timing out. If I look at the console, it looks like there is a new step in the build script called wait_for_exit has been added (not in previous working build scripts). It's in this new step that the build is getting stuck and timing out. 

See https://app.shippable.com/runs/5707fadb49783a12002d5b29

**Comment by trriplejay** [comment]
wait_for_exit has been there for awhile, but it is not visible under normal circumstances.  It is just our way of following the build and waiting for it to complete.  In this case, it looks to me like your build became stuck during the CI step, and eventually timed out.  Since your build didn't explicitly fail, the failure is marked in the wait_for_exit step instead of the build_ci step.

Was there any change in your CI workflow that could have caused that step to hang?

**Comment by npahucki** [comment]
I'm sorry, I meant to attach this which shows the problem is in the wait_for_exit. 

![screenshot 2016-04-11 15 57 59](https://cloud.githubusercontent.com/assets/823555/14438826/60b2302c-fffe-11e5-91ca-56f551be191d.png)

**Comment by trriplejay** [comment]
The way we present it is a bit confusing, but basically this is saying that 'wait_for_exit' waited for 1 hour and 54 minutes for your build container to exit.  When it didn't exit within the maximum time allowed, the container was killed.  The other steps in your build occur in parallel with this step, not in series as the order in the console implies.  

In this case, the build never completed.  It looks like the build_ci step didn't finish for some reason.  I figured I'd first ask if there could be any change in your CI that would result in the build suddenly having trouble executing that step.  If not, then we'll have to dig a bit deeper and see if we can figure out the underlying issue.

**Comment by npahucki** [comment]
I see. There were some changes, but they were tested and seemed to work in the PR. I'll do a little more investigation and testing before asking you to dig into it. Please don't close this issue until we have a resolution.

**Comment by npahucki** [comment]
Ok, we can close this. I found some stuff on our side that could have contributed, but also some stuff that worked fine locally but makes the build hang when only when run on shippable (using grunt-concurrent for running unit tests - I still have no idea how this makes the build hang or how it worked for months with no problems then suddenly stopped. I'm guessing some new version of some npm library made it break).
