### ISSUE TITLE
Builds failing for an unknown reason

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#2522]
### Is your request:

- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:
[Failed build 1](https://app.shippable.com/runs/570dd1cde817e50c00f2e230)
[Failed build 2](https://app.shippable.com/runs/570dd1aab7923b0c00d94dcc)

The following error appears in the logs:

    [ERROR] An unknown compilation problem occurred
    An exception has occurred in the compiler (1.8.0_25). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.

**Comment by manish-in-java** [comment]
Also note that the builds are not being retried despite the YML file containing a retry directive:

    language: java
    jdk:      oraclejdk8
    script:
      - shippable_retry mvn -clean test

**Comment by a-murphy** [comment]
This Java bug appears to match: http://bugs.java.com/view_bug.do?bug_id=8056984

It might be worth checking what you changed between the last successful build and the failed build to see if you can avoid the compilation error.
