### ISSUE TITLE
Not receiving build notification emails

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#2523]
### Is your request:

- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:
We are not receiving build notification emails for [our project](https://app.shippable.com/projects/55801052edd7f2c0521a75d8).  The last email received was on March 28, 2016.  After that no new failure or success emails have been received.

**Comment by manishas** [comment]
@manish-in-java can you share your yml?

**Comment by pranaypareek** [comment]
@manish-in-java it'll also be helpful if you could let us know the `runId`s for which you did not receive the emails.

**Comment by manish-in-java** [comment]
language: java
    jdk:      oraclejdk8
    script:
      - shippable_retry mvn -clean test

Failed runs:
* [1](https://app.shippable.com/runs/56fe141d01bc170c00d96567)
* [2](https://app.shippable.com/runs/56fe33cb01bc170c00dc863a)
* [3](https://app.shippable.com/runs/56fe343a1f6f0d0c00c203bf)
* [4](https://app.shippable.com/runs/57011c7e15baad0c00297e7c)
* [5](https://app.shippable.com/runs/570136cc5ef1180c00ffb759)
* [6](https://app.shippable.com/runs/570138555ef1180c00fffda0)
* [7](https://app.shippable.com/runs/570350641644e20b0027698a)
* [8](https://app.shippable.com/runs/57051fa11c51560c007726ed)
* [9](https://app.shippable.com/runs/5705d6d6c72afc0c00ba18a7)
* [10](https://app.shippable.com/runs/570b85f0a6dbbe0c00f694be)
* [11](https://app.shippable.com/runs/570c6774ab73e00c00204b88)
* [12](https://app.shippable.com/runs/570dd1aab7923b0c00d94dcc)
* [13](https://app.shippable.com/runs/570dd1cde817e50c00f2e230)
* [14](https://app.shippable.com/runs/570dde3e2961610c00e41332)

**Comment by pranaypareek** [comment]
@manish-in-java we are investigating the issue and will get back to you soon.

**Comment by amalfra** [comment]
@manish-in-java A fix for this issue is live now. You should get notification emails for runs from now onward. Please let us know if you are still not getting notification emails for build failures.

By default, we send email notifications to the last committer when a build fails, or the status changes from failed to passed. So, if you need notification emails for success too then update your yml to include:

```
integrations:
    notifications:
        - integrationName: email
          type: email
          recipients:
            - exampleone@org.com
          on_success: always
          on_failure: always
```
http://docs.shippable.com/ci_configure/#email-notifications has full documentation on all config that we support.

**Comment by manishas** [comment]
@manish-in-java i am closing this issue since we have fixed the problem. Please let us know if you run into any issues.
