### ISSUE TITLE
faster builds

### ISSUE THREAD

**Issue by filipeguelber** [Shippable/support#2524]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [x] A question: A non-technical question such as billing.

### Description of your issue:
If I upgrade to a paid plan with, for eg,  2 containers, my build will spent the same time and the only advantage is to run 2 build jobs at the same time or these 2 containers can be used to provide a faster build ?

**Comment by manishas** [comment]
@filipeguelber if you upgrade your plan, you will get more parallel builds, so you can run multiple builds at the same time. This will help you save time when builds are triggered at the same time and queued. . 

You can make your builds faster with the following options-
- cache your dependencies. We allow you to specify folders you want to cache and this saves time if you're downloading and installing dependencies for each build. More on this here - http://docs.shippable.com/ci_configure/#caching

- using your custom docker image that is fine tuned with what you need for your build. 

- attach your own build machines to your subscription. You can attach bigger build machines which will help you run faster builds. More on this here - http://docs.shippable.com/ci_byoh/

Let me know if this helps.

**Comment by manishas** [comment]
Closing since question has been answered. Please let us know if we can help further.
