### ISSUE TITLE
Slack integration: widen webhookUrl input

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2525]
### Is your request:
- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
### Description of your issue:

We made mistakes in issue #2516 that I think could be prevented in the future in a few ways. I've opened different issues, and this is one is about the web hook input. The simplest way is to widen the webhookUrl field in a Slack integration: the `.ss-input-short` class is applied, which makes the input field needlessly small. Just let it take the whole width, please.

Thanks for Shippable!

**Comment by avinci** [comment]
@amalfra do we know what the status of this is? Seems like this dropped off from the face of the planet..

**Comment by amalfra** [comment]
@avinci this got missed and I think we had put hold on this since those pages were going to be redone. With the UI iterations looks like this is no longer relevant since we already removed `ss-input-short` class from the inputs and hence has more width now

**Comment by pquentin** [comment]
Now it's the `ss-input` class that limits the width to 440px. Better, but still 30% too short to show the full URL. Using the full width would be better.
