### ISSUE TITLE
Share integrations in subscription

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2526]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.

### Description of your issue:

We made mistakes in issue #2516 that I think could be prevented in the future in a few ways. I've opened different issues, and this is one is about sharing integrations. We don't understand why we can't share integrations per subscription: everyone has to configure its own integration in order to apply it to its projects. Having each developer configuring its own integration brings many issues:

 * it increases the likelihood of errors,
 * it requires us to make sure that we use the same name so that our .shippable.yml are uniform,
 * it means we have to go through all projects when a developers leave, since we can't access his integration and know which projects he has configured

Thanks for Shippable!

**Comment by mbrodala** [comment]
I see that there is now an option to add integrations to subscriptions based on integrations created by users. This would allow for sharing integrations between all projects within a subscription AFAIS.

However, it seems like this feature is not yet finished or I fail to understand this change. I get this error:

> Integration name specified in yml does not match integrations present in project settings: foobar_slack

The relevant snippet from my `shippable.yml`:

```yaml
integrations:
  notifications:
    - integrationName: foobar_slack
      type: slack
      recipients:
        - "#shippable"
```

This Slack integration named `foobar_slack` was added to the subscription and is currently already used within all projects successfully.

**Comment by rageshkrishna** [comment]
Sorry about the delayed update, but integrations have now been consolidated at the subscription level. I'm going to go ahead and close this because you can now share integrations across all projects within a subscription.

**Comment by mbrodala** [comment]
Yes, works like a charm, thanks. :-)
