### ISSUE TITLE
Do not tie integrations to projects in the UI

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2527]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.

### Description of your issue:

We made mistakes in issue #2516 that I think could be prevented in the future in a few ways. I've opened different issues, and this is one is about integration configuration. We don't want to have to enable an integration in the UI before specifying in .shippable.yml. Why can't we just choose the integration in the .shippable.yml? I think it would be perfectly possible once #2526 is implemented.

Thanks for Shippable

**Comment by manishas** [comment]
we will think about how to mitigate this painpoint and the one mentioned in the previous issue together. Closing this as dup of #2526
