### ISSUE TITLE
Allow specifying default options in Slack integration

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2528]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.

### Description of your issue:

We made mistakes in issue #2516 that I think could be prevented in the future in a few ways. I've opened different issues, and this is one is about default options. We only want to say "integrate with Slack" in our .shippable.yml, and would like to specify on_success, on_failure, recipients and type in the integration where the key is already specified. It would only help after #2526 is implemented.

I realize this is not the route you want to choose because you said in #2516 you would remove the channel from the account integration, so feel free to close this ticket (the same applies for the other ones, of course).

Thanks for Shippable!

**Comment by osvalr** [comment]
I think this proposal will be useful, currently I'm using [slackcat](http://slackcat.chat/) to accomplish this

**Comment by manishas** [comment]
@pquentin we have removed the channel from account integration. Looking at overall feedback, it looked like having the channel in account integration and then letting folks override was causing too much confusion. So the decision was to require channels in the yml config.
