### ISSUE TITLE
Connecting to an external API

### ISSUE THREAD

**Issue by rorteg** [Shippable/support#2529]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

https://app.shippable.com/runs/570ebd94b7923b0c00fe0351

Hello, I have a functional test of a Magento module that need to connect to a real external API, it depends on her return to work test.

There is this possibility?

For my tests do not pass because there is no return of the API.

Running these tests locally do not have any problems.

Thanks.

**Comment by ric03uec** [comment]
@rorteg from the build logs it seems like all the failed builds are making calls to `http://127.0.0.1...` url. I don't see any external http requests.
can you help us figure out which external calls are failing and where.

**Comment by manishas** [comment]
@rorteg I am closing this issue but if you still need help please let us know, and we'll reopen and take another look.
