### ISSUE TITLE
Beanstalk - Docker deployments stopped working

### ISSUE THREAD

**Issue by rsteckler** [Shippable/support#2531]
### Is your request:
- [X ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:
Docker deployments to Beanstalk stopped working recently.  Here is the failed section of the build:
````
aws_eb_deploy 1m 27s
  pip install awsebcli 26s  
  eb --version 1s  
  deployment_details 0s  
  echo | eb init "evmote-web" -r "us-east-1" -p "" 2s  
  eb use "evmote-web-prod" 1s  
  eb deploy -l shippable.evmote-web-prod.master.251 57s  
WARNING: You have uncommitted changes.
Creating application version archive "shippable.evmote-web-prod.master.251".

Uploading: [--------------------------------------------------] 0% 
Uploading: [####----------------------------------------------] 8% 
Uploading: [########------------------------------------------] 17% 
Uploading: [#############-------------------------------------] 25% 
Uploading: [#################---------------------------------] 33% 
Uploading: [#####################-----------------------------] 42% 
Uploading: [#########################-------------------------] 50% 
Uploading: [#############################---------------------] 58% 
Uploading: [#################################-----------------] 67% 
Uploading: [######################################------------] 75% 
Uploading: [##########################################--------] 83% 
Uploading: [##############################################----] 92% 
Uploading: [##################################################] 100% Done...
INFO: Environment update is starting.
INFO: Deploying new version to instance(s).
INFO: Batch 1: Starting application deployment on instance(s) [i-9d1a0e64].
INFO: Batch 1: De-registering instance(s) from the load balancer and waiting for them to go out of service.
INFO: Batch 1: Starting application deployment command execution.
ERROR: Failed to download authentication credentials <DOCKER_CONFIG> from elasticbeanstalk-us-east-1-868487526669
ERROR: [Instance: i-9d1a0e64] Command failed on instance. Return code: 1 Output: (TRUNCATED)...t;</Key><RequestId>REDACTED</RequestId><HostId>REDACTED</HostId></Error>
Failed to download authentication credentials <DOCKER_CONFIG> from elasticbeanstalk-us-east-1-868487526669. 
Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/03build.sh failed. For more detail, check /var/log/eb-activity.log using console or EB CLI.
INFO: Batch 1: Completed application deployment command execution.
INFO: Command execution completed on 1 of 2 instances in environment.
ERROR: Unsuccessful command execution on instance id(s) 'i-9d1a0e64'. Aborting the operation.Leaving instances running for troubleshooting. Instances have not been re-attached to load balancer.
ERROR: Failed to deploy application.
ERROR: Failed to deploy application.
````

Note this line:
````
ERROR: Failed to download authentication credentials <DOCKER_CONFIG> from elasticbeanstalk-us-east-1-868487526669
````
It sounds to me like the ````<DOCKER_CONFIG>```` isn't being replaced with whatever belongs there.

Here is a working build from last week.  It's the exact same codebase.  All I did to get the failure was to rebuild the existing repo by pushing the build button.  You can see that the old working build did an aws_eb_docker_deploy and the new broken one did a aws_eb_deploy.  Not sure if that's important.
````
  aws_eb_docker_deploy 3s
  deployment_details 0s  
  use_dockerrun_aws_json 0s  
  upload_artifacts 0s  
  create_application_version 1s  
  update_environment
````

**Comment by manishas** [comment]
@trriplejay can you please look into this?

**Comment by trriplejay** [comment]
@rsteckler Shippable is moving away from management of creating/uploading/referencing dockercfg files during the build workflow.  What we recommend our users do now is to create their own dockercfg file according to instructions found here:
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker.container.console.html#docker-images-private

and then simply update your Dockerrun.aws.json file so that the authentication section references the bucket and file directly, without the need for finding/replacing tags on the fly.
```
"Authentication": {
    "Bucket": "my-bucket",
    "Key": "mydockercfg"
  }
```

This way you have full control over what credentials your beanstalk deployment is using at all times, and Shippable won't stand between you and your authentication.  

The main piece Shippable becomes responsible for is replacing <IMAGE_NAME> and <TAG> to match whatever image you may have just finished building.

Let me know if you have any questions about this.

**Comment by rsteckler** [comment]
Got it.  So if I can just play that back:  You're saying that in the Dockerrun.aws.json file, Shippable will continue to replace ````<IMAGE_NAME>```` and ````<TAG>````, but will no longer replace ````<DOCKER_CONFIG>````.  Is that right?

Thanks!
Ryan

**Comment by trriplejay** [comment]
yep, that's right.
