### ISSUE TITLE
Unable to complete GCR integration

### ISSUE THREAD

**Issue by neilberkman** [Shippable/support#2533]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

I'm trying to integrate with GCR using the instructions here:

http://blog.shippable.com/docker-with-google-container-registry-and-shippable

I'm on "Pushing an image to GCR" but I'm not seeing "Push build" in my settings UI.  Are the docs up to date?  Thanks.

**Comment by abhijitkini** [comment]
@neilberkman we have significantly upgraded our platform since that blog was written. Please refer to the documentation on [pushing an image to the registry](http://docs.shippable.com/ci_configure/#pushing-an-image-to-a-registry) that includes information on pushing to GCR

**Comment by neilberkman** [comment]
Thanks.  You might want to add a note referencing the updated docs to the top of that post.

**Comment by abhijitkini** [comment]
Yes, we are working on it. All deprecated blog articles should have the note pointing to the docs, shortly.
