### ISSUE TITLE
Successful Build Is Not AutoDeployed / New Build Is Not Available for Image Creation

### ISSUE THREAD

**Issue by jgregors** [Shippable/support#2536]
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:

After a successful build, my image is not being auto-deployed via the pipeline. When I try to manually create a new image in order to deploy it, the build is not available.

For instance, on my project "osden/platform", the latest successful build is "master.38" but the current image deployed is associated with "master.32". When I go to "new version" on the the pipeline settings page, I cannot see "master.38" in the tags dropdown even after syncing. This means that I have no way to deploy the current build.

**Comment by trriplejay** [comment]
@jgregors Hello, it looks like your image got into a state where it was failing to properly sync tags.  I've gotten it unstuck and I'm opening an internal issue to correct the root of the problem.

Your image should be back to normal now and auto-deploy should function again. Let me know if you still have trouble.

**Comment by trriplejay** [comment]
The fix for the underlying issue has been deployed. Closing this issue. Please reopen if you have further questions.
