### ISSUE TITLE
no docker hub login at all

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#2539]
https://app.shippable.com/runs/57151c99e782fb0c00c6b098

**Comment by trriplejay** [comment]
@luckyraul It looks like your pre-ci build step is trying to use a base image, but it can't find the tag that the dockerfile is asking for.  Since the image isn't being built, the boot step cannot use it.

**Comment by luckyraul** [comment]
It is okay to fail first two builds however all other builds created and booted successfully. They can't push with auth required

**Comment by manishas** [comment]
@luckyraul you do not need the `agent_only: true` line in your yml. Please remove that line and everything should work as expected.

**Comment by luckyraul** [comment]
I inserted it via https://github.com/Shippable/support/issues/2289

**Comment by manishas** [comment]
The agent_only flag indicates that you don't want us to login to hub from inside your CI container. If you want to push the container and use agent_only, please use the push section of the yml.

**Comment by manishas** [comment]
@luckyraul I am closing this issue, but please let us know if you have any more questions and we'll be happy to reopen.
