### ISSUE TITLE
On deploy, ECS task is updated but task definition is not

### ISSUE THREAD

**Issue by jgregors** [Shippable/support#2544]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

When an image is deployed to my ECS cluster, the task is updated but the task definition is not. Is it possible to check if the messages sent to AWS are correct. I have not been able to find an issue on the AWS side (but this is completely likely as I am an AWS newbie). This happens for both autodeploy and when I manually change the deployed version. The fix for me has been to log onto AWS, stop the task, and then update the ECS service with the correct task definition.

**Comment by manishas** [comment]
@trriplejay can you take a look?

**Comment by trriplejay** [comment]
@jgregors If there's an issue placing new tasks, it should appear in your 'events' list on the status page for your pipeline. (there are 3 tabs there: deploy, history, events).

I believe that by default, ECS will not allow a deployment to reduce the tasks below 100% of your desired replicas, so when you deploy, it will try to bring up the new task before killing the old one.  If it cannot find a place to run the new task, then the old one will just keep running.  If you kill the old task manually, the new one should start up on its own once ECS realizes it is able to do so, though sometimes it can take a minute or two.

Let me know if you have any other questions.

**Comment by jgregors** [comment]
@trriplejay thanks for this. Makes perfect sense. I reconfigured the images, redeployed and worked as expected. I appreciate the help!
