### ISSUE TITLE
Queue time statistics

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#2545]
Hi,

I think this is currently not possible, but it would be really helpfull to have statistics on queue times of builds so we can adjust the amount of workers to a sensible amount.

Are these statistics available somewhere?

Regards, Bjorn.

**Comment by ttrahan** [comment]
@bbrala : 
Hi Bjorn, we've added that to the backlog.  In the meantime, you can use calculations based on queuing theory to calculate the optimal number of minions based on your build characteristics.  For example, if you want to have a <1% chance of a 30s wait for a build to start when the number of builds during the peak hour of the day is 30 and the average build duration is 5 minutes, you should have 7 build minions available:
```
$ node --harmony recMinionsSingleScript.js 30 5

*** Recommended minion count: 7 ***

Probability of waiting less than X minutes for specified number of minions:
[ [ 'Minions', 0.5, 5, 10, 15, 20, 25, 30 ],
  [ 3, 0.33, 0.57, 0.74, 0.84, 0.9, 0.94, 0.96 ],
  [ 4, 0.72, 0.93, 0.98, 1, 1, 1, 1 ],
  [ 5, 0.9, 0.99, 1, 1, 1, 1, 1 ],
  [ 6, 0.97, 1, 1, 1, 1, 1, 1 ],
  [ 7, 0.99, 1, 1, 1, 1, 1, 1 ] ]
```

If there are 10 builds during the peak hour with 5 minute builds, the numbers switch to:
```
$ node --harmony recMinionsSingleScript.js 10 5

*** Recommended minion count: 4 ***

Probability of waiting less than X minutes for specified number of minions:
[ [ 'Minions', 0.5, 5, 10, 15, 20, 25, 30 ],
  [ 1, 0.18, 0.29, 0.4, 0.49, 0.57, 0.64, 0.69 ],
  [ 2, 0.78, 0.92, 0.98, 0.99, 1, 1, 1 ],
  [ 3, 0.95, 0.99, 1, 1, 1, 1, 1 ],
  [ 4, 0.99, 1, 1, 1, 1, 1, 1 ] ]
```

To run these calculations yourself for your data, you can find the code for this here:
https://github.com/ttrahan/q-calc

**Comment by bbrala** [comment]
Thanks for the answer, I'll keep an eye on this issue.

**Comment by manishas** [comment]
@bbrala we have an Insights view that will tell you how long your builds were queued in the past week. To look at this, click on the icon for insights on the Subscription dashboard:
![image](https://user-images.githubusercontent.com/2983749/43542019-b84af124-9580-11e8-9303-76fc296bbcc3.png)
  
This will give you a view of the last 7 days:
![image](https://user-images.githubusercontent.com/2983749/43542050-d3f90708-9580-11e8-9d41-16be8ee4d877.png)

We're working on providing this view for longer/custom durations, but this should help in determining if your builds are spending a lot time in queues.
