### ISSUE TITLE
parallel testing builds multiple docker images

### ISSUE THREAD

**Issue by oppianmatt** [Shippable/support#2551]
### Is your request:
- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.
### Description of your issue:

Following the guide in the section "Building your CI image" to build my own image for testing. Building my docker image in the pre_ci section.

Also set parallelized_test to true in the build: section.

  parallelized_test: true

Test matrix setup to split tests across nodes:

```
env:
  matrix:
    - NODE_TOTAL=2 NODE_INDEX=0
    - NODE_TOTAL=2 NODE_INDEX=1
```

The issue is that the pre_ci section is building 2 docker images, one for each node. But the point of the tests is that I want to test the same docker image on each node. I want to build the custom docker ci image ONCE, and then run parallel tests on that image. Having each node build it's own image could mean slightly different images for testing.

Then it seems the `push` section is also run multiple times per node. So the slightly different ci images are pushed to the same tag.

I also have `cache: true` in the build section but it seems I get a cache miss more often then not when it comes to building the custom docker image. Which means my docker image is running a 17 minutes requirements.txt stage, which hasn't change and normally would be cached.

This means I have 2 minions tied up for an hour rather than 10 minutes.

Note I couldn't find anything about `parallelized_test` and what it's meant to do in the docs. How can we have one docker image built and pushed but have parallel tests?

**Comment by oppianmatt** [comment]
Initially I thought I solved the issue by having an environment variable control which instance does the pushing. But I thought push is only called when all nodes succeeds but I find that's not the case.

Here the third node has called push but node two hasn't even finished yet. How does it know it should push if the tests haven't completed yet?

![image](https://cloud.githubusercontent.com/assets/48596/14677664/61778f1c-070a-11e6-960c-08e73cf7da58.png)

**Comment by oppianmatt** [comment]
I've even had tests fail but it thinks it a success on one of the nodes and pushes.

How do we tie into the shared state success and not the individual node success? Surely it can be done and it's not a feature request? If not then what use is any of the on_success methods if using parallel builds.

Didn't realize this was a limitation. Why would there be a feature to parallel the tests as described in the blog http://blog.shippable.com/running-parallel-builds-on-shippable and docs and it collects/collates the tests. But still will run the on_success handlers even if there is a failure?

This comment (from Sep 11, 2014) says it aggregates https://github.com/Shippable/support/issues/279#issuecomment-55229835 
> We have added build groups which aggregate everything executed on parallel minions under one status.

But how do we run something on just that success?

Initially was attracted to move to shippable because of the pipelines which promises running tests on containers and deploying, but can't use pipelines unless using a PaaS I found out. Now I'm finding out I can't even get shippable to be reliable in announcing and running code on test failures.

**Comment by avinci** [comment]
Today our YML is at a build level. Hence trying to break the YML across multiple builds is going to be very difficult. That being said, this is my personal opinion and we do this extensively at Shippable. 

We first isolate all the parts of the image that is not code dependent and build a base image repo out of it. The only goal of this is to build an immutable package & OS image. We do npm packages, apt-get packages etc. into this.

Then, in our code repo we just pull this image, add code to it and test it from CI perspective. If this works, then we push the new container with code over-layed on top it with fully tested CI.

To achieve this, you would need to do the following
* create a project for your Dockerfile and move all package dependencies to it. Do a docker push to hub once this builds
* Second, in your code project use the `pre_ci_boot` section to pull the above built image and the system should do what you are trying to do. Use the same image across multiple code CI builds
* you can push you CI tested container to the hub and you are guaranteed to have consistent immutable images

The one thing this cannot do right now is that, if your image repo on github changes, it doesnt fire cascading builds. Of course your other web hook issue 2556 should solve that and it should be going live on Monday.

let me know if this helps?

**Comment by oppianmatt** [comment]
Not trying to break the yml across multiple builds, this is all still in one build, albeit a parallel build, but still the one build.

If I did what you said it still would happen: 
 - parallel build will kick off starting N sub builds
 - each N sub builds still builds a docker and overlays the code on top
 - push section will still happen N times, even if one of the parallel builds FAILED

Don't see how your solution would help anything at all.

The issue is simple (but the fix not so). The `pre_ci` and the `push` sections, are being run multiple times for the one build. 

It needs global (and in this context means across the set of parallel linked builds) sections which run only once, and not N times. So in the global_pre_ci section (which runs once/first) I would build a docker image that I want to test.

Then the parallel ci test section using that one docker image to split my tests up between N hosts.

Then after all the tests are done we need a global success or failure. The current state where if one of the N hosts fail is still considered a success it not really acceptable. I would like to run code after all N hosts have completed tests knowing either all N have passed or at least one failed.

Here would be an example if such a thing was supported:

```
build:
  cache: true
  parallelized_test: true
  global_pre_ci:
    - docker build -t $BRANCH.$BUILD_NUMBER
  pre_ci_boot:
    image_name: $DOCKER_IMAGE
    image_tag: $BRANCH.$BUILD_NUMBER
  ci:
    - bash shippable_ci.sh
  global_on_success:
    - docker push
```

The global_pre_ci is run once, on one host before the parallel ci section is run on the N minions.

Then the global_on_success is run once, AFTER all the N minions have completed.


What I find strange is that in the docs you have a section in the multiple builds about allowing failures http://docs.shippable.com/ci_configure/#allowing-failures

> Allowed failures are items in your build matrix that are allowed to fail without causing the entire build to be shown as failed. 

That means you already know if a set of builds has a failure or not. What I want is to know the same thing. How do I get this event that either the entire build was successful or a failure? Surely if you can report a whole build as a failure based on one minion failing then I can get that event too. Or what's the point of allowing failures?

**Comment by avinci** [comment]
There are a few challenges to make global work. 

first is that multiple builds are running on multiple machines. the docker image is on that machine and when we centrally know whether the entire build with all items have passed or not, we cannot go back to the same machine to run a docker push as there is no guarantee that machine is still idle or alive.

second issue is that we need to split the YML now into three parts as you don't want the non-global part to run when the global part is running and you cannot run the non-global part until the global-pre is not run

third issue is that we cannot parallelize the builds across multiple machines as the global-pre-ci which creates the image does not exist on the other machine.

I totally understand what you are trying to do and I will spend some time to think about what is an elegant way to do this. But based on how it is currently working, this is not possible to do, atleast elegantly. There is a clunky way to do, but I am not proud of it and hence not even posting it here...

**Comment by RyanShelf** [comment]
Is there any movement on this? It seems this is what's holding my teams from moving to shippable.

**Comment by manishas** [comment]
@RyanShelf I will post an update on this later today.

**Comment by RyanShelf** [comment]
@manishas any update?

**Comment by avinci** [comment]
@RyanShelf this particular issue was the reason we created an entire new product line called pipelines. The complexity of different workflows and trying to mimic that with CI which pretty much every competitor of our in the CI space has the same problem.

The way to do this would be to use pipelines. Here is the docs link of the pipelines http://docs.shippable.com/pipelines/overview/

Here is what you would need.

- runCLI job to build your docker image and push it to a temp registry. 
- runCI job to use that temp image name as this image for your `pre_ci` where you pull this. Use `pre_ci` to boot this and then do the `ci`
- create a follow on runCLI job to now just tag the temp image into a permanent tag if the runCI job succeeds. 

This flow control is super easy with pipelines and please let me know if you would like me to write a detailed blog for this.
