### ISSUE TITLE
node provisioning taking unusually long time 19+ minutes

### ISSUE THREAD

**Issue by oppianmatt** [Shippable/support#2552]
### Is your request:

- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:

https://app.shippable.com/runs/57175738d1acc00e004161fd

![image](https://cloud.githubusercontent.com/assets/48596/14671860/1e68d366-06ec-11e6-9457-f4f86daffc11.png)

vs (in the same matrix)

![image](https://cloud.githubusercontent.com/assets/48596/14671872/31b860bc-06ec-11e6-96d1-a1b018768e64.png)

**Comment by kanthchandra** [comment]
Hi @oppianmatt, We have identified a small bug in our node allocation module because of which the nodes are not allocated on time occasionally. We have fixed the bug and are testing it as we speak. This should be deployed to production in the next couple of hours or so. Sorry about this.

**Comment by manishas** [comment]
This should be in prod now. @oppianmatt let us know if you see long wait times for node provisioning again.

**Comment by oppianmatt** [comment]
it's happening again 
![image](https://cloud.githubusercontent.com/assets/48596/14741533/c137baaa-088e-11e6-905b-fe6e4eded6fd.png)

**Comment by kanthchandra** [comment]
Hi @oppianmatt , I'm sorry about this. We have noticed this issue again today and we are actively investigating as to what is going on. We will get back to you as soon as we have more information on this.

**Comment by oppianmatt** [comment]
thanks

**Comment by kanthchandra** [comment]
Hi @oppianmatt , we have deployed a fix for this today. Please let us know if you observe this again.

**Comment by manishas** [comment]
closing this since fix is in prod. Please let us know if you run into this again.
