### ISSUE TITLE
Set memory as BestEffort for my cell manifest

### ISSUE THREAD

**Issue by filipegiusti** [Shippable/support#2555]
### Is your request:
- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.
### Description of your issue:

I would like to set memory as BestEffort for my cell manifest. Specifically describing Docker options what I have now is:

```
QoS Tier:
      cpu:      BestEffort
      memory:   Guaranteed
Limits:
      memory:   100Mi
Requests:
      memory:           100Mi
```

and what I want is

```
QoS Tier:
      cpu:      Burstable
      memory:   BestEffort
Limits:
      memory:   150Mi
```

**Comment by trriplejay** [comment]
This isn't currently supported, so I'm marking as a feature request.  Definitely something we'd like to add though.

**Comment by avinci** [comment]
this is no longer relevant as we have completely moved to pipelines and we don't use this anymore.  Please let us know if this is still an issue. 

The new manifest which support all sorts of pass through options are documented here http://docs.shippable.com/pipelines/jobs/manifest/
