### ISSUE TITLE
webhook notification

### ISSUE THREAD

**Issue by oppianmatt** [Shippable/support#2556]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

Surprised to see there isn't a generic webhook notification post build. There is the ones listed on http://docs.shippable.com/int_notifications/ which include slack/irc/hipchat/email. I would assume the slack and hipchat ones work from a webhook. So why can't we have a generic webhook to trigger the custom flows? 

Was hoping I could do it with pipelines but can't. 

Scenario is that shippable does the CI testing, marks it as ok and then kicks off a deployments/process with a custom webhook post.

Note it's trivial to implement a webhook ourself BUT the caveat is if using parallel testing it will kick off multiple times per minion (see #2551). If the webhook was part of the notifications sections (or you let us run some custom code there) that should kick off once per group build.

**Comment by manishas** [comment]
We're currently working on exactly this feature. You'll be able to configure a post run webhook that will be triggered once per group build. ETA is early next week.

**Comment by manishas** [comment]
@oppianmatt this is now available and is documented here - http://docs.shippable.com/ci_configure/#event-triggers

Let me know if you have any questions.
