### ISSUE TITLE
$BRANCH environment variable not expanding on docker commands

### ISSUE THREAD

**Issue by kileyhykawy** [Shippable/support#2558]
### Is your request:
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:
I am trying to use the $BRANCH environment variable in the post-ci and push sections but it doesn't seem to expand in the docker command and it ends up with a docker build failure. It expands when I just echo it.

```
build_post_ci
    echo $BRANCH  
        feature/feature-1

    docker build -t kileyhykawy/shippable_artifacts:$BRANCH .
        repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
```

Link to build failure: https://app.shippable.com/runs/57194f6b3f01b80c00f6a03c
Attached shippable.yml as shippable.yml.txt
[shippable.yml.txt](https://github.com/Shippable/support/files/230846/shippable.yml.txt)

**Comment by a-murphy** [comment]
It looks like your branch name contains a slash.  Docker won't allow slashes in tags, so Docker won't build your image.  It might be best to choose something else for your image tags.

**Comment by manishas** [comment]
Closing this issue since it's not a problem with shippable. Docker does not support / in tag name.

**Comment by kileyhykawy** [comment]
Doh! That makes sense. I thought the command in the log would actually have the variable expanded. Then I would have noticed. Thanks for the assistance.

For anyone else who comes along and sees this and you are using Git Flow, you'll need to find a way to normalize your branch name for features if you want to use them for Docker tags.
