### ISSUE TITLE
Update Git to support subtree command

### ISSUE THREAD

**Issue by tinchou** [Shippable/support#256]
I have a project with a structure like this:

````
-
| - dev
| - docs
| - spikes
````

In order to deploy the `dev` folder to Heroku, I was using `git subtree` from my own computer as shown here: https://coderwall.com/p/ssxp5q. Now I'm trying to delegate the deployment step to Shippable.

When the minion finishes building and executes `git subtree push --prefix 'dev' heroku master` (set in the `after_success` section of my `shippable.yml` file), I get the following message:

````
git: subtree is not a git command. See git --help.
````

It seems that you have an outdated version without subtree support. Hope you can update Git to allow us to use this feature.

Also, there is no documentation on how to use a build environment different than Ubuntu 12.04. Should it be as follows? (I tried it, nothing changed)

````
build_environment: ubuntu1310
````

In case you want to check, the ID of my project is `53acd8e1c40d71a900e7e704`.

Thanks,
Martín Coll.

**Comment by manishas** [comment]
Our official images in the  [drydock repo on docker hub](https://hub.docker.com/u/drydock/) now have git 2.7.1 which supports subtree.

This is resolved, closing.
