### ISSUE TITLE
Document API run statusCode

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2560]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

"run" and other documents returned by the API contain "statusCode". By trial and error it seems that:

- 20: running
- 30: success
- 80: failure

I suppose they are related to the list provided in https://github.com/Shippable/support/issues/2428#issuecomment-200292156 , starting at 0. 

Note these have been documented here : http://docs.shippable.com/ci_builds/#build-status

But they are not in "statusCode" order. I think the API documentation should detail the statusCode to human readable code mapping explicitely, and link to the page describing them.

**Comment by abhijitkini** [comment]
Updates complete to include statuscodes both in [API](http://localhost:5555/api/#status-code-mapping) & [build status](http://docs.shippable.com/ci_builds/#build-status) documentation.
