### ISSUE TITLE
Get latest run for a specific branch of a project with the API

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2561]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

I would like to make some kind of dashboard listing "failing projects". "Failing projects" are projects with one branch (among a set of well known branches like ("master", "develop")) which latest run was not successful. I would like to fetch all latest "runs" (?for specific branches) from all projects, but I could not find it in the documentation.

I see I can list all projects and get their branches at the same time. But I cannot see a call to get the latest run of a project *for a specific branch*. Or for all branches. And I am aware this approach is expensive as it requires $PROJECT*$PROJECT_BRANCHES or $PROJECTS calls.

Is there any way to achieve this?

Thank you for any suggestion.

**Comment by pmezard** [comment]
I misunderstood the documentation. "/projects/:projectId/branchRunStatus" does what I want, but it is titled as "Get latest run for a branch" where it really is "Get latest run for all project branches".

So I am down to one call per project. So you think I can do better than that?

**Comment by rageshkrishna** [comment]
@pmezard We don't have an API that returns the dataset that you're looking for. One call per project is necessary at the moment.

**Comment by abhijitkini** [comment]
Closing the issue. Please let us know if you have further questions.
