### ISSUE TITLE
Shippable IP addresses for accessing AWS-based build nodes

### ISSUE THREAD

**Issue by rlcomte** [Shippable/support#2562]
### Is your request:

- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:
What are the Shippable IP addresses from which our AWS build nodes are accessed?

**Comment by abhijitkini** [comment]
@rlcomte Shippable does not need access, if you set up build nodes and run the initialization scripts yourself. Configuring it this way, there is no need to whitelist Shippable's IP addresses. 

[Here's the documentation](http://docs.shippable.com/ci_subscriptions/#adding-your-own-build-infrastructure-byoh) on the steps to configure the same.

**Comment by abhijitkini** [comment]
Closing the issue. Please let us know if you need further help.
