### ISSUE TITLE
Getting more out of the code coverage report

### ISSUE THREAD

**Issue by materik** [Shippable/support#2563]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

I'm able to upload the code coverage data and I can see which files are not covered 100%, which is awesome. However, now I want to be able to go deeper into each file to see what code is not covered. How could I do that? Can I maybe store the html coverage report as an artifact or something?

**Comment by materik** [comment]
my temp solution is to commit the html coverage report when the shippable build is done.

**Comment by manishas** [comment]
@materik we will look into code coverage improvements in a holistic fashion in a later milestone. I am closing this request as a dup of https://github.com/Shippable/support/issues/174 since that is tracking everything for code coverage.
