### ISSUE TITLE
No local knex install found

### ISSUE THREAD

**Issue by robwilkerson** [Shippable/support#2564]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [✔️ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

My builds have been failing since this weekend and I don't understand why. It _seems_ to be something environmental but I don't have any insight into what the build environment looks like. At the moment, I'm installing the `knex` npm library globally, but still getting the error that...

> No local knex install found

I saw this for the first time a few days ago, but it's been intermittent. What's been less intermittent lately is a failure to execute the test script with no helpful error message. This all runs fine in my Vagrant environment (Ubuntu 14.04, Node 5.9.x, etc).

Wondering if someone could take a look at things and see if you see anything.

Build: https://app.shippable.com/runs/571e54ec2ad8320c00b405ff

**Comment by a-murphy** [comment]
There's a warning in your local npm install that you might want to look into.  I don't know what's in your package.json, but it could certainly explain why Knex wasn't found in that run but was in the run before.

**Comment by robwilkerson** [comment]
So in this case, a command a few lines above that in the `ci:` section installs knex and eslint globally:

    npm install -g knex eslint

That's the part that confuses me. The executable should be ready to go.

**Comment by a-murphy** [comment]
It looks like the "No local knex install found" error is actually from the globally-installed knex.  So, the global knex install must have correctly installed the CLI, but needs a locally-installed knex to run for some reason.  Unfortunately, I was unable to find any documentation on why this would be.

**Comment by robwilkerson** [comment]
Unfortunately, it's not that simple. No "local knex" is required. Has anything change in the build environment? This didn't happen in past builds. I assume you have access to the history, but if you have a moment, take a look at the most recent successful build (probably some time last week) on the `master` branch. The same code ran just fine. Knex installed globally and the migrations ran as expected.

I appreciate you taking the time to look into this. I'm at a loss and the failing builds are becoming a real problem...

**Comment by a-murphy** [comment]
We haven't found any Shippable changes related to your errors.  The image you are using was last updated six weeks ago and we haven't identified any changes in how it's run that could be related.

The build linked above had a warning about the package.json file for the ```npm install``` command that was not in your other builds, but not all of those builds were successful.  The majority of your failed builds appear to have a failing test, which we do not have the context to debug.  Since the knex error only appeared in the same build as the unsuccessful ```npm install```, the knex error is likely related to the npm warning in some way.

**Comment by robwilkerson** [comment]
Well, crap. This makes no sense to me. Thanks for taking some time to investigate. I guess this will be a brute force trial and error thing at this point...

**Comment by robwilkerson** [comment]
Okay, well this is embarrassing. It seems as though there was an errant comma in my `package.json` that I kept looking right past. It invalidated the JSON and was subtle enough to get right past me. My apologies, @a-murphy.
