### ISSUE TITLE
Not able to find Docker hub Integration configuration on Setting

### ISSUE THREAD

**Issue by somenathghosh** [Shippable/support#2566]
As per Documentation at http://docsshippable.readthedocs.org/en/latest/docker_build.html

**On the repo page, go to ‘Settings’. Choose the following -
Docker Build : ON
Dockerbuild order : Post-CI
Push Build : Yes if you want to push to Docker Hub, No if you don’t want to push to Docker Hub
Push image to : docker_hub_username/image_name
Pull image from : Since your Dockerbuild is happening post CI, enter the image you want to use for CI**

I am not able to find these options on setting of the Project. Few places I have seen documentation is pretty old and not updated properly and missign github repo(getting 404). Just wondering if configuration got changed or not. 

Please note: I have FREE account.

**Comment by rageshkrishna** [comment]
Hi @somenathghosh. It looks like you've stumbled upon some very old documentation. The latest docs are at http://docs.shippable.com/. Please take a look and let us know if you still have any questions.
