### ISSUE TITLE
Bringing up new node sometimes fails.

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#2567]
### Is your request:
**_A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue._**

### Description of your issue:

I have weird failures sometimes when using custom nodes. Sometimes the node fails to start a new docker nodig and i need to kill the python script for it to continue. How should i debug this?

Subscription swisnl

**Comment by bbrala** [comment]
It might have been a random timeout on this build https://app.shippable.com/runs/571f0c6f7a93fb0b006a8478 not sure.

**Comment by n0mer** [comment]
i've got same issue: 'provision job node', and then timeout in 2 hours

**Comment by n0mer** [comment]
this is logs output

```bash
$ docker logs b6a76e8591a8
No LSB modules are available.
Distributor ID: Ubuntu Description: Ubuntu 14.04.4 LTS Release: 14.04 Codename: trusty
Ubuntu confirmed
Looking for apt-get...
Found apt-get at /usr/bin/apt-get
Looking for sudo...
Found sudo at /usr/bin/sudo
Looking for git...
Found git at /usr/bin/git
Looking for ssh-agent
Found ssh-agent at /usr/bin/ssh-agent
Looking for python...
Found python at /usr/bin/python
Booting up CEXEC
Running CEXEC script
```

**Comment by n0mer** [comment]
if i 'cancel' build and press 'rebuild', then docker container on build node named 'c.exec.<PROJECT_NAME>.643.1' but shippable web console says current build number is 646

**Comment by n0mer** [comment]
i manually killed containers 644.1 and 645.1 on docker host machine, now build is running as c.exec.project_name.646.1 (646 is current number of job on shippable website)

**Comment by manishas** [comment]
@ric03uec can you look into this please?

**Comment by ric03uec** [comment]
@bbrala it seems like there is no shippable agent running on your custom node. can you reinitialize the host and try again. in an ideal scenario, there should be a shippable container `shippable-mexec-<id>` running on the machine. if reinitializing does not help, can you send me the output of following commands
- docker ps -a
- docker images
- docker logs -f shippable-mexec-<_id_of_the_container_>  
you can send these on my email : devashish AT shippable dot com

**Comment by ric03uec** [comment]
@bbrala the fix is now in production, you'll need to reinitialize the custom node for it to work.

**Comment by bbrala** [comment]
Ok, thanks, i'll give them a reset and keep an eye out for problems.

**Comment by manishas** [comment]
@bbrala I am closing this issue, but if you see any problems in this area please comment here and we'll be happy to reopen.
