### ISSUE TITLE
Don't see option to enable Docker Hub

### ISSUE THREAD

**Issue by somenathghosh** [Shippable/support#2569]
On the repo page, go to ‘Settings’. Choose the following -
Docker Build : ON
Dockerbuild order : Pre-CI
Push Build : Yes if you want to push to Docker Hub, No if you don’t want to push to Docker Hub
Push image to : docker_hub_username/image_name We need an image name for the image we build from your Dockerfile, even if you choose not to push to GCR
Source Location : (source code location where tests will be run)

I don't see these options in my Account. Is it because of FREE account ? I am looking for a document to integrate Docker hub with my account.

**Comment by kanthchandra** [comment]
Hi @somenathghosh, It looks like you've stumbled upon some very old documentation. The latest docs are at http://docs.shippable.com/. Also we have moved away from configuring your docker build from our UI. You can now configure the all the docker settings from your yml itself.

You can refer http://docs.shippable.com/ci_configure/ to configure your CI.
If you are specifically looking for docker support please refer http://docs.shippable.com/ci_docker/

**Comment by abhijitkini** [comment]
Closing the resolved issue.
