### ISSUE TITLE
What prerequisites need to be in a custom image to be a CI build container?

### ISSUE THREAD

**Issue by kileyhykawy** [Shippable/support#2571]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:
I'm testing out using a custom image for a CI build container based on Alpine Linux (specifically mhart/alpine-node:5.10.1). However, when I use it, I get an error in 'boot_container' saying it can't start container with a message saying no such file or directory:

```
sudo docker run -d -e HOME=/root -v /home/shippable/cexec:/home/shippable/cexec -v /home/shippable/cache:/home/shippable/cache -v /tmp/cexec:/tmp/cexec -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock --name=c.exec.shippable_customimage.7.1 --entrypoint=/home/shippable/cexec/build.sh -e RUN_MODE=production -e SHIPPABLE_API_URL=https://api.shippable.com -e SHIPPABLE_API_RETRY_INTERVAL=3 -e SHIPPABLE_CONTAINER_NAME=c.exec.shippable_customimage.7.1 -e SHIPPABLE_IS_OFFICIAL_IMAGE=false -e SHIPPABLE_IS_LEGACY_IMAGE=false mhart/alpine-node:5.10.1

        3d62d4e0558e1f450ef476613b96453acb5586584a49e70ff1155905d7873356
        Error response from daemon: Cannot start container 3d62d4e0558e1f450ef476613b96453acb5586584a49e70ff1155905d7873356: [8] System error: no such file or directory
```

alpine-node is a minimal container (based on Busybox, only has /bin/sh and not bash, etc.) so I'm not surprised. However, I can use this image for dev/test in my development environment. My first thought is that the image doesn't contain a requirement that Shippable wants. Is there anything that Shippable needs from the CI image to work successfully? 

- Link to the build failure: https://app.shippable.com/runs/57210e6075be0e0b0008dccb
[shippable.yml.txt](https://github.com/Shippable/support/files/239263/shippable.yml.txt)

**Comment by ric03uec** [comment]
@kileyhykawy as of now, our build system officially supports only the images based out of `ubuntu:12.04` and `ubuntu:14.04` although users have managed to run the builds on other images like `debian` that satisfy underlying dependencies
There are many dependencies on the build image that are missing in `alpine` like following
- /bin/bash
- python2.7
- /proc/sys/kernel/uuid
- apt-get // this is used to install further dependencies like `git` and `openssh-client`

these dependencies are critical for the shippable build runner to execute inside a user-provided image. 
We can add your issue as a feature-request for supporting non-ubuntu (or generic) images.

**Comment by kileyhykawy** [comment]
Definitely some requirements that will be tricky to get into Alpine Linux (like apt-get). Thanks @ric03uec for marking as a feature request.

In the meantime, I'm looking for a way to at least run tests in the custom image (more confidence that software will work in thus environment). What I'd like to do is "compile" my code with the standard drydock images, but then run tests in an Alpine Linux Node image in the "post-ci" section (or maybe it should still be in "ci"?). Running the image would mount the current working directory into the image so it has the compiled files from "ci" and well as the test files. Something like this (/src/app in image is the working directory):
```
docker build -t test_image .
docker run --rm -v ${PWD}:/src/app test_image /bin/sh -c "./run_tests.sh"
```

Would this work? I remember reading an issue somewhere that said something like an image like I have here wouldn't have access to the repository folder as defined in the "ci/post-ci" sections as they don't exist as named outside the CI build container. I suppose I need to know what folder name I can use for my volume mount because ${PWD} probably won't work.

Thoughts?

**Comment by ric03uec** [comment]
- when you say "compile" the code, im assuming you mean creating a new image where your code is based on top of one of the standard drydock images. 

- from my understanding, this might be the workflow you're looking for
  - run ci using shippable drydock image
  - this generates a bunch of test files, say the files are written into `testFiles` folder in the project directory
  - you do a `docker build -t test/test_image` in the `ci` section
  - now you want to run test some tests on this image inside `ci` section. 
so you should be able to do
```
docker run --rm -v ${PWD}:/src/app test/test_image /bin/sh -c "./run_tests.sh"
```
which should work since `docker ` command is available inside the `ci` section alongwith your source code and the generated test files

- let me know if i understood the problem and answered it. If not, i'll be happy to jump on a hangout and resolve this

**Comment by manishas** [comment]
Closing this issue. @kileyhykawy please let us know if you need any more help.
