### ISSUE TITLE
User access - can't see any subscriptions

### ISSUE THREAD

**Issue by manish-sangani** [Shippable/support#2572]
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description:
I have a user who has a github account and also have a write access to repository in github organization.
However, when he login to Shippable, he don't see any projects

What could be the issue?

My Shippable ID
5643b567bd279e0c001f472c

Please assist.

Thanks

**Comment by manishas** [comment]
@manish-sangani are the repositories private? If so, he will need to turn on access to private repos. 

To do this, he needs to click on the gear icon on the top navbar (for account settings). On the settings page, go to the Git identities section and enable private repos for GitHub. Once he authorizes that, he should 'Sync' his account on the Settings page. He should see the repos after that.

Let me know if this doesn't work.

**Comment by manish-sangani** [comment]
Got it.  That was very quick 👍 

Thanks
