### ISSUE TITLE
Filter ANSI color sequences from build log 

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2574]
### Is your request:
- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.
### Description of your issue:

It would be great if Shippable would filter out ANSI color sequences from the build logs. Currently the build output is put into the log as is, thus these escape sequences end up in the build log file, where they are less useful. Example:

```
pickle install --ansi intl && echo "extension=intl.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - Installing [32mintl[39m ([33mlatest-stable[39m)
    Downloading: [33mConnecting...[39m    Downloading: [33m0%[39m               Downloading: [33m10%[39m    Downloading: [33m20%[39m    Downloading: [33m30%[39m    Downloading: [33m40%[39m    Downloading: [33m50%[39m    Downloading: [33m100%[39m    Downloading: [33m100%[39m
```

**Comment by mbrodala** [comment]
For Sublime Text users there is a [package which evaluates the escape sequences](https://packagecontrol.io/packages/ANSIescape) and shows them as colors.

**Comment by manishas** [comment]
closing in favor of https://github.com/Shippable/support/issues/2207
