### ISSUE TITLE
api trigger new run specify sha

### ISSUE THREAD

**Issue by oppianmatt** [Shippable/support#2575]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

When using the api to trigger a new run, it would be nice to be able to specify what to build. Perhaps a sha/tag/branch?

**Comment by a-murphy** [comment]
Branch names can be specified in the body or a querystring.  For example, the following body would trigger a build for the master branch.
```JSON
{
  "branchName": "master"
}
```
And so would ```https://api.shippable.com/projects/:projectId/newBuild?branch=master```.

**Comment by abhijitkini** [comment]
Closing the issue. Do let us know if you have further questions.
