### ISSUE TITLE
Build fails at build_on_success step with error: "Permission denied (publickey)"

### ISSUE THREAD

**Issue by abhijitkini** [Shippable/support#2578]
### Is your request:

- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:
I am running into a ssh key issue when running a `docker build...` in an `after_success:` shippable.yml step. The issue is that I am getting the "Permission denied (publickey)" error when cloning from a public GitHub repo. I have a similar step in the shippable.yml steps to pull the same Github repos and that works successfully. My question is how do I get the ssh keys from my Shippable Key Integration inside the docker build process? I see that ssh keys are on the shippable build container in /tmp/ssh. I have tried copying those over to the docker build process, but for some reason they are not getting copied in as I would expect. Any suggestions on this?

- Link to the build failure: https://app.shippable.com/runs/572265d8f0b20b0c0048b337

**Comment by abhijitkini** [comment]
Using the command below in the Dockerfile, we copied the contents of SSH folder in the build directory into the Docker image. 

COPY ssh/* /root/.ssh/

[Docker wants you to copy](https://docs.docker.com/engine/reference/builder/#copy) from a relative path to an absolute or a relative path, and SHIPPABLE_BUILD_DIR is an absolute path.

**Comment by nmarshall-cst** [comment]
Hi Abhijit - I appreciate the help on this. I ended up getting this working by 

shippable.yml:
`  - mkdir -p $SHIPPABLE_BUILD_DIR/ssh`
`  - cp -a /tmp/ssh/00_sub $SHIPPABLE_BUILD_DIR/ssh/id_rsa` 

Dockerfile:
`VOLUME /root/.ssh`
`COPY ssh/* /root/.ssh/`
`RUN ssh-keyscan -t rsa github.com 2>&1 >> /root/.ssh/known_hosts && \`
`    cd /application && \`
`    npm install`

**Comment by abhijitkini** [comment]
Thanks @nmarshall-cst. Closing the issue. Do let us know if you have further questions.
