### ISSUE TITLE
Tagging a commit in GitHub kicks off a build

### ISSUE THREAD

**Issue by pkaminski** [Shippable/support#2579]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

As of sometime on Apr 27th, tagging a commit kicks off a build on Shippable (see, e.g., build 1046 for tag `build-1045` in https://app.shippable.com/projects/540e995e3479c5ea8f9f26ef).  This is basically issue #905, but I'm opening a new one because it appears to be a regression from previous behavior.  If it's intentional, could you please provide a switch to turn it off before changing the default?  Thanks.

**Comment by ric03uec** [comment]
@pkaminski this is definitely a regression from the expected behavior. Sorry about this. we're working on fixing this now

**Comment by ric03uec** [comment]
@pkaminski this should now be fixed. can you please confirm that tagging is not triggering any builds on shippable.
thanks

**Comment by abhijitkini** [comment]
Closing the issue. Do let us know if you are still see tagging triggers builds.

**Comment by pkaminski** [comment]
Thanks!  I'm sure it's working fine now, but I haven't been able to cut a release recently so won't be able to check until later.
