### ISSUE TITLE
Adding a custom node on AWS does not work at all

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2585]
I set up a C4 instance on AWS. I followed the instructions, but it seems the process is broken. 

1) You don't set the authorized_keys to 600 mode, so the init script can ssh to the box. I fixed that, then;
2) The init script suddenly fails with no explanation visible during the second step. See Attachment. 
![screenshot 2016-05-02 15 42 36](https://cloud.githubusercontent.com/assets/823555/14964026/e5b3a3ee-107c-11e6-93b3-89e24e77fc69.png)

**Comment by manishas** [comment]
@ric03uec can you take a look at this?

**Comment by trriplejay** [comment]
@npahucki Hello, it looks like your node is using an unsupported operating system. You can see the requirements in our documentation here: http://docs.shippable.com/ci_byoh/#minimum-requirements

We'll be opening an internal issue to link to this documentation directly from the new node page.  Sorry for the confusion!

**Comment by npahucki** [comment]
I more than met all the minimum requirements, the only thing that was different is that I used Amazon's Linux instead of Ubuntu.

**Comment by trriplejay** [comment]
The add node page has been updated to link to the more detailed documentation. closing.
