### ISSUE TITLE
Issue with Post_CI 

### ISSUE THREAD

**Issue by twillms07** [Shippable/support#2588]
### Is your request:
Unsure why this is occurring have been trying to trouble shoot all evening.
- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:
Removing intermediate container 822594125f79
Step 9 : ADD ./buildoutput/server.jar /server.jar
lstat buildoutput/server.jar: no such file or directory

- Link to the build failure
https://app.shippable.com/runs/57284b8d3145260c00550b6b
- Scripts called from the yml (optional)

**Comment by rageshkrishna** [comment]
It looks like your `build_ci` step is placing files in `./shippable/buildoutput` but your Dockerfile is trying to look at `./buildoutput`. Can you please update it to ADD files from ./shippable/buildoutput instead?

**Comment by twillms07** [comment]
Hi Regesh that worked thanks for the help.

From:  Ragesh Krishna <notifications@github.com>
Reply-To:  Shippable/support
<reply+004a65c56485ebb6c1b914a628a6a768e7af73656411490092cf0000000113401abb9
2a169ce091a3b53@reply.github.com>
Date:  Tuesday, May 3, 2016 at 12:52 AM
To:  Shippable/support <support@noreply.github.com>
Cc:  Todd Willms <twillms07@gmail.com>, Author <author@noreply.github.com>
Subject:  Re: [Shippable/support] Issue with Post_CI  (#2588)


It looks like your build_ci step is placing files in ./shippable/buildoutput
but your Dockerfile is trying to look at ./buildoutput. Can you please
update it to ADD files from ./shippable/buildoutput instead?


You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Shippable/support/issues/2588#issuecomment-216461426>

**Comment by rageshkrishna** [comment]
@twillms07 Good to know! Thanks for the update.
