### ISSUE TITLE
First level support for PHP 7

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2589]
### Is your request:
- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.
### Description of your issue:

The current approach for [PHP 7 builds on Shippable](http://docs.shippable.com/ci_languages/#running-builds-with-php7) (see #2378) is only useful for single builds with this PHP version. If you need to build against multiple PHP versions aside from PHP 7 and set up a matrix build, you cannot switch the image and thus [builds will fail partially](https://app.shippable.com/runs/57286aa5ef18f90c001485c0), e.g. when trying to install PHP extensions via `pickle`.

Thus I'd like to ask for first level support within the default Shippable PHP images.

**Comment by chrisandchris** [comment]
+1 for this

**Comment by mbrodala** [comment]
@manishas Are there some updates here?

Since you are using Ubuntu you could maybe integrate the [PHP PPA of Ondřej Surý](https://launchpad.net/~ondrej/+archive/ubuntu/php) which provides packages for PHP 5.5, 5.6, 7.0 and 7.1 including PHP extensions.

**Comment by avinci** [comment]
This was completed a while ago. Not sure if this has been resolved. We are also launching new images this weekend and you should have this. Please let us know if this is not the case

**Comment by mbrodala** [comment]
Yeah, we are actually using this for months now and I even forgot that this didn't work back then. ;-)

Thus this is resolved.
