### ISSUE TITLE
Access to SSH Key integration

### ISSUE THREAD

**Issue by ajunge** [Shippable/support#2593]
In the docs says: "Your SSH key will then be available in your build minion and you can use ssh commands in your shippable.yml." (http://docs.shippable.com/int_keys/) 
Where is that key stored?

Cannot find it

**Comment by rageshkrishna** [comment]
@ajunge The keys are loaded in to ssh-agent when the build begins so you should be able to just run whatever ssh commands you need and expect the authentication to work. If, however, you do really need the key files they are placed in the `/tmp/ssh/` directory.

**Comment by manishas** [comment]
Closing this issue since the qs has been answered. @ajunge let us know if you have any other questions.

**Comment by ajunge** [comment]
Hi @rageshkrishna , if I do a ssh-add -l I only see /tmp/ssh/00_pub and /tmp/ssh/01_deploy (maybe the names are diferent, writing without seeing) . I cannot see the SSH key I have added as an "Key Integration" in my account

**Comment by a-murphy** [comment]
Have you added the SSH key integration to the project on the settings tab and to your shippable.yml file?  Similar to [hub integrations](http://docs.shippable.com/ci_configure/#pulling-your-ci-image-from-a-docker-registry), the SSH key integration should be specified in shippable.yml like this (using the name of the integration you created):
```YML
integrations:
   key:
      - integrationName: MySSHKeyIntegration
        type: ssh-key
```

**Comment by ajunge** [comment]
@a-murphy will try. I think that is not described in the docs. Maybe an update in the docs is needed

**Comment by ajunge** [comment]
@a-murphy it worked! Key is at `/tmp/ssh/MySSHKeyIntegration`
