### ISSUE TITLE
Currently no build notifications (Slack)

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2594]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

Right now we don't see any build notifications from Shippable in our Slack, neither start nor end.

Any idea what's wrong?

**Comment by manishas** [comment]
@a-murphy we need to look into this asap

**Comment by a-murphy** [comment]
Slack messages are working again.  Sorry about that; there was a version mismatch leading to messages not being processed correctly.

**Comment by manishas** [comment]
@mbrodala i am closing this issue, but please let us know if it doesn't work for you and we'll reopen.

**Comment by mbrodala** [comment]
Looks good, the messages are back. :-)
