### ISSUE TITLE
binfmt-support to allow cross compilations for arm

### ISSUE THREAD

**Issue by encodeering** [Shippable/support#2596]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

It seems that the **binfmt_misc** module is not available, but required when using qemu (afaik), to emulate an arm cross build for docker images.

```
Setting up binfmt-support (2.1.4-1) ...
update-binfmts: warning: Couldn't load the binfmt_misc module.

...

cat: /proc/sys/fs/binfmt_misc/status: No such file or directory
.travis/prepare.sh: 6: .travis/prepare.sh: cannot create /proc/sys/fs/binfmt_misc/register: Directory nonexistent
```

Do you know an alternative solution or can tell, if it will be part of the infrastructure some day?

Thank you very much

**Comment by avinci** [comment]
@encodeering, based on my quick research we need to update the kernel etc. (I am not ARM expert)

There are 2 options, 
* One, you can run a custom machine image for your builds, if you need to change the host itself. 
* Second, You can run any Docker image on our platform, if it does not require kernel update on the host.

 I am going to close this as differed and if there is more interest in the future, we will absolutely consider adding it to our list of natively supported images.

**Comment by encodeering** [comment]
@avinci okay, thank you for the reply. I'll check then from time to time or do some promotion on this :)
