### ISSUE TITLE
Android Build Fails, Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by shgharib** [Shippable/support#2597]
Hi, android build fails

> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

I already added all gradle stuff (except .gradle) to repository.
```

language: java
jdk:
    - oraclejdk7
install:
    - sudo apt-get update
    - sudo apt-get install -y lib32stdc++6 lib32z1
    - chmod +x ./gradlew
    - ./gradlew clean build
script:
    - ./gradlew check
```
How fix it ?

**Comment by rageshkrishna** [comment]
Hi @shgharib. I'm no expert on java or android, but from researching this online it seems that this usually happens if gradle-wrapper.jar is not checked in to your git repository. Can you please check if http://stackoverflow.com/a/31622432/34985 helps?

**Comment by shgharib** [comment]
Thank you for your concern, as I said I already added gradle-wrapper.jar to repository, I build my project successfully with codeship but same project with shippable fails (with same shell stuffs) . what is the problem?

**Comment by rageshkrishna** [comment]
Do you mind if I trigger a few builds on your project to debug this further?

**Comment by shgharib** [comment]
no problem, thank you.

**Comment by rageshkrishna** [comment]
@shgharib I think I've figured out where the problem is. We seem to be cloning GitLab projects to an incorrect directory. I'll update this issue as soon as we have a resolution for this.

**Comment by shrivara** [comment]
@shgharib This should be resolved now. Let us know if you run into this again.

**Comment by shgharib** [comment]
It's fixed, Thank you.
