### ISSUE TITLE
UI shows full information only for a subset of projects due to runStatus incomplete output

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2598]
### Is your request:

- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

#### Steps to reproduce

Make an API call to `/subscriptions/:id/runStatus` to go to our [subscription page](https://app.shippable.com/subscriptions/547c792bd46935d5fbbf0b11) (which calls runStatus itself).

#### Actual results

Since Friday 6th May 2016 (the issue started between 14:44 UTC and 15:44 UTC), the API calls to `/subscriptions/:id/runStatus` only return a subset of projects: the ones that we don't test daily. All other projects show up as gray (.ship-text-default: #a1abab) with zero builds:

![capture d ecran 2016-05-09 a 09 58 28](https://cloud.githubusercontent.com/assets/42327/15104742/9ece9d44-15cc-11e6-907e-ca18ccca5f27.png)

However, looking at the project history (https://app.shippable.com/projects/54bfbb325ab6cc13528948f0 here) does show all builds as expected.

#### Expected results

`/subscriptions/:id/runStatus` should have returned all projects, and they should appear correctly in the Shippable UI.

**Comment by manishas** [comment]
@amalfra can you look into this asap?

**Comment by kanthchandra** [comment]
Hi @pquentin, can you please try now and let us know if this works for you?

Additionally now you can also configure the branches for which you would like to see the latest run status in the summary tab. You can do this by updating the dashboard settings in the project setting page.

**Comment by pquentin** [comment]
Thanks, it works!

I'm not sure if I understood your suggestion, but I always want to show the Bitbucket default branch, because we don't want to have to specify the branch twice, both in Bitbucket and Shippable.
