### ISSUE TITLE
API: runStatus shows an old run for one project

### ISSUE THREAD

**Issue by pquentin** [Shippable/support#2599]
### Is your request:

- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue

I don't think it's the same issue than https://github.com/Shippable/support/issues/2598 since I've experienced this one before.

#### Steps to reproduce

Make an API call to `/subscriptions/:id/runStatus`.

(This happened once already, and I think this happens only when Shippable syncs a project that is currently building. Maybe this will help reproducing/understanding the issue.)

#### Actual result

The last build of https://app.shippable.com/projects/54bfe6635ab6cc1352894e74 is 2016-04-26.

#### Expected result

Since this project was built a few minutes ago, `runStatus` should show the actual last build, not a build that is nearly two weeks old.
I would have expected that syncing the project fixes the issue. It did fix the issue the last time this occurred, but not this time.

(This blocks our continuous integration that ensures all builds are performed every day. I wished this was a part of Shippable, this has been a great source of frustration since we started doing this in 2015.)

**Comment by amalfra** [comment]
Hi @pquentin, The latest build seems to be on branch named 'develop'. If you navigate to your projects settings(https://app.shippable.com/projects/54bfe6635ab6cc1352894e74/settings) and scroll down,there is a panel with 'Dashboard Settings' heading which lets you configure branches from which you need latest build to be shown in dashboard pages. Once you add 'develop' branch you should be seeing the latest builds too. Let us know if that doesn't work.

**Comment by rageshkrishna** [comment]
@pquentin It looks like the setting got messed up when we did a migration for the new feature that we added last week, where you can manually pick one or more branches for which you want to see build status even if they're not the default on the source provider.

I have manually reset your project's settings to reflect the default branch settings from your source provider. Sorry about the error.

Please let me know if you're still seeing any issues.

**Comment by pquentin** [comment]
Thanks, that fixed it!
