### ISSUE TITLE
Setup of nightly builds

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#2600]
### Is your request:
- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.
### Description of your issue:

I would love to be able to setup nightly builds either via the Shippable homepage or Shippable API instead of requiring a seperate server for this (e.g via a cron job and the Shippable API). Thanks.

**Comment by mattclay** [comment]
This would be especially useful for running "heavier" builds, such as a normal build matrix with code coverage enabled (which might increase the build time by 6x or more). To do that there would need to be an environment variable set which indicated the job was a scheduled job.

**Comment by jeppefrandsen** [comment]
Any news regarding this feature? Thanks.

Kind Regards,
Jeppe, Bang & Olufsen

**Comment by avinci** [comment]
This can be achieved by using our pipelines. 
- http://docs.shippable.com/pipelines/resources/time/
- http://docs.shippable.com/pipelines/jobs/runCI/

We have added 1 resource that is a timer resource which accepts cron like syntax and periodically triggers the jobs following it

In the most recent release we introduced a runCI job. This is a native way to add your CI projects into a pipeline workflow. 

Using a combination of the above 2 features, you can achieve your nightly scheduled builds. 

@chetantarale please write a blog and sample code to demonstrate it.

**Comment by danielmenezesbr** [comment]
@avinci 
This feature is available for non paid accounts?

The documentation [1] says "Make sure your subscription has the isNewPipeline: true"

[1] https://github.com/shippableSamples/sample_pipelines

**Comment by manishas** [comment]
@danielmenezesbr that README file in the sample is outdated. This is available to all accounts.

Please check out the blog at http://blog.shippable.com/setup-nightly-builds-on-shippable

**Comment by danielmenezesbr** [comment]
@manishas Thanks!

In your example to trigger a job everyday at 22.00 hours everyday, I think you need to replace interval to "**0** 0 22 * *"

**Comment by manishas** [comment]
Cron format is explained in detail here http://www.nncron.ru/help/EN/working/cron-format.htm

So to trigger at 10pm every day it should be 

0 22 0 0 0

**Comment by manishas** [comment]
Closing this since the blog has been published.
