### ISSUE TITLE
Improve API "Trigger a run" documentation

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2601]
### Is your request:

- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.

### Description of your issue:

I would like to trigger runs programmatically, on a specific branch and optionally pass environment variables. The API documentation has http://docs.shippable.com/api/#trigger-a-new-run which seems promising.

The section does not tell how to run for a specific branch, but looking at API calls done by shippable applications it seems posting "branchName" should do it.

About the environment variables, the documentation states:
```
You can also inject global environment variables into the new build by specifying key-value pairs in the request body of the POST. These key-value pairs have to be set in the globalEnv property.
```
and then shows some pseudo-JSON:
```
{
  "globalEnv": {
    "FOO": "bar",
    "FIZZ": "buzz"
  }
}
```
I am confused. Does it mean this is a JSON payload to be posted? In that case, is there a way to specify the branch I want to build?

**Comment by pmezard** [comment]
Apparently I can add "branchName" key to the JSON payload.

Wouldn't it be worth documenting?

**Comment by oppianmatt** [comment]
yep, same issue here https://github.com/Shippable/support/issues/2575

needs documentation that you can trigger specific builds

**Comment by manishas** [comment]
yes we should absolutely update the documentation. thanks for the suggestion!

**Comment by manishas** [comment]
I have updated the docs with details on how to specify a branch and also that the snippet is a JSON payload. Updated docs are here - http://docs.shippable.com/api/#trigger-a-new-run

**Comment by manishas** [comment]
closing.
