### ISSUE TITLE
Google Cloud Platform Integration 

### ISSUE THREAD

**Issue by somenathghosh** [Shippable/support#2602]
Getting following error while adding environment 

```
(Id: 4005) Adapter call failed for getRegions
verbose: common|gcp|validateAccountIntegration|_getRegions
"403"
```

These are the steps I have followed:

1. Crated Account in GKE
2. Created Service Account
3. Added JSON key to Shippable
4. Tried to add Environment and getting that error. 

I think I am doing something wrong. Please help.

**Comment by a-murphy** [comment]
I just tried creating a new key (and a new service account) following the [documentation](https://cloud.google.com/storage/docs/authentication#service_accounts) and did not find any errors.  In your case, it looks like the credentials were valid, but we couldn't use them to get the list of zones.  Did you change the permissions on your service account?

**Comment by somenathghosh** [comment]
I tried to provide permission as Owner to service account. It did not work. Do I have to change anything in Security and setting in GCP ?

**Comment by a-murphy** [comment]
You shouldn't have to change anything; that's why I asked if you had.  A new service account should have the right permissions.  Mine has the "editor" role on the "IAM" tab and no "members" listed under the service account if I go to configure the permissions there.

**Comment by somenathghosh** [comment]
I tried both. First I had default role(which is editor) and next I tried with role change. None of them worked.

**Comment by a-murphy** [comment]
I've found a way to reproduce your error (disabling the Google Compute Engine API).  Could you go to "API Manager" and check that the "Google Compute Engine API" is enabled?

**Comment by somenathghosh** [comment]
Yes that was it. I was not sure why that was disabled. Thanks for your help.
