### ISSUE TITLE
Organization member not seeing private repos

### ISSUE THREAD

**Issue by asans** [Shippable/support#2603]
### Is your request:

- [ X ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:

We have a member who's also an owner of the organization team.  Going to Manage Access for his account shows that he has admin access to all repos.  However, when he is on shippable, he only sees public repositories and not the private repos.  Therefore, he's not able to access the private repo builds on shippable due to this.

The changes in permission hasn't been changed for close to a year now.  How do we get shippable to see his permissions?  

One thing that I noticed differently is that his profile is private compared to mine.  But considering that he's logged in using his credentials, I don't think this matters.

As an org owner, he does not need to be placed in any of the repositories to have access to them; he has full access to all repos.

Please advise.

**Comment by manishas** [comment]
@asans he probably hasn't enabled access for private repositories on Shippable. By default, when someone signs in, we ask for access to public repositories and private repos need to be turned on.

To turn on private repos, he can go to his Shippable account settings (gear icon on top navbar), scroll to the `Git identities` section, and enable private repos. After enabling this, he should click on the 'Sync' button on the account settings page. He should see private repos after that.

Let me know if this works. Thanks!

**Comment by manishas** [comment]
@asans I am closing this issue, but please let us know if the suggestion above did not work and we'll take another look into this.
