### ISSUE TITLE
Builds timeout with PhantomJS

### ISSUE THREAD

**Issue by Thau** [Shippable/support#2604]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:
Hello, we seem to be having some problem with our functional tests that make them timeout. They work on development machines without any kind of problem, so we don't know where to debug anymore. I don't think we're running out of memory because on our dev machines the tests don't use more than 500MB. Could you please help us understand what's happening?

Here's a link to one of these builds: https://app.shippable.com/runs/5732f4432e65390c009ac4ed

Thank you.

**Comment by trriplejay** [comment]
could it be CPU bottleneck? our build machines are c4.large on AWS, which is defined as:
c4.large (8 ECUs, 2 vCPUs, 2.9 GHz, Intel Xeon E5-2666v3, 3.75 GiB memory, EBS only)

I don't see anything obviously wrong in your builds, it simply looks like the tests are taking a long time.  You say it works on development machines: how long does a typical build take in those cases? Is there a large dependency on network speed or any other external factors?

**Comment by trriplejay** [comment]
another possibility I got from a response in this thread: http://stackoverflow.com/questions/13144292/phantomjs-works-but-is-very-slow

could your test be trying to connect to something that isn't there, thus hitting a timeout for those bad requests, and adding several minutes for each timed out request?

The above linked thread suggests reducing the default timeout value of requests to something like 3000ms. Might be worth a try.

**Comment by abhijitkini** [comment]
Closing the issue as resolved. If you have further questions on this issue, please re-open.
