### ISSUE TITLE
Untar re-exec error: exit status 1: output: write /usr/bin/smbpasswd: no space left on device

### ISSUE THREAD

**Issue by n0mer** [Shippable/support#2605]
https://app.shippable.com/runs/5733373d46f44c0d0082d078
{code}
9dff504e9ef1: Error downloading dependent layers
63655319ed5c: Error pulling image (latest) from docker.io/shippable/minv2, endpoint: https://registry-1.docker.io/v1/, Untar re-exec error: exit status 1: output: write /usr/bin/smbpasswd: no space left on device
63655319ed5c: Error pulling image (latest) from docker.io/shippable/minv2, Untar re-exec error: exit status 1: output: write /usr/bin/smbpasswd: no space left on device
Error pulling image (latest) from docker.io/shippable/minv2, Untar re-exec error: exit status 1: output: write /usr/bin/smbpasswd: no space left on device
{code}

**Comment by a-murphy** [comment]
The ```Job node info``` section of your logs shows that almost all of the memory is in use and you have some extra containers running on your build host.  If you started some containers that you don't need, those should probably be stopped and removed.  You're also pulling an almost 13 GB image, which is close to the amount of space available, so it might be a good idea to create a little more space on your build host.  Removing unused images and any old build containers usually helps.

**Comment by avinci** [comment]
@n0mer our minv2 image is already on the AMI. I am not sure you need to manually pull this yourself. Let us know if you need anything more to be looked into.
