### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by jspanjers** [Shippable/support#2606]
Are there any plans to provide base images using the latest Ubuntu LTS 16.04?

**Comment by avinci** [comment]
We will do this. Should be done in the next couple of weeks.

**Comment by jspanjers** [comment]
Any progress on this yet?

**Comment by jspanjers** [comment]
Any news?

**Comment by manishas** [comment]
ETA for this is 3 weeks.

**Comment by gitglacier** [comment]
It's a day past three weeks. :)
https://github.com/dry-dock/u16phpall seems to be empty compared to https://github.com/dry-dock/u14phpall

**Comment by jamesalton** [comment]
@manishas 
It's a day past three weeks. :)
https://github.com/dry-dock/u16phpall seems to be empty compared to https://github.com/dry-dock/u14phpall

**Comment by manishas** [comment]
This is in progress. I'll have an update in the next couple of days.

**Comment by AndreCimander** [comment]
Any updates? Pulling from u16 images still fails:

> ff618ffc57e6: Error downloading dependent layers
> 5ca6971b25b4: Error pulling image (tip) from docker.io/drydock/u16pytall, endpoint: https://registry-1.docker.io/v1/, Untar re-exec error: exit status 1: output: unexpected EOF
> 5ca6971b25b4: Error pulling image (tip) from docker.io/drydock/u16pytall, Untar re-exec error: exit status 1: output: unexpected EOF
> Error pulling image (tip) from docker.io/drydock/u16pytall, Untar re-exec error: exit status 1: output: unexpected EOF

**Comment by avinci** [comment]
this is launching this week. adding it to 5.3.1

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image.
