### ISSUE TITLE
BASE_BRANCH and HEAD_BRANCH env vars not returning values

### ISSUE THREAD

**Issue by hunt3ri** [Shippable/support#2607]
I have the following output in a deploy script and both are not outputing any values:

echo Target Branch is $BASE_BRANCH
echo Head Branch is $HEAD_BRANCH

Neither env variable returns a value, however $BRANCH and $IS_PULL_REQUEST do

Thanks

**Comment by a-murphy** [comment]
```$BASE_BRANCH``` and ```$HEAD_BRANCH``` are only defined for pull request builds.  If ```$IS_PULL_REQUEST``` is true, then you can use those.  But, if ```$IS_PULL_REQUEST``` is false, then ```$BRANCH``` is the only available branch variable.  ```$BRANCH``` is defined for both pull request and commit builds and will be the same as ```$BASE_BRANCH``` in a pull request build.

**Comment by hunt3ri** [comment]
Ahh thanks, that clarifies things :+1:
