### ISSUE TITLE
Docker in Docker?

### ISSUE THREAD

**Issue by kofalt** [Shippable/support#261]
I don't suppose Shippable has support for running a docker daemon?
[Hroot](https://github.com/polydawn/hroot) is a tool that uses Docker, and as such is mainly tested by using Hroot to launch containers.

After a few tries I've forked it [here](https://github.com/kofalt/hroot) for testing without bugging our watch-ees.
I'm unable to get Docker to play nice within Travis or Shippable.

**Comment by rarkins** [comment]
@kofalt @avdrav I have the same need as this. I was really under the impression this would be supported "soon" but it's been a year and still seems no minion supports running docker inside it, unless I'm misunderstood. @kofalt did you succeed with this or give up hope?

**Comment by kofalt** [comment]
Really this is a feature of the runtime provider, not the CI provider - there's no great way to recursively Docker, and so CI providers using a Docker-like runtime won't have many options for doing so.

In our case, we ended up sticking with a runtime that could allow us to launch containers - a full VM via Travis. In my conversation with @avdrav et al, we agreed this was something of an edge case.

If you're in a position that would allow the CI provider to launch your containers, maybe have a look at Shippable's [formations](http://docs.shippable.com/formations_overview/) - they support spinning up several simultaneous images to run your tests. If you can use Shippable, I recommend their services: in particular the latency from commit-to-launch was superb.

Only if you're launching containers explicitly as part of your project, as Hroot was, will the runtime provider actually be an issue for you. If it is, I'd be curious what you're working on :)

**Comment by rarkins** [comment]
@kofalt I don't myself need "docker in docker". I just need container launching support inside minions, like it sounds like you did. 

I think this issue should be closed seeing as there is apparently not any plan by shippable to allow customers to arbitrarily launch their own docker containers inside minions.

**Comment by manishas** [comment]
@rarkins our minions are docker containers. so if you want to launch a container inside a minion, you're asking for docker-in-docker.

That being said, your feedback on Formations was very helpful. We'll soon make it easy for customers to customize their container sizes which will help make it compelling for someone with your scenario.

**Comment by manishas** [comment]
Closing this issue. We do not support docker in docker as of today. However, customer wanting to spin up topologies for their docker apps can use Shippable Formations.
