### ISSUE TITLE
Project is not listed by API /projects call

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2610]
### Is your request:

- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.

### Description of your issue:

Hello,

I have registered a new bitbucket project, it builds fine but I cannot list it with the API. SubscriptionId is listed in:

https://app.shippable.com/subscriptions/547c792bd46935d5fbbf0b11

The project is "clmake-test" and a successful build is here:

https://app.shippable.com/runs/5733475da1e3550c005172d7

The API call is a simple /projects?subscriptionId=xxx. It works with the other projects. 

Random ideas:
- Are /projects result paginated?
- Could it be the project default branch having never built make the project disappear from the list?

**Comment by kanthchandra** [comment]
Hi @pmezard , We do not paginate the /projects route and can you provide me with more details so that I can debug this?

1. when you make a call to https://api.shippable.com/projects?subscriptionIds=547c792bd46935d5fbbf0b11 how many projects are being returned to you?
2. Can you see this project in the subscriptions page summary tab?

**Comment by pmezard** [comment]
1. I see 152 projects. And indeed, playing with (undocumented?) "skip" only reduces that count so pagination is out of question.
2. Yes I see the develop build in "https://app.shippable.com/subscriptions/547c792bd46935d5fbbf0b11"

**Comment by pmezard** [comment]
I tried triggering a build on this project and it fails too with "401 Client Error: Unauthorized for url: https://api.shippable.com/projects/573345902a8192902e1fa97d/newBuild".

If I try the same thing with another project, listed by "/projects", it works. At least the API is consistent.

**Comment by kanthchandra** [comment]
That means it's a permissions issue. Can you please force sync your account in the account settings page and try? Everything should work after that. If it doesn't work we will investigate this further. Thanks.

**Comment by pmezard** [comment]
I clicked on "Sync" in the first section of the first tab of "Account Settings". It changed nothing.

**Comment by kanthchandra** [comment]
@pmezard Can you try now and see if it works? I synced all the permissions for this projects.

**Comment by pmezard** [comment]
It works, thanks. Any what happened? Did I do something wrong when creating it?

**Comment by kanthchandra** [comment]
Hi @pmezard, were you using the token generated from your account? or the token generated from someone else's account (who has access to that particular subscription)?

**Comment by pmezard** [comment]
That is correct, this token is used for build automation. It should work though, right?

**Comment by manishas** [comment]
@pmezard the token that is being used for your build automation wasn't synced and this was causing the problem. Ideally you should use your own token so that you can sync your account as needed.

**Comment by manishas** [comment]
closing this issue since the problem has been addressed.
