### ISSUE TITLE
Deploy to ECS not working after you removed 'stop' 'start' buttons

### ISSUE THREAD

**Issue by cratz** [Shippable/support#2612]
### Is your request:

- [ x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

We currently use shippable to deploy 2 services on ECS.
We always had to 'stop'  and after it was stopped we had to use 'start'.
Reason for this: deploy button was never working since you only try to update service with new task instead of stopping current running task and start new task version after current task was  successfully stopped.
It is not possible to start a new version of the task without stopping running one since they use the same port.

Could you plz re add start, stop button?
and | or
Fix deploy action that it stops current task and start new one afterwards?

**Comment by stephanielingwood** [comment]
Hi @cratz,

Thanks for the question. Yes, we recently changed the stop/start button to a scale button, to more closely reflect what's happening on the provider (ECS, in your case). 

Scaling to 0 will achieve the same result as the previous 'stop' button; on ECS, this will set your desiredCount for the service to 0. From there, you can deploy a new manifest/replica count on the configuration tab, which will update the task definition and desiredCount. Or, you can scale the service back up to your desired number of replicas, which would have the same effect as the previous start button.

Hope this helps! Let us know if you have any other questions.

**Comment by manishas** [comment]
we are updating the documentation around this since that was a miss at our end. Thanks!

**Comment by cratz** [comment]
Thank you very much for the information works for us.

Is there any chance that you will change the behavior of the deploy button that it will stop and start the service automatically?

**Comment by stephanielingwood** [comment]
@cratz glad it works for you. As for the behavior of the deploy button, we don't plan on changing that in the near future. We'll mark this as a feature request, though, and may re-evaluate based on customer demand.

**Comment by avinci** [comment]
closing it as deferred and will reopen if we change our design decision.
