### ISSUE TITLE
How can I specify the logConfiguration parameter for an image?

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#2613]
In AWS Task Definitions, you can specify an element called logConfiguration to specify what logging providers get used. I don't see any place to specify this - am I simply missing this or does this feature not exist?

**Comment by trriplejay** [comment]
This is not currently supported. I'll mark as a feature request.

**Comment by npahucki** [comment]
Bummer. This is needed so that i can use the awslogs Docker driver and have my image logs end up in CloudWatch without needing additional processes that ship the docker logs to the CloudWatch. 

Thanks!

**Comment by npahucki** [comment]
Any news on this!?

**Comment by trriplejay** [comment]
We'll have some new on this by the end of the week!

**Comment by manishas** [comment]
This has been addressed in the brand new pipelines unveiled last week. 

@npahucki you will receive a couple of emails about the release this week, but in a nutshell, we have moved to a yml based format for pipelines. Check it out at:

[CD Pipelines overview](http://docs.shippable.com/pipelines/overview/)
[Getting started](http://docs.shippable.com/pipelines/gettingStarted/)
[Sample tutorial](http://docs.shippable.com/tutorials/pipelines/samplePipeline/)

**Comment by manishas** [comment]
Specifically, the dockerOptions resource supports logConfiguration: http://docs.shippable.com/pipelines/resources/dockerOptions/
