### ISSUE TITLE
Stuck at waiting

### ISSUE THREAD

**Issue by oneleft** [Shippable/support#2614]
I have updated my shippable.yml but the build appears to be stuck at waiting...

**Comment by manishas** [comment]
@oneleft we were investigating an issue with our queuing and it is now resolved. Can you cancel the build and try running one more?

**Comment by oneleft** [comment]
It's running now

**Comment by manishas** [comment]
Thanks for confirming. I am closing this issue since everything is back to normal.

**Comment by gnzzz** [comment]
@manishas I saw the same issue yesterday at the same time as @oneleft and I'm seeing it again this morning. Are you having problems with your queuing again?

For more info, I'm seeing a javascript error when I go in to the build that should be triggered:
```javascript
lib.min.js:21 TypeError: Cannot read property 'projectId' of undefined
    at t (app.min.js:8)
    at lib.min.js:5
    at lib.min.js:5
    at lib.min.js:5
    at g (lib.min.js:5)
    at d.each (lib.min.js:5)
    at o (lib.min.js:5)
    at Object.map (lib.min.js:5)
    at t (lib.min.js:5)
    at Object.d.parallel (lib.min.js:5)
```

**Comment by manishas** [comment]
@trriplejay can you take a look?

**Comment by gnzzz** [comment]
@manishas I just canceled the build and tried it again. It's not building yet, but looks a bit more normal.

**Comment by manishas** [comment]
everything should be back to normal now. please let us know if you run into any more issues. thanks!
