### ISSUE TITLE
Manually decrypt secure environment variables

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2618]
### Is your request:
- [x] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [ ] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.
### Description of your issue:

I would like to move as much as possible of our build configurations to a central location for maintenance purposes. For this I would also like to provide secure environment variables centrally.

Is there a way to manually decrypt a given encrypted environment variable string during build?

**Comment by avinci** [comment]
ahh i think we cannot right now. We are doing a new feature to centrally give you this capability. Are you interested to talk further about this and beta test this feature?

**Comment by mbrodala** [comment]
@avinci Sure thing, let me know how to continue here. :-)

**Comment by avinci** [comment]
Can we talk sometime tomorrow? Not sure what timezone you are in. But I can do anytime from 10am to 9pm IST.

**Comment by mbrodala** [comment]
@avinci CEST, so your time would be 6am to 5pm here. Make that 11am to 5pm (3pm to 9pm IST) and we can talk. :-)

**Comment by avinci** [comment]
Sorry, I missed this. We are adding a feature where only owners can see decrypted variables. That should solve your short term issue. The bigger change we are doing is that we are going to be offering a central config management & service discovery feature. This is already in development and wanted to get a customer feedback on our design...

Does today same time work for you?

**Comment by mbrodala** [comment]
@avinci What is "see" exactly in this context? In the subscription settings? In the build output? I'm not sure how that'll help me with my plan. ;-)

The new feature sounds interesting and I'm certain I can add two cents or more on that. Yes, today is similar so hit me whenever your can.

**Comment by mbrodala** [comment]
I saw that a decryption feature has been added to project settings. That'd help recovering encrypted environment variables but doesn't exactly cover my usecase.

Notice that my original requirement was sharing a common Github OAuth token between many projects. This is now obsolete thanks to [Github dropping the rate limiting](https://github.com/composer/composer/issues/4884#issuecomment-195229989) for dist archive downloads via their API.

**Comment by manishas** [comment]
@mbrodala is there still a feature request here or can we close this?

**Comment by mbrodala** [comment]
@manishas Yes, the feature would be a CLI client which allows for decrypting environment variables which could then be exported manually afterwards.

Of course I'm open for suggestions how to solve this in a better fashion. :-)

**Comment by mbrodala** [comment]
Another option for us would be a feature where one can define secure environment variables on a subscription level. This could be implemented through integrations which are already configured per subscription instead of project.

**Comment by mbrodala** [comment]
Trying to continue here: could you elaborate on how the values are encrypted exactly? Could I e.g. decrypt them via GPG CLI or similar language functionality?

**Comment by mbrodala** [comment]
Is there really no way to achieve this? I assume I'll have to build something myself using the [PEM key integration](http://docs.shippable.com/integrations/keys/pem/) in that case.

**Comment by kanthchandra** [comment]
@mbrodala is this your use case? Let's say you have 2 projects A and B which belong to the same subscription and you have encrypted  let's say `AWS_ACCESS_KEY=abc` using the shippable UI and you have the encrypted string with you. But you dont want to put it in the secure env section instead you want to decrypt this string at run time while running your build manually whenever you need it right?

**Comment by mbrodala** [comment]
Correct. The idea was to use the Shippable UI to encrypt values and then add the encrypted value to a custom config within the repository. This custom config could then be evaluated and decrypted during build.

**Comment by kanthchandra** [comment]
OK I have some ideas around this (I cannot gurantee that it'll work), let me discuss this with @avinci and @manishas and get back to you.

**Comment by avinci** [comment]
Did we get this resolved?

**Comment by kanthchandra** [comment]
@avinci @mbrodala sorry, this ran out of my radar. There is a way with which you can do this, I will put together a small project by tomorrow to achieve this.

1. In short we do have an API to decrypt the secure env (but this needs the subscription owners token to make an api call).
2. We can achieve the decryption in the build itself but it will need some scripts. So I'll put together the project to do this.

**Comment by rageshkrishna** [comment]
@kanthchandra I believe we have a script that can do this in a generalized way. Maybe we should add it to the new images so it's available everywhere.

**Comment by avinci** [comment]
thats a better approach. We should create something like shippable_decrypt

**Comment by mbrodala** [comment]
Thanks for the info so far. :-)

**Comment by rageshkrishna** [comment]
This will be available on Monday. `shippable_decrypt` will be available on the new images to help with local decryption. I'll update this issue once the images are live and docs are available.

**Comment by avinci** [comment]
this has been in production for a while. closing this.
