### ISSUE TITLE
builds queuing up but aren't running

### ISSUE THREAD

**Issue by jamesmk** [Shippable/support#2619]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [x] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

Our builds are queuing up, but none of them are running. It says we have 5 available minions and currently 4 builds in the queue marked "waiting".

https://app.shippable.com/subscriptions/540f392a586ac5d7e36513c3

**Comment by manishas** [comment]
we're looking into this....

**Comment by manishas** [comment]
@jamesmk this should be fixed now. Builds that were stuck in queued state were canceled so you will need to re-trigger it. Let me know if it works.
