### ISSUE TITLE
Can't delete pipeline or environment because they depend on each other

### ISSUE THREAD

**Issue by seanxe** [Shippable/support#2620]
### Is your request:

- [ ] A feature request: The feature you want currently does not exist. If implemented, will provide additional value to you.
- [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
- [ ] A question: A non-technical question such as billing.

### Description of your issue:

Title says it all really. I'm using google container engine. Trying to delete a pipeline, but the button is greyed out and says:

"This pipeline is active in the following environments. It must be stopped before the pipeline can be deleted."

Then, I go to an environment, and the delete button is also greyed out and says:

"The following pipelines are active in this environment. They must be stopped before the environment can be deleted."

Can't see any sort of "stop" or "un-deploy" buttons or anything...

**Comment by manishas** [comment]
@seanxe sorry about this. we made a recent change to our pipelines UI and this text needs to be updated.

Here is how you can 'stop' a pipeline in your environment: Go to the pipeline status in that environment and use the 'Scale' action to scale to zero.

![image](https://cloud.githubusercontent.com/assets/2983749/15269470/56db145e-19b4-11e6-946b-8db287ed812c.png)

This will stop all instances of the pipeline in that environment. You can then delete the environment, and then the pipeline.

Let me know if it works for you.

**Comment by seanxe** [comment]
@manishas awesome - that worked!

thanks for the quick response as well.
