### ISSUE TITLE
Github checks not triggered

### ISSUE THREAD

**Issue by danielfriis** [Shippable/support#2622]
When I submit pull requests, Github checks are not triggered. Shippable runs the tests alright, but the status and results are not showed in github.

Github PR: https://github.com/space10-community/space10/pull/51
Shippable run: https://app.shippable.com/runs/573867f556620f0d00136efc

**Comment by kanthchandra** [comment]
Hi @danielfriis, I looked at the logs for your project and it looks like github is sending us this a not found message. My guess is that we are not encoding the branch name (df/fix-shippable) correctly. We will investigate this further and will get back to you as soon as we have something substantial. 
```
 { 
    message: 'Not Found',
    documentation_url: 'https://developer.github.com/v3'
 }
```

**Comment by kanthchandra** [comment]
Hi @danielfriis, we investigated this today and found that one of the collaborators for the project with username `kaspernj` does not have the required scopes to update the project status and as a result github was giving a not found error.

We use a random account that has access to the project to update the commit status on github. So @kaspernj will have to revoke access to shippable here https://github.com/settings/applications and then login back. After this everything should start to work. We also recommend our users to not update any of the scopes.

Please let us know if you still run into this after the reauthorization. We will take a deeper look at this.

**Comment by kaspernj** [comment]
@danielfriis I have revoked Shippable and logged back in. Please check if it works now :-)

**Comment by danielfriis** [comment]
@kanthchandra Thanks a lot - that fixed it! cc @kaspernj
