### ISSUE TITLE
Code Coverage For Android projects

### ISSUE THREAD

**Issue by shgharib** [Shippable/support#2625]
Hi again, How can I use shippable code coverage for android project? this script does nothing, the coverage badge still shows "unknown".
```
before_script:
    - mkdir -p shippable/testresults
script:
    - ./gradlew check jacocoTestReport
after_script:
    - cp -r ${appName}/build/test-results/* shippable/testresults/
```

**Comment by a-murphy** [comment]
It looks like you are coping the test results correctly and that report is being parsed.  Code coverage is a separate report and should be copied to ```shippable/codecoverage```.  We support coverage reports in Cobertura XML format.  Although not using Gradle, [this sample Java project](https://github.com/shippableSamples/sample-java-mysql-openshift) has code coverage with Cobertura.

**Comment by shgharib** [comment]
Thank you @a-murphy, I found [gradle-cobertura-plugin](https://github.com/stevesaliman/gradle-cobertura-plugin) and better solution [codecov](https://codecov.io).
