### ISSUE TITLE
Browser tests random not triggered in build process

### ISSUE THREAD

**Issue by tim0t** [Shippable/support#2627]
### Description of your issue:

We experience some problems with random not starting browser tests. But we can't really figure out why and console logs are not conclusive. Could this be due to a memory problem?

Here are some links to builds that didn't start the browser test:
- https://app.shippable.com/runs/573b6e0412be900d006e7922 (tab 2)
- https://app.shippable.com/runs/573c12e48706ea0c006141e3 (tab 5)
- https://app.shippable.com/runs/57370b860720110c0007e960 (tab 6)

All these builds end with this about the same failure message:

     Testem Tests / undefined / Browser "google-chrome --user-data-dir=/tmp/testem-2107.chrome --no-default-browser-check --no-first-run --ignore-certificate-errors --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:54443/2107/tests/index.html?hidepassed=&filter=suite2" failed to connect. testem.js not loaded? Stderr: Xlib: extension "RANDR" missing on display ":99". [614:642:0517/113535:ERROR:bus.cc(432)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory Xlib: extension "RANDR" missing on display ":99". libGL error: failed to load driver: swrast (google-chrome:614): GConf-WARNING **: Client failed to connect to the D-BUS daemon: //bin/dbus-launch terminated abnormally without any error message (google-chrome:614): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Failed to execute child process "dbus-launch" (No such file or directory) [614:653:0517/113536:ERROR:browser_gpu_channel_host_factory.cc(120)] Failed to launch GPU process.

This is our shippable.yml:

    language: node_js
    env:
    global:
      - secure: 
    matrix:
      - DEPLOY=1
      - TEST_FILTER=JSHint
      - TEST_FILTER=Unit
      - TEST_FILTER=suite1
      - TEST_FILTER=suite2
      - TEST_FILTER=suite3
    branches:
    only:
    	- master
    build:
    cache: true
    cache_dir_list:
      - $SHIPPABLE_BUILD_DIR/unicorn-leerling/node_modules
      - $SHIPPABLE_BUILD_DIR/unicorn-leerling/bower_components
    pre_ci_boot:
    	image_name: quay.io/gynzy/docker-drone-node
    	image_tag: master
    	pull: true
    	options: "-e HOME=/root"
    ci:
    	- chmod 777 ./ci/*.sh
    	- bash ./ci/npm-install.sh
    	- bash ./ci/bower-install.sh
    	- bash ./ci/modify-git-checkout.sh
    	- bash ./ci/test.sh
    	- bash ./ci/deploy.sh
    	- bash ./ci/generateDocs.sh
    integrations:
    hub:
    	- integrationName: "Quay Gynzy"
    	  type: quay.io
    	  branches:
    		  only:
    			- master

**Comment by a-murphy** [comment]
It doesn't look like a typical memory problem.  Most of the issues we see about running out of memory will occur in the middle of a test, not starting the tests.  Have you checked if something might not be getting installed, or if you're not waiting long enough for the browser to start?

**Comment by manishas** [comment]
@tim0t we have been unable to detect why this might be happening. Please let us know if you could debug this further...

**Comment by ralfschimmel** [comment]
More debugging, exit moment of browser is random, seems like a true OOM case.
It is in the middle of a test, but within xfvb, thus the error thrown is xfvb running out of memory as it seems. Tabs randomly succeed and fail on rebuilds. Please investigate, this is not workable if we cannot run basic JS tests.

https://app.shippable.com/runs/57436a46a7f3850d00e8bd2c

# 1
 Testem Tests / Chrome 50.0 / Browser "google-chrome --user-data-dir=/tmp/testem-9789.chrome --no-default-browser-check --no-first-run --ignore-certificate-errors --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:58544/9789/tests/index.html?hidepassed=&filter=suite3" exited unexpectedly with exit code null. Stderr: Xlib: extension "RANDR" missing on display ":1". [617:636:0523/205455:ERROR:bus.cc(432)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory Xlib: extension "RANDR" missing on display ":1". [663:663:0523/205501:ERROR:sandbox_linux.cc(334)] InitializeSandbox() called with multiple threads in process gpu-process (google-chrome:617): GConf-WARNING **: Client failed to connect to the D-BUS daemon: //bin/dbus-launch terminated abnormally without any error message (google-chrome:617): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Failed to execute child process "dbus-launch" (No such file or directory) ALSA lib confmisc.c:768:(parse_card) cannot find card '0' ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory ALSA lib conf.c:4727:(snd_config_expand) Evaluate error: No such file or directory ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM default ALSA lib confmisc.c:768:(parse_card) cannot find card '0' ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory ALSA lib conf.c:4727:(snd_config_expand) Evaluate error: No such file or directory ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM default


# 2
Testem Tests / undefined / Browser "google-chrome --user-data-dir=/tmp/testem-2432.chrome --no-default-browser-check --no-first-run --ignore-certificate-errors --disable-renderer-backgrounding --disable-background-timer-throttling http://localhost:51172/2432/tests/index.html?hidepassed=&filter=suite1" failed to connect. testem.js not loaded? Stderr: Xlib: extension "RANDR" missing on display ":1". [627:647:0523/205444:ERROR:bus.cc(432)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory Xlib: extension "RANDR" missing on display ":1". (google-chrome:627): GConf-WARNING **: Client failed to connect to the D-BUS daemon: //bin/dbus-launch terminated abnormally without any error message [674:674:0523/205445:ERROR:sandbox_linux.cc(334)] InitializeSandbox() called with multiple threads in process gpu-process (google-chrome:627): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Failed to execute child process "dbus-launch" (No such file or directory)

**Comment by a-murphy** [comment]
Out-of-memory errors are usually resolved by adding a node with more memory.  More information on adding your own node is available [here](http://docs.shippable.com/ci_byoh/).  Shippable nodes have 3.75GB of RAM, so you probably want to try more than that.

**Comment by abhijitkini** [comment]
Closing the issue as resolved as OOM issues are fixed by [bringing your own dedicated hosts](http://docs.shippable.com/ci_byoh/). Let us know, if you have further questions on this topic.
