### ISSUE TITLE
Issue with eb_aws_deploy step

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2628]
### Issue with eb_aws_deploy step

Link to failed build:
https://app.shippable.com/runs/573c290cd49fd90c009be42f

### Is your request

 * [X] A technical issue: You are unable to use Shippable's service per your expectation & need help to resolve the issue.
 
### Description of Issue

aws_eb_deploy step is failing, even with a simple integration:

```
  echo | eb init "quintessentially-api" -r "eu-central-1" -p "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1" 0s  
  Traceback (most recent call last):
    File "/usr/local/bin/eb", line 5, in <module>
      from pkg_resources import load_entry_point
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
      working_set = WorkingSet._build_master()
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
      ws.require(__requires__)
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
      needed = self.resolve(parse_requirements(requirements))
    File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
      raise DistributionNotFound(req)
  pkg_resources.DistributionNotFound: blessed==1.9.5 
 ```

It looks as though it's Blessed that is not found, I tried installing it via pip in the pre_ci step, but that didn't resolve anything, so remove it.

My shippable.yml is:

```
language: php

build:
  ci:
    - echo "No tests yet. Build successful."

integrations:
  deploy:
    - integrationName: "MyIntegratioName"
      type: aws
      target: mytarget
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: myawsappname
      env_name: myawsebenv
      region: eu-central-1
      image_name: "mydocker/image"
      image_tag: "latest"
```

I don't believe I am doing anything wrong, but if so would appreciate pointers. Otherwise, looks as though there is package version problem?

Cheers

**Comment by bobbydeveaux** [comment]
Also, now using pre_ci to user my own docker container and now the eb command isn't even available.

```
  pip install awsebcli 0s  
/root/d922ca44-aeb8-405c-832f-eea17a2dded8.sh: line 58: pip: command not found

  eb --version 0s  
  deployment_details 0s  
  echo | eb init "quintessentially-api" -r "eu-central-1" -p "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1" 0s  
/root/d922ca44-aeb8-405c-832f-eea17a2dded8.sh: line 58: eb: command not found
```

Builld : https://app.shippable.com/runs/573c4dac2f6b330b000946d6

**Comment by oppianmatt** [comment]
Is `eb` in your docker?

If you're using a custom docker image you need to load all your requirements. Only the `push` stage of the build is run outside your custom docker image.

**Comment by bobbydeveaux** [comment]
Even without a custom docker image..!

**Comment by trriplejay** [comment]
Regarding the first build you linked, it looks like there's an issue with our php base image. We're investigating that. @oppianmatt is correct regarding your custom image. We run eb commands inside the build container, so if you're running on a custom container, it will need the awsebcli dependencies.

**Comment by bobbydeveaux** [comment]
Thanks guys. From what I recall, I tried installing awsebcli but needed to install pip.. When I tried installing pip, nether yum not apt-get were available :(

Will try again with the node build to avoid any of the php build issues and report back!

Thanks again :)

**Comment by trriplejay** [comment]
quick update. looks like python-dev package is required by awsebcli, and some of our base images seem to be missing that.  While we work on updating those images, you can add `sudo apt-get install python-dev` in your CI step to allow the eb deploy to work.

**Comment by BrilliantBasicsSync** [comment]
Working fine with u14php7all - thanks.

**Comment by bobbydeveaux** [comment]
Working fine with u14php7all:tip - thanks 👍
