### ISSUE TITLE
docker cache issues

### ISSUE THREAD

**Issue by oppianmatt** [Shippable/support#2629]
### Description of your issue:

We are currently experiencing an issue with the docker caching system. Our last few builds haven't shown the new code changes. For example:

https://app.shippable.com/runs/573c2e53d49fd90c009ce12f

Even the minions can't agree on the current cache value. This is in the build_pre_ci stage where we build a custom docker image.

![image](https://cloud.githubusercontent.com/assets/48596/15356316/efc21f44-1cef-11e6-86f1-8b69b7f5aa84.png)

![image](https://cloud.githubusercontent.com/assets/48596/15356363/1c1132f6-1cf0-11e6-881c-64531539a99b.png)

Building it like so:

```
docker build --build-arg VERSION=$BRANCH.$BUILD_NUMBER -t $DOCKER_IMAGE:$BRANCH.$BUILD_NUMBER .
```

This is a major issue as it's affecting deployment. How can we trust the docker to have the code in it that it claims to have? How do we fix it?

**Comment by oppianmatt** [comment]
Well I don't know for sure if the docker cache id are meant to correlate. But I do know for sure that the docker container that was build did not have the code in it. Can see the git sync (both times) to hash e64412599fbb74dacbe8dff45814cb8139aa8dad

But the file in the container is an old one and is not showing the changes.

**Comment by avinci** [comment]
Can you add the following flags `--no-cache --rm=true` to your `docker build` command and try?

**Comment by oppianmatt** [comment]
If I understand that would mean docker build would never use the cache. Thing is though our docker build takes 17 minutes so we would like to use the cache. It's one of the selling points of shippable vs other CI servers.

the latest build seems to have found some minions that didn't have it cached and is now doing it from scratch

Have tried a git clean -f -x just before the docker build

**Comment by avinci** [comment]
I am not sure if docker got messed up. Maybe we should think about adding this flag to the commit message to temporarily do it for 1 build, so that users could reset it if something got messed up.

1 question is if you want intermediate containers to be cached too? Maybe just adding `--rm=true` might reduce corruption.

**Comment by oppianmatt** [comment]
thing is though I don't understand how/why old files are in the docker that was build.

When ADDing files in a Dockerfile shouldn't it detect changes and invalidate the cache automatically. 

Also the default behaviour of docker build is `rm=true` https://docs.docker.com/engine/reference/commandline/build/ so adding that won't change anything.

**Comment by avinci** [comment]
did any of your prior builds fail? If docker build fails, then i don't think by default the intermediate layer gets removed. So they will stay no matter what on the machine. `--force-rm` will always remove whether your build fails or succeeds. 

I am just guessing here as I am trying to figure out whether this was an isolated instance or a systemic problem.

**Comment by oppianmatt** [comment]
no failures, green all the way down

**Comment by avinci** [comment]
I am stumped... need to get some docker gods to chime :-)

I can force your hosts to reset, if that helps. I want to make sure we resolve your issue.

**Comment by oppianmatt** [comment]
don't reset please, investigating other external options

**Comment by oppianmatt** [comment]
ok don't think it's a docker cache issue anymore. Last build built the docker from scratch (as well had a git clean -f -x before it).


https://app.shippable.com/runs/573c4d142f6b330b000938eb


I see there is a restore_cache step. It possible that the docker image is fine, but when the docker image starts up for the CI tests the restore_cache restores old files over the top?

It shouldn't affect it though as there is a git sync step which does a hard reset.

**Comment by avinci** [comment]
`pre_ci` has no effect on cache as caching is only for `ci`. I am assuming that in your Dockerfile you are adding the source code. Did anything change in your Dockerfile by any chance?

Looking at the logs, it seems like the gitSync on the pre_ci section had no errors and hence it has the latest code. Are you sure that the code you are expecting is in the right branch? 

The one option we have is reset your host and see if the problem persists...

I am happy to jump on a hangout and debug it live...

**Comment by avinci** [comment]
I don't see any issues with your latest build. No conflict in git_sync and hence all the code should be there. Just to be 100% sure, you can try adding a brand new test file into your repo and do an ADD of that file in your Dockerbuild and you can verify that the right code has been added by looking for that file in your `ci` step. 

I am 100% sure that git repo where your Docker build ran is doing `git reset --HARD <right changeset>` So it highly unlikely that the files are stale, unless your Dockerfile is missing that file in 1 of its ADD commands.

**Comment by bobbydeveaux** [comment]
We're experiencing this too. Even with clearing force cache.

```
RUN git clone git@github.com/xxxx/xxxxi.git /srv;
```

Gives an error that /srv already exists and is not empty. Even though it worked until recently.

If it had cloned the repo, it should be cached... but it's as though it's run the command before and is now running it again...

**Comment by oppianmatt** [comment]
building the docker image locally with jenkins shows the dockerfile is correct and the file is getting added.

file in question is: pitchup/templates/staticflatpages/version.html

contents are:

```
<pre>
  version: {{ VERSION }}
  deploy_version: {{ DEPLOY_VERSION }}
  git_version: {{ GIT_DESCRIBE_VERSION }}
  Pitchup.com OK!
</pre>
```

but if I pull the container and inspect it's still showing the old file which used to be:

```
{{ VERSION }} Pitchup.com OK!
```

File was changed in git commit e64412599fbb74dacbe8dff45814cb8139aa8dad (that was the merge to master).

This is the shippable run building that commit https://app.shippable.com/runs/573c2e53d49fd90c009ce12f

minions 1,2,3 build a base docker container to use for ci tests

tests are split over minions 1 and 2

minion 3 does static asset optimizations and creates another docker image, using the base container.

minion 3 pushes this docker to dockerhub



Thing is there is a restore_cache step between building the base container and using it, but the git sync should fix it as that file is in git.



We have moved the docker building steps to a local jenkins instance and not experiencing any issues so it's definitely a shippable cache issue here.

Further builds still have the old files.

**Comment by bobbydeveaux** [comment]
Please could someone look into https://github.com/Shippable/support/issues/2628 ?

Much appreciated!! :)

**Comment by avinci** [comment]
Ok let me look into this. I will get back to you once we finish investigating...

**Comment by avinci** [comment]
Here is what I did to test this and unfortunately i cannot repro it. 
the project is https://github.com/avinci/testDockerCache, it has super simple `Dockerfile` made out of alpine linux and then installs bash. I then add a web folder to `tmp/web` and this web folder has a static html. The project has cache enabled in yml. This should reflect your scenario if I am not mistaken

1. first, I just ran the first version and then push the container to my docker hub. https://app.shippable.com/runs/573eccb50012090c00c6a02e
![screen shot 2016-05-20 at 2 25 43 pm](https://cloud.githubusercontent.com/assets/1302035/15422589/f3ff211c-1e96-11e6-90a2-485486d434fc.jpg)

1. then i made a change to html file and then pushed again immediately so that the build host is still running and hence it will use the intermediate level docker images when i rerun the same build. https://app.shippable.com/runs/573eccc0a56faf0c0004e5a8
![screen shot 2016-05-20 at 2 26 13 pm](https://cloud.githubusercontent.com/assets/1302035/15422606/fd923b56-1e96-11e6-9977-58d23a4769a3.jpg)

In the first case `docker build` built all the layers and in the second case it used the cache for all the steps except the last step where the HTML was changed where it redid the layer.

Hence, the build system is doing the right thing even with docker cache as well as shippable cache.

I am not sure what is different in your scenario anymore. One thought is, whether this file thats changing, is this happening in the `ci` step? i.e. dynamically generated or its part of the repo itself where someone changed it and pushed a code change?

**Comment by oppianmatt** [comment]
see comment at https://github.com/Shippable/support/issues/2629#issuecomment-220004646

Pretty sure it's not a docker cache issue but a shippable cache issue as that is the only difference. The file isn't generated. It's a typical html file in source control.

We actually had to move our docker building off shippable since we couldn't trust it anymore. Plus sometimes minions would take 40+ minutes to build if they missed a cache.

**Comment by avinci** [comment]
the reason its not a restore cache issue is this because, your `docker build` is running in `pre_ci` which runs before `restore_cache` is which only for the `ci` step. 

I am happy to jump on a call and we can debug this live if you would like us to. Any chance that you would like to do that?

I just looked at the code to be 100% sure and even my sample code is trying to mimic what you are doing. I would love to get to the bottom of this mystery

**Comment by abhijitkini** [comment]
@oppianmatt following up to see if would like a live debug session to troubleshoot your issue.

**Comment by oppianmatt** [comment]
of course once I started putting in some some debugging lines to output the files, it has gone away (which is why I think it's a caching issue). Don't think debugging now is going to give any results.

Have now have migrated the docker building part to our own local jenkins where we know what's going and the cache is right each time. shippable just runs ci tests now.

**Comment by abhijitkini** [comment]
@oppianmatt Do let us know if you would like to revisit or need further help on this issue. We are happy to jump in and troubleshoot.

Closing the issue.

**Comment by oppianmatt** [comment]
ok just saw an instance of this with https://app.shippable.com/runs/57b195d9c98b330e004c5294/2/tests

It's complaining some tests have failed but it's on code from another branch!

This line here:

```
File "/root/src/github.com/pitchup/Pitchup.com/pitchup/campsite/tests/test_models/__init__.py", line 307, in test_apply_tax_rms_tax
```

If we actually look at the sha 27a77a07a9 that file should still be test_models.py. In other words it's running code from another branch that should not be possible.

The change to make test_models.py into a separate python package was done in another totally separate branch, this shippable run is it https://app.shippable.com/runs/57b1986400cee6110080bf3b/summary

Sha: 1913d3276a 


So to summarize:
 - change code in one branch and have shippable run it
 - shippable picks up/caches code changes this branch and uses it in other non-related branches test runs
 - result is confusing on what is tested



Some debug info from the console for https://app.shippable.com/runs/57b195d9c98b330e004c5294/1/console

first git sync step checks out correct git sha:

```
HEAD is now at 27a77a0... #6218 catch bad request geo query
git merge origin/master 0s  
Already up-to-date.
```

Then it builds the docker and boots into. Restores the tar.gz cache file.

second git sync step (in the docker) checks out the right sha:

```
HEAD is now at 27a77a0... #6218 catch bad request geo query
git merge origin/master 0s  
Already up-to-date.
```

My guess is that the cache caches all the code, so it snappshotted a copy of the code from the other branch which had the python file as a package instead. Then it restored that copy in the directory but then checked out the branch it was testing. The branch goes back to using the python.py file instead of package dir, but the package dir still exists. So we now have:

 - file.py (from git)
 - file/__init__.py (from cache)

And since the python package wins, and file.py is ignored, it uses the python package which has code from the old branch.

**Comment by oppianmatt** [comment]
ok this is really confusing on why this is happening, I put in another `git clean -f -x` in the build_ci phase right before it runs the tests and after git checkout.

I still have failures in test code that isn't on that branch: https://app.shippable.com/runs/57b1a226c98b330e004c563b/1/console

git clean removed some pyc files, but tests still had failures in `/test_models/__init__.py` , but the issue is that file doesn't exist in that branch. That change is in another branch and not even merged to master yet
