### ISSUE TITLE
Add https://app.shippable.com/ response rate to status page

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2631]
The new [Shippable Status](http://status.shippable.com/) page should also have a graph for the response rate of https://app.shippable.com/.

**Comment by manishas** [comment]
@mbrodala at this time, our plan allows us to only surface one response rate :)

If multiple folks feel strongly about this, we'll either switch from api to ui or upgrade our plan. Closing this as deferred, but will definitely reconsider if there is a lot of interest around this.

**Comment by mbrodala** [comment]
Alright, thanks for considering.
