### ISSUE TITLE
Creating Multiple Pipelines

### ISSUE THREAD

**Issue by twillms07** [Shippable/support#2634]
Our team is having issues working to set up multiple pipelines. We're hoping to get some help completing this. We had discussed with Manisha at some point getting some training on this and would like to set up time as soon as possible to do so.

Thanks

**Comment by manishas** [comment]
@twillms07 yes we're happy to set up a demo. What time works for you? We're in the PST time zone.

**Comment by twillms07** [comment]
I¹ll work with my team and we¹ll come up with a good time. Thanks again.

From:  Manisha <notifications@github.com>
Reply-To:  Shippable/support
<reply+004a65c59bdf5df741fb16f9a03f76c61af2957bcdabd06292cf00000001135701749
2a169ce094a9cea@reply.github.com>
Date:  Friday, May 20, 2016 at 9:46 AM
To:  Shippable/support <support@noreply.github.com>
Cc:  Todd Willms <twillms07@gmail.com>, Mention <mention@noreply.github.com>
Subject:  Re: [Shippable/support] Creating Multiple Pipelines (#2634)


@twillms07 <https://github.com/twillms07>  yes we're happy to set up a demo.
What time works for you? We're in the PST time zone.


You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/Shippable/support/issues/2634#issuecomment-220657996>

**Comment by twillms07** [comment]
Hi Mannish - 

I¹m working with our team now to set up time would next Tuesday or Wednesday
around 9am work for you?


From:  Manisha <notifications@github.com>
Reply-To:  Shippable/support
<reply+004a65c59bdf5df741fb16f9a03f76c61af2957bcdabd06292cf00000001135701749
2a169ce094a9cea@reply.github.com>
Date:  Friday, May 20, 2016 at 9:46 AM
To:  Shippable/support <support@noreply.github.com>
Cc:  Todd Willms <twillms07@gmail.com>, Mention <mention@noreply.github.com>
Subject:  Re: [Shippable/support] Creating Multiple Pipelines (#2634)


@twillms07 <https://github.com/twillms07>  yes we're happy to set up a demo.
What time works for you? We're in the PST time zone.


You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/Shippable/support/issues/2634#issuecomment-220657996>

**Comment by manishas** [comment]
@twillms07 Yes, we can meet next Tuesday 5/31/2016 at 9am PST. Please let me know what email I should send the meeting request to. Thanks!

**Comment by manishas** [comment]
@twillms07 can you let me know what email address i should send the meeting invite to? Thanks!

**Comment by twillms07** [comment]
Hi Manisha - 

Here are the emails ­ I look forward to speaking with you and team.

- twillms@piiq.co
- ceecer.lamichhane@gmail.com
- borut.dagarin@gmail.com


From:  Manisha <notifications@github.com>
Reply-To:  Shippable/support
<reply+004a65c58ccb1468f9777d9f76468262920d97ab5c74475292cf0000000113604f089
2a169ce094a9cea@reply.github.com>
Date:  Friday, May 27, 2016 at 11:08 AM
To:  Shippable/support <support@noreply.github.com>
Cc:  Todd Willms <twillms07@gmail.com>, Mention <mention@noreply.github.com>
Subject:  Re: [Shippable/support] Creating Multiple Pipelines (#2634)


@twillms07 <https://github.com/twillms07>  can you let me know what email
address i should send the meeting invite to? Thanks!


You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Shippable/support/issues/2634#issuecomment-222215457> ,
or mute the thread 
<https://github.com/notifications/unsubscribe/AEplxTDYVSVBSrc2TRADqLoxvvgzGU
HOks5qFzMIgaJpZM4Ii4ED> .

**Comment by manishas** [comment]
I am closing this issue since a meeting request for the demo was sent out.
