### ISSUE TITLE
Error enabling project.

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2637]
### Description of your issue:

Attempting to enable a project from an organization I'm a member of is returning an error:

```
(Id: 2002) Owner not found for projectId::573f79d02a8192902e20e34b
warn: caller:573f3445d911710c00c93693|projects|enableById:573f79d02a8192902e20e34b|_getValidOwner
```

This is blocking use of the service.

**Comment by a-murphy** [comment]
It doesn't look like any owners of that project have signed in to Shippable.  Without a repository owner, we can't add the webhooks to trigger builds.  Could you ask an owner of the repository on GitHub to enable it on Shippable?

**Comment by mattclay** [comment]
I'm currently an owner on that project. I ended up having to use the "sync" button to refresh privileges so I was recognized on Shippable as an owner.
