### ISSUE TITLE
Client-Server Program Using Socker API in C++ Is not Able to Communicate over Docker

### ISSUE THREAD

**Issue by vikasr04** [Shippable/support#2639]
Issue:
I have a Server program written in C++ ,using posix Socket API. The Dockerfile used for building the Server image is:
$ cat Dockerfile
FROM gcc:4.9
WORKDIR /home/vikrana
COPY . .
EXPOSE 1001
RUN g++ -o testcplusplus testprogram.cpp
ENV PATH /home/vikrana:$PATH
ENTRYPOINT ["testcplusplus", "1001"]

Below is the link for the Server program written in C++.
[testprogram.txt](https://github.com/Shippable/support/files/275715/testprogram.txt)

Following is the Docker command I am using to run my server program in the container:
$ docker run --net=user_def_nw -ti -P --name server1 my-server-app

On running above command the container gets attached with user_def_nw and an IP address "172.18.0.2" is assigned to the container, which is always is the case. The same IP address I have used in my server program cpp file.

On the other hand following are the details of my Client program written in C++ using posix Socket API.
DockerFile to create client image:
$ cat Dockerfile
FROM gcc:4.9
WORKDIR /home/vikrana
COPY . .
RUN g++ -o testcplusplus testclientprogram.cpp
ENV PATH /home/vikrana:$PATH
ENTRYPOINT ["testcplusplus", "172.18.0.2", "1001"]

Below is the link for the Client program:
[testclientprogram.txt](https://github.com/Shippable/support/files/275722/testclientprogram.txt)

Following is the Docker command I am using to run my client program in the container:
$ docker run --net=user_def_nw -ti  --name cli1 my-client-app

On running the above command it is noticed Client is not able to connect to the server at IP: 172.18.0.2 listening at port 1001.

The error code return my the connect API is "111" which means, connection refused.

Can anyone help me in resolving this issue in Docker.?

Thanks in Advance.

**Comment by manishas** [comment]
@vikasr04 is this a for a project you've enabled on Shippable?

If yes, can you please share the username you use to sign in to Shippable?

**Comment by vikasr04** [comment]
@manishas 
No I have not enabled any project on shippable. Not sure if by uploading my program files, by default the project gets created in Shippable.
Actually, I am new to Docker, and was trying to use certain features of it. In that one of it is container can communicated over a given user defined bridge network. So I wrote a Client server program (each program running as a container) using POSIX Socket API. But I am facing problem in setting up a TCP connection between the two containers.
If you or anyone in GitHub know the solution of my problem then please help me out.

**Comment by manishas** [comment]
@vikasr04 looks like your question is solely docker related then. Support for docker is at https://github.com/docker/docker/issues so you should ask your docker questions there. 

Shippable is a continuous integration and delivery platform that has excellent support for docker based workflows. If you want help setting up CI we're happy to help. 
Thanks!

**Comment by vikasr04** [comment]
@manishas 
Thanks for redirecting me to the correct forum.
