### ISSUE TITLE
Build Fail - shippable.yml & UI specified integration non functional

### ISSUE THREAD

**Issue by iamacup** [Shippable/support#2644]
Hi - I am really sorry if this is blindingly obvious but I have tried several different integrations, with different names, all fail the same way, and read all the documentation - i can't work out what i could be doing wrong so i am reporting it as an issue.

I have an integration specified in the shippable.yml
[shippable.yml.zip](https://github.com/Shippable/support/files/278378/shippable.yml.zip)

 and in my project settings - the names are identical - but every time the build runs it always fails with 

`Integration name specified in yml does not match integrations present in project settings: shippableecr`

<img width="919" alt="image1" src="https://cloud.githubusercontent.com/assets/12894620/15486301/8571e84e-213c-11e6-86ab-e85281debddf.png">

<img width="1108" alt="image2" src="https://cloud.githubusercontent.com/assets/12894620/15486302/85777db8-213c-11e6-8d11-cb40cfe7e106.png">

Link to the fail: https://app.shippable.com/runs/5743800da7f3850d00ed177c

**Comment by a-murphy** [comment]
It looks like it's just indentation.  There are some tabs in your shippable.yml, leading to it not being parsed as intended.  Try indenting it to look like this (with spaces):
```
integrations:
    hub:
      - integrationName: shippableecr
        type: ecr
        region: eu-west-1
```

And here is an online parser you can use to check it: http://yaml-online-parser.appspot.com/.  `integrationName`, `type`, and `region` should all be in one object in the the `hub` array.

**Comment by iamacup** [comment]
Thanks very much - i thought i had solved this - if you take a look here:

http://docs.shippable.com/ci_faq/#how-do-i-specify-a-region-while-setting-up-amazon-ec2-container-registry-ecr-integration

The YAML under **How do I specify a region while setting up Amazon EC2 Container Registry (ECR) Integration?** is not quite right.

Cheers

**Comment by abhijitkini** [comment]
@iamacup Thanks for bringing this to our attention. The documentation has been updated.
