### ISSUE TITLE
Can't build node_js

### ISSUE THREAD

**Issue by clounie** [Shippable/support#2645]
### Description of your issue:
I copied a `shippable.yml` file that had been working in another repo before the weekend, and tried to re-use it, but it wouldn't work. I then commented out everything but a *very* simple snippet:
```
language: node_js
node_js:
  - "0.12"
build:
    post_ci:
      - echo Hello
```
But keep on getting this error:
```common2|_cleanRunYml|callerId:5743f4e396bad111007dc251|projectId:5743f55d2a8192902e212954|_cleanLanguage Invalid RUN language: node_js```
I even tried with the python RUN language just for grins...and that one failed too. What's up?

P.S. `language: none` did at least run without error. So my syntax wasn't completely off.

https://app.shippable.com/runs/57447d7aa92d080c00688023

**Comment by trriplejay** [comment]
It looks like your project is enabled as an 'infrastructure' type, but to run a traditional build, it needs to be enabled under the 'ci' tab from your subscription page.

'infra' builds are for running provisioning scripts like that of Terraform.  Those types of builds expect slightly different yml parameters.

To correct this, you should go to your project page, and click 'delete' under the settings tab.  This will basically disable the project from the infra section.  Then you can go to the 'ci' section, find your project, and click enable.  After that, the yml you've listed above should be valid, and should allow for a successful run.

**Comment by clounie** [comment]
That worked, thanks.
