### ISSUE TITLE
Failed to POST accountIntegration 

### ISSUE THREAD

**Issue by glongo88** [Shippable/support#2647]
Hi, 

similar to other issues, I'm not able to login with my bitbucket account (username glongo88).
It shows the 'Failed to POST accountIntegration' error.

Could you check my account?

Thank you

**Comment by rageshkrishna** [comment]
@glongo88 Sorry about that. Can you please try logging in now?

**Comment by glongo88** [comment]
@rageshkrishna Now it works! Thank you for your quick reply

**Comment by rageshkrishna** [comment]
Happy to help! :)
