### ISSUE TITLE
Feature Request: Allow display of CI runs as list instead of tabs

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2649]
Allow display of runs as a list instead of tabs. This would make it much easier to look at the big picture quickly. Columns displayed should include:

- Job Number
- Matrix Values
- Duration
- Success/Failure

An example of this kind of layout can be seen on Travis CI.

**Comment by manishas** [comment]
@mattclay thanks for the suggestion! We'll take a look at this experience and figure out how to make it easier to look at all jobs for a run.

**Comment by mattclay** [comment]
Other output that would be useful to include in a list of jobs:

- Test Results
- Code Coverage

**Comment by mattclay** [comment]
@manishas Do you have any idea of whether or not this feature will be implemented, and if so, on what kind of timeframe that might be?

Not having this really discourages the use of more than 11 concurrent containers since anything beyond that appears in the drop down menu on the right, and there's no way to know which tab is associated with which test matrix parameters without clicking on each one.

**Comment by manishas** [comment]
@mattclay we are already working on improving the user experience for matrix builds and addressing your scenario. Current ETA is 6/13. I will keep you updated as we get closer to launching this.

**Comment by manishas** [comment]
@mattclay this is now available and all jobs for your build should be displayed in a Summary tab. We're still fixing a couple of fit and finish issues, but this should address your scenario.

Let me know your feedback.

ccing @gundalow @fmasa since they liked my comment  above :)

**Comment by mattclay** [comment]
@manishas The new Summary tab is exactly what we needed. Thanks for the quick implementation.

A few improvements come to mind while looking at this build:

https://app.shippable.com/runs/5757653d4d84240c005ddffc

- Include an option to sort or filter on success/failure so it is easier to view just the failures. For example,  the above mentioned build has 1 of 30 jobs failed, but you have to scroll down to see the failure.

- Display the full value for truncated details, such as the matrix values, when hovering over a row in the summary table. This is especially important for matrix values since it's how you can identify what the job was without clicking on it.

- Some of the columns could be displayed as two lines to allow them to be narrower, since the text is smaller, leaving a lot of space above/below. For example, sequence coverage could be displayed below branch coverage instead of on one line. The same could be done for the test data. This would leave more room for other columns such as the matrix values.

**Comment by manishas** [comment]
@mattclay thanks for the feedback. Showing the env variables in a tooltip is part of the fit and finish items I mentioned and will be addressed today. 

We'll also put adding a filter on our feature backlog. Thanks!

**Comment by manishas** [comment]
The tooltip and filter are now available, so please check it out and let us know what you think :)

**Comment by mattclay** [comment]
Excellent. That's perfect! Thanks for the quick turn around on this.
