### ISSUE TITLE
Feature Request: Add project setting to require shippable.yml

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2652]
It would be helpful to have a project setting in the UI which could be enabled to require a shippable.yml in a branch before triggering build jobs.

This would would be especially helpful as a short-term work-around for https://github.com/Shippable/support/issues/2643 to at least cut down on the noise and wasted build time for PRs with only a Travis configuration.

**Comment by mattclay** [comment]
After thinking about this more, I don't think this feature will be useful as a work-around for issue #2643. If a branch is out-of-date, I'd rather have it fail tests than run no tests at all.

Feel free to close this request if you don't see any other value in it.

**Comment by mattclay** [comment]
@manishas Is there a possibility this could be implemented?

I'm trying to trigger CI for pre-Shippable integration PRs, but due to issue #3231 the builds are failing due to having a `travis.yml` file. If Shippable could be told to ignore this file, I'd be able to trigger builds by closing and re-opening PRs, or if there was a way to [trigger builds through the API](https://github.com/Shippable/support/issues/3245).

Otherwise I'm stuck with old PRs which I'm unable to run tests on.

**Comment by manishas** [comment]
Let me discuss with the team and get back to you.

**Comment by avinci** [comment]
@manishas did you get a resolution on this? I think #3231 is resolved. I am not sure if this is still relevant

**Comment by mattclay** [comment]
Closing this as it's no longer an issue.
