### ISSUE TITLE
Permissions required to manually trigger rebuild from Shippable UI

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2653]
What permissions are required in order for a user to trigger a rebuild from the Shippable UI?

**Comment by a-murphy** [comment]
Both "collaborators" and "owners" can trigger builds.  On GitHub, this means that the user must have at least read access as part of a team in an organization or be added to the repository as a collaborator.

**Comment by mattclay** [comment]
For a public project, does that mean anyone can trigger a rebuild?

**Comment by a-murphy** [comment]
No.  Anyone can see the public project (with a link to it), but only users that have permissions through a GitHub organization team with access to the repository or have been added directly to the GitHub repository will be able to click "rebuild."

**Comment by mattclay** [comment]
We had a user with write access via a team which could not see the rebuild button. I ended up re-syncing our account with GH using the sync button and they refreshed their browser cache. This resolved the issue for them.
