### ISSUE TITLE
ECR Login

### ISSUE THREAD

**Issue by bantonj** [Shippable/support#2657]
### Description of your issue:
I'm trying to use AWS ECR to host a custom docker image for building with. I see this output
```
Unable to find image '116065022286.dkr.ecr.us-east-1.amazonaws.com/krossover-devops:latest' locally
Pulling repository 116065022286.dkr.ecr.us-east-1.amazonaws.com/krossover-devops
Authentication is required.
```
I have the ECR account integration and hub integration setup with AWS credentials that can call ecr:GetAuthorizationToken successfully.

- https://app.shippable.com/runs/5748848ea991900d00f77e13

#set your language below
language: php

#set language version. This is only required if you use the default Shippable image for your build
python:
    - 5.5

#specify which services you need. This is only valid if you use the default Shippable image for your build
services:

env:
    - COMPOSER_ROOT_VERSION=dev-master

matrix:

build:
    #commands in this section run on your build machine and not inside your CI container.
    pre_ci:

    pre_ci_boot:
        image_name: 116065022286.dkr.ecr.us-east-1.amazonaws.com/krossover-devops
        image_tag:
        pull:
        options:
    #commands in this section run inside your CI container. In addition, any commands such as ls, in this section can be used to skip default processing for CI.
    ci:
      - ssh-agent bash -c 'ssh-add /home/git.key; composer install'
      - cd build
      - ../vendor/bin/phing lint
      - ../vendor/bin/phing phpcs
      - ../vendor/bin/phing phpmd
      - cd ..
      - mkdir deploy
      - cd deploy
      - ssh-agent bash -c 'ssh-add /home/git.key; git clone git@bitbucket.org:krossoverintelligence/deployer-builder.git'
      - cd deployer-builder/intelligence-api
      - python builder.py -b $BRANCH -w test-envs
      #To build forks builder.py needs to use the $REPOSITORY_URL env var to know where to grab code from
    post_ci:
    on_success:
    on_failure:
    cache:
    #commands in this section run on your build machine and not inside your CI container.
    push:

**Comment by manishas** [comment]
@bantonj you also need the integration in your yml. Replace the `integrationName` and `region` values below and add to the integrations section of your yml:

```
integrations:
  hub:
    - integrationName: your_integration_name
      type: ecr
      region: us-west-2
```

**Comment by manishas** [comment]
some more things to keep in mind:  In the  `pre_ci_boot` section, you need to specify the `tag` of the image you want to pull. `pull` should be set to 'true'. In `options`, you should specify a path for the HOME environment variable. For example:

```
pre_ci_boot:
    image_name: 116065022286.dkr.ecr.us-east-1.amazonaws.com/krossover-devops
    image_tag: latest
    pull: true
    options: "-e HOME=/root"

```

**Comment by bantonj** [comment]
Getting closer I think. Now I get the below. If I run that command locally it works fine.

`sudo docker pull 116065022286.dkr.ecr.us-east-1.amazonaws.com/krossover-devops:latest 
latest: Pulling from krossover-devops
23286f48d129: Pulling fs layer
cbee5247e891: Pulling fs layer
c00e76f9999f: Pulling fs layer
037a89f5cdfa: Pulling fs layer
c30417c333a9: Pulling fs layer
40efcfcc9e15: Pulling fs layer
a49cb69cd8d9: Pulling fs layer
f8d593f19275: Pulling fs layer
087b068298db: Pulling fs layer
693804d85773: Pulling fs layer
d05fb2f39237: Pulling fs layer
bd4f6470c173: Pulling fs layer
4520707dc12b: Pulling fs layer
e4b5243d63ec: Pulling fs layer
6b0972042f1e: Pulling fs layer
053a347d96a9: Pulling fs layer
874c3d4c5a37: Pulling fs layer
6826574d2c05: Pulling fs layer
8f5735ddb238: Pulling fs layer
926acd5e559b: Pulling fs layer
Pulling repository 116065022286.dkr.ecr.us-east-1.amazonaws.com/krossover-devops
Error: image krossover-devops:latest not found`

from this yml

#set your language below
language: php

#set language version. This is only required if you use the default Shippable image for your build
python:
    - 5.5

#specify which services you need. This is only valid if you use the default Shippable image for your build
services:

env:
    - COMPOSER_ROOT_VERSION=dev-master

matrix:

build:
    #commands in this section run on your build machine and not inside your CI container.
    pre_ci:

    pre_ci_boot:
        image_name: 116065022286.dkr.ecr.us-east-1.amazonaws.com/krossover-devops
        image_tag: latest
        pull: true
        options: "-e HOME=/home"
    #commands in this section run inside your CI container. In addition, any commands such as ls, in this section can be used to skip default processing for CI.
    ci:
      - ssh-agent bash -c 'ssh-add /home/git.key; composer install'
      - cd build
      - ../vendor/bin/phing lint
      - ../vendor/bin/phing phpcs
      - ../vendor/bin/phing phpmd
      - cd ..
      - mkdir deploy
      - cd deploy
      - ssh-agent bash -c 'ssh-add /home/git.key; git clone git@bitbucket.org:krossoverintelligence/deployer-builder.git'
      - cd deployer-builder/intelligence-api
      - python builder.py -b $BRANCH -w test-envs
      #To build forks builder.py needs to use the $REPOSITORY_URL env var to know where to grab code from
    post_ci:
    on_success:
    on_failure:
    cache:
    #commands in this section run on your build machine and not inside your CI container.
    push:

integrations:
  hub:
    - integrationName: krossover-devops
      type: ecr
      region: us-east-1

**Comment by manishas** [comment]
@a-murphy can you take a look?

**Comment by a-murphy** [comment]
It's probably something about one of the layers in that image (it knows what they are, but isn't pulling them).  Is it possible that the credentials being used don't have permission to pull one of the layers?  Perhaps trying to pull the base image in the `pre_ci` step in shippable.yml might help.

The error looks like this one: https://forums.aws.amazon.com/thread.jspa?threadID=227929 and pulling the base image first worked there.

**Comment by bantonj** [comment]
That's interesting. This image is based on php:5.5. I added the below, but it's not helping, does that look like an appropriate work around?

pre_ci:
        - docker pull php:5.5

**Comment by a-murphy** [comment]
So I guess that's not it.  This isn't exactly a common problem, so we're still looking for other possible causes.

**Comment by manishas** [comment]
@bantonj are you still running into issues? We haven't been able to find a root cause for the error you were seeing, but wanted to check in with you to see if you made any progress.

**Comment by bantonj** [comment]
In order to continue testing out Shippable I switched to Docker Hub, which works fine. I would prefer to use ECR though, and don't know what else to try.

**Comment by stephanielingwood** [comment]
@bantonj We looked into this some more today, and have two more potential culprits. 

The first could be that one (or more) of your layers on ECR is bad - or that ECR thinks it is. We've noticed that, very occasionally, images on one registry have problems with layers that came from another registry. This seems to happen more when going from Docker Hub to EC

**Comment by manishas** [comment]
Closing this issue since there is no further action item for us.

@bantonj please let us know if either of the 2 suggestions above work for you.

**Comment by bantonj** [comment]
I tried pushing to a new ECR repository, and it still fails with the same error. 

`Error: image shippable-php:latest not found`

I've also noticed that it lists some fs layers that it is going to pull, that don't seem accurate. Could it be not logging in to ECR correctly?

**Comment by stephanielingwood** [comment]
Looks like you're logged in to ECR correctly. If you weren't, the errors are usually something like: 
`Error pushing to registry: Server error: 403 trying head request`

Like we mentioned above, sometimes images on one registry have problems with layers that come from another registry. Did you ever get a chance to remove the base image locally, and rebuild the image? If so, is this the image you're pushing to ECR?

Just curious - in what way do you think the fs layers that are being pulled are inaccurate? That might help debug what's going on with this image.

**Comment by abhijitkini** [comment]
@bantonj following up to see if you were able to remove and rebuild the base image and give info to continue troubleshooting this issue.

**Comment by abhijitkini** [comment]
Closing the issue. Do re-open to continue troubleshooting and let us know if tried the above recommendation.

**Comment by bantonj** [comment]
I still cannot get this to work. I've rebuilt the image from scratch and pushed to a new ECR repo  116065022286.dkr.ecr.us-east-1.amazonaws.com/shippable-please-work

The repo works fine from a completely fresh docker installation, so it's not having any issue pulling layers from different repos.

**Comment by bantonj** [comment]
Any thoughts on this? I'd like to switch to shippable, but I don't want to have to use Docker Hub.

**Comment by bantonj** [comment]
Looks like this was a IAM permission issue.
