### ISSUE TITLE
Missing pdo_pgsql

### ISSUE THREAD

**Issue by chrisandchris** [Shippable/support#2658]
### What it is about
Question/Support

### Description
I'm trying to build a repository using php and postgres. But it appears that there's no pdo_pgsql driver installed by default in the docker image.

I tried installing the driver using `apt-get install php5-pgsql`, but it appears not to solve my problem.

**Comment by manishas** [comment]
@chrisandchris can you point us to your build link?

**Comment by chrisandchris** [comment]
@manishas Yes, the project overview is here: https://app.shippable.com/projects/574752252a8192902e218835

Try to build the target/v1.0.0 branch, it contains a shippable.yml as the only branch.

Isn't there a way to provide a override shippable.yml for testing purposes? I now have around 20 commits in my repo just for trying out shippable...

**Comment by manishas** [comment]
@chrisandchris we're looking into this now and can't find the specific build where you were seeing this issue. Can you post a link to the specific build or paste the error you're seeing in the console?

**Comment by chrisandchris** [comment]
So like here: https://app.shippable.com/runs/57495dcaceeddf0d00198bd3

When it runs `composer install`, it fails due to a missing driver. But I actually have seen, that builds using PHP 7 and PHP 5.6 are right now not possible, and due to missing Bitbucket Server integration, I anyway might not be able to use shippable as supposed to.

**Comment by trriplejay** [comment]
Things we tried: 
  - altering the php.ini 
  - installing pgo_pgsql with PECL and Pickle 
  - installing php5dev and libpq-dev with apt-get
  - moving the version of pgsql.so installed by apt-get to the directory of that version of php in phpenv
  - various other unsucessful attempts to get the version of pgsql.so to match the version of PHP.

unfortunately none of these resulted in achieving what you're trying to achieve.

**Comment by manishas** [comment]
Closing this issue since our investigation has reached a dead end. This will be reopened if we get any new leads or more customers run into it.

**Comment by abhijitkini** [comment]
@chrisandchris Do refer https://github.com/Shippable/support/issues/2807 for a workaround on this issue.
