### ISSUE TITLE
Beginning part of BUILD_URL is undefined

### ISSUE THREAD

**Issue by Vilsepi** [Shippable/support#2659]
Today between 09-10AM UTC, the BUILD_URL environment variable broke. Its beginning part (protocol and hostname) is now "undefined":

    echo $BUILD_URL
    undefined/runs/574c3aa5e77e550d00fb7ec8

It should be:

    https://app.shippable.com/runs/574c3aa5e77e550d00fb7ec8

**Comment by pranaypareek** [comment]
@Vilsepi thanks for bringing this to our notice. We have identified the problem and are fixing the issue.

**Comment by pranaypareek** [comment]
We have pushed the fix and it's back to normal.

Please let us know if things are okay on your end!

**Comment by Vilsepi** [comment]
Seems fixed now, thanks!
