### ISSUE TITLE
build hangs on "provisioning job node"

### ISSUE THREAD

**Issue by seanxe** [Shippable/support#2661]
Can't seem to spin up any job nodes:

https://app.shippable.com/runs/574c532e2fa69b1200c562d8

I cancelled it after 31 minutes.

Tried to "rebuild" and i'm already up to 5 minutes which is the longest I've ever hard to wait?

https://app.shippable.com/runs/574c5a62f719490f005f9b18

**Comment by manishas** [comment]
looking into this...

**Comment by phagunbaya** [comment]
Same with us.

**Comment by manishas** [comment]
we're working on this. update in a few mins.

**Comment by rocknruby** [comment]
same same

**Comment by manishas** [comment]
we've identified the issue but the fix is taking some time..... i will keep this thread updated.

**Comment by manishas** [comment]
we're almost there.... just a few more mins and everything will be back up. Thanks for your patience!

**Comment by manishas** [comment]
This should be resolved now. Please let us know if you're still running into this.

**Comment by phagunbaya** [comment]
Works for us !

**Comment by manishas** [comment]
Thanks for confirming! We are monitoring everything closely to make sure everything stays up. 

Thanks for your patience!

**Comment by rocknruby** [comment]
Hi, it seems to work now as expected. Thanks.

**Comment by seanxe** [comment]
yup, all good for me here as well. closing the issue as the original problem is resolved.

thanks for the quick turn around @manishas !

**Comment by rocknruby** [comment]
Hi @manishas the problem occurs again. My build is waiting 15min from now and not starting.

**Comment by kanthchandra** [comment]
Hi @rocknruby, it looks like you have changed to the unstable version of the image. So your existing node died without processing the job request. Can you trigger another build and a new node with the unstable image should come up?

**Comment by rocknruby** [comment]
Hi @kanthchandra, I changed the setting back to the stable version of the image. Canceled the build and started the build process again. Cleared the cache, but the build is not starting.

**Comment by kanthchandra** [comment]
Hi @rocknruby, I see that your build is running now :)

**Comment by rocknruby** [comment]
Thanks. Any suggestions to keep the builds running?
