### ISSUE TITLE
Container cache disabled due to AWS credentials misssing [sic]

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2664]
I just noticed the following output in the `boot_container` step in [my builds](https://app.shippable.com/runs/574d4a360800fa0f00b84bf6):

>  echo 'Cache enabled for the build' 0s
>  echo 'AWS credentials misssing, will not be able to cache' 0s
>  aws s3api get-object --profile shippable --bucket <bucket> --key cache/<id>.tar.gz /home/shippable/cache/<id>.tar.gz 6s
>  echo 'Failed to pull cache from S3 bucket, proceeding without cache'

Is there some issue with the container caching ATM?

**Comment by avinci** [comment]
this is a bug on our side. We are going to fix it ASAP.

**Comment by avinci** [comment]
@ric03uec your team is picking this up as CQD

**Comment by mbrodala** [comment]
@avinci Random fact: I just learned what CQD means and that Germany invented the SOS signal. ;-)

**Comment by avinci** [comment]
:-)  we use CQ, CQD and SOS 

CQ (seek you) is someone picks this up the moment they finish what they are doing
CQD (seek you in distress) someone stops what they are doing and picks this up
SOS (save our souls) the entire company stops doing what they are doing until this is fixed :-)

**Comment by kanthchandra** [comment]
Hi @mbrodala, This is fixed and deployed. Can you please see if it works for you now?

**Comment by mbrodala** [comment]
@kanthchandra [Looks good](https://app.shippable.com/runs/574d72381e6d8e0c00441546):

>   echo 'Cache enabled for the build' 0s
>  echo 'Configuring subscription registry' 0s
>  echo 'Successfully configured registry credentials' 0s
>  aws s3api get-object --profile shippable --bucket [bucket] --key cache/[id].tar.gz /home/shippable/cache/[id].tar.gz

Thanks for the fix. :-)
