### ISSUE TITLE
Pipeline ECS Container Links

### ISSUE THREAD

**Issue by deanmraz** [Shippable/support#2667]
Currently, I rely on container links to connect my nginx and phpfpm container via hostname. Docker configures the ip routing in the /etc/hosts file automatically and I can use the hostname in the nginx conf to forward php requests to the phpfpm container. 

https://app.shippable.com/pipelines/574e5e871e6d8e0c006ef4e8

This is configurable in AWS ECS Task Definition, but how do I apply that configuration with shippable?

**Comment by manishas** [comment]
@trriplejay can you take a look at this?

**Comment by trriplejay** [comment]
Unfortunately we do not currently support container links. This is something we're planning to support in the near future, though.

If both of your containers are in the same manifest, then you can communicate between them via localhost if your host/container ports are defined.

**Comment by deanmraz** [comment]
@trriplejay got it thanks!

I'm trying to remove the pipeline but looks like I'm getting an error.  Any thoughts? 
https://app.shippable.com/pipelines/574e5e871e6d8e0c006ef4e8

ping @manishas

**Comment by a-murphy** [comment]
For the deletion error, your deployment has a "success" status.  This prevents deletion of the pipeline because something may be running.  To change the status to "stopped," scale the pipeline to zero replicas from the status tab for the pipeline in that environment.  (Deploying zero from the configuration tab is something that we've intended to change.)

**Comment by deanmraz** [comment]
@a-murphy I can't find the page to change the status to "stopped". Could you provide a link?

**Comment by trriplejay** [comment]
you can just click the `scale` button on this page: 
https://app.shippable.com/cellConfigs/574e5e880800fa0f00eb79bb/status

![image](https://cloud.githubusercontent.com/assets/6869398/15843465/2eab8a8e-2c17-11e6-9b03-78b67b087034.png)


The replicas are already set to 0, so just clicking the button should take care of the rest.

**Comment by deanmraz** [comment]
@trriplejay that worked, thanks guys!
