### ISSUE TITLE
Behat testing on a GO project

### ISSUE THREAD

**Issue by mvmaasakkers** [Shippable/support#2668]
I am wondering if it is possible to do PHP based behat testing in a project build. We have an extensive behat testing environment written for our projects but done in PHP and we also use this for our GO projects so we can maintain one codebase for the tests.

I couldn't find if I can use PHP in the build process if my selected language is go but I'm hoping you could point me in the right direction if this is possible.

**Comment by a-murphy** [comment]
Using multiple languages in a build is definitely possible, but you can only specify one in your shippable.yml file.  There are basically two choices: use the default image for the language you specify and install your dependencies for the other language in the build, or build your own Docker image with all the dependencies you need for both.

So, if you choose to use a Go image, you'll need to install PHP in the `ci` step, and with a PHP image, you'll need to install Go.

If you decide to build your own Docker image with PHP and Go installed, here is the documentation on [selecting that image](http://docs.shippable.com/ci_configure/#overriding-the-default-build-image).  It should be an Ubuntu-based image (with Python installed).

**Comment by abhijitkini** [comment]
Closing the issue as resolved. Please let us know if you need further help on this topic.
