### ISSUE TITLE
Ability to Show and Hide projects from Dashboard

### ISSUE THREAD

**Issue by mapio** [Shippable/support#2673]
I am trying to delete https://app.shippable.com/projects/552845f55ab6cc1352bfedc1 but when I go to the config page and hit the "Confirm" button after hitting "Delete" one, I get

```
(Id: 2000) No access or object not found for id: 552845f55ab6cc1352bfedc1
warn: common|validateProjs|callerId:574f4f323f50700c009b96a5|_checkProjectPermissions
```

I have not added such project, It appeared in my dashboard as soon as I connected with BitBucket.

**Comment by shrivara** [comment]
You appear to have collaborator access to the project, which gives you access to the project's builds. You need to be an owner of the project to delete it.

**Comment by mapio** [comment]
Oh I see. 

This means that anyone can pollute my dashboard with projects I can't delete just by adding me as a collaborator. 

Of course is reasonable that I can't delete the original project (on BitBucket, or Shippable), but I would like to be able to delete (or just hide) from my dashboard projects I'm collaborating with. Especially since being added as a collaborator is something you can't prevent on BitBucket (you don't need to approve, or accept, being added as such).

**Comment by avinci** [comment]
we have added this so that you can create custom views on your dashboard. This will go live this week.

**Comment by avinci** [comment]
Custom views were launched into production. Please let us know if you face any issues.
