### ISSUE TITLE
Repeated "Permission denied (publickey)" error

### ISSUE THREAD

**Issue by gappleto97** [Shippable/support#2675]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure

https://codeship.com/projects/121065/builds/10491710

This is a public repo, and is not the first time I've encountered this problem. The last time I hit some sort of reset setting, but I can't seem to locate it again. I would appreciate help with resolution.

**Comment by manishas** [comment]
@gappleto97 the link you've posted appears to be a link to a codeship project. 

This is the support repo for Shippable. Are you having problems with your builds on Shippable? The Reset button for Shippable projects is in the Settings tab and you'll need to scroll all the way down to find the Reset action. Let me know if it works for you.

**Comment by gappleto97** [comment]
I'm sorry. This just goes to show I shouldn't be filing issues at midnight.

**Comment by manishas** [comment]
No worries :)
