### ISSUE TITLE
Looking to change the memory allocated in php

### ISSUE THREAD

**Issue by rachellawson** [Shippable/support#2676]
### Description of your issue:
My build is failing as it runs out of memory during the install phase of the Drupal 8 website. It’s not entirely surprising as I’m firing up the php webserver thing, Drupal itself and behat.
Ideally, I’d like to be able to set the php memory allocation to 256MB or thereabouts and I did find a mention to another issue where the outcome was to blog about how to do this but I cannot find any relevant blog article. Can you add it to the main Shippable documentation?

- Link to the build failure
https://app.shippable.com/runs/5751919a110fc30c00299f3a

- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
Combining [this issue](https://github.com/Shippable/support/issues/543) with [this one](http://stackoverflow.com/questions/561066/fatal-error-allowed-memory-size-of-134217728-bytes-exhausted-codeigniter-xml), it looks like adding the following to the `ci` section of your `shippable.yml` should work.
```
- echo "memory_limit = 256M" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
```

**Comment by abhijitkini** [comment]
@rachellawson Please let us know if the above suggestion worked or if you need further help. Closing the issue.

**Comment by rachellawson** [comment]
Yes thanks it worked well - tried it earlier today


Rachel
