### ISSUE TITLE
Cannot add or find ECS formation

### ISSUE THREAD

**Issue by vivekbhupatiraju** [Shippable/support#2678]
### Description of your issue:
I'm unable to find or add formations to my repo that I want to run builds on. The formation I'm interested in using is for ECS.

Is this something not available in the free version and only part of the subscription plan?

I have set up my AWS integration already with the access key and secret. The AWS api endpoint was defaulted to https://api.aws.com

**Comment by stephanielingwood** [comment]
Hi @vivekbhupatiraju,

Would you mind telling us more about what you'd like to do? With a little more information, we can point you in the right direction.

If you want to run your ci builds on your own custom host (on ECS or elsewhere), we provide details in [our documentation](docs.shippable.com/ci_byoh/#running-builds-on-your-own-machines-byoh). This is a good option if you need build machines with more cores/RAM, or want faster build times.

If you want to manage deployments to ECS, then we suggest looking at the [pipelines documentation](http://docs.shippable.com/pipelines_overview/). (Pipelines were formerly called formations.)

**Comment by abhijitkini** [comment]
@vivekbhupatiraju Following up for more information on your scenario.

To clarify, as part of the free plan, you get one Pipeline, which allows you to set up deployment for one deployment unit of your application.

**Comment by abhijitkini** [comment]
Closing the issue. Do re-open and provide more information to continue troubleshooting this issue.
