### ISSUE TITLE
Feature Request: Restart individual job from build matrix

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2680]
Sometimes just one or two builds in the build matrix fail due to transient errors such as a network timeout. In these cases it would be nice to have the option to restart individual builds from the build matrix, rather than the entire set of jobs, particularly when the matrix is large.

**Comment by avinci** [comment]
@mattclay do you want to restart it as a new job or do you need it to run as the same job? 

The former is super easy, the later is a bit of a chaos especially since all internal eventing needs to be reset since the whole set of jobs have reached a terminal state.

**Comment by mattclay** [comment]
If restarting as a new job would allow that job, upon completion, to take the place of the previous job for purposes of reporting status for the entire set of jobs (such as updating a PR), then yes.

For example, if 1 of 30 jobs fails, is restarted and then passes, the status for the set of jobs would need to reflect everything passing.

**Comment by jimi-c** [comment]
Yes, restarting in-place would be best. For example, https://app.shippable.com/runs/575705135cde2b0c00589cf3 (job 434.15) failed in a one-off way, so restarting it should delete and recreate 434.15.

**Comment by mattclay** [comment]
This appears to be the same request as issue #794.

**Comment by nitzmahone** [comment]
This would solve a lot of pain- some of our tests that rely on external infrastructure can have spurious failures, and when we're running dozens of those builds at once, the likelihood of at least one spurious failure is quite high... Being able to restart just the failures would be a much more stable path to "everything's green" than rolling the dice with all of them repeatedly.

**Comment by mattclay** [comment]
Has any more consideration been given to implementing this?

**Comment by manishas** [comment]
@mattclay we're discussing internally and will have an update early next week.

**Comment by manishas** [comment]
@mattclay we discussed this and wanted to make sure the following scenario would work for you:

- You have N jobs in your build matrix. For build number 545, these are numbered 545.1, 545.2,...., 545.n

- For build 545, you have some failures, let's say 545.2 and 545.7 fail, while everything else passes.

- You can click on rebuild for those individual jobs. 545.2 and 545.7 will rerun and update the status for build 545. If this was a pull request build, the pull request status will be updated as well.

-  You will lose the previous job information (i.e. console, status, etc) for 545.2 and 545.7 since it will be overwritten by the rebuilt information.

**Comment by mattclay** [comment]
@manishas What you describe sounds good, except for the last item. Losing previous job information would make it very difficult to troubleshoot past failures for reducing or eliminating them in the future.

If the failed job information could preserved, even if located elsewhere in the UI, that would probably be adequate. Just so long as there was some way to get at it after the job had been restarted (possibly multiple times if it failed on subsequent re-runs).

The person(s) reviewing failed jobs may not be the same person(s) who are restarting them, so capturing or reviewing the information before jobs are restarted isn't practical.

**Comment by mattclay** [comment]
@manishas I just thought of another issue with replacing individual job results. We have automated processes that respond to CI failures by downloading results using the API. If those results disappear or change when jobs are restarted, that is going to cause problems for those processes.

Would it be possible to create a new run that contained only the jobs that failed from the previous run, then splice in the results from the previous jobs which succeeded?

For example, the initial run could be:

- 500
  - 500.1 pass
  - 500.2 fail
  - 500.3 fail

Re-running the entire run (failed jobs only) would result in a new run:

- 501
  - 500.1 pass -- This would simply be a reference to the original 500.1 job in the job list.
  - 501.2 pass
  - 501.3 pass

The final status for 501 would work like any normal run, except that that some of the jobs contributing to that status are actually from the previous 500 run.

**Comment by manishas** [comment]
@mattclay let me discuss with the team and get back to you in a couple of days.

**Comment by mattclay** [comment]
Thank you for adding the "Restart failed items" option. This is going to save a lot of time and reduce CI load substantially.

**Comment by manishas** [comment]
Reopening this to fix the problem with the wrong SHA being selected while rerunning.

**Comment by manishas** [comment]
This was fixed in late May. Rerunning failed jobs now gives you a choice of using latest vs original SHA.
