### ISSUE TITLE
error: no PostgreSQL user name specified in startup packet

### ISSUE THREAD

**Issue by jugglerjer** [Shippable/support#2682]
Hello!

I'm unable to get my postgresql database tests to pass. I've attempted to use a variety of configuration strings in combination with users I've created via the shippable.yml.

`pg://postgres@127.0.0.1/heartstrings_test`
`pg://testuser:1234@127.0.0.1:5432/heartstrings_test`

```
language:
  node_js

node_js:
  - 4.4.3

services:
  - postgres

build:
    ci:
      - npm install
      - psql -c "create role testuser login password '1234';" -U postgres
      - psql -c 'create database heartstrings_test;' -U postgres
      - npm run test:ci
```

 The tests consistently fail with the following error:
`error: no PostgreSQL user name specified in startup packet`

Everything runs perfectly in my local environment.

Relevant builds:
https://app.shippable.com/runs/5756561035afea0c00f9942f
https://app.shippable.com/runs/5755297a5cde2b0c00ea23a2

Any help would be much appreciated. Thanks!

**Comment by a-murphy** [comment]
Have you tried ```postgresql://postgres@127.0.0.1:5432/heartstrings_test```?  Or the example for the node module you're using starts with ```postgres://```.

``psql postgresql://postgres@127.0.0.1:5432/test``did not return an error for me, but ``psql pg://postgres@127.0.0.1:5432/test`` did.

**Comment by jugglerjer** [comment]
Same problem with all of these:

`postgresql://postgres@127.0.0.1/heartstrings_test`
`postgres://postgres@127.0.0.1/heartstrings_test`
`postgresql://postgres@127.0.0.1:5432/heartstrings_test`
`postgres://postgres@127.0.0.1:5432/heartstrings_test`

Relevant builds:
https://app.shippable.com/runs/5756f7b597ae890c003eac69
https://app.shippable.com/runs/5756f8405cde2b0c0054c717
https://app.shippable.com/runs/5756f8d597ae890c003f1236
https://app.shippable.com/runs/5756f94b5cde2b0c005535d7

**Comment by a-murphy** [comment]
Sorry, I couldn't reproduce your error.  I tried using `pg` version 4.5.6 with NodeJS version 4.4.3 in a `drydock/u14nodall:prod` image with the string `postgres://postgres@127.0.0.1:5432/app_test` (after creating an `app_test` database) and did not get any errors retrieving an object from the database.  Is there something unusual about how you have it set up?

We have a [sample repository for Node and Postgres](https://github.com/shippableSamples/sample_node_postgres) that uses Knex to connect to Postgres as well.  The shippable.yml file is in the old format, but it still runs.

**Comment by jugglerjer** [comment]
Thanks. Turns out I had updated my test code to include the postgres username but not the actual production code being tested :-/ Everything is worked fine now.

Btw, when will you be adding support for postgres 9.5?

**Comment by manishas** [comment]
Thanks for the update!

We update our images every quarter so the next update is scheduled for the last week of June. We will make sure Postgres 9.5 is included in the update.
