### ISSUE TITLE
Private Repositories Inaccessible to collaborators

### ISSUE THREAD

**Issue by BrilliantBasicsSync** [Shippable/support#2683]
### Private Repositories Inaccessible to collaborators

We have our builds, i.e. https://app.shippable.com/runs/575688f297ae890c00126f02

The failed build link goes into our Slack channel. However, our developers cannot see the build - it says they do not have access (the big red banner across the top). Our developers are collaborators on the GitHub repository in question, and they could view the builds until the Repo was moved to 'private' in GitHub. 

Our developers can still commit to github, and view the branches on Github, but simply cannot view the builds.

Please can you fix this?

Many thanks

**Comment by kanthchandra** [comment]
Hi @BrilliantBasicsSync , We have documented a few FAQ here http://docs.shippable.com/ci_faq/#why-cant-i-see-some-of-my-repositories-in-my-shippable-account . Please take a look at the suggestions there and let us know if it doesn't work for you.

**Comment by bobbydeveaux** [comment]
Thanks - was my personal account that needed Private GH access, not just BB

**Comment by abhijitkini** [comment]
Closing the issue. Let us know if you need further help on this.
