### ISSUE TITLE
Suddenly getting error about certificates but not using SSL at all

### ISSUE THREAD

**Issue by rachellawson** [Shippable/support#2689]
On https://app.shippable.com/runs/5759384097ae890c00a46ed8 I am suddenly seeing errors in my Behat script along the lines of 

Given I am on the homepage # features/Example.feature:7
      cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) (GuzzleHttp\Exception\RequestException)

Which is strange, given I’m never actually using SSL…

Builds failing because of this. I can’t think of anything that has changed to cause it to think SSL is involved in any way.

Any ideas?

**Comment by rachellawson** [comment]
an update and more information…

As it happens, I *am* using SSL but only in a client context - I have a drupal module, CAS, that is trying to contact a public website with a valid SSL certificate. It appears that when that module is enabled, I get the error. Maybe for some reason that php cannot contact a site via https?

Ohh - is there a php.ini thing or a lack of openssl on server possibly causing this?

**Comment by rageshkrishna** [comment]
[The curl error list](https://curl.haxx.se/libcurl/c/libcurl-errors.html) tells me that error 60 is `Peer certificate cannot be authenticated with known CA certificates.`

It's possible that the CA cert for the server you're connecting to doesn't exist in the build container's certificate store, causing curl to fail the certificate validation.

Can you try running the command `update-ca-certificates` before your tests? This should update the cert store with the latest bundle.

**Comment by rachellawson** [comment]
hmm - it is like the certs are updated but curl isn’t reading them?

Running on a (newly built) vm, I can see 

```
vagrant@drupalvm:~$ curl -vvI https://www.horizonsunlimited.com/cas
*   Trying 69.5.16.192...
* Connected to www.horizonsunlimited.com (69.5.16.192) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 694 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / DHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: www.horizonsunlimited.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: OU=Domain Control Validated,OU=EssentialSSL,CN=www.horizonsunlimited.com
* 	 start date: Mon, 21 Sep 2015 00:00:00 GMT
* 	 expire date: Tue, 20 Sep 2016 23:59:59 GMT
* 	 issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> HEAD /cas HTTP/1.1
> Host: www.horizonsunlimited.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Date: Thu, 09 Jun 2016 15:06:12 GMT
Date: Thu, 09 Jun 2016 15:06:12 GMT
< Server: Apache
Server: Apache
< Set-Cookie: SESS78bb81b12f7abd745557fa8b5012cc56=eo9siooir7aet2snmm0bah02c3; expires=Fri, 10-Jun-2016 03:07:52 GMT; path=/; domain=.horizonsunlimited.com
Set-Cookie: SESS78bb81b12f7abd745557fa8b5012cc56=eo9siooir7aet2snmm0bah02c3; expires=Fri, 10-Jun-2016 03:07:52 GMT; path=/; domain=.horizonsunlimited.com
< Expires: Sun, 19 Nov 1978 05:00:00 GMT
Expires: Sun, 19 Nov 1978 05:00:00 GMT
< Last-Modified: Thu, 09 Jun 2016 15:06:12 GMT
Last-Modified: Thu, 09 Jun 2016 15:06:12 GMT
< Cache-Control: store, no-cache, must-revalidate
Cache-Control: store, no-cache, must-revalidate
< Cache-Control: post-check=0, pre-check=0
Cache-Control: post-check=0, pre-check=0
< Content-Type: text/html; charset=utf-8
Content-Type: text/html; charset=utf-8

< 
* Connection #0 to host www.horizonsunlimited.com left intact
```

but I just inserted the same curl command in my shippable.yml to create a result on the CI server and got the linked output…

https://app.shippable.com/runs/5759855e97ae890c00ba9ebd

**Comment by rachellawson** [comment]
(yes, I’m expecting a 404 right now, I’m okay with that)

**Comment by rageshkrishna** [comment]
Hmm, that's odd. It looks like a couple of things going wrong:

1. For some reason curl isn't looking at /etc/ssl/certs/ca-certificates.crt
1. Even if I do `curl -vvI https://www.horizonsunlimited.com/cas --cacert /etc/ssl/certs/ca-certificates.crt` _after_ running `update-ca-certificates`, it still fails validation.

I was able to get it to stop complaining with this:

````
wget http://curl.haxx.se/ca/cacert.pem -O /etc/ssl/certs/ca-certificates.crt
curl -vvI https://www.horizonsunlimited.com/cas --cacert /etc/ssl/certs/ca-certificates.crt
````

I'm not really sure at this point why curl isn't looking at ca-certificates by default. Perhaps we're missing some configuration. I'll take a deeper look and get back to you on this.

**Comment by manishas** [comment]
@rageshkrishna where are we on this?

**Comment by rageshkrishna** [comment]
Sorry, this completely fell off the radar. I'll look in to this and have something to share in a day or two.

**Comment by rageshkrishna** [comment]
@rachellawson Can you try running these two commands before running your tests:

````
wget http://curl.haxx.se/ca/cacert.pem -O /etc/ssl/certs/ca-certificates.crt
echo "cacert=/etc/ssl/certs/ca-certificates.crt" | tee -a ~/.curlrc
````

**Comment by abhijitkini** [comment]
@rachellawson following up to see if the above recommendation worked.

**Comment by abhijitkini** [comment]
@rachellawson please let us know if you need further help with this issue.
