### ISSUE TITLE
Billing question

### ISSUE THREAD

**Issue by benbernard** [Shippable/support#2690]
### Description of your issue:
I signed up for a plan last night for $40/month, but canceled after just an hour of playing because I realized I would need a lot more time to make sure this is the right solution for my company.  I switched back to the free plan, but I was wondering if it would be possible to get a partial refund since I only used about an hour or two of time.

**Comment by manishas** [comment]
@benbernard I'll enter a request for a refund. It will take up to 72 hours to issue it.

We would love to understand what you're looking for and help you get started. Are you available for a hangout sometime today or tomorrow? We're in the PST time zone.

Alternatively you can also send me an email at manisha@shippable.com and I can help with your scenario. Thanks!

**Comment by benbernard** [comment]
Thanks for putting the refund request in!

well, the main thing is that I've got my build sorta working, but as soon as I start my selenium/chrome based browser tests I get a timeout.  I couldn't find anything about being able to ssh or interactively debug that issue, which is something we do all the time with our current provider, circle, and I wasn't really interested in doing debug cycles with a strange system when the iteration steps are 5 mins :).

Maybe there is a container I can run locally to reproduce the problem?  How do you recommend debugging things like this?

**Comment by manishas** [comment]
Thanks for the explanation. One way you can ssh into your build machines to debug is to add your own build nodes to your subscription. This is explained here - http://docs.shippable.com/ci_byoh/ and the instructions are here - http://docs.shippable.com/ci_subscriptions/#ci_byoh

In a nutshell, you can 'attach' your build node to your Shippable subscription, after which all builds for your subscription are routed to your node over which you have full control including SSH access. You can then tail the logs, or you can 'docker exec' into the running container and navigate the file system, make changes, and pretty much do anything you need. 

Adding a build node is something you can do temporarily to debug or leave the build node(s) attached to your subscription to get additional benefits like faster build times, image caching, etc.

Let me know if this helps. Happy to do a quick hangout anytime and chat further.

**Comment by benbernard** [comment]
Yep makes since, but will take some time to setup, thanks for the tips!

**Comment by manishas** [comment]
It takes less than 10 mins to have everything up and running with a node on Digital Ocean or AWS :) 

Our build nodes are c3.large (2 cores, 3.75GB) so you can provision something similar. Plus, you save the 'Provisioning node' time when you kick off the build, which will save ~3mins.

Let me know if you need any help :)

**Comment by abhijitkini** [comment]
@benbernard let us know if you have further questions. We are happy to jump on a Google hangout to answer your questions in real time, as you evaluate Shippable for your company.
