### ISSUE TITLE
Deploy To Maven Manually?

### ISSUE THREAD

**Issue by benoj** [Shippable/support#2691]
I have several libraries which should be deployed manually, Is it possible to have a pipeline to deploy to my private maven repo?

**Comment by manishas** [comment]
@benoj our pipelines currently deploy to container services like Amazon ECS, GKE, Docker Cloud, etc.
Where do you want to deploy your repo? We're in the process of extending pipelines to handle non container workloads so would be good to know your desired workflow.

**Comment by benoj** [comment]
Sure, I have a self contained nexus repository (currently hosted in AWS, however I'm in the process of switching it over to being s3 backed) and am using the maven release plugin to manage releases. What I would ideally like to have is a pipeline which continuously builds and verifies changes to my libraries, but when I want to release I click a manual "release" button which executes the maven release plugin (tagging git and pushing to maven repo)

**Comment by timkral** [comment]
+1 here. We have two flavors of project that we'd like to build and release with Shippable:

1. A service application running in Docker and released to AWS ElasticBeanstalk. Shippable already covers this use case.
2. A set of common Java libraries which support our service applications. For these projects, we'd like to publish the libraries to our privately hosted Maven repository through Shippable Pipelines. I can't seem to find anything in the documentation which speaks to this use case.

Any suggestions about how to get Use Case 2 working?

**Comment by avinci** [comment]
We have released runCLI in addition to runCI. You can create an assembly line that could look something like this. 

1. run CI process using the shippable.yml
1. create a shippable.jobs.yml which has a runCLI job that can push to maven with an IN from runCI job
1. upon completion, runCLI will trigger and push to maven

above can all be done within the CI system also, if you don't have complex dependency logic.
