### ISSUE TITLE
aws_eb_deploy running before "push:"

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2692]
I want to deploy the images that I push.

see: https://app.shippable.com/runs/5759ed355cde2b0c00ee55f6

However, the eb deploy happens before the 'push'...

Shouldn't aws_eb_deploy be after the push?

**Comment by bobbydeveaux** [comment]
# language setting
language: php

# specifying runtime
php:
   '7.0'

env:
  global:
    - secure: KWzBVQZwAOm5Iu0tyMrHT5Oghqa/pAn6LbOrNeGqrPbICzZqHgHhhKIg/cEjT2ikXlTDsMcLZU/anWvFeSdZTMv1uJX73pd7Ddd25v04j90ISIb0gO08bV5aa5s+PUPPQSIeRaWc0pJHyFRtBBksW/YKmGBL4T6N84Eg6Kfmkia8/TGJcbcqXBH8d9ycSMPZN1Y5Ze6Ott8qp0wwQE3RbBHTbNHJOag8wXQJOzgVTrPGA4h+/FlE0Ibf+0E010AuRbSPr0CtlBE035cNEu5+zJ+kMxrlrHSbCRHR64J16SO0lo45NJBlDVK3RT+CZPMJS6xc5qzz3B/BSrHKrpw3UA==
    - secure: C+379fb+JF5kAElT+RSZhPK6SukpcNraSIaiYi0YKGljqS8cJ5bYJ+R4rNYXR7kEyqZpjs3mSnNd2OpvO5zITQAggtNIA67n6fEbqEopXTPL7r7KYUYm9LnZ2G6b+HTJmOvS6Ck6/sJrYe/vQHUFMlP+zxKBz6j5kTsJDi8MtlBju2vdinw8sxdQPC/46NNtLKQfFWnuXF7Y+FTmgtYd5zTpBgG5mhO5NC7TJzLkhXI84UM4X6hncTIsSwMedBZJ+N9PfhM5Qyu1aRcOXwFrXB34ymMKbe30fBiTQLvclbgPBw4ctZQTDAmGEFocvETNPU+pVPpW7dQioBvIDrCvEg==

build:
  # commands in this section run on your build machine and not inside your CI container.
  pre_ci:
    - docker build  --rm=true -t bobbydvo/webapp-release:tip .
    - docker build  --rm=true -t bobbydvo/webapp-release:$BRANCH.$BUILD_NUMBER .
    - docker images

  pre_ci_boot:
    image_name: bobbydvo/webapp-release
    image_tag: tip
    pull: false
    options: "-e HOME=/root"

  # commands in this section run inside your CI container. In addition, any commands such as ls, in this section can be used to skip default processing for CI.
  ci:
    # Here you'd place anything you want to test. For PHP apps, maybe Phpunit?
    - yum -y install python-pip
    - mkdir -p ~/.aws
    - echo '[profile eb-cli]' > ~/.aws/config
    - echo "aws_access_key_id = $AWSAccessKeyId" >> ~/.aws/config
    - echo "aws_secret_access_key = $AWSSecretAccessKey" >> ~/.aws/config
    - cat ~/.aws/config
    - cd /srv
    - mkdir -p .elasticbeanstalk
    - cp beanstalk.yml .elasticbeanstalk/config.yml
    - pip install awsebcli
    - eb init && eb status
    - echo 'No tests.'

  # Everything all good? Let's push this to docker.
  # commands in this section run on your build machine and not inside your CI container.
  push:
    - docker push bobbydvo/webapp-release:tip
    - docker push bobbydvo/webapp-release:$BRANCH.$BUILD_NUMBER

integrations:
  ## Our Docker Hub Integration in Shippable
  hub:
    - integrationName: "DockerHub"
      type: docker
      agent_only: true
      branches:
        only:
          - master
  deploy:
    - integrationName: "BobbyAWS"
      type: aws
      target: adapt-webapp
      platform: "64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1"
      application_name: "Test Application"
      env_name: testenv
      region: eu-west-1
      image_name: "bobbydvo/webapp-release"
      image_tag: "$BRANCH.$BUILD_NUMBER"
      branches:
        only:
          - master

**Comment by a-murphy** [comment]
You should be able to move the commands in `push:` to the end of `ci:`.  Since the image you are pushing has already been built, and docker commands run from within the build container actually run on the host, moving the `docker push` commands will push the images earlier, before the deployment step.

**Comment by bobbydeveaux** [comment]
I believe this has fixed this issue. However, all documentation suggests that anything in ci & post_ci will be run on the container itself, not the build machine. 

I love Shippable, you guys are always great to respond so quickly, and is probably the main reason why I recommend Shippable to others, however some of these hiccups could easily be solved with better documentation. If there is anything I can do to help with this, please let me know! :)

Cheers

**Comment by abhijitkini** [comment]
@bobbydeveaux I would like to clarify that the `pre_ci`, `pre_ci_boot` and `push` run on the build machine and not the container. `ci` runs within the container. You'll see a blog on this shortly.

Thanks for your kind comments on our response time. Regarding documentation, if you see something that needs a change, feel free to submit a PR on our docsV2 repo. It will be reviewed and merged. We appreciate the help.
