### ISSUE TITLE
Delete ECR integration

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#2694]
I created an ECR integration, but I'm unable to delete it. 

```
(Id: 4008) AccountIntegration DELETE failed for :id 574e18721e6d8e0c006a4bef
verbose: accountIntegrations|deleteById|callerId:573a53d9cdcbf10c00e9719c|accountIntegrationId:574e18721e6d8e0c006a4bef|_checkDependencies
```

**Comment by manishas** [comment]
@pwarnock is the ECR integration being used by any project? If so, it should show you the dependencies if you click on the ... as shown below in the gif. You will need to remove the integration from your projects and then delete it.

![show hub dependencies](https://cloud.githubusercontent.com/assets/2983749/15973422/2c667ee4-2ef8-11e6-838c-203ef4805a5e.gif)

**Comment by abhijitkini** [comment]
Closing as resolved. Do let us know if you need further help on this issue.
