### ISSUE TITLE
All steps in a build appear to have been executed twice

### ISSUE THREAD

**Issue by abhijitkini** [Shippable/support#2697]
The console output shows every action in a build executed two times. 

- Link to the build: https://app.shippable.com/runs/575ac25ab4d2260c000e58ee

Rest of the builds appear fine.

**Comment by alexmarkley** [comment]
Glancing around our history I don't see any other builds that exhibit this same behavior. You can see that the same build was definitely provisioned twice, and it secured two different job nodes. Maybe some kind of race condition in your job queuing implementation?

**Comment by a-murphy** [comment]
The cause has been found and corrected and this has not reoccurred.  Builds are reliably queued only once now.
