### ISSUE TITLE
Post build options

### ISSUE THREAD

**Issue by adityajain21** [Shippable/support#2700]
### Description of your issue:
I want a binary file of the source code I build using shippable. It only shows ways to push it to docker hub or use it to deploy on AWS etc. I want to deploy it on my own and only want a binary file out of it. Is it possible?

**Comment by pranaypareek** [comment]
@adityajain21 uploading build artifacts is handled as part of the `shippable.yml` configuration.

You can push the binary to your S3 bucket if you want to use it.

The docs here will guide you with pushing to S3:
http://docs.shippable.com/ci_configure/#build-artifacts

**Comment by adityajain21** [comment]
I dont want to push it. Can I download it from somewhere without it getting exposed anywhere?

**Comment by pranaypareek** [comment]
@adityajain21 We don't store the artifacts for builds. Hence, they cannot be downloaded.

**Comment by pranaypareek** [comment]
@adityajain21 linking this to a feature request issue (https://github.com/Shippable/support/issues/2444) for archiving artifacts and supporting downloads.

We'll be working on this soon. I'll make sure to ping you once we have pushed this feature out. Thanks!
