### ISSUE TITLE
Build job failed at boot_container

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2702]
Job 571.18 for https://app.shippable.com/runs/575f2b1057959d0e00c9a322 failed at boot_container.

What caused this failure? Can anything be done to prevent it in the future?

**Comment by pranaypareek** [comment]
@mattclay thanks for reaching out. We are looking into the problem and will get back to you soon.

**Comment by pranaypareek** [comment]
I looked into this early in the noon. My investigation was inconclusive as I don't have much context on this. I discussed this with @manishas and it was suggested that the issue be looked into by someone who has better familiarity with this.

Hence, I've unassigned myself and assigned this to @ric03uec. I informed him about the discussion prior to the assignment.

**Comment by mattclay** [comment]
Same failure again at boot_container on job 623.10 here: https://app.shippable.com/runs/576099c66a58d80d00ad934f

**Comment by manishas** [comment]
@ric03uec can you investigate?

**Comment by manishas** [comment]
@mattclay did you see this happening again? We haven't been able to find an exact reason for the boot container issue but we have hardened code in this area so I'm hoping this doesn't happen now.

**Comment by mattclay** [comment]
The most recent boot_container failure I've seen is this one from yesterday:

https://app.shippable.com/runs/576b6a262f8d210c005b62f7

**Comment by rageshkrishna** [comment]
@mattclay Do you need the CI containers to run in privileged mode? https://github.com/docker/docker/issues/22710#issuecomment-219001218 seems to indicate that these kinds of errors can happen when running in privileged mode and `/dev` is mounted from the host.

If your tests don't need run run in a privileged container you can try turning it off by adding a `pre_ci_boot` section to your shippable.yml, like so:

````
build:
  pre_ci_boot:
    options: "--privileged=false --net=bridge"
````

By default, we start containers with `--privileged=true --net=bridge`.

**Comment by mattclay** [comment]
@rageshkrishna I've switched all of our CI containers to unprivileged per your suggestion. We do, however, have two jobs which each need to start one additional privileged container to work around issues with AppArmor configuration on the host.

Hopefully this change will reduce the chances of jobs getting stuck at boot_container.

**Comment by mattclay** [comment]
@rageshkrishna We've been running with unprivileged containers, per your suggestion. However, we just hit another boot_container failure here: https://app.shippable.com/runs/577db8f590fa6d0c008db02c

**Comment by rageshkrishna** [comment]
This looks like a new problem. It's complaining about the docker daemon being unresponsive. Is this the first boot_container failure of this sort that you've seen since moving to unprivileged containers?

**Comment by mattclay** [comment]
I believe it is, although I haven't checked every failed build since the change was made.

**Comment by mattclay** [comment]
I haven't seen any of these failures recently, so I'm closing this issue.
