### ISSUE TITLE
Configure projects to run on a specific node

### ISSUE THREAD

**Issue by deanmraz** [Shippable/support#2706]
Currently, we have 2 custom nodes running and I want to target projects run on separate nodes. 
Nodes: https://app.shippable.com/subscriptions/5480a3ebd46935d5fbbf5bed/settings

Is there an easy way to do this?

**Comment by abhijitkini** [comment]
@deanmraz If you are trying to run projects simultaneously on both nodes, it can be done by splitting your tests with the help of 2 env variables so it creates a matrix. On the other hand, if you are looking to specify a node for a project to be executed, it cannot be specified.

If it is neither of the above, could you elaborate the scenario you want to accomplish?

**Comment by deanmraz** [comment]
@abhijitkini We have many projects but some need to ship quicker than the others. For example, I would like the 5+ Client Javascript apps to run on node 1 and the 2 API projects run on node 2. Client projects are stacking up the queue and causing 20 minute+ build times for the API projects.

**Comment by abhijitkini** [comment]
@deanmraz You can serialize across jobs within a project and ensure the jobs wait for their turn to be processed on one node and do not take up an available second node as a resource. You can read more about it in [our documentation](http://docs.shippable.com/ci_projects/#run-parallel-jobs).

However, it looks like you want to serialize across projects  and specify nodes for the project. This scenario is not currently supported.

**Comment by avinci** [comment]
this is not possible with our current architecture. We have listeners at the org level and tough to manage machines at project level.
