### ISSUE TITLE
custom host reset failure: "Problem with MergeList"

### ISSUE THREAD

**Issue by trriplejay** [Shippable/support#2708]
### Description of your issue:

The 'reset' action on a custom node seems to fail.  the `check_64_bit` section has a red check, but the logs on the failing command are in the first `copy_script_remote` section, in the last sudo chown output, where it says something along the lines of "Problem with MergeList".

I can work around this issue by SSHing into my node and doing `sudo apt-get update`, and then clicking 'reset' again in the Shippable UI.  However, this is not ideal.  The reset script should handle this case better.

It's not clear what conditions cause the error, since if I add a new node, then click reset, it works fine.  Perhaps a node that has been in use for awhile can get into a stale state?

**Comment by manishas** [comment]
I am going to close this issue unless we hear this from a customer again.
