### ISSUE TITLE
Couldn't enable bitbucket shared project

### ISSUE THREAD

**Issue by TimurAditazz** [Shippable/support#2709]
(Id: 2002) Owner not found for projectId::5762d2b72a8192902e23efe2
warn: caller:5762d2b501346a0d00959a0c|projects|enableById:5762d2b72a8192902e23efe2|_getValidOwner

**Comment by a-murphy** [comment]
Do you have admin permissions on the Bitbucket repository?  It doesn't look like an owner of that repository has logged in to Shippable.  Admin permissions are required to add the webhook that will trigger builds for code changes.

If you don't have admin permissions, could you ask someone who does to enable it?  And if you do, your permissions on Shippable may be out of date and need to be updated.  You can synchronize your permissions by clicking on the little gear in the top right corner and the the green "sync" button.

**Comment by TimurAditazz** [comment]
Yep, I have write permissions onle

**Comment by abhijitkini** [comment]
[FAQs in our documentation](http://docs.shippable.com/ci_faq/#enabling-a-project-fails-with-the-error) has been updated to include this issue.
