### ISSUE TITLE
build fails with Exception Invalid or no script tags received

### ISSUE THREAD

**Issue by SimonNodel-AI** [Shippable/support#2710]
Looking through the logs I see that the application was built successfully however, build_ci is marked as failed.  Looking at the logs I see this error message:

ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy;ssh-add /tmp/ssh/bbssh; cd /root && /root/4c250a03-6b88-4bd8-9881-47ee4af182f6.sh'
Exception Invalid or no script tags received

Here is the link to the build:
https://app.shippable.com/runs/5762e2d07f14c50c00a64ffe

This is the build section in shippable.yml:

build:
  ci:
    - ssh-agent bash -c 'ssh-add /tmp/ssh/bbssh; npm install --unsafe-perm'

**Comment by SimonNodel-AI** [comment]
Update: 
Just to clarify, npm install would result in postinstall script being executed and it ran build script that completed successfully but, shippable failed with above error.  

adding postbuild script in package.json that echos some text fixed the issue for me.
`
"scripts": {
    "prebuild": "npm run lint",
    "build": "node node_modules/angular-cli/bin/ng build",
    "postbuild": "echo build process done",    
    "postinstall": "typings install && npm run build",
    "lint": "tslint \"src/**/*.ts\""
}
`

**Comment by abhijitkini** [comment]
thanks for the update. closing as resolved.

**Comment by ratpik** [comment]
I am facing this same issue. My npm test throws a bunch of warnings which `Exception Invalid or no script tags received`. Making the tests silent passes the build. Please fix. I need the warnings to be in the report but the build to pass.
