### ISSUE TITLE
automatic sync

### ISSUE THREAD

**Issue by steelorbis** [Shippable/support#2711]
Hi, 

I would like to sync from upstream before each build and push if build is successfull. Would this be possible?

Thanks.

**Comment by steelorbis** [comment]
Hi, 
I see this an essential in a ci process. Is there a way to do this?

**Comment by manishas** [comment]
@steelorbis can you explain your scenario in greater detail?

If you are referring to pushing code from your branch/fork to the parent branch/repo if the CI passes, we support it through our pull request support. When you open a pull request with your changes on GitHub or Bitbucket, we run CI on merged code and report the results on the Github/Bitbucket pull request page. This should give you the confidence that your changes will work with code from upstream before you actually do the merge.

Let me know if this addresses your concern or if i'm misunderstanding your scenario.

**Comment by steelorbis** [comment]
Hi Manisha, 

We would like to keep our branches up to date even before PR. We have two specific needs: 

1) We have an integration branch which is automatically deployed to test environment after each commit. We have a manuel testing process on it so we would like to synch from upstream before manuel testing begins. 

2) Our feature branches can take weeks to complete. So we would prefer to sync after each commit so we are notified of any conflicts as soon as possible. 

Thanks.

**Comment by a-murphy** [comment]
Usually builds involving multiple branches are pull requests.  So you'll have to do this in your script in the shippable.yml file for the branch triggered.  To update the repository to resemble what it would when you open a pull request, unless it is a pull request, you should be able to add something like this to the beginning of the `ci` section (and `pre_ci` if you have it):
```YAML
  - if [ "$IS_PULL_REQUEST" == "false" ]; then git reset --hard origin/master; fi
  - if [ "$IS_PULL_REQUEST" == "false" ]; then git pull origin $BRANCH; fi
```

This example assumes that you want the latest version of the master branch in the same repository and the latest version of the branch you are building.  If you want the updated version of another repository, you may need to add a `git remote add` as well, and if you want a specific commit you'll need to specify that as well.  (The commit the build was triggered for is available in the environment as $COMMIT.)

**Comment by steelorbis** [comment]
When I push the merged code, I get the following error: 

> conq: repository access denied. access via a deployment key is read-only.

I probably need the ssh key for the building machine. Could you give an example for pushing on a successfull build? 

Thanks.

**Comment by steelorbis** [comment]
Hi, 

In the usual shippable flow, git_sync is triggered only once just before build_pre_ci phase. 

If I put this into pre_ci section: 
- if [[ "$BRANCH" =~ SP-.* ]]; then git merge -m '[skip ci]' master; fi 
 
then git_sync is triggered a second time before build_ci phase. So the original commit state is built instead of the merged code. How can I build the merged code in the build_ci phase?

Thanks.

**Comment by a-murphy** [comment]
The repository is cloned separately for the `pre_ci` and `ci` steps, so changes made to the repository in `pre_ci` won't be available in `ci`.  The possible sections in shippable.yml are documented [here](http://docs.shippable.com/ci_configure/#shippableyml-structure).  Only `pre_ci` and `push` run outside the build container.  The rest (`ci`, `post_ci`, `on_success`, and `on_failure`) run in the build container.  So, if you want the merged code in `build_ci`, you should put the merge command in the beginning of the `ci` section (the first section to run in the build container).  If you also need the merged code in `pre_ci` (or `push`), you may need to merge it twice.

**Comment by abhijitkini** [comment]
@steelorbis Please let us know if you need further help on this issue.
