### ISSUE TITLE
Build stuck in Queued mode for more than 2 hours

### ISSUE THREAD

**Issue by byndcivilization** [Shippable/support#2715]
### Description of your issue:
https://app.shippable.com/projects/57193cf42a8192902e1d7e88

**Comment by abhijitkini** [comment]
@byndcivilization we are investigating the issue. Will provide an update soon.

**Comment by byndcivilization** [comment]
The build seemsto have initialized now but its been stuck at parse coverage reports for the last 20 minutes.

**Comment by byndcivilization** [comment]
It looks like the first of three builds has passed, but the remaining two dont seem to be starting. Is there some new setting that I missed?

**Comment by molerat619** [comment]
My builds are also in queu for more than 10 minutes

**Comment by jaecSolutions** [comment]
+1, same here!

**Comment by abhijitkini** [comment]
The issue is now resolved. Builds are now being processed successfully. 
http://status.shippable.com/ 

Do let us know if you continue to see delays in the builds processing.

**Comment by byndcivilization** [comment]
Thanks!

**Comment by manishas** [comment]
Closing since this is fixed.
