### ISSUE TITLE
Display results from multiple runs in build status

### ISSUE THREAD

**Issue by jeradphelps** [Shippable/support#2717]
Github allows for the results of multiple builds to be displayed in the status area of a pull request.  Here is an example of the Travis integration:

<img width="778" alt="screen shot 2016-06-20 at 9 37 07 pm" src="https://cloud.githubusercontent.com/assets/1202792/16217318/7c63ccdc-372f-11e6-879f-d0b6a91685b5.png">

Is this possible with Shippable?  If not, is it planned?

**Comment by manishas** [comment]
We're planning on supporting the Github Checks API, and there are currently no plans to enhance these PR status messages. 

I'm closing this as deferred, but happy to reopen if I see a lot of interest through +1 feedback or multiple reports.
