### ISSUE TITLE
Github submodule checkout not working despite configuring deploy key in github

### ISSUE THREAD

**Issue by sshivaji** [Shippable/support#2718]
I added the deployment key for the submodule checkout but it still says access rights are not present for a private github repo

https://app.shippable.com/runs/5769099c0f480e0b00678236 is the build failure.

**Comment by abhijitkini** [comment]
@sshivaji can you clarify if you added the key from your subscription settings or your own key?

**Comment by sshivaji** [comment]
From subscription settings 

On June 21, 2016, at 10:01 AM, Abhijit Kini <notifications@github.com> wrote:

@sshivaji can you clarify if you added the key from your subscription settings or your own key?

**Comment by a-murphy** [comment]
Copying the key on the subscription settings page and adding it to the repository to be added as a submodule as a deploy key worked for me.  Adding the key to my account as an SSH key works as well.  Would you mind checking that the key was copied correctly?

**Comment by sshivaji** [comment]
Did you try it on my project, it does not work within that project? Should
I create a new project? I tried this a few times already.

Thanks, Shiv

**Comment by a-murphy** [comment]
I can't test it on your project; I've been using my own private GitHub repository to test.

 It shouldn't have anything to do with the project, so creating a new one probably won't help.  I've only been able to get similar errors when I haven't added the key to GitHub.  Where (on GitHub) are you adding the key from the subscription settings tab?  And, is this submodule already in .gitmodules?  (Although, that hasn't gotten a similar error either.)

**Comment by abhijitkini** [comment]
@sshivaji following up on the information requested.

**Comment by abhijitkini** [comment]
Closing. let us know if you need further help on this issue.
