### ISSUE TITLE
Run script on branch delete

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#2719]
We deploy every branch to a new staging server. We want to shutdown that server when the branch is deleted.

The deploy happens at the end of the build script, creating the server if necessary - it would be logical for the build SaaS to delete the deployment when the branch is deleted.

To do that we need to be able to run a script (in yml delete_branch: script).

**Comment by avinci** [comment]
I am not sure I follow this. Are you saying we should listen to webhook delete branch event? IN that case, if the branch is already deleted, how do we get the script from the YML? Is this not going to create a catch 22?

I think the better solution would be to use pipelines workflow where you could create provisioning and de-provioning jobs that can do this for you depending on what events you fire. Just a thought....

I would love to understand your scenario to be able to better provide a solution

**Comment by BryanCrotaz** [comment]
Doh! Of course... this can't be done by the build server after deleting the branch - of course the yml def file isn't available any more. Though it would be nice if we could define a yaml script on the project that is run when a branch is deleted.

**Comment by BryanCrotaz** [comment]
Equally, a yaml script that runs before the first build of a new branch.

**Comment by manishas** [comment]
This isn't currently in the roadmap, so I am closing as deferred. If we hear this feature request from additional folks, we will bring it back in scope.
