### ISSUE TITLE
Saving of cache fails when including [reset minion] or [reset_minion] in commit message

### ISSUE THREAD

**Issue by devillex** [Shippable/support#2721]
I am trying to resolve an issue with a bad cache (node modules). I have tried resetting the cache through the Setting Tab on the project, but this is broken (see #2720). When I include [reset minion] or [reset_minion] in the commit message the cache is successfully cleared for the build, but then saving the cache fails as follows:

```bash
- upload_cache
  - aws s3api put-object --profile shippable --bucket 56fccc619d043da07b0966a5 --key cache/5714c4ad2a8192902e1d0929.tar.gz --body /home/shippable/cache/5714c4ad2a8192902e1d0929.tar.gz 0s  

    The config profile (shippable) could not be found

```

- Link to the build failure

https://app.shippable.com/runs/57692f060f480e0b00705a5b

**Comment by trriplejay** [comment]
Thanks for pointing this out. We've found the problem, and it should be resolved now.  Can you try again and let us know if you're still seeing this issue?

**Comment by trriplejay** [comment]
closing this. please reopen if the problem persists.

**Comment by devillex** [comment]
Thanks for the update @trriplejay.

I tested as requested and the following seems to work:
- Clearing the cache by including '[reset minion]' in the commit message
- Uploading of the 'new' cache during the same build

I did have an error on the next very next build (after clearing the cache) though.

I had the following error during the 'setup_ve' step of the build:
```yml
nvm install "4.4.4"
v4.4.4 is already installed.
nvm is not compatible with the npm config "prefix" option: currently set to "/usr"
Run `npm config delete prefix` or `nvm use --delete-prefix v4.4.4` to unset it.
```

I'm not sure if this is related to this issue (#2721), or whether it is because I am caching the node modules from NVM as follows:
```bash
CURRENT_NVM_VERSION=$(nvm current)
$NVM_DIR/versions/node/$CURRENT_NVM_VERSION/lib/node_modules
```

For reference, the link to the failed build is: https://app.shippable.com/runs/57723ed145eaa40e00c4dede

**Comment by devillex** [comment]
I also tried separately adding `npm config delete prefix` and `nvm use --delete-prefix v4.4.4` to the 'post_ci' section, but still got the same error under 'setup_ve' on subsequent build jobs:
```bash
nvm install "4.4.4"
v4.4.4 is already installed.
nvm is not compatible with the npm config "prefix" option: currently set to "/usr"
Run `npm config delete prefix` or `nvm use --delete-prefix v4.4.4` to unset it.
```

**Comment by devillex** [comment]
Ok, I basically gave up on caching global node modules installed through 'nvm'.

Everything works now. I can confirm that this issue is indeed resolved.
