### ISSUE TITLE
Builds queuing and not starting

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2724]
I have 5 nodes spun up and idle. 

Currently have at least one build that has been in a waiting state for 8+ minutes.

**Comment by chriskinsman** [comment]
Build finally started but now is running very slowly.  20+ minutes for a build that normally runs in ~10 minutes...

**Comment by jeradphelps** [comment]
Currently experiencing similar issues: `Minion Usage: 0 of 2`

**Comment by manishas** [comment]
@jeradphelps @chriskinsman everything should be back to normal now. Are you still seeing issues?

**Comment by jeradphelps** [comment]
Yes, they appear to be running again.  Thank you!
