### ISSUE TITLE
Any way to permanently update npm version?

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2727]
I have found the default npm 2.14 doesn't support http:// based tarball locations.  2.15.1 does.

I can install as a ci step with npm install npm@2.15.1 -g but this adds ~13s to my build. Is there anyway to save this default?

In the past I would just create my own updated docker file with a different version.  Not sure how to do this in the new world...

**Comment by manishas** [comment]
@chriskinsman you can still use a custom Docker image with the desired npm version and specify that image in the pre_ci_boot section. This is explained here- http://docs.shippable.com/ci_configure/#overriding-the-default-build-image

Let me know if this addresses your issue...

**Comment by chriskinsman** [comment]
I suspect it will.  I will give it a try.

Thanks!
