### ISSUE TITLE
Build is NOT triggered

### ISSUE THREAD

**Issue by rlcomte** [Shippable/support#2728]
### Description of your issue:
Our builds stay in waiting state way too long. Nothing is being built on our custom build servers (which are doing nothing...)

**Comment by rlcomte** [comment]
Same issues as #2724

**Comment by kanthchandra** [comment]
Hi @rlcomte can you please point me to the subscription for which the builds are not firing?

**Comment by rlcomte** [comment]
I just saw that after 10-12 minutes the builds are finally started.
Subscription is to-increase.

**Comment by neilberkman** [comment]
Builds are being queued for 20+ minutes.  Your status page doesn't indicate any current issues.

**Comment by manishas** [comment]
We have identified the issue and are working on a fix. I will update this thread with an ETA soon.

**Comment by manishas** [comment]
This should be resolved for most folks.... we're still looking through a couple of issues affecting a handful of customers.

**Comment by abhijitkini** [comment]
The fix is in place and all users should see builds processed normally. Do let us know if you see builds being queued up.
