### ISSUE TITLE
API does not return all runs in waiting state

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2729]
Hello,

I am afraid this will be hard to debug but:
- When I looked at https://app.shippable.com/projects/575fa7472a8192902e2390c7 in the web UI, I saw a run in waiting state.
- When I fetched runs using my API key using "/runs" with subscriptionId=547c792bd46935d5fbbf0b11, the run was not listed.

It eventually turned in ~7mn later when it moved to processing state. Have you ever seen that?

Thanks.

**Comment by pmezard** [comment]
In addition, the hook triggering the build took a very long time to be processed on shippable side, bitbucket reported more than 3s. It is possible the platform was overloaded at that point. What I do not explain is why the web ui and the API disagreed, are they not feeding from the same data source?

**Comment by kanthchandra** [comment]
Hi @pmezard , We were having a few issues with our API response time around the same time you opened the issue. So the system was a little sluggish and things were moving slowly. We have fixed the api response time issues.

The API and the UI are getting the data from the same source. It's just that the UI is sending some extra filters that gets the exact data that it needs. To be precise `https://api.shippable.com/runs?projectIds=575fa7472a8192902e2390c7&status=incomplete` this is the call that the UI made to get all the runs in the waiting state for that project.

The call that you made GET `/runs?subscriptionIds=547c792bd46935d5fbbf0b11` will get all the runs for your subscription and the default limit for that is 100. So you might not have got that run. 

You can refer our documentation http://docs.shippable.com/api/#get-all-runs here to view the list of all valid query params which will give the exact data that you need. Let us know if you want any help with this.

**Comment by pmezard** [comment]
I was assuming the "/runs" endpoint was returning the N latest runs. Is that incorrect? If not, the run I was looking for was clearly in the range.

Thank you for your response, I will use "status" in that particular case.
