### ISSUE TITLE
Consistently failing to clone valid repos

### ISSUE THREAD

**Issue by gappleto97** [Shippable/support#2731]
I have a few submodules as part of my package. It fails consistently to download them, starting today.

1. https://app.shippable.com/runs/576b2be6d77a600c008c7193
2. https://app.shippable.com/runs/576b318d2f8d210c0054501b
3. https://app.shippable.com/runs/576b33262f8d210c0054a53c
4. https://app.shippable.com/runs/576b35fcc05f5b0c001783ab
5. https://app.shippable.com/runs/576b3b91d77a600c008f9349 (still in progress)

Can you let me know what's going on? I can clone this repo myself, and so can the other CIs I'm using.

**Comment by manishas** [comment]
@rageshkrishna can you take a look at this?

**Comment by rageshkrishna** [comment]
At first glance, this seems to be a network issue. @gappleto97 Can we trigger builds on your project to debug this?

**Comment by gappleto97** [comment]
Yes.

**Comment by rageshkrishna** [comment]
@gappleto97 I triggered a build and this time all 7 builds in the matrix ran successfully. It looks like it may have been a networking glitch on a specific host at that point in time.

Unfortunately, there's not much I can do at this point to explore the issue further. Please let me know if you see this happening again and I will try to debug this issue directly on the host that's causing the issue.

**Comment by gappleto97** [comment]
Okay, thanks. I'll close this issue for now.
