### ISSUE TITLE
How to compare builds of the same branch?

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#2732]
Can't see how to go to the previous build of the same branch in the UI when looking at a build run

**Comment by abhijitkini** [comment]
@BryanCrotaz Click on the Project, then go into the History sub-tab of the Project's Status tab. 

Let me know if that answered your question, or if you are looking for something else.
![accessing details of previous builds](https://cloud.githubusercontent.com/assets/14990231/16289905/25896c5c-38ae-11e6-8705-8df6f4cb001d.gif)

**Comment by manishas** [comment]
@BryanCrotaz to add to the comment above, the History tab has a filter that lets you filter by branch and see all builds for a specific branch.

**Comment by BryanCrotaz** [comment]
That's not easy to use - can we have a history tab on a single build which shows the history of that branch please?

**Comment by BryanCrotaz** [comment]
We have 50 active branches

**Comment by manishas** [comment]
How about if we make the branch name on the build page clickable and it goes to the history page with the branch already chosen in the filter so that you get the view you want? Will that work?

**Comment by BryanCrotaz** [comment]
Yes that would work - history tab would be better though

On 23 June 2016 at 19:16, Manisha <notifications@github.com> wrote:

> How about if we make the branch name on the build page clickable and it
> goes to the history page with the branch already chosen in the filter so
> that you get the view you want? Will that work?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Shippable/support/issues/2732#issuecomment-228136939>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB7FC3FWhNgEhfEldIHhPSqH0KUsa0Vwks5qOs2OgaJpZM4I8Y_R>
> .
>



-- 
Bryan Crotaz
Managing Director
Silver Curve

**Comment by avinci** [comment]
this has been fixed in the new UI we launched a couple of weeks ago. Please switch the UI to new UI if you have not been already moved. Everyone will be moved in the first week of July.
