### ISSUE TITLE
Randomly slow instances

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#2734]
In this run: https://app.shippable.com/runs/576bbcdfc05f5b0c002bd2f5
`pip install awscli` took 1m 30s
An `aws s3 cp` command for a single file of ~1KB size took 1m 51s !

In this run before that: https://app.shippable.com/runs/576bbabfc6aa160c00390b96
The same commands took 1s and 0s respectively.

And here's another run from immediately before that where they took a long time again: https://app.shippable.com/runs/576bb06cd77a600c00a08c7e

Something definitely seems wrong with the infrastructure when 0s and 1s commands take more than 1.5 minutes at times. Looking at the job node info, this is not as simple as warm vs cold instances either:

09:48:35 up 2 min,  0 users,  load average: 0.53, 0.43, 0.18 - SLOW
10:32:36 up 46 min,  0 users,  load average: 0.00, 0.04, 0.22 - FAST
10:41:37 up 27 min,  0 users,  load average: 0.00, 0.03, 0.19 - SLOW

**Comment by stephanielingwood** [comment]
Hi @rarkins,

Thanks for letting us know. Sounds like there may have been some transient network slowness on AWS EC2 (all our build nodes are on EC2) while those builds were running. Are you still seeing this in your builds?

Also, the awscli is already installed in the image you're using, so you can remove the `pip install awscli` command from your yml if you'd like.

**Comment by abhijitkini** [comment]
@rarkins are you still seeing the random slowness for the `pip install awscli` step?

**Comment by rarkins** [comment]
I actually haven't had a need to run builds on this repo since then, but will trigger some manually to test soon. Thanks

**Comment by rarkins** [comment]
Actually since removing the need for `pip` and `s3 cp` I'm unable to reproduce anymore, so closing.
