### ISSUE TITLE
Build fails when cache is enabled

### ISSUE THREAD

**Issue by jcgcecilia** [Shippable/support#2736]
### Description of your issue:
The build works fine while building without cache enabled or with [reset_minion] in the commit comment.
Once the cache is enabled the build fails. 
Out build uses a thrift compiler to generate code automatically and it seems that the error is related to that. 

- Link to the build failure
https://app.shippable.com/runs/576bcf91d77a600c00a7d87c
- Scripts called from the yml (optional)
scripts/shippable.sh

**Comment by a-murphy** [comment]
It looks like you are caching the whole build directory.  If you don't actually need the whole directory cached, could you try caching only a subdirectory, as documented [here](http://docs.shippable.com/ci_configure/#caching)?  For instance, adding `$SHIPPABLE_BUILD_DIR/subdirectory` to `cache_dir_list` will just cache the files in that subdirectory of the repository.  We can't guess what you want cached and what will cause problems for your build, so we just cache the folders listed and you'll have to remove any files that you cached and don't want when your build runs.

**Comment by abhijitkini** [comment]
@jcgcecilia let us know if you need further help.
