### ISSUE TITLE
Docker Image Caching?

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#2737]
Are you guys doing any caching of the Docker Images pulled from Docker Hub outside the node that has pulled it?

I built a new image from your DryDock/u14nodpls to add a newer version of npm and the image comes in at 2GB.  A little concerned on the impact to build startup time...

**Comment by manishas** [comment]
@chriskinsman all our official images are already on our AMI so if you start your Dockerfile with `FROM drydock/u14nodpls:prod` the image won't be pulled each time.

**Comment by chriskinsman** [comment]
So then it only has to pull my slice which may be smaller?

**Comment by chriskinsman** [comment]
Also finding after rebuilding the default u14nodpls container it is no longer selecting the right node version for me.  I added node v4.2.2 and set it to the default in my container but when a build is run using that container it is coming up at 0.10.X

**Comment by manishas** [comment]
can you point me to the build?

**Comment by chriskinsman** [comment]
I have given up on this.  Found it was just quicker to install a newer npm as a CI step compared to the overhead of pulling my docker image.  Thanks!
