### ISSUE TITLE
Provision job node takes long time (>5min)

### ISSUE THREAD

**Issue by roman-gliffy** [Shippable/support#2738]
Hi,

How long does it take to provision a node for an account with a subscription?

```
Provision job node
  Info  
Provisioning a node for subscriptionId: 
```

Takes >5 minutes or longer, I'm still waiting.

**Comment by abhijitkini** [comment]
We are working on fixing the issue. We'll have an update soon. Check http://status.shippable.com/ for the latest status.

**Comment by roman-gliffy** [comment]
The status page says it's been resolved, but nodes are still not provisioned.
Could you clarify if things are back to normal?

**Comment by abhijitkini** [comment]
@roman-gliffy Yes, things are back to normal. Can you provide a link to your build?

**Comment by roman-gliffy** [comment]
https://app.shippable.com/runs/576c2493c6aa160c00590077

**Comment by abhijitkini** [comment]
@roman-gliffy the nodes for your build just got provisioned.

**Comment by roman-gliffy** [comment]
Yes, the build run. 
But now page is not rendered :(

**Comment by abhijitkini** [comment]
We know the issue is being caused by MongoDb and are working to fix it. Stay tuned.

**Comment by fedenusy** [comment]
My nodes are still not getting provisioned 😢 

https://app.shippable.com/runs/576c2bcc561e0a0c007082e0

**Comment by fedenusy** [comment]
There we go, just took a while 👍

**Comment by abhijitkini** [comment]
The job nodes have been provisioning normally for the last 2 hours, since we have deployed the fix. Closing as resolved. Do let us know if you see any delay.
