### ISSUE TITLE
Builds stuck at "Provisioning job node"

### ISSUE THREAD

**Issue by Gudahtt** [Shippable/support#2739]
Both of our minions are tied up at the moment on jobs stuck at the "Provisioning job node" phase.

It has been nearly an hour since the builds started, and still no progress.

e.g. https://app.shippable.com/runs/576c07e72f8d210c0082f513

**Comment by Gudahtt** [comment]
Update: They've both just started up again.

**Comment by Gudahtt** [comment]
Was something done, or was the timing coincidental? Curious if this is a known problem and expected to happen again, or if there's something amiss in the shippable.yml or anything.

**Comment by abhijitkini** [comment]
@Gudahtt this was related to an issue we had https://github.com/Shippable/support/issues/2738. 
Nodes are being provisioned normally since we implemented the fix. Do let us know if you see a delay.
