### ISSUE TITLE
Merge Bitbucket and GitHub accounts

### ISSUE THREAD

**Issue by abhijitkini** [Shippable/support#2740]
Per the tweet received: https://twitter.com/GreeneScientist/status/746032258352582656
Trying to merge my accounts [github/bitbucket] since I have one of each. Delete account not working?

Customer has a Bitbucket and a GitHub account each linked to Shippable. Needs the Bitbucket account (https://bitbucket.org/cgreene/) deleted.

**Comment by abhijitkini** [comment]
@trriplejay could you delete the Bitbucket account on our system? https://bitbucket.org/cgreene/

**Comment by trriplejay** [comment]
Account has been deleted. The user should be able to enable bitbucket on his main account now.

**Comment by abhijitkini** [comment]
Closing issue as resolved.
