### ISSUE TITLE
AWS keys

### ISSUE THREAD

**Issue by roman-gliffy** [Shippable/support#2741]
Hi

I'd like to push artifacts to S3 in on_success section. Aws keys are configured in Pipelines -> environments section.

How do I access those keys in the CI? 

Thank you.
R

**Comment by rageshkrishna** [comment]
Hi @roman-gliffy! Integrations configured for pipelines are not currently available in CI. You'll need to set it up in the Settings tab on the project's page. There's an "Integrations" panel on that page where you can pick the integrations you want to use for CI.

**Comment by roman-gliffy** [comment]
Ok, there is account integration with aws. That has project listed.

So how do I access keys listed in that integration within CI or it's not possible?

**Comment by rageshkrishna** [comment]
If you've enabled your AWS integration on the project, we will automatically configure aws-cli in your CI container. You should just be able to do `aws s3 cp something s3://your-bucket/` and upload whatever you need.

**Comment by roman-gliffy** [comment]
Builds still can't see it. Could you take a look, please?
https://app.shippable.com/runs/576cc89c561e0a0c008a543b

```
 build_on_success 7s
  aws configure list 0s  
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                <not set>             None    None
access_key                <not set>             None    None
secret_key                <not set>             None    None
    region                <not set>             None    None

```

**Comment by rageshkrishna** [comment]
Sorry, I forgot to tell you earlier that you also need to require the integration in your YML file. Please add this to your shippable.yml file and everything should be good to go:

````
integrations:
  deploy:
    - integrationName: aws_staging
      type: aws
````

**Comment by roman-gliffy** [comment]
Thanks!
