### ISSUE TITLE
Aaaand mondgodb errorz

### ISSUE THREAD

**Issue by roman-gliffy** [Shippable/support#2742]
Was trying to enable "deploy integration" - it allows double clicks... Guess it was the reason for error below. 

(Id: 666) Database error
error: caller:xxx214bf|ProjectIntegrations|post|_post
{"name":"MongoError","code":11000,"err":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: shippable.projectIntegrations.$accountIntegrationId_1_projectId_1 dup key: { : \"xxx67938\", : \"xxx48bce\" }"}

**Comment by roman-gliffy** [comment]
It didn't cause any problems though, but still looks scary.

**Comment by ankul-shippable** [comment]
@roman-gliffy Thanks for letting us know. We are redoing our UI, this will be fixed there.
