### ISSUE TITLE
Back navigation from build always returns to summary

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2746]
When using the browser's back button while viewing a build, the browser always navigates back to the summary, even if the previous view was history.

To reproduce this, view build history, click on a build, then navigate back and notice you're on the summary tab instead of the history tab.

This is especially annoying if you've used "fetch more" in history to navigate farther back in history, as all of the additional history that was loaded is gone.

**Comment by kanthchandra** [comment]
Hi @mattclay , sorry for the delayed response on this one. We have fixed this some time back. Please let us know if this is still an issue.

**Comment by kanthchandra** [comment]
Closing this as resolved.
