### ISSUE TITLE
Can a new commit auto-cancel a running build?

### ISSUE THREAD

**Issue by fedenusy** [Shippable/support#2747]
While a build is running, if I push a new commit to that build's branch, I'd like the build to auto-cancel in favor of the newer commit. Is this possible?

**Comment by abhijitkini** [comment]
@fedenusy we have this feature request on our roadmap. Currently, I don't have an ETA and I'll notify you when we have an update.

**Comment by fedenusy** [comment]
Great, thanks!

**Comment by ambarish2012** [comment]
@fedenusy this feature is available now in PROD in our [5.4.3](https://github.com/Shippable/pm/wiki/Product-Releases#customer-notifications) release. Please give it a spin and send us feedback if any.

**Comment by fedenusy** [comment]
Just turned it on, thank you!
