### ISSUE TITLE
Cannot enable project through web interface, due to `_getValidOwner` error

### ISSUE THREAD

**Issue by RemiLehe** [Shippable/support#2748]
I tried to add CI to the open-source project Warp (https://bitbucket.org/berkeleylab/warp), using Shippable. However, when I try to enable this project in my Shippable account (through the web interface), I get the following error:
```
(Id: 2002) Owner not found for projectId::5686afb51895ca44746736f1
warn:
caller:XXXXXXXXXXXXXX|projects|enableById:5686afb51895ca44746736f1|_getValidOwner
```

Here is a screen shot:

![screen shot 2016-06-24 at 4 15 22 pm](https://cloud.githubusercontent.com/assets/6685781/16352831/0f418716-3a27-11e6-8aee-87a9dd5cca5b.png)

NB: I removed the caller ID, as I was unsure if it is OK to have this public.

**Comment by abhijitkini** [comment]
@RemiLehe Admin permissions on the Bitbucket (or GitHub) repo is required to enable it as a project. If you still get the error, then go into Account Settings (gear icon on the top right hand navigation bar) and click the green 'Sync' button in the 'Accounts' tab. 

You can also read it about this in our [FAQ](http://docs.shippable.com/ci_faq/#enabling-a-project-fails-with-the-error)

**Comment by RemiLehe** [comment]
OK, great. Thanks for the rapid answer.
