### ISSUE TITLE
Log Configuration in AWS Task Definition

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#2749]
Is there a way to specify the log configuration for an ECS task definition?

I'd like to enable awslogs http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html

I was able to manually configure via AWS dashboard, but subsequent deployment via pipeline replaced the task definition.

**Comment by trriplejay** [comment]
Unfortunately we don't currently support that setting.  It's on our roadmap along with a few other unsupported parameters.

As you noticed, subsequent deploys will create new task definitions that will override any changes you make directly on aws.

I'll mark this as a feature request and we'll update when this support becomes available.

**Comment by manishas** [comment]
@pwarnock I hope you saw the announcement about the new continuous delivery pipelines. You will be able to configure this pretty easily.

Some useful docs links:
Continuous Delivery Pipelines - http://docs.shippable.com/pipelines/overview/
Getting started: http://docs.shippable.com/pipelines/gettingStarted/
Sample pipeline: http://docs.shippable.com/tutorials/pipelines/samplePipeline/

Let me know how we can help you get started. Always happy to jump on a hangout and answer any questions.

**Comment by manishas** [comment]
closing since Log configuration is available in the new pipelines.
