### ISSUE TITLE
index.lock': File exists.

### ISSUE THREAD

**Issue by chssch** [Shippable/support#2751]
### Description of your issue:

I get this on every build, tried a reset:

git checkout -f develop --
fatal: Unable to create '/root/src/github.com/chssch/12k/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.

Link to Build.
https://app.shippable.com/runs/576fafddd7b8e20c0081fa53

**Comment by a-murphy** [comment]
It looks like the partial clone on the cancelled build 34 caused the problem with cloning the repository on the node for your pre_ci step.  Unfortunately, there's not really a way to get out of it right now without resetting the node (or waiting for it to be replaced when it's not busy if it's a Shippable node).

**Comment by abhijitkini** [comment]
@chssch Please let us know if you need further help. Closing the issue.
