### ISSUE TITLE
pipeline not picking up new version

### ISSUE THREAD

**Issue by seanxe** [Shippable/support#2752]
No idea why this has started happening.

Successful CI build: https://app.shippable.com/runs/577045b6d7b8e20c008bd97f

Pipeline isn't picking up new version: 
https://app.shippable.com/cellConfigs/573a1f8668530b0c008179d6/status

Last build version shows as # 25. 

Been working fine - haven't updated shippable.yml for weeks.

Just had to rollback to an older version as build number 25 is broken.

**Comment by trriplejay** [comment]
@seanxe are you still having trouble? it looks like you have a more recent image tag now. Was the tag sync just slow?

**Comment by abhijitkini** [comment]
@seanxe let us know if you need further help with this issue.
