### ISSUE TITLE
Deployment to ECS fails. /home/shippable/cexec/build.sh not found.

### ISSUE THREAD

**Issue by bholzer** [Shippable/support#2754]
I have a Cell with one image being deployed to ECS. The deployment fails with an error from the ecs agent:

`Reason DockerStateError: Container command '/home/shippable/cexec/build.sh' not found or does not exist.`

My builds are using the default Shippable Node.js container.

Any help is much appreciated, thanks.

**Comment by trriplejay** [comment]
It looks like you're pushing the build image and attempting to deploy it.  Our build images have entry points that are set up to run a CI job.  The file that it cannot find is mounted onto the container when a build is run on Shippable, but it does not exist as part of the image itself.

I'd recommend that you docker build and push an image based on your own Dockerfile that will just include your project's dependencies.  Then you can specify your own entry point or starting command, like `npm start`

Let me know if you have any other questions.

**Comment by bholzer** [comment]
Perfect, this is exactly what I was looking for. Thanks.

**Comment by abhijitkini** [comment]
Closing the issue. Let us know if you need further help.
