### ISSUE TITLE
Documentation Request: Many blog posts refer to the old shippable.yml format.

### ISSUE THREAD

**Issue by bholzer** [Shippable/support#2755]
As a new customer, I am running into some confusion when reading older blog posts referring to (what I assume is) the old `shippable.yml` format.

For example, [this post on caching build containers](http://docs.shippable.com/ci_configure/#setting-your-build-image) talks about caching items in the `before_install` section of the yml file which appears to no longer exist.

**Comment by abhijitkini** [comment]
@bholzer thanks for the feedback. You are correct that the older blog posts refer to the old `shippable.yml` format.

A built-in yml translator does translates from the old to the new format. Read more about the translation from the old to the [new format here](http://blog.shippable.com/migrating-to-the-new-build-platform)

We will update the older blogs that reflects this message.

**Comment by abhijitkini** [comment]
The [blog on caching](http://blog.shippable.com/container-caching) has been updated to reflect the above message.
