### ISSUE TITLE
ImportError: cannot import name Config

### ISSUE THREAD

**Issue by bobbydeveaux** [Shippable/support#2757]
I'm opening this ticket to document this problem/solution and I'll immediately close it.

Get a config error when running eb init. 

```
File "/usr/local/lib/python2.7/dist-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 17, in <module>
    from botocore.client import Config
ImportError: cannot import name Config
```

The solution is to pip install --upgrade botocore so that botocore is 1.0.1

refs https://github.com/boto/botocore/issues/593

**Comment by abhijitkini** [comment]
@bobbydeveaux Thanks for logging this error and the solution here.
