### ISSUE TITLE
"Invalid RUN language: python" - unable to run CI for Python project (BitBucket)

### ISSUE THREAD

**Issue by FelixSchwarz** [Shippable/support#2758]
I have a simple Python project on BitBucket and I enabled it via the shippable web ui as usual.

The first thing I noticed is that there is only a "provision" button after enabling the project (which is strange, previously shippable used to start a build immediately and I see a "build" button only).

Then the build immediately fails with the error message "common2|_cleanRunYml|callerId:564c61348bfbdb0d00819146|projectId:577246773be4f4faa56b0bc2|_cleanLanguage Invalid RUN language: python"

build url: https://app.shippable.com/runs/57724c9cd7b8e20c00de1da4
project url: https://app.shippable.com/projects/577246773be4f4faa56b0bc2

My shippable.yml is pretty simple:

    language: python
    
    python:
     # ...
     - "2.7"
     # ...
     - "3.3"
     # ...
     - "3.4"
    
    install:
     # shippable uses pip 1.5 which doesn't understand
     # '--index-url' parameters in requirements.txt
     # upgrading to a newer verson fixes that
     - pip install --upgrade pip
     - pip install -r requirements.txt
     - pip install -r dev_requirements.txt
     - python setup.py develop
    
    before_script:
     - mkdir -p shippable/testresults
    
    script:
     - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml

Probably I'm missing something obvious here but I'm a bit at a loss because similar configurations worked in the past without any problems.

**Comment by rageshkrishna** [comment]
It looks like you may have enabled your repository as an "Infra" project. Please go to the settings page for your project and hit the "Delete" button to undo this, and then head over to the "CI" tab and enable it from there.

Infra projects are meant for terraform deployments and do not allow languages to be specified in the YML.

**Comment by FelixSchwarz** [comment]
Yes, thanks a lot. I didn't notice  that it was in "infra" mode.

Btw: I find the "infra" naming a bit confusing - seems to easy to me to use the wrong mode and the error message doesn't really help. But that's a different issue.

Thank you very much for your quick reply.
