### ISSUE TITLE
npm install - ECONNRESET

### ISSUE THREAD

**Issue by ashernevins** [Shippable/support#2763]
Multiple consecutive builds have failed due to network connection resets during npm install.

I am unsure if this is a localised issue with shippable and npm or a more general networking problem. I can run the builds fine elsewhere.

Example: https://app.shippable.com/runs/5774ca9ad7b8e20c0061b981

**Comment by abhijitkini** [comment]
One of the ways to address network connection resets is to use the [`shippable_retry` command](http://docs.shippable.com/ci_configure/#retrying-a-command) in the `shippable.yml` file. We have a few examples in our [blog](http://blog.shippable.com/automatically-retry-scripts-to-avoid-network-hiccups-during-ci-process). 

Let us know if you see an improvement by implementing this command.

**Comment by abhijitkini** [comment]
@ashernevins Let us know if you need further help with this issue.

**Comment by dchymko** [comment]
@abhijitkini I am also seeing this in our builds. I added the `shippable_retry` command but its frustrating as it means the builds will sometimes take twice as long. We're seeing this with about 1/3 of all the builds that run.  NPM doesn't show any issues on their status page.
