### ISSUE TITLE
Build not faster when cache enabled.

### ISSUE THREAD

**Issue by jcgcecilia** [Shippable/support#2764]
Hi
I am not noticing any improvement in my build times with cache enabled. I haved added a set of directories as explained in the documentation. 
_build:
  cache: true
  cache_dir_list:
    - dir1
    - dir2_

I ignore if I am doing something wrong. I have tried to find similar issues hoping to find a solution for this or at least a hint. No luck so far.

What am I doing wrong?

- https://app.shippable.com/runs/577504a1628e400c00c282a7

Br
JC

**Comment by a-murphy** [comment]
I don't see anything in your build log to indicate that the cache isn't working.  Do you have some way of knowing that the contents of the directories listed aren't available in the next build?

Usually, the directories to cache would be chosen to avoid downloading something every build.  In that case, the installer used will check if it's already there before downloading the cached files, skipping the download and saving time.  Are there files in the directories that you cached that would be reused and not re-downloaded or re-generated on the next build?

All we can do is save the files and put them back for the next build, we can't tell your build what to do with them.

**Comment by jcgcecilia** [comment]
Hi
Thanks for the reply. What I am trying to do is caching building artifacts (many of them are libs) to avoid building the whole project everytime we commit a little change. Basically rebuild what it is needed and not all. 
Is it possible to cache files generated during the build like libs?
Br 
Juan Carlos

**Comment by a-murphy** [comment]
The cache is created at the end, so files created during the build can definitely be cached.  We're not filtering the files cached at all, so anything in the listed directories that `tar -czf` can put in the archive should be saved.  Have you checked if the files were properly restored at the beginning of your build (such as with `ls`)?  And, how is your script determining that the files need to be rebuilt?  Could restoring them from a .tar.gz file be enough to confuse it?

**Comment by jcgcecilia** [comment]
Hi
The files are properly restores at the begining of the build. 
Changing the timestamp of the source files (cpp/hpp) to commit time seems to help. We get faster build times.
Br
JC
