### ISSUE TITLE
Dedicated hosts

### ISSUE THREAD

**Issue by DaHoopster** [Shippable/support#2766]
### Description of your issue:
I found this blog from 2014: http://blog.shippable.com/dedicated-hosts- I'd like to create dedicated hosts for our build. I can't find the __startup__ plan anymore. What do I need to do to set this up?

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by abhijitkini** [comment]
@DaHoopster we support dedicated hosts. Read more about [Bringing Your Own Hosts (BYOH)](http://docs.shippable.com/ci_byoh/) in our documentation.

**Comment by abhijitkini** [comment]
Let us know if you need more help on this issue.
