### ISSUE TITLE
Deploy using custom deploy yaml file

### ISSUE THREAD

**Issue by ggleason** [Shippable/support#2767]
Is it possible to setup shippable to deploy to an ECS cluster based on a custom deploy script using a custom deploy yml file?

For example deploying using this script and the generated deploy yml file it points to.

/usr/local/bin/ecs-cli compose --debug --file generated-deploy.yml --project-name `perl -ne 'print $1 if /SERVICE_NAME:s*(.*)/' generated-deploy.yml` service up

**Comment by manishas** [comment]
@ggleason I think we met at DockerCon last week.. nice to hear from you! 

Our brand new pipelines which we demoed at DockerCon will be available for beta preview next week. Your scenario is supported with the new pipelines. Let me know if you want to try it out. We can also jump on a hangout anytime next week and show you how it works.

**Comment by ggleason** [comment]
What will the new pipelines allow users to do?

**Comment by philipn** [comment]
We (@shotwell-labs) would love to be set up on the beta of pipelines, as well!  We'd be happy to provide feedback on our experience while it's in beta, as well!

**Comment by manishas** [comment]
@philipn that's great news! I'll follow up with you over email and get you on the beta list. Thanks!

**Comment by manishas** [comment]
closing this since we're following up offline on pipelines beta.
