### ISSUE TITLE
Webhook Not working?

### ISSUE THREAD

**Issue by wegenern** [Shippable/support#2769]
I'm trying to get our integration with your services completed.  But we continue to have issues.  Now our webhooks are not being picked up from github?  Are you guys down?

> Sorry, something went wrong and we weren’t able to fetch the deliveries for this hook.

![image](https://cloud.githubusercontent.com/assets/1320655/16537521/00740c2e-3fca-11e6-88b5-31e0e6e4bfd1.png)

**Comment by manishas** [comment]
@wegenern is this a consistent issue or are you seeing this today? As far as we can detect webhooks are working for builds so I don't know if this was a github glitch or something at our end. 

We did notice that your support issue did not trigger a message in our internal slack channels so I suspect it might be a GitHub glitch.

**Comment by wegenern** [comment]
I'll give it go in a little bit.  Hopefully it's just github.

**Comment by manishas** [comment]
Also I notice your webhook is only configured for pull requests and releases. Is that intentional

**Comment by wegenern** [comment]
That is intentional.  It's quite the build.  
Seems to be working now,  thanks for the quick responses!
