### ISSUE TITLE
Pipeline not Deploying

### ISSUE THREAD

**Issue by twillms07** [Shippable/support#2770]
### Description of your issue:
The builds seem to be working fine but the Pipeline doesn't seem to automatically deploying to our cluster all the time. Looking at the Pipeline dashboard you can see the latest build but it's like it's not triggered and deployed. We're really trying to get some fixes out are you able to help us figure this out?

- https://app.shippable.com/subscriptions/5569c022edd7f2c05201b331/pipelines

Thanks,

Todd @ twillms@piiq.co

**Comment by trriplejay** [comment]
it looks like your latest tag synced, but didn't create a new version to be deployed. If you go to your pipeline settings page, you can click 'new version', select the tag from the correct build, and click 'create'.  Once it's created, you can deploy it from your pipeline configuration tab.

Let me know if you have any questions.

**Comment by abhijitkini** [comment]
@twillms07 Closing the issue. Let us know if your issue is still unresolved after implementing the above recommendation.
