### ISSUE TITLE
All builds timing out

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#2772]
### Description of your issue:

This morning my builds are all timing out without assigning a build node. I have a paid plan with 3 nodes total. Example of a build in progress that can't get a node:

![image](https://cloud.githubusercontent.com/assets/6311784/16545019/59940bf8-411c-11e6-9794-971aa9ac1a1e.png)
(https://app.shippable.com/runs/57789b8f30814b0c00420539)

Example of one that did time out:
![image](https://cloud.githubusercontent.com/assets/6311784/16545024/85388216-411c-11e6-9316-4b7e7ba8a931.png)
(https://app.shippable.com/runs/57789b1cae1dd40c00db82c2)

**Comment by rarkins** [comment]
@manishas @a-murphy @abhijitkini @rageshkrishna @spsiddarthan @ric03uec This issue is 100% service impacting because not a single build even *starts*. It cannot wait "1 business day" and I request you look into it immediately as it clearly indicates a serious error in your infrastructure.

I canceled all builds and then tried to retry one. Even though I should have up to 3 concurrent build nodes, this one is in the queue and not even attempting to assign a job node:
![image](https://cloud.githubusercontent.com/assets/6311784/16545043/95f21224-411d-11e6-8780-7799d1a092d6.png)

**Comment by kanthchandra** [comment]
Hi @rarkins , I'm sorry about this, I'm looking into this right now and will update this thread as soon as I have more info.

**Comment by rarkins** [comment]
@kanthchandra thank you!

**Comment by rarkins** [comment]
FYI, the last build that *didn't* time out or need canceling was 19 hours ago: https://app.shippable.com/runs/5777e7ea7e28fe0c001358d4

**Comment by kanthchandra** [comment]
@rarkins , It looks like the outage is because the ami which you are using is not available on AWS and it is affecting only those who are using unstable amis. While I look into why that ami is not available on AWS can you switch to stable AMI and try? (if you absolutely need the unstable ami, I'll need sometime to figure out what's going on).

**Comment by rarkins** [comment]
@kanthchandra Because of my docker compose requirements, I need at least Docker 1.10.0 (I think). Is that supported in stable yet?

**Comment by kanthchandra** [comment]
@rarkins ,unfortunately we have only docker version 1.9.1 on the stable ami. We are working on creating the new ami and it might take some time to create it. I'll update this thread as soon as that is available.

**Comment by rarkins** [comment]
@kanthchandra OK, I'll wait.

**Comment by kanthchandra** [comment]
@rarkins We have started the creation of AMI and it might take 2-3 hours for it to be available. Thanks for your patience. We will update the thread when the new ami is available.

**Comment by rarkins** [comment]
OK

**Comment by kanthchandra** [comment]
Hi @rarkins, can you trigger a build now and see if it works? We have brought up a new AMI and everything should be working now.

**Comment by kanthchandra** [comment]
@rarkins I have verified that nodes are coming up for your subscription on AWS and the build queue us backed up a little, so it might take a few minutes for your current builds to start running.

**Comment by rarkins** [comment]
Currently queued 7 minutes and counting:

![image](https://cloud.githubusercontent.com/assets/6311784/16545526/de0b43b8-412d-11e6-944c-b8ed8b90d056.png)

(https://app.shippable.com/runs/577909046a1a1a0b00d05755)

**Comment by rarkins** [comment]
Yes, it's now building
