### ISSUE TITLE
Avoid project title wrap on Home dashboard

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2774]
The space for project titles in the new dashboard (I love where this is going BTW) is a tad to small on the "Home" view, thus basically all project titles are wrapped and thus harder to read.

Not sure how this could be fixed since all information next to it (branch, last build date, last committer, last commit title) is useful.

**Comment by manishas** [comment]
@mbrodala we improved this a bit.... is your Home view still wrapping most project titles?

**Comment by mbrodala** [comment]
@manishas No, looks perfect now, thanks a lot.
