### ISSUE TITLE
how to build a repository on a different account?

### ISSUE THREAD

**Issue by shrebo** [Shippable/support#2776]
### Description of your issue:

We just subscribed for 4 minions/$30 per month but then realised that building the product repository (hosted on a different github account) does not seem possible. however, short-term we cannot migrate that repository to this account. what do you suggest we should do?

Thank you.

**Comment by abhijitkini** [comment]
@shrebo You can upgrade the right account to be the paid subscription on Shippable and we will refund the amount on the current one.

Let us know which account needs to be refunded and which one you are upgrading.

**Comment by miraculixx** [comment]
great - indeed, did so:

![image](https://cloud.githubusercontent.com/assets/859611/16596199/1c455e68-42f3-11e6-9ee5-260cd5266bde.png)

upgraded: miraculixx
please refund: shrebo

Thank you.

**Comment by abhijitkini** [comment]
@miraculixx Thanks for the info. Refund has been initiated for @shrebo. You should see it on your card soon.
