### ISSUE TITLE
Timeouts are changed to 60 minutes instead of 120 minutes?

### ISSUE THREAD

**Issue by realAkhmed** [Shippable/support#2778]
### Description of your issue:

Hello! It looks like there might have been some change recently with regard to build timeouts.

My builds require occasional build time over 60 minutes. They are not CPU intensive -- it is mostly waiting for some cloud back-end to complete the task.

The recent blog post [here](http://blog.shippable.com/changing-the-default-timeout-for-a-continuous-integration-project) seems to allow one to specify a custom time out but if I choose anything over 60 minutes now, it gives me an error.
```
(Id: 4005) Custom timeout is greater than the maximum limit of 3600000 milliseconds
verbose: projects|putById|callerId:Xxxxxxxxxxxxxxx|projectId:xxxxxxxxxxxx|_validateTimeout
```

I am not sure if the service was downgraded on purpose or this is just a bug?
Having 2 hour timeouts was one of the most attractive features on Shippable.

Thank you for your attention and for an amazing service!

**Comment by manishas** [comment]
@realAkhmed you're right, we recently fixed a bug in our code that set timeouts for free plans to 120 mins. Our limits are: 60 mins for free plans and 120 mins for paid plans.

You can upgrade for as little as $10 and you will get 120 min timeouts as well as an additional build container to run parallel builds.

**Comment by realAkhmed** [comment]
@manishas I see. Thanks for your fast response! 

I haven't been upgrading since I actually need a sequential execution rather than parallel.

Is it possible to use an additional build container (in a paid plan) such that all builds originating from the same Github repo are still sequential? Builds originating from different Github repos can run in parallel.

**Comment by manishas** [comment]
Yes, we support that scenario :)

If you go to your project's Settings page and click on 'Runs config' in the sidebar menu, you can scroll down to the 'Run parallel jobs' section to disable parallel builds for the project. You can even set this for specific branches if needed.

![disable parallel jobs](https://cloud.githubusercontent.com/assets/2983749/16609147/561962e8-4306-11e6-88ca-d74fa9dace65.gif)

http://docs.shippable.com/ci_projects/#runs-config

**Comment by abhijitkini** [comment]
The [blog post](http://blog.shippable.com/changing-the-default-timeout-for-a-continuous-integration-project) has been updated to reflect the default timeouts of 60 minutes (for free plans) and 120 minutes (for paid plans).

**Comment by realAkhmed** [comment]
@manishas Awesome, thanks! I will take a look at it.
