### ISSUE TITLE
npm install - 502 errors

### ISSUE THREAD

**Issue by ashernevins** [Shippable/support#2779]
For a number of hours our builds have been consistently failing during the npm install phase. We are getting 502 errors. I've build my app from multiple different machines at the same time as the shippable builds and all of them work fine, so I suspect this is related to shippable specifically.

Example build: https://app.shippable.com/runs/577cb05c26e8510c0007b087

`npm ERR! fetch failed https://registry.npmjs.org/ordered-ast-traverse/-/ordered-ast-traverse-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/aws-sign/-/aws-sign-0.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/lodash.debounce/-/lodash.debounce-2.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/ps-tree/-/ps-tree-0.0.3.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/ordered-ast-traverse/-/ordered-ast-traverse-0.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/aws-sign/-/aws-sign-0.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/lodash.debounce/-/lodash.debounce-2.4.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.5.tgz
npm ERR! fetch failed https://registry.npmjs.org/ps-tree/-/ps-tree-0.0.3.tgz
npm ERR! fetch failed https://registry.npmjs.org/commander/-/commander-2.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/ordered-ast-traverse/-/ordered-ast-traverse-0.1.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/aws-sign/-/aws-sign-0.2.0.tgz
npm ERR! fetch failed https://registry.npmjs.org/lodash.debounce/-/lodash.debounce-2.4.1.tgz
npm ERR! Linux 3.19.0-51-generic
npm ERR! argv "/root/.nvm/versions/node/v0.12.9/bin/node" "/root/.nvm/versions/node/v0.12.9/bin/npm" "install"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9

npm ERR! fetch failed with status code 502`

**Comment by manishas** [comment]
We believe this is a problem with npm since many folks are running into this right now outside of Shippable - https://twitter.com/search?q=npm%20502&src=typd&lang=en

I think this should resolve itself when the issue is fixed at their end.

**Comment by rageshkrishna** [comment]
Linking to https://github.com/npm/npm/issues/13284
