### ISSUE TITLE
Follow log output

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2780]
It would be useful if Shippable had an option to follow log output which means always scrolling to the bottom on every output.

It currently kind of works for single commands if you manually scroll to the bottom. As long as a single command outputs something, Shippable will automatically keep scrolling to the bottom. As soon as a new command is executed, the scrolling behavior is reset.

(Travis has [something similar](https://github.com/travis-ci/travis-ci/issues/1491)).

**Comment by blackstar257** [comment]
👍

**Comment by ChaitanyaVootla** [comment]
This has been resolved in the new UI, please switch to the new UI if you haven't already

**Comment by mbrodala** [comment]
Seems to work just fine, thanks.

**Comment by mbrodala** [comment]
@ChaitanyaVootla It seems like this has stopped working in the last days. New steps added to the build output still trigger the scroll but it doesn't work for the output of a single step anymore.

**Comment by ChaitanyaVootla** [comment]
@mbrodala thank you for reporting, we are looking into this

**Comment by ChaitanyaVootla** [comment]
@mbrodala this has been fixed a few weeks ago sorry for not getting back to you until now, please close the issue if you don't see the issue anymore.

**Comment by mbrodala** [comment]
Yes, this seems to be fixed again, thanks a lot!
