### ISSUE TITLE
npm cant fetch but https://registry.npmjs.org is reachable

### ISSUE THREAD

**Issue by lutzk** [Shippable/support#2781]
npm install cant fetch from `https://registry.npmjs.org`
`https://registry.npmjs.org` is perfectly reachable from local computer and npm install works well too

failed comand: `- shippable_retry npm install --quiet --progress=false`
link: `https://app.shippable.com/runs/577cde3c26e8510c0012c1ab`

**Comment by rageshkrishna** [comment]
@lutzk npm is currently down for a lot of people. You can follow https://github.com/npm/npm/issues/13284 for updates on the problem.

**Comment by lutzk** [comment]
ok
thank you

**Comment by abhijitkini** [comment]
The [npm issue](https://github.com/npm/npm/issues/13284) is resolved. Please let us know if you continue to see failures.

**Comment by lutzk** [comment]
its building again no failures
