### ISSUE TITLE
Github Organizations

### ISSUE THREAD

**Issue by herriojr** [Shippable/support#2784]
My company uses shippable, and so when I started, I created a shippable account. I expected it to actually add the organization to my list in the hamburger menu but it did not.  I had to first enable private repos and then I had to **Log Out** and then log back in for it to show up.  The log out part either needs to be documented or fixed.

**Comment by RobertSheaO** [comment]
+1, so annoying

**Comment by abhijitkini** [comment]
@herriojr You don't have to log out and log back in, after enabling Shippable's access to your private repos, in order for them to show up on your subscription's dashboard. If they don't show up, you can force sync your permissions between Shippable and your source control management system. To do so, go into the Account Settings (gear icon on the top right navigation bar) and click the 'Sync' button under the 'Accounts' tab.

A [note has been added to the documentation](http://docs.shippable.com/acc_overview/#git-identities) to reflect the same.

**Comment by manishas** [comment]
@herriojr @RobertSheaO To add to the comment above, we completely understand it's annoying to have to enable private repos even after signing in to Shippable. However, this was based on frequent feedback from customers who just wanted to run their public repos and did not have the authorization to grant access to their org private repos. Therefore, we chose a model where you start with minimum permissions and do a one time action of enabling private repos if needed.

Hope that explains the rationale behind the extra step. As Abhijit mentioned above, you can force sync your account to see your private repos after enabling.

**Comment by herriojr** [comment]
In fact I did a sync and it still wouldn't show up. It didn't show up until
I did a log out and log back in. I'll create a dummy account to do it
again.

On Wed, Jul 6, 2016, 12:41 PM Manisha <notifications@github.com> wrote:

> @herriojr <https://github.com/herriojr> @RobertSheaO
> <https://github.com/RobertSheaO> To add to the comment above, we
> completely understand it's annoying to have to enable private repos even
> after signing in to Shippable. However, this was based on frequent feedback
> from customers who just wanted to run their public repos and did not have
> the authorization to grant access to their org private repos. Therefore, we
> chose a model where you start with minimum permissions and do a one time
> action of enabling private repos if needed.
>
> Hope that explains the rationale behind the extra step. As Abhijit
> mentioned above, you can force sync your account to see your private repos
> after enabling.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Shippable/support/issues/2784#issuecomment-230884065>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAP3kNTslMMR2hP3FQlyBRKXH_Mt98b1ks5qTAT5gaJpZM4JGY0C>
> .
>
-- 
Thanks,
Jonathan Herriott

**Comment by herriojr** [comment]
No longer appears to be an issue.
