### ISSUE TITLE
Env Variable Support

### ISSUE THREAD

**Issue by twillms07** [Shippable/support#2785]
Using Env Variables on Multiple Builds:

We're trying to set different values to an environment variable PERSONAS_SERVER_ENV and the documentation indicates that if we do the following: 

  env:
    -PERSONAS_SERVER_ENV=test
    -PERSONAS_SERVER_ENV=integration

This will create multiple builds with the environment variable set different for each of the builds. My confusion is how do I access the different builds and if I want to deploy one to our test environment and the other to our integration environment how is that done? Is that possible? Can we set this up in our pipeline?

Thanks,

Todd

**Comment by twillms07** [comment]
Hi guys - 

I wanted to follow up on this as we're getting ready to start our next round of Alpha testing and I'm hoping that we can use environment variables to help with this.

**Comment by manishas** [comment]
At this time, the best way to achieve your scenario is by deploying through 2 different pipelines. Here is how it will work:

- In your CI workflow, push to the docker registry with different tags depending on environment variable. For example, you can push with the tag $PERSONAS_SERVER_ENV. $BUILD_NUMBER.
- Create 2 pipelines: piiq-test and piiq-integration. For piiq-test, use the auto-increment tag pattern test.* and for piiq-integration, use integration.*

The above config will create 2 docker images for each build - one for test and one for integration - and then the images will be deployed to the correct environment because of the distinct tags. 

Please note that you will need to upgrade your account to buy an additional pipeline, which is $10/mo. 
Let me know if that makes sense.... I'm happy to jump on a call and help configure if you need help.

**Comment by twillms07** [comment]
Awesome thanks Manisha! Let me see if I can figure it out then may ask for
some additional help.

**Comment by abhijitkini** [comment]
@twillms07 let us know if you need further help. closing the issue.

**Comment by twillms07** [comment]
Hi Abhijit - 

For some reason the environment variables are not being picked up and the
builds keep failing. Maybe I¹m missing something I¹ve attached my YAML and
below is the build. I¹ve also included the instructions not sure what I¹m
missing.

Here¹s the URL to the build -
https://app.shippable.com/runs/578031945acb3d0d0041a04c/1/console

At this time, the best way to achieve your scenario is by deploying through
2 different pipelines. Here is how it will work:
* In your CI workflow, push to the docker registry with different tags
depending on environment variable. For example, you can push with the tag
$PERSONAS_SERVER_ENV. $BUILD_NUMBER.
* Create 2 pipelines: piiq-test and piiq-integration. For piiq-test, use the
auto-increment tag pattern test.* and for piiq-integration, use
integration.*



From:  Abhijit Kini <notifications@github.com>
Reply-To:  Shippable/support
<reply+004a65c5385b580417168d64ae84efcca05a0a8ed241624292cf000000011397f1e79
2a169ce09c8e29a@reply.github.com>
Date:  Friday, July 8, 2016 at 3:57 PM
To:  Shippable/support <support@noreply.github.com>
Cc:  Todd Willms <twillms07@gmail.com>, Mention <mention@noreply.github.com>
Subject:  Re: [Shippable/support] Env Variable Support (#2785)


@twillms07 <https://github.com/twillms07>  let us know if you need further
help. closing the issue.


You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Shippable/support/issues/2785#issuecomment-231492041> ,
or mute the thread 
<https://github.com/notifications/unsubscribe/AEplxVm9Wy4h2shbhfRv-H4tfQNvk8
Y5ks5qTtXngaJpZM4JGcUl> .

**Comment by manishas** [comment]
@twillms07 the `env` section needs to be at the same level as `build` and not inside it.... can you try that out?

**Comment by twillms07** [comment]
It looks like it¹s working thanks guys.

From:  Manisha <notifications@github.com>
Reply-To:  Shippable/support
<reply+004a65c51a2e56b89dfb00159ef76e2d0ea2b90139efe8ee92cf00000001139801489
2a169ce09c8e29a@reply.github.com>
Date:  Friday, July 8, 2016 at 5:03 PM
To:  Shippable/support <support@noreply.github.com>
Cc:  Todd Willms <twillms07@gmail.com>, Mention <mention@noreply.github.com>
Subject:  Re: [Shippable/support] Env Variable Support (#2785)


@twillms07 <https://github.com/twillms07>  the env section needs to be at
the same level as build and not inside it.... can you try that out?


You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Shippable/support/issues/2785#issuecomment-231500028> ,
or mute the thread 
<https://github.com/notifications/unsubscribe/AEplxeGEfGgu3DJLi56OB_dl-pPUgk
xLks5qTuVIgaJpZM4JGcUl> .

**Comment by twillms07** [comment]
Hi Mannish - 

Sorry to keep bothering you with this but my guys are blocked because I keep
wrecking our config. So the environments are being built successfully but
when I log onto the docker container on AWS and do a

printenv here¹s what I get -

PERSONAS_SERVER_ENV=


Caused by: com.typesafe.config.ConfigException$BadPath: path parameter:
Invalid path 'environment.': path has a leading, trailing, or two adjacent
period '.' (use quoted "" empty string if you want an empty element)

at 
com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:170)

at 
com.typesafe.config.impl.PathParser.parsePathExpression(PathParser.java:74)

at com.typesafe.config.impl.PathParser.parsePath(PathParser.java:61)

at com.typesafe.config.impl.Path.newPath(Path.java:230)

at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)

at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:258)

at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:264)

at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:37)

at co.piiq.phantom.database.connector.Connector$.<init>(Connector.scala:19)

at co.piiq.phantom.database.connector.Connector$.<clinit>(Connector.scala)

... 17 more

19:35:16.883 - [undefined][Cluster(akka://Personas)]
Cluster(akka://Personas) Cluster Node [akka.tcp://Personas@localhost:1551] -
Node [akka.tcp://Personas@localhost:1551] is JOINING, roles []

19:35:17.892 - [undefined][Cluster(akka://Personas)]
Cluster(akka://Personas) Cluster Node [akka.tcp://Personas@localhost:1551] -
Leader is moving node [akka.tcp://Personas@localhost:1551] to [Up]

[ec2-user@ip-10-0-0-106 ~]$ docker exec -it 47534b2f847b /bin/bash

bash: /root/.bashrc: Permission denied

daemon@47534b2f847b:/data$ printenv

HOSTNAME=47534b2f847b

SCALA_VERSION=2.11.5

INITRD=No

SCALA_PKG=scala-2.11.5

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

PERSONAS_SERVER_ENV=

PWD=/data

JAVA_HOME=/usr/lib/jvm/java-8-oracle

LANG=en_US.UTF-8

SHLVL=1

HOME=/root

DEBIAN_FRONTEND=noninteractive

_=/usr/bin/printenv

daemon@47534b2f847b:/data$



In the application we¹re trying to use that environment variable to
determine what cassandra node to connect to. Is this something we can do
with Shippable?

From:  Manisha <notifications@github.com>
Reply-To:  Shippable/support
<reply+004a65c51a2e56b89dfb00159ef76e2d0ea2b90139efe8ee92cf00000001139801489
2a169ce09c8e29a@reply.github.com>
Date:  Friday, July 8, 2016 at 5:03 PM
To:  Shippable/support <support@noreply.github.com>
Cc:  Todd Willms <twillms07@gmail.com>, Mention <mention@noreply.github.com>
Subject:  Re: [Shippable/support] Env Variable Support (#2785)


@twillms07 <https://github.com/twillms07>  the env section needs to be at
the same level as build and not inside it.... can you try that out?


You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Shippable/support/issues/2785#issuecomment-231500028> ,
or mute the thread 
<https://github.com/notifications/unsubscribe/AEplxeGEfGgu3DJLi56OB_dl-pPUgk
xLks5qTuVIgaJpZM4JGcUl> .

**Comment by a-murphy** [comment]
It looks like you've added a config to a manifest in your pipeline, but haven't set a value in your environment.  If you were expecting `PERSONAS_SEVER_ENV` to be nonempty,  you can set a value on the cellConfig page. From your subscription  pipelines tab, click on your pipeline in the correct environment ( the column on the right) and then the "Configuration" tab.  Here you can enter environment variables for this pipeline in this environment.  Remember to click "Deploy" after entering the new value to update it.
