### ISSUE TITLE
Change EBS deploy version label

### ISSUE THREAD

**Issue by bpujos** [Shippable/support#2788]
Hi,
is there a way to set the version label used when deploying to AWS Elastic Beanstalk when using the template ?
integrations:
  deploy:
    - integrationName: "aws"
      type: aws
      target: eb_paas
      platform: "Node.js"
      application_name: sample-node-eb-paas-app
      env_name: sample-node-eb-paas-env
      region: us-east-1
Thanks for your help!
bertrand

**Comment by trriplejay** [comment]
currently we are internally setting that field, and it can't be changed.  Sounds like a reasonable feature request though :)

**Comment by bpujos** [comment]
Thanks!Bertrand 




On Thu, Jul 7, 2016 at 10:47 PM -0300, "John Stockbauer" <notifications@github.com> wrote:












currently we are internally setting that field, and it can't be changed.  Sounds like a reasonable feature request though :)

**Comment by manishas** [comment]
The recommended approach for deploying to EBS is now with a [runSh job](http://docs.shippable.com/platform/workflow/job/runsh/). Closing this as deferred since we're not enhancing the `deploy` section in CI part of shippable.yml.
