### ISSUE TITLE
Run multiple scripts in parallel

### ISSUE THREAD

**Issue by colinbankier** [Shippable/support#279]
I am considering moving to Shippable from our current CI service, semaphore.
A key feature I found missing was the ability to run script steps in parallel as part of the same build - ie run unit tests one minion and cucumber tests on another - and have the results as part of the same build.
Using multiple "env" elements to trigger multiple builds did not prove adequate for my needs.
For us this would be a key feature to add.
For example Semaphore implement this: https://semaphoreapp.com/parallelism

**Comment by oppianmatt** [comment]
I'm finding that if one of the minions in the test groups fail, the others see a success and the on_success code still runs. Or if both minions have success the on_success/push stuff runs twice. The build groups if they have one status, need to have a hook for that one status
