### ISSUE TITLE
Pull request not using docker image from shippable.yml but instead cached version

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#2790]
We have an issue with caching of docker images. We have changed the shippable.yml file in the pull request to use a new docker image e.g. version 1.12. But when building (even when resetting the minion, clearing the cache from shippable.com) it still uses the cached version (version 1.11)

The build failure can be seen here:
https://app.shippable.com/runs/577f9edf6519cb0c002c072f/1/console

Thank you very much in advance.

**Comment by a-murphy** [comment]
Caching won't save the image tag.  For some reason, your build thinks that your shippable.yml specified tag 1.11.  I've tried to reproduce this by creating a new branch, changing the tag in `pre_ci_boot`, and opening a pull request to my original branch.  Unfortunately, it used the new tag in the pull request build like it should.

The shippable.yml used for pull requests is the result of merging the changes in the pull request into the shippable.yml of the base branch.  Is there anything unusual about your pull request that could have resulted in the two files not being merged as expected?  Most merge errors will result in an error in the build logs, so it was most likely either a successful (but not as expected) merge or we didn't find your updated shippable.yml in the list of files updated by the pull request.

**Comment by jeppefrandsen** [comment]
I tried creating a new branch and changing the docker image name and here it works. Do not know what is wrong with this branch. Closing the issue
