### ISSUE TITLE
Not possible to dynamically configure pre_ci_boot image

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#2793]
I would like to be able to dynamically configure the pre_ci_boot image as we have multiple build targets and docker images for the same repository. I use two environment variables this which is set in pre_ci. However it seems as pre_ci_boot is not able to use these:

https://app.shippable.com/runs/57810809b020cd0c00587366/1/console

It works if I define the image name and tag as global environment variables but not if I define or export the values in pre_ci. Is there another way of doing this? 

Thank you very much in advance

**Comment by manishas** [comment]
@jeppefrandsen can you share your shippable.yml? especially the pre_ci and pre_ci_boot sections

**Comment by jeppefrandsen** [comment]
@manishas yes, of cause:

build:
  pre_ci:
    - export IMAGE_NAME=`./build.sh -t $PLATFORM -n`
    - export IMAGE_TAG=`./build.sh -t $PLATFORM -o`
  pre_ci_boot:
    image_name: $IMAGE_NAME
    image_tag: $IMAGE_TAG
    pull: true
    options: "-e HOME=/root"

if I define IMAGE_NAME and IMAGE_TAG in env global it works fine. The idea is that we define PLATFORM when triggering nightly builds via the Shippable API. The docker image name and tag is then retrieved from the build.sh script (used to only define the tags in one place).

**Comment by jeppefrandsen** [comment]
The complete shippable.yml is now attached. Thanks.

**Comment by jeppefrandsen** [comment]
I think I will manage to use global environment variables together with the test program so closing the issue. Thank you anyway for a great support!
