### ISSUE TITLE
integrating shippable to our GitLab CE

### ISSUE THREAD

**Issue by DavidMont** [Shippable/support#2794]
Im having problem integrating shippable to our GitLab CE

```
(Id: 2002) Owner not found for projectId::578317bb3be4f4faa56c6451
warn: caller:5783161b6519cb0c0083380e|projects|enableById:578317bb3be4f4faa56c6451|_getValidOwner
```

**Comment by abhijitkini** [comment]
@DavidMont Admin permissions on the repository are required to enable it as a project on Shippable's platform. If an admin on the repo has already enabled it as a project & you are still getting the error, synchronize your permissions by clicking on the Account settings (gear icon in the top navigation bar) and clicking the Sync button.

**Comment by abhijitkini** [comment]
@DavidMont We have this error documented in [the troubleshooting section](http://docs.shippable.com/ci_troubleshoot/#owner-not-found) for reference. Let us know if you continue to have the same error even after implementing the above recommendation.

**Comment by DavidMont** [comment]
@abhijitkini yes im one of the admins, I don't know why but I did follow the instructions.

**Comment by abhijitkini** [comment]
@DavidMont Could you check the permissions on the project itself and confirm if you are an owner or master?

**Comment by DavidMont** [comment]
@abhijitkini yes I am, master & owner

**Comment by shrivara** [comment]
@DavidMont There is no change required in Gitlab CE. Could you provide us the Shippable account ID(found in account settings) with which you are adding the account integration and the version of Gitlab CE you are running to investigate this further?

**Comment by abhijitkini** [comment]
@DavidMont Following up for your Shippable account ID and version of GitLab CE to dig into this.

**Comment by manishas** [comment]
I am closing this issue since we cannot proceed without the GitLab CE version information. @DavidMont we will reopen and investigate when we have this info, Thanks!

**Comment by DavidMont** [comment]
Shippable ID
57f358a86d80900e003aa302

GitLab Community Edition 8.4.2 8d07b81

**Comment by DavidMont** [comment]
(Id: 2002) Owner not found for projectId:578317bb3be4f4faa56c6451
warn: projects|enableById|callerId:57f358a86d80900e003aa302|projectId:578317bb3be4f4faa56c6451|_getValidOwner

again im having problem.

**Comment by knowredev** [comment]
I have the same error. The error message is:

```
(Id: 2002) Owner not found for projectId:58579de6f1e544100066d502
warn: projects|getById|callerId:566ff1261895ca4474665b13|projectId:58579de6f1e544100066d502|_getProjectOwner
```

My shippable ID is: 566ff1261895ca4474665b13
GitLab CE version: 8.13.3-0
