### ISSUE TITLE
Menu is very unclear

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#2795]
When you open the menu, it is quite unclear what you are looking at. I see myself and my company twice in the menu, after opening them, it seems to be github and bitbucket, but the menuitem doesn't show that at all which is not that good for the user experience ;)

![image](https://cloud.githubusercontent.com/assets/3294970/16726534/f1f2594a-475c-11e6-9e89-cac6e0c1f5d6.png)

**Comment by abhijitkini** [comment]
@bbrala I agree it can be confusing especially if the avatars across GitHub and Bitbucket are the same. Marking this as a feature request to better the user experience.

**Comment by bbrala** [comment]
Yeah, and really, as a company you would have every avatar the same mostly :) Looking forward to an update sometime in the future.

**Comment by manishas** [comment]
@rageshkrishna can we address this? We need some indicator in the Subscription dropdown menu that shows which source control provider it is associated with.

**Comment by avinci** [comment]
this has been fixed in the new UI we launched a couple of weeks ago. Please switch the UI to new UI if you have not been already moved. Everyone will be moved in the first week of July.

**Comment by bbrala** [comment]
Yeah i saw the changes, thanks :)
