### ISSUE TITLE
Bitbucket webhooks do not trigger builds

### ISSUE THREAD

**Issue by limestreet** [Shippable/support#2797]
From few hours my builds are not triggered by pushing to bitbucket.org repo. I tried few times but nothing happened...
Link to project: https://app.shippable.com/projects/577b908a3be4f4faa56bcee4/status/

Thanks in advance.

**Comment by limestreet** [comment]
Now it is working :) Thanks a lot!

**Comment by abhijitkini** [comment]
@limestreet Glad the builds are being triggered :) Let us know if you need further help with this issue.
