### ISSUE TITLE
build failing because it's claiming I don't have an integration by that name

### ISSUE THREAD

**Issue by x110dc** [Shippable/support#2798]
### Description of your issue:

The build is complaining that I don't have an integration by that name, but I do. 

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/runs/57843e9e2f55e60c0085a40d/1/console

**Comment by x110dc** [comment]
<img width="843" alt="screenshot 2016-07-11 19 52 46" src="https://cloud.githubusercontent.com/assets/1091864/16751716/465522c6-47a1-11e6-8f86-c424ed0aa8ec.png">

**Comment by a-murphy** [comment]
Could you check that the integration has been added to your subscription on the subscription settings tab?  Project integrations were moved to the subscription recently.  So, adding the account integration to the project to give it access to the integration has been replaced by adding it to the subscription.  Once you add the the integration to the subscription, all projects in that subscription should be able to use it.

**Comment by x110dc** [comment]
Oh. I think I understand now. I didn't realize I had to add the integration and then add the integration to the subscription as well. I think that's it. Thanks!

**Comment by abhijitkini** [comment]
@x110dc Let us know if you need further help with this issue.
