### ISSUE TITLE
BYOH on CentOS ?

### ISSUE THREAD

**Issue by mdespriee** [Shippable/support#2799]
Hi,
I'm interested to the BYOH feature for a customer project.
Unfortunately, this customer only uses CentOS and not Ubuntu, and your doc mentions that you only support Ubuntu.
Is there a way to make it work on CentOS ?

Thanks
Mathieu

**Comment by abhijitkini** [comment]
@mdespriee Currently we only support Ubuntu. I will put this as a feature request.

**Comment by bobbydeveaux** [comment]
All my builds are CentOs.. you just have to use your own build image.. ?

**Comment by mdespriee** [comment]
@Bobby, i'm not talking about the docker images for builds, but about the
setup of my own build workers ('bring your own host' option of shippable)

Le 14 juil. 2016 12:34 PM, "Bobby DeVeaux" <notifications@github.com> a
écrit :

**Comment by mdespriee** [comment]
@abhijitkini : a version of the script for a docker enabled host (so, making the script independant of the host OS) would be fine as well.

**Comment by ambarish2012** [comment]
@mdespriee we have added support for BYON CentOS. The setup instructions can be found [here](http://docs.shippable.com/platform/tutorial/workflow/jobs-centos/).
