### ISSUE TITLE
shippable.yml file gets cached when building for a pull request

### ISSUE THREAD

**Issue by maxhudson** [Shippable/support#2801]
When building for a pull, shippable uses the shippable.yml you commit. When building for a pull, it uses the the shippable.yml for the first commit in the pull request, and then ignores updates to the shippable.yml for subsequent commits before the pull request gets closed.

If this isn't a bug, it's not clear that the software will behave this way. At minimum a note should be left in app.shippable.com/projects/{project-id}/settings/runs next to the pull request run toggle.

**Comment by a-murphy** [comment]
I haven't been able to reproduce this.  Multiple commits on a pull request to change the `shippable.yml` file resulted in pull request builds reflecting all of the changes made at the point the build was created.  We don't cache the `shippable.yml` files used to generate builds.  In the case of a pull request build, we will use the latest version of the file in the base branch combined with the changes in the pull request to match what the `shippable.yml` file will be after merging.  Is there a particular section of the `shippable.yml` file that you didn't see update?

**Comment by maxhudson** [comment]
Sorry, I didn't provide quite enough specificity. This only happens when you have automatic building for Pull Requests enabled (with building for commits disabled). If you have commits and pull request building enabled (on Shippable), then it works fine.

**Comment by a-murphy** [comment]
I'm still not seeing this error; multiple commits on a pull request made with commit builds disabled reflected all of the changes at the point that each was triggered.  It's very strange that your pull request builds aren't working as expected with commit builds disabled, but work when they're enabled.  GitHub and Bitbucket send separate webhooks for the pull request update and the commit, so those builds are processed separately.  Meaning that we fetch the shippable.yml separately for the pull request build whether or not commit builds are enabled.  It is possible in a few cases that we don't have the permissions needed to get the changes when the pull request is from another repository, but then you wouldn't be getting the changes made in the first commit.  Would you mind including which of your projects isn't working as expected and what was expected?

**Comment by abhijitkini** [comment]
@maxhudson following up for information on your projects that is having the issue.

**Comment by abhijitkini** [comment]
@maxhudson Closing the issue for now. We'll re-open and proceed once we have information about the projects that isn't working.
