### ISSUE TITLE
Slack integration not working

### ISSUE THREAD

**Issue by ashernevins** [Shippable/support#2802]
Slack notifications are not working most of the time. For the last 10 builds we have gotten a total of 2 messages (should be 20).

https://app.shippable.com/subscriptions/562f31171895ca4474213cff

**Comment by ankul-shippable** [comment]
Hi @ashernevins, we have changed our default behavior for slack notification, Please check if you a slack integrations configured in your shippable.yml as well as in subscription Settings Integrations.
Please check our [updated docs](http://docs.shippable.com/ci_subscriptions/#integrations) for subscription integrations. Thanks

**Comment by manishas** [comment]
More details here: http://blog.shippable.com/slack-elastic-beanstalk-and-ui-changes-in-july1-update
