### ISSUE TITLE
Getting the API job id from the environment

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2806]
Is there a way to find the job id (for use with the Shippable API) from the environment?

The documentation lists a few environment variables which seem promising, unfortunately none of them have the correct id:
- JOB_ID - This matches the projectId from the job.
- SHIPPABLE_JOB_ID - This matches the jobNumber from the job.
- SHIPPABLE_BUILD_ID - This matches the runId from the job.
- BUILD_NUMBER - This matches the runNumber from the job.

**Comment by manishas** [comment]
@mattclay can you describe your scenario as to why you need the job id? you're right the JOB_ID right now does not contain the right value, but a description of your scenario will help me suggest an approach.

**Comment by mattclay** [comment]
@manishas I'm sending the job id to an external API which then uses it to look up the job using the Shippable API. I've worked around the issue for now by using the Shippable API to get all the jobs for the run, then finding the job id from the job number.

**Comment by chetantarale** [comment]
Fix for this requires a big change. We will need to discuss about this.

**Comment by mattclay** [comment]
Since I have a usable work-around, don't spend too much effort on this. I thought it might be a quick fix, but it sounds like it's not.

**Comment by avinci** [comment]
closing this as it not required.

**Comment by kartikluke** [comment]
@manishas One scenario where this is useful and I was hoping to be able to use this is to retrieve the jobTestReports. Also it's confusing that the value returned is incorrect. You should change the documentation [here](http://docs.shippable.com/ci/advancedOptions/environmentVariables/#injecting-global-env-variables) to indicate the value is incorrect.

@mattclay 's solution works. But the info that he posted about what the values represented is pretty important and should be documented.

**Comment by manishas** [comment]
@kartikluke Looking at this again, the value shouldn't be incorrect in the first place :(

I'm following up on why we thought this was a major change....

**Comment by kartikluke** [comment]
@manishas Yeah I think that would be the best course of action. Could you open the issue so I'll be notified when it's rectified and closed.

**Comment by manishas** [comment]
This has been fixed. JOB_ID should now contain the correct value.
