### ISSUE TITLE
GCR 403 Forbidden

### ISSUE THREAD

**Issue by 360itsolution** [Shippable/support#2809]
I am getting a 403 forbidden error when trying to do a docker push to my google container registry.  I have setup the integration and downloaded the key json file for authentication from the Google Container Engine Service account.  I have added that integration in my shippable.yml.  When I used docker push in the "on_success" section it gives me a 403 and errors out the build.  I have tried creating the push: section and including the push statements only to have the same 403 error.  I am 3 days into trying to get this to build and am unclear on what I am missing.  Please help.
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure: https://app.shippable.com/runs/5787becc080eef0c0014009f/1/console
Here is the screen shot of the build.http://screenpresso.com/=S4fUd
- Scripts called from the yml (optional)

# language setting
language: node_js

# version numbers, testing against one version of node
node_js:
    - 0.12
env:
    - XUNIT_FILE=../shippable/testresults/result.xml API_PORT=3001
build:
   pre_ci:
    - cd micro-api && docker build -t micro-api .
   pre_ci_boot:
    image_name: drydock/u14nod
    image_tag: prod
    pull: false

   ci:
    - mkdir -p ../shippable/testresults
    - mkdir -p ../shippable/codecoverage
    - cd micro-api
    - npm install
    - npm install -g grunt-cli
    - grunt

   on_success:
    - cd ..
    - cd micro-www && docker build -t micro-www .
    - docker tag -f micro-www:latest gcr.io/dealerbible/micro-www:latest
    - docker tag -f micro-api:latest gcr.io/dealerbible/micro-api:latest
    #- gcloud config set account container-engine-service-accou@dealerbible.iam.gserviceaccount.com
    - docker push gcr.io/dealerbible/micro-api:latest
    - docker push gcr.io/dealerbible/micro-www:latest
hub:
  - integrationName: gcr-integration-project
    type: gcr

**Comment by a-murphy** [comment]
The `hub` integration in your shippable.yml should be in an `integrations` section, which is why the build doesn't have your credentials.  The structure is shown [here](http://docs.shippable.com/ci_configure/#shippableyml-structure).

**Comment by 360itsolution** [comment]
Wow, thank you, I have been starring at the screen to long...I am getting
this now...

http://screenpresso.com/=hEtIb

Brian Head
cell:918-830-2732
Director of Operations
Nelson Auto Group

**Comment by a-murphy** [comment]
It looks like it's something about your GCR key.  Perhaps it doesn't have a permission that it needs.  Did you follow our [documentation](http://docs.shippable.com/int_docker_registries/#google-container-registry-gcr) to create the JSON key?

**Comment by abhijitkini** [comment]
@360itsolution let us know if you need further help with your issue.

**Comment by 360itsolution** [comment]
Yes we are good.  You guys are awesome!  I re-setup the json service
account and updated the integration and worked!  Shippable is awesome!

Brian Head
cell:918-830-2732
Director of Operations
Nelson Auto Group
