### ISSUE TITLE
How to disable run build for master branch when you pushing PR

### ISSUE THREAD

**Issue by slavikg** [Shippable/support#2810]
When I push commits to PR Shippable automatically run build for PR and master. How to disable run build for master? Thank.

**Comment by abhijitkini** [comment]
@slavikg Would like to clarify if you are looking to disable running a build on the master branch only for Pull Requests (PR), while keep it enabled for other branches?

You can disable running of builds for a project for all Pull Requests, for all branches. Go to the 'Project' Settings, 'Runs Config' section and scroll down to 'Configure Webhook Events for Triggering Builds'. Click the 'Disable' button for Pull Requests. More details in [our documentation](http://docs.shippable.com/ci_projects/#runs-config). 

![disable build runs for prs](https://cloud.githubusercontent.com/assets/14990231/16882592/b216a25c-4a74-11e6-900e-2f21321beede.gif)

**Comment by manishas** [comment]
@slavikg if you have an open PR and submit further commits, we will build the merged commit each time. There is currently no way to turn off this behavior.

As Abhijit mentions above, you can turn off PR builds completely if needed.
