### ISSUE TITLE
CI never start after a push and execute Github Webhook

### ISSUE THREAD

**Issue by maceto** [Shippable/support#2811]
after 06/30/2016 with a new commit, PR, etc... CI stop to work correctly only in one project. Here the link to the project

- https://app.shippable.com/projects/562198e01895ca44741e536f/status/dashboard

I checked Github integration and webhooks and everything is ok. Here the log of the Webhook from Github:

REQUEST:

Request URL: https://562198e01895ca44741e536f:NlUYejufmwqGppIW@api.shippable.com/projects/562198e01895ca44741e536f/newBuild
Request method: POST
Authorization: ********
content-type: application/x-www-form-urlencoded
Expect: 
User-Agent: GitHub-Hookshot/8d6c563
X-GitHub-Delivery: 0b532f00-4ad1-11e6-95d2-7c708189423d
X-GitHub-Event: push

RESPONSE 200

Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept,Content-Type,Authorization,Cookie
Access-Control-Allow-Methods: GET,PUT,POST,DELETE
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 25
Content-Type: application/json; charset=utf-8
Date: Fri, 15 Jul 2016 21:15:57 GMT
X-Powered-By: Express

Any idea ?

Thanks
Martin

**Comment by manishas** [comment]
@maceto for some reason all triggers for your project have been turned off in Settings:

![image](https://cloud.githubusercontent.com/assets/2983749/16889150/338e05cc-4a99-11e6-84a4-b39813ea0b2d.png)

You can go to the Settings tab of your project, click on Runs Config in the sidebar menu, and go to the 'Configure Webhook Events for Triggering Builds' section shown in the picture above. Turn on builds for the webhooks you need.... typically you would turn them on for Pull requests and and Commits.

Let me know if it works for you.

**Comment by manishas** [comment]
Here is the link where you can change this setting  https://app.shippable.com/projects/562198e01895ca44741e536f/settings/runs

**Comment by maceto** [comment]
@manishas ok, changing the config I solved my problem, to start the CI.

But still not working the webhook to Slack when start the CI, where is the config to check it ?

Thanks
Martin

**Comment by abhijitkini** [comment]
@maceto There was [a change in the way we handle legacy Slack integrations](http://docs.shippable.com/ci_troubleshoot/#slack-notifications-do-not-occur-after-the-july-1st-service-maintenance) on our July 1 service update.  

To ensure Slack is working, you'll need to do 2 things:
1. Ensure Slack integration is added in your Subscription. To do so, go to your [Subscription Settings, Integration section, Add Integration](https://app.shippable.com/subscriptions/562198de1895ca44741e52f4/settings/integrations).
2. Ensure this integration is included in the `shippable.yml` for the project you want Slack notifications. You can use the snippet below. Replace _foobar-slack_ with the exact Slack integration name you specify in Step 1 and replace _"#shippable"_ with your Slack channel or recipient that needs to be notified. 
```
integrations:
  notifications:
    - integrationName: foobar-slack
      type: slack
      recipients:
        - "#shippable"
      on_start: always
      on_success: always
```

**Comment by manishas** [comment]
@maceto let us know if you're still running into issues.

**Comment by maceto** [comment]
The problem was solved. Thanks
