### ISSUE TITLE
Unable to login to Shippable

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#2812]
I accidentally clicked on Github login (but I use the Bitbucket login) and now I can't login because it redirects to Github and doesn't have an option to cancel and go back.

Logging out of Github doesn't make a difference. I had to go into browser settings and clear cookies/localstorage to resolve.

**Comment by abhijitkini** [comment]
@pwarnock We'll delete your GitHub account on Shippable. For future reference, you can [link your Bitbucket and GitHub accounts.](http://docs.shippable.com/ht_link_gh_and_bb/)

**Comment by abhijitkini** [comment]
@pwarnock Let us know if you need further help on this issue.
