### ISSUE TITLE
Build Status Badge not updating

### ISSUE THREAD

**Issue by ArdusJax** [Shippable/support#2813]
Build badge stuck on pending. I have looked through the other issues and have tried the following:

- Deleted and re-added the markdown from the settings -> badges section
- Hard refresh of the readme
- Tried using the image tag instead of the Markdown
- Opened up the page on a new computer
- Cleared any cache in the browser.
- Verified that it updates if the url is put directly into a browser. (Chrome)

Badge link:
https://api.shippable.com/projects/577ca6dd3be4f4faa56be7cf/badge?branch=master

Markdown: 
[![Run Status](https://api.shippable.com/projects/577ca6dd3be4f4faa56be7cf/badge?branch=master)](https://app.shippable.com/projects/577ca6dd3be4f4faa56be7cf)

The status never updates on the README.md. I have successful builds in my project.

Thank you.

**Comment by harryi3t** [comment]
@ArdusJax is the badge not updating in just the readme (which you have tried on diff computers) or is this is not even updating in shippable (in the projects settings page).

**Comment by abhijitkini** [comment]
@ArdusJax Looks like the badge is showing up correctly in the Project's Settings page, 'Badges' section and in a browser as well. 

Can you try embedding the Badge link in a new README file and let us know if it works?

**Comment by manishas** [comment]
@ArdusJax I am closing this issue, but please let us know if you still need help and i'll be happy to reopen and take another look.

**Comment by ArdusJax** [comment]
Hi Manisha,

Yes the issue has been resolved. Thank you for updating me, and resolving
the issue.

Thank you!

Chris
