### ISSUE TITLE
Missing Organization in Subscriptions Dropdown

### ISSUE THREAD

**Issue by clubdesign** [Shippable/support#2814]
Hey,

i signed up via Github, allowed all necessary permissions, but i am missing my organizations in the subscriptions dropdown. I already deleted my account, removed all github permissions and reconnected everything, no change.

Can somebody please have a look at this?

Greets

**Comment by vidyar** [comment]
Hi @clubdesign ,
Could you please go to github organization and remove the restrictions from **third party access policy** and then force sync the shippable account? 
Refer http://docs.shippable.com/ci_faq/#why-cant-shippable-see-my-org-on-github for more details

**Comment by clubdesign** [comment]
Hi @vidyar,

thanks for the reply.

Did remove restriction and sync, still no org.
The Application is enabled tough in github: http://d.pr/i/1iT4A/2WhNh419

Greets

**Comment by clubdesign** [comment]
Huh.

for some reason i got it in there now, just a lot of reconnecting, deleting. But now its there.

Thanks
