### ISSUE TITLE
Multiple cell manifests created with auto-increment for only one CI build

### ISSUE THREAD

**Issue by kileyhykawy** [Shippable/support#2817]
I have a pipeline set up with two images. I have auto increment enabled and the same image tag pattern set on both images. When a build completes, I first see one cell manifest get created with one image changing to the new build and then a second cell manifest created with the second image changing. That means two cell manifests are published when there should only be one. If I turn on auto-deploy on an environment, this behaviour triggers two deploys.

I think it should only create one new cell manifest. Or is this the expected behaviour? I think I could live with it if I can make sure I can control the order of which image gets updated first

**Comment by trriplejay** [comment]
This is actually expected behavior right now, but we're in the process of making some pipeline enhancements that should help address this scenario.  I'll mark this as a feature request for now so that we update you when the new functionality becomes available.

**Comment by manishas** [comment]
@kileyhykawy your issue has been addressed with the new pipelines release. 
We are deprecating the old pipelines implementation, and we're requesting all users to migrate to the new Pipelines before Sept 30, 2016. Please let me know if you received the migration email.

**Comment by kileyhykawy** [comment]
Hi @manishas, I received the migration e-mail. Trick is if we have the time to migrate before then - we have a release on that date as well :).

**Comment by manishas** [comment]
We're happy to jump on a hangout and help configure or answer any questions!
