### ISSUE TITLE
Enable projects on subscription menu

### ISSUE THREAD

**Issue by wilsonmar** [Shippable/support#2818]
There doesn't seem to be agreement between
"Enable Project" on the menu and on the left vs. the title 
"Enable Projects".  Also, I would suggest them both be
"Enable projects" because projects in not a proper name?

![shippable-subscriptions-menu-403x218](https://cloud.githubusercontent.com/assets/300046/16933381/0b2dbc1c-4d0a-11e6-8ee5-3ed4c5ac1c5f.jpg)

**Comment by manishas** [comment]
@Riturajcse lets fix this. Please look at all sidebar menus and if there are 2 words, the second word should not have a capital first letter unless its a proper noun.

Also, the header should be Enable project

**Comment by manishas** [comment]
this is fixed, so closing.
