### ISSUE TITLE
Shippable does not permit application to listen to a TCP port?

### ISSUE THREAD

**Issue by kerler** [Shippable/support#2819]
Dear Sir,

The build [https://app.shippable.com/runs/578e022999a1e60d008121b0/1/console](https://app.shippable.com/runs/578e022999a1e60d008121b0/1/console) shows below error. I can not download the detail build artifact file from shippable but I guess the reason is "`My test case code based on SpringBoot want to start an embedded tomcat and listen to a TCP port but shippable does not permit that`".

It this reason correct? If yes, how to permit "`start an embedded tomcat and listen to a TCP port`"?

`    org.springframework.data.gremlin.object.tests.orientdb.core.OrientDB_Core_RestApiIntegrationTest > testRestApiNewEHR FAILED
    java.lang.IllegalStateException
        Caused by: org.springframework.beans.factory.BeanCreationException
            Caused by: org.springframework.beans.BeanInstantiationException
                Caused by: java.lang.RuntimeException
`

**Comment by abhijitkini** [comment]
@kerler we do not store artifacts for your builds, hence they cannot be downloaded. You can read more about it in [our documentation](http://docs.shippable.com/ci_configure/#build-artifacts).

**Comment by kerler** [comment]
Dear Sir,

I am not asking how to store or download build artifacts. I am asking whether Shippable permit application to listen to a TCP port. And, if permit, what is the permitted range of TCP port?

My test case code run well on my PC but not on shippable. One snippet code(actually REST API) of my test case code start an embedded tomcat and listen to a TCP port, the other snippet code connect to that TCP port to call the REST API. So I guess shippable does not permit my test code to listen to a TCP port or has constraint on the range of TCP port.

**Comment by nate-r** [comment]
@kerler Just had some random thoughts after reading your issue. Feel free to ignore me.  :)

The build containers seem to allow apache, mysql, etc, to start up on their respective ports without problems.  Is tomcat trying to bind to all interfaces?  (There might be a security restriction in place that only allows binding to 127.0.0.1, but I'm personally unaware of how that would be accomplished.)  Could tomcat be trying to bind to a port number already in use and failing?

Good luck resolving!

**Comment by chetantarale** [comment]
@kerler We do not restrict applications from listening on any port. All our build containers run in privileged mode and as a root user. You are free to bind your application to any port of your choice.

**Comment by abhijitkini** [comment]
@kerler Hope your question is answered. Let us know if you need further help.
