### ISSUE TITLE
Get accurate coverage across a build matrix

### ISSUE THREAD

**Issue by stsquared99** [Shippable/support#2821]
Build URL: https://app.shippable.com/runs/578e4fe4e196c90c00313465/summary

I am currently playing around with using the build matrix to separate unit, functional, and integration tests. As such, I only want coverage results from one of the jobs, specifically my unit tests. However, this gives me a coverage result of 33% (100% for only 1 of the 3 jobs). Is there any way of remedying this? Basically, I only want to calculate coverage results from a specific job.

Thanks

**Comment by manishas** [comment]
@stsquared99 where do you see the 33%?

**Comment by stsquared99** [comment]
Sorry, it's on the badge.
https://app.shippable.com/projects/576841062a8192902e24592e/settings/badges

I've tested with a cleared cache and on multiple browsers.

**Comment by manishas** [comment]
@stsquared99 this is expected behavior as of now. The status for the entire run is the aggregate for code coverage numbers across jobs, which is 33%. Let me find out if there is any way to get a more granular code coverage number and I will follow up with you.

**Comment by avinci** [comment]
this is by design.
