### ISSUE TITLE
Jobs stuck on provisioning nodes

### ISSUE THREAD

**Issue by erykwarren** [Shippable/support#2823]
### Description of your issue:
Our minions have been stuck at the stage "Provision job node" for about an hour.

https://app.shippable.com/runs/578e74385bec7e0b00a5c93a/1/console

Please advise.

**Comment by erykwarren** [comment]
We tried cancelling the job, but the new ones have the same problem

**Comment by jaecSolutions** [comment]
👍

**Comment by a-murphy** [comment]
This is related to the increased error rates for Amazon Elastic Compute Cloud in North Virginia (http://status.aws.amazon.com/).  Our requests to provision the job nodes are failing.

**Comment by abhijitkini** [comment]
The Amazon EC2 issue is resolved and the nodes are being provisioned normally. We continue to monitor the impact on Shippable http://status.shippable.com/.
