### ISSUE TITLE
Logs too long, cannot download

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2826]
We occasionally have builds like [this one](https://app.shippable.com/runs/578f3fdbde92f00c002baf09/1/console) which says this:

> Logs too long to show here. Please use download button to download the logs.

If we [try this](%28https://app.shippable.com/download/jobConsoles?jobId=578f3fdbeeac370c00a2ce9c%29) we either get an error ...

> {"logType":"error","methodName":"jobConsoles|getSByJobIdDownload|callerId:54f05fcb6e35fd0e00f2032f|jobId:578f3fdbeeac370c00a2ce9c|_getSByJobIdDownload","id":666,"message":"JobConsolesModel.find for jobId: 578f3fdbeeac370c00a2ce9c","link":{"name":"MongoError","message":"getMore runner error: Overflow sort stage buffered data usage of 33554593 bytes exceeds internal limit of 33554432 bytes"}}

... or simply a white page.

I know this issue has been brought up before (#2642) but I still think this needs a solution.

Since the build finishes at some point the log output should be finite too.

**Comment by avinci** [comment]
There are a bunch of changes that are being worked on this https://github.com/Shippable/support/issues/3398. This should cover this issue and hence closing this to reduce duplication
