### ISSUE TITLE
Too hard to add a project

### ISSUE THREAD

**Issue by khamusa** [Shippable/support#2828]
This is not really an issue but a suggestion of improvement of the app UX/UI. I believe it would be of great benefit if you could provide a few welcoming steps for new accounts, specially helping users to add their first projects and start the first build. I had to look for the "subscriptions view" for quite some time before being able to do anything in the platform. 

Or in the following phrase:
"There are no active projects to display. Please enable projects by navigating to the subscriptions view." 

We could just have the 'subscriptions view' clickable :)

**Comment by abhijitkini** [comment]
@khamusa Thanks for the feedback. We strive to make it easier for users to get onboarded to the Shippable platform quickly and get to a green build. This is helpful, will mark it as a feature request and update when we implement it.

**Comment by avinci** [comment]
this has been fixed in the new UI we launched a couple of weeks ago. Please switch the UI to new UI if you have not been already moved. Everyone will be moved in the first week of July.
