### ISSUE TITLE
Build fails with an `invalid yml format` error

### ISSUE THREAD

**Issue by abhijitkini** [Shippable/support#2829]
Issue logged on [Twitter](https://twitter.com/SaizNicolas/status/756125876841046016):

Hi. Shippable started to show me a "invalid yml format" alert this week. And I haven't changed anything on it. Do you know why?

Link to the build failure: https://app.shippable.com/runs/578e78239f4a600c009c6112/1/console

**Comment by manishas** [comment]
This is already fixed. The user has `script` section repeated in his yml.
