### ISSUE TITLE
Build status icons are differentiated only by color

### ISSUE THREAD

**Issue by tgross** [Shippable/support#2831]
The various build status icons (see image below) are differentiated only by color, which makes them hard to use for colorblind users. The icons have mouse-over text, but you can't see this without mousing over of course. If the icon glyphs were different for different states they would be easier to use (ex. a check mark, an "X", etc.)

<img width="221" alt="screen shot 2016-07-22 at 3 26 26 pm" src="https://cloud.githubusercontent.com/assets/1409219/17068726/af03f202-5020-11e6-9faa-c263604a1831.png">

**Comment by abhijitkini** [comment]
@tgross Thanks for this feedback. I've marked this as a feature request and will update as it is implemented.

**Comment by avinci** [comment]
this has been fixed in the new UI we launched a couple of weeks ago. Please switch the UI to new UI if you have not been already moved. Everyone will be moved in the first week of July.
