### ISSUE TITLE
Notifications appearing with on_success: change

### ISSUE THREAD

**Issue by philipn** [Shippable/support#2832]
We just started seeing notifications appearing in slack and via email, and we've changed nothing on shippable.com or in our `shippable.yml` configuration file.  Our `shippable.yml` specifies `on_success: change`, and we're seeing notifications even when the build has passed -> passed -> passed, etc.

**Comment by chetantarale** [comment]
@philipn we are unable to reproduce this at our end. Can you share the build link and your yml?

**Comment by philipn** [comment]
Here's an example build link:

https://app.shippable.com/runs/5795860c0bf39a0c00b1bf83

and here's our shippable YAML (with some non-public bits removed):

```
# Note that Shippable minions preserve state from build to build, so
# this script is not guaranteed to behave the same from run to run
# (i.e. if things are left in an inconsistent state).
build:
  pre_ci_boot:
    # Emulate docker machine setup
    options: "-v /srv/data:/srv/data"
  ci:
    < contents >
  on_success:
    # The value of the --allowed option should match the branches listed
    # in the "hub" section below.
    < an image push to ECR line >
integrations:
  notifications:
    # The integrationName is the name we specified in the "Account
    # Integrations" section of the Shippable website (when logged in to
    # our account).
    - integrationName: Slack
      type: slack
      recipients:
        - "#tech"
      # The branches defaults to notifying for all branches.
      #
      # branches:
      #   only:
      #     - master
      #   except:
      #     - scratch
      #
      # The defaults are: on_start ("never"), on_success ("change"),
      # on_failure ("always"), and on_pull_request ("always").
      # We keep on_start on "never" and on_success on "change" to cut down
      # on Slack noise.
      on_start: never
      on_success: change
      on_failure: always
      on_pull_request: always
  hub:
    - integrationName: ecr-integration
      type: ecr
      region: us-west-2
      branches:
        only:
          - master
          # This branch is meant for testing purposes.  To test a commit
          # (e.g. with debug code that you don't want in master), you can
          # force push to this branch (hence the name throwaway).
          - throwaway
```

**Comment by chetantarale** [comment]
@philipn Sadly we are still unable to reproduce this. We looked into your build history.

I have a couple of questions which will be helpful in resolving your issue. Please shed some light here.
So as of today and according to your yml config you should be receiving  4 notifications.
How many have you received?
Does this happen often. Or are you facing this recently?
Also if possible can you share a screenshot of your slack channel for the notifications you received today.

**Comment by philipn** [comment]
It looks like this stopped happening this morning, so I'm closing this. Thanks!
