### ISSUE TITLE
AWS ECS CPU Units=0

### ISSUE THREAD

**Issue by jplimpens** [Shippable/support#2833]
When deploying to AWS ECS from pipeline it creates a task definition. However, the CPU Units are set to 0 which fails to start the container (on AWS Task revision is errors that the value of CPU Unit must be > 1).

Setting the CPU value in the Cell configuration doesn't work.
Please advice how to set the CPU Unit on AWS ECS.

Further, I received your emails about tips & tricks. However, in your email about "Deploy your First App with Shippable" it contains a link to an empty page. Link underneath.
http://docs.shippable.com/nt_container_services/?utm_campaign=Shippable+New+Customer+Nurture&utm_source=hs_automation&utm_medium=email&utm_content=26367550&_hsenc=p2ANqtz-_ptfHTMsp_fgCvua9gKDSAwO-ORL7zg13nFcvDyII-6ysku5rP069inSso6TfIXam-mgnTgM-oTgrFEcdSxG94tMgj_Q&_hsmi=26367550

**Comment by trriplejay** [comment]
Currently we do not expose this setting.  However, according to ECS documentation, a value of 0 is valid, but will behave differently depending on your ECS agent version.  From the docs:

![image](https://cloud.githubusercontent.com/assets/6869398/17118785/28ca3cba-5277-11e6-956b-ff2136ab3636.png)

[link to docs](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#advanced_container_definition_params)

We have plans to expose this and other settings in the near future, but until then.. are you sure it's the CPU value that is causing your container to not start? Can you provide a link to your pipeline for further investigation? Does your service have any messages in the 'events' section?

**Comment by jplimpens** [comment]
I've got it running. Not sure what went wrong. I deleted the previous pipeline (where I initially filled in CPU Units - after which I deleted the value). Once I created a new pipeline it just worked as expected. 

Issue can be closed as far as I'm concerned.

I read some feature request for awslogs. I + that request. Any idea when that feature will be available?

**Comment by trriplejay** [comment]
In the next 2-3 weeks we'll be coming out with a large pipelines enhancement that will allow you to specify both CPU and log settings, among other things.  I'll mark this as a feature request, and we'll notify you when it becomes available.
