### ISSUE TITLE
SequelizeDatabaseError: column runs.queuedDate does not exist

### ISSUE THREAD

**Issue by HelainSchoonjans** [Shippable/support#2834]
Hello dear Shippable team,

One of my scripts that has been running over the last months has recently started having failures; it seems that the error originates from the shippable SQL database, which throws a SequelizeDatabaseError.  This is the output of my script, with the response from the Shippable API:

> python scripts/shipp/cancel_if_needed.py 0s  
Module ng-server-plugin-gateway-data on branch rc
​
Loading information about existing projects.
Failed to get build for identifier '55cdxxxxxxxxxxxxxxxxx', status 'running' and branch 'rc'.
Status code: 500
Response message: {  
   "logType":"error",
   "methodName":"runs|getS|callerId:55cdxxxxxxxxxxxxx|_getSRuns",
   "id":666,
   "message":"runs.findAll",
   "link":{  
      "name":"SequelizeDatabaseError",
      "message":"column runs.queuedDate does not exist",
      "parent":{  
         "name":"error",
         "length":107,
         "severity":"ERROR",
         "code":"42703",
         "position":"810",
         "file":"parse_relation.c",
         "line":"3090",
         "routine":"errorMissingColumn",
         "sql":"SELECT \"id\", \"runNumber\", \"projectId\", \"projectName\", \"subscriptionId\", \"subscriptionOrgName\", \"isPrivate\", \"lastCommitShortDescription\", \"commitSha\", \"triggeredBy\", \"committer\", \"statusCode\", \"startedAt\", \"createdAt\", \"endedAt\", \"branchName\", \"isPullRequest\", \"pullRequestNumber\", \"projectHtmlUrl\", \"providerName\", \"commitUrl\", \"runLengthInMS\", \"totalTests\", \"testsFailed\", \"testsPassed\", \"testsSkipped\", \"testsErrors\", \"postCallerId\", \"providerId\", \"providerUrl\", \"sequenceCoveragePercent\", \"branchCoveragePercent\", \"language\", \"type\", \"isGitTag\", \"gitTagName\", \"gitTagMessage\", \"isRelease\", \"isPrerelease\", \"releasedAt\", \"releaseName\", \"releaseBody\" FROM \"runs\" AS \"runs\" WHERE \"runs\".\"projectId\" IN ('55cdxxxxxxxxxxxxxxxxxx') AND \"runs\".\"branchName\" IN ('rc') AND \"runs\".\"statusCode\" IN (NULL) ORDER BY \"runs\".\"queuedDate\" DESC LIMIT '1';"
      },
      "original":{  
         "name":"error",
         "length":107,
         "severity":"ERROR",
         "code":"42703",
         "position":"810",
         "file":"parse_relation.c",
         "line":"3090",
         "routine":"errorMissingColumn",
         "sql":"SELECT \"id\", \"runNumber\", \"projectId\", \"projectName\", \"subscriptionId\", \"subscriptionOrgName\", \"isPrivate\", \"lastCommitShortDescription\", \"commitSha\", \"triggeredBy\", \"committer\", \"statusCode\", \"startedAt\", \"createdAt\", \"endedAt\", \"branchName\", \"isPullRequest\", \"pullRequestNumber\", \"projectHtmlUrl\", \"providerName\", \"commitUrl\", \"runLengthInMS\", \"totalTests\", \"testsFailed\", \"testsPassed\", \"testsSkipped\", \"testsErrors\", \"postCallerId\", \"providerId\", \"providerUrl\", \"sequenceCoveragePercent\", \"branchCoveragePercent\", \"language\", \"type\", \"isGitTag\", \"gitTagName\", \"gitTagMessage\", \"isRelease\", \"isPrerelease\", \"releasedAt\", \"releaseName\", \"releaseBody\" FROM \"runs\" AS \"runs\" WHERE \"runs\".\"projectId\" IN ('55cdxxxxxxxxxxxxxxxxxxxx') AND \"runs\".\"branchName\" IN ('rc') AND \"runs\".\"statusCode\" IN (NULL) ORDER BY \"runs\".\"queuedDate\" DESC LIMIT '1';"
      },
      "sql":"SELECT \"id\", \"runNumber\", \"projectId\", \"projectName\", \"subscriptionId\", \"subscriptionOrgName\", \"isPrivate\", \"lastCommitShortDescription\", \"commitSha\", \"triggeredBy\", \"committer\", \"statusCode\", \"startedAt\", \"createdAt\", \"endedAt\", \"branchName\", \"isPullRequest\", \"pullRequestNumber\", \"projectHtmlUrl\", \"providerName\", \"commitUrl\", \"runLengthInMS\", \"totalTests\", \"testsFailed\", \"testsPassed\", \"testsSkipped\", \"testsErrors\", \"postCallerId\", \"providerId\", \"providerUrl\", \"sequenceCoveragePercent\", \"branchCoveragePercent\", \"language\", \"type\", \"isGitTag\", \"gitTagName\", \"gitTagMessage\", \"isRelease\", \"isPrerelease\", \"releasedAt\", \"releaseName\", \"releaseBody\" FROM \"runs\" AS \"runs\" WHERE \"runs\".\"projectId\" IN ('55cdxxxxxxxxxxxxxxxxx') AND \"runs\".\"branchName\" IN ('rc') AND \"runs\".\"statusCode\" IN (NULL) ORDER BY \"runs\".\"queuedDate\" DESC LIMIT '1';"
   }
}
Traceback (most recent call last):
  File "scripts/shipp/cancel_if_needed.py", line 17, in <module>
    canceller.clean_queue(module_name, build_id)
  File "/root/src/bitbucket.org/B2Boost/ng-server-plugin-gateway-data/scripts/shipp/build/Canceller.py", line 14, in clean_queue
    self.load_module_data(module_name)
  File "/root/src/bitbucket.org/B2Boost/ng-server-plugin-gateway-data/scripts/shipp/build/Algorithm.py", line 55, in load_module_data
    self.load_latest_build(module, id, "running", reload)
  File "/root/src/bitbucket.org/B2Boost/ng-server-plugin-gateway-data/scripts/shipp/build/Algorithm.py", line 61, in load_latest_build
    self.graph.node[module_name]["latest_"+status+"_build"] = self.build_from_response(response)
  File "/root/src/bitbucket.org/B2Boost/ng-server-plugin-gateway-data/scripts/shipp/build/Algorithm.py", line 48, in build_from_response
    if response[0]:
KeyError: 0

**Comment by rageshkrishna** [comment]
Hi @HelainSchoonjans. Thanks for letting us know about this issue. Over the weekend, we moved `runs` and `jobs` from mongodb to postgres. The field `queuedDate` has never existed in the `runs` schema. MongoDb appears to have been quite forgiving about this, but postgres most definitely is not.

Removing the `queuedDate` field from your API call should get you around this. Perhaps you're looking for `startedAt` instead?

**Comment by HelainSchoonjans** [comment]
Thanks @rageshkrishna ; using 'createdAt' instead of queuedDate solved my issue.
