### ISSUE TITLE
Get minions/active_minions count programmatically

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2835]
Hello,

Some of our scripts were calling:
```
GET /subscriptions/$subscription_id/activeMinions
```
to get the active minions count and decide to schedule builds or not. This call started to return 400 around 2016-07-20. Is there another similar endpoint we can use to retrieve this information? We can probably deduce it from the active build list but I am curious.

Thank you.

**Comment by a-murphy** [comment]
`GET /subscriptions/:subscriptionId/activeMinions` no longer exists.  Could you try `GET /subscriptions/:subscriptionId/state` instead?  The response object from that route has a `activeJobs` property that will be the number of builds currently processing.

**Comment by manishas** [comment]
@pmezard apologies for retiring a route that you were using. 

The main issue is that we haven't yet versioned our APIs. We will address this in our upcoming release in August and you will not see these kind of problems any more.

**Comment by pmezard** [comment]
Thank you for your response. To be fair, the original call was not documented in:

  http://docs.shippable.com/api/

so as far as I am concerned there were no guarantees about it. That said I am reluctant to replace it with another undocumented call, I will retrieve active builds and assume there are as many minions. This is a minor issue anyway.
