### ISSUE TITLE
Where do I set Machine Image to Unstable (Docker 1.11)?

### ISSUE THREAD

**Issue by tmcgannon** [Shippable/support#2836]
In hopes of reducing the number of Build Timeouts on my dedicated host, I want to try the Unstable Machine Image which is said to include Docker 1.11 (SEE: http://docs.shippable.com/ci_subscriptions/#selecting-the-machine-images).  On that page is says "Go to the 'Settings' tab of your 'Subscription'. Click on the 'Options' tab and select from the dropdown under the 'Machine Images' section."  However, on my Subscriptions -> Options tab there is no Machine Images tab nor am I able to find any reference to that in the documentation, support issues, or by googling.  Where do I set the Machine Image to Unstable?

**Comment by a-murphy** [comment]
The machine image is selected on the "Settings" tab of the "Subscription" page.  But, it can only be selected when using Shippable nodes.  Since you're using a dedicated node, it won't show the machine image choices.

Machine images are the images used for the nodes that we will start to run builds.  With a dedicated node, the node is already running so the machine image would never be used.

**Comment by tmcgannon** [comment]
So, if I run my own dedicated node, I am stuck with using docker 1.9.1?

**Comment by a-murphy** [comment]
I'm afraid so.  The initialization script currently installs 1.9, and updating the version of Docker after adding the node would be unlikely to work because there's a Docker container running to listen for new builds.

**Comment by tmcgannon** [comment]
Bummer.  Currently, if I install my own Shippable node (on an Azure VM where my unit test database also  resides), the docker mexec process seems to always hang with the following docker log entry:

```
INFO[1217] POST /v1.21/containers/shippable-mexec-57854427cc2aa60c00476189/restart?t=0
INFO[1217] Container 316be27f457c36091553c9fb3c0e4140246251ea9065f57d106b2ecd06ec6716 failed to exit within 0 seconds of SIGTERM - using the force
```

It then just pauses.  Sometimes it times out and starts up the cexec docker process but most of the time will it will not and eventually times out after 60 minutes.  I can restart the mexec process and then it will run my Shippable build but that is a pain in the neck.

**Comment by tmcgannon** [comment]
Docker 1.9.1 is now almost 9m months old.  When do you plan to upgrade to a current version?

**Comment by satoko-a** [comment]
Is there any updates?
I'd like to use Docker 1.11(or later).

**Comment by manishas** [comment]
@satoko-a http://docs.shippable.com/ci/advancedOptions/machineImages/

**Comment by satoko-a** [comment]
@manishas 
Thanks.
However, I'm afratid this option is only available for shippable infrastructures, not for BYON.
[BYON (Bring Your Own Nodes) while running your Continuous Integration projects - Shippable Docs](http://docs.shippable.com/ci/advancedOptions/byon/)

Can I use Docker 1.11 with BYON?

**Comment by manishas** [comment]
Not as of now, but we plan to enable this soon. I will keep you updated.

**Comment by manishas** [comment]
BYON nodes now run docker 1.11.1. Please let us know if you're still having issues with docker version.
