### ISSUE TITLE
API "Get latest run for a branch" documentation is incorrect (or call is broken)

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#2837]
Hello,

"Get latest run for a branch" or "/projects/:projectId/branchRunStatus" used to return the "projectName" field in its response, as shown in:

http://docs.shippable.com/api/#get-latest-run-for-a-branch

This seems to be no longer the case. Maybe fix the documentation (or better the call, as having a unified output schema makes things much easier). I have not checked all the fields.

Thanks.

**Comment by avinci** [comment]
We are implementing a feature that will solve this problem in a fully REST compatible way. I will update the issue after it goes live this week.

**Comment by ric03uec** [comment]
@pmezard sorry for the late reply, the docs are now updated here: http://docs.shippable.com/reference/api-overview/#!/Projects/get_projects_projectId_branchRunStatus
marking this as resolved.

**Comment by deepikasl** [comment]
Closing as the link is fixed. Please re-open if you have any more concerns.
