### ISSUE TITLE
Build Failure: getAccountProfiles failed

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2839]
Why is this build failing?

https://app.shippable.com/runs/5798dd32e763b40c007e8ca7/1/console

The error message on the console is:
```
runs|post|callerId:5646af051895ca4474237ee2|projectId:573f79d02a8192902e20e34e|_createNewAccounts getAccountProfiles failed for account:github/dav1xruns|post|callerId:5646af051895ca4474237ee2|projectId:573f79d02a8192902e20e34e|_createNewAccounts getAccountProfiles failed for account:github/dav1x
```

**Comment by mattclay** [comment]
We're seeing this error on more builds. Here's another one:

https://app.shippable.com/runs/579a6a4adb05080c00d03fff/1/console

```
runs|post|callerId:5646af051895ca4474237ee2|projectId:573f79d02a8192902e20e34f|_createNewAccounts getAccountProfiles failed for account:github/norisdietzel
```

**Comment by ric03uec** [comment]
@mattclay we're looking into this now. will update the issue as soon as we have more information

**Comment by manishas** [comment]
Raising priority.

**Comment by ric03uec** [comment]
@mattclay we're testing the fix for this internally right now and will be pushed to prod in a few hours.

**Comment by ric03uec** [comment]
@mattclay im closing this issue as the fix has now been deployed. please feel free to re-open it if you see the problem again.
