### ISSUE TITLE
Project name not clickable in runs anymore

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2841]
The project name in the app header is not clickable anymore within run views:

![image](https://cloud.githubusercontent.com/assets/5037116/17245103/4d12e714-5585-11e6-9ff3-eb17f5b737c4.png)

The subscription name is still clickable though.

**Comment by manishas** [comment]
@mbrodala the project name is clickable if you're on the run page....it is not clickable when you're on the project page since you're already on that page. If that's not the case for you, please let me know what browser+version you're using.

**Comment by mbrodala** [comment]
@manishas This was working until recently, that's why I opened this ticket. ;-)

I am using the latest Chrome browser.

**Comment by mbrodala** [comment]
Seems like it's working again as expected.
