### ISSUE TITLE
Override Branch: Only: option in shippable.yml

### ISSUE THREAD

**Issue by nmarshall-cst** [Shippable/support#2843]
Hello - we use the feature that builds specific branches by using the branches sections in our yml. There are a select few branches that we would like the CI to build automatically. If we would like to skip the automated build process we commit with the [skip ci] text in our commit message. My question is that we have a branch that is not in the list of specific branches, but we need a shippable build to run on said branch. I tried to manually run a build within the Shippable interface by selecting 'Show All Branches', but I receive an error "Run skipped because the YML file does not allow this branch." I know that we can commit the branch name in the list of branches in the yml, but this is a one off scenario and I would like to keep our shippable.yml clean from this branch. Is there a flag or a commit message that the CI will recognize to override the branch: only: section of the yml? Thanks!

**Comment by manishas** [comment]
@nmarshall-cst there is a way to achieve what you want, though not with manual build as it is designed today.

You can do a commit in the one-off branch including the branch name in the `branches:` tag... this will trigger your automated build. If you do one more commit in the one-off branch and exclude the branch name from the tag, it will just skip the build and your yml will be clean again.

**Comment by nmarshall-cst** [comment]
Thank you @manishas!
