### ISSUE TITLE
Add files to build download list

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2845]
For every job I am able to download the log output.

It would be great if one could add arbitrary files from the build to this download menu. Imagine for example an acceptance test failing; if one could simply download the output and screenshot through this menu, debugging could be simplified.

**Comment by mbrodala** [comment]
As a workaround for now I have implemented a archiving and upload to the "Downloads" section of the building repository using the [Bitbucket API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/downloads#post). This way we can inspect files/directories generated during build.

**Comment by avinci** [comment]
We are adding artifacts as a way to pull files from the builds. This should solve the problem,

Closing this issue as there is another duplicate request around the same https://github.com/Shippable/support/issues/2444

**Comment by mbrodala** [comment]
Thanks, I'll watch that ticket.
