### ISSUE TITLE
Shippable.yml for multicontainer docker image on AWS EB with images from dockerhub

### ISSUE THREAD

**Issue by anywhereinfo** [Shippable/support#2847]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

Hi, my docker images are stored in dockerhub and i want shippable to do the following:

1. Build with gradle wrapper command such as `./gradlew build`

2. On successful build, my gradle uploads the docker image to docker hub. I can do it from my local workstation, but what do i modify or provide to support this integration?

3. On successful build, promote the multiple containers hosted on docker-hub to aws ebs as described in my docker-compose.yml

**Comment by trriplejay** [comment]
1. yes, this should work
2. You can do this by adding an 'account integration' for Docker on the account settings page [as shown here](http://docs.shippable.com/int_docker_registries/).  Once you've done that, you can follow [these instructions](http://docs.shippable.com/ci_configure/#adding-a-hub-integration-to-a-project) for using that integration in your build to push your images.
3. If you create a Dockerrun.aws.json file [as described here](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_v2config.html#create_deploy_docker_v2config_dockerrun) for your docker images, you can deploy to beanstalk by creating a 'deploy' type integration on shippable, and adding it to your yml (similar to adding your docker hub integration). [Check this out](http://docs.shippable.com/int_paas_iaas_providers/) for our documentation on setting up beanstalk.

**Comment by manishas** [comment]
closing since the question was answered

**Comment by yanikkoval** [comment]
@anywhereinfo do you succeed with this integration? 
Want to do very similar one.
