### ISSUE TITLE
Chrome support

### ISSUE THREAD

**Issue by vaivars** [Shippable/support#285]
Hello,

Currently it seems that shippable only supports firefox (atleast based on the documentation). 

Would it be possible to add support for more browsers like chrome?

**Comment by 9dev** [comment]
@cbliard Hey, thanks for your solution. Have you changed anything else beside this block of code?

I used it exactly as you posted, but I keep getting the following error:

> selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service /usr/bin/google-chrome
