### ISSUE TITLE
Add PhantomJS service

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2850]
In addition to Selenium it would be useful if Shippable did provide [PhantomJS](http://phantomjs.org/). Thus one could simply add this to his `shippable.yml`:

``` yaml
services:
  - phantomjs
```

After this, the PhantomJS service should be running and listening to connections on port 4444.

Notice that this is a more general solution/workaround for #2846.

**Comment by avinci** [comment]
@rageshkrishna can we add this to all?

**Comment by mbrodala** [comment]
[PhantomJS was discontinued](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE) in the meantime and didn't work well anyways, thus closing this.
