### ISSUE TITLE
Pipeline not auto deploying 

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#2851]
i constructed a pipeline
https://app.shippable.com/subscriptions/578f3c82eeac370c00a23846/pipelines

It is expected to auto deploy, but i do not see any errors or any activity on pipeline that is triggered by a sucesfull CI run.

Manual deployment works ok, i see the tasks/services created on cluster in AWS, and proper images land on ECS. The only issue seems to be that pipeline is not automatically deploying and no new cell versions are created after a CI run.

please advise how to proceed.

**Comment by a-murphy** [comment]
It appears as though you don't have any valid auto-increment tag patterns.  These tag patterns are regular expressions that will be used to determine which new tags should create new versions of the cell manifest.  The tag pattern `.*` should match any tag (any character zero or more times).

**Comment by KarolAdamiec** [comment]
Ha,

somehow i was convinced that * is a correct pattern, confusing regex with globs i suppose.

So that worked like a charm. Manifests upgrade and auto deploy.

The only issue i have now is that deploy is unsuccessful because port is taken on ECS.
I imagined that auto deploy will underlay old cell and deploy new one. How is that supposed to work?

Or is the fact that previous manifest deploy triggered manually preventing automated deployment?

**Comment by KarolAdamiec** [comment]
ECS needs two instances to deploy smoothly. Closing.
