### ISSUE TITLE
Build hangs / aborts in the middle of tests

### ISSUE THREAD

**Issue by phw** [Shippable/support#2854]
We are currently evaluating Shippable, but our builds fail to complete. The tests start running, but stop at some point. The test console output ends just randomly.

Example for a failing build: https://app.shippable.com/runs/57a0eed8ff19fb0c0016a0df/summary

It is not clear to me why this is failing. Are we running into the build timeout or do we reach any other resource limit? Would be nice if the UI would provide a bit more insight in those cases.

**Comment by a-murphy** [comment]
Yes, your build timed out.  The colored circles behind the commit or pull request icons show the status, with the colors documented [here](http://docs.shippable.com/ci_builds/#build-status).  If you mouse over the icon, a tooltip will also display the status.

**Comment by phw** [comment]
Thanks for the confirmation and the hint with the icon labels/colors.
