### ISSUE TITLE
Slack notification with test results

### ISSUE THREAD

**Issue by timtribers** [Shippable/support#2856]
Hi,

Slack notification is very cool, and working fine for me.
However, the messages I receive in Slack always say "No test results were reported. " even though I am creating test results and these are displaying in the Shippable console when I click through from the build link in the Slack message and go to the tests tab.  Do I need to specify anything in particular in my yml to get this working?

Thanks

**Comment by kanthchandra** [comment]
Hi @timtribers can you please post the link to the build which did not have test results in the notification? Also can you post a screenshot of the slack message that you received?

**Comment by timtribers** [comment]
Sure thing,

Here's the link: https://app.shippable.com/runs/57a36dde5dff510c001dae6c

And here's the screenshot:

![slack2](https://cloud.githubusercontent.com/assets/7858892/17434258/53d05b32-5b01-11e6-8180-9c8a9fd4248f.png)

**Comment by kanthchandra** [comment]
Ah, I see why this is happening. I think it's bug at our end. We are not handling a case where all the test cases failed correctly while sending slack notification. We will let you know when the fix is available.

**Comment by timtribers** [comment]
Thanks @kanthchandra 

I am constructing the testresults.xml file myself (in code), so do let me know if there's something I should correct in my formatting or content of that file.  I don't want you to have to do a bug fix, if no-one else will ever generate a test results file like mine!!

**Comment by kanthchandra** [comment]
As long as our report parser is parsing your testresults.xml correctly (the values are right), I dont think it would matter whether you are creating it by yourself or you are using a parser.

**Comment by timtribers** [comment]
It was your comment "We are not handling a case where all the test cases **failed correctly**" that made me wonder if its something I should be correcting in the testresults file.

At the moment I have generated:
`<testsuite id="0" name="Test 1" tests="0" disabled="0" errors="0" failures="65" skipped="0" time="0">`

which I am thinking ought really (at the least) to be:
`<testsuite id="0" name="Test 1" tests="65" disabled="0" errors="0" failures="65" skipped="0" time="0">`

**Comment by chebum** [comment]
Our Slack integration stopped working completely. The Slack's webhook itself is working - I can confirm this by sending a POST request to it.  I tried re-adding a webhook with no luck. Looks like Shippable doesn't send POST request to the webhook. Is there something we can do to solve the problem?

**Comment by kanthchandra** [comment]
Hi @timtribers this has been deployed to prod and fixed. Can you please confirm if it works for you?

**Comment by kanthchandra** [comment]
@chebum can you please open a separate issue for your problem by giving us the id of the build for which you dint receive the notification? We will track that separately.

**Comment by timtribers** [comment]
Thanks @kanthchandra , I will give it a go.

**Comment by timtribers** [comment]
Woohoo, looking good!

![slack3](https://cloud.githubusercontent.com/assets/7858892/17532271/be85e680-5e77-11e6-8b8f-30f160a8275e.png)

Fantastic job, and great speed on the turnaround of this - really appreciate it.
Shippable is awesome.
