### ISSUE TITLE
first commit on a branch doesn't cause a build

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#2862]

**Comment by a-murphy** [comment]
Could you include some more information about this build that wasn't created?  Builds are usually created for new branches, so it would be nice to have more information about what we should be looking for.  Knowing which source provider it is and if the commit was pushed with the new branch or updated an existing branch would help narrow down the search.  Or if there was anything unusual about how this commit was pushed.

**Comment by manishas** [comment]
@BryanCrotaz can you go to the 'History' page for your project and make sure that the new branch did not get built? Did the branch have a shippable.yml?

**Comment by manishas** [comment]
closing this issue. @BryanCrotaz let us know if you need any help with this.
