### ISSUE TITLE
Navigation between builds should be improved

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#2864]
From a build run page (eg https://app.shippable.com/runs/57a8b5db6a05380c00b93c11/1/console) I should be able to navigate directly to:
- Previous build on this branch (ideally make below summary clickable)
- Next build on this branch

Branch name should be clickable to take me to a list of all builds on that branch

Add link to the project which shows me all branches

It would be useful to see the summary of the last (5?) builds: overall status, pass|fail|etc, number of failed tests, headline coverage number to be able to see if this build is an anomaly, if we're getting better or worse etc

**Comment by manishas** [comment]
Great suggestions. We will definitely keep this in mind as we tackle our next set of UI improvements.

**Comment by BryanCrotaz** [comment]
Before they delete it at the end of the year, get yourself a $10 account on
Atlassian cloud Bamboo. Their UI navigation and build info is second to
none. Same data you've got but much better presented.

They're discontinuing the service so we're moving to shippable.

Bryan Crotaz
Silver Curve

On 9 Aug 2016, at 20:12, Manisha <notifications@github.com> wrote:

Great suggestions. We will definitely keep this in mind as we tackle our
next set of UI improvements.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Shippable/support/issues/2864#issuecomment-238659448>,
or mute the thread

**Comment by avinci** [comment]
this has been fixed in the new UI we launched a couple of weeks ago. Please switch the UI to new UI if you have not been already moved. Everyone will be moved in the first week of July.
