### ISSUE TITLE
Database error when (automatically|manually) building

### ISSUE THREAD

**Issue by abatiz** [Shippable/support#2865]
### Description of your issue:

Shippable “build” is not triggered automatically from GitHub's commit (nor does present the updated git log), and when “build” is manually triggered from Shippable, an error appears:

```
(Id: 666) Database error
error: builds|chkPermForId|callerId:579b424da8f22a0c00a414fd|buildId:undefined|_getBuildById
{"message":"Cast to ObjectId failed for value \"undefined\" at path \"_id\"","name":"CastError","kind":"ObjectId","value":"undefined","path":"_id"}
```

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure: the previous error appears on this url: https://app.shippable.com/builds/undefined
- It is a private repository that on 3/Aug/2016 was building correctly.
- Scripts called from the yml (optional): my yml is

```
language: node_js

node_js:
  - 6
  - 5
```

I tried to delete the repo from Shippable and enable it again: now it shows the latest commit, but builds are not run (the same error appears).

I would be grateful if somebody could help me with this problem. I'm new to Shippable and my PR on GitHub need these tests to pass before merging…

Thanks!

**Comment by a-murphy** [comment]
Could it be that you have commit builds disabled on the project settings tab?  The manual builds triggered by clicking the "build" buttons are commit builds and so won't be created with commit builds disabled.  This would also explain why builds for commits from GitHub are not created.

**Comment by wegenern** [comment]
I'm getting the same error as well.

(Id: 666) Database error
error: builds|chkPermForId|callerId:57410f27dd010b0c007d6793|buildId:undefined|_getBuildById
{"message":"Cast to ObjectId failed for value \"undefined\" at path \"_id\"","name":"CastError","kind":"ObjectId","value":"undefined","path":"_id"}

**Comment by manishas** [comment]
@abatiz Are you referring to this project - https://app.shippable.com/projects/579b43a3a8f22a0c00a44a1a/status/

Please go to the Settings tab, choose Runs config from the left sidebar menu, and in the `Configure Webhook Events for Triggering Builds` section, click on 'Enable' for commit builds.

**Comment by manishas** [comment]
@abatiz @wegenern let us know if you still need help with this. closing.

**Comment by Miguel-Herrero** [comment]
@manishas @wegenern Thank you! It does works again! 👏 

However, just for curiosity. How is that it suddenly stopped running tests for my PR? (It worked before without the “commit” builds enabled).
