### ISSUE TITLE
URGENT: I can't trigger new builds!

### ISSUE THREAD

**Issue by deanmraz** [Shippable/support#2866]
I typically use the API with a curl request like this one: 

curl -H "Content-Type: application/json" -H "Authorization: apiToken $SHIPPABLE_API_KEY" -X POST -I "https://api.shippable.com/projects/575a15582a8192902e232717/newBuild?branch=artifact"

and it usually responds with the build ID but i'm getting this: 
{}

and these headers: 
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Accept,Content-Type,Authorization,Cookie
Access-Control-Allow-Methods: GET,PUT,POST,DELETE
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Date: Tue, 09 Aug 2016 21:32:47 GMT
ETag: W/"2-mZFLkyvTelC5g8XnyQrpOw"
Vary: X-HTTP-Method-Override
X-Powered-By: Express
Content-Length: 2
Connection: keep-alive

Also, tried to trigger Rebuild button here: 
https://app.shippable.com/runs/57a9130aa353270c008c7c23/1/console

and it takes me here: 
https://app.shippable.com/runs/undefined/summary

Please help!

**Comment by trriplejay** [comment]
we're investigating. we'll keep you updated.

**Comment by trriplejay** [comment]
actually, if you need a workaround: This appears to be related to having commit builds disabled.  You could try enabling them, click 'build', then disable again.  Otherwise we'll try to get a fix out and we'll let you know when its available.

**Comment by trriplejay** [comment]
Hello, this fix should be deployed now. Please let us know if you are still having trouble.

**Comment by deanmraz** [comment]
@trriplejay thanks I'll review

**Comment by manishas** [comment]
closing this issue. please let us know if you run into any problems.

**Comment by deanmraz** [comment]
Confirmed all good, thank you!
