### ISSUE TITLE
Can't create a database

### ISSUE THREAD

**Issue by magicalbanana** [Shippable/support#2868]
### Description of your issue:

I'm using this `go` package `pgmgr` to create/migrate the database for the CI build but I am getting this error (works locally).

`createdb: could not connect to database template1: FATAL:  role "root" does not exist`

How do I configure the database to have the credentials is used the database migrations are executed?
- Link to the build failure

https://app.shippable.com/runs/57aa7a3f611c161000403aaf/1/console
- Scripts called from the yml (optional)

**Comment by avinci** [comment]
What database are you using? Are you still having this issue? For e.g. if you use postgres, here is what you need to do http://docs.shippable.com/ci/services/postgreSQL/

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image. Please let us know if you still are facing issues.
