### ISSUE TITLE
[Question] How to pass spring active profile to script? 

### ISSUE THREAD

**Issue by jhseong** [Shippable/support#2871]
I am using gradle and spring boot.
I want to pass **SPRING_PROFILES_ACTIVE=development, staging, production** each to the script section.
I want to pass the profile dynamically. 
What should I do?

ex) 
SPRING_PROFILES_ACTIVE=development ./gradlew clean check
SPRING_PROFILES_ACTIVE=staging  ./gradlew clean check
SPRING_PROFILES_ACTIVE=production  ./gradlew clean check
 
- shippable.yml
```
language: java

jdk:
- oraclejdk8

install:
- ./gradlew assemble

script:
- ./gradlew check
```

**Comment by a-murphy** [comment]
Correct me if I'm wrong, but it sounds like you're trying to create a matrix of builds with different values for the environment variable `SPRING_PROFILES_ACTIVE`.  Adding the following `env` section to your `shippable.yml` file will result in a matrix of three builds, one with each value for `SPRING_PROFILES_ACTIVE`:
```YML
env:
  - SPRING_PROFILES_ACTIVE=development
  - SPRING_PROFILES_ACTIVE=staging
  - SPRING_PROFILES_ACTIVE=production
```

More information about using environment variables with Shippable is available [here](http://docs.shippable.com/ci_configure/#custom-variables).

**Comment by jhseong** [comment]
I tried it before.
You understood it correctly. Your guid is right.
It fails because of another problem.
I solved it!
Thanks! @a-murphy
