### ISSUE TITLE
Outage: failing to provision job nodes

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#2873]
No builds are proceeding. All fail to provision a job node.

Example build: https://app.shippable.com/runs/57ac6390626fb70f005c69bf/1/console

FYI I am using "unstable" and this previously resulted in a multi-day outage (https://github.com/Shippable/support/issues/2772)

Cc @kanthchandra

**Comment by rarkins** [comment]
Cc @manishas @a-murphy @abhijitkini @rageshkrishna @spsiddarthan @ric03uec
This is another complete outage, perhaps for unstable customers only?

**Comment by rarkins** [comment]
Someone please acknowledge and add tag https://github.com/Shippable/support/labels/bug-SOS

**Comment by rarkins** [comment]
![image](https://cloud.githubusercontent.com/assets/6311784/17588216/a46d4958-5fcd-11e6-9803-b95709b9d475.png)

**Comment by spsiddarthan** [comment]
@rarkins, We're looking at it right now. Will revert back to you shortly.

**Comment by rarkins** [comment]
@spsiddarthan thanks

**Comment by spsiddarthan** [comment]
@rarkins, We're still looking as to why this happened, but here's the initial analysis. We suspect it's due to an issue from aws's end. This is the message we got from AWS "We are investigating increased error rates for API requests and new instance launches in the US-EAST-1 Region."

Could you please try rebuilding your stuck builds?

**Comment by rarkins** [comment]
@spsiddarthan I have restarted a couple of builds and will see if they can provision a build node

**Comment by rarkins** [comment]
@spsiddarthan I can confirm that they're getting job nodes now and have begun their builds

**Comment by spsiddarthan** [comment]
@rarkins, Thank you for confirming! 

Dropping priority level to bug. Will need to speak with @rageshkrishna to debug what happened here.

**Comment by kanthchandra** [comment]
![selection_234](https://cloud.githubusercontent.com/assets/1583444/17589714/da27e12c-5ff3-11e6-8411-5b45769843e2.png)

@rarkins It looks like its an AWS issue and the errors that we are getting in the logs do match with the error that they have mentioned in the status page. So I'm removing the bug label. Let us know if you still run into this. From our end we have verified that builds are triggering and your subscription also seems to be fine.

**Comment by rarkins** [comment]
@kanthchandra do you you have systems in place to detect these error rates at *your* end and display a status? It sounded like the first you aware of it was responding to this issue, but didn't this impact every build of every customer?

I agree though it's not a bug, but little concerning if you don't have alerting when instances stop launching.

**Comment by rarkins** [comment]
This problem has reoccured (raised in #2906)

**Comment by manishas** [comment]
This was from 5 days ago, so closing. The issue from today will be tracked in 2906.

**Comment by Zhomart** [comment]
900 years? That's too much for me to wait.
