### ISSUE TITLE
Project doesn't show up in /projects response

### ISSUE THREAD

**Issue by HelainSchoonjans** [Shippable/support#2874]
Dear supports,

One of my repositories has been recently enabled in shippable ( id 579f4221ebf6220b00c0ce99 ). I can't however access it throught the Shippable API:

It doesn't show up when doing a GET request on the /projects endpoint.
When doing GET /projects/579f4221ebf6220b00c0ce99 I can only get the following response:

> {
>   "logType": "warn",
>   "methodName": "common|validateProjs|callerId:55cdad6325413a0b0072f844|_checkProjectPermissions",
>   "id": 2000,
>   "message": "No access or object not found for id: 579f4221ebf6220b00c0ce99"
> }

I already tried syncing the project with the Shippable web interface. My other projects show up as usual.

Thanks

**Comment by a-murphy** [comment]
The token you are using to make the API call does not have access to that project.  It looks like it belongs to another account.  Synchronizing your account will only update the list of projects that you have access to; it won't update the lists of projects that other accounts can access.

**Comment by manishas** [comment]
closing this issue. @HelainSchoonjans let us know if you have additional questions.
