### ISSUE TITLE
Cancelled build Github integration

### ISSUE THREAD

**Issue by kqdtran** [Shippable/support#2875]
Is there anyway we can hide cancelled build(s) from Github integration? For example, one of our team members push back-to-back commits for a pull request. Two builds were queued, and we decided to cancel one of them.

![](https://i.imgur.com/RLOlLoH.png)

, but then the overall result of the pull request looks like the build failed.

![](https://i.imgur.com/NAPd8Zl.png)

Is it possible to exclude cancelled builds?

**Comment by manishas** [comment]
@kqdtran as of now there is no way to exclude canceled builds. We will keep this on our radar to see if we get more requests for this feature.
