### ISSUE TITLE
Application Load Balancing

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#2876]
Any plans in the near term to support [application load balancing](https://aws.amazon.com/blogs/aws/powerful-aws-platform-features-now-for-containers/) target groups for ECS?

The drop down on the routing tab only shows classic load balancers from my account.

**Comment by trriplejay** [comment]
We definitely want to support these. I'm not sure of the time table, but I'll mark this as a feature request and we'll let you know.

**Comment by Kirtap** [comment]
need this as well.

**Comment by pwarnock** [comment]
Closing this issue since the feature is now supported. http://docs.shippable.com/pipelines/resources/loadBalancer/
