### ISSUE TITLE
question about scripted download

### ISSUE THREAD

**Issue by simbo1905** [Shippable/support#2877]
Is it possible to script a download of an "archive=true" ci build ?

**Comment by manishas** [comment]
@simbo1905 we no longer store build artifacts and the archive: true tag has been deprecated. You can still upload your artifacts. Instructions are at http://docs.shippable.com/ci_configure/#build-artifacts

**Comment by simbo1905** [comment]
that's not really a feature I want to use. I was suffering from very slow code compiles with Play on OpenShift so wanted a ci service where I could have autoscaling 12-factor instances pull the built `sbt dist`. your solution of pushing the final build means that I need some other stateful accounts to host the files. I may as well host Jenkins on OpenShift and skip a step. May my next project will be containers and I will use shippable but for a simple app on a public cloud it's missing a "no brainier" feature.

**Comment by avinci** [comment]
We are adding this back by default as tons of people asked for it. We will allow you to do this in the next few weeks.

**Comment by manishas** [comment]
dup of https://github.com/Shippable/support/issues/2444
