### ISSUE TITLE
Error to connect to github.com during ci step

### ISSUE THREAD

**Issue by danielfbm** [Shippable/support#2879]
### Description of your issue:
Build is unable to connect to github.com
I added a ``curl`` command just to make sure it was not my ``go get`` command, and the result is the same. 

A few hours ago I could successfully build with almost the same script, and I haven't really changed the github part

Is this a temporary issue? 

NOTE: If you are experiencing a build failure, please include:
https://app.shippable.com/runs/57b1e3d1fde2520e006a68b8/1/console

Last build that it was working
https://app.shippable.com/runs/57b1d200c98b330e004c5ede/1/console

**Comment by rageshkrishna** [comment]
@danielfbm It looks like your recent builds have run successfully. I think it's safe to assume it was just a temporary issue because we are not seeing any global problems connecting to github.com. Please let me know if you see it happening again and we'll investigate further.
