### ISSUE TITLE
Is there a way to prevent "gradle check" running automatically after gradle assemble

### ISSUE THREAD

**Issue by pplaatje** [Shippable/support#2880]
Hi,

We have some unit tests in our code, but we're still figuring out how to best run them. Right now, our build will fail on the gradle check step, as the tests can't find the compiled resources. Is there any way to prevent "gradle check" from executing automatically?

Thanks!

**Comment by a-murphy** [comment]
It sounds like you haven't said what you want the build to do, so it's using a default script.  Specifying another set of commands in the `build: ci` section of your `shippable.yml` as documented [here](http://docs.shippable.com/ci_configure/#the-ci-section) will replace the default commands with whatever you list.

**Comment by pplaatje** [comment]
Thanks, I have put a ci section in my yml file though:

language: java

jdk:
  - oraclejdk8

ci:
   - gradle assemble

**Comment by a-murphy** [comment]
The `ci` section belongs in the `build` section.  Could you try this shippable.yml?
```YML
language: java

jdk:
  - oraclejdk8

build:
  ci:
    - gradle assemble
```

**Comment by pplaatje** [comment]
Yeah, just figured it out a second before posting. Build is succeeding now, thanks a lot!
