### ISSUE TITLE
deployment key not used by npm

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#2881]
Build failure: 
[https://app.shippable.com/runs/57b2343000cee6110080f1e5/1/console]

Error while npm is checking out ember-dds project, which is successfully checked out here:
[https://app.shippable.com/runs/57b2330500cee6110080f140/1/console]

Looks like the deployment key is not being used?

**Comment by BryanCrotaz** [comment]
@abhijitkini could we get some support on this please?

**Comment by rageshkrishna** [comment]
Hi @BryanCrotaz. To diagnose this, can you please add the following lines to your yml file, right before the `npm install`:

````
 # This will list all the keys available to ssh agent
 - ssh-agent -l

 # This will show us which keys are being used to negotiate the connection
 - ssh -vT git@bitbucket.org
````

We add the deploy keys to ssh-agent by default, so it's odd that it isn't available when the `git clone` is running.

**Comment by BryanCrotaz** [comment]
pushed.

**Comment by BryanCrotaz** [comment]
branch is `test_shippable_keys`

**Comment by BryanCrotaz** [comment]
```
ssh-agent -l 0s  
unknown option -- l
usage: ssh-agent [options] [command [arg ...]]
Options:
  -c          Generate C-shell commands on stdout.
  -s          Generate Bourne shell commands on stdout.
  -k          Kill the current agent.
  -d          Debug mode.
  -a socket   Bind agent socket to given name.
  -t life     Default identity lifetime (seconds).
```

**Comment by rageshkrishna** [comment]
Sorry, my bad. That should have been `ssh-add -l`

**Comment by BryanCrotaz** [comment]
https://app.shippable.com/runs/57b595bd3c799a1000aa3c62/1/console

**Comment by BryanCrotaz** [comment]
@rageshkrishna  Do you mean the deployment key?

If so you can see it has been as there is a shippable build working successfully from the project that npm is trying to download.

**Comment by rageshkrishna** [comment]
Every project on Shippable gets its own key pair. Because of the way SSH keys work, we can't share them across projects as GIthub/Bitbucket will not allow you to add the same keys on multiple entities.

Your other project builds successfully because we use the project-specific key pair to clone it.

The only way to make dependencies work across private projects is to manually set the subscription key that I linked to earlier either at the repo level (which works, again, only if you have one dependency that you care about), or at an account level that you can then give access to all the dependencies you need.

**Comment by BryanCrotaz** [comment]
We have around 150 repos that we need to migrate from Bamboo. That would mean adding 150 keys to an account, or doing a very complex setup to add keys to each dependency repo.

If we could have an ssh key for our account and one for the project, we could choose how to authorize (with what level of security/hassle)

**Comment by BryanCrotaz** [comment]
hang on, is that what you're suggesting is already there? 
Do we have a "deployment key" per project and a "subscription key" per account?

**Comment by rageshkrishna** [comment]
You're correct -- the subscription key is for the subscription and is available to builds on all projects in that subscription. Adding that one key to an account that has access to all your dependencies should get your scenario to work.

**Comment by BryanCrotaz** [comment]
may I suggest you add this information in the docs where they talk about deployment keys

**Comment by rageshkrishna** [comment]
Sorry for not getting around to this sooner. We have updated the docs with more details on how SSH keys are used with recommendations on what to use when, and how: http://docs.shippable.com/ci/advancedOptions/sshKeys/
