### ISSUE TITLE
unable to parse repository info: repository name component must match

### ISSUE THREAD

**Issue by twillms07** [Shippable/support#2882]
This was working before. Not sure why this is failing at this stage now. We're trying to get our site launched.

- docker build -t website-backend:$WEBSITE_SERVER_ENV.$BUILD_NUMBER .

https://app.shippable.com/runs/57b3defd2a033c0f00ba41ff/1/console

**Comment by rageshkrishna** [comment]
@twillms07 The error message indicates that docker is unable to process a repository name in your Dockerfile. Has anything changed in your Dockerfile recently? What does the `FROM` line contain?

**Comment by twillms07** [comment]
Hi Ragesh - I think that there's an extra FROM. I was in the middle of updating but have been working for over 12 hours so I think I missed it. Manisha saw that to and I've changed and I'm rebuilding. Thanks for the quick response.

**Comment by manishas** [comment]
Todd confirmed that it works now so closing this issue.
