### ISSUE TITLE
Why do we need admin privilege of our GIT at the organization level?

### ISSUE THREAD

**Issue by quantumbuild** [Shippable/support#2883]
### Description of your issue:
Under our GIT organization we have many repos. We only provide admin privileges of the repo of the build account. However shippable requires admin right at the organization level. How do we configure?

We have reported the issue to Tom Trahan, but haven't not gotten a response back. 

Would you provide a response asap?

**Comment by ttrahan** [comment]
Shippable will recognize and honor the permissions you set at the repo level, without requiring similar permissions at the organization level. However, prior to this being possible, an owner of the organization must login to Shippable at least once to initialize the account on Shippable. Once an owner of the organization has logged in, all repo-level activities (e.g. enabling a project, running a build, etc.) can be managed by users with repo-level permissions only.
