### ISSUE TITLE
Error building images (Internal error getting builder token for account id)

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#2884]
We are having trouble running builds. It fails with following error.
```
Internal error getting builder token for account id xxxxxxxxxx : SyntaxError: Unexpected token C
```

**Comment by trriplejay** [comment]
can you try again? I can't seem to reproduce. We may have had a brief hiccup during a deployment.

**Comment by phagunbaya** [comment]
Seems to be working fine now.
