### ISSUE TITLE
Shippable tutorial includes slashes in repository names, but this is not permitted.

### ISSUE THREAD

**Issue by ezeeetm** [Shippable/support#2886]
build link
https://app.shippable.com/runs/57b9062f4d7c050e00834eac/1/console

The Shippable tutorial for DDC here
http://blog.shippable.com/getting-started-with-docker-datacenter

and shippable.yaml docs for DTR integration here
http://docs.shippable.com/ci_configure/

both use the following line to build an image to ship to DTR
```
  post_ci:
    - docker build -t ship-dtr.in/sdemo/sample_app:$BRANCH.$BUILD_NUMBER .
```

However, this throws:
```
docker build -t dtr.stationddc.com/admin/cdTest:$BRANCH.$BUILD_NUMBER . 0s  
repository name component must match "[a-z0-9](?:-*[a-z0-9])*(?:[._][a-z0-9](?:-*[a-z0-9])*)*"
```
according to #2558, which is closed, slashes are not permitted in repo names.  How are these tutorials ever worked, if that is the case?

**Comment by rageshkrishna** [comment]
I don't think the slashes are the problem. Repo names must be lower case. Can you try changing `cdTest` to `cdtest`?

**Comment by ezeeetm** [comment]
@rageshkrishna you are correct, thank you very much!
