### ISSUE TITLE
API to Add On-Premise Build Node

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#2888]
Hi there! I've built out my automation to create build nodes in AWS (specifically via a fixed size auto-scaling group). I would like a machine to automatically add itself to my Shippable account's node list. A brief look at the API docs does not indicate that this is possible.

How can I go about doing this? If it's not possible, can I issue this as a feature request?

Thanks!

**Comment by manishas** [comment]
@BlueDragonX thanks for the suggestion. We have had this request from other customers so we will definitely put it in our backlog for an upcoming milestone.

**Comment by vkhatri** [comment]
👍

**Comment by avinci** [comment]
this is a missing API doc. Again, next week we will have swagger api docs and you will be able to do it. Let me make sure the APIs are open to all users. 

@chetantarale we need to sample this out so that folks can do this

**Comment by ankul-shippable** [comment]
@BlueDragonX we have added the docs for clusterNodes. You can check them [here](http://docs.shippable.com/api/docs/#/ClusterNodes). 
We have also created a [nodejs project](https://github.com/shippableSamples/provision-custom-nodes) to provision custom nodes. You can follow the instructions in README.md.
Please let us know if you have any issues/doubts. Thanks
