### ISSUE TITLE
Support for read-only flag in AWS ECS task definition

### ISSUE THREAD

**Issue by stekershaw** [Shippable/support#2891]
Similar to  #2749, in that I imagine it is a feature request to support another AWS ECS task definition parameter.

I'd love to be able to run containers with read-only root filesystem, as I often do when using Docker or ECS directly. ECS parameter is _readonlyRootFilesystem_: http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_storage

Thanks!

**Comment by manishas** [comment]
This is now available. Docs are updated at http://docs.shippable.com/pipelines/resources/dockerOptions/#mapping-dockeroptions-to-your-container-service

Please let us know if you have any questions :)

**Comment by manishas** [comment]
closing this since it is complete. @stekershaw let us know if we can help with anything else.
