### ISSUE TITLE
Need tabs or some way of grouping on the CI dashboard

### ISSUE THREAD

**Issue by failpunk** [Shippable/support#2892]
### Description of your issue:
Feature Request

The dashboard is getting very crowded and it's very hard to keep track of what is building or has been build.  It would be great a be able to group things on the dashboard so it's possible to find them easier.

**Comment by manishas** [comment]
@failpunk can you describe in a bit more detail what the problem is and what you're proposing?

The in progress builds are currently separated into a panel which shows up at the top of a dashboard page when there are builds in progress.

**Comment by manishas** [comment]
also, there is some customization you can do for the dashboard: http://localhost:5555/navigatingUI/projects/settings/#dashboard-settings

**Comment by manishas** [comment]
@failpunk if you get a chance, do let us know any improvements you want to suggest in this area.
