### ISSUE TITLE
Improve Error Messages for provisioning Load Balancers in Pipelines

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#2894]
I'm unable to get my deployed containers exposed through the load balancer I have configured in Shippable, and I'm finding that there's very little documentation to help me out. 

I've have a number of small containers that provide services, fronted by an NGINX server that acts as a proxy. On kubernetes alone (without Shippable), I haven't had any trouble getting my configuration to work. 

On Shippable, my load balancer config looks like this:
![screen shot 2016-08-22 at 10 47 18 pm](https://cloud.githubusercontent.com/assets/1018189/17878635/6b852728-68ba-11e6-99d6-c44426f49f98.png)

However, in my Kubernetes console, this is what gets created, with no external ports defined:
![screen shot 2016-08-22 at 10 47 48 pm](https://cloud.githubusercontent.com/assets/1018189/17878648/7b042352-68ba-11e6-9d2b-813d187f14c7.png)

Is someone able to help me get this configured?

**Comment by trriplejay** [comment]
I notice on your status page, in your events tab there is an error from gke stating:
```
Error creating load balancer (will retry): Failed to create load balancer for service...
```

When you add external ports to your load balancer, we create a service in gke with `type: LoadBalancer` which you may be familiar with from the gke docs: http://kubernetes.io/docs/user-guide/services/#type-loadbalancer

When specifying type: LoadBalancer, gke automatically performs a few tasks to expose your service externally, including assigning an external IP and creating forwarding rules based on the ports you have exposed.

Unfortunately I don't have the ability to further debug why the load balancer is failing to be created.  Perhaps there is some configuration issue with your gke cluster? Or some limitation with assigning IPs and creating forwarding rules?


You say on kubernetes alone it works fine. are you creating a service with type: LoadBalancer or just using the default type?

**Comment by trriplejay** [comment]
oh, actually I was just able to expand that error message, and I see that it says this:
```
failed to ensure static IP : error creating gce static IP address: googleapi: Error 403: Quota 'STATIC_ADDRESSES' exceeded. Limit: 15.0, quotaExceeded
```

**Comment by ryan-kimber** [comment]
That makes sense.
Is it possible to change the UI so these failures to provision the load balancer are displayed prominently and the error is displayed clearly? A modal would be great for an error like this.

**Comment by manishas** [comment]
@ryan-kimber i am going to close this bug since we're planning to migrate everyone to the  new pipelines in the next few weeks.
