### ISSUE TITLE
Bitbucket Repo Webhook is not created

### ISSUE THREAD

**Issue by naxmefy** [Shippable/support#2895]
Project: https://app.shippable.com/projects/57bad3994d7c050e00837dbb/settings/runs

i can press ``` reset ```, delete the project or try to disable and enable the webhook settings
but the webhook won't created in the repository settings.

I dont know why

**Comment by kanthchandra** [comment]
@naxmefy It looks like you have enabled the projects from [infra tab] (https://app.shippable.com/subscriptions/56619e0c1895ca44744d0edd/infraStatus). Please delete the project and go to the [ci tab] (https://app.shippable.com/subscriptions/56619e0c1895ca44744d0edd/ci/enable) tab and enable the project from there. The webhooks should autmatically get created.

**Comment by naxmefy** [comment]
thank you - works
