### ISSUE TITLE
Support for haskell

### ISSUE THREAD

**Issue by piyush-kurur** [Shippable/support#2896]
As far as I can tell you do not have haskell builds yet. I have been using travis for quite some time. It would be great if you can support haskell.

To start with I have a docker image suitable for it I guess
- https://hub.docker.com/r/raazcrypto/docker-haskell-cli/
- [Git hub Repository](https://github.com/raaz-crypto/docker-haskell-cli)

If you are interested this can be used as the starting point of haskell support.

**Comment by piyush-kurur** [comment]
Sorry renamed the repository and image. The CLI at the name end was a typo it should have been ci 

* https://hub.docker.com/r/raazcrypto/docker-haskell-ci/
* [Github repository](https://github.com/raaz-crypto/docker-haskell-ci)

**Comment by piyush-kurur** [comment]
Just to let you know that I have managed the first successful build of a haskell project
with shippable.

https://bitbucket.org/piyush-kurur/naksha

**Comment by piyush-kurur** [comment]
The repository has now moved into a team repository

https://bitbucket.org/naksha/naksha/

**Comment by piyush-kurur** [comment]
@rageshkrishna What is the status of this? If you do not have the necessary resource for this, I can help you out on this.

**Comment by manishas** [comment]
Haskell builds can be run with a custom Docker image or by installing the necessary dependencies. Closing as deferred, but will reopen if we see a lot of +1 feedback.
