### ISSUE TITLE
Inviting Team Members?

### ISSUE THREAD

**Issue by tspicer** [Shippable/support#2898]
Greetings,

It was not obvious in the UI nor could I discern the actual steps to invite other team members into an account via the docs. 

I have a couple of DevOps team members I would like to add to my (company) account. Can you kindly advise how best to proceed?

**Comment by a-murphy** [comment]
Team members cannot be directly added to Shippable.  The source provider permissions are used to determine access to subscriptions and projects, so if your team members have access to a repository with the source provider and log into Shippable they should be able to access the Shippable project.

**Comment by tspicer** [comment]
Does it inherent all the integration configurations as well? Meaning, all the setups I have for AWS, ECR, IAM...? Would want to avoid this sort of setup for each person if possible. Thanks!

**Comment by a-murphy** [comment]
Any integrations added to a subscription (the group of projects belonging to a GitHub organization or account) will be available to projects in that subscription, so another user who logs in to run a project in a subscription that you have added integrations to will be able to use those integrations.  However, they will not be able to add the same integration to other subscriptions.  If these users have forks of the repository in their own GitHub accounts, those forks will not have access to the integrations.

**Comment by manishas** [comment]
closing this issue since the question is answered.
