### ISSUE TITLE
Feature Request: Opening jobs in a separate tab

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2899]
It would be convenient for jobs listed on the summary tab of a run to be links, so they could be opened in new browser tabs. Currently only the job navigation tabs across the top (and the jobs in the "More Runs" menu) are links.

**Comment by harryi3t** [comment]
Thanks @mattclay for the feedback.
We have taken this to our internal issue tracking system.
Will update here once this feature is in production.

Have modified the feature to include the current functionality also.
Now on normal click it will open the job in current tab (as usual)
And on Ctrl-Click it will open the job in a new tab.

Let me know you have some other concerns.

**Comment by manishas** [comment]
This was complete a few months ago and it looks like we missed updating it. Closing this issue.
