### ISSUE TITLE
Shippable Service Upgrade Maintenance 9pm PST 8/24

### ISSUE THREAD

**Issue by abhijitkini** [Shippable/support#2901]
Started at 9pm PST on 8/24.

For the latest status: http://status.shippable.com

**Comment by abhijitkini** [comment]
This scheduled upgrade can cause unexpected build failures and timeouts. 

This ticket and the status will updated once the upgrade is complete.

**Comment by vaibhavswarnkar** [comment]
When this upgrade would be finished because I not cannot open my account.

**Comment by abhijitkini** [comment]
The scheduled upgrade has been completed. http://status.shippable.com. 

Closing this issue.
