### ISSUE TITLE
Multiple Docker Containers App? 

### ISSUE THREAD

**Issue by yanikkoval** [Shippable/support#2902]
Is it possible to run multiple docker containers, yet connected,  application with shippable?

**Comment by ryan-kimber** [comment]
That's all in how you configure your deployment. 

If you were using Google Container Engine (GKE), you could set up clusters on the same virtual network and create two pipelines in Shippable for deployment, deploying one part of your app to one cluster, and the other to the other cluster.

**Comment by manishas** [comment]
@yanikkoval you can run docker compose on Shippable as part of your CI workflow by including commands in the yml. However if you want to run a real test environment, you should set up a cluster on Amazon ECS or GKE or any container service and create a pipeline on Shippable for deployment. As an example, check out http://docs.shippable.com/tutorials/pipelines/samplePipeline/
Even though this example brings up a single container, you can easily define similar pipelines and deploy to the same cluster.

**Comment by manishas** [comment]
Let me know if you need any help with the config or have additional questions.
