### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by sahanarula** [Shippable/support#2903]
### Not able to Login

![screen shot 2016-08-25 at 1 56 19 pm](https://cloud.githubusercontent.com/assets/7797853/17961908/ddba5e54-6acb-11e6-882e-90c391e1f55e.png)

**Comment by LuisMuniz** [comment]
Same thing here.

**Comment by hunt3ri** [comment]
Any update?

**Comment by manishas** [comment]
we're looking into this....

**Comment by navymaker** [comment]
Same thing, but sometimes I get following error:
<img width="645" alt="login" src="https://cloud.githubusercontent.com/assets/3058188/17981775/b9a2636c-6b0d-11e6-9e5b-dc95857bbba3.png">

**Comment by manishas** [comment]
This was because of the upgrade and we have found the issue and fixed it. Please let us know if it happens again.
