### ISSUE TITLE
Broken Layouts

### ISSUE THREAD

**Issue by yanikkoval** [Shippable/support#2904]
You have broken layouts on 
`http://docs.shippable.com/int_paas_iaas_providers/*` URL.
For example: 
http://docs.shippable.com/int_paas_iaas_providers/tutorials/ci/runSampleCIBuild/ 

Looks like: https://monosnap.com/file/OxTDBhqqUEvcpQcQjpkrzezseNSed6 

Google Chrome Version 52.0.2743.116 (64-bit)
OS X

**Comment by manishas** [comment]
@yanikkoval we have revamped the docs. Please go to docs.shippable.com to access the new docs.

**Comment by manishas** [comment]
closing this issue
