### ISSUE TITLE
Pipelines V2: Created Integration Resource, but doesn't appear in list

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#2907]
I'm in the middle of building our CD pipelines, so it's actually a good time for V2 to come out (that is, prior to my getting things up and working on V1).

So, I dove right in. The resources tab wants me to create a resource, so I click add resource. I automatically taken to the create integrations page. I create an integration there. The UI takes me back to the resources page(tab), but the resource does not display in the list. 

I've tried logging out and back in, and just giving it some time, but the item still doesn't end up in the list.
![screen shot 2016-08-25 at 11 17 04 am](https://cloud.githubusercontent.com/assets/1018189/17974799/7d98348a-6ab5-11e6-8d85-415a0ad46cd9.png)

![screen shot 2016-08-25 at 11 16 27 am](https://cloud.githubusercontent.com/assets/1018189/17974779/66977264-6ab5-11e6-86d1-7ead0012a3ec.png)

**Comment by a-murphy** [comment]
The "add resource" button is expecting you to select a repository that contains a `shippable.resources.yml` and/or a `shippable.jobs.yml`, and then resources will be created for the objects defined in those files and updated when the files change.  Adding a source provider integration, such as GitHub or Bitbucket, to the subscription for the first box will then let you select the project and branch that contain your YML files.

**Comment by ryan-kimber** [comment]
Are there instructions somewhere yet for the Pipelines V2 stuff? It would
be helpful to have documentation links right in the app to the relevant
parts of the documentation.

**Comment by ryan-kimber** [comment]
I've navigated myself to here: http://docs.shippable.com/pipelines/gettingStarted/

I was surprised to not find anything on the Blog about these changes.

**Comment by ryan-kimber** [comment]
Oh, I found the line that mentions this in the documentation.

We'll create a separate repository for the configuration for each pipeline we have.

**Comment by manishas** [comment]
@ryan-kimber let us know if you need help with this.

The docs have been updated to describe how CD pipelines work: Here is an [overview](http://docs.shippable.com/pipelines/overview/) and here is a [Getting started guide](http://docs.shippable.com/pipelines/gettingStarted/)

We also have a sample application and a tutorial showing how it works: http://docs.shippable.com/tutorials/pipelines/samplePipeline/

The sample application and tutorial will be enhanced to describe a more complex workflow later today or early tomorrow. Also, we're happy to jump on a hangout and answer any questions.

**Comment by manishas** [comment]
@ryan-kimber i am assuming you found what you needed here, so closing this issue.
