### ISSUE TITLE
Pipelines V1: Navigating to Pipelines V1 Tab By URL never loads

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#2908]
When using a URL to get to the Pipelines V1 tab, or when refreshing your browser, the tab never loads, you just get the spinner.

If, instead, I click one of the other tabs, then click the Pipelines V1 tab, the content loads correctly.

https://app.shippable.com/subscriptions/my-project-id/pipelinesv1

![screen shot 2016-08-25 at 11 24 59 am](https://cloud.githubusercontent.com/assets/1018189/17975135/95596084-6ab6-11e6-8992-bdb320dbe7b9.png)

**Comment by failpunk** [comment]
This was really slow for us, but seems to load now.

**Comment by manishas** [comment]
@ryan-kimber are you still running into this? We made a fix this morning that addressed overall platform instability so want to make sure that covered your case.

**Comment by ryan-kimber** [comment]
Still happens. Easy to reproduce: Got the pipelines V1 tab, wait for
everything to load, then hit refresh. For me, it just shows the spinner
indefinitely.

**Comment by ryan-kimber** [comment]
Working now.
