### ISSUE TITLE
Pipelines V1: Link to pipeline settings page not working

### ISSUE THREAD

**Issue by failpunk** [Shippable/support#2909]
### Link to pipeline setting page not working.
Link from cell manifest to **pipeline settings page** takes you back to the app.shippable.com and NOT to the settings page.

![screen shot 2016-08-25 at 11 27 44 am](https://cloud.githubusercontent.com/assets/1109167/17981140/3815922a-6ab7-11e6-8495-564bf7f2cda8.png)

**Comment by failpunk** [comment]
Does anyone know of another way to get to the pipeline settings page?  I can't build new versions to deploy right now!

**Comment by manishas** [comment]
@trriplejay we need to fix this link.

**Comment by a-murphy** [comment]
Until the link is fixed, clicking the pipeline (the middle column) on the Pipelines v1 tab will also go to that settings page.

**Comment by manishas** [comment]
this is complete, closing.
