### ISSUE TITLE
Builds are stuck and dashboard showing error

### ISSUE THREAD

**Issue by DaHoopster** [Shippable/support#2910]
### Description of your issue:
It started about 30 minutes ago. Builds are stuck and when loading the dashboard page, it shows me this error (screenshot). This is impacting all development and production deployment on our end. Please help ASAP.

<img width="1388" alt="screen shot 2016-08-25 at 11 35 08 am" src="https://cloud.githubusercontent.com/assets/2730866/17981303/0217419a-6ab8-11e6-9dfd-c0769272b4f7.png">

- Link to the build failure
https://app.shippable.com/accounts/571fd9bfc631130c005180d7/dashboard
- Scripts called from the yml (optional)

**Comment by DaHoopster** [comment]
__Update 1__

Logged out and tried to log back in, go a different error screen
<img width="1386" alt="screen shot 2016-08-25 at 11 39 35 am" src="https://cloud.githubusercontent.com/assets/2730866/17981458/b1bfcaea-6ab8-11e6-9be9-e5d4818502da.png">

**Comment by DaHoopster** [comment]
Yep, our github repo integration also confirms the error:

<img width="944" alt="screen shot 2016-08-25 at 11 41 45 am" src="https://cloud.githubusercontent.com/assets/2730866/17981541/f8f739e8-6ab8-11e6-991c-e0a9447b1006.png">

**Comment by rarkins** [comment]
Same error here. @manishas @rageshkrishna @a-murphy this seems like an SOS situation

**Comment by rarkins** [comment]
My project dashboard:
![image](https://cloud.githubusercontent.com/assets/6311784/17981902/eb685986-6b05-11e6-9f69-75306da2000f.png)

**Comment by rarkins** [comment]
Shippable status thinks everything is fine: http://status.shippable.com/ (which is itself another failure you should look into).

However this presumably explains why/how things have gone so wrong today:
![image](https://cloud.githubusercontent.com/assets/6311784/17982091/b52115e2-6b06-11e6-9eda-97f38b9f4ff2.png)

**Comment by manishas** [comment]
looking into this.... tagging @ric03uec @avinci.

**Comment by mattclay** [comment]
I'm also seeing the same errors (as well as a few others):

```
(Id: 2000) No access or object not found for query: [object Object]
warn: common|validateSubs|callerId:573f3445d911710c00c93693|_injectSubscriptionPermissions
```

```
(Id: 2000) No access or object not found for query: [object Object]
warn: common|validateProjs|callerId:573f3445d911710c00c93693|_getProjectPermissions
```

```
(Id: 4005) Failed to getMasterIntegrations for masterIntegrationIds=55bba7932c6c780b00e4426c,562dc2f048095b0d00ceebcd
verbose: accountIntegrations|getS|callerId:573f3445d911710c00c93693|_getMasterIntegrationFields
```

**Comment by kileyhykawy** [comment]
We are also seeing the same kind of errors:
`(Id: 2000) No access or object not found for query: [object Object]
warn: common|validateProjs|callerId:56ba599d87f1950c003e278d|_getProjectPermissions`

**Comment by rarkins** [comment]
![image](https://cloud.githubusercontent.com/assets/6311784/17982336/b5b34a24-6b07-11e6-8bf7-e83feb914f33.png)

**Comment by manishas** [comment]
We have identified a probable cause and are fixing it right now. I'll update this issue soon. Please note that this is mainly an issue with Shippable UI - builds should not be unaffected. 

http://status.shippable.com/ is showing status:

![image](https://cloud.githubusercontent.com/assets/2983749/17983015/51812f64-6abf-11e6-93e8-a3385642765f.png)

**Comment by DaHoopster** [comment]
@manishas I think there has to be some issues with the API as well. Please see the screenshot I attached from our github account. It was reporting a 500 error for the webhook to shippable.

**Comment by rarkins** [comment]
@manishas I also experienced builds timing out around the same time this UI problem started. 

Example:
![image](https://cloud.githubusercontent.com/assets/6311784/17983119/4a9d5dc0-6b0b-11e6-8f83-c263c1dc55e8.png)

I subsequently had one build pass.

**Comment by manishas** [comment]
@DaHoopster @rarkins @mattclay @kileyhykawy this should be resolved now. Can you please confirm that everything is back to normal?

**Comment by DaHoopster** [comment]
yep, everything is back to normal.

**Comment by mattclay** [comment]
Everything appears to be working normally.

**Comment by manishas** [comment]
:+1:

Sorry about the inconvenience!

**Comment by manishas** [comment]
Closing this issue since it is resolved.
