### ISSUE TITLE
Add support for DigitalOcean

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2911]
So far I see no 1st class support for DigitalOcean within Shippable pipelines. I saw #1405 but the [linked docs page](http://docs.shippable.com/digitalocean/) is utterly broken and empty, thus I have no idea how this could work.

I may be missing something and maybe one should solve this with the "Docker" integration. If so, please point me to some resources which explain this. :-)

**Comment by manishas** [comment]
@mbrodala can you describe the scenario you were thinking of?

**Comment by mbrodala** [comment]
Basically native support for DO in Shippable pipelines as a recipient for build artifacts, thus basically a full deployment workflow.

**Comment by avinci** [comment]
We already have this in place. Are you asking for machine deployment of provisioning of machines?

**Comment by mbrodala** [comment]
Since I'm not using the Shippable pipelines yet, I'll close this one for now.
