### ISSUE TITLE
Localhost networking with custom images

### ISSUE THREAD

**Issue by elmpp** [Shippable/support#2915]
This is somewhat related to https://github.com/Shippable/support/issues/2542 , only difference being that I have bundled my processes up into the 1 image (php and postgres). 

I am experiencing problems connecting to the postgres DB from php. The PHP DB connection params are set through env variables in pre_ci_boot 

`build:
  pre_ci_boot:
    image_name: eu.gcr.io/partridge-alan/php-cli-wiremock-postgres
    image_tag: latest
    pull: true
    options: "-e SYMFONY__DATABASE__USER=postgres -e SYMFONY__DATABASE__HOST=localhost -e SYMFONY__DATABASE__PASSWORD="`

The container runs fine in testing locally.

I have tried also `--net=host` without success. Should 2 processes within the same container be able to address eachother via localhost? 

Build failure example - https://app.shippable.com/runs/57c088f81fcce00e00958901/1/console

One possible cause of this failure other than networking differences is if the entrypoint script overrides the image's default (it runs postgres and initdb before running the php tests). This seems to be the case but am unable to get eyes on the contents of it. Should i be able to see this through the scripts part of the console?

**Comment by a-murphy** [comment]
We do override the entrypoint in order to run the build scripts.  You can see this in the `docker run` command at the end of the `boot_container` section in the console; the scripts themselves are under "scripts" on the build page.  Could you try adding the commands that would normally run in the default entrypoint script to the beginning of the `ci` section in your `shippable.yml`?

**Comment by elmpp** [comment]
Yes, I could see the entrypoint is being swapped out. The docker run command is:

`sudo docker run -d --net=host -e SYMFONY__DATABASE__USER=postgres -e SYMFONY__DATABASE__HOST=localhost -e SYMFONY__DATABASE__PASSWORD= -v /home/shippable/cexec:/home/shippable/cexec -v /usr/bin/docker:/usr/bin/docker -v /home/shippable/cache:/home/shippable/cache -v /tmp/cexec:/tmp/cexec -v /var/run/docker.sock:/var/run/docker.sock --name=c.exec.api.66.1 --entrypoint=/home/shippable/cexec/build.sh -e RUN_MODE=production -e SHIPPABLE_API_URL=https://api.shippable.com -e SHIPPABLE_API_RETRY_INTERVAL=3 -e SHIPPABLE_CONTAINER_NAME=c.exec.api.66.1 -e SHIPPABLE_IS_OFFICIAL_IMAGE=false -e SHIPPABLE_IS_LEGACY_IMAGE=false eu.gcr.io/partridge-alan/php-cli-wiremock-postgres:latest`

Which refers to the entrypoint script:

`/home/shippable/cexec/build.sh`

However, this script is not visible through the scripts section of the console. It appears to me that these comprise of just the standard shell scripts and not anything dynamic to the job.

Can you please recommend a way to see this entrypoint script and also a good way to debug the state of a container (other than print statements), in particular the processes and networking??

**Comment by elmpp** [comment]
I have indeed moved the entrypoint commands into the ci: section
