### ISSUE TITLE
eaccess error permission denied on shippable deployed image

### ISSUE THREAD

**Issue by 360itsolution** [Shippable/support#2916]
I am very new to the dockerfile / shippable deployment pipeline.   I feel I am very close to having my environment setup, but seem to be stuck after build.  

I have a Dockerfile created.  When I run it locally all is well.  Shippable build is a successful deployment and push to Google Container Engine, however when the image is spun up on Google Container engine pod it throws this error npm WARN checkPermissions Missing write access to /usr/lib/node_modules

Nothing with npm install on the deployed google container engine is written and nodejs stops.  

If I have my Dockerfile working locally shouldn't it work when pushed to container engine through shippable?  I think I dont understand the correlation between Dockerfile and shippable.yml

**Comment by manishas** [comment]
@360itsolution we will look into this and get back to you.

**Comment by trriplejay** [comment]
@360itsolution 

Hello,  

One suggestion I have is to try moving your docker build to the CI section. In pre_ci, commands are run as a root user, which could be affecting the permission levels of the modules being installed.

**Comment by manishas** [comment]
@360itsolution I am closing this issue but please let us know if you're still running into it.
