### ISSUE TITLE
aWS Application ELB

### ISSUE THREAD

**Issue by jplimpens** [Shippable/support#2918]
### Description of your issue:
After configuring a pipeline v2 with some simple jobs the deploy job fails with error: 
" error creating serviceInvalidParameterException: Unable to assume role and validate the specified targetGroupArn. Please verify that the ECS service role being passed has the proper permissions."

Since the Application ELB is recently launched by AWS I figured the IAM user used lacks the proper permissions. Therefor I adjusted the user policies to allow usage of methods from the new API.
Snippet: 
Action": [
                "elasticloadbalancing:CreateListener",
                "elasticloadbalancing:CreateTargetGroup",
                "elasticloadbalancing:DescribeLoadBalancers",
                "elasticloadbalancing:DeleteListener",
                "elasticloadbalancing:DeleteTargetGroup",
                "elasticloadbalancing:DescribeTargetGroupAttributes",
                "elasticloadbalancing:DescribeTargetGroups",
                "elasticloadbalancing:DescribeTargetHealth",
                "elasticloadbalancing:ModifyListener",
                "elasticloadbalancing:ModifyTargetGroup",
                "elasticloadbalancing:RegisterTargets",

Unfortunately this didn't resolve the issue.
Then I updated the role Trust relationship.
Snippet:
         "ecs.amazonaws.com",
          "ec2.amazonaws.com" 

Unfortunately this too didn't resolve the issue.

As described in the documentation I use the targetGroupARN to point to the target group of the Application ELB.

Probably I'm missing something, so please advise.

Regards,

**Comment by manishas** [comment]
@trriplejay can we look into this?

**Comment by BlueDragonX** [comment]
Ensure you have an ecsServiceRole with path `/` and that it is assigned `AmazonEC2ContainerServiceRole`. It should have the `ecs.amazonaws.com` trust relationship.

Then ensure the ARN of your target is correct. When I was experiencing this issue it was because I was using the name of my target and not the ARN.

**Comment by trriplejay** [comment]
Did you attach the above policy to your `user`, or to your `role`? It sounds like internally we found a role that we thought would work, but must have been missing some of the necessary permissions. 

I think we could be doing a better job of verifying the selected role, but I'd say double check that the above policy that you mentioned is attached to the role that has the `ecs.amazonaws.com` trust relationship.

**Comment by jplimpens** [comment]
I checked the targetGroup arn, but that was ok (did try the ELB arn just to make sure, but switched back to targetGroup arn).

I ran through all IAM configs again..
- the shippable-user-to-allow-ecs-access user with policies as described in the docs, but with the updated methods for elasticloadbalancing.
- the shippable-role-to-allow-ecs-access with policies and trust relationship as described in the docs
- a ecsServiceRole which has assigned AmazonEC2ContainerServiceRole and trust relationship ecs.amazonaws.com

But I got the same error.

Since I was using an older AMI I decided to upgrade AMI (and docker agent). After that this error was gone. The deployment still failed, but I found it was due to permissions with the docker registry/repository in Artifactory. Unfortunately this wasn't something I could get from the shippable logging. I had to create the service manually to find the error on the task.

So I have  two more questions
- How can I get such logging (failing authentication as part of the shippable job logs
- I added Artifactory as a private docker registry. Pushing the image from the build works. Pulling the image should work since the manifest jobs is successful. However deploying fails due to failing autentication. Currently I allow anonymous to have a successful deployment, but obvious prefer otherwise.

**Comment by jplimpens** [comment]
the service events gave me 12 minutes of useless info. In the job as well as in AWS. It kept trying to deploy the service/task.

I found the error when I clicked the task shown in the service, then opening the container it showed the authentication error.

Thanks for the aws link. I forgot about that.
I'll close this issue now. Thanks for the help.
