### ISSUE TITLE
Build terminated

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#2919]
I am currently seeing [builds](https://app.shippable.com/runs/57c3df8dd69e8d0f00537a8b/1/console) being terminated during the `build_ci` step without any further action. The error status is shown at the `wait_for_exit` step with this error:

```
sudo docker logs -f c.exec.<repository>.30.1
No LSB modules are available.
Distributor ID: Ubuntu Description: Ubuntu 14.04.3 LTS Release: 14.04 Codename: trusty
Ubuntu confirmed
Looking for apt-get...
Found apt-get at /usr/bin/apt-get
Looking for sudo...
Found sudo at /usr/bin/sudo
Looking for git...
Found git at /usr/bin/git
Looking for ssh-agent
Found ssh-agent at /usr/bin/ssh-agent
Looking for python...
Found python at /usr/bin/python
Booting up CEXEC
Running CEXEC script
/home/shippable/cexec/build.sh: line 159:    33 Terminated              /home/shippable/cexec/dist/main/main
echo Container c.exec.<repository>.30.1 exited with 143
```

These are the last lines of the `build_ci` step:

```
apt-get install shellcheck
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  shellcheck
0 upgraded, 1 newly installed, 0 to remove and 124 not upgraded.
Need to get 635 kB of archives.
After this operation, 4,562 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-backports/universe shellcheck amd64 0.3.3-1~ubuntu14.04.1 [635 kB]
Fetched 635 kB in 0s (1,187 kB/s)
Selecting previously unselected package shellcheck.
```

There is no other output afterwards.

**Comment by manishas** [comment]
@rageshkrishna can we look into this? Looks like it's still happening...

**Comment by rageshkrishna** [comment]
@mbrodala It looks like the build container is somehow being forcefully terminated during, or right after, the installation of `shellcheck`. We have bash traps that should catch all the regular exit scenarios and run the on_failure scripts, but it's not even getting there. Somehow, the entire container is just dying abruptly. I'm not quite sure what could be causing this sort of failure.

I suspect it has something to do with the shellcheck installation. Would you mind sharing your `runnerfile.sh` so I can try and reproduce this and see what's really going on? Thanks!

**Comment by mbrodala** [comment]
Your questions gave me the idea to try to skip the [Bash Task Runner](https://github.com/stylemistake/bash-task-runner) and that indeed let my [build succeed](https://app.shippable.com/runs/57c956eb09de4a0f001f2532/1/console).

The Bash Task Runner also [sets up a trap](https://github.com/stylemistake/bash-task-runner/blob/233c33f0aa4950bc6218d5c57a8663a9ade7c72b/src/runner.sh#L6-L9) for processing so maybe that's the root cause?

**Comment by rageshkrishna** [comment]
Yes, that would explain it. We do our best to reset the traps between commands but if a single command sets a trap and then fails, there's not much we can really do to catch it.

**Comment by mbrodala** [comment]
OK, is there something you can suggest to fix this issue? Should the trap setup be fixed in Bash Task Runner? If yes, how exactly?

**Comment by rageshkrishna** [comment]
I'm don't really know bash task runner well enough to suggest anything just yet, but I will take a deeper look at it and get back to you. I find it odd that the runner would cause an exit even though the commands it runs are able to complete without errors.

**Comment by rageshkrishna** [comment]
@mbrodala I was trying to repro this with https://github.com/rageshkrishna/test-runner-shellcheck but I'm not able to run in to the same error. Perhaps you're doing something differently? At this point I'm not really sure why it's crashing for you but not for me. Would you mind taking a look at my repo and letting me know if I should try something else?

Thanks!

**Comment by manishas** [comment]
@mbrodala @rageshkrishna what is the way forward here :)

**Comment by mbrodala** [comment]
I'll get back to you this week.

**Comment by mbrodala** [comment]
I have just tried again and the build was terminated as previously. The last lines from the output differ slightly:

```
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  shellcheck
0 upgraded, 1 newly installed, 0 to remove and 130 not upgraded.
Need to get 635 kB of archives.
After this operation, 4,562 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-backports/universe shellcheck amd64 0.3.3-1~ubuntu14.04.1 [635 kB]
Fetched 635 kB in 0s (1,176 kB/s)
Selecting previously unselected package shellcheck.
(Reading database ... 35170 files and directories currently installed.)
Preparing to unpack .../shellcheck_0.3.3-1~ubuntu14.04.1_amd64.deb ...
Unpacking shellcheck (0.3.3-1~ubuntu14.04.1) ...
```

This is my `shippable.yml`:

```yaml
language: node_js

build:
  ci:
    - npm install
    - npm install -g bash-task-runner
    - runner build
```

This is my `Runnerfile.sh`:

```bash
task_prepare() {
  runner_log "Installing ShellCheck"
  echo "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-backports universe" > /etc/apt/sources.list.d/$(lsb_release -sc)-backports.list
  runner_run apt-get update -qq
  runner_run apt-get install shellcheck
}

task_shell_lint() {
  runner_log "Linting Shell scripts via ShellCheck"
  runner_run find \
    -name "*.sh" \
    -not -path "./node_modules/*" \
    -not -name "Runnerfile.sh" \
    -print0 \
    |
    xargs \
      -0 \
      -n1 \
      -P0 \
      script -q -c shellcheck
}

task_build() {
  runner_sequence \
    prepare \
    shell_lint
}
```

**Comment by mbrodala** [comment]
Interestingly the [build runs fine](https://app.shippable.com/runs/57ece13b6d80900e003a1189/1/console) if I drop the `runner_run` wrapper. (And [terminates again](https://app.shippable.com/runs/57ece2078c20f5100016c77f/1/console) if I undo this.)

That wrapper is responsible for outputting the command to be run for logging purposes and honestly [doesn't do much](https://github.com/stylemistake/bash-task-runner/blob/233c33f0aa4950bc6218d5c57a8663a9ade7c72b/src/runner.sh#L193-L197).

**Comment by mbrodala** [comment]
I was also able to fix this issue by dropping the `script` usage. This was an attempt to simulate a TTY to have full color output but after running this command separately I noticed a termination of the process.

So for me the issue seems fixed now, thanks for your help!
