### ISSUE TITLE
Pipelines: Support ECS Auto-Scaling

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#2921]
## Problem

ECS service scale is hardcoded in the pipeline using `replicas`. There is no way to configure auto-scaling in the pipeline or to use the existing scale of the service as the input to a deploy.
## Solution
1. Don't clobber the existing scale if no `replicas` resource exists. Currently it assumes a value of `1` if no `replicas` resource. Instead it should use the existing value.
2. Add support for service auto-scaling by adding a new `autoscale` resource or by extending the `replicas` resource.

This is related closely to https://github.com/Shippable/support/issues/2920.

**Comment by BlueDragonX** [comment]
Any word on this? We're going all in wish Shippable pipelines. I've migrated over five new projects and will be migrating the remaining 10 or so in the next three weeks. We'll be needing auto-scaling soon!

**Comment by BlueDragonX** [comment]
Any update?

**Comment by manishas** [comment]
This has been picked up for this month's milestone so should be addressed soon. I'll let you know when it's available.

**Comment by manishas** [comment]
@BlueDragonX this is now be available. We went with option 1: Don't clobber the existing scale if no replicas resource exists. Currently it assumes a value of 1 if no replicas resource. Instead it should use the existing value.

We will still assume a value of 1 if the service is being created for the first time. But in all other cases, it should work as expected. Please let us know if you run into any issues.

**Comment by pwarnock** [comment]
I deleted my replicas resource and reran the prod deploy (deployMethod: upgrade) and it went from 6 to 1. Was there anything else I needed to do?
