### ISSUE TITLE
Bitbucket authorisation in custom image

### ISSUE THREAD

**Issue by elmpp** [Shippable/support#2923]
I have a custom image that I am using to perform CI with. My account has been authorised with Bitbucket and runs well upon commits to a couple of branches for the project "api".

I am trying to add a stage within "on_success" that will package my project into a new docker image but am having trouble pulling down the source from Bitbucket at this point (using wget).

I had assumed that the VM upon which docker is running would have been already authorised with Bitbucket and my subsequent request from Docker would be allowed. Can you confirm this case else suggest ways in which i could get authorised? I was hoping for an environment variable to a token or password but cannot see anything. I know i can embed a .wgetrc file in the container but would rather not.

Thanks

Build failure link: https://app.shippable.com/runs/57c47831c96a570f00b9ddc6/1/console

**Comment by a-murphy** [comment]
The VM doesn't actually have access to all of your Bitbucket projects.  Shippable creates a deploy key to clone private projects and uses that, so a build can't get other private projects by default.  There are multiple different ways to allow access to other projects.

The easiest way to allow access to another project is usually to add the SSH key on the subscription settings tab to the other project (or account) on Bitbucket as a deploy key.  The subscription SSH key will be available in the build, and adding it as a deploy key is usually enough to clone another project. 

Another option is to add credentials as encrypted environment variables and use those in your commands.  To do this, encrypt the variables on the subscription settings tab and then add them to your shippable.yml in the `env` section as shown [here](http://docs.shippable.com/ci/shippableyml/).  If you have multiple environment variables, you can either encrypt them together as one encrypted variable or put them in a `global` section in `env` to avoid creating a different build for each line.

**Comment by ksnyde** [comment]
I'm running into the same issue I think. In my nodejs project my `package.json` file points to two separate git repos that look something like the following:

   "dependencies": {
      "rsvp": "^3.1.0",
      "stack-trace": "0.0.9",
      "private-dep-1": "git+ssh://git@bitbucket.org:transporters/private-dep-1.git",
      "private-dep-2": "git+ssh://git@bitbucket.org:transporters/private-dep-2.git"
    }

@a-murphy your first options -- aka, withe SSH key on subscription settings -- sounds like what I'd want to do but I'm afraid I may need a little more handholding. 

What I've done is to take the deployment key from shippable and add it to both the primary source repo as well as the two private repos. But I am still getting:

> npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror ssh://git@bitbucket.org/TEAM/REPO.git /root/.npm/_git-remotes/ssh-git-bitbucket-org-TEAM-REPO-git-58e80126: conq: repository access denied. deployment key is not associated with the requested repository.

Any idea what's wrong. Oh one last thing, I also went and added all three projects to my dashboard (which also adds a deployment key). So in all three cases if I navigate to the BitBucket project settings, you'd see: 

![image](https://cloud.githubusercontent.com/assets/980757/18186345/3ed4c412-709a-11e6-8d38-5912f30caded.png)

**Comment by a-murphy** [comment]
It sounds like the wrong key is being used for npm install, but the subscription key is the default.  Could you try adding `ssh -vT git@bitbucket.org` to your shippable.yml file as suggested for a similar problem in issue #2881 to check which key is being used?  The subscription key is named `00_sub`.

**Comment by ksnyde** [comment]
Ok, adding this was very helpful and pointed me to the fact that I had missed a third dependency (the first two _were_ ok).

**Comment by manishas** [comment]
closing since this is resolved.
