### ISSUE TITLE
Can't add syncRepo resource

### ISSUE THREAD

**Issue by navymaker** [Shippable/support#2924]
When I'm adding syncRepo resource through UI, I get following error
<img width="779" alt="error" src="https://cloud.githubusercontent.com/assets/3058188/18069492/2b16e280-6e50-11e6-9e52-6010646db69b.png">
syncRepo resource appears in "Resources" tab, but resources didn't update from shippable.resources.yml.

**Comment by manishas** [comment]
@navymaker we took a look at this and looks like your GitHub integration is currently only applicable to project openbridge/ob_sync can you remove that restriction from the integration and try running the sync jobs again?

We can also do a hangout anytime from 9:30am-5pm PST tomorrow and help with this.

**Comment by navymaker** [comment]
@manishas I added "All Projects" permission, still getting errors, but with 500 code.

**Comment by navymaker** [comment]
@manishas we solved this issue by adding integration from another account, I think there is some issues with permissions with my account.
