### ISSUE TITLE
Frontend failing again?

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#2925]
I got the red UI error boxes showing again on my dashboard so tried logging out then in. Now I can't log in:

![image](https://cloud.githubusercontent.com/assets/6311784/18101367/c6301806-6eee-11e6-8860-9a9c0cef9b64.png)

@manishas this seems like a similar frontend problem as you solved last week

**Comment by rarkins** [comment]
it reminded me of http://status.shippable.com/incidents/6lg60jm8gpqb

**Comment by ramasamymohan** [comment]
+1

**Comment by trriplejay** [comment]
we're looking into this now.

**Comment by jimi-c** [comment]
I'm seeing the same type of popup errors as the issue last week:
<pre>
(Id: 2000) No access or object not found for query: [object Object]
warn: common|validateProjs|callerId:573fa8a22a8192902e20e993|_getProjectPermissions</pre>

**Comment by rarkins** [comment]
I checked from another computer that I'm still logged in from. It's not seeing any UI errors so far, however it IS seeing all builds fail, e.g.

![image](https://cloud.githubusercontent.com/assets/6311784/18101815/71f083a0-6ef0-11e6-8c83-786bb5095291.png)

I've never seen more than one "provision job node" in a row before, even when they are failing.

**Comment by rarkins** [comment]
Builds are piling up.

**Comment by rarkins** [comment]
Attempting a manual rebuild with the "Build" buttons doesn't work - just gets permanent spinning circle:
![image](https://cloud.githubusercontent.com/assets/6311784/18102101/b109b060-6ef1-11e6-8430-8946ffe2c6c5.png)

**Comment by rarkins** [comment]
@trriplejay when will you update status.shippable.com and escalate the labels here? Catastrophic outages for a business-critical service like this cannot be considered "business as usual" even if they're happening weekly now.

**Comment by trriplejay** [comment]
@rarkins it looks to me like your builds are running now. the manual builds you triggered are waiting for available minions. The errors caused a delay in the start of builds for some customers. 

We apologize for the inconvenience. We're always working to improve our response time. We'd definitely like to alert users of these problems as soon as possible, and we're investigating better ways to do that.

**Comment by rarkins** [comment]
@trriplejay the best situation would be if you alerted yourselves first, actually. i.e. I would feel slightly better about your regular outages if at least you detected them before or at the same time I do, rather than the 10-30 minute delay it takes for customers to realise "this is definitely another outage - I better raise an issue" and then the delay for you to notice the issue. Far better would be if you had internal real-time alerts, as when such outages occur they surely cause your stats to either drop to the floor or go through the roof - depending on what metric you're counting. i.e. you should be able to detect catastrophic problems within a minute or two.

**Comment by thelamer** [comment]
@rarkins +1 here man, and I still think you are experiencing an outage. I need to babysit builds right now because they are not ending properly after parsing the coverage reports.

**Comment by manishas** [comment]
@rarkins yes, you are right. These particular outages were a bit tricky since basic checks like pingdom etc always passed. We have improved our service health check logic to alert us if this happens again.
