### ISSUE TITLE
Shippable.com website issues

### ISSUE THREAD

**Issue by TomK** [Shippable/support#2926]
Hi, just letting you know of a discrepancy on your pricing page (https://app.shippable.com/pricing.html). Under "Growing Teams" the description says "100 builds a month for private projects", but in the FAQ it says "With any paid plan, you get unlimited builds for even provate projects."
I'm assuming that the FAQ is correct in that private builds are unlimited for paid plans.
Also, please note the spelling mistake in the FAQ "provate" should be "private".

I'd also like to make you aware that your contact forms redirect to a 404.

I hope this helps.

**Comment by manishas** [comment]
@TomK thanks a ton for pointing this out. We have addressed the discrepancy - you're right paid plans get unlimited builds for all projects.
