### ISSUE TITLE
I don't know how to stop a pipeline

### ISSUE THREAD

**Issue by sebcreme** [Shippable/support#2928]
### Description of your issue:
I have a pipeline with two environments and i want to remove one of them.
I've tried to reduce the replica number to 0.
But i can't manage to find a way to "stop" a pipeline.

When try to disconnect, i have the following error : 

```(Id: 4005) Cannot delete active cellConfig with :id 57bee208ab66290e00d06e35
verbose: cellConfigs|deleteById|callerId:57446e9f96bad11100e79c0e|cellConfigId:57bee208ab66290e00d06e35|_getCellConfig```

**Comment by a-murphy** [comment]
If you scale the number of replicas to 0 on the status tab (not the configuration tab), the deployment should be updated to "stopped" and allow you to delete the environment.  Scaling the number of replicas on the configuration tab is considered a deployment and so the status will be "success."
