### ISSUE TITLE
Unable to access dashboard

### ISSUE THREAD

**Issue by LiranLast** [Shippable/support#2929]
When accessing my dashboard/project I'm getting the following error and the information does not load.

I have tried clearing cookies and re-doing the login with no success.

(Id: 2000) No access or object not found for query: [object Object]
warn: common|validateProjs|callerId:57b99f9b1419e20f001a55cb|_getProjectPermissions

**Comment by robertboloc** [comment]
Same here. 

If it helps debugging, Bitbucket asked me to migrate my account to Atlassian today so it might be that the "Authenticate with Bitbucket" functionality is now broken?

Thanks,
Rob

**Comment by elkdanger** [comment]
I get the same thing with my Github.com integration. At the moment I can't even log in, I get:

`getSystemIntegrationById failed for :id xxx`

.. and then I'm asked to log out or return to the app, neither of which let me proceed to the dashboard.

**Comment by pvangeel** [comment]
Same problem here... can't seem to get into the dashboard anymore

**Comment by jplimpens** [comment]
+1 
Please fix quickly. I was about to record a demo (luckily not a live one)

**Comment by elkdanger** [comment]
Appears to be working for me now.

**Comment by robertboloc** [comment]
It works for me too now.

**Comment by LiranLast** [comment]
Seems ok

**Comment by avinci** [comment]
This should  be resolved. Looking at what the hiccup was...

**Comment by manishas** [comment]
We are investigating this issue more deeply and adding some checks that will also help detect immediately. Please let us know if you see this again.
