### ISSUE TITLE
git_sync -- fatal: Could not parse object

### ISSUE THREAD

**Issue by Zhomart** [Shippable/support#2932]
I've created a tag using `git tag 0.0.2` and pushed tag to the bitbucket `git push origin 0.0.2`.

Build is failing on step `git_sync` with `fatal: Could not parse object`.

Please help me.

Build: https://app.shippable.com/runs/57c7f133236da20f00dc831f/1/console

```
>>> git checkout -f 0.0.2 -- 0s  
Note: checking out '0.0.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 3bfec41... update

>>>  git reset --hard 4b07184004ef9aa4133dc73070ca1699d424a039  
fatal: Could not parse object '4b07184004ef9aa4133dc73070ca1699d424a039'.
```

If I locally do these commands, everything is ok:
```
$ git reset --hard 4b07184004ef9aa4133dc73070ca1699d424a039
HEAD is now at 4b07184 shippable: script chaged
```

**Comment by rageshkrishna** [comment]
We've seen this happening before on BitBucket projects. If you try rebuilding that commit just a little later it will work. It's almost as if BitBucket was serving a cached copy of the repository when we try and clone it in a short window after the commit. Unfortunately, this isn't really reproducible all the time and we have only ever seen it happen with BitBucket repositories.

**Comment by Zhomart** [comment]
I did rebuild after 7 hours, the same problem.

**Comment by Zhomart** [comment]
I've removed cache. It went ok for now. I'll let you know if this issue comes up again.

**Comment by Zhomart** [comment]
I made this problem by myself.

Problem was adding `.git` to `cache_dir_list:`. I've seen it in documentation somewhere and thought it was a good idea :).

```yaml
build:
  ci:
    - pip install --upgrade pip
    - pip install -r requirements/requirements.txt
    - mkdir -p shippable/testresults && mkdir -p shippable/codecoverage
    - nosetests --with-xunit --xunit-file=shippable/testresults/nosetests.xml
  cache: true
  cache_dir_list:
    # - $SHIPPABLE_BUILD_DIR/.git  ## remove this line
    - /root/venv
```

**Comment by shailendra-ahir** [comment]
I am facing this problem at bitbucket repository as well as github repository

**Comment by trriplejay** [comment]
Are you caching your `.git` directory? If not, could you open a new support issue with a link to one of your failing builds so that we can investigate?
