### ISSUE TITLE
Bitbucket: Builds not triggered after merge; and push multiple branches

### ISSUE THREAD

**Issue by Zhomart** [Shippable/support#2933]
Similar closed issues: #398, #2897

Dan Tao confirms that Bitbucket already released new webhook API in this issue https://bitbucket.org/site/master/issues/7775/post-service-does-not-provide-useful

There is the news in Bitbucket's blog https://blog.bitbucket.org/2015/06/24/the-new-bitbucket-webhooks/

Other useful links https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html
and https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/hooks#get

**Comment by ambarish2012** [comment]
@Zhomart we have fixed this bug. Please let me know if this issue can be closed.

**Comment by Zhomart** [comment]
Thanks for fix. Currently I don't use shippable. You can close the issue if it's fixed.
