### ISSUE TITLE
Machine Image - Unstable: Stucks on provision job node

### ISSUE THREAD

**Issue by Zhomart** [Shippable/support#2936]
I've found similar issues here #2906 and #2873. It looks like it worked for them somehow.

I'm facing the same issue here, tried cancelling build and rebuilding several times. It's not passing provisioning node.

**Comment by Zhomart** [comment]
In the end I got time out.

**Comment by manishas** [comment]
@ric03uec we need to look into this.

**Comment by Zhomart** [comment]
https://app.shippable.com/runs/57ca0afe0043620f009ba6d3/1/console

**Comment by manishas** [comment]
@Zhomart can you try again? We have identified the issue and the machine image has been updated.

**Comment by Zhomart** [comment]
@manishas It looks like it went through. Thank you! 🎉 
I hope this is one time issue.
