### ISSUE TITLE
Builds stuck waiting with all workers free

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#2937]
Builds are stuck waiting with all workers free:

https://app.shippable.com/runs/57ca7a40eab2150f003d10c7/summary

**Comment by rageshkrishna** [comment]
@mattclay I'm looking in to this. I'll have an update for you soon.

**Comment by rageshkrishna** [comment]
This should be resolved now. There was an issue with the job trigger service that was causing it to trigger jobs slower than usual. All your jobs should be running normally now. Please let me know if you still see any problems.

**Comment by mattclay** [comment]
It's working now.
