### ISSUE TITLE
Login redirects me to bitbucket, when I want to sign in with Github

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#2940]
When we first signed up for Shippable, I attached our BitBucket account and repositories, but limitations on the integration (at the time) with BitBucket, combined with a sudden change in GitHub's pricing model, made switching to GitHub make sense.

We moved all of our repositories over, linked them to Shippable, added my GitHub account to shippable, and disconnected my BitBucket repositories. 

Unfortunately, Shippable keeps redirecting me to Bitbucket when I need to sign in, which is frustrating, especially since we're enforcing 2-factor auth on our GitHub accounts, but this less secure auth option remains.

Is this a bug, or just a configuration item on my account that can be changed?

**Comment by manishas** [comment]
@ryan-kimber i am trying to understand your scenario... how does shippable keep redirecting you to Bitbucket? When you click on the Start button on our landing page, you should see options to sign in with github and sign in with bitbucket. If you click on the GitHub button, you'll be signed in with Github. What am i missing?

**Comment by manishas** [comment]
@ryan-kimber is this still an issue?

**Comment by ryan-kimber** [comment]
This seems to have stopped in the past few days. Previously, I wasn't being
given a choice between BitBucket and GitHub - pointing my browser at
shippable.com was always taking me to BitBucket. If I cleared my cache, or
used incognito mode, I could get to the BitBucket/GitHub screen, but once I
signed in, it would go back to always trying to get me to sign in through
BitBucket.

This wasn't a one-time thing: it was consistent over several months and on
both my Mac desktop and MacBook.

Seems fine now though.

**Comment by ryan-kimber** [comment]
Just did some more testing and I'm no longer having this issue. Closing.
