### ISSUE TITLE
Recently added project not showing up in the /projects API

### ISSUE THREAD

**Issue by LuisMuniz** [Shippable/support#2941]
Two recently added projects not showing up in the /projects API list.
I have already synced both projects.

These are the two failures.

https://app.shippable.com/runs/57ce8de9a100830e005f6370/1/console
https://app.shippable.com/runs/57ce91a5d9cbdb0e000f7b06/1/console

Both in script
scripts/shipp/cancel_if_needed.py

**Comment by kanthchandra** [comment]
Hi @LuisMuniz , can you please sync the account from which the token was created and try?

**Comment by LuisMuniz** [comment]
Hi,

The synchronisation button seems to be disabled:

[cid:3BC65FF3-6382-46AD-92F9-F759F755106B]

The spinner never stops spinning, the betony server gets enabled.
I have logged out / logged in 5 minutes ago.


From: Chandrakanth
Reply-To: Shippable/support
Date: Tuesday 6 September 2016 at 15:10
To: Shippable/support
Cc: Luis Muniz, Mention
Subject: Re: [Shippable/support] Recently added project not showing up in the /projects API (#2941)


Hi @LuisMuniz<https://github.com/LuisMuniz> , can you please sync the account from which the token was created and try?

**Comment by LuisMuniz** [comment]
Same thing for History.

[cid:9F21249F-D56D-4B9D-B5C8-6C7AADC5DBD0]

The dashboard does show up.


From: Luis Muniz Fernandez
Date: Tuesday 6 September 2016 at 16:26
To: Shippable/support, Shippable/support
Cc: Luis Muniz
Subject: Re: [Shippable/support] Recently added project not showing up in the /projects API (#2941)

Hi,

The synchronisation button seems to be disabled:

[cid:3BC65FF3-6382-46AD-92F9-F759F755106B]

The spinner never stops spinning, the betony server gets enabled.
I have logged out / logged in 5 minutes ago.


From: Chandrakanth
Reply-To: Shippable/support
Date: Tuesday 6 September 2016 at 15:10
To: Shippable/support
Cc: Luis Muniz, Mention
Subject: Re: [Shippable/support] Recently added project not showing up in the /projects API (#2941)


Hi @LuisMuniz<https://github.com/LuisMuniz> , can you please sync the account from which the token was created and try?

**Comment by kanthchandra** [comment]
@LuisMuniz if the spinner in the account settings was still running means the sync was happening the background. Please let me know the accountId if you are still running into this!

**Comment by LuisMuniz** [comment]
I have synced the account, re-encrypted the API key used in shippable.yml. Still have the same issue.

**Comment by kanthchandra** [comment]
Can you please provide me with the following details
1. the accountId from which the token was generated
2. the name of the token that you created (visible in the account settings )
3. The full name of the projects that you are trying to get using the above token or the projectIds

**Comment by LuisMuniz** [comment]
ShippableId:
55cdad6325413a0b0072f844

Token name:
optipost

Project Ids:
56cc3e671895ca44747748cc
57d01ba6210fe60f003257af

**Comment by kanthchandra** [comment]
@LuisMuniz can you re-encrypt your token with the name API_ACCESS_TOKEN=PUT_YOUR_TOKEN_HERE and use $API_ACCESS_TOKEN in your scripts? I suspect there is a conflict in the naming of the token because we too export a variable called SHIPPABLE_API_TOKEN and you are also encrypting the token with SHIPPABLE_API_TOKEN=token.

Also make sure that you are send the authorization header in this format `apiToken YOUR_TOKEN` while making the request.

**Comment by LuisMuniz** [comment]
Before going on a red herring chase, it is worth pointing out that the exact same scripts work with 15+ other similar projects. Do you still insist on doing this?

From: Chandrakanth
Reply-To: Shippable/support
Date: Wednesday 7 September 2016 at 16:36
To: Shippable/support
Cc: Luis Muniz, Mention
Subject: Re: [Shippable/support] Recently added project not showing up in the /projects API (#2941)


@LuisMuniz<https://github.com/LuisMuniz> can you re-encrypt your token with the name API_ACCESS_TOKEN=PUT_YOUR_TOKEN_HERE and use $API_ACCESS_TOKEN in your scripts? I suspect there is a conflict in the naming of the token because we too export a variable called SHIPPABLE_API_TOKEN and you are also encrypting the token with SHIPPABLE_API_TOKEN=token.

Also make sure that you are send the authorization header in this format apiToken YOUR_TOKEN while making the request.

**Comment by kanthchandra** [comment]
@LuisMuniz can we do a small test to confirm the hypothesis that we have arrived and then go ahead make the fixes in the code?

1. Use the token with name `optipost` and make a call to get all the projects.
 `curl -i -H "Authorization: apiToken PUT_YOUR_TOKEN_HERE" -H "Content-Type: application/json" https://api.shippable.com/projects` 
2. Check if the project in question is returned.
3. If you received the project in the first call it means that `optipost` token has access to that particular project and something in the script is causing the failures and we may need to investigate the script.

I hope this helps.

**Comment by LuisMuniz** [comment]
Hi,

Indeed, the projects are returned in the json response.
I am adding the engineer responsible for the script in the discussion.

Regards,

Luis

From: Chandrakanth
Reply-To: Shippable/support
Date: Thursday 8 September 2016 at 10:18
To: Shippable/support
Cc: Luis Muniz, Mention
Subject: Re: [Shippable/support] Recently added project not showing up in the /projects API (#2941)

curl -i -H "Authorization: apiToken PUT_YOUR_TOKEN_HERE" -H "Content-Type: application/json" https://api.shippable.com/projects

**Comment by LuisMuniz** [comment]
Dear Chandrakanth,

It can happen that a project can’t be found with the /projects endpoint of the API hours after his creation. We tried both to syncing the project and the account, without success. Is there another button to sync the projects, ensuring that newly created projects show up in /projects?

We use in our builds a script that use the /projects to get a list of the existing projects, if the /project endpoint is not up to date, it can cause our script to fail…

Best regards,

Hélain Schoonjans
Junior Developer | B2Boost
Chaussée de Waterloo, 1453, 1180 Brussels , Belgium
T : +32 (0)2.629.60.00 | F: +32(0)2.629.60.01 | Mobile : +32 (0)48.419.12.59
Helain.Schoonjans@b2boost.com<mailto:Helain.Schoonjans@b2boost.com> | www.b2boost.com<http://www.b2boost.com/>

Please consider the environment before printing.

**Comment by kanthchandra** [comment]
Closing this issue since it's resolved. Let us know if you are still running into this. Thanks.
