### ISSUE TITLE
BYON uses an outdated version of docker that is not supported by docker-compose

### ISSUE THREAD

**Issue by tomazk** [Shippable/support#2947]
### Description of your issue:

BYON uses an outdated version of docker that is not supported by docker-compose

Error print by docker-compsoe
"The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.10.0 or greater."

If I upgrade docker manually on my own node, the build just stalls at " Running job on customer's build node for subscriptionId: "

**Comment by manishas** [comment]
This is fixed now. BYON should be using docker version 1.11.1 which does support docker compose.
