### ISSUE TITLE
Aws Integration - Fatal Error Python.h: No Such file or directory

### ISSUE THREAD

**Issue by carlton355** [Shippable/support#2949]
Running a basic php yml file with aws integration bombs out with this:

"Installing eb script to /usr/local/bin
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    checking if libyaml is linkable
    x86_64-linux-gnu-gcc -pthread build/temp.linux-x86_64-2.7/check_libyaml.o -lyaml -o build/temp.linux-x86_64-2.7/check_libyaml
    building '_yaml' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c ext/_yaml.c -o build/temp.linux-x86_64-2.7/ext/_yaml.o
    ext/_yaml.c:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h""

- Link to the build failure
https://app.shippable.com/runs/57d44952e4e8500e0074a73a/1/console

Any help appreciated.

**Comment by manishas** [comment]
@carlton355 the link doesn't work for some reason. Do you mind sharing a link again? WHat username do you log in to shippable with?

**Comment by manishas** [comment]
Closing this issue. @carlton355 please share a build link and we'll be happy to take a look.
