### ISSUE TITLE
ECR Get-Login ThrottlingException

### ISSUE THREAD

**Issue by Kenny-House** [Shippable/support#2950]
We're seeing relatively frequent

`An error occurred (ThrottlingException) when calling the GetAuthorizationToken operation: Rate exceeded
ECR get-login failed`

 in our builds and I was curious if anyone else has experienced these or if there's a work-around.

Our builds are fairly infrequent, and certainly below the limit for the ecr get-login limit of 1 TPS with bursts up to 50 TPS as documented at: http://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors.html#error-429-too-many-requests

Manually re-triggering the builds runs without issue, but it's a bit of an annoyance.

**Comment by manishas** [comment]
@Kenny-House can you share a link to your build?

**Comment by Kenny-House** [comment]
Hi @manishas, we saw this issue on several builds. I'm happy to link you to a particular one, just let me know the easiest way to do so (not sure if you prefer application name and build number, or uuid?).

On the `ecr_login` step in our build, the following output was reported, and the build would fail:

```
An error occurred (ThrottlingException) when calling the GetAuthorizationToken operation: Rate exceeded
ECR get-login failed


/root/4e76736a-f427-44f2-8dcf-98ea443995e2.sh: eval: line 59: syntax error near unexpected token `('
/root/4e76736a-f427-44f2-8dcf-98ea443995e2.sh: eval: line 59: `An error occurred (ThrottlingException) when calling the GetAuthorizationToken operation: Rate exceeded'

An error occurred (ThrottlingException) when calling the GetAuthorizationToken operation: Rate exceeded
```

We've been debugging a related problem within our development and production infrastructure with the EC2 Container Service itself for the past couple of weeks, so my apologies for the delayed reply.

It appears some recent changes to the determination of when to throttle the `GetAuthorizationToken ` endpoint for ECR has resulted in several ECR users experiencing elevated rate limits on the `GetAuthorizationToken ` request. The ECS-agent team recently had to add ECR token cacheing to help counteract this issue: https://github.com/aws/amazon-ecs-agent/issues/498

When I contacted AWS support, they highly recommended implementing retry logic in any application that depends on the `GetAuthorizationToken` request (along with exponential backoff).

My request to shippable would be handling ThrottlingExceptions from AWS with a retry on the `GetAuthorizationToken ` request instead of the build simply failing.

**Comment by kiranmeduri** [comment]
This issue should be fixed by #523 when using agent v1.13.0. Are you still seeing this issue on your end?

**Comment by Kenny-House** [comment]
Hi @kiranmeduri, I don't think Shippable is running within an ECS environment (although I might be wrong on that). The issue with the ECS agent was referenced above as an example of other AWS ECR integrated projects that have had to work with decreased limits on getting authorization tokens.

I haven't seen this issue in some time though, and I suspect the ECR throttle limits have been increased somewhat.

**Comment by manishas** [comment]
closing since this is no longer a problem.
