### ISSUE TITLE
Documentation: How to capture code coverage and test result output from tests in Docker

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#2951]
Hi guys! 'love your product.

I'm using CI to build a docker image, then running tests in side the container for that image.

I struggled mightily trying to mount a host volume so that my test and coverage results would be available to shippable. 

I think I've figured out that when we're running inside shippable, we're in a docker container, so we actually can't mount a host folder, even though no errors are provided by either shippable or docker.

To work around this, I'm 'cat'-ing our test results and coverage from docker to dump them into the local ./shippable folder. 

Documentation on how to mount volumes, or how to capture your test results and code coverage when running your tests against a docker image probably would have saved me the better part of a day. I'm sure it will benefit others.

**Comment by ryan-kimber** [comment]
Here's the ugly hack I'm using for now:

```
build:
  ci:
    - echo $FH_NPM_TOKEN > ~/.npmrc
    - echo scope=formhero >> ~/.npmrc
    - date > ./shippable/timestamp.txt
    - docker build -t fh-library-service:$BRANCH.$BUILD_NUMBER .
    - docker run -P -h localhost.formhero.io fh-library-service:$BRANCH.$BUILD_NUMBER npm run test-shippable
    - docker run -P -h localhost.formhero.io fh-library-service:$BRANCH.$BUILD_NUMBER npm run test-shippable-coverage-conversion
    - docker run -P -h localhost.formhero.io fh-library-service:$BRANCH.$BUILD_NUMBER cat ./shippable/testresults/report.xml > ./shippable/testresults/report.xml
    - docker run -P -h localhost.formhero.io fh-library-service:$BRANCH.$BUILD_NUMBER cat ./shippable/codecoverage/cobertura-coverage.xml > ./shippable/codecoverage/cobertura-coverage.xml
```

**Comment by avinci** [comment]
here is a solution to mount stuff into docker containers from host. 
https://github.com/Shippable/support/issues/3402

Let me know if this helps.
