### ISSUE TITLE
Your cassandra information is out of date

### ISSUE THREAD

**Issue by mattiasw2** [Shippable/support#2952]
At http://docsshippable.readthedocs.io/en/latest/samples/cassandra.html

you say you use port 9160. Nope, you use the standard. A better sample would be

```
cqlsh 127.0.0.1 -f schema.txt
```

instead of

```
 cassandra-cli -host localhost -port 9160 -f schema.txt
```

**Comment by manishas** [comment]
@mattiasw2 I need to track down these old docs and shut them down.

Our current docs are at http://docs.shippable.com/ I will update them tomorrow with more information about cassandra.

**Comment by avinci** [comment]
@manishas is this complete?

**Comment by avinci** [comment]
we do not support cassandra anymore. so closing this.
