### ISSUE TITLE
Pipelines V2: Allow custom namespaces

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#2956]
The dynamic namespaces make sense, but are quite cumbersome when you are dealing with multiple deployment configurations. 

It would be great if there was a option to provide the namespace for each deployment. This would allow us to use the default namespace for our dev deployments, while naming our other deployments appropriately (sandbox, production-blue, production-green, etc).

**Comment by manishas** [comment]
@ryan-kimber this has been implemented and deployed. Docs are here: http://docs.shippable.com/pipelines/resources/cluster/
