### ISSUE TITLE
All builds are stuck in the queue

### ISSUE THREAD

**Issue by mhzajac** [Shippable/support#2958]
We currently have several builds that all have the status "WAITING" and will not start running (across multiple repos). The last successful build finished about 2 hours ago. Our minion usage is listed as "0 of 8".

Here are just a few of the builds that won't start, and the pile keeps growing:

https://app.shippable.com/runs/57d6ce75cc95d80f000fe8fc/summary
https://app.shippable.com/runs/57d6ce94e584090f002f0da2/summary
https://app.shippable.com/runs/57d6cd57cc95d80f000fe68e/summary
https://app.shippable.com/runs/57d6cc5fcc95d80f000fe62d/summary
https://app.shippable.com/runs/57d6cc1a591bec0e00e2c9e0/summary

**Comment by manishas** [comment]
we're looking into this.

**Comment by manishas** [comment]
this should have been resolved. can you please confirm?

**Comment by mhzajac** [comment]
Yes, everything seems to be back to normal.
