### ISSUE TITLE
private fork spams upstream maintainers because of .travis.yml

### ISSUE THREAD

**Issue by cjerdonek** [Shippable/support#2959]
I have a fork of another project in a private repo. The upstream project has `notifications.email` configured in `.travis.yml`. The problem is that whenever I push the upstream commits to my personal repo, Shippable reads and acts on the `.travis.yml` file and sends unwanted e-mails to the upstream owners on build failures, etc.

I'd like to keep copies of the upstream branches in my fork, but I'm not sure what to do to prevent Shippable from sending those unwanted e-mails. Thanks.

**Comment by cjerdonek** [comment]
I'm not sure if you've had complaints about this from other users or if you've already given thought to this.

One idea is to have a configurable "whitelist" of e-mail addresses in the UI for each project. A whitelist would let users be sure they aren't unknowingly spamming other people.

**Comment by avinci** [comment]
I am not sure what the right solution for this is at all. The bigger question is whether spambots are using this and then spam those email addresses. 

I will give it some thought and let you know

**Comment by avinci** [comment]
We have added integrations that avoids putting email addresses in to your YML. this should avoid folks forking and spamming the owners. 

But we cannot do anything with travis.yml as we don't manage that system. You might want to remove that from your repo if you use shippable.

**Comment by cjerdonek** [comment]
> But we cannot do anything with travis.yml as we don't manage that system. You might want to remove that from your repo if you use shippable.

The problem is that it's the _upstream_ project (i.e. other people I don't know) that decide whether .travis.yml is in the project or not. So what you're suggesting isn't possible. If I fork that project and want to be able to sanely manage upstream changes, the file will be there.

It sounds like you're saying the only solution is not to use Shippable for forked Travis projects, but to to keep using Travis.
