### ISSUE TITLE
Build Stuck: Running job on customer's build

### ISSUE THREAD

**Issue by deanmraz** [Shippable/support#2960]
See here: https://app.shippable.com/runs/57d737f9c202180f00f1b3b5/1/console

Its stuck and not continuing the build process

**Comment by trriplejay** [comment]
Has this problem happened to you before? the symptoms are looking a bit like https://github.com/Shippable/support/issues/2857

What are the specs of your build nodes? Our standard nodes typically have 2 cores, 3.75 GB RAM each. Occasionally we find that customers with single core can result in a stuck shippable agent, while too little RAM can result in the agent (or the running build) getting killed by the kernel.

You might want to try the 'reset' button on the subscription->settings->nodes tab.  That should re-initialize your hosts and reconnect them to to shippable.

If you reset, you will need to cancel and rerun your currently processing jobs to get them to be picked up again.

Let us know if you have any questions!

**Comment by deanmraz** [comment]
@trriplejay  We haven't had problems in the past. I'll try the reset and get back to you. Thanks!

**Comment by deanmraz** [comment]
@trriplejay I decided to destroy the old nodes and create new ones since the machines were 3 months old. Should we be doing this regularly? If so, how often?

**Comment by trriplejay** [comment]
typically a `reset` should be enough to refresh your node with the latest agent, but I wouldn't say that you have to do it regularly.  Really it would only be necessary if we made some incompatible changes to the platform, but typically in that case we would notify users ahead of time and/or perform the node reset ourselves (with some warning ahead of time).

**Comment by manishas** [comment]
closing this issue since it's resolved.
