### ISSUE TITLE
postgres geos support

### ISSUE THREAD

**Issue by oppianmatt** [Shippable/support#2961]
Tried to use the postgres in shippable but it's lacking geos support. Would be nice to have it already configured

GEOS is required and has not been detected. Are you sure it is installed? See also https://docs.djangoproject.com/en/1.8/ref/contrib/gis/install/geolibs/

**Comment by avinci** [comment]
@rageshkrishna can we get this added too?

**Comment by rageshkrishna** [comment]
Yes, we're adding PostGIS 2.3.2 on the new images. I believe that comes with GEOS 3.6.1.

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.
