### ISSUE TITLE
automatic deployment not a freemium

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#2962]
In old pipeline i had setup that always pushed latest to dev cluster. I am unable to replicate that now on new pipelines. Only paid accounts are able to generate a token that is needed for that setup.

On main page you claim freemium model so when is that restriction on api token being lifted or when do you provide a new way of doing continuous deployment to dev environments?

**Comment by manishas** [comment]
@KarolAdamiec this will be addressed in the next couple of days as we will allow free users to create limited scope tokens that will let you trigger your pipelines.

**Comment by spsiddarthan** [comment]
Hi @KarolAdamiec, We have addressed this issue. Free users can create a token now (the token has limited privileges) that can be used to trigger your pipeline. You can go to your account settings page to create an apiToken.  

Please let us know know if you have any questions!

**Comment by KarolAdamiec** [comment]
that worked. Thank you.

I had issue with stopping previous service/task on AWS. Had to go in and kill it manually then it finished deployment correctly. Will keep an eye on that and if persist report in separate issue.
