### ISSUE TITLE
SPOG: Last Run timestamps for all items

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#2964]
It would be very helpful to be able to see when each component on the SPOG was last run. Relative time (32 minutes ago, for example) would be most helpful, but a timestamp in the users local timezone would work too.

Unfortunately, the version numbers don't provide much information, unless you think to make a note of them before you make a commit.

**Comment by manishas** [comment]
we should show when each resource was last updated and each job was last run.

**Comment by ryan-kimber** [comment]
Any updates on this? We're doing a deployment now that's required a number of config file changes to get right and this would really help us to see what items in the SPOG are synced to the last commit.

**Comment by rageshkrishna** [comment]
This information is now available. Clicking on a resource or job in the SPOG will now show you the last update/run time.

**Comment by ryan-kimber** [comment]
Awesome! Thanks!
