### ISSUE TITLE
Relation between CI and CD

### ISSUE THREAD

**Issue by thibaultdelor** [Shippable/support#2965]
Hi,
I am a bit confused on how to set up a relation between CI and CD (pipelines) and couldn't find the answer in the docs.
I have two different repos with a shippable.yml each. At the moment both works, when I commit on one of those repos, it executes a job.
The second repo actually depends on the first repo execution. So now I want to set up a simple a pipeline which run those two jobs in sequence whenever one of those repos changes.

I know I can do it use using only CI features with triggers and hooks, but I would rather doing it in a pipeline because it is meant to grow (I will have much more than 2 tasks depending on each other).

PS: I guess my use is pretty common, the first repo is a base docker image, the second project uses this base image.

**Comment by manishas** [comment]
@thibaultdelor this is a great question. In a nutshell, CI is about running your unit tests for every commit or pull request and triggering a deploy job, if you write the right scripts in your shippable.yml. CI does not address the lifecycle of your commit beyond that first step. You can't easily use CI to do release automation or management unless you want to spend the time to write thousands of lines of code. 

That's where Pipelines come in. Using pipelines, you can string together a sequence of jobs that do different things like create a service manifest, deploy to an environment, and even define releases. This gives you the workflow through different environments like dev, test, beta, and finally production. 

A good example is the simple sample use case as described at http://docs.shippable.com/pipelines/overview/#sample-use-case

As shown, CI is just the first step towards CD.

Let me know if this makes sense.

**Comment by thibaultdelor** [comment]
That totally make sense in theory. I am actually already familiar with the concept of CI and CD and have several years of years experiment it.
I have also understand how pipelines are working in shippable.
Let me reformulate my question:
How to make use of my already existing projects containing a shippable.yml file inside a pipeline?

**Comment by manishas** [comment]
It usually works like this: Your already existing CI project runs tests on your code and creates a docker image and pushes it to a registry. You include some lines in your shippable.yml that will trigger the rest of your pipeline every time a new image is pushed. 

A great way to understand how CI connects to Pipelines is to look at the sample pipeline tutorial: http://docs.shippable.com/tutorials/pipelines/samplePipeline/

**Comment by manishas** [comment]
![image](https://cloud.githubusercontent.com/assets/2983749/18500906/16bad14a-7a01-11e6-81b3-172ab476cf6f.png)

**Comment by thibaultdelor** [comment]
Alright! That's the answer I was looking for. Too bad it requires a paid account ^^ ( to create the api token used in the trigger)

**Comment by manishas** [comment]
We're making a change today or tomorrow that will let you create a limited token with a free account. This token can be used to trigger the pipeline.

**Comment by spsiddarthan** [comment]
@thibaultdelor,  Free accounts can create tokens now that can be used to trigger a pipeline. Please note that this token comes with limited privileges. You can create the token from your account settings page. 

![selection_304](https://cloud.githubusercontent.com/assets/6594561/18546528/0c3b9a0e-7b5c-11e6-9efa-75aa0a130501.png)

Please let us know if you face any issues!
