### ISSUE TITLE
Unable to enable project

### ISSUE THREAD

**Issue by skamalapur** [Shippable/support#2969]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

hi 
I am trying to enable a project. But could not see a subscription drop down.  Anything i need to do?

Thanks
Shrini

**Comment by manishas** [comment]
The subscription dropdown is at the left of your top navigation bar. It's an icon with 3 horizontal lines. Let me know if you find it.

**Comment by skamalapur** [comment]
Hi,
Okay. Got it..

There in no help popping out when I roll over mouse as in the case of other
buttons.

Cool.thnx.
Shrini.

On Sep 16, 2016 8:35 PM, "Manisha" <notifications@github.com> wrote:
>
> The subscription dropdown is at the left of your top navigation bar. It's
an icon with 3 horizontal lines. Let me know if you find it.

**Comment by skamalapur** [comment]
Hi Manisha

I am evaluating Shippable to propose to one of our Oil and Gas customer.
Can someone from your team Bangalore help us to do a small project using
Shippable which can be demonstrated?

Thanks
Shrini

On Fri, Sep 16, 2016 at 9:31 PM, Shrinivas Kamalapur <
shrinivas.kamalapur@gmail.com> wrote:

> Hi,
> Okay. Got it..
>
> There in no help popping out when I roll over mouse as in the case of
> other buttons.
>
> Cool.thnx.
> Shrini.
>
> On Sep 16, 2016 8:35 PM, "Manisha" <notifications@github.com> wrote:
> >
> > The subscription dropdown is at the left of your top navigation bar.
> It's an icon with 3 horizontal lines. Let me know if you find it.
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
>



-- 
Thanks.
Shrinivas Kamalapur

Cell - 91 95350 77114

LOVE PEOPLE AND *USE THINGS* - NOT LOVE THINGS AND *USE PEOPLE*.

**Comment by manishas** [comment]
@skamalapur absolutely happy to. I'll follow up with you over email.

**Comment by skamalapur** [comment]
Hi, Sorry, did not get you.

**Comment by avinci** [comment]
@skamalapur @manishas will send you and email to co-ordinate this shortly.

**Comment by skamalapur** [comment]
Thanks Avi. I am in touch with Manisha and Tom.

**Comment by manishas** [comment]
closing this issue since we're following up over email.
