### ISSUE TITLE
Build badges not updated in GitHub README using Chrome

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#2970]
We suddenly see that build badges are not updated on our GitHub README when using the Chrome browser. Tried to upgrade to 53.0.2785.116 m but still the same. The build badges are getting updated using IE11.

Thank you very much in advance.

Kind Regards,
Jeppe

**Comment by stephanielingwood** [comment]
Hi Jeppe,

Thanks for the heads-up. We're looking into this and hope to have a fix in the next day or two.

**Comment by stephanielingwood** [comment]
Hi @jeppefrandsen,

This should be fixed now. Can you give it a try and let us know if you're still seeing the issue?

Thanks,
Stephanie

**Comment by jeppefrandsen** [comment]
Seems to work. Thanks.
