### ISSUE TITLE
Deployment failed with error : Provider not found for integration of type AWS_IAM

### ISSUE THREAD

**Issue by cratz** [Shippable/support#2973]
I created "ECS integration using Cross Account AWS IAM Roles" according to http://docs.shippable.com/integrations/containerServices/ecs/

And used this for an integration in "Subscription Settings", now I get the following error on deploy:

`Deployment failed with error : Provider not found for integration of type AWS_IAM`
Any ideas how to solve this?

**Comment by manishas** [comment]
assigning to @trriplejay to take a look.

**Comment by trriplejay** [comment]
Unfortunately AWS IAM type integrations are not yet supported for pipelines v2.  We're hoping to have this available in the next 2-3 weeks.  You can create a regular aws integration using a key and secret in the meantime as a workaround. 

Would that work for you, or is the IAM support critical for your scenario?

**Comment by manishas** [comment]
@cratz we have updated the docs at http://docs.shippable.com/integrations/containerServices/ecs/

**Comment by cratz** [comment]
@trriplejay  @manishas 
Thanks for this information. I think a regular aws integration will work as well if not I will get back to you.
Best

**Comment by cratz** [comment]
Regular aws integration is working properly. Thanks a lot.

**Comment by trriplejay** [comment]
AWS_IAM has been added as a valid deployment provider. closing.
