### ISSUE TITLE
Not the subscription owner / Out of private jobs

### ISSUE THREAD

**Issue by nathan-albrecht** [Shippable/support#2974]
The shippable subscription for our internal builds are no longer running due to the error: "This job was skipped because you have reached your private job limit for this month. Please upgrade your subscription to continue running jobs."

However, according to this blog post, we get unlimited private builds with only one minion:
http://blog.shippable.com/how-to-upgrade-your-ci-cd-subscription

This wouldn't be a problem if we could update the subscription level to be able to run unlimited builds, but I'm the one who set up the org on Shippable and I can't upgrade it. Is there a specific account for the org that needs to login to Shippable to be able to upgrade? I should mention that it's for a Bitbucket org and I'll give more details in a private conversation.

**Comment by manishas** [comment]
@nathan-albrecht we adjusted Shippable pricing with our latest release on Aug 25, 2016. 

All free subscriptions that were active as of the latest upgrade (I.e. Ran at least one build between July 25 2016 and August 24 2016 were grandfathered into the free plan. If your subscription was not active, it wasn't grandfathered. 

Can you point me to the subscription? You should be able to upgrade if you're an owner of the Organization in your source control system.

**Comment by nathan-albrecht** [comment]
I'm not the owner of the Org in Bitbucket. I'll follow up with the owner of our Org, thanks.

**Comment by manishas** [comment]
Closing this issue.
