### ISSUE TITLE
Attachments in Email Notifications

### ISSUE THREAD

**Issue by timtribers** [Shippable/support#2978]
Hi,

Just wondering if it is possible to specify a file(s) to be sent as an attachment on email notifications.  If not, would it be something easy to add?  It would very much help, for example, to be able to send certain test output or log files to people in the event of a failure.

Many thanks for a great service.

**Comment by avinci** [comment]
this is being planned for 5.3.3 release.

**Comment by timtribers** [comment]
That's absolutely awesome guys - many thx


*  REVOLUTIOИARYsystems*

*​m: *
*​ *​
+44 (0)7760 654640

*w:  *www.revolutionarysystems.co.uk
*a:  *Penvose House, Broad Lane, Upper Bucklebury, Reading, Berkshire, RG7
6QH

**Comment by avinci** [comment]
sorry, i was not very clear on what the implementation will be. We are adding artifacts that you can download from a build if you need to. In addition you can send variables with strings as part of the email in this version. File attachments will be done on next rev. sorry for not being very clear.

**Comment by nealeu** [comment]
Hope that you keep shippable fast and light.  Perhaps artifact download should be restricted to just a handful of recent builds unless on a paid plan :)

**Comment by manishas** [comment]
There are a bunch of improvements we've made in this area, so you can attach the following for email notifications:
- Console logs
- Failing commands
- Code coverage reports

Config details here:
http://docs.shippable.com/ci/email-notifications/#advanced-config
