### ISSUE TITLE
Format of link in dockerOptions is unclear

### ISSUE THREAD

**Issue by bholzer** [Shippable/support#2981]
I am trying to use the `link` functionality from the `dockerOptions`, but can't figure out a way to use it.

The documentation claims `"<container name>:<alias>"` is the right form, which follows the normal Docker use for `link`. As far as I can tell, however, Shippable only gives dynamic names to the containers. Is there something I'm missing on how to link containers, or define a container name?

I have a few manifests, each with image that runs a service. I am using a `dockerOptions` resource as an input to one of the manifests that should link it to the other services being deployed in the same job.

**Comment by trriplejay** [comment]
The service name is dynamic, but the container name within a task definition should always be the name of your image resource. Is that not the case? Pipelines v1 had dynamic names, but also didn't support linking.

**Comment by bholzer** [comment]
All of that is true, but it appears the values provided to the `dockerOptions` resource are passed directly to docker. 

As far as I can tell, the only way to link containers in Docker is by using the name specified when running the container. This name is generated by Shippable every time the container is spun up.

**Comment by bholzer** [comment]
Hold that thought, I may be seeing a different issue entirely, will report back.

**Comment by trriplejay** [comment]
One other suggestion. I think in order to link containers, they must be part of the same task definition on ecs. In order to achieve this in pipelines, your image resources have to all be IN resources to the same manifest job.  If they are in separate manifests, they will be deployed as separate task definitions, and then will not be able to link to each other.

**Comment by bholzer** [comment]
That appears to have been my problem. That leaves me with a different question though.

If I want three services deployed alongside each other, with one talking to the other two, I need to input them all to the same manifest. That means, though, that all 3 of those images need to use the same `dockerOptions` resource. Which is fine for the most part, except if you want to link containers.

If you want to link one of those services to another, but they use the same dockerOptions, you end up with a container that is trying to link to itself, causing the deploy to fail.

**Comment by trriplejay** [comment]
there's a modifier you can use in your deploy job, called `applyTo`.  You can use this to specify particular images to apply your options and/or params to.

There are some examples of it here: http://docs.shippable.com/pipelines/jobs/deploy/#multi-manifest-deploy

**Comment by trriplejay** [comment]
actually this applyTo command also works in the manifest job, if you'd prefer to add them there. it's up to you.

**Comment by bholzer** [comment]
Ah, excellent! Thank you

**Comment by manishas** [comment]
http://docs.shippable.com/pipelines/jobs/manifest/#multi-package-manifest-pattern

This is an example of how applyTo works for multi package manifest. The example shows it for `params ` resource but it works the same way for dockerOptions.

**Comment by manishas** [comment]
Closing this since it has been addressed.
