### ISSUE TITLE
taskRoleArn and volumes for AWS ECS task definition

### ISSUE THREAD

**Issue by feleil** [Shippable/support#2985]
### Description of your issue:

The attributes of an AWS ECS task definition can include:

```
{
    "taskDefinitionArn": "arn:aws:ecs:us-east-1:123456789012:task-definition/my-task-definition:1",
    "taskRoleArn": "arn:aws:iam::123456789012:role/my-task-role",
    "containerDefinitions": [...],
    "volumes": [
      {
        "host": {
          "sourcePath": "/data"
        },
        "name": "data"
      }
    ],
    "networkMode": "bridge"
}
```

Shippable sets the attribute `containerDefinitions` of an AWS ECS task definition by parsing these resources in my shippable.resources.yml:
- `dockerOptions` for, e. g., memory, volumes, log-driver
- `params`, for environment variables.

How can I specify the AWS IAM task role with shippable?

How can I specify the volumes with shippable?

**Comment by trriplejay** [comment]
currently we don't support the AWS IAM task role field. I'll mark that as a feature request.

volumes are supported as a dockerOptions field. They are accepted in the format:
```
volumes:                                 
  - "<source>:<container path>:<options>"
  - "<source>:<container path>:<options>"
```

when you do this, it maps to your taskDefinition and containerDefintion in the following way:

- the taskDefintiion volume `name` is created by shippable
- the taskDefinition volume `host.sourcePath` is the `<source>` in the example above
- the containerDefinition mountPoints `sourceVolume` is created by shippable (matches the taskDefinition `name` field)
- the containerDefinition mountPoints `containerPath` is the `<container path>` from the example above
- `<options>` supports a value of `ro` for read only

Let me know if you have other questions!

**Comment by feleil** [comment]
Thank you for the detailed description of how Shippable's `volumes` option maps to an AWS ECS task definition. With that I was able to fix the resource definition in my shippable.resources.yml
```
volumes:
  - "/data-on-instance:/data-in-container:rw"
```
where `/data-on-instance` is the directory on the EC2 instance (the mount point of an attached EBS volume), and `/data-in-container` is the path in the container. Shippable creates the ECS task definition as described in your comment. Nice!

Thank you for considering the feature request for IAM task roles. It would be great to be able to avoid distributing IAM user credentials to every container.

**Comment by BlueDragonX** [comment]
Any word when IAM roles for ECS tasks will be available? This is something we will need soon.

**Comment by scriptnull** [comment]
`taskRoleArn`  is now available and can be given by using a [dockerOptions resource](http://docs.shippable.com/pipelines/resources/dockerOptions/) with the following configuration as IN on your manifest or deploy job. 

```yml
  - name: ecs-dockerOpts
    type: dockerOptions
    version:
      taskDefinition:
        taskRoleArn: "YOUR_TASK_ROLE_ARN" 
```

Please check our updated [dockerOptions resource documentation](http://docs.shippable.com/pipelines/resources/dockerOptions/), for getting idea of newly supported attributes.

I am closing this issue for now. Please feel free to reopen, if you are having any queries.

Thanks.
