### ISSUE TITLE
Often requested to re-login to shippable.com using GitHub

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#2987]
We are often requested to login again to shippable.com e.g. when accessing the build logs from a GitHub pull request. Is there a timeout on the login? Using github.com this is never needed. Thanks.

Kind Regards,
Jeppe, Bang & Olufsen

**Comment by rageshkrishna** [comment]
@jeppefrandsen Our logins are currently tied to the browser session. We are going to change this to be persistent now.

**Comment by jeppefrandsen** [comment]
Sounds really great. Thanks.

**Comment by rageshkrishna** [comment]
@jeppefrandsen This is fixed. You should see persistent sessions from the next time you log in to Shippable. Let me know if you're still having trouble with this.

**Comment by jeppefrandsen** [comment]
Works perfectly. Thanks a lot
