### ISSUE TITLE
Shippable removes latest slash in github entreprise api endpoint

### ISSUE THREAD

**Issue by tarikd** [Shippable/support#2988]
### Description of your issue:

When trying to add integration of github enterprise, I need to fil a field with my "GitHub Enterprise server's API endpoint".

My github enterprise server's API endpoint looks like this:
    https://[hostname]/api/v3/

But when I put it in the field and save the configuration, shippable automatically removes the last slash sign which leads to a 404 page.

How can I solve this ?

Many thanks.

**Comment by rageshkrishna** [comment]
@tarikd This shouldn't bean issue because we append the trailing `/` wherever we need it. Is this stopping your integration from working? You may need to sync your account before your GitHub Enterprise organizations get listed on Shippable.

**Comment by tarikd** [comment]
I synced my account multiple times and still my account on github entreprise doesn't appear in the list with my github.com account.

**Comment by rageshkrishna** [comment]
I'm seeing SSL certificate errors in our logs. Is your Github Enterprise server using a self-signed or private CA certificate?

**Comment by tarikd** [comment]
Yep they are having trouble with the certificate, it's gonna be solved soon. Do you think that it's the reason why shippable is unable to integrate with ?

**Comment by rageshkrishna** [comment]
Yes, that explains why the organizations and repositories are not getting synced to Shippable. I think everything will work once the certificate issue is resolved.
