### ISSUE TITLE
Stuck in provision node for the last 15minutes

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#2990]
I cancelled before after 7 minutes and back the the same state: 
subscriptionId: 57b7db1f3d3c340e00026d35

Can someone check what is happening?

thanks

**Comment by a-murphy** [comment]
I'm not sure what was wrong with the node originally provisioned, but a new one is running.  It could have been a much slower than normal response to our request to provision a node, essentially leading to a timeout.

**Comment by Kirtap** [comment]
It unstuck itself after about an hour. Things seems back to normal now. Thanks
