### ISSUE TITLE
Unable to push a dockerimage to docker hub or to a private registry

### ISSUE THREAD

**Issue by Hrishike** [Shippable/support#2993]
I am unable to push a docker image to docker hub nor to a private registry of my own. 
I double, triple checked that the name mentioned in the integration is the same as used in the shippable.yml file. 

- Link to the build failure with docker hub as the integration :  https://app.shippable.com/runs/57e597e2fa747a0f008ab740/1/console 
- Link to the build failure with a private registry as the integration :  
https://app.shippable.com/runs/57e59263dd566d0f00a7e9ea/1/console

Any thoughts?

**Comment by manishas** [comment]
Can you share your shippable.yml?

**Comment by trriplejay** [comment]
(I noticed your project is public) 

It looks like your yml says `integration:` when it should say `integrations:`.  the missing `s` is causing it to be ignored.

Also, your `integrations` section is indented too far in the yml. it should be at the same indentation as the `build:` tag.

Lastly, I notice that your `env:` section is also indented too far. it should be at the same indentation as the `build` section as well.

**Comment by Hrishike** [comment]
Here is my shippable.yml

# Language setting
language: java

# Version number
jdk:
  - oraclejdk8

build:

  ci:
    - java -version
    - mvn --version
    - mvn clean install -DskipTests
    - mvn sonar:sonar
    - docker build -t hrishi/ms_catalog:latest .
    - docker images | grep hrishi

  post_ci:
#    - docker login dockerregistry.hclets.com -u hrishikesh.deodhar -p ${password}
    - docker push hrishi/ms_catalog:latest

  integration:
    hub:
      - integrationName: myregistry
#        type: "private docker registry"
        type : docker
  env: 
  - secure: JGpME+/yPInzSoM7M1KPLMgPo8yGraMWVrK+6eb+Cc7aI1mkDXujXyr/WIsu6gBacCAJTp3Pk1DDfHXA//Kr2bt5GqMglHzBbaeEQztKBClUkMhU1H6EoMY3yy7zAGWSMaEaGX6puycaVycdMx0fkLnWQFY/xgM1XtVwyM2GVN/LRkSVrZClVqhK4OK5CrJjS5BrMdwt7R4gbtmWOst/c+BfCWjB6KuXzS8CybmxKitKj44JNgNGqSIWYvogpen/hWCD/u7yFOd6BNV+LytbcCjELzKOzX49yacWOwXhAr68K/VdOIq8WlBWh+cCRVaUcOFdwG6vPRecxRnarCqKXQ==

**Comment by Hrishike** [comment]
@trriplejay . Thankyou !!! 
I had moved from `integrations` to `integration`. Indeed the indentation and the right usage of the keyword allowed me to push my image to the dockerhub repository.
