### ISSUE TITLE
Build stop triggering automatically on commit

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#2994]
This happened twice to me in 2 days. For some reason, builds stop beeing triggered when a commit is done on bitbucket. It just stop working for some reason

* Did not pause anything
* Confirmed the webhook in bitbucket is firing, getting a 200 back
* Body of response indicates {Webhook processed}

Only way I can get this  back to automatically triggering builds is to reset the project which reset the webhook. Then when i commit, the webhook response body indicates { "message": "Queuing run"} and the build is triggered in shippable.

Any insight?

**Comment by manishas** [comment]
@Kirtap Are you still running into this? Can you notify us next time this happens before you reset the project so we can look into what's going on?

**Comment by manishas** [comment]
CLosing this issue but @Kirtap let us know if you still need help witht his.
