### ISSUE TITLE
Karma PhantomJS Failure

### ISSUE THREAD

**Issue by gregorskii** [Shippable/support#2995]
Hi there,

I am finding a failure when using Karma and PhantomJS on Shippable.

The issue appears to be with PhantomJS Karma runner connecting to PhantomJS core:

```
24 09 2016 23:19:47.986:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
24 09 2016 23:19:47.987:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
24 09 2016 23:19:47.993:INFO [launcher]: Starting browser PhantomJS
24 09 2016 23:19:53.994:WARN [launcher]: PhantomJS have not captured in 6000 ms, killing.
24 09 2016 23:19:54.000:INFO [launcher]: Trying to start PhantomJS again (1/2).
24 09 2016 23:20:00.006:WARN [launcher]: PhantomJS have not captured in 6000 ms, killing.
24 09 2016 23:20:00.008:INFO [launcher]: Trying to start PhantomJS again (2/2).
24 09 2016 23:20:06.015:WARN [launcher]: PhantomJS have not captured in 6000 ms, killing.
24 09 2016 23:20:06.017:ERROR [launcher]: PhantomJS failed 2 times (timeout). Giving up.
```

The issue is intermittent.

Appears it may be related to https://github.com/karma-runner/karma-phantomjs-launcher/issues/84 where the solve seems to be an issue with the loopback URL or localhost DNS entry in the hosts file.

Running:

"karma": "^1.1.0"
"karma-phantomjs-launcher": "^1.0.0"
"phantomjs-prebuilt": "^2.1.7"

Any ideas?

Thanks!

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image.

You could also use `shippable_retry` to reduce flakiness. DNS can be flaky an hence the retry.
