### ISSUE TITLE
Pipelines: ECS Service Not Assigned ALB Load Balancer

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#2999]
### Problem Description
I'm attempting to deploy a new service using an existing pipeline. In order to do so I have added new `image`, `dockerOptions`, `manifest`, and `loadBalancer` resources as input to an existing `deploy` job. These are all configured in the same way as the other services I am deploying. The main differences are in the image being deployed and the ARN of the ALB target. After my initial build completed the `deploy` job itself completed successfully. However, when I checked to ensure that the ECS service was running I found that the service did not have a load balancer associated with it.

The image I'm trying to deploy is `loyalty-image-develop` which should trigger the `loyalty-develop` manifest and, in turn, the `zd` deploy job. That deploy job also has as input the `loyalty-zd-elb` load balancer.

### What I've Tried
I have made a few changes to the repo since the initial deploy. These subsequent deploys did not cause the ECS service to be re-deployed with the load balancer.

I've double-checked that the ALB Target ARN is correct and that the `deploy` job's `IN` values appear correct.

**Comment by BlueDragonX** [comment]
I have now also tried deleting the ECS service and letting Shippable redeploy it. The new service still does not have an attached load balancer.

**Comment by trriplejay** [comment]
It looks like your `applyTo` under `loyalty-zd-elb` has a typo (par of your `zd` job). Can you fix that and let me know if it works?

**Comment by BlueDragonX** [comment]
Well no wonder :smile: Thanks. Running that now to make sure that's the only thing.

**Comment by BlueDragonX** [comment]
All good! Thanks for bearing with me here.
