### ISSUE TITLE
Schedule Runs

### ISSUE THREAD

**Issue by plotti** [Shippable/support#30]
Is there a way to make shippable run an integration test once a week? Sometimes I'dont have code that i push during that week but the underlying apis might have changed, and I'd like to make sure that the software is still working. Any ideas?

Cheers
Thomas

**Comment by avinci** [comment]
We have APIs that can do this for you. Please let us know if you would need help to achieve this. We are not planning to implement this as a feature on Shippable other than the API route.

Hope that works.

**Comment by roman-gliffy** [comment]
That's a dealbreaker :( 
CI has to be continuous. 

https://docs.travis-ci.com/user/cron-jobs

**Comment by manishas** [comment]
Things have changed. Scheduled builds are now on our roadmap. :)

**Comment by plotti** [comment]
Oh thats great to hear! thx!

**Comment by keen99** [comment]
for other searchers, this got added with https://github.com/Shippable/support/issues/2600
