### ISSUE TITLE
Can't delete incorrect sync repository jobs

### ISSUE THREAD

**Issue by motobrew** [Shippable/support#3000]
I can't delete incorrect sync repository job which includes “/“ in the name.

In our Pipelines configuration, it seems to have added Pipelines jobs incorrectly.
When I added the pipeline resource (following “Add a sync repository” in http://docs.shippable.com/pipelines/gettingStarted/), I used the symbol “/“ in the resource name. (cause our branch name incluedes "/") Then, it was unsuccessful, but rSync job was made. And those are Jobs list and SPOG.

I tried to delete those incorrect jobs but could’t.
How do I delete them?

**Comment by motobrew** [comment]
adding information

When I added the resource which includes "/", the following message shown.
Then, the resource and the job were made.
After that, I could delete the resource, but the job couldn't. 
```
(Id: 4005) postResource for :parentResourceId 2459
verbose: resources|postNewSyncRepo|callerId:57d7891d954cbb0f0063f400|_postRSyncJob
500
```

**Comment by manishas** [comment]
@motobrew deleting the resource and job names in the yml and committing should get rid of the jobs. They will be show up in the 'Deleted' section of the resources list and you can delete permanently in the UI.

**Comment by trriplejay** [comment]
I was able to reproduce this using a branch with a `/` as stated. We'll investigate a fix.

**Comment by trriplejay** [comment]
@motobrew we've got a fix for this in the works, but until then, you can work around this by changing the name of your sync resource to not include the `/` when adding it for the first time.  We'll clean up your orphaned jobs.

**Comment by manishas** [comment]
This should be resolved. closing.
