### ISSUE TITLE
Deploy to existing Pods/Deployments?

### ISSUE THREAD

**Issue by ghost** [Shippable/support#3001]
Hi there,

With Pipelines, I would like to deploy an container image
to our existing Pods/Deployments in default namespace on GKE.
Is it possible?

**Comment by motosby** [comment]
I have tried the pipeline sample,
https://github.com/shippableSamples/samplePipelinesDemo
Then, I configured YAML files and I could deploy an image on my GKE cluster.
But I couldn't specify the namespace and Pods.

**Comment by trriplejay** [comment]
We don't allow this right now, but we are planning some enhancements in the future that would at least allow you to specify a custom namespace.

In your scenario, are you just saying that you want to be able to update the image of an existing pod? Currently, we only support modifying pods that were originally created on Shippable.  That's an interesting scenario though, and it sounds like a useful feature for us to consider.

We're also currently using replicationControllers, not deployments. We have some plans to allow the use of the deployment object, but I'm not sure what kind of timeline we're on for that.

Typically your pod would be defined in shippable pipelines and referred to as a "manifest".  You would update your manifest by changing the images, envs, or other options that are listed as inputs to the manifest.  The Shippable deploy job would then take care of sending the new pod spec to the replication controller, or creating a new replicationController if one didn't already exist, but there aren't any extra customizations on which RC and which pod.  Shippable generates the names based on a combination of your resource names (from yml) and typically a uuid.

**Comment by andremohamed** [comment]
+1 being able to specify the namespace would be good - in fact, critical, for our purposes where namespaces are used to define environments eg. dev, test, staging.

**Comment by Tapppi** [comment]
In general, the black box style of deploying to e.g. `gke` turned me off from using pipelines completely. Simple examples seem cool, but once I tried to find information about what the pipeline **ACTUALLY DOES** I was stumped. The fact that I'll just have to "trust shippable's pipeline" to work correctly and have no actual control over the kubernetes object modifications seems like it prohibits any complex infrastructure from using this.

I personally am not affected by this much, as we already have *CD* deployment scripts based on git `tag`s and `branch`es, but I did waste a good few hours just trying to find what pipelines actually do.

**Comment by avinci** [comment]
we launched `runCLI` which is exactly what you are looking for. There are 3 modes in which folks use us.

- runSH, this is dont do anything, just let me as a user do everything. (Jenkins like)
- runCLI, set up all the connections, auth etc to my integrations and stop there. This will reduce the amount of code needed to login etc and also avoid putting in sensitive information into your deployment scripts. But the actual deployment json configuration is still done by the user. This is an environment variable substituting command that makes it easy to replace some variables in your JSON file if needed
- deploy, this is fully managed for folks who might not want to be manipulation JSON to create deploys

So pick your choice based on your comfort. Hopefully this helps.

**Comment by manishas** [comment]
runCLI docs: http://docs.shippable.com/pipelines/jobs/runCLI/
