### ISSUE TITLE
Random npm ERR! network read ECONNRESET

### ISSUE THREAD

**Issue by thelamer** [Shippable/support#3003]
These were few and far between over the last few months, but recently this happens 50% of the time we run a build. 

Link to one of them: 

https://app.shippable.com/runs/57eab48ad946ef0f001dd58f/1/console

A rebuild will usually work, but only 50% of the time.

**Comment by a-murphy** [comment]
We've looked at this and have not been able to find a likely cause.  The more recent `ECONNRESET` errors did not all occur on the same host, and the hosts that were used to run those builds also ran successful builds. It may have simply been a temporary networking problem.  If you wish to retry your `docker build` commands, you may want to consider [`shippable_retry`](http://docs.shippable.com/ci/advancedOptions/retry/).

I was also unable to find a recent `ECONNRESET` error in that subscription that failed with the same error on rebuild, so perhaps I didn't search back far enough.  Do you have a link to one of those?

**Comment by thelamer** [comment]
Here is a rebuild that failed. 

https://app.shippable.com/runs/57ec5c616d80900e003a03b7/1/console

I understand the shippable retry and will most likely need to implement, just sucks because it triples real build failure feedback time.

I have to say most of our docker builds used to run through docker hosts in AWS similar to your infra, and we never ran into this. The fact that you have NPM specifically mentioned in that article means to me this is at least kind of common. 

I cannot imagine this is a network problem that is outside of your control, even if it is random it has to be a software bug, maybe something in Docker host networking. I assume you are doing some pretty complex multi layer stuff there. 

In the end though this cannot be written off as a "temporary" or uncommon problem.

**Comment by ashernevins** [comment]
We are also experiencing this. Shippable has has intermittent network problems for a while, but they seem much worse lately when using npm. Something like 50% of our builds are failing due to this. These builds are successful when not using Shippable at the same time. This is a really big problem as it ends up taking a very long time to get a successful build.

https://app.shippable.com/runs/57f337a150f20d10005e4bf1/1/console

**Comment by mberrueta** [comment]
me too, same problem. actually, there are a lot of issues related with the same

**Comment by thelamer** [comment]
This keeps being a problem, are you looking into this? If this continues we need to migrate back to gitlab.

**Comment by manishas** [comment]
We will take another look into this.

**Comment by ashernevins** [comment]
It seems to be happening again for me today. Any update on this?

**Comment by avinci** [comment]
is this happening since then? There has been whole bunch of updates mades n the last few months and I hope this is not happening anymore

**Comment by jails** [comment]
It happened to me today for the first time. We will keep you posted if it's a recurring issue.
