### ISSUE TITLE
Maven dependency Jars cannot be read

### ISSUE THREAD

**Issue by matthewfinn** [Shippable/support#3005]
### Description of your issue:
I am experiencing an issue where .jar files cannot be extracted when downloading from my dropbox artifact repository. It runs locally with no problems but when I run on shippable it gives me the error `[ERROR] error reading /root/.m2/repository/ie/nuigalway/mfinn/StudentRegistration/1.0.0/StudentRegistration-1.0.0.jar; error in opening zip file`.
I assume there is a problem with either access or folder creation in the shippable workspace.
Is there a way of accessing the build workspace on shippable?

- Link to the build failure: https://app.shippable.com/runs/57eba1d96fb4bc0e008f14bb/1/console
- Scripts called from the yml : 
   - mvn clean dependency:copy-dependencies (not necessary was just messing with it)
   - mvn compile assembly:single

Thanks,
Matthew
m.finn11@nuigalway.ie

**Comment by matthewfinn** [comment]
Just thinking as a workaround I could copy dependencies into a folder where they're being looked for if it's a problem with them being created in the shippable workspace.

**Comment by a-murphy** [comment]
Earlier in the logs for that build, there's a warning in with the download logs:
```
[WARNING] The POM for <name> is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
```

So perhaps the file that cannot be opened isn't actually a valid jar file.  Could you try `mvn -X compile assembly:single` to see what the debug logs say?

**Comment by matthewfinn** [comment]
Ah yeah just after spotting
`[FATAL] Non-parseable POM /root/.m2/repository/ie/nuigalway/mfinn/StudentRegistration/1.0.0/StudentRegistration-1.0.0.pom: entity reference names can not start with character '&' (position: START_TAG seen ...vent.target; elm; elm = elm.parentElement) {\n        if (elm.id &&... @57:22)  @ line 57, column 22`

Don't know how I didn't see it before. Thanks for point me in the right direction
