### ISSUE TITLE
[PRE-SALES]- CentOS and Alpine based containers

### ISSUE THREAD

**Issue by tspicer** [Shippable/support#3006]
We have dozens of our containers currently using CentOS and Alpine. My reading of the docs indicate we would have to transition all of our containers to use Ubuntu. Is this a correct reading of the docs? If it is not, what limitations or considerations are there for using our current OS choices and choosing Shippable. Thanks!

**Comment by tspicer** [comment]
I will have to assume that the answer is yes, you will have to rewrite your container OS to align with Ubuntu

**Comment by BlueDragonX** [comment]
That is not correct, you can build any container you want. You should also be able to use any base image for a build container that you want so long as the appropriate tools are included. In general if Docker supports it Shippable supports it.

FYI, we build Ubuntu, Debian, and Alpine containers on Shippable. I've used Ubuntu and Debian for build containers in a BYON setup.

**Comment by tspicer** [comment]
BlueDragonX,

Thanks for the reply. So there are no limitations or requirements that a user must run Ubuntu? There are prior issues here on GitHub which indicate otherwise. For example, this was from @ric03uec a few months back:

>As of now, our build system officially supports only the images based out of ubuntu:12.04 and ubuntu:14.04 although users have managed to run the builds on other images like debian that satisfy underlying dependencies
> There are many dependencies on the build image that are missing in alpine like following
> 
>     /bin/bash
>     python2.7
>     /proc/sys/kernel/uuid
>     apt-get // this is used to install further dependencies like git and openssh-client
> 
> these dependencies are critical for the shippable build runner to execute inside a user-provided image.
> We can add your issue as a feature-request for supporting non-ubuntu (or generic) images.

I can imagine that while it may work with other base images, it is not supported. So I know I can use different base images (and have), it is not supported officially by Shippable. I want to avoid being told "Sorry, we don't officially support X, Y or Z because you are not using ubuntu:12.04 and ubuntu:14.04". Maybe this has changed, I just cant locate anything to the contrary from Shippable.

**Comment by BlueDragonX** [comment]
That only applies to the _build images_: the images that Shippable uses to build _your_ images.

**Comment by JJ** [comment]
So I guess Alpine images are still not supported, right?

**Comment by trriplejay** [comment]
While we don't have pre-made Alpine based build images, and we don't have dynamic nodes that run purely on Alpine, you can still utilize Alpine images in the pre_ci_boot section of your yml, and you can successfully `docker build` Alpine images in your CI.  They will just be running/building on a host that is based on u14.04, u16.04, or centOS.

**Comment by manishas** [comment]
We launched support for CentOS a few months ago, so you should now be able to just buy CentOS build nodes and run your builds.

Alpine images also work on Shippable, but we don't have a standard library of images. So the recommended approach is to use an Alpine image as a custom image in `pre_ci_boot` as John suggests above. I can point anyone who's interested to some samples.
