### ISSUE TITLE
Build output folder

### ISSUE THREAD

**Issue by sheldon-sminq** [Shippable/support#3008]
Is there any change to the build output directory structure, my build fail
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:05 min
[INFO] Finished at: 2016-09-29T11:31:44+00:00
[INFO] Final Memory: 50M/497M
[INFO] ------------------------------------------------------------------------


cp -r ./target/* ./shippable/buildoutput
cp: target ‘./shippable/buildoutput’ is not a directory
```

- https://app.shippable.com/runs/57ecf7876d80900e003a145e/1/console

The shippable/buildoutput folder does not exist anymore.

**Comment by cratz** [comment]
@sheldon-sminq 
As far as I know you have to create this directory before you can use it
like this:
```
ci:
  - mkdir -p shippable/buildoutput
  - %RUN BUILD%
  - cp -r ./target/* ./shippable/buildoutput
```

**Comment by sheldon-sminq** [comment]
This was never a part of my yml config, it was working all these days until today. Will try your suggestion and check again.

**Comment by cratz** [comment]
Well this is weird since we have it from the beginning in our `shippable.yml` according to the outdated docs:
https://github.com/Shippable/docsv2/blob/3c25a6914d674351c5c0f690f821db038adf0bb3/sources/legacyFiles/ht_docker_build.md#copying-artifacts-to-prod-image

**Comment by sheldon-sminq** [comment]
I tried your suggestion and it works now thanks.
