### ISSUE TITLE
Support for building on a specific node

### ISSUE THREAD

**Issue by bogotej** [Shippable/support#3009]
We could really use the ability to trigger builds on specific build nodes (using BYON).
Some scenarios where this could be useful to us: 
- Tracking build time on a fixed hardware configuration.
- Execute build on a node placed in a special network.
- Execute build on a "monster" node.

Best,
Torben, Bang & Olufsen

**Comment by avinci** [comment]
Based on our current architecture, this would be very difficult to do. At this point nodes are at a subscription and making them go to at a project level is a lot of rework. We dont have any plans to do this and we will update it if that changes. 

Sorry for not being able to accommodate this at this time.
