### ISSUE TITLE
I'm trying to add github enterprise to my account and it's not working

### ISSUE THREAD

**Issue by sarahleeashraf** [Shippable/support#3012]
The sync appears to work, but I don't see github enterprise in my CI dropdown

**Comment by a-murphy** [comment]
We're getting an error trying to get basic information about your GitHub Enterprise account in order to synchronize it.  Could you check that the GitHub Enterprise token you added to Shippable has [these scopes](http://docs.shippable.com/integrations/scm/githubEnterprise/)?

**Comment by sarahleeashraf** [comment]
So we had to re-set up everything, but we're still having the same issue. I think we have the right scopes is it easy to see which one is missing?

**Comment by sarahleeashraf** [comment]
Looking at the server logs and we don't see any requests coming from you guys?

**Comment by a-murphy** [comment]
There aren't any more clues in our logs.  The point at which your syncs are failing is consistent with missing `user` or `user:email` scopes.  It may also be that we simply can't reach your GitHub Enterprise server.  Do you know of anything that would prevent requests reaching your server?  We'll keep investigating.

**Comment by sarahleeashraf** [comment]
We only allow connections on certain ports. What port are you trying to connect on?

**Comment by a-murphy** [comment]
It should just be the HTTPS default port 443 for these requests.  They're both `GET` requests to the URL specified in the account integration with `/user` and `/user/emails` added to the end to get basic information about the account to be synchronized.

**Comment by sarahleeashraf** [comment]
Ok just regenerated the token and used it with the api. I seem to be able to make both of those requests fine. That port is open.

**Comment by mattlevin** [comment]
I am taking this over from my colleague. As she mentioned, we are able to successfully call the 2 api methods from outside our network with the token entered in our shippable github enterprise integration. I setup another instance of shippable with my github account (same enterprise account) and see the same problem as her. Is there any update from your side on this?

Not sure if it matters, but the github enterprise page for setting the scopes for personal access tokens has changed from the screenshot in your documentation, so I'm not sure if anything behind the scenes has changed that you would need to update in your code. Just a wild theory.

**Comment by mattlevin** [comment]
Sorry to push, but this is a blocker for us right now and we are looking to pick a new CI system asap to work with our new Github Enterprise system. Please let me know what you have found or if you need anything from our side. Thanks.

**Comment by trriplejay** [comment]
Hey, sorry about the delay on this. We suspect it's certificate related. We're working on updating the ca list on our services to see if that resolves the problem. Is there anything particularly unusual about your certificate setup? I suspect ours just needs to be updated.

**Comment by trriplejay** [comment]
@mattlevin are you by chance using a self-signed certificate on your ghe server?

**Comment by sarahleeashraf** [comment]
@trriplejay we were, but that should be fixed now.

**Comment by trriplejay** [comment]
The error that we're encountering seems to be due to the fact that only the server certificate is being sent in the certificate chain, and that doesn't appear to be enough to validate the chain.  If your server certificate was signed by an intermediate authority, then that intermediate certificate should also appear in the chain.  Once we are able to properly trace the certificate back to the root, it is likely that it will be recognized and the communication will be allowed.

We checked this by running `openssl s_client -showcerts -connect <your domain>` from one of our hosts.  It only showed one certificate, and reported `Verify return code: 21 (unable to verify the first certificate)`.

I think if you can install the intermediate certificate such that it is returned in the chain, it should solve this problem.

**Comment by mattlevin** [comment]
That did it. Thanks so much for you help @trriplejay !

**Comment by trriplejay** [comment]
awesome, I'm glad that worked!
