### ISSUE TITLE
docker-compose: command not found

### ISSUE THREAD

**Issue by affinion** [Shippable/support#3014]
Receiving error message: ```docker-compose: command not found```

https://app.shippable.com/runs/57f1605c6d80900e003a70ab/1/console

![screen shot 2016-10-02 at 12 32 13 pm](https://cloud.githubusercontent.com/assets/22244407/19023222/dd59ffa6-889d-11e6-93ea-f24fc0d446cc.png)

**Comment by a-murphy** [comment]
The default Shippable build nodes have Docker 1.9.1 installed, which does not support compose.  Nodes with Docker 1.11.1 may be selected on the subscription settings tab.  The same type of node will be used for all builds in the subscription.  More information about the node choices is available [here](http://docs.shippable.com/ci/advancedOptions/machineImages/).

**Comment by tmornini** [comment]
I've configured my account to use the unstable image, but I'm still receiving the [same error](https://app.shippable.com/runs/57fd077e9f7f140f00c75a3c/1/console):

**Comment by tmornini** [comment]
@avinci Could you take another look at this, even though you closed it?

**Comment by a-murphy** [comment]
Sorry, for some reason I thought that those nodes had Compose.  But, it can be installed on the "unstable" nodes.  Documentation on installing Docker Compose is [here](https://docs.docker.com/compose/install/).  The installation commands can be added to your shippable.yml before using `docker-compose`.

**Comment by tmornini** [comment]
@a-murphy I've [now installed](https://app.shippable.com/runs/57ff26fc11c4731000757953/1/console) docker-compose (1.8.1) on unstable, but it's not working correctly.

I get errors like:
```
ERROR: for purchases  Cannot start service purchases: Container command '/purchases' not found or does not exist.

ERROR: for releases  Cannot start service releases: Container command '/releases' not found or does not exist.
```

This works locally on Mac OS X 10.11.6 (15G1004) with Docker for Mac installed.

I believe I understand what the error messages mean, but it doesn't make sense as those executables *are* on the built images, right where they should be, which I verified by:

```
docker history incentive-networks/purchases

IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
3c914004375b        19 seconds ago      /bin/sh -c #(nop) EXPOSE 81/tcp                 0 B                 
21f2e31187d1        19 seconds ago      /bin/sh -c #(nop) EXPOSE 80/tcp                 0 B                 
57853a1bb1b8        19 seconds ago      /bin/sh -c #(nop) CMD ["/purchases"]            0 B                 
39ec944831ea        19 seconds ago      /bin/sh -c #(nop) COPY file:e726d2d3d5407f910   273.8 kB            
b4e0fb99bd49        19 seconds ago      /bin/sh -c #(nop) COPY file:4e4b16605f140ea30   10.43 MB            
dcb2e45ff85b        20 seconds ago      /bin/sh -c #(nop) MAINTAINER Tom Mornini <tmo   0 B                 

docker export incentivenetworks_purchases_1 | tar tvf -

-rwxr-xr-x 0/0               0 2016-10-13 06:18 .dockerenv
drwxr-xr-x 0/0               0 2016-10-13 06:18 dev/
-rwxr-xr-x 0/0               0 2016-10-13 06:18 dev/console
drwxr-xr-x 0/0               0 2016-10-13 06:18 dev/pts/
drwxr-xr-x 0/0               0 2016-10-13 06:18 dev/shm/
drwxr-xr-x 0/0               0 2016-10-13 06:18 etc/
-rwxr-xr-x 0/0               0 2016-10-13 06:18 etc/hostname
-rwxr-xr-x 0/0               0 2016-10-13 06:18 etc/hosts
lrwxrwxrwx 0/0               0 2016-10-13 06:18 etc/mtab -> /proc/mounts
-rwxr-xr-x 0/0               0 2016-10-13 06:18 etc/resolv.conf
drwxr-xr-x 0/0               0 2016-10-13 06:18 etc/ssl/
drwxr-xr-x 0/0               0 2016-10-13 06:18 etc/ssl/certs/
-rw-r--r-- 0/0          273790 2016-10-13 06:18 etc/ssl/certs/ca-certificates.crt
drwxr-xr-x 0/0               0 2016-10-13 06:18 proc/
-rwxr-xr-x 0/0        10434589 2016-10-13 06:18 purchases
drwxr-xr-x 0/0               0 2016-10-13 06:18 sys/
```
and
```
docker history incentive-networks/releases

IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
5d4970d5ed8c        16 seconds ago      /bin/sh -c #(nop) EXPOSE 81/tcp                 0 B                 
438be8a9fda8        16 seconds ago      /bin/sh -c #(nop) EXPOSE 80/tcp                 0 B                 
f4315c7a81cc        17 seconds ago      /bin/sh -c #(nop) CMD ["/releases"]             0 B                 
7df6b59bc268        17 seconds ago      /bin/sh -c #(nop) COPY file:e726d2d3d5407f910   273.8 kB            
52fc6bda553a        17 seconds ago      /bin/sh -c #(nop) COPY file:496cd78685e4a0be8   9.334 MB            
dcb2e45ff85b        20 seconds ago      /bin/sh -c #(nop) MAINTAINER Tom Mornini <tmo   0 B                 

docker export incentivenetworks_releases_1 | tar tvf -

-rwxr-xr-x 0/0               0 2016-10-13 06:18 .dockerenv
drwxr-xr-x 0/0               0 2016-10-13 06:18 dev/
-rwxr-xr-x 0/0               0 2016-10-13 06:18 dev/console
drwxr-xr-x 0/0               0 2016-10-13 06:18 dev/pts/
drwxr-xr-x 0/0               0 2016-10-13 06:18 dev/shm/
drwxr-xr-x 0/0               0 2016-10-13 06:18 etc/
-rwxr-xr-x 0/0               0 2016-10-13 06:18 etc/hostname
-rwxr-xr-x 0/0               0 2016-10-13 06:18 etc/hosts
lrwxrwxrwx 0/0               0 2016-10-13 06:18 etc/mtab -> /proc/mounts
-rwxr-xr-x 0/0               0 2016-10-13 06:18 etc/resolv.conf
drwxr-xr-x 0/0               0 2016-10-13 06:18 etc/ssl/
drwxr-xr-x 0/0               0 2016-10-13 06:18 etc/ssl/certs/
-rw-r--r-- 0/0          273790 2016-10-13 06:18 etc/ssl/certs/ca-certificates.crt
drwxr-xr-x 0/0               0 2016-10-13 06:18 proc/
-rwxr-xr-x 0/0         9333947 2016-10-13 06:18 releases
drwxr-xr-x 0/0               0 2016-10-13 06:18 sys/
```

**Comment by a-murphy** [comment]
The executable file is most likely there, but can't run.  The error message from Docker is the same if the file is missing or if the container can't run the file.  Are there volume mounts involved?  Or could the file be missing some dependency?

**Comment by tmornini** [comment]
> Are there volume mounts involved?

No

> Or could the file be missing some dependency?

Anything is possible, but this exact same path cross-compiles (os x -> linux) go, and builds two file Docker containers which start fine on Mac OS X.

Are there common dependencies -- besides SSL root certs which I've already handled -- that I should be aware of?

**Comment by a-murphy** [comment]
I can't determine what dependencies your code has.  Either pushing the image built on Shippable to a registry or using images pulled from a registry (built locally) may help you narrow down why it doesn't work.
