### ISSUE TITLE
Build hanging as "Pending" while Provisioning a node 

### ISSUE THREAD

**Issue by paulcornwell** [Shippable/support#3015]
### Description of your issue:
AWS elastic beanstalk build hangs in Pending status:   "Provisioning a node for subscriptionId: 57ea8202f59fdd0e00b51f82"

- Link to the build failure
https://app.shippable.com/runs/57f2a22d75a4470f00e6a0d0/1/console

**Comment by paulcornwell** [comment]
![image](https://cloud.githubusercontent.com/assets/2745250/19049039/bc2bb5a2-8976-11e6-977f-f41f1c2f9ff9.png)

**Comment by trriplejay** [comment]
it looks like increased error rates in AWS us-east-1 region have caused a few node provisions to fail. Those issues seems to have been resolved now, so if you cancel your build and run again, it should provision.

**Comment by paulcornwell** [comment]
Yep, noticed that it's working again. Thanks for the explains, trriplejay.
