### ISSUE TITLE
Github webhook stopped working

### ISSUE THREAD

**Issue by gielwijgergangs** [Shippable/support#3019]
The webhook in Github for triggering a build stopped working. Where can I find the documentation on how to set this up? It was setup like:
https://???:???@api.shippable.com/projects/???/newBuild
How can I use the new API key in the URL above?

Also triggering a new build in shippable app gives us errors:

(Id: 4006) postRun failed for projectId: 54bf73655ab6cc135289424d
verbose: projects|triggerNewBuildRequest:54bf73655ab6cc135289424d|_queueRun
500

https://api.shippable.com/projects/54bf73655ab6cc135289424d/newBuild

**Comment by rageshkrishna** [comment]
@gielwijgergangs You can use the "Reset" button on the project's "Settings" tab. This will regenerate the webhook for you on GitHub.

The second issue is that it looks like one of your subscription integrations is no linked to an account integration that no longer exists. We are working on a fix to make sure this scenario never occurs, but in the mean time if you can either delete that subscription integration (if you are no longer using it), or link it to a valid account integration, your builds should start running again.

**Comment by gielwijgergangs** [comment]
@rageshkrishna  Thanks, I tried reset. But the webhook isn't created in Github.
I fixed integrations, and triggering a new build in Shippable works now.

**Comment by gielwijgergangs** [comment]
@rageshkrishna I finally found it. The reset was under a different "settings" tab. I used the settings for the organization, not the repository. Thanks.
