### ISSUE TITLE
Build failed on `waiting_for_exit` step.

### ISSUE THREAD

**Issue by vvahans** [Shippable/support#3020]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

Error output:

 Command: sudo docker rm -fv $CONTAINER_NAME 0s  
  Error response from daemon: no such id: c.exec.myapp.5090.1
  Error: failed to remove containers: [c.exec.myapp.5090.1]

myapp added instead if the real app name.

- Link to the build failure
https://app.shippable.com/runs/57f3bcc2ca30990e003809c5/1/console

**Comment by manishas** [comment]
@vvahans your build timed out since it ran for over an hour. The timeout for free plan is 60 minutes.

**Comment by vvahans** [comment]
@manishas Can you see what makes it to take so long?

**Comment by trriplejay** [comment]
@vvahans looks like there may have been some hiccup that caused your build to get set to processing without a node provisioned to run it.  It may not have been picked up until a subsequent build was triggered, causing a new node to be provisioned again. By the time the new node got provisioned and began to ran the build, there were only about 10 minutes left until the timeout was up, so the container was killed while processing.
