### ISSUE TITLE
Only receiving emails for one email in list

### ISSUE THREAD

**Issue by bantonj** [Shippable/support#3022]
I'm only receiving emails for the second email below, and the Hipchat notification isn't working. Below is my notification yaml.

  notifications:
    - integrationName: email
      type: email
      recipients:
        - one@krossover.com
        - two@krossover.com
        - three@krossover.com
      on_success: change
      on_failure: always

    - integrationName: HipChat Eng Notifications
      type: hipchat
      recipients:
        - Engineering Notifications
      on_success: always
      on_failure: always

**Comment by trriplejay** [comment]
Hello,

For emails, we validate that the email provided is tied to a shippable account that has access to the project. This is to prevent people from getting spammed by forked repos when they might not even use shippable.  Have the owners of the other two emails logged into shippable?

For hipchat, this seems to be a legitimate bug, but we're investigating.

As a workaround, can you try updating the "recipients" line to say:
```
recipients:
  - #Engineering%20Notifications
```

our standard is to require `#` or `@` to distinguish between user and channel, so in this case the `#` is definitely required.  I suspect you'll also need the `%20` to url-encode the space in the channel name.  We should be doing that automatically, but I don't think we are. That is a bug on our part.

Let me know if the workaround works for you.

**Comment by kanthchandra** [comment]
Hi @bantonj Can you point me to the latest build for which you dint receive notifications?

**Comment by bantonj** [comment]
@kanthchandra This one https://app.shippable.com/runs/57f5535bb48edb0e00394b30/1/console. 

I haven't tried the workaround for the hipchat notifications yet. And I need to check on those email addresses for Github, I think if I can get those added the emails should start working.

**Comment by kanthchandra** [comment]
Hi @bantonj , I looked into the email issue, I dont see any issues with the yml and the way we store the recipient and the logs also dont suggest any errors while sending email. 

Can you also check if the emails are going to the spam folder?
Are you seeing this behaviour consistently? From your config you should receive email only when the build fails.

Coming to hipchat notification, let us know if the workaround suggested by @trriplejay works for you.

**Comment by manishas** [comment]
closing this issue but @bantonj let us know if you have any additional questions.
