### ISSUE TITLE
V1 Pipelines are no longer available!

### ISSUE THREAD

**Issue by failpunk** [Shippable/support#3023]
### Description of your issue:
V1 pipelines have been disabled with all 10  of our pipelines.
We are currently in the process of testing out the new pipelines but they are not going to be ready for some time.  WE MUST have the pipelines V1 enabled to continue development of currently active production sites.

How can we turn these pipelines back on?

Shippable ID
5748c0272a8192902e21aa25

**Comment by trriplejay** [comment]
Access is restored now. Please contact us if you have any questions on how to make the transition.  We will extend the availability of v1 until next wed.

**Comment by pwarnock** [comment]
When was the sunset date announced that we had to get off of v1? It's a tough sell to management, that we have to drop everything to reconfigure 10 pipelines with 30 environments.  Next Wednesday is a bit short notice. I think it should be supported at least through the end of the month.

**Comment by manishas** [comment]
@pwarnock we tried to send out at least 5 emails over the past month to your ops alias but you had unsubscribed from all Shippable emails so they were not delivered. We use the ops contact to send these kind of notifications so if you unsubscribe, you're going to miss them.

The best we can do at this time is to keep pipelines v1 active for your account until next Friday 10/14. We are happy to assist with the move and will handle your issues and questions with top priority. We are also available to jump on a google hangout and help if you need that.

**Comment by pwarnock** [comment]
@manishas Thanks.  I don't know how we got unsubscribed, but how can we correct that?

We really like the product, but unlearning V1 and learning the new way is proving to be difficult.  Any support you can provide would be greatly appreciated.

The biggest issue I'm encountering is updating the image resource version when CI finishes pushing a Docker image.  I've followed the [Connecting CI to Pipelines tutorial](http://docs.shippable.com/tutorials/pipelines/connectingCiPipelines/).  I don't know what a successful result looks like, but I'm assuming the version sent in the payload from the webhook, should create a [new version of my image resource](https://app.shippable.com/subscriptions/573a53db2a8192902e204f23/pipelines/resources/3056/versions).

Another issue is that my teammates and I cannot see each others' triggers. Also, do we have to create a trigger per pipeline?

Lastly, how do we rollback deployments? Do we have to re-seed the image and deploy forward?

I look forward to your reply. Please let me know how/when we can connect for a faster feedback cycle.

**Comment by pwarnock** [comment]
@manishas The CI trigger error was because I wasn't passing the correct api key.  Is there a place that would report the error or does it silently fail?

**Comment by manishas** [comment]
It should have shown an error in your CI console logs. 

We can set up a hangout to help on Monday if you have some time. We're available from 9am-5pm PST. Let me know a time that works and we can set it up.

**Comment by manishas** [comment]
@pwarnock just a reminder that pipelines v1 are scheduled to be turned off tomorrow. Let me know if you want to troubleshoot anything over a hangout.

**Comment by pwarnock** [comment]
@manishas Thanks for the reminder. What's a good time for a Hangout? I'm available all day. 

The questions we have so far are:
# How do we rollback? (run a previous job?)
# How do versioned releases work? (What we see in the UI versus what we read in the documentation)
# How do we know what triggers were added by another user?
# How do filters work in the SPOG UI?

**Comment by manishas** [comment]
How about 2pm PST? I can send you a meeting invite.

**Comment by pwarnock** [comment]
Great! peter@studymode.com or petewarnock@gmail.com

**Comment by manishas** [comment]
Closing this issue since we turned off pipelines v1 today. Please let us know if there are any concerns around this,.
