### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by antoligy** [Shippable/support#3024]
### Monorepo support

Hey, is it possible to maintain separate/distinct projects in Shippable which test and deploy independently of one another from a monorepo?
I've had a look through existing issues, and through the docs, and so far I can't see a good way of setting this up without having to write lots of scripts.

We have two use-cases for this right now:
1. Microservices which share a tech-stack, but which are tested and deployed separately.  With different requirements such as code-coverage dependent on service tier.
2. A SOA, with (for example) a front-end powered by Node and a back-end powered by something else - Here the tech stack isn't shared, and so these need to be tested independently of each other with differing environments.  It's possible to run different environments right now, but I'm not sure if it's possible to then build different docker images and run different test suites.

It seems as though both use-cases might be fixed given the ability to import a repository with multiple shippable.yml files, with each one appearing as a first-class citizen in Shippable (a distinct, separate project).

Thanks!
Alex

**Comment by adamporad** [comment]
This is a feature I am interested in as well. Monorepo's aren't that uncommon.

**Comment by avinci** [comment]
Shippable currently runs monorepo internally. We have written a blog about how we do it. Does this scenario work for you? If so we can write up a blog and show how it can be done.

**Comment by avinci** [comment]
Attaching the blog to demonstrate how to build and deploy a monorepo. Please let us know if this helps. 

http://blog.shippable.com/build-test-and-deploy-applications-independently-from-a-monorepo

**Comment by njdnet101** [comment]
Workaround is useful but I think this is still a valid request. Struggling to find any vendor that supports this without custom work
