### ISSUE TITLE
docker push: unauthorized

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#3026]
Hi, I'm building an image and pushing it to Docker Hub, but I'm getting the error
```
unauthorized: authentication required
```

This happens in [this build](https://app.shippable.com/runs/57f7566c6da7b40e005d3903/1/console), while the push succeeded in a [previous build](https://app.shippable.com/runs/57f74c2c6da7b40e005d3878/1/console), without me changing the integration settings...

I attach my yml as well ! 

[shippable.yml.zip](https://github.com/Shippable/support/files/515613/shippable.yml.zip)

**Comment by jacopo-chevallard** [comment]
(now I switched the Docker Hub repo to public, but it would be nice to understand the cause of the problem)

**Comment by trriplejay** [comment]
We don't see anything in your failing build that explains this behavior. You yml integration was recognized, and the docker login was successful.  My guess is some kind of temporary issue with docker hub authorization. Making your repo public still wouldn't allow you to push to it unless you were an authorized user.

**Comment by jacopo-chevallard** [comment]
ok, thanks for checking, closing
