### ISSUE TITLE
Testing in multiple languages

### ISSUE THREAD

**Issue by gappleto97** [Shippable/support#3030]
I have a set of tests I need to run in Javascript and Python.

I attempted to define a matrix build, but for some reason it [detected this as ruby](https://app.shippable.com/runs/57fb199fb48edb0e0039b5cd/summary).

How can I modify [my yml file](https://github.com/gappleto97/p2p-project/blob/develop/shippable.yml) in such a way where I can test in both of these languages?

**Comment by a-murphy** [comment]
If there is no `language` in the shippable.yml file, the default is Ruby.

The usual way to run tests with two languages is to specify one language in the shippable.yml file, with the version(s) of that language to be tested and add environment variables for the versions of the second language that can be used in the `build` section in the shippable.yml file.  Only one build image may be chosen for all the builds in the matrix.  If it's the default for one of the languages, then you may need to install versions of the other language in the `build` section.  All of the default images have one version installed for NodeJS (with nvm) and Python 2.7.  Or, you can [use your own image](http://docs.shippable.com/ci/shippableyml/#pre_ci_boot).
