### ISSUE TITLE
Deploying to ECS fails with 'Provider not found for integration of type ECR'

### ISSUE THREAD

**Issue by asaf** [Shippable/support#3031]
Hey,

I'm trying to follow the demo pipeline,

I get:

```bash
WARN
package.json
npm
package.json shippable-Deploy@4.0.1 No repository field.
npm
 WARN 
 WARN package.json shippable-Deploy@4.0.1 No README data
 shippable-Deploy@4.0.1 No license field.
npm WARN package.json
----> Run Deploy
Starting Deployment for: deploy-preview
Preparing manifests
Applying manifest overrides for preview-manifest
Summary of loadBalancers: -- newlyAdded: 0, -- changed: 0, -- deleted: 0
Summary of cluster: -- newlyAdded: 1, -- changed: 0, -- deleted: 0
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Force deployment is: false
Deployment failed with error : Provider not found for integration of type ECR
```

What **Provider not found for integration of type ECR** means?

Thanks.

**Comment by a-murphy** [comment]
The cluster is expected to have an subscription integration with type "AWS" instead of "Amazon ECR".  Changing the integration for the cluster resource to a "AWS" integration should work.

**Comment by manishas** [comment]
CLosing this since the question was answered. @asaf let us know if you have any follow up qs.

**Comment by asaf** [comment]
@a-murphy Thanks!
Although tricky, I would suggest handling incorrect pipeline steps in a more descriptive way,
(Maybe restrict/allow certain type of integrations or at least provide a better descriptive errors)

@manishas sorry was on a vacation =)

Thanks guys
