### ISSUE TITLE
Unable to view FAQs for pipelines

### ISSUE THREAD

**Issue by stuartstevenson** [Shippable/support#3033]
### Description of your issue:
When I visit http://docs.shippable.com/pipelines_faq/ I am unable to view the pages content. Page headers and side bars are being rendered, but the main content isn't.

There are 2 errors in the console:

Failed to load resource: the server responded with a status of 403 (Forbidden) http://docs.shippable.com/pipelines_faq/

and 

Failed to load resource: the server responded with a status of 403 (Forbidden)
http://docs.shippable.com/pipelines_faq/mkdocs/js/require.js

I am seeing this on both Chrome and Edge on Windows 10.

I visited the above page trying to troubleshoot an issue as suggested on the support landing page. This page was also broken http://docs.shippable.com/ci_faq/

**Comment by stuartstevenson** [comment]
I was checking with colleagues if this was an issue isolated to me and discovered the issue was simple that the links on https://github.com/Shippable/support to the FAQs were pointing to pages that no longer exist and I found the FAQs here http://docs.shippable.com/faq/

**Comment by manishas** [comment]
@stuartstevenson sorry about this :(

We'll update the docs links asap.

**Comment by manishas** [comment]
fixed. closing.
