### ISSUE TITLE
Integration name specified in yml does not match integrations present in Subscription settings

### ISSUE THREAD

**Issue by thelamer** [Shippable/support#3034]
https://app.shippable.com/runs/57fd3929ca30990e0038ef78/1/console

This integration exists and I have checked and changed the name a couple times now, not sure where to go from here.

**Comment by a-murphy** [comment]
It looks like there is probably an account integration with that name that hasn't been added to the subscription.  Could you try adding it to the subscription as [described here](http://docs.shippable.com/navigatingUI/subscriptions/settings/#adding-integrations)?  Then builds in that subscription will be able to use the integration.
