### ISSUE TITLE
CI build pages not protected by auth

### ISSUE THREAD

**Issue by mattlevin** [Shippable/support#3035]
I am able to access and navigate my CI build pages, starting with a project's status page, without being logged in (I do not wish to put the url here since then anyone can access it). This is a private GHE repo that its running against and although the url for Shippable is not easily guessable, I cannot have it publicly exposed. How can I protect these pages?

**Comment by kanthchandra** [comment]
Hi @mattlevin we did a quick test on a private github project and we are not able to access it until we logged in.

Can you please email me the project url so that I can take a look at whats going on? chandrakanth@shippable.com

**Comment by kanthchandra** [comment]
We take security seriously and unless it's a public project we dont allow anyone who doesn't have access to the project to view the projects page or any of the builds for that project. We inherit the same permissions that GHE gives and any person who doesn't have access to the project on your GHE server should not be able to see the project on shippable. This rule holds good not only on GHE but also across all source providers.

**Comment by mattlevin** [comment]
@kanthchandra Just emailed you. Thanks.

**Comment by kanthchandra** [comment]
@mattlevin I have opened an Internal Issue to discuss the issue, I'll get back to you when we have a resolution on this one. Thanks

**Comment by stephanielingwood** [comment]
@mattlevin This should now be resolved. Please let us know if you're still running into this issue, or if you need help with anything else. Thanks.

**Comment by mattlevin** [comment]
I see the page protected now. Thanks
