### ISSUE TITLE
Can I output a Load Balancer resource from runSh job

### ISSUE THREAD

**Issue by stuartstevenson** [Shippable/support#3036]
I'm trying to set up a pipeline that will create an ELB load balancer before deploying an ECS Service that relies on said ELB. I had envisaged that I would be able to use a runSh job to run some CloudFormation template to generate the ELB and then output the new Target Group name and then set this on the Load Balancer resource that is then used as an IN to the deployment job. This would mean the .pointer.sourceName would need to be something that could be outputted and overridden.

I'm unclear from the documentation if this possible because the tutorial only mentions updating version fields on OUT resources. Please could you provide some guidance on whether this is possible, and if not how would you recommend doing CloudFormation updates as part of a pipeline.

I currently have:

```
IN: AWS integration ->
                                         runSh          -> OUT: loadBalancer resource -> deploy job
IN: Github repo        ->
```

Also the loadBalancer resource is not being connected to the existing resource in the SPOG view.

Cheers.

**Comment by stuartstevenson** [comment]
Is there any documentation on this error message and why my job would be failing?

`No dependencyHandler for dependency type: OUT loadBalancer`

**Comment by trriplejay** [comment]
That's a great scenario that we plan to support in the future, but unfortunately today having a loadBalancer as an "OUT" is not supported, which is why you see that error message.  There is not a way, currently, to dynamically create a loadBalancer and update your pipeline with the LB's info. It has to be directly added to the loadBalancer resource in the yml.

This is definitely something that we're planning to support/enhance in the near future though.

**Comment by stuartstevenson** [comment]
@trriplejay Thank you for the quick response and clarity on the current state.

**Comment by jessica-pixvana** [comment]
I just tried to use params as an output and this also gives the error `No dependencyHandler for dependency type: OUT params`

It really would be nice to have a list of which resources are supported as outputs

**Comment by avinci** [comment]
@jessica-pixvana @stuartstevenson we introduced a new job type called `runCLI` with this you can achieve your scenario. Let me know if you would like us to sample code this.

**Comment by avinci** [comment]
We have opened up all the resources to be able to added as OUT. There should be no limits on this and you can use the OUTs as INs to other jobs which can do further operations. Please let us know if you need any further information...
