### ISSUE TITLE
Cannot build anything after maintenance

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#3046]
I know there was a system maintenance a few hours ago, and we cannot build anything after that. The build does not even start although we brought our own node.
https://app.shippable.com/runs/57ff92b9a447cb0e00081beb/summary

**Comment by PaulWebbster** [comment]
Yes, after few hours of working after the maintanence the builds stop working once again.

**Comment by LuisMuniz** [comment]
We have the same issue, same setup. We tried switching to standard shippable nodes and the jobs still don't start up.

**Comment by mattclay** [comment]
I'm seeing the same thing. Builds are created, but there are no runs associated with them. They're stuck at waiting with all build minions unused:

https://app.shippable.com/runs/57ff92f1578c830e00e71f09/summary
https://app.shippable.com/runs/57ff932da447cb0e00081bf0/summary
https://app.shippable.com/runs/57ff94febe4b4c1000663f10/summary
https://app.shippable.com/runs/57ff997ab3d1650f00eabf5d/summary

**Comment by lucasmpb** [comment]
Same here.

**Comment by bantonj** [comment]
Same here, just greyness.

**Comment by toshovski** [comment]
same issue here

**Comment by mattclay** [comment]
Builds are working now.

**Comment by manishas** [comment]
closing since this is resolved.

**Comment by Kivol** [comment]
Queue seems like to be stalled again.
