### ISSUE TITLE
I can't delete my account

### ISSUE THREAD

**Issue by ssaar** [Shippable/support#3048]
I've been trying to delete my account, but every time it fails. It says I need to delete the dependencies, so I click delete dependency, and it takes awhile and then it's gone. Then when I click confirm delete it says I need to delete the dependency. The dependency is no longer in the list, but when I refresh the page it shows up again.

**Comment by manishas** [comment]
@ssaar Do you want us to delete your account?

**Comment by ssaar** [comment]
Yes please.

-Stephen

**Comment by trriplejay** [comment]
account has been deleted. closing.
