### ISSUE TITLE
CI builds are not triggered on Github push

### ISSUE THREAD

**Issue by sendyhalim** [Shippable/support#3051]
### Description of your issue:
CI Builds are not triggered on github push/commit. I believe this is related with #3047 

https://app.shippable.com/projects/552c7ec75ab6cc1352c300d8

**Comment by manishas** [comment]
@rageshkrishna can we look into this?

**Comment by rageshkrishna** [comment]
@sendyhalim Can you please check if this is still happening? I see that a webhook build was indeed triggered for your project around an hour ago. Please let me know if you're still running in to this problem.

**Comment by sendyhalim** [comment]
@rageshkrishna Yep it's working now, thanks! 🍻
