### ISSUE TITLE
npm module find failure on shippable but not on Windows

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#3055]
https://app.shippable.com/runs/5802a2578eacbd0f0096248d/1/console

Any thoughts as to why this wouldn't work here but works 100% on Windows?

The module that fails builds on its own on shippable:

https://app.shippable.com/runs/5802a2522bc62c0f007415a9/1/console

**Comment by stephanielingwood** [comment]
Hi @BryanCrotaz,

**Comment by avinci** [comment]
closing this for lack of response
