### ISSUE TITLE
Build failure at setup_env due to improper string escaping

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#3056]
The [build](https://app.shippable.com/runs/58040777dfe1300e00c9e23b) for PR [5280](https://github.com/ansible/ansible-modules-core/pull/5280) is failing at `setup_env` due to improper string escaping.

From the `run` section of the build [script](https://app.shippable.com/runs/58040777dfe1300e00c9e23b/1/script):

``` shell
export COMMIT_MESSAGE="Make find return sample a YAML dict

In the description of the `find` module return value, the sample dict
has its `key=value` strings converted to `key=value: None` in the
web documentation. This commit updates the sample output to a 'real'
dict.

Minor additional edit in the description: \"return list *of* files\"." 
```

The backtick characters in the commit message are in double quotes, which does not prevent them from triggering shell command substitution. This is most likely what is causing this PR to fail to build repeatedly during `setup_env.`

**Comment by bencomp** [comment]
Removing the backticks from the commit message and force-pushing it allowed the build to continue.

**Comment by manishas** [comment]
Thanks for reporting this. We'll look into it and work on a fix.

**Comment by mattclay** [comment]
@manishas, @trriplejay: Is there any ETA on a fix for this issue?

**Comment by manishas** [comment]
Yes, this will be fixed before 12/23.

**Comment by rageshkrishna** [comment]
This should be fixed now. Please let us know if you're still seeing this problem.
