### ISSUE TITLE
Pipelines: Service Downgraded During Upgrade

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3058]
### Description of your issue:

I attempted to deploy a prod service and rather than upgrading the task version is downgraded the number of tasks to 0 and attempted to roll out that way. I find this strange and very broken. All of the other services which I deployed at roughly the same time upgraded appropriately: they rolled two additional tasks in order to replace the two old tasks.

I noticed this in the output:

```
downgrading previous service crm-zp-deploy-crm-latest-100b9ed6-6707-473a-a6da-d3740d51ed22
waiting for downgrade of previous service crm-zp-deploy-crm-latest-100b9ed6-6707-473a-a6da-d3740d51ed22
Running Tasks :2, Pending Tasks:0
Running Tasks :2, Pending Tasks:0
Running Tasks :2, Pending Tasks:0
```

This caused production downtime which I both did not anticipate and had no control over since I had to let Shippable finish doing its thing.

I need to get this fixed ASAP so it does not bite us in the future.

**Comment by trriplejay** [comment]
It looks like this was due to a detected change in load balancer. did you add a load balancer to an existing service? or change its name or some other field that would necessitate a rebuild of the service?

**Comment by BlueDragonX** [comment]
No I've not made any changes to the load balancer.

**Comment by BlueDragonX** [comment]
This happened to me again today in our production environment. It took our entire environment down for about fifteen minutes while connections drained from services.

I've added new deploy tasks which need load balancers but I have not changed any of the existing tasks to the best of my knowledge. I need help debugging this ASAP otherwise I'm going to just have to pull the plug on Shippable's CD pipelines.

**Comment by manishas** [comment]
@BlueDragonX we did implement a fix to our load balancer change detection but since it's happening again, we'll look into it asap. @trriplejay will follow up on this.

**Comment by BlueDragonX** [comment]
The output for the deploy job shows no changes for the load balancer, but it redeployed due to load balancer changes anyways:

```
Comparing manifests for crm-latest
Packages match: true
Replicas match: true
Images match: false
Summary of loadBalancers: -- newlyAdded: 0, -- changed: 0, -- deleted: 0
Summary of cluster: -- newlyAdded: 0, -- changed: 0, -- deleted: 0
Force deployment is: false
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Initialized AWS Adapter.
Deployment flow: serial
Executing deploy type: upgrade
creating container definition
getting previous service
Found previous service: crm-zp-deploy-crm-latest-100b9ed6-6707-473a-a6da-d3740d51ed22
creating task definition
getting service
Service will be deleted and recreated for load balancers to take effect.
```

**Comment by trriplejay** [comment]
@BlueDragonX So you have other deploy jobs also using application load balancing, but this particular deploy job seems to have this issue? is there anything unique about it when compared to your other jobs?   We're looking into this right away.

**Comment by BlueDragonX** [comment]
No, they're all experiencing the issue.

**Comment by trriplejay** [comment]
Ok, we've identified some questionable logic and are planning to release a patch for this tonight.

**Comment by trriplejay** [comment]
Patch is deployed. Let us know if you're having any other issues.

**Comment by BlueDragonX** [comment]
Ok, I'll give it a shot with one of the services that isn't live yet.

**Comment by BlueDragonX** [comment]
That seems to have fixed the problem. I won't be running another full prod release until next Tuesday so I'll let you know if it's all better then.

**Comment by manishas** [comment]
@BlueDragonX I am closing this issue assuming you're not running into this problem any more.
