### ISSUE TITLE
Carnegie Mellon FSE - job was skipped because you have reached your private job limit

### ISSUE THREAD

**Issue by amyz** [Shippable/support#3059]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

Hi, 
Hakan Erdogmus has contacted you regarding the private job limit.  It would be super helpful to get that adjusted.  
Thank you and have a great day!!
Best, 
Amy

**Comment by manishas** [comment]
@amyz this should no longer be a problem. Can you run a build and check?

**Comment by amyz** [comment]
It appears to be building.  Thank you for for quick support!

Best,
Amy

**Comment by manishas** [comment]
:+1:
