### ISSUE TITLE
minions available but pipelines and ci do nothing

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#3061]
Everything seems to be stuck and we are generating a backlog of jobs at the moment.

https://app.shippable.com/subscriptions/578f3c82eeac370c00a23846/ci/dashboard

Is there anything i can do from my side to poke shippable to start working??

**Comment by rageshkrishna** [comment]
We're looking in to this. I'll have an update on this very soon.

**Comment by antoligy** [comment]
Hey, this is blocking my builds too.  Please let us know!

**Comment by rageshkrishna** [comment]
We've identified the problem and corrected it. There was an issue with the build request processor causing it to process messages far, far slower than normal. The service has been reset and it has now processed the complete backlog. Your builds should be running normally now.

Please let me know if you're still seeing issues.

**Comment by KarolAdamiec** [comment]
all fine now.
Thank you!
