### ISSUE TITLE
Pipelines: SPOG Redraw is Brutal

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3063]
### Description of your issue:
Doing something in the SPOG when an event comes in can really wreck your day! It causes a redraw and often re-arranges all of the pipelines in the view.

I now have around 25 deploy tasks which span four environments. They're triggered by a much smaller number of images. Any time a CI build comes down (which is frequent) the SPOG gets re-arranged. There's no guarantee that it will get arranged in the way you expect it.

There appears to be a filter drop-down. I assume that would let me view a subset of my resources/jobs. I've yet to find the documentation that describe this feature, but that would reduce the impact of this bug a great deal.

**Comment by manishas** [comment]
@BlueDragonX the SPOG redraw issue is on our radar and we'll definitely address it soon.

As for the filter, you can define a `flags` tag for any job (or resource). 

```
jobs:
  - name: job_name
    type: manifest
    #Inputs, etc for job
    flags:
      - dv
```

All flags will show up in the `Filter` dropdown and you can see a filtered view of your pipeline. Adding the flag to just one job or resource will show the upstream and downstream jobs as well, so you do not need to add it to every job or resource along the way.

We're working on making sure that this behaves as expected, so any feedback around this will be very helpful!

**Comment by BlueDragonX** [comment]
I've added flags to allow for filtering by service, pipeline, or image. That feature doesn't work the way I would expect it to, but it does solve this issue.
