### ISSUE TITLE
Pipelines: Validation and Testing

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3064]
### Description of your issue:

Currently there's no built-in way to validate and test a pipeline without deploying it. I find this odd given that you're a CI/CD company.

I feel a solution that allows you to validate a branch and execute it in dry-run mode would be superb.

One of my team members suggested creating a separate account that would allow us to QA these things. That doesn't work, though, as you would still be accessing the same cloud resources when triggering a pipeline.

**Comment by manishas** [comment]
@BlueDragonX can you explain what you mean by 'test' the pipeline? Do you mean validate the resources and jobs yml?

**Comment by BlueDragonX** [comment]
I mean validate the YAML files _and_ execute a pipeline as a "dry run" so we know what actions it will take. But we should be able to do this against a PR before approval - just like any code change.

It's important to test code before it's released. The pipeline code should not be any different. However, You do not provide that functionality.

**Comment by BlueDragonX** [comment]
Any update on this?

**Comment by avinci** [comment]
We are currently planning this feature. Let me get back to you on a date on this.

**Comment by ankul-shippable** [comment]
@BlueDragonX We have added support for dry runs for pipelines. Please check the docs [here](http://docs.shippable.com/pipelines/dryrun/). Currently we have added support for dry runs for a branch in a project. Dry run pipelines for a pull request is work in progress, we will update you once that is live.
Please let us know if have any queries. Thanks

**Comment by ambarish2012** [comment]
@BlueDragonX I am closing this issue. If you run into any issues with dry-run mode, please reopen.
