### ISSUE TITLE
Submodule fetch fails in git sync

### ISSUE THREAD

**Issue by apmolsa** [Shippable/support#3066]
Yesterday on second git_sync step our submodule fetching stopped working, it had been working correctly prior to this. I have double checked that the deployment key is set and is right for the submodule repository.

> Fetching submodule flib
> Warning: Permanently added the RSA host key for IP address '104.192.143.1' to the list of known hosts.
> conq: repository access denied. deployment key is not associated with the requested repository.
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by lazebny** [comment]
I had the same issue, cache clearing helped me. https://ibb.co/mNx9qa

**Comment by avinci** [comment]
Please let us know if this is still happening. cache clearing might help depending on what folders you are caching...
