### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3068]
Yesterday I saw [subsequent](https://app.shippable.com/runs/5808ecf33ba98c1000e95239/1/console) [builds](https://app.shippable.com/runs/5808ed0c8eacbd0f00970bcf/1/console) failing because of a memory exhaustion during code coverage generation by PHPUnit:

> Generating code coverage report in PHPUnit XML format ...PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /.../vendor/phpunit/php-token-stream/src/Token/Stream.php on line 161

Any idea how to fix this? I have never seen this issue before in any build.

**Comment by a-murphy** [comment]
I can't determine why you're running out of memory, but you can change what PHP will allow by updating the `php.ini` file.  For example, adding this to your `shippable.yml` will increase the limit from the default 128MB to 256MB:
```
- echo "memory_limit = 256M" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
```

**Comment by mbrodala** [comment]
Thanks that [fixed the build](https://app.shippable.com/runs/580db7f4e5f93e10006b1f8f/1/console). I still wonder why I haven't encountered this before but oh well.
