### ISSUE TITLE
Could not find any repositories for your account

### ISSUE THREAD

**Issue by Tapppi** [Shippable/support#3071]
I am currently evaluating shippable.com for use in our organisation `tuup`. I managed to get some builds off the ground (no success though yet) but now all my organisations and repos have disappeared from shippable. No matter how I sync or re add the integration I only get this message on the front page of shippable.com: 

> Thanks for signing up! We could not find any repositories for your account

I am using this account and the organisation is github.com/tuup

**Comment by Tapppi** [comment]
Okay i guess this is related to #3070

**Comment by rageshkrishna** [comment]
Hi @Tapppi. Thanks for trying us out!

Yes, this is related to the issues that GitHub is having right now. Syncing your account once this issue is resolved will let you see all your projects and builds again.

**Comment by madshostrup** [comment]
Please sync my account as well asap

**Comment by Tapppi** [comment]
@madshostrup the issue is with github's dns provider, not shippable. They can't do jack about it.
