### ISSUE TITLE
Permission denied (public key)

### ISSUE THREAD

**Issue by Tapppi** [Shippable/support#3072]
Hi, we are experiencing issues with git sync since fiddling with the integration settings (due to the dns outage):
https://app.shippable.com/runs/580a275f63e20a0f0087b5ae/1/console

Could you provide steps to fix the key problem in the new interface (everything I found on the subject refer to old interfaces).

Thanks!

**Comment by Tapppi** [comment]
Still getting the same error after resetting and re-enabling github integration? Any clues?

https://app.shippable.com/runs/580a909ee5f93e10006af83f/1/console

**Comment by a-murphy** [comment]
Considering the DNS problems affecting GitHub earlier today, could you try resetting your project again?  It could be that the new deploy key request didn't get through to GitHub.

**Comment by Tapppi** [comment]
Sure, another project is working as expected so I suspect this'll start working soon enough with a reset.
