### ISSUE TITLE
Docker push hangs

### ISSUE THREAD

**Issue by rakshazi** [Shippable/support#3074]
Hello!
When I try to do docker push, build freezes on some layers from 5 to 15 mins
Build log: https://app.shippable.com/runs/580a66c2f057850f005bc8ca/1/console
No scripts called, freezed on docker push

**Comment by avinci** [comment]
is this is still happening? Docker hub is finicky and we have seen this happen when docker hub stop to respond. Please let us know if this is still happening. Also have you tried any other registry and see is this happen there too?

We internally at Shippable moved all our images to AWS ECR. Perf and consistency was the issue.
