### ISSUE TITLE
Migrate resources from one sync repo to another

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#3075]
How do I migrate resources from one sync repo to another? I started out with separate repos, but now I want to combine them. Furthermore, I have dependencies between those repos.

**Comment by avinci** [comment]
a new feature to do this is being implemented this week. There was a manual round about way of doing it but this should be possible with the new feature with relative ease.

**Comment by avinci** [comment]
we have added a new feature to migrate resources from one sync repo to another. Please let us know if you need any further help around this.
