### ISSUE TITLE
Error when adding image from Docker Hub with "." in the name

### ISSUE THREAD

**Issue by bhedge** [Shippable/support#3076]
### Description of your issue:

When adding an image to watch in the Account Settings, an image with "." in the name is not allowed but is a valid image name in Docker Hub.

ERROR MESSAGE: 

> Unable to save lighthouseImage: The image name **company/image.name.title** is invalid. Example: library/ubuntu

**Comment by rageshkrishna** [comment]
@bhedge Sorry about the late reply, but we have completely eliminated this feature. I'm closing this issue because it's no longer relevant.
