### ISSUE TITLE
Request: ability to increment build number

### ISSUE THREAD

**Issue by gappleto97** [Shippable/support#3077]
Is there any way that we could increment our build number?

I'm using two other CI services along with Travis, and Travis is the only one which has a different build number. I'd like to get them in sync.

**Comment by mmacret** [comment]
+1

**Comment by avinci** [comment]
send us your projectId and we can do it 1 time. this is really not a critical feature that many people might need and hence we are going to punt on it. We can do it as a support request as it might be much faster.

**Comment by avinci** [comment]
I am closing this as won't fix. Please submit which projectId needs what number and we can do it as long as the number is higher than what it currently is
