### ISSUE TITLE
Shippable doesn't show repo branches

### ISSUE THREAD

**Issue by fernandowiek** [Shippable/support#3078]
Hi,
I added two repos on my Shippable. One is brand new, with 3 branches, and another is very old, with a lot of branches.
Shippable's only list the branches on the new one. In the older repo, i don't see any branchesl. I did everything in the web interface but nothing works. Do you know why this happening?
Best regards.

**Comment by kanthchandra** [comment]
hi @fernandowiek , Can you go to the project settings page and click on sync button?

**Comment by fernandowiek** [comment]
Hi, @kanthchandra. I did this. Actually, I changed all the option on shippable but nothing changes. My project ID is 57ed436175a4470f00e62f1e. Here are some screenshots: http://prnt.sc/cypu5b http://prnt.sc/cypy7y http://prnt.sc/cypyzp

**Comment by fernandowiek** [comment]
If helps in the troubleshooting: i have 99 branches on my repo.

**Comment by fernandowiek** [comment]
Guys,
I clean up my repo and now I can see the branches. I think i had more branches than Shippable can handle.
Regards!
