### ISSUE TITLE
Cannot make Chrome or Firefox to work with Behat and Selenium

### ISSUE THREAD

**Issue by Herod** [Shippable/support#3080]
I am trying to execute a Behat test with help of selenium and Chrome or Firefox.
The problem is that browsers are not starting. I am always getting the error for Chrome:

```
  [Behat\Mink\Exception\DriverException]                                                                                                                                                         
  Could not open connection: unknown error: Chrome failed to start: exited abnormally                                                                                                            
    (Driver info: chromedriver=2.13.307649 (bf55b442bb6b5c923249dd7870d6a107678bfbb6),platform=Linux 3.19.0-51-generic x86_64) (WARNING: The server did not provide any stacktrace information)  
  Command duration or timeout: 60.06 seconds                                                                                                                                                     
  Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'                                                                                                                
  System info: host: 'ea40b59dca15', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-51-generic', java.version: '1.7.0_80'                                             
  Driver info: org.openqa.selenium.chrome.ChromeDriver              
```

before_install:

```
    - curl -o /tmp/selenium.jar -L http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar

    - curl -o /tmp/chromedriver.zip -L http://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
    - unzip /tmp/chromedriver.zip -d /home/shippable/bin
    - chmod +x /home/shippable/bin/chromedriver
    - echo '#!/bin/bash' | sudo tee /usr/bin/google-chrome
    - echo 'exec /usr/bin/chrome --no-sandbox --disable-gpu \"$@\"' | sudo tee -a /usr/local/bin/google-chrome
    - sudo chmod +x /usr/local/bin/google-chrome
    - Xvfb :1 -screen 5 1024x768x8 +extension RANDR &
    - export DISPLAY=:1


```

script:

```
    - ./bin/console server:start -n
    - ./vendor/behat/behat/bin/behat

```

**Comment by stephanielingwood** [comment]
Hi @Herod,

If you haven't looked at it yet, I'd suggest basing your yml off the one in our [docs on using Selenium](http://docs.shippable.com/ci/services/selenium/). Those docs also have a link to a sample project that uses Selenium with nightwatch.json to select Chrome or Firefox as the browser.

Also, from the exampel you provided, it looks like you're using our old yml format with the `before_install` and `script` sections. While that will work, I'd encourage you to use our [newer yml format](http://docs.shippable.com/ci/shippableyml/), as it gives you more options.

Finally, if you're trying to do something specific with Behat, Selenium, Chrome, and Firefox, it may be easiest to create a custom image with those services set up the way you want, and then [use that custom image](http://docs.shippable.com/ci/shippableyml/#pre_ci_boot) in your build. You're welcome to use our [node image](https://hub.docker.com/r/drydock/u14nodall/) that has services installed as a starting place; to see what's in the image, check out the [repo on GitHub](https://github.com/dry-dock/u14nodall).

**Comment by Herod** [comment]
it's not resolved. I have abandoned the issue since i found a better and workable way to do it.
