### ISSUE TITLE
[frontend] console size

### ISSUE THREAD

**Issue by eddwardo** [Shippable/support#3081]
The console size with the build output is fixed, no matter how big the resolution or window is. It is quite annoying css bug. Could the console be adaptive to the screen size?
I am currently doing it by setting `.ship-console-fixed` to `1000px` which is bad, but works for me.

**Comment by BlueDragonX** [comment]
I second this. My main monitor as an LG Ultrawide. The console output is tiny.

**Comment by avinci** [comment]
this has been fixed in the new UI we launched a couple of weeks ago. Please switch the UI to new UI if you have not been already moved. Everyone will be moved in the first week of July.
