### ISSUE TITLE
Cannot start selenium on nod14all

### ISSUE THREAD

**Issue by toshovski** [Shippable/support#3084]
Selenium server requires java 8 and nod14all has only java 7. Is there a newer image, that also contains java 8? 

> ---
> ## selenium-standalone installation finished
> 
> Exception in thread "main"
> java.lang.UnsupportedClassVersionError: org/openqa/grid/selenium/GridLauncherV3 : Unsupported major.minor version 52.0
> 
>   at java.lang.ClassLoader.defineClass1(Native Method)
>   at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
> 
>   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
> 
>   at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
> 
>   at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
> 
>   at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
>   at java.security.AccessController.doPrivileged(Native Method)
> 
>   at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
> 
>   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
> 
>   at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>   at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
> [20:15:04] 'wct:local' errored after 42 s
> [20:15:04] Error: Selenium server did not start.Another Selenium process may already be running or your java version may be out of date.
> npm ERR! Test failed.  See above for more details.

**Comment by a-murphy** [comment]
The current Java image, `drydock/u14javall:prod`, has Java 8 installed if your build would run on a Java image (it also has Node 0.10.37,  Python 2.7.6, and Ruby 2.2.1).  Or there is an updated version of the image you are currently using, `drydock/u14nodall:tip`, with Java 8.  However, the `tip` tagged images have not yet been completely tested and it's possible that some options may not work with these images.  In either case, directions to specify the image to use in your shippable.yml file are available [here](http://docs.shippable.com/ci/shippableyml/#pre_ci_boot).

**Comment by toshovski** [comment]
Node 0.10.37 is outdated. They will end also the support of node 0.12 by the end of the year. Since April 2015 java 7 is also not anymore supported and many java based applications like the selenium server require java 8. 

When will be the u16nodall avaliable?

**Comment by avinci** [comment]
this is going to be released this week. You should have all the updated images and moving forward we are updating our images every month so that we dont fall behind on this. Thanks for your patience.

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.
