### ISSUE TITLE
App not loading on shippable.com

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#3092]
The app not loading on app.shippable.com. Can you have a look? Thanks

**Comment by manishas** [comment]
We're working on this problem. It's intermittent right now.

**Comment by manishas** [comment]
Are you still seeing this?

**Comment by jeppefrandsen** [comment]
Yes, still the same. Not loading the dashboard

**Comment by jeppefrandsen** [comment]
Now it seems to work! Thanks
