### ISSUE TITLE
Container.image contains invalid characters

### ISSUE THREAD

**Issue by tjomk** [Shippable/support#3094]
While trying to deploy to AWS ECR getting the following error: Container.image contains invalid characters.

There's not much other text to try and figure out what's in the name that is causing this.

- Link to the build failure: https://app.shippable.com/subscriptions/5804b7490492dd0f005ea82b/pipelines/builds/5817153483c1a50e002b060f/consoles

**Comment by a-murphy** [comment]
The error refers to the name or tag of the Docker image AWS has been asked to deploy.  This is the `sourceName` and `versionName` of the image resource in your `shippable.resources.yml` file.  Could you check that the images in your `shippable.resources.yml` file have valid Docker image names specified in the `pointer` sections and tags in the`seed` sections [as documented here](http://docs.shippable.com/pipelines/resources/image/)?  After updating your image resources, you'll have to re-run the manifest job before the deploy job to get the updated resources.

**Comment by manishas** [comment]
@tjomk let us know if you need more help.
