### ISSUE TITLE
Cannot see a project that is shared with me

### ISSUE THREAD

**Issue by ibratoev** [Shippable/support#3096]
When I try to see a build for a project that is shared with me, for example: https://app.shippable.com/runs/581860354e13e60f003b7ee0/ i get an error: "(Id: 4004) Run not found for id: 581860354e13e60f003b7ee0".

**Comment by a-murphy** [comment]
Could you try synchronizing your account?  It looks like the subscription that project is in changed at some point, which is likely why you aren't able to see it.  The gear icon in the top right corner of the page will take you to the account settings page where there is a green "sync" button.

**Comment by ibratoev** [comment]
@a-murphy Tried sync-ing - didn't work. Still I have no access to the project.

**Comment by a-murphy** [comment]
We'll look into why the sync didn't work, but have corrected your permissions.  Would you mind trying again?

**Comment by ibratoev** [comment]
Thanks, @a-murphy. All works fine.
