### ISSUE TITLE
All minions show in-use but no active jobs? What is consuming our minion?

### ISSUE THREAD

**Issue by prasek** [Shippable/support#3098]
Minion usage shows all in-use, but we have no active jobs and a bunch of queued jobs stuck in the waiting state:
https://app.shippable.com/subscriptions/578558ac3be4f4faa56c9584

Not sure what is consuming the minion. Have tried cancelling all pending jobs with no luck.

Has been happening since yesterday afternoon. 

Please advise.

**Comment by a-murphy** [comment]
One of the jobs in a canceled run wasn't properly canceled.  It should be working now.

**Comment by prasek** [comment]
Perfect, thanks!
