### ISSUE TITLE
API does not return job logs anymore

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#3100]
Hello,

The run in question is:

  https://app.shippable.com/runs/5818d442aae6c30f0015b809/1/console

The log information appears in the UI console but I cannot retrieve it from the API, I get:

  404 Cannot GET /jobs/5818ce00d1184e0f002e1c9c/consoles/download

requesting the same URI with the usual credentials working with other endpoints. The URL seems to match documented one:

  http://docs.shippable.com/api/job/#download-console-logs

The code fetching log information was definitely working last week. This project was created a couple of hours ago, but it seems to fail with older projects too.

**Comment by a-murphy** [comment]
Could you try the `GET /jobConsoles?jobIds=5818ce00d1184e0f002e1c9c&download=true` route?  It should return consoles in the same format as the previous download route.

**Comment by pmezard** [comment]
It works, thanks. Should it be considered the new official way to retrieve logs?

**Comment by manishas** [comment]
@pmezard yes, i will make sure docs are updated.

**Comment by manishas** [comment]
i have updated docs to show the correct API. Closing this issue.

**Comment by pmezard** [comment]
Hello, I am reopening this issue as the new route seems to be broken again. Without changing any of our code using the API, we now get:
```
404
Cannot GET /jobConsoles?download=true&amp;jobIds=5845466c9d1f3e0f00577153
```
Documentation has not changed though:

http://docs.shippable.com/api/job/#download-console-logs

**Comment by pmezard** [comment]
Commenting does not seem to reopen, I will create a new issue.

**Comment by manishas** [comment]
this has been fixed. thanks for your help!
