### ISSUE TITLE
ENV variables

### ISSUE THREAD

**Issue by magicalbanana** [Shippable/support#3104]
### Description of your issue:
I can't seem to load ENV VARs though my application. It should load it before any tests is run.
Not sure if you guys are familiar with [dotenv](https://github.com/bkeepers/dotenv).

- Link to the build failure
[build](https://app.shippable.com/runs/581750879e265b0f00d3b828/1/console)

- Scripts called from the yml (optional)

**Comment by manishas** [comment]
@a-murphy can you look into this?

**Comment by a-murphy** [comment]
Adding `dotenv-rails` to the Gemfile and 
```Ruby
require 'dotenv'
Dotenv.load
```
as documented is working for me.

Could you check that the `.env` file is in the repository and not excluded by a `.gitignore` file?

**Comment by magicalbanana** [comment]
@a-murphy still doesn't work. If you could try it with a rails app and not just sinatra or plain ol' ruby that would be great.

**Comment by a-murphy** [comment]
I've tried updating a sample project using Rails to use an environment variable with dotenv, and it works as well.  I just added a `.env` file,  the `gem 'dotenv-rails', :groups => [:development, :test]` line to the top of the Gemfile, and a test to check that the environment variable was set.

**Comment by magicalbanana** [comment]
@a-murphy are you running any spec because that's where mine fails.

**Comment by stephanielingwood** [comment]
Hey, @magicalbanana. We tried this with two sample projects; one using rspec (without rails), and the other using minitest-reporters (rails); both worked. Not sure what's going on in your testing setup; maybe http://stackoverflow.com/questions/29823257/env-not-being-loaded-in-test-environment-in-rails-with-rspec would give you some more ideas?

**Comment by magicalbanana** [comment]
@stephanielingwood sorry it was my mistake, I didn't commit my .env file. Thanks for all the help!

**Comment by stephanielingwood** [comment]
@magicalbanana Hate it when that happens. ;) Glad you got it figured out - let us know if you have any other questions.
