### ISSUE TITLE
u16nodall pulls the image every time I build

### ISSUE THREAD

**Issue by toshovski** [Shippable/support#3105]
I asked last week about [u16nodall](https://github.com/Shippable/support/issues/3084), when is going to be official. I switched to u16 and it works fine for my need, but it takes over 30 Minutes to pull the docker image from the registry. Is there a way to cache the docker image?

Currently we have 4 minions, but we evaluate, if we can use it across multiple teams and this issue might be a stopper.

**Comment by manishas** [comment]
We plan to include the u16 images on our build machine AMIs in the next 2-3 weeks. At that time your image will no longer be pulled each time. I'll let you know when this is implemented.

**Comment by toshovski** [comment]
Is there any progress on that issue?

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.
