### ISSUE TITLE
CRITICAL: Got super user rights after sign up

### ISSUE THREAD

**Issue by philipstanislaus** [Shippable/support#3106]
I assume this is a severe issue, please correct me if I am wrong: 

after signing up, I got access to a admin menu icon. I was able to stop nodes arbitrarily, get access to private SSH keys and so on. Here is a screenshot: 

![bildschirmfoto 2016-11-02 um 17 36 51](https://cloud.githubusercontent.com/assets/6912756/19938014/b3e17a20-a123-11e6-8eaa-3fadd2ecfe35.png)

Hope this issue helps you to improve your service! 

Best regards

Philip

**Comment by manishas** [comment]
We're looking into this and have removed your access.  Thanks for the heads up!
