### ISSUE TITLE
Errors accessing app.shippable.com

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#3109]
Attempting to access https://app.shippable.com/ while logged in to GitHub results in errors like:

```
Error getting account model: [object Object]
```

```
(Id: 2000) invalid apiToken
warn: common|validateCaller|route:/subscriptions|_getAccountIdByAccountToken
```

**Comment by mattclay** [comment]
Same problem as reported in issue #3108.

**Comment by manishas** [comment]
We're working on this. Pls look at the update on http://status.shippable.com/

**Comment by manishas** [comment]
ETA for everything to come up is 10 mins

**Comment by manishas** [comment]
Tracking this issue in https://github.com/Shippable/support/issues/3111
