### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by bennykstudy** [Shippable/support#3110]
### Description of your issue:
Earlier, got an error when clicking Login -> Bitbucket
Now, clicking Login times out.
Need to deploy, please help, thanks!
Ben

**Comment by manishas** [comment]
http://status.shippable.com/

ETA for everything to be back up is about 10 mins.

**Comment by manishas** [comment]
Tracking this issue in https://github.com/Shippable/support/issues/3111
