### ISSUE TITLE
http://shippable.com doesn't load

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3112]
http://shippable.com

redirects me to: https://app.shippable.com/

and then I get:
```
The app.shippable.com page isn’t working

app.shippable.com didn’t send any data.
ERR_EMPTY_RESPONSE
```

(Using Chrome Version 54.0.2840.71 (64-bit))

I try it on Firefox with no previous shippable cookies and I get:
```
Secure Connection Failed

The connection to the server was reset while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

I saw your email about invalidating API tokens, but this appears that the entire site is down.

**Comment by mattclay** [comment]
@gitglacier Looks like this is covered by issue #3111 stating:

`The service is currently down and will be back up in 10 mins.`

**Comment by gitglacier** [comment]
Closing per prior #3111
