### ISSUE TITLE
Pipelines job hangs

### ISSUE THREAD

**Issue by navymaker** [Shippable/support#3113]
I'm started deploy job about 40 minutes ago, and it hangs after "Generating Job" status. Minion is still in use, and I can't run any other jobs.

**Comment by a-murphy** [comment]
Your newer jobs should be running now.

**Comment by manishas** [comment]
@navymaker i am closing this issue but let us know if your builds still aren't running.

**Comment by navymaker** [comment]
Old build is still stale in running status, last update - Yesterday at 4:48 PM
