### ISSUE TITLE
GitHub access issues

### ISSUE THREAD

**Issue by ben-pushspring** [Shippable/support#3116]
Hi,
I'm trying to access shippable via GitHub. I was able to access all of the projects prior to the login reset earlier today. I cleared my cookies. We had a different team member sign in to shippable and re-enable the builds. However, when I try to access shippable, I get stuck in an authorization loop. We haven't changed any permissions for my account. It asks me to authorize commit status read and write access and deployments. Even with Owner access for the organization in GitHub, I still end up in the authorization loop.

![image](https://cloud.githubusercontent.com/assets/16885225/19951517/e08a08ec-a11b-11e6-94e8-0fc7278e4be6.png)

**Comment by manishas** [comment]
We're looking into this...

**Comment by manishas** [comment]
@ben-pushspring Login should work now. Can you please try it and confirm that it works?

**Comment by ben-pushspring** [comment]
I'm now able to login, but the project permissions seem to be off. I can't access repos that are part of the organization:

![image](https://cloud.githubusercontent.com/assets/16885225/19953579/c4c0cf9a-a12c-11e6-8742-46f318f88840.png)

**Comment by a-murphy** [comment]
It looks like the last time your account was synchronized was during the earlier error.  Could you try going to the account settings page (the gear in the top right corner) and clicking the "sync" button?  That will update your project permissions.

**Comment by ben-pushspring** [comment]
All clear. Thanks so much for your help!
