### ISSUE TITLE
Webhook stopped, used to work without issues

### ISSUE THREAD

**Issue by willyyeo** [Shippable/support#3117]
Build stopped working and when clicking on "Machine Images: -> Stable(Default)" ..

Link to build :
https://app.shippable.com/subscriptions/562ddce81895ca44742102a6/settings/options

With the error :
(Id: 4001) subscription.update failed with error: insert or update on table "subscriptions" violates foreign key constraint "subscriptions_systemMachineImageId_fkey"
verbose: subscriptions|put|callerId:571d906e2a8192902e1dcc28|subscriptionId:562ddce81895ca44742102a6|_updateSubscription

**Comment by manishas** [comment]
@ric03uec can we look into this?

**Comment by christopherlongden** [comment]
I am having same problem I am getting a response of "Queuing run" but nothing is appearing in shippable:

HTTP status: 200
Elapsed time: 440ms
Request time: a few seconds ago (Thursday, November 3rd 2016, 9:26:52 am)
Headers
Content-Length	25
Access-Control-Allow-Headers	Accept,Content-Type,Authorization,Cookie
X-Powered-By	Express
Vary	X-HTTP-Method-Override
Connection	keep-alive
ETag	W/"19-J669BQy0W3dtiC1T4qFnJA"
Access-Control-Allow-Credentials	true
Date	Thu, 03 Nov 2016 09:26:52 GMT
Access-Control-Allow-Origin	*
Access-Control-Allow-Methods	GET,PUT,POST,DELETE
Content-Type	application/json; charset=utf-8
Body
{
  "message": "Queuing run"
}
Request
Attempt type: Manual resend
Headers
X-Request-UUID	9fcb55a3-c04c-4947-aaad-c182b4a6f4ca
X-Event-Key	repo:push
User-Agent	Bitbucket-Webhooks/2.0
X-Attempt-Number	2
X-Hook-UUID	375fa252-e620-4d20-856f-2ae7469c105d
Content-Type	application/json

**Comment by mbrodala** [comment]
I can confirm the issue with [this project](https://app.shippable.com/projects/5720c8e62a8192902e1e1c46/) and also see `Queuing run` in the hook response without any build started.

**Comment by mbrodala** [comment]
Our builds seem to be triggered normally now, we'll monitor the current state.

**Comment by christopherlongden** [comment]
No progress on mine. Just tried again, still getting the same response in that the build is queued but I see nothing:

HTTP status: 200
Elapsed time: 463ms
Request time: 3 minutes ago (Thursday, November 3rd 2016, 11:50:35 am)
Headers
Content-Length	25
Access-Control-Allow-Headers	Accept,Content-Type,Authorization,Cookie
X-Powered-By	Express
Vary	X-HTTP-Method-Override
Connection	keep-alive
ETag	W/"19-J669BQy0W3dtiC1T4qFnJA"
Access-Control-Allow-Credentials	true
Date	Thu, 03 Nov 2016 11:50:35 GMT
Access-Control-Allow-Origin	*
Access-Control-Allow-Methods	GET,PUT,POST,DELETE
Content-Type	application/json; charset=utf-8
Body
{
  "message": "Queuing run"
}
Request
Attempt type: Initial attempt
Headers
X-Request-UUID	7ae19794-bc77-4385-a587-5eb926ec67fb
X-Event-Key	repo:push
User-Agent	Bitbucket-Webhooks/2.0
X-Attempt-Number	1
X-Hook-UUID	375fa252-e620-4d20-856f-2ae7469c105d
Content-Type	application/json

**Comment by henkvanramshorst** [comment]
We have the same problem with the bitbucket/shippable integration. Builds are not initiated when pushing to bitbucket.

**Comment by christopherlongden** [comment]
Still no joy. Deleted the Webhook in Bitbucket and then did a sync in Shippable to re-create. Still the same behaviour; web-hook requests are created, a 200 response comes back with "Queuing Run" and nothing appears in my project(s) in Shippable UI.

**Comment by henkvanramshorst** [comment]
We just managed to solve the problem.

Yesterday all our builds started to fail. This morning I received an email from shippable about the security issue. I removed cookies and logged in again. Now the builds didn't even start. Someone else from my team just tried the same thing (removing cookies and loggin in) and now everything works just fine.

Maybe this might help..

**Comment by manishas** [comment]
Sorry for the delay... we're going to look into this right away. 

@henkvanramshorst are you an owner of the Project in Bitbucket? If not, was the other person from your team who logged in an owner?

**Comment by henkvanramshorst** [comment]
@manishas The other person is the one who created the shippable account, so I guess he is the owner. But the email about the security issue was sent to me, not to him.

**Comment by manishas** [comment]
@christopherlongden can you try syncing your account and seeing if that helps?

**Comment by christopherlongden** [comment]
@manishas - I have tried that, but I tried again, same problem. Output from bitbucket web hook is below:

Response from https://55fb46f61895ca4474162f26:F5FXKYhNx8dDL3yh@api.shippable.com/projects/55fb46f61895ca4474162f26/newBuild
HTTP status: 200
Elapsed time: 672ms
Request time: 3 minutes ago (Thursday, November 3rd 2016, 4:20:59 pm)
Headers
Content-Length	25
Access-Control-Allow-Methods	GET,PUT,POST,DELETE
X-Powered-By	Express
Vary	X-HTTP-Method-Override
Connection	keep-alive
ETag	W/"19-J669BQy0W3dtiC1T4qFnJA"
Access-Control-Allow-Credentials	true
Date	Thu, 03 Nov 2016 16:21:02 GMT
Access-Control-Allow-Origin	*
Access-Control-Allow-Headers	Accept,Content-Type,Authorization,Cookie
Content-Type	application/json; charset=utf-8
Body
{
  "message": "Queuing run"
}
Request
Attempt type: Initial attempt
Headers
X-Request-UUID	3f4adb3c-d8bc-4606-bb18-bf3dcf234bb2
X-Event-Key	repo:push
User-Agent	Bitbucket-Webhooks/2.0
X-Attempt-Number	1
X-Hook-UUID	0f03653f-8eda-49e2-955c-bbe17bec978d
Content-Type	application/json

**Comment by ric03uec** [comment]
@christopherlongden we've fixed the project tokens and future webhooks should work now. can you please test and verify.

**Comment by christopherlongden** [comment]
@ric03uec that did the trick. Thanks.

**Comment by ric03uec** [comment]
@christopherlongden @henkvanramshorst @mbrodala  im closing this since builds are running now. please re-open if you run into the same issue again
