### ISSUE TITLE
Problem with bitbucket integration

### ISSUE THREAD

**Issue by henkvanramshorst** [Shippable/support#3118]
### Description of your issue:
For the past 22 hours our automatic builds in bitbucket failed, probably because of the security issue. After removing cookies and login in on shippable, the builds don't start at all.

**Comment by rollcat** [comment]
*Insert obligatory "me too" message*

**Comment by mbrodala** [comment]
@henkvanramshorst Is this the same as #3117? If yes, then please join us there. :-)

**Comment by henkvanramshorst** [comment]
@mbrodala It seems to be the same problem.
