### ISSUE TITLE
Can't connect to bitbucket for certain projects 

### ISSUE THREAD

**Issue by flipbug** [Shippable/support#3119]
Hi,

It seems that there is something wrong with our deployment keys. Some of our projects aren't able to fetch the repository from bitbucket since yesterday. Other projects can be build without issues even though they have the same deployment keys set on bitbucket...

And if i try to reset a project i get the following error:
syncProjectById for :id 5615312f1895ca44741abdda returned error: GET /projects/5615312f1895ca44741abdda/sync?force=true returned 504
error: projects|resetById|callerId:56ab6ca11895ca447472ed1d|projectId:5615312f1895ca44741abdda|_syncProjectById

Project ID, which can't connect: 5615312f1895ca44741abdda
Project ID, which works fine: 568bc4871895ca447467918e

Subscription ID 5445fdccb904a4b21567c286

**Comment by manishas** [comment]
@a-murphy can we look into this?

**Comment by a-murphy** [comment]
I've updated that project so that it should be able to sync now.  Could you try resetting your project again?

**Comment by flipbug** [comment]
@a-murphy @manishas After being able to reset the project, everything works fine 👍 .
Thanks for your help.
