### ISSUE TITLE
Support C/C++ projects (at least allow builds to start)

### ISSUE THREAD

**Issue by tkelman** [Shippable/support#312]
At the moment a project with `language: cpp` (I didn't test `language: c` but I'm guessing it does the same) won't build in Shippable, I have to lie and say my project is something else like Ruby or Python and make sure none of the default build steps for those specific languages get executed.

You shouldn't have to do too much for this, since the minions presumably already have `build-essential` installed. Would be cool to install clang and add `CC=clang`, `CXX=clang++` to the build matrix if I ask for `compiler: clang`, but I can do that manually if I really need to. And some default choices for build steps to be consistent with what Travis does might also make sense.

The service did eventually work well though, builds about twice as fast as Travis once I got my test case up and running. I did stumble over other previously reported issues, like shell variables not persisting from one line of yml to the next, and needing to wait for the build to finish before being able to see any of the log. Could you maybe do something clever with `tee` there?

**Comment by wamatt** [comment]
Would anyone that has this C/C++ working, mind sharing their YML?

**Comment by tkelman** [comment]
I think https://github.com/tkelman/julia/blob/4ac0c544a643c8cfda4b1e8a06f367307c327b8c/shippable.yml may have worked, though it was months ago. This should've been an easy feature to add, I'm amazed it's still open.

**Comment by manishas** [comment]
@tkelman I agree that it's not difficult to add it. We've just been slightly more focused on making the service more robust + completing e2e workflows for the scenarios we do support. I'll make sure we have this on our radar soon.

**Comment by larsbrinkhoff** [comment]
@wamatt This worked at the time:
https://raw.githubusercontent.com/larsbrinkhoff/lbForth/7940c96c5d0e357ae97a00bc8c571ef365bcc005/.travis.yml

**Comment by wamatt** [comment]
ty @larsbrinkhoff & @tkelman

**Comment by larsbrinkhoff** [comment]
@manishas @rageshkrishna Any update on this?

**Comment by codemercenary** [comment]
It would be nice to have this feature, I'd like to migrate to Shippable from Travis because your images are more up to date than what Travis has.

**Comment by manishas** [comment]
Closing as dup of #105 which consolidates requests for all languages.
