### ISSUE TITLE
Shippable not getting new commits from github

### ISSUE THREAD

**Issue by ricardoon** [Shippable/support#3120]
Shippable stopped to sync with new commits to github unexpectedly..
I tried to change the Github API Token, but it didn't worked out.
Can you help me?

**Comment by Kirtap** [comment]
I had that happen to me before, I solved it by going in the **project** settings and hit the reset button. This will redeploy the webhook.

**Comment by ricardoon** [comment]
@Kirtap you are the man!! thanks..
