### ISSUE TITLE
We have jobs running that never end and a CI build that cannot provision a node

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#3121]
Following the security issue, we did reset all our API token, cleared our cookies and re-logged in. We however have deploy jobs hanged and CI builds waiting on provisioning a node. Can someone at shippable help. Thanks

Project is mxitechnologies

regards,

Patrick

**Comment by Kirtap** [comment]
We are currently not able to trigger any deployment. Anyone can assist here? thanks

**Comment by manishas** [comment]
@Kirtap we're looking into this...

cc @ric03uec

**Comment by Kirtap** [comment]
Thanks, We did try to delete everything in our CD and re-sync but that did not work

**Comment by Kirtap** [comment]
![image](https://cloud.githubusercontent.com/assets/4245982/19980205/8e374eca-a1d3-11e6-9a2f-b57f54402feb.png)

Tried to delete everything to redo out CD and I cannot add a Synch repository anymore.

**Comment by trriplejay** [comment]
@Kirtap did you do the hard-delete as well? it looks like this error indicates that the name of the syncRepo resource that you're trying to add already exists.  If your resource is still in the "Deleted" list, can you try fully deleting it?

If that's not the case, we will look into it further.

**Comment by Kirtap** [comment]
Started to delet eeverything but got errors

![image](https://cloud.githubusercontent.com/assets/4245982/19981913/3a94cfca-a1da-11e6-918a-22c512b9ca4b.png)

**Comment by Kirtap** [comment]
![image](https://cloud.githubusercontent.com/assets/4245982/19981960/6bbae27e-a1da-11e6-8796-ffa4c504ff08.png)

Same thing for all remaning jobs and resources

**Comment by Kirtap** [comment]
Even deleted the ECS integration with no luck. We are stuck right now with no way to deploy. 
I also noticed we have 1 minion running but no idea what it is doing as we have nothing running now.

**Comment by trriplejay** [comment]
we're working on cleaning this up for you. I'll let you know once we're done, and then you can try adding your sync repo again.

**Comment by Kirtap** [comment]
thanks

**Comment by trriplejay** [comment]
@Kirtap hey, you should be all cleaned up now. can you try adding your syncRepo again?

**Comment by Kirtap** [comment]
all good now. thanks...

**Comment by trriplejay** [comment]
closing as resolved. let us know if you run into anything else.
