### ISSUE TITLE
Trouble Adding Project to Integration

### ISSUE THREAD

**Issue by herriojr** [Shippable/support#3124]
(Id: 4001) subscriptionIntegration not found for :id 2583
verbose: subscriptionIntegrations|putById|callerId:576d7cea561e0a0c00b08d61| subscriptionIntegrationId:2583|_getSubscriptionIntegration

Go to team
Click settings
Click integrations
Choose integration
Choose project to add
Click Save (then see this error)

**Comment by manishas** [comment]
@herriojr we made some changes due to which only subscription owners can add integrations. We're working on changing this, but in the meantime, can you ask an owner to add the integration? Thanks!

**Comment by herriojr** [comment]
@manishas We've attempted with both the owner of the subscription and the user that enabled the integration and neither work. Thanks!

**Comment by herriojr** [comment]
@manishas is there a timeframe on this -- we are unable to push new apps at the moment

**Comment by trriplejay** [comment]
We're actively working on this and should have a solution deployed soon.

**Comment by trriplejay** [comment]
@herriojr this should be resolved now. Could you try again and let us know if you're still seeing errors?

**Comment by herriojr** [comment]
It's still an issue under my account, I'll try with the other account when the account owner gets in.

**Comment by trriplejay** [comment]
Only the account that created the integration from the account settings page will be able to add it to the subscription.

If you were the original creator of the account integration, can you try going to your account settings and clicking the "sync" button? it's possible that your permission level has not been updated since we deployed the fix.

**Comment by herriojr** [comment]
@trriplejay awesome, thanks, we can add them now!

**Comment by trriplejay** [comment]
glad it's working! let us know if you need anything else.
