### ISSUE TITLE
Provisioning is taking a long time

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3125]
Provisioning is taking a long time. (It's at 16 minutes! Still waiting for it to start....)

https://app.shippable.com/runs/581bb472b7d4350f00491420/1/console

**Comment by trriplejay** [comment]
are you still seeing this issue? typical provisioning time should be in the 3-5 minute range, but there are occasionally exceptions.

**Comment by manishas** [comment]
Closing this issue. @gitglacier please let us know if you are still seeing long provisioning times.
