### ISSUE TITLE
nonresponsive UI: cannot login,cannot do anything

### ISSUE THREAD

**Issue by magwas** [Shippable/support#3126]
At https://app.shippable.com/ I see the following message:
Error getting account model: [object Object]

The wheel what I normally see while the page is loading is rotating there ad infinitum.

on the javascript console I see the following:

Navigated to https://app.shippable.com/
api.shippable.com/accounts:1 GET https://api.shippable.com/accounts 401 (Unauthorized)
api.shippable.com/subscriptionAccounts?:1 GET https://api.shippable.com/subscriptionAccounts? 401 (Unauthorized)
api.shippable.com/subscriptions?:1 GET https://api.shippable.com/subscriptions? 401 (Unauthorized)
api.shippable.com/projectAccounts?:1 GET https://api.shippable.com/projectAccounts? 401 (Unauthorized)

If I click "Sign up" the exact same thing happens (including javascript errors).

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
Have you tried clearing your cookies? Or going to https://app.shippable.com/logout?

**Comment by magwas** [comment]
Going to the logout page have solved my problem. Thank you.
