### ISSUE TITLE
Cannot add sync repository for pipeline

### ISSUE THREAD

**Issue by PaulWebbster** [Shippable/support#3127]
I cannot add sync repository for pipeline. I get following error when i try to do that:

![add_resource_error](https://cloud.githubusercontent.com/assets/7093147/19987896/99eb33e2-a1da-11e6-81f7-0887cfc5f5a3.png)

Should I do something with my Github integration?

**Comment by trriplejay** [comment]
It looks like the selected subscriptionIntegration does not have the required privileges to get/post webhooks to the github project. Can you make sure that the accountIntegration associated with that subscriptionIntegration has owner-level permission?

**Comment by PaulWebbster** [comment]
In integrations on github I see something like this:

![permissions](https://cloud.githubusercontent.com/assets/7093147/19988217/47ed3426-a1dc-11e6-94b3-0141fc4a75e5.png)

How can I check the privileges to get/post webhooks in more detailed way?

**Comment by trriplejay** [comment]
on your subscription settings page, there is an 'integrations' tab.  In that list of integrations, you should have an integration named "github".  This integration is tied to to a github account that does not have the correct permissions level.  

If you click "edit" on that github item, you can choose an accountIntegration from the dropdown to use for that subscription.  Whichever account integration is currently selected does not have enough access to the organization.

**Comment by trriplejay** [comment]
Actually, I see your other support issue. You may not have the correct permissions to perform this edit.  We are working at correcting the recent change to permissions change that is causing these problems.  

In the meantime, someone who is considered an admin of the organization will need to log in, go to the settings tab in this subscription, and change the accountIntegration to use their admin-level integration.  This will have the permissions needed to add webhooks to the project.

**Comment by PaulWebbster** [comment]
Thanks, now I understand. Yes it helps. But things goes complicated with the new  security update.
