### ISSUE TITLE
Resources are not visible when adding EventTrigger

### ISSUE THREAD

**Issue by PaulWebbster** [Shippable/support#3128]
Hi,

I sync repository with pipeline elements like:
* resources
* jobs
* triggers

I see all this resources in SPOG however when I try to add EventTrigger the list is empty:
![trigger resource](https://cloud.githubusercontent.com/assets/7093147/19989502/411e681a-a1e4-11e6-8a91-9640d349d663.png)
This is view from SPOG:
![spog](https://cloud.githubusercontent.com/assets/7093147/19989520/646e6aa4-a1e4-11e6-8537-eff11fbfaee4.png)

Any ideas what I can do wrong?

**Comment by trriplejay** [comment]
It looks like you don't have any resources of type "image". an eventTrigger right now only supports "image" resources.

Usually this means your build pushes an image tag, and then this new tag gets associated with the pipelines image resource.

Here's some documentation on how this setup should work: http://docs.shippable.com/tutorials/pipelines/connectingCiPipelines/#connecting-ci-to-pipelines

**Comment by PaulWebbster** [comment]
I bad, thanks for fast response I omit this one.

**Comment by PaulWebbster** [comment]
Ok, I see that the image resource can only trigger manifest job. I would like to trigger runSh job after the CI build is done. Is this possible in any way?

**Comment by trriplejay** [comment]
actually it's the image resource that is getting triggered.  If you list this resource as an IN to your runSh job, it will trigger that job whenever the image chages. It is not limited to a manifest type job.

**Comment by PaulWebbster** [comment]
I've another question since I cannot find this in the manuals. It is possible to show the dependencies between CI builds in SPOG? I've few CI builds which triggers another CI builds after all this builds (one for every component) are done I would like to combine deployment package from all the artifacts. Now I see only the border CI builds in SPOG.

**Comment by trriplejay** [comment]
Currently you cannot see beyond the CI project that is the direct trigger of the image resource. We do have plans to more thoroughly integrate CI with pipelines so that you would be able to see such relationships, but I'm not sure what the timeline is for that feature.

**Comment by manishas** [comment]
To add to John's comment above, this is very much on our roadmap and the ETA right now is 3-4 weeks.

**Comment by chetantarale** [comment]
@PaulWebbster The features you have requested are now available. You can now hook your CI projects in pipelines and trigger pipeline jobs. Here are the [docs](http://docs.shippable.com/pipelines/jobs/runCI/) explaining runCI jobs and how to use it in shippable.jobs.yml.

To view dependencies between CI builds you can enhance your shippable.jobs.yml file and specify dependencies there just like any other pipeline job
