### ISSUE TITLE
Cannot load dashboard or teams on windows

### ISSUE THREAD

**Issue by Tapppi** [Shippable/support#3130]
Cannot connect to dashboard on windows, even though was working fine on os x earlier today. I just get

> There is an issue loading the app, please contact support

Tried clearing all browsing data and all that jazz..

**Comment by Tapppi** [comment]
Got newest chrome, all request in dev tools pass, no errors in console..

**Comment by manishas** [comment]
@Tapppi is this still happening? Can we jump on a hangout and see what's going on? Let me know... we're in PST time zone.

**Comment by Tapppi** [comment]
@manishas I will try to setup some time I could be online so we can do that. I'm in northern Europe but I think I can work it out. And yes, it's still happening

**Comment by Tapppi** [comment]
This magically disappeared today, no idea why, but closing..
