### ISSUE TITLE
Decrypt box disappeared

### ISSUE THREAD

**Issue by aedades** [Shippable/support#3131]
We no longer see the decrypt box under Settings > Encrypt when in the scope of a project.

**Comment by aedades** [comment]
![screen shot 2016-11-04 at 4 14 41 pm](https://cloud.githubusercontent.com/assets/2856151/20025250/dca4d9a2-a2a9-11e6-8f03-511b635d9ab0.png)

**Comment by manishas** [comment]
@aedades this was introduced recently when we made some permissions related changes. We will work on a fix. 

In the meantime, subscription owners should be able to see the decrypt box so if you need to decrypt something you can ask a subscription owner.

**Comment by manishas** [comment]
@aedades we looked into this and it is actually by design at this point. The logic is:

- Subscription owners and collaborators can encrypt
- Subscription owners can decrypt
