### ISSUE TITLE
Feature Request: R language

### ISSUE THREAD

**Issue by realAkhmed** [Shippable/support#3132]
### Description of your issue:

Just wanted to check if there are any plans about supporting R language build environment for CI?

```yaml
language: R
```
As of today, R is:
* [the fastest language growing on StackOverflow](https://www.r-bloggers.com/r-is-the-fastest-growing-language-on-stackoverflow/)
* [takes the 5th place in IEEE language rankings](https://www.r-bloggers.com/r-moves-up-to-5th-place-in-ieee-language-rankings/)
* [growing exponentially](http://www.techrepublic.com/article/exponential-growth-of-rs-open-source-community-threatens-commercial-competitors/)

As a work-around, I am currently using Docker builds to create the R environment myself but understandably Docker builds would finish much slower than having "native" R environment available.

**Comment by manishas** [comment]
There are docker containers publicly available that can be used with Shippable to run R builds. Closing this issue since we don't really need to provide this as part of the platform.
