### ISSUE TITLE
Unable to Log In

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3133]
### Description of your issue:
I can't log in. I get an error that I don't understand. I've tried logging out and logging back in, clearing cookies, the whole nine yards.

![2016-11-07-085409_597x191_scrot](https://cloud.githubusercontent.com/assets/465340/20066865/fccbdbac-a4c7-11e6-8dc6-5186bb102198.png)

**Comment by a-murphy** [comment]
We're looking into this.

**Comment by a-murphy** [comment]
And it should be working now.  Let us know if you run into any more problems.

**Comment by BlueDragonX** [comment]
Works! Thanks!
