### ISSUE TITLE
Not able to log in to shippable app

### ISSUE THREAD

**Issue by paulcornwell** [Shippable/support#3134]
### Description of your issue:
I'm using the same bitbucket account I always use.  I received the following error:
Error
 An error occured, please choose an action.

getSystemIntegrationById for :id 58153295203fb3100060dca2 returned an error

**Comment by a-murphy** [comment]
Could you clicking the "logout" button and trying again?  It should be working now,

Duplicate of #3133

**Comment by manishas** [comment]
Closing this since it's resolved.

**Comment by fabiusks** [comment]
Hello! Having the same problem here! Any suggestions? 

Thanks!

**Comment by manishas** [comment]
@fabiusks we're looking into this as we speak.

**Comment by fabiusks** [comment]
Thank you :) I'll try again soon! Good luck hehe

**Comment by ambarish2012** [comment]
@fabiusks we will keep posting updates here - http://status.shippable.com/

**Comment by fabiusks** [comment]
Ok Thanks @ambarish2012

**Comment by ambarish2012** [comment]
@fabiusks issue has been resolved.

**Comment by fabiusks** [comment]
Thank you guys!
