### ISSUE TITLE
Connection refused while component testing my API during CI process

### ISSUE THREAD

**Issue by Neal910** [Shippable/support#3135]
I would like to add component testing into CI process, so I added component testing right after unit test finish. Shippable yml like below:
```
 # Unit test
- $GRADLE_HOME/bin/gradle build

   #Component tests
- docker build -f $SHIPPABLE_BUILD_DIR/prod/Dockerfile  -t lrp/forecasting-engine $SHIPPABLE_BUILD_DIR
- docker run -d -p 8080:8080 --name forecasting-engine lrp/forecasting-engine
- $GRADLE_HOME/bin/gradle componentTest
```

In my component test, I just simply use rest Assured to send a request to API and test response, which works perfectly in my local. Code like below:
```
baseURI = "http://0.0.0.0";
port = Integer.getInteger("http.port", 8080);
when().get("/forecast").then().assertThat().statusCode(200).extract().asString();
```

However, in Shippable CI process I got java.net.ConnectException: Connection refused. You could take a look my build: [https://app.shippable.com/projects/58101221818c7f0e00199971/status/history]

I have been using docker ps and inspect to troubleshoot, the container is running and linked to 0.0.0.0:8080, but just componentTest cannot hit on this port. I tried curl as well, got connection refused as well.

Please help me out. Thanks a lot.

**Comment by herriojr** [comment]
I was actually just having this issue and about to post something about it. I'm using docker-compose to bring up local instances of services for component testing as the first step in my ci section, however, when I try and connect to these services during testing, I get a connection refused.  Doing a docker ps shows that these services are in fact running and exposing those particular ports.

Thanks!

**Comment by herriojr** [comment]
Interestingly, lsof -i only returns a single entry which isn't any of the docker ports that I've exposed.  So somehow, it is not listening on the localhost like it should be.

Below is the docker inspect results for one of these services
```
[
    {
        "Id": "821755e06c44431c01d1b8769277344647c85a607c37763343be41bbcf0d1e53",
        "Created": "2016-11-08T19:07:57.657947171Z",
        "Path": "/usr/bin/java",
        "Args": [
            "-Djava.library.path=.",
            "-jar",
            "DynamoDBLocal.jar",
            "-dbPath",
            "/var/dynamodb_local",
            "-port",
            "8000"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 3191,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-11-08T19:08:01.073194371Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:78b80a1863a732ee6376627b10841480fc7b2d1ca193b2f72dd95c0e74ac3731",
        "ResolvConfPath": "/data/containers/821755e06c44431c01d1b8769277344647c85a607c37763343be41bbcf0d1e53/resolv.conf",
        "HostnamePath": "/data/containers/821755e06c44431c01d1b8769277344647c85a607c37763343be41bbcf0d1e53/hostname",
        "HostsPath": "/data/containers/821755e06c44431c01d1b8769277344647c85a607c37763343be41bbcf0d1e53/hosts",
        "LogPath": "/data/containers/821755e06c44431c01d1b8769277344647c85a607c37763343be41bbcf0d1e53/821755e06c44431c01d1b8769277344647c85a607c37763343be41bbcf0d1e53-json.log",
        "Name": "/myapp_dynamodb_1",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "myapp_default",
            "PortBindings": {
                "8000/tcp": [
                    {
                        "HostIp": "localhost",
                        "HostPort": "8000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "StorageOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "BlkioIOps": 0,
            "BlkioBps": 0,
            "SandboxSize": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Name": "5a349c1b9ae6e23460c51def61062a3031144548826e3034185f18b0af51c073",
                "Source": "/data/volumes/5a349c1b9ae6e23460c51def61062a3031144548826e3034185f18b0af51c073/_data",
                "Destination": "/var/dynamodb_local",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Name": "98a5c928c042363c48e50369358c1c2badcafe01dd63511dc33580849a83c555",
                "Source": "/data/volumes/98a5c928c042363c48e50369358c1c2badcafe01dd63511dc33580849a83c555/_data",
                "Destination": "/var/dynamodb_wd",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "821755e06c44",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "LC_ALL=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "JAVA_HOME=/usr/lib/jvm/java-7-oracle"
            ],
            "Cmd": [
                "-port",
                "8000"
            ],
            "Image": "deangiberson/aws-dynamodb-local",
            "Volumes": {
                "/var/dynamodb_local": {},
                "/var/dynamodb_wd": {}
            },
            "WorkingDir": "/var/dynamodb_wd",
            "Entrypoint": [
                "/usr/bin/java",
                "-Djava.library.path=.",
                "-jar",
                "DynamoDBLocal.jar",
                "-dbPath",
                "/var/dynamodb_local"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "085f93a22a5c182c73263180824ee412b64d9155e79e95dc7d145ba3edd15903",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "myapp",
                "com.docker.compose.service": "dynamodb",
                "com.docker.compose.version": "1.8.1"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "395b65ed1bb7ca14b6746dc622a04127e0a1d3746119c62ed6d8333fe472915d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8000"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/395b65ed1bb7",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "myapp_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "dynamodb",
                        "821755e06c44"
                    ],
                    "NetworkID": "14fb3d990ae5732d2ad0eaf5d53a4ec85c3c716e8938abb443485e4ee3fb5e71",
                    "EndpointID": "5066cf0779a3019f399543a9968116ae92f62eb1d73103ac70b8bb3849d7acbf",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:04"
                }
            }
        }
    }
]
```

**Comment by herriojr** [comment]
As a further question, when running a docker container in shippable, is it being done via starting a sibling or via starting a child container?  As in, is this docker-in-docker or docker with the /var/run/docker.sock mapped?

**Comment by Neal910** [comment]
I compared very carefully with @herriojr 's post about container inspection result, those are almost same. Actually, I have similar implementation in my CD process which works perfectly. what I did over there is below:
```
- docker run selenium hub and selenium nodes containers
- docker run another container to connect to selenium hub, then hub assign tests to nodes.
```
Note that: there is no tests running on the shippable node but in my containers, and all my containers connected with `docker run -link` command. 

Does it mean that in my CI process I need to create with another container to only run my component tests? But if so, it is kind of the workflow similar to @herriojr .

**Comment by herriojr** [comment]
@Neal910 The reason I asked if they were mapping /var/run/docker.sock vs docker-in-docker is because having the sock mapped means that the ci container would need to be on the same bridge in order for it to access the other resources. If that's the case, I'd have to manually create a bridge pre_ci and make sure the ci container is run with that bridge.

**Comment by herriojr** [comment]
@Neal910 Ok, I've added debugging within the pre_ci section and it appears that containers are actually siblings to the ci container.  This means the ci container won't have access to them to run tests unless you add your containers to the same network that the ci container runs on.  I'm trying out a solution right now to see if it works and will report back my findings.

**Comment by Neal910** [comment]
Hi @herriojr , after you mentioned the bridge network, I added `docker network inspect bridge` to see if the bridge contains my running container. Unfortunately, the answer is yes, it is in the bridge. However, you said you figured out the siblings result, could you please explain how you debugging in pre_ci section to confirm the siblings? Thanks.

**Comment by herriojr** [comment]
@Neal910 
pre_ci is executed in the host which runs the docker container.  Just doing a docker ps in this section will list containers being run in the host.  I found my services were listed here, which makes them siblings of the ci container.  My problem is my tests are run from the ci container whereas any docker container you started from the ci container are actually siblings and won't be on the same network (at least in my case using docker-compose).

**Comment by herriojr** [comment]
@Neal910 in your case since you already have your container connected to the bridge network, you just have to make sure when you run your container that it uses an network alias for your service.

Then your unit test, which is running in the ci container (the one you called docker build in) your base uri will be "http://youralias"

**Comment by Neal910** [comment]
@herriojr , just update what I have found. In the pre_ci, docker ps, I found there are two containers, I guess one is for my CI container and they are all in the bridge. During CI, I start my server container, and found it has been set in the bridge as well, sibling with pre_ci containers. So I guess our cases are the same. 
May I know what your solution is on binding all those containers together in pre_ci? Because my test in CI container, CI container run before my server container, how CI container links to server container, so test from CI can recognize server.
Thanks a lot.

**Comment by Neal910** [comment]
Latest update: I gave up running my server container from CI container, now I just run the server itself on the CI container. so that my component tests can easily access to server. 
Any advice is still appreciated!!!

**Comment by herriojr** [comment]
@Neal910 In my case, I essentially did the following in ci section which will work for you:

    - CONTAINERS=$(docker ps -q)
    - docker network create mynetwork
    - docker run ... --network mynetwork --network-alias app
    - for CONTAINER in $CONTAINERS; do if [ -z "$(docker network inspect mynetwork | grep $CONTAINER)" ]; then docker network connect mynetwork $CONTAINER; else echo "$CONTAINER already added to network"; fi; done
    - .... do tests ...
    - docker network rm mynetwork

You just need to make sure in your tests that the endpoint for your app is "app" to match the network alias above.

**Comment by Neal910** [comment]
@herriojr , cool, thanks a lot. I appreciate.
