### ISSUE TITLE
NPM Private Repo Dependency Fails

### ISSUE THREAD

**Issue by jetpacmonkey** [Shippable/support#3137]
We have a dependency on a private github repo in our nodejs project, which recently began failing with `ERROR: Repository not found.` and `fatal: Could not read from remote repository.`. I've tried resetting keys on everything I can get my hands on, clearing caches, and confirming that my account is the one used to process webhooks, with no effect. Both repos have a `shippable-production` deploy key visible in their repo settings.

I should note: it only fails on a specific branch, where I updated the commit hash that we're pointing at. I can only assume that the other branches are passing because they have a cached copy of the previous commit.

Everything installs as expected locally, so I have to assume this is something related to permissions, but I can't think what else to look at. Any additional debugging suggestions would be greatly appreciated.

**Comment by a-murphy** [comment]
The deploy keys added to each project when they are enabled are only used for builds of that project.  To allow access to another repository, the subscription SSH key can be added to the second project as a deploy key.  On the subscription settings tab, there's a "Deployment Key" section.  Copying that key and adding it to GitHub as a deploy key usually resolves similar errors.

**Comment by jetpacmonkey** [comment]
Github gave me an error claiming "Key is already in use" when I tried that.

**Comment by a-murphy** [comment]
GitHub doesn't allow keys to be used multiple times.  If there are multiple projects in a subscription that need access to other projects, adding the key to the account on GitHub (instead of the projects) will also work.  Otherwise, I would suggest checking that the subscription key was added to the right project.
