### ISSUE TITLE
Job limitation doesn't reset

### ISSUE THREAD

**Issue by toracle** [Shippable/support#3138]
I'm using Shippable with free tier to build my private repository. My first build starts from Oct ~~14~~ 4 and reached to limit on Nov 1 but the limitation doesn't reset for new calendar month (until today, Nov 9).

- [Link to the build failure](https://app.shippable.com/projects/57f3b172de88e10f004533cd/status/history)

**Comment by manishas** [comment]
we'll need to look into this...

**Comment by stephanielingwood** [comment]
Hey, @toracle. Sorry this issue didn't get updated earlier. The bug fix for this will be in our next release. In the meantime, we have reset your limit in the database, so you should be able to run builds now.

**Comment by manishas** [comment]
This is fixed now, so closing this issue.
