### ISSUE TITLE
Integration account visibility issue among multiple users

### ISSUE THREAD

**Issue by Neal910** [Shippable/support#3139]
## Issue: When we added integration account from Account Settings, team members cannot see each others' integration account.

For example, I added an integration account called TriggerWebImage, then I created a subscription based on this integration account. My colleague cannot see the integration account, but can see the subscription.

Is this an expectation or something wrong with our settings? Our account called "mxitechnologies", you could have a check.

Thanks.

**Comment by a-murphy** [comment]
This sounds right.  The account integrations in the account settings belong to the account that created them, and no other users may see them.  Adding the account integration to a subscription in the subscription settings tab allows that subscription to use a particular integration, but does not allow other users in that subscription to see the values in the account integration.  For example, adding a Docker Hub integration to a subscription will allow those credentials to be used to pull images for builds in that subscription, but the subscription settings tab will only show who added the integration and its name.  For more information, [the integrations documentation is available here.](http://docs.shippable.com/integrations/overview/)

**Comment by Neal910** [comment]
Thanks @a-murphy . In terms of security, I totally understand the design purpose, however if me and another guy have exactly same privilege on docker hub and Shippable account and we want to check and be able to modify all integration account, is there way to do that? Because we don't really want to wait for THE only guy to do it if we want to change that account setting. Thanks.

**Comment by Kirtap** [comment]
Hi,

I am a co-worker of Neal and i'm trying to imagine how this works in a team and dev-ops perspective. I did create a bunch of Account Integrations early on and the rest of the team started to create some as well. We now have a bunch of account integrations defined that we cannot share even if as a team, we need to be aware of them and be able to change them.

I can understand about specific account management and billing but API Token and Integrations should be something that we can share as a team. Can't you move them to the team level (We are using bitbucket) and if security is a concern, only make them visible to administrator of that team?

Also, we noticed that the Bitbucket account integration was visible to all of us (in the same team). What is so special about that one? Can't the other one be the same?

thanks

**Comment by Kirtap** [comment]
We did some more testing and noticed that even at the team level, the account integration created on another account are not visible to someone else in the team so they cannot create subscriptions.

This is a big issue for us as we do not want to have a single point for creating account integrations and subscription. What if a subscription needs to be added or modified when I am not around? What about project permissions? Can you at least make it so that everyone that is an admin in the bitbucket team can view and share those globally?

This will become quite important as we will have more teams starting to move to the cloud soon and shippable is currently the platform I recommend but it will need to support enterprise level teams that share dev-ops among all of them.

**Comment by manishas** [comment]
@Neal910 @Kirtap are you available to jump on a call so I can understand the issue more clearly?

Let me explain how integrations work today. 

(1) Integrations defined at an account level are private to the account. So if I go to my gear icon in the Shippable UI and create an integration, only I can see it in my Account Settings. 

![image](https://cloud.githubusercontent.com/assets/2983749/20193654/cefae168-a743-11e6-9785-f4e57b9796b7.png)

(2) Next, you can `add` your account integration to any subscription. This means everyone who has access to that Subscription can see the integration in Subscription Settings in Shippable UI. Anyone from the team can add integrations at this level.

Please note that a subscription on Shippable is equivalent to your Bitbucket Project. 

For example, our Shippable subscription settings look like this:

![image](https://cloud.githubusercontent.com/assets/2983749/20193810/8c2ef7c4-a744-11e6-9196-08d3ad419d55.png)

(3) All Bitbucket Project owners can modify integrations that are present for that subscription. This means that if you add one of your integrations to the subscription and someone else wants to replace it, they can go to Subscription Settings->Integrations, click on edit for the integration, and replace it with one of their own account integrations.

Happy to demo this over a call. Let me know what time works.

**Comment by Kirtap** [comment]
Thanks Manishas for your response.

I am usually available between 9am and 4 pm  eastern time. I would like to discuss with you some issues this is causing us. For now, the only way I can see resolving those is to create a dummy account that we all share for API tokens and build level integrations.

Let me know how we can get in contact.

thanks

Patrick

**Comment by manishas** [comment]
I am available for a hangout right now if you're free: https://hangouts.google.com/hangouts/_/shippable.com/shippablehelp?authuser=0

**Comment by manishas** [comment]
@Kirtap tagging you so you see this. I will be in the hangout for another 15 mins in case you're free and want to join.
