### ISSUE TITLE
Support for building docker containers?

### ISSUE THREAD

**Issue by silarsis** [Shippable/support#314]
Heya,

I have a project I'm currently building over at wercker, that is all built within a docker container - that is, the project has it's own Dockerfile and is deployed (currently to orchard, although that'll have to change) as docker containers elsewhere.

Does Shippable have support for this - automated build, test and deploy of docker containers in a nice way?

**Comment by egorpe** [comment]
Any updates? :)

**Comment by behemphi** [comment]
Hello @manishas any update on this.  Would love to test it out.

**Comment by manishas** [comment]
This is now available! Check out our blog post explaining how to set it up - http://blog.shippable.com/making-deployments-even-easier-with-docker-build

**Comment by wamatt** [comment]
way to go @manishas  + team docker!

**Comment by nathanboktae** [comment]
What's the point of using a hosted CI if you have to provide your own VM and your own docker image with all the tools installed? I really just wanted to add a `shippable.yml` and a `Dockerfile` to my got repo, provide some credentials, and be done. :disappointed:

**Comment by egorpe** [comment]
Exactly my thoughts as well. I mean, I won't name the competitors, but there are few that are doing it right now with fully hosted containers.

**Comment by manishas** [comment]
@nathanboktae You can start with a Dockerfile and shippable.yml, but you will need a dedicated host as of today. I understand that you don't want to manage your machines and we will address this in the next few weeks. Our dedicated hosts feature has always been in beta and available for $1/month and this was done to support specific customer asks.

@egorpe I don't want to discuss competitors but I believe they charge hundreds for an equivalent of our $1 plan. 

Stay tuned for some announcements in the next few weeks that will address your requirements.

**Comment by manishas** [comment]
This is now complete. You can build dockerfiles or use your custom image on our CI platform without dedicated hosts.

Please let us know if this works and any feedback is welcome!!
