### ISSUE TITLE
Delete project and enabling it doesn't delete history

### ISSUE THREAD

**Issue by pelegb** [Shippable/support#3143]
Hi,
I wan't to delete all project history and continue to use shippable. In order to do this I tried to delete and the project and re-enable it. Unfortunately all history was kept and build numbers restarted from zero causing new builds not to appear in recent history.

Please assist ASAP,
Barak

**Comment by manishas** [comment]
@pelegb we're looking into this and should have a fix soon.

**Comment by manishas** [comment]
@pelegb we have made some fixes at our end for this. If you delete the project again and re-enable it, it should delete all build history and start from build number zero again.
