### ISSUE TITLE
Support for ivy

### ISSUE THREAD

**Issue by RadAd** [Shippable/support#3144]
Is it possible to use ivy (http://ant.apache.org/ivy/) in an ant project?

**Comment by RadAd** [comment]
Just need to copy http://search.maven.org/remotecontent?filepath=org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar to ANT_HOME/lib

**Comment by ambarish2012** [comment]
@RadAd please let me know if you need any additional help.

**Comment by manishas** [comment]
@ambarish2012 this should be documented somewhere as a tip for using Ivy with shippable. We can then close the issue.
