### ISSUE TITLE
How can I trigger a pull build of the current state of my project w/o the git webhook?

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3146]
On occasion, I have observed that Shippable 'misses' the git webhook notification, leaving me to to have to make a dummy commit to get the build to happen. Is there some other way than filling my repo with dummy commits to tell shippable to grab the latest code from some branch and start building it?

**Comment by manishas** [comment]
@npahucki  you can click on the `Build` button for a project in the Shippable UI to do this. This will get the latest code from the branch and build it. 

![image](https://cloud.githubusercontent.com/assets/2983749/20193128/7ba68c76-a741-11e6-8ac7-53e55c0f3109.png)

**Comment by npahucki** [comment]
The problem is when the hook is missed there is no item shown, only old builds. If I click and old build, it builds that commit, it doesn't pull the latest from git. That's the problem.

**Comment by manishas** [comment]
Hmm we will test this again to make sure it works as expected. The `Build` button on your project's page is supposed to build the latest code. 

The `Rebuild` button on a build page does what you're saying and rebuilds the commit that triggered that particular build.

**Comment by npahucki** [comment]
Oh, perhaps I have only ever clicked on the rebuild...let me try that.

Typed on a teeny tiny keyboard that my fingers can't feel..typos and autocorrect errors are inevitable.

**Comment by manishas** [comment]
@npahucki let me know if clicking on the  `Build` button didn't do the trick.
