### ISSUE TITLE
Cannot see one of our private repos while collaborator can see it

### ISSUE THREAD

**Issue by ronnix** [Shippable/support#3147]
I cannot see one of our projects (based on a GitHub private repo in our organization) in Shippable any more, while my collaborator can see it.

Other projects were still visible, but this one disappeared.

If I follow a link to the project's page, I get an error message:
```
(Id: 2000) No access or object not found for id: (...)
warn: common|validateProjs|callerId:(...)|_checkProjectPermissions
```

We both have enabled public and private access to our GitHub accounts.

I tried both the "Sync" button on the "Account Settings" page, and the one on the "Enable project" page.

My collaborator tried deleting the project on Shippable. I could see other private repos on the "Enable project", but not this one.

(Note: This is a blocking issue.)

**Comment by a-murphy** [comment]
Your permissions should be fixed now, and we will look into why the account sync didn't update the permissions properly.

**Comment by ronnix** [comment]
Thanks!
