### ISSUE TITLE
deploy jobs stopped triggering

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#3148]
i can not start a deploy job. Successful image build is not triggering a pipeline deploy.
A did swap the token few days back to get it back to working. Saw at least one deploy go through. Now nothing. Swapping trigger tokens does not help.

https://app.shippable.com/subscriptions/578f3c82eeac370c00a23846/pipelines/spog

**Comment by npahucki** [comment]
+1 here, Last time is worked for me was Tuesday Nov 8th.

**Comment by KarolAdamiec** [comment]
ha,

notifications are seriously delayed. around 1 hour. just got one. then pipeline started working.

congestion?

**Comment by a-murphy** [comment]
Messages were stuck, but are almost caught up now.  We're not expecting them to be delayed again in the near future.

**Comment by KarolAdamiec** [comment]
works now without delay. Thanks.
