### ISSUE TITLE
Our shippable builds are not moving forward, stuck in Provisioning a node for subscriptionId

### ISSUE THREAD

**Issue by luislobo** [Shippable/support#3149]
Hi,
Our shippable builds are not moving forward, stuck in Provisioning a node for subscriptionId

For example, this one:
https://app.shippable.com/runs/5824a97499b9e20e00280b7c/1/console

Do you know if there is a problem with provisioning?

Thank you!

**Comment by a-murphy** [comment]
There are not currently any widespread problems with node provisioning, or any other errors that we could find.  Triggering another build will likely provision a node correctly.

**Comment by luislobo** [comment]
I tried that already, several times. I'll do it again and let you know

**Comment by luislobo** [comment]
Just started this one https://app.shippable.com/runs/5824afdcd152f20e009550fa/1/console. Last one was stuck there 
![screenshot from 2016-11-10 11-35-09](https://cloud.githubusercontent.com/assets/453120/20187468/fc0ceac0-a739-11e6-877b-639da83e41e3.png)

**Comment by luislobo** [comment]
OK, this new one started moving forward! All previous ones were delayed and never progressed more than that first step, since like 2 hours ago...
I'll let you know if I find any new issues. Closing it for now, thanks!
