### ISSUE TITLE
Does BYON need Ubuntu 14.04?

### ISSUE THREAD

**Issue by luislobo** [Shippable/support#3151]
I was trying to set up BYON using Ubuntu 16.10 but the scripts had problems getting the Docker version needed.

Is other version other than 14.04 supported or does it have to be exactly 14.04?
The docs say MINIMUM requirements:
 
```The minimum requirements for a build machine that can be attached to Shippable are:
1.8GB RAM
30GB SSD
Ubuntu 14.04 OS
64-bit architecture
```
Thank you!

**Comment by BlueDragonX** [comment]
The docs indicate 14.04 only. I was previously running Docker 16.04 myself, but when deploying new nodes I found that it no longer work. So now all of my nodes are 14.04.

It shouldn't matter much - the real work happens in the build containers.

**Comment by manishas** [comment]
@luislobo I will update docs - the minimum requirements are more referring to the RAM and storage requirements. We do require Ubuntu 14.04 for BYON.

However, as @BlueDragonX pointed out, you can use custom Docker images with 16.04 for your build container which is where the CI commands are actually run. 

Here are the docs that help with configuring custom images: http://docs.shippable.com/ci/shippableyml/#pre_ci_boot

Let me know if you need help with configuring this.

**Comment by luislobo** [comment]
I was able to install it on 16.10, I only had to replace trusty for xenial and instead of docker-engine 1.11.1, I used 1.12.3.

Can an option for selecting your "destination" release be used, so that the script is adjusted accordingly?

**Comment by luislobo** [comment]
cc/ @BlueDragonX can the script be changed and a "version" dropdown added so that I don't have to find/replace trusty/xenial 1.11.1/1.12.3 everytime a node becomes Inactive (I also wonder that happens...)

**Comment by BlueDragonX** [comment]
@luislobo I don't know, I don't work here.
