### ISSUE TITLE
Critical: App Not Loading

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3152]
### Description of your issue:
I hate to be the bearer of bad news, but:
![2016-11-10-202556_1645x824_scrot](https://cloud.githubusercontent.com/assets/465340/20204377/09dacf06-a784-11e6-8a7e-0e15e9e349b6.png)

It gives me that error and never finishes loading.

**Comment by djenriquez** [comment]
Yup, can confirm. I was getting intermittent errors, so I figured I'd clear my cookies out. Now it won't load in at all, showing the same as @BlueDragonX's above.

**Comment by manishas** [comment]
Hmmm we're looking into this. In the meantime can you go to https://app.shippable.com/logout and then logging back in?

**Comment by manishas** [comment]
Let me know if that works. Looks like we have some issue with cookies and are looking into it.

**Comment by manishas** [comment]
We've  also deployed some fixes for some of the issues we've been seeing over the last week.

**Comment by BlueDragonX** [comment]
I've been using it successfully for the past few hours. All good by me.
