### ISSUE TITLE
One project, two project ids

### ISSUE THREAD

**Issue by djenriquez** [Shippable/support#3153]
### Description of your issue:
Hi all,

I'm experiencing weird behaviors and it appears to be related to the fact that there are two project ids matching the same project:

https://app.shippable.com/projects/581a2fc51ae1890f00d3dd6c/status/
https://app.shippable.com/projects/581e7826fbc68c0f00deb0ca/status/

581e7826fbc68c0f00deb0ca runs fine, while the other is stuck in a waiting state, however 581a2fc51ae1890f00d3dd6c is what is linked from Github as the status for PRs.

Is this normal?

**Comment by a-murphy** [comment]
It looks like the repository was deleted and re-created (or re-forked) on GitHub at some point.  So it is expected that two projects exist on Shippable, and the permissions on those projects appear to be correct.  However, nothing should be triggering the older project.  Are the links from GitHub on older or more recent commits?

**Comment by djenriquez** [comment]
Gotcha, when we transferred ownership, it added another webhook without cleaning up the old one.

Got it resolved, thanks for the info!
