### ISSUE TITLE
Cannot login into Shippable dashboard

### ISSUE THREAD

**Issue by PaulWebbster** [Shippable/support#3154]
Today, I've tired log-in standard way via Github. First thing is that Shippable ask me once again to authorize the application, but it is already authorized. Nevertheless, I click to authorize shippable and OAuth start processing something. However, similarly to the situation from 2 weeks ago, after few seconds of processing it brings me back into Github authorization page so I cannot log-in now into Shippable at all.

**Comment by kpmeen** [comment]
Me and a colleague are having the the exact same problem....the oauth authorisation processes goes into a loop and never manages to get back to shippable. Even tried revokgin shippable access to my github, the doing the auth process again. Still the same loop occurs. However `prod-shippable` is correctly registered in the authorised apps section.

**Comment by manishas** [comment]
We're fixing this right now.

**Comment by kpmeen** [comment]
Managed to get in now...thanks
