### ISSUE TITLE
Cannot view any of my projects, error 4001

### ISSUE THREAD

**Issue by dbalatero** [Shippable/support#3155]
### Description of your issue:

Whenever I try to view a build/project, I get:

```
(Id: 4001) No routeRoles found for pattern: /projects/:projectId
verbose: /projects/:projectId|GET|validateAccount|_getRouteRoles
```

<img width="1543" alt="screenshot 2016-11-11 11 35 53" src="https://cloud.githubusercontent.com/assets/59429/20227823/12e0fd80-a803-11e6-9720-43a7ee41b0b3.png">

Help!

Running on Chrome, OS X.

**Comment by trriplejay** [comment]
we're looking into this now.

**Comment by dbalatero** [comment]
@trriplejay looks like i'm back in

**Comment by trriplejay** [comment]
great, this should be resolved now. Let us know if you have further issues.
