### ISSUE TITLE
Unable to call the `/accounts` and `/subscriptions` API endpoints

### ISSUE THREAD

**Issue by kpmeen** [Shippable/support#3158]
Using the API with an apiToken, today I am suddenly getting a 401 response from the `accounts` and `subscriptions` services. The other services seem to work as expected (`projects`, `runs` and `jobs`).

**Comment by manishas** [comment]
we are looking into this...

**Comment by avinci** [comment]
@kpmeen free users have limited access to api. Is this happening in spite of you having a paid account? We need to document this better and we have an open issue to do that.
