### ISSUE TITLE
Webhooks no longer triggering builds

### ISSUE THREAD

**Issue by antoligy** [Shippable/support#3164]
Hey, a few weeks ago we renamed one of our repositories, and since then webhooks haven't been failing.  I've just attempted to rename the username which the webhook contains to the right repository name, with no luck.

Could you please take a look?  https://app.shippable.com/projects/57e9a92d30fd8c0e00d51efb/status/

**Comment by manishas** [comment]
@antoligy can you try resetting the project? There is a reset option in project settings.

**Comment by antoligy** [comment]
Thanks @manishas, resetting seems to have fixed it!
