### ISSUE TITLE
(Pipelines) Deploy Job - User configurable timeout needed in shippable.jobs.yml

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3165]
Please see previous issue: https://github.com/Shippable/support/issues/3161#issuecomment-260727097

This is still a very close config to the sample pipelines. I'm just trying it with 3 nodes and 2 running services (2 replicas) on AWS ECS now.

```
waiting for updated task to become steady
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:1
Desired count: 2, Running count:1, Pending count:0
Desired count: 2, Running count:1, Pending count:0
Desired count: 2, Running count:1, Pending count:0
Desired count: 2, Running count:1, Pending count:0
Desired count: 2, Running count:1, Pending count:0
ec1f75c7-6e2e-47bb-b59a-07e93288de6c - (service dv-prod-ecs-dv-man-7fc63b07-8371-47fe-a925-9666369a3436) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance e6e38f2c-8437-4ad9-b79a-8bc3fe43ee30) is already using a port required by your task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide. (Tue Nov 15 2016 21:41:34 GMT+0000 (UTC))
e9fdcffa-4ba0-47f3-8391-cfdb7e6dcadd - (service dv-prod-ecs-dv-man-7fc63b07-8371-47fe-a925-9666369a3436) has started 1 tasks: (task bee54fbc-a7ec-4de8-96c9-9ac9368616be). (Tue Nov 15 2016 21:41:23 GMT+0000 (UTC))
58cc803c-3b5d-4028-ac07-d62337c06741 - (service dv-prod-ecs-dv-man-7fc63b07-8371-47fe-a925-9666369a3436) has stopped 1 running tasks: (task 4bc69ed2-f9a7-482d-8d05-05bb5d8f4c92). (Tue Nov 15 2016 21:41:34 GMT+0000 (UTC))
Successfully created folder /build/state/dv-man/
Successfully saved file ecs-service-response.json
Successfully created folder /build/state/dv-man/
Successfully saved file ecs-service-definition.json
Successfully saved file ecs-task-definition.json
Successfully created folder /build/state/dv-man/
Failed to deploy manifest for type: upgrade
Deployment failed for dv-man
Deployment failed with error : true
```
![image](https://cloud.githubusercontent.com/assets/16925064/20325546/65225d4a-ab42-11e6-85da-4f8ee9263ff4.png)

I think we are hitting a timeout limit. https://app.shippable.com/subscriptions/57f4596bb60e2a0f001627f3/pipelines/builds/582b80e543e4db1000e4eaf3/consoles

I'm not sure why that fails sometimes but not other times. I think we're hitting a timeout when it's waiting for the hosts to change around. I just don't know what timeout values are used or if that's what's happening....?

**Comment by trriplejay** [comment]
I think this may be a bug. Our deployment is failing too soon in cases where ECS can still figure out a way to finish deploying the task definition.  Adding a 4th host would get around this, but the upgrade should work without that... we'll investigate.

**Comment by gitglacier** [comment]
If you look in the past history, I tested a few times using blueGreen and upgrade for my prod cluster. Neither worked. Using replace on my dev cluster worked great.

**Comment by gitglacier** [comment]
@trriplejay if you need to test a slower bootup of ECS nodes, I am using the latest official Amazon ECS Linux AMI: ami-1924770e and I have the following (edited) User Data in my Launch Configuration. (I believe this somehow gets passed down to cloud-init through the "magic" of auto-scaling.)

Original: (something like)
```
#! /bin/bash
echo ECS_CLUSTER=my-cluster-name-here >> /etc/ecs/ecs.config
```

Ours: (something like)
```
#! /bin/bash
echo ECS_CLUSTER=my-cluster-name-here >> /etc/ecs/ecs.config
#......... more stuff here, adding our suffix to DNS search, mounting an NFS share
yum -y update  #AWS doesn't update their images often enough, security updates are out
```

**Comment by trriplejay** [comment]
in your scenario above: 
- blueGreen is expected to fail
- upgrade is expected to work (but doesn't)
- replace should work.

We'll work on a fix for upgrade. ECS does this balancing act of trying to bring up tasks, failing, removing old tasks, trying to bring up new ones again, back and forth forever or until it hopefully reaches a steady state.  It seems that the Shippable deploy job is giving up too soon and labeling it as a failure.  I agree that we should allow some kind of configurable timeout.

**Comment by gitglacier** [comment]
Something to be aware of, I just realized that I have no ability to stop anything running on the Pipelines screen. So if the timeout is too long or if there's no way to cancel the operation in progress, that would be bad.

**Comment by trriplejay** [comment]
@gitglacier we've recently introduced a `maxWaitTime` flag on the deploy job ([docs here](http://docs.shippable.com/platform/workflow/job/deploy/)) which will limit how long the deploy task will wait for things to become steady.  

We've also updated the `upgrade` method logic so that in your case upgrade should no longer fail, but will instead give ECS more chances to find a way to place the task.

Please let us know, or open a new issue, if you're still having any issues with managed deployments.
