### ISSUE TITLE
test coverage with a ruby on rails project

### ISSUE THREAD

**Issue by magicalbanana** [Shippable/support#3166]
### Description of your issue:
Looking for an example application that has test coverage and data on the test tab because the documentation found [here](https://github.com/shippableSamples/sample-rubyonrails-postgres-heroku) is outdated.

**Comment by cratz** [comment]
@magicalbanana 
We have a running RoR project with coverage.
This is what we have in our `shippable.yml`

```
env: 
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage CI=true HEADLESS=1400 .....  

  ci:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - % bundle and prepare test db steps% 
    - rspec -f JUnit -o shippable/testresults/results.xml
```

Gemfile:
```
  gem 'simplecov', :require => false
  gem 'simplecov-rcov', :require => false
  gem 'simplecov-csv', :require => false
```

And in `spec/support/simplecov.rb`

if ENV['RAILS_ENV'] == 'test' && ENV['COVERAGE']
  require 'simplecov'
  require 'simplecov-rcov'
  require 'simplecov-csv'
  SimpleCov.formatters = [
    SimpleCov::Formatter::RcovFormatter,
    SimpleCov::Formatter::CSVFormatter,
    SimpleCov::Formatter::HTMLFormatter,
  ]
  SimpleCov.coverage_dir(ENV["COVERAGE_REPORTS_DIR"])
  SimpleCov.start 'rails'
  
    if ENV['COVERAGE'] == 'full'
    ignore_list = [
      %ignored files list%
    ]

    (Dir.glob('app/**/*.rb') +  Dir.glob('lib/**/*.rb')).select do |file|
      ignore_list.reduce(true){|res, pattern| res && (file =~ pattern).nil?}
    end.each{|f| require_relative "#{Rails.root}/#{f}"}
  end
end
```
Best

**Comment by magicalbanana** [comment]
I'm getting an error for `require j_unit`.

**Comment by magicalbanana** [comment]
I just had to use a different gem for formatting it to XML. Works now, thanks!
