### ISSUE TITLE
(Pipelines) Deploy not showing a fail when it actually did fail

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3167]
I'm trying to get this working: http://docs.shippable.com/pipelines/jobs/manifest/#multi-package-manifest-pattern

"There are some cases where your services are not completely decoupled." (This is my build. A bunch of docker images are created and not decoupled from each other.)

Here is my console: https://app.shippable.com/subscriptions/57f4596bb60e2a0f001627f3/pipelines/builds/582bc816aa733910002c5949/consoles

The deploy script looks fairly empty. On Amazon, a service is created with no tasks. I'm not sure how else to debug this.

I think I may switch to multiple single-package manifests, but I wanted to point this out in case I'm just doing something wrong there.

Thanks.

**Comment by gitglacier** [comment]
I've tried simplying my pipeline down to just one image. It still does not appear to deploy right. It's practically 1:1 with the sample though, so I must have something wrong there.

**Comment by gitglacier** [comment]
Actually, I think this was working, I was just looking in the wrong area of AWS's interface.

**Comment by gitglacier** [comment]
I'm re-opening this one. I figured out why I was confused. The running task list on AWS's interface was empty. (Under the service.)

It turns out thought, there actually was an error with this. The deploy was showing green while Amazon was presenting an error.

**Comment by gitglacier** [comment]
I would expect this to fail in the Shippable Pipelines view:

![image](https://cloud.githubusercontent.com/assets/16925064/20359682/218b8640-abee-11e6-8bd6-cadf9fd8d41c.png)



Here is the relevant parts of: (https://app.shippable.com/subscriptions/57f4596bb60e2a0f001627f3/pipelines/builds/582ca0ec4dac720f008c3924/consoles)
```
/home/shippable/micro/nod/stepExec/managed/deploy/run.sh 2s  
####### DEPLOY: RUN.SH ########
npm
WARN
 shippable-Deploy@4.0.1 No description
 
 package.json
npm WARN package.json shippable-Deploy@4.0.1 No repository field.
npm WARN package.json shippable-Deploy@4.0.1 No license field.
npm WARN package.json shippable-Deploy@4.0.1 No README data
----> Run Deploy
Starting Deployment for: dv-test-ecs
Preparing manifests
Applying manifest overrides for peak-laradock-manifest
Inside stepExec|managed|_common|compareManifests
Comparing manifests for peak-laradock-manifest
Images match: false
Replicas match: true
Packages match: true
Summary of cluster: -- newlyAdded: 0, -- changed: 0, -- deleted: 0
Force deployment is: false
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Initialized AWS Adapter.
Deployment flow: serial
Found previous service: dv-test-ecs-peak-laradock-manifest-bc9951c4-97c3-4cdb-91ab-44cfcdf52cf7
Executing deploy type: replace
creating container definition
getting previous service
creating task definition
getting service
registering task definition
creating service
upgrading service
Successfully created folder /build/state/peak-laradock-manifest/
Successfully saved file ecs-service-response.json
Successfully created folder /build/state/peak-laradock-manifest/
Successfully created folder /build/state/peak-laradock-manifest/
Successfully created folder /build/state/
Successfully saved file ecs-task-definition.json
Successfully saved file ecs-service-definition.json
Successfully saved file manifests.json
Successfully created folder /build/state/
Successfully created folder /build/state/
Successfully saved file release.json
Successfully saved file loadBalancers.json
Successfully created folder /build/state/
Successfully saved file cluster.json
  on_success
```

I see how I need to change around my shippable.resources.yml file to request smaller amounts of CPU, but in my opinion this should at least be exposed through the script `/home/shippable/micro/nod/stepExec/managed/deploy/run.sh`

(The expected outcome of the above is that the box turns red on the pipelines view when insufficient CPU resources are available in the cluster.)

**Comment by trriplejay** [comment]
hmm. currently, `deployMethod: replace` doesn't not wait for the new service to successfully start running. It considers the job a success if the task definition is successfully posted and the service is successfully updated.

We should be waiting for the new tasks to spawn like we do with other methods. I'll open an internal bug for this.

**Comment by manishas** [comment]
We have fixed this, but it;s waiting to be deployed. I'll update when deployed and close. Thanks!

**Comment by manishas** [comment]
This is deployed. Closing.
