### ISSUE TITLE
(Pipelines) leaving out cpuShares leads to no service created

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3168]
I took out cpuShares to "let the host manage the resources" and then the services in my ECS cluster were not even created.

In other words: (in a shippable.resources.yml)
```
  - name: img-test-opts
    type: dockerOptions
    version:
      memory: 128
      cpuShares: 128
      publishAllPorts : true
```

becomes:

```
  - name: img-test-opts
    type: dockerOptions
    version:
      memory: 128
      publishAllPorts : true
```

Per your documentation you can do this, but it doesn't seem to work.

![image](https://cloud.githubusercontent.com/assets/16925064/20360226/24cfe240-abf0-11e6-901b-ee674b14fad0.png)

I added back in my cpuShares and now the ECS Cluster services are created again.

**Comment by avinci** [comment]
Yup, this should be defaulting if its not present. We will fix it in the next drop

**Comment by trriplejay** [comment]
We don't specify cpu at all in the task definition if it's not in the options provided. According to ECS this setting (`cpu`) is optional and will just take a default depending on agent/docker version. is this still a problem for you?

**Comment by manishas** [comment]
Closing this issue. @gitglacier please let us know if this is still a problem.
