### ISSUE TITLE
(Pipelines) deploy not going through

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3169]
There is very little information about why this isn't working:
https://app.shippable.com/subscriptions/57f4596bb60e2a0f001627f3/pipelines/builds/582cb3b25a16461000506733/consoles

I've tried with other deploy types also. No ECS Cluster services currently exist, and none are created.

```
####### DEPLOY: RUN.SH ########
npm
 
 package.json
WARN
npm
package.json
 
 shippable-Deploy@4.0.1 No description
 shippable-Deploy@4.0.1 No repository field.
 WARN
npm WARN package.json shippable-Deploy@4.0.1 No README data
npm WARN package.json shippable-Deploy@4.0.1 No license field.
----> Run Deploy
Starting Deployment for: dv-test-ecs
Preparing manifests
Applying manifest overrides for peak-laradock-manifest
Inside stepExec|managed|_common|compareManifests
Comparing manifests for peak-laradock-manifest
Images match: false
Packages match: true
Replicas match: true
Summary of cluster: -- newlyAdded: 0, -- changed: 0, -- deleted: 0
Force deployment is: false
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Initialized AWS Adapter.
Deployment flow: serial
Executing deploy type: replace
getting previous service
creating container definition
Found previous service: dv-test-ecs-peak-laradock-manifest-bc9951c4-97c3-4cdb-91ab-44cfcdf52cf7
Successfully created folder /build/state/peak-laradock-manifest/
Successfully saved file ecs-service-definition.json
Deployment failed with error : true
Failed to deploy manifest for type: replace
Deployment failed for peak-laradock-manifest
```

**Comment by gitglacier** [comment]
I've now cleared out all past Tasks and Services on my ECS clusters. I've switched to the default blueGreen and it's still not deploying. Is this just something with my config or is it a more global problem?

**Comment by gitglacier** [comment]
Latest run that still fails:
https://app.shippable.com/subscriptions/57f4596bb60e2a0f001627f3/pipelines/builds/582cd1c366a7db10002fa07f/consoles

I have completely removed my pipelines repo, deleted all resources, and re-added. It still isn't working and the following lines from your script output are not much to go off of?

```
Starting Deployment for: dv-test-ecs
Preparing manifests
Applying manifest overrides for dv-laradock-manifest
Summary of cluster: -- newlyAdded: 1, -- changed: 0, -- deleted: 0
Force deployment is: true
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Initialized AWS Adapter.
Deployment flow: serial
Executing deploy type: blueGreen
**creating container definition
Failed to deploy manifest for type: blueGreen**
Deployment failed for dv-laradock-manifest
Deployment failed with error : true
```

**Comment by trriplejay** [comment]
It seems like it's running into some problem creating your container definition. It may be related to something in your dockerOptions or your params, if those are being included.

**Comment by gitglacier** [comment]
I narrowed it down to one container and that seems to have shaken things loose. Adding containers one at a time again. Thanks!
