### ISSUE TITLE
Build success e-mail *not* received

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#3170]
Hi, since the last few successful builds I'm not receiving e-mail notifications anymore, see, for instance, https://app.shippable.com/runs/582c9b855a16461000506540/1/console, while I keep receiving notifications for failures and cancelled builds. The last successful build that triggered an e-mail was https://app.shippable.com/runs/5811d6476875b1100068103f/1/console 

Any hint?

**Comment by a-murphy** [comment]
Your shippable.yml indicates that e-mails should only be sent on successful builds if it is a change from the previous run's status.  This is the default, so it's possible that your shippable.yml isn't being parsed as intended.  If this is the case, I would suggest checking the indentation (it's the most common cause).  Either way, the documentation on setting when e-mails should be sent is [here](http://docs.shippable.com/integrations/notifications/email/).

**Comment by jacopo-chevallard** [comment]
Fantastic, thanks a lot ! (will re-open in the case it doesn't solve)
