### ISSUE TITLE
Report Details not available: Coverage breakdowns are not showing in the UI with the `Show Details` button

### ISSUE THREAD

**Issue by aleksihakli** [Shippable/support#3172]
### Description of your issue:

Hello!

Shippable is not happy with our coverage results and I would like a breakdown in the UI :(

We are building our project and storing our unit test coverage information for a Django project in `codecoverage` folder with the following structure:

- `codecoverage/.coverage` - Coverage binary output
- `codecoverage/coverage.xml` - Coverage XML output
- `codecoverage/htmlcov/...`  - HTML reports

We later move this whole folder into a `shippable` folder (see below).

When we build we get test results and branch coverage nicely out of the UI, but the build reports the following error on Coverage details on the `Show Details` button:

```
Report Details not available. ( Reason: {"logType":"verbose","methodName":"passthrough|jobs|getReportsByJobId|_getFiles","id":4005,"message":"Failed to get files for subscriptionId: 5823599b28bd290f00c19c14"} )
```

- Link to the build failure

https://app.shippable.com/runs/582d78f0b8b8e41000a5b517/1/coverage

- Scripts called from the yml (optional)

This is our whole test configuration:

```
build_environment: Ubuntu 14.04
language: python
services:
  - postgres
python:
  - 3.5
before_install:
    - sudo mv /etc/localtime /etc/localtime-old
    - sudo ln -sf /usr/share/zoneinfo/Europe/Helsinki /etc/localtime
install:
    - pip install -U pip
    - pip install -U wheel
before_script:
    - psql -c "CREATE ROLE test PASSWORD 'test' SUPERUSER LOGIN;" -U postgres
    - psql -c "CREATE DATABASE test OWNER test TEMPLATE template0 ENCODING 'UTF8';" -U postgres
build:
  ci:
    - pip install -r requirements.txt
    - python manage.py collectstatic --noinput
    - python manage.py migrate --noinput
    - py.test
    - mkdir -p shippable
    - cp -r {testresults,codecoverage} shippable
```

And this is our pytest configuration:

```
[pytest]
addopts = --ds=config.settings.test --junit-xml=testresults/django.xml --cov-config .coveragerc --cov-report term-missing --cov-report=xml --cov-report=html --cov .
python_files = test*.py *test.py *tests.py
norecursedirs = __pycache__ *.egg-info virtualenv*
```

And this is our coverage configuration:

```
[run]
branch = True
data_file = codecoverage/.coverage

include =
    *

omit =
    */manage.py
    */wsgi.py
    */settings/aws.py
    */settings/prod.py
    */settings/local.py
    */storages/backends/s3.py
    */migrations/*

[report]
show_missing = True

[xml]
output = codecoverage/coverage.xml

[html]
directory = codecoverage/htmlcov
```

Jenkins has no problem reading the coverage output or our JUnit test results, and coveralls.io is happy with the same format, too. Are we misconfiguring something?

**Comment by Sahloul** [comment]
@aleksihakli I have the same issue..

But I am further unable to push the coverage to Coveralls Pro, perhaps because my repo is private.
Is your repo public or private? If private, mind to show your submission configuration as well?

**Comment by aleksihakli** [comment]
Hey @Sahloul 

It is a private repository which does not at the moment use Coveralls, but we have the exact same configuration working with Coveralls and Jenkins Coverage plugin in other projects.

**Comment by Sahloul** [comment]
@aleksihakli I see, Thank you!
Aside from this issue, it seems they have another problem with coveralls, perhaps related to private repos.

**Comment by ambarish2012** [comment]
@aleksihakli we have fixed this bug. Please let us know if this issue can be closed.
