### ISSUE TITLE
Commit skipped

### ISSUE THREAD

**Issue by Tapppi** [Shippable/support#3173]
Bug. A commit simply did not proc a build in shippable. 

subid: 5808c5f2a708080e00ad7d86
projectid: 5817e61183502f0e006eb97b
commit hash: 40694d7f352bdfc617c31bf94397e3eb77ec141e

**Comment by avinci** [comment]
Can you verify that the webhook was actually delivered. We have seen in the past that this happens more often with Bitbucket than GH. If this is happening consistently, please let us know.
