### ISSUE TITLE
Request: pypi publishing

### ISSUE THREAD

**Issue by justin8** [Shippable/support#3175]
### Description of your issue:
There is no way to publish to pypi from shippable at this time.

Currently travis and drone.io both support this, but the shippable model of having credentials not stored in the repository is far superior and I would like to use it instead.

**Comment by avinci** [comment]
We are implementing a custom integrations which will allow you to store any name value pair in an encrypted fashion. We will make this available to your build environment and hence this can be achieved.

**Comment by avinci** [comment]
closing this as this will be tracked here https://github.com/Shippable/support/issues/3399
