### ISSUE TITLE
how to have test coverage with golang

### ISSUE THREAD

**Issue by magicalbanana** [Shippable/support#3178]
### Description of your issue:
Looking for examples that successfully show how to configure the YAML file to output the test tab and coverage tab for golang applications.

**Comment by BlueDragonX** [comment]
You need to generate a JUnit compatible XML file from the `go test` output. We use this tool and it works great: https://github.com/jstemmer/go-junit-report.

We run it like this, however:
```
go test -v | tee test.out
cat test.out | go-junit-report > shippable/testresults/report.xml
```
That way the full test output is print to the console and it will still cause a failure on error.

**Comment by magicalbanana** [comment]
But what about coverage? How do you test for that?

**Comment by BlueDragonX** [comment]
You use [gocov](https://github.com/axw/gocov) and [gocov-xml](https://github.com/AlekSi/gocov-xml):
```
go test -v -coverprofile=coverage.out | tee test.out
cat test.out | go-junit-report > shippable/testresults/report.xml
gocov convert coverage.out | gocov-xml > shippable/codecoverage/report.xml
```
Pro tip: RTFM+Google will get you 90% of the way to most solutions. The other 10% is experimentation. "Teach a man to fish..." and all that.

**Comment by manishas** [comment]
@BlueDragonX thanks a ton for helping!

@magicalbanana were you able to set up test and code coverage?
