### ISSUE TITLE
Bitbucket Server not included in integrations

### ISSUE THREAD

**Issue by jlumme** [Shippable/support#3179]
I'm trying to start implementing Shippable as part of our CI/CD, but can't get going since there is no option to make a Bitbucket Server integration, even though the documentation clearly says it should be there 😞

**Comment by manishas** [comment]
@jlumme thanks for pointing this out.

We recently launched Shippable Server which supports Bitbucket Server.  Unfortunately, we had to make some changes to support this which required ending support on our Hosted platform. I will update the docs to reflect this.

If you're interested in learning more about Shippable Server, let me know and I can set up a short intro call.
