### ISSUE TITLE
Docker Push fails with 'authentication required'

### ISSUE THREAD

**Issue by jrobison153** [Shippable/support#3180]
Hi,

I'm trying to do my first docker image build/push via Shippable however the push step keeps failing with the following error

docker push jrobison151/cancellation 0s  
The push refers to a repository [docker.io/jrobison151/cancellation] (len: 4)
0ab697ae5ee5: Preparing
unauthorized: authentication required

I've setup the dockerhub integration in both my account and my subscription. I've verified that my yaml file integration name matches the configured integration in the subscriptions UI. I've tried deleting and re-creating the integrations in the UI. I can push this image from my local development environment so it doesn't appear to be a docker/dockerhub issue.

Git Project: https://github.com/jrobison153/cancellation
Failing build: https://app.shippable.com/runs/583187ffb8b8e41000a5e1f2/1/console

Thanks for any help, looking forward to moving to the deployment side of the pipeline once I get past this.

**Comment by cratz** [comment]
@jrobison153 
This should fix your issue:
https://github.com/jrobison153/cancellation/pull/1

**Comment by manishas** [comment]
Closing this issue. @cratz thanks for helping with this@

@jrobison153 let us know if this fixed your problem.
