### ISSUE TITLE
Why does shippable set the NPM CA to an empty string?

### ISSUE THREAD

**Issue by czardoz** [Shippable/support#3183]
I noticed that in the `setup_ve` step of our builds, this command is being run:

```
npm config set ca ''
```

What is the purpose of running this?

**Comment by rageshkrishna** [comment]
We did this a _very_ long time ago when npm stopped supporting their own self-signed certificates. It was one of the recommended workarounds in [their blog post](http://blog.npmjs.org/post/78085451721/npms-self-signed-certificate-is-no-more). It's definitely not necessary anymore, so we'll look in to removing this in a future release.

**Comment by kanthchandra** [comment]
@czardoz , this has been fixed and is in the process of testing and  will be available with the next release around Jan 20.

**Comment by kanthchandra** [comment]
@czardoz this has been fixed in the latest deployment. Please let us know if this is still a problem. Closing this issue.
