### ISSUE TITLE
Error when removing a subscription integration

### ISSUE THREAD

**Issue by nmarshall-cst** [Shippable/support#3184]
Hello,

I am having trouble removing a BitBucket subscription integration and receiving the following error:

```
(Id: 4001) subscriptionIntegrations.destroy failed for id: 1843 returned error: update or delete on table "subscriptionIntegrations" violates foreign key constraint "resources_subscriptionIntegrationId_fkey" on table "resources"
verbose: subscriptionIntegrations|deleteById|callerId:5609c118a4c15d0d008bc7e8|id: 1843|_deleteById

```
URL: https://app.shippable.com/accounts/5609c118a4c15d0d008bc7e8/settings/account

Could I please get some assistance with cleaning this integration up? 

Thanks!
Nate

**Comment by manishas** [comment]
@a-murphy can you help with this?

**Comment by a-murphy** [comment]
There was a stray pipelines resource that had used the subscription integration.  Since the resource wouldn't have been of any use without its dependencies (which had already been removed), I've removed it.  You should be able to delete your subscription integration now.

**Comment by manishas** [comment]
closing. @nmarshall-cst let us know if you need anything else.

**Comment by nmarshall-cst** [comment]
Much appreciated!
