### ISSUE TITLE
Pipelines: Feature Request: Simplified or Custom ECS Service/Task Names

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3185]
### Description of your issue:
The auto-generated ECS service and task names complicate a number of functions we must perform out side of deployment. The most important of these is monitoring.

We use Sysdig for monitoring our container infrastructure. Sysdig allows you to filter and group containers by service and task name. In fact, this is the default behavior - which is sane. Unfortunately Sysdig does not get along well with Shippable's automatically generated ECS names. In some cases it is able to group running tasks under their associated service name but in most cases it cannot. In addition to this, Sysdig expects a service to be named the same across its lifetime. If a service is replaced by Shippable it is treated as a new service in Sysdig.

The second (albeit less important) issue is usability. It is very difficult to pick out services by name using Shippable's naming conventions. This effect is spread across all of the other service which we integrate with ECS.

In our case we have strict naming conventions for AWS resources. We have made explicit exceptions for resources deployed by Shippable. I would prefer not to do this if at all possible.

### Proposed Fix
Allow services to be named in a manifest or deployment task.

I am aware that this would complicate, or perhaps make impossible, replacing a running service with a new one. Perhaps in such cases it would be wise to suffix the name with a unique identifier.

In any case I believe Shippable should provide the end user with more control over how the resulting ECS resources are named.

**Comment by BlueDragonX** [comment]
I've encountered another use case that makes this feature critical for us.

We're attempting to add new automation around ECS services. Specifically we would like to create our own load balancer which can monitor tasks in a particular ECS service. Doing so requires that we can look up services in the ECS API by name. The fact that Shippable generates these names adds a layer of complexity to the implementation that we would rather avoid.

**Comment by manishas** [comment]
@BlueDragonX thanks for the note. I'll notify the team.

**Comment by manishas** [comment]
This has been scheduled for a February release. I will let you know when it's picked up by the team.

**Comment by avinci** [comment]
This has been implemented. Moving forward we are using the convention [deploy job name]_[manifest name]. If a blue green was used, the build number is also appended. Let us know if you see any issues further.

**Comment by manishas** [comment]
We have made some enhancements for this scenario that gives the user more control over the task names. Docs are here : http://docs.shippable.com/deploy/amazon-ecs/#customizing-service-names

Thanks!
