### ISSUE TITLE
Pipeline: Deploy Job Failure, Out of Sync with ECS

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3186]
### Description of your issue:
I'm attempting to deploy a service via a new pipeline. The first deploy job failed due to the ALB Target not being associated with an ALB. Because of this the service was either not created or it was rolled back after the failure.

I fixed the ALB issue and attempted to redeploy. The job states `Found previous service: ECS-SERVICE` and subsequently fails when it attempts to downgrade it.

The service does not exist in the cluster. For some reason Shippable thinks that it does.

This issue is blocking deploy for two of my applications.

Redacted job output:
```
Starting Deployment for: DEPLOY-JOB
Preparing manifests
Applying manifest overrides for MANIFEST-JOB
Summary of cluster: -- newlyAdded: 1, -- changed: 0, -- deleted: 0
Force deployment is: false
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Initialized AWS Adapter.
Deployment flow: serial
Executing deploy type: upgrade
creating task definition
Found previous service: ECS-SERVICE
creating container definition
getting previous service
getting service
Service will be deleted and recreated for load balancers to take effect.
downgrading previous service ECS-SERVICE
Failed to to update service ECS-SERVICE for cluster ECS-CLUSTER
Successfully created folder /build/state/MANIFEST-JOB/
Successfully saved file ecs-service-definition.json
Successfully created folder /build/state/MANIFEST-JOB/
Successfully saved file ecs-task-definition.json
Failed to deploy manifest for type: upgrade
Deployment failed for MANIFEST-JOB
Deployment failed with error : true
```

**Comment by manishas** [comment]
@a-murphy can you look into this?

**Comment by a-murphy** [comment]
I've opened an internal issue to fix this.  In the meantime, we haven't been able to find a way to avoid the error on this deploy job because of the load balancer.  You'll have to delete the deploy job (comment it out in your shippable.jobs.yml file, let it sync, go to the "jobs" tab on Shippable, and click the "delete" button next to the job).  Then you can uncomment the job to add it back without the failed deploy history.

**Comment by BlueDragonX** [comment]
I'm working on executing this work-around. I'll let you know if it's successful.

**Comment by BlueDragonX** [comment]
The workaround worked for me.
