### ISSUE TITLE
Failure Trying to Reset Project In order to fix Web Hook Problem

### ISSUE THREAD

**Issue by scottbro** [Shippable/support#3187]
The bitbucket commit webhooks for one of my projects are not working, so I tried to reset the project under Settings/Options to see if that would fix the issue, but I get the following error:

(Id: 2000) No access or object not found for id: 582c8951f207180f005c76c9
warn: common|validateProjs|callerId:5825d5bec5fdb3100085cb5b|_checkProjectPermissions

I get the same error if I try to delete the project.

**Comment by a-murphy** [comment]
Only owners can reset or delete a project.  Since you are a collaborator, could you ask the project owner to reset the project?

**Comment by scottbro** [comment]
OK thanks.

**Comment by manishas** [comment]
closing this issue since it's been addressed.
