### ISSUE TITLE
Unable to enable a Private Project

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3188]
### Description of your issue:
I am currently trying to enable a private project from my company, but I am getting the below error

(Id: 2002) Owner not found for projectId:583638a656f74e0f009bd2b9
warn: projects|enableById|callerId:582a4b3e219b6a0f00323fd9|projectId:583638a656f74e0f009bd2b9|_getValidOwner

**Comment by avinci** [comment]
We need at least one of the owners of the subscription token in order to enable a project. This is required to enable webhooks and deployment keys. Please get one of the owners to login into shippable and after that any collaborator should be able to enable.

**Comment by asanchezgiraldo** [comment]
thank you for your help is all working now
