### ISSUE TITLE
Enable project fails

### ISSUE THREAD

**Issue by strombringer** [Shippable/support#3191]
I'm trying to enable the sampleNod project in my subscription list but it fails with this error message:

"(Id: 4005) getHooks failed for strombringer/sampleNod
verbose: common|github|postWebHook:strombringer/sampleNod|_getHooks
404"

![shippable_enable_project](https://cloud.githubusercontent.com/assets/3511229/20617923/816ea77c-b2ec-11e6-8c4d-bc9bed7d2e8f.png)

I saw in screenshots from other issues that sometimes the permission setting in github contains write access for shippable, but in my account there is only read-only access. I'm not sure if this is part of the problem and I also don't know how to change this setting.

![shippable_github_permission](https://cloud.githubusercontent.com/assets/3511229/20617927/86428afc-b2ec-11e6-8c3d-5a660e50c2dc.png)

**Comment by rageshkrishna** [comment]
@strombringer We've had some issues with GitHub scopes recently that may have caused this. Can you please try hitting https://app.shippable.com/auth/github/581532953d9ed90f00b6c0e7/public? This should fix your scopes.

**Comment by strombringer** [comment]
Perfect, that worked. Thanks!
