### ISSUE TITLE
unable to enable shippable for bitbucket project

### ISSUE THREAD

**Issue by FelixSchwarz** [Shippable/support#3192]
### Description of your issue:
I have a private bitbucket project called ( https://bitbucket.org/dp24/grumpywidgets ) which I like to test with shippable.

However shippable won't show the project so I can't enable it:
https://app.shippable.com/subscriptions/577241dd3be4f4faa56b0ba5/ci/enable

If I press the "sync" button it just spins for a long time. After some time (minutes?) the spinner stops but the project does not appear.

**Comment by asanchezgiraldo** [comment]
I had a similar issue with github, and the solution was that at least one of the owners of the subscription token in order to enable a project. 

refer to issue https://github.com/Shippable/support/issues/3188

**Comment by manishas** [comment]
@FelixSchwarz I apologize for the long delay in responding. Are you still seeing this issue?

**Comment by FelixSchwarz** [comment]
Ah, I see all repos now. Must have been fixed itself within the last 3 days
