### ISSUE TITLE
Unable to enable my project

### ISSUE THREAD

**Issue by rahulbatra** [Shippable/support#3193]
Hey,

I am trying to enable my test repo in Shippable for trying it out. My repo URL is below:
https://github.com/rahulbatra/ideal-carnival

My shippable URL for enabling the subscription project is below
URL: https://app.shippable.com/subscriptions/582ac9187432da0f0073593e/ci/enable

The error I got as a floating pink box is below.
(Id: 4005) getHooks failed for rahulbatra/ideal-carnival
verbose: common|github|postWebHook:rahulbatra/ideal-carnival|_getHooks
404

Am I doing something wrong here? Thanks for your help.

**Comment by rageshkrishna** [comment]
@rahulbatra Please hit https://app.shippable.com/auth/github/581532953d9ed90f00b6c0e7/public to fix your github scopes. We've had some issues recently that may have cause the scopes on your account to not be set correctly. Visiting the URL above should sort it all out.

**Comment by jideji** [comment]
That fixed it for me, thanks @rageshkrishna.
