### ISSUE TITLE
Cannot switch back to Stable Machine Image

### ISSUE THREAD

**Issue by jideji** [Shippable/support#3194]
I changed the Machine Image to Unstable under options to tried it out. Now that I try to change it back it gives me the following error message:

```
(Id: 4001) subscription.update failed with error: insert or update on table "subscriptions" violates foreign key constraint "subscriptions_systemMachineImageId_fkey"
```

It also contains a verbose line, but don't know if any of IDs are considered sensitive information.

**Comment by avinci** [comment]
We have identified a fix. We are going to deploy a fix this friday. Does that work for you?

**Comment by jideji** [comment]
Yes there's no rush, unstable is working for me.

Thanks

**Comment by avinci** [comment]
this has been deployed....let me know if this works.

**Comment by jideji** [comment]
Works! Thank you.
