### ISSUE TITLE
Hung builds

### ISSUE THREAD

**Issue by elmpp** [Shippable/support#3195]
Hi there,

I'm consistently experiencing hung builds that have until recently been running ok. I am using a custom container and the hang occurs at the moment when PHPUnit is about to run. 

I can run this docker image with exact same checkouts consistently ok on a local [mac] docker environment. 

This is one of the many hung builds i have had today
 - https://app.shippable.com/runs/583a1eea04d5ee0f001f28bc/1/console

Here is my shippable.yml:
```# http://docs.shippable.com/ci/shippableyml/#anatomy-of-shippableyml

language: none # https://github.com/autopilotpattern/mysql/blob/master/shippable.yml

build:
  pre_ci_boot:
    image_name: eu.gcr.io/partridge-alan/php-cli-wiremock-postgres
    image_tag: latest
    pull: true
    options: "--net=host -e SYMFONY__DATABASE__NAME=partridge -e SYMFONY__DATABASE__USER=postgres -e SYMFONY__DATABASE__HOST=localhost -e SYMFONY__DATABASE__PASSWORD="

  # run integration tests using Docker Compose
  ci:
    - /initdb.sh
    - gosu postgres pg_ctl -D "$PGDATA" start 2> /dev/stderr &
    - cd /root/src/bitbucket.org/alanpartridge/api
    - composer install
    - ./robo test:unit
    - ./robo test:integration

  # send the containers to the Docker Hub
  on_success:
    - cd /root/src/bitbucket.org/alanpartridge/api && ./robo build:images

#  on_failure:
#    - cd /root/src/bitbucket.org/alanpartridge/api && ./robo build:fail


  cache: true
#    cache_dir_list:
#      - $SHIPPABLE_BUILD_DIR/node_modules
#      - $SHIPPABLE_BUILD_DIR/.git


# http://docs.shippable.com/integrations/imageRegistries/gcr/#pull-an-image-from-gcr
integrations:
  hub:
    - integrationName: GCR-API
      type: gcr

  notifications:
    - integrationName: email
      type: email
      recipients:
        - matthew.penrice@gmail.com
      on_success: change
      on_failure: always
    - integrationName: Shippable-Slack
      type: slack
      recipients:
        - "#build"
      on_success: change
      on_failure: always

branches:
  only:
    - dev
    - rc
```

Note that it is hanging at the beginning of the final step in the ci tasks (test:integration). As i mention, this is a set of phpunit tests running. I would expect to see the console updating with each pass. They'd usually all pass within a minute or two.

If i could get some visibility into the results of the build that would help but i suspect the shippable console is becoming unattached (?) to the output, hence the 2hr hang. The console should surely have been updated even if the tests had failed instead of completing.

**Comment by stephanielingwood** [comment]
Thanks for your question. Typically, timeouts in integration tests are the result of the tests waiting for something that isn't there. You may want to check that everything you need is getting installed/set up correctly.

We did notice that you have the following log earlier in your `ci` step: 
`could not change directory to "/root/src/bitbucket.org/alanpartridge/api": Permission denied`
which may be contributing to the problem. Is that expected? You might want to double-check that your code is in the `/root/src/bitbucket.org/alanpartridge/api` directory when you're running your container locally.

**Comment by manishas** [comment]
@elmpp are you still running into this?

**Comment by elmpp** [comment]
Very sorry to not close this - it was a zombied process caused by wrapping
my test runner. Are you able to close this please add in on email only.
Thanks

**Comment by manishas** [comment]
Yes, I'll close it. Thanks for the update!
