### ISSUE TITLE
"Invalid frame header" when accessing account settings

### ISSUE THREAD

**Issue by FelixSchwarz** [Shippable/support#3196]
When I try to access my account settings ( https://app.shippable.com/accounts/564c61348bfbdb0d00819146/settings/account ) the "sync" wheel is constantly spinning while the rest of the page seems to work (however I still see #3192).

In the web console I see the following errors (Fedora Linux 24, Google Chrome Version 54.0.2840.100 (64-bit)): 

    socket.io.js:4026 WebSocket connection to 'wss://app.shippable.com/socket.io/?EIO=3&transport=websocket' failed: Invalid frame header

If I use Firefox (50.0) the experience is the same but the messages in my log are different (translated by me):

    Connection to wss://app.shippable.com/socket.io/?EIO=3&transport=websocket was interrupted while the page was loading.  socket.io.js:4026:31
    GET https://app.shippable.com/socket.io/

**Comment by a-murphy** [comment]
Websocket updates, which should have stopped the spinner, are working again (and have been continuing to work).  We're not expecting future outages.
