### ISSUE TITLE
BYON running out of disk space

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3199]
I've been running shippable on own nodes. But yesterday one of the nodes ran out of space. Don't the scripts handle the management of remaining space?

**Comment by avinci** [comment]
We do not manage disk space on a custom node. The issue is we do not know anything about what people are doing on that machine. So we tend to stay away from that aspect. On our dynamic nodes, we stop and destroy that machine an spin a new one when we hit storage limits...
