### ISSUE TITLE
New deploys taking too long

### ISSUE THREAD

**Issue by ricardoon** [Shippable/support#3200]
Hi, every new deploy is taking an hour to terminate.
It get stacked in "pull_job_image" for too long.

Can you help me?
You have broken my work plan for the night already because of this problem.. =(

Another thing is, how can I go to premium? I put my card there, but it has no option to change.

**Comment by avinci** [comment]
Hey @ricardoon can you let me know what your subscriptionId is? We will take a look at this.

**Comment by ricardoon** [comment]
@avinci my Shippable ID is 54d5e37a5ab6cc13528b283c

**Comment by kanthchandra** [comment]
Hi @ricardoon,

> every new deploy is taking an hour to terminate. It get stacked in "pull_job_image" for too long.
1. It looks like you are using shippable/minv2 as your build image. This image is around 20 gb and is no longer supported by shippable and hence it has been removed from our existing AMI. As a result every time your build runs we are pulling this image and hence the long delay.
2. If you switch to one of our dry-dock images which are available on the AMI, your build run time should reduce to whatever it was earlier. More instructions on configuring your build is given here http://docs.shippable.com/ci/shippableyml/ . If you have trouble migrating to the new images, please post your yml here, we will take a look at it and let you know the changes required.

> Another thing is, how can I go to premium? I put my card there, but it has no option to change.
1. Now go to your subscription settings page and click on update plan.
2. Select the number of minions you want to purchase by dragging the slider.
3. If you have added a card earlier, select the card from the dropdown and click on buy (the dropdown has the options to add more card and allows you to change the cards as well)
4. If you haven't yet added a card, add a card and click on save and then once the card is added, select the card and click on buy.


Let us know if you are having any troubles, happy to help you.

**Comment by cratz** [comment]
@kanthchandra 

> It looks like you are using shippable/minv2 as your build image. This image is around 20 gb and is no longer supported by shippable and hence it has been removed from our existing AMI. As a result every time your build runs we are pulling this image and hence the long delay.

Is this some kind of joke???
We are using this images as well but we never received an information that this is not supported anymore or will be removed somewhen.
We had to use this image since there was (may be still is) no proper dry-dock replacement for our case see: https://github.com/Shippable/support/issues/2313

**Comment by avinci** [comment]
this was a miss on our side. We will add this back and update the images. It should about an hour or 2 and you will have it..

Just as an FYI we will removing this in the next 60 days, and you will receive the notification...

**Comment by cratz** [comment]
THX
We will try "dry-dock" image in the meanwhile may be it works now.

**Comment by avinci** [comment]
I have started the AMI build which depends on how long AWS takes. in the past its been 2-3 hrs and i will let you know...

In the meantime, dry dock images are new and updated with all the security patches which have been running for last year. So they should not cause any issues unless your build was relying on some old version of a package. 

let me know how it goes..

**Comment by cratz** [comment]
@avinci 
No we run in same problems as initial described here.
It just takes forever and `boot_container` never succeeds

**Comment by avinci** [comment]
can you let me know what image are you using? YML snippet if possible?

**Comment by cratz** [comment]
```yml
build:
  pre_ci_boot:
    image_name: drydock/u14ruball
    image_tag: prod
```
I also tried tag: `tip` whatever the meaning of this tags are.
After waiting 20min for the docker pull job started building but I run in other issue:
```
postgres_start 0s
  echo "postgres will not be started because the binary was not found at /usr/lib/postgresql/9.4/bin/postgres."
```

May be I should create new issue?
Or just wait until `shippable/minv2` is working again.

**Comment by ricardoon** [comment]
@kanthchandra 

> Now go to your subscription settings page and click on update plan.

Can you send me the link? I can't find this page.

**Comment by ricardoon** [comment]
@kanthchandra @avinci 

> It looks like you are using shippable/minv2 as your build image. This image is around 20 gb and is no longer supported by shippable and hence it has been removed from our existing AMI. As a result every time your build runs we are pulling this image and hence the long delay.

I do not define it.. In my yml I dont define Build.. its default!!

**Comment by stephanielingwood** [comment]
Hey, @ricardoon. To find the subscription settings page, click on the subscription name from the dropdown in the upper right. That'll give you a screen that looks like this: 

![subscriptiondashboard](https://cloud.githubusercontent.com/assets/7757711/20847971/13685c84-b885-11e6-9ac4-f3d5b73c685c.png)

From here, click on the "settings" tab. Now you have these options on the left:
![subscriptionsettings](https://cloud.githubusercontent.com/assets/7757711/20848137/a208813a-b885-11e6-8aff-5d1933664d34.png)

Choose "billing", and you'll see a button to click on to update your plan.

**Comment by manishas** [comment]
@ricardoon I apologize for this mixup. I will clarify this with the engineering team.

Your build uses minv2 by default since your project was enabled a long time ago. We should not have removed the image from our AMI without warning so we're working on fixing this.

In the next 1-2 months, we do intend to retire minv2 and you'll see communication about this over email in the next few days.

**Comment by ricardoon** [comment]
@stephanielingwood thanks.. I found it. Do you know what a minion is?

**Comment by manishas** [comment]
A minion is a build container... the number of minions you have in a subscription determines the number of parallel builds you can run.

**Comment by ricardoon** [comment]
> Your build uses minv2 by default since your project was enabled a long time ago. We should not have removed the image from our AMI without warning so we're working on fixing this.

> In the next 1-2 months, we do intend to retire minv2 and you'll see communication about this over email in the next few days.

@manishas thanks.. so when you guys retire minv2 the default of my account will be changing too, right?

**Comment by manishas** [comment]
@ricardoon Yes, the default on your account will change at that time. We will still likely keep the minv2 image around and you can pull it explicitly with yml config if you still need it. But it will be unsupported as a standard image.

**Comment by avinci** [comment]
this has been updated and you should see this in the new build you fire. Let me know if you have issues

**Comment by manishas** [comment]
closing.
