### ISSUE TITLE
Builds fails at the "Provision job node" / "Job node info" step

### ISSUE THREAD

**Issue by ronnix** [Shippable/support#3201]
Sometimes builds just fail, with no useful explanation in the console, e.g. https://app.shippable.com/runs/584186ad77df3c0f002c447b/1/console

Hitting "Rebuild" does not help.

Other builds on other branches build fine.

This is a blocker issue.

Thanks.

**Comment by kanthchandra** [comment]
Hi @ronnix I looked at your build history and it looks like this failure happens only on builds where the commit message is
```
`some commit message
```
Can you try pushing another commit to that branch making sure that the commit message doesnt have any special characters and see if it works for you? Meanwhile I'll discuss about this and get back to you next week.

**Comment by ronnix** [comment]
OK, I'll rewrite the commit messages in that branch to remove the back-quotes to see if it changes something.

**Comment by ronnix** [comment]
The build worked this time, thanks for the workaround!

I guess we'll have to avoid using backquotes in commit messages then.

May I suggest that you fix this on your side (probably some escaping issue?) so that other people do not hit the same problem?

**Comment by kanthchandra** [comment]
I think the problem here was a single backquote. We do `export COMMIT_MESSAGE="some commit message"` and bash did not like that single backquote in the commit mesage. 

Yes we will discuss this and then figure out how to fix this issue.

**Comment by jtaylor10** [comment]
Having a similar issue but we don't use any back-ticks in our commit messages but everyone of our builds just hangs (for 2 hours) at the "Provisioning Job Node" stage - no info provided.

We just started using Shippable and it worked for a couple days now this for the past two days

**Comment by kanthchandra** [comment]
@jtaylor10 It sounds like your issue is different from the one being discussed on this thread. We need to investigate that separately. Can you please open a new issue and point me to builds the which were affected? Thanks.

**Comment by rageshkrishna** [comment]
We have implemented proper escaping on these fields. Please let us know if this happens again.

**Comment by ronnix** [comment]
Thanks for the update!
