### ISSUE TITLE
Selenium instability

### ISSUE THREAD

**Issue by elmpp** [Shippable/support#3203]
Hi there. I have followed the helpful guide on setting up selenium jobs using node as described here - http://docs.shippable.com/ci/services/selenium/

All was going pretty well until yesterday/today when i have started experiencing broken builds as a result of the selenium server becoming unresponsive. The nature of the tests have not changed, other than the fact the external system they are testing may have be responding a bit quicker. I am also running my tests on a more regular basis so maybe some caching coming into play on shippable perhaps?

This page shows the history - https://app.shippable.com/projects/58398d0183cb0511001841ab/status/history

Note how today this run succeeded - https://app.shippable.com/runs/5841c4ca33a1af1000ad83c1/1/console
Yet the exact same code ran but failed few minutes later here - https://app.shippable.com/runs/5841c7b377df3c0f002c4c57/1/console

Viewing the console for any of the recent few day's tests will show the same failure cause of unresponsive selenium server albeit at varying times. I am running the tests on just the one thread so shouldn't be overloading it.

Thanks.

**Comment by manishas** [comment]
@a-murphy can we look into this?

**Comment by stephanielingwood** [comment]
Hi there. Thanks for questions.

Random timeouts are some of the hardest things to figure out; there can be many causes. Here's some things worth looking at:

- We noticed that you're using an old build image (shippable/minv2) which will be deprecated soon; it hasn't been updated in over a year. We recommend updating to our newer images, with newer versions installed. You can do this by using our (newer yml format)[http://docs.shippable.com/ci/shippableyml/], if you're not already. Either leave the pre_ci_boot section blank (this will use the current default Ubuntu 14 node image), or specify one of our newer images. You can see exactly what's installed in these images (here)[https://github.com/dry-dock].

- Out of memory: often, builds that run out of memory will timeout in roughly the same place. However, yours is timing out in different places in the build, so this is more of a long shot. If Firefox is being restarted for each test, Firefox would freeze when it runs out of memory. It may be worth checking to make sure there isn't a stray operation that's running amok and taking up too much memory.

- Selenium version: the version you're specifying in your yml is 2.5 years old. Unless there's a particular reason you need an older version, you could try using a newer version of Selenium. If it helps, the Selenium we install on our newer images is 2.52.

It's definitely not a caching issue, as many of your failing builds have run on completely new nodes.

Hope this helps. If you need help transitioning to our newer yml format, let us know.

**Comment by elmpp** [comment]
I have upgraded the image and it's running properly. Thank you.

Your tutorials are quite a bit of date then...
