### ISSUE TITLE
Many Provision Job Node failures

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#3204]
Large percentage of builds are failing to provision a job node. Total time taken is about 6 minutes. Example output:

![image](https://cloud.githubusercontent.com/assets/6311784/20855946/b4b44f7e-b904-11e6-9dea-630e0b4fce00.png)

**Comment by kanthchandra** [comment]
Hi @rarkins , The nodes got successfully provisioned for all your builds. But the error is coming from one of your commands in the build_ci section. The last command is throwing `make: *** [condition-report-publish] Error 1` as the output and I'm assuming that this is the cause for build failures. Can you please check and let us know?

**Comment by rarkins** [comment]
@kanthchandra sorry, you're right. I was confused by having "Provision job node" come *after* build_ci. The failures I noticed today are actually then expected/valid.
