### ISSUE TITLE
Add support for Shell Language, sh, bash, etc.

### ISSUE THREAD

**Issue by wltjr** [Shippable/support#3205]
### Description of your issue:
Add support for Shell Language, sh, bash, etc.

Invalid RUN language: bash
https://app.shippable.com/runs/58434ffa4d42fa0f00b4d1d2/1/console

**Comment by trriplejay** [comment]
all builds are run within a bash shell.  If all you need is access to the shell, then you can add `language: none` to your yml.  This will skip any language-based defaults and just run whatever commands you specify in your yml.

**Comment by wltjr** [comment]
Ok, I can try that but I am not configuring for shippable. I only have a .travis.yml and shippable is picking that up. I have not tried others, but for shell scripts it works fine. I am not sure if none is valid for travis. I could go with no language, which may work for both. I think it is cool shippable read the stuff from travis. I was going to make a shippable.yml, and I may still. But if I have 1 for both that would be great 👍

**Comment by manishas** [comment]
`language: none` is the recommended way to use unsupported languages. Closing this issue.

@wltjr hope your build worked fine.... if not let us know and we'll take a look.

**Comment by wltjr** [comment]
Ok cool I wasn't sure if none was supported, travis has that but did not see none on shippable. That works for me thanks!
