### ISSUE TITLE
Is Softlayer docker plataform supported?

### ISSUE THREAD

**Issue by tmoreira2020** [Shippable/support#3206]
Hi there, I'm playing with Softlayer trying to spinning a new docker image every successful build but I cannot find any documentation related to Softlayer, is it supported?

**Comment by avinci** [comment]
we do not support soft layer at this time. Do you have a specific scenario that you are trying out? Not sure what orchestration they are using. But if they support Kube or Mesos we can easily implement it as a custom deployment end point
