### ISSUE TITLE
No ruby project build are working since friday

### ISSUE THREAD

**Issue by cratz** [Shippable/support#3207]
we used old shippable CI image and after this was removed by shippable without any information as I figured out by accident by reading https://github.com/Shippable/support/issues/3200
Now all ruby jobs are not working anymore.
https://app.shippable.com/runs/5843f57d307b1f0f004f8854/1/console
https://app.shippable.com/runs/5842a5684d42fa0f00b4cb8f/1/console

and many many more.

**Comment by manishas** [comment]
is this still happening?

**Comment by cratz** [comment]
we found a solution Thanks
