### ISSUE TITLE
weird bypassing/failing script /home/shippable/cexec/build.sh

### ISSUE THREAD

**Issue by czhujer** [Shippable/support#3208]
I'm going to use custom image, but i see mostly error with /home/shippable/cexec/build.sh script.

i'm using centos image, but I thought, "language: none" bypass this scripts and runs my command vin"ci" section...
Some builds worked..
https://app.shippable.com/runs/584428474d42fa0f00b4d71e/1/console
https://app.shippable.com/runs/58441d2c307b1f0f004f8a92/1/console

But others failed..
e.g.
https://app.shippable.com/runs/584435624d42fa0f00b4d77f/1/console

Do you have Ideal with is related condition?
I tried rewrite docker entrypoint, but it seems is not possible "by design".

Thanks,
Patrik

**Comment by czhujer** [comment]
you can check this build..
https://app.shippable.com/runs/584444039d1f3e0f005761a6/1/console
there isn't section "wait for error" with error in docker logs.

but...this is build with error. it's rebuild on same commit.
https://app.shippable.com/runs/5844490b4d42fa0f00b4d824/1/console

**Comment by kanthchandra** [comment]
Hi @czhujer , It looks like you are running a custom image which has some unmet dependencies, If you download the build logs you will see the following lines which are causing your build to fail.
```
Looking for apt-get...
which: no apt-get in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
Could not find apt-get. Missing build system dependencies will not be automatically installed.
/home/shippable/cexec/dist/main/main: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/shippable/cexec/dist/main/libz.so.1)
``` 
Before we start your build we check for the following dependencies. Please make sure that your custom image has the following dependencies installed.
*  apt-get
*  sudo
*  git
*  sshagent
* python

**Comment by czhujer** [comment]
Hi @kanthchandra,
thanks for info.

I understood, script build.sh has to be executed . successfully :)
Ok, i'm going to modify CentOS that way..

FYI there is baseimage.. https://github.com/czhujer/docker-shippable-c6base
