### ISSUE TITLE
drydock/u14ruball:prod missing packages

### ISSUE THREAD

**Issue by cratz** [Shippable/support#3209]
Because of https://github.com/Shippable/support/issues/3200 and https://github.com/Shippable/support/issues/3207 we were forced to take care of https://github.com/Shippable/support/issues/2313

For us (Ruby + pg) this package is missing in `drydock/u14ruball:prod` image:
`libpq-dev`

Is it possible to pre install this package to speed up the build?

**Comment by manishas** [comment]
@cratz I will keep this open for when we update our images.

**Comment by cratz** [comment]
@manishas 
Thank you!

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.

**Comment by cratz** [comment]
@avinci 
Thx works now!
Only thing we had to change was adding `selenium` to `services`

**Comment by cratz** [comment]
@avinci is it possible that new new image is not present on the worker instances?
Currently `boot_container` step takes forever on some builds.
