### ISSUE TITLE
Log retrieval API seems broken again

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#3210]
Hello,

This is a followup of https://github.com/Shippable/support/issues/3100

The new route documented by http://docs.shippable.com/api/job/#download-console-logs does not seem to work anymore. We now get:
```
404
Cannot GET /jobConsoles?download=true&amp;jobIds=5845466c9d1f3e0f00577153
```
The former one does not work either. Is there another way to fetch job logs?

**Comment by a-murphy** [comment]
Sorry, the route's been changed again.  It's `GET /jobs/:jobId/consoles?download=true` now.  So your example would be `GET /jobs/5845466c9d1f3e0f00577153/consoles?download=true`.

**Comment by manishas** [comment]
@pmezard I am very sorry this happened again without prior warning. I have escalated this within the team and we will make sure future changes are documented and customers are notified. 

We're also versioning our APIs in the next future to avoid these situations.

**Comment by manishas** [comment]
Documentation has been updated again.
