### ISSUE TITLE
I don't see my organization in the drop down list

### ISSUE THREAD

**Issue by yegor256** [Shippable/support#3211]
I don't see my organization in the drop down list at the top left corner. "Sync" doesn't help. What else do I miss?

**Comment by kanthchandra** [comment]
Hi @yegor256 are you using Bitbucket or github? If you are using github, then can you please check if shippable is given access to that organization? This can be seen when you navigate to the authorized applications page on github or by directly clicking on this [link](https://github.com/settings/connections/applications/2f98b6d654957d9d0963).

If you are using bitbucket. Please give us your username on Bitbucket.

**Comment by yegor256** [comment]
@kanthchandra fixed, thanks
