### ISSUE TITLE
Excluded braches get built and deployed CI

### ISSUE THREAD

**Issue by lapponiandevil** [Shippable/support#3212]
Feature branches get built and deployed according to other CI settings, even if shippable.yml has these lines included:

```
branches:
   only:
     - master
```

http://docs.shippable.com/ci/advancedOptions/branches/

**Comment by a-murphy** [comment]
Could it be that these are pull request builds?  The `branches` section above will not exclude pull requests to `master`.  You can disable pull requests entirely in the project settings tab or check if a particular build is a pull request while it is running using the `PULL_REQUEST` or `IS_PULL_REQUEST` [environment variables](http://docs.shippable.com/ci/advancedOptions/environmentVariables/).

**Comment by lapponiandevil** [comment]
No, they are not pull requests. Just nice pure commits to other branches than master.

**Comment by a-murphy** [comment]
Then would you mind including a link to one of these?

**Comment by a-murphy** [comment]
I was hoping for the ID out of the URL, but the name of the branch at the top of the build page and the `branches` section out of the `shippable.yml` on that branch will do.  It may also be worth double-checking if it has a pull request symbol
![screenshot from 2016-12-06 08 55 41](https://cloud.githubusercontent.com/assets/5492015/20934984/e5fec64c-bb91-11e6-8be7-5d09ad0f0545.png)
or a commit symbol
![screenshot from 2016-12-06 08 56 02](https://cloud.githubusercontent.com/assets/5492015/20935003/f57e0966-bb91-11e6-9d91-3c7f16ad7574.png)

**Comment by lapponiandevil** [comment]
Now I noted that the built commits actually were PR's to the branch which was supposed to be building. They are not merged though, so they shouldn't build, right?

**Comment by a-murphy** [comment]
Builds are triggered by default when a pull request is opened or a new commit is added to an open pull request.  Pull request builds use the code (and `shippable.yml`) file from the base branch with the changes in the pull request added.  The usual way that commands are only run when it is not a pull request is by checking the environment variables, with lines in `shippable.yml` similar to the following:
```YML
 - 'if [ "$PULL_REQUEST" == "false" ]; then commandThatShouldRunWhenNotAPullRequest; fi'
```
Of course, if you don't want pull request builds at all, you can disable them on the project settings tab.

**Comment by lapponiandevil** [comment]
Oh there was a setting for that on the website! I'll just disable that one then.
Thank you for your help.
