### ISSUE TITLE
Shippable Heroku documentation

### ISSUE THREAD

**Issue by ubwhole** [Shippable/support#3213]
Hello,

I was trying to deploy my Shippable build to Heroku.  I based my shippable.yml on the **Without Heroku toolbelt** [documentation](http://docs.shippable.com/tutorials/ci/integrations/deploy/usingHeroku/).  It would not deploy.

After I modified my shippable.yml file to the following, it finally deployed.

```
...

build:
  on_success:
    - git push -f git@heroku.com:$APP_NAME.git master

...
```

It looks to me multiple places in the documentation needs to be updated.

Thanks,
-John

**Comment by avinci** [comment]
@manishas is this done?

**Comment by avinci** [comment]
@manishas ?

**Comment by deepikasl** [comment]
[Heroku documentation] (http://docs.shippable.com/tutorials/ci/deploy-heroku/) is updated. Closing.
