### ISSUE TITLE
ecs deploy not including elb

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#3214]
My ECS service that was working, no longer has an ELB mapped as of the last few deploys.

I've tried renaming the load balancer resource and the deploy job and I continue to get green deployments, but there is no ELB mapped in the ECS service. 

https://app.shippable.com/subscriptions/573a53db2a8192902e204f23/pipelines/builds/5845c53b307b1f0f004fb249/consoles

**Comment by trriplejay** [comment]
I think they key is in this line here:
```
no match found in image hapi-common-api-img for container port 3000. Skipping LB
```
It looks like your `applyTo` section contains a reference to this port, but the image in the manifest that the applyTo is referencing is not set up to use that port. Was there a change to a dockerOptions object recently that would have removed that `3000` port definition?

**Comment by pwarnock** [comment]
Thanks! I scanned right past that. I was indeed missing a config.
