### ISSUE TITLE
Reached private job limit for this month

### ISSUE THREAD

**Issue by mats990** [Shippable/support#3215]
Hi,

I'm having problems with running private job. I get error:
>  This job was skipped because you have reached your private job limit for this month. Please upgrade your subscription to continue running jobs. 

How can I check my usage and how can I check when will I be available to run jobs again?

Thanks in advance

**Comment by a-murphy** [comment]
The limit resets on the first of every month.  Since there was a bug resulting in limits not resetting, I've updated your limit.  (The bug causing limits to not reset has been fixed as well.)  You should be able run jobs again now.

**Comment by mats990** [comment]
Thank you for the fix, it works now

**Comment by manishas** [comment]
closing
