### ISSUE TITLE
Docs pages are completely empty

### ISSUE THREAD

**Issue by frankwiles** [Shippable/support#3216]
This wasn't the case yesterday, but assume it's a bug/build failure somewhere.  Verified in Chrome and Safari for OSX.
![screen shot 2016-12-06 at 3 50 57 pm](https://cloud.githubusercontent.com/assets/144159/20945199/ec5353d4-bbcb-11e6-9868-78373b6f9838.png)

**Comment by frankwiles** [comment]
I logged in and now they're available? But yesterday I didn't have an account so not sure how I was able to view them then.  Perhaps an edge case when going to docs (via Google search) when logged in?

**Comment by manishas** [comment]
@frankwiles I think that if we change a docs link google sometimes still points to the old link. Please let us know if you still see issues with docs.
