### ISSUE TITLE
Subscription Settings with free pricing?

### ISSUE THREAD

**Issue by ivansabik** [Shippable/support#3217]
### Description of your issue:
I have been using the free service, can I change the AMI to the unstable one to use docker-compose or do I need to have some priced plan?

I refactored my whole tests rely on `docker-compose`  so shippable might not be an option for that, I know travis has builtin support for that by specifying docker under the service section.

Thanks!

**Comment by ivansabik** [comment]
If not possible when will this AMI be released as stable?

**Comment by a-murphy** [comment]
Any subscription owner can change the AMI used for builds in the subscription on the subscription settings tab.  It's under "Machine Images" in "Options."  Documentation is [here](http://docs.shippable.com/ci/advancedOptions/machineImages/#setting-an-image) if you have trouble finding it.

**Comment by ivansabik** [comment]
I looked for this setting before posting this without success but tried again now just found it!  Thanks a lot
