### ISSUE TITLE
How to setup webhook for microsoft teams?

### ISSUE THREAD

**Issue by MikeVitik** [Shippable/support#3219]
Hello.
I'm try to setup webhook for "Microsoft Teams" services. I've read [shippable custom webhook](http://blog.shippable.com/triggering-a-custom-webhook-after-continuous-integration). I try to adopt the article for MS teams web hook as it mention in [MS webhook](https://dev.outlook.com/Connectors/GetStarted) for it I add the next line to the .yml
```
    - integrationName: xenarius-ms-teams
        type: webhook
        title: "Failure - $REPO_FULL_NAME - $BUILD_NUMBER"
        on_failure: always
        on_success: never

```
and setup url provided by MS Teams for 'xenarius-ms-teams' integration.
But I recieve the following error for [build](https://app.shippable.com/runs/58494f66307b1f0f0050181c/1/console):
```
Triggering webhook  
Failed to trigger webhook for objectId:58494f66307b1f0f0050181c with statusCode:400 and message:Could not parse error body
```
I test the webhook provided by MS Teams and all works fine: 
`curl -H "Content-Type: application/json" -d "{\"title\": \"Learn about Office 365 Connectors\", \"text\": \"Visit the [Outlook Dev Portal](https://dev.outlook.com) to learn more about Office 365 Connectors!\", \"themeColor\": \"EA4300\"}" https://outlook.office365.com/webhook/8d5ca19b-b404-43d9-a43d-6480801c79be@e4d60396-9352-4ae8-b84c-e69244584fa4/IncomingWebhook/03d4914a8d6641f58083d5295c9d0e4a/349e56c1-6dc2-4505-9a95-ff96c07b6abe
`
I suppose something go wrong with generated post request, but I cannot debug it or get any info about it from the error message that shippable service provided. 
Can you point me to the right direction how to get additional info about request or give me some instruction or clarification that I should write to yml file.

[shippable.yml.txt](https://github.com/Shippable/support/files/639525/shippable.yml.txt)

**Comment by a-murphy** [comment]
It looks like we tried to send the webhook to the URL in your integration and it returned a 400.  It might be that it doesn't expect an empty body.  Could you try updating the integration your `shippable.yml` to the following format?  The title should be in a `payload` object so that it will be sent.
```YML
    - integrationName: xenarius-ms-teams
      type: webhook
      payload:
        title="Failure - $REPO_FULL_NAME - $BUILD_NUMBER"
      on_failure: always
      on_success: never
```
More [documentation on webhook integration options is available here](http://docs.shippable.com/integrations/notifications/webhooks/#configure-the-integration).

**Comment by MikeVitik** [comment]
Thank you for documentation link.
I change shippable.yml [build](https://app.shippable.com/runs/584a7ba79d1f3e0f00581732/1/console) as you suggestiong, but has the same error:
```
Triggering webhook  
Failed to trigger webhook for objectId:584a7ba79d1f3e0f00581732 with statusCode:400 and message:Could not parse error body


```
[shippable.yml.txt](https://github.com/Shippable/support/files/641848/shippable.yml.txt)

**Comment by a-murphy** [comment]
Sorry, there was a missing `-` in payload (it should be an array, not an object), and it looks like something doesn't like the quotes.  I can't say for sure what Microsoft Teams will think of the payload, but testing with my own URL, and the updated `payload` above, the webhook contains the expected title.

**Comment by a-murphy** [comment]
And I noticed that you are using the same account integration twice in your notifications section.  That has been known to cause conflicts when saving payloads, and using a separate integration for each webhook in the YML is usually recommended.

**Comment by MikeVitik** [comment]
Thank you very much for you patience and sorry for my inattention. Today I got the first message to MS Teams.
