### ISSUE TITLE
Amazon ECS integration missing

### ISSUE THREAD

**Issue by jbouse** [Shippable/support#3221]
### Description of your issue:
Attempting to go through and follow the re:Invent 2016 Booth Challenge - Phase 2 instructions and it mentioned adding the Amazon ECS integration but all I see are Amazon ECR, Amazon Web Services (IAM) and AWS.

**Comment by ttrahan** [comment]
hi @jbouse : sorry for the confusion. For the ECS integration, you'll use the 'AWS' integration from the dropdown.

![image](https://cloud.githubusercontent.com/assets/4467650/21026694/aceb5200-bd42-11e6-99d6-a3cd55e36056.png)
