### ISSUE TITLE
Build for tsavo/malice suddenly not launching containers

### ISSUE THREAD

**Issue by TSavo** [Shippable/support#3225]
### Description of your issue:
Just made a commit to github.com/tsavo/malice, and it's building everywhere else, but shippable doesn't seem to boot the containers. It fails on the setup_ve step, with no output.

**Comment by a-murphy** [comment]
The most recent failed build of yours failed to download a particular version of Node.  I can't be sure why it wasn't successful, but you should be able to get the same logs by clicking the "download" button.  The downloaded logs sometimes contain a little more than is displayed.

**Comment by TSavo** [comment]
Turns out it was nvm, the CDN it was pulling from was down.
