### ISSUE TITLE
nvm install "6" --> xz: (stdin): File format not recognized

### ISSUE THREAD

**Issue by solsenfinovertech** [Shippable/support#3226]
Hi, very related to issue described in https://github.com/Shippable/support/issues/743

After downloading latest nodejs v6.+, logged:

```
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Seems to be an issue that started today.

https://app.shippable.com/runs/584ad9bbc3509e0f0012010d/1/console

**Comment by a-murphy** [comment]
I haven't been able to reproduce this error.  But, since all of your failures were within a few hours and there was another support issue where downloading a NodeJS version failed, just trying again will likely work.  It could be that the NodeJS 6.9.2 download was incomplete.

**Comment by solsenfinovertech** [comment]
I haven't seen it recently as well, closing the issue.
