### ISSUE TITLE
CI Stuck at provisioning a node for subscriptionId

### ISSUE THREAD

**Issue by jessica-pixvana** [Shippable/support#3227]
All my CI jobs are stuck at the "Provisioning a node for subscriptionId" stage. They have previously worked fine and am using the standard shippable instance. They job had been stuck there for 45+ minutes, I cancelled it and tried to rebuilt again. Still no change

**Comment by manishas** [comment]
@trriplejay @a-murphy can you look into this?

**Comment by a-murphy** [comment]
We haven't been able to find a cause, but it looks like a later build provisioned nodes for your subscription.  The majority of subscriptions have had nodes provisioned correctly.

**Comment by manishas** [comment]
This should not be happening any more. Closing.
