### ISSUE TITLE
How to change build trigger config [Commit/PR] for different branches

### ISSUE THREAD

**Issue by desoukya** [Shippable/support#3228]
@manishas 

is it possible to set the build trigger configuration for each branch? Versus having the same trigger configuration across all the branches (see image below):

<img width="772" alt="screen shot 2016-12-11 at 4 12 01 pm" src="https://cloud.githubusercontent.com/assets/10380913/21083371/e50820b0-bfbc-11e6-941e-2d1673fccb80.png">

**Comment by manishas** [comment]
No, we do not support this at a branch level... just at a project level.

**Comment by desoukya** [comment]
I'd like to suggest this as a feature request.

Reasoning:
As part of my CI process, I'm handling environment promotion on successful builds from develop, to staging, and finally master as per some logic defined in the `on_success` block of each build.

The Issue:

Assuming:
- All selected branches have configured webhooks to trigger builds on PR & Commits.
- Develop, Staging, and Master branches are carbon copies of each other.

Scenario: A PR is raised against `develop`, this kicks off a build. The CI build is successful and the PR is reviewed and merged. By virtue of merging, this causes a commit on the develop branch, in turn triggering another build. On this build, the following instruction is executed within the `on_success` section:

```
if [ "$BRANCH" == "develop" ] && [ "$IS_PULL_REQUEST" == false ]; then ./ci_environment_promotion.sh develop staging; fi
```

The script uses github API to raise a PR from `develop` to `staging`. Since a PR is raised, this triggers a build. Once the build is successful, it runs the following instruction within the `on_success` section:

```
if [ "$BRANCH" == "staging" ] && [ "$IS_PULL_REQUEST" == true ]; then ./ci_merge_pr.sh $PULL_REQUEST; fi
```

Here is where the issue is, the script above will merge the PR from `develop` to `staging`, and thus result in a new commit against `staging`, which in turn will trigger another CI build. The same applies to master.  I want to avoid these redundant builds against staging & master for commits.

To achieve the above workflow, I require the following configuration:
- `Develop` branch triggers builds on PRs & Commits
- `Staging` branch triggers builds on PRs only
- `Master` branch triggers builds on PRs only

**Comment by avinci** [comment]
@desoukya we can do this using runSh jobs in pipelines. The limitations of CI projects is that its one config per project. The reason why we built pipelines is to allow this kind of workflow and run different configs per branch. 

@chetantarale please write a blog around this and demonstrate the implementation.

**Comment by avinci** [comment]
we have updated our docs around this. This should be relative easy to do now with runSH jobs since we have combines all the jobs into 1 pane with the new UI
