### ISSUE TITLE
Timeout while provisioning

### ISSUE THREAD

**Issue by mats990** [Shippable/support#3230]
Hi,

I'm having problems with builds for last few days. It all started last Friday at 7:53 PM when my build was 39min in provisioning state ( https://app.shippable.com/runs/584afdb5a932c20f003a6468/1/console ). I canceled that build, started antoher one ( https://app.shippable.com/runs/584b06d94d42fa0f00b5a998/1/console ) and that one timed out after 1h. Today I restarted this same build but it's still in provisioning state (37min and counting).

Can someone take a look?

**Comment by mattclay** [comment]
I'm also seeing builds with jobs stuck provisioning, such as this one:

https://app.shippable.com/runs/584f21e7938d4210003b825d/26/console

It's been stuck at `Provisioning a node for subscriptionId: 573f79ce2a8192902e20e349` for 40 minutes, yet most other jobs are provisioning just fine (there are a few others stuck at provisioning as well).

**Comment by mattclay** [comment]
I'm continuing to see jobs stuck provisioning. Here's another:

https://app.shippable.com/runs/584f3048ac4a911000ec9250/4/console

Out of 34 jobs in the build, only this one got stuck. I ended up having to cancel the build and restart it so all the tests could pass.

**Comment by trriplejay** [comment]
we're currently investigating this.

**Comment by shrivara** [comment]
@mats990 is it okay if we trigger a few builds in your subscription to debug this?

**Comment by mats990** [comment]
yes, of course

**Comment by shrivara** [comment]
@mats990 we haven't been able to identify the cause of the timed out builds, but the build we tried recently seems to be okay. Could you please check if this is a problem still?

**Comment by mattclay** [comment]
@shrivara I can't speak for @mats990, but I'm still seeing the issue:

https://app.shippable.com/runs/5850a102938d4210003baf5c/14/console
https://app.shippable.com/runs/5850a126938d4210003baf80/29/console
https://app.shippable.com/runs/5850a134938d4210003baf94/23/console

**Comment by shrivara** [comment]
@mattclay we have identified a potential cause for this in your case, where builds would start running but then timeout. We'll keep you posted with updates.

**Comment by mats990** [comment]
@shrivara it seems OK now. If it happens again, I'll open a new issue. Thank you for your assistance

**Comment by mats990** [comment]
Hi,
I'm having the same issue right now. [31 minutes in state "Provision job node"](https://app.shippable.com/runs/586df8c03b531310004590c5/1/console) and nothing happens after that.

Can you please take a look ASAP?
Thanks

**Comment by rageshkrishna** [comment]
@mats990 Can you please cancel the current build and rebuild it? I'm monitoring your nodes right now to see what's going on. Thanks.

**Comment by mats990** [comment]
@rageshkrishna thank you for fast response. I started new build right now. you can build it on your own if you want.

**Comment by rageshkrishna** [comment]
It looks like your build ran successfully this time.

We currently have a known issue with the build runner sometimes not coming up on Unstable nodes. We are working on a fix for this that should roll out very soon. In the meantime, please let us know if you see this again and we will manually get your nodes running correctly.

**Comment by mats990** [comment]
Ok, thank you for your assistance.
Have a nice day
