### ISSUE TITLE
PR fails with "Logs are not available."

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#3231]
The following PR fails with "Logs are not available.":

https://app.shippable.com/runs/584f2e3cbdca630f00231a38/1/console

No other output is given. Rebuilding results in the same failure immediately.

What is it about this PR that Shippable doesn't like?

One thing that comes to mind is that the committer name contains Unicode characters.

**Comment by mattclay** [comment]
The PR itself is here: https://github.com/ansible/ansible/pull/18437

**Comment by mattclay** [comment]
Here's another: https://app.shippable.com/runs/584f4f799559830f00090d96/1/console

The PR for it is here: https://github.com/ansible/ansible/pull/16657

**Comment by mattclay** [comment]
Here's another: https://app.shippable.com/runs/584f5b1ebdca630f00231f4b/1/console

The PR is here: https://github.com/ansible/ansible/pull/15896

**Comment by manishas** [comment]
@trriplejay @rageshkrishna we need to look into this.

**Comment by rageshkrishna** [comment]
@mattclay Do you mind if I try re-running these builds to see what's going on here?

**Comment by mattclay** [comment]
@rageshkrishna Feel free to restart builds as needed.

**Comment by trriplejay** [comment]
OK, I believe we've identified the cause.  In each of these cases, the PR was raised from a fork that contained a travis.yml but not the shippable.yml.  This seems to be an unhandled case in our job processor.

We'll have to discuss this scenario internally, but I think we will at the very least improve the error message.

**Comment by manishas** [comment]
@mattclay we have addressed this by showing an error message if the fork contains a travis.yml but not a shippable.yml. The fix should be deployed tomorrow.

**Comment by mattclay** [comment]
I'm seeing the new error now, instead of "Logs are not available."

Thanks.
