### ISSUE TITLE
How to run and access another docker container from CI build container

### ISSUE THREAD

**Issue by Zingoer** [Shippable/support#3232]
I try to create a database container and make CI build artifact connect with that container. However, everytime when I try to connect database container, I get connection timeout. I use the container_name:port way to connect to the database container which is work in docker compose locally. (https://app.shippable.com/runs/584f09d93a097e0f00d7ffca/1/console) Please ignore the ```liquibase: command not found``` The point is that I use the wait-for-it.sh to wait the db container to setup, however after 15 sec timeout, it still can't access the db container(usually it only need 1sec in locally). So I'm wondering that if that actually CI build container is not connect with the db container. However, when I use docker ps -a, I can see that db container is in the same bridge network as the CI build container.

db container inspect network section
```
[
{
    "Id": "39b88867bd586b65786a7769becc906575930b06080c38236171654aabf45a13",
    
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "965fbd04ea2ba9755922aef09b6218478890d509eb031e8a9a2168b42cb11adb",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "5432/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "5432"
                }
            ]
        }
        "Networks": {
            "bridge": {
                "EndpointID": "88536b224239f6d1b1d16aa9a5ef676051b68ee9cba353fd50a1fd5533104ba5",
                "Gateway": "172.17.0.1",
                "IPAddress": "172.17.0.5",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:ac:11:00:05"
            }
        }
    }
}
]
```
bridge network inspection
```

    {
        "Name": "bridge",
        "Id": "36156066723d3911b8ad4769d0d2659df6a5452a934195f6b494c1871908334b",
        "Scope": "local",
        "Driver": "bridge",
        "IPAM": {
            "Driver": "default",
            "Config": [
                {
                    "Subnet": "172.17.0.0/16"
                }
            ]
        },
        "Containers": {
            "2b0039415e1d8f272a350b019930e513f3e57033aef1483d60d0fcb0c51c1477": {
                "EndpointID": "5d2259e6b2176c5b7c980c208c2890df76efe0fbc68aefa07436ad121bcd7231",
                "MacAddress": "02:42:ac:11:00:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "39b88867bd586b65786a7769becc906575930b06080c38236171654aabf45a13": {
                "EndpointID": "88536b224239f6d1b1d16aa9a5ef676051b68ee9cba353fd50a1fd5533104ba5",
                "MacAddress": "02:42:ac:11:00:05",
                "IPv4Address": "172.17.0.5/16",
                "IPv6Address": ""
            },
            "3e9ebef3b9300305cb56f45d50cfd8caa67ae2ad6f3853d98d2ba56b672d186b": {
                "EndpointID": "994f4a49f4fa25773d8fafe98ad89706a14a72c6d4e366351c0ffe8584fa19bf",
                "MacAddress": "02:42:ac:11:00:04",
                "IPv4Address": "172.17.0.4/16",
                "IPv6Address": ""
            },
            "d84019dbac6e11088760763b9236b0753fabbd0b7b196e2e84e0d341cbb16952": {
                "EndpointID": "1659a4fb04ca23ea2bca99c6182b729ec7fad1ba38eac00ea04a194db1aefad7",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        }
```
 
Later on I tried to create another network which mentioned in #3135, I met multiple issues...

1.I try to remove the network I create and I get this error
```
 if [[ -n $(docker network ls --filter name=mynetwork -q) ]]; then docker network rm mynetwork; fi 0s  
flag provided but not defined: --filter
See 'docker network ls --help'.
```
But it works locally. I also tried ```-qf```, ```-q -f``` which all work locally. 

2. I try to download a tool called liquibase to update my database structure. However, I can't unzip it. Everytime in the middle of unzip, the post-ci will suddenly fail. Is there a time limition for post-ci? (https://app.shippable.com/runs/584f6d8dbdca630f0023205f/1/console)

I found it's very hard to setup env in CI build container for my component test before pushing the artifact. So Hope you would give some suggestion how I should create multiple docker containers from CI build container and link each other. Thank you!

**Comment by a-murphy** [comment]
Commands in the `ci` and `post_ci` sections run in the build container, but Docker is mounted so that Docker commands actually run on the host.  So `docker ps` or `docker run` will list the containers running on the host and start a new container on the host, respectively.  The result is that containers started from the `ci` or `post_ci` step are running alongside the build container, not in the build container.

One way to access other containers is to change the network of the build container.  Adding [`--net=host`](https://docs.docker.com/engine/reference/run/#/network-host) to `options` in [`pre_ci_boot`](http://docs.shippable.com/ci/shippableyml/#pre_ci_boot) will mean that the build container will consider the host machine to be `localhost` and not its own IP address, allowing the build container to find ports exposed by other containers.  If you would rather not use the host network, you could try starting your database container in `pre_ci` and using the [`--link` option](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/#/connect-with-the-linking-system).

Timeouts are documented [here](http://docs.shippable.com/ci/advancedOptions/timeouts/).  There are no special rules for `post_ci`.  The whole build gets an hour to run.

**Comment by manishas** [comment]
@Zingoer did the suggestion above help?

**Comment by Zingoer** [comment]
Sorry, my bad. It's very helpful and I final solve it using the --link option in the pre_ci_boot
Thanks for the shippable team!

**Comment by manishas** [comment]
:+1:

**Comment by thigm85** [comment]
@a-murphy When I try the  --net=host approach I get the following error right after 'boot_container' stage

```
sudo docker logs -f c.exec.prediction-engine.21.1 0s  
No LSB modules are available.
Distributor ID: Ubuntu Description: Ubuntu 16.04.2 LTS Release: 16.04 Codename: xenial
Ubuntu confirmed
Looking for apt-get...
Found apt-get at /usr/bin/apt-get
Looking for sudo...
Found sudo at /usr/bin/sudo
Looking for git...
Found git at /usr/bin/git
Looking for ssh-agent
Found ssh-agent at /usr/bin/ssh-agent
Looking for python...
Found python at /usr/bin/python
sudo: unable to resolve host ip-172-31-31-24
sudo: unable to send audit message: Operation not permitted
/home/shippable/cexec/build.sh: line 131:    20 Segmentation fault      (core dumped) $SUDO mkdir -p /shippableci
```

If I remove the --net=host everything works as expected (except the original issue of course of not being able to communicate with other containers created at the ci stage.)

Any thoughts?

**Comment by a-murphy** [comment]
I'm not sure why this is occurring, but it does appear to be a problem with the newest [machine image](http://docs.shippable.com/reference/machine-images-overview) (v5.5.1)  Switching to an older machine image on the subscription settings tab or [using your own node](http://docs.shippable.com/getting-started/byon-overview/) both work with `--net=host`.

**Comment by santtu** [comment]
I have run into the same problem of getting segv with v5.6.1 machine image. Using v5.5.1 didn't work either:

```
/home/shippable/cexec/build.sh: line 131:    18 Segmentation fault      (core dumped) $SUDO mkdir -p /shippableci
```

Version 5.4.1 did work, but none of the newer ones do (5.5.1 and 5.6.1). For the failure I have this in the shippable.yml file:

```
build:
    pre_ci_boot:
      options: "--net=host"
```

Taking `--net=host` out will mean the builder starts okay with 5.6.1 but of course, the build cannot complete (I need to be able to run postgres in a container and the build host needs to be able to access it for setup).

**Comment by kanthchandra** [comment]
@santtu can you please open a new issue so that we can keep things clean and also can you please point us to the build which failed with the error?
