### ISSUE TITLE
CI on Pull request

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#3233]
Am I correct when I test pull request from DEV to STAGE - Shippable use code from stage branch?

**Comment by rageshkrishna** [comment]
If you haven't changed any project settings, you will see two builds kicked off when a PR is opened or updated:

1. The PR's head branch itself is built as-is. You see this as a commit build on the head branch.
1. The PR's head branch is merged in to the base branch on Shippable and the resulting code is built. You see this as a merge build on the base branch.

I hope this clarifies what happens. Let me know if you have more questions.

**Comment by manishas** [comment]
Closing this since it is answered.
