### ISSUE TITLE
Build failing immediately on provisioning node

### ISSUE THREAD

**Issue by mattclay** [Shippable/support#3234]
I'm seeing builds failing immediately on provisioning node:

https://app.shippable.com/runs/5851e7c2938d4210003bd3a5/1/console
https://app.shippable.com/runs/5851eaf0ea2e1e0f00a1f927/1/console

**Comment by trriplejay** [comment]
looks like a dup of:
https://github.com/Shippable/support/issues/3056
https://github.com/Shippable/support/issues/3201

we're in the process of getting this fixed, but for now, umatched backticks in the commit message will cause this type of failure.
