### ISSUE TITLE
Unable to login to the app using Bitbucket

### ISSUE THREAD

**Issue by bhargav3** [Shippable/support#3235]
I was using Shippable with Bitbucket login and suddenly I'm not able login and all I see a error 400 page. I tried to logout, clear cookies, tried logging in from different browser and nothing worked. Here is the screenshot of the error. Please help.

<img width="1402" alt="screenshot at dec 15 17-37-27" src="https://cloud.githubusercontent.com/assets/949476/21223507/7dc83d70-c2ed-11e6-9fa0-55085f3da64a.png">

**Comment by shrivara** [comment]
@bhargav3 This should be fixed for you now. Could you try logging in again?

**Comment by bhargav3** [comment]
It's fixed now. Thanks.
