### ISSUE TITLE
Shippable is ... slow.

### ISSUE THREAD

**Issue by rollcat** [Shippable/support#3236]
Our builds are getting stuck for 20-30min at a time, while provisioning node, syncing git (from Bitbucket), etc. We're not having much issues pulling from bitbucket on an ordinary EC2 instance.

- Link to the build failure: https://app.shippable.com/runs/5852c39efbf7600f0078ec92/1/console
- Scripts called from the yml (optional): didn't get there
- Screenshot: https://imgur.com/a/dlszh

What's going on guys?

**Comment by trriplejay** [comment]
Hey there,

Looks like there was some issue on aws with one of your nodes experiencing degradation of underlying hardware. We've terminated the node. It looks like your other builds are running normally.  Let us know if you are still seeing issues.

**Comment by manishas** [comment]
Closing this issue. We will look into making this scenario where AWS gives us a degraded node more reliable in the future.
