### ISSUE TITLE
How to get coverage metrics with JaCoCo for a non-standard layout?

### ISSUE THREAD

**Issue by gdemecki** [Shippable/support#3238]
### Description of your issue:
Recently I've heard great news, you at Shippable support JaCoCo for JVM-based projects. I wanted to try it, but after 4 hours no success.

I have a Java + Maven multi-module project for which I'm calculating a combined report (firstly merge all jacoco.exec files and then generate one report). Everything works fine with maven. But I don't know how to get it working with a Shippable visualization.
Although build and tests are green, there is always a message: *No coverage reports for this build*.
I guess this might be because my directories layout is not standard. So I'm stuck.

On the [http://docs.shippable.com](http://docs.shippable.com/tutorials/ci/integrations/codeCoverage/usingJacoco/) I can read:

```yml
  # mvn install will create a `target` folder which will contain a jacoco.xml
  # jacoco.xml will be present at path `target/site/jacoco/`
  - mvn install

  # copy this target folder to the `shippable/codecoverage` folder
  # target folder should have `/site/jacoco/jacoco.xml` file
  - cp -r target shippable/codecoverage
```

So I had assumed somehow that all what is needed is a correct jacoco.xml file at  `shippable/codecoverage/target/site/jacoco/jacoco.xml`. But I guess it's not true, is it?

I've tried a lot of things, like copying `jacoco.exec` with all classes to the `shippable/codecoverage/target` - but it also didn't work.

Part of my `shippable.yml` looks like below: 
```yml
  - cp -r  coverage-report/target/combined-coverage/*   shippable/codecoverage/target/site/jacoco
  - cp -r  coverage-report/target/jacoco.exec  shippable/codecoverage/target/site/jacoco
  - cp -r  module-one/target/classes    shippable/codecoverage/target
  - cp -r  module-two/target/classes    shippable/codecoverage/target
```
(ps. `combined-coverage` is equivalent of the `site` folder and `coverage-report` is a separate module for aggregating all jacoco.exec files.)

Any clues?

// most of all, please tell me what exactly are the minimum requirements, to have a working visualization?

Regards,
Greg

**Comment by trriplejay** [comment]
From taking a look at your build, at a glance it seems like you are taking the correct steps. I'll dig into this a bit today and see if we might have some kind of bug in our parsing.  Your assumption about the xml needing to be there is correct, but it's possible that our parser is having trouble with the combined report as you mentioned.

**Comment by manishas** [comment]
we're working on a  fix for this, ETA is tomorrow.

**Comment by gdemecki** [comment]
Thanks everyone.
I've checked today and it works perfectly fine now. I'm closing this issue.
