### ISSUE TITLE
Custom timeouts larger than 7200000 milliseconds

### ISSUE THREAD

**Issue by jeppefrandsen** [Shippable/support#3239]
Would it be possible to support custom timeouts larger than 7200000 milliseconds when using BYON?

We are sometimes building new docker images on our own build servers. This takes quite some time (a bit over 2 hours) due to the use of yocto (downloads packages, compiles, installs etc.). We are doing some caching but still takes time. We could of cause buy larger build machines but this also has a cost.

Thank you very much in advance.

Kind Regards,
Jeppe (Bang & Olufsen a/s)

**Comment by manishas** [comment]
Thanks for the suggestion. I'll discuss this with the team and get back to you.

**Comment by jeppefrandsen** [comment]
Hi @manishas. Did you discuss with the team? Thanks.

**Comment by manishas** [comment]
@jeppefrandsen yes, i discussed this with the team and we're going to allow subscriptions with BYON to set larger timeouts. The team is out next week but we'll get to this first thing in Jan and it should be available before mid January. i hope that works.

**Comment by jeppefrandsen** [comment]
@manishas Thank you so much! Really great! 👍

**Comment by jeppefrandsen** [comment]
@manishas do you know if it will be available this week or? Thanks once again.

**Comment by rageshkrishna** [comment]
@jeppefrandsen This will be available next Friday (January 13).

**Comment by rageshkrishna** [comment]
@jeppefrandsen Unfortunately, due to other issues this fix will be delayed and not be available today. 

The backend is ready, but it's still not possible to configure bigger values from the UI or API. If you can tell me the timeout value you want and the projects you want it on, I can update the system manually to enable it right away on your projects.

The complete feature (including UI update) will be deployed next Friday (January 20).

**Comment by jeppefrandsen** [comment]
@rageshkrishna No worries. Can you configure it for the ASE project to 180 minutes (3 hours)? Thanks a lot

**Comment by rageshkrishna** [comment]
@jeppefrandsen It's done. You should see the timeout in effect immediately.

**Comment by jeppefrandsen** [comment]
@rageshkrishna can you increase timeout to 4 hours. 3 was unfortunately not enough in all cases. Thanks a lot once more!

**Comment by rageshkrishna** [comment]
@jeppefrandsen I've updated it to 4 hours. Let me know if you need any more adjustments!
