### ISSUE TITLE
No scm accountIntegrations found for account id

### ISSUE THREAD

**Issue by legendik** [Shippable/support#3240]
Hi,

I'm unable to enable new project (private repository). I can see the private repository on page "Enable project" (repository name `damejidlo/geocoder`). But after click on `Enable` i'm getting error:

```
(Id: 4005) No scm accountIntegrations found for account id: 550b01355ab6cc1352a52a84
verbose: projects|getById|callerId:584963a8307b1f0f00501a3e|projectId:5649e6e91895ca44742396db|_getOwnerScmAccountIntegrations
```

SCM integration for Github is created. I can enable other private repositories from same organization, but not this one.

I've tried to add new Github integration with new Github API key, but the result is same :(

**Comment by rageshkrishna** [comment]
@legendik Can you please try this again? You should be able to enable your project now. Let me know if you're still running in to this. 

In case your GitHub integration is still giving you trouble, please logout and login.

**Comment by legendik** [comment]
@rageshkrishna Thank you, it's working now! :)
