### ISSUE TITLE
Each dashboard item displayed twice

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3241]
Every item on our dashboard is displayed twice.

This has happened a few times, but isn't consistent. Sometimes the items are duplicated, sometimes they aren't.

Please see the image below:

![screen shot 2016-12-19 at 10 45 21 am](https://cloud.githubusercontent.com/assets/1018189/21318733/77392eb8-c5d8-11e6-9a08-33c438050dee.png)

**Comment by rageshkrishna** [comment]
Hi @ryan-kimber, is this happening to you all the time or is it a sporadic thing?

**Comment by jeppefrandsen** [comment]
Have seen the same when launching app.shippable.com. After reloading everything seems ok

**Comment by harryi3t** [comment]
We have fixed the issue and this should not be happening anymore after the next production deployment (which should be in the next couple of days).

**Comment by harryi3t** [comment]
The fix is in production now.
You should not be having this issue any more.
