### ISSUE TITLE
How to filter multiple bitbucket projects?

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#3242]
Hi,

We do have 3 dev teams working on one one bitbucket "team" see ([bitbucket large team approach](https://confluence.atlassian.com/bitbucket/bitbucket-cloud-teams-321853005.html#BitbucketCloudTeams-Largecompanywithseparateteams)) and I was wondering how we can manage to see only the builds for our respective projects.

We can do this for the SPOG by using filter flags but I do not see something similar for CI builds. How is Shippable envisioning to support this? Could a project(s) filter be added to the CI build dasboard?

thanks

**Comment by manishas** [comment]
@Kirtap co-incidentally we were just discussing this yesterday with another customer. there is no way to customize the dashboard right now, but this is certainly on our radar in the next few weeks.

**Comment by Kirtap** [comment]
Thank You Manishas,

Our CI dashboard is starting to look rather cluttered now so I am really happy to know that this is on your short term backlog.

**Comment by Kirtap** [comment]
Hi Manishas,

any update on this? We are adding our 3rd team soon and it will become quite crowded on our build dashboard....

thanks

**Comment by rageshkrishna** [comment]
@Kirtap This is now available. The docs are at http://docs.shippable.com/navigatingUI/accountSettings/myDashboard/
