### ISSUE TITLE
'Owner not found' when trying to enable a gitlab CE repo

### ISSUE THREAD

**Issue by knowredev** [Shippable/support#3243]
When I try to integrate shippable to my gitlab CE and enable a repo, the following error message comes out. I can see the gitlab account and repo but cannot enable it.

The error message is:

```
(Id: 2002) Owner not found for projectId:58579de6f1e544100066d502
warn: projects|getById|callerId:566ff1261895ca4474665b13|projectId:58579de6f1e544100066d502|_getProjectOwner
```

Seems like this is the identical problem with #2794, the closed issue.

My shippable ID is: 566ff1261895ca4474665b13
GitLab CE version: 8.13.3-0

**Comment by manishas** [comment]
@knowredev are you an admin for the gitlab repo? Please check out the troubleshooting qs here - http://docs.shippable.com/ci/troubleshoot/#owner-not-found

**Comment by Kivol** [comment]
@mantishas Yes I'm sure it is the admin account because it is the only account(generated on installation) on my gitlab.

**Comment by knowredev** [comment]
I tried reinstallation of Gitlab CE and it shows the same error as before:
```
(Id: 2002) Owner not found for projectId:585a294e8171491100bbd9e6
warn: projects|getById|callerId:566ff1261895ca4474665b13|projectId:585a294e8171491100bbd9e6|_getProjectOwner
```

**Comment by manishas** [comment]
@rageshkrishna can we look at this?

**Comment by shrivara** [comment]
@knowredev We're seeing a 404 when we try to `GET <gitlabURL>/api/v3/projects/knowre%2FDaekyoAPI_KR` which is why we're unable to obtain the owner. Could you try to this API call with your token and let us know if this works for you?

**Comment by knowredev** [comment]
@shrivara You're right, it shows 404 when querying through your URL, but that kind of API call is not enlisted on gitlab API document. ( https://docs.gitlab.com/ce/api/projects.html )

Instead, `GET <gitlabURL>/api/v3/projects/:id` seems working well when inserting `:id` as 1.

**Comment by shrivara** [comment]
@knowredev Gitlab also supports `NAMESPACE/PROJECT_NAME` format as documented [here](https://docs.gitlab.com/ee/api/projects.html#get-single-project). Maybe you're serving Gitlab behind a reverse proxy that unescapes this?

**Comment by knowredev** [comment]
It worked!!!

For those who will Google later, here's the walkthrough:

I was using Bitnami's gitlab AMI for EC2 instance, and I added `PassengerAllowEncodedSlashes On` next to the line `AllowEncodedSlashes NoDecode` of `/opt/bitnami/apps/gitlab/conf/httpd-app.conf`, and restarted Apache with command `/opt/bitnami/ctlscript.sh restart apache`.

Thank you very much, @shrivara .

**Comment by shrivara** [comment]
Awesome! Do let use know if you have any other problems, or questions with this.
