### ISSUE TITLE
Unable to remove github integration from shippable

### ISSUE THREAD

**Issue by RyanShelf** [Shippable/support#3244]
Not sure if this is the right place for this but when I go to remove my github integration i'm hit with an error message with the following information:

(Id: 4001) subscriptionIntegrations.destroy failed for id: 3996 returned error: update or delete on table "subscriptionIntegrations" violates foreign key constraint "resources_subscriptionIntegrationId_fkey" on table "resources"
verbose: subscriptionIntegrations|deleteById|callerId:570288f72a8192902e1b89b7|id: 3996|_deleteById

I was hoping someone could assist me at removing our github integration, thank you.

**Comment by manishas** [comment]
@RyanShelf can you share more information about why you're trying to remove the github integration?

If you signed into Shippable with github, that is an integration we create automatically and it cannot be removed since that is your primary method of signing in.

**Comment by RyanShelf** [comment]
haha that makes sense, sorry to bother. I figured out the solution to my problem (done via removing access through github)
