### ISSUE TITLE
matplotlib freetype cannot be built

### ISSUE THREAD

**Issue by Borda** [Shippable/support#3248]
### Description of your issue:
I am not able to install `pip install matplotlib==1.3.1` because the required library freetype is missing

> freetype: no  [pkg-config information for 'freetype2' could not be found.]

please see the [jobConsoles.log.txt](https://github.com/Shippable/support/files/669424/jobConsoles.log.txt) file, line 259
and configuration [travis.yml.txt](https://github.com/Shippable/support/files/669433/travis.yml.txt) file

what am I missing in the config file?

**Comment by rageshkrishna** [comment]
Hi @Borda! I've found that running `apt-get install freetype*` before `pip install matplotlib` allows it to succeed. I'm not really sure if we need _all_ of the freetype packages to do this, but hopefully this gives you something to work with.

**Comment by Borda** [comment]
Well, where should I put it in to the file?
```
before_install:
  - apt-get install freetype*
```
or
```
install:
  - apt-get install freetype*
```
because neither option seems to work (tried both in costume build)

**Comment by rageshkrishna** [comment]
The "custom build" feature currently only allows you to inject new environment variables. It doesn't let you inject new commands into the build. Please add the commands to your YML file. `before_install`, or the first step of the `install` should do fine.

I put up a quick test project [here](https://github.com/rageshkrishna/test-matplotlib/blob/master/shippable.yml), and you can see that [the build successfully installed matplotlib](https://app.shippable.com/runs/585cf5c9e18a291000c1a68b/1/console).

**Comment by Borda** [comment]
Oki, it works. Thanks
