### ISSUE TITLE
Hanging build

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3250]
This build has failed, but is not finishing. There is no running process on the nodes.

https://app.shippable.com/runs/585d165407d5371300725bef/1/console

Could you kill that job?

**Comment by bbrala** [comment]
Hmm, build are now not starting for that project. Get an error on it when i try to delete is (to fully reset)

(Id: 4004) No projects found for projectId(s): 5469e45ed46935d5fbbdcc71

**Comment by manishas** [comment]
@bbrala is this still happening? I see a later build for that project so just checking...

**Comment by bbrala** [comment]
Ok, everything is in working order again. Can even delete/sync/etc the project again.
