### ISSUE TITLE
Provisioning job nodes timing out again

### ISSUE THREAD

**Issue by rarkins** [Shippable/support#3253]
All my builds are timing out or failing due to Shippable issues right now.

e.g. this types of provisioning job node timeouts:

![image](https://cloud.githubusercontent.com/assets/6311784/21502230/b79407c2-cc4e-11e6-98cd-cfcde986c20f.png)

**Comment by rarkins** [comment]
Some have provisioned but then timed out while pulling images from Docker Hub

**Comment by rarkins** [comment]
They have begun provisioning and working again.

**Comment by rarkins** [comment]
Builds are stuck on "Provisioning a node for subscriptionId: 54d872f85ab6cc13528b4023" for the past hour. No job nodes are being provided, even if I cancel the build and retry it.

**Comment by rarkins** [comment]
Still happening for most builds! If you can't even get builds to reliably start, how do you expect to retain customers?

**Comment by kanthchandra** [comment]
Hi @rarkins sorry that you are running into this issue. I'm looking into this and I'll update the issue as and when I have more details.

**Comment by rarkins** [comment]
@kanthchandra thanks. As usual, builds have started working again, although of course the ones that timed out are not automatically retried.

This job node provisioning problem causes too much manual intervention from your users. As a CI provider, surely getting at least 99.9% successful job node provisioning is a must-have?

Here are some since last night that timed out or I needed to cancel:
https://app.shippable.com/runs/586413fbf6c7101000c389e3/1/console
https://app.shippable.com/runs/58641ab7e18a291000c2d2c4/1/console
https://app.shippable.com/runs/58641ce9666b4b1000d1b9ed/1/console
https://app.shippable.com/runs/58641f39e18a291000c2d366/1/console
https://app.shippable.com/runs/5864d1343b5313100043365a/1/console

**Comment by kanthchandra** [comment]
@rarkins I looked at every single subscription that was running builds at the moment and all of them had nodes provisioned (including unstable ones). So it's not a system wide problem and is an isolated case where the build runner doesn't spin up correctly.

We have some leads on why this is happening and we will be addressing those issues and also harden the node provisioning flow in the next release.

**Comment by jmarver** [comment]
We're getting the timeouts as well: https://app.shippable.com/runs/58644462b1bb441000bb25bf/1/console

**Comment by jmarver** [comment]
We encountered another timeout again today: 
https://app.shippable.com/runs/586d80513b5313100045702d/1/console

**Comment by kanthchandra** [comment]
Hi @rarkins, We have implemented the logic for re provisioning nodes for stuck builds and we are in the process of testing it. So this will be available by with the next release (Around Jan 20). Thanks for your patience.

**Comment by rarkins** [comment]
@kanthchandra thanks for the info

**Comment by manishas** [comment]
@kanthchandra if this was included in our latest deployment, can you please confirm and close this issue?

**Comment by kanthchandra** [comment]
@manishas Yes, we have fixed this in our latest issue. For some reason if the jobs get stuck, now we reprovision the nodes. @rarkins Please let us know if you run into this again.
