### ISSUE TITLE
How do I get shippable to use git as a specific user?

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3256]
I need to have our build push things back to the GitHub repository (`npm version` being used, new package.json and tags must be pushed). It works ok using the deploy key, however, we have restrictions on who can push to master (using GitHub protected branches), and using the deploy key doesn't have an associated user in GitHub so I can't specify that Shippable should be able to push to master (an no one else but admins should). So, I created a GitHub account for our build user and gave him access push to the master branch. I removed the shippable deploy key from the repo, and added this to the SSH keys of the new build user. However, when the build tries to sync with GitHub, it fails with publickey error. If I log into GitHub with the build user and examine the SSH keys, it indicates that the SSH key has never been used. 

I feel like I'm missing some step somewhere to tell shippable what GitHub user to use when it does the `clone` (and later in my script where I do a push). Has anyone ever done a setup like this before where you use a machine user instead of GitHub deploy keys? Any clues on how to get this scenario working?

**Comment by npahucki** [comment]
BTW: I did see this already: https://github.com/Shippable/support/issues/1669. I can get it all to work if I *don't* have any restrictions on the master branch, but I need DO need to have the restrictions, hence why I tried creating a GitHub user for the build.

**Comment by npahucki** [comment]
Ok, now I'm even more confused. I decided to go back to playing around with the deploy key (instead of build user). So I copied the key from the subscriptions, and put this back into GitHub deploy keys. Now I STILL get a publickey error, and the dpeloy key shows that it is never used. I went to compare with a repo that is still working, and that deploy key (which shows it was used this morning) has a different fingerprint than the one that is working. I ran `ssh-keygen -E md5 -lf key.txt` on the public key shown in the integrations page, and this gives me the same fingerprint as the one in the now non-working repo, and different than the working repo. Is the UI showing the WRONG key here? If not, where did the working key come from and why it is not shown in the UI?

Working repo: https://app.shippable.com/projects/56c5f9ff1895ca4474745ddb/status/
Now non working repo: https://app.shippable.com/projects/5703ede72a8192902e1b9a06/status/

Working key fingerprint: ee:4c:f2:3b:f8:aa:6d:2e:69:34:d7:6d:91:4f:8b:49
Non working (shown in https://app.shippable.com/subscriptions/56c5f9fd1895ca4474745dd3/settings/options) fingerprint: c0:ea:78:fc:a0:0b:2f:b2:8b:47:98:71:25:35:40:c3

I'm quite confused about what happened here.

**Comment by npahucki** [comment]
ok, I Reset the project which automatically puts a new deploy key in GitHub...I'm just realizing that the key shown in the UI at https://app.shippable.com/subscriptions/56c5f9fd1895ca4474745dd3/settings/options is NOT the one used for github. 

So the question is, how would I get the public key so that I can add it to a user instead of as a deploy key?

**Comment by rageshkrishna** [comment]
@npahucki You're right, the deploy key we add to the project on GitHub is not what you see on the subscriptions page.

This key is currently only available with an API call -- `https://api.shippable.com/projects/:projectId` will give you the `deployPublicKey` property. I think this is what you need. Please let me know if I've misunderstood what you're looking for.

**Comment by npahucki** [comment]
Thank you, thank answers my question. I'll close the issue.
