### ISSUE TITLE
Update Status Dashboard to show tags and releases

### ISSUE THREAD

**Issue by grandmore** [Shippable/support#3258]
Currently the Status Dashboard page only shows branches. However I am using releases and tags as the trigger to build images. 

What shows is an empty master branch which never builds( which is correct) but does not show any tags or release's.

I can click on history to see what was build but it seems that it should be displayed just like branches on the dashboard.

**Comment by avinci** [comment]
This is present in the new UI we launched a few weeks back. Please let us know if this works for you.
