### ISSUE TITLE
can't revert to the free plan

### ISSUE THREAD

**Issue by etoccalino** [Shippable/support#3262]
I'm trying to cancel our subscription and go back to the free plan. I followed the instructions on #1976, but find the "Enable free plan" button is disabled.

![enable-free-plan](https://cloud.githubusercontent.com/assets/493706/21646011/36b493da-d273-11e6-8bba-0ff548527d58.png)

Is there a way to disable our plan and remove the credit card information from my account?

**Comment by a-murphy** [comment]
We've updated your subscription to the free plan for you.  The button was improperly disabled as a result of some old pipelines purchased for the subscription.  Up-to-date documentation on removing cards is available [here](http://docs.shippable.com/navigatingUI/accountSettings/cards/) if you would like to try to remove your card now.

**Comment by etoccalino** [comment]
confirmed. thanks!
