### ISSUE TITLE
Feature request: more browsers in for CI

### ISSUE THREAD

**Issue by popelnuh** [Shippable/support#3263]
Hi There,

Not an issue but a feature request.

Is it possible to have more browsers pre-installed, this is required for the Selenium regression tests. 

Thank you!

**Comment by avinci** [comment]
@rageshkrishna did we add more browsers in this version? @popelnuh you could also extend our images and push it to docker and use that as a base image. The only issue being, it will download that on every build. 

We are updating our images and I was wondering if you wanted any particular browsers for your tests.

**Comment by rageshkrishna** [comment]
We have Chrome, Firefox and Opera. All of them will be the latest releases in the images we launch this week. No other browsers have been added yet.

@popelnuh Please let us know what browsers you're looking for. We may be able to squeeze it in this week. Thanks.

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.
