### ISSUE TITLE
rpc error: code = 2 desc = "containerd: container did not start before the specified timeout"

### ISSUE THREAD

**Issue by jmarver** [Shippable/support#3265]
We've seen this error a couple of times over the last week:
rpc error: code = 2 desc = "containerd: container did not start before the specified timeout"

https://app.shippable.com/runs/58643114e18a291000c2db8d/1/console
https://app.shippable.com/runs/586e9cf49a67460f0095452d/1/console

**Comment by stephanielingwood** [comment]
Hi @jmarver,

Thanks for letting us know. While we don't see it that often, this is a [known issue](https://github.com/docker/docker/issues/24574) with Docker 1.11.1, which is what is in the unstable machine image. If you're able to use the stable machine image, that's using 1.9.1, and isn't prone to this error (as far as we know). If you decide to switch machine images, that can be done in the Subscription Settings tab.

Hope this helps. Let us know if you have any other questions.

**Comment by jmarver** [comment]
Hi @stephanielingwood, 

Thanks for the reply and the additional information. Yes, we're able to switch back to using the stable machine image, Docker 1.9.1. 

We were hoping to use Docker 1.11.1 to take advantage of [wildcard support in .dockerignore files] (https://github.com/docker/docker/pull/17090) but we can use a workaround until Shippable deems Docker 1.11.1 or newer to be stable. 

Thanks again.
