### ISSUE TITLE
Provision job node TIMEOUT errors

### ISSUE THREAD

**Issue by jmarver** [Shippable/support#3266]
We're also seeing the provisioning job node timeout errors:

https://app.shippable.com/runs/586d80513b5313100045702d/1/console
https://app.shippable.com/runs/58644462b1bb441000bb25bf/1/console
https://app.shippable.com/runs/5859be085de9af10007fdcae/1/console
https://app.shippable.com/runs/58587ae2f1e5441000674cb8/1/console

**Comment by manishas** [comment]
@jmarver apologies for the delay in looking into this. are you still experiencing these timeouts?

**Comment by jmarver** [comment]
H @manishas , thanks for the reply. I appears the timeouts have stopped so I'll close this ticket.
