### ISSUE TITLE
Cannot download invoice

### ISSUE THREAD

**Issue by legendik** [Shippable/support#3271]
Hi,

I'm getting following error while trying to download any invoice:

{"logType":"verbose","methodName":"transactions|getReceiptById|callerId:584963a8307b1f0f00501a3e|transactionId:58678fdfe18a291000c387f8_getAccountById","id":4001,"message":"getAccountById for id: 550b01345ab6cc1352a52a82 returned error: account not found for :accountId 550b01345ab6cc1352a52a82"}

**Comment by stephanielingwood** [comment]
Hi @legendik,

Sorry you're seeing this. It looks like the account that set up the billing (and whose card was being billed) has been deleted - which unfortunately means those receipts are no longer accessible. If you need the amount of the charge, that's available for you on the billing tab for the subscription.

Hope this helps. Let us know if you have any other questions.

**Comment by legendik** [comment]
I'm sorry but this is not enought for our financial department. Can you please regenerate only december invoice manualy?

And what about future invoices?

**Comment by manishas** [comment]
@legendik I can send you the December receipt over email. What email address would you like me to send it to?

**Comment by legendik** [comment]
`marek.sneberger@damejidlo.cz`, thanks ;)

The future invoices will be there?

**Comment by avinci** [comment]
We are working on revamping this piece up. You should be able to see future stuff.

**Comment by legendik** [comment]
@manishas Can you please send me the invoice over email?

**Comment by manishas** [comment]
this is done, closing.
