### ISSUE TITLE
question: How to limit to pull request branches?

### ISSUE THREAD

**Issue by GuyMograbi** [Shippable/support#3273]
Hi, 

I would like to limit my builds to pull requests only. 
How can I do that? 

I am using a private repo on bitbucket without forks. 

Thanks.

**Comment by a-murphy** [comment]
Commit builds may be disabled on the project settings tab.

From the project page (click on the project name on a build page if you can't find it):
1. Click on the "Settings" tab on the top.
2.  Then click "Runs config" on the left.
3. Commit webhook builds can be disabled under "Configure Webhook Events for Triggering Builds." 

Documentation on the options in this section is available [here](http://docs.shippable.com/navigatingUI/projects/settings/#configure-webhook-events-for-triggering-builds).  It won't stop you from building commits manually, but will prevent commit builds running automatically while pull request builds continue to run.

**Comment by manishas** [comment]
Closing.
