### ISSUE TITLE
Can I get a bigger Docker to run our tests? 

### ISSUE THREAD

**Issue by vivekna1** [Shippable/support#3274]
currently its 4gb ram and CPU - 2 cores ( not sure of the speed)
Our tests are taking a lot of time to run, so can this be increased/ configured ? 

Alternatively, Can we connect to an ElasticBeanstalk in BYON model.

**Comment by avinci** [comment]
You can potentially create Custom Nodes and achieve this. This might not be the best case scenario for you as now you have a machine that is running all the time for builds. Are you looking for dynamic nature with custom hosts and hence you are looking for EBS?

It might be an interesting experiment to try but from a real use, EBS will add quite a bit of tax with its layer and then pushing stuff to it will have to be s3 etc. 

Actually if you need dynamic way of doing this, you can use our pipelines to achieve it. commit to repo, will trigger and provision node job (can be any size any cloud) and then once this is successful then you run CI on top of it and once CI finishes you destroy the machine. 

Lastly, we have thought about offering bigger machines at a higher price, would you be interested in that?

**Comment by avinci** [comment]
closing this due to lack of response

**Comment by manishas** [comment]
We just launched bigger nodes. Our regular nodes are c4.large so they have 2 cores, 4gb RAM. 

You can now upgrade to c4.xlarge (4 core, 7.5gb) or c4.2xlarge (8 core, 15gb) from your billing page.
