### ISSUE TITLE
Tests Directory

### ISSUE THREAD

**Issue by herriojr** [Shippable/support#3276]
I'm not a big fan of having to copy the tests to a separate directory for my builds. If the tests fail, it will only be copied if there is code in on_failed to copy it over to the directory, which means I need to duplicate the copy code.  It would be easier if it were just a configuration option to tell shippable where the output of tests exists as it would simplify the process.

**Comment by avinci** [comment]
Thanks for the suggestion, we have thought about this in the past and since we had not seen very many people complain about it, it never made it to a release. I will just keep it open and see if people want to +1 it.

**Comment by mbrodala** [comment]
I can only talk about our case but we can simply run PHPUnit accordingly as documented and everything (test and coverage output) is put in the expected location.

What are you using and are you not able to configure the output location?

**Comment by herriojr** [comment]
sbt with scoverage -- the documentation is a bit obtuse, so it may be possible.  My googlefu could be off as well.

**Comment by avinci** [comment]
closing it. I prefer to keep the tests, coverage directory deterministic as we are going to be adding analytics to the reports etc. Heuristically finding this mean it will be error prone and would like to avoid it if its possible...

Thanks for letting us know you pain point.
