### ISSUE TITLE
Pipelines: Support Task Placement in ECS

### ISSUE THREAD

**Issue by BlueDragonX** [Shippable/support#3278]
ECS allows you to set options for task placement on a service. It would be beneficial if Shippable supported setting these parameters in the pipeline.

**Comment by avinci** [comment]
We will implement this feature in our next sprint.

**Comment by manishas** [comment]
This is now available. We have added support for placementStrategy in the dockerOptions resource. Docs at http://docs.shippable.com/pipelines/resources/dockerOptions/#amazon-ecs

Please let us know if you have any questions.
