### ISSUE TITLE
Support for OpenJDK8 in build matrix

### ISSUE THREAD

**Issue by MateuszKubuszok** [Shippable/support#3282]
Could you add support for OpenJDK8? Currently There is only support for Oracle JDK8 or older versions of OpenJDK.

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.

**Comment by robmoore** [comment]
I'm having timezone issues with the OpenJDK and want to confirm that `tzdata-java` is installed as well?

**Comment by rageshkrishna** [comment]
@robmoore What version of OpenJDK are you using and which drydock image are you running it on?

**Comment by robmoore** [comment]
@rageshkrishna I'm using OpenJDK8 with 5.3.2.

**Comment by robmoore** [comment]
@rageshkrishna I think I may have found the issue that's causing this. Please see https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806. I followed the approach outlined here with success: https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806/comments/4

**Comment by rageshkrishna** [comment]
Glad you found a workaround.

It looks like [tzdata-java is no longer available in Ubuntu 16.04](https://askubuntu.com/questions/795901/what-happened-to-tzdata-java-in-xenial-16-04) because of some missing dependencies from OpenJDK 8. I don't think there's anything we can do in our images to work around this.

**Comment by robmoore** [comment]
I think this is an issue that could arise with OracleJDK8 as well as it's really an OS-level issue.
