### ISSUE TITLE
How to implement a certain workflow

### ISSUE THREAD

**Issue by darilldrems** [Shippable/support#3283]
cc: @trriplejay @manishas 

I will like to set shippable up in the following way:

- when a PR is done, shippable should run build but not aws integration
- when we merge the PR to master branch shippable should run build for master and if successful run integration deploy to aws
- when we merge the PR to dev branch shippable should run build for dev branch and if successful run integration deploy to aws

How can I achieve this flow?

**Comment by avinci** [comment]
@darilldrems when you say but not aws integration on your first bullet, could you elaborate a bit. Not sure i understand that part.

I am guessing you are talking about CI to pipelines connection? If you CI connector, its not possible to do this. We are making this happen in Feb and it should work. In the meantime,

- Do you use matrix functionality?
- Do you care about test reports and coverage visualization?

If No to above, we can do it today. Let me know what your thoughts are...

**Comment by avinci** [comment]
@chetantarale we should look into this.

**Comment by avinci** [comment]
We have implemented a bunch of new features and updated our docs/blogs. Please let us know if this issue needs attention.
