### ISSUE TITLE
Random failures as of late

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3284]
The last week or so, I see a lot of failed build with the following in the log: 

```
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/919f913a-7e5a-4076-8222-be620e8d9348.sh'
Exception Invalid or no script tags received
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/919f913a-7e5a-4076-8222-be620e8d9348.sh'
Exception Invalid or no script tags received
```

Here is one such example: https://app.shippable.com/runs/58791b4b79509c100049d0ea/1/console

**Comment by npahucki** [comment]
Anyone? This is becoming a real problem, about 1/3 of the builds fail with this errors, right after npm install.

**Comment by npahucki** [comment]
@shrivara can you have someone look at this pls, it's been 4 days since I opened this and not even a comment on it yet. Thanks.

**Comment by npahucki** [comment]
Here is another example if you need one: https://app.shippable.com/runs/587e6e6b79509c10004b5cc4/1/console

**Comment by trriplejay** [comment]
It looks like something is causing your build script to exit suddenly. We're investigating.

**Comment by npahucki** [comment]
Anything guys? We are having a really hard time when I need to rerun over 50% of the builds which take 15 minutes each.

**Comment by trriplejay** [comment]
we haven't been able to reproduce this. our best guess so far is that something in your npm install is running its own script which may be exiting with a bad code, causing our handler to treat it like a build failure.  Would you be able to provide us with your package.json?

**Comment by npahucki** [comment]
I will provide the package.json but I don't want to attach it here. Please send me an email address to which I can send it.

**Comment by trriplejay** [comment]
john@shippable.com

thanks.

**Comment by trriplejay** [comment]
Still haven't been able to reproduce. using your package.json, we've run many builds and have yet to see the failure ourselves.  Our builds don't include every piece of the package.json, though. Any chance one of your subscription's specific dependencies might be causing this?

**Comment by npahucki** [comment]
Dependencies like what? Declared in the NPM? They all come from npmjs.org. 
It still happens a few times a day....what can we do to troubleshoot it when it happens? I want to see which process exits with non zero, I want to see error messages - right now I don't have any of that information, so I can't even do anything on my end. That would be the biggest help - help me instrument the build to get me that information.

**Comment by trriplejay** [comment]
well, the ones specifically associated with your org are private, so we took those out of our test, and haven't been able to reproduce. 

The reason there are no error messages is that this seems to be exiting the script in a way that bypasses our build runner's error handling. Do you spawn some kind of concurrent background process as part of this step?

**Comment by npahucki** [comment]
The private ones are very simple and have no scripts at all running with them, I highly doubt this has anything to do with the problem. There is nothing funny going on during npm install, it's pure putting files on the hard drive (which BTW, it looks like it does finish doing).

Is there no way you guys can run repeat one of the existing builds that has failed? I meant, I imagine that an admin there should be able to trigger our builds (including installing all the private modules) in a controlled environment. 

One other thought - could npm install be running out of memory on the install? See this thread: https://github.com/npm/npm/issues/9884 - when exiting due to memory constraints. I can try to limit the memory with `node --max_semi_space_size=1 --max_old_space_size=198 --max_executable_size=148 /usr/bin/npm install` and see if that helps. What is the RAM that is available to each of these docker images running the builds?

Additionally, I think I will bump the logging on npm install to silly to see if there is anything useful before the process exits using `--loglevel=silly`

**Comment by trriplejay** [comment]
running out of memory is a possibility.  The build minions have about 3.7GB available. It could explain why it's inconsistent.  Did the log level provide any extra info?

**Comment by npahucki** [comment]
So, putting the log level to silly, I can see that the npm process exited just fine, but still there is a failure: 

```
...
npm sill runTopLevelLifecycles Finishing
npm sill install printInstalled
npm WARN @execthread/api-server@1.25.1 No repository field.
npm WARN @execthread/api-server@1.25.1 No license field.
npm verb exit [ 0, true ]
npm info ok 

cp dev.example.env .env

echo LINKEDIN_SECRET_KEY=$LINKEDIN_SECRET_KEY>>.env

ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/10ecc064-a363-4f65-99f7-80d75de4da61.sh'
Exception Invalid or no script tags received
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/10ecc064-a363-4f65-99f7-80d75de4da61.sh'
Exception Invalid or no script tags received
```

In this case at least, NPM exited with 0 (a good thing), but I see the same failure message : `ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/10ecc064-a363-4f65-99f7-80d75de4da61.sh'` What does this error mean? This seems to be a script that Shippable is running. I pasted this in the original message when I opened the ticket, and I'm curious why this message does not seem interesting to you - according the the message that is the command that failed, it has something to do with adding a key for aah-agent, and nothing to do with `npm install`.

**Comment by npahucki** [comment]
I have sent you via email the full output of the build when using 'silly' log level. The thing of note, is that with the log level set thus, it fails 100% of the time now.

**Comment by kanthchandra** [comment]
Hi @npahucki can we trigger a couple of builds on your behalf and see whats going on? or you can trigger the build as well and I'll take a look right now.

**Comment by npahucki** [comment]
Please be my guest and trigger some builds on our behalf. However, note that I have took out the verbose logging because it blocks our team from developing. Is there some way we can have you troubleshoot this without blocking our dev team? If I had a branch that had the logging turned on (and thus fails consistently) could that work?

**Comment by kanthchandra** [comment]
Yeah sure, a branch specific to debug this issue would help us. If we are
able to repro that bug consistently on that branch that would be great.
Please let us know the branch name. I'll take a look at this tomorrow. (I'm
in the IST timezone).

**Comment by npahucki** [comment]
You can use this branch for testing: https://app.shippable.com/runs/588f6f2f69174c0f000be2b3/1/console

**Comment by npahucki** [comment]
Any news on this, it seems to be failing more more - to the point we are considering dumping shippable as at this point it's completely useless and you guys have not been very responsive nor proactive. Please respond ASAP.

**Comment by manishas** [comment]
@npahucki I apologize for the delay here. I'm going to ask someone to look into this asap.

**Comment by trriplejay** [comment]
investigating this now via test branch. thanks for your patience.

**Comment by trriplejay** [comment]
@npahucki Based on further examination of some of your build failures, we may have found the root cause. Something (possibly during npm install, or shortly afterwards) is printing a non-UTF8 character, and that is making our log parser throw an exception that is being poorly handled.  We're working toward a fix now. 

In the meantime, you mentioned loglevel silly makes it fail every time. does loglevel silent reduce the failure rate?

**Comment by npahucki** [comment]
I'll try log level silent on the test branch to see what happens.

**Comment by npahucki** [comment]
I have set the log level to silent on the test branch mentioned above, please trigger it a few times to see if it fails. The first run worked ok.

**Comment by trriplejay** [comment]
alright, we're still working on this.

**Comment by trriplejay** [comment]
one more thing to try as a workaround.

can you change your npm install line to something like this:
`shippable_retry npm install --loglevel error 1> /dev/null`

This way if npm fails you'll still be able to see the errors, but it's really that huge dependency tree being suddenly printed at the end that we think might be causing some kind of buffer flood.  npm doesn't offer a way to silence that part, so redirecting to /dev/null seems to be the best solution.  We'll work on figuring out the root cause in the meantime, but this will hopefully provide some relief from the intermittent failures.

Let me know if that helps.

**Comment by npahucki** [comment]
You know what seems to help: not using 'shippable retry', I think all builds have passed since I took this out.

**Comment by npahucki** [comment]
You should seriously consider that`shippable retry` is faulty, since taking this out I have not had any failures at all related to the npm install process. I would like to use `shippable retry` because of course `npm install` could fail because of transient network issues.

**Comment by trriplejay** [comment]
thanks for bringing that to our attention. we'll take a closer look at that.

**Comment by avinci** [comment]
@npahucki we looked at `shippable_retry` very thoroughly and could not find any issues. You probably were seeing these issues as a by-product of what was happening on the api. there was a memory leak which was causing certain api instances to die and start timing out and this was causing all sorts of side effects. We have resolved the problem and in the last couple of weeks we have not seen this happen. Please let us know if you see this repeat.
