### ISSUE TITLE
Multiple containers under a ECS Task Definition

### ISSUE THREAD

**Issue by sample-sample** [Shippable/support#3285]
I have two repos A and B and I need both to the run as containers under a single Task Definition in ECS. I am trying to link between containers and it looks like the link flag in dockerOptions works only when the containers exists in the same task definition. To try it, I need to move the containers to the same task definition. How do I do this?

**Comment by trriplejay** [comment]
in your manifest job, simply list both image resources as IN statements. this will put them in the same "manifest", which will then become a single task definition when deployed.  the same dockerOptions can be applied to both, or each one can have its own by using the `applyTo` keyword, specifying the image resource name.  You can see some examples here: http://docs.shippable.com/pipelines/jobs/deploy/  and here: http://docs.shippable.com/pipelines/jobs/manifest/

**Comment by sample-sample** [comment]
Thanks for the reply. I got the reference from this link [](http://stackoverflow.com/questions/34517265/linking-containers-between-task-definitions-in-aws-ecs).. just to confirm is it required that both containers be defined under the same task definition? Also, how do I get the name of the container to assign to the --link in dockerOptions?

**Comment by trriplejay** [comment]
yes, to use link on ECS, both containers must be in the same task definition.  Your container's name should be the same as the image resource name.

**Comment by manishas** [comment]
Closing this issue since the qs is answered.

**Comment by sample-sample** [comment]
Thanks for the support. I was able to get this working.
