### ISSUE TITLE
Missing history and no access to account

### ISSUE THREAD

**Issue by elmpp** [Shippable/support#3286]
I've come to use my shippable account but am seeing a constant message of "Project sync currently in progress" and in the organisation view the last build time is reading as 5 months ago (it is in daily use until today). 

The project id is "579f1f0d104d810c00d91999". Here are screenshots of the offending pages
![screen shot 2017-01-16 at 08 53 08](https://cloud.githubusercontent.com/assets/864612/21976345/46c879a8-dbc9-11e6-87e5-5973d4c4da14.png)
![screen shot 2017-01-16 at 08 53 17](https://cloud.githubusercontent.com/assets/864612/21976346/46d4142a-dbc9-11e6-8720-9aa644fd204f.png)

**Comment by elmpp** [comment]
The offending pipeline is "alanpartridge/api". It should be reading as last build from "dev" branch and very recent.

Is this related to the Bitbucket maintenance window perhaps?

**Comment by kanthchandra** [comment]
@elmpp I'm looking into it and will get back to you with my findings.

**Comment by elmpp** [comment]
that's brilliant thanks

**Comment by kanthchandra** [comment]
@elmpp can you check if it works now? It's a bug at our end which will be fixed in the next release. For now I have fixed it for you manually.

**Comment by elmpp** [comment]
yes! looks much better in the pipeline page which is good enough for me!

Btw, the org view still shows out of date "last run"

![screen shot 2017-01-16 at 09 30 33](https://cloud.githubusercontent.com/assets/864612/21977569/9403d80c-dbce-11e6-8edd-e7800a2848fb.png)
![screen shot 2017-01-16 at 09 30 42](https://cloud.githubusercontent.com/assets/864612/21977570/94057d42-dbce-11e6-8758-3a39c0b95ca0.png)

**Comment by elmpp** [comment]
Having looked a bit deeper it seems i've lost a build that would have been around 23:30 yesterday (UTC). Probably all part of same bug

**Comment by kanthchandra** [comment]
Is it a webhook build?? Can you check if the webhook was delivered on bitbucket and I dont think this bug has anything to do with triggering of builds.

**Comment by elmpp** [comment]
not really sure how to check webhook history but i see the bitbucket commit 10 hours ago and another commit just now has resulted in a build with no bitbucket config changes.

Can dig a bit deeper if you need but am happy with things. Thanks for speedy response this morning

**Comment by kanthchandra** [comment]
> Btw, the org view still shows out of date "last run" 

In the organizations page we show the latest completed build for all the enabled projects based on the dashboard settings that you have configured in the project settings page. For `api` project you have configured master branch and the last completed build for master branch in api was 70 so it's shown in the dashboard page. More documentation on this can be found at http://docs.shippable.com/navigatingUI/subscriptions/ci/

> Can dig a bit deeper if you need but am happy with things
Glad that you are happy with our product. Please feel free to open an issue if you need help and we will be happy to help :)

**Comment by elmpp** [comment]
Oh i see. I've altered that now. Thanks
