### ISSUE TITLE
Build fails with virtual memory exhausted: Cannot allocate memory

### ISSUE THREAD

**Issue by didiersmith** [Shippable/support#3287]
I am trying to build a C++ project that I have building using gulp. This works fine locally and on travis, but on shippable, it seems like the build exhausts the available memory. Is there any way we can increase the amount of memory on the build VM?

https://app.shippable.com/runs/587d31fae69a190f002287de/1/console

**Comment by a-murphy** [comment]
All builds on Shippable nodes run on machines the same size.  For more memory, you can attach your own, larger, build node to your subscription.  Documentation of the requirements for those nodes and how to add them is available [here](http://docs.shippable.com/ci/advancedOptions/byon/).

**Comment by abhijitkini** [comment]
closing as question is resolved
