### ISSUE TITLE
.travis.yml scripts commands are not run as described in the travis documentation

### ISSUE THREAD

**Issue by prokopst** [Shippable/support#3288]
The travis documentation for `scripts` says:

> When one of the build commands returns a non-zero exit code, the Travis CI build runs the subsequent commands as well, and accumulates the build result.

[source](https://docs.travis-ci.com/user/customizing-the-build#Customizing-the-Build-Step)

So I did have in my .travis.yml multiple commands:
```yaml
scripts:
    - nosetests tests --with-xunit --xunit-file=shippable/testresults/nosetests.xml --cover-xml --cover-xml-file shippable/codecoverage/coverage.xml
    - coverage run --branch tests
    - coverage xml -o shippable/codecoverage/coverage.xml tests
```

Unfortunately the nosetests command returned 1 and looks like the coverage related commands were not executed at all:
https://app.shippable.com/runs/587e71bc79509c10004b5ea8/1/console

Note I'm no longer using these three commands.

**Comment by avinci** [comment]
@prokopst we only support basic travis command. I would recommend that you use shippable.yml syntax as it has a bunch of features that travis does not support and vice versa.
