### ISSUE TITLE
python unknown version defaults to python 2.7

### ISSUE THREAD

**Issue by prokopst** [Shippable/support#3289]
The [docs](http://docs.shippable.com/ci/languages/python/) don't state that you support python 3.6 (though it was released a month ago), but when I tried to use it, the version was happily accepted. Unfortunately this turned out to be a false positive - although the version was accepted the default one was used because `/usr/bin/python3.6` wasn't found.

Build:
https://app.shippable.com/runs/587e8276ed52f70f00e41dbe/2/console
```
virtualenv -p /usr/bin/python3.6 /root/venv/3.6 5s  
    The executable /usr/bin/python3.6 (from --python=/usr/bin/python3.6) does not exist
```

Could you please add verification for valid/supported versions and fail on such error?

**Comment by stephanielingwood** [comment]
Hi @prokopst,

This was recently released, and your build will now fail when the version specified for python is not available. Closing this issue now - thanks for the input!

**Comment by txomon** [comment]
Hello, I am getting this same error still. is it really fixed?
![image](https://cloud.githubusercontent.com/assets/228250/24200885/c5ae3bcc-0f0e-11e7-9803-00ea6c19f3b2.png)

**Comment by stephanielingwood** [comment]
Hi @txomon,

To be clear: if you received that error in the logs, your build should fail. That error means that the version of python you specified in the yml (3.6) is not available in the build image.  If you received that error message and the build succeeded, then please include a link to that build so we can take a look.

As for python 3.6: python 3.6 was made available in our recently released images. If you want to use python 3.6, you can either:
- Use our newest machine image. To do this, go to your subscription settings tab and find the panel called "machine images". In the dropdown, select `v5.2.3` for your machine image. When we run your build, your build will run on our default Ubuntu 16 image, with Python 3.6 installed.
- [Specify the docker image](http://docs.shippable.com/ci/shippableyml/#pre_ci_boot) you wish to use in the `pre_ci_boot` section of your yml. In this case, you'll want the `v5.3.2` tag of our [Ubuntu 14 python image](https://hub.docker.com/r/drydock/u14pytall/) or our [Ubuntu 16 python image](https://hub.docker.com/r/drydock/u16pytall/). The `pre_ci_boot` section will look something like this:

```yml
build:
  pre_ci_boot:
    image_name: drydock/u14pytall
    image_tag: v5.3.2
```
