### ISSUE TITLE
multiple language support

### ISSUE THREAD

**Issue by zacr** [Shippable/support#329]
I have a project with a node gruntFile that invokes compass, so I need ruby on the box as well. Can I specify multiple languages or do I need to install ruby on the fly?

**Comment by abrararies** [comment]
Hey,
I'm trying to do the same thing (run gem install) but it fails.
I tried your solution but now it gives, 
"/home/shippable/build/build.sh: line 84: /root/.rvm/scripts/rvm: No such file or directory".

My shippable.yml file is:

build_image: shipimg/ubuntu1204_nodejs
language: node_js
node_js:
  - '0.10'
  - '0.11'

before_script:
  - npm install -g bower grunt-cli
  - source ~/.rvm/scripts/rvm && rvm use 1.9.3   #this will activate ruby 1.9.3
  - ruby --version #ruby 1.9.3 is now ready to use
  - gem install sass

**Comment by Azuka** [comment]
I'm having the same issue on the shippableimages/ubuntu1404_php box. IS there a PHP box with rvm and node available?

**Comment by abrararies** [comment]
@Azuka I dont know about Php but I did get it to run with Node and Rvm.
Here is my shippable file:

before_install:

  # Install mpapis public key (might need `gpg2` and or `sudo`)
  - curl -sSL https://rvm.io/mpapis.asc | gpg --import -

  # Download the installer
  - \curl -O https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer
  - \curl -O https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc

  # Verify the installer signature (might need `gpg2`), and if it validates Run the installer
  - gpg --verify rvm-installer.asc && bash rvm-installer stable
  - source /etc/profile.d/rvm.sh


install:
  - source /usr/local/rvm/scripts/rvm && rvm install ruby  #usr path is specific to this docker image
  - rvm use ruby --default
  - gem install sass # If you want to use sass
