### ISSUE TITLE
All repos, subscriptions disappeared

### ISSUE THREAD

**Issue by pkaminski** [Shippable/support#3293]
When I try to load the dashboard for one of my projects that was working fine earlier today, I get a slew of errors on the page:

```
(Id: 4004) No projects found for projectId(s):
verbose: /projects|GET|callerId:540e995cf2f13e740b428eab|validateProjects|_computeShim
(Id: 4004) No projects found for projectId(s):
verbose: /projects|GET|callerId:540e995cf2f13e740b428eab|validateProjects|_computeShim
(Id: 4004) No projects found for projectId(s):
verbose: /projects|GET|callerId:540e995cf2f13e740b428eab|validateProjects|_computeShim
(Id: 4004) No projects found for projectId(s):
verbose: /projects|GET|callerId:540e995cf2f13e740b428eab|validateProjects|_computeShim
(Id: 4004) No subscriptions found for subscriptionId(s): 540e995d3479c5ea8f9f26e3
verbose: /subscriptions/:subscriptionId/runStatus|GET|callerId:540e995cf2f13e740b428eab|validateSubscriptions|_computeShim
(Id: 4004) No projects found for projectId(s):
verbose: /runs|GET|callerId:540e995cf2f13e740b428eab|validateProjects|_computeShim
```

Looks like something is very broken with Shippable?

**Comment by rageshkrishna** [comment]
@pkaminski We have been seeing quite a few errors from the GitHub API in the past couple of errors. This may have caused your permissions to have been synchronized incorrectly. Can you please try syncing your account from the account settings page now? It should restore everything for you.

**Comment by pkaminski** [comment]
Thanks, that did the trick.  Might be nice if Shippable did this automatically when every call is failing, or at least provides a tip that this may fix things...
