### ISSUE TITLE
Email reports generated by code coverage

### ISSUE THREAD

**Issue by vivekna1** [Shippable/support#3294]
There are certain reports that are generated in our shippable/codecoverage folder. 

This is generated by our Ruby - rpsec command. the output being copied to shippable/codecoverage.

Now this is not in a format shippable can read and print in the coverage tab( it is in html format) ... can this be attached in the same email that is being sent to people / team configured in the notifications tab.

Our shippable.yml (for reference)
before_install:
  - apt-get update
  - apt-get install libmagickwand-dev
  - apt-get install imagemagick
  - apt-get install libmysqlclient-dev
  - gem install bundler
  - rvm install 2.3.3

script:
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - rspec spec --format RspecJunitFormatter  --out shippable/testresults/rspec.xml || true
    - cp -r /xx/yy/coverage/* shippable/codecoverage/
notifications:
  email:
    recipients:
      - yz@abc.com

**Comment by avinci** [comment]
We cannot attach html reports into email. We have added a functionality where all the reports are uploaded natively to a file store than can be downloaded. Will that work for your scenario?

**Comment by avinci** [comment]
closing this for lack of response
