### ISSUE TITLE
API returns "No projects found" for all post requests

### ISSUE THREAD

**Issue by tjomk** [Shippable/support#3295]
When running `curl -H 'Content-Type: application/json' -H 'Authorization: apiToken XXXX' https://api.shippable.com/projects/57f39f016d80900e003aae80` I get back project information.

However when running `curl -H 'Content-Type: application/json' -H 'Authorization: apiToken XXXX' https://api.shippable.com/projects/57f39f016d80900e003aae80/newBuild` I'm getting `{"logType":"verbose","methodName":"/projects/:projectId/newBuild|POST|callerId:5581b1acedd7f2c052202125|validateProjects|_computeShim","id":4004,"message":"No projects found for projectId(s): 57f39f016d80900e003aae80"}`.

What's wrong here?

**Comment by a-murphy** [comment]
It looks like the apiToken you're using doesn't have write access to the project.  Could you check that the token belongs to an account that would be able to push to the repository and try synchronizing that account?  To synchronize an account, click on the gear icon in the top right corner while logged in as that account and then click the green "sync" button.

**Comment by tjomk** [comment]
Yes, I did that under my account (I am repository admin). Although shippable thinks that I am not the owner.
In the end we removed the whole thing from Shippable completely and re-added. Then it started working.
