### ISSUE TITLE
rSync is unremovable

### ISSUE THREAD

**Issue by ykrevnyi** [Shippable/support#3296]
Hey, guys

There is one problem with jobs. One of them cannot be deleted.

What I did:
- added sync repository (with probably broken .yml syntax)
- got job `retryer.js_ci_rSync`
- then I removed all sync repositories
- one job got stuck (job name `retryer.js_ci_rSync`)
- aaand I can't remove it

The job looks like:
```javascript
"propertyBag": {
  "yml": {
    "name": "retryer.js_ci_rSync",
    "type": "rSync",
    "steps": [
      {
        "IN": "retryer.js_ci"
      },
      {
        "TASK": "managed"
      }
    ]
  },
  "isPaused": false
}
```

How is it possible to remove it?

Thanks

**Comment by a-murphy** [comment]
Would you mind including a link to the subscription?  Removing the syncRepo usually removes the rSync job, so we'd like to be able to see what exactly is stuck.

**Comment by ykrevnyi** [comment]
Thanks for reply @a-murphy !

Did you mean this link?
https://app.shippable.com/subscriptions/587cc538e69a190f00223c4a/pipelines/jobs

**Comment by a-murphy** [comment]
Thank you for the link.  We've looked into it and the rSync job isn't attached to any other resources that would prevent deletion.  We're looking into how this got into such an unusual state. The only option to remove it right now is if we remove it for you.  Would you mind if we remove it?

**Comment by ykrevnyi** [comment]
Yes, please!
It would be great

**Comment by a-murphy** [comment]
I've removed it.  Let us know if you need anything else.

**Comment by manishas** [comment]
Closing this.
