### ISSUE TITLE
Bower components not installing

### ISSUE THREAD

**Issue by lukehutton** [Shippable/support#3297]
Have there been any reports from users on bower install not properly installing packages? I have noticed in past day, not all packages have been downloaded and extracted, even though bower logs in shippable console say they have installed 

Build: https://app.shippable.com/runs/587fd58a2f36a111000ea4e1/1/console

In shippable.yml:
`shippable_retry bower --allow-root install`

Console output says installed correctly:
`uikit#2.27.2 bower_components/uikit`

However, when print the bower_components directory, I don't see the UIKit component there? 

Apologize if this has been caused by some update to some other package. I've tried old builds that worked before and they break as well, must be an update to something.

**Comment by a-murphy** [comment]
Sorry, we haven't gotten any other reports about errors with Bower and haven't changed anything recently that could be related to your error.  It does sound like a package that you use was likely updated.  Bower itself does not appear to have been, but it may be worth checking the other packages you're using to see if an update may have resulted in a conflict.

**Comment by lukehutton** [comment]
Thanks for looking into, and I apologize. It turns out that it was indeed package issue. Downgraded and it worked so will dig into the component. Cheers. Closing.
