### ISSUE TITLE
Incorrect nodejs version

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#3299]
My base image is `drydock/u14nod:prod` and my `shippable.yml` looks like:
```
language: node_js
node_js:
  - 7.4.0
```
When starting the build is trying to download node v7.4.0
```
 nvm install "7.4.0" 9s  
Downloading https://nodejs.org/dist/v7.4.0/node-v7.4.0-linux-x64.tar.xz...

############################                                              39.9%
######################################################################## 100.0%
WARNING: checksums are currently disabled for node.js v4.0 and later
Now using node v7.4.0 (npm v4.0.5)
```
But when I check the npm and node version within my shell script it says node v0.10.11
```
/usr/local/bin/node -> v0.10.37
/usr/local/bin/npm -> 1.4.28
```
NOTE : In before_build.sh I'm referencing node and npm as
```
ln -s /usr/bin/npm /usr/local/bin/npm
ln -s /usr/bin/node /usr/local/bin/node
```

Build run for reference: 58807a29eda6bc0f0082c44c

**Comment by phagunbaya** [comment]
I think I found the solution. It should be 
```
ln -s /root/.nvm/versions/node/v7.4.0/bin/npm /usr/local/bin/npm
ln -s /root/.nvm/versions/node/v7.4.0/bin/node /usr/local/bin/node
```

**Comment by rageshkrishna** [comment]
@phagunbaya You're right.

We use `nvm` to switch node versions. This does _not_ update the binaries in /usr/bin, but instead updates your path to use the binaries it downloads when you ask for a specific version.

Any reason you need to create links in your build scripts? Just running `node --version` will do the right thing.

**Comment by phagunbaya** [comment]
@rageshkrishna : The only reason to keep them as absolute path is to avoid any discrepancies that might occur due to two binaries having same name appear on the environment PATH.
