### ISSUE TITLE
Trigger Notifications adding issues

### ISSUE THREAD

**Issue by navymaker** [Shippable/support#3302]
Hi,
I have issues with adding trigger notifications to trigger pipelines from CI builds.
When I'm trying to add integration in subscription settings, I getting following error:
(Id: 4011) subscriptionIntegrations.create failed with error: Validation error
verbose: subscriptionIntegrations|post|callerId:57bec88cdf04f70e0042be97|_post
Its actually added after that, though, and works in most cases. I will describe other cases in separate issue.

**Comment by stephanielingwood** [comment]
Hi @navymaker,

Would you mind double-checking that you don't already have a subscriptionIntegration in that subscription with the same name? That's the main culprit for getting a validation error in this scenario, as we require that subscriptionIntegration names be unique within the subscription. That might also explain why it seems like it's added, because it's already there.

**Comment by navymaker** [comment]
No, this is always a new integration for new project. But I'm adding account integration and subscription integration with the same names, maybe that names are interfering to each other.

**Comment by stephanielingwood** [comment]
It's okay to have your account integration and your subscription integration with the same name; personally, I do that all the time to keep myself organized.

Would you mind walking me through how you're creating the new account and subscription integrations? If you're creating them from the account integration page, and selecting the subscription from the dropdown, then the subscription integration is automatically created for you. Trying to add the subscription integration (for that account integration) again from the subscription integration tab would give the error you're seeing above, as it would already exist.

**Comment by navymaker** [comment]
Yes, I'm choosing subscription in account integration and then trying to add subscription integration. I think following tutorial is outdated:
http://docs.shippable.com/tutorials/pipelines/connectingCiPipelines/
Can you please update it?
Thanks, closing this issue.

**Comment by stephanielingwood** [comment]
Hi @navymaker,

The tutorial is now updated. Thanks for letting us know about the needed update.

**Comment by navymaker** [comment]
That's nice, thanks!
