### ISSUE TITLE
Boto not installing (?)

### ISSUE THREAD

**Issue by sumothecat** [Shippable/support#3304]
### AWS EB deployment not working due to boto not installing (?)

Attempting to set up AWS EB deployment (without Docker - we were previously using Docker). It appears to be failing on installing the AWS boto library.

- Link to the build failure https://app.shippable.com/runs/5880d809eda6bc0f0082f8ed/1/console
- Scripts called from the yml (optional) https://github.com/jncc/deli/blob/master/shippable.yml

**Comment by a-murphy** [comment]
It looks like an outdated version of botocore.  Could you add the following to the end of the `ci` section in your `shippable.yml`?
```YML
- pip install --upgrade botocore 
```

It will update the version of botocore in the container and should fix the error.

**Comment by sumothecat** [comment]
Thank you, that fixed.
