### ISSUE TITLE
ntp clock sync on shippable job node 

### ISSUE THREAD

**Issue by ankur--bhatia** [Shippable/support#3307]
### Description of your issue:
Our deployments using elastic-beastalk started to fail recently. Digging into the logs, we saw that aws is rejecting our operation because the job-node time is over 5 min off. 

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
   https://app.shippable.com/runs/587e5feceda6bc0f0081df42/1/console
  * the step that fails is =>  build_on_success
  * Is there are way to sync the times. I feel there should be ntp deamon running and ensuring the clocks are synced.  
- Scripts called from the yml (optional)

**Comment by kanthchandra** [comment]
Hi @ankur--bhatia This was fixed last december. Can you please reset your node and your node should be in sync with clock servers.

**Comment by ankur--bhatia** [comment]
@kanthchandra how do I reset the the node.

**Comment by kanthchandra** [comment]
Go to subscriptions -> Settings -> nodes. You will see a list of nodes and beside each node you will see 3 options, Edit-Reset-Delete. You can reset the node by clicking on reset.

**Comment by ankur--bhatia** [comment]
👍  thank you for the quick response

**Comment by manishas** [comment]
closing
