### ISSUE TITLE
Triggered build on bitbucket branch never starts if it contains a slash

### ISSUE THREAD

**Issue by belak** [Shippable/support#3308]
This is a duplicate of #1205 because I wasn't able to get a response there or by directly emailing who closed the ticket.

It was closed because it was stated that there was no way for Shippable to fix this, however there is an additional endpoint which should be used to get the commit hash for a branch. I've copied my response from #1205 as it should provide the information needed to fix this.

> This is actually possible to fix, but it involves an additional API request.
>
> https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/refs/branches/%7Bname%7D
>
> This endpoint will allow you to get the hash for any branch, even if it contains a slash. That hash can then be plugged into the commit revision API.

**Comment by rageshkrishna** [comment]
Thanks @belak for the workaround. Our BitBucket customers have been waiting for a long time for this. I'm going to tag this as a feature request, but we definitely want to get this done very soon.

**Comment by shrivara** [comment]
@belak This is now available.
