### ISSUE TITLE
Webhook integration ignoring branches property

### ISSUE THREAD

**Issue by ykrevnyi** [Shippable/support#3310]
Hey guys,

Seems like `branches` property (webhook integration) does't work correctly.

I have two types of branches:
- `master`
- `release` (`release/v0.1.0`, `release/v0.1.1` ..)

At `CI`s level there is (works):
```
branches:
  only:
    - master
    - v*
```

If I put integration without `branches` property - everything works just fine:
```javascript
integrations:
  notifications:
    - integrationName: trigger.retryerjs.pipelines
      type: webhook
      payload:
        - versionName=${GIT_TAG_NAME#v}
        - isRelease=$IS_RELEASE
      on_success: always
      on_failure: never
```

But if we add `branches` section:
```javascript
notifications:
    - integrationName: trigger.retryerjs.pipelines
      type: webhook
      payload:
        - versionName=${GIT_TAG_NAME#v}
        - isRelease=$IS_RELEASE
      branches:
        only:
          - master
          - v*
      on_success: always
      on_failure: never
```

it doesn't work at all.

I also tried different combinations of `branches` and it didn't work out too.

*Link to the build failure*
works:
https://app.shippable.com/runs/5884c169cbf449120090dd27/1/console
https://app.shippable.com/runs/5884c1f9aebc4e0f00801304/1/console

doesn't work:
https://app.shippable.com/runs/5884be5414732910007d0593/1/console
https://app.shippable.com/runs/5884c056aebc4e0f008012dd/1/console
https://app.shippable.com/runs/5884c07f3b653a0f00fa46ac/1/console

Thanks

**Comment by rageshkrishna** [comment]
@ykrevnyi Thanks for reporting this. It looks like we have a bug with processing wildcards in the branches list for notifications. We'll look into this very soon.

**Comment by rageshkrishna** [comment]
@ykrevnyi This has been fixed. Wildcards should be working correctly now in the branches list for notifications. Please let me know if you still see issues with this.
