### ISSUE TITLE
Shippable website not working with IE 11 anymore

### ISSUE THREAD

**Issue by jmarver** [Shippable/support#3313]
### Description of your issue:
Starting late last week I'm unable to access https://app.shippable.com/ using IE 11. The life preserver ring image shows up and spins but that's is far as it goes. I'm able to work okay with Chrome. 

Is IE 11 no longer supported?

**Comment by rageshkrishna** [comment]
@jmarver Thanks for reporting this. It looks like a strict mode violation slipped through in one of the changes that we launched a few days ago. We'll have this fixed very soon. Sorry for the trouble.

**Comment by rageshkrishna** [comment]
This has been fixed. IE11 should be working correctly now.
