### ISSUE TITLE
Notification integrations are throwing error despite the integration being set up

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#3314]
I'm trying to get slack integration up and running, but whatever I try, I'm not getting an integration name match.  
I've tried slack-integration in both the integration settings and my yml and it says slack-integration isn't found, so I've tried changing it, and get:

    Errors  
        Integration name specified in yml does not match integrations present 
        in Subscription settings: slack

```integrations:
  notifications:
    - integrationName: slack
      type: slack
      recipients:
        - "#shippable-builds"
#      branches:
#        only:
#          - master
#          - dev
      on_success: always
      on_failure: always
```

https://app.shippable.com/runs/5886397111c45a1000af883d/1/console

**Comment by nealeu** [comment]
it would also help to show both ends of what you are reporting in that error, which would mean my error should be reading:

    Integration name 'slack' specified in yml does not match any of the following integrations present in Subscription settings: ['slack']

  Ah.. and in writing that up, I realise that there are two touch points.

Another thing you could do here is to put a link in to "Subscriptions" config in the error message.

**Comment by a-murphy** [comment]
It sounds like you may have already found it, but you have to add the account integration to the subscription to allow it to be used by builds in that subscription.  If you go to the subscription page (click the subscription name in the top corner from the build page or choose it in the top left dropdown), then click the settings tab, and integrations on the left, there is a list of integrations that this subscription is allowed to use.  An account integration can be added to the subscription by clicking the "add integration" button above this list.

**Comment by nealeu** [comment]
Thanks. Yes.  Hope you will consider the suggestions for saving people missing the subscriptions vs integrations confusion
