### ISSUE TITLE
Stuck in queue

### ISSUE THREAD

**Issue by xxkyzerxx** [Shippable/support#3317]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

https://app.shippable.com/projects/5886dbe13b653a0f00fb16e2

The job shows "Waiting in queue".
Shippable node (node-422a59bd ID: 5886eac63b653a0f00fb1a8b) status is "success" and "inactive" in current workload.

**Comment by kanthchandra** [comment]
Hi @xxkyzerxx Did you by any chance delete that project from github and recreated the same?

**Comment by xxkyzerxx** [comment]
yup. i deleted the project and recreated the same name.

I noticed itz fixed. Thanks
