### ISSUE TITLE
Integrating Shippable Build Messages in Github/Bitbucket

### ISSUE THREAD

**Issue by Reagan** [Shippable/support#3321]
Whenever a build failure occurs, a little red fail marker is displayed next to the relevant commit. However to view the actual build error message, one has to click on the marker, exit the source control platform and login to Shippable. Does Shippable allow for it's build failure messages to be displayed next to the failing commit as seen on GitHub or BB (in the same way the build marker is displayed)?

**Comment by stephanielingwood** [comment]
Hi @Reagan,

We've marked this as a feature request, though to be honest it's probably not something we'll implement. Both GitHub and Bitbucket don't allow that many characters to be displayed next to the commit. So, we might be able to gain a very heavily truncated failure message, but it would be at the expense of the message saying "FAILED", and would probably be too short to be useful.

I'm going to close this for now, and we can revisit this if GitHub/BB revise their character limits.
