### ISSUE TITLE
Job execution time is incorrect

### ISSUE THREAD

**Issue by ykrevnyi** [Shippable/support#3323]
Hi guys,

The **Duration: 4 minutes** is correct. But the stages calculation is not (especially **Provision job node**).

![image](https://cloud.githubusercontent.com/assets/4376146/22284451/12d11bb8-e2f0-11e6-95f2-85620958fcd3.png)

- Link to the build failure
   https://app.shippable.com/download/buildJobConsoles?buildJobId=58886b9db22f431000db1230

Thanks

**Comment by manishas** [comment]
We have improved the durations being shown since this issue was opened. Closing.
