### ISSUE TITLE
Issues with build deploying to aws through elastic beanstalk

### ISSUE THREAD

**Issue by darilldrems** [Shippable/support#3325]
Traceback (most recent call last):
  File "/usr/local/bin/eb", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named packaging.version

the build command
build:
  ci:
    - npm install
    - npm test
    - pip install --upgrade botocore

**Comment by manishas** [comment]
This is a dup of https://github.com/Shippable/support/issues/3316

From @a-murphy :
It looks like a new version of `setuptools` was released and the dependencies of that dependency (`packaging` and `appdirs`) are causing the problem.  Installing the latest version of `setuptools` or its dependencies before `awsebcli` appears to help.  So, adding either `pip install packaging=16.8 appdirs=1.4.0` or `pip install setuptools==34.0.1` to the end of your `ci` section should allow `awsebcli` to be installed.
