### ISSUE TITLE
Delete Account does not actually delete my account

### ISSUE THREAD

**Issue by caleblloyd** [Shippable/support#3326]
1. Sign into Shippable with GitHub and authorize
2. Enable access to private repos
3. Click Settings gear, then Delete Account.  I am signed out

Now, sign into Shippable with the same account as before.  I am brought right back into my account without going through GitHub Oauth2 authorization again, and all of my settings in Shippable are exactly the same as before I "Deleted" my account.

Obviously, this is not actually "Deleting" my account.

**Comment by avinci** [comment]
Thats a github cookie. You need to clear your github cookies in order to OAuth to fire. You might see the network traffic where we redirect to github and if github is not challenging you then its cos of githubs oAuth cookie. 

Delete your account and then try it with a private browser session and see if the same things persists.

**Comment by caleblloyd** [comment]
I think it is due to the fact that Shippable is still an Authorized Application in Github after I delete my shippable account:

![image](https://cloud.githubusercontent.com/assets/2414837/22305143/6ab99090-e308-11e6-817f-7d8f112789cf.png)

Shouldn't the "Delete Account" function in shippable automatically revoke access via a GitHub API Call?

The purpose of this is I'm trying to delete an account and re-sign up to get it to re-sync.

**Comment by avinci** [comment]
I am not sure we can delete that auth as an oAuth relying party. I will look into it more if github allows us to delete

**Comment by rageshkrishna** [comment]
We cannot do this because the GitHub API doesn't allow it. Quoting from https://developer.github.com/v3/oauth_authorizations:

> You can use this API to manage the access OAuth applications have to your account. You can only access this API via Basic Authentication using your username and password, not tokens.
