### ISSUE TITLE
Add branch level caching for CI

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#3327]
See #3300 for one consequence of this.

Another is that caches are per-project, not per-branch.

The classic use of caches is the npm_modules folder, caching of which speeds up builds 10 fold. However if we create a new branch in order to test out upgrading third party modules, it will use the cached version with the old versions. Worse, those new versions are now in the cache and the mainline code will use them!

**Comment by mbrodala** [comment]
For caching per branch I did open #2582 a while ago.

**Comment by avinci** [comment]
closing this and resolving this in #2582
