### ISSUE TITLE
git submodule failing

### ISSUE THREAD

**Issue by tomsterritt** [Shippable/support#3329]
Hi,

Our git submodule update has stopped working. Example build: 588a36c1adf5420f00f35a4b

The submodule is also a repo we have set up in shippable so I don't understand why it's stopped working. I've been through and reset both projects to ensure the deploy keys are set but it's still failing.

Thanks

**Comment by a-murphy** [comment]
If you're trying to use private git submodules, you'll have to add a SSH key to give the build using the submodule access to the submodule.  The Shippable deploy keys added when a project is enabled or reset only allow builds to pull that specific repository, not any other private repositories in the subscription.  But, the build also has a subscription SSH key that can be added to repositories to make them accessible to all builds in the subscription.  Documentation is available [here](http://docs.shippable.com/ci/advancedOptions/gitSubmodules/#using-git-submodules).

**Comment by manishas** [comment]
@tomsterritt let us know if the suggestion above worked.

**Comment by tomsterritt** [comment]
@manishas I followed those steps when I set it up and it's been working for quite some time - the last build was fine on 12th Jan. Has something changed since then? I hadn't changed any of the settings on the GitHub repos before it broke, but I've just been through and reset them all since.

One of the images on that docs page is broken by the way :)

**Comment by rageshkrishna** [comment]
@tomsterritt Apologies for the confusion around this. We have identified an issue with submodule sync. Please follow https://github.com/Shippable/support/issues/3332 for the latest.
