### ISSUE TITLE
Error on AWS deploy:   No module named packaging.version

### ISSUE THREAD

**Issue by paulcornwell** [Shippable/support#3330]
https://app.shippable.com/runs/588a30e700e1510f00bb13c8/1/console

Please advise.  Has not worked since Monday.

**Comment by a-murphy** [comment]
This is a duplicate of #3316.  It looks like there's something wrong with one of the awsebcli dependencies that pip is installing.

**Comment by manishas** [comment]
@paulcornwell let us know if the suggestion in #3316 doesn't work.

Closing this issue.
