### ISSUE TITLE
Git submodule update failure

### ISSUE THREAD

**Issue by mmenozzi** [Shippable/support#3332]
Dear Shippable Support,
suddenly all our builds with private git submodules fail at the git submodule update step.
We didn't make any changes to our ssh keys.

- Link to the build failure: https://app.shippable.com/runs/588b0e035e71000f00182923/1/console or https://app.shippable.com/runs/588b0a54f2ff731000b3fe42/1/console

**Comment by rageshkrishna** [comment]
@mmenozzi We're looking in to this. I'll update this issue when I have more information.

**Comment by rageshkrishna** [comment]
@mmenozzi We've identified an issue with syncing private submodules that affects a number of projects on Shippable. We are working on resolving the issue with these projects now. I'll post an update as soon as we have a fix in place.

**Comment by rageshkrishna** [comment]
@mmenozzi @tomsterritt Can you please try triggering a build now and let me know how it goes?

**Comment by tomsterritt** [comment]
@rageshkrishna working again here, thanks 👍

**Comment by pureclouds** [comment]
The same problem with submodules placed in private Bitbucket repositories. Still not working.

**Comment by kanthchandra** [comment]
@pureclouds can you please point me to the build please?

**Comment by pureclouds** [comment]
@kanthchandra https://app.shippable.com/runs/588b37d8d7cf0a0f00535c53/1/console

**Comment by kanthchandra** [comment]
@pureclouds can you please try triggering a build now see how it goes?

**Comment by pureclouds** [comment]
@kanthchandra submodules cloned ! thanks!

**Comment by mmenozzi** [comment]
@rageshkrishna thank you, now it works!
