### ISSUE TITLE
Build receiving connection timeout from GitHub

### ISSUE THREAD

**Issue by taylortdixon** [Shippable/support#3333]
My bower install is failing because of: 

fatal: unable to access 'https://github.com/angular/bower-angular-mocks.git/': Failed to connect to github.com port 443: Connection timed out

Link to Build:  https://app.shippable.com/runs/588b837f00e1510f00bbbf4f/1/console

Path to it: 
build_ci --> bower --allow-root install

**Comment by stephanielingwood** [comment]
Hi @taylortdixon,

We took a look at this and suspect that GitHub may have had some slow response times this morning. While they didn't post a status update per se, a look at their [graphs](https://status.github.com/) shows that there was some sluggishness. (Take a look at mean API response time, mean hook delivery time, and browser time to first byte.) 

It looks like things are resolving themselves on GitHub's end, so your builds should be succeeding now. If this happens again when GitHub's graphs don't show some slowdown, do let us know. 

Thanks.

**Comment by abhijitkini** [comment]
closing as resolved
