### ISSUE TITLE
Setting timeouts on eb deploy command

### ISSUE THREAD

**Issue by KnowRe** [Shippable/support#3336]
Hello,

https://app.shippable.com/runs/589027542e6ab20f00bd6a0f/1/console

We're using Elastic Beanstalk and have multiple servers behind a load balancer, so the application deployment to the server instances is performed one instance by one. However, it takes several minutes to deploy each server so it sometimes treats as timeout even when the servers are successfully deployed.

So, is there any way to provide `--timeout` option to `shippable.yml` on `eb deploy` command? That might prevent the false negative alert of shippable build.

**Comment by avinci** [comment]
@KnowRe apologize for the delayed response. We just added a runCLI based job to alleviate the issues people were having with EB. The main issue is with CI, the deploy stage has very little control. We have created the ability to chain CI jobs into a pipeline and give you a much richer control. 

If you are interested, happy to jump on a call and demonstrate how to do this.

**Comment by manishas** [comment]
Closing since this is an old issue and there was no followup.
