### ISSUE TITLE
Installed dependency in shippable.yml still leads to import failure

### ISSUE THREAD

**Issue by Reagan** [Shippable/support#3337]
When setting up my `shippable.yml` file, I include the script `pip install celery` and later on run py.test on python code that requires this `celery` dependency. However, i still get an `ImportError: No module named celery` error. 

Here's my `shippable.yml` file: 

    language: python

    python:
    - 2.7

    install:
      - pip install celery
    
    before_script: 
      - mkdir -p shippable/testresults
      - mkdir -p shippable/codecoverage

    script:
      - cd source_apps/
      - py.test
      - cd ..

    cache: true

and here's the build error message:

    py.test 2s  
    ============================= test session starts ==============================
    platform linux2 -- Python 2.7.6, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
    rootdir: /source_apps, inifile: 
    collected 0 items / 2 errors

    ==================================== ERRORS     ====================================
    _________________________ ERROR collecting test_pytest.py _________________________
    test_pytest.py:1: in <module>
        ...
        import celery
    E   ImportError: No module named celery
    =========================== 2 error in 0.44 seconds ============================

i've also tried `sudo aptitude install python-celery` and well setting a specific version of celery for installation i.e. `sudo pip install celery==3.1.23` however this build error persists. Any ideas? 

* sorry if this is cross-posted

**Comment by stephanielingwood** [comment]
Hi @Reagan,

Would you mind sharing a link to your failed build? I just tried to reproduce this and was unable to. 

Also, I noticed that you're using our old yml format. While that is still supported, we highly recommend using our current format. The yml you have above would look like this in the new format: 
```
language: python

python:
  - 2.7

build:
  cache: true
  ci:
    - pip install celery
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - cd source_apps/
    - py.test
    - cd ..
```

More documentation on our current format is available in our [docs](http://docs.shippable.com/ci/shippableyml/).

**Comment by avinci** [comment]
@Reagan are you still having this issue?
