### ISSUE TITLE
Getting error: There is an issue loading the app, please contact support

### ISSUE THREAD

**Issue by deepak-khopade-isdr** [Shippable/support#3338]
### Description of your issue:
I triggered the PR from our repo and then was expecting Shippable to start the process, which it didn't. So when tried to check online @ app.shippable.com, just getting the spinning wheel with an error message below: **There is an issue loading the app, please contact support.**
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by kanthchandra** [comment]
hi @deepak-khopade-isdr We have an issue with one of our services and we are looking into it. We will get back to you as soon as we have more details on this.

**Comment by czardoz** [comment]
@kanthchandra Do you have a public status page?

**Comment by kanthchandra** [comment]
http://status.shippable.com/ @czardoz

**Comment by deepak-khopade-isdr** [comment]
Do you guys have any ETA?

**Comment by kanthchandra** [comment]
The service should be back up.

**Comment by ryan-kimber** [comment]
I'm still unable to access the application via http://shippable.com or https://app.shippable.com. Server response is empty.

**Comment by a-murphy** [comment]
The issue from earlier this morning reappeared, but Shippable is once again running and we are monitoring it closely while we permanently resolve the issue.
