### ISSUE TITLE
Wrong Selenium version in u14javall - expects 2.52, present 2.45

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#3342]
Possibly related to https://github.com/Shippable/support/issues/3054, except it is Shippable that is selecting which image to use. 

In build https://app.shippable.com/runs/58920641ace68f1000da2fb9/1/console, we get

- selenium_start 
  - echo "selenium will not be started because the binary was not found at /usr/local/selenium/selenium-server-standalone-2.52.0.jar."

## shippable.yml contains:
```
language: java

services:
  - selenium

addons:
    firefox: "49.0"
```
Looking at the build for u14javall, it appears that the selenium version should be 2.53.1.

**Comment by nealeu** [comment]
Okay, I've specified `build_image: drydock/u14javall:2016.02`, and even that doesn't have the expected version of Selenium.

Can you clarify what is supposed to happen here please?

**Comment by nealeu** [comment]
Come on folks.  It's been two days and this is actually a really simple (one line probably) fix your end.

**Comment by rageshkrishna** [comment]
@nealeu Sorry about not getting back to you sooner on this. I've taken a look and it looks like we have indeed messed up the Selenium version in the Java images. If Selenium 2.45.0 will work for you, I do have a quick workaround that can unblock you. Just add this to your YML file to override the default Selenium path:

````
env:
  global:
    - SHIPPABLE_SELENIUM_BINARY=/usr/local/selenium/selenium-server-standalone-2.45.0.jar
````

We're definitely going to update the images to fix this. I hope this works for you in the meantime. Let me know if you have any more questions.

**Comment by nealeu** [comment]
Thanks.  I'll try that as a workaround.
