### ISSUE TITLE
no build triggered for github pull request

### ISSUE THREAD

**Issue by magwas** [Shippable/support#3343]
This is an example:
https://github.com/edemo/PDOauth/pull/959
At least  3 of the last 5 commits should have triggered a build. None did.
What we have tried:
- Checked the config multiple times, reenabled pull requests and commits under Configure Webhook Events for Triggering Builds (I guess there was some new defaults, because those event did trigger a build before)
- added commits to the pull request to trigger a build
- tried to redeliver the webhook payload from github,
but nothing happens.

If this was a conscious change in shippable to close the security issue related to builds triggered by pulls running with the ssh key of the destination entity, then
a) a notice about it would have helped. I did check the top of the twitter feed for anything related
b) the solution would have been just to provide the key of the source entity.

**Comment by magwas** [comment]
Another pull request not triggering build: https://github.com/edemo/PDOauth/pull/960

**Comment by a-murphy** [comment]
It looks like you accidentally disabled webhooks when you went to enable them.  We haven't changed the defaults; it's still commits and pull requests, but not tags and releases, by default.  Could you re-enable webhooks by clicking the "enable" buttons for the appropriate webhook types on the project settings page and let us know if you are still able to reproduce this?

**Comment by magwas** [comment]
Build for commits and pull requests were already enabled in the target project.
I have deleted the webhook on the github side, reset the shippable project, and checked that the webhook appeared on the github side. Closed the old pull request, and opened a new one:
https://github.com/edemo/PDOauth/pull/961
And it does not build either.
Now I have enabled build for commits and build on the shippable of the source project, and reset it.
Going to close this pull request as well, and open an even newer one.
Let's see.

**Comment by magwas** [comment]
... and still no build: https://github.com/edemo/PDOauth/pull/962
Help!

**Comment by magwas** [comment]
Moreover, there is no green tick or yellow circle near the commit  8084eea in https://github.com/edemo/PDOauth/pull/959 but that commit is already built to green on claymanus's PDOauth shippable project. (He have manually triggered another build of the branch now.)

This is a showstopper for us, as we don't want to acquire a habit of integrating without green build.

**Comment by magwas** [comment]
Same for the commit 0c5efe3 of https://github.com/edemo/PDOauth/pull/962 , the pull request I have issued above for the third time.
Interestingly for some earlier commits there are signs of shippable builds in both of the pull requests.

**Comment by manishas** [comment]
I'll ask someone to take a look as soon as the team is online in a few hours.

**Comment by manishas** [comment]
@magwas please check your project Settings -> Runs config. It should look like this if you want to build commits and pull requests:

![image](https://cloud.githubusercontent.com/assets/2983749/22631043/9d9b3968-ebba-11e6-8131-63d44823acc4.png)

**Comment by magwas** [comment]
So I should set pull requests to DISABLE if I want to ENABLE build on pull requests???
Strange.
Nonetheless it seems to work...
