### ISSUE TITLE
Shippable build hangs out after job initialization

### ISSUE THREAD

**Issue by PaulWebbster** [Shippable/support#3345]
All of our builds on Shippable hangs out after job initialization step.

Console log available here: https://app.shippable.com/runs/589441ced3cc6a1000c484f2/1/console

**Comment by rageshkrishna** [comment]
@PaulWebbster Can we try triggering a build on your project to debug?

**Comment by PaulWebbster** [comment]
Yes, sure

**Comment by PaulWebbster** [comment]
@rageshkrishna We still have the issue described above but only in two builds.

Feel free to trigger this builds for testing purposes.

https://app.shippable.com/projects/5832df74fd9c101000d708a8/status/dashboard
https://app.shippable.com/projects/5858ef078171491100bb4e36/status/dashboard

**Comment by rageshkrishna** [comment]
Hi @PaulWebbster. W've looked in to this and rounded down the problem to one of your SSH key integrations. It looks like setting a value that isn't a real SSH key here trips up our build runner.

Can you please try double checking the integrations on these two projects and verify that the SSH integrations have correct values?

**Comment by PaulWebbster** [comment]
Yes sure, I will check
