### ISSUE TITLE
found SSH Key integration but SSH key not found in /tmp/ssh 

### ISSUE THREAD

**Issue by yumetodo** [Shippable/support#3347]
ref: #2593 

I'm trying to deploy minified css/JavaScript to ``gh-pages`` branch.
To push commit, created on shippable, to Github, SSH key is required.
So, I configured SSH integration as below.

1. Generate Public/Private key in my local PC by

```sh
$ssh-keygen -t rsa -b 4096 -C "yume-wikijp@live.jp" -f github_deploy_key -N ''
```

2. Go to the Dashboard  
![image](https://cloud.githubusercontent.com/assets/10869046/22623533/c9805c34-eba1-11e6-9f82-96db201c9b40.png)
3. Go to Integrations  
![image](https://cloud.githubusercontent.com/assets/10869046/22623552/55261ff8-eba2-11e6-9c3a-ce01c6d4c835.png)
4. Add Integration  
![image](https://cloud.githubusercontent.com/assets/10869046/22623556/76155774-eba2-11e6-80e6-a524790a1240.png)
5. Named integration as ``shippable2githubssh``  
![image](https://cloud.githubusercontent.com/assets/10869046/22623559/915a3bbc-eba2-11e6-976b-2db54d923b27.png)
6. Account Integrations -> Add integration  
![image](https://cloud.githubusercontent.com/assets/10869046/22623561/ae4d11ae-eba2-11e6-91d6-aed9a1208730.png)
7. Choose SSH Key  
![image](https://cloud.githubusercontent.com/assets/10869046/22623567/d1e596ae-eba2-11e6-9c51-5f0f23c5b1e3.png)
8. Named integration as ``shippable2githubssh`` , paste Public/ Private key and click save.  
![image](https://cloud.githubusercontent.com/assets/10869046/22623570/fa381fa0-eba2-11e6-8ff9-f585546fe1d7.png)
9. Save  
![image](https://cloud.githubusercontent.com/assets/10869046/22623575/2444a160-eba3-11e6-8964-72526ef233a4.png)
10. Check correctly saved  
![image](https://cloud.githubusercontent.com/assets/10869046/22623579/38f4921e-eba3-11e6-9835-de2ce9ede1b8.png)
11. Go to the Github Repogitry -> Setting -> Deploy keys  -> Add deploy Key
![image](https://cloud.githubusercontent.com/assets/10869046/22623580/5b818936-eba3-11e6-8d88-d887a5f735e4.png)
12. Paste public key, allow write access and click add key.
![image](https://cloud.githubusercontent.com/assets/10869046/22623589/7e36778e-eba3-11e6-9afb-d7e81893444f.png)
13. check correctly registered.  
![image](https://cloud.githubusercontent.com/assets/10869046/22623593/9bf487d4-eba3-11e6-83d1-9ae7d7a2b7d0.png)
14. Commit yml and deploy script  
https://github.com/yumetodo/Hatena-Blog-Themes/pull/2/commits/7016eb28d6c681618991368d6849d607558dacdb
15. **Deploy failed** because SSH key not found that I create in ``/tmp/ssh ``
https://app.shippable.com/runs/58969f06fd5a0e0f00f20244/1/console
Lool up build_ci

```sh
$ls -l /tmp/ssh
total 8
-rw------- 1 root root 1680 Feb  5 03:44 00_sub
-rw------- 1 root root 1676 Feb  5 03:44 01_deploy
```

According to the build console, integrations ``shippable2githubssh`` was found. However, SSH key not found. 

**What is a problem of my step?**

**Comment by manishas** [comment]
@yumetodo the build you've linked to is a pull request build for a public project. For security reasons, we do not enable integrations for these builds since anybody can submit a pull request and trigger a deployment. Is this happening for merge/commit builds as well?

Please see https://github.com/Shippable/support/issues/2775

**Comment by manishas** [comment]
I don't see this mentioned in the docs, so we will update that.

**Comment by yumetodo** [comment]
@manishas I thought that disabling deploy when it is PR is a next step of this issue. I didn't know that integrations is disabled when it's PR.

I succeeded to auto-deploy for marge commit!
https://app.shippable.com/runs/5897c5efc57f200f00dbfcd0/1/console

---

>I don't see this mentioned in the docs, so we will update that.

That's very kind of you.

---

Is there way to check weather it is PR build or not other than checking ``/tmp/ssh``?

**Comment by manishas** [comment]
The icon inside the status circle indicates the difference:

http://docs.shippable.com/navigatingUI/builds/overview/#build-status-definitions

The white icon inside the circle shows whether a commit or a pull request triggered the build:

![image](https://cloud.githubusercontent.com/assets/2983749/22631517/b4d11a9a-ebc3-11e6-9327-97ef1e59ddfc.png) for a build triggered by a commit

![image](https://cloud.githubusercontent.com/assets/2983749/22631524/c215a450-ebc3-11e6-81d2-4c3f9e2213d2.png) for a build triggered by a pull request

**Comment by manishas** [comment]
Closing this issue.

**Comment by yumetodo** [comment]
@manishas As far as I know, there is no way to check that icon in yml...
Is there way to check weather it is PR build or not **in yml script**?

**Comment by manishas** [comment]
Sorry I misunderstood :)

You can check the IS_PULL_REQUEST environment variable> It is set to true if the build is a pull request. If not, it will be set to false.
 
http://docs.shippable.com/ci/advancedOptions/environmentVariables/

**Comment by yumetodo** [comment]
@manishas Oh, I missed that document. thank you!
