### ISSUE TITLE
Environment variables not loaded

### ISSUE THREAD

**Issue by micheleangioni** [Shippable/support#335]
Dear @avdrav ,
I chose to open a new issue since a can give you some more details.
First of all, the minions are now working well.
My actual problem is that env variables are not being loaded, causing all tests to fail.
My repo is a BitBucket private repo, php project build with Laravel 4. The project id should be 53d813d16353776a05fb860e
My shippable-yml is:

```
language: php

php:
  - 5.4

services:
  - redis

env:
  global:
    - DATABASE_MYSQL_NAME=testing DATABASE_MYSQL_USER=testing DATABASE_MYSQL_PASSWORD=testing MAIL_USERNAME=testing MAIL_PASSWORD=testing

before_script:
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install

script:
  - phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage app/tests/unit
```

and the error reported in the dashboard build is:

```
 phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage app/tests/unit
PHPUnit 4.1.4-21-ge4c97ee by Sebastian Bergmann.
Configuration read from /home/minion/projects/53d813d16353776a05fb860e/code/phpunit.xml
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
Time: 1.38 minutes, Memory: 98.75Mb
There were 30 errors:
1) UserControllerTest::testIndex
ErrorException: Undefined index: DATABASE_MYSQL_NAME
/home/minion/projects/53d813d16353776a05fb860e/code/app/config/database.php:58
```

the code line giving error is:

```
'database'  => $_ENV['DATABASE_MYSQL_NAME'],
```

Probably I'm making a mistake somewhere.. help! :)
Thanks in advance!

**Comment by monooso** [comment]
I appear to have exactly the same problem, but the solution above with an apparent solution includes a broken image link (why?) to an unknown function.

Can anybody clarify what the solution to this problem is, please?

**Comment by manishas** [comment]
@monooso the suggestion was to use the getenv() function.

**Comment by monooso** [comment]
Thanks @manishas. I'll try that out.
