### ISSUE TITLE
Deleted project still accessible

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3350]
It seems like even after deleting a project its [status](https://app.shippable.com/projects/58984c3ef6ea981100c7e9cd/status/dashboard) and [settings](https://app.shippable.com/projects/58984c3ef6ea981100c7e9cd/settings/options) are still accessible if one still has the project ID.

This is not really an issue but could be fixed to avoid confusion.

**Comment by abhijitkini** [comment]
thanks for the feedback. It'll be addressed in the next release.
