### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by ronnix** [Shippable/support#3351]
Is Python 3.6 available in the default build images?

**Comment by abhijitkini** [comment]
Not at this time. We'll be including it when we update our images in the upcoming releases.

**Comment by ronnix** [comment]
OK. What is the timeline for this?

**Comment by abhijitkini** [comment]
end of this month

**Comment by avinci** [comment]
This is launching this week and will be available as an option to pick for images.

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.

**Comment by ronnix** [comment]
Thanks, switching to v5.3.2 images. I'll open another issue if we run into any problems.

**Comment by Borda** [comment]
with this image  v5.3.2 can I use pythons 2.7 and 3.6 or there is just one - 3.6?
