### ISSUE TITLE
504 downloading the console log

### ISSUE THREAD

**Issue by swhite-finovertech** [Shippable/support#3352]
For one of our larger projects, we continually get 504 downloading console log. Ex

  https://app.shippable.com/download/jobConsoles?jobId=5898a2e28be1080f0079ef4a

The 504 always occurs after a period of 30 seconds.  Is there a way to get around the problem, like perhaps increasing the timeout period?

**Comment by swhite-finovertech** [comment]
I attempted to download the same logfile using the shippable API i.e.

 https://api.shippable.com/jobs/5898a2e28be1080f0079ef4a/consoles?download=true

but I still get the 504 GATEWAY TIMEOUT after 30 seconds.

**Comment by avinci** [comment]
@swhite-finovertech your build is uploading 15gb of logs. We do not allow more than 16mb of consoles and this is causing various other problems in the system. We had a governor in the system that got removed in the recent release and hence the issue. 

Could you kindly reduce the logs that your build is generating? Thanks very much

**Comment by abhijitkini** [comment]
closing as resolved
