### ISSUE TITLE
Failed to send e-mail

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#3355]
Hi, the build here https://app.shippable.com/runs/5899ef605512b90f00b6d2e9/1/console
 runs smoothly, but I'm getting an error
```
Failed to send mail for objectId:5899ef605512b90f00b6d2e9 with error Error: Invalid login: 535 5.7.0 Mailgun is not loving your login or password
```
I haven't changed my e-mail settings, any idea of what can cause this problem?

**Comment by stephanielingwood** [comment]
Hi @jacopo-chevallard,

Thanks for the heads-up. Looks like we had a glitch with our email service; we've reset it and your emails should be sending now. 

Sorry for the inconvenience! Do let us know if you see this again or have any questions. 

Cheers.

**Comment by jacopo-chevallard** [comment]
Great, I'll check asap! Thanks for the fast reply!!

**Comment by jacopo-chevallard** [comment]
Mail notifications are working indeed, closing
