### ISSUE TITLE
Logs not available

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3358]
I've noticed that quite a lot of our builds show `Logs not available`, [example](https://app.shippable.com/runs/588726f13b653a0f00fb3231/1/console)

Does Shippable purge older logs after some time or is this a bug?

**Comment by trriplejay** [comment]
Typically logs older than 15 days are deleted. However we did introduce some functionality that will increase this length of time.  It was just deployed recently, so I think any logs from about Feb 2nd onward should stick around much longer.

**Comment by abhijitkini** [comment]
closing as resolved.

**Comment by mbrodala** [comment]
@trriplejay Thanks for clarifying this. Is this mentioned somewhere? I'd assume that this is unexpected to a lot of people.

And what does "longer" mean exactly?

**Comment by trriplejay** [comment]
Looks like we don't currently document that information. I'll open an issue to add it to our documentation, and get a more solid answer for you regarding how long.

**Comment by mbrodala** [comment]
Just now I noticed an issue in one of our projects and the Shippable log could have helped debugging it but unfortunately it was deleted already. :-/

I hope the new log lifetime is at least a few months.

**Comment by abhijitkini** [comment]
@mbrodala For builds after Feb 17, the console logs will be stored for 3 months. Details in [the documentation](http://docs.shippable.com/ci/advancedOptions/console-logs/).

**Comment by mbrodala** [comment]
@abhijitkini Thanks for updating the docs.

So I can assume that there is absolutely no way to restore older logs, e.g. from backups or the like if someone needs to debug an issue?

**Comment by abhijitkini** [comment]
Unfortunately we do not restore older logs. We hope the increased duration from 14 days to 3 months will help.

**Comment by mbrodala** [comment]
Yes, it'll help for future issues but not with current ones. So I'm left with guessing.

**Comment by manishas** [comment]
@mbrodala you can rebuild that particular build and get the logs.
