### ISSUE TITLE
Rebuild dissapeared from my account

### ISSUE THREAD

**Issue by luislobo** [Shippable/support#3359]
Rebuild dissapeared from my account.

I used to have permissions to rebuild and for some reason they all dissapeared. We use Bitbucket, my account name in bitbucket is luislobo.

Can you help me with this issue?

**Comment by a-murphy** [comment]
It looks like your Bitbucket account only has read access to repositories.  It's possible that your account didn't synchronize correctly.  Could you try re-synchronizing your account?  The gear icon in the top right corner on Shippable will take you to the account settings page where there is a green "sync" button.  Clicking that should update all of your permissions to match Bitbucket.

**Comment by luislobo** [comment]
Thank you for your prompt answer.
I tried that several times already but with no success yet

**Comment by luislobo** [comment]
I have several teams in bitbucket, the repository is in one of the teams... May be is that? I'm an admin of the team and the repository

**Comment by a-murphy** [comment]
Do you know when the rebuild button was last there?  And did you check that you have access to the repository on Bitbucket in the "user and group access" section of the repository settings?  It's possible to have admin access to a team but not even read access to the repository on Bitbucket.

**Comment by luislobo** [comment]
I don't remember because I almost never had to do that.
There are two people as admins, my self, and KeatonFoster, into that repository. He can see Build, I cannot.
What would happen if I delete my account form shippable and add it back?

**Comment by a-murphy** [comment]
Very little would change if you deleted your account and added it back.  It's extremely unlikely to help with permissions any more than the sync button (the same process would create permissions for the new account), but it would cause any API tokens you had created to stop working, account integrations to be deleted, some projects are deleted as a result, and a new accountId would be created for the new account.

**Comment by luislobo** [comment]
So, then, what can I do to fix it? can you tell me what command / api are you using with bitbucket to see if it's a bitbucket issue?

**Comment by a-murphy** [comment]
Since you do have read access, it's just the permission level.  For that, we use `https://api.bitbucket.org/2.0/repositories?role=admin`, `https://api.bitbucket.org/2.0/repositories?role=owner`, and `https://api.bitbucket.org/2.0/repositories?role=contributor`.

**Comment by luislobo** [comment]
I can see myself as an admin using 
`https://api.bitbucket.org/2.0/repositories?pagelen=100&role=admin`

**Comment by luislobo** [comment]
OK, today when I opened Shippable, a growl message appeared saying Your account is Syncing. And then, your Account is in sync. Now all works!

**Comment by a-murphy** [comment]
Sorry for the trouble.  We've found a sudden increase in rate limited requests to Bitbucket, which caused at least your later sync failures.  We're looking into it.

**Comment by luislobo** [comment]
Oh, ok! thank you, for now anyway, my account is in sync, and I can see the build/rebuild buttons.
