### ISSUE TITLE
Trigger runSh from rsync 

### ISSUE THREAD

**Issue by nmarshall-cst** [Shippable/support#3360]
### Trigger runSh from rsync 
Hello - I am trying to trigger a runSh job after a successful rsync. After looking over the documentation I am not able to pinpoint the trigger job to kick the runSh on a successful rsync. Any guidance would be appreciated.

**Comment by trriplejay** [comment]
Hello,

There are two main ways you can do this.

If you have a job that you want to run *every* time rSync completes successfully, then you can just use the name of the rSync job as an `- IN` to your other job.  This will attach the rSync job directly to the subsequent job.

The other way to control the triggering of jobs based on yml change is through the `shippable.triggers.yml` file.  You can create a 'trigger' and attach it to one or more jobs in your pipeline.  Once attached, those jobs will be triggered any time that trigger's `version` section is changed in the yml.  Check out our docs for how to define and use triggers: http://docs.shippable.com/pipelines/triggers/


The main difference is that with triggers, if you update the trigger, rSync will trigger the job, even if rSync itself ends with one or more errors (red status).  If you directly connect rSync to the job, then it will always trigger the job when rSync itself ends successfully (green status).

does that make sense? let me know if you have more questions.

**Comment by nmarshall-cst** [comment]
When I add the rsync name to my jobs -IN section I receive this error: 

_No resource exists for name docker_dbpool_ID-183_rsync_

Do I have to define my rsync job in the resources.yaml or is there a separate name that the rsync falls unders?

**Comment by a-murphy** [comment]
Could you try updating your `shippable.jobs.yml` to capitalize the "S" in "rSync"?  Resource names are case-sensitive, so that's why it's not finding your rSync job.

**Comment by nmarshall-cst** [comment]
Ah! Nice catch! That did the trick. Thank you both for the help on this.
