### ISSUE TITLE
Lot of missing projects.

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3361]
Seems a lot of projects are missing in our subscription overview, we use bitbucket.

Also builds don't seem to trigger at the moment.

**Comment by bbrala** [comment]
swisnl, and ehh missing loads really, few examples; qlinix, webbeheer-testing, aap.

**Comment by kanthchandra** [comment]
Can you trying syncing your account from your account settings page? In the mean time I'll check the logs to see if I can find anything.

**Comment by kanthchandra** [comment]
@bbrala Did the syncing fix your problem?

**Comment by bbrala** [comment]
No Sorry that was the first thing I tried

Op 10 feb. 2017 17:58 schreef "Chandrakanth" <notifications@github.com>:

**Comment by a-murphy** [comment]
We've found that there's been a recent increase in rate limited requests to Bitbucket.  We're looking into it, but suggest waiting and then clicking the "sync" button again.  Bitbucket's rate limits should reset every hour.

**Comment by avinci** [comment]
@bbrala we have deployed a fix to reduce number of calls made to SCM in this version. Please let us know if this is still happening.
