### ISSUE TITLE
How do I configure a shippable.yml for multiple deployments

### ISSUE THREAD

**Issue by darilldrems** [Shippable/support#3362]
How do I create a shippable file that can deploy to multiple servers using aws integrations for different branches.

So if a merge was done to master and it passes tests then deploy to the environment specified for master. 

If it was for dev then deploy to environment set to dev on heroku or aws.

Thanks

**Comment by manishas** [comment]
You can configure this by using a combination of the `branches` keyword while defining integrations in your yml and the $BRANCH environment variable to determine where to deploy.

More on a simple example using $BRANCH here: http://blog.shippable.com/specifying-deployment-targets-for-different-git-branches

Example for `branches` keyword is in this issue: https://github.com/Shippable/support/issues/3340

Let me know if this helps... happy to answer follow up qs.
