### ISSUE TITLE
Integration fails, but build shows it is succesfull

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3364]
Hello,

quite new to shippable, so might not have understood correctly, but deploying a custom build image to aws fails with errors (authentication etc.), but the build is green.

Should it not highlight the errors better and fail the build?

https://app.shippable.com/runs/58a1a8dab195740f00e090b4/1/console

Mikko

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by avinci** [comment]
this is by design. We do not fail a build on deployment. A better way to do this will be through pipelines where you get a lot more control. EB will be launched next week into prod where you can do CI and then do a deployment to EB. Let me know if you need more info. Happy to jump on a hangout.

**Comment by mikkopori** [comment]
yep, tnx for clarifying!
