### ISSUE TITLE
Emails sent to wrong address

### ISSUE THREAD

**Issue by gappleto97** [Shippable/support#3366]
I changed my email address in both Github and Shippable. Shippable emails are still getting sent to the old address. Can you correct this?

**Comment by a-murphy** [comment]
Is your old address still in your git config used for commits?  By default, emails are sent to the last author, as long as that email address is identified as someone who belongs to the project.

If you would like to notifications to be sent to a specific address, it can be configured in your shippable.yml as documented [here](http://docs.shippable.com/integrations/notifications/email/).
