### ISSUE TITLE
[Urgent] Elastic Beanstalk Integration fails on specific region

### ISSUE THREAD

**Issue by KnowRe** [Shippable/support#3367]
https://app.shippable.com/runs/58a40a939b5dfa0f0043ccbf/1/console

Seems like Elastic Beanstalk integration fails on specific(`us-east-1` on my case) region, because CodeCommit option was newly introduced to EB CLI.

FYI, I use my own node and reset them as the email notice yesterday.

```
echo | eb init "MyApplication" -r "us-east-1" -p "" 2s  
Select the default environment. 
You can change this later by typing "eb use [environment_name]".
1) my-environment1
2) my-environment2
(default is 1): Note: Elastic Beanstalk now supports AWS CodeCommit; a fully-managed source control service. To learn more, see Docs: https://aws.amazon.com/codecommit/
Do you wish to continue with CodeCommit? (y/N) (default is n): ERROR: EOFError :: EOF when reading a line
```

**Comment by rageshkrishna** [comment]
It looks like you're running on a custom image with a specific version of EB cli. Newer versions of EB cli show this prompt. Can you check if downgrading to an older version as suggested in https://github.com/Shippable/support/issues/3065 helps?

**Comment by KnowRe** [comment]
It works. Thank you very much!

**Comment by KnowRe** [comment]
https://forums.aws.amazon.com/thread.jspa?messageID=750663

Hello,
I downgraded my EB cli to 3.7.8 and this same bug as the link above started to occur. I think only applying the latest version of EB can resolve this.

So could you please support the latest version of EB cli?

**Comment by rageshkrishna** [comment]
We are launching updated images with the latest CLIs in the coming week. I'll comment here as soon as the new images are available.

**Comment by KnowRe** [comment]
Hello,
Is there any schedule for this fix to be shipped?

**Comment by rageshkrishna** [comment]
@KnowRe The new images will be officially launched in a couple of days, but I just checked and we still have the issue with the new Amazon EB CLI asking the question about CodeCommit. I'm looking in to a fix for that and will update this issue as soon as we have a resolution.

**Comment by rageshkrishna** [comment]
@KnowRe We have figured out a fix that will allow you to use the latest `eb` releases. This will be deployed over the weekend. I will update this issue as soon as it's live so you can update your images and give it a shot.

Thank you for your patience on this issue.

**Comment by avinci** [comment]
This has been fixed and deployed to production. Please let us know if you encounter any further issues
