### ISSUE TITLE
Hanging pipeline job on BYON after reset

### ISSUE THREAD

**Issue by timkral** [Shippable/support#3369]
I reset our BYON nodes this week per your requirements to do so and now our shRun pipeline deployment job is hanging.

After the reset, our CI job is passing and correctly triggering the pipeline deployment. However, the pipeline job is hanging during the `Provision job node` phase.

Here are the logs that I downloaded:

```
Getting subscription integrations
Successfully fetched subscription integrations
Getting subscription integration permissions
Successfully fetched subscription integration permissions
Checking subscription integration permissions
Getting account integrations
Successfully fetched account integrations
Decrypting secure envs
Successfully decrypted secure envs
Saving integrations
Successfully saved integrations
Info
Running job on customer's build node for subscriptionId: 554aae94edd7f2c052e3972d
```

Normally, this deployment takes under a minute. I've tried to let it run for 20 minutes just in case there were provisioning steps that needed to happen, but there was no progress in the logs. I've also tried resetting the BYON nodes and running the CI job from scratch.

This is blocking our ability to continuously deploy to our test environment.

**Comment by trriplejay** [comment]
based on your node reset logs, it looks like there was some issue during reset, do you have access to the node? what is the result of a `sudo docker ps -a`?

**Comment by timkral** [comment]
Yes, here's the output:

```
$ sudo docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
e7fd336b9423        shipimg/genexec:v5.2.2   "/home/shippable/micr"   22 hours ago        Up 51 minutes                           shippable-exec-5883b6cb587bd11000cf923a
```

**Comment by trriplejay** [comment]
could you do a `docker stop -t=0 e7fd`, and then click the 'reset' button once more?

**Comment by timkral** [comment]
Ok, here's the output:

```
$ sudo docker stop -t=0 e7fd
e7fd
$ sudo docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
e7fd336b9423        shipimg/genexec:v5.2.2   "/home/shippable/micr"   22 hours ago        Up 24 seconds                           shippable-exec-5883b6cb587bd11000cf923a
---- RESET BUTTON PUSHED ----
$ sudo docker ps -a
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
6814cc42d3cc        shipimg/genexec:v5.2.2   "/home/shippable/micr"   9 seconds ago       Up 8 seconds                            shippable-exec-5883b6cb587bd11000cf923a
```

From a blackbox perspective, it doesn't look like anything changed. Should I try the pipeline job again?

**Comment by trriplejay** [comment]
go ahead and cancel the current job, but don't start a new one yet, i want to check on something.

**Comment by timkral** [comment]
Ok, hanging job has been stopped.

**Comment by trriplejay** [comment]
ok, everything looks normal. can you go ahead and run your job?

**Comment by timkral** [comment]
SUCCESS! Thank you for your help @trriplejay
