### ISSUE TITLE
Timeout termination

### ISSUE THREAD

**Issue by bibendi** [Shippable/support#337]
Documentation says:
If your script or test suite hangs for a long time or there hasn’t been any log output in 20 minutes.

Our build script runs longer than 20 minutes and it continuously writes to stdout.
And with all this, the build falls with error 'Command timed out'
https://www.shippable.com/projects/53d214e9c1763bb6017e8afc/builds/36

**Comment by moylop260** [comment]
Hello @manishas 
Can I increase timeout in our startup plan?

I have similar problem here:
[timeout_build](https://app.shippable.com/builds/5523f428bd14530c001e99f8)
