### ISSUE TITLE
Build reports available to unauthenticated and unauthorised users 

### ISSUE THREAD

**Issue by Reagan** [Shippable/support#3371]
When using webhooks, unauthenticated users are able to view the list of Build Runs. While the actual logs are not available to unauthenticated users, being able to view the list of build runs to unauthenticated users raises security concerns.

**Comment by rageshkrishna** [comment]
@Reagan I'm not sure I've understood the scenario you're running in to. Repositories that are public on GitHub/BitBucket are visible to public users on Shippable. Private repositories should be accessible only to authenticated users with permissions to the repository.

If that's not what you're seeing, please email me at ragesh@shippable.com so we can discuss the issue in detail. Thanks.

**Comment by avinci** [comment]
@Reagan please let us know if this is still an issue...and re-open. Public projects are open and users can see this information by design.
