### ISSUE TITLE
Ubuntu 16.04 support for custom nodes

### ISSUE THREAD

**Issue by pavelbinar** [Shippable/support#3372]
I am trying to add my own node.

I run command from the node settings dialog:

```
sudo useradd -d /home/shippable -m -s /bin/bash -p shippablepwd shippable && sudo echo 'shippable ALL=(ALL) NOPASSWD:ALL' | sudo tee -a /etc/sudoers; sudo mkdir -p /home/shippable/.ssh/; sudo chown -R $USER:$USER /home/shippable/; echo ssh-rsa SECRET >> /home/shippable/.ssh/authorized_keys; sudo chown -R shippable:shippable /home/shippable/
```

No errors.

I see red icon next to my node. Here is the detail of
`ID: 58a5b535ec8b7210004f5e8a IP Address: XX.XXX.XX.XXX Created At: Today at 3:20 PM`

```
copy_script_remote
  echo 'Copying keys' 0s  
Copying keys
  echo 'Removing any host key if present' 0s  
Removing any host key if present
/root/.ssh/known_hosts updated.
Original contents retained as /root/.ssh/known_hosts.old
  echo 'Establishing connection and copying Files' 0s  
Establishing connection and copying Files
executing rsync -avz -e 'ssh -o StrictHostKeyChecking=no -o NumberOfPasswordPrompts=0 -p 22 -i /tmp/ba11e032-aa3f-4f36-95bd-c034f186ad75/node_key -C -c blowfish' /tmp/ba11e032-aa3f-4f36-95bd-c034f186ad75 shippable@XX.XXX.XX.XXX:/tmp
no matching cipher found: client blowfish-cbc server chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
```

```
Command failed : /tmp/ba11e032-aa3f-4f36-95bd-c034f186ad75/ba11e032-aa3f-4f36-95bd-c034f186ad75-0.sh ba11e032-aa3f-4f36-95bd-c034f186ad75 0 Exception Script failure tag received
```

It seems that `rsync` is having issues copy the file into `/tmp`

I found few tickets regarding this issues, but they was always resolved one to one, no public information.

My Shippable ID: `58495782a932c20f003a2f81`

Thanks!

**Comment by kanthchandra** [comment]
Hi @pavelbinar before we begin our investigation can you please us the following details.
1. Did you run the command that authorizes us to ssh into the node before trying to init the node (this is shown in the UI when you try to initialize a node)?
2. Can you please check if your ssh service is running on the host and listening to requests on port 22 like you have configured.

**Comment by pavelbinar** [comment]
Add 1. YES. See my original comment:

I run command from the node settings dialog:

```
sudo useradd -d /home/shippable -m -s /bin/bash -p shippablepwd shippable && sudo echo 'shippable ALL=(ALL) NOPASSWD:ALL' | sudo tee -a /etc/sudoers; sudo mkdir -p /home/shippable/.ssh/; sudo chown -R $USER:$USER /home/shippable/; echo ssh-rsa SECRET >> /home/shippable/.ssh/authorized_keys; sudo chown -R shippable:shippable /home/shippable/
```

Add 2. YES. I am able to connect to my server via standard ssh on port `22`

Add 3. Ubuntu 16.04 LTS

**Comment by a-murphy** [comment]
Ubuntu 16.04 isn't currently supported for custom nodes.  We're planning to add it, but for now you will have to use Ubuntu 14.04.  Please make sure that your node also meets the [minimum requirements](http://docs.shippable.com/ci/advancedOptions/byon/#minimum-requirements) for RAM and disk space.

**Comment by avinci** [comment]
this is getting launched by end of next week. We already have it working in our test environments and will be pushed to prod next week.

**Comment by jmills-bespoke** [comment]
any update on this availability in ubuntu 16.04 ?

**Comment by ric03uec** [comment]
@jmills-bespoke sorry about the delay in updating this issue.
Support for ubuntu 16.04 on custom nodes will be available with our next release by monday 03/13

**Comment by avinci** [comment]
this has been launched to production just now. Please let us know if you encounter any issues using the new initialization scripts.

**Comment by jmills-bespoke** [comment]
@avinci I can't seem to get rid of this error message 
```
(Id: 4005) Failed to generate itinerary for node :id NODE_ID error: ActErr { logType: 'verbose', methodName: 'common|genInitSteps|nodeId:NODE_ID|_checkInputParams', id: 4004, message: 'Missing data: params.nodeInitScript' }
verbose: clusterNodes|put|callerId:CALLER_ID|clusterNodeId:NODE_ID|_generateInitSteps
```

**Comment by a-murphy** [comment]
It sounds like no script was select in the "Node Type" dropdown.  When you're adding the new node, could you check that the correct Ubuntu version is selected before clicking "initialize" or "generate initialization scripts?  Full directions to initialize a node are available [here](http://docs.shippable.com/ci/advancedOptions/byon/#adding-a-build-node).  And we'll look into why the page let you try to initialize the node without selecting a script.

**Comment by jmills-bespoke** [comment]
@a-murphy thanks! I did a hard reset with just deleting all nodes and beginning fresh with a new ec2 node server and it works fine now. 🍻
