### ISSUE TITLE
Deploy master after PR merge

### ISSUE THREAD

**Issue by TimvdEijnden** [Shippable/support#3376]
### Description of your issue:
We've got the following in our shippable.yml:

```yml
branches:
 except:
   - master
```

Because we only want to test & deploy the Branches from the PR's we create. If we remove this section shippable builds the PR & PR + master, that's something we don't want. But our master wont be deployed this way. We prefer that the master will be tested & deployed after a merge of a PR. What should we do to make this work?

**Comment by manishas** [comment]
@TimvdEijnden let me clarify the behavior you're looking for. Let's say you have `master` and `dev` branches. You commit a change to your `dev` branch and then open a PR to `master` branch. Then the PR gets merged to `master`.

Which of the following events do you want to trigger CI for:

- commit to dev branch
- open PR from dev to master
- merge PR to master

**Comment by TimvdEijnden** [comment]
We only have a master branch for which we open PR's. 

We want to trigger CI for:
* commits to master (PR merge) 
* open PR to master

**Comment by manishas** [comment]
So you do not want to trigger CI when you commit to `dev` branch?

**Comment by manishas** [comment]
I think we're missing something in communication. 

Can we jump on a hangout and clarify the scenario? https://hangouts.google.com/hangouts/_/shippable.com/manisha?authuser=0

**Comment by manishas** [comment]
The following config will ensure that only commits to `master` and PRs from other branches to `master` are built

```
branches:
  only:
    - master

```

**Comment by TimvdEijnden** [comment]
I'm sorry but you're right in your first comment. We create a branch for each story so that's it was confusing for me. So let's say that these are called the dev branch. Then I want exactly what you said

**Comment by manishas** [comment]
:+1:

Let us know if it works as expected and if you have any more questions. Closing this issue.

**Comment by TimvdEijnden** [comment]
I've changed it to:

```
branches:
  only:
    - master
```

Now if I commit to a dev branch, a CI is triggered. (Thats good!)
And it uses the sha of the commit I made (Thats good too)
And it the branch name is master (Thats OK as long as it's the code from the sha)

But after the test I want to deploy that code to our CDN in a name that matches the PR branch.

So in the on_success we run a script to do this. I've added to following to get access the the PR branch name:

```
#!/bin/bash
if [ -z ${PULL_REQUEST_BASE_BRANCH+x} ]; then 
    echo "keeping branch ${BRANCH}"
else
    echo "changing branch to ${PULL_REQUEST_BASE_BRANCH}"
    BRANCH=$PULL_REQUEST_BASE_BRANCH
fi
```

The output was:`changing branch to master` so PULL_REQUEST_BASE_BRANCH has the value master. How do I know the name of the branch the commit and PR is from?

**Comment by a-murphy** [comment]
It sounds like you are looking for `HEAD_BRANCH` instead of `PULL_REQUEST_BASE_BRANCH`.  The head branch is the branch that the pull request is opened from and the base branch is the one that it will be merged into.  The available environment variables are documented [here](http://docs.shippable.com/ci/advancedOptions/environmentVariables/) in case you need any more variables.

**Comment by TimvdEijnden** [comment]
That works for us, thank you! 😃
