### ISSUE TITLE
selenium-server-standalone-3.0.1.jar

### ISSUE THREAD

**Issue by ZeroPit** [Shippable/support#3378]
### Update selenium-server-standalone 2.52 to 3.0.1
Hi can you update the selenium-server-standalone to 3.0.1 or can show me how can i use me local selenium-server-standalone-3.0.1.jar in the git files

Thanks

- Error log in build_ci
WebDriverException: Message: TypeError: Cannot find function createHTMLDocument in object [object DOMImplementation]. (http://localhost:8081/static/gui/js/jquery.min.js#4)

- https://app.shippable.com/runs/58a9cd575c87e70f00893861/1/console

**Comment by ZeroPit** [comment]
I have find a way but now I get this 
```
export SHIPPABLE_SELENIUM_CMD="java -jar /srv/selenium-server-standalone-3.1.0.jar -Djava.security.egd=file:///dev/urandom -port 4444 > /dev/null 2>&1 &" 0s  

~/src/github.com/XXXXX/XX
/root/ea966f24-86e2-4e27-880e-e3046980c696.sh: line 540: [: missing `]'
```
And 
```
selenium_start 3m 33s
  sudo su -c "java -jar /srv/selenium-server-standalone-3.1.0.jar -Djava.security.egd=file:///dev/urandom -port 4444 > /dev/null 2>&1 & > /dev/null 2>&1 &" 0s  
  echo 'Service selenium boot error, restarting...'
```

and this are the YML
```
language: python

python:
  - 2.7

addons:
  selenium: "3.1"

services:
  - selenium
```

**Comment by stephanielingwood** [comment]
Hi @ZeroPit,

Thanks for your question. While we don't officially support selenium 3.1, you can likely get this to work by using one of our images with Java 8 (which Selenium requires), such as drydock/u14javall, removing the "services" section from the yml so we don't try to boot selenium, and then booting selenium 3.1 yourself. Actually, in looking at your build history, it looks like you've gone the route of a custom image and your builds are succeeding - which is always a great way to go, since you get absolute control over what's installed.

We'll mark this as a feature request, though, to support it as an option from the yml. In the meantime, if you have other questions, let us know.

**Comment by avinci** [comment]
Selenium 3.01 is getting launched this week with the new images. You will need to manually update the image that you use for your build and it should start using the new version. Docs will be updated with more details.

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.

**Comment by nealeu** [comment]
@avinci Can we get the docs updated to say what's in the u16 versions please.  e.g. http://docs.shippable.com/ci/languages/java/ and http://docs.shippable.com/ci/languages/node/

**Comment by rageshkrishna** [comment]
@nealeu Sorry about the delay on the docs. They will be updated shortly. In the mean time, here's a list of what's available in the images you asked about:

## Java (drydock/u16javall:v5.3.2)
  * openjdk7
  * openjdk8
  * oraclejdk7 
  * oraclejdk8

## Node (drydock/u16nodall:v5.3.2)
* 0.10
* 0.12 (default if no runtime specified)
* 4.2.3
* 4.6.0
* 5.12.0
* 6.7.0
* 6.8.0
* 6.9.4
* 7.0.0
* 7.2.1
* 7.3.0
* 7.4.0
* iojs 1.0
* iojs 2.0
* iojs 3.3.1

## Services

Both images come with the following:

* couchdb 1.6
* elasticsearch 5.1.2
* neo4j 3.1.1
* memcached 1.4.34
* mongodb 3.4
* mysql 5.7
* postgres 9.6
* rabbitmq 3.6
* redis 3.2
* rethinkdb 2.3
* riak 2.2.0
* selenium 3.0.1
* sqllite 3

In addition, the following packages are also available on both images:

* Basic packages: build-essential, curl, gcc, gettext, git, htop, jq, libxml2-dev, libxslt-dev, make, nano, openssh-client, openssl, python-dev, python-pip, python-software-properties, software-properties-common, software-properties-common, sudo, texinfo, unzip, virtualenv, wget
* Java 1.8
* Ruby 2.3.3
* awscli 1.11.44
* awsebcli 3.9
* gcloud 145.0.0
* jfrog-cli 1.7.0
* kubectl 1.5.1
* packer 0.12.2
* terraform 0.8.7
