### ISSUE TITLE
cannot login into docker hub after upgrade

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#3379]
All of our builds which are using quay integration are no longer able to build. The build log shows the following error : 

`
 echo 'Hub login failed' 0s  Hub login failed
  echo 'Docker login failed for username ... and email ...' 0s  
  echo 'docker: error while loading shared libraries: libsystemd-journal.so.0: cannot open shared object file: No such file or directory'
`

please advice since this is blocking our complete ci pipeline.

**Comment by RevathiRD** [comment]
@rvdwijngaard  we are looking into it. I'll provide an update as soon as we've found the root cause.

**Comment by RevathiRD** [comment]
@rvdwijngaard Could you please provide your build link so that it will helpful to investigate more?
Thanks

**Comment by rvdwijngaard** [comment]
[build link](https://app.shippable.com/runs/58aac4365c87e70f008a86ef/1/console)

I followed the staps recommended in your email regarding the upgrade of custom nodes; I checked the logs of our custom nodes and noticed they were giving errors. 
`
Command failed : /tmp/4b1a5e72-5621-4bfe-81cf-c350a0fcc852/4b1a5e72-5621-4bfe-81cf-c350a0fcc852-0.sh 4b1a5e72-5621-4bfe-81cf-c350a0fcc852 0 Exception Script failure tag received
`

I will now terminate one of our nodes and replace them with a new instance.

**Comment by rvdwijngaard** [comment]
removing my custom build nodes and recreating them from scratch have solved this problem.
