### ISSUE TITLE
Link to jobs from build failure mail

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3382]
If a build fails, one gets an email with details about the build. This mail also contains a table with each job for the build and the result.

However, the links at the end all link to the build, it would be useful if each of these would link to the specific job instead. Thus link to `https://app.shippable.com/runs/<build>/<job>/console` instead of `https://app.shippable.com/runs/<build>/summary`.

**Comment by deepikasl** [comment]
This is in production now. The jobs in build report email links to the specific job on shippable.
Hence Closing.
