### ISSUE TITLE
Couldn't remove deleted projects and delete account

### ISSUE THREAD

**Issue by baleyko** [Shippable/support#3384]
Two private projects were deleted from the bitbucket.
And I cannot delete them, because the "Disable" button is absent in the projects list near the project.

To reset my history of using the Shippable I decided to delete account and sign up again, but...
When  I try to delete the account by clicking on "Delete Account" I see the next text in red message box:
(Id: 2002) Failed to delete project with :id 58ac693f8b69ec0f008516d4
warn: accounts|deleteById|callerId:58ac68fa0bfe5710005a89e4|accountId:58ac68fa0bfe5710005a89e4|_deleteIndividualProjects

Could you help me in this. Even we should delete my account. It's good for me. I'll sign up again.

Best regards, Valery.

**Comment by stephanielingwood** [comment]
Hi @baleyko,

We synced your account. This deleted the two projects from Shippable that had been deleted from Bitbucket. If you still want to delete your account, you shouldn't get that error again. But you also may not need to delete your account now. 

Hope this helps. Let us know if you have any questions.
Best, Stephanie

**Comment by baleyko** [comment]
Thank you guys! I'll check my account today, if I will have any problems I will notify you.
Best regards, Valery.

**Comment by baleyko** [comment]
Hey folks. Nothing is changed.
I've deleted cookies/local-storage data.
The same list of the projects, the next ones couldn't be deleted:
less   public	 02/17/2016
rebar public	 Last Tuesday at 6:23 PM
rebar public	 09/24/2015

The same error on deleting:
(Id: 4001) accounts.destroy failed for id: 58ac68fa0bfe5710005a89e4 returned error: update or delete on table "accounts" violates foreign key constraint "projects_enabledBy_fkey" on table "projects"
verbose: accounts|deleteById|callerId:58ac68fa0bfe5710005a89e4|accountId:58ac68fa0bfe5710005a89e4|_deleteAccountById

Could you just remove all the data of my account?
When I'll create a new one.

**Comment by baleyko** [comment]
Never mind... I'll just create a new account :)

**Comment by stephanielingwood** [comment]
Hi, @baleyko.

Hmm...thanks for letting us know. We're going to open an internal ticket to investigate further. In the meantime, we've deleted your account and cleaned up everything in our database. Sorry for the inconvenience. Looking forward to seeing your new account. :)

Best, Stephanie

**Comment by baleyko** [comment]
>> Sorry for the inconvenience.
No problem. Thank you!

**Comment by avinci** [comment]
this has been fixed now as we released a new version to prod. please let us know if you still encounter this issue.
