### ISSUE TITLE
"returned error verbose" looking at my personal bitbucket subscription

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3386]
When I click the menu at the top left, then click on my personal bitbucket subscription, I get the following error:

    (Id: 4004) getBuildJobs for query: subscriptionIds=58ad04eaa0f1360f009ff892&statusCodes=4001 returned error
    verbose: subscriptions|getStateById|callerId:58ad04e5a0f1360f009ff88e|subscriptionId:58ad04eaa0f1360f009ff892_getProcessingBuildJobs

Screenshot of the error:

![screen shot 2017-02-23 at 2 45 01 pm](https://cloud.githubusercontent.com/assets/112729/23244027/cc8777f8-f9d6-11e6-9c52-ee1c60afebd2.png)

I am not sure what the actual error is.

Unfortunately, this means that I can't delete integrations for this subscription, as the settings tab does not appear to work properly as a result.

**Comment by stephanielingwood** [comment]
Hi @brianmay,

That error could be a result of a subscription that doesn't contain any git projects. Does your Bitbucket subscription only contain mercurial projects? 

Thanks for checking.

**Comment by brianmay** [comment]
I have one public repository - which looks like Mercurial to me (odd - I don't remember creating this!):

https://bitbucket.org/penguin_brian/django-jsonfield

Plus a number of private repositories. The private repositories are all git based. As shippable can see other private repositories (in other organisations) through the same bitbucket credentials, I assume it should be able to see these too.

**Comment by brianmay** [comment]
Ok, I was wrong. Somehow my bitbucket has a public repository I created and had forgotten about in 2014, however doesn't have several private repositories I created in 2015. How very odd. Will continue to investigate. Wonder if this has something to do with the recent account migrations on bitbucket - not that I can really think of any good explanation - AFAIK I only ever had one bitbucket account.

 However, getting back on topic, this shouldn't be a fatal error in shippable - i.e. I think I should still be able to access the settings for the subscription which are still very important even if there are no projects.

**Comment by brianmay** [comment]
Oops sorry for the noise. I had put the private projects on gitlab, not bitbucket. Still shouldn't be a fatal error however.

**Comment by stephanielingwood** [comment]
Hi @brianmay,

Ahhh...that makes more sense.Glad to hear you found your projects. :)

And, yes, we should likely provide a way for users to interact with their subscription integrations, even if they don't have any projects. We'll look into that.

**Comment by avinci** [comment]
this has been fixed in the new UI we launched a couple of weeks ago. Please switch the UI to new UI if you have not been already moved. Everyone will be moved in the first week of July.
