### ISSUE TITLE
Educational Use of Shippable

### ISSUE THREAD

**Issue by loren138** [Shippable/support#3389]
Hi,

I'm at Georgia Tech, and we're interested in using Shippable to support builds for our class project.  The project is hosted in Github Enterprise as a private repository so we are worried we might run over the 150 builds / month limit.

My question is two part, first, can that limit be increased.  Second, what is the best way to go about it.  We'd like each group to manage their own build process as much as possible and be able to see the build status, but groups shouldn't have access to each other's code.  To accomplish this, should each group have a shippable account(s) or should we have one instructor shippable account which owns all the processes.

Groups can obviously control their own build since they can write the shippable.yml file, but I'm not sure how best to control build status/failure message access.

Thanks,
Loren

**Comment by ttrahan** [comment]
@loren138 : let's jump on a call to discuss your scenario. please contact me at tom@shippable.com.

Thanks,
Tom
