### ISSUE TITLE
`pip install python-coveralls` fails

### ISSUE THREAD

**Issue by Nzbuu** [Shippable/support#3391]
There's a failure when installing the python coverage tools on Python 3.5:

See "build_on_success" step:
- https://app.shippable.com/runs/58af1c2fb4650b0f00aa2095/2/console

**Comment by a-murphy** [comment]
The error installing packages with pip in your build appears to be a result of updating pip.  Adding `pip install --upgrade wheel` right after updating pip should avoid the errors in both installing `python-coveralls` and the contents of the `requirements.txt` file.  However, `python-coveralls` did actually install and couldn't figure out what to update on Coveralls.    You may want to check that you have a configuration file with a `COVERALLS_REPO_TOKEN` as [in the python-coveralls documentation](https://github.com/z4r/python-coveralls).
