### ISSUE TITLE
Tag latest not found in repository docker.io

### ISSUE THREAD

**Issue by magwas** [Shippable/support#3392]
The git repo contains a Dockerfile, and push triggers a build on both hub.docker.com and shippable.
The shippable build uses the docker image resulting from the hub.docker.com build.
Before the push there was already a docker image, and it is not required to wait for the new version built.
However it seems that there is a brief time period when docker.io does not provide the image.

A build failing because of that:
https://app.shippable.com/runs/58af51e69168fd0f007d836c/1/console

There was a previous issue about this, but I cannot find it to reopen. It was clear from this that this issue affects multiple builds.
I understand that you view it as Someone Else's Problem, but ultimately it affects the usability of your service. You can optimize the caching of docker images (if you do cache), and perhaps you are in a better position to work out a solution than Random Developer.

See also https://forums.docker.com/t/image-is-missing-for-some-periods-of-time/28850

**Comment by rageshkrishna** [comment]
Hi @magwas. I see what you're saying. As a quick workaround, can you try if adding this to your shippable.yml file helps:

````
build:
  pre_ci:
    - shippable_retry sudo docker pull magwas/pdengine:latest
````

This should retry the docker pull a few times before giving up. I agree that it would be useful for us to do this by default on the pull_image step. We'll get that wired up soon. In the meantime, I hope the trick above is helpful.

**Comment by avinci** [comment]
we are deploying a fix for this in this version so that users dont need to do this themselves.

**Comment by avinci** [comment]
this has been fixed and deployed. Please let us know if you see issues with this again.
