### ISSUE TITLE
Shippable account is FUBAR

### ISSUE THREAD

**Issue by rhenretta** [Shippable/support#3393]
I have been unable to get a build working for a couple days now.  I was getting an error on a setup integrations script saying EOF found looking for matching `''.  After many attempts to fix it, I decided it would be fastest to destroy and recreate my account to start from scratch. 

I can't delete any integrations, it errors out with: 

(Id: 4001) subscriptionIntegrations.destroy failed for id: 5151 returned error: update or delete on table "subscriptionIntegrations" violates foreign key constraint "resources_subscriptionIntegrationId_fkey" on table "resources"
verbose: subscriptionIntegrations|deleteById|callerId:589ddc5ec3a3b40f006e12b2|id: 5151|_deleteById

I can't delete my account, it errors out with:

(Id: 4001) deleteSubscriptionIntegrationById for id: 5151 returned error: subscriptionIntegrations.destroy failed for id: 5151 returned error: update or delete on table "subscriptionIntegrations" violates foreign key constraint "resources_subscriptionIntegrationId_fkey" on table "resources"
verbose: accounts|deleteAccountIntegrationDependencies|callerId:589ddc5ec3a3b40f006e12b2|_deleteSubscriptionIntegrations

I only have a few hours left to get the builds running again so I can present this service to the team

**Comment by rageshkrishna** [comment]
@rhenretta It looks like you have some soft-deleted resources that need to be permanently removed. Please go to the pipelines tab on the subscription you were trying to set up and delete any resources you see there. That should allow you to delete your integrations and start over.

**Comment by rhenretta** [comment]
There is no delete option for them

**Comment by rhenretta** [comment]
Nevermind, I have to delete dependencies first ☺

**Comment by rhenretta** [comment]
I'm seeing the same initial error again after rebuilding everything.  I can do a build (albeit without a push to docker hub) if I remove the docker-hub integration.  However, when I put it back in I get the same error:

  Debug 0s
  Debug logs 0s  
ScriptType:setup_integrations|msg:/tmp/mexec/tmp-script.sh: line 283: unexpected EOF while looking for matching `''

This integration was working last week, I can find no reason for it to start failing.  

Build failing with docker-hub integration:
https://app.shippable.com/runs/58b05e50ddd8e807004222f0/1/console

**Comment by rageshkrishna** [comment]
Can you check if any of your integrations values have special characters (back-ticks, quotes, etc.)? We may be missing something in our bash escaping.

**Comment by rhenretta** [comment]
There it is.  I used a random password, and it had an apostrophe in it

**Comment by rageshkrishna** [comment]
Wow... I'm really sorry you ran in to that. We'll review our escape routines and make sure we handle this correctly. Glad you got your builds running. Do let me know if there's anything else I can help you with.

**Comment by rhenretta** [comment]
Thanks for your help
