### ISSUE TITLE
= character in encrypted resource values

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3395]
Not clear how to pass these through correctly.

In my case I have a password containing the = character: ``XYZ_PASSWORD=q1<...>=<...>``.

Where <...> is a series of other ASCII characters that don't appear to be a problem.

It seems I cannot quote the values. Not if it is being used in ``shippable.resources.yml``. As per the documentation:

http://docs.shippable.com/navigatingUI/subscriptions/settings/#encrypt

For same reason, it seems to be split at the first character, being the q. The q gets dropped. So I get:

```
XYZ_PASSWORD=
1<...>=<...>
```

**Comment by avinci** [comment]
We are splitting on = and hence the issue. We are looking into ways that we can solve this problem. unfortunately there is really no good way to do this without removing the feature of single line encryption string. 

Let me think about what we could do...if you have ideas, happy to try them out.

**Comment by bholzer** [comment]
Am I wrong to think that checking to see if the `=` is enclosed in quotes before splitting on it is a valid solution? Is it not possible to differentiate between:

`SOME_ENV=sH7$=sMlpO` and `SOME_ENV="sH7$=sMlpO"`

**Comment by bholzer** [comment]
Alternatively, since the variable name can not include `=`, can it not be assumed that the first `=` encountered is the one between the variable name and value?

**Comment by brianmay** [comment]
Like I said above, you cannot quote values in ``shippable.resources.yml``. As in the quotes become part of the value too.

I can't comment on your second suggestion, it seems reasonable to me.

**Comment by bholzer** [comment]
Sorry, I completely missed the part about the quotes. 

If variables are isolated and THEN split by `=`, the second approach should work. That said, of course, without any knowledge of how that string is parsed.

**Comment by manishas** [comment]
This has been fixed.
