### ISSUE TITLE
not seeing new Amazon ECR image

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3396]
Hello,

I have a pipeline that does not appear to be working. The following happened:

1. I made a small change to the code and pushed it.
2. The CI run and pushed the image to ECR. I can confirm in Amazon web interface it has the correct version - ``master.12``. It also has the old version ``master.11``.
3. No further steps in the pipeline got executed. Manifest didn't execute. If I click on the image icon ``myro-img`` in the pipelines view, it show only the old version ``master.11``.
4. If I manually start the manifest tasks they will use the old version ``master.11``. At least that is what shows when I look at the trace page.

Problem is I am not sure where to start debugging this or what other information might be useful.

Speculation: Maybe shippable is expecting to receive an event from ECR when the image has changed, but it isn't getting it? Or is it a problem with the runCI command not working for some reason?

Regards

**Comment by a-murphy** [comment]
Assuming I found the right build, it looks like you haven't told the runCI job to update the image.  The "processing version" step shows that the output tag hadn't changed.

To avoid creating new versions of image resources when you don't want them, and to make sure that we get the right tags, we only update the image resources when the `.env` file for that resource contains a new tag.  At some point in your build, you'll have to add the new tag to the `.env` file for the image resource.  You can do that by adding a line like this the `shippable.yml` file after pushing the new image tag:
```YML
 - echo "versionName=your-image-tag" >> $JOB_STATE/your-image-resource-name.env
```

More detailed documentation is available [here](http://docs.shippable.com/tutorials/pipelines/connectingCiPipelines/#using-runci).

**Comment by brianmay** [comment]
Thanks. That would be it.

For some reason it is still unhappy. From: https://app.shippable.com/runs/58b4a6a75b77cc0600780a72/1/console

Looks like everything worked, but the overall status was failure.

Later: Oh, I see the error:

```
genExec|pipelines|__postVersion, Failed to post version for resourceId: undefined 404
```

Which has me puzzled. I write to ``$JOB_STATE/myro-img.env`` and the pipeline image resource is called ``myro-img``. Is there something else I have wrong here?

**Comment by brianmay** [comment]
Ok, I ran the build again, this time it worked. Weird.

https://app.shippable.com/runs/58b4afb2cb79ea05000c1966/1/console

**Comment by a-murphy** [comment]
The account used for webhooks on that project didn't have access to the repository containing the pipelines resources, so couldn't create the new image version.  I've updated the CI project on Shippable to use the owner's token for webhooks, as it usually would, and that account has access to both.  The webhook builds should work now as well as the manual ones.

**Comment by brianmay** [comment]
Thanks!
