### ISSUE TITLE
Filter on usernames in History

### ISSUE THREAD

**Issue by POU-BNO** [Shippable/support#3397]
Hi,

Would it be possible to implement a way to filter on usernames in History for organizations? As of right now, you can only filter in history by **Types**, **Statuses** and **Projects**. We currently have 110 users in our Github organization, and it is a bit awkward to scroll down multiple runs to find a specific users run.

Br.
Jim

**Comment by avinci** [comment]
We are completely revamping our UI and we will add to that queue to make sure this happens.
