### ISSUE TITLE
Feature request: custom integrations

### ISSUE THREAD

**Issue by magnushiie** [Shippable/support#3399]
Integrations for passing credentials down to the builds as predefined environment variables. I propose you add an integration type "Custom" for which you define the environment variables, and that you can bring into a build environment using the shippable.yml as with other integrations.

I know it's possible to bring credentials into the build environment via secure variables, but that's a lot more work (and more obscure) than just bringing in an integration.

**Comment by avinci** [comment]
@magnushiie we have `params` resource for exactly that. 

The way we are looking at it is; An integration for us is credentials to connect to an external resource. It typically owned by an account and it has its challenges when working in a  team especially it has to change often.

Params on the other hand are part of the project and versioned in source code. Hence its easy to manage and change in a team.

Are you asking for any specific values that you would like to put as Custom?

**Comment by magnushiie** [comment]
First, I'm talking about builds, not pipelines. And my request is exactly about the scenario you mentioned integration is for - "credentials to connect to an external resource" (by the build process I might add).

I can bring two examples:
- npm package repository - the base image has `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` in `~/.npmrc`, and therefore I would like to create a custom integration for passing in NPM_TOKEN to all projects (not specify it per-project)
- an infrastructure service built in-house - the builds (not the resulting services built by the builds) of other projects would like to interact with that service

Both are examples very much like your existing integrations (e.g. hub integrations). For NPM, it would of course be great if there was a specific NPM integration, but until then, custom integration would work great. And for the other case there couldn't be a standard integration, but a custom integration would be really helpful.

**Comment by avinci** [comment]
fair enough. This will be done in our next sprint and ship by end of next week.

**Comment by magnushiie** [comment]
Wow, I didn't expect this to pop to the top of your backlog. Thanks! It will be really appreciated.

**Comment by avinci** [comment]
this has been launched into production to allow you to create any list of key values. Please let us know if you face any issues using this.

**Comment by magnushiie** [comment]
Sorry, I can't find this feature, can you provide some pointers?

**Comment by ankul-shippable** [comment]
@magnushiie sorry, Got delayed due to some discussions around this. This is will be available in next release(5.4.1) which we will do next week(Monday).
I will update here once this is live.

**Comment by avinci** [comment]
sorry this was shipped last week. here is the docs link. http://docs.shippable.com/integrations/generic/keyValuePair/
