### ISSUE TITLE
Doesn't clean up ECS task definitions

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3400]
It seems every time a new deploy happens, we get a new ECS task definition, and the old one also remains.

Ideally every new task definition should appear as a new version of the last one, not use a brand new name.

![screen shot 2017-02-28 at 10 35 51 am](https://cloud.githubusercontent.com/assets/112729/23385080/e97aaaa0-fda1-11e6-8a5a-3899307c8081.png)

**Comment by avinci** [comment]
@himanshu0503 we should avoid doing this. This should be linked to task definitions issue we are already working on. There is really no reason to repeat task definitions and use versions instead.

**Comment by avinci** [comment]
We have made a bunch of enhancements to reduce the clutter. We reuse the task definitions as much as possible. Please let us know if you see any further issues.
