### ISSUE TITLE
Setting up postgis for pre_ci

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3403]
Hello,

as in https://app.shippable.com/runs/58b574ab1304cc0500e0868d/1/console

I need a running postgis for Docker imagebuilding (and also further on in ci as well), but am unable to install the required packages. They install ok in ci.

So, am I doing this thing right or how should I get this set up in your opinion?

Yours,

Mikko

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by avinci** [comment]
Are you doing a docker build? if so can you send me your Docker file

**Comment by avinci** [comment]
ahh i see what you are doing. `pre_ci` is used to prep anything before you run you CI. If you want the CI container to be updated, you need do it through building a docker file and doing whatever you need to do. I see that you are trying to install postgres 9.5. We are launching new images which has this pre-installed end of this this week. Is that what you are trying to do?

I am assuming postgis is typo for postgres.

**Comment by avinci** [comment]
this sample repo might help you to do this...
https://github.com/shippableSamples/ci-with-custom-ubuntu1604-build-image

**Comment by mikkopori** [comment]
Nope, not a typo http://docs.shippable.com/ci/services/postgreSQL/#using-postgis :)

**Comment by avinci** [comment]
sorry my bad. So why are trying to do this in `build_pre_ci1? can you try and do it in `ci`?

**Comment by mikkopori** [comment]
It works in ci but the building of the Docker image needs the postgis-db and as I gather the building of the image needs to happen at pre_ci..

**Comment by avinci** [comment]
`pre_ci` is used to create a docker image if you would like to. It typically is used in prepping of the environment. Anything that runs there will not be carried over to CI unless you are building a docker image. 

Based on looking at your build, you are trying to install directly onto the component that is trying to boot your CI image. That will not work. 

The easiest way is to use base python image for your build and just put that apt-get install command into CI section before anything and It should work. 

Another way to do it is put the install command inside a Docker file and you can do a docker build of that Dockerfile in the pre_ci. Then boot this image using `pre_ci_boot` and then you will have postgis in your CI image.

The sample I gave above does a nodejs custom docker image build. You can change it to python and make the same thing work. 
https://github.com/shippableSamples/ci-with-custom-ubuntu1604-build-image

Let me know if this helps...

**Comment by mikkopori** [comment]
Okay, as far as I understand the first option does not work for me as the building of the Docker in pre_cli requires the postgis db.

But you are suggesting in building the image in ci? I'll give it a try..

**Comment by mikkopori** [comment]
Apparently you do not support python3?

"The executable /usr/bin/python3.6 (from --python=/usr/bin/python3.6) does not exist"

**Comment by avinci** [comment]
those images are launching on Friday. But you can pull `drydock/u16pyt:master` in your FROM clause in Dockerfile to test it out. They will be live after we launch and can automatically picked.

**Comment by mikkopori** [comment]
mm, why are you running trusty as default?

**Comment by mikkopori** [comment]
The build is taking over 21 minutes, hey! :D

**Comment by mikkopori** [comment]
Ok, saw you guys had some trouble :)

Did you mean: https://hub.docker.com/r/drydock/u16pytall/ ? trying that, takes some time to pull..

**Comment by mikkopori** [comment]
Ok, now proceeding with that image u16pytall, but the pulling seems to take 20+ minutes everytime..

**Comment by mikkopori** [comment]
Ok, now ran into:

"psql -c 'create role shippable with superuser;' -U postgres 0s  
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?"

in: https://app.shippable.com/runs/58b6810e5b77cc0600799132/1/console

Although I have:

services:
  - postgres

Any idea what I'm failing to do to start the pg?

**Comment by rageshkrishna** [comment]
The image you're using is still pre-release so we don't automatically start services on it even if you add it to your YML. Please try adding the command `shippable_service posgtres start` as the first thing in the `ci` section in your YML.

**Comment by mikkopori** [comment]
shippable_service posgtres start 0s  
Unknown service: posgtres

this happened...

**Comment by rageshkrishna** [comment]
I'm really sorry about this... I made a typo. It should have been `shippable_service postgres start`.

**Comment by mikkopori** [comment]
okay :D should have spotted myself! Trying again.

**Comment by mikkopori** [comment]
Okay, moving forward, but now I'm running into:

 psql -U postgres -c "create extension postgis" 0s  
ERROR:  could not open extension control file "/usr/share/postgresql/9.6/extension/postgis.control": No such file or directory

So, problems with postgis-support? Saw some cases about that earlier..

**Comment by mikkopori** [comment]
Maybe the problem is in versions? 9.5 vs. 9.6?

**Comment by avinci** [comment]
@rageshkrishna can we get postgis installed on our images that we are launching? It might make this easy for @mikkopori

**Comment by mikkopori** [comment]
moved to installing 9.6 on that shippable image. Also installing postgis, but seem not to get any response on that, so it might not be there or might not install..?

Take a look: https://app.shippable.com/runs/58b7c713ddd8e807004769db/1/console

**Comment by avinci** [comment]
@mikkopori we are adding it ourselves. So this won't an issue for you. THis will launch monday. @rageshkrishna we should update the docs on images

**Comment by mikkopori** [comment]
Okay, sounds good, thank you.

Will it be available in in Dockerhub before Monday? :)

**Comment by mikkopori** [comment]
Hello, launched yet? :)

**Comment by rageshkrishna** [comment]
Hi @mikkopori, the release is a little delayed due to issues unrelated to the images themselves. What you see at `drydock/u16pytall:master` right now is the release candidate and will, in all likelihood, be exactly what will be released. You can use that tag if you need it right away. I expect the official launch to be a little later this week. I hope this helps.

**Comment by mikkopori** [comment]
Tnx, I'll give it a spin and report what I find :)

**Comment by mikkopori** [comment]
Postgis is working now, but having trouble opening access from the docker image to the shippable docker, it accepts edits to conf files ok without reload/restart? (to stop a shippable service seems to be a permanent operation..)

Any news on the release? These 20+ min. pulls on almost every run are really annoying when trying to debug..

**Comment by rageshkrishna** [comment]
The images will be released over the weekend. I'm not sure I understood the problem with "opening access from docker image to the shippable docker". Can you please elaborate on that?

`pg_ctl reload` should work for applying config file updates without having to restart the service. Is that not working for you?

**Comment by mikkopori** [comment]
Now I'm trying out an approach presented here: https://github.com/Shippable/support/issues/1092

Have not tried `pg_ctl reload` yet.

I'm building a docker image in CI and that build process runs tests which requires a db. So I'm trying to open access from that image process to the postgres running in shippable image.

**Comment by rageshkrishna** [comment]
Oh, so you want a container that you launch to be able to talk to the postgres instance running in the container that we launch? You'll need to set up some port forwarding to make this work.

I think something like this should do the trick:

1. Add `options: -p 5432:5432` to your `pre_ci_boot` section. This will get port 5432 from the host routed to 5432 in your shippable container.
1. From the container that is running your tests, try using 172.17.42.1 as your postgres host.

Docker link should also work, and that is probably a cleaner solution, but I can't remember the exact arguments off the top of my head.

**Comment by mikkopori** [comment]
Tnx, tried that and it failed:

django.db.utils.OperationalError: could not connect to server: No route to host
	Is the server running on host "172.17.42.1" and accepting
	TCP/IP connections on port 5432?

in

https://app.shippable.com/runs/58c29f78ba295305001a55a7/1/console

You do not think we specifically need alter the pg-conf to allow connections connections?

**Comment by rageshkrishna** [comment]
You're right -- I forgot that the default config only allows connections from localhost to go through. This seems like an interesting problem to solve. I will try to put together a sample project for this over the weekend.

**Comment by mikkopori** [comment]
Ok, thank you, looking forward to hearing from you :)

**Comment by mikkopori** [comment]
Oh, and I've setup this thing locally ok using this guide: http://stackoverflow.com/questions/31249112/allow-docker-container-to-connect-to-a-local-host-postgres-database, if it helps :)

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image for cpp.

**Comment by mikkopori** [comment]
Thank you, set that up and running now.

There is something strange happening in the gui, I seem not to be able to click to the running (or historical) jobs details?

Also I was still waiting for a solution for the access from @rageshkrishna so maybe let's not close this case just yet :)

**Comment by mikkopori** [comment]
Ahh, I had to log out and in again to see the runs!

**Comment by mikkopori** [comment]
@rageshkrishna any update on this problem? :)

**Comment by rageshkrishna** [comment]
I _just_ got it working :)

Check out https://github.com/rageshkrishna/postgres_remote for my test project and here's the build that succeeded with it:

https://app.shippable.com/github/rageshkrishna/postgres_remote/runs/8/1/console

**Comment by mikkopori** [comment]
Tnx! Ran into this:

```
virtualenv -p /usr/bin/python3.6 /root/venv/3.6 1s  
The path /usr/bin/python3.6 (from --python=/usr/bin/python3.6) does not exist

```

So, python 3.6 is not supported?

**Comment by rageshkrishna** [comment]
Sorry, I didn't realize you needed python 3.6. It's available in `drydock/u16pytall:v5.3.2`. Please use that image instead.

**Comment by mikkopori** [comment]
Should have spotted that myself, tnx :)

**Comment by mikkopori** [comment]
Works great! Builds are finally passing :)

Took some time because of technical debt piling up durint the time builds where failing..

**Comment by mikkopori** [comment]
@rageshkrishna how long do I have to keep using the image from drydock and when is this available in the default-version? :)

**Comment by rageshkrishna** [comment]
@mikkopori The drydock images are indeed our official images.

If you'd like to continue using the 5.3.2 tags, please go to https://app.shippable.com/subs/github/mikkopori/settings/options and change the Machine Images setting to v5.3.2. Once you do this, your builds will start running on the 5.3.2 machines which have all the 5.3.2 drydock images already pulled locally.

Having said that, just a few hours ago we released the 5.4.1 images, too. There are some improvements and bug fixes, but nothing that affects the python images. If you can, I'd suggest just moving to 5.4.1 instead of 5.3.2. Of course, pick 5.4.1 for your machine image so you don't have to pull the drydock images on each build.

**Comment by mikkopori** [comment]
Thank you for the reply. No need to use 5.3.2 specifically, latest should be safest for me.

Changed the settings to stable https://app.shippable.com/subs/github/mikkopori/settings/options

But how do I do this bridging:

    image_name: drydock/u16pytall
    image_tag: v5.3.2
    options: "-p 5432:5432 --net=bridge"
?

**Comment by rageshkrishna** [comment]
Don't use `stable`. That's an unfortunate choice of name that we made a long time ago. At the moment, Stable and Unstable are actually deprecated images. We will update the naming to reflect this.

Please pick the 5.4.1 image and use that tag in your yml file, too.

The docker options should work exactly as they did before. We have not changed anything about the YML definitions.

**Comment by mikkopori** [comment]
Ok :)

**Comment by mikkopori** [comment]
Tnx, seems to work ok :)
