### ISSUE TITLE
Error with git_sync

### ISSUE THREAD

**Issue by mariale425** [Shippable/support#3406]
Hello!

I have a problem with a build of cucumber:

https://www.evernote.com/l/AiTc5LTIB49FUp4R34sZHewBIf2QCLtZRaw

https://app.shippable.com/runs/58b5a5b61304cc0500e0af8f/1/console

I had created a branch but now it was deleted. This branch was not merge. It was just push to the repository.

**Comment by stephanielingwood** [comment]
Hi @mariale425 

So it looks like the branch you triggered the build for, `merge_master`, no longer exists in your repository. Is this indeed the case? If so, we aren't able to run a build for a branch that no longer exists, as we first check out the branch, and then we reset to the commit.
