### ISSUE TITLE
Buy minions on demand

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3411]
### Description of your issue:
I was looking at the pricing plans and was wondering if you have though of providing an on demand minion purchasing using and API.

Currenlty we have a flux of build time some weeks and then this drops.

It would be great if we could buy a base amount of minions per month, but also have the ability to purchase some on demand when influx of build time is required.

**Comment by avinci** [comment]
this is something we dont support at this time. You are asking overage or burst mode. Its and interesting concept, let me noodle around and get back to you.

**Comment by asanchezgiraldo** [comment]
@avinci not sure how this could work. 

overage has the advantage of

**Comment by avinci** [comment]
I thought about it and at this point, unless we move to an hourly billing mode, its tough to implement it. This required changing the billing system completely and its a big undertaking. So at this time we will have to punt this request as we are focused on adding features to the product.
