### ISSUE TITLE
Git repos not visible

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3412]
I go to my dashboard page, https://app.shippable.com/accounts/57f458c4b48edb0e003928fb/dashboard

and no repos appear?

I have shippable pipelines, but I can't see them.

I go into integrations and I see everything is normal there, but I can't see pipelines or build status, etc.

**Comment by a-murphy** [comment]
It looks like we got a 502 from GitHub last time your account was synchronized.  Could you try re-synchronizing your account?  (Click on the gear in the top right corner on Shippable and then the "Sync" button.)

**Comment by gitglacier** [comment]
This fixed it, thanks!
