### ISSUE TITLE
Maven install triggered before the before_scripts

### ISSUE THREAD

**Issue by bakersemail** [Shippable/support#3414]
Maven projects appear to automatically have mvn install -DskipTests added and run on them before the scripts are run. If this mvn install has to be here, can it be made to be -B (batch) so the download progress indicator doesn't flood the logs with download progression output.

Also, if unfortunately the maven build relies on scripts in the before_script, the build will fail.

My project is  bdmqld / bdm-queensland for reference.

**Comment by rageshkrishna** [comment]
It sounds to me like you may be using the YML format that we support for compatibility with travis.yml. With that format, we do inject default commands (just like Travis). You should not see this happening if you use the shippable.yml format that is documented at http://docs.shippable.com/ci/shippableyml/

Using the new format gives you complete control over exactly what runs when. I hope this helps.

**Comment by rageshkrishna** [comment]
@bakersemail Were you able to get this to work as you expected it to? Let me know if you need any more help.
