### ISSUE TITLE
Browser title (_r.title) for subscription, projects, runs is never updated

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#3415]
As a user of a large number of projects on Shippable, when using multiple tabs, or wanting to bookmark specific jobs, the browser title is not updated to reflect where I am.

The page title is set as:

    <title ng-cloak>{{_r.title}}</title>

but `_r.title` is not updated for the most used pages, and instead is either "Subscription - Shippable" or "Shippable | Hosted Continuous Integration Service".

The most useful solution would be that is that for runs within a given project, `_r.title` would be set to `job.subscriptionOrgName + '/' + job.projectName`

**Comment by jatindogra** [comment]
Hi @nealeu

We have updated the browser titles. The changes will be reflected in next release.
Thanks.

**Comment by nealeu** [comment]
Yay! 

Thanks. That'll make my multi-tab life easier

**Comment by avinci** [comment]
this has been released to prod

**Comment by nealeu** [comment]
Excellent. I've checked the key areas where it impacted me and it looks spot on.

Many thanks. You've made a number of the team here happier :)
