### ISSUE TITLE
Stalled Run

### ISSUE THREAD

**Issue by bantonj** [Shippable/support#3416]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- https://app.shippable.com/runs/58b9abfb4d9b81050056bbc6/1/console
- Looks like it's stuck at this command `export DISPLAY=:99; grunt e2eLocal`

**Comment by stephanielingwood** [comment]
Hi @bantonj,

Looked at your build, and yes, it looks like one of tasks in `grunt e2eLocal` is perhaps waiting for input. Or, you may have a test that is waiting for a response and not getting any.

Either way, you have a couple choices: you can cancel the build if you're tired of waiting for it, or it will time out.

Hope this helps. Let us know if you have any other questions.
