### ISSUE TITLE
How to transfer source code from CI to CD

### ISSUE THREAD

**Issue by srinivasanramaraju** [Shippable/support#3417]
### Description of your issue:
Hi,
My CI runs on the CiRepo input, I want to use the same source code for my CD. I am not sure how to  pass the same source code to the my next stage (ie., custom runSh job) on which my CI ran. I tried with gitRepo as input resource for my custom job in the pipeline. But, when I do multiple commits my custom job runs on the latest commit not on the commit which my CI has passed. ( eg : commit -1( CI passed) , commit -2 (still CI running). In this case, my CD picks up commit-2 and starts deploying. Ideally, I want my CD to pick up commit - 1 code and deploy).

PIPELINE:  CI - > custom runsh Job

I'm wondering if could tar my source code as post_ci job and push it to OUT/ directory. So, I can access it as my IN/ in my next stage of my deployment. But, I couldn't find a good example on how to do it. It would be great, if you could suggest me a good way of doing this or help me out how to push my tar file as OUT/

**Comment by stephanielingwood** [comment]
Hi @srinivasanramaraju ,

Best place to put your tar file is in the STATE directory of the CI job. That folder will persist between jobs and will be available in, say, your runSh job. 

Your shippable.yml would then have this in it: 
```
 - tar -C $SHIPPABLE_BUILD_DIR -czvf $JOB_STATE/my-tar-file.tar.gz .
```

This will tar the repo (SHIPPABLE_BUILD_DIR) and place that tar into the state (JOB_STATE) directory of the `runCI` job. 

Then, add the `runCI` job associated with that `ciRepo` as an IN to your runSh job. You can now access that tar file because you have access to that `runCI` job's STATE directory. 

For example, I have a `sample_python` CI project. The `ciJob` is called `sample_python_runCI`. So, the STATE directory for this job is SAMPLE_PYTHON_RUNCI_STATE. If I do this in my `runSh` job...
```
- script: ls -la $SAMPLE_PYTHON_RUNCI_STATE
```

I see `my-tar-file.tar.gz` listed.

**Comment by srinivasanramaraju** [comment]
Hey @stephanielingwood,
Thank you for getting back. It's the same stuff i'm trying.   but, hit a new prob in that. It's throwing me new error  in saving job files Error 413
![screen shot 2017-03-03 at 5 49 30 pm](https://cloud.githubusercontent.com/assets/9116146/23574933/c78e9060-0039-11e7-983a-3b219f6f7453.png)

Not sure how to deal this

**Comment by stephanielingwood** [comment]
Hmm. Error 413 probably means the file is too large to save in the STATE directory. What about saving the sha into a file in STATE, and then reading that in your runSH job? You could then reset the cloned git repo back to that sha. 

Just tried it out with this setup:

Create a gitRepo resource that references your repo (yes, the repo you use to set up your CD - aka your syncRepo - can also be used for a gitRepo resource). This will give you a way to access the files of that repo.

In the `shippable.yml`, add something like this:
```
- echo "COMMIT_SHA=$COMMIT" > $JOB_STATE/commit.env
```

In your runSh job, add the gitRepo resource as an IN to that job., like so: 
```
      - IN: yourGitRepoResourceName
        switch: off
```
The "switch: off" bit will keep your `runSh` job from triggering twice on a commit to that repo - e.g. it will only trigger when the CI build is done. You should now have both the `runCI` and the `gitRepo` inputs as INs.

Add something like this to the TASK section of your `runSh` job:
```
        - script: source $SAMPLE_PYTHON_RUNCI_STATE/commit.env
        - script: cd $SAMPLEPYTHON_STATE
        - script: git reset --hard $COMMIT_SHA
```
 
And you should now be in the root directory of your repo, with your files at the commit that ran in the CI job. 

FWIW, if you're using multiple branches (e.g. your `gitRepo` is specifying a given branch that doesn't match the one you used for the build), you will also need to save the CI branch to your env file. The branch is available as $BRANCH. Then, in your `runSh` job, do a `git checkout` on that branch before you reset.

**Comment by srinivasanramaraju** [comment]
Awesome! great. This seems to be a good idea. I will try that and update.

**Comment by srinivasanramaraju** [comment]
It Worked! Thank you for your timely help. I really appreciate it.

**Comment by srinivasanramaraju** [comment]
Hey, could you tell me what is the maximum size that could be saved in the STATE Directory ?

**Comment by stephanielingwood** [comment]
Hey @srinivasanramaraju  - glad you got it working. As for the limit, it's currently 1mb.
