### ISSUE TITLE
Import Errors trying to build python project in Shippable

### ISSUE THREAD

**Issue by arunxarun** [Shippable/support#3418]
In my shippable.yml file I specify the following:

language: python
python:
  - 2.7
env:
  - env1=dev
  - #env2=bar
build:
  pre_ci:
    - pip install -r requirements.txt
  ci:
    - python -m pytest test_*.py

This builds locally, and I've validated the build by re-initializing virtualenv and re-running the pip install -r requirements.txt. 

When I try to build with Shippable,  I get the following errors: 
____________________ ERROR collecting test_configurator.py _____________________
test_configurator.py:7: in <module>
    from configurator import Configurator
configurator.py:1: in <module>
    import yaml
E   ImportError: No module named yaml
_______________________ ERROR collecting test_sender.py ________________________
test_sender.py:9: in <module>
    from google.cloud import pubsub
E   ImportError: No module named google.cloud

both of these packages are installed, I've validated they are installed in the pre_ci step. 
Not sure what is different between my virtualenv and the one on shippables container. 

link to build:  https://app.shippable.com/runs/58ba4fb665094f0500a9d783/1/console

**Comment by rageshkrishna** [comment]
`pre_ci` runs in a separate container. It's typically used to create a Docker image with which you want to run your CI.

Just move that step to `ci` and your builds should run fine.

**Comment by manishas** [comment]
Closing this issue. @arunxarun let us know if the suggestion above doesn't work for you.
