### ISSUE TITLE
Project Owner permission transition

### ISSUE THREAD

**Issue by Neal910** [Shippable/support#3422]
How to transfer Project Owner permission to another team member or grant the permission?

Currently, we are not sure how a person in my team got the permission to add Hook in a project to enable runCI in pipeline. How this person can grant permission to others?

Thanks,

Neal

**Comment by a-murphy** [comment]
Our permissions match those for the repository on the source provider (GitHub, Bitbucket, or GitLab).  Anyone who is an "admin" (a mapping for each source provider is available [here](http://docs.shippable.com/ci/permissions/#user-repository-permissions-mapping-to-shippable-roles)) will have permission to click the "hook" button in project settings.  If the permissions don't appear to match on Shippable, clicking the little gear in the top right corner and then the green "sync" button will synchronize the logged-in account's permissions on Shippable with the source provider.

**Comment by Neal910** [comment]
@a-murphy  Thank you very much.
