### ISSUE TITLE
Taking too long to build

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3423]
https://app.shippable.com/subscriptions/57f4596bb60e2a0f001627f3/pipelines

Please help me understand what is going on here, the pending number goes up and down, up and down. Not reasonable for a production environment.

Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:2
Desired count: 2, Running count:0, Pending count:1
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:2
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:2
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:2
Desired count: 2, Running count:0, Pending count:1
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:2
Desired count: 2, Running count:0, Pending count:2
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:2
Desired count: 2, Running count:0, Pending count:1
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:2
Desired count: 2, Running count:0, Pending count:1
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0
Desired count: 2, Running count:0, Pending count:0

**Comment by stephanielingwood** [comment]
Hi @gitglacier,

Sorry to hear you're having trouble with your AWS deployment. My best guess, looking at those messages, is that your containers are exiting for some reason and the service keeps trying to bring them back up. As to why they're exiting...well...unfortunately we don't have visibility into that. You might want to ssh into those instances and take a look at the logs of the failing containers. Perhaps it's erroring on start, or the container is finishing its work and exiting (containers won't stay alive unless they have something to do).

**Comment by gitglacier** [comment]
Do you ever issue a mkdir (mountpointname) in your API implementation? Can you please change that to a mkdir -p (mountpointname)?

I am getting this error from AWS EC2 (and it's a recent error, so maybe there was a recent change on your side?)

```
CannotStartContainerError: API error (500): mkdir /nffs_data: file exists
```

These are the relevant parts of our docker-compose.xml:
```
        volumes:
            - /nffs_data:/nffs_data
```

We do not reference nffs_data anywhere else in our docker code. We do reference it in our user data (AWS startup code), but it is mkdir -p there. (Which should not give an error if it's an existing directory.)

Thanks.

**Comment by gitglacier** [comment]
Unsure what fixed it unfortunately. Did a reboot of all instances and now the problem seems to have gone away.
