### ISSUE TITLE
Python 3.6 missing

### ISSUE THREAD

**Issue by Nzbuu** [Shippable/support#3425]
Python 3.6 does not appear to be available despite having been released in Dec-2016

https://app.shippable.com/runs/58c028dcba2953050017fb9f/1/console

**Comment by rageshkrishna** [comment]
Python 3.6 will be available in the new images that we are releasing this week. I'll update this issue as soon as they are available.

**Comment by avinci** [comment]
we released new version of images just now. Please set your subscription to use `v5.3.2` version of system images on your subscription settings page to get the latest image.
