### ISSUE TITLE
TRAVIS environment variable should be false

### ISSUE THREAD

**Issue by Nzbuu** [Shippable/support#3426]
According to http://docs.shippable.com/ci/advancedOptions/environmentVariables/, the default setting is:

```
TRAVIS=true
```

But Shippable is not Travis, so the correct value would be `false`.

The correct environment variable for scripting should be the `CI` one.

**Comment by manishas** [comment]
@Nzbuu this is for compatibility with Travis yml format. We have some customers who start using Shippable with .travis.yml and they need the environment to be like Travis. Please note though that this isn't the recommended approach.
