### ISSUE TITLE
Test works locally, but not on shippable

### ISSUE THREAD

**Issue by NiclasHedam** [Shippable/support#3430]
Hi!

I'm running on ants tests, but it does not work on Shippable.
The tests target seems to be empty on shippable, but not locally.

On shippable the build result looks like this
```
Buildfile: /root/src/github.com/BFST/BFST/build.xml

clean:

compile:
    [mkdir] Created dir: /root/src/github.com/BFST/BFST/out/main
    [javac] Compiling 29 source files to /root/src/github.com/BFST/BFST/out/main
     [copy] Copying 2 files to /root/src/github.com/BFST/BFST/out/main

test-compile:
    [mkdir] Created dir: /root/src/github.com/BFST/BFST/out/test

test:

coverage:
[jacoco:report] Loading execution data file /root/src/github.com/BFST/BFST/out/jacoco.exec

BUILD FAILED
/root/src/github.com/BFST/BFST/build.xml:58: Unable to read execution data file /root/src/github.com/BFST/BFST/out/jacoco.exec

Total time: 13 seconds
```

Locally, it looks like this
```
Buildfile: /xxxx/BFST/build.xml

clean:
   [delete] Deleting directory /xxxx/BFST/out

compile:
    [mkdir] Created dir: /xxxx/BFST/out/main
    [javac] Compiling 29 source files to /xxxx/BFST/out/main
     [copy] Copying 2 files to /xxxx/BFST/out/main

test-compile:
    [mkdir] Created dir: /xxxx/BFST/out/test
    [javac] Compiling 1 source file to /xxxx/BFST/out/test

test:
    [junit] objc[2768]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/bin/java (0x103eca4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x103f944e0). One of the two will be used. Which one is undefined.
    [junit] Running Tests
    [junit] Testsuite: Tests
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.541 sec
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.541 sec
    [junit]
    [junit] Testcase: testCanBoot took 2.519 sec
    [junit] Testcase: testUnitTests took 0 sec

coverage:
[jacoco:report] Loading execution data file /xxxx/BFST/out/jacoco.exec
[jacoco:report] Writing bundle 'JaCoco' with 35 classes
[jacoco:report] To enable source code annotation class files for bundle 'JaCoco' have to be compiled with debug information.

BUILD SUCCESSFUL
Total time: 11 seconds
```

`<project name="BFST" default="dist" basedir="." xmlns:jacoco="antlib:org.jacoco.ant">
    <property name="main.build.dir" value="out/main"/>
    <property name="main.src.dir" value="src"/>
    <property name="test.build.dir" value="out/test"/>
    <property name="test.src.dir" value="Tests"/>
    <property name="resources" value="Resources"/>
    <property name="dist" location="out"/>

    <taskdef uri="antlib:org.jacoco.ant" resource="org/jacoco/ant/antlib.xml">
        <classpath path="lib/jacocoant.jar"/>
    </taskdef>

    <path id="classpath.test">
        <pathelement location="lib/junit-4.12.jar"/>
        <pathelement location="lib/hamcrest-core-1.3.jar"/>
        <pathelement location="${main.build.dir}"/>
    </path>

    <target name="compile" depends="clean">
        <mkdir dir="${main.build.dir}"/>
        <javac srcdir="${main.src.dir}" destdir="${main.build.dir}" includeantruntime="false"/>
        <copy todir="${main.build.dir}" overwrite="true">
            <fileset dir="${resources}"/>
        </copy>
    </target>

    <target name="test-compile" depends="compile">
        <mkdir dir="${test.build.dir}"/>
        <javac srcdir="${test.src.dir}" destdir="${test.build.dir}" includeantruntime="false">
            <classpath refid="classpath.test"/>
        </javac>
    </target>

    <target name="dist" depends="compile">
        <jar destfile="${dist}/BFST.jar" basedir="${main.build.dir}">
            <manifest>
                <attribute name="Main-Class" value="Main"/>
            </manifest>
        </jar>
    </target>

    <target name="test" depends="test-compile">
        <jacoco:agent property="agentvmparam" destfile="${dist}/jacoco.exec"/>
        <junit printsummary="on" haltonfailure="yes" fork="true">
            <jvmarg value="${agentvmparam}"/>
            <classpath>
                <path refid="classpath.test"/>
                <pathelement location="${test.build.dir}"/>
            </classpath>
            <formatter type="plain" usefile="false" />
            <batchtest fork="true">
                <fileset dir="${test.src.dir}" includes="**/*.java" />
            </batchtest>
        </junit>
    </target>

    <target name="coverage" depends="test">
        <jacoco:report>
            <executiondata>
                <file file="${dist}/jacoco.exec"/>
            </executiondata>
            
            <structure name="JaCoco">
                <classfiles>
                    <fileset dir="${dist}"/>
                </classfiles>
                <sourcefiles encoding="UTF-8">
                    <fileset dir="${main.src.dir}"/>
                </sourcefiles>
            </structure>
            <xml destfile="${dist}/jacoco.xml"/>
        </jacoco:report>
    </target>
    <target name="clean"
            description="clean up">
        
        <delete dir="out"></delete>
    </target>
</project>`

**Comment by rageshkrishna** [comment]
Can you try running ant in verbose mode? It might tell us why it's not running the javac step in the test-compile task.

**Comment by NiclasHedam** [comment]
```
test-compile:
    [mkdir] Created dir: /root/src/github.com/BFST/BFST/out/test
    [javac] /root/src/github.com/BFST/BFST/Tests/testRoads.osm skipped - don't know how to handle it

test:
[antlib:org.jacoco.ant] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
    [junit] Starting test thread 0
    [junit] Ending test thread 0
```

**Comment by NiclasHedam** [comment]
I tried moving the OSM file out of the tests dir, which did not solve the issue.

**Comment by NiclasHedam** [comment]
It was due to case sensitivity.

**Comment by NiclasHedam** [comment]
Actually, one more question about this tests. The test coverage is successfully uploaded to shippable, but the Sequence coverage is 0.00% and the coverage badge is "Unknown".
The branch coverage is about 57%, so why isn't this value shown?

[![Coverage Badge](https://api.shippable.com/projects/58bd4a7dedea8405002fd156/coverageBadge?branch=develop)](https://app.shippable.com/github.itu.dk/BFST/BFST)

**Comment by scriptnull** [comment]
Hi @NiclasHedam,

Currently Shippable uses the sequence coverage value as default in the badges. So, if the sequence coverage value is 0.00%, then the badge will show "unknown".

I am opening an internal feature request ticket, which will deal with having separate coverage badges for sequence and branch coverage.

**Comment by NiclasHedam** [comment]
Thank you very much. It makes no sense for me though that the branch coverage is 57% and the sequence coverage is 0%. Shouldn't they be somewhat near each other?

Whenever there are at least one test, I would argue that it is impossible to have a coverage of 0% in any metric.

**Comment by scriptnull** [comment]
Yes ! I was also wondering about those values.

Could you provide the build link, that has the above mentioned coverage values ? So that we could take a look at it and see if something is going wrong.

**Comment by NiclasHedam** [comment]
https://app.shippable.com/github.itu.dk/BFST/BFST/runs/120/1/coverage

**Comment by scriptnull** [comment]
@NiclasHedam We are using `LINE` counter information in jacoco.xml file to calculate sequence coverage value. Currently, this value seem to be missing in your reports.

[Jacoco ant page suggests](http://www.eclemma.org/jacoco/trunk/doc/ant.html) the following, in order to get the line coverage information.

> If you want to have line number information included in the coverage reports or you want source code highlighting the class files of the test target must be compiled with debug information.

So, could you please try adding `debug="true"` in your test target and check ? 

```xml
<target name="test-compile" depends="compile">
    <mkdir dir="${test.build.dir}"/>
    <javac srcdir="${test.src.dir}" destdir="${test.build.dir}" debug="true" includeantruntime="false">
        <classpath refid="classpath.test"/>
    </javac>
</target>
```

**Comment by NiclasHedam** [comment]
Unfortunately I was unaware of the monthly build limit for private repos, so I'm unable to build and test any further.

**Comment by avinci** [comment]
did you get a chance to test this? if you temporarily need the limits removed to resolve this, I am happy o do so...

**Comment by avinci** [comment]
closing this due to lack of response....please re-open if otherwise.
