### ISSUE TITLE
Missing bundler

### ISSUE THREAD

**Issue by Antronin** [Shippable/support#3431]
Build failes because it cannot find bundler, although the setup seems to install it.
I'm using the default image:
```
Pulling from drydock/u14ruball
Digest: sha256:c065a12ccbc28fbda34981b792e3659f4d023a48183b82b7f20e2fd504c9e075
Status: Image is up to date for drydock/u14ruball:prod
.
.
.
gem install bundler --no-ri --no-rdoc
Successfully installed bundler-1.14.6
1 gem installed

bundle --version
Bundler version 1.14.6

ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

gem --version
2.4.8
.
.
.
bundle package --all
/root/467a668c-df7d-4ac9-a83e-b2589db9a388.sh: line 58: bundle: command not found
```
- Scripts called from the yml:
```
 ci:
    - shippable_retry apt-get update && apt-get install -y libpq-dev imagemagick libmagickwand-dev libmysqlclient-dev phantomjs
    - mysql -uroot -e "GRANT ALL PRIVILEGES ON $TEST_DB_NAME.* TO $TEST_DB_USERNAME@$TEST_DB_HOST"
    - bundle package --all
    - shippable_retry bundle install
    - ruby -v
    - .openshift/action_hooks/deploy
    - mkdir -p shippable/codecoverage
    - mkdir -p shippable/testresults
    - bundle exec rake db:migrate:reset
    - bundle exec rake db:seed
    - bundle exec rake
```

**Comment by a-murphy** [comment]
I haven't been able to get any errors with the image and Ruby version above and the first few lines of you CI section.  Is there anything unusual about your project?  For example, a Gemfile that's not typical or something else that's also named `bundle`.

**Comment by a-murphy** [comment]
There is another possibility.  If your `.ruby-gemset` or `.rvmrc` is specifying a different gemset, the `git_sync` step will switch gemsets.  So, `bundler` is installed and available before `git_sync` and not in `ci`.  Could you check your `.ruby-gemset` and `.rvmrc` files, if you have them?

**Comment by manishas** [comment]
@Antronin did the suggestions above help? Please let us know.

**Comment by Antronin** [comment]
Hi,

Sorry for teh delay. Yes it helped. It was a problem with the `.ruby-gemset` I specified another gemset. I added `gem install bundler` to my `shippable.yml` just before `shippable_retry bundle install` and now it works.
I would suggest add this as an automatic step, as I cannot imagine a use case where you don't need bundler in your custom gemset.
