### ISSUE TITLE
How to debug docker integration errors?

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3432]
Hello,

trying to push image to docker hub but failing with 
"denied: requested access to the resource is denied"
in
https://app.shippable.com/github/mikkopori/enterlot/runs/327/1/console

Also, unable to delete the docker integration to create a new one:

"Deleting from subscriptions fails:
"(Id: 4001) subscriptionIntegrations.destroy failed for id: 5297 returned error: update or delete on table "subscriptionIntegrations" violates foreign key constraint "resources_subscriptionIntegrationId_fkey" on table "resources"
verbose: subscriptionIntegrations|deleteById|callerId:589ddbd754b6ed0f002586d4|id: 5297|_deleteById""

Deleting from account (naturally) integrations fails:
"Confirm Delete Account Integration
Please delete following dependencies before deleting docker 

Dependencies
1 dependency
subscription Integrations
mikkopori - docker"

So, how move forward in fixing this? Thank you.

**Comment by kanthchandra** [comment]
It looks like you have added a resource with name `otapark-img` which is using this subscription integration. If you delete that resource you should be able to delete the subscriptionIntegration.

**Comment by mikkopori** [comment]
Tnx, where did I add that, where can I remove it?

**Comment by kanthchandra** [comment]
That would be there in your shippable.resources.yml . If you go to your pipelines page you can see those resources at the bottom.

**Comment by mikkopori** [comment]
Right, I can see them in the resources. How do I delete those? No shippable.resources.yml atm in my git, might have tried to use that some time back. So, was something left behind?

**Comment by kanthchandra** [comment]
It was soft deleted when you remove the shippable.resources.yml. So Please go to the pipelines page, right click on those resources you will see an option to remove them.

**Comment by mikkopori** [comment]
Thank, got those cleared. Redid the integration, but still facing:

"denied: requested access to the resource is denied"

How should I continue debugging?

**Comment by kanthchandra** [comment]
Hi @mikkopori would you mind sharing your yml file?? My guess is you probably haven't added that integration in your yml. Documentation for that is available here http://docs.shippable.com/ci/shippableyml/#hub .

**Comment by mikkopori** [comment]
post_ci:
    - docker push mikkopori/otapark:shippable
  on_success:
  on_failure:
  cache:
  cache_dir_list:
  push:
integrations:
  hub:
    - integrationName: docker
      type: docker
      branches:
        only:
          - shippable
  deploy:
    - integrationName: aws
      type: aws
      target: eb_docker
      application_name: "otapark"
      env_name: "otapark-staging"
      bucket_name: "elasticbeanstalk-eu-west-1-414075299243"
      region: "eu-west-1"
      image_name: "mikkopori/otapark"
      image_tag: "shippable"
  notifications:
    - integrationName: email
      type: email
      on_success: never
      on_failure: never
      on_pull_request: never

**Comment by kanthchandra** [comment]
Hey @mikkopori it looks like you have put branches only as shippable and you are running the build on master branch. If you put branches only, it will only be applied to that specified branch.

**Comment by kanthchandra** [comment]
Looks like your build is working now :) and going past the push image step.

**Comment by mikkopori** [comment]
Yes, thanks to your help :)

Now I just have to make sure it does not send any extra artifacts into aws, but just the bare minimum to deploy...

**Comment by kanthchandra** [comment]
Glad it worked. Closing this issue as resolved.

**Comment by mikkopori** [comment]
Fails, now it deploys the code as well and rebuilds on aws which is something I'm trying to avoid.

It would seem that the documentation here:
http://docs.shippable.com/integrations/deploy/eb/

is not fully the same as in this blog post:
http://blog.shippable.com/how-to-deploy-to-elastic-beanstalk-part-2

So is the documentation correct?

**Comment by mikkopori** [comment]
So, how do I achieve this:

```
zip -r upload_to_aws.zip Dockerrun.aws.json .ebextensions
eb deploy --staged otapark-dev

```

on shippable? Now it zips the whole projects and aws rebuilds the image. I want it to use the image already uploaded to Docker Hub..

**Comment by mikkopori** [comment]
So, I want to deploy to aws using the image pushed to Docker Hub. How should I do this?

**Comment by a-murphy** [comment]
Do you have an `.ebignore` file in your repository?  We usually suggest adding an `.ebignore` file to the root of the repository to exclude files that don't need to be updated to AWS.

The following `.ebignore` file will only upload the `Dockerrun.aws.json` and `.ebextensions` files.
```
*
!Dockerrun.aws.json
!.ebextensions/*
````

If the `Dockerfile` isn't uploaded, Elastic Beanstalk won't rebuild the image.

**Comment by mikkopori** [comment]
That worked, tnx! :)
