### ISSUE TITLE
AWS ignored .ebextentions when restarting instance

### ISSUE THREAD

**Issue by ameenmohamed** [Shippable/support#3433]
I have a sprint boot jar file that i run on elastic beanstalk , i have .ebextentions in jar file as stated by AWS . 
in the .ebextensions  i run container commands to mount elastic file system on to ec2 instance 

following is the set up 
1. cloud formation creates the beanstalk - ( i see mount successful i.e ebextentions ran successfully)
2. Jenkins deploys the build artifact to beanstalk 
3. i change the Autoscaling options from min 1 to 2 - ( see 2nds instance created with efs mount - indicating ebextentions ran successfully 

Day 2
 the same stack gets new instance , but this  instance does not have a mount i.e ebextentions was not run 
***Question : when the instance was created on day 2 it was not though Clodformation run or autoscaling event . for some reason instance was killed and replaced but Why was .ebextentions ignored*** 

Note below  : the parameters are provided by cloudformation e.g 
 "Namespace":"aws:elasticbeanstalk:application:environment",
          "OptionName":"EFS_URL",
          "Value": {"Ref": "EFSURL" }
Conetnts of env.config in .ebextentions  :>>

```
container_commands:
  01_mount:
    command: "echo ****** mounting EFS for  ${APPNAME} *****"
  02_mount:
    command: "/home/ec2-user/mount-efs.sh"       

files:
  "/home/ec2-user/mount-efs.sh":
      mode: "000755"
      content : |  
       #!/bin/bash
       sudo mkdir -p /home/ec2-user/efs
       sudo chown ec2-user:ec2-user /home/ec2-user/efs
       sudo echo ${EFS_URL}':/ /home/ec2-user/efs nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0' >> /etc/fstab
       sudo mount -a -t nfs4
       sudo mkdir -p /home/ec2-user/efs/${APPNAME}/
       sudo mkdir -p /var/log/${APPNAME}
       sudo mount --bind /home/ec2-user/efs/${APPNAME} /var/log/${APPNAME}
       sudo echo '/home/ec2-user/efs/${APPNAME} /var/log/${APPNAME} none defaults,bind 0 0' >> /etc/fstab
       echo 'EFS mount complete.'  
```

**Comment by stephanielingwood** [comment]
Hi @ameenmohamed,

I'm going to close this issue, as it looks like you've found the [correct forum](https://forums.aws.amazon.com/thread.jspa?threadID=251440&tstart=0) in which to ask your question. Best of luck getting your .ebextensions to work. 

Cheers,
- the Shippable team
