### ISSUE TITLE
drydock/u14ruball:v5.3.2 not present on worker instances 

### ISSUE THREAD

**Issue by cratz** [Shippable/support#3434]
I just run into this issue while evaluating #3209 
`boot_container` step runs longer than 45min because of:
`Unable to find image 'drydock/u14ruball:v5.3.2' locally`

**Comment by cratz** [comment]
Now even the pulling of the image is broken, see:
`https://app.shippable.com/github/bidderplace/backoffice-adv/runs/1406/1/console`

**Comment by rageshkrishna** [comment]
They are available on the new machine images. Go to your subscription settings and pick `v5.3.2` from the "Machine Images" panel. That has all the new drydock images available locally.

**Comment by cratz** [comment]
THX this helped.
