### ISSUE TITLE
Set base image per project

### ISSUE THREAD

**Issue by cratz** [Shippable/support#3435]
Is it possible to set a base image per project instead of per subscription?

We change our base image recently to latest version `v5.3.2`. Unfortunately this broke some of our projects because it uses newer version of project related CI-image (in this case `drydock/u16nodall`).
Of course we can just set used image to former used version in 'pre_ci_boot' but it looks like all "old" Ci-images where removed from "new" base image this leads to fresh pull of the old image and a long running build.

In general I don't get the point to specify the base image on a subscription level since needed dependencies are related to each project and not to the subscription. Because of this it is basically not possible to switch easily to a new base image without adapting "all" connected projects at once instead of updating  projects successively.

For sure I missed an important part of the chain but setting base image per project would solve this issue.

**Comment by manishas** [comment]
We'll need to think through this. 

Build minions are managed at a subscription level and are used to trigger builds across projects if the minion is 'warm'. If we let customers set build image per project we won't be able to reuse a machine that is already up if it was spun up with a different image. This complicates the logic behind node handling.

**Comment by cratz** [comment]
Well this is something which I had in my mind.
I don't know if it's feasible, because of disk space limitations, or even useful to keep at least two versions of the CI images inside the base image. This would enable the customers to incremental update all projects without the need to do it straight away or always download former used images.

For us this one is not urgent because we updated all our projects but we will run into it again once a new base image will be released.

**Comment by rageshkrishna** [comment]
@cratz That's a good solution to allow incremental upgrades. We'll keep this in mind when we roll out the next set of images as part of our monthly releases.

**Comment by manishas** [comment]
We now support node pools, and image versions are specified per node pool. 

You can create a separate node pool with the older image version and tell your CI jobs that need older images to use that node pool by adding the following to **shippable.yml**: 

```
runtime:
  nodePool: <node pool name>
```
