### ISSUE TITLE
Unexpected $BRANCH for Pull Request

### ISSUE THREAD

**Issue by MerrickClark** [Shippable/support#3436]
### Unexpected $BRANCH for Pull Request :
For PRs I'm seeing that $BRANCH is being populated with the value that I'd expect from $BASE_BRANCH ?

From commit on feature branch:
BUILD_URL=https://app.shippable.com/github/LifographGit/lifoclient/runs/57
BASE_BRANCH=
BRANCH=shippable-test
HEAD_BRANCH=
IS_PULL_REQUEST=false
PULL_REQUEST_BASE_BRANCH=

From PR of same branch:
BUILD_URL=https://app.shippable.com/github/LifographGit/lifoclient/runs/58
BASE_BRANCH=dev
BRANCH=dev
HEAD_BRANCH=shippable-test
IS_PULL_REQUEST=true
PULL_REQUEST_BASE_BRANCH=dev

For the PR, I'd expect $BRANCH to be branch of PR; but am seeing it's the same value as $BASE_BRANCH. Is this the expected behavior?

**Comment by a-murphy** [comment]
Yes, `$BRANCH` is expected to match `$BASE_BRANCH`.  If you want the name of the branch the pull request was opened from, that is available in `$HEAD_BRANCH`.  A pull request runs the latest `$BASE_BRANCH` with the changes in the pull request added, so it will reflect what `$BRANCH` will be when the pull request is merged.

**Comment by MerrickClark** [comment]
👍

**Comment by ibratoev** [comment]
We hit the same issue. The documentation of the $BRANCH variable can be improved: http://docs.shippable.com/ci/advancedOptions/environmentVariables/ ;)
