### ISSUE TITLE
How do I create a pipeline that crosses multiple repos?

### ISSUE THREAD

**Issue by deitch** [Shippable/support#3437]
Assume I have 3 services, A, B and C, each with their own repo. Each service will have its own tests for CI. Assume all create docker images that will be pushed out to a registry.

However, since these services interact, before actual deployment to production, I want to run a series of cross-functional tests (call them "system integration tests" if you will). Essentially, these validate that service A hasn't broken its API contract on which B depends, B for C, etc.

Essentially I need to define a pipeline such that if any one (or more) changes:

1. run CI (standard)
2. If CI passes deploy artifacts from *all* services to a testing environment
3. Run system integration tests
4. If system integration tests pass, deploy the changed service(s) to prod

**Comment by ttrahan** [comment]
@deitch : you can certainly model this within pipelines. It will be fairly straightforward if you persist a full topology testing environment and slightly more complex if you will be provisioning the testing environment on-demand/as-needed. Which will you be doing?

**Comment by deitch** [comment]
Thanks @ttrahan.

> It will be fairly straightforward if you persist a full topology testing environment and slightly more complex if you will be provisioning the testing environment on-demand/as-needed.

I don't understand the distinction. If by "persist a full topology", you mean that it just runs tests against something already deployed, how could that test against a change? Or did you mean that it has a full deployed environment and updates just the changed component?

**Comment by deitch** [comment]
Thanks I will email you and schedule for next week.

May I recommend that this is the type of info that would be really helpful in the docs and tutorials?

**Comment by ttrahan** [comment]
Definitely agree. We continually add new sample projects to demonstrate different use cases at http://github.com/shippableSamples. This particular use case isn't demonstrated there yet, but should be so within the next month or so.

**Comment by manishas** [comment]
@chetantarale this is another use case we need to shwocase in our docs.

**Comment by deitch** [comment]
@manishas definitely. @ttrahan kindly spent some time on the phone with me describing how it works. This is a major advantage of shippable over other CI-only solutions, and should be highlighted.
