### ISSUE TITLE
Billing: Email address for accounting

### ISSUE THREAD

**Issue by infrab2boost** [Shippable/support#3439]
### Description of your issue:
Hi, for technical notifications we use xxx@b2boost.com
However, we need any billing-related emails to go to x@b2boost.com

I don't see anywhere on your admin site anything to set this up. Could you please take care of this in your backend?

Thank you.

Our shippable Id is xx

**Comment by rageshkrishna** [comment]
@infrab2boost Please take a look at the "Settings" tab on your subscription page. You should see a "Billing Contact" panel. This setting can only be modified by subscription owners. I hope this helps.

**Comment by infrab2boost** [comment]
Thanks! Missed it
