### ISSUE TITLE
Failing rSync 

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3440]
Why does this keep failing?

It seems to say that there are 2 invalid Yml Files, but that can't be, as the pipeline seems to work. If there is a problem with YML how can I tell what's wrong? 

https://app.shippable.com/subs/github/ExecThread/pipelines

It's the one called Members-App_runCI, It's not clear to me how it got there, and I can not find any UI anywhere to remove it.

**Comment by a-murphy** [comment]
It looks like you have the same resources defined in multiple syncRepos.  Since the other rSync job already created them, and resource names are unique within a subscription, the failing rSync job is telling you that it can't create the resources that already exist.  You can get the names of these resources out of the rSync logs; it's the two lines starting with "there is already a resource named."  

Removing the resources that have been created by other rSync jobs from the YML for this rSync job will allow the job to succeed.

**Comment by npahucki** [comment]
Hw do I get rid of the duplicate?

**Comment by a-murphy** [comment]
If you remove the resources the rSync job says already exist from the `shippable.resources.yml` in the branch the failing rSync job is following, this rSync job will stop warning you that they already exist.  The other rSync job, that already created the resources, will still have the resources and can be used to update those resources if you need to.

**Comment by npahucki** [comment]
I think they both point to the same branch. One is a duplicate of the other that got accidentally created in the process of trying to get things setup. You didn't answer my question, i'll re ask it here in hopes that it gets answered this time: 

**How do I delete the extraneous rsync job?** 

There is no UI that is obvious that will let me do it. The duplicate does not show up under integrations, and there is no button to delete it in the SPOG.

**Comment by npahucki** [comment]
My Pipelines tab had only a SPOG view in it, and right clicking there does not give the option to delete. 

See screen shot. 

![screen shot 2017-03-16 at 1 32 15 pm](https://cloud.githubusercontent.com/assets/823555/24007398/2ff9d638-0a4d-11e7-8ad8-20498cc59c8c.png)

**Comment by a-murphy** [comment]
That's a runCI job.  Those are created for projects enabled in CI and can only be deleted by deleting the project in CI.

Only syncRepo resources have a delete option in the SPOG.  The syncRepos in your SPOG are all in the left-most column, the top two and the bottom one in that column.

**Comment by npahucki** [comment]
Now I'm really confused as to which one I need to delete. The one called `Members-App master` I thought was the one that I wanted to keep. Whichever I delete, I need to make sure both CI and CD continue working. Can you take a look at my account and see which I can delete safely?

I'm sorry but the UI is quite confusing and it's not clear what is connected to what.

**Comment by a-murphy** [comment]
I haven't been able to identify any rSync jobs without associated resources.  Are you sure you don't just have two resources that are listed in two different syncRepos?

It looks like you've soft-deleted one of them, though.  If you want to add it back, find the syncRepo, right-click on it, and click "restore."  Previous deployments in deploy jobs don't usually survive soft-delete, so you may want to check that any soft-deleted deploy jobs are correctly deployed after restoring them.

**Comment by npahucki** [comment]
I tried removing the `Members-App master` and it broke CD! So I have restored it. 

Is is possible to get on a hangout to work this out?

**Comment by stephanielingwood** [comment]
Sure. If you want to send me a hangout link - stephanie at shippable dot com, we're free to jump on a hangout now.

**Comment by npahucki** [comment]
sent.

**Comment by stephanielingwood** [comment]
Hope that helped. Let us know if you need any other help with this!

**Comment by npahucki** [comment]
I think we are good, you can close this ticket. Thank you again!
