### ISSUE TITLE
Shippable docs are broken

### ISSUE THREAD

**Issue by sumothecat** [Shippable/support#3442]
Hi, existing links from around the web are currently opening in an empty page. E.g. http://docs.shippable.com/ci_configure/#aws-elastic-beanstalk

![image](https://cloud.githubusercontent.com/assets/917606/23998793/1b93f286-0a4e-11e7-8db6-e19087b8c23b.png)

**Comment by Riturajcse** [comment]
Hello @sumothecat 
Thanks for letting us know about this. This will be fixed soon.

**Comment by stephanielingwood** [comment]
Hi @sumothecat,

Sorry about this - we found a bug in our 404 page which is making it not-so-informative. However, it will be fixed soon. In the meantime, the docs you need are here: http://docs.shippable.com/integrations/deploy/eb/

Cheers,
Stephanie
