### ISSUE TITLE
v5.3.2 with drydock/u16pytall:tip hanging on redis_start

### ISSUE THREAD

**Issue by AndreCimander** [Shippable/support#3443]
### Description of your issue:
Builds with image_name: drydock/u16pytall and the image_tag: tip fail to complete, the build becomes stuck in redis_start ("Waiting for redis to start..." loop).

Are we using the wrong image_tag? 

https://app.shippable.com/bitbucket/influencerdbit/influencerdb.net/runs/5444/1/console

**Comment by rageshkrishna** [comment]
Please use image tag `v5.3.2`.
