### ISSUE TITLE
Builds taking too long to finish

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#3444]
For our tercel project, builds are timing out and taking too long to finish. Mostly, it happens during PDT timezone working hours.

https://app.shippable.com/github/Falkonry/tercel/runs/4048/1/console

**Comment by stephanielingwood** [comment]
HI @phagunbaya,

We took a look at the history of your tercel project, and it looks like the occasional timed-out builds have been happening at a variety of days/times (including Saturdays, non-PST hours, etc.) for awhile. While it may be possible that some of your calls to different resources are slower during peak business times, it's probably not the cause of your timeouts. 

However, we did notice that most of the recent timed-out builds are getting to the same couple groups of tests and just...stopping. Often we see this behavior when the node runs out of memory. Additionally, we found this in the logs for one of the timed-out builds (3959):
```
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000070d480000, 62390272, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 62390272 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /root/src/github.com/Falkonry/tercel/libraries/scala/routine/hs_err_pid1948.log
# [ timer expired, abort... ]
```

Assuming it's an out-of-memory problem, there's a couple options you can pursue. First would be to check your test and see if you can locate what's taking up so much memory. If you can't find it, and/or if your tests need that much memory, you can run your builds on a [custom node](http://docs.shippable.com/ci/advancedOptions/byon/) with as much memory as you require.

**Comment by phagunbaya** [comment]
Thanks @stephanielingwood for looking into this. I'll check why tests are consuming too much memory.
