### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by blackstar257** [Shippable/support#3446]
When will the new u14phpall prod tag be upgraded to include the new php 7.1?

**Comment by avinci** [comment]
We will not update prod tag anymore. We are moving to static tags so that we can support backward compatibility. You will need to use the tag `v5.2.3` to get the latest version.

**Comment by blackstar257** [comment]
I have php 7.1 defined in my .travis.yml but it looks like shippable CI has it hard coded to use u14phpall:prod docker image....

**Comment by blackstar257** [comment]
language: php
php:
- 7.1

**Comment by blackstar257** [comment]
So is my only option to ditch my travis.yml and use a shippable.yml with the extra section defining the CI image as u14phpall:v5.2.3

**Comment by blackstar257** [comment]
@avinci

**Comment by manishas** [comment]
@blackstar257 you will need to migrate to the shippable.yml format use the new images.

Here is what you need to do:

- Migrate to shippable.yml. Documentation is [here](http://docs.shippable.com/ci/shippableyml/) and we also have a [blog that helps with the migration](http://blog.shippable.com/migrating-to-the-new-build-platform). [This blog](http://blog.shippable.com/5-tips-for-a-successful-migration) might also help. 

- Change your Subscription Settings to use the v5.3.2 image:
![image](https://cloud.githubusercontent.com/assets/2983749/24062704/be367114-0b19-11e7-8610-ce5d140e0058.png)

- Use the following in your `shippable.yml`:

```
build:
  pre_ci_boot:
    image_name: drydock/u14phpall
    image_tag: v5.3.2
```

**Comment by avinci** [comment]
We support basic travis.yml features as a way to quickly onboard. A lot of cool nice capabilities need shippable.yml. I would recommend you use our native yml if you need those features. docker settings, boot, pre build, integrations are a few of those examples. 

For what you are trying to do, changing your subscription machine image should work. Let me know if this works. 

![screen shot 2017-03-17 at 10 56 24 am](https://cloud.githubusercontent.com/assets/1302035/24062671/810f6e8a-0b00-11e7-917a-f1acd9e8eefd.jpg)

**Comment by blackstar257** [comment]
Thanks
