### ISSUE TITLE
Error attempting to deploy to GKE

### ISSUE THREAD

**Issue by epipho** [Shippable/support#3447]
### Description of your issue:

When attempting to deploy the sample app (https://github.com/epipho/node-gcr-deploy-gke-loadbalancer/)  to GKE I receive the following error during the deploy step:

```
Generating task script 0s  
  Writing managed task script 0s  
  Validating script dependencies 0s  
  /home/shippable/micro/nod/stepExec/managed/deploy/run.sh 1s  
Starting Deployment for: shipdemo-deploy-gke-test
Preparing manifests
Applying manifest overrides for shipdemo-manifest-gke
Summary of cluster: -- newlyAdded: 1, -- changed: 0, -- deleted: 0
Force deployment is: true
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Manifests removed: 0
buffer.js:208
    throw new TypeError('must start with number, buffer, array or string');
    ^
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:208:11)
    at new Buffer (buffer.js:65:10)
    at /home/shippable/micro/nod/stepExec/managed/deploy/providers/gke/Adapter.js:96:28
    at /home/shippable/micro/nod/stepExec/managed/deploy/providers/gke/Adapter.js:596:16
    at /home/shippable/micro/nod/stepExec/managed/deploy/providers/gke/Adapter.js:647:7
    at /home/shippable/micro/nod/node_modules/async/dist/async.js:3583:11
    at /home/shippable/micro/nod/node_modules/async/dist/async.js:396:18
    at replenish (/home/shippable/micro/nod/node_modules/async/dist/async.js:866:27)
    at /home/shippable/micro/nod/node_modules/async/dist/async.js:878:27
    at /home/shippable/micro/nod/node_modules/async/dist/async.js:840:18
```

As far as I can tell the GKE integration is correct and the intermediate values in the pipeline look ok (image, docker properties etc).

Deploy job is being triggered from https://app.shippable.com/github/epipho/node-gcr-deploy-gke-loadbalancer/runs/6/1/console and the deploy job shows an ID of 17253.

 First time trying out Shippable, so I suspect I have something somewhere misconfigured.

**Comment by ankul-shippable** [comment]
Hi @epipho, we have filed an internal bug to fix this, will keep you posted with the status of that.

**Comment by epipho** [comment]
I tweaked my service account's permissions to include more container engine perms and it seems to be getting furthur along.  This may just be bad error handling of a permissions error.

**Comment by ankul-shippable** [comment]
@epipho Great! we will fix this scenario to provide more informative error message.

**Comment by ankul-shippable** [comment]
This is fixed now, we have provided more informative error message stating that error is due to missing certificates and/or keys.
Closing this.
