### ISSUE TITLE
Error "Delete account"

### ISSUE THREAD

**Issue by danielmenezesbr** [Shippable/support#3448]
When I try to delete account, show this message:

![image](https://cloud.githubusercontent.com/assets/5949657/24076081/a8aaac7c-0c07-11e7-9ef3-d560532ec4c3.png)

**Comment by Riturajcse** [comment]
Hey, @danielmenezesbr Sorry for the inconvenience. We have opened an internal issue for this and will let you know about our standing on this.

**Comment by manishas** [comment]
@danielmenezesbr Do you want to delete your account? :(

**Comment by danielmenezesbr** [comment]
@manishas No! Just was just a test.  : )

**Comment by deepikasl** [comment]
This is fixed. Hence, closing.
