### ISSUE TITLE
SETTING UP NIGHTLY BUILDS ON SHIPPABLE

### ISSUE THREAD

**Issue by danielmenezesbr** [Shippable/support#3453]
When I configure my shippable.resources.yml with the interval "*/2 * * * *" my jobs is triggered every 2 minutes and all works fine. But when I change interval to a fixed time, for example, "10 20 * * * my job is not triggered.

**shippable.yml**
language: python

python:
  - 2.7

install:
  - pip install dropbox

script:
  - python script.py

**script.py**
print "hi"

**shippable.jobs.yml**
jobs:
  - name: "sample_runCI"
    type: runCI
    steps:
      - IN: nightly-trigger
    on_success:                          
      - script: echo 'on success !!!!!'  
    on_failure:                          
      - script: echo 'Failed job .... :('

**shippable.resources.yml**
resources:
  - name: nightly-trigger
    type: time
    seed:
      interval: "10 20 * * *"

**Comment by a-murphy** [comment]
When specifying a particular time, the new version of the time resource will be created at that time in UTC.  So, you may need to convert the time you would like triggered from your local timezone to UTC and use the UTC time in your shippable.resources.yml.

If your time was in UTC, could you let us know which subscription had this problem so that we can look at the correct resource?

**Comment by danielmenezesbr** [comment]
@a-murphy 
I convert my local timezone to UTC, but it's doesn't work.
My Shippable ID: 58cd47daa1d9180500193f34

![image](https://cloud.githubusercontent.com/assets/5949657/24127669/4aa91f46-0db5-11e7-921a-8c37f8e60489.png)

![image](https://cloud.githubusercontent.com/assets/5949657/24127672/550e2698-0db5-11e7-8ac7-2ed4d5dbd05d.png)

**Comment by a-murphy** [comment]
It does look like there is a bug changing the interval on existing time resources; the next time it thinks it needs to trigger is still the previously set time.  We'll look into that.

One option to get around this is to delete the time resource (comment it out of your `shippable.resources.yml` and `shippable.jobs.yml`, then find it on the pipelines tab of your subscription, right-click on it, and click "delete") and add it back (uncomment it in your `shippable.resources.yml` and `shippable.jobs.yml`).  Or you can just wait until the previously-specified time, which looks like tomorrow afternoon for you, after which it will be updated to next trigger at the correct time.

**Comment by danielmenezesbr** [comment]
@a-murphy, thanks!

Your workaround works!

**Comment by ankunath** [comment]
This issue is now fixed in the recent 5.3.4 release. Hence i am closing this issue.
