### ISSUE TITLE
Overall service degraded

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#3457]
Hi,

There are several issues right now (We're using our own node for shippable build and there's nothing special in our machine):

1. Overall service is really slow. It takes up to 10min to start build, and Slack notifications also delays 10~30 minutes. Several steps communicating with Shippable's central server(?) are especially slow.
2. Cancelled build automatically restarts, even nobody tried to rebuild.
https://app.shippable.com/github/Knowre-Dev/DaekyoAPI_KR/runs/1391/summary

https://status.shippable.com/ This status page says everything's normal, then what is the point of the status page? (Also, this page doesn't even have valid SSL cert...)

**Comment by mbrodala** [comment]
I can confirm this behavior.

**Comment by caleblloyd** [comment]
Builds are also very slow to start for me right now

**Comment by kanthchandra** [comment]
Yes, we are looking into it as we speak. I'll update you as soon as I have more info.

**Comment by manishas** [comment]
@Kivol @mbrodala @caleblloyd this should now be resolved. We're monitoring the service very closely.

Please let us know if you run into any slowness again. Thanks for your patience!

**Comment by mbrodala** [comment]
@manishas Thanks for fixing. I've been asking this before but could you add some kind of metric to the status page which tracks the general performance or the part which was responsible this time? BTW: what was the issue?
