### ISSUE TITLE
How to identify a "fork" PR build?

### ISSUE THREAD

**Issue by ivailop** [Shippable/support#3461]
What is the way to identify a `fork` PR build?
Based on the documentation, at least the way I interpreted it, `IS_FORK` environment variable is supposed to provide that information. However testing I found it is always set to `false`!

Besides that, it would be better if you provide the actual `fork` Repo name (similar to how Travis does) instead of just a Boolean.

**Comment by rageshkrishna** [comment]
Hi @ivailop, can you please link me to a build where you are seeing the wrong data? Thanks.

**Comment by ivailop** [comment]
Hi @rageshkrishna, you can find the build at https://app.shippable.com/github/munderseth/build-box/runs/52/1/console.

**Comment by stephanielingwood** [comment]
Hi @ivailop,

`IS_FORK` is used to describe the enabled project that the build is running under. So, in your case, it should be false, as the build happened under the project that is not a fork.

If you just need to know whether a build originates from a PR, you can use the `IS_PULL_REQUEST` environment variable. However, if you'd like to know whether the PR arose from a forked repo, or from the original repo, we can add this as a feature request. Just let us know.

**Comment by ivailop** [comment]
I guess, the way you define `IS_FORK` (even I can't understand the need and haven't seen anybody else providing such thing) has some application in practice... 

In my case, I need to know if the build originates from a `fork` PR. Basically having `IS_PULL_REQUEST==true` and `REPO_FULL_NAME != HEAD_REPO_FULL_NAME` (assuming you have `HEAD_REPO_FULL_NAME` or something else providing the name of the originating repo). 

For your information:
* Travis provides `TRAVIS_PULL_REQUEST_SLUG`
* Circle - `CIRCLE_PR_USERNAME` and `CIRCLE_PR_REPONAME`
* Appveyour - `APPVEYOR_PULL_REQUEST_REPO_NAME`
* Jenkins - `ghprbGhRepository`

**Comment by stephanielingwood** [comment]
Makes sense. I'll mark this as a feature request, then.

In the meantime, if all your contributors are making PRs from the master branch of their fork to your master branch, you could check if `HEAD_BRANCH` (the branch on the PR repo) is the same as the `BASE_BRANCH` (the one on the base repo). Definitely a hack (was debating even suggesting it!), but it might work until we can get to it in our backlog.

**Comment by ivailop** [comment]
Based on [your documentation](http://docs.shippable.com/ci/advancedOptions/environmentVariables/) it looks like you recently added `PULL_REQUEST_REPO_FULL_NAME`. However for both `fork` and `branch` PR builds it is always empty.

**Comment by himanshu0503** [comment]
@ivailop : We looked through one of your PR's and found that it is a `rerun`. The metadata for `rerun` is picked from the previous run, it is possible that your previous PR run didn't have this data.
Moving forward all your new PR builds will be having this property set.
Can you please try sending in a new PR and see if it works?

**Comment by ivailop** [comment]
Yes, you are right. I just tried again with a **new** build and it worked all fine. Sorry for creating any unnecessary noise.
