### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by mariale425** [Shippable/support#3462]
Hello, I'm having this error in all my PR:

https://www.evernote.com/l/AiTDS02GmqlNKqG3fVFih1eq2LGB1euvvzw
Build: https://app.shippable.com/github/iTourSmart/touritinerary/runs/14280/1/console

Can you help me?

**Comment by niranjan92** [comment]
Hi, 
Can you please check if your tests have changed and are taking longer than before. . It looks like the job is timing out after the maximum of 2 hours.

We would be happy to investigate further if that's not the case.

**Comment by mariale425** [comment]
Time of my tests on my local server @niranjan92 :
```
real	11m22.294s
user	7m25.216s
sys	0m27.315s
```

**Comment by stephanielingwood** [comment]
Hi @mariale425,

If your tests are running fine locally, but timing out in your build, usually it's because your tests are looking for something (maybe an endpoint, or a db, or another service) that you haven't made available in your build. Hopefully that helps with the troubleshooting.

**Comment by mariale425** [comment]
The problem was the cache. I cleared the cache and it worked again.
@stephanielingwood @niranjan92

**Comment by stephanielingwood** [comment]
@mariale425 

Glad to hear you found the problem! I'm going to close this issue now - feel free to open another issue if you run into more challenges.
