### ISSUE TITLE
Builds sometime fail during aws_eb_deploy step

### ISSUE THREAD

**Issue by jmarver** [Shippable/support#3464]
We're seeing build failures during the aws_eb_deploy step. So far, clicking Rebuild results in successful builds. 

https://app.shippable.com/github/serlio/tart/runs/128/1/console
https://app.shippable.com/github/serlio/tart/runs/124/1/console
https://app.shippable.com/github/serlio/tart/runs/119/1/console

Any thoughts on this? Thanks in advance. Jeff.

**Comment by stephanielingwood** [comment]
Hi Jeff,

Thanks for letting us know about those builds. We've taken a look and suspect it may be the same issue we're seeing as https://github.com/Shippable/support/issues/3450 - basically, the console logs just stopping during periods of intense output. I'm going to close this issue so we can track the discussion in #3450. If we need to, we can always reopen this issue if it's not resolved there.
