### ISSUE TITLE
https://shippable.com does not redirect to https://www.shippable.com

### ISSUE THREAD

**Issue by haf** [Shippable/support#3465]
Your site is down as seen from Stockholm.

**Comment by rageshkrishna** [comment]
@haf, I don't think so. I did a quick check and the site is still reachable. Can you please try again and let me know?

**Comment by haf** [comment]
Still down.

**Comment by haf** [comment]
curl -vv https://shippable.com
* Rebuilt URL to: https://shippable.com/
*   Trying 54.231.32.113...

**Comment by kanthchandra** [comment]
hi @haf can you try accessing https://app.shippable.com

**Comment by haf** [comment]
That works.

**Comment by kanthchandra** [comment]
@haf I think http://shippable.com opens home page and when you click login it redirects to https://app.shippable.com, but https://shippable.com is not loading the home page, I guess we'll need to look into that but in the mean time can you use https://app.shippable.com?

**Comment by harryi3t** [comment]
Our marketing site url: https://www.shippable.com/
Our main app url : https://app.shippable.com/

Currently we don't have redirect from https://shippable.com/ to https://www.shippable.com/
After next deployment on Sunday at 10:30pm PST this should be available

**Comment by haf** [comment]
https://www.shippable.com/ redirects to app.shippable.com

**Comment by haf** [comment]
This is not a question.

**Comment by harryi3t** [comment]
@haf have updated it to a bug. (This will be fixed on next deployment)


Also about your previous query/comment

> https://www.shippable.com redirects to app.shippable.com

this will happen only if you are logged in

I hope it clears the confusion

**Comment by rageshkrishna** [comment]
@haf The redirect has been fixed. http://shippable.com and https://shippable.com now redirect you to https://www.shippable.com. You will still end up at https://app.shippable.com if you are already logged in.
