### ISSUE TITLE
When building a docker image where to find shippable version number?

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3466]
Hello,

I'm building and deploying docker images in shippable and would like to show the software version in the gui of the deployed image as well. So, in which file does shippable store this information so I could make it visible?

Best regards,

Mikko

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by rageshkrishna** [comment]
Hi @mikkopori, our environment variables are documented at http://docs.shippable.com/ci/advancedOptions/environmentVariables/

You should be able to use `$SHIPPABLE_BUILD_NUMBER` to get the build number, if that's what you're looking for. I hope this helps.

**Comment by mikkopori** [comment]
Tnx, that was it!

Mikko
