### ISSUE TITLE
Event notification webhook doesn't trigger build

### ISSUE THREAD

**Issue by szarekm** [Shippable/support#3468]
## Description:
I've created 4 integrations (all event triggers). All of them seem to work (they return success in the build log), but only one of them triggers build. The only difference between repositories that I can find is that I'm the owner of the one that works, and the admin (not the owner) of the rest.

### Console log:
![wehook](https://cloud.githubusercontent.com/assets/21328988/24347056/57fc43d6-12d7-11e7-9c32-2f487d4e147d.png)

### Integrations part in YML file:
![integrations](https://cloud.githubusercontent.com/assets/21328988/24347021/329c59f0-12d7-11e7-9ebf-1100d1139821.png)

**Comment by a-murphy** [comment]
Is the screenshot of the working integration or one of the others?  I haven't been able to find which of your projects are using the integrations that aren't working.  Would you mind letting us know which projects have the event triggers that aren't working and which one works?

Your permissions shouldn't be a problem; just write permissions are required to trigger a build.  The most common causes of event triggers not working as expected are reusing the same account integration multiple times in the same shippable.yml and incorrectly formatted tokens in the account integration (it should be "apiToken" followed by one space and then the token).

**Comment by szarekm** [comment]
Ok, I've found what's gone wrong. All integrations work, but they trigger repository default branch, which is not a branch that I want to build. Can I trigger specific branch in event trigger?

**Comment by a-murphy** [comment]
Although it's possible to specify a branch with an event trigger, it won't work very well when also specifying environment variables.  In your case, using the API is probably the best choice.  Adding something like the following to the `on_success` section of your `shippable.yml` will trigger a build on the specified branch with the same environment variables above:
```YML
 - 'if [ "$BRANCH" == "cross-compilation" ] && [ "$IS_PULL_REQUEST" == "false" ] ; then curl -H "Authorization: apiToken $API_TOKEN" -H "Content-Type: application/json" -d "{\"branchName\": \"yourBranchName\", \"globalEnv\": {\"REPO_TRIGGER\": \"$REPO_NAME\", \"AUTHOR_TRIGGER\": \"$COMMITTER\", \"FCC_BUILD_NUMBER\": \"$BUILD_NUMBER\"}}" -X POST https://api.shippable.com/projects/:projectId/newBuild; fi'
```
You'll have to add an environment variable with `API_TOKEN` to the `shippable.yml` as well, just encrypt a variable on the settings tab with `API_TOKEN=yourAPIToken` as documented [here](http://docs.shippable.com/ci/advancedOptions/environmentVariables/#secure-variables).  And replace "yourBranchName" in the post body with the branch you would like to trigger and ":projectId" in the URL with the ID of the project to trigger.  The project ID can be found in the badge URLs on the project settings tab (the parameter after "projects/").

**Comment by szarekm** [comment]
Works like a charm. Thank you!
