### ISSUE TITLE
Fail on restore_cache

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#3469]
Hi,

I'm using our own node and sometimes(about 1~2 out of ten) I encounter the following error and then the build fails. I tried removing `/home/shippable/cache/buildCache.tar.gz` inside `genexec` container, but the error still presents.

Is there any idea to prevent this?

https://app.shippable.com/github/Knowre-Dev/USKMU-SERVER/runs/977/1/console
```
tar -xzf /home/shippable/cache/buildCache.tar.gz
tar: root/src/github.com/Knowre-Dev/USKMU-SERVER/node_modules/phantomjs-prebuilt/node_modules/.bin: Directory renamed before its status could be extracted
......
```

Thanks,
Kurt

**Comment by rageshkrishna** [comment]
It looks like you're using overlayfs. There's an open issue with docker about this: https://github.com/docker/docker/issues/19647

Can you try switching to aufs if that's an option to see if it helps?
