### ISSUE TITLE
Docker tag no respected in deploy?

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3473]
Hello,

running:
https://app.shippable.com/github/mikkopori/enterlot/runs/387/1/console

it would seem that though I set a build-specific docker-tag that is not respected in the deploy-phase and the wrong tag (latest instead of 389) from dockerhub is deployed:

cat /tmp/Dockerrun.tmp | sed 's//mikkopori\/otapark/' | sed 's//389/' | sed 's///' | sed 's//elasticbeanstalk-eu-west-1-414075299243/' > Dockerrun.aws.json 0s  

  cat Dockerrun.aws.json 0s  
{
"AWSEBDockerrunVersion": "1",
"Authentication": {
    "Bucket": "elasticbeanstalk-eu-west-1-414075299243",
    "Key": ".dockercfg"
  },
"Image": {
  "Name": "mikkopori/otapark:latest",
  "Update": "true"
},
"Ports": [
  {
    "ContainerPort": "8000"
  }
],
"Volumes": [
  ]
}

Could this have something to do with the fact I'm running this image-version:
    image_name: drydock/u16pytall
    image_tag: v5.3.2
    options: "-p 5432:5432 --net=bridge"
?

Mikko

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
In the image section of your Dockerrun.aws.json file, Shippable is expecting to find placeholders like `"Name": "<IMAGE_NAME>:<TAG>"`

In your case, if the name and tag are already filled in (with `mikkopori/otapark:latest`) then nothing will be replaced, and that is the name/tag that will be deployed.

documentation here describes the configuration of the dockerrun file: http://docs.shippable.com/integrations/deploy/eb/

**Comment by mikkopori** [comment]
Thank you, works fine. Did not understand the docs :)

Mikko
