### ISSUE TITLE
CI skip integrations from forked repository

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3474]
We have a primary repository. During the CI run, it should upload a docker image to ECR. This is fine.

I have my own personal fork of the repository. When I push changes to the master branch, I want the CI to run, but not upload the docker image to ECR. What actually happens is that shippable won't even attempt to run the job, because the integration is not available:

```
This project does not have access to the integration specified in the yml AWS-wspdigital-testing-ecr
```

As a result, it doesn't get to the step where the docker push step is skipped.

Is there any way to get this job to run without the integration on my personal repository?

**Comment by ambarish2012** [comment]
Unfortunately not, since integrations will not propagate from the primary repository account to your account. As you rightly guessed, you will have to create the AWS integration in your account and use it in the YML.

**Comment by manishas** [comment]
@brianmay let me think of a couple of options and get back to you.

**Comment by brianmay** [comment]
Thanks.

**Comment by manishas** [comment]
@brianmay there is no way to 'turn off' integrations for a forked repo. So you would need to do the following:

- Create an integration for the subscription containing the fork. The integration should be named the same as in the yml:  'AWS-wspdigital-testing-ecr'
- In your yml, check for the IS_FORK variable and only push if this is set to false.

I have added this request to our backlog. We will investigate how to best address this scenario and get back to you.

**Comment by manishas** [comment]
This isn't currently in the roadmap, so closing as deferred. The suggested workaround, while not perfect, should bypass this problem.
