### ISSUE TITLE
Is there a recommended/best practice workflow for versioned releases?

### ISSUE THREAD

**Issue by evanbrumley** [Shippable/support#3475]
Hi all,

We've got all of the CI, image creation, manifests, deployments, notifications etc set up for our first Shippable project - all looking good! The last thing we need to figure out is a sensible way of managing releases and versions.

A simplified version of our current pipeline is something along the lines of:

```
test deploy job --> release job (bump=minor) --> staging deploy job --> production deploy job
```

The release job works fine for simple minor version bumps, but we'll be doing a constant mix of rc, patch, minor and major releases. It seems like with the pipeline above we'd have to manually edit the bump directive in the release yaml then run the release job every time. Is this how the release jobs were designed to be used?

I'm curious to know if there are any reference pipelines that handle this in a more elegant way, or if the Shippable team have any recommended workflows that we can learn from.

For reference, our current pipeline can be viewed here:
https://app.shippable.com/subs/bitbucket/wspdigital/pipelines

Cheers,

Evan Brumley

**Comment by ambarish2012** [comment]
Hi Evan - I would like to better understand your scenario. It would be useful for us to get into a call or email conversation so that I can better understand what you are trying to accomplish. We should be able to support your requirements but as things stand with your current design, you will need to update the release yaml.

Please let me know your email address if you want to discuss this further.

**Comment by evanbrumley** [comment]
Thanks @ambarish2012 - is there a private support channel I can use to share my contact details with you?

**Comment by ambarish2012** [comment]
Sure - you can email your contact details directly to me @ ambarish@shippable.com.

**Comment by keen99** [comment]
+1 - I'd love to hear was the result of this was....

**Comment by seniorquico** [comment]
@evanbrumley @ambarish2012 Any updates to share? I'd also like to understand if there is a better way to manage this using the release job. We currently manage our package versions external to the pipeline.

**Comment by manishas** [comment]
@ambarish2012 can we post resolution here and close this issue? We should also write a doc on this and post the link here.

**Comment by manishas** [comment]
Unfortunately, we have lost the history on this issue, so closing it. However, if anyone wants to have a conversation on how to use the release job, happy to jump on a call and make some recommendations. Shoot me an email at manisha@shippable.com
