### ISSUE TITLE
How do you stop a CD job?

### ISSUE THREAD

**Issue by jsgoller1** [Shippable/support#3476]
I have multiple deploy jobs in the CD pipelines that talk to ECS and attempt to start tasks. Shippable will spin for a long time if it can't start ECS tasks, so I want to be able to stop the job. Where is the stop button? How do I kill a job that's in process so I don't have to wait for it to fail?

**Comment by ambarish2012** [comment]
We do not have the ability to stop deploy jobs yet, they currently time out after a few minutes like you have observed.

**Comment by ambarish2012** [comment]
This feature request is already in our backlog. As soon as it is available, we will let you know. Thanks!

**Comment by manishas** [comment]
Closing since the deploy job issue is addressed. We're working on a broader effort to allow cancel for managed jobs as well.
