### ISSUE TITLE
Environment variable COMMITTER does not have a fallback

### ISSUE THREAD

**Issue by kaatula** [Shippable/support#3479]
I'm sending notifications from our build. Messages include [$COMMITER](http://docs.shippable.com/ci/advancedOptions/environmentVariables/) variable.
It works fine when the commiters have set Public name in their profile
![image](https://cloud.githubusercontent.com/assets/939396/24445215/d507e858-1471-11e7-98ed-b958f7f99a43.png)

However, number of people does not have this field filled.

In this case, $COMMITER is empty.

Expected behavior:
I would expected it to fallback to username of commiter account.

[Sample of such build](https://app.shippable.com/github/DevExpress/dashboards/runs/3813/summary)

**Comment by ambarish2012** [comment]
@kaatula Thanks for reporting this issue. I have filed a bug.

**Comment by avinci** [comment]
this si not resolved until the bug is closed.

**Comment by ChaitanyaVootla** [comment]
@kaatula This change was shipped yesterday, $COMMITTER var will now fallback to the username.
