### ISSUE TITLE
Postgresql service is failing in middle of the tests

### ISSUE THREAD

**Issue by txomon** [Shippable/support#3480]
### Description of your issue
Lately we have been receiving a lot of build failures because the database goes offline for a while during the tests. And there is no real reason, as the tests after retrying pass. If you could have a look it would be awesome

- Link to the build failure: https://app.shippable.com/github/Ridee/jinn-api/runs/14511/1/console

**Comment by ambarish2012** [comment]
@txomon I looked at your console logs and postgres is going into recovery mode after which it is refusing all connections.

FATAL:  the database system is in recovery mode
E       OperationalError: (OperationalError) FATAL:  the database system is in recovery mode

I suggest you look at the database log files to debug this issue further. Please send us the log files if you need further assistance.

**Comment by JesusAlk** [comment]
@ambarish2012
I need to retrieve the logs.
Do you know the location of the logs in the container?
Can you help me with this?

**Comment by ambarish2012** [comment]
@JesusAlk are you using your own build machine (custom node) for the build or using a shippable node? Also are you interested in the container logs or the database server logs?

**Comment by JesusAlk** [comment]
We are using  a Shippable Node. I am interested in container logs also. Thank you.

**Comment by ambarish2012** [comment]
@JesusAlk 

1. To get the container logs, add this line to post_ci

- docker ps | sed -n 2p | awk '{print $NF}' | xargs docker logs --tail=all

Tweak the docker logs command as needed.

2. To dump the database logs, you can simply cat them in the post_ci section as well.
