### ISSUE TITLE
Github access from runCLI job

### ISSUE THREAD

**Issue by mliszewski** [Shippable/support#3481]
I have a runCLI job that has a gitRepo as a resource. At the end of the job I would like to add and push a git tag to GithHub but the git command fails with the following.

```
Error: Command failed: git push origin master  --tags
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

Is there a way to give the runCLI job permissions for my GitHub repo?

**Comment by chetantarale** [comment]
@mliszewski You can do this using the ssh keys that are added to your repository. All private projects have a ssh key added to your repository. It can be found at the location `/tmp/ssh`. 
You can also use ssh key integration to achieve this. [Here](http://docs.shippable.com/ci/advancedOptions/sshKeys/) are the docs for ssh and instructions on how you can do it. 

Let me know if you have any questions.
Thanks
