### ISSUE TITLE
Where is "Download" button for long console logs?

### ISSUE THREAD

**Issue by johnwickerson** [Shippable/support#3483]
When the log is very long, I get the following message:
````
Logs too long to show here. Please use download button to download the logs.
````
But where is the 'download button'? I can't see it anywhere!

**Comment by ambarish2012** [comment]
The download button is right above the console.

<img width="1162" alt="screen shot 2017-03-29 at 11 53 12 am" src="https://cloud.githubusercontent.com/assets/26096758/24471263/74d753e2-1476-11e7-9c43-4b9c1d486a68.png">

**Comment by johnwickerson** [comment]
Hmph, I don't see it (see pic below). Is it possible that the Download button only appears once the job is completed?

<img width="1144" alt="screen shot 2017-03-29 at 20 45 16" src="https://cloud.githubusercontent.com/assets/4182011/24473351/de017574-14c0-11e7-9164-3c7faefde259.png">

**Comment by ambarish2012** [comment]
Yes, that is correct. The job has to complete.
