### ISSUE TITLE
Support custom timeouts for EBS deployments step

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3484]
Hello,

my deployments are often running longer than the 10 min. timeout set for them, like this one:
https://app.shippable.com/github/mikkopori/enterlot/runs/395/1/console

How can I extend that timeout for deployment?

Thank you!

Mikko

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by ambarish2012** [comment]
@mikkopori custom timeouts can be set for projects and the steps for doing so are documented [here](http://docs.shippable.com/ci/advancedOptions/timeouts/). Thanks.

**Comment by manishas** [comment]
@ambarish2012 the first suggestion above won't work because @mikkopori is not directly calling the eb deploy command. He is using the Shippable yml block documented here: http://docs.shippable.com/integrations/deploy/eb/

@mikkopori custom timeouts are not supported and I'll add this as a feature request.

You have the following options to make it work today:
- Remove the EB deploy integration and directly use the cli in shippable.yml. 
- Use Pipelines to deploy to EB by using the runCLI job.

Let me know if you need an example of how you can deploy to EB using pipelines.

**Comment by manishas** [comment]
Here is a sample project showing how you can deploy to EB using runCLI: https://github.com/shippableSamples/java-ecr-runcli-elasticbeanstalk

**Comment by mikkopori** [comment]
I'll try running cli directly as my setup currently is too small to take the steps to use pipelines yet :)

**Comment by mikkopori** [comment]
boot_container took 33m 58s, do you have a different chain where to report performance issues? :)

**Comment by manishas** [comment]
@mikkopori if you are using images with the v5.3.2 tag, you should choose the 'v5.3.2' machine image in your subscription settings.

The v5.3.2 images are already on the machine image so boot container step won't need to pull the image.

**Comment by mikkopori** [comment]
When using the cli directly the problem are the credentials, can I somehow reference to them?

**Comment by mikkopori** [comment]
I guess I have to start building up the pipeline...

**Comment by ambarish2012** [comment]
@mikkopori that is correct. 

The sample demonstrates how to -

1. Create a cliconfig resource in a shippable.resources.yml [file](https://github.com/shippableSamples/java-ecr-runcli-elasticbeanstalk/blob/master/shippable.resources.yml).

2. Define a runCLI job in [shippable.jobs.yml](https://github.com/shippableSamples/java-ecr-runcli-elasticbeanstalk/blob/master/shippable.jobs.yml) to run your cli scripts by using the cliConfig resource.

You will need to create a cliConfig integration before getting to step 1, which is documented [here](http://docs.shippable.com/pipelines/resources/cliConfig/)

**Comment by mikkopori** [comment]
Okay, tried that, but for some reason the deployment is not triggered:
https://app.shippable.com/github/mikkopori/enterlot/runs/400/1/console

What must I be doing wrong?

**Comment by ambarish2012** [comment]
@mikkopori you will need to create a sync repository - which is a source control repository that contains your pipeline configuration files. The steps for running a pipeline are very different from running a CI build job. 

This [doc](http://docs.shippable.com/pipelines/gettingStarted/#seedPipeline) will explain all the steps needed to setup your sync repository and get your pipeline going.

**Comment by mikkopori** [comment]
Okay, tried that, something strange, selection for branches is empty and I cannot therefore save the sync repo. Should I create a branch specifically for this or?

**Comment by ambarish2012** [comment]
That's odd - are you not seeing the master branch?

**Comment by mikkopori** [comment]
Nope..

**Comment by ambarish2012** [comment]
@mikkopori for my clarification, you selected a subscription and a project in the Add resource popup after clicking the + button in the pipelines UI for the subscription and did not see any branches. 

Did you see the loading animation after selecting the project, when the UI fetches the branches for the project?

One thing you could do is go to account settings and click on Sync and then retry. If that does not work, we will probably have to get into a google hangout call to debug further.

**Comment by mikkopori** [comment]
![screenshot from 2017-04-01 00-54-10](https://cloud.githubusercontent.com/assets/14071201/24570717/c9d0cf8a-1675-11e7-960a-fd6c62f840ac.png)

Yes, this is what I get..

Yes, I saw the loading animation. Sync did not help.

Also tried another browser, but the same effect.

**Comment by ambarish2012** [comment]
@mikkopori you already have a sync repo for that repository and I think i can see it in your pipeline UI. You can run that pipeline.

**Comment by mikkopori** [comment]
okay, tnx, running now..

**Comment by mikkopori** [comment]
Okay, the deployment or as far as I can see the pipeline is still not triggered, what should I do differently?

**Comment by mikkopori** [comment]
@ambarish2012 any update on this? Can you please help me on what I'm still doing wrong?

**Comment by ambarish2012** [comment]
@mikkopori there is a syntax error in your yml file.

Failed to parse YML content for fileName: shippable.resources.yml. { [YAMLException: bad indentation of a mapping entry at line 2, column 9:
        type: cliConfig
            ^]
  name: 'YAMLException',
  reason: 'bad indentation of a mapping entry',
  mark: 
   Mark {
     name: null,
     buffer: '- name: awscli\n    type: cliConfig\n    integration: aws\n    pointer:\n      region: eu-west-1\n\u0000',
     position: 23,
     line: 1,
     column: 8 },
  message: 'bad indentation of a mapping entry at line 2, column 9:\n        type: cliConfig\n            ^' }

The way I figured this out is in your pipeline, i clicked on the rSync box, which navigated me to the console. A Red color code indicates an error. From the console, I could easily figure out the error.

After you fix the YML error, look at the rSync box, it should turn green.

**Comment by mikkopori** [comment]
Ahh, I did ot realise it works that way! Thank you, running now. Let's see.

**Comment by mikkopori** [comment]
Okay, moving forward, now I'm running into "deploy_aws dependency has been deleted from the yml or has no versions" but I have it shippable.jobs.yml. What must I be doing wron this time?

**Comment by ambarish2012** [comment]
@mikkopori I will need to look at your shippable.jobs.yml and shippable.resources.yml to debug this issue. Please can you email these files to ambarish@shippable.com.

**Comment by mikkopori** [comment]
Yes I will. Thank you.

**Comment by mikkopori** [comment]
Got help via email. got forward. Closing this and opening a new one for the next issue. Thank you.
