### ISSUE TITLE
Changelog mentions packer integration, but docs don't

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3485]
https://github.com/Shippable/support/wiki/5-2-3

There is mention of packer, but no mention of packer on the linkes integrations page. Which is kinda weird :)

**Comment by ambarish2012** [comment]
@bbrala we are addressing this issue in our docs update, thanks for reporting it.

**Comment by bbrala** [comment]
Any ETA on this? "Our docs update" is a bit vague :)

**Comment by ambarish2012** [comment]
@bbrala I can point you to a sample that uses packer, but I don't have a specific date to share for or docs update that we are actively working on.

**Comment by bbrala** [comment]
Well, i was trying to get packer working, but it doesnt want to build my image in the `ci` and `pre_ci` tag. 

https://app.shippable.com/bitbucket/swisnl/swisdev-packer
