### ISSUE TITLE
Support for Azure CaaS deployments

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#3487]
Hi,

We are using Shippable with multiple projects, deploying on AWS CaaS and it works pretty well. We are now investigating Azure CaaS. I remember seeing some Azure documentation a while ago but nothing anymore surrounding Azure.

So, are you supporting Azure deployment? and if not, when are you planning to do so>

thanks

**Comment by ambarish2012** [comment]
@Kirtap we are tracking support for Azure CaaS in our backlog. As soon as we finalize the release details, I will share them with you.

**Comment by avinci** [comment]
this is not resolved. We need to make sure we track this as a feature request.

**Comment by Kirtap** [comment]
Any timeline on this? Also since Azure can use Docker Swarm or DC/OS (meso) for orchestration. any preference on which one you will tackle first? Personally, i would vote for DC/OS with Meso

**Comment by manishas** [comment]
We are actively working on DC/OS and this should be available in the next couple of weeks. We'll let you know as soon as it's launched.

**Comment by manishas** [comment]
@Kirtap we've added Azure as an integration and here is a sample project that deploys to Azure: https://github.com/jatindogra/sample_azure/tree/docs

We're revamping docs and this will be included in the new docs with a step by step tutorial. However, wanted to let you know in case you want to play around with the integration.

**Comment by Kirtap** [comment]
Many thanks Manisha


Sent from my Bell Samsung device over Canada's largest network.
-------- Original message --------From: Manisha <notifications@github.com> Date: 2017-05-09  1:24 AM  (GMT-05:00) To: Shippable/support <support@noreply.github.com> Cc: Kirtap <pcarriere@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Shippable/support] Support for Azure CaaS deployments (#3487) 
@Kirtap we've added Azure as an integration and here is a sample project that deploys to Azure: https://github.com/jatindogra/sample_azure/tree/docs
We're revamping docs and this will be included in the new docs with a step by step tutorial. However, wanted to let you know in case you want to play around with the integration.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Shippable/support","title":"Shippable/support","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Shippable/support"}},"updates":{"snippets":[{"icon":"PERSON","message":"@manishas in #3487: @Kirtap we've added Azure as an integration and here is a sample project that deploys to Azure: https://github.com/jatindogra/sample_azure/tree/docs\r\n\r\nWe're revamping docs and this will be included in the new docs with a step by step tutorial. However, wanted to let you know in case you want to play around with the integration. "}],"action":{"name":"View Issue","url":"https://github.com/Shippable/support/issues/3487#issuecomment-300064418"}}}

**Comment by ambarish2012** [comment]
@Kirtap I am closing this issue. If you run into any issues deploying to Azure, please open a new issue and we will help you work through it.
