### ISSUE TITLE
Changing default branch for remotely initiated builds

### ISSUE THREAD

**Issue by elmpp** [Shippable/support#3488]
This appears quite similar to the previous issue here - https://github.com/Shippable/support/issues/248

I can see that initiating a build remotely through the "newBuilds" api call should behave as directed within the shippable.yml file. 
However, i am unable to make shippable aware of a change to my intended "default" branch.
I have added the same section (below) to all branches of the project in bitbucket and have triggered both "clear cache" and "sync project" multiple times.

```
branches:
  only:
    - dev
```

Whenever i then initiate a build (e.g. https://api.shippable.com/projects/58df746f512fbf07003fe1e1/newBuild) it results in a broken build due to the branch not being allowed - e.g. https://app.shippable.com/bitbucket/alanpartridge/docker-images/runs/81/1/console

The expected behaviour should seemingly be that a remote api newBuild triggers a build against the branches specified in the yml. The branch from which this yml is read becomes a bit tricky obvs (this is why i have ensured all my project branch shippables.yml have the same `branches`)

**Comment by elmpp** [comment]
I may add also however that the addition of the `branches` yml has resulted in correct behaviour following commits (i.e. commits to only 'dev' result in a build)

**Comment by elmpp** [comment]
I am still at a loss as to how to adjust the default branch that is built via a remote API call. Don't quite know why this was resolved??

**Comment by trriplejay** [comment]
The default branch we use is based on the default branch setting from the source control, so if `dev` was your default branch, then calling the `/newBuild` route would trigger that branch.  You should be able to adjust this setting in your repository settings on the source control provider.

You can also give a branch in the post body of the request:
```
{
  branchName: "dev"
}
```

**Comment by elmpp** [comment]
The branchname attr is very helpful. Don't think it is documented. Thanks
