### ISSUE TITLE
[Pipeline Jobs - deploy] I am not able to cancel Shippable jobs from the SPOG

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3489]
I am trying to cancel Jobs running as I found that the Job configuration has some issues.

I would like to cancel the Job similar to the option that I have on the CI

**Comment by Bharath92** [comment]
We do not have the ability to stop pipeline deploy jobs yet. We have already added this into our backlog as a feature request.

 Closing as this is similar to #3476
