### ISSUE TITLE
id:4011 postResource error

### ISSUE THREAD

**Issue by capablaza** [Shippable/support#3490]
Hi guys i have the next error when i try enable my web project.

(Id: 4011) postResource failed for sourceName: mxitechnologies/lp-web returned error resources.create failed with error: Validation error
verbose: projects|enableById|callerId:582b43112179161000dd929f|projectId:58dbfb46cd6d820800ef9b58|_createCIRepoResource

Please maybe have a document about the error description.
thanks

**Comment by ambarish2012** [comment]
@capablaza Please can you share a link to your console.

**Comment by capablaza** [comment]
Sorry, but  i haven't this link. However, the problem is when i try enable the project, not yet will running

**Comment by ambarish2012** [comment]
@capablaza there is another lp-web project that is already enabled in your account. Did you remove and add this project from your bitbucket account?

**Comment by ambarish2012** [comment]
@capablaza We have cleaned up the stale resources for your project, you should be able to enable the project in the dashboard now.

**Comment by ambarish2012** [comment]
In the future if you are deleting and adding back the same repository to your bitbucket account, after deleting the repository, you would delete the project from the dashboard prior to adding it back. Thanks.
