### ISSUE TITLE
Build Stuck on Provisioning Job Node

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3491]
Our builds have been working quite reliably for the past couple of months. 

Today though, I'm seeing our build stall at 'Provisioning Job Node'.

Some help as quickly as possible would be appreciated. I'm supposed to be demonstrating a new feature to a client, but I need this to work for deployment. 

Thanks.

![screen shot 2017-04-04 at 12 34 35 pm](https://cloud.githubusercontent.com/assets/1018189/24668085/a06c6864-1933-11e7-9489-0eec3c78f4eb.png)

**Comment by ryan-kimber** [comment]
Our other projects are having the same issue.

**Comment by trriplejay** [comment]
looks like your nodes stopped picking up builds for some reason. I see you're adding a new one, so that should start running builds once the intialization is complete. please let us know if you continue to see problems.

**Comment by ryan-kimber** [comment]
Yes, I deleted my nodes and added a new one. It seems to be working correctly.

Have other customers had to recreate their nodes recently for some reason?

**Comment by trriplejay** [comment]
a couple users reported errors during node reset, but we haven't seen nodes that just stop picking up the builds like yours did. Do you know when you last initialized those nodes? it may have had something to do with the agent being out of date, or it could have been related to something on the machines themselves... like some kind of docker error preventing the agent from starting.  If you still have access to the old machines you can check the docker logs to see if there are any errors.

**Comment by ryan-kimber** [comment]
It was a while back - they were probably last initialized, I'm guessing,
November.
