### ISSUE TITLE
Multiple tests

### ISSUE THREAD

**Issue by rrrkren** [Shippable/support#3492]
We are using shippable to do automatic testing of our rails app. We have two separate tasks for frontend and backend testing. 
`rake test` invokes backend testing with MiniSpec
`rake teaspoon` invokes frontend testing with teaspoon. 
Both test frameworks outputs result to the shippable results directory.
The problem is that whenever backend test fails, the frontend tests are not run at all. Is there any way around this?
Also, is there a way to distinguish the two tests on the shippable UI?

**Comment by ambarish2012** [comment]
@rrrkren 

1. To continue to run your subsequent tests on failure of your previous tests,  add || true to your task. This will force the exit code of your task code to be set to 0 when the task fails and Shippable will continue to run the next set of tasks in your YML.

For example, in your specific case do this - rake test || true.

2. There is a way to distinguish the two tests on the Shippable UI. If you follow this approach, your tests will run independently regardless of failure and you won't need to use the approach i suggested above.

The specific technique is called matrix builds - this [document](http://docs.shippable.com/ci/advancedOptions/matrixBuilds/) explains the details of the various mechanisms by which you can matrix (run multiple instances of your build with different config) your build.

Here is an example YML file that mirrors what you are trying to do, albeit in python.

language: python

python:
  - 2.7
  
env:
  - TEST_TO_RUN="test.py"
  - TEST_TO_RUN="test2.py"

build: 
  ci:
    - pip install -r requirements.txt 
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - nosetests $TEST_TO_RUN --with-xunit --xunit-file=shippable/testresults/nosetests.xml
    - which python && coverage run --branch $TEST_TO_RUN
    - which python && coverage xml -o shippable/codecoverage/coverage.xml $TEST_TO_RUN

Here we use the Environment variable matrix build technique and we specific two different tasks in the the same environment variable. You can specify tasks such as "rake test" or scripts to run such as "test.py" in the environment variable.

You would specify rake test and rake teaspoon in your environment variable to run those tests independently.

**Comment by rrrkren** [comment]
@ambarish2012 thanks! the matrix builds are quite neat, I should have looked through the docs more thoroughly :)
