### ISSUE TITLE
Does Shippable support Windows OS anyhow?

### ISSUE THREAD

**Issue by Neal910** [Shippable/support#3494]
### Description of your issue:
As our product requires multiple browsers support, Chrome, Firefox and IE11 especially, I need to enable IE 11 selenium webdriver end to end testing. Running Chrome and Firefox is much easier by using runCI task in Shippable with docker container in Linux. However, IE 11 is the issue since it seems no way to create a docker container with IE 11 running in Ubuntu system. 

- NOTE: [Those docker containers](https://hub.docker.com/u/microsoft/) are only runnable in Windows docker engine.

### Therefore, my questions would be:
1. Can Shippable also provide me with a Windows OS CI node to run my microsoft containers there?
2. If Shippable cannot support Windows OS, can you add a selenium IE service in CI? It seems Shippable only has [Chrome and Firefox](http://docs.shippable.com/ci/services/selenium/)?

Another reference: https://github.com/Microsoft/Virtualization-Documentation/issues/214

**Comment by ambarish2012** [comment]
@Neal910 Supporting microsoft containers and selenium IE service is on our roadmap.

**Comment by Neal910** [comment]
@ambarish2012 , that is great, thank you very much.

**Comment by ambarish2012** [comment]
@Neal910 we have added support for azure DC/OS integration.

http://docs.shippable.com/reference/int-azure-dcos/#azure-dc/os-integration

Search our docs for Azure and you will find a bunch of docs on Azure container support.

**Comment by Neal910** [comment]
Hi @ambarish2012 ,Thanks a lot for the update. 
As I haven't used Azure before and I just had a glance on this tool, I am still not sure how this integration can answer my question. 

But let me guess what you are thinking with this integration tool can help my situation:
I need to deploy my selenium grid IE browser on this Azure platform, then from Shippable CI build, I can call this deployed browser to test the server deployed on AWS?

Please guide me more in details or direction. Thanks.

**Comment by ambarish2012** [comment]
@Neal910 Sorry, I completely forgot you wanted to run IE/Selenium. This is not possible with DC/OS or even with Windows containers today based on the documentation I read. Until and unless Windows 10 or Windows server containers support IE edge, it will not be possible for us to support this scenario.

**Comment by Neal910** [comment]
>  Until and unless Windows 10 or Windows server containers support IE edge, it will not be possible for us to support this scenario.
Do you mean you have Windows 10 container but don't support IE edge yet? IE 10 is good enough BTW.

**Comment by seniorquico** [comment]
@ambarish2012 IE/Selenium aside, is there a general timeline for Windows container support?

#457 and #4 seem related in the general case.

**Comment by ambarish2012** [comment]
@Neal910 @seniorquico we don't have a timeline to share yet for windows container support.

**Comment by ambarish2012** [comment]
@Neal910  we have added support for on-demand Windows nodes. 

To create the node, go to your billing page and create the Windows Server 2016 on-demand SKU as indicated in the screenshot below.

<img width="1166" alt="screen shot 2018-04-02 at 11 53 32 am" src="https://user-images.githubusercontent.com/26096758/38210596-b88ec94e-366c-11e8-837d-a7b1c1dd7cae.png">
