### ISSUE TITLE
Customize kube-deploy job

### ISSUE THREAD

**Issue by vkamra** [Shippable/support#3495]
### Description of your issue:
We currently use the kube-deploy job to deploy in our Kubernetes cluster. I'd like to be able to specify what the deployment name and selector labels should look like for the deployed services so I can create Kubernetes services that reference these. Is there a way to override the kube-deploy defaults?

**Comment by ambarish2012** [comment]
@vkamra we are investigating.

**Comment by trriplejay** [comment]
@vkamra our managed deploy task uses a combination of the pipeline job name plus a unique ID to name the deployment object.  We're investigating ways to make this more readable and predictable, but for now that cannot be customized.

Labels also cannot be customized at this time, but we are planning to support that in an upcoming release.

Today, we always set two labels in the deployment object:
- "shippable.jobName"
- "shippable.deploymentName"

the job name is taken straight from your yml, while the deployment name is the job name plus a unique ID.

**Comment by ambarish2012** [comment]
@vkamra We are tracking this issue in our backlog. Thanks for reporting it.

**Comment by ambarish2012** [comment]
@vkamra while we address the issue you have reported, the other alternative is to use [runCLI](http://docs.shippable.com/pipelines/jobs/runCLI/) job to manage these details directly. 

The runCLI job gives you a tremendous amount of flexibility but requires you to handle all the scripting tasks.

In this [sample](https://github.com/shippableSamples/node-dockerhub-runcli-kubernetes-kubectl), you will see one example on how you could do this with a kubernetes cluster.

**Comment by vkamra** [comment]
Thanks @ambarish2012 and @trriplejay . I've been able to get things working for us by customizing the deploy job name and leveraging how that's used by kube-deploy script.

The sample you pointed me to is useful and I anticipate us moving to that shortly.

**Comment by ambarish2012** [comment]
@vkamra I am closing this issue since you are moving to the kube-deploy script. We have also fixed the bug and the fix should be in PROD in our next release.
