### ISSUE TITLE
Set correct docker DNS settings for BYON's.

### ISSUE THREAD

**Issue by rlennox-bauer** [Shippable/support#3496]
We are running a shippable BYON's succesfully apart from one issue. 

During a pipeline test stage, we need to correctly resolve a set of internal DNS names (i.e. *.internal). The current setup of a BYON sets the running docker options to be 

`SHIPPABLE_DOCKER_OPTS='DOCKER_OPTS="$DOCKER_OPTS -H unix:///var/run/docker.sock -g=/data --storage-driver aufs --dns 8.8.8.8 --dns 8.8.4.4"'`

This is setting the dns resolver to be google, not our internal EC2 DNS server (in our case this is 10.202.0.2). This means our internal test steps are failing due to the inability to resolve internal URL's. 

We have fixed this manually for the moment by manually editing /etc/default/docker on the BYON's and setting the following docker options and restarting the docker daemon.

`DOCKER_OPTS="$DOCKER_OPTS -H unix:///var/run/docker.sock -g=/data --storage-driver aufs --dns 8.8.8.8 --dns 8.8.4.4 --dns 10.202.0.2 `

We are unable to set the right DOCKER_OPTS during the server build (cloudinit) because the docker default file is overridden by the shippable BYON init scripts and there is no way to hook into the shippable init script currently without manually running it (which we don't particularly want to do).  

It's not clear to use why the SHIPPABLE_DOCKER_OPTS needs to set the dns entries at all as removing the "--dns" entries correctly makes the docker daemon utilise the host DNS settings, which are correctly set on EC2 boot. 

Our thoughts are just updating the init scripts to remove the --dns settings entirely will work - but not sure what the impacts of that might be. Alternatively, we need a way to ensure that the docker daemon used on the BYON's is using the correct DNS settings.

**Comment by ambarish2012** [comment]
@rlennox-bauer I am adding this feature request to our backlog. Thanks!

**Comment by keen99** [comment]
just ran into this myself trying to ssh from a container on my BYON minion to internal infra.   

anyone running minions inside AWS trying to hit internal-only infra is going to hit this immediately.   shippable definitely shouldnt be overriding a node's DNS environment in BYON....

thanks to @rlennox-bauer for the workaround ideas.

**Comment by rlennox-bauer** [comment]
@ambarish2012 - do you have an update on this?

**Comment by ambarish2012** [comment]
@rlennox-bauer we no longer override docker options.
