### ISSUE TITLE
Firefox selenium stopped working on your standard node

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3497]
https://app.shippable.com/bitbucket/swisnl/frmwebbased/runs/934/1/console

The run dies on PhpUnit not finding the geckodriver. This broke without us really changing anything afaik.

**Comment by ambarish2012** [comment]
@bbrala I am investigating. There was an error launching Firefox - 

(process:391): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Mozilla Firefox 29.0

**Comment by bbrala** [comment]
Ok, thanks.

**Comment by ambarish2012** [comment]
@bbrala which version of gecko driver do you currently use? Did you change the gecko driver version recently?

The error is happening since you changed the machine image to version 5.4.1 which has selenium driver v3.0.1. The machine image that you were using earlier had selenium v2.52.0.

**Comment by bbrala** [comment]
I always assumed you installed a compatible firefox,selenium and drivers if you use your nodes and enable those services. 

But if you are using selenium 3 on your new nodes, then firefox 29 won't work afaik. There was quite some noise around that subject.

**Comment by ambarish2012** [comment]
Let me know if you need help with configuring your build to use the 2.52 version of selenium. Alternatively, if you want to move to the 3.x version, moving to the latest version of FF is recommended and you can specify the FF version in the yml.

**Comment by bbrala** [comment]
The documentation states max version is 25, that isn't correct then? 

For now i fixed it by moving the project to our own custom container which is also fine, even better maybe.
