### ISSUE TITLE
Service elasticsearch boot error, restarting...

### ISSUE THREAD

**Issue by HelainSchoonjans** [Shippable/support#3498]
It happens since this morning, the builds are stuck at the elasticsearch_start task:

> shippable_service elasticsearch start  
> ================= Starting Elasticsearch ===================
> 
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> Service elasticsearch boot error, restarting...
> 

Can you have a look at it? We are using the default shippable elasticsearch service.
Thanks.

**Comment by ambarish2012** [comment]
@HelainSchoonjans Please can you send a link to the console.

**Comment by HelainSchoonjans** [comment]
Here is a fresh one:
https://app.shippable.com/bitbucket/B2Boost/ng-server-plugin-mr-security/runs/37/1/console

**Comment by ambarish2012** [comment]
Thanks @HelainSchoonjans I am filing a bug for this issue.

**Comment by HelainSchoonjans** [comment]
We did a df -h:

> $ df -h
> Filesystem      Size  Used Avail Use% Mounted on
> udev            7.9G  8.0K  7.9G   1% /dev
> tmpfs           1.6G  384K  1.6G   1% /run
> /dev/xvda1       99G   89G  5.6G  95% /
> none            4.0K     0  4.0K   0% /sys/fs/cgroup
> none            5.0M     0  5.0M   0% /run/lock
> none            7.9G     0  7.9G   0% /run/shm
> none            100M     0  100M   0% /run/user

Since the /dev/xvda1 folder is full, we removed some of the docker images that are inside:
# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.9G  8.0K  7.9G   1% /dev
tmpfs           1.6G  384K  1.6G   1% /run
/dev/xvda1       99G   24G   71G  26% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            7.9G     0  7.9G   0% /run/shm
none            100M     0  100M   0% /run/user

The % use is now acceptable, but the node is still marked as stopped on the Shippable Gui, even after we restarted the node.

**Comment by mohit5it9** [comment]
Hi,
Do you mind removing the node and adding it back again?

**Comment by HelainSchoonjans** [comment]
Hello mohit5it9,

We removed the node and added it back, but Elasticsearch still does not boot... We are worried, as it is affecting our ability to deploy production releases.

Here is a fresh console with this issue: https://app.shippable.com/bitbucket/B2Boost/backend-isfe-app/runs/219/1/console

**Comment by mohit5it9** [comment]
Hi @HelainSchoonjans ,
Elasticsearch on newer machine images(v5.3.2 and v5.4.1) are incomptible with java 1.7. Please switch to higher version of Java or switch back to Stable/Unstable image.

**Comment by ambarish2012** [comment]
@HelainSchoonjans just an FYI - v5.x version of elastic search ships on images v5.4.1 onwards.

**Comment by HelainSchoonjans** [comment]
I would want to use the elasticsearchy 1.7.5 version in my builds, is there a way to choose a specific version in the shippable.yml?

**Comment by ambarish2012** [comment]
@HelainSchoonjans choosing a specific version of elasticsearch is not supported.
