### ISSUE TITLE
All subscription data and history of account is missing.

### ISSUE THREAD

**Issue by vrajroham** [Shippable/support#3499]
### Description of your issue:
My all subscriptions are being missing with it's build history and all. I haven't changed any settings from original repo. Now no builds are being processed when I push to my repo. Following is the error snippet which I get on visiting  history links (browser history) when I try to visit old subscriptions.

    (Id: 4004) No projects found for projectId(s): 588b80695e71000f00186861, 
    58a1bdde8780e11000eaeb8b, 584119c833a1af1000ad70d4, 584119b2fed7c01000aec7e5
    verbose: /projects|GET|callerId:57f8c3462af6010f0058f2f1|validateProjects|_computeShim

![screenshot from 2017-04-06 16 00 03](https://cloud.githubusercontent.com/assets/12662173/24749832/2f835a30-1ae2-11e7-8986-fbc2b3a43067.png)

**Comment by kanthchandra** [comment]
Hi @vrajroham Can you please go to your account settings and sync your account and they see if it works?? If it doesn't work, we'll take a deeper look at this.

**Comment by vrajroham** [comment]
@kanthchandra I synchronized the account multiple times but no luck.

**Comment by kanthchandra** [comment]
@vrajroham would you mind giving me your accountId?

**Comment by vrajroham** [comment]
**Shippable ID** 57f8c3462af6010f0058f2f1

**Comment by kanthchandra** [comment]
@vrajroham are you sure that the token that you are using is a valid token? I mean the gitlab token that you have given in the account integration

**Comment by kanthchandra** [comment]
From our logs it looks like the token is invalid and as a result we are not able to sync your account. So the permissions for those projects do not exist on shippable. So if you update your account integration with a valid gitlab token and sync your account, you should be able to use shippable as before.

**Comment by vrajroham** [comment]
@kanthchandra  Thank you very much for your help! 

**Issue Resolved **

We didn't hit any settings in shippable and gitlab previously. Now as per your suggested steps for verifying Access Token we updated shippable integration with Gitlab token again and now everything works fine.

Thank You
