### ISSUE TITLE
ERROR: script_runner: Command failed

### ISSUE THREAD

**Issue by grouxsome** [Shippable/support#3500]
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy;ssh-add /tmp/ssh/GithubSSHKey; cd /root && /root/30394983-a082-466b-9906-44e7a60bec24.sh'
Exception Invalid or no script tags received
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy;ssh-add /tmp/ssh/GithubSSHKey; cd /root && /root/30394983-a082-466b-9906-44e7a60bec24.sh'

https://app.shippable.com/github/zenreach/WiFast-Base/runs/1955/1/console

**Comment by ambarish2012** [comment]
@grouxsome we are investigating.

**Comment by ambarish2012** [comment]
@grouxsome the error indicates that some task in your build_ci section exited abruptly.

The only difference I can tell between your current failed and past successful run is at this stage in your build.

Installing indices for smbsite.Trigger model
[CHANGE] someone@example.com            valid: True  -> False score: 0.50 -> 0.25 reason: 'test'   -> 'change'
RY R[DUN] someone@example.com            valid: True  -> False score: 0.50 -> 0.25 reason: 'test'   -> 'change'
{'good-header': 'good', 'content-length': 'good', 'content-type': 'good'}

017-03-22 19:56:30.094000+00:00 (2:19:41)>, <Visit: Visit (33:E1:49:CB:FA:A5): 2017-03-17 17:36:49.097000+00:00 -> 2017-03-17 21:26:19.097000+00:00 (3:49:30)>, <Visit: Visit 

At this point, your script is aborting abruptly.

**Comment by ambarish2012** [comment]
My suspicion is that Installing the indices for smbsite.Trigger model is causing a catastrophic crash.

**Comment by ambarish2012** [comment]
@grouxsome I am closing this issue, please reopen if you continue to see this problem.

**Comment by grouxsome** [comment]
Seeing this again on https://app.shippable.com/github/zenreach/WiFast-Base/runs/2204/1/console

This time while copying files...

**Comment by grouxsome** [comment]
Hi Ambarish

Seeing this again. Cannot re-open the issue but added comments:

Seeing this again on
https://app.shippable.com/github/zenreach/WiFast-Base/runs/2204/1/console

This time while copying files...


Thanks
