### ISSUE TITLE
elasticsearch 2.x support

### ISSUE THREAD

**Issue by jtaylor10** [Shippable/support#3501]
In need of elasticsearch 2.x support - since shippable is docker based this should be simple
Locally I run this prior to build:
docker run d --name elasticsearch -p9200:9200 -p9300:9300 elasticsearch:2

and everything is good to go. I tried to do this as part of my CI (not expecting it to work but why not try) and it doesn't work - I get connection issues after startup - I'm assuming the container can't get the required ports to work.

**Comment by ambarish2012** [comment]
@jtaylor10 Please can you send me a link to the build job console.

**Comment by ambarish2012** [comment]
@jtaylor10 Please take a look at this [doc](http://docs.shippable.com/ci/services/elasticSearch/) regarding how to use elastic search.

You will need to and add this block to your yml -

services:
  - elasticsearch

For more customizations, please see the doc.

**Comment by jtaylor10** [comment]
Yes, you have elasticsearch support but your docs say elastic search 1.x - Elastic search has 2.x and 5.x out - I need 2.x for my application so do you support 2.x and your docs are out of date? or is there a way to launch 2.x.

Would be great to do the following in my yml to control versions since it's a simple docker container launch I presume:

```
services:
  - elasticsearch:2
```

**Comment by ambarish2012** [comment]
We support elastic search 5.1.2 in our latest image [v5.4.1](http://docs.shippable.com/ci/machine-images/v5-4-1/). I will let you know as soon as we add support for 2.x.
