### ISSUE TITLE
PG::ConnectionBad: fe_sendauth: no password supplied

### ISSUE THREAD

**Issue by baelter** [Shippable/support#3503]
Can you assist in why my postgres connection is not working:

https://app.shippable.com/github/84codes/customer-core/runs/3/1/console

**Comment by cratz** [comment]
Did you tried to set it up like described in the docs:
```
services:
  - postgres
ci:
    - psql -c 'create role shippable with superuser;' -U postgres
```
http://docs.shippable.com/ci/services/postgreSQL/

**Comment by baelter** [comment]
This is my config

```
sudo: false
language: ruby
rvm:
  - 2.3.3
env:
- DATABASE_URL='postgres://localhost/customer-core-test'
before_install: gem install bundler -v 1.12.5
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
- psql -c 'create role shippable with superuser;' -U postgres
- psql -c 'create database "customer-core-test";' -U postgres
- rake db:migrate
```

And im using the env var `DATABASE_URL` in my migrate task

**Comment by cratz** [comment]
First try to remove `postgresql: "9.5"` from addons this is not working anymore at least not for us and we are also using ruby and we had this config until ~ 2 month ago. If you wanna start custom PG version check link from my first comment (section "Custom startup command")
Depending on you application config you should also specify more ENV vars for DB-user, DB-pwd and used database otherwise you application will not be able to connect to the database.
Also the DATABASE_URL depends on your application config and is may be wrong you should compare it with you dev / production environment.

**Comment by ambarish2012** [comment]
@baelter we support postgres version 9.6 in the v5.4.1 image that you are using. Multiple versions of postgres are not supported so you can remove the addons section like @cratz suggested.

If your rake scripts are using different credentials for accessing your database, you should put these settings in a config file in your repository (config/database.shippable.yml for example) and copy it over in the ci section:

build:
  ci:
    - cp config/database.shippable.yml config/database.yml

**Comment by ambarish2012** [comment]
@baelter I am closing this issue, please reopen if you continue to run into this problem.

**Comment by baelter** [comment]
Thanks! will try that

**Comment by baelter** [comment]
No luck

> If your rake scripts are using different credentials for accessing your database

What do you meen be different? What are the defaults?

**Comment by cratz** [comment]
Well I think @ambarish2012 was talking about how do you specify database credentials in your application. Common for rails applications is to setup this in a file `config/database.yml`. 
This depends on the setup of you application.

**Comment by baelter** [comment]
yes, but are there default credentials?

**Comment by cratz** [comment]
Yes and no ;)
Try this on shippable
```
host: localhost
database: customer-core-test
username: postgres
password: 
port: 5432
```

**Comment by baelter** [comment]
got it, thanks
