### ISSUE TITLE
Dont see subscriptions

### ISSUE THREAD

**Issue by szymczakk** [Shippable/support#3505]
Hi,

on dashboard there is written that I will find my subscription in those hamburger in top-left. But in my case  it's missing 

![image](https://cloud.githubusercontent.com/assets/8584646/24871030/99d0c7ae-1e18-11e7-96e9-caef3f9ec864.png)

Can you look at it why I can see it?

Or maybe if can you delete my account: (my shippable ID) 58ea03635ad03e06001a9316 and I will create new one, one more time 😉  ❓

**Comment by deepikasl** [comment]
@szymczakk  Can you please sync your account once? :)

**Comment by szymczakk** [comment]
Really... ❓  it was so easy ?! ehhhh.... soooory for problem. thank you 😃
