### ISSUE TITLE
Mogno failed to start in pre-ci script

### ISSUE THREAD

**Issue by jamesmoey** [Shippable/support#3506]
### Description of your issue:
Mongo failed to start in my pre-ci script.

Log from the mongo container
```
chown: cannot dereference '/proc/1/fd/1': Permission denied
chown: cannot dereference '/proc/1/fd/2': Permission denied
about to fork child process, waiting until server is ready for connections.
forked process: 17
ERROR: child process failed, exited with error number 1
```

- https://app.shippable.com/bitbucket/moeyservices/sentimentvoice-server/runs/189/1/console

**Comment by ambarish2012** [comment]
@jamesmoey you are running into a mongo db issue [154](https://github.com/docker-library/mongo/issues/154).

I suggest you try some of the workarounds suggested such as starting the container with --user mongodb.

**Comment by ambarish2012** [comment]
@jamesmoey I am closing this issue, please reopen if you continue to run into this problem.

**Comment by jamesmoey** [comment]
Hi,

I have tried putting --user mongodb and all the different suggested solution on that issue 154 ticket but the issue persist. MongoDB startup fine on the local, the issue is just in shippable environment.

James

**Comment by ambarish2012** [comment]
@jamesmoey we are investigating.
