### ISSUE TITLE
Add obsfusicated permalinks to all views

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3509]
Since a recent update Shippable now shows human readable titles in URLs of subscriptions and projects. While this is nice for internal usage, it is not really suitable for e.g. posting URLs of subscriptions and projects in public, e.g. on this issue tracker.

Thus it would be nice if there was a permalink button everywhere which would show URLs with the previous internal identifiers instead.

**Comment by mohit5it9** [comment]
Thanks for opening this issue and letting us know. We'll mark this as a feature request.

**Comment by rageshkrishna** [comment]
The ids for accounts, projects and subscriptions are now visible at the bottom corner of the page. I believe this serves the purpose of anonymizing things when reporting issues. Feel free to reopen the issue if you think differently.

**Comment by mbrodala** [comment]
I still cannot post clickable URLs this way but it works when mentioning _build N in project <hash>_.
