### ISSUE TITLE
Node stopped due to insufficient space.

### ISSUE THREAD

**Issue by HelainSchoonjans** [Shippable/support#3510]
Our team has two Shippable minions on Amazon. Noticing that our builds were launched one by one ( we are supposed to be able two parallel builds at once ), I did go on the https://app.shippable.com/subs/bitbucket/B2Boost/settings/nodes page and noticed that one node was stopped. Clicking on it I got the following message:

> Node stopped due to insufficient space.
>   The node has been stopped as disk usage exceeds 90%. Please free up disk space and reinitialize the node to allow builds to continue on this node.

On amazon however the node is running and green. Restarting it didn't change his stopped status on the Shippable interface.

**Comment by ambarish2012** [comment]
@HelainSchoonjans please can you run df -h on your Amazon node and send us the output.

**Comment by HelainSchoonjans** [comment]
We did a df -h:

> $ df -h
> Filesystem      Size  Used Avail Use% Mounted on
> udev            7.9G  8.0K  7.9G   1% /dev
> tmpfs           1.6G  384K  1.6G   1% /run
> /dev/xvda1       99G   89G  5.6G  95% /
> none            4.0K     0  4.0K   0% /sys/fs/cgroup
> none            5.0M     0  5.0M   0% /run/lock
> none            7.9G     0  7.9G   0% /run/shm
> none            100M     0  100M   0% /run/user

Since the /dev/xvda1 folder is full, we removed some of the docker images that are inside:

> $ df -h
> Filesystem      Size  Used Avail Use% Mounted on
> udev            7.9G  8.0K  7.9G   1% /dev
> tmpfs           1.6G  384K  1.6G   1% /run
> /dev/xvda1       99G   24G   71G  26% /
> none            4.0K     0  4.0K   0% /sys/fs/cgroup
> none            5.0M     0  5.0M   0% /run/lock
> none            7.9G     0  7.9G   0% /run/shm
> none            100M     0  100M   0% /run/user
> 

The % use is now acceptable, but the node is still marked as stopped on the Shippable Gui, even after we restarted the node.

**Comment by ambarish2012** [comment]
Thanks @HelainSchoonjans,  I am creating a bug for our engineering team to investigate.

**Comment by ambarish2012** [comment]
@HelainSchoonjans please try deleting the build node and adding it back, while we address this issue.

**Comment by HelainSchoonjans** [comment]
Deleting the node and adding it back solved the issue.

**Comment by shrivara** [comment]
Custom nodes which are stopped due to insufficient space can now be reset after freeing up space to make it start picking up builds again.
