### ISSUE TITLE
Build not finishing

### ISSUE THREAD

**Issue by herriojr** [Shippable/support#3515]
We keep running into an issue where a build which usually takes 5 minutes somehow gets "stuck" while running tests.  However, on further investigation, it appears that it is actually way past that.

The reason I know is because we spin up a docker-compose env and shut it down after the build succeeds or fails.  When I log onto the box, the docker-compose env is shut down but the logs on shippable still shows it as though tests are still being processed, which isn't the case.

https://app.shippable.com/github/upsidecommerce/backend-api/runs/658/1/console

A few things to note:

1. We run on our own hosted node
2. We haven't explicitly tried to get any updates from shippable (does this automatically happen when you run your own build node?)

**Comment by ambarish2012** [comment]
@herriojr I see this command at the end of your build run - PATCH /v1/reward_definitions/:id

My suspicion is that command is either hanging or taking a very long time to complete. Please can you check.

**Comment by herriojr** [comment]
Again, the logs are misleading.  The process is way past at this point as processing which happens further down the line has already happened (shutting down the docker-compose environment).  The logs just seem to be stuck in time.

**Comment by ambarish2012** [comment]
@herriojr Please look at [this](http://docs.shippable.com/integrations/notifications/email/) document regarding setting up email notifications for your builds.

**Comment by ambarish2012** [comment]
@herriojr I see this output from your last successful run -

/v1/rewards
    POST /v1/reward
      ✓ should create a valid basket reward (52ms)
      ✓ should be idempotent based on Reward ID (1090ms)
    GET /v1/reward/:rewardId
      ✓ should return not found when the reward does not exist
      ✓ should return a reward when the reward does exists (87ms)

In the build which is stuck, I see this in the logs -

  /v1/reward_definitions
    POST /v1/reward_definitions
      ✓ should create a valid reward definition
      ✓ should generate an ID if one is not provided
    PATCH /v1/reward_definitions/:id

What exactly is PATCH doing?

**Comment by herriojr** [comment]
making an http request to the service under test which in turn only accesses local resources (hence the docker-compose environment).

Ultimately, the reason I'm asking about whether hosting our own nodes gets updates is you guys had a bug at one point (which I had reported) which would hang everything due to a bug associated with how you guys were collecting the logs.

**Comment by ambarish2012** [comment]
@herriojr would it be possible for you to capture memory consumption during one stuck build run? 

We have addressed the problems underlying jobs stopping during periods of intense console output. I however don't see intense console logging in your specific case. 

I also am not 100% convinced your tests are completing. Is it possible for you to modify your scripts to write some state to the file system or some database after your tests complete? This would bypass logging and provide concrete proof around tests completing or hanging in PATCH.

**Comment by herriojr** [comment]
Sure, I'll post back when it gets stuck again.

But again, do you guys automatically update the images in use on our own hosted nodes when you guys fix things, or do we have to reinitialize a new box?

**Comment by ambarish2012** [comment]
@herriojr we do **not** automatically update hosted nodes. However, you can click on the reset button to update your nodes. 

If you chose the option of running scripts yourself when you configured hosted nodes, the reset button functionality is not offered. You will have delete and add the nodes back and rerun scripts if you chose that route.
