### ISSUE TITLE
Unable to install libsecret-1-dev

### ISSUE THREAD

**Issue by janekolszak** [Shippable/support#3516]
Hi there!

- Link to the build failure
https://app.shippable.com/bitbucket/janekolszak/wta-desktop/runs/8/1/console

- Scripts called from the yml (optional)
sudo apt-get install libglib2.0-dev libsecret-1-dev

It fails with:
```
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libglib2.0-dev : Depends: libglib2.0-0 (= 2.40.0-2) but 2.40.2-0ubuntu1 is to be installed
                  Depends: libglib2.0-bin (= 2.40.0-2) but it is not going to be installed
                  Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by ambarish2012** [comment]
@janekolszak please look at the suggestions here - https://unix.stackexchange.com/questions/203128/unmet-dependencies-when-trying-to-build-chromium-browser-on-ubuntu-14-04.

In pre_ci, add these commands before your apt-get command -

- sudo apt-get autoclean
- sudo apt-get autoremove
- sudo apt-get update
- sudo apt-get dist-upgrade

**Comment by janekolszak** [comment]
Hi,
This doesn't work. 
Maybe the pre-installed glib is installed manually?
