### ISSUE TITLE
runSh: common logic and IN execution order 

### ISSUE THREAD

**Issue by sample-sample** [Shippable/support#3517]
I've a deploy resource A and a runSh job with IN: A. Whenever A is triggered the TASK in .runSh is executed. I also have a similar setup for resource B with its runSh job and so on.  My shippable.jobs.yml now has N runSh jobs, one for each resource. 

I'd like to put all of this in a single .runSh job as most of the operations is the same. I'd also like to know which deploy resource executed this TASK. Is this possible?

The documentation says everything under steps is executed sequentially. So if I've two IN in my .runSh and both of them are running, it will wait for both of them to finish before running TASK?

**Comment by nranjanShippable** [comment]
Hi,
> I'd like to put all of this in a single .runSh job as most of the operations is the same. I'd also like to know which deploy resource executed this TASK. Is this possible?

You can check the `trace` tab listing all the resources / jobs for a particular job. The resource which will we the latest in `Created At` column is the resource that executed the TASK in the runSh job.

This is my pipeline having two resources for one runSh job:
![image](https://cloud.githubusercontent.com/assets/19686832/25086345/b91232b2-2384-11e7-9960-d3f2641263c4.png)

I just change ` trigger-dv-man-1` resource and this is latest:
![image](https://cloud.githubusercontent.com/assets/19686832/25086415/1658b0ae-2385-11e7-99e0-acedf59bc88d.png)


> So if I've two IN in my .runSh and both of them are running, it will wait for both of them to finish before running TASK?

No, it will not wait for both of them to finish before running the TASK. It executes as soon as one of them is finished. If you have two IN in your runSh job then it will be executed twice. 

Executed twice:
![image](https://cloud.githubusercontent.com/assets/19686832/25086454/6a0d1e7e-2385-11e7-96d4-841b04251d8c.png)

**Comment by nranjanShippable** [comment]
@sample-sample Please re-open this issue, if you have any more problem on this.

**Comment by sample-sample** [comment]
@nranjanShippable Thanks for your response. My first question was more to do with conditional execution. I don't want certain tasks to run for some jobs defined in IN.

Something like..
```
**jobs:

-name xyz
  steps:
  - IN: A
  - IN: B
  -TASK:
   -if A:
    - run this
   -if B:
    - run this**
```

This way, I can define one job instead of duplicating it several times.

**Comment by ambarish2012** [comment]
@sample-sample we do not have this capability currently, I will add this feature request to our product backlog.

**Comment by sample-sample** [comment]
Thanks for adding the request. I've few commands that I run specific to the job that triggers the task. I end up duplicating the entire setup for a single change. 

Appreciate the quick response and the awesome support.

**Comment by ambarish2012** [comment]
@sample-sample please could you email your job and resources yml file to ambarish@shippable.com, so that we understand your scenario.

**Comment by manishas** [comment]
This is scheduled to be deployed to production on Thursday 4/20.

**Comment by sample-sample** [comment]
Thanks!

**Comment by manishas** [comment]
Hmmm completely dropped the ball on updating this.

We have added a couple of environment variables that will help with your scenario:

JOB_TRIGGERED_BY_NAME contains name of the resource or job that triggered the current job
JOB_TRIGGERED_BY_ID  contains the ID of the resource or job that triggered the current job

You can set up your conditional workflow with the JOB_TRIGGERED_BY_NAME variable.
