### ISSUE TITLE
Build script failure

### ISSUE THREAD

**Issue by grouxsome** [Shippable/support#3519]
**PLEASE DO NOT CLOSE THIS WITHOUT CONSULTATION AS I CANNOT REOPEN TICKETS!!!!**

Seeing build script crashes again. Could not reopen previous issue (#3500). Please note this build completes both locally and when run manually on the build node image.

ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy;ssh-add /tmp/ssh/GithubSSHKey; cd /root && /root/3559504f-7ac2-44b7-a13e-5652a187101c.sh' Exception Invalid or no script tags received ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy;ssh-add /tmp/ssh/GithubSSHKey; cd /root && /root/3559504f-7ac2-44b7-a13e-5652a187101c.sh'

https://app.shippable.com/github/zenreach/WiFast-Base/runs/2204/1/console

**Comment by ambarish2012** [comment]
@grouxsome sounds good - will keep this ticket open to monitor your issue.

**Comment by ambarish2012** [comment]
@grouxsome just to pick up where we last left, are you reverting the copy command?

**Comment by grouxsome** [comment]
NO! We reverted on a SINGLE BRANCH to unblock development, but this copy
command NEEDS to go into production. I am going to instrument a build to
determine disk usage before the copy command.

**Comment by ambarish2012** [comment]
@grouxsome sounds good. I am looking into other possible causes of failure on my side.

**Comment by grouxsome** [comment]
Thank you! I have just confirmed disk space is not the issue. After the
build, before the copy command there is 40GB free. The static assets being
copy amount to about 150MB.

**Comment by ambarish2012** [comment]
@grouxsome the crash is most likely occurring due to intense console logging, an issue we have been actively investigating.

Until we find a solution for that issue, I recommend redirecting the output of the copy command either to /dev/null or a file.
