### ISSUE TITLE
Zenreach: Rsync job not triggered for the ops-pipeline repository

### ISSUE THREAD

**Issue by ambarish2012** [Shippable/support#3521]
### Description of your issue:
Rsync job is not triggered for commit SHA bc841b4320c4523e2dc8237ac027cec9994af653 in the ops-pipeline repository.

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by shrivara** [comment]
rSync will no longer be skipped if we fail to find previous SHA in the provider.
