### ISSUE TITLE
Unable to pull from Github

### ISSUE THREAD

**Issue by cschlegelmilch** [Shippable/support#3523]
My builds seems to have stopped pulling from github.  Not sure why.  I've reentered my token on the github account integration, but that doesn't seem to help.  Here is the specific error:

```ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git clone git@github.com:bucketduck/doobi.git /home/shippable/workspace/src/github.com/doobi' 3s  
Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
Cloning into '/home/shippable/workspace/src/github.com/doobi'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

retrying 1 of 3 times...
```

The failed build can be found [here](https://app.shippable.com/github/bucketduck/doobi/runs/325/1/console)

I'm not using any specific git integration for the subscription nor am I using custom ssh keys.  What can I do to re enable this?

**Comment by manishas** [comment]
@cschlegelmilch can you try resetting your project and see if that works?

Reset project is in project settings -> options -> reset project.

**Comment by cschlegelmilch** [comment]
Thanks @manishas .  That did it.
