### ISSUE TITLE
OpenJDK8 not working

### ISSUE THREAD

**Issue by rhenretta** [Shippable/support#3527]
I built a CI pipeline with an openjdk8 machine.  

See build here: https://app.shippable.com/github/GoodwayGroup/TagGenerator/runs/4/1/console

 build_ci 0s
  echo $JAVA_HOME 0s  
/usr/lib/jvm/java-8-openjdk-amd64

  whoami 0s  
root

  mvn install -f utils/ 0s  
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-8-openjdk-amd64/bin/java

openjdk7 gets past this point, but I can't compile this app with 7

**Comment by rhenretta** [comment]
I was able to make this work by adding 
- JAVA_HOME=/usr/lib/jvm/java-8-oracle
to the beginning of the CI steps.

Still a bug though

**Comment by ambarish2012** [comment]
@rhenretta thanks for finding the workaround. I will file a bug for openjdk8.

**Comment by ambarish2012** [comment]
@rhenretta openJDK 8 is supported in the v5.4.1 image. Please go to Subscription settings->Machine images and select the v5.4.1 image.

**Comment by athrane** [comment]
@ambarish2012 I experienced the same issue with my project (https://app.shippable.com/github/athrane/pineapple) and changing from using the stable image (5.5.1) to 5.4.1 resolved the issue. Two questions:
1) Where do I find information about which features is supported in a particular images?
2) What do I do if I want to use the stable image?
