### ISSUE TITLE
Error on project dashboard after moving project from github personal account to organization

### ISSUE THREAD

**Issue by rspitlerkb** [Shippable/support#3529]
I moved my repo from a personal github account to an organization.  After this move shippable nicely remembered all of my build history, but now when I click on the project on the subscription dashboard page to get to the project dashboard i get an error message and the project dash does not appear.

(Id: 4004) No subscriptions found for subscriptionId(s):[REDACTED]
verbose: /jobDependencies|GET|callerId:[REDACTED]|validateSubscriptions|_computeShim

**Comment by ambarish2012** [comment]
@rspitlerkb Please can you let me know which repo is having this problem.

**Comment by rspitlerkb** [comment]
Reactsocial/rest-api

**Comment by ambarish2012** [comment]
@rspitlerkb - I see a project called react-rest-api and not rest-api in your dashboard, please confirm.

**Comment by ambarish2012** [comment]
@rspitlerkb we are addressing the permissions issue in our backend. I will update this issue as soon as we are done.

I am also filing a bug for this issue.

**Comment by ambarish2012** [comment]
@rspitlerkb we have fixed the permissions issue - please can you let me know if the problem has been resolved.

**Comment by rspitlerkb** [comment]
working! thank you!
