### ISSUE TITLE
ElasticBeanstalk Deploy from Pipeline?

### ISSUE THREAD

**Issue by herriojr** [Shippable/support#3531]
I'm trying to use the pipeline feature and noticed that there is no mention of EB being a target for deployment for a deployment job. Is this correct, or is there a way to do this?

To be more specific, I am currently building a docker image and pushing up to S3 and registering the version with Elastic Beanstalk.  Now, I need to co-locate another docker image (both generated by ci and stored on a private dockerhub repo) on the same machine, so I thought Pipeline would be a good use-case for this as I can build a Dockerrun v2 with dependencies on both projects and deploy to EB. Unfortunately, it doesn't appear http://docs.shippable.com/pipelines/jobs/deploy/ is capable of this. Is the only other option to create another ci job which builds and deploys the dockerrun file based on a manifest?  If so, how do I get access to the manifest information within a ci job?

**Comment by herriojr** [comment]
http://blog.shippable.com/how-to-deploy-to-elastic-beanstalk-part-2 seems to mention that there is a way in the reference to part 3, but part 3 was never written.

**Comment by herriojr** [comment]
Duplicate of #3218

**Comment by ambarish2012** [comment]
@herriojr you can also look at this sample project, which deploys to elastic beanstalk  -https://github.com/shippableSamples/java-ecr-runcli-elasticbeanstalk.

**Comment by herriojr** [comment]
@ambarish2012 ty
