### ISSUE TITLE
Docs for ECS integration are inconsistent

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3534]
Hello!

I'm trying to implement deployment to my ECS cluster. I'm following this guide: http://blog.shippable.com/continuous-delivery-from-github-to-amazon-ecs.

In order to configure deployment I need to setup integration with ECS. There is an article for this: http://docs.shippable.com/integrations/containerServices/ecs/.

However, the article content seems inconsistent and some important details are missing from it.

1). It says `Step 1: Create a user with access to ECS resources`, however, the documentation for this step guides us to create a `Role` not a `User`.

2). Also, it says `Select New Role and add Role Name as: shippable-role-to-allow-ecs-access`, however, there is no input field for a role name at this point in AWS console.

3). And the most important part, I don't know what is `< shippable aws account id >` and `< users shippable account id >` mentioned and there is no additional explanation for it (at least I've failed to find it).

Could you elaborate please?

Also, I suggest to update this documentation article.

Side question, @manishas in your blog entry you suggest to create a separate branch called `pipelines` for deployment configuration. Is it necessary? May I store this configuration in `master` branch? Is it possible to move those configuration files from root of the project to a sub-directory, e.g. `shippable`?

Thank you!

**Comment by manishas** [comment]
@slavafomin you do not need a different branch... you can use `master`.

I'll let @trriplejay clarify the the other questions.

**Comment by slavafomin** [comment]
@manishas Also, the process of connecting CI with pipelines are different in your blog post and in this [documentation article](http://docs.shippable.com/tutorials/pipelines/connectingCiPipelines/). Why is that? What method is preferred?

Actually, I think method, mentioned in the docs are more straightforward and simple that the one mentioned in the blog post. What do you think?

**Comment by manishas** [comment]
The one in the docs is correct. The method mentioned in the blog post  was the old way and we are in the process of deprecating that. I'll update the blog this week.

The runCI job described in the docs makes CI a first class citizen within pipelines and you can use INs and OUTs for the runCI job just like you would with other pipeline jobs.

**Comment by trriplejay** [comment]
@slavafomin the docs are a bit confusing. There are two separate types of integrations we have for aws deployments: `aws` and `aws_iam`.  

With `aws`, you simply provide us with a key and secret for an account that has appropriate access to everything that you'd want it to do (all of the permissions described on that page)

With `aws_iam`, you're actually just creating a role, and then giving the Shippable account cross account permission to assume that role and make certain calls on your behalf.

If you start to create a new "Amazon Web Services (IAM) Integration" on the shippable account settings page, these fields: `externalId` and `AWS Account ID` will be filled in already, and those are the values you should use give cross account access on AWS when creating the role.

**Comment by ambarish2012** [comment]
@slavafomin I am closing this issue, please reopen if you run into other issues. We will address your feedback regarding documentation in the next version of docs, which we are working on currently.

**Comment by slavafomin** [comment]
Thanks!

**Comment by failpunk** [comment]
AWS Documentation for creating cross-account roles:
http://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html?icmpid=docs_iam_console
