### ISSUE TITLE
You do not have minions to run this job

### ISSUE THREAD

**Issue by AndriyPt** [Shippable/support#3537]
### You do not have minions to run this job. Please contact Shippable if you think this is a mistake.:
This is build 
https://app.shippable.com/github/shadow-robot/sr_common/runs/125/1/console
of the open source project https://github.com/shadow-robot/sr_common

I am getting this error `You do not have minions to run this job. Please contact Shippable if you think this is a mistake`
![image](https://cloud.githubusercontent.com/assets/10820297/25269504/9f908ee8-2685-11e7-8251-c360c2091443.png)

According to your pricing https://www.shippable.com/pricing.html it should be available for open source projects: `Unlimited builds for open source projects`.

Could you please check it?
Thank you in advance.

**Comment by ambarish2012** [comment]
@AndriyPt we are investigating.

**Comment by avinci** [comment]
@AndriyPt we get hammered by bitcoin miners and we have checks which are heuristics on our system that tries to flag suspicious activity. I apologize that this happened on your account. shadow robot was too fishy for our heuristic. I have added you to white list. 

Please let me know if this is back to normal for you.

**Comment by AndriyPt** [comment]
@avinci It is back to normal now. Thank you :)
