### ISSUE TITLE
php-fpm setup issue

### ISSUE THREAD

**Issue by loboallwyn1** [Shippable/support#3540]
Error while starting php-fpm
 ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm 0s  
[24-Apr-2017 10:42:24] ERROR: [pool www] cannot get gid for group 'nobody'
[24-Apr-2017 10:42:24] ERROR: FPM initialization failed

- Link to the build failure
https://app.shippable.com/bitbucket/vamaship/vamaweb/runs/9/1/console
- Scripts called from the yml (optional)

**Comment by ambarish2012** [comment]
Hi @loboallwyn1 , you might find suggestions on this link useful - https://groups.google.com/forum/#!topic/highload-php-en/GtvjLlbe_Bs.

If they doesn't work, please let us know, but I don't think this is a shippable issue at this point.

**Comment by loboallwyn1** [comment]
Thanks for pointing me in the right direction.
