### ISSUE TITLE
Please help migrate from event triggers to runCI

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3544]
https://app.shippable.com/subs/github/gitglacier/pipelines

I was going through your tutorial document on migrating event triggers (http://docs.shippable.com/tutorials/pipelines/migrateEventTrigger/) and I can't figure out how runCI will work with our pipelines from even a high level.

We are using docker-compose to build three images in our repo, then set off three triggers to tell pipelines that three images have changed. In the past I've tried to just change this to a single trigger, but then it fails to retrieve the other two images once they are created.

My question is: How do I tell runCI that three images are updated after my shippable.xml runs and builds them?

**Comment by gitglacier** [comment]
My first thought is to do something like this, please correct me if it sounds wrong:
```
build:
  ci:
    # your ci commands

    - echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/my_image1.env
    - echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/my_image2.env
    - echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/my_image3.env
```

**Comment by gitglacier** [comment]
I'm also not sure of how shippable.jobs.yml will look...?

**Comment by gitglacier** [comment]
Will the file shippable.triggers.yml be going away as part of this migration?

**Comment by manishas** [comment]
@gitglacier are you available to jump on a quick call? We can help you make the changes.

**Comment by gitglacier** [comment]
Sure. I've just sent a Google Hangout message to you.

**Comment by gitglacier** [comment]
Thanks for the help!
