### ISSUE TITLE
Briefly showing 47 years

### ISSUE THREAD

**Issue by gitglacier** [Shippable/support#3545]
![screenshot_2017-04-25_17-14-46](https://cloud.githubusercontent.com/assets/16925064/25411736/a126a432-29db-11e7-938b-bc3219897d4f.png)
I just noticed that the view is very quickly displaying "47 years" and being replaced with the actual time. Although it felt like 47 years today when we were waiting for it, I think this is a mistake. :-)

https://www.google.com/#q=angular+47+years

(Maybe ng-hide or ng-show until your time variable is not null?)

**Comment by ambarish2012** [comment]
@gitglacier thanks for reporting this issue - i will file a bug anyway.
