### ISSUE TITLE
Setting kubectl config (kubeconfig)

### ISSUE THREAD

**Issue by vkamra** [Shippable/support#3547]
### Description of your issue:
As recommended in #3495 , I'm using a runCLI job to run custom kubectl commands using [1] as a reference. 

I don't see where/how kubeconfig is being set in that sample though. What is the recommended approach here?

I am referencing my kubernetes cluster integration and I see the enviornment variables set appropriately.

[1]
https://github.com/shippableSamples/node-dockerhub-runcli-kubernetes-kubectl

**Comment by ambarish2012** [comment]
@vkamra kubeconfig is set in your kubernetes cluster integration, which you should create first in account integration (gear icon on the top right corner of your dashboard). Shippable authenticates using this configuration.

Are you running into any errors? You can specify as many contexts as you like in your kubernetes cluster integration and change contexts as needed.

**Comment by vkamra** [comment]
@ambarish2012 - I do have the kubernetes cluster integration created and referenced in the runCLI job (I see the environment variables set correctly with the kubeconfig content).

However, if I execute "kubectl config view" in the job [1], the config is empty. Does shippable correctly initialize this - I don't see where/how this happens.

[1]
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []

**Comment by vkamra** [comment]
I fixed this by manually specifying the kubeconfig extracted from the environment variables (my integration name is kube_cluster_playground) and that worked.

Is this a required step missing from the sample or is there some other step I'm missing?

`echo "${KUBECLUSTERPLAYGROUND_INTEGRATION_MASTERKUBECONFIGCONTENT}" >> ${KUBECLUSTER_PATH}/kubeconfig
export KUBECONFIG=${KUBECLUSTER_PATH}/kubeconfig
kubectl config view
`

**Comment by vkamra** [comment]
This was an issue on my side. I was referencing the kubernetes cluster integration via a "cluster" resource and not a "cliConfig" resource.
