### ISSUE TITLE
Remove Repository from Shippable after it has been deleted on Github

### ISSUE THREAD

**Issue by shadev** [Shippable/support#3551]
I removed a github repository and as it seems it cannot be removed from shippable. When clicking on Project | Settings | Delete the wheel spins forever and I get the following error:
```
(Id: 2002) getOwnerByProjectId failed for id:582cXXXX returned an errorOwner not found for projectId: 582cXXXX
warn: projects|disableById|callerId:57f6499XXX|projectId:582cXXX|_getValidOwner
```

**Comment by kanthchandra** [comment]
Hi @shadev can you please go to your account settings page and then sync your account so that we will sync your account and the project will be removed automatically.
