### ISSUE TITLE
Doing an npm publish and a git push.

### ISSUE THREAD

**Issue by zthun** [Shippable/support#3552]
I've been searching for a way to do this with shippable, but is there any support for doing an npm publish from a CI build?  

I also want to do a git push branch and git push --tags in my workflow.  Is this supported at all?  Basically, the workflow would be:

npm install
grunt
docker build
--RELEASE BRANCH ONLY---
git checkout release
npm version
git push origin release
git push origin --tags
npm publish --tag rc
docker push

Later on, I would also like to do this in my release pipeline
npm install (my-component-version)@rc
-- Read from the package.json what the rc version is and set it to version
npm dist-tag add (my-component-version)@(version) latest

Is any of the npm workflow possible right now?

**Comment by ambarish2012** [comment]
@zthun it should be possible. 

1) Please look at this sample to get started - https://github.com/devops-recipes/ci-push-docker-hub. It shows you how to author a shippable.yml file with some of the functionality you want in your CI build. You can riff off it and then customize it.

You can add npm push and git commands in the build section in your Shippable.yml file. The YML file for the sample above can be found in the repo [here](https://github.com/devops-recipes/ci-push-docker-hub/blob/master/shippable.yml).

2) We expose a ton of environment variables documented [here](http://docs.shippable.com/ci/advancedOptions/environmentVariables/). 

You can check $BRANCH for your release branch name. 
```
- >
     if [ "$BRANCH"  == "release" ]
     then
     fi
```

3) Also take a look at [this](https://github.com/Shippable/support/issues/3436) support issue.

**Comment by manishas** [comment]
@zthun to add to the points above, the following env will be especially relevant for you:

IS_RELEASE: Set to true if the build is triggered by a release webhook. If not, this will be set to false. 

IS_PRERELEASE: Set to true if the release is marked pre-release when it was published. If not, this will be set to false. 

RELEASED_AT: The timestamp when the release was published. 

RELEASE_NAME: The name of the release.

**Comment by manishas** [comment]
Let us know if you have any more questions. Closing.
