### ISSUE TITLE
Deploy job fails without meaningful error

### ISSUE THREAD

**Issue by grouxsome** [Shippable/support#3556]
### Description of your issue:
 wifast-demo-dev-deploy job is failing without any indication as to why. 

Starting Deployment for: wifast-demo-dev-deploy
Preparing manifests
Applying manifest overrides for wifast-demo-dev
Inside stepExec|managed|_common|compareManifests
Comparing manifests for wifast-demo-dev
Replicas match: true
Images match: false
Packages match: true
Top level docker options match: true
Summary of cluster: -- newlyAdded: 0, -- changed: 0, -- deleted: 0
Force deployment is: true
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Manifests removed: 0
Initialized AWS Adapter.
Deployment flow: serial
Executing deploy type: upgrade
getting previous service
Found previous service: wifast-demo-dev-deploy-wifast-demo-dev-3c0c00a0-dc26-4444-9680-ace0c1207b1f
creating container definition
Successfully created folder /build/state/wifast-demo-dev/
Successfully saved file ecs-service-definition.json
**Failed to deploy manifest for type: upgrade
Deployment failed for wifast-demo-dev
Deployment failed with error : true**

[buildJobConsoles.txt](https://github.com/Shippable/support/files/968257/buildJobConsoles.txt)

**Comment by manishas** [comment]
@trriplejay we need to look at this asap.

**Comment by grouxsome** [comment]
Thank you for the prompt response

I suspect the error may be to one or more of the following...
1) old service was on a different ECS cluster
2) pipeline was modified to use image links
3) pipeline was modified to pull an image form a public DockerHub repository

**Comment by trriplejay** [comment]
looks like a bug in how we create the container definitions. the `/udp` in your docker options is causing the error.  We don't currently support setting the "protocol" field in the port mapping.  I'll open a bug to handle the error better and add the support for protocol.

**Comment by grouxsome** [comment]
Is there a work around to set both a UDP and TCP port in the pipeline? If not, do we have a rough ETA for adding the support?

Thank-you!

**Comment by manishas** [comment]
@grouxsome we're working to add support for this and ETA is Thursday EOD.

**Comment by manishas** [comment]
This was deployed last week. Docs are still being updated, but you can specify protocol like this:

```
resources:
  - name: myDockerOptions                         
    type: dockerOptions                 
    version:
      portMappings:                        #optional
        - "80:80/udp"                         #hostPort:containerPort/protocol (udp | tcp)

```

**Comment by manishas** [comment]
Please let us know if it doesn't work as expected and we can reopen the issue. Thanks for your patience!
