### ISSUE TITLE
Support: Reciving Artifacts

### ISSUE THREAD

**Issue by NFGamerMC** [Shippable/support#3557]
#### Question?
Can you tell me how to define what files are artifacts in shippable, I want to be able to take a file and use it as an artifact

**Comment by ambarish2012** [comment]
@NFGamerMC please can you elaborate more on your scenario? Are you trying to download some of the files from a build?

**Comment by NFGamerMC** [comment]
@ambarish2012 What I would like is for me to have shippable find a certain file from the build and make it accessible as an artifact.

**Comment by NFGamerMC** [comment]
https://raw.githubusercontent.com/NFGamerMC/mcpe-default-addon/master/shippable.yml

**Comment by ambarish2012** [comment]
@NFGamerMC a couple of things -

1. I suggest you move to the new format of Shippable yml. You can look at this YML file as an example - https://github.com/devops-recipes/basic-node/blob/master/shippable.yml.

More information on the structure of our the latest YML format can be found [here](http://docs.shippable.com/ci/shippableyml/).

2. Regarding build artifacts, take a look at [this link](http://docs.shippable.com/ci/advancedOptions/artifacts/).

**Comment by NFGamerMC** [comment]
Yes, but I don't have Amazon S3

**Comment by ambarish2012** [comment]
@NFGamerMC where would you like to copy the build artifact to?

**Comment by ambarish2012** [comment]
@NFGamerMC to make things clear, we no longer support making build artifacts available for download from the Shippable console. You will have to copy them to your own cloud storage.

**Comment by NFGamerMC** [comment]
@ambarish2012 Do you know of any free ones?

**Comment by ambarish2012** [comment]
@NFGamerMC you can try AWS or Azure free tier.
