### ISSUE TITLE
[question] how can I make a JOB in the pipeline compulsory to be successful

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3559]
### Description of your issue:
Currently I have a shippable.jobs.yml file that has a release with multiple inputs. Some of this input are functional test that must PASS before the JOB can be trigger either manually or automatically.

![image](https://cloud.githubusercontent.com/assets/15203863/25606376/4e64e92e-2f54-11e7-9924-65ac23ac9222.png)

My expectation is for the Release Job to be disable if a previous Job has failed.

files are located at
https://gist.github.com/asanchezgiraldo/9e412ca41a13caed313659e13304dc95

**Comment by deepikasl** [comment]
@asanchezgiraldo Thanks for reporting this issue. Currently we doesn't support your requested flow. 
If you have multiple inputs to your release job. Your release job will be triggered for any of its input jobs version change.
I will add this as a `feature request` to our backlog.

**Comment by manishas** [comment]
@asanchezgiraldo we're looking into this scenario a little deeper and we might have a solution for you. I'll be back with an update soon.

**Comment by manishas** [comment]
@asanchezgiraldo spoke too soon. We need to fix a couple of things at our end for this :(

In the meantime,  Deepika's suggestion is the right way to handle this case.

**Comment by asanchezgiraldo** [comment]
@deepikasl @manishas thanks, at the moment we do have it ``` switch: off ```  but it will be great if there was an option like Mandatory JOBs or something like that

**Comment by asanchezgiraldo** [comment]
Hi @deepikasl @manishas any updates on this feature request?

**Comment by ambarish2012** [comment]
@asanchezgiraldo - we are planning our next release and I will update you shortly.

**Comment by ambarish2012** [comment]
@asanchezgiraldo we have started working on this feature and it will be available in our next release in the second week of July.

**Comment by ankul-shippable** [comment]
@asanchezgiraldo we have fixed this.
1. A job will not trigger if any of its IN jobs are in failed/cancelled/timeout state
2. A job will not trigger if any of its IN resource is in inconsistent state
3. Manually triggering the job will always trigger it irrespective of the state of IN resources/jobs.

You can find the docs [here](http://docs.shippable.com/reference/jobs-overview/#triggering-jobs).
Thanks

**Comment by ankul-shippable** [comment]
I am closing this issue now. Please reopen if you find any issues with this. Thanks
