### ISSUE TITLE
[question] Unable to delete a seed from the pipeline from SPOG

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3561]
### Description of your issue:
Currenlty I created my pipeline seed with the wrong integration, but I am not able delete this from the SPOG

https://app.shippable.com/subs/github/bauerxcelmedia/pipelines

**Comment by ambarish2012** [comment]
@asanchezgiraldo which integration are you trying to delete? Or are you trying to delete some other job / resource in the pipeline?

Also - please could you explain what you mean by "pipeline seed".

**Comment by asanchezgiraldo** [comment]
@ambarish2012 I am trying to delete shippable-pipeline_rSync

**Comment by ambarish2012** [comment]
@asanchezgiraldo I don't see it - I saw several rsync jobs which suffix with shippable-pipeline_rSync.

**Comment by asanchezgiraldo** [comment]
sorry i meant  module-service_shippable-pipeline_rSync 


![image](https://cloud.githubusercontent.com/assets/15203863/25647276/019930a4-3004-11e7-89ad-da656099064e.png)

**Comment by ambarish2012** [comment]
ok i deleted it - you have to right click on the CIRepo resource that connects to the RSync job (to the left of the rsync job) and click delete. The CIRepo resource refers to the repository that has the pipeline config and hence it is the one that has to be removed. The RSync job creates the resources and jobs specified in the yml files and is a virtual job in some sense.

This soft deletes the sync repo and rsync job. All soft deleted resources show in pink colored boxes at the very bottom of the SPOG (scroll all the way to the bottom). You can then hard delete  these jobs by right clicking on them and choosing remove.

I haven't hard deleted your Rsync job.
