### ISSUE TITLE
Shippable CI reinstalls dependencies in Custom Docker container 

### ISSUE THREAD

**Issue by Reagan** [Shippable/support#3562]
With a custom docker container that already contains a number of dependencies and uploaded to Docker Hub, Shippable is able to `docker pull` the container but subsequent test commands show that dependencies in the custom container still need to be reinstalled. 

Here's what I mean:

Here's an example Dockerfile: 

```python
FROM ubuntu:14.04
MAINTAINER ...

RUN DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get -y install python-numpy

ADD . /myapp
WORKDIR /myapp
          
RUN pip install bs4
```

On building this docker image, both `bs4` and `python-numpy` should be now be installed in the container. 
 
Here is a shippable.yml

```python
language: python

python:
  - 2.7

build:
  cache: true
  pre_ci:
    - docker pull ...
  ci:
    - export PYTHONPATH=./source_apps/:$PYTHONPATH
    - export LC_ALL="en_US.UTF-8"
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage
    - pip install  bs4
```

Notice that the shippable.yml is trying to reinstall the library `bs4`. My expectation is that the console output on shippable should show that `bs4` is already installed and skip over this installation. However, the console output shows that `bs4` is reinstalled again for each build even though the custom container has this dependency already.

**Comment by deepikasl** [comment]
@Reagan This needs to be done in `pre_ci_boot`.

`pre_ci` section is used primarily if you need to use a custom image for your build or if you need to customize behavior of the default CI container. Commands in this section run outside the CI container, so you should not include any commands required for your CI workflow here.

Can you add the installation part in `pre_ci_boot` section of your yml?
example:
```yaml
pre_ci_boot:
    image_name: $IMAGE_NAME
    image_tag: $IMAGE_TAG
    pull: $IMAGE_PULL
    options: '--privileged=true --net=bridge -e FOO=true -e BOO=false' 
```
Docs for more information on `pre_ci` and `pre_ci_boot`: [ci-shippableyml](http://docs.shippable.com/ci/shippableyml/)

**Comment by Reagan** [comment]
Thanks @deepikasl. That fixed it! Looking through the docs.

**Comment by deepikasl** [comment]
@Reagan  Thanks for the update. I will close this issue. Please re-open this issue if you have some problem.
