### ISSUE TITLE
shippable.yml alternative

### ISSUE THREAD

**Issue by aswath-veersoft** [Shippable/support#3564]
Is there an alternative to run the CI other than shippable.yml.
Reason:  The shippable.yml modifications has to be pushed, if we change the build configurations.  If we want a different build or small number tests has to be run, then shippable.yml should be modified.  
Sometimes we want more tests, and sometimes, we want small number of tests to be run for every commit.  Is this possible without modifying shippable.yml and pushing it.

**Comment by deepikasl** [comment]
@aswath-veersoft, shippable.yml is mandatory to run your CI builds as all configuration for CI happens through shippable.yml.
You have to modify your `shippable.yml` for the desired behavior of your run. :)

**Comment by manishas** [comment]
@aswath-veersoft let me think about your scenario and get back to you. 

Your requirement is this - you want to run a smaller test suite for some commits and a larger test suite for others. You don't want to change the yml file each time. 

Please correct me if I'm misunderstanding the scenario.

**Comment by aswath-veersoft** [comment]
Thats correct.

**Comment by deepikasl** [comment]
@aswath-veersoft we can actually do without modifying shippable.yml.
You always have access to your commit message in your ci as `$COMMIT_MESSAGE`.

Whenever you want to run full test suite just mention `full-test-suite` in the commit message. 
( here i have used `full-test-suite` as an example you can use anything).

And then configure your shippable.yml to read your commit message and execute full test suite if `full-test-suite` is present else execute smaller test suite if `full-test-suite` is not present.
you can parse and check whether your commit message has `full-test-suite` or not:
`if [[ $COMMIT_MESSAGE == *"full-test-suite"* ]]; then ..`
Example:
```yaml
build:
  ci:
    - if [[ $COMMIT_MESSAGE == *"full-test-suite"* ]]; then echo "run script of  full test suite"; fi
```

![screenshot from 2017-05-03 22 54 56](https://cloud.githubusercontent.com/assets/18304961/25673023/8ed2b608-3053-11e7-94a3-ba43efbafaeb.png)

Hope this helps. Please let me know if you have any concern.

**Comment by ambarish2012** [comment]
@aswath-veersoft please let us know if this is a viable solution for you.

**Comment by aswath-veersoft** [comment]
Seems like a alternative solution.    The shippable.yml needs to be committed in for syntax errors, logic etc, and if not correct, it needs to be committed again.  
Is there  a way to write the script on the server itself?  Snap-ci.com allows this.

**Comment by manishas** [comment]
The solution addresses your requirement of triggering different test suites without changing the yml.

As for syntax errors, we recommend using a yml validator like http://www.yamllint.com/. This won't find logic errors but will at least validate the syntax. Writing a yml is a one time thing and most folks want the config to live with their source code and be versioned. Usually, they create a branch and add the yml in there and when the config looks right, they merge it with their main branch.

That said, we definitely want to build a Shippable specific validator so the trial and error doesn't need multiple commits.

**Comment by Tarpan1007** [comment]
@manishas  : Please reply asap.
Thanks.

**Comment by trriplejay** [comment]
make sure the yml file is in the root of your repo. we only check the root directory for the shippable.yml file.
