### ISSUE TITLE
Is the projects:enableById endpoint available in the public API?

### ISSUE THREAD

**Issue by kartikluke** [Shippable/support#3565]
I'd like to automatically enable projects for specific repositories, is this API allowed for paid users?

**Comment by ambarish2012** [comment]
@kartikluke yes - you can call that API. We will also document it.

**Comment by kartikluke** [comment]
@ambarish2012 Yeah I tried it with my free key but got this error. This is because it isn't paid, correct?

`curl -X POST --header 'Accept: application/json' --header 'Authorization: <api-key>' 'https://api.shippable.com/projects/<project-id>/enable'`
```
{"logType":"warn","methodName":"/projects/:projectId/enable|POST|validateAccount|_computeShim","id":2000,"message":"access denied for route: /projects/:projectId/enable"}
```
