### ISSUE TITLE
Cannot run Sen2cor processor in SNAP application

### ISSUE THREAD

**Issue by JakubZeleny** [Shippable/support#3566]
Hello, 
 
i am having trouble processing my images in SNAP, sen2cor processor which runs under anaconda

i am having this message:

"D:\ProgramData\Anaconda2\Lib\site-packages\sen2cor-2.3.1-py2.7.egg\sen2cor/L2A_Process.py", line 7, in <module>
    from tables import *
ImportError: No module named tables

"no module named tables"

Please, what does it mean and what should i do? 

Thank you, Jakub

**Comment by ambarish2012** [comment]
@JakubZeleny is this is Shippable issue or a SNAP issue?

**Comment by JakubZeleny** [comment]
i am using SNAP, so it is a SNAP issue
