### ISSUE TITLE
Can I use secure env variables in my CD pipeline

### ISSUE THREAD

**Issue by vkamra** [Shippable/support#3567]
### Description of your issue:
I'm using the runCLI job type in my CD pipeline. I'd like to reference secure environment variables (AWS keys, that I'm also using in CI) here.

Can I do this and how would I specify these in a runCLI job?

**Comment by manishas** [comment]
@vkamra you can use a [params](http://docs.shippable.com/pipelines/resources/params/) resource as an input to your runCLI job.

**Comment by vkamra** [comment]
Ah great - thank you!

**Comment by manishas** [comment]
To follow up on that, the decrypted key-value pairs are available in your runCLI job scripts as environment variables.

For example, if you have encrypted foo=bar and your params resource is names myParams, the environment variable available in runCLI will be MYPARAMS_PARAMS_FOO.

**Comment by vkamra** [comment]
And assume the same resource name sanitization scheme applies? So if my encrypted var is AWS_SECRET_ACCESS_KEY=bar, and resource name is myparams, env variable will be MYPARAMS_PARAMS_AWS_SECRET_ACCESS_KEY ?

**Comment by manishas** [comment]
That sounds right... @trriplejay can confirm.

**Comment by ambarish2012** [comment]
@vkamra yes - please look at this sample as a reference - https://github.com/devops-recipes/test-api-nouvola.

**Comment by trriplejay** [comment]
yep, that's right.
