### ISSUE TITLE
getHooks failed when enabling sample project

### ISSUE THREAD

**Issue by Sha01in** [Shippable/support#3570]
I have forked your sample project.  When I enable, I get error:

(Id: 4005) getHooks failed for Sha01in/sampleNod
verbose: common|github|postWebHook:Sha01in/sampleNod|_getHooks
404
![shippableerror](https://cloud.githubusercontent.com/assets/3494200/25793779/ecd5effe-3382-11e7-849c-129ebc99becc.PNG)

**Comment by manishas** [comment]
Can you try again now? We're investigating a glitch in the service that happened several minutes ago and this could have been due to that.

**Comment by Sha01in** [comment]
This is working now.  Thank you.

**Comment by juliocanares** [comment]
@manishas I am still getting this error while trying to enable a gitlab project

**Comment by juliocanares** [comment]
![image](https://image.prntscr.com/image/El-6AwDcQ6CImk2lTjkS6w.png)

**Comment by ambarish2012** [comment]
@juliocanares please can you try this -

1. Go to your project -> settings.
2. Click on the reset button.

**Comment by juliocanares** [comment]
done, still not working

**Comment by ambarish2012** [comment]
@juliocanares please open a new ticket. Is your project hosted on gitlab.com or in your own environment?
