### ISSUE TITLE
Database Sync Build Failures

### ISSUE THREAD

**Issue by LoganArnett** [Shippable/support#3571]
### Description of your issue:
We are currently running a Node application with Hapijs, Postgresql, and Sequelize. Running our tests locally we are able to see that the database and models are constructed and the tests can run 100% of the time. On Shippable, we were getting the database to sync some of the time but other times failing but as the application has grown we now get failures 100% of the time. It appears that our Postgresql database has not synced with the data models prior to the tests running. This sync of the database occurs in our code on construction of the server in the test environment. So I am trying to find the disconnect between local and CI. Any help would be appreciated.

[**Build Failure Can Be Found Here**](https://app.shippable.com/github/MVRK-HQ/Authentication/runs/138/1/console)

**Comment by ambarish2012** [comment]
@LoganArnett - need some clarifications. 

Which postgres database are you referring to - the test database created by Shippable that you have specified in your YML OR some other database?

**Comment by LoganArnett** [comment]
The one that is created in the YML. That is the one I am trying to connect to and sync with the models before running the test suite

**Comment by ambarish2012** [comment]
Where exactly does the sync happen before you execute npm run test-ci? Which specific command do you execute in the Shippable yml to initiate the sync?

I am not seeing any log messages in the console regarding the sync. If you can add some logging before and after the data models are sync'ed, it would help with the debugging.

**Comment by LoganArnett** [comment]
Thanks @ambarish2012 for reaching out, I was able to diagnose the issue through a rabbit hole of console.logs and was able to track it back to an unexpected behavior or Hapi's `server.inject` method
