### ISSUE TITLE
project has inconsistent state

### ISSUE THREAD

**Issue by rvdwijngaard** [Shippable/support#3572]
Hi, 

I followed the steps described in this [tutorial](http://blog.shippable.com/setup-nightly-builds-on-shippable); I configured a nightly build for one of my projects. For some reason one of my projects is now in an inconsistent state; As a result I cannot get the nightly builds working and this project does not build anymore. Please advice. 

https://app.shippable.com/bitbucket/to-increase/dashboard-service/runs/147/1/console

Cheers, 
Ron

**Comment by ambarish2012** [comment]
@rvdwijngaard we are investigating.

**Comment by ambarish2012** [comment]
@rvdwijngaard we have set the state to consistent. Please let us know if the problem is resolved.

**Comment by rvdwijngaard** [comment]
yep it's resolved; thanks!
