### ISSUE TITLE
Installing from requirements.txt automatically

### ISSUE THREAD

**Issue by sample-sample** [Shippable/support#3573]
I see that the files in requirements.txt is being installed in the build_ci step even if it is not defined in my shippable.yml file.

  if [ -f $SHIPPABLE_BUILD_DIR/requirements.txt ]; then pip install -r $SHIPPABLE_BUILD_DIR/requirements.txt; fi

Is this the default behaviour? How do I turn this off?

**Comment by manishas** [comment]
Can you point me to your build link?

**Comment by sample-sample** [comment]
I've sent you an email with the link.

**Comment by manishas** [comment]
@sample-sample if you have an empty `ci` section, we run a default command as documented here: http://docs.shippable.com/ci/languages/python/#default-commands

To avoid this, just put some command in `ci`... even something simple like:

```
build:
  ci:
    - pwd

```

**Comment by sample-sample** [comment]
ah! ok. Thanks.
