### ISSUE TITLE
Cannot enable project located in Bitbucket team

### ISSUE THREAD

**Issue by qqilihq** [Shippable/support#3577]
I've just connected my Shippable account with Bitbucket and I would like to enable CI for a repository which I can access as a Bitbucket team member.

My Bitbucket team correctly shows up in the Subscriptions hamburger menu. However, I cannot enable the project, as the "Enable" button is simply missing. On the Bitbucket repositories which I directly own, the "Enable" button shows up.

Is this possible at all? Anything I'm missing?

**Comment by qqilihq** [comment]
Ok, I'm a step further now. I noticed that I need "write" privileges for the repository (I have created a dedicated Bitbucket user for Shippable, because the requested privileges seemed a bit "broad").

So, I enabled "write" access for the user and the "Enable" button shows up.

However, when I click "Enable", I get the following error:

```
(Id: 2002) getOwnerByProjectId failed for id: xxxxxxxxxxxxxxxxxxxxxxxx returned error: Owner not found for projectId: xxxxxxxxxxxxxxxxxxxxxxxx
warn: projects|enableById|callerId:xxxxxxxxxxxxxxxxxxxxxxxx|projectId:xxxxxxxxxxxxxxxxxxxxxxxx|_getValidOwner
```

(I've obfuscated the actual IDs for the public ticket, but I'm happy to supply them to you, in case that's relevant).

**Comment by manishas** [comment]
@qqilihq we require that at least one admin for the repository needs to have signed in at some point in order for the repository to be enabled.

This is because write permissions aren't enough to create webhooks. When you enable a project, we automatically create webhooks, for which we need admin permissions.

**Comment by qqilihq** [comment]
@manishas Many thanks, setting privileges to "admin" worked fine!

Btw; can you tell me if it is okay to downgrade privileges to a lower level after initially setting up the project? Not to sound distrustful to you’re guys great work, but I just sleep better when I know that no third party service could wipe my entire repository :)

**Comment by ambarish2012** [comment]
@qqilihq you can downgrade the permission. However, please remember that if you want to enable more projects, reset or remove an enabled project, you will need to temporarily grant admin permissions again.
