### ISSUE TITLE
Cannot remove Slack integration

### ISSUE THREAD

**Issue by chuckphillips** [Shippable/support#3578]
I am trying to remove the Slack integration from our account but am getting the following error:

```
(Id: <ID>) accountIntegrations.destroy failed for id:
verbose: accountIntegrations|deleteById|callerId:<ID>|accountIntegrationId:<ID>|_deleteById
"<ID> returned error: update or delete on table \"accountIntegrations\" violates foreign key constraint \"subscriptionIntegrations_accountIntegrationId_fkey\" on table \"subscriptionIntegrations\""
```

**Comment by kanthchandra** [comment]
Hi @chuckphillips , I looked into the scenario that you mentioned, it looks like you had added your account integration to a sub called `mindbody` and that subs still uses this slack integration. Please delete that subscription integration and then you should be able to delete the account integration.

Thanks.

**Comment by kanthchandra** [comment]
We also do show the dependencies before we allow you to delete the account integration, but it looks like this sub doesn't have any permissions right now on Shippable (probably the permissions were revoked on github?) and as a result you were not able to see the dependencies for this account integration.

**Comment by chuckphillips** [comment]
Hi @kanthchandra , I've tried to delete the Slack integration from Shippable but got the same exact error. I'm sorry. I might be confused as to what I should be deleting.

You are correct. Shippable permissions have been revoked from our Github account.

**Comment by ambarish2012** [comment]
@chuckphillips we are deleting the slack integration for you from the mindbody sub. Once that is complete, you will be able to remove it from your account.

**Comment by ambarish2012** [comment]
@chuckphillips you should be able to remove slack integration now.

**Comment by chuckphillips** [comment]
@kanthchandra It worked. Thank you!
