### ISSUE TITLE
GCE Deployment Failing but no details available for error

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3579]
Deployment to our DEV environment is failing today, but I can't see any errors to give me a clue as to what might be wrong with our configuration. 

Please see the attached image.

![screen shot 2017-05-10 at 11 59 00 am](https://cloud.githubusercontent.com/assets/1018189/25908486/533a3650-3578-11e7-932f-801605ff612d.png)

**Comment by ryan-kimber** [comment]
Components prior to the gke-develop-deploy step all seem to be working, and there are no complaints from the SPOG about our config.

![screen shot 2017-05-10 at 12 01 54 pm](https://cloud.githubusercontent.com/assets/1018189/25908593/914c4942-3578-11e7-82ba-c372ed42d552.png)

**Comment by ambarish2012** [comment]
@ryan-kimber we are investigating.

**Comment by trriplejay** [comment]
I think I see what's happening here.

We released some new features on 5/5, one of which was an enhancement to portMappings in dockerOptions.  Before that day, GKE jobs basically ignored the `hostPort` part of the portMapping. Today they will respect the hostPort, containerPort, and protocol specified in dockerOptions.

It looks like many of your images in the manifest have the same hostPorts listed. Before 5/5 those were ignored, but now we're actually sending them to GKE when we try to update your replicationController. GKE doesn't like the fact that multiple images are trying to use the same hostPort.

Are any of your images actually using those hostPorts? can you update your dockerOptions to remove any unnecessary hostPort specifications? you can use syntax like `:80` to specify only a containerPort and default to tcp.

Of course its also a problem that this information wasn't made available in the error message... we'll update our logging here.

**Comment by ryan-kimber** [comment]
We do specify the host ports, but I think that they are all unique.

I've included our shippable.resources.yml below for reference:

resources:

   #notification: # notification are only supported for runSh? That's weird.
   #  - name: slack-notifications
   #    type: notification
   #    integration: Slack
   #   pointer:
   #     recipients:
   #       - "#beta"                               #required
   #       - "@trriplejay"                         #optional

  - name: replicas-2                              #required
    type: replicas                              #required
    version:
      count: 2                                  #required

  - name: replicas-3                              #required
    type: replicas                              #required
    version:
      count: 3

  - name: replicas-4                              #required
    type: replicas                              #required
    version:
      count: 4


# Docker Image for NGINX Server
  - name: nginx-container-img
    type: image
    integration: gcr-integration
    pointer:
      sourceName: "us.gcr.io/formhero-io/nginx-for-gce"
      isPull: false
    seed:
      versionName: "develop.34"

  - name: nginx-container-opts
    type: dockerOptions
    version:
      memory: 512
      #cpuShares: 256
      portMappings:
        - 30080:80
        - 30443:443
      publishAllPorts : true

# Docker Image for fh-library-service
  - name: fh-library-service-container-img
    type: image
    integration: gcr-integration
    pointer:
      sourceName: "us.gcr.io/formhero-io/fh-library-service"
      isPull: false
    seed:
      versionName: "develop.52"

  - name: fh-library-service-container-opts
    type: dockerOptions
    version:
      memory: 1024
      #cpuShares: 256
      portMappings:
        - 30002:3002
      publishAllPorts : true

# Docker Image for fh-pdf-refinery
  - name: fh-pdf-refinery-container-img
    type: image
    integration: gcr-integration
    pointer:
      sourceName: "us.gcr.io/formhero-io/fh-pdf-refinery-service"
      isPull: false
    seed:
      versionName: "develop.14"

  - name: fh-pdf-refinery-container-opts
    type: dockerOptions
    version:
      memory: 4096
      #cpuShares: 256
      portMappings:
        - 30880:8080
      publishAllPorts : true

# Docker Image for fh-studio-auth-service
  - name: fh-auth-service-container-img
    type: image
    integration: gcr-integration
    pointer:
      sourceName: "us.gcr.io/formhero-io/fh-auth-service"
      isPull: false
    seed:
      versionName: "develop.76"

  - name: fh-auth-service-container-opts
    type: dockerOptions
    version:
      memory: 512
      #cpuShares: 256
      portMappings:
        - 30001:3001
      publishAllPorts : true

# Docker Image for fh-style-service
  - name: fh-style-service-container-img
    type: image
    integration: gcr-integration
    pointer:
      sourceName: "us.gcr.io/formhero-io/fh-style-service"
      isPull: false
    seed:
      versionName: "develop.27"

  - name: fh-style-service-container-opts
    type: dockerOptions
    version:
      memory: 512
      #cpuShares: 256
      portMappings:
        - 30008:3008
      publishAllPorts : true

# Docker Image for fh-style-service
  - name: fh-submissions-service-container-img
    type: image
    integration: gcr-integration
    pointer:
      sourceName: "us.gcr.io/formhero-io/fh-submissions-service"
      isPull: false
    seed:
      versionName: "develop.98"

  - name: fh-submissions-service-container-opts
    type: dockerOptions
    version:
      memory: 1024
      #cpuShares: 256
      portMappings:
        - 30003:3003
      publishAllPorts : true

  - name: fh-phone-service-container-img
    type: image
    integration: gcr-integration
    pointer:
      sourceName: "us.gcr.io/formhero-io/fh-phone-service"
      isPull: false
    seed:
      versionName: "develop.22"

  - name: fh-phone-service-container-opts
    type: dockerOptions
    version:
      memory: 256
      #cpuShares: 256
      portMappings:
        - 30004:3004
      publishAllPorts : true

# Docker Image for fh-event-queue-processor
  - name: fh-event-queue-processor-container-img
    type: image
    integration: gcr-integration
    pointer:
      sourceName: "us.gcr.io/formhero-io/fh-event-queue-processor"
      isPull: false
    seed:
      versionName: "develop.28"

  - name: fh-event-queue-processor-container-opts
    type: dockerOptions
    version:
      memory: 512

# Docker Image for fh-email-queue-processor
  - name: fh-email-queue-processor-container-img
    type: image
    integration: gcr-integration
    pointer:
      sourceName: "us.gcr.io/formhero-io/fh-email-queue-processor"
      isPull: false
    seed:
      versionName: "develop.32"

  - name: fh-email-queue-processor-container-opts
    type: dockerOptions
    version:
      memory: 512

# Versioning resource (shippable uses this to track what version we're
at. No need to modify the versionName below.
  - name: fh-backend-version                    #required
    type: version                               #required
    seed:
      versionName: "0.0.1"                      #required


# add Develop Env on Google Container Engine
  - name: fh-gke-dev-cluster
    type: cluster
    integration: fh-gke-integration
    pointer:
      sourceName : "fh-dev-cluster"
      region: "us-central1-a"
      namespace: "formhero-ns"

  - name: fh-dev-environment             #required
    type: params                       #required
    version:
      params:
        #This is FORMHERO_CONFIG_PASSWORD
        secure:
UKwTvp4tAsggkTr0uC3r+7eSTuBw8IPE6i38xkSOrrx63WCUxGKyizPLkfNFTMrgizTpvNTZbdHXX4/Vns5cQG7nL9DQ5fDZFIYgfvYaDB1mmNBzZRv4AxseXFRc91P0gLnfMQ3Bty/dhTVLrHLOiA0k7MfOP/l3RTjRtdKhwKzr5wmVjHiUMwrGvuKY3mn0gpXbjjS2B3a5PesZ9LANpN6oF5ga5vihhDXgbSII7TCdWobaE3q/8oeRJyHw4EFehFRU1s1ABkZl9j75lJybCVUohH5mV46e/3bveZqynZedC5n348VUQ0IUzRAEmI8qOELomKBnrLnNYPzMYKzedg==
        FORMHERO_CONFIG_FILE: ./gce-config.json
        FORMHERO_ENVIRONMENT: dev

# add Sandbox Env on Google Container Engine
  - name: fh-gke-sandbox-cluster
    type: cluster
    integration: fh-gke-integration
    pointer:
      sourceName : "fh-sandbox-cluster"
      region: "us-central1-a"
      namespace: "formhero-ns"

  - name: fh-sandbox-environment             #required
    type: params                       #required
    version:
      params:
        secure:
TzxsFynTAVLvdeQIZZe9qPcb20TG+E3G2krnvqH1y81635kMEQy23GuejnzKzMh0/csUg4IullWCmI/sFNbBaskvQY0+T8tEH1f3Bo9cRF14Uz66AYGcT6mLbvmL5JhkUCbARMmP9vXtTsUhCcfGxNnzzcDISPsVBIykDmWbqLETKrujcg3Rd3xGaAgUU/lltVsouPrbDKtVly4Ij18KJzwjz2kI2hq50AvZX6xbIBSUARAQGO3LpYFqD8RWAv/uGXZhCewaQ9VvsnZ/mytHagymk6mINsCfxKIG8Fl5QkqNU7rZJ6VyuaICydskvbvG/jns4jGWVhKWy0ERtsxUUA==
        FORMHERO_CONFIG_FILE: ./gce-config.json
        FORMHERO_ENVIRONMENT: sandbox

  - name: fh-gke-prod-blue-cluster
    type: cluster
    integration: fh-gke-integration
    pointer:
      sourceName : "fh-prod-blue-cluster"
      region: "us-central1-a"
      namespace: "formhero-ns"

  - name: fh-blue-environment             #required
    type: params                       #required
    version:
      params:
        secure:
SML3+CVJgNEaHvPZ3yvDz7RR1ucuXzF3lpPGIQwlD82Phn/qegONWLblenU0KLNFe4+1ttK7YEWJqMbC5cdH3xVVoSqOOzrNDHwZrRLv/aonxWnuIN3RuXOeQjD3gC+rgecmJLhk+HnNOOlrrpRoZEBmAxEl/6ORl0tqc7LNQW3PkeZEmmrpGN7yJjjjiZLJSLQouXvwGO+2vr+cD4ZIQmpxpwI9bpcG+BsqgjWSdFutz7D+9SZyAm/2K9UPW7CiHA0dwPUSA4ll2KSC960E7xPCfW/DNJMyP5LMNOWl0M0u7cTBa5a0abLCvQlFoOhKCiK+LkN+nvmHsnFGEfSnlQ==
        FORMHERO_CONFIG_FILE: ./gce-config.json
        FORMHERO_ENVIRONMENT: production-blue

  - name: fh-gke-prod-green-cluster
    type: cluster
    integration: fh-gke-integration
    pointer:
      sourceName : "fh-prod-green-cluster"
      region: "us-central1-a"
      namespace: "formhero-ns"

  - name: fh-green-environment             #required
    type: params                       #required
    version:
      params:
        secure:
SML3+CVJgNEaHvPZ3yvDz7RR1ucuXzF3lpPGIQwlD82Phn/qegONWLblenU0KLNFe4+1ttK7YEWJqMbC5cdH3xVVoSqOOzrNDHwZrRLv/aonxWnuIN3RuXOeQjD3gC+rgecmJLhk+HnNOOlrrpRoZEBmAxEl/6ORl0tqc7LNQW3PkeZEmmrpGN7yJjjjiZLJSLQouXvwGO+2vr+cD4ZIQmpxpwI9bpcG+BsqgjWSdFutz7D+9SZyAm/2K9UPW7CiHA0dwPUSA4ll2KSC960E7xPCfW/DNJMyP5LMNOWl0M0u7cTBa5a0abLCvQlFoOhKCiK+LkN+nvmHsnFGEfSnlQ==
        FORMHERO_CONFIG_FILE: ./gce-config.json
        FORMHERO_ENVIRONMENT: production-green

  - name: fh-gke-td-blue-cluster
    type: cluster
    integration: fh-gke-integration
    pointer:
      sourceName : "fh-td-prod-blue-cluster"
      region: "us-central1-a"
      namespace: "formhero-ns"

  - name: fh-td-environment             #required
    type: params                       #required
    version:
      params:
        secure:
TzxsFynTAVLvdeQIZZe9qPcb20TG+E3G2krnvqH1y81635kMEQy23GuejnzKzMh0/csUg4IullWCmI/sFNbBaskvQY0+T8tEH1f3Bo9cRF14Uz66AYGcT6mLbvmL5JhkUCbARMmP9vXtTsUhCcfGxNnzzcDISPsVBIykDmWbqLETKrujcg3Rd3xGaAgUU/lltVsouPrbDKtVly4Ij18KJzwjz2kI2hq50AvZX6xbIBSUARAQGO3LpYFqD8RWAv/uGXZhCewaQ9VvsnZ/mytHagymk6mINsCfxKIG8Fl5QkqNU7rZJ6VyuaICydskvbvG/jns4jGWVhKWy0ERtsxUUA==
        FORMHERO_CONFIG_FILE: ./gce-td-config.json
        FORMHERO_ENVIRONMENT: production-blue

#######1: EOF Create DV pipeline

**Comment by ryan-kimber** [comment]
Hi guys, sorry, but I don't think that explains it. 

Here are the dockerOptions configs we are using in our shippable.resources.yml. There don't seem to be any duplicated ports at all.

  - name: nginx-container-opts
    type: dockerOptions
    version:
      memory: 512
      #cpuShares: 256
      portMappings:
        - 30080:80
        - 30443:443
      publishAllPorts : true

  - name: fh-library-service-container-opts
    type: dockerOptions
    version:
      memory: 1024
      #cpuShares: 256
      portMappings:
        - 30002:3002
      publishAllPorts : true

  - name: fh-pdf-refinery-container-opts
    type: dockerOptions
    version:
      memory: 4096
      #cpuShares: 256
      portMappings:
        - 30880:8080
      publishAllPorts : true

  - name: fh-auth-service-container-opts
    type: dockerOptions
    version:
      memory: 512
      #cpuShares: 256
      portMappings:
        - 30001:3001
      publishAllPorts : true

  - name: fh-style-service-container-opts
    type: dockerOptions
    version:
      memory: 512
      #cpuShares: 256
      portMappings:
        - 30008:3008
      publishAllPorts : true

  - name: fh-submissions-service-container-opts
    type: dockerOptions
    version:
      memory: 1024
      #cpuShares: 256
      portMappings:
        - 30003:3003
      publishAllPorts : true

  - name: fh-phone-service-container-opts
    type: dockerOptions
    version:
      memory: 256
      #cpuShares: 256
      portMappings:
        - 30004:3004
      publishAllPorts : true

**Comment by trriplejay** [comment]
hmm. ok, we'll continue to investigate. the replicationController object is being rejected by kubernetes for some reason. I still suspect it has something to do with the portMappings, but i'll see if i can narrow that down.

**Comment by trriplejay** [comment]
could you provide the deploy job yml? i think maybe the applyTo sections aren't working. it might be a yml formatting issue.

**Comment by trriplejay** [comment]
sorry, i mean the manifest job. the job that has the applyTo sections.

**Comment by trriplejay** [comment]
I also see that you're using `publishAllPorts: true`.  This option isn't supported by GKE.  It won't cause any errors, but it's not adding any functionality either, in case you'd like to remove it.

regarding applyTo sections, make sure your yml looks like this:

```
- IN: myDockerOptions
  applyTo:
    - myDockerImage
```

and does NOT look like:
```
- IN: myDockerOptions
  applyTo: myDockerImage
```

**Comment by ryan-kimber** [comment]
I removed the publishAllPorts: true, and updated all the applyTo sections,
but the deployment is still failing.

I've attached our .yml files for your info.

The extra fh-dev-cluster-load-balancer.yml is the command we used to
initially create our load balancer (might not be relevant here, but I
thought I'd include it in case).

Thanks for your help,

**Comment by trriplejay** [comment]
it looks like the manifest job hasn't been run again since those changes, can you run that job first? that should trigger the deploy with the changes made.

**Comment by ryan-kimber** [comment]
That seems to have worked. I'll do some testing to make sure the app comes
up properly, but if you don't hear from me, we're all good.

Thanks John!

**Comment by trriplejay** [comment]
great! glad we got that resolved. Feel free to reopen if needed.
