### ISSUE TITLE
Liveness failure

### ISSUE THREAD

**Issue by haf** [Shippable/support#3581]
I've written a highly concurrent web- and business app with [Hopac](https://github.com/Hopac/Hopac/), a concurrent-ML derivative for F#, that I'm testing on Mono v4.8.1 on Shippable.

As part of writing the app, I've also written a concurrent test framework [expecto](https://github.com/haf/expecto) and a DSL for testing the whole system in memory (closed source). This test DSL uses the [embedded EventStore](http://docs.geteventstore.com/dotnet-api/4.0.0/embedded-client/), itself a highly concurrent software.

I'm getting test failures when running on Shippable, despite bumping the time/wait budget. How do I bump concurrency on the build so that I can ship my software?

**Comment by scriptnull** [comment]
Hi @haf,

Could you share the link for your build ? So that, we can take a look at it and try to understand whats going on.

> How do I bump concurrency on the build so that I can ship my software?

By the above statement, I assume that you might be looking for [matrix builds](http://docs.shippable.com/ci/advancedOptions/matrixBuilds/). Please correct me, if I am wrong.

Thanks.

**Comment by haf** [comment]
@scriptnull No I mean classic software concurrency. https://app.shippable.com/download/jobConsoles?jobId=591704261973250800b7f6e6 for example.

**Comment by haf** [comment]
Ping, what's your answer?

**Comment by haf** [comment]
Is there anything else I can answer? This is stopping our deployment.

**Comment by manishas** [comment]
@ambarish2012 can we look into this?

**Comment by kanthchandra** [comment]
Hi @haf I had a question,

1. When you say bump the concurrency, do you mean increasing the number of cores of the machine? - The reason why I asked is, Shippable doesn't restrict anything in terms of how many threads can run concurrently or any other default OS settings. We run on C4 large ubuntu machines on AWS with 2 core processor and 3.75 GB of RAM, however we do run your build scripts inside a docker container (I'm not sure if that would affect concurrency in anyway and I couldn't find anything online either). So can you please let me know how Shippable is causing builds to fail and what we could do to help you?

**Comment by haf** [comment]
Yeah, that should be enough. So you're not doing https://docs.docker.com/engine/admin/resource_constraints/ ?

The funky thing is that all tests pass locally on the same mono version as we're running on shippable, but not when we actually run it on shippable. If you're sure that you're giving 2 cores to the container, as well as the VM, then I'll start debugging more from my side?

**Comment by kanthchandra** [comment]
1. Yes, I'm pretty sure, all the machine that are spun up are 2 core 3.75 GB RAM machines, unless you have paid for bigger machines. Here is the link with the pricing and configuration of build machines. http://docs.shippable.com/getting-started/billing-overview/ . In case you need bigger machines you can upgrade your plan from billing tab by selecting the required machine.

2. We do not set any memory limits on the build container, you can actually see the docker run command in the boot_container section of your consoles. If you specify a specific image, we just spin that up without any limits. 

Please let us know if you need any further help.

**Comment by haf** [comment]
Thanks, I'll try to wrench the build into submission from my side then. I'll leave this issue open for now.

**Comment by ambarish2012** [comment]
@haf please let us know if you need more help, I will then reopen this issue.

**Comment by haf** [comment]
Yeah, we haven't been able to fix the shippable build, despite working locally. We're still in the process of trying different configurations and trying to prune the search space.
