### ISSUE TITLE
ciRepo dependency is inconsistent

### ISSUE THREAD

**Issue by aurelien-reeves** [Shippable/support#3584]
### Description of your issue:
After making some tests with pipelines we are no more able to build anything because of the error "[project]_ciRepo dependency is inconsistent"

![capture du 2017-05-15 16-37-24](https://cloud.githubusercontent.com/assets/24386780/26063037/096d56ba-398d-11e7-8c74-1d84cfc979aa.png)

- Link to the build failure: https://app.shippable.com/github/hiptest/hiptest/runs/2436/1/console

What does that mean and how could we fix this?

**Comment by kanthchandra** [comment]
@aurelien-reeves I'm looking into the issue, I'll update you as soon as I have more info.

**Comment by kanthchandra** [comment]
Hi @aurelien-reeves I can't seem to figure out why your project was marked as inconsistent, can you let me know what are the things that you tried out? To shorten the down the problem, something that happened from commits 6886578c4f56364143bc9925d6fdb676e03468ef to 8cc9c80f551168c46b96d8c7fa05544200382cde caused the resource to be marked as inconsistent.

**Comment by aurelien-reeves** [comment]
I made some tests within a branch "are-shippable-pipelines".

At some point, a commit create the following job:
```
jobs:
  - name: hiptest_ciRepo
    type: runCI
    steps:
- OUT: hiptest_image
```

and comment everything in the resource file:
```
# resources:
#   - name: hiptest_repo
#     type: gitRepo
#     integration: Github
#     pointer:
#       sourceName: hiptest/hiptest
#       branch: are-shippable-pipelines
```

After that the resource file have been edited again because of an error that said "null resource":
```
-# resources:
+resources:
```

Finaly the file has been totaly cleaned-up
```
-resources:
-#   - name: hiptest_repo
-#     type: gitRepo
-#     integration: Github
-#     pointer:
-#       sourceName: hiptest/hiptest
-#       branch: are-shippable-pipelines
```

The job has then be renamed:
```
-  - name: hiptest_ciRepo
+  - name: hiptest_runCI
```

Before to be fully deleted
```
-jobs:
-  - name: hiptest_runCI
-    type: runCI
-    steps:
-      - OUT: hiptest_image
+# jobs:
+#   - name: hiptest_runCI
+#     type: runCI
+#     steps:
+#       - OUT: hiptest_image
```

Actually as you can see I groped :(

**Comment by ambarish2012** [comment]
@aurelien-reeves we have set the state of your ciRepo to consistent.

**Comment by aurelien-reeves** [comment]
It seems to be working, thank you 👍
