### ISSUE TITLE
Changing name of integration doesn't work

### ISSUE THREAD

**Issue by kartikluke** [Shippable/support#3585]
Changing the name of a webhook integration creates a new integration with a dependency on the old integration name.

![screen shot 2017-05-15 at 1 20 23 pm](https://cloud.githubusercontent.com/assets/3857139/26070121/69adff78-3971-11e7-8844-612f8dfa6a3d.png)

![screen shot 2017-05-15 at 1 20 35 pm](https://cloud.githubusercontent.com/assets/3857139/26070120/69a33548-3971-11e7-95d0-6c4cf723e437.png)

**Comment by ambarish2012** [comment]
@kartikluke please can you clarify whether this is a project, generic Webhook or resource event trigger?

**Comment by kartikluke** [comment]
@ambarish2012 It's a generic webhook.

**Comment by kartikluke** [comment]
Steps to reproduce:

1. Create an event trigger of the generic webhook type.
2. Change the name
3. Try to delete the integration and it'll have a dependency on the old name of the webhook.

**Comment by kartikluke** [comment]
Another issue is the new name doesn't work.

![screen shot 2017-05-15 at 2 52 11 pm](https://cloud.githubusercontent.com/assets/3857139/26073915/28b9aaf0-397e-11e7-9303-ae1919ebb07c.png)

**Comment by ambarish2012** [comment]
@kartikluke did you rename trigger_report to trigger_report_local?

**Comment by kartikluke** [comment]
@ambarish2012 No I renamed `Trigger Report Locally` to `trigger_report_local`. The old name no longer shows in the list. `trigger_report` is another one.

**Comment by ambarish2012** [comment]
@kartikluke I looked at your subscription.

1) Your subscription trigger_report_locally refers to an account integration called	trigger_report_locally.

2) Your yml needs to be updated so that you reference your integration by its current name - `trigger_report_locally`.

3) When an account integration is renamed, we do not automatically rename the subscription integration. What we do is simply reference your existing subscription integration to the renamed account integration.

We do not rename the subscription integration since it will break your build.

**Comment by kartikluke** [comment]
@ambarish2012 `trigger_report_locally` is another one I made. I created a few duplicates to test it out. I am unable to delete renamed integrations that's why I have so many duplicates in there.

I understand that you're referencing the old name but the issue I'm facing is that a renamed subscription doesn't respond to it's new name and cannot be deleted. I want to delete the integrations because it's hard to understand which is the one I'm using unless I rename them to `[DELETED]` or something like that.

**Comment by ambarish2012** [comment]
@kartikluke got it - I am looking into why you cannot delete trigger_report_local now.

**Comment by ambarish2012** [comment]
@kartikluke you have a subscription integration `Trigger Report Locally` that is referencing the account integration `trigger_report_local` that I understand you renamed.

I suggest you delete the `Trigger Report Locally` subscription integration and then delete the `trigger_report_local` account integration, in that order.

**Comment by kartikluke** [comment]
@ambarish2012 I can't delete `Trigger Report Locally` because it no longer shows in the list. This is what I can see. Also `Trigger Report Locally` is the old name of `trigger_report_local`. I didn't reference them that happened automatically when I renamed it.

![screen shot 2017-05-15 at 3 41 18 pm](https://cloud.githubusercontent.com/assets/3857139/26075925/0af1bba0-3985-11e7-98dd-5884379e0c1a.png)

**Comment by ambarish2012** [comment]
@kartikluke to delete `Trigger Report Locally`, go to your subscription. Then click on Settings -> Integration and click on `Delete`. 

`Trigger Report Locally` is a subscription integration and hence in the subscription settings UI.
