### ISSUE TITLE
Using Yarn with Shippable

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3587]
Hello!

The Yarn package manager is a great alternative to npm, it has all the features of npm plus lockfile support and it works much faster.

So our entire infrastructure is configured around using Yarn instead of npm. What is the best way to use it with Shippable?

Looks like build process for `node_js` is specifically tailored to use npm and provides some useful optimizations, like e.g. module caching. Is it possible to achieve the same with Yarn?

Thank you!

**Comment by sumothecat** [comment]
I believe support for Yarn would for example have prevented this issue https://github.com/Shippable/support/issues/3634 and others. Reproducible builds are desirable.

**Comment by sumothecat** [comment]
We have switched to Yarn and it works in Shippable. 
```
build:
  ci:
    - npm install -g yarn
    - yarn install
    - yarn run build:prod
```

You need a recent-ish version of Node as Yarn `Expected version ">=4.6.0".` We upgraded our Shippable.yml to 

```
 node_js:
    - 6.9.4
```

**Comment by himanshu0503** [comment]
Hey @sumothecat, we now have yarn preinstalled on our [v5.6.1 images](http://docs.shippable.com/reference/machine-image-v561/#nod-561). You can [change your subscription machine image](http://docs.shippable.com/reference/machine-images-overview/#changing-the-subscription-machine-image) to point to v5.6.1 to be able to use them.
After you update your subscription machine image, you need not install yarn and your yml will look like this.
```yml
build:
  ci:
    - yarn install
    - yarn run build:prod
```

**Comment by sumothecat** [comment]
Thanks @himanshu0503 - but why v5 and not v6? v6 is LTS on my understanding. https://github.com/nodejs/LTS#lts-schedule1

**Comment by rageshkrishna** [comment]
The version numbers on our machine images are tied to Shippable's releases and not to the languages or frameworks available within.

The node versions available in our 5.6.1 images are documented at http://docs.shippable.com/reference/machine-image-v561/#nod-561

**Comment by sumothecat** [comment]
Ahh....! Thanks.

**Comment by ambarish2012** [comment]
@sumothecat [docs](docs.shippable.com) have also been updated.

**Comment by slavafomin** [comment]
@ambarish2012 the link is broken :)

**Comment by ambarish2012** [comment]
@slavafomin it's working for me.

**Comment by slavafomin** [comment]
The yarn is not pre-installed on `node_js/8.6.0` machines. Why don't you add it to all newer versions of node machines?

Even the [official Node Docker image](https://hub.docker.com/_/node/) has yarn pre-installed.

**Comment by slavafomin** [comment]
I've just realized, that you need to switch AMI version in Shippable "Nodes" configuration in order to use the latest machine image.

**Comment by manishas** [comment]
Yes the latest machine image has Yarn http://docs.shippable.com/platform/tutorial/runtime/ami-v582/#nod-582
