### ISSUE TITLE
feature request:  automatically expand errors in console log view

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3589]
I would really really -really- love it if the collapsed section of the console log view that contains an error (the little X icon) would be expanded.     Ideally the subsection that triggered the error  could also be expanded and indicated, but expanding the main section would be a great start.

it's a pain to have to stare at tiny nearly-the-same-color X and check marks (remember, some folks are colorblind and red/green near each other is the worst) to find out which one was the error.   Then expand that, then troll through the sections and expand those.    if a section triggered an `on_failure` it seems logical you can identify it an expand it....

**Comment by keen99** [comment]
another useful expand feature would be to allow me to specify a flag in my task's step to always expand that section....  ie:

```  - name: dv-test-runsh
    type: runSh
    expand_log_view: true```

would always cause `/home/shippable/micro/nod/genExec/managed/runSh/run.sh` to expand.  

:)

**Comment by ambarish2012** [comment]
Thanks for these excellent usability suggestions @keen99 - I will add these to our backlog.

**Comment by a-murphy** [comment]
The failing sections are now automatically expanded, so I'm closing this.
