### ISSUE TITLE
Support PHP 5.3.3

### ISSUE THREAD

**Issue by andrerom** [Shippable/support#359]
PHP 5.3.3 is the PHP version used by Redhat 6.x and has thus often been the common minimum supported version in the PHP community.

Hence for maintaining existing releases that support this platform, it is beneficial to support this version in addition to the main 5.3, 5.4, 5.5 and 5.6 versions.

Note: Redhat has patched their version over the years to fix some fatal errors and security issues that can be found in stock 5.3.3, the travis used php-build project [never applied](https://github.com/CHH/php-build/issues/140) these, but it would be highly beneficial if they where, especially the fatal errors affecting unit tests.

**Comment by manishas** [comment]
Closing as DUP of #105 where I'm tracking requests for additional languages and versions
