### ISSUE TITLE
feature request:  allow opening SPOG links in new window/tab

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3590]
![image](https://cloud.githubusercontent.com/assets/1108844/26132785/89a8f47c-3a70-11e7-8561-6ae731b39adc.png)

it would be really nice to be able to middle-click the jobs in the SPOG and have that open the console/etc view in a new tab or window.   since you capture the right-click, adding a "open in..."
 option to that would be nice.   if nothing else, adding an actual link I can click/middleclick/rightclick/copy/paste in the popup would be good - 

![image](https://cloud.githubusercontent.com/assets/1108844/26132834/e9ce3a10-3a70-11e7-9485-86e13a46e4ea.png)

When trying to debug a problem that requires looking at two pipeline task console logs at the same time it's very annoying since I cant just pop them into their own tab/window.  I either have to keep closing/navigating/opening/expanding/looking rinse and repeat, or open a new window with the SPOG and drill in again.

**Comment by ambarish2012** [comment]
Thanks @keen99 - I will add this UX suggestion to our backlog.

**Comment by avinci** [comment]
this now opens in new tab.
