### ISSUE TITLE
Use new URL layout for badges

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3591]
A while ago Shippable has changed its app url layout from `https://app.shippable.com/projects/<id>` to `https://app.shippable.com/<vcs>/<subscription>/<project>`.

This should be reflected in the badge URLs which currently still use `https://api.shippable.com/projects/<id>/badge?branch=<branch>` and should probably be `https://api.shippable.com/<vcs>/<subscription>/<project>/badge?branch=<branch>` instead.

**Comment by ambarish2012** [comment]
@mbrodala app URL layout was changed to make it more friendly. However, as far as API is concerned, badges will continue to exist on the /projects route. We do not want that route to be VCS or subscription based.

**Comment by mbrodala** [comment]
@ambarish2012 OK maybe a little more background: I've set up a kickstart process where users are supposed to enable projects on Shippable, grab the project ID and enter it. I use this ID to e.g. put shields.io badges in the README. Currently project IDs are basically hidden and can only be found in the badges tab of projects.

Thus I'd need either Shippable badges or shields.io adhering to the new URL layout.

**Comment by ambarish2012** [comment]
@mbrodala thanks, I will get back to you after some internal discussions.

**Comment by ambarish2012** [comment]
@mbrodala we cannot support the URL format at this time. Please continue to use the format suggested.

**Comment by mbrodala** [comment]
OK, I've created #3591 for this.
