### ISSUE TITLE
Telegram support?

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3594]
Hello!

Is there an integration between Shippable and Telegram? We would really love to receive notifications to our Telegram chat when each new job is complete.

**Comment by ambarish2012** [comment]
@slavafomin we do not have support for Telegram currently, I will add this request to our backlog.

**Comment by slavafomin** [comment]
@ambarish2012 thanks! Will be looking forward for it.

**Comment by manishas** [comment]
This isn't currently on the roadmap, so closing as deferred. Happy to revisit if it is a critical requirement or gets a lot of +1s
