### ISSUE TITLE
rSync build failing

### ISSUE THREAD

**Issue by mutchco** [Shippable/support#3598]
We're trying to get our shippable pipeline back up after transferring our repos to a new organization and we're getting this error:

Failed to getSHAByAccountIntegrationId for accountIntegrationId: xxxxx

It seems to be failing on one of our git resources.

**Comment by ambarish2012** [comment]
@mutchco we are investigating.

**Comment by ambarish2012** [comment]
@mutchco your gitRepo resource git_libraries_staging is marked inconsistent in the pipeline (it's the only pink colored box in the SPOG). 

I would double check the repo and ensure that you have specified the right branch, which presumably is staging. Do you have a staging branch for that git repo?

**Comment by ambarish2012** [comment]
@mutchco I am closing this issue since your rSync is working now.
