### ISSUE TITLE
Protractor 5 installation issue due Node and NPM versions

### ISSUE THREAD

**Issue by Tix1981** [Shippable/support#3600]
After installing NodeJS, I'm checking node version (v7.0.0) and NPM version (3.10.8). After that, trying to install Protractor 5, but I got `npm WARN engine protractor@5.1.2: wanted: {"node":">=6.9.x"} (current: {"node":"0.10.33","npm":"1.4.28"})` and build is failing after that. Selected language is PHP so I'm trying to manually install NodeJs. 

Link to the build failure: https://app.shippable.com/github/GaryBreslow/Zwivel-/runs/16460/1/console

Yml file:

```
build_environment: Centos 6.5

language: php

php:
  - 5.6

#node_js:
# - 6.9.4

addons:
  firefox: "48.0"

services:
  - mysql
  - elasticsearch
  - selenium

before_install:
  - php -v
  - mkdir -p ~/.nvm/versions
  - source ~/.nvm/nvm.sh && nvm install 7.0.0 && nvm alias default 7.0.0 && nvm use default
  - node --version
  - npm -v
  - shippable_retry sudo gem install compass
  - echo "xdebug.max_nesting_level = 1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - shippable_retry sudo npm install -g protractor
  - protractor --version
  - shippable_retry sudo webdriver-manager update

before_script:
  - cp ./.env.testing .env
  - mkdir -p shippable/testresults
  - composer self-update
  - composer install --prefer-source --no-interaction
  - compass clean
  - compass compile
  - mysql -e 'create database if not exists zwivel_test;'
  - mysql -e 'set global net_buffer_length=1000000;'
  - mysql -e 'set global max_allowed_packet=1000000000;'
  - mysql -e 'set global max_connections = 500;'
  - php artisan migrate
  - php artisan db:seed
  - php -S localhost:8000 public/index.php &
  - php artisan trigger-set-up-test-env
script:
  - phpunit --configuration phpunit.xml --log-junit shippable/testresults/junit.xml --testsuite integration
  - xvfb-run protractor tests/protractor/conf-log-in.js
  - xvfb-run protractor tests/protractor/conf-request-proccess.js
```

**Comment by ambarish2012** [comment]
@Tix1981 we do not support CentOs (and the build_environment tag which is being ignored).

Also you are using the shippable/minv2 image in the build/pre_ci_boot section, which is no longer supported. I suggest you either move to a custom image that suits your requirements or try our v5.5.1 image. 

Our machine images are documented [here](http://docs.shippable.com/reference/machine-images-overview/)

**Comment by ambarish2012** [comment]
@Tix1981 I built a YML using a subset of your YML and was able to install protactor with the latest image.

- Console link - https://app.shippable.com/github/ambarish2012/samplePipelinesDemo/runs/22/1/console
- YMLlink
https://github.com/ambarish2012/samplePipelinesDemo/blob/master/shippable.yml

Also - you are using the older YML format. We have plenty of YML samples in this github organization - https://github.com/devops-recipes. 

For example, look at this project in that organization - https://github.com/devops-recipes/basic-node/blob/master/shippable.yml.

**Comment by Tix1981** [comment]
Tnx, changing image solved the problem 
```
build:
    pre_ci_boot:
      imageName: dry-dock/u16phpall
      tag: latest
      pull: true

```
