### ISSUE TITLE
Add easy way to get project ID

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3601]
A while ago Shippable has changed its app url layout from `https://app.shippable.com/projects/<id>` to `https://app.shippable.com/<vcs>/<subscription>/<project>`.

However, we still need the internal project ID to e.g. put build badges in `README` files on project kickstart.

Thus I'd like to request a way to get the current project ID aside from the "Badges" section in the project settings.

**Comment by ambarish2012** [comment]
@mbrodala - my understanding is that a separate setting that just exposes the project id is what you are looking for?

**Comment by mbrodala** [comment]
Yes, if possible directly on the project view and not hidden in the settings. ;-)

**Comment by manishas** [comment]
coming up in the next couple of weeks :)

**Comment by mbrodala** [comment]
Thanks, I love you guys. ;-)

**Comment by rageshkrishna** [comment]
This is now available in the new UI that was launched today. All the project pages have the ID displayed on the bottom right hand corner of the page. Subscription pages have subscription IDs, too.

**Comment by mbrodala** [comment]
Yeah, I've switched to the new UI right away and like it. Thanks a lot. :-)
