### ISSUE TITLE
dockerfile configuration

### ISSUE THREAD

**Issue by aswath-veersoft** [Shippable/support#3602]
Hello,
I want to use shippable.yml with the dockerfile.  It will be easy to further expand using dockerfile, instead of your style configuration.
Do you have dockerfile that I can use for the following shippable.yml file
dockerfile should contain
jdk1.7
maven 3.3
selenium 2.53 with headless firefox 47.1

My current shippable.yml.
------------------------------------------------------------------
language: java

jdk:
   - oraclejdk7

env:
  - JUNIT4SET=true
  - TESTSET1=true
  - TESTSET2=true
  - TESTSET3=true
  - TESTSET4=true

addons:
  firefox: "47.0.1"

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    #download selenium version 2.53.1
    - mkdir ~/selenium
    - pushd ~/selenium
    - sudo wget http://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
    - pwd && ls -lR
    #start selenium server
    - java -jar ./selenium-server-standalone-2.53.1.jar &
    - popd
    - "export DISPLAY=:99.0"

    - if [ ! -z "$JUNIT4SET" ]; then xvfb-run --server-args="-ac" mvn verify -Pfirefox -Pjunit4testset; fi
    - if [ ! -z "$TESTSET4" ]; then xvfb-run --server-args="-ac" mvn verify -Pfirefox -Ptestset4; fi
    - if [ ! -z "$TESTSET3" ]; then xvfb-run --server-args="-ac" mvn verify -Pfirefox -Ptestset3; fi
    - if [ ! -z "$TESTSET2" ]; then xvfb-run --server-args="-ac" mvn verify -Pfirefox -Ptestset2; fi
    - if [ ! -z "$TESTSET1" ]; then xvfb-run --server-args="-ac" mvn verify -Pfirefox -Ptestset1; fi
    - mvn appengine:devserver_stop

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:

  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
  # turning of email for PR builds, get notified only on failure and change in status
  # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never

**Comment by ambarish2012** [comment]
@aswath-veersoft we do not have that specific docker file. The images that we offer are documented [here](http://docs.shippable.com/reference/machine-images-overview/). For your specific requirements, please build a custom image.
