### ISSUE TITLE
Network issue etc.

### ISSUE THREAD

**Issue by nmarjanovic** [Shippable/support#3605]
Hi,

As I run from private repository I can't provide some information. Sorry for that.

Server: Azure Cloud VM Ubuntu 16.04
Docker version: 1.13.0 [do you know that now default is docker-ce and not docker-engine,just saying]

What happen today?

All started today after resetting private build node to get last version of shippable agent v5.5.4. Then I run to some network issues from your servers, but that is not all ...

First error[warning] on my side is:

'WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker
Pulling redis (redis:3.2.1-alpine)...'

2nd Issue
From settings I have option to select machine version, but you stopped updating that option from version v5.5.1, and if I try to selected from Settings>Machine Images, only option v5.5.1 [default] is available. When i click on '_Click here to see a complete list of what is available in each version_. ' i get this error:

403 Forbidden

    Code: AccessDenied
    Message: Access Denied
    RequestId: DCA*****
    HostId: 5BP****

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: AccessDenied
    Message: Access Denied

I tested on your node, as well on mine, same issue on both sides. Your script pull 2 containers, but not the same version.

drydock/u16pytall:v5.5.1
shipimg/genexec:v5.5.4 

In the end builds not working and I'm blocked all day. If you need more information i will need a way to send private message to you.

**Comment by manishas** [comment]
@ambarish2012 @ric03uec  we need to look into this asap. It could affect everyone with BYON.

**Comment by ric03uec** [comment]
@nmarjanovic can you send me the subscription name you're using. my email is devashish[AT]shippable.com. we're currently investigating the workflow you're having problems with to repro the issue.
- as for your point about docker-ce vs docker-engine, we're aware of the changes and planning to use the updated version once we've tested it extensively

**Comment by ambarish2012** [comment]
@nmarjanovic the `Click here to see a complete list of what is available in each version` link is working now.

**Comment by nmarjanovic** [comment]
Thank you for your updates, hope to see all up and running again, ASAP.

**Comment by nmarjanovic** [comment]
Solution and update.

1. For users having this issue, first don't use last version of drydock/u1*pytall, for us drydock/u14pytall was good, to set this edit your shippable.yml file with

pre_ci_boot:
  image_name: drydock/u14pytall
  image_tag: v5.5.1

2. Error from 'Settings>Machine Images', is fixed 50%, open url from "Cleak here" give error page, but now you can pick version of node you want to run [if you don't run one of yours], v5.5.4 is not in this menu, but trust me it's better like that for now.

3.It will be nice from Shippable team to send mail to all users when they make 'BIG' changes, and like that they will update users about changes they made. GitKraken is doing that on every new version, you can do as well, just share information.
