### ISSUE TITLE
Bitbucket repo missing from enable project list

### ISSUE THREAD

**Issue by jacobperron** [Shippable/support#3607]
Currently, our team is unable to enable the project (private Bitbucket repository). I believe this is because we had unintentionally disabled (or removed) the project from Shippable and tried to re-enable builds. 

Tried syncing, but the repo still does not appear in the list.

The old link to Shippable project still works, but when attempting to trigger the build we get the following error:

```
(Id: 4004) postRun for :projectId 590b88be50821b07008250a2 returned error: Missing data: reqBody.type
verbose: projects|triggerNewBuildRequest|projectId:590b88be50821b07008250a2|_queueRun
```

Also, there is no longer a Shippable production key in the repo settings.

**Comment by ambarish2012** [comment]
@jacobperron we are investigating.

**Comment by ambarish2012** [comment]
@jacobperron you can go ahead and enable your project. I can see the project in your dashboard.

**Comment by jacobperron** [comment]
@ambarish2012 Thank you :+1:
