### ISSUE TITLE
404 Pages on Project Settings

### ISSUE THREAD

**Issue by herriojr** [Shippable/support#3609]
I don't know why I'd be getting 404 pages at the following URI

https://app.shippable.com/github/<owner\>/<project\>/settings/options

**Comment by trriplejay** [comment]
try https://app.shippable.com/subs/github/<owner>/<project>/settings/options

you're missing the 'subs' part of the url.

**Comment by herriojr** [comment]
what I mean is, I just click the settings link on the page -- I'm not explicitly typing in the URL

**Comment by trriplejay** [comment]
I see, my mistake. which page were you on where you found this bad link?

**Comment by herriojr** [comment]
Project dashboard.  I click on the settings link in the following page

https://app.shippable.com/github/upsidecommerce/node-server-chassis/status/dashboard

This issue seems to be on a per-project basis

**Comment by trriplejay** [comment]
It seems like you don't have proper permissions to access the project in your link above. This would explain why you get the 404. was that project deleted from github?

**Comment by herriojr** [comment]
No, it exists in github and I have admin privileges.

**Comment by herriojr** [comment]
actually, don't worry about it just deleted the project and try again.
