### ISSUE TITLE
No way of cancelling builds

### ISSUE THREAD

**Issue by moltar** [Shippable/support#361]
I have produced a rogue build yaml file that installs a package via apt-get, but I forgot to add the "-y" flag and now the build got stuck and minion won't free up, because apt-get threw in a prompt to confirm the install. It's been 2 hours. I am not sure if there is a timeout or something, but a UI button to abort the build would be nice.

I also tried deleting the repo, and adding it again, and deleting minions and adding a new one. But it seems like the new minion always picks up the old job anyway and the new one is always stuck in "queued" status.

Minion ID: 53e22ff7e5f3d56900ea6d97

**Comment by fieldawarepiotr** [comment]
@avinci can you point me to a link?

**Comment by avinci** [comment]
http://docs.shippable.com/ci/cancel-builds/#canceling-builds

**Comment by eddwardo** [comment]
@avinci This is not what I am looking for. I'd like to be able to cancel build from shippable.yml. Is there a `command` that I can invoke to cancel (or abort, but not fail) the build?
