### ISSUE TITLE
slack notifications - please rework format to be useful?

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3610]
With shippable's slack notifications - when it triggers slack's own notifier triggering OSX notifications (I know, right?), the message displayed is.... less than useful:

![image](https://cloud.githubusercontent.com/assets/1108844/26430087/fd52b068-40b8-11e7-8609-0b50c18fbe32.png)

The message in the slack client is relatively useful:

![image](https://cloud.githubusercontent.com/assets/1108844/26430081/f2473360-40b8-11e7-9682-af94c009acf1.png)

I believe the simply fix would be to add the build status part (`[repo:branch] BUILD # STATE`) as the first line in the message body (or whatever that section is that starts with the date.

Might be useful to truncate that in some way to fit the apparent 29 character field in the OSX notification as well.

To reproduce this,  just set a slack notification to notify you directly `@you` instead of a channel (`#channel`) and turn on 1:1 notifications in the slack client.

**Comment by keen99** [comment]
mobile notification would get better with the same fix... :)

![image](https://cloud.githubusercontent.com/assets/1108844/26432829/83802a36-40cc-11e7-8d8f-a3fffbc30ee2.png)

**Comment by manishas** [comment]
@ambarish2012 let's add this to our backlog. It's almost a bug :)

**Comment by manishas** [comment]
This is currently being worked on.... consolidating all Slack requests in https://github.com/Shippable/support/issues/2650

Closing as a duplicate... 2650 will be updated when this is available.
