### ISSUE TITLE
links to old docs are 403s

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3615]
there seems to have been some sort of recent `docs` platform migration.

trying to find docu is now super painful - links that worked a week or two ago (open in my browser even) now return 403s.  most google search results, support issues, and everything else link to 403s.

for example:

this issue:
https://github.com/Shippable/support/issues/2380
links to:
http://docs.shippable.com/ci_configure/#caching-your-container

which returns

```
403 Forbidden

    Code: AccessDenied
    Message: Access Denied
    RequestId: D10B83659DF3CADD
    HostId: Uw97znGiOmNKuiKAWE6hRK4hEahlz4jmd6GlXKAyjn3MTuNAVDzH1ojqM2iDvLkguqEl2yxltxQ=

An Error Occurred While Attempting to Retrieve a Custom Error Document

    Code: AccessDenied
    Message: Access Denied
```

it would be really really really nice if there were some useful redirects going on instead of 403s.

**Comment by ambarish2012** [comment]
@keen99 we did rewrite our docs and I apologize for the broken links -  I will fix that link asap. In the meantime, we have built a new search feature and you can search for caching to find the relevant document.

**Comment by ambarish2012** [comment]
@keen99 I updated the links in the support issue. We have had 2 rewrites to our documentation since the support issue was published and wherever possible, we have created redirects.
