### ISSUE TITLE
Build Status Not Updating In GitHub

### ISSUE THREAD

**Issue by katelynmcgovern** [Shippable/support#3617]
Hello,

Today we have begun running into an issue where builds are correctly being submitted and run, but our build status display in GitHub does not update beyond "Waiting" even when the status of the build changes or when the build successfully completes.

This issue is affecting our ability to merge any pull requests for the time being as a returned "Success" from Shippable is required to merge.  Please let me know if any further details are required - thank you for your assistance!

**Comment by manishas** [comment]
@katelynmcgovern we are investigating.

**Comment by trriplejay** [comment]
We've released a patch to fix this issue. If you re-run the PR build it should correctly update the status. please let us know if it's not working for you.

**Comment by katelynmcgovern** [comment]
Thanks for the update, will try it out and let you know.
