### ISSUE TITLE
build not updating status in github

### ISSUE THREAD

**Issue by kylape** [Shippable/support#3618]
The build succeeds in the shippable UI, but the status is not being updated on the PR.

https://app.shippable.com/github/RedHatInsights/insights-plugins/runs/293

**Comment by manishas** [comment]
@trriplejay we need to look at this asap. This is a CQD issue.

**Comment by trriplejay** [comment]
We've released a patch to fix this issue. If you re-run the PR build it should correctly update the status. please let us know if it's not working for you.

**Comment by kylape** [comment]
It's working now.  Thanks.
