### ISSUE TITLE
BUILD_NUMBER - can this be reset to a custom starting point?

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3619]
working on migrating some builds off of jenkins, and the auto incrementing BUILD_NUMBER is a direct component of our build versioning.  with other systems I've used, there's a mechanism to set this to a known starting point to facilitate migrations or other reset-causing events.

Is there a way to reset this for shippable CI builds?  (pipeline side has version resources, etc, which have a way to be reset, but this is shippable.yml CI side that I need)

**Comment by manishas** [comment]
@keen99 we should be able to help with this on the backend.  What do you want to set the build number to and for which project(s)?


cc @trriplejay @rageshkrishna

**Comment by ambarish2012** [comment]
@keen99 do you need any further assistance on this ticket?
