### ISSUE TITLE
Gitlab Integration

### ISSUE THREAD

**Issue by christianmoretti** [Shippable/support#3620]
### Description of your issue:
Hi, I'm trying integrate Shippable with a custom Gitlab, but when I'll enable an project I got this error:

```
(Id: 4001) getValidCollaboratorByProjectId for projectId 592a028685f2a2070064763a returned an error: Failed to get valid collaborator account for project :id 592a028685f2a2070064763a
verbose: projects|getById|callerId:58dc005bcd6d820800ef9efd|projectId:592a028685f2a2070064763a|_getValidCollaborator
```

Anybody can help identify what I missing?

**Comment by deepikasl** [comment]
@christianmoretti can you please check whether you have read/write (collaborator)permission for that project in GITLAB once.
This error only comes when your are un-authorized.

**Comment by christianmoretti** [comment]
Hi @deepikasl,

I've created a new user and the permission is Master, but I still getting this error:
```
(Id: 4001) getValidCollaboratorByProjectId for projectId 592a037485f2a207006476c0 returned an error: Failed to get valid collaborator account for project :id 592a037485f2a207006476c0
verbose: projects|getById|callerId:592a089d85f2a2070064780b|projectId:592a037485f2a207006476c0|_getValidCollaborator
```

<img width="939" alt="imagem_colada_29_05_17_10_03" src="https://cloud.githubusercontent.com/assets/1626925/26550881/382967d6-4456-11e7-8de6-c3ce4c5a5512.png">

**Comment by christianmoretti** [comment]
Also, I'm trying find the problem and I can perform requests do endpoint and get information of my own project:

```
curl --header "PRIVATE-TOKEN: **the same token in gitlab integration**" https://gitlab.fractaltecnologia.com.br/api/v4/projects/36/members
[{"name":"Administrator","username":"root","id":1,"state":"active","avatar_url":"https://secure.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80\u0026d=identicon","web_url":"https://gitlab.fractaltecnologia.com.br/root","access_level":40,"expires_at":null}]
```

**Comment by shrivara** [comment]
@christianmoretti Could you update the account integration to use the `v3` Gitlab end-point instead and see if it works?

**Comment by christianmoretti** [comment]
Hi @shrivara,
The integration has been updated to use the `v3` endpoint but the error remains:
![imagem_colada_30_05_17_11_12-1](https://cloud.githubusercontent.com/assets/1626925/26587689/68d4c78a-4529-11e7-830f-5985e5c53153.png)

and when I'll enable the project:
![imagem_colada_30_05_17_11_14-2](https://cloud.githubusercontent.com/assets/1626925/26587723/81d64b50-4529-11e7-83c2-163fd2195a43.png)

Gitlab-CE v9.2.0
Best regards.

**Comment by shrivara** [comment]
We've seen this problem before when the reverse proxy unescapes the API call we make to get the project. Could you follow the guide here: https://github.com/Shippable/support/issues/3243#issuecomment-268552005 and see if it helps?

**Comment by christianmoretti** [comment]
Hi @shrivara,
Many thanks for help, now it works 👍 
I have to improve the configuration of Apache with this configs:

```
AllowEncodedSlashes NoDecode

ProxyPass "/" "http://localhost:8081/" nocanon
ProxyPassReverse "/" "http://localhost:8081/"
```

Best regards.
