### ISSUE TITLE
excess logs

### ISSUE THREAD

**Issue by aswath-veersoft** [Shippable/support#3622]
There are lot of log lines.   For example. There are 600 lines for the following message.
Resolving selenium-release.storage.googleapis.com (selenium-release.storage.googleapis.com)... 216.58.218.240, 2607:f8b0:4004:80a::2010
Connecting to selenium-release.storage.googleapis.com (selenium-release.storage.googleapis.com)|216.58.218.240|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21231092 (20M) [application/java-archive]
Saving to: ‘selenium-server-standalone-2.53.1.jar’

     0K .......... .......... .......... .......... ..........  0% 16.6M 1s
    50K .......... .......... .......... .......... ..........  0% 34.3M 1s
   100K .......... .......... .......... .......... ..........  0% 45.7M 1s
   150K .......... .......... .......... .......... ..........  0% 95.0M 1s
   200K .......... .......... .......... .......... ..........  1% 53.0M 1s
   250K .......... .......... .......... .......... ..........  1%  138M 0s
   300K .......... .......... .......... .......... ..........  1%  130M 0s
   350K .......... .......... .......... .......... ..........  1% 72.4M 0s
   400K .......... .......... .......... .......... ..........  2%  143M 0s
   450K .......... .......... .......... .......... ..........  2% 64.8M 0s
   500K .......... .......... .......... .......... ..........  2%  161M 0s
   550K .......... .......... .......... .......... ..........  2%  145M 0s
   600K .......... .......... .......... .......... ..........  3%  138M 0s

Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/codehaus-parent/4/codehaus-parent-4.pom (5 KB at 588.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/versions-maven-plugin/2.1/versions-maven-plugin-2.1.jar
3/237 KB   
5/237 KB   
8/237 KB   
11/237 KB   
13/237 KB   
16/237 KB   
19/237 KB   
21/237 KB   
24/237 KB   
27/237 KB   
29/237 KB   
32/237 KB   
36/237 KB   
40/237 KB   
44/237 KB   
48/237 KB   ....

Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/mojo-parent/30/mojo-parent-30.pom (27 KB at 1182.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/gwt-maven-plugin/2.6.1/gwt-maven-plugin-2.6.1.jar
3/189 KB   
5/189 KB   
8/189 KB   
11/189 KB   
13/189 KB   
16/189 KB   
19/189 KB   
21/189 KB   
24/189 KB   
27/189 KB   
29/189 KB   
32/189 KB   
36/189 KB   
40/189 KB   
44/189 KB   
48/189 KB   .....

Downloading: file:///root/src/github.com/aswath-veersoft/githubaccguru/libs/gwt-visualization/gwt-visualization/1temp.0/gwt-visualization-1temp.0.jar
88/404 KB   356/2191 KB   48/107 KB   344/695 KB   
92/404 KB   356/2191 KB   48/107 KB   344/695 KB   
96/404 KB   356/2191 KB   48/107 KB   344/695 KB   
63/63 KB   72/404 KB   10/10 KB   356/2191 KB   344/695 KB   
100/404 KB   356/2191 KB   48/107 KB   344/695 KB   4/233 KB   
100/404 KB   360/2191 KB   48/107 KB   344/695 KB   4/233 KB   
104/404 KB   360/2191 KB   48/107 KB   344/695 KB   4/233 KB   
104/404 KB   364/2191 KB   48/107 KB   344/695 KB   4/233 KB   
108/404 KB   364/2191 KB   48/107 KB   344/695 KB   4/233 KB   
108/404 KB   368/2191 KB   48/107 KB   344/695 KB   4/233 KB   
112/404 KB   368/2191 KB   48/107 KB   344/695 KB   4/233 KB   
112/404 KB   372/2191 KB   48/107 KB   344/695 KB   4/233 KB   
116/404 KB   372/2191 KB   48/107 KB   344/695 KB   4/233 KB   
116/404 KB   376/2191 KB   48/107 KB   344/695 KB   4/233 KB   
120/404 KB   376/2191 KB   48/107 KB   344/695 KB   4/233 KB   
120/404 KB   380/2191 KB   48/107 KB   344/695 KB   4/233 KB   
124/404 KB   380/2191 KB   48/107 KB   344/695 KB   4/233 KB   
124/404 KB   384/2191 KB   48/107 KB   344/695 KB   4/233 KB   
128/404 KB   384/2191 KB   48/107 KB   344/695 KB   4/233 KB   
128/404 KB   388/2191 KB   48/107 KB   344/695 KB   4/233 KB   
132/404 KB   388/2191 KB   48/107 KB   344/695 KB   4/233 KB   
132/404 KB   392/2191 KB   48/107 KB   344/695 KB   4/233 KB   
136/404 KB   392/2191 KB   48/107 KB   344/695 KB   4/233 KB   
136/404 KB   396/2191 KB   48/107 KB   344/695 KB   4/233 KB   
140/404 KB   396/2191 KB   48/107 KB   344/695 KB   4/233 KB   
140/404 KB   400/2191 KB   48/107 KB   344/695 KB   4/233 KB   
144/404 KB   400/2191 KB   48/107 KB   344/695 KB   4/233 KB   
144/404 KB   404/2191 KB   48/107 KB   344/695 KB   4/233 KB   .....

There are 49l line, before my actual application logs begin.  

Please see the logs for the following link
https://app.shippable.com/github/aswath-veersoft/githubaccguru/runs/22/2/console

Thanks.

**Comment by aswath-veersoft** [comment]
Please close this.  I used mvn -B switch.

**Comment by kanthchandra** [comment]
Cool! Thanks for confirming.
