### ISSUE TITLE
Build done with errors

### ISSUE THREAD

**Issue by aswath-veersoft** [Shippable/support#3624]
Hi, 
I have 5 builds.
The first build write all the test results
Tests run: 13, Failures: 2, Errors: 9, Skipped: 0
But, at the end it says
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/5074235b-966e-46db-97db-3d4e4058a025.sh'
Exception Script failure tag received
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/5074235b-966e-46db-97db-3d4e4058a025.sh'

The 2n build does not write the test results like the above
It says 'Killed'
and then, 
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/150b204e-9acd-4617-b4f2-8fb7691c8c97.sh'
echo 'No test reports exist, skipping test report processing'
No test reports exist, skipping test report processing

Same, with the remaining builds.
See https://app.shippable.com/github/aswath-veersoft/githubaccguru/runs/23/summary

**Comment by kanthchandra** [comment]
Hi @aswath-veersoft have you tried the suggestions that I had mentioned here https://github.com/Shippable/support/issues/3596#issuecomment-302364038 .

**Comment by aswath-veersoft** [comment]
The tests were running fine in minimal snap-ci plan.  Does your free plan machines have very low memory.

**Comment by kanthchandra** [comment]
Our build Machines have 2 cores, 3.75 GB RAM each. I'm not telling that memory is the definitely the cause, but I guess it's worth investigating if memory is the cause. Can you trigger and build and after the second build fails add a comment here so that I will look at the memory consumption on the build machine?

**Comment by ambarish2012** [comment]
@aswath-veersoft to understand the machines sizes offered in free and paid plans, please visit - http://docs.shippable.com/getting-started/billing-overview/.
