### ISSUE TITLE
Build stops without further output

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3625]
We currently see builds failing for one of our projects (591af55a2fd3990700d446d0) without apparent reason. The output suddenly stops and only newlines appear.

Oddly the `build_ci` steps shows no icon at all, neither success nor error:

![image](https://cloud.githubusercontent.com/assets/5037116/26588013/5118a5b4-4554-11e7-84eb-991e3e0eb3db.png)

You can see this e.g. in run 20 of that project.

**Comment by ambarish2012** [comment]
@mbrodala we are investigating.

**Comment by ambarish2012** [comment]
@mbrodala I downloaded the console logs. 

The reason we are not reporting failure is because CHECKSTYLE is logging a lot of empty lines and suddenly exiting. Please can you take a look.

You can see this in the downloaded console logs, which indicates that some command exited abruptly - 

```
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/0eb192d5-a4dc-498c-842c-d20c2a640413.sh'

Exception Invalid or no script tags received
```

**Comment by mbrodala** [comment]
The actual command is `bin/typoscript-lint` but we'll have a look, thanks.

**Comment by mbrodala** [comment]
After fixing all warnings of that linter the build now runs through just fine, so the issue seems resolved for now.
