### ISSUE TITLE
Build failure - Docker Hub login fails with Internal Server Error

### ISSUE THREAD

**Issue by asans** [Shippable/support#3627]
### Description of your issue:
Our builds are currently failing without any updates to existing shippable.yml nor credentials.  Upon further checking, I'm seeing the error showing:

```
 hub_login 0s
  echo 'Hub login failed' 0s  
  echo 'Docker login failed for username vpsci and email ci@evirtualpost.com' 0s  
  echo 'Error response from daemon: Internal Server Error'
```

https://app.shippable.com/github/virtualpost/vpm-ui-desktop/runs/289/1/console

Credentials have not changed for docker hub.  I've retested this.

**Comment by trriplejay** [comment]
looks like docker hub is having some problems right now: https://status.docker.com/

**Comment by trriplejay** [comment]
docker hub issues should be resolved now. Let us know if you're still experiencing this error.
