### ISSUE TITLE
API Integration

### ISSUE THREAD

**Issue by christianmoretti** [Shippable/support#3628]
Hi, I'm trying use the API to trigger a new build, but I get an error:

```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization:apiToken *****' -d '{ "branchName": "master" }' 'https://api.shippable.com/projects/592de7ac39c3920700a83ceb/newBuild'
```
Response:
```
{"logType":"warn","methodName":"projects|triggerNewBuildRequest|projectId:592de7ac39c3920700a83ceb|_queueRun","id":2000,"message":"postRun for :projectId 592de7ac39c3920700a83ceb returned error: access denied to route: /runs"}
```
and I don't see any build running, anybody can help to identify what I missing?
Thanks.

**Comment by ankul-shippable** [comment]
@christianmoretti one reason this can happen is that your permissions for this project are not synced. Can you try syncing your account by going to Account Settings tab and clicking `sync`. You should be a collaborator or admin/owner for a project to be able to trigger builds.
If this still happens can you please send me your `Shippable Id`(in account settings tab) at `ankul at shippable dot com`.

**Comment by ambarish2012** [comment]
@christianmoretti API is available to only paid customers.

**Comment by kanthchandra** [comment]
Hi @christianmoretti I looked at the logs for your project and it looks like you are trying to make an newBuild API call with one of the tokens that you created. The builds can only be triggered from the API only if you are a paid user.
