### ISSUE TITLE
Deployments to Kubernetes appends a long string to the name

### ISSUE THREAD

**Issue by rhenretta** [Shippable/support#3631]
When I do a deploy to a kubernetes cluster, shippable appends a long string, such as 
`-9d7ebeb5-6f2f-4f5e-ad3e-cb9552b96756`

The max length of a label is 63 characters, so this causes a build to fail if the name is more than 26 characters.

The most obvious fix here is to only append that string up to a max length of 63 characters.

**Comment by trriplejay** [comment]
Thanks for reporting. We've opened an internal issue to resolve this.

**Comment by manishas** [comment]
@rhenretta this is now fixed. Please check out http://docs.shippable.com/deploy/kubernetes/#customizing-deployment-names

Also, names longer than 63 characters will be truncated.
