### ISSUE TITLE
Run git config --global before git_sync step in CI build

### ISSUE THREAD

**Issue by kileyhykawy** [Shippable/support#3632]
### Description of your issue:
I am trying to enable private git submodules as per http://docs.shippable.com/ci/git-submodules/ and realized that I need to specify the submodule URL in the main repo as an SSH URL (e.g. `git@github.com:someuser/somelibrary.git`). However, this doesn't work for us because then all of the developers need to use SSH and would like to avoid that if possible (right now, we are using HTTPS with user name/password stored in Git credential keyrings).

One option we have is to configure Git on the CI server to rewrite the URL:
```
git config --global url.git@bitbucket.org:.insteadOf https://bitbucket.org/
```

However, I can't find a place to do this before the `git_sync` build step. `ci` is too late and `pre_ci` is outside of the CI container. Any thoughts on how/where I could run this git configuration command?

Thanks!

**Comment by ambarish2012** [comment]
@kileyhykawy here is something you could try  -

1. Setup your username and password in environment variables (secure environment variable for the password).

2. In the very first command in your build/ci section, use the git sync command that your developers are using to sync the submodule over https but with the username and password specified in the environment variables. 

This approach would work assuming the git sync for the main repo works - which means you do not have any config in .gitmodules and .git/config for private submodules.

**Comment by ambarish2012** [comment]
@kileyhykawy if you want to turn off all submodules, follow the steps here - http://docs.shippable.com/ci/git-submodules/#turning-off-submodules.

**Comment by kileyhykawy** [comment]
@ambarish2012, I think I see where you are going with this.

1. Disable git submodules for shippable so that it doesn't try to do the sync and fail.
2. Then configure whatever I want in `build/ci` and do the `git sync` and `git update` myself either using HTTPS credentials or even doing the global git config I mentioned (and still use SSH for CI builds).

This sounds like a good option. Thanks!
