### ISSUE TITLE
Website unusable in Firefox

### ISSUE THREAD

**Issue by JaZo** [Shippable/support#3633]
I keep getting errors when opening the site in Firefox, making it unusable. Sometimes it works after ~10 page refreshes, but having two tabs opened never works.

![afbeelding](https://cloud.githubusercontent.com/assets/3475007/26683251/7dbdef12-46e3-11e7-83c0-dedba6d43317.png)

**Comment by ambarish2012** [comment]
@JaZo which version of Firefox are you using and on which OS / OS version?

**Comment by JaZo** [comment]
I'm using Firefox Developer Edition 54.0a2 (64-bits) on Windows 10

**Comment by ambarish2012** [comment]
@JaZo we will test on that version and get back to you. A couple of questions -

1) Does the website work in Chrome/Edge on your OS?

2) Instead of a screenshot, please can you cut and paste the error and post it here in english if possible?

**Comment by JaZo** [comment]
1. It works on Chrome 58.0.3029.110 (64-bit), Edge 38.14393.1066.0 and Firefox (Regular Edition) 53.0.3 (32-bit)
2. Logs in English text:
- Firefox can't connect with the server on wss://app.shippable.com/socket.io/?EIO=3&transport=websocket. (socket.io.js:4026:31)
- The connection with wss://app.shippable.com/socket.io/?EIO=3&transport=websocket was interrupted during page load. (socket.io.js:4026:31)
- : (socket.io.js:4026)
- Error: [$injector:undef] http://errors.angularjs.org/1.3.15/$injector/undef?p0=websocketConnection (lib.min.js:20:18199)

**Comment by ambarish2012** [comment]
@JaZo we will follow up with Firefox team. For the time being, please use any of the other browsers that are working.

**Comment by JaZo** [comment]
Ok, thanks! I just updated Firefox Developer Edition to the latest version (54.0b12) and the problem seems to be gone!

**Comment by ambarish2012** [comment]
ok great - thanks for letting us know.
