### ISSUE TITLE
Zip error on Elastic Beanstalk deploy

### ISSUE THREAD

**Issue by sumothecat** [Shippable/support#3634]
This just started happening for no obvious reason. Can't be our code, I don't think. 

From log:
eb deploy --staged -l shippable.deli-lidar.lidar.112 14s  
Creating application version archive "shippable.deli-lidar.lidar.112".
ERROR: ValueError :: ZIP does not support timestamps before 1980

Furthermore the build does not report failing, even though this error is occurring. 

- Link to the build failure
https://app.shippable.com/github/jncc/deli/runs/112/1/console

**Comment by ambarish2012** [comment]
@sumothecat the error is coming from the git archive command used by eb deploy (http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-deploy.html). To debug further run eb deploy with --debug -v options.

**Comment by sumothecat** [comment]
@ambarish2012 the eb deploy command is not being run by our script, but by Shippable's deploy configuration for eb_paas. So I don't know how to pass options to it. 

This doesn't happen in dev environment - it looks like some change in the Shippable build environment. 

The only reference I can find to this error with eb depoy is https://stackoverflow.com/questions/31166275/elastic-beanstalk-cli-deploy-zip-error

**Comment by sumothecat** [comment]
Update: This is reproducible after a full clean of node_modules - apologies @ambarish2012 
For reference, seems to be due to an issue with Uglify.js 
https://github.com/aws/aws-cli/issues/2639

**Comment by sumothecat** [comment]
For info, I added these lines to the end of the build: ci: section of shippable.yml

    # workaround uglify.js shipping with 1969 timestamps
    - touch -t 200001010000 /tmp/timestamp # make a file with a timestamp of the year 2000
    - find . ! -newer /tmp/timestamp -exec touch -t 201701010000 '{}' \; # update all files with earlier timestamps

**Comment by fdintino** [comment]
For cross-reference, here is the uglifyjs issue: mishoo/UglifyJS2#2054
