### ISSUE TITLE
Builds are succeeding and not calling GitHub webhooks 

### ISSUE THREAD

**Issue by grouxsome** [Shippable/support#3636]
### Description of your issue:
Builds are succeeding and not calling GitHub webhooks. We have seen this sporadically for a few days now. 

Latest victim is:

https://app.shippable.com/github/zenreach/platypus/runs/8147/1/console

<img width="744" alt="screen shot 2017-06-05 at 2 40 29 pm" src="https://cloud.githubusercontent.com/assets/4642501/26798041/25ac22ea-49fd-11e7-9fcd-4adcdcdd5995.png">

**Comment by ambarish2012** [comment]
@grouxsome we are investigating.
