### ISSUE TITLE
Builds failing with 

### ISSUE THREAD

**Issue by adriennedomingus** [Shippable/support#3637]
### Description of your issue:
All builds, including master (which was passing when last pushed) are now failing with `Segmentation fault      (core dumped)`

Sample build: https://app.shippable.com/bitbucket/everpath/course-platform/runs/3856/1/console

**Comment by ambarish2012** [comment]
@adriennedomingus we are investigating.

**Comment by ambarish2012** [comment]
@adriennedomingus what is crashing is this command -

```
coverage run --branch --source='.' manage.py test --with-xunit --xunit-file='shippable/testresults/xunittest.xml' --verbosity=3
request_id=no_request_id 139870366058240 WARNING py.warnings:22 __new__() /home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)
```

We diffed your last successful with your current failed run and found the following -

1. Compilation errors

```Compiling /home/shippable/build_ve/python/2.7/build/zeep/zeep/asyncio/bindings.py ...
SyntaxError: ('invalid syntax', ('/home/shippable/build_ve/python/2.7/build/zeep/zeep/asyncio/bindings.py', 8, 13, '    async def send(self, client, options, operation, args, kwargs):\n'))

Compiling /home/shippable/build_ve/python/2.7/build/zeep/zeep/asyncio/transport.py ...
SyntaxError: ('invalid syntax', ('/home/shippable/build_ve/python/2.7/build/zeep/zeep/asyncio/transport.py', 38, 17, '        async def _load_remote_data_async():\n'))
```

Would these impact the coverage run?

2) One dependency of a dependency was updated between your run and a successful run. 

lxml-3.7.3 to lxml-3.8.0

**Comment by adriennedomingus** [comment]
Thank you @ambarish2012 - The zeep errors pre-exist this change in build status, so not the issue. However, if we reorder our requirements.txt and ensure lxml is intstalled at 3.7.3 before it is required as a dependency at a different version, the build passes, so we will rework to ensure they are installed in the correct order. Appreciate the help.
