### ISSUE TITLE
Unable to delete old integrations for previous Orgs

### ISSUE THREAD

**Issue by adminfromhell** [Shippable/support#3639]
### Description of your issue:
I am unable to delete integrations for orgs that I am no longer a member of. The error I receive is below.

(Id: 4001) accountIntegrations.destroy failed for id:
verbose: accountIntegrations|deleteById|callerId:58fe2f5728b7f006008bccb2|accountIntegrationId:58fe30ed28b7f006008bce09|_deleteById
"58fe30ed28b7f006008bce09 returned error: update or delete on table \"accountIntegrations\" violates foreign key constraint \"subscriptionIntegrations_accountIntegrationId_fkey\" on table \"subscriptionIntegrations\""

**Comment by ambarish2012** [comment]
@adminfromhell please can you explain your use-case in detail. 

Did you originally create the account integration and give permissions to the orgs you are no longer a member of? Do current members of those orgs not have an account with Shippable and are thus unable to remove the integration?

**Comment by adminfromhell** [comment]
It was a company that I left that I had created the integrations on my account.

**Comment by ambarish2012** [comment]
@adminfromhell we have deleted the integrations.

**Comment by adminfromhell** [comment]
Thanks!
