### ISSUE TITLE
Language version with zero evaluated as integer

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3640]
It seems like Shippable (or its YAML parser) evaluates language versions ending with `.0` as integer values.

Thus given the following snippet:

```yaml
language: php

php:
  - 7.0
```

This leads to a build with PHP version `7` instead of `7.0`, thus `phpenv` fails and leaves the default PHP version instead, thus e.g. `7.1`:

```
setup_php
  /usr/local/bin/phpenv-install 7 1s  
  [Error]: Definition 7 not found.

  eval "$(phpenv init -)"

  /root/.phpenv/bin/phpenv global 7
  rbenv: version `7' not installed

  php --version
  PHP 7.1.1 (cli) (built: Mar 29 2017 11:29:38) ( NTS )
  Copyright (c) 1997-2017 The PHP Group
  Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

This issue can be worked around by using `"7.0"` instead of `7.0` which is less than ideal, especially given the [official docs use regular float numbers](http://docs.shippable.com/ci/php-continuous-integration/#setting-language-and-runtime).

**Comment by manishas** [comment]
@ambarish2012 can we correct the docs to say that language version need to be in double quotes if the version has a 0 at the end? We already say this for Node, so just say the same thing for Python.

http://docs.shippable.com/ci/nodejs-continuous-integration/

```
If you want to test against several versions of Node.js, you can specify multiple runtimes. The snippet below will trigger 2 builds, one against each version:

node_js:
  - "0.10"
  - "7.0.0"

Please note that the 0.10 version is inside double quotes. This is to prevent our parser from incorrectly interpreting the language version to be 0.1. For any version ending with a 0, remember to use double quotes around the version number.
```

**Comment by ambarish2012** [comment]
ok makes sense - updating it now.

**Comment by ambarish2012** [comment]
Docs are updated - @mbrodala thanks for letting us know.

**Comment by mbrodala** [comment]
@ambarish2012 Thanks. Can you add the _Please note_ to the PHP docs, too? Otherwise people will most likely simply not notice this.

**Comment by ambarish2012** [comment]
Its already documented - http://docs.shippable.com/ci/php-continuous-integration/. You might have  to refresh that page in your browser.

**Comment by mbrodala** [comment]
Ah, you're right. I've looked in _Setting language and runtime_ instead of _Basic configuration_ above. ;-)
