### ISSUE TITLE
Console View is Small

### ISSUE THREAD

**Issue by jasonkemm** [Shippable/support#3642]
### Description of your issue:
The Console window is tiny (only 500px really?), Can you enable css resizing with the window size please?

![screen shot 2017-06-08 at 10 48 54 am](https://user-images.githubusercontent.com/478188/26940647-b3d52de0-4c38-11e7-8760-3c1c682a3d8f.png)

**Comment by ambarish2012** [comment]
@jasonkemm we are tracking this bug in our backlog.

**Comment by jasonkemm** [comment]
@ambarish2012 Thank you!

**Comment by avinci** [comment]
this has been fixed in the new UI we launched a couple of weeks ago. Please switch the UI to new UI if you have not been already moved. Everyone will be moved in the first week of July.
