### ISSUE TITLE
Using --net=host causes builder to segv for 5.5.1 and 5.6.1 images

### ISSUE THREAD

**Issue by santtu** [Shippable/support#3643]
See https://github.com/Shippable/support/issues/3232 for more detailed background on this. 

The short version: I need to access a docker container from the build host. This is possible to accomplish with 5.4.1 (and older) image versions using the following shippable.yml configuration:

```
build:
    pre_ci_boot:
      options: "--net=host"
```

However 5.5.1 and 5.6.1 will fail during builder setup with a segv:

```
/home/shippable/cexec/build.sh: line 131:    18 Segmentation fault      (core dumped) $SUDO mkdir -p /shippableci
```

Here's a failed build with 5.5.1 image (https://app.shippable.com/bitbucket/sanoste/sassy/runs/3057/1/console) and with 5.6.1 image (https://app.shippable.com/bitbucket/sanoste/sassy/runs/3056/1/console).

**Comment by ambarish2012** [comment]
@santtu this is a known bug that we are investigating.

**Comment by rageshkrishna** [comment]
I discovered a conversation at Docker that deals with this exact problem: https://github.com/moby/moby/issues/5899

@santtu Can you please add `--pid=host` as an option in your `pre_ci_boot` like this:

````yaml
build:
  pre_ci_boot:
    image_name: foo/bar
    image_tag: latest
    options: "--net=host --pid=host"
````

This should unblock you while we figure out how to fix this at a platform level.

**Comment by santtu** [comment]
@rageshkrishna Using `--pid=host` allows the build to continue with the 5.6.1 image successfully. So that works at the moment as a workaround.
