### ISSUE TITLE
Builds randomly skipping with "You do not have any custom nodes to run this job"...

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3644]
We do have a custom node, which I reset today, thinking the agent version might be the issue, but I'm still getting this message. Meanwhile, the custom node is marked as inactive.

![screen shot 2017-06-09 at 3 39 36 pm](https://user-images.githubusercontent.com/1018189/26991852-1bc4018c-4d2a-11e7-9cdc-c1fedc5b852b.png)

**Comment by ambarish2012** [comment]
@ryan-kimber we are investigating.

**Comment by ambarish2012** [comment]
@ryan-kimber I clicked on your custom node and saw this error -
```
Node stopped due to insufficient space.
  The node has been stopped as disk usage exceeds 90%. Please free up disk space and reset the node to allow builds to continue on this node.
```

Did you free up disk space and then reset the node?

**Comment by ryan-kimber** [comment]
Thanks. I've expanded the disk for the node, restarted it, reset it in Shippable, and now it's working again.
