### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by aswath-veersoft** [Shippable/support#3645]
Hi, I have the following .yml file.  I want to add the node also.
----------------------
language: java

jdk:
   - oraclejdk7

env:
  - JUNIT4SET=true
  - TESTSET5=true
  - TESTSET4=true
  - TESTSET3=true
  - TESTSET2=true
  - TESTSET1=true

addons:
  firefox: "26.0"

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    - "export DISPLAY=:99.0"

    - if [ ! -z "$JUNIT4SET" ]; then xvfb-run --server-args="-ac" mvn -B verify -Pfirefox -Pjunit4testset; fi
    - if [ ! -z "$TESTSET5" ]; then xvfb-run --server-args="-ac" mvn -B verify -Pfirefox -Ptestset5; fi
    - if [ ! -z "$TESTSET4" ]; then xvfb-run --server-args="-ac" mvn -B verify -Pfirefox -Ptestset4; fi
    - if [ ! -z "$TESTSET3" ]; then xvfb-run --server-args="-ac" mvn -B verify -Pfirefox -Ptestset3; fi
    - if [ ! -z "$TESTSET2" ]; then xvfb-run --server-args="-ac" mvn -B verify -Pfirefox -Ptestset2; fi
    - if [ ! -z "$TESTSET1" ]; then xvfb-run --server-args="-ac" mvn -B verify -Pfirefox -Ptestset1; fi
    - mvn appengine:devserver_stop

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:

  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
  # turning of email for PR builds, get notified only on failure and change in status
  # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never

**Comment by ambarish2012** [comment]
@aswath-veersoft do you want to add node.js?

**Comment by ambarish2012** [comment]
We do not support multiple languages for a single project - so your best option is to install node.js using script. 

Add [this](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) command at the very beginning of your CI section.
