### ISSUE TITLE
`exit 0` should not fail a build (in `post_ci` command)

### ISSUE THREAD

**Issue by zx8** [Shippable/support#3646]
Exactly the same issue as: https://github.com/Shippable/support/issues/1141

I have the following step within `post_ci`:

```
[...]
- if [ "${BRANCH%feature/*}" = "" -o "$IS_PULL_REQUEST" = true ]; then exit 0; fi
[...]
```

And the build is marked as failed – it should be successful as a return status of 0 is not an error.

**Comment by ambarish2012** [comment]
@zx8 will file a bug and let you when the fix is deployed.

**Comment by ambarish2012** [comment]
@zx8 I am sorry that we will not be able to support `exit 0` anytime soon. We will keep this request in our backlog however and consider it in a future design iteration. 

In the meantime, I would recommend that you use if - else blocks to workaround this limitation.
