### ISSUE TITLE
Failure to locate build context within Docker daemon 

### ISSUE THREAD

**Issue by athrane** [Shippable/support#3647]
Hi,

I have been trying to implement a part of the build documented in your example:
https://github.com/shippableSamples/java-ecr-runcli-elasticbeanstalk, but I have a problem accessing the build context within the Docker daemon, i.e. I can't find my files.

**Some details**

In my shippable.yml, I copy the binary to be included in the Docker image to a staging/target directory using the commands:

```
  post_ci:
  - mkdir -p $SHIPPABLE_BUILD_DIR/dockersrc  
  - cp $SHIPPABLE_BUILD_DIR/src/ci/Dockerfile $SHIPPABLE_BUILD_DIR//dockersrc
  - cp /root/src/github.com/athrane/pineapple/applications/pineapple-web-application/pineapple-standalone-web-client/target/pineapple-standalone-web-client-*.zip $SHIPPABLE_BUILD_DIR/dockersrc 
``` 
The purpose is to minimize the size of the build context and speed up the build.

Then I build the Docker image using the staging directory:

```
  - docker build -t pineapple/pineapple:1.10.0 $SHIPPABLE_BUILD_DIR/dockersrc
  - docker push pineapple/pineapple:1.10.0 $SHIPPABLE_BUILD_DIR/dockersrc
```

For some reason I can't locate the the $SHIPPABLE_BUILD_DIR directory (and subdirectories) within the Docker daemon during execution of the Dockerfile. In the example Docker file provided by you (https://github.com/devops-recipes/ci-java-push-ecr/blob/master/Dockerfile) the Shippable build directory is referenced from within the Dockerfile:

` COPY $SHIPPABLE_BUILD_DIR/target/HelloWorld.war /usr/local/tomcat/webapps/HelloWorld.war
`
This doesn't work for me, thus I fail to locate my build context?! Please help.

**Link to the build failure**
https://app.shippable.com/github/athrane/pineapple/runs/112/1/console

**Scripts called from the yml (optional)**
https://github.com/athrane/pineapple/blob/master/shippable.yml
https://github.com/athrane/pineapple/blob/master/src/ci/Dockerfile

**Comment by ambarish2012** [comment]
@athrane we are investigating.

**Comment by athrane** [comment]
Thanks. I can add that I did try to build by adding the entire generated build context to the Docker image, using the Shippable build directory as input to the Docker build command and referencing the to the Shippable build directory from the Dockerfile. All as specified in the example but with no luck :-(

**Comment by ambarish2012** [comment]
@athrane you cannot use Shippable environment variables in your Dockerfile, since Docker is not aware of your shell environment variables. 

You have a couple of options -

1) Add this command in your yml before docker build - ```shippable_replace Dockerfile```. This will replace all your shippable env variables with their defined values in your Dockerfile.

2) Pass environment variables to Docker

https://docs.docker.com/engine/reference/commandline/build/#use-a-custom-parent-cgroup-cgroup-parent

docker build --build-arg SHIPPABLE_BUILD_DIR=$SHIPPABLE_BUILD_DIR <rest of your arguments>

**Comment by ambarish2012** [comment]
@athrane I am also updating the sample code.

**Comment by athrane** [comment]
@ambarish2012 Thank you for the answer. If this is the case, can you please explain what mechanism makes your example work (https://github.com/shippableSamples/java-ecr-runcli-elasticbeanstalk), where it seems to me that Shippable environment variables are used in the Dockerfile without resorting to either option #1 or #2. Did I miss something?

**Comment by athrane** [comment]
@ambarish2012  Should I use the command shippable_replace Dockerfile like this:

```
post_ci:
  - shippable_replace Dockerfile
  - mkdir -p $SHIPPABLE_BUILD_DIR/dockersrc  
  - cp $SHIPPABLE_BUILD_DIR/src/ci/Dockerfile $SHIPPABLE_BUILD_DIR//dockersrc
  - cp /root/src/github.com/athrane/pineapple/applications/pineapple-web-application/pineapple-standalone-web-client/target/pineapple-standalone-web-client-*.zip $SHIPPABLE_BUILD_DIR/dockersrc 
  - docker build -t pineapple/pineapple:1.10.0 $SHIPPABLE_BUILD_DIR/dockersrc
  - docker push pineapple/pineapple:1.10.0 $SHIPPABLE_BUILD_DIR/dockersrc
```

**Comment by ambarish2012** [comment]
@athrane you want to run shippable_replace with the right path to your Dockerfile. So ```shippable_replace  $SHIPPABLE_BUILD_DIR/dockersrc/Dockerfile``` just before your docker build command (and after ```cp $SHIPPABLE_BUILD_DIR/src/ci/Dockerfile $SHIPPABLE_BUILD_DIR/dockersrc```).

**Comment by athrane** [comment]
@ambarish2012  Thanks :-)

**Comment by athrane** [comment]
@ambarish2012 I tried your solution with:
`docker build --build-arg SHIPPABLE_BUILD_DIR=$SHIPPABLE_BUILD_DIR <rest of your arguments>`
.. but I failed to get it to work. Here is the output for the failed build: 
[https://app.shippable.com/github/athrane/pineapple/runs/115/summary/console](url)

Also, where can I find the build context within docker during the build of the image?

**Comment by athrane** [comment]
I have now tried to simplify the build:
```
 post_ci:
  - cp $SHIPPABLE_BUILD_DIR/src/ci/Dockerfile.shippable $SHIPPABLE_BUILD_DIR/Dockerfile
  - docker build --no-cache --build-arg SHIPPABLE_BUILD_DIR=$SHIPPABLE_BUILD_DIR -t pineapple/pineapple:1.10.0 $SHIPPABLE_BUILD_DIR
  - docker push pineapple/pineapple:1.10.0 $SHIPPABLE_BUILD_DIR
```

With full build context, none of my files are accessible during execution of the Dockerfile.
Link to see https://app.shippable.com/github/athrane/pineapple/runs/116/summary/console
