### ISSUE TITLE
Sample failing due to missing shippable.yml file

### ISSUE THREAD

**Issue by toomanyedwards** [Shippable/support#3648]
I am trying to run the sample described here: 
http://bharathshippablecom-demo.readthedocs.io/tutorials/pipelines/samplePipeline/

When I attempt to run the pipeline, I get:

 Errors  
Shippable needs a valid YML file to build your project.

The https://github.com/shippableSamples/samplePipelinesTest repo does not contain a shippable.yml file so appears the sample is broken.  How do I fix this?

**Comment by ambarish2012** [comment]
@toomanyedwards what sample are you looking for? The https://github.com/shippableSamples/samplePipelinesTest  sample project is for a pipeline and not CI.

If you are looking for a CI project, please fork [this sample](https://github.com/devops-recipes/basic-node). This samples builds a node.js app with unit tests and coverage reports using mocha and istanbul.

You will many CI samples in the devops-recipes github organization.

**Comment by toomanyedwards** [comment]
I finally figured that out through trial and error. The product is good, but the docs need a *lot* of help for anyone to find that out.  For example, seeding the pipeline is confusing.  The docs point to a link on how to seed the pipeline, but no where do those docs actually mention seeding.

**Comment by ambarish2012** [comment]
@toomanyedwards thanks for the feedback. We are looking for every opportunity to improve the usability of our documentation - please could you let me know which link and if you could elaborate more on seeding, I can take some action on improving that aspect of our documentation.

**Comment by rageshkrishna** [comment]
@toomanyedwards I think the problem is you were not on the right URL for our docs. The link in your first comment above seems to be an external fork of our docs that was hosted on readthedocs.io. Our official docs are at http://docs.shippable.com. I hope this helps.
