### ISSUE TITLE
postgis installation error

### ISSUE THREAD

**Issue by Kim-Andersen** [Shippable/support#3649]
Hi, I'm getting a build falilure when trying to install postgis as per the documention (http://docs.shippable.com/ci/postgresql/#using-postgis).

Link to failing build:
- https://app.shippable.com/github/Kim-Andersen/kiddo-server/runs/68/1/console

Any help is much appreciated.

Thanks,
Kim

**Comment by ambarish2012** [comment]
@Kim-Andersen we are investigating.

**Comment by ambarish2012** [comment]
@Kim-Andersen I would recommend moving to v5.6.1 version of our machine image which has postgis already installed. You can change the version here -
 https://app.shippable.com/subs/github/Kim-Andersen/settings/options.

Stable is an old and unsupported machine version.

**Comment by ambarish2012** [comment]
I will also update the docs.

**Comment by Kim-Andersen** [comment]
Okay, I tried the same build after changing to machine image v5.6.1, but the build still fails, with different error message though:

https://app.shippable.com/github/Kim-Andersen/kiddo-server/runs/71/1/console <https://app.shippable.com/github/Kim-Andersen/kiddo-server/runs/71/1/console>

**Comment by rageshkrishna** [comment]
It looks like you're still trying to install postgis. The 5.6.1 images come with postgis pre-installed so you should be able to just start using it directly.

**Comment by Kim-Andersen** [comment]
Got it, let me try...

**Comment by Kim-Andersen** [comment]
That did it. Thanks a lot :)

I want to mention you guys have excellent support. A detail like you say you will update the documentation, hence being proactive on the matter, makes all the difference. Much appreciated.

Have a good one.

Kim
