### ISSUE TITLE
Getting UnknownEndpoint attempting to deploy to Aws ECS

### ISSUE THREAD

**Issue by toomanyedwards** [Shippable/support#3650]
I am attempting to deploy to ECS.  This worked once, but subsequently I get am getting the error below.  It looks to me that potentially shippable needs to be calling AWS in another region.  I didn't see anywhere to set the AWS API region in the AWS integration.  How do I get past this?

Update: Attempting to use ECS via us-east-1b I see that indeed it is not supported in that region so definitely looks like Shippable is attempting to call the ECS api in region that does not exist.

  /home/shippable/micro/nod/stepExec/managed/deploy/run.sh 1s  
Starting Deployment for: dv-test-ecs2
Preparing manifests
Applying manifest overrides for dv-manfoo2
Summary of cluster: -- newlyAdded: 1, -- changed: 0, -- deleted: 0
Force deployment is: false
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Manifests removed: 0
Initialized AWS Adapter.
Deployment flow: serial
Executing deploy type: blueGreen
creating container definition
creating task definition
registering task definition
Failed to register task definition for dv-test-ecs2-dv-manfoo2. Provider response: UnknownEndpoint: Inaccessible host: `ecs.us-east-1b.amazonaws.com'. This service may not be available in the `us-east-1b' region.
Failed to deploy manifest for type: blueGreen
Deployment failed for dv-manfoo2
Deployment failed with error : true

**Comment by trriplejay** [comment]
for ECS, the region is typically defined in the cluster resource in your `shippable.resources.yml`.  Can you check your yml file and let us know if that is not the case? Here's some documentation on the cluster resource: http://docs.shippable.com/reference/resource-cluster/

**Comment by toomanyedwards** [comment]
It *is* defined in the cluster as "us-east-1c" where my cluster is. I don't know where us-east-1b is coming from.  Again, my deploy actually worked once, but then failed on the second attempt with this error. In the shippable AWS integration config UI there an "AWS API Endpoint" field, but it isn't editable so I can't specify the API region that shippable is using so it looks like under the covers it's using us-east-1b now for some reason.  All of my deploys are failing with this error. I tried creating a new AWS integration, but am still getting the same error when using a new AWS integration as well.

**Comment by trriplejay** [comment]
From what I can see, you have 3 cluster resources, and they all seem to have region as `us-east-1b`, which is taken directly from the `shippable.resources.yml` files in the sync repositories. Can you share your yml? if your yml says `1c` but your resource says `1b` then that would be a strange bug.

But actually now that I think about it, neither us-east-1b or us-east-1c will work. you actually just want `us-east-1`.  The letter further distinguishes the availability zone, but that extra information is not necessary when it comes to making requests to the aws ecs API.  I'd recommend updating your cluster resources to just say `us-east-1`.

**Comment by toomanyedwards** [comment]
Here's my repo: https://github.com/toomanyedwards/wifi-location-sensing-server

Again, this deploy worked once.  I have never specified us-east-1b anywhere.  Changing the cluster region to us-east-1 didn't change anything. Still getting the same behavior.  The region I need to deploy to is in us-east-1c so I don't think just specifying us-east-1  in the cluster deployment will work if I get past this issue.

**Comment by toomanyedwards** [comment]
I don't know if shippable is using the AWS command line client under the covers, but if so it looks like the default region for it for me is set to us-east-1b somehow.

**Comment by trriplejay** [comment]
I see the issue here. If you look at your sync job for the repo you linked, it's red.  If you open the logs and look at the error messages, you'll see:

![image](https://user-images.githubusercontent.com/6869398/27204030-92de2bd2-51dd-11e7-86c6-cf80560e1195.png)

You have the cluster defined already in another repo that is in your subscription, and the names have to be unique.  It looks like the cluster being used right now actually comes from your `samplePipelinesTest` repo.  It looks like this is where the us-east-1b is getting picked up from as well.

Either you can pick a different name for the cluster in your repo, or you can update the resources yml in samplePipelinesTest to remove the duplicate cluster, or you can entirely remove samplePipelinesTest from your pipeline if it's no longer being used.

**Comment by toomanyedwards** [comment]
I updated the resource names so that rsync is green and am still getting the same us-east-1b error.

**Comment by trriplejay** [comment]
if the cluster defined in `wifi-location-sensing-server` is the one you want to deploy to, and you renamed it, then you'll also need to update your deploy jobs to reference that new name in the `IN` statements.

**Comment by toomanyedwards** [comment]
Thanks. That got me farther.  Now it looks like the deploy is stuck. I'm seeing a ton of the following messages. Is there a way to manually kill a deploy so I can retry?

Desired Tasks: 1, Running Tasks :0, Pending Tasks:0
Service status of dv-test-ecs2-dv-manfoo2-192985 : ACTIVE
Desired Tasks: 1, Running Tasks :0, Pending Tasks:0
Service status of dv-test-ecs2-dv-manfoo2-192985 : ACTIVE
Desired Tasks: 1, Running Tasks :0, Pending Tasks:0
Service status of dv-test-ecs2-dv-manfoo2-192985 : ACTIVE
Desired Tasks: 1,

**Comment by toomanyedwards** [comment]
Also is there a way to Disable a project once it's been enabled? I have enabled builds of some test git projects just to get started and now I want to remove them from shippable so it's not cluttered, but don't see how to do this.

**Comment by trriplejay** [comment]
the deployment will time out after about 15 minutes. unfortunately the ability to cancel an in-progress deployment is in our feature backlog.

You can stop the deployment early by going to the ECS UI, finding the service that was created, and change its desiredCount to 0.

While you're in the ECS UI, you can look at the service's events, and you might see why the task cannot start. Some common reasons are: not enough CPU, not enough memory, or duplicate ports.

**Comment by toomanyedwards** [comment]
Ok.  What about disabling/removing projects I no longer associated with shippable?

**Comment by trriplejay** [comment]
regarding delete:

In your "spog" view, if you right-click on the syncRepo, you'll get a popup like this:
![image](https://user-images.githubusercontent.com/6869398/27204788-eb18ae04-51e1-11e7-8ae5-bd38910e0880.png)


Once you click "remove", all resources that were created from this sync job will be soft-deleted.  They'll still appear in red at the bottom of your spog view.  From there, you can find the red syncRepo again, right click, and select 'remove' once more (syncRepo is the one with the little refresh icon).  This will permanently delete all of the resources that were created from that syncRepo.  (you can also delete one at a time, but if you know that you're not using the repo at all, this is the best way to do it)
![image](https://user-images.githubusercontent.com/6869398/27204869-6d37247e-51e2-11e7-88b2-07dc3ad62f04.png)

**Comment by toomanyedwards** [comment]
Ok. Great. Thanks for your help.  I'll close this issue. I think I have enough info to get my deploy working now (fingers crossed). I'll open a new issue if I need to for any reason. Thanks again!
