### ISSUE TITLE
ECS Deployment only working if previous service manually removed from ECS first

### ISSUE THREAD

**Issue by toomanyedwards** [Shippable/support#3652]
I can only deploy to ECS if I have manually gone into ECS and stopped and deleted the old service first.  Below is the log I get when I attempt to deploy *without* doing this. I think the relevant portion is: 

ce0947a0-e598-4642-a05d-e5f87d1ce771 - (service wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance 25923f07-58f5-4a95-a67a-aa9897095066) is already using a port required by your task. 

But I am not sure.  My github repo is: https://github.com/toomanyedwards/wifi-location-sensing-server

Please let me know how I get this fixed.  Maybe this is something related to seeding as I don't quite understand what seeding the pipeline means in shippable. Thanks!

Shippable deploy log:

  Generating Job 0s
  Initializing Job 2s
  Processing IN Dependency: wifi-location-sensing-server-manifest 1s
  Processing IN Dependency: wifi-location-sensing-server-test-ecs-cluster 0s
  Executing Managed Task: deploy
  Generating task script 0s  
  Writing managed task script 0s  
  Validating script dependencies 0s  
  /home/shippable/micro/nod/stepExec/managed/deploy/run.sh  
Starting Deployment for: wifi-location-sensing-server-deploy
Preparing manifests
Applying manifest overrides for wifi-location-sensing-server-manifest
Inside stepExec|managed|_common|compareManifests
Comparing manifests for wifi-location-sensing-server-manifest
Replicas match: true
Images match: false
Packages match: true
Top level docker options match: true
Summary of cluster: -- newlyAdded: 0, -- changed: 0, -- deleted: 0
Force deployment is: false
Summary of 1 manifests: -- scalable: 0, -- deployable: 1
Manifests removed: 0
Initialized AWS Adapter.
Deployment flow: serial
Executing deploy type: blueGreen
creating container definition
creating task definition
registering task definition
creating service
waiting for service to become steady
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : ACTIVE
Desired Tasks: 1, Running Tasks :0, Pending Tasks:0
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : ACTIVE
Desired Tasks: 1, Running Tasks :0, Pending Tasks:0
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : ACTIVE
Desired Tasks: 1, Running Tasks :0, Pending Tasks:0
getting events of failed Service
ce0947a0-e598-4642-a05d-e5f87d1ce771 - (service wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300) was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance 25923f07-58f5-4a95-a67a-aa9897095066) is already using a port required by your task. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide. (Fri Jun 16 2017 05:44:22 GMT+0000 (UTC))
downgrading failed new service wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300
waiting for downgrade of Failed new service wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300
Running Tasks :0, Pending Tasks:0
delete failed new service wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300
waiting for failed new service to become inactive
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : DRAINING
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : DRAINING
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : DRAINING
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : DRAINING
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : DRAINING
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : DRAINING
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : DRAINING
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : DRAINING
Service status of wifi-location-sensing-server-deploy-wifi-location-sensing-server-manifest-193300 : DRAINING

**Comment by trriplejay** [comment]
The default shippable deployment is blue-green style, so we try to bring up a second copy of your service before bringing down the original copy.  This means that if you only have one container instance, and you're trying to expose a port, it will not work, because that port will already be in use.

Either you need enough container instances to run 2 copies of your service at the same time, or you can update your deploy job yml to have this:

```
TASK: managed
deployMethod: replace
```

the replace method will specifically take down your existing service before deploying the new one, so any port conflicts will be avoided.

you can read more about deployment types here: http://docs.shippable.com/reference/job-deploy/#deployment-types
