### ISSUE TITLE
Triggers not firing deployment job

### ISSUE THREAD

**Issue by toomanyedwards** [Shippable/support#3653]
I am trying to set up continuous deployment to ECS for my project and have set up a trigger as described in the docs here: http://blog.shippable.com/continuous-delivery-from-github-to-amazon-ecs

However, neither my manifest or deployment jobs are getting run after my CI is finished. My repo is: https://github.com/toomanyedwards/wifi-location-sensing-server

Please help.  BTW, the docs are somewhat confusing, but so far support has been great and much appreciated.

**Comment by manishas** [comment]
@toomanyedwards that is an old blog which describes a deprecated method of connecting CI to pipelines. We will get that changed asap.

Please follow the instructions here to connect CI with pipelines: http://docs.shippable.com/ci/trigger-pipeline-jobs/

**Comment by toomanyedwards** [comment]
I also tried following that and don't see anything triggered. Please see the shippable.yml and  shippable.jobs.yml in my repo: https://github.com/toomanyedwards/wifi-location-sensing-server  

It feels like I'm close to getting this to really work for continuous deployment, but not quite there.  It's definitely confusing that there are outdated versions of the docs still up.

**Comment by ambarish2012** [comment]
@toomanyedwards you can remove the webhook integration and run your CI job. Please let me know if I have permissions in triggering your CI job so that I can debug whether or not your manifest job is getting triggered by it - your jobs yml seems correct to me.

**Comment by ambarish2012** [comment]
@toomanyedwards you missed one command in your Shippable.yml file, mentioned in the doc that @manishas sent - 

```yaml
echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/wifi-location-sensing-server-image.env````

Add this after your docker push command.
