### ISSUE TITLE
Coverage report excluded files

### ISSUE THREAD

**Issue by deblockt** [Shippable/support#3655]
The code coverage show files excluded from coverage report.
In the job : https://app.shippable.com/gitlab.com/easyalgo/language/runs/20/summary/console

File : src/parser.spec.ts is present. But on coverage command *.spec.ts is ignored.

On the `shippable/codecoverage/coverage.xml` file parser.spec.ts is not present. I don't understand why shippable show this file, and how is computed Branch Coverage and Sequence Coverage for this file.

Regards,
Thomas.

**Comment by ambarish2012** [comment]
@deblockt I am not sure I understand your question. The coverage command is not being generated by Shippable, but is most likely in your package.json file.

**Comment by deblockt** [comment]
Yes, of course.

The command line work fine, the file `shippable/codecoverage/coverage.xml` is generated with istanbul code coverage. This file don't contains any info for `parser.spec.ts` file. But on Shippable report, this file is present.

I don't understand why.

Thank's.
