### ISSUE TITLE
"Back" button in new UI does nothing

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3656]
The new UI has a back button next to the Shippable logo in the upper left area:

![image](https://user-images.githubusercontent.com/5037116/27219394-db7e76cc-5281-11e7-989c-e070a441c4d9.png)

However, this button currently does nothing.

**Comment by rageshkrishna** [comment]
It's not a back button; it's meant to collapse the sidebar menu :)

The strange thing is that it appears to work for me. We'll look in to this.

**Comment by mbrodala** [comment]
Alight, I didn't know this. After flushing the browser caches, the button now indeed does what it should.

Maybe you should reconsider the icon and even the design of this feature. ;-)

E.g. the new Bitbucket UI simply shows a clickable icon on hover:

![image](https://user-images.githubusercontent.com/5037116/27219695-e83824e8-5282-11e7-9782-61136d90aa7b.png)

Clicking it hides/shows the sidebar texts.
