### ISSUE TITLE
[NEW UI] Runs dont show the latest status

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3657]
The new UI dont shows Job Runs latest status

the below is showing some runs have not been executed, but they have

![image](https://user-images.githubusercontent.com/15203863/27220228-c706f7dc-52c7-11e7-9587-4215e8e1604e.png)

**Comment by ambarish2012** [comment]
@asanchezgiraldo we are investigating.

**Comment by ambarish2012** [comment]
@asanchezgiraldo can you describe the problem in more detail -

1. Is this issue occurring frequently?
2. Would it be possible for you to demo it to me?

**Comment by asanchezgiraldo** [comment]
@ambarish2012 it does not seem to be happening anymore.
