### ISSUE TITLE
Build colors in scroller of new UI too bright

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3660]
The build scroller on the top displays the status of all recent builds at once. However, the colors are too bright which leads to color bleeding especially where successful (green) and failed (red) builds meet:

![image](https://user-images.githubusercontent.com/5037116/27231691-bac3b71c-52b3-11e7-97b8-eddb9fd8de03.png)

The brightness/saturation should be reduced a bit which in turn would also make the button text more readable.

**Comment by mbrodala** [comment]
The same goes for the status labels in build tables:

![image](https://user-images.githubusercontent.com/5037116/27231818-327fa220-52b4-11e7-9fab-f5d8a78ae145.png)

This is rather hard to read.

**Comment by ambarish2012** [comment]
@mbrodala thanks for the feedback, I will talk to our UX team and get back to you.

**Comment by mbrodala** [comment]
It seems like this has been improved a bit already:

![image](https://user-images.githubusercontent.com/5037116/27743373-17865604-5dbc-11e7-9a0f-9a2806950743.png)

However, I think the colors are still to light for a good contrast. Here's an example using the colors used by Bitbucket to signify build status in the commit list:

![image](https://user-images.githubusercontent.com/5037116/27743471-6a772348-5dbc-11e7-826a-f68657990161.png)

(green: `#14892c`, red: `#d04437`)

**Comment by avinci** [comment]
this has been updated back to our old colors. Please let us know if that works.

**Comment by mbrodala** [comment]
![image](https://user-images.githubusercontent.com/5037116/28007064-4608fe12-6552-11e7-9f54-80a731dcf78b.png)

Yes, this looks _way_ better, thanks!
