### ISSUE TITLE
Wrong version of CI build showing in Pipeline view

### ISSUE THREAD

**Issue by toomanyedwards** [Shippable/support#3662]
In the pipeline view, the wifi-location-sensing-server_runCI job shows one previous version that the latest one actually run.  For instance, the pipeline view currently shows version 55, but if I click on this job for details I see version 56.  Is this a big or am misinterpreting what version is showing in the pipeline view vs detail?

**Comment by ambarish2012** [comment]
@toomanyedwards I can't repro this issue. I looked at your pipeline dashboard and I see version 57, which correlates with the job details view.
