### ISSUE TITLE
Not reporting failures on elastic beanstalk deployment

### ISSUE THREAD

**Issue by gcoombe** [Shippable/support#3663]
### Description of your issue:
Currently when there is an error in the elastic beanstalk deployment stage of my build shippable reports that the build was successful.  This can be confusing for our team when the deploy is reported as successful to our slack channel only to find later that the new code is not actually live.  

- https://app.shippable.com/github/gcoombe/fetch-home/runs/815/1/console

**Comment by ambarish2012** [comment]
@gcoombe eb deploy is returning a success code to the shell in spite of failure. We look at exit codes to determine whether a task / script is successful or not.

Some useful suggestions can be found here - https://stackoverflow.com/questions/37736392/aws-eb-deploy-always-returns-returncode-0
