### ISSUE TITLE
API documentation & examples use plaintext HTTP

### ISSUE THREAD

**Issue by rollcat** [Shippable/support#3664]
All API examples found at <http://docs.shippable.com/reference/api-overview/> use insecure HTTP in copy-paste examples, including cases when the secret API token is included in the request. The API endpoint does not support plaintext HTTP (the server refuses connections on port 80) at this moment, so accidentally copy-pasting the `curl` example does not immediately leak the token in plain text.

It is however quite cumbersome to manually tweak every example before making the request.

**Comment by ambarish2012** [comment]
@rollcat thanks for reporting this issue - we will update the API docs.

**Comment by ambarish2012** [comment]
This issue has been fixed.
