### ISSUE TITLE
API docs do not list any working examples, or where to get the parameters from

### ISSUE THREAD

**Issue by rollcat** [Shippable/support#3665]
I was trying to start using the official API (as documented here:
<http://docs.shippable.com/reference/api-overview/>), but the documentation is very scarce, does not explain where to get the expected values from, or where actually to get started. Error responses are not helpful, or indicative of what went wrong.

Examples:

1. There is no explanation about the exact meaning, difference, and correlation between Builds, Jobs, and BuildJobs.

2. I was trying to get the recent builds information. Hitting an API endpoint with `curl`:

    `curl -X GET --header :Accept: application/json: --header :Authorization: xxxx-xxxx-xxxx-xxxx-xxxx: https://api.shippable.com/buildJobs?sortBy=createdAt&sortOrder=-1`

    I get the following response:

    `{"logType":"verbose","methodName":"/buildJobs|GET|callerId:public|validateProjects|_computeShim","id":4004,"message":"No projects found for projectId(s): "}`

    There is no information where to get `projectIds` from; hitting `/projects` results in the same message. I couldn't find the project ID anywhere in the UI.

3. Several endpoints (including `/builds` and `/accounts`) simply result in the message `"access denied for route: /someRoute"`.

**Comment by tjomk** [comment]
+1

**Comment by kanthchandra** [comment]
Hey @rollcat while we fix the documentation let me try and help you with your current problem.

I think you need to have something like this 
` curl -X GET --header :Accept: application/json: --header :Authorization: apiToken xxxx-xxxx-xxxx-xxxx-xxxx: https://api.shippable.com/buildJobs?sortBy=createdAt&sortOrder=-1`
`
Please notice apiToken in the authorization header. Since the token was probably not sent in the right syntax, we were not able to find any projects that were associated. So the project list was also empty.

We will definitely try and improve the documentation around this.

**Comment by ambarish2012** [comment]
@rollcat thanks for the feedback, we will augment the docs and add a how-to section that describes how to use the API for specific use-cases. Please can you also email me your authorization token @ ambarish@shippable.com, I will look into why you are getting the access denied errors. 

Regarding project ID, we do expose it in the new UI. Click on Try the new Shippable link at the top right of your dashboard to switch to the new UI.
 
You can see the project ID at the bottom of every project dashboard screen - for example if you scroll all the way down for the [yamaha-genos](https://app.shippable.com/bitbucket/u9/yamaha-genos/dashboard) project, you will see the project ID. 

In the old UI, you can extract the project ID from the badge settings. Navigate to the project dashboard and click on Settings->Badges. You can see the project id in the status badge URL path after projects/. For example, the project id for this status badge url - 
```https://api.shippable.com/projects/58d160e6e72ded05004e326a/badge?branch=master``` is 58d160e6e72ded05004e326a.

I will add this to the API documentation.

**Comment by rollcat** [comment]
@ambarish2012 can you please not leak our private projects' names on a public forum?

**Comment by rollcat** [comment]
@kanthchandra @ambarish2012 thanks guys for the help! Everything works.

**Comment by ambarish2012** [comment]
@rollcat sorry about the leak, will obfuscate names in the future.
