### ISSUE TITLE
GitLab integration showing database errors

### ISSUE THREAD

**Issue by Kintar** [Shippable/support#3666]
I was attempting to configure GitLab integration.  It wasn't showing up in my subscriptions, so I decided to delete the integration and try again.  When I attempted to delete it, I get the following error:

(Id: 4001) accountIntegrations.destroy failed for id:
verbose: accountIntegrations|deleteById|callerId:59355b6a87114907003d484e|accountIntegrationId:5948088bdf895007001789d3|_deleteById
"5948088bdf895007001789d3 returned error: update or delete on table \"accountIntegrations\" violates foreign key constraint \"subscriptionIntegrations_accountIntegrationId_fkey\" on table \"subscriptionIntegrations\""

Currently, I'm seeing zero Subscriptions available in my Shippable dashboard.

**Comment by ambarish2012** [comment]
@Kintar we are deleting your account integration from our backend. We just realized that due to a UI bug, every time you click save on your account integration we are wiping out the API token. This does not happen when you create the gitlab account integration for the first time - only when you edit the account integration.

**Comment by Kintar** [comment]
Thanks.  I'll try again in a few hours.

**Comment by trriplejay** [comment]
@Kintar your integrations are cleaned up now, can you try syncing your account again, and let us know if your subscriptions become available?

**Comment by Kintar** [comment]
Just synced.  Still nothing showing up for GitLab.

**Comment by Kintar** [comment]
Although I did just get a pipeline failure email from GitLab. o.o

**Comment by trriplejay** [comment]
ok, we'll continue to investigate.

**Comment by trriplejay** [comment]
@Kintar 
Based on our sync logs, it looks like we're unable to get your gitlab user info.

If you're using gitlab.com, can you make sure your integration has the correct url? `https://gitlab.com/api/v3` and double check that your token has read_user and api access?

**Comment by Kintar** [comment]
Good morning, John.  I had changed it to https://gitlab.com on a
recommendation from some random googling.  I've now changed it back to the
full /api/v3 URL, and it still does no appear to be syncing.

**Comment by trriplejay** [comment]
If that is the case, then it seems like something might be wrong with the token.  Can you try this command on your local machine?
```
curl --header "PRIVATE-TOKEN: <your token here>" https://gitlab.com/api/v3/projects
```

If your token is valid, then you should get back a list of your projects.  can you let me know if that works?

**Comment by Kintar** [comment]
Well...I'm an idiot.  All this time I've been using my gorram runner token,
not the API access token. >.<

Thank you for your assistance and patience, John.  I owe you a few beers,
and apologize for my idiocy. ;)

**Comment by Kintar** [comment]
I spoke too soon!  Now I'm getting this:

getValidCollaboratorByProjectId for projectId 594ad1b050bbb70600216095
returned an error: Failed to get valid collaborator account for project :id
594ad1b050bbb70600216095

**Comment by trriplejay** [comment]
you're welcome! glad we got it figured out :)

**Comment by trriplejay** [comment]
@Kintar can you try again? it should work now.

**Comment by Kintar** [comment]
It's not failing, but the spinner next to the project enablement switch has
been spinning for about 15 minutes.

[image: image.png]

**Comment by trriplejay** [comment]
We're trying to figure out why this happened.. in the meantime, I have enabled the project for you.

**Comment by ambarish2012** [comment]
@Kintar closing this issue for now - please feel free to open an issue if you run into this issue again.
