### ISSUE TITLE
[New UI] Error on Dry run when we use a different runCI name

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3667]
ISSUE: We are getting an error message on the dry run due to runCI not being present even though the OLD UI does show this job

```
project: homes-site does not exists, please use valid runCI job
```

ACTUAL:
New UI
![image](https://user-images.githubusercontent.com/15203863/27317336-f36eec2c-55c8-11e7-8834-a6ff4f9f8677.png)

Old UI
![image](https://user-images.githubusercontent.com/15203863/27317292-afb9b71e-55c8-11e7-8f64-114b80898f3b.png)

EXPECTED:
User should be able to do a dry run of any changes to the pipeline through a separate branch

**Comment by ambarish2012** [comment]
@asanchezgiraldo we are investigating.

**Comment by ambarish2012** [comment]
@asanchezgiraldo this bug has been fixed. Please let us know if SPOG dry run is working for you.
