### ISSUE TITLE
Git LFS does not work with Bitbucket

### ISSUE THREAD

**Issue by garth-wells** [Shippable/support#3670]
Cloning repositories that use Git LFS from Bitbucket fails. A sample log is at <https://app.shippable.com/bitbucket/fenics-project/dolfin/runs/4/1/console>. See also #3053.

**Comment by rageshkrishna** [comment]
Copying my comment from #3053 for reference -- BitBucket has a limitation that prevents deploy keys from accessing the LFS store: 

https://confluence.atlassian.com/bitbucket/current-limitations-for-git-lfs-with-bitbucket-828781638.html#CurrentlimitationsforGitLFSwithBitbucket-AccesskeysdonotallowaccesstotheGitLFSfiles

The recommended workaround from Atlassian is to use app passwords for this, which is currently unsupported on Shippable. We need to investigate whether this is feasible or if there are other workarounds we can pursue.

**Comment by garth-wells** [comment]
I work-around that is possible on other systems is to allow the git command to be controlled from the config file.

**Comment by garth-wells** [comment]
I'd be really grateful for a work-around for this since it's a blocker for repos on Bitbucket that use Git LFS. I notice that Shippable is cloning over https (https://app.shippable.com/bitbucket/fenics-project/dolfin/runs/5/1/console). Can I switch this to ssh?

**Comment by avinci** [comment]
@garth-wells i will look into this and get back to you.

**Comment by manishas** [comment]
We're actively working on implementing this now...

**Comment by shrivara** [comment]
This is now supported.

For a public Bitbucket project which does not require credentials:
- Goto the project settings and configure a HTTPS custom clone URL without a username. Example: https://bitbucket.org/your-project/your-repo.git

For a private Bitbucket project or a project which requires credentials:
- Generate an app password in Bitbucket. Use this to [create a Git credential integration](http://docs.shippable.com/reference/int-git-credential/). 
- Goto the project settings and configure a HTTPS custom clone URL with the username specified in the Git integration. Example: https://user-name@bitbucket.org/your-project/your-repo.git
