### ISSUE TITLE
[production issue] "Reached private job limit" blocking account usage when only 55 builds so far

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#3671]
Hi,

Our build is showing as having reached our private job limit when we haven't.  1st of month was build 632, and build stopped at 687.

This looks like a repeat of #3215 as 150 builds back lands a few builds into the 1st May.

Can you reset our count please - on github/eccosolutions.

**Comment by ambarish2012** [comment]
@nealeu we are investigating.

**Comment by ambarish2012** [comment]
@nealeu we have reset the limit.
