### ISSUE TITLE
Status Doesn't Show All Jobs

### ISSUE THREAD

**Issue by bantonj** [Shippable/support#3672]
The dashboard for a given repo doesn't show all my jobs. I would like to be able to see all jobs that have run. The history page seems to show that, but it's unclear.

I'm trying out the new interface and the history page seems to show all repos. Is there a way to just see a list of all jobs for a repo?

**Comment by ambarish2012** [comment]
To see all the jobs for your repo, click on the repo in your subscription dashboard.

For example, these are all my jobs in the deploy-ecs-basic repo.

![screen shot 2017-06-20 at 1 03 58 pm](https://user-images.githubusercontent.com/26096758/27353494-0e8255cc-55b9-11e7-8304-a2ce7f0d8ebb.png)

**Comment by metalwood** [comment]
When I go to a specific repo page this is what I see.

<img width="1395" alt="screen shot 2017-06-20 at 4 08 19 pm" src="https://user-images.githubusercontent.com/29510361/27353652-cff0adb2-55d2-11e7-92db-618b1f2390fd.png">

It doesn't show anything from yesterday or the day before that, etc.

**Comment by ambarish2012** [comment]
ok - makes sense. I think allowing search history to specify repository scope would be very useful. I will submit that feature request.

**Comment by metalwood** [comment]
Thanks. Preferably though I'd like a way to configure the dashboard to just show all jobs by run date. Otherwise that page is useless to me and seeing my job history takes more time and clicks.

**Comment by ambarish2012** [comment]
@metalwood I didn't understand your comment - you can sort results in the search history page on the createdAt field. What is your specific usecase?

**Comment by metalwood** [comment]
My point was that I don't want to have to go to the search history page. I'd rather the dashboard be a useful page. I don't really understand what it is showing now, but I'd like it to just show all the most recent jobs that have run.

**Comment by ambarish2012** [comment]
@metalwood the dashboard currently renders jobs and resources for every branch. What is rendered is the status for the most recent run, per branch for every job in your repository. It also renders all the currently processing jobs.

Our model is that to get a historical view of runs for a specific job, you would use the history feature. We will augment the search history feature to filter on date and repository.

Regarding seeing the history in your current dashboard, you can click on a specific job and see its execution history.
![screen shot 2017-06-21 at 2 21 04 pm](https://user-images.githubusercontent.com/26096758/27407405-027c02f8-568d-11e7-8c7b-fa1851284a7e.png)

**Comment by ambarish2012** [comment]
If you want to see all the jobs that you specifically have triggered, you can search using your github account name in the dashboard.

**Comment by manishas** [comment]
@bantonj @metalwood we just launched an enhancement that will show job history on the project dashboard. 

![image](https://user-images.githubusercontent.com/2983749/28302534-d9f49cd0-6b42-11e7-984d-1989ba743dee.png)

**Comment by metalwood** [comment]
Thank you, that is very helpful.
