### ISSUE TITLE
Pipelines in SPOG with recent successful runs are all gray

### ISSUE THREAD

**Issue by johnsonwj** [Shippable/support#3673]
Another member of our organization looked at the flag (`team-tonka`) and they appear green to her, so this appears to be an issue with my account.

![image](https://user-images.githubusercontent.com/3478488/27353042-8c567b06-55b7-11e7-87f5-7f2a67716205.png)

**Comment by ambarish2012** [comment]
@johnsonwj - can you send a link to your subscription?

**Comment by johnsonwj** [comment]
@ambarish2012 do you mean this: https://app.shippable.com/subs/github/konciergeMD/dashboard
or is there a more helpful link I can give you?

**Comment by ambarish2012** [comment]
@johnsonwj I am closing this issue for now. I will setup a zoom session with you to debug this.
