### ISSUE TITLE
Clicking on jobs, manifests, etc. in SPOG navigates to a new page

### ISSUE THREAD

**Issue by johnsonwj** [Shippable/support#3674]
Previously, a modal was opened up in the same page where I could review job history and logs, and then closing that window would return me to the SPOG view.

Now I have to hit the back button to return to the SPOG, and though it is still filtered by the flags I selected, I have to scroll/zoom through them to find the pipeline I am interested in.

**Comment by ambarish2012** [comment]
@johnsonwj in our current model, you can open the job view in a new tab. You can then tab-switch between the SPOG view and the job view.

**Comment by johnsonwj** [comment]
@ambarish2012 that would be fine but when I right click those I get the Shippable context menu (run/pause job etc.), not the Chrome menu that I can open a new tab in

**Comment by ambarish2012** [comment]
@johnsonwj makes sense - however on the Mac i am able to command + click to open the job view in a new tab.

**Comment by johnsonwj** [comment]
hmm, using cmd+click appears to just open the SPOG view in another tab for me

**Comment by ambarish2012** [comment]
@johnsonwj I have submitted this feature request. I think your suggestion of opening the job view in a new tab on click in the SPOG makes perfect sense.

**Comment by avinci** [comment]
this has been implemented.
