### ISSUE TITLE
Usability issues in new UI

### ISSUE THREAD

**Issue by johnsonwj** [Shippable/support#3675]
I'm going to collect some issues here that I notice while I'm exploring the new UI. Thank you for all the work that went into this!

- in a job page, the collapsible panels can only be toggled with the small +/- button in the top right corner. I expect to be able to click anywhere in the header bar to be able to open/close these panels.

![image](https://user-images.githubusercontent.com/3478488/27353750-02985206-55ba-11e7-8589-4c84af9df162.png)

**Comment by ambarish2012** [comment]
@johnsonwj thanks for a ton for the feedback. I will keep an eye on this issue and will pass it along to our UX team once you have posted all your feedback.

**Comment by johnsonwj** [comment]
- in the SPOG view, I would really appreciate having a filter dropdown _in addition_ to the flags dropdown (which is amazingly helpful!). This would allow me to focus on deployments for one or two projects; then when I clear those filters, I return to all of the projects flagged for my team.

**Comment by ambarish2012** [comment]
@johnsonwj you can try creating custom views for those projects. We are adding support for SPOG for custom views this week - right now custom views only support grid view.

**Comment by johnsonwj** [comment]
oh awesome, thanks!

**Comment by ambarish2012** [comment]
To create a custom view, click on Home -> + -> select your pipeline filters, jobs, CI projects.

**Comment by manishas** [comment]
@johnsonwj SPOG for custom views is now available. Still working on the expand/collapse for panes.

**Comment by ric03uec** [comment]
@johnsonwj this is now fixed
