### ISSUE TITLE
Cannot enable project in new UI

### ISSUE THREAD

**Issue by sdlarsen** [Shippable/support#3676]
Hi,

I added a Python project to my bitbucket account (like many others) and wanted to enable it on shippable. For some reason, that was not possible in the new UI (no slider shown). Switching to the old UI it worked as it used to.

**Comment by ambarish2012** [comment]
@sdlarsen which python project is not showing up? Please email the project name and subscription to ambarish@shippable.com and I will take a look.

**Comment by sdlarsen** [comment]
The project is showing up, there's just no UI component available for enabling it. I've already enabled it using the old interface which works just fine.

**Comment by ambarish2012** [comment]
@sdlarsen in the new UI, you have to click on the + sign to see the enable projects view.
<img width="1138" alt="screen shot 2017-06-22 at 11 31 25 am" src="https://user-images.githubusercontent.com/26096758/27449785-68584472-573e-11e7-865e-1626f90469bc.png">

**Comment by ambarish2012** [comment]
@sdlarsen please feel free to open another issue if you see this problem again.
