### ISSUE TITLE
Can't see the branch that triggered the build in the new UI

### ISSUE THREAD

**Issue by tmcnicol** [Shippable/support#3682]
Just looking for the current branch of the builds in the new UI path `runs/1605/summary/console`

**Comment by deepikasl** [comment]
Hi @tmcnicol can you please go to the tab `summary`. 
![screenshot from 2017-06-22 11 28 18](https://user-images.githubusercontent.com/18304961/27419339-f7b28f34-573d-11e7-95f4-557f1531c42a.png)

you can see `Branch` field present after the `overall status`.

**Comment by tmcnicol** [comment]
Thanks for this.

**Comment by kanthchandra** [comment]
Hey @tmcnicol this has been fixed and deployed. Can you please check and let us know if it works for you.

**Comment by manishas** [comment]
Closing.
