### ISSUE TITLE
New UI: Clickable Status buttons

### ISSUE THREAD

**Issue by gundalow** [Shippable/support#3685]
### Description of your issue:

Nice work on the UI :)

The column that tells you the status for each jobs should be a link to the individual sub job.

Currently the only way to select the subjob is from the top ribbon, which doesn't work that well for us as we have 41 jobs.

**Comment by ambarish2012** [comment]
@gundalow I did not understand what you meant by sub-job. The job and name columns are clickable, so it's not clear to me why making the status column clickable would help.

Please can you post screenshots here or email them to me at ambarish@shippable.com.

**Comment by gundalow** [comment]
![status_column](https://user-images.githubusercontent.com/940557/27555782-fe8b9128-5aaa-11e7-800e-9868314f61a9.png)

I'd expect to be able to click the `Processing`, `Success` links to be taken to that specific job.

**Comment by ambarish2012** [comment]
@gundalow we have added this feature request to our backlog. We will update this issue when the feature is available in PROD.

**Comment by ambarish2012** [comment]
@gundalow this feature will go live by end of week.

**Comment by ambarish2012** [comment]
@gundalow this feature is live in production. Thanks for your feedback.
