### ISSUE TITLE
Cannot access my Bitbucket subscription

### ISSUE THREAD

**Issue by rollcat** [Shippable/support#3686]
I can no longer access my BB subscription.

My BB username is `kamilce`. I'm an admin for the `u9` BB team. I have granted OAuth access and I can see Shippable among authorised apps in my profile settings at `https://bitbucket.org/account/user/kamilce/api`. I can also see BB among identities in my Shippable dashboard (new UI) at `https://app.shippable.com/accounts/540f414740b70914000b1243/settings`.

I can't see the subscription, nor any of my BB teams, in neither the old nor the new UI.

I've tried deleting and re-adding the OAuth integration, logging out&in, removing&re-adding account integration, nothing helps.

(EDIT: obviously this has been working great for me for the past year or two.)

**Comment by ambarish2012** [comment]
@rollcat we will need to jump into a quick hangout session to debug your problem. Please let us know what time you are available today after 12pm.

**Comment by rollcat** [comment]
Hey, it seems it's working now, so this can be closed.

I'm in CEST so normally I'm available during [PST night/early morning](https://www.worldtimebuddy.com/?qm=1&lid=12,8&h=12&date=2017-6-27&sln=10-18), but in case this pops up again I can stay online a bit longer.
