### ISSUE TITLE
drydock image tags are confusing

### ISSUE THREAD

**Issue by jalan** [Shippable/support#3691]
Suppose I want to always use the latest released version of the [drydock/u14pytall](https://hub.docker.com/r/drydock/u14pytall) image. It isn't clear which tag I can rely on. [hub.docker.com/r/drydock/u14pytall/tags/](https://hub.docker.com/r/drydock/u14pytall/tags/) shows tags `master`, `latest`, `tip`, and `prod`. Can I use one of these tags in my `shippable.yml` and reliably get the latest image?

**Comment by ambarish2012** [comment]
@jalan you should use the v5.6.4 tag. The latest image is the most recent v[major.minor.patch] tag.

You can also find information on our latest machine images [here](http://docs.shippable.com/reference/machine-images-overview/) .

**Comment by jalan** [comment]
Sure, `v5.6.4` is the newest version _right now_, but I want to automatically use the newest version, without updating my `shippable.yml` every time you change it.

**Comment by ambarish2012** [comment]
ok - makes perfect sense. I will create a feature request so that you can specify the `latest` tag to get the latest released version.

**Comment by manishas** [comment]
@jalan you do not have to change shippable.yml to use a later version. As long as you do not override the default build image using the `pre_ci_boot` section in your shippable.yml, whatever machine image you choose in the UI will be automatically pulled.

Here is how you can change machine image: http://docs.shippable.com/reference/machine-images-overview/#changing-the-subscription-machine-image

**Comment by jalan** [comment]
@manishas: I see. Unfortunately that would change the image used for many other projects in my org, so I am not able to go that route.

**Comment by ambarish2012** [comment]
@jalan this issue has been addressed - you can use the latest tag.
