### ISSUE TITLE
Slow build times on paid plan

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#3692]
We've upgraded to a paid plan and wondering whether to continue, as we're seeing some horrendous delays on 'non-work' (i.e. not doing the actual build and provisioning).

An example is where firefox --version is taking 8 seconds or more compared to on my laptop:

    time firefox --version
    real	0m0.119s
    user	0m0.024s
    sys	0m0.016s

Similarly, java --version is taking 9 seconds (see https://app.shippable.com/github/eccosolutions/ecco/runs/742/1/console)

Can you please investigate what is going on as this is rather defeating the reason we've switched to a paid plan.

**Comment by ambarish2012** [comment]
@nealeu we are investigating.

**Comment by ambarish2012** [comment]
@nealeu I can confirm this is a bug in our system reporting time. The command is taking much less time in the container, but we are reporting it inaccurately.

This is the real time taken to execute firefox --version in the build container -
```
root@69003b34faec:/firefox# time ./firefox --version
Mozilla Firefox 45.3.0

real	0m0.168s
user	0m0.005s
sys	0m0.030s```

**Comment by nealeu** [comment]
Ok. I'll wait for the fix and check again.  It doesn't fully explain some of the build times, but perhaps I'd better start watching the wall clock when they start to see if this is all mis-reporting

**Comment by nealeu** [comment]
Just checked back on some older builds.  I think there is a resource contention issue here, as the wall time measured on our Slack notifications for commit and build success matches the elapsed time reported for the total job, and this run https://app.shippable.com/github/eccosolutions/ecco/runs/732/1/console, took twice as long as we were getting when on the free plan.

What guarantees do we get for paying?

**Comment by manishas** [comment]
@nealeu: 

- Paid plans give you unlimited builds for private projects, the ability to set up to a two hour timeout for builds, API access, among other premium features. We're also introducing the ability to SSH into your build minions with paid plans very shortly. 

- Bigger machines help with build duration if your CI is memory bound and/or leverages additional CPUs, If not, you might not see a huge improvement in build times.

- Our goal is to keep the API response time between 300-500ms but for some projects that write a lot of data to the console, small variations in API response time can affect the reported build duration. So even if the actual build in the container takes a shorter time, it takes us extra time to write the console logs to the DB, change status, send notifications. It doesn't happen for every build but can affect an occasional build, depending on API load. We're investigating a fix but most approaches are fairly intrusive and need to be designed very carefully so we don't break anything :)

Some options that can help accelerate builds in the shorter term :
- You can split your test suite and run it in parallel by buying more minions. These can be c4.large minions.
- Check if your tests can leverage the additional CPUs in some way. 

Let me know if you want to jump on a hangout to discuss further.

**Comment by nealeu** [comment]
Hi @manishas,

That's really fantastic feedback.  I'll have a look at cutting down on what we write to the console during the build, but also will look at how we might build some modules in parallel to use the extra CPU threads.

Thanks,
Neale
