### ISSUE TITLE
Update URL when switching builds through roller

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3698]
Thanks to the roller in the new UI one can easily switch between builds. However, the URL is not updated accordingly which throws users back to the initially opened build on browser refresh.

The URL should be updated to reflect the selected build (e.g. using the HTML 5 History API).

**Comment by rageshkrishna** [comment]
Hi @mbrodala. This is definitely a bug. Thanks for reporting it. I've added this to our backlog.

**Comment by mbrodala** [comment]
Seems like this was fixed by now. The URL now changes when switching between builds in the roller.
