### ISSUE TITLE
[new UI] SPOG is only displaying the JOB with flags compare to old UI

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3700]
### Description of your issue:
Currenlty the Old UI would display all the jobs associated to any Job that is flagged, but the new UI is only displaying the jobs with flags

before
![image](https://user-images.githubusercontent.com/15203863/27888404-2c87ff78-6229-11e7-8830-d19be3bbcd4d.png)

after
![image](https://user-images.githubusercontent.com/15203863/27888152-eb560bd6-6227-11e7-9ea9-108cd277ad80.png)

**Comment by ambarish2012** [comment]
@asanchezgiraldo we are tracking this request in our backlog.

**Comment by manishas** [comment]
This is now fixed. Please let us know if you need any other help with this.
