### ISSUE TITLE
Error trying to delete an integration 

### ISSUE THREAD

**Issue by caliagaa** [Shippable/support#3704]
Error trying to delete an integration 

(Id: 4001) subscriptionIntegration not found for :id 4673
verbose: subscriptionIntegrations|getById|callerId:582b43112179161000dd929f|_getProjectAccounts

This only occurs with just one integration

**Comment by ambarish2012** [comment]
@caliagaa we have deleted the integration. You probably deleted the repository before deleting the integration.

**Comment by caliagaa** [comment]
great! thanks.
