### ISSUE TITLE
shippable disappeared from my github project

### ISSUE THREAD

**Issue by soby** [Shippable/support#3705]
### Description of your issue:
Builds not occurring or appearing on PRs

Shippable builds just disappeared from our PR pages this morning around 9:15 pacific. I've reset the project, revoked the oauth token on the github side, re-authenticated, and try to unsubscribe/resubscribe. Resubscribing throws an error like: 

deleteRunById for id: 58daffecbb77b606001e678c returned error: Run not found for id: 58daffecbb77b606001e678c

Repo is https://github.com/soby/sbn-enterprise

**Comment by a-murphy** [comment]
It looks like you've deleted/disabled that project on Shippable.  Have you tried re-enabling it?  The error above could be the result of attempting to delete the project while it was in the process of being deleted.

**Comment by soby** [comment]
I deleted it as a troubleshooting step. That error is what I get when I tried to re-enable yet. After waiting a bit it appears to allow me to re-enable and is building again
