### ISSUE TITLE
New UI: Usability issues

### ISSUE THREAD

**Issue by jodastephen** [Shippable/support#3708]
While generally usable, I've found myself frustrated by parts of the new UI.

1) On the dashboard, a job will start in the "queued jobs" section, then move to the "processing jobs" section. But when complete it **just disappears** As such, there is no way to see whether a job I initiated a few minutes ago completed successfully or not without going to the relevant project. This is now getting very annoying.

2) Even when I go to the project page I still can't see the status of the recently completed jobs. Instead, I get the latest status of each branch, including branches that are very old and not interesting. This simply isn't what I want to know - I usually want to see what has just finished, not the status of each branch.  To find the status of a recently completed job I have to click on the highest job number I can see, and then hover over each job number until I find the job I'm actually interested in. The whole process is a slog.

3) The new UI has stolen the ability to right click on my mouse for the job numbers. As such, it is **really difficult** to open a shippable link to a job in a new tab. Opening a tab for a job is thus really tricky, requiring manually copying the URL.

I hope this feedback helps and inspires changes, because spending my day fighting the UI isn't a very relaxing way to spend my day!

**Comment by manishas** [comment]
@jodastephen Thanks for the feedback!  I'm taking this to the team and will have an update soon.

**Comment by manishas** [comment]
@jodastephen some updates:

- We have added job history on the project page. 
- Right clicking on a job number should show the standard menu to open the job on a new page.

**Comment by jodastephen** [comment]
Thanks for the right click change, thats certainly better (although the "i" icon flows onto the next line most of the time for me).

The job history section is pretty much exactly what is needed. However every time you arrive at a project page, you always have to collapse the "latest status" section to see it. I'd argue that a short (last 5 or 8 jobs) history section should go above "latest status". (This could be configured in user settings, but its usually better to get the default behaviour right for  UI). In addition, the history section should be on the home/dashboard view.

It would also be worth changing the "started at" column to not use human-readable date forms like "Last Wednesday at 4:41 PM". This type of date description is too long, and wastes space on the screen.

On the home/dashboard view, the "name" column always tends to be truncated, so I see "OpenGamma/Referenc..." instead of "ReferenceDataService". Since all the projects are in the same organization, the org prefix is just wasted space.

Thanks again
