### ISSUE TITLE
Shippable JavaScript hangs using 100% CPU

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3710]
If I visit the following like:

https://app.shippable.com/bitbucket/wspdigital/jobs/myro_stag-deploy-myrocc/builds/5962c4cffee13a070011563d/console

Nothing happens for a while, except I noticed the fan speed on my laptop increasing. Eventually, I get this message:

![screenshot 2017-07-10 12 41 12](https://user-images.githubusercontent.com/112729/28001085-53b41946-656d-11e7-955e-35ee166b7fbb.png)

Have tried closing the tab, reopening, but I cannot access certain pages, including the one I linked to above.

**Comment by rageshkrishna** [comment]
Hi @brianmay. We're looking in to this. I'll update this issue as soon as I have more information.

**Comment by rageshkrishna** [comment]
@brianmay This should be working correctly now. Can you give it another shot and let me know? Thanks.

**Comment by brianmay** [comment]
Confirmed. It looks fine to me now. Thanks.
