### ISSUE TITLE
Spog view missing many projects

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3711]
I made a few pipeline resources and jobs, unfortunately this weekend they disappeared and haven't come back. I've talked with Manisha about this issue, and i think she might've raised the issue with a team. But since it hasn't resolved itself over the weekend i also raise the issue here.

So basically, im missing a lot of projects in the SPOG view, and a few in the normal grid view. This weekend i had like 12 out of a few hundred projects in that view, and even in the enable repository things were missing. 

Other colleagues do see the right projects.

https://app.shippable.com/subs/bitbucket/swisnl/dashboard

My account bitbucket.org/bbrala

Thanks.

**Comment by manishas** [comment]
@trriplejay @a-murphy can we look into this asap?

**Comment by bbrala** [comment]
Btw I've made a new bitbucket account this afternoon on an email alias and I saw everything fine on that one.

So I could work through that account.

**Comment by trriplejay** [comment]
It looks like this might be related to two account integerations you added recently.  Our logs suggest that one of the tokens being used is invalid.  It also looks like you have 3 integrations with bitbucket in total.  I'd recommend removing the two you've added recently and just use the original one for your pipelines.

**Comment by bbrala** [comment]
Hmm, ok I'll try that. Thanks for checking it out. I'll get back to you tomorrow hopefully.

**Comment by bbrala** [comment]
Few things while deleting the integrations;

1. Before deleting i needed to put all scopes to 'confgiure later' before i could delete them.
1. When deleting a integration which has a resource depending on them i get the following (not so helpfull) error message:
```subscriptionIntegrations.destroy failed for id: 7205 returned error: update or delete on table "subscriptionIntegrations" violates foreign key constraint "resources_subscriptionIntegrationId_fkey" on table "resources"```

Perhaps it is possible to get the resource name and show that? :)

**Comment by bbrala** [comment]
I have cleaned up the integrations and rerun sync on the projects-overview. THe projectspage shows about 3 of 25 pages of projects, and the spog view is empty. Perhaps the interface doesn't show it is still syncing, but the button stopped loading.

**Comment by bbrala** [comment]
Ok, the data has returned to my account. Perhaps there was an automatic sync? I would assume that pressing the sync button manually would do the same, but perhaps that isn't true?

**Comment by ambarish2012** [comment]
@bbrala I am closing the issue now, please let us know if this occurs again.
