### ISSUE TITLE
Can not delete repo connection

### ISSUE THREAD

**Issue by JohnDuplechain** [Shippable/support#3712]
(Id: 4001) deleteRunById for id: 589a312a85020e0f00d468da returned error: Run not found for id: 589a312a85020e0f00d468da
verbose: projects|disableById|callerId:584841d4c42d210f009d64be|projectId:584849b4c42d210f009d65a9|_removeRuns

**Comment by a-murphy** [comment]
We're looking into why project deletion may have tried to delete a run that had already been deleted or tried to delete the same run twice.  In the meantime, you may want to just try again. It's unlikely that you'll get the same error a second time.
