### ISSUE TITLE
Rsync seems to try and parse wrong file

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3718]
https://app.shippable.com/bitbucket/swisnl/jobs/shippable_master_syncRepo_rSync/builds/59688c069586c007006c0f41/console

The sync job seems to try to parse a file named: `shippable.jobs.yml.example`. This is not really a file it should parse and error on :( Maybe a wrong regex on the filenames?

**Comment by bbrala** [comment]
Hmm, also, the syncRepo job doesnt seem to trigger as it should

**Comment by rageshkrishna** [comment]
Hi @bbrala. You're right, this is probably a faulty regex. Thanks for reporting it. We'll look in to it shortly.

**Comment by mohit5it9** [comment]
@bbrala We've fixed this. Could you please try once?
