### ISSUE TITLE
Sometimes get RPC error on new container

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3719]
Sometimes i get the following error:
`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "process_linux.go:83: executing setns process caused \"exit status 15\""`

https://app.shippable.com/bitbucket/swisnl/jobs/boipDrupalUpdate/builds/59689e1826baa40700a9bcc6/console

Not sure why. It is a fresh node even.

**Comment by rageshkrishna** [comment]
@bbrala The linked build appears to be failing with `Error: Call to undefined function drupal_get_installed_schema_version()`. I can't seem to find the "rpc error" or "exit status 15" anywhere. Can you please point me to a build that reports this error? Thanks!

**Comment by bbrala** [comment]
I might've removed the build, been working on automating Drupal updates, but that ment sometimes resetting the jobs/repos.
