### ISSUE TITLE
golang 1.8 support

### ISSUE THREAD

**Issue by rakeshlacework** [Shippable/support#3720]
Add golang 1.8 to the list of supported compilers

**Comment by manishas** [comment]
This is coming up in a couple of weeks.

**Comment by kanthchandra** [comment]
Hey @rakeshlacework a new machine image v5.7.3 was deployed to production last week. Please go to your nodes page and select [v5.7.3](http://docs.shippable.com/reference/machine-image-v573/) as your [machine image](http://docs.shippable.com/reference/machine-images-overview/) to use go 1.8. There is an image called [drydock/u16golall:v5.7.3](https://github.com/dry-dock/u16golall/) which has go 1.8 installed.
