### ISSUE TITLE
New UI, how to ensure the latest code is used when trying to runa build

### ISSUE THREAD

**Issue by attiam-blueoak** [Shippable/support#3721]
On the new interface, for any of the repository, I can only find the 'rebuild' button. Every time I click that build process uses the specific code that was checked in and not the latest code on the branch. On the old UI, I just used to click on the 'Build' button and shippable always grabbed the latest code that was checked into the particular branch.

How to I ensure that every time I want to build a branch *using the new UI", I always get the latest code.?

**Comment by ankul-shippable** [comment]
@attiam-blueoak You can goto your project page. Click on the play icon for manual build. In the builds page you can select the branch for which you want to trigger build, we'll get the latest code for that branch and run a build.

![manual_build](https://user-images.githubusercontent.com/16793274/28245391-470d734e-6a23-11e7-8510-f59a5ae39b95.png)

**Comment by manishas** [comment]
Closing.
