### ISSUE TITLE
Manually run Docker in Debug (SSH)

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3727]
The new SSH debugging feature looks useful but currently I struggle with entering the build container.

To debug what is going on inside of the container, I've tried to run via `sudo docker run ... -it --rm bash`, however that told me this:

    docker: Error response from daemon: Conflict. The container name "/c.exec.<project>.<build>.<job>" is already in use by container <hash>. You have to remove (or rename) that container to be able to reuse that name..

A more simpler approach with `sudo docker run -it --rm vendor/image bash` doesn't work either:

    sudo: unable to resolve host ip-172-31-2-231

How could I enter a build container for debugging?

**Comment by kanthchandra** [comment]
Hey @mbrodala 

1. sudo docker ps -a
2. choose the id of the container you want to enter.
3. sudo docker exec -it $CONTAINER_ID /bin/bash 
4. You will be inside the build container.

Docs: http://docs.shippable.com/ci/ssh-access/#okay-now-im-on-the-debug-machine-where-should-i-go

**Comment by mbrodala** [comment]
OK, I was actually able to enter the container, the message came from the container itself.

Thanks for the explanation how to properly enter the existing container. :-)
