### ISSUE TITLE
Use custom init script for build container

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3728]
Currently I'm evaluating [these images](https://bitbucket.typo3.com/projects/T3COM/repos/bamboo-remote-agent/browse) for build. The docs say the following to run the build container:

    docker run -it --rm typo3gmbh/php70:1.0 /sbin/my_init -- bash

Thus the command started in the container is `/sbin/my_init` with a nested `bash` session.

How could I integrate this with Shippable? Simply setting `options: /sbin/my_init` didn't work (`docker: Error parsing reference: "/sbin/my_init" is not a valid repository/tag: invalid reference format.`) and I guess setting `--entrypoint` is also not the right way since Shippable already uses this for `/home/shippable/cexec/build.sh`.

Any idea how to achieve this?

**Comment by mbrodala** [comment]
I've just tried with `options: "--entrypoint=/sbin/my_init"` and it was ignored.

**Comment by kanthchandra** [comment]
I'm assuming you want to use `typo3gmbh/php70:1.0` this image for your ci right? Can you try this and let me know if it works?
```
language: none
build:
  pre_ci_boot:
    image_name: typo3gmbh/php70
    image_tag: 1.0
    pull: true
    env: FOO=bar
    options: "-e HOME=/root"
  ci:
      - /sbin/my_init -- bash
```

So basically what this configuration will do is 
1. Language : none will make sure that we will not run any (default) setup commands.
2. pre_ci_boot will boot up your image with whatever envs and options you want. 
3. Then we clone your ci repository
3. `/sbin/my_init -- bash` - I'm assuming this will intialialize something. So this will be the first command that will run inside the ci container and it will intialize whatever you need. 

Only difference between the command you mentioned and this approach is that the container here will start in daemon mode instead of interactive mode like in the command that you mentioned.

**Comment by mbrodala** [comment]
Notice that the [`Dockerfile` of these images](https://bitbucket.typo3.com/projects/T3COM/repos/bamboo-remote-agent/browse/php70/Dockerfile?at=9440679e44841504aa040ee652e603f7159ae543) looks OK from my POV:

```dockerfile
FROM typo3gmbh/baseimage:1.0
MAINTAINER TYPO3 GmbH <info@typo3.com>

ADD . /pd_build
RUN /pd_build/install.sh
CMD ["/sbin/my_init"]
```

Thus unless one specifies a command (what Shippable is not doing in `boot_container` AFAIS), the container should automatically run the `/sbin/my_init` init script.

**Comment by kanthchandra** [comment]
Oh BTW if you use language as none we just spin up the container and not run any initial setup commands everything has to be done by you.

**Comment by mbrodala** [comment]
@kanthchandra I already tried `/sbin/my_init` in `build.ci` but I guess I should try the full command instead. ;-)

**Comment by mbrodala** [comment]
@kanthchandra That didn't help either:

```
/sbin/my_init -- bash  
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 276
*** Running bash...
*** bash exited with status 0.
warning: /etc/service/syslog-forwarder: unable to open supervise/ok: file does not exist
*** Shutting down runit daemon (PID 276)...
```

And of course, this makes sense since `bash` requires interaction.

I wonder why `/sbin/my_init` is not used when Shippable starts the container even though it's the `CMD` in the Dockerfile and no other command is passed ...

**Comment by mbrodala** [comment]
@kanthchandra Can you have another look at this, especially the `CMD` usage by Shippable?

**Comment by mbrodala** [comment]
Right now the `boot_container` command looks something like this with a custom image:

    sudo docker run -d -e HOME=/root -v /home/shippable/cexec:/home/shippable/cexec -v /opt/docker/docker:/usr/bin/docker -v /home/shippable/cache:/home/shippable/cache -v /tmp/cexec:/tmp/cexec -v /var/run/docker.sock:/var/run/docker.sock --name=c.exec.<project>.<build>.<job> --entrypoint=/home/shippable/cexec/build.sh -e RUN_MODE=production -e SHIPPABLE_API_URL=https://api.shippable.com -e SHIPPABLE_API_RETRY_INTERVAL=3 -e SHIPPABLE_CONTAINER_NAME=c.exec.<project>.<build>.<job> -e SHIPPABLE_IS_OFFICIAL_IMAGE=false -e SHIPPABLE_IS_LEGACY_IMAGE=false <vendor>/<image>:<tag>

However, I *think* it would be better if Shippable didn't use `--entrypoint` but passed the script as command instead:

```diff
- sudo docker run -d -e HOME=/root -v /home/shippable/cexec:/home/shippable/cexec -v /opt/docker/docker:/usr/bin/docker -v /home/shippable/cache:/home/shippable/cache -v /tmp/cexec:/tmp/cexec -v /var/run/docker.sock:/var/run/docker.sock --name=c.exec.<project>.<build>.<job> --entrypoint=/home/shippable/cexec/build.sh -e RUN_MODE=production -e SHIPPABLE_API_URL=https://api.shippable.com -e SHIPPABLE_API_RETRY_INTERVAL=3 -e SHIPPABLE_CONTAINER_NAME=c.exec.<project>.<build>.<job> -e SHIPPABLE_IS_OFFICIAL_IMAGE=false -e SHIPPABLE_IS_LEGACY_IMAGE=false <vendor>/<image>:<tag>
+ sudo docker run -d -e HOME=/root -v /home/shippable/cexec:/home/shippable/cexec -v /opt/docker/docker:/usr/bin/docker -v /home/shippable/cache:/home/shippable/cache -v /tmp/cexec:/tmp/cexec -v /var/run/docker.sock:/var/run/docker.sock --name=c.exec.<project>.<build>.<job> -e RUN_MODE=production -e SHIPPABLE_API_URL=https://api.shippable.com -e SHIPPABLE_API_RETRY_INTERVAL=3 -e SHIPPABLE_CONTAINER_NAME=c.exec.<project>.<build>.<job> -e SHIPPABLE_IS_OFFICIAL_IMAGE=false -e SHIPPABLE_IS_LEGACY_IMAGE=false <vendor>/<image>:<tag> /home/shippable/cexec/build.sh
```

This way either images could specify an `ENTRYPOINT` or users via `build.pre_ci_boot.options` in their `shippable.yml`.

**Comment by mbrodala** [comment]
@ambarish2012 @kanthchandra could you have a look at this? I'd really like to know if there is something wrong with the Docker images or with the way Shippable uses them.

**Comment by trriplejay** [comment]
Shippable uses the entrypoint as a way to run the build script. If you bypass this, your build will not run correctly.  The best solution is to run whatever initialization you need in the `build.ci` section as the first step.

You mention that you tried this and it didn't work because bash required input, but how would this be any different if the script was executed as the `entrypoint` or `CMD` instead? Wouldn't it still be asking for input?

**Comment by mbrodala** [comment]
@trriplejay 

> Shippable uses the entrypoint as a way to run the build script. If you bypass this, your build will not run correctly.

But I *cannot* bypass this in the first place. If I could, I'd make sure that Shippable's script is executed properly in the end but ATM I don't even have that option.

> The best solution is to run whatever initialization you need in the build.ci section as the first step.

I don't need any initialization but the Docker container *must* be launched with a custom init script to work properly. See the [description of the mentioned Docker images](https://bitbucket.typo3.com/projects/T3COM/repos/bamboo-remote-agent/browse). It's built on the popular [passenger docker](https://github.com/phusion/passenger-docker) image from Phusion.

> You mention that you tried this and it didn't work because bash required input, but how would this be any different if the script was executed as the entrypoint or CMD instead? Wouldn't it still be asking for input?

The mentioned example using `bash` is for an interactive session in the container. Of course in case of a Shippable build the container run would look like this:

`docker run -it --rm typo3gmbh/php70:1.0 /sbin/my_init -- /home/shippable/cexec/build.sh`

Thus `my_init` is executed as command which wraps Shippable's build script and ensures everything is started and terminated correctly.

**Comment by trriplejay** [comment]
hmm, I see. I'll mark this as a feature request and see if we can implement some support that would allow you to run your custom script in place of our entrypoint.

**Comment by mbrodala** [comment]
@trriplejay do you have any update on this?

**Comment by trriplejay** [comment]
This is in our backlog. we'll be allowing entrypoint override for our runSh enhancement that allows the runSh job to execute inside a custom container, however I'm not yet sure of an ETA on enhancing the CI side of things.

**Comment by mbrodala** [comment]
Alright, let me know if you need anything else. :-)

**Comment by ambarish2012** [comment]
@mbrodala  we have implemented this feature. After you upgrade your subscription to the latest release, you can use a custom docker image in your runSh jobs as shown [here](http://docs.shippable.com/platform/tutorial/workflow/using-runSh/#using-a-custom-docker-image).

**Comment by mbrodala** [comment]
@ambarish2012 Would it be possible to get this working with the `options` from `pre_ci_boot`, too? This would be way easier to understand and integrate than the whole assembly line setup.

**Comment by manishas** [comment]
At this point, we don't have plans to implement the same functionality for CI, unless we hear a lot of +1 feedback. Closing as deferred.
