### ISSUE TITLE
skipped master branch results in build failure

### ISSUE THREAD

**Issue by rhenretta** [Shippable/support#3729]
Link: https://app.shippable.com/github/GoodwayGroup/TagGenerator/runs/145/summary/console

I don't have the master branch enabled in the shippable.yml and because of this on every commit to master, I get red on SPOG when the build fails with:

Errors  
Run skipped because the YML file does not allow this branch

Skipped runs should not result in an error

**Comment by rageshkrishna** [comment]
Hi @rhenretta. You're right, marking these builds as `failed` is a bad choice. I've added this to our backlog and will update this issue with an ETA as soon as possible.

**Comment by niranjan92** [comment]
The commits to master branch will be ignored if branch name is not enabled in the yml. I am able to reproduce the issue by manually triggering the build. 

@rhenretta :Can you please confirm if you are manually triggered the build or committing to the master branch?

**Comment by niranjan92** [comment]
@rhenretta we have fixed the issue.  Manually triggered builds, for branches that are not enabled,  are marked as `skipped` instead of failed. Commits to branches that are not enabled, will not trigger any builds as before. 

Please re-open the issue if you continue to have issues.

**Comment by rhenretta** [comment]
I think it was caused by pull requests to branches not enabled, but I'll take a look and make sure
