### ISSUE TITLE
Gitlab SCM is not able to sync manually

### ISSUE THREAD

**Issue by vrajroham** [Shippable/support#3731]
### Description of your issue:
SCM is not able to sync. We are using gitlab as SCM and today no pipelines are triggered from gitlab(May be gitlab issue). But I tried to sync repo manually but it's always gets timeout. I have shared the screen shot of it.

![screenshot from 2017-07-21 13 42 14](https://user-images.githubusercontent.com/12662173/28456890-93994038-6e21-11e7-8805-ed87f842689b.png)

**Comment by vrajroham** [comment]
I was able to sync from profile tab, but only after multiple times trying. Even now also automatic builds are not triggered.

**Comment by deepikasl** [comment]
@vrajroham thanks for reporting the issue, we are looking into it.

**Comment by vrajroham** [comment]
@deepikasl Everything is now working as expected. Closing the issue, but would like to know for future reference.
