### ISSUE TITLE
Cannot switch back to Shippable nodes

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3732]
I just tried BYON but failed to add a node (Docker issue due to ARM64 instead of AMD64). However now I am unable to switch back to the Shippable nodes:

> You are running builds on your own build nodes. To use Shippable nodes, first delete all the custom nodes.

However, there are no custom nodes anymore:

![image](https://user-images.githubusercontent.com/5037116/28461175-abec7fb2-6e15-11e7-9226-4c3eae100ca9.png)

Can you fix this ASAP? (Subscription Id 54f05f3c5ab6cc13528f2751)

**Comment by himanshu0503** [comment]
@mbrodala : We don't allow node switching while builds are still running, can you stop the running builds and try to switch?

**Comment by mbrodala** [comment]
Thanks, that did the trick. There was indeed a build running, after stopping it I was able to switch back.

Could you extend the Nodes management page to mention that all running builds must be stopped? If possible simply link to the subscription page which already shows all running builds.
