### ISSUE TITLE
Minions size with BYON

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3735]
The *Minions size* option in the _Subscription Billing_ page is always available, even when using BYON. Does this mean that Shippable uses at maximum the resources mentioned in the selected minion size?

Thus even if my build node has 4 CPU cores and 8 GB RAM will Shippable limit the builds to 2 CPU cores and 3,75 GB RAM with *c4.large*? Or is the minion size only relevant for Shippable nodes?

**Comment by kanthchandra** [comment]
No, we do not restrict the usage of any resources that are available on the machine. If your machine has 4 cores and 8 GB RAM, everything will be available to your build container. You can see the `boot_container` section of your consoles to see the options that we pass while spinning up the build container.

**Comment by mbrodala** [comment]
Thanks for clarification. Maybe that field could be hidden/disabled for BYON users to avoid confusion (+ a tooltip explaining why the option is not available)

**Comment by kanthchandra** [comment]
Yes, I will discuss this internally and open an issue to track this.

**Comment by mbrodala** [comment]
Thanks for removing the field on BYON. :-)
