### ISSUE TITLE
Build With PHP 7.1

### ISSUE THREAD

**Issue by Nexyssify** [Shippable/support#3737]
Hey, 

I want to upgrade PHP to 7.1 but Shippable instaled 7.0.1. 

Here my Shippable.yml : 
`language: php

php:
    - 7.1

services:
    - mysql

etc...
`

Can we use php 7.1 with shippable ?

**Comment by kanthchandra** [comment]
Hey @Nexyssify can you please point me to the build where this happened?

**Comment by Nexyssify** [comment]
Sorry, of course. 
https://app.shippable.com/github/StimuLab/StimulApp/runs/1807/1/console

**Comment by kanthchandra** [comment]
Hey @Nexyssify Please go to https://app.shippable.com/subs/github/StimuLab/nodes page and update the machine image to use v5.7.3 which has all the latest version of php. You are using an image which is over a year old.

**Comment by kanthchandra** [comment]
More info can be accessed here http://docs.shippable.com/reference/machine-image-v573/

**Comment by kanthchandra** [comment]
Hey @Nexyssify did it resolve your issue?

**Comment by Nexyssify** [comment]
Yes, thanks you very much :-)
