### ISSUE TITLE
Link from nodes to builds not working

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3738]
The node management view links to the current build a node is processing. However, the link is apparently invalid. Currently it looks like this:

`https://app.shippable.com/<vcs>/<subscription>/<project>/runs/<build>/<job>/`

However, it should look like this instead:

`https://app.shippable.com/<vcs>/<subscription>/<project>/runs/<build>/<job>/console`

Currently one is immediately redirected to his dashboard instead.

**Comment by mohit5it9** [comment]
@mbrodala This will be available in the next release!

**Comment by mbrodala** [comment]
Great. :-)

**Comment by kanthchandra** [comment]
Hey @mbrodala this has been fixed and deployed today morning. Can you please check?

**Comment by mbrodala** [comment]
Yes, works as expected now, thanks. :-)
