### ISSUE TITLE
403 on document accesses

### ISSUE THREAD

**Issue by paul42** [Shippable/support#3740]
I keep getting a 403 when trying to visit http://docs.shippable.com/reference/resource-gitRepo/
could be same as #3615 ?

**Comment by a-murphy** [comment]
We'll look into it.  Could you try http://docs.shippable.com/reference/resource-gitrepo/?

**Comment by paul42** [comment]
amusingly that worked. looks like the link I was following capitalized the R in getRepo.

**Comment by paul42** [comment]
The broken link is from the bottom of http://docs.shippable.com/reference/shippable-resources-yml/

**Comment by a-murphy** [comment]
Thank you.  That link will definitely be fixed in the next documentation update.
