### ISSUE TITLE
Filter `/runs` API (or others) based on commitSha

### ISSUE THREAD

**Issue by philipn** [Shippable/support#3741]
We'd like to be able to, based on a particular commit sha, figure out whether or not the commit lead to a successful shippable run.  Is there any way to do this besides pulling down the entire history of every run and filtering on our end?

**Comment by amiceli** [comment]
We're also interested by this feature.
It can be just a filter, not an endpoint ?

Example : 
`https://api.shippable.com/runs?commitSha=68ada5fd98181b2e4c19e5619eca766c051bfea9`

**Comment by a-murphy** [comment]
A `commitShas` filter is now available on the `GET /runs` route and documented [here](http://docs.shippable.com/platform/api/api-overview/#!/Runs/get_runs).  A comma-separated list of full commitShas can be used to query runs.
