### ISSUE TITLE
Example: pypi publishing

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#3742]
Hi, I see from #3175 and #3399 that publishing on pypi is now supported. 

I could not find, however, on the Shippable docs a minimal example on how to achieve this. Could you help me, or point me towards an example? 

thanks!

**Comment by deepikasl** [comment]
Hi @jacopo-chevallard, we have a custom integration named `Key-value pair integration` which will allow you to store any name value pair in an encrypted fashion.
Here is the docs link: http://docs.shippable.com/reference/int-key-value/#key-value-pair-integration
give your credentials as key-value pair in this integration and create it. You can use this integration in your build environment. Refer the above [docs](http://docs.shippable.com/reference/int-key-value/#key-value-pair-integration) link for more information.
