### ISSUE TITLE
shippable build failure

### ISSUE THREAD

**Issue by rakeshlacework** [Shippable/support#3743]
I am seeing these errors in the build log -

/usr/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory - /etc/default/datacollector (Errno::ENOENT)
	from /usr/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
	from /usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
	from /usr/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
	from /usr/lib/ruby/1.9.1/fileutils.rb:436:in `cp_r'
	from /var/lib/gems/1.9.1/gems/fpm-1.9.1/lib/fpm/package/rpm.rb:480:in `block in output'
	from /var/lib/gems/1.9.1/gems/fpm-1.9.1/lib/fpm/package/rpm.rb:476:in `each'
	from /var/lib/gems/1.9.1/gems/fpm-1.9.1/lib/fpm/package/rpm.rb:476:in `output'
	from /var/lib/gems/1.9.1/gems/fpm-1.9.1/lib/fpm/command.rb:487:in `execute'
	from /var/lib/gems/1.9.1/gems/clamp-1.0.1/lib/clamp/command.rb:68:in `run'
	from /var/lib/gems/1.9.1/gems/fpm-1.9.1/lib/fpm/command.rb:574:in `run'
	from /var/lib/gems/1.9.1/gems/clamp-1.0.1/lib/clamp/command.rb:133:in `run'
	from /var/lib/gems/1.9.1/gems/fpm-1.9.1/bin/fpm:8:in `<top (required)>'
	from /usr/local/bin/fpm:23:in `load'
	from /usr/local/bin/fpm:23:in `<main>'

**Comment by kanthchandra** [comment]
Hey @rakeshlacework can you please point me to the build please?

**Comment by rakeshlacework** [comment]
This is the build failure mail,

[image: Inline image 1]

Today morning when I click on the build id link, it is giving me 404. I
logged out and logged in back using my github account and don't see any
views. Please help.

Thanks,
Rakesh

**Comment by trriplejay** [comment]
@rakeshlacework  There was a github outage this morning that may have resulted in some permission issues.  Can you click the "sync" button on the account profile page, refresh your page, and let us know if you can see all of your views again?

**Comment by rakeshlacework** [comment]
Yes, I was able to figure that out when I checked with others who had no
issue. Now on to build failures, any ideas what broke the builds on Friday?

Thanks,
Rakesh

**Comment by rakeshlacework** [comment]
I am seeing between builds there is a change in fpm version. Success build
used fpm-1.8.1 and failure build is using fpm-1.9.1

Thanks,
Rakesh

**Comment by a-murphy** [comment]
Since you are installing `fpm` in your build, could you try installing 1.8.1 instead of 1.9.1?  Replacing `shippable_retry sudo gem install fpm` with `shippable_retry sudo gem install fpm -v 1.8.1` in your shippable.yml file will install 1.8.1.

It also looks like [1.9.2 is available](http://fpm.readthedocs.io/en/latest/changelog.html) and fixes an error with 1.9.1 if you want to try that.  (Just rerunning with your current shippable.yml will install the latest version of `fpm`.)

**Comment by rakeshlacework** [comment]
Thank you, I saw that and reran the build which succeeded. Can you provide
some details on how to debug using ssh to build node?

Thanks,
Rakesh

**Comment by rakeshlacework** [comment]
rebuild using fpm v1.9.2 fixed, the build failure problem. 

Can you point me a way to access node in debug mode via ssh that would be helpful.

Thanks,
Rakesh

**Comment by a-murphy** [comment]
Documentation on debugging with SSH is available [here](http://docs.shippable.com/ci/ssh-access/).  Once you've SSHed into the build node, you can use [`docker exec`](https://docs.docker.com/v1.9/engine/reference/commandline/exec/) to run commands in the running container.

**Comment by rakeshlacework** [comment]
Got it thank you. Go ahead and close the bug.

Thanks,
Rakesh
