### ISSUE TITLE
Notification for drydock/genexec updates

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3744]
Today I noticed that there was an update for in our Nodes section:

![image](https://user-images.githubusercontent.com/5037116/28769456-e2727f32-75db-11e7-86d5-1248b35bbb04.png)

It was purely coincidentally that I stumbled upon this since I was working on our nodes.

Would it be possible to get a notification for these updates somehow, if possible including a list of changes? There is no info at all on the [Docker Hub](https://hub.docker.com/r/drydock/genexec/tags/).

**Comment by mbrodala** [comment]
Can you have another look at this and at least provide the changelog for new image tags? It takes me roughly half an our to re-initialize a node with the latest image and manually drop the old one (see #3833) so I would like to know how urgent an update is.

**Comment by manishas** [comment]
We will look into providing a changelog for image updates.

**Comment by mbrodala** [comment]
We won't be using Shippable anymore.

But thanks so far!
