### ISSUE TITLE
Add a `test` section in the configuration

### ISSUE THREAD

**Issue by schettino72** [Shippable/support#3745]
From the docs:

>  The `ci` section is where you install dependencies, create databases and folders, 
   and include your build and test commands.

```
build:
  ci:
   - build1
   - build2
   - test1
   - test2
```

The problem is that when any command fails the subsequent command are not executed.
With this setup is that when `test1` fails, `test2` is not executed. 
I would like to have the overall build to fail but still see the result of `test2`.

For the actual build it makes sense to abort when anything fails but for tests it does not.
So I am proposing adding one more section to the configuration file. For example we could have:

```
build:
  ci:
   - build1
   - build2
  tests:
   - test1
   - test2
```

In the `test` section a failure in a command would not abort the process immediately.

**Comment by rageshkrishna** [comment]
If your tests can output standard junit XMLs, you could do this and copy all your test outputs to the standard folder for us to parse the results:

````
build:
  ci:
    - build1
    - build2
    - test1 || true
    - test2 || true
````

This way all your tests would execute, and if there are any test failures you will see your build status say "Unstable". Granted, it's not as _elegant_ as having a separate `tests` array in the YML, but maybe this will unblock your scenario.

**Comment by schettino72** [comment]
thanks for quick reply

oh. I didn't know about this `unstable` status.
I guess that is good enough for me... using `|| true` has the advantage of putting logical blocks of build + test together.
