### ISSUE TITLE
rSync failed with Error

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#3749]
I've changed shippable.jobs.yml 
and now rsync is failing with the error:
rSync encountered 1 errors while processing undefined: 
  - Attempted to update the resource:

https://app.shippable.com/github/kastenhq/jobs/k10_master_rSync/builds/597fb49b202dac07006d91b2

**Comment by depohmel** [comment]
Also, I've tried SPOG dry-run and it didn't show any errors.

**Comment by a-murphy** [comment]
It looks like you've tried to change the type of a resource in your shippable.jobs.yml.  Types cannot be changed.  If you want to add a new resource with the same name as the existing one, you'll have to delete the existing resource first by removing it from the `shippable.jobs.yml` file and then hard-deleting it on Shippable.
