### ISSUE TITLE
shippable keeps failing, says authentication failed.

### ISSUE THREAD

**Issue by gib65** [Shippable/support#3751]
Hello, we're having trouble with shippable. It keeps failing to build. says authentication failed.

This never happened before and we did nothing to change things.

Here is the console output:

npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/biznas/busboy.git /root/.npm/_git-remotes/git-https-github-com-biznas-busboy-git-45f8eee3: Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-biznas-busboy-git-45f8eee3'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/biznas/busboy.git /root/.npm/_git-remotes/git-https-github-com-biznas-busboy-git-45f8eee3: remote: Invalid username or password.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/biznas/busboy.git /root/.npm/_git-remotes/git-https-github-com-biznas-busboy-git-45f8eee3: fatal: Authentication failed for 'https://github.com/biznas/busboy.git/'
npm WARN deprecated ng2-tooltip@0.0.5: name updated to match new angular versions. install ngx-tooltip instead
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/biznas/ng2-uploader.git /root/.npm/_git-remotes/git-https-github-com-biznas-ng2-uploader-git-7d297f7f: Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-biznas-ng2-uploader-git-7d297f7f'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/biznas/ng2-uploader.git /root/.npm/_git-remotes/git-https-github-com-biznas-ng2-uploader-git-7d297f7f: remote: Invalid username or password.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/biznas/ng2-uploader.git /root/.npm/_git-remotes/git-https-github-com-biznas-ng2-uploader-git-7d297f7f: fatal: Authentication failed for 'https://github.com/biznas/ng2-uploader.git/'
npm ERR! Linux 3.19.0-51-generic
npm ERR! argv "/root/.nvm/versions/node/v6.10.3/bin/node" "/root/.nvm/versions/node/v6.10.3/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/biznas/busboy.git /root/.npm/_git-remotes/git-https-github-com-biznas-busboy-git-45f8eee3
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-biznas-busboy-git-45f8eee3'...
npm ERR! remote: Invalid username or password.
npm ERR! fatal: Authentication failed for 'https://github.com/biznas/busboy.git/'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/src/bitbucket.org/gibran_shah/riskalive/npm-debug.log

**Comment by a-murphy** [comment]
Have you updated the versions of any of your dependencies in your package.json?  Or are there any that just released a newer version that would now be installed based on your package.json?  It's likely that the error is from attempting to install a newer version of a dependency or dependency of a dependency.

**Comment by manishas** [comment]
@gib65 are you still running into this?

**Comment by gib65** [comment]
No, the problem is fixed. thanks very much.
