### ISSUE TITLE
How can I delete an unwanted flag?

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#3752]
### Description of your issue:
I have added a new flag but I didn't untick the default flag. 

![image](https://user-images.githubusercontent.com/14726381/28951186-bcb01898-790c-11e7-9fac-30184869fc2f.png)

Could you please tell me how I can delete an unwanted flag?

**Comment by ankul-shippable** [comment]
@JoeRattanamaneesilp Please go to your rSync job's config page. And uncheck the checkbox and this rSync job again.
1.  Goto your rSync job `car-service_shippable-pipeline_rSync`
2. On the top-right corner. click on the `wrench` icon to goto rSync configuration page
![1](https://user-images.githubusercontent.com/16793274/28955305-63fd9f08-7903-11e7-814e-97b44f851137.png)

3. On configuration page, uncheck the option for default flag and build this rSync job again. Your default flag will be removed from all the resources that have it.

![2](https://user-images.githubusercontent.com/16793274/28955310-6b81b8f4-7903-11e7-88f9-9e1a912973e6.png)

Please let us know if you are able to delete. Thanks

**Comment by JoeRattanamaneesilp** [comment]
@ankul-shippable  I have followed the instructions.
![image](https://user-images.githubusercontent.com/14726381/28956094-25df4962-792e-11e7-8b86-718984dd8946.png)

However, I still see it.
![image](https://user-images.githubusercontent.com/14726381/28956103-3e874154-792e-11e7-9631-00984ce72ff0.png)

Could you please advise?

**Comment by ankul-shippable** [comment]
Can you please try deselecting and and refreshing your page?

**Comment by JoeRattanamaneesilp** [comment]
@ankul-shippable Yes. I have deselected and refreshed. I can see it is unticked correctly.
Also, I have noticed there is a green popup as below.
![image](https://user-images.githubusercontent.com/14726381/28956409-0c9fad1e-7930-11e7-8563-60584e8ff101.png)

So I have rebuilt the sync job and it's gone now.

Thanks for the solution.

**Comment by ankul-shippable** [comment]
Great!
I am closing this issue. Please reopen if encounter any other issue related to this. Thanks.
