### ISSUE TITLE
Builds too slow and variable

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#3757]
Hi,

If you check https://app.shippable.com/github/eccosolutions/ecco/dashboard, you'll find that we've recently had builds time out that have at best been as low as 23 minutes.  The build that today timed out had not even got through to the slow UI tests.

Rebuilding that commit then gave a build of 42 minutes.  Whatever is going on, this is really not acceptable for a paid plan.  It costs developers time to investigate false negatives like this, so for now I've dropped back from paying you folks $75/mth to the free plan.

I get that you're iterating and rolling out features, but frankly I want to be able to get build times that are even close to my 4 year old dual core laptop, but I'd just settle for something predictable.

Please do something to sort this out.  When you're done, do give us a month back on this plan for free and we'll start paying again if things are working.

Thanks,

Neale

**Comment by manishas** [comment]
@nealeu we were experiencing long queuing times and builds today. We've been actively working on this all day and some temporary workarounds are in place and we're monitoring the system. Additional fixes will be deployed tonight and tomorrow. 

I looked at your subscription and saw one timed out build today. Were there  more timeouts? I also see the rebuild took 43 mins but the next build seemed more within normal range of ~30-35 mins. 

Please let me know if you're running into any other issues. I'll follow up with you over email to suggest ways of speeding up builds.

**Comment by nealeu** [comment]
Hi,

The build time is not as variable on my laptop, so why are we not getting near the 23 mins most of the time, especially as we are caching the Maven dependencies which is the only potential variable.

There seems to be contention on the box which would indicate that we're not getting a dedicated instance when our build starts or that some bottleneck is causing an issue during the build, which I can only think is the console logging, as nothing else is happening outside of the server instance at that point.

Cheer,
Neale

**Comment by mbrodala** [comment]
Right now I'm also seeing builds taking > 20 minutes which should be done in 2-3 minutes instead, e.g. project `54f05f3c5ab6cc13528f27b7`. The build itself indeed is slow but our own nodes don't have any load at all. Any idea?

**Comment by manishas** [comment]
@trriplejay can we look into this?

**Comment by trriplejay** [comment]
it looks like some kind of network issue in the case of @mbrodala 's project. for example, git_sync took almost 2 minutes. uploading coverage reports in one case took over 7 minutes...  it's strange for sure. we'll have to keep monitoring.

**Comment by mbrodala** [comment]
@trriplejay I just re-triggered that build and now it went through with 2-4 minutes as usual, thus it may indeed have been a temporary network issue. Would you happen to know if this could be caused by our own build nodes?

**Comment by trriplejay** [comment]
@mbrodala it's possible that it could be related to your node... it's hard to say for sure where the bottleneck might be. the "uploading coverage reports" step puts files in shippable's s3 bucket, on aws us-east-1, but git_sync is copying from the source provider, so the fact that both of these were slow could indicate that the node itself was having some kind of network issue.  The issue didn't seem widespread on our end, or at least there was no indication that other customers were having this issue.

**Comment by mbrodala** [comment]
OK, thanks for the confirmation.

**Comment by nealeu** [comment]
Hi,

We're still getting some weird behaviour like over a minute to install 
 sshpass (which by the way would be a good utillity to have by default on the images) See https://app.shippable.com/github/eccosolutions/ecco/runs/1050/1/console 

Thanks.
