### ISSUE TITLE
key-value pair: Invalid integration

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#3759]
Hi, I'm trying to build and publish on pypi using a key-value pair integration, but I'm getting the error

```
Invalid integration pypi specified for integration type : generic
```

Here the link to the build https://app.shippable.com/github/jacopo-chevallard/PyP-BEAGLE/runs/6/1/console

Am I doing something wrong?

thanks!

**Comment by ChaitanyaVootla** [comment]
@jacopo-chevallard, looks like the subscription integration you currently have is `PYPI`, please change that to `pypi` (lowercase) and try again.

**Comment by jacopo-chevallard** [comment]
You mean the integration name in Shippable? it is lowercase already (it was upper case initially, but I I changed it) 
![screen shot 2017-08-08 at 12 08 09](https://user-images.githubusercontent.com/8123595/29067261-48bdc4fc-7c32-11e7-8da1-7b95cde22e96.png)

**Comment by ChaitanyaVootla** [comment]
@jacopo-chevallard the subscription integration that was created still has the name set as `PYPI`, please update it too, you can find the subscription integrations page here:
![image](https://user-images.githubusercontent.com/8705710/29067517-934eacca-7c50-11e7-80e0-8d510dff9cf2.png)
on your subscription home page.

**Comment by ChaitanyaVootla** [comment]
please update the subscription integration and try again.

**Comment by jacopo-chevallard** [comment]
Oups, brilliant, thanks !!
