### ISSUE TITLE
MIssing lots of projects in overview

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3760]
See #3711 

Well, it is currently happening again. This time a colleage of mine, user (bitbucket) ceesgeene.

He is missing quite a few projects from his overview. For example fitpost.

**Comment by manishas** [comment]
@rageshkrishna can we look into this?

**Comment by rageshkrishna** [comment]
@bbrala We've been having some issues over the last couple of days that may have indirectly caused the issue your colleague is seeing. I can see now that his account has synced successfully, so he should be able to see the fitpost project in his dashboard. Can you please ask him to check once again and let me know if he's still having trouble?

Thanks.

**Comment by bbrala** [comment]
Think things solved themselves. Ill open another ticket if it happens again. Thanks.
