### ISSUE TITLE
Job queued with 3 "free" workers /  processing jobs shows finished jobs / etc

### ISSUE THREAD

**Issue by cratz** [Shippable/support#3763]
For some reason all deploy jobs are queued for ages without a visible reason (0/3 workers)
"Processing jobs" list a job which is already finished.
for all this stuff a "refresh", neither with refresh button nor with hard browser refresh, changes nothing. 

With the new shippable interface it's already more than hard to have a proper oeverview of the projects, "latest status" is useless to find a specific project but the worst is the performance each click takes ages :(
Is also not possible to have the dashboard open in 2 tabs with 2 different views (e.g. SPOG and Grid) 
Is there a way to get the old and working interface back?

**Comment by bbrala** [comment]
Yeah got the same here, jobs arn't starting and are piling up :(

**Comment by manishas** [comment]
Looking into this.

**Comment by cratz** [comment]
Thanks a lot!

**Comment by manishas** [comment]
Service is back up. Sorry for the problems you're seeing today.... we're looking into the slow queuing of builds. Please follow the support issue at https://github.com/Shippable/support/issues/3767
