### ISSUE TITLE
The Resource type is not available in integrations

### ISSUE THREAD

**Issue by christianmoretti** [Shippable/support#3764]
Hi,

I'm trying to create another integration (notification -> Event Trigger) but in the option "What would you like to trigger?" doesn't appear the option "Resource":

<img width="1093" alt="imagem_colada_08_08_17_16_08" src="https://user-images.githubusercontent.com/1626925/29090296-75e6ec4c-7c55-11e7-995b-15e836cec38b.png">

In another older integration the "resource" option are available:
<img width="1104" alt="imagem_colada_08_08_17_16_22" src="https://user-images.githubusercontent.com/1626925/29090410-dc431e66-7c55-11e7-9363-039e2c00af24.png">

If possible i need to know what I missing, thanks for attention.

**Comment by a-murphy** [comment]
Resource event triggers were deprecated several months ago.  We recommend connecting your CI builds to the rest of your pipeline using `runCI` jobs.  Documentation to help you do this is available [here](http://docs.shippable.com/ci/trigger-pipeline-jobs/).  If you don't see the runCI job in your subscription you may need to click the hook pipeline button on the project settings page.
