### ISSUE TITLE
Jobs stuck in queue

### ISSUE THREAD

**Issue by jkenn99** [Shippable/support#3765]
The jobs queue doesn't seem to be running at all for my account. I have jobs that have been waiting three hours to run. https://app.shippable.com/github/advisorwebsites/d8platform/runs/10728/summary/

**Comment by manishas** [comment]
We're working on this with the highest priority.

**Comment by manishas** [comment]
Service is back up. We're still looking into slow queuing of builds. Please follow the support issue at https://github.com/Shippable/support/issues/3767
