### ISSUE TITLE
Shippable not working

### ISSUE THREAD

**Issue by rsinnet** [Shippable/support#3766]
Repro steps:
1. Go to shippable.com
2. Observe that server is unavailable

How long will this outage be? Is this planned? Is Shippable going out of business?

**Comment by trriplejay** [comment]
Unfortunately we are currently experiencing a major outage. We're working to get things back online as soon as possible: http://status.shippable.com/

**Comment by manishas** [comment]
The service is back up now. There is still a problem with slow queueing of builds, which we're looking into. Please follow the support issue https://github.com/Shippable/support/issues/3767
