### ISSUE TITLE
PLEASE READ: Builds are being queued slowly

### ISSUE THREAD

**Issue by manishas** [Shippable/support#3767]
UPDATE: The service is back up. There is still a delay in queueing builds, and we're looking into that right now.

----

We are currently experiencing a major service outage.

Status is posted at https://status.shippable.com

We're actively working on recovering as soon as we can. We'll post updates as we go along.

**Comment by manishas** [comment]
We will have an update in 30 minutes. Our DB is down because for some reason EC2 isn't recognizing  the volumes.

**Comment by rhenretta** [comment]
Any new update?

**Comment by manishas** [comment]
The service should be back up very soon, but we're still looking at what's causing slow queuing of builds. I'll update the title of this issue once the service is back up and use it to track the queuing issue.

**Comment by manishas** [comment]
The service should be back up now. We're still looking into the queuing slowness.

**Comment by manishas** [comment]
Our queue has caught up and builds should no longer be slow to trigger.

We are closely monitoring the situation. I will leave this open for a while to make sure nobody is running into it again.

**Comment by manishas** [comment]
I am closing this since nobody has reported this for a while and our monitoring also shows that builds are being triggered as usual.
