### ISSUE TITLE
Inconsistencies in displayed commit message and SHA in runs view

### ISSUE THREAD

**Issue by ybart** [Shippable/support#3768]
In the Runs view, when pushing multiple commits at once some information does not look consistent:

- Commit Msg : this currently shows the first (older) commit included in the push. I believe this should show the most recent commit message instead. I thought the most recents commits were not taken in account because I the message I read was not the most recent. 
- Commit SHA : This shows the SHA for the most recent commit, but links to the least recent commit from the last push. (The SHA in href does not match the one in the title).

**Comment by a-murphy** [comment]
Thank you for reporting this.  We'll let you know when this is fixed.  It looks like it only occurs when processing GitLab webhooks, is your project on GitLab?

**Comment by ybart** [comment]
Yes, the project is absolutely on GitLab.

**Comment by trriplejay** [comment]
@ybart This should now be fixed. please let us know if you're still seeing this issue.
