### ISSUE TITLE
Build stuck in processing

### ISSUE THREAD

**Issue by rhenretta** [Shippable/support#3769]
link: https://app.shippable.com/github/GoodwayGroup/appgenerator/runs/14/1/console

There was an error in wait_for_exit:
sudo docker rm -fv $CONTAINER_NAME 0s  
Error response from daemon: no such id: c.exec.appgenerator.14.1
Error: failed to remove containers: [c.exec.appgenerator.14.1]

**Comment by trriplejay** [comment]
This looks like a symptom related to some of the queueing and timeout issues we saw last week. This should be resolved now. please reopen if you're still running into this.
