### ISSUE TITLE
Build badges docs entry not up to date

### ISSUE THREAD

**Issue by schumannd** [Shippable/support#3770]
The first two points state:

* Go to your Project in the UI and click on Settings

* Click on Badges in the left sidebar menu

I can not find `Badges` in any sidebar. Is this only available if certain prerequisites are met? If so, then that should be stated as well.

**Comment by manishas** [comment]
@schumannd Thanks for pointing this out... we'll get it updated asap.

In the meantime, here is how you get badges for a project:

1. In the left sidebar, click on the subscription name:
![image](https://user-images.githubusercontent.com/2983749/29174554-84dbe33c-7d9b-11e7-88a2-b135ffb7ac19.png)

2. On the subscription dashboard, click on the project you want the badge for. This will take you to 
 your project dashboard:
![image](https://user-images.githubusercontent.com/2983749/29174596-9dd99a78-7d9b-11e7-8a41-eb983feb4e50.png)

3. Click on the 'Badges' icon... the one that looks like a card:
![image](https://user-images.githubusercontent.com/2983749/29174692-eee8b962-7d9b-11e7-9b32-9242c838e4fd.png)

**Comment by schumannd** [comment]
Hello Manisha,

unfortunately the badges Icon and the Wrench icon are missing. This is what my view looks like.

**Comment by manishas** [comment]
The image didn't come through.  Can you send it again?

What permissions do you have on that organization and project in GitHub?

**Comment by schumannd** [comment]
Hello Manisha,

It is a bitbucket project, and I have admin rights.

Please find the image attached.

best,
David

**Comment by manishas** [comment]
The image isn't showing up on this issue... can you send it to me at manisha@shippable.com

Also, what is the bitbucket username you sign in with?

**Comment by ambarish2012** [comment]
@schumannd hope your issue is resolved. Please feel free to reopen if you need any further assistance.
