### ISSUE TITLE
SSH Key Verification Failure after creator disabled OAuth

### ISSUE THREAD

**Issue by carrollgt91** [Shippable/support#3773]
### Description of your issue:
Yesterday, the person who initially set up shippable revoked OAuth access to shippable.
Immediately, our `git-sync` stage of all CI started failing.
 
I've since recreated the Account Integration using a new user, new github API token (the user does have correct permissions), and I reset the subscription to generate a new SSH key. I added that SSH key to the new user. I believe (though have not been able to confirm) that there's a stale SSH key somewhere that was associated with the account which revoked OAuth access yesterday.

Please advise, we're in the middle of an important series of releases and could really use our CI system in full working order at the moment.

- Link to the build failure:
https://app.shippable.com/github/satchelhealth/wholphin-client/runs/327/1

**Comment by a-murphy** [comment]
Could you click the "reset all keys" button on the project settings page?  If the deploy key was added to GitHub by the account that revoked access, GitHub would have automatically deleted the key.  Clicking "reset all keys" will add a new deploy key to the repository on GitHub.

To get to the project settings page from the page you linked above, click on the project name in the breadcrumb at the top of the page and then the gears in the top right.  The reset button is near the bottom of the project settings page.

**Comment by carrollgt91** [comment]
Unfortunately, I get the following message when I try to do so:

```getOwnerByProjectId failed for :projectId 57c5ea0778d0c810003cd62f returned an error: A project owner must be signed-in to Shippable to complete this operation for projectId: 57c5ea0778d0c810003cd62f```

**Comment by a-murphy** [comment]
Could you ask someone with admin permissions on the repository to click the button?  Or, if you have admin permissions that aren't being recognized, could you try synchronizing your account (click "profile" on the left and then "sync") and trying again?  That button recreates the deploy key and webhook on GitHub, which requires admin permissions.
