### ISSUE TITLE
How do I move a dependency from one credit card to another?

### ISSUE THREAD

**Issue by BrianSkipworth** [Shippable/support#3774]
In the "Account / Profile / Credit Card" section of my account, I need to remove a credit card, but cannot figure out how to move it's dependency to another credit card before deleting.

**Comment by manishas** [comment]
Is the card being used to pay for a subscription?

**Comment by deepikasl** [comment]
@BrianSkipworth In your subscription billing page, you can see `card` field in `plan` section. If you want to change the card, click on it and choose. 
![image](https://user-images.githubusercontent.com/18304961/29239343-1b0fcbb4-7f6a-11e7-960e-c6f1eae6fd1f.jpg)

After that save the billing plan. Now your subscription will use the new card you have choosed.
![screenshot from 2017-08-12 14 29 10](https://user-images.githubusercontent.com/18304961/29239362-a4060262-7f6a-11e7-9df8-b53e30eeadc5.png)

**Comment by BrianSkipworth** [comment]
Thank you!
