### ISSUE TITLE
Build failing due to old JDK version

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#3779]
We have a Java 8, Maven project that is failing to compile due to JDK version 1.8.0 patch 25 being used by the Shippable build system.

Here are snippets from the failing build:

    sudo update-alternatives --set java /usr/lib/jvm/java-8-oracle/jre/bin/java

    sudo update-alternatives --set javac /usr/lib/jvm/java-8-oracle/bin/javac

    java -version

    java version "1.8.0_25"
    Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
    Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

    [ERROR] COMPILATION ERROR : 
    [ERROR] /home/shippable/workspace/src/bitbucket.org/project/src/main/java/ReportingService.java:[161,67] no suitable method found for collect(java.util.stream.Collector<java.lang.Object,capture#1 of ?,java.util.Set<java.lang.Object>>)
        method java.util.stream.Stream.<R>collect(java.util.function.Supplier<R>,java.util.function.BiConsumer<R,? super capture#2 of ? extends Trend>,java.util.function.BiConsumer<R,R>) is not applicable
            (cannot infer type-variable(s) R
                (actual and formal argument lists differ in length))

This bug is described in the [Java bug archive](http://bugs.java.com/view_bug.do?bug_id=8033483) and was fixed in Oracle JDK 1.8.0 patch 40. Unfortunately, there is no workaround for this issue in the code, as the problem is due to a bug in the Java compiler.

Shippable build system must upgrade to the latest JDK 8 version so that our builds start working again.

**Comment by rageshkrishna** [comment]
@manish-in-java What image are you using to run your builds? We release new images monthly with updated language versions. For example, `drydock/u14javall:v5.7.3` has a newer JDK:

```
$ docker run drydock/u14javall:v5.7.3 /bin/bash -c "java -version"

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

**Comment by manish-in-java** [comment]
@rageshkrishna, how do I find out the Docker image being used? Our `shippable.yml` file as the following content:

    language: java
    jdk:      oraclejdk8
    script:
      - shippable_retry mvn clean test

**Comment by manish-in-java** [comment]
Ok, found the image details from the Subscriptions page. Here is a screenshot.

![shippable](https://user-images.githubusercontent.com/1606819/29520991-38543e60-86a1-11e7-899c-a7c02e918af9.png)

**Comment by a-murphy** [comment]
I couldn't find the project you're reporting problems with.  Could you include either a link to a build that you expect to be using the newer image or the project ID at the bottom of that page?

If you haven't specified an image tag in your shippable.yml, selecting a newer machine image on the subscription nodes page should update the image used for builds in that subscription.  It would help if you could try setting the machine image to a newer image again, trigger a build, and let us know which build and which machine image.

**Comment by manish-in-java** [comment]
[Here](https://app.shippable.com/accounts/55d549ca6ed0590b008bba40/dashboard) is the link to my account dashboard. You can check builds 1877 or 1878.

**Comment by a-murphy** [comment]
It looks like that project was enabled before we had the option of selecting a machine image.  As a result, it has an older default image.  To use a newer image, you'll have to specify it in your `shippable.yml` in the [pre_ci_boot](http://docs.shippable.com/ci/yml-structure/#anatomy-of-shippableyml) section.  Changing the machine image will update the image for projects enabled March 2016 or later, but projects older than that will continue to use the older image.

Your YML should be something like this:
```YML
language: java
jdk:
  - oraclejdk8
build:
  pre_ci_boot:
    image_name: drydock/u16javall
    image_tag: v5.8.2
  ci:
   - mvn install -DskipTests=true
    - shippable_retry mvn clean test

**Comment by manish-in-java** [comment]
Thanks @a-murphy, I will try and update here on how things go.

**Comment by manish-in-java** [comment]
@a-murphy, your suggestion worked. Builds seem to be passing now.
