### ISSUE TITLE
Build the project on AWS ec2

### ISSUE THREAD

**Issue by glozhkovoy** [Shippable/support#3780]
Hello, I have fully integrated CI and CD but I need to run npm install(I think it's unnecessary) **npm build** and **npm start** in order to start my application on ec2 instance

Those are my ymls

**shippable.yml**

> language: node_js
> node_js:
>   - 7.4.0
> 
> branches:
>   only:
>     - master
> 
> env:
>   global:
>     - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
>     - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
>     - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
>     - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
> 
> build:
> 
>   ci:
>     - shippable_retry npm install
>     - docker build -t testshippable .
>     - docker tag testshippable:latest **PATH**/testshiprep:latest
>   post_ci:
>     - docker push **PATH**/testshiprep:latest
>     - echo "versionName=latest" >> shipdemo-img.env
>     - echo "commitSha=$COMMIT" >> shipdemo-img.env
> 
> 
> integrations:
>   hub:
>     - integrationName: ECR_INTEGRATION
>       region: us-west-1
>       type: ecr

**shippable.resources.yml**

> resources:
>   - name: shipdemo-img
>     type: image
>     integration: ECR_INTEGRATION
>     pointer:
>       sourceName: "**PATH**/testshiprep" 
>       isPull: false
>     seed:
>       versionName: "latest"  
> 
>   - name: shipdemo-img-options
>     type: dockerOptions
>     version:
>       portMappings:
>         - 3000:3000
> 
>   - name: ecs-test-cluster
>     type: cluster
>     integration: AWS_INTEGRATION
>     pointer:
>       sourceName : "testshipcluster" 
>       region: "us-west-1" 

**shippable.jobs.yml**

> jobs:
>   - name: shipdemo-manifest
>     type: manifest
>     steps:
>      - IN: shipdemo-img
>      - TASK: managed
>        
>   - name: Test_Shippable_runCI
>     type: runCI
>     steps:
>       - OUT: shipdemo-img
>        
>   - name: shipdemo-test-deploy
>     type: deploy
>     steps:
>       - IN: shipdemo-manifest
>         force: true
>       - IN: shipdemo-img-options
>       - IN: ecs-test-cluster
>       - TASK: managed
>         deployMethod: replace

I have tried to add to the job file **runSH** scripts so I added this:

> - name: shipdemo-script
>     type: runSh
>     steps:
>       - IN: shipdemo-img
>       - TASK:
>         - script: npm install 
>         - script: npm build
>         - script: npm start
>     on_success:                                 #optional
>     - script: echo 'This block executes after the TASK section executes successfully'
>     - NOTIFY: email
>     on_failure:                                 #optional
>     - script: echo 'This block executes if the TASK section fails'
>     - NOTIFY: email

but rSync failed with   **- Missing dependency for job: shipdemo-script**

**Comment by trriplejay** [comment]
I'd recommend performing the npm install and npm build as part of your docker build workflow.  The npm run would then be your container's entrypoint.  Ideally the image should already be installed and packaged during the CI step in such a way that your application will run when the container is run on ECS.

what does your Dockerfile look like?

**Comment by glozhkovoy** [comment]
> Ideally the image should already be installed and packaged during the CI step in such a way that your application will run when the container is run on ECS.

That's what I'm trying to accomplish. I did **npm install** and **npm build** during CI step so everything I need is call npm start on ECS

I doesn't have dockerfile. You think I need to set it up?

**Comment by trriplejay** [comment]
well I see this line in your shippable yml: `docker build -t testshippable .`  In order for that command to succeed, there must be a `Dockerfile` in your repo. That file should contain instructions for mounting your sourcecode, performing npm install, and then setting a default entry point or CMD to run when the container starts.  It would look something like this:
```
FROM node:7.10.1  #base image to start from, see https://hub.docker.com/_/node/

RUN mkdir -p /usr/src/app  # this is where your source will live in the image
WORKDIR /usr/src/app

ADD . /usr/src/app  # take your current source (.) and add it to /usr/src/app in the image

RUN npm install  # now that your source is added, including package.json, run npm install

ENTRYPOINT ["npm", "start"]  # when this image is run as a container, run npm start by default
```

I havent tried this specific dockerfile so it might need some tweaking for your scenario but that's the gist of it.  All of these steps get executed when you issue `docker build`, and the resulting image will contain your source, along with the source installed by npm install, such that an npm start should start your app (if it's defined correctly in the package.json)

**Comment by glozhkovoy** [comment]
I found the **Dockerfile**
It looks like

> FROM node:latest
> 
> # Create app directory
> RUN mkdir -p /usr/src/app
> 
> RUN ls -la .
> 
> WORKDIR /usr/src/app
> 
> # Install app dependencies
> COPY package.json /usr/src/app/
> RUN npm install
> 
> # Bundle app source
> COPY . /usr/src/app
> 
> EXPOSE 3000
> CMD [ "npm", "start" ]

You want me to change it as you wrote or his current state is okay?

**Comment by trriplejay** [comment]
actually that looks good, assuming your app is listening to port 3000. so when your container starts on ECS during the shippable deploy job, it should already be running the `npm start`, and your app should be running. Are you having trouble connecting to it? is port 3000 reachable on your instance? do you see any error messages in the service event logs in ECS?

**Comment by glozhkovoy** [comment]
That's the picture of logs
![image](https://user-images.githubusercontent.com/20016615/29432594-eaba301e-83a4-11e7-9bca-dfbedd0c9474.png)


That's newer Dockerfile

> FROM mhart/alpine-node:latest
> 
> RUN mkdir -p /usr/src/app
> WORKDIR /usr/src/app
> 
> # Install app dependencies
> COPY package.json /usr/src/app/
> RUN npm install
> 
> COPY . /usr/src/app
> 
> EXPOSE 443
> EXPOSE 3000
> EXPOSE 80
> 
> CMD ["npm", "run", "start"]

Trying to get access to my site but it fails with 404

> login.mySite.com/:30 GET 
> http://login.mySite.com/build/scripts.min.js 
> 23:57:23.520 login.mySite.com/:30 GET 
> http://login.mySite.com/build/scripts.min.js 404 (Not Found)

**Comment by trriplejay** [comment]
based on the events, it seems like the container is running. are you sure your app is listening to 3000? are you accessing your site directly at port 3000? if you're adding `443` and `80` as extra ports, you'll have to also add them to your dockerOptions resource in the `portMapping` section.  if you plan to use them to access the site.  Is your instance part of a security group? if so, are the correct ports accessible in the security group?

Not sure what your last few lines are showing. you should have some ec2 domain or public IP that that you can hit at port `3000` or whichever port you've mapped to the port your container is listening to (via portMapping dockerOptions)

**Comment by glozhkovoy** [comment]
I figured out what was the problem so you can close the topic. Thank you for advises

**Comment by trriplejay** [comment]
great! let us know if you have any more questions. closing.
