### ISSUE TITLE
Shippable configuration

### ISSUE THREAD

**Issue by glozhkovoy** [Shippable/support#3782]
Hello again :)

This question related to #3775 . I'm trying to repeat these steps for private repository that shared for me. All of the shippable integration set up on the private repo.
For example I made a dev branch on private repo and using my setting for yml testing some environment.
#3775 We did that I was able to upload automatically image on the aws instance every time I push something but it doesn't work for this project here my setting because I have no idea how to resolve it.

BTW I'm not able to see how's rSync running and SPOG view, but if I run dry SPOG it showed me something.

**shippable.yml**

> language: node_js
> node_js:
>   - 7.4.0
> branches:
>   only:
>     - dev
> 
> env:
>   global:
>     - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
>     - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
>     - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
>     - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
> 
> build:
> 
>   ci:
>     - shippable_retry npm install
>     - docker build -t testshippable . 
>     - docker tag testshippable:latest **rep**/testshiprep:latest
>   post_ci:
>     - docker push **rep**/testshiprep:latest
>     - echo "versionName=latest" >> $JOB_STATE/shipdemo-img.env
>     - echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/shipdemo-img.env
> 
> 
> integrations:
>   hub:
>     - integrationName: crep-dev-ecr
>       region: us-west-1
>       type: ecr
>   notifications:
>     - integrationName: crep-email-notification
>       type: email
>       recipients:
>         - emails
>       branches:
>         only:
>           - master
>           - dev
>       on_success: always
>       on_failure: always

**shippable.resources.yml**

> resources:
>   - name: shipdemo-img
>     type: image
>     integration: crep-dev-ecr
>     pointer:
>       sourceName: "**rep**/testshiprep" 
>       isPull: false
>     seed:
>       versionName: "latest" 
> 
>   - name: shipdemo-img-options
>     type: dockerOptions
>     version:
>       portMappings:
>         - 3000:3000
>         - 8000:8000
>         - 443:443
>         
>   - name: ecs-test-cluster
>     type: cluster
>     integration: crep-dev-aws #Name of your AWS integration
>     pointer:
>       sourceName : "testshipcluster" 
>       region: "us-west-1"

**shippable.jobs.yml**

> jobs:
>   - name: shipdemo-manifest
>     type: manifest
>     steps:
>      - IN: shipdemo-img
>      - TASK: managed
> 
>   - name: MyRepositoryName_runCI
>     type: runCI
>     steps:
>       - OUT: shipdemo-img
> 
>   - name: shipdemo-test-deploy
>     type: deploy
>     steps:
>       - IN: shipdemo-manifest
>         force: true
>       - IN: shipdemo-img-options
>       - IN: ecs-test-cluster
>       - TASK: managed
>         deployMethod: replace

*DockerFile*

> FROM mhart/alpine-node:latest
> 
> MAINTAINER Dev
> 
> RUN mkdir -p /usr/src/app
> 
> COPY package.json /usr/src/app/
> COPY . /usr/src/app
> 
> WORKDIR /usr/src/app
> 
> RUN npm install
> RUN npm run build
> 
> EXPOSE 443
> EXPOSE 3000
> EXPOSE 8000
> EXPOSE 80
> 
> CMD ["npm", "run", "start"]

**package.json**

> {
>   "name": "contingency-plots",
>   "version": "1.0.0",
>   "main": "index.js",
>   "scripts": {
>     "build": "webpack",
>     "dev": "concurrently --kill-others  \"npm run start-dev\" \"npm run start-dev-api\"",
>     "start-dev-api": "NODE_ENV=dev nodemon ./api",
>     "start-dev": "NODE_ENV=dev webpack && webpack-dev-server ./build/scripts.min.js ./build/login.min.js --content-base --watch --hot --inline",
>     "prod": "concurrently --kill-others  \"npm run start-prod\" \"npm run start-prod-api\"",
>     "start-prod": "NODE_ENV=prod webpack && node server.js",
>     "start-prod-api": "NODE_ENV=prod nodemon ./api",
>     "watch": "webpack -w",
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   .....

That's SPOG view of my test rep
![image](https://user-images.githubusercontent.com/20016615/29496477-459df1e4-85dc-11e7-9fbf-445a580dd9c4.png)

That's SPOG view of my private rep
![image](https://user-images.githubusercontent.com/20016615/29496516-bb633dc6-85dc-11e7-8b69-cf94a6e839da.png)

That's SPOG DRY RUN
![image](https://user-images.githubusercontent.com/20016615/29496528-fa4acf5e-85dc-11e7-93cb-55ee278f9bd6.png)

AWS cluster service
![image](https://user-images.githubusercontent.com/20016615/29496536-13adc85c-85dd-11e7-8825-e187e7261e7e.png)

AWS cluster task
![image](https://user-images.githubusercontent.com/20016615/29496538-275be258-85dd-11e7-94b2-3a44ba71acc8.png)

AWS task definitions
![image](https://user-images.githubusercontent.com/20016615/29496543-357dec78-85dd-11e7-9606-aa2f8f5ed8e1.png)

AWS repository
![image](https://user-images.githubusercontent.com/20016615/29496550-64f8ee80-85dd-11e7-9220-7b738fe03fc4.png)

------
This setup works locally and on the server. It runs **"start-dev-api"** script but when I tried to change it to **CMD ["npm", "run", "prod"]** it doesn't work on the server but it works locally (that's how I run the project.) but not working when I deployed on the instance.
------

First issue is that I killed my task Definitions on AWS because I expected that they would resume work but they wouldn't.

Second issue -- On AWS instants I'm not getting latest image but I have it in repo

Third issue -- npm run prod isn't working 

I tried to describe it deepest as I can.

**Comment by glozhkovoy** [comment]
New details
----
rSync Never started with private repo that's why we never got our image delivered. 
As far as I know task definition for this was created by hands instead of generating by shippable.

That's all of task definitions that we're using for different clusters .
![image](https://user-images.githubusercontent.com/20016615/29499234-75efb1f0-8615-11e7-8e49-110f7b062a4f.png)

What should we do with that? Can we say somewhere in yml that we want to generate or work with task definition with concrete name like **crep_prod**

Thank you

**Comment by trriplejay** [comment]
if you've added new shippable resources/jobs ymls to a new private repo, you'll have to add that private repo as a sync repo, and it will create its own rSync job specifically for resources and jobs in that repo, so you'll have to go through that process again by clicking then `+` button in the top right of the subscription page.  

Regarding ECS not running your latest image: from what I can tell, if you already have an image with tag: `latest` on the machine, then when an ECS task starts, it will not pull latest again. it will see that latest already exists and it will just run the existing one.  The recommended way to address this is to use unique tags for each image that you generate that you'd like to deploy.  so instead of pushing tag `latest` during CI, you can set a dynamic tag like `$BRANCH.$BUILD_NUMBER` or `$COMMIT`, and this way every time ci runs, it will produce a unique tag, and then ECS will be forced to pull that specific versoin of the image.

regarding task definition naming: we have some documentation [here](http://docs.shippable.com/deploy/amazon-ecs-naming-conventions/) on how to specify a service name, but you cannot directly specify a task definition name.  If you want the name to stay consistent, i'd recommend using `deployMethod: upgrade` or `replace`, since those will keep a consistent service name through every deployment. The task definition `family` will be consistent.  it's defined as `<jobName>-<manifestName>`, so while you cannot customize it, it is very predictable.

**Comment by glozhkovoy** [comment]
> if you've added new shippable resources/jobs ymls to a new private repo, you'll have to add that private repo as a sync repo, and it will create its own rSync job specifically for resources and jobs in that repo, so you'll have to go through that process again by clicking then + button in the top right of the subscription page.

That was the case. I haven't notice that before.

Thank you. @trriplejay helped me a lot.
