### ISSUE TITLE
setup_php failded with no error

### ISSUE THREAD

**Issue by Nexyssify** [Shippable/support#3783]
Hey, 

I am using a custome installation for PHP 5.5.38. But since today (I didn't change anything in the shippable.yml) the build for setup_php failded but with no error. Did you change anything ? 

Here my shippable.yml : 

> language:
> 
>  php
> 
> php:
>   - 5.5.38
> 
> services:
>     - mysql
> 
> env:
>   global:
>    - SYMFONY_ENV="test"
>    - SYMFONY__ENV__DATABASE_USER='shippable'
>     - SYMFONY__ENV__DATABASE_PASSWORD=''
>     - SYMFONY__ENV__DATABASE_NAME='symfony'
> 
> before_install:
>   - export PATH=$HOME/.phpenv/bin:$HOME/.phpenv/extensions:$PATH && eval "$(phpenv init -)"
>   - phpenv global $SHIPPABLE_PHP_VERSION
> 
> before_script:
>     - mysql -e "create database symfony_test;"
>     - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
>     - echo 'memory_limit = 1024M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
>    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
>     - php -r "if (hash_file('SHA384', 'composer-setup.php') === '669656bab3166a7aff8a7506b8cb2d1c292f042046c5a994c43155c0be6190fa0355160742ab2e1c88d40d5be660b410') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
>     - php composer-setup.php --version=1.4.1
>     - php -r "unlink('composer-setup.php');"
>     - chmod +x composer.phar
> 
>     - sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
>     - php ./composer.phar install
>     - php app/console doctrine:schema:update --force --env=test
>     - php app/console doctrine:fixtures:load --env=test
> 
> 
> after_failure:
>     - cat app/config/parameters.yml
> 
> script:
>     - vendor/phpunit/phpunit/composer/bin/phpunit -c app --log-junit shippable/testresults/junit.xml --coverage-clover shippable/codecoverage
> 

And here my error report : 

>[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 5.5.38 into /root/.phpenv/versions/5.5.38
[Downloading]: https://secure.php.net/distributions/php-5.5.38.tar.bz2
[Preparing]: /tmp/php-build/source/5.5.38
[Compiling]: /tmp/php-build/source/5.5.38
[xdebug]: Installing version 2.5.0
[xdebug]: Compiling xdebug in /tmp/php-build/source/xdebug-2.5.0
[xdebug]: Installing xdebug configuration in /root/.phpenv/versions/5.5.38/etc/conf.d/xdebug.ini
[xdebug]: Cleaning up.
[Info]: Enabling Opcache...
[Info]: Done
[Info]: The Log File is not empty, but the Build did not fail. Maybe just warnings got logged. You can review the log in /tmp/php-build.5.5.38.20170821092840.log
[Success]: Built 5.5.38 successfully.
/usr/local/bin/phpenv-install: line 76: phpenv: command not found
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/ec18f22b-60d9-417d-aacb-ab4b8e4c99f4.sh'
Exception Script failure tag received
ERROR:script_runner - script_runner:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/ec18f22b-60d9-417d-aacb-ab4b8e4c99f4.sh'
Exception Script failure tag received
echo 'No test reports exist, skipping test report processing'
No test reports exist, skipping test report processing

Thank.

**Comment by scriptnull** [comment]
Hi @Nexyssify, 

We are looking into this right now. We will provide an update on this soon.

**Comment by Nexyssify** [comment]
Ok, thanks.

**Comment by nranjanShippable** [comment]
Hi @Nexyssify,
The issue has been rectified. You should be able to run your project as before with PHP 5.5.38.
You can re-open this issue if the build fails again.

**Comment by Nexyssify** [comment]
That's good ;-), Thanks.
