### ISSUE TITLE
Shippable needs a valid YML file to build your project.

### ISSUE THREAD

**Issue by Cr1stal** [Shippable/support#3784]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

https://app.shippable.com/gitlab.com/easync/amzn_workers/runs/147/1/console
Shippable needs a valid YML file to build your project.

I had this working. But today is not working.

**Comment by Cr1stal** [comment]
language: node_js

node_js:
  - 6.11.1

branches:
  only:
    - master

env:
  global:
    - REGISTRY_URL=XXX
    - PROJECT_NAME=XXX
    - IMAGE_REPO=XXX

build:
  pre_ci_boot:
    image_name: node
    image_tag: 6.11.0
    pull: true

  ci:
    - shippable_retry npm install -g yarn@0.27.5
    - shippable_retry yarn install --production

  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    - docker build -t $REGISTRY_URL/$PROJECT_NAME/$IMAGE_REPO:$BRANCH.$BUILD_NUMBER .
    - docker push $REGISTRY_URL/$PROJECT_NAME/$IMAGE_REPO:$BRANCH.$BUILD_NUMBER

integrations:
  hub:
    - integrationName: private-repo
      type: "private docker registry"

notifications:
    - integrationName: email
      type: email
      recipients:
        - XXXX
      sendConsoleLogs: true

**Comment by jatindogra** [comment]
Hey, @Cr1stal, we've tried the same scenario with the yml you've specified and it seems to be valid.
It might be a temporary glitch from gitlab as they were upgrading to `GitLab EE 9.5.0.RC6`
Could you please try your scenario once again?

**Comment by Cr1stal** [comment]
I tried several times. And got nothing. I will retry soon.

**Comment by Cr1stal** [comment]
https://docs.gitlab.com/ce/api/v3_to_v4.html

I think they upgraded their api to v4. Does shippable have support this new api? If not, when it will be integrated?

**Comment by jatindogra** [comment]
Hey, @Cr1stal We have recently migrated all users from v3 to v4. We have discovered a bug in the way we are handling the new v4 api to get yml file. This will be fixed shortly.

**Comment by Cr1stal** [comment]
Thank you

**Comment by jatindogra** [comment]
Hi @Cr1stal ,
The issue has been rectified. You should be able to run your build as before.
You can re-open this issue if the build fails again.
