### ISSUE TITLE
master_rSync job fails with cryptic error

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3789]
Hello!

I'm having a hard time figuring out what exactly is making my "master_rSync" task to fail.

Here's the ID of the failed build: `599da722bc415d0700f52916`.

And here's the error:

```
/home/shippable/micro/nod/genExec/managed/rSync/run.sh 1s  
Starting rSync
Reading message
Getting syncRepo and rSync resources
Getting version
Getting subscription integration
Getting account integrations
Getting system codes
Getting list of YML files
encountered an error trying to read file: /build/IN/…_master/syncRepo/bin/cli
Encountered an error processing dir: /build/IN/…_master/syncRepo/bin
{ [Error: ENOENT: no such file or directory, open '/build/IN/…_master/syncRepo/bin/cli']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/build/IN/…_master/syncRepo/bin/cli' }
Failed to process rSync message
```

I'm not sure what exactly is going on. Could you please elaborate on this error? Thank you!

**Comment by a-murphy** [comment]
It looks like your rSync job is running into an error looking for the `shippable.resources.yml` and/or `shippable.jobs.yml` files because it isn't sure if that file is a directory or not.  We'll let you know when we've figured out what we can do about this.

**Comment by slavafomin** [comment]
@a-murphy thanks! I'm looking forward for a solution.

Also, if it helps, I've deleted shippable configuration from the repository at some point and then added it back in another commit. I think it has something to do with this.

**Comment by a-murphy** [comment]
We're still planning to fix this, but it doesn't look like we're going to be able to get to it this week.  In the meantime, you might want to try [migrating your pipeline YML files to another repository](http://docs.shippable.com/deploy/configuration/#migrating-pipeline-resources-from-one-repository-to-another) that only has the `shippable.resources.yml` and `shipable.jobs.yml` files.  The error isn't related to your pipeline YML files; one of the other files in your repository is causing the rSync error.

**Comment by trriplejay** [comment]
We plan to deploy this fix tonight. We will update once it's live. thanks for your patience!

**Comment by trriplejay** [comment]
This fix is live now. Please let us know if you're still experiencing this error.

**Comment by slavafomin** [comment]
Thanks! I hope it's resolved, but I can't check it right now myself.
