### ISSUE TITLE
Unable to upgrade plan

### ISSUE THREAD

**Issue by DaHoopster** [Shippable/support#3790]
### Description of your issue:
I am trying to upgrade the plan in order to add more custom build nodes. I wasn't able to upgrade.

<img width="528" alt="screen shot 2017-08-23 at 11 43 46 am" src="https://user-images.githubusercontent.com/2730866/29632650-77f55722-87f8-11e7-8f55-4b81baa37611.png">

**Comment by DaHoopster** [comment]
Also, I updated our credit card on file earlier. The old card was canceled, which may have caused the account to be past due. Please advise on how to proceed.

**Comment by manishas** [comment]
@DaHoopster As you mentioned, the account was past due and hence all actions were blocked. I have reprocessed the past due amount and it seemed to go through.... can you try upgrading again and let me know if it works as expected?

**Comment by DaHoopster** [comment]
Thanks Manishas! Trying ....
