### ISSUE TITLE
Bitbucket build status not updating if latest build succeeds

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3793]
When multiple builds are triggered for the same commit/PR and the first is canceled because you only allow 1 per branch, then build status in bitbucket doesn't change to succeeded if the last build is done. From what i understand from bitbucket thisis because every build had its own build number, so it doesn't reconize the fact those builds are doing the same.

For example:
https://app.shippable.com/bitbucket/swisnl/evenementenkaart/runs/101/1/console
https://app.shippable.com/bitbucket/swisnl/evenementenkaart/runs/102/1/console

This PR is marked as failed.

**Comment by a-murphy** [comment]
If you click on the failed icon on Bitbucket, it should display a list of statuses, which will show that one build was successful and one was canceled.  We'll look into grouping all runs for a commit into one status and let you know the outcome.

Most commits that run multiple times have manually triggered builds; webhooks won't usually send us the same commit for the same pull request multiple times.  Do you mind if I ask how you are triggering these builds?  It would help us understand why you want the commit statuses grouped together.

**Comment by bbrala** [comment]
Im bit sure why it triggered twice, can you see why in linked builds why?

Op 25 aug. 2017 18:35 schreef "a-murphy" <notifications@github.com>:

**Comment by bbrala** [comment]
I'm not sure*

Op 25 aug. 2017 19:03 schreef "Björn Brala" <bjorn@bjornbrala.com>:

**Comment by bbrala** [comment]
Cheers :)
