### ISSUE TITLE
Run Django Functional Tests with Browserstack and Shippable

### ISSUE THREAD

**Issue by jonperron** [Shippable/support#3794]
### Description of your issue:
Hello,
Our issue is similar to https://github.com/Shippable/support/issues/2885.

We want to run functional tests on Browserstack each time we run a build on Shippable. We tried to implement in python/django was has been done in [node](https://github.com/rageshkrishna/sample-browserstack-local/blob/master/tests/test.js). So far, it keeps failing, the Browserstack's video displaying a `unable to connect to page` error in the remote browser. 

The oddity is that it runs perfectly in the same conditions on a local computer, it only fails with Shippable.

You can find an exemple of failure with build f7b5a39283.

The .yml contains: 
```
build:
  ci:
    - ./BrowserStackLocal --key <browserstackKey>
    - sleep 30
    - ./manage.py runserver 0.0.0.0:8000 --nostatic &
    - sleep 30
```

**Comment by ambarish2012** [comment]
@jonperron I see several projects in your subscription. Please send a link to the failing build here or directly to me @ ambarish@shippable.com.

**Comment by jonperron** [comment]
Thank you for answering @ambarish2012 ! We managed to make it works using the django LiveServerTestCase, so this issue can be safely closed.
