### ISSUE TITLE
running a postgresql docker failure after using a elasticsearch service

### ISSUE THREAD

**Issue by yingqiaomxi** [Shippable/support#3795]
### Description of your issue:
We replaced the Stable image with recent ones for our CI build on Wednesday. Then, we have seen CI build failures. This is one of them. 

In this build, we specify to use an elasticsearch service of the CI build docker machine with the script as:
services:
  - elasticsearch

However, when our script tries to start a postgresql docker container, the build is failed. 

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure: https://app.shippable.com/bitbucket/mxitechnologies/lrp-planmanager/runs/245/1/console
- Scripts called from the yml (optional)
 if [[ -n $(docker ps -aqf "name=postgresdb") ]]; then docker stop postgresdb && docker rm postgresdb; fi
 docker run -d --name postgresdb -p 5432:5432 -e POSTGRES_PASSWORD=password postgres:9.6

**Comment by rageshkrishna** [comment]
If you look at the output of the "Job node info" section for the linked build, you'll see that `docker ps -a` reports that another postgres container named `ipcdb` is already running on the node with port 5432 mapped. I am assuming this is a container that was launched by a previous build of yours that ran on this node.

Your cleanup script, however, only removes containers named `postgresdb`. This means the `ipcdb` container is still running when you try to launch another `postgresdb` container with the same ports. 

If your builds launch containers, you'll need to clean them up yourself so each build starts with a clean slate.

**Comment by yingqiaomxi** [comment]
Right!

Many thanks!
