### ISSUE TITLE
Configuring project with git dependency

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#3797]
We have a git project which has a dependency on another git project. While running build, it fails complaining that the dependent git project not found. How to give shippable access to both the git projects ?

Here's the link - https://app.shippable.com/github/Falkonry/riactor/runs/1/1/console

**Comment by a-murphy** [comment]
Access to private submodules is usually granted by adding the subscription SSH key from Shippable to the second repository.  If there's just one submodule, adding the public key on the subscription settings page to that repository as a deploy key is usually easiest.  If there are multiple submodules, adding the SSH key to an account that has at least read access to all of the submodules will work.  Documentation about using submodules with Shippable is available [here](http://docs.shippable.com/ci/git-submodules/#using-git-submodules).

**Comment by phagunbaya** [comment]
@a-murphy Thanks

**Comment by a-murphy** [comment]
Hope it helped!
