### ISSUE TITLE
Getting tasks splits in runSH in external script

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3798]
We use a central repository for some automation scripts, and to configure a project is only 2 lines of calling a bash script. But i wonder if i can let the called script split itself so it will be a little more readable in your interface.

I would like to see collapsable rows with timings if possible, this would help readablity since eveything is now just one line.

https://app.shippable.com/bitbucket/swisnl/jobs/boipDrupalUpdate/builds/59a35d3bbc415d0700f55a8c/console

```
  Executing Managed Task: runCLI 3m 57s
  Generating task script 0s  
  Writing managed task script 0s  
  Validating script dependencies 0s  
  /home/shippable/micro/nod/genExec/managed/runCLI/run.sh 3m 57s  
  on_success 0s  
  always 0s 
```

**Comment by ambarish2012** [comment]
@bbrala we have implemented this feature. After you upgrade to the latest release, you can define multiple tasks in a single runSh job and split a script section into multiple lines. Please find details on runSh usecases documented [here](http://docs.shippable.com/platform/tutorial/workflow/using-runSh/).
