### ISSUE TITLE
Upgrade my subscription

### ISSUE THREAD

**Issue by Cr1stal** [Shippable/support#3799]
### Description of your issue:
How could I upgrade my subscription?

**Comment by manishas** [comment]
http://docs.shippable.com/platform/visibility/subscription/billing/

Let me know if you need additional help.

**Comment by Cr1stal** [comment]
I made a mistake. I payed for GitHub, but I use gitlab. Could you transfer my payment to gitlab?

**Comment by manishas** [comment]
Pls upgrade the gitlab account and I'll issue you a refund for the GitHub subscription. Let me know if that works.

**Comment by Cr1stal** [comment]
Ok. Thank you.

**Comment by Cr1stal** [comment]
Hello. When you'll issue me a refund for the GitHub subscription ?

**Comment by Cr1stal** [comment]
@manishas

**Comment by manishas** [comment]
Hi, the transaction has to settle before I can issue a refund. I'll give you an update later today.

**Comment by Cr1stal** [comment]
Hello. When you'll issue me a refund for the GitHub subscription ?

@manishas

**Comment by manishas** [comment]
@Cr1stal I have refunded your amount in our payment provider UI. It might take a couple of days for you to see it on your statement.
