### ISSUE TITLE
URGENT: Build status updates in Slack keeps getting redelivered

### ISSUE THREAD

**Issue by asans** [Shippable/support#3800]
I just pushed out a github commit, which triggered a build.  Our build status is connect to slack.  And right now, even though the build has completed, the slack build status messages keeps repeating itself over and over again.  It's not stopping at all.

It does not look like the system is rebuilding in Shippable since the same message shows the same build number.  So it looks like there's an issue with sending and clearing out Slack messages in your system?

**Comment by manishas** [comment]
we're looking into this...

**Comment by trriplejay** [comment]
It looks like slack itself is having some trouble, including duplicate messages being sent according to https://status.slack.com

**Comment by trriplejay** [comment]
looks like the slack issues are resolved now. closing this. @asans let us know if you're still having trouble.
