### ISSUE TITLE
Execute code when build is timed out

### ISSUE THREAD

**Issue by attiam-blueoak** [Shippable/support#3803]
We are having issues with our shippable execution as it is timing out and hence it is being terminated. 

We know that this timeout is occurring because our JUNITs tests are taking a long time to complete. I would like to know if there is any way we could upload our own testing log file to AWS when this timeout has occurred to help us identify the reason why we are having issues. 

We already upload our testing log once a build and testing have completed for our own records, so have all the scripts etc. The problem is, we do not know where in our shippable.yml file can we add this code when the process is terminated due to timeout. 

We have added upload code to 'on_failure' section but this is not being executed when the process is terminated due to timeout.

- Link to the build failure
https://app.shippable.com/github/attiam-blueoak/BlueBilling/runs/397/1/console

I hope you can help.

Regards
Attila

**Comment by trriplejay** [comment]
today there is no way to execute code once a build has timed out, so we've marked this as a feature request.

One alternative might be for you to try out our ssh feature for debugging builds: http://docs.shippable.com/ci/ssh-access/#ssh-access-to-build-machine

This might be difficult if the timeout is intermittent, but if it is consistently timing out, then i'd suggest that you follow that documentation for running a debug build, then you can ssh into the machine as your build is running, and while on the machine you can take whatever steps you think might be helpful (upload files to s3 for example)

let us know if you have any other questions!
