### ISSUE TITLE
Unable to disable a project.

### ISSUE THREAD

**Issue by louib** [Shippable/support#3805]
### Description of your issue:

When trying to disable a project in `https://app.shippable.com/subs/github/ORG/enable`, I get a `No projects found for projectId(s):` error, with some uuid. The project is then still enabled. I tried with 2 different projects, and both were not disabled.

**Comment by deepikasl** [comment]
Hi @louib can you try sync your account once.

**Comment by louib** [comment]
@deepikasl tried that, still not working.

**Comment by deepikasl** [comment]
@louib do you have right permissions for that project? If you are a collaborator of that project, then you wont have access to disable it.
You can check our docs here: http://docs.shippable.com/ci/permissions/

**Comment by louib** [comment]
@deepikasl that is probably the problem then, I'm not admin on those repos. I think the cause of the error could be made explicit when trying to disable a project while not being admin. Thanks for the help!
