### ISSUE TITLE
Caching of docker layers during docker build

### ISSUE THREAD

**Issue by brianmay** [Shippable/support#3806]
Hello,

Just wondering if Shippable supports caching of docker layers when building Docker images? As it looks like to me every image is built from scratch.

I see some existing tickets on similar issues, such as https://github.com/Shippable/support/issues/2684, however, as this ticket rather old now, I am not sure how accurate this is.

Thanks.

**Comment by deepikasl** [comment]
Hi @brianmay, We do not support caching of docker images. The previous issue https://github.com/Shippable/support/issues/2684#issuecomment-224520608 is accurate.

Please let us know if you have any concerns.

**Comment by brianmay** [comment]
Do you still support BYOH? If I go to http://docs.shippable.com/ci_byoh/ which is a link from http://blog.shippable.com/how-to-upgrade-your-ci-cd-subscription I get an error - 403 Forbidden.

**Comment by ambarish2012** [comment]
We do support BYON, more information can be found here - http://docs.shippable.com/platform/tutorial/runtime/custom-nodes/.

Thanks for reporting the broken link - we are fixing it now.

**Comment by deepikasl** [comment]
Closing the issue. Please re-open if you have any concerns.
