### ISSUE TITLE
No projects found for projectId(s)

### ISSUE THREAD

**Issue by ischoonover** [Shippable/support#3809]
When our release automation attempts to send an API request to get the latest build for a project, the API returns "No projects found for projectId(s)" despite the project existing. I see some other support requests about the matter that implicated the API token. I created a token with my own shippable account which is tied to an SCM where I am administrator on all projects and Sync'd, but I am still getting the same error.

Postman extrapolated from app source: http://i.imgur.com/ooKpBqd.png

**Comment by deepikasl** [comment]
Hi @ischoonover, just to confirm, did you provide API token in the header? key: `Authorization` and value should look be your tokken written in `apiToken 57e8c615-b48e-47ff-83ac-2b8888a79111` format.

**Comment by ischoonover** [comment]
Thank you! I had indeed forgotten the 'apiToken' portion of the value on the Authorization header during the Postman test. The new API token works fine now :)
