### ISSUE TITLE
Outdated mongodb distribution

### ISSUE THREAD

**Issue by smarzola** [Shippable/support#381]
Hello.
The mongodb installed in a fresh 12.04 minion is the mongodb-10gen package, the 10gen distributions are old and I think that should be used the [mongodb-org ones](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/).

In my particular case, I have a project that relies on mongodb 2.6 features, so I'm installing the correct version using the `before_install` tags, but the first build after a new minion creation fails because the stop and start of the mongod service are denied by the `policy-rc.d`, so the old service is still running. The following builds run correctly.

Thanks :)

**Comment by Zambonilli** [comment]
To save someone an hour of their life.  Here's how to get mongodb 2.6 running using the before_install block.

before_install:  
  # pull mongodb 2.6.6 binaries & start mongod process
  - echo "============ Installing mongodb ==============="
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list
  - apt-get update -y
  - apt-get -y install --force-yes mongodb-org=2.6.6 mongodb-org-server=2.6.6 mongodb-org-shell=2.6.6 mongodb-org-mongos=2.6.6 mongodb-org-tools=2.6.6
  - mkdir -p /data/db/
  #- service mongod start
  - mongod > /var/log/mongodb/mongodb.log &
  - echo "mongodb-org-server hold" | dpkg --set-selections
  - echo "mongodb-org-shell hold" | dpkg --set-selections

**Comment by manishas** [comment]
Thanks for these tips! I'm going to add these to our documentation so we build up a knowledge base over time.
