### ISSUE TITLE
Not getting TestNg or any other report after build execution.

### ISSUE THREAD

**Issue by DharmeshPatelKiwiQa** [Shippable/support#3810]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

**Following is the pom.xml  and i have added plugin for start execution.**
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>

				<configuration>
					<suiteXmlFiles>
						**<suiteXmlFile>Build\TestSuite.xml</suiteXmlFile>**
									
					</suiteXmlFiles>	

**Following is the  created TestSuite.xml.**
<?xml version="1.0" encoding="UTF-8"?>
<suite name="SuiteName" verbose="10" parallel="false" thread-count="1">
	<parameter name="selenium.host" value="127.0.0.1" />
	<parameter name="selenium.port" value="4444" />

	
	
	 <test name=" Test Case Name">
		<classes>
			<class name="com.Framework.Index.Index">
				<methods>
					<include name="DemoMethod" />
				</methods>
			</class>
		</classes>
	</test>
		
</suite>

I am getting build success but i yet not getting any report after execution. 
And how can i verify my script was executed or not.

Please find attached image.

![image](https://user-images.githubusercontent.com/13761354/30052258-8b7c9338-9242-11e7-9f7e-e9c89d50b68e.png)

**Comment by deepikasl** [comment]
Hi @DharmeshPatelKiwiQa, did you add these test execution commands in `ci` section of your shippable.yml?
If its okay you, can u please share your shippable.yml?

**Comment by DharmeshPatelKiwiQa** [comment]
@deepikasl  Following is my .yml file
language: java
jdk:
- openjdk8

services:
- selenium

build:
ci:
- mvn test

**Comment by ambarish2012** [comment]
@DharmeshPatelKiwiQa you are missing the xvbf setup. Please take a look at this document - http://docs.shippable.com/ci/selenium/#continuous-integration-with-selenium.

**Comment by DharmeshPatelKiwiQa** [comment]
@ambarish2012 Now I have added xvbf but script is yet not executing.

Please find attached. image.

 Shippable is doing execution on linux. So that linux server is console based or GUI based.

![image](https://user-images.githubusercontent.com/13761354/30104988-e583862a-9314-11e7-9039-de8439560782.png)

**Comment by a-murphy** [comment]
It looks like xvbf isn't running when you're trying to start your tests.  Where did you add xvbf?  The command to start xvbf and then run your tests should be in the `build: ci` section of your `shippable.yml`.  If it is in your YML and isn't being run, you may want to check that the indentation in your `shippable.yml` matches the example [here](http://docs.shippable.com/ci/yml-structure/).

**Comment by DharmeshPatelKiwiQa** [comment]
@a-murphy  

**Following is yml file**
language: java
jdk:
- openjdk8

services:
- selenium

build:
ci:
- sudo chmod +X /root/src/github.com/DharmeshPatelKiwiQa/Demo/Resource/chromedriver
- sudo mvn -version
- sudo mvn install
- "export DISPLAY=:99.0"
- xvfb-run --server-args="-ac" mvn test

script execution had already started. but there was an error and error is chrome driver failed to started. As you can see in screenshot. So please my query is, If I will run the script again, then will browser open or not?

**Comment by a-murphy** [comment]
The xvfb-run command uses [xvfb](https://www.x.org/archive/X11R7.6/doc/man/man1/Xvfb.1.xhtml) to create a display that will allow the browser to run.  Which command in the script is resulting in the error?  I wouldn't expect that error to occur in the `xvfb-run` line.  The command should be shown in the console logs above the command output.

And, could you check that the indentation of your `shippable.yml` matches the following (with `ci` indented under `build`)?
```YML
language: java
jdk:
  - openjdk8

services:
  - selenium

build:
  ci:
    - sudo chmod +X /root/src/github.com/DharmeshPatelKiwiQa/Demo/Resource/chromedriver
    - sudo mvn -version
    - sudo mvn install
    - "export DISPLAY=:99.0"
    - xvfb-run --server-args="-ac" mvn test
```

**Comment by tarpanKiwiqa** [comment]
Hi @deepikasl @a-murphy 
How can I see my TestNg report in Shippable after Selenium test completed?

I am developing automation scripts in Java using selenium web driver. And running my build on shippable.
Please help me out of this.

**Comment by a-murphy** [comment]
The comment above appears to be a duplicate of https://github.com/Shippable/support/issues/4041.  Let us know if it is a different issue requiring a separate response.
