### ISSUE TITLE
Flags / SPOG Documentation Not Found / Forbidden

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3811]
I'm trying to access the documentation about SPOG Flags at http://docs.shippable.com/getting-started/single-pane-of-glass-spog, but AWS is returning a 403:Forbidden error for the bucket, access denied.

**Comment by deepikasl** [comment]
hi @ryan-kimber thanks for pointing this out.
You can refer: http://docs.shippable.com/validate/single-pane-of-glass-spog/
More about flags: http://docs.shippable.com/validate/single-pane-of-glass-spog/#filter

**Comment by ryan-kimber** [comment]
Thanks. 

Could you also point me to copies for this resource? I'm getting the same error.

http://docs.shippable.com/platform/workflow/job/runcli

**Comment by a-murphy** [comment]
The runCLI job type has been combined with the runSh job type.  All of the runCLI options are now available in runSh and documented [here](http://docs.shippable.com/platform/workflow/job/runsh/).  You can continue to use any runCLI jobs that you have and the runSh documentation will apply to those as well.
