### ISSUE TITLE
Cancel managed jobs

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3816]
If our settings are wrong and cause the deployment to fail on AWS ECS, Shippable seems to keep trying to deploy for a long time before finally giving up.

This makes it difficult to correct a mistake, as we have to wait more than 30 minutes before it seems like Shippable gives up.

There is also no option to cancel the deploy, so we're stuck waiting/have to queue our subsequent attempts.

I've attached a screenshot to illustrate:

![screen shot 2017-09-05 at 4 19 37 pm](https://user-images.githubusercontent.com/1018189/30081716-52521b50-9256-11e7-89f5-3258fbe77075.png)

**Comment by ryan-kimber** [comment]
![screen shot 2017-09-05 at 4 27 44 pm](https://user-images.githubusercontent.com/1018189/30081997-3ae7699c-9257-11e7-9c85-aacd341bf2ac.png)

Ugh.

**Comment by trriplejay** [comment]
hmm. sorry about that. we'll look into a better way to handle this. in the mean time, the best workaround is to go onto ECS itself, and set the 'desired count' for the deployed service to 0.  This way, the running count will match desired, and the job will consider it a success.

**Comment by manishas** [comment]
Changing title to use this issue to track work required to cancel managed jobs.

**Comment by trriplejay** [comment]
@ryan-kimber this feature has been implemented. "managed" jobs can now be cancelled.
