### ISSUE TITLE
In shippable.resources.yml's dockerOptions I should be able to leave memory out and NOT have a default hard memory limit included in the ECS task definition

### ISSUE THREAD

**Issue by npahucki** [Shippable/support#3817]
The memory parameter is supposed to be optional. In ECS, this corresponds to the HARD memory limit, at which ECS kills the docker container. For development, we want to use only the SOFT limit (the `memoryReservation` param in dockerOptions). This allows us to cram more development images on a single machine as these may occasionally peak above the SOFT limit without ECS killing the container. However, leaving the `memory` param of dockerOptions out seems to then specify a default of 400MB, which is NOT what we want, we want no default at all specified (which is legal and functional in an ECS taskdef.).

Please consider adding this feature/correcting this bug.

**Comment by trriplejay** [comment]
thanks for pointing this out.  Unfortunately it doesn't look like we have a way to set memoryReservation without the hard limit `memory` being set as well.  I'll file this as a bug.

**Comment by trriplejay** [comment]
This has been deployed.  If you supply a value for `memoryReservation`, then the typical default value for `memory` will not be set.
