### ISSUE TITLE
Builds hang and timeout intermittently

### ISSUE THREAD

**Issue by gcoombe** [Shippable/support#3819]
### Description of your issue:

We are quite often seeing builds hang and timeout.  When manually rebuilding on the exact same git commit the build usually succeeds. As an example

- https://app.shippable.com/github/gcoombe/fetch-home/runs/1695/1/console timed out
- https://app.shippable.com/github/gcoombe/fetch-home/runs/1697/1/console succeeded despite seemingly being on the same commit with the same configuration.

The timed out builds seem to be hang on our testing step.  It seems like all steps have run but it seems like shippable thinks the test:ci step hasn't completed.

**Comment by a-murphy** [comment]
We haven't found any Shippable-related potential causes.  However, there are reports of similar errors occurring with older versions of [gulp-mocha](https://github.com/sindresorhus/gulp-mocha/issues) when connections are left open or `setTimeout` is used.  You may want to try either updating to gulp-mocha 4.0.0 or check your tests for possible unclosed connections.

**Comment by gcoombe** [comment]
Thanks for the advice! I'll close this and try out your suggestions.
