### ISSUE TITLE
Build failing, even builds that before ran successfully fail now because of an import error that does not exist in development environment

### ISSUE THREAD

**Issue by cancerballs** [Shippable/support#3820]
Build failing, even builds that before ran successfully fail now because of an import error that does not exist in development environment

https://app.shippable.com/bitbucket/sanoste/sassy/runs/3351/1/console

Searching for Flask-User<0.7
Reading https://pypi.python.org/simple/Flask-User/
Downloading https://pypi.python.org/packages/64/67/1310c6062e114fb7619602d14e76fbcea5f338d6214c2cc2011f492f4e9e/Flask-User-0.6.17.tar.gz#md5=9cf612a54cd6bf6e9827a2d4bc0b77dd
Best match: Flask-User 0.6.17
Processing Flask-User-0.6.17.tar.gz
Writing /tmp/easy_install-sw_w9179/Flask-User-0.6.17/setup.cfg
Running Flask-User-0.6.17/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sw_w9179/Flask-User-0.6.17/egg-dist-tmp-phgn_6x2
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 158, in save_modules
    yield saved
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 199, in setup_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python3.5/dist-packages/setuptools/sandbox.py", line 49, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-sw_w9179/Flask-User-0.6.17/setup.py", line 5, in <module>
    # the source distribution for more details.
  File "/tmp/easy_install-sw_w9179/Flask-User-0.6.17/flask_user/__init__.py", line 7, in <module>
ImportError: No module named 'passlib'

**Comment by a-murphy** [comment]
It sounds like you already have `passlib` installed locally.  The best solution is probably to install it in your build as well.  Could you try adding it to your list of dependencies before the dependency that is failing or installing on its own before the rest of the dependencies?

**Comment by cancerballs** [comment]
Flask-User package has a dependency on passlib and when installing Flask-user locally passlib is also installed correctly. This used to work but now when I trigger older successful builds they fail because Flask-User can't install its dependency passlib.

For some reason the dependency is not installed in shippable.

**Comment by a-murphy** [comment]
It looks like the newest version of Flask-User was [released recently](https://pypi.python.org/pypi/Flask-User).  Perhaps that's related.  I don't see any attempt to install passlib in your logs, just an error when it wasn't found, so installing passlib before Flask-User will most likely avoid the error.  You could also try specifying a previous version of Flask-User if that was working for you.

**Comment by matthijskooijman** [comment]
This is caused by https://github.com/lingthio/Flask-User/issues/183 and is fixed in the 0.6.19 release (though I can't quite find that release anywhere). Looking through [the commit that broke this](https://github.com/lingthio/Flask-User/commit/c88b3765682b88fe3e23eabb763c1ad7e6898c3c), It seems 0.6.14 is the first broken version.

**Comment by cancerballs** [comment]
Yes, this has nothing to do with Shippable and the problem was caused by a new version of Flask-User. Thanks for the help!
