### ISSUE TITLE
Builds not getting triggered on git commits

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#3822]
Since today afternoon we are facing this issue. Builds are not getting triggered automatically on git commits.

**Comment by trriplejay** [comment]
looks like github is currently experiencing delays with webhook deliveries:
https://status.github.com/

**Comment by phagunbaya** [comment]
Thanks ! Just noticed.

**Comment by trriplejay** [comment]
seems to be resolved based on github's latest status. closing. let us know if you're still having trouble.
