### ISSUE TITLE
post_ci change request

### ISSUE THREAD

**Issue by StuporHero** [Shippable/support#3823]
I am using docker-compose to create my build environment within a ci job. I need to cleanup the docker-compose project after my build runs whether it succeeds or fails. Because the post_ci section does not run if the build fails, I have to duplicate my cleanup code in an on_failure section. Please either change post_ci so it runs on every build (which would make the most sense since it is currently no different from on_success) or add a new lifecycle step that will run after the ci step regardless of whether it succeeds.

**Comment by deepikasl** [comment]
@StuporHero This is already in our backlog. We will update you once the feature is on production.

**Comment by manishas** [comment]
This is about adding an on_cancel or always section to the yml which will execute regardless of the build result.

This request is being tracked in https://github.com/Shippable/support/issues/3017 so closing this issue in favor of that. Please track 3017 for a resolution.
