### ISSUE TITLE
rSync failed with   - Failed to getSHAByAccountIntegrationId for accountIntegrationId

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#3826]
our rSync job is failing with:

  - Failed to getSHAByAccountIntegrationId for accountIntegrationId

It looks like that all dependencies were processed without errors.

**Comment by a-murphy** [comment]
This is most often either because a subscription integration has been specified for a gitRepo resource and does not have access to that repository or a branch has been specified for a new gitRepo that doesn't exist.  I would suggest looking for any resources with status "inconsistent" to find out which resource ran into the problem.

**Comment by depohmel** [comment]
https://app.shippable.com/github/kastenhq/jobs/k10_master_rSync/builds/59b1a13c811f750700fb2e6e/console

I don't see any inconsistent error

**Comment by depohmel** [comment]
and it's master branch, so it exists

**Comment by ambarish2012** [comment]
@depohmel - from the rSync logs - 
`Getting SHA data for k10_cd_test_repo`

This resource is inconsistent - https://app.shippable.com/subs/github/kastenhq/resources/k10_cd_test_repo/versions.

**Comment by a-murphy** [comment]
Sorry, if you go back to the subscription dashboard, then you can search for inconsistent resources in the resources panel (click the eye at the top and then "show resources" if you don't have a resources panel).  It looks like there is one inconsistent resource.  I'm not sure if you want me to paste its name in a public support issue.  I would suggest checking the `branch` of that resource in your `shippable.resources.yml` file to make sure it exists.

**Comment by depohmel** [comment]
Found it. Please close the bug.
Our cd_test branch is a test branch which got delete time to time

**Comment by a-murphy** [comment]
Great!  Thank you for letting us know you found it.
