### ISSUE TITLE
Newly added Github repository is not listed in configuration

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3827]
Hello!

I've added a new repository to my GitHub account half an hour ago, but it's not listed on Shippable configuration screens. I'm trying to add new sync repo, but can't select it in the list. This is really frustrating, because I need to reconfigure my pipelines and to deploy the production application fast.

When I click on `Synchronize SCMs` button it shows spinner indefinitely and repository is not appearing anywhere.

Please advise! Thanks.

**Comment by slavafomin** [comment]
It finally appeared, but it took a very long time. It would be great to optimize this process.

**Comment by cyberbliss** [comment]
Same for me... clicking the Sync button to manually sync our Github repos doesn't work anymore. Just providing an auto-sync that runs every 4 hours is not sufficient

**Comment by manishas** [comment]
@slavafomin @cyberbliss have you seen this recently? We haven't seen these failures in more than 3 weeks but want to confirm before closing.

**Comment by slavafomin** [comment]
I've never tried to add any more repositories lately. But the last one I was adding was added correctly.

**Comment by manishas** [comment]
Thanks for clarifying!
