### ISSUE TITLE
desiredCount vs replicas

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3828]
Hello!

Could you please elaborate on the difference between the `dockerOptions.service.desiredCount` and the `replicas.version.count` options? I'm looking from the context of ECS deployment. Are these the different means to control the same setting or do they serve different purposes?

Thanks.

**Comment by trriplejay** [comment]
they control the same setting. replicas can be used across all orchestration platforms that Shippable supports, while service.desiredCount will only work for ECS, but if you are using ECS there is no difference.

**Comment by slavafomin** [comment]
Actually it seems that `dockerOptions.service.desiredCount` is ignored. I've set this property to `2` in order to launch two instances of the service, but only one instance was launched. I've removed this option and used `replicas.version.count` instead, which finally worked.

**Comment by trriplejay** [comment]
ah yes, ok. usually when Shippable provides native support for a field, we ignore the provider-specific duplicate field in the dockerOptions. glad you got it working with replicas.  Let us know if you have any other questions.

**Comment by slavafomin** [comment]
I would suggest to update the documentation to make this point clear.
