### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by Cr1stal** [Shippable/support#3829]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

Hello,
I enabled a new repo under my gitlab subscription. And I clicked build button on new repo. Then I got this: 
"postRun for :projectId 5977ad8aeb488607006c1cc5 returned error: POST /runs? returned 504".

Help me, plz.

**Comment by a-murphy** [comment]
It looks like this is most likely resulting from an error finding the GitLab accounts for the author and committer.  Could you check if GitLab is correctly identifying your commits as yours?

We'll fix this and let you know when it's deployed.  For now, I would suggest making sure the author and committer of the commit you are trying to build are correctly identified by GitLab, which should avoid the error.

**Comment by a-murphy** [comment]
This was fixed last week.  Please let us know if you see this error again.
