### ISSUE TITLE
Show outdated jobs graphically on SPOG

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3830]
Hello!

I have a `deploy` job, which I use to deploy my application to production server. All `IN`s of it is switched off, so I can manually decide when to release the app. However, it's always displayed green on SPOG, even if input resources where updated.

It would be great to distinguish this graphically, so it will be easy to see when job is outdated.

**Comment by manishas** [comment]
This has been fixed. You will see a grey border around stale jobs, i.e. job which have not been run though newer versions of inputs are available.

![image](https://user-images.githubusercontent.com/2983749/39203688-5c132846-47aa-11e8-9a29-cdff1e037299.png)
