### ISSUE TITLE
Drop previous genexec images on re-initialize

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3833]
Our build nodes just where stopped due to running out of disk space (see #3832). Among others we saw that all previous genexec images where still present, filling up the disk.

Thus I'd like to request that the Shippable node init script drops the previous image(s) on node re-initialize.

**Comment by ambarish2012** [comment]
@mbrodala thanks for the excellent suggestion, we will add this feature request to our backlog.

**Comment by mbrodala** [comment]
I've noticed that old build images are also not cleaned up. In our case we use the `latest` tag so it would be nice if Shippable could clean up old images if a newer image was pulled for `latest`.

**Comment by mbrodala** [comment]
We won't be using Shippable anymore.

But thanks so far!
