### ISSUE TITLE
Can't access to subscriptions list

### ISSUE THREAD

**Issue by madjid-asa-optim** [Shippable/support#3834]
### Description of your issue:
I have problem to access to subscription list of my company, all member of my team have access except me. 
I loggin myself with github, and I accept all authorizations, but I can't see any project and Shippable doesn't detect my ssh key.

**Comment by deepikasl** [comment]
Hi @madjid-asa-optim can you try sync your account?

**Comment by madjid-asa-optim** [comment]
Hi @deepikasl thank you for your response !

I had try, but it's the same case, I will try again in few hour and I hope it's will be ok.

If you have another tips, please let me know please.
