### ISSUE TITLE
How to add file to image build that isn't in repository

### ISSUE THREAD

**Issue by glozhkovoy** [Shippable/support#3835]
Hi, I want to use data from the file (config.json) that I need to pull from amazon bucket. Since that file contains some passwords I cannot add it to repository
Can you give me some examples how to pull the file and build an image using data from file that was pulled recently.

Thanks!

```
  ci:
    - if [ "$BRANCH" == "dev" ]; then CI_CONFIG=stage; fi
    - shippable_retry npm install
    - shippable_retry npm run build:$CI_CONFIG
    - if [ "$BRANCH" == "master" ]; then PUSH_IMAGE_NAME="myName"; else PUSH_IMAGE_NAME="myName"; fi
    - docker build --build-arg DK_CONFIG=$CI_CONFIG --build-arg CI_BUILD_NUMBER=$BUILD_NUMBER -t $PUSH_IMAGE_NAME .
  #post_ci:
    - docker push $PUSH_IMAGE_NAME
    - echo "versionName=latest" >> $JOB_STATE/shipdemo-img-$BRANCH.env
    - echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/shipdemo-img-$BRANCH.env

```

That's my CI step. What I need to add here?

**Comment by a-murphy** [comment]
If you're pushing your image to ECR and already have an ECR integration in your `integrations` section, and your ECR image and S3 bucket are in the same region, you will have been authenticated with AWS using those credentials.  If you don't have an ECR integration, you can either add a key-value pair integration or encrypt your AWS key and secret with [secure environment variables](http://docs.shippable.com/ci/env-vars/#secure-variables).

Then you can copy your config.json file from S3 to the location where your Dockerfile expects it.  For example, adding ` - aws s3 cp s3://yourBucket/config.json config.json` will copy `config.json` from the root of the bucket to the current directory.  The AWS documentation for `cp` is available [here](http://docs.aws.amazon.com/cli/latest/reference/s3/cp.html) with examples for more complicated cases.

**Comment by glozhkovoy** [comment]
@a-murphy I have an ECR integration and they are in the same region
where exactly I need to put this command?  This's aws command so I need to do in script section like this?
```
script:
       - aws s3 cp s3://yourBucket/config.json config.json
```
Do I need to install awscli?

**Comment by a-murphy** [comment]
If you're using a Shippable image, `awscli` should already be installed.  The `aws s3` command should be before the `docker build` command in your `ci` section.

Something like this, but with your bucket name for `yourBucket` and the correct path (if your `config.json` is in a subdirectory in the bucket or you want to copy it somewhere else):
```YML
  ci:
    - if [ "$BRANCH" == "dev" ]; then CI_CONFIG=stage; fi
    - shippable_retry npm install
    - shippable_retry npm run build:$CI_CONFIG
    - if [ "$BRANCH" == "master" ]; then PUSH_IMAGE_NAME="myName"; else PUSH_IMAGE_NAME="myName"; fi
    - aws s3 cp s3://yourBucket/config.json config.json
    - docker build --build-arg DK_CONFIG=$CI_CONFIG --build-arg CI_BUILD_NUMBER=$BUILD_NUMBER -t $PUSH_IMAGE_NAME .
  #post_ci:
    - docker push $PUSH_IMAGE_NAME
    - echo "versionName=latest" >> $JOB_STATE/shipdemo-img-$BRANCH.env
    - echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/shipdemo-img-$BRANCH.env
```

**Comment by glozhkovoy** [comment]
It works for me. Thank you!

**Comment by a-murphy** [comment]
Great!  I'll close this issue as resolved.
