### ISSUE TITLE
Java samples in docs are missing

### ISSUE THREAD

**Issue by adam-kosseck** [Shippable/support#3836]
Java samples listed in the docs here: http://docsv2.readthedocs.io/en/latest/samples/java.html are missing (404)

**Comment by Varsha-Arun** [comment]
hi @adam-kosseck 

sorry for inconvenience. Updated docs for java is [here](http://docs.shippable.com/platform/runtime/language/java/#java).

**Comment by ambarish2012** [comment]
@adam-kosseck http://docs.shippable.com is our docs site. http://docsv2.readthedocs.io/en/latest/samples/java.html is deprecated and the older version of our docs.
