### ISSUE TITLE
My gitlab subscription disapeared

### ISSUE THREAD

**Issue by Cr1stal** [Shippable/support#3842]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

Hello. My gitlab subscription disapeared. How can I reestablish it again?

**Comment by a-murphy** [comment]
It looks like the access token in your GitLab integration has most likely expired or been revoked.  Could you check that the token in your GitLab integration is still valid in your GitLab account settings and then click sync again?  If the token is no longer valid, you can create a new access token and update the account integration.

**Comment by vrajroham** [comment]
@a-murphy @Cr1stal 
Due to resent bug in **gitlab**, they removed access tokens of some of the users and notified them via **email**.
