### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by johnsonwj** [Shippable/support#3845]
Hello,

After using the documentation to set up a pipeline from scratch, there are some spots where I think the documentation is misleading or unclear.

Overall I think the documentation is not very helpful for a developer who very rarely has to work with configuring pipelines---in fact, only when creating a brand new project. Even then, we have scripts to generate shippable configuration files for most cases, so starting from only having seen project configurations before and having a general idea of what a job or a resource is, it took a lot of digging around tutorials and comparing to the doc pages for specific job/resource types to set up even a very simple project.

## Environment Variables

The documentation on resource pages has a line like this:

> &lt;NAME&gt; is the the friendly name of the resource.

followed by a listing of environment variables like

> &lt;NAME&gt;_ID

However, for a resource named e.g. `my-shippable-resource`, the variables actually look like `MYSHIPPABLERESOURCE_ID`.

The wording in the documentation does not indicate at all how the resource name is reformatted to produce the environment variable name. I think this is not obvious and should be made explicit wherever environment variables are documented.

## `state` Resource Usage

The [documentation on the `state` resource](http://docs.shippable.com/platform/workflow/resource/state/) leaves out several important points that are crucial for using this resource correctly. These are shown in [the relevant tutorial page](http://docs.shippable.com/platform/tutorial/workflow/sharing-data-between-jobs/), but I think they should be spelled out explicitly on the resource documentation so that it is easy to locate:

* In order to make files available in the resource, the resource must be an OUT on that job, and the files must be copied to the `/build/OUT/state-resource-name/state` directory.

The requirement that files go under the `state` directory is not obvious at all, and in fact I thought that was just a part of the example in the tutorial, rather than part of the resource itself.

* The files can be retrieved by making the resource an IN on another job, where they will appear in `/build/IN/state-resource-name/state`

This is easy enough to guess from the `OUT` usage, but it always helps to be over-specific in documentation :)

## `cliConfig` Resource Usage

I think it would help a lot to clarify here that `integration` should be the name of an integration that appears in `https://app.shippable.com/subs/github/subscription-name/integrations`. Having never worked directly with those integrations before, it was not clear to me what "name of the subscription integration" was referring to.

**Comment by ambarish2012** [comment]
Thanks for the excellent and detailed feedback @johnsonwj. We will incorporate your excellent suggestions.

**Comment by manishas** [comment]
@johnsonwj this feedback has been addressed.... feel free to comment on the new docs :)
