### ISSUE TITLE
Shippable UI Broken

### ISSUE THREAD

**Issue by adam-kosseck** [Shippable/support#3847]
### Description of your issue:
I logged into Shippable UI today, and all of my subscriptions have vanished.
The button to view subscriptions is also gone.

- When I click "Enable a project" it tells me to pick a subscription from the list, but nothing is shown.
- When I try to search for subscriptions it tells me "No projects found for projectId(s):"
- When I click "Integrations" it tells me "No subscriptions found for subscriptionId(s):"
- When I click "Add Account Integration", it shows a 404 error for this page: https://app.shippable.com/accounts//integrations/new

**Comment by a-murphy** [comment]
If you are using Bitbucket, it may be a result of the recent Bitbucket errors.  Could you try clicking "Profile" in the left sidebar and then the "sync" button.  If that doesn't work, could you include either the name of the account you logged in with or the account ID at the bottom of the profile page?

**Comment by adam-kosseck** [comment]
Thanks,

That seems to have resolved the issue.

Regards,

*Adam Kosseck*
solutions engineer at www.brightsparklabs.com
p: +61 411 338 683 / e: adam.kosseck@brightsparklabs.com
