### ISSUE TITLE
kubectl version when using cliConfig

### ISSUE THREAD

**Issue by nmarshall-cst** [Shippable/support#3849]
We are using some newer features in Kubernetes and when we try to run our continuous deployment through Shippable our deploys are failing. The Shippable deploy job shows as successful, but the new pods error in our cluster. Looking over the logs it seems that an older version of kubectl is being used during deployments. In the log below you will see that the client that Shippable uses is v1.5.1 where our servers are configured to use v1.6.7. Is the kubectl version configurable?

` Executing Managed Task: runCLI 14s
  Generating task script 0s  
Successfully generated managed task script
  Writing managed task script 0s  
Successfully saved managed task script: /build/stepExec.sh
  Validating script dependencies 0s  
the path is: /build/stepExec.sh
Successfully validated script dependencies
  /home/shippable/micro/nod/genExec/managed/runCLI/run.sh 14s  
Identity added: /tmp/00_sub (/tmp/00_sub)
Configured kubectl credentials for dev-kube-cluster. Using version:
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.7", GitCommit:"095", GitTreeState:"clean", BuildDate:"2017-07-05T16:40:42Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
deployment "app-deployment" configured
configmap "app-properties" configured
  on_success 0s  
  always`

**Comment by trriplejay** [comment]
unfortunately there is no way to configure this. I'll open a ticket to get this updated to the latest version.

**Comment by trriplejay** [comment]
actually, there is nothing stopping you from updating kubectl at the top of your runCLI script.  I realize this would be annoying to have to update for every single deployment, but it would at least get you around this problem if it's blocking you until we can get the latest version officially released.

**Comment by nmarshall-cst** [comment]
Thanks @trriplejay. I was trying to sidestep having to update the client in each deployment. :) I will keep an eye out on this feature request and apply the workaround.

**Comment by trriplejay** [comment]
Hi @nmarshall-cst. We released an update. kubectl is now at version 1.8 in runSh/runCLI jobs.  Let me know if you run into any additional problems.

**Comment by nmarshall-cst** [comment]
Great! Thanks @trriplejay
