### ISSUE TITLE
No subscription menu

### ISSUE THREAD

**Issue by tela** [Shippable/support#3850]
### Description of your issue:
I just signed-up and connected to the private repo for my Github organization. Huzzah! The first onboarding step in your instructions says "You can enable your first project by navigating to a subscription using the subscription drop-down on the side panel." There is no subscription option on the side panel. See attached screenshot.
<img width="1155" alt="screen shot 2017-09-22 at 2 14 42 pm" src="https://user-images.githubusercontent.com/325755/30764626-af097e72-9fa0-11e7-92fc-8891bbadc579.png">

**Comment by manishas** [comment]
@tela can you click on Profile and then click on Sync?

Please let me know if that works.

**Comment by tela** [comment]
Thanks for the speedy reply, @manishas - I gave that a try before submitting the issue, but it didn't result in any change to available options. I also logged-out and re-authenticated...without effect.

**Comment by a-murphy** [comment]
Does your organization have third-party access restrictions on GitHub?  You can check this by going to the organization settings page and clicking on "third-party access" on the left.

If you have this enabled and it doesn't show that access has been granted to Shippable, you can go to your GitHub settings and "request" or "grant" access to the subscription as described [here](https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/).

**Comment by tela** [comment]
Thanks, @a-murphy I think we're on the right path. I do show prod-shippable as an authorized oauth app under my personal profile. However, it's not under my organization 's authorized oauth apps. I didn't want to revoke access to prod-shippable from my personal profile because it seems like bad things can happen which can't be undone.

I removed restrictions to third-party oauth apps from my organization, and tried logging-in to shippable again. No luck. Do you have any suggested next steps?

**Comment by a-murphy** [comment]
Could you click profile on the left and then click the sync button again?  This time the sync should be able to see the projects in your organization. If they still don't appear when the spinner stops, try refreshing the page as well.

**Comment by tela** [comment]
Worked a charm. Thanks!
