### ISSUE TITLE
AWS ECR not authenticating for custom image 

### ISSUE THREAD

**Issue by clippermadness** [Shippable/support#3851]
I have followed the instructions in the docs to create an integration with AWS ECR, but I'm getting an error in the build that docker is not logged in when it issues the pull request.

http://docs.shippable.com/platform/integration/aws-ecr/
http://docs.shippable.com/ci/custom-docker-image/#pull-image

https://app.shippable.com/bitbucket/thetalake/frameextractor/runs/18/1/console

This is the error is see:
Pulling repository 203834682469.dkr.ecr.us-west-2.amazonaws.com/thetalake/python-3.5-opencv-3.2
unauthorized: authentication required

Running the same commands at the command line with the AWS credentials I created for shippable appears to work.

**Comment by a-murphy** [comment]
It doesn't look like you've specified a region for your ECR integration; the default is `us-east-1`.  Could you try adding `region: us-west-2` to the integration in your `shippable.yml`?

The integrations section should be formatted like this:
```YML
integrations:
  hub:
    - integrationName: ecr-integration
      type: ecr
      region: us-west-2
      type: ecr
```

Thank you for including the links to the documentation pages you used.  Now we know which ones should probably mention the `region` option.

**Comment by clippermadness** [comment]
That was it. Thanks!

While you're updating the docs, could you also list the requirements that are necessary to be installed in the container.

My build now fails because apparently the awscli is required to be installed in the container. It'd be nice to know why that's needed and what other dependencies there are.

**Comment by a-murphy** [comment]
The `awscli` is only required if you plan to use the awscli in your `ci`, `post_ci`, `on_success`, or `on_failure`.  By default. we will try set up the ECR authentication in the container, but you can disable this by adding [`agent_only: true`](http://docs.shippable.com/ci/push-amazon-ecr/#using-a-custom-image-for-ci) to the integration in your `shippable.yml` file.

I've opened an internal issue about the documentation.

**Comment by clippermadness** [comment]
Excellent thanks for that.

**Comment by clippermadness** [comment]
I can confirm that the `agent_only: true` flag works. My docker image no longer needs `awscli` installed on it.
