### ISSUE TITLE
WebHook fails with 404 for tag-triggered build

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3852]
Hi guys,

I have project that builds perfectly from tags, but I've got another where the webhook from GitHub is failing every time I commit a tag (it gets a 404). I tried resetting the project to re-create the WebHook, but it's still doing the same thing.

Here are some images to illustrate the config and issue:

![screen shot 2017-09-24 at 12 16 11 pm](https://user-images.githubusercontent.com/1018189/30784409-9f518f5a-a122-11e7-8a58-c3e56a61adfd.png)
![screen shot 2017-09-24 at 12 16 36 pm](https://user-images.githubusercontent.com/1018189/30784412-a299468a-a122-11e7-948b-e10d6ced23b3.png)
![screen shot 2017-09-24 at 12 17 02 pm](https://user-images.githubusercontent.com/1018189/30784413-a5b1a704-a122-11e7-8fa4-eebc087d14fa.png)
![screen shot 2017-09-24 at 12 17 24 pm](https://user-images.githubusercontent.com/1018189/30784415-a8d232d2-a122-11e7-8d5a-de61c5cf3529.png)

**Comment by a-murphy** [comment]
I'm not sure how the "create" event got selected for your webhook.  We don't usually enable that one, so I'll look into how that might have happened.

What is the "X-GitHub-Event" header in the request for the failed webhook?  The error message implies that it's one that we don't support.  I would expect a `push` event for a tag webhook.

**Comment by a-murphy** [comment]
Did you edit the webhook to add the create event?  I haven't found another likely cause, and adding the create event to a webhook does result in a similar error.  There should also be a push webhook at the same time.  Does that one show any errors?

**Comment by ryan-kimber** [comment]
I did add it, but it turned on in our other project that builds on tags.

Before I turned it on, this project (nginx-for-AWS) was not building when I
pushed tags.

**Comment by ryan-kimber** [comment]
Just a correction to my language: it is turned on in our other project that
builds form tags. It’s nit causing an issue there, and I believe I had to
turn it on to get it to pick up the tag pushes:

**Comment by a-murphy** [comment]
Adding the create event shouldn't cause any problems other than the failed webhooks on GitHub.  GitHub also sends a push webhook, which we will process.

Looking at the other builds in nginx-for-AWS and the screenshot you included of the tags above, it looks like your tags are excluded by the `branches: only` in your `shippable.yml`.  Perhaps it's a typo in the third item in your `branches: only` (`_` instead of `-`)?  If `branches: only` is used, both tags and branches need to match the options in the list.

**Comment by ryan-kimber** [comment]
You are 100% right. Typo on our branches: only. Thanks for the help and sorry for the trouble. The rest of my day is going to be much more productive now!

**Comment by a-murphy** [comment]
I'm glad it's working.  I'll close this as resolved.
