### ISSUE TITLE
S3 region for build cache

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3853]
Since I've noticed that our builds are slowed down whenever an upload is performed (e.g. build cache upload) I'd like to know what region Shippable uses for its S3 storage.

Our custom build nodes are located in Dallas and have an uplink of 10 Gbps so this shouldn't be the bottleneck.

**Comment by rageshkrishna** [comment]
It's in `us-east-1`.

**Comment by mbrodala** [comment]
Hm, so the distance is not that huge. Any other idea what else could slow down uploads here?
