### ISSUE TITLE
Yarn: You don't appear to have an internet connection

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3854]
Hello!

Our builds are failing with the following error message during `yarn global add @angular/cli && yarn install`:

```
yarn global v1.0.2
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/postcss-merge-longhand/-/postcss-merge-longhand-2.0.2.tgz: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/usr/local/share/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
The command '/bin/sh -c yarn global add @angular/cli &&   yarn install' returned a non-zero code: 1
```

It's installing totally fine w/o a cache on my local machine.

What could be the problem? Thanks!

**Comment by a-murphy** [comment]
Have you seen this error frequently?  It looks like it's most likely an intermittent network problem.  You can try using `shippable_retry` on the command in your `shippable.yml` to retry the command when it fails.  Documentation on `shippable_rety` is available [here](http://docs.shippable.com/ci/retry-command/).

**Comment by slavafomin** [comment]
@a-murphy I've just tried to rebuild, but got the same error.

**Comment by slavafomin** [comment]
@a-murphy Strangely, this time it continued the build process even after reporting this error. I'm going to investigate further and will report here.

**Comment by slavafomin** [comment]
@a-murphy It's built correctly the last time, looks like a temporary issue. I'm closing this for now. Thank you for your time.
