### ISSUE TITLE
Hub login failed: ECR docker login failed Flag --email has been deprecated, will be removed in 1.14

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#3855]
Hello!

The following error is recently appeared during our server build process:

```
ecr_login 19s
  echo 'Hub login failed' 0s  
Hub login failed
  echo -e 'ECR docker login failed\n\n'Flag --email has been deprecated, will be removed in 1.14. 0s  
Error response from daemon: Login: 404 page not found
 (Code: 404; Headers: map[Content-Type:[text/plain; charset=utf-8] Date:[Mon, 25 Sep 2017 20:49:39 GMT] Docker-Distribution-Api-Version:[registry/2.0] X-Content-Type-Options:[nosniff] Content-Length:[19]])
ECR docker login failed
Flag --email has been deprecated, will be removed in 1.14.
/tmp/mexec/tmp-script.sh: line 74: Error: command not found
/tmp/mexec/tmp-script.sh: line 75: Code:: command not found
/tmp/mexec/tmp-script.sh: line 75: Headers:: command not found
/tmp/mexec/tmp-script.sh: line 75: Date:[Mon,: command not found
```

We are using ECR integration to push built docker containers.

What could be the problem? Thanks!

**Comment by slavafomin** [comment]
It looks like this issue was also related to networking problems.

**Comment by a-murphy** [comment]
As far as I can tell, a 404 was returned when attempting `docker login`.  I haven't found any potential causes, but I would suggest just trying again.  This is definitely not a common error and could potentially be related to the Docker Registry (ECR) or the DNS server.

**Comment by slavafomin** [comment]
@a-murphy I've tried again and it built successfully, however, it looks like networking is unstable. I would suggest to investigate this.
