### ISSUE TITLE
execute runSh job via http request?

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3857]
is there a way to "trigger" a runSh job via http, ideally also providing some level of inputs?

I have a runSh job that needs to be fired off upon request from an outside resource.

I looked at the API `POST /resources/{resourceId}/triggerNewBuildRequest` but there dont seem to be inputs available (and the docu doesnt really explain what `resourceId` is in this context), I've looked at `shippable.triggers.yml` but those require commits to the `rSync` repo to trigger, and the only other mechanism I can find is `time` which also isn't what I'm looking for.

In the UI, I can press the play button and execute a runSh job two different ways.  one allows `ENV` var inputs, the other doesnt take inputs.    I shouldn't have to reverse engineer the UI to do this, though... :)

**Comment by a-murphy** [comment]
The `resourceId` can be found on the job dashboard (the page that shows all of the times that job has run accessible by clicking the job name on the subscription dashboard).  It's  "Job Id" at the bottom of the page.

When calling the `POST /resources/{resourceId}/triggerNewBuildRequest` you can send an optional `globalEnv` object in the request body with additional environment variables for runSh jobs.  The keys in `globalEnv` are the variable names and the values are the values.

**Comment by keen99** [comment]
thanks - so no way to trigger by resource name?   that makes it a lot of fun for debugging problems I bet....

**Comment by a-murphy** [comment]
No, there's no way to trigger by name at this time.  You can, however, find resources by name using `GET /resources` (documented [here](http://docs.shippable.com/platform/tutorial/api/api-overview/#!/Resources/get_resources)) and then use the `id` in that resource object.

**Comment by keen99** [comment]
thanks, got it working.   might be worth adding something to the api docs about a) how to find the resourceid and b) the inputs available to `triggerNewBuildRequest`

**Comment by keen99** [comment]
on another question about this:

is there a friendly internal way to call this from inside another job? (inside a runCI for example that needs to conditionally decide to trigger a runSh - and where passing ENV vars is a lot saner than the OUT/IN options, particularly since the OUT option triggers aren't conditionally optional)

**Comment by keen99** [comment]
seems like having to do curl testing logic and passing in an API token secret is pretty heavy. :)

**Comment by a-murphy** [comment]
There isn't currently a way to trigger a job with additional environment variables other than through the API.  It sounds like in your case it may make the most sense to instead update a resource as an `OUT` of the first job and an `IN` to the second.  Then the resource won't be updated unless it has changed and will trigger the second job when it does change.  You can also add additional information to the new version of the resource that will be available in the next job.

[This documentation](http://docs.shippable.com/platform/tutorial/workflow/writing-keyvalues-to-output-resource/) may be helpful if you decide to update a resource from your runSh job.

**Comment by keen99** [comment]
except since this needs to be triggered by multiple paths, I'd have to

a) create and manage the IN > environment variable naming, and
create/update of the env vars
b) conditionally update the env vars from the IN, since updates might come
via external trigger which are only ever set as env vars

so it'll actually be easier to just duplicate the code that calls the curl
and pass the secret and ID in I guess.

**Comment by manishas** [comment]
@ambarish2012 can we update the API docs with this:

a) how to find the resourceid in order to make a call like  GET /resources
b) calling triggerNewBuildRequest with env variables
