### ISSUE TITLE
Support shallow clone

### ISSUE THREAD

**Issue by keen99** [Shippable/support#3862]
folks,

testing out migrating a large monorepo project to shippable.    This will use shippable-managed minions not private minions.

For a runCI job I've noticed a few things:

First, intermittently the repo can take many minutes to clone (6m 22s this time - sometimes it's only 30-45 seconds).   I'm assuming it's found a new minion that doesn't have a cache.   Is there no shared cache between minions for git?

Second, the clone seems to happen twice - one `git_sync` step before `build_pre_ci` and a second `git_sync` in the final build container between `setup_ruby` and `build_ci`.   I HOPE this one will be leveraging a cache of the first - it appears to be faster or as fast as the first run (when the first run is fast)

Since you guys have written articles about using monorepos internally, any suggestions for how to optimize shippable's git clones for large repos?

**Comment by fieldawarepiotr** [comment]
I'll add my question here:
Is there a way to customize git sync step? I'd like to do shallow clone of the repo (depth=1) instead of doing it all the way.
Is there a way to do so?

**Comment by manishas** [comment]
This is in flight and will be available soon.

**Comment by ric03uec** [comment]
@keen99 this feature is now available in production. You can see more details in docs http://docs.shippable.com/ci/shallow-clone/

**Comment by ric03uec** [comment]
@fieldawarepiotr ^^^

**Comment by fieldawarepiotr** [comment]
Already using it. Thank you!
