### ISSUE TITLE
rSync Failure

### ISSUE THREAD

**Issue by KarolAdamiec** [Shippable/support#3863]
Hi,

Out of the blue my main repo with jobs and resources stopped syncing correctly. How can that be fixed? In order to force it i tried multiple things, even deleted the key from GitHub, nothing works...

This is a blocker for us. :(

```
git_sync 0s  
Identity added: /tmp/key.pem (/tmp/key.pem)
Cloning into '/build/IN/web-template_master/syncRepo'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

https://app.shippable.com/github/Trilogiq/jobs/web-template_master_rSync/builds/59ce4b536b484407003cb33e/console

**Comment by a-murphy** [comment]
From the error, it sounds like the deploy key on the GitHub repository was most likely deleted.  This can occur if the account used to add the deploy key revokes access to Shippable or loses access to the repository.

There should be a deploy key named "shippable-1534" on the GitHub repository used as your syncRepo.  This is not the same key as is used for CI.  If it's no longer there, I can email the public key so you can add it back.  We're planning to add a way to reset the deploy key for a syncRepo by clicking a button, like for CI projects, but unfortunately it's not ready yet.

If the correct key is still there, or was there when it was failing, have you renamed the project?  A rename that hasn't been noticed yet could also cause an error that should be resolved by clicking sync on the profile page.

**Comment by KarolAdamiec** [comment]
i deleted that key in unsuccessful attempts to make it work/resync generate a new key. So please email me a public key. Thanks.

**Comment by a-murphy** [comment]
I've sent the public key to your default email address in your Shippable account profile.  Let us know if it still doesn't work.
