### ISSUE TITLE
reduce number of calls to bitbucket to avoid rate limiting

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#3864]
Hi,

I cant restart jobs at the moment...

https://app.shippable.com/subs/bitbucket/swisnl/dashboard

Perhaps a bitbucket api rate issue again? But i haven't been using shippable much today :/

**Comment by a-murphy** [comment]
Our logs confirm that it is the result of reaching the rate limit for some of your Bitbucket projects.  Bitbucket rate limits are measured per Bitbucket account, so it's possible that something other than Shippable is contributing to the rate limit.  I'm not sure how you're getting rate limited this frequently; it's certainly not typical.  Do you know if you have something else set up that calls Bitbucket, or have you been clicking sync every few minutes?

For the immediate problem, my suggestion is to wait a few more minutes and click sync again.  The Bitbucket rate limits are all measured in one hour windows.

**Comment by bbrala** [comment]
For bitbucket not really. Just my editor windows perhaps, but that
shouldn't be that much... Do you have counters logged perhaps? Think
bitbucket sends back headers with counts doesn't it?

Op 2 okt. 2017 18:19 schreef "a-murphy" <notifications@github.com>:

**Comment by a-murphy** [comment]
We don't have the headers logged; just "Rate limit for this resource has been exceeded" and the name of a repository.  I've opened an internal issue to look into reducing the number of calls made when synchronizing Bitbucket accounts.

**Comment by manishas** [comment]
This should now be fixed. Closing.
