### ISSUE TITLE
How to re-add a sync repository with the default flag

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#3865]
### Description of your issue:
This may be just a general question. Could you please have a look and clarify?

In Github, the repository contains two branches: master and shippable-pipeline. 
In Shippable, the shippable-pipeline branch has been synced by using a customised flag (without a default flag) since we started the project. 

Is this the reason why the shippable-pipeline branch doesn't appear in the list?
![image](https://user-images.githubusercontent.com/14726381/31106947-e10c09ce-a83a-11e7-9d69-1b65ff1b15bb.png)

What I'm trying to do is that the pipeline doesn't display correctly when using a customised `flags`. So I have to remove the customised flags` in the shippable-pipeline branch and then I will re-add a sync repository again with the default flag.
![image](https://user-images.githubusercontent.com/14726381/31107073-9cf8cbc2-a83b-11e7-8e7c-5167090aeac3.png)

Could you please advise?

**Comment by JoeRattanamaneesilp** [comment]
Also I have found this tutorial page. 
http://docs.shippable.com/platform/tutorial/workflow/crud-syncrepo/#editing-a-syncrepo
It seems that the EDIT FLAGS field doesn't appear in the current Shippable. 
![image](https://user-images.githubusercontent.com/14726381/31109094-5773af32-a849-11e7-8868-d4a75084a758.png)

Could you please check?

**Comment by ankul-shippable** [comment]
@JoeRattanamaneesilp Your `shippable-pipeline` branch is not showing while adding the new syncRepo because you have already added a pipeline using this branch. We only support one syncRepo per branch.

From your last comment is seems you are checking for update default flag setting on rSync job's page, we have moved this setting from rSync job to syncRepo(`search-service_shippable-pipeline` resource in your pipeline). Please it check there and let us know if you are able to update the default flag.

**Comment by JoeRattanamaneesilp** [comment]
@ankul-shippable Thanks for the clarification and the solution.

Now I'm able to update the default flag. Also I have removed the old flag on the same page. 
However, the old flag is still appearing in the list.
Could you please guide me how I can delete the old flag in the list?
![image](https://user-images.githubusercontent.com/14726381/31153118-07265da2-a8eb-11e7-8fd5-47b88c322104.png)

Cheers,
Joe

**Comment by ankul-shippable** [comment]
@JoeRattanamaneesilp While updating the default flag, it was not deleted from your rSync job.
we have deleted it. It should not show in the flags list now.
Thanks

**Comment by JoeRattanamaneesilp** [comment]
Thanks @ankul-shippable 

Could you please tell me if we have a step to manually delete it?

If this cannot be done by myself, could you please help to delete the pointed flags as shown in the screenshot below?
![image](https://user-images.githubusercontent.com/14726381/31206849-2e5af276-a9c6-11e7-9cbf-89062f672202.png)

**Comment by ankul-shippable** [comment]
@JoeRattanamaneesilp We have deleted these flags. Thanks

**Comment by Nathaniel9729** [comment]
Want to help . Don't want to be forced

**Comment by Nathaniel9729** [comment]
Reroute flag

**Comment by JoeRattanamaneesilp** [comment]
Thanks @ankul-shippable for your help.
