### ISSUE TITLE
/usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)

### ISSUE THREAD

**Issue by DronMDF** [Shippable/support#3866]
Two days ago build are ok.
https://github.com/DronMDF/goost/commits/master

Today i remove one comment.
And build was failed.
https://app.shippable.com/github/DronMDF/goost/runs/495/summary/console

Where was I wrong?
Thank.

**Comment by a-murphy** [comment]
There was a new version of pdd [released yesterday](https://rubygems.org/gems/pdd/versions/0.18).  Your `gem install pdd` command doesn't tell gem which version to install, so it's installing the new version.  Another dependency, [rainbow](https://rubygems.org/gems/rainbow), was added in version 0.18 and the error is when gem tries to install that dependency.  It looks like adding `gem install rake` before `gem install pdd` in your `shippable.yml` file should fix the error.

**Comment by DronMDF** [comment]
Thank's.
I apologize for the trouble, I could have guessed it myself.
