### ISSUE TITLE
Builds stays in waiting state

### ISSUE THREAD

**Issue by szarekm** [Shippable/support#3868]
Hello,
I started a build about an 40 minutes ago and it is still in 'QUEUED JOBS'
There were no other builds run in that time. Right now I have 7 jobs - all queued.
There are no active jobs.

Link to the first job:
https://app.shippable.com/github/twentybelow/QuantumX_Iris_Module/runs/1348/1/console

**Comment by nalipaz** [comment]
me too

**Comment by Fabianoshz** [comment]
Same here

**Comment by ricardoon** [comment]
Having the same issue.

**Comment by nalipaz** [comment]
I wonder if there is some sort of mass attack going down, because TravisCI has the same thing going on since this morning.

**Comment by trriplejay** [comment]
we're investigating. thanks for reporting.

**Comment by nalipaz** [comment]
https://www.traviscistatus.com/
TravisCI seems to be posting some sort of issue with Github integration possibly

**Comment by nalipaz** [comment]
nice to know it isn't isolated to github @jdextraze

**Comment by ambarish2012** [comment]
A Bitcoin miner launched an attack that took up a large number of our build resources and caused a lot of customer builds to get queued up. We have addressed this issue and builds are getting processed now.

**Comment by nalipaz** [comment]
fast sleuthing guys, way to go
