### ISSUE TITLE
Unable to enable project

### ISSUE THREAD

**Issue by MarkCuddihy** [Shippable/support#3871]
### Description of your issue:
I am unable to enable a project. I believe the issue is because I had enabled the project on shippable, then I deleted the project on github and created a new project with the same name. Now I am unable to enable the project and I get the following error message.

deleteResourceById failed for id: 45196 returned error deleteVersionById for versionId: 2380536 returned error: versions.destroy failed for versionId: 2380536 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"

I have tried to delete my account and create a new one but I am unable to delete my account. I just get an error "Invalid APIToken" and am then logged out.

Could you wipe my account data so that I can create a new one and have this issue resolved.

**Comment by a-murphy** [comment]
Account deleted as requested.  Please let us know if you run into any other problems.

**Comment by a-murphy** [comment]
It looks like you've successfully created an new account and re-enabled your project, so I'm closing this as resolved.  Let us know if you run into any more problems.
