### ISSUE TITLE
AWS ECS Deployments Failing

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3872]
I'm getting very quick results showing my AWS ECS deployments as failed, although, checking on AWS, the tasks do seem to get created and end up running.

I've reduced our deployment manifest down to a single container to try to reduce the possibility that the problem is one of my deployment configurations, but I'm still getting the same sort of errors: the Shippable console log even seems to show a series of success messages, but then this:

> Deployment failed for fh-td-backend-deployment-manifest
> Deployment failed with error : true

Please checkout the dashboard for our aws-td-deploy deployment job: https://app.shippable.com/github/formhero/jobs/aws-td-deploy/dashboard

I've been trying a number of different things, including recreating the cluster, recreating the load balancer, manually removing the tasks / reducing the number to 0, etc, and then redeploying, but I'm running into similar issues regardless.

There's probably just something I'm missing, and an expert set of eyes will be a big help.

Thanks

**Comment by ryan-kimber** [comment]
I've now removed our load-balancer too, so we're not trying to deploy a single container, but it's still failing in the Shippable console:

![screen shot 2017-10-04 at 10 05 23 am](https://user-images.githubusercontent.com/1018189/31180079-a82ba266-a8eb-11e7-99e5-211e1c262b56.png)

**Comment by ryan-kimber** [comment]
I've created two brand new clusters: td-blue-cluster and td-green-cluster, and running the deployment successfully created the tasks, but again, reported failed.
![screen shot 2017-10-04 at 10 19 32 am](https://user-images.githubusercontent.com/1018189/31180884-ca4147dc-a8ed-11e7-846e-36dc968adfba.png)

**Comment by ryan-kimber** [comment]
Redeploys on these two new clusters now seem to be working (I still have the load balancer commented out). 
I'm working on adding the load-balancer back in.

**Comment by trriplejay** [comment]
ahh, i think i see the problem. I notice that your manifests all go into your release job, but then you also have two manifests specified directly as input to the deploy job.

when you pass manifests into a release job, and then the release job into the deploy job, the release job carries all of the manifests into the deployment, so you don't need to directly use the manifests as IN statements on the depoy job.

I think the errors you are seeing are a side effect of having the same manifest being deployed multiple times in the same deploy job.

**Comment by ryan-kimber** [comment]
That makes so much sense.

**Comment by ryan-kimber** [comment]
That fixed it. Deployment is working consistently now. Thank John!

**Comment by Nathaniel9729** [comment]
Run
