### ISSUE TITLE
AWS EC2 deployment using upgrade

### ISSUE THREAD

**Issue by glozhkovoy** [Shippable/support#3876]
Hi, I've tried to use **deployMethod: upgrade** in my deployment job but I ended up with this

> https://app.shippable.com/github/kylepolich/jobs/shipdemo-dev-deploy/builds/59d61962a59c1d0700689933/console

> service was unable to place a task because no container instance met all of its requirements. The closest matching (container-instance 918476b4-c715-48a8-ae71-e6471012f912) is already using a port required by your task.

resource.yml

> resources:
>   - name: shipdemo-img-master
>     type: image
>     integration: crep-deploy2
>     pointer:
>       sourceName: "myName" 
>       isPull: false
>     seed:
>       versionName: "latest"  
> 
>       
>   - name: shipdemo-img-options-both
>     type: dockerOptions
>     version:
>       portMappings:
>         - 80:80
>         - 443:443
>         - 3000:3000
>         - 8000:8000
>         - 9001:9001
>      
>      
>   - name: ecs-master-cluster
>     type: cluster
>     integration: crep-deploy 
>     pointer:
>       sourceName : "crep-cluster" 
>       region: "us-east-1" 
>       
>       
>   - name: shipdemo-img-dev
>     type: image
>     integration: crep-dev-ecr
>     pointer:
>         sourceName: "myName"
>         isPull: false
>     seed:
>         versionName: "latest"
>         
>         
>   - name: ecs-dev-cluster
>     type: cluster
>     integration: crep-dev-aws
>     pointer:
>       sourceName : "testshipcluster" 
>       region: "us-west-1"

jobs.yml

> jobs:
>   - name: shipdemo-manifest-master
>     type: manifest
>     steps:
>      - IN: shipdemo-img-master
>      - TASK: managed
> 
>   - name: commercial-real-estate-portal_runCI
>     type: runCI
>     steps:
>       - OUT: shipdemo-img-master
>       - OUT: shipdemo-img-dev
> 
>   - name: shipdemo-master-deploy
>     type: deploy
>     steps:
>       - IN: shipdemo-manifest-master
>         force: true
>       - IN: shipdemo-img-options-both
>       - IN: ecs-master-cluster
>       - TASK: managed
>         deployMethod: upgrade
>         
>         
>   - name: shipdemo-manifest-dev
>     type: manifest
>     steps:
>       - IN: shipdemo-img-dev
>       - TASK: managed
>       
>       
>   - name: shipdemo-dev-deploy
>     type: deploy
>     steps:
>       - IN: shipdemo-manifest-dev
>         force: true
>       - IN: shipdemo-img-options-both
>       - IN: ecs-dev-cluster
>       - TASK: managed
>         deployMethod: upgrade    

I found this page **http://docs.shippable.com/deploy/deployment-method-upgrade/** and tried to look at source code but it wasn't useful for me since there's used **replace method**.

If you need any more information -- I will provide it for you

Any advice and suggestions will be greatly appreciated!

**Comment by glozhkovoy** [comment]
I've faced another problem...
When I tried to change everywhere **upgrade** back to **replace** in deploy console it still using **upgrade** everywhere even when this word is not in the file. It seem like **upgrade** is cached somewhere... 

This problem is more important for me right. Thank you for for any advice or suggestion

**Comment by a-murphy** [comment]
It doesn't look like your syncRepo has detected any changes to your YML files since Tuesday.  Could you double-check that you are updating the master branch (the one specified when you added the syncRepo)?  And that your repository on GitHub has two webhooks, one for your CI and one for your syncRepo?

**Comment by glozhkovoy** [comment]
@a-murphy That works for me. Somehow master was behind oh my changes. Thank you!

Back to my first question -- any suggestion how to setup **upgrade** or **bluegreen** deployment?

**Comment by a-murphy** [comment]
Upgrade and blueGreen deployments to Amazon ECS both require there to be enough space to start additional containers before stopping the old ones.  It looks like you were running into a port conflict trying to place the new container, so you'll need to make sure you have more Amazon ECS Container Instances in the cluster than there are replicas of the image you're trying to deploy.  Alternatively, you can look into using a Application Load Balancer, [Shippable documentation here](http://docs.shippable.com/deploy/lb-amazon-ecs-app/), to expose your containers' ports without needing the same ports on the Amazon ECS Container Instance to be available.

**Comment by glozhkovoy** [comment]
@a-murphy 
Thank you. This works for me.
