### ISSUE TITLE
Missing rebuild button on build

### ISSUE THREAD

**Issue by JaZo** [Shippable/support#3877]
### Description of your issue:
The rebuild button is sometimes missing on a build. In this case I don't see the button, but a colleague does and sometimes it's the other way around. This is very annoying because I have to 'search' for a colleague who can see the button in order to trigger a rebuild! I couldn't find any documentation stating there's some logic behind the visibility of this button.

![shippable-missing-rebuild-button](https://user-images.githubusercontent.com/3475007/31228641-787b27a0-a9de-11e7-935f-38fbc551d369.PNG)

**Comment by Riturajcse** [comment]
Hey, @JaZo sorry for the inconvenience. If you have collaborator or admin permission on any project you must be seeing the `rebuild` button for them. So can you make sure your account has the correct permissions for this project?
Also, this will be really helpful for us to debug if could share the build link.

**Comment by JaZo** [comment]
Hi @Riturajcse, how can I check if I have the right permissions? I have admin rights for this project on Bitbucket. Is that what you mean? The button is randomly shown on the same project while my (Bitbucket) rights haven't changed in between.
How can I share the build link privately? My company doesn't want the project name to be publicly visible.

**Comment by Riturajcse** [comment]
Hey, @JaZo you can email me the build link on rituraj@shippable.com .

**Comment by manishas** [comment]
We have fixed this issue, closing.
