### ISSUE TITLE
Merge builds of pull requests fail

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3878]
Apparently with the latest update of Shippable from v4.9.x to v5.10.1 the logic how merge builds of pull request are processed has changed which leads to build failures. See project `58ab0bf60bfe57100058d7a6` for example.

Before the `git_sync` step of merge builds (e.g. build 1838) looked like this:

```
ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; cd /root/src/<provider>/<owner>/<repo> && git clean -f && git fetch'
git config --get user.name || git config user.name 'Shippable Build'
git config --get user.email || git config user.email 'build@shippable.com'
rm -rf /root/src/<provider>/<owner>/<repo>/shippable
mkdir -p /root/src/<provider>/<owner>/<repo>/shippable/testresults
mkdir -p /root/src/<provider>/<owner>/<repo>/shippable/codecoverage
mkdir -p /root/src/<provider>/<owner>/<repo>/shippable/buildoutput
git reset --hard <commit>
git merge -q origin/master
echo "No .gitmodules file was found in the repository"
echo 'Number of files: <files>'
echo 'Repo size: <size>'
```

Now (e.g. build 1846) it looks like this:

```
ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; cd /root/src/<provider>/<owner>/<repo> && git clean -f && git fetch'
  git config --get user.name || git config user.name 'Shippable Build'
  git config --get user.email || git config user.email 'build@shippable.com'
  rm -rf /root/src/<provider>/<owner>/<repo>/shippable
  mkdir -p /root/src/<provider>/<owner>/<repo>/shippable/testresults
  mkdir -p /root/src/<provider>/<owner>/<repo>/shippable/codecoverage
  mkdir -p /root/src/<provider>/<owner>/<repo>/shippable/buildoutput
  git remote add PR mbrodala@<provider>:<owner>/<repo>.git
  ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub; git fetch PR'
Identity added: /tmp/ssh/00_sub (/tmp/ssh/00_sub)
Warning: Permanently added the RSA host key for IP address '<ip-address>' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

retrying 1 of 3 times...
  ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub; git fetch PR' 1s  
Identity added: /tmp/ssh/00_sub (/tmp/ssh/00_sub)
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

retrying 2 of 3 times...
  ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub; git fetch PR' 1s  
Identity added: /tmp/ssh/00_sub (/tmp/ssh/00_sub)
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

retrying 3 of 3 times...
```

Please notice especially these two new lines:

```
  git remote add PR mbrodala@<provider>:<owner>/<repo>.git
  ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub; git fetch PR'
```

This adds a new remote which is supposed to be used for the PR checkout which is bound to fail since I have not added the Shippable deployment key to my personal account. I also don't understand why this was changed since it does not make sense for arbitrary builds triggered by arbitrary people to use the provider account of a single user. (Apparently the user set as *Account Used* in the *Webhook Config* of *Project Settings*.)

Please fix this ASAP since we see all pull requests failing due to this change.

**Comment by Riturajcse** [comment]
Hey, @mbrodala sorry for the inconvenience. I have opened an internal issue for this. We will update you soon with our findings.

**Comment by shrivara** [comment]
@mbrodala, there has been no change in any of the git clone flows this release. We're seeing a mismatch in the project's repository url and the pull request repository url which is causing our build system to assume that this is a pull request from a different repository. These values are synced directly from Bitbucket. We're investigating why these values have changed.

**Comment by rageshkrishna** [comment]
@mbrodala We have confirmed that BitBucket has started returning slightly different (but still valid) values for the repository's SSH URL. This is confusing our git_sync logic that tries to check if we are currently doing a branch-to-branch or fork-to-fork pull request.

I'm very sorry that this broke for you. We did not know that BitBucket was going to make this change.

We're working on fixing this right now and should be able to get it patched soon.

**Comment by mbrodala** [comment]
@rageshkrishna Thank you for investigating this. We ourselves didn't know that Bitbucket did such changes, the only thing that was announced was a [database maintenance](https://status.bitbucket.org/incidents/pcjcw4vp4fgj).

**Comment by Riturajcse** [comment]
Hey, @mbrodala we have patched the fix for this. Can you please check if this is resolved?

**Comment by mbrodala** [comment]
@Riturajcse the issue seems fixed, confirmed in build 1863. Thanks a lot. :-)
