### ISSUE TITLE
Missing build_ci, partially executed in build_on_failure

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3879]
Currently one of our projects (`562dfa4f1895ca44742111f1`) displays some weird build behavior:

1. There is no `build_ci` step.
2. Some of the steps defined for `build.ci` are executed in `build_on_failure` instead.
3. All steps are successful (green check mark on the right).
4. There is no error message anywhere
5. The whole build fails.

See for example build 768 of that project. There is no difference in the `shippable.yml` compared to other projects AFAIS.

**Comment by a-murphy** [comment]
I've opened an internal issue to look into the strange grouping in these logs more closely.  As far as I can tell, it looks like one of the dividing statements got lost, causing the logs to be grouped incorrectly and some of the logs to not be shown.

For the actual failure, you can see more of the logs in the downloaded version (there's a download link in the right column above the logs).  And those logs imply that your runner returned a nonzero exit code, which caused the job to fail.  Is your runner configured to fail the job when the linter doesn't pass?

**Comment by mbrodala** [comment]
@a-murphy The messages you mention are only warnings, they are not supposed to let the build fail, thus this part is fine actually. Here's the [exit code logic of the linter](https://github.com/martin-helmich/typo3-typoscript-lint/blob/45cc0bc/src/Command/LintCommand.php#L154-L159); as you can see, it always exits with status `0` except a) there are errors or b) strict linting is enabled (not the case here).

Maybe Shippable should output a message between each command to display the exit code? Travis does this AFAIK.

**Comment by ankul-shippable** [comment]
Hi @mbrodala, 
We investigated it and found that same UUID was generate for `build_ci` and `build_on_failure`. Due to this during grouping of these consoles, all the consoles of `build_ci` and `build_on_failure` sections were added as part of `build_on_failure` section.

Is this still happening for you?

**Comment by mbrodala** [comment]
No, I haven't seen this issue again.
