### ISSUE TITLE
Documentation unclear about the required files for advanced Jacoco reports

### ISSUE THREAD

**Issue by Nepherte** [Shippable/support#3880]
As per the issue title, the documentation is being very vague about the files required for advanced Jacoco reports and in what structure it expects them to be present under 'shippable/codecoverage'.

> In order to get advanced reports, you must copy more than just the xml file to get the full results.

and it continues to be vague in the provided code snippet:

> \# copy this target folder to the `shippable/codecoverage` folder

where 'this target folder' is something that Maven and its plugins generates. I'm not using Maven and I really don't want to start guessing about what files and folders shippable needs.

**Source:** http://docs.shippable.com/ci/jacoco-reports/

**Comment by trriplejay** [comment]
The basic requirement is for the coverage results to be in a `jacoco.xml` file that exists at this location: `shippable/codecoverage/target/site/jacoco/jacoco.xml`

I see you're using ant. We have a sample project that provides a very basic example, perhaps you can use it as a reference for how to store the jacoco output: https://github.com/shippableSamples/sample_jacoco/tree/ant

**Comment by Nepherte** [comment]
@trriplejay That is not what I meant. The documentation talks about "standard Shippable coverage results" and "advanced reports". You are talking about the former, I am talking about the latter.

To get the standard coverage results, indeed one has to copy the jacoco.xml file to the shippable/codecoverage folder. That is something I've already managed to do in Ant, because this part is documented properly: it clearly states it needs the jacoco.xml file in a specific folder.

To get the advanced reports, "You must copy more than just the xml file to get the full result" (according to the documentation). Then there is a code snippet from shippable.yml that simply copies the entire target folder generated by Maven to shippable/codecoverage. That documentation is very vague about what Shippable needs to show these advanced reports, and I believe it should be stated more clearly what is expected. Would the jacaco sample you're linking to, be sufficient for these advanced reports (ie. the jacoco.exec file, the csv report, the html report and the xml report)?

**Comment by scriptnull** [comment]
@Nepherte Thanks for the suggestion. 

Here is a basic file structure that is needed for seeing both standard and advanced jacoco reports.

```
target/
`-- site
    `-- jacoco
        |-- com.mycompany.app
        |   `-- App.java.html
        `-- jacoco.xml
```

- `target/site/jacoco/jacoco.xml` is needed for standard reports
- `target/site/jacoco/your.package.name/SourceFileName.java.html` is needed for seeing the advanced reports.

> Would the jacaco sample you're linking to, be sufficient for these advanced reports (ie. the jacoco.exec file, the csv report, the html report and the xml report)?

Yes. All we need is `jacoco.xml` and the `.html` report files. You can omit the other files.

**Comment by Nepherte** [comment]
@scriptnull That is exactly the information I needed.

**Comment by manishas** [comment]
docs have been updated. closing.
