### ISSUE TITLE
during docker build, Cannot mkdir for WORKDIR

### ISSUE THREAD

**Issue by grandvizier** [Shippable/support#3881]
I'm having problems with performing the docker build. Locally on my machine everything works. But using the following Dockerfile:
```
FROM node:boron

WORKDIR /usr/app

COPY package.json .
RUN npm install
COPY ./build ./build
```

with the shippable step:
`- docker build -f $SHIPPABLE_BUILD_DIR/frontend/Dockerfile.web -t $DOCKER_ACC/web:$BUILD_NUMBER $SHIPPABLE_BUILD_DIR/frontend/`

----
results in the following error in the build
https://app.shippable.com/github/grandvizier/kinotimes/runs/35/1/console
```
Step 1 : FROM node:boron
 ---> 4e55a5706ff2
Step 2 : MAINTAINER KinoTimes <admin@kintotimes.tk>
 ---> Using cache
 ---> 87840a5e45e7
Step 3 : WORKDIR /usr/app
 ---> Running in c1086cdc3c4c
 ---> 66a4bfb63378
Removing intermediate container c1086cdc3c4c
Step 4 : COPY package.json .
 ---> 0a3f3affbd03
Removing intermediate container c40b50a3897d
Step 5 : RUN npm install
 ---> Running in ca259cfc95b6
Cannot mkdir: /usr/app is not a directory
```
-----
Why is it waiting two Steps later to error that it can't make the dir?
What version of docker is this?

**Comment by grandvizier** [comment]
solution was to add `RUN mkdir /usr/app` before setting the WORKDIR

**Comment by Princewilln** [comment]
I added Run mkdir /usr/app before WORKDIR it still did not work for me

Step 1/5 : FROM openjdk:8-jre-alpine
 ---> f7a292bbb70c
Step 2/5 : EXPOSE 8080
 ---> Using cache
 ---> 353cf68682d9
Step 3/5 : COPY ./target/java-maven-app-*.jar /usr/app
 ---> 639f0086639f
Step 4/5 : RUN mkdir /usr/app
 ---> Running in e29117602db6
[91mmkdir: can't create directory '/usr/app': File exists
[0mThe command '/bin/sh -c mkdir /usr/app' returned a non-zero code: 1

**Comment by FeelCoolOne** [comment]
@Princewilln > 

Add that before `COPY`,  since` COPY` has used that dir `/usr/app`.  when you use dir, you must make sure that exist, otherwise you should make it by yourself before using that.
