### ISSUE TITLE
Changing owner of account integrations

### ISSUE THREAD

**Issue by rhenretta** [Shippable/support#3882]
I am the one who set our organization up on shippable, and as such I'm the owner on all the integrations that we use.  I plan on leaving the company, and need to make sure those integrations won't be affected when my account is no longer connected to the organization.

**Comment by a-murphy** [comment]
Since account integrations belong to an account, the best solution here would be to add another integration with the same values to another person's account and have that person update each of the subscription integrations to use the new account integrations.

**Comment by manishas** [comment]
Instructions are here: http://docs.shippable.com/platform/tutorial/integration/howto-crud-integration/#updating-a-subscription-integrations-underlying-account-integration

**Comment by manishas** [comment]
Please note that someone else from the team needs to go through these steps for each integration. You do not have to change the YML config since the Subscription Integration Name remains the same.

**Comment by rhenretta** [comment]
Perfect, thank you
