### ISSUE TITLE
Not able to enable a project

### ISSUE THREAD

**Issue by sibiisac** [Shippable/support#3884]
Following error message is generated in the shippable

deleteResourceById failed for id: 46204 returned error deleteVersionById for versionId: 2479630 returned error: versions.destroy failed for versionId: 2479630 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"

**Comment by a-murphy** [comment]
I've deleted the resources causing the error if you would like to try again.  It looks like there was a previously enabled project with the same name that was deleted on the source provider causing the conflict.

**Comment by sibiisac** [comment]
Great, thanks for the help
