### ISSUE TITLE
python project freeze (while saving image or multiprocessing)

### ISSUE THREAD

**Issue by Borda** [Shippable/support#3889]
### Description of the issue:
I have a python project using standard python libraries/packages where a part of the test run is exporting a figure with visualization to a folder. This action has been there for a while but just recently it starts to freeze in the middle of the matplotlib.pyplot.savefigure() even it worked fine and also the same code runs fine on other CI such as CircleCI. Do you have any advice what can I do?

### Link
https://app.shippable.com/github/Borda/pyImSegm/runs/111/1/console

**Comment by niranjan92** [comment]
@Borda Can you try running a new build and check the disk and memory usage for the node while running the build? 

You can check that by going to  subscriptions page -> Settings -> Nodes

**Comment by Borda** [comment]
@niranjan92 ok, good idea... I did it but I do not see any strange behavior. 
![screenshot at 2017-10-13 09-03-22](https://user-images.githubusercontent.com/6035284/31534123-c9ae9194-aff5-11e7-97c3-a61048de3a44.png)

The peace of code which raise the issue is:
```
logging.debug('exporting segmentation: %s', path_img)
im_seg = Image.fromarray(segm.astype(np.uint8))
im_seg.save(path_img)
```
with following output:
```
DEBUG:root:exporting segmentation: /root/src/github.com/Borda/pyImSegm/results/experiment_segm-unSupervised_imgDisk/segmentation_GroupGMM/0002_img_43.png
```

and also I tried another alternative:
```
logging.debug('exporting segmentation: %s', path_img)
io.imsave(path_img, segm)
```
with following output:
```
DEBUG:root:exporting segmentation: /root/src/github.com/Borda/pyImSegm/results/experiment_segm-unSupervised_imgDisk/segmentation_GroupGMM/0002_img_43.png
/root/venv/2.7/local/lib/python2.7/site-packages/skimage/io/_io.py:132: UserWarning: /root/src/github.com/Borda/pyImSegm/results/experiment_segm-unSupervised_imgDisk/segmentation_GroupGMM/0002_img_43.png is a low contrast image
  warn('%s is a low contrast image' % fname)
```
I is hard for me to find what is the problem because the same code runs fine on all my computers and also for example on CircleCI and it just freezes, does not crash or write any warning...

**Comment by Borda** [comment]
I notice that the issue may lay in the next sper, in joining multiprocessing pool:
```
mproc_pool = mproc.Pool(params['nb_jobs'])
for name, segm in mproc_pool.imap_unordered(wrapper_segment, imgs_idx_path):
    dict_segms_group[name] = segm
    tqdm_bar.update()
mproc_pool.close()
mproc_pool.join()
```

**Comment by niranjan92** [comment]
@Borda i checked that your last successful build was on 30th Sept. We haven't made any changes to the build environment. 

Can we get on a call to figure out why the build started failing? 
email:  niranjan@shippable.com

**Comment by Borda** [comment]
Issue solved, in the end, it was the really what I was partially thinking, full disk space. I did not change any line of code, just add remove the output dir and create it again before calling the script which was freezing.
Well in such case it seems to that the storage chart does not report the real usage never the less that the storage was constant even I was exporting some images...
