### ISSUE TITLE
Roles / Permissions: Can a user be given access to only some functions in a workflow or Assembly Line?

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3891]
Hi Shippable!

We'd love our dev team to be able to view and run early parts of our pipeline, but then not have access to run deploys on our staging and prod servers, etc.

Is it possible to limit access for certain tasks? Is there some way to do this sort of thing?

Thanks! Great product!

**Comment by manishas** [comment]
Great question :)

Yes, you can easily achieve this with the following configuration:

- Separate out the jobs and resources that you do want your dev team to just have read access to and put them in a separate repository in the same organization. 
- Grant your Ops team read/write permissions on this new repository, while granting devs only read access.

This should do it. You can use the instructions here to migrate your jobs/resources to a separate repo: 
[Migrating jobs](http://docs.shippable.com/platform/tutorial/workflow/crud-job/#migrating-a-job-from-one-yml-to-another)
[Migrating resources](http://docs.shippable.com/platform/tutorial/workflow/crud-resource/#migrating-a-resource-from-one-yml-to-another)
 
We respect permissions from your source control for pipelines defined in a sync repo:

- Anyone with read permissions to the sync repo can view the pipelines but cannot trigger anything even through SPOG or Grid views
- Anyone with write/admin permissions on sync repo can view and also trigger jobs 
- Anyone with no access to the sync repo cannot view or trigger anything

Let me know if this clarifies the approach... if it helps, @ttrahan already has this configured and can walk you through it in more detail.

**Comment by manishas** [comment]
One more clarification - jobs and resources in separate repositories in the same organization can refer to each other to build one pipeline. This is why we also require job and resource names to be unique in a single organization.

**Comment by ttrahan** [comment]
Here's a few screenshots that show this functionality in action.

Logged in as user with access to all jobs/resources (i.e. has at a minimum read access in all repos that hold config for the jobs/resources):
![image](https://user-images.githubusercontent.com/4467650/31522120-1673b01c-af61-11e7-91b9-b5ff7186a777.png)

Logged in as a user with access to a subset of the job/resources in the full workflow:
![image](https://user-images.githubusercontent.com/4467650/31522141-386a456e-af61-11e7-9f68-1ccd452cf279.png)

Right-clicking on a job configured in a repo that the user has read-only access. The menu items that allow the user to manually execute the job or configure the job settings are not visible:
![image](https://user-images.githubusercontent.com/4467650/31522190-7622c0fc-af61-11e7-9ae1-6deda19ef68e.png)

**Comment by manishas** [comment]
Closing since it's answered. @ryan-kimber let us know if you need help with this.
