### ISSUE TITLE
I can see all our Org Repos in Shippable, but my team members only see the public ones

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3895]
Everything is working for my account (which is admin on the organization), but the other members of my team only see the public repo.

I checked out our Org settings in GitHub and I see this: 

![screen shot 2017-10-13 at 1 50 26 pm](https://user-images.githubusercontent.com/1018189/31559114-865851d2-b01d-11e7-9556-8b8fb989cdaf.png)

All of our developers have read/write access to each of the repos, and their commits trigger builds, but they just don't see the items in the SPOG or table view.

Any ideas?

**Comment by manishas** [comment]
Have the members of your team enabled private repos?

http://docs.shippable.com/platform/management/git-identities/#github

**Comment by ryan-kimber** [comment]
That fixed it! Thanks Manisha.
