### ISSUE TITLE
 !!!! Job 344495	 !!!! hapi-legacy-dev-ecs stuck with no way to cancel

### ISSUE THREAD

**Issue by ritch-parker** [Shippable/support#3896]
There is no obvious way to cancel this job which has been running for 8+ hours and preventing future jobs from running.   This is preventing dev progress on our side.

**Comment by trriplejay** [comment]
We're taking a look at this now.

**Comment by trriplejay** [comment]
I've cancelled the stuck job and opened an internal issue to investigate the cause.  Please let us know if you're having any other trouble.

**Comment by ritch-parker** [comment]
Ok, thanks... is there a way we can cancel such jobs in the future?

**Comment by trriplejay** [comment]
unfortunately no. managed pipeline jobs are not cancelable at this time, but we're working on adding that ability.
