### ISSUE TITLE
unable to see bitbucket projects (~ since 2 hours)

### ISSUE THREAD

**Issue by FelixSchwarz** [Shippable/support#3897]
I had github+bitbucket enabled for my account and everything was fine until about earlier this evening. Then I did reload the page with (failed) build and got a 404. Now I only see my github subscriptions in the left nav bar.

Account -> Integrations still shows bitbucket but I can not enable new bitbucket projects anymore (they are not displayed so I can select them).

Is that specific to my account or did you deploy a new version which broke things?

**Comment by a-murphy** [comment]
Our logs show that we weren't able to connect to Bitbucket last time we tried to synchronize your account.  It does not appear to be a widespread problem, so could you try clicking "profile" on the left and then the "sync" button to synchronize your account again?

**Comment by FelixSchwarz** [comment]
you are right - it works now.

Maybe you could add some indicators for this so users can better recognize the situation (or even better - retry automatically so I never see this :-)
