### ISSUE TITLE
Bitbucket outage resolved - Shippable still unavailable

### ISSUE THREAD

**Issue by sscarduzio** [Shippable/support#3899]
Hi guys,
Bitbucket outage has been fixed, however your status page shows "Bitbucket: major outage".

Will you restore this soon? Or is there other problems?

**Comment by niranjan92** [comment]
@sscarduzio the outage was resolved last week itself. We will update the status page.

**Comment by niranjan92** [comment]
closing as the status has now been updated

**Comment by sscarduzio** [comment]
@niranjan92 interesting how my bitbucket project didn't come back to the Shippable dashboard then.
<img width="1234" alt="screen shot 2017-10-16 at 16 45 20" src="https://user-images.githubusercontent.com/1327189/31618180-88b4c322-b291-11e7-82ce-0ddce4fae159.png">

**Comment by sscarduzio** [comment]
my integration has disappeared, and I can't even recreate it.

**Comment by niranjan92** [comment]
@sscarduzio : if you are able to login, bitbucket integration should be there. Can you please try syncing your account? click and profile section in left pane followed by `Sync` button. 

let me know if the issue still persists

**Comment by sscarduzio** [comment]
I had to press sync and everything came back. Thanks @niranjan92 👍

**Comment by niranjan92** [comment]
@sscarduzio welcome. happy to help
