### ISSUE TITLE
Cannot Modify Key=Value Integration

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3901]
We have a number of key=value pairs set using a 'generic' integration, 'key/value pair' type. 

Today, I realized we need to update the values of two of the pairs, but when I change the values and save, the values are not persisted.

I then tried adding / removing pairs from the list and saving, but had the same result: the updated values are not persisted. 

This is presently preventing us from building / deploying, as our NPM token has been updated, but I cannot update the value in our build/CI process.

**Comment by ryan-kimber** [comment]
This is the screen (with our values intentionally cut off)

![screen shot 2017-10-17 at 1 24 24 pm](https://user-images.githubusercontent.com/1018189/31680007-f4af95e8-b340-11e7-8947-a7fb042435dd.png)

**Comment by trriplejay** [comment]
Hey Ryan. Thanks for bringing this to our attention. As a workaround while we investigate, i'd recommend creating a new accountIntegration with the new key/value pairs that you want, then navigate to your list of subscriptionIntegrations, and edit the one that currently refers to your existing key/value pair so that it references the new key/value accountIntegration instead (you should be able to select it from a dropdown).  Then you can just delete the old one.

**Comment by ryan-kimber** [comment]
Interesting this: I deleted the old one, created a new one with the same name, set all the values, saved and, tada, all the old values are back.

**Comment by manishas** [comment]
http://docs.shippable.com/platform/tutorial/integration/howto-crud-integration/#updating-a-subscription-integrations-underlying-account-integration

**Comment by trriplejay** [comment]
@ryan-kimber did you get this working? i wasn't able to recreate this. it seems like it's working as far as i can tell. was there some confusion between the account integration and the subscription integration?

**Comment by ryan-kimber** [comment]
Hi John,

It's interesting. It seems to be this one specific map. If I create a new
map and try to edit / update it, it works just fine.

If I try to delete this one, then add another one back with the same name,
I end up with the old copy and, once again, I can't make changes to it.

Anyway, we've made a new copy with a different name, and things are working.
