### ISSUE TITLE
Link app changelog

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3902]
The bottom right of the Shippable app shows the current version number which is useful to notice when an update was rolled out. It would be useful if that version number was linking to [the changelog](https://github.com/Shippable/support/wiki) which briefly describes everything that was fixed, added or removed.

**Comment by trriplejay** [comment]
hey, thanks for the suggestion. We do have such a page [here](https://github.com/Shippable/support/wiki), so making that version link to its page seems like a great idea.

**Comment by mbrodala** [comment]
@trriplejay Thanks, I didn't know a changelog already exists, I've updated the title and description.

[BTW](https://github.com/Shippable/support/wiki/5.9.4):

> Runs page shows only summary tab by default and job tabs are created on demand

I thought this was a bug. ;-)

**Comment by mbrodala** [comment]
Seems like this was added with version 5.1.2.1:

![image](https://user-images.githubusercontent.com/5037116/34033593-1c8bbd18-e17b-11e7-900d-8a89c9316819.png)

Thanks a lot! :-)
