### ISSUE TITLE
Pre-populate env variable keys for manual builds

### ISSUE THREAD

**Issue by toanctruong** [Shippable/support#3906]
### Description of your issue:
Is there a way to for manual trigger job to take in a manually entered key/values to be applied to that build? We're trying to move away from TeamCity and this feature has proven quite useful, especially in "job runner" type situations.

**Comment by manishas** [comment]
yes, there is :)

- Go to your project page on Shippable and click on the Play button on the right:

![image](https://user-images.githubusercontent.com/2983749/31755330-9e53aeb0-b452-11e7-9014-39f5b78ccc3c.png)

- This will take you to a screen where you can enter custom environment variables, i.e. key value pairs:

![image](https://user-images.githubusercontent.com/2983749/31755351-c67b8638-b452-11e7-85e3-3436bf994cc6.png)

**Comment by manishas** [comment]
Let me know if this works for you.

**Comment by mohit5it9** [comment]
You can also pass custom environment variables to [runSh jobs](http://docs.shippable.com/platform/workflow/job/runsh/).
- Go to your runSh jobs dashboard on shippable, then click on the Play button on the top right:
![image](https://user-images.githubusercontent.com/11424742/31769290-9cd269ca-b4f0-11e7-91a4-e138ef30d19a.png)
- This will take you to a screen where you can enter custom environment variables, i.e. key value pairs:
![image](https://user-images.githubusercontent.com/11424742/31769350-daba534c-b4f0-11e7-83d1-f66b29c30069.png)

**Comment by toanctruong** [comment]
Thank you @manishas and @mohit5it9 . Is there is method to pre-populate the value keys, and have the user enter in the desired value? For example, if my script or job will consume the variable $ABC and $XYZ, it would be nice if the screen already had those variables present but without any values. This would be helpful especially for non-technical team members running any of these jobs.

**Comment by manishas** [comment]
No, we do not pre-populate the fields today. Definitely something to consider so I'll leave this open as a feature request.

**Comment by manishas** [comment]
This is not on the roadmap as of now, so closing as deferred. If we hear a lot of +1 feedback, it will be reopened and reprioritized.
