### ISSUE TITLE
Difference between post_ci and on_success? [doc update?]

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#3907]
Hi,

After our CI has run we want steps to be taken irrespective of success or failure.

The docs seem to imply that post_ci would be this, but then state that it is not run if CI fails.

What, therefore is the difference between post_ci and on_success?

Could you please update the docs to reflect this, as they seem to be the same.

Thanks.

**Comment by dankonino** [comment]
Hmm good points, @nealeu you have my support. That might be handy in some cases for sure!

**Comment by manishas** [comment]
We're tracking requests for on_cancel and always sections in this issue: https://github.com/Shippable/support/issues/3017, so closing this issue in favor of 3017. 

That issue is approved, so we'll pick this up fairly soon.
