### ISSUE TITLE
Commit message webhook

### ISSUE THREAD

**Issue by toanctruong** [Shippable/support#3908]
Is there functionality to trigger jobs based on the contents of a commit message? I see that one can skip builds, but we would like to use custom commit messages to trigger particular jobs/workflows.

http://docs.shippable.com/ci/skip-builds/

**Comment by trriplejay** [comment]
From a CI perspective, there is no direct support for what you're asking, however the commit message is available in your build as an environment variable: `$COMMIT_MESSAGE`.  You can utilize this in your script to perform certain actions when certain substrings are detected, or something like that.


In Shippable Assembly Lines, you can define 'trigger' resources that would allow you to start specific jobs by committing a change to the trigger resource. 

http://docs.shippable.com/platform/workflow/trigger/overview/

Would that work for you? Let me know if you have questions.
