### ISSUE TITLE
Persisting build artifacts

### ISSUE THREAD

**Issue by toanctruong** [Shippable/support#3909]
I've looked through the docs, but don't see anywhere to easily save build artifacts. Not everything we run is in containers so we need to save the outputted files. Is it up to customer to run a custom script and upload those files to a place of our choosing, or is there an integrated artifact storage service? Thanks,

**Comment by manishas** [comment]
@toanctruong you will need to push your artifacts to S3 or another store.

We have a doc that shows how to configure S3 uploads: http://docs.shippable.com/ci/push-to-s3/

**Comment by toanctruong** [comment]
@manishas How do I download the artifacts that were uploaded to S3 through the Shippable UI? We need to be able to download the artifacts produced per job.

**Comment by manishas** [comment]
@toanctruong downloading artifacts pushed to S3 is currently not supported through the Shippable UI.
