### ISSUE TITLE
cliConfig failing to connect/deploy to Kubernetes cluster via bastion

### ISSUE THREAD

**Issue by nmarshall-cst** [Shippable/support#3910]
Hello,

I have two K8s clusters that I would like to deploy pods to via Shippable. One of the two clusters has been working for months. I am trying to build another cluster, but this cluster is a bit different because it is behind a bastion host. I configured the deploy integration to use a bastion host, added my kube config,  and I ran the script on the bastion host to add the shippable account and ssh information. I followed [this doc](http://docs.shippable.com/platform/integration/kubernetes/#adding-account-integration) to create the kube config file, but I am having trouble getting the shippable build server to connect to the cluster. 

```Identity added: /tmp/00_sub (/tmp/00_sub)
Configured kubectl credentials for <redacted>. Using version:
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"04a38a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
runCLI failed with error: 1
```

Are you able to view my kube config in the deploy integration or is there a secure way to send this to you to make sure I have all of the correct settings? The kube config that I pasted into the integration is the same config I use to connect from my local machine and it works correctly.

Build:
- https://app.shippable.com/bitbucket/centerstonetech/jobs/ng-api-ariat-deploy-dev/builds/59e91232af0a170700d68405/console

Thanks!

**Comment by trriplejay** [comment]
Unfortunately the bastion-host mode is not currently supported for cliConfig. It's intended to be utilized in our managed deploy jobs. I'll mark this as a feature request and open an issue internally. I'll also update the documentation to make sure this limitation is stated somewhere. 

When you say you're using this kubeconfig on your local machine, are you using ssh tunneling or something to connect it to the bastion?

**Comment by nmarshall-cst** [comment]
I set the cluster up using [kops](url) with a private network. You might be right that there is [some tunneling](https://github.com/kubernetes/kops/blob/master/docs/bastion.md) happening behind the scenes. I will need to run a few custom commands specific to kops to get it to work. Is there a way to run a script before the cliConfig tries to connect to the k8s cluster?

**Comment by trriplejay** [comment]
no, the cliConfig scripting happens before any user script is executed.

There is one other potential workaround...
- create a new kubernetes integration with the same setup, but add your kubeconfig as json instead of yml format (you can just use a tool like [this](https://www.json2yaml.com/convert-yaml-to-json) to convert).
- instead of cliConfig, create an [integration resource](http://docs.shippable.com/platform/workflow/resource/integration/) that references this new integration, and include it in your job as an IN
- in your script, write some lines like this:
```yml
- script: mkdir -p /root/.kube/
- script: kubedir=$(shipctl get_resource_meta <your integration resource name>)
- script: eval echo -e $(jq '.masterKubeConfigContent' $kubedir/integration.json) > /root/.kube/config
```
Now your kubeconfig should correctly be recognized by kubectl... and you can add your extra kops scripting without the failure you are currently experiencing.

**Comment by nmarshall-cst** [comment]
@trriplejay I appreciate the help on this. I worked around this by handling all of the kubectl/kops configurations using the `script: ...` functionality. Here is an example in case it helps someone else out. 

      - TASK:
        - script: curl -sSL https://github.com/kubernetes/kops/releases/download/1.7.1/kops-linux-amd64 -O
        - script: chmod +x ./kops-linux-amd64
        - script: mv kops-linux-amd64 /usr/bin/kops
        - script: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        - script: chmod +x ./kubectl
        - script: mv kubectl /usr/bin
        - script: export KOPS_STATE_STORE=s3://<kops_state_store>
        - script: cd /build/IN/repo/gitRepo/cluster-configurations/
        - script: export CLUSTER_NAME=<clusterName>; /usr/bin/kubectl config set-context k8s-cluster --namespace=default --cluster=$CLUSTER_NAME --user=$CLUSTER_NAME
        - script: export CLUSTER_NAME=<clusterName>; /usr/bin/kops export kubecfg $CLUSTER_NAME
        - script: /usr/bin/kubectl config use-context k8s-cluster
        - script: export CLUSTER_NAME=<clusterName>; /usr/bin/kops replace cluster --name $CLUSTER_NAME -f $CLUSTER_NAME.yaml
        - script: kubectl apply -f /build/IN/repo/gitRepo/deployments/example-deployment.yaml -l environment=default

**Comment by trriplejay** [comment]
awesome, glad you got it working!
