### ISSUE TITLE
Trigger a build by posting a payload to an endpoint

### ISSUE THREAD

**Issue by nalipaz** [Shippable/support#3911]
This is a question on either how to do it, or perhaps a feature request if not an option currently.

I would like to know if it is possible to kick off a build by posting to an endpoint? There are many applications that don't necessarily integrate with Shippable but have webhooks available. As an example Jira Releases can be made to post a webhook with payload data. I would like to kick off a job on shippable whenever a specific url is called, of course I would need to validate said post data in some way.

Any ideas on this are appreciated. Thanks!

**Comment by manishas** [comment]
The API for triggering a new build is [documented here](http://docs.shippable.com/platform/tutorial/api/api-overview/#!/Runs/post_projects_projectId_newBuild)

It's a POST to /projects/{projectId}/newBuild

Optionally, a `globalEnv` object can be passed to trigger the run with additional environment variables. Let me know if this helps.

**Comment by mohit5it9** [comment]
Yes, You can do this. If you want to trigger CI builds for a particular project you can use this api endpoint `POST /projects/:projectId/newBuild`.
If you want to trigger some builds for your pipeline you can use this endpoint `POST /resources/{resourceId}/triggerNewBuildRequest`, where resourceId is the Id of the job you want to trigger.
You can also refer to our docs [here](http://docs.shippable.com/platform/tutorial/api/api-overview/)

**Comment by nalipaz** [comment]
Thanks guys will look into it.
