### ISSUE TITLE
Conditions in global env

### ISSUE THREAD

**Issue by danielsuter** [Shippable/support#3914]
Is it possible to use if statements in the global env part of the configuration? I always get syntax errors if I try to do this:

```
env:
  global:
    - if [ "$BRANCH" != "master" ] ; then APP_NAME=test ; fi
    - if [ "$BRANCH" == "master" ] ; then APP_NAME=prod ; fi
```

**Comment by a-murphy** [comment]
It's not currently possible to use `if` statements in the global section.  However it looks like in your case, it may make more sense to set `APP_NAME` in the `ci` section.

Assuming you're trying to use the `APP_NAME` variable for commands in the [`ci` section](http://docs.shippable.com/ci/build-and-test/) of your `shippable.yml` file, you can simply move the two lines you currently have in `global` to the beginning of the `ci` section.  Then `APP_NAME` will be available to your commands in the CI section.  For reference, the shippable.yml structure is documented [here](http://docs.shippable.com/ci/yml-structure/#anatomy-of-shippableyml) and `if` statements will work in `pre_ci`, `ci`, `post_ci`, `on_success`, `on_failure`, and `push`.
