### ISSUE TITLE
Assistance to triggerJobs

### ISSUE THREAD

**Issue by christianmoretti** [Shippable/support#3916]
Hi, I need to call a trigger passing the same `versionName` for example: 
```bash
echo "versionName=develop.latest" > $JOB_STATE/my-img.env
```
But I'm receiving this message:
![imagem_colada_24_10_2017_11_19](https://user-images.githubusercontent.com/1626925/31945204-3e02d9a0-b8ad-11e7-8840-8fcc097eed92.jpg)

There's a way to force this execution?

Best regards,
Christian Moretti

**Comment by trriplejay** [comment]
i'd recommend adding a second key/value pair to the .env file that will change with every build, like:
```
echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/my-img.env
```
or
```
echo "sha=$COMMIT" >> $JOB_STATE/my-img.env
```

**Comment by christianmoretti** [comment]
@trriplejay thank you, it worked correctly :)
