### ISSUE TITLE
Assistance to create a strategy of e2e tests

### ISSUE THREAD

**Issue by christianmoretti** [Shippable/support#3917]
Hi there,

We need to create an strategy to deploy our staging environment after the e2e tests are performed, we have this configuration (image bellow) and we have some issues to deploy the exactly image that are tested in e2e tests. 
Our configuration:
![imagem_colada_24_10_2017_13_17](https://user-images.githubusercontent.com/1626925/31952276-00185aea-b8bf-11e7-9989-ca0e03cb65c5.jpg)

When the deploy in our testing cluster are performed, he trigger our e2e tests and after perform our e2e test with success the job trigger the deploy in staging cluster.
But the "problem" is: we can't get the $BRANCH.$BUILD_NUMBER that are deployed in the testing cluster.
To be more clear: we deployed in test cluster the `versionName=develop.360` and after run the e2e tests we would liked to perform the deploy in staging cluster this same versionName (develop.360).

There's a way to perform this strategy or would you have another idea how to do it?

Best regards,
Christian Moretti

**Comment by manishas** [comment]
@christianmoretti you can specify your test-cluster-deploy job as an IN to your staging-deploy job with a switch: off. 

This will ensure that the staging-deploy job won't be auto-triggered after the test-deploy job, however, the manifest will still be available to staging-deploy when e2e-test job triggers it.

Let me know if that makes sense....

![image](https://user-images.githubusercontent.com/2983749/31958817-c38b6232-b8a7-11e7-99cc-3d8c40d6106c.png)

**Comment by christianmoretti** [comment]
Hi @manishas I'll perform some tests and I'll reply as soon as possible, thank you.

**Comment by christianmoretti** [comment]
Hi @manishas bellow follow the structure of this specific micro service, in this case I have one image/manifest/deploy to test and another image/manifest/deploy to staging.
I believe I did not understand very well how I will carry out the call to deploy in staging after running the e2e tests.
Could you help me if I'm doing something wrong?

**Comment by manishas** [comment]
@christianmoretti do you have time to jump on a quick call? Let me know and I can send you a link.

**Comment by christianmoretti** [comment]
@manishas Hi, of course, can please send the link?

**Comment by manishas** [comment]
I'll send you a meeting for 10:30am PST. what email can I send it to?

**Comment by christianmoretti** [comment]
@manishas Hi, christianmoretti@me.com

**Comment by manishas** [comment]
Thanks,
I sent you an email with the meeting link

**Comment by manishas** [comment]
@christianmoretti did you make this work? Let me know if you have any questions.

**Comment by christianmoretti** [comment]
@manishas Hey... sorry for the delay, but works. Many thanks for you time.

**Comment by xiaoxipang** [comment]
@manishas Is this documented somewhere? I'm really interested in the mechanism on this because I have the similar requirement.
I have two microservice A, B deployment pipelines that will try to deploy each service using image in staging. Then the E2E test will trigger to test against that. Whenever the E2E test finishs, I want to automatically trigger the same manifest/image to do other future steps. I don't want both A and B to do the future steps after E2E test. Only the related one that was deployed (which finishes the E2E) will trigger the future steps
