### ISSUE TITLE
Broken search link 403

### ISSUE THREAD

**Issue by dankonino** [Shippable/support#3918]
I searched for speed, and the second result is pointing to 403 page.

<img width="386" alt="screen shot 2017-10-24 at 8 56 56 pm" src="https://user-images.githubusercontent.com/8626427/31975280-0db36516-b8fe-11e7-885c-63d18f5451b6.png">

**Comment by manishas** [comment]
@ambarish2012 we need to fix this asap.

**Comment by ambarish2012** [comment]
@dankonino this issue is fixed.
