### ISSUE TITLE
Build stuck on provision job node

### ISSUE THREAD

**Issue by pat-nomalab** [Shippable/support#3920]
### Description of your issue:
Jobs are stuck at the state "provision job node" for more than 1h.
It's critical for us as we can't deploy new version to our servers

**Comment by mohit5it9** [comment]
@pat-nomalab We're looking into this. Will post an update soon

**Comment by mohit5it9** [comment]
We've identified a configuration issue in the stable machine image and that it's showing up as a problem today because of the unusually slow pull times from docker hub. We're actively working on resolving this.

**Comment by ric03uec** [comment]
@pat-nomalab this is fixed now. your builds should be running correctly.

**Comment by pat-nomalab** [comment]
it works, thanks
