### ISSUE TITLE
Add job tabs in order

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#3921]
Since [version 5.9.4 of the Shippable app](https://github.com/Shippable/support/wiki/5.9.4#features) job tabs are not shown by default and only created when clicking the jobs in the summary tab.

However, newly created tabs are simply placed next to the summary tab, regardless of their order in the summary tab. I think tabs should be added in the same order.

Steps to reproduce:

1. Have a build e.g. 3 jobs
2. Open the summary tab
3. Open job 3 and return to summary tab
4. Open job 1 and return to summary tab
5. Open job 2

Expected tab order:

| Summary | Job 1 | Job 2 | Job 3 |
| - | - | - | - |

Actual tab order:

| Summary | Job 2 | Job 1 | Job 3 |
| - | - | - | - |

**Comment by plessbd** [comment]
As a follow up to this, I liked that the job tabs were there by default without having to click each one.
Would be nice if the tabs were there, just not populated with information until clicked on.  Or at least if there are < X jobs (so you dont have to may tabs)

**Comment by mbrodala** [comment]
We won't be using Shippable anymore.

But thanks so far!
