### ISSUE TITLE
Awsebcli package issue

### ISSUE THREAD

**Issue by ricardoon** [Shippable/support#3922]
Hi,

It cant find awsebcli to install to deplay to AWS.

build_ci
sudo pip install awsebcli
Downloading/unpacking awsebcli
  Cannot fetch index base URL http://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement awsebcli
No distributions at all found for awsebcli
Storing complete log in /home/shippable/.pip/pip.log

For years I made deploys to AWS with shippable using it. How can I resolve this?

Run: 3675.1

**Comment by trriplejay** [comment]
Hello, sorry to see that you're having this error.  I notice that your build is running on our legacy image (shippable/minv2:latest).  We no longer maintain that build image and it's possible that some pieces of it have stopped working entirely.

If you haven't already, I'd recommend you update your shippable.yml to the new yml format described here: http://docs.shippable.com/ci/yml-structure/

Doing this should be enough to have your build automatically select a more up-to-date default build image.  Please let me know if that doesn't work, or if you have any questions about the new format.

**Comment by ricardoon** [comment]
@trriplejay thanks for the response. I'll try it.

**Comment by ricardoon** [comment]
It worked. Thanks.
