### ISSUE TITLE
phpunit - segmentation fault

### ISSUE THREAD

**Issue by atay** [Shippable/support#3923]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:
I'm getting the error:
```
 ./vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage 18s  
PHPUnit 4.3.5 by Sebastian Bergmann.

Configuration read from /home/shippable/workspace/src/github.com/Argo/phpunit.xml

......../home/shippable/03e0c365-9b36-4c79-882b-8440790bf2e3.sh: line 73:  1413 Segmentation fault      (core dumped) ./vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
```

- Link to the build failure
https://goo.gl/62NQUm
- Scripts called from the yml (optional)

**Comment by manishas** [comment]
@atay I see you’re using the build image minv2 which has been deprecated. Another customer also reported a segmentation fault while using an old image. 

Can you try switching to a newer machine image by going to your Subscription dashboard and navigating to Settings->Nodes->machine image  and try running your build again?  Instructions to change machine image are at http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-subscription-machine-image

**Comment by atay** [comment]
@manishas I've changed it, but when I build it, I still have:
```
pull_job_image
  shippable_retry sudo docker pull shippable/minv2:latest  
latest: Pulling from shippable/minv2
```

**Comment by manishas** [comment]
Do you have the image hard coded in your yaml? Can you paste the contents of your pre_ci_boot section?

**Comment by atay** [comment]
that's my `shippable.yml` file, I have nothing else configured:
```
language: php
php:
  - 7.1

install:
    - composer self-update
    - composer install -n

script:
    - ./vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
```

**Comment by manishas** [comment]
@a-murphy can you check why we’re still pulling minv2?

**Comment by manishas** [comment]
Actually, I just noticed that your yaml config is in the old format. Can you update it to the [shippable format](http://docs.shippable.com/ci/yml-structure/)? It will look like this:

```
language: php
php:
  - 7.1

build:
  ci:
    - composer self-update
    - composer install -n
    - - ./vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage
```

**Comment by a-murphy** [comment]
Projects enabled before March 2016 with YML in the old format will continue to use `shippable/minv2` by default because they were enabled before machine images were introduced,

The easiest solution is going to be to simply convert your `shippable.yml` to the new format.

**Comment by atay** [comment]
yep, works fine now, I need to test my code with less memory then
