### ISSUE TITLE
phpenv-install 7.0 - Definition 7.0 not found.

### ISSUE THREAD

**Issue by atay** [Shippable/support#3924]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:
```
/usr/local/bin/phpenv-install 7.0 0s  
[Error]: Definition 7.0 not found.
```

- Link to the build failure
https://goo.gl/PLS6bQ
- Scripts called from the yml (optional)
```language: php
php:
  - "7.0"
```

**Comment by manishas** [comment]
@atay please see my comment on your previous issue. Can you update your machine image to a newer version and try again?

**Comment by atay** [comment]
works fine now, thanks
