### ISSUE TITLE
Upgrade Maven version to 3.5.2

### ISSUE THREAD

**Issue by tmoreira2020** [Shippable/support#3925]
The current version of Maven is 3.2.5 which is almost 3 years old already. Please upgrade to at least 3.3.9 or the latest 3.5.2

**Comment by manishas** [comment]
@tmoreira2020 we have maven 3.3.9 in our latest machine images. Please follow [instructions here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-subscription-machine-image) to change your machine image to the latest one [5.10.4](http://docs.shippable.com/platform/runtime/machine-image/ami-v5104/)

**Comment by tmoreira2020** [comment]
It works, thanks!
