### ISSUE TITLE
rSync didn't added jobs from shippable.jobs.yml

### ISSUE THREAD

**Issue by navymaker** [Shippable/support#3926]
Hi,
I've tried to add Shippable pipeline for one of our project, but rSync didn't added any jobs from shippable.jobs.yml and marked all resources from shippable.resources.yml as orphaned.
Here is the link to rSync build:

https://app.shippable.com/github/openbridge/jobs/ob_api_rules_pipeline_rSync/builds/59f708dbe07b7707001894bf/console

rSync didn't shows any errors in logs and marked build as successfull.

Previously, for another our project with almost the same configuration except of name prefix for all jobs and resources, Shippable added all jobs successfully.

**Comment by Bharath92** [comment]
Could you please share your yml `shippable.jobs.yml` & `shippable.resources.yml` files to this email address bharath@shippable.com ?

**Comment by navymaker** [comment]
Just sent it, thanks!

**Comment by navymaker** [comment]
Issue was on my side, sorry about this.
