### ISSUE TITLE
GPG sign process

### ISSUE THREAD

**Issue by tmoreira2020** [Shippable/support#3928]
Hi there,

I'm working on move all my open source projects based on Maven from Travis to Shippable but I faced an issue where I need to sign off with GPG the artifacts (jars) produced by the build before send them to Maven Central repository.
Is there a best practice to do this? Where should I store the secrets?
The link below is a "How to" for Travis, is there any for Shippable?
http://www.debonair.io/post/maven-cd/

Thanks

**Comment by ambarish2012** [comment]
@tmoreira2020 you can define encrypted environment variables in your shippable.yml file similar to travis.yml.  Please look at [this document](http://docs.shippable.com/ci/env-vars/#secure-variables) for the steps to encrypt your data. This would be the simplest approach.

A cleaner and more sophisticated approach would be to define all your secrets in a key-value pair integration and to use this integration in your yml. All your secrets will automatically be injected as environment variables and you won't need to define them explicitly in your yml file.

I have created a working yml file you can look at [here](https://github.com/ambarish2012/key-value-sample/blob/master/shippable.yml). The console link for the repository, which has been enabled for CI in my shippable account is [here](https://app.shippable.com/github/ambarish2012/key-value-sample/runs/5/1/console).

**Comment by manishas** [comment]
@tmoreira2020 let us know if you need any more help with this. Closing.
