### ISSUE TITLE
Add support for Grails [Feature Request]

### ISSUE THREAD

**Issue by saurabh-agrawal83** [Shippable/support#393]
Please add support for Grails (http://grails.org) so we can use "grails test-app" to run the test cases in Grails projects. Grails can be installed using http://gvmtool.net or you can use Grails Wrapper (http://grails.org/doc/latest/guide/single.html#wrapper) without having to install Grails

Thanks

**Comment by manishas** [comment]
I am going to close this issue since this scenario was successful. We will update our docs with instructions on how users can use grails. Thanks for the help!
