### ISSUE TITLE
Delete all Shippable project fails

### ISSUE THREAD

**Issue by toanctruong** [Shippable/support#3930]
Disabling projects in the subscriptions area returns this error (does it for all projects):

<img width="420" alt="screen shot 2017-11-01 at 10 28 26 am" src="https://user-images.githubusercontent.com/12877463/32287914-7d7dfd38-beef-11e7-923d-4d9ff9399957.png">

We would like to disable, and remove all Shippable connections to our GitHub account. Thanks,

**Comment by trriplejay** [comment]
@toanctruong we're investigating this.

**Comment by trriplejay** [comment]
it looks like your account no longer has access to any projects or subscriptions on shippable. did you revoke access in your github settings? if so, then there's no additional action needed at this time.
