### ISSUE TITLE
Billing Info

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#3932]
Subscription Id: 573a53db2a8192902e204f23

We no longer have access to credit card and need to switch to invoice billing. How can we go about that?

**Comment by ambarish2012** [comment]
@pwarnock we are investigating.

**Comment by ambarish2012** [comment]
@pwarnock to change your billing data, go to your subscription, click on the gear icon and then on Billing. Let me know if you are having issues getting to this page.

**Comment by manishas** [comment]
@pwarnock please disregard the previous comment from @ambarish2012. The UI only supports credit cards as of now.  

If you want to switch to invoices, can you email me at manisha@shippable.com and we can get this set up?

**Comment by pwarnock** [comment]
Thanks @manishas
