### ISSUE TITLE
Slack notification shows different amount of tests compared to shippable console

### ISSUE THREAD

**Issue by dankonino** [Shippable/support#3934]
Cheers :)
I'd like to ask you for help with my issue which goes like this:
From CI we run a lot of tests. Everyone passes if I check the console.
```16 passing (122.60s)
03:14:59.986 INFO - To downstream: {"sessionId":"","status":0,"value":null}
Wrote xunit report to [./shippable/testresults].
Stopping Selenium server
cat: test/selenium/errors/error.log: No such file or directory
```
But the slack output shows different amount
can be seen here 
<img width="411" alt="screen shot 2017-11-02 at 11 49 12 pm" src="https://user-images.githubusercontent.com/8626427/32360011-7d23dfda-c028-11e7-9189-476343fb67df.png">
Please what can be the cause of this ? 
Don't hesitate to ask me more questions as I would like to see the correct number and can provide you with further information.
Thank you, dankonino

**Comment by trriplejay** [comment]
Can you provide a link to one of your builds?

**Comment by dankonino** [comment]
I'd like to but it's 404 since it's private company

**Comment by trriplejay** [comment]
Can you directly email me the link, or the ID from the URL of the job? john@shippable.com I think we'll be able to debug much better if we can take a look at the logs.

Based on what you've said so far, is it possible that the full results aren't being copied into the results directory? perhaps the report written in the end is just a subset of the total tests? maybe you can cat the xunit report? 

also, can you check the output of the "parse test reports" section of your logs? does anything in there seem off?

**Comment by dankonino** [comment]
Thank you, I'm looking at it will let you know with the update. I checked with my colleagues and maybe the very possible is that result is overridden in the process.

**Comment by manishas** [comment]
@dankonino let us know if you were able to resolve this.

**Comment by dankonino** [comment]
Yeah. I fixed it thanks @trriplejay @manishas. Was going bit crazy with this, but finally found that one of my tests weren't saving the result into root `shippable/testresults` but was deeper in the folder structure.  Had the similar project settings from previous one so firstly I was checking all of the results and had no idea what could be wrong with them. yesh :) 👍 
<img width="232" alt="screen shot 2017-11-13 at 3 58 08 pm" src="https://user-images.githubusercontent.com/8626427/32748856-77ffa7d0-c88b-11e7-96f5-fd1793fc55e5.png">
