### ISSUE TITLE
Bitbucket subscription deleted on its own

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#3935]
When I tried to log in to Shippable.com this morning, I was greeted with a weird screen and no subscriptions on the left hand side. A screenshot is attached below.

![shippable](https://user-images.githubusercontent.com/1606819/32361350-833f34ac-c085-11e7-8576-05dd0ff3cc9a.png)

After trying to logout and login several times and finding that nothing worked, I decided to check the Shippable.com issue tracker here on Github and found that others were facing similar problems (see #3933).

I had to perform the following steps to get access to my builds again:

1. Click on the `Profile` link on the left hand side.
1. Click the `Sync` button next to `Synchronize SCMs` label. Note that this will appear only if the account is linked to either Bitbucket or Github.
1. Logout.
1. Login.

This unexpected loss of access is worrying. Please look into this and ensure that it does not repeat.

**Comment by trriplejay** [comment]
@manish-in-java  sorry about this. it seems that some temporary issue prevented us from fetching your permissions from bitbucket at that time, but a subsequent force-sync brought them back.  We've got an internal issue to examine this and try to handle this case better in the future.

**Comment by manishas** [comment]
Closing in favor of https://github.com/Shippable/support/issues/3933 which is the same issue of customers needing to Sync after source control provider outages/connectivity issues.
