### ISSUE TITLE
Unable to access my organisation Repos 

### ISSUE THREAD

**Issue by asanchezgiraldo** [Shippable/support#3939]
Currently I am unable to log into shippable.

github account is asanchezgiraldo
bitbucket account is ale-san-gir

![image](https://user-images.githubusercontent.com/15203863/32423413-5d536b38-c2fa-11e7-9d03-33b7a389bae9.png)

**Comment by a-murphy** [comment]
Could you try going to https://app.shippable.com/logout (to clear the Shippable token stored by your browser) and logging in again?

**Comment by asanchezgiraldo** [comment]
thanks that worked for my bitbucket account but I am still not able to enable my github organisation repos

**Comment by a-murphy** [comment]
Could you clarify if you're able to see your GitHub projects, or log in with GitHub?  If your GitHub projects are missing entirely, clicking "sync" on the account profile page may help.  As far as I can tell, your account has access to enabled projects, so I'm not sure which projects you're having trouble with.

**Comment by asanchezgiraldo** [comment]
i can not see my organisation repos only my personal ones
![image](https://user-images.githubusercontent.com/15203863/32425482-7d279882-c307-11e7-9455-a21e105a62c7.png)

**Comment by a-murphy** [comment]
Your GitHub organization most likely has OAuth App access restrictions.  You should be able to go to your GitHub settings page (click your avatar on the top right on GitHub), then in the  "Applications" section, find "prod-shippable" under "Authorized OAuth Apps",and grant access to the organization you're not seeing.  If you're not an organization owner, you'll instead be able to request access and then an owner can [approve access](https://help.github.com/articles/approving-oauth-apps-for-your-organization/).  Without access to the organization, Shippable can't tell that it exists.

**Comment by asanchezgiraldo** [comment]
thanks, forgot I have to be an owner of the organization
