### ISSUE TITLE
Can't parse test results

### ISSUE THREAD

**Issue by gcoombe** [Shippable/support#3941]
Earlier today our builds started failing to parse test results.  We're a little confused because it started on a one line code change totally unrelated to our tests.

We see the is input during the "parse test reports" step:
reports --destination /shippableci/testresults tests --source /root/src/github.com/gcoombe/fetch-home/shippable/testresults 0s  
time="2017-11-07T19:44:49Z" level=error msg="No valid test parser : /root/src/github.com/gcoombe/fetch-home/shippable/testresults/result.xml" 
time="2017-11-07T19:44:49Z" level=fatal msg="Unable to parse XML content" 

Here is a link to the run where it started failing: https://app.shippable.com/github/gcoombe/fetch-home/runs/2703/1/console

Any guidance on further steps to debug and fix would be greatly appreciated.

**Comment by a-murphy** [comment]
As far as I can tell, your tests ended suddenly and there most likely wasn't a valid results file.  The `Finished 'test:run:ci'` line in your previous successful runs is missing.  There's also an error with `sass` in your postinstall in the failed run that may be related.

Could you try re-running a successful run?  If a previously successful commit starts failing, it usually means that a dependency, such as a node module, has been updated and isn't compatible with something.  And if it succeeds, then it's more likely something that was committed.

**Comment by gcoombe** [comment]
Hey there, so I did a run with ssh turned on and found that the results file is being written, but its written to /shippableci/testresults/testresults/results.xml which is not where shippable is looking for it.

The test run has the env var XUNIT_FILE=shippable/testresults/result.xml set so I am not sure how it's ending up there.

**Comment by a-murphy** [comment]
Shippable moves the results from `shippable/testresults` to `shippableci/testresults` in the "parse test reports" step.  Did you check if the contents of the test results file looked valid?  Given the error message, it's finding the file and can't parse it.  This could be because it's not valid XML or because it just doesn't match any supported test result formats.

**Comment by gcoombe** [comment]
I did run an old build that succeeded and it now fails.  The report looks valid to me.  I do see that  the file is at "/shippableci/testresults/testresults/results.xml" (notice that it's nested under 2 testresults directories). Is that expected?

**Comment by gcoombe** [comment]
Very strange.... all of a sudden it's started parsing my reports again.... Can't explain it but I'll close since it's working now :)

**Comment by a-murphy** [comment]
The doubled `testresults` in the path to the report file is typical and not a problem.

I've opened an internal issue to look into the parsing failure more closely in case it appears again in the future.  At this point, I suspect that it's something about the output saved for one of your previously failing tests.

**Comment by gcoombe** [comment]
Great! Thanks for all your help, much appreciated.  👍
