### ISSUE TITLE
Error: Cannot add runCI job, please enable the project before adding job

### ISSUE THREAD

**Issue by danielmenezesbr** [Shippable/support#3944]
When i try to "ADD A SYNC REPOSITORY" the build fail with the message: "Cannot add runCI job, please enable the project before adding job".

Note: My project was enabled before "ADD A SYNC REPOSITORY"

Build Id: 5a036392e07b7707001f2f91
Subscription Id: 58cd4bc8a99a110500e1fa4e

**Comment by trriplejay** [comment]
it looks like the name of the ciRepo you've added to yml does not match the name of the enabled project.  You can see in the "resources" table, in the "name" column what the name should be in the yml so that it matches.

**Comment by danielmenezesbr** [comment]
You are right!
Thanks!
