### ISSUE TITLE
Can't figure out how to push to a second GitHub repository in post_ci

### ISSUE THREAD

**Issue by wwerner** [Shippable/support#3945]
I'm trying to push some code to a different GitHub repository in post_ci.
Let's call the repository I am building `R1` and the one I want to push to `R2`.

I have set up the following:
* GitHub Subscription contains both `R1` and `R2`
* The deployment key of the subscription is added to deployment keys in GitHub in `R2`
* The build sets up the remote for `R2` using `git remote add origin git@github.com:my-org/my-repo.git`
* The build calls a script that tries to push to `R2` using `ssh-agent bash -c "ssh-add /tmp/ssh/01_deploy; git push origin develop"`

I verified that the referenced key `/tmp/ssh/01_deploy` is present.
Adding `git remote -v` to the push script verifies that the correct origin url is getting set.
I tried both `git@github.com:org/repo` and `ssh://git@github.com/org/repo` forms of the origin url.

Here's what git says:
````
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
````

I also tried the the SSH key integration to no avail.
I figured that the approach using `ssh-add ~/keys/id_${JOB_ID}` is outdated, correct?

Any pointers? Am I missing/misunderstanding sth.? 
Thanks in advance.

**Comment by a-murphy** [comment]
Deploy keys don't usually have write access.  However, GitHub has a checkbox to give push access to a deploy key when you add it.  Could you check that this box was checked?  It should say "read/write" in the list of deploy keys for the repository on GitHub.

**Comment by a-murphy** [comment]
Sorry, you should also be using `00_sub` instead of `01_deploy` in your command to specify the subscription SSH key.  `01_deploy` is a deploy key added to the project, and `00_sub` is the one on the subscription settings page.

**Comment by wwerner** [comment]
Ok, the deploy key had r/w access.
I'll try now with the 00_sub key.

**Comment by wwerner** [comment]
Ok, using the correct key fixed it.
Thanks a bundle!
👍
