### ISSUE TITLE
Unable to pull latest repository 

### ISSUE THREAD

**Issue by libin-n-g** [Shippable/support#3946]
## pull_job_image
shippable_retry sudo docker pull libinngeorge/mycompiler:latest 3s  
Error response from daemon: repository libinngeorge/mycompiler not found: does not exist or no pull access
retrying 1 of 3 times...
Error response from daemon: repository libinngeorge/mycompiler not found: does not exist or no pull access
retrying 2 of 3 times...
Error response from daemon: repository libinngeorge/mycompiler not found: does not exist or no pull access
retrying 3 of 3 times...

**Comment by libin-n-g** [comment]
mycompiler Repository  is a private repository and the url is https://bitbucket.org/libinngeorge/mycompiler

**Comment by a-murphy** [comment]
It looks like you're trying to use a private image for your build.  You'll need to add an integration to the `integrations` section in your `shippable.yml` to give your build permission to pull the image.  Directions are available here: http://docs.shippable.com/ci/custom-docker-image/#pulling-a-private-image

**Comment by libin-n-g** [comment]
Thanks for your Help
