### ISSUE TITLE
builds available (free plan)

### ISSUE THREAD

**Issue by danielmenezesbr** [Shippable/support#3947]
In the *free plan* (limited 150 builds per month) is there any way to see how many builds are still available in the current month?

**Comment by manishas** [comment]
There is currently no way to see how many builds are remaining. You do get a notification once you get the limit. 

It is a great idea however so I’ll mark it a feature request.

**Comment by trriplejay** [comment]
@danielmenezesbr this feature is now available. You should see your remaining available private jobs at the top of your subscription page, as well as the top of any private project individual page.

**Comment by Borda** [comment]
@trriplejay How shall I understand the "150 builds/month for private projects" in free plan? 
Because after the first month I have 0 builds available already for three mons in a row...

**Comment by trriplejay** [comment]
@Borda can you provide your organization name or id? The count should automatically reset to 150 once per month.  Each build you run will use up 1.  Once the counter reaches 0, jobs will be skipped and should have a relevant message saying the quota is used up. Do you think yours is remaining 0 in error?

**Comment by Borda** [comment]
@trriplejay https://app.shippable.com/subs/github/Borda/dashboard , is it enough? :)

**Comment by trriplejay** [comment]
it definitely looks like something is wrong here, we're investigating.

**Comment by trriplejay** [comment]
@Borda I've manually set your capacity back to 150 for this month while we investigate what could have caused this. Please let me know if you experience this again.
