### ISSUE TITLE
NodeJS: Semantic Release fails with "Not running in Travis after_success step"

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#3948]
While using semantic-release in our after_success functions on Shippable used to work, it appears the latest version of semantic-release is expecting an environment variable to tell it that it is running in the after_success or after_failure section of a travis config. 

The latest semantic-release is looking for a variable called TRAVIS_TEST_RESULT to be set to 1 when running in after_success.

**Comment by trriplejay** [comment]
We don't internally set that travis variable, but you could set it yourself as a line in your yml for that section before executing semantic-release. would that work?

**Comment by ryan-kimber** [comment]
We’ve changed to using a no-op verifier for Semantic Release.

It might be worthwhile for Shippable to provide a shippable verifier to
semantic-release, as the default is definitely picking up the TravisCI
variables you do set and going into Travis mode. Semantic release has
become really popular in nodejs projects, and I can imagine people wasting
a lot of time on this (our team has been trying to address this for 2 days
before figuring it out).

Happy to contribute how we got it working, if that’s of use.
