### ISSUE TITLE
shippable.resources.yml deprecation

### ISSUE THREAD

**Issue by brentfamily1** [Shippable/support#3949]
### Description of your issue:
I noticed the documentation was updated to state the shippable.resources.yml will be deprecated.  http://docs.shippable.com/platform/tutorial/workflow/shippable-resources-yml/#anatomy-of-shippable.resources.yml

We currently have scripts that rely on environment variable names based upon the resource name.  The scripts are shared across repositories which helps prevent code duplication and makes maintenance easier.  If the shippable.resources.yml goes away, will there be an alternative way to share a resource across repositories?

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by manishas** [comment]
@brentfamily1 the deprecation isn’t going to happen anytime soon and we’re definitely looking for feedback on this. 

I’m going to make sure The docs are updated ASAP. I apologize for the confusion.

**Comment by trriplejay** [comment]
we've basically consolidated all of the functionality of `shippable.resources.yml` into `shippable.yml` as documented here: http://docs.shippable.com/platform/tutorial/workflow/shippable-yml/

These resources can still be shared across repositories. If you choose to move your resources into a shippable.yml, you should see no impact at all, but it's also fine if you choose to keep shippable.resources.yml.  We don't plan to remove support for that any time soon.

**Comment by brentfamily1** [comment]
@trriplejay how should we setup a shared git repo resource scenario when the resources are only able to be defined within a shippable.yml?  The bash scripts that I have in this repo assume a given resource name to access environment variables such as <RESOURCE_NAME>_STATE.

I tried to name the resource the same across shippable.yml files for each repo, and Shippable presented me with a naming conflict issue.

**Comment by trriplejay** [comment]
you still only have to define it in a single shippable.yml file, and it will add the resource to the subscription, which shares it across any repositories in that subscription, so that any job can use it as an IN.  just like with shippable.resources.yml, it only has to be defined once.

**Comment by brentfamily1** [comment]
Ah, got it.  Thanks!

**Comment by manishas** [comment]
The deprecation notice has been removed. While we will continue to support `shippable.resources.yml` and `shippable.jobs.yml`, our recommended approach is now to include everything in `shippable.yml` files.
