### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by SahithiGagganapally** [Shippable/support#3950]
Hi, 
I am trying a run a simple java program pulling a docker image and trying to save the artifacts created within the container using  
- docker commit $SHIPPABLE_CONTAINER_NAME docker-hub-org/java:latest
- docker push docker-hub-org/java:latest
some how i'm facing different issues everytime i run yml file.
Error: Invalid integration myIntegration specified for integration type : hub

Thanks,
sgagga

**Comment by a-murphy** [comment]
Does your subscription have an integration with that name?  It should be listed on the integrations page for the subscription (click on the subscription name on the left sidebar, then the gear on the top right, and "integrations").

If there is no subscription integration, [these directions to add a subscription integration](http://docs.shippable.com/platform/tutorial/integration/howto-crud-integration/#adding-integration-to-a-subscription) may help.

If it is a subscription integration, what is in the "type" column?  It may be that the integration type isn't valid as a "hub" integration and a different type should be selected.

**Comment by SahithiGagganapally** [comment]
Hi,
I have added the integration in my settings, now when i'm running my yml file it is skipping the pre_ci and post_ci part in the build section.
not sure if i'm doing something wrong.

also can i know if there is a way integrating shippable with Nexus?

Thanks,
sgagga

**Comment by a-murphy** [comment]
Could you check if your shippable.yml file is structured as described [here](http://docs.shippable.com/ci/yml-structure/)?  It sounds like you might either have two `build` sections (in which case they should be combined) or `pre_ci` and `post_ci` might not be indented correctly under the `build` section.

We don't currently have a native Nexus integration; it's in our backlog.  You can, however, use a [key-value pair integration](http://docs.shippable.com/platform/integration/key-value/) to store your Nexus credentials.

**Comment by SahithiGagganapally** [comment]
I can only see Aws, Github, Kubernetes and docker private registry in my subscription page, Am I missing anything?

**Comment by a-murphy** [comment]
If you're trying to add a key-value pair integration, you can click on the + at the top of the panel.  This will allow you to add a new integration.

Or if this is about the original integration that wasn't found, there shouldn't be more than one subscription integration with the same name in a subscription.  Is the one in your `shippable.yml` there?  It doesn't sound like your missing anything if it is.

Would you mind including the subscriptionId from the bottom of the page to make easier for us to see what you're running into?

**Comment by SahithiGagganapally** [comment]
shippable id : 5a0240878aef1a0f0028ac69

**Comment by a-murphy** [comment]
I couldn't find that ID.  Are you using a Shippable Server installation (not shippable.com)?  If so, do you mean that the key-value pair integration isn't in the dropdown list?  You might need to enable the integration type in Admiral on a Server installation.

**Comment by manishas** [comment]
@SahithiGagganapally was this resolved? Please let us know...

**Comment by SahithiGagganapally** [comment]
We're planning on upgrading our current shippable server installation and my higher management is in process of getting that, will reach out if we have any other issues.
you can close this for now.

Thanks
