### ISSUE TITLE
Doc Issue

### ISSUE THREAD

**Issue by brentfamily1** [Shippable/support#3951]
### Description of your issue:
On this page, http://docs.shippable.com/platform/workflow/job/release/, the YML Definition example does not match the text of "type -- is set to manifest".

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by manishas** [comment]
Thanks for reporting the typo. We’ll get it fixed ASAP.... it should say ‘type — is set to release’
