### ISSUE TITLE
Deploying to a linux server

### ISSUE THREAD

**Issue by reflash** [Shippable/support#3952]
Hello,

I cannot find any tutorial on how to deploy to a simple Linux server, without any additional installations like Dokku on it. Can you, please, help me with some notice on how to do that in a right way.

**Comment by manishas** [comment]
@ambarish2012 can you help?

**Comment by ambarish2012** [comment]
@reflash I sure can help. What are you trying to deploy to the Linux server?

**Comment by reflash** [comment]
@ambarish2012, I have to deploy the source code with Python/Flask app and then run a shell script for restarting the app which will run few python scripts, restart queues, etc.

**Comment by ambarish2012** [comment]
@reflash you can take a look at this document - http://docs.shippable.com/deploy/vm-basic/. 

In this example, the source code of the application is tar'ed and located in S3 and is deployed to a VM. You can tweak this example to pull the source code and scripts from wherever your application is located and deploy it to your Linux server as long as your server has a public IP and port 22 is opened. 

Let me know if you want to jump into a quick call to discuss your  scenario after you read the document, if you have additional questions.

**Comment by reflash** [comment]
@ambarish2012 Do I correctly understand you, that I have to tar my current build and then do the same steps?
I've seen this example before, but not quite sure how to apply it to my scenario

**Comment by ambarish2012** [comment]
@reflash tarring the build and making it available in some cloud share in one way you could do. Where is your source code and how do you deploy to your VM today? Once i understand that, i can recommend a solution. You can email me the details at ambarish@shippable.com.
