### ISSUE TITLE
"No such file or directory" after mkdir -p

### ISSUE THREAD

**Issue by jforissier** [Shippable/support#3953]
I am experiencing random build failures with "No such file or directory" 

- Parallel build is used (`make -j $(getconf _NPROCESSORS_ONLN)`). I could not reproduce the issue without the `-j` option.
- Error is reported either by `bash` (when trying to redirect output to a file AFAICT), or by `mkdir`.
- The logs show that the two commands that are launched in parallel by the Makefile are essentially: `mkdir -p out/arm-plat-xxx/core` and `mkdir -p out/arm-plat-xxx ; echo "Blah" >out/arm-plat-xxx/conf.mk.tmp`. One of those commands fails sometimes (but not always). For instance, builds 110 to 113 are OK but build 114 failed, all on the same commit.

Links to failed builds:
https://app.shippable.com/github/jforissier/optee_os/runs/109/summary/ (`bash` error)
https://app.shippable.com/github/jforissier/optee_os/runs/114/summary/ (`mkdir` error)

I can't find any problem in the project Makefiles. I have never observed the error in other environments (Travis CI for instance). Any idea what could be wrong?

**Comment by a-murphy** [comment]
Since `mkdir -p` is not an atomic operation, the concurrent commands are most likely both trying to create `out/arm-plat-xxx`.  Perhaps you have a different number of commands run in parallel in other environments so that these commands don't usually execute at the same time.  If you can, I would suggest changing your scripts so that  multiple `mkdir -p` commands that could create the same directory will not be executed at the same time.

**Comment by jforissier** [comment]
Thanks for your reply, but I don't think it makes sense. OK, `mkdir` is not atomic when several levels are involved. But it doesn't explain why the error code is ENOENT. I would understand EEXIST, but I fail to see how ENOENT could come up. And EEXIST is supposedly handled properly by GNU `mkdir`.

I will write a stress test and try using strace to figure out what is really happening.

**Comment by manishas** [comment]
@jforissier were you able to find out why this was happening?

**Comment by jforissier** [comment]
@manishas no, unfortunately I could not reproduce the issue with `strace` or `mkdir` verbose flag. I ended up disabling parallel build, an splitting our tests between Shippable and Travis.
