### ISSUE TITLE
Cannot enable a repo, "deleteResourceById failed" error

### ISSUE THREAD

**Issue by AlekseyMartynov** [Shippable/support#3956]
> deleteResourceById failed for id: 40469 returned error deleteVersionById for versionId: 1980879 returned error: versions.destroy failed for versionId: 1980879 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"

**Comment by a-murphy** [comment]
It looks like you previously enabled a different project with the same name and those resources were creating conflicts.  I've removed the problematic resources and you should be able to enable your project now.

**Comment by AlekseyMartynov** [comment]
Problem's gone. Thanks.
