### ISSUE TITLE
Can we change the email from which shippable is sending emails?

### ISSUE THREAD

**Issue by SahithiGagganapally** [Shippable/support#3959]
Hi,

How do I change the email from which shippable is sending notifications, right now I'm receiving the emails from noreply@org.com and I want to change it to shippable@org.com.

Thanks

**Comment by a-murphy** [comment]
I'm assuming you must be using a Shippable Server installation.  If you log into the Admiral Admin panel for your installation, the "Configure & Install" panel has a section for email.  You should be able to change the "email sender" there.  After changing it, make sure to click "save" at the bottom of the panel.

**Comment by SahithiGagganapally** [comment]
Yes, we use shippable server installation.
I can see "configure" option in admin panel but no where i found email section in it.

**Comment by a-murphy** [comment]
Which version is your installation?  If you click on the config button next to "Admiral Environment" in the first panel on the page, the version should be listed the the popup as "release."

Most versions will have an "email provider" section with Gmail, Mailgun, and SMTP options in the Configure & Install panel, near the bottom of the panel.

**Comment by SahithiGagganapally** [comment]
Not sure why I'm unable to find anything, I now see SMTP option in Master Integrations page but option of editing is grayed out.

**Comment by a-murphy** [comment]
Only one email provider can be configured at a time.  If you have a different provider selected and want to switch to SMTP, you should be able to uncheck the box next to that provider and then select SMTP.

**Comment by manishas** [comment]
@SahithiGagganapally can you reach out to ambarish@shippable.com and manisha@shippable.com with details on this issue? It might be quicker to jump on a call and resolve this. 

Also, our Server customers have access to a private ticketing system so if you’re running Shippable Server, we can get you set up with that.
