### ISSUE TITLE
gcloud app deploy doesn't finish before build marked as failed

### ISSUE THREAD

**Issue by sheats** [Shippable/support#3960]
### Description of your issue:
Build Failure: https://app.shippable.com/github/sheats/ai/runs/28/1/console
Scripts: 
    - mkdir -p $SHIPPABLE_REPO_DIR/credentials
    - supress=$(echo $GCLOUD_SERVICE_ACCOUNT_KEY > $SHIPPABLE_REPO_DIR/credentials/gcloud.json)
    - gcloud -q auth activate-service-account --verbosity=debug --key-file $SHIPPABLE_REPO_DIR/credentials/gcloud.json
    - gcloud config set project <project-id>
    - yes | sudo apt-get update && sudo apt-get --only-upgrade install kubectl google-cloud-sdk google-cloud-sdk-datastore-emulator google-cloud-sdk-pubsub-emulator google-cloud-sdk-app-engine-go google-cloud-sdk-app-engine-java google-cloud-sdk-app-engine-python google-cloud-sdk-cbt google-cloud-sdk-bigtable-emulator google-cloud-sdk-datalab
    - gcloud config list
    - gcloud version
    - gcloud --quiet app deploy $SHIPPABLE_REPO_DIR/app.yaml --log-http --verbosity=debug

Was hitting other errors before and got them all resolved.  But now it seems like the build process just swallows up that last command while it uploads to google storage before it finishes and proceeds to mark build as failed.  There are no apparent errors displayed and the "build_on_success" never gets a green check mark or a red error x.

**Comment by trriplejay** [comment]
We have a known bug where rapid logging can occasionally cause the build container to crash. could you try reducing the vebosity of your logging for that gcloud command to see if that helps?

**Comment by sheats** [comment]
That seemed to do it thanks!  I added the additional logging to figure out the other issues, funny that it caused it's own issue.

**Comment by manishas** [comment]
Glad it worked! Closing this issue since the logging issue is already being tracked internally.
