### ISSUE TITLE
Miss existing gitlab integration

### ISSUE THREAD

**Issue by Cr1stal** [Shippable/support#3962]
Hello. Missed gitlab integration in my account. Please help.

**Comment by a-murphy** [comment]
It looks like your account has two GitLab integrations for the same URL.  This is very likely to cause problems when synchronizing your account.  Could you delete one on the account integrations page and click the sync button on the account profile page?

**Comment by Cr1stal** [comment]
Done. But nothing changed.

**Comment by jatindogra** [comment]
Hi, @Cr1stal you should do a sync, you gitlab integrations should work now. Sorry for the inconvenience.
