### ISSUE TITLE
Support Azure Container Service (AKS)

### ISSUE THREAD

**Issue by seniorquico** [Shippable/support#3963]
Microsoft has added a GKE-like environment to Azure called Azure Container Service (AKS). This _isn't_ deployed or managed like their previous container service, ACS. AKS is currently in public preview, and it would be awesome to get support for this newer environment on the Shippable roadmap.

AKS relies on the Azure CLI to download a set of Kubernetes credentials and to automatically setup the local kubectl configuration files. After that, all cluster management is done via "vanilla" kubectl commands.

I currently believe the only necessary change is an upgrade of the Azure CLI in the Shippable machine image. The Azure CLI version must be >=2.0.20 to use the new "aks" command namespace (latest published version is 2.0.21; current version in Shippable machine image v5.10.4 is 2.0.19). However, I'm not familiar with the other GCE/GKE/K8s-related integrations in Shippable, so I'm not sure if there are other opportunities to streamline the AKS experience in Shippable. I'd love to hear if there are any interesting things to consider with this new workflow.

Finally... a small documentation error: The [v5.10.4 image documentation](http://docs.shippable.com/platform/runtime/machine-image/ami-v5104/) appears to be listing the Azure CLI version as 2.**_10_**.19 instead of 2.**_0_**.19.

**Comment by manishas** [comment]
This is definitely on our radar and I’ll discuss internally and get back to you with some concrete details. 

Regarding updating azure CLI, we update our images every month and I’ll make sure this is included with the next update.

**Comment by manishas** [comment]
Azure CLI with support for AKS has been on our images since version 6.1.4+ http://docs.shippable.com/platform/runtime/machine-image/cli-versions/
'
Closing this issue since the [runSh job](http://docs.shippable.com/platform/workflow/job/runsh/) can be used to deploy to AKS now.
