### ISSUE TITLE
React-scripts: not found 

### ISSUE THREAD

**Issue by dankonino** [Shippable/support#3965]
Hi guys,
I have one let's say _silly question_, but I need to ask that since it's more of **paranormal** to me.
Last day **react-scripts were not found**. I was wondering what in my code could broke it, (locally nothing).
Then after longer deeper search I wasn't able to find out anything changed with this.
I switched to last working build on shippable where the was no error, hit rebuilt and boom I see this now. 
If you can confirm it should be working, we can close this and I will need to figure this one out, but still don't know what could cause this.
Thanks

**Comment by a-murphy** [comment]
This sounds like the kind of error that will appear if you have a node module installed locally that you aren't installing in your shippable build.  I would suggest trying to run it locally starting from your `npm` or `yarn` install command without a `node_modules` folder to make sure you're comparing with all the same package versions.  It might also be worth checking if you have anything installed globally that you've forgotten about.

**Comment by dankonino** [comment]
Thank you so much, it can be one forgotten module . I will check this since it will be probably that.

**Comment by dankonino** [comment]
@a-murphy I hoped it's the forgotten module you mentioned but it's not.  And trying to compare with global npm is hard. I'll keep on going with this.

**Comment by a-murphy** [comment]
Did you check the versions of the node modules you're installing?  Sometimes a new version of a node module won't have the same dependencies as the previous versions and so the previous dependency will stop being installed without any changes to the `package.json` in your project.  Of course, if you ran `npm install` without a `node_modules` folder and it still works, it's more likely something installed globally.

**Comment by dankonino** [comment]
I guess it's not your problem though, even it seemed like it..
I keep on pushing, just updating the newest version of react scripts. And will see how the shippable accept that :) 
thanks for good hints & info

**Comment by dankonino** [comment]
Yeah as Dan Abramov mentioned, it was caused by old npm version. My node for heroku was 8.1.4 which was using older npm `5.0.3 ` and I just set the project to 8.8.0 as we have shippable set know and it works with `react-scripts` perfectly again
