### ISSUE TITLE
Document minimum requirements of custom Docker images

### ISSUE THREAD

**Issue by cjerdonek** [Shippable/support#3966]
In the section of the documentation [here](http://docs.shippable.com/ci/custom-docker-image/) on "Using a custom Docker image," there doesn't seem to be any information about the minimum requirements of a custom Docker image.

However, in [this comment](https://github.com/Shippable/support/issues/3723#issuecomment-316122258) some of the minimum requirements are described, e.g.

> Ubuntu is not required, however some features may not work as intended with other operating systems. For instance, since you don't have apt-get installed, the dependencies for the build runner are not automatically installed. Could you check that your image has sudo, git, ssh-agent, and Python 2.7 installed?

I think it would be good if the documentation said something about the minimum requirements. Otherwise, people more or less just need to guess. Thank you.

**Comment by manishas** [comment]
great suggestion. ... not sure how we missed that :(

**Comment by cjerdonek** [comment]
Also, in terms of minimal requirements, is it meant to be the case that the dry-dock "base images" satisfy the minimal requirements, like for example the https://github.com/dry-dock/u16 image? If so, that would be good to document, too. Thanks.

**Comment by manishas** [comment]
@cjerdonek Yes, the base images already satisfy the requirements of a custom image. We'll get that updated too.

**Comment by manishas** [comment]
This is complete: http://docs.shippable.com/ci/custom-docker-image/#minimum-requirements
