### ISSUE TITLE
mvn:command not found

### ISSUE THREAD

**Issue by SahithiGagganapally** [Shippable/support#3967]
Hi,

I 'm trying to build my pom.xml through shippable.yaml and i'm coming across the error mvn:command not found.
I'm using our custom java docker image for that, is that something to do with maven installation?
pls help,

Thanks

**Comment by a-murphy** [comment]
Since you are using a custom image, you will have to either install Maven in your image or add Maven installation commands to your `shippable.yml`.  Maven is installed in the default Shippable Java images, but we don't know how or if you would want it installed in your own image.

**Comment by SahithiGagganapally** [comment]
Thanks
