### ISSUE TITLE
Update nvm in dry-dock/u16

### ISSUE THREAD

**Issue by seniorquico** [Shippable/support#3968]
It appears the base image "u16" uses nvm 0.33.0. That release is dated Dec 29, 2016. Is it possible to get a newer version included in one of the next image builds? I've run into a few nvm bugs specific to my build scripts that have since been resolved. The current version is 0.33.6.

Reference: https://github.com/dry-dock/u16/blob/master/node/install.sh

Thanks in advance for your consideration!

Kyle

**Comment by ambarish2012** [comment]
@kyle I have submitted your feature request. In the meantime, you can update nvm using `sudo nvm  install <your version>` in your shippable.yml file.

**Comment by manishas** [comment]
The latest images (6.4.4+) have 0.33.9. Closing this issue.
