### ISSUE TITLE
support alias in Dockerfile

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [Shippable/support#3969]
Regarding Dockerfile, it's (optionally) possible to support

`FROM src_image:version AS alias`

`COPY --from=alias src dst`
 
Shippable does not support it. And it's very usefull to copy the result into a clean container.
Do you think you can support that ?

Best regards,
Marc-Antoine

**Comment by manishas** [comment]
@MarcAntoine-Arnaud this is supported from docker 17.05 onwards. You'll need to select machine image 5.8.2+ http://docs.shippable.com/deploy/why-deploy/

Instructions are here http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-subscription-machine-image
