### ISSUE TITLE
Unable to access Shippable

### ISSUE THREAD

**Issue by DHansenOmadi** [Shippable/support#3970]
I have been unable to access Shippable 

I am getting the following error:
```
Error

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.
```
I also see that the only permission granted to the "prod-shippable" application in github is "Access public information (read-only)"

I have revoked access to the application and tried again.

Will you help me understand why I may be getting this error?

**Comment by ambarish2012** [comment]
@DHansenOmadi i have unblocked your account. Did you create a new github account and use it to sign into Shippable? Such accounts do get flagged, since we have seen malicious users create new accounts and use them to spam our system.

**Comment by DHansenOmadi** [comment]
I did create a new account and joined as part of joining a new company.

Looks like I have access now, thank you.
