### ISSUE TITLE
Account locked for security violation

### ISSUE THREAD

**Issue by partridgeShippable** [Shippable/support#3972]
### Description of your issue:
I believe this is linked to the issues [here](https://github.com/Shippable/support/issues/3971) and [here](https://github.com/Shippable/support/issues/3957) but i've just enabled my an account with Github repo, having already had a Bitbucket account repo enabled. 

Can I also enquire whether Shippable supports [machine users](https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users) for the oauth2 stuff? This looks like the only way to cherrypick repos which, as you mention in your [support page](https://www.shippable.com/security.html), is all-or-nothing otherwise

**Comment by ambarish2012** [comment]
@partridgeShippable I have unblocked your account.

**Comment by partridgeShippable** [comment]
For anyone stumbling on this it does indeed seem possible to create a machine user, add it as a "contributor" to the private repos you want shippable to access then use this user with Shippable
