### ISSUE TITLE
Split accounts

### ISSUE THREAD

**Issue by partridgeShippable** [Shippable/support#3973]
### Description of your issue:
Hi there. I have an existing account which was pointed towards Bitbucket. The account number is "579f1f0bf8e06c0c001d1df4". I have migrated my repos to GitHub with the understanding that i could simply add the subscription to GitHub and have them "come together" in shippable

Things may be a little more unusual in that this GH account (partridgeShippable) is a [machine user](https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users) that is defined as a collaborator against the repos i want to expose. The "repository owner" for GH is "elmpp". 

Can my accounts be "merged" somehow? I would also like to keep my current plan from BitBucket (2 minions with the first free). If this is not possible, i would like please for this deal to be applied to this subsciption please.

**Comment by ankul-shippable** [comment]
@partridgeShippable We are looking into it. We'll get back to you once we have figured out if it is possible.
Thanks

**Comment by elmpp** [comment]
Thanks, it would be most pleasing.

**Comment by manishas** [comment]
@ankul-shippable can you post a follow-up for this issue?

**Comment by elmpp** [comment]
I'd like to know if this is possible please

**Comment by rageshkrishna** [comment]
Hi @elmpp. Sorry for not getting back sooner. Let me see if I understand the situation correctly:

- You currently have a BitBucket subscription with a free minion deal
- You have moved your repos over to GitHub org `elmpp` and you are signing in to Shippable with the `partridgeShippable` GitHub account
- You would like the free minion deal to be transferred from your BitBucket subscription to `elmpp`

Please clarify if this captures what you are looking for. Thanks!

**Comment by elmpp** [comment]
OK, so the order was:
 - You currently have a BitBucket subscription with a free minion deal
 - You have moved your repos over to GitHub org `elmpp` and you are signing in to Shippable with the `partridgeShippable` GitHub account (which is a machine user to some of my repos)

However, i have been told that i needn't worry about restricting access only only those repos and can sign in as `elmpp`. I guess the ultimate issue then now is can my free minion deal be applied to the `elmpp` account please. Thanks.

**Comment by elmpp** [comment]
I assume that once the account is ported over i will be able to kick off builds using the API?

`
Could not json decode the response or imvalid key used. Raw: "{"logType":"warn","methodName":"projects|triggerNewBuildRequest|projectId:5a0f3f8779f26b0700c222aa|_queueRun","id":2000,"message":"postRun for :projectId 5a0f3f8779f26b0700c222aa returned error: access denied to route: /runs"}"
`

**Comment by rageshkrishna** [comment]
@elmpp, got it. Here's what you need to do:

1. Downgrade your Bitbucket subscription on Shippable to a free plan
1. Buy a single minion on your GitHub subscription

Once you confirm that this is done, I can apply the free minion offer on your GitHub subscription.

**Comment by elmpp** [comment]
I've now done that. Thanks.

**Comment by rageshkrishna** [comment]
Hi @elmpp. You should be able to use 2 minions now. Let me know if you don't see it.

**Comment by elmpp** [comment]
yep, all good. Thanks

**Comment by elmpp** [comment]
Hi there, thought i'd tag this on here as the context is all above.

This new paid account should give me API access, correct? I am seeing the following problem:

`
[error]  Could not json decode the response or imvalid key used. Raw: "{"logType":"warn","methodName":"projects|triggerNewBuildRequest|projectId:5a0f3f8779f26b0700c222aa|_queueRun","id":2000,"message":"postRun for :projectId 5a0f3f8779f26b0700c222aa returned error: access denied to route: /runs"}"`

This is using a new API key for this account. The project IDs seem correct??
