### ISSUE TITLE
E: Unable to locate package postgresql-9.6-postgis-2.3

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#3974]
Hello,

I need help in fixing the broken build. Any ideas what is wrong?

https://app.shippable.com/github/mikkopori/enterlot/runs/684/1/console

Br,

Mikko

**Comment by ankul-shippable** [comment]
@mikkopori I see that you are trying to build an image using `ubuntu/devel` and it recently started failing.
Did the base image change or did you change anything in your Dockerfile?

**Comment by mikkopori** [comment]
I did not, and locally it builds ok.

But for some reason building the same image in Shippable points to bionic as locally it points to artful, hmm, I'll investigate further..

**Comment by mikkopori** [comment]
I'll try it with rolling

**Comment by ankul-shippable** [comment]
I think you have the old image in your local, it got update 6 days ago. can you pull the latest version and test it locally again.

**Comment by mikkopori** [comment]
Rolling solved the issue, and is probably more stable.

Thank you for your help!
