### ISSUE TITLE
one repo disappeared, but can't enable it once again!

### ISSUE THREAD

**Issue by Patechoc** [Shippable/support#3976]
We haven't changed our shippable.yml, but this morning, one of our active private project disappeared fro the Shippable dashboard. No one in our team have deleted it, and I can't add it back. I get this error message:

> deleteResourceById failed for id: 49144 returned error deleteVersionById for versionId: 3062861 returned error: versions.destroy failed for versionId: 3062861 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"

What could cause such a repo to disappear?
Why can't I add it again?

Thanks for your help
Patrick

**Comment by manishas** [comment]
@Patechoc we're looking into this.

**Comment by Patechoc** [comment]
Thanks. I discover that a second webhook has been created on this Github's repo, both pointing to shippable. Could that create the error?

**Comment by shrivara** [comment]
@Patechoc we noticed an inconsistency related to the project data. We've resolved this now.  Could you sync your account now and see if this is okay?

**Comment by Patechoc** [comment]
I clicked the "Sync" button under our Github organization, and it looks like it processing something without finishing it. I don't dare stopping it. I will try to add again our github repo righth after.
Thanks ;)

**Comment by Patechoc** [comment]
You solved it. We are back in business. Thanks for the quick replies ;)
