### ISSUE TITLE
Love the talk of Assembly Lines but can't create one

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#3978]
Pressing Sign Up button just takes me into Shippable. Can't find any UI that talks about Assembly Lines let alone a button to create one. Where is it?

**Comment by ankul-shippable** [comment]
@BryanCrotaz You can checkout our docs about how to add an assembly lines [here](http://docs.shippable.com/platform/tutorial/workflow/crud-syncrepo/#adding-a-syncrepo). Before you that you should checkout [configuring assembly lines docs](http://docs.shippable.com/platform/workflow/config/).

Please let us know if you have any issues.

**Comment by manishas** [comment]
@BryanCrotaz were you able to create an assembly line?

**Comment by manishas** [comment]
@BryanCrotaz I am closing this issue since I think you've now an Assembly Line :)

**Comment by BryanCrotaz** [comment]
Yes, thanks to Tom.
