### ISSUE TITLE
Error while enabling deleted project.

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#3979]
Hello, I'm trying to start a new project. 
I added a new git repo foo-test into shippable, but then I renamed it into foo.
Jobs are stopped been scheduled. 
So I deleted the project and I'm getting following error when trying to enable it back.

Error:

```
deleteResourceById failed for id: 52508 returned error deleteVersionById for versionId: 3124335 returned error: versions.destroy failed for versionId: 3124335 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"
```

**Comment by avinci** [comment]
can you send me the subscriptionId of your org?

**Comment by avinci** [comment]
also can you try and force sync your account. 
- go to your profile
- click on sync

**Comment by depohmel** [comment]
sync did help.

**Comment by avinci** [comment]
perfect, thx for trying Shippable..

**Comment by depohmel** [comment]
https://gist.github.com/depohmel/34d61e49f854f984ae0f38cf7da1ef61

**Comment by depohmel** [comment]
No, sync did not help.

**Comment by avinci** [comment]
ok, now try and sync and see if it helps.

**Comment by avinci** [comment]
just to be safe, i would hard refresh the page after sync completes.

**Comment by depohmel** [comment]
ok. It's back. thanks for the help.

**Comment by avinci** [comment]
awesome!
