### ISSUE TITLE
Conditionally load secure environment variables based on branch

### ISSUE THREAD

**Issue by cyrodjohn** [Shippable/support#3980]
Is there a way to conditionally load secure variables based on the current branch?

**Comment by a-murphy** [comment]
Assuming this is for a CI job, you can add [key-value pair integrations](http://docs.shippable.com/platform/integration/key-value/) to the [`generic` section of `integrations` in your `shippable.yml`](http://docs.shippable.com/platform/tutorial/integration/howto-use-key-value-in-runci/).  Branches for each integration can be specified similarly to [`branches` for the project](http://docs.shippable.com/ci/specify-branches/).  Adding `branches` with `except` or `only` to the integration in your `shippable.yml` at the same level as `integrationName` will control which branches will be able to use integration.  Building other branches will still be allowed, but they will not have access to the integration.

**Comment by manishas** [comment]
@cyrodjohn let us know if aidan's suggestion didn't work for you.
