### ISSUE TITLE
State seems to be broken in SPoG Dry Run

### ISSUE THREAD

**Issue by brt-mlaccetti** [Shippable/support#3981]
### Description of your issue:
Our workflow seemed to be broken, so I took a peek at the SPoG dry run, and I see a bunch of errors related to state:

```
Type: state is invalid in shippable.yml for name: staging_state.
Type: state is invalid in shippable.yml for name: uat_state.
Type: state is invalid in shippable.yml for name: prod_state.
```

Is this a bug in the viewer, or is something broken somewhere else?  In the "regular" SPoG viewer, I can see the state being created and populated with data, so I'm assuming it is a bug.

**Comment by trriplejay** [comment]
since your rSync job successfully created the state resource, it seems that this is just an error in the dry run functionality. I"ll open a bug to investigate.

**Comment by rageshkrishna** [comment]
Hi @brt-mlaccetti. Today's release should have fixed this. Please let us know if you're still running in to this bug. Thanks!
