### ISSUE TITLE
Build randomly fails 

### ISSUE THREAD

**Issue by SahithiGagganapally** [Shippable/support#3984]
Hi,

I am facing some random build failures from yesterday while pulling the docker image from our private registry. I tried to pull the same image in my local and its working fine.
I did not change yaml file but builds started failing in pre_ci_boot step all of a sudden.
Highly appreciate if someone can help.

Thanks,

**Comment by trriplejay** [comment]
can you tell us the exact error that you're seeing? does it happen every time now? What image are you using for boot? (is it a shippable default or a custom image?)

**Comment by SahithiGagganapally** [comment]
I am using custom image and we use shippable server installation.
different errors but in same pre_ci_boot step, 1) I wanted to create a tar file with some config files and target artifact created using maven so i changed my mvn command from clean deploy to mvn deploy, all of a sudden i got auth creds error. I revert my changes back to clean deploy and the build started working fine, not sure how and why this is related.
2) Today I did the same, changed the mvn command and it gives me image not found error. I reverified the path and it looks perfectly fine.

**Comment by SahithiGagganapally** [comment]
This is actually blocking my work, can someone help me on finding the root cause and solution for this.

Thanks,

**Comment by trriplejay** [comment]
so you changed the mvn command, and now the pre-ci-boot section says "image not found"? i dont think those two things could be related... is it possible that something changed in your configuration such that you are no longer authenticating properly, and so the private image can't be found?  How are you connecting to the private registry?

**Comment by trriplejay** [comment]
or are you saying your mvn command is in the 'pre-ci' section, followed by the 'pre-ci-boot'?

**Comment by SahithiGagganapally** [comment]
Even I don't see any connection with change in mvn commands and no not using it in pre_ci, I'm doing that step in CI.
I am aware that authentication is not a problem because i have other builds working fine pulling from same registry. I have an integration setup from the private registry on shippable.

**Comment by ambarish2012** [comment]
@SahithiGagganapally can we get into a quick call and resolve this issue?

**Comment by ambarish2012** [comment]
If you can send me your email, I can send you the details for the call.

**Comment by SahithiGagganapally** [comment]
sgagganapally@tablesafe.com

**Comment by SahithiGagganapally** [comment]
Just now my build started working, not sure what made that to work. I did not change anything.
Definitely interested to know the root cause.

**Comment by ambarish2012** [comment]
update: we cannot reproduce the problem now and we gave Sahithi a workaround should this problem occur again and needs to be immediately resolved. We will monitor this issue for now.
