### ISSUE TITLE
SPOG tooltip data is outdated

### ISSUE THREAD

**Issue by johnsonwj** [Shippable/support#3986]
This is what I see when I mouse over one of our pipeline's resources:

![Resource tooltip in SPOG view](https://user-images.githubusercontent.com/3478488/33402359-2abb3c54-d511-11e7-92ae-e2a3d7905748.png)

However, if I open the resource history, there are newer resources:

![Resource History](https://user-images.githubusercontent.com/3478488/33402392-4d4ba9de-d511-11e7-82bd-7ad8ee11db17.png)

This appears to happen when a build finishes; the SPOG tooltip does not get updated with the new OUT resources.

**Comment by ambarish2012** [comment]
This appears to be a bug since the tooltip datasource is not getting refreshed. @johnsonwj will let you know when we deploy the fix.

**Comment by johnsonwj** [comment]
Awesome, thank you!

**Comment by manishas** [comment]
This should have been fixed over a week ago. @ambarish2012 can you please confirm and close?

**Comment by ambarish2012** [comment]
Confirming that its fixed.
