### ISSUE TITLE
image on local machine

### ISSUE THREAD

**Issue by rajesh99** [Shippable/support#3990]
Is there a way to get the image on to a local machine and try the commands

**Comment by a-murphy** [comment]
I'm assuming you're referring to the build image.  If you have Docker installed, you should be able to pull and run any of the build images.  You can see the image used by your build in the `boot_container` section of the build logs in Shippable.  It's the last part of the `docker run` command, and if it's a Shippable default will usually start with `drydock`.  For example, `drydock/u16pytall:v5.10.4`.  You can then pull this image locally (`docker pull drydock/u16pytall:v5.10.4`), and run it with `-i -t` and a command to start bash (`docker run -i -t drydock/u16pytall:v5.10.4 /bin/bash`).  You can then run whatever commands you want in the image (`exit` will stop the container when you're done). This image will not, however, contain any of your code.  You can either clone the project as one of your commands or add a mounted volume with a clone of your repository.
