### ISSUE TITLE
AWS Fargate support for ECS task definitions and ECS services

### ISSUE THREAD

**Issue by nvmker** [Shippable/support#3991]
Hi,
I have a feature request:
AWS Fargate is recenlty released replacement for containers running on top of EC2 instances: https://aws.amazon.com/fargate/
To support it, task definitions should have a Fargate compatibility instead of EC2 compatibility, and will require the awsvpc network mode.
ECS services can run Fargate tasks if task definition have a Fargate compatibility.

**Comment by slavafomin** [comment]
Is there any news? Using Fargate would be a much more convenient option for us (so we don't have to configure the underlying EC2 infrastructure manually).

**Comment by ryan-kimber** [comment]
Looking for news on this Shippable! Is this anywhere on the roadmap?

**Comment by nvmker** [comment]
Since Shippable now a part of JFrog and not in active development I closing this issue.
