### ISSUE TITLE
Can't see private subscriptions

### ISSUE THREAD

**Issue by wwerst** [Shippable/support#3992]
### Description of your issue:
I'm a member of a private organization and I can't automatically see the other subscriptions when I login to my account through github.

**Comment by a-murphy** [comment]
If the missing projects are private GitHub repositories, you will need to enable private scopes in Shippable.  To do this, click "profile" on the left and then enable private scopes in the the "identities" panel.  You might need to click the "sync" button on that page if they don't appear.

If you've already enabled private scopes and a GitHub organization isn't shown, it most likely has third-party app access restrictions.  In this case, you can [request approval](https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/) on GitHub and an organization owner can [grant access on GitHub](https://help.github.com/articles/approving-oauth-apps-for-your-organization/).
