### ISSUE TITLE
non-master branches fail to checkout

### ISSUE THREAD

**Issue by DoWhileGeek** [Shippable/support#3993]
I'm having trouble running builds lately, git checks out my feature branch, but fails, but running the same command locally passes. Heres the build in question.

https://app.shippable.com/github/Omadi/silver-stride/runs/861/1/console

**Comment by DoWhileGeek** [comment]
Seems like numeric branch names trigger this failure. Not sure why though. I've worked around it, but it seems mildly restrictive.

**Comment by a-murphy** [comment]
Have you seen this with any other branches, or is just that one?

I haven't been able to reproduce that particular git error.  Does it still occur if you clear the cache by clicking the reset button next to "reset cache" in the project settings?

**Comment by DoWhileGeek** [comment]
Its happened with several branches. I ended up adding some alphanumerics to the branch name and it passed without a hitch. I dont have another pr yet that I can try the cache, but I'll update when I get around to it.

**Comment by DoWhileGeek** [comment]
tried again with a new branch and a new pr, no reproduction of this error.
