### ISSUE TITLE
Billing email

### ISSUE THREAD

**Issue by brt-mlaccetti** [Shippable/support#3995]
Is there any way to get invoices/receipts emailed to a different/additional person? Finance would really like to get this information, and I'd like to not have to always forward it. :)

**Comment by trriplejay** [comment]
From your subscription dashboard, if you click the gears icon in the top right, there should be a "billing" section.  In there, you can set a billing email.  Currently there is only room for one email address, but you could update that to your finance contact.  Let me know if you have any questions.

**Comment by brt-mlaccetti** [comment]
Sure, that works - be nice if we both got the email, but that'll do for now!
