### ISSUE TITLE
Docker version 

### ISSUE THREAD

**Issue by nmarjanovic** [Shippable/support#3996]
Hi,

We use our node for builds, installed Ubuntu 16.04 as you proposed, but ... after install of docker by us, we get this message after running re-Initialize from node panel:

dpkg: warning: downgrading docker-engine from 17.05.0~ce-0~ubuntu-xenial to 1.13.0-0~ubuntu-xenial

This is annoying ... We have our registry and we wand to use docker login with --passwd-stidn option, but this option old docker version don't support, password goes over network in full text. We tested using your encryption option as well, ok it's cool, but in reality you don't encrypt nothing, on build output we can see again password in full text, ok, it's on local machine etc..., but if that machine is corrupted or let say hacked, they can dig and find more security issue, but put away security away for now .. and yes I know, security of user nodes is not issue.

Back to beginning, why you script force old Docker version? Or I'm missing something?

Best regards

**Comment by nmarjanovic** [comment]
Hi,

I was not aware on this update, but for integration of --password-stdin option we will need to wait for 17.09. Anyway, thanks for sharing this info. And i will propose once again, send information of your updates to users once time to time, we find ourself in situation that we don't know nothing about your work in progress or things done in new images releases etc..

**Comment by manishas** [comment]
@nmarjanovic we now publish release notes each month and these are also linked from the Shippable version at the bottom when you're signed in:

![image](https://user-images.githubusercontent.com/2983749/34161257-f68f809c-e484-11e7-83fb-90ac22ccb942.png)
