### ISSUE TITLE
Can't get previous job's state using shipctl's copy_resource_file_from_state

### ISSUE THREAD

**Issue by seniorquico** [Shippable/support#3998]
I'm trying to pass some version information from a test job to a deploy job (both are `runSh` jobs) using the following guide as inspiration:

http://docs.shippable.com/platform/tutorial/workflow/sharing-data-between-jobs/

Unfortunately, my script fails to copy the file from the test job's state to the deploy job's working directory. The `shipctl copy_resource_file_from_state` call prints:

> `---------------- Restoring file from state -------------------`
> `------  File does not exist in previous state, skipping -----`

Inspecting the deploy job's environment (simply using tree), I noticed that my test job's state does exist at the following path:

/build/IN/test_deploy/_**runSh**_/published.json

Poking around the shipctl scripts, it appears as though it's assembling the following path:

/build/IN/test_deploy/_**state**_/published.json
https://github.com/Shippable/node/blob/master/shipctl/x86_64/Ubuntu_16.04/utility.sh#L278

Of note, running `shipctl get_resource_state test_deploy` correctly returns the path:

/build/IN/test_deploy/_**runSh**_

Am I missing something with implementing this scenario? Is this a bug in the shipctl script? Should I just manually pull the file from the state path using `shipctl get_resource_state test_deploy`?

Another note: I encountered this exact same issue when trying to manually pull information in a runSh job from the state of a managed `manifest` job. It was trying to get `manifests.json` from:

/build/IN/my_image/_**state**_/manifests.json

instead of where it was actually located:

/build/IN/my_image/_**manifest**_/manifests.json

As this was observed across multiple jobs/runs, here are the relevant logs:

- [test_deploy that saved JSON to state](https://app.shippable.com/github/ZapicInc/jobs/test_deploy/builds/5a299e0eb9ead107003733fb/console)
- [production_deploy that attempted to pull JSON from test_deploy state](https://app.shippable.com/github/ZapicInc/jobs/production_deploy/builds/5a29a5c97cc9a80700877b38/console)
- [production_deploy that listed directory using tree](https://app.shippable.com/github/ZapicInc/jobs/production_deploy/builds/5a29a8d7cf141c0700bbfea8/console)

Thanks in advance for any help you can provide with this issue!

Kyle

**Comment by trriplejay** [comment]
Hey, thanks for the analysis. this does appear to be a bug in the shipctl `copy_resource_file_from_state` function.  

Typically, state information is kept in the `/build/IN/<name>/<type>` path.  We have an actual resource type called 'state', so this would work for that resource, but not for the more general case.  `state` is the only resource type that allows the saving of files, which is probably why this was implemented just for that.  It did not take into account being able to copy from the state of an IN job, but I think it definitely should.

The workaround that you've already found is the one I'd recommend until we get this fixed, which is to use `get_resource_state` to find the correct path, then do the copy manually.

**Comment by seniorquico** [comment]
Thanks, @trriplejay! It's an easy enough workaround in the meantime. Might warrant a warning in [the docs](http://docs.shippable.com/platform/tutorial/workflow/sharing-data-between-jobs/) until it's fixed.

**Comment by manishas** [comment]
@trriplejay any update on this?

**Comment by trriplejay** [comment]
This has been fixed, and has been rolled out to runSh jobs.  build images in runCI jobs will not yet have this update.

@seniorquico you should be able to use `copy_resource_file_from_state` on any resource/job that would contain files now.

please let me know if you're still having issues with it.
