### ISSUE TITLE
Cannot add runCI job, please enable the project before adding job

### ISSUE THREAD

**Issue by Zingoer** [Shippable/support#4002]
This is the error console link:
https://app.shippable.com/bitbucket/mxitechnologies/jobs/lrp-deploy_master_rSync/builds/5a2ec3b919bbec0700068274/console

This lrp-vertx-template probject is a very old project. We've enabled and use the event trigger way to deploy the whole project long time ago. Then later on, we move out the project to another project in bitbucket and remove all of the event trigger relating to this project.
Now because we can't add event trigger in shippable, I use your new way by adding a runCI job in the shippable job yml files. 
But then I got the error Cannot add runCI job...
The problem is that in the SPOG, I can't even find the git lrp-vertx-template_ciRepo and lrp-vertx-template_runCI. The SPOG showing the vertx-template manifest and deploy similar to how a old project showing it. But I expect it showing similar to the lrp-auditor or lrp-configuration project.
Therefore, I'm wondering if there are some legacy cache remaining to prevent the lrp-vertx-template to build the whole pipeline in the shippable current suggest way.

**Comment by Zingoer** [comment]
BTW, If I wrote all of my resource and job in the CI shippable.yml file, it doesn't show the whole pipeline in SPOG at all. Though the CI process works successfully.

**Comment by a-murphy** [comment]
Projects created before March 2017 aren't set up with a runCI job by default.  If you go to the project settings page (click "lrp-vertx-template" on the subscription dashboard, then the gears in the top right) there's a "hook" button next to "connect pipelines" in the second to last panel that will create the runCI job.  Could you try clicking that and then running your rSync job again?

**Comment by Zingoer** [comment]
@a-murphy Sorry, I can't find those button. On my left panel, I have
Views
  > Home
Bitbucket
  > companyName(SPOG)

Then in SPOG, there is a setting Gear
Gear
 > Nodes
 > Integrations
 > Settings
I can't see either the hook button or the connect pipelines

**Comment by Zingoer** [comment]
And in the lrp-vertx-template project settings, there are sections:
WEBHOOK CONFIG
VIEW SETTINGS
ENCRYPT
PROJECT CLONE
PROJECT ACTIONS
I can't find the hook button as well

**Comment by a-murphy** [comment]
It sounds like you're found the right project settings page.  The hook button should be in the "project actions" section.

Are you a project owner?  If you aren't a project owner, that would explain why you can't see it.

**Comment by Zingoer** [comment]
@a-murphy,
In Project Actions,
there are only 
- Synchronize SCMs
- Timeout
- Reset Cache

**Comment by Zingoer** [comment]
Hello @a-murphy ,
Thank you for your help. You are right, I don't have privilege to do the hook. Though It's little pain in that way to find each project owner to do that. But it works now.
