### ISSUE TITLE
runCI doesn't automatically trigger the Manifest job

### ISSUE THREAD

**Issue by Zingoer** [Shippable/support#4004]
Hello, me again. I'm not sure if I should create this new thread or it's better to keep add message on the closed thread. 
I'm able to create the similar pipeline mentioned in https://github.com/Shippable/support/issues/3801
However, runCI can't automatically trigger the Manifest job. Neither the staging or prod one. My runCI is
https://app.shippable.com/bitbucket/mxitechnologies/lrp-vertx-template/runs/131/1/console
And if you can check the SPOG dashborad, filter with PipelineDemo will be able to see my current set pipeline.

**Comment by ambarish2012** [comment]
@Zingoer here are the steps to connect your CI to your manifest:

1. Specify the image resources as an OUT on your runCI job
Example:

```yaml
jobs:
  - name: app_runCI
    type: runCI
    steps:
      - OUT: app_develop_img
      - OUT: app_master_img
```

2. In your shippable.yml, create a new version of the image resource, ideally in post_ci section.

```
- shipctl post_resource_state app_develop_img versionName "$BRANCH.$BUILD_NUMBER"
```

3. In your specific case, since you have two branches and two image resources, you will need to add branch specific logic, something like:

```
if [ "$BRANCH" = "develop" ]
then
    shipctl post_resource_state app_develop_img versionName "$BRANCH.$BUILD_NUMBER"
else
    shipctl post_resource_state app_master_img versionName "$BRANCH.$BUILD_NUMBER"
fi
```

Let me know if you need a sample.

**Comment by Zingoer** [comment]
Hello @ambarish2012,
I tried what you said. It doesn't work.
In CI on_success I have this piece:
 `on_success:
    # If the branch is develop, create a staging java docker image, tag it and push it to the staging repository
    # If the branch is master, then promote the develop image to master
    - >
      if [ "$BRANCH" = "develop" ] && [ "$IS_PULL_REQUEST" = false ]; then
        docker build -f $SHIPPABLE_BUILD_DIR/prod/Dockerfile  -t $DEV_IMAGE_NAME $SHIPPABLE_BUILD_DIR;
        docker tag $DEV_IMAGE_NAME:latest $DEV_IMAGE_REPO_URL:latest;
        docker tag $DEV_IMAGE_NAME:latest $DEV_IMAGE_REPO_URL:$BRANCH.$BUILD_NUMBER;
        docker push $DEV_IMAGE_REPO_URL:latest;
        docker push $DEV_IMAGE_REPO_URL:$BRANCH.$BUILD_NUMBER;
        shipctl post_resource_state lrp-vertx-template-img-$BRANCH versionName "latest"
        # echo "versionName=latest" >> $JOB_STATE/lrp-vertx-template-img-$BRANCH.env
      elif [ "$BRANCH" = "master" ] && [ "$IS_PULL_REQUEST" = false ]; then
        docker pull $DEV_IMAGE_REPO_URL:latest;
        docker ps -a;
        docker tag $DEV_IMAGE_REPO_URL:latest $MASTER_IMAGE_REPO_URL:latest;
        docker tag $DEV_IMAGE_REPO_URL:latest $MASTER_IMAGE_REPO_URL:$BRANCH.$BUILD_NUMBER;
        docker push $MASTER_IMAGE_REPO_URL:latest;
        docker push $MASTER_IMAGE_REPO_URL:$BRANCH.$BUILD_NUMBER;
        shipctl post_resource_state lrp-vertx-template-img-$BRANCH versionName "latest"
        # echo "versionName=latest" >> $JOB_STATE/lrp-vertx-template-img-$BRANCH.env
      fi;`

Then in the shippable.jobs.yml, I have
`
jobs:
  - name: lrp-vertx-template_runCI
    type: runCI
    flags:
      - PipelineDemo
    steps:
      - OUT: lrp-vertx-template-img-develop
      - OUT: lrp-vertx-template-img-master

  - name: lrp-vertx-template-man-staging
    type: manifest
    flags:
      - PipelineDemo
    steps:
      - IN: lrp-vertx-template-img-develop
      - IN: lrp-vertx-template-docker-opt-staging
        applyTo:
          - lrp-vertx-template-img-develop
      - TASK: managed

  - name: lrp-vertx-template-man-pre-prod
    type: manifest
    flags:
      - PipelineDemo
    steps:
      - IN: lrp-vertx-template-img-master
      - IN: lrp-vertx-template-docker-opt-pre-prod
        applyTo:
          - lrp-vertx-template-img-master
      - TASK: managed`

Then in the shippable.resources.yml, I have
resources:`
 # lrp-vertx-template docker image
  - name: lrp-vertx-template-img-develop
    type: image
    flags:
      - PipelineDemo
    integration: lrp-ec2-registry
    pointer:
      sourceName: "xxx/staging/vertx-template"
    seed:
      versionName: latest
  - name: lrp-vertx-template-img-master
    type: image
    flags:
      - PipelineDemo
    integration: lrp-ec2-registry
    pointer:
      sourceName: "xxx/production/vertx-template"
    seed:
      versionName: latest`

**Comment by ambarish2012** [comment]
@Zingoer I am looking at your build now.

**Comment by ambarish2012** [comment]
@Zingoer I figured out the issue. The reason new versions of the image resources are not getting created is because the versionName is remaining the same across builds.

There are two ways to fix this problem:

1. Change versionName in every run.

```
shipctl post_resource_state lrp-vertx-template-img-$BRANCH versionName "$BRANCH.$BUILD_NUMBER"`

2. Keep versionName static but add another dynamic key like tag

```
shipctl put_resource_state lrp-vertx-template-img-$BRANCH versionName "latest"
shipctl put_resource_state lrp-vertx-template-img-$BRANCH tag "$BRANCH.$BUILD_NUMBER"
```

**Comment by Zingoer** [comment]
@ambarish2012 Thank you for your help. I will have a try. 
At the mean time, Can you explain a little bit more how this resource state will affect other CD stages. I'm wondering where the key value pair are used and where the key-value pair will be able to see?
If I set `hipctl post_resource_state lrp-vertx-template-img-$BRANCH versionName "$BRANCH.$BUILD_NUMBER"`, Let's say the current branch is Master and the build number is 1
So this key pair will be `versionName=master.1`
But how this will affect the resource?
```
 - name: lrp-vertx-template-img-master
    type: image
    flags:
      - PipelineDemo
    integration: lrp-ec2-registry
    pointer:
      sourceName: "xxx/production/vertx-template"
    seed:
      versionName: latest
```
I set the resource has a seed with a `versionName:latest`. What is the relationship between this seed and the CI build `versionName=master.1`? If they have no relationship, where is the key-pair state change trigger the manifest starting to run

**Comment by Zingoer** [comment]
@ambarish2012 I have a try. It works. I commit on develop and then it post the resource state to be develop.134. Then the lrp-vertx-template-img-develop resource has a new version with a version develop.134. It is not obvious that the table title VERSION actually means the versionName. And I create a dummy key-pair value and that value will also appear in the resource and will be traceable by the future CD steps. Now I understand how the state works and how it's carrying on.

**Comment by Zingoer** [comment]
@ambarish2012 Now I'm starting to understand what the following document means:
http://docs.shippable.com/platform/workflow/state/overview/
http://docs.shippable.com/platform/tutorial/workflow/sharing-data-between-jobs/
I would recommend to add a small code snippet example for http://docs.shippable.com/ci/trigger-pipeline-jobs/ 2nd section so that people can understand what the relationship between this output and the other resources and where it will be used. Or at least providing some reference page link to it.

**Comment by Zingoer** [comment]
@ambarish2012 Now I'm getting a weird case that I try to commit code and trigger the runCI job 135 and 136 and 138. But the image resource didn't get update and keep in develop.134 and in develop.137. This happens whenever I give two lines of post_resource_state.
```
shipctl post_resource_state lrp-vertx-template-img-$BRANCH versionName "$BRANCH.$BUILD_NUMBER"
shipctl post_resource_state lrp-vertx-template-img-$BRANCH whatever "trial"
``` 
Do I make something wrong again or there is a potential bug?

**Comment by rageshkrishna** [comment]
Hi @Zingoer. [post_resource_state](http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#post_resource_state) replaces the state. Your second statement should use [put_resource_state](http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#put_resource_state) instead to _append_ to the state.

**Comment by Zingoer** [comment]
@rageshkrishna Sorry, my bad, I didn't notice that in @ambarish2012 comments. But in th is case, I think I can use `post_resource_state_multi` as well. Right?

**Comment by Zingoer** [comment]
@rageshkrishna I tried `post_resource_state_multi`, it doesn't work and give a error back saying The command post_resource_state_multi is not supported. Then I will go with the way you recommend.

**Comment by ambarish2012** [comment]
@Zingoer post_resource_state_multi is not supported in CI yet. Please proceed with the other option.

**Comment by Zingoer** [comment]
@ambarish2012 Got it, thank you!
