### ISSUE TITLE
Changing the owner of integrations

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#4010]
I'm cleaning up a lot of integrations, but i see a few which are under the wrong owner, which is a problem.

Is there any way to change ownership without breaking dependent jobs and resources?

**Comment by a-murphy** [comment]
Jobs and resources use subscription integrations, which belong to the subscription and give the resources permission to use an account integration.  Updating the existing subscription integrations to use different account integrations can be done by clicking the integration on the subscription integrations page and selecting one of your account integrations in the dropdown.  Changing the account integration selected to another integration of the same type should not cause any problems as long as the new integration has the required access for the intended purpose, for example a Docker Hub integration should have access to the image you need.

**Comment by bbrala** [comment]
Hmm, i see now... It would be really helpfull to have an inidicator of the owner of the integration in the dropdown, this would make things quite a lot clearer, i had 2 integrations named `bitbucket` by 2 different users :)

**Comment by manishas** [comment]
This will be available with the next release.

**Comment by ambarish2012** [comment]
@bbrala closing this issue since this feature has been implemented.

**Comment by bbrala** [comment]
Thanks!
