### ISSUE TITLE
node 6.11 image uses very old npm version

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4011]
specifying node 6.11 in the default image results in npm version 3. This is very buggy, and npm 5.6.0 is now available.

`npm install npm@5.6.0 -g` works but adds 20s to the build time.

**Comment by manishas** [comment]
Thanks for the suggestion. We will ship this with our January image update.

**Comment by manishas** [comment]
@ambarish2012 I also noticed that the Machine image docs do not mention npm version. Can you please fix this?

**Comment by BryanCrotaz** [comment]
maybe we can specify npm version where we specify node version.
Many people are moving to yarn so this would be a good option to add for node images.

**Comment by BryanCrotaz** [comment]
> We will ship this with our January image update.
How do we get notified of image updates?

**Comment by manishas** [comment]
@ric03uec can we get this done asap? We've been sitting on this for months now :(

**Comment by ric03uec** [comment]
The latest drydock images `drydock/u16*:v6.6.4`, `drydock/u14*:v6.6.4` and `drydock/c7*:v6.6.4` use npm version 5.6.0.
Sorry about not updating this thread.
@BryanCrotaz closing this issue. the updated docs will be available in the next release by next week.

**Comment by BryanCrotaz** [comment]
Unfortunately in the 8 months since I reported this, version 6 has been released with some speed improvements for ci builds. Could you please update your images to use the latest release?

**Comment by ric03uec** [comment]
sure. this will be available in the drydock image updates for version `v6.8.4`. thanks for the heads up
