### ISSUE TITLE
Login via GitHub/BitBucket violates security policy

### ISSUE THREAD

**Issue by janesg** [Shippable/support#4012]
I'm unable to login with either GitHub or BitBucket.

Both routes result in an error page:

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

Could you tell me what the issue is please ?

**Comment by a-murphy** [comment]
We automatically flag accounts that appear to be likely to be Bitcoin miners.  Some of the accounts flagged are, of course, not actually Bitcoin miners.  I've removed the flag from your account, so you should be able to log in with either GitHub or Bitbucket now.

**Comment by a-murphy** [comment]
I'm closing this as resolved.  Please let us know if you run into any more problems.
