### ISSUE TITLE
Failed npm install with node v8.9.1 (npm v5.5.1) in Shippable

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4013]
### Description of your issue:
I have upgraded the node version to be v.8.9.1 and run the test successfully in my local. However, when I run this build via Shippable, it shows errors as below. Could you please have a look and advise if there is any solution I should try?

```
Now using node v8.9.1 (npm v5.5.1)
Now using node v8.9.1 (npm v5.5.1)
npm
 
WARN 
tar ENOENT: no such file or directory, open '/build/IN/now-site-repo/gitRepo/automation/node_modules/.staging/moment-750522fb/min/locales.min.js'
npm
 
WARN
 
tar
 ENOENT: no such file or directory, open '/build/IN/now-site-repo/gitRepo/automation/node_modules/.staging/hapi-fac11582/test/file/image.png'
npm
 WARN
 tar ENOENT: no such file or directory, open '/build/IN/now-site-repo/gitRepo/automation/node_modules/.staging/hapi-fac11582/test/file/image.png.gz'
npm 
WARN tar ENOENT: no such file or directory, open '/build/IN/now-site-repo/gitRepo/automation/node_modules/.staging/core-js-4a037c90/client/library.min.js'
npm 
WARN tar ENOENT: no such file or directory, open '/build/IN/now-site-repo/gitRepo/automation/node_modules/.staging/moment-e477d9f3/min/moment-with-locales.js'
npm ERR!
 code
 ETARGET
npm 
ERR! notarget No matching version found for fibers@1.0.16
```

Please click [here](https://app.shippable.com/github/bauerxcelmedia/jobs/CMS-au-now-smoke-test/builds/5a3345564cb6bc0700f72712/console) to see the full log

The script to run this job is
![image](https://user-images.githubusercontent.com/14726381/34028412-007031ae-e1b7-11e7-8fa4-5756dd150002.png)

**Comment by deepikasl** [comment]
Hi @JoeRattanamaneesilp can you try `npm cache clean` before installing npm.

**Comment by JoeRattanamaneesilp** [comment]
Hi @deepikasl,

I have tried the solution that you suggested. It doesn't work. Please see the logs.

- Try `npm cache clean` before `npm install`
![image](https://user-images.githubusercontent.com/14726381/34084679-c39c4712-e3d8-11e7-960a-0bff219f0d24.png)
https://app.shippable.com/subscriptions/583638aafd9c101000d73b34/pipelines/builds/5a36f14264e75f0700a395b2/consoles

- Try `npm cache clean --force` before `npm install`
![image](https://user-images.githubusercontent.com/14726381/34084676-b19c8644-e3d8-11e7-90ff-f781209b02ce.png)
https://app.shippable.com/github/bauerxcelmedia/jobs/CMS-au-now-smoke-test/builds/5a36f02660df4c06000a6cc4/console

I'm trying to find another solution. If you have any suggestion, please let me know.

Regards,
Joe

**Comment by JoeRattanamaneesilp** [comment]
Hi @deepikasl, 

I still cannot find a solution to fix the issue. Please advise if you have any solution.

Regards,
Joe

**Comment by deepikasl** [comment]
Hi @JoeRattanamaneesilp 
This is happening because, you are doing `rm -rf node_modules`. And it is trying to read that file which is not present, so u are getting `ENOENT` errors. Please remove or comment that line.

You can refer my yml here: https://github.com/deepikasl/sample_pipelines/blob/simple_notification/shippable.jobs.yml.
Removing `script: rm - rf node_modules`, did not show any `ENOENT` errors.

**Comment by JoeRattanamaneesilp** [comment]
Hi @deepikasl,

I have tried by removing `rm -rf node_modules`. It doesn't solve the problem.

Below is the result summary of this issue with some cases that I think it may be useful for investigation.

Case 1: Use nvm `6.1.0` without any `npm cache clean` and without `rm -rf node_modules`
:white_check_mark: Npm can be installed successfully in Shippable.
https://app.shippable.com/github/bauerxcelmedia/jobs/CMS-au-now-smoke-test/builds/5a388f8664e75f0700ac05a7/console

Case 2: Create a new job with the same commands as in case 1 except the nvm version. Use nvm `8.9.1`
:x: Errors about no such file or directory in .../.staging/... is appearing.
e.g. `ENOENT: no such file or directory, open '/build/IN/now-site-repo/gitRepo/automation/node_modules/.staging/hapi-fac11582/test/file/image.png'`
https://app.shippable.com/github/bauerxcelmedia/jobs/Spike-CMS-au-now-smoke-test/builds/5a3890f5fa6ab1070042df9e/console
Note: This is working find when I run in my local.
 
Regards,
Joe

**Comment by JoeRattanamaneesilp** [comment]
This problem has been fixed by adding shippable.yml in the module package. It wasn't required when using node v.6.1.0.
