### ISSUE TITLE
Failed to delete rsync job resource

### ISSUE THREAD

**Issue by martinyunify** [Shippable/support#4014]
I failed to delete rsync  job resource. Could you please help me resolve this issue? Thank you!
https://app.shippable.com/subs/github/k8s-unicorn

**Comment by deepikasl** [comment]
Hi @martinyunify We are looking in to it.

**Comment by rageshkrishna** [comment]
@martinyunify Can you take a look now? The delete was actually being processed by the service, but the API call timed out before it was completed, which is probably why you saw an error message. Because a large number of related entities needed to be cleaned up, the delete took some time to finish.

**Comment by martinyunify** [comment]
It works as expected！ Thank you!
