### ISSUE TITLE
one repo disappeared, but can't enable it once again

### ISSUE THREAD

**Issue by Paikan** [Shippable/support#4015]
### Description of your issue:

I have the exact same problem as what is described in #3976 

> deleteResourceById failed for id: 55021 returned error deleteVersionById for versionId: 3406165 returned error: versions.destroy failed for versionId: 3406165 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"

Thanks for your help
Benjamin

**Comment by a-murphy** [comment]
Could you synchronize your account by clicking "profile" on the left and then the "sync" button?  Your subscription had a duplicate that caused some confusion.  I've removed that and your enabled project should reappear after you synchronize your account.

**Comment by Paikan** [comment]
It worked. Thanks.
