### ISSUE TITLE
Using Segment key in CI 

### ISSUE THREAD

**Issue by jeremiahlukus** [Shippable/support#4016]
I am using a travis.yml file to integrate with shippable. I need to add a segment write key (https://github.com/segmentio/analytics-ruby#usage). I know travis has something like

`travis encrypt "WRITE_KEY=this_is _where_my_write_key_goes" --add ` 

On the shippable site there is a place to add keys for aws, docker, git, ect... Is there a way to add this segment write key?

**Comment by rageshkrishna** [comment]
While we don't have a native integration to Segment, we do have a generic key-value pair integration that you can use to do this. You can check out the docs at http://docs.shippable.com/platform/integration/key-value/#key-value-pair-integration.

I hope this helps. Let me know if you have any questions.

**Comment by jeremiahlukus** [comment]
Hm I'm not sure why I am getting this error

`Invalid integration SEGMENT_WRITE_KEY specified for integration type: generic`

```
 integrations:
     generic:
        - integrationName: SEGMENT_WRITE_KEY
```

if I change `  - integrationName: SEGMENT_WRITE_KEY` to `- SEGMENT_WRITE_KEY: SEGMENT_WRITE_KEY`  Since the name and the key are the same I get `Invalid integration undefined specified for integration type: generic`

**Comment by rageshkrishna** [comment]
Did you create a subscription integration? An account integration just defines the credentials, but you need to also associate it with a subscription so it can be used in projects. The details are at http://docs.shippable.com/platform/tutorial/integration/howto-crud-integration/, particularly the section http://docs.shippable.com/platform/tutorial/integration/howto-crud-integration/#adding-integration-to-a-subscription

The `integrationName` in the YML above should match the name of the subscription integration.

**Comment by jeremiahlukus** [comment]
I just erased the key and restarted. Now I have the correct scope 
![screen shot 2017-12-15 at 10 59 32 am](https://user-images.githubusercontent.com/17206638/34049917-1ccb071e-e187-11e7-9f38-60e951198705.png)

Now I am getting the `Invalid integration undefined specified for integration type: generic` I edited my travis.yml above

**Comment by jeremiahlukus** [comment]
Ah sorry it is compiling now
