### ISSUE TITLE
Shippable using chrome instead of Firefox for selenium

### ISSUE THREAD

**Issue by jeremiahlukus** [Shippable/support#4019]
I am using selenium with Firefox, after installing everything for my app and installing qt, geckodriver and Firefox. All tests pass locally but 17 of my tests are failing in the CI env. After looking at the messages it seems like the browser it is running on is Chrome. (http://docs.shippable.com/ci/selenium/) Says that "Some of our official images also have Chrome pre-installed. "  
The error that comes up is 
```
     Failure/Error: page.find_link("Products").click
     Selenium::WebDriver::Error::ElementNotInteractableError:
     # WebDriverError@chrome://marionette/content/error.js:227:5
     # ElementNotInteractableError@chrome://marionette/content/error.js:335:5
     # seleniumClickElement@chrome://marionette/content/interaction.js:240:11
```

My build is here 
https://app.shippable.com/github/stordco/order-inventory/runs/83/1/console

My yml file is 

https://gist.github.com/jeremiahlukus/51e8fe8f66692dc24e5cae6101b69ad6

**Comment by a-murphy** [comment]
Some images do have both Chrome and Firefox installed.  However, your build doesn't have to use Chrome just because it's installed.  And I've never seen an error occur simply because Chrome is installed.

Usually, you'll have a configuration somewhere in your repository with the browser and driver you intend to use with Selenium.  The location varies depending on the language and how you're using Selenium.  I would suggest checking that to make sure that it matches the version of Firefox and driver that you are installing.

**Comment by jeremiahlukus** [comment]
> "And I've never seen an error occur simply because Chrome is installed." 

Its not that its installed its running chrome and when chrome drives the tests there are errors. I know this because thats why I had to remove chrome I was getting the same `Selenium::WebDriver::Error::ElementNotInteractableError:` and ` # MoveTargetOutOfBoundsError@chrome://marionette/content/error.js:441:5` 

Nowhere in my code is chrome mentions I did an Ack search and chrome is not mentioned in my yml file either.

**Comment by jeremiahlukus** [comment]
A few errors I get when using chrome are 

```    Selenium::WebDriver::Error::ElementNotInteractableError:
      # WebDriverError@chrome://marionette/content/error.js:235:5

AND 


      Selenium::WebDriver::Error::MoveTargetOutOfBoundsError:
        (293.93333435058594, 547.3000183105469) is out of bounds of viewport width (576) and height (356)
      # WebDriverError@chrome://marionette/content/error.js:235:5
      # MoveTargetOutOfBoundsError@chrome://marionette/content/error.js:449:5```

**Comment by jeremiahlukus** [comment]
Even after purging Chrome I still get ` Selenium::WebDriver::Error::ElementNotInteractableError:
     # WebDriverError@chrome://marionette/content/error.js:235:5`

**Comment by jeremiahlukus** [comment]
it was an xvfb error
