### ISSUE TITLE
gitRepo resource docs don't document the path that the files are checked out into

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4021]

**Comment by a-murphy** [comment]
If you're still looking for the path, the recommended method is to use `shipctl` in your job as documented [here](http://docs.shippable.com/platform/tutorial/workflow/access-resource-data/#accessing-path-data).  The `shipctl get_resource_state` command given the name of the gitRepo resource will output the path to the cloned repository.

**Comment by manishas** [comment]
@BryanCrotaz the path can be obtained through an [environment variable](http://docs.shippable.com/platform/workflow/resource/gitrepo/#default-environment-variables)

![image](https://user-images.githubusercontent.com/2983749/34160875-7e3e1316-e483-11e7-9709-08d98bdd2abb.png)

The shipctl method Aidan points to above is the recommended approach to get the path.

**Comment by BryanCrotaz** [comment]
path is incorrect.

Resource is ember-repo-master

```
echo $EMBERREPOMASTER_PATH
/build/IN/ember-repo-master
```

But repo is checked out to `/build/IN/ember-media-player-repo-master/gitRepo`

Either the ENV variable is incorrect, or the documentation is incorrect or doesn't say that the repo is actually in a subfolder.

**Comment by manishas** [comment]
Hmmm ok. Will fix this asap.

**Comment by BryanCrotaz** [comment]
Feels like you need an intern who doesn't understand the platform to dogfood it in lots of different ways - docker, node, ember or angular, ruby, java, c#. Simple and complex assembly lines. Then contribute to examples and docs to make it easier to start.

**Comment by ambarish2012** [comment]
Docs have been updated, closing the issue.
