### ISSUE TITLE
Can't add Sync Repo

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#4023]
Hello!

I'm trying to add sync repo:
![subscription - enable project _ shippable 1](https://user-images.githubusercontent.com/1702725/34126441-a378a526-e44a-11e7-984c-0972804bcf84.png)

But I'm getting the following error:
![subscription - enable project _ shippable](https://user-images.githubusercontent.com/1702725/34126434-9d94c1b2-e44a-11e7-9f03-691cacad9a9a.png)

What could be the problem?

Maybe it's somehow related to the fact, that I have previously had the repository with the same name, but deleted it.

Thank you!

**Comment by trriplejay** [comment]
Yes, it seems to be related.  There are still some orphaned resources occupying the name you're attempting to use.  We can get these cleaned up for you.

I notice that one of these is a deploy job with a load balancer.  Is your ECS service still active? typically when a deploy job is deleted on Shippable, the associated service is deleted on ECS, so I want to make sure that we won't be causing you downtime if we try to delete your old deploy job.

If you'd prefer, we can take steps to avoid the service removal.  Are you still using that service?

**Comment by slavafomin** [comment]
@trriplejay Yes, the service could be removed from AWS. I just want to reset this application. Thank you!

**Comment by a-murphy** [comment]
We deleted the orphaned resources.  Could you try adding your syncRepo again now?

**Comment by slavafomin** [comment]
It worked, thanks!
