### ISSUE TITLE
Error: Unable to find service … in cluster

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#4024]
Hello!

I'm getting the following error: `Unable to find service ebc-web-client-prod-deploy-ebc-web-client-manifest undefined in cluster ebc-production`, when trying to deploy our application. However, the `ebc-web-client-prod-deploy-ebc-web-client-manifest` task definition is present in our AWS account.

```
/home/shippable/micro/nod/genExec/managed/deploy/run.sh 6s  
Starting Deployment for: ebc-web-client-prod-deploy
Preparing manifests
Applying manifest overrides for ebc-web-client-manifest
Summary of cluster:
-- added:	1
-- changed:	0
-- deleted:	0
Force deployment is: true
Reset deployment is: false
Summary of 1 manifests:
-- scalable:	0
-- deployable:	1
-- removable:	0
Deployment Settings:
-- method:	upgrade
-- workflow:	serial
Initialized AWS Adapter.
getting previous deploy output
Executing deploy type: upgrade
getting previous service
Found previous service: ebc-web-client-prod-deploy-ebc-web-client-manifest
creating container definition
creating task definition
getting service
Failed to get service for cluster ebc-production
'Unable to find service ebc-web-client-prod-deploy-ebc-web-client-manifest undefined in cluster ebc-production'
Successfully created folder /build/state/ebc-web-client-manifest/
Successfully saved file ecs-service-definition.json
Successfully created folder /build/state/ebc-web-client-manifest/
Successfully saved file ecs-task-definition.json
Failed to deploy manifest for type: upgrade
Successfully created folder /build/state
Successfully saved file outputVersion.json
Deployment failed for ebc-web-client-manifest
Deployment failed with error : true
```

What could be the reason for this?

Thank you.

**Comment by a-murphy** [comment]
Is there also a `ebc-web-client-prod-deploy-ebc-web-client-manifest` service in the cluster?  If you navigate to the cluster in the AWS console, it should be listed on the services tab.  It sounds like it may have been deleted.  If the service is not listed, clicking the "reset" button on the Shippable SPOG or the reset checkbox when triggering the job from the job dashboard should create a new service and deploy successfully.

**Comment by slavafomin** [comment]
Yes. After verifying this, the service is actually missing. However, where do I find this "reset" button? I'm not seeing it anywhere. What if I would create the service manually on the AWS side with the same name?

**Comment by a-murphy** [comment]
There are two ways to trigger a reset.  Either one will work.

First, in the SPOG view on the subscription dashboard.  (Clicking the eye in the top right on the subscription dashboard will let you switch between SPOG and grid views.)  If you right-click on the deploy job there will be a reset option.

Second, if you go to a deploy job page by clicking the name from the grid view or clicking the deploy job on the SPOG view and then the job name in the breadcrumb at the top.  There's a "play" button at the top of that page that will then allow you to check a box for reset.

**Comment by slavafomin** [comment]
Oh, I see. Thanks you )
