### ISSUE TITLE
Build duration is affected by amount of logging

### ISSUE THREAD

**Issue by UncleTawnos** [Shippable/support#4026]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/bitbucket/humanoitgroup/analytics-backend/runs/187/1/console
build is ok but takes ~11 minutes instead of 4 (10 minutes is maven downloading packages which takes ~50s on the underlying node)

mvn install on the same code checked out to physical custom node:
[INFO] Total time: 43.314 s (Wall Clock)

mvn install on shippable docker running on that node:
[INFO] Total time: 09:23 min ( ~99% of it is downloading maven dependencies)

- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
You may want to try caching your maven dependencies as described here: https://github.com/Shippable/support/issues/4005#issuecomment-351151031

I'm not sure why the build container would take so much longer to install. Could some of the dependencies have already been present on the host node, making the install seem much shorter when it actually had less to install?

**Comment by UncleTawnos** [comment]
@trriplejay we have cache enabled already, but we were missing cache_dir line. That do help a lot.
However, this is just a partial solution.
I did some digging and here are my findings
1. running mvn install inside drydock image runs quick, so this is not docker/overlay2 issue
2. running mvn install through shippable controlled build - crucially slow
3. running mvn -q install through shippable controller build - quite fast
conclusion: submitting output to shippable portal is slow as hell. That happens both on custom nodes and your nodes, so problem is definitely somewhere in your web interface API

**Comment by UncleTawnos** [comment]
yet another test (no cache enabled):
 mvn -q package -Dmaven.test.skip=true 1m 26s 
 mvn package -Dmaven.test.skip=true 37m 21s

**Comment by trriplejay** [comment]
thanks for the information. I'll open an internal ticket to investigate this. perhaps there's some contention for network connections with our log streaming.

**Comment by UncleTawnos** [comment]
I'd appreciate if you can share any findings

**Comment by nealeu** [comment]
I just spotted this issue, and it is an ongoing problem that I've experienced before.

Is there not some way that the container can be made independent of the relay of the output?  At the very least, whatever the relay mechanism is, it could do with far more buffering, which could easily be done in memory for 10 or 20 MB of buffer.

**Comment by manishas** [comment]
This is currently being worked on... you should see a big improvement next week after it reaches prod.

**Comment by ric03uec** [comment]
@UncleTawnos @nealeu we've completely overhauled the way we handled logging so the amount of logging should not affect the build times in any way now. The updated build runner was deployed a month ago and has been performing as expected. 
I'm going to go ahead and close this issue. Please feel free to reopen/comment if you're still facing any problems.

**Comment by nealeu** [comment]
@ric03uec Thanks for letting us know.
