### ISSUE TITLE
[Critical] Private docker registry integration stopped working

### ISSUE THREAD

**Issue by UncleTawnos** [Shippable/support#4027]
Since 20 minutes, all my builds first reported that they can't login to docker registry (Quay.io), then in subsequent build, they reported they don't even have access to requested integration.

While trying to recreate integration, I can select scope for any bitbucket account I have with exclusion the one I exactly want.

message: `subscriptionIntegrations.create failed with error: Validation error`
Selecting any other GIT account than bitbucket/humanoitgroup or github/UncleTawnos works well. Selecting "All subscriptions" causes all account being added but the two I've mentioned.

At the moment, Shippable is unusable from our point of view.

**Comment by a-murphy** [comment]
It looks like the account integration that the Quay.io subscription integration was allowing your projects to use was deleted.  If you've created a new account integration, you should be able to go to your subscription integration page (click the gears in the top right, then integrations from the subscription dashboard), click the integration name, and select the new account integration.

**Comment by UncleTawnos** [comment]
No, I'm using the same account. Nothing has changed on my side.

**Comment by a-murphy** [comment]
If you go to the integrations page for the subscription (it should have your subscription name at the top), are you able to see the subscription integration?

**Comment by UncleTawnos** [comment]
![shippable_quay](https://user-images.githubusercontent.com/16896018/34315861-a0f83754-e787-11e7-9911-1b225e073a12.png)
Yes I DO see the integration and I am unable  to delete if (`No access for subscriptionIntegration :id 9247`). Can you please do it? I'm even listed as an owner of the integration...

**Comment by a-murphy** [comment]
Could you try refreshing the page and editing or deleting it?  I think I've figured out the permissions problem; one of the projects it's configured to allow ended up with a duplicate in Shippable.  I'm removing the duplicate now so that it won't cause problems again.

**Comment by UncleTawnos** [comment]
`delete subscriptionIntegrationPermissionById for id: 5498 returned error: No projects found for projectId(s): 5a0d5e7508a557070010ec43`

**Comment by a-murphy** [comment]
I've deleted the subscription integration after confirming that no accounts appeared to have access to the allowed projects (this usually happens when the projects are deleted on the source provider). I haven't been able to determine how it recently stopped working for you, but you should be able to create a new integration with the same name.

**Comment by UncleTawnos** [comment]
works now:

I might have a clue for you
1. integration was created with bitbucket/humanitytoit account
2. Few weeks ago I had added Github/UncleTawnos account and allowed builds from it
3. yesterday access to a Github organization I used to work before was revoked, however this organization wasn't configured to neither use Shippable nor has access to the integration.

As shippable syncs with repository services once a while, this is the only change I can think of

**Comment by a-murphy** [comment]
Changes to your GitHub permissions shouldn't have any impact on your Bitbucket subscriptions.  Thank you for the additional information though.  Perhaps the account integration deletion occurred around the same time as a partial deletion of the subscription integration that reduced the list of projects allowed to use it.  If there were more projects in the list, it would explain why you were able to use it before.

Do you know if that subscription integration was using your account integration before, and do you remember if you deleted your account integration or changed the subscription scopes on it today?  In either case, the permissions on the subscription integration shouldn't have changed, so it's certainly something for us to look into.

**Comment by UncleTawnos** [comment]
shippable was activated with bitbucket, integration was for bitbucket subscription (one of many I'm involved into) and later one github organization was added to the integration.

nothing more has changed, no scope change today.
