### ISSUE TITLE
404 when clicking on runCI on dashboard

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4028]
Clicking on runCI on dashboard links to
https://app.shippable.com/bitbucket/silvercurve//runs/226/summary/console

Correct link:
https://app.shippable.com/bitbucket/silvercurve/sc-pp-backend/runs/226/1/console

**Comment by a-murphy** [comment]
Do these links consistently result in 404s for you, or is it just occasionally immediately after loading the page?  Could you also let us know which dashboard (subscription, account/home, or custom) and if this was the SPOG view or the grid view?  It looks like the project information hadn't loaded based on the missing name, but I haven't been able to reproduce this and more information will allow us to better search for the cause.

**Comment by BryanCrotaz** [comment]
It was repeatable with that project build and none of the others projects at that time. After the next build it went away.

**Comment by BryanCrotaz** [comment]
It was the subscription dashboard with the assembly line on it

**Comment by a-murphy** [comment]
No one has been able to reproduce this.  Please let us know if it happens again.
