### ISSUE TITLE
Have more than one custom node running on the same server

### ISSUE THREAD

**Issue by luislobo** [Shippable/support#4030]
Is it possible to run more than one custom node running on the same server?

Right now we only have one server but it could handle more nodes to have parallel test to be run on the same server. Is that possible?

**Comment by a-murphy** [comment]
It is not currently possible to initialize the same server as multiple nodes, unless you set up a separate VM on the server for each node.  Multiple build runners in the same location will interfere with each other, but isolating each of them in a virtual machine will avoid any conflicts between them.  You'll either have to run the manual initialization scripts or give each VM a different externally available IP address.

I'll leave this open as a feature request to see if we will be able to support parallel jobs on the same server in the future.

**Comment by luislobo** [comment]
Alright! yeah that would be a great addition. Thanks!

**Comment by manishas** [comment]
This isn't on the roadmap as of now, so closing this. Happy to reopen if we get a lot of interest around this.
