### ISSUE TITLE
Failed to get my organization:QingCloudContainerPlatform

### ISSUE THREAD

**Issue by martinyunify** [Shippable/support#4031]
### Description of your issue:
Failed to fetch my organization profile:QingCloudContainerPlatform

My org QingCloudContainerPlatform is not listed

**Comment by manishas** [comment]
@martinyunify can you try clicking on Profile in the left navbar and clicking Sync?

Also, if this is a newly created organization, you might need to enable third party apps - http://docs.shippable.com/getting-started/support/#why-cant-shippable-see-my-org-on-github

**Comment by martinyunify** [comment]
Thank you.
