### ISSUE TITLE
Attempting to deploy to AWS Sub-account

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4032]
We have a primary AWS account where we put our images into ECR. We are then deploying those images to ECS running under different sub-accounts (one for each client).

We'd like to be able to deploy to any of the environments without creating a whole bunch of sub-account credentials and Shippable integrations. 

What is the best way to do this? Is it possible for us to use credentials from the parent AWS account rather than credentials specific to each deployment?

Thanks for your guidance...

**Comment by trriplejay** [comment]
are the sub accounts actually part of the primary account, or are they just totally separate aws accounts? I'm not too familiar with what aws supports in this regard... i know they have this "cross account roles" feature which may allow you to do what you want.  The goal is to create one set of keys on the main account that has permission to perform ECS actions on all the other accounts.  Perhaps there's a way to give the main account permission to utilize those roles on the other accounts.

If you can make that set of keys, it should work on Shippable for controlling the deployments.

**Comment by manishas** [comment]
@ryan-kimber do you still need help with this?

**Comment by ryan-kimber** [comment]
We're having a bit of trouble, but are working it out. 
One thing we've learned is DO NOT USE ECR AS REGISTRY, especially if using sub-accounts. You have to create a 'repository' for each container image name, and grant permissions to each repository to each child account. It's craziness. Just use Docker Registry or Google Container Registry, then you can use one set of permissions for pulling images and manage a tonne of permissions each time you add a new child/sub-account.
