### ISSUE TITLE
split assembly line into multiple files

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4039]
My assembly line is approaching 400 lines of yaml and I'm no more than 20% through defining it.

How should I split it into a file per job or resource?

**Comment by scriptnull** [comment]
Hi @BryanCrotaz,

It is possible to organize jobs and resources by splitting them into different files. 

[The documentation](http://docs.shippable.com/platform/workflow/resource/syncrepo/#syncrepo) quotes 
> Note: Shippable only looks for files ending with shippable.yml. Names like shippable.yml.example are ignored, but example.shippable.yml will be processed.

So you could actually organize your resources and jobs by having `shippable.yml` files inside different directories or by having many `*.shippable.yml` files.
```
services-dir-structure/
|-- billing
|   `-- shippable.yml
|-- notification
|   `-- shippable.yml
`-- registration
    `-- shippable.yml
```
or 
```
services-file-structure/
|-- billing.shippable.yml
|-- notification.shippable.yml
`-- registration.shippable.yml
```
