### ISSUE TITLE
dashboard layout and routing is really weird

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4042]
<img width="648" alt="screen shot 2018-01-03 at 22 38 21" src="https://user-images.githubusercontent.com/2016523/34543050-f3d6f318-f0d6-11e7-8027-8588f2da16f7.png">

Especially bottom left there are much neater ways to lay that out - auto-routing weighting seems way off.

**Comment by BryanCrotaz** [comment]
Minimising line crossing would be a quick way to reconfigure the layout plugin

**Comment by avinci** [comment]
@BryanCrotaz we are already working on this. There is a beta version of this SaaS that we shipped last week. Do you mind trying that out and give us some feedback? 

There are a couple of bugs that we already know off. Big one being shared resources are not being connected e2e. We are pushing a fix this week.

**Comment by BryanCrotaz** [comment]
How?

**Comment by avinci** [comment]
On your SPOG Page, if you click the eye button, there is an option to try the new SPOG.

![screen shot 2018-02-14 at 8 21 10 am](https://user-images.githubusercontent.com/1302035/36215134-1c84c23c-1160-11e8-9ff4-deff72b1fab2.jpg)

**Comment by BryanCrotaz** [comment]
MUCH better, but still possible to improve

![image](https://user-images.githubusercontent.com/2016523/36215713-c61ccc10-11a4-11e8-8980-0e4a47a7e7c0.png)

**Comment by avinci** [comment]
yup, we are fine tuning it. Will get back to you after next deploy.

**Comment by BryanCrotaz** [comment]
thoughts...
![image](https://user-images.githubusercontent.com/2016523/36217037-51efabce-11a8-11e8-9301-de45e9c927da.png)

**Comment by avinci** [comment]
we release another version of it yesterday, can you try that and let me know. Agree on the cropping, we will change that

**Comment by BryanCrotaz** [comment]
Nearly there - consider allowing reordering IN connections to simplify the layout.

**Comment by manishas** [comment]
We have launched the Modern SPOG view which is a big improvement over old SPOG. We will keep improving it in future milestones based on customer feedback.

Closing this issue since this is an ongoing effort.

**Comment by BryanCrotaz** [comment]
How do we see the Modern SPOG?

**Comment by BryanCrotaz** [comment]
Ah - already using it and the above comments are still valid

**Comment by manishas** [comment]
![image](https://user-images.githubusercontent.com/2983749/39221446-c8e3ccfa-47eb-11e8-8677-54c5b6725588.png)

**Comment by manishas** [comment]
You can switch to Modern view... and then switch back to Classic from the same menu.

**Comment by manishas** [comment]
Hmm we lost track of the cropping of names comment. Let me reopen this issue and we'll take care of that.

**Comment by BryanCrotaz** [comment]
See issues #4284 #4285

**Comment by manishas** [comment]
Closing this since new issues have been opened.
