### ISSUE TITLE
I can't log in by bitbucket account

### ISSUE THREAD

**Issue by valus** [Shippable/support#4044]
### Description of your issue:
I can't log in to shippable. I am getting error:

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

My bitbucket login: marcin.stelmach@synerise.com

**Comment by rageshkrishna** [comment]
Hi @valus. I've unblocked your account. You should be able to log in now. Please let me know if you're still having trouble.
