### ISSUE TITLE
[Blocker] Project disappeared and can not be re-enabled

### ISSUE THREAD

**Issue by UncleTawnos** [Shippable/support#4045]
One of our projects (bitbucket source) has disappeared from shippable. It turns out it's not enabled anymore. Re-enabling it ends with error:

```deleteResourceById failed for id: 54430 returned error deleteVersionByResourceId for resourceId:54430 returned error: versions.destroy failed for resourceId: 54430 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"```

**Comment by a-murphy** [comment]
That project ended up listed twice in Shippable, causing it to appear not to be enabled when it should have been enabled.  I've removed the duplicate and the originally-enabled project should be accessible now.

**Comment by UncleTawnos** [comment]
Project is now visible, but builds fail

```  Setting up build directories for job: 5a548e07104d330700275f2f 0s  
  Validating dependencies to get previous job files 0s  
  Getting files of previous job 2s  
genExec|_common|getPreviousState|_getFiles, :getFilesByResourceId failed for resourceId: 54430 with error 404
  Job initialization complete 0s  
  Setting up dependency: analytics-backend_ciRepo  
```

ID 54430 suggests something is still off. Now it has started to be a blocker. Please fix it ASAP

**Comment by a-murphy** [comment]
Could you try running it again?  I've replaced the resource for which it was unable to get files.

**Comment by UncleTawnos** [comment]
I don't know if it's related, but now all actions button are missing - rerun, stop, start

**Comment by a-murphy** [comment]
Could you try synchronizing your account?  Click "profile" on the left and then the sync button.  Missing action buttons are usually the result of missing permissions and shouldn't be related to the earlier errors.

**Comment by UncleTawnos** [comment]
still no luck
1. project is NOT visible at project dashboard
2. project is shown as enable in "enable/disable projects" view
3. I can click in enable/disable projects view to go to project's dashboard
4. I see branches there (so sync is ok)
5. If I try to run a build on this project, I get auth error
```Warning: Permanently added the RSA host key for IP address '104.192.143.3' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
other projects from the same subscription works seemlesly. I tried to disable and re-enable project - no luck. I definitely have correct rights to the project (I can pull/push without issues)

**Comment by a-murphy** [comment]
This error usually occurs when the deploy key has been removed from the source provider.  If this is the case, clicking the "reset all keys" button on the project settings page will add the key back.  However, [Bitbucket has reported errors today](https://status.bitbucket.org/) and it may just be that you will need to try again.

**Comment by UncleTawnos** [comment]
looks like it's cloning now, but can't really tell as bitbucket is still extremely slow. I will let you know either it builds or timeouts
