### ISSUE TITLE
Docs link for nodes broken

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4046]
The *Docs* link on https://app.shippable.com/subs/bitbucket/<account>/nodes currently leads to http://docs.shippable.com/ci/machine-images/overview/ which throws a 403 error. I guess this should be changed to http://docs.shippable.com/platform/runtime/machine-image/ami-overview/ instead. And please consider setting up redirects for cases like these.

**Comment by ambarish2012** [comment]
@mbrodala thanks for reporting this, fixing this now.

**Comment by manishas** [comment]
this should be fixed. closing.

**Comment by mbrodala** [comment]
Yes, there is a redirect now, thanks. :-)

**Comment by ambarish2012** [comment]
:).
