### ISSUE TITLE
Deployment failure to AWS ECS

### ISSUE THREAD

**Issue by ritch-parker** [Shippable/support#4047]
### Description of your issue:
We are currently experiencing failures in one of our deloyments.  The console shows a failure, but could not find a specific indicator as to what was failing.  AWS ECS deployment.

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/bitbucket/repomode/jobs/splat-nginx-deploy-dev-int/builds/5a53d7e6c4f4f80700b469b8/console

- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
we're looking into this.

**Comment by trriplejay** [comment]
it seems to be related to the name of the dockerOptions resource. A temporary workaround is to move that IN statement of the dockerOptions down to be the last IN of the job (after the elb but before TASK).

We're continuing to investigate and will release a patch once resolved.

**Comment by ritch-parker** [comment]
Ok, that worked.   Thanks for the update.

**Comment by a-murphy** [comment]
We've fixed the error processing resources with names that start with a number.  Let us know if you still see any problems.
