### ISSUE TITLE
Deployment Error on ECS: Not authorized to perform iam:PassRole

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4048]
I have not seen this before. 

Extending an existing deployment to add another cluster target, but we're getting this error when we try to run the job to deploy that cluster.

This is using the same manifests and credentials that work against other clusters in the same account.

![screen shot 2018-01-08 at 8 27 00 pm](https://user-images.githubusercontent.com/1018189/34700740-997029e6-f4b2-11e7-8dfb-24e5c160161e.png)

**Comment by ryan-kimber** [comment]
I've temporarily given our shippable-deploy account full account privileges in IAM, and now the deploy works, but I hope we don't have to keep it this way. 

Can you advise on what least-privilege policies the deploy user requires?

**Comment by manishas** [comment]
@trriplejay can you please follow up on this?

**Comment by trriplejay** [comment]
just to give an update, we are working on this. we'll be updating the documentation to make it clear what permissions we require and for what reason.

**Comment by trriplejay** [comment]
Hi Ryan,

We've added explicit policy information to the AWS integration pages here: http://docs.shippable.com/platform/integration/aws-keys/#iam-policies

let me know if you think anything is missing.

**Comment by ryan-kimber** [comment]
Thanks guys, this is great, but I do think it's missing an important piece
of information.

Whenever we have to supply the ARN for a shippable "LoadBalancer", you
actually want the ARN for the AWS Target Group.

That should be really clear in the documentation, but even better, it's
easy for you to pick up in the YML file: target groups will all have an
indicator in the ARN that it's a target group. It would be great if the
shippable job was able to spit out a message telling me it found the ARN
for a LoadBalancer but was expecting the ARN for a Target Group.

**Comment by trriplejay** [comment]
Yes, we are still adding that info. it became part of a separate issue.

You can see the upcoming change in this pr: https://github.com/Shippable/docs/pull/901

also, we have added functionality to the deploy job itself that will allow Shippable to print a more specific error message when the ARN appears wrong (in other words, if it appears to be an ALB arn, we will print a message saying to make sure it is the targetgroup arn instead).  

That feature and these docs will be live in our next release.
