### ISSUE TITLE
Trying to pin image versionName, getting version/propertyBag error

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4050]
I have configured one of our manifests to pin the image tag for a couple of our images, but [we are now receiving an error when manifest is built](https://app.shippable.com/github/formhero/jobs/bmo-services-manifest/builds/5a54ed4310b5120700aef40c/console), as illustrated below:

![screen shot 2018-01-09 at 11 27 49 am](https://user-images.githubusercontent.com/1018189/34731461-6410b832-f530-11e7-96cb-f11a69d59510.png)

I have confirmed that the images exist in our image repository with those tags. The config from our shippable.jobs.yml is seen below:

![screen shot 2018-01-09 at 11 31 46 am](https://user-images.githubusercontent.com/1018189/34731587-b755d860-f530-11e7-8dd5-067074c6a291.png)

I've tried  re-running the jobs that build those images and they are tagging the images properly and pushing them to the repo. 

Could you point me in the right direction to help me resolve this?

Thanks!

**Comment by ryan-kimber** [comment]
Are we only able to use tags that have been previously generated by Shippable? My hope was that we could manually tag images in our image repo, and pin using those tag names. 

Is that not the case?

**Comment by trriplejay** [comment]
it has to be the versionName or ID from shippable. shippable doesn't have to create the image tag itself, but it needs a reference to it. you can do this by manually specifying the tag in the `versionName` in the image resource.

**Comment by ryan-kimber** [comment]
Does that mean we can leave out the 'seedVersion' property for those images?

**Comment by trriplejay** [comment]
any time you push a change to the seed it will create a new version of that image on shippable which can then be referenced as a pinned IN, so if you already had a tag that you wanted shippable to know about, you can update the seed section to have that tag as the versionName, push the change, and when rSync runs, it should create the new version of that image with that tag.

**Comment by ryan-kimber** [comment]
Great. Thanks John.

**Comment by manishas** [comment]
Closing this since it's answered.
