### ISSUE TITLE
Moving a Resource from one Sync Repo to another...

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4051]
We have one core CI repository we use for core artifacts, and additional repos used for specific builds for clients (which use images/manifests, etc from the core repo).

Occasionally, we end up with an element for one build that needs to be reused for other builds.

How can I move an item, such as a reference to a syncRepo, from one GitHub project to another? I end up with errors claiming the item already exists, such as the once below: 

![screen shot 2018-01-09 at 1 49 46 pm](https://user-images.githubusercontent.com/1018189/34737386-0316d476-f544-11e7-9b63-3ed9bc5ff64e.png)

**Comment by trriplejay** [comment]
we have some documentation here on how to move resources from one syncRepo to another. give this a try and let me know if you run into problems:
http://docs.shippable.com/validate/configuration/#migrating-pipeline-resources-from-one-repository-to-another

**Comment by ryan-kimber** [comment]
Excellent, but I get stuck on https://github.com/Shippable/support/issues/4053

**Comment by ryan-kimber** [comment]
Ugh. Got our repo restored, but it came up like this:

![screen shot 2018-01-09 at 3 20 35 pm](https://user-images.githubusercontent.com/1018189/34741518-dd66d674-f550-11e7-8a70-9149a6c0b767.png)

And, even with it paused, I still get the same error when sync'ing the main formhero/continuous-deployment repo: 

![Uploading Screen Shot 2018-01-09 at 1.49.46 PM.png…]()

**Comment by trriplejay** [comment]
hmm, this sync repo was "added back", was it originally soft-deleted or fully removed? were these other resources already moved to other syncRepos?

**Comment by ryan-kimber** [comment]
Honestly, I don't know. I'm not sure why that repo stopped showing.

**Comment by ryan-kimber** [comment]
Is my best solution to delete everything and start over?

**Comment by trriplejay** [comment]
i think we can get it figured out. being unable to migrate the runCI according to the docs might be a bug.

It looks to me like you might have two of the same syncRepo added with different names:
`td-smartforms-deploy_master`and `smartforms-deploy-td_master`, i think this might be where the duplicates are coming from.

**Comment by ryan-kimber** [comment]
Is there a way for me to remove one of those?

**Comment by trriplejay** [comment]
if you look at the "resources" section of the grid view, all of your "syncRepo"s will have a delete button. that will remove the syncRepo and the associated rSync job.  Then, check your "deleted resources" section and remove that same repo again to remove it completely.

**Comment by ryan-kimber** [comment]
Unfortunately, this indicates that the syncRepo will be removed, but it doesn't actually come out of the list. I refresh the browser window and the item rematerializes.

**Comment by manishas** [comment]
@ryan-kimber is this resolved or do you still need help with this?
