### ISSUE TITLE
Sync Repo doesn't appear, error if I try to add it back...

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4053]
Our subscription is: https://app.shippable.com/subs/github/formhero

The sync repo I'm having trouble with is smart-forms-deploy-td. 

I can see the repo in the add sync repo panel, but if I try to add it, I get the following message: 

![screen shot 2018-01-09 at 2 30 55 pm](https://user-images.githubusercontent.com/1018189/34739825-8455900c-f54b-11e7-8cb7-7e5867d4262a.png)

Reviewing the permissions on GitHub though, this repo has the same users/permissions configured as our other sync repos. 

I need to be able to add it back in order to pause it so I can migrate resources out of it.

**Comment by trriplejay** [comment]
which subscription integration are you selecting when adding this syncRepo? that integration needs to have the correct permission on the repo.

**Comment by ryan-kimber** [comment]
Fixed! One of our developers was somehow able to add their own token with the same name we were using for our org credentials. 

I've delete those tokens and recreated and now it's working properly. On to migrating resources!
