### ISSUE TITLE
rSync Job Just Hanging

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4057]
Odd. My entire subscription disappeared from Shippable. I had to re-sync the SCM repos on my profile to bring it back (logging out and back in didn't bring it back).

When I did get it back, one of our rSync jobs (which had recently had a commit) was hanging, and there's no way to cancel it (resetting it just queues another job). It indicates it wrote a token to vault, but won't proceed past this point, and I can't find a way to kill it. Trying to re-run or reset the job only queues more items behind the stuck one.

![screen shot 2018-01-10 at 9 08 34 pm](https://user-images.githubusercontent.com/1018189/34805196-ccdb0ec4-f64a-11e7-9092-3a020ed60b97.png)

This is preventing me from fixing some other jobs that are relying on changes to resources defined in this repo.

I'm also unable to delete and re-add the repository, as the delete fails with an error indicating the resource "has incomplete jobs".

**Comment by ryan-kimber** [comment]
![screen shot 2018-01-10 at 9 57 34 pm](https://user-images.githubusercontent.com/1018189/34806493-4fe79b42-f651-11e7-9458-8dab4801c1c5.png)

**Comment by trriplejay** [comment]
looking at this now

**Comment by trriplejay** [comment]
given your description (subscription disappearing) it sounds like something must have happened during a periodic account sync that caused you to temporarily lose permissions.  If your rSync job tried to run while this was happening, it would have gotten stuck like it did.  This is a known effect when a user loses permission on a project while a job is in the middle of running.

Not sure why the permission loss occurred in the first place, I'll investigate, but it looks like after i cleared your stuck job, the others ran as normal.  Let me know if anything else is out of place.

**Comment by ryan-kimber** [comment]
Thanks John! Happy to be moving again. Terrible timing for this, but I
guess that's Murphy's Law.
