### ISSUE TITLE
Login via BitBucket violates security policy

### ISSUE THREAD

**Issue by timorl1** [Shippable/support#4058]
Every time when I try to login with my BitBucket account I get:

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

I have no idea what the issue is. 
BitBucket profile name is timolehtola

**Comment by manishas** [comment]
@timolehtola I have unblocked your account. Let me know if you run into any issues logging in now.
