### ISSUE TITLE
Using Google Container Registry for AWS ECS deployments

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4059]
Our CI processes are building and pushing images to Google's Container Registry (which we like, because the GCR doesn't require you create a separate repository for every image name).

We are trying to then use those images in our deploy to AWS ECS, but the deployments all fail trying to pull the images. When I dig into the logs on ECS, it is trying to pull the images from Amazon ECR instead of Google GCR. 

Is this configuration possible with Shippable? Is there a piece of configuration I am missing? I don't see any options for setting the container registry in the deploy resource documentation.

**Comment by ryan-kimber** [comment]
I tried to delete my old ECR integration (which my shippable.yml files no longer point to), but the resources that *used* to use the ECR integration fail, complaining that it's missing, even though they no longer refer to it.

**Comment by ryan-kimber** [comment]
Is it that you can't change the repo and image resource is associated with?

**Comment by trriplejay** [comment]
If the resources are deleted but not fully removed then it will still show that error. Could this be from one of your resources that wouldn't fully delete? 

Maybe check your deleted resources list and see if one of them might reference it.

**Comment by trriplejay** [comment]
Also, when deploying, we don't pass on the private registry credentials. Today we are assuming that the hosts are properly configured to pull any image passed in, so you may need to manually authenticate gcr on the hosts.

**Comment by ryan-kimber** [comment]
Thanks John.  This makes sense. I'm assuming it is not possible to configure that through our shippable.jobs.yml. Is that correct?

**Comment by trriplejay** [comment]
That's correct.
