### ISSUE TITLE
AWS ECR account integration (deprecated) cannot be re-pointed at AWS Keys integrations

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4060]
In an effort to clean up a dependency we no longer have (we're trying to use GCR for all of our images), I deleted our AWS ECR Account Integration. 

Now all hell has broken loose. I can't build anything, and I can't re-add the account integration because AWS IAM and AWS Keys are the only AWS options. The subscription integration settings screen won't allow me to change the type, and doesn't give me any options.

![screen shot 2018-01-11 at 11 06 38 am](https://user-images.githubusercontent.com/1018189/34834270-a2722f26-f6bf-11e7-857f-df0556591e13.png)

All of our builds are broken, and I'm trying to get an emergency deploy out that has active customers down.

**Comment by a-murphy** [comment]
You should be able to create an AWS Keys integration with the same name and use that in CI projects with no changes to your shippable.yml file.

**Comment by a-murphy** [comment]
It looks like your subscription integration isn't connected to the account integration.  Could you go to your subscription settings page (gears in the top right on the subscription dashboard) and add the account integration to the subscription integration?

**Comment by trriplejay** [comment]
I've opened an internal issue for not being able to change the type associated with a subscriptionIntegration.  This would have allowed you to pick your awsKeys integration to replace the deprectead ECR integration.  Will update this issue once that fix is released.

**Comment by ryan-kimber** [comment]
Thanks all. Glad we're back up and running. Looking forward to that bug fix too.

**Comment by trriplejay** [comment]
As of this current release, you are now allowed to change the "type" associated with a subscriptionIntegration.  This means that a subscription integration that was originally created for a now-deprecated AWS integration can be switched to a new `awsKeys` integration without having to create a new subscriptionIntegration and change any of the configuration yml.

**Comment by ryan-kimber** [comment]
Awesome!
