### ISSUE TITLE
Tests for an app that invokes docker work outside of Shippable but not in Shippable

### ISSUE THREAD

**Issue by clippermadness** [Shippable/support#4062]
One of the applications that we build on Shippable needs to invoke scripts inside of docker containers. That is part of its functionality.

We have tests that induce the app to invoke docker. They run correctly outside of Shippable, but fail inside of Shippable.

The application invokes docker like so (a concrete example can be found in the logs of the build I like to below):
docker run --rm -a stderr -a stdout -i -v /src/dir:/root/bin -v /tmp/dir:/root/data -w /root/data python:3.5 /root/bin/test.py

The errors imply that the mounted directory /src/dir can't be read from within the launched docker container:
starting container process caused "exec: \"/root/bin/test.py\": stat /root/bin/test.py: no such file or directory"

Is there a way to work around this?

Here is the latest "unstable" build, with a test failing:
https://app.shippable.com/bitbucket/thetalake/classifier/runs/36/1/console

**Comment by a-murphy** [comment]
To make `docker` available in the build containers, it's mounted from the host.  As a result, volume mounts specified in a `docker run` in the build script will be between the new container and the host, not the build container and the new container.  You can get around this by also mounting the same directory on the host to the build container.  One way to do this is by adding the volume mount (for the build container) to `options` in the `pre_ci_boot` section of your [shippable.yml](http://docs.shippable.com/ci/yml-structure/).  A more detailed example is available [here](https://github.com/Shippable/support/issues/3438#issuecomment-286708567).

**Comment by clippermadness** [comment]
Does the directory mounted from the host in pre_ci_boot have to be exactly the same as the one that is mounted in the docker container I invoke? Ideally, I'd like to be able to share a top level directory with the host, then mount different sub-directories with the containers I launch.

**Comment by a-murphy** [comment]
No, they don't have to match exactly as long as the files you need are included in both. What you've described should work just as well as if you had added each subdirectory to both.  However, you may want to create your own directory for the top-level directory, if you weren't already planning to, to avoid accidentally sharing or overwriting system files.
