### ISSUE TITLE
Image Pointers Immutable?

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4063]
We have been migrating some of our images from Google Container Registry to AWS ECR, and we've also renamed a few images.

I've noticed that changes we make to the pointer for any of our image resources are never reflected in our deployments (that is, if we change a pointer path, the deployment still tries to pull the image from the original location).

This has meant that we have to create all new image resources in our yamls and update all references to them.

Is this the expected behaviour?

**Comment by a-murphy** [comment]
No, that is not expected.  A new version of the resource should have been created with the updated `pointer` values.  If you deployed the latest version of the image, it should have used the new `pointer` value.  Were your image inputs to your manifest jobs pinned to use a particular version?  That would explain why they were using the previous value.

**Comment by ryan-kimber** [comment]
This is working properly on a clean setup. I'm sure the issue had something to do with the mess I made of our previous config. I'm going to close the issue. 

Thanks.
