### ISSUE TITLE
Cancel job during the build.

### ISSUE THREAD

**Issue by eddwardo** [Shippable/support#4065]
Question. Is there any command that I can invoke in order to cancel the build?
As a matrix I have a list of paths that point to subprojects in monorepo. But I'd like to cancel builds that have empty diffs with master branch.

Or ideally, not to run the build at all.

**Comment by a-murphy** [comment]
We don't currently have a way to cancel an individual item in a matrix; if any item is canceled, we'll consider the whole run.  There is an [API route](http://docs.shippable.com/platform/api/api-overview/#!/Runs/post_runs_runId_cancel) that can be used to cancel a run, if that is what you intended, although this API route will require a paid account.

A more practical solution may be to set an environment variable early in your build when you determine if it has changed or not and then skip the rest of the commands if it hasn't.  An example of running commands only when a variable is set to a particular value is [in the documentation here](http://docs.shippable.com/ci/env-vars/).
