### ISSUE TITLE
Missing "Re-initialize" button on custom nodes

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4067]
While re-initializing our custom nodes I noticed that two of them are missing the button for this action: `59774677343b2007000cf0c4` and `59771e7c490381060071d26f`. The other two are fine AFAIS.

Can you have a look please?

**Comment by ric03uec** [comment]
@mbrodala can you try re-initialize the nodes again. We've fixed the incorrect status  for the nodes.

**Comment by mbrodala** [comment]
The button did show up again, thanks for fixing.

(The node now hangs at `Removing stale exec containers` for quite a while but I'll keep waiting.)
