### ISSUE TITLE
I got Ubuntu 14.04.5 LTS when I use v5.10.4 as default image

### ISSUE THREAD

**Issue by martinyunify** [Shippable/support#4068]
I found that the base image is Ubuntu 14.04.5 LTS when I use v5.10.4 as the default node image. 

But I need to install skopeo which only provides deb package for Ubuntu 16.04. 

Could you please help me figure it out? 

I'm working on build process for github.com/QingCloudContainerPlatform. Thanks!

**Comment by a-murphy** [comment]
We're currently working on some updates to Assembly Lines that will allow runSh jobs to use the same images as CI jobs.  It's planned to be available in the near future, but until then we're unable to change the image used in a runSh job.  If you're able to enable a repository as a [CI](http://docs.shippable.com/ci/why-continuous-integration/) job that runs your script, it will use the default image you selected (and the default branch can still be triggered by a time resource in the same way that you have your runSh job set up).

I'll see if I can get an up-to-date estimate of when other images will be available in runSh to help you decide if it's worth converting that job to runCI.

**Comment by martinyunify** [comment]
I will migrate to runCI instead. Thanks!

**Comment by manishas** [comment]
@martinyunify custom images for runsh will be available in less than 2 weeks.
