### ISSUE TITLE
Upgrade Cassandra Service to Datastax Community Edition

### ISSUE THREAD

**Issue by tristanwietsma** [Shippable/support#407]
Moving from Shippable/sample_ruby_cassandra#3

The current Cassandra service minion is running 1.1.12, which is over a year behind the current stable release (2.0.9).

Travis-CI's Cassandra service is based on the Datastax Community Edition:
http://docs.travis-ci.com/user/database-setup/#Cassandra
http://planetcassandra.org/cassandra/

Please consider upgrading Cassandra to the latest stable release in the very near future. I'm running into API changes between the preferred client and your minion, rendering the service unusable.

**Comment by gtaylor** [comment]
We require this as well to use Shippable. I couldn't find evidence in the documentation that Cassandra is even supported anymore, though.

Any idea on where this stands?

**Comment by manishas** [comment]
This is not on our roadmap for now, so closing this issue.
