### ISSUE TITLE
Failed to deploy manifest for type: replace

### ISSUE THREAD

**Issue by bdrachinsky** [Shippable/support#4070]
I'm trying to deploy on AWS EC2 instance but deployment job failed.
I have the same scripts that I've found here: https://github.com/devops-recipes/deploy-ecs-basic/blob/master/shippable.yml
amazon user policies is: 
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "elasticloadbalancing:ConfigureHealthCheck",
                "elasticloadbalancing:DescribeLoadBalancers",
                "iam:ListRoles",
                "iam:PassRole",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ecs:DescribeClusters",
                "ecs:ListClusters",
                "ecs:RegisterTaskDefinition",
                "ecs:DeregisterTaskDefinition",
                "ecs:ListTaskDefinitions",
                "ecs:DescribeServices",
                "ecs:UpdateService",
                "ecs:DeleteService",
                "ecs:CreateService",
                "ecs:ListTasks",
                "ecs:ListContainerInstances",
                "ecs:DescribeContainerInstances",
                "ecr:GetAuthorizationToken"
            ],
            "Resource": "*"
        }
    ]
}`
My ymls here:
https://bitbucket.org/bdrachinsky/awsrep/src
That's the log:
https://app.shippable.com/bitbucket/bdrachinsky/jobs/shipdemo-test-deploy/builds/5a5fbd4f7a1ff70700e80a7e/console

I appreciate any suggestions.

**Comment by a-murphy** [comment]
Have you checked for any events in the AWS Console?  If you navigate to your cluster in the Amazon ECS and click on the service, there's an "events" tab that contains messages for the service.  Normally, these will be shown in the Shippable logs as well if it fails, but in your case it may be worth checking.

The most common reason for failed deployments to AWS is that the tasks couldn't be placed.  Do you have an instance in your cluster with enough space to run the task and any ports that you are using available?

**Comment by bdrachinsky** [comment]
Ye, I found this

> service shipdemo-test-deploy-shipdemo-manifest was unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your cluster.

As I understood I need to add more a policy. Am I right?

**Comment by a-murphy** [comment]
No, adding to the policy is unlikely to help.  The AWS container instances are Amazon EC2 instances that are used to run the containers.  Shippable doesn't create these in deploy jobs; they're expected to already exist and the same cluster will very often be used for multiple deploy jobs.  Amazon has documentation for container instances [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_instances.html).

Depending on what type of cluster you have, you can either [scale the cluster](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/scale_cluster.html) or [manually launch a new container instance in EC2](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html).  Amazon also has auto scaling options for clusters that you can set up.

**Comment by bdrachinsky** [comment]
To be clear --
In my integrations I should use the same role (AWS IAM integration) that I attached to the instance?
I think I don't understand how it works right now. I was working with ECR integration few month ago and it was perfect for me.

Few steps that I've made on my AWS:
1. Created user with policies described here http://docs.shippable.com/platform/tutorial/integration/howto-create-AWS-IAM-access/#policy
and added 1 more policy "ecr:GetAuthorizationToken"

2. Created role as were described [here ]
![image](https://user-images.githubusercontent.com/13419649/35154198-00c9c2d2-fd32-11e7-8e36-5f2e16921986.png)
I added AdministratorAccess because I want to start use it and I hoped this will resolve everything.

3. My trust policy is the same as their

> {
>   "Version": "2008-10-17",
>   "Statement": [
>     {
>       "Sid": "",
>       "Effect": "Allow",
>       "Principal": {
>         "Service": "ec2.amazonaws.com"
>       },
>       "Action": "sts:AssumeRole"
>     }
>   ]
> }

Still have the same problem. Any suggestion where I failed?

**Comment by a-murphy** [comment]
It sounds like someone deleted the cluster instance in your cluster on AWS so you wouldn't be billed for it.

Does the "ECS instances" tab in your cluster have a "scale ECS instances" button like this?
![screenshot from 2018-01-19 09 41 17](https://user-images.githubusercontent.com/5492015/35163935-2a6d1772-fcfd-11e7-980e-1d82ba730193.png)

If you have a scale button, click it and then scale your cluster to (at least) one instance.

Or does your "ECS instances" tab look like this, without a scale button?
![screenshot from 2018-01-19 09 38 34](https://user-images.githubusercontent.com/5492015/35163971-504f1242-fcfd-11e7-9eff-48efaf71203f.png)

If you don't have a scale button, you'll need to follow [these directions](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_container_instance.html).

**Comment by bdrachinsky** [comment]
My "ECS instances" tab without a scale button.
Okay, Amazon changed a lot of stuff recently. I hope they have free tier instance on my test purposes

**Comment by bdrachinsky** [comment]
@a-murphy 
I have created ami-1d46df64 and it generated the cluster named "default"
Can I rename this cluster or delete it and create my own?

**Comment by a-murphy** [comment]
I don't think it's possible to rename a cluster.  You can delete clusters and create a new one if you wish to.

It sounds like you forgot to include the "user data" in step 8g when stating your new container instance.

**Comment by bdrachinsky** [comment]
@a-murphy Thank you, you help me a lot
