### ISSUE TITLE
Custom nodes are "Waiting"

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4072]
Currently we see that 3 of 4 of our custom nodes are **Waiting** according to the Nodes list. What is the reason for this? The 4th one shows up normally as **Success**.

Possibly due to this we see builds hanging at the **Provision job node** step, e.g. build 115 of project `57a46ae3d640fc0d00f8d846`.

Can you have a look at this?

**Comment by rageshkrishna** [comment]
"Waiting" typically means that the build runners have not yet reported a healthy status after restarting themselves at the end of a build. Can you check if the `genexec` containers are running on these machines, and if their docker logs are reporting any errors?

**Comment by mbrodala** [comment]
The container seems to be running:

```
$ docker container ls
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS               NAMES
a7264e08952d        drydock/genexec:v6.1.2   "/home/shippable/m..."   46 hours ago        Up 16 hours                             shippable-exec-59774677343b2007000cf0c4
```

The logs for this container indeed indicate some error:

```
$ docker container logs a7264e08952d
forever is NOT watching file changes
...
2018-01-17T18:31:27.340Z - info: Checking system config for msName:genExec
2018-01-17T18:31:27.344Z - info: system config checks for msName:genExec succeeded
2018-01-17T18:31:27.345Z - info: Starting genExec
2018-01-17T18:31:27.346Z - verbose: Initializing ShippableAdapter
2018-01-17T18:31:27.346Z - verbose: Initializing genExec
2018-01-17T18:31:27.349Z - verbose: Checking health of genExec|_common|checkHealth
2018-01-17T18:31:27.350Z - verbose: Checking health of genExec|micro|_healthCheck|amqpMonitor
2018-01-17T18:31:27.759Z - verbose: Connected from genExec to Q amqps://<auth>@msg.shippable.com:5671/shippable
2018-01-17T18:31:27.760Z - verbose: Closed connection from genExec to Q amqps://<auth>@msg.shippable.com:5671/shippable
2018-01-17T18:31:27.761Z - verbose: genExec|micro|_healthCheck|amqpMonitor Successful health checks
2018-01-17T18:31:27.762Z - verbose: Checking health of genExec|micro|_healthCheck|checkShippableApi
2018-01-17T18:31:27.763Z - verbose: Initializing ShippableAdapter
2018-01-17T18:31:27.933Z - verbose: genExec|micro|_healthCheck|checkShippableApi Successful health checks
2018-01-17T18:31:27.933Z - verbose: genExec|_common|updateNodeStatus Starting
2018-01-17T18:31:27.934Z - verbose: Initializing ShippableAdapter
2018-01-17T18:31:28.073Z - verbose: genExec|_common|updateNodeStatus Successfully updated node status
2018-01-17T18:31:28.075Z - verbose: Validating node status of nodeId: 59774677343b2007000cf0c4
2018-01-17T18:31:28.077Z - verbose: Initializing ShippableAdapter
2018-01-17T18:31:28.078Z - verbose: genExec|_common|validateNode Successfully validated node status
2018-01-17T18:31:28.079Z - verbose: Skipping service call home as this is not a serviceNode
2018-01-17T18:31:28.079Z - verbose: Validating node status of nodeId: 59774677343b2007000cf0c4
2018-01-17T18:31:28.088Z - verbose: Initializing ShippableAdapter
2018-01-17T18:31:28.088Z - verbose: genExec|_common|postNodeStats Successfully validated node status
2018-01-17T18:31:28.089Z - verbose: genExec|_common|checkHealth Successful health checks
2018-01-17T18:31:28.089Z - verbose: genExec| getting systemSettings
2018-01-17T18:31:28.090Z - verbose: genExec| setting runMode
2018-01-18T08:39:13.212Z - error: Failed to stop cexec container with err:Error: Command failed: docker ps | grep 'c.exec.' | awk '{print $1}' | xargs -I {} docker rm -fv {}
2018-01-18T08:39:13.215Z - warn: Unable to perform restart with err:Error: Command failed: docker ps | grep 'c.exec.' | awk '{print $1}' | xargs -I {} docker rm -fv {}
Error response from daemon: Unable to remove filesystem for 8c12e1b73279a610891426eda0f2886016da23193bc67840904a71f790ad6d23: remove /var/lib/docker/containers/8c12e1b73279a610891426eda0f2886016da23193bc67840904a71f790ad6d23/shm: device or resource busy

Error response from daemon: Unable to remove filesystem for 8c12e1b73279a610891426eda0f2886016da23193bc67840904a71f790ad6d23: remove /var/lib/docker/containers/8c12e1b73279a610891426eda0f2886016da23193bc67840904a71f790ad6d23/shm: device or resource busy
```

Should I just re-initialize the node?

**Comment by mbrodala** [comment]
I just saw that the 3 affected nodes don't have an "Re-initialize" button just as reported in #4067.

**Comment by rageshkrishna** [comment]
This looks like an issue with docker not being able to stop a build container.

Please restart docker to see if this allows it to free up all the resources that the container is locking up. Let me know if it doesn't resolve it and I will manually update your node status so you can reinitialize it from Shippable.

**Comment by mbrodala** [comment]
Immediately after restarting Docker the node (`59774677343b2007000cf0c4` for example) came back alive and immediately started processing a job. I'll repeat this for the other 2 nodes and will let you know once I'm done. The re-initialize button is still missing on the node ATM.

**Comment by rageshkrishna** [comment]
The re-initialize button is shown only if the node is in one of the "terminal" states. If your node is processing a build, the button is currently expected to stay hidden.

**Comment by mbrodala** [comment]
Indeed, the button now shows up again if a node is idle. After restarting Docker I see that the last re-initialization for some nodes didn't succeed at all, it shows `drydock/genexec:v6.1.1` instead of `drydock/genexec:v6.1.2`. On one node I failed to restart Docker but succeeded in restarting the whole node.

Since the last (**Successful**) node didn't process any jobs I've tried to restart it too but it's totally broken now. But I'll take care of this, this is beyond the scope of Shippable. ;-)

Thanks for the hint!

**Comment by mbrodala** [comment]
In light of #4074 this issue has shown up again today. I had to manually restart Docker on our 3 build nodes to return back to normal. Can you have another look please?

**Comment by rageshkrishna** [comment]
It looks like this issue was first reported in Docker v1.11 and is still open: https://github.com/moby/moby/issues/27381

[One of the comments](https://github.com/moby/moby/issues/27381#issuecomment-257297822) in that really long discussion says this:

> Core of the issue here is that container is either still running or some of its mount points have leaked into other some mount namespace.

I am not really sure how that happens, though.

When did you first start experiencing these failures? Do you happen to know what might have changed just before you started running in to this?

**Comment by mbrodala** [comment]
Since this has started to occur recently it may be related to the last agent updates (6.1.1 and 6.1.2).

**Comment by rageshkrishna** [comment]
How about any changes on the host? Did the docker version change?

**Comment by mbrodala** [comment]
No change, the last package change related to Docker was the installation. Still running the expected 1.13:

```
# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by rageshkrishna** [comment]
Hmm, and was this the same version of Docker you were running before you updated to 6.1.x of the agent? 

I can't really see any changes in the agent with releases 6.1.1 or 6.1.2 that could have increased the likelihood of this error showing up because we haven't changed anything with regard to our interaction with docker or how build containers are brought up.

**Comment by mbrodala** [comment]
Yes, there where no changes at all to the Docker installation since 2017-07-25.

**Comment by mbrodala** [comment]
Once again two of our nodes (`59773e3d343b2007000cec71` and `59773933973f4d07008b4681`) went into the **Waiting** state and the genexec container logs show the known error message.

There are no genexec containers running on these two nodes anymore and it seems like the container has died:

```
# docker container ls -a
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                    PORTS               NAMES
94b7bf052061        drydock/u16phpall:v5.7.3   "/home/shippable/c..."   4 days ago          Exited (255) 3 days ago                       c.exec....
9c4f91007d52        902db7b5dd0c               "/home/shippable/m..."   11 days ago         Dead                                          shippable-exec-59773e3d343b2007000cec71
75e3ad04804a        drydock/u16phpall:v5.7.3   "/home/shippable/c..."   5 months ago        Created                                       c.exec....
```

Is there anything we can do here? As you can already guess the current state is problematic since we can run into all of our nodes suddenly being blocked and thus builds piling up in the queue preventing us from building and deploying changes.

Is there any way to revert to any 5.x image of genexec just to check if that's really not related?

**Comment by mbrodala** [comment]
Notice that I'm currently missing the Re-initialize button on the node `59773e3d343b2007000cec71` even after restarting it. No container is running on that node ATM.

**Comment by mbrodala** [comment]
After manually executing the `docker run` command from the last node reinitialization (and dropping the dead genexec container via `docker container rm <id>`) I was able to revive the node. The state has switched to **Success** again and the Re-initialize button has come back.

**Comment by rageshkrishna** [comment]
There's no way to switch genexec versions when using auto-initialization. If you really want to try it, you'll need to do the following:

1. Remove the node and add it again, but pick `Manual (script based)` as the initialization method this time
1. Download the resulting initialization script and change the `EXEC_IMAGE` environment variable from `drydock/genexec:v6.1.3` to the version you'd like to try out. Do you happen to know what version you were on before you reinitialized and got v6.x?

Is using docker 17.06 an option for you? I'd actually recommend trying that out first because this really seems like an issue with Docker and a more recent release might help.

**Comment by rageshkrishna** [comment]
@mbrodala I was wondering if you had any luck with either of these suggestions.

**Comment by mbrodala** [comment]
I've just upgraded to Docker 17.05 on one node (the [newest available](https://apt.dockerproject.org/repo/pool/main/d/docker-engine/)) and will check if that helps.

**Comment by mbrodala** [comment]
I just removed and re-added that node and by doing that the Shippable scripts replaced `docker-engine` with the newest `docker-ce` (*17.06*) which is fine I guess.

**Comment by mbrodala** [comment]
Since the issue has occurred again in the meantime on the remaining 3 nodes I've repeated the same procedure on these. I'll continue monitoring the situation.

**Comment by mbrodala** [comment]
Usually most of our nodes are "Waiting" after the weekend but everything seems fine today after the recent Docker updates. I'll let you know if the issue occurs again.
