### ISSUE TITLE
Using Docker Socket as Volume with ECS

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4073]
We're trying to add /var/run/docker.socket:/var/run/docker.socket as a volume which we can do when running our container locally or on ECS, but I can't seem to get that configured with Shippable. 

We've tried this in dockerOptions...
>   - name: aqua-security-agent-opts
>    type: dockerOptions
>   flags:
>     - release-2018-01-17
>    version:
>      volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>      memory: 256
>      cpuShares: 250

... but ECS ends up with the following: 

![screen shot 2018-01-18 at 11 15 02 am](https://user-images.githubusercontent.com/1018189/35108199-e9023ba8-fc40-11e7-8d45-7c64e7811ba2.png)

We also tried this, but got the same result: 
      volumes:
       - "docker-socket:/var/run/docker.sock:none"

Is there another way we should be approaching this?

**Comment by a-murphy** [comment]
The first method appears to be correct.  In source volume, "varrundockersock" is the name of the volume.  The path on the host should be under volumes in the task definition.  However, were you trying to add `docker.socket` or `docker.sock`?  You have both mentioned and the wrong path would explain it not working.

**Comment by ryan-kimber** [comment]
We're trying to add an actual 'socket', named docker.sock.

I'll go back to the first form. Thanks.

**Comment by a-murphy** [comment]
Have you gotten your mounted volumes to work, or are you still running into problems with this?
