### ISSUE TITLE
Run builds as non-root user

### ISSUE THREAD

**Issue by sazzer** [Shippable/support#4076]
I have a Java Build that uses the Embedded Postgres - https://github.com/yandex-qatools/postgresql-embedded - as part of the Integration tests. This allows the database to be created for the duration of the tests, and destroyed after, without any infrastructure provisioning at all needed.

Locally this works great. On Shippable this fails with:
> 00:14:58.698 [Thread-5] DEBUG r.y.q.e.p.e.LogWatchStreamProcessor - initdb: cannot be run as root
> 00:14:58.699 [Thread-5] DEBUG r.y.q.e.p.e.LogWatchStreamProcessor - Please log in (using, e.g., "su") as the (unprivileged) user that will
> 00:14:58.699 [Thread-5] DEBUG r.y.q.e.p.e.LogWatchStreamProcessor - own the server process.

Is there some way to configure my Maven build to run as a non-root user so that this will work correctly?

The build failure is at https://app.shippable.com/github/sazzer/spacegame/runs/11/1/console
The scripts called are:
```
mvn clean install -B
```

**Comment by manishas** [comment]
@ambarish2012 pls add this to the docs. We need to watch the support repo for anything that was asked because it’s undocumented and address it in the docs asap.

**Comment by ambarish2012** [comment]
Docs have been updated and instructions are available here - http://docs.shippable.com/ci/non-root/.

**Comment by sazzer** [comment]
Unfortunately I've just tried this out and it doesn't work. I get the following error:

```
  adduser --disabled-password --gecos "" ciuser 0s  
Adding user `ciuser' ...
Adding new group `ciuser' (1002) ...
Adding new user `ciuser' (1001) with group `ciuser' ...
Creating home directory `/home/ciuser' ...
Copying files from `/etc/skel' ...

  chown -R ciuser:ciuser $SHIPPABLE_BUILD_DIR/.. 0s  

  echo $SHIPPABLE_BUILD_DIR 0s  
/root/src/github.com/sazzer/worlds

  ls -l $SHIPPABLE_BUILD_DIR/../.. 0s  
total 4
drwxr-xr-x 3 ciuser ciuser 4096 Feb 14 14:48 sazzer

  su -c "whoami" ciuser 0s  
ciuser

  su -c "cd $SHIPPABLE_BUILD_DIR" ciuser 0s  
bash: line 0: cd: /root/src/github.com/sazzer/worlds: Permission denied
```

As seen here: https://app.shippable.com/github/sazzer/worlds/runs/13/1/console

The best I can think is because the new "ciuser" that was created is not allowed to access `/root`, and therefore the system isn't letting it access anything below that.

Now, I can obviously fix it by doing nasty things like making the entire `/root` accessible to my user, but that's no great. I've tried lots of things with `su` and `sudo` and so on, none of which have worked.

**Comment by ambarish2012** [comment]
@sazzer here is a working maven sample: https://github.com/ambarish2012/maven-samples/blob/master/shippable.yml. Link to my shippable build - https://app.shippable.com/github/ambarish2012/maven-samples/runs/6/1/console.

I am updating docs to include a step to copy the build directory to a folder in the ci user's home directory so that there are no issues with execute permissions for maven.

**Comment by sazzer** [comment]
That works great. Thanks :)
