### ISSUE TITLE
No projects found for projectId

### ISSUE THREAD

**Issue by UncleTawnos** [Shippable/support#4080]
While trying to access nodes configuration for bitbucket subcription

No projects found for projectId(s): 5a65d70c3e988107005697ab

**Comment by a-murphy** [comment]
It looks like one of the nodes was building a new project that we didn't know that you could access.  The error should disappear when your account is synchronized, and we'll look into finding a better way to show that the node is busy when you don't have access to the project.

**Comment by a-murphy** [comment]
The nodes page has been replaced by the node pools page, so this error can no longer occur.  Let us know if you still see any similar errors elsewhere.
