### ISSUE TITLE
 Your account has been blocked

### ISSUE THREAD

**Issue by iUwej** [Shippable/support#4087]
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

Account : suilujic_gro

**Comment by rageshkrishna** [comment]
Hi @iUwej! I've unblocked your account. Please let me know if you're still having issues.

**Comment by iUwej** [comment]
Great
Wait, is this an implicit feature?

**Comment by rageshkrishna** [comment]
We have some heuristics to identify accounts that might be bitcoin miners looking for free compute resources. As you've found out, this sometimes has false positives. Sorry for the trouble!
