### ISSUE TITLE
Link to changelog outdated (is 6.1.3, should be 6.1.4)

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4088]
Due to the agent update notification for our nodes I've seen that [Shippable 6.1.4](https://github.com/Shippable/admiral/blob/master/releaseNotes/v6.1.4.md) was released today.

However, the version and changelog link in the app still shows 6.1.3.

**Comment by rageshkrishna** [comment]
We just started rolling out the new version a few minutes ago, so you probably caught us in the middle of the load balancers switching over :) Can you please check if a refresh helps?

**Comment by mbrodala** [comment]
Yup, it's fine now, sorry for the noise. ;-)
