### ISSUE TITLE
Wrong shippable.yml in PR build

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4090]
Hi,
I have encountered a situation where a pull request (PR) build uses the `shippable.yml` file from the base branch. It looks similar to https://github.com/Shippable/support/issues/988#issuecomment-70636910.

### Description of my issue:
Two builds are run when I push commits to a PR-branch: a PR build (merges the base branch) and a branch build. My [PR build](https://app.shippable.com/github/damejidlo/kubernetes/runs/96/1/console) fails because it uses (incompatible) `shippable.yml` from the base (master) branch. In my case the CI step crashes when entering a directory that is no longer there. 
![image](https://user-images.githubusercontent.com/672781/35436856-560ca3aa-0290-11e8-8436-0f9142f03ca5.png)

The [branch build](https://app.shippable.com/github/damejidlo/kubernetes/runs/95/1/console) does not fail this way. 
![image](https://user-images.githubusercontent.com/672781/35436879-6d80c494-0290-11e8-889a-a811124d7ceb.png)

I have reproduced the git_sync behavior that fetches PR and merges it's base branch. The `shippable.yml` file does not contain the failing `cd code/` command. Therefore I think this may be a bug in shippable service.

----
 - A side note question: can I configure which of these builds shall be run?

**Comment by a-murphy** [comment]
Could you confirm that both branches have a `shippable.yml` (it wasn't renamed) and that it's included in your pull request? If the name doesn't match or the updates aren't in the pull request, it could explain why we used the file from the base branch.  And, is it a particularly large pull request?  If there are too many files, it's possible that we were unable to get the changes to that file in the pull request from GitHub.

If you only want to run commit or pull request builds, you can turn off the other one in the project settings.  The webhook config section at the top has options to enable or disable builds triggered by webhooks for commits, pull requests, tags, or releases.  If you only want to run builds for certain branches, that can be [configured in your shippable.yml](http://docs.shippable.com/ci/specify-branches/).

**Comment by RadekDvorak** [comment]
In the PR approximately 2800 files are moved from directory to directory. However the complete _git_sync_ phase takes only two seconds. Both branches contain `shippable.yml` in the root directory. Its content is changed in the PR as well (e.g. the echo statement in screenshots above).  

When I run a debug build, it fails as well because of those different CI steps that are in master branch only. Then I ssh to the machine to check the fetched files but find the correct PR `shippable.yml` there.  The directory I look in is `/root/src/github.com/{PROJECT}/{REPO}/`. Can I provide some further information to clarify the situation?

**Comment by a-murphy** [comment]
It's almost certainly a result of the number of files in your pull request.  Unfortunately, the GitHub API will only return 300 files in the pull request, and `shippable.yml` must not have been one of those files.  We fetch the YML file from the GitHub API in order to generate the matrix of builds without cloning the rest of your repository, so we aren't currently able to identify changes to a `shippable.yml` file in some large pull requests.

**Comment by RadekDvorak** [comment]
Well I guess we are going to have to get used to the bug. Thanks for the explanation though.
