### ISSUE TITLE
Docker Hub Integration failing to login

### ISSUE THREAD

**Issue by Jan0707** [Shippable/support#4094]
Hello Shippable,

Just today we discovered that our docker-hub integration is failing. Apparently shippable cannot login via the api. As seen in this build:

[https://app.shippable.com/bitbucket/lillydoo/sylius-standard/runs/5954/1/console](https://app.shippable.com/bitbucket/lillydoo/sylius-standard/runs/5954/1/console)

The credentials however have not been changed recently. I tried them myself directly on hub.docker.com and they work perfectly nice. Furthermore, in a different project, we use the same credentials, but login manually to docker hub like this:

`docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD`

Which also works fine, as seen in this build:

[https://app.shippable.com/bitbucket/lillydoo/lep-supply-toolbox/runs/1606/1/console](https://app.shippable.com/bitbucket/lillydoo/lep-supply-toolbox/runs/1606/1/console)

(See build step: `if [ "$IS_PULL_REQUEST" == true ]; then ./_ci/run-behat-ci.sh; fi` )

We therefore have to assume an error in your docker hub integration and Kindly ask you to look into it, as this blocks our builds and denies us any valid test results.

Kind regards,

Jan Gregor Emge-Triebel

**Comment by a-murphy** [comment]
Could you double-check that those builds are in fact using the same Docker Hub account and that you were able to log into Docker Hub with the account used by the failing build?  We haven't changed anything related to `docker login` recently.  The username in the integration is shown in the logs in the `hub_login` step of the failing build.  It doesn't appear to be in the logs of your other build, but someone with admin access to the subscription can decrypt the secure environment variable on the subscription settings page to confirm which account that build is using.

Your dockerhub subscription integration hasn't been changed recently, so it looks like the most likely cause is a changed password on Docker Hub.  If you are able to confirm that they are in fact using the same account, I would suggest retyping the Docker Hub password in the account integration attached to the subscription integration just in case it had been changed but not updated everywhere.  Please let us know if this works.

**Comment by Jan0707** [comment]
I changed the user that was stored in the integration. That did the trick.
