### ISSUE TITLE
Shallow clone for the git sync step

### ISSUE THREAD

**Issue by fieldawarepiotr** [Shippable/support#4096]
Hey,
Is it possible to customize git clone command somehow?
Our repo is quite big (~1.5GB - dont ask) and cloning it entirely every time doesn't make sense to us. I would like just `git clone --depth=1` to take only the latest changes.

**Comment by manishas** [comment]
This has been approved and will be available in < 3 weeks.

Closing this particular issue in favor of https://github.com/Shippable/support/issues/3862. Please follow 3862 for updates.
