### ISSUE TITLE
Build Stuck on "Saving Integrations to Vault"

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4097]
One of my builds is stuck here. This seems to happen occasionally. 

<img width="1817" alt="screen shot 2018-01-30 at 1 38 10 pm" src="https://user-images.githubusercontent.com/1018189/35584391-ec0d6990-05c2-11e8-8f2b-197ea62ac2eb.png">

It would be so great if we could cancel an in-progress deploy, even if it was only up to a certain point.

**Comment by ryan-kimber** [comment]
...eventually went through after an 18 minute pause.

**Comment by a-murphy** [comment]
It looks like the logs aren't in the correct order, we'll look into that.  The logs are usually ordered by time, and that section is from a different service than most of the deploy job.

**Comment by trriplejay** [comment]
This was due to a time difference between two of our servers. We've synchronized their clocks, and the steps should no longer appear out of order.
