### ISSUE TITLE
how to use different bumps against the same version? 

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#4098]
Hello, I 've spent some quality time with shipabble docs but still can not solve it.

My current release pipeline looks like this:  version->release_trigger(release job which just performs a bump)->runCLI job(which actually does all needed release operation) 
Every time we are ready to release trigger got executed, and everything works as desired. 

What I'm trying to get.
Make bump in release job configurable.  Ideally, take it as UI input. 
I even ok have 2-3 separate triggers (one per major, minor, path), but this approach is not working because versionName is stored inside release job, not a version resource. 

I've tried to version->releasejob->version but it doesn't work.

**Comment by a-murphy** [comment]
It's not currently possible to configure the release job in the UI.  You can change the seed versionName or the bump setting in your YML file.

In many cases you can set up multiple release jobs for different purposes, which would include different `bump` settings, that each increment the previous release job's versionName.  There's an example incrementing the version after a deploy job [here](http://docs.shippable.com/release/upstream-releases/), but you can also leave out the deploy job and connect one release job directly to the next.

If this isn't what you're looking for, would you mind explaining what your goal is?  Are the different bump types to be deployed differently, or in the same way?  Are there other inputs to the jobs?

**Comment by manishas** [comment]
@depohmel do you still need help with this?

**Comment by manishas** [comment]
Closing since this is stale a issue. Let us know if you have any additional qs.
