### ISSUE TITLE
Invoicing Info

### ISSUE THREAD

**Issue by dan0mau** [Shippable/support#4099]
Where on earth do you place data for invoicing?
I can't find it, I can't find where to place company name, Address and and most importantly the fiscal number.
With out it they can't be considered expenses in the EU. 
Got the financial / accounting bothering me about this, we may have to switch to someone else that allows this.

**Comment by dan0mau** [comment]
I need somewhere to at least place our fiscal number: "Fixeads SA- PT508069491"
How can that show up in the invoices?

**Comment by trriplejay** [comment]
Unfortunately we do not currently have a way to add custom information to the invoice, but I will mark this as a feature request and open an internal ticket.

**Comment by manishas** [comment]
@dan0mau you can also switch to annual billing since we issue invoices manually for that. We can issue a custom invoice with any information you need.

**Comment by trriplejay** [comment]
@dan0mau FYI we are adding this functionality in our next release (later this week). I'll update here once the feature is live.

**Comment by trriplejay** [comment]
@dan0mau Our latest release includes this support, and is now live.  The billing page of your subscription should have an "extra billing information" section where you can add whatever details you need.
