### ISSUE TITLE
No ciRepo jobDependency found

### ISSUE THREAD

**Issue by gleblozhkovoy** [Shippable/support#4103]
My repository name is 

> site.com

I tired

> sitecom_runCI
> site.com_runCI
> site_com_runCI

Nothing works.  Any suggestion?
Latest build
https://app.shippable.com/github/data-skeptic/jobs/dataskeptic_dev_rSync/builds/5a74c1a9a6e8350700dba01e/console

**Comment by a-murphy** [comment]
The name of the runCI job should be `sitecom_runCI`.  Any characters that are not letters, numbers, underscores, or dashes are removed when generating the name of the runCI job.  Is there anythere in particular that it wasn't working?

**Comment by a-murphy** [comment]
We've found that your runCI job had been soft-deleted, so the rSync job couldn't find it.  I've updated the runCI job so that it is no longer soft-deleted.  Would you mind triggering the rSync job again?

**Comment by glozhkovoy** [comment]
@a-murphy I triggered it but it came with 2 errors

https://app.shippable.com/github/data-skeptic/jobs/dataskeptic_dev_rSync/builds/5a74cd438abc8b06009aeee1/console

**Comment by a-murphy** [comment]
It was missing the connection between the runCI job and the ciRepo.  I've recreated the connection, so that particular error shouldn't appear again, and we're looking into what may have caused this.

**Comment by glozhkovoy** [comment]
@a-murphy I pushed into `dev` branch but nothing changed.
In my dashdoard I saw `master` triggered. I do not undrestand what happens

**Comment by glozhkovoy** [comment]
When I made a SPOG dry run for `dev `branch it returns me `project: dataskepticcom does not exists, please use valid runCI job`

**Comment by a-murphy** [comment]
It doesn't look like the dry run page is correctly handling the `.` in your project name, so that error is just on the dry run page and shouldn't affect how your job runs.  I'll open an internal issue for that.

I don't see any updates to the `dev` branch in your ciRepo's history for this afternoon.  It only shows the commit to `master` resulting from merging `dev` into `master`, which would explain why the `master` branch was triggered.  Did your commit message include `[skip ci]` or similar?

**Comment by glozhkovoy** [comment]
@a-murphy No, I didn't use `[skip_ci]` It seems like I've created the wrong rsync that triggers on `master` but I checked it twice right now .. I pushed 2 minutes ago and  rsync was created for dev branch but didn't update the jobs.

**Comment by glozhkovoy** [comment]
I'm not able to do it right now since I'm not an owner of repository. I will check this and write my reports down here. Thank you

**Comment by manishas** [comment]
@gleblozhkovoy let me know if this worked for you. I am closing this issue for now but happy to reopen if you need help.
