### ISSUE TITLE
missing action buttons (stop, cancel, rebuild, etc) when not logging in as Organization owner (Bitbucket)

### ISSUE THREAD

**Issue by emfanitek** [Shippable/support#4104]
When logging in as a Bitbucket organization member, I can see the builds, but I can't stop them, trigger them, etc. As if my user had degraded access rights. 

However when I use the Bitbucket organization owner as a login in shippable, then I see the action buttons.

Is there a setting I have to change?

**Comment by a-murphy** [comment]
If you have write access to the repository (can merge pull requests and push commits), you should be able to trigger or cancel builds from the UI.  If you only have read access to the repository, you won't have those options.  Could you check if you have write access on Bitbucket?

**Comment by emfanitek** [comment]
I have admin rights on the repositories

**Comment by emfanitek** [comment]
I'll add that this situation was not always the case with the same user. It started happening a couple of months ago. I could not say when exactly.

**Comment by a-murphy** [comment]
It's possible to have admin permission on a Bitbucket repository that belongs to a team without read or write.  If you navigate to the repository on Bitbucket as that user, do you only see the settings?  Or do you have an "overview" tab?  If you only have "settings," then you have admin permissions but not read or write.  If you have an "overview" tab, the access level should be displayed underneath "last updated" and "fork of."

If this doesn't explain it, would you mind letting us know either the name of the user or the "account ID" from the bottom right corner of the Shippable account profile page so we can check the permissions on Shippable?

**Comment by emfanitek** [comment]
I have full rights on every repo, everything is perfectly OK in bitbucket.
However, somehow, in the meantime, my actions have been enabled on shippable. SO whatever you did, it worked.

**Comment by a-murphy** [comment]
We didn't change anything related to this.  Your permissions were most likely corrected when your account was automatically synchronized, which occurs periodically.  If this happens again, you may want to try clicking the "sync" button on your account profile page to see if that helps.

Thank you for letting us know that you can see the action buttons again.
