### ISSUE TITLE
could not fetch run yml file path/sha: shippable.yml/master

### ISSUE THREAD

**Issue by gaberoffman** [Shippable/support#4108]
Shippable won't build for a new repo even though the shippable.yml is in the root of the directory.

reports:
common|github|normalizeRunYml|callerId:593aae9c51a378070095f65f|projectId:5a032e27e07b7707001f048e|__getYmlString could not fetch run yml file path/sha: shippable.yml/master

https://app.shippable.com/github/communityco/svc-sites/runs/6/1/console

**Comment by a-murphy** [comment]
It looks like that pull request contained the shippable.yml and we weren't able to get the new shippable.yml.  Webhook builds will use the builder account ("account used" in the first panel on the project settings page) to fetch the `shippable.yml` file and any updates to that file included in a pull request.  In this case, the account used doesn't have access to the repository with the updated shippable.yml and couldn't get the file.  Selecting an account with read access to both repositories on the project settings page will avoid this error.

**Comment by gaberoffman** [comment]
that doesn't seem to be the case.  The account used does have access to the repo. I even changed the account used to the owner of the repo making the PR and got the same response.  I've since tried removing the project, closing and reopening the PR, then submitting a different PR off of a different branch.  Still the same issue.  Latest failed build.  https://app.shippable.com/github/communityco/svc-sites/runs/2/1/console

**Comment by a-murphy** [comment]
Choosing an account with read permission on both repositories should have been enough.  In your pull request, are you adding or updating the `shippable.yml` file?  Was there already a `shippable.yml` in either of the branches?

**Comment by gaberoffman** [comment]
I'm adding a shippable.yml in my PR.  One was not in the initial repo.

**Comment by a-murphy** [comment]
Does your pull request add or update over 300 files?  GitHub will only return 300 of the files in a pull request, so it's possible that if you have more files we might not get the shippable.yml file.   We're able to determine that there is a `shippable.yml` somewhere, but if it didn't appear to be in the pull request would have then tried to get it from the base branch.

**Comment by gaberoffman** [comment]
Thanks.  The pull request only had 132 files but it was pretty large with 9,400 line changes.  So I broke the PR into a smaller PR and it worked.
