### ISSUE TITLE
How do I integrate with C# library

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4110]
I have a c# git repo. I want to run tests and build dll on shippable.

**Comment by ambarish2012** [comment]
@phagunbaya please take a look at this document to run tests and builds on a C# repo - http://docs.shippable.com/platform/tutorial/workflow/jobs-windows/.

Let me know if you need any additional help.

**Comment by ambarish2012** [comment]
@phagunbaya if your subscription uses custom nodes, we will need to upgrade your subscription to the latest release before you can purchase a Windows SKU and thereafter build your windows repository. 

Your other subscriptions that use our free tier have already been upgraded to the latest release, where you can immediately purchase a windows SKU.

**Comment by ambarish2012** [comment]
@phagunbaya we have also added support for on-demand Windows nodes now. 

To create the node, go to your billing page and create the Windows Server 2016 on-demand SKU as indicated in the screenshot below.

<img width="1166" alt="screen shot 2018-04-02 at 11 53 32 am" src="https://user-images.githubusercontent.com/26096758/38210596-b88ec94e-366c-11e8-837d-a7b1c1dd7cae.png">

**Comment by phagunbaya** [comment]
Yes. I'm aware this release announcement.
