### ISSUE TITLE
List of subscriptions is no longer displayed in the menu

### ISSUE THREAD

**Issue by slavafomin** [Shippable/support#4115]
Hello!

When I hover over GitHub icon in main menu (left sidebar) the drop-down menu is empty. The list of subscriptions is missing from it.

Why is that?

Thanks.

**Comment by a-murphy** [comment]
It shouldn't be empty.  Could you try refreshing the page and click "GitHub" again?  As far as I can tell, your account has access to GitHub subscriptions and projects.

**Comment by slavafomin** [comment]
Well, it appears now. Don't know what caused the issue. Thanks.
