### ISSUE TITLE
Windows on demand node

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4117]
> At this time, Shippable does not allow you to dynamically provision Windows node and we will be soon launching this functionality.

When is "soon"?

**Comment by ambarish2012** [comment]
@BryanCrotaz soon would be by end of February. If we are able to launch this feature earlier, I will let you know.

**Comment by BryanCrotaz** [comment]
We're in March - what's the new expected date?

**Comment by ambarish2012** [comment]
@BryanCrotaz I apologize for the delay. I will let you know the new date by EOD monday.

**Comment by ambarish2012** [comment]
@BryanCrotaz the expected release date is end of March.

**Comment by ambarish2012** [comment]
@BryanCrotaz we have added support for on-demand Windows nodes. 

To create the node, go to your billing page and create the Windows Server 2016 on-demand SKU as indicated in the screenshot below.

<img width="1166" alt="screen shot 2018-04-02 at 11 53 32 am" src="https://user-images.githubusercontent.com/26096758/38210596-b88ec94e-366c-11e8-837d-a7b1c1dd7cae.png">
