### ISSUE TITLE
Support AWS ECS health check grace period

### ISSUE THREAD

**Issue by Ronnie76er** [Shippable/support#4122]
AWS recently added a "grace period" to ECS. This would make the ALB/ELB not check the container's health for some amount of time on startup.

Shippable should support this feature.

Info: https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-ecs-adds-elb-health-check-grace-period/

Documentation: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html

**Comment by ambarish2012** [comment]
@Ronnie76er this feature will be generally available on 02/17. You can add this parameter to the `dockerOptions` resource in the `service` object.

**Comment by Ronnie76er** [comment]
Excellent news, thank you!

**Comment by ambarish2012** [comment]
@Ronnie76er this feature is available in production.

**Comment by Ronnie76er** [comment]
Just tried it out, and it is working! Thank you!
