### ISSUE TITLE
The script of auto-adding a new minion in Shippable is not working

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4123]
### Description of your issue:
The DevOps team has been using this script https://github.com/ambarish2012/create-custom-nodes to auto-create a new minion when an existing minion is terminated. 

However, they have noticed that the new minion is auto-created in AWS but it is not added in Shippable when they terminated one of the existing minion yesterday. The script used to work fine before.

![image](https://user-images.githubusercontent.com/14726381/36288066-0000602c-130d-11e8-889d-61c7e8f34354.png)

Could you please check if this is a side effect from any upgrade at your end during this week?

If you need any more information, please let me know.

**Comment by a-murphy** [comment]
Yes, the script will need to be updated to include `clusterId` in the `POST` to `/clusterNodes`.

To find the `clusterId`:

  * If you click "edit" on one of the node pools, the `clusterId` is the number after `nodePools` in the address bar.
  * Or you can also find the ID for the default cluster in the subscription by getting the subscription with the Shippable API (it's `defaultClusterId` in the object returned).

**Comment by ambarish2012** [comment]
@JoeRattanamaneesilp I am updating the script to add those comments.

**Comment by JoeRattanamaneesilp** [comment]
Thanks @a-murphy and @ambarish2012

**Comment by ambarish2012** [comment]
@JoeRattanamaneesilp I have updated the script. All you need to do is pass the clusterId as an additional argument to the script.

**Comment by ambarish2012** [comment]
@JoeRattanamaneesilp did the script work for you? I just pushed one important change to it, so you can try it now.

**Comment by ahaiong** [comment]
@a-murphy are you referring to this http://docs.shippable.com/platform/api/api-overview/#!/Subscriptions/get_subscriptions

**Comment by a-murphy** [comment]
Either [`/subscriptions`](http://docs.shippable.com/platform/api/api-overview/#!/Subscriptions/get_subscriptions) or [`/subscriptions/:subscriptionId`](http://docs.shippable.com/platform/api/api-overview/#!/Subscriptions/get_subscriptions_subscriptionId), called with an API token that has access to the subscription, will return `defaultClusterId` if there is a default cluster for the subscription.

**Comment by ahaiong** [comment]
@a-murphy I am running
```root@ip-10-202-2-199:/tmp# ./register-custom-node.sh c99034ff-XXXX-XXXX-b431-af927dfed4ca 583638aafd9c101000d73b34 "$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4/) $(curl -s http://169.254.169.254/latest/meta-data/instance-id/)" 74258

and I get 

./shipInitNode.sh: 1: ./shipInitNode.sh: {logType:warn,methodName:/clusterNodes/:clusterNodeId/initScript|GET|validateAccount|_getAccountTokenByApiToken,id:2000,message:invalid apiToken}: not found```

would you know where I can regenerate/find this api token c99034ff-XXXX-XXXX-b431-af927dfed4ca ?

**Comment by ahaiong** [comment]
@a-murphy disregard my last message, found it, my bad

**Comment by ahaiong** [comment]
@ambarish2012 when running your wrapper script, I get the following
```> GET /clusterNodes/74258/initScript HTTP/1.1
> User-Agent: curl/7.35.0
> Host: api.shippable.com
> Authorization: apiToken e9149d1e-8af0-4f05-b483-131d9b4494de
> Accept: application/json
> cache-control: no-cache
>
< HTTP/1.1 404 Not Found
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Accept,Content-Type,Authorization,Cookie
< Access-Control-Allow-Methods: GET,PUT,POST,DELETE
< Access-Control-Allow-Origin: *
< Access-Control-Max-Age: 600000
< Content-Type: application/json; charset=utf-8
< Date: Fri, 16 Feb 2018 04:54:26 GMT
< ETag: W/"bd-GUm42i1lqY74ktfG5rRT4w"
< Vary: Accept-Encoding
< X-Powered-By: Express
< Content-Length: 189
< Connection: keep-alive
<
* Connection #0 to host api.shippable.com left intact
{"logType":"verbose","methodName":"clusterNodes|getInitScriptById|callerId:58aa22eb5c87e70f0089bac3|id:74258|_getInitScriptById","id":4004,"message":"clusterNodes GET failed for :id 74258"}
```

**Comment by ambarish2012** [comment]
@ahaiong are you able to jump into a quick call so that I can examine how you are running the script and the values you are passing?

**Comment by ambarish2012** [comment]
@ahaiong the clusterId should be `110490`. I think you are passing 74258 which is inaccurate.

**Comment by ahaiong** [comment]
@ambarish2012 sure, I get the cluster id from the defaultclusterid as suggested by @a-murphy.
What's the best way to do this?

**Comment by ambarish2012** [comment]
@ahaiong can you get into a quick call?

**Comment by ahaiong** [comment]
Yes, what's the number?

**Comment by ambarish2012** [comment]
https://zoom.us/j/673247273

**Comment by ambarish2012** [comment]
Script is working.

**Comment by JoeRattanamaneesilp** [comment]
Thanks @ambarish2012 and @ahaiong for solving this issue.
I'll close this report.
