### ISSUE TITLE
The build agent version is auto-downgraded to the previous version

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4124]
### Description of your issue:

I have re-initialized the minions to get the latest build agent version. However, there is a strange situation happening. The one that I have already re-initialized is auto-downgraded to be the previous build agent version.

![image](https://user-images.githubusercontent.com/14726381/36289712-9b4ce6d8-1315-11e8-8363-9a0fa4cf0e30.png)

Could you please check if this is a bug?

**Comment by JoeRattanamaneesilp** [comment]
I think I have found the way to replicate this problem.

If a job is built, the build agent version of the minion which is used will be downgraded to the previous version.

![image](https://user-images.githubusercontent.com/14726381/36290505-af1d3ad8-1319-11e8-87fd-e2484f0f4e5b.png)

The **A** point in the screenshot  : `ip-x.x.x.199`
https://app.shippable.com/github/bauerxcelmedia/jobs/spike-export-only/builds/5a8637598dfc650600c524f4/console

The **B** point in the screenshot  : `ip-x.x.x.193 `
https://app.shippable.com/github/bauerxcelmedia/jobs/spike-export-only/builds/5a86393364672f0700c29de4/console

**Comment by a-murphy** [comment]
Since you're initializing these manually, could you check which container is running after you run the initialize script (`sudo docker ps`)?  From the logs that you linked, it looks like it is the `v5.11.1` image is being used, and the UI is likely incorrect in reporting the newer version.

And, could you confirm that you are running the new script, not a previously downloaded script, when you are reinitializing?

**Comment by JoeRattanamaneesilp** [comment]
@a-murphy I can see from the logs that it is v.5.11.1. 
Yes. I have run the new script when I did reinitializing.

I have discussed with DevOps and he thinks it may be a cache. 

Now we will fix the script to create a minion first in this report https://github.com/Shippable/support/issues/4123 Then, I will check again with an auto-created minion one.

**Comment by JoeRattanamaneesilp** [comment]
After https://github.com/Shippable/support/issues/4123 has been fixed, the build agent version of the auto-created minion is correct and working well.

I'll close this report.
