### ISSUE TITLE
Can not remove node from pool due to processing state

### ISSUE THREAD

**Issue by ahaiong** [Shippable/support#4132]
Node in question
https://app.shippable.com/subs/github/bauerxcelmedia/nodes/5a08e44fb4a148070053a190

### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
I've updated the status of that node so that it's no longer "processing."  This can occur of the node is terminated before it has reported that it is no longer processing after running a build or starting to initialize it.  Let us know if there are still any problems.
