### ISSUE TITLE
"verifying job dependencies" stopped the builds

### ISSUE THREAD

**Issue by kuboosoft** [Shippable/support#4133]
### Description of your issue:
Shippable was working perfectly 01/31/2018, today I discover some dependencies isn't installed in Shippable, also "sudo", and stopped the builds. I modified my yml, but is imposible to solve the issue with my hand.

- Link to the build failure

[here](https://app.shippable.com/github/UnitedRPMs/unibuild/runs/570/1/console
)

- Scripts called from the yml (optional)

`docker run --privileged=true --cap-add=SYS_ADMIN -v $(pwd):/root/enjoy/ davidva/unibuild /bin/sh -c "rm -f /urpms && wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/urpms && chmod a+x urpms && /urpms -g UnitedRPMs/tribler -s tribler.spec -r true -d 'dist .fc25' -c true"`

- Results
```
verifying job dependencies
 echo 'jq not installed, installing jq ...' 0s  
jq not installed, installing jq ...

/root/928c83e6-f68b-47d3-96f5-380eea743c46.sh: line 292: sudo: command not found

```

**Comment by ric03uec** [comment]
@kuboosoft this has been already fixed, can you please run your builds again to verify

**Comment by kuboosoft** [comment]
@ric03uec Thanks, now is working fine!
