### ISSUE TITLE
Use '- script: ll <directory name>' in runSh

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4139]
I'm trying to use `ll` command to see files/folders in a directory. However this command is not found.
Could you please advise if there is another command that I can see a list of files in a directory?

This is my runSh job that I have added `ll` with various directories.
``` - name: spike-export-only
    type: runSh
    always:
      - NOTIFY: migrate-slack-notifications
    steps:
      - IN: migrate-service-cli-config
      - IN: migrate-service-s3-param
      - IN: migrate-service-repo-branch
        switch: off
      - TASK:
          <.... other commands>
        - script: cat ../data/ids.txt
        - script: ll $JOB_STATE
        - script: ll $JOB_PREVIOUS_STATE
        - script: ll $MIGRATESERVICEREPOBRANCH_STATE
        - script: ll $SHIPPABLE_BUILD_DIR
```

This is the result in the build log
```
  ll $JOB_STATE 0s  
/var/lib/shippable/882f70f5-ca64-496c-a6d9-aa6760bc43dc/build/scripts/yml_task_0.sh: line 96: ll: command not found
```
Full log, please click [here](https://app.shippable.com/github/bauerxcelmedia/jobs/spike-export-only/builds/5a8ca18b76382b0800e438fe/console)

**Comment by a-murphy** [comment]
The [`ls`](https://en.wikipedia.org/wiki/Ls) command will be available in the default images.  For example, `ls $JOB_STATE` will list the files and directories in `$JOB_STATE`.  You can also install programs that you wish to use in your scripts, although that will take longer than using one that is already available.

**Comment by JoeRattanamaneesilp** [comment]
Thanks @a-murphy 

I have used `ls -l` which is the same as `ll'. The command works well.
I've got more understanding about those variables.
![image](https://user-images.githubusercontent.com/14726381/36455221-4c170ff8-16f3-11e8-9815-dc1c1401e2e7.png)
