### ISSUE TITLE
Upgrade Maven version to 3.5.2

### ISSUE THREAD

**Issue by jodastephen** [Shippable/support#4141]
Issue #3925 was closed without actually updating the Maven version. [Maven v3.5.0](https://maven.apache.org/download.cgi) or later is needed to process Java 9 code, and java 10 is almost out.

Please update the Maven version 😃

**Comment by ambarish2012** [comment]
@jodastephen we have upgraded the Maven version to 3.5.2 in . You will need to set the `runtime version` in your Node pool to v6.2.4. 

Here are the instructions:

1. Navigate to your subscription dashboard and click on Settings (gear icon) -> Node Pools.
2. Click `edit` on your Node pool.
3. Select `v6.2.4` in the `Runtime Version` dropdown.
