### ISSUE TITLE
Maven builds stuck

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4143]
My maven builds are stuck

```
[INFO] --- maven-javadoc-plugin:2.9.1:javadoc (default-cli) @ client ---
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.pom
Feb 22, 2018 1:51:09 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection timed out (Read failed)
Feb 22, 2018 1:51:09 AM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request to {s}->https://repo.maven.apache.org:443
```

https://app.shippable.com/github/Falkonry/falkonry-java-client/runs/27/1/console

**Comment by a-murphy** [comment]
It looks like this may be a network problem.  Since you're running builds on your own nodes, could you check that they are able to connect to repo.maven.apache.org?

**Comment by phagunbaya** [comment]
Yes they can connect

**Comment by phagunbaya** [comment]
Still hanging https://app.shippable.com/github/Falkonry/falkonry-java-client/runs/28/1/console

**Comment by a-murphy** [comment]
We're still investigating this.  So far we haven't found any changes to how Shippable runs your build or the image used between the last successful build and your current builds.

**Comment by a-murphy** [comment]
Do you have any kind of caching set up on your nodes?  Do you see the same error if you clone your repository locally and run the same test commands?

It looks like it's consistently having trouble with `maven-core-2.2.1.pom`, but I was unable to find any different dependency versions when comparing to the previous successful run.  It also occurred on more than one of your nodes, so it's not specific to a particular node.

**Comment by phagunbaya** [comment]
I have not set any caching behavior. Is there any way to verify? And I dont see this error while running locally.

**Comment by a-murphy** [comment]
You don't have Shippable caching enabled,  I was wondering if you had set up anything else that would cause it to look for `maven-core-2.2.1.pom` in the wrong place.

When you run it locally, have to tried cloning your project into a new directory so that there won't be anything already downloaded or installed?  If `maven-core-2.2.1` is already there, then it won't need to download it and is unlikely to get an error.  You could also try the same thing on one of your nodes to narrow down where this occurs.

**Comment by phagunbaya** [comment]
Yes works with a fresh clone.

**Comment by phagunbaya** [comment]
Haven't tried on the node yet.

**Comment by phagunbaya** [comment]
Works on node too. Even tried in a docker container on same node.

**Comment by phagunbaya** [comment]
Any resolution ?

**Comment by trriplejay** [comment]
you mentioned that you tried in docker container, which container? can you try in the same container that your build typically runs in? (`drydock/u17javall:v6.1.4`)

The best lead we have so far is this bug report:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=495089#c4

which suggests disabling IPv6 on the host, as it can conflict with docker in some way, though Shippable has not made any changes that we know of that would impact this.

while your build agent has been upgraded since your last successful build of this project (v6.1.4 -> v6.2.2) the build itself is running in a different container.

When did you last reset your build nodes? did you reset them or provision new ones? if provisioned, were the provisioned in a different way with different settings?

**Comment by phagunbaya** [comment]
I tried with ubuntu:16.04 container.

Build nodes were reset around last week and I did it from shippable UI.

**Comment by ambarish2012** [comment]
@phagunbaya can you try two things:

1)  `curl https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.pom` from the node?

2) docker run -it drydock/u16javall:v6.1.4 bash
curl https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/2.2.1/maven-core-2.2.1.pom

There appears to be some networking issue on your custom node.

**Comment by phagunbaya** [comment]
@ambarish2012  Curl works from node as well as from inside the the container.

**Comment by ambarish2012** [comment]
ok  thanks. 

Please can you also run this command in the `drydock/u16javall:v6.1.4 `container on the node:
`sysctl -a|grep disable_ipv6`

**Comment by phagunbaya** [comment]
```sysctl: reading key "kernel.unprivileged_userns_apparmor_policy"
net.ipv6.conf.all.disable_ipv6 = 0
sysctl: reading key "net.ipv6.conf.all.stable_secret"
net.ipv6.conf.default.disable_ipv6 = 0
sysctl: reading key "net.ipv6.conf.default.stable_secret"
net.ipv6.conf.eth0.disable_ipv6 = 0
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
net.ipv6.conf.lo.disable_ipv6 = 0
sysctl: reading key "net.ipv6.conf.lo.stable_secret"```

**Comment by ambarish2012** [comment]
ok - that indicates ipv6 is enabled on your host. We need to disable it.

**Comment by ambarish2012** [comment]
Lets try the instructions here - https://support.purevpn.com/how-to-disable-ipv6-linuxubuntu.

Please run them on the host machine.

**Comment by phagunbaya** [comment]
And restart docker service ?

**Comment by ambarish2012** [comment]
yes - after you disable ipv6, you can restart docker. Thereafter running the `sysctl -a|grep disable_ipv6` command in the container should show something like:

```
root@3f9e0894fc2e:/# sysctl -a|grep disable_ipv6
sysctl: reading key "net.ipv6.conf.all.stable_secret"
net.ipv6.conf.all.disable_ipv6 = 1
sysctl: reading key "net.ipv6.conf.default.stable_secret"
net.ipv6.conf.default.disable_ipv6 = 1
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
net.ipv6.conf.eth0.disable_ipv6 = 1
sysctl: reading key "net.ipv6.conf.ip6tnl0.stable_secret"
net.ipv6.conf.ip6tnl0.disable_ipv6 = 1
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
net.ipv6.conf.lo.disable_ipv6 = 1
root@3f9e0894fc2e:/# sysctl -a|grep disable_ipv6
sysctl: reading key "net.ipv6.conf.all.stable_secret"
net.ipv6.conf.all.disable_ipv6 = 1
sysctl: reading key "net.ipv6.conf.default.stable_secret"
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
sysctl: net.ipv6.conf.ip6tnl0.disable_ipv6 = 1
reading key "net.ipv6.conf.ip6tnl0.stable_secret"
sysctl: net.ipv6.conf.lo.disable_ipv6 = 1
reading key "net.ipv6.conf.lo.stable_secret"
```

**Comment by ambarish2012** [comment]
Also, just an FYI,  since you have 3 nodes, you will need to do this on all nodes.

**Comment by phagunbaya** [comment]
It's not picking up

```
root@b1e44034e519:/# sysctl -a|grep disable_ipv6
sysctl: reading key "kernel.unprivileged_userns_apparmor_policy"
sysctl: reading key "net.ipv6.conf.all.stable_secret"
net.ipv6.conf.all.disable_ipv6 = 0
sysctl: reading key "net.ipv6.conf.default.stable_secret"
net.ipv6.conf.default.disable_ipv6 = 0
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
net.ipv6.conf.eth0.disable_ipv6 = 0
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
net.ipv6.conf.lo.disable_ipv6 = 0
```

**Comment by ambarish2012** [comment]
@phagunbaya can we get into a quick call?

**Comment by phagunbaya** [comment]
Sure.

**Comment by ambarish2012** [comment]
https://zoom.us/j/685970892

**Comment by phagunbaya** [comment]
Rejoin ?

**Comment by ambarish2012** [comment]
yes - emailing you at phagun.baya@gmail.com

**Comment by phagunbaya** [comment]
OK. And please remove the email from above comment.

**Comment by phagunbaya** [comment]
Looks like there is conflict between test dependencies and java doc dependencies. Resolved by separately executing both command along with a maven clean.
