### ISSUE TITLE
TypeError: cmd.replace is not a function

### ISSUE THREAD

**Issue by jplimpens** [Shippable/support#4144]
I'm lost on the error this runSh job below is giving: 
_reqProc|job|generateSteps|_generateScript, Failed to generate script for task : 0 with err: TypeError: cmd.replace is not a function_

What am I missing??

Job:
_- name: genericSetupStagingEnvironment
      type: runSh
      triggerMode: serial
      dependencyMode: immediate   # optional
      on_start:
        - NOTIFY: Slack
      steps:
        - IN: jdemo_runCI
        - TASK:
            name: setupStagingEnvironment
            script: 
              - echo "==== do something ===="
              - echo $PATH
              - echo "==== finished something ===="
      on_failure:
        - NOTIFY: Slack_

**Comment by trriplejay** [comment]
@jplimpens Hello, our script parser is just having trouble with one of the lines in your script.  It looks like maybe an echo statement that contains a colon? 

if you have a statement like this:
`- echo "try a colon: did it work?"`

i recommend updating to something like this:
`- 'echo "try a colon: did it work?"'`

The extra quotes that surround the entire line should allow the job to proceed.

let me know if that helps!

**Comment by jplimpens** [comment]
Hi, the colon was my first idea. But all echo's have no colon (I'm really trying the job as posted above; once it works I'' extend it to something usefull). So I validated the yml on yamllint and even counted all colons. Just to see whether I had a type somewhere. But can't find it.

The extra quotes don't work unfortunately. Still the same error.
Any ideas?

**Comment by trriplejay** [comment]
hmm.. .taking a closer look at your pipeline, it looks like the syncRepo hasn't been updated via webhook since almost 11 hours ago.  We need to receive the webhook in order to pick up on changes made to the yml.  

Since you've been updating the job, are you sure you've been changing the correct branch? it looks like the sync is set up for the "releases" branch.

**Comment by jplimpens** [comment]
Yes, THANK YOU!

The one thing this noob didn't think to check. I was pushing my updates to the wrong branch.
So, just for completeness.... The first version did have a colon in a echo statement. But once I hit that error I removed that colon. Unfortunately, I pushed the changes to the wrong branch. Again, Thanks!
