### ISSUE TITLE
Help with registering credit card for account

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4145]
A colleague of mine responsible for account payments tried to register to record the payment details and he can't see our organisation on which to record the details. We email Manisha yesterday but have heard nothing back, I'm assuming she's not in a position to respond.

Can someone please assist before we run out of free builds? At the time of raising this issue we have 12 free builds left.

Thanks!

**Comment by manishas** [comment]
@andye2004 sorry for the late follow up on this. I’ll escalate this right away. 

One thing to note is that anyone who upgrades an organization needs admin rights on the org in GitHub/bitbucket. Can you confirm that the person responsible for account payments is an admin of the org?

**Comment by andye2004** [comment]
HI Manisha, thanks for the speedy follow up. I’m not sure if Scott (cc'd) has admin rights in GitHub. I’ll need to check but the problem I have is that it’s late in the day here in Australia and it might be Monday morning before I can check this out.

Is there any way you might be able to increase the number of free builds we have (even slightly) until I can look into this?

Many thanks, Andy.

On 23 Feb 2018, at 4:24 pm, Manisha <notifications@github.com<mailto:notifications@github.com>> wrote:


@andye2004<https://github.com/andye2004> sorry for the late follow up on this. I’ll escalate this right away.

One thing to note is that anyone who upgrades an organization needs admin rights on the org in GitHub/bitbucket. Can you confirm that the person responsible for account payments is an admin of the org?

**Comment by manishas** [comment]
Yes, we can definitely remove the build restriction until Monday.

cc @rageshkrishna

**Comment by andye2004** [comment]
Fabulous! Thank you Manisha. I’ll let the other devs working this weekend know.

On 23 Feb 2018, at 4:30 pm, Manisha <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, we can definitely remove the build restriction until Monday.

cc @rageshkrishna<https://github.com/rageshkrishna>

**Comment by rageshkrishna** [comment]
@andye2004 Since we're already communicating about this over email, would it make sense to close this issue?

**Comment by andye2004** [comment]
@rageshkrishna Happy for you to close this Ragesh.

**Comment by rageshkrishna** [comment]
Great, thanks!
