### ISSUE TITLE
Add/sync new organization

### ISSUE THREAD

**Issue by wltjr** [Shippable/support#4147]
### Description of your issue:
I created a new organization and transferred a project I had Shippable setup for to that organization. That project no loner shows under my organization, but still has its logs. I cannot find out how to sync the organizations or add the new one. I did not find any documents on such, but I may have missed something.

I still see it showing under WebHooks under Github. But it is not notifying shippable, or the repository needs to be activated under its new organization. Not sure if I missed something else on the Github side of things.

Please advise thanks!

Project
https://app.shippable.com/github/Obsidian-StudiosInc/jtidy/dashboard

I moved it to
https://github.com/jtidy/jtidy

**Comment by a-murphy** [comment]
If you've already tried clicking the sync button on you account profile page and the organization still hasn't appeared, the organization most likely has [OAuth App access restrictions](https://help.github.com/articles/about-oauth-app-access-restrictions/) set up.  You can follow [these directions](https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/) to request that Shippable be allowed to see the repositories in that organization.  Then an organization owner can [grant access](https://help.github.com/articles/approving-oauth-apps-for-your-organization/).  Once Shippable has access to the organization, you should just need to click the "sync" button on the account profile page and your organization and project will appear.

**Comment by wltjr** [comment]
The 2nd link provided was the ticket! It had been some time since I had done this so missed that step. Thanks much!
