### ISSUE TITLE
How to configure a job with a large multiline *secret* value?

### ISSUE THREAD

**Issue by jinal--shah** [Shippable/support#4152]
Hi! Thanks for all the great work so far.

I have a long secret multiline value that I would like either written to a file or available in an environment variable during the build->ci phase of a job.

I have concatenated the multiple lines in to one and have used the **key-value integration** to make this variable available to my jobs. That works fine, and I can split the value back in to multiple lines during the ci phase.

But is there a way to avoid doing this concatenation/splitting work? i.e. just configure a shippable job with the original multiline string?

If not, is there a way to use key-value with the concatenated single line value that prevents the value from being displayed in console output? (See #4153 for issue with this)

**Comment by ambarish2012** [comment]
@jinal--shah we will deploy the fix that prevents the integration value from displayed next week.

**Comment by ambarish2012** [comment]
@jinal--shah also the recommended approach for multi-line secrets is to base64 encode the secret and specify it in the integration. You will then need to base64 decode it in your job. Your current approach also is fine.

**Comment by jinal--shah** [comment]
Amazing! Much appreciated. Yeah, actually base64 will do fine and is less fiddling around. Good idea, thanks! Closing this ticket ⚡️
