### ISSUE TITLE
Parsing test results fails on AArch64

### ISSUE THREAD

**Issue by lumag** [Shippable/support#4157]
Parsing of test results fails on AArch64 host with the following message:

```
echo 'Parsing test reports' 0s  
  reports --destination /shippableci/testresults tests --source /root/src/github.com/Linaro/odp/shippable/testresults 0s  
/root/7c63178f-0e13-4935-8926-199e13c05415.sh: line 73: /usr/local/bin/reports: cannot execute binary file: Exec format error
```

- [Build log](https://app.shippable.com/github/Linaro/odp/runs/1001/1/console)

**Comment by ambarish2012** [comment]
@lumag we are deploying the fix for this issue in production next week. I will update this issue when the fix goes live.

**Comment by ambarish2012** [comment]
@lumag the fix has been deployed. Please let me know if your issue has been resolved.
