### ISSUE TITLE
Your account has been blocked when creating new account

### ISSUE THREAD

**Issue by myvizoapp** [Shippable/support#4159]
### Your account has been blocked

Getting following error on creating new account.

> An error occured, please choose an action.
> Your account has been blocked as it was identified to be violating our **security policy**.

Login using GitHub -  **myvizoapp** as username

**Comment by rageshkrishna** [comment]
Hi @myvizoapp. I've unblocked your account. Please try logging in again. Thanks!

**Comment by myvizoapp** [comment]
Thanks @rageshkrishna It works
