### ISSUE TITLE
Error 404 under bitbucket subscriptions

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4160]
I just find out about Shippable and I would like to test it. 

For that, I signed up using my bitbucket credential. Once in the Shippable app, I have the Bitbucket logo under the Subscriptions item from the left panel.

I have two questions:

- Why under the Bitbucket item, I have a lot of bitbucket logins and not only my login (and maybe my team)?
- If a click on any login, I got the error 404 page.

![screenshot](https://user-images.githubusercontent.com/3213882/36845581-9e16da3a-1d57-11e8-9d03-49fa8d7acfa4.png)

Thanks for your help.

**Comment by a-murphy** [comment]
Each Bitbucket account or team with a repository on which you have permissions should appear under "Bitbucket" on the left.  Clicking on any of those will only show projects that you can access in that account or team.

The 404 certainly isn't expected.  It looks like we haven't identified that your account has access to any projects.  Could you click on "profile" under "account" on the left and then the green "sync" button?  That will re-synchronize your account and hopefully correct the list of projects for your account.  If this continues, could you check for any errors in the browser console?

**Comment by BotellaA** [comment]
I got this message in the console whiling syncing.

```
Possibly unhandled rejection: {"logType":"verbose","methodName":"/subscriptionIntegrationPermissions|GET|callerId:5a97e0bc7f06db0700e61625|validateProjects|_computeShim","id":4004,"message":"No projects found for projectId(s): "} lib.min.js:17:8677
	f/< https://app.shippable.com/app/lib.min.js:17:8677
	gb/this.$get</< https://app.shippable.com/app/lib.min.js:16:26517
	j https://app.shippable.com/app/lib.min.js:17:14403
	$eval https://app.shippable.com/app/lib.min.js:17:21703
	$digest https://app.shippable.com/app/lib.min.js:17:20236
	$apply https://app.shippable.com/app/lib.min.js:17:21999
	i https://app.shippable.com/app/lib.min.js:16:30083
	rb/</v.onload https://app.shippable.com/app/lib.min.js:17:1031
```

**Comment by a-murphy** [comment]
That error is a result of the missing project permissions.  Do you have [access control](https://confluence.atlassian.com/bitbucket/control-access-to-your-private-content-862621261.html) set up on Bitbucket that could be preventing access?  Or is the repositories list on https://bitbucket.org/dashboard/overview empty?

**Comment by BotellaA** [comment]
Thank you for your quick answers!

I do not have access control. I have a classic bitbucket account.
The repository list is not empty...
![screen](https://user-images.githubusercontent.com/3213882/36866716-5ec1ab8a-1d93-11e8-9b4a-71f6d043889e.png)

**Comment by ambarish2012** [comment]
@BotellaA can we get into a quick call to go over this issue?

**Comment by BotellaA** [comment]
I am away and busy for few days. If you have some questions or testing to do, you could send me what to do. I might find some time for quick tests if needed.

**Comment by BotellaA** [comment]
I tried one more time and it works... I did not change anything..
I do not understand but now it seems to work.
