### ISSUE TITLE
Auto-rerun a job if it fails

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4161]
We have a scheduling job to run our automation test every morning. However, the job sometimes fails because of an uncontrollable issue (e.g. timeout). It often passes after rerunning.

Do we have a configuration in Shippable to allow the job to be auto-rerun if it fails?

**Comment by ambarish2012** [comment]
@JoeRattanamaneesilp this is possible using Shippable API.

Here is a [sample](https://github.com/ambarish2012/retry_on_failure_runSh/blob/master/shippable.yml) you can look at. The sample allows you to configure the #re-runs as well.

**Comment by JoeRattanamaneesilp** [comment]
Thanks @ambarish2012 for the information. 

I will have a look and apply it in my project.
