### ISSUE TITLE
On SPOG manual jobs show when they're out of date

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4162]
In SPOG it's impossible to see which manual jobs need to be run.

Suggestion - a coloured border (e.g. charcoal to be same as a pending job) that appears when an IN dependency would have triggered the job if it wasn't set to run manually on that IN. It resets when the job is triggered manually or by a different IN.

**Comment by ambarish2012** [comment]
@BryanCrotaz this is a great idea, I am adding it to our backlog.

**Comment by manishas** [comment]
This is complete. We now show a border around a job if it is stale, i.e. there are newer versions of IN resources/jobs.

![image](https://user-images.githubusercontent.com/2983749/39202545-11a80e50-47a7-11e8-8d3b-c9414b5c12b9.png)
