### ISSUE TITLE
Another notifications question

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4165]
I know there is integration with Slack, HipChat, email and IRC but I was wondering if it would be possible to have notifications sent to a configured web hook?

We need to be able to send notifications to people who are not on the dev team and who only use Microsoft Teams and would like to be able to send notifications as for the specific integrations that Shippable provides.

Thanks, Andy.

**Comment by andye2004** [comment]
P.S. Codeship, Circle, Travis and Jenkins all provide integration to Teams. Be really good if shippable can as well.

**Comment by manishas** [comment]
We do offer a webhook integration. It is documented here http://docs.shippable.com/ci/webhook/

I’ll add a request to integrate with Microsoft teams in our feefature request backlog.

**Comment by andye2004** [comment]
Thanks @manishas , I know the web-hook is there I'm asking if it can used as a notification tool in the same way as the built in notifications. E.g. replacing slack in the below config with the web-hook.

integrations:                              
 notifications:
   - integrationName: slack-integration     #replace with your integration name  
     type: slack  
     recipients:
       - “#channelOne”  
       - “#channelTwo”
     on_success: always | change | never
     on_failure: always | change | never
     on_cancel: always | change | never
     on_start: always | never
     on_pull_request: always | never

**Comment by manishas** [comment]
Usage is documented in the docs page for webhook notifications. http://docs.shippable.com/ci/webhook/

You can set up a webhook and specify payload,as well as on_success, on_failure etc. However, you cannot choose channels or rooms in the yml.  If Teams allows you to configure a webhook for a room or set of rooms, you can set up a webhook integration and use it in the yaml to send custom payloads. Let me know if that makes sense.

**Comment by manishas** [comment]
We’ll have to take a deeper look at how Teams works to give you a more specific solution but I just wanted to point you to the webhook docs to get you started.

**Comment by andye2004** [comment]
Ah, thanks @manishas, never thought to look into the web-hook docs that deeply just thought it would have been mentioned in the notifications section. Looks like we should be able to workaround things until there is an official integration.

Thanks again, Andy.

**Comment by andye2004** [comment]
Sorry guys, just re-opening this issue. It's probably very simple to do but I need to pass json to the Teams web hook, something like the json text below, how can I do this from the yaml file? Tried about a dozen different ways and it fails the yaml parser every time.

{
	"title": "BUILD FAILED - $REPO_FULL_NAME - $BUILD_NUMBER",
	"text": "Big boy ( bradleys@yambay.com ) did it and ran away"
}

**Comment by andye2004** [comment]
I'm not even sure the integration block is being triggered, I am deliberately failing the build by issuing an 'exit 1' command but I can't see anything in the logs to say the failure notification is even being triggered.

here is is snippet from the yaml file

`yaml
integrations:
  generic:
    - integrationName: global_env

  hub:
    - integrationName: artifactory
      type: artifactory

  notifications:
    - integrationName: teams-ci-status
      type: webhook
      payload:
        - title=BUILD FAILED - $REPO_FULL_NAME - $BUILD_NUMBER
        - text=Big boy ( bradleys@yambay.com ) did and ran away
      on_cancel: never
`
Microsoft teams expects title and text as minimum attributes in the json payload.

**Comment by andye2004** [comment]
Apologies guys, this is actually working. Due to the standard configuration for on_failure / on_success it wasn't sending anything because the status had not changed. Once I stopped forcing the build error the status changed and I go the notifications.
