### ISSUE TITLE
Account has been blocked

### ISSUE THREAD

**Issue by Evanaellio** [Shippable/support#4166]
I tried to create a new account and got the following error:

> Your account has been blocked as it was identified to be violating our security policy.
> Please contact support if you feel this is a mistake.

It could have happened because I created my GitHub account a few minutes before.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by zakatlyubvi** [comment]
I have the same problem, but I went through bitbucket. https://bitbucket.org/spbdioteam/

**Comment by manishas** [comment]
@zakatlyubvi what username did you sign into Shippable with?

**Comment by zakatlyubvi** [comment]
I do not know, I'm just writing an error. In bitbucket I am under the name "spbdio"

**Comment by zakatlyubvi** [comment]
http://prntscr.com/imqzb3

**Comment by manishas** [comment]
@zakatlyubvi I have unblocked your account. Please log out and log in again into Shippable and let me know if it doesn’t work.

**Comment by zakatlyubvi** [comment]
thx )
