### ISSUE TITLE
Looking for easiest way to....

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4167]
Hey Guys, I'm looking for the easiest way to get the CI completion status of a previous CI run. E.g. FAILED, SUCCEEDED. Any info you could provide would be appreciated.

**Comment by a-murphy** [comment]
Is there a particular location where you are trying to get the status?

In general, you can use the [`GET /runs` API route](http://docs.shippable.com/platform/api/api-overview/#!/Runs/get_runs) including `status=complete` in the querystring to get complete runs.  Using the API requires a paid account for most routes.  However, you can get runs for public projects without a token if you include `projectIds=projectId` (with the ID from the bottom right on the project page) in the querystring.   If it's a private project, you'll need an [`apiToken`](http://docs.shippable.com/platform/api/api-tokens/) in the request headers.

**Comment by andye2004** [comment]
@a-murphy Thanks for the response. I'm trying to get the previous state from a script running as part of a CI build and I was hoping there would be a simple way to do it. I've looked at using the API but it returns numerical states and I need to be able to translate the state. #4169 Is another ticket I have opened as the docs for state are not accessible so I don't what the values mean. If you could maybe supply a state mapping that would help.

Thanks, Andy.

**Comment by a-murphy** [comment]
In CI, 0 is waiting, 20 is processing, 30 is success, 40 is skipped, 50 is unstable (successful run with failing tests), 60 is timeout, 70 is canceled, and 80 is failed.  You can get the mapping from the API as well by calling `https://api.shippable.com/systemCodes?group=statusCodes`.

There is a [branchRunStatus](http://docs.shippable.com/platform/api/api-overview/#!/Runs/get_projects_projectId_branchRunStatus) route that may be a little easier to use if you know the project and branch, but it will also return the same numerical values.  It would move the projectId from a query parameter to a route parameter and only return one without adding a `limit` parameter.  The `GET /runs` route will also work.

**Comment by andye2004** [comment]
@a-murphy Thanks again for the response. It was the branchRunStatus I was looking at using.

What I am effectively trying to do is programmatically send notifications when the build is broken / fixed. I'm trying to do this for Microsoft Teams and have tried using the web-hook integration but it is too cumbersome a method to use from the shippable.yml and I need to come up with a much easier method. The only missing piece is to get the last completed build status.

So my requirement would be to get the last completed build status only for active projects and not for PRs. Given this, I have set IsPullRequest = false and ActiveBranches = true, can you tell me what values I should assign to the Status query parameter? I'm a bit confused between success, successful, complete etc.

Also, do you know if the JQ query language is installed as per my previous question?

**Comment by a-murphy** [comment]
If you're trying to compare to the last complete build for the same branch, I would consider `https://api.shippable.com/runs?projectIds=$PROJECT_ID&branch=$BRANCH&isPullRequest=false&status=complete&sortBy=runNumber&limit=1`.  It would avoid finding the right branch when you parse the response.  Both `PROJECT_ID` and `BRANCH` are [default environment variables in CI](http://docs.shippable.com/ci/env-vars/#standard-variables).

Here are the options for `status` queries that have more than one status code that you asked about:

|name | codes|
|--------|----------|
| complete| success (30), skipped (40), unstable (50), timeout (60), canceled (70), and failed (80) |
| incomplete | waiting (0) and processing (20)
| successful | success (30) and skipped (40)
| unsuccessful | unstable (50), timeout (60), canceled (70) and failed (80)

You can also use `waiting`, `processing`, `success`, `skipped`, `unstable`, `timeout`, `canceled`, or `failed`, which each map to only one status code number, or the numbers in your queries.  Multiple status codes can be separated with commas.

We have `jq` installed in most of the default build images.  If you've specified your own image, you'll have to install it yourself to use `jq` in the `ci`, `on_success`, or `on_failure` sections.  Some older default images don't have `jq` installed, but it's very unlikely that your subscription is configured to use those if you started using Shippable recently.

**Comment by andye2004** [comment]
@a-murphy fantastic! Exactly what I was looking for and fact jq is there by default is even better!

**Comment by andye2004** [comment]
I've got this working now guys so will close off the call. Thanks again!
