### ISSUE TITLE
StatusCodes documentation

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4169]
Trying to access this from the documentation and getting a 403 as below.

403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: E66B62422801E6AB
HostId: D3bLU9A2T0YIv57xCAqlbyofYnxWbmQVfQiTetXUyX7bMY / QnJR39CDDcYLU6dIWc3osnXPN0KU =
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: AccessDenied
Message: Access Denied

**Comment by manishas** [comment]
http://docs.shippable.com/ci/build_status/

**Comment by andye2004** [comment]
Thank you again @manishas
