### ISSUE TITLE
cp: cannot stat '/home/shippable/cexec/bin/*': No such file or directory

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#4170]
Hello,

I've upgraded my own node for shippable to v6.2.4(from v6.1.4), and I'm getting the following error:
`cp: cannot stat '/home/shippable/cexec/bin/*': No such file or directory`
I created the `/home/shippable/cexec/bin/` directory manually but it doesn't help.

The link to the build log is:
https://app.shippable.com/github/Knowre-Dev/knowre/runs/96/1/console

Thanks,
Kivol

**Comment by Kivol** [comment]
I've resolved this by commenting out `copy_bin_dir()` on `/home/shippable/cexec/build.sh`, like the following:

```
copy_bin_dir() {
#  $SUDO cp $PROGDIR/bin/* /usr/local/bin/
  ls $PROGDIR
}```

However, I think it needs to be patched anyway, for using BYON and custom build image.

**Comment by manishas** [comment]
This was fixed a while ago and this issue wasn't updated. Sorry about that!

Closing this issue.
