### ISSUE TITLE
Build is running twice

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#4171]
Hello,

From some day the shippable build script started to run twice, in parallel, in a single build.

For example:
https://app.shippable.com/github/Knowre-Dev/knowre/runs/98/1/console

Is it a bug, or is there any way to prevent this?

Thanks,
Kivol

**Comment by ric03uec** [comment]
@Kivol this happened because of an issue while deploying one of our services. This has bee fixed and you should not see multiple builds running now.
We apologize for the inconvenience.

**Comment by Kivol** [comment]
Thank you for the explanation!
