### ISSUE TITLE
504 Gateway Timeout

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4172]
Hello,

I am experiencing google cloud credentials related issues in my pipeline - therefore I decided to start from scratch so I can detect any configuration error. I failed removing all the objects: `DELETE https://api.shippable.com/resources/58440?hard=true` throws 504 GATEWAY TIMEOUT in little less than a minute time. Even worse a success message follows (_Resource has been deleted successfully._).

Could you please fix it or tell me what I make wrong? I will try to fix my issue another way in the mean time so please do not get confused if the job layout changes. Thank you

**Comment by trriplejay** [comment]
Hey, we're looking into this. It seems to be a bug in part of our delete flow. It looks like you were able to clean up the old resources, in which case you should be able to run your rSync job again to hopefully get your new items created and consistent.

We've opened an internal issue for the delete action. Let me know if you're still experiencing any issues that need to be resolved.

**Comment by RadekDvorak** [comment]
Thank you. I have managed to delete them one by one (few in several attempts). 

Then I run the rSync according to your advice and encountered 21 errors saying "_There is already a resource named ..._". I have seen similar error message before, this time the issue is that these resources are missing in my subscription dashboard. I would delete them but I can not.

**Comment by trriplejay** [comment]
it looks like you have two syncRepo set up that might be trying to add the same resources.  Names must be unique within a subscription. I'd recommend deleting one of them completely, then running the rSync of the other.

**Comment by RadekDvorak** [comment]
I find it difficult to find the other syncRepo. Either I make a silly mistake or it is not there at all. Even the search form found one syncRepo only.
![image](https://user-images.githubusercontent.com/672781/36997835-3b2fbbdc-20bb-11e8-90eb-c31e6ca19a98.png)

I think all I can do is rename the resources as a workaround. 

A wild guess: can the problem be that I delete syncrepo settings by editing it and deleting its name? :thinking:

**Comment by trriplejay** [comment]
if it's OK with you, i could delete your other repo from the back end here. i see one is tied to a repo called "kubernetes2". that seems like the one to remove, should I go ahead?

did you rename any of these projects at the source control?

**Comment by RadekDvorak** [comment]
I deleted kubernetes2 github repository when duplicate resources errors appeared. It is no longer visible in shippable UI. Please delete it.

**Comment by trriplejay** [comment]
ok, i think you're all cleaned up. If you run rSync once more i'd expect it to pass without errors. I decided not to since I see that it will trigger the rest of your pipeline :)

sorry for the inconvenience, we're investigating the root cause. This all started with the 504 timeout, right?

**Comment by RadekDvorak** [comment]
Thanks, rSync works correctly now.

This started when I was developing a workaround for another issue (probably [this one](https://github.com/Shippable/support/issues/4148)) and I decided to delete all the jobs and resources to eliminate any stale cache error. I decided to [delete all the resources](http://docs.shippable.com/platform/tutorial/workflow/crud-resource/#deleting-all-resources-at-the-same-time) at the same time without deleting them from the yaml config first. This is when the timeouts appeared.

**Comment by RadekDvorak** [comment]
Do you have any news on that https://github.com/Shippable/support/issues/4148#issuecomment-368228712 _shipctl-in-my-container_ issue? The new version has been out for two days and it should have solved my initial problem. The now running pipeline shows my workaround is unreliable :disappointed:

**Comment by manishas** [comment]
@RadekDvorak we shipped shipctl for custom images with the latest release. Notes are here: https://github.com/Shippable/admiral/blob/master/releaseNotes/v6.2.4.md

**Comment by RadekDvorak** [comment]
@manishas: I admit I did not read release notes thoroughly when I encountered the missing shipctl error again today ([the failed build](https://app.shippable.com/github/damejidlo/jobs/cargo-build/builds/5a9ecb22fece961500666041/console)). Should I open a new issue?
```
Initializing CLI integrations

Initializing gcloudKey for resource gcloud-cli
|___ Checking params
/var/lib/shippable/build/scripts/resources/cliConfig/gcloudKey/init.sh: line 32: shipctl: command not found
```

**Comment by manishas** [comment]
You might have to switch to the latest ami. @ambarish2012 can you help with this?

**Comment by RadekDvorak** [comment]
@manishas: this hint was sufficient. I changed the version and my build got past the critical point. Thank you. I was mislead by the name "stable". I thought it represents a dynamic label for the latest stable maintained version.

**Comment by manishas** [comment]
👍
