### ISSUE TITLE
Unable to setup webhook in GitHub after rename

### ISSUE THREAD

**Issue by jodastephen** [Shippable/support#4173]
I renamed one of our (OpenGamma) private GitHub projects, from `MarketCalcService` to [`ValuationService`](https://app.shippable.com/github/OpenGamma/ValuationService). I then went to shippable to change the [subscription](https://app.shippable.com/subs/github/OpenGamma/enable). I disabled the GitHub project, then re-enabled it. Unfortunately, this is not setting up the webhook in GitHub - GitHub shows no webhooks for the project.

Googling suggests using the "Hook" button to try and create the ciRepo, but I get this: `postJobDependency for :resourceId 63006 returned error: resource not found for id: 56969`.

Any suggestions as to how to fix this mess?

**Comment by a-murphy** [comment]
The ciRepo for your project had been soft-deleted; I've updated that so you should no longer get the same error if you click the "hook" button.  However, to recreate the CI webhook, you'll need to click the "reset all keys" button in the same panel.

**Comment by jodastephen** [comment]
Works now thanks, although I do think the sequence of actions shouldn't have resulted in a problem.
