### ISSUE TITLE
Removed all GCE references, but getting unable to find account integration messages

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4174]
Hi, we are removing all of our GCE deployments and moving to exclusively AWS. 

I have updated our shippable.yml for this project so it no longer references the gcr-integration we had set up, and I've removed the GCR integrations from our account and the subscription (at least from what I can tell). 

Unfortunately, when I try to build one of my updated projects, I get complaints that the deleted integration doesn't exist, even though we aren't referencing it. 

Could you point me in the right direction on how to fix this issue? 

Thanks in advance.

Also, please see the screen shot for some further details:

https://app.shippable.com/github/formhero/formhero-ui/runs/361/1/console
![screen shot 2018-03-06 at 10 50 46 pm](https://user-images.githubusercontent.com/1018189/37072810-4f3357fc-2191-11e8-8a73-1b1ea728ab46.png)

**Comment by trriplejay** [comment]
you mentioned that you removed them from shippable.yml. does that include all references from any of your pipeline resources? it looks like it used to be referenced by a few image resources. can you confirm that those references are removed as well?

**Comment by ryan-kimber** [comment]
I believe we have all the references out now and we are able to build most of our CI projects once again, but we are still getting a big set of errors on our sync repo. 

Please see the inline image below. URL for this build is https://app.shippable.com/github/formhero/jobs/continuous-deployment_master_rSync/builds/5a9f60c55241fd1800df5996/console

![screen shot 2018-03-08 at 10 10 38 pm](https://user-images.githubusercontent.com/1018189/37188561-d7c29af0-231d-11e8-92a1-ec327cfda705.png)


I can't do much with these errors, because I don't know what they are referring to. =(

**Comment by trriplejay** [comment]
here's an example of one of the resources it's complaining about:
https://app.shippable.com/subs/github/formhero/resources/fh-email-queue-processor-container-img/versions

Based on the yml section on the page, we still see this resource as still having reference to the integration.  Can you confirm that this resource in your yml does not reference the integration?

**Comment by ryan-kimber** [comment]
That specific resource is declared in shippable.resources.yml in the following way: 

>  - name: fh-email-queue-processor-container-img
>    type: image
>    integration: ecr-integration
>    pointer:
>       sourceName: "448989908326.dkr.ecr.ca-central-1.amazonaws.com/fh-email-queue-processor"
>    seed:
>       versionName: "develop.108"

It's pointing to our ecr-integration, which is still declared (and being used throughout our CI builds).

**Comment by ryan-kimber** [comment]
I've managed to get past these error messages by updating all of our image resources and rebuilding, but despite the fact that none of them references the GCR integration there is still some weird behaviour with the versions of the resources themselves.

![screen shot 2018-03-10 at 1 27 57 pm](https://user-images.githubusercontent.com/1018189/37245516-31eafa0a-2467-11e8-84aa-39d4b0da40a6.png)

The above displayed versions were created by the same build, but somehow are showing with two numbers, and one with our proper ECR integration shown, but a second, higher-numbered build still referencing the GCR path. 

This is preventing deployment, as our deploy to AWS is now trying to pull on non-existent image from GCR.

**Comment by ryan-kimber** [comment]
Still working on it, but it looks like if I reset the seedVersion for each resource to be the latest build, that might fix this (so far, so good on three modules).

**Comment by trriplejay** [comment]
is it possible the same resource names were declared in multiple syncRepos? or in multiple .yml files?  It looks like maybe you've got it all worked out now.  I think the extra version came from rSync running and seeing a changed seedVersion like you mentioned.  

what change did you make that eventually got those errors to go away?
