### ISSUE TITLE
Different shippable.yml for commits and PRs

### ISSUE THREAD

**Issue by Jan0707** [Shippable/support#4176]
Hey everyone,

As part of our shippable build, we run unit tests and end-to-end tests. I would like to run the unit tests on every commit, but would like to limit the end-to-end tests to only those jobs that have been triggered by Pull-Requests (as we use selenium and thus those tests are rather slow).

My current workaround in the shippable.yml is this:

`    - if [ "$IS_PULL_REQUEST" == true ]; then ./_ci/run-behat-ci.sh; fi`

Given the fact the we would like to introduce more differences between the non-PR and PR build, this seems like an unpractical solution.

I would much more prefer a solution that allows me to maintain two separate shippable configuration files: One for PR builds, one for the usual commits. 

Is there any way this is possible ? Or is there another solution ?

**Comment by ambarish2012** [comment]
@Jan0707 you can use a [runSh](http://docs.shippable.com/platform/workflow/job/runsh/)  job to cleanly separate the scripts that you want to execute for commits and pull requests. We do not support multiple configuration files yet.

runSh jobs offer most of the functionality of CI jobs with the exception of code coverage and test result visualizations. You can thus create two runSh jobs (one each for commits and pull requests) or you can just create one job for pull requests and leave the rest of your yml as is. The runSh job is typically defined in a separate section in your shippable.yml file or alternatively you can define the job in a separate shippable.jobs.yml file if you want separate configuration files. 

runSh jobs can take a [gitRepo resource](http://docs.shippable.com/platform/workflow/resource/gitrepo/) as an input, which is a pointer to your source code repository.  This resource can be configured to trigger specifically for pull requests or commits. When the job executes, it will checkout the git repository and execute the script code specified in the job. 

Here is a sample that you can look at - https://github.com/ambarish2012/pr-runsh-sample. In this sample I have created one runSh job in a shippable.yml file,  that is triggered only for pull requests. You can easily extend it to create two runSh jobs (which would need an additional gitRepo resource that is triggered for commits only).

Once you define the jobs/resources and commit your yml files, you will need to create a sync repository using the UI. Instructions for adding a sync repository can be found [here](http://docs.shippable.com/platform/tutorial/workflow/crud-syncrepo/#adding-a-syncrepo). Once the sync repository is created, you can see all your jobs and resources in the [SPOG](http://docs.shippable.com/platform/visibility/single-pane-of-glass-spog/).
