### ISSUE TITLE
Build fails with GitLab message

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4178]
Hello,

I replaced my runSh build job with a simpler post_ci setup. However, the [build fails](https://app.shippable.com/github/damejidlo/kubernetes/runs/311/1/console) and claims it is doing something with GitLab - a service we _do not use at all_. This may turn out be a simple misconfiguration. Still I am quite worried what is going on. Can you please advise me?

```
 Posting message for current job 32s  
reqProc|_common|saveState|_postFiles, :postFilesByResourceId failed for resourceId: 58420 with error Failed to execute project clone script for resource with id 58420 and name kubernetes_runCI with err Identity added: /tmp/550b00505ab6cc1352a5282f-254e6806-e1c3-4c36-8bf0-8991be60c885.pem (/tmp/550b00505ab6cc1352a5282f-254e6806-e1c3-4c36-8bf0-8991be60c885.pem)
,Cloning into '/tmp/550b00505ab6cc1352a5282f-254e6806-e1c3-4c36-8bf0-8991be60c885'...
,GitLab: The project you were looking for could not be found.
,fatal: Could not read from remote repository.
```

**Comment by trriplejay** [comment]
Hi @RadekDvorak. Shippable uses gitlab internally, so this isn't a misconfiguration on your part.  I'm investigating this issue.

**Comment by RadekDvorak** [comment]
Hi, the issue is gone. Thank you
