### ISSUE TITLE
How to .....

### ISSUE THREAD

**Issue by jplimpens** [Shippable/support#4179]
Our current way of working is as follows:
- All commits on the development branch are tested for integration (basically CI)
- On success the commits are merged into a release branch. The release branch then does CI, sets up a test environment, creates a manifest, deploys the image and runs tests.
- When all tests are succesfull we merge the release branch into master and delete the test environment
- The master branch then does CI and deploys the image to production with some final tests.

Now... on Shippable I can set the rsync job to the releases branch and create all the necessary jobs (including cleanup and merge to master). On master branch, CI is run automatically since the repo hook sees the merge commit (which is fine).

But what is the best way to progress from here.. 
- Should I create a rsync job for the master branch too?
- can I use the same runCI job then to trigger the next job (on the master branch)? And what would that do to the jobs on the release branch and vica versa?
- Or should I solve this in other ways?

**Comment by trriplejay** [comment]
The branch that contains the pipeline jobs doesn't really matter. You can have a sync job for each branch, or you can add all of your resources under the same branch. It's up to you based on how you'd want it logically split up.

If you do add two separate sync jobs, the resources still need to be uniquely named within the subscription.  Resources and jobs from one branch can be used as IN/OUT to resources/jobs in the other branch.

If you have one runCI job that will execute for both release branch commits and master branch commits, and you want it to take different pipeline actions based on which branch was built, the best way to do that is by adding OUT steps to your CI job.  the CI job knows which branch it is running for, and that information is available in the environment (`$BRANCH`).  You can use some conditional logic to update an OUT resource based on which branch ran, and that OUT resource would trigger the subsequent relevant workflow.

If that sounds like what you're looking for we could provide a sample.

**Comment by jplimpens** [comment]
So, basically (if I understand correctly) we can do something like:
`
jobs:
  - name: my_app_runCI
    type: runCI
    steps:
      - OUT: if [ "$BRANCH" == "release" ]; then
                               my_image_test;
                  else
                               my_image_prod
                  fi

  - name: next-job-in-pipeline_for_test
    type: deploy/manifest/runSh
    steps:
      - IN: my_image_test

  - name: next-job-in-pipeline_for_prod
    type: deploy/manifest/runSh
    steps:
      - IN: my_image_prod
`
That would work for me. Although I wonder whether having a branches option on jobs would provide more flexibility. Something like
`
 - name: next-job-in-pipeline
    type: deploy/manifest/runSh
    branches:
       only:
          - master
          - releases
    steps:
      - IN: my_image
`
Anyway, for now the conditional logic on an OUT resource should do the trick.
Samples are welcome :-)

**Comment by ambarish2012** [comment]
@jplimpens here is an example you can look at: https://github.com/ambarish2012/multi-branch-image-resource-sample/blob/master/shippable.yml

**Comment by jplimpens** [comment]
I used the sample to split jobs between branches. Unfortunatly I can't confrm it works. Ever since I ran into many issues of all kinds. Once fixed I can give more useful comment.

**Comment by jplimpens** [comment]
So.. after all findings in #4213 it seems shipctl post_resource_state in post_ci messes up the image configuration. Sourcename and version set in the resource are not used (or overwritten).

How to proceed?

**Comment by trriplejay** [comment]
actually, what 4213 was saying is that sourcename/version *are* being used, but your job is pushing to `latest`.  This means when ECS triest to pull the tag `release.70` it fails because it doesn't exist.  Your job still has to manually push that tag to the hub so that it can be pulled by ECS later.

do you want to push to "latest" each time, or do you want to push to a build-specific tag like "release.70"?  either one can work, but your "docker push" needs to match what you write out in post_resource_state.

**Comment by jplimpens** [comment]
Well. I figured that out too. Just took a little longer ;-)
What I didn't realized when adopting the above mentioned example (_then shipctl post_resource_state image_2 versionName $BRANCH.$BUILD_NUMBER;_) was that it would influence the version (and sourcename) of the configured resource. Even now, I stll don't understand why sourcename became empty. Note that AWS console should show URI:tag, but after starting over (kind of fresh start) the console showed just :tag (nothing before the : ).

So, what I still want to achieve is a split between jobs. Some run on the releases branch, others on the master branch. But preferably not based on version numbers since that screwed up many things (the resources got inconsistent at one point which resulted in failed builds on the development branch) :-) 
I understand it makes it easier, but versioning etc is something for the future (not something I want to implement right now).

Any alternatives?

**Comment by trriplejay** [comment]
Here's what I would suggest:

instead of doing post_resource_state, change those sections to something like this:
```
shipctl put_resource_state <resource> sourceName $IMAGE_REPOSITORY
shipctl put_resource_state <resource> versionName latest
shipctl put_resource_state <resource> buildNumber $BUILD_NUMBER
```

This will ensure that both sourceName and versionName are defined, assuming `$IMAGE_REPOSITORY` is defined in your yml.  This will also ensure that every build results in an image version getting created due to the changing build_number.  This is important for triggering downstream jobs.

Then, in your deploy job, since your image tag isn't actually changing (sticking with latest), you'll need to add a `force: true` to the manifest IN line, like this:
```
- IN: myManifest
  force: true
```
because otherwise, the deploy job will not deploy the manifest when no changes are detected (it sees the tag hasn't changed, and therefore skips the manifest).

does that make sense?

**Comment by jplimpens** [comment]
Well, I need to read more about shipctl, its options and its behaviour.
It seems to make sense since I already experiment with $IMAGE_REPOSITORY and $IMAGE_VERSION as environment variables (works in CI, but not tested yet for jobs).

Does it still require the use of versiontemplate on the resource? Something like below is what I have in mind, but skipping versiontemplate feels like not repeating (since these values get set with shipctl)
`
- name:             someImage
    type:             image
    integration:      AWS
    versionTemplate: 
          sourceName: $IMAGE_REPOSITORY
          versionName: $IMAGE_VERSION
`

**Comment by trriplejay** [comment]
versionTemplate is still necessary. The resource defined in the yml you can think of as an initial version to get things started.

so one of the reasons your "sourceName" ended up blank is that these two variables "image_repository" and "image_verison" do not have values at the time they are evaluated for this resource.  I'd probably recommend sticking with the script i provided and inserting some dummy values for sourceName and versionName in your resource yml.  If the image_repository doesn't change then you can just put the real value in your yml.

**Comment by jplimpens** [comment]
I prefer envs and so far this seems to work. Even the resource info on the dashboard nicely gets updated.
Thanks for the help.
