### ISSUE TITLE
Builds get stuck starting yesterday for a trial project

### ISSUE THREAD

**Issue by immerrr** [Shippable/support#4181]
We've been evaluating shippable to consider switching from other CI provider, and it has been all good until yesterday, when builds started to get stuck when preparing the container without obvious reasons.

Here's the project ID: 5a8586171d4b560600c4ebfd, builds starting from ~146 are affected.

Do you have any private support channels so as to discuss issues without links that disclose private repository names?

**Comment by khuezy** [comment]
GitHub has some issues yesterday. It looks to be resolved now.

**Comment by manishas** [comment]
I don’t think this is related to the GitHub issues from yesterday. 

@ambarish2012 @trriplejay can we look into this?

**Comment by trriplejay** [comment]
we're investigating.

**Comment by trriplejay** [comment]
@immerrr it looks like our build agent container is getting killed, possibly by something in your script.  Shippable utilizes docker to orchestrate the build, so we have a container-based agent running on the machine, and to run your build we start up another container that houses your code and executes your yml.  This build container has the host's docker mounted, so any docker commands you issue in your script can impact Shippable's agents.

**Comment by immerrr** [comment]
@trriplejay oh, right, i had a problem with docker images being cached from previous builds, and thus I added 
```
docker kill $(docker ps -q) && docker rm $(docker ps -aq)
```
to ensure that the images are fresh, but I guess I'll have to find another way around :) Thank you!
