### ISSUE TITLE
SHIPPABLE_COMMIT_RANGE is not useful for the first commit in a new branch

### ISSUE THREAD

**Issue by larsonmpdx** [Shippable/support#4182]
### Description of your issue:
I have a monorepo with a change detection script similar to your blog post. 
 this uses SHIPPABLE_COMMIT_RANGE to choose which things to build
http://blog.shippable.com/build-test-and-deploy-applications-independently-from-a-monorepo

I have a runCI job that's downstream of a runSh job described in this issue:
https://github.com/Shippable/support/issues/4155

SHIPPABLE_COMMIT_RANGE looks like this on the first commit of a new branch.  otherwise it's normal
0000000000000000000000000000000000000000...d1af60f85dbd7b822e3e78f1b5eddc6ece6ec0bd

see failed run at https://app.shippable.com/github/MIQ-sirrus7/witcan/runs/51/1/console

**Comment by trriplejay** [comment]
Hello,

I think the blog did not take this scenario into account. We'll work on getting that updated.  This sha of zeroes is actually the range given to us by github.  The script would need to be updated to handle that case, but technically it's the expected value in the range when creating a new branch.

**Comment by sixteni** [comment]
Hi,
Either you always push the branch before you make your first commit (error prone)
Or you need to get the range of commits between the latest (e.g. the latest commit in you new branch) and the latest commit in the parents branch:
```{r, engine='bash', count_lines}

LAST_NEW_BRANCH_COMMIT=$(git log --name-status HEAD^..HEAD --pretty=oneline | awk 'FNR==1 {print $1}')
LAST_PAREN_COMMIT=$(git rev-list --simplify-by-decoration -2 HEAD | awk 'FNR==2')
folders=`git diff --name-only $LAST_NEW_BRANCH_COMMIT ^LAST_PAREN_COMMIT | sort -u | awk 'BEGIN {FS="/"} {print $1}' | uniq`
```

I hope that helps!

**Comment by ambarish2012** [comment]
@sixteni thanks for that excellent suggestion, I will update my sample.
