### ISSUE TITLE
runSh not being triggered by github commits, but only sometimes

### ISSUE THREAD

**Issue by larsonmpdx** [Shippable/support#4183]
### Description of your issue:
I have a monorepo discussed in this issue:
https://github.com/Shippable/support/issues/4155

my shippable.yml is a single file for the pipeline stuff and for the runCi "build" job.  Sometimes my runSh job triggers with a new github commit and about 20% of the time it doesn't.

see a sanitized SPOG below, above shows the the gitRepo at version 126 and below shows the dependencies on the runSh job, showing the gitrepo at version 125 and not updating after a half hour
![image](https://user-images.githubusercontent.com/12436438/37184869-5f528e84-22f2-11e8-9a2f-2ce12fc42f28.png)

see https://app.shippable.com/subs/github/MIQ-sirrus7/dashboard

**Comment by a-murphy** [comment]
Updates to gitRepos that contain changes to a `shippable.yml` file do not trigger subsequent jobs.  This is to avoid triggering updated jobs when the same repository is also a syncRepo before the rSync job has finished processing the updates.

**Comment by larsonmpdx** [comment]
it triggers 80% of the time.  is that a bug?

should I break my shippable.yml into two repos?

**Comment by larsonmpdx** [comment]
wait.  do you mean the git update contents are analyzed?

**Comment by a-murphy** [comment]
We fetch the list of modified file names from GitHub through their API for the commit range received and check for any `shippable.yml` files.  We don't process the contents of the files at that time.

**Comment by larsonmpdx** [comment]
ok.  I can work with this, thanks!
