### ISSUE TITLE
Error of "Permission denied (publickey)" in "git_sync"

### ISSUE THREAD

**Issue by JoeRattanamaneesilp** [Shippable/support#4185]
### Description of your issue:
Currently we are getting an error of `Permission denied (publickey).` in `git_sync`.

Please see the build log in [here](https://app.shippable.com/github/bauerxcelmedia/wn-article/runs/93/1/console)

Could you please advise how to solve this issue?

Note: I think it may be similar to this past issue https://github.com/Shippable/support/issues/3863

**Comment by trriplejay** [comment]
In your case, you can generate a new key by going to your project settings page and clicking the "reset all keys" button near the bottom.  This will create a new deployment key on your repository.

**Comment by JoeRattanamaneesilp** [comment]
Thanks @trriplejay. The build can be run successfully now.
