### ISSUE TITLE
Webhook Config for Pull Requests not working

### ISSUE THREAD

**Issue by khuezy** [Shippable/support#4187]
### Description of your issue:
Hi,

It looks like the `Pull Request` webhook config option does not trigger builds.

To reproduce:

1. Turn off "Commit"
2. Turn on "Pull Request"

Then create a PR. The build does not run.

**Comment by manishas** [comment]
@khuezy can you point us to the repo where you're seeing this behavior?

**Comment by ambarish2012** [comment]
@khuezy please let me know if pull requests working for you.

**Comment by khuezy** [comment]
@manishas @ambarish2012 Thanks, it is working now.

Any insights on why it wasn't before?

**Comment by ambarish2012** [comment]
@khuezy we can debug if it occurs again, we don't know what was causing the issue before.

**Comment by khuezy** [comment]
Oops, I spoke too soon. I turned on the "Commits" switch. It isn't working.

**Comment by ambarish2012** [comment]
Please can you send me the link to your project in Shippable UI?

**Comment by khuezy** [comment]
https://app.shippable.com/github/khuezy/Coinfucius/dashboard

**Comment by ambarish2012** [comment]
Please could you go to https://app.shippable.com/github/khuezy/Coinfucius/settings, scroll to the bottom of the page and click on "Reset all keys". This will recreate the webhooks on your project. We can then debug if the problem resurfaces.

**Comment by khuezy** [comment]
The github webhook did fire off, here is the response:
```
{"message":"Queuing run"}
```

**Comment by khuezy** [comment]
Sure, this will be my 3rd time doing this though.

**Comment by khuezy** [comment]
I just pushed a commit to my PR but there's no jobs on Shippable.

**Comment by ambarish2012** [comment]
Can we get into a quick call to debug your issue?

**Comment by khuezy** [comment]
Sure

**Comment by ambarish2012** [comment]
https://zoom.us/j/822597921

**Comment by ambarish2012** [comment]
@khuezy thanks for your time yesterday on Zoom. Please can email me the entire webhook headers, body and response to ambarish@shippable.com.

**Comment by ambarish2012** [comment]
@khuezy the problem is that you raising PRs from the develop branch but you have excluded the develop branch in your yml. Once you remove that branch exclusion, your PR builds will start working.

**Comment by khuezy** [comment]
Ah!

D'oh

Thanks for looking into this @ambarish2012 

I misunderstood what the `branches > except` properties were. I thought it would exclude build those branches.

**Comment by khuezy** [comment]
It is working now. Thanks and sorry for wasting your time :)
