### ISSUE TITLE
Pre-ci docker error: flag provided but not defined: --shm-size

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#4189]
https://app.shippable.com/bitbucket/swisnl/nkl/runs/823/1/console

For some reason our pre-ci command doesn't work anymore. It gives a weird docker error when running the following command

```
docker run -d --name=grid -p 4444:24444 -p 5900:25900 -e TZ="CET" --shm-size=1g --network=selenium_network --ip=172.25.3.3 -itd --name=selenium elgalu/selenium
flag provided but not defined: --shm-size```

**Comment by bbrala** [comment]
Pinging @JaZo

**Comment by rageshkrishna** [comment]
@bbrala Did you change the "Runtime version" in your node pool? I see that your older builds were running on Docker 17.06, whereas the one that's failing now is running on Docker 1.9. This can happen only if your runtime version got switched to "Stable".

Can you please try switching your default node pool to a more recent runtime version so you can get back to running on Docker 17.06?
