### ISSUE TITLE
All runSh jobs STUCK 

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4190]
Hello,

all my runSh jobs are frozen with 
```
Info 0s  
Running job on on-demand node pool: default_node_pool
```
I think 18 minute delay is quite an anomaly

https://app.shippable.com/github/damejidlo/jobs/cargo-gateway_stage/builds/5aa791ba5241fd1800e31568/console
https://app.shippable.com/github/damejidlo/jobs/cargo-db_migrate_stage/builds/5aa79451fece9615006a786e/console
https://app.shippable.com/github/damejidlo/jobs/cargo-definitions-rabbitmq_stage/builds/5aa79451fdc5ae1500336359/console

**Comment by shrivara** [comment]
We've been noticing increased provisioning errors from AWS for about 45 minutes now. [AWS status page](https://status.aws.amazon.com/) reported an ongoing issue about 15 minutes ago. This seems to be resolved now for us now, but we're continuing to monitor.
