### ISSUE TITLE
How to delete nodes

### ISSUE THREAD

**Issue by Jan0707** [Shippable/support#4191]
Hey everyone,

I am currently re-building our docker test environment and in that process I sometimes end up with nodes that are unusable to me ( which is ok and not shippable's fault).

In those cases however I would like to be able to manually delete single nodes so that for the next job a new node must be provisioned. Several months ago I stumbled over that option somewhere, but I cannot seem to find it now that I need it.

Any help is kindly appreciated !

**Comment by ambarish2012** [comment]
@Jan0707 you cannot directly delete a node. 

However, if you switch to a paid plan, you can run your builds with SSH access. This will force a new node to be allocated. Alternatively, you can [attach your own Node](http://docs.shippable.com/platform/tutorial/runtime/custom-nodes/#byon-nodes).

**Comment by Jan0707** [comment]
I am on a paid plan already and we do not want to bring our own nodes for convenience and maintenance reasons. But thanks for the ssh hint anyways, I was not aware of the fact that It forces the instantiation of a new node.
