### ISSUE TITLE
Visualize CTest output

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4192]
I would like to have shippable to parse my ctest output. For that, I used this tutorial (http://alexott.blogspot.co.uk/2012/03/jenkins-cmakectest.html) to convert the ctest xml output into a JUnit xml output.

This converted file cannot be parsed using Shippable:
```
reports --destination /shippableci/testresults tests --source /root/src/bitbucket.org/ArnaudBotella/georep/shippable/testresults 0s  
time="2018-03-13T14:49:37Z" level=error msg="No valid test parser : /root/src/bitbucket.org/ArnaudBotella/georep/shippable/testresults/CTestResults.xml"
time="2018-03-13T14:49:37Z" level=fatal msg="Unable to parse XML content"
```

Do you have an example of conversion tool from ctest to junit?

Job link: https://app.shippable.com/bitbucket/ArnaudBotella/georep/runs/22/1/console

Thanks for your answer.

**Comment by larsonmpdx** [comment]
I'm using this xsl and it's working - https://github.com/rpavlik/jenkins-ctest-plugin/blob/master/ctest-to-junit.xsl

make sure the original ctest file isn't in shippable/testresults and the converted file is

**Comment by BotellaA** [comment]
It works using your xsl file. Thanks for your help!
