### ISSUE TITLE
Downloaded file.

### ISSUE THREAD

**Issue by tarpanMpatel** [Shippable/support#4196]
I am running my test build, using selenium for Java automation test.

How can I verify the downloaded file?
(i.e I have one scenario in which Script is running in chrome browser and one test has Download file functionality. So I need where the file is downloaded when I am running the test on shippable-browserstack)

**Comment by ambarish2012** [comment]
@tarpanMpatel thats a better question to ask on the Selenium or Chrome support forums since they would know best.
