### ISSUE TITLE
runSh job queued, not running

### ISSUE THREAD

**Issue by brentfamily1** [Shippable/support#4197]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure, https://app.shippable.com/github/PassageTech/jobs/MPM4_Package/builds/5aa986ccfdc5ae150034a488/console

- Scripts called from the yml (optional)

This build is still marked as 'Waiting' and I have available minons to process the queued job.  Why is it still waiting?

**Comment by brentfamily1** [comment]
Please note, it is running now but the job was queued for over 30 minutes with an available minion to process the job.  Was not until all jobs were complete that Shippable started to process this stuck build.

**Comment by a-murphy** [comment]
The most common reason for a job to be waiting while there is a minion available is if one of the inputs to the job is still processing.  More information about when jobs will wait and how to set `dependencyMode` to change that is available in the [documentation](http://docs.shippable.com/platform/workflow/overview/#trigger-modes).

**Comment by brentfamily1** [comment]
Thank you @a-murphy, this build was not dependent on the job that was being processed.  This was the build that was in process, https://app.shippable.com/github/PassageTech/shippable-ci/runs/487/1/console and this is the definition of the runSh job:

`
jobs:
- name: MPM4_Package
    type: runSh
    steps:
      - IN: MPM4_Alpha
      - IN: SFDX_DEVHUB
      - IN: SHIPPABLE_ASSETS
        switch: off
      - IN: Milestones-PM-Plus_master
        switch: off

- name: MPM4_Alpha
    type: release
    bump: alpha
    steps:
      - IN: MPM_VERSION
      - IN: Milestones-PM-Plus_master

resources:
  - name: SFDX_DEVHUB
    type: integration
    integration: SFDX_DEVHUB

 - name: SHIPPABLE_ASSETS
    type: gitRepo
    integration: GitHub
    pointer:
      sourceName: PassageTech/shippable-ci
      branch: master
      buildOnCommit: true
      buildOnPullRequest: false
      buildOnRelease: false
      buildOnTagPush: false
`
Please note: SHIPPABLE_ASSETS is referring to the same repo as the build that was in process but not the same branch.  The resource points to the 'master' branch and the build in process was on the 'cleanup_sfdx_update' branch.

**Comment by ambarish2012** [comment]
https://zoom.us/j/822597921

**Comment by ambarish2012** [comment]
@brentfamily1 do you see this issue consistently or was this a one time occurence? We can definitely debug this issue while the job is blocked, so please let us know the next time you see this behaviour.

**Comment by brentfamily1** [comment]
I have only personally observed this once.  Will ask my team to monitor the dashboard to see if we encounter the problem again.

**Comment by manishas** [comment]
@brentfamily1 I am closing this issue, but please let us know if you see this again and we'll be happy to reopen and take a look.
