### ISSUE TITLE
Unable to login with GitHub

### ISSUE THREAD

**Issue by ewhamilton** [Shippable/support#4198]
I am trying to access/login using my official GitHub account but shippable is giving an error: Your account has been blocked as it was identified to be violating our security policy.

Note: My colleague previously had similar issue and reported it as #4085.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by a-murphy** [comment]
It looks like you've been able to log in.  Let us know if you run into any other problems.

**Comment by ewhamilton** [comment]
All working now.  Thanks.
