### ISSUE TITLE
failed to obtain yml from provider - getContents returned an error 403 with response Filtered by adapter because the returned  content-type is text/html; charset=utf-8

### ISSUE THREAD

**Issue by luislobo** [Shippable/support#4203]
Hi,

We started having issues with when starting builds:

`failed to obtain yml from providergetContents returned an error 403 with response Filtered by adapter because the returned  content-type is text/html; charset=utf-8`

Our account is https://app.shippable.com/accounts/58ab89a78b69ec0f00842564

Is there something that needs to be changed? I thought it might have been the integration with bitbucket... but for some reason, I cannot fix it.

Can you please help me with the issue? I don't get any other error anywhere else

**Comment by a-murphy** [comment]
It sounds like the account used to get the YML file doesn't have permission.  Are these webhook or manual builds?  You can try going to the settings page for that project and selecting a different "Account Used" to be used to process webhooks.  We do check the permissions of the account selected, but it may be that the account currently selected has access to the repository and not the files in it.

And, could you let us know which project(s) are getting this error?  There's a "Project Id" in the bottom right corner of the project page if you don't want to include the name.

**Comment by luislobo** [comment]
For some strange reason, it started to work. Nothing changed... Did you do anything? Thanks!

**Comment by trriplejay** [comment]
We didn't take any action.  Shippable automatically synchronizes permissions with the source provider every few hours, so it's possible that when your account synced, whatever permission issue you originally had was automatically fixed.

I'll close this but feel free to reopen if the issue reoccurs.
