### ISSUE TITLE
Using curl command results in messy log output

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4204]
Seems strange this one. Don't know if it relates to commands other than curl but when I use this in my yaml:

```yaml
build:
  ci:
    # Download maven settings file and pass to maven command
    - >
      echo "Attempting to download ..."
      http_status=$( \
          curl -s -O -w "%{http_code}" \
               -H "Accept: application/vnd.github.v3.raw" \
               -H "Authorization: token ${TOKEN}" \
               -L "https://api.github.com/repos/...l" \
      )

      [ ! "${http_status}" = "200" ] && ( echo "Failed to download..., status was ${http_status}" && exit 1 )
```

We end up with really messy logs for the CI build. Results can be viewed [here](https://app.shippable.com/github/yambay-tech/application-config-ee/runs/94/1/console)

**Comment by manishas** [comment]
Sorry for the late response.... will take this to the team and see how we can address it.

**Comment by manishas** [comment]
@andye2004 can you clarify what you mean by messy output? We took a look at the logs for your build and didn't notice anything obvious.

**Comment by manishas** [comment]
I am closing this issue due to lack of response. @andye2004 if you are still running into this, let us know.
