### ISSUE TITLE
Postgis in docker fails build

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4205]
Hey guys, need a bit of help with something. We are trying to run some integrations tests as part of one of our builds and it's failing with a connection refused exception.

We are using a maven plugin configured as below to download and start a docker image of the postgis DB.

The build failures can be seen [here](https://app.shippable.com/github/yambay-tech/viz-server/runs/10/1/console)

```xml
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>docker-maven-plugin</artifactId>
                <version>0.24.0</version>
                <executions>
                    <execution>
                        <id>prepare-it-database</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>start</goal>
                        </goals>
                        <configuration>
                            <images>
                                <image>
                                    <name>mdillon/postgis</name>
                                    <alias>it-database</alias>
                                    <run>
                                        <env>
                                            <POSTGRES_USER>REDACTED</POSTGRES_USER>
                                            <POSTGRES_PASSWORD>REDACTED</POSTGRES_PASSWORD>
                                            <POSTGRES_DB>REDACTED</POSTGRES_DB>
                                        </env>
                                        <ports>
                                            <port>5432:5432</port>
                                        </ports>
                                        <wait>
                                            <log>(?s)database system is ready to accept connections</log>
                                            <time>20000</time>
                                        </wait>
                                    </run>
                                </image>
                            </images>
                        </configuration>
                    </execution>
                    <execution>
                        <id>remove-it-database</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
```

**Comment by rageshkrishna** [comment]
By default, we launch CI build containers with the `--privileged=true --net=bridge` docker options. This means that `127.0.0.1` from inside the container actually refers to the container itself and not the host. You could make it work with one of the following approaches:

1. Use the `pre_ci_boot` section in your YML file specify custom docker options and bring up the build container with `host` networking:

    ````yaml
    pre_ci_boot:
      image_name: your/image
      image_tag: your_tag
      options: "--privileged=true --net=host"
    ````

1. If you prefer to keep using bridge networking instead, try changing your test to connect to `172.17.0.1` as that's the bridge IP address and any services you host with port forwarding from the host (as you are doing) should be accessible on that IP address. I have a (somewhat) similar scenario working in a sample here: https://github.com/rageshkrishna/postgres_remote/blob/master/shippable.yml

**Comment by andye2004** [comment]
@rageshkrishna Thanks Ragesh, got that resolved now. Just some other issues to work through.

**Comment by rageshkrishna** [comment]
Good to know. I'm closing this issue as I believe it's resolved. Let me know if you need any more help with this.
