### ISSUE TITLE
Builds hung last night (and are still hanging)

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#4206]
Last night a few builds hung and didn't timeout.

https://app.shippable.com/bitbucket/swisnl/jobs/fussballyDependencyUpgrade/builds/5ab04f33fdc5ae150037932b/

https://app.shippable.com/bitbucket/swisnl/jobs/gezondewerkvloerDrupalUpdate/builds/5ab04f33fdc5ae150037932a/

https://app.shippable.com/bitbucket/swisnl/jobs/eurosafeDrupalUpdate/builds/5ab04f33ec373f17004e589e/

Not sure why.

**Comment by bbrala** [comment]
Even after canceling the last few runs it wasn't continueing the queue. I deleted the node pool and recreated it to see if that helps.

But it isn't picking up new builds. :(

**Comment by bbrala** [comment]
And the builds have resumed again.

**Comment by trriplejay** [comment]
@bbrala we suspect that there was some issue with the nodes. next time if a build appears stuck, let us know and we can debug while it's still processing.

**Comment by bbrala** [comment]
Will do

**Comment by bbrala** [comment]
@trriplejay I got a new hanging build.

https://app.shippable.com/bitbucket/swisnl/jobs/fussballyDependencyUpgrade/builds/5ab2f20cee4604160024e076/console

**Comment by trriplejay** [comment]
@bbrala the only thing that looks suspicious is that there are several extra containers running, and some of them have errors like this:

```
 * Starting MySQL (Percona Server) database server mysqld                [fail]
```

but others appear to not encounter that error. perhaps the builds that get stuck are ones that experience that error? does your build script wait for some condition in the container that will never be met if this failure occurs?

**Comment by bbrala** [comment]
Hmm, it should not really wait for condition. I'll see if i can reproduce it with that project and see if that might be a problem. De image it runs on is updates automaticly, perhaps something broke in a recent build.

**Comment by manishas** [comment]
@bbrala do you still need help with this?

**Comment by bbrala** [comment]
The culprits were unclosed containers on runsh jobs. So I added a docker kill command on start of the jobs so that the jobs won't keep stacking up. This seems to have fixed the issue.

Thanks for the follow up

Sent from Nine<http://www.9folders.com/>
________________________________
Van: Manisha <notifications@github.com>
verzonden: dinsdag 24 april 2018 18:51
Aan: Shippable/support
Cc: Björn Brala; Mention
Onderwerp: Re: [Shippable/support] Builds hung last night (and are still hanging) (#4206)


@bbrala<https://github.com/bbrala> do you still need help with this?

**Comment by manishas** [comment]
:+1:
