### ISSUE TITLE
Stuck rsync repo

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4207]
Hi,

my rsync repo [seems to be stuck](https://app.shippable.com/github/damejidlo/jobs/kubernetes_master_rSync/builds/5ab0e558fdc5ae150037daa3/console) at an old revision `72ebab0ad`. The CI job correctly [knows](https://app.shippable.com/subs/github/damejidlo/resources/kubernetes_ciRepo/versions) that the latest one is `e0a25f0758d`.

This might have been caused by me force pushing to the master branch. Still I consider force push a valid operation which should not cause any trouble.

I have paused the subsequent jobs so that you can refresh the job without any negative consequences.

**Comment by trriplejay** [comment]
Hi @RadekDvorak 

rSync only runs if changes to the `.yml` files are detected.  Did your latest sha contain changes to your pipeline configuration?

**Comment by RadekDvorak** [comment]
Hi @trriplejay,

there are `shippable.yml` changes:
```
git --no-pager diff e0a25f0758d 72ebab0ad --stat
 README.md                   |  2 +-
 kubernetes/conf.d/site.conf |  2 +-
 shippable.yml               | 63 ++++++++++++++++++++++++++++-----------------------------------
 3 files changed, 30 insertions(+), 37 deletions(-)
```

**Comment by trriplejay** [comment]
hmm, can you do me a favor and verify that those two shas you're using for the diff are the same ones that are sent in the webhook payload for the commit? 

You can see the payload on github in project->settings->webhooks, then find the one that has a url like `resources/:id/hook`

and the before/after should be near the top:
![image](https://user-images.githubusercontent.com/6869398/37668686-4b82eece-2c22-11e8-9b9f-df307c8304b5.png)

and if they're different, can you issue the diff on that and see if there's still a change to shippable.yml? this could be related to the force push as you suggested.

**Comment by RadekDvorak** [comment]
Regarding resource 63050, the syncRepo: the complete chain described by callbacks is
**1.** 72ebab -> fdc803
```
$ git --no-pager diff --stat 72ebab fdc803
 README.md                   |  2 +-
 kubernetes/conf.d/site.conf |  2 +-
 shippable.yml               | 63 +++++++++++++++++++++++++++++++++++----------------------------
 3 files changed, 37 insertions(+), 30 deletions(-)
```
**2.** fdc803 -> 648bb8
```
$ git --no-pager diff --stat  fdc803 648bb8
 README.md | 2 +-
```

**3.** 648bb8 -> e0a25f
```
$ git --no-pager diff --stat  648bb8 e0a25f
 README.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by RadekDvorak** [comment]
My use case was to keep different pipeline configurations in separate branches and then hard reset master to one, force push it and have shippable deploy it. It is possible that diff showed different results at that time because these branches were not pushed to github.

With this information I updated the resource by simply changing a comment in my `shippable.yml`. 

I would politely suggest documenting the behaviour and possibly mentioning the issue at runtime somewhere (eg by the resource) if this annomaly is detectable  at the time diff is made. This could happen to someone else in the future.
