### ISSUE TITLE
Ubuntu distribution on AMI V6.2.4

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4208]
As per the title really, can some tell me the distribution please?

**Comment by andye2004** [comment]
Also, docs are out of date with the latest image being stated as 16.04.3 LTS.

**Comment by trriplejay** [comment]
the underlying host machine is running ubuntu 14.04.  The containers that the build runs inside are built on ubuntu 16.04.

**Comment by trriplejay** [comment]
I'll open an issue to update the docs. thanks for pointing out the error.  We do plan to release an ubuntu16.04 base AMI soon.

**Comment by andye2004** [comment]
@trriplejay Thanks!
