### ISSUE TITLE
git sync finishes, build_ci never starts

### ISSUE THREAD

**Issue by fieldawarepiotr** [Shippable/support#4209]
### Description of your issue:
https://app.shippable.com/github/fieldaware/fieldaware/runs/1897/4/console

I tried everything I can think of:
- Select different branch
- Reset node
- Different node version
- Reset SCM

Git sync step finishes, but build ci never starts, I tried rebuild ~10 times, nothing.

Please fix it, it blocks everything I'm working on.

**Comment by trriplejay** [comment]
we're investigating

**Comment by trriplejay** [comment]
It looks like something is wiping out our build orchestrator.  Are you by chance removing all docker containers at the beginning of your script?

Shippable runs a agent on the build machine inside a container, and also executes your build inside a separate container by default, so if you force remove all containers, your build will get stuck. could this be the case?

**Comment by fieldawarepiotr** [comment]
yes, Sometimes I got hanging containers from previous builds. So to get a clean slate to remove all the containers, i'll stop doing it now. Thanks for the support <3
