### ISSUE TITLE
Publish a /decrypt API endpoint

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#4211]
Hello,

We have internal CLIs using a non-documented `/decrypt` endpoint to decrypt secrets locally, which is convenient when editing configuration files. We recently added a new subscription and this endpoint no longer seems to work, if fails with a 404. I understand the endpoint is not documented, what would you think of exposing it officially in the public API ?

(Also, I am fairly surprised that APIs and build environments depend on the subscription or the  projects creation dates. We had the surprise to have a different docker version in our new subscription builds).

Thanks.

**Comment by trriplejay** [comment]
That URL is still valid.  The permissions on the URL are restrictive, so it's possible that the token being used to make the call does not have the same permission on the new project/subscription, in which case we would respond with a 404.  The user making the call should be considered an "admin" on the subscription.  If the subscription was recently added, you may need to manually sync your account to make sure you have the correct permissions before making the api call.

regarding the build environments, our system is to assign a subscription to the current "default" at the time the sub is created, and then as we continue to release new versions, we don't move existing subs.  This is to avoid breaking anyone's builds by updating versions and packages from underneath them.

**Comment by andye2004** [comment]
@ambarish2012 @trriplejay I know this is not a public API as already stated but how can I find information on it?

**Comment by pmezard** [comment]
@andye2004 use : 
```
POST /projects/$project_id/decrypt
{
     "value": $VALUE_TO_DECRYPT
}
```

I do not know what the problem is, also I do not understand how subscriptions work with hosted gitlabs, but we will not be using it anyway. I am closing the ticket.

Thank you for your answers.
