### ISSUE TITLE
Cannot login with my bitbucket

### ISSUE THREAD

**Issue by sanjaybahrani** [Shippable/support#4212]
I can't log in to shippable. I am getting error:

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

My bitbucket login: sanjay.bahrani@bnedloudcloud.com

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
