### ISSUE TITLE
Port already allocated, draining and now Creation of service was not idempotent

### ISSUE THREAD

**Issue by jplimpens** [Shippable/support#4213]
Today I'm having issues with CI and deployment of a container. In CI I spin up a container to do some tests. Always worked but my last builds now fail on port already allocated. I can't find anything in the history what could have changed to casue this error. However I might be missing something.
- How can I free up this port?

To continue (since these tests have always worked and nothing has changed), I just continued the pipeline. Rsync for the new shippable yml and running the jobs. Deployment at first failed with lots of Draining output, so I changed the method from default (blue/green) to replace.

Further I deregistered the active service on AWS (active task, inactive container).

Now I'm stuck on _Creation of service was not idempotent_
Any thoughts on how to fix this?

**Comment by a-murphy** [comment]
For the port already in use, you most likely still have a container running (and using that port) from a previous job.  If you name your containers, you can remove the container by name before starting a new container.  The number of containers running on a node can be checked in the "job node info" section of your logs under "sudo docker ps -a."  There should be one `reqproc` container (it's the build runner), but other containers at that point will usually be containers that were not removed in previous jobs.

And the deploy job error is a result of deleting the service on AWS.  Shippable expects that the service will be there, and it isn't.  If you right-click on the resource on the SPOG, there's a "reset" option that will deploy without assuming the service is on AWS.

**Comment by jplimpens** [comment]
For the port... I start and stop a container in the CI job (same script). But it seems not all containers have been stopped. Still don't know why this happened, but I'll add a "clean" before CI, just to make sure. Thanks.

For deployment... I removed all services on the ECS cluster and reset the job. Now I'm back to Unable to Start a service that is still Draining. Deployment method is replace.

**Comment by a-murphy** [comment]
When did you last delete the service on AWS?  I would expect that message to appear if the service was currently being deleted because draining usually refers to scaling the number of replicas to zero before removing the service.  Making sure the service has been fully deleted and then resetting should fix this.

**Comment by jplimpens** [comment]
Just before I re-ran the job with reset. I've deregistered the task again on AWS just now. First job to prepare the environment is now running. One finished I'll run the deploy job using reset again and let you know the outcome

**Comment by jplimpens** [comment]
It now gives me a _Failed to deploy manifest for type: replace_ 
Tomorrow another day. Ideas are welcome.

**Comment by a-murphy** [comment]
Common reasons include running out of space for deployments on the EC2 instances in your cluster and images that can't be pulled (such as tags that don't exist).  The "events" tab for your service on AWS will have a list of messages that usually includes the reason.

**Comment by jplimpens** [comment]
Another day, same error. It gives a CannotPullContainerError: API error (404): pull access denied for jdemo, repository does not exist or may require 'docker login'

But a user jdemo is non existent. Repo exists and using AWS console it all works.
Shippable user and role have been set to full access on the repo. In the resource image I use the full ECR URI. Policy simulation in AWS on the role verifies the role can download images.
In Shippable I use the AWS Keys integration.

What am I missing?

**Comment by jplimpens** [comment]
Another day, same issue still. But some more info :-)
I get a pull access denied for jdemo, repository does not exist or may require 'docker login

At first I thought of a strange user (there is no user jdemo) or policy setting or something. But policy simulation with the shippable role works fine.

So I figured to create a new version of the task created with shippable. There I see a non existent image
jdemo:releases.44.

In the resource image (shippable yml) I use the ECR URI as sourcename. Where, how and why is this translated into jdemo?

**Comment by a-murphy** [comment]
For the image tag that doesn't exist, it looks like the image resource was updated with `versionName` `release.70` in run 70, but the image was pushed with tag `latest`.  The `versionName` in the updated image resource should be the tag pushed.  

The `jdemo` in your message is part of your image name.  It doesn't have anything to do with the user authenticated; Docker just couldn't find the image.  Either you don't have access to that image or it doesn't exist.

**Comment by jplimpens** [comment]
We can close this issue and continue #4179 as far as I'm considered.
