### ISSUE TITLE
Feature Request : Upgrade jfrog instance

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4217]
As per title guys, any chance we can get the jfrog instance used for integration updated? It's now at 1.14 and has some additional commands that would be really useful to have access to. I know I could download / install a newer instance but that sucks when it's already integrated.

Thanks, Andy.

**Comment by a-murphy** [comment]
We've updated the version of the JFrog CLI available in the [v6.4.4](http://docs.shippable.com/platform/runtime/machine-image/ami-v644/) images to 1.14.0.  Directions to change the machine image (and default image versions) for node pools in your subscription are [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).  If you have your current image specified in the `pre_ci_boot` section of your `shippable.yml` file, you'll also need to update that.
