### ISSUE TITLE
Synchronize SCMs stuck.

### ISSUE THREAD

**Issue by dovydasvenckus** [Shippable/support#4219]
Since yesterday I'm stuck on Synchronize SCMs. Because it does not complete I can't enable CI on my new repository. 

Problem appeared when I have moved repository from organization to my account. After that I have deleted that organization.

**Comment by ambarish2012** [comment]
@dovydasvenckus which specific repository are you having an issue with?

**Comment by a-murphy** [comment]
The renamed project had partially deleted resources attached in Shippable that caused some problems with the rename.  We've fixed that and your account synchronization should be complete now.

**Comment by dovydasvenckus** [comment]
Thank you. You are awesome :+1:
