### ISSUE TITLE
Image versions are not being updated in task definition

### ISSUE THREAD

**Issue by cristianszz** [Shippable/support#4221]
Hi,

I am having a problem updating the version of the image in the task definition in ECR.
I have a build https://app.shippable.com/bitbucket/mxitechnologies/lp-db-migration/runs/255/1/console and it is executed without problems, deploy jobs are executed, however, whenever the deploy is executed it creates the task definition with the same image "develop.227". I removed the service, the versions of the tasks definitions and performed the entire deploy process again but always when the task definition is created, it is created with the same image.

https://app.shippable.com/bitbucket/mxitechnologies/jobs/lp-db-migration-deploy-staging-ecs/builds/5ab3aba55241fd1800e927d0/console
In the above process the deploy fails because there is no image "develop.227" since the builds are now creating the "develop.255" images.

![imagem_colada_22_03_2018_09_15-ecr](https://user-images.githubusercontent.com/37660844/37772822-2ebd66f2-2db2-11e8-8c2c-38260bad2025.jpg)

What could be happening?

Thanks!

**Comment by a-murphy** [comment]
The manifest job has `lp-db-migration-img-staging` (an image resource) as an input, which is used to specify the image in the manifest.  And no jobs currently update that image.  To update the image from your `lp-db-migration` CI job, you''ll need to add the image as an `OUT` resource for the runCI job in your shippable.yml and update the image resource with the correct tag for `versionName` in your CI job.  An example of one way to update an image from CI is [documented here](http://docs.shippable.com/ci/trigger-pipeline-jobs/).

**Comment by manishas** [comment]
@cristianszz Can you let us know if the suggestion above worked for you?

**Comment by manishas** [comment]
Closing due to lack of response.
