### ISSUE TITLE
File permissions lost on unzip

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4225]
Sorry but I've got to ask is there something in play on the build images that mean when I unzip a zip file all execute permissions are lost on scripts that are contained inside the zip?

**Comment by a-murphy** [comment]
We're not altering the behavior of `unzip` in your scripts.  Do the same `unzip` commands result in the same permissions when you run them locally?  It may be a different version of `unzip` than you are using locally, or it may be the command.

If you're still having trouble, could you let us know exactly which `unzip` commands, including options, you are using?

**Comment by andye2004** [comment]
File permissions are all set in git and then set again when building in shippable then we use the JAR command to zip it up (as you guys don't have zip installed) the zip file is then deployed to artifactory. If I download from artifactory to my mac or to any of our internal linux boxes and unzip then permissions are preserved. When I download the same zip in shippable and unzip permissions are all lost and all we are left with are files that are 400.

This isn't a massive issue for us, just a little annoying, and annoying enough for me to ask the question but we set the permissions as soon as the file is unzipped and we're good to go again.

**Comment by a-murphy** [comment]
Are you updating an existing directory with the `unzip` command?  There are options that will leave existing or unmodified files unchanged, which could explain this.  Which options or modifiers are you using with `unzip`?  And are they the same in all three cases?

**Comment by andye2004** [comment]
No options, just a straight 'unzip file.zip' command. There are no pre-existing files as the unzip is being done into the CI build directory and these files do not exist there. You could look at https://app.shippable.com/github/yambay-tech/application-config-ee/runs/120/1/console in the first command of the CI section you will see the unzip command and the resultant extraction. I could also put together a test project to demo this if you would like?

**Comment by a-murphy** [comment]
It looks like this might be a result of using `jar` to create the zip file.  Could you confirm that the zip files that are unpacked with the intended permissions were also created with `jar`?  I've tried creating zip files in Ubuntu and Centos Docker containers with both `zip` and `jar`, and it seems as though the zip files created with `zip` have the original permissions and the ones created with `jar` do not.  This may be related to https://bugs.openjdk.java.net/browse/JDK-4931799.

**Comment by andye2004** [comment]
@a-murphy Had a look at that bug report BUT if it were the cause then the permissions would be wrong everywhere. It's also a really old bug and one which I'm sure has been fixed. 

It is the EXACT SAME zip file created with the JAR command being unpacked on my mac, local linux boxes and in shippable, which is downloaded directly from Artifactory. One other subtle difference is that in shippable I'm using the Artifactory jfrog integration and locally I'm using wget. I'd be amazed if that were the cause tho. The final thing worth mentioning I suppose is that my mac and the linux boxes things are not running inside docker.

I wouldn't wast any more time on this. It's really a very simple thing to work around.
