### ISSUE TITLE
Subpar wording in job stop confirmation

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4226]
If you try to stop a job you get a confirmation dialog like this:

![image](https://user-images.githubusercontent.com/5037116/37899017-9ad6c906-30ea-11e8-9702-0a919601b3d9.png)

In this context the colors may be clear but the wording could be improved since _Cancel_ also sounds like a valid action to stop the job. Suggestion:

- Primary: _Stop job_
- Secondary: _Keep running_

This should make it clearer what each action entails.

**Comment by manishas** [comment]
@deepikasl can you add this to UI issues list?

**Comment by ric03uec** [comment]
this is fixed, stopping the job shows following message

![image](https://user-images.githubusercontent.com/1110988/47043623-0e2fa500-d15c-11e8-984d-427608abe709.png)

closing

**Comment by mbrodala** [comment]
Awesome, thanks a lot!
