### ISSUE TITLE
I could not login to shippable

### ISSUE THREAD

**Issue by vinaganti** [Shippable/support#4228]
I can't log in to shippable. I am getting the following error:

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

My bitbucket login: vinaganti@virtusa.com

**Comment by manishas** [comment]
@vinaganti I have unblocked your account. Please log out and log in again and let me know if it works. 

We have an automated algorithm that flags some accounts when they first sign in, but it does have false positives. Sorry about that.
