### ISSUE TITLE
How to trigger next job, after previous job queue is empty?

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#4232]
We have a pipeline and sometimes we have many builds in it.
I looked in shippable docs but didn't find an answer. 

I have CDjob1 -> CDjob2, right CDjob2 got triggered for every successful CDjob1.
Is there a way of waiting until all builds are done for CDjob1 and then trigger CDjob2 for the latest successful? 

Thanks.

**Comment by a-murphy** [comment]
It sounds like you might be looking for the `dependencyMode` option.  It's documented [here](http://docs.shippable.com/platform/workflow/overview/#job-triggering-mechanisms).  The `strict` `dependencyMode` option will result in `CDjob2` running fewer times if there are multiple `CDjob1` builds queued at the same time.

**Comment by depohmel** [comment]
@a-murphy, thanks, let me try this one.
