### ISSUE TITLE
Drydock version downgraded to u14: unable to change back to latest build image

### ISSUE THREAD

**Issue by wf-chris-hughes** [Shippable/support#4235]
### Description of your issue:
My build that had been working started failing due to postgres version changing:

This was due to the drydock version downgrading to U14javall from u16javall

Please let me know how I can have the build use the correct u16 image as I can't change it in the node pool.

Passed: 
https://app.shippable.com/github/WoodfordInvestmentManagement/docker-oto/runs/88/1/console
SHIPPABLE_NODE_OPERATING_SYSTEM=Ubuntu_14.04 drydock/u16javall:v5.8.2

FAILED
https://app.shippable.com/github/WoodfordInvestmentManagement/docker-oto/runs/89/1/console
SHIPPABLE_NODE_OPERATING_SYSTEM=Ubuntu_14.04 drydock/u14javall:prod

**Comment by wf-chris-hughes** [comment]
I have changed the node-pool from stable to 5.10.4 and it is now pulling the correct build image. 
you can close this ticket if you like, but should investigate why this u14 image is being pulled for stable.

**Comment by trriplejay** [comment]
Hi @wf-chris-hughes. 

despite its name, "stable" is actually a very old release, from before we used version tags.  We have since then switched to u16 default build images. v6.2.4 is the latest version.

We're working on making this more clear in the UI. Sorry for the confusion!
