### ISSUE TITLE
Invalid shipctl documentation

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4238]
The shipctl has an action `put_resource_state_multi` that is [documented](http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#put_resource_state_multi) to use positional arguments - pairs of key and value. It is not correct as shows the example there.

```
shipctl put_resource_state_multi <resource name> <key> <value> <key> <value>
-> wrong
shipctl put_resource_state_multi "vpc_settings" "HERO=SUPERMAN FOO=bar"
-> correct
```

**Comment by trriplejay** [comment]
thanks for pointing that out. we'll correct the docs.

**Comment by manishas** [comment]
This has been corrected. Closing.
