### ISSUE TITLE
Lost access to subscriptions

### ISSUE THREAD

**Issue by provstevi** [Shippable/support#4242]
### Description of your issue:

Came in to work this morning to discover I no longer have access to my subscriptions. Example:
https://app.shippable.com/subs/github/medicast/dashboard

Other members of my team are seeing this just fine, so it appears to be isolated to my account. 

I tried logging off and logging back in, still 404

Example errors I'm seeing in console:
![screen shot 2018-04-02 at 9 39 49 am](https://user-images.githubusercontent.com/19556235/38204993-d43033da-3659-11e8-9dbd-c61a8efdec29.png)

**Comment by a-murphy** [comment]
Could you try clicking on "profile" on the left and then the "sync" button?  That should synchronize your permissions with GitHub.

**Comment by provstevi** [comment]
That worked! Thank you!

**Comment by provstevi** [comment]
Closing because the suggested fix worked!
