### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4246]
Hi,

I seriously need to use the `POST /resources/{resourceId}/triggerNewBuildRequest` API with the undocumented `globalEnv` body. It is only mentioned in a [support ticket](https://github.com/Shippable/support/issues/3857#issuecomment-332343531) once. I am uncomfortable with the risk that such an undocumented feature might disappear without warning. Furthermore I will have a hard time explaining its usage to my superiors.

Is it a part of _stable_ API? If so, could you please write it to the docs? Otherwise what alternative can I use? Thank you

**Comment by trriplejay** [comment]
Hi @RadekDvorak. I dont think this setting was left out intentionally to make it "unofficial". I'll open a ticket to get that added to the docs. thanks for bringinig it to our attention again.

**Comment by RadekDvorak** [comment]
Thank you!

**Comment by a-murphy** [comment]
The `globalEnv` option has been added to the [API documentation](http://docs.shippable.com/platform/api/api-overview/#!/Projects/post_projects_projectId_newBuild).  I'll close this as resolved.
