### ISSUE TITLE
Secure env variable not set in build_ci

### ISSUE THREAD

**Issue by taqtiqa-mark** [Shippable/support#4247]
### Description
Secure env variable not set in build_ci

The secure env variable decrypts correctly to this:
````
AWS_ACCESS_KEY_ID=ABC AWS_SECRET_ACCESS_KEY=XYZ
````

**Comment by trriplejay** [comment]
Based on your build output, these variables do exist in the environment.  I see in your script that there is a still a 'sudo bash' involved here: https://github.com/taqtiqa-admin/rkt-stacks/blob/4eef7a144b09d36048865e57901c971002fc1b5e/rkt-jupyter.sh#L75

Is there a reason why you're using `| bash` versus just executing the script directly? seems like that is messing with the env scope.

also, post_ci should have the same ENVs available as CI. It's actually all part of the same script being executed. I would guess most issues you're experiencing have this `| sudo bash` at the root.

**Comment by taqtiqa-mark** [comment]
The sudo use required when a script is used in a (build) environment that does not run everything as root.  All runs OK on Travis.  I'd like to keep the scripts unchanged.  Will track this issue.

**Comment by taqtiqa-mark** [comment]
It looks like the same cause as in issue #4244 so I'll add there that secure env variable are also affected.
