### ISSUE TITLE
What is drydock/microbase?

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4248]
I've seen the Docker image `drydock/microbase` showing up on our custom build nodes. What is this image for and do we need it?

**Comment by trriplejay** [comment]
that is the default image used to run tasks in runSh jobs,  similar to how runCI has language-based build images.  It is pulled automatically when executing a task section that doesn't have a custom image specified.

**Comment by trriplejay** [comment]
In our latest runtime version, v6.3.4, this changes to `drydock/u16all` instead of `drydock/microbase`, but the idea is the same.

**Comment by mbrodala** [comment]
Thanks for clarification, so it was a good decision to remove this image. ;-) (See #3833)
