### ISSUE TITLE
Add convenience link to shippable.com to the README.md file

### ISSUE THREAD

**Issue by taqtiqa-mark** [Shippable/support#4252]
Convenience: Add link to shippable.com to the readme.md file

**Comment by a-murphy** [comment]
Do you mean the readme.md file in this support repository, or were you looking for a way to add links to the readme files in your own projects?  We have build badges designed to show that latest status on Shippable in project readme files.  The markdown is accessible by clicking on the badges option (the icon looks like a card) in the top right corner of a CI project dashboard.

**Comment by taqtiqa-mark** [comment]
Correct the readme.md file in this support repository.

**Comment by manishas** [comment]
done: https://github.com/Shippable/support/blob/master/README.md
