### ISSUE TITLE
automated build of BYON Ubuntu_16.04 fails, shipInitNode.sh downloads incorrectly

### ISSUE THREAD

**Issue by ahaiong** [Shippable/support#4253]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

So we're upgrading to Ubuntu_16.04, we've automated our build agents at the user-data/cloud-config level.

However running it from the command line fails. This is the output

root@ip-10-202-2-30:/tmp# curl -s -O https://raw.githubusercontent.com/ambarish2012/create-custom-nodes/master/register-custom-node.sh
root@ip-10-202-2-30:/tmp# chmod +x register-custom-node.sh
root@ip-10-202-2-30:/tmp# ./register-custom-node.sh REMOVING-22c3-4e6b-8f76-REMOVING 583638aafd9c101000REMOVING "$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4/) $(curl -s http://169.254.169.254/latest/meta-data/instance-id/)" 110490
Hit:1 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://ap-southeast-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Fetched 102 kB in 1s (79.6 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
jq is already the newest version (1.5+dfsg-1).
0 upgraded, 0 newly installed, 0 to remove and 174 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   461  100   189  100   272    118    170  0:00:01  0:00:01 --:--:--   170
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   187  100   187    0     0    166      0  0:00:01  0:00:01 --:--:--   166
./shipInitNode.sh: 1: ./shipInitNode.sh: {logType:verbose,methodName:clusterNodes|getInitScriptById|callerId:59e935daa0500307004d76e2|id:4005|_getInitScriptById,id:4004,message:clusterNodes GET failed for :id 4005}: not found
root@ip-10-202-2-30:/tmp#
root@ip-10-202-2-30:/tmp# cat shipInitNode.sh
{"logType":"verbose","methodName":"clusterNodes|getInitScriptById|callerId:59e935daa0500307004d76e2|id:4005|_getInitScriptById","id":4004,"message":"clusterNodes GET failed for :id 4005"}

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
since you're adding this node to a new 16.04 node pool. you'll need to change the "cluster_id" argument in this script.

You can find this ID by clicking "edit" on your 16.04 node pool, and grabbing the number out of the URL in the address bar.  This is the 4th argument to the "register-custom-node" script.

**Comment by ahaiong** [comment]
It's already there as the 4th argument. I am using 110490. I will double check if, that's correct and get back to you.

```root@ip-10-202-2-30:/tmp# ./register-custom-node.sh REMOVING-22c3-4e6b-8f76-REMOVING 583638aafd9c101000REMOVING "$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4/) $(curl -s http://169.254.169.254/latest/meta-data/instance-id/)" 110490```

**Comment by ahaiong** [comment]
How do I find out my cluster_id?

**Comment by trriplejay** [comment]
The ID has changed from what is currently in the script, because it maps to the node pool.  For your new node pool, you can find the ID by clicking "edit".  The ID will be in the resulting URL on the edit page.

**Comment by ahaiong** [comment]
Fantastic that works, just a side note which I'll raise to @ambarish2012 on that script, when using 1604, I had to wrap the following around it.

```sed -i 's/^sudo apt-get -f install jq/sudo apt-get --assume-yes install jq/' register-custom-node.sh```

I believe -f is not valid with 1604, probably best to do it in the register script.

**Comment by ambarish2012** [comment]
@ahaiong thanks for the feedback, I have fixed my script. The `-f` argument is indeed incorrect, it should be `-y`.
