### ISSUE TITLE
Docker push error in on_success not failing CI

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#4256]
In my on_success block of my CI, I do generate a docker image and push it to a repository. I notice that when an error occurred in docker, it does not fail the build. It should in this case. Anything special I should do here to have it fail on docker errors?

```
....
  on_success:
    
    # If the branch is develops, create a new production docker image with just the build artifacts, tag it and push it to the repository
    - >
      if [ "$BRANCH" == "develop" ]; then

        docker build -f $SHIPPABLE_BUILD_DIR/prod/Dockerfile  -t $IMAGE_NAME $SHIPPABLE_BUILD_DIR
        docker tag lpa-web:latest $WEB_REPO_URL:$BRANCH.$BUILD_NUMBER
        docker tag lpa-web:latest $WEB_REPO_URL:"$BRANCH.latest"
        docker push $WEB_REPO_URL:$BRANCH.$BUILD_NUMBER
        docker push $WEB_REPO_URL:"$BRANCH.latest"

        #write to the env file to update resource version and start subsequent pipeline jobs
        echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/lpa-web-img.env
      fi
.......
```

**Comment by manishas** [comment]
@Kirtap the commands in on_success do not affect the result of the build. The idea behind that section is once everything passes in your core CI workflow, you can do some non-critical things which will not affect the build.

The recommended approach for building and pushing a docker image is to put it in your `ci` or `post_ci` sections.

**Comment by Kirtap** [comment]
Thanks, will do it in the post_ci

**Comment by trriplejay** [comment]
quick correction here: a failed command in on_success does actually cause the build to fail. However when you use block notation in your yml, it changes the behavior of the commands inside that block.  A failed command inside that block will not cause the build to fail. this is true in any section of the yml.  block notation seems to override the default stop-on-failure logic.

if you instead add these commands to their own script, like `buildandpush.sh`, and then have a single yml line that says `- ./buildandpush.sh`, a failed command inside the script will cause a failure.

another option is to add your `if` condition onto every single line, which is ugly but effective.:
```sh
- if [ "$BRANCH" == "develop" ]; then docker push $WEB_REPO_URL:$BRANCH.$BUILD_NUMBER; fi
```
