### ISSUE TITLE
go build failing: cannot find package "github.com/containers/image/copy" 

### ISSUE THREAD

**Issue by taqtiqa-mark** [Shippable/support#4259]
### go build failing:
Trying to build [ProjectActomic's `skopeo`](https://github.com/projectatomic/skopeo)
````bash
go build "-buildmode=pie" -ldflags "-X main.gitCommit=28080c8d5f7ac21434948601639ab26ab7aa40bb" -gcflags "" -tags "btrfs_noversion libdm_no_deferred_remove " -o skopeo ./cmd/skopeo
cmd/skopeo/copy.go:9:2: cannot find package "github.com/containers/image/copy" in any of:
	/usr/lib/go-1.6/src/github.com/containers/image/copy (from $GOROOT)
	($GOPATH not set)
````
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/github/taqtiqa-admin/rkt-stacks/runs/55/1/console
- Scripts called from the yml (optional)
````bash
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:projectatomic/ppa 
sudo apt-get update
sudo apt-get install golang 
git clone https://github.com/projectatomic/skopeo $GOPATH/src/github.com/projectatomic/skopeo
cd $GOPATH/src/github.com/projectatomic/skopeo 
make binary-local
sudo make install
````

**Comment by trriplejay** [comment]
For Shippable to set the GOPATH, you'll have to specify `language: go` in your yml.  I suspect that is the reason for error here.

**Comment by taqtiqa-mark** [comment]
Thanks for the prompt response.
When I do that, I get the error:
`bash: line 5: go: command not found` 
https://app.shippable.com/github/taqtiqa-admin/rkt-stacks/runs/58/1/console

I've tried umpteen different ways to set the PATH, but I'm guessing because I can't find any documentation that says where go executable is located in shippable. 

Appreciate any hints, tips and incantations

````bash
go env 1s  
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root"
GORACE=""
GOROOT="/root/.gvm/gos/go1.8"
GOTOOLDIR="/root/.gvm/gos/go1.8/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build452424619=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
````

**Comment by rageshkrishna** [comment]
I see that you're doing something like `cat script.sh | sudo -E bash`. This can cause problems because we use `gvm` to manage multiple versions of go and I believe this is done by setting the PATH environment variable. Unfortunately, `sudo` will not preserve your current $PATH even with the `-E` flag.

We run all of your CI commands as the root user anyway, so unless I'm missing something you shouldn't have to use sudo at all. Just run the script directly and it should work.

I hope this helps.

**Comment by taqtiqa-mark** [comment]
Thanks for the prompt response.  OK I'm going to have to rewrite the Travis-ci.org scripts.
The `-E` advice is from #4244. Can you clarify and document script execution idioms that are consistent with shippable.  The `cat...|sudo bash` pattern worked fine in Travis so others are likely to have similar experiences. 

Maybe a documentation section on `gotchas` when porting from Travis?

**Comment by taqtiqa-mark** [comment]
I've updated #4244 to reference this issue so closing this.
