### ISSUE TITLE
windows BYON and CI on non public repos

### ISSUE THREAD

**Issue by ahaiong** [Shippable/support#4260]
Apologies if this it the wrong forum to chase this up.

I would like to do some windows stuff. However as per blog post
"http://blog.shippable.com/using-windows-containers?hs_preview=xCPDUexW-5589753000"

"We support building of public repositories on GitHub and BitBucket. Support for building private repositories is actively in development and will be available in a few weeks."

Can you confirm if this still is the case (ie no private scm for windows)

Regards

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by ambarish2012** [comment]
@ahaiong  -

1) We have added support for private windows repositories. 
2) You can also purchase on-demand Windows nodes.

I will update the blog.

**Comment by ahaiong** [comment]
Yes please, can you provide some amis and description that you're using for the ami.
```aws ec2 describe-images --owners self amazon --filters Name=platform,Values=windows```

Has too many to pinpoint.

Regards

**Comment by rageshkrishna** [comment]
Hi @ahaiong. If you are planning to use BYON, you don't need to use one of our AMIs. You can use the stock "Microsoft Windows Server 2016 Base (Microsoft Windows 2016 Datacenter edition. [English])" AMI that Amazon publishes.

At the time of writing this comment, the AMI id is `ami-ed14c790`.

**Comment by manishas** [comment]
Closing this issue since it's been answered. @ahaiong let us know if you have any other questions.
