### ISSUE TITLE
Multiple YAML files in a sync repo

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4262]
We would like to set up a number of different pipelines in our project. To create some separation between them it would be nice to split them across multiple files.

Is it possible to have multiple YAML files in one sync repository (shippable-foo.yml, shippable-bar.yml, ...)? I tried looking in the documentation, but could not find anything either way.

**Comment by oyving** [comment]
Thanks! Is anything shared between these? E.g. can I have a shippable.yml on the root directory that contains integrations and resources, and then put the jobs in different directories?

Also, feel free to make me RTFM with a URL 😃

**Comment by rageshkrishna** [comment]
Actually, everything is shared. We will merge all of YMLs we find and evaluate the resulting configuration.

**Comment by oyving** [comment]
Awesome! Thank you for your help.
