### ISSUE TITLE
Build stays in processing state from long time

### ISSUE THREAD

**Issue by ramstm** [Shippable/support#4264]
My jobs are stuck and not sure what is happening. 

https://app.shippable.com/bitbucket/repomode/jobs/shippable-pipelines_master_rSync/builds/5ace079ae19d230700562041/console

https://app.shippable.com/bitbucket/repomode/jobs/shippable-pipelines_master_rSync/builds/5ace2f24b356560700a1fcdf/console

**Comment by a-murphy** [comment]
It looks like it was related to a change in permissions that affected updates to that particular build.  I've canceled the processing build to allow the waiting one to run.  Later builds should continue to run as expected.  Let us know if you run into any more problems.

**Comment by ramstm** [comment]
Thankyou... I just tried to run and it is working now. Will get back for any further queries. 
Really appreciate the quick response!
