### ISSUE TITLE
I have error 'no password supplied' when switched to Postgres

### ISSUE THREAD

**Issue by pmatsinopoulos** [Shippable/support#427]
I just moved from MySQL to Postgres.

Now I am getting the following error:

`PG::ConnectionBad: fe_sendauth: no password supplied`

Can you please help me?

My shippable.yml file is:

```
# language setting
language: ruby

# version numbers
rvm: 2.1.1

before_script:
  - mkdir -p shippable/testresults
  - psql -c 'create database "newleveltherapy_test";' -U postgres
  - rake db:migrate RAILS_ENV=test

env:
  - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage

script:
  - rspec -f RspecJunitFormatter -o shippable/testresults/results.xml
```

Where should I apply / give the password?

What value should the password have?

**Comment by Tobur** [comment]
@J3RN hello, are your solve this problem?
