### ISSUE TITLE
install error for scikit-image using python 3.5

### ISSUE THREAD

**Issue by Borda** [Shippable/support#4272]
Hello,
I just got an error while using scikit-image for python 3.5 (somehow the same code and configuration work fine for python 3.4) and setting requirements as ` pip install scikit-image>=0.13.0`

```
Collecting scikit-image>=0.13.0 (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/64/18/402284ae09b6a2a8694e707b4924a1a9573bb4aa67923cf487978555e822/scikit_image-0.13.1-cp35-cp35m-manylinux1_x86_64.whl (35.5MB)
```

There are many errors which refer to `Your install of scikit-image appears to be broken.` as you can see in my repo and recent builds, for instance this is one of them:
```
ERROR: Failure: ImportError (/root/venv/3.5/lib/python3.5/site-packages/skimage/_shared/geometry.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_UncheckedGet
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
http://scikit-image.org/docs/stable/install.html )
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/venv/3.5/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/root/venv/3.5/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/root/venv/3.5/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/root/venv/3.5/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/root/venv/3.5/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/root/venv/3.5/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/root/src/github.com/Borda/pyBPDL/bpdl/dataset_utils.py", line 30, in <module>
    from skimage import io, draw, transform, filters
  File "/root/venv/3.5/lib/python3.5/site-packages/skimage/__init__.py", line 157, in <module>
    _raise_build_error(e)
  File "/root/venv/3.5/lib/python3.5/site-packages/skimage/__init__.py", line 138, in _raise_build_error
    %s""" % (e, msg))
ImportError: /root/venv/3.5/lib/python3.5/site-packages/skimage/_shared/geometry.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_UncheckedGet
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
http://scikit-image.org/docs/stable/install.html 
```

Any suggestion?

- Link to the build failure:
https://app.shippable.com/github/Borda/pyImSegm/runs?branchName=devel

**Comment by Borda** [comment]
Thanks for your swift suggestion, I had set `stable` option so it would be really hard for me to guess that it may also mean old version... It seems that also proposal #3873 does a similar job:
```
build:
  pre_ci_boot:
    image_tag: v5.8.2
```

**Comment by a-murphy** [comment]
The "stable" option is the oldest version.

Setting an image in `pre_ci_boot` specifies the build image that will be used with that particular YML file.  Choosing a new version in the node pool changes the default image for everything that runs in the node pool.  So, if you set an image in `pre_ci_boot` it will be used.  And if there is no image in `pre_ci_boot`, the default image with the tag matching the one selected for the node pool will be used instead.

**Comment by Borda** [comment]
I see, that is maybe a bit misleading naming stable the odes one, because from my perspective stable should be the newest one which runs fine without any complication and unstable are new in testing, as it is used in OS for computers or mobile phones... I would suggest to put there a footnote with explanation or remove the un/stable completely :)

**Comment by manishas** [comment]
We will definitely look into deprecating the "Stable" image...we call it deprecated in the docs http://docs.shippable.com/platform/runtime/machine-image/ami-stable/, but it's too subtle to make an impression.
