### ISSUE TITLE
I'm getting 404 for one of my projects

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#4274]
Hello, just suddenly i only see half of my shippable projects. 
I still have the same access as before for them via github, but shippable is returning 404, and not listing them under GitHub menu. 

I tried log out and log back in, restarting the browser and etc

**Comment by a-murphy** [comment]
Have you tried clicking the "sync" button on your account profile page?

If that doesn't work,  third-party access restrictions may have been set up on GitHub.  Could you go to https://github.com/settings/applications and click "prod-shippable"?  Your organizations should be listed there with a green checkmark or a red x.  If an organization has a red x, you should be able to either grant or request access to Shippable for that organization (depending on your permissions in the organization) from that page.

**Comment by a-murphy** [comment]
It looks the the account sync should have completed, so I'm not sure why it was still spinning.

Which organization is missing projects?  We weren't able to find anything unusual about your Shippable account and it would help to know if the projects you can't see are in a particular organization.

**Comment by manishas** [comment]
@depohmel Did this work for you?

**Comment by depohmel** [comment]
@manishas, yes it just started working.
