### ISSUE TITLE
Can't enable repo

### ISSUE THREAD

**Issue by gcoombe** [Shippable/support#4276]
When trying to enable a repo I get the following error dialog. The odd thing is that the repo in question is one that was enabled in the past (we've been deploying changes via shippable from this repo for a few months). But all of a sudden it's disabled. No one on our dev team remembers disabling it. 

The name of the rep in question is fetch-auto/fetch-lambdas

![screen shot 2018-04-19 at 10 07 04 am](https://user-images.githubusercontent.com/764083/39007058-c12c7308-43b9-11e8-8c6c-cbadf9c3d8de.png)

**Comment by trriplejay** [comment]
we're investigating.

**Comment by trriplejay** [comment]
it looks to us like the project was already enabled, as you suggested. This error seems to imply that an attempt was made to delete the project, however only certain pieces ended up being deleted. We've repaired some of the connections that were removed, and everything should be back to normal at this point.

Let me know if there's anything that doesn't seem right still.

**Comment by gcoombe** [comment]
Thanks for looking into that.  It's still showing as disabled for me and it no longer appears in my "Latest status" list.

**Comment by gcoombe** [comment]
Looks like it's back on now, thanks!

**Comment by trriplejay** [comment]
Ah, ok. it looks like a duplicate project was created somehow, and was being shown in the UI instead of the existing one. We've removed the extra and things should be back to normal now.

**Comment by gcoombe** [comment]
hmm I just tried to run a build for the first time since this issue and now it's failing due to not having permissions to talk to github.  Should I just delete the project and start again?

**Comment by a-murphy** [comment]
There's a "reset all keys" button near the bottom of the project settings page that will recreate the webhook and deploy key on GitHub.  Could you try clicking that?  It sounds like the deploy key was deleted on GitHub.

**Comment by gcoombe** [comment]
That seems to have resolved things, thanks!
