### ISSUE TITLE
New account blocked immediately on sign up

### ISSUE THREAD

**Issue by campbellbartlett** [Shippable/support#4278]
### Description of your issue:
Hi,
Today I signed up for Shippable and my account was immediately blocked.

No descriptive error message was given, but I've attached a screenshot of the error I am seeing.

I used this GitHub account to sign into Shippable.

<img width="1660" alt="screen shot 2018-04-23 at 12 41 37 pm" src="https://user-images.githubusercontent.com/38512252/39104905-e8a7e9d2-46f5-11e8-9bd8-3322b0dd55e1.png">

**Comment by manishas** [comment]
Sorry about that.... our automated algorithm blocks some new users if their account meets a set of criteria. Your account was a false positive. 

I’ve unblocked your account. Please log out and back in and everything should work as expected.

**Comment by campbellbartlett** [comment]
Working now. Thank!
