### ISSUE TITLE
runCI job gives 404 error in shippable code

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4279]
https://app.shippable.com/bitbucket/silvercurve/pixelpipe-ember-data-core/runs/215/1/console
```
reqProc|runCI|_updateNodeIdInCIJob, failed to :putJobById for jobId: 5adf04c1a74b0e0800aa5359, 404
```

**Comment by a-murphy** [comment]
This is related to #4280.  When your account was synchronized, we were unable to determine that you had more than read access to that project.  And since your account was used to run that job, it could no longer update the status of the job.

**Comment by BryanCrotaz** [comment]
do you know how it forgot that I had admin access?

**Comment by a-murphy** [comment]
The [Bitbucket status page](https://status.bitbucket.org/) reports an API outage earlier today.  It's most likely that the calls to get projects where you have write and admin access did not return any projects, but the earlier call for read-access projects did.

**Comment by BryanCrotaz** [comment]
Sounds like you need to have a ping process to watch for bitbucket to recover and then refresh all your queries. And don't treat 500 errors as an empty list.

**Comment by manishas** [comment]
Dup of #4286
