### ISSUE TITLE
Permission denied - public key

### ISSUE THREAD

**Issue by dalloro** [Shippable/support#428]
Project https://www.shippable.com/projects/53d93b760c2ad7c601cdc6a0 returns error 

Identity added: /home/minion/keys/id_53d93b760c2ad7c601cdc6a0 (/home/minion/keys/id_53d93b760c2ad7c601cdc6a0)
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Seems to be similar to https://github.com/Shippable/support/issues/157, following that resolution 
I checked (positively) that I have the correct deployment keys in the bitbucket project.

Moreover when I try to delete this project I get an error stating that the project cannot be deleted (similar to https://github.com/Shippable/support/issues/422)

**Comment by jpgarcia** [comment]
Hi @rageshkrishna I have the same Issue but I cannot find an option to remove the enabled repositories from Bitbucket. Can you help me with that?
