### ISSUE TITLE
Can't manually run jobs today

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4280]
Right clicking on job in the SPOG gives menu entry `Actions are not allowed for members`

Clicking on the job takes me to the job page which would normally have a triangular button to run the job. That's missing.

**Comment by BryanCrotaz** [comment]
@ttrahan @manishas sorry for the direct message but I urgently need to run these deploy jobs.

**Comment by BryanCrotaz** [comment]
Similarly there is no Stop button on this hung job
https://app.shippable.com/bitbucket/silvercurve/pixelpipe-ember-data-core/runs/215/1/console

**Comment by ankul-shippable** [comment]
@BryanCrotaz 
Could you try syncing your account? You can goto Account/profile page and click on the sync button.
Is this happening for all the jobs or just a particular job?

![sync](https://user-images.githubusercontent.com/16793274/39182803-abddeb8c-47db-11e8-9258-90f30a31cfe1.png)

**Comment by BryanCrotaz** [comment]
All jobs.

Seems to be that my user account is a `Member` and not an `Admin`? That's changed since yesterday and I can't see how to set the membership level for my user.

**Comment by BryanCrotaz** [comment]
Basing that assumption on the docs:
We support 3 roles -

Admin : Admins have all privileges for an organization or Project. They can enable, run and delete projects, upgrade pricing plans, and view/run, cancel, and delete builds.

Collaborator : Collaborators can enable projects and view/run builds on Shippable. They cannot delete enabled projects or upgrade pricing plans.

Member : Members have the most restricted permissions. They can view builds on Shippable.

**Comment by BryanCrotaz** [comment]
sync worked, but nothing has changed on Bitbucket for weeks

**Comment by ankul-shippable** [comment]
@BryanCrotaz We are looking into it, will get back to you in sometime.

**Comment by ankul-shippable** [comment]
@BryanCrotaz could you please send me the accountId of your bitbucket account?
You can find the accountId on the bottom right of the accountProfile page.

You can mail me the accountId at ankul@shippable.com

**Comment by ankul-shippable** [comment]
@BryanCrotaz 
Seems like you are able to run/cancel builds now.
If you are still facing any issues please let us know.
Thanks
