### ISSUE TITLE
How to add BYONs?

### ISSUE THREAD

**Issue by robmoore** [Shippable/support#4281]
From my Node Pools page, when I try to add a new node I don't have the ability to pick type -- "On Demand" is the only option. Is there something I need to select to enable this functionality? I'm on a free plan but the pricing page suggests BYON is supported for these plans.

**Comment by manishas** [comment]
@robmoore please go to the billing page and change the license to BYON. it should still show $0 for one node and you’ll then be able to switch to BYON on the node pools page.

**Comment by robmoore** [comment]
Thanks! That did the trick. IMHO, the docs could use some greater detail to this process in order to make it clear.
