### ISSUE TITLE
Can't parse a particular failed test result?

### ISSUE THREAD

**Issue by randytarampi** [Shippable/support#4282]
Shippable seems like it can't parse the results of a single failed test, and I'm a little bit confused as to why. The XML test results from running them locally on my machine and copied from a [debug build](https://app.shippable.com/github/fetch-auto/fetch-home/runs/5153/1/console) machine looked like valid XML to me, and were parseable by [`xunit-viewer`](https://www.npmjs.com/package/xunit-viewer).

It's a bit disconcerting because the failure went unnoticed for some time as the build succeeds even though the test results weren't able to be parsed. Why doesn't the `parse test reports` step keep going when it runs into a `level=fatal msg="Unable to parse XML content"` error?

Given the following builds, it seems like the test parser just doesn't like the output of the particular test case:
- https://app.shippable.com/github/fetch-auto/fetch-home/runs/5152/1/console 
  - Can't parse results for a single, particular failing test.
- https://app.shippable.com/github/fetch-auto/fetch-home/runs/5154/1/console
  - Add in another failing test and still can't parse test results.
- https://app.shippable.com/github/fetch-auto/fetch-home/runs/5155/1/console
  - I revert the commit causing the test failure in build 5152, leaving only the failure intended in 5154 and Shippable is able to parse results again.

We've run into this issue [before](https://github.com/Shippable/support/issues/3941#issuecomment-342677101), but exactly how it was solved wasn't quite clear. It's been a couple days since I've noticed the issue, so I guess we didn't get off as lucky as we did in November.

**Comment by manishas** [comment]
Closing in favor of https://github.com/Shippable/support/issues/1582 which is tracking all test results issues.
