### ISSUE TITLE
createCustomNode.js broken - interfaces changed but tool not updated?

### ISSUE THREAD

**Issue by keen99** [Shippable/support#4283]
re: 

https://github.com/shippableSamples/provision-custom-nodes

```root@shippable01:/opt/shippable-provision-custom-nodes# nodejs createCustomNode.js
Reading config.json file
creating clusterNode
Initializing ShippableAdapter with token: 63578c85-3a4c-4c86-a0b4-4ff963f1e65b
Shippable returned status 404 for request /clusterNodes
Failed to post clusterNode with error:  { logType: 'verbose',
  methodName: 'clusterNodes|post|callerId:572135560ccf0b0c00832cad|_checkInputParams',
  id: 4004,
  message: 'Missing body data :clusterId',
  statusCode: 404 }
```

we'e been using this to reinitialize our custom nodes when updates were required, but it's not working now.

**Comment by trriplejay** [comment]
thanks for pointing that out. we'll get this sample updated.

**Comment by keen99** [comment]
maybe some automated testing would be in order? 😔 (in the meantime, I'm a few nodes short of a build cluster)

**Comment by trriplejay** [comment]
@keen99 the script has been updated. let me know if you have any trouble with it.

**Comment by keen99** [comment]
looks like `Ubuntu_14.04` is no longer supported for custom nodes?  or is this just a new failure in the tool?

```
stdout: Reading config.json file
Initializing ShippableAdapter with token: ....
fetching default cluster for subscription
creating clusterNode
Shippable returned status 404 for request /clusterNodes
Failed to post clusterNode with error:  { logType: 'verbose',
  methodName: 'clusterNodes|post|callerId:....cad|_generateInitSteps',
  id: 4003,
  message: 'failed to parseScriptName for: Ubuntu_14.04_Docker_1.13.shwith error: Error: Invalid script name, cannot parse for Arch and OS',
  statusCode: 404 }

```

where is a custom node customer supposed to discover these types of changes (the API changes that initially broke this, for example)?  certainly there's no communication with us to -tell- us, instead we just have to discover them when you break them for us.

**Comment by trriplejay** [comment]
the script name format has changed, the script for 14.04 would be this:
`x86_64/Ubuntu_14.04/Docker_1.13.sh`

**Comment by keen99** [comment]
oh, I see - the format for that field changed as well.

`Ubuntu_14.04_Docker_1.13.sh` becomes `x86_64/Ubuntu_14.04/Docker_1.13.sh`

**Comment by keen99** [comment]
again, notification of breaking changes by just breaking them is PAINFUL.

**Comment by manishas** [comment]
@keen99 we’ll definitely take a look at this process and get back to you with some commitment of how we can keep customers better informed.

**Comment by keen99** [comment]
a build agent version release notification channel (emails, etc) might be a good starting point, and a place to note those types of changes.  not perfect if someone chooses to unsub (so it should be a separate mailing list than other channels, targeted to custom node customers, probably...)

**Comment by keen99** [comment]
btw, everything worked after the updates and config changes, thanks.
