### ISSUE TITLE
Modern SPOG needs to wrap project names

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4284]
Wrap on white space, hyphen and underscore
You can see below how the SPOG is meaningless without the last part of the project or resource name.

![image](https://user-images.githubusercontent.com/2016523/39221470-08f36588-482f-11e8-9c8e-728f5d229bda.png)

**Comment by manishas** [comment]
:-)

I've opened an internal issue.... should be fairly easy for job names. Resource names are trickier due to lack of real estate, but we'll see what we can do.

**Comment by BryanCrotaz** [comment]
Could resize resource blocks - plenty of real estate
![image](https://user-images.githubusercontent.com/2016523/39221743-bddf61a8-4830-11e8-89bc-91b28a0a4c4e.png)

**Comment by manishas** [comment]
We're now wrapping job names where there is already real estate. No wrapping for jobs and resources that don't already have real estate yet.... that might take a while, but the low hanging stuff is done.

We're still investigating an issue with insufficient margins for some jobs, which is being tracked by a separate issue.

**Comment by manishas** [comment]
The margins issue has been fixed, so closing this issue.
