### ISSUE TITLE
Modern SPOG should be allowed to reorder inputs

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4285]
e.g. in left column top resource and project should be moved to under the ones below

![image](https://user-images.githubusercontent.com/2016523/39221494-3e7b99d2-482f-11e8-926e-86820c4f2a5d.png)

**Comment by BryanCrotaz** [comment]
Moving top input to below input 3 would reduce line crossing

![image](https://user-images.githubusercontent.com/2016523/39221522-75bc5436-482f-11e8-9022-79b06aca2967.png)

**Comment by BryanCrotaz** [comment]
Another example - top input on top project routes to bottom input on bottom project causing more line crossing. A line-cross minimization algorithm might fix all of these.

Numbering resources 1-5 from the top, they could be reordered:
2,1,3,5,4

![image](https://user-images.githubusercontent.com/2016523/39221857-3fe64afe-4831-11e8-8375-8cdb590e557f.png)

**Comment by manishas** [comment]
@BryanCrotaz We're trying to minimize these crossed paths with modern SPOG, but reordering by the user isn't on the roadmap. Closing this issue, please let me know if I misunderstood the suggestion....

**Comment by BryanCrotaz** [comment]
I meant that the layout renderer should be allowed to reorder nodes in order to reduce line crossing. Not that the user could do it.
