### ISSUE TITLE
Bitbucket API outage causes user rights to be lost in Shippable

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4286]
> The Bitbucket status page reports an API outage earlier today. It's most likely that the calls to get projects where you have write and admin access did not return any projects, but the earlier call for read-access projects did.

Result was that my user went from being an Admin to being a Member, i.e. with no rights.
Also meant that all job runs failed because they (for some reason) were unable to update resources. Why are automated jobs running as a human user?

Had to sync with the repo to fix. Really not at all obvious that this would be the fix for the Run button disappearing from all projects.

Shippable needs to detect this and recover when the API comes back up, or to not screw up its cached rights while the API is down.

**Comment by trriplejay** [comment]
I agree we should handle this scenario better. We're currently exploring some solutions. I can update here once we've released some kind of mitigating fix.

**Comment by manishas** [comment]
Closing in favor of https://github.com/Shippable/support/issues/3933 which is the same issue. This is approved for execution so we should have something in prod in the next 3-4 weeks.
