### ISSUE TITLE
Trying to build new image with deploy process

### ISSUE THREAD

**Issue by guruprasad85** [Shippable/support#4287]
I have configured the same. but manifest not triggered after CI build.

build:
on_success:
- echo CI Running
- export IMAGE_NAME=123.amazonaws.com/services-api
- export TAG_NAME=test-services
- sudo docker build -t $IMAGE_NAME:latest .
- sudo docker tag -f $IMAGE_NAME:latest $IMAGE_NAME:$TAG_NAME
- sudo docker push $IMAGE_NAME:$TAG_NAME
- sudo echo "versionName=$TAG_NAME" >> $JOB_STATE/test-services-api-img.env

jobs:

    name: services-api_runCI
    type: runCI
    steps:
        OUT: test-services-api-img

Build pushed to ecr. always replacing old image with new image. after CI port Manifest not starting. after CI build generate manual manifest process will work. but auto trigger issue.

If I used following code will deploy smoothly. but our project dependency not working.

build:
  on_success:
    - echo CI Running
    - export IMAGE_NAME=123.amazonaws.com/services-api
    - sudo docker build -t $IMAGE_NAME:latest .
    - sudo docker tag $IMAGE_NAME:latest $IMAGE_NAME:$BRANCH.$BUILD_NUMBER
    - sudo docker push $IMAGE_NAME:$BRANCH.$BUILD_NUMBER
    - sudo echo "versionName=$BRANCH.$BUILD_NUMBER" >> $JOB_STATE/test-services-api-img.env

Is there any problem in first settings. please help me to resolve.

**Comment by guruprasad85** [comment]
Anyone can help

**Comment by trriplejay** [comment]
In the first settings, you are using the same TAG_NAME each build, `test-services`.  Shippable will only trigger the next job if the image resource is modified in some way, but since the tag is not changing, it is not triggered.

You could include one additional line like this:
`sudo echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/test-services-api-img.env`

since build number is guaranteed to change every time, this would create a new version of your image every time even if the tag has not changed. Then your manifest will be triggered each time.

One extra step will be necessary in your deploy job yml as well.  You'll need a `force: true` on your manifest IN statement, so that the deploy job knows to deploy even if the image name/tag hasn't chnaged.  That should look something like this:
```yml
- name: myDeploy
  type: deploy
  steps:
    - IN: myCluster
    - IN: myManifest
      force: true
```

give that a try and let me know if you have more questions!

**Comment by guruprasad85** [comment]
nice, i have one more issue on the same. "services-api_runCI" i have called "test-services-api-img" 
"after build i have added 4 mode images eg: test1-services-api-img,test2-services-api-img... this images have different dependencies. if i done any changes in " test1-services-api-img" project deployment should start automatically.

**Comment by trriplejay** [comment]
are you saying that you want any change to `test1-services-api-img` to cause a deployment for all images? or are you saying that that same runCI job might build/push each image separately, and you want each image to trigger its own deployment separately?

**Comment by guruprasad85** [comment]
jobs:
  - name: test-services-api_runCI
    type: runCI
    steps:
      - OUT: test-services-api-img

  - name: test-services-api-man
    type: manifest
    steps:
      - IN: test-services-api-img
      - IN: test-services-docker-opts
        applyTo:
          - test-services-api-img
      - IN: test-postagger-api-img
      - IN: test-postagger-docker-opts
        applyTo:
          - test-postagger-api-img
      - IN: test-grader-api-img
      - IN: test-grader-docker-opts
        applyTo:
          - test-grader-api-img
      - TASK: managed
    flags:
      - test-services-api

  - name: test-services-dev-api-ecs-deploy
    type: deploy
    steps:
      - IN: test-services-api-man
      - IN: test-clu
      - IN: test-services-dev-awslogs-docker-opts
      - IN: test-services-api-params
        applyTo:
          - test-services-api-img
      - TASK: managed
        deployMethod: replace

**Comment by guruprasad85** [comment]
in this case if i have done any changes in "test-postagger-api-img" docker image then how to trigger automatically.

**Comment by guruprasad85** [comment]
one more thing i noticed . after build number update. every build will downloaded in ec2. eg.123.amazonaws.com/services-api:120,123.amazonaws.com/services-api:121...

**Comment by trriplejay** [comment]
if you use buildNumber as the image tag, then it will push each tag separately.  You can use your static tag `test-services` if you want, and just include build number in the echo to help it automatically trigger subsequent jobs.

If you want image `test-postagger-api-img` to also trigger automatically, then you should also add it as an OUT step in your runCI, and it has its own `.env` file that you can append to:
```
echo "versionName=test-services" >> $JOB_STATE/test-postagger-api-img.env
echo "buildNumber=$BUILD_NUMBER" >> $JOB_STATE/test-postagger-api-img.env
```

is `test-postagger-api-img` created in the same CI job or a different one?

**Comment by manishas** [comment]
Closing this issue since the question has been answered. @guruprasad85 let us know if you have any other questions or need help with config.
