### ISSUE TITLE
Login Issue due to "violating the security policy" even tho the github account is new

### ISSUE THREAD

**Issue by MattinSayed** [Shippable/support#4289]
why is that some of my friends who just created a guthub/bitbucket account get the error above? Github even gave shippable all the needed rights.

Help us pls

**Comment by shrivara** [comment]
We have an automated algorithm that flags some accounts when they first sign in, but it does have false positives. Could you give the user name of accounts that are affected, I'll unblock them for you.

**Comment by MattinSayed** [comment]
Hey there, thank you for the fast answer
There are two accounts now and maybe some more to come, but lets not hope so xD
MattinSayed (BitBucket)
LisaZankel (GitHuB)
Sorry for the late answer ^^
Thanks!

**Comment by shrivara** [comment]
These are unblocked now. Let us know if you have any problems.
