### ISSUE TITLE
Lost access to my company's dashboard on Shippable.

### ISSUE THREAD

**Issue by thigm85** [Shippable/support#4291]
I have lost access to my company's Github organization on Shippable. This has happened out of the blue. Any indication why or what other information I need to provide?

**Comment by trriplejay** [comment]
I've re-synced your account and it looks like you've regained access to at least 1 subscription.  Can you check and see if everything looks ok now?

**Comment by thigm85** [comment]
Thanks. It works now. What was the issue?
