### ISSUE TITLE
Docker Registry Integration Error

### ISSUE THREAD

**Issue by tkcranny** [Shippable/support#4292]
### Description of your issue:

After upgrading our Node-Pool to use Ubuntu 16.04, jobs immediately fail due to the Docker-Registry integration crashing due to bad arguments.

This is the integration in the `shippable.yml`:

```yaml
integrations:
  hub:
    - integrationName: docker-hub
      type: dockerRegistryLogin
```

Jobs (including the main repository's CI run) fail quickly due to the `hub_login` stage failing:

<img width="823" alt="screen shot 2018-04-26 at 9 10 17 am" src="https://user-images.githubusercontent.com/4208581/39277805-0952ad0e-4933-11e8-81f4-9406cd9b544e.png">

This is the same output given when a malformed `docker login` command is made using a local docker version:

<img width="249" alt="screen shot 2018-04-26 at 9 13 20 am" src="https://user-images.githubusercontent.com/4208581/39277862-52381c0c-4933-11e8-8b6d-6cda0eaeae24.png">

Prior to the upgrade the integration had been working for several months. Any assistance as to why this is happening would be greatly appreciated.

- **Build failure**: https://app.shippable.com/github/BespokeInsights/westeros/runs/1147

**Comment by manishas** [comment]
@kamikai when was your docker hub integration created? You might have to recreate the integration following instructions here: http://docs.shippable.com/platform/integration/dockerRegistryLogin/

**Comment by tkcranny** [comment]
@manishas We created a new Docker Hub integration after the error occurred, with a different Docker Hub account, and still received the same error: https://app.shippable.com/github/BespokeInsights/westeros/runs/1148

**Comment by manishas** [comment]
@trriplejay can we take a look at this?

**Comment by trriplejay** [comment]
investigating

**Comment by trriplejay** [comment]
@kamikai this is a bug. we've opened an internal issue to address this.  We will prioritize this for our next release.

in the meantime, there are 2 potential workarounds:
1. switch back to 14.04
2. remove your docker integration, and instead use a `key/value pair` integration with your docker hub credentials, then manually perform the login as part of your script.

let me know if you have any questions! sorry for the inconvenience.

**Comment by manishas** [comment]
@kamikai next release will be middle of next week, FYI. Sorry about this!

**Comment by tkcranny** [comment]
I see, thank you for the speedy response. We originally switched away from 14 due to issues with presumably outdated TLS-SNI support (i.e. https requests were failing from Python), so the Key-Value pair sounds like the convenient way to go for now. Thanks again for tracking this down.

**Comment by a-murphy** [comment]
The `hub_login` error was fixed in the latest release.  Let us know if you still have trouble with the Ubuntu 16.04 nodes.
