### ISSUE TITLE
"Modern" SPOG Rendering Error [Safari]

### ISSUE THREAD

**Issue by tkcranny** [Shippable/support#4293]
### Description of your issue:
On Safari (version 11.1, macOS 10.13), the opt-in "modern" version of the SPOG does not have sufficient padding for the content of the job/resource boxes:

<img width="1336" alt="screen shot 2018-04-26 at 2 56 20 pm" src="https://user-images.githubusercontent.com/4208581/39286810-3be75398-4963-11e8-892d-1c0a41d9955d.png">

**Comment by manishas** [comment]
@kamikai We're fixing this in our next release which will be in the middle of next week.

**Comment by manishas** [comment]
We have fixed this issue in our latest release last week. The margins should be adequate now.
