### ISSUE TITLE
SPOG view makes it difficult to right-click

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4295]
When you are in the SPOG view for your pipelines there is a pop-up to show details for a given box that gets in the way when you try to right-click the box. This is more of a UI annoyance than an actual issue. But I thought you would like to know when UI annoys 😃

**Comment by trriplejay** [comment]
thanks for the tip! we're looking into improving this.

**Comment by manishas** [comment]
This will be addressed in the next release.

**Comment by a-murphy** [comment]
There should no longer be a popup when hovering over a box in the SPOG.  Let us know if you still have any trouble with this.
