### ISSUE TITLE
Chromedriver 2.38

### ISSUE THREAD

**Issue by SrDiro** [Shippable/support#4296]
### Description of your issue: Chromedriver 2.38
Chrome version on docker img of shippable is not compatible with latest version of Chromedriver (2.38).

Error:
[13:59:44]  E/launcher - session not created exception: Chrome version must be >= 65.0.3325.0
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 3.13.0-143-generic x86_64) (WARNING: The server did not provide any stacktrace information)

**Comment by a-murphy** [comment]
Could you include either a link to the run that failed with this error, the project ID from the bottom right corner of that page, or the name of the Shippable image that you are using?  If you're using an older image, you may just need to update to a newer one.  Directions to change the default images used in a node pool are available [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).  We don't automatically change the default image used once a project is enabled to keep builds predictable.

**Comment by SrDiro** [comment]
Thanks for your for answer!
I'm using the 6.3.4 version on Shippable

**Comment by a-murphy** [comment]
The next images released are currently planned to have Chrome 66 (and Chromedriver 2.38), which is listed as supported by Chromedriver 2.38.  Although not yet released, these images should be available later this week and we'll update this issue when they are.

**Comment by SrDiro** [comment]
Okey nice, I'm updating chrome version on every deyploment to run protractor correctly. 

page of the discussion and solution:
https://discuss.circleci.com/t/session-not-created-exception-chrome-version-must-be-62-0-3202-0/19258

**Comment by a-murphy** [comment]
The [v6.4.4](http://docs.shippable.com/platform/runtime/machine-image/ami-v644/) images are now available (Chrome version 66, Chromium 65, and Chromedriver 2.38).  Directions to switch default images for the node pool(s) in your subscription are [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).  If you've specified the image in your `pre_ci_boot` section, you'll also need to update the image tag there to use the latest images.

**Comment by manishas** [comment]
Closing this since the new Chromedriver is available.

**Comment by SrDiro** [comment]
Thanks to both for the support! 👍
