### ISSUE TITLE
image version reset in task definition

### ISSUE THREAD

**Issue by ahaiong** [Shippable/support#4299]
From one task definition defintion 23 to 24, the image used has been reset from 42 to 1. Please see output. Need to figure out why this is the case.

Link to build 24
https://app.shippable.com/github/bauerxcelmedia/jobs/trialteam-site-sit-deploy-master/builds/5ad69a6f5bc21c0600adc0f1/console

Link to build 23
https://app.shippable.com/github/bauerxcelmedia/jobs/trialteam-site-sit-deploy-master/builds/5ad68732b5dd7d0700c2fab4/console

Task definition for 24

```     
"image": "317367993082.dkr.ecr.ap-southeast-2.amazonaws.com/trialteam-site:master.1",
      "disableNetworking": null,
      "healthCheck": null,
      "essential": true,
      "links": [],
      "hostname": null,
      "extraHosts": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "privileged": true,
      "name": "trialteam-site-img-master"
    }
  ],
  "placementConstraints": [],
  "memory": null,
  "taskRoleArn": null,
  "compatibilities": [
    "EC2"
  ],
  "taskDefinitionArn": "arn:aws:ecs:ap-southeast-2:042311513972:task-definition/trialteam-site-sit-deploy-master-trialteam-site-man-master:24",
  "family": "trialteam-site-sit-deploy-master-trialteam-site-man-master",
```

Task definition for 23
```      
"image": "317367993082.dkr.ecr.ap-southeast-2.amazonaws.com/trialteam-site:master.42",
      "disableNetworking": null,
      "healthCheck": null,
      "essential": true,
      "links": [],
      "hostname": null,
      "extraHosts": null,
      "user": null,
      "readonlyRootFilesystem": null,
      "dockerLabels": null,
      "privileged": true,
      "name": "trialteam-site-img-master"
    }
  ],
  "placementConstraints": [],
  "memory": null,
  "taskRoleArn": null,
  "compatibilities": [
    "EC2"
  ],
  "taskDefinitionArn": "arn:aws:ecs:ap-southeast-2:042311513972:task-definition/trialteam-site-sit-deploy-master-trialteam-site-man-master:23",
  "family": "trialteam-site-sit-deploy-master-trialteam-site-man-master",```


### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
it looks like your versionName is being defined as `$BRANCH.$BUILD_NUMBER`, and the build number of the runCI job that produced the latest version of that image is 1, so the resulting tag is `master.1`.  If someone disabled and re-enabled this runCI, its build number would have been reset to 1.  Or if the image was being produced by a different job before, and is now an OUT on this job, the buildNumber would be starting over, thus the image tag would be starting over.

You can see in the runCI job that `master.1` is also the image that was pushed, so even though it looks like it deployed an old verison, `master.1` is actually the latest version that was created in that runCI job.
