### ISSUE TITLE
Connecting from Shippable to Amazon Aurora instance without opening access to all IP addresses

### ISSUE THREAD

**Issue by attiam-blueoak** [Shippable/support#4300]
We would like to test our code against an Amazon Aurora instance and wanted to see if there is a way we can connected our test code running on a Shippable CI build to one of our Aurora instances without opening connectivity to our DB from all IP addresses. Is there a recommended/best practice way of achieving this connectivity? 

To ensure minimal latency, in which region should our DB instance be located? We would like to be as close as possible to the region in which the CI instance are executing.

**Comment by trriplejay** [comment]
currently we are not able to share a specific range of IPs for whitelisting purposes.  One option would be to utilize the BYON feature where you attach your own build nodes to Shippable.  This would allow you to have control over the IPs, and help keep them fairly static.

**Comment by attiam-blueoak** [comment]
Hello @trriplejay thanks for getting back to me. In regards to connecting a CI instance to Amazon Aurora instance do you have a recommendation of achieving this? 

If you cannot share the IP addresses for white listing is fine but can you recommend in which region would be closest to the CI instances when executed? We would like this to reduce latency as much as possible between the CI environment and DB.

**Comment by trriplejay** [comment]
The region used for CI is us-east-1.  I'll investigate your other question and get back to you soon.

**Comment by trriplejay** [comment]
One potential workaround is to use a [secure encrypted variable](http://docs.shippable.com/ci/push-to-s3/) to set an aws key and secret for use with the awscli.

At the start of CI, you can get the current public IP address with a command like this: `curl http://169.254.169.254/latest/meta-data/public-ipv4` (got this from aws docs).  

Then you can use the built in awscli to add that IP to the inbound rules.  I'm not sure the exact syntax for that, but could look it up if this method sounds useful to you.

Then at the end of your CI you remove that IP from the rules.
