### ISSUE TITLE
Accounts mistakenly blocked in violation of security policy

### ISSUE THREAD

**Issue by tikul** [Shippable/support#4305]
### Description of your issue:
Two other interns and I have recently joined our company's Bitbucket team. When we try to sign in to Shippable using our Bitbucket accounts, we receive the following error: "Your account has been blocked as it was identified to be violating our security policy. Please contact support if you feel this is a mistake".
Could the following three accounts please be whitelisted:
oluwatobi.adewoye@raventelemetry.com
anqi.wu@raventelemetry.com
francisco.trindade@raventelemetry.com

Thanks

**Comment by trriplejay** [comment]
The first two have been unblocked, the third one does not appear to have logged in to shippable yet.

**Comment by manishas** [comment]
CLosing this issue. @tikul let us know if any other accounts need to be unblocked.
