### ISSUE TITLE
Frustrating Console Output

### ISSUE THREAD

**Issue by tkcranny** [Shippable/support#4307]
# Frustrating Console Output

Easily the most unpleasant feature of debugging a Shippable configuration is trying to understand the console output of a CI run or other (RunSh) Job. By this  I mean the contents of the `shippable.yml` seem to be partially and irregularly intermixed with console output, and a lot of work has to go in to tracing which command's produce which output.

I assume there's logic behind it, but it's always complex and frustrating enough to really make changing the Shippable configuration painful and tedious, just because observing what happened during the build takes more effort than it could and should.

## Example 1

From `shippable.yml`, the snippet of the main CI build:

<img width="785" alt="screen shot 2018-05-02 at 9 19 27 am" src="https://user-images.githubusercontent.com/4208581/39499011-e0ad6a18-4dee-11e8-8303-ba52dcb3099f.png">

Produces the output in the Shippable console of:

<img width="1331" alt="screen shot 2018-05-02 at 9 19 01 am" src="https://user-images.githubusercontent.com/4208581/39499018-ebe84970-4dee-11e8-88a9-96455d04f586.png">

This one is somewhat clear, though the repeated output at the bottom seems arbitrary and requires more tracing and reorientation to figure out where the real commands and their output actually occur.

## Example 2

From the `shippable.yml` snippet, following the last one:

<img width="521" alt="screen shot 2018-05-02 at 9 07 37 am" src="https://user-images.githubusercontent.com/4208581/39499090-4f229040-4def-11e8-8737-c165f3abec16.png">

Produces the output:

<img width="684" alt="screen shot 2018-05-02 at 9 08 37 am" src="https://user-images.githubusercontent.com/4208581/39499094-5534d3bc-4def-11e8-99c0-f2eec273d4e3.png">

Again, some fairly simple lines of bash produce a partially duplicated, out of order log that hampers the ability to simply read through the build and see what happened clearly (particularly when no highlighting as in the screenshots has been applied…).

---

An often frustrating experience is tracking down a particularly tricky step, only to realise it's just the duplicated configuration file being echoed out for another time in a place you don't expect, and that it doesn't actually have the data or results in it you were expecting, and having to do it all over again when you find the similar actual output somewhere else.

## Solution / Plea for Help

I don't know why the configuration file has to have its contents repeatedly printed after the output of its commands has been shown, but I would really appreciate a better mechanism to separate in the log:
- What comes **from yaml**
- What goes **into Bash**
- What comes **out of Bash**

If anything could be done, perhaps with colours for stdin/stdout+stderr, putting them in separate places, or even writing out before each section what output to expect, it would greatly enhance the experience and quality of using Shippable.

---

- **Relevant Build**: https://app.shippable.com/github/BespokeInsights/westeros/runs/1224/1/console

**Comment by trriplejay** [comment]
Correct me if i'm wrong, but all your examples are the results of yml block notation, right? I definitely think there's a bug in how we handle that. I'll open an internal request to look into that. For the most part, with single-line commands, it should be that the title is "from yml" while the "out of bash" is supposed to be what you get when you expand the command.

for example a simple one-line echo statement should look like this:
![image](https://user-images.githubusercontent.com/6869398/40246401-80be01a8-5a7d-11e8-8dde-d896545ed1a6.png)

thanks for pointing this out!

**Comment by tkcranny** [comment]
That's right, the bulk of the commands, including the two examples, are given in yaml block notation.

**Comment by manishas** [comment]
This should have been fixed with the latest release. Please reopen if you still see this.
