### ISSUE TITLE
location of gitrepo cloned in runsh changed - how to find?

### ISSUE THREAD

**Issue by larsonmpdx** [Shippable/support#4308]
### Description of your issue:
earlier this year I was successfully looking in /var/lib/shippable/build/IN/{resource_name}/gitRepo

now the location has changed to /var/lib/shippable/**{UUID}**/build/IN/{resource_name}/gitRepo and my scripts have started failing

what's the correct way to switch to this folder during the runsh script?

**Comment by manishas** [comment]
The safest way is to use the shipctl utility documented here- http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/

shipctl get_resource_state “in gitRepo name” will give you the path where the repo is cloned. Can you try that and let me know?

**Comment by larsonmpdx** [comment]
yes, that fixes things.  thank you!
