### ISSUE TITLE
The sample project is not being built on my dashboard. The message that comes up is "Merge pull request #6 from a-murphy/master Change mocha-junit-reporter version."

### ISSUE THREAD

**Issue by WaliKhan181** [Shippable/support#4309]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by WaliKhan181** [comment]
https://app.shippable.com/github/WaliKhan181/basic-node/dashboard

**Comment by a-murphy** [comment]
That message is the commit message of the latest commit in the repository.  It looks like the project has been built four times this morning; clicking a job number in either the "latest status" or "history" panel will display the build.  Could you explain what you expected to see?
