### ISSUE TITLE
Make project/build status links shorter and human readable

### ISSUE THREAD

**Issue by yihui** [Shippable/support#431]
e.g. compare the badge URL's:
- Shippable: https://api.shippable.com/projects/53fa5b48c9a91cb5066f8468/badge/master
- Travis CI: https://travis-ci.org/yihui/formatR.svg

I strongly prefer Travis CI URL's (username/repo instead of a long hash string).

**Comment by avinci** [comment]
I know this one has been long standing one. We have cleaned up our REST api end points and now we can implement this. We will get this implemented in the next release next week for whoever is still watching this....

Sorry it took this long to get to this.

**Comment by himanshu0503** [comment]
This is now live.
