### ISSUE TITLE
Help setting up testing pipeline

### ISSUE THREAD

**Issue by khskrede** [Shippable/support#4312]
Hi,

I'm trying to set up a pipeline to build docker images, deploy them, test them, and if tests pass tag them for release.

I currently have a runCI job that builds the images and has two 'image out resources' that are then deployed.

The runCI job currently also has a gitRepo out resource that replicates the ciRepo resource. The gitRepo resource is an in to the runSh job that is supposed to run the integration tests.

I am having a problem with the gitRepo resource triggering the runSh job, even when I have tried to disable all the webhooks. I want this to only be triggered after the runCI has completed successfully.

After this I also need the runSh job to download the images (or in some way copy them from the runCI job), tag them, and upload them to docker hub.

Is this a sensible workflow to run on shippable? Do you have suggestions on improving it, or at least a suggestion on how to make this work?

**Comment by trriplejay** [comment]
based on your pipeline, i'd recommend adding the `switch: off` option to your final gitRepo IN statement:
```yml
- IN: myRepo
  switch: off
```
this will ensure that the repo does not trigger the runSh job.

I do notice that there will be a chance for a timing problem here. Lets say 1 commit happens to the repo, CI runs, updates the gitRepo, then in the middle of your pipeline another commit comes in.  By the time your first commit gets to the last job, the gitRepo will be references the latest commit, and so the commit that the final runSh job runs with will be different from the commit that originally kicked off the pipeline flow.  Does that make sense? 

is it important to your scenario that the commit shas match? or are you just using the gitRepo at the end as a source for some other test script?  If this mismatch/timing issue seems unimportant then i'd say that it looks like you're doing everything right, and you should just add that `switch: off`.

**Comment by khskrede** [comment]
The timing issue here is important.

I was thinking of adding a replicated gitrepo resource between each step of the pipeline, but would prefer not to. Is there another option?

**Comment by khskrede** [comment]
I tried putting a gitrepo between each job to get rid of the timing issue. But now realize there are more issues. I need to make sure that one job will never run until after it's following jobs have completed. I.e. that the deploy job will not be run again until after the following RunIntegrationTests job has been run.

Any suggestions on achieving this?

**Comment by khskrede** [comment]
We ended up having to implement everything with a number of hacks in a single runCI job.

**Comment by provCristianMaluenda** [comment]
@khskrede How did you do for your integration test? I am facing the same issue.
