### ISSUE TITLE
Remove 30 second delay in postgres shutdown?

### ISSUE THREAD

**Issue by immerrr** [Shippable/support#4315]
One of our projects under CI has ~10 matrix builds, each using postgres, each spending 30 seconds at shutdown for no evident reason. The build image contains this gem in the postgres shutdown section:
```
printf "\n"
sleep 30 #why sleep before stopping
(kill -9 $(pgrep -f postgresql)) &
echo "service postgresql killed"
printf "\n\n"
```

So it's losing ~5mins of build time (albeit spread across 4 nodes) each time the project is tested. Given how ubiquitous postgres is these days, I'd say that contributes to a lot of computer time spent on just one line of shell script across all users of your build images.

**Comment by trriplejay** [comment]
thanks for pointing this out. we'll take a look at our script and see if we can remove that delay.

**Comment by manishas** [comment]
This will be fixed in the next release.

**Comment by manishas** [comment]
This should be fixed now. Closing.
