### ISSUE TITLE
Account is blocked

### ISSUE THREAD

**Issue by Chris2358** [Shippable/support#4316]
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake. 

Please unblock my account.

Kind regards

**Comment by manishas** [comment]
@Chris2358 I have unblocked your account. Sorry for the inconvenience,.... our automated algorithm flags a small number of accounts but there are some false positives.

**Comment by manishas** [comment]
Please log out and log in again and everything should work as expected.
