### ISSUE TITLE
How to add BYONs? Cannot change from On Demand to BYON

### ISSUE THREAD

**Issue by bvdv25** [Shippable/support#4318]
Steps te reproduce:
- Deleted default_node_pool just in case.
- Go to Subscriptions > Billing > Edit plan.
- Cannot actually change plan, have to 'Add new SKU' BYON, then remove 'On Demand' line and have to uncheck 'unlimited private repo builds' to bring total back to $0.
- During this entire proces Save button is disabled. Even when total is more than $0 and button says 'Upgrade' it remains disabled. I have a card linked.

This is on a bitbucket subscription. Is this maybe a permissions issue?

**Comment by trriplejay** [comment]
This may be a bug on our side, we're investigating.  In order to change billing you should have admin privileges in the organization.

**Comment by bvdv25** [comment]
This was indeed an issue with admin privileges in the organization. The admin was able to do this! Thx!

FYI: We had to add a credit card to continue, even though the grand total was still 0. So this might still be a bug. Anyways, the initial issue is fixed!
