### ISSUE TITLE
Copy github repo from runCI job

### ISSUE THREAD

**Issue by khskrede** [Shippable/support#4319]
I have a job that takes a runCI as an IN dependency. I would like to copy an entire github repo from the runCI job. How can I achieve this?

I would like to not use a gitrepo resource between the jobs if possible...

**Comment by trriplejay** [comment]
The other option is to copy your source code into the `$JOB_STATE` directory.  If you do this, then your next job can access the runCI state directory and see all the source  However, this we only allow a max of 1 MB total for that state directory, so depending on your repo size, this may be difficult to utilize.  

You can try to make sure you only copy the source code itself, (no .git or npm modules, etc) and maybe use some compression.  Would this work for you?

**Comment by trriplejay** [comment]
another option is to just pass the commit sha from job to job, and then at the last stage when you need the source, you can use a gitRepo and just do a `git checkout` in your script.
