### ISSUE TITLE
Kubernetes: container name

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4320]
Hello,

I have a multi image manifest in my pipeline. Is there any way to specify container name in kubernetes pod? Currently container names are prefixed by manifest name and numerically indexed - ie. `cargo-devel-app-manifest-2`. I would love to be able to override this by something more meaningful. Could you give me some advice, please?

**Comment by trriplejay** [comment]
unfortunately we don't have a way to override this today. We do have an option for naming the 'deployment' object, but not the individual container.  i'll add this as a feature request.

**Comment by Bekt** [comment]
Currently, container logs are written in the following format [0]:

```
/var/log/containers/<pod_name>_<pod_namespace>_<container_name>-<container_id>.log
```

For log collection and aggregation purposes, we are using the `container_name` part of the filename to tag each log event. This gives us an ability to query by that static property in Stackdriver/Elasticsearch/etc and set up appropriate metrics or alarms.

Not being able to specify the static container name limits us. Can you think of any workarounds?

--
[0] https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-cri-logging.md

**Comment by RadekDvorak** [comment]
Is there any update on this? I have recently added a container to a pod and our monitoring got broken as the containers' names changed.

**Comment by trriplejay** [comment]
it's still in our backlog, but we've not made any plans as far as the timeline. I'll see if I can get it prioritized since it's still causing you problems.
