### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by wrenaud** [Shippable/support#4321]
This account is blocked with the following message, and I'm not able to log in. Please unblock if possible.

"Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

**Comment by a-murphy** [comment]
Your account appears to have already been unblocked.  Could you confirm that the account you used to open this issue is the same one that saw this message and that you still see the account blocked message when logging in?

**Comment by wrenaud** [comment]
Seems to have been unblocked since I posted that. Thanks for the response!
