### ISSUE TITLE
Bump version strategy according git branch

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4325]
I would like to have two bump strategies according my two deployed branches:

- patch bump for dev branch
- minor bump for master branch.

I could create two release jobs with the two strategies but I cannot see how to configure the workflow to choose which release job to trigger.

Is it possible to do such workflow?
Thanks for your help

**Comment by trriplejay** [comment]
If you had two resources between the branch job and the release jobs, you could control which release job is triggered by only updating 1 of the 2 resources, based on the branch.  This would only trigger the release job that used that particular resource as an IN.

Alternatively, we're planning to release a new function in our `shipctl` tool that will allow you to perform semantic version changes without the need for a release job.  This new function will be available next release, currently planned for next week.  If your only reason for the release job is to increment these numbers, then I'd consider waiting for this new feature. An example command would look something like `shipctl bump_version v1.0.0 patch`.  This would allow you to manipulate the number directly in your branch-based job, and take appropriate followup actions.

**Comment by BotellaA** [comment]
Thank you for your answer. 
I think I will wait for the next release which looks great!
