### ISSUE TITLE
Gitlab subscription plan

### ISSUE THREAD

**Issue by jagedn** [Shippable/support#4326]
### Gitlab with multiple groups
I've created a subscription for my Gitlab server where I have different projects into different groups and want to use BYON nodes in all of them

Do i need to create a billing account in each of them ?

**Comment by a-murphy** [comment]
Each GitLab group is mapped to a subscription in Shippable, which will have separate billing.  So you will have to go to each billing page to switch to BYON.  However, the credit cards you add to billing belong to your account, so you should be able to just select the same card on the other subscriptions.

**Comment by jagedn** [comment]
thnks
