### ISSUE TITLE
Use cliConfig for kubectl in runCi job

### ISSUE THREAD

**Issue by khskrede** [Shippable/support#4327]
Hi,

how can I configure shippable to use a cliConfig resource in a runCi job?

I need to set up kubectl

**Comment by trriplejay** [comment]
unfortunately cliConfig functionality is not available in runCI, but the azure CLI is still present there.  You'll have to manually use your integrations values to configure the CLI and authorize with your cluster.

If you already have the cliConfig as an IN, you should be able to access the associated integration values as described here: http://docs.shippable.com/platform/integration/azure-keys/#default-environment-variables
