### ISSUE TITLE
Unable to use "az aks" in runCI job

### ISSUE THREAD

**Issue by khskrede** [Shippable/support#4328]
> az aks get-credentials --resource-group *** --name ***  
> ERROR: az: error: argument _command_package: invalid choice: aks
> usage: az [-h] [--output {json,tsv,table,jsonc}] [--verbose] [--debug]
>           [--query JMESPATH]

**Comment by trriplejay** [comment]
It looks like you're currently on runtime version 5.8.2.  This has a version of the azure CLI that did not include AKS.  I'd recommend updating your runtime version to at least 6.1.4 (6.4.4 is the latest).  You can see info on what is included in the different versions here: http://docs.shippable.com/platform/runtime/machine-image/ami-v644/

You can update your runtime version by going to your subscription dashboard -> settings -> node pools -> click edit, then select a different runtime version from the dropdown.

**Comment by khskrede** [comment]
Updated the image. Thanks.
