### ISSUE TITLE
Cannot Upgrade Plan (Failed to update Braintree subscription)

### ISSUE THREAD

**Issue by hezronobuchele** [Shippable/support#4336]
### Description of your issue:

I tried to upgrade my plan and got an error message `Failed to update Braintree subscription`.

After I refreshed the page, I can no longer edit the plan as the plan section has now changed to this:

<img width="1397" alt="screen shot 2018-05-11 at 20 49 39" src="https://user-images.githubusercontent.com/1781724/39939059-acf2d1c4-555d-11e8-847f-940cfe7f253b.png">

**Comment by trriplejay** [comment]
could you provide a link to your subscription, or the subscription id from the bottom of the page?

**Comment by hezronobuchele** [comment]
Subscription Id: 588763863b653a0f00fb5661

**Comment by trriplejay** [comment]
looks like we ran into some kind of error processing the card. we will follow up with the billing email provided for the subscription.

How many nodes were you trying to add to your subscription?

**Comment by hezronobuchele** [comment]
I was trying to change my plan from 2 nodes to 4

**Comment by trriplejay** [comment]
we've granted 2 additional nodes to your subscription for a total of 4 until we can get this sorted out. sorry for the trouble!

note: you'll have to edit your node pool to increase the limit to utilize the 2 extra nodes

**Comment by hezronobuchele** [comment]
Thanks 👍

**Comment by hezronobuchele** [comment]
Ping, the billing migration message is still there. When will this be resolved?

**Comment by manishas** [comment]
@hezbucho I expect this will be resolved next week. We'll provide an update in a couple of days.

**Comment by manishas** [comment]
@hezbucho I have emailed the billing contact on your Subscription with resolution steps. Can you let me know if it was received and we can resolve on the email thread.
