### ISSUE TITLE
Using Bitbucket pages

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4338]
I would like to use Shippable with the [Bitbucket pages](https://confluence.atlassian.com/bitbucket/publishing-a-website-on-bitbucket-cloud-221449776.html). I have to name the repository using "XXX.bitbucket.io".

I would like to add a rSync job to this repo. It seems it is not possible.

Do you have an idea to add the job?

**Comment by trriplejay** [comment]
we don't allow `.` in the resource name, but you are able to customize the name of the sync repo/job when adding it in the UI, so you can just remove the `.` or replace them with `_` or `-`.  This will still store the real repo name internally and use that name for the rSync process.

if this is a newly created repo, and you can't even see it in the list, then you'll have to sync your account from the profile page first.

**Comment by BotellaA** [comment]
Great! I thought I could not change the name.
Thanks
