### ISSUE TITLE
Build failure  at login into docker hub or pulling images

### ISSUE THREAD

**Issue by iUwej** [Shippable/support#4339]
<img width="1248" alt="screen shot 2018-05-15 at 4 21 51 pm" src="https://user-images.githubusercontent.com/2762025/40059789-b3ecfb14-585d-11e8-891a-18e4370ea89d.png">
Our builds are failing at this stage or at times while pulling the docker images. Is there an issue connecting to docker hub?. Kindly advise

**Comment by trriplejay** [comment]
It looks like this could be related to an AWS networking issue from earlier today.  That should be resolved now. Are you still seeing errors when pulling images?

**Comment by iUwej** [comment]
@trriplejay thanks for the reply. No more docker hub errors are being reported

**Comment by trriplejay** [comment]
great! glad it's working again.
