### ISSUE TITLE
JFrog Docker not working

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4343]
We are trying to use the JFrog CLI command to push a docker image into our corporate docker registry hosted in Artifactory and it's failing due to authentication issues. The error message is "unknown: Authentication is required" all other deployments are working.

Thanks, Andy.

**Comment by manishas** [comment]
@andye2004 which integration type are you using for this? You’ll need to use the dockerRegistryLogin integration to push a docker image to Jfrog.

**Comment by andye2004** [comment]
Hi @manishas, actually tried this with the Artifactory integration client. Assumed that as we were using the jfrog cli that's what it would be. Just so I understand you completely. Are you saying we cannot use the jfrog cli and that we can only use standard docker commands? (even though jfrog cli supports this AND we are trying to upload to Artifactlry)

**Comment by trriplejay** [comment]
Hi @andye2004 

Based on the [artifactory documentation](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildingDockerImages), you'll still need to authenticate directly with the registry via docker login (which is what the `dockerRegistryLogin` integration is for) before you can use a command like `jfrog rt docker-push`.  So I think in this case I'd recommend using both integrations.

**Comment by andye2004** [comment]
Thanks @trriplejay and @manishas
