### ISSUE TITLE
 Cannot add runCI job - rsync

### ISSUE THREAD

**Issue by bklevels** [Shippable/support#4344]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:
I am experiencing the follow error when I attempt to add the pipeline for the sample app deployment:
  - Cannot add runCI job, please enable the project before adding job: deploy1-ecs-basic_runCI

- Link to the build failure

- Scripts called from the yml (optional)
shippable.yml
# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

# # use this to control what branches get built.
# # http://docs.shippable.com/ci/advancedOptions/branches/
# branches:
#   only:
#     - master

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - ECR_REPO=513783555580.dkr.ecr.us-west-2.amazonaws.com/deploy1-ecs-basic

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - shippable_retry npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - pushd $TESTS_LOC_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    - popd

  push:
    #- aws ecr get-login --no-include-email --region us-west-2
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker push $ECR_REPO:$BRANCH.$BUILD_NUMBER ; fi'
    
  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker build -t $ECR_REPO:$BRANCH.$BUILD_NUMBER .; fi'
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then shipctl post_resource_state deploy1-ecs-basic-image versionName $BRANCH.$BUILD_NUMBER; fi'

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:
  # adding awsKeys integration so that credentials are available to CI Job
  # http://docs.shippable.com/platform/integration/aws-keys/
  hub:
    - integrationName: AWS
      type: amazonKeys
      region: us-west-2
      agent_only: true

resources:
  - name: deploy1-ecs-basic-image
    type: image
    integration: AWS
    pointer:
      sourceName: "513783555580.dkr.ecr.us-west-2.amazonaws.com/deploy1-ecs-basic"
    seed:
      versionName: "latest"

  - name: deploy1-ecs-basic-params
    type: params
    version:
      params:
        PORT: 80
        ENVIRONMENT: "dev"

  - name: deploy1-ecs-basic-docker-options
    type: dockerOptions
    versionTemplate:
      linuxParameters:
        initProcessEnabled: true
      memory: 100
      portMappings:
        - 80:80

  - name: deploy1-ecs-basic-replicas
    type: replicas
    version:
      count: 1

  - name: deploy1-ecs-basic-ecs-cluster
    type: cluster
    integration: dr-aws
    pointer:
      sourceName : "deploy1-ecs-basic" #name of the cluster to which we are deploying
      region: "us-west-2"

jobs:
  - name: deploy1-ecs-basic_runCI
    type: runCI
    steps:
      - OUT: deploy1-ecs-basic-image

  - name: deploy1-ecs-basic-manifest
    type: manifest
    steps:
     - IN: deploy1-ecs-basic-image
     - IN: deploy1-ecs-basic-docker-options
     - IN: deploy1-ecs-basic-params
     - IN: deploy1-ecs-basic-replicas

  - name: deploy1-ecs-basic-deploy
    type: deploy
    steps:
      - IN: deploy1-ecs-basic-manifest
      - IN: deploy1-ecs-basic-ecs-cluster
      - TASK: managed
        deployMethod: replace

**Comment by trriplejay** [comment]
can you verify that your project named `deploy1-ecs-basic` is enabled for CI? 

http://docs.shippable.com/ci/enable-project/

this step is required in order to add a runCI type job to your jobs list.

**Comment by bklevels** [comment]
Actually, my project was named something else. I figured this was the issue and deleted the project and started again. Thanks for the quick response!
