### ISSUE TITLE
Builds are running sequentially, despite having parallel builds on

### ISSUE THREAD

**Issue by hunt3ri** [Shippable/support#4349]
On repo

https://app.shippable.com/github/thinkWhere/themapcloud-portal/dashboard

If I create a PR the PR branch THEN the merged branch run one after teh other, rather than both at the same time.  This has been happening for the last week or so.

**Comment by trriplejay** [comment]
Hi,

It looks like your node pool only had one of your two nodes allocated. I've increased it to two so that both of your nodes should be utilized now as expected.

**Comment by hunt3ri** [comment]
Thanks for the super quick fix, can confirm builds running in parallel again 💯
