### ISSUE TITLE
The IN jobs are not triggered

### ISSUE THREAD

**Issue by cristianszz** [Shippable/support#4350]
Hi, we have an e2e tests that are triggered after the deploy in our test environment, but, a few days ago the triggers are no longer running:

We have an deploy job called "le-web-deploy-new-test-ecs" and after this job is executed, it should trigger the execution of the CI "le-e2e_runCI" (the le-web-deploy-new-test-ecs is configured in step of le-e2e_runCI in the IN section.

<img width="1489" alt="le-shippable" src="https://user-images.githubusercontent.com/37660844/40385435-8e125002-5dd4-11e8-9eca-c27b0d905d93.png">

What's happening? Did we stop setting something up?

**Comment by a-murphy** [comment]
By default, jobs will not be triggered if an input to that job has failed, and other inputs to your runCI job have failed.  If you would like the runCI job to be triggered with failed inputs, you can add `dependencyMode: immediate` ([documented here](http://docs.shippable.com/platform/workflow/job/runci/#yml-definition)) to the job in the `jobs` section of your YML file.

**Comment by cristianszz** [comment]
Many thanks @a-murphy I'll try put the `dependencyMode: immediate` in the jobs.
