### ISSUE TITLE
Cannot increase the number of nodes on shippable

### ISSUE THREAD

**Issue by ankur--bhatia** [Shippable/support#4352]
### Description of your issue:
NOTE: We want to increase the number of nodes so that we can more number of builds in parallel.
<img width="909" alt="screen shot 2018-05-23 at 10 39 25" src="https://user-images.githubusercontent.com/907087/40416619-9f8fab80-5e75-11e8-8d8f-8270017cef46.png">

Please increase it to 5.

**Comment by ankur--bhatia** [comment]
@shrivara @pquentin @avdrav @mkirank @ric03uec  can you help

**Comment by manishas** [comment]
@ankur--bhatia I will follow up with you over email about this issue. In the meantime, I have asked the team to grant you 5 minions while we sort this out.

**Comment by manishas** [comment]
@ankur--bhatia I have sent an email to the billing email for your subscription with instructions on how your billing page can be restored. Let me know if they don't get it or if you need me to send a copy to another email address.

**Comment by manishas** [comment]
@ankur--bhatia I have not yet heard back from your team on this. Can you please address the underlying issue as soon as possible?

**Comment by manishas** [comment]
This has been resolved. You should be unblocked from upgrading your subscription.
