### ISSUE TITLE
Logging into shippable I immediately get an Error

### ISSUE THREAD

**Issue by provBenKnoechel** [Shippable/support#4353]
Right now, when I log into shippable with my github account I immediately get an error and I am unable to continue to login to access the app. The alert says that my account has been blocked but I don't know why that would occur.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by provBenKnoechel** [comment]
Am able to get in now, thanks.
