### ISSUE TITLE
Cannot login to Shippabel using BitBucket account

### ISSUE THREAD

**Issue by kacper-synerise** [Shippable/support#4354]
I cannot log in to Shippable using BitBucket account. The error I get is 
"An error occured, please choose an action.
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

I'm using my company account : kacper.reutt@synerise.com and this is blocking my current work.

Thanks,
    Kacper

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
