### ISSUE TITLE
Add Re-Initialize to node pool list actions

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4356]
It would be useful to have _Re-Initialize_ as another action next to _Edit_ and _Delete_ in the list of nodes in the node pool view. This way updating nodes requires a few clicks less.

(I'd even argue that the _Delete_ action should be moved to the node detail view instead to require *more* steps for this a) rare and b) destructive action.)

**Comment by manishas** [comment]
@deepikasl suggestion for node pool list page.

**Comment by a-murphy** [comment]
A re-initialize button has been added to the node pools page, allowing custom nodes to be re-initialized on both the page for that node and on the node pool page listing all the nodes in a pool.

**Comment by mbrodala** [comment]
Yeah, I'm using it all the time now, thanks a lot!
