### ISSUE TITLE
Duplicated deployments

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4357]
Hi,

I am struggling with kubernetes/GKE deployments from shippable. From time to time old deployments are not removed. I use the blue/green depoyment method.
See the situation after [this build](https://app.shippable.com/github/damejidlo/jobs/cargo-devel-app-deploy/builds/5b06e5ea58cd870700abd9b3/console).
```
$ kubectl get deployment 
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
auxiliaries-638254   1         1         1            1           1d
auxiliaries-640462   1         1         1            1           51m
auxiliaries-640604   1         1         1            1           56s
nginx-640462         1         1         1            1           52m
nginx-640604         1         1         1            1           1m
php-fpm-638254       1         1         1            1           1d
php-fpm-640604       1         1         1            1           2m
redis-cache-640597   1         1         1            1           4m
sqlproxy-640597      1         1         1            1           4m
``` 
I guess the initial cause may be that one of my previous deployments failed. Still I expect that even in such a situation new deployments are able to remove former deployments.

**Comment by trriplejay** [comment]
hmm. this appears to be a bug related to multi-manifest blueGreen deployment. I'll open an internal issue to address this.

typically failures are cleaned up, but there seems to be a case here where that's not happening.

**Comment by RadekDvorak** [comment]
Hello @trriplejay,

could you please let me know if there is something I can do to help with debugging? I am starting to feel a little bit uncomfortable as our production switch has been scheduled for early July.

**Comment by trriplejay** [comment]
Hi @RadekDvorak,

We are aware of the problem, and are working on a fix. I'm not sure yet when it will be available. 

A workaround for now would be to split your deploy job into 2 separate jobs, and use one manifest IN per deploy job.  The issue is related to having 2 manifests as INs, when one succeeds and the other fails.

**Comment by manishas** [comment]
@RadekDvorak did John's suggested approach work for you? I want to make sure we're not blocking you.

**Comment by RadekDvorak** [comment]
I am sorry for the late reply as I was on holiday.

Actually the answer was not much relevant for us. Each new job adds some delay as it bootstraps the machine or it has to compete for a spare machine. Splitting deployment jobs would require twice the number of jobs in our case. Even then, in order to have the cluster consistent we would need to monitor deployments for errors and rollback the part that succeeded. Monitoring the current behaviour is more or less the same amount of work.
