### ISSUE TITLE
Downstream job triggered twice from `runCI` job

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4359]
I have a `runCI` job that has an `OUT` resource. There is a downstream job that has both of these as `IN`, but the `runCI` is marked with `switch: off`.

Despite this the job is still triggered by both the resource and the `runCI` job. What can be done to remedy this?

Also - how can I stop downstream jobs of `runCI` from being triggered by pull requests?

**Comment by trriplejay** [comment]
hmm... it looks like you've got it configured correctly. is there any pattern to when the runCI job triggers it? or does it just seem to occasionally happen?

for gitRepos that are replicated, the `replicateOnPullRequest: false` option should prevent the repo from getting updated, and therefore prevent the downstream jobs from triggering.

**Comment by manishas** [comment]
@oyving do you still need help with this?

**Comment by manishas** [comment]
CLosing due to lack of response
