### ISSUE TITLE
Billing page had been in migration state for very long

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#4362]
If i go to our billing page it mentions the following:

_Your billing account is being migrated. The billing page will be restored once this migration is complete. Please contact support if you have any concerns with billing during this time._

This had been like this for ages now. Could you check what is wrong?

https://app.shippable.com/subs/bitbucket/swisnl/billingV2

**Comment by bbrala** [comment]
This seems to be the same issue as #4352

**Comment by manishas** [comment]
@bbrala I’ll follow up with you over email about this issue. Did you want to adjust your plan?

**Comment by bbrala** [comment]
I was going to check out the caching options sometime in the near future, so this issue was getting more relevant :)

**Comment by pmezard** [comment]
Hello, we have the same issue here. Subscription id is 547c792bd46935d5fbbf0b11, could you look into it ?

Thanks.

**Comment by bbrala** [comment]
Fixed for me, thanks. :)
