### ISSUE TITLE
Different pull request hooks settings for different branches

### ISSUE THREAD

**Issue by clippermadness** [Shippable/support#4364]
Enhancement request:

We'd like to be able to run pull request builds only on certain branches (with certain patterns), and not on the rest. We're looking to mirror our branch permissions settings from bitbucket: where production and release branches require pull requests with approvals, but other branches don't.

**Comment by trriplejay** [comment]
The yml does have an optional `branches` section where you can use wildcards to specify a branch pattern, documented here: http://docs.shippable.com/ci/specify-branches/#specifying-which-branches-you-want-to-build

are you asking for more granularity? like the branch restriction would be limited to PRs while commits can run for all branches?

**Comment by clippermadness** [comment]
Yes - I'm looking for more granularity just as you describe.

Is there a way for the shippable.yml itself to skip a build, or for the first step in the ci: section to just return success on a condition?

**Comment by trriplejay** [comment]
You can skip a build by including [`[skip ci]`](http://docs.shippable.com/ci/skip-builds/) in the commit message.

I don't think there's a way to return early while having the build end in success status, but we do provide some environment variables that you could use in conditional statements throughout your build, like `IS_PULL_REQUEST`, or `BRANCH`.

All included variables are documented here: http://docs.shippable.com/ci/env-vars/

**Comment by manishas** [comment]
@clippermadness I am closing this issue since the question was answered, but please let us know if you have any follow up questions, or if you couldn't get the workflow you needed and have a feature request.
