### ISSUE TITLE
"No subscriptions found for subscriptionId(s):" error upon loading main page

### ISSUE THREAD

**Issue by nastete-skytap** [Shippable/support#4366]
### Description of your issue:
Hi, I just created a new Shippable account and haven't set up any projects yet. In the left sidebar on app.shippable.com, I don't see any subscriptions button. If I click the "Integrations" button, I see a message saying "No subscriptions found for subscriptionId(s):" If I then click the plus button to add an account integration, I'm redirected to a 404 page.

Also, when I load app.shippable.com, several of the HTTP responses have 404 response codes. The response body for these errors looks like the following:
```{"logType":"verbose","methodName":"/subscriptions|GET|callerId:5b0750fcdc428306008f95d6|validateSubscriptions|_computeShim","id":4004,"message":"No subscriptions found for subscriptionId(s): "}```

As far as I can tell, I'm completely blocked from doing anything useful in Shippable.

See attached screenshot.

![subscriptions error](https://user-images.githubusercontent.com/39311210/40679756-e757309c-6338-11e8-86eb-676bb8c9c1fc.png)

**Comment by a-murphy** [comment]
It doesn't look like we were able to find any GitHub repositories for your account when it was synchronized.  Do you have any repositories on GitHub?  If so, could you click the "profile" option in the left sidebar and then the sync button to re-synchronize?

**Comment by nastete-skytap** [comment]
Thanks, this fixed it.
