### ISSUE TITLE
sendMail Unit Tests failing only on Shippable...

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4369]
Hi, 

We have a number of unit tests to send mail via smtp.mandrillapp.com:587 using the NPM package nodemailer. 

These tests all work when running locally or using the images that are built as a part of our Shippable CI process, but the tests fail when running on Shippable itself. 

Is there a firewall in place that is preventing us from connecting to Mandrill? 

Debug output from nodeMailer seems to indicate that it is unable to reach the host.

![screen shot 2018-06-01 at 2 43 10 pm](https://user-images.githubusercontent.com/1018189/40857778-2cebbbe6-65aa-11e8-86e5-705263786ea3.png)

**Comment by trriplejay** [comment]
it looks like our cloud provider for dynamic nodes prevents outgoing traffic to port 587.  Is it possible for you to configure mandrill to use port 2525 instead? this appears to be an option supported by mandrill.

Alternatively you could set up custom nodes on a provider that doesn't limit this.

**Comment by ryan-kimber** [comment]
Thanks John, I was working on exactly that when you posted your comment. Fingers crossed.

**Comment by ryan-kimber** [comment]
That worked. Thanks!
