### ISSUE TITLE
Dashboard showing build for master of original repo and forked repo

### ISSUE THREAD

**Issue by wing328** [Shippable/support#4370]
### Description of your issue:

https://app.shippable.com/github/OpenAPITools/openapi-generator/runs?branchName=master shows not only the build status for master of `OpenAPITools/openapi-generator` but also the build status for the fork which happens to make the change in the master (e.g. https://github.com/OpenAPITools/openapi-generator/pull/196)

Should https://app.shippable.com/github/OpenAPITools/openapi-generator/runs?branchName=master only shows the builds for `OpenAPITools/openapi-generator/` only but not the forked repo?

Now the [shippable badge](https://github.com/OpenAPITools/openapi-generator#openapi-generator) (3rd one from the left) is showing error while the build for master of `OpenAPITools/openapi-generator/` is fine according to https://app.shippable.com/github/OpenAPITools/openapi-generator/runs?branchName=master

**Comment by a-murphy** [comment]
The page with the list of all runs for a particular branch includes commits to that branch and pull requests opened to the branch.  The commits will have this symbol next to the branch name:
![screenshot from 2018-06-04 09 04 28](https://user-images.githubusercontent.com/5492015/40928551-a33e81ec-67d6-11e8-8ce7-033063abda0b.png)
And the pull requests will have this one:
![screenshot from 2018-06-04 09 04 44](https://user-images.githubusercontent.com/5492015/40928572-af0b7688-67d6-11e8-9792-e52494611cf0.png)

The pull request builds are not, however, used to determine which badge to show.  Badges will only show the status of the most recent commit build (manual or webhook).

The project dashboard (the page with all branches in the project) and subscription dashboard (the page will all enabled projects in the subscription) pages do not show pull request builds for the latest build by default.  They can be configured in the project settings to include pull request builds.  Pull request builds can also be disabled entirely in the project settings if you would rather not run them.

**Comment by wing328** [comment]
Thanks for the reply. For the badge, is there a way to only show the master build result (not the forked build)?

**Comment by a-murphy** [comment]
For a build badge that shows the status for the latest commit on the master branch, click the badges option in the top right of the project dashboard, then select "master" in the branches dropdown.  The markdown or image URL can then be copied, depending on how you plan to use it.  The build badge will not show the results of pull request builds or the status of any fork of the repository.
