### ISSUE TITLE
Billing stuck in "Your billing account is being migrated"

### ISSUE THREAD

**Issue by pmezard** [Shippable/support#4371]
Hello,

The "Billing" page of subscription 547c792bd46935d5fbbf0b11 is stuck in "Your billing account is being migrated". Shippable plan cannot be edited either. Is there any way to fix this ?

Thanks,

**Comment by manishas** [comment]
@pmezard I'll reach out to you over email with details on this issue.

**Comment by pmezard** [comment]
The billing account page now displays "An issue has been identified with your billing account. Please contact support". @manishas, I do not know if you tried to reach us using the "Billing Contact(s)" but I noticed by I would not receive emails to the previous address so I updated it, adding mine to the previous one. I you did reach us, would you mine resending the technical details to my address ?

Thank you.

**Comment by pmezard** [comment]
Thank you, the billing account got unstuck and I was able to change plan settings. I am closing the ticket.
