### ISSUE TITLE
Job name wrapping issues

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4373]
Job names with underscores don't read well.

Suggest wrapping on white space, hyphen, dot and underscore.

<img width="311" alt="screen shot 2018-06-05 at 17 12 56" src="https://user-images.githubusercontent.com/2016523/40988887-25abacd2-68e4-11e8-8522-8b69272c6452.png">

**Comment by BryanCrotaz** [comment]
Resources have same issue

**Comment by a-murphy** [comment]
Name wrapping has been updated since this issue was opened.  Further changes to how job names are displayed on the SPOG can be followed in #4525.
