### ISSUE TITLE
Layout routing is still really weird.

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4374]
Suggest minimising line crossing in auto router.
<img width="386" alt="screen shot 2018-06-05 at 17 18 18" src="https://user-images.githubusercontent.com/2016523/40989050-8f92f056-68e4-11e8-8720-08837445b8a0.png">

**Comment by manishas** [comment]
@ChaitanyaVootla bringing this to your attention as you refine SPOG.

**Comment by manishas** [comment]
Modern SPOG has gone through a bunch of recent changes, so this should be cleaned up at this point. Closing, but please let us know if you are still running into issues and happy to take another look.
