### ISSUE TITLE
Cant login with bitbucket account

### ISSUE THREAD

**Issue by tomasz-wojcik-synerise** [Shippable/support#4375]
I'm trying to login with bitbucket account and I receive following error. Can You tell me why this happens and unlock my acount? I know some people for our office had similar issue, so we think it's either false positive with IP addess or domain name for email accounts used for bitbucket. Help please:(

```
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.
```

**Comment by manishas** [comment]
What is the username you signed in with?

**Comment by tomasz-wojcik-synerise** [comment]
I used login via bitbucket with username `synerise-tomekwojcik`.

**Comment by manishas** [comment]
@tomasz-wojcik-synerise your account has been unblocked. Please log out and log back in and everything should work as expected. We'll look into why we're getting so many false positives for your organization.

**Comment by tomasz-wojcik-synerise** [comment]
It works! Thanks a lot!

**Comment by caliagaa** [comment]
Hi i can't login either can you please help?  @manishas

**Comment by a-murphy** [comment]
@caliagaa Could you let us know the name of the account you are trying to use?

**Comment by manishas** [comment]
This has been resolved, closing.
