### ISSUE TITLE
rSync fails on deleting resources with a webhook failure

### ISSUE THREAD

**Issue by provadamscott** [Shippable/support#4376]
### Description of your issue:
We encountered this error while trying to perform an rSync
```sh
rSync encountered 3 errors while processing providenceinnovation/telehealth-CallstatsProxy: 
  - Failed to update resource: 77389, with error: deleteDeployKey Failed for WebHookId: 29199665
  - Failed to update resource: 77390, with error: deleteDeployKey Failed for WebHookId: 29199666
  - Failed to update resource: 77388, with error: deleteDeployKey Failed for WebHookId: 29199664
```
NOTE: If you are experiencing a build failure, please include:
- Link to the build failure
https://app.shippable.com/github/providenceinnovation/jobs/telehealth-CallstatsProxy_master_rSync/builds/5b1870cf20220007009ef461/console

**Comment by a-murphy** [comment]
Could you try again?  I've updated the resources so that rSync won't try to delete the old deploy keys again.

**Comment by provadamscott** [comment]
Well, I don't see the previous error anymore. But now I'm encountering this error:
```sh
rSync encountered 3 errors while processing providenceinnovation/telehealth-CallstatsProxy:
  - Failed to update resource: 77390, with error: Deploy key creation failed for :providerId 562dbd9710c5980d003b0451
  - Failed to update resource: 77389, with error: Deploy key creation failed for :providerId 562dbd9710c5980d003b0451
  - Failed to update resource: 77388, with error: Deploy key creation failed for :providerId 562dbd9710c5980d003b0451
```
Not sure if that's on our end or not.

**Comment by a-murphy** [comment]
Did you rename the GitHub repository and update the `sourceName`s of the gitRepo resources with the new name?  If so, could you delete the deploy keys for these resources on GitHub (they should be named `shippable-77390`, `shippable-77389`, and `shippable-77388`)?  I'm assuming that although we couldn't find the old deploy keys, they are actually still there and conflicting with adding new ones for the `sourceName` change.

**Comment by provadamscott** [comment]
The only deploy keys I see are `shippable-production` and `shippable-77379`. Nothing in the 80s or 90s.

**Comment by provadamscott** [comment]
Wait, they were on a different repo (one we ended up removing from Shippable. I just deleted them.

**Comment by provadamscott** [comment]
That appears to have worked. Thank you very much!

**Comment by provadamscott** [comment]
However, now our runCI is failing. Complaining about not having ssh keys.

**Comment by a-murphy** [comment]
That usually means that the CI deploy key (`shippable-production`) was deleted.  There's a "reset all keys" button near the bottom of the project settings page that will create a new one. (Navigate to the project dashboard, then click the gears in the top right to get to the project settings.)

**Comment by provadamscott** [comment]
Mind explaining further where this button is? I can't seem to find it.

**Comment by provadamscott** [comment]
Nevermind, I found it.

**Comment by provadamscott** [comment]
For some reason it's still saying it doesn't have the ssh keys.

**Comment by a-murphy** [comment]
If I identified the failing job correctly, it's not the typical error for a missing deploy key.  We're looking into it, but that error would be expected if you don't have any SSH keys set up for your GitHub account and tried to rerun the job with the "debug" option.

**Comment by provadamscott** [comment]
Now I'm getting this when I run the rSync
```sh
ssh-agent bash -c ssh-add /tmp/key.pem; git clone git@github.com:providenceinnovation/telehealth-CallstatsProxy.git /build/IN/telehealth-CallstatsProxy_master/syncRepo
Identity added: /tmp/key.pem (/tmp/key.pem)
Cloning into '/build/IN/telehealth-CallstatsProxy_master/syncRepo'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by provadamscott** [comment]
I tried resetting the keys, but it looks like the only key there is the `shippable-production` key.

**Comment by a-murphy** [comment]
There is not currently a button to reset the rSync deploy key.  I can email the public key to be added back to the repository on GitHub.

**Comment by provadamscott** [comment]
Yeah, that would be great!

**Comment by provadamscott** [comment]
The runCI is still failing with this error:
```ssh
No SSH keys found for accountId: 5b0ecc8e1a075407003e9c6d
```

**Comment by a-murphy** [comment]
As far as well can tell, it looks like you're trying to rerun the job with the [SSH debug](http://docs.shippable.com/ci/ssh-access) option.  This adds the public SSH keys from the account (synchronized with GitHub) to the node to allow SSH access.  If you don't have any SSH keys for your GitHub account, you won't be able to run with SSH because there is no way for you to access it.

You should be able to rerun without SSH.  Could you confirm if this occurs when you select "rebuild without SSH"?

**Comment by provadamscott** [comment]
The runCI succeeded when selecting "rebuild without SSH", however now our stage deploy is being denied access to our GitHub repo.

**Comment by a-murphy** [comment]
Could you confirm that the `shippable-77389` deploy key is present in the repository?  The resource object indicates that it is, but as far as we can tell it is attempting to clone the correct repository and the most likely possibility is that the key is missing or invalid.

**Comment by provadamscott** [comment]
It turns out we were missing a lot of our deployment keys. We added those back in and everything seems to be back in the state we expected. Thank you very much!

**Comment by trriplejay** [comment]
glad this is working!
