### ISSUE TITLE
Setup failing when the CI are triggered

### ISSUE THREAD

**Issue by cristianszz** [Shippable/support#4377]
Hi,

We have some e2e tests that are triggered when we do the deploys in our test environments. When the job is triggered automatically the process fails during the CI setup. When the job is manually triggered this failure doesn't happen, what could be happening?

Job: https://app.shippable.com/bitbucket/mxitechnologies/lp-e2e/runs/1794/1/console

```
Setting up dependency: lp-aircraft-deploy-test-ecs 0s  
Creating metadata file
Successfully created folder: /build/IN/lp-aircraft-deploy-test-ecs
Successfully saved file: version.json
Generating replace script
Successfully generated replace script
Validating script dependencies
the path is: /build/IN/lp-aircraft-deploy-test-ecs/replace_placeholders.sh
Successfully validated script dependencies
shippable_replace /build/IN/lp-aircraft-deploy-test-ecs/version.json
Reading version.json
Generating environment variables
Successfully added environment variables for lp-aircraft-deploy-test-ecs
Creating state directory
Successfully created folder: /build/IN/lp-aircraft-deploy-test-ecs/deploy
Getting state information
reqProc|runCI|__getStateInformation :getFilesByResourceId failed for resourceId: 46578 with error 404
```
Error: `reqProc|runCI|__getStateInformation :getFilesByResourceId failed for resourceId: 46578 with error 404`

Best regards

**Comment by trriplejay** [comment]
investigating

**Comment by trriplejay** [comment]
does this actually happen very consistently when the job is automatically triggered vs manually triggered? or does the automatic trigger sometimes work and somtimes not?

**Comment by cristianszz** [comment]
No, the build never works automatically, we always have to run manually for that it works properly.

**Comment by cristianszz** [comment]
Hi @trriplejay 
Do you have any update about this problem? Do you need me to send you any more information? Thanks

**Comment by trriplejay** [comment]
We think this might be related to permissions on the webhook build.  can you navigate to your project settings page, and under the `account used` option in webhook config, make sure the selected account is one with read/write access to the repo? Maybe try changing it to yourself, or someone who you know uses the platform regularly and has correct access?

Let me know if that makes a difference. If not we'll have to take a deeper look.

**Comment by cristianszz** [comment]
So, the webhook has yes access but the build still does not work automatically. Could you see if there is anything else blocking the build? Thanks.

**Comment by trriplejay** [comment]
ok, so it looks like that although the current builder account does have access to the CI project, they do not have access to the syncRepo, which is where the permissions to fetch state files are inherited from.

I'm opening an internal bug to address this scenario, but in the meantime, I've selected a different builder account that should have access to both items.  This should resolve your problem, and the next automatic trigger should run without this error. 

let me know if you're still seeing errors.

**Comment by cristianszz** [comment]
Hi @trriplejay sorry for the delay but thanks, everything is ok now.

**Comment by trriplejay** [comment]
awesome, glad it's working.
