### ISSUE TITLE
Billing stuck in "Failed to update Braintree subscription"

### ISSUE THREAD

**Issue by christianmoretti** [Shippable/support#4379]
Hi there,
We are trying to get more nodes into our environment, but when we try to add new nodes, we get the message: "Failed to update Braintree subscription".

Account: 592a089d85f2a2070064780b

Thanks.

**Comment by trriplejay** [comment]
Sorry for the inconvenience. We're looking into this.

**Comment by manishas** [comment]
@christianmoretti can you try upgrading again? There was a problem with the previous transaction, but it’s now resolved and you should be able to upgrade.

**Comment by christianmoretti** [comment]
Hi, @manishas thanks, now I could add more nodes. But my builds are all queued now, does it have a relationship?

<img width="1631" alt="shippable" src="https://user-images.githubusercontent.com/1626925/41176461-73e38ac2-6b2e-11e8-88f8-9d62bf75b1a6.png">

**Comment by manishas** [comment]
@trriplejay is looking into this.

**Comment by christianmoretti** [comment]
Thanks @manishas and @trriplejay all works fine :)

**Comment by trriplejay** [comment]
This was related to a backed up queue we had. the issue is resolved now.
