### ISSUE TITLE
Slow builds/UI since the update to v6.5.4

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4382]
We noticed that our build times have increased dramatically since the last update of Shippable to v6.5.4.

See for example build 3258 (`build_on_success` at 9m 9s) of project `58ab0bf60bfe57100058d7a6` compared to build 3092 (`build_on_success` at 3m 21s) which was executed by v6.5.1. In this specific case `npm install` caused a timeout.

We also noticed that the console output must have been updated (which unfortunately is not mentioned in the [release docs](https://github.com/Shippable/admiral/blob/master/releaseNotes/v6.5.4.md)) and since then the browser is getting slower and slower to a point where clicks don't do anything anymore and we can only kill the browser tab.

Can you please have a look at this?

**Comment by rageshkrishna** [comment]
Hi @mbrodala. We're looking in to this right now. I'll have an update for you very soon.

**Comment by rageshkrishna** [comment]
@mbrodala We've deployed a fix for the browser slowness.

I'll have someone get back to you on the speed difference in your builds. Did it get slower all by itself (meaning just us upgrading the service to v6.5.4), or did it get slower after you reinitialized your custom nodes to get the v6.5.4 components on your nodes?

**Comment by mbrodala** [comment]
Thanks for the quick updates. I'll have a look at the build output from time to time to see whether the slowness is gone. Right now I did indeed not notice anything like mentioned above anymore.

I'm also watching for any slow builds, but right now builds are actually faster as is to be expected with our new shiny nodes. I guess the NPM failure could also have been a network issue. I'll let you know if it shows up again.

**Comment by manishas** [comment]
Closing this, but please let us know if you run into this issue again and we'll reopen.
