### ISSUE TITLE
Build failing to remove /build/node

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4383]
Currently we are seeing random build failures with errors like this:

```
Setup
  Validating incoming message
  Getting job
  Validating CI Steps
  Validating steps order
  Validating job dependencies
  Updating node
  Parsing job properties
  Setting up build directories for job: 5b1a5a6665ee490700d9104d
Cleaning directories.
Successfully cleaned directory at path: /shippableci/onstartjobenvs
Successfully cleaned directory at path: /tmp/ssh
reqProc|runCI|__cleanDirectories, Failed to clean dir at path:/build with err: Error: EBUSY: resource busy or locked, rmdir '/build/node'
  Validating dependencies to get previous job files
Successfully validated dependencies of previous job
  Getting files of previous job
Successfully received files for previous job
  Saving files of previous job
Successfully saved files for previous job
  Setting permissions on files of previous job
Successfully set permissions for files for previous job
```

See for example build 3263 of project `58ab0bf60bfe57100058d7a6`.

Unfortunately I cannot see on which of our nodes the build was executed since the *Job node info* step comes after the *Setup* step. I've added a new node today and don't know if that one is causing issues.

**Comment by shrivara** [comment]
It looks like that the build agent managed to pick up a build just after/before the node started reinitialization. While we try to ensure no builds are queued to these nodes during reinitialization, there is still a small window in which the build agent is active and can pick up builds.

**Comment by mbrodala** [comment]
OK, thanks for the info. Since all of our new nodes are up and running now I don't expect this to happen anymore in this case. I'll let you know if it does on the next re-init.
