### ISSUE TITLE
Subscription integrations could not be loaded. Integration permissions will not be displayed.

### ISSUE THREAD

**Issue by cyrodjohn** [Shippable/support#4384]
### Description of your issue:
All of a sudden all my projects are gone and i keep getting

> Subscription integrations could not be loaded. Integration permissions will not be displayed.

**Comment by deepikasl** [comment]
Hi @cyrodjohn can you please try syncing your account?
Go to `Account Profiles`. Click on `sync` button.

**Comment by cyrodjohn** [comment]
Thanks! Why did that happen anyways?

**Comment by rageshkrishna** [comment]
Hi @cyrodjohn. We had a brief issue with our sync service this morning while we were upgrading the service. The problem has been fixed and you shouldn't have any trouble now that your account has synced again.

**Comment by cyrodjohn** [comment]
Okay got it. Thanks!
