### ISSUE TITLE
Store build cache on node

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4385]
I think it would be useful if there was an option to store Shippable's build cache on the node where it was executed instead of downloading and uploading it via S3 all the time. This can speed up build times a lot since network roundtrips are not necessary anymore.

Of course this is only useful for custom nodes (BYON) which have a lot of space.

Do you think this could be added?

**Comment by trriplejay** [comment]
it is possible to configure this behavior today for custom nodes.  The `pre_ci_boot` section allows you to add custom volume mounts.  If you create a directory on your host machine, and mount that into your container, then any files you store there will persist on your node.  Then you just need your script to copy to/from that directory.

It won't use our automated `cache: true` system, so it requires some extra scripting on your part, but that would be my suggestion to accomplish what you want.

We also just released a "cache" feature for dynamic nodes, where instead of periodically creating/destroying the build nodes, we allow them to just be paused/resumed, thus preserving any files on the node.  

Let me know if you have more questions.

**Comment by mbrodala** [comment]
Certainly an interesting idea and after some fiddling I actually got this to work which reduced my build time by almost a whole minute.

However there are quite a few disadvantages:

1. Caches are per-node thus given our 4 nodes each project would very likely have at least 4 builds without cache.
2. Following that a cache update also needs to be performed 4 times in the worst case.
3. We cannot easily drop the cache for a project on our nodes, we'd actually need to SSH into the 4 nodes and manually drop the cache.

This is why I think a solution properly integrated into Shippable would be way more useful.

**Comment by trriplejay** [comment]
yeah, those are good points.  Perhaps a way to choose between s3 and on-disk caching, with some auto-distribution across nodes built in.  I'll open a feature request to see if there's something we can do.

Regarding the 4 nodes issue... this might cause more harm than good, but you *could* split your nodes into 4 separate node pools, then have specific projects run on specific pools, thus eliminating the need for the cache to be distributed across machines.  This would make you lose the ability to have parallel builds for the same project, but separate projects would still be parallel. definitely a hack, but maybe it would work for you? (doesn't solve your 3rd point)

**Comment by mbrodala** [comment]
@trriplejay Thanks for opening the feature request.

As for your suggestion: this could work indeed but then we have a lot more work to maintain relations between our projects and node pools. Also if one single-node pool dies then, the project comes to a halt and needs manual intervention. With a multi-node pool the build simply runs on another node. So that won't really work well for us I'm afraid.

**Comment by rageshkrishna** [comment]
It sounds like what you are looking for is a synchronized peer-to-peer file store. You could use something like [SyncThing](https://syncthing.net/) to do this and place your cache files in that mounted directory. It's still entirely up to you to manage, though, but it gives you a completely local solution.

Admittedly I haven't thought it through fully, but I feel like any solution to this would necessarily need to be outside of the scope of Shippable's build runner as establishing node-to-node relationships in a BYON setting would be highly specific to each user's network.

**Comment by mbrodala** [comment]
That sounds interesting, I'll have a look.

**Comment by rageshkrishna** [comment]
@mbrodala It doesn't look like we'll be able to do this natively. The complexity of creating a local cache that is synchronized across BYON nodes is currently way out of the scope of what our build runner can do. There are so many variables in a BYON scenario that we cannot provide a solution that makes everyone happy.

I think SyncThing or some other peer-to-peer file system would be the way to go if you want to keep everything local.

I'm closing this issue now as we don't plan on doing this.

**Comment by mbrodala** [comment]
Yes, thanks for bringing up a few options how I can do this myself. 👍
