### ISSUE TITLE
Debugging CentOS 7 Node

### ISSUE THREAD

**Issue by StuporHero** [Shippable/support#4388]
I'm rerunning a build in debug mode, and the `ssh` command I received was `ssh -p 22 ubuntu@<ip>`. Naturally, that didn't work given this a CentOS 7 node and not an Ubuntu node. I tried guessing a bunch of different usernames including `ec2-user`, `centos`, and `shippable`, but none of them worked. Kindly tell me the username to use for a CentOS 7 node and update your interface to provide a working `ssh` command for nodes other than Ubuntu.

**Comment by shrivara** [comment]
This should be working now, could you give it a go and let us know? Our new CentOS 7 image was incorrectly configured for SSH access.

**Comment by StuporHero** [comment]
@shrivara Trying it now.

**Comment by StuporHero** [comment]
@shrivara Bingo! That worked. Thank you.

**Comment by bradskuse** [comment]
I am facing this exact issue currently.  I can ssh to a ubuntu build node but not a CentOS 7 build node.

The debug command is as the original poster said -> ssh -p 22 ubuntu@[ip]

Please can this be looked at again?

**Comment by shrivara** [comment]
Sorry about the trouble. This should be fixed now. Could you try again?

**Comment by bradskuse** [comment]
@shrivara just tried but got -> /home/centos/.ssh/authorized_keys 0s  
/tmp/mexec/tmp-script.sh: line 79: /home/centos/.ssh/authorized_keys: No such file or directory

on the add_ssh_key build step

**Comment by bradskuse** [comment]
@shrivara fantastic! It is now working.  Thank you for the help.
