### ISSUE TITLE
Shippable Configuration Repo not Synchronizing

### ISSUE THREAD

**Issue by ryan-kimber** [Shippable/support#4389]
Our main Shippable configuration repo (continuous-deployment_master_rSync in our formhero account) has, just this morning, stopped picking up commits to the repository. 

Other repos seem to be unaffected, but commits to this repo aren't triggering an update, and manually triggered builds don't seem to be picking up the latest code. 

Any help will be greatly appreciated. Thanks. 😁

**Comment by ryan-kimber** [comment]
Bump! Any updates on this?

**Comment by trriplejay** [comment]
@ryan-kimber looking into this now.  can you check the webhooks present on the repo? you should have one that looks something like `resources/57249/hook`

It's possible that the webhook was deleted by github if something changed in the permissions.  If the webhook is still present, can you verify that it's been sent? can you check the status? (github puts a green check or red x based on shippable's response to the hook).

**Comment by cpoll** [comment]
@trriplejay `https://api.shippable.com/resources/57249/hook` is present, and includes PR, Push and Release events. A webhook payload has been delivered for a recent commit (with 200 response), but this is not reflected in the continuous-deployment_master syncRepo resource.

It seems like this issue is now present in more than one of our repos. `continuous-deployment_master` and `managed-deployments_master` syncRepo resources are both on older versions; there are no new versions created for any git commits made today.

**Comment by ryan-kimber** [comment]
It doesn't look like there are / were any problems with the webhook registration. 

![screen shot 2018-06-11 at 1 15 16 pm](https://user-images.githubusercontent.com/1018189/41246815-2d0cb508-6d7a-11e8-9c53-fb2fb69b0494.png)

**Comment by trriplejay** [comment]
one other question... are you adding commits that actually change one or more `shippable.yml` files? syncrepo/rsync will only run if a configuration file is changed, so if you are changing some other file in the repo, rSync does not run. any chance that is the case here?

**Comment by ryan-kimber** [comment]
We deleted one shippable.yml file, and added a few that had names like shippable.\<some-description\>.yml.

**Comment by trriplejay** [comment]
when you say `<some-description>`, are you referring to resources, jobs, triggers? if you put any other custom identifier in there, it won't be recognized. though you can do `<description>.shippable.yml` and that would work.

**Comment by ryan-kimber** [comment]
Ahh. That's too bad. It would be a nice feature (vs having to have different folders). 
We've split our deployments into a number of folders but have some shared common configurations for different-sized AWS EC2 instances.

**Comment by trriplejay** [comment]
just to be clear, you can have the files in the same folder, it's just that the extra description has to come *before* the `.shippable.yml` part. so something like `dev.shippable.yml`, `staging.shippable.yml` is valid, for example.  it wont work if you instead try `shippable.dev.yml`, etc.

also `dev.shippable.jobs.yml` or `dev.shippable.resources.yml`, though in the current version of shippable, you can just use `shippable.yml` for both.

**Comment by trriplejay** [comment]
closing this. let me know if you have any other questions.
