### ISSUE TITLE
Slow builds due to cache restore

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4391]
ATM we see rather slow build cache restores taking more than 3 minutes. You can see this e.g. in build 209 of project `59c3af5636154a070093df38`.

An idea what's wrong? Could this be our build nodes' fault?

**Comment by mbrodala** [comment]
Seems like this is a [general AWS (S3) issue](http://downdetector.com/status/amazon/map/):

![image](https://user-images.githubusercontent.com/5037116/41285479-8be3c1f8-6e3c-11e8-9a04-831ac4d61342.png)

(Shippable uses `us-east-1`.)

**Comment by trriplejay** [comment]
thanks for finding that. i'm not seeing any change in status on official aws page though. i guess it's just a slowdown rather than an outage?

**Comment by mbrodala** [comment]
We still see the same issue, cache restores range from 1 to 2 minutes ATM which considerably slows down our builds.

**Comment by trriplejay** [comment]
hmm.. hard to say. we haven't made any change to our caching workflow. Has your cache size grown significantly? have you seen any improvement in the past few days? does this happen across all projects or only on that specific project you mentioned?

**Comment by mbrodala** [comment]
We haven't changed anything on our side either and it affects all of our projects AFAIS. Yesterday the restore times where a lot better already though so I'll continue monitoring this for now.

**Comment by mbrodala** [comment]
Right now we are seeing slow cache restores again, e.g. in build 3327 of project `58ab0bf60bfe57100058d7a6`. Do you see something similar in other projects ATM?

**Comment by mbrodala** [comment]
Some cache restores now take **more than 4 minutes**, e.g. build 3329 of that project. In this case it might actually be faster for us to disable the cache.

Please have a look at this and let me know if this could be an issue with our build nodes. In that case I'll ask the tech staff of our provider.

**Comment by rageshkrishna** [comment]
The cache is pulled directly from S3. Can you check if you notice any general slowness with s3 downloads from your node? Although there is no incident according to AWS, I have noticed occasional slowness from several of my own machines on DO in the last few days.

**Comment by mbrodala** [comment]
Do you have a suggestion how I could check the speed of S3 downloads from `us-east-1`? Sites like the [Amazon Web Services Network Test](https://cloudharmony.com/speedtest-for-aws:s3) obviously perform tests using my desktop location. Our build nodes are located in Dallas however.

**Comment by mbrodala** [comment]
Are you able to upload a test file (100 MB should do) to your S3 bucket and make it public? This way I could easily check the speed via `curl`.

**Comment by trriplejay** [comment]
@mbrodala I've sent you an email with a link you can use to perform some tests. Let me know when you're done with it.

**Comment by mbrodala** [comment]
Thanks for that. Here are the results based on [this `curl` call](https://coderwall.com/p/lwpszg/measuring-download-speed-from-the-command-line-with-curl):

- Node 1
  - 1st run
    ```
    time_connect: 0.035s
    time_namelookup: 0.004s
    time_pretransfer: 0.249
    time_starttransfer: 0.396s
    time_redirect: 0.000s
    time_total: 177.558s
    ```
  - 2nd run
    ```
    time_connect: 0.066s
    time_namelookup: 0.033s
    time_pretransfer: 0.308
    time_starttransfer: 0.439s
    time_redirect: 0.000s
    time_total: 103.814s
    ```
- Node 2
  - 1st run
    ```
    time_connect: 0.035s
    time_namelookup: 0.004s
    time_pretransfer: 0.377
    time_starttransfer: 0.608s
    time_redirect: 0.000s
    time_total: 127.929s
    ```
  - 2nd run
    ```
    time_connect: 0.039s
    time_namelookup: 0.005s
    time_pretransfer: 0.269
    time_starttransfer: 0.382s
    time_redirect: 0.000s
    time_total: 30.607s
    ```
- Node 3
  - 1st run
    ```
    time_connect: 0.036s
    time_namelookup: 0.004s
    time_pretransfer: 0.257
    time_starttransfer: 0.442s
    time_redirect: 0.000s
    time_total: 80.669s
    ```
  - 2nd run
    ```
    time_connect: 0.043s
    time_namelookup: 0.013s
    time_pretransfer: 0.263
    time_starttransfer: 0.341s
    time_redirect: 0.000s
    time_total: 82.511s
    ```
- Node 4
  - 1st run
    ```
    time_connect: 0.046s
    time_namelookup: 0.013s
    time_pretransfer: 0.383
    time_starttransfer: 0.511s
    time_redirect: 0.000s
    time_total: 165.365s
    ```
  - 2nd run
    ```
    time_connect: 0.072s
    time_namelookup: 0.029s
    time_pretransfer: 0.317
    time_starttransfer: 0.429s
    time_redirect: 0.000s
    time_total: 132.620s
    ```
- Desktop
  - 1st run
    ```
    time_connect: 0.125000s
    time_namelookup: 0.031000s
    time_pretransfer: 0.453000
    time_starttransfer: 0.578000s
    time_redirect: 0.000000s
    time_total: 21.281000s
    ```
  - 2nd run
    ```
    time_connect: 0.156000s
    time_namelookup: 0.062000s
    time_pretransfer: 0.469000
    time_starttransfer: 0.594000s
    time_redirect: 0.000000s
    time_total: 20.109000s
    ```

The speed varies considerably between calls but in general the download is very slow compared to my desktop. Since neither Shippable nor AWS has changed anything recently, I'll ask our node provider about this.

**Comment by mbrodala** [comment]
I just went ahead and copied the `curl` command from the build (3341) while it was running. Downloading the build cache file took 2 minutes in the build but it took only 32 seconds on my desktop.

**Comment by mbrodala** [comment]
I'm still talking about this with the node provider and let you know once we find something.

**Comment by mbrodala** [comment]
I just noticed the new insights page (`https://app.shippable.com/subs/<vcs>/<subscription>/insights`) and it seems very useful. But apparently the history only goes back 7 days, is there a way to include data older than that? That would help me pinpoint the exact time our builds started to get slow.

**Comment by trriplejay** [comment]
today we only offer the 7 day history, though we're hoping to expand that in the future.

**Comment by manishas** [comment]
@mbrodala did you get any information from your node provider? Let us know if we need to investigate.

**Comment by mbrodala** [comment]
Unfortunately not yet. I'll let you know as soon as I have anything.

**Comment by mbrodala** [comment]
Our nodes where migrated to a different location which lets our builds run a lot faster again now. The issue might be related to the fixes for Spectre/Meltdown, we'll keep going with this.

In any case this is not something Shippable should/can fix. Thanks for looking into this.

**Comment by mbrodala** [comment]
I have just set up a new node (vServer, 4 **dedicated** CPU cores, 16GB RAM, 60 GB SSD, located in Nuremberg, Germany) with a completely different provider and I see the same issue again, but this time even worse.

The `boot_container` step takes more than 6 minutes (!) to complete and hangs at downloading the `buildCache.tar.gz` from S3. (See job 3 of build 459 of project `54f05f3c5ab6cc13528f2757`) for an example:

![image](https://user-images.githubusercontent.com/5037116/53014533-0ef98000-3449-11e9-919e-80bdccb70dd4.png)

If I execute the same command in parallel while the job is running I get a completely different result:

```
# time curl -s -XGET 'https://shippable-production-<...>.s3.amazonaws.com/subscriptions/54f05f3c5ab6cc13528f2751/projects/54f05f3c5ab6cc13528f2757/buildCache.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<...>&X-Amz-Date=20190219T121123Z&X-Amz-Expires=600&X-Amz-Signature=<...>&X-Amz-SignedHeaders=host' -o 'buildCache.tar.gz'

real    0m8.158s
user    0m0.312s
sys     0m0.684s
```

So it only took 8 seconds to download this file directly on the host system. How can exactly the same download take that much longer in the build?

**Comment by mbrodala** [comment]
As far as I can see this issue is directly related to the cache size. So far we put the whole `~/.composer/cache` directory in the build cache which grows infinitely over time. On some projects we have now switched to only put the `vendor-dir` into the cache and now it's loaded in ~10 seconds which is perfectly fine.

We'll continue monitoring but this is probably resolved.
