### ISSUE TITLE
Builds timing out very frequently

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#4392]
A large number of builds for our project `55d549ca6ed0590b008bba40` have started timing out since about 4:00 AM GST yesterday. Builds that used to take 13-18 minutes before Saturday started taking 30+ minutes, starting at about 12:33 PM GST on Saturday, and steadily climbed up to 60+ minutes, when they have started timing out.

Please see build numbers `2891`, `2894`, `2895`, `2897`, `2898` and `2899` as examples.

Details for the timeouts and when the situation is expected to be restored to normal would be appreciated.

**Comment by trriplejay** [comment]
we're investigating

**Comment by trriplejay** [comment]
it looks to me like it's related to network speeds. some of the downloads in your build seem to be extremely slow. Has anything changed in the spring repository that you're using? any outage or reports of slowness in general?

**Comment by manish-in-java** [comment]
@trriplejay, can you clarify your comment about network speeds? Did that refer to the hosting environment for Shippable.com, or some other network speed?

We have not added or changed any repository that would have resulted in any increase in build times. Local builds and those on other environments are running just fine, without any problems or change in build times. Even many Shippable.com CI builds have completed without problems. For example, builds `2856`, `2858`, `2862`-`2890` have all completed fine, although they took much longer than they used to before the timeout problem cropped up. Even build `2896` finished fine yesterday, although it too nearly timed out.

Checking logs for the timed out builds also shows that they have been failing at different stages. Additionally, the last messages in the logs are clearly from the Shippable.com code, for instance:

```
Build: 2898

Successfully validated inputGenerating EmailValidating inputValidating inputSuccessfully generated EmailGenerating EmailGetting SMTP system integrationSuccessfully fetched emailsystem integrationGetting SMTP system integrationSending EmailSuccessfully sent EmailSending Email

Build: 2899

Successfully validated inputValidating inputValidating inputGenerating EmailSuccessfully generated EmailGenerating EmailGetting SMTP system integrationSuccessfully fetched emailsystem integrationGetting SMTP system integrationSending EmailSuccessfully sent EmailSending Email

Build: 2900

Validating inputSuccessfully validated inputGenerating EmailValidating inputGetting SMTP system integrationSuccessfully generated EmailGenerating EmailSuccessfully fetched emailsystem integrationGetting SMTP system integrationSending EmailSuccessfully sent EmailSending Email
```

Our application has no log messages even close to what we see here, so these are clearly neither from our application, nor from the build system Maven (as Maven as no built-in email notification mechanism, nor are we using any plugin that would offer such functionality).

**Comment by trriplejay** [comment]
it's possible that it's related to the shippable node's networking environment. we're investigating that.  

Those logs are from Shippable sending out an email notification when the build completes (in this case from timing out) so those are always at the end.  Timing out in different stages makes sense, since the build is actively running when the 1 hour mark hits, so there will be some variation in how far it gets.

**Comment by manish-in-java** [comment]
Builds have started running normally since Thursday last week. Can we assume that the problem has been resolved? Can we get some details on what caused the problem?

**Comment by shrivara** [comment]
We're still looking into why the earlier builds timed-out. We found a few tests that were taking much longer than usual resulting in the time-outs and wanted to know if this is something that is expected. Could you give me your email id or contact me at shrivara@shippable.com so I can share the details?

**Comment by shrivara** [comment]
We discussed over email that the time-outs have stopped now. @manish-in-java, please reopen if you see this again.
