### ISSUE TITLE
Cant login with bitbucket account

### ISSUE THREAD

**Issue by Shaun-Schwartz** [Shippable/support#4394]
I'm trying to login with BitBucket account and I receive following error:

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake. 

My BitBucket username is shaunschwartz

**Comment by manishas** [comment]
@Shaun-Schwartz can you log out and back in and see if everything works? I have unblocked your account.

**Comment by Shaun-Schwartz** [comment]
That worked, thank you!
