### ISSUE TITLE
Document notification triggers for notification resource better

### ISSUE THREAD

**Issue by immerrr** [Shippable/support#4395]
The official documentation for `notification` resource (http://docs.shippable.com/platform/workflow/resource/notification/) mentions

> You can send notifications upon the following events in your workflow:

with some bullet points containing keywords, but say nothing about how are they supposed to be used or have any examples. CI-related notification documentation has it written out much better:
- http://docs.shippable.com/ci/send-notifications/#2-customizing-notification-triggers
- http://docs.shippable.com/ci/slack-notifications/#2-customizing-notification-triggers
- http://docs.shippable.com/ci/email-notifications/#5-customizing-notification-triggers
and so on.

One could deduce that the configuration is the same, but it takes a while to navigate to the proper page from there.

**Comment by manishas** [comment]
We’re in process of improving docs in this area. Here is a doc that shows how to use the notification resource http://docs.shippable.com/platform/tutorial/workflow/send-job-status-notifications/

**Comment by manishas** [comment]
The docs have been updated.... closing this issue.
