### ISSUE TITLE
Problem with Billing page.

### ISSUE THREAD

**Issue by RedLucas** [Shippable/support#4397]
I don't know what to say, I'm looking in the Subscription billing page and it tells me to contact support because of a problem.

**Comment by trriplejay** [comment]
We will get in touch with the billing contact listed on your subscription billing page to get this resolved, thanks!

**Comment by manishas** [comment]
@RedLucas I have emailed the billing contact for your account. Please let me know if I should send the email to anyone else. Thanks!

**Comment by manishas** [comment]
This is now resolved. Closing.
