### ISSUE TITLE
Update Docker

### ISSUE THREAD

**Issue by StuporHero** [Shippable/support#4398]
The Docker version on the build nodes is about 1 year old. I don't know if you have a particular cadence you follow, but it's probably about time to update it. The latest stable version that I'm seeing is `18.03.1-ce`. I've got a build that is mysteriously failing on your build nodes that works just fine on my workstation, and I'd like to eliminate the docker version as the cause since I'm using the same exact container image on both.

**Comment by trriplejay** [comment]
we're in the process of adding support for this. I'm not sure of an exact timeline at the moment, but I'll mark this as a feature request, and we'll update here once the new version is available.

**Comment by StuporHero** [comment]
@trriplejay Thanks! It might not be a bad idea to make it a configurable option in the node pool so people can match their production environments if they're a little slow to update.

**Comment by trriplejay** [comment]
typically for dynamic nodes, the docker version is static for a given Shippable runtime version, and the runtime version is changeable per-nodepool. You can see the descriptions here: http://docs.shippable.com/platform/runtime/machine-image/ami-overview/

so if you still needed an older version, you could use an older runtime.

alternatively, if you use custom nodes, you can select one of the supported docker versions and it will be installed as part of the node initialization.

**Comment by StuporHero** [comment]
That makes sense. I'll bet you could build out some additional packer configs to build each new runtime version with a variety of docker versions to make that slightly more configurable. I don't really need that. I'm just offering my thoughts on what you could do to improve the product. I know how it goes, though, because I've got quite the backlog of features to implement in my own pipeline.

**Comment by manishas** [comment]
ETA for this is first week of August.

**Comment by ric03uec** [comment]
@StuporHero i apologize for not updating this earlier. This got delayed due to some other high priority issues but the team is now working on it. We'll launch this in release `v6.10.4` scheduled for last week of October.

**Comment by StuporHero** [comment]
@ric03uec Duly noted.

**Comment by nealeu** [comment]
@ric03uec v6.10.4 is now out if you want to update your node pool to give that version a spin.

**Comment by StuporHero** [comment]
@nealeu @ric03uec I gave it a try, and it didn't solve my issue, so I'll have to look elsewhere. Also, out of curiosity, I know I said at the beginning that the latest stable was `18.03.1-ce`, but that was in June. The latest stable now seems to be `18.06.1-ce`. Is there any particular reason you didn't use the latest at the time you did the upgrade?

**Comment by ric03uec** [comment]
@StuporHero sorry to hear that this is still not working for you. I'd be happy to get on a call to debug this and get your builds running on shippable. 
As for the docker version, we follow a certain cookbook for upgrading docker version. First this is rolled out as an option for BYON nodes for a select OS's, then for all, and finally the on-demand nodes. This is done to test docker for as many scenarios as possible before making this this default option for new customers. The downside is that docker might come up with new versions while the cycle is ongoing, which is what happened in this case. Hope this explains your question.
As I mentioned earlier, we can schedule a quick call to go over your scenario and fix that. I'm available at devashish at shippable dot com.

**Comment by StuporHero** [comment]
@ric03uec I'm not leaving shippable. I just mean that my problem wasn't with the docker version.
