### ISSUE TITLE
File corruption while transferring via job state

### ISSUE THREAD

**Issue by dcecile** [Shippable/support#4403]
I'm trying to transfer a 6.5K file from one job to another using job state, and it seems like it's getting corrupted in transit (`tar` fails to extract, and SHA1 hash is different between jobs).

I have this set up right now in my [tacit-lang](https://app.shippable.com/subs/github/tacit-lang/dashboard) organization, where for example [tacit_runCI job 29.1](https://app.shippable.com/github/tacit-lang/tacit/runs/29/1/console) has the hash of the file computed as `9e18e56db22518fa8d279d7f5dea738c8c247810` but then [tacit_ghPagesDeploy job 673579](https://app.shippable.com/github/tacit-lang/jobs/tacit_ghPagesDeploy/builds/5b245b09fc690f0700bcce14/console) receives the file with hash `fc704c6916e10239ade5d78e0a5a78bd8afcd6ac`.

(I also got the same problem using a state resource, and when trying to transfer a PNG file not inside at TAR archive.)

Is there a step that I missed in saving the state? Or is state not intended for this use...?

Please let me know if any additional information is needed.

Thanks,
Dan

**Comment by rageshkrishna** [comment]
Hi @dcecile. I investigated this and it looks like we have a bug where binary data is encoded incorrectly when being transferred via job state. We'll work on fixing this in the next release, but I'd like for you to not be blocked in the mean time. You can workaround this issue by base64 encoding/decoding the TAR file.

In your CI job, do this:

```yaml
    - tar cvfR ./transfer.tar gh-pages-files/
    - base64 < transfer.tar > $TRANSFER/transfer.tar.b64
```

And in you runSh job, do the opposite with:

```yaml
    - base64 -d < $TRANSFER/transfer.tar.b64 > $TRANSFER/transfer.tar
    - tar xvf $TRANSFER/transfer.tar
```

I hope this helps to unblock you. I'll update this issue as soon as we release the encoding fix in our build runner. Let me know if you have any questions.

**Comment by dcecile** [comment]
:clap: OK, thanks @rageshkrishna for looking into it. The workaround worked for me! I'll try undoing the workaround when the next version is ready.

**Comment by ankul-shippable** [comment]
@dcecile We have fixed this now, you can update the script in your shippable.yml.

Let us know if it works for you. Thanks.

**Comment by dcecile** [comment]
It worked perfectly, thanks @ankul-shippable! :+1:
