### ISSUE TITLE
Account deletion questions

### ISSUE THREAD

**Issue by jdextraze** [Shippable/support#4409]
Hi,

I am leaving my organization and need to delete my account but I am the person who created our organization. I see in the documentation that the organization will not be deleted which is great, but what about the credit card and integrations used by our organization because those also seems to be linked to an account. Will this cause issue? Is there a way to move all those to another account?

**Comment by a-murphy** [comment]
Billing:
Another admin in the subscription can update the billing to use a card linked to their account.  Directions to change credit cards are [here](http://docs.shippable.com/platform/management/subscription/billing/#changing-payment-method).

Subscription Integrations:
Another account with access to the subscription can update the subscription integrations to reference account integrations belonging to that account.  Basically, go to the subscription integrations page (under the settings gears in the top right on the subscription dashboard), click on a subscription integration, and pick an account integration.  Directions are available [here](http://docs.shippable.com/platform/management/subscription/integrations/#edit-your-subscription-integration).

**Comment by jdextraze** [comment]
Thanks, I will try this.
