### ISSUE TITLE
account blocked err 

### ISSUE THREAD

**Issue by pavannomula** [Shippable/support#4411]
### Description of your issue:
I am seeing below error when i'm trying to login using github account 

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

email : pavan.nomula@stacksports.com

**Comment by trriplejay** [comment]
you should be unblocked now. can you try logging out/in again?

**Comment by pavannomula** [comment]
It's good now . Thank you
