### ISSUE TITLE
 /usr/local/bin/phpenv-install 5.5 [Error]: Definition 5.5 not found.

### ISSUE THREAD

**Issue by mustela** [Shippable/support#4412]
Nothing has changed in our stack but we started to get 

``` 
 /usr/local/bin/phpenv-install 5.5
[Error]: Definition 5.5 not found.
``` 

Any clue?

**Comment by a-murphy** [comment]
It looks like the node pool in your subscription was updated to use `v6.1.4` images.  The [`v6.1.4` PHP image](http://docs.shippable.com/platform/runtime/machine-image/ami-v614/#php-614) does not have PHP 5.5 installed.  A list of which images have each PHP version is available [here](http://docs.shippable.com/platform/runtime/machine-image/language-versions/#php).  You can also specify a supported version and then install a different version in your script.
