### ISSUE TITLE
ci/cd is not happening when i split the build and resources/job config file

### ISSUE THREAD

**Issue by vinaganti** [Shippable/support#4413]
### Description of your issue: #ci/cd is not happening#
NOTE: If you are experiencing a build failure, please include:

**my CI(build) config file is root of the code repository and build is good as soon as code commits, but automatic deployment is not happening after build unless we  trigger a manual deployment**

#here is the build file#

language: node_js
node_js:
  - 8.11.1

branches:
  only:
    - master

env:
  global:   
    - ECR_REPO=066245240757.dkr.ecr.us-east-1.amazonaws.com/bnc-compass-frontend-repo

build:

  
  ci:
    
    #- shippable_retry yarn install   

  
  post_ci:
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker build -t $ECR_REPO:$BRANCH.$BUILD_NUMBER .; fi'    
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker push $ECR_REPO:$BRANCH.$BUILD_NUMBER ; fi'
    #- 'if [ $IS_PULL_REQUEST == "false" ] ; then echo "versionName=$BRANCH.$BUILD_NUMBER" > $JOB_STATE/deploy-ecs-frontend-image.env ; fi'
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then shipctl post_resource_state deploy-ecs-frontend-image versionName $BRANCH.$BUILD_NUMBER; fi'

integrations:
  
  hub:
    - integrationName: shippable_devops_AWS_keys
      type: amazonKeys
  
  notifications:
    - integrationName: "Slack-Integration-for-Builds"
      type: slack
      recipients:
        - "#builds-progress"
      branches:
        only:
          - master
      on_success: always
      on_failure: always
      
  ##End of file##
  

**but, my resources/jobs config file for deployment is in another common repo and i noticed that continues build is happening, but deployment has to be triggered manually and it is not happening automatically** 

#here is my deployment file

resources:
  
  - name: deploy-ecs-frontend-image
    type: image
    flags:
      - deploy-ecs-frontend
    integration: shippable_devops_AWS_keys
    pointer:
      sourceName: "066245240757.dkr.ecr.us-east-1.amazonaws.com/bnc-compass-frontend-repo"
    seed:
      versionName: "master.278"
  

  - name: deploy-ecs-frontend-dev-cluster
    type: cluster
    flags:
      - deploy-ecs-frontend
    integration: shippable_devops_AWS_keys
    pointer:
      sourceName : "compass-frontend-demo" #name of the cluster to which we are deploying
      region: "us-east-1"

  - name: deploy-ecs-frontend-qa-cluster
    type: cluster
    flags:
      - deploy-ecs-frontend
    integration: shippable_devops_AWS_keys
    pointer:
      sourceName : "BNC-QA-FRONTEND-CLUSTER" #name of the cluster to which we are deploying
      region: "us-east-1"

  - name: deploy-ecs-frontend-dev-opts
    type: dockerOptions
    flags:
      - deploy-ecs-frontend
    versionTemplate:
      linuxParameters:
        initProcessEnabled: true
      memory: 512
      portMappings:
        - 0:8080
      taskDefinition:
        taskRoleArn: "arn:aws:iam::066245240757:role/ecsTaskExecutionRole"
      logConfiguration:
        logDriver: awslogs
        options:
          awslogs-group: "/ecs/deploy-ecs-solutions-frontend-lg"
          awslogs-region: us-east-1
          awslogs-stream-prefix: dev

  - name: deploy-ecs-frontend-qa-opts
    type: dockerOptions
    flags:
      - deploy-ecs-frontend
    versionTemplate:
      linuxParameters:
        initProcessEnabled: true
      memory: 512
      portMappings:
        - 0:8080
      taskDefinition:
        taskRoleArn: "arn:aws:iam::066245240757:role/ecsTaskExecutionRole"
      logConfiguration:
        logDriver: awslogs
        options:
          awslogs-group: "BNC-QA-ECS-FRONTEND-CW-LG"
          awslogs-region: us-east-1
          awslogs-stream-prefix: qa

  - name: deploy-ecs-frontend-dev-params
    type: params
    flags:
      - deploy-ecs-frontend
    version:
      params:
        PORT: 8080
        ENVIRONMENT: "dev"

  - name: deploy-ecs-frontend-qa-params
    type: params
    flags:
      - deploy-ecs-frontend
    version:
      params:
        PORT: 8080
        ENVIRONMENT: "qa"

  - name: deploy-ecs-frontend-dev-replicas
    type: replicas
    flags:
      - deploy-ecs-frontend
    version:
      count: 1

  - name: deploy-ecs-frontend-qa-replicas
    type: replicas
    flags:
      - deploy-ecs-frontend
    version:
      count: 1

  - name: deploy-ecs-frontend-dev-alb
    type: loadBalancer
    flags:
      - deploy-ecs-frontend
    pointer:
      sourceName: arn:aws:elasticloadbalancing:us-east-1:066245240757:targetgroup/frontend/0067b0c0cf6f1c2c
      method: application
      role: "arn:aws:iam::066245240757:role/ecsServiceRole"

  - name: deploy-ecs-frontend-qa-alb
    type: loadBalancer
    flags:
      - deploy-ecs-frontend
    pointer:
      sourceName: arn:aws:elasticloadbalancing:us-east-1:066245240757:targetgroup/frontend-qa-alb-target/53d1e82dddbda563
      method: application
      role: "arn:aws:iam::066245240757:role/ecsServiceRole"

jobs:

  - name: compass_frontend_runCI
    type: runCI
    flags:
      - deploy-ecs-frontend
    steps:
      - OUT: deploy-ecs-frontend-image

  - name: deploy-ecs-frontend-manifest-1
    type: manifest
    flags:
      - deploy-ecs-frontend
    steps:      
      - IN: deploy-ecs-frontend-image
  
  - name: deploy-ecs-frontend-dev-deploy
    type: deploy
    method: upgrade
    flags:
      - deploy-ecs-frontend
    steps:
      - IN: deploy-ecs-frontend-dev-opts
      - IN: deploy-ecs-frontend-dev-replicas
      - IN: deploy-ecs-frontend-dev-params
      - IN: deploy-ecs-frontend-manifest-1
        #switch: off
      - IN: deploy-ecs-frontend-dev-cluster
      - IN: deploy-ecs-frontend-dev-alb
        applyTo:
          - manifest: deploy-ecs-frontend-manifest-1
            image: deploy-ecs-frontend-image
            port: 8080

  - name: deploy-ecs-frontend-qa-deploy
    type: deploy
    method: upgrade
    flags:
      - deploy-ecs-frontend
    steps:
      - IN: deploy-ecs-frontend-qa-opts   
      - IN: deploy-ecs-frontend-qa-replicas     
      - IN: deploy-ecs-frontend-qa-params 
      - IN: deploy-ecs-frontend-dev-deploy
        #switch: off     
      - IN: deploy-ecs-frontend-qa-cluster
      - IN: deploy-ecs-frontend-qa-alb
        applyTo:
          - manifest: deploy-ecs-frontend-manifest-1
            image: deploy-ecs-frontend-image
            port: 8080    
##End of file##

**Comment by a-murphy** [comment]
It looks like your deploy job is paused.  To resume automatic triggering when the manifest completes, you can unpause the job by clicking on the job, going to the job dashboard by clicking the job name in the breadcrumb at the top, and clicking the resume job button in the top right.

**Comment by manishas** [comment]
Closing this issue. Please let us know if you have any additional questions.
