### ISSUE TITLE
Experiencing really slow builds and builds hanging

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4415]
We are seeing lots of our builds taking a VERY long time to run and in some cases just hanging completely. Then when the build is complete the build time being reported is nothing like the time actually taken.

Could someone please take a look?

Here is one example ...../mobility-server/runs/1059/1/console, this one has done nothing and is being reported at 15 mins duration but was actually running longer than that before being cancelled.

Thanks, Andy.

**Comment by manishas** [comment]
@shrivara can we look into this?

**Comment by shrivara** [comment]
We suspect that a recent kernel change in the VM image caused the problem. We have moved your subscription to use the earlier image, so everything should be back to normal.

Sorry about the trouble. Do let use know if the problem persists.

**Comment by andye2004** [comment]
@shrivara I would say it's better in that the build ran to completion but still a fair bit longer than our normal build times. 4 mins waiting for a node to be provisioned then a 15 minute build time for builds that complete on average in 9 minutes. Can you please look again?

**Comment by shrivara** [comment]
The build duration includes the node provisioning time if a new node comes up. So the overall build time is closer to 11 minutes. We're continuing to monitor to see if there any other factors affecting the build times.

**Comment by shrivara** [comment]
@andye2004, are you still experiencing slow/hanging builds?

**Comment by andye2004** [comment]
I haven't had any builds go though myself but I haven't had anyone complain over the last couple of days so on that basis I would think it's been OK. I'll close this issue.
