### ISSUE TITLE
Issue identified with billing account

### ISSUE THREAD

**Issue by trexx** [Shippable/support#4416]
Hi there, upon entering the billing page I get a notice asking me to get in touch with support.

**Comment by rageshkrishna** [comment]
Hi @trexx. Thanks for getting in touch. We will email you on the billing email address associated with your subscription shortly with more information on how this can be resolved.

**Comment by trexx** [comment]
Hi @rageshkrishna, when would I expect the email? I don't think I've received it yet.

**Comment by rageshkrishna** [comment]
Sorry about the delay on this, @trexx. I'll follow up on this and make sure you have all the details in the next few hours.

**Comment by manishas** [comment]
@trexx I have sent an email to the billing email listed for your Subscription. Please let me know if it was received and we can resolve this issue over that thread.

**Comment by trexx** [comment]
Thanks @manishas. I've received the email. I'll be getting in touch soon.

**Comment by manishas** [comment]
This has been resolved, closing.
