### ISSUE TITLE
runSh multiline script truncated to just one character

### ISSUE THREAD

**Issue by dcecile** [Shippable/support#4418]
I'm trying to use a multiline `runSh` script, but just the first character is getting run. For example, trying to put `echo` first:

```
/var/lib/shippable/build/scripts/yml_task_0.sh: line 96: e: command not found
```

Here's the job output: https://app.shippable.com/github/tacit-lang/jobs/tacit_ghPagesDeploy/builds/5b2db9123626c20700cdf42e/console

I tried running my config in a YAML parser, and everything looks valid. Any ideas what's happening here?

**Comment by a-murphy** [comment]
The `script` in `TASK` is expected to be an array of script commands.  It sounds like a string may have been converted to an array.  Could you make sure that you have a `-` in front of each script line or multi-line block in `script` as shown [here](http://docs.shippable.com/platform/workflow/job/runsh/)?  Multi-line blocks should only have one `-` at the beginning, not one for each line.  Single-line commands should each have a `-`.

**Comment by dcecile** [comment]
Thanks @a-murphy, that was exactly it 🙇 

In case it's useful information, here's the path that led me all the way to reach this error...

1. I wanted a way to only run my `runSh` job for non-PR commits, but didn't find any job fields for "stop when CONDITION" or "only start when CONDITION", or any organization settings to keep PRs enabled for CI but disabled for assembly lines
2. I decided to integrate the `IS_PULL_REQUEST` flag into my CI script (it's not available for `runSh` jobs), but couldn't find any way to "stop here without failing" for a multi-step script (e.g. `if CONDITION; then exit 0; fi` doesn't work)
3. The CI job happens to support both multi-line blocks with and without a ` - ` at the beginning (leading me to believe the same would be true for `runSh`)
4. The [`runSh` docs](http://docs.shippable.com/platform/workflow/job/runsh/) actually have 2 examples of using multi-line blocks without ` - ` at the beginning (search for `script: |`)

Anyways my scripts are working fine now, so none of these issues are blocking me. Thanks for your help!

**Comment by manishas** [comment]
We're going to go over docs and correct any problematic examples.

**Comment by trriplejay** [comment]
We've updated the docs to have to correct syntax. thanks for pointing this out.
