### ISSUE TITLE
Timeout during the build

### ISSUE THREAD

**Issue by gfamorimo** [Shippable/support#4419]
Hi guys,

On Tuesday I was able to generate a build as normal.
But when I tried on Thursday it didn't work anymore.
I didn't change nothing in my shippable.yml, but after this error I tried included some cache but still not working.
I saw that when the maven try download the dependencies it took so much time and the build failure with timeout reason.
Can you guys help me with this?

- https://app.shippable.com/bitbucket/gfamorimo/sisfest-server/runs/244/1/console

This is big issue for me, and I can say that it is critical.

**Comment by shrivara** [comment]
Have there been any recent changes to the dependencies? 

We've seen [slow maven downloads](https://github.com/Shippable/support/issues/4026) due to excessive logging before. Could you try running `mvn -q install` and see if it helps? 

Also, the Java image you are running has been deprecated. Please consider moving to a [newer image](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/).

**Comment by gfamorimo** [comment]
Hi Shrivara,

Thank you for answer.
I didn't change nothing regarding the dependencies.
I update the version of my node and also included the `mvn -q install`.
Still getting timeout.

Do you have any suggestion?

**Comment by shrivara** [comment]
Could you try rebuilding any older successful build see if it also times out? There haven't been any changes to the build environment recently, so its strange that it would start to time out.

**Comment by gfamorimo** [comment]
Hi Shrivara,

Sorry for this delayed answer.
I tried rebuild the last successful build that I had and I got timeout too.
Any idea what I can do?

**Comment by shrivara** [comment]
Looking at the build logs, it looks like one of the maven repositories (http://maven.mashape.com/releases) is taking a long time to resolve. Could you try removing it/using an alternative and see if that helps?

**Comment by gfamorimo** [comment]
Hi Shrivara!

Sorry for took your time.
You're right, this legacy application was using a old version of one dependency.
So, I updated this dependency, removed this repository to oldest jar and worked!

Thank you!
