### ISSUE TITLE
Trigger release based on specific job

### ISSUE THREAD

**Issue by xiaoxipang** [Shippable/support#4420]
### Description of your issue:
I have a pipeline that has two deploy job (A) and job (B), both of them may trigger a E2E test runCI job (C) at either different time or same time. If test succeed, I want to trigger another two release job (D) and (E) according to A & B which triggers the C.
```
A(deploy) --\               /-- D(release)
               C(runCI)
B(deploy) --/               \-- E(release)
```
If A finishes deployment, then C runs successfully, D should be triggered.
If B finishes deployment and C runs successfully, E should be triggered.
If both A and B finishes around same time and C runs successfully, D and E should be triggered.
If both A and B finishes and C runs failed, None of them should be triggered.

First, I thought deploy job doesn't support OUT. So what I can think of is creating a central state and a followup runSh after each deployment. Then write add value into central state accordingly. Then when C finishes testing successfully, it will read in the central state and bump the version/param resource based on the collection of state. Then the bump version/param resource will auto trigger the release. 
```
A(deploy) --- A'(runSh) --\                 /-- D'(param/version) -- D(release)
                   |        \             /
                   F(state)      C(runCI)
                   |        /             \
B(deploy) --- B'(runSh) --/                 \-- E'(param/version) -- E(release)
```
Overall, I feel what I'm thinking is too complicated. So I'm wondering if there is a better solution on this problem.

**Comment by manishas** [comment]
@Zingoer The $JOB_TRIGGERED_BY_NAME environment variable can tell you which job triggered the runCI job. So in job C, you can use this variable to determine which release to increment.

What is the purpose of D' and E' in your picture?

**Comment by xiaoxipang** [comment]
@manishas Thank you for your help!
When you mentioned "which release to increment", how should I achieve that?

The deploy A and B will deploy our service into staging and D and E will be the release gate for service deployment in pre-producation environment. I hope that after C finish tests, it can help trigger either D or E or both based on $JOB_TRIGGERED_BY_NAME. What I've understood that the release can be auto triggered by a IN job/resource, that's why I want to add a resource D' and E' that will modified by the C to change the release. But I assume there should be a easier way. Any suggestion?

BTW, in Webhook config, I turn on the "Last commit/Branch" for job C. In this case, if A triggers C, and then B finishes the deployment, C will restart and the value for $JOB_TRIGGERED_BY_NAME will be only B. However, I hope after the C, both D and E can deploy because both A and B are deployed.

**Comment by xiaoxipang** [comment]
Or is there a way I can make image resource as an IN for the release job but holding it to trigger the release  D until test C finishing?

**Comment by trriplejay** [comment]
@Zingoer I think you're on the right track. if you need to trigger D, E conditionally, then you'll need that intermediate resource.  That resource could be the version itself:

![image](https://user-images.githubusercontent.com/6869398/41870821-ffb949ec-7871-11e8-9e98-c8e10ecd4b12.png)

This also gives you control over what version number gets produced next, but if you just want the release job to handle that, then you just need to write some other value to the version resource via `shipctl_put_resource_state`

what are the release jobs being used for, is it purely to produce the version number?  If so, then you may want to consider just using the `bump_version` feature of shipctl in your runCI job. http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#bump_version  However this would mean that you'd have to fully manage the version numbers yourself.

is there anything that comes after jobs D and E in your pipeline? are you doing more deployments via deploy jobs?

**Comment by xiaoxipang** [comment]
@trriplejay Thank you for your explanation, I'll digest what you are saying and have a try. 

D and E controls another two deployment jobs F and G (Pre-prod) to another AWS environment that is different from A and B (Staging). 

Where if A is deployed, I hope eventually D will trigger F to deploy. Where if B is deployed, I hope E will trigger G to deploy.

The hardest part is when both A and B deployed, And C will start to trigger by A, for example. Then because B's deployment, it will stop the current C and restart C. Then only the E will be released. But in this case, we actually hope that both D and E can be released.

**Comment by xiaoxipang** [comment]
@trriplejay Is there a way I can use two condition combination to decide if I want to trigger the release. 

For example, https://app.shippable.com/subs/bitbucket/mxitechnologies/dashboard
I have a fp-web-img and fp-web-version-pre-prod as the IN of the fp-web-release-pre-prod. 
and a fp-forecast-img and fp-forecast-version-pre-prod as the IN of the fp-forecast-release-pre-prod. 

If both IN of fp-web-img and fp-web-version-pre-prod are increased to a new value, then the fp-web-release-pre-prod will release.

**Comment by trriplejay** [comment]
whether or not the release job triggers depends on whether or not you update the resource between runCI and release.  So, you can use any logic that you'd like to decide whether or not to perform that update. You can definitely check versions of IN resources. It might be difficult to see if they've changed, since that would require that you keep track of their previous version information as well, but this should be possible by using the job's own state (I can explain how to do that if you need that functionality).

Another thing i wanted to mention is that if you connect your deploy job (A) to the release job (D) the manifest from (A) will be passed along as part of the release, then when you deploy again to (F) it will use the same manifest (which can be modified via dockerOptions and params in job F). Not sure if that's what you'd want, but figured I'd mention it.

**Comment by xiaoxipang** [comment]
@trriplejay Yes, I think I need your help to explain how to keep tracking the previous version of the same job so that even C is restarted by a new finished deployment, I can still accumulate the services I want to release eventually. 
Yes, we use different dockerOptions to control the A and F

BTW, when you say " So, you can use any logic that you'd like to decide whether or not to perform that update. You can definitely check versions of IN resources.", do you mean I can write some script logic in deployment job to check what is in or do you mean I can write some script logic in the runCI to make different OUT condition?

**Comment by trriplejay** [comment]
I was referring to script logic in the runCI to determine which OUT resource to update.  Today there is no setting that allows you to only trigger after a certain combination of inputs changes.

So, when a job is running, you will have access to a state directory, located at `$JOB_STATE`.  Any files that you create in the directory will be saved as part of the job's state (up to 1MB total max).  Each job also contains a `previousState` directory, where all of the files exist from the last time the job completed.

What you'd probably want to do is write some detail about each item into a file, like:
```sh
img1CurrentVersion=$(shipctl get_resource_version_name img1)
img2CurrentVersion=$(shipctl get_resource_version_name img1)
echo "img1LastVersion=$img1CurrentVersion" >> $JOB_STATE/versionList.env
echo "img2LastVersion=$img2CurrentVersion" >> $JOB_STATE/versionList.env
```

You can check if this file exists in previousState, and if so, source it into the ENV
```sh
if [ -f $JOB_PREVIOUS_STATE/versionList.env ]; then . $JOB_PREVIOUS_STATE/versionList.env; fi
```
then you can compare `img1LastVersion` to `img1CurrentVersion` to see if they are different

One caveat of this is that you need to disable parallel builds for this runCI job, or else if multiple jobs run in parallel, the state may not be accurate.

**Comment by xiaoxipang** [comment]
@trriplejay Thank you so much! I'll try it.

**Comment by xiaoxipang** [comment]
@trriplejay A side question, when I SSH into a debug session in runCI job and exec the docker, there is no value coming back from ECHO. For example, inside the docker, I try to `ECHO $STATE` but I got empty response.
I also try to use shipctl inside the debug mode, but no value be able to return.
![capture](https://user-images.githubusercontent.com/15240273/41947338-f5e5e02e-7984-11e8-81ae-e65c887231ea.PNG)

So do I make some mistake or it's just not be able to echo out/shipclt out value inside the SSH debug mode?

**Comment by trriplejay** [comment]
ahh, my mistake, it should be `$JOB_STATE`

Although when ssh'd in, your shell is not in the same context as the build script, so the environment variables won't be available.  These variables are documented here: http://docs.shippable.com/platform/workflow/job/runci/

**Comment by xiaoxipang** [comment]
@trriplejay Got it, thank you! I'll keep trying.

**Comment by xiaoxipang** [comment]
@trriplejay I almost make it work use another way. But there is a bug in my pipeline (I believe it's somehow I mis-configure it)
https://app.shippable.com/accounts/57dbf044d6fd750f001ed8fd/dashboard/31

For example, when I trigger lrp-validator-runCI job, it will output image and generate manifest, then try to deploy in staging. However, at this moment, lrp-test_runCI job is automatically triggered somehow. Instead of disorder running, I hope the pipeline run in the order of runCI -> manifest -> deploy-staging -> protractor_runCI -> test_runCI -> release.
I highly suspect the reason of this bug is that I'm trying to make fp-validator-img as a IN of the lrp-test-runCI. The reason I'm doing that is I want to fetch the image version in the lrp-test_runCI so that I can OUT is in fp-env-params-validator-pre-prod-trigger
```shipctl put_resource_state "fp-env-params-validator-pre-prod-trigger" "IMAGE_VERSION" $(shipctl get_resource_version_name "fp-validator-img");```

So I'm wondering how I can fetch the fp-validator-img version name without make fp-validator-img as a IN?

**Update**
I fixed the bug by change all of the IN's switch off. Though I still have the same question,
how I can fetch the fp-validator-img version name without make fp-validator-img as a IN? Because When I click in the future job and under the Trace tab, I can see all of the previous resource and job. So I thought there probably a way I can find anything in previous. I just not sure if I can do this through shipctl.

**Comment by trriplejay** [comment]
There isn't an easy way to get the versionName of the image without using it as an IN.  I think your best alternative option is to utilize the "trace" data like you mentioned. However, looking at your pipeline, it doesn't seem like you're actually using this versionName information. It's being written to a params resource, which triggers the subsequent release job, but release job won't utilize the value in params, and those params aren't getting used elsewhere, so is the versionName actually important to pass along?

**Comment by xiaoxipang** [comment]
@trriplejay Yes, versionName doesn't be used for later job. It's a work around to know which services need to deploy in preprod based on the versionName difference. Would you mind to tell me how I can use the trace data? Especially in the runCI/runSh command mode, how do I be able to fetch all of those trace tree?

**Comment by trriplejay** [comment]
so, each IN resource has its own incoming 'trace' property.  The 'trace' property is a flat array that lists all relevant resources and version details that lead up to the current job.  Each item has knowledge of its parent, so you can build the dependency tree from it, but in your case, I think you can just loop over the array to find the relevant resourceNames and versionNames.

You can get to the trace object by using the "meta" path for the IN resource:
```sh
meta_path=$(shipctl get_resource_meta <your IN resource name>)
jq '.version.propertyBag.trace' $manifest_meta/version.json
```

each item in the array will look something like this:
```json
{
          "operation": "IN",
          "resourceId": 51613,
          "resourceName": "ecsStaging-deploy",
          "resourceTypeCode": 1015,
          "versionId": 4264494,
          "versionNumber": 4,
          "versionName": null,
          "versionCreatedAt": "2018-02-12T21:02:35.078Z",
          "usedByVersionId": 0
        }
```

**Comment by xiaoxipang** [comment]
@trriplejay This is totally awesome, thank you so much! I'll try this at the end of the week.

**Comment by xiaoxipang** [comment]
@trriplejay The method works! Thank you so much!
