### ISSUE TITLE
Long hanging jobs

### ISSUE THREAD

**Issue by xiaoxipang** [Shippable/support#4421]
### Description of your issue:
This is our statistic page https://app.shippable.com/subs/bitbucket/mxitechnologies/insights
From this page, you can identify and find on 2018-06-25 9AM to 10AM and 4PM to 6PM that we got several jobs that hanged for several hours. Because we had multiple team that tried to merge the code, I'm not sure the true cause was. But based on the build log, each job hanged in the different place and had no relationship. As well, there were no more logs printing after hanging that can help us identifying the problem, we had to manually stop them.
I've seen this thread https://github.com/Shippable/support/issues/4415 but not fully sure if it's the similar problem.

**Comment by shrivara** [comment]
@Zingoer, the problem is related. We have now rolled back all the images. You should not see the problem again, do let us know if this isn't the case.

**Comment by xiaoxipang** [comment]
@shrivara Thank you for your help! We haven't seen similar problem again today. 
Another small question, will you auto update ours image after you fixing this or we need to manually change that?

**Comment by shrivara** [comment]
No manual action is needed if/when we update the images.

**Comment by shrivara** [comment]
@Zingoer, please reopen if this occurs again.

**Comment by xiaoxipang** [comment]
@shrivara Thank you for the help and fix!
