### ISSUE TITLE
Is it possible to configure the Docker storage driver used by builds?

### ISSUE THREAD

**Issue by ray-grointel** [Shippable/support#4425]
We're using a custom Docker image for our shippable builds, and have had errors caused by the Docker AUFS storage driver's [lack of support for some filesystem actions](https://docs.docker.com/storage/storagedriver/aufs-driver/#modifying-files-or-directories): 

> Renaming directories: Calling rename(2) for a directory is not fully supported on AUFS. It returns EXDEV (“cross-device link not permitted”), even when both of the source and the destination path are on a same AUFS layer, unless the directory has no children. Your application needs to be designed to handle EXDEV and fall back to a “copy and unlink” strategy.

We've seen this issue affect `npm --global install` commands, and raise "postgres permission denied" errors:
 
- https://github.com/Painted-Fox/docker-postgresql/issues/30#issuecomment-61350621
- https://github.com/puntonim/docker-postgresql93/issues/2#issuecomment-65127667

Some solutions suggested include switching the Docker storage driver from AUFS to devicemapper:

- https://github.com/puntonim/docker-postgresql93/issues/2#issuecomment-65490168

Is it possible to configure the Docker storage driver used by builds? https://docs.docker.com/storage/storagedriver/device-mapper-driver/#configure-docker-with-the-devicemapper-storage-driver

---

Example build: https://app.shippable.com/bitbucket/grointelligence/gro/runs/19351/1/console

**Comment by trriplejay** [comment]
Currently this is not a configuration option that we provide.  I think if you were to utilize our [BYON feature](http://docs.shippable.com/platform/tutorial/runtime/custom-nodes/#byon-nodes) that you might be able to configure a node to use device mapper instead.
