### ISSUE TITLE
Issue identified with billing account

### ISSUE THREAD

**Issue by Boolos** [Shippable/support#4426]
### Billing account issue
I received this message on my billing page:
> An issue has been identified with your billing account. Please contact support

Any help would be appreciated, thx!

**Comment by sdlarsen** [comment]
I got this as well. Advice appreciated.

**Comment by rageshkrishna** [comment]
@Boolos your billing page should be restored now.

@sdlarsen I've reached out to your billing email with details on how to resolve it for your subscription.

**Comment by Boolos** [comment]
Awesome thank you, @rageshkrishna !
