### ISSUE TITLE
wrong error message - "does not match integrations present" instead of "is only usable in assembly line jobs"

### ISSUE THREAD

**Issue by michael-paddle** [Shippable/support#4428]
### Description of your issue:
I definitely definitely have an integration called "abc" in my subscription - see attached image. 

<img width="787" alt="shippable-screenshot" src="https://user-images.githubusercontent.com/34446076/42029327-1dba0fce-7ac7-11e8-8fcc-e92bcbb92491.png">

I still get the message 

`Integration name specified in yml does not match integrations present in Subscription settings: abc
`
I assume I'm doing something wrong but I really can't work out what.  Please help.

- Link to the build failure

https://app.shippable.com/github/PaddleHQ/aws-cloudflare-secgroup/runs/34/1/console

- Scripts called from the yml (optional)

**Comment by rageshkrishna** [comment]
It looks like you're trying to use an "AWS IAM" integration in a CI job. Currently, AWS IAM integrations are only [supported for use in assembly line jobs](http://docs.shippable.com/platform/integration/aws-iam/#usage-in-assembly-lines), not in CI.

Perhaps you're looking for the [AWS Keys integration](http://docs.shippable.com/platform/integration/aws-keys/), which can be used in CI.

**Comment by michael-paddle** [comment]
Okay, aws key does work so that would be it.  I guess this can be considered a bug report that the error message is wrong.  Instead of saying that the integration doesn't match the error should say that the integration is only usable in assembly lines.  

Thanks for your help

**Comment by manishas** [comment]
This has been fixed with a better error message.
