### ISSUE TITLE
passing dynamic environment variables are failing in build section

### ISSUE THREAD

**Issue by vinaganti** [Shippable/support#4429]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by vinaganti** [comment]
here is the config file for your review, please help us ASAP

# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js
node_js:
  - 8.11.1

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:   
    - ECR_REPO=066245240757.dkr.ecr.us-east-1.amazonaws.com/bnc-compass-frontend-repo
    - API_URL_DEMO=https://jhcexiree7.execute-api.us-east-1.amazonaws.com/demo
    - API_URL_QA=https://5r7w7kdt16.execute-api.us-east-1.amazonaws.com/qa

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    #- shippable_retry yarn install   


  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    # If this is master (not a pull request, not a release), build with demo url
    - 'if [ $IS_PULL_REQUEST == "false" ] && [ "$IS_RELEASE" == "false" ] ; then docker build -t $ECR_REPO:$BRANCH.$BUILD_NUMBER . --build-arg API_URL=$API_URL_DEMO; fi'    
    # If this is a release (not a pull request, is a release), build with QA url
    - 'if [ $IS_PULL_REQUEST == "false" ] && [ "$IS_RELEASE" == "true" ] ; then docker build -t $ECR_REPO:$BRANCH.$BUILD_NUMBER . --build-arg API_URL=$API_URL_QA; fi'    
    # In both instances, push the result
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker push $ECR_REPO:$BRANCH.$BUILD_NUMBER ; fi'
    #- 'if [ $IS_PULL_REQUEST == "false" ] ; then echo "versionName=$BRANCH.$BUILD_NUMBER" > $JOB_STATE/deploy-ecs-frontend-image.env ; fi'
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then shipctl post_resource_state deploy-ecs-frontend-image versionName $BRANCH.$BUILD_NUMBER; fi'
# Integrations are used to connect external resources to CI

**Comment by a-murphy** [comment]
The YML parser can be a little picky about a `:` in the middle of a line.  Could you try putting single quotes around those lines so that the `env` section becomes:
```YML
env:
  global:
    - ECR_REPO=066245240757.dkr.ecr.us-east-1.amazonaws.com/bnc-compass-frontend-repo
    - 'API_URL_DEMO=https://jhcexiree7.execute-api.us-east-1.amazonaws.com/demo'
    - 'API_URL_QA=https://5r7w7kdt16.execute-api.us-east-1.amazonaws.com/qa'
```

If this doesn't work, could you let us know if you are seeing an error message or which project this is?

**Comment by adampash** [comment]
Thanks for the response, @a-murphy.

That's not the issue, those vars are being recognized fine. The issue we're having is that because this is a bitbucket repo, `if [ $IS_PULL_REQUEST == "false" ] && [ "$IS_RELEASE" == "true" ]` isn't working for us (I saw too late in the docs that `IS_RELEASE` only works for github), so the real question here is: what's a good alternative way to approach this. Essentially we need a "staging" type build off master and a "prod" type build off of release tags (or at least this was the goal). It's looking now like that might not be an option, so I'm just trying to find a good solution to reach the same outcome, which is that our `docker build` command gets a different `API_URL` variable depending on whether it's the `master` branch (staging) or a release (production).

**Comment by a-murphy** [comment]
We don't support releases on Bitbucket (and they don't appear to be an option on Bitbucket), but we do support tag webhooks.  (GitHub has both tags and releases, with a release either creating a tag or referring to an existing one.)  So you could enable tag builds in your project settings and use `IS_GIT_TAG` to determine if the build was created for a new tag.

**Comment by adampash** [comment]
@a-murphy According to your docs for `IS_GIT_TAG`: 

> This env variable is currently supported for GitHub only.

Is that not the case?

**Comment by a-murphy** [comment]
Although tags used to be supported only for GitHub, they are now supported for both GitHub and Bitbucket.  We've already opened an internal issue to update that in the documentation.

**Comment by adampash** [comment]
Great to hear, thanks! I'll give that a try.

**Comment by adampash** [comment]
@a-murphy Does it also support `GIT_TAG_NAME`?

**Comment by a-murphy** [comment]
Yes, `GIT_TAG_NAME` will also be set for Bitbucket tag builds.

**Comment by manishas** [comment]
The docs for this are fixed. Closing this issue, but let us know if you have any other questions @vinaganti @adampash
