### ISSUE TITLE
trying to pay for support - blocked with a noentry but no error

### ISSUE THREAD

**Issue by michael-paddle** [Shippable/support#4431]
### Description of your issue:
When we try to pay for support on the console the upgrade button doesn't work.  It is slightly greyed out and the mouse icon changes to a noentry sign.  We can't see any error or explanation fo why.  What's wrong.  We are trying to pay from the wilson-paddle account.   ##

<img width="887" alt="shippable-try-to-pay" src="https://user-images.githubusercontent.com/34446076/42101167-2d6374c6-7bba-11e8-83d2-7eb39afd98a9.png">

**Comment by manishas** [comment]
@michael-paddle did you enter a billing contact? That as a required field and the Upgrade button should be activated after that.

**Comment by michael-paddle** [comment]
Thanks for your response @manishas ;  we can't see the place to fill in the billing contact anywhere.  this is what we see when we put in a credit card.


![snippable-card-image](https://user-images.githubusercontent.com/34446076/42104421-695d632e-7bc4-11e8-83c3-9ca074edfcc4.png)

**Comment by trriplejay** [comment]
It looks like you're lacking the necessary permission on the organization to make this change. Unfortunately our UI is quite confusing about what you can and can't do, so I'll open a ticket to address that.

Is there someone with admin-level permissions on the organization that could log in and make this change?

**Comment by manishas** [comment]
@michael-paddle do you still need help with this? Were you able to get an admin to upgrade?

**Comment by michael-paddle** [comment]
@manishas this has worked.  We did _have_ to fill everything in on the GitHub account owner's account and this _does not_ make sense since the credit card we wanted to use belongs to someone else.  Please do make this less confusing because we almost ended up not subscribing because it was not at all obvious what was wrong.  

Still.  Problem solved.  Thanks for your and @trriplejay's help.
