### ISSUE TITLE
Maven snapshot issue

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4433]
Hey guys, we're having a problem with one of our builds that currently has a snapshot dependency where when the build is run it does not download a newer snapshot.

On the surface this would seem like a maven issue but I don't think it is because Maven logs that that it has downloaded the latest meta data for the snapshot but then it just doesn't bother to download the newer snapshot. We are using the '-U' flag and have also set the refresh policy to 'always' so assuming the timestamp on the local file is older than the fresh meta data then Maven would download the snapshot.

So my question is; when the cache is restored does it have any effect on the timestamps of the files in the cache? Is it possible that the timestamp on the m2 repo snapshot is being updated to the time the file was restored? If so then this would explain the reason Maven doesn't try to download the newer version.

Thanks, Andy.

**Comment by trriplejay** [comment]
Hi Andy,

I can confirm that the timestamps in restored cache match the time from when the cache was created. It should have its original timestamp until something else modifies it.

**Comment by andye2004** [comment]
Thanks @trriplejay, silly question anyway. I just completely forgot that Maven doesn't even look at the timestamp on the file, was hoping rather than expecting a problem here.

Thanks for getting back to me!
