### ISSUE TITLE
UI indicates that one more parallel job can run, but queued jobs stay waiting

### ISSUE THREAD

**Issue by yulianovdey** [Shippable/support#4437]
Hi Shippable,

Our Shippable UI says `Parallel jobs: 1 of 2`, but queued jobs stay in the queue until the number of `processing` jobs is back down to 0:

![screen shot 2018-07-03 at 4 22 25 pm](https://user-images.githubusercontent.com/2703323/42243001-e9c4f10a-7edd-11e8-9111-a4758a20c0c2.png)

Is this because we've hit some other limit? If so, is there a way to view that limit somewhere and find out when it will reset?

Thank you!

Yulian

**Comment by trriplejay** [comment]
we're investigating

**Comment by trriplejay** [comment]
it looks like your node pool is currently only configured to have 1 node. You can change this by going to your subscription dashboard -> settings button -> node pools -> select "edit" in the right column next to your node pool, then in the "node count" field you can increase it to 2.

**Comment by yulianovdey** [comment]
@trriplejay ah. That solved it! Thanks for the quick reply.
