### ISSUE TITLE
Still can't get chrome headless working even after upgrading to 6.5.4 node

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4439]
https://app.shippable.com/bitbucket/silvercurve/pixelpipe-ember-architecture-service/runs/18/1/console

Just get browser timeout every time in every project. This one is the simplest test run. Works fine on Mac terminal with Chrome 67.

**Comment by a-murphy** [comment]
Could you try running your tests with [`xvfb`](https://www.x.org/archive/X11R7.6/doc/man/man1/Xvfb.1.xhtml) to create a display for the tests to use?  There's an example in our [Selenium documentation](http://docs.shippable.com/ci/selenium/#continuous-integration-with-selenium) to use `xvfb` with `npm test` for Selenium.  In your case, you'll probably want to use `xvfb` with `ember test`.

**Comment by manishas** [comment]
@BryanCrotaz did @a-murphy's suggestion work for you

**Comment by manishas** [comment]
Closing since the question was answered. Happy to reopen if it's not working.
