### ISSUE TITLE
An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.

### ISSUE THREAD

**Issue by provScottGiminiani** [Shippable/support#4440]
### Description of your issue:
The following error started occurring on our builds:

```
echo -e 'ECR get-login failed\n\n'
An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.
ECR get-login failed
/tmp/mexec/tmp-script.sh: eval: line 80: syntax error near unexpected token `('
/tmp/mexec/tmp-script.sh: eval: line 80: `An error occurred (UnrecognizedClientException) when calling the GetAuthorizationToken operation: The security token included in the request is invalid.'
```

I reverted the SCM change which kicked off the build when I first saw the error however it still seems to be occurring which leads me to believe it isn't something on our end. I also checked with our infrastructure team and they also didn't make and changes recently which would be causing this error.

- Link to the build failure:
Most recent: https://app.shippable.com/github/providenceinnovation/api.identity/runs/121/1/console
Original: https://app.shippable.com/github/providenceinnovation/api.identity/runs/119/1/console

**Comment by trriplejay** [comment]
This error indicates that the keys used to authenticate with ECR don't actually have access. Is it possible that the permissions were changed in AWS on those keys, or that those keys were revoked or have expired?

**Comment by provScottGiminiani** [comment]
I don't believe we're actually using ECR for anything. Is this not something internal to Shippable that is failing?

**Comment by trriplejay** [comment]
it looks like the shippable.yml includes an AWS integration in the "hub" section.  When Shippable sees this, we automatically try to do a ecr get-login and docker login using those keys.  Is the AWS integration being used for something else?

**Comment by trriplejay** [comment]
If you want to use the aws keys, but don't want ECR, I'd recommend utilizing a [key/value pair](http://docs.shippable.com/platform/integration/key-value/) type integration.  This will directly inject the variables into your environment.  If you set this up with the variables defined [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html), then any awscli command will automatically utilize the values from the environment. At a minimum I'd recommend `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_DEFAULT_REGION`.  

This type of integration can be included in the "generic" integration section of yml as shown here: http://docs.shippable.com/platform/tutorial/integration/howto-use-key-value-in-runci/

**Comment by manishas** [comment]
@provScottGiminiani I am closing this issue since the question was answered, but please let us know if you have any follow up questions.
