### ISSUE TITLE
My Project is not getting integrated to shippable

### ISSUE THREAD

**Issue by KevalS** [Shippable/support#4441]
Below is the issue that we are facing. I am adding Github integration to our project name 'Superble' in shippable but after integration its not showing in subscriptions. It was showing it till yesterday. Can you help me in knowing whats wrong? Below is the link to our account:
https://app.shippable.com/accounts/58f239f8b4fc670700aebdc3/settings
My email is krs435@nyu.edu

**Comment by a-murphy** [comment]
It looks like your subscription has two subscription integrations, but neither one is connected to an account integration.  Did you delete the original account integrations?

To select an account integration for the subscription integration, you can go to the subscription integration page in the subscription (click on the subscription name in the sidebar and then the gears in the top right), click on the subscription integration you want to update, and select an account integration from the dropdown.

**Comment by manishas** [comment]
Closing since the question has been answered. @KevalS let us know if you have any more questions.
