### ISSUE TITLE
3 nodes in our node pool, 2 are shown but only 1 is used

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4442]
This is from the node pool settings

![image](https://user-images.githubusercontent.com/332350/42400664-cc549912-8172-11e8-9053-9e5ae6067634.png)

And we have jobs waiting in our queue.

**Comment by a-murphy** [comment]
This is related to an issue we are investigating on our [status page](http://status.shippable.com/).  We'll update there, but the delays should be resolved at this point.

**Comment by vidiecan** [comment]
works now
