### ISSUE TITLE
Version name for runSH in app.shippable.com

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4443]
I have empty `Version Name` for runSh jobs dashboard, can I add a custom string there?

We have multiple use cases: 
- important information easily seen for the last N builds: e.g., custom QA information like 98%;
- version of a resource that the script was executed against (IN resource): if I want to find the build for a specific change I cannot do it from the dashboard but have to check every one or guess based on the times...

**Comment by a-murphy** [comment]
You should be able to add a [`shipctl put_resource_state`](http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#put_resource_state) command to your runSh job to set the version name.  For example, `shipctl put_resource_state $JOB_NAME "versionName=$YOUR_NAME"` will set the version name to the value of a `$YOUR_NAME` variable.

**Comment by vidiecan** [comment]
for the record, the correct cli is
```
shipctl put_resource_state $JOB_NAME "versionName" "$INFO"
```
