### ISSUE TITLE
Manifest jobs hanging indefinitely upon reset

### ISSUE THREAD

**Issue by moncef-mestiri** [Shippable/support#4445]
### Description of your issue:
- Manifest reset jobs are hanging in `Processing` status and cannot be stopped/cancelled
- The jobs hang at the `Generating Job` step and don't go beyond `Saving integration to vault`
- No errors are generated
- Cannot delete/purge the hanging jobs from the queue

- Links to the builds:
https://app.shippable.com/github/formhero/jobs/td-pat-studio-manifest/builds/5b40e61c138d9d07006ef22f/console
https://app.shippable.com/github/formhero/jobs/td-pat-services-manifest/builds/5b40e620d74dca0700ccbf75/console
https://app.shippable.com/github/formhero/jobs/td-pat-catalog-manifest/builds/5b40e5c7704d2e07008ff108/console

- `This is blocking deployment to production environment with business impact`

**Comment by RadekDvorak** [comment]
I have encountered a similar problem, for example [this manifest] (https://app.shippable.com/github/damejidlo/jobs/dj-prod-supervisor-manifest/builds/5b4145d41e57690700754ceb/console) does not finish. (stuck at _Getting files of previous job_).

**Comment by manishas** [comment]
@a-murphy @trriplejay can we take a look asap?

**Comment by trriplejay** [comment]
@moncef-mestiri i've cleared your stuck jobs. investigating the cause.

**Comment by moncef-mestiri** [comment]
Thanks @trriplejay

**Comment by trriplejay** [comment]
We've rolled back the changes that caused these stuck jobs. Please reopen if you see this again.
