### ISSUE TITLE
Job not started (still queued)

### ISSUE THREAD

**Issue by kileyhykawy** [Shippable/support#4446]
### Description of your issue:
I started a job over 30 minutes ago (https://app.shippable.com/bitbucket/luminarts/luminlife/runs/1165/summary/console) and it is still in the queued state. The console shows nothing for the job yet.

I know you had fixed some issues around this last night but it still looks like it isn't fixed.

**Comment by manishas** [comment]
I see that your job executed now. I have escalated this issue to the team.

**Comment by trriplejay** [comment]
we've rolled back the changes that caused this issue. please reopen if you see this again.
