### ISSUE TITLE
Cannot re-initialize nodes: host connection timeout

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4447]
We where trying to update our build nodes from 6.6.1 to 6.6.4 today and most of them have failed:

```
 copy_script_remote
  echo 'Creating the private key file...'
  echo 'Establishing connection and copying files to remote host...'
Establishing connection and copying files to remote host...
ssh: connect to host <build-node-ip> port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
```

Any idea what could be wrong here?

**Comment by rageshkrishna** [comment]
Hi @mbrodala. A couple of days ago we had an issue with GitHub connectivity as a result of which we had to quickly change our public IP address to avoid a service disruption.

Please whitelist `18.210.52.74` for incoming connections on port 22 to your hosts.

**Comment by rageshkrishna** [comment]
I see that you were able to update your nodes successfully so I'm going to go ahead and close this issue. Please let me know if you've had any other trouble with this.

**Comment by mbrodala** [comment]
Yes, it did not work so I temporarily had to drop all firewall rules. It's possible that these are simply messed up so I'll need to have a look at this.

**Comment by rageshkrishna** [comment]
Thanks for the update. Feel free to reopen the issue if you find it doesn't work even after whitelisting the new IP address.

**Comment by mbrodala** [comment]
I've done the change via UFW now, a manual rule edit before didn't work. Now re-init works fine.
