### ISSUE TITLE
Unclear about the failure

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4449]
Master build succeeds. Adding few MBs of file causes build failure. Is there is a disk limit? Any way to override?
https://app.shippable.com/github/Falkonry/kestrel/runs/490/1/console

**Comment by a-murphy** [comment]
It looks like you've switched to an Alpine base image for a `docker build` command in the failing run.  If your new base image uses `pip` version 10, it does looks like there are some issues installing `pandas` with that version of pip.  You can try installing `Cython` before `pandas`, try a different version of `pip,` or use a different base image.

I don't see anything related to the size of the files in the linked run, so let me know if I was looking in the wrong place.

**Comment by manishas** [comment]
@phagunbaya do you still need help with this?

**Comment by phagunbaya** [comment]
Nope. Thanks @a-murphy for the help.
