### ISSUE TITLE
Repetitive issues with connecting BitBucket accounts

### ISSUE THREAD

**Issue by psoders** [Shippable/support#4451]
Hello,

We encounter repetitive issues when new users connect to our shippable subscription
https://app.shippable.com/subs/bitbucket/humanoitgroup

user which now have issues "WojtekMrozek"

these were very similar issues, can we work out some permanent fix?
https://github.com/Shippable/support/issues/4375
https://github.com/Shippable/support/issues/4354
https://github.com/Shippable/support/issues/4044

**Comment by rageshkrishna** [comment]
@psoders Sorry for the trouble. We'll look at ways to minimize these false positives.

I've unblocked `WojtekMrozek`.

**Comment by psoders** [comment]
thank you @rageshkrishna , it works now

looking forward to see this issue removed permanently :)

**Comment by rageshkrishna** [comment]
Thanks for the update. I'll close this issue now as the user is unblocked.

We will definitely look in to improving our algorithm soon so genuine users are not inconvenienced by this.
