### ISSUE TITLE
Getting Image push failed error when i am trying to perform "docker push" to my AWS-ECS

### ISSUE THREAD

**Issue by sasikanthc** [Shippable/support#4452]
### Description of your issue: Getting Image push failed error when i am trying to perform docker push to my AWS ECS.

At Execute Shell added below script: 
docker build --pull -t ecs_app .
docker tag -f ecs_app $AWS_ACC_ID.dkr.ecr.us-west-2.amazonaws.com/ecs_app:latest
docker push 060360511212.dkr.ecr.us-west-2.amazonaws.com/ecs:latest

Error display in Jenkins:
203ac7c888b0: Buffering to Disk
203ac7c888b0: Image push failed

Please login prior to push:
Username: EOF
Build step 'Execute shell' marked build as failure
Finished: FAILURE

Kindly guide me what needs to be taken care from my end.

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
Based on the error message, it sounds like you haven't [authenticated with ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_AWSCLI.html).  Depending on which plugins you are using, your method of authentication may be different.

The issues in this GitHub repository are meant for questions and problems using [Shippable](https://www.shippable.com), and as a result we can't help much with errors in Jenkins.  If your error is specific to Jenkins, you will likely get a better answer elsewhere.

**Comment by manishas** [comment]
Closing this since it doesn't look like a Shippable issue
