### ISSUE TITLE
Stuck job

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4453]
Hi,

My [rSync job](https://app.shippable.com/github/damejidlo/jobs/dj-vue_prerender-pipeline_rSync/builds/5b472456511d780600f3768b/console) has been stuck for 26 minutes. Could you please do something about this problem?

**Comment by Bharath92** [comment]
We recently did a deployment. There was a problem with our rSync service. We paused it for a while. Now, it is back up. The job should be running now.

**Comment by RadekDvorak** [comment]
Fair enough. I would suggest pushing such information to the status page. I check it whenever I encounter a problem.
