### ISSUE TITLE
How to check Shippable's service status? (e.g. when facing builds stuck in Queue)

### ISSUE THREAD

**Issue by cboettig** [Shippable/support#446]
Hi,

My (simple trial/test) build has been stuck in queue for 30 minutes so far https://www.shippable.com/projects/53ed33ef87c0a9d101a9ef6a

Browsing similar issues it seems like this might be due to server load problems on shippable.  I was wondering if there was something like https://status.github.com/ for shippable, where I could see if shippable was suffering systemic problems and working to fix them, (in which case I would know to sit back and relax and not trouble you with support tickets that will resolve themselves when the big issue is fixed), or whether this problem was unique to me (in which case I would need to trouble-shoot to find out if I messed up something in my shippable.yml or so).  

I couldn't find any such page though.  If you don't have one, is that something you could consider?  (Your twitter account doesn't suggest any outages that I could see, but some of your recent replies in issues requests do, e.g.  #443 #444).  

Otherwise, if there's some other reason why my build is stuck in queue, I'd appreciate your help!

**Comment by manishas** [comment]
I am closing this issue since the build problems have been addressed. While we have not implemented a status page yet, we post status updates on twitter through our account. Follow us at https://twitter.com/BeShippable

**Comment by manishas** [comment]
We now have a status page live at http://status.shippable.com :)

Sorry for the long delay on this.... we've overhauled our process and can implement new features very quickly now so you'll see an improved response time to customer-initiated feature requests.
