### ISSUE TITLE
Nightly CI build for multiple branches

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4460]
The [`time` resource](http://docs.shippable.com/platform/workflow/resource/time/) can be used to [set up nightly CI builds](http://blog.shippable.com/setup-nightly-builds-on-shippable).

However, I need to do this for various branches, thus not only `master` but also `foo`, `bar`, etc since all of these cover a supported release version.

Is there any way to trigger nightly CI builds for each branch separately?

**Comment by trriplejay** [comment]
At this time, we don't have a way to trigger a particular branch for a runCI job via time resource.  It will always trigger the default branch.  This is something we're looking to enhance in the future.

Today, the best workaround is to use an intermediate runSh job plus API calls to manage the branches.  That would look something like this:
- your time resource is an IN to a runSh job.
- you have a shippable API token added as a key/value integration that is also an IN to the runSh job
- your runSh job executes an API call to start a new build: [call documented here](http://docs.shippable.com/platform/api/api-overview/#!/Projects/post_projects_projectId_newBuild)

In your api call, your payload can specify the branch that you want to run.  Let me know if you have further questions.

**Comment by manishas** [comment]
Closing this issue. Let us know if you have any follow up questions.
