### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by ConfuzzledRegistrationDev** [Shippable/support#4461]
Trying to create a new account using Github results in "account blocked" error.

The Github username is this one, `ConfuzzledRegistrationDev`.

Can you help?

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by ConfuzzledRegistrationDev** [comment]
Thank you very much. :-)
