### ISSUE TITLE
Unable to Stop Job in Processing Mode

### ISSUE THREAD

**Issue by johnboyer** [Shippable/support#4463]
### Description of your issue:

I'm unable to stop a job that has been processing for more than 5 hours. The link to the job is below. Pausing and resetting does not work in the UI. Deploying a new build doesn't work either. Please stop the job, so that I an deploy a new build in the UI. Thank you.

Note: This has been a problem since GitHub's outage today.

Regards,
John Boyer

NOTE: If you are experiencing a build failure, please include:

- https://app.shippable.com/github/konciergeMD/jobs/deploy-test3-presence-svc-manifest/builds/5b4ce2c749b38e0700485461/console

- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
We've updated that job to "canceled."  Let us know if you have any other problems.

**Comment by johnboyer** [comment]
Thank you, this issue is resolved.
