### ISSUE TITLE
PostgeSQL and PHP

### ISSUE THREAD

**Issue by atwiltshire** [Shippable/support#4465]
### Description of issue:

I am trying to integrate PHPUnit tests into my CI flow, however I am experiencing issues with the Postgres DB as the required php extensions are not installed by default. 

I initially tried to install the extension via pickle per the [documentation](http://docs.shippable.com/ci/php-continuous-integration/), however pickle is returning an error. 
```
pickle install pdo_pgsql
  - Installing pdo_pgsql (latest-stable): Downloading (connecting...)Downloading (0%)           Downloading (55%)Downloading (100%)

                                                                         
  [Exception]                                                            
  Couldn't parse the version defined in the PHP_PDO_PGSQL_VERSION macro  
```
Looking over the[ pickle repository ](https://pecl.php.net/package/PDO_PGSQL)I have also noticed that the latest release is V1.0.2 which was release on 01/05/2006.

I have tried to use the package manger to install the required php extension however I am not sure if this is being installed against the correct PHP instance.
```
   - sudo apt update --fix-missing
   - sudo apt install php-pgsql
   - echo "extension=pgsql.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
```
Resulting in 
```
if [[ $PHPCS != 1 ]]; then vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage; fi
PHP Warning:  PHP Startup: Unable to load dynamic library '/root/.phpenv/versions/7.1/lib/php/extensions/no-debug-non-zts-20160303/pgsql.so' - /root/.phpenv/versions/7.1/lib/php/extensions/no-debug-non-zts-20160303/pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/root/.phpenv/versions/7.1/lib/php/extensions/no-debug-non-zts-20160303/pgsql.so' - /root/.phpenv/versions/7.1/lib/php/extensions/no-debug-non-zts-20160303/pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHPUnit 6.5.9 by Sebastian Bergmann and contributors.

.IIException: Database driver Cake\Database\Driver\Postgres cannot be used due to a missing PHP extension or unmet dependency in [/root/src/bitbucket.org/cardiffuni/php-app-toolkit/vendor/cakephp/cakephp/src/Database/Connection.php, line 179]
```

- Link to the build failure: https://app.shippable.com/bitbucket/cardiffuni/php-app-toolkit/runs/28/1/console

**Comment by a-murphy** [comment]
PHP can't find `pgsql.so` because the `php.ini` file is configured with `extension_dir` `/root/.phpenv/versions/7.1/lib/php/extensions/no-debug-non-zts-20160303` and that's not where the `apt` command installed it.  You can try using a full path in the `php.ini` so that it will know where to look.  Since the path for `pgsql.so` installed with this method includes the date, I would suggest using `find / -name pgsql.so` to find the path and assign it to a variable.  For example, `PGSQL_PATH=$(find / -name pgsql.so)`.  And then use that variable in the `echo`.

**Comment by atwiltshire** [comment]
Thanks I had't thought about the different install location.

Moving past the pgsql dependency issue I am now getting the following error.

```
if [[ $PHPCS != 1 ]]; then vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage; fi
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20170718/pgsql.so' - /usr/lib/php/20170718/pgsql.so: undefined symbol: pcre_exec in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/20170718/pgsql.so' - /usr/lib/php/20170718/pgsql.so: undefined symbol: pcre_exec in Unknown on line 0
PHPUnit 6.5.9 by Sebastian Bergmann and contributors.

.IIException: Database driver Cake\Database\Driver\Postgres cannot be used due to a missing PHP extension or unmet dependency in [/root/src/bitbucket.org/cardiffuni/php-app-toolkit/vendor/cakephp/cakephp/src/Database/Connection.php, line 179]
```

I have added the following into my .yml file however this does not seem to be the solution, do you have any ideas?

`- pickle install apcu && echo "extension=apcu.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/p;`


- Link to the build failure:  https://app.shippable.com/bitbucket/cardiffuni/php-app-toolkit/runs/48/1/console

**Comment by a-murphy** [comment]
Did you mean to add `extension=acpu.so` to `php.ini`?  If so, it looks like you lost the last part of your file path in the `echo` command at some point and fixing that is likely to help.  The most common suggestion for similar errors seems to be to reinstall `apc`.

**Comment by atwiltshire** [comment]
Sorry, copy past error into the ticket. The `apc` extension had been installed (I have tried both an install via apt and pickle, both result in the same error.

```
#- sudo apt install php-apcu;
#- APCU_PATH=$(sudo find / -name apcu.so | sort -r | head -n 1);
#- echo "extension="$APCU_PATH;
#- echo "extension="$APCU_PATH >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
 - pickle install apcu --no-interaction && echo "extension=apcu.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
```
I also printed the PHP.ini to ensure the extensions had been added.

```
extension=apcu.so
extension=/usr/lib/php/20170718/pgsql.so
```
Result:

```
if [[ $PHPCS != 1 ]]; then vendor/bin/phpunit --log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage; fi
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20170718/pgsql.so' - /usr/lib/php/20170718/pgsql.so: undefined symbol: pcre_exec in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/20170718/pgsql.so' - /usr/lib/php/20170718/pgsql.so: undefined symbol: pcre_exec in Unknown on line 0
PHPUnit 6.5.9 by Sebastian Bergmann and contributors.

.IIException: Database driver Cake\Database\Driver\Postgres cannot be used due to a missing PHP extension or unmet dependency in [/root/src/bitbucket.org/cardiffuni/php-app-toolkit/vendor/cakephp/cakephp/src/Database/Connection.php, line 179]
```

**Comment by a-murphy** [comment]
One thing I noticed is that the `php-pgsql` package you are installing is installing `pgsql` for PHP 7.2.  I would suggest trying `php7.1-pgsql` because you are using PHP 7.1.

**Comment by atwiltshire** [comment]
Thanks, I had assumed that as I was setting the php version explicitly in the .yml file this would have been the default. I altered both the pgsql and apcu installs to use php7.1 and the issue remains. https://app.shippable.com/bitbucket/cardiffuni/php-app-toolkit/runs/61/1/console

**Comment by a-murphy** [comment]
I'm not a PHP expert, so I'm not sure what the problem could be at this point.  It certainly sounds like something is looking for `pcre_exec` in the wrong place, but I don't know what or where it's looking.

You could try something similar to this workaround for another PHP issue a few years ago: https://github.com/Shippable/support/issues/2807#issuecomment-234156571, if you haven't already.  Most of that issue won't be relevant to you, but perhaps copying the `.so` file(s) from another installation would work since it has worked in the past with an older build image.

**Comment by manishas** [comment]
@atwiltshire were you able to resolve this?

**Comment by rageshkrishna** [comment]
Closing as we haven't heard back in many months. Please re-open if you still need help with this.
