### ISSUE TITLE
gitRepo resources are marked as inconsistent

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4467]
I have some `gitRepo` resources marked as inconsistent, and I can't tell why based on the `rSync` job output:

```
rSync encountered 3 errors while processing AIAScience/MLSuite: 
  - Failed to update resource: 82673, with error: Failed to fetch data for AIAScience/MLSuite with error: getRepository returned error or empty body:AIAScience/MLSuite
  - Failed to update resource: 82675, with error: Failed to fetch data for AIAScience/MLSuite with error: getRepository returned error or empty body:AIAScience/MLSuite
  - Failed to update resource: 82674, with error: Failed to fetch data for AIAScience/MLSuite with error: getRepository returned error or empty body:AIAScience/MLSuite
```

Not sure how to proceed from this error message. Sample resource definition from the `shippable.yml` file.

```
  - name: mlsuite-built-github
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: AIAScience/MLSuite
      branch: master
      buildOnCommit: false
```

**Comment by a-murphy** [comment]
It looks like the account integration linked to the "github" subscription integration doesn't have access to that project.  If the integration belongs to an account that should have access, you can ask that user to click the "sync" button on the account profile page.  Or you can update the subscription integration to use a different account or add a new subscription integration.

**Comment by oyving** [comment]
Yeah, I noticed the same thing and fixed it. Thanks!

Would have been nice with a better hint from the error message.

**Comment by manishas** [comment]
We're improving error handling for integrations, so this is already on our radar. Closing this issue since the original problem was resolved.
