### ISSUE TITLE
Enable "ldap" PHP extension

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4469]
One of our PHP projects uses a package which requires the `ldap` PHP extension so we added it to the according Composer manifest. However, it seems that the `ldap` PHP extension is not installed by default in the Shippable PHP build images.

We already have a setup which catches this and automatically [installs extensions via Pickle](http://docs.shippable.com/ci/php-continuous-integration/#installing-extensions) but this fails:

```
pickle install --ansi ldap
  - Installing ldap (latest-stable):
  Downloading (connecting...)
  Downloading (0%)
  Downloading (failed)
                                                                                             
  [Composer\Downloader\TransportException]                                                   
  The "https://pecl.php.net/get/ldap" file could not be downloaded (HTTP/1.0 404 Not Found)  
                                                                                             

install [--no-convert] [--defaults] [--source] [--with-configure-options WITH-CONFIGURE-OPTIONS] [--save-logs SAVE-LOGS] [--dry-run] [--php PHP] [--ini INI] [--tmp-dir TMP-DIR] [--] [<path>]
```

In #1546 it was suggested to install the extension via APT and while this basically works it seems like it is installed for the system-wide PHP environment, not the one prepared by `phpenv` since again our fallback to Pickle kicks in which indicates that the `ldap` extension is not loaded.

You can see this e.g. in build 8 of project `5af2d405d4612c0600baa5a4`.

How should we enable the `ldap` PHP extension to be available in our builds?

**Comment by trriplejay** [comment]
we're investigating this.

**Comment by manishas** [comment]
@trriplejay can you post an update to this issue?

**Comment by trriplejay** [comment]
I haven't found a decent workaround, I think we'll have to build it into the php base image like we did for a similar previous issue https://github.com/Shippable/support/issues/2846

I'll add this to our todo list for next drydock release.

**Comment by vijayreddy1991** [comment]
This issue got fixed, now php ldap is available in v6.8.4 later.

**Comment by mbrodala** [comment]
@vijayreddy1991 Thanks for the hint, we'll check our builds. It would be great if such changes also where mentioned in the Shippable changelog.

**Comment by mbrodala** [comment]
We just tried and it seems like `ldap` is not installed after all. See build 87 of project `5af2d405d4612c0600baa5a4`:

```
composer install --no-progress --ansi
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for causal/ig_ldap_sso_auth 3.4.x-dev -> satisfiable by causal/ig_ldap_sso_auth[3.4.x-dev].
    - causal/ig_ldap_sso_auth 3.4.x-dev requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
  Problem 2
    - Installation request for causal/ig_ldap_sso_auth dev-master -> satisfiable by causal/ig_ldap_sso_auth[dev-master].
    - causal/ig_ldap_sso_auth dev-master requires ext-ldap * -> the requested PHP extension ldap is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /root/.phpenv/versions/7.2/etc/php.ini
    - /root/.phpenv/versions/7.2/etc/conf.d/xdebug.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by trriplejay** [comment]
@mbrodala while the package did get installed in the base image, it was not added to the php configuration... This should be corrected in the next drydock release scheduled for the end of October. Sorry for the delay!

**Comment by mbrodala** [comment]
With version 6.10.4 the `ldap` extension is now finally really installed. Thanks for the fix!
