### ISSUE TITLE
Node sizes in the documentation

### ISSUE THREAD

**Issue by aurelien-reeves** [Shippable/support#4470]
Hi,

What is the exact RAM size of on demand nodes?

If I take a look in your documentation here: http://docs.shippable.com/platform/runtime/nodes/ it says:

>     2 core, 7.5GB RAM (L)(default)
>     4 core, 15GB RAM (XL)
>     8 core, 30GB RAM (2XL)

But it seems to be the half actually!?

**Comment by manishas** [comment]
We are in the process of moving all customers to those node sizes. 

Your subscription might not be migrated yet, in which case you will have a 2 core 4gb machine for the L tier.

**Comment by aurelien-reeves** [comment]
Ok, great, thank you.
