### ISSUE TITLE
Github integration issue

### ISSUE THREAD

**Issue by RedLucas** [Shippable/support#4473]
My github integration seems to have broken and I don't know how to fix. I've checked  the permissions. I don't know what changed since yesterday but I don't have access anymore. Is there anything more that you can see on your end. From what I can tell everything is configured properly and the permissions are set appropriately as well. 

https://app.shippable.com/github/advisorwebsites/d8platform/runs/16523/1/console ... among others.

**Comment by trriplejay** [comment]
it's possible that the deploy key was deleted from github.  Can you try navigating to your project settings page, and click the "reset all keys" button near the bottom?  That should create a new deploy key.

![image](https://user-images.githubusercontent.com/6869398/43220856-f70b07fe-8fff-11e8-8035-a35286cb8132.png)

**Comment by RedLucas** [comment]
Yes, thank you! I wasn't 100% if that would fix it, didn't want to risk making matters worse and more complicated if that didn't fix it. 

Thanks for your help.
