### ISSUE TITLE
Cancel managed jobs

### ISSUE THREAD

**Issue by vinaganti** [Shippable/support#4474]
### Description of your issue: job is running since 2 hrs, can you please kill this job as we don't have that option and causing all other jobs queued up. 

Job Id: 732603

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
I've marked the stuck job as failed, and your queued jobs are being picked up now.

**Comment by vinaganti** [comment]
Thanks you John,

what options do i have to stop these kind of bad jobs in future to allow other jobs?

**Comment by trriplejay** [comment]
typically deploy jobs have their own internal timeout that should cause them to fail if they get stuck. This job had some unusual error that prevented that from happening. Unfortunately the best way to handle this kind of error today is to open a support ticket. We have cancellation support for managed jobs in our current backlog.

**Comment by manishas** [comment]
Feature request to cancel managed jobs will be tracked in https://github.com/Shippable/support/issues/3816

Please follow that issue for resolution.
