### ISSUE TITLE
Upgrade of node pool failed

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4475]
I tried to change the SKU and increase the number of nodes in our node pool through the billing page. However, that returned an error saying our existing node pool was still in use and could not be removed.

Now I am in a state where I can't provision the new nodes of the new SKU in the node pool setup, but the billing page shows you charged us and displays the correct number of nodes of the new SKU.

How can I start using what we paid for?

Customer: AIA Science
Transaction: gsxm98yk

**Comment by shrivara** [comment]
Sorry about the trouble. I've updated your subscription to reflect the billing update. Also, a new default node pool has been created to make use of the new licenses. All your new builds should be directed there. 

I'll open an internal ticket to handle this better.

**Comment by oyving** [comment]
Thank you for the quick response!
