### ISSUE TITLE
Lost free Node after changing plan

### ISSUE THREAD

**Issue by ghost** [Shippable/support#4478]
### Description of your issue:
Hi we lost our free node after changing our plan from ubuntu 14 to ubuntu 16
How can I bring it back?

- link to account: https://app.shippable.com/accounts/59c125465b955c0700b67895/dashboard

**Comment by trriplejay** [comment]
we're investigating.

**Comment by manishas** [comment]
@pat-nomalab You were locked into an old pricing plan which is no longer offered by Shippable. Any changes to the plan results in being switched over to the new pricing model which is described at https://www.shippable.com/pricing.html

The current pricing model offers a free node with restrictions for private repo builds. A $25 upgrade removes the restrictions on the free node, and subsequent nodes can also be purchased at $25/node.

**Comment by ghost** [comment]
So you telling that know paying $25 only remove the 150 build limit for private repo and if I want 2 concurrent jobs I have to pay $50??

**Comment by ghost** [comment]
I would like to cancel my subscription and go back to limited private repo, but I can't disable the option the checkbox is disable.

**Comment by ghost** [comment]
ok found it at the bottom of the page
