### ISSUE TITLE
Stage not set on cap deploy

### ISSUE THREAD

**Issue by TomasSjosten** [Shippable/support#4479]
I use Shippable togheter with Capistrano. I can run Capistrano locally and it deploys the app. When doing locally i trigger `cap demo deploy`. But I always get a mysterious error message, see image below. I set a variabel, TARGET, but when using it's like it's not set.

```
Stage not set, please call something such as 'cap production deploy', where production is a stage you have defined.
```

Failing on these scripts:

```
after_script:
   - echo $BRANCH
   - if [ "$BRANCH" == "stage" ]; then export TARGET="stage" ; fi
   - if [ "$BRANCH" == "demo" ]; then export TARGET="demo" ; fi
   - echo $TARGET
   - cap $TARGET deploy
```

Link to build: https://app.shippable.com/github/TomasSjosten/muddest/runs/1295/1/console

![image](https://user-images.githubusercontent.com/1782777/43465392-9049c978-94dd-11e8-9407-55ddcdafaa09.png)

**Comment by a-murphy** [comment]
Could you check that you have `demo` defined in your Capistrano config files and that the config has been committed and pushed to GitHub?  It looks like your other branches are working correctly and Capistrano just doesn't know what `demo` is.

**Comment by TomasSjosten** [comment]
Nice! It was driving me crazy, apparently someone had added gitignore on the config files.
