### ISSUE TITLE
No access to shippable runs on collaborator repo

### ISSUE THREAD

**Issue by tbach** [Shippable/support#4480]
### Description of your issue:
I am a collaborator on a private repo which is set up with Shippable. I have auth'd to Shippable with the related GitHub account, but I still can't see those repos in Shippable and clicking on run details from GitHub PRs takes me to a 404 within Shippable.

E.g. https://app.shippable.com/github/soby/appomni/runs/390/summary/console

**Comment by manishas** [comment]
Hello, can you check if you’re enabled private repos on Shippable?

Go to ‘profile’ in the left navbar and in the Git identities panel, both public and private should be checked for GitHub. If not, check private and go through the auth flow. You should also click on Sync after this. 

Let me know if you still don’t see the repo in Shippable after this.

**Comment by tbach** [comment]
Thanks @manishas that seems to solve it

**Comment by buckett** [comment]
We just had two people bump into this, it would be good if it was a little easier to resolve this without searching the support issues.
