### ISSUE TITLE
renaming .travis.yml to .shippable.yml does not trigger rSync job

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4482]
How to rename .travis.yml to .shippable.yml after I added an rSync job? 
Alternatively, is there a way to delete an rSync job?

**Comment by trriplejay** [comment]
normally rSync only runs when changes are made to a shippable.yml file.  It is possible that in the case of a pure rename, github reports it as a change to `.travis.yml`, and thus we don't trigger the job.  I would say that if you make an additional commit to the shippable.yml the rsync should trigger.

Alternatively, you can delete a sync job.  If you find your syncRepo->rSync job in the SPOG, and right click on the syncRepo, you should see a trash can icon.  This will soft-delete the sync job, sync repo, and any resources that it created.

Next, you'll have to look at your deleted resources, find the syncRepo or rSync job again, right click, and delete again.  This will fully delete the resources.  Then they can be added back via the normal UI workflow.
