### ISSUE TITLE
AWS Keys integration not working 

### ISSUE THREAD

**Issue by grohan2002** [Shippable/support#4488]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:
We did follow this tutorial to setup AWS infra using terraform and shippable https://github.com/devops-recipes/prov_aws_vpc_terraform
Although the aws key integration is set it fails stating it did not find the integration

- Link to the build failure
https://app.shippable.com/github/grohan2002/jobs/prov_aws_vpc_terraform_master_rSync/builds/5b694293ae04ed0600323ddd/console
- Scripts called from the yml (optional)

**Comment by Riturajcse** [comment]
Hey @grohan2002, seems you haven't tried running the rSync job after you updated the integration. Could you please run it again?

**Comment by grohan2002** [comment]
@Riturajcse Hey it worked the Access Credentials were wrong , I have a new issue 
https://app.shippable.com/github/grohan2002/prov_aws_ec2_terraform/dashboard

Even though we have type: runSh jobs the Job runs as runCI , can you please check

**Comment by Riturajcse** [comment]
@grohan2002 I guess you have enabled `prov_aws_ec2_terraform` for CI, instead, you should be adding this as an assembly line ( using the + button in the right [here](https://app.shippable.com/subs/github/grohan2002/enable)). 
You should also turn off the `enable CI` toggle for  `prov_aws_ec2_terraform`.
Here are the [docs](http://docs.shippable.com/platform/tutorial/workflow/add-assembly-line/#adding-an-assembly-line-to-shippable) for adding assembly lines.

**Comment by grohan2002** [comment]
@Riturajcse  I have Enable CI for a repo prov_aws_vpc_terraform  and it works fine and uses runSH, however if i disable CI they repo get greyed out and i am not able to check any builds for it. The rsync for the ec2 repo did run now .

**Comment by Riturajcse** [comment]
@grohan2002 Enabling Ci is not required while you are adding assembly line. I can see you have some errors in your rSync job [here](https://app.shippable.com/github/grohan2002/jobs/prov_aws_ec2_terraform_master_rSync/builds/5b696c34312b3a07004b903a/console) , so if you fix these errors you should be able to see your `runSh` job and run it.
