### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by jakub-kmiotek-synerise** [Shippable/support#4489]
Hey I'm not able to create account for bitbucket account, I've got error message  "account blocked".
my account id: 
`jakub-kmiotek-synerise`

Can you help?

**Comment by rageshkrishna** [comment]
Hi @jakub-kmiotek-synerise. I've unblocked your account. Sorry for the trouble. You should be able to log in now.

**Comment by rageshkrishna** [comment]
It looks like you were able to log in successfully. Closing the issue.
