### ISSUE TITLE
Accout blocked

### ISSUE THREAD

**Issue by ghost** [Shippable/support#4490]
Hi, 
I'm unable to log into shippable because my account (https://github.com/CICDtestlumapps) seems to violate your security policy.

Indeed it is a brand new github account as I want to test various CI/CD solutions without sharing all my company code.

Would you mind unlock it ?

**Comment by rageshkrishna** [comment]
@CICDtestlumapps your account has been unblocked. You should be able to login now.

**Comment by manishas** [comment]
@CICDtestlumapps please let us know if you need any help with config. Always happy to jump on a call and answer questions as well.

**Comment by ghost** [comment]
I can login with success now. Thank you.
