### ISSUE TITLE
GitHub integration doesn't queue builds on new commits

### ISSUE THREAD

**Issue by immerrr** [Shippable/support#4491]
It has happened few times during the last week, and as of now it affects at least one repository in our project.

According to GitHub integration screen, the payloads are being sent and return HTTP 200 OK with 
```
{"message":"Queuing run"}
```
body, but nothing happens and the pull request page is blocked on the following status:
```
Shippable Expected — Waiting for status to be reported
```

Here's some information for you to cross-reference with the logs from GH:
```
Request URL: https://{USER}:{PASS}@api.shippable.com/projects/5ac638e654f7fe0700529a16/newBuild
Request method: POST
Authorization: ********
content-type: application/x-www-form-urlencoded
Expect: 
User-Agent: GitHub-Hookshot/4f5b68a
X-GitHub-Delivery: ba8f8e60-9a33-11e8-8b51-5954b6691721
X-GitHub-Event: pull_request
```

**Comment by immerrr** [comment]
Regarding your latest update on the status page,

> Currently its affecting runSh jobs only. runCI jobs should be running normally.

I don't think this is true.

**Comment by rageshkrishna** [comment]
@immerrr Sorry for the delayed response. We've identified that the issue affects subscriptions with a subscription integration that is no longer linked to an account integrations. We are rolling out a fix for this at the highest priority. If it is an option for you, deleting the unusable subscription integration will immediately unblock you.

**Comment by immerrr** [comment]
hi @rageshkrishna 

thank you for the reply. I've deleted two subscriptions that no longer had an account integration linked and tried redelivering a github webhook payload, but still nothing happened.

**Comment by rageshkrishna** [comment]
@immerrr We have deployed a fix. Can you try once again?

**Comment by immerrr** [comment]
@rageshkrishna , yep, it works now, but only with different commits. That is, if I try to redeliver a payload that was already sent to shippable it looks like nothing happens (maybe some deduplication on your side), but if I rewrite the same commit so that it gets a different hash, it works.
