### ISSUE TITLE
Build failing - Error 504

### ISSUE THREAD

**Issue by atulkumarpundhir** [Shippable/support#4493]
### Description of your issue:

My build was running till yesterday but today I am getting following error.

{"logType":"error","methodName":"projects|triggerNewBuildRequest|projectId:5b338feb2d59e9070065a3a3|_queueRun","id":1005,"message":"postRun for :projectId 5b338feb2d59e9070065a3a3 returned error: POST /runs? returned 504"}

**Comment by rageshkrishna** [comment]
@atulkumarpundhir We've identified an issue that affects subscriptions with subscription integrations that are no longer linked to account integrations. We are working on deploying a fix for this right now.

**Comment by rageshkrishna** [comment]
@atulkumarpundhir A fix was deployed on the same day, so I'm going to close this issue now. Feel free to reopen if you are still running in to this.
