### ISSUE TITLE
Ruby caching broken on v6.7.4

### ISSUE THREAD

**Issue by allanyung** [Shippable/support#4494]
I upgraded the base image to 6.7.4 (in order to fix #4297) but in doing so suddenly the build fails when creating the cache of the gems.

https://app.shippable.com/github/ImmersiveLabsUkOrg/immersive-labs-api/runs/258/1/console
With ruby 2.4.1 the debug logs complain about ruby 2.4.2 being required, though this appears to be a red herring
```
cache
Required ruby-2.4.2 is not installed.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
Required ruby-2.4.2 is not installed.
Could not connect to Redis at 127.0.0.1:6379: Connection refused
tar -czf /home/shippable/cache/buildCache.tar.gz /usr/local/rvm/gems/ruby-2.4.1
```

https://app.shippable.com/github/ImmersiveLabsUkOrg/immersive-labs-api/runs/260/1/console
With ruby 2.4.2 the debug logs complain about connections to mysql and redis, which should be unrelated to caching?
```
cache
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
Could not connect to Redis at 127.0.0.1:6379: Connection refused
tar -czf /home/shippable/cache/buildCache.tar.gz /usr/local/rvm/gems/ruby-2.4.2
```

https://app.shippable.com/github/ImmersiveLabsUkOrg/immersive-labs-api/runs/250/1/console
It also appears that the tar command has lost some of the paths, which may or may not be related. Below is the log from a previous run on the older 6.1.4 image.
```
cache
tar -czf /home/shippable/cache/buildCache.tar.gz /usr/local/rvm/gems/ruby-2.4.4/gems /usr/local/rvm/gems/ruby-2.4.4/specifications /root/src/github.com/ImmersiveLabsUkOrg/immersive-labs-api
tar: Removing leading `/' from member names
```

**Comment by ric03uec** [comment]
@allanyung we're investigating this. 
- the error about mysql and redis seems to be unrelated to caching. we did fix a few bugs in caching workflows but no changes were made in any of the recent releases that affected any of the services.

**Comment by manishas** [comment]
@ric03uec can you post an update for this issue and close?

**Comment by ric03uec** [comment]
we've fixed the bugs in the caching workflow that were causing errors in `tar` command(s).
 
mysql and redis issues mentioned in the build seem to be unrelated since we've been able to test both these services successfully and other builds using same services are not showing any similar problems.

closing this issue, feel free to reopen if the problem still persists.
