### ISSUE TITLE
Pem-Key Integration Failing 

### ISSUE THREAD

**Issue by sanster23** [Shippable/support#4497]
I had an integration of type Pem-Key and its being used in the terraform scripts.

When I am trying to give the integration permissions of the git repo. 
It fails saying that 
**subscriptionIntegrations.create failed with error: Validation error**

Also even if the pem-key loads the build fails saying:
* aws_instance.openldap-master: Failed to read key "-----BEGIN RSA PRIVATE KEY----- **KEY** -----END RSA PRIVATE KEY-----\n": no key found

The link for the build : 
https://app.shippable.com/github/sanster23/jobs/prov_aws_ec2_openvpn_ldap/builds/5b6ad16f83b5800700a56605/version

**Comment by trriplejay** [comment]
This validation error occurs when you try to create a subscription integration with the same name as one that already exists.  This can happen when you create both (by adding an account integration, and granting permission to a particular subscription), and then delete the account integration.  The subscription integration is left behind.  Then if you try to create a new account integration again, but give it the same name, it will already exist on the sub from before.

If you navigate to your subscription dashboard, and go to settings -> integrations, you should see the integration listed there with a warning sign next to its name:

![image](https://user-images.githubusercontent.com/6869398/43851905-c99d4204-9af0-11e8-954e-69a534ec7722.png)

click on its name to edit the integration, then select the correct item from the "Account Integration" dropdown box.  This will associate your newly created account integration with your existing subint, and your job should be able to access the key again.

let me know if you have any questions.

**Comment by sanster23** [comment]
Thanks, this worked. 
But i am stuck on the second issue still 
This is an excerpt from my shippable.yaml

            - export PUBLIC_SSH_KEY=$(shipctl get_integration_resource_field aws_ec2_ldap_tf_ssh "key")
            - shipctl copy_file_from_resource_state aws_ec2_ldap_tf_state terraform.tfstate .

            - echo $PUBLIC_SSH_KEY
            - export PEM_KEY_PATH="/tmp/pem_key.pem"
            - echo $PUBLIC_SSH_KEY >> $PEM_KEY_PATH
            - cat $PEM_KEY_PATH
            - chmod 400 $PEM_KEY_PATH

But when i try to use the pem **file** or the value directly into the **$PUBLIC_SSH_KEY**  in my terraform script, it fails saying this:

aws_instance.openldap-master: Failed to read key "-----BEGIN RSA PRIVATE KEY----- KEY -----END RSA PRIVATE KEY-----\n": no key found

Failed to read key "${file(\"/tmp/pem_key.pem\")}": no key found

Is this a shippable side issue or on my side?

**Comment by trriplejay** [comment]
I'm not seeing any obvious error in what you're doing. Is there some issue with how the path is specified in the terraform script? I see your most recent jobs have succeeded, did you figure out the issue?

**Comment by sanster23** [comment]
The jobs succeeded because I had to upload the actual pem key file in the Git repo for shippable to pull.

Like this : ** private_key = "${file("${path.module}/files/ldap_test_punchh.pem")}" **

If i use the key file through integration it fails.

I have also checked a few other issues related to terraform version and syntax (https://github.com/hashicorp/terraform/issues/8963), I am not able to figure it out

**Comment by rageshkrishna** [comment]
@sanster23 I think your problem is because the PEM key's newlines might be getting mangled when you try to get the "key" and pipe it to a file.

The key file is actually already available for you to use directly. Here's what you can do instead:

````yaml
- cp $AWS_EC2_LDAP_TF_SSH_KEYPATH $PEM_KEY_PATH
````

I hope this helps.

**Comment by sanster23** [comment]
I just tried this it still failed with the same error 
Changes made 
ec2privatekey="${AWS_EC2_LDAP_TF_SSH_KEYPATH}"

private_key  = "${var.ec2privatekey}"

Error:
* aws_instance.openldap-master: Failed to read key "/var/lib/shippable/build/IN/aws_ec2_ldap_tf_ssh/aws_ec2_ldap_tf_ssh_key.pem": no key found

**Comment by rageshkrishna** [comment]
I'm not a terraform expert and I haven't actually tried this myself, but shouldn't it be `private_key = "${file(var.ec2privatekey)}"`

**Comment by sanster23** [comment]
@rageshkrishna silly mistake this one 
apologies 
and this solved the issues, Thanks a bunch man :+1:
