### ISSUE TITLE
Newest commits are not showing up in Shippable. I've clicked the sync repos button.

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#4499]
### Description of your issue:
Newest commits are not showing up in Shippable. I've clicked the sync repos button.

- Link to the build failure
https://app.shippable.com/bitbucket/bncompass/compass_frontend/runs?branchName=master

**Comment by a-murphy** [comment]
It looks like someone has disabled webhooks for the project.  To re-enable webhook builds, you can click on the project name in the breadcrumb at the top of the page and then the gears in the top right for settings.  The webhook toggle is at the top of the settings page; green is enabled with builds created for webhooks received and red is disabled.

Alternatively, if you want to run the newest commit manually, you can trigger a build from the play button in the top right of the project dashboard.

**Comment by pwarnock** [comment]
Thanks. The global sync button didn't refresh it, but the sync button on the page after I toggled that switch did.
