### ISSUE TITLE
[Consolidated Feature request] Support for additional source control providers

### ISSUE THREAD

**Issue by voanhduy1512** [Shippable/support#45]
Is Shippable supported custom git server (Gitalb) or will be supported in near feature?

**Comment by JHKennedy4** [comment]
Would love stash support. Would definitely help with selling shippable internally.

**Comment by vkuusk** [comment]
+1 for Stash support !
(we can not mirror to github for security reasons)

**Comment by mathieumg** [comment]
+1 for Stash as well. :+1:

**Comment by vkuusk** [comment]
@manishas @avinci Do you have a timeline for implementation of stash support. The reason I'm asking because we have to make a decision what to choose to build our unified CI/CD pipeline:  Shippable or Jenkins.
1. We have shippable "custom node" (dedicated host) inside our internal network which performs deployments
2. We have many engineering projects in Stash, which is also inside the our corp network.

Is there a short term solution (workaround)  to use shippable with Stash, which does not involve copying/syncing the whole repo from Stash to Github?
At least something like passing a stash repo name as a parameter to an API call to trigger Shippable project, so we can use a single project to git clone and test multiple stash repos.

Thanks

**Comment by abhi1010** [comment]
+1 for a generic HTTP webhook

I am using Shippable since a long time now but ever since I moved to my source code to Gitlab, the unavailability of this feature is hurting me the most.

Is there any timeline on this feature yet? I see we are talking about it for more than a year now.

**Comment by avinci** [comment]
@abhi1010 are you saying you need to call an external web hook from shippable? Also for folks who are on the thread, we just released Github Enterprise into beta and we are working on bitbucket server and Gitlab to be released shortly..

**Comment by abhi1010** [comment]
@avinci I think my line was confusing there. I actually meant that there should be a way to add build support for any git clone URL. For example, if `Shippable` can allow me to support build for any project just by me providing the public URL, then that's the best perhaps. Here could be one example. 

    git@gitlab.com:abhipandey/abhiscripts.git

**Comment by sandermarechal** [comment]
@avinci The other way around. Some external service does a HTTP POST to shippable to trigger the build. Like @abhi1010 suggest, all Shippable would need is provide a public SSH key, and a way for us to enter a (public) URL to a git repository. Example workflow:

1. On my Shippable account page there should be a public SSH key that Shippable uses to connect to external git servers.
2. I copy that key and put it in (Beanstalk/Gitlab/.ssh/authorized_keys/whatever)
3. I add a new repository in Shippable by prividing the URL (e.g. `git@mycompany.beanstalkapp.com/project.git`)

That's the basic setup. Now I should be able to trigger a build by doing a HTTP POST to http://shippable.com/some/url/for/my/project. Shippable can now clone my repository using the SSH private key and the git URL and run a build from that.

**Comment by tdaff** [comment]
Just wanted to register that there is still demand for mercurial support (with BitBucket).

**Comment by oppianmatt** [comment]
@sandermarechal doesn't the api let you trigger a build?

**Comment by keen99** [comment]
+1 for a webhook callback to trigger a build from any git repo (any git repo that you can configure post-commit hooks, anyway).  

ideally that callback could provide core setup for the project, too, so it could create a new one OR trigger an existing one. :)   (ie, include the project name and the URL path to pull from)

then all of this "we dont support your service of the week" would be turned into "we dont support it directly, but you can build it in..."

obviously providing API tokens, public ssh keys, and IP addresses to whitelist would still be needed.

**Comment by abhijitkini** [comment]
We are pleased to announce Shippable support for GitLab. Here's the [blog announcement](http://blog.shippable.com/getting-started-gitlab-with-shippable-ci). Our [docs](http://docs.shippable.com/int_scm/#gitlab) are updated too.

**Comment by abhijitkini** [comment]
Just to clarify - GitLab is available as an integration, so you will still need to sign in to Shippable with GitHub or Bitbucket and then add Gitlab repositories for CI.

Supporting GitLab auth is on our near term roadmap.

**Comment by keen99** [comment]
👍   sweet. :)

**Comment by sandermarechal** [comment]
@oppianmatt Seems like it (http://docs.shippable.com/api/#trigger-a-new-run) but a simple HTTP POST would be *much* better because almost all git hosting solutions support some kind of post-commit HTTP POST. That makes setting it up much easier.

@abhijitkini That's great to hear! Any plans for a generic web hook as well so that everyone can integrate with Shippable?

**Comment by abhijitkini** [comment]
@sandermarechal We evaluated this feature & have decided to defer it for now. We will prioritize it in our roadmap, if the demand for supporting generic git servers increases.

**Comment by cgreene** [comment]
+1 for mercurial support [from previous #136] - we have both types of repos in our organization and are looking for service providers that support both

**Comment by abhijitkini** [comment]
We now support Bitbucket server through an addon available in the Atlassian Marketplace. Docs are here: http://docs.shippable.com/ht_using_bitbucket_server/

**Comment by Korijn** [comment]
The company I work for is interested in this service, it supports literally everything we could possibly ask for (and is the only one), except for mercurial/hg. :disappointed:

So here's my :+1: for mercurial/hg support!

Are you guys open to (commercial) funding to add such a feature?

**Comment by manishas** [comment]
Closing this issue.

We now support the following scenarios:

Shippable Hosted:
- GitHub 
- Bitbucket
- GitHub enterprise (Sign with Github/Bitbucket)
- Bitbucket Server (Sign with Github/Bitbucket)
- Gitlab (Sign with Github/Bitbucket)

Shippable Server:
- GitHub Enterprise
- Bitbucket Server
- GitHub
- Bitbucket
- Gitlab (sign in with another auth provider)

**Comment by peerst** [comment]
Closing the Mercurial support issue because its duplicate and ignoring Mercurial completely here.
Does not make a good impression.  Moving on
