### ISSUE TITLE
Log says container was pushed, but I don't see it in ECR

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#4500]
### Description of your issue:
Log says container was pushed, but I don't see it in ECR

- Link to the build failure
https://app.shippable.com/bitbucket/bncompass/compass_frontend/runs/1186/1/console

**Comment by a-murphy** [comment]
Could you confirm that you are checking ECR in us-east-1 (N. Virginia), and that you intended to push the image to us-east-1?  You can switch regions in the AWS console in the second dropdown from the right at the top of the page, between your account name and "support."  The linked build appears to have pushed an image with tag `master.1186`.

**Comment by pwarnock** [comment]
My apologies. While the ECR interface does not show the two builds, I was able to pull from ECR via cli.
