### ISSUE TITLE
URGENT 

### ISSUE THREAD

**Issue by davidcervi** [Shippable/support#4503]

**Comment by davidcervi** [comment]
Hi guys,

Any update on this?

Thanks!

**Comment by davidcervi** [comment]
Hi guys,

Any update on whether this feature request has been accepted or not?

Thanks!

**Comment by manishas** [comment]
Hi David, This feature is in our backlog, and since it's not a common scenario, I'd like to get some more details on the requirements and some background on the organization. 

You can reach me at manisha@shippable.com and we can continue this over email.

**Comment by davidcervi** [comment]
Hi Manishas,

Cool sounds good.

Thanks,
David.
