### ISSUE TITLE
Logout after transition from app page to doc page

### ISSUE THREAD

**Issue by tigermax139** [Shippable/support#4504]
I can't read protect pages form documentation, after transition from https://app.shippable.com ( I am logged in, successfully ) to http://docs.shippable.com/deploy/amazon-ecs/ .
When i try 'sing in' on docs page i redirect to login page. After login throw github i redirect to  https://app.shippable.com and also can't read docs.
-----------------
Code of error
403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: E851E90FCC6A806C
HostId: O7ftmo7ERfC9vvflNazZw1xeWc9v2CpT5Qogqzhs/ZPW8iCiMP0ljfmpIKKUdmoMVY10z2i3F/g=
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: AccessDenied
Message: Access Denied

**Comment by a-murphy** [comment]
You shouldn't need to log in to Shippable to read documentation.  The login button is meant to be a convenient way to navigate to https://app.shippable.com.

The 403 message means that that page is no longer in that location.  Could you let us know what you are looking for?  Information about setting up a deploy job in Shippable Assembly Lines, including deployments to Amazon ECS, is [here](http://docs.shippable.com/deploy/deployment-methods-overview/).  Or an example of a deployment without using the deploy job is [also available](http://docs.shippable.com/deploy/deploy-amazon-ecs-cloud-native-cli/).
