### ISSUE TITLE
Shippable not running build (staying queued)

### ISSUE THREAD

**Issue by 0x63616c** [Shippable/support#4505]
Trying to get a branch to build and run the tests but it's just staying in the 'queued jobs' queue and not running.

https://app.shippable.com/github/findpace/prix-core/runs/1017/summary/console

**Comment by kjackson87** [comment]
Occurring for us as well 👍

**Comment by trriplejay** [comment]
One of our queues was temporarily backed up, but everything should be back to normal now.  Sorry for the inconvenience.  Let me know if your jobs still seem to be stuck.

**Comment by 0x63616c** [comment]
@trriplejay all good now, thanks!

**Comment by kjackson87** [comment]
@trriplejay looks good for us, is it possible in the future to have this info available on the status page?

**Comment by trriplejay** [comment]
note: the delay has returned. job are being processed but you may notice a delay before they start. we are continuing to investigate. (status page should reflect this now)

**Comment by aurelien-reeves** [comment]
Our queue is not processed right now.
The status page does not show any incident for the moment.

![image](https://user-images.githubusercontent.com/24386780/44096908-b9e6e73e-9fdc-11e8-8dd0-fbc560ece684.png)


Are there issues today?

Edit: it is processing now. It looks like our nodes was still working on something "invisible" on the dashboard. Still not now what it was working on but I saw the nodes in the node pools going from "processing" status to "success" whereas nothing was processing on the dashboard.

**Comment by manishas** [comment]
This has been resolved and patched in production. Closing.
