### ISSUE TITLE
URGENT - Builds are not getting triggerd

### ISSUE THREAD

**Issue by ankur--bhatia** [Shippable/support#4506]
### Description of your issue:
We are noticing that our jobs are getting queued up but they are not getting picked up by our nodes. 
We have 4 nodes and none of them are picking up the jobs. 
1. I have tried re-initializing the nodes. Did not work
2. restart of our nodes. Did not work

All jobs getting queued up here: 
<img width="971" alt="screen shot 2018-08-13 at 17 58 05" src="https://user-images.githubusercontent.com/907087/44046150-8645eaf2-9f22-11e8-874e-ed001c625bfa.png">

All nodes still inactive:
<img width="1033" alt="screen shot 2018-08-13 at 17 59 04" src="https://user-images.githubusercontent.com/907087/44046349-17b9884a-9f23-11e8-86f0-ccde8b7c5ea4.png">

https://app.shippable.com/github/hostmakerco/hostmaker-api/runs/12503/summary/console

**Comment by trriplejay** [comment]
One of our queues got backed up, but it should be back to normal now.  Are your jobs starting now?

**Comment by trriplejay** [comment]
note: the delay has returned. job are being processed but you may notice a delay before they start. we are continuing to investigate.

**Comment by manishas** [comment]
We have deployed a fix for this in prod, so this shouldn't happen anymore.
