### ISSUE TITLE
URGENT - pipeline sync job failed

### ISSUE THREAD

**Issue by ritch-parker** [Shippable/support#4508]
### Description of your issue:
a pipeline sync job has failed - and is blocking further updates

https://app.shippable.com/bitbucket/repomode/jobs/shippable-pipelines_master_rSync/builds/5b71d636f50d4207001b14c6/console

**Comment by trriplejay** [comment]
we've cancelled the stuck job and are looking into what happened. You should be able to re-run the job to pick up the latest changes.

**Comment by ritch-parker** [comment]
Ok, thanks.  We had another update in the queue that seems to have competed now.
