### ISSUE TITLE
My account has been blocked

### ISSUE THREAD

**Issue by pruthvireddypuresoftware** [Shippable/support#4510]
I am trying to login to shippable with my github account and i am getting error as account blocked.

![shippable_error](https://user-images.githubusercontent.com/42368140/44075885-f44dce22-9fbb-11e8-8ca7-01a2770b95d2.png)

**Comment by rageshkrishna** [comment]
@pruthvireddy1991 I have unblocked your account. Please log out and try logging in once more.

**Comment by pruthvireddypuresoftware** [comment]
@rageshkrishna Thank you so much
