### ISSUE TITLE
Unable to view subscriptions field in shippable landing page

### ISSUE THREAD

**Issue by pruthvireddypuresoftware** [Shippable/support#4511]
Unable to view subscriptions column field in shippable landing page.

Please suggest me what need to be done to view the same.

Thanks in advance.

**Comment by Bharath92** [comment]
Could you try clicking on the `Sync` button present in the `Account` -> `Profile` page?

**Comment by pruthvireddypuresoftware** [comment]
@Bharath92 Thank you so much. Now i can see after syncing.
