### ISSUE TITLE
Significant node CPU performance degradation 

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4512]
We have been experiencing a significant increase in execution time across all of our heavy CPU jobs.
The best show case is our cppcheck job (that does not execute our code)

```
| 32 | Success | Today at 4:15 AM | 3h 19m | nightly-trigger04 |  
| 31 | Success | Yesterday at 4:16 AM | 3h 18m | nightly-trigger04 |  
| 30 | Success | Last Sunday at 4:15 AM | 3h 16m | nightly-trigger04 |  
| 29 | Success | Last Saturday at 4:15 AM | 3h 19m | nightly-trigger04 |  
| 28 | Success | Last Friday at 8:13 PM | 3h 22m |
| 27 | Success | Last Friday at 4:15 AM | 3h 17m | nightly-trigger04 |  
| 26 | Success | Last Thursday at 4:15 AM | 52 minutes | nightly-trigger04 |  
| 25 | Success | Last Wednesday at 4:15 AM | 43 minutes | nightly-trigger04 |  
| 24 | Success | 08/07/2018 | 53 minutes | nightly-trigger04 |  
| 23 | Success | 08/06/2018 | 47 minutes | nightly-trigger04 |  
| 22 | Success | 08/05/2018 | 46 minutes | nightly-trigger04 |  
| 21 | Success | 08/04/2018 | 44 minutes | nightly-trigger04 |  
| 20 | Success | 08/03/2018 | 46 minutes | nightly-trigger04 |  
| 19 | Success | 08/02/2018 | 52 minutes | nightly-trigger04
```

It started when the node changed from
```
Total Memory: 3.676GiB
Name: ip-172-31-4-22
ID: 6UTB:P67M:JXLA:VODV:EGT6:CY6F:YHE2:NKI2:7IZS:WWSO:MJG4:KZID
```

to a slower one

```
Total Memory: 7.306GiB
Name: node-cecf869a
ID: XP7O:4TPI:GQR4:45XT:HTT7:C3SP:2LVE:OYZV:MBVD:JZ7Q:UNCE:6ZII
```
Information taken from `docker info` for jobs 26 and 27.

**Comment by manishas** [comment]
@vidiecan Thanks for reporting this. We are looking into this. In the meantime we have reverted your account back to the old node type, so you shouldn't see these slowdowns any more.

**Comment by vidiecan** [comment]
@manishas interestingly, it did not really help much

```
35 | Success | Today at 4:15 AM | 3h 3m | nightly-trigger04 |  
34 | Success | Yesterday at 8:35 AM | 3h 4m |  |  
33 | Success | Yesterday at 4:15 AM | 2h 38m | nightly-trigger04
```

**Comment by manishas** [comment]
Hmmm ok. Let me discuss with the team and get back to you. We might need your help in trying a couple of things.

**Comment by vidiecan** [comment]
@manishas ok

**Comment by vidiecan** [comment]
For the record, this particular task is running a docker image on our sources. On a several years old laptop the tasks takes 1h 7m to finish:

- Processor	Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz, 2401 Mhz, 2 Core(s), 4 Logical Processor(s)
- Installed Physical Memory (RAM)	8.00 GB

The execution time is similar to the times before the degradation.

**Comment by manishas** [comment]
@rageshkrishna can we look into this asap?

**Comment by rageshkrishna** [comment]
@vidiecan Is it alright if I trigger these jobs manually? There are some internal parameters that I would like to tweak and see how it affects your job's execution time, so it would be a lot easier if I could trigger them myself. I will probably be able to get back to you by Monday with some findings. 

Can you also drop me an email at ragesh@shippable.com? We might need to discuss specific details about your jobs. It would be better to do that in private. Thanks!

**Comment by vidiecan** [comment]
Fixed by @rageshkrishna
