### ISSUE TITLE
Requested for free shared license to run builds on 64 bit arm machines 

### ISSUE THREAD

**Issue by pruthvireddypuresoftware** [Shippable/support#4517]
I have requested for free shared license to run builds on 64 bit arm machines, but didn't get any response on the same.
Could you please provide me the same team.
Thanks.

**Comment by manishas** [comment]
@pruthvireddy1991 I just responded to you... your subscription has been enabled for the shared Arm pool. Let me know how it goes.

**Comment by pruthvireddypuresoftware** [comment]
@manishas Thank you so much
