### ISSUE TITLE
Unable to reach organization PyPi repo

### ISSUE THREAD

**Issue by oyving** [Shippable/support#4520]
We are timing out reaching our own PyPi repository from Shippable. The repo is globally available (not only on an internal network), and doing `pip3 install` against this repo used to work earlier.

I have verified that we can use the repository from our own machines.

**Comment by trriplejay** [comment]
We're investigating.  I see that two of your builds from this morning were able to download the repo successfully. Is this still a problem? or was it temporary?

**Comment by oyving** [comment]
I wrapped everything in `shippable_retry`, which seems to have solved it for now.
