### ISSUE TITLE
Accidentally deleted rSync ssh key(s)

### ISSUE THREAD

**Issue by vidiecan** [Shippable/support#4521]
Project Id: 548f3ff2d46935d5fbc03c6b
repo: c-image-to-text
all three c-image-to-text_*_rSync jobs
Based on the issue tracker, seems reset ssh key feature has not been implemented yet so I ask you to send me the public keys via email. Thank you

Suggestion: use different names for ssh keys so you a slightly bigger chance to not forget that rSync jobs are not triggered every day while deleting ssh keys that have not been used for some time.

**Comment by trriplejay** [comment]
I've sent an email with the keys to the technical contact address in the sub. sorry for the inconvenience! We're working on that reset feature, as well as consolidating keys for the same project, so you don't get one-per-enabled-branch for rSync.  Please reopen if you need something else.

**Comment by vidiecan** [comment]
thanks
