### ISSUE TITLE
Stalled deployment due to space

### ISSUE THREAD

**Issue by SpencerTranter** [Shippable/support#4524]
Deployment has stalled due to error:
`Failed to dir at path:/build/IN with err: Error: ENOSPC: no space left on device, mkdir '/build/IN'`

- https://app.shippable.com/github/formhero/jobs/smarties-deploy/builds/5b7f01afdfcdc60600078178/console

**Comment by a-murphy** [comment]
I've canceled that job so that you won't have to wait for it to time out while we look into it.  You should now be able to rerun the deploy job.

**Comment by neilouellette** [comment]
We are seeing the same thing.

https://app.shippable.com/bitbucket/mxitechnologies/jobs/lpa-document-deploy-staging-ecs/builds/5b7f0344dfcdc60600078392/console

**Comment by a-murphy** [comment]
I've canceled that one as well.

**Comment by neilouellette** [comment]
Thank you a-murphy.

**Comment by jefffleming** [comment]
I'm seeing this also.
https://app.shippable.com/bitbucket/jeff_fleming/jobs/webupdate-manifest/builds/5b84372ff50d42070027c38c/

Is this the same issue I hit 2 weeks ago? https://github.com/Shippable/support/issues/4509

**Comment by trriplejay** [comment]
Looks like a separate problem (from 4509), this one related to a  space issue on one of our service machines. I've removed your stuck job and resolved the space issue.  If you run it again manually it will operate properly.

**Comment by ric03uec** [comment]
we've fixed all our services that were having this issue. the jobs should run correctly now without running into out-of-space errors.
closing this
