### ISSUE TITLE
SPOG dashboard captions are unreadable

### ISSUE THREAD

**Issue by BryanCrotaz** [Shippable/support#4525]
![image](https://user-images.githubusercontent.com/2016523/44660246-fb6fde00-a9fe-11e8-9e51-3a0e46d8056f.png)

To read them I have to zoom all the way into an individual job which makes the pipeline view useless.

**Comment by rageshkrishna** [comment]
We've updated the "modern view" in the SPOG to use a cleaner font and better weights. This should look a lot better now. Feel free to re-open if you're still having trouble with this.
