### ISSUE TITLE
No cluster nodes available for new node pool

### ISSUE THREAD

**Issue by sdlarsen** [Shippable/support#4528]
Hi.
I've created a new node pool as we need more (and updated) builders. It seems to be stuck.

The Nodes section displays:
"No cluster nodes available for node pool dynamic__x86_64__Ubuntu_16_04__c4_xlarge."

Will it eventually be there or can I do something about it?

**Comment by Riturajcse** [comment]
Hey @sdlarsen `dynamic` nodes gets created automatically when you run a build, you should be able to see nodes added to your node pool when you will run a build.

Also  If you have not defined which node pool to choose in your Shippable ymls make sure you make your `dynamic__x86_64__Ubuntu_16_04__c4_xlarge` as default node pool.

Please refer our node pool [docs](http://docs.shippable.com/platform/management/subscription/node-pools/) if you need some more info.

**Comment by sdlarsen** [comment]
I have plenty builds queued up, that's why I'm wondering.
From tinkering, I see only builders from the default pool is used. I've reduced to one default pool and increased the size of that. It works. I wonder if that's the expected behaviour?

**Comment by Bharath92** [comment]
For nodes to be available on the nodepool:
- enable a project using the `+` button on your subscription dashboard
- the build can be triggered manually or by pushing a commit to the enabled project
- to run the builds, on-demands nodes will be created

Please confirm if you have done the above steps.

**Comment by sdlarsen** [comment]
You beat me to it. Yes, I've done the above steps. The only way I can get it to work is by only having one pool. The non-default pool is never used it seems.

**Comment by Bharath92** [comment]
could you please let us know the name of your subscription?

**Comment by sdlarsen** [comment]
@Bharath92 Sure, that would be uberresearch

**Comment by Bharath92** [comment]
Say you want to create a new nodepool and use it in your build, use
```
runtime:
  nodePool: #name of nodePool
```

By default, the nodePool which is default is used even though the runtime section is not specified in the yml.

For using a different nodepool in a CI build refer to the docs specified here 
- http://docs.shippable.com/ci/yml-structure/

For using a different nodepool in a runSh build refer to the docs specified here
- http://docs.shippable.com/platform/workflow/job/runsh/#yml-definition

Please check the `runtime` section in the above docs

**Comment by sdlarsen** [comment]
@Bharath92 Thanks, that explains what I see.
