### ISSUE TITLE
Job not triggering through time resource

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#4532]
The following build is not triggering on the time resource. I'm not sure why.

https://app.shippable.com/bitbucket/swisnl/laravel-nova-updater/runs/34/summary/

https://app.shippable.com/subs/bitbucket/swisnl/resources/updateNovaEvery4Hours/versions

**Comment by trriplejay** [comment]
we've found the issue and will be patching it shortly

**Comment by bbrala** [comment]
Awesome, thanks

**Comment by trriplejay** [comment]
This fix has been deployed now, and it looks like your 4 hour interval job was successfully triggered.  Let me know if you're still seeing any issues.

**Comment by bbrala** [comment]
Awesome, thanks
