### ISSUE TITLE
Can no longer view our builds/jobs/repos in shippable 

### ISSUE THREAD

**Issue by doc82** [Shippable/support#4533]
### Description of your issue:
Our github repo disappeared from our dashboard! We get 404s whenever we try to view our builds/jobs. Nothing has changed. 

- https://app.shippable.com/github/hyxus/hyxus-accounts/runs/258/summary/console

**Comment by trriplejay** [comment]
can you try going to the "profile" page and click the "sync" button?

**Comment by doc82** [comment]
@trriplejay You are a scholar and a saint sir. 

Panic attack mode over. We are good to go.

**Comment by trriplejay** [comment]
awesome, glad that fixed it!
