### ISSUE TITLE
Cypress support

### ISSUE THREAD

**Issue by raelgc** [Shippable/support#4535]
### Description of your issue:

Build: https://app.shippable.com/github/arizonabay/output/runs/8582

Actually I've wrote some tests using Cypress (which is a headless npm testing framework).

I've tried to follow their CI instructions: https://docs.cypress.io/guides/guides/continuous-integration.html

But my build stops after the `npm install`.

**Comment by trriplejay** [comment]
Could you try updating to the latest runtime version? 

On your subscription dashboard, go to settings -> node pools -> edit the default node pool -> select v6.7.4 from the runtime version drop-down -> save. 

Then try running the build again. Let me know if you still see the same issue.

**Comment by raelgc** [comment]
Ok, I've made this and now mysql refuse to start. I've reverted back to 5.8.

Build: https://app.shippable.com/github/arizonabay/output/runs/8592

**Comment by raelgc** [comment]
Probably it's related to Ubuntu 14.04. But I cannot find a way to change it. In the Noode Pools page, it was a disabled field.

**Comment by a-murphy** [comment]
Changing the node operating systems available in your subscription can be done in [subscription billing](http://docs.shippable.com/platform/management/subscription/billing/).  However, the container you are using to run your build is 16.04 in both cases, just running on a 14.04 node.  I haven't been able to reproduce an error in `mysql_start`.  Did you change anything else at the same time?  Or are there any unusual configuration files in your repository?

**Comment by raelgc** [comment]
I just reverted back to latest 5.8 to not block the team on deliverables. Anyway, I've found that if I redirect the `npm install` to `/dev/null`, it works. Appears that a long output for the `npm install` will fail the build.

Now, appears that I cannot install some packages required by `cypress` using `apt`. 

Can you, please, give any advice?

Build: https://app.shippable.com/github/arizonabay/output/runs/8615

**Comment by raelgc** [comment]
Nevermind, I've changed my configs to be `14.04` and run an `apt update` before install and it worked. Maybe we should use this as an example for cypress + shippable, as cypress is just the new hot UI automation framework.

**Comment by raelgc** [comment]
Just to share my recipe: http://raelcunha.com/2018/09/05/ui_testing_with_continuous_integration/

**Comment by trriplejay** [comment]
@raelgc glad it's working. nice tutorial!
