### ISSUE TITLE
Bitbucket build status not updating if latest build succeeds

### ISSUE THREAD

**Issue by AaronLuo3296** [Shippable/support#4536]
I met the same issue with https://github.com/Shippable/support/issues/3793, but I could't reopen that one, so I create a new issue.

Bitbucket server version I used: Atlassian Bitbucket v5.4.8

For every build, I called the bitbucket build status API to update status when the build is started and finished.
```
curl -u $BITBUCKET_KEY:$BITBUCKET_PASS -H "Content-Type: application/json" -X POST https://bitbucket.fqdn/rest/build-status/1.0/commits/${COMMIT_ID} -d "{ \"state\": \"$BUILD_RESULT\", \"key\": \"${BUILD_ID}\", \"name\": \"${BUILD_NUMBER}\", \"url\": \"${BUILD_URL}\", \"description\": \"built by $BUILD_CREATOR\" }"
```
The result of every build was what we expected, but the build status in Bitbucket dashboard was not updated when the latest build succeeded.

the result of every build:
![image](https://user-images.githubusercontent.com/14754431/44896391-6ee55880-ad3b-11e8-8e25-809a5f3b7108.png)

- build 50: I created a PR, build and test passed;
- build 51: I merged the PR, It will upload a package to my repository, but the version had existed in my repository, so it failed
- build 52: I removed the package from repository and rebuilt, it was successful
- build 53, I removed the package from repository again and rebuilt, it was successful

But the result of Bitbucket dashboard also showed error.
![image](https://user-images.githubusercontent.com/14754431/44896466-a18f5100-ad3b-11e8-9f89-7b6a0f212c32.png)

**Comment by a-murphy** [comment]
Since you're using `$BUILD_ID` for the `key` in the status, and the `$BUILD_ID` changes each run, Bitbucket will keep a status for each build.  If you want to only show the last status in Bitbucket, you'll have to use the same `key` every time you update the status.

**Comment by AaronLuo3296** [comment]
@a-murphy Thanks for your quick answer. 

Basically I want to show the last status in Bitbucket dashboard, but keep all status in Bitbucket server. That means it shows how many builds are there when I put the mouse pointer on the build status badge, and it pops up a window showing the details of every build when I click the badge it, which is the same as Jenkins integration with Bitbucket.

For example, the following two screen shots are build results from Jenkins.
(1) the result in Bitbucket dashboard
![bitbucket dashboard](https://user-images.githubusercontent.com/14754431/44963008-67f05d00-af6a-11e8-86d2-93319067dbd3.png)
(2) the details of builds
![builds status](https://user-images.githubusercontent.com/14754431/44963021-835b6800-af6a-11e8-9fb4-15fbf78dcbb6.png)


If I assigned the ```$COMMIT_ID``` to ```key``` (using the same ```key``` every time), only the last status was kept in Bitbucket, the previous builds were gone. 
```
curl -u $BITBUCKET_KEY:$BITBUCKET_PASS -H "Content-Type: application/json" -X POST https://bitbucket.fqdn/rest/build-status/1.0/commits/${COMMIT_ID} -d "{ \"state\": \"$BUILD_RESULT\", \"key\": \"${COMMIT_ID}\", \"name\": \"${BUILD_NUMBER}\", \"url\": \"${BUILD_URL}\", \"description\": \"built by $BUILD_CREATOR\" }"
```

Do you have any suggestion to implement what I expect to do? Thanks

**Comment by a-murphy** [comment]
The [Bitbucket documentation](https://developer.atlassian.com/server/bitbucket/how-tos/updating-build-status-for-commits/) suggests overwriting a commit status by using the same key if the overall status should no longer be failed.  I don't think it's possible to have a failed status in the list of builds and "success" appearing next to the commit.

The closest you would be likely to get to keeping the list of builds while not showing the failures would be to first get the list of statuses from the [Bitbucket API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Busername%7D/%7Brepo_slug%7D/commit/%7Bnode%7D/statuses) and then check for a failed status and reuse the key only if there is a failure.

**Comment by AaronLuo3296** [comment]
Thank you @a-murphy . I think I can close the ticket.
