### ISSUE TITLE
Not able to push to github

### ISSUE THREAD

**Issue by AgrawalRahul** [Shippable/support#4538]
### Description of your issue:
I am not able to push changes to github from shippable. It does not even give a log that build failed or something. Shippable shows everything is successful (shows the new commit) but I do not see any commit in https://github.com/AgrawalRahul/spin-kub-v2-demo.

- Scripts called from the yml (optional)
```
language: go

go:
  - 1.9

before_script:
  - git remote set-url origin git@github.com:AgrawalRahul/spin-kub-v2-demo.git
  - git config --get remote.origin.url

build:
  ci:
    - echo $BASE_BRANCH
    - echo $BRANCH
    - echo $GIT_TAG_NAME
    - echo $IS_RELEASE
    - if [[ "$GIT_TAG_NAME" == deploy* ]] ; then chmod +x deploy.sh && ./deploy.sh; fi;
    - echo "Done"
```

The deploy.sh is
```
touch terraform.tfstate
git log -n 5
git add terraform.tfstate
git commit -m "adding terraform state"
git push origin master
git log -n 5
```

**Comment by Bharath92** [comment]
Could you please share the build link?

**Comment by AgrawalRahul** [comment]
https://app.shippable.com/github/AgrawalRahul/spin-kub-v2-demo/runs/12/summary/console

I am working on it. I think deploy.sh is run when a tag starting with `deploy` keyword is pushed. So the branch becomes tag name instead of master. Which is causing this problem. Because if I do `git status`, it shows `HEAD is detached from

**Comment by AgrawalRahul** [comment]
Yes. I need to manually checkout the branch if I am doing build based on Tag Push. That was the issue. 
```
git checkout master
touch terraform.tfstate
git add terraform.tfstate
git commit -m "adding terraform state"
git push origin master
```

This works while
```
touch terraform.tfstate
git add terraform.tfstate
git commit -m "adding terraform state"
git push origin master
```
Does not work because if I trigger a build on tag push, the current branch is not `master`, instead it's detached.
