### ISSUE TITLE
Unable to log in using github account

### ISSUE THREAD

**Issue by LubaMiteva** [Shippable/support#4543]
Unable to log into shippable using github login. I have enabled 2-factor identification on github and consistently getting the message: 

"An error occured, please choose an action.
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

Going "home" just shows "account blocked".

**Comment by rageshkrishna** [comment]
@LubaMiteva Sorry about that. Our system to flag accounts for review sometimes hits false positives. I've unblocked your account. Please logout and back in. Thanks!

**Comment by LubaMiteva** [comment]
Able to log in now, thank you @rageshkrishna !
