### ISSUE TITLE
Docker arm64 builds?

### ISSUE THREAD

**Issue by jmreicha** [Shippable/support#4545]
I was wondering if it is possible to build Docker images against arm64 (and other) platforms alongside amd64 using Shippable?  Are there docs or an example somewhere for doing this?

**Comment by ssps12** [comment]
I have requested for arm license on shippable. Still I didn't get any response. Please let me know if I need to request in any other place.Thanks

**Comment by trriplejay** [comment]
@ssps12 we've processed your request and your subscription has been given permission to use the restricted aarch64 node pool.  You can continue following the instructions here: http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/#2-configure-your-yaml

**Comment by trriplejay** [comment]
@jmreicha typically you'd want to split this into separate jobs, and have one job assigned to an arm64 node pool while the other is assigned to the amd64 node pool. amd64 is the default architecture when you login to Shippable.  You can follow [this link](http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm) to request access to a shared Arm node pool.  In your job yml you can specify which node pool you want the job to run on.  Let me know if you have more questions.

**Comment by jmreicha** [comment]
@trriplejay Thanks.  So the machines in the arm64 node pool should be able to build Docker images natively then yeah?

**Comment by trriplejay** [comment]
yes, your build will run on an Arm host, inside an Arm-based docker container, which is configured to allow docker build commands.
