### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by ghost** [Shippable/support#4546]
### Description of your issue:

Trying to log in using whitlowc@cardiff.ac.uk, receiving the following error:

> An error occured, please choose an action.
> 
> Your account has been blocked as it was identified to be violating our security policy.
> Please contact support if you feel this is a mistake.

**Comment by rageshkrishna** [comment]
@CharlieChalk100 I've unblocked your account. You should be able to log in now.

**Comment by ghost** [comment]
yep that's done it, great thank you!
