### ISSUE TITLE
Build fails - AWS integration not functioning

### ISSUE THREAD

**Issue by sshen81** [Shippable/support#4548]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

We are experiencing failing builds after updating our integration in shippable.yml
https://app.shippable.com/bitbucket/vigorsystemsinc/vigor-image/runs/521/1/console

The build fails with the following output:

aws iam get-user
Unable to locate credentials. You can configure credentials by running "aws configure".

**Comment by a-murphy** [comment]
AWS integrations in the `generic` section are not automatically configured for use.

There are two easy ways to connect to AWS through the CLI from your CI job.  You can add the integration to the `hub` section with `type: ecr` as documented [here](http://docs.shippable.com/ci/push-amazon-ecr/) to automatically configure the AWS credentials.  Or you can use environment variables, either [secure environment variables](http://docs.shippable.com/ci/env-vars/#secure-variables) or a [key-value pair integration](http://docs.shippable.com/platform/integration/key-value/) in the `generic` section of `integrations`, to set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables the [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html) will use.

**Comment by sshen81** [comment]
The attempt to use the ECR type was attempted in this build. https://app.shippable.com/bitbucket/vigorsystemsinc/vigor-image/runs/519/1/console

However, it failed as we are not installing the awscli until the ci section of our build. ECR was therefore not able to initialize.

**Comment by a-murphy** [comment]
If the AWS CLI is not in your build image, Shippable cannot automatically configure the AWS credentials.  In this case, environment variables would be your best option.  Using the environment variables recognized by the AWS CLI should allow you to connect to AWS without any configuration commands once the CLI is installed.
