### ISSUE TITLE
Failure to login to shippable

### ISSUE THREAD

**Issue by gstewart-onevigor** [Shippable/support#4551]
Previously I used Bitbucket to authenticate with shippable.  My organization switch email addresses a while back and I needed to create a new Bitbucket account in order to be able to login.  Now, I am unable to login via Bitbucket to shippable.

The error message I receive is: 

"An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

I receive the above when I try to login via my new Bitbucket account.  Also, I tried logging in with a new GitHub account and received a 'account blocked' pop-up upon logging in.

Thanks!
Greg

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your accounts so you should be able to sign in.

**Comment by gstewart-onevigor** [comment]
Thanks!  Works now!
