### ISSUE TITLE
Service redis boot error, restarting...

### ISSUE THREAD

**Issue by Mateja94** [Shippable/support#4552]
redis_start can not start redis service. It prints "Service redis boot error, restarting..." over and over until it timeouts.

![selection_089](https://user-images.githubusercontent.com/33351174/45352669-4ff78980-b5b9-11e8-9234-01a0849a3059.png)

**Comment by a-murphy** [comment]
It looks like only one of the branches in your project is unable to start Redis, and the other branch starts Redis as expected.  There isn't any noticeable difference between the most successful and timed out runs other than the branch, so the failure is likely related to the branch.  Are there configuration files in the branch timing out that are not in the branch succeeding?  It's most likely that something added in the first pull request to time out (on 8/27) is related to the error.

Although I don't know what is causing the error, it's possible that switching to a newer build image with a more recent version of Redis may help. The versions of Redis available on the build images are [here](http://docs.shippable.com/platform/runtime/machine-image/services-versions/#redis) and directions to change the default image versions in your subscription [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).

**Comment by manishas** [comment]
@Mateja94 do you still need help with this?

**Comment by Mateja94** [comment]
@manishas No, we fixed it, thank you. Sorry, i forgot to close the issue.
