### ISSUE TITLE
Account blocked while logging in

### ISSUE THREAD

**Issue by prov-ShawnChambless** [Shippable/support#4554]
I was attempting to grant additional scopes to Shippable on my second login, and my account was blocked. Looks like the same issue as #4243.
![screen shot 2018-09-11 at 3 15 21 pm](https://user-images.githubusercontent.com/43181270/45390835-8511d500-b5d5-11e8-81c4-978ae9ef9834.png)

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by provPaulBrousseau** [comment]
Not to say "me too", but... "me too".

**Comment by a-murphy** [comment]
I've just unflagged your account as well.

**Comment by provPaulBrousseau** [comment]
Thank you; problem resolved!

**Comment by prov-paul-nathan** [comment]
@a-murphy Hi there! Me too!

**Comment by a-murphy** [comment]
Your account is now unflagged, too.

**Comment by provsweeney** [comment]
@a-murphy Hi there - me too!

**Comment by a-murphy** [comment]
Your account is unflagged now.
