### ISSUE TITLE
Documentation links lead to 403

### ISSUE THREAD

**Issue by cbliard** [Shippable/support#4555]
### Description of your issue:

On http://blog.shippable.com/notifying-ci-failure/success-status-on-email-slack at the end of the page there are links to HipChat and IRC integrations. They both lead to 403 Forbidden error pages. Links are:
  - IRC: http://docs.shippable.com/int_notifications/#irc-notifications
  - http://docs.shippable.com/int_notifications/#hipchat-notifications

**Comment by a-murphy** [comment]
Thank you for letting us know.  The correct links are [Hipchat](http://docs.shippable.com/ci/hipchat-notifications/) and [IRC](http://docs.shippable.com/ci/irc-notifications/).

**Comment by ric03uec** [comment]
this is fixed, closing
