### ISSUE TITLE
Creating Slack integration - What does "Edit permissions" means?

### ISSUE THREAD

**Issue by cbliard** [Shippable/support#4556]
Hello there,

I'm creating a slack integration. All fields make sense except for "Edit permissions". I can choose member, collaborator or admin. What do they refer to? I can't find this information in Slack.

Thanks

**Comment by ankul-shippable** [comment]
@cbliard 
We allow creating integrations at two levels: Account and Subscription

Account level integrations only you can edit and view.

Subscription level integrations are shared between all the subscription members, collaborators and admins. And, You can select whether members and collaborators can edit and view the credentials for these integrations using `Edit permissions`. By default, admins can edit and view credentials in these integrations.

**Comment by cbliard** [comment]
Thanks @ankul-shippable 👍 

That was not very clear from the UI.
