### ISSUE TITLE
aws-deploy job stoppped working and does not launch even manually

### ISSUE THREAD

**Issue by mikkopori** [Shippable/support#4557]
Hello,

any ideas what might have changed or be wrong?

https://app.shippable.com/github/mikkopori/jobs/deploy_aws/dashboard

yours,

Mikko

**Comment by manishas** [comment]
We're experiencing a service interruption: http://status.shippable.com/

**Comment by mikkopori** [comment]
Okay, hope you get this fixed soon. Thank you for the quick reply.
