### ISSUE TITLE
test in any branch, deploy only in master

### ISSUE THREAD

**Issue by juanpabloaj** [Shippable/support#456]
if I have many branchs,

how I can run the test in any branch and make deploy only in master branch ?

**Comment by oniltonmaciel** [comment]
WARNING
Note for google parachuters:

For Pull requests, shippable seems to also build branches as if they were merged with master.
So, for this builds you would have $BRANCH=="master" in the build, even if the code is not on master yet.

So the safest way to make sure you only deploy code when they are really in master is to check for PULL_REQUEST variable, like this:

    if [ "$BRANCH" == "master" -a "$PULL_REQUEST" == "false" ] ; then echo "Deploy to master"; fi
