### ISSUE TITLE
Job does not start

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4566]
Hi,

I am unable to start the job [80722](https://app.shippable.com/github/damejidlo/jobs/dj-mobile-beta-build/dashboard). I tried both API and SPOG GUI. The corresponding rSync job look OK.

Can you please fix the issue or give me advice what to do?

Thank you

**Comment by trriplejay** [comment]
@RadekDvorak it looks like your job still contains an IN for a git repo resource that no longer exists. This is likely why the job won't run.  The job should have been marked as inconsistent. we'll investigate why it wasn't, but you should be able to fix this by removing the bad gitRepo from the IN steps of this job.

**Comment by RadekDvorak** [comment]
Thank you!
