### ISSUE TITLE
Cannot re-initialize nodes

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4568]
Today I tried to re-initialize some of our nodes to v6.9.1 but after some time without output these failed:

```
 copy_script_remote
  echo 'Creating the private key file...' 0s  
  echo 'Establishing connection and copying files to remote host...' 0s  
Establishing connection and copying files to remote host...
ssh: connect to host <ip> port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
```

Could it be that the IP address of Shippable has changed and needs to be unlocked in firewalls?

**Comment by rageshkrishna** [comment]
Hi @mbrodala. We were forced to change it yesterday because BitBucket blocked us. The new IP is 52.70.242.32.

**Comment by mbrodala** [comment]
Thanks, after unlocking this in our firewall we could re-initialize our nodes again. It would be great if something like this was shown somewhere, e.g. http://status.shippable.com/.

**Comment by mbrodala** [comment]
@rageshkrishna Seems like Shippable has changed its IP address again, at least I see the same error again today when trying to update to the latest images:

```
Establishing connection and copying files to remote host...
ssh: connect to host <ip> port 22: Connection timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
```

Can you please tell me the new IP addresses of Shippable? And maybe create a docs page which always lists the latest IP addresses?

**Comment by rageshkrishna** [comment]
@mbrodala We haven't changed it since [my last comment](https://github.com/Shippable/support/issues/4568#issuecomment-423568167) on this issue. It's still `52.70.242.32`.

Point taken on the docs update for this. I'll make sure we add this info and link to it here.

**Comment by mbrodala** [comment]
Yes, apparently something is wrong with the node in question, I'll reset it. Thanks for having a look.
