### ISSUE TITLE
GitHub repo renamed now no longer appears even after syncing

### ISSUE THREAD

**Issue by 345paul** [Shippable/support#4571]
I had to rename a GitHub repo that was previously set up in Shippable and working.  After the rename, the repository won't appear in the list of repositories in order to enable it for CI.  I have tried clicking the Sync button many times, but it is not appearing at all.

Thinking it might be something that was still set on the repository in the GitHub settings, I manually removed the Shippable web hook and also the deployment key for Shippable, but still the repository won't appear in the list in order to enable it for CI.

**Comment by a-murphy** [comment]
Renamed projects should still be enabled after they are renamed.  Could you check if the project is listed on the subscription dashboard by clicking the name of the subscription containing your repository under "subscriptions" in the left sidebar on Shippable and looking for the new repository name in the first tab?  And, when you renamed the repository, did you also move it to a different organization or account (that can cause problems with some resources in the rename)?

**Comment by 345paul** [comment]
Hi, thanks for the quick response.

No, the project doesn't appear in the subscription dashboard in the Jobs tab.  The project hasn't moved organisation or account either.

**Comment by a-murphy** [comment]
It appears that the syncRepo part of your project had trouble updating the webhook when the name changed.  We'll let you know when it's fixed.

**Comment by 345paul** [comment]
Ok, thanks

**Comment by 345paul** [comment]
Just to let you know, I recreated the repo in GitHub and re-synced with Shippable to enable it so we are back up and running.
