### ISSUE TITLE
Deployment ordering

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4572]
Hello,

what is the order of deployments in deploy job with multiple manifests? How can I set the order manifests are deployed? I tried changing the order of IN clauses without success.

I tried to work around this with several linked deploy jobs. However previous deploy job is unfortunately added to the following job. I found no way to switch this behaviour off :-(

Could you please give me an advice?

**Comment by trriplejay** [comment]
hmm... they're supposed to be done in the order that they're listed in the yml IN steps.  If that is not the case, I will open a bug for this. 

Could you verify that in your deploy job logs, the IN steps are listed/processed in the proper order that you expect in the setup section of the script?

in the meantime, I think your idea of linking will work, but you'll unfortunately need to add a buffer runSh job in between each deploy job.  The runSh job will prevent the previous deploy job state from being added to the next deploy job.  

deployA -> runSh -> deploy B -> runSh -> deployC

We'll investigate the ordering issue.

**Comment by trriplejay** [comment]
ok, we've confirmed that the ordering of INs is not preserved in the managed deploy script. I've opened a bug, and we can let you know when it's scheduled for release.

**Comment by RadekDvorak** [comment]
Great. Could you please explain the ordering in deploy job documentation? I could not find it.

**Comment by trriplejay** [comment]
Once we've fixed this issue, we'll also update the documentation of the deploy job to explain the ordering.  At the moment I don't think there's a great explanation to offer :)

**Comment by a-murphy** [comment]
Manifests are now deployed in the order the `IN` steps are listed.  If there is another deploy job or a release job listed as an `IN`, those manifests will be deployed at the deploy or release job's position in `steps`.  This has also been added to the deploy job page in the documentation.
