### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by cbohiptest** [Shippable/support#4574]
I try to connect shippable.com with github (hiptest organization) login but I have an error : 
_Error
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake._

I try to revoke the shippable app from github and try to connect again, but it still does not work.

**Comment by Bharath92** [comment]
Your account is unflagged now. Could you please try again?

**Comment by cbohiptest** [comment]
It's ok.
Thanks.

**Comment by aurelien-reeves** [comment]
@Bharath92 just curious to know what happened?

**Comment by trriplejay** [comment]
New logins to Shippable will occasionally get flagged based on some checks we do to prevent abuse of the platform, however we do get some false positives, in which case opening a ticket here is the right action to take.

**Comment by PhilThom25** [comment]
Hi, I'm trying to login on my account but seems I've got same problem as other mates above. My account is blocked. Can I have access please (Hiptest)

**Comment by a-murphy** [comment]
@PhilThom25 I've unflagged your account and you should be able to log in now.
