### ISSUE TITLE
Unable to delete amazonKeys integration

### ISSUE THREAD

**Issue by 345paul** [Shippable/support#4575]
For some reason an amazonKeys integration we had created which had been set to 'all projects' permissions scope couldn't be accessed by a new project created in GitHub.  So, I tried to select the specific project in the permissions scope, but get this error when saving:

`getSubscriptionIntegrationById for id: 12980 returned error: subscriptionIntegration not found for :id 12980`

I then try and delete the integration:

`No access for subscriptionIntegration :id 12980`

We have created a new amazonKeys integration, but we are unable to do anything with the current one.

In GitHub, I'm the owner/admin of the organisation.  My colleague who is a member in GitHub but who is the owner of the integration in Shippable is unable to delete it either.

**Comment by a-murphy** [comment]
That integration had been set up so that only one project was allowed to use it, and that project was then (most likely) deleted on GitHub.  Since you did not have access to the deleted project, you couldn't edit or delete the integration.  Because the integration was unusable, I have deleted it.

**Comment by 345paul** [comment]
Ok thanks.

The project permissions scope was set to all projects, but maybe it wasn't originally.  The project that is would likely have been associated with was deleted (well, it was renamed, which caused another problem in Shippable, see issue https://github.com/Shippable/support/issues/4571) and we ended up having to delete and recreate the repo in GitHub for it to appear again in Shippable.  Seems that despite the project permissions scope setting, it must have been somehow associated with that deleted repo.

I'll close the issue.
