### ISSUE TITLE
Unable to drop old reqproc images

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4576]
We are unable to drop old `drydock/u16reqproc` images because they have the same image ID as the latest one:

```
docker image ls drydock/u16reqproc
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
drydock/u16reqproc   v6.8.4              403134fbd76a        2 weeks ago         1.92GB
drydock/u16reqproc   v6.9.1              403134fbd76a        2 weeks ago         1.92GB
drydock/u16reqproc   v6.9.4              403134fbd76a        2 weeks ago         1.92GB
```

How is this possible?

**Comment by rageshkrishna** [comment]
Changes in these releases did not require any updates to our reqProc service. As a result, they are all actually the same image with different tags. They do not take up any extra space as the layers are all shared.

If you really want to make them go away from the list you can do `docker rmi drydock/u16reqproc:v6.8.4 drydock/u16reqproc:v6.9.1`. This will un-tag them. It won't make any difference to your storage, though.

**Comment by mbrodala** [comment]
Thanks, that makes sense. I just free some space from time to time, if these images use the same space, it won't really matter.
