### ISSUE TITLE
Manually install nodejs

### ISSUE THREAD

**Issue by danielsuter** [Shippable/support#4577]
I use the oraclejdk8 image. Node 7.10. 0 also seems to be installed. I now require a later node version and tried to update and install it but failed. I always finds the old installation. Ways I tried so far:

Using nvm
> - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
 > - nvm install 8.12.0

Nvm can't be found, because it would need to restart the shell.

Install a later node version

>  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
>  - sudo apt-get install -y nodejs

It will still use the old version.

**Comment by trriplejay** [comment]
Could you provide a project ID or link to one of your builds?

our default java images should have nvm and node pre-installed, but it depends on how your subscription is configured, so it would help if we could take a closer look.

**Comment by danielsuter** [comment]
nvm try: https://app.shippable.com/bitbucket/Sanix/shinseikan-crm/runs/106/1/console

Installing node 8: https://app.shippable.com/bitbucket/Sanix/shinseikan-crm/runs/104/1/console

**Comment by a-murphy** [comment]
Your subscription has been configured to use a build image from June 2017.  The easiest solution would be to update that to a newer image that already has Node 8.12.0 installed.  For example, the default Java image in v6.9.4 has Node 8.12.0.  Then you won't need to manually install NodeJS.

To update to a newer default image, you can edit the node pool in your subscription as described [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).  The default build image versions used will match the "runtime version" selected.

**Comment by danielsuter** [comment]
Thanks that works. Now I have other issues but I will open a separate issue for that.
