### ISSUE TITLE
Gradle takes wrong jdk version

### ISSUE THREAD

**Issue by danielsuter** [Shippable/support#4582]
I set the version of the jdk to 8. This works if I check using java -v. But gradle will find a jdk 10 installation. How can I change this?

https://app.shippable.com/bitbucket/Sanix/shinseikan-crm/runs/116/1/console

<pre>
language: java
jdk:
- oraclejdk8

env:
  global:
  - APP_NAME=name
build:
  cache: true
  cache_dir_list:
  - ~/.gradle/caches
  - $SHIPPABLE_BUILD_DIR/client/node_modules
  - $SHIPPABLE_BUILD_DIR/frontend/node_modules
  - $SHIPPABLE_BUILD_DIR/.gradle

  pre_ci:
  - which heroku || wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

  ci:
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
  - chmod +x startServer.sh
  - java -version
  - ./gradlew -v
  - echo $JAVA_HOME
  - ./gradlew check
  - ./gradlew assemble
  - ./startServer.sh
  - ./gradlew e2e
  - cp -r backend/build/test-results/* shippable/testresults/
  - cp frontend/js-tests.xml shippable/testresults/js-tests.xml
  - cp -r frontend/test-results/* shippable/testresults/

after_success:
- if [ "$BRANCH" != "master" ] ; then ./gradlew deployHeroku ; fi
- if [ "$BRANCH" == "master" ] ; then ./gradlew deployHeroku -Pproduction ; fi
</pre>

**Comment by trriplejay** [comment]
Hello, this is a known issue that should be fixed in a future release.

For now, you can work around this by adding one extra line to the CI section of your yml:
```
- source shipctl jdk set oraclejdk8
```
this should set the requested JDK for both cases.

docs here: http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#jdk-set

**Comment by rageshkrishna** [comment]
This has been fixed in the v7.1.4 Java images. Please let us know if you're having trouble with the latest images.
