### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by yasithab-zone-zz** [Shippable/support#4585]
When I try to login to Shippable, I get the following error.

> Error
> An error occured, please choose an action.
> 
> Your account has been blocked as it was identified to be violating our security policy.
> Please contact support if you feel this is a mistake.

Revoked access from github and tried again, but the same thing keeps happening.

**Comment by rageshkrishna** [comment]
@yasithab-zone I've unblocked your account. You should be able to log in without any errors now.

**Comment by yasithab-zone-zz** [comment]
@rageshkrishna Great, it is working! Thanks a lot :)
