### ISSUE TITLE
My colleague could not login to shippable

### ISSUE THREAD

**Issue by WLimpens** [Shippable/support#4586]
My colleague can't log in into shippable. He is getting the following error:

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

His github account is Jurgen-Allewijn

**Comment by rageshkrishna** [comment]
@WLimpens I've unblocked the account. Please ask your colleague to try again. Thanks!

**Comment by WLimpens** [comment]
Sorry, for the late reply. It worked. Thanks!
