### ISSUE TITLE
Trying to run Alpine image but getting "You are not running Ubuntu" from build.sh

### ISSUE THREAD

**Issue by DeanHutchison** [Shippable/support#4587]
I am evaluating Shippable to become our new build pipeline but I am having issues getting our Alpine image working.

I have added all the required dependencies into my Dockerfile for my Alpine based image, but when shippable is running the container it is setting the entry point to build.sh which is causing the job to fail.

Is there an example of shippable.yml which uses an Alpine boot image ?

Here is my shippable.yml:

```
language: none

env:
  global:
    - SERVICE=base
    - IMAGE_TAG=15
    - REGISTRY_ACCOUNT=EXAMPLE.dkr.ecr.eu-west-1.amazonaws.com/gcs

build:

  pre_ci_boot:
    image_name: $REGISTRY_ACCOUNT/$SERVICE
    image_tag: $IMAGE_TAG
    pull: true
    options: "-e HOME=/root"
    
  ci:
    - echo "CI Step"
    
  post-ci:
    - echo "Post CI Step"

integrations:                 
  hub:
    - integrationName: gcs-aws-ecr
      type: ecr
      region: eu-west-1

```

Here is failure message in output from Console in Shippable:

```
sudo docker logs c.exec.gcsbasedockerimage.18.1 0s  
/home/shippable/cexec/build.sh: line 20: lsb_release: command not found
********************************************************************
*                           WARNING                                *
*                                                                  *
* You are not running Ubuntu. This configuration is not supported. *
*                                                                  *
********************************************************************
Looking for apt-get...
Could not find apt-get. Missing build system dependencies will not be automatically installed.
/home/shippable/cexec/build.sh: line 172: /home/shippable/cexec/dist/x86_64/linux/main/main: No such file or directory
```

Here is the Dockerfile which I am building my Docker Image (for use in the pre_ci_boot section above)

```
FROM alpine:3.7

ARG COMPOSER_VERSION=1.6.3

# Set system timezone
ENV TZ=Europe/London

RUN apk add -U \
    bash \
    bc \
    coreutils \
    curl \
    gawk \
    git \
    grep \
    jq \
    nginx \
    nodejs \
    nodejs-npm \
    openssh \
    php7 \
    php7-dev \
    php7-gd \
    php7-common \
    php7-apcu \
    php7-bcmath \
    php7-xmlwriter \
    php7-ctype \
    php7-curl \
    php7-exif \
    php7-iconv \
    php7-intl \
    php7-json \
    php7-mbstring \
    php7-opcache \
    php7-openssl \
    php7-pcntl \
    php7-pdo \
    php7-mysqlnd \
    php7-pdo_mysql \
    php7-pdo_pgsql \
    php7-phar \
    php7-posix \
    php7-session \
    php7-xml \
    php7-simplexml \
    php7-mcrypt \
    php7-xsl \
    php7-zip \
    php7-zlib \
    php7-dom \
    php7-redis \
    php7-fpm \
    php7-tokenizer \
    sed \
    sudo \
    supervisor \
    && export npm_config_user=65534 \
    && rm -rf /var/cache/apk/* \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer --version=${COMPOSER_VERSION} \
    && composer global require "hirak/prestissimo:0.3.7" \
    && adduser -D -g 'www' www \
    && mkdir -p /run/nginx \
    && mkdir -p /usr/share/nginx/cache \
    && mkdir -p /usr/share/nginx/fcgicache \
    && mkdir -p /etc/supervisor/conf.d \
    && mkdir -p /var/log/supervisor \
    && mkdir -p /var/log/nginx \
    && mkdir -p /var/log/php-fpm \
    && rm /etc/supervisord.conf \
    && rm /etc/nginx/conf.d/default.conf \
    && npm install npm@5.6.0 -g \
    && command -v node \
    && command -v npm \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone
    
```
From reading the support docs I added git, jq, sudo, bash, bc, coreutils, gawk and grep to the Dockerfile above. Unless I have missed something, I'm a bit stuck at how to progress from here. Any help would be much appreciated.

I have run the example yaml file from [here](https://github.com/devops-recipes/build_alpine_ci_image/blob/master/shippable.yml) and that works, but it is not using the Alpine image in the pre_ci_boot section, so I am not sure whether this is significant to my issue or not.

Update:

It appears that the error is when the [build.sh](https://github.com/Shippable/cexec/blob/master/build.sh) script tries to run [/home/shippable/cexec/dist/x86_64/linux/main/main](https://github.com/Shippable/cexec/blob/master/dist/x86_64/linux/main/main) and it gets a "No such file or directory" error.
I assume the file is there because in the build.sh script it checks for the presence of "main" before trying to execute it. The only reason I can think of for the "No such file or directory" error is that the "main" file is failing because of a missing [dependancy](https://superuser.com/a/1176328).

**Comment by sdlarsen** [comment]
Maybe add the packages mentioned here: http://docs.shippable.com/ci/custom-docker-image/ for when you don't have apt-get?

**Comment by DeanHutchison** [comment]
Hi @sdlarsen, I have already added those.

**Comment by trriplejay** [comment]
I think you're correct that there's some kind of missing library dependency. We'll investigate this and see if we can come up with an example workaround.

**Comment by trriplejay** [comment]
@DeanHutchison 
We do have an Alpine image that we've created to run on Shippable.  It installs some extra dependencies that I believe will avoid this library issue.

Here is the dockerfile:
https://github.com/devops-recipes/build_alpine_ci_image/blob/master/Dockerfile.alpine37

here is the install script that contains the extra packages:
https://github.com/devops-recipes/build_alpine_ci_image/blob/master/install.sh

Maybe you can take a look and let me know if this would be compatible with what you're trying to do.  The example just uses assembly line jobs, not CI, but the resulting Alpine image is also usable as a build image for CI jobs.

**Comment by DeanHutchison** [comment]
@trriplejay 

Thanks for the pointers to the Dockerfile and the install script. That has allowed me to get my own Dockerfile running correctly now.
