### ISSUE TITLE
Build fails with syntax error in /tmp/mexec/tmp-script.sh

### ISSUE THREAD

**Issue by sdlarsen** [Shippable/support#4589]
What we see is the following, using official python images as build image (we've done this for a long time, with no issues):
In Setup:

```
Cleaning up git configs
Validating script dependencies
the path is: /var/lib/shippable/build/cleanup_git_configs.sh
Successfully validated script dependencies
fatal: unable to read config file '/root/.gitconfig': No such file or directory
echo 'No global git configs found'
No global git configs found
```
And setup is reported to finish without errors (?)

Later on, in Debug:
```
Debug logs
ScriptType:setup_integrations|msg:/tmp/mexec/tmp-script.sh: line 319: syntax error near unexpected token `)'
```

And the build fails.
This happens with python:3.6.3 and python 3.7.0 (just tried the upgrade to see if it was the python version). We use both and haven't had issues before now.

The build: https://app.shippable.com/bitbucket/uberresearch/language_detection_batch/runs/5/1/console

**Comment by Bharath92** [comment]
As per the debug logs, the script is failing while setting up integrations. During the `setup_integrations` step, we login to docker. Has there been any changes in the credentials recently, like adding special characters? This might be messing up the docker login command.

**Comment by sdlarsen** [comment]
Yes the docker repo password was changed and contains special characters. As did the previous password. It seems that '(' in the password is not handled very well. I sincerely hope that you don't recommend passwords without special characters though.
For now I've changed the password to use "less special" characters. 
Thank you for getting back on this.

**Comment by trriplejay** [comment]
we've opened a ticket internally to ensure that any valid password will be equally valid on shippable.
