### ISSUE TITLE
macOS version support

### ISSUE THREAD

**Issue by mpaddle** [Shippable/support#4591]
The page on [macOS jobs](http://docs.shippable.com/platform/tutorial/workflow/jobs-macos/) mentions that I'd need a macOS 10.12 VM. Is 10.12 the only supported version of macOS? Which versions are actually supported?

For reference, I'm looking to use macOS 10.9.5 and the latest macOS (currently 10.14) as VMs.

**Comment by a-murphy** [comment]
Although the macOS initialization scripts have only been tested with 10.12, they will most likely work with other versions of macOS 10.
