### ISSUE TITLE
Builds fail with error in /tmp/mexec/tmp-script.sh

### ISSUE THREAD

**Issue by pkaminski** [Shippable/support#4595]
On Oct 6th between 9:37pm and 9:56pm PDT my build started failing ([first failure](https://app.shippable.com/github/Reviewable/reviewable-server/runs/1936/1/console)).  It looks like it doesn't even get to pulling the image and start building, instead failing right after "Job node info" with the "Debug" section saying:
```
ScriptType:collect_stats|msg:Identity added: /tmp/ssh/00_sub (/tmp/ssh/00_sub)
ScriptType:collect_stats|msg:Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
ScriptType:on_start_job_envs|msg:Identity added: /tmp/ssh/00_sub (/tmp/ssh/00_sub)
ScriptType:on_start_job_envs|msg:Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
ScriptType:on_start_job_envs|msg:/tmp/mexec/tmp-script.sh: line 402: unexpected EOF while looking for matching `''
```

AFAICT this is not a bug in my own script.  Can you advise?  Thanks.

**Comment by a-murphy** [comment]
This usually occurs when there is an unmatched single quote in an environment variable.  In this case, it looks like this started to occur at the same time that you added a new secure environment variable.  Could you try re-encrypting that environment variable (in case there was a typo when it was first encrypted)?  Subscription admins can also decrypt secure environment variables on the subscription settings page if you would prefer to instead check the value or no longer have the decrypted value.

**Comment by pkaminski** [comment]
Thanks, that makes sense -- I did add a new encrypted environment variable in that revision.  I used single quotes when defining it since the value has spaces inside but I guess that delimiter wasn't recognized.  I switched to double quotes and that seems to work better.  The string also has `\n`'s in it. 
 Can you confirm double quotes are right approach and the string will come out the other end unscathed?  Thanks.

**Comment by a-murphy** [comment]
Both single quotes and double quotes will work, with the `\n`s preserved.  It should only cause a problem parsing the resulting script if there are three (matching single or double) quote marks or only one quote mark.

**Comment by pkaminski** [comment]
Huh, guess it was a typo on my part then -- sorry for the noise.  😊  Would be nice if the UI validated env var syntax before encrypting, though.

Also tagging issue https://github.com/Shippable/support/issues/1774 since spaces in env vars are now clearly OK.
