### ISSUE TITLE
Can't re-enable project

### ISSUE THREAD

**Issue by nvmker** [Shippable/support#4597]
Hi,
I can't re-enable project:
deleteResourceById failed for id: 51287 returned error deleteVersionByResourceId for resourceId:51287 returned error: versions.destroy failed for resourceId: 51287 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"

**Comment by a-murphy** [comment]
Your project ended up with a duplicate, which caused some confusion.  I've deleted the duplicate and you should be able to see the already-enabled project now.  Let us know if you have any more problems.

**Comment by nvmker** [comment]
It works now, thanks!

**Comment by adinuca** [comment]
Hi @a-murphy, I have the same issue, although I do not think anybody disabled the project.
```
deleteResourceById failed for id: 72396 returned error deleteVersionByResourceId for resourceId:72396 returned error: versions.destroy failed for resourceId: 72396 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"
```

Should I raise another issue for it?

**Comment by a-murphy** [comment]
@adinuca Your project should be visible again now.  In future, I would suggest opening a new issue instead of commenting on a closed issue for a project in another subscription.  The response time is usually better on new issues than closed ones.

**Comment by adinuca** [comment]
Thank you! I will follow your suggestion next time. Have a nice weekend!
