### ISSUE TITLE
Unable to access organisation's Shippable projects.

### ISSUE THREAD

**Issue by QasimK** [Shippable/support#4598]
I am unable to access my organisation's Shippable projects. Specifically [this URL](https://app.shippable.com/github/findpace/prix-core/runs/1496/summary) 404s for me but works for other members of my organisation.

* I am part of [findpace](https://github.com/findpace/) with this GitHub account.
* I have logged into Shippable using this GitHub account.
* I have enabled private repo access (is this necessary though?)
* I can see `prod-shippable` under Authorised OAuth Apps in my GitHub settings.
* The organisation admin believes everything is set up on their side as far as they can see.

Are we missing something?

**Comment by deepikasl** [comment]
Hi @QasimK can you try `sync` your account once? 
Go to `Account` - `Profile` click on `Sync` button
![screenshot from 2018-10-10 18 53 20](https://user-images.githubusercontent.com/18304961/46739279-cc1ae500-ccbd-11e8-8f87-fda4d661f2e5.png)

**Comment by QasimK** [comment]
@deepikasl Yes, that worked. Thank you.
