### ISSUE TITLE
add OUT option to long exested RunCLI job gives - Missing dependency for job

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#4599]
I have an old RunCLI job and trying to expend the pipeline. 
as a results rSync job is failing with `Missing dependency for job`

**Comment by a-murphy** [comment]
It looks like your rSync job is now successful, so perhaps you've already figured it out.  The names of the missing resources can be found in the logs on the lines starting with `No resource exists for name`.  In this case, there are two resources named in the YML jobs that don't exist.

**Comment by depohmel** [comment]
It's successful because I've removed OUTs form jobs :)

**Comment by rageshkrishna** [comment]
@depohmel I'm not sure if this was fully resolved. Do you still need help with this?

**Comment by rageshkrishna** [comment]
@depohmel I'm going to close this issue as we haven't heard back from you in quite some time.

Feel free to reopen if you need more help with this.
