### ISSUE TITLE
Account problems

### ISSUE THREAD

**Issue by andye2004** [Shippable/support#4602]
One of our devs is having issues with his shippable account, when he logs in he can't see any of the organisations private repos and when he commits code to github the build is triggered but github then rejects an attempt from our build script to tag the just build branch.

The build that failed is this one https://app.shippable.com/github/yambay-tech/application-config-wp/runs/136/1/console, the user account details can be obtained from the build.

**Comment by rageshkrishna** [comment]
@andye2004 This user hasn't enabled access to private repos on GitHub. This can be done from the "Identities" panel in the "Account Profile" page on Shippable. Just click on the checkbox for "Private" GitHub repositories and follow the prompts.

**Comment by andye2004** [comment]
Thanks @rageshkrishna !

**Comment by yambaypaul** [comment]
Thanks @rageshkrishna . Sorted.
