### ISSUE TITLE
Shippable stopped getting updates from bitbucket

### ISSUE THREAD

**Issue by jefffleming** [Shippable/support#4604]
Shippable stopped getting updates from bitbucket.  Recent commits are not triggering the build process.  When I try manually building it uses the code from the earlier run.

**Comment by a-murphy** [comment]
It sounds like the webhook may have been deleted.  Assuming this is a CI project, could you try clicking the "reset all keys" button in the second-to-last panel on the project settings page?

You should also be able to manually run the latest commit by clicking the "play" button in the top right corner of the project dashboard and selecting the branch.  The "rebuild" buttons will run the commit displayed, which is usually the last commit to run on that branch.

**Comment by Kirtap** [comment]
I also see problems with hooks triggering 10 15 minutes later. Since last week, the status is "degraded"
http://status.shippable.com/

I have new branches that are not showing up so what are my options now?  Shippable support, any update on when this situation will be remediated?

**Comment by a-murphy** [comment]
There's nothing we can do about delayed webhooks, except watch the [Bitbucket status page](https://status.bitbucket.org/).  Unfortunately, if we don't get the webhook, we don't have any way of knowing that there is anything to process.

For the new branches, you can try clicking the "sync" button on the project settings page (second-to-last panel) and then running the branches manually.

**Comment by jefffleming** [comment]
I don't know what happened to the webhooks, but that resolved the issue.
