### ISSUE TITLE
CI build lags Branch commit by 52 minutes

### ISSUE THREAD

**Issue by slevert** [Shippable/support#4607]
### Description of your issue:
We are push code, merging branches and waiting for an ensuing CI build to occur.  What we have noticed is that there is sometimes a lag between the pushing (or merge) of the code into a branch and a subsequent CI build.  Our bitbucket repo does not show any shippable build waiting or in progress.  In some cases, it has taken up to 52 minutes to see a corresponding build start.

Here are the commit details:

Merge: e9c7e8d aebf074
Author: Gustavo Pichetto <gustavo.pichetto@ifsworld.com>
Date:   Mon Oct 15 12:07:01 2018 -0400

    Merged develop into LPA-213

Here is the shippable build details

![image](https://user-images.githubusercontent.com/4116189/47038356-4381c600-d14f-11e8-9a6a-9bdf6864054a.png)
https://app.shippable.com/bitbucket/mxitechnologies/lpa-core-task/runs/215/1/console

Is there any way we can help diagnose this?  Is this a known problem? I did a quick scan and could not see it in any open issues.

Thanks,

Stephane Levert

**Comment by slevert** [comment]
I missed the commit SHA 

commit 5b735eabf6157b3008c97abff38f367e080dfc07
Merge: e9c7e8d aebf074
Author: Gustavo Pichetto <gustavo.pichetto@ifsworld.com>
Date:   Mon Oct 15 12:07:01 2018 -0400

    Merged develop into LPA-213

**Comment by trriplejay** [comment]
Hi @slevert 

On Oct. 15th, bitbucket reported webhook delays: https://status.bitbucket.org/incidents/zzydzdqxyjny

I believe this was around the same time as the example you provided.  If you're still seeing this today, it might be a different problem, but it looks to me like bitbucket was just slow to send webhooks at the time.

**Comment by manishas** [comment]
@slevert are you still seeing this?

**Comment by slevert** [comment]
The problem has not manifested itself again.  Thanks for the previous replies.
