### ISSUE TITLE
Unable to deploy , error getting service

### ISSUE THREAD

**Issue by iparraguezs** [Shippable/support#4610]
Dears,
I have a problem, to execute job deployment.
here is the shippable link.

https://app.shippable.com/bitbucket/mxitechnologies/jobs/lp-notify-deploy-test-integration-ecs/builds/5bc891aa64e8ed070007a421/console

**Comment by trriplejay** [comment]
This looks like a bug that has to do with how we handle state once your first job failed. I'll open an issue for that. You should be able to get around this by using the "reset" feature on the job.  In the SPOG, you can right click on your deploy job, and select "reset".

![image](https://user-images.githubusercontent.com/6869398/47169629-e013a780-d2b8-11e8-91d7-d3f7e56168dc.png)

**Comment by iparraguezs** [comment]
trriplejay,
Thanks the problem was solved
