### ISSUE TITLE
Supporting union type element

### ISSUE THREAD

**Issue by junaruga** [Shippable/support#4611]
### Description of your issue:

This is a request for feature.
On below `shippable.yml`, the `rvm: 2.5` is not used. The default Ruby 1.9.3 is actually used.

```
language: ruby
rvm: 2.5 
build:
  ci: echo "abc"
```

Below setting works. Ruby 2.5 is actually used.

```
language: ruby
rvm:
  - 2.5 
build:
  ci: echo "abc"
```

You can consider union type element.
For example in the YAML parser logic, 

if `rvm` element is string, do something
if `rvm` element is array, do something.

This is what Travis CI's `.travis.yml` implemented.
This proposal for union type is not only `rvm`, but also maybe for some other elements too.

- Link to the build failure
  https://app.shippable.com/github/junaruga/ruby-pg/runs/50/1/console
  > Language ruby 1.9.3
- Scripts called from the yml (optional)
  https://github.com/junaruga/ruby-pg/blob/feature/ci-32bit-shippable-report-union/shippable.yml

**Comment by rageshkrishna** [comment]
This will be fixed early next week in the v7.1.4 release.

**Comment by junaruga** [comment]
@rageshkrishna alright. Thanks.

**Comment by a-murphy** [comment]
We've released an update that will allow you to specify `rvm: 2.5`.  Let us know if you still have any trouble.
