### ISSUE TITLE
Problem occuring again: oraclejdk8 build failing - No compiler is provided in this environment

### ISSUE THREAD

**Issue by dturczanski** [Shippable/support#4613]
Build passing locally, no changes in shippable config. Fails since Friday.

https://app.shippable.com/bitbucket/digitaltoucan/structure-cloud/runs/75/summary/console

Same as previously closed issue #4603

**Comment by trriplejay** [comment]
we're investigating. sorry for the inconvenience.

**Comment by trriplejay** [comment]
actually I see that the issue has been patched now. Let me know if you're still having trouble.
