### ISSUE TITLE
Kubectl fails: Unknown user "client"

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4614]
Hi,

I get kubectl failure with AMI 6.5.4 or newer. Version 6.4.4 works just fine. [My job](https://app.shippable.com/github/damejidlo/jobs/dj-playground-horizontal-autoscaler/builds/5bcb6216ec335d0700da2c3a/console) fails with `Unknown user "client"`. Is this a configuration issue or an AMI bug?

**Comment by a-murphy** [comment]
AMI 6.5.4 included updating from `kubectl` from 1.5.1 to 1.9.0.  And the 6.7.4 AMI updated `kubectl` again to 1.11.0.  It's possible that there is a conflict with the version of Kubernetes that you are using to run your cluster or an update to `kubectl` caused a particular setting to be interpreted differently.

**Comment by RadekDvorak** [comment]
Thanks for pointing that out. Knowing that and with little help from google search I found out that the disabled legacy authorization in kubernetes was the real culprit.
