### ISSUE TITLE
blocked from shippable

### ISSUE THREAD

**Issue by Scottkellett** [Shippable/support#4615]
Hi, 
My name is Scott and I'm doing a college assignment which requires me to create a Shippable account. I'm not sure what went wrong exactly but i tried to sign in via Github and I was blocked within seconds. My assignment is due wednesday so any help before then would be perfect. 
 github Account :Scottkellett
Email :s.kellett1@nuigalway.ie
Regards,
Scott.

**Comment by manishas** [comment]
@Scottkellett I have unblocked your account. Please log out and back in and everything should work as expected.
