### ISSUE TITLE
Problem Create Pipeline

### ISSUE THREAD

**Issue by iparraguezs** [Shippable/support#4619]
Error, create pipeline production
error work is attached, and job configuration files
###Error
 - Attempted to change type of resource xxxx from manifest to image. Resource type can not be changed.
 - Missing dependency for job: xxxx

###Link pipeline error
- https://app.shippable.com/bitbucket/mxitechnologies/jobs/lp-deploy_master_rSync/builds/5bce902156f6dd0700fa4ff1/console

[shippable..zip](https://github.com/Shippable/support/files/2504308/shippable.zip)

**Comment by trriplejay** [comment]
It is not possible to change the type of a resource/job directly.  The easiest solution is to pick a new name for your image resource.  

If you want your new image resource to have the same name as the old manifest job that you had, you'll have to do a few separate steps:
1. delete the manifest job (remove it from your yml, commit, push)
2. fully delete the manifest job from shippable.  You can do this by going to your "deleted" tab on the subscription dashboard, and finding the manifest job, and clicking the "delete" button next to it.  note: this button may not appear if the manifest job is still used as an IN to some other job, so make sure to also remove all IN references.
3. now that the manifest is fully deleted, you can add the "image" resource with the same name, and include it as an IN wherever you'd like.

**Comment by rageshkrishna** [comment]
@Iparragu I see that your rSync job is running successfully now so I'm assuming your problem is resolved. I'm closing the issue. Please reopen it if you still need help with this.
