### ISSUE TITLE
Are custom nodes compulsory for the node pool

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4622]
I want to delete the custom nodes and shift the workload to the shippable managed minions.

**Comment by rageshkrishna** [comment]
Node pools can be created and used with any kind of node. However, it isn't possible to switch an existing node pool between BYON and on-demand.

Here's what you can do to move everything over:

1. Go to your billing page, click "edit". 
1. Click on "Add new SKU" and configure it.
1. Delete the already existing "BYON" SKU
1. Verify your pricing and confirm the change.
1. For convenience, we automatically create a new node pool for you when you purchase a new SKU, so you should see it listed in your node pools at this point.

You can also take a look at http://docs.shippable.com/platform/management/subscription/billing/ for a walkthrough.

I hope this helps!

**Comment by phagunbaya** [comment]
I see this "An issue has been identified with your billing account. Please contact support."

**Comment by rageshkrishna** [comment]
I just checked and, yes, there is indeed a problem with your billing account. Can you please email me at ragesh@shippable.com to discuss the details? Thanks.

**Comment by rageshkrishna** [comment]
@phagunbaya Thanks for reaching out. The issue has been resolved. Let me know if you need any help with moving to on-demand nodes.

**Comment by phagunbaya** [comment]
Thank you. Now the builds are getting failed :( #4623 and #4624

**Comment by rageshkrishna** [comment]
I'm closing this issue as the node pool problem is resolved.
