### ISSUE TITLE
Build failed for java 8 (gradle builder)

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4624]
After moving from BYON to on-demand nodes, java build failed.
https://app.shippable.com/github/Falkonry/edge/runs/1304/1/console

```
Could not determine java version from '10.0.2'.
```

**Comment by rageshkrishna** [comment]
This is the same problem with runtime version as described in https://github.com/Shippable/support/issues/4623#issuecomment-432596018

Java 8 is available in runtime version v6.6.4. Switching to this runtime should meet both your Java and Python version requirements.

**Comment by phagunbaya** [comment]
Thanks.

**Comment by rageshkrishna** [comment]
It looks like you got a successful build on this, so I'm closing the issue. Feel free to reopen if you still need help with this.
