### ISSUE TITLE
Hi, just created a shippable account and it automatically blocked me from my account 

### ISSUE THREAD

**Issue by rioghnachQuinnOBaoighill** [Shippable/support#4626]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
