### ISSUE TITLE
Cannot login, I get taken to error page after trying to login using github.

### ISSUE THREAD

**Issue by darshan-cl** [Shippable/support#4627]
### Description of your issue:
Also to note, I am trying to login to shippable for the first time. Can somebody please take a look?
Btw the error message in the Error page, shows this.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

Thanks,
Darshan.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
