### ISSUE TITLE
not building java maven projects

### ISSUE THREAD

**Issue by craigham** [Shippable/support#4630]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:
my java maven builds do not seem to build any more.  

here is typical output.

`  build_ci 0s
  echo "MAVEN_OPTS='-Xms1g -Xmx2g -XX:PermSize=512m -XX:MaxPermSize=1g'" > ~/.mavenrc 0s  
  echo 'mvn clean install -B -V 1> .build.stdout 2> .build.stderr' > .build.sh 0s  
  chmod 0755 .build.sh 0s  
  travis_wait 60 ./.build.sh 0s  
/root/514a5e1f-5701-4833-9d21-920da38117e1.sh: line 86: travis_wait: command not found`

- Link to the build failure
https://app.shippable.com/github/QuailAutomation/openhab2-addons/runs/218/1/console

- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
it looks like your script contains a Travis command that is not supported on shippable: `travis_wait`.  Although we do offer some amount of basic Travis CI compatibility, not all features are supported.

I'd recommend you introduce a `.shippable.yml` to the project to best utilize the Shippable platform. You can see details on shippable.yml syntax here: http://docs.shippable.com/ci/yml-structure/ 

If you're against the idea of having a separate config script for Shippable, but still want to run builds on Shippable, then I'd recommend modifying your existing script to check for the `SHIPPABLE` environment variable.  If this variable is set to "true", then you should avoid using `travis_wait`.

Let me know if you have any questions.

**Comment by craigham** [comment]
Thanks for the feedback.

Here is the link to the repository, there is a shippable.xml file there.  I noticed you put a dot before the name.  Is that new?  I have been using shippable with various repositories for over a year and it was working.

https://github.com/QuailAutomation/openhab2-addons/tree/omnilink-binding

**Comment by trriplejay** [comment]
ah, interesting.  Actually, we don't support a `shippable.xml`, we support `shippable.yml`.  However, we also support `.travis.yml`, which your project does have.

I think what is happening, is that we check your repo for shippable.yml, don't see it, and then default to the .travis.yml, since we do offer some travis compatibility.  

I think all you need to do is change the `.xml` to `.yml` and Shippable will start using that file instead.

With regard to the leading `.`, that is optional.  It works with or without.

**Comment by craigham** [comment]
thanks so much.  I did some rearranging of my branch and moved that shippable over and misnamed it.  just kept missing the mistake.
