### ISSUE TITLE
Can't build, resync or delete repository

### ISSUE THREAD

**Issue by psoders** [Shippable/support#4634]
repository become unusable, i can not trigger builds, tried to delete it sync SCM and reenable, but it did not work, repository is still visible after deletion
user: psoders
https://app.shippable.com/bitbucket/humanoitgroup/schema-service/dashboard

**Comment by Bharath92** [comment]
Are you getting any error messages while deleting the repository?

**Comment by psoders** [comment]
no i did not get any error message and i can still view repository in interface, however i can not reenable it

when reenabling under https://app.shippable.com/subs/bitbucket/humanoitgroup/enable i get this error
```
deleteResourceById failed for id: 89266 returned error deleteVersionByResourceId for resourceId:89266 returned error: versions.destroy failed for resourceId: 89266 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"
```

**Comment by Bharath92** [comment]
Do you want us to try and delete the project?

**Comment by psoders** [comment]
i would like it to work... so that might be a solution, please delete it

**Comment by ankul-shippable** [comment]
@psoders we have deleted the project, please try re-enabling it again and let us know if it works for you. Thanks.

**Comment by psoders** [comment]
that worked, thanks
