### ISSUE TITLE
Error upgrade account

### ISSUE THREAD

**Issue by fractal-tech** [Shippable/support#4638]
When update my account I have this alert -> `Failed to create Braintree subscription`

**Comment by trriplejay** [comment]
Hi @fractal-tech , we're investigating. I've reset your private job quota so that you don't have to worry about running out while we get this sorted.

**Comment by fractal-tech** [comment]
@trriplejay right, thanks.

**Comment by fractal-tech** [comment]
@trriplejay , I had this problem.

[https://app.shippable.com/github/fractaltecnologia/datagateway-api/runs/25/1/console](https://app.shippable.com/github/fractaltecnologia/datagateway-api/runs/25/1/console)

**Comment by trriplejay** [comment]
Hmm.. it looks like you've switched from 14.04 to 16.04, and this seems to be some kind of bug in our build agent causing apt-get update and apt-get install to fail when in the `pre_ci` section.

is there a reason why you need those commands in the `pre_ci` section? This is installing the library on the build agent, but then immediately booting a separate build container to run your build in, so those two lines actually have no impact on the environment that your build runs in.  

I'd recommend deleting your `pre_ci` section, both as a workaround for this error, and in general as a way to speed up your build.

**Comment by fractal-tech** [comment]
@trriplejay makes perfect sense, thank you! build works now.

**Comment by fractal-tech** [comment]
Hi guys, I need to know about my upgrade issue.

**Comment by fractal-tech** [comment]
@trriplejay or @manishas I need help, my repo builds will expire and I need upgrade my account.

**Comment by manishas** [comment]
@fractal-tech I have removed build limits for your subscription for now... we will follow up as soon as we have a root cause for your billing issue.

**Comment by fractal-tech** [comment]
@manishas I build in two organizations, github and gitlab.

**Comment by rageshkrishna** [comment]
@fractal-tech I looked in to this and your transaction was rejected with a status of "Processor Declined". You will need to talk to your bank to know why it's blocking the charge.

Alternatively, you could try using another credit card.

You can reach me at ragesh@shippable.com if you would like more details about the transactions.

**Comment by fractal-tech** [comment]
Hi @rageshkrishna, thank you. This problem resolved.
