### ISSUE TITLE
Jobs stuck in queued state

### ISSUE THREAD

**Issue by seniorquico** [Shippable/support#4639]
I triggered two manual builds (rebuilds, more accurately), and they are stuck in the queued state:

https://app.shippable.com/github/ZapicInc/Zapic-Platform/runs/1453/summary/console
https://app.shippable.com/github/ZapicInc/Zapic-Platform/runs/1454/summary/console

Thanks in advance for assistance!

**Comment by trriplejay** [comment]
@seniorquico we're investigating now

**Comment by Boolos** [comment]
Same here if you can take a look (https://app.shippable.com/subs/github/casestack/dashboard), @trriplejay .  Thx!

**Comment by trriplejay** [comment]
@seniorquico @Boolos our build processing slowed down for a bit, but everything should be caught up now. Are you still seeing any issues?

**Comment by Boolos** [comment]
it's looking good now, thx!

**Comment by Boolos** [comment]
It's looking like Jobs are processing now.  Thx!

**Comment by seniorquico** [comment]
@trriplejay I kicked off the jobs again... it took a few minutes before they started executing. So... it's working, but it's still pretty slow (relatively... normally we're queued for only a handful of seconds). 😐

https://app.shippable.com/github/ZapicInc/Zapic-Platform/runs/1455/summary/console
https://app.shippable.com/github/ZapicInc/Zapic-Platform/runs/1456/summary/console

Feel free to close.

**Comment by trriplejay** [comment]
thanks, we'll be keeping an eye on this for awhile, so i'll leave this open for now.

**Comment by trriplejay** [comment]
we've released a patch that will prevent this from occurring. please let me know if you run into this again.
