### ISSUE TITLE
Two different repositories triggered at the same time

### ISSUE THREAD

**Issue by TomasSjosten** [Shippable/support#4644]
### Description of your issue:
When I commit new code to one repository, `mudbest`, it also triggers deploy on another repository `muddest` at the exact same time. I've been through the setup in my `shippable.yml` aswell as `deploy.rb` and the repository there is correct. I'm really out of clues on how to separate these two repositories from each other. When I deploy to `mudbest` I only want to trigger deploy from that repository.

### Correct deploy repository
https://app.shippable.com/github/muddest/mudbest/runs/3/summary/

### Wrong deploy repository
https://app.shippable.com/github/muddest/muddest/runs/1841/summary/

**Comment by a-murphy** [comment]
It looks like both of those were triggered by webhooks, so it's possible that the correct repository has webhooks for both projects.  Could you go to the repository settings on GitHub and check the webhooks tab?  There should be one Shippable webhook containing the `Project Id` from the bottom of the run page.  If there is another webhook with the `Project Id` for the wrong repository, that should be deleted.

**Comment by TomasSjosten** [comment]
Thanks @a-murphy, solved the issue.
