### ISSUE TITLE
Params as IN and OUT

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4645]
I would like to read the value from a `params` and modify it according the script inside a `runSh`. It seems that we cannot use the same ressource both as IN and OUT, even if the IN is `switch: off`. However, the environement variables seem to be set only for the IN ressource.

In the end, I only want my `params`as OUT but I would like a way to read the current value it stores.

**Comment by ankul-shippable** [comment]
@BotellaA `params` resource can not be used as IN and OUT to same job as it results in circular dependency.

You can use the current job's state or the state resource for this:
1. Use job state to save any information you want to use in the successive runs of the same job only.
2. Use [state](http://docs.shippable.com/platform/workflow/resource/state/) resource if you want single state to be shared with and modified by multiple jobs. `state` resource can be used as IN and OUT to the same job.

Please check our documention [here](http://docs.shippable.com/platform/tutorial/workflow/share-info-across-jobs/#job-state) for job state, which should solve your problem.
Let us know if it works for you, Thanks.
