### ISSUE TITLE
Missing dependency for: IN _ciRepo

### ISSUE THREAD

**Issue by TomasSjosten** [Shippable/support#4647]
### Description of your issue:
I got 2 issues I cannot seem to resolve.

1. Missing dependency for: IN muddest_ciRepo
I can't seem to fix this issue

2. Automated builds are not enabled on this repository because webhook was not setup.
I can't find anywhere where I can create/get a new webhook for the repository.

https://app.shippable.com/github/muddest/muddest/runs/1863/1/console

**Comment by Bharath92** [comment]
Could you please go to the Project -> Settings page and click on
- `Hook`: this will create the `ciRepo` resource for your project
- `Reset all keys`: this will setup webhooks

Please let us know if this helps.

**Comment by TomasSjosten** [comment]
Thanks for fast answer.
`Hook` doesn't help though, gives me following error message:
```
postJobDependency for :resourceId 92628 returned error: resource not found for id: 27948
```

Where should the webhooks be visible, once I've clicked `Reset all keys`?

**Comment by Bharath92** [comment]
It seems that your project was in a weird state. We have `Hook`ed and `Reset all keys` of your project. Could you please check and let us know whether it is working fine now?

**Comment by TomasSjosten** [comment]
Thanks alot!
Worked better. Though, where do I find the actual webhook?
Which URL to use

**Comment by Bharath92** [comment]
It will be present in your github project's Settings -> Webhooks section. Probably [here](https://github.com/muddest/muddest/settings/hooks).

**Comment by TomasSjosten** [comment]
Nice, thank you very much!
