### ISSUE TITLE
Account blocked 

### ISSUE THREAD

**Issue by ppavlov92** [Shippable/support#4648]
Our organization created a separate admin account to manage a project's CI and it got blocked on sign in.
BitBucket account: bee_ci

Thanks

**Comment by Bharath92** [comment]
We have unblocked the account. Could you please try again?

**Comment by ppavlov92** [comment]
It works now, thanks

**Comment by ppavlov92** [comment]
My personal account also got blocked, could you unblock it as well?
Bitbucket account: pavel.pavlov@bee.io

**Comment by a-murphy** [comment]
I've unblocked your account.  You should now be able to log in with either account.
