### ISSUE TITLE
Unable to add subscription integration

### ISSUE THREAD

**Issue by ppavlov92** [Shippable/support#4649]
I'm attempting to add a subscription integration for a new account following the following instructions:
http://docs.shippable.com/platform/tutorial/workflow/add-assembly-line/#instructions

However, the button to create a subscription integration for the subscription is not present:
![selection_071](https://user-images.githubusercontent.com/9005821/48538770-092a5680-e8be-11e8-8e35-cb4773ea25e7.png)

I also noticed that the section to automatically create subscription integrations on the edit page of the existing BitBucket integration is not present:
![selection_072](https://user-images.githubusercontent.com/9005821/48538838-324ae700-e8be-11e8-999e-1e463e4d1879.png)

In contrast with that, I've been testing the service and preparing the configurations using a personal account of mine, and there the subscription integration was created automatically from the BitBucket integration which was created on the first login, and I'm also able to add additional ones:
![selection_073](https://user-images.githubusercontent.com/9005821/48538921-66bea300-e8be-11e8-9b03-e29f83f92cdf.png)
![selection_074](https://user-images.githubusercontent.com/9005821/48538952-7b02a000-e8be-11e8-9547-8766ffc2b4d6.png)

BitBucket username of the account that doesn't work: bee_ci
BitBucket username of the account that works: ppavlov92

The main difference between the two accounts that I can come up with is that mine has its own repositories and the builds are run on a repo of which it is an owner, while the other one is specifically created to manage the CI of a project, so it does not own any repos, but is instead added as an admin to an existing one. What am I missing?

Thanks

**Comment by a-murphy** [comment]
It looks like bee_ci doesn't have enough permission on the subscription to be allowed to add integrations.  To allow bee_ci to add integrations, bee_ci will have to be given an `admin` or `contributor` role on the Bitbucket team.  Clicking the "sync" button on the Shippable profile page after updating permissions on Bitbucket will update the permissions on Shippable.

**Comment by ppavlov-dw** [comment]
This worked, thanks for the help. It seems I had not grokked the way subscription permissions map to the repository permissions. Sorry for the delay, it took some effort to convince the admins into allowing that level of access. This can be closed

**Comment by a-murphy** [comment]
Glad it's working!
