### ISSUE TITLE
 notificacion on_success:always only in master branch

### ISSUE THREAD

**Issue by juanpabloaj** [Shippable/support#465]
I test and build in master and develop branch.

I try notifier to the users when stable changes are released, changes in master branch.

How I can send notification `on_success:always` but only from master branch?

**Comment by oniltonmaciel** [comment]
WARNING
Note for google parachuters:

For Pull requests, shippable seems to also build branches as if they were merged with master.
So, for this builds you would have $BRANCH=="master" in the build, even if the code is not on master yet.

So the best way to only notify about code changes when they are really in master is to check for PULL_REQUEST variable, like this:

    if [ "$BRANCH" == "master" -a "$PULL_REQUEST" == "false" ] ; then echo "Something changed in master"; fi
