### ISSUE TITLE
ECS integration not working for specific build

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#4650]
I am building a specific docker image in the on_success portion of my build that pulls from ECS in the FROM portion. It always fails on no basic auth. 
See: https://app.shippable.com/bitbucket/csi3/alarmconsoleserver/runs/12/1/console

I validated that my AWS keys are fine by building locally that same image, with the same AWS  keys used in my integration.  I also have a similar build that works in Shippable pulling from a different AWS account.
See: https://app.shippable.com/bitbucket/csi3/bluecrewleagueathletic/runs/23/1/console

I did ssh into my failing build to see what was wrong. It looks like the AWS cli is not properly configured with my integrations keys. Any help here would help.

thanks

**Comment by a-murphy** [comment]
The failing run does not have any `hub` integrations in the YML, and the successful one does.  Could you check that your AWS integration is correctly indented in the `integrations` section of your `shippable.yml`?

**Comment by Kirtap** [comment]
Right on the money... it was a YAML indentation issue :(

**Comment by a-murphy** [comment]
Great!  I'll close this issue.  Let us know if you have any other problems.
