### ISSUE TITLE
Billing issue

### ISSUE THREAD

**Issue by cedric-g** [Shippable/support#4652]
Hi, in our plan section of billing you have the following message:
`An issue has been identified with your billing account. Please contact support.`

URL: https://app.shippable.com/subs/github/ALTRAN-MONTPELLIER/billingV2

Do you have more information ?

**Comment by rageshkrishna** [comment]
@cedric-g Can you please email me at ragesh@shippable.com to discuss this? Thanks.

**Comment by cedric-g** [comment]
Any news ? I sent you an email on friday 😃

**Comment by rageshkrishna** [comment]
Strange, I do remember replying to it. I can check again in a bit and try sending it again.

**Comment by cedric-g** [comment]
Ah wait I just found your email, it has been filtered in one of my list because of the shippable domain.
