### ISSUE TITLE
SPOG wrong diagram

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4653]
My SPOG shows twice the same job. It appears in grey the picture.
![screenshot-geode-solutions dashboard - shippable - mozilla firefox](https://user-images.githubusercontent.com/3213882/48617875-8245ae80-e98f-11e8-8a88-34e8d8d02fdd.png)

**Comment by ChaitanyaVootla** [comment]
@BotellaA the second gray job (the elliptical one) is a dummy job which is supposed to be drawn when a direct line cannot be drawn between the objects (to quickly identify the dependencies).

Drawing the main job as a separate entity in this case seems unnecessary, this will be fixed soon

**Comment by BotellaA** [comment]
Thanks. You can close this, if you will fix it.
