### ISSUE TITLE
docker login requires at most 1 argument

### ISSUE THREAD

**Issue by bltavares** [Shippable/support#4655]
Hi there,

I'm trying Shippable and it seems that the `dockerRegistryLogin` integration can't log in.
I'm using the examples from the documentation, and I've both email and usernames on the integration page.

<details>
<summary>Error log</summary>

```
echo '"docker login" requires at most 1 argument.
See 'docker login --help'.
Usage:  docker login [OPTIONS] [SERVER] [flags]
Log in to a Docker registry'
"docker login" requires at most 1 argument.
See docker login --help.
Usage:  docker login [OPTIONS] [SERVER] [flags]
Log in to a Docker registry
```

</details>

---

- [Link to the build failure](https://app.shippable.com/github/bltavares/docker-images/runs/6/3/console)
- [Scripts called from the yml](https://github.com/bltavares/docker-images/blob/1fb9a28af5e6abd7ce340a3868652667dcf6ed58/shippable.yml)

**Comment by ric03uec** [comment]
@bltavares we've identified the underlying issue. For security reasons, I'd prefer not to recommend a fix here. You can either mail me at devashish at shippable.com or post your email id here so that I can give you the details. thanks.

**Comment by bltavares** [comment]
Thanks @ric03uec for getting back. I'll email you.
