### ISSUE TITLE
Can't logon with bitbucket

### ISSUE THREAD

**Issue by ghost** [Shippable/support#4656]
When I try to logon with my bitbucket account: ngildersleeve@devexi.com I get this error
![screenshot from 2018-11-20 10-58-58](https://user-images.githubusercontent.com/7928728/48801018-2d23d880-ecc0-11e8-8800-61ef58702372.png)

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by ghost** [comment]
Awesome. Thanks for the quick response.
