### ISSUE TITLE
New account blocked

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#4659]
Getting this error when logging in:

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

Account: xxx

can you please advise

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by Kirtap** [comment]
Now works, thanks.
