### ISSUE TITLE
Unable to Login to Shippable (Bitbucket: invalid redirect_uri)

### ISSUE THREAD

**Issue by ray-grointel** [Shippable/support#4660]
After following the instruction to **log out** and log back in with Bitbucket (something to do with Bitbucket v1 REST APIs), we're unable to log back into Shippable.

<img width="500" alt="screen shot 2018-11-27 at 10 50 51 am" src="https://user-images.githubusercontent.com/34545687/49066707-125ae200-f233-11e8-9b6d-2cf806f09782.png">

```
Invalid redirect_uri

This integration is misconfigured. Contact the vendor for assistance.
```

<img width="500" alt="screen shot 2018-11-27 at 10 54 54" src="https://user-images.githubusercontent.com/34545687/49066715-1850c300-f233-11e8-8589-00d2b42849f1.png">

**Comment by rageshkrishna** [comment]
@raymond-grointel Sorry about that. The problem has been corrected. Can you please try logging in again?

**Comment by ray-grointel** [comment]
Working now; thank you!
