### ISSUE TITLE
Docker build has no network connection

### ISSUE THREAD

**Issue by mliszewski** [Shippable/support#4661]
As of this morning we are seeing an issue where a `docker build` done within our CI build is having issues accessing the network. Nothing changed about our Dockerfile

Here is a build from this morning that is failing: https://app.shippable.com/github/CompanionLabs/api-graphql-server/runs/952/summary/console

Here is one from last week that succeeded: https://app.shippable.com/github/CompanionLabs/api-graphql-server/runs/943/1/console

**Comment by rageshkrishna** [comment]
https://registry.yarnpkg.com/flatmap-stream/-/flatmap-stream-0.1.1.tgz is the dependency that's failing to download. I'm seeing `{"error":"package could not be found."}` when I try to hit that URL from the browser. Is this a private package?

**Comment by rageshkrishna** [comment]
It turns out this package has been removed because it contained malicious code: https://www.zdnet.com/article/hacker-backdoors-popular-javascript-library-to-steal-bitcoin-funds/

**Comment by mliszewski** [comment]
Ok. Thank you. We will remove the reference to that packag.e
