### ISSUE TITLE
Reenabling integrations after bitbucket REST update fails with foreign key error

### ISSUE THREAD

**Issue by SparK-Cruz** [Shippable/support#4662]
Today my bitbucket subscription warned me about REST v1 api.
I logged out and in as instructed and my integrations were gone, so I decided to reenable them.

When I click the toggle the following noty message pops up:
![FK violation](https://user-images.githubusercontent.com/1179000/49098166-6b3b7200-f255-11e8-975a-a7b74476a62d.png)

My subscription: https://app.shippable.com/subs/bitbucket/tecnofit

(The message says delete, but the toggle is red and I'm trying to turn it green)

**Comment by SparK-Cruz** [comment]
Apparently my boss (org owner) didn't face the same bugs, even though it was me who added the integration. :/

**Comment by a-murphy** [comment]
Your subscription had duplicates of some projects, and just happened to show you the copy that hadn't been enabled today.  I've removed the duplicates so it won't be a problem again.  Let us know if you have any other problems.
