### ISSUE TITLE
New bitbucket integration not build tags

### ISSUE THREAD

**Issue by SparK-Cruz** [Shippable/support#4663]
Git tags are not showing in the build queue when I push them.

**Comment by a-murphy** [comment]
Assuming this is the same subscription as #4662, it looks like the enabled projects were completely disabled and re-enabled.  This would have reset the project settings.  Tag builds can be enabled in the first panel on the project settings page (click the project name and then the gears in the top right to access the project settings).  A project owner can enable tag builds.

**Comment by SparK-Cruz** [comment]
I feel dumb, thank you!
