### ISSUE TITLE
Bitbucket account blocked

### ISSUE THREAD

**Issue by jdestep93** [Shippable/support#4666]
Hi there, I cannot authenticate with bitbucket.  My account on bitbucket is jon@seamlesscontacts.com and the account being billed for the service is seamlesscontactstech.  Subscription is seamlesscontacts

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
