### ISSUE TITLE
cliConfig with scope:gke fails to authenticate

### ISSUE THREAD

**Issue by haraldnh** [Shippable/support#4667]
I'm trying to set up a CD pipeline deploying to GKE.  But no matter what I do, the setup of credentials on the cluster fails:

`
Activated service account credentials for: [<user>@<project>.iam.gserviceaccount.com]
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) get-credentials requires edit permission on <project>
Failed to initialize kubeAdapter: gcloud failed and exited with error code 1
`

For the runSh jobs, I have worked around it by having the cliConfig without scope and just running 'gcloud container clusters get-credentials' at the start of the script.  But for deployments (and other managed jobs), this is not possible.

I have tried giving the service account more permissions (up to project editor) with no effect.

**Comment by a-murphy** [comment]
This appears to be related to a combination of a GKE cluster created without a certificate and the `container/use_client_certificate` setting.  We set `container/use_client_certificate` to true with the gcloud CLI because there are older clusters that require that setting.  We're investigating potential workarounds and what to do about this case.

The cluster details page in the Google Cloud Console will say "client certificate" is disabled if this is the case.  Could you let us know if your cluster does in fact have a certificate so that we can attempt to find other potential causes if needed?

**Comment by haraldnh** [comment]
You are correct that the client certificate seems to be disabled here.  There also doesn't seem to be any easy way to enable it once the cluster has been created, and there are other deployments running on the cluster already.  So I guess I'm a bit stuck.

I see that Google is recommending new clusters to be created with only IAM-based access, i.e. both basic auth and client certificate disabled, so I guess this will be a quite common situation soon.

For me, the best way would be if you could add a setting I can put either on the integration or in the yaml file which would make things work with IAM/RBAC-only clusters.

**Comment by haraldnh** [comment]
A bit more information (and more confusion on my side):  I created a test cluster with client certificates enabled.  It now passes the setup part, but all kubectl commands I try to run fails with permission denied, and user "client" cannot do whatever the command is about.  But the service account in the integration is definitely not "client", so I don't understand anything about how this fits together.

(The part I'm working on at the moment is setting up secrets.  So it is mostly a sequence of kubectl apply of various yaml files I've done variable substitution on.)

**Comment by haraldnh** [comment]
Ok, got things working by giving the master certificate the cluster-admin role, as described in https://github.com/kubernetes/kubernetes/issues/65400.  So as far as I can tell, the currently managed code does not use the service account in the integration for kubernetes operations, rather it pulls out the master client certificate and uses whatever rights that one has.

I guess I hope you can change your system so that I can ignore these certificates.  The way it is now is quite confusing and requires that I set up the access rights in several locations.

**Comment by haraldnh** [comment]
Moving on to the deployment, things again fail, but now in new and interesting ways:

`Activated service account credentials for: [<user>@<project>.iam.gserviceaccount.com]`
`Fetching cluster endpoint and auth data.`
`ERROR: (gcloud.container.clusters.get-credentials) either auth_provider, token or username & password must be provided`
`Failed to initialize kubeAdapter: gcloud failed and exited with error code 1`

I'm just getting more and more confused here.

**Comment by trriplejay** [comment]
We've opened the certificate issue internally. Something you might want to try in your case is using a generic [kubernetes](http://docs.shippable.com/platform/integration/kubernetes/) integration instead of GKE.  This integration allows you to just provide a yml config file that works for your cluster. We also document some steps in how to create this file from scratch, utilizing a service account on your cluster: http://docs.shippable.com/deploy/tutorial/create-kubeconfig-for-self-hosted-kubernetes-cluster/

**Comment by haraldnh** [comment]
I've been playing a bit with the kubeconfig file, and it doesn't seem to get me much further.  I can set up the contents for application-default credentials easily enough, but there doesn't seem to be a way to embed the service-account private key (the json used in the gcloud integration) into the kubeconfig file.  And there is no way to side-load the service-account key and configure the environment to pick it up either.

So the only thing it seems I can do with the kubernetes configuration is to use yet another old-style cluster setup.  I've tested things running on an older cluster we have, and once I've given the client certificate enough rights, the gcloud integration works, so I don't think doing it another way will give me much.

I'll spend some time trying to map out exactly what needs to be set on a cluster in order for the current gcloud integration to work.  But my target would be to run with the new RBAC authentication only.  On the other hand, I'm not sure you can easily combine kubectl proxy and application-default-credentials, which probably means getting OpenID tokens instead, with associated lifetime fun...

**Comment by haraldnh** [comment]
Some more testing today, I've been creating and deleting a lot of clusters...

A cluster which has 'client certificate' and 'legacy authorisation' enabled works for cliConfig jobs with scopes: gke, but fails for deploy jobs.  If I additionally enable 'basic auth', deploy jobs also work.

It seems to work nicely with most other stuff I can throw at it, including vpc-native networking and private clusters (with master exposed).

**Comment by Stelminator** [comment]
This was hard to find: https://www.terraform.io/docs/providers/google/d/datasource_client_config.html

I'm not sure if that solves your problem, but, this was the bit I needed for authorization w/o client cert or master auth.  I'm leaving it here in case it helps someone else.

```
data "google_client_config" "default" {}

data "google_container_cluster" "my_cluster" {
  name   = "my-cluster"
  zone   = "us-east1-a"
}

provider "kubernetes" {
  load_config_file = false

  host = "https://${data.google_container_cluster.my_cluster.endpoint}"
  token = "${data.google_client_config.default.access_token}"
  cluster_ca_certificate = "${base64decode(data.google_container_cluster.my_cluster.master_auth.0.cluster_ca_certificate)}"
}
```

**Comment by haraldnh** [comment]
It's been almost 3 months now, any progress on fixing this issue?

**Comment by trriplejay** [comment]
At this time the issue is still in our backlog. I'll see if we can get some movement on it soon!

**Comment by Kirtap** [comment]
I am running into this as well when using the GKE integration. Giving all permissions to the service account does not change anything.

ERROR: (gcloud.container.clusters.get-credentials) get-credentials requires edit permission on xxx

Is the current solution to either enable basic auth and legacy auth in the cluster vs doing a self-hosted kubernete integration? Any update on when this will be fixed for GKE integration?

Currently, when creating a cluster in GKE, enabling basic auth and client certificate results in the following:

Starting with version 1.12, clusters will have basic authentication and client certificate issuance disabled by default.

**Comment by Kirtap** [comment]
Any update on this? For reference, I have everything running with Legacy authorisation disabled using GKE integration but still require basic auth and certificates.

**Comment by haraldnh** [comment]
Some more months have passed, we're now 8 months since reporting this.  Any progress at all to allow us to use Shippable together with GKE without having to jump through hoops?

**Comment by haraldnh** [comment]
I guess Shippable is dead, so closing.
