### ISSUE TITLE
Dynamic Build Node using Java 11 instead of configured Java 8

### ISSUE THREAD

**Issue by StuporHero** [Shippable/support#4669]
I'm calling Gradle to run my builds, and a build is failing in Shippable that is not failing on my desktop. I used Gradle's build scans feature to try to identify the problem, and it seems that Gradle is executing under Java 11 on the Shippable node despite the Shippable config being set to Java 8 and even the log clearly showing Java 8 being set up.

[Shippable Config](https://github.com/Shippable/support/files/2637514/shippable.yml.txt)
[Build Log](https://github.com/Shippable/support/files/2637518/sunsofterp-oracle-forms-gradle-plugin-86.1.log)
[Shippable Build Scan](https://scans.gradle.com/s/qkyrfwkufcxhg/infrastructure)
[Local Desktop Build Scan](https://scans.gradle.com/s/o5n5aepc5ny5w/infrastructure)

**Comment by StuporHero** [comment]
As a side note, it would be nice if your support wasn't a public issue tracker so I could privately pass these kinds of details to you. This case doesn't matter as much, but there are plenty of cases where I might be working with proprietary stuff that I'm not at liberty to disclose in this forum.

**Comment by trriplejay** [comment]
Hi @StuporHero,

This is a known issue that will be resolved in our next release, however in the meantime you can avoid this error by adding one extra line to your yml build ci section that looks like this:

`- source shipctl jdk set oraclejdk8`

This should properly set the `$JAVA_HOME` variable w gradle is relying on.  Once the next release comes out you will be able to remove this extra line.  Let me know if you have any questions.

In the future if you have potentially sensitive info to share, we'd be happy to move the discussion to email to avoid having to provide anything publicly.

We do offer a few different support tiers, detailed here if you're interested: https://www.shippable.com/premium-support.html

**Comment by StuporHero** [comment]
@trriplejay Is the following also a known issue?

`Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

After making your recommended change, I now get that error, and searches suggest that this is due to a misconfigured Java install likely to do with `java-common` and `ca-certificates-java` in Ubuntu.

**Comment by trriplejay** [comment]
That issue (or one very similar) has actually come up previously. and unfortunately I don't have a good solution for it. It appears to be related to a bug in Ubuntu that was fixed in 18.04 but not backported to 16.04. I think this bug report might list some workarounds that you could try:

https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1739631

**Comment by StuporHero** [comment]
@trriplejay I fixed all my problems by using an older version of the shippable build node. I was just bringing that up in case it persists after the update that fixes my original problem. We can consider this closed.
