### ISSUE TITLE
Is there a way to reset only 1 job hitstory?

### ISSUE THREAD

**Issue by depohmel** [Shippable/support#4671]
I have 2 git repos enabled and I want to entirely reset history for one of them. How do I do that? 
I've searched thru docs... But no luck.

**Comment by a-murphy** [comment]
You can delete a `gitRepo` and add it back.  To delete the `gitRepo`: identify the jobs using that `gitRepo`, update those jobs to no longer reference the `gitRepo` (comment out the `IN` or `OUT`), comment out (or delete) the `gitRepo` definition from your YML file, commit these changes to your `syncRepo`(s), find the `gitRepo` on the "deleted" tab of your subscription dashboard, and click "delete."  You can then uncomment the `gitRepo` and commit it to your `syncRepo` and a new resource will be created with the same name that can be added back to the jobs that use it.

If you don't intend to use the same name, it can be easier to rename the `gitRepo` and then delete the old one.

**Comment by depohmel** [comment]
i'll try. thanks

**Comment by rageshkrishna** [comment]
@depohmel Do you need any more help with this?

**Comment by depohmel** [comment]
Nope. Thanks.
