### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by nsofian** [Shippable/support#4675]
My github account has been blocked since i first time logged into shippable using Github. It says 'Your account has been blocked as it was identified to be violating our security policy.
github login: nsofian

**Comment by Bharath92** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by nsofian** [comment]
Thanks!
