### ISSUE TITLE
CentOS on-demand node missing sudo access

### ISSUE THREAD

**Issue by pmack** [Shippable/support#4677]
In the current on-demand CentOS 7 nodes, the `centos` user seems to be unable to sudo with being prompted for a password. This makes debugging test builds a problem since the docker containers can't be accessed. The Ubuntu on-demand nodes work as expected.

![image](https://user-images.githubusercontent.com/3597623/49834156-f2f6a580-fd58-11e8-9331-5c25d3e6d707.png)

**Comment by trriplejay** [comment]
@pmack this looks like a bug in the more recent centOS AMIs. As a workaround, you can move back to runtime version 6.8.4 to avoid this error.  We're investigating the root cause and will hopefully get a fix out in the upcoming release.

**Comment by pmack** [comment]
@trriplejay Thanks! Switching the runtime to the older image seems to work.

**Comment by a-murphy** [comment]
This has now been fixed.  You should now be able to use `sudo` in debug builds on both new and older AMIs.
