### ISSUE TITLE
Pipeline being triggered by two CI builds

### ISSUE THREAD

**Issue by DeanHutchison** [Shippable/support#4679]
I have my yml setup to only run on master branch.

When I do a Pull Request I get two builds triggered. One is for the PR and the other is against master. From what I have read, this appears to be the expected behaviour.

However, once my CI runs I update a resource which triggers a deploy job and that in turn triggers a shakedown job.

My issue is the extra CI job which is running against master is getting mixed up in my pipeline process and triggering extra deploys and updating my manifest.

My pipeline looks like so..
![pipeline](https://user-images.githubusercontent.com/3185942/50000984-49e7bf00-ff93-11e8-9b64-c95dd049afd8.png)

.. and if I trigger my pipeline manually everything is great. But on a PR I get unexpected behaviour because of the two triggered builds. 

I have experimented with the $IS_PULL_REQUEST variable but ideally I just want to know when it's a PR, when it's a commit and when it's a merge into master so I can trigger different behaviours in my pipeline.

Is there a way to achieve this ?

**Comment by ankul-shippable** [comment]
@DeanHutchison Using `IS_PULL_REQUEST` is the right approach here.

You can do something like this:
```
build:
  ci:
    - if [ "$IS_PULL_REQUEST" == false ]; then ./update_OUT_resource; fi
```

Let us know if this works for you. Thanks.

**Comment by DeanHutchison** [comment]
Thanks Ankul, I've tried a number of ways of using IS_PULL_REQUEST and it solves one but not all of my issues.

I really only want to run my pipeline when there is a pull request or a merge into master. At the moment, from what I can see and what I have read, the PR triggers two builds. One build is against the PR branch and the other is on the branch the PR is against (master in my case). I still don't understand the reason for the second build that is triggered on master.

The "IS_PULL_REQUEST" solves half of my problem for letting me know when to run my pipeline on the PR, but the other half of my problem is that I don't know when to run my pipeline ONLY on merge into master. I am assuming that the lack of something like an "IS_MERGE" env variable probably means that it's not possible to know (from the meta data that Bitbucket provides) that a merge has happened.

At the moment my thought process is along the lines of using a semaphore to get the second build process to sleep until my pipeline has completed processing to prevent the second build interrupting my pipeline.

I may just be missing something fundamental here, but I have spent a lot of time trying to understand how to control the process execution and would appreciate any help possible.

Thanks

**Comment by ankul-shippable** [comment]
@DeanHutchison Could you please give the us Subscription Id (can be found on the bottom-right of SPOG page) and Project Id(bottom-right of projects page) of the project for which you are trying to setup this.
1. subscription id
![sub_id](https://user-images.githubusercontent.com/16793274/50336351-fdbcf180-0533-11e9-889d-30d106b456f0.png)

2. project id
![project_id](https://user-images.githubusercontent.com/16793274/50336361-03b2d280-0534-11e9-8cba-934929dc8fb2.png)

You can mail these Ids to me at ankul@shippable.com.

Could you please tell us the exact workflow you want to run with inputs and expected outputs. Thanks.

**Comment by DeanHutchison** [comment]
Hi @ankul-shippable,

Details sent.

**Comment by DeanHutchison** [comment]
I have found the reason that I was getting that extra build triggered @ankul-shippable.

I had set `buildOnPullRequest: true` on my gitRepo resource. Removing this gives me more of the behaviour I was expecting.
