### ISSUE TITLE
account blocked

### ISSUE THREAD

**Issue by montyelligo** [Shippable/support#4681]
## Account Blocked

My account is blocked. Please unblock me?

## Scopes Message

Note: an email I got from github said: "Hey montyelligo! Previously, a third-party OAuth application (prod-shippable) did not have any scopes. It was recently granted additional scopes (admin:repo_hook, read:org, repo:status, repo_deployment, and user:email)."

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

And the scopes message sounds like just a notification for the required scopes to use Shippable for repositories in an organization that has third-party restrictions enabled on GitHub.  It's not related to your account being blocked, but is related to logging in to Shippable for the first time with GitHub.

**Comment by montyelligo** [comment]
Thanks
