### ISSUE TITLE
Can not delete Assembly Line

### ISSUE THREAD

**Issue by slevert** [Shippable/support#4682]
I migrated our deployment jobs and resource to a master branch and was attempting to update the assembly line to point to that branch.   I created the assembly line and was then attempting to delete the old assembly line and I get an error on delete. I've pasted the error below.

{"logType":"verbose","methodName":"resources|deleteResource|id:95592|_deleteJobDependencies","id":4001,"message":"deleteJobDependencyById for JobDependencyId: 117950 returned error: resource object(s) not found for jobDependency id: 117950"}

I don't know how to find the mentioned dependency and I want to rebuild a new assembly line for my project.

**Comment by slevert** [comment]
Here is a related build failure.  

https://app.shippable.com/bitbucket/mxitechnologies/jobs/lpa-deploy-
master_rSync/builds/5c195483e462ca07005e0711/console

**Comment by a-murphy** [comment]
Could you try again?  I've deleted that dependency.  We'll have to look into why the resource wasn't found, but that resource should not cause further problems with the dependency object removed.

It's not clear which resource(s) you are trying to delete.  Is it just the deploy job, or a syncRepo/rSync?

**Comment by slevert** [comment]
Hello, I tried deleting the assembly line and it still fails.  Here's the latest error:

{"logType":"verbose","methodName":"resources|deleteResource|id:95595|_deleteJobDependencies","id":4001,"message":"deleteJobDependencyById for JobDependencyId: 117945 returned error: resource object(s) not found for jobDependency id: 117945"}

I was trying to remove the syncRepo/rSync.

**Comment by slevert** [comment]
The latest error I'm getting is:

{"logType":"verbose","methodName":"resources|deleteResource|id:95595|_deleteJobDependencies","id":4001,"message":"deleteJobDependencyById for JobDependencyId: 117943 returned error: resource object(s) not found for jobDependency id: 117943"}

**Comment by a-murphy** [comment]
We've found that the appears to be related to resources in the new syncRepo referring to resources in the old syncRepo.  Given the number of resources involved, and the intent to delete them, we've removed all of the links to resources in the old syncRepo.  You should now be able to delete the old syncRepo without any more of these errors.  I would suggest running the new syncRepo _after_ deleting the old syncRepo, or the links will be recreated.  Let us know if you continue to see any errors.

**Comment by slevert** [comment]
It seems to be all clear now.  Thanks for the help.
