### ISSUE TITLE
Builds failing since last AMI release

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#4685]
Our first build yesterday (coincidentally, first since the v6.12.4 release) failed
- https://app.shippable.com/github/eccosolutions/ecco/runs/2478/summary/console
The root cause was "Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty", which a search around shows that issue relates to the SSL key store when accessing Maven artifacts over HTTPS, but could be down to a difference in the JDK (missing CA certs).

I cleared the Maven artifact cache prior to this build which exposes the issue more obviously.
- https://app.shippable.com/github/eccosolutions/ecco/runs/2482/1/console

Our node pool remains set to 6.10.4 (and we don't have any override in shippable.yml), yet as seen in the console output for 2478.

I've connected to the node, and verified that 6.10.4 still sees the same version of Maven, which it does, so that's not the issue.

I've also had a quick look to see that the JDK still appears to have CA certificates, which it appears to: 

    ll /usr/lib/jvm/java-11-openjdk-amd64/lib/security/

and

    ll /etc/ssl/certs/java/

What else has changed?  We're stuck as to what has gone on, but I'm aware that there are v6.12.4 elements in the process which may be part of this

    sudo docker ps
    CONTAINER ID        IMAGE                        COMMAND                  CREATED              STATUS              PORTS               NAMES
     b88f068dd0bd        drydock/u16javall:v6.10.4    "/home/shippable/cex…"   About a minute ago   Up About a minute                       c.exec.ecco.2483.1
     754237228b48        drydock/u14reqproc:v6.12.4   "/bin/sh -c $IMAGE_R…"   2 minutes ago        Up 2 minutes                            reqProc-5c1b975a596ae107008b94fe

**Comment by rageshkrishna** [comment]
@nealeu We did ship a fix in [v6.12.4](https://github.com/Shippable/admiral/releases/tag/v6.12.4) for an issue where JAVA_HOME was being incorrectly set to a JRE and not a JDK (this was happening mainly on CentOS images), and in some configurations (including Ubuntu) the path was ultimately being overridden to actually use an incorrect version of Java altogether.

I suspect Maven is picking up on the _fixed_ JAVA_HOME and running in to some deeper issue with the actual Java 11 environment in the v6.10.4 images.

I haven't tried this out, but attempting a `source /etc/drydock/.env` as the first step in your build might help to reset the environment variables to the original (albeit probably incorrect) values and allow your build to work while we investigate a more appropriate fix.

**Comment by nealeu** [comment]
Hi @rageshkrishna, 

That sounds plausible as I've continued digging on this one and found https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1739631 and https://gist.github.com/mikaelhg/527204e746984cf9a33f7910bb8b4cb6 which relate to a change in the keystore format as of JDK 9.

I was thinking that given we have a symlink from the java install to /etc/ssl/certs/java/, then the selection of java via Shipctl, presumably, is potentially not accounting for this issue.

I'll give your fix a try and let you know.

I'm not clear how the 6.12.4 release is affecting our 6.10.4 build though...

**Comment by rageshkrishna** [comment]
This happens because the latest version of shipctl is mounted in to the build container. We do this to make sure everyone gets to benefit from enhancements and bug fixes. Unfortunately, it looks like this is a fix that, despite achieving the correct behaviour from the perspective of picking and configuring the right java version, causes a problem in build behaviour.

**Comment by nealeu** [comment]
Hi @rageshkrishna,

Thanks for clarifying that.  Useful to know.

Incidentally, I just tried another workaround via SSH that also worked to allow `mvn compile` to pull artifacts down.

    rm /etc/ssl/certs/java/cacerts 
    update-ca-certificates -f

On a new build with your fix, things are running.

For reference, I added it at the start of the ci section as follows:

    ci:
      - source /etc/drydock/.env

**Comment by rageshkrishna** [comment]
I'm happy to hear you are unblocked. 

I'm sorry about the trouble this has caused. I'll continue to investigate this and see what we might need to change at our end so this works out-of-the-box, and also what we need to improve in our drydock tests so we can catch these problems sooner.

**Comment by nealeu** [comment]
Thanks for the speedy 5-star support :)

**Comment by rageshkrishna** [comment]
We've figured out how to resolve the certificate store conflict between JDK 8 and 11. The next release of the drydock images in v7.1.4 should make this problem go away.

**Comment by nealeu** [comment]
Excellent. Thanks for the update.

**Comment by a-murphy** [comment]
The v7.1.4 images are now available if you want to try them.

**Comment by nealeu** [comment]
Great idea @a-murphy!

**Comment by nealeu** [comment]
Working for me so I'll close the issue.
