### ISSUE TITLE
Unable to add or modify node pools

### ISSUE THREAD

**Issue by nathanaherne** [Shippable/support#4686]
### Description of your issue:
I noticed that I am unable to delete files/folders from within my Dockerfile. It seems this is a Docker/Kernel issue. To solve this, I want to update my node pool to see if this solves the issue. I tried to do this and got the following error:

No valid cluster nodes available for ids: 5c1b31b274bcaf070059bcdc

I am unable to delete the existing node pool, I am unable to add a new node pool and I am unable to edit the existing node pool.

Would someone be able to tell me how I solve this issue please?

**Comment by trriplejay** [comment]
Hi @nathanaherne. What was the action you took to upgrade your pool? And which organization is this for?

**Comment by nathanaherne** [comment]
hi @trriplejay to access the node pool -> go to subscriptions, click on the bitbucket project, select the cog and select node pools. Click on the default_node_pool and I get the error in my above post.

I am not sure what organisation I am logged into as I am logged in under my own name.

**Comment by trriplejay** [comment]
@nathanaherne I've moved your node pool to the latest runtime version, can you refresh and see if you still get that error? if you want a different runtime, feel free to change it, and let me know if you see any issues still.

**Comment by nathanaherne** [comment]
@trriplejay thank you for this. I tested building using the stable version and I still got the issue. I upgraded the node pool to version 6.12.4 and I still get the delete error:

```
 ---> Running in b5eb1cd90ea6
rm: can't remove '/tmp/hugo_theme/static/img': Directory not empty
rm: can't remove '/tmp/hugo_theme/static': Directory not empty
rm: can't remove '/tmp/hugo_theme': Directory not empty
The command '/bin/sh -c rm -rf /tmp/hugo_theme' returned a non-zero code: 1
```
I am not 100% certain but I think my issue is related to this one - https://stackoverflow.com/questions/46824425/docker-is-unable-to-delete-a-directory-when-building-images

Any idea on why I seem to be running into this issue on Shippable?

**Comment by trriplejay** [comment]
Hmm, although the runtime version is updated for the node pool, the kernel version of the underlying host is the same, so it might be worthwhile to also upgrade the node pool to use u16 as the base, which has a newer kernel

**Comment by nathanaherne** [comment]
I tried to upgrade Ubuntu but Ubuntu 14.04 is the only option available to me. I will try again right now.

**Comment by nathanaherne** [comment]
Tried for the 3rd time, no option other than Ubuntu 14.04

**Comment by trriplejay** [comment]
Switching to 16 is a little different from switching the runtime. You'll have to add a new cluster license from the billing page, selecting 16.04 on demand, then you can create a new node pool that targets 16.04

**Comment by trriplejay** [comment]
I can take care of this transition if you'd like!

**Comment by nathanaherne** [comment]
Thank you for showing me how to do this and offering to do it for me. To save you having to do it, I have made this change myself.

**Comment by trriplejay** [comment]
oh, great! glad you figured it out. Let me know if you have any other questions.

**Comment by nathanaherne** [comment]
Thank you for your help @trriplejay
