### ISSUE TITLE
Delete my account

### ISSUE THREAD

**Issue by eunomics-github** [Shippable/support#4693]
Hello,
   I requested that my account be deleted months ago, it all appeared to work, but my accounting department indicates that we are still being charged on our credit card.
   Please immediately delete my account and stop charging my credit card.
Thank you,
Jim Burns

**Comment by manishas** [comment]
Hello,  thanks for reaching out. 

We canceled your subscription today so your card will not be charged again. We will also issue a refund for all charges after 8/2018 since that’s when we found a request to cancel.

**Comment by eunomics-github** [comment]
Thank you very much!

Jim Burns



________________________________

**Comment by rageshkrishna** [comment]
I'm closing this as the billing issue has been resolved. Feel free to re-open it if there's anything else we can help with.
