### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by it-svit-sbn** [Shippable/support#4696]
I tried to check build results for some private repo first time and got the message.
I remember that I logged in with Github account but was blocked immediately.
Please unblock. This Github account - it-svit-sbn
Thanks in advance.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by it-svit-sbn** [comment]
Thanks, everything is fine.
