### ISSUE TITLE
Error occurring when reenabling a disabled project

### ISSUE THREAD

**Issue by wtaylor45** [Shippable/support#4697]
### Description of your issue:
When I click to re-enable a project, I am met with this error:

deleteResourceById failed for id: 97142 returned error deleteVersionByResourceId for resourceId:97142 returned error: versions.destroy failed for resourceId: 97142 returned error: update or delete on table "versions" violates foreign key constraint "jobs_versionId_fkey" on table "jobs"

Looks like there's some stale out there from the last time I had it enabled. Anything I can do on my end to resolve this?

Thanks!

**Comment by Bharath92** [comment]
Yeah, there was some stale data that didn't get cleaned up while the project got disabled. We have opened an internal ticket for it.

The data has been cleaned up at our end. Could you please try re-enabling the project and let us know if it works?

**Comment by rageshkrishna** [comment]
We're making some changes to the disable/enable flows to make sure this doesn't happen again. I expect this to ship with our 7.1.4 release towards the end of next week.

**Comment by wtaylor45** [comment]
Sorry just now getting back to this! Awesome to hear, thanks a lot for your help!
