### ISSUE TITLE
cloudformation template error : Unable to assume role and validate the specified targetGroupArn. Please verify that the ECS service role being passed has the proper permissions

### ISSUE THREAD

**Issue by irfanjs** [Shippable/support#4698]
**what is expected :** 
cloud formation template should execute successfully and build the infrastructure 

**what is the issue:** 
I'm creating following template to create the AWS ECS fargate cluster along with service, task definition and container definition. the existing resources such as VPC, TargetGroup, Role , LoadBalancer, i would like to consume as it is. 

please refer below : 

```
AWSTemplateFormatVersion: 2010-09-09
Description: An example CloudFormation template for Fargate.
Parameters:
  "vpcabcvmn":
    Type: AWS::EC2::VPC::Id
    Default: "vpc-08e61a299d1e32d64"
  "abcvmnSubnetA":
    Type: AWS::EC2::Subnet::Id
    Default: "subnet-09bf5a57cca8addd7"
  "abcvmnSubnetB":
    Type: AWS::EC2::Subnet::Id
    Default: "subnet-0ba623cfd9f403987"
  TargetGroupName:
    Type: String
    Default: abc-tg

  Image:

    Type: String

    Default: 890543041640.dkr.ecr.eu-central-1.amazonaws.com/abcvmn:latest

  ServiceName:

    Type: String

    Default: abc-service-dev

  ContainerPort:

    Type: Number

    Default: 8080

  LoadBalancerPort:

    Type: Number

    Default: 80

  HealthCheckPath:

    Type: String

    Default: /healthcheck

  HostedZoneName:

    Type: String

    Default: abc.com

  Subdomain:

    Type: String

    Default: abc-service-dev

  MinContainers:

    Type: Number

    Default: 2

  MaxContainers:

    Type: Number

    Default: 10

  AutoScalingTargetValue:

    Type: Number

    Default: 50

Resources:

  Cluster:

    Type: AWS::ECS::Cluster

    Properties:

      ClusterName: abc-fargatecluster-dev

  TaskDefinition:

    Type: AWS::ECS::TaskDefinition

    DependsOn: LogGroup

    Properties:

      Family: abc-taskdef-dev

      NetworkMode: awsvpc

      RequiresCompatibilities:

        - FARGATE

      Cpu: 512

      Memory: 1GB
Fargate tasks to make API calls to Amazon ECR."
      ExecutionRoleArn: arn:aws:iam::890543041640:role/ecsTaskExecutionRole
      TaskRoleArn: arn:aws:iam::890543041640:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: abc-service-dev
          Image: 890543041640.dkr.ecr.eu-central-1.amazonaws.com/abcvmn:latest
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: eu-central-1
              awslogs-group: /ecs/abc-taskdef-dev
              awslogs-stream-prefix: ecs
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref ServiceName, ContainerSecurityGroup]]
      VpcId: vpc-08e61a299d1e32d64
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref ServiceName, LoadBalancerSecurityGroup]]
      VpcId: vpc-08e61a299d1e32d64
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref LoadBalancerPort
          ToPort: !Ref LoadBalancerPort
          CidrIp: 0.0.0.0/0
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 2
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref abcvmnSubnetA
            - !Ref abcvmnSubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroupName
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60
      Name: !Join ['', [!Ref ServiceName, LoadBalancer]]
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets:
        - !Ref abcvmnSubnetA
        - !Ref abcvmnSubnetB
  DNSRecord:
    Type: AWS::Route53::RecordSet

    Properties:
      HostedZoneName: !Join ['', [!Ref HostedZoneName, .]]
      Name: !Join ['', [!Ref Subdomain, ., !Ref HostedZoneName, .]]
      Type: A
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/abc-taskdef-dev
Outputs:
  Endpoint:
    Description: Endpoint
    Value: !Join ['', ['https://', !Ref DNSRecord]]

```
following is the error message in the failure event of AWS logs : 

> Unable to assume role and validate the specified targetGroupArn. Please verify that the ECS service role being passed has the proper permissions

i m not sure what is the wrong. if i create the cluster using AWS management console , it works great with these network resources, but not working with cloud formation template . 

please suggest

**Comment by a-murphy** [comment]
It looks like you are specifying a target group name instead of a target group ARN in the load balancer.  The [AWS CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-loadbalancers.html) states the the `LoadBalancers` in the service should have an ARN, not a name, for `TargetGroupArn` when it is specified.  Could you make sure that your target group ARN is of the format `arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/my-targets/73e2d6bc24d8a067`, although, of course, correct for your target group, account, and region?

**Comment by irfanjs** [comment]
Great. it worked . awesome !!!
Let me test thoroughly and get back

**Comment by a-murphy** [comment]
Let us know if you run into any problems and we can reopen this.

**Comment by 3j0s** [comment]
Greetings!

I have the same issue:  
I'm using : 
``Terraform v0.12.23
+ provider.aws v2.50.0
+ provider.github v2.4.0 ``
This is the issue: 
Error: InvalidParameterException: Unable to assume role and validate the specified targetGroupArn. Please verify that the ECS service role being passed has the proper permissions. "cicd_ecs" 

This is the portion of code that it doesn't work:
 
``resource "aws_ecs_service" "cicd_ecs" {
  name                = "cicd-ecs"
  cluster              = aws_ecs_cluster.cicd_ecs_cluster.id
  task_definition = aws_ecs_task_definition.ecs-service.arn
  iam_role          = var._ec2role_arn_

  load_balancer {
      target_group_arn = aws_lb_target_group.cicd-lb-tg.arn
      container_name   = var._ecs_container_name_
      container_port     = 8080
  }

  deployment_controller {
    type = "CODE_DEPLOY"
  }

  placement_constraints {
    type       = "memberOf"
    expression = "attribute:ecs.availability-zone in [us-east-2a]"
  }

  depends_on = [aws_lb_target_group.cicd-lb-tg]
}
``

I'm able to build the 'lb' and the 'target', but something happend after that. So Did i missed something? or Am i doing something wrong?

thx in advance
