### ISSUE TITLE
What are the Windows Server 2016 on demand software?

### ISSUE THREAD

**Issue by BotellaA** [Shippable/support#4705]
I would like to purchase a Windows Server 2016 node but I do not know what is installed on this image.
I would need CMake, Git, NodeJS and Visual Studio C++ (at least 2015).

How to get this information? How to install something if it is not on the image?

Thanks for your answer

**Comment by Bharath92** [comment]
The list of softwares installed is documented here: http://docs.shippable.com/platform/runtime/machine-image/ami-v6124/

The versions of softwares installed differ in each runtime version of on-demand nodes. Here is the list of all the available on-demand runtime versions: http://docs.shippable.com/platform/runtime/machine-image/ami-overview/

To install packages of your own, you could use a package manager like [chocolatey](https://chocolatey.org/), which we internally use to install the software.

P.S., Windows on-demand nodes were introduced from [v6.3.4](http://docs.shippable.com/platform/runtime/machine-image/ami-v634/).

**Comment by BotellaA** [comment]
Thanks. According to the doc chocolatey is not installed. 
So I need to install it in my runSh and then use it to install other packages?

**Comment by rageshkrishna** [comment]
That's a miss in the docs. We use choco to set up the node, so it's most certainly available for you to use right out of the box.

**Comment by BotellaA** [comment]
Great! I will try that.
