### ISSUE TITLE
Failed to install bundler with Ruby 2.6.0

### ISSUE THREAD

**Issue by christianmoretti** [Shippable/support#4709]
Hi, we are trying to run some tests but the bundler is failing during the RVM installation. Is there any workaround to fix this error?

Build: https://app.shippable.com/github/LinckyDev/simulie-api/runs/2/1/console

<img width="713" alt="image" src="https://user-images.githubusercontent.com/1626925/51366429-3fee3a00-1ac4-11e9-8022-6cc7fe9c308f.png">

shippable.yml
```language: ruby
rvm:
  - 2.6.0

# Services that are used by tests
services:
  - redis
  - postgres

# use this to control what branches get built.
branches:
  only:
    - master
    - develop

# Environment
env:
  global:
    - CI_REPORTS=shippable/testresults COVERAGE_REPORTS=shippable/codecoverage
    - AWS_REPO_URL=''
    - SHIPPABLE_POSTGRES_VERSION=""
    - GEM_HOME=vendor/bundle

# Build and test
build:
  # Cache
  cache: false
  cache_dir_list:
    - $SHIPPABLE_BUILD_DIR
  pre-ci:
    - mkdir -p $CI_REPORTS
    - mkdir -p $COVERAGE_REPORTS
  ci:
    - cd $SHIPPABLE_BUILD_DIR
    - cp -pRfv .env.shippable .env
    - bundle config --global path "$SHIPPABLE_BUILD_DIR/$GEM_HOME"
    - bundle config --global bin "$SHIPPABLE_BUILD_DIR/$GEM_HOME/bin"
    - bundle package --all
    - bundle install
    - bundle exec rails db:create
    - bundle exec rails db:migrate
    - bundle exec rails db:seed
    - bundle exec cucumber --tags @api --format junit --out $CI_REPORTS
    - bundle exec rspec --format RspecJunitFormatter --out $CI_REPORTS/rspec.xml
```

Thanks!

**Comment by Bharath92** [comment]
This is happening because `rvm 2.6.0` installs `gem` CLI with version > 3.0.0, where the `gem install` command doesn't support options like `--no-ri`/`--no-rdoc`. We are currently rolling out a release where we are removing the references to `--no-ri`/`--no-rdoc` from the `gem` commands we use internally, when the `gem` CLI version is greater than 3. We will post an update on this issue once the release is done and you could try running the same build again.

**Comment by christianmoretti** [comment]
Ok, thanks @Bharath92 please keep me in touch.
Best regards!

**Comment by Bharath92** [comment]
The [latest release](https://github.com/Shippable/admiral/blob/master/releaseNotes/v7.1.1.md) is out now. The above issue must be fixed. Could you retry running the build and let us know if it works?

**Comment by christianmoretti** [comment]
Hi @Bharath92, the build has been executed. Thanks for the support!
