### ISSUE TITLE
Gradle 5 Support

### ISSUE THREAD

**Issue by neilouellette** [Shippable/support#4710]
This is a feature request.

The latest couple shippable machine images (6.10.4 and 6.12.4) added jdk11 into the mix. Since gradle only officially [supports java 11 with v5+](https://docs.gradle.org/5.0/release-notes.html#java-11-runtime-support), is there any plan to add AMIs with gradle 5+?

**Comment by rageshkrishna** [comment]
Gradle 5 is currently being tested for our next release of drydock images, which should be in a couple of weeks.

**Comment by neilouellette** [comment]
Great. Thanks!

**Comment by rageshkrishna** [comment]
@neilouellette Sorry about the late update, but the v7.1.4 images that were released a few weeks ago have Gradle 5 on them.

Ref: http://docs.shippable.com/ci/java-continuous-integration/#gradle-and-ant-compatibility
