### ISSUE TITLE
Cannot create a new account at shippable using my bitbucket account

### ISSUE THREAD

**Issue by saeedsq** [Shippable/support#4717]
Error
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

**Comment by rageshkrishna** [comment]
@saeedsq I see that your account is no longer blocked. Please let me know if you're still unable to login. Thanks!

**Comment by saeedsq** [comment]
@rageshkrishna Thanks for quick reply,  my account is created by bitbucket `saeed-upkook` and is blocked

**Comment by rageshkrishna** [comment]
Ok, I've unblocked that account now. Please try again.

**Comment by saeedsq** [comment]
Thanks, it works now.
