### ISSUE TITLE
Your account has been blocked

### ISSUE THREAD

**Issue by htpc-helper** [Shippable/support#4721]
Hey Shippable support

I am so excited to try your service. I created a new BitBucket account separate from my other projects with the username cam-shippable and I was blocked by your security service. Would you mind unblocking me?

Cheers!

**Comment by ankul-shippable** [comment]
@htpc-helper Your account has been unblocked. Sorry for the trouble.

**Comment by htpc-helper** [comment]
Thank you for your prompt response!
