### ISSUE TITLE
mysql "Can't connect to local MySQL server through socket" error on 6.12.4

### ISSUE THREAD

**Issue by clippermadness** [Shippable/support#4722]
We have a build where we configure mysql a bit before compiling and running tests. The build was working fine on 6.7.4. When we upgraded to 6.12.4 and made no changes to our shippable.yml, the build failed on the mysql config steps with this error:

`mysql -e "CREATE USER redacted@localhost IDENTIFIED BY 'redacted';"
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

If we add `--protocol=TCP` to the mysql commands, everything works fine. Mysql is listed in our services section and appears to start fine.

Build log:
https://app.shippable.com/bitbucket/thetalake/classifier/runs/439/1/console

**Comment by a-murphy** [comment]
Although it sounds like you've already found a workaround, adding [`shippable_retry`](http://docs.shippable.com/ci/retry-command/#retrying-a-command) in front of the command may also help if it does not fail consistently.  With `shippable_retry`, a command will be tried three times if it fails, giving it additional chances to succeed.

We're still attempting to reproduce the error, but so far have not been successful.  Have you noticed the same error in any other projects?

**Comment by clippermadness** [comment]
I just tried and can't reproduce it either. Maybe it was some transient error. Closed: Gamma rays. :)

**Comment by rageshkrishna** [comment]
Thanks for the update. Please reopen this issue if you do run into this again. We've tried a bunch of things to try and reproduce it ourselves but haven't been able to.
