### ISSUE TITLE
Problem with resetting cache? 

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#4724]
Hi, I'm getting some build errors when trying to build a project for which I updated some dependencies (https://app.shippable.com/github/jacopo-chevallard/BEAGLE/runs/240/1/console). It looks like Shippable is using a cached version of the dependencies, while I want to re-compile them all. I tried to clear the cache from the GUI and to add ``[reset cache]`` to the commit message firing the build, but it looks like it is still using the cache (i.e., CMake finds existing libraries in ``/root/install/lib/``)

Any idea of what might be going on?

Thanks !

**Comment by a-murphy** [comment]
The linked run does not appear to be using a Shippable cache or have anything cached on the node.  Since you are using a custom image, perhaps the dependencies were added to your image in the past to speed up your builds.  If they are in the `/root/install/lib` directory of your custom build image, it would make the most sense to rebuild your image either with the new versions or without installing the dependencies.  You could also add a command to remove the problematic files in the `ci` section of your script.

**Comment by jacopo-chevallard** [comment]
Thanks for the quick reply ! That's what I thought as well, but strangely I couldn't find those dependencies when running the image on my local machine and exploring the folder ``/root``, which seems empty... I'll keep looking!

**Comment by jacopo-chevallard** [comment]
If I explore the Docker image from within the Shippable build I still cannot find the libraries, while CMake finds them (https://app.shippable.com/github/jacopo-chevallard/BEAGLE/runs/243/1/console)... perhaps I'm not seeing something obvious, but I don't understand where do those libraries come from during the build...

**Comment by a-murphy** [comment]
Have you tried running your CMake script in your custom image locally?  We haven't identified any likely reasons why this would be only occur on Shippable and it may be easier for you to debug this locally.  We also support [SSH access for debugging](http://docs.shippable.com/ci/ssh-access/#which-machine-image-supports-ssh-access-for-debugging?) in paid subscriptions that would make it possible to see the file structure after the failure and execute commands in the build container.

**Comment by jacopo-chevallard** [comment]
Yes, this is what I'm going to do, thanks again for the support and for the great service you provide !

**Comment by jacopo-chevallard** [comment]
Closing, the problem is indeed somewhere in my CMake configuration scripts !
