### ISSUE TITLE
Cannot Upgrade Plan (Failed to update Braintree subscription)

### ISSUE THREAD

**Issue by robmoore** [Shippable/support#4730]
When trying to upgrade to a second node, I'm seeing the Braintree subscription error. There's no further info so hard to know what the problem is.

**Comment by rageshkrishna** [comment]
@robmoore I looked in to this and found that your transactions failed with an error of "processor declined". You will need to check with your bank about this. Alternatively, you can try using a different card.

**Comment by a-murphy** [comment]
It looks like you've been able to update your subscription.  Let us know if you still have any trouble.
