### ISSUE TITLE
Docker "Unknown flag"

### ISSUE THREAD

**Issue by jacopo-chevallard** [Shippable/support#4732]
Hi, I'm getting a Docker error 
```
Step 5 : FROM scratch
 ---> 
Step 6 : COPY --from=0 /container.beagle/ /
Unknown flag: from
```
when running this build https://app.shippable.com/github/jacopo-chevallard/BEAGLE/runs/263/1/console, and I was getting an error also when using the 
```
FROM foo as bar
```
syntax. I tried to update Docker within the container that I boot, but apparently this is not the right way to have an updated Docker version (https://github.com/Shippable/support/issues/4468).

If I run inside my ``build_ci`` section
```
docker --version
Docker version 1.9.1, build a34a1d5
```
Is this the expected available version? Am I missing something? thanks !

**Comment by Bharath92** [comment]
The `runtime version` your build is running on is a deprecated version. Please go to [https://app.shippable.com/subs/github/jacopo-chevallard/nodePools](https://app.shippable.com/subs/github/jacopo-chevallard/nodePools) > Click on `Edit`. In the `Runtime Version` section, you should be able to update the `runtime version` of your node pool to a newer version, which have the newer docker releases installed on the `on-demand` node brought up to run your builds.

http://docs.shippable.com/platform/runtime/machine-image/ami-overview/

**Comment by jacopo-chevallard** [comment]
Thanks so much for the super quick answer ! I didn't know users were responsible for manually updating the node version, but I guess this is necessary to prevent breaking build with automatic updates ! I'm re-running the build, I will then update here

**Comment by jacopo-chevallard** [comment]
Updating the node version solved the problem, closing
