### ISSUE TITLE
Failed build EOF/use of closed network connection

### ISSUE THREAD

**Issue by vidavidorra** [Shippable/support#4733]
Yesterday I had two builds failing, one due to `EOF` and another one due to `use of closed network connection`. Both builds from a build matrix.

This morning I restarted the build in and now they succeeded (one is still running ATM). The change I made that originally triggered this build was very minimal, see [here](https://github.com/vidavidorra/linux-cmake/commit/5929df67acafd41a07bdd8f9847ed3f812d15b1b), so I don't know why they failed and succeeded, with the exact same code, this morning. Any ideas why? Maybe due to server maintenance of the build servers?

Failed build(s): [6](https://app.shippable.com/github/vidavidorra/linux-cmake/runs/6/summary/console)
New build(s): [7](https://app.shippable.com/github/vidavidorra/linux-cmake/runs/7/summary/console)

**Comment by rageshkrishna** [comment]
Hi! Your subscription's [default node pool](https://app.shippable.com/subs/github/vidavidorra/nodePools/71636/view) is currently using a deprecated [runtime version](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/). It's possible that the docker version your build is using has bugs that have been fixed by now.

You can try [editing your node pool](https://app.shippable.com/subs/github/vidavidorra/nodePools/71636/edit?redirectUrl=~2Fsubs~2Fgithub~2Fvidavidorra~2FnodePools~2F71636~2Fview) to use a more recent runtime version.

Ref: http://docs.shippable.com/platform/tutorial/runtime/manage-node-pools/#managing-node-pools

**Comment by vidavidorra** [comment]
Thanks for the quick reply! I'll update my node pool to the latest version (v6.12.4), I had no idea that I was using a deprecated version. I'll close this ticket for now as my build is currently working and using the new node pool will hopefully fix this. Am I normally supposed to keep track myself of when new node pool versions are being released and update them If I want to upgrade?

If I run into the issue again I'll reopen this or create a new ticket, referencing this one.

@rageshkrishna Thanks for your help

**Comment by vidavidorra** [comment]
@rageshkrishna Another quick question, I didn't get any email that the build has failed, even though the previous build succeeded and email settings in the [yml file](https://github.com/vidavidorra/linux-cmake/blob/develop/shippable.yml#L22-L29) are set to change. So after finishing build 6, which failed, I should have received an email right, as build 5 was success?

**Comment by rageshkrishna** [comment]
When you customize email notifications using the YML, it's necessary to also specify `recipients`. Take a look at http://docs.shippable.com/ci/email-notifications/ for some examples.

**Comment by vidavidorra** [comment]
That documentation reads

> This overrides the default setting of 'last committer' and 'project owner(s)' email address that we get from your source control management system (GitHub/Bitbucket). 

So I'd expect it to default to the project owner (me) and/or last committer (also me), right? I'll try to specify the value anyways.

**Comment by rageshkrishna** [comment]
Yeah, the documentation definitely needs improvement there. You can use `--last_committer` and `--last_author` in your recipients list to preserve the default behaviour, but it's still necessary to specify them.
