### ISSUE TITLE
Use aws-cli in ci via integrations

### ISSUE THREAD

**Issue by cpoll** [Shippable/support#4735]
I'm trying to use `aws s3 cp` in the `build_post_ci` section. I've created an AWS Keys integration, and am placing it in the `integrations:` section.

Under the `integrations:  deploy:` subsection it works, but adds an `aws_eb_deploy` build phase and fails (the account doesn't have permission for Elastic Beanstalk)
Under the `integrations: hub:` subsection (with type: ecr) it fails in the `ecr_login` build phase (the account doesn't have permission for ECR)
Under the `integrations: generic:` subsection it doesn't work (no authentication)

This behaviour is consistent with what I'm reading in http://docs.shippable.com/platform/workflow/config/#integrations, but is there a way to get an aws integration without side-effects (only `aws configure`), or do I need to set a secure parameter and do `aws configure` manually?

**Comment by a-murphy** [comment]
If you want to use an AWS integration without ECR or deploying to Elastic Beanstalk, I would suggest adding an [`integration` resource](http://docs.shippable.com/platform/workflow/resource/integration/) as an `IN` to the `runCI` job as part of an Assembly Line.  Directions to add an Assembly Line to your subscription are [here](http://docs.shippable.com/platform/tutorial/workflow/add-assembly-line/) and information about adding the existing CI job to your Assembly Line [here](http://docs.shippable.com/platform/workflow/job/runci/#how-do-you-use-it-in-assembly-lines).

Alternatively, you can use the AWS environment variables (listed [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html)) in a [key-value pair integration](http://docs.shippable.com/platform/integration/key-value/) to configure the AWS CLI without `aws configure`.  A key-value pair integration can be listed in the `integrations: generic` section.  This would usually by `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in the key-value pair integration, but you can set more of the AWS options to specify a non-default region.

**Comment by cpoll** [comment]
Thanks @a-murphy. In retrospect, using a key-value pair integration was obvious. I'll explore the integration resource method soon, as it sounds more secure than using envvars.
