### ISSUE TITLE
"Scripts" tab is empty

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4737]
Currently the *Scripts* tab of any job is empty:

![image](https://user-images.githubusercontent.com/5037116/52486860-8d8a2e00-2bbc-11e9-989c-593f02efa69f.png)

Normally all scripts used in the build are shown here.

**Comment by a-murphy** [comment]
We no longer keep the scripts for all jobs after they are complete.  Scripts should be available for thirty days for unsuccessful jobs and are removed shortly after successful jobs are completed.  We'll discuss ways to improve the UI internally to reduce future confusion.

**Comment by manishas** [comment]
This is by design, so closing.
