### ISSUE TITLE
Builds failing with 6.12.4 and openjdk11

### ISSUE THREAD

**Issue by athrane** [Shippable/support#4739]
Building using image 6.12.4 using openjdk11 fails with the exception

`(Failed to read artifact descriptor for org.zkoss.zk:zkmax:jar:7.0.2: Could not transfer artifact org.zkoss.zk:zkmax:pom:7.0.2 from/to repository.springsource.snapshot (http://repo.springsource.org/snapshot): Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> `

Looking around I found the issue #4685, where the workaround seems to be the inclusion of 
`- source /etc/drydock/.env`

Adding this to the build enables it to complete. But is this a permanent solution?

Link to failed build:
https://app.shippable.com/github/athrane/pineapple/runs/197/summary/console

**Comment by a-murphy** [comment]
We are expecting to release new image versions in the near future that should not have this problem and so will not require `source /etc/drydock/.env`.  You will have to continue to use the `source /etc/drydock/.env` workaround while on v6.12.4.

**Comment by athrane** [comment]
Thank you for the update.

**Comment by a-murphy** [comment]
The recently released `v7.1.4` images should not have this problem, so would not require `source /etc/drydock/.env`.  Directions to update your subscription node pool to newer default images are available [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) if you want to update to v7.1.4.  Let us know if you still have any trouble.

**Comment by rageshkrishna** [comment]
@athrane The latest images should be working fine. Feel free to re-open this issue if it isn't resolved for you. Thanks!
