### ISSUE TITLE
Specify secrets in containerDefintions via parameter store

### ISSUE THREAD

**Issue by cgspohn** [Shippable/support#4741]
We need to pass a `secrets` configuration within the `containerDefinitions` for a ECS Task.  I tried add it it in the dockerOptions resource, but got an error during the deploy stage:
https://app.shippable.com/github/shiftgig/jobs/lightbulb_api-dev-2-deploy/builds/5c61a535becdb307000b6c4a/console

How should I specify the `secrets` in Shippable?
Reference from AWS:
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html

**Comment by a-murphy** [comment]
It looks like you are using an AWS feature that was added in a version of the AWS SDK newer than the one we are currently using for deploy jobs.  We'll let you know when we schedule the next AWS SDK update.

**Comment by cgspohn** [comment]
Thanks @a-murphy - just so I can plan accordingly, when could we expect the AWS SDK update to happen? A couple days, a couple weeks?

**Comment by a-murphy** [comment]
It looks like this will be in the next release, so will most likely be available in the next week or two.

**Comment by a-murphy** [comment]
The AWS SDK used in deploy jobs has  been updated.  The `secrets` option should be available now.
