### ISSUE TITLE
Hub login fail

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#4742]
https://app.shippable.com/github/Knowre-Dev/USKMU-SERVER/runs/4531/summary/

The build is failing with the following message:
```
echo 'Hub login failed'
  cat /build/hub_login_out
cat: /build/hub_login_out: No such file or directory
```
I tried several different valid accounts for logging in but it didn't help.
My `shippable.yml` includes:
```
  hub:
    - integrationName: "Knowre Docker Hub"
      type: docker
```
This is pretty serious because we cannot deploy anything at all now.

**Comment by gtnx** [comment]
Same here. nothing has changed on our side

**Comment by ankul-shippable** [comment]
@Kivol @gtnx we are looking into this, will post an update soon. Thanks.

**Comment by rageshkrishna** [comment]
We've identified the issue and will be deploying a fix in a few minutes.

**Comment by Kivol** [comment]
Is it fixed now?

**Comment by MattiLahtinen** [comment]
Yeah, this is also occurring on my team production deployments. does this have something to do with the deprecation of the docker method?

**Comment by rageshkrishna** [comment]
Sorry about the delayed update. The test for this fix took a little longer than I expected, but we are ready to roll it out now.

We found that there was an issue with the way the docker login was being handled on CI projects that were enabled very long ago (prior to March 2017), and haven't yet been [hooked up to pipelines](http://docs.shippable.com/platform/workflow/job/runci/#how-do-you-create-a-runci-job?). In the v7.1.4 release we made an improvement to the way we handle Docker passwords, which unfortunately causes a failure in these early CI projects.

If you need an immediate solution, using the "Hook Pipelines" button in the project settings linked above will unblock you. If you would rather not do that, we will be deploying a fix within 30 minutes.

**Comment by Kivol** [comment]
Verified that it is fixed. Thanks for the effort!
