### ISSUE TITLE
Builds stuck on Provision Node for a long time

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#4744]
Our builds have been stucked on provision node for quite a while. We killed a few after 15 minutes but the next one are still stuck.

https://app.shippable.com/accounts/5b69c68cdfcdc60600fa1ab8/dashboard

Can you advise, please? Thanks

**Comment by trriplejay** [comment]
@Kirtap sorry about that. we had a backup in our queue causing delayed provisioning of dynamic nodes. The queue has caught up now and we're continuing to investigate the root cause. sorry for any inconvenience! Let us know if you're having any other problems.

**Comment by Kirtap** [comment]
will do
