### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters ...

### ISSUE THREAD

**Issue by Borda** [Shippable/support#4745]
I am using the same configuration and testing very similar code for a while, but recently I started to get ASCII failer on Python 2.7 even for commits that earlier (last week) passed without any problem. The sample failer is following: 
* `UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-40: ordinal not in range(128)`
* `UnicodeEncodeError: 'ascii' codec can't encode characters in position 37-39: ordinal not in range(128)`

before: https://app.shippable.com/github/Borda/pyImSegm/runs/312/summary/console
after: https://app.shippable.com/github/Borda/pyImSegm/runs/318/summary/console

before: https://app.shippable.com/github/Borda/BIRL/runs/527/summary/console
after: https://app.shippable.com/github/Borda/BIRL/runs/531/summary/console

Any idea what changed during last week?

**Comment by a-murphy** [comment]
It looks like two of the dependencies of your projects have in common have been updated to newer versions.  The version of `scipy` has changed from 1.2.0 to 1.2.1 and `tqdm` from 4.30.0 to 4.31.1.  Given the locations of the errors, I suspect that something about the new version of `tqdm` isn't compatible with how you are using it in your project with Python 2.7.  A `tqdm` release list is [here](https://github.com/tqdm/tqdm/releases) if you need to see what has changed in `tqdm`.  You can try specifying a more specific version of `tqdm` in your `requirements.txt` file to confirm if it is related to the `tqdm` update.

For the second linked error, some `apt-get` errors result from running on old images, which haven't been updated in quite a while.  You may want to try [updating the machine image in your node pool](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) to a newer version to user newer default images in your subscription.

**Comment by Borda** [comment]
Thank you, it helped. Just wondering if there is a newer version of ubuntu then 14..04?

**Comment by a-murphy** [comment]
Both nodes and images are available with Ubuntu 16.04.

To update the nodes to 16.04:
1. [Update your plan](http://docs.shippable.com/platform/management/subscription/billing/) with an Ubuntu 16.04 SKU.
2. Make sure your subscription has a [node pool](http://docs.shippable.com/platform/management/subscription/node-pools/) using the Ubuntu 16.04 SKU with the correct number of nodes.
3. Either make the Ubuntu 16.04 node pool the default for your subscription or [specify the node pool in your shippable.yml](http://docs.shippable.com/ci/runtime-config/#runtime-with-one-node-pool).

To update the images, but not nodes, to Ubuntu 16.04:

Most of the default images are already Ubuntu 16.04.  You can [update the machine image](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) in your existing subscription node pool to use newer images by default.  Only the "stable" and "unstable" machine images, which are the oldest two, use Ubuntu 14.04 build images by default.  If you only want to change the image for one project and not the rest of your subscription, you can also set an image in the `pre_ci_boot` section of your `shippable.yml`.
