### ISSUE TITLE
Bitbucket team projects not visible to me but visible to othes

### ISSUE THREAD

**Issue by rxjx** [Shippable/support#4749]
I just joined Shippable to my company's Bitbucket account but I cannot see any of our projects. Other team members can see them. I can push code to these projects in Bitbucket. 

If I try to sync, it just stops after running for a while without actually syncing.

**Comment by a-murphy** [comment]
Would you mind sharing your Bitbucket username?  I'm having trouble finding your account.

**Comment by rxjx** [comment]
It’s rohitj1221

**Comment by a-murphy** [comment]
It looks like your account sync was delayed (we're investigating what caused the delay).  It has now been synchronized, so could you check again?

**Comment by rxjx** [comment]
Yep, works now. Thanks.
