### ISSUE TITLE
Account has been blocked

### ISSUE THREAD

**Issue by RKawpto** [Shippable/support#4750]
#### ERROR:
An error occured, please choose an action.
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

I created a fresh Github account for my studies' project about Shippable. Apparently it got immediately blocked.
Github account: https://github.com/RKawpto
email: george.temp@onet.eu

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by a-murphy** [comment]
It looks like you've been able to log in.  Let us know if you have any other problems.
