### ISSUE TITLE
Builds targeting Oracle JDK 10 failing

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#4751]
Our YML file is as follows:

```
language: java
jdk:      oraclejdk10
build:
  pre_ci_boot:
    image_name: drydock/c7javall
    image_tag:  v6.4.4
    options:    "-e HOME=/root"
    pull:       true
  ci:
    - shippable_retry mvn clean test
```

However, the following code does not compile and fails builds:

```
enum Color { RED, BLUE, GREEN }

java.util.Set.of(Color.RED, Color.BLUE);
```

Note that [static overloaded `of` methods](https://docs.oracle.com/javase/9/docs/api/java/util/Set.html) were added to JDK 9 and therefore the builds should not fail.

The following lines are printed at the top of the Shippable build, confirming that JDK 10 is in use:

```
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

**Comment by rageshkrishna** [comment]
@manish-in-java There are a couple of bugs around this in the earlier dry-dock images. As Java 10 is now EOL, would it be possible for you to use Java 11 instead? The latest drydock release (v7.1.4) has the necessary fixes to make this work correctly.

**Comment by manish-in-java** [comment]
@rageshkrishna, thanks, I have upgraded to v7.1.4 and OpenJDK 11 and can see the builds working now.
