### ISSUE TITLE
Bitbucket Integration not working

### ISSUE THREAD

**Issue by jtunison** [Shippable/support#4754]
I attempted to remove & re-add the bitbucket integration.

After adding a bitbucket integration I get the error:
"Subscription integrations could not be loaded. Integration permissions will not be displayed."

No integration appears to have been added.

Name: bitbucket
Integration Type: Bitbucket
Url: https://bitbucket.org
Token: ********

Token generated from https://bitbucket.org/account/user/{username}/app-passwords

**Comment by a-murphy** [comment]
The Bitbucket integration expects an OAuth token for the Shippable OAuth consumer.  I would recommend selecting an account integration to link to the subscription integration instead of creating an integration directly in the subscription for Bitbucket.  However, that does not explain why it can't be displayed.  Would you mind including either an account or subscription name or an ID from the bottom of a page so that we can see which subscription has this problem?

**Comment by jtunison** [comment]
Account Id: 5900fe62a527e80700a02de0

**Comment by jtunison** [comment]
If I use OAuth instead of App Passwords to get a Bitbucket API Token, it looks like the intended path is to install the Shippable/Bitbucket App from the Bitbucket Marketplace?  However I can't do this because it is currently not available:  

https://marketplace.atlassian.com/apps/1215081/shippable-ci-cd-for-bitbucket/version-history

"This app is hidden from public view because it no longer meets the requirements for Atlassian Marketplace."

**Comment by a-murphy** [comment]
It looks like you should be able to log out of Shippable and back in to generate a new account integration.  I'm not sure what happened to your Bitbucket integration, but they are not usually created manually.  They are automatically created when logging in with Bitbucket.

**Comment by jtunison** [comment]
I logged out & logged back in again - this time I got the Bitbucket authorization page and I can see the account.  

New problem:  I can't re-add the syncRepo.  When I try, I get "Please make sure subscription integration used to add syncRepo has admin access on project:5900fe64fa2ac30800868409"

**Comment by a-murphy** [comment]
The only Bitbucket integration in that subscription is linked to another user's Bitbucket account integration, and that user does not have access to that project.  If you go to the subscription integrations page under the gear on the top right of the subscription dashboard, you can see whose account is linked to the integration.  If that user should have access, you can ask that user to click "sync" on the account profile page.  Or you can edit the integration to link to your own Bitbucket integration or add a second Bitbucket integration to the subscription that links to your account integration and use that to add your syncRepo.

**Comment by jtunison** [comment]
Thanks.  Resolved!
