### ISSUE TITLE
My account is blocked

### ISSUE THREAD

**Issue by rameshjatiya1988** [Shippable/support#4759]
### Description of your issue:
I tried to register for Shipplable using my Github account , It gave me error as "Your account is Blocked"

**Comment by rageshkrishna** [comment]
@rameshjatiya1988 I've unblocked your account. Please try logging in again. Thanks!

**Comment by rageshkrishna** [comment]
@rameshjatiya1988 I'm closing this issue now. Please let me know if you're still having any trouble logging in.
