### ISSUE TITLE
Changes to shippable.yml not taking effect

### ISSUE THREAD

**Issue by yulianovdey** [Shippable/support#4761]
Hello!

I disabled caching in my `shippable.yml`, and added a `pre_ci_boot` section to the `build` step to use a custom image, but the build still seems to be pulling `drydock/u16nodall:v5.7.3`. I've tried `[reset cache]` and `[reset minion]` in the commit messages, and then waited until the next morning to see if the change would be picked up, but no dice. Here's a link to the last relevant build:

https://app.shippable.com/github/ExecThread/admin/runs/104/summary/console

**Comment by a-murphy** [comment]
This is usually because the `pre_ci_boot` section wasn't found when the `shippable.yml` file was parsed.  Could you double-check that there is one `build` section containing both the `ci` and `pre_ci_boot` sections indented equally and that you haven't accidentally combined tabs and spaces?

**Comment by yulianovdey** [comment]
Thanks for your reply! I verified that there is one `build` section with `ci` and `pre_ci_boot` indented equally and everything is using spaces. I also noticed that *something* is still being cached, because changes within my `build > ci` section don't take effect either. There is currently no `npm install` in the file, but that's the first step that was done during the last build:

https://app.shippable.com/github/ExecThread/admin/runs/105/1/console

**Comment by a-murphy** [comment]
The `npm install` line would have been added as a default if the `ci` section also wasn't found.  Since I can't see your original, unparsed `shippable.yml`, you can check that it is correctly formatted by comparing the sections in your `shippable.yml` to the ones documented [here](http://docs.shippable.com/ci/yml-structure/).  Or you can include your `shippable.yml` in the support issue so that we can see how it is formatted.

**Comment by yulianovdey** [comment]
Makes sense. Just to make sure, is `npm test` also added as a default? That's where the last build failed.

**Comment by yulianovdey** [comment]
@a-murphy we had the `build` section under `env` all along and I didn't notice. Sorry for the trouble.

Best,

Yulian
