### ISSUE TITLE
Purchased a single additional node but can't add it to the default node pool

### ISSUE THREAD

**Issue by ccr-billing** [Shippable/support#4769]
We were originally using the free tier and purchased an additional node. However, we cannot increase the number of nodes in the default node pool past 1 - we should be able to create a pool with 2 nodes. How can we make use of our paid node in addition to our fee node? 

In addition, when trying to create a 2nd node pool it does not show that any nodes are available.

**Comment by a-murphy** [comment]
It looks like your subscription only has one node.  More nodes can be purchased on the billing page ([directions here](http://docs.shippable.com/platform/management/subscription/billing/)) and additional nodes, if purchased, can be added to existing node pools or put in a new node pool following [these directions](http://docs.shippable.com/platform/management/subscription/node-pools/).

**Comment by ccr-billing** [comment]
Based on your pricing page, it states that the free tier includes one concurrent job (node) and "each additional concurrent job" is $25 per month. I interpret this as paying $25 per month will get me 2 concurrent jobs. Is this not the case? We purchased an additional concurrent job so I expected that we would have 2. Originally, we did but then we deleted the default node pool when we could not add an additional node now we only have access to a single node.

**Comment by a-murphy** [comment]
Upgrading the node from the free tier to the paid tier (for unlimited private project builds and access to the API) is the same price as an additional node the same size.  At this time, two large nodes with unlimited private project builds and API access is $50/month; $25/month to upgrade the first node and $25/month for the second node.

**Comment by ccr-billing** [comment]
It would be clearer if you could clarify your pricing page to make it clear that the first node purchased is an upgrade of a single node to allow access to the API and private repos and not an additional node as currently stated.

Also, how to we switch from monthly to annual billing?

**Comment by manishas** [comment]
@ccr-billing We will add clarity to the pricing page.

I will send an email to your billing contact re: annual billing after reviewing your account. Thanks!
