### ISSUE TITLE
Using secure environment variables in `build_pre_ci` step

### ISSUE THREAD

**Issue by robmoore** [Shippable/support#4770]
I'm trying to use run a tool (Snyk) that uses an environment variable for authentication. I've set the environment variable up as a secure env variable and am running the `snyk auth` command in the `build_prec_ci` section. The command fails apparently because it doesn't find the environment variable. I just wanted to confirm this value should be present at this step.

**Comment by a-murphy** [comment]
Yes, the environment variables are available in `pre_ci`.  Reading the Snyk documentation, it looks like you should either set the `SNYK_TOKEN` environment variable or run `snyk auth <snyk token>` and do not need to do both.  Could confirm that you are either using the environment variable in the `snyk auth <api token>` command or setting the `SNYK_TOKEN` environment variable?

**Comment by robmoore** [comment]
Indeed, I am not explicitly passing the value to the command but simply using the environment variable. The change is part of a PR that is failing to be built in Shippable. I'd assume that the shippable.yml from the project would be used (and hence would have the secure var) rather than master (where the PR is targeted)?

**Comment by a-murphy** [comment]
A pull request containing changes to the `shippable.yml` will run with the `shippable.yml` that would be expected after the pull request is merged.  So the `shippable.yml` of the base branch plus the changes in the pull request.

From what I read in the Snyk documentation, it sounded like you don't need the `snyk auth` command at all if you have the `SNYK_TOKEN` environment variable.  Could you try removing `snyk auth <snyk token>` command?

**Comment by robmoore** [comment]
Thanks for the tip! 

I'm running into a different problem now. I have a script that executes the snyk command (which was installed using `npm install -g snyk`) and the `snyk` command isn't found in the path. 

From the console of the build I see the following: 
```
npm install -g snyk
...
/usr/local/bin/snyk -> /usr/local/lib/node_modules/snyk/dist/cli/index.js
+ snyk@1.136.0
added 272 packages in 13.318s
```
Does that mean I should add `/usr/local/bin/snyk` to the path or is there another place where I could expect to find it?

**Comment by a-murphy** [comment]
If I'm looking at the right project, it looks like you're running `npm install -g snyk` in `pre_ci` and then trying to use `snyk` in the `ci` section.  The `pre_ci` section runs before the build container is started, to give people a chance to build an image for the build container or set up something a custom image requires, and the `ci` section runs in the build container.  Basically, you're installing `snyk` in one Docker container and trying to use it in another.  One option would be to move `npm install -g snyk` to the `ci` section if you aren't planning to use it in `pre_ci`.

**Comment by robmoore** [comment]
Thanks for the explanation. I was able to get the script to run after following your instructions.
