### ISSUE TITLE
Account blocked — Identified violating security policy

### ISSUE THREAD

**Issue by kundur** [Shippable/support#4772]
### Description of your issue:
Getting a similar issue to #4134. Not able to create an account.

Account is Bitbucket, username: kundu.r@cambridgeassessment.org.uk

**Comment by trriplejay** [comment]
I've unflagged your account, you should be able to log in now.

**Comment by kundur** [comment]
Thank you. I am able to log in now.

**Comment by lazebny** [comment]
We have a similar issue.
Account is Bitbucket, username: yevhenii.poberezhnyi@rubygarage.org
