### ISSUE TITLE
Unable to start container pulled from Docker Hub

### ISSUE THREAD

**Issue by mchuang3** [Shippable/support#4777]
### Description of your issue:
I'm trying to reduce our build/test time by pulling a pre-built Docker container from Docker Hub instead of building it each time.  If shippable builds the container (using commands in pre_ci section), everything works fine.  However, if I build this exact same container on my machine, then push to Docker Hub, and change shippable.yml to pull from Docker Hub, the build job gets stuck after "boot_container" and eventually times out after 2 hours.

I believe the Docker Hub integration is working fine, and it is able to pull the (private) container from Docker Hub.  The "boot_container" seems to work fine based on console log, but appears that it never transitions to the next step (I believe the "run" script).

Currently a build job is stuck in this state:
https://app.shippable.com/github/quattronetworks/qctl/runs/4471/1/console

Here is one that timed out:
https://app.shippable.com/github/quattronetworks/qctl/runs/4469/1/console

Thanks for any pointer to what I might be doing wrong.

-Mike

**Comment by a-murphy** [comment]
To rule out the possibility that it may be related to the version of Docker, I would suggest [updating your node pool machine image](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) to a more recent machine image.  The machine image you are currently using is the oldest machine image and has Docker 1.9 installed.  Let us know if this helps.

**Comment by mchuang3** [comment]
I updated the machine image to latest v7.1.4, and the Docker version is a much more recent 18.03.1-ce.  Unfortunately, it is still stuck in exact same place.  I noticed the machine is Ubuntu 14.04.  The custom Docker image is built on Ubuntu 18.04 VM.  Is there any compatibility issues there?  Thanks.

**Comment by trriplejay** [comment]
you could try replacing your 14.04 node pool with a 16.04 node pool, but it doesn't seem like that should matter... it seems like there has to be some fundamental difference between the image built elsewhere and the one built on shippable. What is the base OS of your custom docker image? Do you have any particular files or directories locally that would be included in the image that aren't there when it's built directly on shippable?

**Comment by mchuang3** [comment]
The base OS of the custom docker image is Ubuntu 16 (from drydock/u16).  Experimentation tells me that this is an issue w/ Docker and/or base OS version issues w/ the custom container vs. the Shippable build VM versions.  For now, I've worked around it by adding a new build job on Shippable to create the custom container (instead of building it on our newer machines).  It's working for us now.
