### ISSUE TITLE
Crashing jobs with gcloud

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4778]
### Description of your issue:
Hi,

we have been encountering job crashes lately. It is very annoing and quite dangerous. An old shippable issue #4357 is that blue/green deployments duplicate when re-run after a crash :-1: Please have a look at the crashes.

```
Successfully provisioned resource dj-staging-nginx-lb
ERROR: gcloud crashed (TokenRevokeError): invalid_request
If you would like to report this issue, please run the following command:
  gcloud feedback
To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
Failed to destroy kubeAdapter: gcloud failed and exited with error code 1
Exiting with error: true
Provision failed with error : true
```

- [Failing build](https://app.shippable.com/github/damejidlo/jobs/dj-staging-provision_sidecar/builds/5c8a49444df5210007371ad4/console)

**Comment by rune-bk** [comment]
Also getting this, which is becoming a major issue for us.

It seems to happen around 50% of the time. Rerunning the deploy jobs manually will eventually work, but may take a couple of tries. It will also often leave residual "zombie" deployments on Gcloud.

Sometimes the build even succeeds with what it's supposed to do on Gcloud, but the job fails and this error appears.
It seems to occur after a deployment has been deployed and it is either waiting for it to become stable or shortly after it has become stable during cleanup. Either way, the job is marked as failed.

After some googling, this has happened to others as well recently. I suspect google changed something which is not terribly backwards compatible. It happens sporadically when calling gcloud auth revoke. If the client does not handle this error well, it will crash. 

I think this can possibly be solved with a new machine image running gcloud v236.
I suspect this is related to this line in the gcloud release notes:

> 236.0.0 (2019-02-26)
Modified error handling for gcloud auth revoke when revoking a service account token to print a friendly error message with more detailed instructions on how to revoke the token.
Source: https://cloud.google.com/sdk/docs/release-notes

**Comment by trriplejay** [comment]
Thanks for bringing this to our attention.  We're investigating this issue, and will let you know when we have more info.

**Comment by xificurk** [comment]
Any news regarding this? It's getting pretty bad - some of the deployment jobs fail >50% times, so we've been basically deploying manually for a week or so.

**Comment by haraldnh** [comment]
Another problem with this is for provisioning jobs, where the credentials are activated and revoked for each load balancer in the IN list, running in sequence.  So it is basically impossible to have the job survive long enough to process the later inputs.  We've had to break up the structure with separate provisioning jobs for each load balancer / node port / cluster ip, just to be able to force things through with repeated manual triggering.

**Comment by xificurk** [comment]
As of today, our provision jobs started to fail every single time - [example](https://app.shippable.com/github/damejidlo/jobs/dj-staging-provision_sidecar/builds/5c94d557f125b300077ab4db/console)
@trriplejay Can you give us any update, or ETA on the fix? Is there any way we can help debug this? Or shall we rather start working on moving our pipelines to a platform that actually works?

**Comment by manishas** [comment]
I'll get an update asap on this.

**Comment by trriplejay** [comment]
We've just released a patch for this bug. Please let me know if you're still running into this issue.

**Comment by haraldnh** [comment]
Sorry, but nothing has changed:
```
Successfully provisioned resource wapi-np
ERROR: gcloud crashed (TokenRevokeError): invalid_request
If you would like to report this issue, please run the following command:
  gcloud feedback
To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
Failed to destroy kubeAdapter: gcloud failed and exited with error code 1
```

**Comment by trriplejay** [comment]
@haraldnh my apologies, the deploy service had been patched, but not provision. both services have the patch applied now.

**Comment by haraldnh** [comment]
Tested and works fine now.  Thanks. 👍

**Comment by rune-bk** [comment]
Seems to be working again. FYI to others:
Needed to manually delete some deployments on the first successful run as their state was not sent back to shippable. Cleaned up as usual on the 2nd run. 🎉

**Comment by RadekDvorak** [comment]
It seems to be fixed. Thanks
