### ISSUE TITLE
Support to download built binary in a specific location

### ISSUE THREAD

**Issue by ossdev07** [Shippable/support#4779]
Dear Team,

We have a requirement to built a binary in arm64 platform and download binary to specific location where we can download for further requirements. Unable to get any document regarding the same. Please guide me in getting above  requirement.

Thanks in advance.

**Comment by trriplejay** [comment]
It sounds like you want to take a binary that you built on a Shippable arm64 node, and upload it to a different location, is that right?

If that's the case, then how you do that would mostly depend on where you need to upload it to.  If it is a service like aws s3, we have some built in utilities that would allow you to easily upload.  If you just need it copied to a specific machine, you might want to investigate using your [subscription's ssh key](http://docs.shippable.com/ci/ssh-keys/#ssh-keys) to allow you to use something like `scp` to copy the binary.

Let me know if I can clarify anything for you.

**Comment by ossdev07** [comment]
@trriplejay 
Thanks for the reply.
Can we use ssh key to place binary in same github project which we are using to generate binary?
Could you please guide me on the same.
Thanks in advance.

**Comment by trriplejay** [comment]
Yes, that can be done. There are a few steps you'll have to take to accomplish that:
- since your projects are public, we don't automatically create a deploy key.  I would recommend just taking the public ssh key on your subscription settings page, and adding that to your project as a deploy key.  Make sure to grant it `push` access.
- after your artifact is built, you can do a standard `git add`, `git commit`, `git push`.  **note:** make sure to add a `[skip ci]` to your commit message so that your job doesn't infinitely trigger from its own commit. for example:

```
git commit -m 'adding binary for $BUILD_NUMBER [skip ci]'
git push origin master
```

**Comment by ossdev07** [comment]
@trriplejay 
I have added below commands
1) git add .
2) git commit -m 'adding binary for $BUILD_NUMBER [skip ci]'
3) ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub; git push origin master'

Error after push command:
Identity added: /tmp/ssh/00_sub (/tmp/ssh/00_sub)
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/ossdev07/flow.git/'

Please guide me on this issue.
Thanks in advance.

**Comment by trriplejay** [comment]
ah, i think there is one more thing to change.  Since the project is public, we clone via https, but when pushing with a key, the url needs to be in the ssh format. so you can add an extra line like this:

```
git remote add ssh-origin git@github.com:ossdev07/flow.git
git push ssh-origin master
```

give that a try and let me know how it goes.

**Comment by ossdev07** [comment]
@trriplejay 
Thanks for the help. Added ssh-key in git ssh-keys settings and it has successfully committed.

**Comment by trriplejay** [comment]
glad that's working! let us know if you have any additional questions.
