### ISSUE TITLE
Registration via github account selects arbitrary email address (not primary)

### ISSUE THREAD

**Issue by rowanthorpe** [Shippable/support#478]
Since registering for shippable using my github account, one of the three email addresses I have registered at github was apparently arbitrarily selected for the mailing list updates from shippable. The one that was selected is not my primary one at github, and is one i *never* use for receiving such emails, but it seems there is nowhere I can specify or update this from within shippable (and it obviously doesn't necessarily default to my primary github email). The emails I've received look entirely non-spam/legitimate (DKIM-signed), and there is an "update email preferences" link in the email but it points to a slightly odd address starting with http://shippable.hs-sites.com/... - and for that reason I am hesitant to visit that link, yet there is no eqivalent link from within the shippable.com web-interface...

**Comment by manishas** [comment]
Closing this issue since it is from before the V2 upgrade. We have revamped our email handling in V2.
