### ISSUE TITLE
Tooltips are not going away

### ISSUE THREAD

**Issue by Mendalorien** [Shippable/support#4783]
### Tooltips are not going away:

When I click on a job in the SPOG, and then navigate back, the tooltips are still there from the previous time.  After you do this a bunch of time you end up with a lot of tooltips on the screen.  The only way to get rid of them is to do a refresh of the webpage.

![Screen Shot 2019-03-19 at 12 34 13 PM](https://user-images.githubusercontent.com/7612850/54628349-59b7e900-4a43-11e9-9841-cc89711fa68f.png)

**Comment by a-murphy** [comment]
Thank you for reporting this.  We haven't seen this before.  Would you mind telling us which browser this is?

**Comment by Mendalorien** [comment]
This is Firefox, on a Mac.

**Comment by Bekt** [comment]
This happens in MacOS Chrome as well.

**Comment by manishas** [comment]
This has been addressed a few days ago, so closing.
