### ISSUE TITLE
I can't log in my bitbucket account

### ISSUE THREAD

**Issue by yandroskaos** [Shippable/support#4790]
Description of your issue:
I can't log in to shippable. I am getting error:
An error occured, please choose an action.
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.
My bitbucket login: dev@zapiens.org

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by yandroskaos** [comment]
No apologies, great support (and great software) :) it's working. Thanks!
