### ISSUE TITLE
Builds timing out

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#4791]
Builds for our project https://app.shippable.com/projects/55801052edd7f2c0521a75d8 have started failing since 2:00 PM IST today. The last build before that started at 12:00 PM IST and succeeded.

The builds have simply become too slow, eventually failing to download Maven dependencies for the projects.

**Comment by trriplejay** [comment]
we're investigating this issue.

**Comment by manish-in-java** [comment]
Re-ran the failed builds just now (9:00 AM IST, 3:30 AM UTC) and they succeeded just fine. Would like to understand the root cause for the failed builds.

**Comment by manish-in-java** [comment]
@trriplejay, any update?

**Comment by trriplejay** [comment]
Hi @manish-in-java.  During our latest deployment (late Thursday night PDT, 3/28) we scaled up a few resources that we suspected were causing the bottleneck behind these stuck builds. This seems to have alleviated the conditions that were causing the builds to get stuck. Please let us know if you're still experiencing this problem.
