### ISSUE TITLE
Shippable future after JFrog acquisition

### ISSUE THREAD

**Issue by danielrs** [Shippable/support#4793]
@avinci 
@trriplejay 
@abhijitkini 
@manishas 

My team is currently considering using Shippable for our CI/CD solution. But we were wondering about the future of Shippable as a product after being acquired by JFrog. Looking at the issues and media in general, it seems that development and support has slowed down, and that worries me.

What can we expect as the users of Shippable?

**Comment by manishas** [comment]
@danielrs Thanks for your interest in Shippable!

We are fully committed to the product and supporting our customers,  and this has not changed before or after the acquisition. We are also working on a longer term roadmap and how the products will work better together and provide a superior end-to-end experience for customers. 

Short answer? Don't worry :) Feel free to reach out directly at manisha@shippable.com or manishas@jfrog.com... happy to chat and answer any questions.

**Comment by manishas** [comment]
Closing.
