### ISSUE TITLE
Custom slack notification

### ISSUE THREAD

**Issue by vitaliy-mityevskyy** [Shippable/support#4794]
Hi, guys.
Slack notification works perfect, but I would be glad to have opportunity to send my own custom messages, not just auto generated by shippable. For example name of image what was build, or url to deployed application, etc.
Maybe there is such function, but I didn't find nothing about it

**Comment by trriplejay** [comment]
Hi @vitaliy-mityevskyy 

We actually do have a way to do this. Our `shipctl` utility that is available at build runtime has a `notify` function that can be used for exactly this purpose.  http://docs.shippable.com/platform/tutorial/workflow/using-shipctl/#notify

By default it will send the standard shippable payload, but it allows you to customize the various attributes of that payload, including the message, the recipient (channel or user), the icon, and even the color of the highlight bar (shippable does green for pass, red for failed).

If you want more advanced configuration, you can also create your own payload from scratch. For example if you just want the most basic, single-line message you can do something like this:
```yml
- echo "{\"text\":\"Hello world!\"}" > /tmp/payload.json
- shipctl notify mySlackResource --payload=/tmp/payload.json
```
This would send the message in "text" to the pre-configured channel.  The payload has to be in a format that will be accepted by the slack api.

To use this, you'll need a notification resource with an attached slack integration as an IN step to your job.  That is the resource that is referenced in the notify command: http://docs.shippable.com/platform/workflow/resource/notification/

let me know if you have any questions!

**Comment by vitaliy-mityevskyy** [comment]
Thanx John! Just what I need
