### ISSUE TITLE
Mutli-stage pipelines 

### ISSUE THREAD

**Issue by Boolos** [Shippable/support#4795]
### Description:
I have a build pipeline that looks like:
`manifest --> deploy_to_test --> deploy_to_stage --> deploy_to_prod`
This looks to be in accordance with the docs: http://docs.shippable.com/deploy/multi-stage-deployments/

However, the job is failing, but it successfully upgraded the kube Deployment.  It looks like the deploy is making 1 manifest as "scalable" and 1 manifest as "deployable".  Then it completes the blue/green successfully, but I'm guessing its trying to scale the deleted "blue" deployment.  If you run the job again, it succeeds, but leaves an extra kube Deployment orphaned. 

This problem appears to have only started recently.  Can you please provide some assistance?  This is a fairly high severity problem for us.

#### Link to the build failure
https://app.shippable.com/github/supplypike/jobs/core-ui_stage_core_deploy/builds/5ca4e7efb8751000064f90d6/console

**Comment by trriplejay** [comment]
we're investigating this.

**Comment by trriplejay** [comment]
@Boolos could you try performing a "reset" on the stage_core_deploy job? in the SPOG, you can right click and select the "reset" button.  It seems like this series of jobs has had some change in configuration recently and we're thinking that there may just be some stale settings leftover from the older deployments. Performing a reset should ensure that it starts with a clean slate.  Once you perform the reset, you can try letting it auto-trigger from the input job to ensure it works.

**Comment by Boolos** [comment]
I tried this early, and the job succeeds, but leaves an orphaned kube Deployment.  I just tried to "reset" again, and it looks like the same behavior.  I'm rerunning the pipeline from the manifest job to see if it gets back into the stale state.  Should I reset a different job other than the stage deploy?

**Comment by Boolos** [comment]
Update: I ran the pipeline from the manifest job and the stage deploy failed: https://app.shippable.com/github/supplypike/jobs/core-ui_stage_core_deploy/builds/5ca516c8d964990007a2fe1e/console

**Comment by trriplejay** [comment]
ok. actually the initial reset is expected to leave an orphan, since it is disregarding previous actions taken.  Ideally it would've been a one-time orphan to fix the state issue, but it's very odd that your manifest would end up in both the scalable and deployable sections... we're continuing to investigate.

**Comment by Boolos** [comment]
yeah that makes sense.  i'll keep testing a bit and see if i can provide any more info.  if this helps, the original config had the manifest as an input to the stage deploy (to be able to control the deployment name as specified in [this issue](https://github.com/Shippable/support/issues/4345)).  But we removed the manifest as it seemed to start causing problems within the the last week or two.  please let me know if you discover anything, and thanks!

**Comment by Boolos** [comment]
worse case scenario, i suppose we could do a hard delete, but i wouldn't want the deployments to get deleted when we delete the corresponding config, as we have production resources managed by Shippable.

**Comment by Boolos** [comment]
Yes it looks as if any time I run the stage deploy directly, I can get things to behave as expected consistently.  But once I trigger the stage deploy via a preceding job, the stage deploy gets back into the state where it detects 1 scalable and 1 deployable manifest.  And this results in a failed deploy

**Comment by trriplejay** [comment]
we'll be releasing a patch shortly that should fix this logic. I'll let you know once it's rolled out.

**Comment by Boolos** [comment]
awesome, thanks so much!!

**Comment by trriplejay** [comment]
ok, patch is rolled out to the deploy service now. the next time your job triggers it should behave as expected.  Please let me know if you're seeing any other issues.

**Comment by Boolos** [comment]
Everything appears to be working correctly.  Thanks again!
