### ISSUE TITLE
Failed to send mail no recipients defined

### ISSUE THREAD

**Issue by vidavidorra** [Shippable/support#4796]
### Description of your issue:
I'm using `--last_committer` and `--last_author` as the recipients and am getting an error. It should work like that based on the documentation [here](http://docs.shippable.com/ci/email-notifications/).

```
  Sending Email
Failed to send mail for objectId:5ca090ede32d580007c36fb2 with error Error: No recipients defined
```

- Link to the build failure
https://app.shippable.com/github/vidavidorra/homebrew-yard/runs/4/1/console
- Link to shippable configuration file
https://github.com/vidavidorra/homebrew-yard/blob/master/shippable.yml#L26-L27

- ~~Scripts called from the yml (optional)~~

**Comment by a-murphy** [comment]
The YML parser is interpreting your `recipients` as one recipient.  Could you try this format?
```YML
      recipients:
        - --last_committer
        - --last_author
```

**Comment by vidavidorra** [comment]
That does work, thanks!
Probably not a bad idea to update the documentation to specify this ;)

**Comment by sshen81** [comment]
👍 Ran into the same issue - please update documentation http://blog.shippable.com/notifying-ci-failure/success-status-on-email-slack
