### ISSUE TITLE
Tag docker image as Github release

### ISSUE THREAD

**Issue by Asgoret** [Shippable/support#4807]
Hi to everyone! Can somebody route me to part of documentation where described how tag builded docker as GitHub Release or how get this value from dockerfile?

**Comment by rageshkrishna** [comment]
If you are using CI
---

Turn on builds for GitHub releases
http://docs.shippable.com/platform/management/project/settings/#webhook-config

Use the `IS_RELEASE` and `GIT_TAG_NAME` environment variables
http://docs.shippable.com/ci/env-vars/#standard-variables

If you are using assembly lines
---

Configure your gitRepo resource to allow releases by setting the `buildOnRelease` tag
http://docs.shippable.com/platform/workflow/resource/gitrepo/#latest-syntax-shippable-v611-and-above

Then use the environment variables `<NAME>_RELEASE_NAME` and `<NAME>_IS_RELEASE` 
http://docs.shippable.com/platform/workflow/resource/gitrepo/#default-environment-variables

**Comment by Asgoret** [comment]
@rageshkrishna Thanks! And i don't know where send this:
![image](https://user-images.githubusercontent.com/30697011/56280655-4f0c7480-6113-11e9-8680-70532bdcd493.png)
