### ISSUE TITLE
Can't login with Bitbucket account

### ISSUE THREAD

**Issue by giam-forte** [Shippable/support#4810]
I can't log in to shippable. I am getting error:
An error occurred, please choose an action.
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

My bitbucket login: concisoti@fortenetwork.com.br

**Comment by rageshkrishna** [comment]
Your account is unblocked now. Please try logging in once again.

**Comment by giam-forte** [comment]
Now works!!
Your support was very fast and efficient

Thank you!!
