### ISSUE TITLE
Account blocked — Identified violating security policy

### ISSUE THREAD

**Issue by theparadigmcity** [Shippable/support#4822]
Hi,

I just wanted to log in with a Github account that has only permissions for the repositories I want to use with Shippable, and it threw the error shown on the title. Is it allowed to use a Github account for this purpose? If that so, could you please unblock this account on Shippable?

Thanks in advance!

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by theparadigmcity** [comment]
Thank you!
