### ISSUE TITLE
Not recognized files by docker volume mounted

### ISSUE THREAD

**Issue by junaruga** [Shippable/support#4824]
### Description of your issue:

A file volume mounted in the docker container by `docker run -v "$(pwd):."` is not recognized for only Shippable CI.

I prepared the reproducer script here.
https://github.com/junaruga/report-docker-empty-volume

Below command works on
* Travis CI (Docker version 18.06.0-ce, Ubuntu, x86_64)
* My local (Docker version 17.06.0-ce, Mac, x86_64)
.

```
$ git clone https://github.com/junaruga/report-docker-empty-volume.git
$ cd report-docker-empty-volume
```

```
$ docker run --rm -t -w /build -v "$(pwd):/build" ubuntu ls -l bar.txt
-rw-rw-r-- 1 2000 2000 12 May  4 21:30 bar.txt
$ docker run --rm -t -w /build -v "$(pwd):/build" ubuntu cat bar.txt
...
Hello, bar!
```

But does not work on
* Shippable CI
  * Docker version 17.06.0-ce, Ubuntu, x86_64
  * Docker version 17.09.1-ce, Ubuntu, aarch64

```
$ docker run --rm -t -w /build -v "$(pwd):/build" ubuntu ls -l bar.txt
ls: cannot access 'bar.txt': No such file or directory
```

### docker --version, docker info

I would show you the result of `docker --version` and `docker info` between Shippable x86_64 case, Travis CI x86_64 case, and my local as a comparison.

#### Shippable CI - x86_64

```
+ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

```
+ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 28
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1028-gcp
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.298GiB
Name: node-40044e72
ID: QBNA:U2SW:G6NJ:YVBY:QQKD:P4D4:QD6P:OK3X:APFF:OMIV:GITW:3DTL
Docker Root Dir: /data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

#### Travis CI - x86_64

```
+ docker --version
Docker version 18.06.0-ce, build 0ffa825
```

```
+ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.15.0-1028-gcp
Operating System: Ubuntu 16.04.6 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.298GiB
Name: travis-job-63b987d7-32b9-40d5-8d23-b95dc8971941
ID: WP5N:5JG2:SAP4:DFPV:7X24:XUGL:N7AX:EPJX:WOAL:GD2N:FG7K:GXY2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://mirror.gcr.io/
Live Restore Enabled: false
```

#### My local - x86_64

```
$ docker --version
Docker version 17.06.0-ce, build 02c1d87
```

```
$ docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 4
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 34
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.74-boot2docker
Operating System: Boot2Docker 17.06.0-ce (TCL 7.2); HEAD : 0672754 - Thu Jun 29 00:06:31 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955GiB
Name: default
ID: PKCA:4QWM:4AGW:SQXI:LK73:H7T2:VFKD:RZXS:LBYB:JUJO:GW3E:LRSB
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 27
 System Time: 2019-05-04T22:09:32.376341984Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Link to the build failure
  https://app.shippable.com/github/junaruga/report-docker-empty-volume/runs/18/summary/console
- Scripts called from the yml (optional)
  https://github.com/junaruga/report-docker-empty-volume/blob/master/shippable.yml

**Comment by a-murphy** [comment]
For the job running in `default_node_pool`, the volume mount created is for a directory that isn't on the host, so that's why it's empty.  The docker containers started in node pools that aren't shared run alongside the build container on the host, with volume mounts from the host to the container.  In order to share files between the build container and the new container, they need to be in a directory that is also mounted to the build container.  Volume mounts can be added in the `pre_ci_boot` `options` as described [here](http://docs.shippable.com/ci/custom-docker-image/#pulling-a-public-image).  In your case, adding `"-v $SHIPPABLE_BUILD_DIR:$SHIPPABLE_BUILD_DIR"` to `options` will likely work.

The shared node pool would not have the missing volume mount.  However it appears as though your first `docker run` finds the files and the later ones fail because of the `--rm` in your `docker run`.  As [documented by Docker](https://docs.docker.com/engine/reference/run/#clean-up---rm), the `--rm` removes unnamed volumes.  So, if you want to use `--rm` and not remove the files, you should [create the volume](https://docs.docker.com/engine/reference/commandline/volume_create/) first.

**Comment by junaruga** [comment]
@a-murphy thank you for the detailed answer, I try your suggested way.
I am fine to close this ticket for now.

**Comment by junaruga** [comment]
> For the job running in default_node_pool, the volume mount created is for a directory that isn't on the host, so that's why it's empty. The docker containers started in node pools that aren't shared run alongside the build container on the host, with volume mounts from the host to the container.

One question, why does this situation happens?
It's because of DinD (Docker-in-Docker)?
I mean `default_node_pool` is running on the container.
And my container is running in the container, right?
