### ISSUE TITLE
Can't enable email notifications for runSh step of the workflow

### ISSUE THREAD

**Issue by immerrr** [Shippable/support#4826]
Here's the latest build with a pretty minimalistic shippable.yml file where I tried to get it to work to no avail: https://app.shippable.com/github/localistico/jobs/shippable-playground_master_rSync/builds/5cd2bd73bbceea00079a93b0/console

I tried:
- using `NOTIFY: email`
- adding a `resources: { name: "email-resource", type: "notification", integration: "email" }` and using `NOTIFY: email-resource`, didn't work because it could not find `integration: email` under the account
- copying the notification configuration section to NOTIFY, so that it looks like
```
       - NOTIFY:
           - integrationName: email
             type: email
```

The [documentation](http://docs.shippable.com/platform/tutorial/workflow/using-runSh/) has an example for slack, which uses a resource and I cannot create a notification resource for emails, so I'm stuck.

**Comment by a-murphy** [comment]
You should be able to add a [notification resource](http://docs.shippable.com/platform/workflow/resource/notification/) with `method: email` in the `versionTemplate`, and no integration, to the `resources` section of your YML.  The notification resource is then used with `NOTIFY` in the `on_start`, `on_success`, `on_failure`, or `on_cancel` sections of the [runSh](http://docs.shippable.com/platform/workflow/job/runsh/) job.

**Comment by immerrr** [comment]
Thank you, I have successfully enabled email notifications. Alas, it doesn't support some of the niceties of CI notifications (showing failing snippet), but at least now I get a GMail notification if something happens during the deployment step.
