### ISSUE TITLE
Amazon Corretto JDK in default java image

### ISSUE THREAD

**Issue by bradskuse** [Shippable/support#4831]
Hi, we are looking to migrate to Amazon Corretto 8 (https://aws.amazon.com/corretto/)

The latest build images come with various Oracle / OpenJDK versions installed.  Could Corretto 8 be added in the default image and allowed to be set via shippable.yml with - jdk: corretto8

If this is not possible, how could this be achieved in a viable way?

Thank you,
Brad

**Comment by bradskuse** [comment]
Any comment to above question?

**Comment by andye2004** [comment]
@ambarish2012, @manishas Guys can get we get this looked at and some kind of feedback supplied?

Given the recent announcements regarding long term support etc of Java8 and others it's looking like corretto may become the only viable JDK8 implementation out there.
