### ISSUE TITLE
account has been blocked as it was identified to be violating our security policy

### ISSUE THREAD

**Issue by edvinsv** [Shippable/support#4834]
### Description of your issue:
Hi,
I am having the error: 
"An error occured, please choose an action.
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

I am trying to login using Bitbucket user:  edvins_vezis

**Comment by AlexeyMorozov-dx** [comment]
Hi,I just signed in with my github account and tried to register with shippable, but my account was instantly blocked.
Can you unblock my account?

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your accounts so you should be able to sign in.
