### ISSUE TITLE
Python version is different than documented

### ISSUE THREAD

**Issue by robmoore** [Shippable/support#4836]
I've specified python 3.7.2 in my yml file and am using machine image 7.2.4 but when I run `python --version` I'm seeing 3.5.2.

According to the [docs](http://docs.shippable.com/platform/runtime/machine-image/language-versions/#python) I should have 3.7.2 available, no?

**Comment by robmoore** [comment]
I'm running on dynamic nodes with Ubuntu 16.04.

**Comment by a-murphy** [comment]
Could you include either a link to an example of this in one of your projects or the ID from the bottom of the page?  The 7.2.4 Python images should have Python version 3.7.2, but commands in the `pre_ci` section run before the build container has started.   And if the `language` in your YML is not `python`, any Python language settings would be ignored.

**Comment by robmoore** [comment]
Thanks, @a-murphy. I'm experiencing the case of seeing 3.5.2 when running within the `pre_c` section. In the `ci` section I do indeed have 3.7.2 available to me.
