### ISSUE TITLE
Accounts mistakenly blocked in violation of security policy

### ISSUE THREAD

**Issue by tsutaj** [Shippable/support#4838]
I tried to log in to Shippable service for the first time, but I could not complete logging in and I can only see the following message.

Message: "An error occured, please choose an action. Your account has been blocked as it was identified to be violating our security policy. Please contact support if you feel this is a mistake. "

Could the following account please be whitelisted:
tsutajiro+hupc2019day2 [atmark] gmail.com

Thank you.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by tsutaj** [comment]
I can log in successfully. Thank you!
