### ISSUE TITLE
Request for static IP for our node pool

### ISSUE THREAD

**Issue by robmoore** [Shippable/support#4839]
I requested a static IP for our node pull on Thursday, May 16th, and haven't heard anything back. The docs specify requests are to be done via email but I wanted to confirm but I thought I might need to open a ticket here instead.

**Comment by trriplejay** [comment]
@robmoore sorry for the delay. I've updated your subscription to allow your node pools to utilize the static IP setting. You should now be able to turn this on from the "edit node pool" page. Let me know if you have any other questions .

**Comment by robmoore** [comment]
@trriplejay Thanks!
