### ISSUE TITLE
unable to run "sudo apt-get install -u lib32stdc++6 lib32z1"

### ISSUE THREAD

**Issue by menny** [Shippable/support#484]
One of my builds is failing because my minion fails to install _lib32stdc++6 lib32z1_
These two libraries are essentials for my Android environment.

```
sudo apt-get install -u lib32stdc++6 lib32z1
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
node-node-uuid node-lru-cache node-which node-tar node-semver
node-block-stream libv8-3.7.12.22 node-request node-mkdirp node-fstream
node-nopt node-minimatch node-inherits node-abbrev libev4 libv8-dev
node-rimraf libc-ares2 libev-dev libc-ares-dev node-graceful-fs node-ini
Use apt-get autoremove to remove them.
The following extra packages will be installed:
lib32gcc1 libc6-i386
The following NEW packages will be installed:
lib32gcc1 lib32stdc++6 lib32z1 libc6-i386
0 upgraded, 4 newly installed, 0 to remove and 112 not upgraded.
Need to get 3,992 kB/4,430 kB of archives.
After this operation, 11.2 MB of additional disk space will be used.
Err http://archive.ubuntu.com/ubuntu/ precise-updates/main libc6-i386 amd64 2.15-0ubuntu10.5
404 Not Found [IP: 91.189.92.201 80]
Err http://archive.ubuntu.com/ubuntu/ precise-security/main libc6-i386 amd64 2.15-0ubuntu10.5
404 Not Found [IP: 91.189.92.201 80]
Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/e/eglibc/libc6-i386_2.15-0ubuntu10.5_amd64.deb 404 Not Found [IP: 91.189.92.201 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by tango4567** [comment]
@rageshkrishna Still having the same issue 
`sudo apt-get update
[sudo] password for sowt: 
Ign:1 https://storage.googleapis.com/download.dartlang.org/linux/debian stable InRelease
Hit:2 https://storage.googleapis.com/download.dartlang.org/linux/debian stable Release
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease 
Hit:5 http://dl.google.com/linux/chrome/deb stable Release 
Hit:6 http://packages.microsoft.com/repos/vscode stable InRelease 
Hit:7 http://linux.teamviewer.com/deb stable InRelease 
Ign:8 http://in.archive.ubuntu.com/ubuntu zesty InRelease 
Hit:10 http://linux.teamviewer.com/deb preview InRelease 
Ign:11 http://security.ubuntu.com/ubuntu zesty-security InRelease 
Ign:12 http://in.archive.ubuntu.com/ubuntu zesty-updates InRelease 
Err:13 http://security.ubuntu.com/ubuntu zesty-security Release 
404 Not Found [IP: 91.189.88.149 80]
Ign:14 http://in.archive.ubuntu.com/ubuntu zesty-backports InRelease 
Err:15 http://in.archive.ubuntu.com/ubuntu zesty Release
404 Not Found [IP: 91.189.88.149 80]
Err:16 http://in.archive.ubuntu.com/ubuntu zesty-updates Release
404 Not Found [IP: 91.189.88.149 80]
Err:17 http://in.archive.ubuntu.com/ubuntu zesty-backports Release
404 Not Found [IP: 91.189.88.149 80]
Reading package lists... Done
E: The repository 'http://security.ubuntu.com/ubuntu zesty-security Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://in.archive.ubuntu.com/ubuntu zesty Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://in.archive.ubuntu.com/ubuntu zesty-updates Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://in.archive.ubuntu.com/ubuntu zesty-backports Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by jacobrohit** [comment]
root@kali:~# sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lib32z1
E: Unable to locate package lib32ncurses5
E: Unable to locate package lib32bz2-1.0
E: Couldn't find any package by glob 'lib32bz2-1.0'
E: Couldn't find any package by regex 'lib32bz2-1.0'
E: Unable to locate package lib32stdc++6
E: Couldn't find any package by regex 'lib32stdc++6'
root@kali:~#

**Comment by jacobrohit** [comment]
root@kali:~# sudo apt-get install lib32z1 lib32ncurses5 lib32bz2-1.0 lib32stdc++6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package lib32z1
E: Unable to locate package lib32ncurses5
E: Unable to locate package lib32bz2-1.0
E: Couldn't find any package by glob 'lib32bz2-1.0'
E: Couldn't find any package by regex 'lib32bz2-1.0'
E: Unable to locate package lib32stdc++6
E: Couldn't find any package by regex 'lib32stdc++6'
