### ISSUE TITLE
Account blocked — Identified violating security policy

### ISSUE THREAD

**Issue by gerywahyu** [Shippable/support#4841]
### Description of your issue:
Getting similar issue to #4812 

Thanks!

**Comment by Bharath92** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by soft4good** [comment]
@Bharath92 Im getting the same issue while trying to login with my bitbucket account, what should I do? thanks!

**Comment by a-murphy** [comment]
@soft4good I've unblocked your account, so you should be able to log in now.
