### ISSUE TITLE
Project no longer found when using API Token to trigger build

### ISSUE THREAD

**Issue by adinuca** [Shippable/support#4843]
### Description of your issue:
Our build pipeline is set so that when a build passes it triggers another deployment build. The first build uses an API Token to trigger the deployment build. Builds starting failing yesterday with the following errors: 
```
{"logType":"verbose","methodName":"/projects/:projectId/newBuild|POST|callerId:57ff8affbe4b4c1000663dfa|validateProjects|_computeShim","id":4004,"message":"No projects found for projectId(s): 5804f143e8fe021000f9aed1"}
Failed to trigger deploy.
```
This worked fine until yesterday. If the API Token used to trigger the second build is changed with a new one, the build is successful. 

We would like to better understand the problem and if it is required to change API Tokens for all projects and also how we could prevent this in the future.

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/github/NRGI/shiny-apps-deploy/runs/648/1/console
https://app.shippable.com/github/derilinx/ckan-docker-public/runs/200/1/console

- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
It looks like last time the account to which the token belongs was synchronized permissions could not be determined and so the account lost access to the project.  This most often occurs when an account is rate limited by the SCM provider.  Your token should be working again now.  If this does occur again, logging in as that account and clicking the "synchronize" button on the account profile page should resynchronize the account and restore permissions, provided that any rate limits have not continued to be exceeded.

**Comment by adinuca** [comment]
Thank you. I can confirm the issue is fixed now.
