### ISSUE TITLE
CI (runCI) jobs no longer being run by Shippable

### ISSUE THREAD

**Issue by julio-lopez** [Shippable/support#4844]
### Description of your issue:

CI (runCI) jobs no longer being run by Shippable in our project's GitHub repo.

Github reports the following status for the Shippable integration:

"Shippable Expected — Waiting for status to be reported"

The jobs status page shows 0 queued jobs, minion nodes seem to be healthy

**Comment by julio-lopez** [comment]
Seems to be working now. Not sure what changed.

**Comment by trriplejay** [comment]
Hi @julio-lopez,

GitHub experienced a webhook outage earlier today. I believe this is the reason why your jobs were delayed: https://www.githubstatus.com/

**Comment by julio-lopez** [comment]
@trriplejay Thanks for the reply. That is a likely explanation.

I would have expected that it would have shown up in the shippable status page ( https://shippable.statuspage.io, http://status.shippable.com), but it showed that the integration with Github was operational.
