### ISSUE TITLE
please contact support if you feel this is a mistake

### ISSUE THREAD

**Issue by bheaps99** [Shippable/support#4845]
## I get the following error message
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

I am trying to log in with benedict@***.com bitbucket account

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
