### ISSUE TITLE
GitHub notifications being down

### ISSUE THREAD

**Issue by Mendalorien** [Shippable/support#4846]
When GitHub notifications are down, which seems to happen relatively frequently these days.  Our CI/CD pipeline in Shippable becomes unusable, even if we run the jobs manually.

Our naive assumption was that, even if the build aren't being triggered automatically because notifications are down, if we run the jobs manually in the UI then it will still pull the most recent versions of the code in Git, build it, and deploy it.  However, this is not what happens.  In many cases, especially the ```Sync Jobs```, they never do a Git Pull to get the most recent version of the code when we run them manually.  It seems like they only get the most recent version in Git if a Notification is sent.

A simple fix would be to enable the naive assumption that when a job is run manually it will actually get the most recent version of the code in Git.

**Comment by trriplejay** [comment]
You are correct that sync jobs, as well as any `gitRepo` resources, will only update from an incoming webhook. I'll mark this as a feature request to allow the latest to be forced instead of relying fully on incoming hooks.
