### ISSUE TITLE
javascript coverage ui needs love

### ISSUE THREAD

**Issue by jayzeng** [Shippable/support#485]
We have an angular project deployed and set up test coverage, while it works, but UI definitely needs a lot love. Let me give you an example:

From https://www.shippable.com/projects/53f65bd7ada2292503ca524b/builds/189:
```javascript
 scripts B 0.00% | S 74.29%
 app.js B 0.00% | S 59.09%
(anonymous_1) ()V	61 hits
(anonymous_2) ()V	0 hits
(anonymous_3) ()V	0 hits
(anonymous_4) ()V	0 hits
(anonymous_5) ()V	61 hits
(anonymous_6) ()V	61 hits
(anonymous_7) ()V	0 hits
```

It apparently uses reflection to generate the method stubs, but I have no clue what they refer to so the whole thing is virtually useless.

**Comment by manishas** [comment]
We haven't heard this request again, so I'm closing it out for now. We'll revisit this if we hear this feedback again.
