### ISSUE TITLE
increase duration above 120 mins

### ISSUE THREAD

**Issue by emaxerrno** [Shippable/support#4851]
We bootstrap clang (takes ~2 hours) then build our code (takes 1.5 hrs). 

How to get around the limitation of 2 hours max build time. We need about 4. Or rather, I'm OK having the limit per step which seems more sensible.

**Comment by emaxerrno** [comment]
Ping. 

So this was changed internally to 300 for the organization but not for the actual repo (named `v` in case admins can change this asap)

When i tried to increase above 120 mins I think there is a data validation on the UI (javascript end) that doesn't allow me to increase it above 120. 

Can the admins help please. 

Thank you.

**Comment by trriplejay** [comment]
sorry about that, there are a few different spots where this value can be set, it has now been updated directly on the project so you should be all set now. let me know how it goes!

**Comment by emaxerrno** [comment]
@trriplejay  - i see it set now. thanks!

**Comment by emaxerrno** [comment]
@trriplejay  - so i see all the timeouts set, but the build times out at ~ 2 hrs.

**Comment by trriplejay** [comment]
third time's a charm... Your project settings will show 120 in the UI, however the value in your node pool settings will be the one that is used.  Please let me know if you still have trouble with this.

**Comment by emaxerrno** [comment]
@trriplejay still not fixed. A timeout was triggered today after 2hrs 5 mins. 
(Sha : f5ec8edb42)

**Comment by emaxerrno** [comment]
Also, I can't seem to be able to re-open the issue, let me know if you want me to create a new one.

**Comment by trriplejay** [comment]
i'm not seeing the timed out job. i see a 1 hour 51 minute job with that sha that you reference, and it was successful.  Can you provide a link to the timeout?

**Comment by emaxerrno** [comment]
Yes sir. one sec.

**Comment by emaxerrno** [comment]
```
v
--
Branch : feature/packaging-tests-v4             Sha : f5ec8edb42
Builder : mmaslankaprv                          Triggered By :                mmaslankaprv
```

**Comment by emaxerrno** [comment]
https://app.shippable.com/github/mmaslankaprv/v/runs/2/1/console

**Comment by emaxerrno** [comment]
![github_issue](https://user-images.githubusercontent.com/175206/60216491-08c44780-981f-11e9-9f86-8916f6713281.png)

**Comment by trriplejay** [comment]
ah, i see. this build ran in a different subscription from the one whose timeout we increased. The timeout is set at the node pool level, which belongs to a particular subscription.  Unfortunately this subscription that you've linked appears to be on the free plan, which we do not allow customizable timeouts for.

**Comment by emaxerrno** [comment]
oh i see. I thought all the developers would automatically get the timeouts. 

question: how does a developer know if their build is working if it timesout for them?

**Comment by emaxerrno** [comment]
Note the pullrequest is from their branch, to our main repo branch. simple git workflow.

**Comment by trriplejay** [comment]
a PR against the main repo would trigger the build for that main subscription, so that should work if you're able to do that.

When they push a commit to their fork, since they've enabled the project in their personal subscription, a build will run for the commit.  This will time out, since their personal sub does not have the ability to customize timeouts.  When they open a PR against the main repo, that will trigger a PR build in the main subscription, which will have the increased timeout.

If you look at your main subscription, you will see that same sha was actually used in a pullrequest build that was successful after 1 hour 51 minutes.

**Comment by emaxerrno** [comment]
Got it. So there are 2 builds effectively. 

1. Is from their subscription
2. Is against our main/paid subscription. 

Results

1. fails
2. succeeded. 

Got it. 

Is there a link/docs on how to then unlink their personal one.

**Comment by trriplejay** [comment]
He can click "delete project" at the bottom of the project settings page in his personal subscription:

http://docs.shippable.com/platform/management/project/settings/#delete-project

**Comment by emaxerrno** [comment]
Thanks @trriplejay  - feel free to close then. I'll send link to team.
