### ISSUE TITLE
Account incorrectly blocked for violating security policy

### ISSUE THREAD

**Issue by davidjpfeiffer** [Shippable/support#4856]
My company has created a Shippable account for me, but when I try to login to app.shippable.com I get the following error:

<img width="1680" alt="Screen Shot 2019-06-03 at 10 57 35 AM" src="https://user-images.githubusercontent.com/8846738/58823508-b82a4780-85ee-11e9-9d51-1d38a5ce0f81.png">

My email is david@thetalake.com. Please let me know if you need any more information from me to fix this error.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by davidjpfeiffer** [comment]
I appreciate your prompt response! I am now able to login. Thank you!
