### ISSUE TITLE
Error Logging in To Shippable

### ISSUE THREAD

**Issue by slevertbiot** [Shippable/support#4857]
Hello,

I'm getting the following error when I'm attempting to login to shippable.

email: stephane.levert@buildingsiot.com

Error
An error occured, please choose an action.
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by rageshkrishna** [comment]
I'm closing this as it appears to be resolved. Please let me know if this is still an issue.
