### ISSUE TITLE
Lost all permissions to my projects in Shippable

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#4859]
Hi,

I was working in shippable and got a bunch of errors with projects not accessible anymore and I cannot see any of my projects anymore. I checked bitbucket and I am still admin on them everywhere. I tried login in and out of both shippable and bitbucket and even use incognito mode to no avail.

Please help. I need access back ASAP.

**Comment by a-murphy** [comment]
Could you try clicking the "sync" button on your account profile page in Shippable?  First click "profile" under account on the left and then the "sync" button on that page.

**Comment by Kirtap** [comment]
That seems to have fixed it, many thanks for the quick reply.
