### ISSUE TITLE
Builds have stopped running

### ISSUE THREAD

**Issue by manish-in-java** [Shippable/support#4861]
Builds for our [account](https://app.shippable.com/accounts/55d549ca6ed0590b008bba40/integrations) have simply stopped running after May 16, 2019. The last build ran on May 16 and timed out after just over an hour. No builds ran after that. We have not received any notification either on why the builds have stopped running.

A build (job 4326) was triggered manually today and ran just fine.

**Comment by manish-in-java** [comment]
Builds are still not starting automatically. Builds being triggered manually complete just fine but they are not getting triggered automatically when a commit is pushed to the repository.

**Comment by rageshkrishna** [comment]
This usually means that the webhook on your GitHub repository has been removed or disabled. You can correct this by using the reset option in your project settings page: http://docs.shippable.com/platform/management/project/settings/#project-actions

**Comment by manish-in-java** [comment]
We have not touched the Webhooks on Bitbucket where the repository is hosted. Interestingly, the last commit triggered an automatic build (job 4327), whereas the one previous to it did not.

Attaching a screenshot to show that the Shippable Webhook is configured as expected.

![4861](https://user-images.githubusercontent.com/1606819/59022903-48c18b80-886c-11e9-8064-50abf0faf067.png)

We can re-sync the project. However, please investigate this internally to ensure that this is not a problem within the Shippable platform. Want to make sure that the builds will work automatically once the project is re-synced. Also, (our) experience shows that [all problems reported (by us)](https://github.com/Shippable/support/issues?q=author%3Amanish-in-java) so far have been problems with the Shippable platform.

**Comment by manish-in-java** [comment]
Interestingly, two more builds have run automatically. We have not re-synced the project so far.

The summary of the day thus far is this:

* A manual build (job 4326) was triggered at 11:41 AM IST and it completed successfully.
* The next push did not trigger an automatic build.
* The next three pushes triggered automatic builds (jobs 4327-4329), which completed fine.

Could the manual build triggered this morning have re-synced the project on its own? If yes, why did that not trigger a build for the first push after the manual build completed?
