### ISSUE TITLE
Error Logging in To Shippable

### ISSUE THREAD

**Issue by killua2017** [Shippable/support#4863]
Hello,

We are getting the following error when I'm attempting to login to shippable.

github accounts, emails: 
knis007, denis.sorn82@gmail.com
killua2017, bonh69@yahoo.fr

Error
An error occured, please choose an action.
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

Please assist.

Thank you.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your accounts so you should be able to sign in.

**Comment by killua2017** [comment]
Thanks heaps!
