### ISSUE TITLE
Build Error: ENOSPC: no space left on device, write

### ISSUE THREAD

**Issue by gabrielpascua** [Shippable/support#4864]
### Description of your issue:
Here is the trace from the build
```
Successfully created folder /build/state/deploy-ecs-user-manifest-1/
Failed to save file ecs-service-response.json due to Error: ENOSPC: no space left on device, write
true
Successfully created folder /build/state/deploy-ecs-user-manifest-1/
Failed to save file ecs-service-definition.json due to Error: ENOSPC: no space left on device, write
Could not save service definition for future deployments
true
Failed to deploy manifest for type: replace
Successfully created folder /build/state
Failed to save file outputVersion.json due to Error: ENOSPC: no space left on device, write
Exiting with error: true
Deployment failed with error : true
```

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
https://app.shippable.com/bitbucket/bncompass/jobs/deploy-ecs-user-qa-deploy/builds/5cfe8b2a9bbe6e0007593df4/console

- Scripts called from the yml (optional)

**Comment by trriplejay** [comment]
we're investigating

**Comment by trriplejay** [comment]
This should be fixed now, can you try running your deployment again?

**Comment by gabrielpascua** [comment]
No luck.  I kicked off a deploy from the beginning of our pipeline and this is what I get.  What changes did you make?
```
Error creating service: InvalidParameterException: Creation of service was not idempotent.
{ InvalidParameterException: Creation of service was not idempotent.
    at Request.extractError (/home/shippable/micro/nod/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/home/shippable/micro/nod/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/shippable/micro/nod/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/shippable/micro/nod/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/shippable/micro/nod/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/shippable/micro/nod/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/shippable/micro/nod/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'Creation of service was not idempotent.',
  code: 'InvalidParameterException',
  time: 2019-06-10T19:13:55.683Z,
  requestId: 'e43b77b1-8bb3-11e9-916b-b12889cfc7ae',
  statusCode: 400,
  retryable: false,
  retryDelay: 913.3281184400981 }
Successfully created folder /build/state/deploy-ecs-user-manifest-1/
Successfully saved file ecs-service-definition.json
```
https://app.shippable.com/bitbucket/bncompass/jobs/deploy-ecs-user-dev-deploy/builds/5cfeabea10f8010007f20445/console

**Comment by a-murphy** [comment]
It sounds like no previous state showing that the service had been deployed before was found, and so the previous service wasn't removed before starting the new service.  Could you remove the service on AWS and then run the deploy job with the reset option by right-clicking the job in the SPOG and selecting the "reset" option?  That will reset the deploy job state so that it won't expect anything to already be present on AWS.

**Comment by gabrielpascua** [comment]
You meant like this: http://docs.shippable.com/deploy/deleting-a-service/?  Is there a less drastic approach I can take?

**Comment by a-murphy** [comment]
No, I wasn't suggesting deleting the deploy job.  There is documentation on [resetting a deployment](http://docs.shippable.com/deploy/amazon-ecs-deploy-reset/#resetting-the-deployment), should you need it.  You'll have to delete the service on AWS manually, because it has been forgotten, and then click the "reset" option on the deploy job on Shippable.

**Comment by gabrielpascua** [comment]
We deleted the generated container images on AWS that failed, then reset the deployment, and we're still getting the same error of "Creation of service was not idempotent."

**Comment by trriplejay** [comment]
I think you'll need to delete the actual service itself, not just the container image. The service should be named: `deploy-ecs-user-qa-deploy-deploy-ecs-user-manifest-1`

you should be able to find this in the "services" tab of your cluster on ECS.  Once this is successfully deleted, you can use the 'reset' option for the shippable deploy job.

**Comment by gabrielpascua** [comment]
AWS Cluster Service deleted using trriplejay's instructions and our deployments are back to normal. Thank you both for the help. 

I'm still not sure though what triggered the original error of "**Error: ENOSPC: no space left on device, write"**.  What happened there and how was it fixed?

**Comment by trriplejay** [comment]
That was on our end. One of our service machines had run out of disk space, and then failed executing your deploy job when it tried to write some files to disk.  We've cleaned up our service machines and taken some steps to avoid encountering this in the future.
