### ISSUE TITLE
Ability to change SHIPPABLE_BUILD_DIR

### ISSUE THREAD

**Issue by tsvetomir** [Shippable/support#4865]
Currently the build path seems to be fixed, at least for GitHub-based projects to:
`/root/src/github.com/<org>/<repo>`

Is there a way to change it? I'm hitting a [specific issue](https://github.com/TypeStrong/typedoc/issues/1049) with a dependency that will not work if the path contains a dot.

**Comment by trriplejay** [comment]
It's not customizable, but in your script you could copy your source to a different directory, and run the rest of your script from there.
