### ISSUE TITLE
Jobs not automatically running

### ISSUE THREAD

**Issue by Boolos** [Shippable/support#4866]
### Description of your issue:
It appears [this job](https://app.shippable.com/github/supplypike/jobs/smoke_tests_helm_stage_platform_smokeTests/builds/5cff410f2900de00063223dc/console) is not running after the previous job completes.  I also cannot trigger it manually.  I click the "run" button, but nothing happens.  This was working as expected yesterday.  This is currently disrupting our build pipelines, so any help would be appreciated.

**Comment by Boolos** [comment]
Looks like I can't manually start these jobs either:
- https://app.shippable.com/github/supplypike/jobs/integration_tests_helm_stage_platform_integrationTests/builds/5cff41520f070400063e1f0d/console
- https://app.shippable.com/github/supplypike/jobs/supplypike-edi_integration_tests_helm_stage_platform_integrationTests/builds/5cff41aa71268a000618bfa6/console
- https://app.shippable.com/github/supplypike/jobs/smoke_tests_helm_prod_platform_smokeTests/builds/5cff426acecb900006dc29ce/console

**Comment by trriplejay** [comment]
we're investigating

**Comment by trriplejay** [comment]
@Boolos would you mind if i try triggering one of these jobs myself to try and debug this?

**Comment by Boolos** [comment]
go for it!  the pipelines should be "idempotent"

**Comment by Boolos** [comment]
Also, I don't know if this is related, but [this CI job](https://app.shippable.com/github/supplypike/cgen/dashboard) didn't kick off after a code push, and it looks like GitHub is currently operational.  But if this is separate, I can create a new issue.

**Comment by trriplejay** [comment]
actually one thing i notice is that your most recent sync job failed:
https://app.shippable.com/github/supplypike/jobs/platform_rSync/builds/5cff439ca1ba59000601200b/console

it looks like some resources may have been deleted, and there might be some mismatch between your yml and the jobs, this could possibly be causing the issue, though its not an ideal way for it to surface... can you take a look at your yml changes and see what might be causing the sync failure?

**Comment by Boolos** [comment]
aahh, i did not realize that, let me take a look, and I'll get back to you

**Comment by trriplejay** [comment]
there's definitely a bug on our end here, since the jobs should have been marked inconsistent if something they depend on was removed, but i think removing the deleted resource(s) as an IN from the jobs should get things going again.

**Comment by Boolos** [comment]
ok i'll give that a shot.  side question, in the sync job, it's processing resources that don't have to do with that pipelines repo.  is that expected?  to make that question a bit more concrete, our organization has a separate sync repo for each of our apps, and we run the sync repo for App A, it looks like it process resources for App B as well (for example).  Is this anticipated?  Does a run of any sync job process everything for the subscription?

Let me know if that question doesn't make sense.  😄

**Comment by trriplejay** [comment]
runCI jobs for the whole subscription will show up in the logs of each rSync. this is normal. Other jobs can also show up, but only when being marked consistent/inconsistent.

For example if project 1 has resource A, and project 2 has a job that uses resource A, you might see resource A mentioned in the sync of project 2, since its job has a cross-project dependency.  The Sync job has to check to see if the input resource was defined in another project.  

So rSync jobs will check for dependencies across the whole subscription, but they'll typically only show up in the logs if something is missing.

**Comment by Boolos** [comment]
Ah makes sense.  And it turns out we had a typo in our config files (improper indentation) which was causing the sync job to fail (and the `undefined` resource message).  Looks like things are working now, thanks so much for all the help!

**Comment by trriplejay** [comment]
great, glad that fixed things for you!
