### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by nurlitaa** [Shippable/support#4867]
Hello,

I am getting this error when I'm trying to login using github account:

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

Gtihub username: nurlitaa
Email : ndfatmawati@cermati.com

**Comment by ankul-shippable** [comment]
@nurlitaa I have unblocked your account. please try logging again. Sorry for the inconvenience.

**Comment by nurlitaa** [comment]
Thank you!
