### ISSUE TITLE
How to give other users access to integrations I created

### ISSUE THREAD

**Issue by DeanHutchison** [Shippable/support#4871]
### Description of your issue:
I have created a number of integrations ( Account -> Integrations ) and I would like other team members to be able to access and edit those integrations.

When other team members login the don't have any integrations in the Account -> Integrations area but they can see the Integrations in the Subscription -> Settings -> Integrations section but they can't edit them in the same way as I can as the creator.

Is there a way to let other users see and edit the integrations that I create ?

**Comment by rageshkrishna** [comment]
@DeanHutchison [Org integrations](http://docs.shippable.com/platform/tutorial/integration/subscription-integrations/#creating-an-org-integration-recommended-for-teams) is what you're looking for.

Account integrations are always private to the account that creates them. Org integrations were built to be shared within your organization.

**Comment by DeanHutchison** [comment]
Thanks @rageshkrishna, that was exactly what I was looking for.
