### ISSUE TITLE
Jobs are queued but there are available nodes

### ISSUE THREAD

**Issue by eitamb** [Shippable/support#4874]
Hi,

We have a default node pool with 4 L machines but it appears that only 2 are running in parallel and the rest of the jobs are queued instead of running on the available nodes.

We tried running various projects but it seems that all the projects which use the default nodes pool are experiencing this issue.

You can see the issue in the "Biocatch" account.

How can this be fixed?

Thanks,
Eitam Belahousky

**Comment by trriplejay** [comment]
it looks like your default node pool is currently set to utilize max of 2 nodes, though your license allows for 4.  If you click "edit" on your default node pool, you should be able to change this number to a 4, and that should allow 4 parallel nodes.

**Comment by eitambelahousky** [comment]
That solved the issue. You should know that this was already configured correctly. For some reason, it was changed once we modified our payment method.

Thanks
