### ISSUE TITLE
blocked from logging in

### ISSUE THREAD

**Issue by itsmhuang** [Shippable/support#4875]
Hi first time trying to log into Shippable and got this error. Please advise.
`Your account has been blocked as it was identified to be violating our security policy.`

**Comment by itsmhuang** [comment]
I was trying to log in via bitbucket. Same username.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by itsmhuang** [comment]
thank you
