### ISSUE TITLE
Inability to buy more nodes

### ISSUE THREAD

**Issue by brentfamily1** [Shippable/support#4876]
### Description of your issue:
On the subscription billing page, https://app.shippable.com/subs/github/PassageTech/billingV2?isEditMode=true, it says to contact support which links me here.  I would like to know how much it costs to add a node to my account.

**Comment by rageshkrishna** [comment]
Hi @brentfamily1. It appears there is an issue with your billing account. Can you please email me at ragesh@shippable.com so I can share the details in private?

**Comment by rageshkrishna** [comment]
I'm closing this issue as we've resolved this over email.
