### ISSUE TITLE
Account got blocked after sign in

### ISSUE THREAD

**Issue by hnfp** [Shippable/support#4877]
Hi,

I've just created a new github account and tried to login using my new github account, but it says "Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

**Comment by ankul-shippable** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that.I have unflagged your account so you should be able to sign in.

**Comment by hnfp** [comment]
thanks!
