### ISSUE TITLE
Your account has been blocked

### ISSUE THREAD

**Issue by jayvdk** [Shippable/support#4878]
I would like to use Shippable by using the Bitbucket identification and got this error message :

"Error
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

Bitbucket account : prtjrm

Thanks !

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by jayvdk** [comment]
That's now okay. Thanks for that !
