### ISSUE TITLE
numpy builds broken - cannot remove dind docker image

### ISSUE THREAD

**Issue by mattip** [Shippable/support#4882]
Our shippable builds started failing about two days ago. The command `sudo docker rm -fv shippable-dind` is failing, but this does not come from our CI.

https://app.shippable.com/github/numpy/numpy/runs/4875/1/console

**Comment by mattip** [comment]
ping - any news here?

**Comment by a-murphy** [comment]
A problem with the nodes in that node pool has been identified and addressed.  Please let us know if you see anything similar in the future.

**Comment by mattip** [comment]
@a-murphy errors have returned, for instance [this CI run](https://app.shippable.com/github/numpy/numpy/runs/5794/1/console)
