### ISSUE TITLE
Account blocked - Identified violating security policy

### ISSUE THREAD

**Issue by louisharris** [Shippable/support#4884]
Hi, I've just created a bitbucket account, and tried to connect to Shippable but I get this error? I'm not violating any rules, have just created a new account for company use.

**bitbucket username:** louisfharris

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by louisharris** [comment]
Thank you!
