### ISSUE TITLE
Kubernetes Integration with Shippable 

### ISSUE THREAD

**Issue by shiv-jetwal90** [Shippable/support#4887]
Kubectl Commands are not working when I am Using Cliconfig resource as a Kubernetes Integration.

**Comment by trriplejay** [comment]
can you provide a link to a build that is having this issue?

**Comment by shiv-jetwal90** [comment]
https://app.shippable.com/github/shiv-jetwal90/jobs/publish_installer/builds/5d2cbbcf2900de000646157f/console
`language: node_js
# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

#using pre-defined build variables
#full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - DOCKER_REPO="node_app"
    - DOCKER_ACC=*****# {account name}
    - SHIP_IMG_RES=$DOCKER_REPO"_img_dh"

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - node -v
    - npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - pushd $TESTS_LOC_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    - popd

  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    - docker build -t $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER .
    - if [ "$IS_PULL_REQUEST" != true ]; then docker push $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER; fi
    
integrations:
  hub:
    - integrationName: dr_dh
      type: dockerRegistryLogin
      
  kubernets:
    - integrationName: drship_kube
      type: Kubernetes

resources:
  - name: kubeconfig
    type: cliConfig
    integration: "drship_kube"

  - name: test_repo
    type: gitRepo
    integration: "test_github"
    versionTemplate:
      sourceName: "shiv-jetwal90/node_app"
      branch: master
 
#   - name: kubecluster
#     type: cluster
#     integration: "drship_kube"
#     versionTemplate: N/A

jobs:
  - name: publish_installer
    type: runSh
    steps:
      - IN: kubeconfig
      - IN: test_repo
      - IN: node_app_runCI
      - TASK:
          script:
            - echo "Hello"
            - kubectl get po
   
            
on_success:
      script:
        - echo "SUCCESS"
`

**Comment by shiv-jetwal90** [comment]
https://app.shippable.com/github/shiv-jetwal90/jobs/publish_installer/builds/5d2cbbcf2900de000646157f/console

`language: node_js

branches:
  only:
    - master


env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - DOCKER_REPO="node_app"
    - DOCKER_ACC=shiv100 # {account name}
    - SHIP_IMG_RES=$DOCKER_REPO"_img_dh"

build:

  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    - node -v
    - npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - pushd $TESTS_LOC_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    - popd

  post_ci:
    - docker build -t $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER .
    - if [ "$IS_PULL_REQUEST" != true ]; then docker push $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER; fi
    
integrations:
  hub:
    - integrationName: dr_dh
      type: dockerRegistryLogin
      
  kubernets:
    - integrationName: drship_kube
      type: Kubernetes

resources:
  - name: kubeconfig
    type: cliConfig
    integration: "drship_kube"

  - name: test_repo
    type: gitRepo
    integration: "test_github"
    versionTemplate:
      sourceName: "shiv-jetwal90/node_app"
      branch: master
 
#   - name: kubecluster
#     type: cluster
#     integration: "drship_kube"
#     versionTemplate: N/A

jobs:
  - name: publish_installer
    type: runSh
    steps:
      - IN: kubeconfig
      - IN: test_repo
      - IN: node_app_runCI
      - TASK:
          script:
            - echo "Hello"
            - kubectl get po
   
            
on_success:
      script:
        - echo "SUCCESS"
`

**Comment by shiv-jetwal90** [comment]
https://app.shippable.com/github/shiv-jetwal90/jobs/publish_installer/builds/5d2cbbcf2900de000646157f/console


`language: node_js

branches:
  only:
    - master


env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - DOCKER_REPO="node_app"
    - DOCKER_ACC=shiv100 # {account name}
    - SHIP_IMG_RES=$DOCKER_REPO"_img_dh"

build:

  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    - node -v
    - npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - pushd $TESTS_LOC_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    - popd

  post_ci:
    - docker build -t $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER .
    - if [ "$IS_PULL_REQUEST" != true ]; then docker push $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER; fi
    
integrations:
  hub:
    - integrationName: dr_dh
      type: dockerRegistryLogin
      
  kubernets:
    - integrationName: drship_kube
      type: Kubernetes

resources:
  - name: kubeconfig
    type: cliConfig
    integration: "drship_kube"

  - name: test_repo
    type: gitRepo
    integration: "test_github"
    versionTemplate:
      sourceName: "shiv-jetwal90/node_app"
      branch: master
 


jobs:
  - name: publish_installer
    type: runSh
    steps:
      - IN: kubeconfig
      - IN: test_repo
      - IN: node_app_runCI
      - TASK:
          script:
            - echo "Hello"
            - kubectl get po
   
            
on_success:
      script:
        - echo "SUCCESS"
`

**Comment by shiv-jetwal90** [comment]
https://app.shippable.com/github/shiv-jetwal90/jobs/publish_installer/builds/5d2cbbcf2900de000646157f/console

Shippable.yaml-

```
language: node_js

branches:
  only:
    - master


env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - DOCKER_REPO="node_app"
    - DOCKER_ACC=shiv100 # {account name}
    - SHIP_IMG_RES=$DOCKER_REPO"_img_dh"

build:

  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    - node -v
    - npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - pushd $TESTS_LOC_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    - popd

  post_ci:
    - docker build -t $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER .
    - if [ "$IS_PULL_REQUEST" != true ]; then docker push $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER; fi
    
integrations:
  hub:
    - integrationName: dr_dh
      type: dockerRegistryLogin
      
  kubernets:
    - integrationName: drship_kube
      type: Kubernetes

resources:
  - name: kubeconfig
    type: cliConfig
    integration: "drship_kube"

  - name: test_repo
    type: gitRepo
    integration: "test_github"
    versionTemplate:
      sourceName: "shiv-jetwal90/node_app"
      branch: master
 


jobs:
  - name: publish_installer
    type: runSh
    steps:
      - IN: kubeconfig
      - IN: test_repo
      - IN: node_app_runCI
      - TASK:
          script:
            - echo "Hello"
            - kubectl get po
   
            
on_success:
      script:
        - echo "SUCCESS"

```

**Comment by trriplejay** [comment]
based on the error, it sounds like there might be some information missing from your kubeconfig file, can you verify that it's a valid file that you can use to connect to your cluster?

**Comment by shiv-jetwal90** [comment]
I tried it 2-3 times, but didn't work for me.

**Comment by shiv-jetwal90** [comment]
Ok I will verify and update you.

**Comment by shiv-jetwal90** [comment]
I created new cluster and new kube config file works fine for me.
