### ISSUE TITLE
Bitbucket account blocked; unable to log in

### ISSUE THREAD

**Issue by TonyLovesDevOps** [Shippable/support#4890]
I'm attempting to sign in with my bitbucket username: _tony-msignia_

I'm receiving the following error:
```Error
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

```

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by TonyLovesDevOps** [comment]
Thanks!
