### ISSUE TITLE
Email notifications failing to send

### ISSUE THREAD

**Issue by jasonbelt** [Shippable/support#4892]
Email notifications are not being sent out due to error messages like the following

`
Sending Email
Failed to send mail for objectId:5d3b525ba1c1050006a9bf8b with error Error: Invalid login: 535 5.7.0 Mailgun is not loving your login or password`

Here is an example build that contains the error in its log:
https://app.shippable.com/github/santoslab/slang-embedded-building-control/runs/149/summary/

**Comment by trriplejay** [comment]
thanks for letting us know. we're investigating.

**Comment by vidavidorra** [comment]
This is still the case today (at least for my [build](https://app.shippable.com/github/vidavidorra/ci-fiddle/runs/108/1/console)). This is quite a big deal, not receiving any mail when the build fails. Any updated on this? @trriplejay

**Comment by vidavidorra** [comment]
@manishas @rageshkrishna ?

**Comment by naorlivne** [comment]
also affects me as I did not recieve any alert when encountering  #4914

**Comment by timtribers** [comment]
Am also suffering this on our builds @trriplejay  :(

**Comment by trriplejay** [comment]
Sorry for the extreme delay on this, but emails are now fixed. You should start receiving them from any future builds based on your configured settings.  Please let me know if you're still having trouble.

**Comment by timtribers** [comment]
Many thanks @trriplejay
