### ISSUE TITLE
Broken escaping in json

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#4895]
### Description of your issue:
Shipctl notify is **broken**. This simple command...

```
              shipctl notify "vue-ssr-playground-notifier" \
                --username="SSR deployment" \
                --recipient="#deployment" \
                --pretext="Deployment začal" \
                --text="Nasazuju \"${DEPLOYED_GIT_REF}\" do prostředí \"playground\". Viz ${BUILD_URL}" \
                --icon_url="https://www.damejidlo.cz/static/apple-touch-icon.png"
```
...crashes:
```
parse error: Invalid numeric literal at line 1, column 100
Error: payload is not valid JSON
```

I was curious why the `envsubst` command is required. There is a `jq` program that can be used to form a valid json. AFAIK it is alredy required by shippable.

- Link to the build failure
[Broken build](https://app.shippable.com/github/damejidlo/jobs/vue-ssr-playground-build/builds/5d4191ae77f28b00060d7167/console)

**Comment by mbrodala** [comment]
Just for testing can you retry without any special characters, thus in your case `č` and `ř`?

**Comment by RadekDvorak** [comment]
@mbrodala: special characters (č, ř) are ok.

**Comment by trriplejay** [comment]
Could you try removing the escaped quotes in your `--text` argument? I suspect that is causing this error. We do use jq to check that the payload is json before trying to send it. envsubst is used to replace all of the ENVs with their values in the payload before sending it.

**Comment by RadekDvorak** [comment]
Hi,

have you been able to reproduce the error using the command I wrote in my first post? Unless the command is insuficient I would kindly prefer you test `shipctl` in your CI/testsuite.

**Comment by RadekDvorak** [comment]
If I look at the right sources, this [json template](https://github.com/Shippable/node/blob/21a12b43b530607baf03d51152dc59253add2a1d/shipctl/aarch32/Ubuntu_16.04/utility.sh#L1252) greatly depends on [shipctl replace](https://github.com/Shippable/node/blob/21a12b43b530607baf03d51152dc59253add2a1d/shipctl/aarch32/Ubuntu_16.04/utility.sh#L1314) to know json syntax (to escape strings corretcly). Unfortunately it [does not look](https://github.com/Shippable/node/blob/21a12b43b530607baf03d51152dc59253add2a1d/shipctl/aarch32/Ubuntu_16.04/shippable_replace) like it does.

**Comment by trriplejay** [comment]
I can confirm this this command: `- shipctl notify mySlackNotifier --text="this will soon test escaped quotes"` results in a successful message sent via slack

while this command: `- shipctl notify mySlackNotifier --text="this will soon test \"escaped\" quotes"` results in the same error you see: 
```
parse error: Invalid numeric literal at line 1, column 120
Error: payload is not valid JSON
```

This might seem odd, but I was able to get the correct payload to show up by triple-escaping the quotes like this: `- shipctl notify mySlackNotifier --text="this will soon test \\\"escaped\\\" quotes"`

![image](https://user-images.githubusercontent.com/6869398/62253938-58f97100-b3ac-11e9-942f-dc73f9e15c3f.png)

So if you absolutely need the quotes, I'd recommend using that method. As you said, when the values are put into the payload, there is no special treatment for escaped characters, they are processed by bash, so much like doing an `echo "my \"escaped\" string"`, the escapes will be processed, and the resulting payload will end up having extra quotes.

**Comment by RadekDvorak** [comment]
Hi @trriplejay,

thanks for the workaround. Quotes are "nice to have", I do not need them. I care about platform stability instead. I care about the time I spend debugging the issue. I am worried whether a CI/CD platform actually uses CI for its code.
