### ISSUE TITLE
Unclear build failures

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4900]
Gradle build is successful, but the build was still marked as `failed`.
https://app.shippable.com/github/Falkonry/barbary/runs/2112/1/console

**Comment by rageshkrishna** [comment]
You have an error showing up when your `after_build.sh` script runs. Please take a look at line 61664 of the downloaded console logs.

**Comment by rageshkrishna** [comment]
@phagunbaya Do you need any more help on this issue?

**Comment by phagunbaya** [comment]
No. thanks
