### ISSUE TITLE
trigger build only on master build

### ISSUE THREAD

**Issue by vedant-khandelwal** [Shippable/support#4901]
We're trying to create jobs that get triggered only when commits are merged to master of a github repo. We've tried setting the job config in the shippable.yaml. The rsync jobs are failing since they're unable to find runCI dependency for the same repo. Here's the link to the build failure: https://app.shippable.com/github/Falkonry/jobs/systems_master_rSync/builds/5d4c237b31101c000689067c/console

Please advice how we can proceed. Thank you.

**Comment by a-murphy** [comment]
It looks like that project was enabled quite a while ago and hasn't been connected to Assembly Lines.  Could you go to the project settings page for the CI project (click the gears in the top right on the project dashboard) and click "hook" in the last panel?  That will connect the project to Assembly Lines and then rerunning the rSync job should be able to find the project.

**Comment by phagunbaya** [comment]
Thanks. worked.
