### ISSUE TITLE
Parallel rspec building not running in parallel

### ISSUE THREAD

**Issue by raelgc** [Shippable/support#4904]
I tried to follow the old recipe from here: http://blog.shippable.com/running-parallel-builds-on-shippable.

It got spllited on 3, but for some reason, each build got ran in a sync way, not in parallel.

Am I missing something?

- Build: https://app.shippable.com/github/arizonabay/output/runs/15272/summary/console

**Comment by a-murphy** [comment]
It looks like your subscription only has one build node.  Builds will run in parallel when there are nodes available to run multiple builds.  Additional nodes may be purchased following these directions: http://docs.shippable.com/platform/management/subscription/billing/#upgrade-or-downgrade-your-plan.

**Comment by raelgc** [comment]
Oh, right! Thanks!
