### ISSUE TITLE
Error Build Project

### ISSUE THREAD

**Issue by renanrboliveira** [Shippable/support#4907]
### Description of your issue:
I created a organization and migrated repo of my personal account to organization and now I'm this problem.

https://app.shippable.com/github/mandrakess/jobs/easy-flooring-api_staging_rSync/builds/5d53013931101c00068bdb37/console

**Comment by a-murphy** [comment]
Part of the runCI job got left behind in the other subscription.  We'll clean that up and let you know when it should be working again.

**Comment by a-murphy** [comment]
Could you try running your rSync job again?  The CI projects should be only in your new subscription now, and so will be found by the rSync job.

The statuses of the last run on the subscription dashboard page will update as jobs run in this subscription; previous runs from the previous subscription may still be seen on the project page history tab.

**Comment by renanrboliveira** [comment]
@a-murphy That's ok now, thanks =).

**Comment by a-murphy** [comment]
Let us know if anything else strange occurs from the change in subscription.
