### ISSUE TITLE
SSH key not updating with synced BitBucket

### ISSUE THREAD

**Issue by ghost** [Shippable/support#4910]
My SSH key in Shippable is not the same as in BitBucket. When I sync the settings the SSH key is not updating.

**Comment by a-murphy** [comment]
Assuming you mean that the SSH key added to you project as a deploy key isn't the one shown in the UI, the SSH key shown on the subscription settings page is a different key than the one automatically added for a project.  Each project has a different deploy key and there is only one subscription key.

Could you explain what problem you think a mismatched SSH key is causing?  And, if this was about a CI project, confirm that you clicked "reset all keys" on the project settings page to reset the deploy key?

**Comment by ghost** [comment]
Thanks for your reply! I'm sorry for not elaborating enough. I'm talking about the SSH key under Profile > Identities. The provider 'Bitbucket' shows two old SSH keys that have been deleted from my Bitbucket account. The new SSH key I have added to Bitbucket is not being synced with my Shippable account. I have pressed the 'sync' button on the profile page but that doesn't refresh the keys.

The reason that I need my SSH key is because I'd like to SSH into a failed build. The error message I receive is "Permission denied (publickey)".

**Comment by a-murphy** [comment]
Unfortunately we can't update those keys.  The Bitbucket v1 API [was deprecated and removed](https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/?_ga=2.198025071.1552210277.1565970051-1409761674.1555084965), and Bitbucket [doesn't allow us to get the public SSH keys in v2](https://bitbucket.org/site/master/issues/16975/oauth-authentication-methods-are-blocked).

If you have a GitHub account linked to your Bitbucket account on Shippable, you can add the SSH key to your GitHub account and that will be synchronized.
