### ISSUE TITLE
Git LFS with Bitbucket not working

### ISSUE THREAD

**Issue by rxjx** [Shippable/support#4912]
I am migrating a project on Bitbucket to Git-LFS. This project was building before the migration for over a year. The migration is on the branch referenced in the failed build below. 

I followed the instructions in https://github.com/Shippable/support/issues/3670 by:
- generating an app password in Bitbucket. Note that we only provided for read access to the repo.
- creating a new integration of type 'Git Credential' in addition to our existing integration of type 'BitBucket' (which** has to remain for the other projects).
- configuring a HTTPS custom clone URL with the username specified in the Git integration for the project we are migrating

However, the build fails with 'remote: Invalid username or password'. I am appending the link to the failed build : https://app.shippable.com/bitbucket/thetalake/objectdetector/runs/124/1/console 
and the yaml file as an attachment.

**Comment by a-murphy** [comment]
It doesn't look like the gitCredential integration has been added to the `shippable.yml` file.  Could you add it under the `integrations` section in the following format?
```YML
  generic:
    - integrationName: my-gitCredentials-integration # the name you chose for your integration
```

The `generic` section should be at the same level as `notifications` or `hub`.

**Comment by rxjx** [comment]
Thanks. Is that the only change needed to the yml file? Should there be additional attributes specified for the integration?

**Comment by a-murphy** [comment]
The other required values (the username and password) should be stored in the subscription integration, so you don't need to specify them again.  Just the integration name in the YML.

**Comment by rxjx** [comment]
Tried this and got a new error:

  Errors 
Invalid integration ObjectDetectorLFS specified for integration type: generic

Should the integration type be ‘Git Credential’?

**Comment by a-murphy** [comment]
No, it should be in the `generic` section.  Is your integration named "ObjectDetectorLFS" on the subscription integrations page?  The name in the YML should match the name in the left column on the subscription integrations page, accessible from the subscription dashboard by selecting "integrations" in the gears dropdown in the top right.

**Comment by rxjx** [comment]
Yes, the names match exactly.

**Comment by rxjx** [comment]
I got my boss to create a similar integration just in case permissions was an issue and tried that but got the same error. Does the path to the repo specified in the integration need to include the project folder if there are multiple projects in the repo?

**Comment by rxjx** [comment]
Any new info on this? Is there a possibility this can be resolved soon?

**Comment by a-murphy** [comment]
Could you double-check that the name (`integrationName: name`) in the YML exactly matches the name the integration was given in the subscription?  This error means that no integration was found with that name.

To get to the subscription integrations page:
  1. Click the subscription name in the left sidebar.
  2. Click the picture of three gears in the top right and then "integrations."

On the subscription integrations page, the names used in the YML are the ones in the leftmost column ("Subscription Integration Name").  If you click on a subscription integration name to edit the integration, it will also say "this is the name to use in the YML files" under the name at the top.

**Comment by rxjx** [comment]
It did match when I created the integration in my account which is not an Admin account for our company. I then asked my boss to create the integration and deleted mine. I used the name of the integration he created correctly. However, the odd thing is that I don’t see the integration he created in my list of integrations. However, I don’t see other integration he has created in the past (for email and slack) in my list either and those are working just fine. So I don’t think that is the issue.

**Comment by a-murphy** [comment]
It sounds like you are looking at your list of account integrations, not the subscription integrations available to the subscription.  Account integrations can be linked to subscription integrations, which may or may not have the same name, but are not available for use in a subscription unless they are linked to a subscription integration.  You won't be able to see anyone else's account integration, but will be able to see which integrations are available to a subscription on the subscription integrations page.  More information about the different types of integrations is available [here](http://docs.shippable.com/platform/tutorial/integration/subscription-integrations/).

**Comment by rxjx** [comment]
These are the settings for the integration we added:

**Comment by rxjx** [comment]
Ah, I see the problem now. The subscription integration has a different name than the associated account integration because that name was changed later in the account integration. How can I make them consistent?

**Comment by a-murphy** [comment]
If you go to the subscription integration page (not the account integration page), you can click on the name of one of the subscription integrations to go to a page to edit that integration.  Then there's a delete button at the bottom of the edit page.  I would suggest deleting the integrations with the wrong names.  Once the wrong integrations are deleted, you can click the + in the top right to add a new subscription integration with the name you want.  Select "use an account integration" at the top of the new integration page and then type in your intended name, select your account integration, and click "save."

**Comment by rxjx** [comment]
OK, thanks. Will try this out.

**Comment by rxjx** [comment]
OK, we’re back to the original error.



Build log is at https://app.shippable.com/bitbucket/thetalake/objectdetector/runs/130/1/console <https://app.shippable.com/bitbucket/thetalake/objectdetector/runs/130/1/console>

Yaml file has this:



Subscription integration is this:



and



Is this happening because the user in the integration doesn’t match that in the git clone command? They’re both valid users and I used the Bitbucket app password for the integration.

**Comment by a-murphy** [comment]
The username in the integration should match the username in the URL configured in the project settings (the part after `https://` and before `@`).  And the host in the integration should be `bitbucket.org` because you are using Bitbucket.  Could you check both of those?

**Comment by rxjx** [comment]
The user name was the same. The host however, was different in that we use https://bitbucket.org/<our-company-name>/ to access our repos. I changed it to just https://bitbucket.org <http://bitbucket.org/> and retried but that made no difference. Are you able to see the images I am appending in my emails?

**Comment by rxjx** [comment]
I removed the https:// and that seems to be going further. Should’ve realized that sooner. Will update if it succeeds.

**Comment by a-murphy** [comment]
No, I can't see any images.  I'm not sure if GitHub supports attachments in email replies to comments on an issue.  Let us know if your integration works.

**Comment by rxjx** [comment]
I think the integration is working. However, git_sync is happening before I install LFS in the ci section of my yml file. How do I ensure that LFS is installed in my docker container before git_sync? I think you have a copy of my yml file already since I zipped it and appended it earlier in this chain.

**Comment by rxjx** [comment]
Please remove that zipped yml file from the forum after reviewing it.

**Comment by a-murphy** [comment]
It isn't possible to run any commands specified in a `shippable.yml` file in the container before `git_sync`.  However, if you really need something installed that is not available by default, you can [use a custom Docker image](http://docs.shippable.com/ci/custom-docker-image/) and install whatever you need in your image.

I can't completely remove the file you uploaded to GitHub; only GitHub would have the ability to do so.  You can edit the comment yourself by clicking the `...` to the right in the header above the comment and remove the link to it.

**Comment by rxjx** [comment]
It doesn’t look like this is working still. I changed my yml file to this so that I could update git LFS files after git-sync:
--------------------------------------------------------------------------
 ci:
    # run tests and code coverage
    - export LC_ALL=C
    - apt-get install -y python-pip
    - pip install coverage
    - pip install nose

    - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
    - apt-get install git-lfs
    - git lfs install
    - git lfs fetch
    - git lfs pull
—————————————————————————————————————

However, now I get this error (see https://app.shippable.com/bitbucket/thetalake/objectdetector/runs/133/1/console <https://app.shippable.com/bitbucket/thetalake/objectdetector/runs/133/1/console> for log):

--------------------------------------------------------------------------
  build_ci
  export LC_ALL=C
  apt-get install -y python-pip
  pip install coverage
  pip install nose  
  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
  apt-get install git-lfs
  git lfs install
Updated git hooks.

Git LFS initialized.


  git lfs fetch
fetch: Fetching reference refs/heads/VID-600

batch response: Authorization error: https://thetalake-rich@bitbucket.org/thetalake/objectdetector.git/info/lfs/objects/batch
Check that you have proper access to the repository

error: failed to fetch some objects from 'https://thetalake-rich@bitbucket.org/thetalake/objectdetector.git/info/lfs’
—————————————————————————————————————

So it looks like I still cannot access Bitbucket’s LFS files.

**Comment by rxjx** [comment]
OK, I think we can close this. I added git-lfs to my docker image and now everything seems to work correctly. So the steps that were missing:

- make sure the Git Credentials integration is a subscription integration
- the integration’s host should be set to bitbucket.org <http://bitbucket.org/> (ho http before or anything after)
- make sure git-lfs is installed in your docker image so that git-sync can use it because ‘git lfs pull’ in the [ci] section will not work.
