### ISSUE TITLE
docker: Error response from daemon: Conflict. The container name "/shippable-dind" is already in use by container

### ISSUE THREAD

**Issue by naorlivne** [Shippable/support#4914]
### Description of your issue:

Upon reaching the `  sudo docker run -d --privileged --name shippable-dind docker:17.09.1-dind` step The following error is received: 
```
docker: Error response from daemon: Conflict. The container name "/shippable-dind" is already in use by container "8d42ce9836972a4991a7abe7dbc2425b909985818952c257d933003ec2958e75". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

The build then get stuck for a long time before failing due to timeout a few steps later without any other error being shown.

I've had this problem happen on & off in the past but now it seems like it's constant across multiple builds of multiple different repos

Not sure if it's relevent or not but this is a ARM based build running on `shippable_shared_aarch64 `

Please fix as I have 3 projects who's build fails & can't release a ARM version for as a result of this bug.

### Partial list of affected builds 

- https://app.shippable.com/github/nebula-orchestrator/reporter/runs/106/1/console
- https://app.shippable.com/github/nebula-orchestrator/reporter/runs/105/1/console
- https://app.shippable.com/github/nebula-orchestrator/manager/runs/274/1/console
- https://app.shippable.com/github/nebula-orchestrator/manager/runs/273/1/console

**Comment by naorlivne** [comment]
Happened again on https://app.shippable.com/github/nebula-orchestrator/manager/runs/277/1/console

Are you running the jobs inside a shared server on a shared Docker engine (IE not containerized\jailed\etc)? 

based on the errors of: 
```
  sudo docker rm -fv shippable-dind
Error response from daemon: No such container: shippable-dind
  sudo docker run -d --privileged --name shippable-dind docker:17.09.1-dind
docker: Error response from daemon: Conflict. The container name "/shippable-dind" is already in use by container "8d42ce9836972a4991a7abe7dbc2425b909985818952c257d933003ec2958e75". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
```

I'm guessing that the issue is that when multiple builds happen on the same time there's a race condition as shippable-dind share the name between jobs.

**Comment by naorlivne** [comment]
And once again in https://app.shippable.com/github/nebula-orchestrator/manager/runs/281/1/console 

Can I get any reply on this? half the time builds fail and it's been a week since first reported with no response.

**Comment by trriplejay** [comment]
Hi @naorlivne, sorry about the delay.  The shared nodes were having some docker issues.  We've restarted them and everything seems to be back to normal. 

Though the nodes are shared, your build will be the only one running on any given node at any one time, so if you have two builds running at the same time, they are running on separate nodes and shouldn't interfere with each other.  It could be that one node had this particular issue, and so whenever a build happened to be assigned to that node, you would see this issue, making it intermittent and unpredictable.

please let us know if you're still seeing this problem.

**Comment by naorlivne** [comment]
Thanks for the response, I'll be sure to reopen a ticket if the issue repeats itself.
