### ISSUE TITLE
Commits on master not triggering the CI

### ISSUE THREAD

**Issue by aurelien-reeves** [Shippable/support#4915]
### Description of your issue:
Our last commits on the master branch did not triggered the CI
No apparent reason to that

https://app.shippable.com/github/hiptest/hiptest

**Comment by hunt3ri** [comment]
Yes same here, PRs seem to trigger builds but not direct commits onto a branch

**Comment by rageshkrishna** [comment]
GitHub is reporting "degraded performance" on notifications at this time: https://www.githubstatus.com/

**Comment by aurelien-reeves** [comment]
Ok, tx.
CI has finally been triggered.
It may be related to GitHub issues.

**Comment by aurelien-reeves** [comment]
Looks fixed.
