### ISSUE TITLE
Issue accessing API

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#4916]
Is there any issue with the APIs ? APIs are getting timed out.

**Comment by phagunbaya** [comment]
Seems to be working now. Could you please explain the issue? Also, the status page was not visible.

**Comment by rageshkrishna** [comment]
Hi @phagunbaya. We did have a connectivity issues in some of our internal APIs which caused some calls to timeout. The issue has been corrected and things should be back to normal now.
