### ISSUE TITLE
Can't create a node other than Ubuntu 14.04

### ISSUE THREAD

**Issue by stsquad** [Shippable/support#4922]
I've been trying to update the default Node for the QEMU project to something more upto date than Ubuntu 14.04. Even after deleting my account and starting again with a blank slate 14.04 is the only node type offered.

Other community members have reported they were able to create 1 16.04 node after deleting their account but they couldn't change the configuration after that.

I think this is a bug.

**Comment by a-murphy** [comment]
Your subscription should now have an Ubuntu 16.04 node instead of an Ubuntu 14.04 node.  Please let us know if there are any problems with the switch to 16.04.

**Comment by stsquad** [comment]
I can see the project node has been updated but my personal one is still stuck at 14.04. Does this mean this is a manual process for every user?

**Comment by a-murphy** [comment]
I've updated the stsquad GitHub subscription to Ubuntu 16.04 as well.

New subscriptions will have Ubuntu 16.04 nodes by default, but we try not to change the environment in which builds run for existing subscriptions for more predicable build results.  Subscriptions that have purchased either additional nodes or unlimited private builds are able to change the operating system of their nodes on the billing page.  For other subscriptions, we have to update each one individually.
