### ISSUE TITLE
The dashboard is empty

### ISSUE THREAD

**Issue by magwas** [Shippable/support#4923]
### Description of your issue:
I see no jobs when I go to shippable com, which redirects to https://app.shippable.com/accounts/557717717915e70b00593809/dashboard
Before that happened I tried to stop a build job twice, but some error happened both times.

**Comment by magwas** [comment]
When i go to individual job page, I see it.
This is the job I tried to stop, and it is still processing:
https://app.shippable.com/github/edemo/PDEngine/runs/949/1/console

**Comment by a-murphy** [comment]
Have you tried clicking "profile" in the left sidebar and then "sync."  It sounds like we may have been unable to correctly determine your permissions on that project last time it was synchronized.

**Comment by provPaulBrousseau** [comment]
@magwas, I am experiencing the same issue.

**Comment by a-murphy** [comment]
We're investigating and will update when we have resolved the slowness identified this morning.

**Comment by magwas** [comment]
Now app.shippable.com is completely unavailable.

**Comment by a-murphy** [comment]
In order to resolve in underlying issue, we had to make shippable.com temporarily unavailable.  We are continuing to work on it and will update again when it is resolved.

**Comment by a-murphy** [comment]
We have resolved the problem and shippable.com is again available.

**Comment by provPaulBrousseau** [comment]
Is it possible that the fix is still rolling out?  We are still experiencing issues.

**Comment by a-murphy** [comment]
Everything should be updated now.  If you are still not seeing jobs that you should, could you try clicking "profile" in the left sidebar and then "sync"?  It might be that some permissions were lost as a result of the issue and may need to be re-synchronized.

**Comment by provPaulBrousseau** [comment]
After syncing my profile, I can see the list of jobs in the "latest status" view.  ~~However, almost all of them are reporting "not built".~~ After refreshing the list (not the page), I can see the jobs, and their build status.  The history view does show a history as expected.

**Comment by magwas** [comment]
syncing seem to have solved the problem.
