### ISSUE TITLE
Status page inactive

### ISSUE THREAD

**Issue by danielahedges** [Shippable/support#4924]
My builds are not running right now. I came here to investigate why. You have a link to your status page here: http://status.shippable.com/ That page redirects to a statuspage.io address that reports that your service is inactive.

Is your service down now, or is it just that your statuspage account is down?

Thanks!

**Comment by brentfamily1** [comment]
We have builds that are not triggering as expected right now so it does appear to be an outage right now.

**Comment by manishas** [comment]
Status page is up and is updated. We're working on restoring the service, will have an update soon.

**Comment by danielahedges** [comment]
Thanks! I'll close this issue (the problem with the status page) and I will follow the issue reported in the status page separately.
