### ISSUE TITLE
Can't stop processing jobs

### ISSUE THREAD

**Issue by maggiedeuitch** [Shippable/support#4926]
Hi there,

I have two processing jobs (manifest jobs), which seem to be stuck. I have tried the stop Action, but when I refresh, they are still there. Going into the job and clicking cancel does not work either.
They have been running for 22 hours. It might be related to the outage yesterday?

[Job 1](https://app.shippable.com/github/formhero/jobs/formhero-rc-staging-catalog-manifest/builds/5d68002313741b0007bfec70/)

[Job 2](https://app.shippable.com/github/formhero/jobs/formhero-rc-staging-filler-manifest/builds/5d680011d9f40a00063cbbba/)

**Comment by a-murphy** [comment]
Yes, they were probably still displaying "processing" because of the outage.  I've cancelled those two jobs for you.  Please let us know if you notice anything else strange.

**Comment by maggiedeuitch** [comment]
Thank you, working fine now!
