### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by ltujiba** [Shippable/support#4927]
Hi,

I was trying to create an account in Shippable using my github account. When I signed in, It tells me the the account is blocked. It was redirected to an error page.
It says 'Your account has been blocked as it was identified to be violating our security policy.

Credentials
Github Username: ltuijba

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
