### ISSUE TITLE
My bitbucket account is blocked

### ISSUE THREAD

**Issue by mrfrodo** [Shippable/support#4930]
### Description of your issue:

I goto the url http://shippable.com. I press the button LOGIN. I choose signin with Bitbucket. Then I am redirectet to https://app.shippable.com/error.
Please advice.
My bitbucket account username is frodejohns.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
