### ISSUE TITLE
invalid apiToken error seen in Shippable UI

### ISSUE THREAD

**Issue by shmax** [Shippable/support#4932]
### Description of your issue:

After the outage (and your everything-is-back-to-normal post), I am now seeing a red error popup on virtually every page of the Shippable interface. The errors vary depending on what I clicked on, but here are a few typical examples:

![image](https://user-images.githubusercontent.com/773172/64217259-905ab200-ce71-11e9-88e3-245467455c75.png)

![image](https://user-images.githubusercontent.com/773172/64217332-de6fb580-ce71-11e9-80d1-a0fb4670855a.png)

![image](https://user-images.githubusercontent.com/773172/64217351-edeefe80-ce71-11e9-9b1e-ead5fe78bd4f.png)

**Comment by manishas** [comment]
We're looking into this :(

**Comment by manishas** [comment]
This should be resolved now. Please let us know if you run into anything else, and thanks for your patience!
