### ISSUE TITLE
Unable to login: getSystemIntegrationById returned an error

### ISSUE THREAD

**Issue by pwarnock** [Shippable/support#4933]
Error trying to login with Bitbucket

getSystemIntegrationById for :id 58a7c57801d83b0f00dec47a returned an error

**Comment by pwarnock** [comment]
Since status update of "The Api issue has been addressed, it was a misconfiguration while fixing the outage. We are continuing to monitor the service." we're able to login, but not see our projects.

**Comment by pwarnock** [comment]
When I click on integrations, I see: "Subscription integrations could not be loaded. Integration permissions will not be displayed."

**Comment by a-murphy** [comment]
Have you tried clicking your "profile" in the left sidebar and then the "sync" button?  Or if it still fails after that, logging out and back in?  It sounds like some of the project permissions may have been missed when they were last synchronized as a result of the outage.

**Comment by pwarnock** [comment]
Thanks!
