### ISSUE TITLE
Can't see former subscriptions

### ISSUE THREAD

**Issue by parsaeini** [Shippable/support#4934]
subscriptions list is gone and can't see any of them.
Everything looks like a new start!

**Comment by manishas** [comment]
Can you please click on Profile and then on Sync? Let me know if that restores everything.

**Comment by parsaeini** [comment]
I logged out and logged in again and synced my repositories
now i can see the subscriptions but I'm getting an error:
   "Unable to fetch the repository. If this is a private repository, please make sure that the repository still contains Shippable's deploy key. If the deploy key is not present in the repository, you can use the "Reset Project" button on the project settings page to restore it."
what is wrong with the deploy key?before it would be set automatically

**Comment by parsaeini** [comment]
> subscriptions list is gone and can't see any of them.
> Everything looks like a new start!

**Comment by parsaeini** [comment]
> Can you please click on Profile and then on Sync? Let me know if that restores everything.

I logged out and logged in again and synced my repositories
now i can see the subscriptions but I'm getting an error:
"Unable to fetch the repository. If this is a private repository, please make sure that the repository still contains Shippable's deploy key. If the deploy key is not present in the repository, you can use the "Reset Project" button on the project settings page to restore it."
what is wrong with the deploy key?before it would be set automatically

**Comment by Amir-4m** [comment]
> Can you please click on Profile and then on Sync? Let me know if that restores everything.

I got the same problem with error "Unable to fetch the repository. If this is a private repository, please make sure that the repository still contains Shippable's deploy key. If the deploy key is not present in the repository, you can use the "Reset Project" button on the project settings page to restore it."

**Comment by a-murphy** [comment]
Deploy keys are automatically added to private projects when they are enabled.  The keys are not automatically replaced when they are deleted on the source provider.  Could you check if the keys are present, and if not, click the "reset all keys" button on the project settings page to replace the key and webhook on the repository?

**Comment by parsaeini** [comment]
> Deploy keys are automatically added to private projects when they are enabled. The keys are not automatically replaced when they are deleted on the source provider. Could you check if the keys are present, and if not, click the "reset all keys" button on the project settings page to replace the key and webhook on the repository?

Thank you so much, it worked.
