### ISSUE TITLE
Slow build or slow logging

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#4935]
Hi,

Looks like the build itself or log streaming is getting really slow after the outage.

This example build usually takes about 15minutes, and looks like each steps takes as usual. However, the total elapsed time for the build and the actual log streaming shows much slower performance.

Every build seems to experience the same issue.

https://app.shippable.com/github/Knowre-Dev/knowre/runs/21931/summary/console

**Comment by trriplejay** [comment]
@Kivol are you still seeing this? we increased our capacity yesterday to better handle the load. Let me know if things don't seem back to normal for you.

**Comment by Kivol** [comment]
Yeah, looks like the performance is fine since Sep 4, 12:15 PDT. Thanks for your effort!
