### ISSUE TITLE
All configuration dissapeared, can't start new builds

### ISSUE THREAD

**Issue by pvangeel** [Shippable/support#4936]
This morning I discovered that shippable is not picking up code changes from bitbucket. When I logged in I see that all my build configurtions have dissapeared, and that manually triggering a new one doesn't work.
<img width="604" alt="Screenshot 2019-09-04 at 09 41 21" src="https://user-images.githubusercontent.com/5185399/64235504-c7c07180-cef8-11e9-8f03-a773bd546ca4.png">

**Comment by pvangeel** [comment]
Update: It seems I can start manual builds, but we lost all history?

**Comment by rageshkrishna** [comment]
Can you try syncing your account? Click on "Profile" under "Account" in the sidebar and then on the "Sync" button.

**Comment by pvangeel** [comment]
I tried that multiple times as it was a suggestion on the status page. I can see my repositories, but all history is gone. New commits on configured branches no longer get built automatically

**Comment by rageshkrishna** [comment]
Sorry for the trouble. Please logout of Shippable, login with BitBucket and try to sync your account once again. This should restore your access.

**Comment by pvangeel** [comment]
Ok this seems to have worked. Thanks for the quick response!

**Comment by pvangeel** [comment]
Unfortunately this happened again. 
This time I did get my repositories back after an account sync. I did lose all 'latest status' and history again though : /

**Comment by pvangeel** [comment]
Nevermind it settled after a while
