### ISSUE TITLE
URGENT: Bitbucket projects (and section) not showing in App section

### ISSUE THREAD

**Issue by PaulHughes01** [Shippable/support#4938]
We've been using Shippable for a few years now; last night however, the Bitbucket projects are not showing in the admin panel (my personal Github still is though). I tried logging out and in, but they still are not showing. Any idea what might be causing it?

Thank you! This is urgent as it is affecting our ability to deploy to our production environments.

Much appreciated;

Paul Hughes
![Selection_025](https://user-images.githubusercontent.com/1262199/64259567-487e6e00-cef7-11e9-80b4-0f6892f4c5a0.png)

**Comment by PaulHughes01** [comment]
Account ID is 574756c58b33920c00fc9f4a

**Comment by gabrielpascua** [comment]
Our team had the same issue today and this addressed this for us. Hope it helps yours

log out > log in > profile sync

**Comment by PaulHughes01** [comment]
Thank you so much! Looks like that did the trick. :-)
