### ISSUE TITLE
Can no longer see spogs, builds, subscription, etc

### ISSUE THREAD

**Issue by Kirtap** [Shippable/support#4940]
My team is encountering issue with Shippable this AM. Our subscription is no longer listed and we cannot see builds or anything anymore. We need this fixed ASAP please.

Errors:

![image](https://user-images.githubusercontent.com/4245982/64263558-cf364980-cefd-11e9-9e25-83f1ea328499.png)

Account under patrick.carriere@buildingsiot.com

**Comment by Kirtap** [comment]
So, logged out, then logged back in and did profile -> Sync. This seemed to have restored it (originally lost all the build status but it came back after a while)

**Comment by SparK-Cruz** [comment]
@Kirtap's solution did work for viewing stuff but not building...
I can't trigger builds, clickin the build button says "build triggered succesfully" but no build shows up. Account: roger(at)tecnofit.com.br

**Comment by a-murphy** [comment]
@SparK-Cruz Are you still missing those builds you triggered?  It looks like your project was triggered this morning, so I wonder if those were the ones that didn't show up.  If they're still missing, do you remember what you triggered and when?

**Comment by SparK-Cruz** [comment]
@a-murphy Now it looks ok... only thing weird now is we have 4 processing jobs but we only paid for 2 workers. Thanks anyways.

EDIT: Nevermind, our jobs are cancelled but the dashboard shows them as running...

**Comment by SparK-Cruz** [comment]
![image](https://user-images.githubusercontent.com/1179000/64282647-47b3ff00-cf2c-11e9-977d-119fd4d6326b.png)
Things are... slow
