### ISSUE TITLE
Bitbucket permissions denied

### ISSUE THREAD

**Issue by jjwatson** [Shippable/support#4941]
Our team found our respective job screens empty today, but were able to restore them by resynchronising our accounts. However since then we've had build errors on bitbucket checkout. I've tried resetting the key in shippable and updating it into bitbucket user settings -> ssh keys. We're subs/bitbucket/carepo

Error below:

"Identity added: /tmp/ssh/01_deploy (/tmp/ssh/01_deploy)
Cloning into '/root/src/bitbucket.org/carepo/diagnostic-learnosity'...
Warning: Permanently added the RSA host key for IP address '18.205.93.1' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository."

**Comment by a-murphy** [comment]
It sounds like you reset the subscription key.  The project keys are separate SSH keys added to each project to clone that repository.  Could you try the "reset all keys" button on the project settings page?  Documentation for the project settings page is available [here](http://docs.shippable.com/platform/management/project/settings/#project-settings).

**Comment by jjwatson** [comment]
Thank you so much that worked.
