### ISSUE TITLE
Would it be possible to add an API endpoint for encrypting strings?

### ISSUE THREAD

**Issue by DanieleGBX** [Shippable/support#4942]
As per title, would it be possible to add an API endpoint for encrypting strings? I couldn't find anything in the docs for it.

**Comment by a-murphy** [comment]
The API to encrypt secure environment variables is `POST https://api.shippable.com/subscriptions/{subscriptionId}/encrypt`, where `{subscriptionId}` is the `id` of the subscription in which you intend to use the encrypted variable.  The route expects a JSON object in the format `{'clearText':'my string to encrypt'}` for the body of the request and will return the encrypted string.
