### ISSUE TITLE
Additional jobs using shippable.*.yml files in non-master branch

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4943]
I just tried to add a custom `shippable.production.yml` file to a repository but not in the `master`  but in a `production` branch. The goal was to only have builds for that branch use multiple jobs for a deployment.

However, the additional file is not respected and only a single job is executed. (See build 4916 of project `58ab0bf60bfe57100058d7a6`)

Am I missing something or is this actually not possible? The docs slightly hint at this.

**Comment by rageshkrishna** [comment]
CI only supports `shippable.yml` (and `.shippable.yml` if you like to hide it).

What you're talking about is currently only possible on pipelines. A syncRepo can contain one more shippable*.yml files and we will process all of the resource and job definitions. CI doesn't do this.

**Comment by mbrodala** [comment]
Aw, that's too bad. Do you see a way to achieve what I had in mind?

**Comment by rageshkrishna** [comment]
If you need a matrix to run only in the `production` branch, your only option right now is to have a `shippable.yml` there that defines the matrix.

There is no way to "merge" multiple YMLs in CI today.

**Comment by mbrodala** [comment]
That's what I wanted to avoid to prevent merge conflicts in case changes on `shippable.yml` are merged into `production`. But I guess I don't have a choice ATM.

Could you add this as feature request?

**Comment by mbrodala** [comment]
We won't be using Shippable anymore.

But thanks so far!
