### ISSUE TITLE
Not able to login to shippable.com 

### ISSUE THREAD

**Issue by akshay-ship-it** [Shippable/support#4945]
### Description of your issue:

When I click Login button on shippable.com, i see following error message:
"
Error
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.
"

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
