### ISSUE TITLE
Login to Private Docker Registry fails after password change

### ISSUE THREAD

**Issue by sdlarsen** [Shippable/support#4946]
### Description of your issue:

After changing password on my private registry, the integration to it fails. Updating the password on the integration seems to do nothing.

- Link to the build failure
https://app.shippable.com/bitbucket/uberresearch/solr-loader/runs/77/1/console
The above is just one of MANY builds failing now...

**Comment by Bharath92** [comment]
Are you seeing any error while updating the password on the integration?

**Comment by sdlarsen** [comment]
No, no errors are shown. I saw that the Private Docker Registry integration was deprecated, so I've deleted it and created a new with the same name.
Same same: https://app.shippable.com/bitbucket/uberresearch/solr-loader/runs/79/1/console

**Comment by sdlarsen** [comment]
I see 'validation error' if I try to add any scoping to the integration. Not what the error is (very useless...)

**Comment by sdlarsen** [comment]
Interestingly, changing the type of integration from 'private docker registry' to 'docker registry' in my shippable.yaml file yields: Invalid integration private-docker-uberresearch-com specified for integration type: hub

**Comment by Bharath92** [comment]
Which is the integration you are using in the job? `private-docker-uberresearch-com` hasn't been updated recently. If you are using `private-docker-uberresearch-com` integration in your job, the password should be updated for that integration.

**Comment by sdlarsen** [comment]
private-docker-uberresearch-com was re-created today. Why do you think differently? Today 10:58 it says (but that time is not changed when updating password). So maybe updating passwords doesn't work.
Several development teams are now blocked due to this...

**Comment by sdlarsen** [comment]
I'm really keen to get this resolved. Entire teams are blocked by this!

**Comment by Bharath92** [comment]
> Why do you think differently?

From the subscription integrations page, `docker.uberresearch.com` seems to be the integration that was updated today. The above job seems to be using the integration `private-docker-uberresearch-com` which was last updated around a year ago.

So, could you update `private-docker-uberresearch-com` subscription integration's password and try whether running a job works?

**Comment by sdlarsen** [comment]
![image](https://user-images.githubusercontent.com/698809/64418453-54a33080-d09b-11e9-9572-d729bae62bd6.png)

We're not looking at the same page. Can you see the picture I've posted?

**Comment by sdlarsen** [comment]
And the Updated At column is not updated when changing the password (or the password is not changed)

**Comment by sdlarsen** [comment]
We _were_ in fact looking at different pages. I found the page you were looking at, and changing the password there helped. A tad confusing with several pages on the same subject? Anyway, I'm closing this here. Thank you for your assistance.
