### ISSUE TITLE
Not able to login to app.shippable.com

### ISSUE THREAD

**Issue by lwkamal** [Shippable/support#4947]
I am not able to login to app.shippable.com. The error message is: 

"
Error
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake "

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
