### ISSUE TITLE
Unable to log into shippable

### ISSUE THREAD

**Issue by MichaelWakahe** [Shippable/support#4950]
We have a Bitbucket account `gro-intelligence.com` with user `murage_`

He is unable to log in with the message: 
"Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

What could be the matter?

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
