### ISSUE TITLE
Slack Notification URL Not Updating

### ISSUE THREAD

**Issue by guitarislife87** [Shippable/support#4952]
Description
========
We've had several teams notice they're not getting Slack notifications for failures on their runSh jobs. We noticed the jobs getting an error message of
```
Failed to send slack message for objectId:5d76d0b6b67c730007f48cca with error:Error: Invalid URI "********"
```
I couldn't tell if that was simply an output mask or if it was actually trying to send astrisks. We've gone into our slack integration and updated the url, but we get the same error. We switched one job to a different integration, and the error message was sent to the appropriate channels.

The issues isn't blocking, but developers aren't getting build failures to know if they need to make corrections.

We had a [previous issue](https://github.com/Shippable/support/issues/4921) where we upgraded all of our integrations from personal to organizational. We seemed to notice the  issue with the slack integration start the next day. See [this job](https://app.shippable.com/github/supplypike/jobs/analytics-smoke-tests_analytics-ui_prod_analytics_smokeTests/dashboard) between 8/27 and 8/28 to see the change.

Goal
====
We'd like to be able to update the Slack URL without having to delete the current integration, deleting all it's associated resources, and resyncing all our projects.

Resources
=======
Previous issue involving integrations: https://github.com/Shippable/support/issues/4921
Our slack integration: https://app.shippable.com/subs/github/supplypike/integrations/7948/
Resource tying integration to job (that we also debugged by switching integrations): https://app.shippable.com/subs/github/supplypike/resources/ml_slackNotifications/versions
Job getting error that we swapped the integration on: https://app.shippable.com/github/supplypike/jobs/ml-bridge-integration-tests_ml-worker_stage_ml_integrationTests/builds/5d571996ed1bf400070214b3/console
Another Job with the same error but can see the error message starting to appear on 8/28: https://app.shippable.com/github/supplypike/jobs/analytics-smoke-tests_analytics-ui_prod_analytics_smokeTests/dashboard

**Comment by a-murphy** [comment]
Since your Slack integration was an older type of Slack integration and the new Slack integrations are very similar, I've updated the integration to the new Slack type.  Let us know if it helps.  If not, we'll continue investigating why you aren't getting your Slack messages.

**Comment by guitarislife87** [comment]
Unfortunately, there was no change.

So I reran https://app.shippable.com/github/supplypike/jobs/ml-bridge-integration-tests_ml-bridge_stage_ml_integrationTests/dashboard and still got the error.

I then removed the url in the integration, readded it, reran the job, and still got the error.

**Comment by Bekt** [comment]
@a-murphy any luck? A few of our teams are being affected.

**Comment by trriplejay** [comment]
Hi @Bekt

It looks like this is due to the permission level of the integration. could you edit the slack integration from the integrations page, and change the edit role from "admin" to "collaborator"? I think this will solve the problem. At the moment, the credentials being used to run the job don't seem to have the permission to read the URL.

**Comment by Bekt** [comment]
That seems to have worked, thanks! Any idea what changed?

**Comment by trriplejay** [comment]
I think this was due to the migration from account level to subscription level integrations. subscription integrations have a slightly different permissions model, and so this one started to get blocked from the jobs trying to use it.

**Comment by trriplejay** [comment]
let us know if you have any other questions!
