### ISSUE TITLE
3.3.1 required to at least look at .mvn/ if it exists

### ISSUE THREAD

**Issue by damianszczepanik** [Shippable/support#4953]
I'm facing problem with maven version which is older than expected and I could not find way how to force to use never version:

```
[INFO] Maven Version: 3.2.5
[INFO] JDK Version: 1.8.0_72 normalized as: 1.8.0-72
[INFO] OS Info: Arch: amd64 Family: unix Name: linux Version: 3.19.0-51-generic
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (display-info) @ build-history-manager ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
3.3.1 required to at least look at .mvn/ if it exists.
```
- https://app.shippable.com/github/damianszczepanik/build-history-manager-plugin/runs/37/1/console
- https://github.com/damianszczepanik/build-history-manager-plugin/blob/master/shippable.yml

**Comment by a-murphy** [comment]
The versions of Maven preinstalled vary depending on the build image version used to run the job.  So the easiest way to get a newer version of Maven is to [update the machine image in your subscription node pool](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) to update the default build image versions used in your subscription.  The latest, v7.2.4, images [have Maven 3.6.0](http://docs.shippable.com/platform/runtime/machine-image/ami-v724/#java).

**Comment by damianszczepanik** [comment]
Looks good, however I had 'stable' version so I thought it was the most recent and also I had to patch default configuration as there is still problem with cache https://github.com/damianszczepanik/build-history-manager-plugin/pull/13
