### ISSUE TITLE
Shippable account blocked

### ISSUE THREAD

**Issue by andrii-ostashevskyi** [Shippable/support#4956]
When I try to Log In wit my github account password, I have "account blocked" message.
![Screenshot from 2019-09-19 14-58-40](https://user-images.githubusercontent.com/55447887/65242215-1de30680-daee-11e9-989e-4a2c529016dc.png)

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by andrii-ostashevskyi** [comment]
Great, It works correctly, thanks.
Best Regards,
Andrew.
