### ISSUE TITLE
Deployment keys gone

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#4965]
Today I noticed that some of our Bitbucket projects (e.g. `5ce549f71f6d1300073be0da`) didn't have the Shippable deployment key anymore which lead to access errors in the `git_sync` CI build step.

How could this happen? I'm quite sure that none of us has explicitly removed the Shippable deployment key on Bitbucket.

**Comment by a-murphy** [comment]
If the keys were recently removed, the most likely reason would be if the account that added the keys lost access to the project.  Bitbucket won't notify us that the keys have been deleted as the result of a change in permissions for an account.  If they keys could have been missing for over two months, it could also be the result of an update at that time.  In either case, if you haven't already, clicking the reset all keys button on the project settings page should replace the webhook and deploy keys for the project.

**Comment by mbrodala** [comment]
Yes, I did the latter already to fix the projects which build just fine again.

However, there was no change on our side AFAIK ...
