### ISSUE TITLE
Deploy jobs on kubernetes 1.14 fails.

### ISSUE THREAD

**Issue by haraldnh** [Shippable/support#4967]
It is no longer possible to run managed deploy jobs when deploying to a cluster running kubernetes 1.14 (and later).  The job fails with:

`Generating namespace specification`
`W1022 12:47:21.210704     323 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger`
`error: error validating "/tmp/shippable/7ac29028-f033-443c-9b92-d7cc7f78d825/deploymentSpec-b6f1c815-2105-48be-84f4-e292a6c150e5.json": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false`
`Failed to apply namespace`
`Spec: kubectl failed and exited with error code 1`

See https://app.shippable.com/github/wattsight/jobs/last-scraper-standing-dev-deploy/builds/5daefa510a11690007756f8b/console for an example.

I suspect the problem is that the managed jobs run a way too old version of kubectl.

**Comment by haraldnh** [comment]
Checking the error message against the kubernetes code base, the 'factory_object_mapping.go' file was deleted from the master branch towards the end of may 2018.  So I guess the deploy jobs are running kubectl 1.9 or possibly 1.10.  This is so out of date that it's not even funny any more.

**Comment by haraldnh** [comment]
Can you please confirm that the shippable services are still alive and at least have the intention of being maintained?  I just tried to call you (10:15AM Seattle time, there should be people in the office) and ended up directly in what sounded like a private voicemail account.  Mails are not being answered, bugs reported here are not being followed up, and your chat system is not being answered (and lists messages as unread for days).

Do we have to accept that app.shippable.com is a dead man walking, and stop pouring money and effort into using your platform?  It used to be the best hosted CI/CD system, but it's been going rapidly downhill ever since JFrog entered the picture.

**Comment by haraldnh** [comment]
After 5 months this has now suddenly been fixed after somebody else reported it, see linked issue.  Nice to get things working again, but your support performance stinks.

I certainly cannot recommend Shippable any more, it used to be a great service.

**Comment by trriplejay** [comment]
Hi @haraldnh, I'm afraid I really dropped the ball on this one. After some initial discussion on how to fix the error, and what the risks were back when you first opened the ticket, I ended up losing track of this issue and moved on to other things.  When another customer brought it to our attention recently we were in a better position to take action.  Unfortunately this left you broken for several months, and for that, I'm sorry.  Despite this failure, this support issues page is still the best place to get help when you're having trouble.  I hope this hasn't completely soured you to Shippable.

**Comment by rune-bk** [comment]
Stepping in for @haraldnh

Thank you for finally answering and stepping up @trriplejay.

May I suggest you consider a workflow/github action/whatever that reminds you of dropped-ball issues such as this to avoid it happening again. We _really_ like the concept of shippable but not being reachable at all by e-mail, chat or phone in addition to a support ticket goes way beyond any single person dropping the ball. We tried for days if not weeks after this. After a while we simply gave up.

Beneath this blocker-issue lies a deeper and just as concerning issue. The machine images have not been visibly updated for a year! Not a single version bump. It's almost a miracle that they are still mostly working? We run a bunch of jobs using pure kubectl commands on a version that's now dangerously obsolete. How can you guarantee that similar issues will not happen again, and how can we be safely ensured that Shippable support is at all reachable if it does? 

We were truly impressed with Shippable as an invaluable tool. Roughly 6 months ago we lost that impression.
