### ISSUE TITLE
Access issue

### ISSUE THREAD

**Issue by mkrohnlw** [Shippable/support#4970]
### Description of your issue:
When I login, I get the error page:

**An error occured, please choose an action.**

**Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.**
![Screen Shot 2019-10-23 at 3 02 58 PM](https://user-images.githubusercontent.com/56850103/67437724-633f9b80-f5a6-11e9-8b8f-17b8f2963e59.png)

I have set up shippable as an Authorized OAuth App in github.

**Comment by trriplejay** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by mkrohnlw** [comment]
Thanks!
