### ISSUE TITLE
Shippable builds failing, 401 from dl.bintray.com during apt-get update in build_ci check

### ISSUE THREAD

**Issue by PaulHughes01** [Shippable/support#4972]
### Description of your issue:
Tried upgrading nodejs build package to 8.15.0 (provided by shippable, see http://docs.shippable.com/platform/runtime/machine-image/language-versions/#nodejs), also updated to latest environment version in our ubuntu node pool. However, during the build_ci step in the apt-get update step, this error happens during it

`E: Failed to fetch http://dl.bintray.com/apache/cassandra/dists/311x/main/binary-amd64/Packages  401  Unauthorized [IP: 52.33.219.150 80]`

There also are some missing PUBKEYs, which I assume are related. I think this is an issue on the shippable side, since we aren't using our own containers; it is the nodejs version Shippable is providing. It happened  on the node 6.10 and 6.16 versions (tried updating to that first) as well. Any idea what might be up? Planning to increase to nodejs version 10 shortly to see if it works.

- https://app.shippable.com/bitbucket/ypidev/vst-lambda/runs/903/1/console

**Comment by trriplejay** [comment]
seems like there's some issue with that Cassandra repository. Can you try adding this to the beginning of your script? `rm /etc/apt/sources.list.d/cassandra.sources.list`

**Comment by PaulHughes01** [comment]
Thank you! That seems to have done the trick.
