### ISSUE TITLE
Migrating github accounts, account marked as "blocked"

### ISSUE THREAD

**Issue by pcbng-peter** [Shippable/support#4975]
### Description of your issue:
Hi! I am transferring the ownership of my organization on Github to another account, and in the process I attempted to login to shippable using the new Github account. The account was immediately flagged as "blocked". Can you please look into it. Thanks!

Old github account: pbkhrv
New github account: pcbng-peter
Organization on github: "pcbng" (PCB:NG, Inc.)

Thank you!

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by pcbng-peter** [comment]
all set. thanks!!
