### ISSUE TITLE
Email notifications not being triggered

### ISSUE THREAD

**Issue by timtribers** [Shippable/support#4977]
Just recently my builds on the following project have stopped sending email notifications:

https://app.shippable.com/github/tbs-translations/YM-Product-Uploader/dashboard

The console logs always used to include a final step called either **email on_success** or **email on_failure**

![image](https://user-images.githubusercontent.com/7858892/68117110-60bd3a00-fef4-11e9-940c-3a6363843ab5.png)

But now that final step is ALWAYS omitted.  Nothing has changed in our Shippable config file (except I tweaked the notification settings AFTER this started happening to see if I could fix this).

Any ideas?

Thanks.

**Comment by trriplejay** [comment]
looks like our email service got backed up. it's been cleared out now. sorry for the inconvenience! Let me know if you're still seeing this issue.

**Comment by timtribers** [comment]
Many thanks @trriplejay

**Comment by timtribers** [comment]
Oh dear, the same thing on the same repo has started happening again @trriplejay .  Does it need another clear out of the email queue, or similar?

**Comment by a-murphy** [comment]
Yes, it was similar.  It should be all caught up now with emails sent promptly as steps complete.  We'll keep an eye on it for a while to be sure.

**Comment by timtribers** [comment]
Many thanks @a-murphy
