### ISSUE TITLE
Git fetching extra branch to compare fails

### ISSUE THREAD

**Issue by mei-li** [Shippable/support#4981]
### Description of your issue:
We are trying to compare the files that have changed in the PR branch with master branch, in order to conditionally run some tests.  We are getting an error:
```git fetch origin master
Warning: Permanently added the RSA host key for IP address '18.205.93.0' to the list of known hosts.
Unauthorized
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
### Link to build:
https://app.shippable.com/bitbucket/uberresearch/radar/runs/30374/1/console

### Scripts 

`shippable_check_integration_tests` looks like this:
 
```
#!/usr/bin/env bash
set -ex  # if any command fails the script stops and fails

git fetch origin master
BACKEND_DIFF=$(git diff --name-only master... | grep -v -E '.(js|sass)$' | tr "\n" " ")
if [[ $BACKEND_DIFF = "" ]]; then
  exit 0
fi

SKIP_COMBINE_COVERAGE=true SKIP_VCR=true ./integration_tests --logging
```

We have tried without the `git fetch` command and it also fails

**Comment by a-murphy** [comment]
It sounds like it's not using the project deploy key.  Could you try `ssh-agent bash -c 'ssh-add /tmp/ssh/01_deploy; git fetch'` (similar to the `git fetch` command in the git_sync section of the console output?

**Comment by mei-li** [comment]
thanks this worked
