### ISSUE TITLE
Shippable Account Blocked

### ISSUE THREAD

**Issue by josprimasihombing** [Shippable/support#4989]
My github account has been blocked since i first time logged into shippable using Github. It says 'account blocked'.

![image](https://user-images.githubusercontent.com/57883217/69024842-245f0300-09f7-11ea-9586-21a211f705ea.png)

my github login: josprimasihombing

**Comment by rageshkrishna** [comment]
Hi, your account has been unblocked. Please try logging in again and let me know if you're having trouble. Thanks!

**Comment by Djeber-Merah** [comment]
Hello, my account has been blocked since the first signing in, what should i do ? 
my github login : Djeber-Merah
