### ISSUE TITLE
Bitbucket account blocked

### ISSUE THREAD

**Issue by rickbrenn** [Shippable/support#4990]
I cannot authenticate with bitbucket. My account on bitbucket is rick.brenn@seamlessleads.com and the account being billed for the service is seamlesscontactstech. Subscription is seamlesscontacts

**Comment by a-murphy** [comment]
Do you a see a particular error?  I don't see any obvious reason why your account would not be able to log in.

**Comment by rickbrenn** [comment]
Well I just tried to login to take a screenshot of the error but it let me in. Thursday/Friday I was getting directed to the /error page and the message said something about my account being flagged as potentially malicious or something. Maybe it got reviewed and resolved since Friday. Sorry for the inconvenience.

**Comment by a-murphy** [comment]
That makes sense.  It sounds like your account was flagged and someone has since removed the flag.  I'll close this issue.  Let us know if there are still any problems.
