### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by gerK66** [Shippable/support#4992]
hi 
Was just setting up my account and when i linked in to my git hub i got the message

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.
dont think i violated ur security police so can u help me please

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by gerK66** [comment]
thank you
