### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by SeanKilker123** [Shippable/support#4995]
Hi,
I am just after creating a Github and tried linking it to shippable but it says the account is blocked. is there any easy way to unblock my account?

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by mohamedghozzi-lw** [comment]
I have the same issue. Could you please unblock my account mohamedghozzi-lw

**Comment by a-murphy** [comment]
@mohamedghozzi-lw I've unflagged your account as well.
