### ISSUE TITLE
Account has too many admin rights he is not expected to have

### ISSUE THREAD

**Issue by shekerev-progress** [Shippable/support#4998]
- I am a member of Telerik / Progress.
- I have write access to a number of repositories.
- Previously I had admin rights to a few repositories, but those admin rights have been removed for convenience / security reasons.
- In the Shippable UI, in github-telerik subscription, I see a number of admin related options that I expect a normal user like my account should not see - billing, edit and delete nodes and integrations

Is this the expected behavior of Shippable?

**Comment by a-murphy** [comment]
It looks like your account might not have been synchronized between changing the repository permissions and checking on Shippable.  Account permissions are synchronized periodically, but to immediately synchronize any changes, you can click the "sync" button on your account profile page in Shippable.  Could you confirm if you should still have admin permission on any of the repositories in the subscription?

**Comment by shekerev-progress** [comment]
Greetings

I clicked "sync". After the operation completed, the described behavior did not change.

Just to be sure, I logged out and in again. Still no change

**Comment by a-murphy** [comment]
Since you are not a subscription admin, you shouldn't be able to edit billing information.  However, you may still be able to view the billing page to see how may nodes the subscription is allowed without the edit options.

Access to the nodes pages is expected, and access to add or edit integrations if you have write access.

**Comment by shekerev-progress** [comment]
Understood. Closing the item as fixed
