### ISSUE TITLE
apt-get update error in build

### ISSUE THREAD

**Issue by Amir-4m** [Shippable/support#5001]
This is the error when it starts building:

```
Reading package lists...
Building dependency tree...
Reading state information...
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
The following additional packages will be installed:
  libjbig-dev libjpeg-dev libjpeg-turbo8 libjpeg-turbo8-dev liblzma-dev
  liblzma5 libtiff5 libtiffxx5
Suggested packages:
  liblzma-doc
The following NEW packages will be installed:
  libjbig-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblzma-dev
  libtiff5-dev libtiffxx5
The following packages will be upgraded:
  libjpeg-turbo8 liblzma5 libtiff5
3 upgraded, 7 newly installed, 0 to remove and 357 not upgraded.
Need to get 1,343 kB of archives.
After this operation, 3,322 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libjpeg-turbo8 amd64 1.4.2-0ubuntu3.3 [111 kB]
Err:2 http://ppa.launchpad.net/jonathonf/backports/ubuntu xenial/main amd64 liblzma5 amd64 5.2.2-1.3~16.04.york0
  404  Not Found
Err:3 http://ppa.launchpad.net/jonathonf/backports/ubuntu xenial/main amd64 liblzma-dev amd64 5.2.2-1.3~16.04.york0
  404  Not Found
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libjpeg-turbo8-dev amd64 1.4.2-0ubuntu3.3 [255 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial/main amd64 libjpeg8-dev amd64 8c-2ubuntu8 [1,552 B]
Get:6 http://archive.ubuntu.com/ubuntu xenial/main amd64 libjpeg-dev amd64 8c-2ubuntu8 [1,546 B]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libtiff5 amd64 4.0.6-1ubuntu0.7 [149 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/main amd64 libjbig-dev amd64 2.1-3.1 [24.8 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libtiffxx5 amd64 4.0.6-1ubuntu0.7 [5,598 B]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libtiff5-dev amd64 4.0.6-1ubuntu0.7 [269 kB]
Fetched 817 kB in 0s (980 kB/s)
E: Failed to fetch http://ppa.launchpad.net/jonathonf/backports/ubuntu/pool/main/x/xz-utils/liblzma5_5.2.2-1.3~16.04.york0_amd64.deb  404  Not Found

E: Failed to fetch http://ppa.launchpad.net/jonathonf/backports/ubuntu/pool/main/x/xz-utils/liblzma-dev_5.2.2-1.3~16.04.york0_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```
I tried passing it by running this command:
`sudo rm -rf /var/lib/apt/lists/*`

But I wonder is there any other way to fix this??

**Comment by a-murphy** [comment]
Since this error occurs when `apt-get` tries to reach a repository that no longer exists, [updating the subscription node pool](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) to a newer machine image, and so newer default build images, usually helps.

**Comment by ldavison** [comment]
Related: https://github.com/dry-dock/u16all/issues/185

**Comment by trriplejay** [comment]
I've patched the underlying build images to remove reference to this repository. Can you try running the job again?

**Comment by ldavison** [comment]
@trriplejay that resolved the issue with our builds, thank you for your prompt response!

**Comment by Amir-4m** [comment]
@trriplejay I tried again and error has been changed to:
```
E: Failed to fetch http://ppa.launchpad.net/jonathonf/backports/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
W: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by thewellnamed** [comment]
I'm seeing the 404 on the jonathonf PPA for `u16phpall` as well.

**Comment by trriplejay** [comment]
@Amiiwr1 @thewellnamed  can you [update your subscription node pool version](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) to use the latest machine image? (v7.2.4)  only the 7.2.4 images were patched.

**Comment by thewellnamed** [comment]
This is what is in shippable.yml right now:

```
  pre_ci_boot:
    image_name: drydock/u16phpall
    image_tag: v7.2.4
```

I assume that accomplishes the same thing?

**Comment by trriplejay** [comment]
@thewellnamed that works, however it means the image will have to be pulled. If you switch your node pool machine image to 7.2.4, then the image is already on the vm that spins up to run your build (it will still need to pull the patched layer, but that is small in comparison)

**Comment by trriplejay** [comment]
@thewellnamed if you are using 7.2.4 and still seeing the error, can you provide a link to your build?

**Comment by thewellnamed** [comment]
@trriplejay interesting about the node pool. We tried changing that also just now but are still seeing the same failure: https://app.shippable.com/github/CommuniCare-Technology/SS_Webservices/runs/5793/1/console

**Comment by trriplejay** [comment]
i noticed that your build seems to be following an older script pattern which does not pull the build image before running the build.  I have updated your projects to the newer workflow which pulls the image by default.  This should result in the patched image being pulled when you run your next build.  Can you try again?

**Comment by thewellnamed** [comment]
Thanks for taking a look! I'm still getting the same error: https://app.shippable.com/github/CommuniCare-Technology/SS_Webservices/runs/5797/1/console

Edit: I suspect, but am not sure, that whatever you changed may have broken builds on other repos we have, which seemed to be working before. Just based on timing of failures.

**Comment by archy-bold** [comment]
I've run into this error with a php7.1 machine image. Have they been updated too? Our application tests need to run in php 7.1 so updating to 7.2.4 isn't really an option.

**Comment by ldavison** [comment]
> i noticed that your build seems to be following an older script pattern which does not pull the build image before running the build.

Is there something different we should be doing? If so, can you please direct me to the documentation?

Yesterday I was poking around to see if there was a newer image, but http://docs.shippable.com/platform/runtime/machine-image/ami-overview/ shows 7.2.4 being the latest. Prior to that, new images were released monthly and the page says:

> Shippable officially supports the Machine Images for 12 months from their release date after which they're deprecated.

That gives us roughly 2 months on the latest image before it's no longer officially supported. If there is something else we should be using, I'd like to start using it sooner than later.

Thanks!

EDIT:

http://docs.shippable.com/ci/build-image/ also says:

> Machine images are released every month, and supported for 13 months after they are first released. By default, Machine image for your subscription is usually the latest available image when the first project was enabled for CI.

> You should periodically upgrade to the latest image in order to get access to newer versions of languages and services. We recommend upgrading at least once every 3-6 months to stay current, even if you do not specifically need anything in the new image.

**Comment by trriplejay** [comment]
@thewellnamed do you still have a pre_ci_boot section in your yml? if so, can you set the `pull: true` option? seems like these issues are all stemming from the patched image not being pulled onto the machine.
```
pre_ci_boot:
  image_name: drydock/u16phpall
  image_tag: v7.2.4
  pull: true
```

**Comment by trriplejay** [comment]
@archy-bold the v7.2.4 is referring to the shippable machine image version, not the php version.  You can see the contents of the u16phpall:v7.2.4 image on this page: http://docs.shippable.com/platform/runtime/machine-image/ami-v724/#php  (it contains php 7.1.26)

**Comment by thewellnamed** [comment]
@trriplejay this seems to work. Thanks!

```
pre_ci_boot:
  image_name: drydock/u16phpall
  image_tag: v7.2.4
  pull: true
```

**Comment by trriplejay** [comment]
@thewellnamed awesome. one more thing.... 

since you changed your node pool to the v7.2.4 machine image, you should be able to remove the 'pre_ci_boot' section entirely, because it will use 7.2.4 images by default.  When there is no pre_ci_boot section at all, the default behavior is to pull the image.  If there is a pre_ci_boot section, the `pull` is set to false by default, which is why you have to specifically set it to true to pull the patched image. 

So, if you want to simplify the yml a bit, you should be able to safely remove the pre_ci_boot section entirely. if you want to leave it as-is since it's working now, that's fine too :)

**Comment by archy-bold** [comment]
> @archy-bold the v7.2.4 is referring to the shippable machine image version, not the php version. You can see the contents of the u16phpall:v7.2.4 image on this page: http://docs.shippable.com/platform/runtime/machine-image/ami-v724/#php (it contains php 7.1.26)

@trriplejay I realised that and deleted my response. Thanks.

In my case, I was using an older machine image because I needed an older version of elasticsearch than the one provided in the newer images. Would I have to install elasticsearch manually to get around that?

**Comment by trriplejay** [comment]
@ldavison There's nothing different you should be doing. It just means that your projects were enabled previous to our release of shippable assembly lines functionality.  That actually turned out to not be the issue in this case anyway, it was purely an image pulling issue.  Regarding the release schedule... 7.2.4 is still the latest, and we'll continue to support that at this time.

**Comment by trriplejay** [comment]
@archy-bold another option is to add some commands to your script that will avoid this error. Can you link me to your failing job and I'll let you know how you can work around this?

**Comment by archy-bold** [comment]
@trriplejay I tried doing that myself but couldn't manage it, so that would be perfect.

Here's the first job that failed: https://app.shippable.com/github/archy-bold/wata-server/runs/479/1/console

**Comment by trriplejay** [comment]
@archy-bold since you're on an older image (5.10.4) there are a few extra keys to add. Adding these commands to the beginning of your script should resolve most of the errors and allow your build to continue
```
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23E7166788B63E1E 6A030B21BA07F4FB 4B8EC3BAABDC4346 EB3E94ADBE1229CF 960B2B2623A0BD5D 6B05F25D762E3157

rm /etc/apt/sources.list.d/jonathonf-ubuntu-backports-xenial.list
```

**Comment by archy-bold** [comment]
EDIT: I'd forgotten to switch the node pools back. The above worked for me.

~~Thanks @trriplejay, that got me most of the way. The `jonathonf-ubuntu-backports-xenial.list` file didn't exist for me, but a `jonathonf-ubuntu-backports-xenial.list.save` file did so the following did it:~~

**Comment by Amir-4m** [comment]
@trriplejay I updated node pool version and it worked.
thanks for your help
