### ISSUE TITLE
Deplying only Dockerrun.aws.json to ElasticBeanstalk

### ISSUE THREAD

**Issue by stevegcc** [Shippable/support#5005]
### Description of your issue:
I'm attempting to deploy to AWS ElasticBeanstalk. I've found and followed a number of Shippable demos on how to achieve this. I saw a number because it appears as if there are various methods to implementing this integration.  

The latest doc I have used is http://docs.shippable.com/ci/deploy-to-aws-beanstalk/

Most of the integration is successful. However, an entire .zip file is being uploaded as the Application Version to EB when really all I want is the Dockerrun.aws.json file to be sent.

Is there a way to have the Dockerrun.aws.json deployed as the version (since the Docker image is already built and available in ECR) and not the .zip file containing the Dockerfile?

Link to the latest build failure is https://app.shippable.com/bitbucket/codecave/health360.api/runs/73/1/console

No additional scripts called by the yml file.

**Comment by trriplejay** [comment]
can you try adding a [.ebignore file](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-configuration.html#eb-cli3-ebignore) to you project that looks like this?
```
*
!Dockerrun.aws.json
!.ebextensions/*
```
basically, if beanstalk sees the Dockerfile, it will try to do a docker build. This ignore file will ensure that only the Dockerrun.aws.json file and the ebextensions folder (if you use that) get uploaded, and it should automatically pick up on the Dockerrun file to pull the image and run the container.

**Comment by stevegcc** [comment]
That worked well. Thanks!  Not sure why I didn't think of that workaround before.
