### ISSUE TITLE
CI builds not triggered from Bitbucket

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#5007]
Currently CI builds are not triggered from Bitbucket.

I have enabled the history in the `Shippable_Webhooks` hook on Bitbucket and can see proper `repo:push` events which Shippable even responds to:

```json
{
  "message": "Queuing builds"
}
```

However, Shippable does not trigger a build.

I have also tried to reset the keys and hook in the Shippable project but that didn't make a difference.

See for example project `58ab0bf60bfe57100058d7a6`.

Any idea?

**Comment by mbrodala** [comment]
Apparently not all projects are affected, e.g. `59c3af5636154a070093df38` works fine with no apparent difference in the webhook request/response ...

**Comment by a-murphy** [comment]
For project `58ab0bf60bfe57100058d7a6`, it looks like webhooks have been switched off.  If you go to the project settings page, the toggle at the top can be used to switch webhooks back on so that it will trigger for future webhooks.

**Comment by mbrodala** [comment]
You are right, that setting indeed was switched off. I have no idea why though. :thinking: 

Would it be possible to let the API inform me about this in its response? Right now it says `Queuing builds` even if webhook processing is switched off ...
