### ISSUE TITLE
Build timing out too soon (at 1 hr not 2 hrs) on paid account

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#5009]
We're on a paid account which should be allowing builds of up to 2 hours.  Instead, our build is timing out at an hour whenever there is an issue causing it to take longer than normal.

- Link to the build failure
https://app.shippable.com/github/eccosolutions/ecco/runs/3807/summary/console

**Comment by a-murphy** [comment]
It looks like that particular project has a one hour timeout set in the project settings. You should be able to increase it to two hours on the project settings page.

**Comment by neale-bpm** [comment]
Ah, thank you.  I looked again and was able to change it.  Sorry to be a pain.

**Comment by nealeu** [comment]
Ah. I looked again and was able to change it.  Perhaps I was looking in the wrong place.

Many thanks.
