### ISSUE TITLE
Error Logging in to Shippable

### ISSUE THREAD

**Issue by MarinaShaevich** [Shippable/support#5012]
Hello,

I am trying to login with my Bitbucket account (marina.shaevich@biocatch.com) to shippable but getting the following error: "An error occured, please choose an action.
Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

Please advise.

Thank you,
Marina

**Comment by rageshkrishna** [comment]
Hi @MarinaShaevich. Our system that detects malicious accounts sometimes throws false positives. Sorry about the confusion. Your account has been unblocked and you should be able to log in without any trouble now.
