### ISSUE TITLE
boot_container takes 5 min. Is there way make it quicker ?

### ISSUE THREAD

**Issue by romani** [Shippable/support#5014]
### Description of your issue:

build log: https://app.shippable.com/github/checkstyle/checkstyle/runs/11668/1/console
config: https://github.com/checkstyle/checkstyle/blob/master/shippable.yml

"boot_container" takes 5 minutes. Is there way to make it quicker ?

**Comment by a-murphy** [comment]
It looks like you've specified the v5.9.4 version of that build image and have an older default version set in the node pool.  If you [change the machine image version](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image) in your subscription's node pool to one that matches the image version, the image will already be on the build node and won't need to be pulled.

**Comment by romani** [comment]
@a-murphy , we can now use latest version of image - https://hub.docker.com/r/drydock/u18java/tags
on ubuntu 18. 

But I ca not change ubuntu version:
![image](https://user-images.githubusercontent.com/812984/72026715-52abd280-3231-11ea-9a5d-e384a50d7c2b.png)

and https://hub.docker.com/r/drydock/u18java/tags no versioned tags.

Is it expected to still use Ubuntu 14.04 images ?

**Comment by a-murphy** [comment]
The Ubuntu 16.04 images should also be available on Ubuntu 14.04 machine images, and are the defaults in most cases.  The host will be 14.04.  We can also replace your node pool with an Ubuntu 16.04 node pool.

Ubuntu 18.04 images will not, however, be present on the Ubuntu 14.04 or Ubuntu 16.04 machine images, and Ubuntu 18.04 dynamic node pools are not currently available.  Available versions are documented [here](http://docs.shippable.com/platform/runtime/machine-image/language-versions/).

**Comment by romani** [comment]
> We can also replace your node pool with an Ubuntu 16.04 node pool.

please do.
To use latest possible for us version of ubuntu.

**Comment by a-murphy** [comment]
I've replaced your Ubuntu 14.04 node pool with Ubuntu 16.04.  It should be used by default in future jobs.

**Comment by romani** [comment]
thanks a lot !!
now container is booting quickly.
