### ISSUE TITLE
kikilacework cannot login

### ISSUE THREAD

**Issue by mkrohnlw** [Shippable/support#5017]
### Description of your issue:
kikilacework cannot login:  gets account blocked
<img width="1474" alt="Account blocked from Kiki's account" src="https://user-images.githubusercontent.com/56850103/72303084-f8d84d80-3620-11ea-8ec8-8b7bf408256f.png">

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged that account.
