### ISSUE TITLE
rSync job in inconsistent state: "There is already a resource named"

### ISSUE THREAD

**Issue by cpoll** [Shippable/support#5019]
### Description of your issue:
Build failing: https://app.shippable.com/github/formhero/jobs/managed-deployments_master_rSync/builds/5e209358304d4c000728103c/console

This build is failing with several `There is already a resource named [resource] in this subscription` errors. These resources are not in any other rsync git repos.

This is related to some mistakes on my part. We have two rsync repos,  'managed-deployments' and 'continous-deployments', and I was attempting to move some jobs/resources from one to another. I failed to follow the advice in this article: http://docs.shippable.com/platform/tutorial/workflow/migrate-jobs-resources/

Steps I took:

- Merged change to remove jobs/resources from 'managed-deployments' (rsync passed)
- Merged changes to add jobs/resources to 'continous-deployments' (rsync failed with "there is already a resource named [resource removed from managed-deployments]"
- Reverted change to add jobs/resources to 'continous-deployments' (rsync passed)
- Reverted change to remove jobs/resources from 'managed-deployments', thereby re-adding the resources to their original repo (rsync fails)

At this point, both repos are back to how they were before I made changes, but the resources described in 'managed-deployments' no longer seem to "belong" to that repo.

**Comment by trriplejay** [comment]
It looks like the resources are currently considered "deleted", but are associated with the "continuous-deployments" sync repo.

can you try following the steps to see if that will get things migrated?
1. pause your managed-deployments job (this is an important step for the migration workflow)
1. add those resources back to your continuous-deployments job
1. sync, and let me know what happens.

**Comment by cpoll** [comment]
@trriplejay The `continuous-deployment` rsync is passing (after following your steps).

I did play around with disabling `managed-deployments` before, but at the time `continuous-deployments` was still failing on retry. I'm guessing at some point I successfully moved the resources and didn't realize.


1. Is there a way to identify which repo a resource comes from?

2. I assume it's now safe to remove the resources from `managed-deployments` and re-enable the rsync?

**Comment by trriplejay** [comment]
yep, if continuous-deployments is passing with the resources added back then it should be safe to remove them from managed-deployments.

**Comment by trriplejay** [comment]
Identifying which repo a resource belongs to can be done via API but there's no convenient way to see it in the UI unfortunately.

**Comment by cpoll** [comment]
Thanks @trriplejay , everything is working now.

The tip about using the API is very helpful, I'll try that if I need to debug issues in the future.

Feel free to close this issue.
