### ISSUE TITLE
NPM install truncating private packages

### ISSUE THREAD

**Issue by sshen81** [Shippable/support#5020]
### Description of your issue: Attempting to run "npm ci" results in Integrity check failures.

We are using "npm ci" in our Dockerfile to install both public and private packages. .npmrc has been configured with a read token for our private packages.

Intermittently we will see integrity check failures due to mismatched SHA-512 calculation which terminates the "npm ci" installation. Looking at the build logs, we can see that for the exact same package and version, the SHA-512 is calculated differently and the size of the tarball downloaded is different. Why would downloading the same version result in different size of tarball? Although this does not happen every time, it is a frequent occurrence & prevents builds from proceeding reliably. We do not see this issue when performing npm package installation in any environments other than Shippable.

Build number 1:
[https://app.shippable.com/bitbucket/vigorsystemsinc/edisen-api/runs/361/1/console](https://app.shippable.com/bitbucket/vigorsystemsinc/edisen-api/runs/361/1/console)
`integrity checksum failed when using sha512: wanted sha512-r8RKU6GlCfU7dUdoZDILKlMNgZt7DonYKZyje0l/xx+In5/RF/8eyem03HjPZWwDheAEpcakGUoYscR9+b/LrA== but got sha512-QjTgOE85NWsN5IpcLH43XyqLU87kw2Rf8keso0Ik7k1EYJqO3XLIt8j3v63GoNyVcT5h1NxYXrD5FBOO0NaxAA==. (4502271 bytes)`

Build number 2 (building the same package and version):
[https://app.shippable.com/bitbucket/vigorsystemsinc/edisen-api/runs/362/1/console](https://app.shippable.com/bitbucket/vigorsystemsinc/edisen-api/runs/362/1/console)
`integrity checksum failed when using sha512: wanted sha512-r8RKU6GlCfU7dUdoZDILKlMNgZt7DonYKZyje0l/xx+In5/RF/8eyem03HjPZWwDheAEpcakGUoYscR9+b/LrA== but got sha512-FeTpB2WLVefk4K8EKQlFl9xoxMaED8CDom+L1+gcYk0cqXLowdJ+UgjEsD7yv9o6lt8hzXNHPsTwfNEqx179lg==. (5008376 bytes)`

**Comment by a-murphy** [comment]
Have you tried adding `npm cache verify` to your script?  It should at least help determine if it's a problem that exists earlier or only appears when the current error is printed.

I'll also mention that your builds are running on very old machine images, and updating to a newer version will often help with many problems.  Directions to change images in a node pool are [here](http://docs.shippable.com/platform/runtime/machine-image/ami-overview/#changing-the-node-pool-machine-image).

**Comment by sshen81** [comment]
Yes, we've tried both `npm cache verify` and cache `npm clear --force` but it has not resolved the issue. I've tested against a different machine image in a new node pool and it was successful, but hard to say whether that is a real fix as the issue is intermittent.
