### ISSUE TITLE
Cannot log in to https://app.shippable.com/ usng my github account

### ISSUE THREAD

**Issue by Cyrus-Cruz** [Shippable/support#5024]
To whom it may concern,

I'm trying to log in to https://app.shippable.com/ using my github account but I'm getting an error.
On the sign-in page, I click on the Github button but then I get the error page with the message:
**"Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."**

This is the first time I'm using/logging into Shippable so I'm not sure what policy I've violated.
Please let me know if you need any more information.

Thank you,

**Comment by trriplejay** [comment]
Hello, your account has been unblocked. Sorry for the inconvenience!

**Comment by Cyrus-Cruz** [comment]
Thank you.
