### ISSUE TITLE
How to repair CI integration

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#5028]
Hi,

we have removed the github webhook for the default CI integration - probably due to a human error. The best solution I found mentioned is to "reset" the project. This would however reset all the screts in all Github repositories, would it not? 

Is there any other way to recreate the default CI webhook for our `damejidlo/kubernetes` repository? 

Thanks

P.S.: Project Id: 5a5cc16da6b0030700c04bc9

**Comment by a-murphy** [comment]
Clicking the "reset" button on the project settings page will reset the project SSH key and the webhook, but encrypted variables are encrypted using the subscription key.  Resetting the project shouldn't cause any problems for encrypted variables in your shippable.yml, but resetting the subscription key on the subscription settings page would.

Assuming you just mean [this type of secure variables](http://docs.shippable.com/ci/env-vars/#secure-variables), I would suggest clicking the reset button on the project page.  The only truly different alternative at this time would be to add the webhook to GitHub manually, and the webhook URL contains basic authentication (that is only used for the webhook) that makes it inadvisable to post in a public forum.

**Comment by RadekDvorak** [comment]
Issue solved. Thanks a lot @a-murphy.
