### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by tasos-lacework** [Shippable/support#5029]
### Description of your issue:
I tried to login to Shippable (logged in with Github and gave authorization to the app), but I'm getting the following error page:

<img width="1792" alt="Screen Shot 2020-01-31 at 4 40 42 PM" src="https://user-images.githubusercontent.com/60270647/73583774-daf45080-4448-11ea-9a0e-1597535176ba.png">

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
