### ISSUE TITLE
Account profile page never finishes loading

### ISSUE THREAD

**Issue by vladimir-cheverdyuk-altium** [Shippable/support#5034]
I click on Account | Profile and page never loads. I asked my co-worker to check on another machine and he has the same problem. I did wait like 6 hours and problem still there.

Some pages shows red "braintreeAdapter getAddons failed"

**Comment by a-murphy** [comment]
Thank you for reporting this.  We'll look into it.

**Comment by maggiedeuitch** [comment]
Hello. Are there any updates on this? The Subscription Menu is missing from a coworker's account and we can't sync it as the Profile page does not load.

**Comment by a-murphy** [comment]
I don't have an estimate for when the profile page will be restored, but can trigger account synchronization if you don't mind sharing the "Account Id" at the bottom of the home dashboard.

**Comment by clarencepong** [comment]
Hi, please trigger account synchronization for this Account ID: 5e41c63794f27d0006e131de

Thanks!

**Comment by a-murphy** [comment]
I've synchronized that account.  Let me know if it's still missing the subscription you were trying to sync.

**Comment by maggiedeuitch** [comment]
Hi again, Clarence's subscription is now synced only to the public repos. How are the private ones enabled? There's this [documentation](http://docs.shippable.com/ci/enable-project/) but there isn't an account settings icon. Guessing it's outdated? If it's on the profile page, then we can't load it.

**Comment by a-murphy** [comment]
The button to enable private repositories is on the account settings page.  I've updated the account profile directly to change the requested scopes.  Logging out of Shippable and back in (with GitHub) should prompt to allow the new scopes.

**Comment by maggiedeuitch** [comment]
That didn't work. He still only sees the public repo.

**Comment by a-murphy** [comment]
Sorry, it looks like a triggered sync set the scopes back.  Could you try going to https://app.shippable.com/auth/github/58a7c5789433b00f00ab373a/private instead?  That should also enable private scopes in the same way that the currently inaccessible button on the account profile page would.

**Comment by maggiedeuitch** [comment]
Unfortunately, that didn't work either.

**Comment by a-murphy** [comment]
It looks like the scopes were updated and sync found quite a few more projects for that account.  Could you try refreshing the page to see if that helps?

Otherwise, it may be that the subscription isn't allowing OAuth access, which isn't usually the case if any projects in the subscription are visible to anyone.  That can be checked by going to https://github.com/settings/applications, clicking "prod-shippable," and checking if there is a green checkmark or a red x next to the organization.

**Comment by maggiedeuitch** [comment]
Looks like it's working now. Thank you.

**Comment by rageshkrishna** [comment]
The account profile page should be fully functional now. We had an issue with our payment provider integration that caused an unhandled error on this page. The problem with the integration has been resolved. Please let me know if you're still having trouble. Thanks!
