### ISSUE TITLE
Error in "Node Pools" page

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#5036]
I am currently unable to see/manage our node pool:

![image](https://user-images.githubusercontent.com/5037116/74415962-a28b4400-4e44-11ea-8497-6a3af3756843.png)

However, I am still able to directly open a node pool at `https://app.shippable.com/subs/bitbucket/<user>/nodePools/<id>/view`

Can you please have a look at this?

**Comment by a-murphy** [comment]
This is related to #5034.  We're looking into it and will report when we are able to correct it.  Were you trying to edit a node pool, or will accessing the existing node pools directly for now work?

**Comment by rageshkrishna** [comment]
@mbrodala We had an issue with our billing integration that caused this page to throw an error. The problem with the integration has been fixed and your pages should now load normally. Please let me know if you're still having trouble. Thanks!

**Comment by mbrodala** [comment]
Looks good now, thanks for the fix.
