### ISSUE TITLE
Failed to fetch https://downloads.apache.org/cassandra/debian/dists/36x/InRelease

### ISSUE THREAD

**Issue by KushagraChauhan** [Shippable/support#5038]
Debian Mirrors are not down, still I face this error

Hit:1 http://archive.canonical.com/ubuntu xenial InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease        
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease          
Reading package lists... Done                     
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://downloads.apache.org/cassandra/debian/dists/36x/InRelease  
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by KushagraChauhan** [comment]
The Temp. workaround in ticket #1272 does not work either.

**Comment by rageshkrishna** [comment]
@KushagraChauhan Can you link me to a build where you see this happening?
