### ISSUE TITLE
Broken deployment

### ISSUE THREAD

**Issue by RadekDvorak** [Shippable/support#5048]
### Description of your issue:
Managed kubernetes/GKE jobs have suddenly started failing. This is a **serious issue** as it is broken in production as well. 
```
W0325 11:39:10.527789   19340 factory_object_mapping.go:423] Failed to download OpenAPI (the server could not find the requested resource), falling back to swagger
error: error validating "/tmp/shippable/a55bed4d-b64f-4e08-a84b-238d06527dba/deploymentSpec-19bd1674-7797-4d20-952b-3572ea1921aa.json": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
Failed to apply namespaceSpec: kubectl failed and exited with error code 1
```

The strange thing is that runSh jobs run kubectl without problems. I tried to update to the latest AMI - it did not help. We have not changed anythoing in GKE lately. Unfortunately I have no idea how to debug managed jobs myself :frowning_face: 

See the [failed job](https://app.shippable.com/github/damejidlo/jobs/dj-staging-nginx-deploy/builds/5e7b42d8118d1c000729e642/console).

**Comment by rageshkrishna** [comment]
@RadekDvorak sorry about the delay. We're looking in to this now and will update this issue as we make progress.

**Comment by RadekDvorak** [comment]
Thanks @rageshkrishna.

**Comment by trriplejay** [comment]
@RadekDvorak we've patched our deploy service. could you try again?

**Comment by RadekDvorak** [comment]
@trriplejay I have tested it. Deploy jobs work again. Great work :clap: 
I see [a provision job](https://app.shippable.com/github/damejidlo/jobs/dj-staging-provision_sidecar/builds/5e7e9c6d1888b80006b62403/console) failing in the same manner. Could it benefit from the same fix?

Edit: I worked around that by excluding the provision job. For others reading this: do not delete the job or the k8s svc will be deleted.

**Comment by trriplejay** [comment]
@RadekDvorak the provision service has been patched as well. sorry for the inconvenience!

**Comment by rune-bk** [comment]
While I'm glad this is fixed, it would have been nice with a fast response... in October...
https://github.com/Shippable/support/issues/4967#issue-510851818

**Comment by rune-bk** [comment]
No comment on Shippable's non-existent support handling during the JFrog merger @trriplejay  ?
Or should I submit a pull request to your readme updating your triage response time to a more realistic expectancy?
https://github.com/Shippable/support/blob/master/README.md
