### ISSUE TITLE
SPOG broken

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#5050]
Currently I am unable to view the SPOG, the tab is just empty:

![image](https://user-images.githubusercontent.com/5037116/77745325-59213d80-701b-11ea-8aed-86b176cee1ee.png)

Also the following errors show up in the console:

```
grid-view: 0.658935546875ms
lib.min.js:17 RangeError: Maximum call stack size exceeded
    at Function.s.each.s.forEach (lib.min.js:1)
    at l (app.min.js:28)
    at app.min.js:28
    at Function.s.each.s.forEach (lib.min.js:1)
    at l (app.min.js:28)
    at app.min.js:28
    at Function.s.each.s.forEach (lib.min.js:1)
    at l (app.min.js:28)
    at app.min.js:28
    at Function.s.each.s.forEach (lib.min.js:1)
lib.min.js:17 TypeError: Cannot set property 'searchText' of undefined
    at l (app.min.js:18)
    at app.min.js:18
    at lib.min.js:17
    at f (lib.min.js:16)
    at lib.min.js:16
lib.min.js:17 TypeError: Cannot set property 'searchText' of undefined
    at l (https://app.shippable.com/app/app.min.js:18:9188)
    at https://app.shippable.com/app/app.min.js:18:12849
    at https://app.shippable.com/app/lib.min.js:17:31536
    at f (https://app.shippable.com/app/lib.min.js:16:5904)
    at https://app.shippable.com/app/lib.min.js:16:7351 Possibly unhandled rejection: {}
```

Our subscription ID is `54f05f3c5ab6cc13528f2751`, can you please have a look at this?

**Comment by rageshkrishna** [comment]
@mbrodala We'll look in to this. Did this start happening just now?

**Comment by mbrodala** [comment]
I cannot say for sure since I haven't looked into the SPOG for a while. It's just today that I try to set up an assembly line and noticed the error.

**Comment by mbrodala** [comment]
@rageshkrishna Where you already able to find something? It's not super urgent but having an overview of our assembly lines again would be useful.

**Comment by rageshkrishna** [comment]
@mbrodala Sorry, not yet. This appears to be something happening specifically on your SPOG. We'll take a deeper look very soon and get back to you.

**Comment by mbrodala** [comment]
FYI: I just switched back to the classic SPOG and that one works, all elements are shown properly.

However, a message which says _Circular dependency found in the pipeline_ pops up when loading the SPOG so maybe that's what breaks the modern SPOG:

![image](https://user-images.githubusercontent.com/5037116/78755157-016ac680-7979-11ea-9cb0-694764bd7e1e.png)

Unless you beat me to it I'll see if I can find that dependency.

**Comment by mbrodala** [comment]
Alright that was it. I deleted a really ancient assembly line attempt for project `58ab0bf60bfe57100058d7a6` and now the modern SPOG works just fine again. :-)
