### ISSUE TITLE
Build Timeouts

### ISSUE THREAD

**Issue by danielahedges** [Shippable/support#5052]
Our builds have been getting longer, gradually, as we developers have added new code. That's life.

We have now started to cross a threshold, though, and our builds are now starting to timeout after successfully building the container. It looks to me that the timeout is set at 30 minutes.

I wanted to extend the time. But the only timeout I could find is set at 120 minutes.

Can you tell me what is causing my build to timeout after 30 minutes?

Links:
- https://app.shippable.com/github/Elligo/eDirectSource/runs/11891/1/console
- https://app.shippable.com/github/Elligo/eDirectSource/runs/11890/1/console

(I know the build is taking more than 30 minutes, but I believe the timeout happens at 30 minutes and the container continues shutting down, generating output for one or two minutes more.)

**Comment by a-murphy** [comment]
Your thirty minute timeout was set at the subscription level.  This can be changed on the subscription settings page.  To get there, click on the subscription name in the breadcrumb at the top of the page to get to the subscription dashboard, then the three gears in the top right and the "settings" option in the dropdown.

**Comment by danielahedges** [comment]
Thank you! Found it.
