### ISSUE TITLE
License to run this job on node pool "shippable_shared_aarch64" not found. Ask a Shippable adminstrator to assign the appropriate license.

### ISSUE THREAD

**Issue by gounthar** [Shippable/support#5053]
### Description of your issue:
License to run this job on node pool "shippable_shared_aarch64" not found. Ask a Shippable adminstrator to assign the appropriate license.

- Link to the build failure: [https://app.shippable.com/github/MerryKombo/jitsi-meet/runs/1/1/console](https://app.shippable.com/github/MerryKombo/jitsi-meet/runs/1/1/console)

- Scripts called from the yml (optional)

Hi there,
I already have a few projects running on the shippable_shared_aarch64 pool, but I created a new organization on GitHub (public) and can't build my repo with the shippable_shared_aarch64 pool.
Can you please help?
Thanks.

**Comment by a-murphy** [comment]
That subscription should now have access to `shippable_shared_aarch64`.  Let us know if you still have a problem running that job.
