### ISSUE TITLE
Account Blocked on initial subscription

### ISSUE THREAD

**Issue by gregsmirnov-av** [Shippable/support#5057]
### Description of your issue:
New account, just connected with github and immediately got error.
User: gregsmirnov-av

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by gregsmirnov-av** [comment]
I have proper access now. Thank you.
