### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by ghost** [Shippable/support#5058]
I'm getting "account blocked" trying to configure a shippable project. This is my Github machine account to do CI/CD.

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by ghost** [comment]
My account got wedged and I tried to delete and recreated it now I see this.

An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

**Comment by a-murphy** [comment]
I've unflagged your account again.

**Comment by goemie** [comment]
I created a git account for a school assignment but also got blocked the moment I wanted to login on shippable.
Can someone unblock me please :)?

**Comment by a-murphy** [comment]
@goemie I've unflagged your account.  You should be able to log on now.
