### ISSUE TITLE
Accounts blocked

### ISSUE THREAD

**Issue by mbrodala** [Shippable/support#5059]
We currently have two internships here at our company and both get the "account blocked" view when trying to enter the Shippable app. Can you please unlock them? Our subscription ID is `54f05f3c5ab6cc13528f2751`.

**Comment by rageshkrishna** [comment]
@mbrodala Can you send us their GitHub usernames?

**Comment by mbrodala** [comment]
It's Bitbucket, the usernames are `Dayzu` and `mmorl`.

**Comment by rageshkrishna** [comment]
It's done. They should be able to log in now.

**Comment by mbrodala** [comment]
I can confirm, thanks!
