### ISSUE TITLE
Builds failing from unknown reason

### ISSUE THREAD

**Issue by maciejmika** [Shippable/support#5060]
My builds fail although ci part ends successfully. From log probable cause is this error:

_ERROR:script_runner2 - script_runner2:Command failed : ssh-agent bash -c 'ssh-add /tmp/ssh/00_sub;ssh-add /tmp/ssh/01_deploy; cd /root && /root/5770f2fc-6c12-46eb-ab59-1ed19ebbd050.sh'
Exception Script failure tag received_

Exemplary build : https://app.shippable.com/bitbucket/digitaltoucan/toucan-tests/runs/257/1/console

**Comment by a-murphy** [comment]
It looks like the `build_always` section has a command to copy a directory of screenshots, and that directory doesn't exist.  The error is in the `build_always` section of the logs.  If the variable is the wrong directory, I would suggest updating it, and if it sometimes exists and in other runs doesn't, adding an `|| true` after the `cp` command on the same line should allow it to continue when the directory can't be copied.

**Comment by maciejmika** [comment]
thank you, that worked.
