### ISSUE TITLE
Node stuck in waiting

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#5062]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

https://app.shippable.com/subs/bitbucket/mygento/nodes/5e8de15fac0a480007e692cb

**Comment by a-murphy** [comment]
We're investigating this and at this time believe it may be related to a Google Cloud outage (https://status.cloud.google.com/).

**Comment by a-murphy** [comment]
Everything appears to be back to normal at this time.  We are continuing to keep an eye on node provisioning.
