### ISSUE TITLE
Builds stuck after 'Provision Job Node' step

### ISSUE THREAD

**Issue by neil-buildingsiot** [Shippable/support#5064]
We are having builds get stuck at the 'Provision Job Node' step. The builds just seem to hang.

This started happening this morning and seems to be happening with all our builds.

Some examples:
https://app.shippable.com/bitbucket/csi3/onpointweb/runs/1707/1/console
https://app.shippable.com/bitbucket/csi3/accesscontrol/runs/1772/1/console
https://app.shippable.com/bitbucket/csi3/fedcommon/runs/152/1/console

**Comment by AdelUnito** [comment]
We're having the same issue

**Comment by a-murphy** [comment]
We're investigating this and at this time believe it may be related to a Google Cloud outage (https://status.cloud.google.com/).

**Comment by a-murphy** [comment]
Everything appears to be back to normal at this time.  We are continuing to keep an eye on node provisioning.

**Comment by neil-buildingsiot** [comment]
Builds working again. Thanks.
