### ISSUE TITLE
Can't log in with bitbucket

### ISSUE THREAD

**Issue by biscuit95** [Shippable/support#5074]
I can't log using my bitbucket account : 

_An error occured, please choose an action._
_Your account has been blocked as it was identified to be violating our security policy._
_Please contact support if you feel this is a mistake._

**Comment by a-murphy** [comment]
Could you please include the name of the account that is unable to log in?

**Comment by biscuit95** [comment]
qlaborde@beautylitic.com

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
