### ISSUE TITLE
Cannot start job with SSH access 

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#5077]
I want to debug a runSh jon, but it seems like it won't allow me to start a debug job. Is this expected?

https://app.shippable.com/bitbucket/swisnl/jobs/cvrm_drupalUpdate/builds/5eaabc9f34f9f30007a3b89e/console

**Comment by a-murphy** [comment]
Debug runs with SSH are not currently supported for runSh.  They are only available for runCI jobs.

**Comment by bbrala** [comment]
Thats unfortunate.
