### ISSUE TITLE
missing 'rerun tests' button (play icon)

### ISSUE THREAD

**Issue by bcoca** [Shippable/support#5078]
### Description of your issue:
I cannot rerun failed jobs anymore since the button that enabled that has disappeared, i can only see the 'refresh page' icon now.

https://app.shippable.com/github/ansible/ansible/runs/165443/summary/console

**Comment by a-murphy** [comment]
It looks like you should be able to trigger jobs, but a previous account synchronization may have been unable to determine that you had that permission.  Could you confirm that you are logged in to Shippable?  You should be able to see your avatar in the bottom left corner of the page.

**Comment by bcoca** [comment]
I was logged in  and could see my profile, i did resync scm 2 or 3 times and it seems that (or something else) finally fixed the issue, i can see the button again.
