### ISSUE TITLE
Getting weird timeout for some reason, but i dont understand why

### ISSUE THREAD

**Issue by bbrala** [Shippable/support#5079]
Tried quite a few things, but getting weird timeouts of certain builds. Any change you can see what is happening? 

Running
https://app.shippable.com/bitbucket/swisnl/jobs/cvrm_drupalUpdate/builds/5eab109334f9f30007a3e752/console

Older
https://app.shippable.com/bitbucket/swisnl/jobs/cvrm_drupalUpdate/builds/5eaae1c97c4be00007064fcb/console

**Comment by a-murphy** [comment]
The most common reason a script would time out in the same place is if it's waiting for input.  However, comparing with your last successful run, it looks like you are removing a Docker container at that time.  Any chance you could be accidentally removing, or trying to remove, the wrong container?

**Comment by bbrala** [comment]
Hmm, we always try to remove a named container for caching reasons but I'll double check the changes. Perhaps removing hangs and stays in that state because the node is cached?

**Comment by bbrala** [comment]
Not sure how exactly anymore, but the issue has been resolved.
