### ISSUE TITLE
All Build Steps pass but build is still failure

### ISSUE THREAD

**Issue by hhimanshu** [Shippable/support#508]
https://app.shippable.com/builds/540fce6762bb25260055f2c9

@manishas, @rageshkrishna , can you please tell me what's going on?

This was working before your update happened

Thanks

**Comment by humanly-clement** [comment]
I am having this issue where all steps pass but the status is still marked as failure. It's very frustrating ><

![screen shot 2018-03-14 at 12 14 13 am](https://user-images.githubusercontent.com/34407518/37338651-f136de62-271c-11e8-97e2-025ed2a44223.png)

**Comment by clemnz** [comment]
I am having this issue where all steps pass but the status is still marked as failure. It's very frustrating =(

![screen shot 2018-03-14 at 12 14 13 am](https://user-images.githubusercontent.com/15212801/37338782-59611d2c-271d-11e8-80bd-a3ee19b881b1.png)
