### ISSUE TITLE
getAccountCardById for paymentMethodToken: null returned error: Unable to find card 

### ISSUE THREAD

**Issue by katsusuke** [Shippable/support#5086]
### I can't change my payment method.

- I changed my GitHub Pro account (mk-system) to Organization account and Owner to katsusuke
- mk-system's Shippable account has been deleted.
- Then, I get the following error on the Billing page.

![Subscription_Billing___mk-system_-_Shippable_と__Users_katsusuke_git_github_com_mk-system_arp_app_models_monthly_accident_rb_-_Emacs_KatsusukeMacBookPro_local](https://user-images.githubusercontent.com/624736/81368463-c819a800-912a-11ea-8cec-75234191e4d2.png)

The URL of the page where the error occurs is as follows.
https://app.shippable.com/subs/github/mk-system/billingV2?isEditMode=true.

Thank you for your support.

**Comment by a-murphy** [comment]
We've removed the old reference that was causing the error from the subscription.  You should now be able to add a new card.  Please let us know if you still have any trouble.

**Comment by katsusuke** [comment]
We succeeded in changing the billing successfully.
Thank you for your quick support.
