### ISSUE TITLE
Can't Sync SSH Key from bitbucket

### ISSUE THREAD

**Issue by bmcclareifs** [Shippable/support#5094]
I'm trying to sync my SSH key from bitbucket but it won't seem to take the latest. Currently shippable shows 3 old keys (which were deleted from bitbucket). However the one NEW key in bitbucket won't populate when I use the Synchronize SCM button.
I can't ssh into a CI build machine because I've lost the 3 old keys.
Is there anything I can try?

**Comment by a-murphy** [comment]
Bitbucket will no longer allow SSH public keys to be listed using OAuth tokens (https://jira.atlassian.com/browse/BCLOUD-16975), so we can't get an updated list.  If you have a GitHub account linked on Shippable, you can try adding a key to your GitHub account.

**Comment by bmcclareifs** [comment]
Thankyou, i will give that a go.
