### ISSUE TITLE
Unable to login to Shippable

### ISSUE THREAD

**Issue by subhadeep-studymode** [Shippable/support#5097]
![Screenshot from 2020-05-28 18-44-00](https://user-images.githubusercontent.com/66105130/83232027-1231fe80-a1aa-11ea-8322-dd78795c17e1.png)

Have an active bitbucket login, but using that unable to login to shippable

**Comment by rageshkrishna** [comment]
@subhadeep-studymode Please tell me your bitbucket login so I can unblock your account. Thanks.

**Comment by rageshkrishna** [comment]
@subhadeep-studymode I think I found it. Please try logging in again!

**Comment by subhadeep-studymode** [comment]
Hi,
Bitbucket login is subhadeep@studymode.com


Thanks,
Subhadeep

**Comment by subhadeep-studymode** [comment]
Hi Ragesh,

Thanks a lot. I am able to login now.

Regards,
Subhadeep
