### ISSUE TITLE
Unable to login to Shippable with bitbucket

### ISSUE THREAD

**Issue by barryaschultz** [Shippable/support#5098]
I have an active bitbucket login, but using that unable to login to shippable.

My bitbucket login is : schultz.b@cambridgeenglish.org

![shippable-login](https://user-images.githubusercontent.com/9305340/83243884-764ac780-a196-11ea-8712-43b3ef9095d6.PNG)

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by barryaschultz** [comment]
I am now able to log in.

Thanks for your help.
