### ISSUE TITLE
Got "account blocked" when login Shippable via GitHub

### ISSUE THREAD

**Issue by johnholw** [Shippable/support#5100]
I tried to login to Shippable via my GitHub account ("johnholw") but got "account blocked" error.  Would you please check and let me know the status?

Thanks!
John

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by johnholw** [comment]
Thank you very much! I can get in now.
