### ISSUE TITLE
No more shippable_shared_aarch64 nodes?

### ISSUE THREAD

**Issue by kinke** [Shippable/support#5105]
Our CI builds have been skipped since at least June 11th (`No active nodes found in shared node pool "shippable_shared_aarch64" to run this job.`). I haven't found any related news/status updates, so is the AArch64 integration via Packet dead or just temporarily down?

**Comment by trriplejay** [comment]
Hello, thanks for pointing that out. We've added some fresh nodes. Let us know if you have any issues.

**Comment by kinke** [comment]
Working again, much appreciated. Cheers!

**Comment by kinke** [comment]
Happening again: https://app.shippable.com/github/ldc-developers/ldc/runs/3043/1/console

**Comment by trriplejay** [comment]
should be back again, let me know if you have any trouble.

**Comment by kinke** [comment]
Excellent, thanks!

**Comment by kinke** [comment]
Can I bother you again before shutting down in May? (https://app.shippable.com/github/ldc-developers/ldc/runs/3151/1/console)

**Comment by a-murphy** [comment]
The shared AArch64 node pool should be available again.  Sorry for the inconvenience.

**Comment by kinke** [comment]
It is, thanks!
