### ISSUE TITLE
I got the account has been blocked issue when trying to login to shippable using github account

### ISSUE THREAD

**Issue by linhuang-lw** [Shippable/support#5118]
### Description of your issue:

Hi,

I got the following error when I am trying to login shippable.com using my github account. Can you point me what the problem might be? 

The following is error:
=========
Error
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

thanks,

Lin

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by linhuang-lw** [comment]
login is working now. Thanks.

**Comment by rpvilao** [comment]
@a-murphy we are running into the same issue. Could you unlock the cvkua organization? the email is cvkprosvita@theworkademy.com. Thanks!

**Comment by a-murphy** [comment]
@rpvilao I've unblocked that account.
