### ISSUE TITLE
Error when signing in using bitbucket

### ISSUE THREAD

**Issue by Matth93** [Shippable/support#5119]
![Naamloos](https://user-images.githubusercontent.com/55991992/86934208-b8730b80-c13b-11ea-82cd-af513c9c4907.png)

It seems i've been flagged when trying to sign up for Shippable using Bitbucket. Is there any way you could help?

Thanks, 

Matthijs

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
