### ISSUE TITLE
Notification email not updating.

### ISSUE THREAD

**Issue by gkarapeev** [Shippable/support#5120]
I've changed the Notification Email in my account settings several times, but I keep receiving them in my personal inbox. I've waited for about 2 weeks for the changes to apply without any luck.

**Comment by a-murphy** [comment]
Build notifications don't use the email in account settings; that's used for non-build emails.  For CI build email configuration, see http://docs.shippable.com/ci/email-notifications/.  By default, emails will be sent to the last author and last committer using the addresses in the commit from the source provider.

**Comment by gkarapeev** [comment]
Thank you!
