### ISSUE TITLE
I am blocked when log into shippable using the git account

### ISSUE THREAD

**Issue by ychau-lw** [Shippable/support#5122]
### Description of your issue:
Hi,

When I tried to view the build info on shippable, https://app.shippable.com/github/lacework/rainbow/runs/16770/summary/console. I got the 404 page. Please help me fix it.

Thanks,
Ying

**Comment by a-murphy** [comment]
If you have not enabled private repositories, you'll need to do so in order to see private projects.  To enable private GitHub repositories, go to your account profile page by clicking "profile" on the left sidebar and then click the "private" checkbox next to GitHub in the identities panel.

**Comment by ychau-lw** [comment]
I have enabled the private repositories. But the result doesn't change. I still can not view the page.

**Comment by a-murphy** [comment]
Could you try clicking the "sync" button on the account profile page?  Synchronization should have been triggered automatically, but may not have been.  And confirm that you have at least read access to the repository on GitHub?

**Comment by ychau-lw** [comment]
"sync" button works. I can view the it. Thank you.
