### ISSUE TITLE
build Duplicates inside one build

### ISSUE THREAD

**Issue by luckyraul** [Shippable/support#5130]
### Description of your issue:
NOTE: If you are experiencing a build failure, please include:
- Link to the build failure
- Scripts called from the yml (optional)

Duplicate lines leads to 2 parallel deploy, one of them is kicked off by lock file, and build fails

run id 5f2449228b374200070e449d

![Скриншот 2020-07-31 19 44 39](https://user-images.githubusercontent.com/7735520/89057537-7cac1a00-d366-11ea-98d3-c5220aad999d.png)

**Comment by a-murphy** [comment]
Thank you for reporting this.  I've identified the copy of the service responsible for starting the job twice and this should no longer occur.
