### ISSUE TITLE
Shippable account is blocked

### ISSUE THREAD

**Issue by madearyadi** [Shippable/support#5132]
Hi, my shippable account is blocked after logged in using github.

here is the screenshot:
![image](https://user-images.githubusercontent.com/69135543/89370344-b4221a00-d70a-11ea-8e92-0c98af701ec8.png)

github username: madearyadi

any idea?
Thanks

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by madearyadi** [comment]
Okay, thank you.
