### ISSUE TITLE
No projects on Shippable

### ISSUE THREAD

**Issue by sanjaybahrani** [Shippable/support#5134]
Hello,

I don't see the projects in shippable for my account. 

https://app.shippable.com/accounts/5ab14b5f76ee0c1700c28351/dashboard

I know bitbucket had issues couple of hours back which is resolved now. Can you please check?

Thanks
Sanjay

**Comment by a-murphy** [comment]
Have you tried clicking the "sync" button on the account profile page?  That will usually find any projects that weren't found on the previous automatic sync.

**Comment by sanjaybahrani** [comment]
Thanks.. it works

**Comment by sanjaybahrani** [comment]
Closing this one as it got resolved
