### ISSUE TITLE
syncRepo Resource not syncing

### ISSUE THREAD

**Issue by guitarislife87** [Shippable/support#5135]
### syncRepo Resource is not Syncing
We've updated a repo with our pipelines definitions multiple times in the past day, but the rsync step continues to run with an out dated version of the git repo. All the webhooks in github report a successful submission (says {"message":"Queuing builds"}), but nothing is happening in shippable.

syncRepo resource: https://app.shippable.com/github/supplypike/jobs/analytics-pipelines_master/dashboard/yml

**Comment by a-murphy** [comment]
Could you try re-sending the last webhook?  Sometimes webhooks will be processed trying to use an account that no longer has access when that account hasn't been synchronized since losing access, and given some timestamps we have, I think that may be what happened.  It doesn't usually occur three times, but I've synchronized all the accounts on Shippable that appeared to have access to that repository to rule it out.

**Comment by guitarislife87** [comment]
Unfortunately, that didn't seem to work. Looks like a coworker pushed another commit about 15 minutes ago, and it didn't trigger a sync. I also resent the webhook for the commit that we're really needing, and nothing seem to happen then either.  Also, it looks like all the old versions for analytics-pipelines_master are now missing.

**Comment by a-murphy** [comment]
I can't find anything in our logs for your repository.  Would you mind checking if the webhook URL ends with `projects/59a47a4a59c4990700d6587b/newBuild` or `resources/<number>/hook`?  Don't send the part of the webhook URL before the `@`; the username and password there are used to validate that webhooks are valid (that's all they're used for) and if those are wrong I should have found an error in the logs.

**Comment by a-murphy** [comment]
And I still see versions of that sync repository, so suggest re-synchronizing your account to see if that helps.

**Comment by guitarislife87** [comment]
Confirming that the webhook URL ends with `/projects/59a47a4a59c4990700d6587b/newBuild` (<- copied from GitHub).

I ran synchronize under both my profile and the organization profile, and the jobs list for analytics-pipelines_master is still empty.
![Screen Shot 2020-08-13 at 4 11 16 PM](https://user-images.githubusercontent.com/1772489/90187982-52078b80-dd80-11ea-9bfa-f0b450784a42.png)

**Comment by a-murphy** [comment]
The screenshot appears to be a job page with a resource name.  Although it is possible to get to that page by entering a URL in the address bar, it's not completely valid.  Could you navigate to the job or resource from the subscription dashboard to see if the jobs are shown for the rSync or the versions for the resource?

And could you double-check that one of the recently-sent webhooks is for a commit that contains changes to one of the YML files (shippable.jobs.yml, shippable.resources.yml, or shippable.yml) on the master branch?  Those are the ones that should update the syncRepo, and occasionally it does turn out that updates were made to another branch.

**Comment by guitarislife87** [comment]
🤦 on me. PBKAC error. I missed that the file that we added as missing shippable in the file extension. Changed the extension, and the job showed up.

Thank you for your time today!

**Comment by a-murphy** [comment]
Glad to hear it's working now!
