### ISSUE TITLE
User blocked trying to login

### ISSUE THREAD

**Issue by DeanHutchison** [Shippable/support#5140]
### Description of your issue:
One of our users is blocked from accessing our Shippable account. 

I emailed support@shippable.com with details but have received no response.

**Comment by a-murphy** [comment]
I've tried to guess which account it was and unblocked one that looked like it may be the one you meant.  I'll confirm with someone who has access to the support email account as soon as I can.

**Comment by a-murphy** [comment]
The account should be unblocked.  Let us know if you have any more trouble with it.

**Comment by DeanHutchison** [comment]
Thanks @a-murphy. I didn't want to put private details in this channel.
