### ISSUE TITLE
my Shippable account is blocked

### ISSUE THREAD

**Issue by ezzaardiala** [Shippable/support#5141]
Hello, my account is blocked after login using my github account

here is the screenshot:
![Screenshot from 2020-09-01 17-02-37](https://user-images.githubusercontent.com/70500650/91836500-ded39580-ec18-11ea-8ecb-ad63700d6c8f.png)

my github name is ezzaardiala
is there anything wrong?

thank you

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
