### ISSUE TITLE
Account is blocked after signing in with Bitbucket

### ISSUE THREAD

**Issue by WesleyKlop** [Shippable/support#5142]
### Description of your issue:

After trying to sign in to Shippable I get the error message that my account has been blocked with the following error:

![image](https://user-images.githubusercontent.com/12008100/91993154-526ac500-ed35-11ea-804b-9b5889acc3b5.png)

The account that is trying to sign in is a Bitbucket account with the email address wklop@swis.nl

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by WesleyKlop** [comment]
That fixed it, thank you! :)
