### ISSUE TITLE
account blocked on first login

### ISSUE THREAD

**Issue by AshnaWiar** [Shippable/support#5144]
### Issue description:
My account got blocked after signing in:

![afbeelding](https://user-images.githubusercontent.com/19426001/92364704-bacdf380-f0f3-11ea-91b1-df4b0c326081.png)

bitbucket username: **[AshnaWiar](https://bitbucket.org/AshnaWiar/)**

**Comment by rageshkrishna** [comment]
@AshnaWiar Your account has been unblocked. Please let me know if you're still having trouble. Thanks!

**Comment by AshnaWiar** [comment]
Thank you @rageshkrishna. 

It works
