### ISSUE TITLE
Can't Access shippable with bitbucket account

### ISSUE THREAD

**Issue by CameronShum** [Shippable/support#5146]
![image](https://user-images.githubusercontent.com/48306422/92818548-aea89700-f37c-11ea-837f-b7f9efeaf3f9.png)

I get this error when trying to log in with my bitbucket account: cameron.shum@raventelemetry.com

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by CameronShum** [comment]
Great it works now
