### ISSUE TITLE
No link to download test artifacts

### ISSUE THREAD

**Issue by plessbd** [Shippable/support#5147]
### Description of your issue:
I am unable to see a link for test artifact download.  The UI looks different than what is in the documentation

Documentation:
http://blog.shippable.com/setting-up-continuous-integration-test-result-visualization

![image](https://user-images.githubusercontent.com/683012/92941615-a012bc00-f41e-11ea-9a8f-fbc4a6acacba.png)

What I see:

![image](https://user-images.githubusercontent.com/683012/92941581-91c4a000-f41e-11ea-8b3b-f21e25c32def.png)

link to my builds https://app.shippable.com/github/ubccr/xdmod/runs/6083/1/tests

Is there just some setting I am missing somewhere?  Is the documentation not up to date?

Thanks

**Comment by a-murphy** [comment]
Although it's probably not exactly what you're looking for, there is an API route that will return the contents of the test report files: http://docs.shippable.com/platform/api/api-overview/#!/Jobs/get_jobs_jobId_jobTestReports

The dropdown from the older blog was replaced by the "download" section under the environment variables where the consoles may be downloaded.

**Comment by plessbd** [comment]
I am fine with using an API.  Thank you.
