### ISSUE TITLE
Blocked account

### ISSUE THREAD

**Issue by odiliacermati** [Shippable/support#5149]
### Description of your issue:
Hi there! I recently tried to sign in using my github account, and it immediately said that my account is blocked.
Can anyone help me resolve this?

Thank you!

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by odiliacermati** [comment]
Cool, I'm in now. thank you!
