### ISSUE TITLE
Error while accessing a build on a public repo

### ISSUE THREAD

**Issue by stof** [Shippable/support#515]
I just tried to access one of the build for https://github.com/symfony/symfony (using the link set in the Pr status). However, I got a message

```
 Error

You don't have sufficient permissions to perform this operation
```

this looks weird to me. The only thing I tried to do is seeing the build output (which should probably be fully public for public github repos, it should maybe not even require being logged in, like Travis does). Thus, I'm a collaborator on the github repo.

**Comment by manishas** [comment]
This is now available.... anyone can view public projects on Shippable!
