### ISSUE TITLE
Account blocked — Identified violating security policy

### ISSUE THREAD

**Issue by eoin-coulter** [Shippable/support#5153]
Description of your issue:
See image below:
image
![image](https://user-images.githubusercontent.com/72228956/94991858-e1117280-057d-11eb-9f4a-bcbb2c5a5476.png)

Transcript:
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

Comments:
I do feel like this was a mistake. 

Thank you in advance!

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
