### ISSUE TITLE
Wrong card number on invoice

### ISSUE THREAD

**Issue by Kivol** [Shippable/support#5154]
### Description of your issue:
About a week ago I changed my credit card for shippable because the old card is expired, and the transaction was successful.
But on the invoice it still shows the old credit card number, and it might raise some accounting issue of a company.

The transaction is run under 'Knowre-Dev' organization of Github.
The transaction ID: a4dg859f

**Comment by a-murphy** [comment]
Is it possible that the transaction was before you updated the card number?  Some banks will continue to process recurring charges when the old number is the same account.

The number shown on the invoice/receipt is the one our payment processor provided us in the transaction metadata and we have no direct control over it.  Future transactions should have the new number.
