### ISSUE TITLE
Account Blocked whrn linking with Bitbucket Account

### ISSUE THREAD

**Issue by Gabbou52** [Shippable/support#5157]
Hi,

Granting access to my bitbucket account I got this error:

Transcript:
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

My username: gabriel.blais-bourget@akinox.com

Thank you in advance!

**Comment by a-murphy** [comment]
I've unblocked your account.  Let us know if you still have any trouble linking your accounts.

**Comment by Gabbou52** [comment]
purrfect
