### ISSUE TITLE
Build Issue, [RuntimeException] The PEAR repository has been removed from Composer 2.0  

### ISSUE THREAD

**Issue by irfan116** [Shippable/support#5159]
### Description of your issue:
Whenever
![pear](https://user-images.githubusercontent.com/19527604/97104883-fa1ec680-16d8-11eb-9d6d-9dbaf70d2fa2.JPG)
 i run shippable it shows the following error message:
 [RuntimeException] The PEAR repository has been removed from Composer 2.0  :

- https://app.shippable.com/github/1eq/1EQ/runs/10633/1/console

**Comment by a-murphy** [comment]
Composer 2.0 removed support for Pear; they have an upgrade guide: https://getcomposer.org/upgrade/UPGRADE-2.0.md listing the potentially-breaking changes.

**Comment by irfan116** [comment]
@a-murphy : yes thanks
