### ISSUE TITLE
My Account Is Blocked With Logging In Via Github - Identified Violating Security Policy

### ISSUE THREAD

**Issue by phillipleech** [Shippable/support#5161]
### Description of your issue:
See image below
![image](https://user-images.githubusercontent.com/72160515/97332024-feb5bd00-1847-11eb-92eb-5afd681be92c.png)

An error occurred, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.

I tried contacting support but nobody responded and it has been a week.
Email is phillip.leech@hpe.com

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by phillipleech** [comment]
Thanks!  I can log in now.
