### ISSUE TITLE
Account blocked error when login with bitbucket account

### ISSUE THREAD

**Issue by sperez-belikesoftware** [Shippable/support#5162]
Hi,

I was trying to log in for the first time with a bitbucket account and I get this message:
```
An error occured, please choose an action.

Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake.
```
user: sperez@belikesoftware.com

What is the procedure to unlock the account?

Thanks in advance

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.
