### ISSUE TITLE
Immediately no builds avail on downgrade to free despite having paid to end of period

### ISSUE THREAD

**Issue by nealeu** [Shippable/support#5166]
Hi,
I've just downgraded our builds to free (Sorry, but that's your i.e. JFrog's fault - we're having to supplement our use of Shippable with another build system due to you not having released any support for recent Java versions!).

However, we've paid you for a full month, and under the free plan we should still have a limited number of builds per month and/or the rest of our month's builds we've paid for.

Can you please reset the builds on eccosolutions.

Cheers,
Neale

**Comment by a-murphy** [comment]
The allowed private builds per month on the free plan resets on the first of the calendar month, UTC, with the number available displayed updating with the first build triggered in that month.  It appears that now that a build has been triggered, the count displayed has updated.  Were there other builds that should have been created and were not?

**Comment by nealeu** [comment]
I can see that if I'm on the free plan already, then that is valid information.

The point I made was that we got zero free builds for the month with our paid builds having counted against our free build allowance.
