### ISSUE TITLE
New account blocked as flagged by security policy

### ISSUE THREAD

**Issue by ghost** [Shippable/support#5167]
### Description of your issue:

I just created a shippable account and when I logged in for the first time it said the account was blocked.

![error](https://user-images.githubusercontent.com/73751806/98305449-ca659d80-1fb9-11eb-9567-289fff4da972.png)

I think this is a false positive, could you please unblock the account?

Thanks

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by ghost** [comment]
Great, thanks.
