### ISSUE TITLE
Shippable build gets failed when executing sudo apt-get update command

### ISSUE THREAD

**Issue by irfan116** [Shippable/support#5170]
### Description of your issue:
**Getting the following during shippable build failed:**
`The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E91335D77E3E87CB
Ign:31 https://packagecloud.io/basho/riak/ubuntu xenial/main Sources
Get:48 https://packagecloud.io/github/git-lfs/ubuntu xenial/main amd64 Packages [9,119 B]
Ign:37 https://packagecloud.io/basho/riak/ubuntu xenial/main amd64 Packages
Ign:35 https://packagecloud.io/basho/riak/ubuntu xenial/main all Packages
Err:31 https://packagecloud.io/basho/riak/ubuntu xenial/main Sources
  402  Payment Required
Ign:37 https://packagecloud.io/basho/riak/ubuntu xenial/main amd64 Packages
Ign:35 https://packagecloud.io/basho/riak/ubuntu xenial/main all Packages
Fetched 7,922 kB in 3s (2,565 kB/s)
Reading package lists...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: KEYEXPIRED 1507181400  KEYEXPIRED 1546376218  KEYEXPIRED 1546372003  KEYEXPIRED 1580619281  KEYEXPIRED 1580607983  KEYEXPIRED 1580619281  KEYEXPIRED 1507181400  KEYEXPIRED 1546376218  KEYEXPIRED 1546372003  KEYEXPIRED 1580619281  KEYEXPIRED 1580607983  KEYEXPIRED 1507181400  KEYEXPIRED 1546376218  KEYEXPIRED 1546372003  KEYEXPIRED 1580619281  KEYEXPIRED 1580607983
W: The repository 'https://packagecloud.io/basho/riak/ubuntu xenial Release' does not have a Release file.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://downloads.apache.org/cassandra/debian 311x InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E91335D77E3E87CB
W: Failed to fetch http://www.apache.org/dist/cassandra/debian/dists/311x/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E91335D77E3E87CB
W: Failed to fetch http://dl.yarnpkg.com/debian/dists/stable/InRelease  The following signatures were invalid: KEYEXPIRED 1507181400  KEYEXPIRED 1546376218  KEYEXPIRED 1546372003  KEYEXPIRED 1580619281  KEYEXPIRED 1580607983  KEYEXPIRED 1580619281  KEYEXPIRED 1507181400  KEYEXPIRED 1546376218  KEYEXPIRED 1546372003  KEYEXPIRED 1580619281  KEYEXPIRED 1580607983  KEYEXPIRED 1507181400  KEYEXPIRED 1546376218  KEYEXPIRED 1546372003  KEYEXPIRED 1580619281  KEYEXPIRED 1580607983
E: Failed to fetch https://packagecloud.io/basho/riak/ubuntu/dists/xenial/main/source/Sources  402  Payment Required
W: Some index files failed to download. They have been ignored, or old ones used instead.
`
NOTE: If you are experiencing a build failure, please include:

- https://app.shippable.com/github/1eq/1EQ/runs/10792/1/console

**My Yml configuration**

    - sudo update-alternatives --set php /usr/bin/php7.1
    - php7.1 -v
    - python ./build/notify.py --slack-url $SLACK_URL --message started
    - curl -sS https://getcomposer.org/installer | sudo php7.1 -- --install-dir=/usr/local/bin --filename=composer
    - php7.1 /usr/local/bin/composer self-update
    - cp app/config/config_template.php app/config/config.php
    - mkdir -p shippable/codecoverage
    - mkdir -p shippable/testresults
    #- apt-key list
    #- sudo apt-key adv --keyserver pool.sks-keyservers.net --refresh-keys
    - sudo apt-get update
    - sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-key E91335D77E3E87CB
    - sudo apt-get install python-software-properties
    - sudo apt-add-repository -y ppa:brightbox/ruby-ng
    - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add
    - sudo apt-get update

**Comment by wing328** [comment]
I'm seeing the same issue in https://app.shippable.com/github/OpenAPITools/openapi-generator/runs/23593/1/console

**Comment by RichardVanSchaikRaspidev** [comment]
We are too, looks like Shippable needs payment to their cloud provider.

Our error
E: Failed to fetch https://packagecloud.io/basho/riak/ubuntu/dists/xenial/main/source/Sources  402  Payment Required

**Comment by AATAccounts** [comment]
> I'm seeing the same issue in https://app.shippable.com/github/OpenAPITools/openapi-generator/runs/23593/1/console

Wing328 it looks like you are having the same issue as RichardVanSchaikRaspidev

**Comment by trriplejay** [comment]
When these images were created, riak  (which is one of the services we provide on our build images) was installed via this packagecloud host. It seems that they have switched hosts, or simply that packagecloud now requires a paid account to use them as an apt source, while before today they did not.

If you're not using riak then I'd recommend adding 
```
rm /etc/apt/sources.list.d/basho_riak.list
```
to your script before doing an apt-get update.

let me know how it goes!

**Comment by irfan116** [comment]
@trriplejay : Thakns,
 `rm /etc/apt/sources.list.d/basho_riak.list`  worked for me

**Comment by RichardVanSchaikRaspidev** [comment]
rm /etc/apt/sources.list.d/basho_riak.list worked for me too
