### ISSUE TITLE
Account is blocked

### ISSUE THREAD

**Issue by annied-uqam** [Shippable/support#5178]
### Description of your issue:
When trying to connect with the bitbucket account, the user is getting the error page saying that his account is blocked. 

Could you unlock it?

![image](https://user-images.githubusercontent.com/65986193/100145254-0deb5300-2e66-11eb-9518-43c913fea9cf.png)

NOTE: If you are experiencing a build failure, please include:

- Link to the build failure
- Scripts called from the yml (optional)

**Comment by a-murphy** [comment]
Would you mind sharing the account name or some other clue as to which account it is?  I haven't been able to identify the correct account with the information here.

**Comment by annied-uqam** [comment]
Sorry, I should 've shared them : 
email of the dev : 
benjamin.proulx-mathers@akinox.com

URL : https://app.shippable.com/subs/bitbucket/akinox/dashboard 

Thanks for the quick answer.

**Comment by a-murphy** [comment]
Thank you.  I've unblocked the account.
