### ISSUE TITLE
shippable php language node setup too slow

### ISSUE THREAD

**Issue by ritch-parker** [Shippable/support#5182]
### Description of your issue:
Added a new ci integration for repomode/wp-splat-multisite
the setup for the shippable yml is:

language: php

php:
  - "7.2.15"

Using node from pool dynamic__x86_64__Ubuntu_14_04__c4_xlarge

setup doing php compile -- is the a way to change this -- unacceptable time to setup php, our builds can not take this long (5 mins plus before even running build code).

https://app.shippable.com/bitbucket/repomode/wp-splat-multisite/runs/1/1/console
https://app.shippable.com/bitbucket/repomode/wp-splat-multisite/runs/2/1/console
https://app.shippable.com/bitbucket/repomode/wp-splat-multisite/runs/3/1/console

Thanks,

Ritch...

**Comment by ritch-parker** [comment]
All php language versions 
- 7.1.26
- 7.2.15
- 7.3.2

for image v7.2.4 seem to have the same behaviour... current setting is now "7.1.26"

**Comment by a-murphy** [comment]
Those versions in that image were installed as `7.1`, `7.2`, and `7.3`, so specifying `7.3` instead of `7.3.2` should be much faster (and it's still actually 7.3.2).

**Comment by ritch-parker** [comment]
Ok, thanks.   That looks like it's working.
