### ISSUE TITLE
In shippable run a bash script file as part of a job

### ISSUE THREAD

**Issue by tkumark** [Shippable/support#5186]
When using a runsh job I would like to run a myscript.sh file the script would be handeling few things related to preping the system before the actual deployment happens. I would rather have runsh job download the script from bitbucket report and execute the bash script. How can we accomplish this?

**Comment by a-murphy** [comment]
Assuming you don't want to clone the entire repository (in which case you could use a [gitRepo](http://docs.shippable.com/platform/workflow/resource/gitrepo/) input), I would suggest using `curl` or `wget` with the file's "raw" URL.  On Bitbucket, there's an "open raw" option in the dropdown at the top right corner when viewing the file.
