### ISSUE TITLE
Is it possible for gitrepo not to trigger for a commit 

### ISSUE THREAD

**Issue by tkumark** [Shippable/support#5187]
Is it possible for gitrepo not to trigger for a commit and execute the job only when manually trigged at which point the job pulls from git and does the execution. 

if not is it possible to add excempt from to gitRepo not to trigger if some specific files are updated and checked in right now you only seem to offer for shippable.resources.yml, shippable.jobs.yml or shippable.triggers.yml

**Comment by a-murphy** [comment]
Adding `switch:off` to the `IN` section as described in http://docs.shippable.com/platform/tutorial/workflow/crud-job/#turning-off-automatic-job-execution will prevent the gitRepo triggering the job.
