### ISSUE TITLE
Cannot Access Lacework Shippable

### ISSUE THREAD

**Issue by clly** [Shippable/support#5196]
### Description of your issue:
Able to login but I cannot see any Lacework builds or statuses. It appears that my account is not linked with Lacework but I'm currently in the Lacework GitHub Organization.

**Comment by a-murphy** [comment]
It looks like most of the projects in that subscription are private and you haven't enabled access to private repositories on GitHub.  Without access to private repositories, we can't determine if you have access to any projects for private repositories.

To enable private repositories:
* Click on "account profile" on the left sidebar in Shippable.
* Click the private checkbox next to GitHub.
* Allow Shippable access to private repositories.
* If sync doesn't automatically start immediately, click the "sync" button on the account profile page.

**Comment by clly** [comment]
That was the issue. Thank you
