### ISSUE TITLE
Account Blocked after enabling private repos

### ISSUE THREAD

**Issue by taejin-hwang** [Shippable/support#5197]
Hello, after connecting my Github account, enabling private repos, and syncing it looks like my account has been blocked.
Github Username: taejin-hwang

![Screen Shot 2021-01-28 at 3 18 55 PM](https://user-images.githubusercontent.com/77992606/106211528-d35fa880-617d-11eb-8d99-78359411caf3.png)

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by taejin-hwang** [comment]
Looks like it's working now, thanks!
