### ISSUE TITLE
Migration of opensource organization to JFrog Pipelines

### ISSUE THREAD

**Issue by romani** [Shippable/support#5202]
### Description of your issue:
How can I migrate opensource organization to JFrog Pipelines ? Is there free plans for opensource ?

https://jfrog.com/artifactory/start-free/#saas requires some cloud, shippable does not require any.
How such clouds resources will be used?

Our opensource organization - https://app.shippable.com/github/checkstyle/checkstyle/dashboard
org: https://github.com/checkstyle/

**Comment by trriplejay** [comment]
Hi @romani. There is a free tier of the JFrog cloud platform. When you select a cloud from that page, you're selecting on which cloud you'd like JFrog to deploy to.

Let me know if you have any further questions.
