### ISSUE TITLE
Account Blocked

### ISSUE THREAD

**Issue by saikslacework** [Shippable/support#5210]
Need help logging in
Tried logging into app.shippable.com with GitHub as an identity provider and got an error.

"Your account has been blocked as it was identified to be violating our security policy.
Please contact support if you feel this is a mistake."

Thank you

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by saikslacework** [comment]
I am able to login now.
Thanks for the quick response!
