### ISSUE TITLE
Account locked (Bitbucket provider)

### ISSUE THREAD

**Issue by brankeye** [Shippable/support#5215]
Hi, I'm trying to authenticate via Bitbucket provider but my account was locked.

Name: Brandon Keyes
Bitbucket username: brandonkeyes
Email: brandon.keyes@raventelemetry.com

Can my account be unlocked, please?

**Comment by a-murphy** [comment]
Our algorithm automatically flags potentially malicious accounts but it does give some false positives. Sorry about that... I have unflagged your account so you should be able to sign in.

**Comment by brankeye** [comment]
@a-murphy thank you!
