### ISSUE TITLE
No valid Shippable yml found in GitHub repository.

### ISSUE THREAD

**Issue by misha** [Shippable/support#522]
All our builds result in that message and do not proceed. Manually triggered builds work as expected. I have not changed our yml since before the update to 2.0.

~~Account 54107ff31fea8b1400a68825.~~

**Comment by gsvijayraajaa** [comment]
HI ,

     The git trigger in shippable was working fine last week, but then it doesn't auto trigger the CI for a commit being made since today. Kindly check the same. This is a private git repo. Please  note that the manual build is fine.

Shippable ID: 570deb07b7923b0c00db3dff

Regards,
Vijay Raajaa G S

**Comment by dlckl** [comment]
To add to the same, I am getting a response: {"message":"Queuing run"} from the web hook in github ,  though i have free minions to run the CI build.

**Comment by avinci** [comment]
there was an update made yesterday that broke this. I have rolled back and it should be back to normal.
let me know if you are still facing the issue

**Comment by gsvijayraajaa** [comment]
Thanks it is working fine now.
