### ISSUE TITLE
GitHub repository not visible after accepting invitation

### ISSUE THREAD

**Issue by Radhakishore2001** [Shippable/support#5224]
GitHub repository not visible in my repository tab after accepting invitation from an organisation.
Earlier the repository was visible but now not visible although I am able to access it

**Comment by a-murphy** [comment]
Is this an issue related to Shippable, or were you looking for [GitHub support](https://support.github.com/)?

**Comment by Radhakishore2001** [comment]
Looking for GitHub support

**Comment by Radhakishore2001** [comment]
Done
