### ISSUE TITLE
Unable to download  lib32gcc-s1  lib32stdc++6  lib32z1 packages on 20.04

### ISSUE THREAD

**Issue by kelachim** [Shippable/support#5226]
E: Unable to locate package lib32gcc-s1
E: Unable to locate package lib32stdc++6
E: Unable to locate package lib32z1

This is my sources.list:

deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse

deb http://archive.canonical.com/ubuntu focal partner
deb-src http://archive.canonical.com/ubuntu focal partner

running sudo apt-get update before trying to install those packages didnt help
(im trying to install these packages on i386 architecture)

Im really miserable at this moment, can someone please provide a way to get these packages.
Im new to ubuntu and i might miss something so im here.

**Comment by a-murphy** [comment]
This isn't really the best forum for your question.  The purpose of this repository is for questions relating to Shippable CI/CD, which was acquired by JFrog (https://jfrog.com/blog/weve-acquired-shippable-to-complete-devops-pipeline-automation-from-code-to-production/).

However, have you checked the output of your `sudo apt-get update` to check if the updated lists were fetched or if there were any errors there?  If you really just need a way to download the packages, it is always possible to download them from packages.ubuntu.com, for example: https://packages.ubuntu.com/focal/lib32stdc++6.
