### ISSUE TITLE
DJango LiveServerTestCase Selenium tests produce error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by davidthewatson** [Shippable/support#524]
The build here is generating the same error on all selenium tests. This was working prior to v2, but I can't get to the history right now to point out where/when.

https://app.shippable.com/builds/54108bee1fea8b1400a68c1e

    python:
        - "2.7"

    language: python

    before_script:
      - mkdir -p shippable/codecoverage shippable/testresults
      - mysql -e 'create database hae;'
      - "export DISPLAY=:99.0"
      - "/etc/init.d/xvfb start"

    install: "pip install -r dependencies.conf"

    env:
      - DJANGO_VERSION=1.6

    script:
      - "export DISPLAY=:99.0"
      - ./website/manage.py test --with-xunit --xunit-file=shippable/testresults/nosetests.xml
      - ./website/manage.py test --with-coverage --cover-xml --cover-xml-file=shippable/codecoverage/coverage.xml --cover-package=website --cover-branches
      - pep8 --ignore=E501 website --exclude=migrations
      #- pylint website
      #- pyflakes website

    notifications:
      email:
        - david.watson@hireanesquire.com
        - andy.somerville@hireanesquire.com
        - dan@hireanesquire.com
        - ariana.farshchi@hireanesquire.com

    services:
      - selenium

    after_script:
     - "/etc/init.d/xvfb stop"

**Comment by manishas** [comment]
Closing due to age of the issue. Please feel free to re-open if this is still happening and we will be happy to take another look. 
Thanks!
