### ISSUE TITLE
Anybody should be able to view build info for public repositories.

### ISSUE THREAD

**Issue by bobeagan** [Shippable/support#53]
When clicking the build status details link on github for a public repo, it requires me to be logged in to view.  This should only be the case on private repos.  Otherwise, people that want to view the build status details of our public repos will have to create a shippable account first.

**Comment by lkiesow** [comment]
Any update on this? It would be really great if this would be possible.

**Comment by jordandukart** [comment]
+1

**Comment by nigelgbanks** [comment]
+1

**Comment by manishas** [comment]
We do allow anyone to view build info for public repos if they have a link (i.e. clicking on build badge/PR page 'Details' link/direct link in an email).

We haven't enabled making the entire build history available as a page so leaving this open.

**Comment by certik** [comment]
@manishas what I would like to see is for anyone to view the build info without having to log in, e.g. here is a link to a build: https://app.shippable.com/builds/55044f059b228b0d005bd5ca, and if you open it in an incognito window, you won't see any build info, but rather a login screen.

**Comment by lkiesow** [comment]
Exactly. As an open source project it would be great to tell people, here is a list of the last builds. Have a look at them if you want...

**Comment by qadan** [comment]
Agreed. That's what's keeping our organization from making the switch to Shippable; an open source community should be able to make pull requests to public repositories and then monitor the build status of those PRs without requiring each and every one of them to sign up/auth for the service. 'Anybody' includes anonymous users.

**Comment by geshan** [comment]
has this been implemented? Is there a way to make builds/build history public  for open source projects?

**Comment by anowell** [comment]
+1

**Comment by manishas** [comment]
This is now available :) Anyone with a link can view public project results!

@anowell @geshan @qadan @bobeagan @certik @ArturT @lkiesow  @pkaminski @nigelgbanks @jordandukart @RX14 would be great to get some feedback! Thanks for your patience!

**Comment by certik** [comment]
Awesome, thanks @manishas!

**Comment by trollixx** [comment]
Unfortunately, [`/latest` link](https://app.shippable.com/projects/54ac2ce4d46935d5fbc19b84/builds/latest) doesn't work and returns the following error:

```json
{"id":3000,"message":"Unauthorized access to route","methodName":"validateCaller|_checkPublicRoute"} 
```
