### ISSUE TITLE
Environment Variables not working in V2 eg: $SHIPPABLE_ARTIFACTS_URL 

### ISSUE THREAD

**Issue by nathgs** [Shippable/support#532]
http://docs.shippable.com/en/latest/config.html#common-environment-variables

In my shippable.yml I've set:
`archive: true`

```
after_archive:
  - echo $SHIPPABLE_ARTIFACTS_URL
```

Output is empty.

Prior to V2 this was working perfectly and I used the variable to enable an external system to automatically download the artifacts and prep them for deployment.

It seems this is not the only env variable that's broken (I also got empty from `echo $SHIPPABLE_API_TOKEN`).

Fix coming soon?

**Comment by cchantep** [comment]
Still not working :(

**Comment by manishas** [comment]
We now have API access for Shippable paid accounts. Details at http://docs.shippable.com/api and http://docs.shippable.com/api/#builds will show you how to get build artifacts.

Please let us know if this doesn't work.
