### ISSUE TITLE
bundle install all the time

### ISSUE THREAD

**Issue by nappa32** [Shippable/support#533]
5 minutes of the CI time is wasted in bundling. I'm trying to figure out how to make our tests fit in within the 20 minutes. The cache directive from travi.yml doesn't seem to work. 

my shippable : 

build_environment: ubuntu1204
language: ruby
cache: bundler
bundler_args: -j20
services:
    - elasticsearch 
    - redis
env:
- secure:  
  rvm:
- 1.9.3
  before_install: 
- bash deploy/shippable_before_install.sh
- gem install debugger-ruby_core_source
- gem install debugger -v '1.6.1'  
  before_script: bundle exec rake db:test_prepare
  script: rspec ./spec/models/ ./spec/contexts/ ./spec/routing/ ./spec/controllers/ ./spec/views/ ./spec/migrations/ ./spec/jobs/ ./spec/generators/ ./spec/mailers/
  branches:
  except:

```
- test1
```

**Comment by ArturT** [comment]
@onesupercoder If you check project settings then you will find info
```
Caching can only be enabled if you are pulling a Docker image.
```
As far as I remember a few months ago `cache: true` was working.
