### ISSUE TITLE
Adding Collaborators to the project

### ISSUE THREAD

**Issue by kirillberlin** [Shippable/support#55]
Hi There,

I am not seeing my GitHub private repo collaborators added to a project. Are there additional steps required to set this up?

Also, on your Features page, you state "Invite members even if they are not a part of the GitHub repo ". How do I do that?

Thanks.

**Comment by mraerino** [comment]
At the moment none of the collaborators of my private repo are able to access the build stati.
If they try to go to the project url they get `permission denied`.

How can I enable them to see my private repos in shippable?
