### ISSUE TITLE
Is it possible to disable MySQL and PostgreSQL services or get a clean Ubuntu/CoreOS build image?

### ISSUE THREAD

**Issue by evgeny-goldin** [Shippable/support#564]
I see in my [build log](https://app.shippable.com/builds/5417388f9dc0572a03719f32) the following two services are started, even though I absolutely don't need them:

```
sudo su -c "/usr/bin/mysqld_safe > /dev/null 2>&1 &"
sudo su -c "sudo -u postgres /usr/lib/postgresql/9.2/bin/postgres -c "config_file=/etc/postgresql/9.2/main/postgresql.conf" > /dev/null 2>&1 &"
```

Is it possible to completely disable them? Or put it another way - is it possible to get a plain vanilla Ubuntu/CoreOS build image with no run-time of any kind pre-installed and running? Right now I'm specifying a "python" language in my shippable.yml so that it (hopefully) starts faster than a Ruby one. 

Obviously, we could use a [custom Docker image](https://github.com/Shippable/support/issues/562) for that but I was wondering if there's a built-in way.

**Comment by alexw23** [comment]
:+1:
