### ISSUE TITLE
Manually triggered deployments

### ISSUE THREAD

**Issue by pniederw** [Shippable/support#570]
Couldn't find a discussion forum so posting here. I'm building an OSS library that needs to get published to Maven OSS/Maven Central. Each build should get published to Maven OSS, but only manually selected builds (releases) should get published to Maven Central.  Does Shippable support manually triggered deployments (i.e. pull model)?

**Comment by avinci** [comment]
We have done a whole bunch of things around this. Please let us know if you need more information. At this point I am marking this closed
