### ISSUE TITLE
Login page clobbers original destination

### ISSUE THREAD

**Issue by luhn** [Shippable/support#578]
Observed behavior:

* Click on a link to a Shippable build, such as `https://app.shippable.com/#/builds/123456`, with no logged in session or an expired login session
* You are redirected to `http://www.shippable.com/#/builds/123456`.
* Click on "Login" in top right.
* Click "GitHub auth"  (I assume BitBucket auth behaves similarly, but I haven't verified.)
* You are logged in and redirected to `https://app.shippable.com/`.

Desired behavior:  After login, be redirected to the initial destination:, `https://app.shippable.com/#/builds/123456`.

Another suggestion:  It would make it flow a little smoother if we were redirected to a dedicated login page (containing "GitHub auth" and "BitBucket auth" in very large buttons, and little else), rather than the homepage.  It might not be evident from the homepage that a login is being requested, nor is it immediately clear where one is able to log in.

**Comment by paulstatezny** [comment]
What @luhn said.

Post-login redirects work, but never from integrated GitHub pull request links. I *still* have to re-login, close the tab, and click on the link *again* when looking at builds from GitHub. (Which is 98% of the time.)

Would you guys be willing to look into this?

**Comment by rageshkrishna** [comment]
I've just deployed a fix for this. Please try it out with new PRs or re-running existing ones.

**Comment by paulstatezny** [comment]
Thanks @rageshkrishna! The fix worked if you've already pre-authenticated with GitHub.

It seems that it doesn't work if you're working from a fresh environment where you haven't logged into GitHub before. I opened an incognito window, and it just took me to the Shippable homepage after logging in. (I did have to perform multi-factor auth. Perhaps this is connected?)

**Comment by avinci** [comment]
This has been cleaned up significantly and please let us know if you are still seeing these issues
