### ISSUE TITLE
Scheduled builds

### ISSUE THREAD

**Issue by sundaymtn** [Shippable/support#582]
Hi,
Will there be an ability to schedule periodic builds (other than automatic upon push)?
Right now I have a project called waterline that builds then and commits a result db back to its own repository.  This causes a perpetual build cycle and I figure this might be an annoyance on your end, please let me know and I'll shut the project down.
Thanks,
Seth

**Comment by bbradbury** [comment]
Woot +1 to this. We have some builds that encompass where a number of disparate and usually safe changes happen throughout the day, so we don't want to use up our shippable workers building them all the time, but also don't want to lose all testing on them.

**Comment by bbradbury** [comment]
As a possible quick alternative-- if there were a REST hook we could use to trigger a build, we could roll our own with cron.

**Comment by angelathewebdev** [comment]
REST hook would be an interesting alternative

**Comment by manishas** [comment]
This is already available and we're working on documenting our newly released APIs :) I'll update this issue as soon as the docs are available.

**Comment by angelathewebdev** [comment]
@manishas awesome, thanks

**Comment by geshan** [comment]
how do we do nightly builds?

**Comment by avinci** [comment]
You can use our API to trigger builds on a schedule that you need run. does that help?

**Comment by geshan** [comment]
Any docs? but APIs are only available for paid accounts right?

**Comment by avinci** [comment]
http://docs.shippable.com/en/latest/api.html and yes its on the $1/month plan.

**Comment by manishas** [comment]
Closing this since it is available through our API.

**Comment by yehudasabag** [comment]
The API is nice but it is far from being alternative to the ability to configure nightly builds or deployment. The meaning of having this API is that I will need to call it from somewhere that will schedule it on night, only if I had commits to some relevant places, etc. 
This practically means I need some kind of CI server that will trigger shippable. So I will move to this CI server. 
To make it short - this is a feature for CI server and shippable should implement it IMO.
Thanks

**Comment by jeppefrandsen** [comment]
+1 for @yehudasabag's proposal

**Comment by keen99** [comment]
for other searchers, this got added with https://github.com/Shippable/support/issues/2600
