### ISSUE TITLE
Gem in Node.js project

### ISSUE THREAD

**Issue by ajunge** [Shippable/support#586]
Hi, 
We have a node.js project that uses Compass ( http://compass-style.org/ ) for css authoring. Compass is installed with `gem install compass`  we have the problem, that if we define the language as node_js  when we add:

```
language: node_js
node_js:
    - "0.11"

before_install: 
  - shippable_retry npm install -g grunt-cli
  - shippable_retry gem install compass
```

we get:

```
ERROR: While executing gem ... (Errno::EACCES)
Permission denied - /var/lib/gems
```

any solution to this?

Thanx
Andres Junge

**Comment by tobiaswidmer** [comment]
Looks like the solution above does not work anymore as of today. I'm using the exact same configuration enhanced with @rageshkrishna's proposal, but I get:
```
line 85: /root/.rvm/scripts/rvm: No such file or directory
```
I've tried both with Ubuntu 12 and 14 Node JS images, but no luck. Any help would be appreciated.

**Comment by Ivaylo-Bachvarov** [comment]
> /root/.rvm/scripts/rvm: No such file or directory

Same problem here :crying_cat_face:
