### ISSUE TITLE
Shippable account does not use Github primary email

### ISSUE THREAD

**Issue by arielschiavoni** [Shippable/support#601]
Hi,

I have a Github account with two different emails configured.
Then when I created a Shippable account linked to Github it seems to be using the last email in that list which is not the primary one.

Thanks.

Ariel.

**Comment by marshall007** [comment]
@manishas I have the same issue but with Bitbucket. Shippable is sending email notifications to my secondary email address rather than the primary. The yml config workaround isn't that useful for those of us on medium to large teams.

**Comment by marshall007** [comment]
See also #478, #871, #912.

**Comment by manishas** [comment]
@arielschiavoni @marshall007 are you still running into this?

**Comment by marshall007** [comment]
@manishas yea as of yesterday at least, this was still an issue for me with Bitbucket.

**Comment by manishas** [comment]
@rageshkrishna can you take a look at this?

**Comment by rageshkrishna** [comment]
Hi @marshall007! I'm looking in to this issue now. Can you please forward one of the build notifications that you received on the wrong email address to ragesh@shippable.com? I'd also like to know which address you expect to receive it on.

**Comment by marshall007** [comment]
@rageshkrishna just emailed you, thanks for taking a look! Let me know if you need anything else from me.

**Comment by lekhab** [comment]
@marshall007: We tried reproducing the issue, but we are unable to. Are you still facing this? Can you try switching your emails and seeing if the problem still persists (emails continue to be sent to the secondary address)? Looks like there is something specific in your scenario that we are unable to figure out..

**Comment by marshall007** [comment]
@lekhab just to be clear, I'm experiencing this issue with Bitbucket and I haven't tested whether it's resolved for GitHub or not.

> Can you try switching your emails and seeing if the problem still persists

I've switched them back-and-forth multiple times over the past couple months. Note that when I first created my shippable account, the `marshall007` was the only address. I then added the `mcottrell` one and set it as primary, but I've never received a shippable notification to this address.

![screen shot 2015-08-24 at 5 20 47 pm](https://cloud.githubusercontent.com/assets/877936/9454118/405c3e64-4a85-11e5-9f79-ac8d4bec8524.png)

**Comment by lekhab** [comment]
thanks for the details, @marshall007.  following up on this.

**Comment by lekhab** [comment]
@marshall007: So it looks like you have conflicting primary emails on GitHub and Bitbucket.  You are logging in with your GitHub identity and we use the preferences from your last used identity. So the emails are being sent to the primary email set up on GitHub. 

If you log in with your Bitbucket account, emails will be sent to the primary email configured on Bitbucket. 

Hope that helps.

**Comment by marshall007** [comment]
@lekhab is there a rationale behind using the preferences from your last used identity? That doesn't make a lot of sense to me. Why isn't it based on the identity/organization the repo is associated with?.

**Comment by lekhab** [comment]
@marshall007: Agreed. It should be. This is being taken into account during our re-design. I am going to tag this as a feature request to track  - since the current issue is by design..

**Comment by manishas** [comment]
We have added a field in account settings for default email. This is initially populated with what we get from your source control provider, but you can override it to anything you want. 

This should address the problems described here.
