### ISSUE TITLE
We need the ability to specify the patchlevel of Ruby we'd like to use

### ISSUE THREAD

**Issue by pgibler** [Shippable/support#621]
Ruby projects that utilize any gems derived from debugger-ruby_core_source or debase-ruby_core_source must allow the right patchlevel to be specified for the ruby version.

My ruby project is giving a false failure now, because the patchlevel that the shippable VM uses (2.0.0-p576) is not supported by the debase & ruby-debug-ide gem's I'm utilizing.

For the list of supported ruby versions, check here:

https://github.com/cldwalker/debugger-ruby_core_source/tree/master/lib/debugger/ruby_core_source

Would it be possible to allow us to configure the patchlevel of the Ruby version used in our VM?

**Comment by manishas** [comment]
Closing this issue since there is no action item from our side. please re-open if you have any questions.
