### ISSUE TITLE
build_environment variable ignored

### ISSUE THREAD

**Issue by Lazin** [Shippable/support#668]
I need to use ubuntu 13.10 build environment. I've add to my .travis.yml following line:
`build_environment: Ubuntu 13.10`build_environment: Ubuntu 13.10
but everything runs in ubuntu 12.04 anyway. Can I fix this somehow? My config file is here: https://github.com/akumuli/Akumuli/blob/dev/.travis.yml

**Comment by manishas** [comment]
Custom docker containers are documented, so closing this issue. Also, you can use standard base images available in shippableImages - http://docs.shippable.com/en/latest/custom_images.html#custom-images

Please let us know if you need anything else.
