### ISSUE TITLE
You have already activated rake 0.9.6, but your Gemfile requires rake 10.3.2.

### ISSUE THREAD

**Issue by cjroebuck** [Shippable/support#675]
Getting this when running rake. 

```
You have already activated rake 0.9.6, but your Gemfile requires rake 10.3.2. Prepending `bundle exec` to your command may solve this.
/home/shippable/.rvm/gems/ruby-2.0.0-p576/gems/bundler-1.7.3/lib/bundler/runtime.rb:34:in `block in setup'
/home/shippable/.rvm/gems/ruby-2.0.0-p576/gems/bundler-1.7.3/lib/bundler/runtime.rb:19:in `setup'
/home/shippable/.rvm/gems/ruby-2.0.0-p576/gems/bundler-1.7.3/lib/bundler.rb:121:in `setup'
/home/shippable/.rvm/gems/ruby-2.0.0-p576/gems/bundler-1.7.3/lib/bundler/setup.rb:17:in `<top (required)>'
(See full trace by running task with --trace)
Stopping services
```

Only unusual thing I can think of that I'm doing in shippable.yml is placing my bundle in non-standard directory, i.e. the shippable directory:

```
bundler_args: --without development doc --path=shippable
```

This is so that I can archive and download the bundle once it's all working

**Comment by maheshkakani** [comment]
Hi All, 

I was facing the similar issue as above in redmine 3.1.0.0 when installed in windows 7 PC (client)& trying to configure SVN repository (Windows Server). 

"You have already activated rake 0.9.6, but your Gemfile requires rake 10.4.2".

What was the Shippable.yml mentioned above?? I didn't have any such type of file.
