### ISSUE TITLE
Smarter way to copy repo code into shippable folder for archiving

### ISSUE THREAD

**Issue by cjroebuck** [Shippable/support#676]
Hey I'm trying to copy my code into the shippable folder once all tests have passed, but the command I'm using is causing the build to fail, even though it does manage to copy the files ok:

Here is the command i'm using:

```
after_success:
  - mv $SHIPPABLE_REPO_DIR/* shippable/
```

The error is:

```
mv: cannot move '/home/shippable/workspace/src/github.com/cjroebuck/project' to a subdirectory of itself, 'shippable/project'
```

I tried ignoring the error by changing the command to `- mv $SHIPPABLE_REPO_DIR/* shippable/ 2>/dev/null` but still the build fails. There must be smarter way than this!?

**Comment by son351** [comment]
@cjroebuck 'done' please, minor one :+1:
