### ISSUE TITLE
How can I download the build artifacts using curl/wget to remote machine?

### ISSUE THREAD

**Issue by cjroebuck** [Shippable/support#677]
Hi there,

I'm trying to download the build archive on a remote machine, using the url from $BUILD_URL: 

    curl https://app.shippable.com/builds/<build_id> -o mybuild.tar.gz

But its not working.

I read in #442 about needing an access token for this, but the link given to the docs their doesn't exist anymore - I can't seem to find anywhere in the docs for how to download the artifacts securely?

Thanks

PS The download archive button/functionality on the website is working fine for the same build id

**Comment by henrjk** [comment]
It seems there are a few alternatives to curl/wget artifacts:
1. #847 mentions a workaround to use a post build step to deploy build artifacts to S3. 
2. On a dedicated host one could access the build artifacts as one has full control over the machine.
3. Publish container to docker hub.

Before I pursue any of these I'd rather use a way to simply use curl/wget. Can you give us an update on the status of this?

**Comment by velo** [comment]
I do need that as well, any news?

**Comment by thephred** [comment]
This is now possible with the new shippable API:
http://docs.shippable.com/en/latest/api.html#builds-buildid-builditemnumber-artifacts

You must first make a request to the api to get the url for the artifact you are wishing to download.  Then you can use wget or curl to download it.

**Comment by manishas** [comment]
Closing this.

API access is now available - http://docs.shippable.com/api so you can use it to download artifacts.

please let us know if you need help with this.
