### ISSUE TITLE
Don't see build status for each commit on Github

### ISSUE THREAD

**Issue by rockerhieu** [Shippable/support#679]
Recently I don't see any icon to indicate build status for each commit on Github from Shippable. My project is https://app.shippable.com/projects/543f4a86b904a4b215678013. I tried to delete and re-enable the project on Shippable, but it didn't fix the issue.

**Comment by manishas** [comment]
This is an old issue and we haven't heard additional customer requests for this. At this time, this is not on our near term roadmap, so closing as won't fix.
