### ISSUE TITLE
More prominent coverage display

### ISSUE THREAD

**Issue by denis-sokolov** [Shippable/support#681]
Consider displaying code coverage a bit more prominently.
For example, see how [CodeClimate does it](http://docs.codeclimate.com/article/219-setting-up-test-coverage). Primarily, it would be nice to see the change compared to previous builds, as opposed to an absolute value that gives no useful information. It would also be nice if there was an option to send warning emails if coverage suddenly drops.
Perhaps you have features like this, but I didn't find them?
Thank you.

**Comment by manishas** [comment]
Closing since all requests for code coverage enhancements will be tracked in #174 .
