### ISSUE TITLE
Custom clone directory

### ISSUE THREAD

**Issue by fenfe1** [Shippable/support#689]
Hi,

Is it possible to set the name of the directory to clone into?

For example I have a project 'ansible-roles-bootstrap' that I clone as 'bootstrap', can I configure this in Shippable?

I.e. the command would end up being something like:

    git clone git@github.com:fenfe1/ansible-role-bootstrap.git /home/shippable/workspace/src/github.com/fenfe1/bootstrap

Thanks

**Comment by manishas** [comment]
Closing this issue. Please let us know if you need anything else. Thanks!
