### ISSUE TITLE
regex & wildcards in branch exclusion

### ISSUE THREAD

**Issue by jeradphelps** [Shippable/support#693]
I'd like to be able to run builds on wildcards for git-flow branches.  For instance, something like this:

~~~
branches:
  only:
    - master
    - develop
    - feature/*
    - release/*
    - support/*
    - hotfix/*
~~~

Is this supported?  It is not documented (though it is for [travis](http://docs.travis-ci.com/user/build-configuration/#Using-regular-expressions)), and in my initial tests, it is not working.

**Comment by rogierslag** [comment]
I'd love to exclude eg all tags which start with `deploy_` since that is just a deploy of a build (`master`) which in turn will trigger another build

**Comment by garthbrydon** [comment]
@manishas any progress on this feature request?

**Comment by trriplejay** [comment]
This feature is now available.  A `*` within branches only/exclude will be treated like a wildcard.  Please let us know if you run into any problems or have any questions about this feature.

**Comment by trriplejay** [comment]
I'm going to leave this open until we get our documentation updated to reflect this functionality.

**Comment by abhijitkini** [comment]
Info on wildcard entries has been updated in the documentation. http://docs.shippable.com/ci_configure/#includingexcluding-branches.

Closing as resolved.

**Comment by GuyMograbi** [comment]
link is broken

**Comment by abhijitkini** [comment]
@GuyMograbi Here's the updated link: http://docs.shippable.com/ci/advancedOptions/branches/
