### ISSUE TITLE
Build hangs and after 3600s is killed (?)

### ISSUE THREAD

**Issue by AndreaCensi** [Shippable/support#701]
Since the upgrade I have been having problems while running the tests for a project, Compmake, which worked fine before the upgrade, and currently whose tests work find on other platforms (Ubuntu 12/14, Mac).  Now on Shippable the build lasts 1 hour and then I suppose it's killed (though it says MemoryError). The tests shouldn't last more than a couple of minutes.

This is the project:
https://app.shippable.com/projects/540e77d33479c5ea8f9e92ab
Also here is the code: https://github.com/AndreaCensi/compmake/

Granted, these tests are probably slightly more involved than the average project because they include things like starting new processes. So perhaps they encounter some limitation of the virtual host where they run in Shippable compared to a normal host?

Now my problem is that these tests work on the platforms I have access to, but they don't work on Shippable, so I have no way to debug what's happening. It is also hard to debug by trial and error because each build will last 1 hour.

Any suggestion on figuring this out?

**Comment by manishas** [comment]
@AndreaCensi i see your latest builds for your project take about 4 mins, so am closing this issue. if you still need help, please re-open or post a comment and we'll take a look.
