### ISSUE TITLE
[Consolidated feature request] Support additional Notifications providers

### ISSUE THREAD

**Issue by amobrem** [Shippable/support#707]
https://slack.com/

**Comment by bittner** [comment]
**One:** [Official Slack docs on Integrations](https://slack.zendesk.com/hc/en-us/articles/202035138) -- *"If you provide a service and want to integrate with Slack, get in touch!"*

**Two:** I believe compatibility with [Travis-CI](http://docs.travis-ci.com/user/notifications/#Email-notifications) syntax would be favorable. Can you make this happen?

**Comment by manishas** [comment]
Tracking all requests for integration with notification providers here,

Slack
Hipchat #878

**Comment by manishas** [comment]
Slack is now supported natively! Check out http://blog.shippable.com/how-to-use-slack-integration-for-build-notifications

Give it a shot and let us know what you think :)

**Comment by taz77** [comment]
@manishas One request with the slack integration. Support private groups in addition to channels, and direct messages.

**Comment by rageshkrishna** [comment]
Hi @taz77! Private groups and DMs should be working. Does `#privateroom` and `@username` not work for you?

**Comment by taz77** [comment]
Hello @rageshkrishna I can get it to work for channels, I have not tried the direct message, but private rooms don't work. I had it running on a private room and through the notifications were broken till I decided to try a public channel - voila success. So I assumed you guys didn't support private room messaging in the emplementation of the notification to Slack.

**Comment by avinci** [comment]
both these have been implemented. hence closing this as complete.
