### ISSUE TITLE
Visualization of Code Quality metrics and browser (for Python)

### ISSUE THREAD

**Issue by bittner** [Shippable/support#708]
On your website you explicitly mention the "[Code quality metrics](https://www.shippable.com/features.html)" feature. With test results and code coverage alone (as of [configuration](http://docs.shippable.com/en/latest/config.html#test-and-code-coverage-visualization)) I'm missing the "rich visualizations" a bit. It says *"All tests are passing!"*, and *"n.nn% Branch/Sequence coverage"* only, for me at the moment.

For the team I need more information about code quality, ideally a browseable ranking of the most numerous / most severe violations / warnings / etc. Really, I'm missing something like [Sonar](http://www.sonarsource.com/products/plugins/languages/python/). An online [demo is here](http://nemo.sonarqube.org/dashboard/index/pyffi). The Python plugin uses [Pylint](http://pylint.org/) data.

Do you have Sonar or something similar on your roadmap? (Or did I miss some of the existing features in your UI?)

**Comment by bittner** [comment]
Any news on visualizations and/or drill down of test results? I'd love to see something like [Sonar](http://www.sonarsource.com/products/plugins/languages/python/) on Shippable, that would be awesome.

**Comment by manishas** [comment]
@bittner we have redefined our process a bit and the plan is to pick up an entire feature area (such as test results and code coverage) and address everything there at one go.

I'll update the overall issue (#174) when we pick this up.
