### ISSUE TITLE
How to define relative path to the project

### ISSUE THREAD

**Issue by mavarazy** [Shippable/support#71]
We are building our Scala Play2 project, using shippable.

The structure of the project is a bit different from expected one, git initialised not in the root folder of the project, but in the parent folder (parent contains, only project folder).

I could not find relevant shippable documentation, to support this kind of configuration.
Can you point me there?

**Comment by tiemevanveen** [comment]
@avinci I'm looking for the build path env var name but can't find it. Doesn't seem to be listed here: http://docsv2.readthedocs.org/en/latest/config.html#common-environment-variables
