### ISSUE TITLE
Build Fails Intermittently 

### ISSUE THREAD

**Issue by codeviking** [Shippable/support#712]
Our build intermittently fails on Shippable due to a permissions issue with `npm update -g`.  

Here's an example:

https://app.shippable.com/builds/544e8e0435700814002f6bff

The only fix we've found is to trigger another build a few minutes later.  Sometimes this works, sometimes it doesn't.

We'd love to see this fixed!

@schmmd

**Comment by manishas** [comment]
@codeviking your latest builds all pass, so closing this issue. please feel free to re-open if you run into this again.

**Comment by codeviking** [comment]
True -- but we think it's because of some refactoring on our part but there's likely still an underlying issue.

The error appears to be related to a classpath of a certain length.  We had a branch which added a few additional dependencies to an already complicated classpath, my guess is it was related to this:

http://stackoverflow.com/questions/3057841/too-long-line-in-manifest-file-while-trying-to-create-jar

I suppose we'll just stay tuned and if it re-arises we'll let you know if the above mentioned fix doesn't resolve our issue.

**Comment by manishas** [comment]
@codeviking sure, let us know if it happens again and we'll be happy to take a look.
