### ISSUE TITLE
Is there a way to drill down test results

### ISSUE THREAD

**Issue by erdogmush** [Shippable/support#718]
I just succeeded in triggering test results visualization using maven. It's showing a summary with number of tests passing, errors and failures. Is it possible to drill down to each test to see more detailed reports. The junit xml file is pushed and has all the information. The repo name is erdogmush/SN-Kata.

**Comment by manishas** [comment]
I have added this to the list of code coverage/test results enhancements feature request. Closing this issue since 174 will be used to track all of these.
