### ISSUE TITLE
Git can't checkout branch

### ISSUE THREAD

**Issue by that0n3guy** [Shippable/support#725]
I have a branch to start testing shippable with a "shippable" branch.

I get this: 

```
git checkout -f shippable
error: pathspec 'shippable' did not match any file(s) known to git.
Build completed
```

I'm not sure what's going on b/c I defiantly have a shippable branch.   Is this branch not being pulled locally before trying to check it out?  Do I need to do that manually w/ before_script?

**Comment by shadowbrush** [comment]
Same error message here with branch 'shippable'. Renaming the branch resolved the issue.

**Comment by that0n3guy** [comment]
Yup, confirmed.
