### ISSUE TITLE
Some usability issues (breadcrumb links, delete buttons)

### ISSUE THREAD

**Issue by bittner** [Shippable/support#733]
I'm regularly stumbling over the following rough edges of the [Shippable](https://app.shippable.com) user interface:

## 1) Breadcrumb-like Title With Double-Function
* On the Subscriptions page (e.g. https://app.shippable.com/subscriptions/...) the "breadcrumb", which is the name of the **Organization**, is a link *off the page* to the organization's Bitbucket or Github repository list.
* On a Project page (e.g. https://app.shippable.com/projects/...) the breadcrumb is divided in two parts:
  1. The first part is the **Organization** name again, but now it is a link taking you *back to* the Subscriptions page.
  1. The second part is the **Repository** name, which takes you *off the page* to the Bitbucket or Github repository.

### Suggestions:
1. All links in the **breadcrumb**-like title should help **navigating through Shippable only**! None of the links should take you off the page (except you make it really clear what will be happening!).
1. On the Subscriptions page the *"Bitbucket Organization"* or *"Github Organization"* text below the Organization could be made a link to take me off the page to Bitbucket/Github.
1. Links to the repos off the page should generally be made very obvious (e.g. provide a **clickable arrow icon** next to the Repository name).

## 2) Dangerous Delete Buttons
* The user account drop-down menu has a **"Delete account"** option right there in the drop-down. This scares me to death, and I always move the mouse cursor away to not accidentally click on the option.
* On both the projects page (e.g. https://app.shippable.com/projects/...) and the build page (e.g. https://app.shippable.com/builds/...) there is a **large dust bin** in the right upper corner to delete the project (*sigh!*) and a single build, respectively. That's a little bit less scary (*"Fine, I'll only lose my configuration work, not the whole account..."*), but still an obvious word of warning is missing (think: *"When I click on it, will it immediately delete X?"*).

### Suggestions:
1. Move the *"Delete account"* option **into the account page**, the *Dashboard*, make it a little less easy to click on it by accident (or even: to find it!). Maybe on the right-hand side, below the *"Organizations"* block you could make another block for *"Account"* things, like destroying the internet of things.
1. Make the *large dust bin* in a **warning color** (e.g. red) when **hovering over** it. I think Github does it do like that for dangerous actions.

**Comment by tobiasfuhlroth** [comment]
+1

**Comment by chschuermann** [comment]
+1

**Comment by sebastianmanger** [comment]
+1

**Comment by bittner** [comment]
Howdy Shippable, just wanted to let you know: Thanks for moving the "Delete account" button into a separate account page!  :+1:

**Comment by manishas** [comment]
We now have a brand new UI :)

Breadcrumb-like Title With Double-Function - fixed. 
Dangerous Delete Buttons - fixed 

Additional UI feedback is very welcome since everything;s changed recently. Please let us know :)

**Comment by bittner** [comment]
First of all: Thanks for fixing the issues I reported!  :+1: 

As for the new UI unfortunately I have bad news:

* Navigating the UI and **finding the information** you need has become much worse. My colleagues complain regularly. It's obviously not just a matter of "getting used to it". There are more hierarchies to climb it seems like (or at least feels like).
* The look and feel is **more Travis-CI like**, but is that really what you want? Your former UI looked more refreshing, more slim, easier to understand.

This is serious. I believe you'll have to go over the whole UI again and get the concept right. You need professional UX support. Please, don't be offended. It's really that I want a tool that's a pleasure to use for everyone of us.

**Comment by manishas** [comment]
@bittner Thanks for the feedback :) We will definitely keep this in mind as we move forward.

Can you provide a bit more detail on what your colleagues are trying to find that is difficult with the new UI? This will help us see if we can address it with small tweaks while keeping the scenario in mind as we evolve the UI.

**Comment by bittner** [comment]
@manishas In general, the old UI was much more refreshing. Yes, there were issues, but there was less clutter, less "we want to look like Travis-CI".

One major issue I just faced: On the home page there is no easy way to find one of our numerous projects. There is no search box, and only the first 5 projects are listed. Okay, there is a "Fetch More" link and the subscription drop-down box for drill-down, but when you select a subscription from the drop-down the next drop-down box appearing only offers you the projects that are **already visible** in the list! OMG!

So, in order to get to the build of a project we've not touched for 2 weeks or more I have to click me through "Fetch More" about 10 to 15 times until the project is listed! -- And it's clear that the drop-down is of no use this way: I can find the projects then on the page already.

## Don't Get Me Wrong: It's an Honest Feedback

I'm really sorry. I don't want to be mean. It's just that we really enjoyed Shippable. Because it was different. With all the issues there were (speed, mainly) it was nice to use Shippable, really nice. Refreshing!

And now it feels like a single stomachache. I've never again heard anyone saying what a pleasure it is that we have Shippable, think about this! It *was* different before. -- And, acknowledged, I never was a big fan of Travis-CI. The UI always felt clumsy and complicated, or not transparent as for the user experience to say at least. It's sad to see you copying their style. It's just plain wrong. Sorry.
