### ISSUE TITLE
Persistent Login Session Option [Feature Request]

### ISSUE THREAD

**Issue by paulstatezny** [Shippable/support#737]
Feature Request: Upon logging in, the user is given a "remember me" option. (Perhaps a checkbox?) This makes the user's login session persist even after the browser is closed.

It seems like every time I need to view a failed Shippable build, I'm asked to log in again. This feature would make the experience a lot smoother.

Somewhat related to #578.

Thanks!

**Comment by tomsterritt** [comment]
Something like this would be very helpful for me too - I end up having to log in pretty much every time I visit - even when I go directly to app.shippable.com as advised elsewhere. 

I would probably even say I'd expect the default behaviour with Github/Bitbucket auth to be remember me.

**Comment by zanona** [comment]
I share the same feelings here, mostly every time I want to check the dashboard I need to re-authenticate to login. In my case, I am using my Bitbucket account to authenticate which as far as I know, has a static token which should grant me lifetime login :) but unfortunately that doesn't last for long on shippable.

**Comment by manishas** [comment]
This should not happen anymore, can you please re-open if you run into this again?
