### ISSUE TITLE
How to use godep on a go project

### ISSUE THREAD

**Issue by vdemario** [Shippable/support#754]
My go project uses [godep](https://github.com/tools/godep) for all builds and tests. How do I install and use it on Shippable? I tried adding it to the `install` section on the `shippable.yml` file, and then using it on the `script` section, like so:

    language: go
    go:
      - tip
    install:
      - go get github.com/tools/godep
    script: godep go test -v ./...

But I just get a command not found:

    /home/shippable/build/build.sh: line 84: godep: command not found

What am I missing?

**Comment by manishas** [comment]
I am closing this issue since this is working with the changes suggested. Please re-open if you have further questions.
@icdev @elimisteve  Thanks for your help!!
