### ISSUE TITLE
Do you guys offer an API?

### ISSUE THREAD

**Issue by nateleavitt** [Shippable/support#768]
I would like to get a lot of the information that you present on the website into a cli tool. Things like build status and logs. I looked, but couldn't find reference to an api.

Thanks!

**Comment by trollixx** [comment]
Could you provide us with any ETA of public API?

**Comment by coreybutler** [comment]
Personally, I'd love to see something as simple as the ability to add a new git repository via API... even if that means updating the git repo webhooks directly. 

For context, I've got a Node.js-based yeoman generator that scaffolds new projects. It automatically sets up a new git repository and generates a ton of boilerplate stuff, including the most common unit tests. The one thing we can't do is setup the CI tests in a programmatic fashion.

**Comment by grue** [comment]
I'd love to see something like this too. :+1:

**Comment by skippy** [comment]
+1

**Comment by avinci** [comment]
Yes, we are actively working on this and altering our permissions model in order to allow MACHINE_IDENTITY tokens. Please look out for an announcement in the coming weeks...

Thanks for pushing us to do this...

**Comment by manishas** [comment]
API is available for all paid customers - http://docs.shippable.com/api/
