### ISSUE TITLE
SHIPPABLE_MINION_INDEX and SHIPPABLE_MINION_TOTAL

### ISSUE THREAD

**Issue by ArturT** [Shippable/support#771]
Could you provide variables:
* `SHIPPABLE_MINION_INDEX` it should starts from zero.
* `SHIPPABLE_MINION_TOTAL` it says how many minions particular build has.

I created knapsack gem https://github.com/ArturT/knapsack and I'd like to integrate it with shippable. It would be nice to have mentioned envs. CircleCI has similar thing https://circleci.com/docs/parallel-manual-setup#env-splitting

**Comment by manishas** [comment]
This is not on our near term roadmap, so deferring.
