### ISSUE TITLE
Looking to build my own docker image

### ISSUE THREAD

**Issue by pauldavidgilligan-msm** [Shippable/support#772]
How can I setup the shippable.yaml for a cents 6 docker build -t="hvd/go-skydns" .  ?

**Comment by pauldavidgilligan-msm** [comment]
Hi there. the latest version of shipyard is working great must have pickup an earlier version.

**Comment by manishas** [comment]
Thanks, I'll close this issue now.

We launched docker build support today, so check it out when you get a chance - http://blog.shippable.com/making-deployments-even-easier-with-docker-build
