### ISSUE TITLE
Rspec & Cucumber output with colors

### ISSUE THREAD

**Issue by ArturT** [Shippable/support#774]
It would be great to have colorized output for script command. It's much easier to read rspec or cucumber output when I see what's green or red. Feature badly needed. :)

**Comment by mbrodala** [comment]
See also #526 which already requested color output but was closed with the other request.

**Comment by ryanhendry** [comment]
+1

**Comment by mbrodala** [comment]
I just saw that Shippable apparently **does** support color output ([Example build](https://app.shippable.com/builds/569521999188220d001c2da1)):

![image](https://cloud.githubusercontent.com/assets/5037116/12268711/2e7215a6-b94e-11e5-9ec8-e0aadcd41e5a.png)

@manishas Is this WIP?

**Comment by mbrodala** [comment]
As it seems the basic 16 colors are indeed working:

![image](https://cloud.githubusercontent.com/assets/5037116/12294351/fa044c4c-b9f9-11e5-9d6b-a2d72824fb5e.png)

I've created an [example repository](https://bitbucket.org/mbrodala/colorful-shippable) which executes two shell scripts on build to test 16/256 color output.

**Comment by shrivara** [comment]
This is supported. [Here](https://app.shippable.com/runs/56e92d27fbb4d40d0034fab9) is an example run with `rspec` running in documentation mode. [This](https://github.com/shrivara/fat_free_crm) is the project being built.
