### ISSUE TITLE
local validator for shippable.yml

### ISSUE THREAD

**Issue by davcdhanesh1** [Shippable/support#775]
Hey I am using shippable for quite few months now. I was just thinking about a command line utility which can validate the shippable.yml before pushing the code to central repo. It is true that travis has their own validator which works for shippable.yml too. But I would be very happy to have such utility on my CLI. So that I can always validate my .yml file before commiting. An advanced exetention would be to run the same commands from .yml on local box before commiting.

Something like $ shippable-build-simulator 

this will run all the commands excluding docker setup part on my local box. This well help developers identify any potential mistakes they might have done in .yml files before pushing code to central repo.

**Comment by manishas** [comment]
yml files can be validated at http://yaml-online-parser.appspot.com/ or http://www.yamllint.com/

I have created a docs issue to add this to our docs.
