### ISSUE TITLE
Many specs failed but build is a success

### ISSUE THREAD

**Issue by murtyk** [Shippable/support#777]
Build status is a success even though there are many failures. Even it pushed to heroku. 

![screenshot from 2014-11-16 10 51 44](https://cloud.githubusercontent.com/assets/2120154/5062038/a98e0866-6d7e-11e4-95b4-369239917d7b.png)

**Comment by manishas** [comment]
@murtyk we need to schedule a call to follow up and understand this better. Are you available sometime this week or next? Thanks!

**Comment by murtyk** [comment]
Manisha,
Happy New Year!
I am tied up for couple of weeks. Will send you a note as soon as I get some free time. And I am very interested in working with you to resolve this issue.
Regards,Murty

**Comment by manishas** [comment]
@murtyk i am closing this issue but let me know when you are free to follow up about this and we can re-open it. Thanks!
