### ISSUE TITLE
Piped command breaks execution -- or just the log

### ISSUE THREAD

**Issue by bittner** [Shippable/support#790]
I'm using a series of piped commands to validate an HTML file as part of the build process. The [YAML file](https://bitbucket.org/bittner/adventsbasar/src/master/shippable.yml#cl-12) validates (with [Travis WebLint](http://lint.travis-ci.org/)) and the build process seems to execute successfully. However, the [build log](https://app.shippable.com/builds/546c825a7aac73c600837567) looks a bit odd:
```
(-)  script                                                                ✓ 1 seconds
      bash -c '! python html5check.py home/*.html
    (+) csslint --format=compact home/*.css
    Build script completed 
```
## Command is cut off at first pipe

The first script command really is:
```
bash -c '! python html5check.py home/*.html | grep -v "Error:.*frameborder.*attribute.*iframe" | grep "Error:\ "'
```
In the console log only the part before the first pipe shows up. There is no output of the command shown, but that *may* be correct, because with no errors there is no output. Also when I download the console log the text output is not much better: The part starting at the first pipe character is missing completely.

Is this just a text output error or is part of the command *actually* swallowed?

## Side Note

I need to do the weird `bash -c '...'` construct, because the YAML won't validate with a simple negated Bash command line. Explained with examples in https://github.com/mozilla/html5-lint/issues/9.

**Comment by bittner** [comment]
Regression :bomb:  This is an issue again.

In my YAML file I have the following script section:
``` yaml
script:
  - for FILE in `find . -name cv*.html | xargs`; do ! python html5check.py $FILE | grep "Error:\ ";  done
  - csslint --format=compact `find . -name *.css | xargs`
```
The first command is chopped off at the first pipe, and no output is shown whatsoever.
The second command is also chopped off at the first pipe, but at least the output is displayed in Shappable's Console log.

Example build: https://app.shippable.com/builds/55c7c87b99917b0b00401128

**Comment by lekhab** [comment]
following up on this..

**Comment by lekhab** [comment]
@bittner: this is resolved now. can you please let me know if everything looks good on your end?

**Comment by bittner** [comment]
When I go to the [example build](https://app.shippable.com/builds/55c7c87b99917b0b00401128) I've mentioned above the console shows *"Waiting for logs..."* and nothing more happens. I hope this is a temporary issue. Otherwise I would say it's worse than before.

**Comment by lekhab** [comment]
@bittner: Sorry! should have asked you to look at recent builds. The reason why you are unable to see the logs for the older builds is because we had to purge logs older than Aug 16 to handle DB out of space issues. (https://github.com/Shippable/support/).

I just re-ran the [old build](https://app.shippable.com/builds/55dded9a7743f10b0027d462). You should be able to check the logs now.

**Comment by lekhab** [comment]
@bittner: please let me know if you are still facing any issues here.

**Comment by bittner** [comment]
No, sorry that I didn't respond.
