### ISSUE TITLE
Re-run individual builds environments 

### ISSUE THREAD

**Issue by hanloong** [Shippable/support#794]
Is it possible to run individual builds (So just build 19.2 not 19.X which would include (19.1, 19.2, 19.3 etc)).

We have setup environments to run builds separately.
- unit tests
- integration tests
- external integration tests (rely on external API's)

Unit tests are super reliable, integration tests less so, and external integration even less than that. On Travis if one of these fails we can just trigger a re-run of that test and leave the others as passed.

I know most people tend to mock out external API calls during tests but we have been burnt by our payment gateway API making breaking changes to existing API versions, so this is the best way to make sure our code is stable.

**Comment by ralfschimmel** [comment]
This would be great, we have 12 test jobs, and when one fails (due to npm/docker/whatever one-off reason) we need to re-run all of them. This is not good for us, but also not for your shared resources 👍

**Comment by ambarish2012** [comment]
Closing as dup of Shippable/support#680

**Comment by rmmcnulty9** [comment]
@ambarish2012 Shippable/support#680 does not have anything to do this with issue. 

We also need a way to re-run a single build from a build matrix. This issue should be reopened or the correct duplicate should be linked.

**Comment by trriplejay** [comment]
I believe it's this one that should've been linked (though this issue is older...):
https://github.com/Shippable/support/issues/2680

We are currently working on this feature.
