### ISSUE TITLE
Notifications for only master branch

### ISSUE THREAD

**Issue by luhn** [Shippable/support#796]
I would like to be notified via email if the master branch fails the tests, but the other branches are all WIP code that fail tests all the time and I don't need email notifications for.  (I'll know when they fail from the GitHub pull request page.)

**Comment by lolo121** [comment]
Yes, i face the same issue with the notification setting in shippable.yaml file
how to make it only send email for only master branch?
do we have branch attribute for this ?

notifications:
    email:
        recipients: xxx
        branch: master
