### ISSUE TITLE
more minions

### ISSUE THREAD

**Issue by kadut** [Shippable/support#798]
Is there some way to purchase a larger minion pool?  In my settings, I can choose between individual and startup, but see no option for > 5 minions.  Yet I see others report issues that their, say, 10 minions are all hung so there must be some way to get more.  And I need more!  Please let me know what to do here.

**Comment by kadut** [comment]
Hi Manisha,

We would love to use shippable as our primary testing platform.  Our vision
is to run related tests on the local machine, but when those pass then
count on shippable to do the full test suites faster than we could do them
locally on on our little dev machines.

We have our unit tests paralyzed enough that Shippable is already faster
than local by a good amount, but we use 4 minions for a single branch test
and so things can get backed up.

Ideally (assuming something like a linear cost increase) I would like to
try going up to 12 minions to start, which would allow us to run 3 builds
in parallel in our current configuration.

Also a huge + for getting containerized tests going - I know you are
working on this, but without it we need to run our selenium tests
containarized on a Strider that we manage ourselves.

Thanks,

Keith

**Comment by manishas** [comment]
@kadut we can customize a plan with 12 minions and get back to you. 

For the containerized tests, can we do a hangout so I can better understand your requirements? What time will work for you? We're in PST time zone.
