### ISSUE TITLE
[Consolidated feature request] Support for additional Docker Registries

### ISSUE THREAD

**Issue by alexanderlamb** [Shippable/support#800]
Is there a way to pass the login credentials for a private Docker Registry along with the build_image config in shippable.yml?

docker pull docker.company.net/pms_web
       Error occurred : Authentication is required.
       docker pull docker.company.net/pms_web complete

**Comment by curtiszimmerman** [comment]
+1 for this please holy smokes. I'd submit a PR tonight if I could do it myself.

**Comment by surjikal** [comment]
I would like to see this as well.

**Comment by sklose** [comment]
Is there any estimate on when this feature will become available?

**Comment by curtiszimmerman** [comment]
Ping! Any updates?

**Comment by manishas** [comment]
We current support Docker Hub and GCR - http://docs.shippable.com/docker_registries/

Requests for additional registry support -
Quay
Private registries

**Comment by jzelinskie** [comment]
I'm an engineer who works on Quay.io, if you have any questions for working to integrate with us, just ping me.

**Comment by manishas** [comment]
@jzelinskie I'll probably get in touch early next week. What's the best way to reach you?

Thanks for your message!

**Comment by jzelinskie** [comment]
@manishas It may seem impersonal, but an email to support@quay.io is probably the best means of contact. This way we can basically tie things into our issue tracker. We don't have a support team, so this is currently a line straight to our engineers.

**Comment by manishas** [comment]
This is now available! You can push and pull images from Quay.io as well as private docker registries.

Check out our docs at http://docs.shippable.com/docker_registries/

Let me know if you have any questions.... feedback much appreciated :)

**Comment by curtiszimmerman** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Awesome! <3

**Comment by manishas** [comment]
Closing this issue since Quay and private registries are now supported. Thanks!

**Comment by manishas** [comment]
@jzelinskie we announced quay integration and posted a blog about it today - http://blog.shippable.com/integrate-with-quay.io-and-private-docker-registry

If possible, would love a retweet from quay so your customers know about this integration - https://twitter.com/BeShippable/status/621386282556616704

Thanks!

**Comment by manishas** [comment]
@jzelinskie Thanks! I just saw a retweet :)

**Comment by jzelinskie** [comment]
np @manishas thanks for the integration :+1:
