### ISSUE TITLE
Default OS user to use in shippable from my custom images

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#802]
Hello,
I have a problem running some app from root user.
Then I will need create a new user and run app with this one.
Are there a variable in .yml file for this case?

I try using 
```bash
sudo su myuser
```
And build is timeout.

I try using
```bash
ENV myuser
```
But don't work.

Or a user named standard that allow use it in shippable.

**Comment by moylop260** [comment]
Hello @manishas

**Comment by manishas** [comment]
@moylop260 we don't currently know of a way to use another user. Are you blocked by this?
