### ISSUE TITLE
[question] Using more than one custom images

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#803]
I have defined into ```.travis.yml``` file
```yml
build_image: my_custom_image
```

But We need add other images to test it.
```yml
build_image: 
   - my_custom_image1
   - my_custom_image2
   - shippable/minv2
```
Is possible?

**Comment by manishas** [comment]
This is fixed with our build system upgrade since you can now customize the yml to handle this scenario. New yml documented at http://docs.shippable.com/ci_configure/
