### ISSUE TITLE
Only include services based on current build matrix

### ISSUE THREAD

**Issue by hanloong** [Shippable/support#820]
Is it possible to only include services for specific builds in the matrix?

For example we have unit tests and integration tests.
 - They both require `postgres` and `redis` - this works now
 - Only the INTEGRATION tests require `selenium` which can take a long time to start

Also I noticed `mysql` is started by default, is there a way to stop this?

Thanks in advance

**Comment by manishas** [comment]
We no longer start mysql and postgres by default except for the legacy build image minv2.

As for starting services only for specific builds in a matrix, we haven;t heard additional customer feedback in this area. This is not on our near term roadmap, so closing.
