### ISSUE TITLE
No way to stop 'processing' builds without admin permission 

### ISSUE THREAD

**Issue by grepped** [Shippable/support#826]
I have a build that is hanging on a command and listed as 'Processing'. There seems to be no way to cancel a build, and I do not have permission to delete as a non-admin. 

In a team workflow it is time consuming to ask the account administrator to delete every stuck build, I feel it would be a beneficial feature for users, or a stop button at the very least.

**Comment by manishas** [comment]
We have no current plans to allow everyone to cancel or delete builds. Closing this issue.
