### ISSUE TITLE
Add a way to clear cache from the UI

### ISSUE THREAD

**Issue by maxgalbu** [Shippable/support#829]
I'd like to start with a fresh docker image, but keep the cache enabled. I currently have some permission issues and would like to start with a new image, but I'd like to cache the new image too. How can I do that?

**Comment by pmoust** [comment]
also interested /ping

**Comment by manishas** [comment]
This is now available in Project Settings.

![screen shot 2015-07-30 at 9 58 27 am](https://cloud.githubusercontent.com/assets/2983749/8989526/9141092e-36a1-11e5-9dd5-38112725dd72.png)

Thanks for your patience!
