### ISSUE TITLE
Using environment variables in commit_container

### ISSUE THREAD

**Issue by jamesjwarren** [Shippable/support#834]
Is it possible to do something like:
`commit_container: dockerusername/$project:$tag`

setting `$project` and `$tag` via environment variables? I have tried this but get invalid repository name as it thinks the repo name is $project...

Ideally I would like to set the tag based on the branch.

**Comment by manishas** [comment]
This is now possible since you can now use docker commands directly in your yml. 

Relevant docs - 
http://docs.shippable.com/ci_configure/#pushing-an-image-to-a-registry
http://docs.shippable.com/ci_docker/
