### ISSUE TITLE
Docker login failing with "No credentials provided"

### ISSUE THREAD

**Issue by alexanderlamb** [Shippable/support#835]
The build is failing on the docker pull step with the following:
![screen shot 2014-12-01 at 8 15 46 pm](https://cloud.githubusercontent.com/assets/5480111/5257932/24eea7ee-7997-11e4-980a-b28dee039226.png)

I have entered my Docker Hub credentials and the Docker Hub icon is showing as green and "On".  This configuration was previously working and I was able to pull from a private Docker Hub repo.

This with a custom docker image and is running on a dedicated host.  Am I missing something?

```
#build against docker image
build_image: fdadev/pms_web

# language setting
language: php

# version numbers, testing against two versions of node
php:
  - 5.6.3
```

**Comment by CentaurWarchief** [comment]
@rageshkrishna @manishas Same happened here; now.

**Comment by Vilsepi** [comment]
Had this again. Went through when rebuilding manually.

     Docker pull shippable/minv2:latest
    Authentication is required.: Traceback (most recent call last):
      File "/home/shippable/dpd/step_listener.py", line 98, in handle_message_callback
        self.execute_step(build_plan, current_step, False)
      File "/home/shippable/dpd/step_listener.py", line 164, in execute_step
        raise e
    Exception: Authentication is required.

**Comment by rageshkrishna** [comment]
@Vilsepi We had an issue on one of our hosts. This shouldn't be happening any more. Please let me know if you still run in to this.
