### ISSUE TITLE
Firewall rules to allow Shippable infrastructure to control Dedicated hosts

### ISSUE THREAD

**Issue by vkuusk** [Shippable/support#839]
I would like to use dedicated hosts with shippable behind the firewall and have several questions about opening my firewall:
1. which ports, except SSH port 22, should be opened to dedicated hosts?
2. on which ports the dedicated hosts will talk back to shippable (or should it be ALL)?
3. is there a list of IPs of Shippable, which I can white-list on my firewall?
4. Is all traffic TCP? 

Thanks.

Regards,

Vlad

**Comment by manishas** [comment]
Closing this issue. @vkuusk please re-open if you have further questions.
