### ISSUE TITLE
Intermittent Failures on Ruby / Rails Build

### ISSUE THREAD

**Issue by jamescgibson** [Shippable/support#842]
I'm not sure if this is because of the (possibly ongoing?) DDOS on DNSSimple, but I'm seeing intermittent  failures on the install step of a ruby/rails hello world app. Different gems each time, and I can always access the file that 503s manually from my macine. It's always a 503 from Bundler when trying to install the gem. An example:

```
Installing rspec-core 3.1.7

Gem::RemoteFetcher::FetchError: bad response Service Unavailable 503 (https://rubygems.global.ssl.fastly.net/gems/rspec-expectations-3.1.2.gem)
An error occurred while installing rspec-expectations (3.1.2), and Bundler
cannot continue.
Make sure that `gem install rspec-expectations -v '3.1.2'` succeeds before
bundling.
```

I know this might not be something you all can fix, but wanted to report it regardless.

**Comment by reiz** [comment]
Since 2 days I'm getting the same error.

**Comment by jamescgibson** [comment]
@reiz When this occurred for me, it ended up being intermittent connectivity issues between the RubyGems server and Shippable - best I can recommend, personally, is to wait a day and hope it resolves itself.
