### ISSUE TITLE
[UX] On/off dashboard labels are unclear

### ISSUE THREAD

**Issue by jtmarmon** [Shippable/support#844]
It's a bit hard to understand what this:
![image](https://cloud.githubusercontent.com/assets/4528076/5301663/7a2a04d4-7ba8-11e4-8382-c60cbab71688.png)

means. I can't tell if it's trying to convey state or the result of clicking it.

**Comment by manishas** [comment]
This UI has completely changed. Please let us know if you're having issues with the new UI.
