### ISSUE TITLE
Deploy build artifacts to S3

### ISSUE THREAD

**Issue by behemphi** [Shippable/support#847]
We are just trying out Shippable now and while it read the build portion of the .travis.yml (brilliant idea) it did not read the deploy sections.  Looking through the documentation this does not appear to be directly supported.

Our use case is the building of documentation with sphinx, then release to an S3 bucket configured to serve a static website.  

After hacking on this with `s3cmd` and some logic around the `$BRANCH` environment variable we are able to make the move.  However, it seems that the lack of ability to drop build artifacts in to S3 natively as Travis does would be useful to many others in many other situations.

Thanks for considering the idea.

**Comment by jessica-pixvana** [comment]
I'm looking to do what @behemphi did and upload build artifacts to S3. But it appears his link is dead now. Does the blog post live somewhere else now?
