### ISSUE TITLE
Execute command after commit_container

### ISSUE THREAD

**Issue by dstendardi** [Shippable/support#848]
Is there anyway to execute a command after a container is commited ?

I would like to autodeploy the container to a demo environment after a succesful build but unfortunately I can't use the after_success phase which happen before  commit_container.

thx for your help !

**Comment by amobrem** [comment]
I need this too. Thanks!

**Comment by amobrem** [comment]
eta?

**Comment by wrabbit-revisited** [comment]
Making the creation of small docker containers easy would be of interest to me, too.

**Comment by amobrem** [comment]
any news?

Thanks
Ali

**Comment by manishas** [comment]
We launched Docker build support today, along with webhook support through our REST APIs. Will this combination address your scenarios? More on today's feature release here - http://blog.shippable.com/exciting-new-features-at-shippable

**Comment by vially** [comment]
Unless I'm missing something this does not seem to address the original issue. My use case (which does not seem to be covered right now) would be to deploy the newly pushed container. For example let's say I want to spin up a new VM instance which will run the newly built container image.

Ideally I should be able to define a new hook in the shippable.yml (e.g.: `after_image_push: deploy_container.sh`) which would get executed after the container is pushed to the Google Container Registry.

**Comment by manishas** [comment]
CLosing as DUP of #824 where i'm consolidating all requests for pushing to docker registries and tagging of images.
