### ISSUE TITLE
Open directory permission denied

### ISSUE THREAD

**Issue by crimsonronin** [Shippable/support#855]
Hi there,

I'm getting the following error:

```
Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(/home/shippable/workspace/src/github.com/zoopcommerce/commerce-theme-module/tests/Zoop/Theme/Test/Parser/../../../../../data/temp/simple-temp): failed to open dir: Permission denied' in /home/shippable/workspace/src/github.com/zoopcommerce/commerce-theme-module/tests/Zoop/Theme/Test/Parser/FileParserTest.php:171
Stack trace:
#0 [internal function]: RecursiveDirectoryIterator->__construct('/home/shippable...', 0)
```

It seems as though I can write to `/home/shippable/workspace/src/github.com/zoopcommerce/commerce-theme-module/data` but I can't open the directory using [`RecursiveDirectoryIterator`](http://php.net/manual/en/class.recursivedirectoryiterator.php). Are you able to update the file permissions to allow this?

Thanks

**Comment by manishas** [comment]
This totally fell off the radar. Apologies for that!

I don't see recent builds for your project, so am closing this issue. Let us know if you want us to take a look and we'll prioritize this.
