### ISSUE TITLE
[question] Coverage.py warning: No data was collected.

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#856]
I have a build with next error:
![coverage error good](https://cloud.githubusercontent.com/assets/6644187/5330383/4fd218f8-7db4-11e4-9a98-55b19c8a30cb.png)

Then I execute (for local debug):
```bash
docker pull MYPROJECT:MYBUILD
docker run -it MYPROJECT:MYBUILD /bin/bash
```

Now I run same command in my local container:
![coverage without error](https://cloud.githubusercontent.com/assets/6644187/5330395/f6292548-7db4-11e4-92b2-bfc28ce9a6da.png)

I saw:
shippable<>local
Shippable container with a error.
Local container without a error.

I expected:
See same error into both container (shippable=local)

NOTE Next bug is same case (locally build <> shippable build)
https://github.com/docker/docker/issues/783

Question:
I need the same environment of docker app as shippable in my local.
Are there a documentation of configuration docker app that use shippable?
Do you have a particular configuration of docker for AUFS?

**Comment by moylop260** [comment]
:+1:

**Comment by mnesterovych** [comment]
Have the same problem with coverage==4.1
