### ISSUE TITLE
Continuous Deployment to a Chef Server for cookbooks

### ISSUE THREAD

**Issue by behemphi** [Shippable/support#857]
It would be ideal to have a way to upload a cookbook to a Chef server after it passes test.  
- light weight - do not install the entire chef gem or omnibus package, only what is needed to the the upload
- connect to any Chef server (i.e. Host Chef, Private Chef, Enterprise Chef)

**Comment by avinci** [comment]
We have added a bunch of stuff with assembly lines in the past year or so. This should make it relatively easy to do this. Not sure if anyone still needs this though. Cleaning this us as its from a while ago.
