### ISSUE TITLE
Nested docker images

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#864]
Hi,

Is is possible to have docker containers defined within the test suite? That way we can isolate our services like we do in production and use Shippable nonetheless.

@alexnederlof

**Comment by jamesjwarren** [comment]
Would 'full Docker build' include the possibility to run multiple docker containers inside the test environment. We have docker containers configured for database servers that would be useful to run along side the app container for testing.

**Comment by manishas** [comment]
Yes, your scenario will be addressed. Watch for upcoming announcements soon. Thanks!

**Comment by apeiniger** [comment]
Is there an update on availability of this feature?

**Comment by caarlos0** [comment]
+1

**Comment by mpscholten** [comment]
Any updates on this one?

**Comment by manishas** [comment]
Please check out Shippable Formations - http://blog.shippable.com/introducing-shippable-formations-devops20-for-dockerized-apps

This allows you to run multi container environments pretty easily. We can best explain with a demo, so feel free to schedule one at https://shippable.youcanbook.me/

Main strengths -
- Define your application as a set of services
- Each service can have one or more containers, plus some config like URLs, ports, etc
- Shippable manages the environments for you, you do not need to write any scripts or code to get everything hooked up. Environments are fully orchestrated and persistent, so you can run your dev/test labs using this.
- You can upgrade or rollback in a single click, plus you can choose to auto deploy, which means for every code commit, we will do CI on the single container, and then push the tested container to your environment.

**Comment by manishas** [comment]
Closing.
