### ISSUE TITLE
Cache not working anymore?

### ISSUE THREAD

**Issue by hafen** [Shippable/support#867]
Last week I was experimenting with the cache and it seemed to be working as expected.  This is the big feature that is drawing me to shippable.

However, this week, I am having trouble.  No matter what I do, subsequent builds always start from shippable/minv2.  I have cache: true in my shippable.yml, and at the end, I get "successfully cached container", but subsequent builds still start from shippable/minv2.  I've tried waiting for a while between builds, etc., but can't get it to work.  An example build is: 54872b9d67b7f514009aa4db.  I don't know what has changed from last week, but I can't get it to start from a cached image.

**Comment by jpgarcia** [comment]
Having the same issue here. Is the fix already in place? 

I've configured the .yml with **cache: true** and I've also enabled the project settings **"Cache Container"** and set an image name to run on.

Should I specify the cache option in both sides?
