### ISSUE TITLE
Cannot cancel or delete builds if not repo owner

### ISSUE THREAD

**Issue by professorplumb** [Shippable/support#869]
I have admin rights to the bitbucket repo I'm building but am unable to delete or cancel builds (assuming because I'm not the owner.)  This means that when a build hangs (separate ticket) I have to wait 60 minutes for it to be terminated before I can run another; this is unacceptable.  Can the owner give me permission to delete/cancel builds, and if so, how?

**Comment by manishas** [comment]
@professorplumb you should be able to cancel builds with your permissions. Delete builds is an owner only action for now.

I am closing this issue, but please re-open if you cannot cancel builds.
