### ISSUE TITLE
Webhooks for Builds

### ISSUE THREAD

**Issue by nielsen** [Shippable/support#87]
Is there a way to publish custom post bodies to a webhook URL with build results?

**Comment by toby-griffiths** [comment]
Any news on this feature being added?

**Comment by pmoust** [comment]
@toby-griffiths you can already implement this via `after_success:` and `after_failure:` parts in your shippable.yml. Check the environment values in the script part of you build, you can use those to craft a curl call.

**Comment by marshall007** [comment]
I think it still makes a lot of sense to support webhooks. We'd like to be able to generically listen for build events across our organization without having to configure `after_success` and `after_failure` steps in each individual project.

**Comment by n0mer** [comment]
@marshall007 i second that - with shell scripts there is no point of using Shippable.

They advertise that as "DevOps" with a click of a button, and listening that "please write a shell script for that" is so 1990s
