### ISSUE TITLE
Build hanging

### ISSUE THREAD

**Issue by professorplumb** [Shippable/support#870]
Build 7.1 of the favorizeapp repo under ericplumb account (started 12/9/14 6:36 PM) hangs on `python manage.py test` with no console output, no indication of what's going on, no way to cancel.  (See #869; I am unable to delete the build.)

**Comment by manishas** [comment]
@professorplumb we have no way to print a message in the console indicating that it is waiting for user input. I am closing this issue but I will add an FAQ about this.
