### ISSUE TITLE
Change email address for notifications

### ISSUE THREAD

**Issue by cbliard** [Shippable/support#871]
I receive shippable build notification mails on an old email address. I have 3 different email address associated with my github account. How can I choose a different one?

**Comment by ianawilson** [comment]
I have a similar problem, but with Bitbucket. I just changed my primary email on Bitbucket, but it hasn't been reflected on Shippable. I've tried logging out / back in again, hoping that would sync it. Also tried the "sync" button on the Shippable dashboard. Is there anything else I can do other than edit the shippable.yml file? This is for a set of team projects, and I'd rather change it on my account than start hard coding emails to all the repos.
