### ISSUE TITLE
Cannot build branch, using dedicated host and cache: true.

### ISSUE THREAD

**Issue by ryanwalker** [Shippable/support#880]
I am using a dedicated host. I wondered if "cache: true" would work (didn't think so but tried it). I am testing only on a specific branch. I pushed the change up and it built. But after that it would not build anymore for me. It will not not build when i push or when i manually run the build. it just spins and spins and does nothing.

**Comment by manishas** [comment]
@ryanwalker checking in to see if this started working for you. If not, can we get on a hangout and track this down?

**Comment by manishas** [comment]
Closing due to lack of response. Please re-open this if you have further questions.
