### ISSUE TITLE
uncss: Error executing command to extract phantom ports

### ISSUE THREAD

**Issue by henrjk** [Shippable/support#884]
In this [build](https://app.shippable.com/builds/548f41f9637861dc007738d4), the script fails with the following error:

``` bash
Running "uncss:test" (uncss) task
Fatal error: Error executing command to extract phantom ports: Error: Command failed: (Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
)
```
The project is a fresh clone (without additional changes) from https://github.com/addyosmani/grunt-uncss. On my Mac with OS X 10.9.5 `npm install` followed by `npm test` worked without problems.

I tracked down that the message comes from this line of code [node-phantom-simple](https://github.com/baudehlo/node-phantom-simple/blob/master/node-phantom-simple.js#L175),

Can you give me some guidance on how to troubleshoot this further?

**Comment by manishas** [comment]
@henrjk we do not make private patched forks since we cannot commit to maintaining them over time. I am closing this issue since there is nothing actionable for us.

I will definitely keep an eye on this and if this becomes a common complaint from folks, we will revisit again. Thanks!

**Comment by vijilent** [comment]
Hello, same issue for us I think- pushing our application up on a Heroku.com Linux instance, which does not allow the app to use netstat.  Any advice?
