### ISSUE TITLE
npm is throwing error with lodash dependency under Grunt

### ISSUE THREAD

**Issue by bryhsiao** [Shippable/support#885]
My shippable.yml file : 

language: node_js
node_js:
  - "0.10.33"
before_install:
  - sudo npm -g install grunt-cli karma bower
  - npm install
  - bower install
  - grunt

Grunt seems to be having issues, karma/bower all installed just fine. 

npm WARN optional dep failed, continuing fsevents@0.3.1
/usr/bin/grunt -> /usr/lib/node_modules/grunt-cli/bin/grunt

> ws@0.4.32 install /usr/lib/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

then 
npm install failed

 npm install
npm WARN deprecated grunt-ngmin@0.0.2: use grunt-ng-annotate instead
npm WARN deprecated ngmin@0.3.8: use ng-annotate instead
npm WARN optional dep failed, continuing fsevents@0.3.1

> ws@0.4.32 install /home/shippable/workspace/src/bitbucket.com/medsyna/medapp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/shippable/workspace/src/bitbucket.com/medsyna/medapp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/shippable/workspace/src/bitbucket.com/medsyna/medapp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm WARN optional dep failed, continuing request@~2.40.0
npm WARN optional dep failed, continuing clean-css@2.2.22
npm ERR! Error: EACCES, mkdir '/home/shippable/.npm/lodash/0.9.2'
npm ERR!  { [Error: EACCES, mkdir '/home/shippable/.npm/lodash/0.9.2']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/home/shippable/.npm/lodash/0.9.2',
npm ERR!   parent: 'grunt' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/home/shippable/.nvm/v0.10.33/bin/node" "/home/shippable/.nvm/v0.10.33/bin/npm" "install"
npm ERR! cwd /home/shippable/workspace/src/bitbucket.com/medsyna/medapp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! path /home/shippable/.npm/lodash/0.9.2
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/home/shippable/.npm/lodash/0.9.2'
npm ERR! not ok code 0
Build completed
Skipping artifact upload
Build completed

**Comment by manishas** [comment]
Closing this issue since we suggested a fix. @bryhsiao please re-open if this doesn't address your issue. and we'll be happy to take another look. Thanks !
