### ISSUE TITLE
feature request: post build docker image builds

### ISSUE THREAD

**Issue by daniel-garcia** [Shippable/support#891]
I would like to define a specific output directory in my build that would be kicked off as a new docker build. For example, I set some setting DOCKER_BUILDDIR=/usr/local/dockerbuild. This directory would contain build output I have placed in it as well as a Dockerfile. Shippable would run a docker build after my build has successfully completed, tag it, and push it to some destination I have configured. It would be nice to be able to emit the docker registry, tag and credentials as part of the build process.

This process would allow me to create minimal docker images for my builds that are production/qa ready.

**Comment by txchen** [comment]
Hi @avinci 
Our team needs this feature very urgently for our project... May I know the latest status of this? We are happy to dog food the beta.

**Comment by manishas** [comment]
@daniel-garcia we introduced post CI dockerbuild a couple of months ago, sorry for the late update here.

Please check out - 
http://docs.shippable.com/docker_build/#post-ci-dockerbuild
http://docs.shippable.com/docker_registries/

This should address your scenario completely. Please let me know.
