### ISSUE TITLE
oracle jdk export policy

### ISSUE THREAD

**Issue by lumir-mrkva** [Shippable/support#892]
hi, aes encryption is very important for my project, but your docker image *shippable/minv2*
doesn't have patched unlimited export policy in their oracle jdk's and that results in this exception:
```
java.lang.IllegalStateException: java.security.InvalidKeyException: Illegal key size or default parameters
```
please configure your image with this patch - you can get it here (jdk7):http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html 

this problem doesn't apply to openjdk builds.

**Comment by aug70** [comment]
+1

**Comment by manishas** [comment]
you can actually do this yourself by add the policy files you want to use in the root of your repo, and the following lines in the yml:

```
before_install:
    - sudo mv -f local_policy.jar /usr/lib/jvm/java-7-oracle/jre/lib/security
    - sudo mv -f US_export_policy.jar /usr/lib/jvm/java-7-oracle/jre/lib/security
```

**Comment by manishas** [comment]
Closing this issue since there is nothing else actionable from our side.
