### ISSUE TITLE
Use custom Elasticsearch configuration during tests

### ISSUE THREAD

**Issue by rvrignaud** [Shippable/support#903]
Hello,
My application needs to use a custom elasticsearch configuration for its tests.
I'm currently using builtin shipppable Elasticsearch service. 
Is this possible to push a specific configuration ? Is it also possible to add Elasticsearch plugin ?
If not do you know any workaround ? 

Thanks in advance,
Regards

**Comment by manishas** [comment]
@rvrignaud did the suggestion above work for you?

**Comment by rvrignaud** [comment]
Yes, that did the trick. Thanks

2015-01-05 20:06 GMT+01:00 Manisha <notifications@github.com>:

**Comment by manishas** [comment]
Thanks for the update!
Closing this issue.
