### ISSUE TITLE
[Consolidated] Git tags for deploys start new test

### ISSUE THREAD

**Issue by rogierslag** [Shippable/support#905]
We'd like to keep track of which code was running in production at which point in time. However, if our deploy script pushes a new tag to github this triggers a new build on shippable. Can we switch this off somehow? It kinda pollutes the overview and causes regular builds to hold

```
git tag "deploy_SOMEVAL"
git push --tags
```

**Comment by lukehutton** [comment]
+1 can we make building on tags configurable? I would like to tag the github repo with the build number if the build was successful. thanks.

**Comment by lukehutton** [comment]
Nevermind, I am able to tag the repository and a build is not initiated

    after_success:
      - git tag -a build-$BUILD_NUMBER -m "build-$BUILD_NUMBER"
      - git push --tags origin master

**Comment by joostverdoorn** [comment]
:+1: would be nice to only build unique git hashes.

**Comment by manishas** [comment]
This is also a request for Bitbucket - #1180

**Comment by manishas** [comment]
We need to add a project setting making this configurable.

**Comment by ryan-kimber** [comment]
It would be particularly useful if this was combined with [#693](https://github.com/Shippable/support/issues/693)

Configuring this in the project settings would be great, so shippable doesn't have to pull my branch/tag only to find out we don't want it built.

**Comment by manishas** [comment]
We have added a project setting so that you can configure whether your project should be built when you push a tag or create a release. 

![image](https://cloud.githubusercontent.com/assets/2983749/15169977/12e71c90-16f6-11e6-855a-e109b5391dc4.png)

This setting only works for GitHub projects as of now.

**Comment by abhijitkini** [comment]
Closing the issue as the ability to configure your project to be built on push a tag or create a release has been added to the project settings for GitHub

**Comment by tjomk** [comment]
@manishas @abhijitkini all Bitbucket tickers refer to this one, yet you have only added GitHub support. What's the state with BB?

**Comment by manishas** [comment]
https://github.com/Shippable/support/issues/2615 is now in progress so we're adding tags support for bitbucket.
