### ISSUE TITLE
docker push failed; 404 Client Error: Not Found ("No such container:

### ISSUE THREAD

**Issue by cekees** [Shippable/support#909]
I'm getting a failure I don't understand after enabling pushing to docker hub. I see multiple  `docker commit` and `docker push` steps in the output, and the container seems to get pushed successfully, but the `docker push` and `purge` steps nevertheless fail. Here are the relevant public project pages

https://app.shippable.com/projects/54976689d46935d5fbc0c457
https://github.com/cekees/testShippable
https://registry.hub.docker.com/u/cekees/testshippable

**Comment by manishas** [comment]
@cekees this is fixed now. Please let us know if you run into any problems. Thanks!

**Comment by yazgoo** [comment]
Hi,

I'm having a similar problem: 
https://app.shippable.com/projects/549439afd46935d5fbc0a9cf/builds/latest
with docker push, I get: ` No such container`
and with purge, I get ` response from daemon: No such id`
Is this related ?

Thanks

**Comment by moylop260** [comment]
Hi,

I'm having the same problem here:
https://app.shippable.com/builds/54c2bed37119a70d008881cb

![shippable_borrar](https://cloud.githubusercontent.com/assets/6644187/5884235/97257844-a320-11e4-8f83-7f14f0e22951.jpg)

**Comment by moylop260** [comment]
@manishas 
I have the same problem now.
Is fixed?

**Comment by moylop260** [comment]
@manishas 
Fix it with button "reset" from shippable view

**Comment by manishas** [comment]
Yes, please reset your dedicated host to get this fix. Closing this issue...
