### ISSUE TITLE
Dedicated Host on OSX

### ISSUE THREAD

**Issue by chriskinsman** [Shippable/support#917]
I want to run a dedicated host on an inhouse machine to build iOS / Android apps.  I can't seem to find any instructions on how to setup a dedicated host on osx.  Thanks!

**Comment by manishas** [comment]
@chriskinsman Avi told me you're planning to meet him in the next couple of days, so I guess you can discuss this with him :)

I'll leave this open for a follow up after your talk.

**Comment by chriskinsman** [comment]
Sounds good.

**Comment by apobbati** [comment]
are there any plans to add support for building mobile apps (osx and android)?

**Comment by manishas** [comment]
Tracking all additonal platform requests in #457. Closing this issue as a duplicate.

Currently, our immediate roadmap does not include iOS. However, customers do successfully run android builds by installing the SDK on the minions. For example https://github.com/eyedol/kasahorow-Keyboard-For-Android/blob/master/shippable.yml

```    - sudo apt-get install -u lib32stdc++6 lib32z1```
