### ISSUE TITLE
 git_sync fails with branch named `shippable`

### ISSUE THREAD

**Issue by mpscholten** [Shippable/support#920]
The `git_sync` step fails with the following message when you are testing a branch named `shippable`:
```
git checkout -f shippable
error: pathspec 'shippable' did not match any file(s) known to git.
Build completed
Skipping artifact upload
Build completed
```

When you push the same commit to another branch (`git checkout -b someotherbranch && git push origin someotherbranch`) it works.

**Comment by manishas** [comment]
this is fixed now. closing this issue... please feel free to re-open if it doesn't work.

**Comment by thiagonache** [comment]
Hi there,

I'm yet facing this problem.

Thank you.

Best,

Nash
