### ISSUE TITLE
Problem with git sync when using custom image

### ISSUE THREAD

**Issue by apeiniger** [Shippable/support#921]
We are using our own custom docker image and dedicated host. When running some builds we get the following error. Looks like there is some misconfiguration with the git client.

![bildschirmfoto_2014-12-30_um_13_19_57](https://cloud.githubusercontent.com/assets/2005574/5578421/255061c2-9027-11e4-9d80-3daed73ad255.png)

Any ideas on how we could resolve that?

**Comment by apeiniger** [comment]
Is this already fixed?

**Comment by manishas** [comment]
@apeiniger yes this has been fixed. Please re-open this issue if you run into this again. Thanks!!
