### ISSUE TITLE
Submodule and SSH keys

### ISSUE THREAD

**Issue by bassamtabbara** [Shippable/support#923]
It would be great if shippable automatically added is "shippable_production" SSH keys to submodules within a repo. The scenario is as follows:

Repo A has submodule Repo B
Log into Shippable with Github Credentials
Enable Repo A

Actual: Build Fails since shippable has no access to Repo B
Expected: Build success.

I should mention that both repos are private in this scenario

**Comment by mavarazy** [comment]
The file is no longer there, and no clear explanation available, of where to find it.

**Comment by manishas** [comment]
new link is - http://docs.shippable.com/project_settings/#git-submodules

At this point, we support this manually. I am closing this issue but if we get enough requests for automation in this area we'll take another look at it.
 Thanks!
