### ISSUE TITLE
Add support for a shell scripts

### ISSUE THREAD

**Issue by bassamtabbara** [Shippable/support#924]
Please add support for shell scripts builds. I.e. in shippable.yml language is set to "bash" or "shell". Also would be great for there to be a generic base image with no services and language runtimes installed. I tried using shippableimages/ubuntu_base but that was not supported. Finally, having an icon for the generic image in your web UI would be great, as it stands the default is the ruby gem icon.

**Comment by caarlos0** [comment]
+1

this is supported by travis, for example...

as a workaround, I'm using the ruby image.

**Comment by avinci** [comment]
I think the best solution would be to use python as the language as we native ubuntu python and nothing gets started or stopped. Closing this as its possible today and we are moving away from programming languages with the evolution of Docker
