### ISSUE TITLE
Sometimes the projects under shippable builder disappears

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#925]
We are working in a team, and for some members shippable does not show any projects or repos. And this happens randomly to any of the member. Is it an issue with permission or something else ?

**Comment by pwhitey86** [comment]
@manishas I am on the same team as Phagun and I have the same issue. I ensured I have Private Repos On. Please see screen shot below.

![screen shot 2015-01-02 at 10 14 06 am](https://cloud.githubusercontent.com/assets/5240409/5598289/9381e3da-9268-11e4-8514-7795a356c60f.png)

**Comment by manishas** [comment]
@phagunbaya @pwhitey86 this is pretty strange. we'll take a look asap. thanks!

**Comment by manishas** [comment]
@phagunbaya we have revamped our permissions and this should not be happening any more. please re-open if you are still running into this.
