### ISSUE TITLE
Any way to get timestamp with built console output

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#926]
Is there any way to get the timestamp with console output during built time ? The problem is sometimes built take a longer than expected (even longer than an hour. Our tests output have a time stamp so they are not the culprit. If we get the console output with timestamp, we can find the abnormal condition.

**Comment by phagunbaya** [comment]
@manishas Thanks !

**Comment by manishas** [comment]
We print the amount of time it took for each step in the console. You should be able to find any abnormalities with this.

Timestamps would make the console too busy, so we're not going to do this in the near future unless there are several +1s for it.
