### ISSUE TITLE
Do not allow credit card information to be deleted while on a paid plan.

### ISSUE THREAD

**Issue by dataferret** [Shippable/support#927]
Not wanting to leave a credit card in the system, I removed it after paying for a year. No warnings. Nothing. It just downgrades the account immediately back to free, while I'm still charged.

This is quite an unusual way of doing payments. Usually system activation is detached from invoicing/active cc's.

**Comment by dataferret** [comment]
@manishas on a personal front, thank you for the restoration. I'll let you close or leave this open if you need it to address the underlying issue.  Cheers.

**Comment by manishas** [comment]
@dataferret I will leave this open. We will either disable deleting card information while you are on a paid plan (like GitHub does) or warn that deleting the card will result in downgrading your plan. As I said, there isn't much control we have over this since we use a third party payment provider to create and track subscriptions.

**Comment by nabla-c0d3** [comment]
Hi,
The same thing happened with my account. I don't mind putting the card back but will I be charged again?
Thanks

**Comment by manishas** [comment]
@nabla-c0d3 yes if you add the card and upgrade to startup plan again, you will be charged again. 

However this is necessary to get back to the startup plan. Please let me know which org you upgraded and we can issue a refund if the same org was upgraded twice. 
Thanks!

**Comment by nabla-c0d3** [comment]
I just re-enabled my plan and got charged again. Can I get a refund for the following organization: datatheorem ?
Thanks!

**Comment by manishas** [comment]
@nabla-c0d3 I'll let you know as soon as the refund is issued.

**Comment by manishas** [comment]
@nabla-c0d3 This should have been refunded. 

We've changed the experience around removing cards, so closing this issue.
