### ISSUE TITLE
Using custom build image *without* dedicated hosts

### ISSUE THREAD

**Issue by bassamtabbara** [Shippable/support#929]
Hi,

It would be great if you can enable the use of custom build images *without* requiring dedicated hosts. Today, I'm able to use shippable/minv2 and then apt-get install a number of packages to customize it, including installing build tools and such. If I wanted to use the same packages and build tools across repos then my options are:

1. share the scripts and tools within the source repository (i.e. a scripts submodule or just repeat portions in shippable.yml).
2. Use a custom docker build image and use a dedicated host.

(1) pollutes the source repository with a lot of build stuff that I'd like to avoid. Also for new projects that want to use these build scripts its harder to get going quickly.

It would be great if we can relax (2) to just "Use a custom docker build image". Using a dedicated host would become necessary only in cases where I want my on-premise hosts.

I can understand your desire to keep build images that you host locked down. I would think that running a non-privileged container would achieve this. If the concern is load on your servers then its not much different from using one of you images and then apt-get installing something that uses up many resources. Also for the latter you can limit resource usage using LXC if needed (which you might already be doing).

From a business model standpoint, I'm OK with upgrading to a paid account when using custom images. I just don't want to manage build machines. 

With this feature my flow becomes:
1. Use your base images to create a new custom build image and push it to docker hub.
2. User our custom build image for all other projects. 

Thanks for listening and happy new year!
Bassam

**Comment by manishas** [comment]
@bassamtabbara we will introduce some new ways to use Shippable in the near future that should address your scenario. Please stay tuned for a few announcements soon :)

**Comment by bassamtabbara** [comment]
@manishas thanks. looking forward to it.

**Comment by rogierslag** [comment]
Same here!

**Comment by blakeblackshear** [comment]
Have these new ways been introduced? Did I miss something?

**Comment by andruby** [comment]
Hi guys,

I would love to get an update on this too. Right now, our builds waste a lot of time installing dependencies that don't change often (npm, ember-cli, etc). With a custom build image we could include those dependencies in the image.

**Comment by rarkins** [comment]
+1 to hearing if this is really supported too. Some of the announcements make it *sound* like it's supported but I haven't found any documentation or examples to confirm it.

**Comment by manishas** [comment]
Yes, custom images for CI are supported with or dedicated hosts now. Documented at http://docs.shippable.com/docker_registries/
