### ISSUE TITLE
Please add support for shippableimage/ubuntu1404_base

### ISSUE THREAD

**Issue by bassamtabbara** [Shippable/support#931]
This is currently not supported in shippable.yml and is useful in scenarios where none of the language runtimes are needed.

**Comment by avinci** [comment]
@bassamtabbara do you have a DockerFile for this. I can easily add this if you. 

One Q for you. Ee  plan is to let the community drive images as we don't want to be the bottleneck. Do you think thats a good idea?

**Comment by bassamtabbara** [comment]
Thanks @avinci. This Dockerfile would work for now https://github.com/shippableImages/ubuntu1404_base/blob/master/Dockerfile

Having the community drive images sounds like a great plan. If you just relaxed the rules around build_image today you could achieve that, i.e. any image on docker hub is supported (even private images). #929 has some more thoughts on this.

I'm enjoying using your product. Keep up the good work!

**Comment by manishas** [comment]
@bassamtabbara we are working on this and will have one available in the next day or two. I will update when it's done. Thanks!

**Comment by pmoust** [comment]
same as well. Need to be able to run tests in a private docker container and then use your commit functionality to push on docker hub.

**Comment by pmoust** [comment]
@manishas thanks for hooking me  up with your product, I met you guys at Dockercon. Seems that we 'll be using it once few things are pushed forward.

**Comment by rageshkrishna** [comment]
Folks, `shippableimages/ubuntu1204_base` and `shippableimages/ubuntu1404_base` are now available.

**Comment by pmoust** [comment]
:clap:

**Comment by bassamtabbara** [comment]
thanks!

**Comment by manishas** [comment]
Closing.
