### ISSUE TITLE
Deploy to DO

### ISSUE THREAD

**Issue by davidsoderberg** [Shippable/support#933]
Hi, I am totaly newbie on this so please have that in mind :smile: 
I have made an shell script: 
```
#!/bin/bash

user=$1
host=$2

ssh $user@$host -- "
  set -e
  cd /
  cd /var/www/
  git pull origin master
"
```
How can I make this work with shippable?

_Many thanks/
David_

**Comment by avinci** [comment]
Are you using containers? if so we are actually releasing a new deploy piece in the next couple of weeks.. We can also add SSH piece into it if not.

The approach you are taking might be a bit more work than this. Your git command won't work as your DO host will not be trusted by Github, unless you create keys there and then move this script to DO box and call it....over SSH

You could also do it with SCP then it will try to move all the files over every single time. I am thinking if there is any other way that is better....Let me think about it..

**Comment by davidsoderberg** [comment]
Containers?

But I do this today on another ci saas.
I have an no password key I add to the ci and then I pull from github on DO.
Github and DO is connected with an ssh key. And Github trust DO.

Think about it and I did not understand what is coming up in two weeks.

**Comment by avinci** [comment]
Yes, if DO is trusted by github you can do it. But you need this script file on the DO machine and trigger it over SSH. Can you share, what CI provider you are able to do this remotely?

You can supply user and password through ENV vars and if you don't want it open, you can encrypt it too.

we are coming up with a deploy agent, that will allow you do deploys automatically without the manual stuff.

**Comment by davidsoderberg** [comment]
Absolutly snap-ci.
Could you please give me an code example on how I use ENV vars?

Alright that sounds exciting :smile:

**Comment by avinci** [comment]
I would first take the deployment key thats on your subscription page and add it to the authorized_keys of DO machine. This will allow shippable minion to connect to DO. Then I would make the following changes to your YML

```
env:
  global:
    - DO_USER=foo DO_HOST=8.8.8.8

after_success:
  - eval `ssh-agent -s`
  - ssh-add
  - ssh $DO_USER@$DO_HOST -q ~/deploy/do_machine_git_script.sh
```

Note: the shell script should be on your remote machine not on shippable CI minion.

Let me know if this works...

**Comment by davidsoderberg** [comment]
How do I add an key to authorized_keys ?

**Comment by avinci** [comment]
if you got `.ssh` folder on your user home directory, you will see a file, if not create a file called `authorized_keys` and stick the public key there.....

**Comment by davidsoderberg** [comment]
Just copy and paste?

**Comment by avinci** [comment]
yup

**Comment by davidsoderberg** [comment]
Ok

**Comment by davidsoderberg** [comment]
On snap-ci I can have int on snap-ci server, why can I not that on shippable?

**Comment by avinci** [comment]
you mean integer? maybe we can get on a hangout call and I can help you out...

**Comment by davidsoderberg** [comment]
No I am on my cellphone, I did edit my post above :smile:

**Comment by davidsoderberg** [comment]
I will try to make my post above a bit more clear :smile: 

I have a sh file in my github repo with the content I wrote in my first post.
I have an ssh key on DO and snap-ci. Then DO trust snap-ci.
I also have an ssh key beteewen DO and Github, so I can pull from Github on Do.

On snap-ci I run my deploy with this command: 
```bash ./deploy.sh $REMOTE_USER $REMOTE_HOST```

```$REMOTE_USER``` and ```$REMOTE_HOST``` are defined on snap-ci.
When I push the deployment are done.

How can I do this on Shippable?

**Comment by manishas** [comment]
@davidsoderberg we have a post describing how to deploy to DO - http://docs.shippable.com/en/latest/continuous_deployment.html#continuous-deployment-to-digitalocean

I will also loop in someone from the team to follow up with you to help make this work.

**Comment by davidsoderberg** [comment]
I do not want to use capistrano then I need to install ruby on rails also. I want a simple deployment flow like I have on snap-ci.

**Comment by anowak** [comment]
@davidsoderberg I guess the confusion about adding the key to `.ssh/authorized_keys` arisen from the fact that you used [DigitalOcean control panel](https://cloud.digitalocean.com/ssh_keys) to configure your keys. Just add the Shippable key, available on your account configuration panel, through the DO web console. This in fact has the same effect eventually, i.e. the `.ssh/authorized_keys` gets modified.

Now, you have two possibilities while handling DO->GitHub authorization. The first one is to add the DO SSH key as a deploy to your GitHub repository. This is how I believe you set up your snap-ci flow and should work just fine with Shippable as well, i.e. your script would not need any modification. Just please remember to **not** include these lines in your `shippable.yml` in this scenario:

     - eval `ssh-agent -s`
     - ssh-add

What these two lines do is to tell SSH to use the same keys also on the target machine (DO droplet in our case). This is so called *ssh forwarding*. If you want to use this feature, then you have one key less to manage, but then you need to add the Shippable key as a deploy key to your Github repository, not the one found on the droplet.

I hope that it made it a little bit more clear. Please let me know if you still experience this problem.

**Comment by manishas** [comment]
@davidsoderberg can you please let us know if your issue was resolved by the comment above?

**Comment by manishas** [comment]
Closing since the question was answered. Please let us know if we can help with anything else.

**Comment by davidsoderberg** [comment]
Ok i will give Shippable one more try, how can I deploy to a DO machine without capistrano?
the only thing I whant to do on my DO machine is git pull. How can I do that?
