### ISSUE TITLE
Build failing in container purge

### ISSUE THREAD

**Issue by apeiniger** [Shippable/support#934]
Some of our builds are failing because of the last purge step. We are using a dedicated host with our custom image.

![bildschirmfoto_2015-01-02_um_09_58_52](https://cloud.githubusercontent.com/assets/2005574/5594968/3679d76c-9266-11e4-9f71-3556399ed1f4.png)

A "docker ps -a" on the dedicated host shows that the container is stopped but still there.

Could this be a bug?

**Comment by manishas** [comment]
We'll take a look and get back to you soon. thanks!

**Comment by ragsden** [comment]
@apeiniger Sorry about the issue. We had upgraded our build agent and for some reason your host machine's build containers were not up to date. I have re-initialized your host and now the builds are passing. Thanks.

**Comment by apeiniger** [comment]
Awesome, thanks
