### ISSUE TITLE
Timeouts for builds

### ISSUE THREAD

**Issue by apeiniger** [Shippable/support#935]
We are getting timeouts for the builds in the last hours. Can you check e.g. build 54a69716bfd85e0f0025584b ? It hangs after the scripts have run. Any idea?

**Comment by manishas** [comment]
@apeiniger are you still seeing this issue? sorry for the delay!

**Comment by apeiniger** [comment]
It seems fixed now, thanks

**Comment by apeiniger** [comment]
There seems to be a similar problem now, can you check build 54aa423a82dbf00e003f7c3d?

**Comment by manishas** [comment]
We're looking into this now.

**Comment by manishas** [comment]
@apeiniger we're pushing a fix for this issue very soon. Stay tuned for an update. 
Thanks!

**Comment by manishas** [comment]
@apeiniger this should be fixed now and you shouldn't see it again. Please re-open if you do. Thanks!!
