### ISSUE TITLE
Cannot build a project with private dependencies

### ISSUE THREAD

**Issue by austinsmorris** [Shippable/support#936]
Is there anyway to upload a private key for my minions to use?  If not, I don't see any way I can build a private project that has private dependencies.  Since GitHub only allows a key to be used once, the single deploy key you provide per organization doesn't cut it.  

With other CI solutions (Travis), I'm able to upload a private key, which is then tied a machine user in GitHub (or GitLab) that has access to all the private dependencies.

Is there a workaround available?  Without this, Shippable does not work for me at all.

**Comment by austinsmorris** [comment]
Ha, nevermind, I can just use that deploy key with a machine user to give me all the access I need.

**Comment by fabiocarneiro** [comment]
@austinsmorris what did you mean with machine user? Github only accepts the same key once and when i tried to add the same key to more than 1 dependency repo, it didnt allow me.

**Comment by austinsmorris** [comment]
I was thinking about it backwards.  Instead of wanting to upload a private key to shippable, I just need to upload my shippable public key to GitHub.

**Comment by fabiocarneiro** [comment]
@austinsmorris ok, but were did you set it? your personal account? i would like to set the key in organization level, but you can't assign the same key in more than one place in github, so i cant use the shippable public key to each private dependency I have.

**Comment by avinci** [comment]
@fabiocarneiro one thing you could do is create an account on github that has permissions to all the dependencies and then add shippable SSH key to it as an authorized key. this should solve it.

longer term, I think we need to give you a way to add deploy keys to all your dependencies from our UI so that we can generate a unique key for you.

**Comment by fabiocarneiro** [comment]
@avinci I tried to add it to my personal account and re-run the test task but it failed again. In my github account it says the key was never used. Do you know if i have to do something else?

Also the per-repository deployment key would do the job.

**Comment by avinci** [comment]
@fabiocarneiro my bad, i think we create per repo key internally and use that to connect to your repo. I think sub level keys are available on the minions. Lets me get back to you...

+1 on the github feature and though we were doing this in the past, there was a lot of concern by users about security in terms of using a single key....

**Comment by fabiocarneiro** [comment]
I removed the previous comment since i found that my composer.lock was making composer download dependencies from bitbucket instead of github.
