### ISSUE TITLE
Empty cache from web interface / Clean rerun of build

### ISSUE THREAD

**Issue by apeiniger** [Shippable/support#938]
Is it possible to re-run the build from the web interface with cleaning the cache at the same time? A lot of time we forget to put the reset minion command into the commit.

**Comment by manishas** [comment]
@apeiniger currently, no. I am going to track this as a feature request.

**Comment by manishas** [comment]
Dup of #829. This is on our radar now.

**Comment by manishas** [comment]
This is now available through our UI in Project Settings -

![screen shot 2015-07-30 at 9 58 27 am](https://cloud.githubusercontent.com/assets/2983749/8989568/c1afe24c-36a1-11e5-96a0-cf35a36aefc7.png)
