### ISSUE TITLE
git submodule init/update with private repos

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#939]
Main repo has multiple git submodules pointing to public and private repos.

The `ssh-agent add` seems to not hold the proper key to allow check out of private repos through ssh. It is just ran on the initial clone.

The subsequent git submodule calls fail due to that.

**Comment by pmoust** [comment]
For your internal reference a failing build demonstrating this behaviour is 54aa63df76c5440e00d33388

**Comment by rageshkrishna** [comment]
@pmoust For multiple private submodules to work you'll need to add the Deployment Key you find on your subscription's page to a GitHub user account. We have a more detailed explanation at http://blog.shippable.com/demystifying-shippables-deployment-keys. I hope this helps.

**Comment by pmoust** [comment]
@rageshkrishna thank you. I'd prefer it if it was a per repo setting however.
