### ISSUE TITLE
Build failed although everything ran through smoothly

### ISSUE THREAD

**Issue by apeiniger** [Shippable/support#941]
Can you check build 54aa8d1642798d110054235d

There are green marks everywhere but still the status is failed.

**Comment by rageshkrishna** [comment]
Thanks for pointing this out. I believe this may be a UI issue. Your builds is actually throwing an error at the "saving coverage reports" stage but the UI doesn't seem to mark this as a failed step correctly. We'll sort this out soon.

**Comment by manishas** [comment]
@apeiniger this should be fixed now so am closing this issue. Please let me know if we can help with anything else.
