### ISSUE TITLE
UI/UX enhancement: update head title with something meaningful

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#942]
Operating in multiple tabs tends to be annoying when the head>title does not contain useful info.

In this example multiple tabs with different builds are open, yet it is not possible to distinguish which is what.

![screenshot 2015-01-05 15 59 29](https://cloud.githubusercontent.com/assets/2493339/5613934/fb249f2c-94f3-11e4-9183-874b3e78115e.png)

Would be very nice to have the information available at a glance (i.e. Repo name / # ID)
Extra candy would be to update the DOM with the build status.

**Comment by manishas** [comment]
@pmoust this is a great suggestion. We'll work on this soon :)

**Comment by avinci** [comment]
this has been implemented
