### ISSUE TITLE
Authentication is required

### ISSUE THREAD

**Issue by prabeshshrestha** [Shippable/support#945]
![shippable](https://cloud.githubusercontent.com/assets/538544/5660010/254ab628-971b-11e4-8955-e9d2ad8171b6.png)

I am using the default image provided by shippable. Still I get authentication required error.

**Comment by rageshkrishna** [comment]
We've identified that this is happening on one of our minion hosts. We're looking in to this. I'll update this issue as soon as I have more details.

**Comment by rageshkrishna** [comment]
@prabeshshrestha You shouldn't be seeing this any more. Please let me know if you're still running in to this.

**Comment by manishas** [comment]
Closing since this is not happening with the latest builds any more.
