### ISSUE TITLE
Could not find the python package installed, import package failures

### ISSUE THREAD

**Issue by adamyao** [Shippable/support#949]
I installed a bunch of python packages, and see the message says they are installed successfully: 

Successfully installed Babel Jinja2 MarkupSafe PyYAML amqp anyjson backports.ssl-match-hostname billiard boto celery certifi couchbase coverage futures iso8601 kombu netaddr nose oslo.config pbr prettytable python-heatclient python-keystoneclient python-swiftclient pytz requests simplejson six stevedore tornado
Cleaning up...

But testcases python code run failed because of failed to import the package:

ImportError: No module named jinja2

The python search path is seen from sys.path:
['', '/home/shippable/build_ve/python/2.7/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/home/shippable/workspace/src/github.com/lithiumtech/cloudops-skybase-core', '/home/shippable/build_ve/python/2.7/lib/python2.7', '/home/shippable/build_ve/python/2.7/lib/python2.7/plat-linux2', '/home/shippable/build_ve/python/2.7/lib/python2.7/lib-tk', '/home/shippable/build_ve/python/2.7/lib/python2.7/lib-old', '/home/shippable/build_ve/python/2.7/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/home/shippable/build_ve/python/2.7/lib/python2.7/site-packages']

I have tried a few build images:  default, ubuntu120,  and shippableimages/ubuntu1404_python, all have the same import error.

**Comment by adamyao** [comment]
I mean ubuntu 1204

**Comment by manishas** [comment]
@adamyao can you paste a link for a specific build that has this issue? Thanks!

**Comment by manishas** [comment]
@adamyao I am closing this issue, but please do re-open if you are still running into this.

On a separate note, I see your last successful build was on Thursday, so can we help with the recent build failures? Let me know... manisha@shippable.com
