### ISSUE TITLE
Donwload with 0 bytes whith msg "The console log is too large to be displayed. You can download it instead."

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#951]
If you build show a message with:
`The console log is too large to be displayed. You can download it instead.`

And press download button:
![descarga 1](https://cloud.githubusercontent.com/assets/6644187/5688912/7bc1de20-9822-11e4-954d-6c42abb335f9.png)

Now you have a empty file downloaded with 0 bytes.

**Comment by manishas** [comment]
@moylop260 we're taking a look. thanks!

**Comment by manishas** [comment]
@moylop260 this is due to an issue with mongoose driver for MongoDB, see https://github.com/LearnBoost/mongoose/issues/2423 opened by us. We will track this and try to push for a resolution soon.

**Comment by manishas** [comment]
@moylop260 are you still running into this?

**Comment by manishas** [comment]
Closing this issue. @moylop260 please re-open if this is still happening for you.
