### ISSUE TITLE
Multiple dedicated hosts with common IP: Punching through firewall/NAT

### ISSUE THREAD

**Issue by taqtiqa-mark** [Shippable/support#953]
Hi, I'd like to know if you have tested, or are aware of users successfully using ngrok to connect to multiple dedicated hosts sharing an IP address of the host.

Related issues are;
#839 @ragsden Establishes that Shippable : 
- needs general outbound access
- needs SSH access to `<subdomain>.ngrok.com:<number>`

#837 Establishes that Shippable can (since 6-Dec-2014) utilize multiple dedicated hosts with same IP and different ports.

The question arises when combining #839 and #837.  That is, multiple dedicated hosts on the same IP adderess behind firewall/NAT:
- Does Shippable require SSH access via a port that is dedicated to each dedicated host...?

That is, in the example in #837, I would set up ngrok to tunnel TCP traffic as follows:
````
mysubdom.ngrok.com:10122 -> 1.1.1.1 port 10122
mysubdom.ngrok.com:10222 -> 1.1.1.1 port 10222
````

**Comment by manishas** [comment]
@taqtiqa-mark shippable no longer requires SSH access to dedicated hosts. You can set up the hosts by downloading our scripts and running them yourself.

Details here - http://docs.shippable.com/ci_subscriptions/#adding-your-own-build-infrastructure-byoh
