### ISSUE TITLE
heroku deploy stopped working

### ISSUE THREAD

**Issue by gilderman** [Shippable/support#955]
git remote -v | grep ^heroku || heroku git:remote --app $APP_NAME
ERROR: Incomplete credentials detected, git may not work with Heroku. Run `heroku login` to update your credentials. See documentation for details: https://devcenter.heroku.com/articles/http-git#authentication
Build completed
Skipping artifact upload
Build completed

I changed api key, encrypted again, checked localy, still get the same error

**Comment by manishas** [comment]
Does the solution proposed by @rageshkrishna in https://github.com/Shippable/support/issues/863 work for you?

Please let me know. If it doesn't work we will investigate further asap.

**Comment by gilderman** [comment]
Did not help after upgrading to cedar 14

**Comment by manishas** [comment]
Sorry I should have been more specific.... this is the comment - 

t looks like something changed with the way Heroku deals with Git authentication. Can you please try adding `--ssh-git` to your `heroku git:remote` command? The full command should now look like this:

````
git remote -v | grep ^heroku || heroku git:remote --ssh-git --app $HEROKU_APP_NAME
````

This should get you around the `Incomplete credentials detected, git may not work with Heroku.` error.

**Comment by manishas** [comment]
Closing this issue. Please re-open if the suggestion above didn't help.
