### ISSUE TITLE
push to a private docker registry

### ISSUE THREAD

**Issue by arypurnomoz** [Shippable/support#956]
Is there any way to push to a private docker registry?

**Comment by manishas** [comment]
@arypurnomoz as of today, no. we're working on this so watch for some key announcements soon :)

**Comment by jtmarmon** [comment]
This is supported through shell though right? Like I can run `docker login` and `docker push` during the `after_success` stage?

**Comment by cep21** [comment]
Ping.  Can I get an update on this as well?  Being able to create and push docker images after a build is a requirement for CI, and I like all the other features of Shippable.  I tried doing this through shell.  My config looked like

    install:
      - curl -sSL https://get.docker.com/ | sudo sh

    after_success:
      - docker info

And I get the error:

time="2015-03-04T22:01:32Z" level="fatal" msg="Get http:///var/run/docker.sock/v1.17/info: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS?"

**Comment by MrNerdHair** [comment]
Ping! I need this feature as well. I intend to pair Shippable's docker build capability with the Amazon EC2 Container Service, but I need a private registry since it's a commercial product.

**Comment by adamkdean** [comment]
Circle CI don't integrate with Bitbucket. Shippable doesn't allow private registries. My list continues, so far every CI solution only offers a part of the puzzle. Please add this in. You were so close guys!

**Comment by jtmarmon** [comment]
> My list continues, so far every CI solution only offers a part of the puzzle. 

this is the most true sentence I've read all year

**Comment by Nalum** [comment]
Just adding my vote to this.

**Comment by rsslldnphy** [comment]
Me too - this is what's stopping us going with Shippable at the moment.

**Comment by avinci** [comment]
this is coming very soon. Please stay tuned

**Comment by cosmicnag** [comment]
+1

**Comment by topiaruss** [comment]
12 Jan:   "some key announcements soon :)"

Today: Nada!

It makes no sense for me to use Shippable CI/CD without private registry push.

**Comment by manishas** [comment]
@topiaruss you're right, we should have included private registry access in our latest release and it was simply due to lack of time that we decided to ship without it.

This is on our roadmap as an important feature request since we also heard this requirement from a lot of folks at Dockercon. 

As for an ETA, we're shooting for 7/20. I'll make sure we announce it in this thread as soon as it's available. Thanks!!

**Comment by topiaruss** [comment]
Thanks for coming back, @manishas. Sometime this month would be great. I'll be looking out for it!
--r

**Comment by manishas** [comment]
We're trying to consolidate support issues, so I'm tracking the issue of adding support for quay.io and private docker registries in issue #800

Please follow that issue for updates (as promised, we'll have updates in the next 2-3 weeks).

**Comment by manishas** [comment]
This is now available! You can push and pull images from Quay.io as well as private docker registries.

Check out our docs at http://docs.shippable.com/docker_registries/

Let me know if you have any questions.... feedback much appreciated :)

**Comment by topiaruss** [comment]
Thanks for the notification.
—r
> On 13 Jul 2015, at 17:04, Manisha <notifications@github.com> wrote:
> 
> This is now available! You can push and pull images from Quay.io as well as private docker registries.
> 
> Check out our docs at http://docs.shippable.com/docker_registries/ <http://docs.shippable.com/docker_registries/>
> Let me know if you have any questions.... feedback much appreciated :)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Shippable/support/issues/956#issuecomment-120980862>.
> 

Russ Ferriday -- Software Product Architect, Developer, Mentor
CEO Topia Systems Ltd.
russf@topia.com  --  +44 7429 518822
