### ISSUE TITLE
pip install egg from other private github repository fails

### ISSUE THREAD

**Issue by sveitser** [Shippable/support#958]
I've added our organizations shippable deploy key to the github repo in question, but the authentication doesn't succeed.

```
Obtaining ambi-utils from git+ssh://git@github.com/ambilabs/ambi_utils.git#egg=ambi_utils (from -r install/pip_requirements.txt (line 21))
  Cloning ssh://git@github.com/ambilabs/ambi_utils.git to /root/ve/src/ambi-utils
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
  Complete output from command /usr/bin/git clone -q ssh://git@github.com/ambilabs/ambi_utils.git /root/ve/src/ambi-utils:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git clone -q ssh://git@github.com/ambilabs/ambi_utils.git /root/ve/src/ambi-utils failed with error code 128 in None
Storing debug log for failure in /root/.pip/pip.log
```

Is it possible the deploy key of the repository is used for this ```git clone``` command?

**Comment by rageshkrishna** [comment]
@sveitser Sorry we lost track of this. Is this still happening? Can I get a project or build ID so I can see what's going on? Thanks!

**Comment by manishas** [comment]
@sveitser ping... can we get a build id so we can take a look?

**Comment by sveitser** [comment]
I haven't tried it out since. 

Here's one of the failing builds https://app.shippable.com/builds/54b4d036b2360f0e00f13d55

**Comment by manishas** [comment]
@sveitser Sorry for the long delay! I think you've disabled the project now. Please let me know if we can help figure out what's going wrong.

**Comment by manishas** [comment]
Closing this issue since there is no response. Please re-open if you want us to help debug.
