### ISSUE TITLE
Code climate coverage integration

### ISSUE THREAD

**Issue by wrousseau** [Shippable/support#959]
Dear Shippable team,

I'm currently trying to set up code climate's coverage reporting into shippable. Our repository is hosted on Github by the organization GroupEat and its name is groupeat-hybrid-mobile. I have I believe followed the instructions correctly, as my test script generates a file in

    `coverage/lcov/PhantomJS/lcov.info`

Our shippable.yml looks like this

    language: node_js
    env:
        -CODECLIMATE_REPO_TOKEN=[My Code climate repo token]
    node_js:
        - "0.10.26"
    before_script:
        - npm install -g bower
        - bower install
        - source ~/.rvm/scripts/rvm && rvm use 1.9.3
        - gem install compass
        - npm install -g grunt-cli
        - grunt init
    after_script:
        - npm install -g codeclimate-test-reporter
        - codeclimate < coverage/lcov/*/lcov.info

Obviously, I've hidden my code climate repo token. I'm also using the path `coverage/lcov/*/lcov.info` because `lcov.info` is located within a directory whose name is platform dependent.

I am getting this error, which does not make the build fail but it seems like coverage data is not sent properly to code climate because of it :

    codeclimate < coverage/lcov/*/lcov.info
        /home/shippable/build/build.sh: eval: line 85: syntax error near unexpected token `('
        Build completed
        Skipping artifact upload
        Build completed

If you have any idea on what is wrong with what I'm doing or if there is a better way to work with Code Climate and Shippable, it would be great !

Best regards

**Comment by rageshkrishna** [comment]
@wrousseau Can you please share the lcov outputs from your build? Your YML is fine and I can't think of any reason for this not to work. I can quickly debug this if I can get your `lcov.info` files. You can send them to ragesh@shippable.com. Thanks!

**Comment by wrousseau** [comment]
Thank you for your quick answer. I've sent the file to the email address you provided. 

Best regards

**Comment by manishas** [comment]
Tracking all code coverage issues in https://github.com/Shippable/support/issues/174
