### ISSUE TITLE
shippable does not resync repos correctly if there is an org rename

### ISSUE THREAD

**Issue by daniel-garcia** [Shippable/support#961]
username: daniel-garcia
repo: stackengine/app

We renamed our org from StackEngine to stackengine. Now, shippable does not want to sync our repo correctly and tries to clone github.com/StackEngine/app which does not exist.

**Comment by ragsden** [comment]
@daniel-garcia, Syncing of repos happen periodically and hence you are seeing this lag.
The issue got corrected in your last 2 builds. Git sync is now happening on stackengine/app.
Please let me know if you have any questions.

**Comment by daniel-garcia** [comment]
Thanks.
