### ISSUE TITLE
Beanstalk with docker

### ISSUE THREAD

**Issue by kimpellikaan** [Shippable/support#963]
Hi Guys,

In the documentation you describe how to deploy your build based on a predefined standard package. I was wondering if you have a guide how to deploy based on a docker file.

Kim

**Comment by manishas** [comment]
@kimpellikaan we recently introduced Docker build support and have documented how to use this feature - http://blog.shippable.com/making-deployments-even-easier-with-docker-build

Please re-open this issue if it doesn't address your scenario.

**Comment by kimpellikaan** [comment]
@manishas anishas, my issue is about beanstalk docker builds. That is something completely different then what your feature is about.

Kim
