### ISSUE TITLE
Clarification on the function of 'cache'

### ISSUE THREAD

**Issue by jtmarmon** [Shippable/support#964]
In the docs, there is an option to cache builds (`cache: true`). Does this mean my docker images will be cached? I use 3 linked docker images in my production topology (redis, mongo, and the app).  Will the app be cached as well, or just redis and mongo? Should I `git pull` and run that code as a volume to prevent the entire app from running from cached?

**Comment by zanona** [comment]
I also have a similar question, how does shippable know what to cache?
How is it possible to distinguish what is a dependency and what is a code to be tested?
For example, for my node js applications everything inside node_modules is a dependency however for web apps I also use bower or volo which have different locations inside my project where dependencies are downloaded. So in case, shippable keeps everything cached, I'm afraid that the next git clone would simply delete all dependencies which were previously downloaded wouldn't it?

I have been using a few other CI providers and there is a `$PROVIDER_CACHE` env path which is persisted across builds, so, as long as something is deployed to that location it can be re-used later on. 
In such cases, it is possible set that as the dependency home and symlink those dependencies into my project.

However, I am not completely sure on what is the logic behind Shippable's cache as well?

**Comment by manishas** [comment]
Caching is explained here - http://docs.shippable.com/project_settings/#cache-container
