### ISSUE TITLE
SSH key for custom deployments

### ISSUE THREAD

**Issue by jtmarmon** [Shippable/support#965]
Is there a way for me to add an SSH key to my minion so that I can deploy with a custom deployment script to my servers?

**Comment by jtmarmon** [comment]
My current solution is encrypting an ssh key, adding that to the repo, passing the encryption key as a secure env var and then decrypting the ssh key at deploy time. however, this seems like a lot of work lol

**Comment by rageshkrishna** [comment]
We generate a key pair for your subscription (see the "Deployment Key" in the right side of the page when you visit your organization page on Shippable). Would it be possible for you to add that key to your target machines instead? The key is written to `~/.ssh/id_rsa` for each build so it'll "just work" if your machines trust our key.

**Comment by jtmarmon** [comment]
ah yes that would have been simpler. I ended up going with a self-hosted system (jenkins) but good to know
