### ISSUE TITLE
How to bypass auto gradle action?

### ISSUE THREAD

**Issue by txchen** [Shippable/support#966]
Hi, our project has a build.gradle in the root folder. However we cannot directly invoke gradle to build it, instead, we need to run some custom shell script to do the build.

May I know how do we tell shippable not to invoke gradle, even if it found build.gradle?

Thanks a lot!

**Comment by rageshkrishna** [comment]
@txchen I apologize for not getting back to you sooner on this. If you don't specify anything in the `install` or `script` sections of your YML file we will inject some default commands based on the project's language. If you want to override this, all you have to do is add your commands to the YML file, like so:

````
install:
 - ./runMyCustomInstallSteps.sh

script:
 - mvn whateverYouWantToDo
````

I hope this helps.

**Comment by txchen** [comment]
Thanks @rageshkrishna , I actually figured out myself.

Now my biggest hope is that shippable can support custom docker image build. Now the docker feature does not look good because I don't want to pack my entire source repo into the image.
