### ISSUE TITLE
how does docker hub integration work?

### ISSUE THREAD

**Issue by txchen** [Shippable/support#967]
The document just mentioned "commit_container: username/sample_project" but may I know more details behind it?

Like:
* Do you use dockerfile to build image?
* If so, which dockerfile?
* Can I use customscripts to build docker image?
* Can I specify docker image tag before pushing?

**Comment by manishas** [comment]
@txchen sorry for the delay in responding. Right now, the flow is this - you can specify an image you want to use for your builds in the yml -
build_image: <docker_hub_username>/<image_name>

When you change source code, we pull your image from docker hub, source code from github, create an application container, and run tests in it. If everything passes, you can use the commit_container tag to push the application container back to docker hub.

We are making major enhancements to this in the next couple of weeks, so please watch for an announcement.
