### ISSUE TITLE
build is timing out

### ISSUE THREAD

**Issue by amobrem** [Shippable/support#968]
When I switched build image:

build_image: shippableimages/ubuntu1404_nodejs

**Comment by amobrem** [comment]
works fine with the default image...

**Comment by manishas** [comment]
@amobrem can you try adding a -y to the sudo apt-get install step? Please let me know if that works.

**Comment by amobrem** [comment]
Thanks that seemed to worked.

**Comment by manishas** [comment]
Thanks for confirming!
