### ISSUE TITLE
Activating private GitHub repositories does not sync organizations repositories

### ISSUE THREAD

**Issue by severinedarlot** [Shippable/support#972]
The public GitHub repositories are activated. I needed to see a private repositories shared with other team members. I clicked the "Private repos On" logo on the top right corner, authenticated with GitHub, accepted the authorizations, and nothing... I could not see the builds of the private project we were sharing. I had to click on the corresponding organization on the right, click the "sync repos"  button on the top and then the builds are displayed on the dashboard.

I had to look around before finding the "sync repos" button. It would be better if the repositories were synced as soon as we enable private repositories.

**Comment by manishas** [comment]
@severinedarlot we sync automatically periodically but you have a great point. I will add this to our feature list.

**Comment by manishas** [comment]
This should work now. closing.
