### ISSUE TITLE
dedicated host: cancelled builds do not stop and remove test containers

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#973]
dedicated host: cancelled builds do not stop and remove test containers.

Cancelling a bunch of builds results in their private image test containers running with jobs on.

This spikes our load hugely.

**Comment by manishas** [comment]
@pmoust thanks for the feedback. We'll take a look at why this is happening.

**Comment by pmoust** [comment]
Closing since dedicated nodes are deprecated.
