### ISSUE TITLE
Shippable container failing to boot

### ISSUE THREAD

**Issue by andersonbn** [Shippable/support#974]
Hi,

Shippable is intermittently failing to boot the default container image after a git push to bitbucket. I noticed that this problem only occurs when I set *cache* to *true*.
You can see a failed build on this link: https://app.shippable.com/builds/54b80c3a4051091100defc16

![screen shot 2015-01-15 at 15 21 55](https://cloud.githubusercontent.com/assets/535893/5766926/a17a9452-9cca-11e4-87b1-420690722754.png)

Thanks!

**Comment by manishas** [comment]
@andersonbn we'll take a look at this and get back to you. Thanks!

**Comment by andersonbn** [comment]
Hi,

I'm also having a similar problem. This time it happens even when I'm not using caching. See image bellow.
![screen shot 2015-01-26 at 13 27 58](https://cloud.githubusercontent.com/assets/535893/5906710/5fcc8108-a55f-11e4-8229-312cf3d77fd7.png)

**Comment by manishas** [comment]
@andersonbn I see all your latest builds are green. Is this still happening?

**Comment by andersonbn** [comment]
Hi Manisha,

 It's probably going to happen again, if I enable the build cache.

**Comment by manishas** [comment]
@andersonbn I am closing this issue. Please re-open if you see this again (even after enabling cache)
