### ISSUE TITLE
no space left of device??? really

### ISSUE THREAD

**Issue by gilderman** [Shippable/support#975]
Warning, new version of rvm available '1.26.9', you are using older version '1.26.8'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/12.04/x86_64/ruby-2.1.2.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
You are running low on disk space 110MB, required 100MB.
ruby-2.1.2 - #configure
ruby-2.1.2 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  6 21.2M    6 1327k    0     0  1708k      0  0:00:12 --:--:--  0:00:12 1849k
100 21.2M  100 21.2M    0     0  13.2M      0  0:00:01  0:00:01 --:--:-- 13.7M
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.1.2 - #validate archive
ruby-2.1.2 - #extract
mkdir: cannot create directory `/home/shippable/.rvm/rubies/ruby-2.1.2': No space left on device
mktemp: failed to create directory via template `/home/shippable/.rvm/tmp/rvm-tmp.XXXXXXXXX': No space left on device
mkdir: cannot create directory `': No such file or directory
tar: : Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

**Comment by byterussian** [comment]
Similar issue on git clone for me:
```
fatal: cannot create directory at 'app/assets/images/thumbs': No space left on device
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by manishas** [comment]
We're taking a look at what's going on...

**Comment by rogierslag** [comment]
![screenshot 2015-01-16 01 19 58](https://cloud.githubusercontent.com/assets/2778689/5769583/d8437636-9d1d-11e4-8048-099096170f6a.png)

Same here, happens randomly :(

**Comment by manishas** [comment]
This was fixed the same day. Please let me know if you're still running into this.

Sorry about the failed builds. We're adding monitoring for this so it will not happen again.

**Comment by caarlos0** [comment]
Hi, just happened to me. :cry:

**Comment by avinci** [comment]
@caarlos0 I checked all our machines. We have ample space. Can you check again? Also are you running custom hosts?

**Comment by caarlos0** [comment]
@avinci oh, sure, forgot what I said..
