### ISSUE TITLE
/home/shippable/wrk/boot.sh: no such file or directory

### ISSUE THREAD

**Issue by nzin** [Shippable/support#981]
Hi,

I'm evaluating shippable.com, and build a node js "hello world" application
After exporting it as a docker file, I tried to run it:
docker run nzin/nodetest:master.10.1
2015/01/17 01:11:39 exec: "/home/shippable/wrk/boot.sh": stat /home/shippable/wrk/boot.sh: no such file or directory

I open the docker image, the /home/shippable/wrk directory is here but I didn't found the boot.sh executable.
Is it a bug from me, or a bug in the your build process?

Thanks,

Nicolas

**Comment by rageshkrishna** [comment]
Our build uses `/home/shippable/wrk/boot.sh` as the `entrypoint` on the docker image when we launch a build to ensure that our build script runs on boot. Unfortunately, this gets embedded in the image configuration when we commit the container and create an image. As a result, when you say `docker run nzin/nodetest:master.10.1`, it tries to run boot.sh again.

You can get around this by forcing an entrypoint in your docker run command. For example, `docker run --entrypoint /bin/bash nzin/nodetest:master.10.1`

I hope this helps.

**Comment by nzin** [comment]
Ok,

so what should I do to  have nodejs starting when I run my docker image?
I should had a new entry point?

Thanks,

**Comment by rageshkrishna** [comment]
@nzin Yes, just replace `/bin/bash` in the command below with whatever you need to do to launch your application:

````
docker run --entrypoint /bin/bash nzin/nodetest:master.10.1
````

**Comment by manishas** [comment]
Closing this issue since its answered. Please let us know if we can help further.
