### ISSUE TITLE
Configuration to run builds in queue for a project

### ISSUE THREAD

**Issue by phagunbaya** [Shippable/support#983]
Right now if any changes are pushed to git repo, built is triggered on shippable and runs in parallel. I want to configure it in such a way that for a project it should run a built at a time and rest triggered builds should wait in queue. Any way to do this ?

**Comment by manishas** [comment]
@phagunbaya there is currently no way to stop a triggered build from starting on an available minion. Can you explain your scenario in a bit more detail so we can figure out if this is a common requirement?

**Comment by phagunbaya** [comment]
The scenario is : 
Pre-requisite :
1. Common database for storage (hosted by user)
2. Sample data set (for running data manipulation tests)

Case : If a build is triggered and is running tests on the data set and in between if other build starts (for the same project) then, both may fail because they use same database storage and they have same data set on which all tests run.

**Comment by manishas** [comment]
This is now possible with the new build platform, so marking implement.

This should be a project setting for 'run builds sequentially' that is false by default.

**Comment by manishas** [comment]
@phagunbaya this is now available as a project setting. If you go to the Settings tab for your project and scroll to the 'Run parallel jobs' section, you'll see a button to `Disable` parallel builds. You can even set it at a branch level in cases where you only want builds from specific branches to run in sequence.

Docs are updated here - http://docs.shippable.com/ci_projects/#run-parallel-jobs

**Comment by phagunbaya** [comment]
Thanks for the update.

**Comment by manishas** [comment]
👍
