### ISSUE TITLE
Skipped/incomplete tests are not correctly parsed

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#984]
![screenshot 2015-01-19 10 52 31](https://cloud.githubusercontent.com/assets/2493339/5797823/1e3d1702-9fc9-11e4-9708-eb4c40da2f6c.png)

While in reality it's:
```
FAILURES!                                                                         
Tests: 376, Assertions: 3279, Failures: 6, Errors: 10, Incomplete: 9, Skipped: 26.
```

PHPUnit is ran with `--log-junit shippable/testresults/junit.xml --coverage-xml shippable/codecoverage` as  per docs.

Also I am under the impression that code coverage yields  a bigger percentage than it should.

Reference build: 54bcb89466407b0d00b67869

**Comment by rageshkrishna** [comment]
@pmoust Would it be possible for you to share your test and coverage result files with me at ragesh@shippable.com? This will help me repro this quickly and figure out what's going on. Thanks!

**Comment by pmoust** [comment]
@rageshkrishna should have hit your mailbox ;)

**Comment by manishas** [comment]
@pmoust @rageshkrishna any update on this?

**Comment by rageshkrishna** [comment]
I'm looking at it right now :)

**Comment by pmoust** [comment]
@manishas @rageshkrishna thank you

**Comment by manishas** [comment]
@rageshkrishna do you have an update on this?

**Comment by manishas** [comment]
closing this issue since there is no update on this for a long time. @pmoust @rageshkrishna please feel free to re-open if this isn't resolved
