### ISSUE TITLE
Initialising a new Dedicated Host performs multiple provisioner runs

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#985]
After adding a dedicated host and hitting `Initialize` your provisioning scripts are run twice on the target host.
This results in dedicated host being mark as failed (because apt db is locked) and creating a spike in load as `dd` and `mkswap` are run twice till one fails.

This is reproducible consistently.

**Comment by pmoust** [comment]
The work around is to keep the Host running, remove it from Shippable Dedicated Host UI, add it back and re-initialize.
It will find no dependency missing, swap is there and is being activated, containers are spawned and Host init is marked as "success".

**Comment by pmoust** [comment]
That said, in the documentation it states 2 worker containers should be running, we get 4. But this doesn't seem to be an issue for us.

**Comment by manishas** [comment]
@pmoust we are working on some improvements to dedicated hosts which should light up in the next few days. I will add this to the list of changes. Thanks!

**Comment by manishas** [comment]
Actually, it was already on the list. I will update you when its in.

**Comment by gavinheavyside** [comment]
I've just seen this too, the biggest issue was swap creation. At one point I had 5 processes all running `dd if=/dev/zero of=/home/shippable/_sh_swap_ bs=1M count=15039`, overwriting each others outputs. initializing worked eventually, but it wasn't a smooth process and there were lots of errors in the logs along the way.

**Comment by velo** [comment]
Saw the same!

**Comment by manishas** [comment]
This has been fixed. Please re-open if it doesn't work for you.
