### ISSUE TITLE
Capybara, Poltergeist and missing fonts

### ISSUE THREAD

**Issue by byterussian** [Shippable/support#986]
Hi,

my integration tests running fine locally but on CI server fail cause lack of fonts, there is a way to fix this problem?

**Comment by rageshkrishna** [comment]
You have full sudo access on the minions so you should be able to install any fonts you need as you normally would on your local machine.

**Comment by manishas** [comment]
@byterussian I am closing this issue since ragesh has provided a solution. please feel free to re-open if this doesn't work for you or you have further questions.

Thanks!
