### ISSUE TITLE
Ability to link containers on a dedicated host

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#987]
I would like us to be able to link containers (in a Fig manner) via shippable.yml while on a Dedicated Host.

We are migrating for a monolithic app to a microservices model, and for our CI needs to have this feature.

Docker-in-docker is not an easy option for us as -still- some issues are not resolved on Dockers side.

**Comment by manishas** [comment]
@pmoust Can we do a google hangout later this on wednesday or thursday? We are working on some features that will be interesting to you, but I want to better understand your scenario. Let me know what time works for you.

**Comment by pmoust** [comment]
@manishas sure. Set up a google invite and I will RSVP.

**Comment by pmoust** [comment]
Hello, is there an ETA for this feature request?
It would be helpful if you released a roadmap so we know if it makes sense for us to create a temporary solution that will fit our needs or if we could wait for such feature release.

Sidenote: if you chose to opensource part of your engine I am sure a lot of us could contribute

**Comment by pmoust** [comment]
Relates: https://github.com/Shippable/support/issues/1030

**Comment by jchamberlain** [comment]
Echoing the request for an ETA. Is this actually in the works? I would be willing to pay extra for this feature.

**Comment by manishas** [comment]
We've addressed this through Shippable Formations - http://blog.shippable.com/introducing-shippable-formations-devops20-for-dockerized-apps

Please sign up for a demo to see how it works - https://shippable.youcanbook.me/

@jchamberlain if you believe Formations does not work for you, please send me an email at manisha@shippable.com and we can set up a call to discuss further.
