### ISSUE TITLE
Cannot hit my node server during my integration tests

### ISSUE THREAD

**Issue by sguimont** [Shippable/support#989]
I run a node application on locahost:3000 then I run a suite of test that try to send HTTP request to the localhost:3000, but  I always got this error:
```
Error: connect ECONNREFUSED     
   at errnoException (net.js:904:11)
   at Object.afterConnect [as oncomplete] (net.js:895:19)
```
But when I ran locally on my computer everything works perfectly.

Here's the build number with failing tests : 54bd98e368606e0e0056d09c

Do I need to use special port for testing? or special configuration?

Thanks.

**Comment by rageshkrishna** [comment]
@sguimont Our samples do the same thing and we haven't seen any issues with node apps not starting up. Can you share your Gruntfile and package.json with me at ragesh@shippable.com? I'd like to try and reproduce exactly what your build is trying to do to see if there are any issues. Thanks!

**Comment by manishas** [comment]
@sguimont I am closing this issue, but please feel free to re-open if you still need help with this. Thanks!
