### ISSUE TITLE
Support of user-hosted git repos or GitLab

### ISSUE THREAD

**Issue by drakmail** [Shippable/support#99]
Subj.

**Comment by geshan** [comment]
any plans on doing a full native support for gitlab with things like builds on pull request as well?

**Comment by koryonik** [comment]
+1 for Gitlab support.

**Comment by Borales** [comment]
+1 
it's almost a year since the first comment..
Is there any update about this?

**Comment by zkanda** [comment]
Update on this please, I have my repos in Gitlab.

**Comment by manishas** [comment]
Closing as dup of https://github.com/Shippable/support/issues/45. All requests for integration with source control providers will be tracked there.

**Comment by mfilotto** [comment]
+1 for Gitlab support

**Comment by hzkochhar** [comment]
+++++
look at all the repos not getting the shippable love.
oh why so silent shippable team?

**Comment by abhijitkini** [comment]
We are pleased to announce Shippable support for GitLab. Here's the [blog announcement](http://blog.shippable.com/getting-started-gitlab-with-shippable-ci). Our [docs](http://docs.shippable.com/int_scm/#gitlab) are updated too.

**Comment by manishas** [comment]
Just to clarify - GitLab is available as an integration, so you will still need to sign in to Shippable with GitHub or Bitbucket and then add Gitlab repositories for CI. 

Supporting GitLab auth is on our near term roadmap.

**Comment by DavidMont** [comment]
+1
