### ISSUE TITLE
Team member left, pulls now fail from team repositories

### ISSUE THREAD

**Issue by catskul** [Shippable/support#990]
A team member left who originally set up the account, and we recently disconnected his bitbucket account from the team account. Immediately after this the builds are now failing with:
```
conq: repository access denied.
fatal: Could not read from remote repository.
```

I'm assuming the issue is that the account was relying on his auth to the team repo (bitbucket)

I've groped around the interface and docs attempting to find a way to reauth, but have found no solution so far.

example failing build:
https://app.shippable.com/builds/54bf38bd24bcec0e0059e75b

**Comment by rageshkrishna** [comment]
I think what would have happened is that BitBucket would have deleted all the deploy keys that were added to the repository by the user that got removed.

We currently don't have a way to refresh the authorization keys on the project. The easiest way is to delete the project from Shippable and enable it again.

**Comment by catskul** [comment]
@rageshkrishna if I'm not mistaken that means I'd lose all previous data from the project. Is that correct?

If that's the case, this solution is pretty stark.

I'm not sure I have anything critical that I couldn't stand to lose, but I'd much prefer a non-destructive solution.

**Comment by catskul** [comment]
I couldn't wait and ended up deleting and re-adding the project in an attempt to get testing working again with no success:

````
Obtaining raven-python from git+git@bitbucket.org:hireanesquire/raven-python.git@hae_custom#egg=raven_python (from -r dependencies.conf (line 58))
  Cloning git@bitbucket.org:hireanesquire/raven-python.git (to hae_custom) to /home/shippable/build_ve/python/2.7/src/raven-python
conq: repository access denied.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
  Complete output from command /usr/bin/git clone -q git@bitbucket.org:hireanesquire/raven-python.git /home/shippable/build_ve/python/2.7/src/raven-python:
````

I see that the repo in question has a shippable deployment key that was original put in place on 2014-06-05 and has not changed.

I'm not sure where that key came from, but I imagine it could possibly have been associated with the mentioned user and was deleted on the shippable side when he was removed from the team.

Thoughts?

**Comment by ragsden** [comment]
Sorry about that. I was in the middle of responding to the issue. 
Currently on Shippable there are project ssh key and subscription ssh key. The project ssh key is used repo related git operations (in this case the repo is HAE). In the build logs I see that you are cloning hireanesquire/raven-python.git repo and for this to happen, you have to give subscription ssh key access to the repo. This can be done by either adding the ssh key to the team or to the user who has access to this repo. Please let me know if you have any questions.

**Comment by ragsden** [comment]
If you want to do a googe hangout, feel free to reach out to me at raghu@shippable.com

**Comment by catskul** [comment]
It appears that the current shippable key is associated with the former team members bitbucket account.

Since the deploy key is associated with the bitbucket organization rather than the project, the deployment key was not regenerated on project delete and recreate.

Since it's not reasonable to try and delete and recreate my organization on bitbucket, regenerating the key on the shippable side seems to be a necessity.

**Comment by catskul** [comment]
I'll have to follow up with you tomorrow. I've run out of time for the evening.

**Comment by manishas** [comment]
@catskul what time works for you tomorrow and what's your email? I'll set up a call.

**Comment by catskul** [comment]
Attempts to add the subscription key produce the error from bitbucket:

"Someone has already registered that SSH key"

I assume this is because the ssh key was added to the team member who left's account.

It would appear that unless I can re-gain access to that team member bitbucket account. I'm stuck.

**Comment by catskul** [comment]
@manishas 10 am EST work?

**Comment by ragsden** [comment]
@catskul : I have generated a new deployment key and updated your subscription. Please add this key to the team's ssh keys instead of the user's ssh keys. I hope this resolves your build issue.
Let me know if you have any questions.

**Comment by catskul** [comment]
@ragsden I'm still having the same issue:

"Someone has already registered that SSH key"

The only thing I can figure is that you're referring to a different key than I'm using. The key I'm using is within the dashboard for the "Bitbucket Organization".

I might imagine that the subscription key would be available on the primary dashboard, but I see no deployment key there.

**Comment by ragsden** [comment]
@catskul: I will take a look at it and update you in couple of hours.

**Comment by manishas** [comment]
@catskul we're going to try one more thing at our end and let's do a hangout at 1pm EST if this issue persists until then. Hope that time works for you. 

Thanks for your patience! 

We're

**Comment by catskul** [comment]
@manishas any luck?

**Comment by ragsden** [comment]
@catskul : Are you available for Google hangout?

**Comment by ragsden** [comment]
I generated a new deploy key for the subscription and we were able to add the key to the team in Bitbucket. This resolved the access denied issue and the build ran successfully.
Thank you @catskul for your patience.
Closing the issue.
