### ISSUE TITLE
Build stuck on waiting

### ISSUE THREAD

**Issue by ownbite** [Shippable/support#991]
When played around with dedicated hosts today suddenly my builds are getting stuck on the waiting status. My server also got frozen, I restarted it but I could not get the builds to start. Even if I cancelled the builds and stated anew nothing seams to happen.

**Comment by manishas** [comment]
@ownbite can you paste a link to your build? Thanks!

**Comment by ownbite** [comment]
Ah sry, here it is.

https://app.shippable.com/builds/54c001d524bcec0e005a0f66

**Comment by manishas** [comment]
thanks. nothing changed in your shippable.yml, right?

Can you try the following - delete any builds that are running or waiting, then reset the host by clicking on 'Dedicated hosts' icon at the top right of your  profile (ownbite) and then clicking on Reset in the dialog that pops up.

Please let me know if this works.

**Comment by ownbite** [comment]
Have not changed anything in the .yml. 

Yes it worked, the dedicated server I had did not have enough power so it broke down. Now upgraded and it seams to work better.

**Comment by manishas** [comment]
Thanks for the update! I will close this issue for now, but please let me know if you need anything else.

We're working on improving the dedicated hosts backend so you will soon notice some improvements :)
