### ISSUE TITLE
Handling Github outages better

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#993]
Hi guys,
Github had a brief outage in parts of the services a few minutes ago.

Our logged in users were not able to list projects or check any build history during that time.

This is just a FYI you can close this ofc.

**Comment by spyrospph** [comment]
Hi Shippable,

We constantly get "No recent builds" and we can not track our builds. Please fix as this is unusable.

**Comment by manishas** [comment]
@pmoust thanks for reporting this. We do depend on GitHub for a lot of that data since we do not want to store redundant data on our side. We will find ways to address this better in future enhancements.

@spyrospph can you open up a new issue for this? Thanks!!
