### ISSUE TITLE
Codecoverage not parsed

### ISSUE THREAD

**Issue by Antronin** [Shippable/support#996]
Hi!

I have the following config in shippable.yml:
```
CI_REPORTS="shippable/testresults",COVERAGE_REPORTS="shippable/codecoverage"
```
During the run I see the followings in the output:
```
29 tests, 53 assertions, 0 failures, 0 errors, 0 skips
Writing XML reports to /root/workspace/src/bitbucket.com/***/***/shippable/testresults
Coverage report generated for MiniTest to /root/workspace/src/bitbucket.com/***/***/shippable/codecoverage. 194 / 212 LOC (91.51%) covered.
Build script completed
```
Still at the end it only shows the test results but not the coverage report:
```
 parse_coverage_reports
No coverage reports to parse.
 parse_test_reports
Test reports successfully parsed.
 save_test_reports
Test reports saved.
```
Can you tell me what am I doing wrong and how to fix to have correct coverage report parsing?

**Comment by manishas** [comment]
we're looking into this now.. thanks!

**Comment by Antronin** [comment]
Hi manishas,

Any news about the problem?

**Comment by rolandpoulter** [comment]
Antronin,
Can you tell me what language your project is using and what code coverage tools it uses please?

**Comment by Antronin** [comment]
Hi Roland,

Sure. I'm Using Ruby (RoR specifically) and I'm using Minitest with
SimpleCov.
My config in test/test_helper.rb is below:
```
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
include ActionDispatch::TestProcess
require 'rails/test_help'
require 'simplecov'
require "minitest/reporters"
Minitest::Reporters.use! [
  Minitest::Reporters::DefaultReporter.new,
  Minitest::Reporters::JUnitReporter.new(reports_dir =
"shippable/testresults")]
SimpleCov.coverage_dir('shippable/codecoverage')
SimpleCov.start 'rails'

class ActionController::TestCase
    include Devise::TestHelpers
end

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical
order.
  #
  # Note: You'll currently still have to declare fixtures explicitly in
integration tests
  # -- they do not yet inherit this setting
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

Roland Poulter <notifications@github.com> ezt írta (időpont: Wed Feb 04
2015 at 21:50:42):

Antronin,

**Comment by rolandpoulter** [comment]
Thanks Antronin.

I'm currently looking into this issue. I'll get back to you as soon as possible.

**Comment by juanlizarazo** [comment]
@Antronin I run into that last night. 
Your SimpleCov.start 'rails' must be placed before your require File.expand_path('../../config/environment', __FILE__). Therefore, all the requires of simplecov must be placed before as well.

```
This is my test_helper.rb

ENV["RAILS_ENV"] ||= "test"
ENV["COVERAGE_REPORTS"] ||= "shippable/codecoverage"

# Coverage report
require 'simplecov'
require 'simplecov-csv'

SimpleCov.formatter = SimpleCov::Formatter::CSVFormatter
SimpleCov.coverage_dir(ENV["COVERAGE_REPORTS"])
SimpleCov.start 'rails'

# Test helper

require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

# Rest of the file .... below

```

**Comment by Antronin** [comment]
@juanlizarazo thanx for your comment. Unfortunately it was not solving my problem directly. But because in your code seems not to use minitest formatters instead of  simplecov-csv, I started to review my own code.
Finally I solved: the minitest formatter provides JUnit output file format which seems not read by shippable.com's parser. In fact they stated to use Cobertura xml format in the support documents so changed my code to use simplecov-cobertura gem for this, and it is now finally working almost correctly, although it shows branch coverage as 0% alway, although sequence coverage is 100% in the same file. But that's another story.
Below is my code I use in test/test_helper.rb (using your suggestion too):
```ruby
ENV['RAILS_ENV'] ||= 'test'
ENV["COVERAGE_REPORTS"] ||= "shippable/codecoverage"

require 'simplecov'
require "minitest/reporters"
Minitest::Reporters.use! [
  Minitest::Reporters::DefaultReporter.new, 
  Minitest::Reporters::JUnitReporter.new(reports_dir = "shippable/testresults")]
SimpleCov.coverage_dir('shippable/codecoverage')
SimpleCov.formatter = SimpleCov::Formatter::CoberturaFormatter
SimpleCov.start 'rails'

require File.expand_path('../../config/environment', __FILE__)
include ActionDispatch::TestProcess
require 'rails/test_help'

class ActionController::TestCase
    include Devise::TestHelpers
end

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.yml for all tests in alphabetical order.
  #
  # Note: You'll currently still have to declare fixtures explicitly in integration tests
  # -- they do not yet inherit this setting
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```
