### ISSUE TITLE
Build information not found, for some of our organisation members

### ISSUE THREAD

**Issue by pmoust** [Shippable/support#997]
At frequent times our developers are not able to check the builds page (shows up a 'Build not found' error).
After some minutes they can again.

We 've tried logging in and out, clearing cookies and what not.

Reference build: https://app.shippable.com/builds/54c225e77119a70d00884c98

**Comment by spyrospph** [comment]
Hi shippable,

This is happening for a few days and is making your product extremely unusable.

If a build fails and build information is not shown on your site, our workflow is complete;y broken as the devs can not get any info on what broke.

Pls fix asap.

**Comment by aris-b** [comment]
This is really frustrating ... pls fix

**Comment by spirosoik** [comment]
Every time when I want to see the progress of my current build, shippable ui reports me "The build you're looking for wasn't found.". pls fix it

**Comment by manishas** [comment]
We have looked at why this is happening, and it's because some of your team members haven't given us access to private repositories.

If an org repository is private, anyone who wants to view build details will need to give Shippable permissions to access private github repos. You can do this by going to your dashboard and clicking on the 'Private Repos Off' button. 
![screen shot 2015-01-12 at 1 01 53 pm](https://cloud.githubusercontent.com/assets/2983749/5882635/10c75a58-a300-11e4-9cfb-4ca445148bb6.png)


This will take you to a GitHub page where you can accept the permissions and you will be able to see build results after that.

**Comment by manishas** [comment]
Please let me know if this works.

**Comment by pmoust** [comment]
@manishas thanks for taking a look. The issue is that we 've verified the devs have authorized already Shippable to access their private repos. 
They can view builds for some time, then they just cant, and then again after few minutes they can view the builds again.
We 've got over 5 people complaining about this.

Shot in the dark: Are you guys caching 'teams'/collaborator info from Github? Could that be it? I am the owner of the organization and I 've never had this issue with builds. All of our devs though are in teams under Github org that have different ACL per repo.

**Comment by manishas** [comment]
@pmoust the reason I asked about the permissions/access is that we found that we did not have private repo access for folks who are seeing this erratic behavior. There are some improvements we're making at our end to make it super consistent, but in the meantime, the way to getting it to work is to turn on private repo access.

Can you confirm that the icon for 'Private repos' on their dashboard is set to ON and is green? 

If so, we will definitely need to do a hangout.

**Comment by spyrospph** [comment]
Hi manisha,

We have done this but again this does not solve the issue.

Our private repos are on but our builds are not shown.

Free for a skype call to help troubleshoot this.

**Comment by spyrospph** [comment]
@manishas I had to sync repos and it worked.

**Comment by pmoust** [comment]
Closing for now. @manishas seems that people had to rsync as @spyrospph mentioned.
