### ISSUE TITLE
Screen with message "The build you're looking for wasn't found"

### ISSUE THREAD

**Issue by moylop260** [Shippable/support#998]
Hello,

I have a PR in a private repo.
![imp commission payment has landed to lodigroup by hbto pull request 94 vauxoo lodigroup](https://cloud.githubusercontent.com/assets/6644187/5884390/3d0598f6-a322-11e4-85a8-e56801be1886.png)

I have a shippable build: https://app.shippable.com/builds/54c2bed37119a70d008881cb
I see next screen:
![no wasnt found](https://cloud.githubusercontent.com/assets/6644187/5884336/a490d3d8-a321-11e4-985a-4934c4e518f1.png)

My user has permission into repo (because I have created PR) but I can't see my build.

Can you help me?

**Comment by pmoust** [comment]
Dup of https://github.com/Shippable/support/issues/997

**Comment by manishas** [comment]
@moylop260 we're talking a look at this now.

**Comment by manishas** [comment]
@moylop260 to confirm the scenario -

- You have enabled private repos on shippable. Can you confirm that the 'Private repos' icon on your dashboard is set to ON, i.e. green?
 
- You are trying to merge a PR and Shippable kicks off a build
- You click on the 'Details' link on PR page on GitHub
- You get a  'Build not found error' on Shippable

**Comment by moylop260** [comment]
Thank for you answer. 
Fix it
